Juniper: Juniper.Unity.Editor.JuniperEditorWindow Class Reference
Juniper.Unity.Editor.JuniperEditorWindow Class Reference
Protected Member Functions
Task RepaintAsync ()
JuniperEditorWindow (string title, bool startWatcher)
virtual void OnEditorUpdate ()
virtual void OnBackgroundUpdate ()
virtual void OnSelectionChanged ()
virtual void OnPaint ()
virtual void OnReset ()
bool Button (bool enabled, string title, Action act, params GUILayoutOption[] options)
bool Button (string title, Action act, params GUILayoutOption[] options)
bool Button (string title, params GUILayoutOption[] options)
Static Protected Attributes
static readonly GUILayoutOption availFieldWidth = Width(50)
static readonly GUILayoutOption shortLabelWidth = Width(75)
static readonly GUILayoutOption distFieldWidth = Width(100)
static readonly GUILayoutOption panoFieldWidth = Width(200)
static readonly GUILayoutOption latLngFieldWidth = Width(250)
Properties
Exception CurrentError [get, set]
Private Member Functions
void OnEditorUpdateInternal ()
void OnBackgroundUpdateInternal ()
void OnSelectionChangedInternal ()
void OnPaintInternal ()
void OnResetInternal ()
void OnGUI ()
void Init ()
void ClearError ()
void StartWatcher ()
void StopWatcher ()
void BackgroundThread ()
Private Attributes
readonly GUIContent windowTitle
readonly TaskFactory mainThread
readonly bool startWatcher
CancellationTokenSource tokenSource
CancellationToken cancelToken
Task watcherTask
Exception curError
Static Private Attributes
static readonly TableView errorView
Detailed Description
Definition at line 23 of file JuniperEditorWindow.cs.
Constructor & Destructor Documentation
JuniperEditorWindow()
Juniper.Unity.Editor.JuniperEditorWindow.JuniperEditorWindow (string title, bool startWatcher) inline protected
Definition at line 65 of file JuniperEditorWindow.cs.
         {
             windowTitle = new GUIContent(title);
             this.startWatcher = startWatcher;
             var scheduler = TaskScheduler.FromCurrentSynchronizationContext();
             mainThread = new TaskFactory(scheduler);
             EditorApplication.update += OnEditorUpdateInternal;
             Selection.selectionChanged += OnSelectionChangedInternal;
         }
References Juniper.Unity.Editor.JuniperEditorWindow.mainThread, Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdateInternal(), Juniper.Unity.Editor.JuniperEditorWindow.OnSelectionChangedInternal(), Juniper.Unity.Editor.JuniperEditorWindow.startWatcher, and Juniper.Unity.Editor.JuniperEditorWindow.windowTitle.
Member Function Documentation
BackgroundThread()
void Juniper.Unity.Editor.JuniperEditorWindow.BackgroundThread () inline private
Definition at line 280 of file JuniperEditorWindow.cs.
         {
             while (true)
             {
                 cancelToken.ThrowIfCancellationRequested();
                 OnBackgroundUpdateInternal();
             }
         }
References Juniper.Unity.Editor.JuniperEditorWindow.cancelToken, and Juniper.Unity.Editor.JuniperEditorWindow.OnBackgroundUpdateInternal().
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher().
Button() [1/3]
bool Juniper.Unity.Editor.JuniperEditorWindow.Button (bool enabled, string title, Action act, params GUILayoutOption [] options) inline protected
Definition at line 217 of file JuniperEditorWindow.cs.
         {
             using (new EditorGUI.DisabledScope(!enabled))
             {
                 return Button(title, act, options);
             }
         }
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
Button() [2/3]
bool Juniper.Unity.Editor.JuniperEditorWindow.Button (string title, Action act, params GUILayoutOption [] options) inline protected
Definition at line 225 of file JuniperEditorWindow.cs.
         {
             if (GUILayout.Button(title, options))
             {
                 act();
                 return true;
             }
             return false;
         }
Button() [3/3]
bool Juniper.Unity.Editor.JuniperEditorWindow.Button (string title, params GUILayoutOption [] options) inline protected
Definition at line 236 of file JuniperEditorWindow.cs.
         {
             return GUILayout.Button(title, options);
         }
ClearError()
void Juniper.Unity.Editor.JuniperEditorWindow.ClearError () inline private
Definition at line 247 of file JuniperEditorWindow.cs.
         {
             CurrentError = null;
         }
References Juniper.Unity.Editor.JuniperEditorWindow.CurrentError.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.Init(), and Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
Init()
void Juniper.Unity.Editor.JuniperEditorWindow.Init () inline private
Definition at line 241 of file JuniperEditorWindow.cs.
         {
             ClearError();
             OnSelectionChangedInternal();
         }
References Juniper.Unity.Editor.JuniperEditorWindow.ClearError(), and Juniper.Unity.Editor.JuniperEditorWindow.OnSelectionChangedInternal().
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI(), and Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher().
OnBackgroundUpdate()
virtual void Juniper.Unity.Editor.JuniperEditorWindow.OnBackgroundUpdate () inline protected virtual
Definition at line 94 of file JuniperEditorWindow.cs.
 { }
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnBackgroundUpdateInternal().
OnBackgroundUpdateInternal()
void Juniper.Unity.Editor.JuniperEditorWindow.OnBackgroundUpdateInternal () inline private
Definition at line 95 of file JuniperEditorWindow.cs.
         {
             if (JuniperSystem.IsMainThreadReady)
             {
                 OnBackgroundUpdate();
             }
         }
References Juniper.JuniperSystem.IsMainThreadReady, and Juniper.Unity.Editor.JuniperEditorWindow.OnBackgroundUpdate().
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.BackgroundThread().
OnEditorUpdate()
virtual void Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdate () inline protected virtual
Definition at line 77 of file JuniperEditorWindow.cs.
 { }
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdateInternal().
OnEditorUpdateInternal()
void Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdateInternal () inline private
Definition at line 78 of file JuniperEditorWindow.cs.
         {
             try
             {
                 if (!JuniperSystem.IsMainThreadReady)
                 {
                     JuniperSystem.EnsureFactory();
                 }
                 OnEditorUpdate();
             }
             catch (Exception exp)
             {
                 CurrentError = new Exception("Error occured during editor update", exp);
             }
         }
References Juniper.Unity.Editor.JuniperEditorWindow.CurrentError, Juniper.JuniperSystem.EnsureFactory(), Juniper.JuniperSystem.IsMainThreadReady, and Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdate().
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.JuniperEditorWindow().
OnGUI()
void Juniper.Unity.Editor.JuniperEditorWindow.OnGUI () inline private
Definition at line 149 of file JuniperEditorWindow.cs.
         {
             titleContent = windowTitle;
             if (!startWatcher)
             {
                 Init();
             }
             else
             {
                 if (watcherTask.IsRunning())
                 {
                     using (new HGroup())
                     {
                         LabelField("Watcher task running");
                         Button("Stop", StopWatcher, Width(75));
                     }
                 }
                 else if (watcherTask != null)
                 {
                     using (new HGroup())
                     {
                         if (watcherTask.IsCanceled == true)
{
                             LabelField("Watcher task canceled");
                         }
                         Button("Reset", OnResetInternal, Width(75));
                         Button("Start", StartWatcher, Width(75));
                     }
                     if (watcherTask != null
                         && watcherTask.IsFaulted == true
                         && CurrentError == null
                         && !(watcherTask.Exception.InnerExceptions.All(exp => exp is ThreadAbortException)))
                     {
                         CurrentError = new Exception("Error occured on background task", watcherTask.Exception);
                         watcherTask = null;
                     }
                 }
             }
             if (CurrentError != null)
             {
                 Button("Clear error", ClearError);
                 using (errorView.Begin())
                 {
                     var head = CurrentError;
                     while (head != null)
                     {
                         LabelField(head.Message);
                         LabelField(head.StackTrace, EditorStyles.wordWrappedLabel);
                         head = head.InnerException;
                     }
                 }
             }
             OnPaintInternal();
             if (startWatcher
                 && watcherTask == null
                 && CurrentError == null)
             {
                 StartWatcher();
             }
         }
References UnityEditor.TableView.Begin(), Juniper.Unity.Editor.JuniperEditorWindow.Button(), Juniper.Unity.Editor.JuniperEditorWindow.ClearError(), Juniper.Unity.Editor.JuniperEditorWindow.CurrentError, Juniper.Unity.Editor.JuniperEditorWindow.errorView, Juniper.Unity.Editor.JuniperEditorWindow.Init(), Juniper.Unity.Editor.JuniperEditorWindow.OnPaintInternal(), Juniper.Unity.Editor.JuniperEditorWindow.OnResetInternal(), Juniper.Unity.Editor.JuniperEditorWindow.startWatcher, Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher(), Juniper.Unity.Editor.JuniperEditorWindow.StopWatcher(), Juniper.Unity.Editor.JuniperEditorWindow.watcherTask, and Juniper.Unity.Editor.JuniperEditorWindow.windowTitle.
OnPaint()
virtual void Juniper.Unity.Editor.JuniperEditorWindow.OnPaint () inline protected virtual
Definition at line 116 of file JuniperEditorWindow.cs.
         { }
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnPaintInternal().
OnPaintInternal()
void Juniper.Unity.Editor.JuniperEditorWindow.OnPaintInternal () inline private
Definition at line 118 of file JuniperEditorWindow.cs.
         {
             try
             {
                 OnPaint();
             }
             catch (Exception exp)
             {
                 if (!exp.Message.StartsWith("Getting control"))
                 {
                     CurrentError = new Exception("Error occured during repaint", exp);
                 }
             }
         }
References Juniper.Unity.Editor.JuniperEditorWindow.CurrentError, and Juniper.Unity.Editor.JuniperEditorWindow.OnPaint().
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
OnReset()
virtual void Juniper.Unity.Editor.JuniperEditorWindow.OnReset () inline protected virtual
Definition at line 133 of file JuniperEditorWindow.cs.
         { }
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnResetInternal().
OnResetInternal()
void Juniper.Unity.Editor.JuniperEditorWindow.OnResetInternal () inline private
Definition at line 135 of file JuniperEditorWindow.cs.
         {
             try
             {
                 CurrentError = null;
                 watcherTask = null;
                 OnReset();
             }
             catch(Exception exp)
             {
                 CurrentError = new Exception("Error occured during reset", exp);
             }
         }
References Juniper.Unity.Editor.JuniperEditorWindow.CurrentError, Juniper.Unity.Editor.JuniperEditorWindow.OnReset(), and Juniper.Unity.Editor.JuniperEditorWindow.watcherTask.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
OnSelectionChanged()
virtual void Juniper.Unity.Editor.JuniperEditorWindow.OnSelectionChanged () inline protected virtual
Definition at line 103 of file JuniperEditorWindow.cs.
 { }
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnSelectionChangedInternal().
OnSelectionChangedInternal()
void Juniper.Unity.Editor.JuniperEditorWindow.OnSelectionChangedInternal () inline private
Definition at line 104 of file JuniperEditorWindow.cs.
         {
             try
             {
                 OnSelectionChanged();
             }
             catch (Exception exp)
             {
                 CurrentError = new Exception("Error occured during selection change", exp);
             }
         }
References Juniper.Unity.Editor.JuniperEditorWindow.CurrentError, and Juniper.Unity.Editor.JuniperEditorWindow.OnSelectionChanged().
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.Init(), and Juniper.Unity.Editor.JuniperEditorWindow.JuniperEditorWindow().
RepaintAsync()
Task Juniper.Unity.Editor.JuniperEditorWindow.RepaintAsync () inline protected
Definition at line 60 of file JuniperEditorWindow.cs.
         {
             return mainThread.StartNew(Repaint);
         }
References Juniper.Unity.Editor.JuniperEditorWindow.mainThread.
StartWatcher()
void Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher () inline private
Definition at line 252 of file JuniperEditorWindow.cs.
         {
             Init();
             try
             {
                 if (tokenSource != null)
                 {
                     tokenSource.Dispose();
                     tokenSource = null;
                 }
                 tokenSource = new CancellationTokenSource();
                 cancelToken = tokenSource.Token;
                 watcherTask = Task.Run(BackgroundThread, cancelToken);
             }
             catch (Exception exp)
             {
                 CurrentError = new Exception("Error occured while starting watcher", exp);
             }
         }
References Juniper.Unity.Editor.JuniperEditorWindow.BackgroundThread(), Juniper.Unity.Editor.JuniperEditorWindow.cancelToken, Juniper.Unity.Editor.JuniperEditorWindow.CurrentError, Juniper.Unity.Editor.JuniperEditorWindow.Init(), Juniper.Unity.Editor.JuniperEditorWindow.tokenSource, and Juniper.Unity.Editor.JuniperEditorWindow.watcherTask.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
StopWatcher()
void Juniper.Unity.Editor.JuniperEditorWindow.StopWatcher () inline private
Definition at line 275 of file JuniperEditorWindow.cs.
         {
             tokenSource.Cancel();
         }
References Juniper.Unity.Editor.JuniperEditorWindow.tokenSource.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
Member Data Documentation
availFieldWidth
readonly GUILayoutOption Juniper.Unity.Editor.JuniperEditorWindow.availFieldWidth = Width(50) static protected
Definition at line 29 of file JuniperEditorWindow.cs.
cancelToken
CancellationToken Juniper.Unity.Editor.JuniperEditorWindow.cancelToken private
Definition at line 40 of file JuniperEditorWindow.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.BackgroundThread(), and Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher().
curError
Exception Juniper.Unity.Editor.JuniperEditorWindow.curError private
Definition at line 43 of file JuniperEditorWindow.cs.
distFieldWidth
readonly GUILayoutOption Juniper.Unity.Editor.JuniperEditorWindow.distFieldWidth = Width(100) static protected
Definition at line 31 of file JuniperEditorWindow.cs.
errorView
readonly TableView Juniper.Unity.Editor.JuniperEditorWindow.errorView static private
Initial value:
= new TableView(
            "ERROR",
            ("Stack Trace", 300))
Definition at line 25 of file JuniperEditorWindow.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
latLngFieldWidth
readonly GUILayoutOption Juniper.Unity.Editor.JuniperEditorWindow.latLngFieldWidth = Width(250) static protected
Definition at line 33 of file JuniperEditorWindow.cs.
mainThread
readonly TaskFactory Juniper.Unity.Editor.JuniperEditorWindow.mainThread private
Definition at line 36 of file JuniperEditorWindow.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.JuniperEditorWindow(), and Juniper.Unity.Editor.JuniperEditorWindow.RepaintAsync().
panoFieldWidth
readonly GUILayoutOption Juniper.Unity.Editor.JuniperEditorWindow.panoFieldWidth = Width(200) static protected
Definition at line 32 of file JuniperEditorWindow.cs.
shortLabelWidth
readonly GUILayoutOption Juniper.Unity.Editor.JuniperEditorWindow.shortLabelWidth = Width(75) static protected
Definition at line 30 of file JuniperEditorWindow.cs.
startWatcher
readonly bool Juniper.Unity.Editor.JuniperEditorWindow.startWatcher private
Definition at line 37 of file JuniperEditorWindow.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.JuniperEditorWindow(), and Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
tokenSource
CancellationTokenSource Juniper.Unity.Editor.JuniperEditorWindow.tokenSource private
Definition at line 39 of file JuniperEditorWindow.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher(), and Juniper.Unity.Editor.JuniperEditorWindow.StopWatcher().
watcherTask
Task Juniper.Unity.Editor.JuniperEditorWindow.watcherTask private
Definition at line 41 of file JuniperEditorWindow.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnGUI(), Juniper.Unity.Editor.JuniperEditorWindow.OnResetInternal(), and Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher().
windowTitle
readonly GUIContent Juniper.Unity.Editor.JuniperEditorWindow.windowTitle private
Definition at line 35 of file JuniperEditorWindow.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.JuniperEditorWindow(), and Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
Property Documentation
CurrentError
Exception Juniper.Unity.Editor.JuniperEditorWindow.CurrentError get set private
Definition at line 45 of file JuniperEditorWindow.cs.
         {
             get
             {
                 return curError;
             }
             set
             {
                 curError = value;
                 if (value != null)
                 {
                     Debug.LogException(value, this);
                 }
             }
         }
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.ClearError(), Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdateInternal(), Juniper.Unity.Editor.JuniperEditorWindow.OnGUI(), Juniper.Unity.Editor.JuniperEditorWindow.OnPaintInternal(), Juniper.Unity.Editor.JuniperEditorWindow.OnResetInternal(), Juniper.Unity.Editor.JuniperEditorWindow.OnSelectionChangedInternal(), and Juniper.Unity.Editor.JuniperEditorWindow.StartWatcher().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Editor Scripts/JuniperEditorWindow.cs