Juniper: Juniper.Mathematics.SingleStatisticsCollection Class Reference
Juniper.Mathematics.SingleStatisticsCollection Class Reference abstract
Computes statistics on System.Single values.
Public Member Functions
SingleStatisticsCollection (IList< float > collection)
Initializes a new instance of the Juniper.Statistics.SingleStatistics class.
SingleStatisticsCollection (int capacity)
Create a RingBuffer of floats of a fixed size. RingBuffers aren't resizable. Statistical values default to null.
IEnumerator< T > GetEnumerator ()
Returns an enumerator that iterates through the collection.
void Add (T item)
Adds an item to the collection, and recalculates the statistical values.
void Clear ()
Clears the collection and resets the statistics to null.
bool Contains (T item)
Returns true if the give item is in the collection.
void CopyTo (T[] array, int arrayIndex)
Copies the elements of the collection to an Array, starting at a particular Array index.
bool Remove (T item)
Remove an item from the collection.
int IndexOf (T item)
Determines the index of the specified item in the underlying collection.
void Insert (int index, T item)
Insert an item at an arbitrary point in the collection.
void RemoveAt (int index)
Remove an item at the specified index from the collection.
bool Append (T value, int numStandardDeviations, int minSamples=2)
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Public Attributes
int Count
Returns the number of items in the collection.
bool IsReadOnly
Gets a value indicating whether this collection is read only.
T? Delta
The difference between the Maximum and Minimum
T? Median
The midpoint between the Maximum and the Minimum
Protected Member Functions
override float Abs (float value)
Performs Abs() on floats.
override float Add (float a, float b)
Performs Add on floats.
override float Divide (float a, float b)
Performs Divide on floats.
override bool LessThan (float a, float b)
Performs Less-Than on floats.
override float Multiply (float a, float b)
Performs Multiply on floats.
override float Scale (float a, float b)
Performs Scale on floats.
override float Sqrt (float value)
Performs Sqrt on floats.
override float Subtract (float a, float b)
Performs Subtract on floats.
abstract T Add (T a, T b)
Implementing classes can define how two values get added (because C# generics cannot specify operator constraints)
void RecomputeStatistics ()
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
void UpdateStatistics (T value)
Recalculate statistics that don't need to perform a full collection scan.
abstract T Subtract (T a, T b)
Implementing classes can define how two values get subtracted (because C# generics cannot specify operator constraints)
abstract T Multiply (T a, T b)
Implementing classes can define how two values get multiplied (because C# generics cannot specify operator constraints)
abstract T Scale (T a, float b)
Implementing classes can define how a value gets scaled by a scalar (because C# generics cannot specify operator constraints)
abstract T Divide (T a, float b)
Implementing classes can define how a value gets divided by a scalar (because C# generics cannot specify operator constraints)
abstract T Sqrt (T value)
Implementing classes can define how calculate the square root of a value (because C# generics cannot specify operator constraints)
abstract T Abs (T value)
Implementing classes can define how calculate the absolute value of a value (because C# generics cannot specify operator constraints)
abstract bool LessThan (T a, T b)
Implementing classes can define how two values get compared (because C# generics cannot specify operator constraints)
Properties
T? Maximum [get, private set]
The maximum value in the list, if there are any values in the list.
T? Minimum [get, private set]
The minimum value in the list, if there are any values in the list.
T? Mean [get, private set]
The arithmetic mean of the values in the list, if there are any values in the list.
T? Variance [get, private set]
The variance of all the values in the list, if there are any values in the list.
T? StandardDeviation [get, private set]
The standard deviation of all the values in the list, if there are any values in the list.
bool IsSaturated [get]
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
T this[int index] [get, set]
Gets or sets the element at the specified index.
Detailed Description
Computes statistics on System.Single values.
Definition at line 11 of file SingleStatisticsCollection.cs.
Constructor & Destructor Documentation
SingleStatisticsCollection() [1/2]
Juniper.Mathematics.SingleStatisticsCollection.SingleStatisticsCollection (IList< float > collection) inline
Initializes a new instance of the Juniper.Statistics.SingleStatistics class.
Parameters
collection Collection.
Definition at line 17 of file SingleStatisticsCollection.cs.
             : base(collection, 0, float.MinValue, float.MaxValue)
         {
         }
SingleStatisticsCollection() [2/2]
Juniper.Mathematics.SingleStatisticsCollection.SingleStatisticsCollection (int capacity) inline
Create a RingBuffer of floats of a fixed size. RingBuffers aren't resizable. Statistical values default to null.
Parameters
capacity
Definition at line 27 of file SingleStatisticsCollection.cs.
             : base(capacity, 0, float.MinValue, float.MaxValue)
         {
         }
Member Function Documentation
Abs() [1/2]
override float Juniper.Mathematics.SingleStatisticsCollection.Abs (float value) inline protected
Performs Abs() on floats.
Parameters
value
Returns
Definition at line 37 of file SingleStatisticsCollection.cs.
         {
             return Math.Abs(value);
         }
Abs() [2/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Abs (T value) protected pure virtual inherited
Implementing classes can define how calculate the absolute value of a value (because C# generics cannot specify operator constraints)
Parameters
value
Returns
Add() [1/3]
override float Juniper.Mathematics.SingleStatisticsCollection.Add (float a, float b) inline protected
Performs Add on floats.
Parameters
a
b
Returns
Definition at line 48 of file SingleStatisticsCollection.cs.
         {
             return a + b;
         }
Referenced by Juniper.World.CompassRose.SetNorth(), Juniper.Widgets.Shaker.Update(), and Juniper.Widgets.QualityDegrader.Update().
Add() [2/3]
void Juniper.Mathematics.AbstractStatisticsCollection< T >.Add (T item) inline inherited
Adds an item to the collection, and recalculates the statistical values.
Parameters
item
Definition at line 161 of file AbstractStatisticsCollection.cs.
         {
             collect.Add(item);
             UpdateStatistics(item);
         }
Add() [3/3]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Add (T a, T b) protected pure virtual inherited
Implementing classes can define how two values get added (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Append()
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.Append (T value, int numStandardDeviations, int minSamples = 2) inline inherited
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Parameters
value
numStandardDeviations
minSamples The minimum number of collected samples in the collection to have before rejecting outliers. MinSamples must be at least 2.
Returns
True if the item was added, false if it was rejected.
Definition at line 275 of file AbstractStatisticsCollection.cs.
         {
             var delta = Abs(Subtract(value, Mean));
             var isInlier = Count < 2
                 || Count < minSamples
                 || LessThan(delta, Scale(StandardDeviation, numStandardDeviations));
             if (isInlier)
             {
                 Add(value);
             }
             return isInlier;
         }
Clear()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.Clear () inline inherited
Clears the collection and resets the statistics to null.
Definition at line 170 of file AbstractStatisticsCollection.cs.
         {
             collect.Clear();
             Minimum = null;
             Maximum = null;
             Mean = null;
             Variance = null;
             StandardDeviation = null;
         }
Contains()
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.Contains (T item) inline inherited
Returns true if the give item is in the collection.
Parameters
item The item to search for.
Returns
True if the item is found. False if it is not.
Definition at line 185 of file AbstractStatisticsCollection.cs.
         {
             return collect.Contains(item);
         }
CopyTo()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.CopyTo (T [] array, int arrayIndex) inline inherited
Copies the elements of the collection to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
arrayIndex The zero-based index in array at which copying begins.
Exceptions
System.ArgumentNullException array is null
System.ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from arrayIndex to the end of the destination array .
Definition at line 206 of file AbstractStatisticsCollection.cs.
         {
             collect.CopyTo(array, arrayIndex);
         }
Divide() [1/2]
override float Juniper.Mathematics.SingleStatisticsCollection.Divide (float a, float b) inline protected
Performs Divide on floats.
Parameters
a
b
Returns
Definition at line 59 of file SingleStatisticsCollection.cs.
         {
             return a / b;
         }
Divide() [2/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Divide (T a, float b) protected pure virtual inherited
Implementing classes can define how a value gets divided by a scalar (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
GetEnumerator()
IEnumerator<T> Juniper.Mathematics.AbstractStatisticsCollection< T >.GetEnumerator () inline inherited
Returns an enumerator that iterates through the collection.
Returns
Definition at line 138 of file AbstractStatisticsCollection.cs.
         {
             for (var i = 0; i < collect.Count; ++i)
             {
                 yield return collect[i];
             }
         }
IndexOf()
int Juniper.Mathematics.AbstractStatisticsCollection< T >.IndexOf (T item) inline inherited
Determines the index of the specified item in the underlying collection.
Parameters
item The object to location in the collection.
Returns
The index of item if found in the list; otherwise, -1.
If an object occurs multiple times in the list, the IndexOf method always returns the first instance found.
Definition at line 232 of file AbstractStatisticsCollection.cs.
         {
             return collect.IndexOf(item);
         }
Insert()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.Insert (int index, T item) inline inherited
Insert an item at an arbitrary point in the collection.
Parameters
index The index at which to insert item .
item The value to insert.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
Definition at line 245 of file AbstractStatisticsCollection.cs.
         {
             collect.Insert(index, item);
             UpdateStatistics(item);
         }
LessThan() [1/2]
override bool Juniper.Mathematics.SingleStatisticsCollection.LessThan (float a, float b) inline protected
Performs Less-Than on floats.
Parameters
a
b
Returns
Definition at line 70 of file SingleStatisticsCollection.cs.
         {
             return a < b;
         }
LessThan() [2/2]
abstract bool Juniper.Mathematics.AbstractStatisticsCollection< T >.LessThan (T a, T b) protected pure virtual inherited
Implementing classes can define how two values get compared (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Multiply() [1/2]
override float Juniper.Mathematics.SingleStatisticsCollection.Multiply (float a, float b) inline protected
Performs Multiply on floats.
Parameters
a
b
Returns
Definition at line 81 of file SingleStatisticsCollection.cs.
         {
             return a * b;
         }
Multiply() [2/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Multiply (T a, T b) protected pure virtual inherited
Implementing classes can define how two values get multiplied (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
RecomputeStatistics()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.RecomputeStatistics () inline protected inherited
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
Definition at line 321 of file AbstractStatisticsCollection.cs.
         {
             Maximum = Minimum = Mean = Variance = StandardDeviation = null;
             if (Count > 0)
             {
                 Minimum = MaxValue;
                 Maximum = MinValue;
                 for (var i = 0; i < Count; ++i)
                 {
                     var v = this[i];
                     Minimum = Min(Minimum, v);
                     Maximum = Max(Maximum, v);
                     Mean = Add(Mean, Divide(v, Count));
                 }
                 if (Count > 1)
                 {
                     Variance = Zero;
                     for (var i = 0; i < Count; ++i)
                     {
                         var v = this[i];
                         var residual = Subtract(v, Mean);
                         Variance = Add(Variance, Divide(Multiply(residual, residual), Count - 1));
                     }
                     StandardDeviation = Sqrt(Variance);
                 }
             }
         }
Remove()
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.Remove (T item) inline inherited
Remove an item from the collection.
Parameters
item The value to remove.
Returns
True if the item existed in the buffer and was removed. False otherwise.
Definition at line 216 of file AbstractStatisticsCollection.cs.
         {
             var removed = collect.Remove(item);
             RecomputeStatistics();
             return removed;
         }
RemoveAt()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.RemoveAt (int index) inline inherited
Remove an item at the specified index from the collection.
Parameters
index The index at which to remove an item.
Exceptions
System.ArgumentOutOfRangeException index is less than 0 or greater than Count - 1.
Definition at line 258 of file AbstractStatisticsCollection.cs.
         {
             collect.RemoveAt(index);
             RecomputeStatistics();
         }
Scale() [1/2]
override float Juniper.Mathematics.SingleStatisticsCollection.Scale (float a, float b) inline protected
Performs Scale on floats.
Parameters
a
b
Returns
Definition at line 92 of file SingleStatisticsCollection.cs.
         {
             return a * b;
         }
Scale() [2/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Scale (T a, float b) protected pure virtual inherited
Implementing classes can define how a value gets scaled by a scalar (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Sqrt() [1/2]
override float Juniper.Mathematics.SingleStatisticsCollection.Sqrt (float value) inline protected
Performs Sqrt on floats.
Parameters
value
Returns
Definition at line 102 of file SingleStatisticsCollection.cs.
         {
             return (float)Math.Sqrt(value);
         }
Sqrt() [2/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Sqrt (T value) protected pure virtual inherited
Implementing classes can define how calculate the square root of a value (because C# generics cannot specify operator constraints)
Parameters
value
Returns
Subtract() [1/2]
override float Juniper.Mathematics.SingleStatisticsCollection.Subtract (float a, float b) inline protected
Performs Subtract on floats.
Parameters
a
b
Returns
Definition at line 113 of file SingleStatisticsCollection.cs.
         {
             return a - b;
         }
Subtract() [2/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Subtract (T a, T b) protected pure virtual inherited
Implementing classes can define how two values get subtracted (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
UpdateStatistics()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.UpdateStatistics (T value) inline protected inherited
Recalculate statistics that don't need to perform a full collection scan.
Parameters
value
Definition at line 356 of file AbstractStatisticsCollection.cs.
         {
             Minimum = Min(Minimum, value);
             Maximum = Max(Maximum, value);
             var prevMean = Mean;
             var residual = Subtract(value, prevMean);
             Mean = Add(prevMean, Divide(residual, Count));
             if (Count > 1)
             {
                 var secondResidual = Subtract(value, Mean);
                 var n2 = Count - 2;
                 var n1 = Count - 1;
                 Variance = Divide(
                     Add(
                         Scale(Variance, n2),
                         Multiply(residual, secondResidual)),
                     n1);
                 StandardDeviation = Sqrt(Variance);
             }
         }
Member Data Documentation
Count
int Juniper.Mathematics.AbstractStatisticsCollection< T >.Count inherited
Returns the number of items in the collection.
Definition at line 77 of file AbstractStatisticsCollection.cs.
Delta
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Delta inherited
The difference between the Maximum and Minimum
Definition at line 107 of file AbstractStatisticsCollection.cs.
IsReadOnly
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.IsReadOnly inherited
Gets a value indicating whether this collection is read only.
true if is read only; otherwise, false.
Definition at line 102 of file AbstractStatisticsCollection.cs.
Median
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Median inherited
The midpoint between the Maximum and the Minimum
Definition at line 112 of file AbstractStatisticsCollection.cs.
Property Documentation
IsSaturated
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.IsSaturated get inherited
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
true if is saturated; otherwise, false.
Definition at line 84 of file AbstractStatisticsCollection.cs.
         {
             get
             {
                 if (collect is RingBuffer<T> buf)
                 {
                     return buf.IsSaturated;
                 }
                 else
                 {
                     return false;
                 }
             }
         }
Maximum
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Maximum get private set inherited
The maximum value in the list, if there are any values in the list.
Definition at line 38 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
Mean
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Mean get private set inherited
The arithmetic mean of the values in the list, if there are any values in the list.
Definition at line 54 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
Minimum
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Minimum get private set inherited
The minimum value in the list, if there are any values in the list.
Definition at line 46 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
StandardDeviation
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.StandardDeviation get private set inherited
The standard deviation of all the values in the list, if there are any values in the list.
Definition at line 70 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
this[int index]
T Juniper.Mathematics.AbstractStatisticsCollection< T >.this[int index] get set inherited
Gets or sets the element at the specified index.
Parameters
index An index into the buffer, modulated by the buffer length.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
The element at the specified index.
Definition at line 123 of file AbstractStatisticsCollection.cs.
         {
             get
             {
                 return collect[index];
             }
             set
             {
                 collect[index] = value;
             }
         }
Variance
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Variance get private set inherited
The variance of all the values in the list, if there are any values in the list.
Definition at line 62 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Mathematics/SingleStatisticsCollection.cs