Juniper: Juniper.Unity.Permissions.AbstractPermissionHandler Class Reference
Juniper.Unity.Permissions.AbstractPermissionHandler Class Reference
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Public Member Functions
void Awake ()
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual bool Install (bool reset)
Install, with or without a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
Detailed Description
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Definition at line 8 of file AbstractPermissionHandler.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Permissions.AbstractPermissionHandler.Awake () inline
Definition at line 10 of file AbstractPermissionHandler.cs.
         {
             Install(false);
         }
References Juniper.Unity.Permissions.AbstractPermissionHandler.Install().
Install()
virtual bool Juniper.Unity.Permissions.AbstractPermissionHandler.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfuly. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Permissions.WindowsMRPermissionHandler.
Definition at line 29 of file AbstractPermissionHandler.cs.
         {
             return true;
         }
Referenced by Juniper.Unity.Permissions.AbstractPermissionHandler.Awake(), and Juniper.Unity.Permissions.AbstractPermissionHandler.Reinstall().
Reinstall()
virtual void Juniper.Unity.Permissions.AbstractPermissionHandler.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 15 of file AbstractPermissionHandler.cs.
         {
             Install(true);
         }
References Juniper.Unity.Permissions.AbstractPermissionHandler.Install().
Uninstall()
virtual void Juniper.Unity.Permissions.AbstractPermissionHandler.Uninstall () inline virtual
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 34 of file AbstractPermissionHandler.cs.
         {
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Permissions/AbstractPermissionHandler.cs