Juniper: System.Collections.Generic.IEnumerableExt Class Reference
System.Collections.Generic.IEnumerableExt Class Reference
Extension methods for System.Collections.Generic.IEnumerable{T}
Static Public Member Functions
static bool MaybeAdd< T > (this List< T > collect, T value)
Creates set-like behavior for generic lists. If the list already contains the given value, it will not be added to the list again.
static T Random< T > (this IEnumerable< T > collection)
Get a random item out of the collection.
static bool Matches< T > (this IEnumerable< T > a, IEnumerable< T > b)
Checks two collections to see if they contain all the same items.
static bool Matches< T > (this IEnumerable< T > a, IEnumerable b)
Checks two collections to see if they contain all the same items.
static bool Matches< T > (this IEnumerable< T > a, IEnumerator b)
Checks two collections to see if they contain all the same items.
static bool Matches (this IEnumerable< Type > a, IEnumerable< Type > b)
Check two collections of types to see if they contain all the same items.
static bool MoveNext (this IEnumerable< IEnumerator > enums)
Takes N enumerators and moves through them all, even if some of them are null or finished.
static IEnumerable Current (this IEnumerable< IEnumerator > enums)
For N enumerators, returns all M Current values of each non-null entry in the enums collection. M is less than or equal to N.
static bool Empty< T > (this IEnumerable< T > enumer, Func< T, bool > predicate)
Filters a collection and checks to see if it would return 0 results.
static bool Empty< T > (this IEnumerable< T > enumer)
Evaluates a collection and checks to see if it has 0 items.
static bool Empty (this IEnumerable enumer)
Evaluates a collection and checks to see if it has 0 items.
static IEnumerable AsEnumerable (this IEnumerator iter)
Convert an Enumerator collection to an Enumerable collection.
static void AddRange< T > (this Queue< T > q, IEnumerable< T > e)
Add an entire collection to a queue.
static void Add< T > (this Queue< T > q, T value)
Make Queues usable with collection initializer syntax.
static string ToString (this IEnumerable< string > enumer, string sep)
static string ToString< T > (this IEnumerable< T > enumer, string sep)
static IEnumerable< T > SkipLast< T > (this IEnumerable< T > enumer, int count)
static IEnumerable< T > TakeLast< T > (this IEnumerable< T > enumer, int count)
Static Private Member Functions
static string ValueToString< T > (T value)
Static Private Attributes
static readonly Random r = new Random()
A random number generator to use with the following methods.
Detailed Description
Extension methods for System.Collections.Generic.IEnumerable{T}
Definition at line 8 of file IEnumerableExt.cs.
Member Function Documentation
Add< T >()
static void System.Collections.Generic.IEnumerableExt.Add< T > (this Queue< T > q, T value) inline static
Make Queues usable with collection initializer syntax.
Template Parameters
T The type of the elements of the queue
Parameters
q The queue to which to add the item.
value The item to add to the queue.
Definition at line 377 of file IEnumerableExt.cs.
         {
             if (q is null)
             {
                 throw new ArgumentNullException(nameof(q));
             }
             q.Enqueue(value);
         }
AddRange< T >()
static void System.Collections.Generic.IEnumerableExt.AddRange< T > (this Queue< T > q, IEnumerable< T > e) inline static
Add an entire collection to a queue.
Template Parameters
T The type of elements in the queue.
Parameters
q The queue to which to add items.
e The items to add to the queue, in order.
Definition at line 353 of file IEnumerableExt.cs.
         {
             if (q is null)
             {
                 throw new ArgumentNullException(nameof(q));
             }
             if (e is null)
             {
                 throw new ArgumentNullException(nameof(e));
             }
             foreach (var o in e)
             {
                 q.Enqueue(o);
             }
         }
AsEnumerable()
static IEnumerable System.Collections.Generic.IEnumerableExt.AsEnumerable (this IEnumerator iter) inline static
Convert an Enumerator collection to an Enumerable collection.
Returns
The enumerable.
Parameters
iter Iterator.
Definition at line 339 of file IEnumerableExt.cs.
         {
             while (iter?.MoveNext() == true)
             {
                 yield return iter.Current;
             }
         }
References System.Collections.Generic.IEnumerableExt.MoveNext().
Current()
static IEnumerable System.Collections.Generic.IEnumerableExt.Current (this IEnumerable< IEnumerator > enums) inline static
For N enumerators, returns all M Current values of each non-null entry in the enums collection. M is less than or equal to N.
Parameters
enums
Returns
Definition at line 260 of file IEnumerableExt.cs.
         {
             if (enums is null)
             {
                 throw new ArgumentNullException(nameof(enums));
             }
             var anyExist = false;
             var anySucceed = false;
             foreach (var e in enums)
             {
                 if (e is object)
                 {
                     anyExist = true;
                     object value;
                     try
                     {
                         value = e.Current;
                         anySucceed = true;
                     }
 #pragma warning disable CA1031 // Do not catch general exception types
                     catch (InvalidOperationException)
                     {
                         value = null;
                     }
 #pragma warning restore CA1031 // Do not catch general exception types
                     if (value is object)
                     {
                         yield return value;
                     }
                 }
             }
             if (anyExist && !anySucceed)
             {
                 throw new InvalidOperationException();
             }
         }
Empty()
static bool System.Collections.Generic.IEnumerableExt.Empty (this IEnumerable enumer) inline static
Evaluates a collection and checks to see if it has 0 items.
Returns
The empty.
Parameters
enumer Enumerator.
Template Parameters
T The 1st type parameter.
Definition at line 329 of file IEnumerableExt.cs.
         {
             return enumer.Cast<object>().Empty();
         }
Empty< T >() [1/2]
static bool System.Collections.Generic.IEnumerableExt.Empty< T > (this IEnumerable< T > enumer, Func< T, bool > predicate) inline static
Filters a collection and checks to see if it would return 0 results.
Returns
The empty.
Parameters
enumer Enumerator.
predicate Predicate.
Template Parameters
T The 1st type parameter.
Definition at line 307 of file IEnumerableExt.cs.
         {
             return !enumer.Any(predicate);
         }
Empty< T >() [2/2]
static bool System.Collections.Generic.IEnumerableExt.Empty< T > (this IEnumerable< T > enumer) inline static
Evaluates a collection and checks to see if it has 0 items.
Returns
The empty.
Parameters
enumer Enumerator.
Template Parameters
T The 1st type parameter.
Definition at line 318 of file IEnumerableExt.cs.
         {
             return !enumer.Any();
         }
Matches()
static bool System.Collections.Generic.IEnumerableExt.Matches (this IEnumerable< Type > a, IEnumerable< Type > b) inline static
Check two collections of types to see if they contain all the same items.
Parameters
a
b
Returns
Definition at line 195 of file IEnumerableExt.cs.
         {
             if (a is null)
             {
                 return b is null;
             }
             else if (b is null)
             {
                 return false;
             }
             if (a.Count() != b.Count())
             {
                 return false;
             }
             using (var c = a.GetEnumerator())
             using (var d = b.GetEnumerator())
             {
                 while (c.MoveNext() && d.MoveNext())
                 {
 #if NETFX_CORE
                     var e = c.Current.GetTypeInfo();
                     var f = d.Current.GetTypeInfo();
 #else
                     var e = c.Current;
                     var f = d.Current;
 #endif
                     if (!e.IsAssignableFrom(f))
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
Matches< T >() [1/3]
static bool System.Collections.Generic.IEnumerableExt.Matches< T > (this IEnumerable< T > a, IEnumerable< T > b) inline static
Checks two collections to see if they contain all the same items.
Template Parameters
T Any type
Parameters
a
b
Returns
True if the collections are the same length and contain the same items, in the same order.
var a = new int[]{ 1, 2, 3, 4, 5 };
var b = new int[]{ 1, 2, 3, 4, 5 };
var c = new int[]{ 1, 2, 3, 4, 6 };
var d = new int[]{ 1, 2, 3, 4, 5, 6 };
var e = new int[]{ 1, 2, 3, 4 };
a.Matches(b); // --> true
a.Matches(c); // --> false
a.Matches(d); // --> false
a.Matches(e); // --> false
Definition at line 87 of file IEnumerableExt.cs.
         {
             if (a is null)
             {
                 return b is null;
             }
             else if (b is null)
             {
                 return false;
             }
             if (a.Count() != b.Count())
             {
                 return false;
             }
             using (var c = a.GetEnumerator())
             using (var d = b.GetEnumerator())
             {
                 while (c.MoveNext() && d.MoveNext())
                 {
                     if (!c.Current.Equals(d.Current))
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
Matches< T >() [2/3]
static bool System.Collections.Generic.IEnumerableExt.Matches< T > (this IEnumerable< T > a, IEnumerable b) inline static
Checks two collections to see if they contain all the same items.
Template Parameters
T Any type
Parameters
a
b
Returns
True if the collections are the same length and contain the same items, in the same order.
var a = new int[]{ 1, 2, 3, 4, 5 };
var b = new int[]{ 1, 2, 3, 4, 5 };
var c = new int[]{ 1, 2, 3, 4, 6 };
var d = new int[]{ 1, 2, 3, 4, 5, 6 };
var e = new int[]{ 1, 2, 3, 4 };
a.Matches(b); // --> true
a.Matches(c); // --> false
a.Matches(d); // --> false
a.Matches(e); // --> false
Definition at line 138 of file IEnumerableExt.cs.
         {
             if (a is null && b is null)
             {
                 return true;
             }
             if ((a is null) != (b is null))
             {
                 return false;
             }
             return a.Matches(b.Cast<T>());
         }
Matches< T >() [3/3]
static bool System.Collections.Generic.IEnumerableExt.Matches< T > (this IEnumerable< T > a, IEnumerator b) inline static
Checks two collections to see if they contain all the same items.
Template Parameters
T Any type
Parameters
a
b
Returns
True if the collections are the same length and contain the same items, in the same order.
var a = new int[]{ 1, 2, 3, 4, 5 };
var b = new int[]{ 1, 2, 3, 4, 5 };
var c = new
int[]{ 1, 2, 3, 4, 6 };
var d = new int[]{ 1, 2, 3, 4, 5, 6 };
var e = new int[]{ 1, 2, 3, 4 };
a.Matches(b); // --> true
a.Matches(c); // --> false
a.Matches(d); // --> false
a.Matches(e); // --> false
Definition at line 174 of file IEnumerableExt.cs.
         {
             if (a is null && b is null)
             {
                 return true;
             }
             if ((a is null) != (b is null))
             {
                 return false;
             }
             return a.Matches(b.AsEnumerable().Cast<T>());
         }
MaybeAdd< T >()
static bool System.Collections.Generic.IEnumerableExt.MaybeAdd< T > (this List< T > collect, T value) inline static
Creates set-like behavior for generic lists. If the list already contains the given value, it will not be added to the list again.
Template Parameters
T
Parameters
collect
value
Returns
True if the item was actually added.
Definition at line 18 of file IEnumerableExt.cs.
         {
             if (collect is null)
             {
                 throw new ArgumentNullException(nameof(collect));
             }
             if (!collect.Contains(value))
             {
                 collect.Add(value);
                 return true;
             }
             else
             {
                 return false;
             }
         }
MoveNext()
static bool System.Collections.Generic.IEnumerableExt.MoveNext (this IEnumerable< IEnumerator > enums) inline static
Takes N enumerators and moves through them all, even if some of them are null or finished.
Parameters
enums
Returns
True when all enumerators can no longer move to another item.
Definition at line 238 of file IEnumerableExt.cs.
         {
             if (enums is null)
             {
                 throw new ArgumentNullException(nameof(enums));
             }
             var anyNext = false;
             foreach (var iter in enums)
             {
                 anyNext |= iter?.MoveNext() == true;
             }
             return anyNext;
         }
Referenced by System.Collections.Generic.IEnumerableExt.AsEnumerable().
Random< T >()
static T System.Collections.Generic.IEnumerableExt.Random< T > (this IEnumerable< T > collection) inline static
Get a random item out of the collection.
Template Parameters
T
Parameters
collection
Returns
A random item out of the collection.
// This is just one potential outcome.
var arr = new int[]{ 1, 2, 3, 4, 5, 6, 7, 8, 9 };
arr.Random(); // --> 3
arr.Random(); // --> 1
arr.Random(); // --> 4
arr.Random(); // --> 1
arr.Random(); // --> 5
arr.Random(); // --> 9
arr.Random(); // --> 2
arr.Random(); // --> 6
Definition at line 59 of file IEnumerableExt.cs.
         {
             var count = collection.Count();
             var skip = r.Next(0, count);
             return collection.Skip(skip)
                 .FirstOrDefault();
         }
References System.Collections.Generic.IEnumerableExt.r.
SkipLast< T >()
static IEnumerable<T> System.Collections.Generic.IEnumerableExt.SkipLast< T > (this IEnumerable< T > enumer, int count) inline static
Definition at line 403 of file IEnumerableExt.cs.
         {
             return enumer.Reverse().Skip(count).Reverse();
         }
TakeLast< T >()
static IEnumerable<T> System.Collections.Generic.IEnumerableExt.TakeLast< T > (this IEnumerable< T > enumer, int count) inline static
Definition at line 408 of file IEnumerableExt.cs.
         {
             return enumer.Reverse().Take(count).Reverse();
         }
ToString()
static string System.Collections.Generic.IEnumerableExt.ToString (this IEnumerable< string > enumer, string sep) inline static
Definition at line 387 of file IEnumerableExt.cs.
         {
             return string.Join(sep, enumer);
         }
ToString< T >()
static string System.Collections.Generic.IEnumerableExt.ToString< T > (this IEnumerable< T > enumer, string sep) inline static
Definition at line 392 of file IEnumerableExt.cs.
         {
             return enumer.Select(ValueToString<T>).ToString(sep);
         }
References System.Collections.Generic.IEnumerableExt.ValueToString< T >().
ValueToString< T >()
static string System.Collections.Generic.IEnumerableExt.ValueToString< T > (T value) inline static private
Definition at line 397 of file IEnumerableExt.cs.
         {
             return value.ToString();
         }
Referenced by System.Collections.Generic.IEnumerableExt.ToString< T >().
Member Data Documentation
r
readonly Random System.Collections.Generic.IEnumerableExt.r = new Random() static private
A random number generator to use with the following methods.
Definition at line 39 of file IEnumerableExt.cs.
Referenced by System.Collections.Generic.IEnumerableExt.Random< T >().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/NETFX/Collections/Generic/IEnumerableExt.cs