Juniper: Juniper.Console.ConsoleCommandProcessor Class Reference
Juniper.Console.ConsoleCommandProcessor Class Reference
Public Member Functions
void Pump ()
void Execute (ConsoleKey key)
void PrintUsage ()
void Add (ConsoleKey key, string description, Action action)
void Add ((ConsoleKey key, string description, Action action) entry)
bool ContainsKey (ConsoleKey key)
bool TryGetValue (ConsoleKey key, out NamedAction value)
IEnumerator< KeyValuePair< ConsoleKey, NamedAction > > GetEnumerator ()
void SetLogLevel (int direction)
void OnInfo (object sender, StringEventArgs e)
void OnInfo (ConsoleColor color, string msg)
void OnInfo (string msg)
void OnLog (object sender, StringEventArgs e)
void OnWarning (object sender, StringEventArgs e)
void OnError (object sender, ErrorEventArgs e)
void OnError (ErrorEventArgs e)
Static Public Member Functions
static string GetName (uint logLevel)
Public Attributes
IEnumerable< ConsoleKey > Keys => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Keys
IEnumerable< NamedAction > Values => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Values
int Count => actions.Count
Properties
NamedAction this[ConsoleKey key] [get]
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
void Log< T > (uint level, Action< string > logger, ConsoleColor foreground, T e)
void Log< T > (uint level, Action< string > logger, ConsoleColor foreground, ConsoleColor background, T e)
Private Attributes
readonly Dictionary< ConsoleKey, NamedAction > actions = new Dictionary<ConsoleKey, NamedAction>()
uint logLevel = 0
Detailed Description
Definition at line 16 of file ConsoleCommandProcessor.cs.
Member Function Documentation
Add() [1/2]
void Juniper.Console.ConsoleCommandProcessor.Add (ConsoleKey key, string description, Action action) inline
Definition at line 97 of file ConsoleCommandProcessor.cs.
         {
             actions.Add(key, (description, action));
         }
References Juniper.Console.ConsoleCommandProcessor.actions.
Referenced by Juniper.Console.ConsoleCommandProcessor.Add().
Add() [2/2]
void Juniper.Console.ConsoleCommandProcessor.Add ((ConsoleKey key, string description, Action action) entry) inline
Definition at line 102 of file ConsoleCommandProcessor.cs.
         {
             var (key, description, action) = entry;
             Add(key, description, action);
         }
References Juniper.Console.ConsoleCommandProcessor.Add().
ContainsKey()
bool Juniper.Console.ConsoleCommandProcessor.ContainsKey (ConsoleKey key) inline
Definition at line 108 of file ConsoleCommandProcessor.cs.
         {
             return actions.ContainsKey(key);
         }
References Juniper.Console.ConsoleCommandProcessor.actions.
Execute()
void Juniper.Console.ConsoleCommandProcessor.Execute (ConsoleKey key) inline
Definition at line 43 of file ConsoleCommandProcessor.cs.
         {
             actions[key].Invoke();
         }
References Juniper.Console.ConsoleCommandProcessor.actions.
Referenced by Juniper.Console.ConsoleCommandProcessor.Pump().
GetEnumerator() [1/2]
IEnumerator<KeyValuePair<ConsoleKey, NamedAction> > Juniper.Console.ConsoleCommandProcessor.GetEnumerator () inline
Definition at line 118 of file ConsoleCommandProcessor.cs.
         {
             return ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).GetEnumerator();
         }
References Juniper.Console.ConsoleCommandProcessor.actions.
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.Console.ConsoleCommandProcessor.GetEnumerator () inline private
Definition at line 123 of file ConsoleCommandProcessor.cs.
         {
             return ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).GetEnumerator();
         }
References Juniper.Console.ConsoleCommandProcessor.actions.
GetName()
static string Juniper.Console.ConsoleCommandProcessor.GetName (uint logLevel) inline static
Definition at line 138 of file ConsoleCommandProcessor.cs.
         {
             return logLevel switch
             {
                 0 => "Verbose",
                 1 => "Log",
                 2 => "Warning",
                 3 => "Error",
                 _ => "N/A"
             };
         }
References Juniper.Console.ConsoleCommandProcessor.logLevel.
Log< T >() [1/2]
void Juniper.Console.ConsoleCommandProcessor.Log< T > (uint level, Action< string > logger, ConsoleColor foreground, T e) inline private
Definition at line 150 of file ConsoleCommandProcessor.cs.
         {
             Log(level, logger, foreground, C.BackgroundColor, e);
         }
Log< T >() [2/2]
void Juniper.Console.ConsoleCommandProcessor.Log< T > (uint level, Action< string > logger, ConsoleColor foreground, ConsoleColor background, T e) inline private
Definition at line 155 of file ConsoleCommandProcessor.cs.
         {
             if (e is null)
             {
                 throw new ArgumentNullException(nameof(e));
             }
             if (level >= logLevel)
             {
                 using var scope = new ColorScope(background, foreground);
                 logger($"[{GetName(level)}] {e.ToString()}");
             }
         }
References Juniper.Console.ConsoleCommandProcessor.logLevel.
OnError() [1/2]
void Juniper.Console.ConsoleCommandProcessor.OnError (object sender, ErrorEventArgs e) inline
Implements Juniper.Logging.IErrorDestination.
Definition at line 200 of file ConsoleCommandProcessor.cs.
         {
             Log(3, C.Error.WriteLine, Red, e);
         }
OnError() [2/2]
void Juniper.Console.ConsoleCommandProcessor.OnError (ErrorEventArgs e) inline
Definition at line 206 of file ConsoleCommandProcessor.cs.
         {
             Log(3, C.Error.WriteLine, Red, e);
         }
OnInfo() [1/3]
void Juniper.Console.ConsoleCommandProcessor.OnInfo (object sender, StringEventArgs e) inline
Implements Juniper.Logging.IInfoDestination.
Definition at line 170 of file ConsoleCommandProcessor.cs.
         {
             OnInfo(e?.Value);
         }
OnInfo() [2/3]
void Juniper.Console.ConsoleCommandProcessor.OnInfo (ConsoleColor color, string msg) inline
Definition at line 176 of file ConsoleCommandProcessor.cs.
         {
             Log(0, C.WriteLine, color, msg);
         }
OnInfo() [3/3]
void Juniper.Console.ConsoleCommandProcessor.OnInfo (string msg) inline
Definition at line 182 of file ConsoleCommandProcessor.cs.
         {
             Log(0, C.WriteLine, White, msg);
         }
OnLog()
void Juniper.Console.ConsoleCommandProcessor.OnLog (object sender, StringEventArgs e) inline
Implements Juniper.Logging.INCSALogDestination.
Definition at line 188 of file ConsoleCommandProcessor.cs.
         {
             Log(1, C.WriteLine, Cyan, e);
         }
OnWarning()
void Juniper.Console.ConsoleCommandProcessor.OnWarning (object sender, StringEventArgs e) inline
Implements Juniper.Logging.IWarningDestination.
Definition at line 194 of file ConsoleCommandProcessor.cs.
         {
             Log(2, C.WriteLine, Yellow, e);
         }
PrintUsage()
void Juniper.Console.ConsoleCommandProcessor.PrintUsage () inline
Definition at line 48 of file ConsoleCommandProcessor.cs.
         {
             var maxKeyLen = (from key in actions.Keys
                              let keyName = key.ToString()
                              select keyName.Length)
                         .Max();
             var format = $"  {{0,-{maxKeyLen}}} : {{1}}";
             var lines = (from command in actions
                          select string.Format(CultureInfo.InvariantCulture, format, command.Key, command.Value.Name))
                          .Prepend("Usage:")
                          .Prepend("")
                          .Append("")
                          .ToArray();
             var maxLen = lines.Max(l => l.Length);
             for (var i = 0; i < lines.Length; ++i)
             {
                 while (lines[i].Length <= maxLen)
                 {
                     lines[i] += " ";
                 }
                 lines[i] = " " + lines[i];
             }
             C.WriteLine();
             using var scope = new ColorScope(DarkGray, Yellow);
             foreach (var line in lines)
             {
                 C.WriteLine(line);
             }
         }
References Juniper.Console.ConsoleCommandProcessor.actions.
Referenced by Juniper.Console.ConsoleCommandProcessor.Pump().
Pump()
void Juniper.Console.ConsoleCommandProcessor.Pump () inline
Definition at line 27 of file ConsoleCommandProcessor.cs.
         {
             if (C.KeyAvailable)
             {
                 var keyInfo = C.ReadKey(true);
                 if (actions.ContainsKey(keyInfo.Key))
                 {
                     Execute(keyInfo.Key);
                 }
                 else
                 {
                     PrintUsage();
                 }
             }
         }
References Juniper.Console.ConsoleCommandProcessor.actions, Juniper.Console.ConsoleCommandProcessor.Execute(), and Juniper.Console.ConsoleCommandProcessor.PrintUsage().
SetLogLevel()
void Juniper.Console.ConsoleCommandProcessor.SetLogLevel (int direction) inline
Definition at line 128 of file ConsoleCommandProcessor.cs.
         {
             var nextLogLevel = (uint)(logLevel + direction);
             if (nextLogLevel < 4)
             {
                 logLevel = nextLogLevel;
                 C.WriteLine($"Logging level is now {GetName(logLevel)}");
             }
         }
References Juniper.Console.ConsoleCommandProcessor.logLevel.
TryGetValue()
bool Juniper.Console.ConsoleCommandProcessor.TryGetValue (ConsoleKey key, out NamedAction value) inline
Definition at line 113 of file ConsoleCommandProcessor.cs.
         {
             return actions.TryGetValue(key, out value);
         }
References Juniper.Console.ConsoleCommandProcessor.actions.
Member Data Documentation
actions
readonly Dictionary<ConsoleKey, NamedAction> Juniper.Console.ConsoleCommandProcessor.actions = new Dictionary<ConsoleKey, NamedAction>() private
Definition at line 23 of file ConsoleCommandProcessor.cs.
Referenced by Juniper.Console.ConsoleCommandProcessor.Add(), Juniper.Console.ConsoleCommandProcessor.ContainsKey(), Juniper.Console.ConsoleCommandProcessor.Execute(), Juniper.Console.ConsoleCommandProcessor.GetEnumerator(), Juniper.Console.ConsoleCommandProcessor.PrintUsage(), Juniper.Console.ConsoleCommandProcessor.Pump(), and Juniper.Console.ConsoleCommandProcessor.TryGetValue().
Count
int Juniper.Console.ConsoleCommandProcessor.Count => actions.Count
Definition at line 87 of file ConsoleCommandProcessor.cs.
Keys
IEnumerable<ConsoleKey> Juniper.Console.ConsoleCommandProcessor.Keys => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Keys
Definition at line 83 of file ConsoleCommandProcessor.cs.
logLevel
uint Juniper.Console.ConsoleCommandProcessor.logLevel = 0 private
Definition at line 25 of file ConsoleCommandProcessor.cs.
Referenced by Juniper.Console.ConsoleCommandProcessor.GetName(), Juniper.Console.ConsoleCommandProcessor.Log< T >(), and Juniper.Console.ConsoleCommandProcessor.SetLogLevel().
Values
IEnumerable<NamedAction> Juniper.Console.ConsoleCommandProcessor.Values => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Values
Definition at line 85 of file ConsoleCommandProcessor.cs.
Property Documentation
this[ConsoleKey key]
NamedAction Juniper.Console.ConsoleCommandProcessor.this[ConsoleKey key] get
Definition at line 90 of file ConsoleCommandProcessor.cs.
         {
             get
             {
                 return actions[key];
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Console/ConsoleCommandProcessor.cs