Juniper: Juniper.Unity.Input.Pointers.Motion.MotionController Class Reference
Juniper.Unity.Input.Pointers.Motion.MotionController Class Reference
Public Member Functions
override void Reinstall ()
override bool IsButtonPressed (OVRInput.Button button)
bool IsButtonPressed (VirtualTouchPadButton button)
bool IsButtonPressed (VirtualTriggerButton button)
override bool IsButtonPressed (InputButton button)
override bool IsButtonDown (OVRInput.Button button)
bool IsButtonDown (VirtualTouchPadButton button)
bool IsButtonDown (VirtualTriggerButton button)
override bool IsButtonDown (InputButton button)
override bool IsButtonUp (OVRInput.Button button)
bool IsButtonUp (VirtualTouchPadButton button)
bool IsButtonUp (VirtualTriggerButton button)
override bool IsButtonUp (InputButton button)
override void Awake ()
override bool Install (bool reset)
Static Public Member Functions
static MotionController [] MakeMotionControllers (Func< string, MotionController > MakePointer)
Public Attributes
override bool IsConnected
override Vector2 SquareTouchPoint
override Vector2 RoundTouchPoint
override? bool IsCharging
override? float BatteryLevel
override bool IsRightHand
override bool IsLeftHand
Protected Member Functions
override void InternalUpdate ()
override IEventSystemHandler ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared)
Static Protected Member Functions
static Vector2 Round2Square (Vector2 point)
static Vector2 Square2Round (Vector2 point)
Protected Attributes
override bool TouchPadTouched
override bool TouchPadTouchedDown
override bool TouchPadTouchedUp
override bool TouchPadPressed
override bool TouchPadPressedDown
override bool TouchPadPressedUp
readonly ButtonMapper< VirtualTouchPadButton > touchPadButtons
readonly ButtonMapper< VirtualTriggerButton > triggerButtons
Properties
static OVRInput.Controller Left [get]
override bool IsDominantHand [get]
abstract float Trigger [get]
override bool AnyButtonPressed [get]
Static Private Member Functions
static MotionController MakeMotionController (Func< string, MotionController > MakePointer, Hands hand)
Create a new hand pointer object for an interaction source that hasn't yet been seen.
Detailed Description
Definition at line 9 of file MotionController.cs.
Member Function Documentation
Awake()
override void Juniper.Unity.Input.Pointers.Motion.OculusTouchController.Awake () inline inherited
Definition at line 141 of file OculusTouchController.cs.
         {
             base.Awake();
             AddButton(TRIGGER_BUTTON, InputButton.Left);
             AddButton(TOUCHPAD_BUTTON, InputButton.Right);
             AddButton(OVRInput.Button.Back, InputButton.Middle);
         }
References Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TOUCHPAD_BUTTON, and Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TRIGGER_BUTTON.
Install()
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Install (bool reset) inline inherited
Definition at line 105 of file AbstractMotionController.cs.
         {
             reset &= Application.isEditor;
             base.Install(reset);
             PointerConfig.Install(touchPadButtons, gameObject);
             PointerConfig.Install(triggerButtons, gameObject);
 #if UNITY_EDITOR
             if (LaserPointerMaterial == null)
             {
                 LaserPointerMaterial = ComponentExt.EditorLoadAsset<Material>("Assets/Juniper/Materials/LaserPointer.mat");
             }
 #endif
             return true;
         }
InternalUpdate()
override void Juniper.Unity.Input.Pointers.Motion.OculusTouchController.InternalUpdate () inline protected inherited
Definition at line 150 of file OculusTouchController.cs.
         {
             transform.localPosition = OVRInput.GetLocalControllerPosition(NativeHandID);
             transform.localRotation = OVRInput.GetLocalControllerRotation(NativeHandID);
             base.InternalUpdate();
         }
IsButtonDown() [1/4]
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsButtonDown (OVRInput.Button button) inherited
IsButtonDown() [2/4]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonDown (VirtualTouchPadButton button) inline inherited
Definition at line 158 of file AbstractMotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressedDown;
         }
IsButtonDown() [3/4]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonDown (VirtualTriggerButton button) inline inherited
Definition at line 173 of file AbstractMotionController.cs.
         {
             return VirtualTriggerButtonThreshold(button, Trigger)
                 && !VirtualTriggerButtonThreshold(button, lastTrigger);
         }
IsButtonDown() [4/4]
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonDown (InputButton button) inline inherited
Definition at line 310 of file AbstractMotionController.cs.
         {
             return base.IsButtonDown(button)
                 || touchPadButtons.IsButtonDown(button)
                 || triggerButtons.IsButtonDown(button);
         }
IsButtonPressed() [1/4]
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsButtonPressed (OVRInput.Button button) inherited
IsButtonPressed() [2/4]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonPressed (VirtualTouchPadButton button) inline inherited
Definition at line 153 of file AbstractMotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressed;
         }
IsButtonPressed() [3/4]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonPressed (VirtualTriggerButton button) inline inherited
Definition at line 168 of file AbstractMotionController.cs.
         {
             return VirtualTriggerButtonThreshold(button, Trigger);
         }
IsButtonPressed() [4/4]
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonPressed (InputButton button) inline inherited
Definition at line 296 of file AbstractMotionController.cs.
         {
             return base.IsButtonPressed(button)
                 || touchPadButtons.IsButtonPressed(button)
                 || triggerButtons.IsButtonPressed(button);
         }
IsButtonUp() [1/4]
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsButtonUp (OVRInput.Button button) inherited
IsButtonUp() [2/4]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonUp (VirtualTouchPadButton button) inline inherited
Definition at line 163 of file AbstractMotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressedUp;
         }
IsButtonUp() [3/4]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonUp (VirtualTriggerButton button) inline inherited
Definition at line 179 of file AbstractMotionController.cs.
         {
             return !VirtualTriggerButtonThreshold(button, Trigger)
                 && VirtualTriggerButtonThreshold(button, lastTrigger);
         }
IsButtonUp() [4/4]
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonUp (InputButton button) inline inherited
Definition at line 303 of file AbstractMotionController.cs.
         {
             return base.IsButtonUp(button)
                 || touchPadButtons.IsButtonUp(button)
                 || triggerButtons.IsButtonUp(button);
         }
MakeMotionController()
static MotionController Juniper.Unity.Input.Pointers.Motion.MotionController.MakeMotionController (Func< string, MotionController > MakePointer, Hands hand) inline static private
Create a new hand pointer object for an interaction source that hasn't yet been seen.
Definition at line 41 of file MotionController.cs.
         {
             var pointer = MakePointer(PointerConfig.MakePointerName(hand));
             pointer.Hand = hand;
             return pointer;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.MotionController.MakeMotionControllers().
MakeMotionControllers()
static MotionController [] Juniper.Unity.Input.Pointers.Motion.MotionController.MakeMotionControllers (Func< string, MotionController > MakePointer) inline static
Definition at line 30 of file MotionController.cs.
         {
             return new[] {
                 MakeMotionController(MakePointer, Hands.Left),
                 MakeMotionController(MakePointer, Hands.Right)
             };
         }
References Juniper.Unity.Input.Pointers.Motion.MotionController.MakeMotionController().
Referenced by Juniper.Unity.StageExtensions.Install().
ProcessButtons()
override IEventSystemHandler Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared) inline protected inherited
Definition at line 287 of file AbstractMotionController.cs.
         {
             var a = base.ProcessButtons(evtData, pixelDragThresholdSquared);
             var b = touchPadButtons.Process(evtData, pixelDragThresholdSquared);
             var c = triggerButtons.Process(evtData, pixelDragThresholdSquared);
             return a ?? b ?? c;
         }
Reinstall()
override void Juniper.Unity.Input.Pointers.Motion.MotionController.Reinstall () inline
Definition at line 25 of file MotionController.cs.
         {
             base.Reinstall();
         }
Round2Square()
static Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Round2Square (Vector2 point) inline static protected inherited
Definition at line 226 of file AbstractMotionController.cs.
         {
             var pLen = point.magnitude;
             if (pLen > 0)
             {
                 var onUnitCircle = point / pLen;
                 float mx = Mathf.Abs(onUnitCircle.x),
                     my = Mathf.Abs(onUnitCircle.y);
                 var onUnitSquare = onUnitCircle;
                 if (mx > my)
                 {
                     onUnitSquare /= mx;
                 }
                 else if (my > 0)
                 {
                     onUnitSquare /= my;
                 }
                 point *= onUnitSquare.magnitude;
             }
             return point;
         }
Square2Round()
static Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Square2Round (Vector2 point) inline static protected inherited
Definition at line 250 of file AbstractMotionController.cs.
         {
             var pLen = point.magnitude;
             if (pLen > 0)
             {
                 var onUnitCircle = point / pLen;
                 var onUnitSquare = Round2Square(onUnitCircle);
                 point /= onUnitSquare.magnitude;
             }
             return point;
         }
Member Data Documentation
BatteryLevel
override? float Juniper.Unity.Input.Pointers.Motion.OculusTouchController.BatteryLevel inherited
Initial value:
=>
            0.01f * OVRInput.GetControllerBatteryPercentRemaining(NativeHandID)
Definition at line 122 of file OculusTouchController.cs.
IsCharging
override? bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsCharging inherited
Initial value:
=>
            OVRPlugin.batteryStatus == OVRPlugin.BatteryStatus.Charging
Definition at line 119 of file OculusTouchController.cs.
IsConnected
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsConnected inherited
Initial value:
=>
            OVRInput.IsControllerConnected(NativeHandID)
Definition at line 78 of file OculusTouchController.cs.
IsLeftHand
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsLeftHand inherited
Initial value:
=>
            NativeHandID == OVRInput.Controller.LTouch || NativeHandID == OVRInput.Controller.LTrackedRemote
Definition at line 138 of file OculusTouchController.cs.
IsRightHand
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsRightHand inherited
Initial value:
=>
            NativeHandID == OVRInput.Controller.RTouch || NativeHandID == OVRInput.Controller.RTrackedRemote
Definition at line 135 of file OculusTouchController.cs.
RoundTouchPoint
override Vector2 Juniper.Unity.Input.Pointers.Motion.OculusTouchController.RoundTouchPoint inherited
Initial value:
=>
            Square2Round(SquareTouchPoint)
Definition at line 107 of file OculusTouchController.cs.
SquareTouchPoint
override Vector2 Juniper.Unity.Input.Pointers.Motion.OculusTouchController.SquareTouchPoint inherited
Initial value:
=>
            OVRInput.Get(TOUCHPAD_AXIS, NativeHandID)
Definition at line 104 of file OculusTouchController.cs.
touchPadButtons
readonly ButtonMapper<VirtualTouchPadButton> Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.touchPadButtons protected inherited
Definition at line 83 of file AbstractMotionController.cs.
TouchPadPressed
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TouchPadPressed protected inherited
Initial value:
=>
            OVRInput.Get(TOUCHPAD_BUTTON, NativeHandID)
Definition at line 95 of file OculusTouchController.cs.
TouchPadPressedDown
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TouchPadPressedDown protected inherited
Initial value:
=>
            OVRInput.GetDown(TOUCHPAD_BUTTON, NativeHandID)
Definition at line 98 of file OculusTouchController.cs.
TouchPadPressedUp
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TouchPadPressedUp protected inherited
Initial value:
=>
            OVRInput.GetUp(TOUCHPAD_BUTTON, NativeHandID)
Definition at line 101 of file OculusTouchController.cs.
TouchPadTouched
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TouchPadTouched protected inherited
Initial value:
=>
            OVRInput.Get(TOUCHPAD_TOUCH, NativeHandID)
Definition at line 86 of file OculusTouchController.cs.
TouchPadTouchedDown
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TouchPadTouchedDown protected inherited
Initial value:
=>
            OVRInput.GetDown(TOUCHPAD_TOUCH, NativeHandID)
Definition at line 89 of file OculusTouchController.cs.
TouchPadTouchedUp
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.TouchPadTouchedUp protected inherited
Initial value:
=>
            OVRInput.GetUp(TOUCHPAD_TOUCH, NativeHandID)
Definition at line 92 of file OculusTouchController.cs.
triggerButtons
readonly ButtonMapper<VirtualTriggerButton> Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.triggerButtons protected inherited
Definition at line 84 of file AbstractMotionController.cs.
Property Documentation
AnyButtonPressed
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.AnyButtonPressed get inherited
Definition at line 186 of file AbstractMotionController.cs.
         {
             get
             {
                 return base.AnyButtonPressed
                     || IsButtonPressed(VirtualTouchPadButton.Any)
                     || IsButtonPressed(VirtualTriggerButton.On)
                     || IsButtonPressed(VirtualTriggerButton.Full);
             }
         }
IsDominantHand
override bool Juniper.Unity.Input.Pointers.Motion.OculusTouchController.IsDominantHand get inherited
Definition at line 126 of file OculusTouchController.cs.
         {
             get
             {
                 var dom = OVRInput.GetDominantHand();
                 return dom == OVRInput.Handedness.LeftHanded && IsLeftHand
                       || dom == OVRInput.Handedness.RightHanded && IsRightHand;
             }
         }
Left
static OVRInput Controller Juniper.Unity.Input.Pointers.Motion.OculusTouchController.Left static get inherited
Definition at line 33 of file OculusTouchController.cs.
         {
             get
             {
                 if (OVRInput.GetDominantHand() == OVRInput.Handedness.LeftHanded)
                 {
 #if UNITY_ANDROID
                     return OVRInput.Controller.LTrackedRemote;
 #else
                     return OVRInput.Controller.LTouch;
 #endif
                 }
                 else
                 {
 #if UNITY_ANDROID
                     return OVRInput.Controller.RTrackedRemote;
 #else
                     return OVRInput.Controller.RTouch;
 #endif
                 }
             }
         }
Trigger
abstract float Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Trigger get inherited
Definition at line 135 of file AbstractMotionController.cs.
         {
             get;
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Pointers/Motion/MotionController.cs