Juniper: Juniper.XR.Grounded Class Reference
Juniper.XR.Grounded Class Reference
This component searches for the ground above or below the gameObject it's attached to. When a mesh tagged as the "Ground" is found, with horizontal surfaces, the gameObject is moved to the ground and kept there. Use this when you have objects that should rest of the ground, but you're not sure where the ground will be.
Public Member Functions
void Awake ()
Get the physics components of the gameObject, find information about the ground mesh, and freeze the object in place until the ground is found.
void Update ()
If the test timeout has passed, raycast for the ground mesh under and over the object. If it's found, move the object to that point and unfreeze it.
void Reset ()
Delete the saved ground point, starting the work of looking for the ground again.
void WhenGrounded (Action p)
Check to see if the object is grounded, and call the callback if it is. If it's not, put the callback into a queue for execution later in EmptyJobQueue.
Public Attributes
float testTimeout = 0.25f
How many seconds to wait in between ground tests, to avoid pegging the system with ground tests.
float horizontalnessThreshold = 0.85f
The minimum amount of horizontalness to consider for the "ground".
Private Member Functions
void Freeze ()
Freezing the object turns off any physics and dragging capability that might have been on the object.
Vector3? GetGroundUnderObject ()
Search above and below the object to find the ground mesh.
void Unfreeze ()
Restore physics and draggable capabilities.
void EmptyJobQueue ()
Execute any WhenGrounded(Action) callbacks that were registered before the object was grounded.
Private Attributes
Draggable dragger
If the object being grounded is also controlled by a draggable constraint handle, then we will need to check if the draggable is being held and disengage any attempts to ground the gameObject.
bool wasUsingGravity
The saved "useGravity" value from the body object, so that it can be restored to its original value after the draggable handle has been removed.
Vector3? groundPoint
Where the current gameObject has been ordered to find.
Queue< Action > q
Before the object is actually grounded, other entities may wish to know when it is. This queue holds callbacks to those entities to execute once the object is grounded.
int GroundMask
The raycasting mask for the ground mesh.
float lastTime
The timestamp of when the last ground test was performed.
Detailed Description
This component searches for the ground above or below the gameObject it's attached to. When a mesh tagged as the "Ground" is found, with horizontal surfaces, the gameObject is moved to the ground and kept there. Use this when you have objects that should rest of the ground, but you're not sure where the ground will be.
Definition at line 16 of file Grounded.cs.
Member Function Documentation
Awake()
void Juniper.XR.Grounded.Awake () inline
Get the physics components of the gameObject, find information about the ground mesh, and freeze the object in place until the ground is found.
Definition at line 75 of file Grounded.cs.
         {
 #if UNITY_MODULES_PHYSICS
             body = GetComponent<Rigidbody>();
 #endif
             dragger = GetComponent<Draggable>();
             GroundMask = LayerMask.GetMask("Ground");
             lastTime = Time.time;
             Freeze();
         }
References Juniper.XR.Grounded.dragger, Juniper.XR.Grounded.Freeze(), Juniper.XR.Grounded.GroundMask, and Juniper.XR.Grounded.lastTime.
EmptyJobQueue()
void Juniper.XR.Grounded.EmptyJobQueue () inline private
Execute any WhenGrounded(Action) callbacks that were registered before the object was grounded.
Definition at line 195 of file Grounded.cs.
         {
             if (q != null)
             {
                 while (q.Count > 0)
                 {
                     var act = q.Dequeue();
                     act();
                 }
                 q = null;
             }
         }
References Juniper.XR.Grounded.q.
Referenced by Juniper.XR.Grounded.Update().
Freeze()
void Juniper.XR.Grounded.Freeze () inline private
Freezing the object turns off any physics and dragging capability that might have been on the object.
Definition at line 91 of file Grounded.cs.
         {
 #if UNITY_MODULES_PHYSICS
             if (body != null)
             {
                 if (dragger != null)
                 {
                     dragger.enabled = false;
                 }
                 wasUsingGravity = body.useGravity;
                 body.useGravity = false;
             }
 #endif
         }
References Juniper.XR.Grounded.dragger, and Juniper.XR.Grounded.wasUsingGravity.
Referenced by Juniper.XR.Grounded.Awake(), and Juniper.XR.Grounded.Update().
GetGroundUnderObject()
Vector3? Juniper.XR.Grounded.GetGroundUnderObject () inline private
Search above and below the object to find the ground mesh.
Returns
The ground under object.
Definition at line 140 of file Grounded.cs.
         {
 #if UNITY_MODULES_PHYSICS
             var center = transform.position;
             var rays = new[]
             {
                 new Ray(center, -transform.up),
                 new Ray(center, transform.up)
             };
             foreach (var ray in rays)
             {
                 RaycastHit target;
                 if (Physics.Raycast(ray, out target, 10, GroundMask))
                 {
                     var test = Vector3.Dot(Vector3.up, target.normal);
                     var isHorizontal = test >= horizontalnessThreshold;
                     if (isHorizontal)
                     {
                         return target.point;
                     }
                 }
             }
 #endif
             return null;
         }
References Juniper.XR.Grounded.GroundMask, and Juniper.XR.Grounded.horizontalnessThreshold.
Referenced by Juniper.XR.Grounded.Update().
Reset()
void Juniper.XR.Grounded.Reset ()
Delete the saved ground point, starting the work of looking for the ground again.
Unfreeze()
void Juniper.XR.Grounded.Unfreeze () inline private
Restore physics and draggable capabilities.
Definition at line 176 of file Grounded.cs.
         {
 #if UNITY_MODULES_PHYSICS
             if (body)
             {
                 body.useGravity = wasUsingGravity;
                 if (dragger)
                 {
                     dragger.enabled = true;
                 }
             }
 #endif
         }
References Juniper.XR.Grounded.dragger, and Juniper.XR.Grounded.wasUsingGravity.
Referenced by Juniper.XR.Grounded.Update().
Update()
void Juniper.XR.Grounded.Update () inline
If the test timeout has passed, raycast for the ground mesh under and over the object. If it's found, move the object to that point and unfreeze it.
Definition at line 111 of file Grounded.cs.
         {
             if (groundPoint == null && Time.time - lastTime > testTimeout)
             {
                 lastTime = Time.time;
                 groundPoint = GetGroundUnderObject();
                 if (groundPoint == null)
                 {
                     Freeze();
                 }
                 else
                 {
                     var anchor = GetComponent<Anchored>();
                     anchor?.WeighAnchor();
                     transform.position = groundPoint.Value;
                     anchor?.DropAnchor();
                     Unfreeze();
                     EmptyJobQueue();
                 }
             }
         }
References Juniper.XR.Grounded.EmptyJobQueue(), Juniper.XR.Grounded.Freeze(), Juniper.XR.Grounded.GetGroundUnderObject(), Juniper.XR.Grounded.groundPoint, Juniper.XR.Grounded.lastTime, Juniper.XR.Grounded.testTimeout, and Juniper.XR.Grounded.Unfreeze().
WhenGrounded()
void Juniper.XR.Grounded.WhenGrounded (Action p) inline
Check to see if the object is grounded, and call the callback if it is. If it's not, put the callback into a queue for execution later in EmptyJobQueue.
Parameters
p P.
Definition at line 214 of file Grounded.cs.
         {
             if (groundPoint != null)
             {
                 p();
             }
             else
             {
                 if (q == null)
                 {
                     q = new Queue<Action>();
                 }
                 q.Enqueue(p);
             }
         }
References Juniper.XR.Grounded.groundPoint, and Juniper.XR.Grounded.q.
Referenced by Juniper.StageExtensions.GroundAvatar().
Member Data Documentation
dragger
Draggable Juniper.XR.Grounded.dragger private
If the object being grounded is also controlled by a draggable constraint handle, then we will need to check if the draggable is being held and disengage any attempts to ground the gameObject.
Definition at line 23 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.Awake(), Juniper.XR.Grounded.Freeze(), and Juniper.XR.Grounded.Unfreeze().
GroundMask
int Juniper.XR.Grounded.GroundMask private
The raycasting mask for the ground mesh.
Definition at line 54 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.Awake(), and Juniper.XR.Grounded.GetGroundUnderObject().
groundPoint
Vector3? Juniper.XR.Grounded.groundPoint private
Where the current gameObject has been ordered to find.
Definition at line 43 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.Update(), and Juniper.XR.Grounded.WhenGrounded().
horizontalnessThreshold
float Juniper.XR.Grounded.horizontalnessThreshold = 0.85f
The minimum amount of horizontalness to consider for the "ground".
Definition at line 64 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.GetGroundUnderObject().
lastTime
float Juniper.XR.Grounded.lastTime private
The timestamp of when the last ground test was performed.
Definition at line 69 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.Awake(), and Juniper.XR.Grounded.Update().
q
Queue<Action> Juniper.XR.Grounded.q private
Before the object is actually grounded, other entities may wish to know when it is. This queue holds callbacks to those entities to execute once the object is grounded.
Definition at line 49 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.EmptyJobQueue(), and Juniper.XR.Grounded.WhenGrounded().
testTimeout
float Juniper.XR.Grounded.testTimeout = 0.25f
How many seconds to wait in between ground tests, to avoid pegging the system with ground tests.
Definition at line 59 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.Update().
wasUsingGravity
bool Juniper.XR.Grounded.wasUsingGravity private
The saved "useGravity" value from the body object, so that it can be restored to its original value after the draggable handle has been removed.
Definition at line 38 of file Grounded.cs.
Referenced by Juniper.XR.Grounded.Freeze(), and Juniper.XR.Grounded.Unfreeze().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/XR/Grounded.cs