Juniper: Hjg.Pngcs.Chunks.PngChunk Class Reference
Hjg.Pngcs.Chunks.PngChunk Class Reference abstract
Represents a instance of a PNG chunk
Public Types
enum ChunkOrderingConstraint {
ChunkOrderingConstraint.NONE, ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT, ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT, ChunkOrderingConstraint.BEFORE_IDAT,
ChunkOrderingConstraint.NA
}
Restrictions for chunk ordering, for ancillary chunks
Public Member Functions
ChunkRaw createEmptyChunk (int len, bool alloc)
override String ToString ()
Basic info: Id, length, Type name
abstract ChunkRaw CreateRawChunk ()
Serialization. Creates a Raw chunk, ready for write, from this chunk content
abstract void ParseFromRaw (ChunkRaw c)
Deserialization. Given a Raw chunk, just rad, fills this chunk content
abstract void CloneDataFromRead (PngChunk other)
Override to make a copy (normally deep) from other chunk
abstract bool AllowsMultiple ()
This is implemented in PngChunkMultiple/PngChunSingle
abstract ChunkOrderingConstraint GetOrderingConstraint ()
Get ordering constrain
Static Public Member Functions
static void FactoryRegister (String chunkId, Type type)
Registers a Chunk ID in the factory, to instantiate a given type
static T CloneChunk< T > (T chunk, ImageInfo info)
Public Attributes
readonly String Id
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
readonly bool Crit
Standard basic properties, implicit in the Id
Protected Member Functions
PngChunk (String id, ImageInfo imgInfo)
Constructs an empty chunk
Protected Attributes
readonly ImageInfo ImgInfo
Image basic info, mostly for some checks
Properties
bool Priority [get, set]
For writing. Queued chunks with high priority will be written as soon as possible
int ChunkGroup [get, set]
Chunk group where it was read or writen
int Length [get, set]
long Offset [get, set]
Private Member Functions
internal bool mustGoBeforePLTE ()
internal bool mustGoBeforeIDAT ()
internal bool mustGoAfterPLTE ()
internal void write (Stream os)
Static Private Member Functions
static Dictionary< String, Type > initFactory ()
static internal bool isKnown (String id)
static internal PngChunk Factory (ChunkRaw chunk, ImageInfo info)
static internal PngChunk FactoryFromId (String cid, ImageInfo info)
Creates one new blank chunk of the corresponding type, according to factoryMap (PngChunkUNKNOWN if not known)
Private Attributes
readonly bool Pub
readonly bool Safe
Static Private Attributes
static Dictionary< String, Type > factoryMap = initFactory()
Detailed Description
Represents a instance of a PNG chunk
Concrete classes should extend PngChunkSingle or PngChunkMultiple
Note that some methods/fields are type-specific (GetOrderingConstraint(), AllowsMultiple()) some are 'almost' type-specific (Id,Crit,Pub,Safe; the exception is PngUKNOWN), and some are instance-specific
Ref: http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html
Definition at line 24 of file PngChunk.cs.
Member Enumeration Documentation
ChunkOrderingConstraint
enum Hjg.Pngcs.Chunks.PngChunk.ChunkOrderingConstraint strong
Restrictions for chunk ordering, for ancillary chunks
Enumerator
NONE
No constraint, the chunk can go anywhere
BEFORE_PLTE_AND_IDAT
Before PLTE (palette) - and hence, also before IDAT
AFTER_PLTE_BEFORE_IDAT
After PLTE (palette), but before IDAT
BEFORE_IDAT
Before IDAT (before or after PLTE)
NA
Does not apply
Definition at line 54 of file PngChunk.cs.
{
             /// <summary>
             /// No constraint, the chunk can go anywhere
             /// </summary>
             NONE,
             /// <summary>
             /// Before PLTE (palette) - and hence, also before IDAT
             /// </summary>
             BEFORE_PLTE_AND_IDAT,
             /// <summary>
             /// After PLTE (palette), but before IDAT
             /// </summary>
             AFTER_PLTE_BEFORE_IDAT,
             /// <summary>
             /// Before IDAT (before or after PLTE)
             /// </summary>
             BEFORE_IDAT,
             /// <summary>
             /// Does not apply
             /// </summary>
             NA
         }
Constructor & Destructor Documentation
PngChunk()
Hjg.Pngcs.Chunks.PngChunk.PngChunk (String id, ImageInfo imgInfo) inline protected
Constructs an empty chunk
Parameters
id
imgInfo
Definition at line 82 of file PngChunk.cs.
{
             this.Id = id;
             this.ImgInfo = imgInfo;
             this.Crit = Hjg.Pngcs.Chunks.ChunkHelper.IsCritical(id);
             this.Pub = Hjg.Pngcs.Chunks.ChunkHelper.IsPublic(id);
             this.Safe = Hjg.Pngcs.Chunks.ChunkHelper.IsSafeToCopy(id);
             this.Priority = false;
             this.ChunkGroup = -1;
             this.Length = -1;
             this.Offset = 0;
         }
References Hjg.Pngcs.Chunks.PngChunk.ChunkGroup, Hjg.Pngcs.Chunks.ChunkHelper.IsCritical(), Hjg.Pngcs.Chunks.ChunkHelper.IsPublic(), Hjg.Pngcs.Chunks.ChunkHelper.IsSafeToCopy(), Hjg.Pngcs.Chunks.PngChunk.Length, Hjg.Pngcs.Chunks.PngChunk.Offset, and Hjg.Pngcs.Chunks.PngChunk.Priority.
Referenced by Hjg.Pngcs.Chunks.PngChunk.FactoryFromId().
Member Function Documentation
AllowsMultiple()
abstract bool Hjg.Pngcs.Chunks.PngChunk.AllowsMultiple () pure virtual
This is implemented in PngChunkMultiple/PngChunSingle
Returns
Allows more than one chunk of this type in a image
Implemented in Hjg.Pngcs.Chunks.PngChunkMultiple, Hjg.Pngcs.Chunks.PngChunkSingle, and Hjg.Pngcs.Chunks.PngChunkSkipped.
Referenced by Hjg.Pngcs.Chunks.ChunkHelper.Equivalent(), and Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
CloneChunk< T >()
static T Hjg.Pngcs.Chunks.PngChunk.CloneChunk< T > (T chunk, ImageInfo info) inline static
Type Constraints
T : PngChunk
Definition at line 185 of file PngChunk.cs.
                                                                        : PngChunk {
             PngChunk cn = FactoryFromId(chunk.Id, info);
             if ((Object)cn.GetType() != (Object)chunk.GetType())
                 throw new PngjException("bad class cloning chunk: " + cn.GetType() + " "
                         + chunk.GetType());
             cn.CloneDataFromRead(chunk);
             return (T)cn;
         }
References Hjg.Pngcs.Chunks.PngChunk.CloneDataFromRead(), and Hjg.Pngcs.Chunks.PngChunk.FactoryFromId().
CloneDataFromRead()
abstract void Hjg.Pngcs.Chunks.PngChunk.CloneDataFromRead (PngChunk other) pure virtual
Override to make a copy (normally deep) from other chunk
Parameters
other
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTEXT, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkIEND, and Hjg.Pngcs.Chunks.PngChunkSkipped.
Referenced by Hjg.Pngcs.Chunks.PngChunk.CloneChunk< T >().
createEmptyChunk()
ChunkRaw Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk (int len, bool alloc) inline
Definition at line 179 of file PngChunk.cs.
{
             ChunkRaw c = new ChunkRaw(len, ChunkHelper.ToBytes(Id), alloc);
             return c;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
Referenced by Hjg.Pngcs.Chunks.PngChunkTEXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkGAMA.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTIME.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkOFFS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSTER.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPHYS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkUNKNOWN.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSRGB.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk().
CreateRawChunk()
abstract ChunkRaw Hjg.Pngcs.Chunks.PngChunk.CreateRawChunk () pure virtual
Serialization. Creates a Raw chunk, ready for write, from this chunk content
Implemented in Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkIEND, Hjg.Pngcs.Chunks.PngChunkTEXT, Hjg.Pngcs.Chunks.PngChunkZTXT, and Hjg.Pngcs.Chunks.PngChunkSkipped.
Referenced by Hjg.Pngcs.Chunks.PngChunk.write().
Factory()
static internal PngChunk Hjg.Pngcs.Chunks.PngChunk.Factory (ChunkRaw chunk, ImageInfo info) inline static private
Definition at line 151 of file PngChunk.cs.
{
             PngChunk c = FactoryFromId(Hjg.Pngcs.Chunks.ChunkHelper.ToString(chunk.IdBytes), info);
             c.Length = chunk.Len;
             c.ParseFromRaw(chunk);
             return c;
         }
References Hjg.Pngcs.Chunks.PngChunk.FactoryFromId(), Hjg.Pngcs.Chunks.ChunkRaw.IdBytes, Hjg.Pngcs.Chunks.ChunkRaw.Len, Hjg.Pngcs.Chunks.PngChunk.Length, Hjg.Pngcs.Chunks.PngChunk.ParseFromRaw(), and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
Referenced by Hjg.Pngcs.PngReader.ReadChunk().
FactoryFromId()
static internal PngChunk Hjg.Pngcs.Chunks.PngChunk.FactoryFromId (String cid, ImageInfo info) inline static private
Creates one new blank chunk of the corresponding type, according to factoryMap (PngChunkUNKNOWN if not known)
Parameters
cid Chunk Id
info
Returns
Definition at line 163 of file PngChunk.cs.
{
             PngChunk chunk = null;
             if (factoryMap == null) initFactory();
             if (isKnown(cid)) {
                 Type t = factoryMap[cid];
                 if (t == null) Console.Error.WriteLine("What?? " + cid);
                 System.Reflection.ConstructorInfo cons = t.GetConstructor(new Type[] { typeof(ImageInfo) });
                 object o = cons.Invoke(new object[] { info });
                 chunk = (PngChunk)o;
             }
             if (chunk == null)
                 chunk = new PngChunkUNKNOWN(cid, info);
             return chunk;
         }
References Hjg.Pngcs.Chunks.PngChunk.factoryMap, Hjg.Pngcs.Chunks.PngChunk.initFactory(), Hjg.Pngcs.Chunks.PngChunk.isKnown(), and Hjg.Pngcs.Chunks.PngChunk.PngChunk().
Referenced by Hjg.Pngcs.Chunks.PngChunk.CloneChunk< T >(), and Hjg.Pngcs.Chunks.PngChunk.Factory().
FactoryRegister()
static void Hjg.Pngcs.Chunks.PngChunk.FactoryRegister (String chunkId, Type type) inline static
Registers a Chunk ID in the factory, to instantiate a given type
This can be called by client code to register additional chunk types
Parameters
chunkId
type should extend PngChunkSingle or PngChunkMultiple
Definition at line 130 of file PngChunk.cs.
{
             factoryMap.Add(chunkId, type);
         }
References Hjg.Pngcs.Chunks.PngChunk.factoryMap.
GetOrderingConstraint()
abstract ChunkOrderingConstraint Hjg.Pngcs.Chunks.PngChunk.GetOrderingConstraint () pure virtual
Get ordering constrain
Returns
Implemented in Hjg.Pngcs.Chunks.PngChunkTextVar, Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkSkipped, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkTIME, and Hjg.Pngcs.Chunks.PngChunkIEND.
Referenced by Hjg.Pngcs.Chunks.PngChunk.mustGoAfterPLTE(), Hjg.Pngcs.Chunks.PngChunk.mustGoBeforeIDAT(), and Hjg.Pngcs.Chunks.PngChunk.mustGoBeforePLTE().
initFactory()
static Dictionary<String, Type> Hjg.Pngcs.Chunks.PngChunk.initFactory () inline static private
Definition at line 96 of file PngChunk.cs.
{
             Dictionary<String, Type> f = new Dictionary<string, System.Type>();
             f.Add(ChunkHelper.IDAT, typeof(PngChunkIDAT));
             f.Add(ChunkHelper.IHDR, typeof(PngChunkIHDR));
             f.Add(ChunkHelper.PLTE, typeof(PngChunkPLTE));
             f.Add(ChunkHelper.IEND, typeof(PngChunkIEND));
             f.Add(ChunkHelper.tEXt, typeof(PngChunkTEXT));
             f.Add(ChunkHelper.iTXt, typeof(PngChunkITXT));
             f.Add(ChunkHelper.zTXt, typeof(PngChunkZTXT));
             f.Add(ChunkHelper.bKGD, typeof(PngChunkBKGD));
             f.Add(ChunkHelper.gAMA, typeof(PngChunkGAMA));
             f.Add(ChunkHelper.pHYs, typeof(PngChunkPHYS));
             f.Add(ChunkHelper.iCCP, typeof(PngChunkICCP));
             f.Add(ChunkHelper.tIME, typeof(PngChunkTIME));
             f.Add(ChunkHelper.tRNS, typeof(PngChunkTRNS));
             f.Add(ChunkHelper.cHRM, typeof(PngChunkCHRM));
             f.Add(ChunkHelper.sBIT, typeof(PngChunkSBIT));
             f.Add(ChunkHelper.sRGB, typeof(PngChunkSRGB));
             f.Add(ChunkHelper.hIST, typeof(PngChunkHIST));
             f.Add(ChunkHelper.sPLT, typeof(PngChunkSPLT));
             // extended
             f.Add(PngChunkOFFS.ID, typeof(PngChunkOFFS));
             f.Add(PngChunkSTER.ID, typeof(PngChunkSTER));
             return f;
         }
References Hjg.Pngcs.Chunks.ChunkHelper.bKGD, Hjg.Pngcs.Chunks.ChunkHelper.cHRM, Hjg.Pngcs.Chunks.ChunkHelper.gAMA, Hjg.Pngcs.Chunks.ChunkHelper.hIST, Hjg.Pngcs.Chunks.ChunkHelper.iCCP, Hjg.Pngcs.Chunks.PngChunkOFFS.ID, Hjg.Pngcs.Chunks.PngChunkSTER.ID, Hjg.Pngcs.Chunks.ChunkHelper.IDAT, Hjg.Pngcs.Chunks.ChunkHelper.IEND, Hjg.Pngcs.Chunks.ChunkHelper.IHDR, Hjg.Pngcs.Chunks.ChunkHelper.iTXt, Hjg.Pngcs.Chunks.ChunkHelper.pHYs, Hjg.Pngcs.Chunks.ChunkHelper.PLTE, Hjg.Pngcs.Chunks.ChunkHelper.sBIT, Hjg.Pngcs.Chunks.ChunkHelper.sPLT, Hjg.Pngcs.Chunks.ChunkHelper.sRGB, Hjg.Pngcs.Chunks.ChunkHelper.tEXt, Hjg.Pngcs.Chunks.ChunkHelper.tIME, Hjg.Pngcs.Chunks.ChunkHelper.tRNS, and Hjg.Pngcs.Chunks.ChunkHelper.zTXt.
Referenced by Hjg.Pngcs.Chunks.PngChunk.FactoryFromId().
isKnown()
static internal bool Hjg.Pngcs.Chunks.PngChunk.isKnown (String id) inline static private
Definition at line 134 of file PngChunk.cs.
{
             return factoryMap.ContainsKey(id);
         }
References Hjg.Pngcs.Chunks.PngChunk.factoryMap.
Referenced by Hjg.Pngcs.Chunks.PngChunk.FactoryFromId(), and Hjg.Pngcs.Chunks.ChunkHelper.ShouldLoad().
mustGoAfterPLTE()
internal bool Hjg.Pngcs.Chunks.PngChunk.mustGoAfterPLTE () inline private
Definition at line 147 of file PngChunk.cs.
{
             return GetOrderingConstraint() == ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT;
         }
References Hjg.Pngcs.Chunks.PngChunk.GetOrderingConstraint().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite().
mustGoBeforeIDAT()
internal bool Hjg.Pngcs.Chunks.PngChunk.mustGoBeforeIDAT () inline private
Definition at line 142 of file PngChunk.cs.
{
             ChunkOrderingConstraint oc = GetOrderingConstraint();
             return oc == ChunkOrderingConstraint.BEFORE_IDAT || oc == ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT || oc == ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT;
         }
References Hjg.Pngcs.Chunks.PngChunk.GetOrderingConstraint().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite().
mustGoBeforePLTE()
internal bool Hjg.Pngcs.Chunks.PngChunk.mustGoBeforePLTE () inline private
Definition at line 138 of file PngChunk.cs.
{
             return GetOrderingConstraint() == ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT;
         }
References Hjg.Pngcs.Chunks.PngChunk.GetOrderingConstraint().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite().
ParseFromRaw()
abstract void Hjg.Pngcs.Chunks.PngChunk.ParseFromRaw (ChunkRaw c) pure virtual
Deserialization. Given a Raw chunk, just rad, fills this chunk content
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkTEXT, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkIEND, and Hjg.Pngcs.Chunks.PngChunkSkipped.
Referenced by Hjg.Pngcs.Chunks.PngChunk.Factory().
ToString()
override String Hjg.Pngcs.Chunks.PngChunk.ToString () inline
Basic info: Id, length, Type name
Returns
Definition at line 204 of file PngChunk.cs.
{
             return "chunk id= " + Id + " (len=" + Length + " off=" + Offset +") c=" + GetType().Name;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id, Hjg.Pngcs.Chunks.PngChunk.Length, and Hjg.Pngcs.Chunks.PngChunk.Offset.
write()
internal void Hjg.Pngcs.Chunks.PngChunk.write (Stream os) inline private
Definition at line 194 of file PngChunk.cs.
{
             ChunkRaw c = CreateRawChunk();
             if (c == null)
                 throw new PngjException("null chunk ! creation failed for " + this);
             c.WriteChunk(os);
         }
References Hjg.Pngcs.Chunks.PngChunk.CreateRawChunk(), and Hjg.Pngcs.Chunks.ChunkRaw.WriteChunk().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
Member Data Documentation
Crit
readonly bool Hjg.Pngcs.Chunks.PngChunk.Crit
Standard basic properties, implicit in the Id
Definition at line 32 of file PngChunk.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), and Hjg.Pngcs.PngReader.ReadChunk().
factoryMap
Dictionary<String, Type> Hjg.Pngcs.Chunks.PngChunk.factoryMap = initFactory() static private
Definition at line 94 of file PngChunk.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunk.FactoryFromId(), Hjg.Pngcs.Chunks.PngChunk.FactoryRegister(), and Hjg.Pngcs.Chunks.PngChunk.isKnown().
Id
readonly String Hjg.Pngcs.Chunks.PngChunk.Id
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
Definition at line 28 of file PngChunk.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkSingle.Equals(), Hjg.Pngcs.Chunks.ChunkHelper.Equivalent(), Hjg.Pngcs.Chunks.ChunksList.GetChunksKeys(), Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode(), Hjg.Pngcs.Chunks.ChunkPredicateId.Matches(), Hjg.Pngcs.Chunks.ChunkPredicateId2.Matches(), Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite(), Hjg.Pngcs.Chunks.PngChunk.ToString(), and Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
ImgInfo
readonly ImageInfo Hjg.Pngcs.Chunks.PngChunk.ImgInfo protected
Image basic info, mostly for some checks
Definition at line 37 of file PngChunk.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetGray(), Hjg.Pngcs.Chunks.PngChunkSBIT.GetLen(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetRGB(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetRGB(), Hjg.Pngcs.Chunks.PngChunkSBIT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkHIST.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTRNS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.setIndexEntryAsTransparent(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetRGB(), and Hjg.Pngcs.Chunks.PngChunkBKGD.SetRGB().
Pub
readonly bool Hjg.Pngcs.Chunks.PngChunk.Pub private
Definition at line 32 of file PngChunk.cs.
Safe
readonly bool Hjg.Pngcs.Chunks.PngChunk.Safe private
Definition at line 32 of file PngChunk.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks().
Property Documentation
ChunkGroup
int Hjg.Pngcs.Chunks.PngChunk.ChunkGroup get set
Chunk group where it was read or writen
Definition at line 46 of file PngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite(), Hjg.Pngcs.Chunks.ChunksList.ToStringFull(), and Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
Length
int Hjg.Pngcs.Chunks.PngChunk.Length get set
Definition at line 48 of file PngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.PngChunk.Factory(), Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), Hjg.Pngcs.Chunks.PngChunkSkipped.PngChunkSkipped(), and Hjg.Pngcs.Chunks.PngChunk.ToString().
Offset
long Hjg.Pngcs.Chunks.PngChunk.Offset get set
Definition at line 49 of file PngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), Hjg.Pngcs.PngReader.ReadChunk(), and Hjg.Pngcs.Chunks.PngChunk.ToString().
Priority
bool Hjg.Pngcs.Chunks.PngChunk.Priority get set
For writing. Queued chunks with high priority will be written as soon as possible
Definition at line 42 of file PngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.PngChunk.PngChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/ThirdParty/Required/Hjg.Pngcs/Chunks/PngChunk.cs