Juniper: Juniper.Widgets.FollowObject Class Reference
Juniper.Widgets.FollowObject Class Reference
Make one object's pose follow the pose of another object.
Public Member Functions
void SetTarget (Transform target)
Change the follow target at runtime.
void Reparent (Transform target)
Achieve the target following by re-parenting this gameObject to the target object. The FollowObject component will be removed in the process.
void Update ()
void LateUpdate ()
The object following is performed in the LateUpdate function to make sure that it occurs after the target's own Update function, where it is most likely to have its pose updated.
void Skip ()
void Copy (AbstractFollowSettings other)
Public Attributes
Transform followObject
The target object. Set followMainCamera to false or else it will be overwritten at runtime.
CartesianAxisFlags FollowPosition = CartesianAxisFlags.XZ
bool interpolatePosition = true
float FollowPositionThreshold = 0
The maximum allowable deviation in distance from the target's position.
float maxSpeed = 1
float Distance = 0
The distance to maintain from the target object.
CartesianAxisFlags FollowRotation
Follow the target's rotation in the X-Axis.
bool interpolateRotation = true
Vector3 FollowRotationThreshold = 10 * Vector3.up
The maximum allowable deviation in angles from the target's rotation..
float maxRotationRate = 10
Private Member Functions
void SetRate (CartesianAxisFlags follow, bool interpolate, Vector3 current, Vector3 end, ref Vector3 actual, ref Vector3 target, float maxRate, Action skip)
Vector3 NextPosition (float dt)
Quaternion NextRotation (float dt)
void SkipToRotation ()
void SkipToPosition ()
Vector3 GetEndPosition ()
Vector3 GetEndRotationEuler ()
Private Attributes
const float CLOSE_THRESHOLD = 0.01f
const float MAX_TIME = 1.5f
Vector3 targetVelocity
Vector3 velocity
Vector3 targetRotationRate
Vector3 rotationRate
Detailed Description
Make one object's pose follow the pose of another object.
Definition at line 12 of file FollowObject.cs.
Member Function Documentation
Copy()
void Juniper.Widgets.AbstractFollowSettings.Copy (AbstractFollowSettings other) inline inherited
Definition at line 46 of file AbstractFollowSettings.cs.
         {
             FollowPosition = other.FollowPosition;
             interpolatePosition = other.interpolatePosition;
             FollowPositionThreshold = other.FollowPositionThreshold;
             maxSpeed = other.maxSpeed;
             Distance = other.Distance;
             FollowRotation = other.FollowRotation;
             interpolateRotation = other.interpolateRotation;
             FollowRotationThreshold = other.FollowRotationThreshold;
             maxRotationRate = other.maxRotationRate;
         }
References Juniper.Widgets.AbstractFollowSettings.Distance, Juniper.Widgets.AbstractFollowSettings.FollowPosition, Juniper.Widgets.AbstractFollowSettings.FollowPositionThreshold, Juniper.Widgets.AbstractFollowSettings.FollowRotation, Juniper.Widgets.AbstractFollowSettings.FollowRotationThreshold, Juniper.Widgets.AbstractFollowSettings.interpolatePosition, Juniper.Widgets.AbstractFollowSettings.interpolateRotation, Juniper.Widgets.AbstractFollowSettings.maxRotationRate, and Juniper.Widgets.AbstractFollowSettings.maxSpeed.
Referenced by Juniper.Widgets.FollowPlatformSettings.Awake(), and Juniper.Widgets.FollowPlatformSettings.OnValidate().
GetEndPosition()
Vector3 Juniper.Widgets.FollowObject.GetEndPosition () inline private
Definition at line 157 of file FollowObject.cs.
         {
             var end = followObject.position + (Distance * transform.forward);
             var delta = end - transform.position;
             if ((FollowPosition & CartesianAxisFlags.X) == 0)
             {
                 delta.x = 0;
             }
             if ((FollowPosition & CartesianAxisFlags.Y) == 0)
             {
                 delta.y = 0;
             }
             if ((FollowPosition & CartesianAxisFlags.Z) == 0)
             {
                 delta.z = 0;
             }
             if (delta.magnitude < FollowPositionThreshold && velocity.magnitude == 0)
             {
                 delta = Vector3.zero;
             }
             return delta + transform.position;
         }
References Juniper.Widgets.AbstractFollowSettings.Distance, Juniper.Widgets.FollowObject.followObject, Juniper.Widgets.AbstractFollowSettings.FollowPosition, Juniper.Widgets.AbstractFollowSettings.FollowPositionThreshold, and Juniper.Widgets.FollowObject.velocity.
Referenced by Juniper.Widgets.FollowObject.SkipToPosition(), and Juniper.Widgets.FollowObject.Update().
GetEndRotationEuler()
Vector3 Juniper.Widgets.FollowObject.GetEndRotationEuler () inline private
Definition at line 185 of file FollowObject.cs.
         {
             var startEul = transform.eulerAngles;
             var endEul = followObject.eulerAngles;
             var deltaEul = endEul - startEul;
             var rotationSpeed = rotationRate.magnitude;
             if ((FollowRotation & CartesianAxisFlags.X) == 0
                 || rotationSpeed == 0
                     && Mathf.Abs(deltaEul.x) < Mathf.Abs(FollowRotationThreshold.x))
             {
                 deltaEul.x = 0;
             }
             if ((FollowRotation & CartesianAxisFlags.Y) == 0
                 || rotationSpeed == 0
                     && Mathf.Abs(deltaEul.y) < Mathf.Abs(FollowRotationThreshold.y))
             {
                 deltaEul.y = 0;
             }
             if ((FollowRotation & CartesianAxisFlags.Z) == 0
                 || rotationSpeed == 0
                     && Mathf.Abs(deltaEul.z) < Mathf.Abs(FollowRotationThreshold.z))
             {
                 deltaEul.z = 0;
             }
             var angX = new Angle(startEul.x);
             var angY = new Angle(startEul.y);
             var angZ = new Angle(startEul.z);
             angX += deltaEul.x;
             angY += deltaEul.y;
             angZ += deltaEul.z;
             return new Vector3(angX, angY, angZ);
         }
References Juniper.Widgets.FollowObject.followObject, Juniper.Widgets.AbstractFollowSettings.FollowRotation, Juniper.Widgets.AbstractFollowSettings.FollowRotationThreshold, and Juniper.Widgets.FollowObject.rotationRate.
Referenced by Juniper.Widgets.FollowObject.SkipToRotation(), and Juniper.Widgets.FollowObject.Update().
LateUpdate()
void Juniper.Widgets.FollowObject.LateUpdate () inline
The object following is performed in the LateUpdate function to make sure that it occurs after the target's own Update function, where it is most likely to have its pose updated.
Definition at line 101 of file FollowObject.cs.
         {
             if (FollowPosition != CartesianAxisFlags.None
                 && interpolatePosition)
             {
                 transform.position = NextPosition(Time.deltaTime);
             }
             if (FollowRotation != CartesianAxisFlags.None
                 && interpolateRotation)
             {
                 transform.rotation = NextRotation(Time.deltaTime);
             }
         }
References Juniper.Widgets.AbstractFollowSettings.FollowPosition, Juniper.Widgets.AbstractFollowSettings.FollowRotation, Juniper.Widgets.AbstractFollowSettings.interpolatePosition, Juniper.Widgets.AbstractFollowSettings.interpolateRotation, Juniper.Widgets.FollowObject.NextPosition(), Juniper.Widgets.FollowObject.NextRotation(), and Juniper.Units.Time.
NextPosition()
Vector3 Juniper.Widgets.FollowObject.NextPosition (float dt) inline private
Definition at line 129 of file FollowObject.cs.
         {
             return transform.position + velocity * dt;
         }
References Juniper.Widgets.FollowObject.velocity.
Referenced by Juniper.Widgets.FollowObject.LateUpdate().
NextRotation()
Quaternion Juniper.Widgets.FollowObject.NextRotation (float dt) inline private
Definition at line 134 of file FollowObject.cs.
         {
             return Quaternion.Euler(rotationRate * dt) * transform.rotation;
         }
References Juniper.Widgets.FollowObject.rotationRate.
Referenced by Juniper.Widgets.FollowObject.LateUpdate().
Reparent()
void Juniper.Widgets.FollowObject.Reparent (Transform target) inline
Achieve the target following by re-parenting this gameObject to the target object. The FollowObject component will be removed in the process.
Parameters
target Target.
Definition at line 40 of file FollowObject.cs.
         {
             transform.Reparent(target, false);
             enabled = false;
             this.DestroyImmediate();
         }
SetRate()
void Juniper.Widgets.FollowObject.SetRate (CartesianAxisFlags follow, bool interpolate, Vector3 current, Vector3 end, ref Vector3 actual, ref Vector3 target, float maxRate, Action skip) inline private
Definition at line 47 of file FollowObject.cs.
         {
             if (follow != CartesianAxisFlags.None)
             {
                 if (interpolate)
                 {
                     var delta = end - current;
                     var displacement = delta.magnitude;
                     var time = displacement / maxRate;
                     if (displacement < CLOSE_THRESHOLD || time > MAX_TIME)
                     {
                         skip();
                     }
                     else
                     {
                         target = delta / Time.deltaTime;
                         var speed = target.magnitude;
                         if (speed > maxRate)
{
                             target *= maxRate / speed;
                         }
                         actual = Vector3.Lerp(actual, target, 0.5f);
                     }
                 }
                 else
                 {
                     skip();
                 }
             }
         }
References Juniper.Widgets.FollowObject.MAX_TIME, and Juniper.Units.Time.
Referenced by Juniper.Widgets.FollowObject.Update().
SetTarget()
void Juniper.Widgets.FollowObject.SetTarget (Transform target) inline
Change the follow target at runtime.
Parameters
target Target.
Definition at line 30 of file FollowObject.cs.
         {
             followObject = target;
         }
References Juniper.Widgets.FollowObject.followObject.
Skip()
void Juniper.Widgets.FollowObject.Skip () inline
Definition at line 116 of file FollowObject.cs.
         {
             if (FollowPosition != CartesianAxisFlags.None)
             {
                 SkipToPosition();
             }
             if (FollowRotation != CartesianAxisFlags.None)
             {
                 SkipToRotation();
             }
         }
References Juniper.Widgets.AbstractFollowSettings.FollowPosition, Juniper.Widgets.AbstractFollowSettings.FollowRotation, Juniper.Widgets.FollowObject.SkipToPosition(), and Juniper.Widgets.FollowObject.SkipToRotation().
Referenced by Juniper.Widgets.FollowMainCamera.OnEnable().
SkipToPosition()
void Juniper.Widgets.FollowObject.SkipToPosition () inline private
Definition at line 148 of file FollowObject.cs.
         {
             var end = GetEndPosition();
             transform.position = end;
             targetVelocity
                 = velocity
                 = Vector3.zero;
         }
References Juniper.Widgets.FollowObject.GetEndPosition(), Juniper.Widgets.FollowObject.targetVelocity, and Juniper.Widgets.FollowObject.velocity.
Referenced by Juniper.Widgets.FollowObject.Skip(), and Juniper.Widgets.FollowObject.Update().
SkipToRotation()
void Juniper.Widgets.FollowObject.SkipToRotation () inline private
Definition at line 139 of file FollowObject.cs.
         {
             var endEul = GetEndRotationEuler();
             transform.rotation = Quaternion.Euler(endEul);
             targetRotationRate
                 = rotationRate
                 = Vector3.zero;
         }
References Juniper.Widgets.FollowObject.GetEndRotationEuler(), Juniper.Widgets.FollowObject.rotationRate, and Juniper.Widgets.FollowObject.targetRotationRate.
Referenced by Juniper.Widgets.FollowObject.Skip(), and Juniper.Widgets.FollowObject.Update().
Update()
void Juniper.Widgets.FollowObject.Update () inline
Definition at line 80 of file FollowObject.cs.
         {
             SetRate(
                 FollowPosition, interpolatePosition,
                 transform.position, GetEndPosition(),
                 ref velocity, ref targetVelocity,
                 maxSpeed,
                 SkipToPosition);
             SetRate(
                 FollowRotation, interpolateRotation,
                 transform.eulerAngles, GetEndRotationEuler(),
                 ref rotationRate, ref targetRotationRate,
                 maxRotationRate,
                 SkipToRotation);
         }
References Juniper.Widgets.AbstractFollowSettings.FollowPosition, Juniper.Widgets.AbstractFollowSettings.FollowRotation, Juniper.Widgets.FollowObject.GetEndPosition(), Juniper.Widgets.FollowObject.GetEndRotationEuler(), Juniper.Widgets.AbstractFollowSettings.interpolatePosition, Juniper.Widgets.AbstractFollowSettings.interpolateRotation, Juniper.Widgets.AbstractFollowSettings.maxRotationRate, Juniper.Widgets.AbstractFollowSettings.maxSpeed, Juniper.Widgets.FollowObject.rotationRate, Juniper.Widgets.FollowObject.SetRate(), Juniper.Widgets.FollowObject.SkipToPosition(), Juniper.Widgets.FollowObject.SkipToRotation(), Juniper.Widgets.FollowObject.targetRotationRate, Juniper.Widgets.FollowObject.targetVelocity, and Juniper.Widgets.FollowObject.velocity.
Member Data Documentation
CLOSE_THRESHOLD
const float Juniper.Widgets.FollowObject.CLOSE_THRESHOLD = 0.01f private
Definition at line 14 of file FollowObject.cs.
Distance
float Juniper.Widgets.AbstractFollowSettings.Distance = 0 inherited
The distance to maintain from the target object.
Definition at line 29 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), and Juniper.Widgets.FollowObject.GetEndPosition().
followObject
Transform Juniper.Widgets.FollowObject.followObject
The target object. Set followMainCamera to false or else it will be overwritten at runtime.
Definition at line 21 of file FollowObject.cs.
Referenced by Juniper.Widgets.FollowMainCamera.Awake(), Juniper.Widgets.FollowObject.GetEndPosition(), Juniper.Widgets.FollowObject.GetEndRotationEuler(), and Juniper.Widgets.FollowObject.SetTarget().
FollowPosition
CartesianAxisFlags Juniper.Widgets.AbstractFollowSettings.FollowPosition = CartesianAxisFlags.XZ inherited
Definition at line 15 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), Juniper.Widgets.FollowObject.GetEndPosition(), Juniper.Widgets.FollowObject.LateUpdate(), Juniper.Widgets.FollowObject.Skip(), and Juniper.Widgets.FollowObject.Update().
FollowPositionThreshold
float Juniper.Widgets.AbstractFollowSettings.FollowPositionThreshold = 0 inherited
The maximum allowable deviation in distance from the target's position.
Definition at line 22 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), and Juniper.Widgets.FollowObject.GetEndPosition().
FollowRotation
CartesianAxisFlags Juniper.Widgets.AbstractFollowSettings.FollowRotation inherited
Follow the target's rotation in the X-Axis.
Definition at line 35 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), Juniper.Widgets.FollowObject.GetEndRotationEuler(), Juniper.Widgets.FollowObject.LateUpdate(), Juniper.Widgets.FollowObject.Skip(), and Juniper.Widgets.FollowObject.Update().
FollowRotationThreshold
Vector3 Juniper.Widgets.AbstractFollowSettings.FollowRotationThreshold = 10 * Vector3.up inherited
The maximum allowable deviation in angles from the target's rotation..
Definition at line 42 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), and Juniper.Widgets.FollowObject.GetEndRotationEuler().
interpolatePosition
bool Juniper.Widgets.AbstractFollowSettings.interpolatePosition = true inherited
Definition at line 17 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), Juniper.Widgets.FollowObject.LateUpdate(), and Juniper.Widgets.FollowObject.Update().
interpolateRotation
bool Juniper.Widgets.AbstractFollowSettings.interpolateRotation = true inherited
Definition at line 37 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), Juniper.Widgets.FollowObject.LateUpdate(), and Juniper.Widgets.FollowObject.Update().
MAX_TIME
const float Juniper.Widgets.FollowObject.MAX_TIME = 1.5f private
Definition at line 15 of file FollowObject.cs.
Referenced by Juniper.Widgets.FollowObject.SetRate().
maxRotationRate
float Juniper.Widgets.AbstractFollowSettings.maxRotationRate = 10 inherited
Definition at line 44 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), and Juniper.Widgets.FollowObject.Update().
maxSpeed
float Juniper.Widgets.AbstractFollowSettings.maxSpeed = 1 inherited
Definition at line 24 of file AbstractFollowSettings.cs.
Referenced by Juniper.Widgets.AbstractFollowSettings.Copy(), and Juniper.Widgets.FollowObject.Update().
rotationRate
Vector3 Juniper.Widgets.FollowObject.rotationRate private
Definition at line 24 of file FollowObject.cs.
Referenced by Juniper.Widgets.FollowObject.GetEndRotationEuler(), Juniper.Widgets.FollowObject.NextRotation(), Juniper.Widgets.FollowObject.SkipToRotation(), and Juniper.Widgets.FollowObject.Update().
targetRotationRate
Vector3 Juniper.Widgets.FollowObject.targetRotationRate private
Definition at line 24 of file FollowObject.cs.
Referenced by Juniper.Widgets.FollowObject.SkipToRotation(), and Juniper.Widgets.FollowObject.Update().
targetVelocity
Vector3 Juniper.Widgets.FollowObject.targetVelocity private
Definition at line 23 of file FollowObject.cs.
Referenced by Juniper.Widgets.FollowObject.SkipToPosition(), and Juniper.Widgets.FollowObject.Update().
velocity
Vector3 Juniper.Widgets.FollowObject.velocity private
Definition at line 23 of file FollowObject.cs.
Referenced by Juniper.Widgets.FollowObject.GetEndPosition(), Juniper.Widgets.FollowObject.NextPosition(), Juniper.Widgets.FollowObject.SkipToPosition(), and Juniper.Widgets.FollowObject.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Widgets/FollowObject.cs