Juniper: Juniper.World.GIS.Google.MapTiles.LinePathCollection Class Reference
Juniper.World.GIS.Google.MapTiles.LinePathCollection Class Reference
Public Member Functions
LinePathCollection (LinePathStyle style, bool encodePath, IEnumerable< string > points)
LinePathCollection (LinePathStyle style, bool encodePath, params string[] points)
LinePathCollection (LinePathStyle style, bool encodePath, IEnumerable< LatLngPoint > points)
LinePathCollection (LinePathStyle style, bool encodePath, params LatLngPoint[] points)
LinePathCollection (bool encodePath, IEnumerable< string > points)
LinePathCollection (bool encodePath, params string[] points)
LinePathCollection (bool encodePath, IEnumerable< LatLngPoint > points)
LinePathCollection (bool encodePath, params LatLngPoint[] points)
LinePathCollection (LinePathStyle style, IEnumerable< string > points)
LinePathCollection (LinePathStyle style, params string[] points)
LinePathCollection (LinePathStyle style, IEnumerable< LatLngPoint > points)
LinePathCollection (LinePathStyle style, params LatLngPoint[] points)
LinePathCollection (IEnumerable< string > points)
LinePathCollection (params string[] points)
LinePathCollection (IEnumerable< LatLngPoint > points)
LinePathCollection (params LatLngPoint[] points)
override string ToString ()
int IndexOf (string item)
void Insert (int index, string item)
void Insert (int index, LatLngPoint item)
void RemoveAt (int index)
void Add (string item)
void Add (LatLngPoint item)
void Clear ()
bool Contains (string item)
bool Contains (LatLngPoint item)
void CopyTo (string[] array, int arrayIndex)
bool Remove (string item)
bool Remove (LatLngPoint item)
IEnumerator< string > GetEnumerator ()
Static Public Member Functions
static int EncodePolylinePart (StringBuilder sb, double part, ref int firstPart)
static string EncodePolyline (IEnumerable< string > points)
static void EncodePolylineEntry (StringBuilder sb, string point, ref int firstLat, ref int firstLng)
Public Attributes
int Count => Points.Count
bool IsReadOnly => ((IList<string>)Points).IsReadOnly
Properties
LinePathStyle Style [get]
List< string > Points [get]
bool EncodePath [get]
string this[int index] [get, set]
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Detailed Description
Definition at line 12 of file LinePathCollection.cs.
Constructor & Destructor Documentation
LinePathCollection() [1/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, bool encodePath, IEnumerable< string > points) inline
Definition at line 20 of file LinePathCollection.cs.
         {
             if (points is null)
             {
                 throw new ArgumentNullException(nameof(points));
             }
             Style = style ?? throw new ArgumentNullException(nameof(style));
             EncodePath = encodePath;
             Points = new List<string>(points);
             if (Points.Count < 2)
             {
                 throw new ArgumentException("There needs to be at least 2 points in a path for it to be renderable.", nameof(points));
             }
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePath, Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points, and Juniper.World.GIS.Google.MapTiles.LinePathCollection.Style.
LinePathCollection() [2/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, bool encodePath, params string [] points) inline
Definition at line 37 of file LinePathCollection.cs.
             : this(style, encodePath, points.AsEnumerable()) { }
LinePathCollection() [3/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, bool encodePath, IEnumerable< LatLngPoint > points) inline
Definition at line 40 of file LinePathCollection.cs.
             : this(style, encodePath, points.Select(p => p.ToString(CultureInfo.InvariantCulture))) { }
LinePathCollection() [4/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, bool encodePath, params LatLngPoint [] points) inline
Definition at line 43 of file LinePathCollection.cs.
             : this(style, encodePath, points.AsEnumerable()) { }
LinePathCollection() [5/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (bool encodePath, IEnumerable< string > points) inline
Definition at line 46 of file LinePathCollection.cs.
             : this(default, encodePath, points) { }
LinePathCollection() [6/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (bool encodePath, params string [] points) inline
Definition at line 49 of file LinePathCollection.cs.
             : this(default, encodePath, points) { }
LinePathCollection() [7/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (bool encodePath, IEnumerable< LatLngPoint > points) inline
Definition at line 52 of file LinePathCollection.cs.
             : this(default, encodePath, points) { }
LinePathCollection() [8/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (bool encodePath, params LatLngPoint [] points) inline
Definition at line 55 of file LinePathCollection.cs.
             : this(default, encodePath, points) { }
LinePathCollection() [9/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, IEnumerable< string > points) inline
Definition at line 58 of file LinePathCollection.cs.
             : this(style, false, points) { }
LinePathCollection() [10/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, params string [] points) inline
Definition at line 61 of file LinePathCollection.cs.
             : this(style, false, points) { }
LinePathCollection() [11/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, IEnumerable< LatLngPoint > points) inline
Definition at line 64 of file LinePathCollection.cs.
             : this(style, false, points) { }
LinePathCollection() [12/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (LinePathStyle style, params LatLngPoint [] points) inline
Definition at line 67 of file LinePathCollection.cs.
             : this(style, false, points) { }
LinePathCollection() [13/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (IEnumerable< string > points) inline
Definition at line 70 of file LinePathCollection.cs.
             : this(default, false, points) { }
LinePathCollection() [14/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (params string [] points) inline
Definition at line 73 of file LinePathCollection.cs.
             : this(default, false, points) { }
LinePathCollection() [15/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (IEnumerable< LatLngPoint > points) inline
Definition at line 76 of file LinePathCollection.cs.
             : this(default, false, points) { }
LinePathCollection() [16/16]
Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection (params LatLngPoint [] points) inline
Definition at line 79 of file LinePathCollection.cs.
             : this(default, false, points) { }
Member Function Documentation
Add() [1/2]
void Juniper.World.GIS.Google.MapTiles.LinePathCollection.Add (string item) inline
Definition at line 205 of file LinePathCollection.cs.
         {
             Points.Add(item);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
Add() [2/2]
void Juniper.World.GIS.Google.MapTiles.LinePathCollection.Add (LatLngPoint item) inline
Definition at line 210 of file LinePathCollection.cs.
         {
             if (item is null)
             {
                 throw new ArgumentNullException(nameof(item));
             }
             Points.Add(item.ToString(CultureInfo.InvariantCulture));
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points, and Juniper.World.GIS.LatLngPoint.ToString().
Clear()
void Juniper.World.GIS.Google.MapTiles.LinePathCollection.Clear () inline
Definition at line 220 of file LinePathCollection.cs.
         {
             Points.Clear();
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
Contains() [1/2]
bool Juniper.World.GIS.Google.MapTiles.LinePathCollection.Contains (string item) inline
Definition at line 225 of file LinePathCollection.cs.
         {
             return Points.Contains(item);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.Contains().
Contains() [2/2]
bool Juniper.World.GIS.Google.MapTiles.LinePathCollection.Contains (LatLngPoint item) inline
Definition at line 230 of file LinePathCollection.cs.
         {
             if (item is null)
             {
                 throw new ArgumentNullException(nameof(item));
             }
             return Contains(item.ToString(CultureInfo.InvariantCulture));
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Contains(), and Juniper.World.GIS.LatLngPoint.ToString().
CopyTo()
void Juniper.World.GIS.Google.MapTiles.LinePathCollection.CopyTo (string [] array, int arrayIndex) inline
Definition at line 240 of file LinePathCollection.cs.
         {
             Points.CopyTo(array, arrayIndex);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
EncodePolyline()
static string Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolyline (IEnumerable< string > points) inline static
Definition at line 148 of file LinePathCollection.cs.
         {
             if (points is null)
             {
                 throw new ArgumentNullException(nameof(points));
             }
             var sb = new StringBuilder();
             var lastLat = 0;
             var lastLng = 0;
             foreach (var point in points)
             {
                 EncodePolylineEntry(sb, point, ref lastLat, ref lastLng);
             }
             return sb.ToString();
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolylineEntry().
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.ToString().
EncodePolylineEntry()
static void Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolylineEntry (StringBuilder sb, string point, ref int firstLat, ref int firstLng) inline static
Definition at line 166 of file LinePathCollection.cs.
         {
             var parts = point.SplitX(',');
             var values = parts.Select(p => double.Parse(p.Trim(), CultureInfo.InvariantCulture)).ToArray();
             _ = EncodePolylinePart(sb, values[0], ref firstLat);
             _ = EncodePolylinePart(sb, values[1], ref firstLng);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolylinePart().
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolyline().
EncodePolylinePart()
static int Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolylinePart (StringBuilder sb, double part, ref int firstPart) inline static
Definition at line 110 of file LinePathCollection.cs.
         {
             if (sb is null)
             {
                 throw new ArgumentNullException(nameof(sb));
             }
             var val = (int)Round(part * 1e5);
             var delta = val - firstPart;
             firstPart = val;
             var comp = delta << 1;
             if (part < 0)
             {
                 comp = ~comp;
             }
             const int CHUNK_SIZE = 5;
             var binString = Convert.ToString(comp, 2);
             var numGroups = (int)Ceiling((float)binString.Length / CHUNK_SIZE);
             var paddedLen = numGroups * CHUNK_SIZE;
             binString = binString.PadLeft(paddedLen, '0');
             for (var i = numGroups - 1; i >= 0; --i)
             {
                 var chunk = binString.Substring(i * CHUNK_SIZE, CHUNK_SIZE);
                 var dec = Convert.ToInt32(chunk, 2);
                 if (i > 0)
                 {
                     dec |= 0x20;
                 }
                 dec += 63;
                 _ = sb.Append((char)dec);
             }
             return val;
         }
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolylineEntry().
GetEnumerator() [1/2]
IEnumerator<string> Juniper.World.GIS.Google.MapTiles.LinePathCollection.GetEnumerator () inline
Definition at line 264 of file LinePathCollection.cs.
         {
             return ((IList<string>)Points).GetEnumerator();
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.World.GIS.Google.MapTiles.LinePathCollection.GetEnumerator () inline private
Definition at line 269 of file LinePathCollection.cs.
         {
             return ((IList<string>)Points).GetEnumerator();
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
IndexOf()
int Juniper.World.GIS.Google.MapTiles.LinePathCollection.IndexOf (string item) inline
Definition at line 174 of file LinePathCollection.cs.
         {
             return Points.IndexOf(item);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
Insert() [1/2]
void Juniper.World.GIS.Google.MapTiles.LinePathCollection.Insert (int index, string item) inline
Definition at line 179 of file LinePathCollection.cs.
         {
             Points.Insert(index, item);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
Insert() [2/2]
void Juniper.World.GIS.Google.MapTiles.LinePathCollection.Insert (int index, LatLngPoint item) inline
Definition at line 184 of file LinePathCollection.cs.
         {
             if (item is null)
             {
                 throw new ArgumentNullException(nameof(item));
             }
             Points.Insert(index, item.ToString(CultureInfo.InvariantCulture));
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points, and Juniper.World.GIS.LatLngPoint.ToString().
Remove() [1/2]
bool Juniper.World.GIS.Google.MapTiles.LinePathCollection.Remove (string item) inline
Definition at line 245 of file LinePathCollection.cs.
         {
             return Points.Remove(item);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.Remove().
Remove() [2/2]
bool Juniper.World.GIS.Google.MapTiles.LinePathCollection.Remove (LatLngPoint item) inline
Definition at line 250 of file LinePathCollection.cs.
         {
             if (item is null)
             {
                 throw new ArgumentNullException(nameof(item));
             }
             return Remove(item.ToString(CultureInfo.InvariantCulture));
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Remove(), and Juniper.World.GIS.LatLngPoint.ToString().
RemoveAt()
void Juniper.World.GIS.Google.MapTiles.LinePathCollection.RemoveAt (int index) inline
Definition at line 194 of file LinePathCollection.cs.
         {
             Points.RemoveAt(index);
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points.
ToString()
override string Juniper.World.GIS.Google.MapTiles.LinePathCollection.ToString () inline
Definition at line 82 of file LinePathCollection.cs.
         {
             var sb = new StringBuilder();
             var delim = "";
             if (Style != default)
             {
                 _ = sb.Append(Style);
                 delim = "|";
             }
             if (EncodePath)
             {
                 _ = sb.Append("enc:")
                   .Append(EncodePolyline(Points));
             }
             else
             {
                 foreach (var point in Points)
                 {
                     _ = sb.Append(delim)
                       .Append(point);
                     delim = "|";
                 }
             }
             return sb.ToString();
         }
References Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePath, Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePolyline(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points, and Juniper.World.GIS.Google.MapTiles.LinePathCollection.Style.
Member Data Documentation
Count
int Juniper.World.GIS.Google.MapTiles.LinePathCollection.Count => Points.Count
Definition at line 260 of file LinePathCollection.cs.
IsReadOnly
bool Juniper.World.GIS.Google.MapTiles.LinePathCollection.IsReadOnly => ((IList<string>)Points).IsReadOnly
Definition at line 262 of file LinePathCollection.cs.
Property Documentation
EncodePath
bool Juniper.World.GIS.Google.MapTiles.LinePathCollection.EncodePath get
Definition at line 18 of file LinePathCollection.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection(), and Juniper.World.GIS.Google.MapTiles.LinePathCollection.ToString().
Points
List<string> Juniper.World.GIS.Google.MapTiles.LinePathCollection.Points get
Definition at line 16 of file LinePathCollection.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.Add(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Clear(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Contains(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.CopyTo(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.GetEnumerator(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.IndexOf(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Insert(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Remove(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.RemoveAt(), and Juniper.World.GIS.Google.MapTiles.LinePathCollection.ToString().
Style
LinePathStyle Juniper.World.GIS.Google.MapTiles.LinePathCollection.Style get
Definition at line 14 of file LinePathCollection.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.LinePathCollection(), and Juniper.World.GIS.Google.MapTiles.LinePathCollection.ToString().
this[int index]
string Juniper.World.GIS.Google.MapTiles.LinePathCollection.this[int index] get set
Definition at line 200 of file LinePathCollection.cs.
         {
             get { return Points[index]; }
             set { Points[index] = value; }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/MapTiles/LinePathCollection.cs