Juniper: Juniper.World.LightMeasurement Class Reference
Juniper.World.LightMeasurement Class Reference
Abstracts the measurement of light intensity from camera frames for Augmented Reality Light Estimation. This component executes in edit mode.
Public Member Functions
void Awake ()
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
void Install ()
void Uninstall ()
void Update ()
Check to see if the ARCore light estimation has been updated.
Public Attributes
bool useFake
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
float Intensity = 0.8f
The fake intensity value to use if UseFakeIntensity is true.
Color Color = Color.white
The fake color to use if UseFakeIntensity is true.
bool useCustomAnalyzer
Set to true to use the custom image analyzer when running Vuforia. This is mostly only useful on Android for Vuforia v7.1.
bool DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Color ColorEstimate
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
float IntensityEstimate
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Properties
bool UseFakeIntensity [get]
Returns true if the user has requested a fake intensity, or the application is running in the Unity Editor.
Private Member Functions
void SetFakeValues ()
Sets the current Intensity and Color from the fake values set in the Unity Editor.
IEnumerator GetIlluminationManagerCoroutine ()
Waits for a tracker manager, a state manager, and an illumination manager.
void GetAveragePixelIntensity (Vuforia.Image image, GetPixelFromBuffer pixelGetter)
Calculates an average pixel value in HSV space for the given image format.
void Start ()
Sets up the ARKit light estimation system.
void UnityARSessionNativeInterface_ARFrameUpdatedEvent (UnityARCamera camera)
Process the ARKit light estimation values.
void Start ()
Sets up the ARCore light estimation system.
void PrintDebugReport ()
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Private Attributes
float lastIntensity
Light estimate updates happen concurrently with frame updates. This value stores the last light intesity measurement that was calculated, for use in the current render frame.
Color lastColor
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
VuforiaImageAnalyzer analyzer
If useCustomAnalyzer is set to true, this is the image analyzer that performs the light estimation.
const int NumSampleRows = 10
If useCustomAnalyzer is set to true, this is the number of rows in the camera feed that will be sampled to make the light estimation.
const int NumSamplesPerRow = 10
If useCustomAnalyzer is set to true, this is the number of columns in the camera feed that will be sampled to make the light estimation.
IlluminationManager illumination
If useCustomAnalyzer is set to false, Vuforia's built-in light estimation is used. This will be based on ARKit or ARCore, depending on the underlying runtime platform.
Detailed Description
Abstracts the measurement of light intensity from camera frames for Augmented Reality Light Estimation. This component executes in edit mode.
Definition at line 21 of file LightMeasurement.cs.
Member Function Documentation
Awake()
void Juniper.World.LightMeasurement.Awake () inline
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
Definition at line 135 of file LightMeasurement.cs.
         {
             Install();
             SetFakeValues();
 #if VUFORIA
             if (Application.isPlaying)
             {
                 if (VuforiaUnityExt.HasLightEstimation && !useCustomAnalyzer)
                 {
                     StartCoroutine(GetIlluminationManagerCoroutine());
                 }
                 else
                 {
                     analyzer.imageAnalyzer = GetAveragePixelIntensity;
                 }
             }
 #endif
         }
References Juniper.World.LightMeasurement.analyzer, Juniper.World.LightMeasurement.GetAveragePixelIntensity(), Juniper.World.LightMeasurement.GetIlluminationManagerCoroutine(), Juniper.World.LightMeasurement.Install(), Juniper.World.LightMeasurement.SetFakeValues(), and Juniper.World.LightMeasurement.useCustomAnalyzer.
GetAveragePixelIntensity()
void Juniper.World.LightMeasurement.GetAveragePixelIntensity (Vuforia.Image image, GetPixelFromBuffer pixelGetter) inline private
Calculates an average pixel value in HSV space for the given image format.
Parameters
image Image.
pixelGetter Pixel getter.
Definition at line 207 of file LightMeasurement.cs.
         {
             float avgH, avgS, avgV;
             avgH = avgS = avgV = 0;
             int bytesPerPixel = image.Stride / image.Width;
             int numPixels = image.Width * image.Height;
             for (int r = 0; r < NumSampleRows; ++r)
             {
                 int y = Random.Range(0, image.Height);
                 for (int c = 0; c < NumSamplesPerRow; ++c)
                 {
                     int x = Random.Range(0, image.Width);
                     int i = y * image.Stride + x * bytesPerPixel;
                     Color pixel = pixelGetter(image.Pixels, i);
                     float h, s, v;
                     Color.RGBToHSV(pixel, out h, out s, out v);
                     avgH += h / numPixels;
                     avgS += s / numPixels;
                     avgV += v / numPixels;
                 }
             }
             lastIntensity = avgV;
             lastColor = Color.HSVToRGB(avgH, avgS, avgV);
         }
References Juniper.World.LightMeasurement.Color, Juniper.World.LightMeasurement.lastColor, Juniper.World.LightMeasurement.lastIntensity, Juniper.World.LightMeasurement.NumSampleRows, and Juniper.World.LightMeasurement.NumSamplesPerRow.
Referenced by Juniper.World.LightMeasurement.Awake().
GetIlluminationManagerCoroutine()
IEnumerator Juniper.World.LightMeasurement.GetIlluminationManagerCoroutine () inline private
Waits for a tracker manager, a state manager, and an illumination manager.
Returns
The illumination manager coroutine.
Definition at line 185 of file LightMeasurement.cs.
         {
             yield return new WaitUntil(() =>
                 TrackerManager.Instance != null);
             StateManager stateManager = null;
             yield return new WaitUntil(() =>
             {
                 stateManager = TrackerManager.Instance.GetStateManager();
                 return stateManager != null;
             });
             yield return new WaitUntil(() =>
             {
                 illumination = stateManager.GetIlluminationManager();
                 return illumination != null;
             });
         }
References Juniper.World.LightMeasurement.illumination.
Referenced by Juniper.World.LightMeasurement.Awake().
Install()
void Juniper.World.LightMeasurement.Install () inline
Implements Juniper.IInstallable.
Definition at line 156 of file LightMeasurement.cs.
         {
 #if VUFORIA
             analyzer = this.EnsureComponent<VuforiaImageAnalyzer>();
 #endif
         }
References Juniper.World.LightMeasurement.analyzer.
Referenced by Juniper.World.LightMeasurement.Awake().
PrintDebugReport()
void Juniper.World.LightMeasurement.PrintDebugReport () inline private
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Definition at line 326 of file LightMeasurement.cs.
         {
             if (UseFakeIntensity)
             {
                 ScreenDebugger.Print("Using fake light estimate");
             }
 #if VUFORIA
             if (illumination == null)
             {
                 if (analyzer == null)
                 {
                     ScreenDebugger.Print("No illumination manager or image analyzer");
                 }
                 else
                 {
                     if (!analyzer.Running)
                     {
                         ScreenDebugger.Print("Image analyzer is not running");
                     }
                     ScreenDebugger.Print("Image analyzer image format is {0}", VuforiaImageAnalyzer.ImageFormat);
                 }
             }
             else
             {
                 if (illumination.AmbientIntensity == null)
                 {
                     ScreenDebugger.Print("Illumination manager doesn't have an estimate");
                 }
             }
 #endif
             ScreenDebugger.Print("  Raw: int {0:0.000} col {1}", IntensityEstimate, ColorEstimate);
         }
References Juniper.World.LightMeasurement.analyzer, Juniper.World.LightMeasurement.ColorEstimate, Juniper.World.LightMeasurement.illumination, Juniper.World.LightMeasurement.IntensityEstimate, ScreenDebugger.Print(), and Juniper.World.LightMeasurement.UseFakeIntensity.
Referenced by Juniper.World.LightMeasurement.Update().
SetFakeValues()
void Juniper.World.LightMeasurement.SetFakeValues () inline private
Sets the current Intensity and Color from the fake values set in the Unity Editor.
Definition at line 173 of file LightMeasurement.cs.
         {
             lastIntensity = Intensity;
             lastColor = Color.Scale(lastIntensity);
         }
References Juniper.World.LightMeasurement.Color, Juniper.World.LightMeasurement.Intensity, Juniper.World.LightMeasurement.lastColor, and Juniper.World.LightMeasurement.lastIntensity.
Referenced by Juniper.World.LightMeasurement.Awake(), and Juniper.World.LightMeasurement.Update().
Start() [1/2]
void Juniper.World.LightMeasurement.Start () inline private
Sets up the ARKit light estimation system.
Definition at line 242 of file LightMeasurement.cs.
         {
             if(!Application.isEditor)
             {
                 UnityARSessionNativeInterface.ARFrameUpdatedEvent += UnityARSessionNativeInterface_ARFrameUpdatedEvent;
                 var arkit = this.FindAny<UnityARCameraManager>();
                 if(arkit == null)
                 {
                     Debug.LogWarning("Could not find UnityARCameraManager");
                 }
                 else
                 {
                     arkit.enableLightEstimation = true;
                 }
             }
         }
References Juniper.World.LightMeasurement.UnityARSessionNativeInterface_ARFrameUpdatedEvent().
Start() [2/2]
void Juniper.World.LightMeasurement.Start () inline private
Sets up the ARCore light estimation system.
Definition at line 276 of file LightMeasurement.cs.
         {
             var arCoreSession = this.FindAny<ARCoreSession>();
             arCoreSession.SessionConfig.EnableLightEstimation = true;
         }
Uninstall()
void Juniper.World.LightMeasurement.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 163 of file LightMeasurement.cs.
         {
 #if VUFORIA
             this.RemoveComponent<VuforiaImageAnalyzer>();
 #endif
         }
UnityARSessionNativeInterface_ARFrameUpdatedEvent()
void Juniper.World.LightMeasurement.UnityARSessionNativeInterface_ARFrameUpdatedEvent (UnityARCamera camera) inline private
Process the ARKit light estimation values.
Definition at line 262 of file LightMeasurement.cs.
         {
             if (camera.lightData.arLightingType == LightDataType.LightEstimate)
             {
                 lastIntensity = 0.001f * camera.lightData.arLightEstimate.ambientIntensity;
                 lastColor = camera.lightData.arLightEstimate.ambientColorTemperature.FromKelvinToColor();
             }
         }
References Juniper.World.LightMeasurement.lastColor, and Juniper.World.LightMeasurement.lastIntensity.
Referenced by Juniper.World.LightMeasurement.Start().
Update()
void Juniper.World.LightMeasurement.Update () inline
Check to see if the ARCore light estimation has been updated.
Definition at line 286 of file LightMeasurement.cs.
         {
             if (UseFakeIntensity)
             {
                 SetFakeValues();
             }
             else
             {
 #if VUFORIA
                 if (illumination != null)
                 {
                     if (illumination.AmbientIntensity != null)
                     {
                         lastIntensity = illumination.AmbientIntensity.Value / 1000f;
                     }
                     if (illumination.AmbientColorTemperature != null)
                     {
                         lastColor = illumination.AmbientColorTemperature.Value.FromKelvinToColor();
                     }
                 }
 #elif ARCORE
                 if (Frame.LightEstimate.State == LightEstimateState.Valid)
                 {
                     lastIntensity = Frame.LightEstimate.PixelIntensity;
                     lastColor = Frame.LightEstimate.ColorCorrection;
                 }
 #endif
             }
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.World.LightMeasurement.DebugReport, Juniper.World.LightMeasurement.illumination, Juniper.World.LightMeasurement.lastColor, Juniper.World.LightMeasurement.lastIntensity, Juniper.World.LightMeasurement.PrintDebugReport(), Juniper.World.LightMeasurement.SetFakeValues(), and Juniper.World.LightMeasurement.UseFakeIntensity.
Member Data Documentation
analyzer
VuforiaImageAnalyzer Juniper.World.LightMeasurement.analyzer private
If useCustomAnalyzer is set to true, this is the image analyzer that performs the light estimation.
Definition at line 89 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.Awake(), Juniper.World.LightMeasurement.Install(), and Juniper.World.LightMeasurement.PrintDebugReport().
Color
Color Juniper.World.LightMeasurement.Color = Color.white
The fake color to use if UseFakeIntensity is true.
Definition at line 75 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.GetAveragePixelIntensity(), and Juniper.World.LightMeasurement.SetFakeValues().
ColorEstimate
Color Juniper.World.LightMeasurement.ColorEstimate
Initial value:
=>
            lastColor
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light color estimate.
Definition at line 120 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.PrintDebugReport(), and Juniper.World.IndoorLightEstimate.Update().
DebugReport
bool Juniper.World.LightMeasurement.DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Definition at line 113 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.Update().
illumination
IlluminationManager Juniper.World.LightMeasurement.illumination private
If useCustomAnalyzer is set to false, Vuforia's built-in light estimation is used. This will be based on ARKit or ARCore, depending on the underlying runtime platform.
Definition at line 107 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.GetIlluminationManagerCoroutine(), Juniper.World.LightMeasurement.PrintDebugReport(), and Juniper.World.LightMeasurement.Update().
Intensity
float Juniper.World.LightMeasurement.Intensity = 0.8f
The fake intensity value to use if UseFakeIntensity is true.
Definition at line 70 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.SetFakeValues().
IntensityEstimate
float Juniper.World.LightMeasurement.IntensityEstimate
Initial value:
=>
            lastIntensity
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light intensity estimate.
Definition at line 128 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.PrintDebugReport(), and Juniper.World.IndoorLightEstimate.Update().
lastColor
Color Juniper.World.LightMeasurement.lastColor private
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
Definition at line 33 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.GetAveragePixelIntensity(), Juniper.World.LightMeasurement.SetFakeValues(), Juniper.World.LightMeasurement.UnityARSessionNativeInterface_ARFrameUpdatedEvent(), and Juniper.World.LightMeasurement.Update().
lastIntensity
float Juniper.World.LightMeasurement.lastIntensity private
Light estimate updates happen concurrently with frame updates. This value stores the last light intesity measurement that was calculated, for use in the current render frame.
Definition at line 27 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.GetAveragePixelIntensity(), Juniper.World.LightMeasurement.SetFakeValues(), Juniper.World.LightMeasurement.UnityARSessionNativeInterface_ARFrameUpdatedEvent(), and Juniper.World.LightMeasurement.Update().
NumSampleRows
const int Juniper.World.LightMeasurement.NumSampleRows = 10 private
If useCustomAnalyzer is set to true, this is the number of rows in the camera feed that will be sampled to make the light estimation.
Definition at line 95 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.GetAveragePixelIntensity().
NumSamplesPerRow
const int Juniper.World.LightMeasurement.NumSamplesPerRow = 10 private
If useCustomAnalyzer is set to true, this is the number of columns in the camera feed that will be sampled to make the light estimation.
Definition at line 101 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.GetAveragePixelIntensity().
useCustomAnalyzer
bool Juniper.World.LightMeasurement.useCustomAnalyzer
Set to true to use the custom image analyzer when running Vuforia. This is mostly only useful on Android for Vuforia v7.1.
Definition at line 83 of file LightMeasurement.cs.
Referenced by Juniper.World.LightMeasurement.Awake().
useFake
bool Juniper.World.LightMeasurement.useFake
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
Definition at line 39 of file LightMeasurement.cs.
Property Documentation
UseFakeIntensity
bool Juniper.World.LightMeasurement.UseFakeIntensity get private
Returns true if the user has requested a fake intensity, or the application is running in the Unity Editor.
true if use fake intensity; otherwise, false.
Definition at line 47 of file LightMeasurement.cs.
         {
             get
             {
                 if (useFake || Application.isEditor)
                 {
                     return true;
                 }
                 else
                 {
 #if VUFORIA
                     return (illumination == null && analyzer == null)
                         || (illumination != null && illumination.AmbientIntensity == null)
                         || (analyzer != null && (!analyzer.Running || VuforiaImageAnalyzer.ImageFormat == null));
 #else
                     return false;
 #endif
                 }
             }
         }
Referenced by Juniper.World.LightMeasurement.PrintDebugReport(), and Juniper.World.LightMeasurement.Update().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/World/LightMeasurement.cs