Juniper: Juniper.Data.AbstractBackgroundThread Class Reference
Juniper.Data.AbstractBackgroundThread Class Reference abstract
An abstract class for performing an operation on a background thread.
Protected Member Functions
void OnError (Exception exp)
Trigger the Error event handler, if it has any listeners attached to it.
virtual void Awake ()
Create a background thread runner in a stopped state.
void Begin ()
Get the background thread up and running.
virtual void OnBegin ()
Respond to the thread starting.
abstract void Execute ()
Override the Execute method in child classes to run functionality on the background thread.
Properties
virtual bool Running [get]
Returns true when the background thread is still running.
Events
EventHandler< BackgroundThreadErrorEventArgs > Error
An event that triggers if the background operation throws an exception.
Private Member Functions
void Run ()
The thread body.
Private Attributes
bool running
Whether or not the BackgroundThread is still running.
Detailed Description
An abstract class for performing an operation on a background thread.
Definition at line 9 of file AbstractBackgroundThread.cs.
Member Function Documentation
Awake()
virtual void Juniper.Data.AbstractBackgroundThread.Awake () inline protected virtual
Create a background thread runner in a stopped state.
Reimplemented in Juniper.Data.AbstractBackgroundRepeatingThread.
Definition at line 42 of file AbstractBackgroundThread.cs.
         {
             running = false;
         }
References Juniper.Data.AbstractBackgroundThread.running.
Begin()
void Juniper.Data.AbstractBackgroundThread.Begin () inline protected
Get the background thread up and running.
Definition at line 50 of file AbstractBackgroundThread.cs.
         {
             if (!Running)
             {
                 OnBegin();
                 Task.Run(new Action(Run));
             }
         }
References Juniper.Data.AbstractBackgroundThread.OnBegin(), Juniper.Data.AbstractBackgroundThread.Run(), and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.Unity.Imaging.VuforiaImageAnalyzer.Update().
Execute()
abstract void Juniper.Data.AbstractBackgroundThread.Execute () protected pure virtual
Override the Execute method in child classes to run functionality on the background thread.
Implemented in Juniper.Data.AbstractBackgroundRepeatingThread, and Juniper.Data.OneShotThread.
Referenced by Juniper.Data.AbstractBackgroundThread.Run().
OnBegin()
virtual void Juniper.Data.AbstractBackgroundThread.OnBegin () inline protected virtual
Respond to the thread starting.
Reimplemented in Juniper.Data.AbstractBackgroundRepeatingThread.
Definition at line 62 of file AbstractBackgroundThread.cs.
         {
             running = true;
         }
References Juniper.Data.AbstractBackgroundThread.running.
Referenced by Juniper.Data.AbstractBackgroundThread.Begin().
OnError()
void Juniper.Data.AbstractBackgroundThread.OnError (Exception exp) inline protected
Trigger the Error event handler, if it has any listeners attached to it.
Parameters
exp
Definition at line 31 of file AbstractBackgroundThread.cs.
         {
             if (Running)
             {
                 Error?.Invoke(this, new BackgroundThreadErrorEventArgs(exp));
             }
         }
References Juniper.Data.AbstractBackgroundThread.Error, and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.Data.AbstractBackgroundRepeatingThread.Execute(), and Juniper.Data.AbstractBackgroundThread.Run().
Run()
void Juniper.Data.AbstractBackgroundThread.Run () inline private
The thread body.
Definition at line 80 of file AbstractBackgroundThread.cs.
         {
             try
             {
                 Execute();
             }
             catch (Exception exp)
             {
                 OnError(exp);
             }
             running = false;
         }
References Juniper.Data.AbstractBackgroundThread.Execute(), Juniper.Data.AbstractBackgroundThread.OnError(), and Juniper.Data.AbstractBackgroundThread.running.
Referenced by Juniper.Data.AbstractBackgroundThread.Begin().
Member Data Documentation
running
bool Juniper.Data.AbstractBackgroundThread.running private
Whether or not the BackgroundThread is still running.
Definition at line 75 of file AbstractBackgroundThread.cs.
Referenced by Juniper.Data.AbstractBackgroundThread.Awake(), Juniper.Data.AbstractBackgroundThread.OnBegin(), and Juniper.Data.AbstractBackgroundThread.Run().
Property Documentation
Running
virtual bool Juniper.Data.AbstractBackgroundThread.Running get
Returns true when the background thread is still running.
Definition at line 20 of file AbstractBackgroundThread.cs.
         {
             get
             {
                 return running;
             }
         }
Referenced by Juniper.Data.AbstractBackgroundThread.Begin(), and Juniper.Data.AbstractBackgroundThread.OnError().
Event Documentation
Error
EventHandler<BackgroundThreadErrorEventArgs> Juniper.Data.AbstractBackgroundThread.Error
An event that triggers if the background operation throws an exception.
Definition at line 14 of file AbstractBackgroundThread.cs.
Referenced by Juniper.Data.AbstractBackgroundThread.OnError().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Data/AbstractBackgroundThread.cs