Juniper: System.Collections.Generic.NAryTree< T > Class Template Reference
System.Collections.Generic.NAryTree< T > Class Template Reference
A node in an N-ary tree.
Public Member Functions
NAryTree (T value)
Creates a root node with no children.
void Add (NAryTree< T > node)
Add an element as a child of the node.
void Add (T value)
Create a new node out of a value and add it to the tree.
override string ToString ()
Print out a debugging string.
Public Attributes
readonly T Value
The value stored in this node.
bool IsLeaf
Returns true if there are no child nodes.
bool IsRoot
Returns true if this node has no parent node.
Protected Member Functions
void Recurse (Action< NAryTree< T >> act)
Perform an operation over the trie, using a local stack instead of the function call stack frame.
Private Member Functions
void IncreaseDepth ()
Increase the depth of this and any child nodes.
Private Attributes
int depth
How deep into the tree is this branch
NAryTree< T > parent
The next node above the current node.
List< NAryTree< T > > children
All nodes below the current node.
Detailed Description
A node in an N-ary tree.
Template Parameters
T Any type of object
Definition at line 9 of file NAryTree.cs.
Constructor & Destructor Documentation
NAryTree()
System.Collections.Generic.NAryTree< T >.NAryTree (T value) inline
Creates a root node with no children.
Parameters
value The value to store at the root.
Definition at line 20 of file NAryTree.cs.
         {
             Value = value;
             depth = 0;
             children = new List<NAryTree<T>>();
         }
References System.Collections.Generic.NAryTree< T >.children, System.Collections.Generic.NAryTree< T >.depth, and System.Collections.Generic.NAryTree< T >.Value.
Member Function Documentation
Add() [1/2]
void System.Collections.Generic.NAryTree< T >.Add (NAryTree< T > node) inline
Add an element as a child of the node.
Parameters
node The node to add.
Definition at line 43 of file NAryTree.cs.
         {
             children.Add(node);
             node.parent = this;
             node.IncreaseDepth();
         }
References System.Collections.Generic.NAryTree< T >.children, System.Collections.Generic.NAryTree< T >.IncreaseDepth(), and System.Collections.Generic.NAryTree< T >.parent.
Add() [2/2]
void System.Collections.Generic.NAryTree< T >.Add (T value)
Create a new node out of a value and add it to the tree.
Parameters
value The value to store.
IncreaseDepth()
void System.Collections.Generic.NAryTree< T >.IncreaseDepth () private
Increase the depth of this and any child nodes.
Referenced by System.Collections.Generic.NAryTree< T >.Add().
Recurse()
void System.Collections.Generic.NAryTree< T >.Recurse (Action< NAryTree< T >> act) inline protected
Perform an operation over the trie, using a local stack instead of the function call stack frame.
Parameters
act Act.
Definition at line 80 of file NAryTree.cs.
         {
             // how to do recursion without killing the function call stack
             var stack = new Stack<NAryTree<T>>();
             stack.Push(this);
             while (stack.Count > 0)
             {
                 var here = stack.Pop();
                 here.children.ForEach(stack.Push);
                 act(here);
             }
         }
Referenced by System.Collections.Generic.NAryTree< T >.ToString().
ToString()
override string System.Collections.Generic.NAryTree< T >.ToString () inline
Print out a debugging string.
Returns
A text representation of the tree.
Definition at line 61 of file NAryTree.cs.
         {
             var sb = new StringBuilder();
             Recurse(here =>
             {
                 for (var i = 0; i < here.depth; ++i)
                 {
                     sb.Append("--");
                 }
                 sb.AppendLine(here.Value.ToString());
             });
             return sb.ToString();
         }
References System.Collections.Generic.NAryTree< T >.Recurse().
Member Data Documentation
children
List<NAryTree<T> > System.Collections.Generic.NAryTree< T >.children private
All nodes below the current node.
Definition at line 106 of file NAryTree.cs.
Referenced by System.Collections.Generic.NAryTree< T >.Add(), and System.Collections.Generic.NAryTree< T >.NAryTree().
depth
int System.Collections.Generic.NAryTree< T >.depth private
How deep into the tree is this branch
Definition at line 96 of file NAryTree.cs.
Referenced by System.Collections.Generic.NAryTree< T >.NAryTree().
IsLeaf
bool System.Collections.Generic.NAryTree< T >.IsLeaf
Initial value:
=>
            children.Count == 0
Returns true if there are no child nodes.
Definition at line 30 of file NAryTree.cs.
IsRoot
bool System.Collections.Generic.NAryTree< T >.IsRoot
Initial value:
=>
            parent == null
Returns true if this node has no parent node.
Definition at line 36 of file NAryTree.cs.
parent
NAryTree<T> System.Collections.Generic.NAryTree< T >.parent private
The next node above the current node.
Definition at line 101 of file NAryTree.cs.
Referenced by System.Collections.Generic.NAryTree< T >.Add().
Value
readonly T System.Collections.Generic.NAryTree< T >.Value
The value stored in this node.
Definition at line 14 of file NAryTree.cs.
Referenced by System.Collections.Generic.NAryTree< T >.NAryTree().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Extensions/NETFX/Collections/Generic/NAryTree.cs