Juniper: Juniper.Collections.Statistics.AbstractCollectionStatistics< T > Class Template Reference
Juniper.Collections.Statistics.AbstractCollectionStatistics< T > Class Template Reference abstract
An abstract class for a collection wrapper that can automatically compute statistics on the values contained within.
Public Member Functions
IEnumerator< T > GetEnumerator ()
Returns an enumerator that iterates through the collection.
void Add (T item)
Adds an item to the collection, and recalculates the statistical values.
void AddRange (IEnumerable< T > collect)
Add a collection of items to the current collection.
void Clear ()
Clears the collection and resets the statistics to null.
bool Contains (T item)
Returns true if the give item is in the collection.
void CopyTo (T[] array, int arrayIndex)
Copies the elements of the collection to an Array, starting at a particular Array index.
bool Remove (T item)
Remove an item from the collection.
int IndexOf (T item)
Determines the index of the specified item in the underlying collection.
void Insert (int index, T item)
Insert an item at an arbitrary point in the collection.
void RemoveAt (int index)
Remove an item at the specified index from the collection.
bool Append (T value, int numStandardDeviations, int minSamples=2)
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Protected Member Functions
AbstractCollectionStatistics (IList< T > collection, T zero, T one)
Creates a new collection analyzer out of a generic collection.
AbstractCollectionStatistics (int capacity, T zero, T one)
Creates a new collection analyzer with a RingBuffer as the underlying collection.
void RecomputeStatistics ()
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
void UpdateStatistics (T value)
Recalculate statistics that don't need to perform a full collection scan.
abstract T Add (T a, T b)
Implementing classes can define how two values get added (because C# generics cannot specify operator constraints)
abstract T Subtract (T a, T b)
Implementing classes can define how two values get subtracted (because C# generics cannot specify operator constraints)
abstract T Multiply (T a, T b)
Implementing classes can define how two values get multiplied (because C# generics cannot specify operator constraints)
abstract T Scale (T a, float b)
Implementing classes can define how a value gets scaled by a scalar (because C# generics cannot specify operator constraints)
abstract T Divide (T a, float b)
Implementing classes can define how a value gets divided by a scalar (because C# generics cannot specify operator constraints)
abstract T Sqrt (T value)
Implementing classes can define how calculate the square root of a value (because C# generics cannot specify operator constraints)
abstract T Abs (T value)
Implementing classes can define how calculate the absolute value of a value (because C# generics cannot specify operator constraints)
abstract bool LessThan (T a, T b)
Implementing classes can define how two values get compared (because C# generics cannot specify operator constraints)
Properties
T? Maximum [get, private set]
The maximum value in the list, if there are any values in the list.
T? Minimum [get, private set]
The minimum value in the list, if there are any values in the list.
T? Mean [get, private set]
The arithmetic mean of the values in the list, if there are any values in the list.
T? Variance [get, private set]
The variance of all the values in the list, if there are any values in the list.
T? StandardDeviation [get, private set]
The standard deviation of all the values in the list, if there are any values in the list.
int Count [get]
Returns the number of items in the collection.
bool IsSaturated [get]
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
bool IsReadOnly [get]
Gets a value indicating whether this T:Juniper.Statistics.AbstractCollectionStatistics`1 is read only.
T? Delta [get]
The difference between the Maximum and Minimum
T? Median [get]
The midpoint between the Maximum and the Minimum
T this[int index] [get, set]
Gets or sets the element at the specified index.
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Returns an enumerator that iterates through the collection.
T? Add (T? a, T? b)
Coalesces null values for performing Add(T, T).
T? Subtract (T? a, T? b)
Coalesces null values for performing Subtract(T, T).
T? Multiply (T? a, T? b)
Coalesces null values for performing Multiply(T, T).
T? Scale (T? a, float b)
Coalesces null values for performing Scale(T, float).
T? Divide (T? a, float b)
Coalesces null values for performing Divide(T, float).
T Min (T? a, T b)
Coalesces null values for performing Min(T, T).
T Max (T? a, T b)
Coalesces null values for performing Max(T, T).
T? Sqrt (T? value)
Coalesces null values for performing Sqrt(T).
T? Abs (T? value)
Coalesces null values for performing Abs(T, T).
bool LessThan (T? a, T? b)
Coalesces null values for performing LessThan(T, T).
Private Attributes
readonly T Zero
The value that represents 0 for T.
readonly T One
The value that represents 1 for T.
readonly T MinValue
The value that represents the minimum vaule for T (e.g. float.MinValue).
readonly T MaxValue
The value that represents the maximum value for T (e.g.
readonly IList< T > collect
The collection being wrapped.
Detailed Description
An abstract class for a collection wrapper that can automatically compute statistics on the values contained within.
Type Constraints
T : struct
Definition at line 10 of file AbstractCollectionStatistics.cs.
Constructor & Destructor Documentation
AbstractCollectionStatistics() [1/2]
Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.AbstractCollectionStatistics (IList< T > collection, T zero, T one) inline protected
Creates a new collection analyzer out of a generic collection.
Parameters
collection Collection.
zero The value that represents Zero for T
one The value that represents One for T
Definition at line 332 of file AbstractCollectionStatistics.cs.
         {
             collect = collection;
             Zero = zero;
             One = one;
             MaxValue = Scale(One, float.MaxValue);
             MinValue = Scale(One, float.MinValue);
         }
AbstractCollectionStatistics() [2/2]
Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.AbstractCollectionStatistics (int capacity, T zero, T one) inline protected
Creates a new collection analyzer with a RingBuffer as the underlying collection.
Parameters
capacity Capacity.
zero The value that represents Zero for T
one The value that represents One for T
Definition at line 347 of file AbstractCollectionStatistics.cs.
             : this(new RingBuffer<T>(capacity), zero, one)
         {
         }
Member Function Documentation
Abs() [1/2]
abstract T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Abs (T value) protected pure virtual
Implementing classes can define how calculate the absolute value of a value (because C# generics cannot specify operator constraints)
Parameters
value
Returns
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Abs(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append().
Abs() [2/2]
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Abs (T? value) inline private
Coalesces null values for performing Abs(T, T).
Parameters
value
Returns
Definition at line 616 of file AbstractCollectionStatistics.cs.
         {
             if (value == null)
             {
                 return null;
             }
             else
             {
                 return Abs(value.Value);
             }
         }
Add() [1/3]
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Add (T item) inline
Adds an item to the collection, and recalculates the statistical values.
Parameters
item
Definition at line 175 of file AbstractCollectionStatistics.cs.
         {
             collect.Add(item);
             UpdateStatistics(item);
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Add(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AddRange(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Add() [2/3]
abstract T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Add (T a, T b) protected pure virtual
Implementing classes can define how two values get added (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Add() [3/3]
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Add (T? a, T? b) inline private
Coalesces null values for performing Add(T, T).
Parameters
a
b
Returns
Definition at line 488 of file AbstractCollectionStatistics.cs.
         {
             return Add(a ?? Zero, b ?? Zero);
         }
AddRange()
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.AddRange (IEnumerable< T > collect) inline
Add a collection of items to the current collection.
Parameters
collect
Definition at line 185 of file AbstractCollectionStatistics.cs.
         {
             foreach (var v in collect)
             {
                 Add(v);
             }
         }
Append()
bool Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Append (T value, int numStandardDeviations, int minSamples = 2) inline
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Parameters
value
numStandardDeviations
minSamples The minimum number of collected samples in the collection to have before rejecting outliers. MinSamples must be at least 2.
Returns
True if the item was added, false if it was rejected.
Definition at line 301 of file AbstractCollectionStatistics.cs.
         {
             var delta = Abs(Subtract(value, Mean));
             var isInlier = Count < 2
                 || Count < minSamples
                 || LessThan(delta, Scale(StandardDeviation, numStandardDeviations));
             if (isInlier)
             {
                 Add(value);
             }
             return isInlier;
         }
Clear()
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Clear () inline
Clears the collection and resets the statistics to null.
Definition at line 196 of file AbstractCollectionStatistics.cs.
         {
             collect.Clear();
             Minimum = null;
             Maximum = null;
             Mean = null;
             Variance = null;
             StandardDeviation = null;
         }
Referenced by Juniper.Unity.Widgets.QualityDegrader.Update().
Contains()
bool Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Contains (T item) inline
Returns true if the give item is in the collection.
Parameters
item The item to search for.
Returns
True if the item is found. False if it is not.
Definition at line 211 of file AbstractCollectionStatistics.cs.
         {
             return collect.Contains(item);
         }
CopyTo()
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.CopyTo (T [] array, int arrayIndex) inline
Copies the elements of the collection to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
arrayIndex The zero-based index in array at which copying begins.
Exceptions
System.ArgumentNullException array is null
System.ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from arrayIndex to the end of the destination array .
Definition at line 232 of file AbstractCollectionStatistics.cs.
         {
             collect.CopyTo(array, arrayIndex);
         }
Divide() [1/2]
abstract T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Divide (T a, float b) protected pure virtual
Implementing classes can define how a value gets divided by a scalar (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Divide(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Divide() [2/2]
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Divide (T? a, float b) inline private
Coalesces null values for performing Divide(T, float).
Parameters
a
b
Returns
Definition at line 546 of file AbstractCollectionStatistics.cs.
         {
             if (a == null)
             {
                 return null;
             }
             else
             {
                 return Divide(a.Value, b);
             }
         }
GetEnumerator() [1/2]
IEnumerator<T> Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.GetEnumerator () inline
Returns an enumerator that iterates through the collection.
Returns
Definition at line 166 of file AbstractCollectionStatistics.cs.
         {
             return collect.GetEnumerator();
         }
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.GetEnumerator () inline private
Returns an enumerator that iterates through the collection.
Returns
Definition at line 321 of file AbstractCollectionStatistics.cs.
         {
             return collect.GetEnumerator();
         }
IndexOf()
int Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.IndexOf (T item) inline
Determines the index of the specified item in the underlying collection.
Parameters
item The object to location in the collection.
Returns
The index of item if found in the list; otherwise, -1.
If an object occurs multiple times in the list, the IndexOf method always returns the first instance found.
Definition at line 258 of file AbstractCollectionStatistics.cs.
         {
             return collect.IndexOf(item);
         }
Insert()
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Insert (int index, T item) inline
Insert an item at an arbitrary point in the collection.
Parameters
index The index at which to insert item .
item The value to insert.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
Definition at line 271 of file AbstractCollectionStatistics.cs.
         {
             collect.Insert(index, item);
             UpdateStatistics(item);
         }
LessThan() [1/2]
abstract bool Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.LessThan (T a, T b) protected pure virtual
Implementing classes can define how two values get compared (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.LessThan(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Max(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Min().
LessThan() [2/2]
bool Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.LessThan (T? a, T? b) inline private
Coalesces null values for performing LessThan(T, T).
Parameters
a
b
Returns
Definition at line 635 of file AbstractCollectionStatistics.cs.
         {
             if (a == null || b == null)
             {
                 return false;
             }
             else
             {
                 return LessThan(a.Value, b.Value);
             }
         }
Max()
T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Max (T? a, T b) inline private
Coalesces null values for performing Max(T, T).
Parameters
a
b
Returns
Definition at line 582 of file AbstractCollectionStatistics.cs.
         {
             if (a != null && LessThan(b, a.Value))
             {
                 return a.Value;
             }
             else
             {
                 return b;
             }
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Min()
T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Min (T? a, T b) inline private
Coalesces null values for performing Min(T, T).
Parameters
a
b
Returns
Definition at line 564 of file AbstractCollectionStatistics.cs.
         {
             if (a != null && LessThan(a.Value, b))
             {
                 return a.Value;
             }
             else
             {
                 return b;
             }
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Multiply() [1/2]
abstract T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Multiply (T a, T b) protected pure virtual
Implementing classes can define how two values get multiplied (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Multiply(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Multiply() [2/2]
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Multiply (T? a, T? b) inline private
Coalesces null values for performing Multiply(T, T).
Parameters
a
b
Returns
Definition at line 510 of file AbstractCollectionStatistics.cs.
         {
             if (a == null || b == null)
             {
                 return null;
             }
             else
             {
                 return Multiply(a.Value, b.Value);
             }
         }
RecomputeStatistics()
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.RecomputeStatistics () inline protected
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
Definition at line 356 of file AbstractCollectionStatistics.cs.
         {
             Maximum = Minimum = Mean = Variance = StandardDeviation = null;
             if (Count > 0)
             {
                 Minimum = MaxValue;
                 Maximum = MinValue;
                 foreach (var v in this)
                 {
                     Minimum = Min(Minimum, v);
                     Maximum = Max(Maximum, v);
                     Mean = Add(Mean, Divide(v, Count));
                 }
                 if (Count > 1)
                 {
                     Variance = Zero;
                     foreach (var v in this)
                     {
                         var residual = Subtract(v, Mean);
                         Variance = Add(Variance, Divide(Multiply(residual, residual), Count - 1));
                     }
                     StandardDeviation = Sqrt(Variance);
                 }
             }
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Remove(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RemoveAt().
Remove()
bool Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Remove (T item) inline
Remove an item from the collection.
Parameters
item The value to remove.
Returns
True if the item existed in the buffer and was removed. False otherwise.
Definition at line 242 of file AbstractCollectionStatistics.cs.
         {
             var removed = collect.Remove(item);
             RecomputeStatistics();
             return removed;
         }
RemoveAt()
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.RemoveAt (int index) inline
Remove an item at the specified index from the collection.
Parameters
index The index at which to remove an item.
Exceptions
System.ArgumentOutOfRangeException index is less than 0 or greater than Count - 1.
Definition at line 284 of file AbstractCollectionStatistics.cs.
         {
             collect.RemoveAt(index);
             RecomputeStatistics();
         }
Scale() [1/2]
abstract T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Scale (T a, float b) protected pure virtual
Implementing classes can define how a value gets scaled by a scalar (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Scale(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Scale() [2/2]
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Scale (T? a, float b) inline private
Coalesces null values for performing Scale(T, float).
Parameters
a
b
Returns
Definition at line 528 of file AbstractCollectionStatistics.cs.
         {
             if (a == null)
             {
                 return null;
             }
             else
             {
                 return Scale(a.Value, b);
             }
         }
Sqrt() [1/2]
abstract T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Sqrt (T value) protected pure virtual
Implementing classes can define how calculate the square root of a value (because C# generics cannot specify operator constraints)
Parameters
value
Returns
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Sqrt(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Sqrt() [2/2]
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Sqrt (T? value) inline private
Coalesces null values for performing Sqrt(T).
Parameters
value
Returns
Definition at line 599 of file AbstractCollectionStatistics.cs.
         {
             if (value == null)
             {
                 return null;
             }
             else
             {
                 return Sqrt(value.Value);
             }
         }
Subtract() [1/2]
abstract T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Subtract (T a, T b) protected pure virtual
Implementing classes can define how two values get subtracted (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Subtract(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Subtract() [2/2]
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Subtract (T? a, T? b) inline private
Coalesces null values for performing Subtract(T, T).
Parameters
a
b
Returns
Definition at line 499 of file AbstractCollectionStatistics.cs.
         {
             return Subtract(a ?? Zero, b ?? Zero);
         }
UpdateStatistics()
void Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.UpdateStatistics (T value) inline protected
Recalculate statistics that don't need to perform a full collection scan.
Parameters
value
Definition at line 389 of file AbstractCollectionStatistics.cs.
         {
             Minimum = Min(Minimum, value);
             Maximum = Max(Maximum, value);
             var prevMean = Mean;
             var residual = Subtract(value, prevMean);
             Mean = Add(prevMean, Divide(residual, Count));
             if (Count > 1)
             {
                 var secondResidual = Subtract(value, Mean);
                 var n2 = Count - 2;
                 var n1 = Count - 1;
                 Variance = Divide(
                     Add(
                         Scale(Variance, n2),
                         Multiply(residual, secondResidual)),
                     n1);
                 StandardDeviation = Sqrt(Variance);
             }
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Add(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Insert().
Member Data Documentation
collect
readonly IList<T> Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.collect private
The collection being wrapped.
Definition at line 35 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Add(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AddRange(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Contains(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.CopyTo(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.GetEnumerator(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.IndexOf(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Insert(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Remove(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RemoveAt().
MaxValue
readonly T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.MaxValue private
The value that represents the maximum value for T (e.g.
float.MinValue).
Definition at line 30 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics().
MinValue
readonly T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.MinValue private
The value that represents the minimum vaule for T (e.g. float.MinValue).
Definition at line 25 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics().
One
readonly T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.One private
The value that represents 1 for T.
Definition at line 20 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics().
Zero
readonly T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Zero private
The value that represents 0 for T.
Definition at line 15 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Add(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Subtract().
Property Documentation
Count
int Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Count get
Returns the number of items in the collection.
Definition at line 81 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 return collect.Count;
             }
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Unity.World.CompassRose.PrintDebugReport(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Delta
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Delta get
The difference between the Maximum and Minimum
Definition at line 124 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 return Subtract(Maximum, Minimum);
             }
         }
IsReadOnly
bool Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.IsReadOnly get
Gets a value indicating whether this T:Juniper.Statistics.AbstractCollectionStatistics`1 is read only.
true if is read only; otherwise, false.
Definition at line 113 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 return collect.IsReadOnly;
             }
         }
IsSaturated
bool Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.IsSaturated get
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
true if is saturated; otherwise, false.
Definition at line 93 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (collect is RingBuffer<T> buf)
                 {
                     return buf.IsSaturated;
                 }
                 else
                 {
                     return false;
                 }
             }
         }
Referenced by Juniper.Unity.Widgets.QualityDegrader.Update().
Maximum
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Maximum get private set
The maximum value in the list, if there are any values in the list.
Definition at line 41 of file AbstractCollectionStatistics.cs.
         {
             get; private set;
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Mean
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Mean get private set
The arithmetic mean of the values in the list, if there are any values in the list.
Definition at line 57 of file AbstractCollectionStatistics.cs.
         {
             get; private set;
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Unity.Widgets.Shaker.PrintDebugReport(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), Juniper.Unity.World.CompassRose.SetNorth(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Median
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Median get
The midpoint between the Maximum and the Minimum
Definition at line 135 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 return Add(Minimum, Divide(Delta, 2));
             }
         }
Minimum
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Minimum get private set
The minimum value in the list, if there are any values in the list.
Definition at line 49 of file AbstractCollectionStatistics.cs.
         {
             get; private set;
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
StandardDeviation
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.StandardDeviation get private set
The standard deviation of all the values in the list, if there are any values in the list.
Definition at line 73 of file AbstractCollectionStatistics.cs.
         {
             get; private set;
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Unity.Widgets.Shaker.PrintDebugReport(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
this[int index]
T Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.this[int index] get set
Gets or sets the element at the specified index.
Parameters
index An index into the buffer, modulated by the buffer length.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
The element at the specified index.
Definition at line 151 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 return collect[index];
             }
             set
             {
                 collect[index] = value;
             }
         }
Variance
T? Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Variance get private set
The variance of all the values in the list, if there are any values in the list.
Definition at line 65 of file AbstractCollectionStatistics.cs.
         {
             get; private set;
         }
Referenced by Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Collections.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Collections/Statistics/AbstractCollectionStatistics.cs