Juniper: Juniper.Widgets.VideoVader Class Reference
Juniper.Widgets.VideoVader Class Reference
Manages the life-cycle of a video that can be faded out or faded in.
Public Member Functions
void Awake ()
Retrieves the video player and its fader.
void FireComplete ()
override void Enter ()
Fire the OnEnable event and perform the Enter transition.
override void SkipEnter ()
override void Exit ()
Fire the OnExiting event and perform the Exit transition.
override void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
bool HasStopped ()
virtual void SkipExit ()
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Public Attributes
float restartTimeout = 10
The number of seconds a video may remain hidden until it resets to the beginning.
float lingerTimeout = 0
The number of second to wait after the video has ended to trigger the next state.
UnityEvent onComplete = new UnityEvent()
A Unity Event that fires when the video has finished playing.
float minAlpha = 0
The minimum opacity of the object, where 0 = completely transparent.
float maxAlpha = 1
The maximum opacity of the object, where 1 = completely opaque.
float length = 0.25f
The amount of time it takes to complete the transition.
override float TransitionLength => length
The amount of time it takes to complete the transition.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
virtual bool IsComplete => state == STOPPED
bool IsRunning => !IsComplete
Protected Member Functions
override void OnEnabled ()
override void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
override void RenderValue (float value)
Updates the size of the transitioning object every frame the transition is active.
virtual void OnDisabled ()
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Protected Attributes
float DeltaAlpha
The scale range the transition has to traverse.
const int ENTERING = 1
const int STOPPED = 0
const int EXITING = -1
int state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Properties
WaitUntil Waiter [get]
Events
EventHandler< ValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Member Functions
void RestartVideo ()
Reset the video to the beginning if the user lost tracking for a long time.
void Finish ()
Trigger the timeout for the finisher.
void OnFinish ()
Finish out the video state.
Detailed Description
Manages the life-cycle of a video that can be faded out or faded in.
Definition at line 13 of file VideoVader.cs.
Member Function Documentation
Awake()
void Juniper.Widgets.VideoVader.Awake () inline
Retrieves the video player and its fader.
Definition at line 42 of file VideoVader.cs.
         {
 #if UNITY_MODULES_VIDEO
             player = GetComponent<VideoPlayer>();
             this.EnsureComponent<DetectVideoEnd>()
                 .Value
                 .onVideoEnd
                 .AddListener(Finish);
 #endif
         }
References Juniper.Widgets.VideoVader.Finish().
Enter()
override void Juniper.Animation.AbstractTransitionController.Enter () inline virtual inherited
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.FadeTransition.
Definition at line 57 of file AbstractTransitionController.cs.
         {
             StartTransition(ENTERING);
             base.Enter();
         }
References Juniper.AbstractStateController.ENTERING, and Juniper.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.EnterActivatesObject(), Juniper.Animation.TransitionControllerTests.EnterEnablesObject(), Juniper.Animation.TransitionControllerTests.EnterFiresEntering(), Juniper.Animation.TransitionControllerTests.EnterStartsAtZero(), Juniper.Animation.TransitionControllerTests.EnterStartsValueChanged(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Animation.WorkflowStep.Show().
Exit()
override void Juniper.Animation.AbstractTransitionController.Exit () inline virtual inherited
Fire the OnExiting event and perform the Exit transition.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.TransitionControllerTests.MockTransition, and Juniper.Animation.FadeTransition.
Definition at line 71 of file AbstractTransitionController.cs.
         {
             StartTransition(EXITING);
             base.Exit();
         }
References Juniper.AbstractStateController.EXITING, and Juniper.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Widgets.Openable.SetOpen().
Finish()
void Juniper.Widgets.VideoVader.Finish () private
Trigger the timeout for the finisher.
Referenced by Juniper.Widgets.VideoVader.Awake().
FireComplete()
void Juniper.Widgets.VideoVader.FireComplete ()
HasStopped()
bool Juniper.AbstractStateController.HasStopped () inherited
OnDisable()
void Juniper.AbstractStateController.OnDisable () inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
OnDisabled()
virtual void Juniper.AbstractStateController.OnDisabled () inline protected virtual inherited
Reimplemented in Juniper.SubSceneController.
Definition at line 214 of file AbstractStateController.cs.
         {
             if (!skipEvent)
             {
                 OnExited();
             }
         }
References Juniper.AbstractStateController.OnExited(), and Juniper.AbstractStateController.skipEvent.
OnEnable()
void Juniper.AbstractStateController.OnEnable () inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Referenced by Juniper.AbstractStateController.Enter().
OnEnabled()
override void Juniper.Widgets.VideoVader.OnEnabled () inline protected virtual
Reimplemented from Juniper.AbstractStateController.
Definition at line 63 of file VideoVader.cs.
         {
             base.OnEnabled();
             CancelInvoke(nameof(RestartVideo));
 #if UNITY_MODULES_VIDEO
             player.Stop();
             player.Play();
 #endif
         }
References Juniper.Widgets.VideoVader.RestartVideo().
OnEntered()
virtual void Juniper.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Animation.FadeTransition.
Definition at line 241 of file AbstractStateController.cs.
         {
             onEntered?.Invoke();
             Entered?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.Entered, and Juniper.AbstractStateController.onEntered.
Referenced by Juniper.AbstractStateController.Update().
OnEntering()
virtual void Juniper.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 228 of file AbstractStateController.cs.
         {
             onEntering?.Invoke();
             Entering?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.Entering, and Juniper.AbstractStateController.onEntering.
Referenced by Juniper.AbstractStateController.OnEnabled().
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 267 of file AbstractStateController.cs.
         {
             onExited?.Invoke();
             Exited?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.Exited, and Juniper.AbstractStateController.onExited.
Referenced by Juniper.AbstractStateController.OnDisabled().
OnExiting()
override void Juniper.Widgets.VideoVader.OnExiting () protected virtual
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented from Juniper.AbstractStateController.
OnFinish()
void Juniper.Widgets.VideoVader.OnFinish () private
Finish out the video state.
RenderValue()
override void Juniper.Widgets.VideoVader.RenderValue (float value) inline protected virtual
Updates the size of the transitioning object every frame the transition is active.
Parameters
value
Reimplemented from Juniper.Animation.AlphaTransition.
Definition at line 91 of file VideoVader.cs.
         {
 #if UNITY_MODULES_VIDEO
             if (player.renderMode == VideoRenderMode.CameraNearPlane
                || player.renderMode == VideoRenderMode.CameraFarPlane)
             {
                 var o = Mathf.Clamp01(minAlpha + value * DeltaAlpha);
                 player.targetCameraAlpha = o;
             }
             else
             {
 #endif
                 base.RenderValue(value);
 #if UNITY_MODULES_VIDEO
             }
 #endif
         }
References Juniper.Animation.AlphaTransition.DeltaAlpha, and Juniper.Animation.AlphaTransition.minAlpha.
RestartVideo()
void Juniper.Widgets.VideoVader.RestartVideo () inline private
Reset the video to the beginning if the user lost tracking for a long time.
Definition at line 56 of file VideoVader.cs.
         {
 #if UNITY_MODULES_VIDEO
             player.Stop();
 #endif
         }
Referenced by Juniper.Widgets.VideoVader.OnEnabled().
SkipEnter()
override void Juniper.Animation.AbstractTransitionController.SkipEnter () inline virtual inherited
Reimplemented from Juniper.AbstractStateController.
Definition at line 63 of file AbstractTransitionController.cs.
         {
             StartTransition(ENTERING);
             base.SkipEnter();
             SetProgress(0);
         }
References Juniper.AbstractStateController.ENTERING, Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.MasterSceneController.FadeOut().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Definition at line 131 of file AbstractStateController.cs.
         {
             skipEvent = true;
             Exit();
             Update();
             state = STOPPED;
             Update();
             skipEvent = false;
         }
References Juniper.AbstractStateController.Exit(), Juniper.AbstractStateController.skipEvent, Juniper.AbstractStateController.state, Juniper.AbstractStateController.STOPPED, and Juniper.AbstractStateController.Update().
Update()
override void Juniper.Animation.AbstractTransitionController.Update () inline virtual inherited
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.SpiralTransition.
Definition at line 81 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress > 0)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress - change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     SetProgress(0);
                     state = STOPPED;
                 }
             }
             base.Update();
         }
References Juniper.Animation.AbstractTransitionController.attack, Juniper.AbstractStateController.IsRunning, Juniper.Animation.AbstractTransitionController.progress, Juniper.Animation.AbstractTransitionController.release, Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.state, Juniper.AbstractStateController.STOPPED, and Juniper.Animation.AbstractTransitionController.TransitionLength.
Member Data Documentation
attackTime
float Juniper.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 18 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.StartTransition().
DeltaAlpha
float Juniper.Animation.AlphaTransition.DeltaAlpha protected inherited
Initial value:
=>
            maxAlpha - minAlpha
The scale range the transition has to traverse.
Definition at line 34 of file AlphaTransition.cs.
Referenced by Juniper.Animation.AlphaTransition.RenderValue(), and Juniper.Widgets.VideoVader.RenderValue().
ENTERING
const int Juniper.AbstractStateController.ENTERING = 1 protected inherited
Definition at line 176 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Enter(), Juniper.AbstractStateController.Enter(), Juniper.Animation.AbstractTransitionController.SkipEnter(), Juniper.Animation.AbstractTransitionController.StartTransition(), Juniper.SubSceneController.Update(), and Juniper.AbstractStateController.Update().
EXITING
const int Juniper.AbstractStateController.EXITING = -1 protected inherited
Definition at line 180 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Exit(), Juniper.AbstractStateController.Exit(), Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.SubSceneController.Update(), and Juniper.AbstractStateController.Update().
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete => state == STOPPED inherited
Definition at line 89 of file AbstractStateController.cs.
Referenced by Juniper.Animation.TransitionControllerTests.EnterCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.ExitCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.ExitDoesntCompleteRightAway(), Juniper.Animation.TransitionControllerTests.SetEnabledCompletesAsynchronously(), and Juniper.AbstractStateController.Update().
IsRunning
bool Juniper.AbstractStateController.IsRunning => !IsComplete inherited
Definition at line 91 of file AbstractStateController.cs.
Referenced by Juniper.SubSceneController.Update(), and Juniper.Animation.AbstractTransitionController.Update().
length
float Juniper.Animation.AlphaTransition.length = 0.25f inherited
The amount of time it takes to complete the transition.
Definition at line 24 of file AlphaTransition.cs.
lingerTimeout
float Juniper.Widgets.VideoVader.lingerTimeout = 0
The number of second to wait after the video has ended to trigger the next state.
Definition at line 32 of file VideoVader.cs.
maxAlpha
float Juniper.Animation.AlphaTransition.maxAlpha = 1 inherited
The maximum opacity of the object, where 1 = completely opaque.
Definition at line 19 of file AlphaTransition.cs.
minAlpha
float Juniper.Animation.AlphaTransition.minAlpha = 0 inherited
The minimum opacity of the object, where 0 = completely transparent.
Definition at line 14 of file AlphaTransition.cs.
Referenced by Juniper.Animation.AlphaTransition.RenderValue(), and Juniper.Widgets.VideoVader.RenderValue().
onComplete
UnityEvent Juniper.Widgets.VideoVader.onComplete = new UnityEvent()
A Unity Event that fires when the video has finished playing.
Definition at line 37 of file VideoVader.cs.
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 33 of file AbstractStateController.cs.
Referenced by Juniper.Animation.TransitionControllerTests.MockTransition.Awake(), Juniper.StateControllerTests.MockStateController.Awake(), and Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 24 of file AbstractStateController.cs.
Referenced by Juniper.Animation.TransitionControllerTests.MockTransition.Awake(), Juniper.StateControllerTests.MockStateController.Awake(), and Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 51 of file AbstractStateController.cs.
Referenced by Juniper.Animation.TransitionControllerTests.MockTransition.Awake(), Juniper.StateControllerTests.MockStateController.Awake(), and Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 42 of file AbstractStateController.cs.
Referenced by Juniper.Animation.TransitionControllerTests.MockTransition.Awake(), Juniper.StateControllerTests.MockStateController.Awake(), and Juniper.AbstractStateController.OnExiting().
onValueChanged
UnityEvent Juniper.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 31 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.TransitionControllerTests.MockTransition.Awake(), and Juniper.Animation.AbstractTransitionController.OnValueChanged().
releaseTime
float Juniper.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 25 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.StartTransition().
restartTimeout
float Juniper.Widgets.VideoVader.restartTimeout = 10
The number of seconds a video may remain hidden until it resets to the beginning.
Definition at line 27 of file VideoVader.cs.
state
int Juniper.AbstractStateController.state protected inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 204 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.Exit(), Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), Juniper.Animation.AbstractTransitionController.StartTransition(), Juniper.SubSceneController.Update(), Juniper.Animation.AbstractTransitionController.Update(), and Juniper.AbstractStateController.Update().
STOPPED
const int Juniper.AbstractStateController.STOPPED = 0 protected inherited
Definition at line 178 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), Juniper.SubSceneController.Update(), and Juniper.Animation.AbstractTransitionController.Update().
TransitionLength
override float Juniper.Animation.AlphaTransition.TransitionLength => length inherited
The amount of time it takes to complete the transition.
Definition at line 29 of file AlphaTransition.cs.
tween
TweenType Juniper.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 36 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.StartTransition().
tweenK
float Juniper.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 43 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.SetProgress().
Property Documentation
Waiter
WaitUntil Juniper.AbstractStateController.Waiter get inherited
Definition at line 185 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(() => IsComplete);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.StateControllerTests.EnterCompletesAsynchronously(), Juniper.StateControllerTests.EnterDoesntDeactivate(), Juniper.StateControllerTests.EnterDoesntDisable(), Juniper.StateControllerTests.EnterDoesntFireExited(), Juniper.StateControllerTests.EnterFiresEntered(), Juniper.StateControllerTests.ExitCompletesAsynchronously(), Juniper.StateControllerTests.ExitDisables(), Juniper.StateControllerTests.ExitDoesntDeactivate(), Juniper.StateControllerTests.ExitDoesntFireEntered(), Juniper.StateControllerTests.ExitDoesntFireEntering(), Juniper.StateControllerTests.ExitFiresExited(), Juniper.StateControllerTests.ExitFiresExiting(), Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.MasterSceneController.QuitCoroutine(), Juniper.StateControllerTests.SetEnabledCompletesAsynchronously(), Juniper.StateControllerTests.SetEnabledDoesntDeactivate(), Juniper.StateControllerTests.SetEnabledDoesntDisable(), Juniper.StateControllerTests.SetEnabledDoesntFireExited(), Juniper.StateControllerTests.SetEnabledFiresEntered(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 69 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 60 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 87 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 78 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
ValueChanged
EventHandler<ValueChangedEventArgs> Juniper.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 49 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/VideoVader.cs