Juniper: Juniper.World.GIS.LatLngPoint Class Reference
Juniper.World.GIS.LatLngPoint Class Reference
A point in geographic space on a radial coordinate system.
Public Member Functions
LatLngPoint (float lat, float lng, float alt)
Create a new instance of LatLngPoint.
LatLngPoint (float lat, float lng)
LatLngPoint ()
void GetObjectData (SerializationInfo info, StreamingContext context)
Get serialization data from the object.
string ToDMS (int sigfigs)
Pretty-print the Degrees/Minutes/Second version of the Latitude/Longitude angles.
string ToDMS (int sigfigs, IFormatProvider provider)
override string ToString ()
Pretty-print the LatLngPoint for easier debugging.
string ToString (IFormatProvider provider)
string ToString (int sigfigs)
Pretty-print the LatLngPoint for easier debugging.
string ToString (string precision, IFormatProvider provider)
Pretty-print the LatLngPoint for easier debugging.
string ToString (string precision)
override bool Equals (object obj)
Check two LatLngPoints to see if they overlap.
bool Equals (LatLngPoint other)
override int GetHashCode ()
The hash code is used for putting objects into dictionaries.
int CompareTo (LatLngPoint other)
Static Public Member Functions
static bool TryParse (string value, out LatLngPoint point)
static LatLngPoint Parse (string value)
static operator string (LatLngPoint value)
static bool operator== (LatLngPoint left, LatLngPoint right)
static bool operator != (LatLngPoint left, LatLngPoint right)
static bool operator< (LatLngPoint left, LatLngPoint right)
static bool operator<= (LatLngPoint left, LatLngPoint right)
static bool operator > (LatLngPoint left, LatLngPoint right)
static bool operator >= (LatLngPoint left, LatLngPoint right)
Properties
float Altitude [get]
An altitude value thrown in just for kicks. It makes some calculations and conversions easier if we keep the Altitude value.
float Latitude [get]
Lines of latitude run east/west around the globe, parallel to the equator, never intersecting. They measure angular distance north/south.
float Longitude [get]
Lines of longitude run north/south around the globe, intersecting at the poles. They measure angular distance east/west.
Private Member Functions
LatLngPoint (SerializationInfo info, StreamingContext context)
Deserialize the object.
Static Private Member Functions
static bool TryParseDMS (string value, out float dec)
Try to parse a string as a Latitude/Longitude.
static bool TryParseDMSPair (string value, out LatLngPoint point)
static bool TryParseDecimal (string value, out LatLngPoint point)
static string ToDMS (float value, string negative, string positive, int sigfigs, IFormatProvider provider)
Pretty-print the Degrees/Minutes/Second version of the Latitude/Longitude angles.
Detailed Description
A point in geographic space on a radial coordinate system.
Definition at line 13 of file LatLngPoint.cs.
Constructor & Destructor Documentation
LatLngPoint() [1/4]
Juniper.World.GIS.LatLngPoint.LatLngPoint (float lat, float lng, float alt) inline
Create a new instance of LatLngPoint.
Parameters
lat The latitude
lng The longitude
alt The altitude
Definition at line 42 of file LatLngPoint.cs.
         {
             Latitude = lat;
             Longitude = lng;
             Altitude = alt;
         }
References Juniper.World.GIS.LatLngPoint.Altitude, Juniper.World.GIS.LatLngPoint.Latitude, and Juniper.World.GIS.LatLngPoint.Longitude.
LatLngPoint() [2/4]
Juniper.World.GIS.LatLngPoint.LatLngPoint (float lat, float lng) inline
Definition at line 49 of file LatLngPoint.cs.
 : this(lat, lng, 0) { }
LatLngPoint() [3/4]
Juniper.World.GIS.LatLngPoint.LatLngPoint () inline
Definition at line 51 of file LatLngPoint.cs.
 : this(0, 0, 0) { }
Referenced by Juniper.World.GIS.LatLngPoint.TryParseDecimal(), and Juniper.World.GIS.LatLngPoint.TryParseDMSPair().
LatLngPoint() [4/4]
Juniper.World.GIS.LatLngPoint.LatLngPoint (SerializationInfo info, StreamingContext context) inline private
Deserialize the object.
Parameters
info
context
Definition at line 60 of file LatLngPoint.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Latitude = Longitude = Altitude = 0;
             foreach (var pair in info)
             {
                 switch (pair.Name.ToLowerInvariant().Substring(0, 3))
                 {
                     case "lat":
                     Latitude = info.GetSingle(pair.Name);
                     break;
                     case "lon":
                     case "lng":
                     Longitude = info.GetSingle(pair.Name);
                     break;
                     case "alt":
                     Altitude = info.GetSingle(pair.Name);
                     break;
                 }
             }
         }
References Juniper.World.GIS.LatLngPoint.Altitude, Juniper.World.GIS.LatLngPoint.Latitude, and Juniper.World.GIS.LatLngPoint.Longitude.
Member Function Documentation
CompareTo()
int Juniper.World.GIS.LatLngPoint.CompareTo (LatLngPoint other) inline
Definition at line 308 of file LatLngPoint.cs.
         {
             if (other is null)
             {
                 return -1;
             }
             else
             {
                 var byLat = Latitude.CompareTo(other.Latitude);
                 var byLng = Longitude.CompareTo(other.Longitude);
                 var byAlt = Altitude.CompareTo(other.Altitude);
                 if (byLat == 0
                     && byLng == 0)
                 {
                     return byAlt;
                 }
                 else if (byLat == 0)
                 {
                     return byLng;
                 }
                 else
                 {
                     return byLat;
                 }
             }
         }
References Juniper.World.GIS.LatLngPoint.Altitude, Juniper.World.GIS.LatLngPoint.Latitude, and Juniper.World.GIS.LatLngPoint.Longitude.
Referenced by Juniper.World.GIS.Google.StreetView.MetadataResponse.CompareTo().
Equals() [1/2]
override bool Juniper.World.GIS.LatLngPoint.Equals (object obj) inline
Check two LatLngPoints to see if they overlap.
Parameters
obj The number of obj
Returns
Whether or not the two values represent the same point on earth.
Definition at line 273 of file LatLngPoint.cs.
         {
             return obj is LatLngPoint p && Equals(p);
         }
Equals() [2/2]
bool Juniper.World.GIS.LatLngPoint.Equals (LatLngPoint other) inline
Definition at line 278 of file LatLngPoint.cs.
         {
             return other is object
                 && Latitude == other.Latitude
                 && Longitude == other.Longitude
                 && Altitude == other.Altitude;
         }
References Juniper.World.GIS.LatLngPoint.Altitude, Juniper.World.GIS.LatLngPoint.Latitude, and Juniper.World.GIS.LatLngPoint.Longitude.
GetHashCode()
override int Juniper.World.GIS.LatLngPoint.GetHashCode () inline
The hash code is used for putting objects into dictionaries.
Returns
A hash code
Definition at line 301 of file LatLngPoint.cs.
         {
             return Latitude.GetHashCode()
                 ^ Longitude.GetHashCode()
                 ^ Altitude.GetHashCode();
         }
References Juniper.World.GIS.LatLngPoint.Altitude, Juniper.World.GIS.LatLngPoint.Latitude, and Juniper.World.GIS.LatLngPoint.Longitude.
GetObjectData()
void Juniper.World.GIS.LatLngPoint.GetObjectData (SerializationInfo info, StreamingContext context) inline
Get serialization data from the object.
Parameters
info
context
Definition at line 93 of file LatLngPoint.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(nameof(Latitude), Latitude);
             info.AddValue(nameof(Longitude), Longitude);
             info.AddValue(nameof(Altitude), Altitude);
         }
References Juniper.World.GIS.LatLngPoint.Altitude, Juniper.World.GIS.LatLngPoint.Latitude, and Juniper.World.GIS.LatLngPoint.Longitude.
operator !=()
static bool Juniper.World.GIS.LatLngPoint.operator != (LatLngPoint left, LatLngPoint right) inline static
Definition at line 292 of file LatLngPoint.cs.
         {
             return !(left == right);
         }
operator >()
static bool Juniper.World.GIS.LatLngPoint.operator > (LatLngPoint left, LatLngPoint right) inline static
Definition at line 349 of file LatLngPoint.cs.
         {
             return left is object
                 && left.CompareTo(right) > 0;
         }
operator >=()
static bool Juniper.World.GIS.LatLngPoint.operator >= (LatLngPoint left, LatLngPoint right) inline static
Definition at line 355 of file LatLngPoint.cs.
         {
             return left is null
                 ? right is null
                 : left.CompareTo(right) >= 0;
         }
operator string()
static Juniper.World.GIS.LatLngPoint.operator string (LatLngPoint value) inline explicit static
Definition at line 238 of file LatLngPoint.cs.
         {
             return value?.ToString(CultureInfo.InvariantCulture);
         }
References Juniper.World.GIS.LatLngPoint.ToString().
operator<()
static bool Juniper.World.GIS.LatLngPoint.operator< (LatLngPoint left, LatLngPoint right) inline static
Definition at line 336 of file LatLngPoint.cs.
         {
             return left is null
                 ? right is object
                 : left.CompareTo(right) < 0;
         }
operator<=()
static bool Juniper.World.GIS.LatLngPoint.operator<= (LatLngPoint left, LatLngPoint right) inline static
Definition at line 343 of file LatLngPoint.cs.
         {
             return left is null
                 || left.CompareTo(right) <= 0;
         }
operator==()
static bool Juniper.World.GIS.LatLngPoint.operator== (LatLngPoint left, LatLngPoint right) inline static
Definition at line 286 of file LatLngPoint.cs.
         {
             return ReferenceEquals(left, right)
                 || (left is object && left.Equals(right));
         }
Parse()
static LatLngPoint Juniper.World.GIS.LatLngPoint.Parse (string value) inline static
Definition at line 166 of file LatLngPoint.cs.
         {
             if (TryParse(value, out var point))
             {
                 return point;
             }
             else
             {
                 throw new FormatException("Value needs to be a pair of Degrees-Minutes-Seconds values or a pair of Decimal Degrees values, separated by a comma.");
             }
         }
References Juniper.World.GIS.LatLngPoint.TryParse().
ToDMS() [1/3]
string Juniper.World.GIS.LatLngPoint.ToDMS (int sigfigs) inline
Pretty-print the Degrees/Minutes/Second version of the Latitude/Longitude angles.
Parameters
sigfigs The number of significant figures
Returns
A printed format for the latitude/longitude in degrees/minutes/seconds
Definition at line 183 of file LatLngPoint.cs.
         {
             return ToDMS(sigfigs, CultureInfo.CurrentCulture);
         }
Referenced by Juniper.World.GIS.GPSLocation.PrintDebugReport(), and Juniper.World.GIS.LatLngPoint.ToDMS().
ToDMS() [2/3]
string Juniper.World.GIS.LatLngPoint.ToDMS (int sigfigs, IFormatProvider provider) inline
Definition at line 188 of file LatLngPoint.cs.
         {
             var latStr = ToDMS(Latitude, "S", "N", sigfigs, provider);
             var lngStr = ToDMS(Longitude, "W", "E", sigfigs, provider);
             var altStr = Units.Converter.Label(Altitude, Units.UnitOfMeasure.Meters);
             return $"<{latStr}, {lngStr}> alt {altStr}";
         }
References Juniper.World.GIS.LatLngPoint.Altitude, Juniper.World.GIS.LatLngPoint.Latitude, Juniper.World.GIS.LatLngPoint.Longitude, and Juniper.World.GIS.LatLngPoint.ToDMS().
ToDMS() [3/3]
static string Juniper.World.GIS.LatLngPoint.ToDMS (float value, string negative, string positive, int sigfigs, IFormatProvider provider) inline static private
Pretty-print the Degrees/Minutes/Second version of the Latitude/Longitude angles.
Parameters
value The decimal degree value to format
negative The string prefix to use when the value is negative
positive The string prefix to use when the value is positive
sigfigs The number of significant figures to which to print the value
Returns
The degrees/minutes/seconds version of the decimal degree
Definition at line 204 of file LatLngPoint.cs.
         {
             var hemisphere = value < 0
                 ? negative
                 : positive;
             value = Abs(value);
             var degrees = (int)value;
             var minutes = (value - degrees) * 60;
             var intMinutes = (int)minutes;
             var seconds = (minutes - intMinutes) * 60;
             var secondsStr = seconds.SigFig(sigfigs);
             while (secondsStr.IndexOf(".", StringComparison.Ordinal) <= 1)
             {
                 secondsStr = "0" + secondsStr;
             }
             return $"{hemisphere} {degrees.ToString(provider)} {intMinutes.ToString(provider)}' {secondsStr}\"";
         }
ToString() [1/5]
override string Juniper.World.GIS.LatLngPoint.ToString () inline
Pretty-print the LatLngPoint for easier debugging.
Returns
A decimal degrees printed format
Definition at line 228 of file LatLngPoint.cs.
         {
             return ToString(CultureInfo.InvariantCulture);
         }
Referenced by Juniper.World.GIS.Google.MapTiles.LinePathCollection.Add(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Contains(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Insert(), Juniper.World.GIS.LatLngPoint.operator string(), Juniper.World.GIS.Google.MapTiles.LinePathCollection.Remove(), and Juniper.World.GIS.LatLngPoint.ToString().
ToString() [2/5]
string Juniper.World.GIS.LatLngPoint.ToString (IFormatProvider provider) inline
Definition at line 233 of file LatLngPoint.cs.
         {
             return Latitude.ToString("0.000000", provider) + "," + Longitude.ToString("0.000000", provider);
         }
References Juniper.World.GIS.LatLngPoint.Latitude, and Juniper.World.GIS.LatLngPoint.Longitude.
ToString() [3/5]
string Juniper.World.GIS.LatLngPoint.ToString (int sigfigs) inline
Pretty-print the LatLngPoint for easier debugging.
Parameters
sigfigs The number of sigfigs
Returns
A decimal degrees printed format with rounding
Definition at line 248 of file LatLngPoint.cs.
         {
             return $"({Latitude.SigFig(sigfigs)}, {Longitude.SigFig(sigfigs)})";
         }
ToString() [4/5]
string Juniper.World.GIS.LatLngPoint.ToString (string precision, IFormatProvider provider) inline
Pretty-print the LatLngPoint for easier debugging.
Parameters
precision The number of precision
Returns
A decimal degrees printed format with a .NET number format specifier
Definition at line 258 of file LatLngPoint.cs.
         {
             return $"({Latitude.ToString(precision, provider)}, {Longitude.ToString(precision, provider)})";
         }
ToString() [5/5]
string Juniper.World.GIS.LatLngPoint.ToString (string precision) inline
Definition at line 263 of file LatLngPoint.cs.
         {
             return ToString(precision, CultureInfo.CurrentCulture);
         }
References Juniper.World.GIS.LatLngPoint.ToString().
TryParse()
static bool Juniper.World.GIS.LatLngPoint.TryParse (string value, out LatLngPoint point) inline static
Definition at line 146 of file LatLngPoint.cs.
         {
             return TryParseDecimal(value, out point)
                 || TryParseDMSPair(value, out point);
         }
References Juniper.World.GIS.LatLngPoint.TryParseDecimal(), and Juniper.World.GIS.LatLngPoint.TryParseDMSPair().
Referenced by Juniper.World.GIS.LatLngPoint.Parse(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.ParseSearchParams(), Juniper.Processes.ProcessArgs.TryGetLatLng(), Juniper.World.GIS.LatLngPoint.TryParseDecimal(), and Juniper.World.GIS.LatLngPoint.TryParseDMS().
TryParseDecimal()
static bool Juniper.World.GIS.LatLngPoint.TryParseDecimal (string value, out LatLngPoint point) inline static private
Definition at line 152 of file LatLngPoint.cs.
         {
             point = null;
             var parts = value.SplitX(',');
             if (parts.Length == 2
                 && float.TryParse(parts[0].Trim(), out var lat)
                 && float.TryParse(parts[1].Trim(), out var lng))
             {
                 point = new LatLngPoint(lat, lng);
             }
             return point is object;
         }
References Juniper.World.GIS.LatLngPoint.LatLngPoint(), and Juniper.World.GIS.LatLngPoint.TryParse().
Referenced by Juniper.World.GIS.LatLngPoint.TryParse().
TryParseDMS()
static bool Juniper.World.GIS.LatLngPoint.TryParseDMS (string value, out float dec) inline static private
Try to parse a string as a Latitude/Longitude.
Parameters
value A degrees/minutes/seconds formated degree value.
dec The decimal degrees formated degree value that the value represents
Returns
Whether or not the degrees/minutes/seconds value parsed correctly
Definition at line 111 of file LatLngPoint.cs.
         {
             dec = 0;
             var parts = value.SplitX(' ');
             var hemisphere = parts[0];
             if ((hemisphere == "N" || hemisphere == "S" || hemisphere == "E" || hemisphere == "W")
                 && int.TryParse(parts[1], out var degrees)
                 && float.TryParse(parts[2], out var minutes))
             {
                 dec = degrees + (minutes / 60.0f);
                 if (hemisphere == "S" || hemisphere == "W")
                 {
                     dec *= -1;
                 }
                 return true;
             }
             return false;
         }
References Juniper.World.GIS.LatLngPoint.TryParse().
Referenced by Juniper.World.GIS.LatLngPoint.TryParseDMSPair().
TryParseDMSPair()
static bool Juniper.World.GIS.LatLngPoint.TryParseDMSPair (string value, out LatLngPoint point) inline static private
Definition at line 132 of file LatLngPoint.cs.
         {
             point = null;
             var parts = value.SplitX(',');
             if (parts.Length == 2
                 && TryParseDMS(parts[0], out var lat)
                 && TryParseDMS(parts[1], out var lng))
             {
                 point = new LatLngPoint(lat, lng);
             }
             return point is object;
         }
References Juniper.World.GIS.LatLngPoint.LatLngPoint(), and Juniper.World.GIS.LatLngPoint.TryParseDMS().
Referenced by Juniper.World.GIS.LatLngPoint.TryParse().
Property Documentation
Altitude
float Juniper.World.GIS.LatLngPoint.Altitude get
An altitude value thrown in just for kicks. It makes some calculations and conversions easier if we keep the Altitude value.
Definition at line 22 of file LatLngPoint.cs.
 { get; }
Referenced by Juniper.World.GIS.LatLngPoint.CompareTo(), Juniper.World.GIS.LatLngPoint.Equals(), Juniper.World.GIS.LatLngPoint.GetHashCode(), Juniper.World.GIS.LatLngPoint.GetObjectData(), Juniper.World.GIS.LatLngPoint.LatLngPoint(), Juniper.World.GIS.LatLngPoint.ToDMS(), and Juniper.Units.LatLng.ToUTM().
Latitude
float Juniper.World.GIS.LatLngPoint.Latitude get
Lines of latitude run east/west around the globe, parallel to the equator, never intersecting. They measure angular distance north/south.
Definition at line 28 of file LatLngPoint.cs.
 { get; }
Referenced by Juniper.World.GIS.LatLngPoint.CompareTo(), Juniper.World.GIS.LatLngPoint.Equals(), Juniper.World.GIS.LatLngPoint.GetHashCode(), Juniper.World.GIS.Google.Geocoding.GeometryViewport.GetObjectData(), Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData(), Juniper.World.GIS.Google.StreetView.MetadataResponse.GetObjectData(), Juniper.World.GIS.LatLngPoint.GetObjectData(), Juniper.World.GIS.LatLngPoint.LatLngPoint(), Juniper.World.GIS.LatLngPointEditor.OnGUI(), Juniper.World.GIS.LatLngPointExt.SphericalMercator(), Juniper.World.GIS.LatLngPoint.ToDMS(), Juniper.Units.EquitorialSpherical.ToHorizontal(), Juniper.World.GIS.LatLngPoint.ToString(), and Juniper.Units.LatLng.ToUTM().
Longitude
float Juniper.World.GIS.LatLngPoint.Longitude get
Lines of longitude run north/south around the globe, intersecting at the poles. They measure angular distance east/west.
Definition at line 34 of file LatLngPoint.cs.
 { get; }
Referenced by Juniper.World.GIS.LatLngPoint.CompareTo(), Juniper.World.GIS.LatLngPoint.Equals(), Juniper.World.GIS.LatLngPoint.GetHashCode(), Juniper.World.GIS.Google.Geocoding.GeometryViewport.GetObjectData(), Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData(), Juniper.World.GIS.Google.StreetView.MetadataResponse.GetObjectData(), Juniper.World.GIS.LatLngPoint.GetObjectData(), Juniper.World.GIS.LatLngPoint.LatLngPoint(), Juniper.World.GIS.LatLngPointExt.SphericalMercator(), Juniper.World.GIS.LatLngPoint.ToDMS(), Juniper.Units.EquitorialSpherical.ToHorizontal(), Juniper.World.GIS.LatLngPoint.ToString(), and Juniper.Units.LatLng.ToUTM().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/World/GIS/LatLngPoint.cs