Juniper: Juniper.Security.ICredentialReceiverExt Class Reference
Juniper.Security.ICredentialReceiverExt Class Reference
Static Public Member Functions
static void ClearCredentials (this ICredentialReceiver receiver)
static void ReceiveCredentials (this ICredentialReceiver receiver)
static void ReceiveCredentials (this ICredentialReceiver receiver, string fileName)
Detailed Description
Definition at line 6 of file ICredentialReceiverExt.cs.
Member Function Documentation
ClearCredentials()
static void Juniper.Security.ICredentialReceiverExt.ClearCredentials (this ICredentialReceiver receiver) inline static
Definition at line 8 of file ICredentialReceiverExt.cs.
         {
             if (receiver is null)
             {
                 throw new System.ArgumentNullException(nameof(receiver));
             }
             receiver.ReceiveCredentials(null);
         }
References Juniper.Security.ICredentialReceiver.ReceiveCredentials().
ReceiveCredentials() [1/2]
static void Juniper.Security.ICredentialReceiverExt.ReceiveCredentials (this ICredentialReceiver receiver) inline static
Definition at line 18 of file ICredentialReceiverExt.cs.
         {
             if (receiver is null)
             {
                 throw new System.ArgumentNullException(nameof(receiver));
             }
             receiver.ReceiveCredentials(receiver.CredentialFile);
         }
References Juniper.Security.ICredentialReceiver.CredentialFile, and Juniper.Security.ICredentialReceiver.ReceiveCredentials().
ReceiveCredentials() [2/2]
static void Juniper.Security.ICredentialReceiverExt.ReceiveCredentials (this ICredentialReceiver receiver, string fileName) inline static
Definition at line 28 of file ICredentialReceiverExt.cs.
         {
             if (receiver is null)
             {
                 throw new System.ArgumentNullException(nameof(receiver));
             }
             if (File.Exists(fileName))
             {
                 receiver.ReceiveCredentials(File.ReadAllLines(fileName));
             }
         }
References Juniper.Security.ICredentialReceiver.ReceiveCredentials().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Security/ICredentialReceiverExt.cs