Juniper: Hjg.Pngcs.PngIDatChunkOutputStream Class Reference
Hjg.Pngcs.PngIDatChunkOutputStream Class Reference
outputs the stream for IDAT chunk , fragmented at fixed size (32k default).
Public Member Functions
PngIDatChunkOutputStream (Stream outputStream_0)
PngIDatChunkOutputStream? (Stream outputStream_0, int size)
override void Close ()
override void Flush ()
override void Write (byte[] b, int off, int len)
void Write (byte[] b)
long GetCountFlushed ()
Protected Member Functions
override void Dispose (bool disposing)
override void FlushBuffer (byte[] b, int len)
Private Attributes
const int SIZE_DEFAULT = 32768
readonly Stream outputStream
Detailed Description
outputs the stream for IDAT chunk , fragmented at fixed size (32k default).
Definition at line 11 of file PngIDatChunkOutputStream.cs.
Constructor & Destructor Documentation
PngIDatChunkOutputStream()
Hjg.Pngcs.PngIDatChunkOutputStream.PngIDatChunkOutputStream (Stream outputStream_0) inline
Definition at line 16 of file PngIDatChunkOutputStream.cs.
             : this(outputStream_0, SIZE_DEFAULT)
         {
         }
Member Function Documentation
Close()
override void Hjg.Pngcs.PngIDatChunkOutputStream.Close () inline
Definition at line 46 of file PngIDatChunkOutputStream.cs.
         {
             // closing the IDAT stream only flushes it, it does not close the underlying stream
             Flush();
         }
References Hjg.Pngcs.ProgressiveOutputStream.Flush().
Referenced by Hjg.Pngcs.PngWriter.End().
Dispose()
override void Hjg.Pngcs.PngIDatChunkOutputStream.Dispose (bool disposing) inline protected
Definition at line 27 of file PngIDatChunkOutputStream.cs.
         {
             if (disposing)
             {
                 outputStream.Dispose();
             }
             base.Dispose(disposing);
         }
References Hjg.Pngcs.PngIDatChunkOutputStream.outputStream.
Referenced by Hjg.Pngcs.PngWriter.Dispose().
Flush()
override void Hjg.Pngcs.ProgressiveOutputStream.Flush () inline inherited
Definition at line 30 of file ProgressiveOutputStream.cs.
         {
             base.Flush();
             CheckFlushBuffer(true);
         }
References Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer().
Referenced by Hjg.Pngcs.ProgressiveOutputStream.Close(), and Hjg.Pngcs.PngIDatChunkOutputStream.Close().
FlushBuffer()
override void Hjg.Pngcs.PngIDatChunkOutputStream.FlushBuffer (byte [] b, int len) inline protected virtual
Implements Hjg.Pngcs.ProgressiveOutputStream.
Definition at line 37 of file PngIDatChunkOutputStream.cs.
         {
             var c = new ChunkRaw(len, ChunkHelper.b_IDAT, false)
             {
                 Data = b
             };
             c.WriteChunk(outputStream);
         }
References Hjg.Pngcs.Chunks.ChunkHelper.b_IDAT, Hjg.Pngcs.PngIDatChunkOutputStream.outputStream, and Hjg.Pngcs.Chunks.ChunkRaw.WriteChunk().
GetCountFlushed()
long Hjg.Pngcs.ProgressiveOutputStream.GetCountFlushed () inline inherited
Definition at line 84 of file ProgressiveOutputStream.cs.
         {
             return countFlushed;
         }
References Hjg.Pngcs.ProgressiveOutputStream.countFlushed.
Referenced by Hjg.Pngcs.PngWriter.ComputeCompressionRatio().
PngIDatChunkOutputStream?()
Hjg.Pngcs.PngIDatChunkOutputStream.PngIDatChunkOutputStream? (Stream outputStream_0, int size) inline
Definition at line 21 of file PngIDatChunkOutputStream.cs.
             : base(size > 8 ? size : SIZE_DEFAULT)
         {
             outputStream = outputStream_0;
         }
References Hjg.Pngcs.PngIDatChunkOutputStream.outputStream.
Write() [1/2]
override void Hjg.Pngcs.ProgressiveOutputStream.Write (byte [] b, int off, int len) inline inherited
Definition at line 36 of file ProgressiveOutputStream.cs.
         {
             base.Write(b, off, len);
             CheckFlushBuffer(false);
         }
References Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer().
Referenced by Hjg.Pngcs.ProgressiveOutputStream.Write().
Write() [2/2]
void Hjg.Pngcs.ProgressiveOutputStream.Write (byte [] b) inline inherited
Definition at line 42 of file ProgressiveOutputStream.cs.
         {
             Write(b, 0, b.Length);
             CheckFlushBuffer(false);
         }
References Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer(), and Hjg.Pngcs.ProgressiveOutputStream.Write().
Member Data Documentation
outputStream
readonly Stream Hjg.Pngcs.PngIDatChunkOutputStream.outputStream private
Definition at line 14 of file PngIDatChunkOutputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkOutputStream.Dispose(), Hjg.Pngcs.PngIDatChunkOutputStream.FlushBuffer(), and Hjg.Pngcs.PngIDatChunkOutputStream.PngIDatChunkOutputStream?().
SIZE_DEFAULT
const int Hjg.Pngcs.PngIDatChunkOutputStream.SIZE_DEFAULT = 32768 private
Definition at line 13 of file PngIDatChunkOutputStream.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/PngIDatChunkOutputStream.cs