Juniper: Juniper.Unity.Audio.ResonanceInteractionAudio Class Reference
Juniper.Unity.Audio.ResonanceInteractionAudio Class Reference
Public Member Functions
override void Install (bool reset)
Install, with or without a full reset.
override void Uninstall ()
Remove platform-specific features from the object.
AudioSource Spatialize (AudioSource audioSource, bool loop, AudioMixerGroup group)
AudioSource Spatialize (AudioSource audioSource, bool loop)
AudioSource Spatialize (AudioSource audioSource, AudioMixerGroup group)
AudioSource Spatialize (AudioSource audioSource)
void Reinstall ()
Reinstall the object with a full reset.
virtual void Awake ()
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
void Start ()
void OnValidate ()
Static Public Member Functions
static HapticExpression GetHapticExpressions (Interaction action)
Converts an Interaction into a haptic expression to be able to play.
static float Play (Interaction action, AbstractHapticDevice haptics)
Play the specified action at the camera position using the specified haptics, with no callback.
static float Play (Interaction action, Transform pose, AbstractHapticDevice haptics)
Play the specified action using the specified pose and haptic subsystem, with no callback.
static float Play (Interaction action, AbstractHapticDevice haptics, Action onComplete)
Play the specified action at the camera position using the specified haptics, with a callback on completion.
static float Play (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete)
Play the specified action using the specified pose and haptic subsystem, with a callback on completion.
Public Attributes
AudioMixerGroup defaultMixerGroup
The audio mixer to use with ResonanceAudio
GameObject volumeSlider
AudioClipCollection soundOnClosed
The sound to play when an Widgets.Openable object has been closed.
AudioClipCollection soundOnDisabled
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
AudioClipCollection soundOnDragged
The sound to play when a Widgets.Draggable has been moved more than 10cm.
AudioClipCollection soundOnEntered
The sound to play when a cursor first hovers over any Widgets.Touchable.
AudioClipCollection soundOnError
The sound to play when an operation needs to indicate an error.
AudioClipCollection soundOnExited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
AudioClipCollection soundOnOpened
The sound to play when an Widgets.Openable object has been opened.
AudioClipCollection soundOnReleased
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
AudioClipCollection soundOnScrolled
The sound to play when a scrollable section is moved a certain distance.
AudioClipCollection soundOnSelected
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
AudioClipCollection soundOnSuccess
The sound to play when a long-running operating needs to indicate success.
AudioClip soundOnStartUp
The sound to play when the application first starts up.
AudioClip soundOnShutDown
The sound to play right before the application shuts down.
Protected Member Functions
override AudioSource InternalSpatialize (AudioSource audioSource, bool loop, AudioMixerGroup group)
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Protected Attributes
ResonanceAudioListener resListener
AudioListener listener
Properties
override string DefaultAudioMixer [get]
float???? Volume [get, set]
Private Member Functions
void OnDisplayTypeChange (object sender, DisplayTypes e)
Detailed Description
Definition at line 9 of file ResonanceInteractionAudio.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Audio.AbstractInteractionAudio.Awake () inline virtual inherited
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
Definition at line 275 of file InteractionAudio.cs.
         {
             if (instance != null)
             {
                 Debug.LogWarning("Juniper: There can be only one! (R2D2)");
                 this.Destroy();
             }
             else
             {
                 Install(false);
                 instance = this;
                 camT = DisplayManager.MainCamera.transform;
 #if UNITY_MODULES_AUDIO
                 startUp = new SingleAudioClipCollection(soundOnStartUp, false);
                 shutDown = new SingleAudioClipCollection(soundOnShutDown, false);
                 audioSources = new List<AudioSource>(10);
                 if (volumeSlider != null)
                 {
                     volume = volumeSlider.GetSlider();
                     volume.ValueChange += Volume_ValueChange;
                 }
 #endif
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.audioSources, Juniper.Unity.Audio.AbstractInteractionAudio.camT, Juniper.Unity.Audio.AbstractInteractionAudio.Install(), Juniper.Unity.Audio.AbstractInteractionAudio.instance, Juniper.Unity.Display.AbstractDisplayManager.MainCamera, Juniper.Unity.Audio.AbstractInteractionAudio.shutDown, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnShutDown, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnStartUp, Juniper.Unity.Audio.AbstractInteractionAudio.startUp, Juniper.Unity.Widgets.IValuedControl< T >.ValueChange, Juniper.Unity.Audio.AbstractInteractionAudio.volume, Juniper.Unity.Audio.AbstractInteractionAudio.Volume_ValueChange(), and Juniper.Unity.Audio.AbstractInteractionAudio.volumeSlider.
GetHapticExpressions()
static HapticExpression Juniper.Unity.Audio.AbstractInteractionAudio.GetHapticExpressions (Interaction action) inline static inherited
Converts an Interaction into a haptic expression to be able to play.
Returns
The haptic expressions.
Parameters
action Action.
Definition at line 50 of file InteractionAudio.cs.
         {
             switch (action)
             {
                 case Interaction.Closed:
                 return HapticExpression.Heavy;
                 case Interaction.Disabled:
                 return HapticExpression.Warning;
                 case Interaction.DraggingStarted:
                 case Interaction.Dragged:
                 case Interaction.DraggingEnded:
                 return HapticExpression.SelectionChange;
                 case Interaction.Error:
                 return HapticExpression.Error;
                 case Interaction.Opened:
                 return HapticExpression.Medium;
                 case Interaction.Clicked:
                 return HapticExpression.Light;
                 case Interaction.Success:
                 return HapticExpression.Success;
                 default:
                 return HapticExpression.None;
             }
         }
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.PlayHaptics().
Install()
override void Juniper.Unity.Audio.ResonanceInteractionAudio.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Reimplemented from Juniper.Unity.Audio.AbstractInteractionAudio.
Definition at line 22 of file ResonanceInteractionAudio.cs.
         {
             base.Install(reset);
             var js = ComponentExt.FindAny<JuniperSystem>();
             var dsp = ComponentExt.FindAny<DisplayManager>();
             resListener = listener.Ensure<ResonanceAudioListener>().Value;
             resListener.stereoSpeakerModeEnabled = Application.isEditor || js.DisplayType != DisplayTypes.Stereo;
             dsp.DisplayTypeChange += OnDisplayTypeChange;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.listener, Juniper.Unity.Audio.ResonanceInteractionAudio.OnDisplayTypeChange(), and Juniper.Unity.Audio.ResonanceInteractionAudio.resListener.
InternalSpatialize()
override AudioSource Juniper.Unity.Audio.ResonanceInteractionAudio.InternalSpatialize (AudioSource audioSource, bool loop, AudioMixerGroup group) inline protected virtual
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Parameters
audioSource
loop
group
Returns
Reimplemented from Juniper.Unity.Audio.AbstractInteractionAudio.
Definition at line 47 of file ResonanceInteractionAudio.cs.
         {
             audioSource = base.InternalSpatialize(audioSource, loop, group);
             var resSource = audioSource.Ensure<ResonanceAudioSource>().Value;
             resSource.quality = ResonanceAudioSource.Quality.High;
             return audioSource;
         }
OnDisplayTypeChange()
void Juniper.Unity.Audio.ResonanceInteractionAudio.OnDisplayTypeChange (object sender, DisplayTypes e) inline private
Definition at line 34 of file ResonanceInteractionAudio.cs.
         {
             resListener.stereoSpeakerModeEnabled = Application.isEditor || e != DisplayTypes.Stereo;
         }
References Juniper.Unity.Audio.ResonanceInteractionAudio.resListener.
Referenced by Juniper.Unity.Audio.ResonanceInteractionAudio.Install().
OnValidate()
void Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate () inline inherited
Definition at line 510 of file InteractionAudio.cs.
         {
             if (defaultMixerGroup == null)
             {
                 defaultMixerGroup =
                     (from g in Resources.FindObjectsOfTypeAll<AudioMixerGroup>()
                      where g.audioMixer.name == DefaultAudioMixer
                      orderby g.name == "Master" descending
                      select g)
                         .FirstOrDefault();
             }
             if (defaultMixerGroup != null)
             {
                 Volume = PlayerPrefs.GetFloat(MASTER_VOLUME_KEY, 1);
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.DefaultAudioMixer, Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup, Juniper.Unity.Audio.AbstractInteractionAudio.MASTER_VOLUME_KEY, and Juniper.Unity.Audio.AbstractInteractionAudio.Volume.
Play() [1/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, AbstractHapticDevice haptics) inline static inherited
Play the specified action at the camera position using the specified haptics, with no callback.
Returns
The play.
Parameters
action Action.
haptics Haptics.
Definition at line 88 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, haptics) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Referenced by Juniper.Unity.Widgets.AttentionDirector.FoundCoroutine(), Juniper.Unity.Widgets.AttentionDirector.LostCoroutine(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
Play() [2/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, Transform pose, AbstractHapticDevice haptics) inline static inherited
Play the specified action using the specified pose and haptic subsystem, with no callback.
Returns
The play.
Parameters
action Action.
pose Pose.
haptics Haptics.
Definition at line 100 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, pose, haptics) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play() [3/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, AbstractHapticDevice haptics, Action onComplete) inline static inherited
Play the specified action at the camera position using the specified haptics, with a callback on completion.
Returns
The play.
Parameters
action Action.
haptics Haptics.
onComplete
Definition at line 113 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, haptics, onComplete) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play() [4/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete) inline static inherited
Play the specified action using the specified pose and haptic subsystem, with a callback on completion.
Returns
The play.
Parameters
action Action.
pose Pose.
haptics Haptics.
onComplete
Definition at line 127 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, pose, haptics, onComplete) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Reinstall()
void Juniper.Unity.Audio.AbstractInteractionAudio.Reinstall () inline inherited
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 250 of file InteractionAudio.cs.
         {
             Install(true);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.Install().
Spatialize() [1/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource, bool loop, AudioMixerGroup group) inline inherited
Definition at line 134 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, loop, group);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Referenced by Juniper.Unity.Video.Video360.CreateAudioTracks(), Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource(), and Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine().
Spatialize() [2/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource, bool loop) inline inherited
Definition at line 139 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, loop, defaultMixerGroup);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup, and Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Spatialize() [3/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource, AudioMixerGroup group) inline inherited
Definition at line 144 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, false, group);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Spatialize() [4/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource) inline inherited
Definition at line 149 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, false, defaultMixerGroup);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup, and Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Start()
void Juniper.Unity.Audio.AbstractInteractionAudio.Start () inline inherited
Definition at line 487 of file InteractionAudio.cs.
         {
             for (var i = 0; i < 5; ++i)
             {
                 CreateNewAudioSource();
             }
             Volume = PlayerPrefs.GetFloat(MASTER_VOLUME_KEY, 1);
             if (volume != null)
             {
                 volume.value = Volume;
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource(), Juniper.Unity.Audio.AbstractInteractionAudio.MASTER_VOLUME_KEY, Juniper.Unity.Widgets.IValuedControl< T >.value, Juniper.Unity.Audio.AbstractInteractionAudio.volume, and Juniper.Unity.Audio.AbstractInteractionAudio.Volume.
Uninstall()
override void Juniper.Unity.Audio.ResonanceInteractionAudio.Uninstall () inline virtual
Remove platform-specific features from the object.
Reimplemented from Juniper.Unity.Audio.AbstractInteractionAudio.
Definition at line 39 of file ResonanceInteractionAudio.cs.
         {
             ComponentExt.FindAny<AudioListener>()
                 ?.Remove<ResonanceAudioListener>();
             base.Uninstall();
         }
Member Data Documentation
defaultMixerGroup
AudioMixerGroup Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup inherited
The audio mixer to use with ResonanceAudio
Definition at line 160 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource(), Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize(), Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate(), and Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize().
listener
AudioListener Juniper.Unity.Audio.AbstractInteractionAudio.listener protected inherited
Definition at line 239 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.ResonanceInteractionAudio.Install(), and Juniper.Unity.Audio.AbstractInteractionAudio.Install().
resListener
ResonanceAudioListener Juniper.Unity.Audio.ResonanceInteractionAudio.resListener protected
Definition at line 20 of file ResonanceInteractionAudio.cs.
Referenced by Juniper.Unity.Audio.ResonanceInteractionAudio.Install(), and Juniper.Unity.Audio.ResonanceInteractionAudio.OnDisplayTypeChange().
soundOnClosed
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnClosed inherited
The sound to play when an Widgets.Openable object has been closed.
Definition at line 168 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnDisabled
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnDisabled inherited
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
Definition at line 174 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnDragged
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnDragged inherited
The sound to play when a Widgets.Draggable has been moved more than 10cm.
Definition at line 179 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnEntered
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnEntered inherited
The sound to play when a cursor first hovers over any Widgets.Touchable.
Definition at line 184 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnError
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnError inherited
The sound to play when an operation needs to indicate an error.
Definition at line 189 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnExited
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnExited inherited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
Definition at line 195 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnOpened
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnOpened inherited
The sound to play when an Widgets.Openable object has been opened.
Definition at line 200 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnReleased
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnReleased inherited
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
Definition at line 205 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnScrolled
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnScrolled inherited
The sound to play when a scrollable section is moved a certain distance.
Definition at line 210 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnSelected
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnSelected inherited
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
Definition at line 215 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnShutDown
AudioClip Juniper.Unity.Audio.AbstractInteractionAudio.soundOnShutDown inherited
The sound to play right before the application shuts down.
Definition at line 233 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake().
soundOnStartUp
AudioClip Juniper.Unity.Audio.AbstractInteractionAudio.soundOnStartUp inherited
The sound to play when the application first starts up.
Definition at line 228 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake().
soundOnSuccess
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnSuccess inherited
The sound to play when a long-running operating needs to indicate success.
Definition at line 220 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
volumeSlider
GameObject Juniper.Unity.Audio.AbstractInteractionAudio.volumeSlider inherited
Definition at line 162 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.MasterSceneController.SetupSystemInterface().
Property Documentation
DefaultAudioMixer
override string Juniper.Unity.Audio.ResonanceInteractionAudio.DefaultAudioMixer get protected
Definition at line 12 of file ResonanceInteractionAudio.cs.
         {
             get
             {
                 return "ResonanceAudioMixer";
             }
         }
Volume
float???? Juniper.Unity.Audio.AbstractInteractionAudio.Volume get set inherited
Definition at line 557 of file InteractionAudio.cs.
         {
             set
             {
 #if UNITY_MODULES_AUDIO
                 PlayerPrefs.SetFloat(MASTER_VOLUME_KEY, value);
                 PlayerPrefs.Save();
                 var log = Mathf.Log(value) * 11.5f;
                 if (float.IsInfinity(log))
                 {
                     log = -1000;
                 }
                 defaultMixerGroup
                     ?.audioMixer
                     ?.SetFloat("Volume", log);
 #endif
             }
             get
             {
                 float value = 0;
 #if UNITY_MODULES_AUDIO
                 if (defaultMixerGroup?.audioMixer?.GetFloat("Volume", out value) == true)
                 {
                     value = Mathf.Pow(E, value / 11.5f);
                 }
 #endif
                 return value;
             }
         }
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate(), Juniper.Unity.Audio.AbstractInteractionAudio.Start(), and Juniper.Unity.Audio.AbstractInteractionAudio.Volume_ValueChange().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Platforms/Resonance/ResonanceInteractionAudio.cs