Juniper: Juniper.ConfigurationManagement.PlatformConfiguration Class Reference
Juniper.ConfigurationManagement.PlatformConfiguration Class Reference
Public Member Functions
PlatformConfiguration ()
void SwitchTarget ()
void InstallUnityPackages (IProgress prog=null)
void InstallRawPackages (IProgress prog=null)
void Activate (IProgress prog)
void UninstallRawPackages (IProgress prog=null)
void UninstallUnityPackages (IProgress prog=null)
Public Attributes
string Name
string CompilerDefine
string buildTarget
string spatializer
string androidSdkVersion
string iOSVersion
string wsaSubtarget
string [] vrSystems
string [] packages
Properties
BuildTarget BuildTarget [get]
BuildTargetGroup TargetGroup [get]
bool IsSupported [get]
IEnumerable< UnityXRPlatforms > XRPlatforms [get]
UnityPackage [] UninstallableUnityPackages [get, set]
UnityPackage [] IncludedUnityPackages [get, set]
UnityPackage [] ExcludedUnityPackages [get, set]
RawPackage [] UninstallableRawPackages [get, set]
RawPackage [] RawPackages [get, set]
bool TargetSwitchNeeded [get]
List< string > CompilerDefines [get]
Private Member Functions
internal void Deactivate (PlatformConfiguration nextConfiguration)
Detailed Description
Definition at line 16 of file PlatformConfiguration.cs.
Constructor & Destructor Documentation
PlatformConfiguration()
Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration () inline
Definition at line 28 of file PlatformConfiguration.cs.
         {
             Name = null;
             CompilerDefine = null;
             buildTarget = null;
             vrSystems = null;
             packages = null;
             spatializer = null;
             androidSdkVersion = null;
             iOSVersion = null;
             wsaSubtarget = null;
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.androidSdkVersion, Juniper.ConfigurationManagement.PlatformConfiguration.buildTarget, Juniper.ConfigurationManagement.PlatformConfiguration.CompilerDefine, Juniper.ConfigurationManagement.PlatformConfiguration.iOSVersion, Juniper.ConfigurationManagement.PlatformConfiguration.Name, Juniper.ConfigurationManagement.PlatformConfiguration.packages, Juniper.ConfigurationManagement.PlatformConfiguration.spatializer, Juniper.ConfigurationManagement.PlatformConfiguration.vrSystems, and Juniper.ConfigurationManagement.PlatformConfiguration.wsaSubtarget.
Member Function Documentation
Activate()
void Juniper.ConfigurationManagement.PlatformConfiguration.Activate (IProgress prog) inline
Definition at line 198 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(
                 IncludedUnityPackages, progs[0],
                 (pkg, p) => pkg.Activate(TargetGroup, p));
             Platforms.ForEachPackage(
                 RawPackages, progs[1],
                 (pkg, p) => pkg.Activate(TargetGroup, p));
             if (!string.IsNullOrEmpty(spatializer))
             {
                 var hasSpatializer = AudioSettings
                     .GetSpatializerPluginNames()
                     .Contains(spatializer);
                 if (hasSpatializer)
                 {
                     AudioSettings.SetSpatializerPluginName(spatializer);
                     AudioSettingsExt.SetAmbisonicDecoderPluginName(spatializer);
                 }
             }
             var supportedVRSDKs = PlayerSettings.GetAvailableVirtualRealitySDKs(TargetGroup);
             var vrSDKs = XRPlatforms
                 .Distinct()
                 .Select(x => x.ToString())
                 .Where(supportedVRSDKs.Contains)
                 .ToArray();
             var enableVR = vrSDKs.Any(sdk => sdk != "None");
             if (enableVR != PlayerSettings.GetVirtualRealitySupported(TargetGroup))
             {
                 PlayerSettings.SetVirtualRealitySupported(TargetGroup, enableVR);
                 if (enableVR && !vrSDKs.Matches(PlayerSettings.GetVirtualRealitySDKs(TargetGroup)))
                 {
                     PlayerSettings.SetVirtualRealitySDKs(TargetGroup, vrSDKs);
                 }
             }
             if (TargetGroup == BuildTargetGroup.WSA)
             {
                 EditorUserBuildSettings.wsaBuildAndRunDeployTarget = WSABuildAndRunDeployTarget.LocalMachine;
                 EditorUserBuildSettings.wsaUWPBuildType = WSAUWPBuildType.D3D;
                 PlayerSettings.WSA.inputSource = PlayerSettings.WSAInputSource.IndependentInputSource;
                 WSASubtarget sub;
                 if (Enum.TryParse(wsaSubtarget, out sub))
                 {
                     EditorUserBuildSettings.wsaSubtarget = sub;
                     PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.SpatialPerception, sub == WSASubtarget.HoloLens);
                 }
             }
             else if (TargetGroup == BuildTargetGroup.Android)
             {
                 AndroidSdkVersions sdkVersion;
                 if (Enum.TryParse(androidSdkVersion, out sdkVersion))
                 {
                     PlayerSettings.Android.minSdkVersion = (AndroidSdkVersions)Math.Max(
                         (int)PlayerSettings.Android.minSdkVersion,
                         (int)sdkVersion);
                 }
             }
             else if (TargetGroup == BuildTargetGroup.iOS)
             {
                 Version v;
                 if (Version.TryParse(iOSVersion, out v)
                     && PlayerSettingsExt.iOS.TargetOSVersion < v)
                 {
                     PlayerSettingsExt.iOS.TargetOSVersion = v;
                 }
             }
         }
References Juniper.ConfigurationManagement.AbstractPackage.Activate(), Juniper.ConfigurationManagement.RawPackage.Activate(), Juniper.ConfigurationManagement.PlatformConfiguration.androidSdkVersion, Juniper.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages, Juniper.ConfigurationManagement.PlatformConfiguration.iOSVersion, Juniper.ConfigurationManagement.PlatformConfiguration.RawPackages, Juniper.AudioSettingsExt.SetAmbisonicDecoderPluginName(), Juniper.ConfigurationManagement.PlatformConfiguration.spatializer, Juniper.ConfigurationManagement.PlatformConfiguration.TargetGroup, Juniper.PlayerSettingsExt.iOS.TargetOSVersion, Juniper.ConfigurationManagement.PlatformConfiguration.wsaSubtarget, and Juniper.ConfigurationManagement.PlatformConfiguration.XRPlatforms.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareProject().
Deactivate()
internal void Juniper.ConfigurationManagement.PlatformConfiguration.Deactivate (PlatformConfiguration nextConfiguration) inline private
Definition at line 318 of file PlatformConfiguration.cs.
         {
             AudioSettings.SetSpatializerPluginName(null);
             AudioSettingsExt.SetAmbisonicDecoderPluginName(null);
             PlayerSettings.virtualRealitySupported = false;
             PlayerSettings.Android.androidTVCompatibility = false;
 #if UNITY_2018_2_OR_NEWER
             PlayerSettings.Android.ARCoreEnabled = false;
 #endif
             PlayerSettingsExt.iOS.RequiresARKitSupport = false;
             PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
             if (nextConfiguration.TargetGroup != TargetGroup)
             {
                 PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
             }
         }
References Juniper.PlayerSettingsExt.iOS.RequiresARKitSupport, Juniper.AudioSettingsExt.SetAmbisonicDecoderPluginName(), and Juniper.ConfigurationManagement.PlatformConfiguration.TargetGroup.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform().
InstallRawPackages()
void Juniper.ConfigurationManagement.PlatformConfiguration.InstallRawPackages (IProgress prog = null) inline
Definition at line 193 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(RawPackages, prog, (pkg, p) => pkg.Install(p));
         }
References Juniper.ConfigurationManagement.RawPackage.Install(), and Juniper.ConfigurationManagement.PlatformConfiguration.RawPackages.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
InstallUnityPackages()
void Juniper.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages (IProgress prog = null) inline
Definition at line 164 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(ExcludedUnityPackages, progs[0], (pkg, p) =>
             {
 #if UNITY_2018_2_OR_NEWER
                 pkg.Uninstall(p);
 #else
                 if (!pkg.Name.StartsWith("com.unity.modules."))
                 {
                     pkg.Install(p);
                 }
 #endif
             });
             Platforms.ForEachPackage(IncludedUnityPackages, progs[1], (pkg, p) =>
             {
 #if UNITY_2018_2_OR_NEWER
                 pkg.Install(p);
 #else
                 if (!pkg.Name.StartsWith("com.unity.modules."))
                 {
                     pkg.Install(p);
                 }
 #endif
             });
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.ExcludedUnityPackages, Juniper.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages, Juniper.ConfigurationManagement.UnityPackage.Install(), and Juniper.ConfigurationManagement.UnityPackage.Uninstall().
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
SwitchTarget()
void Juniper.ConfigurationManagement.PlatformConfiguration.SwitchTarget () inline
Definition at line 153 of file PlatformConfiguration.cs.
         {
             Debug.Log($"Switching build target from {EditorUserBuildSettings.activeBuildTarget} to {BuildTarget}.");
             EditorUserBuildSettings.SwitchActiveBuildTargetAsync(TargetGroup, BuildTarget);
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.BuildTarget, Juniper.XR.Debug, and Juniper.ConfigurationManagement.PlatformConfiguration.TargetGroup.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
UninstallRawPackages()
void Juniper.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages (IProgress prog = null) inline
Definition at line 273 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(UninstallableRawPackages, prog, (pkg, p) => pkg.Uninstall(p));
         }
References Juniper.ConfigurationManagement.RawPackage.Uninstall(), and Juniper.ConfigurationManagement.PlatformConfiguration.UninstallableRawPackages.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
UninstallUnityPackages()
void Juniper.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages (IProgress prog = null) inline
Definition at line 278 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(UninstallableUnityPackages, prog, (pkg, p) => pkg.Uninstall(p));
         }
References Juniper.ConfigurationManagement.UnityPackage.Uninstall(), and Juniper.ConfigurationManagement.PlatformConfiguration.UninstallableUnityPackages.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Member Data Documentation
androidSdkVersion
string Juniper.ConfigurationManagement.PlatformConfiguration.androidSdkVersion
Definition at line 22 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
buildTarget
string Juniper.ConfigurationManagement.PlatformConfiguration.buildTarget
Definition at line 20 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
CompilerDefine
string Juniper.ConfigurationManagement.PlatformConfiguration.CompilerDefine
Definition at line 19 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
iOSVersion
string Juniper.ConfigurationManagement.PlatformConfiguration.iOSVersion
Definition at line 23 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
Name
string Juniper.ConfigurationManagement.PlatformConfiguration.Name
Definition at line 18 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
packages
string [] Juniper.ConfigurationManagement.PlatformConfiguration.packages
Definition at line 26 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
spatializer
string Juniper.ConfigurationManagement.PlatformConfiguration.spatializer
Definition at line 21 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
vrSystems
string [] Juniper.ConfigurationManagement.PlatformConfiguration.vrSystems
Definition at line 25 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration(), and Juniper.ConfigurationManagement.Platforms.Platforms().
wsaSubtarget
string Juniper.ConfigurationManagement.PlatformConfiguration.wsaSubtarget
Definition at line 24 of file PlatformConfiguration.cs.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
Property Documentation
BuildTarget
BuildTarget Juniper.ConfigurationManagement.PlatformConfiguration.BuildTarget get
Definition at line 43 of file PlatformConfiguration.cs.
         {
             get
             {
                 var localBuildTarget = buildTarget;
                 if (localBuildTarget == "Standalone")
                 {
 #if UNITY_EDITOR_WIN
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows);
                     }
 #elif UNITY_EDITOR_OSX
                     localBuildTarget = nameof(BuildTarget.StandaloneOSX);
 #else
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux);
                     }
 #endif
                 }
                 try
                 {
                     return (BuildTarget)Enum.Parse(typeof(BuildTarget), localBuildTarget);
                 }
                 catch
                 {
                     return BuildTarget.NoTarget;
                 }
             }
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.SwitchTarget().
CompilerDefines
List<string> Juniper.ConfigurationManagement.PlatformConfiguration.CompilerDefines get
Definition at line 284 of file PlatformConfiguration.cs.
         {
             get
             {
                 var defines = Platforms.GetCompilerDefines(IncludedUnityPackages, RawPackages);
                 if (!string.IsNullOrEmpty(CompilerDefine))
                 {
                     defines.MaybeAdd(CompilerDefine);
                 }
                 if (TargetGroup == BuildTargetGroup.Android)
                 {
                     for (var i = (int)PlayerSettings.Android.minSdkVersion; i > 0; --i)
                     {
                         if (Enum.IsDefined(typeof(AndroidSdkVersions), i))
{
                             defines.MaybeAdd("ANDROID_API_" + i);
                             defines.MaybeAdd("ANDROID_API_" + i + "_OR_GREATER");
                         }
                     }
                 }
                 else if (TargetGroup == BuildTargetGroup.iOS)
                 {
                     for (var i = PlayerSettingsExt.iOS.TargetOSVersion.Major; i > 0; --i)
                     {
                         defines.MaybeAdd("IOS_VERSION_" + i);
                         defines.MaybeAdd("IOS_VERSION_" + i + "_OR_GREATER");
                     }
                 }
                 return defines;
             }
         }
ExcludedUnityPackages
UnityPackage [] Juniper.ConfigurationManagement.PlatformConfiguration.ExcludedUnityPackages get set
Definition at line 137 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages().
IncludedUnityPackages
UnityPackage [] Juniper.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages get set
Definition at line 131 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages().
IsSupported
bool Juniper.ConfigurationManagement.PlatformConfiguration.IsSupported get
Definition at line 94 of file PlatformConfiguration.cs.
         {
             get
             {
 #if UNITY_2018_1_OR_NEWER
                 return BuildPipeline.IsBuildTargetSupported(TargetGroup, BuildTarget);
 #else
                 var moduleManager = System.Type.GetType("UnityEditor.Modules.ModuleManager,UnityEditor.dll");
                 var isPlatformSupportLoaded = moduleManager.GetMethod(
                     "IsPlatformSupportLoaded",
                     System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
                 var getTargetStringFromBuildTarget = moduleManager.GetMethod(
                     "GetTargetStringFromBuildTarget",
                     System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
                 var targetString = (string)getTargetStringFromBuildTarget.Invoke(null, new object[] {BuildTarget.tvOS});
                 return (bool)isPlatformSupportLoaded.Invoke(null,new object[] {targetString});
 #endif
             }
         }
RawPackages
RawPackage [] Juniper.ConfigurationManagement.PlatformConfiguration.RawPackages get set
Definition at line 149 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.InstallRawPackages().
TargetGroup
BuildTargetGroup Juniper.ConfigurationManagement.PlatformConfiguration.TargetGroup get
Definition at line 85 of file PlatformConfiguration.cs.
         {
             get
             {
                 return BuildPipeline.GetBuildTargetGroup(BuildTarget);
             }
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.ConfigurationManagement.PlatformConfiguration.Deactivate(), and Juniper.ConfigurationManagement.PlatformConfiguration.SwitchTarget().
TargetSwitchNeeded
bool Juniper.ConfigurationManagement.PlatformConfiguration.TargetSwitchNeeded get
Definition at line 160 of file PlatformConfiguration.cs.
         {
             get { return BuildTarget != EditorUserBuildSettings.activeBuildTarget; }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
UninstallableRawPackages
RawPackage [] Juniper.ConfigurationManagement.PlatformConfiguration.UninstallableRawPackages get set
Definition at line 143 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages().
UninstallableUnityPackages
UnityPackage [] Juniper.ConfigurationManagement.PlatformConfiguration.UninstallableUnityPackages get set
Definition at line 125 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages().
XRPlatforms
IEnumerable<UnityXRPlatforms> Juniper.ConfigurationManagement.PlatformConfiguration.XRPlatforms get
Definition at line 115 of file PlatformConfiguration.cs.
         {
             get
             {
                 return from sys in vrSystems
                        select (UnityXRPlatforms)Enum.Parse(typeof(UnityXRPlatforms), sys);
             }
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Editor/ConfigurationManagement/PlatformConfiguration.cs