Juniper: BitMiracle.LibJpeg.BitStream Class Reference
BitMiracle.LibJpeg.BitStream Class Reference
Public Member Functions
BitStream ()
BitStream (byte[] buffer)
void Dispose ()
int Size ()
virtual int Read (int bitsCount)
int Write (int bitStorage, int bitCount)
void Seek (int pos, SeekOrigin mode)
int Tell ()
Public Attributes
Stream UnderlyingStream => m_stream
Protected Member Functions
virtual void Dispose (bool disposing)
Private Member Functions
int BitsAllocated ()
bool WriteBit (byte bit)
void SeekSet (int pos)
void SeekCurrent (int pos)
Private Attributes
bool m_alreadyDisposed
const int bitsInByte = 8
Stream m_stream
int m_positionInByte
int m_size
Detailed Description
Definition at line 6 of file BitStream.cs.
Constructor & Destructor Documentation
BitStream() [1/2]
BitMiracle.LibJpeg.BitStream.BitStream () inline
Definition at line 16 of file BitStream.cs.
         {
             m_stream = new MemoryStream();
         }
References BitMiracle.LibJpeg.BitStream.m_stream.
BitStream() [2/2]
BitMiracle.LibJpeg.BitStream.BitStream (byte [] buffer) inline
Definition at line 21 of file BitStream.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             m_stream = new MemoryStream(buffer);
             m_size = BitsAllocated();
         }
References BitMiracle.LibJpeg.BitStream.BitsAllocated(), BitMiracle.LibJpeg.BitStream.m_size, and BitMiracle.LibJpeg.BitStream.m_stream.
Member Function Documentation
BitsAllocated()
int BitMiracle.LibJpeg.BitStream.BitsAllocated () inline private
Definition at line 158 of file BitStream.cs.
         {
             return (int)m_stream.Length * bitsInByte;
         }
References BitMiracle.LibJpeg.BitStream.bitsInByte, and BitMiracle.LibJpeg.BitStream.m_stream.
Referenced by BitMiracle.LibJpeg.BitStream.BitStream(), BitMiracle.LibJpeg.BitStream.Read(), and BitMiracle.LibJpeg.BitStream.SeekCurrent().
Dispose() [1/2]
void BitMiracle.LibJpeg.BitStream.Dispose () inline
Definition at line 32 of file BitStream.cs.
         {
             Dispose(true);
             GC.SuppressFinalize(this);
         }
Dispose() [2/2]
virtual void BitMiracle.LibJpeg.BitStream.Dispose (bool disposing) inline protected virtual
Definition at line 38 of file BitStream.cs.
         {
             if (!m_alreadyDisposed)
             {
                 if (disposing)
                 {
                     m_stream?.Dispose();
                 }
                 m_stream = null;
                 m_alreadyDisposed = true;
             }
         }
References BitMiracle.LibJpeg.BitStream.m_alreadyDisposed, and BitMiracle.LibJpeg.BitStream.m_stream.
Read()
virtual int BitMiracle.LibJpeg.BitStream.Read (int bitsCount) inline virtual
Definition at line 59 of file BitStream.cs.
         {
             if (Tell() + bitsCount > BitsAllocated())
             {
                 throw new ArgumentOutOfRangeException(nameof(bitsCount));
             }
             //Codes are packed into a continuous bit stream, high-order bit first.
             //This stream is then divided into 8-bit bytes, high-order bit first.
             //Thus, codes can straddle byte boundaries arbitrarily. After the EOD marker (code value 257),
             //any leftover bits in the final byte are set to 0.
             if (bitsCount < 0 || bitsCount > 32)
             {
                 throw new ArgumentOutOfRangeException(nameof(bitsCount));
             }
             if (bitsCount == 0)
             {
                 return 0;
             }
             var bitsRead = 0;
             var result = 0;
             var bt = new byte[1];
             while (bitsRead == 0 || (bitsRead - m_positionInByte < bitsCount))
             {
                 m_stream.Read(bt, 0, 1);
                 result <<= bitsInByte;
                 result += bt[0];
                 bitsRead += 8;
             }
             m_positionInByte = (m_positionInByte + bitsCount) % 8;
             if (m_positionInByte != 0)
             {
                 result >>= (bitsInByte - m_positionInByte);
                 m_stream.Seek(-1, SeekOrigin.Current);
             }
             if (bitsCount < 32)
             {
                 var mask = ((1 << bitsCount) - 1);
                 result &= mask;
             }
             return result;
         }
References BitMiracle.LibJpeg.BitStream.BitsAllocated(), BitMiracle.LibJpeg.BitStream.bitsInByte, BitMiracle.LibJpeg.BitStream.m_positionInByte, BitMiracle.LibJpeg.BitStream.m_stream, and BitMiracle.LibJpeg.BitStream.Tell().
Referenced by BitMiracle.LibJpeg.Sample.Sample().
Seek()
void BitMiracle.LibJpeg.BitStream.Seek (int pos, SeekOrigin mode) inline
Definition at line 135 of file BitStream.cs.
         {
             switch (mode)
             {
                 case SeekOrigin.Begin:
                 SeekSet(pos);
                 break;
                 case SeekOrigin.Current:
                 SeekCurrent(pos);
                 break;
                 case SeekOrigin.End:
                 SeekSet(Size() + pos);
                 break;
             }
         }
References BitMiracle.LibJpeg.BitStream.SeekCurrent(), BitMiracle.LibJpeg.BitStream.SeekSet(), and BitMiracle.LibJpeg.BitStream.Size().
Referenced by BitMiracle.LibJpeg.BitStream.WriteBit().
SeekCurrent()
void BitMiracle.LibJpeg.BitStream.SeekCurrent (int pos) inline private
Definition at line 209 of file BitStream.cs.
         {
             var result = Tell() + pos;
             if (result < 0 || result > BitsAllocated())
             {
                 throw new ArgumentOutOfRangeException(nameof(pos));
             }
             SeekSet(result);
         }
References BitMiracle.LibJpeg.BitStream.BitsAllocated(), BitMiracle.LibJpeg.BitStream.SeekSet(), and BitMiracle.LibJpeg.BitStream.Tell().
Referenced by BitMiracle.LibJpeg.BitStream.Seek().
SeekSet()
void BitMiracle.LibJpeg.BitStream.SeekSet (int pos) inline private
Definition at line 196 of file BitStream.cs.
         {
             if (pos < 0)
             {
                 throw new ArgumentOutOfRangeException(nameof(pos));
             }
             var byteDisplacement = pos / bitsInByte;
             m_stream.Seek(byteDisplacement, SeekOrigin.Begin);
             m_positionInByte = pos - (byteDisplacement * bitsInByte);
         }
References BitMiracle.LibJpeg.BitStream.bitsInByte, BitMiracle.LibJpeg.BitStream.m_positionInByte, and BitMiracle.LibJpeg.BitStream.m_stream.
Referenced by BitMiracle.LibJpeg.BitStream.Seek(), and BitMiracle.LibJpeg.BitStream.SeekCurrent().
Size()
int BitMiracle.LibJpeg.BitStream.Size () inline
Definition at line 52 of file BitStream.cs.
         {
             return m_size;
         }
References BitMiracle.LibJpeg.BitStream.m_size.
Referenced by BitMiracle.LibJpeg.BitStream.Seek().
Tell()
int BitMiracle.LibJpeg.BitStream.Tell () inline
Definition at line 153 of file BitStream.cs.
         {
             return ((int)m_stream.Position * bitsInByte) + m_positionInByte;
         }
References BitMiracle.LibJpeg.BitStream.bitsInByte, BitMiracle.LibJpeg.BitStream.m_positionInByte, and BitMiracle.LibJpeg.BitStream.m_stream.
Referenced by BitMiracle.LibJpeg.BitStream.Read(), BitMiracle.LibJpeg.BitStream.SeekCurrent(), and BitMiracle.LibJpeg.BitStream.WriteBit().
Write()
int BitMiracle.LibJpeg.BitStream.Write (int bitStorage, int bitCount) inline
Definition at line 110 of file BitStream.cs.
         {
             if (bitCount == 0)
             {
                 return 0;
             }
             const int maxBitsInStorage = sizeof(int) * bitsInByte;
             if (bitCount > maxBitsInStorage)
             {
                 throw new ArgumentOutOfRangeException(nameof(bitCount));
             }
             for (var i = 0; i < bitCount; ++i)
             {
                 var bit = (byte)((bitStorage << (maxBitsInStorage - (bitCount - i))) >> (maxBitsInStorage - 1));
                 if (!WriteBit(bit))
                 {
                     return i;
                 }
             }
             return bitCount;
         }
References BitMiracle.LibJpeg.BitStream.bitsInByte, and BitMiracle.LibJpeg.BitStream.WriteBit().
WriteBit()
bool BitMiracle.LibJpeg.BitStream.WriteBit (byte bit) inline private
Definition at line 163 of file BitStream.cs.
         {
             if (m_stream.Position == m_stream.Length)
             {
                 byte[] bt = { (byte)(bit << (bitsInByte - 1)) };
                 m_stream.Write(bt, 0, 1);
                 m_stream.Seek(-1, SeekOrigin.Current);
             }
             else
             {
                 byte[] bt = { 0 };
                 m_stream.Read(bt, 0, 1);
                 m_stream.Seek(-1, SeekOrigin.Current);
                 var shift = (bitsInByte - m_positionInByte - 1) % bitsInByte;
                 var maskByte = (byte)(bit << shift);
                 bt[0] |= maskByte;
                 m_stream.Write(bt, 0, 1);
                 m_stream.Seek(-1, SeekOrigin.Current);
             }
             Seek(1, SeekOrigin.Current);
             var currentPosition = Tell();
             if (currentPosition > m_size)
             {
                 m_size = currentPosition;
             }
             return true;
         }
References BitMiracle.LibJpeg.BitStream.bitsInByte, BitMiracle.LibJpeg.BitStream.m_positionInByte, BitMiracle.LibJpeg.BitStream.m_size, BitMiracle.LibJpeg.BitStream.m_stream, BitMiracle.LibJpeg.BitStream.Seek(), and BitMiracle.LibJpeg.BitStream.Tell().
Referenced by BitMiracle.LibJpeg.BitStream.Write().
Member Data Documentation
bitsInByte
const int BitMiracle.LibJpeg.BitStream.bitsInByte = 8 private
Definition at line 10 of file BitStream.cs.
Referenced by BitMiracle.LibJpeg.BitStream.BitsAllocated(), BitMiracle.LibJpeg.BitStream.Read(), BitMiracle.LibJpeg.BitStream.SeekSet(), BitMiracle.LibJpeg.BitStream.Tell(), BitMiracle.LibJpeg.BitStream.Write(), and BitMiracle.LibJpeg.BitStream.WriteBit().
m_alreadyDisposed
bool BitMiracle.LibJpeg.BitStream.m_alreadyDisposed private
Definition at line 8 of file BitStream.cs.
Referenced by BitMiracle.LibJpeg.BitStream.Dispose().
m_positionInByte
int BitMiracle.LibJpeg.BitStream.m_positionInByte private
Definition at line 12 of file BitStream.cs.
Referenced by BitMiracle.LibJpeg.BitStream.Read(), BitMiracle.LibJpeg.BitStream.SeekSet(), BitMiracle.LibJpeg.BitStream.Tell(), and BitMiracle.LibJpeg.BitStream.WriteBit().
m_size
int BitMiracle.LibJpeg.BitStream.m_size private
Definition at line 14 of file BitStream.cs.
Referenced by BitMiracle.LibJpeg.BitStream.BitStream(), BitMiracle.LibJpeg.BitStream.Size(), and BitMiracle.LibJpeg.BitStream.WriteBit().
m_stream
Stream BitMiracle.LibJpeg.BitStream.m_stream private
Definition at line 11 of file BitStream.cs.
Referenced by BitMiracle.LibJpeg.BitStream.BitsAllocated(), BitMiracle.LibJpeg.BitStream.BitStream(), BitMiracle.LibJpeg.BitStream.Dispose(), BitMiracle.LibJpeg.BitStream.Read(), BitMiracle.LibJpeg.BitStream.SeekSet(), BitMiracle.LibJpeg.BitStream.Tell(), and BitMiracle.LibJpeg.BitStream.WriteBit().
UnderlyingStream
Stream BitMiracle.LibJpeg.BitStream.UnderlyingStream => m_stream
Definition at line 57 of file BitStream.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/BitStream.cs