Juniper: Juniper.Unity.Statistics.KalmanMotionFilter Class Reference
Juniper.Unity.Statistics.KalmanMotionFilter Class Reference
Public Member Functions
override void UpdateState (Vector3 point)
Public Attributes
uint componentCount = 2
float measurementNoise = 10
uint processNoiseScale = 100
float processNoiseExponent = 1
Properties
uint ComponentCount [get, set]
uint Dimension [get, set]
DiscreteKalmanFilter< Vector3[], Vector3 > Kalman [get, set]
override Vector3? PredictedPosition [get]
override Vector3??? Position [get]
Private Member Functions
uint X (uint i)
uint Y (uint i)
uint Z (uint i)
Vector3 [] FromArray (double[] arr)
double [] ToArray (Vector3[] vecs)
double [,] GetProcessNoise (Func< uint, double > getProcNoiseForVec)
double [,] MakePositionMeasurementMatrix ()
double [,] MakeTransitionMatrix ()
Private Attributes
float mNoise
uint procNoiseK
float procNoiseE
const uint VectorSize = 3
Vector3? lastPoint
Detailed Description
Definition at line 14 of file KalmanMotionFilter.cs.
Member Function Documentation
FromArray()
Vector3 [] Juniper.Unity.Statistics.KalmanMotionFilter.FromArray (double [] arr) inline private
Definition at line 143 of file KalmanMotionFilter.cs.
         {
             var vecs = new Vector3[ComponentCount];
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 vecs[i].x = (float)arr[X(i)];
                 vecs[i].y = (float)arr[Y(i)];
                 vecs[i].z = (float)arr[Z(i)];
             }
             return vecs;
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount, Juniper.Unity.Statistics.KalmanMotionFilter.X(), Juniper.Unity.Statistics.KalmanMotionFilter.Y(), and Juniper.Unity.Statistics.KalmanMotionFilter.Z().
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
GetProcessNoise()
double [,] Juniper.Unity.Statistics.KalmanMotionFilter.GetProcessNoise (Func< uint, double > getProcNoiseForVec) inline private
Definition at line 167 of file KalmanMotionFilter.cs.
         {
             var vec = new double[Dimension];
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 for (uint x = 0; x < VectorSize; ++x)
                 {
                     vec[i * VectorSize + x] = getProcNoiseForVec(i);
                 }
             }
             return Matrix.Diagonal((int)Dimension, vec);
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount, Juniper.Unity.Statistics.KalmanMotionFilter.Dimension, and Juniper.Unity.Statistics.KalmanMotionFilter.VectorSize.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
MakePositionMeasurementMatrix()
double [,] Juniper.Unity.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix () inline private
Definition at line 180 of file KalmanMotionFilter.cs.
         {
             var m = new double[VectorSize, ComponentCount * VectorSize];
             for (uint i = 0; i < VectorSize; ++i)
             {
                 m[i, i * ComponentCount] = 1;
             }
             return m;
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount, and Juniper.Unity.Statistics.KalmanMotionFilter.VectorSize.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
MakeTransitionMatrix()
double [,] Juniper.Unity.Statistics.KalmanMotionFilter.MakeTransitionMatrix () inline private
Definition at line 190 of file KalmanMotionFilter.cs.
         {
             var t = Time.fixedDeltaTime;
             var parts = new double[ComponentCount];
             double accum = 1;
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 parts[i] = accum * Mathf.Pow(t, i);
                 accum /= i + 1;
             }
             var m = new double[Dimension, Dimension];
             for (uint y = 0; y < Dimension; ++y)
             {
                 var chunkRow = y % ComponentCount;
                 for (uint x = 0; x < ComponentCount - chunkRow; ++x)
                 {
                     m[y, y + x] = parts[x];
                 }
             }
             return m;
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount, and Juniper.Unity.Statistics.KalmanMotionFilter.Dimension.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
ToArray()
double [] Juniper.Unity.Statistics.KalmanMotionFilter.ToArray (Vector3 [] vecs) inline private
Definition at line 155 of file KalmanMotionFilter.cs.
         {
             var arr = new double[Dimension];
             for (uint i = 0; i < vecs.Length; ++i)
             {
                 arr[X(i)] = vecs[i].x;
                 arr[Y(i)] = vecs[i].y;
                 arr[Z(i)] = vecs[i].z;
             }
             return arr;
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.Dimension, Juniper.Unity.Statistics.KalmanMotionFilter.X(), Juniper.Unity.Statistics.KalmanMotionFilter.Y(), and Juniper.Unity.Statistics.KalmanMotionFilter.Z().
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
UpdateState()
override void Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState (Vector3 point) inline virtual
Implements Juniper.Unity.Statistics.AbstractMotionFilter.
Definition at line 95 of file KalmanMotionFilter.cs.
         {
             componentCount = Math.Max(1, componentCount);
             if (Kalman != null
                 && componentCount == ComponentCount
                 && Mathf.Approximately(measurementNoise, mNoise)
                 && processNoiseScale == procNoiseK
                 && Mathf.Approximately(processNoiseExponent, procNoiseE))
             {
                 Kalman.Correct(point);
             }
             else
             {
                 ComponentCount = componentCount;
                 Dimension = VectorSize * ComponentCount;
                 mNoise = measurementNoise;
                 procNoiseK = processNoiseScale;
                 procNoiseE = processNoiseExponent;
                 var initialState = new Vector3[ComponentCount];
                 initialState[0] = lastPoint ?? point;
                 Kalman = new DiscreteKalmanFilter<Vector3[], Vector3>(
                     initialState,
                     GetProcessNoise(_ => processNoiseScale),
                     (int)VectorSize,
                     0,
                     ToArray,
                     FromArray,
                     x => new double[] { x.x, x.y, x.z })
                 {
                     ProcessNoise = GetProcessNoise(i =>
                         Mathf.Pow(processNoiseScale, processNoiseExponent * (i + 1))),
                     MeasurementMatrix = MakePositionMeasurementMatrix(),
                     TransitionMatrix = MakeTransitionMatrix(),
                     MeasurementNoise = Matrix.Diagonal((int)VectorSize, (double)measurementNoise)
                 };
                 if (lastPoint != null)
                 {
                     Kalman.Correct(point);
                 }
                 Kalman.Predict();
                 lastPoint = point;
             }
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.componentCount, Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount, Juniper.Unity.Statistics.KalmanMotionFilter.Dimension, Juniper.Unity.Statistics.KalmanMotionFilter.FromArray(), Juniper.Unity.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Unity.Statistics.KalmanMotionFilter.Kalman, Juniper.Unity.Statistics.KalmanMotionFilter.lastPoint, Juniper.Unity.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix(), Juniper.Unity.Statistics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Unity.Statistics.KalmanMotionFilter.measurementNoise, Juniper.Unity.Statistics.KalmanMotionFilter.mNoise, Juniper.Unity.Statistics.KalmanMotionFilter.processNoiseExponent, Juniper.Unity.Statistics.KalmanMotionFilter.processNoiseScale, Juniper.Unity.Statistics.KalmanMotionFilter.procNoiseE, Juniper.Unity.Statistics.KalmanMotionFilter.procNoiseK, Juniper.Unity.Statistics.KalmanMotionFilter.ToArray(), and Juniper.Unity.Statistics.KalmanMotionFilter.VectorSize.
X()
uint Juniper.Unity.Statistics.KalmanMotionFilter.X (uint i) inline private
Definition at line 46 of file KalmanMotionFilter.cs.
         {
             return i;
         }
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.FromArray(), and Juniper.Unity.Statistics.KalmanMotionFilter.ToArray().
Y()
uint Juniper.Unity.Statistics.KalmanMotionFilter.Y (uint i) inline private
Definition at line 51 of file KalmanMotionFilter.cs.
         {
             return i + ComponentCount;
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.FromArray(), and Juniper.Unity.Statistics.KalmanMotionFilter.ToArray().
Z()
uint Juniper.Unity.Statistics.KalmanMotionFilter.Z (uint i) inline private
Definition at line 56 of file KalmanMotionFilter.cs.
         {
             return i + (2 * ComponentCount);
         }
References Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.FromArray(), and Juniper.Unity.Statistics.KalmanMotionFilter.ToArray().
Member Data Documentation
componentCount
uint Juniper.Unity.Statistics.KalmanMotionFilter.componentCount = 2
Definition at line 16 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
lastPoint
Vector3? Juniper.Unity.Statistics.KalmanMotionFilter.lastPoint private
Definition at line 93 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
measurementNoise
float Juniper.Unity.Statistics.KalmanMotionFilter.measurementNoise = 10
Definition at line 23 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
mNoise
float Juniper.Unity.Statistics.KalmanMotionFilter.mNoise private
Definition at line 24 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
processNoiseExponent
float Juniper.Unity.Statistics.KalmanMotionFilter.processNoiseExponent = 1
Definition at line 30 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
processNoiseScale
uint Juniper.Unity.Statistics.KalmanMotionFilter.processNoiseScale = 100
Definition at line 26 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
procNoiseE
float Juniper.Unity.Statistics.KalmanMotionFilter.procNoiseE private
Definition at line 32 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
procNoiseK
uint Juniper.Unity.Statistics.KalmanMotionFilter.procNoiseK private
Definition at line 27 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
VectorSize
const uint Juniper.Unity.Statistics.KalmanMotionFilter.VectorSize = 3 private
Definition at line 34 of file KalmanMotionFilter.cs.
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Unity.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix(), and Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
Property Documentation
ComponentCount
uint Juniper.Unity.Statistics.KalmanMotionFilter.ComponentCount get set private
Definition at line 19 of file KalmanMotionFilter.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.FromArray(), Juniper.Unity.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Unity.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix(), Juniper.Unity.Statistics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState(), Juniper.Unity.Statistics.KalmanMotionFilter.Y(), and Juniper.Unity.Statistics.KalmanMotionFilter.Z().
Dimension
uint Juniper.Unity.Statistics.KalmanMotionFilter.Dimension get set private
Definition at line 37 of file KalmanMotionFilter.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Unity.Statistics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Unity.Statistics.KalmanMotionFilter.ToArray(), and Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
Kalman
DiscreteKalmanFilter<Vector3[], Vector3> Juniper.Unity.Statistics.KalmanMotionFilter.Kalman get set private
Definition at line 42 of file KalmanMotionFilter.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Statistics.KalmanMotionFilter.UpdateState().
Position
override Vector3??? Juniper.Unity.Statistics.KalmanMotionFilter.Position get
Definition at line 71 of file KalmanMotionFilter.cs.
         {
             get
             {
                 return Kalman?.State[0] ?? Vector3.zero;
             }
         }
PredictedPosition
override Vector3? Juniper.Unity.Statistics.KalmanMotionFilter.PredictedPosition get
Definition at line 62 of file KalmanMotionFilter.cs.
         {
             get
             {
                 Kalman?.Predict();
                 return Position;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Statistics/KalmanMotionFilter.cs