Juniper: Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType > Class Template Reference
Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType > Class Template Reference abstract
Public Member Functions
void AddButton (ButtonIDType buttonID, InputEventButton buttonValue)
Add a new button mapping to the pointer.
void RemoveButton (ButtonIDType buttonID)
Remove a button mapping from the pointer.
virtual void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
void Start ()
virtual void Install (bool reset)
Install, with or without a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void OnProbeFound ()
Vector2 ScreenFromWorld (Vector3 worldPoint)
Vector2 ScreenFromViewport (Vector2 viewportPoint)
Vector2 ViewportFromWorld (Vector3 worldPoint)
Vector2 ViewportFromScreen (Vector2 screenPoint)
Vector3 WorldFromScreen (Vector2 screenPoint)
Vector3 WorldFromViewport (Vector2 viewportPoint)
virtual void Update ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
virtual void PlayInteraction (Interaction action)
virtual void Process (PointerEventData evtData, float pixelDragThresholdSquared)
virtual bool IsButtonPressed (InputButton button)
virtual bool IsButtonUp (InputButton button)
virtual bool IsButtonDown (InputButton button)
abstract bool IsButtonPressed (ButtonIDType button)
Implementers should return true while the button is depressed.
abstract bool IsButtonDown (ButtonIDType button)
Implementers should return true when a button is first depressed.
abstract bool IsButtonUp (ButtonIDType button)
Implementers should return true when the button is first released.
bool IsButtonDown (PointerEventData.InputButton button)
bool IsButtonPressed (PointerEventData.InputButton button)
bool IsButtonUp (PointerEventData.InputButton button)
Public Attributes
bool Connected
Material LaserPointerMaterial
bool showProbe = true
AbstractMotionFilter motionFilter
Protected Member Functions
PointerEventData Clone (int pointerDataID, PointerEventData evtData)
virtual IEventSystemHandler ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared)
virtual void InternalUpdate ()
abstract AbstractHapticDevice MakeHapticsDevice ()
Protected Attributes
readonly ButtonMapper< ButtonIDType > nativeButtons = new ButtonMapper<ButtonIDType>()
Vector3 pointerOffset
IProbe probe
The cursor probe that shows the physical location of the current selection.
AbstractUnifiedInputModule eventManager
Avatar stage
Static Protected Attributes
static readonly Vector2 VIEWPORT_MIDPOINT
static readonly ConfigType PointerConfig
Properties
Type ButtonType [get]
int PointerDataID [get]
float MinimumPointerDistance [get]
The minimum distance from the camera at which to place the pointer.
float MaximumPointerDistance [get]
int Layer [get, set]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
abstract bool IsConnected [get]
bool IsEnabled [get]
bool IsDisabled [get]
Returns true when the device is supposed to be disabled.
PhysicsRaycaster? Raycaster [get]
virtual bool AnyButtonPressed [get]
string ProbeName [get]
Vector3 Origin [get]
Vector3 LastOrigin [get, private set]
Vector3 OriginDelta [get]
abstract Vector3 WorldPoint [get]
Vector3 LastWorldPoint [get, private set]
Vector3 WorldDelta [get]
Vector3??? SmoothedWorldPoint [get]
The target at and through which the pointer rays fire.
Vector3 LastSmoothedWorldPoint [get, private set]
Vector3 SmoothedWorldPointDelta [get]
Vector3 Direction [get]
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
Vector3 LastDirection [get]
Vector2 ScreenPoint [get]
Vector2 LastScreenPoint [get]
Vector2 ScreenDelta [get]
Vector2 ViewportPoint [get]
Vector2 LastViewportPoint [get]
Vector2 ViewportDelta [get]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
IInputModule InputModule [get]
virtual bool IsDragging [get]
AbstractHapticDevice Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
Transform transform [get]
bool isActiveAndEnabled [get]
Private Member Functions
void TestEnterExit (PointerEventData evtData)
Private Attributes
AbstractMotionFilter lastMotionFilter
float finishTime
Interaction lastAction
Detailed Description
Type Constraints
ButtonIDType : struct
ConfigType : AbstractPointerConfiguration<ButtonIDType>
ConfigType : new()
Definition at line 15 of file AbstractPointerDevice.cs.
Member Function Documentation
AddButton()
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AddButton (ButtonIDType buttonID, InputEventButton buttonValue) inline
Add a new button mapping to the pointer.
Parameters
buttonID
buttonValue
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
Definition at line 39 of file AbstractPointerDevice.cs.
         {
             nativeButtons.AddButton(gameObject, buttonID, buttonValue);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Awake()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake () inline virtual
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 157 of file AbstractPointerDevice.cs.
         {
             Install(false);
             eventManager = ComponentExt.FindAny<UnifiedInputModule>();
             stage = ComponentExt.FindAny<Avatar>();
             pointerOffset = MinimumPointerDistance * Vector3.forward;
             Haptics = MakeHapticsDevice();
             nativeButtons.ButtonDownNeeded += IsButtonDown;
             nativeButtons.ButtonUpNeeded += IsButtonUp;
             nativeButtons.ButtonPressedNeeded += IsButtonPressed;
             nativeButtons.ClonedPointerEventNeeded += Clone;
             nativeButtons.InteractionNeeded += PlayInteraction;
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MakeHapticsDevice(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MinimumPointerDistance, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset, and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.stage.
Clone()
PointerEventData Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone (int pointerDataID, PointerEventData evtData) inline protected
Definition at line 492 of file AbstractPointerDevice.cs.
         {
             return InputModule?.Clone(pointerDataID, evtData);
         }
References Juniper.Input.IInputModule.Clone(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InputModule.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
Install()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 180 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Install(nativeButtons, gameObject);
             OnProbeFound();
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Reinstall().
InternalUpdate()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InternalUpdate () inline protected virtual
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 563 of file AbstractPointerDevice.cs.
         {
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
IsButtonDown() [1/3]
bool Juniper.Input.Pointers.IPointerDevice.IsButtonDown (PointerEventData.InputButton button) inherited
IsButtonDown() [2/3]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown (InputButton button) inline virtual
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 558 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonDown(button);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
IsButtonDown() [3/3]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown (ButtonIDType button) pure virtual
Implementers should return true when a button is first depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonPressed() [1/3]
bool Juniper.Input.Pointers.IPointerDevice.IsButtonPressed (PointerEventData.InputButton button) inherited
IsButtonPressed() [2/3]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed (InputButton button) inline virtual
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 548 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonPressed(button);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
IsButtonPressed() [3/3]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed (ButtonIDType button) pure virtual
Implementers should return true while the button is depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonUp() [1/3]
bool Juniper.Input.Pointers.IPointerDevice.IsButtonUp (PointerEventData.InputButton button) inherited
IsButtonUp() [2/3]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp (InputButton button) inline virtual
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 553 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonUp(button);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
IsButtonUp() [3/3]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp (ButtonIDType button) pure virtual
Implementers should return true when the button is first released.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
MakeHapticsDevice()
abstract AbstractHapticDevice Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MakeHapticsDevice () protected pure virtual
Implemented in Juniper.Input.Pointers.Motion.AbstractHandTracker< HandIDType, ButtonIDType, ConfigType >.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
OnProbeFound()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound () inline virtual
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 213 of file AbstractPointerDevice.cs.
         {
             if (probe == null)
             {
                 probe = Probe.Ensure(transform, ProbeName);
             }
         }
References Juniper.Input.Pointers.Probe.Ensure(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProbeName, and Juniper.Input.Pointers.IPointerDevice.transform.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install().
PlayInteraction()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction (Interaction action) inline virtual
Definition at line 483 of file AbstractPointerDevice.cs.
         {
             if (Time.unscaledTime > finishTime || action != lastAction)
             {
                 lastAction = action;
                 finishTime = Time.unscaledTime + InteractionAudio.Play(action, probe.Cursor, Haptics);
             }
         }
References Juniper.Input.Pointers.IProbe.Cursor, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.finishTime, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastAction, Juniper.Audio.AbstractInteractionAudio.Play(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit().
Process()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process (PointerEventData evtData, float pixelDragThresholdSquared) inline virtual
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 497 of file AbstractPointerDevice.cs.
         {
             if (!IsDragging)
             {
                 TestEnterExit(evtData);
             }
             EventTarget = ProcessButtons(evtData, pixelDragThresholdSquared);
             if (evtData.clickCount == -1)
             {
                 evtData.clickCount = 0;
             }
             LastWorldPoint = evtData.pointerCurrentRaycast.worldPosition;
             LastSmoothedWorldPoint = SmoothedWorldPoint;
             LastOrigin = Origin;
             probe?.SetCursor(
                 evtData.pointerCurrentRaycast.gameObject != null,
                 AnyButtonPressed,
                 LastWorldPoint,
                 evtData.pointerCurrentRaycast.worldNormal);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AnyButtonPressed, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.EventTarget, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDragging, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastOrigin, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastSmoothedWorldPoint, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastWorldPoint, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Origin, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons(), Juniper.Input.Pointers.IProbe.SetCursor(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPoint, and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit().
ProcessButtons()
virtual IEventSystemHandler Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared) inline protected virtual
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 522 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.Process(evtData, pixelDragThresholdSquared);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Reinstall()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 191 of file AbstractPointerDevice.cs.
         {
             Install(true);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install().
RemoveButton()
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.RemoveButton (ButtonIDType buttonID) inline
Remove a button mapping from the pointer.
Parameters
buttonID
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
Definition at line 44 of file AbstractPointerDevice.cs.
         {
             nativeButtons.RemoveButton(buttonID);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
ScreenFromViewport()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromViewport (Vector2 viewportPoint) inline
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 378 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToScreenPoint(viewportPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
ScreenFromWorld()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromWorld (Vector3 worldPoint) inline
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 372 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToScreenPoint(worldPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
Start()
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start () inline
Definition at line 175 of file AbstractPointerDevice.cs.
         {
             eventManager.AddPointer(this);
         }
References Juniper.Input.AbstractUnifiedInputModule.AddPointer(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager.
TestEnterExit()
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit (PointerEventData evtData) inline private
Definition at line 527 of file AbstractPointerDevice.cs.
         {
             var target = ExecuteEvents.GetEventHandler<IPointerEnterHandler>(evtData.pointerCurrentRaycast.gameObject);
             if (target != evtData.pointerEnter)
             {
                 evtData.clickCount = -1;
                 if (evtData.pointerEnter != null)
                 {
                     ExecuteEvents.ExecuteHierarchy(evtData.pointerEnter, evtData, ExecuteEvents.pointerExitHandler);
                     PlayInteraction(Interaction.Exited);
                     evtData.pointerEnter = null;
                 }
                 if (target != null)
                 {
                     evtData.pointerEnter = ExecuteEvents.ExecuteHierarchy(target, evtData, ExecuteEvents.pointerEnterHandler);
                     PlayInteraction(Interaction.Entered);
                 }
             }
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Uninstall()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Uninstall () inline virtual
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 186 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Uninstall(gameObject);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig.
Update()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update () inline virtual
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Definition at line 419 of file AbstractPointerDevice.cs.
         {
             if (motionFilter != lastMotionFilter)
             {
 #if UNITY_EDITOR
                 parentMotionFilter = motionFilter;
 #endif
                 motionFilter = Instantiate(motionFilter);
                 lastMotionFilter = motionFilter;
             }
 #if UNITY_EDITOR
             motionFilter?.Copy(parentMotionFilter);
 #endif
             Connected = IsConnected;
             if (probe != null)
             {
                 probe.SetActive(IsEnabled && showProbe);
                 probe.LaserPointerMaterial = LaserPointerMaterial;
             }
             if (IsEnabled)
             {
                 motionFilter?.UpdateState(WorldPoint);
                 InternalUpdate();
                 probe?.AlignProbe(Direction, transform.up);
             }
         }
References Juniper.Input.Pointers.IProbe.AlignProbe(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Connected, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InternalUpdate(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsConnected, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsEnabled, Juniper.Input.Pointers.IProbe.LaserPointerMaterial, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LaserPointerMaterial, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastMotionFilter, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.motionFilter, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Input.Pointers.IProbe.SetActive(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.showProbe, Juniper.Input.Pointers.IPointerDevice.transform, Juniper.Statistics.AbstractMotionFilter.UpdateState(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldPoint.
ViewportFromScreen()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromScreen (Vector2 screenPoint) inline
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 390 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToViewportPoint(screenPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
ViewportFromWorld()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromWorld (Vector3 worldPoint) inline
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 384 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToViewportPoint(worldPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
WorldFromScreen()
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen (Vector2 screenPoint) inline
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 396 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToWorldPoint((Vector3)screenPoint + pointerOffset);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset.
WorldFromViewport()
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport (Vector2 viewportPoint) inline
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 402 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToWorldPoint((Vector3)viewportPoint + pointerOffset);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset.
Member Data Documentation
Connected
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Connected
Definition at line 50 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
eventManager
AbstractUnifiedInputModule Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager protected
Definition at line 450 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start().
finishTime
float Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.finishTime private
Definition at line 480 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
LaserPointerMaterial
Material Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LaserPointerMaterial
Definition at line 81 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
lastAction
Interaction Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastAction private
Definition at line 481 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
lastMotionFilter
AbstractMotionFilter Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastMotionFilter private
Definition at line 412 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
motionFilter
AbstractMotionFilter Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.motionFilter
Definition at line 413 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.MakeMotionController< T >(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
nativeButtons
readonly ButtonMapper<ButtonIDType> Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons = new ButtonMapper<ButtonIDType>() protected
Definition at line 37 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AddButton(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.RemoveButton().
PointerConfig
readonly ConfigType Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig static protected
Initial value:
=
            new ConfigType()
Definition at line 26 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.MakeMotionController< T >(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Uninstall().
pointerOffset
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset protected
Definition at line 71 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport().
probe
IProbe Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe protected
The cursor probe that shows the physical location of the current selection.
Definition at line 211 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
showProbe
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.showProbe = true
Definition at line 205 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
stage
Avatar Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.stage protected
Definition at line 460 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
VIEWPORT_MIDPOINT
readonly Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.VIEWPORT_MIDPOINT static protected
Initial value:
=
            0.5f * Vector2.one
Definition at line 23 of file AbstractPointerDevice.cs.
Property Documentation
AnyButtonPressed
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AnyButtonPressed get
Definition at line 145 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return IsButtonPressed(InputButton.Left)
                     || IsButtonPressed(InputButton.Right)
                     || IsButtonPressed(InputButton.Middle);
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
ButtonType
Type Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ButtonType get
Definition at line 30 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return typeof(ButtonIDType);
             }
         }
Direction
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Direction get
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
The interaction direction.
Definition at line 300 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (SmoothedWorldPoint - Origin).normalized;
             }
         }
EventTarget
IEventSystemHandler Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.EventTarget get set
Definition at line 107 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Haptics
AbstractHapticDevice Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics get protected set
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 476 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
InputModule
IInputModule Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InputModule get
Definition at line 453 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return eventManager;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone().
isActiveAndEnabled
bool Juniper.Input.Pointers.IPointerDevice.isActiveAndEnabled get inherited
Definition at line 44 of file IPointerDevice.cs.
         {
             get;
         }
IsConnected
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsConnected get
Definition at line 112 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
IsDisabled
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDisabled get
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 129 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return !IsEnabled;
             }
         }
IsDragging
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDragging get
Definition at line 463 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return EventTarget != null && nativeButtons.IsDragging;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
IsEnabled
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsEnabled get
Definition at line 117 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return isActiveAndEnabled && IsConnected;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
LastDirection
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastDirection get
Definition at line 308 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (LastSmoothedWorldPoint - LastOrigin).normalized;
             }
         }
LastOrigin
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastOrigin get private set
Definition at line 238 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
LastScreenPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastScreenPoint get
Definition at line 324 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(LastSmoothedWorldPoint);
             }
         }
LastSmoothedWorldPoint
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastSmoothedWorldPoint get private set
Definition at line 282 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
LastViewportPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastViewportPoint get
Definition at line 348 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(LastSmoothedWorldPoint);
             }
         }
LastWorldPoint
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastWorldPoint get private set
Definition at line 257 of file AbstractPointerDevice.cs.
         {
             get; private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Layer
int Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Layer get set
Definition at line 84 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return gameObject.layer;
             }
             set
             {
                 if (value != gameObject.layer)
                 {
                     foreach (var trans in transform.FamilyTree())
                     {
                         trans.gameObject.layer = value;
                     }
                 }
             }
         }
LockedOnTarget
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LockedOnTarget get set
Definition at line 102 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
MaximumPointerDistance
float Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MaximumPointerDistance get
Definition at line 74 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Min(10f, 0.9f * DisplayManager.MainCamera.farClipPlane);
             }
         }
MinimumPointerDistance
float Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MinimumPointerDistance get
The minimum distance from the camera at which to place the pointer.
Definition at line 64 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Max(1.5f, 1.1f * DisplayManager.MainCamera.nearClipPlane);
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
Origin
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Origin get
Definition at line 230 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return transform.position;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
OriginDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OriginDelta get
Definition at line 244 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Origin - LastOrigin;
             }
         }
PointerDataID
int Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerDataID get
Definition at line 53 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return GetInstanceID();
             }
         }
ProbeName
string Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProbeName get
Definition at line 222 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return name + "-probe";
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound().
Raycaster
PhysicsRaycaster? Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Raycaster get
Definition at line 137 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.Raycaster;
             }
         }
ScreenDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenDelta get
Definition at line 332 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenPoint - LastScreenPoint;
             }
         }
ScreenPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenPoint get
Definition at line 316 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(SmoothedWorldPoint);
             }
         }
ScrollDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScrollDelta get protected set
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 368 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate().
SmoothedWorldPoint
Vector3??? Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPoint get
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 274 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return motionFilter?.PredictedPosition ?? WorldPoint;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
SmoothedWorldPointDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPointDelta get
Definition at line 288 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return SmoothedWorldPoint - LastSmoothedWorldPoint;
             }
         }
transform
Transform Juniper.Input.Pointers.IPointerDevice.transform get inherited
Definition at line 12 of file IPointerDevice.cs.
 { get;  }
Referenced by Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
ViewportDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportDelta get
Definition at line 356 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportPoint - LastViewportPoint;
             }
         }
ViewportPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportPoint get
Definition at line 340 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(SmoothedWorldPoint);
             }
         }
WorldDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldDelta get
Definition at line 262 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return WorldPoint - LastWorldPoint;
             }
         }
WorldPoint
abstract Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldPoint get
Definition at line 252 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/Pointers/AbstractPointerDevice.cs