Juniper: Juniper.XR.VuforiaImageAnalyzer Class Reference
Juniper.XR.VuforiaImageAnalyzer Class Reference
Basic scaffolding around performing image analysis on Vuforia's image feed. This typically only works on Android.
Public Member Functions
void Stop ()
Signal to the background thread that it should stop the repeatition process and shut down.
Public Attributes
Action< Image, GetPixelFromBuffer > imageAnalyzer
The function passed in to perform image analysis.
override bool Running
Returns true if the thread is still running and not in the middle of shutting down
Protected Member Functions
override void Loop ()
attempts to setup the right image format, retrieve images from Vuforia, and pass them on for processing.
override void Awake ()
Create a new background thread, initialized in a non-running, non-shutting down state.
override void OnBegin ()
Code to execute when the thread first starts.
override void Execute ()
The routine that runs on the background thread.
void OnError (Exception exp)
Trigger the Error event handler, if it has any listeners attached to it.
void Begin ()
Get the background thread up and running.
Properties
static Image.? PIXEL_FORMAT ImageFormat [get]
The current image format. If there are no more image formats left to try, the value will be null.
Events
EventHandler< BackgroundThreadErrorEventArgs > Error
An event that triggers if the background operation throws an exception.
Private Member Functions
void Update ()
Checks to see if Vuforia is still running and either starts up the analysis thread if Vuforia is running but the thread isn't, or shuts it down if the thread is running but Vuforia isn't.
Private Attributes
GetPixelFromBuffer pixelGetter
The current pixel retriever.
Image.? PIXEL_FORMAT lastFormat
The image format used in the previous attempt. Useful for
Static Private Attributes
static Dictionary< Image.PIXEL_FORMAT, GetPixelFromBuffer > PixelConverters
A mapping from Vuforia's pixel formats to functions that can retrieve an indexed pixel in those formats.
static Queue< Image.PIXEL_FORMAT > attemptFormats
A queue of formats to try. Not all formats will work on all systems, so we search through the queue until we find one that works.
Detailed Description
Basic scaffolding around performing image analysis on Vuforia's image feed. This typically only works on Android.
Definition at line 15 of file VuforiaImageAnalyzer.cs.
Member Function Documentation
Awake()
override void Juniper.Data.AbstractBackgroundRepeatingThread.Awake () inline protected virtual inherited
Create a new background thread, initialized in a non-running, non-shutting down state.
Reimplemented from Juniper.Data.AbstractBackgroundThread.
Definition at line 25 of file AbstractBackgroundRepeatingThread.cs.
         {
             base.Awake();
             stopping = false;
         }
References Juniper.Data.AbstractBackgroundRepeatingThread.stopping.
Begin()
void Juniper.Data.AbstractBackgroundThread.Begin () inline protected inherited
Get the background thread up and running.
Definition at line 43 of file AbstractBackgroundThread.cs.
         {
             if (!Running)
             {
                 OnBegin();
                 Task.Run(new Action(Run));
             }
         }
References Juniper.Data.AbstractBackgroundThread.OnBegin(), Juniper.Data.AbstractBackgroundThread.Run(), and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Update().
Execute()
override void Juniper.Data.AbstractBackgroundRepeatingThread.Execute () inline protected virtual inherited
The routine that runs on the background thread.
Implements Juniper.Data.AbstractBackgroundThread.
Definition at line 43 of file AbstractBackgroundRepeatingThread.cs.
         {
             while (!stopping)
             {
                 try
                 {
                     Loop();
                 }
                 catch (Exception exp)
                 {
                     OnError(exp);
                 }
             }
         }
References Juniper.Data.AbstractBackgroundRepeatingThread.Loop(), Juniper.Data.AbstractBackgroundThread.OnError(), and Juniper.Data.AbstractBackgroundRepeatingThread.stopping.
Loop()
override void Juniper.XR.VuforiaImageAnalyzer.Loop () inline protected virtual
attempts to setup the right image format, retrieve images from Vuforia, and pass them on for processing.
Implements Juniper.Data.AbstractBackgroundRepeatingThread.
Definition at line 104 of file VuforiaImageAnalyzer.cs.
         {
             if (ImageFormat != lastFormat)
             {
                 while (ImageFormat != null && !CameraDevice.Instance.SetFrameFormat(ImageFormat.Value, true))
                 {
                     attemptFormats.Dequeue();
                 }
                 lastFormat = ImageFormat;
                 pixelGetter = null;
                 if (ImageFormat != null && PixelConverters.ContainsKey(ImageFormat.Value))
                 {
                     pixelGetter = PixelConverters[ImageFormat.Value];
                 }
             }
             if (ImageFormat != null)
             {
                 try
                 {
                     var image = CameraDevice.Instance.GetCameraImage(ImageFormat.Value);
                     if (image != null)
                     {
                         imageAnalyzer(image, pixelGetter);
                     }
                 }
                 catch (Exception exp)
                 {
                     ScreenDebugger.Print(exp, "VuforiaImageAnalyzer");
                 }
             }
         }
References Juniper.XR.VuforiaImageAnalyzer.attemptFormats, Juniper.XR.VuforiaImageAnalyzer.imageAnalyzer, Juniper.XR.VuforiaImageAnalyzer.ImageFormat, Juniper.XR.VuforiaImageAnalyzer.lastFormat, Juniper.XR.VuforiaImageAnalyzer.PixelConverters, Juniper.XR.VuforiaImageAnalyzer.pixelGetter, and System.ScreenDebugger.Print().
OnBegin()
override void Juniper.Data.AbstractBackgroundRepeatingThread.OnBegin () inline protected virtual inherited
Code to execute when the thread first starts.
Reimplemented from Juniper.Data.AbstractBackgroundThread.
Definition at line 34 of file AbstractBackgroundRepeatingThread.cs.
         {
             base.OnBegin();
             stopping = false;
         }
References Juniper.Data.AbstractBackgroundRepeatingThread.stopping.
OnError()
void Juniper.Data.AbstractBackgroundThread.OnError (Exception exp) inline protected inherited
Trigger the Error event handler, if it has any listeners attached to it.
Parameters
exp
Definition at line 26 of file AbstractBackgroundThread.cs.
         {
             if (Running)
             {
                 Error?.Invoke(this, new BackgroundThreadErrorEventArgs(exp));
             }
         }
References Juniper.Data.AbstractBackgroundThread.Error, and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.Data.AbstractBackgroundRepeatingThread.Execute(), and Juniper.Data.AbstractBackgroundThread.Run().
Stop()
void Juniper.Data.AbstractBackgroundRepeatingThread.Stop () inherited
Signal to the background thread that it should stop the repeatition process and shut down.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Update().
Update()
void Juniper.XR.VuforiaImageAnalyzer.Update () inline private
Checks to see if Vuforia is still running and either starts up the analysis thread if Vuforia is running but the thread isn't, or shuts it down if the thread is running but Vuforia isn't.
Definition at line 85 of file VuforiaImageAnalyzer.cs.
         {
             if (imageAnalyzer != null)
             {
                 if (VuforiaBehaviour.Instance.enabled && !Running)
                 {
                     Begin();
                 }
                 else if (!VuforiaBehaviour.Instance.enabled && Running)
                 {
                     Stop();
                 }
             }
         }
References Juniper.Data.AbstractBackgroundThread.Begin(), Juniper.XR.VuforiaImageAnalyzer.imageAnalyzer, Juniper.Data.AbstractBackgroundRepeatingThread.Running, and Juniper.Data.AbstractBackgroundRepeatingThread.Stop().
Member Data Documentation
attemptFormats
Queue<Image.PIXEL_FORMAT> Juniper.XR.VuforiaImageAnalyzer.attemptFormats static private
Initial value:
= new Queue<Image.PIXEL_FORMAT>(new[]
        {
            Image.PIXEL_FORMAT.RGB888,
            Image.PIXEL_FORMAT.RGBA8888,
            Image.PIXEL_FORMAT.YUV,
            Image.PIXEL_FORMAT.RGB565,
            Image.PIXEL_FORMAT.GRAYSCALE,
            Image.PIXEL_FORMAT.UNKNOWN_FORMAT
        })
A queue of formats to try. Not all formats will work on all systems, so we search through the queue until we find one that works.
Definition at line 35 of file VuforiaImageAnalyzer.cs.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Loop().
imageAnalyzer
Action<Image, GetPixelFromBuffer> Juniper.XR.VuforiaImageAnalyzer.imageAnalyzer
The function passed in to perform image analysis.
Definition at line 78 of file VuforiaImageAnalyzer.cs.
Referenced by Juniper.World.LightEstimation.VuforiaLightMeasurement.Awake(), Juniper.XR.VuforiaImageAnalyzer.Loop(), and Juniper.XR.VuforiaImageAnalyzer.Update().
lastFormat
Image.? PIXEL_FORMAT Juniper.XR.VuforiaImageAnalyzer.lastFormat private
The image format used in the previous attempt. Useful for
Definition at line 73 of file VuforiaImageAnalyzer.cs.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Loop().
PixelConverters
Dictionary<Image.PIXEL_FORMAT, GetPixelFromBuffer> Juniper.XR.VuforiaImageAnalyzer.PixelConverters static private
Initial value:
= new Dictionary<Image.PIXEL_FORMAT, GetPixelFromBuffer>
        {
            { Image.PIXEL_FORMAT.GRAYSCALE, ColorExt.GetGrayscalePixel },
            { Image.PIXEL_FORMAT.RGB565, ColorExt.GetRGB565Pixel },
            { Image.PIXEL_FORMAT.RGB888, ColorExt.GetRGB888Pixel },
            { Image.PIXEL_FORMAT.RGBA8888, ColorExt.GetRGB888Pixel },
            { Image.PIXEL_FORMAT.YUV, ColorExt.GetYUVPixel },
            { Image.PIXEL_FORMAT.UNKNOWN_FORMAT, ColorExt.GetRGB888Pixel}
        }
A mapping from Vuforia's pixel formats to functions that can retrieve an indexed pixel in those formats.
Definition at line 21 of file VuforiaImageAnalyzer.cs.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Loop().
pixelGetter
GetPixelFromBuffer Juniper.XR.VuforiaImageAnalyzer.pixelGetter private
The current pixel retriever.
Definition at line 68 of file VuforiaImageAnalyzer.cs.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Loop().
Running
override bool Juniper.Data.AbstractBackgroundRepeatingThread.Running inherited
Initial value:
=>
            base.Running && !stopping
Returns true if the thread is still running and not in the middle of shutting down
Definition at line 13 of file AbstractBackgroundRepeatingThread.cs.
Referenced by Juniper.Data.ManagedRequest< T >.OnMessage(), Juniper.Data.ManagedRequest< T >.OnServerError(), Juniper.Data.ManagedRequest< T >.OnTimedOut(), Juniper.World.LightEstimation.VuforiaLightMeasurement.PrintDebugReport(), and Juniper.XR.VuforiaImageAnalyzer.Update().
Property Documentation
ImageFormat
Image.? PIXEL_FORMAT Juniper.XR.VuforiaImageAnalyzer.ImageFormat static get
The current image format. If there are no more image formats left to try, the value will be null.
The image format.
Definition at line 51 of file VuforiaImageAnalyzer.cs.
         {
             get
             {
                 if (attemptFormats.Count > 0)
                 {
                     return attemptFormats.Peek();
                 }
                 else
                 {
                     return null;
                 }
             }
         }
Referenced by Juniper.XR.VuforiaImageAnalyzer.Loop(), and Juniper.World.LightEstimation.VuforiaLightMeasurement.PrintDebugReport().
Event Documentation
Error
EventHandler<BackgroundThreadErrorEventArgs> Juniper.Data.AbstractBackgroundThread.Error inherited
An event that triggers if the background operation throws an exception.
Definition at line 14 of file AbstractBackgroundThread.cs.
Referenced by Juniper.Data.AbstractBackgroundThread.OnError().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/Vuforia/VuforiaImageAnalyzer.cs