Juniper: UnityEngine.TimedEvent Class Reference
UnityEngine.TimedEvent Class Reference
A component that can be used to trigger events after a set amount of time. Useful for automatically advancing between story views, or delaying action after user input.
Public Member Functions
void Awake ()
If playOnAwake is set to true, starts the firing timer.
void Stop ()
Stop the timer, if it's looping in a repeat.
void Play ()
Starts the delay timer.
Public Attributes
bool playOnAwake
Whether or not the event timer should start automatically when the component comes awake.
float delay
The amount of time, in seconds, to allow to elapse before triggering the event.
bool repeat
Whether or not the event timer should repeat after it has actuated.
UnityEvent onTimeout = new UnityEvent()
The event to occur when the timer has finished counting down.
Events
EventHandler Timeout
The event to occur when the timer has finished counting down.
Private Member Functions
void Fire ()
Runs a delay timer and then executes the event.
Detailed Description
A component that can be used to trigger events after a set amount of time. Useful for automatically advancing between story views, or delaying action after user input.
Definition at line 11 of file TimedEvent.cs.
Member Function Documentation
Awake()
void UnityEngine.TimedEvent.Awake () inline
If playOnAwake is set to true, starts the firing timer.
Definition at line 41 of file TimedEvent.cs.
         {
             if (playOnAwake)
             {
                 Play();
             }
         }
References UnityEngine.TimedEvent.Play(), and UnityEngine.TimedEvent.playOnAwake.
Fire()
void UnityEngine.TimedEvent.Fire () inline private
Runs a delay timer and then executes the event.
Returns
The coroutine.
Definition at line 74 of file TimedEvent.cs.
         {
             onTimeout?.Invoke();
             Timeout?.Invoke(this, EventArgs.Empty);
         }
References UnityEngine.TimedEvent.onTimeout, and UnityEngine.TimedEvent.Timeout.
Referenced by UnityEngine.TimedEvent.Play().
Play()
void UnityEngine.TimedEvent.Play () inline
Starts the delay timer.
Definition at line 58 of file TimedEvent.cs.
         {
             if (repeat)
             {
                 InvokeRepeating("Fire", delay, delay);
             }
             else
             {
                 Invoke(nameof(Fire), delay);
             }
         }
References UnityEngine.TimedEvent.delay, UnityEngine.TimedEvent.Fire(), and UnityEngine.TimedEvent.repeat.
Referenced by UnityEngine.TimedEvent.Awake().
Stop()
void UnityEngine.TimedEvent.Stop ()
Stop the timer, if it's looping in a repeat.
Member Data Documentation
delay
float UnityEngine.TimedEvent.delay
The amount of time, in seconds, to allow to elapse before triggering the event.
Definition at line 21 of file TimedEvent.cs.
Referenced by UnityEngine.TimedEvent.Play().
onTimeout
UnityEvent UnityEngine.TimedEvent.onTimeout = new UnityEvent()
The event to occur when the timer has finished counting down.
Definition at line 31 of file TimedEvent.cs.
Referenced by UnityEngine.TimedEvent.Fire().
playOnAwake
bool UnityEngine.TimedEvent.playOnAwake
Whether or not the event timer should start automatically when the component comes awake.
Definition at line 16 of file TimedEvent.cs.
Referenced by UnityEngine.TimedEvent.Awake().
repeat
bool UnityEngine.TimedEvent.repeat
Whether or not the event timer should repeat after it has actuated.
Definition at line 26 of file TimedEvent.cs.
Referenced by UnityEngine.TimedEvent.Play().
Event Documentation
Timeout
EventHandler UnityEngine.TimedEvent.Timeout
The event to occur when the timer has finished counting down.
Definition at line 36 of file TimedEvent.cs.
Referenced by UnityEngine.TimedEvent.Fire().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Extensions/UnityEngine/TimedEvent.cs