Juniper: Juniper.Widgets.QualityDegrader Class Reference
Juniper.Widgets.QualityDegrader Class Reference
This component manages the quality settings on the fly, making sure the application never falls below 50 FPS minimum. Only one of these components is allowed on a GameObject.
Public Member Functions
void Awake ()
Setup the statistics tracking and get the main camera.
void Pause ()
void Resume ()
void Update ()
Check to see if the average frame delta time (minus outliers) has dropped below 30FPS.
Public Attributes
bool collectStats = true
Properties
int QualityLevel [get, set]
Get the current graphics quality level.
string QualityName [get]
Get the name of the current graphics quality level.
bool IsBad [get]
Returns true when the frame rate drops below 30FPS.
Private Member Functions
void ChangeQuality (Action< bool > changer, Func< int, int, bool > checker, int value)
void OnApplicationPause (bool pause)
void OnApplicationFocus (bool focus)
Private Attributes
TerrainManager ground
readonly SingleStatisticsCollection frameStats = new SingleStatisticsCollection(30)
Calculates statistics for the frame delta time value, for knowing the mean value and rejecting outliers.
DisplayManager display
const string GRAPHICS_QUALITY_KEY = "GraphicsQuality"
bool wasPaused = false
Detailed Description
This component manages the quality settings on the fly, making sure the application never falls below 50 FPS minimum. Only one of these components is allowed on a GameObject.
Definition at line 23 of file QualityDegrader.cs.
Member Function Documentation
Awake()
void Juniper.Widgets.QualityDegrader.Awake () inline
Setup the statistics tracking and get the main camera.
Definition at line 127 of file QualityDegrader.cs.
         {
 #if UNITY_POSTPROCESSING
             prost = GetComponent<PostProcessLayer>();
 #endif
             Find.Any(out ground);
             Find.Any(out display);
             QualityLevel = PlayerPrefs.GetInt(GRAPHICS_QUALITY_KEY, QualityLevel);
 #if UNITY_MODULES_XR
             XRSettings.eyeTextureResolutionScale = 1.5f;
 #endif
         }
References Juniper.Widgets.QualityDegrader.display, Juniper.Widgets.QualityDegrader.GRAPHICS_QUALITY_KEY, Juniper.Widgets.QualityDegrader.ground, and Juniper.Widgets.QualityDegrader.QualityLevel.
ChangeQuality()
void Juniper.Widgets.QualityDegrader.ChangeQuality (Action< bool > changer, Func< int, int, bool > checker, int value) inline private
Definition at line 70 of file QualityDegrader.cs.
         {
             var lastValue = QualityLevel;
             while (checker(lastValue, value))
             {
                 changer(true);
                 var newValue = QualityLevel;
                 if (newValue == lastValue)
                 {
                     throw new Exception("Could not change quality level");
                 }
                 else
                 {
                     lastValue = newValue;
                 }
             }
         }
References Juniper.Widgets.QualityDegrader.QualityLevel.
OnApplicationFocus()
void Juniper.Widgets.QualityDegrader.OnApplicationFocus (bool focus) inline private
Definition at line 161 of file QualityDegrader.cs.
         {
             if (!wasPaused)
             {
                 Resume();
             }
         }
References Juniper.Widgets.QualityDegrader.Resume(), and Juniper.Widgets.QualityDegrader.wasPaused.
OnApplicationPause()
void Juniper.Widgets.QualityDegrader.OnApplicationPause (bool pause) inline private
Definition at line 152 of file QualityDegrader.cs.
         {
             wasPaused = !collectStats;
             if (!wasPaused)
             {
                 Pause();
             }
         }
References Juniper.Widgets.QualityDegrader.collectStats, Juniper.Widgets.QualityDegrader.Pause(), and Juniper.Widgets.QualityDegrader.wasPaused.
Pause()
void Juniper.Widgets.QualityDegrader.Pause () inline
Definition at line 142 of file QualityDegrader.cs.
         {
             collectStats = false;
         }
References Juniper.Widgets.QualityDegrader.collectStats.
Referenced by Juniper.Widgets.QualityDegrader.OnApplicationPause().
Resume()
void Juniper.Widgets.QualityDegrader.Resume () inline
Definition at line 147 of file QualityDegrader.cs.
         {
             collectStats = true;
         }
References Juniper.Widgets.QualityDegrader.collectStats.
Referenced by Juniper.Widgets.QualityDegrader.OnApplicationFocus().
Update()
void Juniper.Widgets.QualityDegrader.Update () inline
Check to see if the average frame delta time (minus outliers) has dropped below 30FPS.
Definition at line 172 of file QualityDegrader.cs.
         {
             if (collectStats)
             {
                 frameStats.Add(1 / Time.unscaledDeltaTime);
                 if (frameStats.IsSaturated && IsBad)
                 {
                     if (QualityLevel > 0)
                     {
                         --QualityLevel;
                     }
                     ScreenDebugger.Print(QualityName);
                     frameStats.Clear();
                 }
             }
         }
References Juniper.Mathematics.SingleStatisticsCollection.Add(), Juniper.Mathematics.AbstractStatisticsCollection< T >.Clear(), Juniper.Widgets.QualityDegrader.collectStats, Juniper.Widgets.QualityDegrader.frameStats, Juniper.Widgets.QualityDegrader.IsBad, Juniper.Mathematics.AbstractStatisticsCollection< T >.IsSaturated, System.ScreenDebugger.Print(), Juniper.Widgets.QualityDegrader.QualityLevel, Juniper.Widgets.QualityDegrader.QualityName, and Juniper.Units.Time.
Member Data Documentation
collectStats
bool Juniper.Widgets.QualityDegrader.collectStats = true
Definition at line 121 of file QualityDegrader.cs.
Referenced by Juniper.Widgets.QualityDegrader.OnApplicationPause(), Juniper.Widgets.QualityDegrader.Pause(), Juniper.Widgets.QualityDegrader.Resume(), and Juniper.Widgets.QualityDegrader.Update().
display
DisplayManager Juniper.Widgets.QualityDegrader.display private
Definition at line 33 of file QualityDegrader.cs.
Referenced by Juniper.Widgets.QualityDegrader.Awake().
frameStats
readonly SingleStatisticsCollection Juniper.Widgets.QualityDegrader.frameStats = new SingleStatisticsCollection(30) private
Calculates statistics for the frame delta time value, for knowing the mean value and rejecting outliers.
Definition at line 31 of file QualityDegrader.cs.
Referenced by Juniper.Widgets.QualityDegrader.Update().
GRAPHICS_QUALITY_KEY
const string Juniper.Widgets.QualityDegrader.GRAPHICS_QUALITY_KEY = "GraphicsQuality" private
Definition at line 119 of file QualityDegrader.cs.
Referenced by Juniper.Widgets.QualityDegrader.Awake().
ground
TerrainManager Juniper.Widgets.QualityDegrader.ground private
Definition at line 25 of file QualityDegrader.cs.
Referenced by Juniper.Widgets.QualityDegrader.Awake().
wasPaused
bool Juniper.Widgets.QualityDegrader.wasPaused = false private
Definition at line 122 of file QualityDegrader.cs.
Referenced by Juniper.Widgets.QualityDegrader.OnApplicationFocus(), and Juniper.Widgets.QualityDegrader.OnApplicationPause().
Property Documentation
IsBad
bool Juniper.Widgets.QualityDegrader.IsBad get private
Returns true when the frame rate drops below 30FPS.
true if is bad; otherwise, false.
Definition at line 105 of file QualityDegrader.cs.
         {
             get
             {
                 return frameStats.Mean / 30f < 1f;
             }
         }
Referenced by Juniper.Widgets.QualityDegrader.Update().
QualityLevel
int Juniper.Widgets.QualityDegrader.QualityLevel get set
Get the current graphics quality level.
The quality level.
Definition at line 40 of file QualityDegrader.cs.
         {
             get
             {
                 return QualitySettings.GetQualityLevel();
             }
             set
             {
                 if (value != QualityLevel)
                 {
                     display.DisableDisplay();
                     ChangeQuality(QualitySettings.IncreaseLevel, (a, b) => a < b, value);
                     ChangeQuality(QualitySettings.DecreaseLevel, (a, b) => a > b, value);
                     display.ResumeDisplay();
                     if (ground != null)
                     {
                         ground.spatialMappingFidelity = (Level)(value / 2);
                     }
 #if UNITY_POSTPROCESSING
                     prost.enabled = QualityLevel >= 4;
 #endif
                     PlayerPrefs.SetInt(GRAPHICS_QUALITY_KEY, value);
                     PlayerPrefs.Save();
                 }
             }
         }
Referenced by Juniper.Widgets.QualityDegrader.Awake(), Juniper.Widgets.QualityDegrader.ChangeQuality(), and Juniper.Widgets.QualityDegrader.Update().
QualityName
string Juniper.Widgets.QualityDegrader.QualityName get private
Get the name of the current graphics quality level.
The name of the quality.
Definition at line 93 of file QualityDegrader.cs.
         {
             get
             {
                 return QualitySettings.names[QualityLevel];
             }
         }
Referenced by Juniper.Widgets.QualityDegrader.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Widgets/QualityDegrader.cs