Juniper: Juniper.Animation.TransitionControllerTests Class Reference
Juniper.Animation.TransitionControllerTests Class Reference
Classes
class MockTransition
Public Member Functions
void SetUp ()
void TearDown ()
void EnterStartsAtZero ()
void EnterStartsValueChanged ()
IEnumerator EnterEndsAtOne ()
IEnumerator EnterEndsWithMoreValuesChanged ()
void SetEnabledStartsAtZero ()
IEnumerator SetEnabledEndsAtOne ()
void ExitStartsAtOne ()
IEnumerator ExitEndsAtZero ()
IEnumerator ExitDoesntCompleteRightAway ()
IEnumerator ExitEndsWithMoreValuesChanged ()
IEnumerator ExitDoesntActivate ()
IEnumerator ExitDoesntEnable ()
IEnumerator ExitDisabledDoesntChangeValue ()
void EnterActivatesObject ()
void EnterEnablesObject ()
void EnterFiresEntering ()
IEnumerator EnterFiresEntered ()
IEnumerator EnterDoesntFireExiting ()
IEnumerator EnterDoesntFireExited ()
IEnumerator EnterCompletesAsynchronously ()
IEnumerator EnterDoesntDisable ()
IEnumerator EnterDoesntDeactivate ()
IEnumerator ExitFiresExiting ()
IEnumerator ExitFiresExited ()
IEnumerator ExitDoesntFireEntering ()
IEnumerator ExitDoesntFireEntered ()
IEnumerator ExitCompletesAsynchronously ()
IEnumerator ExitDisables ()
IEnumerator ExitDoesntDeactivate ()
IEnumerator SetEnabledFiresEntering ()
IEnumerator SetEnabledFiresEntered ()
IEnumerator SetEnabledDoesntFireExiting ()
IEnumerator SetEnabledDoesntFireExited ()
IEnumerator SetEnabledCompletesAsynchronously ()
IEnumerator SetEnabledDoesntDisable ()
IEnumerator SetEnabledDoesntDeactivate ()
Private Member Functions
IEnumerator SetEnabled ()
WaitUntil Waiter ()
IEnumerator Enter ()
IEnumerator Exit ()
Private Attributes
const float TRANS_TIME = 0.2f
const float TRANS_START_VALUE = 0.5f
GameObject go
MockTransition trans
Detailed Description
Definition at line 12 of file TransitionControllerTests.cs.
Member Function Documentation
Enter()
IEnumerator Juniper.Animation.TransitionControllerTests.Enter () inline private
Definition at line 336 of file TransitionControllerTests.cs.
         {
             trans.Enter();
             return Waiter();
         }
References Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.Waiter().
Referenced by Juniper.Animation.TransitionControllerTests.EnterCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.EnterDoesntDeactivate(), Juniper.Animation.TransitionControllerTests.EnterDoesntDisable(), Juniper.Animation.TransitionControllerTests.EnterDoesntFireExited(), Juniper.Animation.TransitionControllerTests.EnterDoesntFireExiting(), Juniper.Animation.TransitionControllerTests.EnterEndsAtOne(), Juniper.Animation.TransitionControllerTests.EnterEndsWithMoreValuesChanged(), Juniper.Animation.TransitionControllerTests.EnterFiresEntered(), Juniper.Animation.TransitionControllerTests.ExitCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.ExitDisables(), Juniper.Animation.TransitionControllerTests.ExitDoesntCompleteRightAway(), Juniper.Animation.TransitionControllerTests.ExitDoesntDeactivate(), Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntered(), Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntering(), Juniper.Animation.TransitionControllerTests.ExitFiresExited(), and Juniper.Animation.TransitionControllerTests.ExitFiresExiting().
EnterActivatesObject()
void Juniper.Animation.TransitionControllerTests.EnterActivatesObject () inline
Definition at line 142 of file TransitionControllerTests.cs.
         {
             trans.Enter();
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.TransitionControllerTests.go, and Juniper.Animation.TransitionControllerTests.trans.
EnterCompletesAsynchronously()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterCompletesAsynchronously () inline
Definition at line 188 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             Assert.IsTrue(trans.IsComplete);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.AbstractStateController.IsComplete, and Juniper.Animation.TransitionControllerTests.trans.
EnterDoesntDeactivate()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterDoesntDeactivate () inline
Definition at line 202 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), and Juniper.Animation.TransitionControllerTests.go.
EnterDoesntDisable()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterDoesntDisable () inline
Definition at line 195 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             Assert.IsTrue(trans.enabled);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), and Juniper.Animation.TransitionControllerTests.trans.
EnterDoesntFireExited()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterDoesntFireExited () inline
Definition at line 180 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredExited);
             yield return Enter();
             Assert.IsFalse(trans.FiredExited);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredExited, and Juniper.Animation.TransitionControllerTests.trans.
EnterDoesntFireExiting()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterDoesntFireExiting () inline
Definition at line 172 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredExiting);
             yield return Enter();
             Assert.IsFalse(trans.FiredExiting);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredExiting, and Juniper.Animation.TransitionControllerTests.trans.
EnterEnablesObject()
void Juniper.Animation.TransitionControllerTests.EnterEnablesObject () inline
Definition at line 149 of file TransitionControllerTests.cs.
         {
             trans.Enter();
             Assert.IsTrue(trans.enabled);
         }
References Juniper.Animation.AbstractTransitionController.Enter(), and Juniper.Animation.TransitionControllerTests.trans.
EnterEndsAtOne()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterEndsAtOne () inline
Definition at line 50 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             Assert.AreEqual(1, trans.Value);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
EnterEndsWithMoreValuesChanged()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterEndsWithMoreValuesChanged () inline
Definition at line 57 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             Assert.Greater(trans.ValueChanges.Count, 1);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.ValueChanges.
EnterFiresEntered()
IEnumerator Juniper.Animation.TransitionControllerTests.EnterFiresEntered () inline
Definition at line 164 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredEntered);
             yield return Enter();
             Assert.IsTrue(trans.FiredEntered);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredEntered, and Juniper.Animation.TransitionControllerTests.trans.
EnterFiresEntering()
void Juniper.Animation.TransitionControllerTests.EnterFiresEntering () inline
Definition at line 156 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredEntering);
             trans.Enter();
             Assert.IsTrue(trans.FiredEntering);
         }
References Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredEntering, and Juniper.Animation.TransitionControllerTests.trans.
EnterStartsAtZero()
void Juniper.Animation.TransitionControllerTests.EnterStartsAtZero () inline
Definition at line 36 of file TransitionControllerTests.cs.
         {
             trans.Enter();
             Assert.AreEqual(0, trans.Value);
         }
References Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
EnterStartsValueChanged()
void Juniper.Animation.TransitionControllerTests.EnterStartsValueChanged () inline
Definition at line 43 of file TransitionControllerTests.cs.
         {
             trans.Enter();
             Assert.AreEqual(1, trans.ValueChanges.Count);
         }
References Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.ValueChanges.
Exit()
IEnumerator Juniper.Animation.TransitionControllerTests.Exit () inline private
Definition at line 342 of file TransitionControllerTests.cs.
         {
             trans.Exit();
             return Waiter();
         }
References Juniper.Animation.TransitionControllerTests.MockTransition.Exit(), Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.Waiter().
Referenced by Juniper.Animation.TransitionControllerTests.ExitCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.ExitDisabledDoesntChangeValue(), Juniper.Animation.TransitionControllerTests.ExitDisables(), Juniper.Animation.TransitionControllerTests.ExitDoesntActivate(), Juniper.Animation.TransitionControllerTests.ExitDoesntDeactivate(), Juniper.Animation.TransitionControllerTests.ExitDoesntEnable(), Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntered(), Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntering(), Juniper.Animation.TransitionControllerTests.ExitEndsAtZero(), and Juniper.Animation.TransitionControllerTests.ExitFiresExited().
ExitCompletesAsynchronously()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitCompletesAsynchronously () inline
Definition at line 243 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             yield return Exit();
             Assert.IsTrue(trans.IsComplete);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.Exit(), Juniper.AbstractStateController.IsComplete, and Juniper.Animation.TransitionControllerTests.trans.
ExitDisabledDoesntChangeValue()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDisabledDoesntChangeValue () inline
Definition at line 135 of file TransitionControllerTests.cs.
         {
             yield return Exit();
             Assert.AreEqual(TRANS_START_VALUE, trans.Value);
         }
References Juniper.Animation.TransitionControllerTests.Exit(), Juniper.Animation.TransitionControllerTests.trans, Juniper.Animation.TransitionControllerTests.TRANS_START_VALUE, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
ExitDisables()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDisables () inline
Definition at line 251 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             yield return Exit();
             Assert.IsFalse(trans.enabled);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.Exit(), and Juniper.Animation.TransitionControllerTests.trans.
ExitDoesntActivate()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDoesntActivate () inline
Definition at line 121 of file TransitionControllerTests.cs.
         {
             yield return Exit();
             Assert.IsFalse(go.activeInHierarchy);
         }
References Juniper.Animation.TransitionControllerTests.Exit(), and Juniper.Animation.TransitionControllerTests.go.
ExitDoesntCompleteRightAway()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDoesntCompleteRightAway () inline
Definition at line 97 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             trans.Exit();
             for (var i = 0; i < 10; ++i)
             {
                 Assert.IsFalse(trans.IsComplete, $"Not complete {i}");
                 yield return null;
             }
             yield return Waiter();
             Assert.IsTrue(trans.IsComplete, "Complete");
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.MockTransition.Exit(), Juniper.AbstractStateController.IsComplete, Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.Waiter().
ExitDoesntDeactivate()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDoesntDeactivate () inline
Definition at line 259 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             yield return Exit();
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.Exit(), and Juniper.Animation.TransitionControllerTests.go.
ExitDoesntEnable()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDoesntEnable () inline
Definition at line 128 of file TransitionControllerTests.cs.
         {
             yield return Exit();
             Assert.IsFalse(trans.enabled);
         }
References Juniper.Animation.TransitionControllerTests.Exit(), and Juniper.Animation.TransitionControllerTests.trans.
ExitDoesntFireEntered()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntered () inline
Definition at line 235 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             yield return Exit();
             Assert.IsFalse(trans.FiredEntered);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.Exit(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredEntered, and Juniper.Animation.TransitionControllerTests.trans.
ExitDoesntFireEntering()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntering () inline
Definition at line 227 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             yield return Exit();
             Assert.IsFalse(trans.FiredEntering);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.Exit(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredEntering, and Juniper.Animation.TransitionControllerTests.trans.
ExitEndsAtZero()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitEndsAtZero () inline
Definition at line 88 of file TransitionControllerTests.cs.
         {
             go.Activate();
             trans.enabled = true;
             yield return Exit();
             Assert.AreEqual(0, trans.Value);
         }
References Juniper.Animation.TransitionControllerTests.Exit(), Juniper.Animation.TransitionControllerTests.go, Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
ExitEndsWithMoreValuesChanged()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitEndsWithMoreValuesChanged () inline
Definition at line 111 of file TransitionControllerTests.cs.
         {
             trans.enabled = true;
             go.Activate();
             trans.Exit();
             yield return Waiter();
             Assert.Greater(trans.ValueChanges.Count, 1, "Many changes");
         }
References Juniper.Animation.TransitionControllerTests.MockTransition.Exit(), Juniper.Animation.TransitionControllerTests.go, Juniper.Animation.TransitionControllerTests.trans, Juniper.Animation.TransitionControllerTests.MockTransition.ValueChanges, and Juniper.Animation.TransitionControllerTests.Waiter().
ExitFiresExited()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitFiresExited () inline
Definition at line 218 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             Assert.IsFalse(trans.FiredExited);
             yield return Exit();
             Assert.IsTrue(trans.FiredExited);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.Exit(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredExited, and Juniper.Animation.TransitionControllerTests.trans.
ExitFiresExiting()
IEnumerator Juniper.Animation.TransitionControllerTests.ExitFiresExiting () inline
Definition at line 209 of file TransitionControllerTests.cs.
         {
             yield return Enter();
             Assert.IsFalse(trans.FiredExiting);
             trans.Exit();
             Assert.IsTrue(trans.FiredExiting);
         }
References Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.MockTransition.Exit(), Juniper.Animation.TransitionControllerTests.MockTransition.FiredExiting, and Juniper.Animation.TransitionControllerTests.trans.
ExitStartsAtOne()
void Juniper.Animation.TransitionControllerTests.ExitStartsAtOne () inline
Definition at line 79 of file TransitionControllerTests.cs.
         {
             go.Activate();
             trans.enabled = true;
             trans.Exit();
             Assert.AreEqual(1, trans.Value);
         }
References Juniper.Animation.TransitionControllerTests.MockTransition.Exit(), Juniper.Animation.TransitionControllerTests.go, Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
SetEnabled()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabled () inline private
Definition at line 326 of file TransitionControllerTests.cs.
         {
             go.Activate();
             trans.enabled = true;
             return Waiter();
         }
References Juniper.Animation.TransitionControllerTests.go, Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.Waiter().
Referenced by Juniper.Animation.TransitionControllerTests.SetEnabledCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntDeactivate(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntDisable(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntFireExited(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntFireExiting(), Juniper.Animation.TransitionControllerTests.SetEnabledEndsAtOne(), Juniper.Animation.TransitionControllerTests.SetEnabledFiresEntered(), and Juniper.Animation.TransitionControllerTests.SetEnabledFiresEntering().
SetEnabledCompletesAsynchronously()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledCompletesAsynchronously () inline
Definition at line 299 of file TransitionControllerTests.cs.
         {
             yield return SetEnabled();
             Assert.IsTrue(trans.IsComplete);
         }
References Juniper.AbstractStateController.IsComplete, Juniper.Animation.TransitionControllerTests.SetEnabled(), and Juniper.Animation.TransitionControllerTests.trans.
SetEnabledDoesntDeactivate()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledDoesntDeactivate () inline
Definition at line 313 of file TransitionControllerTests.cs.
         {
             yield return SetEnabled();
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.Animation.TransitionControllerTests.go, and Juniper.Animation.TransitionControllerTests.SetEnabled().
SetEnabledDoesntDisable()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledDoesntDisable () inline
Definition at line 306 of file TransitionControllerTests.cs.
         {
             yield return SetEnabled();
             Assert.IsTrue(trans.enabled);
         }
References Juniper.Animation.TransitionControllerTests.SetEnabled(), and Juniper.Animation.TransitionControllerTests.trans.
SetEnabledDoesntFireExited()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledDoesntFireExited () inline
Definition at line 291 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredExited);
             yield return SetEnabled();
             Assert.IsFalse(trans.FiredExited);
         }
References Juniper.Animation.TransitionControllerTests.MockTransition.FiredExited, Juniper.Animation.TransitionControllerTests.SetEnabled(), and Juniper.Animation.TransitionControllerTests.trans.
SetEnabledDoesntFireExiting()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledDoesntFireExiting () inline
Definition at line 283 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredExiting);
             yield return SetEnabled();
             Assert.IsFalse(trans.FiredExiting);
         }
References Juniper.Animation.TransitionControllerTests.MockTransition.FiredExiting, Juniper.Animation.TransitionControllerTests.SetEnabled(), and Juniper.Animation.TransitionControllerTests.trans.
SetEnabledEndsAtOne()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledEndsAtOne () inline
Definition at line 72 of file TransitionControllerTests.cs.
         {
             yield return SetEnabled();
             Assert.AreEqual(1, trans.Value);
         }
References Juniper.Animation.TransitionControllerTests.SetEnabled(), Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
SetEnabledFiresEntered()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledFiresEntered () inline
Definition at line 275 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredEntered);
             yield return SetEnabled();
             Assert.IsTrue(trans.FiredEntered);
         }
References Juniper.Animation.TransitionControllerTests.MockTransition.FiredEntered, Juniper.Animation.TransitionControllerTests.SetEnabled(), and Juniper.Animation.TransitionControllerTests.trans.
SetEnabledFiresEntering()
IEnumerator Juniper.Animation.TransitionControllerTests.SetEnabledFiresEntering () inline
Definition at line 267 of file TransitionControllerTests.cs.
         {
             Assert.IsFalse(trans.FiredEntering);
             yield return SetEnabled();
             Assert.IsTrue(trans.FiredEntering);
         }
References Juniper.Animation.TransitionControllerTests.MockTransition.FiredEntering, Juniper.Animation.TransitionControllerTests.SetEnabled(), and Juniper.Animation.TransitionControllerTests.trans.
SetEnabledStartsAtZero()
void Juniper.Animation.TransitionControllerTests.SetEnabledStartsAtZero () inline
Definition at line 64 of file TransitionControllerTests.cs.
         {
             go.Activate();
             trans.enabled = true;
             Assert.AreEqual(0, trans.Value);
         }
References Juniper.Animation.TransitionControllerTests.go, Juniper.Animation.TransitionControllerTests.trans, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
SetUp()
void Juniper.Animation.TransitionControllerTests.SetUp () inline
Definition at line 15 of file TransitionControllerTests.cs.
         {
             go = Utils.CreatePrimitive(PrimitiveType.Cube);
             go.Deactivate();
             trans = go.AddComponent<MockTransition>();
             trans.enabled = false;
             Assert.AreEqual(TRANS_START_VALUE, trans.Value, "Start Value");
         }
References Juniper.Animation.TransitionControllerTests.go, Juniper.Animation.TransitionControllerTests.trans, Juniper.Animation.TransitionControllerTests.TRANS_START_VALUE, and Juniper.Animation.TransitionControllerTests.MockTransition.Value.
TearDown()
void Juniper.Animation.TransitionControllerTests.TearDown () inline
Definition at line 26 of file TransitionControllerTests.cs.
         {
             trans.Destroy();
             trans = null;
             go.Destroy();
             go = null;
         }
References Juniper.Animation.TransitionControllerTests.go, and Juniper.Animation.TransitionControllerTests.trans.
Waiter()
WaitUntil Juniper.Animation.TransitionControllerTests.Waiter () private
Referenced by Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.Exit(), Juniper.Animation.TransitionControllerTests.ExitDoesntCompleteRightAway(), Juniper.Animation.TransitionControllerTests.ExitEndsWithMoreValuesChanged(), and Juniper.Animation.TransitionControllerTests.SetEnabled().
Member Data Documentation
go
GameObject Juniper.Animation.TransitionControllerTests.go private
Definition at line 322 of file TransitionControllerTests.cs.
Referenced by Juniper.Animation.TransitionControllerTests.EnterActivatesObject(), Juniper.Animation.TransitionControllerTests.EnterDoesntDeactivate(), Juniper.Animation.TransitionControllerTests.ExitDoesntActivate(), Juniper.Animation.TransitionControllerTests.ExitDoesntDeactivate(), Juniper.Animation.TransitionControllerTests.ExitEndsAtZero(), Juniper.Animation.TransitionControllerTests.ExitEndsWithMoreValuesChanged(), Juniper.Animation.TransitionControllerTests.ExitStartsAtOne(), Juniper.Animation.TransitionControllerTests.SetEnabled(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntDeactivate(), Juniper.Animation.TransitionControllerTests.SetEnabledStartsAtZero(), Juniper.Animation.TransitionControllerTests.SetUp(), and Juniper.Animation.TransitionControllerTests.TearDown().
trans
MockTransition Juniper.Animation.TransitionControllerTests.trans private
Definition at line 324 of file TransitionControllerTests.cs.
Referenced by Juniper.Animation.TransitionControllerTests.Enter(), Juniper.Animation.TransitionControllerTests.EnterActivatesObject(), Juniper.Animation.TransitionControllerTests.EnterCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.EnterDoesntDisable(), Juniper.Animation.TransitionControllerTests.EnterDoesntFireExited(), Juniper.Animation.TransitionControllerTests.EnterDoesntFireExiting(), Juniper.Animation.TransitionControllerTests.EnterEnablesObject(), Juniper.Animation.TransitionControllerTests.EnterEndsAtOne(), Juniper.Animation.TransitionControllerTests.EnterEndsWithMoreValuesChanged(), Juniper.Animation.TransitionControllerTests.EnterFiresEntered(), Juniper.Animation.TransitionControllerTests.EnterFiresEntering(), Juniper.Animation.TransitionControllerTests.EnterStartsAtZero(), Juniper.Animation.TransitionControllerTests.EnterStartsValueChanged(), Juniper.Animation.TransitionControllerTests.Exit(), Juniper.Animation.TransitionControllerTests.ExitCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.ExitDisabledDoesntChangeValue(), Juniper.Animation.TransitionControllerTests.ExitDisables(), Juniper.Animation.TransitionControllerTests.ExitDoesntCompleteRightAway(), Juniper.Animation.TransitionControllerTests.ExitDoesntEnable(), Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntered(), Juniper.Animation.TransitionControllerTests.ExitDoesntFireEntering(), Juniper.Animation.TransitionControllerTests.ExitEndsAtZero(), Juniper.Animation.TransitionControllerTests.ExitEndsWithMoreValuesChanged(), Juniper.Animation.TransitionControllerTests.ExitFiresExited(), Juniper.Animation.TransitionControllerTests.ExitFiresExiting(), Juniper.Animation.TransitionControllerTests.ExitStartsAtOne(), Juniper.Animation.TransitionControllerTests.SetEnabled(), Juniper.Animation.TransitionControllerTests.SetEnabledCompletesAsynchronously(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntDisable(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntFireExited(), Juniper.Animation.TransitionControllerTests.SetEnabledDoesntFireExiting(), Juniper.Animation.TransitionControllerTests.SetEnabledEndsAtOne(), Juniper.Animation.TransitionControllerTests.SetEnabledFiresEntered(), Juniper.Animation.TransitionControllerTests.SetEnabledFiresEntering(), Juniper.Animation.TransitionControllerTests.SetEnabledStartsAtZero(), Juniper.Animation.TransitionControllerTests.SetUp(), and Juniper.Animation.TransitionControllerTests.TearDown().
TRANS_START_VALUE
const float Juniper.Animation.TransitionControllerTests.TRANS_START_VALUE = 0.5f private
Definition at line 320 of file TransitionControllerTests.cs.
Referenced by Juniper.Animation.TransitionControllerTests.ExitDisabledDoesntChangeValue(), and Juniper.Animation.TransitionControllerTests.SetUp().
TRANS_TIME
const float Juniper.Animation.TransitionControllerTests.TRANS_TIME = 0.2f private
Definition at line 319 of file TransitionControllerTests.cs.
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Tests/Juniper/Animation/TransitionControllerTests.cs