Juniper: Juniper.Widgets.LoadingBar Class Reference
Juniper.Widgets.LoadingBar Class Reference
Public Member Functions
void SetProgress (float progress, string status=null)
void Awake ()
void Update ()
Static Public Member Functions
static PooledComponent< LoadingBar > Ensure (Transform parent)
Properties
float Progress [get, private set]
float TargetValue [get, set]
WaitUntil Waiter [get]
Private Attributes
Transform indicator
WaitUntil _waiter
Detailed Description
Definition at line 6 of file LoadingBar.cs.
Member Function Documentation
Awake()
void Juniper.Widgets.LoadingBar.Awake ()
Ensure()
static PooledComponent<LoadingBar> Juniper.Widgets.LoadingBar.Ensure (Transform parent) static
Referenced by Juniper.MasterSceneController.Install().
SetProgress()
void Juniper.Widgets.LoadingBar.SetProgress (float progress, string status = null)
Implements Juniper.Progress.IProgressReceiver.
Referenced by Juniper.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
Update()
void Juniper.Widgets.LoadingBar.Update () inline
Definition at line 36 of file LoadingBar.cs.
         {
             Progress = Mathf.Lerp(Progress, TargetValue, 0.1f);
             var s = indicator.transform.localScale;
             s.x = Progress;
             indicator.transform.localScale = s;
             indicator.transform.localPosition = new Vector3(0.5f * (Progress - 1), 0, 0);
         }
References Juniper.Widgets.LoadingBar.indicator, Juniper.Widgets.LoadingBar.Progress, and Juniper.Widgets.LoadingBar.TargetValue.
Member Data Documentation
_waiter
WaitUntil Juniper.Widgets.LoadingBar._waiter private
Definition at line 50 of file LoadingBar.cs.
indicator
Transform Juniper.Widgets.LoadingBar.indicator private
Definition at line 45 of file LoadingBar.cs.
Referenced by Juniper.Widgets.LoadingBar.Update().
Property Documentation
Progress
float Juniper.Widgets.LoadingBar.Progress get private set
Definition at line 47 of file LoadingBar.cs.
 { get; private set; }
Referenced by Juniper.Widgets.LoadingBar.Update().
TargetValue
float Juniper.Widgets.LoadingBar.TargetValue get set
Definition at line 48 of file LoadingBar.cs.
 { get; set; }
Referenced by Juniper.Widgets.LoadingBar.Update().
Waiter
WaitUntil Juniper.Widgets.LoadingBar.Waiter get
Definition at line 53 of file LoadingBar.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(this.IsComplete);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.MasterSceneController.LoadingCompleteCoroutine().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Unity/Widgets/LoadingBar.cs