Juniper: Juniper.Haptics.ViveFocusHaptics Class Reference
Juniper.Haptics.ViveFocusHaptics Class Reference
Public Member Functions
override void Cancel ()
Cancel vibrationa
override void Play (HapticExpression expr)
Play a canned haptic pattern.
override void Play (params HapticPatternElement[] points)
Play a haptic pattern.
override void Play (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
override void Play (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
override void Vibrate (HapticPatternElement point)
Play a single element of a haptic pattern.
override void Vibrate (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
override void Vibrate (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
Protected Member Functions
override IEnumerator VibrateCoroutine (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
virtual IEnumerator VibrateCoroutine (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
virtual IEnumerator PlayCoroutine (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
virtual IEnumerator PlayCoroutine (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
Properties
WaveVR_Controller.Device Controller [get, set]
Detailed Description
Definition at line 10 of file ViveFocusHaptics.cs.
Member Function Documentation
Cancel()
override void Juniper.Haptics.AbstractHapticExpressor.Cancel () inline virtual inherited
Cancel vibrationa
Implements Juniper.Haptics.AbstractHapticDevice.
Reimplemented in Juniper.Haptics.WindowsMRHaptics, and Juniper.Haptics.DefaultHaptics.
Definition at line 14 of file AbstractHapticExpressor.cs.
         {
             StopAllCoroutines();
         }
Referenced by Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [1/4]
override void Juniper.Haptics.AbstractHapticExpressor.Play (HapticExpression expr) inline virtual inherited
Play a canned haptic pattern.
Parameters
expr
Implements Juniper.Haptics.AbstractHapticDevice.
Reimplemented in Juniper.Haptics.WindowsMRHaptics.
Definition at line 23 of file AbstractHapticExpressor.cs.
         {
             HapticPatternElement.Play(this, expr);
         }
References Juniper.Haptics.HapticPatternElement.Play().
Play() [2/4]
override void Juniper.Haptics.AbstractHapticExpressor.Play (params HapticPatternElement [] points) inline virtual inherited
Play a haptic pattern.
Parameters
points
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 32 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(points));
         }
References Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [3/4]
override void Juniper.Haptics.AbstractHapticExpressor.Play (long [] pattern) inline virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 59 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern));
         }
References Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [4/4]
override void Juniper.Haptics.AbstractHapticExpressor.Play (long [] pattern, float [] amplitudes) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 69 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern, amplitudes));
         }
References Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine().
PlayCoroutine() [1/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern) inline protected virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Definition at line 97 of file AbstractHapticExpressor.cs.
         {
             float amplitude = 1;
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitude);
                 amplitude = 1 - amplitude;
             }
         }
References Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Referenced by Juniper.Haptics.AbstractHapticExpressor.Play().
PlayCoroutine() [2/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern, float [] amplitudes) inline protected virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Definition at line 112 of file AbstractHapticExpressor.cs.
         {
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitudes[i]);
             }
         }
References Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [1/3]
override void Juniper.Haptics.AbstractHapticExpressor.Vibrate (HapticPatternElement point) inline virtual inherited
Play a single element of a haptic pattern.
Parameters
point
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 41 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(point));
         }
References Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [2/3]
override void Juniper.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds) inline virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 50 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds));
         }
References Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [3/3]
override void Juniper.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds, float amplitude) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 79 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds, amplitude));
         }
References Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
VibrateCoroutine() [1/2]
override IEnumerator Juniper.Haptics.ViveFocusHaptics.VibrateCoroutine (long milliseconds, float amplitude) inline protected virtual
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Haptics.AbstractHapticExpressor.
Definition at line 14 of file ViveFocusHaptics.cs.
         {
             var amp = Mathf.Clamp(Mathf.RoundToInt(amplitude * 5), 0, 5);
             if (amp > 0)
             {
                 Controller?.TriggerHapticPulse(
                     (ushort)(milliseconds * 1000),
                     WVR_InputId.WVR_InputId_Alias1_Trigger);
             }
             yield return new WaitForSeconds(0.001f * milliseconds);
         }
References Juniper.Haptics.ViveFocusHaptics.Controller.
VibrateCoroutine() [2/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine (long milliseconds) inline protected virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Definition at line 88 of file AbstractHapticExpressor.cs.
         {
             yield return VibrateCoroutine(milliseconds, 1);
         }
Referenced by Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine(), Juniper.Haptics.AbstractHapticExpressor.Vibrate(), and Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Property Documentation
Controller
WaveVR_Controller.Device Juniper.Haptics.ViveFocusHaptics.Controller get set
Definition at line 12 of file ViveFocusHaptics.cs.
 { get; set; }
Referenced by Juniper.Haptics.ViveFocusHaptics.VibrateCoroutine().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Platforms/ViveFocus/ViveFocusHaptics.cs