Juniper: Hjg.Pngcs.Zlib.CRC32 Class Reference
Hjg.Pngcs.Zlib.CRC32 Class Reference
Public Member Functions
CRC32 ()
CRC32 (uint polynomial, uint seed)
void Update (byte[] buffer)
void Update (byte[] buffer, int start, int length)
uint GetValue ()
void Reset ()
Static Private Member Functions
static uint [] InitializeTable (uint polynomial)
Private Attributes
const uint defaultPolynomial = 0xedb88320
const uint defaultSeed = 0xffffffff
uint hash
readonly uint seed
readonly uint [] table
Static Private Attributes
static uint [] defaultTable
Detailed Description
Definition at line 3 of file CRC32.cs.
Constructor & Destructor Documentation
CRC32() [1/2]
Hjg.Pngcs.Zlib.CRC32.CRC32 () inline
Definition at line 13 of file CRC32.cs.
             : this(defaultPolynomial, defaultSeed)
         {
         }
CRC32() [2/2]
Hjg.Pngcs.Zlib.CRC32.CRC32 (uint polynomial, uint seed) inline
Definition at line 18 of file CRC32.cs.
         {
             table = InitializeTable(polynomial);
             this.seed = seed;
             hash = seed;
         }
References Hjg.Pngcs.Zlib.CRC32.hash, Hjg.Pngcs.Zlib.CRC32.InitializeTable(), Hjg.Pngcs.Zlib.CRC32.seed, and Hjg.Pngcs.Zlib.CRC32.table.
Member Function Documentation
GetValue()
uint Hjg.Pngcs.Zlib.CRC32.GetValue () inline
Definition at line 51 of file CRC32.cs.
         {
             return ~hash;
         }
References Hjg.Pngcs.Zlib.CRC32.hash.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext().
InitializeTable()
static uint [] Hjg.Pngcs.Zlib.CRC32.InitializeTable (uint polynomial) inline static private
Definition at line 61 of file CRC32.cs.
         {
             if (polynomial == defaultPolynomial && defaultTable is object)
             {
                 return defaultTable;
             }
             var createTable = new uint[256];
             for (var i = 0; i < 256; i++)
             {
                 var entry = (uint)i;
                 for (var j = 0; j < 8; j++)
                 {
                     if ((entry & 1) == 1)
                     {
                         entry = (entry >> 1) ^ polynomial;
                     }
                     else
                     {
                         entry >>= 1;
                     }
                 }
                 createTable[i] = entry;
             }
             if (polynomial == defaultPolynomial)
             {
                 defaultTable = createTable;
             }
             return createTable;
         }
References Hjg.Pngcs.Zlib.CRC32.defaultPolynomial, and Hjg.Pngcs.Zlib.CRC32.defaultTable.
Referenced by Hjg.Pngcs.Zlib.CRC32.CRC32().
Reset()
void Hjg.Pngcs.Zlib.CRC32.Reset () inline
Definition at line 56 of file CRC32.cs.
         {
             hash = seed;
         }
References Hjg.Pngcs.Zlib.CRC32.hash, and Hjg.Pngcs.Zlib.CRC32.seed.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext().
Update() [1/2]
void Hjg.Pngcs.Zlib.CRC32.Update (byte [] buffer) inline
Definition at line 25 of file CRC32.cs.
         {
             if (buffer is null)
             {
                 throw new System.ArgumentNullException(nameof(buffer));
             }
             Update(buffer, 0, buffer.Length);
         }
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
Update() [2/2]
void Hjg.Pngcs.Zlib.CRC32.Update (byte [] buffer, int start, int length) inline
Definition at line 35 of file CRC32.cs.
         {
             if (buffer is null)
             {
                 throw new System.ArgumentNullException(nameof(buffer));
             }
             for (int i = 0, j = start; i < length; i++, j++)
             {
                 unchecked
                 {
                     hash = (hash >> 8) ^ table[buffer[j] ^ (hash & 0xff)];
                 }
             }
         }
References Hjg.Pngcs.Zlib.CRC32.hash, and Hjg.Pngcs.Zlib.CRC32.table.
Member Data Documentation
defaultPolynomial
const uint Hjg.Pngcs.Zlib.CRC32.defaultPolynomial = 0xedb88320 private
Definition at line 5 of file CRC32.cs.
Referenced by Hjg.Pngcs.Zlib.CRC32.InitializeTable().
defaultSeed
const uint Hjg.Pngcs.Zlib.CRC32.defaultSeed = 0xffffffff private
Definition at line 6 of file CRC32.cs.
defaultTable
uint [] Hjg.Pngcs.Zlib.CRC32.defaultTable static private
Definition at line 7 of file CRC32.cs.
Referenced by Hjg.Pngcs.Zlib.CRC32.InitializeTable().
hash
uint Hjg.Pngcs.Zlib.CRC32.hash private
Definition at line 9 of file CRC32.cs.
Referenced by Hjg.Pngcs.Zlib.CRC32.CRC32(), Hjg.Pngcs.Zlib.CRC32.GetValue(), Hjg.Pngcs.Zlib.CRC32.Reset(), and Hjg.Pngcs.Zlib.CRC32.Update().
seed
readonly uint Hjg.Pngcs.Zlib.CRC32.seed private
Definition at line 10 of file CRC32.cs.
Referenced by Hjg.Pngcs.Zlib.CRC32.CRC32(), and Hjg.Pngcs.Zlib.CRC32.Reset().
table
readonly uint [] Hjg.Pngcs.Zlib.CRC32.table private
Definition at line 11 of file CRC32.cs.
Referenced by Hjg.Pngcs.Zlib.CRC32.CRC32(), and Hjg.Pngcs.Zlib.CRC32.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Zlib/CRC32.cs