Juniper: Hjg.Pngcs.PngDeinterlacer Class Reference
Hjg.Pngcs.PngDeinterlacer Class Reference
Private Member Functions
internal PngDeinterlacer (ImageInfo iminfo)
internal void SetRow (int n)
internal void SetPass (int p)
internal void DeinterlaceInt (int[] src, int[] dst, bool readInPackedFormat)
void DeinterlaceIntPacked (int[] src, int[] dst)
internal void DeinterlaceByte (byte[] src, byte[] dst, bool readInPackedFormat)
void DeinterlacePackedByte (byte[] src, byte[] dst)
internal bool IsAtLastRow ()
internal int GetCurrRowSubimg ()
internal int GetCurrRowReal ()
internal int GetPass ()
internal int GetRows ()
internal int GetCols ()
internal int GetPixelsToRead ()
internal int [][] GetImageInt ()
internal void SetImageInt (int[][] imageInt)
internal byte [][] GetImageByte ()
internal void SetImageByte (byte[][] imageByte)
Private Attributes
readonly ImageInfo imi
int pass
int rows
int cols
int dY
int dX
int oY
int oX
int oXsamples
int dXsamples
int currRowSubimg = -1
int currRowReal = -1
readonly int packedValsPerPixel
readonly int packedMask
readonly int packedShift
int [][] imageInt
byte [][] imageByte
Detailed Description
Definition at line 3 of file PngDeinterlacer.cs.
Constructor & Destructor Documentation
PngDeinterlacer()
internal Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer (ImageInfo iminfo) inline private
Definition at line 21 of file PngDeinterlacer.cs.
         {
             imi = iminfo;
             pass = 0;
             if (imi.Packed)
             {
                 packedValsPerPixel = 8 / imi.BitDepth;
                 packedShift = imi.BitDepth;
                 if (imi.BitDepth == 1)
                 {
                     packedMask = 0x80;
                 }
                 else if (imi.BitDepth == 2)
                 {
                     packedMask = 0xc0;
                 }
                 else
                 {
                     packedMask = 0xf0;
                 }
             }
             else
             {
                 packedMask = packedShift = packedValsPerPixel = 1;// dont care
             }
             SetPass(1);
             SetRow(0);
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.PngDeinterlacer.imi, Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.PngDeinterlacer.packedMask, Hjg.Pngcs.PngDeinterlacer.packedShift, Hjg.Pngcs.PngDeinterlacer.packedValsPerPixel, Hjg.Pngcs.PngDeinterlacer.pass, Hjg.Pngcs.PngDeinterlacer.SetPass(), and Hjg.Pngcs.PngDeinterlacer.SetRow().
Member Function Documentation
DeinterlaceByte()
internal void Hjg.Pngcs.PngDeinterlacer.DeinterlaceByte (byte [] src, byte [] dst, bool readInPackedFormat) inline private
Definition at line 202 of file PngDeinterlacer.cs.
         {
             if (!(imi.Packed && readInPackedFormat))
             {
                 for (int i = 0, j = oXsamples; i < cols * imi.Channels; i += imi.Channels, j += dXsamples)
                 {
                     for (var k = 0; k < imi.Channels; k++)
                     {
                         dst[j + k] = src[i + k];
                     }
                 }
             }
             else
             {
                 DeinterlacePackedByte(src, dst);
             }
         }
References Hjg.Pngcs.ImageInfo.Channels, Hjg.Pngcs.PngDeinterlacer.cols, Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte(), Hjg.Pngcs.PngDeinterlacer.dXsamples, Hjg.Pngcs.PngDeinterlacer.imi, Hjg.Pngcs.PngDeinterlacer.oXsamples, and Hjg.Pngcs.ImageInfo.Packed.
Referenced by Hjg.Pngcs.PngReader.ReadRowsByte().
DeinterlaceInt()
internal void Hjg.Pngcs.PngDeinterlacer.DeinterlaceInt (int [] src, int [] dst, bool readInPackedFormat) inline private
Definition at line 143 of file PngDeinterlacer.cs.
         {
             if (!(imi.Packed && readInPackedFormat))
             {
                 for (int i = 0, j = oXsamples; i < cols * imi.Channels; i += imi.Channels, j += dXsamples)
                 {
                     for (var k = 0; k < imi.Channels; k++)
                     {
                         dst[j + k] = src[i + k];
                     }
                 }
             }
             else
             {
                 DeinterlaceIntPacked(src, dst);
             }
         }
References Hjg.Pngcs.ImageInfo.Channels, Hjg.Pngcs.PngDeinterlacer.cols, Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked(), Hjg.Pngcs.PngDeinterlacer.dXsamples, Hjg.Pngcs.PngDeinterlacer.imi, Hjg.Pngcs.PngDeinterlacer.oXsamples, and Hjg.Pngcs.ImageInfo.Packed.
Referenced by Hjg.Pngcs.PngReader.ReadRowsInt().
DeinterlaceIntPacked()
void Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked (int [] src, int [] dst) inline private
Definition at line 162 of file PngDeinterlacer.cs.
         {
             int spos, smod, smask; // source byte position, bits to shift to left (01,2,3,4
             int tpos, tmod, p, d;
             smask = packedMask;
             smod = -1;
             // can this really work?
             for (int i = 0, j = oX; i < cols; i++, j += dX)
             {
                 spos = i / packedValsPerPixel;
                 ++smod;
                 if (smod >= packedValsPerPixel)
                 {
                     smod = 0;
                 }
                 smask >>= packedShift; // the source mask cycles
                 if (smod == 0)
                 {
                     smask = packedMask;
                 }
                 tpos = j / packedValsPerPixel;
                 tmod = j % packedValsPerPixel;
                 p = src[spos] & smask;
                 d = tmod - smod;
                 if (d > 0)
                 {
                     p >>= (d * packedShift);
                 }
                 else if (d < 0)
                 {
                     p <<= ((-d) * packedShift);
                 }
                 dst[tpos] |= p;
             }
         }
References Hjg.Pngcs.PngDeinterlacer.cols, Hjg.Pngcs.PngDeinterlacer.dX, Hjg.Pngcs.PngDeinterlacer.oX, Hjg.Pngcs.PngDeinterlacer.packedMask, Hjg.Pngcs.PngDeinterlacer.packedShift, and Hjg.Pngcs.PngDeinterlacer.packedValsPerPixel.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceInt().
DeinterlacePackedByte()
void Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte (byte [] src, byte [] dst) inline private
Definition at line 220 of file PngDeinterlacer.cs.
         {
             int spos, smod, smask; // source byte position, bits to shift to left (01,2,3,4
             int tpos, tmod, p, d;
             // what the heck are you reading here? I told you would not enjoy this. Try Dostoyevsky or Simone Weil instead
             smask = packedMask;
             smod = -1;
             // Arrays.fill(dst, 0);
             for (int i = 0, j = oX; i < cols; i++, j += dX)
             {
                 spos = i / packedValsPerPixel;
                 ++smod;
                 if (smod >= packedValsPerPixel)
                 {
                     smod = 0;
                 }
                 smask >>= packedShift; // the source mask cycles
                 if (smod == 0)
                 {
                     smask = packedMask;
                 }
                 tpos = j / packedValsPerPixel;
                 tmod = j % packedValsPerPixel;
                 p = src[spos] & smask;
                 d = tmod - smod;
                 if (d > 0)
                 {
                     p >>= (d * packedShift);
                 }
                 else if (d < 0)
                 {
                     p <<= ((-d) * packedShift);
                 }
                 dst[tpos] |= (byte)p;
             }
         }
References Hjg.Pngcs.PngDeinterlacer.cols, Hjg.Pngcs.PngDeinterlacer.dX, Hjg.Pngcs.PngDeinterlacer.oX, Hjg.Pngcs.PngDeinterlacer.packedMask, Hjg.Pngcs.PngDeinterlacer.packedShift, and Hjg.Pngcs.PngDeinterlacer.packedValsPerPixel.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceByte().
GetCols()
internal int Hjg.Pngcs.PngDeinterlacer.GetCols () inline private
How many columns (pixels) are there in the current row
Definition at line 309 of file PngDeinterlacer.cs.
         {
             return cols;
         }
References Hjg.Pngcs.PngDeinterlacer.cols.
Referenced by Hjg.Pngcs.PngDeinterlacer.GetPixelsToRead().
GetCurrRowReal()
internal int Hjg.Pngcs.PngDeinterlacer.GetCurrRowReal () inline private
current row number inside the "real image"
Definition at line 282 of file PngDeinterlacer.cs.
         {
             return currRowReal;
         }
References Hjg.Pngcs.PngDeinterlacer.currRowReal.
Referenced by Hjg.Pngcs.PngReader.ReadRowsByte(), and Hjg.Pngcs.PngReader.ReadRowsInt().
GetCurrRowSubimg()
internal int Hjg.Pngcs.PngDeinterlacer.GetCurrRowSubimg () inline private
current row number inside the "sub image"
Definition at line 273 of file PngDeinterlacer.cs.
         {
             return currRowSubimg;
         }
References Hjg.Pngcs.PngDeinterlacer.currRowSubimg.
Referenced by Hjg.Pngcs.PngReader.ReadRowRaw().
GetImageByte()
internal byte [][] Hjg.Pngcs.PngDeinterlacer.GetImageByte () inline private
Definition at line 329 of file PngDeinterlacer.cs.
         {
             return imageByte;
         }
References Hjg.Pngcs.PngDeinterlacer.imageByte.
Referenced by Hjg.Pngcs.PngReader.ReadRowByte().
GetImageInt()
internal int [][] Hjg.Pngcs.PngDeinterlacer.GetImageInt () inline private
Definition at line 319 of file PngDeinterlacer.cs.
         {
             return imageInt;
         }
References Hjg.Pngcs.PngDeinterlacer.imageInt.
Referenced by Hjg.Pngcs.PngReader.ReadRowInt().
GetPass()
internal int Hjg.Pngcs.PngDeinterlacer.GetPass () inline private
current pass number (1-7)
Definition at line 291 of file PngDeinterlacer.cs.
         {
             return pass;
         }
References Hjg.Pngcs.PngDeinterlacer.pass.
GetPixelsToRead()
internal int Hjg.Pngcs.PngDeinterlacer.GetPixelsToRead () inline private
Definition at line 314 of file PngDeinterlacer.cs.
         {
             return GetCols();
         }
References Hjg.Pngcs.PngDeinterlacer.GetCols().
Referenced by Hjg.Pngcs.PngReader.ReadRowRaw().
GetRows()
internal int Hjg.Pngcs.PngDeinterlacer.GetRows () inline private
How many rows has the current pass?
Definition at line 300 of file PngDeinterlacer.cs.
         {
             return rows;
         }
References Hjg.Pngcs.PngDeinterlacer.rows.
Referenced by Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.ReadRowsByte(), and Hjg.Pngcs.PngReader.ReadRowsInt().
IsAtLastRow()
internal bool Hjg.Pngcs.PngDeinterlacer.IsAtLastRow () inline private
Is current row the last row for the lass pass??
Definition at line 264 of file PngDeinterlacer.cs.
         {
             return pass == 7 && currRowSubimg == rows - 1;
         }
References Hjg.Pngcs.PngDeinterlacer.currRowSubimg, Hjg.Pngcs.PngDeinterlacer.pass, and Hjg.Pngcs.PngDeinterlacer.rows.
Referenced by Hjg.Pngcs.PngReader.ReadRowRaw().
SetImageByte()
internal void Hjg.Pngcs.PngDeinterlacer.SetImageByte (byte imageByte[][]) inline private
Definition at line 334 of file PngDeinterlacer.cs.
         {
             this.imageByte = imageByte;
         }
References Hjg.Pngcs.PngDeinterlacer.imageByte.
Referenced by Hjg.Pngcs.PngReader.ReadRowByte().
SetImageInt()
internal void Hjg.Pngcs.PngDeinterlacer.SetImageInt (int imageInt[][]) inline private
Definition at line 324 of file PngDeinterlacer.cs.
         {
             this.imageInt = imageInt;
         }
References Hjg.Pngcs.PngDeinterlacer.imageInt.
Referenced by Hjg.Pngcs.PngReader.ReadRowInt().
SetPass()
internal void Hjg.Pngcs.PngDeinterlacer.SetPass (int p) inline private
Definition at line 63 of file PngDeinterlacer.cs.
         {
             if (pass == p)
             {
                 return;
             }
             pass = p;
             switch (pass)
             {
                 case 1:
                 dY = dX = 8;
                 oX = oY = 0;
                 break;
                 case 2:
                 dY = dX = 8;
                 oX = 4;
                 oY = 0;
                 break;
                 case 3:
                 dX = 4;
                 dY = 8;
                 oX = 0;
                 oY = 4;
                 break;
                 case 4:
                 dX = dY = 4;
                 oX = 2;
                 oY = 0;
                 break;
                 case 5:
                 dX = 2;
                 dY = 4;
                 oX = 0;
                 oY = 2;
                 break;
                 case 6:
                 dX = dY = 2;
                 oX = 1;
                 oY = 0;
                 break;
                 case 7:
                 dX = 1;
                 dY = 2;
                 oX = 0;
                 oY = 1;
                 break;
                 default:
                 throw new PngjInternalException("bad interlace pass" + pass);
             }
             rows = ((imi.Rows - oY) / dY) + 1;
             if (((rows - 1) * dY) + oY >= imi.Rows)
             {
                 rows--; // can be 0
             }
             cols = ((imi.Cols - oX) / dX) + 1;
             if (((cols - 1) * dX) + oX >= imi.Cols)
             {
                 cols--; // can be 0
             }
             if (cols == 0)
             {
                 rows = 0; // really...
             }
             dXsamples = dX * imi.Channels;
             oXsamples = oX * imi.Channels;
         }
References Hjg.Pngcs.ImageInfo.Channels, Hjg.Pngcs.PngDeinterlacer.cols, Hjg.Pngcs.ImageInfo.Cols, Hjg.Pngcs.PngDeinterlacer.dX, Hjg.Pngcs.PngDeinterlacer.dXsamples, Hjg.Pngcs.PngDeinterlacer.dY, Hjg.Pngcs.PngDeinterlacer.imi, Hjg.Pngcs.PngDeinterlacer.oX, Hjg.Pngcs.PngDeinterlacer.oXsamples, Hjg.Pngcs.PngDeinterlacer.oY, Hjg.Pngcs.PngDeinterlacer.pass, Hjg.Pngcs.PngDeinterlacer.rows, and Hjg.Pngcs.ImageInfo.Rows.
Referenced by Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer(), Hjg.Pngcs.PngReader.ReadRowsByte(), and Hjg.Pngcs.PngReader.ReadRowsInt().
SetRow()
internal void Hjg.Pngcs.PngDeinterlacer.SetRow (int n) inline private
this refers to the row currRowSubimg
Definition at line 53 of file PngDeinterlacer.cs.
         {
             currRowSubimg = n;
             currRowReal = (n * dY) + oY;
             if (currRowReal < 0 || currRowReal >= imi.Rows)
             {
                 throw new PngjInternalException("bad row - this should not happen");
             }
         }
References Hjg.Pngcs.PngDeinterlacer.currRowReal, Hjg.Pngcs.PngDeinterlacer.currRowSubimg, Hjg.Pngcs.PngDeinterlacer.dY, Hjg.Pngcs.PngDeinterlacer.imi, Hjg.Pngcs.PngDeinterlacer.oY, and Hjg.Pngcs.ImageInfo.Rows.
Referenced by Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer(), and Hjg.Pngcs.PngReader.ReadRowRaw().
Member Data Documentation
cols
int Hjg.Pngcs.PngDeinterlacer.cols private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceByte(), Hjg.Pngcs.PngDeinterlacer.DeinterlaceInt(), Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked(), Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte(), Hjg.Pngcs.PngDeinterlacer.GetCols(), and Hjg.Pngcs.PngDeinterlacer.SetPass().
currRowReal
int Hjg.Pngcs.PngDeinterlacer.currRowReal = -1 private
Definition at line 13 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.GetCurrRowReal(), and Hjg.Pngcs.PngDeinterlacer.SetRow().
currRowSubimg
int Hjg.Pngcs.PngDeinterlacer.currRowSubimg = -1 private
Definition at line 10 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.GetCurrRowSubimg(), Hjg.Pngcs.PngDeinterlacer.IsAtLastRow(), and Hjg.Pngcs.PngDeinterlacer.SetRow().
dX
int Hjg.Pngcs.PngDeinterlacer.dX private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked(), Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte(), and Hjg.Pngcs.PngDeinterlacer.SetPass().
dXsamples
int Hjg.Pngcs.PngDeinterlacer.dXsamples private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceByte(), Hjg.Pngcs.PngDeinterlacer.DeinterlaceInt(), and Hjg.Pngcs.PngDeinterlacer.SetPass().
dY
int Hjg.Pngcs.PngDeinterlacer.dY private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.SetPass(), and Hjg.Pngcs.PngDeinterlacer.SetRow().
imageByte
byte [][] Hjg.Pngcs.PngDeinterlacer.imageByte private
Definition at line 19 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.GetImageByte(), and Hjg.Pngcs.PngDeinterlacer.SetImageByte().
imageInt
int [][] Hjg.Pngcs.PngDeinterlacer.imageInt private
Definition at line 18 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.GetImageInt(), and Hjg.Pngcs.PngDeinterlacer.SetImageInt().
imi
readonly ImageInfo Hjg.Pngcs.PngDeinterlacer.imi private
Definition at line 5 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceByte(), Hjg.Pngcs.PngDeinterlacer.DeinterlaceInt(), Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer(), Hjg.Pngcs.PngDeinterlacer.SetPass(), and Hjg.Pngcs.PngDeinterlacer.SetRow().
oX
int Hjg.Pngcs.PngDeinterlacer.oX private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked(), Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte(), and Hjg.Pngcs.PngDeinterlacer.SetPass().
oXsamples
int Hjg.Pngcs.PngDeinterlacer.oXsamples private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceByte(), Hjg.Pngcs.PngDeinterlacer.DeinterlaceInt(), and Hjg.Pngcs.PngDeinterlacer.SetPass().
oY
int Hjg.Pngcs.PngDeinterlacer.oY private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.SetPass(), and Hjg.Pngcs.PngDeinterlacer.SetRow().
packedMask
readonly int Hjg.Pngcs.PngDeinterlacer.packedMask private
Definition at line 16 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked(), Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte(), and Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer().
packedShift
readonly int Hjg.Pngcs.PngDeinterlacer.packedShift private
Definition at line 17 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked(), Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte(), and Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer().
packedValsPerPixel
readonly int Hjg.Pngcs.PngDeinterlacer.packedValsPerPixel private
Definition at line 15 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.DeinterlaceIntPacked(), Hjg.Pngcs.PngDeinterlacer.DeinterlacePackedByte(), and Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer().
pass
int Hjg.Pngcs.PngDeinterlacer.pass private
Definition at line 6 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.GetPass(), Hjg.Pngcs.PngDeinterlacer.IsAtLastRow(), Hjg.Pngcs.PngDeinterlacer.PngDeinterlacer(), and Hjg.Pngcs.PngDeinterlacer.SetPass().
rows
int Hjg.Pngcs.PngDeinterlacer.rows private
Definition at line 7 of file PngDeinterlacer.cs.
Referenced by Hjg.Pngcs.PngDeinterlacer.GetRows(), Hjg.Pngcs.PngDeinterlacer.IsAtLastRow(), and Hjg.Pngcs.PngDeinterlacer.SetPass().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/PngDeinterlacer.cs