Juniper: Juniper.Unity.World.LightEstimation.AbstractLightMeasurement Class Reference
Juniper.Unity.World.LightEstimation.AbstractLightMeasurement Class Reference
Public Member Functions
virtual void Awake ()
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
virtual void Reinstall ()
void Reset ()
virtual bool Install (bool reset)
virtual void Uninstall ()
void Update ()
Check to see if the ARCore light estimation has been updated.
Public Attributes
bool useFake
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
float Intensity = 0.8f
The fake intensity value to use if UseFakeIntensity is true.
Color Color = Color.white
The fake color to use if UseFakeIntensity is true.
bool DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Protected Member Functions
virtual void UpdateMeasurement ()
virtual void PrintDebugReport ()
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Protected Attributes
float lastIntensity
Light estimate updates happen concurrently with frame updates. This value stores the last light intesity measurement that was calculated, for use in the current render frame.
Color lastColor
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
Properties
virtual bool UseFakeIntensity [get]
Returns true if the user has requested a fake intensity, or the application is running in the Unity Editor.
Color ColorEstimate [get]
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
float IntensityEstimate [get]
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Private Member Functions
void SetFakeValues ()
Sets the current Intensity and Color from the fake values set in the Unity Editor.
Detailed Description
Definition at line 7 of file AbstractLightMeasurement.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Awake () inline virtual
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
Reimplemented in Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.
Definition at line 87 of file AbstractLightMeasurement.cs.
         {
             Install(false);
             SetFakeValues();
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Install(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
Install()
virtual bool Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Install (bool reset) inline virtual
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.
Definition at line 108 of file AbstractLightMeasurement.cs.
         {
             reset &= Application.isEditor;
             return true;
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Awake(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reinstall().
PrintDebugReport()
virtual void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport () inline protected virtual
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Reimplemented in Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.
Definition at line 155 of file AbstractLightMeasurement.cs.
         {
             if (UseFakeIntensity)
             {
                 ScreenDebugger.Print("Using fake light estimate");
             }
             ScreenDebugger.PrintFormat("  Raw: int {0:0.000} col {1}", IntensityEstimate, ColorEstimate);
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.ColorEstimate, Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.IntensityEstimate, System.ScreenDebugger.Print(), System.ScreenDebugger.PrintFormat(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UseFakeIntensity.
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update().
Reinstall()
virtual void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reinstall () inline virtual
Implements Juniper.IInstallable.
Definition at line 94 of file AbstractLightMeasurement.cs.
         {
             Install(true);
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Install().
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reset().
Reset()
void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reset () inline
Definition at line 101 of file AbstractLightMeasurement.cs.
         {
             Reinstall();
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reinstall().
SetFakeValues()
void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues () inline private
Sets the current Intensity and Color from the fake values set in the Unity Editor.
Definition at line 121 of file AbstractLightMeasurement.cs.
         {
             lastIntensity = Intensity;
             lastColor = Color.Scale(lastIntensity);
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Color, Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Intensity, Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastColor, and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastIntensity.
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Awake(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update().
Uninstall()
virtual void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Uninstall () inline virtual
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.
Definition at line 114 of file AbstractLightMeasurement.cs.
         {
         }
Update()
void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update () inline
Check to see if the ARCore light estimation has been updated.
Definition at line 130 of file AbstractLightMeasurement.cs.
         {
             if (UseFakeIntensity)
             {
                 SetFakeValues();
             }
             else
             {
                 UpdateMeasurement();
             }
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.DebugReport, Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues(), Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UpdateMeasurement(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UseFakeIntensity.
UpdateMeasurement()
virtual void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UpdateMeasurement () inline protected virtual
Definition at line 147 of file AbstractLightMeasurement.cs.
         {
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update().
Member Data Documentation
Color
Color Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Color = Color.white
The fake color to use if UseFakeIntensity is true.
Definition at line 50 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetAveragePixelIntensity(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
DebugReport
bool Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Definition at line 55 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update().
Intensity
float Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Intensity = 0.8f
The fake intensity value to use if UseFakeIntensity is true.
Definition at line 45 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
lastColor
Color Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastColor protected
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
Definition at line 21 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetAveragePixelIntensity(), Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.InternalUpdate(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
lastIntensity
float Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastIntensity protected
Light estimate updates happen concurrently with frame updates. This value stores the last light intesity measurement that was calculated, for use in the current render frame.
Definition at line 15 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetAveragePixelIntensity(), Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.InternalUpdate(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
useFake
bool Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.useFake
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
Definition at line 27 of file AbstractLightMeasurement.cs.
Property Documentation
ColorEstimate
Color Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.ColorEstimate get
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light color estimate.
Definition at line 63 of file AbstractLightMeasurement.cs.
         {
             get
             {
                 return lastColor;
             }
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.Unity.World.LightEstimation.AbstractLightEstimate.Update().
IntensityEstimate
float Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.IntensityEstimate get
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light intensity estimate.
Definition at line 76 of file AbstractLightMeasurement.cs.
         {
             get
             {
                 return lastIntensity;
             }
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.Unity.World.LightEstimation.AbstractLightEstimate.Update().
UseFakeIntensity
virtual bool Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UseFakeIntensity get protected
Returns true if the user has requested a fake intensity, or the application is running in the Unity Editor.
true if use fake intensity; otherwise, false.
Definition at line 35 of file AbstractLightMeasurement.cs.
         {
             get
             {
                 return useFake || Application.isEditor;
             }
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/World/LightEstimation/AbstractLightMeasurement.cs