Juniper: Juniper.Unity.Widgets.TeleportPad Class Reference
Juniper.Unity.Widgets.TeleportPad Class Reference
Public Member Functions
virtual void OnPointerClick (PointerEventData eventData)
Trigger the onClick/Click events, if they are valid.
void OnLongPress (PointerEventData evt)
void OnLongPressUpdate (PointerEventData evt)
void SetDisabled (bool value)
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
void ToggleEnabled ()
Toggles the boolean value of the disabled field.
virtual void OnPointerEnter (PointerEventData eventData)
Reqct to the pointer hovering over the control.
virtual void OnPointerExit (PointerEventData eventData)
React to the pointer leaving the control and no longer hovering over it.
virtual void OnPointerDown (PointerEventData eventData)
React to the primary button being pressed on the control.
virtual void OnPointerUp (PointerEventData eventData)
React to the primary button being released from the control.
Public Attributes
UnityEvent onClick
The event to call when the button is enabled and clicked. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr Click.
UnityEvent onLongPress
InputButton clickButton
The button we are expecting to use to interact with this object.
bool disabled
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occuring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Vector3 pointerPosition
The place near the control that the pointer was pointing.
Static Public Attributes
static string [] PART_NAMES
The names of the animation states that Touchable expects.
Protected Member Functions
override void OnClick ()
Trigger the onClick/click events, if they are valid;
virtual void OnLongPress ()
virtual void Awake ()
Get the Rigidbody, AbstractAnimator, AudioSource, and InteractionAudio for this control.
virtual void Update ()
Update the physics state of the control, and enable/disable Disabled view on DisabledChanged.
virtual void LateUpdate ()
Saves the state of the flags from the current frame to have them for the next frame.
string ShowState (string enabledPart)
Trigger the animation or swap the gameObjects to show the current control UI state.
void GetPosition (PointerEventData eventData)
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Protected Attributes
Vector3 lastPointerPosition
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
Properties
bool IsDisabled [get, set]
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
bool PointerPositionChanged [get]
Returns true when pointerPosition has changed since the last frame.
Events
EventHandler Click
The event to call when the button is enabled and clicked. You should only use this verison if you are programmatically attaching event listenters. if you are using the Unity Editor, you should prefer onClick.
EventHandler LongPress
Private Member Functions
void Start ()
void Darth_Entered (object sender, System.EventArgs e)
Private Attributes
Transform userT
FadeTransition darth
bool running
Detailed Description
Definition at line 7 of file TeleportPad.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Widgets.AbstractTouchable.Awake () inline protected virtual inherited
Get the Rigidbody, AbstractAnimator, AudioSource, and InteractionAudio for this control.
Reimplemented in Juniper.Unity.Widgets.AbstractValued, Juniper.Unity.Widgets.Openable, and Juniper.Unity.Widgets.Rotatable.
Definition at line 161 of file AbstractTouchable.cs.
         {
             animator = AbstractAnimator.GetAnimator(gameObject, PART_NAMES);
         }
References Juniper.Unity.Widgets.AbstractTouchable.animator, Juniper.Unity.Animation.AbstractAnimator.GetAnimator(), and Juniper.Unity.Widgets.AbstractTouchable.PART_NAMES.
Darth_Entered()
void Juniper.Unity.Widgets.TeleportPad.Darth_Entered (object sender, System.EventArgs e) inline private
Definition at line 37 of file TeleportPad.cs.
         {
             if (running)
             {
                 running = false;
                 if (userT != null)
                 {
                     userT.position = transform.position + 2 * Vector3.up;
 #if UNITY_MODULES_PHYSICS
                     if (user != null)
                     {
                         user.isKinematic = true;
                         user.position = userT.position;
                         user.velocity = Vector3.zero;
                         user.isKinematic = false;
                     }
 #endif
                 }
                 darth.Exit();
             }
         }
References Juniper.Unity.Widgets.TeleportPad.darth, Juniper.Unity.Animation.AbstractTransitionController.Exit(), Juniper.Unity.Widgets.TeleportPad.running, and Juniper.Unity.Widgets.TeleportPad.userT.
Referenced by Juniper.Unity.Widgets.TeleportPad.Start().
GetPosition()
void Juniper.Unity.Widgets.AbstractTouchable.GetPosition (PointerEventData eventData) inline protected inherited
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Parameters
eventData Event data.
Definition at line 219 of file AbstractTouchable.cs.
         {
             pointerPosition = eventData.pointerCurrentRaycast.worldPosition;
             eventData.Use();
         }
References Juniper.Unity.Widgets.AbstractTouchable.pointerPosition.
Referenced by Juniper.Unity.Widgets.AbstractValued.OnBeginDrag(), Juniper.Unity.Widgets.AbstractValued.OnDrag(), Juniper.Unity.Widgets.AbstractValued.OnEndDrag(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Unity.Widgets.AbstractTouchable.OnPointerUp().
LateUpdate()
virtual void Juniper.Unity.Widgets.AbstractTouchable.LateUpdate () inline protected virtual inherited
Saves the state of the flags from the current frame to have them for the next frame.
Reimplemented in Juniper.Unity.Widgets.AbstractValued, Juniper.Unity.Widgets.Draggable, and Juniper.Unity.Widgets.Openable.
Definition at line 184 of file AbstractTouchable.cs.
         {
             wasDisabled = IsDisabled;
             lastPointerPosition = pointerPosition;
         }
References Juniper.Unity.Widgets.AbstractTouchable.IsDisabled, Juniper.Unity.Widgets.AbstractTouchable.lastPointerPosition, Juniper.Unity.Widgets.AbstractTouchable.pointerPosition, and Juniper.Unity.Widgets.AbstractTouchable.wasDisabled.
OnClick()
override void Juniper.Unity.Widgets.TeleportPad.OnClick () inline protected virtual
Trigger the onClick/click events, if they are valid;
Reimplemented from Juniper.Unity.Widgets.Clickable.
Definition at line 9 of file TeleportPad.cs.
         {
             if (!running)
             {
                 running = true;
                 base.OnClick();
                 darth.Enter();
             }
         }
References Juniper.Unity.Widgets.TeleportPad.darth, Juniper.Unity.Animation.AbstractTransitionController.Enter(), and Juniper.Unity.Widgets.TeleportPad.running.
OnLongPress() [1/2]
void Juniper.Unity.Widgets.Clickable.OnLongPress (PointerEventData evt) inline inherited
Implements Juniper.Unity.Events.ILongPressHandler.
Definition at line 60 of file Clickable.cs.
         {
             if (evt.button == clickButton && !IsDisabled)
             {
                 OnLongPress();
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.clickButton, Juniper.Unity.Widgets.AbstractTouchable.IsDisabled, and Juniper.Unity.Widgets.Clickable.OnLongPress().
OnLongPress() [2/2]
virtual void Juniper.Unity.Widgets.Clickable.OnLongPress () inline protected virtual inherited
Definition at line 68 of file Clickable.cs.
         {
             onLongPress?.Invoke();
             LongPress?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Unity.Widgets.Clickable.LongPress, and Juniper.Unity.Widgets.Clickable.onLongPress.
Referenced by Juniper.Unity.Widgets.Clickable.OnLongPress().
OnLongPressUpdate()
void Juniper.Unity.Widgets.Clickable.OnLongPressUpdate (PointerEventData evt) inline inherited
Implements Juniper.Unity.Events.ILongPressHandler.
Definition at line 74 of file Clickable.cs.
         {
             if (evt.button == clickButton && !IsDisabled)
             {
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.clickButton, and Juniper.Unity.Widgets.AbstractTouchable.IsDisabled.
OnPointerClick()
virtual void Juniper.Unity.Widgets.Clickable.OnPointerClick (PointerEventData eventData) inline virtual inherited
Trigger the onClick/Click events, if they are valid.
Parameters
eventData
Reimplemented in Juniper.Unity.Widgets.Openable.
Definition at line 43 of file Clickable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 OnClick();
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.clickButton, Juniper.Unity.Widgets.AbstractTouchable.IsDisabled, and Juniper.Unity.Widgets.Clickable.OnClick().
OnPointerDown()
virtual void Juniper.Unity.Widgets.AbstractTouchable.OnPointerDown (PointerEventData eventData) inline virtual inherited
React to the primary button being pressed on the control.
Parameters
eventData Event data.
Definition at line 255 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton)
             {
                 if (IsDisabled)
                 {
                     ShowState("Disabled");
                 }
                 else
                 {
                     GetPosition(eventData);
                     ShowState("Pressed");
                 }
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.clickButton, Juniper.Unity.Widgets.AbstractTouchable.GetPosition(), Juniper.Unity.Widgets.AbstractTouchable.IsDisabled, and Juniper.Unity.Widgets.AbstractTouchable.ShowState().
OnPointerEnter()
virtual void Juniper.Unity.Widgets.AbstractTouchable.OnPointerEnter (PointerEventData eventData) inline virtual inherited
Reqct to the pointer hovering over the control.
Parameters
eventData Event data.
Definition at line 229 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.clickButton, Juniper.Unity.Widgets.AbstractTouchable.GetPosition(), Juniper.Unity.Widgets.AbstractTouchable.IsDisabled, and Juniper.Unity.Widgets.AbstractTouchable.ShowState().
OnPointerExit()
virtual void Juniper.Unity.Widgets.AbstractTouchable.OnPointerExit (PointerEventData eventData) inline virtual inherited
React to the pointer leaving the control and no longer hovering over it.
Parameters
eventData Event data.
Definition at line 242 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Normal");
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.clickButton, Juniper.Unity.Widgets.AbstractTouchable.GetPosition(), Juniper.Unity.Widgets.AbstractTouchable.IsDisabled, and Juniper.Unity.Widgets.AbstractTouchable.ShowState().
OnPointerUp()
virtual void Juniper.Unity.Widgets.AbstractTouchable.OnPointerUp (PointerEventData eventData) inline virtual inherited
React to the primary button being released from the control.
Parameters
eventData Event data.
Definition at line 275 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.clickButton, Juniper.Unity.Widgets.AbstractTouchable.GetPosition(), Juniper.Unity.Widgets.AbstractTouchable.IsDisabled, and Juniper.Unity.Widgets.AbstractTouchable.ShowState().
SetDisabled()
void Juniper.Unity.Widgets.AbstractTouchable.SetDisabled (bool value) inline inherited
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
Parameters
value
Definition at line 121 of file AbstractTouchable.cs.
         {
             IsDisabled = value;
         }
References Juniper.Unity.Widgets.AbstractTouchable.IsDisabled.
ShowState()
string Juniper.Unity.Widgets.AbstractTouchable.ShowState (string enabledPart) inline protected inherited
Trigger the animation or swap the gameObjects to show the current control UI state.
Returns
The state.
Parameters
enabledPart Enabled part.
Definition at line 207 of file AbstractTouchable.cs.
         {
             enabledPart = NormalizePart(enabledPart);
             animator?.Play(enabledPart);
             return enabledPart;
         }
References Juniper.Unity.Widgets.AbstractTouchable.animator, Juniper.Unity.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Unity.Animation.AbstractAnimator.Play().
Referenced by Juniper.Unity.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Unity.Widgets.Openable.SetOpen(), and Juniper.Unity.Widgets.AbstractTouchable.Update().
Start()
void Juniper.Unity.Widgets.TeleportPad.Start () inline private
Definition at line 26 of file TeleportPad.cs.
         {
             running = false;
             userT = ComponentExt.FindAny<StageExtensions>().transform;
 #if UNITY_MODULES_PHYSICS
             user = userT.GetComponent<Rigidbody>();
 #endif
             darth = ComponentExt.FindAny<FadeTransition>();
             darth.Entered += Darth_Entered;
         }
References Juniper.Unity.Widgets.TeleportPad.darth, Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), Juniper.Unity.AbstractStateController.Entered, Juniper.Unity.Widgets.TeleportPad.running, and Juniper.Unity.Widgets.TeleportPad.userT.
ToggleEnabled()
void Juniper.Unity.Widgets.AbstractTouchable.ToggleEnabled () inline inherited
Toggles the boolean value of the disabled field.
Definition at line 129 of file AbstractTouchable.cs.
         {
             IsDisabled = !IsDisabled;
         }
References Juniper.Unity.Widgets.AbstractTouchable.IsDisabled.
Update()
virtual void Juniper.Unity.Widgets.AbstractTouchable.Update () inline protected virtual inherited
Update the physics state of the control, and enable/disable Disabled view on DisabledChanged.
Reimplemented in Juniper.Unity.Widgets.Rotatable, and Juniper.Unity.Widgets.Openable.
Definition at line 169 of file AbstractTouchable.cs.
         {
             if (DisabledDown)
             {
                 ShowState(PART_NAMES.Last());
             }
             else if (DisabledUp)
             {
                 ShowState(PART_NAMES[0]);
             }
         }
References Juniper.Unity.Widgets.AbstractTouchable.DisabledDown, Juniper.Unity.Widgets.AbstractTouchable.DisabledUp, Juniper.Unity.Widgets.AbstractTouchable.PART_NAMES, and Juniper.Unity.Widgets.AbstractTouchable.ShowState().
Referenced by Juniper.Unity.Widgets.AbstractValued.SetValue().
Member Data Documentation
clickButton
InputButton Juniper.Unity.Widgets.AbstractTouchable.clickButton inherited
The button we are expecting to use to interact with this object.
Definition at line 43 of file AbstractTouchable.cs.
Referenced by Juniper.Unity.Widgets.AbstractValued.OnBeginDrag(), Juniper.Unity.Widgets.AbstractValued.OnDrag(), Juniper.Unity.Widgets.AbstractValued.OnEndDrag(), Juniper.Unity.Widgets.Clickable.OnLongPress(), Juniper.Unity.Widgets.Clickable.OnLongPressUpdate(), Juniper.Unity.Widgets.Clickable.OnPointerClick(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Unity.Widgets.AbstractTouchable.OnPointerUp().
darth
FadeTransition Juniper.Unity.Widgets.TeleportPad.darth private
Definition at line 23 of file TeleportPad.cs.
Referenced by Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), Juniper.Unity.Widgets.TeleportPad.OnClick(), and Juniper.Unity.Widgets.TeleportPad.Start().
disabled
bool Juniper.Unity.Widgets.AbstractTouchable.disabled inherited
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occuring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Definition at line 56 of file AbstractTouchable.cs.
lastPointerPosition
Vector3 Juniper.Unity.Widgets.AbstractTouchable.lastPointerPosition protected inherited
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
Definition at line 143 of file AbstractTouchable.cs.
Referenced by Juniper.Unity.Widgets.AbstractTouchable.LateUpdate(), and Juniper.Unity.Widgets.AbstractValued.OnDrag().
onClick
UnityEvent Juniper.Unity.Widgets.Clickable.onClick inherited
The event to call when the button is enabled and clicked. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr Click.
Definition at line 26 of file Clickable.cs.
Referenced by Juniper.Unity.Widgets.Clickable.OnClick().
onLongPress
UnityEvent Juniper.Unity.Widgets.Clickable.onLongPress inherited
Definition at line 28 of file Clickable.cs.
Referenced by Juniper.Unity.Widgets.Clickable.OnLongPress().
PART_NAMES
string [] Juniper.Unity.Widgets.AbstractTouchable.PART_NAMES static inherited
Initial value:
=
        {
            "Normal",
            "Hovered",
            "Pressed",
            "Opened",
            "Disabled"
        }
The names of the animation states that Touchable expects.
Definition at line 31 of file AbstractTouchable.cs.
Referenced by Juniper.Unity.Widgets.AbstractTouchable.Awake(), Juniper.Unity.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Unity.Widgets.AbstractTouchable.Update().
pointerPosition
Vector3 Juniper.Unity.Widgets.AbstractTouchable.pointerPosition inherited
The place near the control that the pointer was pointing.
Definition at line 137 of file AbstractTouchable.cs.
Referenced by Juniper.Unity.Widgets.AbstractTouchable.GetPosition(), Juniper.Unity.Widgets.AbstractTouchable.LateUpdate(), Juniper.Unity.Widgets.AbstractValued.OnBeginDrag(), and Juniper.Unity.Widgets.AbstractValued.OnDrag().
running
bool Juniper.Unity.Widgets.TeleportPad.running private
Definition at line 24 of file TeleportPad.cs.
Referenced by Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), Juniper.Unity.Widgets.TeleportPad.OnClick(), and Juniper.Unity.Widgets.TeleportPad.Start().
userT
Transform Juniper.Unity.Widgets.TeleportPad.userT private
Definition at line 19 of file TeleportPad.cs.
Referenced by Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Property Documentation
IsDisabled
bool Juniper.Unity.Widgets.AbstractTouchable.IsDisabled get set inherited
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
Definition at line 104 of file AbstractTouchable.cs.
         {
             get
             {
                 return !isActiveAndEnabled || disabled;
             }
             set
             {
                 disabled = value;
             }
         }
Referenced by Juniper.Unity.Widgets.AbstractTouchable.LateUpdate(), Juniper.Unity.Widgets.Rotatable.OnBeginDrag(), Juniper.Unity.Widgets.AbstractValued.OnBeginDrag(), Juniper.Unity.Widgets.Rotatable.OnDrag(), Juniper.Unity.Widgets.Draggable.OnDrag(), Juniper.Unity.Widgets.AbstractValued.OnDrag(), Juniper.Unity.Widgets.AbstractValued.OnEndDrag(), Juniper.Unity.Widgets.Clickable.OnLongPress(), Juniper.Unity.Widgets.Clickable.OnLongPressUpdate(), Juniper.Unity.Widgets.Clickable.OnPointerClick(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Unity.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Unity.Widgets.AbstractTouchable.SetDisabled(), Juniper.Unity.Widgets.Openable.SetOpen(), Juniper.Unity.Widgets.AbstractTouchable.ToggleEnabled(), and Juniper.Unity.Widgets.Rotatable.Update().
PointerPositionChanged
bool Juniper.Unity.Widgets.AbstractTouchable.PointerPositionChanged get protected inherited
Returns true when pointerPosition has changed since the last frame.
true if pointer position changed; otherwise, false.
Definition at line 150 of file AbstractTouchable.cs.
         {
             get
             {
                 return pointerPosition != lastPointerPosition;
             }
         }
Event Documentation
Click
EventHandler Juniper.Unity.Widgets.Clickable.Click inherited
The event to call when the button is enabled and clicked. You should only use this verison if you are programmatically attaching event listenters. if you are using the Unity Editor, you should prefer onClick.
Definition at line 35 of file Clickable.cs.
Referenced by Juniper.Unity.Widgets.Clickable.OnClick().
LongPress
EventHandler Juniper.Unity.Widgets.Clickable.LongPress inherited
Definition at line 37 of file Clickable.cs.
Referenced by Juniper.Unity.Widgets.Clickable.OnLongPress().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/TeleportPad.cs