Juniper: Juniper.IO.ZipFileCacheLayer Class Reference
Juniper.IO.ZipFileCacheLayer Class Reference
Public Member Functions
ZipFileCacheLayer (FileInfo zipFile)
ZipFileCacheLayer (string fileName)
bool IsCached (ContentReference fileRef)
Task< Stream > GetStreamAsync (ContentReference fileRef, IProgress prog)
IEnumerable< ContentReference > GetContentReferences (MediaType ofType)
Private Member Functions
string GetCacheFileName (ContentReference fileRef)
Private Attributes
internal readonly FileInfo zipFile
readonly Dictionary< string, bool > filesExist = new Dictionary<string, bool>()
Detailed Description
Definition at line 12 of file ZipFileCacheLayer.cs.
Constructor & Destructor Documentation
ZipFileCacheLayer() [1/2]
Juniper.IO.ZipFileCacheLayer.ZipFileCacheLayer (FileInfo zipFile) inline
Definition at line 18 of file ZipFileCacheLayer.cs.
         {
             if (zipFile is null)
             {
                 throw new ArgumentNullException(nameof(zipFile));
             }
             if (!zipFile.Exists)
             {
                 throw new FileNotFoundException("ZipFileCacheLayer: No zip file! " + zipFile.FullName);
             }
             this.zipFile = zipFile;
         }
References Juniper.IO.ZipFileCacheLayer.zipFile.
ZipFileCacheLayer() [2/2]
Juniper.IO.ZipFileCacheLayer.ZipFileCacheLayer (string fileName) inline
Definition at line 33 of file ZipFileCacheLayer.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             zipFile = new FileInfo(fileName);
             if (!zipFile.Exists)
             {
                 throw new FileNotFoundException("ZipFileCacheLayer: No zip file! " + zipFile.FullName);
             }
         }
References Juniper.IO.ZipFileCacheLayer.zipFile.
Member Function Documentation
GetCacheFileName()
string Juniper.IO.ZipFileCacheLayer.GetCacheFileName (ContentReference fileRef) inline private
Definition at line 53 of file ZipFileCacheLayer.cs.
         {
             var baseName = fileRef.CacheID.Replace('\\', '/');
             var cacheFileName = fileRef.ContentType.AddExtension(baseName);
             return cacheFileName;
         }
References Juniper.MediaType.AddExtension(), Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
Referenced by Juniper.IO.ZipFileCacheLayer.GetStreamAsync(), and Juniper.IO.ZipFileCacheLayer.IsCached().
GetContentReferences()
IEnumerable<ContentReference> Juniper.IO.ZipFileCacheLayer.GetContentReferences (MediaType ofType) inline
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 103 of file ZipFileCacheLayer.cs.
         {
             if (ofType is null)
             {
                 throw new ArgumentNullException(nameof(ofType));
             }
             foreach (var file in Decompressor.Entries(zipFile).Files())
             {
                 if (ofType.Matches(file.FullName))
                 {
                     var cacheID = PathExt.RemoveShortExtension(file.FullName);
                     yield return cacheID + ofType;
                 }
             }
         }
References Juniper.Compression.Zip.Decompressor.Entries(), System.IO.PathExt.RemoveShortExtension(), and Juniper.IO.ZipFileCacheLayer.zipFile.
GetStreamAsync()
Task<Stream> Juniper.IO.ZipFileCacheLayer.GetStreamAsync (ContentReference fileRef, IProgress prog) inline
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 86 of file ZipFileCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             Stream stream = null;
             if (IsCached(fileRef))
             {
                 var cacheFileName = GetCacheFileName(fileRef);
                 stream = Decompressor.GetFile(zipFile, cacheFileName);
             }
             return Task.FromResult(stream);
         }
References Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), Juniper.Compression.Zip.Decompressor.GetFile(), Juniper.IO.ZipFileCacheLayer.IsCached(), and Juniper.IO.ZipFileCacheLayer.zipFile.
IsCached()
bool Juniper.IO.ZipFileCacheLayer.IsCached (ContentReference fileRef) inline
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 60 of file ZipFileCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             if (!filesExist.ContainsKey(fileRef.CacheID))
             {
                 if (zipFile.Exists)
                 {
                     var cacheFileName = GetCacheFileName(fileRef);
                     using var zip = Decompressor.Open(zipFile);
                     var entry = zip.GetEntry(cacheFileName);
                     filesExist[fileRef.CacheID] = entry is object;
                 }
                 else
                 {
                     filesExist[fileRef.CacheID] = false;
                 }
             }
             return filesExist.ContainsKey(fileRef.CacheID)
                 && filesExist[fileRef.CacheID];
         }
References Juniper.IO.ContentReference.CacheID, Juniper.IO.ZipFileCacheLayer.filesExist, Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), Juniper.Compression.Zip.Decompressor.Open(), and Juniper.IO.ZipFileCacheLayer.zipFile.
Referenced by Juniper.IO.ZipFileCacheLayer.GetStreamAsync().
Member Data Documentation
filesExist
readonly Dictionary<string, bool> Juniper.IO.ZipFileCacheLayer.filesExist = new Dictionary<string, bool>() private
Definition at line 16 of file ZipFileCacheLayer.cs.
Referenced by Juniper.IO.ZipFileCacheLayer.IsCached().
zipFile
internal readonly FileInfo Juniper.IO.ZipFileCacheLayer.zipFile private
Definition at line 14 of file ZipFileCacheLayer.cs.
Referenced by Juniper.IO.ZipFileCacheLayer.GetContentReferences(), Juniper.IO.ZipFileCacheLayer.GetStreamAsync(), Juniper.IO.ZipFileCacheLayer.IsCached(), and Juniper.IO.ZipFileCacheLayer.ZipFileCacheLayer().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Compression/Zip/ZipFileCacheLayer.cs