Juniper: BitMiracle.LibJpeg.Classic.JpegDecompressStruct Class Reference
BitMiracle.LibJpeg.Classic.JpegDecompressStruct Class Reference
JPEG decompression routine.
Public Member Functions
delegate bool JpegMarkerParserMethod (JpegDecompressStruct cinfo)
The delegate for application-supplied marker processing methods.
JpegDecompressStruct ()
Initializes a new instance of the JpegDecompressStruct class.
JpegDecompressStruct (JpegErrorMessage errorManager)
Initializes a new instance of the JpegDecompressStruct class.
void JpegStdioSrc (Stream infile)
Sets input stream.
ReadResult JpegReadHeader (bool require_image)
Decompression startup: this will read the source datastream header markers, up to the beginning of the compressed data proper.
bool JpegStartDecompress ()
Decompression initialization.
int JpegReadScanlines (byte[][] scanlines, int max_lines)
Read some scanlines of data from the JPEG decompressor.
bool JpegFinishDecompress ()
Finish JPEG decompression.
int JpegReadRawData (byte[][][] data, int max_lines)
Alternate entry point to read raw data.
bool JpegHasMultipleScans ()
Is there more than one scan?
bool JpegStartOutput (int scan_number)
Initialize for an output pass in buffered-image mode.
bool JpegFinishOutput ()
Finish up after an output pass in buffered-image mode.
bool JpegInputComplete ()
Indicates if we have finished reading the input file.
ReadResult JpegConsumeInput ()
Consume data in advance of what the decompressor requires.
void JpegCalcOutputDimensions ()
Pre-calculate output image dimensions and related values for current decompression parameters.
JVirtArray< JBlock > [] JpegReadCoefficients ()
Read or write the raw DCT coefficient arrays from a JPEG file (useful for lossless transcoding).
void JpegCopyCriticalParameters (JpegCompressStruct dstinfo)
Initializes the compression object with default parameters, then copy from the source object all parameters needed for lossless transcoding.
void JpegAbortDecompress ()
Aborts processing of a JPEG decompression operation.
void JpegSetMarkerProcessor (int marker_code, JpegMarkerParserMethod routine)
Sets processor for special marker.
void JpegSaveMarkers (int marker_code, int length_limit)
Control saving of COM and APPn markers into Marker_list.
void JpegAbort ()
void JpegDestroy ()
void ErrExit (JMessageCode code)
Used for fatal errors (print message and exit).
void ErrExit (JMessageCode code, params object[] args)
Used for fatal errors (print message and exit).
void ErrExit (int code, params object[] args)
Used for fatal errors (print message and exit).
void WarnMS (JMessageCode code)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void WarnMS (JMessageCode code, params object[] args)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void WarnMS (int code, params object[] args)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void TraceMS (int lvl, JMessageCode code)
Shows informational and debugging messages.
void TraceMS (int lvl, JMessageCode code, params object[] args)
Shows informational and debugging messages.
void TraceMS (int lvl, int code, params object[] args)
Shows informational and debugging messages.
Static Public Member Functions
static JVirtArray< byte > CreateSamplesArray (int samplesPerRow, int numberOfRows)
Creates the array of samples.
static JVirtArray< JBlock > CreateBlocksArray (int blocksPerRow, int numberOfRows)
Creates the array of blocks.
static byte [][] AllocJpegSamples (int samplesPerRow, int numberOfRows)
Creates 2-D sample array.
Public Attributes
override bool IsDecompressor => true
Retrieves true because this is a decompressor.
int Image_width => imageWidth
Gets the width of image, set by JpegDecompressStruct.jpeg_read_header
int Image_height => imageHeight
Gets the height of image, set by JpegDecompressStruct.JpegReadHeader
int Num_components => numComponents
Gets the number of color components in JPEG image.
ReadOnlyCollection< JpegMarkerStruct > Marker_list => new ReadOnlyCollection<JpegMarkerStruct>(m_marker_list)
Gets the list of loaded special markers.
int Output_width => outputWidth
Gets the actual width of output image.
int Output_height => outputHeight
Gets the actual height of output image.
int Out_color_components => outColorComponents
Gets the number of color components in JpegDecompressStruct.Out_color_space.
int Output_components => outputComponents
Gets the number of color components returned.
int Rec_outbuf_height => recommendOutBufferHeight
Gets the recommended height of scanline buffer.
int Output_scanline => outputScanline
Gets the number of scanlines returned so far.
int Input_scan_number => inputScanNumber
Gets the number of SOS markers seen so far.
int Input_iMCU_row => inputIMcuRow
Gets the number of iMCU rows completed.
int Output_scan_number => outputScanNumber
Gets the nominal scan number being displayed.
int Output_iMCU_row => outputIMcuRow
Gets the number of iMCU rows read.
int [][] Coef_bits => coefBits
Gets the current progression status..
DensityUnit DensityUnit => m_densityUnit
Gets the resolution information from JFIF marker.
short XDensity => m_xDensity
Gets the horizontal component of pixel ratio.
short YDensity => m_yDensity
Gets the vertical component of pixel ratio.
int DataPrecision => m_dataPrecision
Gets the data precision.
int MaxVSampleFactor => m_maxVSampleFactor
Gets the largest vertical sample factor.
int UnreadMarker => m_unreadMarker
Gets the last read and unprocessed JPEG marker.
Static Public Attributes
static string Copyright => "Copyright (C) 2008-2018, Bit Miracle"
Gets the LibJpeg's copyright.
Properties
LibJpeg.Classic.JpegSourceManager Src [get, set]
Gets or sets the source for decompression.
LibJpeg.Classic.JColorSpace Jpeg_color_space [get, set]
Gets or sets the colorspace of JPEG image.
LibJpeg.Classic.JColorSpace Out_color_space [get, set]
Gets or sets the output color space.
int Scale_num [get, set]
Gets or sets the numerator of the fraction of image scaling.
int Scale_denom [get, set]
Gets or sets the denominator of the fraction of image scaling.
bool Buffered_image [get, set]
Gets or sets a value indicating whether to use buffered-image mode.
bool Raw_data_out [get, set]
Enable or disable raw data output.
LibJpeg.Classic.JDctMethod Dct_method [get, set]
Gets or sets the algorithm used for the DCT step.
bool Do_fancy_upsampling [get, set]
Enable or disable upsampling of chroma components.
bool Do_block_smoothing [get, set]
Apply interblock smoothing in early stages of decoding progressive JPEG files.
bool Quantize_colors [get, set]
Colors quantization.
LibJpeg.Classic.JDitherMode Dither_mode [get, set]
Selects color dithering method.
bool Two_pass_quantize [get, set]
Gets or sets a value indicating whether to use two-pass color quantization.
int Desired_number_of_colors [get, set]
Maximum number of colors to use in generating a library-supplied color map.
bool Enable_1pass_quant [get, set]
Enable future use of 1-pass quantizer.
bool Enable_external_quant [get, set]
Enable future use of external colormap.
bool Enable_2pass_quant [get, set]
Enable future use of 2-pass quantizer.
int ActualNumberOfColors [get, set]
The number of colors in the color map.
byte [][] Colormap [get, set]
The color map, represented as a 2-D pixel array of JpegDecompressStruct.Out_color_components rows and JpegDecompressStruct.ActualNumberOfColors columns.
JpegComponentInfo [] CompInfo [get, set]
Comp_info[i] describes component that appears i'th in SOF
JpegProgressManager?? Progress [get, set]
Progress monitor.
JpegErrorMessage?? Err [get, set]
Error handler module.
static string Version [get]
Gets the version of LibJpeg.
Private Member Functions
internal bool UseMergedUpSample ()
Determine whether merged upsample/color conversion should be used. CRUCIAL: this must match the actual capabilities of merged upsampler!
void Initialize ()
Initialization of JPEG compression objects. The error manager must already be set up (in case memory manager fails).
void TransdecodeMasterSelection ()
Master selection of decompression modules for transcoding (that is, reading raw DCT coefficient arrays from an input JPEG file.) This substitutes for initialization of the full decompressor.
bool OutputPassSetup ()
Set up for an output pass, and perform any dummy pass(es) needed. Common subroutine for jpeg_start_decompress and jpeg_start_output. Entry: global_state = DSTATE_PRESCAN only if previously suspended. Exit: If done, returns true and sets global_state for proper output mode. If suspended, returns false and sets global_state = DSTATE_PRESCAN.
void DefaultDecompressParams ()
Set default decompression parameters.
void JpegConsumeInputStart ()
ReadResult JpegConsumeInputInHeader ()
Private Attributes
internal JpegSourceManager m_src
internal int imageWidth
internal int imageHeight
internal int numComponents
internal JColorSpace jpegColorSpace
internal JColorSpace outColorSpace
internal int scaleNum
internal int scaleDenom
internal bool bufferedImage
internal bool rawDataOut
internal JDctMethod dctMethod
internal bool doFancyUpsampling
internal bool doBlockSmoothing
internal bool quantizeColors
internal JDitherMode ditherMode
internal bool twoPassQuantize
internal int desiredNumberOfColors
internal bool enable1PassQuant
internal bool enableExternalQuant
internal bool enable2PassQuant
internal int outputWidth
internal int outputHeight
internal int outColorComponents
internal int outputComponents
internal int recommendOutBufferHeight
internal int actualColorCount
internal byte [][] m_colormap
internal int outputScanline
internal int inputScanNumber
internal int inputIMcuRow
internal int outputScanNumber
internal int outputIMcuRow
internal int [][] coefBits
internal JQuantTable [] m_quant_tbl_ptrs = new JQuantTable[JpegConstants.NUM_QUANT_TBLS]
internal JHuffmanTable [] m_dc_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS]
internal JHuffmanTable [] m_ac_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS]
internal int m_dataPrecision
internal bool isBaseline
internal bool progressiveMode
internal bool arithCode
internal byte [] arithDcL = new byte[JpegConstants.NUM_ARITH_TBLS]
internal byte [] arithDcU = new byte[JpegConstants.NUM_ARITH_TBLS]
internal byte [] arithAcK = new byte[JpegConstants.NUM_ARITH_TBLS]
internal int m_restart_interval
internal bool m_saw_JFIF_marker
internal byte m_JFIF_major_version
internal byte m_JFIF_minor_version
internal DensityUnit m_densityUnit
internal short m_xDensity
internal short m_yDensity
internal bool m_saw_Adobe_marker
internal byte m_Adobe_transform
internal JColorTransform color_transform
internal bool m_CCIR601_sampling
internal List< JpegMarkerStruct > m_marker_list
internal int m_max_h_samp_factor
internal int m_maxVSampleFactor
internal int min_DCT_h_scaled_size
internal int min_DCT_v_scaled_size
internal int m_total_iMCU_rows
internal byte [] m_sample_range_limit
internal int m_sampleRangeLimitOffset
internal int m_comps_in_scan
internal int [] m_cur_comp_info = new int[JpegConstants.MAX_COMPS_IN_SCAN]
internal int m_MCUs_per_row
internal int m_MCU_rows_in_scan
internal int m_blocks_in_MCU
internal int [] m_MCU_membership = new int[JpegConstants.D_MAX_BLOCKS_IN_MCU]
internal int m_Ss
internal int m_Se
internal int m_Ah
internal int m_Al
internal int block_size
internal int [] natural_order
internal int lim_Se
internal int m_unreadMarker
internal JpegDecompMaster m_master
internal JpegDMainController m_main
internal JpegDCoefController m_coef
internal JpegDPostController m_post
internal JpegInputController m_inputctl
internal JpegMarkerReader m_marker
internal JpegEntropyDecoder m_entropy
internal JpegInverseDct m_idct
internal JpegUpSampler m_upsample
internal JpegColorDeconverter m_cconvert
internal IJpegColorQuantizer m_cquantize
Detailed Description
JPEG decompression routine.
See also
JpegCompressStruct
Definition at line 14 of file JpegDecompressStruct.cs.
Constructor & Destructor Documentation
JpegDecompressStruct() [1/2]
BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegDecompressStruct () inline
Initializes a new instance of the JpegDecompressStruct class.
See also
JpegCompressStruct
Definition at line 210 of file JpegDecompressStruct.cs.
         {
             Initialize();
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize().
JpegDecompressStruct() [2/2]
BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegDecompressStruct (JpegErrorMessage errorManager) inline
Initializes a new instance of the JpegDecompressStruct class.
Parameters
errorManager The error manager.
See also
JpegCompressStruct
Definition at line 220 of file JpegDecompressStruct.cs.
             : base(errorManager)
         {
             Initialize();
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize().
Member Function Documentation
AllocJpegSamples()
static byte [][] BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples (int samplesPerRow, int numberOfRows) inline static inherited
Creates 2-D sample array.
Parameters
samplesPerRow The number of samples per row.
numberOfRows The number of rows.
Returns
The array of samples.
Definition at line 158 of file JpegCommonStruct.cs.
         {
             var result = new byte[numberOfRows][];
             for (var i = 0; i < numberOfRows; ++i)
             {
                 result[i] = new byte[samplesPerRow];
             }
             return result;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColorIndex(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColormap(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateSamplesArray(), BitMiracle.LibJpeg.Jpeg.Decompress(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.JpegCMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), and BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler().
CreateBlocksArray()
static JVirtArray<JBlock> BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateBlocksArray (int blocksPerRow, int numberOfRows) inline static inherited
Creates the array of blocks.
Parameters
blocksPerRow The number of blocks in row.
numberOfRows The number of rows.
Returns
The array of blocks.
See also
JBlock
Definition at line 147 of file JpegCommonStruct.cs.
         {
             return new JVirtArray<JBlock>(blocksPerRow, numberOfRows, AllocJpegBlocks);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegBlocks().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.JpegDCoefController(), and BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.MyCCoefController().
CreateSamplesArray()
static JVirtArray<byte> BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateSamplesArray (int samplesPerRow, int numberOfRows) inline static inherited
Creates the array of samples.
Parameters
samplesPerRow The number of samples in row.
numberOfRows The number of rows.
Returns
The array of samples.
Definition at line 135 of file JpegCommonStruct.cs.
         {
             return new JVirtArray<byte>(samplesPerRow, numberOfRows, AllocJpegSamples);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController().
DefaultDecompressParams()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams () inline private
Set default decompression parameters.
Definition at line 1821 of file JpegDecompressStruct.cs.
         {
             /* Guess the input colorspace, and set output colorspace accordingly. */
             /* Note application may override our guesses. */
             switch (numComponents)
             {
                 case 1:
                 jpegColorSpace = JColorSpace.JCS_GRAYSCALE;
                 outColorSpace = JColorSpace.JCS_GRAYSCALE;
                 break;
                 case 3:
                 var cid0 = CompInfo[0].Component_id;
                 var cid1 = CompInfo[1].Component_id;
                 var cid2 = CompInfo[2].Component_id;
                 // Use Adobe marker info, otherwise try to guess from the component IDs
                 if (m_saw_Adobe_marker)
                 {
                     switch (m_Adobe_transform)
                     {
                         case 0:
                         jpegColorSpace = JColorSpace.JCS_RGB;
                         break;
                         case 1:
                         jpegColorSpace = JColorSpace.JCS_YCbCr;
                         break;
                         default:
                         WarnMS(JMessageCode.JWRN_ADOBE_XFORM, m_Adobe_transform);
                         /* assume it's YCbCr */
                         jpegColorSpace = JColorSpace.JCS_YCbCr;
                         break;
                     }
                 }
                 else if (cid0 == 0x01 && cid1 == 0x02 && cid2 == 0x03)
                 {
                     jpegColorSpace = JColorSpace.JCS_YCbCr;
                 }
                 else if (cid0 == 0x01 && cid1 == 0x22 && cid2 == 0x23)
                 {
                     jpegColorSpace = JColorSpace.JCS_BG_YCC;
                 }
                 else if (cid0 == 0x52 && cid1 == 0x47 && cid2 == 0x42)
                 {
                     /* ASCII 'R', 'G', 'B' */
                     jpegColorSpace = JColorSpace.JCS_RGB;
                 }
                 else if (cid0 == 0x72 && cid1 == 0x67 && cid2 == 0x62)
                 {
                     /* ASCII 'r', 'g', 'b' */
                     jpegColorSpace = JColorSpace.JCS_BG_RGB;
                 }
                 else if (m_saw_JFIF_marker)
                 {
                     /* assume it's YCbCr */
                     jpegColorSpace = JColorSpace.JCS_YCbCr;
                 }
                 else
                 {
                     TraceMS(1, JMessageCode.JTRC_UNKNOWN_IDS, cid0, cid1, cid2);
                     /* assume it's YCbCr */
                     jpegColorSpace = JColorSpace.JCS_YCbCr;
                 }
                 /* Always guess RGB is proper output colorspace. */
                 outColorSpace = JColorSpace.JCS_RGB;
                 break;
                 case 4:
                 if (m_saw_Adobe_marker)
                 {
                     switch (m_Adobe_transform)
                     {
                         case 0:
                         jpegColorSpace = JColorSpace.JCS_CMYK;
                         break;
                         case 2:
                         jpegColorSpace = JColorSpace.JCS_YCCK;
                         break;
                         default:
                         WarnMS(JMessageCode.JWRN_ADOBE_XFORM, m_Adobe_transform);
                         /* assume it's YCCK */
                         jpegColorSpace = JColorSpace.JCS_YCCK;
                         break;
                     }
                 }
                 else
                 {
                     /* No special markers, assume straight CMYK. */
                     jpegColorSpace = JColorSpace.JCS_CMYK;
                 }
                 outColorSpace = JColorSpace.JCS_CMYK;
                 break;
                 default:
                 jpegColorSpace = JColorSpace.JCS_UNKNOWN;
                 outColorSpace = JColorSpace.JCS_UNKNOWN;
                 break;
             }
             /* Set defaults for other decompression parameters. */
             scaleNum = block_size;       /* 1:1 scaling */
             scaleDenom = block_size;
             bufferedImage = false;
             rawDataOut = false;
             dctMethod = JpegConstants.JDCT_DEFAULT;
             doFancyUpsampling = true;
             doBlockSmoothing = true;
             quantizeColors = false;
             /* We set these in case application only sets quantize_colors. */
             ditherMode = JDitherMode.JDITHER_FS;
             twoPassQuantize = true;
             desiredNumberOfColors = 256;
             m_colormap = null;
             /* Initialize for no mode change in buffered-image mode. */
             enable1PassQuant = false;
             enableExternalQuant = false;
             enable2PassQuant = false;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.block_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_id, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.dctMethod, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.desiredNumberOfColors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.ditherMode, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.doBlockSmoothing, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.doFancyUpsampling, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable1PassQuant, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable2PassQuant, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enableExternalQuant, BitMiracle.LibJpeg.Classic.JpegConstants.JDCT_DEFAULT, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.jpegColorSpace, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Adobe_transform, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_colormap, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_Adobe_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_JFIF_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorSpace, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.rawDataOut, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.scaleDenom, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.scaleNum, BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.twoPassQuantize, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputInHeader().
ErrExit() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (JMessageCode code) inline inherited
Used for fatal errors (print message and exit).
Parameters
code The message code.
Definition at line 238 of file JpegCommonStruct.cs.
         {
             ErrExit((int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.JVirtArray< BitMiracle.LibJpeg.Classic.JBlock >.Access(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.AddHuffTable(), BitMiracle.LibJpeg.Classic.Internal.ArithEntropyDecoder.ArithEntropyDecoder(), BitMiracle.LibJpeg.Classic.Internal.ArithEntropyEncoder.ArithEntropyEncoder(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.ColorQuantize(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.ColorQuantize(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressData(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.MySourceManager.FillInputBuffer(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.Inverse(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMainController(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultColorspace(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct9x9(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegGenOptimalTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegHasMultipleScans(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct9x9(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegInputComplete(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.LatchQuantTables(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.My1PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.NewColorMap(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.SelectNColors(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.start_pass(), BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.UpSampleComponent(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader().
ErrExit() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (JMessageCode code, params object [] args) inline inherited
Used for fatal errors (print message and exit).
Parameters
code The message code.
args The parameters of message.
Definition at line 248 of file JpegCommonStruct.cs.
         {
             ErrExit((int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit().
ErrExit() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (int code, params object [] args) inline inherited
Used for fatal errors (print message and exit).
Parameters
code The message code.
args The parameters of message.
Definition at line 258 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.ErrorExit();
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.ErrorExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
Initialize()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize () inline private
Initialization of JPEG compression objects. The error manager must already be set up (in case memory manager fails).
Definition at line 1674 of file JpegDecompressStruct.cs.
         {
             /* Zero out pointers to permanent structures. */
             prog = null;
             m_src = null;
             for (var i = 0; i < JpegConstants.NUM_QUANT_TBLS; i++)
             {
                 m_quant_tbl_ptrs[i] = null;
             }
             for (var i = 0; i < JpegConstants.NUM_HUFF_TBLS; i++)
             {
                 m_dc_huff_tbl_ptrs[i] = null;
                 m_ac_huff_tbl_ptrs[i] = null;
             }
             /* Initialize marker processor so application can override methods
             * for COM, APPn markers before calling jpeg_read_header.
             */
             m_marker_list = new List<JpegMarkerStruct>();
             m_marker = new JpegMarkerReader(this);
             /* And initialize the overall input controller. */
             m_inputctl = new JpegInputController(this);
             /* OK, I'm ready */
             globalState = JpegState.DSTATE_START;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dc_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker_list, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegDecompressStruct().
JpegAbort()
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort () inline inherited
Abort processing of a JPEG compression or decompression operation, but don't destroy the object itself.
Closing a data source or destination, if necessary, is the application's responsibility.
Definition at line 198 of file JpegCommonStruct.cs.
         {
             /* Reset overall state for possible reuse of object */
             if (IsDecompressor)
             {
                 globalState = JpegState.DSTATE_START;
                 /* Try to keep application from accessing now-deleted marker list.
                  * A bit kludgy to do it here, but this is the most central place.
                  */
                 if (this is JpegDecompressStruct s)
                 {
                     s.m_marker_list = null;
                 }
             }
             else
             {
                 globalState = JpegState.CSTATE_START;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.IsDecompressor.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAbortCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegAbortDecompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader().
JpegAbortDecompress()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegAbortDecompress () inline
Aborts processing of a JPEG decompression operation.
See also
JpegCommonStruct.JpegAbort
Definition at line 1576 of file JpegDecompressStruct.cs.
         {
             JpegAbort();
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort().
JpegCalcOutputDimensions()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions () inline
Pre-calculate output image dimensions and related values for current decompression parameters.
This is allowed for possible use by application. Hence it mustn't do anything that can't be done twice. Also note that it may be called before the master module is initialized!
Definition at line 1248 of file JpegDecompressStruct.cs.
         {
             // Do computations that are needed before master selection phase
             // This function is used for full decompression.
             /* Prevent application from calling me at wrong times */
             if (globalState != JpegState.DSTATE_READY)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Compute core output image dimensions and DCT scaling choices. */
             m_inputctl.JpegCoreOutputDimensions();
             /* In selecting the actual DCT scaling for each component, we try to
             * scale up the chroma components via IDCT scaling rather than upsampling.
             * This saves time if the upsampler gets to use 1:1 scaling.
             * Note this code adapts subsampling ratios which are powers of 2.
             */
             for (var ci = 0; ci < numComponents; ci++)
             {
                 var ssize = 1;
                 var compptr = CompInfo[ci];
                 var upSampleSize = doFancyUpsampling
                     ? JpegConstants.DCTSIZE
                     : JpegConstants.DCTSIZE / 2;
                 while (min_DCT_h_scaled_size * ssize <= upSampleSize
                     && (m_max_h_samp_factor % (compptr.H_samp_factor * ssize * 2)) == 0)
                 {
                     ssize *= 2;
                 }
                 compptr.DCT_h_scaled_size = min_DCT_h_scaled_size * ssize;
                 ssize = 1;
                 while (min_DCT_v_scaled_size * ssize <= upSampleSize
                    && (m_maxVSampleFactor % (compptr.V_samp_factor * ssize * 2)) == 0)
                 {
                     ssize *= 2;
                 }
                 compptr.DCT_v_scaled_size = min_DCT_v_scaled_size * ssize;
                 /* We don't support IDCT ratios larger than 2. */
                 if (compptr.DCT_h_scaled_size > compptr.DCT_v_scaled_size * 2)
                 {
                     compptr.DCT_h_scaled_size = compptr.DCT_v_scaled_size * 2;
                 }
                 else if (compptr.DCT_v_scaled_size > compptr.DCT_h_scaled_size * 2)
                 {
                     compptr.DCT_v_scaled_size = compptr.DCT_h_scaled_size * 2;
                 }
             }
             /* Recompute downsampled dimensions of components;
             * application needs to know these if using raw downsampled data.
             */
             for (var ci = 0; ci < numComponents; ci++)
             {
                 /* Size in samples, after IDCT scaling */
                 CompInfo[ci].downsampled_width = (int)JpegUtils.jdiv_round_up(
                     imageWidth * CompInfo[ci].H_samp_factor * CompInfo[ci].DCT_h_scaled_size,
                     m_max_h_samp_factor * block_size);
                 CompInfo[ci].downsampled_height = (int)JpegUtils.jdiv_round_up(
                     imageHeight * CompInfo[ci].V_samp_factor * CompInfo[ci].DCT_v_scaled_size,
                     m_maxVSampleFactor * block_size);
             }
             /* Report number of components in selected colorspace. */
             /* Probably this should be in the color conversion module... */
             switch (outColorSpace)
             {
                 case JColorSpace.JCS_GRAYSCALE:
                 outColorComponents = 1;
                 break;
                 case JColorSpace.JCS_RGB:
                 case JColorSpace.JCS_BG_RGB:
                 outColorComponents = JpegConstants.RGB_PIXELSIZE;
                 break;
                 case JColorSpace.JCS_YCbCr:
                 case JColorSpace.JCS_BG_YCC:
                 outColorComponents = 3;
                 break;
                 case JColorSpace.JCS_CMYK:
                 case JColorSpace.JCS_YCCK:
                 outColorComponents = 4;
                 break;
                 default:
                 /* else must be same colorspace as in file */
                 outColorComponents = numComponents;
                 break;
             }
             if (quantizeColors)
             {
                 outputComponents = 1;
             }
             else
             {
                 outputComponents = outColorComponents;
             }
             /* See if upsampler will want to emit more than one row at a time */
             if (UseMergedUpSample())
             {
                 recommendOutBufferHeight = m_maxVSampleFactor;
             }
             else
             {
                 recommendOutBufferHeight = 1;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.block_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegComponentInfo.DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.doFancyUpsampling, BitMiracle.LibJpeg.Classic.JpegComponentInfo.downsampled_height, BitMiracle.LibJpeg.Classic.JpegComponentInfo.downsampled_width, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegComponentInfo.H_samp_factor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageWidth, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jdiv_round_up(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_max_h_samp_factor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_maxVSampleFactor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorSpace, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.recommendOutBufferHeight, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample(), and BitMiracle.LibJpeg.Classic.JpegComponentInfo.V_samp_factor.
Referenced by BitMiracle.LibJpeg.Jpeg.beforeDecompress(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection().
JpegConsumeInput()
ReadResult BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput () inline
Consume data in advance of what the decompressor requires.
Returns
The result of data consumption.
This routine can be called at any time after initializing the JPEG object. It reads some additional data and returns when one of the indicated significant events occurs. If called after the EOI marker is reached, it will immediately return ReadResult.JPEG_REACHED_EOI without attempting to read more data.
Definition at line 1207 of file JpegDecompressStruct.cs.
         {
             var retcode = ReadResult.JPEG_SUSPENDED;
             /* NB: every possible DSTATE value should be listed in this switch */
             switch (globalState)
             {
                 case JpegState.DSTATE_START:
                 JpegConsumeInputStart();
                 retcode = JpegConsumeInputInHeader();
                 break;
                 case JpegState.DSTATE_INHEADER:
                 retcode = JpegConsumeInputInHeader();
                 break;
                 case JpegState.DSTATE_READY:
                 /* Can't advance past first SOS until start_decompress is called */
                 retcode = ReadResult.JPEG_REACHED_SOS;
                 break;
                 case JpegState.DSTATE_PRELOAD:
                 case JpegState.DSTATE_PRESCAN:
                 case JpegState.DSTATE_SCANNING:
                 case JpegState.DSTATE_RAW_OK:
                 case JpegState.DSTATE_BUFIMAGE:
                 case JpegState.DSTATE_BUFPOST:
                 case JpegState.DSTATE_STOPPING:
                 retcode = m_inputctl.ConsumeInput();
                 break;
                 default:
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
                 break;
             }
             return retcode;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeInput(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputInHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputStart(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader().
JpegConsumeInputInHeader()
ReadResult BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputInHeader () inline private
Definition at line 1953 of file JpegDecompressStruct.cs.
         {
             var retcode = m_inputctl.ConsumeInput();
             if (retcode == ReadResult.JPEG_REACHED_SOS)
             {
                 /* Found SOS, prepare to decompress */
                 /* Set up default parameters based on header data */
                 DefaultDecompressParams();
                 /* Set global state: ready for start_decompress */
                 globalState = JpegState.DSTATE_READY;
             }
             return retcode;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeInput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput().
JpegConsumeInputStart()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputStart () inline private
Definition at line 1943 of file JpegDecompressStruct.cs.
         {
             /* Start-of-datastream actions: reset appropriate modules */
             m_inputctl.ResetInputController();
             /* Initialize application's data source module */
             m_src.InitSource();
             globalState = JpegState.DSTATE_INHEADER;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegSourceManager.InitSource(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ResetInputController().
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput().
JpegCopyCriticalParameters()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters (JpegCompressStruct dstinfo) inline
Initializes the compression object with default parameters, then copy from the source object all parameters needed for lossless transcoding.
Parameters
dstinfo Target JPEG compression object.
Parameters that can be varied without loss (such as scan script and Huffman optimization) are left in their default states.
Definition at line 1455 of file JpegDecompressStruct.cs.
         {
             if (dstinfo is null)
             {
                 throw new ArgumentNullException(nameof(dstinfo));
             }
             /* Safety check to ensure start_compress not called yet. */
             if (dstinfo.globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)dstinfo.globalState);
             }
             /* Copy fundamental image dimensions */
             dstinfo.m_image_width = imageWidth;
             dstinfo.m_image_height = imageHeight;
             dstinfo.m_input_components = numComponents;
             dstinfo.m_in_color_space = jpegColorSpace;
             dstinfo.jpeg_width = Output_width;
             dstinfo.jpeg_height = Output_height;
             dstinfo.min_DCT_h_scaled_size = min_DCT_h_scaled_size;
             dstinfo.min_DCT_v_scaled_size = min_DCT_v_scaled_size;
             /* Initialize all parameters to default values */
             dstinfo.JpegSetDefaults();
             /* jpeg_set_defaults may choose wrong colorspace, eg YCbCr if input is RGB.
              * Fix it to get the right header markers for the image colorspace.
              * Note: Entropy table assignment in jpeg_set_colorspace depends
              * on color_transform.
              */
             dstinfo.ColorTransform = color_transform;
             dstinfo.JpegSetColorspace(jpegColorSpace);
             dstinfo.m_data_precision = m_dataPrecision;
             dstinfo.CIR601sampling = m_CCIR601_sampling;
             /* Copy the source's quantization tables. */
             for (var tblno = 0; tblno < JpegConstants.NUM_QUANT_TBLS; tblno++)
             {
                 if (m_quant_tbl_ptrs[tblno] is object)
                 {
                     if (dstinfo.m_quant_tbl_ptrs[tblno] is null)
                     {
                         dstinfo.m_quant_tbl_ptrs[tblno] = new JQuantTable();
                     }
                     Buffer.BlockCopy(m_quant_tbl_ptrs[tblno].quantBal, 0,
                         dstinfo.m_quant_tbl_ptrs[tblno].quantBal, 0,
                         dstinfo.m_quant_tbl_ptrs[tblno].quantBal.Length * sizeof(short));
                     dstinfo.m_quant_tbl_ptrs[tblno].SentTable = false;
                 }
             }
             /* Copy the source's per-component info.
             * Note we assume jpeg_set_defaults has allocated the dest comp_info array.
             */
             dstinfo.m_num_components = numComponents;
             if (dstinfo.m_num_components < 1 || dstinfo.m_num_components > JpegConstants.MAX_COMPONENTS)
             {
                 ErrExit(JMessageCode.JERR_COMPONENT_COUNT, dstinfo.m_num_components, JpegConstants.MAX_COMPONENTS);
             }
             for (var ci = 0; ci < dstinfo.m_num_components; ci++)
             {
                 dstinfo.Component_info[ci].Component_id = CompInfo[ci].Component_id;
                 dstinfo.Component_info[ci].H_samp_factor = CompInfo[ci].H_samp_factor;
                 dstinfo.Component_info[ci].V_samp_factor = CompInfo[ci].V_samp_factor;
                 dstinfo.Component_info[ci].Quant_tbl_no = CompInfo[ci].Quant_tbl_no;
                 /* Make sure saved quantization table for component matches the qtable
                 * slot.  If not, the input file re-used this qtable slot.
                 * IJG encoder currently cannot duplicate this.
                 */
                 var tblno = dstinfo.Component_info[ci].Quant_tbl_no;
                 if (tblno < 0 || tblno >= JpegConstants.NUM_QUANT_TBLS || m_quant_tbl_ptrs[tblno] is null)
                 {
                     ErrExit(JMessageCode.JERR_NO_QUANT_TABLE, tblno);
                 }
                 var c_quant = CompInfo[ci].quant_table;
                 if (c_quant is object)
                 {
                     var slot_quant = m_quant_tbl_ptrs[tblno];
                     for (var coefi = 0; coefi < JpegConstants.DCTSIZE2; coefi++)
                     {
                         if (c_quant.quantBal[coefi] != slot_quant.quantBal[coefi])
{
                             ErrExit(JMessageCode.JERR_MISMATCHED_QUANT_TABLE, tblno);
                         }
                     }
                 }
                 /* Note: we do not copy the source's entropy table assignments;
                 * instead we rely on jpeg_set_colorspace to have made a suitable choice.
                 */
             }
             /* Also copy JFIF version and resolution information, if available.
             * Strictly speaking this isn't "critical" info, but it's nearly
             * always appropriate to copy it if available.  In particular,
             * if the application chooses to copy JFIF 1.02 extension markers from
             * the source file, we need to copy the version to make sure we don't
             * emit a file that has 1.02 extensions but a claimed version of 1.01.
             */
             if (m_saw_JFIF_marker)
             {
                 if (m_JFIF_major_version == 1 || m_JFIF_major_version == 2)
                 {
                     dstinfo.m_JFIF_major_version = m_JFIF_major_version;
                     dstinfo.m_JFIF_minor_version = m_JFIF_minor_version;
                 }
                 dstinfo.m_density_unit = m_densityUnit;
                 dstinfo.m_X_density = m_xDensity;
                 dstinfo.m_Y_density = m_yDensity;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.CIR601sampling, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.color_transform, BitMiracle.LibJpeg.Classic.JpegCompressStruct.ColorTransform, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_id, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegComponentInfo.H_samp_factor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageWidth, BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_width, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.jpegColorSpace, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_CCIR601_sampling, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_data_precision, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dataPrecision, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_density_unit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_densityUnit, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_width, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_in_color_space, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_input_components, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_major_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_major_version, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_minor_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_minor_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_JFIF_marker, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_X_density, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_xDensity, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Y_density, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_yDensity, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPONENTS, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_height, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_width, BitMiracle.LibJpeg.Classic.JpegComponentInfo.quant_table, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Quant_tbl_no, BitMiracle.LibJpeg.Classic.JQuantTable.quantBal, BitMiracle.LibJpeg.Classic.JQuantTable.SentTable, and BitMiracle.LibJpeg.Classic.JpegComponentInfo.V_samp_factor.
JpegDestroy()
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegDestroy () inline inherited
Destruction of a JPEG object.
Closing a data source or destination, if necessary, is the application's responsibility.
Definition at line 226 of file JpegCommonStruct.cs.
         {
             // mark it destroyed
             globalState = JpegState.DESTROYED;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState.
JpegFinishDecompress()
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress () inline
Finish JPEG decompression.
Returns
Returns false if suspended. The return value need be inspected only if a suspending data source is used.
This will normally just verify the file trailer and release temp storage.
See also
JpegDecompressStruct.JpegStartDecompress
Decompression details
Definition at line 991 of file JpegDecompressStruct.cs.
         {
             if ((globalState == JpegState.DSTATE_SCANNING || globalState == JpegState.DSTATE_RAW_OK) && !bufferedImage)
             {
                 /* Terminate final pass of non-buffered mode */
                 if (outputScanline < outputHeight)
                 {
                     ErrExit(JMessageCode.JERR_TOO_LITTLE_DATA);
                 }
                 m_master.FinishOutputPass();
                 globalState = JpegState.DSTATE_STOPPING;
             }
             else if (globalState == JpegState.DSTATE_BUFIMAGE)
             {
                 /* Finishing after a buffered-image operation */
                 globalState = JpegState.DSTATE_STOPPING;
             }
             else if (globalState != JpegState.DSTATE_STOPPING)
             {
                 /* STOPPING = repeat call after a suspension, anything else is error */
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Read until EOI */
             while (!m_inputctl.EOIReached())
             {
                 if (m_inputctl.ConsumeInput() == ReadResult.JPEG_SUSPENDED)
                 {
                     /* Suspend, come back later */
                     return false;
                 }
             }
             /* Do final cleanup */
             m_src.TermSource();
             /* We can use jpeg_abort to release memory and reset global_state */
             JpegAbort();
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeInput(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.EOIReached(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanline, and BitMiracle.LibJpeg.Classic.JpegSourceManager.TermSource().
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
JpegFinishOutput()
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput () inline
Finish up after an output pass in buffered-image mode.
Returns
Returns false if suspended. The return value need be inspected only if a suspending data source is used.
See also
JpegDecompressStruct.JpegStartOutput
Buffered-image mode
Definition at line 1154 of file JpegDecompressStruct.cs.
         {
             if ((globalState == JpegState.DSTATE_SCANNING || globalState == JpegState.DSTATE_RAW_OK) && bufferedImage)
             {
                 /* Terminate this pass. */
                 /* We do not require the whole pass to have been completed. */
                 m_master.FinishOutputPass();
                 globalState = JpegState.DSTATE_BUFPOST;
             }
             else if (globalState != JpegState.DSTATE_BUFPOST)
             {
                 /* BUFPOST = repeat call after a suspension, anything else is error */
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Read markers looking for SOS or EOI */
             while (inputScanNumber <= outputScanNumber && !m_inputctl.EOIReached())
             {
                 if (m_inputctl.ConsumeInput() == ReadResult.JPEG_SUSPENDED)
                 {
                     /* Suspend, come back later */
                     return false;
                 }
             }
             globalState = JpegState.DSTATE_BUFIMAGE;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeInput(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.EOIReached(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.inputScanNumber, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_master, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanNumber.
JpegHasMultipleScans()
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegHasMultipleScans () inline
Is there more than one scan?
Returns
true if image has more than one scan; otherwise, false
If you are concerned about maximum performance on baseline JPEG files, you should use buffered-image mode
only when the incoming file actually has multiple scans. This can be tested by calling this method.
Definition at line 1106 of file JpegDecompressStruct.cs.
         {
             /* Only valid after jpeg_read_header completes */
             if (globalState < JpegState.DSTATE_READY || globalState > JpegState.DSTATE_STOPPING)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             return m_inputctl.HasMultipleScans();
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.HasMultipleScans(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl.
JpegInputComplete()
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegInputComplete () inline
Indicates if we have finished reading the input file.
Returns
true if we have finished reading the input file.
Buffered-image mode
Definition at line 1188 of file JpegDecompressStruct.cs.
         {
             /* Check for valid jpeg object */
             if (globalState < JpegState.DSTATE_START || globalState > JpegState.DSTATE_STOPPING)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             return m_inputctl.EOIReached();
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegInputController.EOIReached(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl.
JpegMarkerParserMethod()
delegate bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegMarkerParserMethod (JpegDecompressStruct cinfo)
The delegate for application-supplied marker processing methods.
Parameters
cinfo Decompressor.
Returns
Return true to indicate success. false should be returned only if you are using a suspending data source and it tells you to suspend.
Although the marker code is not explicitly passed, the routine can find it in the JpegDecompressStruct.UnreadMarker. At the time of call, the marker proper has been read from the data source module. The processor routine is responsible for reading the marker length word and the remaining parameter bytes, if any.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers().
JpegReadCoefficients()
JVirtArray<JBlock> [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients () inline
Read or write the raw DCT coefficient arrays from a JPEG file (useful for lossless transcoding).
Returns
Returns null if suspended. This case need be checked only if a suspending data source is used.
jpeg_read_header must be completed before calling this.
The entire image is read into a set of virtual coefficient-block arrays, one per component. The return value is an array of virtual-array descriptors.
An alternative usage is to simply obtain access to the coefficient arrays during a buffered-image mode
decompression operation. This is allowed after any jpeg_finish_output call. The arrays can be accessed until jpeg_finish_decompress is called. Note that any call to the library may reposition the arrays, so don't rely on JVirtArray<T>.Access results to stay valid across library calls.
Definition at line 1387 of file JpegDecompressStruct.cs.
         {
             if (globalState == JpegState.DSTATE_READY)
             {
                 /* First call: initialize active modules */
                 TransdecodeMasterSelection();
                 globalState = JpegState.DSTATE_RDCOEFS;
             }
             if (globalState == JpegState.DSTATE_RDCOEFS)
             {
                 /* Absorb whole file into the coef buffer */
                 while (true)
                 {
                     ReadResult retcode;
                     /* Call progress monitor hook if present */
                     prog?.Updated();
                     /* Absorb some more input */
                     retcode = m_inputctl.ConsumeInput();
                     if (retcode == ReadResult.JPEG_SUSPENDED)
                     {
                         return null;
                     }
                     if (retcode == ReadResult.JPEG_REACHED_EOI)
                     {
                         break;
                     }
                     /* Advance progress counter if appropriate */
                     if (prog is object && (retcode == ReadResult.JPEG_ROW_COMPLETED || retcode == ReadResult.JPEG_REACHED_SOS))
                     {
                         prog.PassCounter++;
                         if (prog.PassCounter >= prog.PassLimit)
{
                             /* startup underestimated number of scans; ratchet up one scan */
                             prog.PassLimit += m_total_iMCU_rows;
                         }
                     }
                 }
                 /* Set state so that jpeg_finish_decompress does the right thing */
                 globalState = JpegState.DSTATE_STOPPING;
             }
             /* At this point we should be in state DSTATE_STOPPING if being used
             * standalone, or in state DSTATE_BUFIMAGE if being invoked to get access
             * to the coefficients during a full buffered-image-mode decompression.
             */
             if ((globalState == JpegState.DSTATE_STOPPING || globalState == JpegState.DSTATE_BUFIMAGE) && bufferedImage)
             {
                 return m_coef.GetCoefArrays();
             }
             /* Oops, improper usage */
             ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             /* keep compiler happy */
             return null;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeInput(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.GetCoefArrays(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_total_iMCU_rows, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection(), and BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated().
JpegReadHeader()
ReadResult BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader (bool require_image) inline
Decompression startup: this will read the source datastream header markers, up to the beginning of the compressed data proper.
Parameters
require_image Read a description of Return Value.
Returns
If you pass require_image=true (normal case), you need not check for a ReadResult.JPEG_HEADER_TABLES_ONLY return code; an abbreviated file will cause an error exit. ReadResult.JPEG_SUSPENDED is only possible if you use a data source module that can give a suspension return.
This method will read as far as the first SOS marker (ie, actual start of compressed data), and will save all tables and parameters in the JPEG object. It will also initialize the decompression parameters to default values, and finally return ReadResult.JPEG_HEADER_OK. On return, the application may adjust the decompression parameters and then call JpegDecompressStruct.JpegStartDecompress. (Or, if the application only wanted to determine the image parameters, the data need not be decompressed. In that case, call JpegCommonStruct.JpegAbort to release any temporary space.)
If an abbreviated (tables only) datastream is presented, the routine will return ReadResult.JPEG_HEADER_TABLES_ONLY upon reaching EOI. The application may then re-use the JPEG object to read the abbreviated image datastream(s). It is unnecessary (but OK) to call jpeg_abort in this case. The ReadResult.JPEG_SUSPENDED return code only occurs if the data source module requests suspension of the decompressor. In this case the application should load more source data and then re-call jpeg_read_header to resume processing.
If a non-suspending data source is used and require_image is true, then the return code need not be inspected since only ReadResult.JPEG_HEADER_OK is possible.
Need only initialize JPEG object and supply a data source before calling.
On return, the image dimensions and other info have been stored in the JPEG object. The application may wish to consult this information before selecting decompression parameters.
This routine is now just a front end to JpegConsumeInput, with some extra error checking.
Decompression details
Decompression parameter selection
Definition at line 830 of file JpegDecompressStruct.cs.
         {
             if (globalState != JpegState.DSTATE_START && globalState != JpegState.DSTATE_INHEADER)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             var retcode = JpegConsumeInput();
             switch (retcode)
             {
                 case ReadResult.JPEG_REACHED_SOS:
                 return ReadResult.JPEG_HEADER_OK;
                 case ReadResult.JPEG_REACHED_EOI:
                 if (require_image)      /* Complain if application wanted an image */
                 {
                     ErrExit(JMessageCode.JERR_NO_IMAGE);
                 }
                 /* Reset to start state; it would be safer to require the application to
 * call jpeg_abort, but we can't change it now for compatibility reasons.
 * A side effect is to free any temporary memory (there shouldn't be any).
 */
                 JpegAbort(); /* sets state = DSTATE_START */
                 return ReadResult.JPEG_HEADER_TABLES_ONLY;
                 case ReadResult.JPEG_SUSPENDED:
                 /* no work */
                 break;
             }
             return ReadResult.JPEG_SUSPENDED;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput().
Referenced by BitMiracle.LibJpeg.Jpeg.beforeDecompress().
JpegReadRawData()
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData (byte data[][][], int max_lines) inline
Alternate entry point to read raw data.
Parameters
data The raw data.
max_lines The number of scanlines for reading.
Returns
The number of lines actually read.
Replaces jpeg_read_scanlines when reading raw downsampled data. Processes exactly one iMCU row per call, unless suspended.
Definition at line 1042 of file JpegDecompressStruct.cs.
         {
             if (data is null)
             {
                 throw new ArgumentNullException(nameof(data));
             }
             if (globalState != JpegState.DSTATE_RAW_OK)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             if (outputScanline >= outputHeight)
             {
                 WarnMS(JMessageCode.JWRN_TOO_MUCH_DATA);
                 return 0;
             }
             /* Call progress monitor hook if present */
             if (prog is object)
             {
                 prog.PassCounter = outputScanline;
                 prog.PassLimit = outputHeight;
                 prog.Updated();
             }
             /* Verify that at least one iMCU row can be returned. */
             var lines_per_iMCU_row = m_maxVSampleFactor * min_DCT_v_scaled_size;
             if (max_lines < lines_per_iMCU_row)
             {
                 ErrExit(JMessageCode.JERR_BUFFER_SIZE);
             }
             var componentCount = data.Length; // maybe we should use max_lines here
             var cb = new ComponentBuffer[componentCount];
             for (var i = 0; i < componentCount; i++)
             {
                 cb[i] = new ComponentBuffer();
                 cb[i].SetBuffer(data[i], null, 0);
             }
             /* Decompress directly into user's buffer. */
             if (m_coef.DecompressData(cb) == ReadResult.JPEG_SUSPENDED)
             {
                 /* suspension forced, can do nothing more */
                 return 0;
             }
             /* OK, we processed one iMCU row. */
             outputScanline += lines_per_iMCU_row;
             return lines_per_iMCU_row;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressData(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_maxVSampleFactor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanline, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
JpegReadScanlines()
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines (byte scanlines[][], int max_lines) inline
Read some scanlines of data from the JPEG decompressor.
Parameters
scanlines Buffer for filling.
max_lines Required number of lines.
Returns
The return value will be the number of lines actually read. This may be less than the number requested in several cases, including bottom of image, data source suspension, and operating modes that emit multiple scanlines at a time.
We warn about excess calls to jpeg_read_scanlines since this likely signals an application programmer error. However, an oversize buffer (max_lines > scanlines remaining) is not an error.
Decompression details
Definition at line 954 of file JpegDecompressStruct.cs.
         {
             if (globalState != JpegState.DSTATE_SCANNING)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             if (outputScanline >= outputHeight)
             {
                 WarnMS(JMessageCode.JWRN_TOO_MUCH_DATA);
                 return 0;
             }
             /* Call progress monitor hook if present */
             if (prog is object)
             {
                 prog.PassCounter = outputScanline;
                 prog.PassLimit = outputHeight;
                 prog.Updated();
             }
             /* Process some data */
             var row_ctr = 0;
             m_main.ProcessData(scanlines, ref row_ctr, max_lines);
             outputScanline += row_ctr;
             return row_ctr;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_main, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanline, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessData(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
JpegSaveMarkers()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegSaveMarkers (int marker_code, int length_limit) inline
Control saving of COM and APPn markers into Marker_list.
Parameters
marker_code The marker type to save (see JPEG_MARKER enumeration).
To arrange to save all the special marker types, you need to call this routine 17 times, for COM and APP0-APP15 markers.
length_limit If the incoming marker is longer than length_limit data bytes, only length_limit bytes will be saved; this parameter allows you to avoid chewing up memory when you only need to see the first few bytes of a potentially large marker. If you want to save all the data, set length_limit to 0xFFFF; that is enough since marker lengths are only 16 bits. As a special case, setting length_limit to 0 prevents that marker type from being saved at all. (That is the default behavior, in fact.)
See also
JpegDecompressStruct.Marker_list
Special markers
Definition at line 1610 of file JpegDecompressStruct.cs.
         {
             m_marker.JpegSaveMarkers(marker_code, length_limit);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker.
JpegSetMarkerProcessor()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegSetMarkerProcessor (int marker_code, JpegMarkerParserMethod routine) inline
Sets processor for special marker.
Parameters
marker_code The marker code.
routine The processor.
Allows you to supply your own routine to process COM and/or APPn markers on-the-fly as they are read.
Special markers
Definition at line 1590 of file JpegDecompressStruct.cs.
         {
             m_marker.JpegSetMarkerProcessor(marker_code, routine);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker.
Referenced by BitMiracle.LibJpeg.Jpeg.SetMarkerProcessor().
JpegStartDecompress()
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress () inline
Decompression initialization.
Returns
Returns false if suspended. The return value need be inspected only if a suspending data source is used.
jpeg_read_header must be completed before calling this.
If a multipass operating mode was selected, this will do all but the last pass, and thus may take a great deal of time.
See also
JpegDecompressStruct.JpegFinishDecompress
Decompression details
Definition at line 877 of file JpegDecompressStruct.cs.
         {
             if (globalState == JpegState.DSTATE_READY)
             {
                 /* First call: initialize master control, select active modules */
                 m_master = new JpegDecompMaster(this);
                 if (bufferedImage)
                 {
                     /* No more work here; expecting jpeg_start_output next */
                     globalState = JpegState.DSTATE_BUFIMAGE;
                     return true;
                 }
                 globalState = JpegState.DSTATE_PRELOAD;
             }
             if (globalState == JpegState.DSTATE_PRELOAD)
             {
                 /* If file has multiple scans, absorb them all into the coef buffer */
                 if (m_inputctl.HasMultipleScans())
                 {
                     while (true)
                     {
                         ReadResult retcode;
                         /* Call progress monitor hook if present */
                         prog?.Updated();
                         /* Absorb some more input */
                         retcode = m_inputctl.ConsumeInput();
                         if (retcode == ReadResult.JPEG_SUSPENDED)
{
                             return false;
                         }
                         if (retcode == ReadResult.JPEG_REACHED_EOI)
{
                             break;
                         }
                         /* Advance progress counter if appropriate */
                         if (prog is object && (retcode == ReadResult.JPEG_ROW_COMPLETED || retcode == ReadResult.JPEG_REACHED_SOS))
{
                             prog.PassCounter++;
                             if (prog.PassCounter >= prog.PassLimit)
{
                                 /* underestimated number of scans; ratchet up one scan */
                                 prog.PassLimit += m_total_iMCU_rows;
                             }
                         }
                     }
                 }
                 outputScanNumber = inputScanNumber;
             }
             else if (globalState != JpegState.DSTATE_PRESCAN)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Perform any dummy output passes, and set up for the final pass */
             return OutputPassSetup();
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeInput(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.HasMultipleScans(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.inputScanNumber, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_total_iMCU_rows, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanNumber, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, and BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated().
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
JpegStartOutput()
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput (int scan_number) inline
Initialize for an output pass in buffered-image mode.
Parameters
scan_number Indicates which scan of the input file is to be displayed; the scans are numbered starting at 1 for this purpose.
Returns
true if done; false if suspended
See also
JpegDecompressStruct.JpegFinishOutput
Buffered-image mode
Definition at line 1125 of file JpegDecompressStruct.cs.
         {
             if (globalState != JpegState.DSTATE_BUFIMAGE && globalState != JpegState.DSTATE_PRESCAN)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Limit scan number to valid range */
             if (scan_number <= 0)
             {
                 scan_number = 1;
             }
             if (m_inputctl.EOIReached() && scan_number > inputScanNumber)
             {
                 scan_number = inputScanNumber;
             }
             outputScanNumber = scan_number;
             /* Perform any dummy output passes, and set up for the real pass */
             return OutputPassSetup();
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegInputController.EOIReached(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.inputScanNumber, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanNumber.
JpegStdioSrc()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStdioSrc (Stream infile) inline
Sets input stream.
Parameters
infile The input stream.
The caller must have already opened the stream, and is responsible for closing it after finishing decompression.
Decompression details
Definition at line 764 of file JpegDecompressStruct.cs.
         {
             if (infile is null)
             {
                 throw new ArgumentNullException(nameof(infile));
             }
             /* The source object and input buffer are made permanent so that a series
             * of JPEG images can be read from the same file by calling jpeg_stdio_src
             * only before the first one.  (If we discarded the buffer at the end of
             * one image, we'd likely lose the start of the next one.)
             * This makes it unsafe to use this manager and a different source
             * manager serially with the same JPEG object.  Caveat programmer.
             */
             if (m_src is null)
             {
                 /* first time for this JPEG object? */
                 m_src = new MySourceManager(this);
             }
             if (m_src is MySourceManager m)
             {
                 m.Attach(infile);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src.
Referenced by BitMiracle.LibJpeg.Jpeg.beforeDecompress().
OutputPassSetup()
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup () inline private
Set up for an output pass, and perform any dummy pass(es) needed. Common subroutine for jpeg_start_decompress and jpeg_start_output. Entry: global_state = DSTATE_PRESCAN only if previously suspended. Exit: If done, returns true and sets global_state for proper output mode. If suspended, returns false and sets global_state = DSTATE_PRESCAN.
Definition at line 1762 of file JpegDecompressStruct.cs.
         {
             if (globalState != JpegState.DSTATE_PRESCAN)
             {
                 /* First call: do pass setup */
                 m_master.PrepareForOutputPass();
                 outputScanline = 0;
                 globalState = JpegState.DSTATE_PRESCAN;
             }
             /* Loop over any required dummy passes */
             while (m_master.IsDummyPass())
             {
                 /* Crank through the dummy pass */
                 while (outputScanline < outputHeight)
                 {
                     int last_scanline;
                     /* Call progress monitor hook if present */
                     if (prog is object)
                     {
                         prog.PassCounter = outputScanline;
                         prog.PassLimit = outputHeight;
                         prog.Updated();
                     }
                     /* Process some data */
                     last_scanline = outputScanline;
                     m_main.ProcessData(null, ref outputScanline, 0);
                     if (outputScanline == last_scanline)
                     {
                         /* No progress made, must suspend */
                         return false;
                     }
                 }
                 /* Finish up dummy pass, and set up for another one */
                 m_master.FinishOutputPass();
                 m_master.PrepareForOutputPass();
                 outputScanline = 0;
             }
             /* Ready for application to drive output pass through
             * jpeg_read_scanlines or jpeg_read_raw_data.
             */
             if (rawDataOut)
             {
                 globalState = JpegState.DSTATE_RAW_OK;
             }
             else
             {
                 globalState = JpegState.DSTATE_SCANNING;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.IsDummyPass(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_main, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanline, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessData(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.rawDataOut, and BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated().
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput().
TraceMS() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, JMessageCode code) inline inherited
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
See also
JpegErrorMessage.EmitMessage
Definition at line 306 of file JpegCommonStruct.cs.
         {
             TraceMS(lvl, (int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColormap(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.SelectColors(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
TraceMS() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, JMessageCode code, params object [] args) inline inherited
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
args The parameters of message.
See also
JpegErrorMessage.EmitMessage
Definition at line 318 of file JpegCommonStruct.cs.
         {
             TraceMS(lvl, (int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
TraceMS() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, int code, params object [] args) inline inherited
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
args The parameters of message.
See also
JpegErrorMessage.EmitMessage
Definition at line 330 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.EmitMessage(lvl);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
TransdecodeMasterSelection()
void BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection () inline private
Master selection of decompression modules for transcoding (that is, reading raw DCT coefficient arrays from an input JPEG file.) This substitutes for initialization of the full decompressor.
Definition at line 1709 of file JpegDecompressStruct.cs.
         {
             /* This is effectively a buffered-image operation. */
             bufferedImage = true;
             /* Compute output image dimensions and related values. */
             m_inputctl.JpegCoreOutputDimensions();
             if (arithCode)
             {
                 m_entropy = new ArithEntropyDecoder(this);
             }
             else
             {
                 m_entropy = new HuffmanEntropyDecoder(this);
             }
             /* Always get a full-image coefficient buffer. */
             m_coef = new JpegDCoefController(this, true);
             /* Initialize input side of decompressor to consume first scan. */
             m_inputctl.StartInputPass();
             /* Initialize progress monitoring. */
             if (prog is object)
             {
                 var nscans = 1;
                 /* Estimate number of scans to set pass_limit. */
                 if (progressiveMode)
                 {
                     /* Arbitrarily estimate 2 interleaved DC scans + 3 AC scans/component. */
                     nscans = 2 + (3 * numComponents);
                 }
                 else if (m_inputctl.HasMultipleScans())
                 {
                     /* For a nonprogressive multiscan file, estimate 1 scan per component. */
                     nscans = numComponents;
                 }
                 prog.PassCounter = 0;
                 prog.PassLimit = m_total_iMCU_rows * nscans;
                 prog.CompletedPasses = 0;
                 prog.TotalPasses = 1;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithCode, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.JpegProgressManager.CompletedPasses, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.HasMultipleScans(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_total_iMCU_rows, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.progressiveMode, BitMiracle.LibJpeg.Classic.Internal.JpegInputController.StartInputPass(), and BitMiracle.LibJpeg.Classic.JpegProgressManager.TotalPasses.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients().
UseMergedUpSample()
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample () inline private
Determine whether merged upsample/color conversion should be used. CRUCIAL: this must match the actual capabilities of merged upsampler!
Definition at line 1619 of file JpegDecompressStruct.cs.
         {
             /* Merging is the equivalent of plain box-filter upsampling. */
             /* The following condition is only needed if fancy shall select
              * a different upsampling method.  In our current implementation
              * fancy only affects the DCT scaling, thus we can use fancy
              * upsampling and merged upsample simultaneously, in particular
              * with scaled DCT sizes larger than the default DCTSIZE.
              */
             if (m_CCIR601_sampling)
             {
                 return false;
             }
             /* my_upsampler only supports YCC=>RGB color conversion */
             if ((jpegColorSpace != JColorSpace.JCS_YCbCr && jpegColorSpace != JColorSpace.JCS_BG_YCC)
                 || numComponents != 3
                 || outColorSpace != JColorSpace.JCS_RGB
                 || outColorComponents != JpegConstants.RGB_PIXELSIZE
                 || color_transform != JColorTransform.JCT_NONE)
             {
                 return false;
             }
             /* and it only handles 2h1v or 2h2v sampling ratios */
             if (CompInfo[0].H_samp_factor != 2
                 || CompInfo[1].H_samp_factor != 1
                 || CompInfo[2].H_samp_factor != 1
                 || CompInfo[0].V_samp_factor > 2
                 || CompInfo[1].V_samp_factor != 1
                 || CompInfo[2].V_samp_factor != 1)
             {
                 return false;
             }
             /* furthermore, it doesn't work if we've scaled the IDCTs differently */
             if (CompInfo[0].DCT_h_scaled_size != min_DCT_h_scaled_size
                 || CompInfo[1].DCT_h_scaled_size != min_DCT_h_scaled_size
                 || CompInfo[2].DCT_h_scaled_size != min_DCT_h_scaled_size
                 || CompInfo[0].DCT_v_scaled_size != min_DCT_v_scaled_size
                 || CompInfo[1].DCT_v_scaled_size != min_DCT_v_scaled_size
                 || CompInfo[2].DCT_v_scaled_size != min_DCT_v_scaled_size)
             {
                 return false;
             }
             /* ??? also need to test for upsample-time rescaling, when & if supported */
             /* by golly, it'll work... */
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.color_transform, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.jpegColorSpace, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_CCIR601_sampling, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorSpace, and BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection().
WarnMS() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (JMessageCode code) inline inherited
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
Definition at line 271 of file JpegCommonStruct.cs.
         {
             WarnMS((int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.MySourceManager.FillInputBuffer(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
WarnMS() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (JMessageCode code, params object [] args) inline inherited
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
args The parameters of message.
Definition at line 281 of file JpegCommonStruct.cs.
         {
             WarnMS((int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
WarnMS() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (int code, params object [] args) inline inherited
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
args The parameters of message.
Definition at line 291 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.EmitMessage(-1);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
Member Data Documentation
actualColorCount
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.actualColorCount private
Definition at line 65 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.FindNearbyColors(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.SelectColors(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.StartPass().
arithAcK
internal byte [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithAcK = new byte[JpegConstants.NUM_ARITH_TBLS] private
Definition at line 106 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC().
arithCode
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithCode private
Definition at line 102 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
arithDcL
internal byte [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithDcL = new byte[JpegConstants.NUM_ARITH_TBLS] private
Definition at line 104 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC().
arithDcU
internal byte [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithDcU = new byte[JpegConstants.NUM_ARITH_TBLS] private
Definition at line 105 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC().
block_size
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.block_size private
Definition at line 181 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup().
bufferedImage
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage private
Definition at line 41 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
Coef_bits
int [][] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Coef_bits => coefBits
Gets the current progression status..
Coef_bits[c][i] indicates the precision with which component c's DCT coefficient i (in zigzag order) is known. It is -1 when no data has yet been received, otherwise it is the point transform (shift) value for the most recent scan of the coefficient (thus, 0 at completion of the progression). This is null when reading a non-progressive file.
Progressive JPEG support
Definition at line 696 of file JpegDecompressStruct.cs.
coefBits
internal int [][] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.coefBits private
Definition at line 76 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ResetInputController(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.SmoothingOK(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
color_transform
internal JColorTransform BitMiracle.LibJpeg.Classic.JpegDecompressStruct.color_transform private
Definition at line 125 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
Copyright
string BitMiracle.LibJpeg.Classic.JpegCommonStruct.Copyright => "Copyright (C) 2008-2018, Bit Miracle" static inherited
Gets the LibJpeg's copyright.
The copyright.
Definition at line 127 of file JpegCommonStruct.cs.
DataPrecision
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DataPrecision => m_dataPrecision
Gets the data precision.
The data precision.
Definition at line 730 of file JpegDecompressStruct.cs.
dctMethod
internal JDctMethod BitMiracle.LibJpeg.Classic.JpegDecompressStruct.dctMethod private
Definition at line 43 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), and BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.StartPass().
DensityUnit
DensityUnit BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DensityUnit => m_densityUnit
Gets the resolution information from JFIF marker.
The information from JFIF marker.
See also
JpegDecompressStruct.XDensity, JpegDecompressStruct.YDensity
Decompression parameter selection
Definition at line 708 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
desiredNumberOfColors
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.desiredNumberOfColors private
Definition at line 49 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.My1PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), and BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.SelectNColors().
ditherMode
internal JDitherMode BitMiracle.LibJpeg.Classic.JpegDecompressStruct.ditherMode private
Definition at line 47 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColorIndex(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.My1PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.StartPass().
doBlockSmoothing
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.doBlockSmoothing private
Definition at line 45 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), and BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartOutputPass().
doFancyUpsampling
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.doFancyUpsampling private
Definition at line 44 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions().
enable1PassQuant
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable1PassQuant private
Definition at line 50 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
enable2PassQuant
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable2PassQuant private
Definition at line 52 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
enableExternalQuant
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enableExternalQuant private
Definition at line 51 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection().
Image_height
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Image_height => imageHeight
Gets the height of image, set by JpegDecompressStruct.JpegReadHeader
The height of image.
Decompression parameter selection
Definition at line 257 of file JpegDecompressStruct.cs.
Image_width
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Image_width => imageWidth
Gets the width of image, set by JpegDecompressStruct.jpeg_read_header
The width of image.
Decompression parameter selection
Definition at line 250 of file JpegDecompressStruct.cs.
imageHeight
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageHeight private
Definition at line 34 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup().
imageWidth
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageWidth private
Definition at line 33 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup().
Input_iMCU_row
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Input_iMCU_row => inputIMcuRow
Gets the number of iMCU rows completed.
The number of iMCU rows completed.
Indicates the progress of the decompressor input side.
Definition at line 659 of file JpegDecompressStruct.cs.
Input_scan_number
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Input_scan_number => inputScanNumber
Gets the number of SOS markers seen so far.
The number of SOS markers seen so far.
Indicates the progress of the decompressor input side.
Definition at line 652 of file JpegDecompressStruct.cs.
inputIMcuRow
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.inputIMcuRow private
Definition at line 71 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartiMCURow(), and BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartInputPass().
inputScanNumber
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.inputScanNumber private
Definition at line 70 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader().
isBaseline
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.isBaseline private
Definition at line 100 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
IsDecompressor
override bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.IsDecompressor => true
Retrieves true because this is a decompressor.
true
Definition at line 230 of file JpegDecompressStruct.cs.
jpegColorSpace
internal JColorSpace BitMiracle.LibJpeg.Classic.JpegDecompressStruct.jpegColorSpace private
Definition at line 36 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
lim_Se
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.lim_Se private
Definition at line 183 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_ac_huff_tbl_ptrs
internal JHuffmanTable [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_ac_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 91 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable().
m_Adobe_transform
internal byte BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Adobe_transform private
Definition at line 123 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI().
m_Ah
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ah private
Definition at line 177 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_Al
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Al private
Definition at line 178 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_blocks_in_MCU
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_blocks_in_MCU private
Definition at line 169 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_CCIR601_sampling
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_CCIR601_sampling private
Definition at line 128 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
m_cconvert
internal JpegColorDeconverter BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cconvert private
Definition at line 203 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.UpSample().
m_coef
internal JpegDCoefController BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_coef private
Definition at line 196 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeInput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataContextMain(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataSimpleMain(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.StartInputPass(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
m_colormap
internal byte [][] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_colormap private
Definition at line 66 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.ComputeColor(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.FindBestColors(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.FindNearbyColors(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.FinishPass1(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.Pass2FsDither(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass().
m_comps_in_scan
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_comps_in_scan private
Definition at line 162 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.LatchQuantTables(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartiMCURow(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_cquantize
internal IJpegColorQuantizer BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cquantize private
Definition at line 204 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess1Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
m_cur_comp_info
internal int [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cur_comp_info = new int[JpegConstants.MAX_COMPS_IN_SCAN] private
Definition at line 163 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.LatchQuantTables(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartiMCURow(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_dataPrecision
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dataPrecision private
Definition at line 98 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection().
m_dc_huff_tbl_ptrs
internal JHuffmanTable [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dc_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 90 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable().
m_densityUnit
internal DensityUnit BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_densityUnit private
Definition at line 118 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
m_entropy
internal JpegEntropyDecoder BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_entropy private
Definition at line 200 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.FinishInputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.StartInputPass(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
m_idct
internal JpegInverseDct BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_idct private
Definition at line 201 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
m_inputctl
internal JpegInputController BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl private
Definition at line 198 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputInHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputStart(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegHasMultipleScans(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegInputComplete(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
m_JFIF_major_version
internal byte BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_major_version private
Definition at line 115 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
m_JFIF_minor_version
internal byte BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_minor_version private
Definition at line 116 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
m_main
internal JpegDMainController BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_main private
Definition at line 195 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
m_marker
internal JpegMarkerReader BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker private
Definition at line 199 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegSaveMarkers(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegSetMarkerProcessor(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ResetInputController(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker().
m_marker_list
internal List<JpegMarkerStruct> BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker_list private
Definition at line 130 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker().
m_master
internal JpegDecompMaster BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_master private
Definition at line 194 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup().
m_max_h_samp_factor
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_max_h_samp_factor private
Definition at line 139 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup().
m_maxVSampleFactor
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_maxVSampleFactor private
Definition at line 140 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.H2V1UpSample(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.H2V2UpSample(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.IntUpSample(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.UpSample().
m_MCU_membership
internal int [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_MCU_membership = new int[JpegConstants.D_MAX_BLOCKS_IN_MCU] private
Definition at line 170 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_MCU_rows_in_scan
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_MCU_rows_in_scan private
Definition at line 167 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup().
m_MCUs_per_row
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_MCUs_per_row private
Definition at line 166 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup().
m_post
internal JpegDPostController BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_post private
Definition at line 197 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataContextMain(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataCrankPost(), and BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataSimpleMain().
m_quant_tbl_ptrs
internal JQuantTable [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_quant_tbl_ptrs = new JQuantTable[JpegConstants.NUM_QUANT_TBLS] private
Definition at line 87 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.LatchQuantTables().
m_restart_interval
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval private
Definition at line 108 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_sample_range_limit
internal byte [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sample_range_limit private
Definition at line 154 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct16x16(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDctfloat(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDctifast(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDctISlow(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.Pass2FsDither(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareRangeLimitTable(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.QuantizeFsDither(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
m_sampleRangeLimitOffset
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sampleRangeLimitOffset private
Definition at line 155 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct16x16(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDctfloat(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDctifast(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDctISlow(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.Pass2FsDither(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareRangeLimitTable(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.QuantizeFsDither(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
m_saw_Adobe_marker
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_Adobe_marker private
Definition at line 122 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI().
m_saw_JFIF_marker
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_JFIF_marker private
Definition at line 113 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
m_Se
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Se private
Definition at line 176 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_src
internal JpegSourceManager BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src private
Definition at line 31 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputStart(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStdioSrc(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable().
m_Ss
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ss private
Definition at line 175 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
m_total_iMCU_rows
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_total_iMCU_rows private
Definition at line 145 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataContextMain(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartiMCURow(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
m_unreadMarker
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker private
Definition at line 189 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable().
m_upsample
internal JpegUpSampler BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_upsample private
Definition at line 202 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess1Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.StartPass().
m_xDensity
internal short BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_xDensity private
Definition at line 119 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
m_yDensity
internal short BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_yDensity private
Definition at line 120 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
Marker_list
ReadOnlyCollection<JpegMarkerStruct> BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Marker_list => new ReadOnlyCollection<JpegMarkerStruct>(m_marker_list)
Gets the list of loaded special markers.
All the special markers in the file appear in this list, in order of their occurrence in the file (but omitting any markers of types you didn't ask for)
The list of loaded special markers.
Special markers
Definition at line 285 of file JpegDecompressStruct.cs.
MaxVSampleFactor
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.MaxVSampleFactor => m_maxVSampleFactor
Gets the largest vertical sample factor.
The largest vertical sample factor.
Definition at line 736 of file JpegDecompressStruct.cs.
min_DCT_h_scaled_size
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_h_scaled_size private
Definition at line 142 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
min_DCT_v_scaled_size
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.min_DCT_v_scaled_size private
Definition at line 143 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.AllocFunnyPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.MakeFunnyPointers(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataContextMain(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataSimpleMain(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.SetBottomPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.SetWraparoundPointers(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
natural_order
internal int [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.natural_order private
Definition at line 182 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup().
Num_components
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Num_components => numComponents
Gets the number of color components in JPEG image.
The number of color components.
Decompression parameter selection
Definition at line 264 of file JpegDecompressStruct.cs.
numComponents
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents private
Definition at line 35 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.AllocFunnyPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.JpegDCoefController(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegInverseDct(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.MakeFunnyPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.NullConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessDataContextMain(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.SetBottomPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.SetWraparoundPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.SmoothingOK(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.StartPass(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.UpSample(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
Out_color_components
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Out_color_components => outColorComponents
Gets the number of color components in JpegDecompressStruct.Out_color_space.
Computed by JpegDecompressStruct.JpegStartDecompress. You can also use JpegDecompressStruct.JpegCalcOutputDimensions to determine this value in advance of calling JpegDecompressStruct.JpegStartDecompress.
The number of color components.
See also
JpegDecompressStruct.Out_color_space
Decompression parameter selection
Definition at line 545 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
outColorComponents
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorComponents private
Definition at line 56 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.AllocFsWorkspace(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColorIndex(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColormap(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateODitherTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.My1PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.Quantize(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.QuantizeFsDither(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.QuantizeOrdDither(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.SelectNColors(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
outColorSpace
internal JColorSpace BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorSpace private
Definition at line 38 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.SelectNColors(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
Output_components
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_components => outputComponents
Gets the number of color components returned.
Computed by JpegDecompressStruct.JpegStartDecompress. You can also use JpegDecompressStruct.JpegCalcOutputDimensions to determine this value in advance of calling JpegDecompressStruct.JpegStartDecompress.
When quantizing colors, Output_components is 1, indicating a single color map index per pixel. Otherwise it equals to JpegDecompressStruct.Out_color_components.
See also
JpegDecompressStruct.Out_color_space
Decompression parameter selection
Definition at line 559 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress(), and BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
Output_height
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_height => outputHeight
Gets the actual height of output image.
The height of output image.
Computed by JpegDecompressStruct.JpegStartDecompress. You can also use JpegDecompressStruct.JpegCalcOutputDimensions to determine this value in advance of calling JpegDecompressStruct.JpegStartDecompress.
See also
JpegDecompressStruct.Output_width
Definition at line 534 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress(), BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
Output_iMCU_row
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_iMCU_row => outputIMcuRow
Gets the number of iMCU rows read.
The number of iMCU rows read.
Definition at line 676 of file JpegDecompressStruct.cs.
Output_scan_number
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_scan_number => outputScanNumber
Gets the nominal scan number being displayed.
The nominal scan number being displayed.
Definition at line 670 of file JpegDecompressStruct.cs.
Output_scanline
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_scanline => outputScanline
Gets the number of scanlines returned so far.
The output_scanline.
Usually you can just use this variable as the loop counter, so that the loop test looks like while (cinfo.Output_scanline < cinfo.Output_height)
Decompression details
Definition at line 641 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
Output_width
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_width => outputWidth
Gets the actual width of output image.
The width of output image.
Computed by JpegDecompressStruct.jpeg_start_decompress. You can also use JpegDecompressStruct.jpeg_calc_output_dimensions to determine this value in advance of calling JpegDecompressStruct.jpeg_start_decompress.
See also
JpegDecompressStruct.Output_height
Definition at line 524 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress(), BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
outputComponents
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputComponents private
Definition at line 61 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
outputHeight
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight private
Definition at line 55 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.StartPass().
outputIMcuRow
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputIMcuRow private
Definition at line 74 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), and BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartOutputPass().
outputScanline
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanline private
Definition at line 68 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup().
outputScanNumber
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputScanNumber private
Definition at line 73 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput().
outputWidth
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth private
Definition at line 54 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.AllocFsWorkspace(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.CmykRgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayRgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayscaleConvert(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.H2V1UpSample(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.H2V2UpSample(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.IntUpSample(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.NullConvert(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.Pass2FsDither(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.Pass2NoDither(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.PrescanQuantize(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.Quantize(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.Quantize3(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.Quantize3OrdDither(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.QuantizeFsDither(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.QuantizeOrdDither(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
progressiveMode
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.progressiveMode private
Definition at line 101 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.SmoothingOK(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
quantizeColors
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors private
Definition at line 46 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
rawDataOut
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.rawDataOut private
Definition at line 42 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
Rec_outbuf_height
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Rec_outbuf_height => recommendOutBufferHeight
Gets the recommended height of scanline buffer.
In high-quality modes, Rec_outbuf_height is always 1, but some faster, lower-quality modes set it to larger values (typically 2 to 4).
Computed by JpegDecompressStruct.JpegStartDecompress. You can also use JpegDecompressStruct.JpegCalcOutputDimensions to determine this value in advance of calling JpegDecompressStruct.JpegStartDecompress.
Rec_outbuf_height is the recommended minimum height (in scanlines) of the buffer passed to JpegDecompressStruct.JpegReadScanlines. If the buffer is smaller, the library will still work, but time will be wasted due to unnecessary data copying. If you are going to ask for a high-speed processing mode, you may as well go to the trouble of honoring Rec_outbuf_height so as to avoid data copying. (An output buffer larger than Rec_outbuf_height lines is OK, but won't provide any material speed improvement over that height.)
Decompression parameter selection
Definition at line 582 of file JpegDecompressStruct.cs.
recommendOutBufferHeight
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.recommendOutBufferHeight private
Definition at line 63 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions().
scaleDenom
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.scaleDenom private
Definition at line 40 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions().
scaleNum
internal int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.scaleNum private
Definition at line 39 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions().
twoPassQuantize
internal bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.twoPassQuantize private
Definition at line 48 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
UnreadMarker
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UnreadMarker => m_unreadMarker
Gets the last read and unprocessed JPEG marker.
It is either zero or the code of a JPEG marker that has been read from the data source, but has not yet been processed.
See also
JpegDecompressStruct.JpegSetMarkerProcessor
Special markers
Definition at line 746 of file JpegDecompressStruct.cs.
XDensity
short BitMiracle.LibJpeg.Classic.JpegDecompressStruct.XDensity => m_xDensity
Gets the horizontal component of pixel ratio.
The horizontal component of pixel ratio.
See also
JpegDecompressStruct.YDensity, JpegDecompressStruct.DensityUnit
Definition at line 716 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
YDensity
short BitMiracle.LibJpeg.Classic.JpegDecompressStruct.YDensity => m_yDensity
Gets the vertical component of pixel ratio.
The vertical component of pixel ratio.
See also
JpegDecompressStruct.XDensity, JpegDecompressStruct.DensityUnit
Definition at line 724 of file JpegDecompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
Property Documentation
ActualNumberOfColors
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.ActualNumberOfColors get set
The number of colors in the color map.
The number of colors in the color map.
See also
JpegDecompressStruct.Colormap
Decompression parameter selection
Definition at line 598 of file JpegDecompressStruct.cs.
         {
             get { return actualColorCount; }
             set { actualColorCount = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
Buffered_image
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Buffered_image get set
Gets or sets a value indicating whether to use buffered-image mode.
true if buffered-image mode is turned on; otherwise, false.
Buffered-image mode
Definition at line 343 of file JpegDecompressStruct.cs.
         {
             get { return bufferedImage; }
             set { bufferedImage = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Colormap
byte [][] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Colormap get set
The color map, represented as a 2-D pixel array of JpegDecompressStruct.Out_color_components rows and JpegDecompressStruct.ActualNumberOfColors columns.
Colormap is set to null by JpegDecompressStruct.JpegReadHeader. The application can supply a color map by setting Colormap non-null and setting JpegDecompressStruct.ActualNumberOfColors to the map size.
Ignored if not quantizing.
Implementation restriction: at present, an externally supplied Colormap is only accepted for 3-component output color spaces.
See also
JpegDecompressStruct.ActualNumberOfColors, JpegDecompressStruct.Quantize_colors
Decompression parameter selection
Definition at line 619 of file JpegDecompressStruct.cs.
         {
             get { return m_colormap; }
             set { m_colormap = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
CompInfo
JpegComponentInfo [] BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo get set
Comp_info[i] describes component that appears i'th in SOF
The components in SOF.
See also
JpegComponentInfo
Definition at line 753 of file JpegDecompressStruct.cs.
 { get; internal set; }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.AllocFunnyPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.ConsumeData(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressDataOrdinary(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressOnePass(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressSmoothData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.JpegDCoefController(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.LatchQuantTables(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.MakeFunnyPointers(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.SetBottomPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.SetWraparoundPointers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.SmoothingOK(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.StartiMCURow(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
Dct_method
LibJpeg.Classic.JDctMethod BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Dct_method get set
Gets or sets the algorithm used for the DCT step.
The algorithm used for the DCT step.
Decompression parameter selection
Definition at line 369 of file JpegDecompressStruct.cs.
         {
             get { return dctMethod; }
             set { dctMethod = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Desired_number_of_colors
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Desired_number_of_colors get set
Maximum number of colors to use in generating a library-supplied color map.
Default value: 256.
Ignored if JpegDecompressStruct.Quantize_colors is false.
The actual number of colors is returned in a JpegDecompressStruct.ActualNumberOfColors.
See also
JpegDecompressStruct.Quantize_colors
Decompression parameter selection
Definition at line 467 of file JpegDecompressStruct.cs.
         {
             get { return desiredNumberOfColors; }
             set { desiredNumberOfColors = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Dither_mode
LibJpeg.Classic.JDitherMode BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Dither_mode get set
Selects color dithering method.
Default value: JDitherMode.JDITHER_FS.
Ignored if JpegDecompressStruct.Quantize_colors is false.
At present, ordered dither is implemented only in the single-pass, standard-colormap case. If you ask for ordered dither when JpegDecompressStruct.Two_pass_quantize is true or when you supply an external color map, you'll get F-S dithering.
See also
JpegDecompressStruct.Quantize_colors
Decompression parameter selection
Definition at line 433 of file JpegDecompressStruct.cs.
         {
             get { return ditherMode; }
             set { ditherMode = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Do_block_smoothing
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Do_block_smoothing get set
Apply interblock smoothing in early stages of decoding progressive JPEG files.
If true, interblock smoothing is applied in early stages of decoding progressive JPEG files; if false, not. Early progression stages look "fuzzy" with smoothing, "blocky" without.
Default value: true
In any case, block smoothing ceases to be applied after the first few AC coefficients are known to full accuracy, so it is relevant only when using buffered-image mode
for progressive images.
Decompression parameter selection
Definition at line 401 of file JpegDecompressStruct.cs.
         {
             get { return doBlockSmoothing; }
             set { doBlockSmoothing = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Do_fancy_upsampling
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Do_fancy_upsampling get set
Enable or disable upsampling of chroma components.
If true, do careful upsampling of chroma components. If false, a faster but sloppier method is used. The visual impact of the sloppier method is often very small.
Default value: true
Decompression parameter selection
Definition at line 384 of file JpegDecompressStruct.cs.
         {
             get { return doFancyUpsampling; }
             set { doFancyUpsampling = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Enable_1pass_quant
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Enable_1pass_quant get set
Enable future use of 1-pass quantizer.
Default value: false
Significant only in buffered-image mode.
Buffered-image mode
Definition at line 481 of file JpegDecompressStruct.cs.
         {
             get { return enable1PassQuant; }
             set { enable1PassQuant = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Enable_2pass_quant
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Enable_2pass_quant get set
Enable future use of 2-pass quantizer.
Default value: false
Significant only in buffered-image mode.
Buffered-image mode
Definition at line 505 of file JpegDecompressStruct.cs.
         {
             get { return enable2PassQuant; }
             set { enable2PassQuant = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Enable_external_quant
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Enable_external_quant get set
Enable future use of external colormap.
Default value: false
Significant only in buffered-image mode.
Buffered-image mode
Definition at line 493 of file JpegDecompressStruct.cs.
         {
             get { return enableExternalQuant; }
             set { enableExternalQuant = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Err
JpegErrorMessage?? BitMiracle.LibJpeg.Classic.JpegCommonStruct.Err get set inherited
Error handler module.
The error manager.
Error handling
Definition at line 96 of file JpegCommonStruct.cs.
         {
             get { return jpgError; }
             set { jpgError = value ?? throw new ArgumentNullException(nameof(value)); }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegCommonStruct().
Jpeg_color_space
LibJpeg.Classic.JColorSpace BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Jpeg_color_space get set
Gets or sets the colorspace of JPEG image.
The colorspace of JPEG image.
Decompression parameter selection
Definition at line 272 of file JpegDecompressStruct.cs.
         {
             get { return jpegColorSpace; }
             set { jpegColorSpace = value; }
         }
Out_color_space
LibJpeg.Classic.JColorSpace BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Out_color_space get set
Gets or sets the output color space.
The output color space.
Decompression parameter selection
Definition at line 298 of file JpegDecompressStruct.cs.
         {
             get { return outColorSpace; }
             set { outColorSpace = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), and BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
Progress
JpegProgressManager?? BitMiracle.LibJpeg.Classic.JpegCommonStruct.Progress get set inherited
Progress monitor.
The progress manager.
Default value: null.
Definition at line 85 of file JpegCommonStruct.cs.
         {
             get { return prog; }
             set { prog = value ?? throw new ArgumentNullException(nameof(value)); }
         }
Quantize_colors
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Quantize_colors get set
Colors quantization.
If set true, colormapped output will be delivered.
Default value: false, meaning that full-color output will be delivered.
Decompression parameter selection
Definition at line 414 of file JpegDecompressStruct.cs.
         {
             get { return quantizeColors; }
             set { quantizeColors = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), and BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor().
Raw_data_out
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Raw_data_out get set
Enable or disable raw data output.
true if raw data output is enabled; otherwise, false.
Default value: false
Set this to true before JpegDecompressStruct.JpegStartDecompress if you need to obtain raw data output.
See also
JpegReadRawData
Definition at line 358 of file JpegDecompressStruct.cs.
         {
             get { return rawDataOut; }
             set { rawDataOut = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Scale_denom
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Scale_denom get set
Gets or sets the denominator of the fraction of image scaling.
Scale the image by the fraction Scale_num/Scale_denom. Default is 1/1, or no scaling. Currently, the only supported scaling ratios are 1/1, 1/2, 1/4, and 1/8. (The library design allows for arbitrary scaling ratios but this is not likely to be implemented any time soon.)
Smaller scaling ratios permit significantly faster decoding since fewer pixels need to be processed and a simpler DCT method can be used.
See also
JpegDecompressStruct.Scale_num
Decompression parameter selection
Definition at line 332 of file JpegDecompressStruct.cs.
         {
             get { return scaleDenom; }
             set { scaleDenom = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Scale_num
int BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Scale_num get set
Gets or sets the numerator of the fraction of image scaling.
Scale the image by the fraction Scale_num/Scale_denom. Default is 1/1, or no scaling. Currently, the only supported scaling ratios are 1/1, 1/2, 1/4, and 1/8. (The library design allows for arbitrary scaling ratios but this is not likely to be implemented any time soon.)
Smaller scaling ratios permit significantly faster decoding since fewer pixels need to be processed and a simpler DCT method can be used.
See also
JpegDecompressStruct.Scale_denom
Decompression parameter selection
Definition at line 315 of file JpegDecompressStruct.cs.
         {
             get { return scaleNum; }
             set { scaleNum = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Src
LibJpeg.Classic.JpegSourceManager BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Src get set
Gets or sets the source for decompression.
The source for decompression.
Definition at line 237 of file JpegDecompressStruct.cs.
         {
             get { return m_src; }
             set { m_src = value; }
         }
Two_pass_quantize
bool BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Two_pass_quantize get set
Gets or sets a value indicating whether to use two-pass color quantization.
If true, an extra pass over the image is made to select a custom color map for the image. This usually looks a lot better than the one-size-fits-all colormap that is used otherwise. Ignored when the application supplies its own color map.
Default value: true
Ignored if JpegDecompressStruct.Quantize_colors is false.
See also
JpegDecompressStruct.Quantize_colors
Decompression parameter selection
Definition at line 452 of file JpegDecompressStruct.cs.
         {
             get { return twoPassQuantize; }
             set { twoPassQuantize = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Version
string BitMiracle.LibJpeg.Classic.JpegCommonStruct.Version static get inherited
Gets the version of LibJpeg.
The version of LibJpeg.
Definition at line 106 of file JpegCommonStruct.cs.
         {
             get
             {
                 var assembly = typeof(JpegCommonStruct).GetTypeInfo().Assembly;
                 var assemblyName = new AssemblyName(assembly.FullName);
                 var version = assemblyName.Version;
                 var versionString = version.Major.ToString(CultureInfo.InvariantCulture) +
                     "." + version.Minor.ToString(CultureInfo.InvariantCulture);
                 versionString += "." + version.Build.ToString(CultureInfo.InvariantCulture);
                 versionString += "." + version.Revision.ToString(CultureInfo.InvariantCulture);
                 return versionString;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/JpegDecompressStruct.cs