Juniper: Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType > Class Template Reference
Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType > Class Template Reference abstract
Public Member Functions
void AddButton (ButtonIDType buttonID, InputEventButton buttonValue)
Add a new button mapping to the pointer.
void RemoveButton (ButtonIDType buttonID)
Remove a button mapping from the pointer.
virtual void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
void Start ()
virtual void Install (bool reset)
Install, with or without a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void OnProbeFound ()
Vector2 ScreenFromWorld (Vector3 worldPoint)
Vector2 ScreenFromViewport (Vector2 viewportPoint)
Vector2 ViewportFromWorld (Vector3 worldPoint)
Vector2 ViewportFromScreen (Vector2 screenPoint)
Vector3 WorldFromScreen (Vector2 screenPoint)
Vector3 WorldFromViewport (Vector2 viewportPoint)
virtual void Update ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
virtual void PlayInteraction (Interaction action)
virtual void Process (PointerEventData evtData, float pixelDragThresholdSquared)
virtual bool IsButtonPressed (InputButton button)
virtual bool IsButtonUp (InputButton button)
virtual bool IsButtonDown (InputButton button)
abstract bool IsButtonPressed (ButtonIDType button)
Implementers should return true while the button is depressed.
abstract bool IsButtonDown (ButtonIDType button)
Implementers should return true when a button is first depressed.
abstract bool IsButtonUp (ButtonIDType button)
Implementers should return true when the button is first released.
bool IsButtonDown (PointerEventData.InputButton button)
bool IsButtonPressed (PointerEventData.InputButton button)
bool IsButtonUp (PointerEventData.InputButton button)
Public Attributes
bool Connected
Material LaserPointerMaterial
bool showProbe = true
AbstractMotionFilter motionFilter
Protected Member Functions
PointerEventData Clone (int pointerDataID, PointerEventData evtData)
virtual IEventSystemHandler ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared)
virtual void InternalUpdate ()
abstract AbstractHapticDevice MakeHapticsDevice ()
Protected Attributes
readonly ButtonMapper< ButtonIDType > nativeButtons = new ButtonMapper<ButtonIDType>()
Vector3 pointerOffset
IProbe probe
The cursor probe that shows the physical location of the current selection.
AbstractUnifiedInputModule eventManager
Avatar stage
Static Protected Attributes
static readonly Vector2 VIEWPORT_MIDPOINT
static readonly ConfigType PointerConfig
Properties
Type ButtonType [get]
int PointerDataID [get]
float MinimumPointerDistance [get]
The minimum distance from the camera at which to place the pointer.
float MaximumPointerDistance [get]
int Layer [get, set]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
abstract bool IsConnected [get]
bool IsEnabled [get]
bool IsDisabled [get]
Returns true when the device is supposed to be disabled.
PhysicsRaycaster? Raycaster [get]
virtual bool AnyButtonPressed [get]
string ProbeName [get]
Vector3 Origin [get]
Vector3 LastOrigin [get, private set]
Vector3 OriginDelta [get]
abstract Vector3 WorldPoint [get]
Vector3 LastWorldPoint [get, private set]
Vector3 WorldDelta [get]
Vector3??? SmoothedWorldPoint [get]
The target at and through which the pointer rays fire.
Vector3 LastSmoothedWorldPoint [get, private set]
Vector3 SmoothedWorldPointDelta [get]
Vector3 Direction [get]
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
Vector3 LastDirection [get]
Vector2 ScreenPoint [get]
Vector2 LastScreenPoint [get]
Vector2 ScreenDelta [get]
Vector2 ViewportPoint [get]
Vector2 LastViewportPoint [get]
Vector2 ViewportDelta [get]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
IInputModule InputModule [get]
virtual bool IsDragging [get]
AbstractHapticDevice Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
Transform transform [get]
bool isActiveAndEnabled [get]
Private Member Functions
void TestEnterExit (PointerEventData evtData)
Private Attributes
AbstractMotionFilter lastMotionFilter
float finishTime
Interaction lastAction
Detailed Description
Type Constraints
ButtonIDType : struct
ConfigType : AbstractPointerConfiguration<ButtonIDType>
ConfigType : new()
Definition at line 17 of file AbstractPointerDevice.cs.
Member Function Documentation
AddButton()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AddButton (ButtonIDType buttonID, InputEventButton buttonValue) inline
Add a new button mapping to the pointer.
Parameters
buttonID
buttonValue
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
Definition at line 41 of file AbstractPointerDevice.cs.
         {
             nativeButtons.AddButton(gameObject, buttonID, buttonValue);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Awake()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake () inline virtual
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 159 of file AbstractPointerDevice.cs.
         {
             Install(false);
             eventManager = ComponentExt.FindAny<UnifiedInputModule>();
             stage = ComponentExt.FindAny<Avatar>();
             pointerOffset = MinimumPointerDistance * Vector3.forward;
             Haptics = MakeHapticsDevice();
             nativeButtons.ButtonDownNeeded += IsButtonDown;
             nativeButtons.ButtonUpNeeded += IsButtonUp;
             nativeButtons.ButtonPressedNeeded += IsButtonPressed;
             nativeButtons.ClonedPointerEventNeeded += Clone;
             nativeButtons.InteractionNeeded += PlayInteraction;
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MakeHapticsDevice(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MinimumPointerDistance, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.stage.
Clone()
PointerEventData Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone (int pointerDataID, PointerEventData evtData) inline protected
Definition at line 494 of file AbstractPointerDevice.cs.
         {
             return InputModule?.Clone(pointerDataID, evtData);
         }
References Juniper.Unity.Input.IInputModule.Clone(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InputModule.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
Install()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 182 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Install(nativeButtons, gameObject);
             OnProbeFound();
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Reinstall().
InternalUpdate()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InternalUpdate () inline protected virtual
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 565 of file AbstractPointerDevice.cs.
         {
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
IsButtonDown() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonDown (PointerEventData.InputButton button) inherited
IsButtonDown() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown (InputButton button) inline virtual
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 560 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonDown(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
IsButtonDown() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown (ButtonIDType button) pure virtual
Implementers should return true when a button is first depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonPressed() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonPressed (PointerEventData.InputButton button) inherited
IsButtonPressed() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed (InputButton button) inline virtual
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 550 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonPressed(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
IsButtonPressed() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed (ButtonIDType button) pure virtual
Implementers should return true while the button is depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonUp() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonUp (PointerEventData.InputButton button) inherited
IsButtonUp() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp (InputButton button) inline virtual
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 555 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonUp(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
IsButtonUp() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp (ButtonIDType button) pure virtual
Implementers should return true when the button is first released.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
MakeHapticsDevice()
abstract AbstractHapticDevice Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MakeHapticsDevice () protected pure virtual
Implemented in Juniper.Unity.Input.Pointers.Motion.AbstractHandTracker< HandIDType, ButtonIDType, ConfigType >.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
OnProbeFound()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound () inline virtual
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 215 of file AbstractPointerDevice.cs.
         {
             if (probe == null)
             {
                 probe = Probe.Ensure(transform, ProbeName);
             }
         }
References Juniper.Unity.Input.Pointers.Probe.Ensure(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProbeName, and Juniper.Unity.Input.Pointers.IPointerDevice.transform.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install().
PlayInteraction()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction (Interaction action) inline virtual
Definition at line 485 of file AbstractPointerDevice.cs.
         {
             if (Time.unscaledTime > finishTime || action != lastAction)
             {
                 lastAction = action;
                 finishTime = Time.unscaledTime + InteractionAudio.Play(action, probe.Cursor, Haptics);
             }
         }
References Juniper.Unity.Input.Pointers.IProbe.Cursor, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.finishTime, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastAction, Juniper.Unity.Audio.AbstractInteractionAudio.Play(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit().
Process()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process (PointerEventData evtData, float pixelDragThresholdSquared) inline virtual
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 499 of file AbstractPointerDevice.cs.
         {
             if (!IsDragging)
             {
                 TestEnterExit(evtData);
             }
             EventTarget = ProcessButtons(evtData, pixelDragThresholdSquared);
             if (evtData.clickCount == -1)
             {
                 evtData.clickCount = 0;
             }
             LastWorldPoint = evtData.pointerCurrentRaycast.worldPosition;
             LastSmoothedWorldPoint = SmoothedWorldPoint;
             LastOrigin = Origin;
             probe?.SetCursor(
                 evtData.pointerCurrentRaycast.gameObject != null,
                 AnyButtonPressed,
                 LastWorldPoint,
                 evtData.pointerCurrentRaycast.worldNormal);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AnyButtonPressed, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.EventTarget, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDragging, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastOrigin, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastSmoothedWorldPoint, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastWorldPoint, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Origin, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons(), Juniper.Unity.Input.Pointers.IProbe.SetCursor(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPoint, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit().
ProcessButtons()
virtual IEventSystemHandler Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared) inline protected virtual
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.
Definition at line 524 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.Process(evtData, pixelDragThresholdSquared);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Reinstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 193 of file AbstractPointerDevice.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install().
RemoveButton()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.RemoveButton (ButtonIDType buttonID) inline
Remove a button mapping from the pointer.
Parameters
buttonID
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
Definition at line 46 of file AbstractPointerDevice.cs.
         {
             nativeButtons.RemoveButton(buttonID);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
ScreenFromViewport()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromViewport (Vector2 viewportPoint) inline
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 380 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToScreenPoint(viewportPoint);
         }
References Juniper.Unity.Display.AbstractDisplayManager.EventCamera, and Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer().
ScreenFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromWorld (Vector3 worldPoint) inline
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 374 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToScreenPoint(worldPoint);
         }
References Juniper.Unity.Display.AbstractDisplayManager.EventCamera, and Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer().
Start()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start () inline
Definition at line 177 of file AbstractPointerDevice.cs.
         {
             eventManager.AddPointer(this);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager.
TestEnterExit()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit (PointerEventData evtData) inline private
Definition at line 529 of file AbstractPointerDevice.cs.
         {
             var target = ExecuteEvents.GetEventHandler<IPointerEnterHandler>(evtData.pointerCurrentRaycast.gameObject);
             if (target != evtData.pointerEnter)
             {
                 evtData.clickCount = -1;
                 if (evtData.pointerEnter != null)
                 {
                     ExecuteEvents.ExecuteHierarchy(evtData.pointerEnter, evtData, ExecuteEvents.pointerExitHandler);
                     PlayInteraction(Interaction.Exited);
                     evtData.pointerEnter = null;
                 }
                 if (target != null)
                 {
                     evtData.pointerEnter = ExecuteEvents.ExecuteHierarchy(target, evtData, ExecuteEvents.pointerEnterHandler);
                     PlayInteraction(Interaction.Entered);
                 }
             }
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Uninstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Uninstall () inline virtual
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 188 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Uninstall(gameObject);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig.
Update()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update () inline virtual
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Definition at line 421 of file AbstractPointerDevice.cs.
         {
             if (motionFilter != lastMotionFilter)
             {
 #if UNITY_EDITOR
                 parentMotionFilter = motionFilter;
 #endif
                 motionFilter = Instantiate(motionFilter);
                 lastMotionFilter = motionFilter;
             }
 #if UNITY_EDITOR
             motionFilter?.Copy(parentMotionFilter);
 #endif
             Connected = IsConnected;
             if (probe != null)
             {
                 probe.SetActive(IsEnabled && showProbe);
                 probe.LaserPointerMaterial = LaserPointerMaterial;
             }
             if (IsEnabled)
             {
                 motionFilter?.UpdateState(WorldPoint);
                 InternalUpdate();
                 probe?.AlignProbe(Direction, transform.up);
             }
         }
References Juniper.Unity.Input.Pointers.IProbe.AlignProbe(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Connected, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsConnected, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsEnabled, Juniper.Unity.Input.Pointers.IProbe.LaserPointerMaterial, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LaserPointerMaterial, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastMotionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.motionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Unity.Input.Pointers.IProbe.SetActive(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.showProbe, Juniper.Unity.Input.Pointers.IPointerDevice.transform, Juniper.Unity.Statistics.AbstractMotionFilter.UpdateState(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldPoint.
ViewportFromScreen()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromScreen (Vector2 screenPoint) inline
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 392 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToViewportPoint(screenPoint);
         }
References Juniper.Unity.Display.AbstractDisplayManager.EventCamera, and Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer().
ViewportFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromWorld (Vector3 worldPoint) inline
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 386 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToViewportPoint(worldPoint);
         }
References Juniper.Unity.Display.AbstractDisplayManager.EventCamera, and Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer().
WorldFromScreen()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen (Vector2 screenPoint) inline
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 398 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToWorldPoint((Vector3)screenPoint + pointerOffset);
         }
References Juniper.Unity.Display.AbstractDisplayManager.EventCamera, Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset.
WorldFromViewport()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport (Vector2 viewportPoint) inline
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 404 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToWorldPoint((Vector3)viewportPoint + pointerOffset);
         }
References Juniper.Unity.Display.AbstractDisplayManager.EventCamera, Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset.
Member Data Documentation
Connected
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Connected
Definition at line 52 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
eventManager
AbstractUnifiedInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager protected
Definition at line 452 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start().
finishTime
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.finishTime private
Definition at line 482 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
LaserPointerMaterial
Material Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LaserPointerMaterial
Definition at line 83 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
lastAction
Interaction Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastAction private
Definition at line 483 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
lastMotionFilter
AbstractMotionFilter Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastMotionFilter private
Definition at line 414 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
motionFilter
AbstractMotionFilter Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.motionFilter
Definition at line 415 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.MakeMotionController< T >(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
nativeButtons
readonly ButtonMapper<ButtonIDType> Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons = new ButtonMapper<ButtonIDType>() protected
Definition at line 39 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AddButton(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.RemoveButton().
PointerConfig
readonly ConfigType Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig static protected
Initial value:
=
            new ConfigType()
Definition at line 28 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.MakeMotionController< T >(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Uninstall().
pointerOffset
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset protected
Definition at line 73 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport().
probe
IProbe Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe protected
The cursor probe that shows the physical location of the current selection.
Definition at line 213 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
showProbe
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.showProbe = true
Definition at line 207 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
stage
Avatar Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.stage protected
Definition at line 462 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
VIEWPORT_MIDPOINT
readonly Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.VIEWPORT_MIDPOINT static protected
Initial value:
=
            0.5f * Vector2.one
Definition at line 25 of file AbstractPointerDevice.cs.
Property Documentation
AnyButtonPressed
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AnyButtonPressed get
Definition at line 147 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return IsButtonPressed(InputButton.Left)
                     || IsButtonPressed(InputButton.Right)
                     || IsButtonPressed(InputButton.Middle);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
ButtonType
Type Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ButtonType get
Definition at line 32 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return typeof(ButtonIDType);
             }
         }
Direction
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Direction get
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
The interaction direction.
Definition at line 302 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (SmoothedWorldPoint - Origin).normalized;
             }
         }
EventTarget
IEventSystemHandler Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.EventTarget get set
Definition at line 109 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Haptics
AbstractHapticDevice Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics get protected set
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 478 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
InputModule
IInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InputModule get
Definition at line 455 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return eventManager;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone().
isActiveAndEnabled
bool Juniper.Unity.Input.Pointers.IPointerDevice.isActiveAndEnabled get inherited
Definition at line 42 of file IPointerDevice.cs.
         {
             get;
         }
IsConnected
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsConnected get
Definition at line 114 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
IsDisabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDisabled get
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 131 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return !IsEnabled;
             }
         }
IsDragging
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDragging get
Definition at line 465 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return EventTarget != null && nativeButtons.IsDragging;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
IsEnabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsEnabled get
Definition at line 119 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return isActiveAndEnabled && IsConnected;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
LastDirection
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastDirection get
Definition at line 310 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (LastSmoothedWorldPoint - LastOrigin).normalized;
             }
         }
LastOrigin
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastOrigin get private set
Definition at line 240 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
LastScreenPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastScreenPoint get
Definition at line 326 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(LastSmoothedWorldPoint);
             }
         }
LastSmoothedWorldPoint
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastSmoothedWorldPoint get private set
Definition at line 284 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
LastViewportPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastViewportPoint get
Definition at line 350 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(LastSmoothedWorldPoint);
             }
         }
LastWorldPoint
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastWorldPoint get private set
Definition at line 259 of file AbstractPointerDevice.cs.
         {
             get; private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Layer
int Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Layer get set
Definition at line 86 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return gameObject.layer;
             }
             set
             {
                 if (value != gameObject.layer)
                 {
                     foreach (var trans in transform.FamilyTree())
                     {
                         trans.gameObject.layer = value;
                     }
                 }
             }
         }
LockedOnTarget
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LockedOnTarget get set
Definition at line 104 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
MaximumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MaximumPointerDistance get
Definition at line 76 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Min(10f, 0.9f * DisplayManager.MainCamera.farClipPlane);
             }
         }
MinimumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MinimumPointerDistance get
The minimum distance from the camera at which to place the pointer.
Definition at line 66 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Max(1.5f, 1.1f * DisplayManager.MainCamera.nearClipPlane);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
Origin
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Origin get
Definition at line 232 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return transform.position;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
OriginDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OriginDelta get
Definition at line 246 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Origin - LastOrigin;
             }
         }
PointerDataID
int Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerDataID get
Definition at line 55 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return GetInstanceID();
             }
         }
ProbeName
string Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProbeName get
Definition at line 224 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return name + "-probe";
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound().
Raycaster
PhysicsRaycaster? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Raycaster get
Definition at line 139 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.Raycaster;
             }
         }
ScreenDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenDelta get
Definition at line 334 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenPoint - LastScreenPoint;
             }
         }
ScreenPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenPoint get
Definition at line 318 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(SmoothedWorldPoint);
             }
         }
ScrollDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScrollDelta get protected set
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 370 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate().
SmoothedWorldPoint
Vector3??? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPoint get
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 276 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return motionFilter?.PredictedPosition ?? WorldPoint;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
SmoothedWorldPointDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPointDelta get
Definition at line 290 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return SmoothedWorldPoint - LastSmoothedWorldPoint;
             }
         }
transform
Transform Juniper.Unity.Input.Pointers.IPointerDevice.transform get inherited
Definition at line 10 of file IPointerDevice.cs.
 { get;  }
Referenced by Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
ViewportDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportDelta get
Definition at line 358 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportPoint - LastViewportPoint;
             }
         }
ViewportPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportPoint get
Definition at line 342 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(SmoothedWorldPoint);
             }
         }
WorldDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldDelta get
Definition at line 264 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return WorldPoint - LastWorldPoint;
             }
         }
WorldPoint
abstract Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldPoint get
Definition at line 254 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/Pointers/AbstractPointerDevice.cs