Juniper: Hjg.Pngcs.Chunks.AbstractPngChunk Class Reference
Hjg.Pngcs.Chunks.AbstractPngChunk Class Reference abstract
Represents a instance of a PNG chunk
Public Types
enum ChunkOrderingConstraint {
ChunkOrderingConstraint.NONE, ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT, ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT, ChunkOrderingConstraint.BEFORE_IDAT,
ChunkOrderingConstraint.NA
}
Restrictions for chunk ordering, for ancillary chunks
Public Member Functions
ChunkRaw CreateEmptyChunk (int len, bool alloc)
override string ToString ()
Basic info: Id, length, Type name
abstract ChunkRaw CreateRawChunk ()
Serialization. Creates a Raw chunk, ready for write, from this chunk content
abstract void ParseFromRaw (ChunkRaw c)
Deserialization. Given a Raw chunk, just rad, fills this chunk content
abstract void CloneDataFromRead (AbstractPngChunk other)
Override to make a copy (normally deep) from other chunk
abstract bool AllowsMultiple ()
This is implemented in PngChunkMultiple/PngChunSingle
abstract ChunkOrderingConstraint GetOrderingConstraint ()
Get ordering constrain
Static Public Member Functions
static void FactoryRegister (string chunkId, Type type)
Registers a Chunk ID in the factory, to instantiate a given type
static T CloneChunk< T > (T chunk, ImageInfo info)
Protected Member Functions
AbstractPngChunk (string id, ImageInfo imgInfo)
Constructs an empty chunk
Properties
string Id [get]
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
bool Crit [get]
Standard basic properties, implicit in the Id
bool Pub [get]
bool Safe [get]
ImageInfo ImgInfo [get]
Image basic info, mostly for some checks
bool Priority [get, set]
For writing. Queued chunks with high priority will be written as soon as possible
int ChunkGroup [get, set]
Chunk group where it was read or writen
int Length [get, set]
long Offset [get, set]
Private Member Functions
internal bool MustGoBeforePLTE ()
internal bool MustGoBeforeIDAT ()
internal bool MustGoAfterPLTE ()
internal void Write (Stream os)
Static Private Member Functions
static Dictionary< string, Type > InitFactory ()
static internal bool IsKnown (string id)
static internal AbstractPngChunk Factory (ChunkRaw chunk, ImageInfo info)
static internal AbstractPngChunk FactoryFromId (string cid, ImageInfo info)
Creates one new blank chunk of the corresponding type, according to factoryMap (PngChunkUNKNOWN if not known)
Static Private Attributes
static readonly Dictionary< string, Type > factoryMap = InitFactory()
Detailed Description
Represents a instance of a PNG chunk
Concrete classes should extend PngChunkSingle or PngChunkMultiple
Note that some methods/fields are type-specific (GetOrderingConstraint(), AllowsMultiple()) some are 'almost' type-specific (Id,Crit,Pub,Safe; the exception is PngUKNOWN), and some are instance-specific
Ref: http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html
Definition at line 20 of file AbstractPngChunk.cs.
Member Enumeration Documentation
ChunkOrderingConstraint
enum Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkOrderingConstraint strong
Restrictions for chunk ordering, for ancillary chunks
Enumerator
NONE
No constraint, the chunk can go anywhere
BEFORE_PLTE_AND_IDAT
Before PLTE (palette) - and hence, also before IDAT
AFTER_PLTE_BEFORE_IDAT
After PLTE (palette), but before IDAT
BEFORE_IDAT
Before IDAT (before or after PLTE)
NA
Does not apply
Definition at line 55 of file AbstractPngChunk.cs.
         {
             /// <summary>
             /// No constraint, the chunk can go anywhere
             /// </summary>
             NONE,
             /// <summary>
             /// Before PLTE (palette) - and hence, also before IDAT
             /// </summary>
             BEFORE_PLTE_AND_IDAT,
             /// <summary>
             /// After PLTE (palette), but before IDAT
             /// </summary>
             AFTER_PLTE_BEFORE_IDAT,
             /// <summary>
             /// Before IDAT (before or after PLTE)
             /// </summary>
             BEFORE_IDAT,
             /// <summary>
             /// Does not apply
             /// </summary>
             NA
         }
Constructor & Destructor Documentation
AbstractPngChunk()
Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk (string id, ImageInfo imgInfo) inline protected
Constructs an empty chunk
Parameters
id
imgInfo
Definition at line 88 of file AbstractPngChunk.cs.
         {
             Id = id;
             ImgInfo = imgInfo;
             Crit = ChunkHelper.IsCritical(id);
             Pub = ChunkHelper.IsPublic(id);
             Safe = ChunkHelper.IsSafeToCopy(id);
             Priority = false;
             ChunkGroup = -1;
             Length = -1;
             Offset = 0;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkGroup, Hjg.Pngcs.Chunks.AbstractPngChunk.Crit, Hjg.Pngcs.Chunks.AbstractPngChunk.Id, Hjg.Pngcs.Chunks.AbstractPngChunk.ImgInfo, Hjg.Pngcs.Chunks.ChunkHelper.IsCritical(), Hjg.Pngcs.Chunks.ChunkHelper.IsPublic(), Hjg.Pngcs.Chunks.ChunkHelper.IsSafeToCopy(), Hjg.Pngcs.Chunks.AbstractPngChunk.Length, Hjg.Pngcs.Chunks.AbstractPngChunk.Offset, Hjg.Pngcs.Chunks.AbstractPngChunk.Priority, Hjg.Pngcs.Chunks.AbstractPngChunk.Pub, and Hjg.Pngcs.Chunks.AbstractPngChunk.Safe.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId().
Member Function Documentation
AllowsMultiple()
abstract bool Hjg.Pngcs.Chunks.AbstractPngChunk.AllowsMultiple () pure virtual
This is implemented in PngChunkMultiple/PngChunSingle
Returns
Allows more than one chunk of this type in a image
Implemented in Hjg.Pngcs.Chunks.PngChunkSingle, Hjg.Pngcs.Chunks.PngChunkMultiple, and Hjg.Pngcs.Chunks.PngChunkSkipped.
Referenced by Hjg.Pngcs.Chunks.ChunkHelper.Equivalent().
CloneChunk< T >()
static T Hjg.Pngcs.Chunks.AbstractPngChunk.CloneChunk< T > (T chunk, ImageInfo info) inline static
Type Constraints
T : AbstractPngChunk
Definition at line 217 of file AbstractPngChunk.cs.
                                                                        : AbstractPngChunk
         {
             if (chunk is null)
             {
                 throw new ArgumentNullException(nameof(chunk));
             }
             var cn = FactoryFromId(chunk.Id, info);
             if (cn.GetType() != (object)chunk.GetType())
             {
                 throw new PngjException("bad class cloning chunk: " + cn.GetType() + " "
                         + chunk.GetType());
             }
             cn.CloneDataFromRead(chunk);
             return (T)cn;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId().
CloneDataFromRead()
abstract void Hjg.Pngcs.Chunks.AbstractPngChunk.CloneDataFromRead (AbstractPngChunk other) pure virtual
Override to make a copy (normally deep) from other chunk
Parameters
other
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkTEXT, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkIEND, and Hjg.Pngcs.Chunks.PngChunkSkipped.
CreateEmptyChunk()
ChunkRaw Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk (int len, bool alloc) inline
Definition at line 209 of file AbstractPngChunk.cs.
         {
             var c = new ChunkRaw(len, ChunkHelper.ToBytes(Id), alloc);
             return c;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.Id, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
Referenced by Hjg.Pngcs.Chunks.PngChunkTEXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkUNKNOWN.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkGAMA.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkOFFS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSTER.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTIME.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSRGB.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPHYS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk().
CreateRawChunk()
abstract ChunkRaw Hjg.Pngcs.Chunks.AbstractPngChunk.CreateRawChunk () pure virtual
Serialization. Creates a Raw chunk, ready for write, from this chunk content
Implemented in Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkIEND, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkTEXT, and Hjg.Pngcs.Chunks.PngChunkSkipped.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.Write().
Factory()
static internal AbstractPngChunk Hjg.Pngcs.Chunks.AbstractPngChunk.Factory (ChunkRaw chunk, ImageInfo info) inline static private
Definition at line 166 of file AbstractPngChunk.cs.
         {
             var c = FactoryFromId(ChunkHelper.ToString(chunk.IdBytes), info);
             c.Length = chunk.Len;
             c.ParseFromRaw(chunk);
             return c;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId(), Hjg.Pngcs.Chunks.ChunkRaw.IdBytes, Hjg.Pngcs.Chunks.ChunkRaw.Len, Hjg.Pngcs.Chunks.AbstractPngChunk.Length, and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
Referenced by Hjg.Pngcs.PngReader.ReadChunk().
FactoryFromId()
static internal AbstractPngChunk Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId (string cid, ImageInfo info) inline static private
Creates one new blank chunk of the corresponding type, according to factoryMap (PngChunkUNKNOWN if not known)
Parameters
cid Chunk Id
info
Returns
Definition at line 180 of file AbstractPngChunk.cs.
         {
             AbstractPngChunk chunk = null;
             if (factoryMap is null)
             {
                 _ = InitFactory();
             }
             if (IsKnown(cid))
             {
                 var t = factoryMap[cid];
                 if (t is null)
                 {
                     Console.Error.WriteLine("What?? " + cid);
                 }
                 var cons = t.GetConstructor(new Type[] { typeof(ImageInfo) });
                 var o = cons.Invoke(new object[] { info });
                 chunk = (AbstractPngChunk)o;
             }
             if (chunk is null)
             {
                 chunk = new PngChunkUNKNOWN(cid, info);
             }
             return chunk;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.AbstractPngChunk.factoryMap, Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory(), and Hjg.Pngcs.Chunks.AbstractPngChunk.IsKnown().
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.CloneChunk< T >(), and Hjg.Pngcs.Chunks.AbstractPngChunk.Factory().
FactoryRegister()
static void Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryRegister (string chunkId, Type type) inline static
Registers a Chunk ID in the factory, to instantiate a given type
This can be called by client code to register additional chunk types
Parameters
chunkId
type should extend PngChunkSingle or PngChunkMultiple
Definition at line 140 of file AbstractPngChunk.cs.
         {
             factoryMap.Add(chunkId, type);
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.factoryMap.
GetOrderingConstraint()
abstract ChunkOrderingConstraint Hjg.Pngcs.Chunks.AbstractPngChunk.GetOrderingConstraint () pure virtual
Get ordering constrain
Returns
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkSkipped, Hjg.Pngcs.Chunks.AbstractPngChunkTextVar, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, and Hjg.Pngcs.Chunks.PngChunkIEND.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoAfterPLTE(), Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforeIDAT(), and Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforePLTE().
InitFactory()
static Dictionary<string, Type> Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory () inline static private
Definition at line 103 of file AbstractPngChunk.cs.
         {
             var f = new Dictionary<string, Type>
             {
                 { ChunkHelper.IDAT, typeof(PngChunkIDAT) },
                 { ChunkHelper.IHDR, typeof(PngChunkIHDR) },
                 { ChunkHelper.PLTE, typeof(PngChunkPLTE) },
                 { ChunkHelper.IEND, typeof(PngChunkIEND) },
                 { ChunkHelper.tEXt, typeof(PngChunkTEXT) },
                 { ChunkHelper.iTXt, typeof(PngChunkITXT) },
                 { PngChunkZTXT.ID, typeof(PngChunkZTXT) },
                 { ChunkHelper.bKGD, typeof(PngChunkBKGD) },
                 { ChunkHelper.gAMA, typeof(PngChunkGAMA) },
                 { ChunkHelper.pHYs, typeof(PngChunkPHYS) },
                 { ChunkHelper.iCCP, typeof(PngChunkICCP) },
                 { ChunkHelper.tIME, typeof(PngChunkTIME) },
                 { ChunkHelper.tRNS, typeof(PngChunkTRNS) },
                 { ChunkHelper.cHRM, typeof(PngChunkCHRM) },
                 { ChunkHelper.sBIT, typeof(PngChunkSBIT) },
                 { ChunkHelper.sRGB, typeof(PngChunkSRGB) },
                 { ChunkHelper.hIST, typeof(PngChunkHIST) },
                 { ChunkHelper.sPLT, typeof(PngChunkSPLT) },
                 // extended
                 { PngChunkOFFS.ID, typeof(PngChunkOFFS) },
                 { PngChunkSTER.ID, typeof(PngChunkSTER) }
             };
             return f;
         }
References Hjg.Pngcs.Chunks.ChunkHelper.bKGD, Hjg.Pngcs.Chunks.ChunkHelper.cHRM, Hjg.Pngcs.Chunks.ChunkHelper.gAMA, Hjg.Pngcs.Chunks.ChunkHelper.hIST, Hjg.Pngcs.Chunks.ChunkHelper.iCCP, Hjg.Pngcs.Chunks.PngChunkOFFS.ID, Hjg.Pngcs.Chunks.PngChunkSTER.ID, Hjg.Pngcs.Chunks.PngChunkZTXT.ID, Hjg.Pngcs.Chunks.ChunkHelper.IDAT, Hjg.Pngcs.Chunks.ChunkHelper.IEND, Hjg.Pngcs.Chunks.ChunkHelper.IHDR, Hjg.Pngcs.Chunks.ChunkHelper.iTXt, Hjg.Pngcs.Chunks.ChunkHelper.pHYs, Hjg.Pngcs.Chunks.ChunkHelper.PLTE, Hjg.Pngcs.Chunks.ChunkHelper.sBIT, Hjg.Pngcs.Chunks.ChunkHelper.sPLT, Hjg.Pngcs.Chunks.ChunkHelper.sRGB, Hjg.Pngcs.Chunks.ChunkHelper.tEXt, Hjg.Pngcs.Chunks.ChunkHelper.tIME, and Hjg.Pngcs.Chunks.ChunkHelper.tRNS.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId().
IsKnown()
static internal bool Hjg.Pngcs.Chunks.AbstractPngChunk.IsKnown (string id) inline static private
Definition at line 145 of file AbstractPngChunk.cs.
         {
             return factoryMap.ContainsKey(id);
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.factoryMap.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId(), and Hjg.Pngcs.Chunks.ChunkHelper.ShouldLoad().
MustGoAfterPLTE()
internal bool Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoAfterPLTE () inline private
Definition at line 161 of file AbstractPngChunk.cs.
         {
             return GetOrderingConstraint() == ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.GetOrderingConstraint().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
MustGoBeforeIDAT()
internal bool Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforeIDAT () inline private
Definition at line 155 of file AbstractPngChunk.cs.
         {
             var oc = GetOrderingConstraint();
             return oc == ChunkOrderingConstraint.BEFORE_IDAT || oc == ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT || oc == ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.GetOrderingConstraint().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
MustGoBeforePLTE()
internal bool Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforePLTE () inline private
Definition at line 150 of file AbstractPngChunk.cs.
         {
             return GetOrderingConstraint() == ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.GetOrderingConstraint().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
ParseFromRaw()
abstract void Hjg.Pngcs.Chunks.AbstractPngChunk.ParseFromRaw (ChunkRaw c) pure virtual
Deserialization. Given a Raw chunk, just rad, fills this chunk content
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTEXT, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkIEND, and Hjg.Pngcs.Chunks.PngChunkSkipped.
ToString()
override string Hjg.Pngcs.Chunks.AbstractPngChunk.ToString () inline
Basic info: Id, length, Type name
Returns
Definition at line 250 of file AbstractPngChunk.cs.
         {
             return $"chunk id= {Id} (len={Length.ToString(CultureInfo.CurrentCulture)} off={Offset.ToString(CultureInfo.CurrentCulture)}) c={GetType().Name}";
         }
Write()
internal void Hjg.Pngcs.Chunks.AbstractPngChunk.Write (Stream os) inline private
Definition at line 235 of file AbstractPngChunk.cs.
         {
             var c = CreateRawChunk();
             if (c is null)
             {
                 throw new PngjException("null chunk ! creation failed for " + this);
             }
             c.WriteChunk(os);
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.CreateRawChunk().
Member Data Documentation
factoryMap
readonly Dictionary<string, Type> Hjg.Pngcs.Chunks.AbstractPngChunk.factoryMap = InitFactory() static private
Definition at line 101 of file AbstractPngChunk.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId(), Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryRegister(), and Hjg.Pngcs.Chunks.AbstractPngChunk.IsKnown().
Property Documentation
ChunkGroup
int Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkGroup get set
Chunk group where it was read or writen
Definition at line 47 of file AbstractPngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
Crit
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Crit get
Standard basic properties, implicit in the Id
Definition at line 30 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), and Hjg.Pngcs.PngReader.ReadChunk().
Id
string Hjg.Pngcs.Chunks.AbstractPngChunk.Id get
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
Definition at line 25 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkSingle.Equals(), Hjg.Pngcs.Chunks.ChunkHelper.Equivalent(), Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode(), Hjg.Pngcs.Chunks.ChunkPredicateId.Matches(), Hjg.Pngcs.Chunks.ChunkPredicateId2.Matches(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
ImgInfo
ImageInfo Hjg.Pngcs.Chunks.AbstractPngChunk.ImgInfo get protected
Image basic info, mostly for some checks
Definition at line 37 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetGray(), Hjg.Pngcs.Chunks.PngChunkSBIT.GetLen(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetRGB(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetRGB(), Hjg.Pngcs.Chunks.PngChunkSBIT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkHIST.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTRNS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetIndexEntryAsTransparent(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetRGB(), and Hjg.Pngcs.Chunks.PngChunkBKGD.SetRGB().
Length
int Hjg.Pngcs.Chunks.AbstractPngChunk.Length get set
Definition at line 49 of file AbstractPngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.AbstractPngChunk.Factory(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), and Hjg.Pngcs.Chunks.PngChunkSkipped.PngChunkSkipped().
Offset
long Hjg.Pngcs.Chunks.AbstractPngChunk.Offset get set
Definition at line 50 of file AbstractPngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), and Hjg.Pngcs.PngReader.ReadChunk().
Priority
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Priority get set
For writing. Queued chunks with high priority will be written as soon as possible
Definition at line 42 of file AbstractPngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
Pub
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Pub get
Definition at line 31 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk().
Safe
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Safe get
Definition at line 32 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Chunks/AbstractPngChunk.cs