Juniper: Juniper.World.GIS.Google.Geocoding.GeocodingResponse Class Reference
Juniper.World.GIS.Google.Geocoding.GeocodingResponse Class Reference
Public Member Functions
void GetObjectData (SerializationInfo info, StreamingContext context)
Protected Member Functions
GeocodingResponse (SerializationInfo info, StreamingContext context)
Properties
HttpStatusCode Status [get]
GeocodingResult [] Results [get]
string Error_Message [get]
Static Private Attributes
static readonly string STATUS_FIELD = nameof(Status).ToLowerInvariant()
static readonly string RESULTS_FIELD = nameof(Results).ToLowerInvariant()
static readonly string ERROR_MESSAGE_FIELD = nameof(Error_Message).ToLowerInvariant()
Detailed Description
Definition at line 10 of file GeocodingResponse.cs.
Constructor & Destructor Documentation
GeocodingResponse()
Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GeocodingResponse (SerializationInfo info, StreamingContext context) inline protected
Definition at line 23 of file GeocodingResponse.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Status = info.GetString(STATUS_FIELD).MapToStatusCode();
             if (Status == HttpStatusCode.OK)
             {
                 Results = info.GetValue<GeocodingResult[]>(RESULTS_FIELD);
             }
             else if (Status != HttpStatusCode.NoContent)
             {
                 Error_Message = info.GetString(ERROR_MESSAGE_FIELD);
             }
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Error_Message, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.ERROR_MESSAGE_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Results, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.RESULTS_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Status, and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.STATUS_FIELD.
Member Function Documentation
GetObjectData()
void Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 41 of file GeocodingResponse.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(STATUS_FIELD, Status.ToGoogleString());
             if (Status == HttpStatusCode.OK)
             {
                 info.AddValue(RESULTS_FIELD, Results);
             }
             else if (Status != HttpStatusCode.NoContent)
             {
                 info.AddValue(ERROR_MESSAGE_FIELD, Error_Message);
             }
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Error_Message, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.ERROR_MESSAGE_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Results, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.RESULTS_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Status, and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.STATUS_FIELD.
Member Data Documentation
ERROR_MESSAGE_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResponse.ERROR_MESSAGE_FIELD = nameof(Error_Message).ToLowerInvariant() static private
Definition at line 14 of file GeocodingResponse.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GeocodingResponse(), and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GetObjectData().
RESULTS_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResponse.RESULTS_FIELD = nameof(Results).ToLowerInvariant() static private
Definition at line 13 of file GeocodingResponse.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GeocodingResponse(), and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GetObjectData().
STATUS_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResponse.STATUS_FIELD = nameof(Status).ToLowerInvariant() static private
Definition at line 12 of file GeocodingResponse.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GeocodingResponse(), and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GetObjectData().
Property Documentation
Error_Message
string Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Error_Message get
Definition at line 20 of file GeocodingResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GeocodingResponse(), and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GetObjectData().
Results
GeocodingResult [] Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Results get
Definition at line 18 of file GeocodingResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GeocodingResponse(), and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GetObjectData().
Status
HttpStatusCode Juniper.World.GIS.Google.Geocoding.GeocodingResponse.Status get
Definition at line 16 of file GeocodingResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GeocodingResponse(), and Juniper.World.GIS.Google.Geocoding.GeocodingResponse.GetObjectData().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/Geocoding/GeocodingResponse.cs