Juniper: Juniper.ImageTracking.TrackerKeeper Class Reference
Juniper.ImageTracking.TrackerKeeper Class Reference
Public Member Functions
TrackableFoundEventHandler Register (TrackableFoundEventHandler target)
Register's a target and its events for the aggregated events issued by TrackerKeeper.
void Update ()
Checks the current tracking status and fires the events to indicate any change in the tracking status.
void OnDestroy ()
Tears down the tracker keeper.
void LoadDataSet (string dataSetName)
Loads a set of Vuforia markers from disk and activates it at runtime.
void ResetPET ()
On Vuforia, resets the Persistent Extended Tracking, or starts it if it hasn't already been running.
void StartTracker ()
Starts the tracker without changing any dataset data that has already been configured.
void StartTrackerWithDataSet (string dataSetName)
Initializes tracking of a set of targets.
void StartTrackerWithDataSetForTarget (string dataSetName, string targetName)
Initializes tracking of a specific target.
void Reset ()
Stop object tracking while in picker
Public Attributes
bool usePET
Set to true to enable using Vuforia's Persistent Extended Tracking.
bool manageVuforiaFrameRate = true
Set to true to set the target framerate lower than normal when the tracker is active.
bool DebugReport
Set to true to print out a debug report on the screen.
UnityEvent onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
UnityEvent onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
UnityEvent onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
UnityEvent onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
UnityEvent onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
TransformEvent onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
TransformEvent onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
UnityEvent onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
TransformEvent onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
TransformEvent onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Properties
bool Tracking [get, private set]
Is set to true when the tracking system is initialized and running.
bool TargetFound [get]
Returns true when any target has been found and is tracking.
IEnumerator WaitForTracker [get]
A coroutine that waits for a Vuforia ObjectTracker to become available.
WaitUntil WaitForNotInitializing [get]
What for Vuforia's initialization state to no longer be "INITIALIZING".
bool HasTargets [get]
Returns true when there are any GoodTargets.
bool Safe [get]
This value is set to true when the user is at a safe distance from the target.
Private Member Functions
void Start ()
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
void StopTracking ()
Cancel tracking and disable Vuforia. This also forces the Lost event on all of the currently tracked targets.
void EnableDataSet (string dataSetName)
On Vuforia, enables a specific set of data, either image targets, object targets, or scanned model targets.
IEnumerator EnablePETCoroutine ()
Handles marking a target as found, and optionally enables Vuforia's Persistent Extended Tracking.
IEnumerator StartTrackerCoroutine (string dataSetName, string targetName)
Initializes tracking of a specific target.
void WithTarget (string label, ARImageAnchor anchorData, Action< TrackableFoundEventHandler > act=null)
Finds a target object by name and updates its state.
void UnityARSessionNativeInterface_ARImageAnchorAddedEvent (ARImageAnchor anchorData)
An event handler for the first time an image is found by ARKit.
void UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent (ARImageAnchor anchorData)
An event handler that executes every time ARKit updates its understanding of an image.
void UnityARSessionNativeInterface_ARImageAnchorRemovedEvent (ARImageAnchor anchorData)
An event handler that executes when ARKit loses track of an image.
UnityAction TargetFinder (TrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetProximity (TrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetSafe (TrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetLoser (TrackableFoundEventHandler target)
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
void OnAllTargetsLost ()
Triggers the onAllTargetsLost event.
void StartTrackerDelayed ()
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
void PrintDebugReport ()
If DebugReport is set to true, prints a report on the status of tracking.
Private Attributes
const int VUFORIA_INIT_ATTEMPTS = 3
The number of times to attempt initializing Vuforia before just giving up.
ObjectTracker tracker
The Vuforia Tracker API.
bool firstTime = true
Used for reseting Vuforia's tracker the first time the application is started.
bool usingPET
Is set to true when Persistent Extended Tracking is active.
int numUpdates = 0
The number updates to the AR Background Image texture since tracking started. This value is used to delay switching from camera initialization to the app until after we are sure the camera is really ready.
Dictionary< string, TrackableFoundEventHandler > targetsByName
On ARKit, a lookup of targets by name.
Dictionary< string, ARReferenceImagesSet > dataSetsByName
On ARKit, a lookup of the image sets by name.
bool hadAnyTargets
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
readonly List< TrackableFoundEventHandler > targets = new List<TrackableFoundEventHandler>()
All of the targets in the system.
bool wasTracking
The value of Tracking from the previous frame, to detect changes.
bool done
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
XRSystem xr
Detailed Description
Definition at line 20 of file TrackerKeeper.cs.
Member Function Documentation
EnableDataSet()
void Juniper.ImageTracking.TrackerKeeper.EnableDataSet (string dataSetName) inline private
On Vuforia, enables a specific set of data, either image targets, object targets, or scanned model targets.
Parameters
dataSetName Data set name.
Definition at line 388 of file TrackerKeeper.cs.
         {
             if (dataSetName != null)
             {
                 var dataSets = tracker.GetActiveDataSets();
                 foreach (var ds in dataSets)
                 {
                     tracker.DeactivateDataSet(ds);
                 }
                 LoadDataSet(dataSetName);
             }
         }
References Juniper.ImageTracking.TrackerKeeper.LoadDataSet(), and Juniper.ImageTracking.TrackerKeeper.tracker.
Referenced by Juniper.ImageTracking.TrackerKeeper.StartTrackerCoroutine().
EnablePETCoroutine()
IEnumerator Juniper.ImageTracking.TrackerKeeper.EnablePETCoroutine () inline private
Handles marking a target as found, and optionally enables Vuforia's Persistent Extended Tracking.
Returns
The coroutine.
Definition at line 446 of file TrackerKeeper.cs.
         {
             if (VuforiaUnityExt.HasPET && usePET && !usingPET)
             {
                 yield return WaitForTracker;
                 ResetPET();
                 usingPET = true;
             }
         }
References Vuforia.VuforiaUnityExt.HasPET, Juniper.ImageTracking.TrackerKeeper.ResetPET(), Juniper.ImageTracking.TrackerKeeper.usePET, Juniper.ImageTracking.TrackerKeeper.usingPET, and Juniper.ImageTracking.TrackerKeeper.WaitForTracker.
Referenced by Juniper.ImageTracking.TrackerKeeper.ResetPET().
LoadDataSet()
void Juniper.ImageTracking.TrackerKeeper.LoadDataSet (string dataSetName) inline
Loads a set of Vuforia markers from disk and activates it at runtime.
Parameters
dataSetName Data set name.
Definition at line 406 of file TrackerKeeper.cs.
         {
             if (tracker != null && !string.IsNullOrEmpty(dataSetName))
             {
                 var dataSets = tracker.GetActiveDataSets();
                 var targetPath = Path.Combine("Vuforia", dataSetName + ".xml");
                 var dataSet = dataSets.FirstOrDefault(ds =>
                     ds.Path == targetPath);
                 if (dataSet == null)
                 {
                     dataSet = tracker.CreateDataSet();
                     dataSet.Load(dataSetName);
                     tracker.ActivateDataSet(dataSet);
                 }
             }
         }
References Juniper.ImageTracking.TrackerKeeper.tracker.
Referenced by Juniper.ImageTracking.TrackerKeeper.EnableDataSet().
OnAllTargetsLost()
void Juniper.ImageTracking.TrackerKeeper.OnAllTargetsLost () inline private
Triggers the onAllTargetsLost event.
Definition at line 681 of file TrackerKeeper.cs.
         {
             if (Tracking)
             {
                 onAllTargetsLost?.Invoke();
             }
         }
References Juniper.ImageTracking.TrackerKeeper.onAllTargetsLost, and Juniper.ImageTracking.TrackerKeeper.Tracking.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
OnDestroy()
void Juniper.ImageTracking.TrackerKeeper.OnDestroy ()
Tears down the tracker keeper.
PrintDebugReport()
void Juniper.ImageTracking.TrackerKeeper.PrintDebugReport () inline private
If DebugReport is set to true, prints a report on the status of tracking.
Definition at line 811 of file TrackerKeeper.cs.
         {
 #if VUFORIA
             ScreenDebugger.Print(tracker == null ? "No tracker" : "Has tracker");
             ScreenDebugger.Print(usingPET ? "Using PET" : "Not using PET");
 #endif
         }
References System.ScreenDebugger.Print(), Juniper.ImageTracking.TrackerKeeper.tracker, and Juniper.ImageTracking.TrackerKeeper.usingPET.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
Register()
TrackableFoundEventHandler Juniper.ImageTracking.TrackerKeeper.Register (TrackableFoundEventHandler target) inline
Register's a target and its events for the aggregated events issued by TrackerKeeper.
Parameters
target Target.
Definition at line 237 of file TrackerKeeper.cs.
         {
             if (targets?.Contains(target) == false)
             {
                 targets.Add(target);
                 target.onFound.AddListener(TargetFinder(target));
                 target.onLost.AddListener(TargetLoser(target));
                 target.onProximity.AddListener(TargetProximity(target));
                 target.onSafe.AddListener(TargetSafe(target));
             }
             return target;
         }
References Juniper.ImageTracking.TrackableFoundEventHandler.onFound, Juniper.ImageTracking.TrackableFoundEventHandler.onLost, Juniper.ImageTracking.TrackableFoundEventHandler.onProximity, Juniper.ImageTracking.TrackableFoundEventHandler.onSafe, Juniper.ImageTracking.TrackerKeeper.TargetFinder(), Juniper.ImageTracking.TrackerKeeper.TargetLoser(), Juniper.ImageTracking.TrackerKeeper.TargetProximity(), Juniper.ImageTracking.TrackerKeeper.targets, and Juniper.ImageTracking.TrackerKeeper.TargetSafe().
Referenced by Juniper.ImageTracking.TrackableFoundEventHandler.Awake(), and Juniper.ImageTracking.TrackerKeeper.Start().
Reset()
void Juniper.ImageTracking.TrackerKeeper.Reset () inline
Stop object tracking while in picker
Definition at line 794 of file TrackerKeeper.cs.
         {
             onTrackingStopping?.Invoke();
 #if VUFORIA
             StopTracking();
 #else
             Tracking = false;
 #endif
             Update();
         }
References Juniper.ImageTracking.TrackerKeeper.onTrackingStopping, Juniper.ImageTracking.TrackerKeeper.StopTracking(), Juniper.ImageTracking.TrackerKeeper.Tracking, and Juniper.ImageTracking.TrackerKeeper.Update().
ResetPET()
void Juniper.ImageTracking.TrackerKeeper.ResetPET () inline
On Vuforia, resets the Persistent Extended Tracking, or starts it if it hasn't already been running.
Definition at line 460 of file TrackerKeeper.cs.
         {
             if (usingPET && tracker != null)
             {
                 tracker.Stop();
                 tracker.Start();
             }
             else
             {
                 StartCoroutine(EnablePETCoroutine());
             }
         }
References Juniper.ImageTracking.TrackerKeeper.EnablePETCoroutine(), Juniper.ImageTracking.TrackerKeeper.tracker, and Juniper.ImageTracking.TrackerKeeper.usingPET.
Referenced by Juniper.ImageTracking.TrackerKeeper.EnablePETCoroutine(), and Juniper.ImageTracking.TrackerKeeper.StopTracking().
Start()
void Juniper.ImageTracking.TrackerKeeper.Start () inline private
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
Definition at line 185 of file TrackerKeeper.cs.
         {
             xr = ComponentExt.FindAny<XRSystem>();
 #if VUFORIA && UNITY_ANDROID
             manageVuforiaFrameRate = true;
 #endif
             var firstTargets = ComponentExt.FindAll<TrackableFoundEventHandler>()
 #if VUFORIA
                 .Union(from m in this.FindAll<ModelTargetBehaviour>()
                        select m.EnsureComponent<TrackableFoundEventHandler>().Value)
                 .Union(from m in this.FindAll<ImageTargetBehaviour>()
                        select m.EnsureComponent<TrackableFoundEventHandler>().Value)
                 .Union(from m in this.FindAll<ObjectTargetBehaviour>()
                        select m.EnsureComponent<TrackableFoundEventHandler>().Value)
 #endif
                 .Distinct()
                 .ToList();
             foreach (var target in firstTargets)
             {
                 Register(target);
             }
 #if ARKIT
             targetsByName = targets.ToDictionary(target =>
                 target.image.imageName);
             dataSetsByName = targets.Select(target =>
                 target.imagesSet)
                                     .Distinct()
                                     .ToDictionary(set =>
                                         set.resourceGroupName);
             ScreenDebugger.Print($"Found {targets.Count} targets: {string.Join(", ", targetsByName.Keys.ToArray())}");
             ScreenDebugger.Print($"Found {dataSetsByName.Count} data sets: {string.Join(", ", dataSetsByName.Keys.ToArray())}");
             UnityARSessionNativeInterface.ARImageAnchorAddedEvent += UnityARSessionNativeInterface_ARImageAnchorAddedEvent;
             UnityARSessionNativeInterface.ARImageAnchorUpdatedEvent += UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent;
             UnityARSessionNativeInterface.ARImageAnchorRemovedEvent += UnityARSessionNativeInterface_ARImageAnchorRemovedEvent;
             if (dataSetsByName.Count == 1)
             {
                 StartTrackerWithDataSetForTarget(dataSetsByName.Keys.First(), null);
             }
 #endif
         }
References Juniper.ImageTracking.TrackerKeeper.dataSetsByName, Juniper.ImageTracking.TrackerKeeper.manageVuforiaFrameRate, System.ScreenDebugger.Print(), Juniper.ImageTracking.TrackerKeeper.Register(), Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget(), Juniper.ImageTracking.TrackerKeeper.targets, Juniper.ImageTracking.TrackerKeeper.targetsByName, Juniper.ImageTracking.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorAddedEvent(), Juniper.ImageTracking.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorRemovedEvent(), Juniper.ImageTracking.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent(), and Juniper.ImageTracking.TrackerKeeper.xr.
StartTracker()
void Juniper.ImageTracking.TrackerKeeper.StartTracker ()
Starts the tracker without changing any dataset data that has already been configured.
StartTrackerCoroutine()
IEnumerator Juniper.ImageTracking.TrackerKeeper.StartTrackerCoroutine (string dataSetName, string targetName) inline private
Initializes tracking of a specific target.
Returns
The tracker coroutine.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 492 of file TrackerKeeper.cs.
         {
             if (!VuforiaConfiguration.Instance.Vuforia.DelayedInitialization)
             {
                 VuforiaBehaviour.Instance.enabled = true;
                 yield return WaitForNotInitializing;
             }
             else
             {
                 VuforiaConfiguration.Instance.Vuforia.DelayedInitialization = false;
                 for (int i = 1; i <= VUFORIA_INIT_ATTEMPTS && VuforiaRuntime.Instance.InitializationState != VuforiaRuntime.InitState.INITIALIZED; ++i)
                 {
                     if (i > 1)
                     {
                         Debug.LogFormat("Initializating Vuforia failed. Retrying ({0} of {1})", i, VUFORIA_INIT_ATTEMPTS);
                         VuforiaRuntime.Instance.Deinit();
                     }
                     else
                     {
                         Debug.LogFormat("Initializing Vuforia ({0} of {1})", i, VUFORIA_INIT_ATTEMPTS);
                     }
                     if (VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.NOT_INITIALIZED)
                     {
                         VuforiaRuntime.Instance.InitVuforia();
                         VuforiaBehaviour.Instance.enabled = true;
                     }
                     yield return WaitForNotInitializing;
                 }
             }
             if (VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.INITIALIZED)
             {
                 yield return WaitForTracker;
                 if (tracker.IsActive)
                 {
                     tracker.Stop();
                     yield return new WaitUntil(() => !tracker.IsActive);
                 }
                 EnableDataSet(dataSetName);
                 if (!tracker.IsActive)
                 {
                     tracker.Start();
                     yield return new WaitUntil(() =>
                         tracker.IsActive);
                 }
             }
             else
             {
                 Debug.LogError("Failed to initialize Vuforia.");
             }
         }
References Juniper.ImageTracking.TrackerKeeper.EnableDataSet(), Juniper.ImageTracking.TrackerKeeper.tracker, Juniper.ImageTracking.TrackerKeeper.VUFORIA_INIT_ATTEMPTS, Juniper.ImageTracking.TrackerKeeper.WaitForNotInitializing, and Juniper.ImageTracking.TrackerKeeper.WaitForTracker.
Referenced by Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget().
StartTrackerDelayed()
void Juniper.ImageTracking.TrackerKeeper.StartTrackerDelayed () private
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
StartTrackerWithDataSet()
void Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSet (string dataSetName) inline
Initializes tracking of a set of targets.
Parameters
dataSetName Data set name.
Definition at line 745 of file TrackerKeeper.cs.
         {
             ScreenDebugger.Print($"Activating data set: {dataSetName}");
             StartTrackerWithDataSetForTarget(dataSetName, null);
         }
References System.ScreenDebugger.Print(), and Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget().
StartTrackerWithDataSetForTarget()
void Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget (string dataSetName, string targetName) inline
Initializes tracking of a specific target.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 756 of file TrackerKeeper.cs.
         {
             onTrackingStarting?.Invoke();
             var keyboard = ComponentExt.FindAny<RunningMovement>();
             if (keyboard != null)
             {
                 keyboard.Destroy();
             }
 #if VUFORIA
             StartCoroutine(StartTrackerCoroutine(dataSetName, targetName));
 #elif ARKIT
             if (dataSetsByName.ContainsKey(dataSetName))
             {
                 var dataSet = dataSetsByName[dataSetName];
                 var camMgr = ComponentExt.FindAny<UnityARCameraManager>();
                 if (camMgr == null)
                 {
                     Debug.LogError("No Unity AR Camera Manager!");
                 }
                 else
                 {
                     camMgr.detectionImages = dataSet;
                 }
                 Tracking = true;
             }
 #endif
             Update();
         }
References Juniper.ImageTracking.TrackerKeeper.dataSetsByName, Juniper.ImageTracking.TrackerKeeper.onTrackingStarting, Juniper.ImageTracking.TrackerKeeper.StartTrackerCoroutine(), Juniper.ImageTracking.TrackerKeeper.Tracking, and Juniper.ImageTracking.TrackerKeeper.Update().
Referenced by Juniper.ImageTracking.TrackerKeeper.Start(), and Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSet().
StopTracking()
void Juniper.ImageTracking.TrackerKeeper.StopTracking () inline private
Cancel tracking and disable Vuforia. This also forces the Lost event on all of the currently tracked targets.
Definition at line 348 of file TrackerKeeper.cs.
         {
             if (targets != null)
             {
                 foreach (var target in targets)
                 {
                     var modelBehaviour = target.GetComponent<ModelTargetBehaviour>();
                     if (modelBehaviour != null)
                     {
                         modelBehaviour.enabled = false;
                     }
                 }
             }
             ResetPET();
             if (tracker != null && tracker.IsActive)
             {
                 tracker.Stop();
             }
             if (Tracking)
             {
                 VuforiaBehaviour.Instance.enabled = false;
             }
             if (targets != null)
             {
                 foreach (var target in targets)
                 {
                     target.ForceLost();
                 }
             }
         }
References Juniper.ImageTracking.TrackerKeeper.ResetPET(), Juniper.ImageTracking.TrackerKeeper.targets, Juniper.ImageTracking.TrackerKeeper.tracker, and Juniper.ImageTracking.TrackerKeeper.Tracking.
Referenced by Juniper.ImageTracking.TrackerKeeper.Reset(), and Juniper.ImageTracking.TrackerKeeper.Update().
TargetFinder()
UnityAction Juniper.ImageTracking.TrackerKeeper.TargetFinder (TrackableFoundEventHandler target) private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Referenced by Juniper.ImageTracking.TrackerKeeper.Register().
TargetLoser()
UnityAction Juniper.ImageTracking.TrackerKeeper.TargetLoser (TrackableFoundEventHandler target) private
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
Returns
The loser.
Parameters
target Target.
Referenced by Juniper.ImageTracking.TrackerKeeper.Register().
TargetProximity()
UnityAction Juniper.ImageTracking.TrackerKeeper.TargetProximity (TrackableFoundEventHandler target) private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Referenced by Juniper.ImageTracking.TrackerKeeper.Register().
TargetSafe()
UnityAction Juniper.ImageTracking.TrackerKeeper.TargetSafe (TrackableFoundEventHandler target) private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Referenced by Juniper.ImageTracking.TrackerKeeper.Register().
UnityARSessionNativeInterface_ARImageAnchorAddedEvent()
void Juniper.ImageTracking.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorAddedEvent (ARImageAnchor anchorData) private
An event handler for the first time an image is found by ARKit.
Parameters
anchorData Anchor data.
Referenced by Juniper.ImageTracking.TrackerKeeper.Start().
UnityARSessionNativeInterface_ARImageAnchorRemovedEvent()
void Juniper.ImageTracking.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorRemovedEvent (ARImageAnchor anchorData) private
An event handler that executes when ARKit loses track of an image.
Parameters
anchorData Anchor data.
Referenced by Juniper.ImageTracking.TrackerKeeper.Start().
UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent()
void Juniper.ImageTracking.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent (ARImageAnchor anchorData) private
An event handler that executes every time ARKit updates its understanding of an image.
Parameters
anchorData Anchor data.
Referenced by Juniper.ImageTracking.TrackerKeeper.Start().
Update()
void Juniper.ImageTracking.TrackerKeeper.Update () inline
Checks the current tracking status and fires the events to indicate any change in the tracking status.
Definition at line 255 of file TrackerKeeper.cs.
         {
 #if VUFORIA
             bool cameraRendering = VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.INITIALIZED
                 && VuforiaBehaviour.Instance.enabled
                 && VuforiaRenderer.Instance.VideoBackgroundTexture != null;
             Tracking = cameraRendering
                  && numUpdates > Application.targetFrameRate
                  && tracker != null
                  && tracker.IsActive;
             if (cameraRendering)
             {
                 ++numUpdates;
             }
 #endif
             if (Tracking && !wasTracking)
             {
                 xr.StartAR();
 #if VUFORIA
                 if (manageVuforiaFrameRate)
                 {
                     Application.targetFrameRate = 30;
                 }
                 if (firstTime)
                 {
                     firstTime = false;
                     StopTracking();
                     if (tracker != null)
                     {
                         tracker.Start();
                     }
                     VuforiaBehaviour.Instance.enabled = true;
                 }
 #endif
                 onTrackingStarted?.Invoke();
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         target.onFound?.Invoke();
                         if (!target.Safe)
{
                             target.onProximity?.Invoke();
                         }
                     }
                 }
                 if (targets.All(target => !target.Found))
                 {
                     OnAllTargetsLost();
                 }
             }
             else if (!Tracking && wasTracking)
             {
                 onTrackingStopped?.Invoke();
 #if VUFORIA
                 if (manageVuforiaFrameRate)
                 {
                     Application.targetFrameRate = 60;
                 }
                 numUpdates = 0;
 #endif
                 xr.StopAR();
             }
             wasTracking = Tracking;
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.ImageTracking.TrackerKeeper.DebugReport, Juniper.ImageTracking.TrackerKeeper.firstTime, Juniper.ImageTracking.TrackerKeeper.manageVuforiaFrameRate, Juniper.ImageTracking.TrackerKeeper.numUpdates, Juniper.ImageTracking.TrackerKeeper.OnAllTargetsLost(), Juniper.ImageTracking.TrackerKeeper.onTrackingStarted, Juniper.ImageTracking.TrackerKeeper.onTrackingStopped, Juniper.ImageTracking.TrackerKeeper.PrintDebugReport(), Juniper.XRSystem.StartAR(), Juniper.XRSystem.StopAR(), Juniper.ImageTracking.TrackerKeeper.StopTracking(), Juniper.ImageTracking.TrackerKeeper.targets, Juniper.ImageTracking.TrackerKeeper.tracker, Juniper.ImageTracking.TrackerKeeper.Tracking, Juniper.ImageTracking.TrackerKeeper.wasTracking, and Juniper.ImageTracking.TrackerKeeper.xr.
Referenced by Juniper.ImageTracking.TrackerKeeper.Reset(), and Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget().
WithTarget()
void Juniper.ImageTracking.TrackerKeeper.WithTarget (string label, ARImageAnchor anchorData, Action< TrackableFoundEventHandler > act = null) inline private
Finds a target object by name and updates its state.
Parameters
label A label to aid in debugging.
anchorData Anchor data.
act The action to perform once the target is found.
Definition at line 560 of file TrackerKeeper.cs.
         {
             var tracking = Tracking ? "tracking" : "not tracking";
             ScreenDebugger.Print($"{label} {anchorData.referenceImageName} [{tracking}]");
             if (Tracking)
             {
                 var targetName = anchorData.referenceImageName;
                 if (targetsByName.ContainsKey(targetName))
                 {
                     var target = targetsByName[targetName];
                     act?.Invoke(target);
                     target.transform.position = UnityARMatrixOps.GetPosition(anchorData.transform);
                     target.transform.rotation = UnityARMatrixOps.GetRotation(anchorData.transform);
                 }
                 else
                 {
                     ScreenDebugger.Print($"Couldn't find {targetName}");
                     ScreenDebugger.Print($"Names we recognize: {string.Join(", ", targetsByName.Keys.ToArray())}");
                 }
             }
         }
References System.ScreenDebugger.Print(), Juniper.ImageTracking.TrackerKeeper.targetsByName, and Juniper.ImageTracking.TrackerKeeper.Tracking.
Member Data Documentation
dataSetsByName
Dictionary<string, ARReferenceImagesSet> Juniper.ImageTracking.TrackerKeeper.dataSetsByName private
On ARKit, a lookup of the image sets by name.
Definition at line 75 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Start(), and Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget().
DebugReport
bool Juniper.ImageTracking.TrackerKeeper.DebugReport
Set to true to print out a debug report on the screen.
Definition at line 102 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
done
bool Juniper.ImageTracking.TrackerKeeper.done private
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
Definition at line 107 of file TrackerKeeper.cs.
firstTime
bool Juniper.ImageTracking.TrackerKeeper.firstTime = true private
Used for reseting Vuforia's tracker the first time the application is started.
Definition at line 41 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
hadAnyTargets
bool Juniper.ImageTracking.TrackerKeeper.hadAnyTargets private
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
Definition at line 82 of file TrackerKeeper.cs.
manageVuforiaFrameRate
bool Juniper.ImageTracking.TrackerKeeper.manageVuforiaFrameRate = true
Set to true to set the target framerate lower than normal when the tracker is active.
Definition at line 48 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Start(), and Juniper.ImageTracking.TrackerKeeper.Update().
numUpdates
int Juniper.ImageTracking.TrackerKeeper.numUpdates = 0 private
The number updates to the AR Background Image texture since tracking started. This value is used to delay switching from camera initialization to the app until after we are sure the camera is really ready.
Definition at line 63 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
onAllTargetsLost
UnityEvent Juniper.ImageTracking.TrackerKeeper.onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
Definition at line 167 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.OnAllTargetsLost().
onAnyTargetFound
UnityEvent Juniper.ImageTracking.TrackerKeeper.onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
Definition at line 151 of file TrackerKeeper.cs.
onTargetFound
TransformEvent Juniper.ImageTracking.TrackerKeeper.onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
Definition at line 156 of file TrackerKeeper.cs.
onTargetLost
TransformEvent Juniper.ImageTracking.TrackerKeeper.onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
Definition at line 161 of file TrackerKeeper.cs.
onTargetProximity
TransformEvent Juniper.ImageTracking.TrackerKeeper.onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Definition at line 177 of file TrackerKeeper.cs.
onTargetSafe
TransformEvent Juniper.ImageTracking.TrackerKeeper.onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
Definition at line 172 of file TrackerKeeper.cs.
onTrackingStarted
UnityEvent Juniper.ImageTracking.TrackerKeeper.onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
Definition at line 135 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
onTrackingStarting
UnityEvent Juniper.ImageTracking.TrackerKeeper.onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
Definition at line 130 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget().
onTrackingStopped
UnityEvent Juniper.ImageTracking.TrackerKeeper.onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
Definition at line 145 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
onTrackingStopping
UnityEvent Juniper.ImageTracking.TrackerKeeper.onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
Definition at line 140 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Reset().
targets
readonly List<TrackableFoundEventHandler> Juniper.ImageTracking.TrackerKeeper.targets = new List<TrackableFoundEventHandler>() private
All of the targets in the system.
Definition at line 87 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Register(), Juniper.ImageTracking.TrackerKeeper.Start(), Juniper.ImageTracking.TrackerKeeper.StopTracking(), and Juniper.ImageTracking.TrackerKeeper.Update().
targetsByName
Dictionary<string, TrackableFoundEventHandler> Juniper.ImageTracking.TrackerKeeper.targetsByName private
On ARKit, a lookup of targets by name.
Definition at line 70 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Start(), and Juniper.ImageTracking.TrackerKeeper.WithTarget().
tracker
ObjectTracker Juniper.ImageTracking.TrackerKeeper.tracker private
The Vuforia Tracker API.
Definition at line 31 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.EnableDataSet(), Juniper.ImageTracking.TrackerKeeper.LoadDataSet(), Juniper.ImageTracking.TrackerKeeper.PrintDebugReport(), Juniper.ImageTracking.TrackerKeeper.ResetPET(), Juniper.ImageTracking.TrackerKeeper.StartTrackerCoroutine(), Juniper.ImageTracking.TrackerKeeper.StopTracking(), and Juniper.ImageTracking.TrackerKeeper.Update().
usePET
bool Juniper.ImageTracking.TrackerKeeper.usePET
Set to true to enable using Vuforia's Persistent Extended Tracking.
Definition at line 36 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.EnablePETCoroutine().
usingPET
bool Juniper.ImageTracking.TrackerKeeper.usingPET private
Is set to true when Persistent Extended Tracking is active.
Definition at line 56 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.EnablePETCoroutine(), Juniper.ImageTracking.TrackerKeeper.PrintDebugReport(), and Juniper.ImageTracking.TrackerKeeper.ResetPET().
VUFORIA_INIT_ATTEMPTS
const int Juniper.ImageTracking.TrackerKeeper.VUFORIA_INIT_ATTEMPTS = 3 private
The number of times to attempt initializing Vuforia before just giving up.
Definition at line 26 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.StartTrackerCoroutine().
wasTracking
bool Juniper.ImageTracking.TrackerKeeper.wasTracking private
The value of Tracking from the previous frame, to detect changes.
Definition at line 97 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Update().
xr
XRSystem Juniper.ImageTracking.TrackerKeeper.xr private
Definition at line 179 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.TrackerKeeper.Start(), and Juniper.ImageTracking.TrackerKeeper.Update().
Property Documentation
HasTargets
bool Juniper.ImageTracking.TrackerKeeper.HasTargets get
Returns true when there are any GoodTargets.
true if has targets; otherwise, false.
Definition at line 694 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Safe
bool Juniper.ImageTracking.TrackerKeeper.Safe get
This value is set to true when the user is at a safe distance from the target.
Definition at line 712 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found && !target.Safe)
                     {
                         return false;
                     }
                 }
                 return true;
             }
         }
TargetFound
bool Juniper.ImageTracking.TrackerKeeper.TargetFound get
Returns true when any target has been found and is tracking.
Definition at line 113 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Tracking
bool Juniper.ImageTracking.TrackerKeeper.Tracking get private set
Is set to true when the tracking system is initialized and running.
Definition at line 92 of file TrackerKeeper.cs.
 { get; private set; }
Referenced by Juniper.ImageTracking.TrackerKeeper.OnAllTargetsLost(), Juniper.ImageTracking.TrackerKeeper.Reset(), Juniper.ImageTracking.TrackerKeeper.StartTrackerWithDataSetForTarget(), Juniper.ImageTracking.TrackerKeeper.StopTracking(), Juniper.ImageTracking.TrackerKeeper.Update(), and Juniper.ImageTracking.TrackerKeeper.WithTarget().
WaitForNotInitializing
WaitUntil Juniper.ImageTracking.TrackerKeeper.WaitForNotInitializing get private
What for Vuforia's initialization state to no longer be "INITIALIZING".
The wait for not initializing.
Definition at line 478 of file TrackerKeeper.cs.
         {
             get
             {
                 return new WaitUntil(() =>
                     VuforiaRuntime.Instance.InitializationState != VuforiaRuntime.InitState.INITIALIZING);
             }
         }
Referenced by Juniper.ImageTracking.TrackerKeeper.StartTrackerCoroutine().
WaitForTracker
IEnumerator Juniper.ImageTracking.TrackerKeeper.WaitForTracker get private
A coroutine that waits for a Vuforia ObjectTracker to become available.
The wait for tracker.
Definition at line 428 of file TrackerKeeper.cs.
         {
             get
             {
                 return new WaitUntil(() =>
                 {
                     if (tracker == null)
                     {
                         tracker = TrackerManager.Instance.GetTracker<ObjectTracker>();
                     }
                     return tracker != null;
                 });
             }
         }
Referenced by Juniper.ImageTracking.TrackerKeeper.EnablePETCoroutine(), and Juniper.ImageTracking.TrackerKeeper.StartTrackerCoroutine().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Unity/ImageTracking/TrackerKeeper.cs