Juniper: Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller Class Reference
Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller Class Reference
An editor to respond to changes in XRSystem.
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void ShowJuniperWindow ()
Static Private Member Functions
static void DrawRequiredPackages (UnityPackageManifest manifest, PackageReference[] requiredPackages)
static void DrawStatus (PlatformType selectedPlatform, BuildTargetGroup targetGroup)
Private Attributes
const string MENU_NAME = "Juniper/"
const int buttonWidthValue = 100
Static Private Attributes
static readonly GUIContent TITLE = new GUIContent("Juniper")
static readonly GUILayoutOption nameFieldWidth = GUILayout.Width(200)
static readonly GUILayoutOption buttonWidth = GUILayout.Width(buttonWidthValue)
static readonly TableView requiredPackageTable
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 22 of file JuniperRequirePackageInstaller.cs.
Member Function Documentation
DrawRequiredPackages()
static void Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages (UnityPackageManifest manifest, PackageReference [] requiredPackages) inline static private
Definition at line 73 of file JuniperRequirePackageInstaller.cs.
         {
             var needsInstall = from req in requiredPackages
                                where (req.ForRemoval
                                     && manifest.ContainsKey(req.PackageID))
                                 || (!req.ForRemoval
                                     && !Project.IsInstalled(req))
                                orderby req.Source, req.PackageID, req.VersionSpec
                                select req;
             using (requiredPackageTable.Begin())
             {
                 var drawn = 0;
                 foreach (var req in needsInstall)
                 {
                     ++drawn;
                     using (new HGroup())
                     {
                         var isAvailable = Project.IsAvailable(req) || req.ForRemoval;
                         EditorGUILayout.LabelField(req.Source.ToString(), nameFieldWidth);
                         EditorGUILayout.LabelField(req.Name);
                         EditorGUILayout.LabelField(req.VersionSpec, nameFieldWidth);
                         using (new EnabledScope(isAvailable))
{
                             if (GUILayout.Button(isAvailable
                                 ? req.ForRemoval
                                     ? "Remove"
                                     : "Install"
                                 : "Not available", buttonWidth))
{
                                 if (req.ForRemoval)
{
                                     manifest.Remove(req);
                                 }
                                 else
{
                                     var pkg = Project.PackageDatabase.ContainsKey(req.PackageID)
                                         ? Project.PackageDatabase[req.PackageID].FirstOrDefault(req.Equals)
                                         : null;
                                     if (pkg is null)
{
                                         Debug.LogWarning("Couldn't find pakage " + req);
                                     }
                                     else
{
                                         pkg.Install();
                                     }
                                 }
                             }
                         }
                     }
                 }
                 if (drawn == 0)
                 {
                     EditorGUILayout.LabelField("None", EditorStyles.centeredGreyMiniLabel);
                 }
             }
         }
References UnityEditor.TableView.Begin(), Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.buttonWidth, Juniper.ConfigurationManagement.UnityPackageManifest.ContainsKey(), Juniper.XR.Debug, Juniper.ConfigurationManagement.Project.IsAvailable(), Juniper.ConfigurationManagement.Project.IsInstalled(), Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.nameFieldWidth, Juniper.ConfigurationManagement.Project.PackageDatabase, Juniper.ConfigurationManagement.UnityPackageManifest.Remove(), Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.requiredPackageTable, and Juniper.ConfigurationManagement.PackageReference.Source.
Referenced by Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.OnGUI().
DrawStatus()
static void Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawStatus (PlatformType selectedPlatform, BuildTargetGroup targetGroup) inline static private
Definition at line 135 of file JuniperRequirePackageInstaller.cs.
         {
             using (new Header("Status"))
             {
                 EditorGUILayoutExt.LabeledField("Current platform", nameFieldWidth, selectedPlatform, nameFieldWidth);
                 EditorGUILayoutExt.LabeledField("Current build target", nameFieldWidth, targetGroup, nameFieldWidth);
             }
         }
References Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.nameFieldWidth.
Referenced by Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.OnGUI().
OnGUI()
void Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.OnGUI () inline
Definition at line 46 of file JuniperRequirePackageInstaller.cs.
         {
             titleContent = TITLE;
             if (EditorApplication.isCompiling)
             {
                 EditorGUILayout.LabelField("Compiling...");
             }
             else
             {
                 var platforms = Platforms.Load();
                 var selectedPlatform = ProjectConfiguration.Platform;
                 var currentConfiguration = platforms.Configurations[selectedPlatform];
                 var targetGroup = currentConfiguration.GetTargetGroup();
                 DrawStatus(selectedPlatform, targetGroup);
                 var manifest = UnityPackageManifest.Load();
                 var requiredPackages = platforms.Packages
                     .Union(currentConfiguration.Packages)
                     .ToArray();
                 DrawRequiredPackages(manifest, requiredPackages);
             }
         }
References Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages(), Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawStatus(), Juniper.ConfigurationManagement.Platforms.Load(), Juniper.ConfigurationManagement.UnityPackageManifest.Load(), Juniper.ProjectConfiguration.Platform, and Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.TITLE.
ShowJuniperWindow()
static void Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.ShowJuniperWindow () inline static
Definition at line 25 of file JuniperRequirePackageInstaller.cs.
         {
             EditorWindow.GetWindow<JuniperRequiredPackageInstaller>();
         }
Member Data Documentation
buttonWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.buttonWidth = GUILayout.Width(buttonWidthValue) static private
Definition at line 36 of file JuniperRequirePackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages().
buttonWidthValue
const int Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.buttonWidthValue = 100 private
Definition at line 33 of file JuniperRequirePackageInstaller.cs.
MENU_NAME
const string Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.MENU_NAME = "Juniper/" private
Definition at line 30 of file JuniperRequirePackageInstaller.cs.
nameFieldWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.nameFieldWidth = GUILayout.Width(200) static private
Definition at line 35 of file JuniperRequirePackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages(), and Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawStatus().
requiredPackageTable
readonly TableView Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.requiredPackageTable static private
Initial value:
= new TableView(
            "Required Packages",
            ("Source", nameFieldWidth),
            ("Name", null),
            ("Version", nameFieldWidth),
            ("", buttonWidth)
        )
Definition at line 38 of file JuniperRequirePackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages().
TITLE
readonly GUIContent Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.TITLE = new GUIContent("Juniper") static private
Definition at line 31 of file JuniperRequirePackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.OnGUI().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Editor Plugins/ConfigurationManagement/JuniperRequirePackageInstaller.cs