Juniper: Juniper.EditableDateTime Struct Reference
Juniper.EditableDateTime Struct Reference
A wrapper around System.DateTime that makes it possible to edit values in the Unity Editor.
Public Member Functions
EditableDateTime (DateTime time)
Initializes a new structure for editing DateTime values in the Unity Editor.
override bool Equals (object obj)
Determines whether the specified object is equal to the current UnityEngine.EditableDateTime.
bool Equals (EditableDateTime edt)
bool Equals (DateTime dt)
override int GetHashCode ()
Serves as a hash function for a UnityEngine.EditableDateTime object.
Static Public Member Functions
static implicit operator DateTime (EditableDateTime val)
Automatically convert the EditableDateTime to a DateTime, meaning you can use an EditableDateTime anywhere you can use a DateTime.
static implicit operator EditableDateTime (DateTime val)
Automatically convert the DateTime to an EditableDateTime, meaning you can use an DateTime anywhere you can use a EditableDateTime.
static bool operator== (EditableDateTime a, EditableDateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified UnityEngine.EditableDateTime.
static bool operator != (EditableDateTime a, EditableDateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified UnityEngine.EditableDateTime.
static bool operator== (EditableDateTime a, DateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified System.DateTime.
static bool operator != (EditableDateTime a, DateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified System.DateTime.
static bool operator== (DateTime a, EditableDateTime b)
Determines whether a specified instance of System.DateTime is equal to another specified UnityEngine.EditableDateTime.
static bool operator != (DateTime a, EditableDateTime b)
Determines whether a specified instance of System.DateTime is not equal to another specified UnityEngine.EditableDateTime.
Public Attributes
DateTimeKind Kind
Unspecified, UTC, or Local.
int Year
The year.
Month Month
The month.
int Day
The day. If the day is not valid for the month, it will be reset to the next previous valid day.
int Hour
The hour.
int Minute
The minute.
int Second
The second.
int Millisecond
The millisecond.
Static Public Attributes
static readonly TimeSpan TestOffset = new TimeSpan(0, 0, 0)
When testing applications running at different times, you can set this value to change the time the application thinks it is currently.
static DateTime Now => DateTime.Now + TestOffset
Gets the current system time, plus any TestOffset.
Properties
DateTime Value [get, set]
Gets or sets the underlying DateTime value.
bool Changed [get]
Check to see if the input date values are different from the saved DateTime values.
Private Attributes
DateTime lastValue
The underlying DateTime value.
Detailed Description
A wrapper around System.DateTime that makes it possible to edit values in the Unity Editor.
Definition at line 12 of file EditableDateTime.cs.
Constructor & Destructor Documentation
EditableDateTime()
Juniper.EditableDateTime.EditableDateTime (DateTime time) inline
Initializes a new structure for editing DateTime values in the Unity Editor.
Parameters
time Time.
Definition at line 73 of file EditableDateTime.cs.
         {
             lastValue = time;
             Year = lastValue.Year;
             Month = (Month)lastValue.Month;
             Day = lastValue.Day;
             Hour = lastValue.Hour;
             Minute = lastValue.Minute;
             Second = lastValue.Second;
             Millisecond = lastValue.Millisecond;
             Kind = lastValue.Kind;
         }
References Juniper.EditableDateTime.Day, Juniper.EditableDateTime.Hour, Juniper.EditableDateTime.Kind, Juniper.EditableDateTime.lastValue, Juniper.EditableDateTime.Millisecond, Juniper.EditableDateTime.Minute, Juniper.EditableDateTime.Month, Juniper.EditableDateTime.Second, and Juniper.EditableDateTime.Year.
Referenced by Juniper.EditableDateTime.operator EditableDateTime().
Member Function Documentation
Equals() [1/3]
override bool Juniper.EditableDateTime.Equals (object obj) inline
Determines whether the specified object is equal to the current UnityEngine.EditableDateTime.
Parameters
obj The object to compare with the current UnityEngine.EditableDateTime.
Returns
true if the specified object is equal to the current UnityEngine.EditableDateTime; otherwise, false.
Definition at line 233 of file EditableDateTime.cs.
         {
             return (obj is EditableDateTime edt
                     && Equals(edt))
                 || (obj is DateTime dt
                     && Equals(dt));
         }
Referenced by Juniper.EditableDateTime.operator !=(), and Juniper.EditableDateTime.operator==().
Equals() [2/3]
bool Juniper.EditableDateTime.Equals (EditableDateTime edt) inline
Definition at line 241 of file EditableDateTime.cs.
         {
             return edt.Value == Value;
         }
References Juniper.EditableDateTime.Value.
Equals() [3/3]
bool Juniper.EditableDateTime.Equals (DateTime dt) inline
Definition at line 246 of file EditableDateTime.cs.
         {
             return dt == Value;
         }
References Juniper.EditableDateTime.Value.
GetHashCode()
override int Juniper.EditableDateTime.GetHashCode () inline
Serves as a hash function for a UnityEngine.EditableDateTime object.
Returns
A hash code for this instance that is suitable for use in hashing algorithms and data structures such as a hash table.
Definition at line 258 of file EditableDateTime.cs.
         {
             return Value.GetHashCode();
         }
References Juniper.EditableDateTime.Value.
operator !=() [1/3]
static bool Juniper.EditableDateTime.operator != (EditableDateTime a, EditableDateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are not equal; otherwise, false.
Definition at line 172 of file EditableDateTime.cs.
         {
             return !a.Equals(b);
         }
References Juniper.EditableDateTime.Equals().
operator !=() [2/3]
static bool Juniper.EditableDateTime.operator != (EditableDateTime a, DateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified System.DateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second System.DateTime to compare.
Returns
true if a and b are not equal; otherwise, false.
Definition at line 196 of file EditableDateTime.cs.
         {
             return !a.Equals(b);
         }
References Juniper.EditableDateTime.Equals().
operator !=() [3/3]
static bool Juniper.EditableDateTime.operator != (DateTime a, EditableDateTime b) inline static
Determines whether a specified instance of System.DateTime is not equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first System.DateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are not equal; otherwise, false.
Definition at line 220 of file EditableDateTime.cs.
         {
             return !a.Equals(b);
         }
operator DateTime()
static implicit Juniper.EditableDateTime.operator DateTime (EditableDateTime val) inline static
Automatically convert the EditableDateTime to a DateTime, meaning you can use an EditableDateTime anywhere you can use a DateTime.
Returns
The unwrapped DateTime.
Parameters
val Value.
Definition at line 137 of file EditableDateTime.cs.
         {
             return val.Value;
         }
References Juniper.EditableDateTime.Value.
operator EditableDateTime()
static implicit Juniper.EditableDateTime.operator EditableDateTime (DateTime val) inline static
Automatically convert the DateTime to an EditableDateTime, meaning you can use an DateTime anywhere you can use a EditableDateTime.
Returns
The DateTime, wrapped in an EditableDateTime
Parameters
val Value.
Definition at line 148 of file EditableDateTime.cs.
         {
             return new EditableDateTime(val);
         }
References Juniper.EditableDateTime.EditableDateTime().
operator==() [1/3]
static bool Juniper.EditableDateTime.operator== (EditableDateTime a, EditableDateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are equal; otherwise, false.
Definition at line 160 of file EditableDateTime.cs.
         {
             return a.Equals(b);
         }
References Juniper.EditableDateTime.Equals().
operator==() [2/3]
static bool Juniper.EditableDateTime.operator== (EditableDateTime a, DateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified System.DateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second System.DateTime to compare.
Returns
true if a and b are equal; otherwise, false.
Definition at line 184 of file EditableDateTime.cs.
         {
             return a.Equals(b);
         }
References Juniper.EditableDateTime.Equals().
operator==() [3/3]
static bool Juniper.EditableDateTime.operator== (DateTime a, EditableDateTime b) inline static
Determines whether a specified instance of System.DateTime is equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first System.DateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are equal; otherwise, false.
Definition at line 208 of file EditableDateTime.cs.
         {
             return a.Equals(b);
         }
Member Data Documentation
Day
int Juniper.EditableDateTime.Day
The day. If the day is not valid for the month, it will be reset to the next previous valid day.
Definition at line 43 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
Hour
int Juniper.EditableDateTime.Hour
The hour.
Definition at line 49 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
Kind
DateTimeKind Juniper.EditableDateTime.Kind
Unspecified, UTC, or Local.
Definition at line 25 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
lastValue
DateTime Juniper.EditableDateTime.lastValue private
The underlying DateTime value.
Definition at line 266 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
Millisecond
int Juniper.EditableDateTime.Millisecond
The millisecond.
Definition at line 67 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
Minute
int Juniper.EditableDateTime.Minute
The minute.
Definition at line 55 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
Month
Month Juniper.EditableDateTime.Month
The month.
Definition at line 36 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
Now
DateTime Juniper.EditableDateTime.Now => DateTime.Now + TestOffset static
Gets the current system time, plus any TestOffset.
The now.
Definition at line 90 of file EditableDateTime.cs.
Referenced by Juniper.World.GIS.SunPosition.GetTime(), Juniper.World.GIS.GPSLocation.PrintDebugReport(), and Juniper.World.Climate.Weather.Update().
Second
int Juniper.EditableDateTime.Second
The second.
Definition at line 61 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
TestOffset
readonly TimeSpan Juniper.EditableDateTime.TestOffset = new TimeSpan(0, 0, 0) static
When testing applications running at different times, you can set this value to change the time the application thinks it is currently.
Definition at line 20 of file EditableDateTime.cs.
Year
int Juniper.EditableDateTime.Year
The year.
Definition at line 31 of file EditableDateTime.cs.
Referenced by Juniper.EditableDateTime.EditableDateTime().
Property Documentation
Changed
bool Juniper.EditableDateTime.Changed get private
Check to see if the input date values are different from the saved DateTime values.
true if any of the values are different, false otherwise.
Definition at line 273 of file EditableDateTime.cs.
         {
             get
             {
                 return Year != lastValue.Year
                     || Month != (Month)lastValue.Month
                     || Day != lastValue.Day
                     || Hour != lastValue.Hour
                     || Minute != lastValue.Minute
                     || Second != lastValue.Second
                     || Millisecond != lastValue.Millisecond
                     || Kind != lastValue.Kind;
             }
         }
Value
DateTime Juniper.EditableDateTime.Value get set
Gets or sets the underlying DateTime value.
The value.
Definition at line 97 of file EditableDateTime.cs.
         {
             get
             {
                 if (Changed)
                 {
                     if ((int)Month < 1 || 12 < (int)Month
                         || Year < 1 || 9999 < Year
                         || Day == 0)
                     {
                         Value = DateTime.Now;
                     }
                     Day = Math.Min(Day, DateTime.DaysInMonth(Year, (int)Month));
                     lastValue = new DateTime(Year, (int)Month, Day, Hour, Minute, Second, Millisecond, Kind);
                 }
                 return lastValue;
             }
             set
             {
                 lastValue = value;
                 Year = value.Year;
                 Month = (Month)value.Month;
                 Day = value.Day;
                 Hour = value.Hour;
                 Minute = value.Minute;
                 Second = value.Second;
                 Millisecond = value.Millisecond;
                 Kind = value.Kind;
             }
         }
Referenced by Juniper.EditableDateTime.Equals(), Juniper.EditableDateTime.GetHashCode(), Juniper.World.GIS.SunPosition.GetTime(), and Juniper.EditableDateTime.operator DateTime().
The documentation for this struct was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Unity/EditableDateTime.cs