Juniper: Juniper.Units.Minutes Class Reference
Juniper.Units.Minutes Class Reference
Conversions from minutes
Static Public Member Functions
static float Milliseconds (float minutes)
Convert from minutes to milliseconds.
static float Seconds (float minutes)
Convert from minutes to seconds.
static float Hours (float minutes)
Convert from minutes to hours.
static float Days (float minutes)
Convert from minutes to days.
static float Hertz (float minutes)
Convert from minutes to hertz.
Public Attributes
const float PER_MILLISECOND = 1 / Units.Milliseconds.PER_MINUTE
Conversion factor from milliseconds to minutes.
const float PER_SECOND = 1 / Units.Seconds.PER_MINUTE
Conversion factor from seconds to minutes.
const float PER_HOUR = 60
Conversion factor from hours to minutes.
const float PER_DAY = PER_HOUR * Units.Hours.PER_DAY
Conversion factor from days to minutes.
Detailed Description
Conversions from minutes
Definition at line 8 of file Minutes.cs.
Member Function Documentation
Days()
static float Juniper.Units.Minutes.Days (float minutes) inline static
Convert from minutes to days.
Parameters
minutes The number of minutes
Returns
The number of days
Definition at line 65 of file Minutes.cs.
             {
                 return minutes * Units.Days.PER_MINUTE;
             }
References Juniper.Units.Days.PER_MINUTE.
Hertz()
static float Juniper.Units.Minutes.Hertz (float minutes) inline static
Convert from minutes to hertz.
Parameters
minutes The number of minutes
Returns
The number of hertz
Definition at line 75 of file Minutes.cs.
             {
                 return Units.Seconds.Hertz(Seconds(minutes));
             }
References Juniper.Units.Seconds.Hertz(), and Juniper.Units.Minutes.Seconds().
Hours()
static float Juniper.Units.Minutes.Hours (float minutes) inline static
Convert from minutes to hours.
Parameters
minutes The number of minutes
Returns
The number of hours
Definition at line 55 of file Minutes.cs.
             {
                 return minutes * Units.Hours.PER_MINUTE;
             }
References Juniper.Units.Hours.PER_MINUTE.
Milliseconds()
static float Juniper.Units.Minutes.Milliseconds (float minutes) inline static
Convert from minutes to milliseconds.
Parameters
minutes The number of minutes
Returns
The number of milliseconds
Definition at line 35 of file Minutes.cs.
             {
                 return minutes * Units.Milliseconds.PER_MINUTE;
             }
References Juniper.Units.Milliseconds.PER_MINUTE.
Seconds()
static float Juniper.Units.Minutes.Seconds (float minutes) inline static
Convert from minutes to seconds.
Parameters
minutes The number of minutes
Returns
The number of minutes
Definition at line 45 of file Minutes.cs.
             {
                 return minutes * Units.Seconds.PER_MINUTE;
             }
References Juniper.Units.Seconds.PER_MINUTE.
Referenced by Juniper.Units.Minutes.Hertz(), and Juniper.Units.Hertz.Minutes().
Member Data Documentation
PER_DAY
const float Juniper.Units.Minutes.PER_DAY = PER_HOUR * Units.Hours.PER_DAY
Conversion factor from days to minutes.
Definition at line 28 of file Minutes.cs.
Referenced by Juniper.Units.Days.Minutes().
PER_HOUR
const float Juniper.Units.Minutes.PER_HOUR = 60
Conversion factor from hours to minutes.
Definition at line 23 of file Minutes.cs.
Referenced by Juniper.Units.Hours.Minutes().
PER_MILLISECOND
const float Juniper.Units.Minutes.PER_MILLISECOND = 1 / Units.Milliseconds.PER_MINUTE
Conversion factor from milliseconds to minutes.
Definition at line 13 of file Minutes.cs.
Referenced by Juniper.Units.Milliseconds.Minutes().
PER_SECOND
const float Juniper.Units.Minutes.PER_SECOND = 1 / Units.Seconds.PER_MINUTE
Conversion factor from seconds to minutes.
Definition at line 18 of file Minutes.cs.
Referenced by Juniper.Units.Seconds.Minutes().
The documentation for this class was generated from the following file:
Juniper.Units/src/Time/Minutes.cs