Juniper: Juniper.Statistics.SingleStatisticsTests Class Reference
Juniper.Statistics.SingleStatisticsTests Class Reference
Public Member Functions
void MakeABuffer ()
void StartsEmpty ()
void ThrowsWithNoCapacity ()
void AddingIncreasesCount ()
void CanGetBackOutAgain ()
void CanGetBackOutAgain2 ()
void LoopingDoesntGrowSize ()
void LoopingOverwrites ()
void LoopingAgainDoesntGrowSize ()
void LoopingAgainOverwrites ()
void LargerLooping ()
void MaintainsOrder ()
void ShiftsOldValuesOut ()
void ComputesMin ()
void ComputesMax ()
void ComputesMean ()
void ComputesMedian ()
void ComputesTrivialStandardDeviation ()
void ComputesBasicStandardDeviation ()
void ComputesStandardDeviation ()
void CopyUnfullWithoutOffsetThrowsWithTooSmallDestination ()
void CopyUnfullWithOffsetThrowsWithTooSmallDestination ()
void CopyWithNegativeOffsetThrows ()
void CopyWithTooLargeOffsetThrows ()
void CopyUnfullUnwrappedBufferWithoutOffsetMaintainsOrder ()
void CopyUnfullUnwrappedBufferWithOffsetMaintainsOrder ()
void CopyFullUnwrappedBufferWithoutOffsetMaintainsOrder ()
void CopyFullUnwrappedBufferWithOffsetMaintainsOrder ()
void CopyWrappedBufferWithoutOffsetMaintainsOrder ()
void CopyWrappedBufferWithOffsetMaintainsOrder ()
void InsertMaintainsOrder ()
Detailed Description
Definition at line 7 of file SingleStatisticsTests.cs.
Member Function Documentation
AddingIncreasesCount()
void Juniper.Statistics.SingleStatisticsTests.AddingIncreasesCount () inline
Definition at line 25 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(1)
             {
                 5
             };
             Assert.AreEqual(1, buffer.Count);
         }
CanGetBackOutAgain()
void Juniper.Statistics.SingleStatisticsTests.CanGetBackOutAgain () inline
Definition at line 35 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(1)
             {
                 7
             };
             Assert.AreEqual(7, buffer[0]);
         }
CanGetBackOutAgain2()
void Juniper.Statistics.SingleStatisticsTests.CanGetBackOutAgain2 () inline
Definition at line 45 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(5);
             Assert.AreEqual(0, buffer.Count);
             buffer.Add(1);
             Assert.AreEqual(1, buffer.Count);
             Assert.AreEqual(1, buffer[0]);
             buffer.Add(2);
             Assert.AreEqual(2, buffer.Count);
             Assert.AreEqual(1, buffer[0]);
             Assert.AreEqual(2, buffer[1]);
             buffer.Add(3);
             Assert.AreEqual(3, buffer.Count);
             Assert.AreEqual(1, buffer[0]);
             Assert.AreEqual(2, buffer[1]);
             Assert.AreEqual(3, buffer[2]);
             buffer.Add(4);
             Assert.AreEqual(4, buffer.Count);
             Assert.AreEqual(1, buffer[0]);
             Assert.AreEqual(2, buffer[1]);
             Assert.AreEqual(3, buffer[2]);
             Assert.AreEqual(4, buffer[3]);
             buffer.Add(5);
             Assert.AreEqual(5, buffer.Count);
             Assert.AreEqual(1, buffer[0]);
             Assert.AreEqual(2, buffer[1]);
             Assert.AreEqual(3, buffer[2]);
             Assert.AreEqual(4, buffer[3]);
             Assert.AreEqual(5, buffer[4]);
         }
ComputesBasicStandardDeviation()
void Juniper.Statistics.SingleStatisticsTests.ComputesBasicStandardDeviation () inline
Definition at line 238 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 0,
                 2,
                 0,
                 2
             };
             Assert.AreEqual((float)Math.Sqrt(4 / 3f), buffer.StandardDeviation);
         }
ComputesMax()
void Juniper.Statistics.SingleStatisticsTests.ComputesMax () inline
Definition at line 186 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 3,
                 4,
                 1
             };
             Assert.AreEqual(5, buffer.Maximum);
         }
ComputesMean()
void Juniper.Statistics.SingleStatisticsTests.ComputesMean () inline
Definition at line 199 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 3,
                 4,
                 1
             };
             Assert.AreEqual(3.25f, buffer.Mean);
         }
ComputesMedian()
void Juniper.Statistics.SingleStatisticsTests.ComputesMedian () inline
Definition at line 212 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 3,
                 4,
                 1
             };
             Assert.AreEqual(3f, buffer.Median);
         }
ComputesMin()
void Juniper.Statistics.SingleStatisticsTests.ComputesMin () inline
Definition at line 173 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 3,
                 4,
                 1
             };
             Assert.AreEqual(1, buffer.Minimum);
         }
ComputesStandardDeviation()
void Juniper.Statistics.SingleStatisticsTests.ComputesStandardDeviation () inline
Definition at line 251 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 3,
                 4,
                 1
             };
             Assert.AreEqual(1.70782518f, buffer.StandardDeviation);
         }
ComputesTrivialStandardDeviation()
void Juniper.Statistics.SingleStatisticsTests.ComputesTrivialStandardDeviation () inline
Definition at line 225 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 5,
                 5,
                 5
             };
             Assert.AreEqual(0f, buffer.StandardDeviation);
         }
CopyFullUnwrappedBufferWithOffsetMaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.CopyFullUnwrappedBufferWithOffsetMaintainsOrder () inline
Definition at line 371 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3,
                 13
             };
             var arr = new float[5];
             buffer.CopyTo(arr, 1);
             Assert.AreEqual(0, arr[0]);
             Assert.AreEqual(5, arr[1]);
             Assert.AreEqual(7, arr[2]);
             Assert.AreEqual(3, arr[3]);
             Assert.AreEqual(13, arr[4]);
         }
References Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo().
CopyFullUnwrappedBufferWithoutOffsetMaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.CopyFullUnwrappedBufferWithoutOffsetMaintainsOrder () inline
Definition at line 353 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3,
                 13
             };
             var arr = new float[4];
             buffer.CopyTo(arr, 0);
             Assert.AreEqual(5, arr[0]);
             Assert.AreEqual(7, arr[1]);
             Assert.AreEqual(3, arr[2]);
             Assert.AreEqual(13, arr[3]);
         }
References Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo().
CopyUnfullUnwrappedBufferWithOffsetMaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.CopyUnfullUnwrappedBufferWithOffsetMaintainsOrder () inline
Definition at line 336 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3
             };
             var arr = new float[4];
             buffer.CopyTo(arr, 1);
             Assert.AreEqual(0, arr[0]);
             Assert.AreEqual(5, arr[1]);
             Assert.AreEqual(7, arr[2]);
             Assert.AreEqual(3, arr[3]);
         }
References Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo().
CopyUnfullUnwrappedBufferWithoutOffsetMaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.CopyUnfullUnwrappedBufferWithoutOffsetMaintainsOrder () inline
Definition at line 320 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3
             };
             var arr = new float[3];
             buffer.CopyTo(arr, 0);
             Assert.AreEqual(5, arr[0]);
             Assert.AreEqual(7, arr[1]);
             Assert.AreEqual(3, arr[2]);
         }
References Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo().
CopyUnfullWithOffsetThrowsWithTooSmallDestination()
void Juniper.Statistics.SingleStatisticsTests.CopyUnfullWithOffsetThrowsWithTooSmallDestination () inline
Definition at line 278 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3
             };
             var arr = new float[3];
             Assert.Throws<ArgumentException>(() =>
                 buffer.CopyTo(arr, 1));
         }
CopyUnfullWithoutOffsetThrowsWithTooSmallDestination()
void Juniper.Statistics.SingleStatisticsTests.CopyUnfullWithoutOffsetThrowsWithTooSmallDestination () inline
Definition at line 264 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3
             };
             var arr = new float[2];
             Assert.Throws<ArgumentException>(() =>
                 buffer.CopyTo(arr, 0));
         }
CopyWithNegativeOffsetThrows()
void Juniper.Statistics.SingleStatisticsTests.CopyWithNegativeOffsetThrows () inline
Definition at line 292 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3
             };
             var arr = new float[3];
             Assert.Throws<ArgumentOutOfRangeException>(() =>
                 buffer.CopyTo(arr, -1));
         }
CopyWithTooLargeOffsetThrows()
void Juniper.Statistics.SingleStatisticsTests.CopyWithTooLargeOffsetThrows () inline
Definition at line 306 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3
             };
             var arr = new float[3];
             Assert.Throws<ArgumentException>(() =>
                 buffer.CopyTo(arr, 3));
         }
CopyWrappedBufferWithOffsetMaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.CopyWrappedBufferWithOffsetMaintainsOrder () inline
Definition at line 409 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3,
                 13,
                 2
             };
             var arr = new float[5];
             buffer.CopyTo(arr, 1);
             Assert.AreEqual(0, arr[0]);
             Assert.AreEqual(7, arr[1]);
             Assert.AreEqual(3, arr[2]);
             Assert.AreEqual(13, arr[3]);
             Assert.AreEqual(2, arr[4]);
         }
References Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo().
CopyWrappedBufferWithoutOffsetMaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.CopyWrappedBufferWithoutOffsetMaintainsOrder () inline
Definition at line 390 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 7,
                 3,
                 13,
                 2
             };
             var arr = new float[4];
             buffer.CopyTo(arr, 0);
             Assert.AreEqual(7, arr[0]);
             Assert.AreEqual(3, arr[1]);
             Assert.AreEqual(13, arr[2]);
             Assert.AreEqual(2, arr[3]);
         }
References Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo().
InsertMaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.InsertMaintainsOrder () inline
Definition at line 429 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4);
             buffer.Insert(0, 5);
             Assert.AreEqual(5, buffer[0]);
             buffer.Insert(0, 7);
             Assert.AreEqual(7, buffer[0]);
             Assert.AreEqual(5, buffer[1]);
             buffer.Insert(1, 3);
             Assert.AreEqual(7, buffer[0]);
             Assert.AreEqual(3, buffer[1]);
             Assert.AreEqual(5, buffer[2]);
             buffer.Insert(1, 13);
             Assert.AreEqual(7, buffer[0]);
             Assert.AreEqual(13, buffer[1]);
             Assert.AreEqual(3, buffer[2]);
             Assert.AreEqual(5, buffer[3]);
             buffer.Insert(2, 2);
             Assert.AreEqual(13, buffer[0]);
             Assert.AreEqual(3, buffer[1]);
             Assert.AreEqual(2, buffer[2]);
             Assert.AreEqual(5, buffer[3]);
             buffer.Insert(0, 17);
             Assert.AreEqual(17, buffer[0]);
             Assert.AreEqual(3, buffer[1]);
             Assert.AreEqual(2, buffer[2]);
             Assert.AreEqual(5, buffer[3]);
         }
LargerLooping()
void Juniper.Statistics.SingleStatisticsTests.LargerLooping () inline
Definition at line 123 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(100);
             for (var i = 0; i < 120; ++i)
             {
                 buffer.Add(i);
                 Assert.AreEqual(Math.Min(100, i + 1), buffer.Count);
             }
         }
LoopingAgainDoesntGrowSize()
void Juniper.Statistics.SingleStatisticsTests.LoopingAgainDoesntGrowSize () inline
Definition at line 99 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(1)
             {
                 3,
                 2,
                 1
             };
             Assert.AreEqual(1, buffer.Count);
         }
LoopingAgainOverwrites()
void Juniper.Statistics.SingleStatisticsTests.LoopingAgainOverwrites () inline
Definition at line 111 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(1)
             {
                 3,
                 2,
                 1
             };
             Assert.AreEqual(1, buffer[0]);
         }
LoopingDoesntGrowSize()
void Juniper.Statistics.SingleStatisticsTests.LoopingDoesntGrowSize () inline
Definition at line 77 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(1)
             {
                 3,
                 2
             };
             Assert.AreEqual(1, buffer.Count);
         }
LoopingOverwrites()
void Juniper.Statistics.SingleStatisticsTests.LoopingOverwrites () inline
Definition at line 88 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(1)
             {
                 3,
                 2
             };
             Assert.AreEqual(2, buffer[0]);
         }
MaintainsOrder()
void Juniper.Statistics.SingleStatisticsTests.MaintainsOrder () inline
Definition at line 134 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(5)
             {
                 5,
                 3,
                 4,
                 1,
                 2
             };
             Assert.AreEqual(5, buffer[0]);
             Assert.AreEqual(3, buffer[1]);
             Assert.AreEqual(4, buffer[2]);
             Assert.AreEqual(1, buffer[3]);
             Assert.AreEqual(2, buffer[4]);
         }
MakeABuffer()
void Juniper.Statistics.SingleStatisticsTests.MakeABuffer ()
ShiftsOldValuesOut()
void Juniper.Statistics.SingleStatisticsTests.ShiftsOldValuesOut () inline
Definition at line 152 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(4)
             {
                 5,
                 3,
                 4,
                 1
             };
             Assert.AreEqual(5, buffer[0]);
             Assert.AreEqual(3, buffer[1]);
             Assert.AreEqual(4, buffer[2]);
             Assert.AreEqual(1, buffer[3]);
             buffer.Add(2);
             Assert.AreEqual(3, buffer[0]);
             Assert.AreEqual(4, buffer[1]);
             Assert.AreEqual(1, buffer[2]);
             Assert.AreEqual(2, buffer[3]);
         }
References Juniper.Statistics.SingleStatistics.Add().
StartsEmpty()
void Juniper.Statistics.SingleStatisticsTests.StartsEmpty () inline
Definition at line 14 of file SingleStatisticsTests.cs.
         {
             var buffer = new SingleStatistics(100);
             Assert.AreEqual(0, buffer.Count);
         }
ThrowsWithNoCapacity()
void Juniper.Statistics.SingleStatisticsTests.ThrowsWithNoCapacity ()
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Tests/Juniper/Statistics/SingleStatisticsTests.cs