Juniper: Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient Class Reference
Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient Class Reference
Public Member Functions
TextToSpeechClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat, IAudioDecoder audioDecoder, CachingStrategy cache)
TextToSpeechClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat, IAudioDecoder audioDecoder)
async Task< AudioData > GetDecodedAudioAsync (string text, string voiceName, float rateChange, float pitchChange)
Task< AudioData > GetDecodedAudioAsync (string text, Voice voice, float rateChange, float pitchChange)
Task< AudioData > GetDecodedAudioAsync (string text, string voiceName, float rateChange)
Task< AudioData > GetDecodedAudioAsync (string text, Voice voice, float rateChange)
Task< AudioData > GetDecodedAudioAsync (string text, string voiceName)
Task< AudioData > GetDecodedAudioAsync (string text, Voice voice)
async Task< Stream > GetAudioDataStreamAsync (string text, string voiceName, float rateChange=0, float pitchChange=0)
Task< Stream > GetAudioDataStreamAsync (string text, Voice voice, float rateChange=0, float pitchChange=0)
void ClearError ()
async Task< Voice[]> GetVoicesAsync ()
Protected Member Functions
async Task< string > GetAuthTokenAsync ()
Properties
override AudioFormat OutputFormat [get, set]
string AzureRegion [get]
CachingStrategy Cache [get]
bool IsAvailable = true [get, protected set]
Private Member Functions
void CheckDecoderFormat ()
Private Attributes
readonly IAudioDecoder audioDecoder
Detailed Description
Definition at line 9 of file TextToSpeechClient.cs.
Constructor & Destructor Documentation
TextToSpeechClient() [1/2]
Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.TextToSpeechClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat, IAudioDecoder audioDecoder, CachingStrategy cache) inline
Definition at line 13 of file TextToSpeechClient.cs.
             : base(azureRegion, azureSubscriptionKey, azureResourceName, voiceListDecoder, outputFormat, cache)
         {
             this.audioDecoder = audioDecoder
                 ?? throw new ArgumentException("Must provide an audio decoder", nameof(audioDecoder));
             CheckDecoderFormat();
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.audioDecoder, and Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.CheckDecoderFormat().
TextToSpeechClient() [2/2]
Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.TextToSpeechClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat, IAudioDecoder audioDecoder) inline
Definition at line 22 of file TextToSpeechClient.cs.
             : this(azureRegion, azureSubscriptionKey, azureResourceName, voiceListDecoder, outputFormat, audioDecoder, null)
         { }
Member Function Documentation
CheckDecoderFormat()
void Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.CheckDecoderFormat () inline private
Definition at line 41 of file TextToSpeechClient.cs.
         {
             if (audioDecoder.Format != OutputFormat)
             {
                 if (audioDecoder.SupportsFormat(OutputFormat))
                 {
                     audioDecoder.Format = OutputFormat;
                 }
                 else
                 {
                     throw new NotSupportedException($"The provided audio decoder does not support the given output. Decoder: {audioDecoder.Format.Name}. Expected: {OutputFormat.Name}");
                 }
             }
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.audioDecoder, Juniper.Sound.IAudioDecoder.Format, Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.OutputFormat, and Juniper.Sound.IAudioDecoder.SupportsFormat().
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.TextToSpeechClient().
ClearError()
void Juniper.Speech.Azure.CognitiveServices.VoicesClient.ClearError () inline inherited
Definition at line 49 of file VoicesClient.cs.
         {
             IsAvailable = true;
         }
References Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable.
GetAudioDataStreamAsync() [1/2]
async Task<Stream> Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync (string text, string voiceName, float rateChange = 0, float pitchChange = 0) inline inherited
Definition at line 34 of file TextToSpeechStreamClient.cs.
         {
             if (string.IsNullOrEmpty(text))
             {
                 throw new ArgumentException("Must provide some text to generate speech.", nameof(text));
             }
             if (string.IsNullOrEmpty(voiceName))
             {
                 throw new ArgumentException("Must provide a voice to generate speech.", nameof(voiceName));
             }
             try
             {
                 var ttsRequest = new TextToSpeechRequest(AzureRegion, azureResourceName, OutputFormat)
                 {
                     Text = text,
                     VoiceName = voiceName,
                     RateChange = rateChange,
                     PitchChange = pitchChange
                 };
                 if (!Cache.IsCached(ttsRequest))
                 {
                     ttsRequest.AuthToken = await GetAuthTokenAsync()
                         .ConfigureAwait(false);
                 }
                 return await Cache.OpenAsync(ttsRequest)
                     .ConfigureAwait(false);
             }
             catch
             {
                 IsAvailable = false;
                 throw;
             }
         }
References Juniper.Speech.Azure.CognitiveServices.AbstractAzureSpeechRequest< MediaTypeT >.AuthToken, Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion, Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.azureResourceName, Juniper.Speech.Azure.CognitiveServices.VoicesClient.Cache, Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable, Juniper.IO.CachingStrategy.IsCached(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.OutputFormat.
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync().
GetAudioDataStreamAsync() [2/2]
Task<Stream> Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync (string text, Voice voice, float rateChange = 0, float pitchChange = 0) inline inherited
Definition at line 72 of file TextToSpeechStreamClient.cs.
         {
             return GetAudioDataStreamAsync(text, voice?.ShortName, rateChange, pitchChange);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync().
GetAuthTokenAsync()
async Task<string> Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync () inline protected inherited
Definition at line 54 of file VoicesClient.cs.
         {
             try
             {
                 if (string.IsNullOrEmpty(authToken))
                 {
                     var plainText = new StringFactory();
                     var authRequest = new AuthTokenRequest(AzureRegion, azureSubscriptionKey);
                     authToken = await authRequest.DecodeAsync(plainText)
                         .ConfigureAwait(false);
                 }
                 return authToken;
             }
             catch
             {
                 IsAvailable = false;
                 throw;
             }
         }
References Juniper.Speech.Azure.CognitiveServices.VoicesClient.authToken, Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion, Juniper.Speech.Azure.CognitiveServices.VoicesClient.azureSubscriptionKey, and Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable.
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync().
GetDecodedAudioAsync() [1/6]
async Task<AudioData> Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync (string text, string voiceName, float rateChange, float pitchChange) inline
Definition at line 56 of file TextToSpeechClient.cs.
         {
             var stream = await GetAudioDataStreamAsync(text, voiceName, rateChange, pitchChange)
                 .ConfigureAwait(false);
             return audioDecoder.Deserialize(stream);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.audioDecoder, Juniper.IO.IDeserializer< out out ResultT >.Deserialize(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync().
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync(), and Juniper.Sound.AbstractInteractionAudio.PreloadSpeech().
GetDecodedAudioAsync() [2/6]
Task<AudioData> Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync (string text, Voice voice, float rateChange, float pitchChange) inline
Definition at line 63 of file TextToSpeechClient.cs.
         {
             if (voice is null)
             {
                 throw new ArgumentNullException(nameof(voice));
             }
             return GetDecodedAudioAsync(text, voice.ShortName, rateChange, pitchChange);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync(), and Juniper.Speech.Azure.CognitiveServices.Voice.ShortName.
GetDecodedAudioAsync() [3/6]
Task<AudioData> Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync (string text, string voiceName, float rateChange) inline
Definition at line 73 of file TextToSpeechClient.cs.
         {
             return GetDecodedAudioAsync(text, voiceName, rateChange, 0);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync().
GetDecodedAudioAsync() [4/6]
Task<AudioData> Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync (string text, Voice voice, float rateChange) inline
Definition at line 78 of file TextToSpeechClient.cs.
         {
             return GetDecodedAudioAsync(text, voice, rateChange, 0);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync().
GetDecodedAudioAsync() [5/6]
Task<AudioData> Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync (string text, string voiceName) inline
Definition at line 83 of file TextToSpeechClient.cs.
         {
             return GetDecodedAudioAsync(text, voiceName, 0, 0);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync().
GetDecodedAudioAsync() [6/6]
Task<AudioData> Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync (string text, Voice voice) inline
Definition at line 88 of file TextToSpeechClient.cs.
         {
             return GetDecodedAudioAsync(text, voice, 0, 0);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync().
GetVoicesAsync()
async Task<Voice[]> Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync () inline inherited
Definition at line 75 of file VoicesClient.cs.
         {
             try
             {
                 if (voices is null)
                 {
                     var voiceListRequest = new VoiceListRequest(AzureRegion);
                     if (!Cache.IsCached(voiceListRequest))
                     {
                         voiceListRequest.AuthToken = await GetAuthTokenAsync()
                             .ConfigureAwait(false);
                     }
                     voices = await Cache.LoadAsync(voiceListDecoder, voiceListRequest)
                         .ConfigureAwait(false);
                 }
                 return voices;
             }
             catch
             {
                 IsAvailable = false;
                 throw;
             }
         }
References Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion, Juniper.Speech.Azure.CognitiveServices.VoicesClient.Cache, Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable, Juniper.IO.CachingStrategy.IsCached(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.voiceListDecoder, and Juniper.Speech.Azure.CognitiveServices.VoicesClient.voices.
Member Data Documentation
audioDecoder
readonly IAudioDecoder Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.audioDecoder private
Definition at line 11 of file TextToSpeechClient.cs.
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.CheckDecoderFormat(), Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.TextToSpeechClient().
Property Documentation
AzureRegion
string Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion get protected inherited
Definition at line 16 of file VoicesClient.cs.
 { get; }
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.VoicesClient().
Cache
CachingStrategy Juniper.Speech.Azure.CognitiveServices.VoicesClient.Cache get protected inherited
Definition at line 17 of file VoicesClient.cs.
 { get; }
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.VoicesClient().
IsAvailable
bool Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable = true get protected set inherited
Definition at line 47 of file VoicesClient.cs.
 { get; protected set; } = true;
Referenced by Juniper.Speech.Azure.CognitiveServices.VoicesClient.ClearError(), Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync().
OutputFormat
override AudioFormat Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.OutputFormat get set
Definition at line 27 of file TextToSpeechClient.cs.
         {
             get { return base.OutputFormat; }
             set
             {
                 base.OutputFormat = value;
                 if (audioDecoder is object)
                 {
                     CheckDecoderFormat();
                 }
             }
         }
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.CheckDecoderFormat().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Azure/CognitiveServices/TextToSpeechClient.cs