Juniper: Juniper.Mathematics.Matrix3x2Serializable Struct Reference
Juniper.Mathematics.Matrix3x2Serializable Struct Reference
Public Member Functions
Matrix3x2Serializable (float m11, float m12, float m21, float m22, float m31, float m32)
void GetObjectData (SerializationInfo info, StreamingContext context)
override bool Equals (object obj)
bool Equals (Matrix3x2Serializable other)
override int GetHashCode ()
System.Numerics.Matrix3x2 ToSystemMatrix3x2 ()
Static Public Member Functions
static bool operator== (Matrix3x2Serializable left, Matrix3x2Serializable right)
static bool operator != (Matrix3x2Serializable left, Matrix3x2Serializable right)
static implicit operator System.Numerics.Matrix3x2 (Matrix3x2Serializable v)
static operator Matrix3x2Serializable (System.Numerics.Matrix3x2 v)
Properties
float [] Values [get]
Private Member Functions
Matrix3x2Serializable (SerializationInfo info, StreamingContext context)
Static Private Attributes
static readonly string VALUES_FIELD = nameof(Values).ToLowerInvariant()
Detailed Description
Definition at line 8 of file Matrix3x2Serializable.cs.
Constructor & Destructor Documentation
Matrix3x2Serializable() [1/2]
Juniper.Mathematics.Matrix3x2Serializable.Matrix3x2Serializable (float m11, float m12, float m21, float m22, float m31, float m32) inline
Definition at line 15 of file Matrix3x2Serializable.cs.
         {
             Values = new[]
             {
                 m11, m12,
                 m21, m22,
                 m31, m32
             };
         }
References Juniper.Mathematics.Matrix3x2Serializable.Values.
Matrix3x2Serializable() [2/2]
Juniper.Mathematics.Matrix3x2Serializable.Matrix3x2Serializable (SerializationInfo info, StreamingContext context) inline private
Definition at line 26 of file Matrix3x2Serializable.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Values = info.GetValue<float[]>(VALUES_FIELD);
         }
References Juniper.Mathematics.Matrix3x2Serializable.Values, and Juniper.Mathematics.Matrix3x2Serializable.VALUES_FIELD.
Member Function Documentation
Equals() [1/2]
override bool Juniper.Mathematics.Matrix3x2Serializable.Equals (object obj) inline
Definition at line 46 of file Matrix3x2Serializable.cs.
         {
             return obj is Matrix3x2Serializable serializable && Equals(serializable);
         }
Equals() [2/2]
bool Juniper.Mathematics.Matrix3x2Serializable.Equals (Matrix3x2Serializable other) inline
Definition at line 51 of file Matrix3x2Serializable.cs.
         {
             return EqualityComparer<float[]>.Default.Equals(Values, other.Values);
         }
References Juniper.Mathematics.Matrix3x2Serializable.Values.
GetHashCode()
override int Juniper.Mathematics.Matrix3x2Serializable.GetHashCode () inline
Definition at line 56 of file Matrix3x2Serializable.cs.
         {
             return 1291433875 + EqualityComparer<float[]>.Default.GetHashCode(Values);
         }
References Juniper.Mathematics.Matrix3x2Serializable.Values.
GetObjectData()
void Juniper.Mathematics.Matrix3x2Serializable.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 36 of file Matrix3x2Serializable.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(VALUES_FIELD, Values);
         }
References Juniper.Mathematics.Matrix3x2Serializable.Values, and Juniper.Mathematics.Matrix3x2Serializable.VALUES_FIELD.
operator !=()
static bool Juniper.Mathematics.Matrix3x2Serializable.operator != (Matrix3x2Serializable left, Matrix3x2Serializable right) inline static
Definition at line 66 of file Matrix3x2Serializable.cs.
         {
             return !(left == right);
         }
operator Matrix3x2Serializable()
static Juniper.Mathematics.Matrix3x2Serializable.operator Matrix3x2Serializable (System.Numerics.Matrix3x2 v) inline explicit static
Definition at line 84 of file Matrix3x2Serializable.cs.
         {
             return System.Numerics.MathExt.ToJuniperMatrix3x2Serializable(v);
         }
References System.Numerics.MathExt.ToJuniperMatrix3x2Serializable().
operator System.Numerics.Matrix3x2()
static implicit Juniper.Mathematics.Matrix3x2Serializable.operator System.Numerics.Matrix3x2 (Matrix3x2Serializable v) inline static
Definition at line 79 of file Matrix3x2Serializable.cs.
         {
             return v.ToSystemMatrix3x2();
         }
References Juniper.Mathematics.Matrix3x2Serializable.ToSystemMatrix3x2().
operator==()
static bool Juniper.Mathematics.Matrix3x2Serializable.operator== (Matrix3x2Serializable left, Matrix3x2Serializable right) inline static
Definition at line 61 of file Matrix3x2Serializable.cs.
         {
             return left.Equals(right);
         }
ToSystemMatrix3x2()
System.Numerics.Matrix3x2 Juniper.Mathematics.Matrix3x2Serializable.ToSystemMatrix3x2 () inline
Definition at line 71 of file Matrix3x2Serializable.cs.
         {
             return new System.Numerics.Matrix3x2(
                 Values[0], Values[1],
                 Values[2], Values[3],
                 Values[4], Values[5]);
         }
References Juniper.Mathematics.Matrix3x2Serializable.Values.
Referenced by Juniper.Mathematics.Matrix3x2Serializable.operator System.Numerics.Matrix3x2().
Member Data Documentation
VALUES_FIELD
readonly string Juniper.Mathematics.Matrix3x2Serializable.VALUES_FIELD = nameof(Values).ToLowerInvariant() static private
Definition at line 11 of file Matrix3x2Serializable.cs.
Referenced by Juniper.Mathematics.Matrix3x2Serializable.GetObjectData(), and Juniper.Mathematics.Matrix3x2Serializable.Matrix3x2Serializable().
Property Documentation
Values
float [] Juniper.Mathematics.Matrix3x2Serializable.Values get
Definition at line 13 of file Matrix3x2Serializable.cs.
 { get; }
Referenced by Juniper.Mathematics.Matrix3x2Serializable.Equals(), Juniper.Mathematics.Matrix3x2Serializable.GetHashCode(), Juniper.Mathematics.Matrix3x2Serializable.GetObjectData(), Juniper.Mathematics.Matrix3x2Serializable.Matrix3x2Serializable(), and Juniper.Mathematics.Matrix3x2Serializable.ToSystemMatrix3x2().
The documentation for this struct was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Mathematics/Matrix3x2Serializable.cs