Juniper: Juniper.Widgets.ListView Class Reference
Juniper.Widgets.ListView Class Reference
Public Types
enum SelectionMode { SelectionMode.None, SelectionMode.Single, SelectionMode.SingleToggle, SelectionMode.Multiple }
Public Member Functions
void Awake ()
void Clear ()
ListViewItem GetItem (string key)
bool ContainsItem (string key)
void AddItems< T > (IEnumerable< T > items, Func< T, string > getKey, Func< T, string > getText)
ListViewItem AddItem (string text, object dataItem, string key)
void ClearSelection ()
void SetSelection (IEnumerable< string > keys)
void SetSelection (string key)
void RemoveItem (string key)
Public Attributes
SelectionMode selectionMode = SelectionMode.Single
Font font
int fontSize = 24
Color normalBackgroundColor = Color.grey
Color highlightBackgroundColor = Color.Lerp(Color.white, Color.grey, 0.5f)
Color normalColor = Color.white
Color disabledColor = Color.grey
Color highlightColor = Color.black
UnityEvent onSelectionChanged
Properties
List< ListViewItem > Items = new List<ListViewItem>() [get]
List< ListViewItem > Selection = new List<ListViewItem>() [get]
ListViewItem FirstSelectedItem [get]
ScrollRect Container [get]
Private Member Functions
void ChangeSelection (ListViewItem selected)
void SetSelection (List< ListViewItem > newSelection)
Private Attributes
int count
Static Private Attributes
static readonly List< ListViewItem > EMPTY_SELECTION = new List<ListViewItem>()
Detailed Description
Definition at line 11 of file ListView.cs.
Member Enumeration Documentation
SelectionMode
enum Juniper.Widgets.ListView.SelectionMode strong
Enumerator
None
Single
SingleToggle
Multiple
Definition at line 23 of file ListView.cs.
         {
             None,
             Single,
             SingleToggle,
             Multiple
         }
Member Function Documentation
AddItem()
ListViewItem Juniper.Widgets.ListView.AddItem (string text, object dataItem, string key) inline
Definition at line 76 of file ListView.cs.
         {
             var item = new GameObject().AddComponent<ListViewItem>();
             item.transform.SetParent(Container.content, false);
             Items.Add(item);
             item.Key = key;
             item.Text = text;
             item.DataItem = dataItem;
             item.normalColor = normalColor;
             item.disabledColor = disabledColor;
             item.BackgroundColor = normalBackgroundColor;
             item.Font = font;
             item.FontSize = fontSize;
             item.RemoveAllListeners();
             item.AddListener(() =>
                 ChangeSelection(item));
             item.transform.SetSiblingIndex(count++);
             return item;
         }
References Juniper.Widgets.ListView.ChangeSelection(), Juniper.Widgets.ListView.Container, Juniper.Widgets.ListView.count, Juniper.Widgets.ListView.disabledColor, Juniper.Widgets.ListView.font, Juniper.Widgets.ListView.fontSize, Juniper.Widgets.ListView.Items, Juniper.Widgets.ListView.normalBackgroundColor, and Juniper.Widgets.ListView.normalColor.
Referenced by Juniper.Widgets.FileSelector.AddEntry(), and Juniper.Widgets.ListView.AddItems< T >().
AddItems< T >()
void Juniper.Widgets.ListView.AddItems< T > (IEnumerable< T > items, Func< T, string > getKey, Func< T, string > getText) inline
Definition at line 68 of file ListView.cs.
         {
             foreach (var item in items)
             {
                 AddItem(getText(item), item, getKey(item));
             }
         }
References Juniper.Widgets.ListView.AddItem().
Awake()
void Juniper.Widgets.ListView.Awake () inline
Definition at line 42 of file ListView.cs.
         {
             GetComponentsInChildren(true, Items);
         }
References Juniper.Widgets.ListView.Items.
ChangeSelection()
void Juniper.Widgets.ListView.ChangeSelection (ListViewItem selected) inline private
Definition at line 138 of file ListView.cs.
         {
             var wasInSelection = Selection.Contains(selected);
             var newSelection = Selection.ToList();
             if (selectionMode != SelectionMode.Multiple)
             {
                 newSelection.Clear();
             }
             else if (wasInSelection)
             {
                 newSelection.Remove(selected);
             }
             if (selectionMode == SelectionMode.Single
                 || (!wasInSelection && selectionMode != SelectionMode.None))
             {
                 newSelection.Add(selected);
             }
             SetSelection(newSelection);
         }
References Juniper.Widgets.ListView.Selection, Juniper.Widgets.ListView.selectionMode, and Juniper.Widgets.ListView.SetSelection().
Referenced by Juniper.Widgets.ListView.AddItem().
Clear()
void Juniper.Widgets.ListView.Clear () inline
Definition at line 47 of file ListView.cs.
         {
             foreach (var item in Items)
             {
                 item.gameObject.Destroy();
             }
             Items.Clear();
             Selection.Clear();
             count = 0;
         }
References Juniper.Widgets.ListView.count, Juniper.Widgets.ListView.Items, and Juniper.Widgets.ListView.Selection.
Referenced by Juniper.Widgets.FileSelector.ReadDirectory().
ClearSelection()
void Juniper.Widgets.ListView.ClearSelection () inline
Definition at line 100 of file ListView.cs.
         {
             SetSelection(EMPTY_SELECTION);
         }
References Juniper.Widgets.ListView.EMPTY_SELECTION, and Juniper.Widgets.ListView.SetSelection().
ContainsItem()
bool Juniper.Widgets.ListView.ContainsItem (string key) inline
Definition at line 63 of file ListView.cs.
         {
             return GetItem(key) != null;
         }
References Juniper.Widgets.ListView.GetItem().
GetItem()
ListViewItem Juniper.Widgets.ListView.GetItem (string key) inline
Definition at line 58 of file ListView.cs.
         {
             return Items.FirstOrDefault(i => i.Key == key);
         }
References Juniper.Widgets.ListView.Items.
Referenced by Juniper.Widgets.ListView.ContainsItem(), Juniper.Widgets.ListView.RemoveItem(), and Juniper.Widgets.ListView.SetSelection().
RemoveItem()
void Juniper.Widgets.ListView.RemoveItem (string key) inline
Definition at line 115 of file ListView.cs.
         {
             var item = GetItem(key);
             if (item != null)
             {
                 Items.Remove(item);
                 item.gameObject.Destroy();
                 --count;
             }
         }
References Juniper.Widgets.ListView.count, Juniper.Widgets.ListView.GetItem(), and Juniper.Widgets.ListView.Items.
SetSelection() [1/3]
void Juniper.Widgets.ListView.SetSelection (IEnumerable< string > keys) inline
Definition at line 105 of file ListView.cs.
         {
             SetSelection(keys.Select(GetItem).ToList());
         }
References Juniper.Widgets.ListView.GetItem().
Referenced by Juniper.Widgets.ListView.ChangeSelection(), Juniper.Widgets.ListView.ClearSelection(), and Juniper.Widgets.ListView.SetSelection().
SetSelection() [2/3]
void Juniper.Widgets.ListView.SetSelection (string key) inline
Definition at line 110 of file ListView.cs.
         {
             SetSelection(new[] { GetItem(key) }.ToList());
         }
References Juniper.Widgets.ListView.GetItem(), and Juniper.Widgets.ListView.SetSelection().
SetSelection() [3/3]
void Juniper.Widgets.ListView.SetSelection (List< ListViewItem > newSelection) inline private
Definition at line 161 of file ListView.cs.
         {
             var changed = newSelection.Count != Selection.Count
                 || !newSelection.All(Selection.Contains);
             if (changed)
             {
                 Selection.Clear();
                 Selection.AddRange(newSelection);
                 foreach (var item in Items)
                 {
                     var highlight = Selection.Contains(item);
                     item.BackgroundColor = highlight ? highlightBackgroundColor : normalBackgroundColor;
                     item.normalColor = highlight ? highlightColor : normalColor;
                 }
                 onSelectionChanged?.Invoke();
             }
         }
References Juniper.Widgets.ListView.highlightBackgroundColor, Juniper.Widgets.ListView.highlightColor, Juniper.Widgets.ListView.Items, Juniper.Widgets.ListView.normalBackgroundColor, Juniper.Widgets.ListView.normalColor, Juniper.Widgets.ListView.onSelectionChanged, and Juniper.Widgets.ListView.Selection.
Member Data Documentation
count
int Juniper.Widgets.ListView.count private
Definition at line 128 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.AddItem(), Juniper.Widgets.ListView.Clear(), and Juniper.Widgets.ListView.RemoveItem().
disabledColor
Color Juniper.Widgets.ListView.disabledColor = Color.grey
Definition at line 19 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.AddItem().
EMPTY_SELECTION
readonly List<ListViewItem> Juniper.Widgets.ListView.EMPTY_SELECTION = new List<ListViewItem>() static private
Definition at line 127 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.ClearSelection().
font
Font Juniper.Widgets.ListView.font
Definition at line 14 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.AddItem().
fontSize
int Juniper.Widgets.ListView.fontSize = 24
Definition at line 15 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.AddItem().
highlightBackgroundColor
Color Juniper.Widgets.ListView.highlightBackgroundColor = Color.Lerp(Color.white, Color.grey, 0.5f)
Definition at line 17 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.SetSelection().
highlightColor
Color Juniper.Widgets.ListView.highlightColor = Color.black
Definition at line 20 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.SetSelection().
normalBackgroundColor
Color Juniper.Widgets.ListView.normalBackgroundColor = Color.grey
Definition at line 16 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.AddItem(), and Juniper.Widgets.ListView.SetSelection().
normalColor
Color Juniper.Widgets.ListView.normalColor = Color.white
Definition at line 18 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.AddItem(), and Juniper.Widgets.ListView.SetSelection().
onSelectionChanged
UnityEvent Juniper.Widgets.ListView.onSelectionChanged
Definition at line 21 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.SetSelection().
selectionMode
SelectionMode Juniper.Widgets.ListView.selectionMode = SelectionMode.Single
Definition at line 13 of file ListView.cs.
Referenced by Juniper.Widgets.ListView.ChangeSelection().
Property Documentation
Container
ScrollRect Juniper.Widgets.ListView.Container get private
Definition at line 131 of file ListView.cs.
         {
             get
             {
                 return GetComponent<ScrollRect>();
             }
         }
Referenced by Juniper.Widgets.ListView.AddItem().
FirstSelectedItem
ListViewItem Juniper.Widgets.ListView.FirstSelectedItem get
Definition at line 35 of file ListView.cs.
         {
             get
             {
                 return Selection.FirstOrDefault();
             }
         }
Items
List<ListViewItem> Juniper.Widgets.ListView.Items = new List<ListViewItem>() get
Definition at line 31 of file ListView.cs.
 { get; } = new List<ListViewItem>();
Referenced by Juniper.Widgets.ListView.AddItem(), Juniper.Widgets.ListView.Awake(), Juniper.Widgets.ListView.Clear(), Juniper.Widgets.ListView.GetItem(), Juniper.Widgets.ListView.RemoveItem(), and Juniper.Widgets.ListView.SetSelection().
Selection
List<ListViewItem> Juniper.Widgets.ListView.Selection = new List<ListViewItem>() get
Definition at line 32 of file ListView.cs.
 { get; } = new List<ListViewItem>();
Referenced by Juniper.Widgets.ListView.ChangeSelection(), Juniper.Widgets.ListView.Clear(), and Juniper.Widgets.ListView.SetSelection().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/ListView.cs