Juniper: Juniper.Unity.ConfigurationManagement.PlatformConfiguration Class Reference
Juniper.Unity.ConfigurationManagement.PlatformConfiguration Class Reference
Public Member Functions
PlatformConfiguration ()
bool SwitchTarget ()
void InstallUnityPackages (IProgressReceiver prog=null)
void InstallRawPackages (IProgressReceiver prog=null)
void Activate (IProgressReceiver prog)
void UninstallRawPackages (IProgressReceiver prog=null)
void UninstallUnityPackages (IProgressReceiver prog=null)
Public Attributes
string Name
string CompilerDefine
string buildTarget
string [] vrSystems
string [] packages
Properties
BuildTarget BuildTarget [get]
BuildTargetGroup TargetGroup [get]
bool IsSupported [get]
IEnumerable< UnityXRPlatforms > XRPlatforms [get]
UnityPackage [] UninstallableUnityPackages [get, set]
UnityPackage [] IncludedUnityPackages [get, set]
UnityPackage [] ExcludedUnityPackages [get, set]
RawPackage [] UninstallableRawPackages [get, set]
RawPackage [] RawPackages [get, set]
List< string > CompilerDefines [get]
Private Member Functions
internal void Deactivate (PlatformConfiguration nextConfiguration, string thirdPartyDefines)
Detailed Description
Definition at line 17 of file PlatformConfiguration.cs.
Constructor & Destructor Documentation
PlatformConfiguration()
Juniper.Unity.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration () inline
Definition at line 25 of file PlatformConfiguration.cs.
         {
             Name = null;
             CompilerDefine = null;
             buildTarget = null;
             vrSystems = null;
             packages = null;
         }
References Juniper.Unity.ConfigurationManagement.PlatformConfiguration.buildTarget, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.CompilerDefine, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Name, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.packages, and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.vrSystems.
Member Function Documentation
Activate()
void Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate (IProgressReceiver prog) inline
Definition at line 158 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(IncludedUnityPackages, progs[0], (pkg, p) => pkg.Activate(TargetGroup, p));
             Platforms.ForEachPackage(RawPackages, progs[1], (pkg, p) => pkg.Activate(TargetGroup, p));
             var supportedVRSDKs = PlayerSettings.GetAvailableVirtualRealitySDKs(TargetGroup);
             var vrSDKs = XRPlatforms
                 .Distinct()
                 .Select(x => x.ToString())
                 .Where(supportedVRSDKs.Contains)
                 .ToArray();
             var enableVR = vrSDKs.Any(sdk => sdk != "None");
             if (enableVR != PlayerSettings.GetVirtualRealitySupported(TargetGroup))
             {
                 PlayerSettings.SetVirtualRealitySupported(TargetGroup, enableVR);
                 if (enableVR && !vrSDKs.Matches(PlayerSettings.GetVirtualRealitySDKs(TargetGroup)))
                 {
                     PlayerSettings.SetVirtualRealitySDKs(TargetGroup, vrSDKs);
                 }
             }
             if (BuildTarget == BuildTarget.WSAPlayer)
             {
                 EditorUserBuildSettings.wsaBuildAndRunDeployTarget = WSABuildAndRunDeployTarget.LocalMachine;
                 EditorUserBuildSettings.wsaUWPBuildType = WSAUWPBuildType.D3D;
                 PlayerSettings.WSA.inputSource = PlayerSettings.WSAInputSource.IndependentInputSource;
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.InternetClient, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.WebCam, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Bluetooth, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Microphone, ComponentExt.FindAny<KeywordRecognizer>() != null);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Location, ComponentExt.FindAny<GPSLocation>() != null);
             }
         }
References Juniper.Unity.ConfigurationManagement.AbstractPackage.Activate(), Juniper.Unity.ConfigurationManagement.RawPackage.Activate(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.BuildTarget, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.RawPackages, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.TargetGroup, and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.XRPlatforms.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Deactivate()
internal void Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Deactivate (PlatformConfiguration nextConfiguration, string thirdPartyDefines) inline private
Definition at line 239 of file PlatformConfiguration.cs.
         {
             AudioSettings.SetSpatializerPluginName(null);
             AudioSettingsExt.SetAmbisonicDecoderPluginName(null);
             PlayerSettings.virtualRealitySupported = false;
             PlayerSettings.Android.androidTVCompatibility = false;
 #if UNITY_2018_2_OR_NEWER
             PlayerSettings.Android.ARCoreEnabled = false;
 #endif
             PlayerSettingsExt.iOS.RequiresARKitSupport = false;
             PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
             if (nextConfiguration.TargetGroup != TargetGroup)
             {
                 PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
                 PlayerSettings.SetScriptingDefineSymbolsForGroup(TargetGroup, thirdPartyDefines);
             }
         }
References UnityEditor.PlayerSettingsExt.iOS.RequiresARKitSupport, UnityEditor.AudioSettingsExt.SetAmbisonicDecoderPluginName(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.TargetGroup.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform().
InstallRawPackages()
void Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallRawPackages (IProgressReceiver prog = null) inline
Definition at line 153 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(RawPackages, prog, (pkg, p) => pkg.Install(p));
         }
References Juniper.Unity.ConfigurationManagement.RawPackage.Install(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.RawPackages.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
InstallUnityPackages()
void Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages (IProgressReceiver prog = null) inline
Definition at line 140 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(ExcludedUnityPackages, progs[0], (pkg, p) =>
 #if UNITY_2018_2_OR_NEWER
                 pkg.Uninstall(p)
 #else
                 pkg.Install(p)
 #endif
             );
             Platforms.ForEachPackage(IncludedUnityPackages, progs[1], (pkg, p) => pkg.Install(p));
         }
References Juniper.Unity.ConfigurationManagement.PlatformConfiguration.ExcludedUnityPackages, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages, Juniper.Unity.ConfigurationManagement.UnityPackage.Install(), and Juniper.Unity.ConfigurationManagement.UnityPackage.Uninstall().
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
SwitchTarget()
bool Juniper.Unity.ConfigurationManagement.PlatformConfiguration.SwitchTarget () inline
Definition at line 126 of file PlatformConfiguration.cs.
         {
             if (BuildTarget != EditorUserBuildSettings.activeBuildTarget)
             {
                 Debug.Log($"Switching build target from {EditorUserBuildSettings.activeBuildTarget} to {BuildTarget}.");
                 EditorUserBuildSettings.SwitchActiveBuildTargetAsync(TargetGroup, BuildTarget);
                 return true;
             }
             else
             {
                 return false;
             }
         }
References Juniper.Unity.ConfigurationManagement.PlatformConfiguration.BuildTarget, and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.TargetGroup.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
UninstallRawPackages()
void Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages (IProgressReceiver prog = null) inline
Definition at line 194 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(UninstallableRawPackages, prog, (pkg, p) => pkg.Uninstall(p));
         }
References Juniper.Unity.ConfigurationManagement.RawPackage.Uninstall(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallableRawPackages.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
UninstallUnityPackages()
void Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages (IProgressReceiver prog = null) inline
Definition at line 199 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(UninstallableUnityPackages, prog, (pkg, p) => pkg.Uninstall(p));
         }
References Juniper.Unity.ConfigurationManagement.UnityPackage.Uninstall(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallableUnityPackages.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Member Data Documentation
buildTarget
string Juniper.Unity.ConfigurationManagement.PlatformConfiguration.buildTarget
Definition at line 21 of file PlatformConfiguration.cs.
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
CompilerDefine
string Juniper.Unity.ConfigurationManagement.PlatformConfiguration.CompilerDefine
Definition at line 20 of file PlatformConfiguration.cs.
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
Name
string Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Name
Definition at line 19 of file PlatformConfiguration.cs.
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
packages
string [] Juniper.Unity.ConfigurationManagement.PlatformConfiguration.packages
Definition at line 23 of file PlatformConfiguration.cs.
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
vrSystems
string [] Juniper.Unity.ConfigurationManagement.PlatformConfiguration.vrSystems
Definition at line 22 of file PlatformConfiguration.cs.
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
Property Documentation
BuildTarget
BuildTarget Juniper.Unity.ConfigurationManagement.PlatformConfiguration.BuildTarget get
Definition at line 36 of file PlatformConfiguration.cs.
         {
             get
             {
                 var localBuildTarget = buildTarget;
                 if (localBuildTarget == "Standalone")
                 {
 #if UNITY_EDITOR_WIN
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows);
                     }
 #elif UNITY_EDITOR_OSX
                     localBuildTarget = nameof(BuildTarget.StandaloneOSX);
 #else
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux);
                     }
 #endif
                 }
                 return (BuildTarget)Enum.Parse(typeof(BuildTarget), localBuildTarget);
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.SwitchTarget().
CompilerDefines
List<string> Juniper.Unity.ConfigurationManagement.PlatformConfiguration.CompilerDefines get
Definition at line 205 of file PlatformConfiguration.cs.
         {
             get
             {
                 var defines = Platforms.GetCompilerDefines(IncludedUnityPackages, RawPackages).ToList();
                 if (!string.IsNullOrEmpty(CompilerDefine))
                 {
                     defines.Add(CompilerDefine);
                 }
                 if (TargetGroup == BuildTargetGroup.Android)
                 {
                     for (var i = (int)PlayerSettings.Android.minSdkVersion; i > 0; --i)
                     {
                         if (Enum.IsDefined(typeof(AndroidSdkVersions), i))
{
                             defines.Add("ANDROID_API_" + i);
                             defines.Add("ANDROID_API_" + i + "_OR_GREATER");
                         }
                     }
                 }
                 else if (TargetGroup == BuildTargetGroup.iOS)
                 {
                     for (var i = PlayerSettingsExt.iOS.TargetOSVersion.Major; i > 0; --i)
                     {
                         defines.Add("IOS_VERSION_" + i);
                         defines.Add("IOS_VERSION_" + i + "_OR_GREATER");
                     }
                 }
                 return defines;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal().
ExcludedUnityPackages
UnityPackage [] Juniper.Unity.ConfigurationManagement.PlatformConfiguration.ExcludedUnityPackages get set
Definition at line 110 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages().
IncludedUnityPackages
UnityPackage [] Juniper.Unity.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages get set
Definition at line 104 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages().
IsSupported
bool Juniper.Unity.ConfigurationManagement.PlatformConfiguration.IsSupported get
Definition at line 79 of file PlatformConfiguration.cs.
         {
             get
             {
                 return BuildPipeline.IsBuildTargetSupported(TargetGroup, BuildTarget);
             }
         }
RawPackages
RawPackage [] Juniper.Unity.ConfigurationManagement.PlatformConfiguration.RawPackages get set
Definition at line 122 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallRawPackages().
TargetGroup
BuildTargetGroup Juniper.Unity.ConfigurationManagement.PlatformConfiguration.TargetGroup get
Definition at line 70 of file PlatformConfiguration.cs.
         {
             get
             {
                 return BuildPipeline.GetBuildTargetGroup(BuildTarget);
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Deactivate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal(), and Juniper.Unity.ConfigurationManagement.PlatformConfiguration.SwitchTarget().
UninstallableRawPackages
RawPackage [] Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallableRawPackages get set
Definition at line 116 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages().
UninstallableUnityPackages
UnityPackage [] Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallableUnityPackages get set
Definition at line 98 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages().
XRPlatforms
IEnumerable<UnityXRPlatforms> Juniper.Unity.ConfigurationManagement.PlatformConfiguration.XRPlatforms get
Definition at line 88 of file PlatformConfiguration.cs.
         {
             get
             {
                 return from sys in vrSystems
                        select (UnityXRPlatforms)Enum.Parse(typeof(UnityXRPlatforms), sys);
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/ConfigurationManagement/PlatformConfiguration.cs