Juniper: Juniper.Units.Converter Class Reference
Juniper.Units.Converter Class Reference
TODO: validate this against https://www.nist.gov/sites/default/files/documents/pml/wmd/metric/SP1038.pdf
Static Public Member Functions
static Category GetPrimaryCategory (UnitOfMeasure unit)
Retrieve the first category listing in TypeGroups for a given UnitOfMeasure.
static ? UnitOfMeasure GetSystemUnit (SystemOfMeasure system, Category category)
Retrieves the type of unit that is used in a given Category slot for a SystemOfMeasure.
static float Convert (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit)
Convert a value from one unit of measure to another.
static float Convert (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem)
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
static float Convert (this float value, UnitOfMeasure fromUnit)
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
static ? float Convert (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit)
Convert a value from one unit of measure to another.
static ? float Convert (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem)
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
static ? float Convert (this float? value, UnitOfMeasure fromUnit)
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
static string Abbreviate (this UnitOfMeasure unit)
Retrieve the abbreviation for the given unit of measure.
static string Label (this float value, UnitOfMeasure unit, int sigfigs)
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float value, UnitOfMeasure unit)
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int sigfigs)
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int sigfigs)
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem)
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit)
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int sigfigs)
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem)
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int sigfigs)
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit)
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure unit, int sigfigs)
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure unit)
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Public Attributes
const int DEFAULT_SIGNIFICANT_FIGURES = 3
Static Public Attributes
static readonly Dictionary< UnitOfMeasure, string > Abbreviations
All the short-form symbols of each UnitOfMeasure.
Static Private Member Functions
static UnitOfMeasure FindConversion (UnitOfMeasure fromUnit, SystemOfMeasure toSystem)
For a given UnitOfMeasure, find any Category in any SystemOfMeasure which has a matching Category in the given SystemOfMeasure, then retrieve the UnitOfMeasure that fulfills that category in that SystemOfMeasure.
Static Private Attributes
static readonly Dictionary< UnitOfMeasure, Category[]> TypeGroups
The TypeGroups put the different UnitOfMeasures into groupings by Category, to make conversions within categories possible. Every UnitOfMeasure should be included in a Category.
static readonly Dictionary< SystemOfMeasure, Dictionary< Category, UnitOfMeasure > > SystemUnits
SystemUnits are groupings of UnitOfMeasure s into SystemOfMeasure s by Category s. For example, this makes it possible to ask which units are used for short distance measurements in the Metric system. Not every UnitOfMeasure need be included in a SystemOfMeasure.
static readonly Dictionary< UnitOfMeasure, Dictionary< UnitOfMeasure, Func< float, float > > > Conversions
A look-up to quickly find the conversion function for each unit of measure pairing without having to use reflection every time.
Detailed Description
TODO: validate this against https://www.nist.gov/sites/default/files/documents/pml/wmd/metric/SP1038.pdf
Definition at line 10 of file Converter.cs.
Member Function Documentation
Abbreviate()
static string Juniper.Units.Converter.Abbreviate (this UnitOfMeasure unit) inline static
Retrieve the abbreviation for the given unit of measure.
Parameters
unit
Returns
Definition at line 1348 of file Converter.cs.
         {
             return Abbreviations.ContainsKey(unit)
                 ? Abbreviations[unit]
                 : string.Empty;
         }
References Juniper.Units.Converter.Abbreviations.
Convert() [1/6]
static float Juniper.Units.Converter.Convert (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit) inline static
Convert a value from one unit of measure to another.
Parameters
value
fromUnit
toUnit
Returns
Definition at line 1264 of file Converter.cs.
         {
             if (fromUnit == toUnit)
             {
                 return value;
             }
             else if (Conversions.TryGetValue(fromUnit, out var forFromUnit)
                 && Conversions[fromUnit].TryGetValue(toUnit, out var conversion))
             {
                 return conversion(value);
             }
             else
             {
                 throw new InvalidCastException($"Cannot convert {value.ToString(CultureInfo.CurrentCulture)} in {fromUnit.ToString()} to {toUnit.ToString()}.");
             }
         }
References Juniper.Units.Converter.Conversions.
Convert() [2/6]
static float Juniper.Units.Converter.Convert (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem) inline static
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
Parameters
value
fromUnit
toSystem
Returns
Definition at line 1289 of file Converter.cs.
         {
             return value.Convert(fromUnit, FindConversion(fromUnit, toSystem));
         }
References Juniper.Units.Converter.FindConversion().
Convert() [3/6]
static float Juniper.Units.Converter.Convert (this float value, UnitOfMeasure fromUnit) inline static
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
Parameters
value
fromUnit
Returns
Definition at line 1301 of file Converter.cs.
         {
             return value.Convert(fromUnit, SystemOfMeasure.USCustomary);
         }
Convert() [4/6]
static ? float Juniper.Units.Converter.Convert (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit) inline static
Convert a value from one unit of measure to another.
Parameters
value
fromUnit
toUnit
Returns
Definition at line 1313 of file Converter.cs.
         {
             return value?.Convert(fromUnit, toUnit);
         }
Convert() [5/6]
static ? float Juniper.Units.Converter.Convert (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem) inline static
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
Parameters
value
fromUnit
toSystem
Returns
Definition at line 1326 of file Converter.cs.
         {
             return value?.Convert(fromUnit, toSystem);
         }
Convert() [6/6]
static ? float Juniper.Units.Converter.Convert (this float? value, UnitOfMeasure fromUnit) inline static
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
Parameters
value
fromUnit
Returns
Definition at line 1338 of file Converter.cs.
         {
             return value?.Convert(fromUnit);
         }
FindConversion()
static UnitOfMeasure Juniper.Units.Converter.FindConversion (UnitOfMeasure fromUnit, SystemOfMeasure toSystem) inline static private
For a given UnitOfMeasure, find any Category in any SystemOfMeasure which has a matching Category in the given SystemOfMeasure, then retrieve the UnitOfMeasure that fulfills that category in that SystemOfMeasure.
Parameters
fromUnit
toSystem
Returns
Definition at line 1226 of file Converter.cs.
         {
             if (!Conversions.ContainsKey(fromUnit))
             {
                 throw new ArgumentException($"Unit type {fromUnit.ToString()} not recognized for conversion");
             }
             else if (!TypeGroups.ContainsKey(fromUnit))
             {
                 throw new ArgumentException($"Unit type {fromUnit.ToString()} has not had type groupings defined");
             }
             else if (!SystemUnits.ContainsKey(toSystem))
             {
                 throw new ArgumentException($"System type {toSystem.ToString()} not specified");
             }
             else
             {
                 foreach (var g in TypeGroups[fromUnit])
                 {
                     foreach (var s in SystemUnits[toSystem])
                     {
                         if (g == s.Key)
{
                             return s.Value;
                         }
                     }
                 }
                 throw new ArgumentException($"Unit type {fromUnit.ToString()} does not have a matching conversion in system {toSystem.ToString()}");
             }
         }
References Juniper.Units.Converter.Conversions, Juniper.Units.Converter.SystemUnits, and Juniper.Units.Converter.TypeGroups.
Referenced by Juniper.Units.Converter.Convert(), and Juniper.Units.Converter.Label().
GetPrimaryCategory()
static Category Juniper.Units.Converter.GetPrimaryCategory (UnitOfMeasure unit) inline static
Retrieve the first category listing in TypeGroups for a given UnitOfMeasure.
Parameters
unit The unit to look up
Returns
The gross category of the unit
Definition at line 129 of file Converter.cs.
         {
             return TypeGroups[unit][0];
         }
References Juniper.Units.Converter.TypeGroups.
GetSystemUnit()
static ? UnitOfMeasure Juniper.Units.Converter.GetSystemUnit (SystemOfMeasure system, Category category) inline static
Retrieves the type of unit that is used in a given Category slot for a SystemOfMeasure.
Parameters
system The system to query
category The category to look up
Returns
null, if the category is not available in the system, or a UnitOfMeasure otherwise.
Definition at line 209 of file Converter.cs.
         {
             if (SystemUnits.TryGetValue(system, out var sys)
                 && sys.TryGetValue(category, out var unit))
             {
                 return unit;
             }
             else
             {
                 return null;
             }
         }
References Juniper.Units.Converter.SystemUnits.
Label() [1/12]
static string Juniper.Units.Converter.Label (this float value, UnitOfMeasure unit, int sigfigs) inline static
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
unit
sigfigs
Returns
Definition at line 1363 of file Converter.cs.
         {
             return (float.IsInfinity(value) || float.IsNaN(value))
                 ? value.ToString(CultureInfo.CurrentCulture)
                 : value.SigFig(sigfigs) + unit.Abbreviate();
         }
Label() [2/12]
static string Juniper.Units.Converter.Label (this float value, UnitOfMeasure unit) inline static
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
unit
Returns
Definition at line 1377 of file Converter.cs.
         {
             return (float.IsInfinity(value) || float.IsNaN(value))
                 ? value.ToString(CultureInfo.CurrentCulture)
                 : value.SigFig(DEFAULT_SIGNIFICANT_FIGURES) + unit.Abbreviate();
         }
References Juniper.Units.Converter.DEFAULT_SIGNIFICANT_FIGURES.
Label() [3/12]
static string Juniper.Units.Converter.Label (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int sigfigs) inline static
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toUnit
sigfigs
Returns
Definition at line 1393 of file Converter.cs.
         {
             return value
                 .Convert(fromUnit, toUnit)
                 .Label(toUnit, sigfigs);
         }
Label() [4/12]
static string Juniper.Units.Converter.Label (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int sigfigs) inline static
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toSystem
sigfigs
Returns
Definition at line 1409 of file Converter.cs.
         {
             return value.Label(fromUnit, FindConversion(fromUnit, toSystem), sigfigs);
         }
References Juniper.Units.Converter.FindConversion().
Label() [5/12]
static string Juniper.Units.Converter.Label (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem) inline static
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toSystem
Returns
Definition at line 1422 of file Converter.cs.
         {
             return value.Label(fromUnit, FindConversion(fromUnit, toSystem));
         }
References Juniper.Units.Converter.FindConversion().
Label() [6/12]
static string Juniper.Units.Converter.Label (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit) inline static
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toUnit
Returns
Definition at line 1435 of file Converter.cs.
         {
             return value
                 .Convert(fromUnit, toUnit)
                 .Label(toUnit);
         }
Label() [7/12]
static string Juniper.Units.Converter.Label (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int sigfigs) inline static
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toSystem
sigfigs
Returns
Definition at line 1451 of file Converter.cs.
         {
             return value?.Label(fromUnit, toSystem, sigfigs) ?? "N/A";
         }
Label() [8/12]
static string Juniper.Units.Converter.Label (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem) inline static
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toSystem
Returns
Definition at line 1464 of file Converter.cs.
         {
             return value?.Label(fromUnit, toSystem) ?? "N/A";
         }
Label() [9/12]
static string Juniper.Units.Converter.Label (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int sigfigs) inline static
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toUnit
sigfigs
Returns
Definition at line 1478 of file Converter.cs.
         {
             return value?.Label(fromUnit, toUnit, sigfigs) ?? "N/A";
         }
Label() [10/12]
static string Juniper.Units.Converter.Label (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit) inline static
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toUnit
Returns
Definition at line 1491 of file Converter.cs.
         {
             return value?.Label(fromUnit, toUnit) ?? "N/A";
         }
Label() [11/12]
static string Juniper.Units.Converter.Label (this float? value, UnitOfMeasure unit, int sigfigs) inline static
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
unit
sigfigs
Returns
Definition at line 1504 of file Converter.cs.
         {
             return value?.Label(unit, sigfigs) ?? "N/A";
         }
Label() [12/12]
static string Juniper.Units.Converter.Label (this float? value, UnitOfMeasure unit) inline static
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
unit
Returns
Definition at line 1516 of file Converter.cs.
         {
             return value?.Label(unit) ?? "N/A";
         }
Member Data Documentation
Abbreviations
readonly Dictionary<UnitOfMeasure, string> Juniper.Units.Converter.Abbreviations static
All the short-form symbols of each UnitOfMeasure.
Definition at line 225 of file Converter.cs.
Referenced by Juniper.Units.Converter.Abbreviate().
Conversions
readonly Dictionary<UnitOfMeasure, Dictionary<UnitOfMeasure, Func<float, float> > > Juniper.Units.Converter.Conversions static private
A look-up to quickly find the conversion function for each unit of measure pairing without having to use reflection every time.
Definition at line 320 of file Converter.cs.
Referenced by Juniper.Units.Converter.Convert(), and Juniper.Units.Converter.FindConversion().
DEFAULT_SIGNIFICANT_FIGURES
const int Juniper.Units.Converter.DEFAULT_SIGNIFICANT_FIGURES = 3
Definition at line 12 of file Converter.cs.
Referenced by Juniper.Units.Converter.Label().
SystemUnits
readonly Dictionary<SystemOfMeasure, Dictionary<Category, UnitOfMeasure> > Juniper.Units.Converter.SystemUnits static private
SystemUnits are groupings of UnitOfMeasure s into SystemOfMeasure s by Category s. For example, this makes it possible to ask which units are used for short distance measurements in the Metric system. Not every UnitOfMeasure need be included in a SystemOfMeasure.
Definition at line 140 of file Converter.cs.
Referenced by Juniper.Units.Converter.FindConversion(), and Juniper.Units.Converter.GetSystemUnit().
TypeGroups
readonly Dictionary<UnitOfMeasure, Category[]> Juniper.Units.Converter.TypeGroups static private
The TypeGroups put the different UnitOfMeasures into groupings by Category, to make conversions within categories possible. Every UnitOfMeasure should be included in a Category.
Definition at line 19 of file Converter.cs.
Referenced by Juniper.Units.Converter.FindConversion(), and Juniper.Units.Converter.GetPrimaryCategory().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Units/Converter.cs