Juniper: UnityEditor.TableView Class Reference
UnityEditor.TableView Class Reference
Classes
class ScrollViewState
Public Member Functions
TableView (string title, params(string Header, GUILayoutOption Width)[] headers)
TableView (params(string Header, GUILayoutOption Width)[] headers)
TableView? (string title, params(string Header, float? Width)[] headers)
TableView (params(string Header, float? Width)[] headers)
IDisposable Begin ()
Private Member Functions
readonly (string Header, GUILayoutOption[] Width)[] headers
void DrawHeaders ()
Private Attributes
readonly string title
Vector2 scrollPosition
Detailed Description
Definition at line 8 of file TableView.cs.
Constructor & Destructor Documentation
TableView() [1/3]
UnityEditor.TableView.TableView (string title, params(string Header, GUILayoutOption Width) [] headers) inline
Definition at line 14 of file TableView.cs.
         {
             this.title = title;
             this.headers = (from h in headers
                             select (h.Header, h.Width is null ? null : new GUILayoutOption[] { h.Width }))
                         .ToArray();
         }
References UnityEditor.TableView.title.
TableView() [2/3]
UnityEditor.TableView.TableView (params(string Header, GUILayoutOption Width) [] headers) inline
Definition at line 22 of file TableView.cs.
             : this(null, headers)
         { }
TableView() [3/3]
UnityEditor.TableView.TableView (params(string Header, float? Width) [] headers) inline
Definition at line 32 of file TableView.cs.
             : this(null, headers)
         { }
Member Function Documentation
Begin()
IDisposable UnityEditor.TableView.Begin () inline
Definition at line 36 of file TableView.cs.
         {
             if (title != null)
             {
                 using (new Header(title))
                 {
                     DrawHeaders();
                 }
             }
             else
             {
                 DrawHeaders();
             }
             return new ScrollViewState(ref scrollPosition);
         }
References UnityEditor.TableView.DrawHeaders(), UnityEditor.TableView.scrollPosition, and UnityEditor.TableView.title.
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawInstalledPackages(), Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages(), Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages(), Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI(), and Juniper.Unity.Editor.JuniperEditorWindow.OnGUI().
DrawHeaders()
void UnityEditor.TableView.DrawHeaders () inline private
Definition at line 53 of file TableView.cs.
         {
             using (new HGroup())
             {
                 foreach (var header in headers)
                 {
                     if (header.Width is null)
                     {
                         EditorGUILayout.LabelField(header.Header, EditorStyles.centeredGreyMiniLabel);
                     }
                     else
                     {
                         EditorGUILayout.LabelField(header.Header, EditorStyles.centeredGreyMiniLabel, header.Width);
                     }
                 }
             }
         }
Referenced by UnityEditor.TableView.Begin().
readonly()
UnityEditor.TableView.readonly (string Header, GUILayoutOption [] Width) private
TableView?()
UnityEditor.TableView.TableView? (string title, params(string Header, float? Width) [] headers) inline
Definition at line 26 of file TableView.cs.
             : this(title, (from h in headers
                            select (h.Header, h.Width is null ? null : GUILayout.Width(h.Width.Value)))
                         .ToArray())
         { }
Member Data Documentation
scrollPosition
Vector2 UnityEditor.TableView.scrollPosition private
Definition at line 12 of file TableView.cs.
Referenced by UnityEditor.TableView.Begin(), and UnityEditor.TableView.ScrollViewState.ScrollViewState().
title
readonly string UnityEditor.TableView.title private
Definition at line 11 of file TableView.cs.
Referenced by UnityEditor.TableView.Begin(), and UnityEditor.TableView.TableView().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.UnityEditor/TableView.cs