Juniper: Juniper.Input.Keyboardable Class Reference
Juniper.Input.Keyboardable Class Reference
This component listens for a given keystroke, firing an event when it occurs. That event can be used to trigger any
Public Member Functions
virtual bool IsInteractable ()
void ActivateEvent ()
Public Attributes
KeyCode key
The keystroke to listen for. The event will be triggered on-key-down.
UnityEvent onActivated = new UnityEvent()
The event that fires when the shortcut key is activated. You should only prefer to use this version of the event over Activated in the Unity Editor, where standard .NET events are inexplicably unavailable.
bool interactable = true
Protected Member Functions
override void OnDisable ()
override void OnEnable ()
virtual void Awake ()
virtual void Update ()
Protected Attributes
UnifiedInputModule input
Properties
KeyCode KeyCode [get]
Events
EventHandler Activated
The event that fires when the shortcut key is activated. You should prefer to use this event over onActivated whenever possible, such as wiring up events programmatically.
Detailed Description
This component listens for a given keystroke, firing an event when it occurs. That event can be used to trigger any
public void Method(); through the Unity Editor.
Definition at line 14 of file Keyboardable.cs.
Member Function Documentation
ActivateEvent()
void Juniper.Input.AbstractShortcutable.ActivateEvent () inline inherited
Definition at line 88 of file AbstractShortcutable.cs.
         {
             if (IsInteractable())
             {
                 onActivated?.Invoke();
                 Activated?.Invoke(this, EventArgs.Empty);
                 input.ClickButtons(GetComponents<IPointerClickHandler>());
             }
         }
References Juniper.Input.AbstractShortcutable.Activated, Juniper.Input.AbstractUnifiedInputModule.ClickButtons(), Juniper.Input.AbstractShortcutable.input, Juniper.Input.AbstractShortcutable.IsInteractable(), and Juniper.Input.AbstractShortcutable.onActivated.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
Awake()
virtual void Juniper.Input.AbstractShortcutable.Awake () inline protected virtual inherited
Definition at line 49 of file AbstractShortcutable.cs.
         {
             Find.Any(out input);
             var parentControl = GetComponent<IPointerClickHandler>();
             if (parentControl is UnityEngine.UI.Selectable selectable)
             {
                 isParentEnabled = selectable.IsInteractable;
             }
             else if (parentControl is AbstractTouchable touchable)
             {
                 isParentEnabled = touchable.IsInteractable;
             }
             else
             {
                 isParentEnabled = AlwaysEnabled;
             }
         }
References Juniper.Input.AbstractShortcutable.AlwaysEnabled(), Juniper.Input.AbstractShortcutable.input, and Juniper.Input.AbstractShortcutable.isParentEnabled.
IsInteractable()
virtual bool Juniper.Input.AbstractShortcutable.IsInteractable () inline virtual inherited
Reimplemented in Juniper.Speech.Keywordable.
Definition at line 41 of file AbstractShortcutable.cs.
         {
             return isActiveAndEnabled
                 && interactable
                 && input != null
                 && isParentEnabled();
         }
References Juniper.Input.AbstractShortcutable.input, Juniper.Input.AbstractShortcutable.interactable, and Juniper.Input.AbstractShortcutable.isParentEnabled.
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent(), and Juniper.Input.AbstractShortcutable.Update().
OnDisable()
override void Juniper.Input.Keyboardable.OnDisable () inline protected virtual
Implements Juniper.Input.AbstractShortcutable.
Definition at line 29 of file Keyboardable.cs.
         {
             if(input != null)
             {
                 input.RemoveKeyboardShortcut(this);
             }
         }
References Juniper.Input.AbstractShortcutable.input, and Juniper.Input.AbstractUnifiedInputModule.RemoveKeyboardShortcut().
OnEnable()
override void Juniper.Input.Keyboardable.OnEnable () inline protected virtual
Implements Juniper.Input.AbstractShortcutable.
Definition at line 37 of file Keyboardable.cs.
         {
             if(input != null)
             {
                 input.AddKeyboardShortcut(this);
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.AddKeyboardShortcut(), and Juniper.Input.AbstractShortcutable.input.
Update()
virtual void Juniper.Input.AbstractShortcutable.Update () inline protected virtual inherited
Definition at line 71 of file AbstractShortcutable.cs.
         {
             var isInteractable = IsInteractable();
             if (isInteractable != wasInteractable)
             {
                 wasInteractable = isInteractable;
                 if (isInteractable)
                 {
                     OnEnable();
                 }
                 else
                 {
                     OnDisable();
                 }
             }
         }
References Juniper.Input.AbstractShortcutable.IsInteractable(), Juniper.Input.AbstractShortcutable.OnDisable(), Juniper.Input.AbstractShortcutable.OnEnable(), and Juniper.Input.AbstractShortcutable.wasInteractable.
Member Data Documentation
input
UnifiedInputModule Juniper.Input.AbstractShortcutable.input protected inherited
Definition at line 35 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent(), Juniper.Input.AbstractShortcutable.Awake(), Juniper.Speech.Keywordable.IsInteractable(), Juniper.Input.AbstractShortcutable.IsInteractable(), Juniper.Input.Keyboardable.OnDisable(), Juniper.Speech.Keywordable.OnDisable(), Juniper.Input.Keyboardable.OnEnable(), and Juniper.Speech.Keywordable.OnEnable().
interactable
bool Juniper.Input.AbstractShortcutable.interactable = true inherited
Definition at line 37 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.IsInteractable().
key
KeyCode Juniper.Input.Keyboardable.key
The keystroke to listen for. The event will be triggered on-key-down.
Definition at line 19 of file Keyboardable.cs.
onActivated
UnityEvent Juniper.Input.AbstractShortcutable.onActivated = new UnityEvent() inherited
The event that fires when the shortcut key is activated. You should only prefer to use this version of the event over Activated in the Unity Editor, where standard .NET events are inexplicably unavailable.
Definition at line 26 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent().
Property Documentation
KeyCode
KeyCode Juniper.Input.Keyboardable.KeyCode get
Definition at line 22 of file Keyboardable.cs.
         {
             get
             {
                 return key;
             }
         }
Event Documentation
Activated
EventHandler Juniper.Input.AbstractShortcutable.Activated inherited
The event that fires when the shortcut key is activated. You should prefer to use this event over onActivated whenever possible, such as wiring up events programmatically.
Definition at line 32 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Input/Keyboardable.cs