Juniper: Juniper.Display.AbstractDisplayManager Class Reference
Juniper.Display.AbstractDisplayManager Class Reference
Classes
class ARModeEvent
class DisplayTypeEvent
Public Member Functions
virtual void Awake ()
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void Install (bool reset)
Install, with or without a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
void StartXRDisplay ()
void StopXRDisplay ()
void DisableDisplay ()
void ResumeDisplay ()
void StartAR ()
void StopAR ()
virtual void Update ()
Updates the camera FOV according to game window dimensions, and moves the camera into position at the avatar height.
Static Public Member Functions
static void SetupMainCamera ()
static void MoveEventCameraToPointer (IPointerDevice pointer)
Public Attributes
DisplayTypeEvent onDisplayTypeChange
ARModeEvent onARModeChange
Protected Member Functions
virtual void OnDisplayTypeChange ()
virtual void OnARModeChange ()
Protected Attributes
CameraControl cameraCtrl
Properties
static Camera MainCamera [get]
static Camera EventCamera [get]
static CameraClearFlags ClearFlags [get, set]
static Color BackgroundColor [get, set]
static int CullingMask [get, set]
JuniperSystem Sys [get]
PlatformTypes CurrentPlatform [get, private set]
SystemTypes System [get, private set]
DisplayTypes DisplayType [get, private set]
DisplayTypes SupportedDisplayType [get]
AugmentedRealityTypes ARMode [get, private set]
AugmentedRealityTypes SupportedARMode [get]
Options Option [get, private set]
bool IsValidDisplayChange [get]
virtual float DEFAULT_FOV [get]
Gets the field of view value that should be targeted for the running application.
float VerticalFieldOfView [get]
The camera field of view along the large screen axis in portrait mode, the narrow axis in landscape mode.
Events
EventHandler< DisplayTypes > DisplayTypeChange
EventHandler< AugmentedRealityTypes > ARModeChange
Private Member Functions
void ChangeDisplayType (DisplayTypes nextDisplayType)
void ChangeARMode (AugmentedRealityTypes nextARMode)
Static Private Member Functions
static Camera MakeCamera (string tag, string name)
static bool ChangeXRDevice (DisplayTypes displayType)
Private Attributes
JuniperSystem jp
SystemTypes lastSystem
DisplayTypes lastDisplayType
DisplayTypes resumeMode
AugmentedRealityTypes lastARMode
Options lastOption
Static Private Attributes
static Camera cam
The main camera, cached so we don't incur a cost to look it up all the time.
static Camera eventCam
Detailed Description
Definition at line 58 of file DisplayManager.cs.
Member Function Documentation
Awake()
virtual void Juniper.Display.AbstractDisplayManager.Awake () inline virtual
Definition at line 280 of file DisplayManager.cs.
         {
             cam = GetComponent<Camera>();
             Install(false);
             lastSystem = System;
             lastOption = Option;
             StartXRDisplay();
         }
References Juniper.Display.AbstractDisplayManager.cam, Juniper.Display.AbstractDisplayManager.Install(), Juniper.Display.AbstractDisplayManager.lastOption, Juniper.Display.AbstractDisplayManager.lastSystem, Juniper.Display.AbstractDisplayManager.Option, Juniper.Display.AbstractDisplayManager.StartXRDisplay(), and Juniper.Display.AbstractDisplayManager.System.
ChangeARMode()
void Juniper.Display.AbstractDisplayManager.ChangeARMode (AugmentedRealityTypes nextARMode) inline private
Definition at line 473 of file DisplayManager.cs.
         {
             if (nextARMode != lastARMode)
             {
                 try
                 {
                     ARMode = nextARMode;
                     if (ARMode == AugmentedRealityTypes.None)
                     {
                         MainCamera.clearFlags = CameraClearFlags.Skybox;
                     }
                     else
                     {
                         MainCamera.clearFlags = CameraClearFlags.Color;
                         MainCamera.backgroundColor = ColorExt.TransparentBlack;
                     }
                     lastARMode = ARMode;
                     OnARModeChange();
                 }
                 catch (Exception exp)
                 {
                     Debug.LogError($"Could not change AR mode from {lastARMode} to {ARMode}. Reason: {exp.Message}");
                     ARMode = lastARMode;
                 }
             }
         }
References Juniper.Display.AbstractDisplayManager.ARMode, Juniper.XR.Debug, Juniper.Display.AbstractDisplayManager.lastARMode, Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.Display.AbstractDisplayManager.OnARModeChange(), and UnityEngine.ColorExt.TransparentBlack.
Referenced by Juniper.Display.AbstractDisplayManager.StartAR(), and Juniper.Display.AbstractDisplayManager.StopAR().
ChangeDisplayType()
void Juniper.Display.AbstractDisplayManager.ChangeDisplayType (DisplayTypes nextDisplayType) inline private
Definition at line 389 of file DisplayManager.cs.
         {
             if (nextDisplayType != lastDisplayType)
             {
                 try
                 {
                     DisplayType = nextDisplayType;
                     if (IsValidDisplayChange)
                     {
                         lastDisplayType = DisplayType;
 #if UNITY_MODULES_XR && !UNITY_EDITOR
                         ChangeXRDevice(DisplayType);
 #endif
                         MainCamera.enabled = DisplayType != DisplayTypes.None;
                         if (!Mathf.Approximately(MainCamera.fieldOfView, VerticalFieldOfView))
{
                             MainCamera.fieldOfView = VerticalFieldOfView;
                         }
                         OnDisplayTypeChange();
                         if (DisplayType != DisplayTypes.None)
{
                             StartAR();
                         }
                     }
                     else
                     {
                         throw new InvalidOperationException("Unsupported platform");
                     }
                 }
                 catch (Exception exp)
                 {
                     Debug.LogError($"Could not change display type from {lastDisplayType} to {DisplayType}. Reason: {exp.Message}");
                     DisplayType = lastDisplayType;
                 }
             }
         }
References Juniper.Display.AbstractDisplayManager.ChangeXRDevice(), Juniper.XR.Debug, Juniper.Display.AbstractDisplayManager.DisplayType, Juniper.Display.AbstractDisplayManager.IsValidDisplayChange, Juniper.Display.AbstractDisplayManager.lastDisplayType, Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.Display.AbstractDisplayManager.OnDisplayTypeChange(), Juniper.Display.AbstractDisplayManager.StartAR(), and Juniper.Display.AbstractDisplayManager.VerticalFieldOfView.
Referenced by Juniper.Display.AbstractDisplayManager.DisableDisplay(), Juniper.Display.AbstractDisplayManager.ResumeDisplay(), Juniper.Display.AbstractDisplayManager.StartXRDisplay(), and Juniper.Display.AbstractDisplayManager.StopXRDisplay().
ChangeXRDevice()
static bool Juniper.Display.AbstractDisplayManager.ChangeXRDevice (DisplayTypes displayType) inline static private
Definition at line 321 of file DisplayManager.cs.
         {
             var xrDevice = UnityXRPlatforms.None;
             if (displayType == DisplayTypes.Stereo)
             {
                 if (JuniperPlatform.CurrentPlatform == PlatformTypes.AndroidDaydream)
                 {
                     xrDevice = UnityXRPlatforms.daydream;
                 }
                 else if (JuniperPlatform.CurrentPlatform == PlatformTypes.AndroidOculus
                     || JuniperPlatform.CurrentPlatform == PlatformTypes.StandaloneOculus)
                 {
                     xrDevice = UnityXRPlatforms.Oculus;
                 }
                 else if (JuniperPlatform.CurrentPlatform == PlatformTypes.UWPHoloLens
                     || JuniperPlatform.CurrentPlatform == PlatformTypes.UWPWindowsMR)
                 {
                     xrDevice = UnityXRPlatforms.WindowsMR;
                 }
                 else if (JuniperPlatform.CurrentPlatform == PlatformTypes.MagicLeap)
                 {
                     xrDevice = UnityXRPlatforms.Lumin;
                 }
                 else if (JuniperPlatform.CurrentPlatform == PlatformTypes.StandaloneSteamVR)
                 {
                     xrDevice = UnityXRPlatforms.OpenVR;
                 }
                 else if (JuniperPlatform.CurrentPlatform == PlatformTypes.AndroidCardboard
                     || JuniperPlatform.CurrentPlatform == PlatformTypes.IOSCardboard)
                 {
                     xrDevice = UnityXRPlatforms.cardboard;
                 }
             }
             var xrDeviceName = xrDevice.ToString();
             if (XRSettings.loadedDeviceName == xrDeviceName)
             {
                 return true;
             }
             else if (XRSettings.supportedDevices.Contains(xrDeviceName))
             {
                 XRSettings.LoadDeviceByName(xrDeviceName);
                 return true;
             }
             else
             {
                 Debug.LogErrorFormat(
                     "XR Device '{0}' is not available. Current is '{1}'. Available are '{2}'.",
                     xrDeviceName,
                     XRSettings.loadedDeviceName,
                     string.Join(", ", XRSettings.supportedDevices));
                 return false;
             }
         }
References Juniper.JuniperPlatform.CurrentPlatform, and Juniper.XR.Debug.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType().
DisableDisplay()
void Juniper.Display.AbstractDisplayManager.DisableDisplay () inline
Definition at line 458 of file DisplayManager.cs.
         {
             StopAR();
             resumeMode = DisplayType;
             ChangeDisplayType(DisplayTypes.None);
         }
References Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.DisplayType, Juniper.Display.AbstractDisplayManager.resumeMode, and Juniper.Display.AbstractDisplayManager.StopAR().
Install()
virtual void Juniper.Display.AbstractDisplayManager.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Display.DaydreamDisplayManager, Juniper.Display.ARKitDisplayManager, and Juniper.Display.ViveFocusDisplayManager.
Definition at line 308 of file DisplayManager.cs.
         {
             Avatar.Ensure();
             this.Ensure<QualityDegrader>();
             cameraCtrl = this.Ensure<CameraControl>();
         }
References Juniper.Display.AbstractDisplayManager.cameraCtrl, and Juniper.Avatar.Ensure().
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), and Juniper.Display.AbstractDisplayManager.Reinstall().
MakeCamera()
static Camera Juniper.Display.AbstractDisplayManager.MakeCamera (string tag, string name) inline static private
Definition at line 67 of file DisplayManager.cs.
         {
             TagManager.Normalize(tag);
             var cam = ComponentExt.FindAny<Camera>(camera => camera.CompareTag(tag));
             if (cam == null)
             {
                 var obj = new GameObject(name);
                 cam = obj.AddComponent<Camera>();
 #pragma warning disable CS0618 // Type or member is obsolete
                 obj.AddComponent<GUILayer>();
 #pragma warning restore CS0618 // Type or member is obsolete
                 cam.gameObject.tag = tag;
                 var js = ComponentExt.FindAny<JuniperSystem>();
                 if (js != null)
                 {
                     SceneManager.MoveGameObjectToScene(obj, js.gameObject.scene);
                 }
             }
             return cam;
         }
References Juniper.Display.AbstractDisplayManager.cam, and UnityEngine.TagManager.Normalize().
Referenced by Juniper.Display.AbstractDisplayManager.SetupMainCamera().
MoveEventCameraToPointer()
static void Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer (IPointerDevice pointer) inline static
Definition at line 130 of file DisplayManager.cs.
         {
             EventCamera.transform.position = pointer.transform.position;
             EventCamera.transform.rotation = pointer.transform.rotation;
             EventCamera.farClipPlane = pointer.MaximumPointerDistance;
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, Juniper.Input.Pointers.IPointerDevice.MaximumPointerDistance, and Juniper.Input.Pointers.IPointerDevice.transform.
Referenced by Juniper.Input.AbstractUnifiedInputModule.RaycastAll(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromViewport(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromWorld(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromScreen(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromWorld(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport().
OnARModeChange()
virtual void Juniper.Display.AbstractDisplayManager.OnARModeChange () inline protected virtual
Reimplemented in Juniper.Display.AbstractPassthroughDisplayManager.
Definition at line 511 of file DisplayManager.cs.
         {
             onARModeChange?.Invoke(ARMode);
             ARModeChange?.Invoke(this, ARMode);
         }
References Juniper.Display.AbstractDisplayManager.ARMode, Juniper.Display.AbstractDisplayManager.ARModeChange, and Juniper.Display.AbstractDisplayManager.onARModeChange.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeARMode().
OnDisplayTypeChange()
virtual void Juniper.Display.AbstractDisplayManager.OnDisplayTypeChange () inline protected virtual
Definition at line 439 of file DisplayManager.cs.
         {
             onDisplayTypeChange?.Invoke(DisplayType);
             DisplayTypeChange?.Invoke(this, DisplayType);
         }
References Juniper.Display.AbstractDisplayManager.DisplayType, Juniper.Display.AbstractDisplayManager.DisplayTypeChange, and Juniper.Display.AbstractDisplayManager.onDisplayTypeChange.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType().
Reinstall()
virtual void Juniper.Display.AbstractDisplayManager.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 292 of file DisplayManager.cs.
         {
             Install(true);
         }
References Juniper.Display.AbstractDisplayManager.Install().
ResumeDisplay()
void Juniper.Display.AbstractDisplayManager.ResumeDisplay () inline
Definition at line 465 of file DisplayManager.cs.
         {
             if (resumeMode != DisplayTypes.None)
             {
                 ChangeDisplayType(resumeMode);
             }
         }
References Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), and Juniper.Display.AbstractDisplayManager.resumeMode.
SetupMainCamera()
static void Juniper.Display.AbstractDisplayManager.SetupMainCamera () inline static
Definition at line 98 of file DisplayManager.cs.
         {
             if (cam == null)
             {
                 cam = MakeCamera("MainCamera", "Head");
                 cam.Ensure<DisplayManager>();
             }
         }
References Juniper.Display.AbstractDisplayManager.cam, and Juniper.Display.AbstractDisplayManager.MakeCamera().
Referenced by Juniper.JuniperSystem.Install().
StartAR()
void Juniper.Display.AbstractDisplayManager.StartAR () inline
Definition at line 517 of file DisplayManager.cs.
         {
             ChangeARMode(SupportedARMode);
         }
References Juniper.Display.AbstractDisplayManager.ChangeARMode(), and Juniper.Display.AbstractDisplayManager.SupportedARMode.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
StartXRDisplay()
void Juniper.Display.AbstractDisplayManager.StartXRDisplay () inline
Definition at line 445 of file DisplayManager.cs.
         {
             resumeMode = DisplayTypes.None;
             ChangeDisplayType(SupportedDisplayType);
         }
References Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.resumeMode, and Juniper.Display.AbstractDisplayManager.SupportedDisplayType.
Referenced by Juniper.Display.AbstractDisplayManager.Awake().
StopAR()
void Juniper.Display.AbstractDisplayManager.StopAR () inline
Definition at line 522 of file DisplayManager.cs.
         {
             ChangeARMode(AugmentedRealityTypes.None);
         }
References Juniper.Display.AbstractDisplayManager.ChangeARMode().
Referenced by Juniper.Display.AbstractDisplayManager.DisableDisplay(), Juniper.Display.AbstractDisplayManager.StopXRDisplay(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
StopXRDisplay()
void Juniper.Display.AbstractDisplayManager.StopXRDisplay () inline
Definition at line 451 of file DisplayManager.cs.
         {
             StopAR();
             resumeMode = DisplayType;
             ChangeDisplayType(DisplayTypes.Monoscopic);
         }
References Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.DisplayType, Juniper.Display.AbstractDisplayManager.resumeMode, and Juniper.Display.AbstractDisplayManager.StopAR().
Uninstall()
virtual void Juniper.Display.AbstractDisplayManager.Uninstall () inline virtual
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Display.ViveFocusDisplayManager, Juniper.Display.DaydreamDisplayManager, and Juniper.Display.ARKitDisplayManager.
Definition at line 315 of file DisplayManager.cs.
         {
         }
Update()
virtual void Juniper.Display.AbstractDisplayManager.Update () inline virtual
Updates the camera FOV according to game window dimensions, and moves the camera into position at the avatar height.
Definition at line 565 of file DisplayManager.cs.
         {
             if (CurrentPlatform != JuniperPlatform.CurrentPlatform)
             {
                 Debug.LogWarning($"Cannot change {nameof(Platform)} directly. Use the Juniper menu in the Unity Editor. ({JuniperPlatform.CurrentPlatform} => {CurrentPlatform})");
                 CurrentPlatform = JuniperPlatform.CurrentPlatform;
             }
             if (System != lastSystem)
             {
                 Debug.LogWarning($"Cannot change {nameof(System)} directly. Use the Juniper menu in the Unity Editor. ({lastSystem} => {System})");
                 System = lastSystem;
             }
             if (Option != lastOption)
             {
                 Debug.LogWarning($"Cannot change {nameof(Option)} directly. Use the Juniper menu in the Unity Editor. ({lastOption} => {Option})");
                 Option = lastOption;
             }
             if (DisplayType != lastDisplayType)
             {
                 Debug.LogWarning($"Cannot change {nameof(DisplayType)} directly. Use the {nameof(StartXRDisplay)} method. ({lastDisplayType} => {DisplayType})");
                 DisplayType = lastDisplayType;
             }
             if (ARMode != lastARMode)
             {
                 Debug.LogWarning($"Cannot change {nameof(ARMode)} directly. Use the {nameof(StartAR)} method. ({lastARMode} => {ARMode})");
                 ARMode = lastARMode;
             }
             EventCamera.cullingMask = MainCamera.cullingMask & ~LayerMask.GetMask("Ignore Raycast");
         }
References Juniper.Display.AbstractDisplayManager.ARMode, Juniper.JuniperPlatform.CurrentPlatform, Juniper.Display.AbstractDisplayManager.CurrentPlatform, Juniper.XR.Debug, Juniper.Display.AbstractDisplayManager.DisplayType, Juniper.Display.AbstractDisplayManager.EventCamera, Juniper.Display.AbstractDisplayManager.lastARMode, Juniper.Display.AbstractDisplayManager.lastDisplayType, Juniper.Display.AbstractDisplayManager.lastOption, Juniper.Display.AbstractDisplayManager.lastSystem, Juniper.Display.AbstractDisplayManager.MainCamera, and Juniper.Display.AbstractDisplayManager.Option.
Member Data Documentation
cam
Camera Juniper.Display.AbstractDisplayManager.cam static private
The main camera, cached so we don't incur a cost to look it up all the time.
Definition at line 63 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), Juniper.Display.AbstractDisplayManager.MakeCamera(), and Juniper.Display.AbstractDisplayManager.SetupMainCamera().
cameraCtrl
CameraControl Juniper.Display.AbstractDisplayManager.cameraCtrl protected
Definition at line 306 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Install(), Juniper.Display.AbstractPassthroughDisplayManager.OnARModeChange(), Juniper.Display.DefaultDisplayManager.Start(), and Juniper.Display.DaydreamDisplayManager.Start().
eventCam
Camera Juniper.Display.AbstractDisplayManager.eventCam static private
Definition at line 65 of file DisplayManager.cs.
jp
JuniperSystem Juniper.Display.AbstractDisplayManager.jp private
Definition at line 182 of file DisplayManager.cs.
lastARMode
AugmentedRealityTypes Juniper.Display.AbstractDisplayManager.lastARMode private
Definition at line 264 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeARMode(), and Juniper.Display.AbstractDisplayManager.Update().
lastDisplayType
DisplayTypes Juniper.Display.AbstractDisplayManager.lastDisplayType private
Definition at line 241 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), and Juniper.Display.AbstractDisplayManager.Update().
lastOption
Options Juniper.Display.AbstractDisplayManager.lastOption private
Definition at line 278 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), and Juniper.Display.AbstractDisplayManager.Update().
lastSystem
SystemTypes Juniper.Display.AbstractDisplayManager.lastSystem private
Definition at line 219 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), and Juniper.Display.AbstractDisplayManager.Update().
onARModeChange
ARModeEvent Juniper.Display.AbstractDisplayManager.onARModeChange
Definition at line 507 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.OnARModeChange().
onDisplayTypeChange
DisplayTypeEvent Juniper.Display.AbstractDisplayManager.onDisplayTypeChange
Definition at line 435 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.OnDisplayTypeChange().
resumeMode
DisplayTypes Juniper.Display.AbstractDisplayManager.resumeMode private
Definition at line 242 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.DisableDisplay(), Juniper.Display.AbstractDisplayManager.ResumeDisplay(), Juniper.Display.AbstractDisplayManager.StartXRDisplay(), and Juniper.Display.AbstractDisplayManager.StopXRDisplay().
Property Documentation
ARMode
AugmentedRealityTypes Juniper.Display.AbstractDisplayManager.ARMode get private set
Definition at line 245 of file DisplayManager.cs.
         {
             get
             {
                 return Sys.ARMode;
             }
             private set
             {
                 Sys.ARMode = value;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Display.AbstractPassthroughDisplayManager.OnARModeChange(), Juniper.Display.AbstractDisplayManager.OnARModeChange(), Juniper.Animation.FadeTransition.OnEntered(), Juniper.Animation.FadeTransition.OnExiting(), and Juniper.Display.AbstractDisplayManager.Update().
BackgroundColor
Color Juniper.Display.AbstractDisplayManager.BackgroundColor static get set
Definition at line 153 of file DisplayManager.cs.
         {
             get
             {
                 return MainCamera.backgroundColor;
             }
             set
             {
                 foreach (var camera in MainCamera.GetComponentsInChildren<Camera>())
                 {
                     camera.backgroundColor = value;
                 }
             }
         }
Referenced by Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
ClearFlags
CameraClearFlags Juniper.Display.AbstractDisplayManager.ClearFlags static get set
Definition at line 138 of file DisplayManager.cs.
         {
             get
             {
                 return MainCamera.clearFlags;
             }
             set
             {
                 foreach (var camera in MainCamera.GetComponentsInChildren<Camera>())
                 {
                     camera.clearFlags = value;
                 }
             }
         }
Referenced by Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
CullingMask
int Juniper.Display.AbstractDisplayManager.CullingMask static get set
Definition at line 168 of file DisplayManager.cs.
         {
             get
             {
                 return MainCamera.cullingMask;
             }
             set
             {
                 foreach (var camera in MainCamera.GetComponentsInChildren<Camera>())
                 {
                     camera.cullingMask = value;
                 }
             }
         }
Referenced by Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
CurrentPlatform
PlatformTypes Juniper.Display.AbstractDisplayManager.CurrentPlatform get private set
Definition at line 196 of file DisplayManager.cs.
         {
             get
             {
                 return Sys.CurrentPlatform;
             }
             private set
             {
                 Sys.CurrentPlatform = value;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.Update().
DEFAULT_FOV
virtual float Juniper.Display.AbstractDisplayManager.DEFAULT_FOV get protected
Gets the field of view value that should be targeted for the running application.
The default field of view.
Definition at line 532 of file DisplayManager.cs.
         {
             get
             {
                 return MainCamera.fieldOfView;
             }
         }
DisplayType
DisplayTypes Juniper.Display.AbstractDisplayManager.DisplayType get private set
Definition at line 222 of file DisplayManager.cs.
         {
             get
             {
                 return Sys.DisplayType;
             }
             private set
             {
                 Sys.DisplayType = value;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.DisableDisplay(), Juniper.Display.AbstractDisplayManager.OnDisplayTypeChange(), Juniper.Display.AbstractDisplayManager.StopXRDisplay(), and Juniper.Display.AbstractDisplayManager.Update().
EventCamera
Camera Juniper.Display.AbstractDisplayManager.EventCamera static get
Definition at line 108 of file DisplayManager.cs.
         {
             get
             {
                 if (eventCam == null)
                 {
                     eventCam = MakeCamera("EventCamera", "PointerCamera");
                     eventCam.cullingMask = ~LayerMask.GetMask("Ignore Raycast");
                     eventCam.Ensure<PhysicsRaycaster>();
                     eventCam.clearFlags = CameraClearFlags.SolidColor;
                     eventCam.backgroundColor = ColorExt.TransparentBlack;
                     eventCam.depth = MainCamera.depth - 1;
                     eventCam.allowHDR = false;
                     eventCam.allowMSAA = false;
                     eventCam.enabled = false;
                     eventCam.Ensure<PhysicsRaycaster>();
                 }
                 return eventCam;
             }
         }
Referenced by Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromViewport(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromWorld(), Juniper.Input.Pointers.Probe.Start(), Juniper.Display.AbstractDisplayManager.Update(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromScreen(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromWorld(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport().
IsValidDisplayChange
bool Juniper.Display.AbstractDisplayManager.IsValidDisplayChange get private
Definition at line 380 of file DisplayManager.cs.
         {
             get
             {
                 return DisplayType == SupportedDisplayType
                     || DisplayType == DisplayTypes.None
                     || DisplayType == DisplayTypes.Monoscopic;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType().
MainCamera
Camera Juniper.Display.AbstractDisplayManager.MainCamera static get
Definition at line 90 of file DisplayManager.cs.
         {
             get
             {
                 SetupMainCamera();
                 return cam;
             }
         }
Referenced by Juniper.Widgets.FollowMainCamera.Awake(), Juniper.Animation.SpiralTransition.Awake(), Juniper.Audio.AbstractInteractionAudio.Awake(), Juniper.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Avatar.Ensure(), Juniper.Avatar.Install(), Juniper.Audio.AbstractInteractionAudio.Install(), Juniper.Widgets.AbstractValued.LateUpdate(), Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck(), Juniper.MasterSceneController.SetupFader(), Juniper.Input.RocketPack.Start(), Juniper.Audio.AbstractInteractionAudio.Uninstall(), Juniper.Widgets.Standoff.Update(), Juniper.Widgets.Label.Update(), Juniper.World.CompassRose.Update(), Juniper.Animation.SpiralTransition.Update(), Juniper.Widgets.AttentionDirector.Update(), and Juniper.Display.AbstractDisplayManager.Update().
Option
Options Juniper.Display.AbstractDisplayManager.Option get private set
Definition at line 267 of file DisplayManager.cs.
         {
             get
             {
                 return Sys.Option;
             }
             private set
             {
                 Sys.Option = value;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), and Juniper.Display.AbstractDisplayManager.Update().
SupportedARMode
AugmentedRealityTypes Juniper.Display.AbstractDisplayManager.SupportedARMode get
Definition at line 257 of file DisplayManager.cs.
         {
             get
             {
                 return Sys.SupportedARMode;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.StartAR().
SupportedDisplayType
DisplayTypes Juniper.Display.AbstractDisplayManager.SupportedDisplayType get
Definition at line 234 of file DisplayManager.cs.
         {
             get
             {
                 return Sys.SupportedDisplayType;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.StartXRDisplay().
Sys
JuniperSystem Juniper.Display.AbstractDisplayManager.Sys get private
Definition at line 184 of file DisplayManager.cs.
         {
             get
             {
                 if (jp == null)
                 {
                     jp = ComponentExt.FindAny<JuniperSystem>();
                 }
                 return jp;
             }
         }
System
SystemTypes Juniper.Display.AbstractDisplayManager.System get private set
Definition at line 208 of file DisplayManager.cs.
         {
             get
             {
                 return Sys.System;
             }
             private set
             {
                 Sys.System = value;
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.Awake().
VerticalFieldOfView
float Juniper.Display.AbstractDisplayManager.VerticalFieldOfView get
The camera field of view along the large screen axis in portrait mode, the narrow axis in landscape mode.
The vertical field of view.
Definition at line 545 of file DisplayManager.cs.
         {
             get
             {
                 if (Screen.width < Screen.height)
                 {
                     var tan = Mathf.Tan(Units.Degrees.Radians(DEFAULT_FOV / 2));
                     var aspect = (float)Screen.height / Screen.width;
                     return 2 * Units.Radians.Degrees(Mathf.Atan(tan * aspect));
                 }
                 else
                 {
                     return DEFAULT_FOV;
                 }
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType().
Event Documentation
ARModeChange
EventHandler<AugmentedRealityTypes> Juniper.Display.AbstractDisplayManager.ARModeChange
Definition at line 509 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.OnARModeChange().
DisplayTypeChange
EventHandler<DisplayTypes> Juniper.Display.AbstractDisplayManager.DisplayTypeChange
Definition at line 437 of file DisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.OnDisplayTypeChange().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Display/DisplayManager.cs