Juniper: Juniper.Haptics.AbstractHapticImmediateExpressor Class Reference
Juniper.Haptics.AbstractHapticImmediateExpressor Class Reference abstract
Public Member Functions
override void Cancel ()
Cancel the current vibration, whatever it is.
override void Play (HapticExpression expr)
Play a canned haptic pattern.
override void Play (params HapticPatternElement[] points)
Play a haptic pattern.
override void Play (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
override void Play (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
override void Vibrate (HapticPatternElement point)
Play a single element of a haptic pattern.
override void Vibrate (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
override void Vibrate (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
Protected Member Functions
override IEnumerator VibrateCoroutine (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
abstract void SetVibration (long milliseconds, float amplitude)
virtual IEnumerator VibrateCoroutine (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
virtual IEnumerator PlayCoroutine (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
virtual IEnumerator PlayCoroutine (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
Detailed Description
Definition at line 6 of file AbstractHapticImmediateExpressor.cs.
Member Function Documentation
Cancel()
override void Juniper.Haptics.AbstractHapticImmediateExpressor.Cancel () inline virtual
Cancel the current vibration, whatever it is.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 8 of file AbstractHapticImmediateExpressor.cs.
         {
             base.Cancel();
             SetVibration(0, 0);
         }
References Juniper.Haptics.AbstractHapticImmediateExpressor.SetVibration().
Play() [1/4]
override void Juniper.Haptics.AbstractHapticRetainedExpressor.Play (HapticExpression expr) inline virtual inherited
Play a canned haptic pattern.
Parameters
expr
Implements Juniper.Haptics.AbstractHapticDevice.
Reimplemented in Juniper.Haptics.WindowsMRHaptics.
Definition at line 25 of file AbstractHapticRetainedExpressor.cs.
         {
             HapticPatternElement.Play(this, expr);
         }
References Juniper.Haptics.HapticPatternElement.Play().
Play() [2/4]
override void Juniper.Haptics.AbstractHapticRetainedExpressor.Play (params HapticPatternElement [] points) inline virtual inherited
Play a haptic pattern.
Parameters
points
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 34 of file AbstractHapticRetainedExpressor.cs.
         {
             this.Run(PlayCoroutine(points));
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.PlayCoroutine().
Play() [3/4]
override void Juniper.Haptics.AbstractHapticRetainedExpressor.Play (long [] pattern) inline virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 61 of file AbstractHapticRetainedExpressor.cs.
         {
             this.Run(PlayCoroutine(pattern));
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.PlayCoroutine().
Play() [4/4]
override void Juniper.Haptics.AbstractHapticRetainedExpressor.Play (long [] pattern, float [] amplitudes) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 71 of file AbstractHapticRetainedExpressor.cs.
         {
             this.Run(PlayCoroutine(pattern, amplitudes));
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.PlayCoroutine().
PlayCoroutine() [1/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticRetainedExpressor.PlayCoroutine (long [] pattern) inline protected virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Definition at line 99 of file AbstractHapticRetainedExpressor.cs.
         {
             float amplitude = 1;
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitude);
                 amplitude = 1 - amplitude;
             }
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.VibrateCoroutine().
Referenced by Juniper.Haptics.AbstractHapticRetainedExpressor.Play().
PlayCoroutine() [2/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticRetainedExpressor.PlayCoroutine (long [] pattern, float [] amplitudes) inline protected virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Definition at line 114 of file AbstractHapticRetainedExpressor.cs.
         {
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitudes[i]);
             }
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.VibrateCoroutine().
SetVibration()
abstract void Juniper.Haptics.AbstractHapticImmediateExpressor.SetVibration (long milliseconds, float amplitude) protected pure virtual
Implemented in Juniper.Haptics.DefaultHaptics.
Referenced by Juniper.Haptics.AbstractHapticImmediateExpressor.Cancel(), and Juniper.Haptics.AbstractHapticImmediateExpressor.VibrateCoroutine().
Vibrate() [1/3]
override void Juniper.Haptics.AbstractHapticRetainedExpressor.Vibrate (HapticPatternElement point) inline virtual inherited
Play a single element of a haptic pattern.
Parameters
point
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 43 of file AbstractHapticRetainedExpressor.cs.
         {
             this.Run(VibrateCoroutine(point));
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.VibrateCoroutine().
Vibrate() [2/3]
override void Juniper.Haptics.AbstractHapticRetainedExpressor.Vibrate (long milliseconds) inline virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 52 of file AbstractHapticRetainedExpressor.cs.
         {
             this.Run(VibrateCoroutine(milliseconds));
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.VibrateCoroutine().
Vibrate() [3/3]
override void Juniper.Haptics.AbstractHapticRetainedExpressor.Vibrate (long milliseconds, float amplitude) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Haptics.AbstractHapticDevice.
Definition at line 81 of file AbstractHapticRetainedExpressor.cs.
         {
             this.Run(VibrateCoroutine(milliseconds, amplitude));
         }
References Juniper.Haptics.AbstractHapticRetainedExpressor.VibrateCoroutine().
VibrateCoroutine() [1/2]
override IEnumerator Juniper.Haptics.AbstractHapticImmediateExpressor.VibrateCoroutine (long milliseconds, float amplitude) inline protected virtual
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Haptics.AbstractHapticRetainedExpressor.
Definition at line 14 of file AbstractHapticImmediateExpressor.cs.
         {
             var end = DateTime.Now.AddMilliseconds(milliseconds);
             SetVibration(milliseconds, amplitude);
             while(DateTime.Now < end)
             {
                 yield return null;
             }
         }
References Juniper.Haptics.AbstractHapticImmediateExpressor.SetVibration().
VibrateCoroutine() [2/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticRetainedExpressor.VibrateCoroutine (long milliseconds) inline protected virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Definition at line 90 of file AbstractHapticRetainedExpressor.cs.
         {
             yield return VibrateCoroutine(milliseconds, 1);
         }
Referenced by Juniper.Haptics.AbstractHapticRetainedExpressor.PlayCoroutine(), Juniper.Haptics.AbstractHapticRetainedExpressor.Vibrate(), and Juniper.Haptics.AbstractHapticRetainedExpressor.VibrateCoroutine().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Haptics/AbstractHapticImmediateExpressor.cs