Juniper: Juniper.Mathematics.KalmanMotionFilter Class Reference
Juniper.Mathematics.KalmanMotionFilter Class Reference
Public Member Functions
override void UpdateState (Vector3 point)
Public Attributes
uint componentCount = 2
float measurementNoise = 10
uint processNoiseScale = 100
float processNoiseExponent = 1
Properties
uint ComponentCount [get, set]
uint Dimension [get, set]
DiscreteKalmanFilter< Vector3[], Vector3 > Kalman [get, set]
override Vector3? PredictedPosition [get]
override Vector3??? Position [get]
Private Member Functions
uint X (uint i)
uint Y (uint i)
uint Z (uint i)
Vector3 [] ToVector3s (double[] arr)
Vector3 ToVector3 (double[] arr)
double [] ToArray (Vector3[] vecs)
double [] ToArray (Vector3 vec)
double [,] GetProcessNoise (Func< uint, double > getProcNoiseForVec)
double [,] MakePositionMeasurementMatrix ()
double [,] MakeTransitionMatrix ()
Private Attributes
float mNoise
uint procNoiseK
float procNoiseE
const uint VectorSize = 3
Vector3? lastPoint
Detailed Description
Definition at line 13 of file KalmanMotionFilter.cs.
Member Function Documentation
GetProcessNoise()
double [,] Juniper.Mathematics.KalmanMotionFilter.GetProcessNoise (Func< uint, double > getProcNoiseForVec) inline private
Definition at line 182 of file KalmanMotionFilter.cs.
         {
             var vec = new double[Dimension];
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 for (uint x = 0; x < VectorSize; ++x)
                 {
                     vec[i * VectorSize + x] = getProcNoiseForVec(i);
                 }
             }
             return Matrix.Diagonal((int)Dimension, vec);
         }
References Juniper.Mathematics.KalmanMotionFilter.ComponentCount, Juniper.Mathematics.KalmanMotionFilter.Dimension, and Juniper.Mathematics.KalmanMotionFilter.VectorSize.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
MakePositionMeasurementMatrix()
double [,] Juniper.Mathematics.KalmanMotionFilter.MakePositionMeasurementMatrix () inline private
Definition at line 195 of file KalmanMotionFilter.cs.
         {
             var m = new double[VectorSize, ComponentCount * VectorSize];
             for (uint i = 0; i < VectorSize; ++i)
             {
                 m[i, i * ComponentCount] = 1;
             }
             return m;
         }
References Juniper.Mathematics.KalmanMotionFilter.ComponentCount, and Juniper.Mathematics.KalmanMotionFilter.VectorSize.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
MakeTransitionMatrix()
double [,] Juniper.Mathematics.KalmanMotionFilter.MakeTransitionMatrix () inline private
Definition at line 205 of file KalmanMotionFilter.cs.
         {
             var t = Time.fixedDeltaTime;
             var parts = new double[ComponentCount];
             double accum = 1;
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 parts[i] = accum * Mathf.Pow(t, i);
                 accum /= i + 1;
             }
             var m = new double[Dimension, Dimension];
             for (uint y = 0; y < Dimension; ++y)
             {
                 var chunkRow = y % ComponentCount;
                 for (uint x = 0; x < ComponentCount - chunkRow; ++x)
                 {
                     m[y, y + x] = parts[x];
                 }
             }
             return m;
         }
References Juniper.Mathematics.KalmanMotionFilter.ComponentCount, and Juniper.Mathematics.KalmanMotionFilter.Dimension.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
ToArray() [1/2]
double [] Juniper.Mathematics.KalmanMotionFilter.ToArray (Vector3 [] vecs) inline private
Definition at line 161 of file KalmanMotionFilter.cs.
         {
             var arr = new double[Dimension];
             for (uint i = 0; i < vecs.Length; ++i)
             {
                 arr[X(i)] = vecs[i].x;
                 arr[Y(i)] = vecs[i].y;
                 arr[Z(i)] = vecs[i].z;
             }
             return arr;
         }
References Juniper.Mathematics.KalmanMotionFilter.Dimension, Juniper.Mathematics.KalmanMotionFilter.X(), Juniper.Mathematics.KalmanMotionFilter.Y(), and Juniper.Mathematics.KalmanMotionFilter.Z().
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
ToArray() [2/2]
double [] Juniper.Mathematics.KalmanMotionFilter.ToArray (Vector3 vec) inline private
Definition at line 173 of file KalmanMotionFilter.cs.
         {
             var arr = new double[Dimension];
             arr[X(0)] = vec.x;
             arr[Y(0)] = vec.y;
             arr[Z(0)] = vec.z;
             return arr;
         }
References Juniper.Mathematics.KalmanMotionFilter.Dimension, Juniper.Mathematics.KalmanMotionFilter.X(), Juniper.Mathematics.KalmanMotionFilter.Y(), and Juniper.Mathematics.KalmanMotionFilter.Z().
ToVector3()
Vector3 Juniper.Mathematics.KalmanMotionFilter.ToVector3 (double [] arr) inline private
Definition at line 153 of file KalmanMotionFilter.cs.
         {
             return new Vector3(
                 (float)arr[X(0)],
                 (float)arr[Y(0)],
                 (float)arr[Z(0)]);
         }
References Juniper.Mathematics.KalmanMotionFilter.X(), Juniper.Mathematics.KalmanMotionFilter.Y(), and Juniper.Mathematics.KalmanMotionFilter.Z().
ToVector3s()
Vector3 [] Juniper.Mathematics.KalmanMotionFilter.ToVector3s (double [] arr) inline private
Definition at line 141 of file KalmanMotionFilter.cs.
         {
             var vecs = new Vector3[ComponentCount];
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 vecs[i].x = (float)arr[X(i)];
                 vecs[i].y = (float)arr[Y(i)];
                 vecs[i].z = (float)arr[Z(i)];
             }
             return vecs;
         }
References Juniper.Mathematics.KalmanMotionFilter.ComponentCount, Juniper.Mathematics.KalmanMotionFilter.X(), Juniper.Mathematics.KalmanMotionFilter.Y(), and Juniper.Mathematics.KalmanMotionFilter.Z().
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
UpdateState()
override void Juniper.Mathematics.KalmanMotionFilter.UpdateState (Vector3 point) inline virtual
Implements Juniper.Mathematics.AbstractMotionFilter.
Definition at line 93 of file KalmanMotionFilter.cs.
         {
             componentCount = Math.Max(1, componentCount);
             if (Kalman != null
                 && componentCount == ComponentCount
                 && Mathf.Approximately(measurementNoise, mNoise)
                 && processNoiseScale == procNoiseK
                 && Mathf.Approximately(processNoiseExponent, procNoiseE))
             {
                 Kalman.Correct(point);
             }
             else
             {
                 ComponentCount = componentCount;
                 Dimension = VectorSize * ComponentCount;
                 mNoise = measurementNoise;
                 procNoiseK = processNoiseScale;
                 procNoiseE = processNoiseExponent;
                 var initialState = new Vector3[ComponentCount];
                 initialState[0] = lastPoint ?? point;
                 Kalman = new DiscreteKalmanFilter<Vector3[], Vector3>(
                     initialState,
                     GetProcessNoise(_ => processNoiseScale),
                     (int)VectorSize,
                     0,
                     ToArray,
                     ToVector3s,
                     ToArray)
                 {
                     ProcessNoise = GetProcessNoise(i =>
                         Mathf.Pow(processNoiseScale, processNoiseExponent * (i + 1))),
                     MeasurementMatrix = MakePositionMeasurementMatrix(),
                     TransitionMatrix = MakeTransitionMatrix(),
                     MeasurementNoise = Matrix.Diagonal((int)VectorSize, (double)measurementNoise)
                 };
                 if (lastPoint != null)
                 {
                     Kalman.Correct(point);
                 }
                 Kalman.Predict();
                 lastPoint = point;
             }
         }
References Juniper.Mathematics.KalmanMotionFilter.componentCount, Juniper.Mathematics.KalmanMotionFilter.ComponentCount, Juniper.Mathematics.KalmanMotionFilter.Dimension, Juniper.Mathematics.KalmanMotionFilter.GetProcessNoise(), Juniper.Mathematics.KalmanMotionFilter.Kalman, Juniper.Mathematics.KalmanMotionFilter.lastPoint, Juniper.Mathematics.KalmanMotionFilter.MakePositionMeasurementMatrix(), Juniper.Mathematics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Mathematics.KalmanMotionFilter.measurementNoise, Juniper.Mathematics.KalmanMotionFilter.mNoise, Juniper.Mathematics.KalmanMotionFilter.processNoiseExponent, Juniper.Mathematics.KalmanMotionFilter.processNoiseScale, Juniper.Mathematics.KalmanMotionFilter.procNoiseE, Juniper.Mathematics.KalmanMotionFilter.procNoiseK, Juniper.Mathematics.KalmanMotionFilter.ToArray(), Juniper.Mathematics.KalmanMotionFilter.ToVector3s(), and Juniper.Mathematics.KalmanMotionFilter.VectorSize.
X()
uint Juniper.Mathematics.KalmanMotionFilter.X (uint i) inline private
Definition at line 45 of file KalmanMotionFilter.cs.
         {
             return i;
         }
Referenced by Juniper.Mathematics.KalmanMotionFilter.ToArray(), Juniper.Mathematics.KalmanMotionFilter.ToVector3(), and Juniper.Mathematics.KalmanMotionFilter.ToVector3s().
Y()
uint Juniper.Mathematics.KalmanMotionFilter.Y (uint i) inline private
Definition at line 50 of file KalmanMotionFilter.cs.
         {
             return i + ComponentCount;
         }
References Juniper.Mathematics.KalmanMotionFilter.ComponentCount.
Referenced by Juniper.Mathematics.KalmanMotionFilter.ToArray(), Juniper.Mathematics.KalmanMotionFilter.ToVector3(), and Juniper.Mathematics.KalmanMotionFilter.ToVector3s().
Z()
uint Juniper.Mathematics.KalmanMotionFilter.Z (uint i) inline private
Definition at line 55 of file KalmanMotionFilter.cs.
         {
             return i + (2 * ComponentCount);
         }
References Juniper.Mathematics.KalmanMotionFilter.ComponentCount.
Referenced by Juniper.Mathematics.KalmanMotionFilter.ToArray(), Juniper.Mathematics.KalmanMotionFilter.ToVector3(), and Juniper.Mathematics.KalmanMotionFilter.ToVector3s().
Member Data Documentation
componentCount
uint Juniper.Mathematics.KalmanMotionFilter.componentCount = 2
Definition at line 15 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
lastPoint
Vector3? Juniper.Mathematics.KalmanMotionFilter.lastPoint private
Definition at line 91 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
measurementNoise
float Juniper.Mathematics.KalmanMotionFilter.measurementNoise = 10
Definition at line 22 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
mNoise
float Juniper.Mathematics.KalmanMotionFilter.mNoise private
Definition at line 23 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
processNoiseExponent
float Juniper.Mathematics.KalmanMotionFilter.processNoiseExponent = 1
Definition at line 29 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
processNoiseScale
uint Juniper.Mathematics.KalmanMotionFilter.processNoiseScale = 100
Definition at line 25 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
procNoiseE
float Juniper.Mathematics.KalmanMotionFilter.procNoiseE private
Definition at line 31 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
procNoiseK
uint Juniper.Mathematics.KalmanMotionFilter.procNoiseK private
Definition at line 26 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
VectorSize
const uint Juniper.Mathematics.KalmanMotionFilter.VectorSize = 3 private
Definition at line 33 of file KalmanMotionFilter.cs.
Referenced by Juniper.Mathematics.KalmanMotionFilter.GetProcessNoise(), Juniper.Mathematics.KalmanMotionFilter.MakePositionMeasurementMatrix(), and Juniper.Mathematics.KalmanMotionFilter.UpdateState().
Property Documentation
ComponentCount
uint Juniper.Mathematics.KalmanMotionFilter.ComponentCount get set private
Definition at line 18 of file KalmanMotionFilter.cs.
         {
             get; set;
         }
Referenced by Juniper.Mathematics.KalmanMotionFilter.GetProcessNoise(), Juniper.Mathematics.KalmanMotionFilter.MakePositionMeasurementMatrix(), Juniper.Mathematics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Mathematics.KalmanMotionFilter.ToVector3s(), Juniper.Mathematics.KalmanMotionFilter.UpdateState(), Juniper.Mathematics.KalmanMotionFilter.Y(), and Juniper.Mathematics.KalmanMotionFilter.Z().
Dimension
uint Juniper.Mathematics.KalmanMotionFilter.Dimension get set private
Definition at line 36 of file KalmanMotionFilter.cs.
         {
             get; set;
         }
Referenced by Juniper.Mathematics.KalmanMotionFilter.GetProcessNoise(), Juniper.Mathematics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Mathematics.KalmanMotionFilter.ToArray(), and Juniper.Mathematics.KalmanMotionFilter.UpdateState().
Kalman
DiscreteKalmanFilter<Vector3[], Vector3> Juniper.Mathematics.KalmanMotionFilter.Kalman get set private
Definition at line 41 of file KalmanMotionFilter.cs.
         {
             get; set;
         }
Referenced by Juniper.Mathematics.KalmanMotionFilter.UpdateState().
Position
override Vector3??? Juniper.Mathematics.KalmanMotionFilter.Position get
Definition at line 70 of file KalmanMotionFilter.cs.
         {
             get
             {
                 return Kalman?.State[0] ?? Vector3.zero;
             }
         }
PredictedPosition
override Vector3? Juniper.Mathematics.KalmanMotionFilter.PredictedPosition get
Definition at line 61 of file KalmanMotionFilter.cs.
         {
             get
             {
                 Kalman?.Predict();
                 return Position;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Statistics/KalmanMotionFilter.cs