Juniper: Juniper.JuniperSystem Class Reference
Juniper.JuniperSystem Class Reference
Public Member Functions
void Install (bool reset)
Install, with or without a full reset.
void Uninstall ()
Remove platform-specific features from the object.
void Awake ()
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
void Update ()
virtual void Reinstall ()
Reinstall the object with a full reset.
Static Public Member Functions
static void EnsureFactory ()
static Task OnMainThreadAsync (Action act)
static void OnMainThread (Action act)
static Task< T > OnMainThreadAsync< T > (Func< T > act)
static T OnMainThread< T > (Func< T > act)
static void UninstallSystem ()
static void InstallSystem (bool reset)
static void LogError (Task erroredTask)
Public Attributes
PlatformType m_CurrentPlatform
SystemTypes m_System
DisplayTypes m_DisplayType
DisplayTypes m_SupportedDisplayType
AugmentedRealityTypes m_ARMode
AugmentedRealityTypes m_SupportedARMode
Options m_Option
Static Public Attributes
static bool IsMainThreadReady => mainThread != null
static PlatformType CurrentPlatform => ProjectConfiguration.Platform
static SystemTypes System => Platform.GetSystem(CurrentPlatform)
static DisplayTypes SupportedDisplayType => Platform.GetDisplayType(CurrentPlatform)
static AugmentedRealityTypes SupportedARMode => Platform.GetARType(CurrentPlatform)
static Options Option => Platform.GetOption(CurrentPlatform)
Static Private Member Functions
static List< IInstallable > GetInstallables ()
Static Private Attributes
static TaskScheduler mainThreadScheduler
static TaskFactory mainThread
static bool IsOnMainThread => Task.Factory.Scheduler == mainThreadScheduler
Detailed Description
Definition at line 22 of file JuniperSystem.cs.
Member Function Documentation
Awake()
void Juniper.JuniperSystem.Awake () inline
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
Definition at line 201 of file JuniperSystem.cs.
         {
             EnsureFactory();
             if (Find.Any(out MasterSceneController scenes)
                 && scenes.gameObject.scene != gameObject.scene)
             {
                 gameObject.Destroy();
             }
             else
             {
                 Install(false);
             }
         }
References Juniper.JuniperSystem.EnsureFactory(), and Juniper.JuniperSystem.Install().
EnsureFactory()
static void Juniper.JuniperSystem.EnsureFactory () inline static
Definition at line 27 of file JuniperSystem.cs.
         {
             if (mainThread == null)
             {
                 mainThreadScheduler = TaskScheduler.FromCurrentSynchronizationContext();
                 mainThread = new TaskFactory(mainThreadScheduler);
             }
         }
References Juniper.JuniperSystem.mainThread, and Juniper.JuniperSystem.mainThreadScheduler.
Referenced by Juniper.JuniperSystem.Awake(), Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdateInternal(), and Juniper.JuniperSystem.Update().
GetInstallables()
static List<IInstallable> Juniper.JuniperSystem.GetInstallables () inline static private
Definition at line 83 of file JuniperSystem.cs.
         {
             return Find.All<IInstallable>().ToList();
         }
Referenced by Juniper.JuniperSystem.InstallSystem(), and Juniper.JuniperSystem.UninstallSystem().
Install()
void Juniper.JuniperSystem.Install (bool reset) inline
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IO.IInstallable.
Definition at line 108 of file JuniperSystem.cs.
         {
             DisplayManager.SetupMainCamera();
             this.Ensure<EventSystem>();
             this.Ensure<UnifiedInputModule>();
             this.Ensure<AnchorStore>();
             this.Ensure<InteractionAudio>();
             this.Ensure<MasterSceneController>();
             this.Ensure<PermissionHandler>();
         }
References Juniper.Display.AbstractDisplayManager.SetupMainCamera().
Referenced by Juniper.JuniperSystem.Awake(), and Juniper.JuniperSystem.Reinstall().
InstallSystem()
static void Juniper.JuniperSystem.InstallSystem (bool reset) inline static
Definition at line 93 of file JuniperSystem.cs.
         {
             var notInstalled = Installable.InstallAll(GetInstallables, reset);
             if (notInstalled.Count > 0)
             {
                 var names = from module in notInstalled
                             let type = module.Key.GetType()
                             let errorType = module.Value.GetType()
                             let errorMessage = module.Value.Message
                             select $"\n\t[{type.Name}] {errorType.Name}: {errorMessage}";
                 var nameList = string.Join("", names);
                 Debug.LogError("Juniper: ERROR: components were not installed correctly." + nameList);
             }
         }
References Juniper.XR.Debug, Juniper.JuniperSystem.GetInstallables(), and Juniper.IO.Installable.InstallAll().
LogError()
static void Juniper.JuniperSystem.LogError (Task erroredTask) inline static
Definition at line 121 of file JuniperSystem.cs.
         {
             var stack = new Stack<Exception>(erroredTask.Exception.InnerExceptions);
             stack.Push(erroredTask.Exception);
             while (stack.Count > 0)
             {
                 var here = stack.Pop();
                 if (here != null)
                 {
                     Debug.LogException(here);
                     stack.Push(here.InnerException);
                 }
             }
         }
References Juniper.XR.Debug.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
OnMainThread()
static void Juniper.JuniperSystem.OnMainThread (Action act) inline static
Definition at line 57 of file JuniperSystem.cs.
         {
             OnMainThreadAsync(act).Wait();
         }
References Juniper.JuniperSystem.OnMainThreadAsync().
Referenced by Juniper.Imaging.UnityTexture2DCodec.Deserialize(), UnityEngine.ComponentExt.GetZoneName(), Juniper.Sound.AbstractInteractionAudio.PauseZone(), Juniper.Sound.AbstractInteractionAudio.PlayZone(), Juniper.AbstractStateController.Stopper(), and Juniper.Sound.AbstractInteractionAudio.StopZone().
OnMainThread< T >()
static T Juniper.JuniperSystem.OnMainThread< T > (Func< T > act) inline static
Definition at line 78 of file JuniperSystem.cs.
         {
             return OnMainThreadAsync(act).Result;
         }
References Juniper.JuniperSystem.OnMainThreadAsync().
OnMainThreadAsync()
static Task Juniper.JuniperSystem.OnMainThreadAsync (Action act) inline static
Definition at line 40 of file JuniperSystem.cs.
         {
             if (mainThread is null)
             {
                 throw new InvalidOperationException("Main thread starter isn't setup correctly");
             }
             else if (IsOnMainThread)
             {
                 act();
                 return Task.CompletedTask;
             }
             else
             {
                 return mainThread.StartNew(act);
             }
         }
References Juniper.JuniperSystem.IsOnMainThread, and Juniper.JuniperSystem.mainThread.
Referenced by UnityEngine.MonoBehaviourExt.ActivateAsync(), UnityEngine.ComponentExt.ActivateAsync(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap(), UnityEngine.ComponentExt.DeactivateAsync(), Juniper.Sound.AbstractInteractionAudio.EnableDopplerAsync(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetPhotosphere(), UnityEngine.ComponentExt.IsActivatedAsync(), Juniper.JuniperSystem.OnMainThread(), Juniper.JuniperSystem.OnMainThread< T >(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), UnityEngine.ComponentExt.SetActiveAsync(), and Juniper.Imaging.PhotosphereJig.UpdatePhotosphere().
OnMainThreadAsync< T >()
static Task<T> Juniper.JuniperSystem.OnMainThreadAsync< T > (Func< T > act) inline static
Definition at line 62 of file JuniperSystem.cs.
         {
             if (mainThread is null)
             {
                 throw new InvalidOperationException("Main thread starter isn't setup correctly");
             }
             else if (IsOnMainThread)
             {
                 return Task.FromResult(act());
             }
             else
             {
                 return mainThread.StartNew(act);
             }
         }
References Juniper.JuniperSystem.IsOnMainThread, and Juniper.JuniperSystem.mainThread.
Reinstall()
virtual void Juniper.JuniperSystem.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IO.IInstallable.
Definition at line 221 of file JuniperSystem.cs.
         {
             Install(true);
         }
References Juniper.JuniperSystem.Install().
Uninstall()
void Juniper.JuniperSystem.Uninstall () inline
Remove platform-specific features from the object.
Implements Juniper.IO.IInstallable.
Definition at line 119 of file JuniperSystem.cs.
 { }
UninstallSystem()
static void Juniper.JuniperSystem.UninstallSystem () inline static
Definition at line 88 of file JuniperSystem.cs.
         {
             Installable.UninstallAll(JuniperSystem.GetInstallables);
         }
References Juniper.JuniperSystem.GetInstallables(), and Juniper.IO.Installable.UninstallAll().
Update()
void Juniper.JuniperSystem.Update () inline
Definition at line 216 of file JuniperSystem.cs.
         {
             EnsureFactory();
         }
References Juniper.JuniperSystem.EnsureFactory().
Member Data Documentation
CurrentPlatform
PlatformType Juniper.JuniperSystem.CurrentPlatform => ProjectConfiguration.Platform static
Definition at line 136 of file JuniperSystem.cs.
Referenced by Juniper.Widgets.PlatformName.Awake(), Juniper.Widgets.FollowPlatformSettings.Awake(), Juniper.Display.AbstractDisplayManager.ChangeXRDevice(), and Juniper.Display.AbstractDisplayManager.Update().
IsMainThreadReady
bool Juniper.JuniperSystem.IsMainThreadReady => mainThread != null static
Definition at line 38 of file JuniperSystem.cs.
Referenced by Juniper.Unity.Editor.JuniperEditorWindow.OnBackgroundUpdateInternal(), and Juniper.Unity.Editor.JuniperEditorWindow.OnEditorUpdateInternal().
IsOnMainThread
bool Juniper.JuniperSystem.IsOnMainThread => Task.Factory.Scheduler == mainThreadScheduler static private
Definition at line 36 of file JuniperSystem.cs.
Referenced by Juniper.JuniperSystem.OnMainThreadAsync(), and Juniper.JuniperSystem.OnMainThreadAsync< T >().
m_ARMode
AugmentedRealityTypes Juniper.JuniperSystem.m_ARMode
Definition at line 159 of file JuniperSystem.cs.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Display.AbstractPassthroughDisplayManager.OnARModeChange(), Juniper.Display.AbstractDisplayManager.OnARModeChange(), and Juniper.Display.AbstractDisplayManager.Update().
m_CurrentPlatform
PlatformType Juniper.JuniperSystem.m_CurrentPlatform
Definition at line 147 of file JuniperSystem.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Update().
m_DisplayType
DisplayTypes Juniper.JuniperSystem.m_DisplayType
Definition at line 153 of file JuniperSystem.cs.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.DisableDisplay(), Juniper.Display.AbstractDisplayManager.OnDisplayTypeChange(), Juniper.Display.AbstractDisplayManager.StopXRDisplay(), and Juniper.Display.AbstractDisplayManager.Update().
m_Option
Options Juniper.JuniperSystem.m_Option
Definition at line 165 of file JuniperSystem.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), and Juniper.Display.AbstractDisplayManager.Update().
m_SupportedARMode
AugmentedRealityTypes Juniper.JuniperSystem.m_SupportedARMode
Definition at line 162 of file JuniperSystem.cs.
Referenced by Juniper.Display.AbstractDisplayManager.StartAR().
m_SupportedDisplayType
DisplayTypes Juniper.JuniperSystem.m_SupportedDisplayType
Definition at line 156 of file JuniperSystem.cs.
Referenced by Juniper.Display.AbstractDisplayManager.StartXRDisplay().
m_System
SystemTypes Juniper.JuniperSystem.m_System
Definition at line 150 of file JuniperSystem.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), and Juniper.Display.AbstractDisplayManager.Update().
mainThread
TaskFactory Juniper.JuniperSystem.mainThread static private
Definition at line 25 of file JuniperSystem.cs.
Referenced by Juniper.JuniperSystem.EnsureFactory(), Juniper.JuniperSystem.OnMainThreadAsync(), and Juniper.JuniperSystem.OnMainThreadAsync< T >().
mainThreadScheduler
TaskScheduler Juniper.JuniperSystem.mainThreadScheduler static private
Definition at line 24 of file JuniperSystem.cs.
Referenced by Juniper.JuniperSystem.EnsureFactory().
Option
Options Juniper.JuniperSystem.Option => Platform.GetOption(CurrentPlatform) static
Definition at line 144 of file JuniperSystem.cs.
SupportedARMode
AugmentedRealityTypes Juniper.JuniperSystem.SupportedARMode => Platform.GetARType(CurrentPlatform) static
Definition at line 142 of file JuniperSystem.cs.
SupportedDisplayType
DisplayTypes Juniper.JuniperSystem.SupportedDisplayType => Platform.GetDisplayType(CurrentPlatform) static
Definition at line 140 of file JuniperSystem.cs.
System
SystemTypes Juniper.JuniperSystem.System => Platform.GetSystem(CurrentPlatform) static
Definition at line 138 of file JuniperSystem.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/JuniperSystem.cs