Juniper: Hjg.Pngcs.PngIDatChunkInputStream Class Reference
Hjg.Pngcs.PngIDatChunkInputStream Class Reference
Reads IDAT chunks
Classes
class IdatChunkInfo
Public Member Functions
override void Write (byte[] buffer, int offset, int count)
override void SetLength (long value)
override long Seek (long offset, SeekOrigin origin)
override void Flush ()
PngIDatChunkInputStream (Stream iStream, int lenFirstChunk, long offset_0)
Constructor must be called just after reading length and id of first IDAT chunk
void ForceChunkEnd ()
sometimes last row read does not fully consumes the chunk here we read the reamaing dummy bytes
override int Read (byte[] b, int off, int len_0)
This can return less than len, but never 0 Returns -1 nothing more to read, -2 if "pseudo file" ended prematurely. That is our error.
int Read (byte[] b)
override int ReadByte ()
int GetLenLastChunk ()
byte [] GetIdLastChunk ()
long GetOffset ()
bool IsEnded ()
Public Attributes
override long Length => 0
override bool CanWrite => false
override bool CanRead => true
override bool CanSeek => false
IList< IdatChunkInfo > foundChunksInfo
Protected Member Functions
override void Dispose (bool disposing)
Properties
override long Position [get, set]
Private Member Functions
void EndChunkGoForNext ()
internal void DisableCrcCheck ()
Disables CRC checking. This can make reading faster
Private Attributes
readonly Stream inputStream
readonly CRC32 crcEngine
bool checkCrc
int lenLastChunk
readonly byte [] idLastChunk
int toReadThisChunk
bool ended
long offset
Detailed Description
Reads IDAT chunks
Definition at line 13 of file PngIDatChunkInputStream.cs.
Constructor & Destructor Documentation
PngIDatChunkInputStream()
Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream (Stream iStream, int lenFirstChunk, long offset_0) inline
Constructor must be called just after reading length and id of first IDAT chunk
Definition at line 71 of file PngIDatChunkInputStream.cs.
         {
             idLastChunk = new byte[4];
             toReadThisChunk = 0;
             ended = false;
             foundChunksInfo = new List<IdatChunkInfo>();
             offset = offset_0;
             checkCrc = true;
             inputStream = iStream;
             crcEngine = new CRC32();
             lenLastChunk = lenFirstChunk;
             toReadThisChunk = lenFirstChunk;
             // we know it's a IDAT
             Array.Copy(Chunks.ChunkHelper.b_IDAT, 0, idLastChunk, 0, 4);
             crcEngine.Update(idLastChunk, 0, 4);
             foundChunksInfo.Add(new IdatChunkInfo(lenLastChunk, offset_0 - 8));
             // PngHelper.logdebug("IDAT Initial fragment: len=" + lenLastChunk);
             if (lenLastChunk == 0)
             {
                 EndChunkGoForNext(); // rare, but...
             }
         }
References Hjg.Pngcs.PngIDatChunkInputStream.checkCrc, Hjg.Pngcs.PngIDatChunkInputStream.crcEngine, Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ended, Hjg.Pngcs.PngIDatChunkInputStream.foundChunksInfo, Hjg.Pngcs.PngIDatChunkInputStream.idLastChunk, Hjg.Pngcs.PngIDatChunkInputStream.inputStream, Hjg.Pngcs.PngIDatChunkInputStream.lenLastChunk, Hjg.Pngcs.PngIDatChunkInputStream.offset, Hjg.Pngcs.PngIDatChunkInputStream.toReadThisChunk, and Hjg.Pngcs.Zlib.CRC32.Update().
Member Function Documentation
DisableCrcCheck()
internal void Hjg.Pngcs.PngIDatChunkInputStream.DisableCrcCheck () inline private
Disables CRC checking. This can make reading faster
Definition at line 249 of file PngIDatChunkInputStream.cs.
         {
             checkCrc = false;
         }
References Hjg.Pngcs.PngIDatChunkInputStream.checkCrc.
Referenced by Hjg.Pngcs.PngReader.ReadSkippingAllRows().
Dispose()
override void Hjg.Pngcs.PngIDatChunkInputStream.Dispose (bool disposing) inline protected
Definition at line 94 of file PngIDatChunkInputStream.cs.
         {
             if (disposing)
             {
                 inputStream.Dispose();
             }
             base.Dispose(disposing);
         }
References Hjg.Pngcs.PngIDatChunkInputStream.inputStream.
Referenced by Hjg.Pngcs.PngReader.Dispose().
EndChunkGoForNext()
void Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext () inline private
Definition at line 104 of file PngIDatChunkInputStream.cs.
         {
             // Called after readging the last byte of chunk
             // Checks CRC, and read ID from next CHUNK
             // Those values are left in idLastChunk / lenLastChunk
             // Skips empty IDATS
             do
             {
                 var crc = PngHelperInternal.ReadInt4(inputStream);
                 offset += 4;
                 if (checkCrc)
                 {
                     var crccalc = (int)crcEngine.GetValue();
                     if (lenLastChunk > 0 && crc != crccalc)
                     {
                         throw new PngjBadCrcException("error reading idat; offset: " + offset.ToString(CultureInfo.CurrentCulture));
                     }
                     crcEngine.Reset();
                 }
                 lenLastChunk = PngHelperInternal.ReadInt4(inputStream);
                 if (lenLastChunk < 0)
                 {
                     throw new PngjInputException("invalid len for chunk: " + lenLastChunk.ToString(CultureInfo.CurrentCulture));
                 }
                 toReadThisChunk = lenLastChunk;
                 PngHelperInternal.ReadBytes(inputStream, idLastChunk, 0, 4);
                 offset += 8;
                 ended = !PngCsUtils.arraysEqual4(idLastChunk, Chunks.ChunkHelper.b_IDAT);
                 if (!ended)
                 {
                     foundChunksInfo.Add(new IdatChunkInfo(lenLastChunk, offset - 8));
                     if (checkCrc)
                     {
                         crcEngine.Update(idLastChunk, 0, 4);
                     }
                 }
             } while (lenLastChunk == 0 && !ended);
             // rarely condition is true (empty IDAT ??)
         }
References Hjg.Pngcs.PngCsUtils.arraysEqual4(), Hjg.Pngcs.PngIDatChunkInputStream.checkCrc, Hjg.Pngcs.PngIDatChunkInputStream.crcEngine, Hjg.Pngcs.PngIDatChunkInputStream.ended, Hjg.Pngcs.PngIDatChunkInputStream.foundChunksInfo, Hjg.Pngcs.Zlib.CRC32.GetValue(), Hjg.Pngcs.PngIDatChunkInputStream.idLastChunk, Hjg.Pngcs.PngIDatChunkInputStream.inputStream, Hjg.Pngcs.PngIDatChunkInputStream.lenLastChunk, Hjg.Pngcs.PngIDatChunkInputStream.offset, Hjg.Pngcs.PngHelperInternal.ReadBytes(), Hjg.Pngcs.PngHelperInternal.ReadInt4(), Hjg.Pngcs.Zlib.CRC32.Reset(), Hjg.Pngcs.PngIDatChunkInputStream.toReadThisChunk, and Hjg.Pngcs.Zlib.CRC32.Update().
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
Flush()
override void Hjg.Pngcs.PngIDatChunkInputStream.Flush () inline
Definition at line 50 of file PngIDatChunkInputStream.cs.
         {
         }
ForceChunkEnd()
void Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd () inline
sometimes last row read does not fully consumes the chunk here we read the reamaing dummy bytes
Definition at line 154 of file PngIDatChunkInputStream.cs.
         {
             if (!ended)
             {
                 var dummy = new byte[toReadThisChunk];
                 PngHelperInternal.ReadBytes(inputStream, dummy, 0, toReadThisChunk);
                 if (checkCrc)
                 {
                     crcEngine.Update(dummy, 0, toReadThisChunk);
                 }
                 EndChunkGoForNext();
             }
         }
References Hjg.Pngcs.PngIDatChunkInputStream.checkCrc, Hjg.Pngcs.PngIDatChunkInputStream.crcEngine, Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ended, Hjg.Pngcs.PngIDatChunkInputStream.inputStream, Hjg.Pngcs.PngHelperInternal.ReadBytes(), Hjg.Pngcs.PngIDatChunkInputStream.toReadThisChunk, and Hjg.Pngcs.Zlib.CRC32.Update().
Referenced by Hjg.Pngcs.PngReader.ReadLastChunks().
GetIdLastChunk()
byte [] Hjg.Pngcs.PngIDatChunkInputStream.GetIdLastChunk () inline
Definition at line 231 of file PngIDatChunkInputStream.cs.
         {
             return idLastChunk;
         }
References Hjg.Pngcs.PngIDatChunkInputStream.idLastChunk.
Referenced by Hjg.Pngcs.PngReader.ReadLastChunks().
GetLenLastChunk()
int Hjg.Pngcs.PngIDatChunkInputStream.GetLenLastChunk () inline
Definition at line 226 of file PngIDatChunkInputStream.cs.
         {
             return lenLastChunk;
         }
References Hjg.Pngcs.PngIDatChunkInputStream.lenLastChunk.
Referenced by Hjg.Pngcs.PngReader.ReadLastChunks().
GetOffset()
long Hjg.Pngcs.PngIDatChunkInputStream.GetOffset () inline
Definition at line 236 of file PngIDatChunkInputStream.cs.
         {
             return offset;
         }
References Hjg.Pngcs.PngIDatChunkInputStream.offset.
Referenced by Hjg.Pngcs.PngReader.ReadRowRaw(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
IsEnded()
bool Hjg.Pngcs.PngIDatChunkInputStream.IsEnded () inline
Definition at line 241 of file PngIDatChunkInputStream.cs.
         {
             return ended;
         }
References Hjg.Pngcs.PngIDatChunkInputStream.ended.
Referenced by Hjg.Pngcs.PngReader.ReadLastChunks().
Read() [1/2]
override int Hjg.Pngcs.PngIDatChunkInputStream.Read (byte [] b, int off, int len_0) inline
This can return less than len, but never 0 Returns -1 nothing more to read, -2 if "pseudo file" ended prematurely. That is our error.
Definition at line 174 of file PngIDatChunkInputStream.cs.
         {
             if (ended)
             {
                 return -1; // can happen only when raw reading, see Pngreader.readAndSkipsAllRows()
             }
             if (toReadThisChunk == 0)
             {
                 throw new Exception("this should not happen");
             }
             var n = inputStream.Read(b, off, (len_0 >= toReadThisChunk) ? toReadThisChunk : len_0);
             if (n == -1)
             {
                 n = -2;
             }
             if (n > 0)
             {
                 if (checkCrc)
                 {
                     crcEngine.Update(b, off, n);
                 }
                 offset += n;
                 toReadThisChunk -= n;
             }
             if (n >= 0 && toReadThisChunk == 0)
             {
                 // end of chunk: prepare for next
                 EndChunkGoForNext();
             }
             return n;
         }
References Hjg.Pngcs.PngIDatChunkInputStream.checkCrc, Hjg.Pngcs.PngIDatChunkInputStream.crcEngine, Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ended, Hjg.Pngcs.PngIDatChunkInputStream.inputStream, Hjg.Pngcs.PngIDatChunkInputStream.offset, Hjg.Pngcs.PngIDatChunkInputStream.toReadThisChunk, and Hjg.Pngcs.Zlib.CRC32.Update().
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.Read(), Hjg.Pngcs.PngIDatChunkInputStream.ReadByte(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
Read() [2/2]
int Hjg.Pngcs.PngIDatChunkInputStream.Read (byte [] b) inline
Definition at line 212 of file PngIDatChunkInputStream.cs.
         {
             return Read(b, 0, b.Length);
         }
References Hjg.Pngcs.PngIDatChunkInputStream.Read().
ReadByte()
override int Hjg.Pngcs.PngIDatChunkInputStream.ReadByte () inline
Definition at line 217 of file PngIDatChunkInputStream.cs.
         {
             // PngHelper.logdebug("read() should go here");
             // inneficient - but this should be used rarely
             var b1 = new byte[1];
             var r = Read(b1, 0, 1);
             return (r < 0) ? -1 : b1[0];
         }
References Hjg.Pngcs.PngIDatChunkInputStream.Read().
Seek()
override long Hjg.Pngcs.PngIDatChunkInputStream.Seek (long offset, SeekOrigin origin) inline
Definition at line 45 of file PngIDatChunkInputStream.cs.
         {
             return -1;
         }
SetLength()
override void Hjg.Pngcs.PngIDatChunkInputStream.SetLength (long value) inline
Definition at line 41 of file PngIDatChunkInputStream.cs.
         {
         }
Write()
override void Hjg.Pngcs.PngIDatChunkInputStream.Write (byte [] buffer, int offset, int count) inline
Definition at line 37 of file PngIDatChunkInputStream.cs.
         {
         }
Member Data Documentation
CanRead
override bool Hjg.Pngcs.PngIDatChunkInputStream.CanRead => true
Definition at line 60 of file PngIDatChunkInputStream.cs.
CanSeek
override bool Hjg.Pngcs.PngIDatChunkInputStream.CanSeek => false
Definition at line 62 of file PngIDatChunkInputStream.cs.
CanWrite
override bool Hjg.Pngcs.PngIDatChunkInputStream.CanWrite => false
Definition at line 58 of file PngIDatChunkInputStream.cs.
checkCrc
bool Hjg.Pngcs.PngIDatChunkInputStream.checkCrc private
Definition at line 17 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.DisableCrcCheck(), Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
crcEngine
readonly CRC32 Hjg.Pngcs.PngIDatChunkInputStream.crcEngine private
Definition at line 16 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
ended
bool Hjg.Pngcs.PngIDatChunkInputStream.ended private
Definition at line 21 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.IsEnded(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
foundChunksInfo
IList<IdatChunkInfo> Hjg.Pngcs.PngIDatChunkInputStream.foundChunksInfo
Definition at line 64 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), and Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream().
idLastChunk
readonly byte [] Hjg.Pngcs.PngIDatChunkInputStream.idLastChunk private
Definition at line 19 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.GetIdLastChunk(), and Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream().
inputStream
readonly Stream Hjg.Pngcs.PngIDatChunkInputStream.inputStream private
Definition at line 15 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.Dispose(), Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
Length
override long Hjg.Pngcs.PngIDatChunkInputStream.Length => 0
Definition at line 56 of file PngIDatChunkInputStream.cs.
lenLastChunk
int Hjg.Pngcs.PngIDatChunkInputStream.lenLastChunk private
Definition at line 18 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.GetLenLastChunk(), and Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream().
offset
long Hjg.Pngcs.PngIDatChunkInputStream.offset private
Definition at line 22 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.GetOffset(), Hjg.Pngcs.PngIDatChunkInputStream.IdatChunkInfo.IdatChunkInfo(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
toReadThisChunk
int Hjg.Pngcs.PngIDatChunkInputStream.toReadThisChunk private
Definition at line 20 of file PngIDatChunkInputStream.cs.
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.PngIDatChunkInputStream(), and Hjg.Pngcs.PngIDatChunkInputStream.Read().
Property Documentation
Position
override long Hjg.Pngcs.PngIDatChunkInputStream.Position get set
Definition at line 54 of file PngIDatChunkInputStream.cs.
 { get; set; }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/PngIDatChunkInputStream.cs