Juniper: Juniper.IO.ICacheSourceLayerExt Class Reference
Juniper.IO.ICacheSourceLayerExt Class Reference
Static Public Member Functions
static Task< Stream > OpenAsync (this ICacheSourceLayer layer, ContentReference fileRef)
static async Task< ResultT > LoadAsync< ResultT > (this ICacheSourceLayer layer, IDeserializer< ResultT > deserializer, ContentReference fileRef, IProgress prog=null)
static bool TryLoad< ResultT > (this ICacheSourceLayer layer, IDeserializer< ResultT > deserializer, ContentReference fileRef, out ResultT value, IProgress prog=null)
static IEnumerable<(ContentReference contentRef, ResultT result)> Get< ResultT, MediaTypeT > (this ICacheSourceLayer source, IFactory< ResultT, MediaTypeT > deserializer)
Retrieve all the content references that can be deserialized by the given deserializer.
static async Task< Dictionary< ContentReference, ResultT > > GetAsync< ResultT, MediaTypeT > (this ICacheSourceLayer source, IFactory< ResultT, MediaTypeT > deserializer, IProgress prog=null)
Detailed Description
Definition at line 10 of file ICacheSourceLayerExt.cs.
Member Function Documentation
Get< ResultT, MediaTypeT >()
static IEnumerable<(ContentReference contentRef, ResultT result)> Juniper.IO.ICacheSourceLayerExt.Get< ResultT, MediaTypeT > (this ICacheSourceLayer source, IFactory< ResultT, MediaTypeT > deserializer) inline static
Retrieve all the content references that can be deserialized by the given deserializer.
Template Parameters
ResultT
MediaTypeT
Parameters
deserializer
Returns
Type Constraints
ResultT : class
MediaTypeT : MediaType
Definition at line 89 of file ICacheSourceLayerExt.cs.
                           : class
             where MediaTypeT : MediaType
         {
             if (source is null)
             {
                 throw new ArgumentNullException(nameof(source));
             }
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             foreach (var contentRef in source.GetContentReferences(deserializer.ContentType))
             {
                 if (source.TryLoad(deserializer, contentRef, out var result))
                 {
                     yield return (contentRef, result);
                 }
             }
         }
GetAsync< ResultT, MediaTypeT >()
static async Task<Dictionary<ContentReference, ResultT> > Juniper.IO.ICacheSourceLayerExt.GetAsync< ResultT, MediaTypeT > (this ICacheSourceLayer source, IFactory< ResultT, MediaTypeT > deserializer, IProgress prog = null) inline static
Type Constraints
ResultT : class
MediaTypeT : MediaType
Definition at line 114 of file ICacheSourceLayerExt.cs.
                           : class
             where MediaTypeT : MediaType
         {
             if (source is null)
             {
                 throw new ArgumentNullException(nameof(source));
             }
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             var items = new Dictionary<ContentReference, ResultT>();
             var refs = source.GetContentReferences(deserializer.ContentType).ToArray();
             foreach (var (itemProg, contentRef) in prog.Zip(refs))
             {
                 var stream = await source
                     .GetStreamAsync(contentRef, itemProg)
                     .ConfigureAwait(false);
                 if (stream is object
                     && deserializer.TryDeserialize(stream, out var value))
                 {
                     items.Add(contentRef, value);
                 }
             }
             return items;
         }
References Juniper.IO.ICacheSourceLayer.GetContentReferences(), and Juniper.IO.ICacheSourceLayer.GetStreamAsync().
LoadAsync< ResultT >()
static async Task<ResultT> Juniper.IO.ICacheSourceLayerExt.LoadAsync< ResultT > (this ICacheSourceLayer layer, IDeserializer< ResultT > deserializer, ContentReference fileRef, IProgress prog = null) inline static
Definition at line 29 of file ICacheSourceLayerExt.cs.
         {
             if (layer is null)
             {
                 throw new ArgumentNullException(nameof(layer));
             }
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             var progs = prog.Split("Read", "Decode");
             using var stream = await layer
                 .GetStreamAsync(fileRef, progs[0])
                 .ConfigureAwait(false);
             using var progStream = new ProgressStream(stream, stream.Length, progs[1], false);
             return deserializer.Deserialize(progStream);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize(), and Juniper.IO.ICacheSourceLayer.GetStreamAsync().
OpenAsync()
static Task<Stream> Juniper.IO.ICacheSourceLayerExt.OpenAsync (this ICacheSourceLayer layer, ContentReference fileRef) inline static
Definition at line 12 of file ICacheSourceLayerExt.cs.
         {
             if (layer is null)
             {
                 throw new ArgumentNullException(nameof(layer));
             }
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             return layer.GetStreamAsync(fileRef, null);
         }
References Juniper.IO.ICacheSourceLayer.GetStreamAsync().
TryLoad< ResultT >()
static bool Juniper.IO.ICacheSourceLayerExt.TryLoad< ResultT > (this ICacheSourceLayer layer, IDeserializer< ResultT > deserializer, ContentReference fileRef, out ResultT value, IProgress prog = null) inline static
Type Constraints
ResultT : class
Definition at line 60 of file ICacheSourceLayerExt.cs.
                           : class
         {
             value = default;
             var task = layer.LoadAsync(deserializer, fileRef, prog);
             Task.WaitAny(task);
             if (task.IsSuccessful())
             {
                 value = task.Result;
             }
             return value != default;
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/ICacheSourceLayerExt.cs