Juniper: Juniper.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, ConfigType, HapticType > Class Template Reference
Juniper.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, ConfigType, HapticType > Class Template Reference abstract
A ScreenDevice is a AbstractPointerDevice<ButtonIDType, ConfigType> that has its primary pointer interactions happening in screen space.
Public Member Functions
virtual void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
void Start ()
virtual void Install (bool reset)
Install, with or without a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void OnProbeFound ()
Vector2 ScreenFromWorld (Vector3 worldPoint)
Vector2 ScreenFromViewport (Vector2 viewportPoint)
Vector2 ViewportFromWorld (Vector3 worldPoint)
Vector2 ViewportFromScreen (Vector2 screenPoint)
Vector3 WorldFromScreen (Vector2 screenPoint)
Vector3 WorldFromViewport (Vector2 viewportPoint)
virtual void Update ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
virtual void PlayInteraction (Interaction action)
virtual void Process (JuniperPointerEventData evtData, float pixelDragThresholdSquared, List< KeyCode > keyPresses, bool paused)
virtual bool IsButtonPressed (KeyCode key)
virtual bool IsButtonPressed (VirtualTouchPadButtons button)
virtual bool IsButtonPressed (VirtualTriggerButton button)
abstract bool IsButtonPressed (ButtonIDType button)
Implementers should return true while the button is depressed.
virtual bool IsButtonUp (KeyCode key)
virtual bool IsButtonUp (VirtualTouchPadButtons button)
virtual bool IsButtonUp (VirtualTriggerButton button)
abstract bool IsButtonUp (ButtonIDType button)
Implementers should return true when the button is first released.
virtual bool IsButtonDown (KeyCode key)
virtual bool IsButtonDown (VirtualTouchPadButtons button)
virtual bool IsButtonDown (VirtualTriggerButton button)
abstract bool IsButtonDown (ButtonIDType button)
Implementers should return true when a button is first depressed.
Public Attributes
bool Connected
bool enableLaserPointer = false
bool showProbe = true
AbstractMotionFilter motionFilter
Protected Member Functions
JuniperPointerEventData Clone (int pointerDataID, JuniperPointerEventData evtData)
virtual IEventSystemHandler ProcessButtons (JuniperPointerEventData evtData, float pixelDragThresholdSquared, List< KeyCode > keyPresses)
virtual void InternalUpdate ()
Protected Attributes
readonly ButtonMapper< ButtonIDType > nativeButtons = new ButtonMapper<ButtonIDType>()
Vector3 pointerOffset
Avatar stage
Static Protected Attributes
static readonly Vector2 VIEWPORT_MIDPOINT
static readonly ConfigType PointerConfig
Properties
virtual Vector3 CameraPositionOffset [get]
virtual Quaternion CameraRotationOffset [get]
Type ButtonType [get]
virtual bool ProcessInUpdate [get]
int PointerDataID [get]
float MinimumPointerDistance [get]
The minimum distance from the camera at which to place the pointer.
float MaximumPointerDistance [get]
Material LaserPointerNormalMaterial [get, set]
Material LaserPointerEnabledMaterial [get, set]
Material LaserPointerDisabledMaterial [get, set]
int Layer [get, set]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
abstract bool IsConnected [get]
bool IsEnabled [get]
bool IsDisabled [get]
Returns true when the device is supposed to be disabled.
PhysicsRaycaster? Raycaster [get]
virtual bool AnyButtonPressed [get]
IProbe Probe [get, private set]
The cursor probe that shows the physical location of the current selection.
string ProbeName [get]
Vector3 Origin [get]
Vector3 LastOrigin [get, private set]
Vector3 OriginDelta [get]
abstract Vector3 WorldPoint [get]
Vector3 LastWorldPoint [get, private set]
Vector3 WorldDelta [get]
Vector3 SmoothedWorldPoint [get]
The target at and through which the pointer rays fire.
Vector3 LastSmoothedWorldPoint [get, private set]
Vector3 SmoothedWorldPointDelta [get]
Vector3 Direction [get]
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
Vector3 LastDirection [get]
Vector3 CursorPosition [get]
Vector2 ScreenPoint [get]
Vector2 LastScreenPoint [get]
Vector2 ScreenDelta [get]
Vector2 ViewportPoint [get]
Vector2 LastViewportPoint [get]
Vector2 ViewportDelta [get]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
UnifiedInputModule InputModule [get]
virtual bool IsDragging [get]
AbstractHapticDevice Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
Transform transform [get]
bool isActiveAndEnabled [get]
Detailed Description
A ScreenDevice is a AbstractPointerDevice<ButtonIDType, ConfigType> that has its primary pointer interactions happening in screen space.
Type Constraints
ButtonIDType : struct
ConfigType : AbstractPointerConfiguration<ButtonIDType>
ConfigType : new()
HapticType : AbstractHapticDevice
Definition at line 10 of file AbstractScreenDevice.cs.
Member Function Documentation
Awake()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Awake () inline virtual inherited
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 166 of file AbstractPointerDevice.cs.
         {
             Install(false);
             Find.Any(out input);
             Find.Any(out stage);
             Find.Any(out interaction);
             pointerOffset = MinimumPointerDistance * Vector3.forward;
             Haptics = this.Ensure<HapticType>();
             nativeButtons.ButtonDownNeeded += IsButtonDown;
             nativeButtons.ButtonUpNeeded += IsButtonUp;
             nativeButtons.ButtonPressedNeeded += IsButtonPressed;
             nativeButtons.ClonedPointerEventNeeded += Clone;
             nativeButtons.InteractionNeeded += PlayInteraction;
         }
Clone()
JuniperPointerEventData Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Clone (int pointerDataID, JuniperPointerEventData evtData) inline protected inherited
Definition at line 563 of file AbstractPointerDevice.cs.
         {
             if (InputModule != null)
             {
                 return InputModule.Clone(pointerDataID, evtData);
             }
             else
             {
                 return null;
             }
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< InteractionSourceHandedness, WindowsMRButtons, WindowsMRMotionControllerConfiguration, HapticType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake().
Install()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Install (bool reset) inline virtual inherited
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IO.IInstallable.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 190 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Install(nativeButtons, gameObject, reset);
             OnProbeFound();
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Reinstall().
InternalUpdate()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.InternalUpdate () inline protected virtual inherited
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >, and Juniper.Input.Pointers.NetworkPointer.
Definition at line 646 of file AbstractPointerDevice.cs.
         {
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
IsButtonDown() [1/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonDown (KeyCode key) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 641 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonDown(key);
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake().
IsButtonDown() [2/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonDown (VirtualTouchPadButtons button) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 655 of file AbstractPointerDevice.cs.
         {
             return false;
         }
IsButtonDown() [3/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonDown (VirtualTriggerButton button) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 670 of file AbstractPointerDevice.cs.
         {
             return false;
         }
IsButtonDown() [4/4]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonDown (ButtonIDType button) pure virtual inherited
Implementers should return true when a button is first depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonPressed() [1/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonPressed (KeyCode key) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 631 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonPressed(key);
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake().
IsButtonPressed() [2/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonPressed (VirtualTouchPadButtons button) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 650 of file AbstractPointerDevice.cs.
         {
             return false;
         }
IsButtonPressed() [3/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonPressed (VirtualTriggerButton button) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 665 of file AbstractPointerDevice.cs.
         {
             return false;
         }
IsButtonPressed() [4/4]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonPressed (ButtonIDType button) pure virtual inherited
Implementers should return true while the button is depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonUp() [1/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonUp (KeyCode key) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 636 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonUp(key);
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake().
IsButtonUp() [2/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonUp (VirtualTouchPadButtons button) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 660 of file AbstractPointerDevice.cs.
         {
             return false;
         }
IsButtonUp() [3/4]
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonUp (VirtualTriggerButton button) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 675 of file AbstractPointerDevice.cs.
         {
             return false;
         }
IsButtonUp() [4/4]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsButtonUp (ButtonIDType button) pure virtual inherited
Implementers should return true when the button is first released.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
OnProbeFound()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.OnProbeFound () inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 223 of file AbstractPointerDevice.cs.
         {
             if (Probe == null)
             {
                 Probe = Pointers.Probe.Ensure(transform, ProbeName);
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Install().
PlayInteraction()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.PlayInteraction (Interaction action) inline virtual inherited
Definition at line 538 of file AbstractPointerDevice.cs.
         {
             if (interaction != null
                 && (Time.unscaledTime > finishTime
                     || action != lastAction))
             {
                 lastAction = action;
                 finishTime = Time.unscaledTime + interaction.PlayAction(action, Probe.Cursor, Haptics, false);
             }
             if(action == Interaction.Entered)
             {
                 curLaserPointerMaterial = LaserPointerEnabledMaterial;
             }
             else if(action == Interaction.EnteredDisabled)
             {
                 curLaserPointerMaterial = LaserPointerDisabledMaterial;
             }
             else if(action == Interaction.Exited)
             {
                 curLaserPointerMaterial = LaserPointerNormalMaterial;
             }
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< InteractionSourceHandedness, WindowsMRButtons, WindowsMRMotionControllerConfiguration, HapticType >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.TestEnterExit().
Process()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Process (JuniperPointerEventData evtData, float pixelDragThresholdSquared, List< KeyCode > keyPresses, bool paused) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 575 of file AbstractPointerDevice.cs.
         {
             if (!paused)
             {
                 if (!IsDragging)
                 {
                     TestEnterExit(evtData);
                 }
                 EventTarget = ProcessButtons(evtData, pixelDragThresholdSquared, keyPresses);
                 if (evtData.clickCount == -1)
                 {
                     evtData.clickCount = 0;
                 }
             }
             LastWorldPoint = evtData.pointerCurrentRaycast.worldPosition;
             LastSmoothedWorldPoint = SmoothedWorldPoint;
             LastOrigin = Origin;
             Probe?.SetCursor(
                 evtData.pointerCurrentRaycast.gameObject != null,
                 AnyButtonPressed,
                 LastWorldPoint,
                 evtData.pointerCurrentRaycast.worldNormal);
         }
ProcessButtons()
virtual IEventSystemHandler Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ProcessButtons (JuniperPointerEventData evtData, float pixelDragThresholdSquared, List< KeyCode > keyPresses) inline protected virtual inherited
Reimplemented in Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticType >.
Definition at line 603 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.Process(evtData, pixelDragThresholdSquared, keyPresses);
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
Reinstall()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Reinstall () inline virtual inherited
Reinstall the object with a full reset.
Implements Juniper.IO.IInstallable.
Definition at line 201 of file AbstractPointerDevice.cs.
         {
             Install(true);
         }
ScreenFromViewport()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ScreenFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 411 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToScreenPoint(viewportPoint);
         }
ScreenFromWorld()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ScreenFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 405 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToScreenPoint(worldPoint);
         }
Start()
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Start () inline inherited
Definition at line 185 of file AbstractPointerDevice.cs.
         {
             InputModule.AddPointer(this);
         }
Uninstall()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Uninstall () inline virtual inherited
Remove platform-specific features from the object.
Implements Juniper.IO.IInstallable.
Definition at line 196 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Uninstall(gameObject);
         }
Update()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Update () inline virtual inherited
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Definition at line 452 of file AbstractPointerDevice.cs.
         {
             if (motionFilter != lastMotionFilter)
             {
 #if UNITY_EDITOR
                 parentMotionFilter = motionFilter;
 #endif
                 if (motionFilter != null)
                 {
                     motionFilter = Instantiate(motionFilter);
                 }
                 lastMotionFilter = motionFilter;
             }
 #if UNITY_EDITOR
             if (motionFilter != null)
             {
                 motionFilter.Copy(parentMotionFilter);
             }
 #endif
             Connected = IsConnected;
             if (Probe != null)
             {
                 Probe.SetActive(IsEnabled && showProbe);
                 if (curLaserPointerMaterial == null)
                 {
                     curLaserPointerMaterial = LaserPointerNormalMaterial;
                 }
                 if (enableLaserPointer)
                 {
                     Probe.LaserPointerMaterial = curLaserPointerMaterial;
                 }
             }
             if (IsEnabled)
             {
                 if (motionFilter != null)
                 {
                     motionFilter.UpdateState(WorldPoint);
                 }
                 InternalUpdate();
                 if (Probe != null)
                 {
                     Probe?.AlignProbe(Direction, transform.up);
                 }
             }
         }
ViewportFromScreen()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ViewportFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 423 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToViewportPoint(screenPoint);
         }
ViewportFromWorld()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ViewportFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 417 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToViewportPoint(worldPoint);
         }
WorldFromScreen()
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.WorldFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 429 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToWorldPoint((Vector3)screenPoint + pointerOffset);
         }
WorldFromViewport()
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.WorldFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 435 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToWorldPoint((Vector3)viewportPoint + pointerOffset);
         }
Member Data Documentation
Connected
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Connected inherited
Definition at line 41 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
enableLaserPointer
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.enableLaserPointer = false inherited
Definition at line 80 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
motionFilter
AbstractMotionFilter Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.motionFilter inherited
Definition at line 446 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, NoHaptics >.MakeMotionController< T >(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
nativeButtons
readonly ButtonMapper<ButtonIDType> Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.nativeButtons = new ButtonMapper<ButtonIDType>() protected inherited
Definition at line 38 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Install(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.IsButtonDown(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.IsButtonPressed(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.IsButtonUp(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.ProcessButtons().
PointerConfig
readonly ConfigType Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.PointerConfig static protected inherited
Initial value:
=
            new ConfigType()
Definition at line 27 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< InteractionSourceHandedness, WindowsMRButtons, WindowsMRMotionControllerConfiguration, HapticType >.Install(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Install(), Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, NoHaptics >.MakeMotionController< T >(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Uninstall().
pointerOffset
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.pointerOffset protected inherited
Definition at line 70 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.WorldFromScreen(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.WorldFromViewport().
showProbe
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.showProbe = true inherited
Definition at line 215 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
stage
Avatar Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.stage protected inherited
Definition at line 515 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake().
VIEWPORT_MIDPOINT
readonly Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.VIEWPORT_MIDPOINT static protected inherited
Initial value:
=
            0.5f * Vector2.one
Definition at line 24 of file AbstractPointerDevice.cs.
Property Documentation
AnyButtonPressed
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.AnyButtonPressed get inherited
Definition at line 152 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return IsButtonPressed(KeyCode.Mouse0)
                     || IsButtonPressed(KeyCode.Mouse1)
                     || IsButtonPressed(KeyCode.Mouse2);
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
ButtonType
Type Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ButtonType get inherited
Definition at line 31 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return typeof(ButtonIDType);
             }
         }
CameraPositionOffset
virtual Vector3 Juniper.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, ConfigType, HapticType >.CameraPositionOffset get
Definition at line 18 of file AbstractScreenDevice.cs.
         {
             get
             {
                 return Vector3.zero;
             }
         }
CameraRotationOffset
virtual Quaternion Juniper.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, ConfigType, HapticType >.CameraRotationOffset get
Definition at line 26 of file AbstractScreenDevice.cs.
         {
             get
             {
                 return Quaternion.identity;
             }
         }
CursorPosition
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.CursorPosition get inherited
Definition at line 333 of file AbstractPointerDevice.cs.
         {
             get
             {
                 if (Probe != null
                     && Probe.Cursor != null)
                 {
                     return Probe.Cursor.position;
                 }
                 else
                 {
                     return Vector3.zero;
                 }
             }
         }
Direction
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Direction get inherited
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
The interaction direction.
Definition at line 317 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (SmoothedWorldPoint - Origin).normalized;
             }
         }
EventTarget
IEventSystemHandler Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.EventTarget get set inherited
Definition at line 114 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
Haptics
AbstractHapticDevice Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Haptics get protected set inherited
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 531 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.PlayInteraction().
InputModule
UnifiedInputModule Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.InputModule get inherited
Definition at line 508 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return input;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Clone(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Start().
isActiveAndEnabled
bool Juniper.Input.Pointers.IPointerDevice.isActiveAndEnabled get inherited
Definition at line 68 of file IPointerDevice.cs.
         {
             get;
         }
IsConnected
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsConnected get inherited
Definition at line 119 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
IsDisabled
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsDisabled get inherited
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 136 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return !IsEnabled;
             }
         }
IsDragging
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsDragging get inherited
Definition at line 518 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return EventTarget != null && nativeButtons.IsDragging;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
IsEnabled
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.IsEnabled get inherited
Definition at line 124 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return isActiveAndEnabled && IsConnected;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
LaserPointerDisabledMaterial
Material Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LaserPointerDisabledMaterial get set inherited
Definition at line 88 of file AbstractPointerDevice.cs.
 { get; set; }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.PlayInteraction().
LaserPointerEnabledMaterial
Material Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LaserPointerEnabledMaterial get set inherited
Definition at line 86 of file AbstractPointerDevice.cs.
 { get; set; }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.PlayInteraction().
LaserPointerNormalMaterial
Material Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LaserPointerNormalMaterial get set inherited
Definition at line 84 of file AbstractPointerDevice.cs.
 { get; set; }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.PlayInteraction(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
LastDirection
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LastDirection get inherited
Definition at line 325 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (LastSmoothedWorldPoint - LastOrigin).normalized;
             }
         }
LastOrigin
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LastOrigin get private set inherited
Definition at line 248 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
LastScreenPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LastScreenPoint get inherited
Definition at line 357 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(LastSmoothedWorldPoint);
             }
         }
LastSmoothedWorldPoint
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LastSmoothedWorldPoint get private set inherited
Definition at line 299 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
LastViewportPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LastViewportPoint get inherited
Definition at line 381 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(LastSmoothedWorldPoint);
             }
         }
LastWorldPoint
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LastWorldPoint get private set inherited
Definition at line 267 of file AbstractPointerDevice.cs.
         {
             get; private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
Layer
int Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Layer get set inherited
Definition at line 91 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return gameObject.layer;
             }
             set
             {
                 if (value != gameObject.layer)
                 {
                     foreach (var trans in transform.FamilyTree())
                     {
                         trans.gameObject.layer = value;
                     }
                 }
             }
         }
LockedOnTarget
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.LockedOnTarget get set inherited
Definition at line 109 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
MaximumPointerDistance
float Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.MaximumPointerDistance get inherited
Definition at line 73 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Min(InputModule.maxPointerDistance, 0.9f * DisplayManager.MainCamera.farClipPlane);
             }
         }
MinimumPointerDistance
float Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.MinimumPointerDistance get inherited
The minimum distance from the camera at which to place the pointer.
Definition at line 63 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Max(InputModule.minPointerDistance, 1.1f * DisplayManager.MainCamera.nearClipPlane);
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Awake().
Origin
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Origin get inherited
Definition at line 240 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return transform.position;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
OriginDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.OriginDelta get inherited
Definition at line 254 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Origin - LastOrigin;
             }
         }
PointerDataID
int Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.PointerDataID get inherited
Definition at line 52 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return GetInstanceID();
             }
         }
Probe
IProbe Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Probe get private set inherited
The cursor probe that shows the physical location of the current selection.
Definition at line 221 of file AbstractPointerDevice.cs.
 { get; private set; }
ProbeName
string Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ProbeName get inherited
Definition at line 232 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return name + "-probe";
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.OnProbeFound().
ProcessInUpdate
virtual bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ProcessInUpdate get inherited
Definition at line 44 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return true;
             }
         }
Raycaster
PhysicsRaycaster? Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.Raycaster get inherited
Definition at line 144 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Probe?.Raycaster;
             }
         }
ScreenDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ScreenDelta get inherited
Definition at line 365 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenPoint - LastScreenPoint;
             }
         }
ScreenPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ScreenPoint get inherited
Definition at line 349 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(SmoothedWorldPoint);
             }
         }
ScrollDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ScrollDelta get protected set inherited
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 401 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< InteractionSourceHandedness, WindowsMRButtons, WindowsMRMotionControllerConfiguration, HapticType >.InternalUpdate().
SmoothedWorldPoint
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.SmoothedWorldPoint get inherited
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 284 of file AbstractPointerDevice.cs.
         {
             get
             {
                 if (motionFilter == null)
                 {
                     return WorldPoint;
                 }
                 else
                 {
                     return motionFilter.PredictedPosition;
                 }
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Process().
SmoothedWorldPointDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.SmoothedWorldPointDelta get inherited
Definition at line 305 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return SmoothedWorldPoint - LastSmoothedWorldPoint;
             }
         }
transform
Transform Juniper.Input.Pointers.IPointerDevice.transform get inherited
Definition at line 32 of file IPointerDevice.cs.
 { get; }
Referenced by Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.OnProbeFound(), and Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
ViewportDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ViewportDelta get inherited
Definition at line 389 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportPoint - LastViewportPoint;
             }
         }
ViewportPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.ViewportPoint get inherited
Definition at line 373 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(SmoothedWorldPoint);
             }
         }
WorldDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.WorldDelta get inherited
Definition at line 272 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return WorldPoint - LastWorldPoint;
             }
         }
WorldPoint
abstract Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType, HapticType >.WorldPoint get inherited
Definition at line 262 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Input/Pointers/Screen/AbstractScreenDevice.cs