Juniper: Juniper.Sound.NAudioAudioDataDecoder Class Reference
Juniper.Sound.NAudioAudioDataDecoder Class Reference
Public Member Functions
NAudioAudioDataDecoder ()
bool SupportsFormat (AudioFormat format)
WaveStream MakeDecodingStream (Stream stream)
AudioData Deserialize (Stream stream)
Static Public Attributes
static readonly MediaType.Audio [] SupportedFormats
Properties
AudioFormat? Format [get, set]
MediaType.Audio ContentType [get]
Private Member Functions
IMp3FrameDecompressor CreateMp3FrameDecompressor (WaveFormat format)
void ValidateFormat (int sampleRate, int bitsPerSample, int channels)
Static Private Member Functions
static AudioFormat MakeAudioFormat (int sampleRate, int bitsPerSample, int channels)
Private Attributes
AudioFormat format
Detailed Description
Definition at line 9 of file NAudioAudioDataDecoder.cs.
Constructor & Destructor Documentation
NAudioAudioDataDecoder()
Juniper.Sound.NAudioAudioDataDecoder.NAudioAudioDataDecoder () inline
Definition at line 18 of file NAudioAudioDataDecoder.cs.
         { }
Member Function Documentation
CreateMp3FrameDecompressor()
IMp3FrameDecompressor Juniper.Sound.NAudioAudioDataDecoder.CreateMp3FrameDecompressor (WaveFormat format) inline private
Definition at line 79 of file NAudioAudioDataDecoder.cs.
         {
             if (Environment.OSVersion.Platform == PlatformID.Unix
                 || Environment.OSVersion.Platform == PlatformID.MacOSX)
             {
                 // This works on Android, but only seems to work for some Mp3 files.
                 return new NLayer.NAudioSupport.Mp3FrameDecompressor(format);
             }
             else
             {
                 // This seems to work for all Mp3 files, but only works on Windows.
                 return Mp3FileReader.CreateAcmFrameDecompressor(format);
             }
         }
References Juniper.Sound.NAudioAudioDataDecoder.format.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream().
Deserialize()
AudioData Juniper.Sound.NAudioAudioDataDecoder.Deserialize (Stream stream) inline
Definition at line 94 of file NAudioAudioDataDecoder.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             if (!stream.CanSeek)
             {
                 var mem = new MemoryStream();
                 stream.CopyTo(mem);
                 stream = mem;
             }
             var waveStream = MakeDecodingStream(stream);
             var format = waveStream.WaveFormat;
             var sampleRate = format.SampleRate;
             var bitsPerSample = format.BitsPerSample;
             var bytesPerSample = (int)Units.Bits.Bytes(bitsPerSample);
             var channels = format.Channels;
             var samples = waveStream.Length / bytesPerSample;
             ValidateFormat(sampleRate, bitsPerSample, channels);
             var audioFormat = MakeAudioFormat(sampleRate, bitsPerSample, channels);
             var pcmStream = new PcmBytesToFloatsStream(waveStream, bytesPerSample);
             return new AudioData(audioFormat, pcmStream, samples);
         }
References Juniper.Sound.AudioFormat.BitsPerSample, Juniper.Sound.AudioFormat.Channels, Juniper.Sound.NAudioAudioDataDecoder.format, Juniper.Sound.NAudioAudioDataDecoder.MakeAudioFormat(), Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream(), Juniper.Sound.AudioFormat.SampleRate, and Juniper.Sound.NAudioAudioDataDecoder.ValidateFormat().
MakeAudioFormat()
static AudioFormat Juniper.Sound.NAudioAudioDataDecoder.MakeAudioFormat (int sampleRate, int bitsPerSample, int channels) inline static private
Definition at line 141 of file NAudioAudioDataDecoder.cs.
         {
             var channelString = channels == 1 ? "mono" : "stereo";
             var sampsStr = (sampleRate / 1000).ToString(CultureInfo.CurrentCulture);
             var formatName = $"float-{sampsStr}khz-{bitsPerSample.ToString(CultureInfo.CurrentCulture)}bit-{channelString}-pcm";
             var audioFormat = new AudioFormat(
                 formatName,
                 MediaType.Audio.PCMA,
                 sampleRate,
                 bitsPerSample,
                 channels);
             return audioFormat;
         }
References Juniper.MediaType.Audio.PCMA.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.Deserialize().
MakeDecodingStream()
WaveStream Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream (Stream stream) inline
Definition at line 58 of file NAudioAudioDataDecoder.cs.
         {
             if (Format.ContentType == MediaType.Audio.X_Wav)
             {
                 return new WaveFileReader(stream);
             }
             else if (Format.ContentType == MediaType.Audio.Mpeg)
             {
                 return new Mp3FileReader(stream, CreateMp3FrameDecompressor);
             }
             else if (Format.ContentType == MediaType.Audio.PCMA)
             {
                 var format = new WaveFormat(Format.SampleRate, Format.BitsPerSample, Format.Channels);
                 return new RawSourceWaveStream(stream, format);
             }
             else
             {
                 throw new NotSupportedException($"Don't know how to decode audio format {Format.ContentType}");
             }
         }
References Juniper.Sound.AudioFormat.BitsPerSample, Juniper.Sound.AudioFormat.Channels, Juniper.Sound.AudioFormat.ContentType, Juniper.Sound.NAudioAudioDataDecoder.CreateMp3FrameDecompressor(), Juniper.Sound.NAudioAudioDataDecoder.format, Juniper.Sound.NAudioAudioDataDecoder.Format, Juniper.MediaType.Audio.Mpeg, Juniper.MediaType.Audio.PCMA, Juniper.Sound.AudioFormat.SampleRate, and Juniper.MediaType.Audio.X_Wav.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.Deserialize().
SupportsFormat()
bool Juniper.Sound.NAudioAudioDataDecoder.SupportsFormat (AudioFormat format) inline
Implements Juniper.Sound.IAudioDecoder.
Definition at line 21 of file NAudioAudioDataDecoder.cs.
         {
             return Array.IndexOf(SupportedFormats, format?.ContentType) > -1;
         }
References Juniper.Sound.NAudioAudioDataDecoder.ContentType, Juniper.Sound.NAudioAudioDataDecoder.format, and Juniper.Sound.NAudioAudioDataDecoder.SupportedFormats.
ValidateFormat()
void Juniper.Sound.NAudioAudioDataDecoder.ValidateFormat (int sampleRate, int bitsPerSample, int channels) inline private
Definition at line 123 of file NAudioAudioDataDecoder.cs.
         {
             if (sampleRate != Format.SampleRate)
             {
                 throw new InvalidOperationException($"Sample Rate does not match between audio format and audio file. Expected: {Format.SampleRate.ToString(CultureInfo.CurrentCulture)}. Actual: {sampleRate.ToString(CultureInfo.CurrentCulture)}");
             }
             if (bitsPerSample != Format.BitsPerSample)
             {
                 throw new InvalidOperationException($"Sample Size does not match between audio format and audio file. Expected: {Format.BitsPerSample.ToString(CultureInfo.CurrentCulture)}. Actual: {bitsPerSample.ToString(CultureInfo.CurrentCulture)}");
             }
             if (channels != Format.Channels)
             {
                 throw new InvalidOperationException($"Channel Count does not match between audio format and audio file. Expected: {Format.Channels.ToString(CultureInfo.CurrentCulture)}. Actual: {channels.ToString(CultureInfo.CurrentCulture)}");
             }
         }
References Juniper.Sound.AudioFormat.BitsPerSample, Juniper.Sound.AudioFormat.Channels, Juniper.Sound.NAudioAudioDataDecoder.Format, and Juniper.Sound.AudioFormat.SampleRate.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.Deserialize().
Member Data Documentation
format
AudioFormat Juniper.Sound.NAudioAudioDataDecoder.format private
Definition at line 26 of file NAudioAudioDataDecoder.cs.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.CreateMp3FrameDecompressor(), Juniper.Sound.NAudioAudioDataDecoder.Deserialize(), Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream(), and Juniper.Sound.NAudioAudioDataDecoder.SupportsFormat().
SupportedFormats
readonly MediaType.Audio [] Juniper.Sound.NAudioAudioDataDecoder.SupportedFormats static
Initial value:
=
        {
            MediaType.Audio.X_Wav,
            MediaType.Audio.Mpeg,
            MediaType.Audio.PCMA
        }
Definition at line 11 of file NAudioAudioDataDecoder.cs.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.SupportsFormat().
Property Documentation
ContentType
MediaType.Audio Juniper.Sound.NAudioAudioDataDecoder.ContentType get
Definition at line 44 of file NAudioAudioDataDecoder.cs.
         {
             get
             {
                 if (Format is null)
                 {
                     return null;
                 }
                 else
                 {
                     return Format.ContentType;
                 }
             }
         }
Referenced by Juniper.Sound.NAudioAudioDataDecoder.SupportsFormat().
Format
AudioFormat? Juniper.Sound.NAudioAudioDataDecoder.Format get set
Definition at line 29 of file NAudioAudioDataDecoder.cs.
         {
             get { return format; }
             set
             {
                 if (!SupportsFormat(value))
                 {
                     throw new NotSupportedException($"Don't know how to decode audio format {value?.ContentType}");
                 }
                 format = value;
             }
         }
Referenced by Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream(), and Juniper.Sound.NAudioAudioDataDecoder.ValidateFormat().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Sound/NAudioAudioDataDecoder.cs