Juniper: Juniper.Data.AbstractBackgroundRepeatingThread Class Reference
Juniper.Data.AbstractBackgroundRepeatingThread Class Reference abstract
Performs an operation in a loop on a background thread.
Public Member Functions
void Stop ()
Signal to the background thread that it should stop the repeatition process and shut down.
Protected Member Functions
override void Awake ()
Create a new background thread, initialized in a non-running, non-shutting down state.
override void OnBegin ()
Code to execute when the thread first starts.
override void Execute ()
The routine that runs on the background thread.
abstract void Loop ()
Override to implement code that should execute on every repetition of the thread.
void OnError (Exception exp)
Trigger the Error event handler, if it has any listeners attached to it.
void Begin ()
Get the background thread up and running.
Properties
override bool Running [get]
Returns true if the thread is still running and not in the middle of shutting down
Events
EventHandler< BackgroundThreadErrorEventArgs > Error
An event that triggers if the background operation throws an exception.
Private Attributes
bool stopping
Whether or not the thread is currently shutting down.
Detailed Description
Performs an operation in a loop on a background thread.
Definition at line 8 of file AbstractBackgroundRepeatingThread.cs.
Member Function Documentation
Awake()
override void Juniper.Data.AbstractBackgroundRepeatingThread.Awake () inline protected virtual
Create a new background thread, initialized in a non-running, non-shutting down state.
Reimplemented from Juniper.Data.AbstractBackgroundThread.
Definition at line 32 of file AbstractBackgroundRepeatingThread.cs.
         {
             base.Awake();
             stopping = false;
         }
References Juniper.Data.AbstractBackgroundRepeatingThread.stopping.
Begin()
void Juniper.Data.AbstractBackgroundThread.Begin () inline protected inherited
Get the background thread up and running.
Definition at line 50 of file AbstractBackgroundThread.cs.
         {
             if (!Running)
             {
                 OnBegin();
                 Task.Run(new Action(Run));
             }
         }
References Juniper.Data.AbstractBackgroundThread.OnBegin(), Juniper.Data.AbstractBackgroundThread.Run(), and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.Vuforia.VuforiaImageAnalyzer.Update().
Execute()
override void Juniper.Data.AbstractBackgroundRepeatingThread.Execute () inline protected virtual
The routine that runs on the background thread.
Implements Juniper.Data.AbstractBackgroundThread.
Definition at line 50 of file AbstractBackgroundRepeatingThread.cs.
         {
             while (!stopping)
             {
                 try
                 {
                     Loop();
                 }
                 catch (Exception exp)
                 {
                     OnError(exp);
                 }
             }
         }
References Juniper.Data.AbstractBackgroundRepeatingThread.Loop(), Juniper.Data.AbstractBackgroundThread.OnError(), and Juniper.Data.AbstractBackgroundRepeatingThread.stopping.
Loop()
abstract void Juniper.Data.AbstractBackgroundRepeatingThread.Loop () protected pure virtual
Override to implement code that should execute on every repetition of the thread.
Implemented in Juniper.Data.ManagedRequest< T >, and Juniper.Vuforia.VuforiaImageAnalyzer.
Referenced by Juniper.Data.AbstractBackgroundRepeatingThread.Execute().
OnBegin()
override void Juniper.Data.AbstractBackgroundRepeatingThread.OnBegin () inline protected virtual
Code to execute when the thread first starts.
Reimplemented from Juniper.Data.AbstractBackgroundThread.
Definition at line 41 of file AbstractBackgroundRepeatingThread.cs.
         {
             base.OnBegin();
             stopping = false;
         }
References Juniper.Data.AbstractBackgroundRepeatingThread.stopping.
OnError()
void Juniper.Data.AbstractBackgroundThread.OnError (Exception exp) inline protected inherited
Trigger the Error event handler, if it has any listeners attached to it.
Parameters
exp
Definition at line 31 of file AbstractBackgroundThread.cs.
         {
             if (Running)
             {
                 Error?.Invoke(this, new BackgroundThreadErrorEventArgs(exp));
             }
         }
References Juniper.Data.AbstractBackgroundThread.Error, and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.Data.AbstractBackgroundRepeatingThread.Execute(), and Juniper.Data.AbstractBackgroundThread.Run().
Stop()
void Juniper.Data.AbstractBackgroundRepeatingThread.Stop () inline
Signal to the background thread that it should stop the repeatition process and shut down.
Definition at line 24 of file AbstractBackgroundRepeatingThread.cs.
         {
             stopping = true;
         }
References Juniper.Data.AbstractBackgroundRepeatingThread.stopping.
Referenced by Juniper.Vuforia.VuforiaImageAnalyzer.Update().
Member Data Documentation
stopping
bool Juniper.Data.AbstractBackgroundRepeatingThread.stopping private
Whether or not the thread is currently shutting down.
Definition at line 73 of file AbstractBackgroundRepeatingThread.cs.
Referenced by Juniper.Data.AbstractBackgroundRepeatingThread.Awake(), Juniper.Data.AbstractBackgroundRepeatingThread.Execute(), Juniper.Data.AbstractBackgroundRepeatingThread.OnBegin(), and Juniper.Data.AbstractBackgroundRepeatingThread.Stop().
Property Documentation
Running
override bool Juniper.Data.AbstractBackgroundRepeatingThread.Running get
Returns true if the thread is still running and not in the middle of shutting down
Definition at line 14 of file AbstractBackgroundRepeatingThread.cs.
         {
             get
             {
                 return base.Running && !stopping;
             }
         }
Referenced by Juniper.Data.ManagedRequest< T >.OnMessage(), Juniper.Data.ManagedRequest< T >.OnServerError(), Juniper.Data.ManagedRequest< T >.OnTimedOut(), Juniper.World.LightEstimation.VuforiaLightMeasurement.PrintDebugReport(), and Juniper.Vuforia.VuforiaImageAnalyzer.Update().
Event Documentation
Error
EventHandler<BackgroundThreadErrorEventArgs> Juniper.Data.AbstractBackgroundThread.Error inherited
An event that triggers if the background operation throws an exception.
Definition at line 14 of file AbstractBackgroundThread.cs.
Referenced by Juniper.Data.AbstractBackgroundThread.OnError().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Data/AbstractBackgroundRepeatingThread.cs