Juniper: Juniper.Unity.Anchoring.Grounded Class Reference
Juniper.Unity.Anchoring.Grounded Class Reference
This component searches for the ground above or below the gameObject it's attached to. When a mesh tagged as the "Ground" is found, with horizontal surfaces, the gameObject is moved to the ground and kept there. Use this when you have objects that should rest of the ground, but you're not sure where the ground will be.
Public Member Functions
void Awake ()
Get the physics components of the gameObject, find information about the ground mesh, and freeze the object in place until the ground is found.
void Update ()
If the test timeout has passed, raycast for the ground mesh under and over the object. If it's found, move the object to that point and unfreeze it.
void WhenGrounded (Action p)
Check to see if the object is grounded, and call the callback if it is. If it's not, put the callback into a queue for execution later in EmptyJobQueue.
Public Attributes
float testTimeout = 0.25f
How many seconds to wait in between ground tests, to avoid pegging the system with ground tests.
float horizontalnessThreshold = 0.85f
The minimum amount of horizontal-ness to consider for the "ground".
bool grounded = false
Display in the editor whether or not a ground point is currently available.
bool isFrozen = false
Display in the editor whether or not the object is frozen.
Private Member Functions
void Freeze ()
Freezing the object turns off any physics and dragging capability that might have been on the object.
void Unfreeze ()
Restore physics and draggable capabilities.
void EmptyJobQueue ()
Execute any WhenGrounded(Action) callbacks that were registered before the object was grounded.
Vector3? GetGroundUnderObject ()
Search above and below the object to find the ground mesh.
Private Attributes
Draggable dragger
If the object being grounded is also controlled by a draggable constraint handle, then we will need to check if the draggable is being held and disengage any attempts to ground the gameObject.
Rigidbody body
The physics body for this object, used to figure out the affect of gravity on the object.
bool wasUsingGravity
The saved "useGravity" value from the body object, so that it can be restored to its original value after the draggable handle has been removed.
bool wasKinematic
The saved "isKinematic" value from the body object, so that it can be restored to its original value after the draggable handle has been removed.
Vector3? groundPoint
Where the current gameObject has been ordered to find.
Queue< Action > q = new Queue<Action>()
Before the object is actually grounded, other entities may wish to know when it is. This queue holds callbacks to those entities to execute once the object is grounded.
int GroundMask
The raycasting mask for the ground mesh.
float lastTime
The time stamp of when the last ground test was performed.
Avatar stage
The stage that holds the user is really the thing that needs to be grounded.
bool frozen = false
A flag indicating the grounded object is already frozen in place.
Detailed Description
This component searches for the ground above or below the gameObject it's attached to. When a mesh tagged as the "Ground" is found, with horizontal surfaces, the gameObject is moved to the ground and kept there. Use this when you have objects that should rest of the ground, but you're not sure where the ground will be.
Definition at line 16 of file Grounded.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Anchoring.Grounded.Awake () inline
Get the physics components of the gameObject, find information about the ground mesh, and freeze the object in place until the ground is found.
Definition at line 79 of file Grounded.cs.
         {
             stage = ComponentExt.FindAny<Avatar>();
             body = GetComponentInChildren<Rigidbody>();
             dragger = GetComponent<Draggable>();
             GroundMask = LayerMask.GetMask("Ground");
             lastTime = Time.unscaledTime;
             Freeze();
         }
References Juniper.Unity.Anchoring.Grounded.body, Juniper.Unity.Anchoring.Grounded.dragger, Juniper.Unity.Anchoring.Grounded.Freeze(), Juniper.Unity.Anchoring.Grounded.GroundMask, Juniper.Unity.Anchoring.Grounded.lastTime, and Juniper.Unity.Anchoring.Grounded.stage.
EmptyJobQueue()
void Juniper.Unity.Anchoring.Grounded.EmptyJobQueue () inline private
Execute any WhenGrounded(Action) callbacks that were registered before the object was grounded.
Definition at line 133 of file Grounded.cs.
         {
             while (q.Count > 0)
             {
                 var act = q.Dequeue();
                 act();
             }
         }
References Juniper.Unity.Anchoring.Grounded.q.
Referenced by Juniper.Unity.Anchoring.Grounded.Update().
Freeze()
void Juniper.Unity.Anchoring.Grounded.Freeze () inline private
Freezing the object turns off any physics and dragging capability that might have been on the object.
Definition at line 93 of file Grounded.cs.
         {
             if (body != null && !frozen)
             {
                 frozen = true;
                 if (dragger != null)
                 {
                     dragger.enabled = false;
                 }
                 wasUsingGravity = body.useGravity;
                 wasKinematic = body.isKinematic;
                 body.useGravity = false;
                 body.isKinematic = true;
             }
         }
References Juniper.Unity.Anchoring.Grounded.body, Juniper.Unity.Anchoring.Grounded.dragger, Juniper.Unity.Anchoring.Grounded.frozen, Juniper.Unity.Anchoring.Grounded.wasKinematic, and Juniper.Unity.Anchoring.Grounded.wasUsingGravity.
Referenced by Juniper.Unity.Anchoring.Grounded.Awake(), and Juniper.Unity.Anchoring.Grounded.Update().
GetGroundUnderObject()
Vector3? Juniper.Unity.Anchoring.Grounded.GetGroundUnderObject () inline private
Search above and below the object to find the ground mesh.
Returns
The ground under object.
Definition at line 172 of file Grounded.cs.
         {
             var center = transform.position;
             var rays = new[]
             {
                 new Ray(center + 0.1f * Vector3.up, -transform.up),
                 new Ray(center + 0.1f * Vector3.down, transform.up)
             };
             foreach (var ray in rays)
             {
                 RaycastHit target;
                 if (Physics.Raycast(ray, out target, 10, GroundMask))
                 {
                     var test = Vector3.Dot(Vector3.up, target.normal);
                     var isHorizontal = test >= horizontalnessThreshold;
                     if (isHorizontal)
                     {
                         return target.point;
                     }
                 }
             }
             return null;
         }
References Juniper.Unity.Anchoring.Grounded.GroundMask, and Juniper.Unity.Anchoring.Grounded.horizontalnessThreshold.
Referenced by Juniper.Unity.Anchoring.Grounded.Update().
Unfreeze()
void Juniper.Unity.Anchoring.Grounded.Unfreeze () inline private
Restore physics and draggable capabilities.
Definition at line 113 of file Grounded.cs.
         {
             if (body != null && frozen)
             {
                 frozen = false;
                 body.useGravity = wasUsingGravity;
                 body.isKinematic = wasKinematic;
                 body.velocity = Vector3.zero;
                 if (dragger)
                 {
                     dragger.enabled = true;
                 }
             }
         }
References Juniper.Unity.Anchoring.Grounded.body, Juniper.Unity.Anchoring.Grounded.dragger, Juniper.Unity.Anchoring.Grounded.frozen, Juniper.Unity.Anchoring.Grounded.wasKinematic, and Juniper.Unity.Anchoring.Grounded.wasUsingGravity.
Referenced by Juniper.Unity.Anchoring.Grounded.Update().
Update()
void Juniper.Unity.Anchoring.Grounded.Update () inline
If the test timeout has passed, raycast for the ground mesh under and over the object. If it's found, move the object to that point and unfreeze it.
Definition at line 146 of file Grounded.cs.
         {
             if (Time.unscaledTime - lastTime > testTimeout)
             {
                 lastTime = Time.unscaledTime;
                 groundPoint = GetGroundUnderObject();
                 if (groundPoint == null)
                 {
                     Freeze();
                 }
                 else
                 {
                     transform.position = groundPoint.Value;
                     Unfreeze();
                     EmptyJobQueue();
                 }
             }
             isFrozen = frozen;
             grounded = groundPoint != null;
         }
References Juniper.Unity.Anchoring.Grounded.EmptyJobQueue(), Juniper.Unity.Anchoring.Grounded.Freeze(), Juniper.Unity.Anchoring.Grounded.frozen, Juniper.Unity.Anchoring.Grounded.GetGroundUnderObject(), Juniper.Unity.Anchoring.Grounded.grounded, Juniper.Unity.Anchoring.Grounded.groundPoint, Juniper.Unity.Anchoring.Grounded.isFrozen, Juniper.Unity.Anchoring.Grounded.lastTime, Juniper.Unity.Anchoring.Grounded.testTimeout, and Juniper.Unity.Anchoring.Grounded.Unfreeze().
WhenGrounded()
void Juniper.Unity.Anchoring.Grounded.WhenGrounded (Action p) inline
Check to see if the object is grounded, and call the callback if it is. If it's not, put the callback into a queue for execution later in EmptyJobQueue.
Parameters
p P.
Definition at line 226 of file Grounded.cs.
         {
             if (groundPoint != null)
             {
                 p();
             }
             else
             {
                 q.Enqueue(p);
             }
         }
References Juniper.Unity.Anchoring.Grounded.groundPoint, and Juniper.Unity.Anchoring.Grounded.q.
Referenced by Juniper.Unity.Avatar.Install().
Member Data Documentation
body
Rigidbody Juniper.Unity.Anchoring.Grounded.body private
The physics body for this object, used to figure out the affect of gravity on the object.
Definition at line 30 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Awake(), Juniper.Unity.Anchoring.Grounded.Freeze(), and Juniper.Unity.Anchoring.Grounded.Unfreeze().
dragger
Draggable Juniper.Unity.Anchoring.Grounded.dragger private
If the object being grounded is also controlled by a draggable constraint handle, then we will need to check if the draggable is being held and disengage any attempts to ground the gameObject.
Definition at line 25 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Awake(), Juniper.Unity.Anchoring.Grounded.Freeze(), and Juniper.Unity.Anchoring.Grounded.Unfreeze().
frozen
bool Juniper.Unity.Anchoring.Grounded.frozen = false private
A flag indicating the grounded object is already frozen in place.
Definition at line 73 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Freeze(), Juniper.Unity.Anchoring.Grounded.Unfreeze(), and Juniper.Unity.Anchoring.Grounded.Update().
grounded
bool Juniper.Unity.Anchoring.Grounded.grounded = false
Display in the editor whether or not a ground point is currently available.
Definition at line 213 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Update().
GroundMask
int Juniper.Unity.Anchoring.Grounded.GroundMask private
The raycasting mask for the ground mesh.
Definition at line 58 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Awake(), and Juniper.Unity.Anchoring.Grounded.GetGroundUnderObject().
groundPoint
Vector3? Juniper.Unity.Anchoring.Grounded.groundPoint private
Where the current gameObject has been ordered to find.
Definition at line 47 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Update(), and Juniper.Unity.Anchoring.Grounded.WhenGrounded().
horizontalnessThreshold
float Juniper.Unity.Anchoring.Grounded.horizontalnessThreshold = 0.85f
The minimum amount of horizontal-ness to consider for the "ground".
Definition at line 207 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.GetGroundUnderObject().
isFrozen
bool Juniper.Unity.Anchoring.Grounded.isFrozen = false
Display in the editor whether or not the object is frozen.
Definition at line 219 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Update().
lastTime
float Juniper.Unity.Anchoring.Grounded.lastTime private
The time stamp of when the last ground test was performed.
Definition at line 63 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Awake(), and Juniper.Unity.Anchoring.Grounded.Update().
q
Queue<Action> Juniper.Unity.Anchoring.Grounded.q = new Queue<Action>() private
Before the object is actually grounded, other entities may wish to know when it is. This queue holds callbacks to those entities to execute once the object is grounded.
Definition at line 53 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.EmptyJobQueue(), and Juniper.Unity.Anchoring.Grounded.WhenGrounded().
stage
Avatar Juniper.Unity.Anchoring.Grounded.stage private
The stage that holds the user is really the thing that needs to be grounded.
Definition at line 68 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Awake().
testTimeout
float Juniper.Unity.Anchoring.Grounded.testTimeout = 0.25f
How many seconds to wait in between ground tests, to avoid pegging the system with ground tests.
Definition at line 202 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Update().
wasKinematic
bool Juniper.Unity.Anchoring.Grounded.wasKinematic private
The saved "isKinematic" value from the body object, so that it can be restored to its original value after the draggable handle has been removed.
Definition at line 42 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Freeze(), and Juniper.Unity.Anchoring.Grounded.Unfreeze().
wasUsingGravity
bool Juniper.Unity.Anchoring.Grounded.wasUsingGravity private
The saved "useGravity" value from the body object, so that it can be restored to its original value after the draggable handle has been removed.
Definition at line 36 of file Grounded.cs.
Referenced by Juniper.Unity.Anchoring.Grounded.Freeze(), and Juniper.Unity.Anchoring.Grounded.Unfreeze().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Anchoring/Grounded.cs