Juniper: Hjg.Pngcs.ImageLineHelper Class Reference
Hjg.Pngcs.ImageLineHelper Class Reference
Static Public Member Functions
static int [] Palette2rgb (ImageLine line, PngChunkPLTE pal, PngChunkTRNS trns, int[] buf)
Given an indexed line with a palette, unpacks as a RGB array
static int [] Palette2rgb (ImageLine line, PngChunkPLTE pal, int[] buf)
static int ToARGB8 (int r, int g, int b)
static int ToARGB8 (int r, int g, int b, int a)
static int ToARGB8 (int[] buff, int offset, bool alpha)
static int ToARGB8 (byte[] buff, int offset, bool alpha)
static void FromARGB8 (int val, int[] buff, int offset, bool alpha)
static void FromARGB8 (int val, byte[] buff, int offset, bool alpha)
static int GetPixelToARGB8 (ImageLine line, int column)
static void SetPixelFromARGB8 (ImageLine line, int column, int argb)
static void SetPixel (ImageLine line, int col, int r, int g, int b, int a)
static void SetPixel (ImageLine line, int col, int r, int g, int b)
static double ReadDouble (ImageLine line, int pos)
static void WriteDouble (ImageLine line, double d, int pos)
static int Interpol (int a, int b, int c, int d, double dx, double dy)
static int ClampTo_0_255 (int i)
static double ClampDouble (double i)
static int ClampTo_0_65535 (int i)
static int ClampTo_128_127 (int x)
static int [] Unpack (ImageInfo imgInfo, int[] src, int[] dst, bool scale)
static byte [] Unpack (ImageInfo imgInfo, byte[] src, byte[] dst, bool scale)
static int [] Pack (ImageInfo imgInfo, int[] src, int[] dst, bool scale)
static byte [] Pack (ImageInfo imgInfo, byte[] src, byte[] dst, bool scale)
Detailed Description
Bunch of utility static methods to process/analyze an image line.
Not essential at all, some methods are probably to be removed if future releases.
TODO: document this better
Definition at line 12 of file ImageLineHelper.cs.
Member Function Documentation
ClampDouble()
static double Hjg.Pngcs.ImageLineHelper.ClampDouble (double i) inline static
[0,1)
Definition at line 273 of file ImageLineHelper.cs.
         {
             if (i < 0)
             {
                 return 0;
             }
             else if (i >= 1)
             {
                 return 0.999999;
             }
             else
             {
                 return i;
             }
         }
ClampTo_0_255()
static int Hjg.Pngcs.ImageLineHelper.ClampTo_0_255 (int i) inline static
Definition at line 253 of file ImageLineHelper.cs.
         {
             if (i > 255)
             {
                 return 255;
             }
             else if (i < 0)
             {
                 return 0;
             }
             else
             {
                 return i;
             }
         }
ClampTo_0_65535()
static int Hjg.Pngcs.ImageLineHelper.ClampTo_0_65535 (int i) inline static
Definition at line 289 of file ImageLineHelper.cs.
         {
             if (i > 65535)
             {
                 return 65535;
             }
             else if (i < 0)
             {
                 return 0;
             }
             else
             {
                 return i;
             }
         }
ClampTo_128_127()
static int Hjg.Pngcs.ImageLineHelper.ClampTo_128_127 (int x) inline static
Definition at line 305 of file ImageLineHelper.cs.
         {
             if (x > 127)
             {
                 return 127;
             }
             else if (x < -128)
             {
                 return -128;
             }
             else
             {
                 return x;
             }
         }
FromARGB8() [1/2]
static void Hjg.Pngcs.ImageLineHelper.FromARGB8 (int val, int [] buff, int offset, bool alpha) inline static
Definition at line 104 of file ImageLineHelper.cs.
         {
             if (buff is null)
             {
                 throw new ArgumentNullException(nameof(buff));
             }
             buff[offset++] = ((val >> 16) & 0xFF);
             buff[offset++] = ((val >> 8) & 0xFF);
             buff[offset] = (val & 0xFF);
             if (alpha)
             {
                 buff[offset + 1] = ((val >> 24) & 0xFF);
             }
         }
Referenced by Hjg.Pngcs.ImageLineHelper.SetPixelFromARGB8().
FromARGB8() [2/2]
static void Hjg.Pngcs.ImageLineHelper.FromARGB8 (int val, byte [] buff, int offset, bool alpha) inline static
Definition at line 120 of file ImageLineHelper.cs.
         {
             if (buff is null)
             {
                 throw new ArgumentNullException(nameof(buff));
             }
             buff[offset++] = (byte)((val >> 16) & 0xFF);
             buff[offset++] = (byte)((val >> 8) & 0xFF);
             buff[offset] = (byte)(val & 0xFF);
             if (alpha)
             {
                 buff[offset + 1] = (byte)((val >> 24) & 0xFF);
             }
         }
GetPixelToARGB8()
static int Hjg.Pngcs.ImageLineHelper.GetPixelToARGB8 (ImageLine line, int column) inline static
Definition at line 136 of file ImageLineHelper.cs.
         {
             if (line is null)
             {
                 throw new ArgumentNullException(nameof(line));
             }
             if (line.IsInt())
             {
                 return ToARGB8(line.Scanline, column * line.channels, line.ImgInfo.Alpha);
             }
             else
             {
                 return ToARGB8(line.ScanlineB, column * line.channels, line.ImgInfo.Alpha);
             }
         }
References Hjg.Pngcs.ImageInfo.Alpha, Hjg.Pngcs.ImageLine.channels, Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.IsInt(), Hjg.Pngcs.ImageLine.Scanline, Hjg.Pngcs.ImageLine.ScanlineB, and Hjg.Pngcs.ImageLineHelper.ToARGB8().
Interpol()
static int Hjg.Pngcs.ImageLineHelper.Interpol (int a, int b, int c, int d, double dx, double dy) inline static
Definition at line 244 of file ImageLineHelper.cs.
         {
             // a b -> x (0-1)
             // c d
             var e = (a * (1.0 - dx)) + (b * dx);
             var f = (c * (1.0 - dx)) + (d * dx);
             return (int)((e * (1 - dy)) + (f * dy) + 0.5);
         }
Pack() [1/2]
static int [] Hjg.Pngcs.ImageLineHelper.Pack (ImageInfo imgInfo, int [] src, int [] dst, bool scale) inline static
Definition at line 383 of file ImageLineHelper.cs.
         {
             if (imgInfo is null)
             {
                 throw new ArgumentNullException(nameof(imgInfo));
             }
             if (src is null)
             {
                 throw new ArgumentNullException(nameof(src));
             }
             var len0 = imgInfo.SamplesPerRowPacked;
             if (dst is null || dst.Length < len0)
             {
                 dst = new int[len0];
             }
             if (imgInfo.Packed)
             {
                 ImageLine.PackInplaceInt(imgInfo, src, dst, scale);
             }
             else
             {
                 Array.Copy(src, 0, dst, 0, len0);
             }
             return dst;
         }
References Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.ImageLine.PackInplaceInt(), and Hjg.Pngcs.ImageInfo.SamplesPerRowPacked.
Pack() [2/2]
static byte [] Hjg.Pngcs.ImageLineHelper.Pack (ImageInfo imgInfo, byte [] src, byte [] dst, bool scale) inline static
Definition at line 413 of file ImageLineHelper.cs.
         {
             if (imgInfo is null)
             {
                 throw new ArgumentNullException(nameof(imgInfo));
             }
             if (src is null)
             {
                 throw new ArgumentNullException(nameof(src));
             }
             var len0 = imgInfo.SamplesPerRowPacked;
             if (dst is null || dst.Length < len0)
             {
                 dst = new byte[len0];
             }
             if (imgInfo.Packed)
             {
                 ImageLine.PackInplaceByte(imgInfo, src, dst, scale);
             }
             else
             {
                 Array.Copy(src, 0, dst, 0, len0);
             }
             return dst;
         }
References Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.ImageLine.PackInplaceByte(), and Hjg.Pngcs.ImageInfo.SamplesPerRowPacked.
Palette2rgb() [1/2]
static int [] Hjg.Pngcs.ImageLineHelper.Palette2rgb (ImageLine line, PngChunkPLTE pal, PngChunkTRNS trns, int [] buf) inline static
Given an indexed line with a palette, unpacks as a RGB array
Parameters
line ImageLine as returned from PngReader
pal Palette chunk
trns TRNS chunk (optional)
buf Preallocated array, optional
Returns
R G B (one byte per sample)
Definition at line 22 of file ImageLineHelper.cs.
         {
             if (line is null)
             {
                 throw new ArgumentNullException(nameof(line));
             }
             if (pal is null)
             {
                 throw new ArgumentNullException(nameof(pal));
             }
             var isalpha = trns is object;
             var channels = isalpha ? 4 : 3;
             var nsamples = line.ImgInfo.Cols * channels;
             if (buf is null || buf.Length < nsamples)
             {
                 buf = new int[nsamples];
             }
             if (!line.SamplesUnpacked)
             {
                 line = line.UnpackToNewImageLine();
             }
             var isbyte = line.SampleType == Hjg.Pngcs.ImageLine.ESampleType.BYTE;
             var nindexesWithAlpha = trns?.GetPalletteAlpha().Length ?? 0;
             for (var c = 0; c < line.ImgInfo.Cols; c++)
             {
                 var index = isbyte ? (line.ScanlineB[c] & 0xFF) : line.Scanline[c];
                 pal.GetEntryRgb(index, buf, c * channels);
                 if (isalpha)
                 {
                     buf[(c * channels) + 3] = index < nindexesWithAlpha ? trns.GetPalletteAlpha()[index] : 255;
                 }
             }
             return buf;
         }
References Hjg.Pngcs.ImageInfo.Cols, Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntryRgb(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetPalletteAlpha(), Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.SamplesUnpacked, Hjg.Pngcs.ImageLine.SampleType, Hjg.Pngcs.ImageLine.Scanline, Hjg.Pngcs.ImageLine.ScanlineB, and Hjg.Pngcs.ImageLine.UnpackToNewImageLine().
Referenced by Hjg.Pngcs.ImageLineHelper.Palette2rgb().
Palette2rgb() [2/2]
static int [] Hjg.Pngcs.ImageLineHelper.Palette2rgb (ImageLine line, PngChunkPLTE pal, int [] buf) inline static
Definition at line 62 of file ImageLineHelper.cs.
         {
             return Palette2rgb(line, pal, null, buf);
         }
References Hjg.Pngcs.ImageLineHelper.Palette2rgb().
ReadDouble()
static double Hjg.Pngcs.ImageLineHelper.ReadDouble (ImageLine line, int pos) inline static
Definition at line 210 of file ImageLineHelper.cs.
         {
             if (line is null)
             {
                 throw new ArgumentNullException(nameof(line));
             }
             if (line.IsInt())
             {
                 return line.Scanline[pos] / (line.MaxSampleVal + 0.9);
             }
             else
             {
                 return line.ScanlineB[pos] / (line.MaxSampleVal + 0.9);
             }
         }
References Hjg.Pngcs.ImageLine.IsInt(), Hjg.Pngcs.ImageLine.MaxSampleVal, Hjg.Pngcs.ImageLine.Scanline, and Hjg.Pngcs.ImageLine.ScanlineB.
SetPixel() [1/2]
static void Hjg.Pngcs.ImageLineHelper.SetPixel (ImageLine line, int col, int r, int g, int b, int a) inline static
Definition at line 170 of file ImageLineHelper.cs.
         {
             if (line is null)
             {
                 throw new ArgumentNullException(nameof(line));
             }
             var offset = col * line.channels;
             if (line.IsInt())
             {
                 line.Scanline[offset++] = r;
                 line.Scanline[offset++] = g;
                 line.Scanline[offset] = b;
                 if (line.ImgInfo.Alpha)
                 {
                     line.Scanline[offset + 1] = a;
                 }
             }
             else
             {
                 line.ScanlineB[offset++] = (byte)r;
                 line.ScanlineB[offset++] = (byte)g;
                 line.ScanlineB[offset] = (byte)b;
                 if (line.ImgInfo.Alpha)
                 {
                     line.ScanlineB[offset + 1] = (byte)a;
                 }
             }
         }
References Hjg.Pngcs.ImageInfo.Alpha, Hjg.Pngcs.ImageLine.channels, Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.IsInt(), Hjg.Pngcs.ImageLine.Scanline, and Hjg.Pngcs.ImageLine.ScanlineB.
Referenced by Hjg.Pngcs.ImageLineHelper.SetPixel().
SetPixel() [2/2]
static void Hjg.Pngcs.ImageLineHelper.SetPixel (ImageLine line, int col, int r, int g, int b) inline static
Definition at line 200 of file ImageLineHelper.cs.
         {
             if (line is null)
             {
                 throw new ArgumentNullException(nameof(line));
             }
             SetPixel(line, col, r, g, b, line.MaxSampleVal);
         }
References Hjg.Pngcs.ImageLine.MaxSampleVal, and Hjg.Pngcs.ImageLineHelper.SetPixel().
SetPixelFromARGB8()
static void Hjg.Pngcs.ImageLineHelper.SetPixelFromARGB8 (ImageLine line, int column, int argb) inline static
Definition at line 153 of file ImageLineHelper.cs.
         {
             if (line is null)
             {
                 throw new ArgumentNullException(nameof(line));
             }
             if (line.IsInt())
             {
                 FromARGB8(argb, line.Scanline, column * line.channels, line.ImgInfo.Alpha);
             }
             else
             {
                 FromARGB8(argb, line.ScanlineB, column * line.channels, line.ImgInfo.Alpha);
             }
         }
References Hjg.Pngcs.ImageInfo.Alpha, Hjg.Pngcs.ImageLine.channels, Hjg.Pngcs.ImageLineHelper.FromARGB8(), Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.IsInt(), Hjg.Pngcs.ImageLine.Scanline, and Hjg.Pngcs.ImageLine.ScanlineB.
ToARGB8() [1/4]
static int Hjg.Pngcs.ImageLineHelper.ToARGB8 (int r, int g, int b) inline static
Definition at line 67 of file ImageLineHelper.cs.
         {
             unchecked
             {
                 return ((int)(0xFF000000)) | (r << 16) | (g << 8) | b;
             }
         }
Referenced by Hjg.Pngcs.ImageLineHelper.GetPixelToARGB8(), and Hjg.Pngcs.ImageLineHelper.ToARGB8().
ToARGB8() [2/4]
static int Hjg.Pngcs.ImageLineHelper.ToARGB8 (int r, int g, int b, int a) inline static
Definition at line 75 of file ImageLineHelper.cs.
         {
             return (a << 24) | (r << 16) | (g << 8) | b;
         }
ToARGB8() [3/4]
static int Hjg.Pngcs.ImageLineHelper.ToARGB8 (int [] buff, int offset, bool alpha) inline static
Definition at line 80 of file ImageLineHelper.cs.
         {
             if (buff is null)
             {
                 throw new ArgumentNullException(nameof(buff));
             }
             return alpha
                 ? ToARGB8(buff[offset++], buff[offset++], buff[offset++], buff[offset])
                 : ToARGB8(buff[offset++], buff[offset++], buff[offset]);
         }
References Hjg.Pngcs.ImageLineHelper.ToARGB8().
ToARGB8() [4/4]
static int Hjg.Pngcs.ImageLineHelper.ToARGB8 (byte [] buff, int offset, bool alpha) inline static
Definition at line 92 of file ImageLineHelper.cs.
         {
             if (buff is null)
             {
                 throw new ArgumentNullException(nameof(buff));
             }
             return alpha
                 ? ToARGB8(buff[offset++], buff[offset++], buff[offset++], buff[offset])
                 : ToARGB8(buff[offset++], buff[offset++], buff[offset]);
         }
References Hjg.Pngcs.ImageLineHelper.ToARGB8().
Unpack() [1/2]
static int [] Hjg.Pngcs.ImageLineHelper.Unpack (ImageInfo imgInfo, int [] src, int [] dst, bool scale) inline static
Definition at line 321 of file ImageLineHelper.cs.
         {
             if (imgInfo is null)
             {
                 throw new ArgumentNullException(nameof(imgInfo));
             }
             if (src is null)
             {
                 throw new ArgumentNullException(nameof(src));
             }
             var len1 = imgInfo.SamplesPerRow;
             var len0 = imgInfo.SamplesPerRowPacked;
             if (dst is null || dst.Length < len1)
             {
                 dst = new int[len1];
             }
             if (imgInfo.Packed)
             {
                 ImageLine.UnpackInplaceInt(imgInfo, src, dst, scale);
             }
             else
             {
                 Array.Copy(src, 0, dst, 0, len0);
             }
             return dst;
         }
References Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.ImageInfo.SamplesPerRow, Hjg.Pngcs.ImageInfo.SamplesPerRowPacked, and Hjg.Pngcs.ImageLine.UnpackInplaceInt().
Unpack() [2/2]
static byte [] Hjg.Pngcs.ImageLineHelper.Unpack (ImageInfo imgInfo, byte [] src, byte [] dst, bool scale) inline static
Definition at line 352 of file ImageLineHelper.cs.
         {
             if (imgInfo is null)
             {
                 throw new ArgumentNullException(nameof(imgInfo));
             }
             if (src is null)
             {
                 throw new ArgumentNullException(nameof(src));
             }
             var len1 = imgInfo.SamplesPerRow;
             var len0 = imgInfo.SamplesPerRowPacked;
             if (dst is null || dst.Length < len1)
             {
                 dst = new byte[len1];
             }
             if (imgInfo.Packed)
             {
                 ImageLine.UnpackInplaceByte(imgInfo, src, dst, scale);
             }
             else
             {
                 Array.Copy(src, 0, dst, 0, len0);
             }
             return dst;
         }
References Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.ImageInfo.SamplesPerRow, Hjg.Pngcs.ImageInfo.SamplesPerRowPacked, and Hjg.Pngcs.ImageLine.UnpackInplaceByte().
WriteDouble()
static void Hjg.Pngcs.ImageLineHelper.WriteDouble (ImageLine line, double d, int pos) inline static
Definition at line 227 of file ImageLineHelper.cs.
         {
             if (line is null)
             {
                 throw new ArgumentNullException(nameof(line));
             }
             if (line.IsInt())
             {
                 line.Scanline[pos] = (int)(d * (line.MaxSampleVal + 0.99));
             }
             else
             {
                 line.ScanlineB[pos] = (byte)(d * (line.MaxSampleVal + 0.99));
             }
         }
References Hjg.Pngcs.ImageLine.IsInt(), Hjg.Pngcs.ImageLine.MaxSampleVal, Hjg.Pngcs.ImageLine.Scanline, and Hjg.Pngcs.ImageLine.ScanlineB.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/ImageLineHelper.cs