Juniper: Juniper.Widgets.Tooltipable Class Reference
Juniper.Widgets.Tooltipable Class Reference
Public Member Functions
bool IsInteractable ()
void Awake ()
void OnEnable ()
void OnPointerEnter (PointerEventData eventData)
void OnPointerExit (PointerEventData eventData)
Public Attributes
Transform tooltip
float delayBeforeDisplay = 1
float delayBeforeHide = 0.5f
Properties
string Text [get, set]
Private Member Functions
void GetControls ()
void Hide ()
void ShowTooltip ()
void HideTooltip ()
IEnumerator HideTooltipCoroutine ()
Static Private Member Functions
static bool AlwaysEnabled ()
A default function for when the Tooltipable is applied to something that does not have a parent control.
Private Attributes
TextComponentWrapper textElement
Speakable speech
AbstractStateController trans
Func< bool > isParentEnabled
Detailed Description
Definition at line 11 of file Tooltipable.cs.
Member Function Documentation
AlwaysEnabled()
static bool Juniper.Widgets.Tooltipable.AlwaysEnabled () inline static private
A default function for when the Tooltipable is applied to something that does not have a parent control.
Returns
Definition at line 21 of file Tooltipable.cs.
         {
             return true;
         }
Referenced by Juniper.Widgets.Tooltipable.Awake().
Awake()
void Juniper.Widgets.Tooltipable.Awake () inline
Definition at line 101 of file Tooltipable.cs.
         {
             if (tooltip == null)
             {
                 enabled = false;
             }
             else
             {
                 trans = tooltip.GetComponent<AbstractStateController>();
             }
             var parent = GetComponent<IPointerClickHandler>();
             if (parent is UnityEngine.UI.Selectable selectable)
             {
                 isParentEnabled = selectable.IsInteractable;
             }
             else if (parent is AbstractTouchable touchable)
             {
                 isParentEnabled = touchable.IsInteractable;
             }
             else
             {
                 isParentEnabled = AlwaysEnabled;
             }
             Hide();
         }
References Juniper.Widgets.Tooltipable.AlwaysEnabled(), Juniper.Widgets.Tooltipable.Hide(), Juniper.Widgets.Tooltipable.isParentEnabled, Juniper.Widgets.Tooltipable.tooltip, and Juniper.Widgets.Tooltipable.trans.
GetControls()
void Juniper.Widgets.Tooltipable.GetControls () inline private
Definition at line 55 of file Tooltipable.cs.
         {
             if (tooltip == null)
             {
                 tooltip = transform.Find("Tooltip");
             }
             if (tooltip != null && textElement == null)
             {
                 textElement = tooltip.Ensure<TextComponentWrapper>();
                 textElement.SetupControls();
             }
             if (speech == null)
             {
                 speech = GetComponent<Speakable>();
             }
         }
References Juniper.Widgets.TextComponentWrapper.SetupControls(), Juniper.Widgets.Tooltipable.speech, Juniper.Widgets.Tooltipable.textElement, and Juniper.Widgets.Tooltipable.tooltip.
Hide()
void Juniper.Widgets.Tooltipable.Hide () inline private
Definition at line 134 of file Tooltipable.cs.
         {
             if (trans != null)
             {
                 trans.SkipExit();
             }
             if (tooltip != null)
             {
                 tooltip.Deactivate();
             }
         }
References Juniper.AbstractStateController.SkipExit(), Juniper.Widgets.Tooltipable.tooltip, and Juniper.Widgets.Tooltipable.trans.
Referenced by Juniper.Widgets.Tooltipable.Awake(), and Juniper.Widgets.Tooltipable.OnEnable().
HideTooltip()
void Juniper.Widgets.Tooltipable.HideTooltip () inline private
Definition at line 166 of file Tooltipable.cs.
         {
             if (isActiveAndEnabled)
             {
                 this.Run(HideTooltipCoroutine());
             }
         }
References Juniper.Widgets.Tooltipable.HideTooltipCoroutine().
Referenced by Juniper.Widgets.Tooltipable.OnPointerEnter(), and Juniper.Widgets.Tooltipable.OnPointerExit().
HideTooltipCoroutine()
IEnumerator Juniper.Widgets.Tooltipable.HideTooltipCoroutine () inline private
Definition at line 174 of file Tooltipable.cs.
         {
             if (trans != null && trans.CanExit)
             {
                 yield return trans.ExitAsync().AsCoroutine();
             }
             tooltip.Deactivate();
         }
References Juniper.AbstractStateController.CanExit, Juniper.AbstractStateController.ExitAsync(), Juniper.Widgets.Tooltipable.tooltip, and Juniper.Widgets.Tooltipable.trans.
Referenced by Juniper.Widgets.Tooltipable.HideTooltip().
IsInteractable()
bool Juniper.Widgets.Tooltipable.IsInteractable () inline
Definition at line 43 of file Tooltipable.cs.
         {
             return enabled && isParentEnabled();
         }
References Juniper.Widgets.Tooltipable.isParentEnabled.
OnEnable()
void Juniper.Widgets.Tooltipable.OnEnable () inline
Definition at line 129 of file Tooltipable.cs.
         {
             Hide();
         }
References Juniper.Widgets.Tooltipable.Hide().
OnPointerEnter()
void Juniper.Widgets.Tooltipable.OnPointerEnter (PointerEventData eventData) inline
Definition at line 183 of file Tooltipable.cs.
         {
             CancelInvoke(nameof(ShowTooltip));
             CancelInvoke(nameof(HideTooltip));
             Invoke(nameof(ShowTooltip), delayBeforeDisplay);
         }
References Juniper.Widgets.Tooltipable.delayBeforeDisplay, Juniper.Widgets.Tooltipable.HideTooltip(), and Juniper.Widgets.Tooltipable.ShowTooltip().
OnPointerExit()
void Juniper.Widgets.Tooltipable.OnPointerExit (PointerEventData eventData) inline
Definition at line 190 of file Tooltipable.cs.
         {
             CancelInvoke(nameof(ShowTooltip));
             CancelInvoke(nameof(HideTooltip));
             Invoke(nameof(HideTooltip), delayBeforeHide);
         }
References Juniper.Widgets.Tooltipable.delayBeforeHide, Juniper.Widgets.Tooltipable.HideTooltip(), and Juniper.Widgets.Tooltipable.ShowTooltip().
ShowTooltip()
void Juniper.Widgets.Tooltipable.ShowTooltip () inline private
Definition at line 147 of file Tooltipable.cs.
         {
             if (isParentEnabled())
             {
                 tooltip.Activate();
                 if (trans != null && trans.CanEnter)
                 {
                     trans.Enter();
                 }
                 if (speech != null)
                 {
 #if AZURE_SPEECHSDK
                     speech.Play();
 #endif
                 }
             }
         }
References Juniper.AbstractStateController.CanEnter, Juniper.AbstractStateController.Enter(), Juniper.Widgets.Tooltipable.isParentEnabled, Juniper.Widgets.Tooltipable.speech, Juniper.Widgets.Tooltipable.tooltip, and Juniper.Widgets.Tooltipable.trans.
Referenced by Juniper.Widgets.Tooltipable.OnPointerEnter(), and Juniper.Widgets.Tooltipable.OnPointerExit().
Member Data Documentation
delayBeforeDisplay
float Juniper.Widgets.Tooltipable.delayBeforeDisplay = 1
Definition at line 36 of file Tooltipable.cs.
Referenced by Juniper.Widgets.Tooltipable.OnPointerEnter().
delayBeforeHide
float Juniper.Widgets.Tooltipable.delayBeforeHide = 0.5f
Definition at line 37 of file Tooltipable.cs.
Referenced by Juniper.Widgets.Tooltipable.OnPointerExit().
isParentEnabled
Func<bool> Juniper.Widgets.Tooltipable.isParentEnabled private
Definition at line 41 of file Tooltipable.cs.
Referenced by Juniper.Widgets.Tooltipable.Awake(), Juniper.Widgets.Tooltipable.IsInteractable(), and Juniper.Widgets.Tooltipable.ShowTooltip().
speech
Speakable Juniper.Widgets.Tooltipable.speech private
Definition at line 34 of file Tooltipable.cs.
Referenced by Juniper.Widgets.Tooltipable.GetControls(), and Juniper.Widgets.Tooltipable.ShowTooltip().
textElement
TextComponentWrapper Juniper.Widgets.Tooltipable.textElement private
Definition at line 30 of file Tooltipable.cs.
Referenced by Juniper.Widgets.Tooltipable.GetControls().
tooltip
Transform Juniper.Widgets.Tooltipable.tooltip
Definition at line 26 of file Tooltipable.cs.
Referenced by Juniper.Widgets.Tooltipable.Awake(), Juniper.Widgets.Tooltipable.GetControls(), Juniper.Widgets.Tooltipable.Hide(), Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), and Juniper.Widgets.Tooltipable.ShowTooltip().
trans
AbstractStateController Juniper.Widgets.Tooltipable.trans private
Definition at line 39 of file Tooltipable.cs.
Referenced by Juniper.Widgets.Tooltipable.Awake(), Juniper.Widgets.Tooltipable.Hide(), Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), and Juniper.Widgets.Tooltipable.ShowTooltip().
Property Documentation
Text
string Juniper.Widgets.Tooltipable.Text get set
Definition at line 75 of file Tooltipable.cs.
         {
             get
             {
                 GetControls();
                 if(textElement != null)
                 {
                     return textElement.Text;
                 }
                 else
                 {
                     return string.Empty;
                 }
             }
             set
             {
                 GetControls();
                 if(textElement != null)
                 {
                     textElement.Text = value;
                 }
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Widgets/Tooltipable.cs