Juniper: Juniper.Mathematics.Matrix4x4Serializable Struct Reference
Juniper.Mathematics.Matrix4x4Serializable Struct Reference
Public Member Functions
Matrix4x4Serializable (float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24, float m31, float m32, float m33, float m34, float m41, float m42, float m43, float m44)
void GetObjectData (SerializationInfo info, StreamingContext context)
override bool Equals (object obj)
bool Equals (Matrix4x4Serializable other)
override int GetHashCode ()
System.Numerics.Matrix4x4 ToSystemMatrix4x4 ()
Accord.Math.Matrix4x4 ToAccordMatrix4x4 ()
Static Public Member Functions
static bool operator== (Matrix4x4Serializable left, Matrix4x4Serializable right)
static bool operator != (Matrix4x4Serializable left, Matrix4x4Serializable right)
static implicit operator System.Numerics.Matrix4x4 (Matrix4x4Serializable v)
static operator Matrix4x4Serializable (System.Numerics.Matrix4x4 v)
static implicit operator Accord.Math.Matrix4x4 (Matrix4x4Serializable v)
static operator Matrix4x4Serializable (Accord.Math.Matrix4x4 v)
Properties
float [] Values [get]
Private Member Functions
Matrix4x4Serializable (SerializationInfo info, StreamingContext context)
Static Private Attributes
static readonly string VALUES_FIELD = nameof(Values).ToLowerInvariant()
Detailed Description
Definition at line 8 of file Matrix4x4Serializable.cs.
Constructor & Destructor Documentation
Matrix4x4Serializable() [1/2]
Juniper.Mathematics.Matrix4x4Serializable.Matrix4x4Serializable (float m11, float m12, float m13, float m14, float m21, float m22, float m23, float m24, float m31, float m32, float m33, float m34, float m41, float m42, float m43, float m44) inline
Definition at line 15 of file Matrix4x4Serializable.cs.
         {
             Values = new[]
             {
                 m11, m12, m13, m14,
                 m21, m22, m23, m24,
                 m31, m32, m33, m34,
                 m41, m42, m43, m44
             };
         }
References Juniper.Mathematics.Matrix4x4Serializable.Values.
Matrix4x4Serializable() [2/2]
Juniper.Mathematics.Matrix4x4Serializable.Matrix4x4Serializable (SerializationInfo info, StreamingContext context) inline private
Definition at line 31 of file Matrix4x4Serializable.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Values = info.GetValue<float[]>(VALUES_FIELD);
         }
References Juniper.Mathematics.Matrix4x4Serializable.Values, and Juniper.Mathematics.Matrix4x4Serializable.VALUES_FIELD.
Member Function Documentation
Equals() [1/2]
override bool Juniper.Mathematics.Matrix4x4Serializable.Equals (object obj) inline
Definition at line 51 of file Matrix4x4Serializable.cs.
         {
             return obj is Matrix4x4Serializable serializable && Equals(serializable);
         }
Equals() [2/2]
bool Juniper.Mathematics.Matrix4x4Serializable.Equals (Matrix4x4Serializable other) inline
Definition at line 56 of file Matrix4x4Serializable.cs.
         {
             return EqualityComparer<float[]>.Default.Equals(Values, other.Values);
         }
References Juniper.Mathematics.Matrix4x4Serializable.Values.
GetHashCode()
override int Juniper.Mathematics.Matrix4x4Serializable.GetHashCode () inline
Definition at line 61 of file Matrix4x4Serializable.cs.
         {
             return 1291433875 + EqualityComparer<float[]>.Default.GetHashCode(Values);
         }
References Juniper.Mathematics.Matrix4x4Serializable.Values.
GetObjectData()
void Juniper.Mathematics.Matrix4x4Serializable.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 41 of file Matrix4x4Serializable.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(VALUES_FIELD, Values);
         }
References Juniper.Mathematics.Matrix4x4Serializable.Values, and Juniper.Mathematics.Matrix4x4Serializable.VALUES_FIELD.
operator !=()
static bool Juniper.Mathematics.Matrix4x4Serializable.operator != (Matrix4x4Serializable left, Matrix4x4Serializable right) inline static
Definition at line 71 of file Matrix4x4Serializable.cs.
         {
             return !(left == right);
         }
operator Accord.Math.Matrix4x4()
static implicit Juniper.Mathematics.Matrix4x4Serializable.operator Accord.Math.Matrix4x4 (Matrix4x4Serializable v) inline static
Definition at line 106 of file Matrix4x4Serializable.cs.
         {
             return v.ToAccordMatrix4x4();
         }
References Juniper.Mathematics.Matrix4x4Serializable.ToAccordMatrix4x4().
operator Matrix4x4Serializable() [1/2]
static Juniper.Mathematics.Matrix4x4Serializable.operator Matrix4x4Serializable (System.Numerics.Matrix4x4 v) inline explicit static
Definition at line 101 of file Matrix4x4Serializable.cs.
         {
             return System.Numerics.MathExt.ToJuniperMatrix4x4Serializable(v);
         }
References System.Numerics.MathExt.ToJuniperMatrix4x4Serializable().
operator Matrix4x4Serializable() [2/2]
static Juniper.Mathematics.Matrix4x4Serializable.operator Matrix4x4Serializable (Accord.Math.Matrix4x4 v) inline explicit static
Definition at line 111 of file Matrix4x4Serializable.cs.
         {
             return Accord.Math.MathExt.ToJuniperMatrix4x4Serializable(v);
         }
References Accord.Math.MathExt.ToJuniperMatrix4x4Serializable().
operator System.Numerics.Matrix4x4()
static implicit Juniper.Mathematics.Matrix4x4Serializable.operator System.Numerics.Matrix4x4 (Matrix4x4Serializable v) inline static
Definition at line 96 of file Matrix4x4Serializable.cs.
         {
             return v.ToSystemMatrix4x4();
         }
References Juniper.Mathematics.Matrix4x4Serializable.ToSystemMatrix4x4().
operator==()
static bool Juniper.Mathematics.Matrix4x4Serializable.operator== (Matrix4x4Serializable left, Matrix4x4Serializable right) inline static
Definition at line 66 of file Matrix4x4Serializable.cs.
         {
             return left.Equals(right);
         }
ToAccordMatrix4x4()
Accord.Math.Matrix4x4 Juniper.Mathematics.Matrix4x4Serializable.ToAccordMatrix4x4 () inline
Definition at line 85 of file Matrix4x4Serializable.cs.
         {
             return new Accord.Math.Matrix4x4
             {
                 V00 = Values[0x0], V01 = Values[0x1], V02 = Values[0x2], V03 = Values[0x3],
                 V10 = Values[0x4], V11 = Values[0x5], V12 = Values[0x6], V13 = Values[0x7],
                 V20 = Values[0x8], V21 = Values[0x9], V22 = Values[0xA], V23 = Values[0xB],
                 V30 = Values[0xC], V31 = Values[0xD], V32 = Values[0xE], V33 = Values[0xF]
             };
         }
References Juniper.Mathematics.Matrix4x4Serializable.Values.
Referenced by Juniper.Mathematics.Matrix4x4Serializable.operator Accord.Math.Matrix4x4().
ToSystemMatrix4x4()
System.Numerics.Matrix4x4 Juniper.Mathematics.Matrix4x4Serializable.ToSystemMatrix4x4 () inline
Definition at line 76 of file Matrix4x4Serializable.cs.
         {
             return new System.Numerics.Matrix4x4(
                 Values[0x0], Values[0x1], Values[0x2], Values[0x3],
                 Values[0x4], Values[0x5], Values[0x6], Values[0x7],
                 Values[0x8], Values[0x9], Values[0xA], Values[0xB],
                 Values[0xC], Values[0xD], Values[0xE], Values[0xF]);
         }
References Juniper.Mathematics.Matrix4x4Serializable.Values.
Referenced by Juniper.Mathematics.Matrix4x4Serializable.operator System.Numerics.Matrix4x4().
Member Data Documentation
VALUES_FIELD
readonly string Juniper.Mathematics.Matrix4x4Serializable.VALUES_FIELD = nameof(Values).ToLowerInvariant() static private
Definition at line 11 of file Matrix4x4Serializable.cs.
Referenced by Juniper.Mathematics.Matrix4x4Serializable.GetObjectData(), and Juniper.Mathematics.Matrix4x4Serializable.Matrix4x4Serializable().
Property Documentation
Values
float [] Juniper.Mathematics.Matrix4x4Serializable.Values get
Definition at line 13 of file Matrix4x4Serializable.cs.
 { get; }
Referenced by Juniper.Mathematics.Matrix4x4Serializable.Equals(), Juniper.Mathematics.Matrix4x4Serializable.GetHashCode(), Juniper.Mathematics.Matrix4x4Serializable.GetObjectData(), Juniper.Mathematics.Matrix4x4Serializable.Matrix4x4Serializable(), Juniper.Mathematics.Matrix4x4Serializable.ToAccordMatrix4x4(), Juniper.Mathematics.Matrix4x4Serializable.ToSystemMatrix4x4(), and Juniper.Mathematics.MathExt.ToUnityMatrix4x4().
The documentation for this struct was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Mathematics/Matrix4x4Serializable.cs