Juniper: Juniper.XR.CustomEditors.XRSystemEditor Class Reference
Juniper.XR.CustomEditors.XRSystemEditor Class Reference
An editor to respond to changes in XRSystem.
Static Public Member Functions
static bool SetAndroid_MenuItem_Validate ()
static void SetAndroid_MenuItem ()
static bool SetAndroid_ARCore_MenuItem_Validate ()
static void SetAndroid_ARCore_MenuItem ()
static bool SetAndroid_Cardboard_MenuItem_Validate ()
static void SetAndroid_Cardboard_MenuItem ()
static bool SetAndroid_Daydream_MenuItem_Validate ()
static void SetAndroid_Daydream_MenuItem ()
static bool SetAndroid_Oculus_MenuItem_Validate ()
static void SetAndroid_Oculus_MenuItem ()
static bool SetAndroid_ViveFocus_MenuItem_Validate ()
static void SetAndroid_ViveFocus_MenuItem ()
static bool SetIOS_MenuItem_Validate ()
static void SetIOS_MenuItem ()
static bool SetIOS_ARKit_MenuItem_Validate ()
static void SetIOS_ARKit_MenuItem ()
static bool SetIOS_Cardboard_MenuItem_Validate ()
static void SetIOS_Cardboard_MenuItem ()
static bool SetStandalone_MenuItem_Validate ()
static void SetStandalone_MenuItem ()
static bool SetStandalone_Oculus_MenuItem_Validate ()
static void SetStandalone_Oculus_MenuItem ()
static bool SetStandalone_SteamVR_MenuItem_Validate ()
static void SetStandalone_SteamVR_MenuItem ()
static bool SetUWP_MenuItem_Validate ()
static void SetUWP_MenuItem ()
static bool SetUWP_WindowsMR_MenuItem_Validate ()
static void SetUWP_WindowsMR_MenuItem ()
static bool SetUWP_HoloLens_MenuItem_Validate ()
static void SetUWP_HoloLens_MenuItem ()
static bool SetMagicLeap_MenuItem_Validate ()
static void SetMagicLeap_MenuItem ()
static void ClearProgressDialog_MenuItem ()
static void Other_ResetConfiguration ()
static bool Other_ResumeBuild_Validate ()
static void Other_ResumeBuild ()
static void Other_Recompile_Menu ()
static void RefreshPackages ()
static void ActivatePlatform ()
static void PrepareScene ()
Properties
static int BuildProgress [get, set]
static PlatformTypes NextPlatform [get, set]
Static Private Member Functions
static XRSystemEditor ()
static bool Config_PlatformChanged ()
static string ThirdPartyDefines (BuildTargetGroup targetGroup)
static bool MenuCheck (PlatformTypes p)
static void Uninstall ()
static void Install ()
static void OnCancel ()
static void OnCancel (bool canceledByUser)
static void OnEditorUpdate (Action resolve, Action reject=null, Func< bool > test=null)
static void DelayedUpdate (IProgressReceiver prog, float maxTime, Action onComplete)
static List< string > FormatDefines (ref string definesString)
static IProgressReceiver PrepareBuildStep (int offset, string prefix=null)
static void WithProgress (string prefix, Action< IProgressReceiver > act)
static void Recompile (bool advanceBuildStep, string nextDefinesString=null)
static void RecompilePlatformInternal ()
static IEnumerable< IInstallable > GetInstallables ()
static void ResumeBuild ()
static void StartBuild ()
static void DeactivatePlatform ()
Private Attributes
const string MENU_NAME = "Juniper/"
const string ANDROID_MENU_NAME = MENU_NAME + "Android/"
const string IOS_MENU_NAME = MENU_NAME + "IOS/"
const string STANDALONE_MENU_NAME = MENU_NAME + "Standalone/"
const string UWP_MENU_NAME = MENU_NAME + "UWP/"
const string OTHER_MENU_NAME = MENU_NAME + "Other/"
const string RECOMPILE_SLUG = "RECOMPILE_SLUG"
Static Private Attributes
static readonly ProjectConfiguration config
static PlatformTypes CurrentPlatform
static PlatformTypes DesiredPlatform
static bool BuildInProgress
static bool RebuildNeeded
static PlatformConfiguration LastConfiguration
static PlatformConfiguration NextConfiguration
static string [] JUNIPER_DEFINES
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
static string LastPrefix
static readonly Action [] STAGES
static readonly string MANIFEST_FILE = PathExt.FixPath("Packages/manifest.json")
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 23 of file XRSystemEditor.cs.
Constructor & Destructor Documentation
XRSystemEditor()
static Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor () inline static private
Definition at line 29 of file XRSystemEditor.cs.
         {
             config = ProjectConfiguration.Load();
             config.PlatformChanged += Config_PlatformChanged;
             config.PlatformChangeConfirmed += StartBuild;
             if (RebuildNeeded)
             {
                 OnEditorUpdate(() =>
                     NextPlatform = DesiredPlatform,
                     () => EditorUtility.DisplayDialog("Juniper", "Could not change platform.", "OK"));
             }
         }
References Juniper.XR.CustomEditors.XRSystemEditor.config, Juniper.XR.CustomEditors.XRSystemEditor.Config_PlatformChanged(), Juniper.XR.CustomEditors.XRSystemEditor.DesiredPlatform, Juniper.XR.CustomEditors.ProjectConfiguration.Load(), Juniper.XR.CustomEditors.XRSystemEditor.NextPlatform, Juniper.XR.CustomEditors.XRSystemEditor.OnEditorUpdate(), Juniper.XR.CustomEditors.ProjectConfiguration.PlatformChangeConfirmed, Juniper.XR.CustomEditors.ProjectConfiguration.PlatformChanged, Juniper.XR.CustomEditors.XRSystemEditor.RebuildNeeded, and Juniper.XR.CustomEditors.XRSystemEditor.StartBuild().
Member Function Documentation
ActivatePlatform()
static void Juniper.XR.CustomEditors.XRSystemEditor.ActivatePlatform () static
ClearProgressDialog_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.ClearProgressDialog_MenuItem () static
Config_PlatformChanged()
static bool Juniper.XR.CustomEditors.XRSystemEditor.Config_PlatformChanged () inline static private
Definition at line 69 of file XRSystemEditor.cs.
         {
             if (!Platforms.Instance.PlatformDB[config.NextPlatform].IsSupported)
             {
                 EditorUtility.DisplayDialog(
                    "Juniper",
                    $"The platform {config.NextPlatform} is not supported on your current system.",
                    "OK");
                 return false;
             }
             else
             {
                 return config.NextPlatform == PlatformTypes.None
                     || (config.NextPlatform != CurrentPlatform
                         && EditorUtility.DisplayDialog(
                             "Juniper",
                             $"You are about to change the platfrom from {CurrentPlatform} to {config.NextPlatform}. Do you want to continue?",
                             "Change platform",
                             "Don't change platform"));
             }
         }
References Juniper.XR.CustomEditors.XRSystemEditor.config, Juniper.XR.CustomEditors.XRSystemEditor.CurrentPlatform, Juniper.XR.CustomEditors.Platforms.Instance, Juniper.XR.CustomEditors.ProjectConfiguration.NextPlatform, and Juniper.XR.CustomEditors.Platforms.PlatformDB.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor().
DeactivatePlatform()
static void Juniper.XR.CustomEditors.XRSystemEditor.DeactivatePlatform () static private
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.StartBuild().
DelayedUpdate()
static void Juniper.XR.CustomEditors.XRSystemEditor.DelayedUpdate (IProgressReceiver prog, float maxTime, Action onComplete) inline static private
Definition at line 356 of file XRSystemEditor.cs.
         {
             prog?.SetProgress(0);
             var startTime = DateTime.Now;
             OnEditorUpdate(() =>
             {
                 EditorUtility.ClearProgressBar();
                 onComplete();
             }, OnCancel, () =>
             {
                 var age = (float)(DateTime.Now - startTime).TotalSeconds;
                 prog?.SetProgress(age, maxTime);
                 return age > maxTime;
             });
         }
References Juniper.XR.CustomEditors.XRSystemEditor.OnCancel(), Juniper.XR.CustomEditors.XRSystemEditor.OnEditorUpdate(), and Juniper.Progress.IProgressReceiver.SetProgress().
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Recompile().
FormatDefines()
static List<string> Juniper.XR.CustomEditors.XRSystemEditor.FormatDefines (ref string definesString) inline static private
Definition at line 372 of file XRSystemEditor.cs.
         {
             var defines = definesString?.Split(';')?.ToList() ?? new List<string>();
             defines.Sort();
             // move the slug to the end, if it exists
             if (defines.Contains(RECOMPILE_SLUG))
             {
                 defines.Remove(RECOMPILE_SLUG);
                 defines.Add(RECOMPILE_SLUG);
             }
             definesString = string.Join(";", defines);
             return defines;
         }
References Juniper.XR.CustomEditors.XRSystemEditor.RECOMPILE_SLUG.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Recompile().
GetInstallables()
static IEnumerable<IInstallable> Juniper.XR.CustomEditors.XRSystemEditor.GetInstallables () static private
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Install().
Install()
static void Juniper.XR.CustomEditors.XRSystemEditor.Install () inline static private
Definition at line 282 of file XRSystemEditor.cs.
         {
             Uninstall();
             XRSystem.Ensure();
             Installable.InstallAll(GetInstallables);
         }
References Juniper.XRSystem.Ensure(), Juniper.XR.CustomEditors.XRSystemEditor.GetInstallables(), Juniper.Installable.InstallAll(), and Juniper.XR.CustomEditors.XRSystemEditor.Uninstall().
MenuCheck()
static bool Juniper.XR.CustomEditors.XRSystemEditor.MenuCheck (PlatformTypes p) static private
OnCancel() [1/2]
static void Juniper.XR.CustomEditors.XRSystemEditor.OnCancel () static private
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.DelayedUpdate(), and Juniper.XR.CustomEditors.XRSystemEditor.WithProgress().
OnCancel() [2/2]
static void Juniper.XR.CustomEditors.XRSystemEditor.OnCancel (bool canceledByUser) inline static private
Definition at line 318 of file XRSystemEditor.cs.
         {
             if (canceledByUser)
             {
                 Debug.LogWarning("Canceled by user");
             }
             EditorUtility.ClearProgressBar();
             BuildProgress = -1;
         }
References Juniper.XR.CustomEditors.XRSystemEditor.BuildProgress.
OnEditorUpdate()
static void Juniper.XR.CustomEditors.XRSystemEditor.OnEditorUpdate (Action resolve, Action reject = null, Func< bool > test = null) inline static private
Definition at line 328 of file XRSystemEditor.cs.
         {
             if (test == null)
             {
                 test = () => true;
             }
             EditorApplication.CallbackFunction exec = null;
             exec = () =>
             {
                 if (test())
                 {
                     try
                     {
                         EditorApplication.update -= exec;
                         resolve();
                     }
                     catch (OperationCanceledException)
                     {
                         EditorApplication.update -= exec;
                         reject();
                     }
                 }
             };
             EditorApplication.update += exec;
         }
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.DelayedUpdate(), and Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor().
Other_Recompile_Menu()
static void Juniper.XR.CustomEditors.XRSystemEditor.Other_Recompile_Menu () static
Other_ResetConfiguration()
static void Juniper.XR.CustomEditors.XRSystemEditor.Other_ResetConfiguration () static
Other_ResumeBuild()
static void Juniper.XR.CustomEditors.XRSystemEditor.Other_ResumeBuild () static
Other_ResumeBuild_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.Other_ResumeBuild_Validate () static
PrepareBuildStep()
static IProgressReceiver Juniper.XR.CustomEditors.XRSystemEditor.PrepareBuildStep (int offset, string prefix = null) inline static private
Definition at line 390 of file XRSystemEditor.cs.
         {
             LastPrefix = prefix ?? LastPrefix;
             var step = BuildProgress - offset + 1;
             var msg = $"Juniper ({step} of {STAGES.Length}): {LastPrefix}";
             return new UnityEditorProgressDialog(msg)
                 .Subdivide(step + BuildProgress, 2 * STAGES.Length, LastPrefix);
         }
References Juniper.XR.CustomEditors.XRSystemEditor.BuildProgress, Juniper.XR.CustomEditors.XRSystemEditor.LastPrefix, and Juniper.XR.CustomEditors.XRSystemEditor.STAGES.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Recompile(), and Juniper.XR.CustomEditors.XRSystemEditor.WithProgress().
PrepareScene()
static void Juniper.XR.CustomEditors.XRSystemEditor.PrepareScene () static
Recompile()
static void Juniper.XR.CustomEditors.XRSystemEditor.Recompile (bool advanceBuildStep, string nextDefinesString = null) inline static private
Definition at line 417 of file XRSystemEditor.cs.
         {
             if (advanceBuildStep)
             {
                 ++BuildProgress;
             }
             var targetGroup = BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget);
             var prog = PrepareBuildStep(1);
             var currentDefinesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);
             var currentDefines = FormatDefines(ref currentDefinesString);
             var nextDefines = FormatDefines(ref nextDefinesString);
             if (nextDefines.Matches(currentDefines))
             {
                 if (nextDefines.Contains(RECOMPILE_SLUG))
                 {
                     nextDefines.Remove(RECOMPILE_SLUG);
                 }
                 else
                 {
                     nextDefines.Add(RECOMPILE_SLUG);
                 }
             }
             nextDefines.RemoveAll(string.IsNullOrWhiteSpace);
             nextDefinesString = string.Join(";", nextDefines);
             PlayerSettings.SetScriptingDefineSymbolsForGroup(targetGroup, nextDefinesString);
             DelayedUpdate(prog, 30, () => Debug.LogWarning("Timeout!!!"));
         }
References Juniper.XR.CustomEditors.XRSystemEditor.BuildProgress, Juniper.XR.CustomEditors.XRSystemEditor.DelayedUpdate(), Juniper.XR.CustomEditors.XRSystemEditor.FormatDefines(), Juniper.XR.CustomEditors.XRSystemEditor.PrepareBuildStep(), and Juniper.XR.CustomEditors.XRSystemEditor.RECOMPILE_SLUG.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.RecompilePlatformInternal().
RecompilePlatformInternal()
static void Juniper.XR.CustomEditors.XRSystemEditor.RecompilePlatformInternal () inline static private
Definition at line 449 of file XRSystemEditor.cs.
         {
             var newDefinesString = ThirdPartyDefines(NextConfiguration.TargetGroup);
             var newDefines = newDefinesString.Split(';').ToList();
             newDefines.MaybeAddRange(NextConfiguration.CompilerDefines);
             Recompile(false, string.Join(";", newDefines));
         }
References Juniper.XR.CustomEditors.PlatformConfiguration.CompilerDefines, Juniper.XR.CustomEditors.XRSystemEditor.NextConfiguration, Juniper.XR.CustomEditors.XRSystemEditor.Recompile(), Juniper.XR.CustomEditors.PlatformConfiguration.TargetGroup, and Juniper.XR.CustomEditors.XRSystemEditor.ThirdPartyDefines().
RefreshPackages()
static void Juniper.XR.CustomEditors.XRSystemEditor.RefreshPackages () static
ResumeBuild()
static void Juniper.XR.CustomEditors.XRSystemEditor.ResumeBuild () inline static private
Definition at line 471 of file XRSystemEditor.cs.
         {
             if (BuildInProgress)
             {
                 STAGES[BuildProgress].Invoke();
             }
         }
References Juniper.XR.CustomEditors.XRSystemEditor.BuildInProgress, Juniper.XR.CustomEditors.XRSystemEditor.BuildProgress, and Juniper.XR.CustomEditors.XRSystemEditor.STAGES.
SetAndroid_ARCore_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_ARCore_MenuItem () static
SetAndroid_ARCore_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_ARCore_MenuItem_Validate () static
SetAndroid_Cardboard_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_Cardboard_MenuItem () static
SetAndroid_Cardboard_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_Cardboard_MenuItem_Validate () static
SetAndroid_Daydream_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_Daydream_MenuItem () static
SetAndroid_Daydream_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_Daydream_MenuItem_Validate () static
SetAndroid_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_MenuItem () static
SetAndroid_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_MenuItem_Validate () static
SetAndroid_Oculus_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_Oculus_MenuItem () static
SetAndroid_Oculus_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_Oculus_MenuItem_Validate () static
SetAndroid_ViveFocus_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_ViveFocus_MenuItem () static
SetAndroid_ViveFocus_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetAndroid_ViveFocus_MenuItem_Validate () static
SetIOS_ARKit_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetIOS_ARKit_MenuItem () static
SetIOS_ARKit_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetIOS_ARKit_MenuItem_Validate () static
SetIOS_Cardboard_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetIOS_Cardboard_MenuItem () static
SetIOS_Cardboard_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetIOS_Cardboard_MenuItem_Validate () static
SetIOS_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetIOS_MenuItem () static
SetIOS_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetIOS_MenuItem_Validate () static
SetMagicLeap_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetMagicLeap_MenuItem () static
SetMagicLeap_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetMagicLeap_MenuItem_Validate () static
SetStandalone_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetStandalone_MenuItem () static
SetStandalone_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetStandalone_MenuItem_Validate () static
SetStandalone_Oculus_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetStandalone_Oculus_MenuItem () static
SetStandalone_Oculus_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetStandalone_Oculus_MenuItem_Validate () static
SetStandalone_SteamVR_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetStandalone_SteamVR_MenuItem () static
SetStandalone_SteamVR_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetStandalone_SteamVR_MenuItem_Validate () static
SetUWP_HoloLens_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetUWP_HoloLens_MenuItem () static
SetUWP_HoloLens_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetUWP_HoloLens_MenuItem_Validate () static
SetUWP_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetUWP_MenuItem () static
SetUWP_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetUWP_MenuItem_Validate () static
SetUWP_WindowsMR_MenuItem()
static void Juniper.XR.CustomEditors.XRSystemEditor.SetUWP_WindowsMR_MenuItem () static
SetUWP_WindowsMR_MenuItem_Validate()
static bool Juniper.XR.CustomEditors.XRSystemEditor.SetUWP_WindowsMR_MenuItem_Validate () static
StartBuild()
static void Juniper.XR.CustomEditors.XRSystemEditor.StartBuild () inline static private
Definition at line 481 of file XRSystemEditor.cs.
         {
             BuildProgress = 0;
             DeactivatePlatform();
         }
References Juniper.XR.CustomEditors.XRSystemEditor.BuildProgress, and Juniper.XR.CustomEditors.XRSystemEditor.DeactivatePlatform().
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor().
ThirdPartyDefines()
static string Juniper.XR.CustomEditors.XRSystemEditor.ThirdPartyDefines (BuildTargetGroup targetGroup) inline static private
Definition at line 104 of file XRSystemEditor.cs.
         {
             var oldDefinesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);
             var oldDefines = oldDefinesString.Split(';');
             var newDefines = oldDefines.Exclude(JUNIPER_DEFINES);
             return string.Join(";", newDefines);
         }
References Juniper.XR.CustomEditors.XRSystemEditor.JUNIPER_DEFINES.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.RecompilePlatformInternal().
Uninstall()
static void Juniper.XR.CustomEditors.XRSystemEditor.Uninstall () static private
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Install().
WithProgress()
static void Juniper.XR.CustomEditors.XRSystemEditor.WithProgress (string prefix, Action< IProgressReceiver > act) inline static private
Definition at line 399 of file XRSystemEditor.cs.
         {
             try
             {
                 var prog = PrepareBuildStep(0, prefix);
                 prog.SetProgress(0);
                 act(prog);
             }
             catch (OperationCanceledException)
             {
                 OnCancel();
             }
             catch (Exception exp)
             {
                 Debug.LogException(exp);
             }
         }
References Juniper.XR.CustomEditors.XRSystemEditor.OnCancel(), and Juniper.XR.CustomEditors.XRSystemEditor.PrepareBuildStep().
Member Data Documentation
ANDROID_MENU_NAME
const string Juniper.XR.CustomEditors.XRSystemEditor.ANDROID_MENU_NAME = MENU_NAME + "Android/" private
Definition at line 116 of file XRSystemEditor.cs.
BuildInProgress
bool Juniper.XR.CustomEditors.XRSystemEditor.BuildInProgress static private
Initial value:
=>
            0 <= BuildProgress && BuildProgress < STAGES.Length
Definition at line 56 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.ResumeBuild().
config
readonly ProjectConfiguration Juniper.XR.CustomEditors.XRSystemEditor.config static private
Definition at line 27 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Config_PlatformChanged(), and Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor().
CurrentPlatform
PlatformTypes Juniper.XR.CustomEditors.XRSystemEditor.CurrentPlatform static private
Initial value:
=>
            XRSystem.CURRENT_PLATFORM
Definition at line 50 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Config_PlatformChanged().
DesiredPlatform
PlatformTypes Juniper.XR.CustomEditors.XRSystemEditor.DesiredPlatform static private
Initial value:
=>
            config.CurrentPlatform
Definition at line 53 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor().
IOS_MENU_NAME
const string Juniper.XR.CustomEditors.XRSystemEditor.IOS_MENU_NAME = MENU_NAME + "IOS/" private
Definition at line 173 of file XRSystemEditor.cs.
JUNIPER_DEFINES
string [] Juniper.XR.CustomEditors.XRSystemEditor.JUNIPER_DEFINES static private
Initial value:
=>
            Platforms.Instance.AllCompilerDefines
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
Definition at line 101 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.ThirdPartyDefines().
LastConfiguration
PlatformConfiguration Juniper.XR.CustomEditors.XRSystemEditor.LastConfiguration static private
Initial value:
=>
            Platforms.Instance.PlatformDB.Get(CurrentPlatform)
Definition at line 91 of file XRSystemEditor.cs.
LastPrefix
string Juniper.XR.CustomEditors.XRSystemEditor.LastPrefix static private
Definition at line 388 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.PrepareBuildStep().
MANIFEST_FILE
readonly string Juniper.XR.CustomEditors.XRSystemEditor.MANIFEST_FILE = PathExt.FixPath("Packages/manifest.json") static private
Definition at line 479 of file XRSystemEditor.cs.
MENU_NAME
const string Juniper.XR.CustomEditors.XRSystemEditor.MENU_NAME = "Juniper/" private
Definition at line 25 of file XRSystemEditor.cs.
NextConfiguration
PlatformConfiguration Juniper.XR.CustomEditors.XRSystemEditor.NextConfiguration static private
Initial value:
=>
            Platforms.Instance.PlatformDB.Get(NextPlatform)
Definition at line 94 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.RecompilePlatformInternal().
OTHER_MENU_NAME
const string Juniper.XR.CustomEditors.XRSystemEditor.OTHER_MENU_NAME = MENU_NAME + "Other/" private
Definition at line 275 of file XRSystemEditor.cs.
RebuildNeeded
bool Juniper.XR.CustomEditors.XRSystemEditor.RebuildNeeded static private
Initial value:
=>
            DesiredPlatform != CurrentPlatform && !BuildInProgress
Definition at line 59 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor().
RECOMPILE_SLUG
const string Juniper.XR.CustomEditors.XRSystemEditor.RECOMPILE_SLUG = "RECOMPILE_SLUG" private
Definition at line 314 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.FormatDefines(), and Juniper.XR.CustomEditors.XRSystemEditor.Recompile().
STAGES
readonly Action [] Juniper.XR.CustomEditors.XRSystemEditor.STAGES static private
Initial value:
=
        {
            DeactivatePlatform,
            RefreshPackages,
            ActivatePlatform,
            PrepareScene
        }
Definition at line 462 of file XRSystemEditor.cs.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.PrepareBuildStep(), and Juniper.XR.CustomEditors.XRSystemEditor.ResumeBuild().
STANDALONE_MENU_NAME
const string Juniper.XR.CustomEditors.XRSystemEditor.STANDALONE_MENU_NAME = MENU_NAME + "Standalone/" private
Definition at line 203 of file XRSystemEditor.cs.
UWP_MENU_NAME
const string Juniper.XR.CustomEditors.XRSystemEditor.UWP_MENU_NAME = MENU_NAME + "UWP/" private
Definition at line 233 of file XRSystemEditor.cs.
Property Documentation
BuildProgress
int Juniper.XR.CustomEditors.XRSystemEditor.BuildProgress static get set private
Definition at line 44 of file XRSystemEditor.cs.
         {
             get { return config.BuildStep; }
             set { config.BuildStep = value; }
         }
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.OnCancel(), Juniper.XR.CustomEditors.XRSystemEditor.PrepareBuildStep(), Juniper.XR.CustomEditors.XRSystemEditor.Recompile(), Juniper.XR.CustomEditors.XRSystemEditor.ResumeBuild(), and Juniper.XR.CustomEditors.XRSystemEditor.StartBuild().
NextPlatform
PlatformTypes Juniper.XR.CustomEditors.XRSystemEditor.NextPlatform static get set private
Definition at line 63 of file XRSystemEditor.cs.
         {
             get { return config.NextPlatform; }
             set { config.NextPlatform = value; }
         }
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.XRSystemEditor().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/XR/XRSystemEditor.cs