Juniper: Juniper.Compression.Tar.TarArchive Class Reference
Juniper.Compression.Tar.TarArchive Class Reference
Public Member Functions
TarArchive (Stream stream)
TarArchiveEntry GetEntry (string name)
void Decompress (DirectoryInfo outputDirectory, bool overwrite, IProgress prog=null)
void Decompress (DirectoryInfo outputDirectory, bool overwrite=true, string entryPrefix=null, IProgress prog=null)
void Dispose ()
Public Attributes
IReadOnlyCollection< TarArchiveEntry > Entries => entries
Private Member Functions
void Dispose (bool disposing)
Static Private Member Functions
static long SeekToNextEntry (byte[] header, Stream stream, long position, string fileName)
static bool IsAllZeros (byte[] header)
static bool IsFileType (byte[] header)
static string AddFilePrefix (byte[] header, string fileName)
static DateTimeOffset ReadLastModifiedTime (byte[] header, string fileName)
static long ReadFileSize (byte[] header, string fileName)
static void ValidateChecksum (byte[] header, string fileName)
static string GetString (byte[] buffer, int index, int count)
Gets an ASCII string ending by a \0
static ? long ReadOctal (byte[] buffer, int index, int count)
Reads an octal number converted to integer.
Private Attributes
readonly List< TarArchiveEntry > entries
bool disposedValue = false
Static Private Attributes
static readonly DateTimeOffset Epoch = new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero)
Detailed Description
Definition at line 10 of file TarArchive.cs.
Constructor & Destructor Documentation
TarArchive()
Juniper.Compression.Tar.TarArchive.TarArchive (Stream stream) inline
Definition at line 178 of file TarArchive.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             entries = new List<TarArchiveEntry>();
             var header = new byte[512];
             var zeroBlockCount = 0;
             var position = 0L;
             while (zeroBlockCount < 2)
             {
                 var length = stream.Read(header, 0, header.Length);
                 if (length < 512)
                 {
                     throw new InvalidDataException($"Invalid header block size < 512");
                 }
                 position += length;
                 if (IsAllZeros(header))
                 {
                     ++zeroBlockCount;
                 }
                 else
                 {
                     zeroBlockCount = 0;
                     var fileName = GetString(header, 0, 100);
                     ValidateChecksum(header, fileName);
                     var fileLength = ReadFileSize(header, fileName);
                     if (IsFileType(header))
                     {
                         var lastModifiedTime = ReadLastModifiedTime(header, fileName);
                         fileName = AddFilePrefix(header, fileName);
                         var entry = new TarArchiveEntry(stream, fileName, lastModifiedTime.DateTime.ToLocalTime(), fileLength);
                         position += fileLength;
                         position = SeekToNextEntry(header, stream, position, fileName);
                         entries.Add(entry);
                     }
                 }
             }
         }
References Juniper.Compression.Tar.TarArchive.AddFilePrefix(), Juniper.Compression.Tar.TarArchive.entries, Juniper.Compression.Tar.TarArchive.GetString(), Juniper.Compression.Tar.TarArchive.IsAllZeros(), Juniper.Compression.Tar.TarArchive.IsFileType(), Juniper.Compression.Tar.TarArchive.ReadFileSize(), Juniper.Compression.Tar.TarArchive.ReadLastModifiedTime(), Juniper.Compression.Tar.TarArchive.SeekToNextEntry(), and Juniper.Compression.Tar.TarArchive.ValidateChecksum().
Member Function Documentation
AddFilePrefix()
static string Juniper.Compression.Tar.TarArchive.AddFilePrefix (byte [] header, string fileName) inline static private
Definition at line 48 of file TarArchive.cs.
         {
             // Double check magic ustar to load prefix filename
             var ustar = GetString(header, 257, Units.Bits.PER_BYTE);
             // Check for ustar only
             if (ustar.Trim() == "ustar")
             {
                 var prefixFileName = GetString(header, 345, 155);
                 fileName = prefixFileName + fileName;
             }
             return fileName;
         }
References Juniper.Compression.Tar.TarArchive.GetString().
Referenced by Juniper.Compression.Tar.TarArchive.TarArchive().
Decompress() [1/2]
void Juniper.Compression.Tar.TarArchive.Decompress (DirectoryInfo outputDirectory, bool overwrite, IProgress prog = null) inline
Definition at line 241 of file TarArchive.cs.
         {
             Decompress(outputDirectory, overwrite, null, prog);
         }
Decompress() [2/2]
void Juniper.Compression.Tar.TarArchive.Decompress (DirectoryInfo outputDirectory, bool overwrite = true, string entryPrefix = null, IProgress prog = null) inline
Definition at line 246 of file TarArchive.cs.
         {
             if (outputDirectory is null)
             {
                 throw new ArgumentNullException(nameof(outputDirectory));
             }
             entryPrefix ??= string.Empty;
             for (var i = 0; i < entries.Count; ++i)
             {
                 prog.Report(i, entries.Count);
                 try
                 {
                     var entry = entries[i];
                     var fileName = entry.FullName;
                     if (fileName.StartsWith(entryPrefix, StringComparison.InvariantCulture))
                     {
                         if (entryPrefix != null)
{
                             fileName = fileName.Remove(0, entryPrefix.Length);
                         }
                         var outputPath = Path.Combine(outputDirectory.FullName, fileName);
                         var outputFile = new FileInfo(outputPath);
                         var outputFileDirectory = outputFile.Directory;
                         if (overwrite || !outputFile.Exists)
{
                             outputFileDirectory.Create();
                             using var outputStream = outputFile.Create();
                             using var inputStream = entry.Open();
                             inputStream.CopyTo(outputStream);
                         }
                     }
                 }
                 catch { }
                 prog.Report(i + 1, entries.Count);
             }
         }
References Juniper.Compression.Tar.TarArchive.entries.
Dispose() [1/2]
void Juniper.Compression.Tar.TarArchive.Dispose (bool disposing) inline private
Definition at line 287 of file TarArchive.cs.
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     foreach (var entry in entries)
                     {
                         entry.Dispose();
                     }
                     entries.Clear();
                 }
                 disposedValue = true;
             }
         }
References Juniper.Compression.Tar.TarArchive.disposedValue, and Juniper.Compression.Tar.TarArchive.entries.
Referenced by Juniper.Compression.Tar.TarArchiveEntryStream.Dispose().
Dispose() [2/2]
void Juniper.Compression.Tar.TarArchive.Dispose () inline
Definition at line 305 of file TarArchive.cs.
         {
             Dispose(true);
         }
GetEntry()
TarArchiveEntry Juniper.Compression.Tar.TarArchive.GetEntry (string name) inline
Definition at line 228 of file TarArchive.cs.
         {
             foreach (var entry in Entries)
             {
                 if (entry.FullName == name)
                 {
                     return entry;
                 }
             }
             return null;
         }
References Juniper.Compression.Tar.TarArchive.Entries.
GetString()
static string Juniper.Compression.Tar.TarArchive.GetString (byte [] buffer, int index, int count) inline static private
Gets an ASCII string ending by a \0
Parameters
buffer The buffer.
index The index.
count The count.
Returns
A string
Definition at line 121 of file TarArchive.cs.
         {
             var text = new StringBuilder();
             for (var i = index; i < index + count; i++)
             {
                 if (buffer[i] == 0 || buffer[i] >= 127)
                 {
                     break;
                 }
                 text.Append((char)buffer[i]);
             }
             return text.ToString();
         }
Referenced by Juniper.Compression.Tar.TarArchive.AddFilePrefix(), and Juniper.Compression.Tar.TarArchive.TarArchive().
IsAllZeros()
static bool Juniper.Compression.Tar.TarArchive.IsAllZeros (byte [] header) inline static private
Definition at line 30 of file TarArchive.cs.
         {
             for (var i = 0; i < header.Length; i++)
             {
                 if (header[i] != 0)
                 {
                     return false;
                 }
             }
             return true;
         }
Referenced by Juniper.Compression.Tar.TarArchive.TarArchive().
IsFileType()
static bool Juniper.Compression.Tar.TarArchive.IsFileType (byte [] header) inline static private
Definition at line 43 of file TarArchive.cs.
         {
             return header[156] == '0';
         }
Referenced by Juniper.Compression.Tar.TarArchive.TarArchive().
ReadFileSize()
static long Juniper.Compression.Tar.TarArchive.ReadFileSize (byte [] header, string fileName) inline static private
Definition at line 73 of file TarArchive.cs.
         {
             var fileSizeRead = ReadOctal(header, 124, 12);
             if (!fileSizeRead.HasValue)
             {
                 throw new InvalidDataException($"Invalid filesize for file entry [{fileName}] ");
             }
             var fileLength = fileSizeRead.Value;
             return fileLength;
         }
References Juniper.Compression.Tar.TarArchive.ReadOctal().
Referenced by Juniper.Compression.Tar.TarArchive.TarArchive().
ReadLastModifiedTime()
static DateTimeOffset Juniper.Compression.Tar.TarArchive.ReadLastModifiedTime (byte [] header, string fileName) inline static private
Definition at line 62 of file TarArchive.cs.
         {
             var unixTimeStamp = ReadOctal(header, 136, 12);
             if (!unixTimeStamp.HasValue)
             {
                 throw new InvalidDataException($"Invalid timestamp for file entry [{fileName}] ");
             }
             return Epoch.AddSeconds(unixTimeStamp.Value);
         }
References Juniper.Compression.Tar.TarArchive.Epoch, and Juniper.Compression.Tar.TarArchive.ReadOctal().
Referenced by Juniper.Compression.Tar.TarArchive.TarArchive().
ReadOctal()
static ? long Juniper.Compression.Tar.TarArchive.ReadOctal (byte [] buffer, int index, int count) inline static private
Reads an octal number converted to integer.
Parameters
buffer The buffer.
index The index.
count The count.
Returns
An octal number converted to a long; otherwise null if the conversion failed
Definition at line 144 of file TarArchive.cs.
         {
             long value = 0;
             for (var i = index; i < index + count; i++)
             {
                 var c = buffer[i];
                 if (c == 0)
                 {
                     break;
                 }
                 if (c == ' ')
                 {
                     continue;
                 }
                 if (c < '0' || c > '7')
                 {
                     return null;
                 }
                 value = (value << 3) + (c - '0');
             }
             return value;
         }
Referenced by Juniper.Compression.Tar.TarArchive.ReadFileSize(), Juniper.Compression.Tar.TarArchive.ReadLastModifiedTime(), and Juniper.Compression.Tar.TarArchive.ValidateChecksum().
SeekToNextEntry()
static long Juniper.Compression.Tar.TarArchive.SeekToNextEntry (byte [] header, Stream stream, long position, string fileName) inline static private
Definition at line 14 of file TarArchive.cs.
         {
             // The end of the file entry is aligned on 512 bytes
             var delta = (512 - (int)(position & 511)) % 512;
             if (delta > 0)
             {
                 var read = stream.Read(header, 0, delta);
                 if (read < delta)
                 {
                     throw new InvalidDataException($"Invalid end of entry after file entry [{fileName}] ");
                 }
             }
             return position + delta;
         }
Referenced by Juniper.Compression.Tar.TarArchive.TarArchive().
ValidateChecksum()
static void Juniper.Compression.Tar.TarArchive.ValidateChecksum (byte [] header, string fileName) inline static private
Definition at line 85 of file TarArchive.cs.
         {
             // read checksum
             var checksum = ReadOctal(header, 148, Units.Bits.PER_BYTE);
             if (!checksum.HasValue)
             {
                 throw new InvalidDataException($"Invalid checksum for file entry [{fileName}] ");
             }
             // verify checksum
             uint checksumVerif = 0;
             for (var i = 0; i < header.Length; i++)
             {
                 var c = header[i];
                 if (i >= 148 && i < (148 + Units.Bits.PER_BYTE))
                 {
                     c = Units.Bits.PER_INT;
                 }
                 checksumVerif += c;
             }
             // Checksum is invalid, exit
             if (checksum.Value != checksumVerif)
             {
                 throw new InvalidDataException($"Invalid checksum verification for file entry [{fileName}] ");
             }
         }
References Juniper.Compression.Tar.TarArchive.ReadOctal().
Referenced by Juniper.Compression.Tar.TarArchive.TarArchive().
Member Data Documentation
disposedValue
bool Juniper.Compression.Tar.TarArchive.disposedValue = false private
Definition at line 176 of file TarArchive.cs.
Referenced by Juniper.Compression.Tar.TarArchive.Dispose().
entries
readonly List<TarArchiveEntry> Juniper.Compression.Tar.TarArchive.entries private
Definition at line 174 of file TarArchive.cs.
Referenced by Juniper.Compression.Tar.TarArchive.Decompress(), Juniper.Compression.Tar.TarArchive.Dispose(), and Juniper.Compression.Tar.TarArchive.TarArchive().
Entries
IReadOnlyCollection<TarArchiveEntry> Juniper.Compression.Tar.TarArchive.Entries => entries
Definition at line 226 of file TarArchive.cs.
Referenced by Juniper.Compression.Tar.TarArchive.GetEntry().
Epoch
readonly DateTimeOffset Juniper.Compression.Tar.TarArchive.Epoch = new DateTimeOffset(1970, 1, 1, 0, 0, 0, TimeSpan.Zero) static private
Definition at line 172 of file TarArchive.cs.
Referenced by Juniper.Compression.Tar.TarArchive.ReadLastModifiedTime().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Compression/Tar/TarArchive.cs