Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster Class Reference
Master control module
Public Member Functions
JpegDecompMaster (JpegDecompressStruct cinfo)
void PrepareForOutputPass ()
Per-pass setup. This is called at the beginning of each output pass. We determine which modules will be active during this pass and give them appropriate start_pass calls. We also set is_dummy_pass to indicate whether this is a "real" output pass or a dummy pass for color quantization. (In the latter case, we will crank the pass to completion.)
void FinishOutputPass ()
Finish up at end of an output pass.
bool IsDummyPass ()
Private Member Functions
void MasterSelection ()
void PrepareRangeLimitTable ()
Private Attributes
readonly JpegDecompressStruct m_cinfo
int m_pass_number
bool m_is_dummy_pass
bool m_using_merged_upsample
IJpegColorQuantizer m_quantizer_1pass
IJpegColorQuantizer m_quantizer_2pass
Detailed Description
Master control module
Definition at line 13 of file JpegDecompMaster.cs.
Constructor & Destructor Documentation
JpegDecompMaster()
BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.JpegDecompMaster (JpegDecompressStruct cinfo) inline
Definition at line 28 of file JpegDecompMaster.cs.
         {
             m_cinfo = cinfo;
             MasterSelection();
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_cinfo, and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection().
Member Function Documentation
FinishOutputPass()
void BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass () inline
Finish up at end of an output pass.
Definition at line 108 of file JpegDecompMaster.cs.
         {
             if (m_cinfo.quantizeColors)
             {
                 m_cinfo.m_cquantize.FinishPass();
             }
             m_pass_number++;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cquantize, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_pass_number, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup().
IsDummyPass()
bool BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.IsDummyPass () inline
Definition at line 118 of file JpegDecompMaster.cs.
         {
             return m_is_dummy_pass;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_is_dummy_pass.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup().
MasterSelection()
void BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection () inline private
Master selection of decompression modules. This is done once at jpeg_start_decompress time. We determine which modules will be used and give them appropriate initialization calls. We also initialize the decompressor input side to begin consuming data.
Since jpeg_read_header has finished, we know what is in the SOF and (first) SOS markers. We also have all the application parameter settings.
Definition at line 136 of file JpegDecompMaster.cs.
         {
             /* For now, precision must match compiled-in value... */
             if (m_cinfo.m_dataPrecision != JpegConstants.BITS_IN_JSAMPLE)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_PRECISION, m_cinfo.m_dataPrecision);
             }
             /* Initialize dimensions and other stuff */
             m_cinfo.JpegCalcOutputDimensions();
             PrepareRangeLimitTable();
             /* Sanity check on image dimensions */
             if (m_cinfo.outputHeight <= 0 || m_cinfo.outputWidth <= 0 ||
                 m_cinfo.outColorComponents <= 0)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_EMPTY_IMAGE);
             }
             /* Width of an output scanline must be representable as int. */
             long samplesperrow = m_cinfo.outputWidth * m_cinfo.outColorComponents;
             var jd_samplesperrow = (int)samplesperrow;
             if (jd_samplesperrow != samplesperrow)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_WIDTH_OVERFLOW);
             }
             /* Initialize my private state */
             m_pass_number = 0;
             m_using_merged_upsample = m_cinfo.UseMergedUpSample();
             /* Color quantizer selection */
             m_quantizer_1pass = null;
             m_quantizer_2pass = null;
             /* No mode changes if not using buffered-image mode. */
             if (!m_cinfo.quantizeColors || !m_cinfo.bufferedImage)
             {
                 m_cinfo.enable1PassQuant = false;
                 m_cinfo.enableExternalQuant = false;
                 m_cinfo.enable2PassQuant = false;
             }
             if (m_cinfo.quantizeColors)
             {
                 if (m_cinfo.rawDataOut)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
                 }
                 /* 2-pass quantizer only works in 3-component color space. */
                 if (m_cinfo.outColorComponents != 3)
                 {
                     m_cinfo.enable1PassQuant = true;
                     m_cinfo.enableExternalQuant = false;
                     m_cinfo.enable2PassQuant = false;
                     m_cinfo.m_colormap = null;
                 }
                 else if (m_cinfo.m_colormap is object)
                 {
                     m_cinfo.enableExternalQuant = true;
                 }
                 else if (m_cinfo.twoPassQuantize)
                 {
                     m_cinfo.enable2PassQuant = true;
                 }
                 else
                 {
                     m_cinfo.enable1PassQuant = true;
                 }
                 if (m_cinfo.enable1PassQuant)
                 {
                     m_cinfo.m_cquantize = new My1PassCQuantizer(m_cinfo);
                     m_quantizer_1pass = m_cinfo.m_cquantize;
                 }
                 /* We use the 2-pass code to map to external colormaps. */
                 if (m_cinfo.enable2PassQuant || m_cinfo.enableExternalQuant)
                 {
                     m_cinfo.m_cquantize = new My2PassCQuantizer(m_cinfo);
                     m_quantizer_2pass = m_cinfo.m_cquantize;
                 }
                 /* If both quantizers are initialized, the 2-pass one is left active;
                  * this is necessary for starting with quantization to an external map.
                  */
             }
             /* Post-processing: in particular, color conversion first */
             if (!m_cinfo.rawDataOut)
             {
                 if (m_using_merged_upsample)
                 {
                     /* does color conversion too */
                     m_cinfo.m_upsample = new MyMergedUpSampler(m_cinfo);
                 }
                 else
                 {
                     m_cinfo.m_cconvert = new JpegColorDeconverter(m_cinfo);
                     m_cinfo.m_upsample = new MyUpSampler(m_cinfo);
                 }
                 m_cinfo.m_post = new JpegDPostController(m_cinfo, m_cinfo.enable2PassQuant);
             }
             /* Inverse DCT */
             m_cinfo.m_idct = new JpegInverseDct(m_cinfo);
             if (m_cinfo.arithCode)
             {
                 m_cinfo.m_entropy = new ArithEntropyDecoder(m_cinfo);
             }
             else
             {
                 m_cinfo.m_entropy = new HuffmanEntropyDecoder(m_cinfo);
             }
             /* Initialize principal buffer controllers. */
             var use_c_buffer = m_cinfo.m_inputctl.HasMultipleScans() || m_cinfo.bufferedImage;
             m_cinfo.m_coef = new JpegDCoefController(m_cinfo, use_c_buffer);
             if (!m_cinfo.rawDataOut)
             {
                 m_cinfo.m_main = new JpegDMainController(m_cinfo);
             }
             /* Initialize input side of decompressor to consume first scan. */
             m_cinfo.m_inputctl.StartInputPass();
             /* If jpeg_start_decompress will read the whole file, initialize
              * progress monitoring appropriately.  The input step is counted
              * as one pass.
              */
             if (m_cinfo.prog is object && !m_cinfo.bufferedImage && m_cinfo.m_inputctl.HasMultipleScans())
             {
                 /* Estimate number of scans to set pass_limit. */
                 int nscans;
                 if (m_cinfo.progressiveMode)
                 {
                     /* Arbitrarily estimate 2 interleaved DC scans + 3 AC scans/component. */
                     nscans = 2 + (3 * m_cinfo.numComponents);
                 }
                 else
                 {
                     /* For a non progressive multiscan file, estimate 1 scan per component. */
                     nscans = m_cinfo.numComponents;
                 }
                 m_cinfo.prog.PassCounter = 0;
                 m_cinfo.prog.PassLimit = m_cinfo.m_total_iMCU_rows * nscans;
                 m_cinfo.prog.CompletedPasses = 0;
                 m_cinfo.prog.TotalPasses = (m_cinfo.enable2PassQuant ? 3 : 2);
                 /* Count the input pass as done */
                 m_pass_number++;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithCode, BitMiracle.LibJpeg.Classic.JpegConstants.BITS_IN_JSAMPLE, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable1PassQuant, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable2PassQuant, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enableExternalQuant, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cconvert, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_colormap, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cquantize, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dataPrecision, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_idct, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_main, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_pass_number, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_post, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_quantizer_1pass, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_quantizer_2pass, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_total_iMCU_rows, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_upsample, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_using_merged_upsample, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareRangeLimitTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.progressiveMode, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.rawDataOut, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.twoPassQuantize, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.UseMergedUpSample().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.JpegDecompMaster().
PrepareForOutputPass()
void BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass () inline
Per-pass setup. This is called at the beginning of each output pass. We determine which modules will be active during this pass and give them appropriate start_pass calls. We also set is_dummy_pass to indicate whether this is a "real" output pass or a dummy pass for color quantization. (In the latter case, we will crank the pass to completion.)
Definition at line 42 of file JpegDecompMaster.cs.
         {
             if (m_is_dummy_pass)
             {
                 /* Final pass of 2-pass quantization */
                 m_is_dummy_pass = false;
                 m_cinfo.m_cquantize.StartPass(false);
                 m_cinfo.m_post.StartPass(JBufMode.CrankDest);
                 m_cinfo.m_main.StartPass(JBufMode.CrankDest);
             }
             else
             {
                 if (m_cinfo.quantizeColors && m_cinfo.m_colormap is null)
                 {
                     /* Select new quantization method */
                     if (m_cinfo.twoPassQuantize && m_cinfo.enable2PassQuant)
                     {
                         m_cinfo.m_cquantize = m_quantizer_2pass;
                         m_is_dummy_pass = true;
                     }
                     else if (m_cinfo.enable1PassQuant)
                     {
                         m_cinfo.m_cquantize = m_quantizer_1pass;
                     }
                     else
                     {
                         m_cinfo.ErrExit(JMessageCode.JERR_MODE_CHANGE);
                     }
                 }
                 m_cinfo.m_idct.StartPass();
                 m_cinfo.m_coef.StartOutputPass();
                 if (!m_cinfo.rawDataOut)
                 {
                     m_cinfo.m_upsample.StartPass();
                     if (m_cinfo.quantizeColors)
                     {
                         m_cinfo.m_cquantize.StartPass(m_is_dummy_pass);
                     }
                     m_cinfo.m_post.StartPass(m_is_dummy_pass ? JBufMode.SaveAndPass : JBufMode.PassThrough);
                     m_cinfo.m_main.StartPass(JBufMode.PassThrough);
                 }
             }
             /* Set up progress monitor's pass info if present */
             if (m_cinfo.prog is object)
             {
                 m_cinfo.prog.CompletedPasses = m_pass_number;
                 m_cinfo.prog.TotalPasses = m_pass_number + (m_is_dummy_pass ? 2 : 1);
                 /* In buffered-image mode, we assume one more output pass if EOI not
                  * yet reached, but no more passes if EOI has been reached.
                  */
                 if (m_cinfo.bufferedImage && !m_cinfo.m_inputctl.EOIReached())
                 {
                     m_cinfo.prog.TotalPasses += (m_cinfo.enable2PassQuant ? 2 : 1);
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.bufferedImage, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable1PassQuant, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.enable2PassQuant, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_colormap, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cquantize, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_idct, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_inputctl, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_is_dummy_pass, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_main, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_pass_number, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_post, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_quantizer_1pass, BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_quantizer_2pass, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_upsample, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.rawDataOut, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.twoPassQuantize.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup().
PrepareRangeLimitTable()
void BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareRangeLimitTable () inline private
Allocate and fill in the sample_range_limit table.
Several decompression processes need to range-limit values to the range 0..MAXJSAMPLE; the input value may fall somewhat outside this range due to noise introduced by quantization, roundoff error, etc. These processes are inner loops and need to be as fast as possible. On most machines, particularly CPUs with pipelines or instruction prefetch, a (subscript-check-less) C table lookup x = sample_range_limit[x]; is faster than explicit tests if (x & 0) x = 0; else if (x > MAXJSAMPLE) x = MAXJSAMPLE; These processes all use a common table prepared by the routine below.
For most steps we can mathematically guarantee that the initial value of x is within 2*(MAXJSAMPLE+1) of the legal range, so a table running from -2*(MAXJSAMPLE+1) to 3*MAXJSAMPLE+2 is sufficient.But for the initial limiting step(just after the IDCT), a wildly out-of-range value is possible if the input data is corrupt.To avoid any chance of indexing off the end of memory and getting a bad-pointer trap, we perform the post-IDCT limiting thus: x = (sample_range_limit - SUBSET)[(x + CENTER) & MASK]; where MASK is 2 bits wider than legal sample data, ie 10 bits for 8-bit samples. Under normal circumstances this is more than enough range and a correct output will be generated; with bogus input data the mask will cause wraparound, and we will safely generate a bogus-but-in-range output. For the post-IDCT step, we want to convert the data from signed to unsigned representation by adding CENTERJSAMPLE at the same time that we limit it. This is accomplished with SUBSET = CENTER - CENTERJSAMPLE.
Note that the table is allocated in near data space on PCs; it's small enough and used often enough to justify this.
Definition at line 335 of file JpegDecompMaster.cs.
         {
             var table = new byte[5 * (JpegConstants.MAXJSAMPLE + 1)];
             /* First segment of range limit table: limit[x] = 0 for x < 0 */
             /* allow negative subscripts of simple table */
             const int tableOffset = 2 * (JpegConstants.MAXJSAMPLE + 1);
             m_cinfo.m_sample_range_limit = table;
             m_cinfo.m_sampleRangeLimitOffset = tableOffset;
             /* Main part of range limit table: limit[x] = x */
             int i;
             for (i = 0; i <= JpegConstants.MAXJSAMPLE; i++)
             {
                 table[tableOffset + i] = (byte)i;
             }
             /* End of range limit table: limit[x] = MAXJSAMPLE for x > MAXJSAMPLE */
             for (; i < 3 * (JpegConstants.MAXJSAMPLE + 1); i++)
             {
                 table[tableOffset + i] = JpegConstants.MAXJSAMPLE;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sample_range_limit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sampleRangeLimitOffset, and BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection().
Member Data Documentation
m_cinfo
readonly JpegDecompressStruct BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_cinfo private
Definition at line 15 of file JpegDecompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.JpegDecompMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareRangeLimitTable().
m_is_dummy_pass
bool BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_is_dummy_pass private
Definition at line 18 of file JpegDecompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.IsDummyPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
m_pass_number
int BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_pass_number private
Definition at line 17 of file JpegDecompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.FinishOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
m_quantizer_1pass
IJpegColorQuantizer BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_quantizer_1pass private
Definition at line 25 of file JpegDecompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
m_quantizer_2pass
IJpegColorQuantizer BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_quantizer_2pass private
Definition at line 26 of file JpegDecompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), and BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass().
m_using_merged_upsample
bool BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.m_using_merged_upsample private
Definition at line 20 of file JpegDecompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegDecompMaster.cs