Juniper: Juniper.XR.CustomEditors.PlatformConfiguration Class Reference
Juniper.XR.CustomEditors.PlatformConfiguration Class Reference
Public Member Functions
PlatformConfiguration ()
bool SwitchTarget ()
void InstallUnityPackages (IProgressReceiver prog=null)
void InstallRawPackages (IProgressReceiver prog=null)
void Activate (IProgressReceiver prog)
void UninstallRawPackages (IProgressReceiver prog=null)
void UninstallUnityPackages (IProgressReceiver prog=null)
Public Attributes
string Name
string CompilerDefine
string buildTarget
string [] vrSystems
string [] packages
BuildTargetGroup TargetGroup => BuildPipeline.GetBuildTargetGroup(BuildTarget)
bool IsSupported => BuildPipeline.IsBuildTargetSupported(TargetGroup, BuildTarget)
IEnumerable< UnityXRPlatforms > XRPlatforms
Properties
BuildTarget BuildTarget [get]
UnityPackage [] UninstallableUnityPackages [get, set]
UnityPackage [] IncludedUnityPackages [get, set]
UnityPackage [] ExcludedUnityPackages [get, set]
RawPackage [] UninstallableRawPackages [get, set]
RawPackage [] RawPackages [get, set]
List< string > CompilerDefines [get]
Private Member Functions
internal void Deactivate (PlatformConfiguration nextConfiguration, string thirdPartyDefines)
Detailed Description
Definition at line 17 of file PlatformConfiguration.cs.
Constructor & Destructor Documentation
PlatformConfiguration()
Juniper.XR.CustomEditors.PlatformConfiguration.PlatformConfiguration () inline
Definition at line 25 of file PlatformConfiguration.cs.
         {
             Name = null;
             CompilerDefine = null;
             buildTarget = null;
             vrSystems = null;
             packages = null;
         }
References Juniper.XR.CustomEditors.PlatformConfiguration.buildTarget, Juniper.XR.CustomEditors.PlatformConfiguration.CompilerDefine, Juniper.XR.CustomEditors.PlatformConfiguration.Name, Juniper.XR.CustomEditors.PlatformConfiguration.packages, and Juniper.XR.CustomEditors.PlatformConfiguration.vrSystems.
Member Function Documentation
Activate()
void Juniper.XR.CustomEditors.PlatformConfiguration.Activate (IProgressReceiver prog) inline
Definition at line 124 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(IncludedUnityPackages, progs[0], (pkg, p) => pkg.Activate(TargetGroup, p));
             Platforms.ForEachPackage(RawPackages, progs[1], (pkg, p) => pkg.Activate(TargetGroup, p));
             var supportedVRSDKs = PlayerSettings.GetAvailableVirtualRealitySDKs(TargetGroup);
             var vrSDKs = XRPlatforms
                 .Distinct()
                 .Select(x => x.ToString())
                 .Where(supportedVRSDKs.Contains)
                 .ToArray();
             var enableVR = vrSDKs.Any(sdk => sdk != "None");
             if (enableVR != PlayerSettings.GetVirtualRealitySupported(TargetGroup))
             {
                 PlayerSettings.SetVirtualRealitySupported(TargetGroup, enableVR);
                 if (enableVR && !vrSDKs.Matches(PlayerSettings.GetVirtualRealitySDKs(TargetGroup)))
                 {
                     PlayerSettings.SetVirtualRealitySDKs(TargetGroup, vrSDKs);
                 }
             }
             if (BuildTarget == BuildTarget.WSAPlayer)
             {
                 EditorUserBuildSettings.wsaBuildAndRunDeployTarget = WSABuildAndRunDeployTarget.LocalMachine;
                 EditorUserBuildSettings.wsaUWPBuildType = WSAUWPBuildType.D3D;
                 PlayerSettings.WSA.inputSource = PlayerSettings.WSAInputSource.IndependentInputSource;
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.InternetClient, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.WebCam, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Bluetooth, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Microphone, ComponentExt.FindAny<KeywordRecognizer>() != null);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Location, ComponentExt.FindAny<GPSLocation>() != null);
             }
         }
References Juniper.XR.CustomEditors.AbstractPackage.Activate(), Juniper.XR.CustomEditors.RawPackage.Activate(), Juniper.XR.CustomEditors.PlatformConfiguration.BuildTarget, Juniper.XR.CustomEditors.PlatformConfiguration.IncludedUnityPackages, Juniper.XR.CustomEditors.PlatformConfiguration.RawPackages, Juniper.XR.CustomEditors.PlatformConfiguration.TargetGroup, and Juniper.XR.CustomEditors.PlatformConfiguration.XRPlatforms.
Deactivate()
internal void Juniper.XR.CustomEditors.PlatformConfiguration.Deactivate (PlatformConfiguration nextConfiguration, string thirdPartyDefines) inline private
Definition at line 201 of file PlatformConfiguration.cs.
         {
             AudioSettings.SetSpatializerPluginName(null);
             AudioSettingsExt.SetAmbisonicDecoderPluginName(null);
             PlayerSettings.virtualRealitySupported = false;
             PlayerSettings.Android.androidTVCompatibility = false;
 #if UNITY_2018_2_OR_NEWER
             PlayerSettings.Android.ARCoreEnabled = false;
 #endif
             PlayerSettingsExt.iOS.RequiresARKitSupport = false;
             PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
             if (nextConfiguration.TargetGroup != TargetGroup)
             {
                 PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
                 PlayerSettings.SetScriptingDefineSymbolsForGroup(TargetGroup, thirdPartyDefines);
             }
         }
References UnityEditor.PlayerSettingsExt.iOS.RequiresARKitSupport, UnityEditor.AudioSettingsExt.SetAmbisonicDecoderPluginName(), and Juniper.XR.CustomEditors.PlatformConfiguration.TargetGroup.
InstallRawPackages()
void Juniper.XR.CustomEditors.PlatformConfiguration.InstallRawPackages (IProgressReceiver prog = null)
InstallUnityPackages()
void Juniper.XR.CustomEditors.PlatformConfiguration.InstallUnityPackages (IProgressReceiver prog = null) inline
Definition at line 108 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(ExcludedUnityPackages, progs[0], (pkg, p) =>
 #if UNITY_2018_2_OR_NEWER
                 pkg.Uninstall(p)
 #else
                 pkg.Install(p)
 #endif
             );
             Platforms.ForEachPackage(IncludedUnityPackages, progs[1], (pkg, p) => pkg.Install(p));
         }
References Juniper.XR.CustomEditors.PlatformConfiguration.ExcludedUnityPackages, Juniper.XR.CustomEditors.PlatformConfiguration.IncludedUnityPackages, Juniper.XR.CustomEditors.UnityPackage.Install(), and Juniper.XR.CustomEditors.UnityPackage.Uninstall().
SwitchTarget()
bool Juniper.XR.CustomEditors.PlatformConfiguration.SwitchTarget () inline
Definition at line 94 of file PlatformConfiguration.cs.
         {
             if (BuildTarget != EditorUserBuildSettings.activeBuildTarget)
             {
                 Debug.Log($"Switching build target from {EditorUserBuildSettings.activeBuildTarget} to {BuildTarget}.");
                 EditorUserBuildSettings.SwitchActiveBuildTargetAsync(TargetGroup, BuildTarget);
                 return true;
             }
             else
             {
                 return false;
             }
         }
References Juniper.XR.CustomEditors.PlatformConfiguration.BuildTarget, and Juniper.XR.CustomEditors.PlatformConfiguration.TargetGroup.
UninstallRawPackages()
void Juniper.XR.CustomEditors.PlatformConfiguration.UninstallRawPackages (IProgressReceiver prog = null)
UninstallUnityPackages()
void Juniper.XR.CustomEditors.PlatformConfiguration.UninstallUnityPackages (IProgressReceiver prog = null)
Member Data Documentation
buildTarget
string Juniper.XR.CustomEditors.PlatformConfiguration.buildTarget
Definition at line 21 of file PlatformConfiguration.cs.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.PlatformConfiguration().
CompilerDefine
string Juniper.XR.CustomEditors.PlatformConfiguration.CompilerDefine
Definition at line 20 of file PlatformConfiguration.cs.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.PlatformConfiguration().
IsSupported
bool Juniper.XR.CustomEditors.PlatformConfiguration.IsSupported => BuildPipeline.IsBuildTargetSupported(TargetGroup, BuildTarget)
Definition at line 72 of file PlatformConfiguration.cs.
Name
string Juniper.XR.CustomEditors.PlatformConfiguration.Name
Definition at line 19 of file PlatformConfiguration.cs.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.PlatformConfiguration().
packages
string [] Juniper.XR.CustomEditors.PlatformConfiguration.packages
Definition at line 23 of file PlatformConfiguration.cs.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.PlatformConfiguration().
TargetGroup
BuildTargetGroup Juniper.XR.CustomEditors.PlatformConfiguration.TargetGroup => BuildPipeline.GetBuildTargetGroup(BuildTarget)
Definition at line 69 of file PlatformConfiguration.cs.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.Activate(), Juniper.XR.CustomEditors.PlatformConfiguration.Deactivate(), Juniper.XR.CustomEditors.XRSystemEditor.RecompilePlatformInternal(), and Juniper.XR.CustomEditors.PlatformConfiguration.SwitchTarget().
vrSystems
string [] Juniper.XR.CustomEditors.PlatformConfiguration.vrSystems
Definition at line 22 of file PlatformConfiguration.cs.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.PlatformConfiguration().
XRPlatforms
IEnumerable<UnityXRPlatforms> Juniper.XR.CustomEditors.PlatformConfiguration.XRPlatforms
Initial value:
=>
            from sys in vrSystems
            select (UnityXRPlatforms)Enum.Parse(typeof(UnityXRPlatforms), sys)
Definition at line 75 of file PlatformConfiguration.cs.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.Activate().
Property Documentation
BuildTarget
BuildTarget Juniper.XR.CustomEditors.PlatformConfiguration.BuildTarget get
Definition at line 36 of file PlatformConfiguration.cs.
         {
             get
             {
                 var localBuildTarget = buildTarget;
                 if (localBuildTarget == "Standalone")
                 {
 #if UNITY_EDITOR_WIN
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows);
                     }
 #elif UNITY_EDITOR_OSX
                     localBuildTarget = nameof(BuildTarget.StandaloneOSX);
 #else
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux);
                     }
 #endif
                 }
                 return (BuildTarget)Enum.Parse(typeof(BuildTarget), localBuildTarget);
             }
         }
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.Activate(), and Juniper.XR.CustomEditors.PlatformConfiguration.SwitchTarget().
CompilerDefines
List<string> Juniper.XR.CustomEditors.PlatformConfiguration.CompilerDefines get
Definition at line 167 of file PlatformConfiguration.cs.
         {
             get
             {
                 var defines = Platforms.GetCompilerDefines(IncludedUnityPackages, RawPackages).ToList();
                 if (!string.IsNullOrEmpty(CompilerDefine))
                 {
                     defines.Add(CompilerDefine);
                 }
                 if (TargetGroup == BuildTargetGroup.Android)
                 {
                     for (var i = (int)PlayerSettings.Android.minSdkVersion; i > 0; --i)
                     {
                         if (Enum.IsDefined(typeof(AndroidSdkVersions), i))
{
                             defines.Add("ANDROID_API_" + i);
                             defines.Add("ANDROID_API_" + i + "_OR_GREATER");
                         }
                     }
                 }
                 else if (TargetGroup == BuildTargetGroup.iOS)
                 {
                     for (var i = PlayerSettingsExt.iOS.TargetOSVersion.Major; i > 0; --i)
                     {
                         defines.Add("IOS_VERSION_" + i);
                         defines.Add("IOS_VERSION_" + i + "_OR_GREATER");
                     }
                 }
                 return defines;
             }
         }
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.RecompilePlatformInternal().
ExcludedUnityPackages
UnityPackage [] Juniper.XR.CustomEditors.PlatformConfiguration.ExcludedUnityPackages get set
Definition at line 86 of file PlatformConfiguration.cs.
 { get; internal set; }
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.InstallUnityPackages().
IncludedUnityPackages
UnityPackage [] Juniper.XR.CustomEditors.PlatformConfiguration.IncludedUnityPackages get set
Definition at line 83 of file PlatformConfiguration.cs.
 { get; internal set; }
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.Activate(), and Juniper.XR.CustomEditors.PlatformConfiguration.InstallUnityPackages().
RawPackages
RawPackage [] Juniper.XR.CustomEditors.PlatformConfiguration.RawPackages get set
Definition at line 92 of file PlatformConfiguration.cs.
 { get; internal set; }
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.Activate().
UninstallableRawPackages
RawPackage [] Juniper.XR.CustomEditors.PlatformConfiguration.UninstallableRawPackages get set
Definition at line 89 of file PlatformConfiguration.cs.
 { get; internal set; }
UninstallableUnityPackages
UnityPackage [] Juniper.XR.CustomEditors.PlatformConfiguration.UninstallableUnityPackages get set
Definition at line 80 of file PlatformConfiguration.cs.
 { get; internal set; }
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Unity/Editor/Juniper/XR/PlatformConfiguration.cs