Juniper: Juniper.Avatar Class Reference
Juniper.Avatar Class Reference
Public Member Functions
virtual void Awake ()
virtual void Reinstall ()
Reinstall the object with a full reset.
void Install (bool reset)
Install, with or without a full reset.
void Uninstall ()
Remove platform-specific features from the object.
void RotateView (Quaternion dQuat, float minX=-180, float maxX=180)
void SetPosition (Vector3 position)
void SetViewRotation (Quaternion quat, float minX=-180, float maxX=180)
void FixedUpdate ()
Static Public Member Functions
static void Ensure ()
Public Attributes
float defaultAvatarHeight
When running on systems that do not understand the relationship between the camera and the ground (marker-tracking AR, 3DOF VR), this is the height that is used for the camera off of the ground.
PhysicMaterial shoes
A friction material for the player's avatar.
Rigidbody BodyPhysics
Physics for the avatar's body.
Transform GroundPlane
Properties
Vector3 UserTop [get]
Vector3 UserBottom [get]
Vector3 LocalUserTop [get]
float AvatarHeight [get]
Tells us where to put the stage. This will be the defaultAvatarHeight on 3DOF systems, and 0 on 6DOF systems;
Vector3 FullUp [get]
float HalfHeight [get]
Vector3 HalfUp [get]
Vector3 LocalUserCenter [get]
Vector3 UserCenter [get]
Transform Head [get, private set]
Transform Hands [get, private set]
bool IndependentHead [get, set]
Vector3 Velocity [get, set]
Private Member Functions
GameObject MakeBody ()
GameObject MakeGoogles ()
void DestroyGrounder ()
void SetBodyPositionAndShape ()
Static Private Member Functions
static void SetCasters (Renderer[] casters)
static GameObject MakeShadowCaster (PrimitiveType type, Vector3? scale)
static GameObject MakeHead ()
Private Attributes
CapsuleCollider bodyShape
Transform avatar
Transform shoulders
Transform neck
Transform pivot
Transform headShadow
Transform body
bool isIndependentHead
Grounded grounder
Vector3 velocity
Detailed Description
Definition at line 15 of file Avatar.cs.
Member Function Documentation
Awake()
virtual void Juniper.Avatar.Awake () inline virtual
Definition at line 194 of file Avatar.cs.
         {
             Install(false);
             SetCasters(headShadow.GetComponentsInChildren<Renderer>());
             SetCasters(body.GetComponentsInChildren<Renderer>());
         }
References Juniper.Avatar.body, Juniper.Avatar.headShadow, Juniper.Avatar.Install(), and Juniper.Avatar.SetCasters().
DestroyGrounder()
void Juniper.Avatar.DestroyGrounder () inline private
Definition at line 358 of file Avatar.cs.
         {
             grounder.GroundFound -= DestroyGrounder;
             grounder.DestroyImmediate();
             grounder = null;
 #if UNITY_MODULES_PHYSICS
             BodyPhysics.useGravity = true;
             BodyPhysics.isKinematic = false;
             BodyPhysics.velocity = Vector3.zero;
 #endif
         }
References Juniper.Avatar.BodyPhysics, Juniper.Avatar.grounder, and Juniper.Anchoring.Grounded.GroundFound.
Referenced by Juniper.Avatar.Install().
Ensure()
static void Juniper.Avatar.Ensure () inline static
Definition at line 17 of file Avatar.cs.
         {
             if (Find.Any(out JuniperSystem sys))
             {
                 var sysT = sys.transform;
                 var head = DisplayManager.MainCamera.transform;
                 var pivot = head.EnsureParent("Pivot", sysT);
                 var neck = pivot.EnsureParent("Neck", sysT);
                 var avatar = neck.EnsureParent("Avatar", sysT);
                 var stage = avatar.EnsureParent("Stage", sysT);
                 stage.Ensure<Avatar>();
                 stage.transform.SetParent(sysT, false);
             }
         }
References Juniper.Avatar.avatar, Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.Avatar.neck, and Juniper.Avatar.pivot.
Referenced by Juniper.Display.AbstractDisplayManager.Install().
FixedUpdate()
void Juniper.Avatar.FixedUpdate () inline
Definition at line 433 of file Avatar.cs.
         {
 #if UNITY_MODULES_PHYSICS
             var acceleration = (velocity - BodyPhysics.velocity) / Time.fixedDeltaTime;
             BodyPhysics.AddForce(acceleration, ForceMode.Acceleration);
 #else
             avatar.position += velocity * Time.fixedDeltaTime;
 #endif
             SetBodyPositionAndShape();
         }
References Juniper.Avatar.avatar, Juniper.Avatar.BodyPhysics, Juniper.Avatar.SetBodyPositionAndShape(), Juniper.Units.Time, and Juniper.Avatar.velocity.
Install()
void Juniper.Avatar.Install (bool reset) inline
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IO.IInstallable.
Definition at line 242 of file Avatar.cs.
         {
             gameObject.layer = LayerMask.NameToLayer("Ignore Raycast");
             GroundPlane = transform.Find("GroundPlane");
             if(GroundPlane != null
                 && !GroundPlane.HasComponent<Collider>())
             {
                 GroundPlane.gameObject.DestroyImmediate();
                 GroundPlane = null;
             }
             if(GroundPlane == null)
             {
                 GroundPlane = GameObject.CreatePrimitive(PrimitiveType.Quad).transform;
                 GroundPlane.parent = transform;
                 GroundPlane.name = "GroundPlane";
                 GroundPlane.localScale = new Vector3(100, 100, 1);
                 GroundPlane.localRotation = Quaternion.Euler(90, 0, 0);
             }
             GroundPlane.Remove<Renderer>();
             GroundPlane.Deactivate();
             Head = DisplayManager.MainCamera.transform;
             {
                 Head.localPosition = Vector3.zero;
                 if (Head.parent == null)
                 {
                     Head.parent = new GameObject("Pivot").transform;
                 }
                 pivot = Head.parent;
                 pivot.localPosition = Vector3.zero;
                 if (pivot.parent == null)
                 {
                     pivot.parent = new GameObject("Neck").transform;
                 }
                 neck = pivot.parent;
                 neck.localPosition = defaultAvatarHeight * Vector3.up;
                 if (neck.parent == null)
                 {
                     neck.parent = new GameObject("Avatar").transform;
                 }
                 avatar = neck.parent;
                 avatar.localPosition = Vector3.zero;
                 if (avatar.parent != transform)
                 {
                     avatar.parent = transform;
                 }
                 headShadow = Head.Ensure<Transform>("HeadShadow", new Func<GameObject>(MakeHead));
                 var goggles = headShadow.Ensure<Transform>("Goggles", new Func<GameObject>(MakeGoogles));
                 goggles.Value.localPosition = new Vector3(0, 0, 0.311f);
                 shoulders = avatar.Ensure<Transform>("Shoulders");
                 {
                     Hands = shoulders.Ensure<Transform>("Hands");
                     body = shoulders.Ensure<Transform>("Body", new Func<GameObject>(MakeBody));
 #if UNITY_MODULES_PHYSICS
                     var bs = shoulders.Ensure<CapsuleCollider>();
                     if (bs.IsNew)
                     {
                         bs.Value.SetMaterial(shoes);
                         bs.Value.height = AvatarHeight;
                         bs.Value.radius = 0.25f;
                         bs.Value.direction = (int)CartesianAxis.Y;
                     }
                     bodyShape = bs;
 #endif
                 }
             }
 #if UNITY_MODULES_PHYSICS
             var bp = avatar.Ensure<Rigidbody>();
             if (bp.IsNew)
             {
                 bp.Value.mass = 80;
                 bp.Value.constraints = RigidbodyConstraints.FreezeRotation;
             }
             BodyPhysics = bp;
             BodyPhysics.useGravity = false;
             BodyPhysics.isKinematic = true;
             BodyPhysics.velocity = Vector3.zero;
             BodyPhysics.Ensure<RunningMovement>();
             grounder = avatar.Ensure<Grounded>();
             grounder.GroundFound += DestroyGrounder;
 #endif
             SetBodyPositionAndShape();
         }
References Juniper.Avatar.avatar, Juniper.Avatar.AvatarHeight, Juniper.Avatar.body, Juniper.Avatar.BodyPhysics, Juniper.Avatar.bodyShape, Juniper.Avatar.defaultAvatarHeight, Juniper.Avatar.DestroyGrounder(), Juniper.Avatar.grounder, Juniper.Anchoring.Grounded.GroundFound, Juniper.Avatar.GroundPlane, Juniper.Avatar.Hands, Juniper.Avatar.Head, Juniper.Avatar.headShadow, Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.Avatar.MakeBody(), Juniper.Avatar.MakeGoogles(), Juniper.Avatar.MakeHead(), Juniper.Avatar.neck, Juniper.Avatar.pivot, Juniper.Avatar.SetBodyPositionAndShape(), Juniper.Avatar.shoes, and Juniper.Avatar.shoulders.
Referenced by Juniper.Avatar.Awake(), Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Avatar.Reinstall().
MakeBody()
GameObject Juniper.Avatar.MakeBody () inline private
Definition at line 340 of file Avatar.cs.
         {
             return MakeShadowCaster(PrimitiveType.Capsule,
                 new Vector3(0.5f, HalfHeight, 0.5f));
         }
References Juniper.Avatar.HalfHeight, and Juniper.Avatar.MakeShadowCaster().
Referenced by Juniper.Avatar.Install().
MakeGoogles()
GameObject Juniper.Avatar.MakeGoogles () inline private
Definition at line 346 of file Avatar.cs.
         {
             return MakeShadowCaster(PrimitiveType.Cube,
                 new Vector3(HalfHeight, 0.5f, 0.5f));
         }
References Juniper.Avatar.HalfHeight, and Juniper.Avatar.MakeShadowCaster().
Referenced by Juniper.Avatar.Install().
MakeHead()
static GameObject Juniper.Avatar.MakeHead () inline static private
Definition at line 352 of file Avatar.cs.
         {
             return MakeShadowCaster(PrimitiveType.Sphere,
                 new Vector3(0.384284f, 0.3163f, 0.3831071f));
         }
References Juniper.Avatar.MakeShadowCaster().
Referenced by Juniper.Avatar.Install().
MakeShadowCaster()
static GameObject Juniper.Avatar.MakeShadowCaster (PrimitiveType type, Vector3? scale) inline static private
Definition at line 224 of file Avatar.cs.
         {
             var caster = GameObject.CreatePrimitive(type);
             caster.transform.localScale = scale ?? Vector3.one;
             var casterRenderer = caster.GetComponent<Renderer>();
             casterRenderer.lightProbeUsage = LightProbeUsage.Off;
             casterRenderer.reflectionProbeUsage = ReflectionProbeUsage.Off;
             casterRenderer.shadowCastingMode = ShadowCastingMode.On;
             casterRenderer.receiveShadows = false;
             casterRenderer.motionVectorGenerationMode = MotionVectorGenerationMode.ForceNoMotion;
 #if UNITY_MODULES_PHYSICS
             caster.Remove<Collider>();
 #endif
             return caster;
         }
Referenced by Juniper.Avatar.MakeBody(), Juniper.Avatar.MakeGoogles(), and Juniper.Avatar.MakeHead().
Reinstall()
virtual void Juniper.Avatar.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IO.IInstallable.
Definition at line 210 of file Avatar.cs.
         {
             Install(true);
         }
References Juniper.Avatar.Install().
RotateView()
void Juniper.Avatar.RotateView (Quaternion dQuat, float minX = -180, float maxX = 180) inline
Definition at line 386 of file Avatar.cs.
         {
             SetViewRotation(Head.rotation * dQuat, minX, maxX);
         }
References Juniper.Avatar.Head, and Juniper.Avatar.SetViewRotation().
Referenced by Juniper.Input.CameraControl.CheckMode().
SetBodyPositionAndShape()
void Juniper.Avatar.SetBodyPositionAndShape () inline private
Definition at line 371 of file Avatar.cs.
         {
             body.localScale = new Vector3(0.5f, HalfHeight, 0.5f);
 #if UNITY_MODULES_PHYSICS
             var center = LocalUserCenter;
             center.y -= AvatarHeight;
             bodyShape.center = Quaternion.Inverse(transform.rotation) * center;
             bodyShape.height = AvatarHeight;
 #endif
         }
References Juniper.Avatar.AvatarHeight, Juniper.Avatar.body, Juniper.Avatar.bodyShape, Juniper.Avatar.HalfHeight, and Juniper.Avatar.LocalUserCenter.
Referenced by Juniper.Avatar.FixedUpdate(), and Juniper.Avatar.Install().
SetCasters()
static void Juniper.Avatar.SetCasters (Renderer [] casters) inline static private
Definition at line 202 of file Avatar.cs.
         {
             foreach (var caster in casters)
             {
                 caster.shadowCastingMode = ShadowCastingMode.ShadowsOnly;
             }
         }
Referenced by Juniper.Avatar.Awake().
SetPosition()
void Juniper.Avatar.SetPosition (Vector3 position) inline
Definition at line 391 of file Avatar.cs.
         {
             transform.position = position;
         }
SetViewRotation()
void Juniper.Avatar.SetViewRotation (Quaternion quat, float minX = -180, float maxX = 180) inline
Definition at line 396 of file Avatar.cs.
         {
             var eul = quat.eulerAngles;
             avatar.localRotation = Quaternion.AngleAxis(eul.y, Vector3.up);
             var x = eul.x;
             if (x > 180)
             {
                 x -= 360;
             }
             x = Mathf.Max(minX, Mathf.Min(maxX, x));
             pivot.localRotation = Quaternion.AngleAxis(x, Vector3.right);
         }
References Juniper.Avatar.avatar, and Juniper.Avatar.pivot.
Referenced by Juniper.Input.CameraControl.CheckMode(), and Juniper.Avatar.RotateView().
Uninstall()
void Juniper.Avatar.Uninstall () inline
Remove platform-specific features from the object.
Implements Juniper.IO.IInstallable.
Definition at line 382 of file Avatar.cs.
         {
         }
Member Data Documentation
avatar
Transform Juniper.Avatar.avatar private
Definition at line 139 of file Avatar.cs.
Referenced by Juniper.Avatar.Ensure(), Juniper.Avatar.FixedUpdate(), Juniper.Avatar.Install(), and Juniper.Avatar.SetViewRotation().
body
Transform Juniper.Avatar.body private
Definition at line 163 of file Avatar.cs.
Referenced by Juniper.Avatar.Awake(), Juniper.Avatar.Install(), and Juniper.Avatar.SetBodyPositionAndShape().
BodyPhysics
Rigidbody Juniper.Avatar.BodyPhysics
Physics for the avatar's body.
Definition at line 129 of file Avatar.cs.
Referenced by Juniper.Avatar.DestroyGrounder(), Juniper.Avatar.FixedUpdate(), and Juniper.Avatar.Install().
bodyShape
CapsuleCollider Juniper.Avatar.bodyShape private
Definition at line 133 of file Avatar.cs.
Referenced by Juniper.Avatar.Install(), and Juniper.Avatar.SetBodyPositionAndShape().
defaultAvatarHeight
float Juniper.Avatar.defaultAvatarHeight
Initial value:
= (5f + 9f.Convert(UnitOfMeasure.Inches, UnitOfMeasure.Feet))
            .Convert(UnitOfMeasure.Feet, UnitOfMeasure.Meters)
When running on systems that do not understand the relationship between the camera and the ground (marker-tracking AR, 3DOF VR), this is the height that is used for the camera off of the ground.
Definition at line 39 of file Avatar.cs.
Referenced by Juniper.Avatar.Install().
grounder
Grounded Juniper.Avatar.grounder private
Definition at line 190 of file Avatar.cs.
Referenced by Juniper.Avatar.DestroyGrounder(), and Juniper.Avatar.Install().
GroundPlane
Transform Juniper.Avatar.GroundPlane
Definition at line 143 of file Avatar.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.Avatar.Install().
headShadow
Transform Juniper.Avatar.headShadow private
Definition at line 159 of file Avatar.cs.
Referenced by Juniper.Avatar.Awake(), and Juniper.Avatar.Install().
isIndependentHead
bool Juniper.Avatar.isIndependentHead private
Definition at line 175 of file Avatar.cs.
neck
Transform Juniper.Avatar.neck private
Definition at line 151 of file Avatar.cs.
Referenced by Juniper.Avatar.Ensure(), and Juniper.Avatar.Install().
pivot
Transform Juniper.Avatar.pivot private
Definition at line 155 of file Avatar.cs.
Referenced by Juniper.Avatar.Ensure(), Juniper.Avatar.Install(), and Juniper.Avatar.SetViewRotation().
shoes
PhysicMaterial Juniper.Avatar.shoes
A friction material for the player's avatar.
Definition at line 123 of file Avatar.cs.
Referenced by Juniper.Avatar.Install().
shoulders
Transform Juniper.Avatar.shoulders private
Definition at line 147 of file Avatar.cs.
Referenced by Juniper.Avatar.Install().
velocity
Vector3 Juniper.Avatar.velocity private
Definition at line 192 of file Avatar.cs.
Referenced by Juniper.Avatar.FixedUpdate().
Property Documentation
AvatarHeight
float Juniper.Avatar.AvatarHeight get private
Tells us where to put the stage. This will be the defaultAvatarHeight on 3DOF systems, and 0 on 6DOF systems;
Definition at line 71 of file Avatar.cs.
         {
             get
             {
                 return LocalUserTop.y;
             }
         }
Referenced by Juniper.Avatar.Install(), and Juniper.Avatar.SetBodyPositionAndShape().
FullUp
Vector3 Juniper.Avatar.FullUp get private
Definition at line 79 of file Avatar.cs.
         {
             get
             {
                 return AvatarHeight * Vector3.up;
             }
         }
HalfHeight
float Juniper.Avatar.HalfHeight get private
Definition at line 87 of file Avatar.cs.
         {
             get
             {
                 return 0.5f * AvatarHeight;
             }
         }
Referenced by Juniper.Avatar.MakeBody(), Juniper.Avatar.MakeGoogles(), and Juniper.Avatar.SetBodyPositionAndShape().
HalfUp
Vector3 Juniper.Avatar.HalfUp get private
Definition at line 95 of file Avatar.cs.
         {
             get
             {
                 return HalfHeight * Vector3.up;
             }
         }
Hands
Transform Juniper.Avatar.Hands get private set
Definition at line 171 of file Avatar.cs.
         {
             get; private set;
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), Juniper.Avatar.Install(), and Juniper.Input.AbstractUnifiedInputModule.MakeHandPointer< T >().
Head
Transform Juniper.Avatar.Head get private set
Definition at line 166 of file Avatar.cs.
         {
             get; private set;
         }
Referenced by Juniper.Input.CameraControl.CheckMode(), Juniper.Input.AbstractUnifiedInputModule.Install(), Juniper.Avatar.Install(), Juniper.Avatar.RotateView(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), Juniper.Input.RunningMovement.Update(), and Juniper.Imaging.PhotosphereJig.UpdatePhotosphere().
IndependentHead
bool Juniper.Avatar.IndependentHead get set
Definition at line 178 of file Avatar.cs.
         {
             get
             {
                 return isIndependentHead;
             }
             set
             {
                 isIndependentHead = value;
                 body.localPosition = -HalfUp;
             }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install().
LocalUserCenter
Vector3 Juniper.Avatar.LocalUserCenter get private
Definition at line 103 of file Avatar.cs.
         {
             get
             {
                 return LocalUserTop - HalfUp;
             }
         }
Referenced by Juniper.Avatar.SetBodyPositionAndShape().
LocalUserTop
Vector3 Juniper.Avatar.LocalUserTop get private
Definition at line 59 of file Avatar.cs.
         {
             get
             {
                 return UserTop - transform.position;
             }
         }
UserBottom
Vector3 Juniper.Avatar.UserBottom get
Definition at line 51 of file Avatar.cs.
         {
             get
             {
                 return Head.position - FullUp;
             }
         }
UserCenter
Vector3 Juniper.Avatar.UserCenter get
Definition at line 111 of file Avatar.cs.
         {
             get
             {
                 return UserTop - HalfUp;
             }
         }
UserTop
Vector3 Juniper.Avatar.UserTop get
Definition at line 43 of file Avatar.cs.
         {
             get
             {
                 return Head.position;
             }
         }
Velocity
Vector3 Juniper.Avatar.Velocity get set
Definition at line 414 of file Avatar.cs.
         {
             get
             {
                 return velocity;
             }
             set
             {
 #if UNITY_MODULES_PHYSICS
                 var falling = BodyPhysics.velocity.y;
 #endif
                 velocity = value;
 #if UNITY_MODULES_PHYSICS
                 velocity.y = falling;
 #endif
             }
         }
Referenced by Juniper.Input.RunningMovement.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Avatar.cs