Juniper: Hjg.Pngcs.Zlib.Adler32 Class Reference
Hjg.Pngcs.Zlib.Adler32 Class Reference
Public Member Functions
void Update (byte data)
void Update (byte[] data)
void Update (byte[] data, int offset, int length)
void Reset ()
UInt32 GetValue ()
Private Member Functions
void updateModulus ()
Private Attributes
UInt32 a = 1
UInt32 b = 0
const int _base = 65521
const int _nmax = 5550
int pend = 0
Detailed Description
Definition at line 7 of file Adler32.cs.
Member Function Documentation
GetValue()
UInt32 Hjg.Pngcs.Zlib.Adler32.GetValue () inline
Definition at line 53 of file Adler32.cs.
{
             if (pend > 0) updateModulus();
             return (b << 16) | a;
         }
References Hjg.Pngcs.Zlib.Adler32.a, Hjg.Pngcs.Zlib.Adler32.b, Hjg.Pngcs.Zlib.Adler32.pend, and Hjg.Pngcs.Zlib.Adler32.updateModulus().
Referenced by Hjg.Pngcs.PngReader.GetCrctestVal().
Reset()
void Hjg.Pngcs.Zlib.Adler32.Reset () inline
Definition at line 41 of file Adler32.cs.
{
             a = 1;
             b = 0;
             pend = 0;
         }
References Hjg.Pngcs.Zlib.Adler32.a, Hjg.Pngcs.Zlib.Adler32.b, and Hjg.Pngcs.Zlib.Adler32.pend.
Update() [1/3]
void Hjg.Pngcs.Zlib.Adler32.Update (byte data) inline
Definition at line 15 of file Adler32.cs.
{
             if (pend >= _nmax) updateModulus();
             a += data;
             b += a;
             pend++;
         }
References Hjg.Pngcs.Zlib.Adler32._nmax, Hjg.Pngcs.Zlib.Adler32.a, Hjg.Pngcs.Zlib.Adler32.b, Hjg.Pngcs.Zlib.Adler32.pend, and Hjg.Pngcs.Zlib.Adler32.updateModulus().
Referenced by Hjg.Pngcs.PngReader.UnfilterRow(), and Hjg.Pngcs.Zlib.Adler32.Update().
Update() [2/3]
void Hjg.Pngcs.Zlib.Adler32.Update (byte [] data) inline
Definition at line 22 of file Adler32.cs.
{
             Update(data, 0, data.Length);
         }
References Hjg.Pngcs.Zlib.Adler32.Update().
Update() [3/3]
void Hjg.Pngcs.Zlib.Adler32.Update (byte [] data, int offset, int length) inline
Definition at line 26 of file Adler32.cs.
{
             int nextJToComputeModulus = _nmax - pend;
             for (int j = 0; j < length; j++) {
                 if (j == nextJToComputeModulus) {
                     updateModulus();
                     nextJToComputeModulus = j + _nmax;
                 }
                 unchecked {
                     a += data[j + offset];
                 }
                 b += a;
                 pend++;
             }
         }
References Hjg.Pngcs.Zlib.Adler32._nmax, Hjg.Pngcs.Zlib.Adler32.a, Hjg.Pngcs.Zlib.Adler32.b, Hjg.Pngcs.Zlib.Adler32.pend, and Hjg.Pngcs.Zlib.Adler32.updateModulus().
updateModulus()
void Hjg.Pngcs.Zlib.Adler32.updateModulus () inline private
Definition at line 47 of file Adler32.cs.
{
             a %= _base;
             b %= _base;
             pend = 0;
         }
References Hjg.Pngcs.Zlib.Adler32._base, Hjg.Pngcs.Zlib.Adler32.a, Hjg.Pngcs.Zlib.Adler32.b, and Hjg.Pngcs.Zlib.Adler32.pend.
Referenced by Hjg.Pngcs.Zlib.Adler32.GetValue(), and Hjg.Pngcs.Zlib.Adler32.Update().
Member Data Documentation
_base
const int Hjg.Pngcs.Zlib.Adler32._base = 65521 private
Definition at line 10 of file Adler32.cs.
Referenced by Hjg.Pngcs.Zlib.Adler32.updateModulus().
_nmax
const int Hjg.Pngcs.Zlib.Adler32._nmax = 5550 private
Definition at line 11 of file Adler32.cs.
Referenced by Hjg.Pngcs.Zlib.Adler32.Update().
a
UInt32 Hjg.Pngcs.Zlib.Adler32.a = 1 private
Definition at line 8 of file Adler32.cs.
Referenced by Hjg.Pngcs.Zlib.Adler32.GetValue(), Hjg.Pngcs.Zlib.Adler32.Reset(), Hjg.Pngcs.Zlib.Adler32.Update(), and Hjg.Pngcs.Zlib.Adler32.updateModulus().
b
UInt32 Hjg.Pngcs.Zlib.Adler32.b = 0 private
Definition at line 9 of file Adler32.cs.
Referenced by Hjg.Pngcs.Zlib.Adler32.GetValue(), Hjg.Pngcs.Zlib.Adler32.Reset(), Hjg.Pngcs.Zlib.Adler32.Update(), and Hjg.Pngcs.Zlib.Adler32.updateModulus().
pend
int Hjg.Pngcs.Zlib.Adler32.pend = 0 private
Definition at line 12 of file Adler32.cs.
Referenced by Hjg.Pngcs.Zlib.Adler32.GetValue(), Hjg.Pngcs.Zlib.Adler32.Reset(), Hjg.Pngcs.Zlib.Adler32.Update(), and Hjg.Pngcs.Zlib.Adler32.updateModulus().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/ThirdParty/Required/Hjg.Pngcs/Zlib/Adler32.cs