Juniper: Juniper.HTTP Class Reference
Juniper.HTTP Class Reference
Perform HTTP queries
Static Public Member Functions
static void GetStream (string url, string contentType, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Perform a GET request and return the results as a stream of bytes
static void GetByteStream (string url, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
static void GetBytes (string url, string contentType, Action< byte[]> resolve, Action< Exception > reject, IProgress prog=null)
Perform a GET request and return the results as an array of bytes
static void GetBytes (string url, Action< byte[]> resolve, Action< Exception > reject, IProgress prog=null)
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
static void GetText (string url, string contentType, Action< string > resolve, Action< Exception > reject, IProgress prog=null)
Perform a GET request and return the results as string
static void GetText (string url, Action< string > resolve, Action< Exception > reject, IProgress prog=null)
Perform a GET request and return the results as string for the application/unknown MIME type
static void GetJSON (string url, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Perform a GET request and return the results as a stream of bytes, for the application/json MIME type
static void GetJSON (string url, Action< string > resolve, Action< Exception > reject, IProgress prog=null)
Perform a JSON GET request and return the results as a string.
static void PostStream (string url, string mime, long bodyLength, Action< Stream > writeBody, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Perform a POST request, writing the body through a stream, and return thet results as a stream.
static void PostStream (string url, string mime, string body, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Perform a POST request, writing the body through a stream, and return thet results as a stream.
static void GetObject< T > (string url, Action< T > resolve, Action< Exception > reject, IProgress prog=null)
Perform a JSON GET request and return the results as deserialized object.
static void PostObject< T, U > (string url, U body, Action< T > resolve, Action< Exception > reject, IProgress prog=null)
Perform a POST request, serializing the body from an object to JSON, and return thet results as a JSON deserialized object.
Private Member Functions
HTTP (HttpWebRequest request, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Initialize a byte stream request handler.
HTTP (HttpWebRequest request, long bodyLength, Action< Stream > writeBody, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Initialize a byte stream request handler that first writes a request body.
void SetReadResponse (HttpWebRequest request, Action< Stream > resolve, IProgress prog)
Wraps the response reading callback with a progress report.
void SetWriteBody (long bodyLength, Action< Stream > writeBody, IProgress prog)
Wraps the body writing callback with a progress report.
Static Private Member Functions
static void EmptyRejection (Exception exp)
A default error handler that does nothing.
static HttpWebRequest MakeRequest (string method, string url, string contentType)
Create the basic request object.
static void GetRequestStream (IAsyncResult asynchronousResult)
If we know we need to write a request body, get a stream to which we can write the body.
static void GetResponseCallback (IAsyncResult asynchronousResult)
Get the response that the server sent for the request.
Private Attributes
readonly HttpWebRequest request
The HTTP request that is being made to a remote server.
Action< Stream > writeBody
The callback to use when a request body needs to be written.
Action< Stream > resolve
The callback to use when a byte stream has been requested.
readonly Action< Exception > reject
The callback to use when there is an error.
Detailed Description
Perform HTTP queries
Definition at line 15 of file HTTP.cs.
Constructor & Destructor Documentation
HTTP() [1/2]
Juniper.HTTP.HTTP (HttpWebRequest request, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline private
Initialize a byte stream request handler.
Parameters
request The request to handle
resolve The callback to execute when the request completes successfully
reject The callback to execute if the request fails.
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 290 of file HTTP.cs.
         {
             this.request = request;
             this.reject = reject;
             SetReadResponse(request, resolve, prog);
         }
References Juniper.HTTP.reject, Juniper.HTTP.request, Juniper.HTTP.resolve, and Juniper.HTTP.SetReadResponse().
Referenced by Juniper.HTTP.GetRequestStream(), Juniper.HTTP.GetStream(), and Juniper.HTTP.PostStream().
HTTP() [2/2]
Juniper.HTTP.HTTP (HttpWebRequest request, long bodyLength, Action< Stream > writeBody, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline private
Initialize a byte stream request handler that first writes a request body.
Parameters
request The request to handle
bodyLength The length, in bytes, of the request body that needs to be written.
writeBody A callback to execute when the system is ready to write the request body.
resolve The callback to execute when the request completes successfully
reject The callback to execute if the request fails.
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 307 of file HTTP.cs.
         {
             this.request = request;
             this.reject = reject;
             var progs = prog.Split(2);
             SetWriteBody(bodyLength, writeBody, progs[0]);
             SetReadResponse(request, resolve, progs[1]);
         }
References Juniper.HTTP.reject, Juniper.HTTP.request, Juniper.HTTP.resolve, Juniper.HTTP.SetReadResponse(), Juniper.HTTP.SetWriteBody(), and Juniper.HTTP.writeBody.
Member Function Documentation
EmptyRejection()
static void Juniper.HTTP.EmptyRejection (Exception exp) inline static private
A default error handler that does nothing.
Parameters
exp
Definition at line 349 of file HTTP.cs.
         {
         }
Referenced by Juniper.HTTP.GetStream().
GetBytes() [1/2]
static void Juniper.HTTP.GetBytes (string url, string contentType, Action< byte[]> resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a GET request and return the results as an array of bytes
Parameters
url The URL to request
contentType The MIME of the expected response
resolve The callback to perform on success, with the byte array payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 73 of file HTTP.cs.
         {
             GetStream(
                 url,
                 contentType,
                 stream => resolve(stream.ReadBytes(prog)),
                 reject,
                 prog);
         }
References Juniper.HTTP.GetStream(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
Referenced by Juniper.HTTP.GetBytes().
GetBytes() [2/2]
static void Juniper.HTTP.GetBytes (string url, Action< byte[]> resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
Parameters
url The URL to request
resolve The callback to perform on success, with the byte array payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 91 of file HTTP.cs.
         {
             GetBytes(url, "application/octet-stream", resolve, reject, prog);
         }
References Juniper.HTTP.GetBytes(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
GetByteStream()
static void Juniper.HTTP.GetByteStream (string url, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
Parameters
url The URL to request
resolve The callback to perform on success, with the byte array payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 60 of file HTTP.cs.
         {
             GetStream(url, "application/octet-stream", resolve, reject, prog);
         }
References Juniper.HTTP.GetStream(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
GetJSON() [1/2]
static void Juniper.HTTP.GetJSON (string url, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a GET request and return the results as a stream of bytes, for the application/json MIME type
Parameters
url The URL to request
resolve The callback to perform on success, with the stream payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 134 of file HTTP.cs.
         {
             GetStream(url, "application/json", resolve, reject, prog);
         }
References Juniper.HTTP.GetStream(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
Referenced by Juniper.HTTP.GetObject< T >().
GetJSON() [2/2]
static void Juniper.HTTP.GetJSON (string url, Action< string > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a JSON GET request and return the results as a string.
Parameters
url The URL to request
resolve The callback to perform on success, with the JSON string payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 146 of file HTTP.cs.
         {
             GetText(url, "application/json", resolve, reject, prog);
         }
References Juniper.HTTP.GetText(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
GetObject< T >()
static void Juniper.HTTP.GetObject< T > (string url, Action< T > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a JSON GET request and return the results as deserialized object.
Parameters
url The URL to request
resolve The callback to perform on success, with the deserialized object payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 203 of file HTTP.cs.
         {
             try
             {
                 GetJSON(
                     url,
                     jsonText => resolve(JsonConvert.DeserializeObject<T>(jsonText)),
                     reject,
                     prog);
             }
             catch (Exception exp)
             {
                 reject(exp);
             }
         }
References Juniper.HTTP.GetJSON(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
GetRequestStream()
static void Juniper.HTTP.GetRequestStream (IAsyncResult asynchronousResult) inline static private
If we know we need to write a request body, get a stream to which we can write the body.
Parameters
asynchronousResult
Definition at line 372 of file HTTP.cs.
         {
             var http = (HTTP)asynchronousResult.AsyncState;
             try
             {
                 using (var requestBody = http.request.EndGetRequestStream(asynchronousResult))
                 {
                     http.writeBody(requestBody);
                     http.request.BeginGetResponse(new AsyncCallback(GetResponseCallback), http);
                 }
             }
             catch (Exception exp)
             {
                 http.reject(new Exception($"retrieving request stream [{http.request.RequestUri}]", exp));
             }
         }
References Juniper.HTTP.GetResponseCallback(), and Juniper.HTTP.HTTP().
Referenced by Juniper.HTTP.PostStream().
GetResponseCallback()
static void Juniper.HTTP.GetResponseCallback (IAsyncResult asynchronousResult) inline static private
Get the response that the server sent for the request.
Parameters
asynchronousResult
Definition at line 393 of file HTTP.cs.
         {
             var http = (HTTP)asynchronousResult.AsyncState;
             try
             {
                 var response = (HttpWebResponse)http.request.EndGetResponse(asynchronousResult);
                 if (http.resolve != null)
                 {
                     using (var stream = response.GetResponseStream())
                     {
                         http.resolve(stream);
                     }
                 }
                 else
                 {
                     http.reject(new Exception($"Couldn't figure out how to handle the request for [{http.request.RequestUri}]"));
                 }
             }
             catch (Exception exp)
             {
                 http.reject(new Exception($"retrieving response [{http.request.RequestUri}]", exp));
             }
         }
Referenced by Juniper.HTTP.GetRequestStream(), and Juniper.HTTP.GetStream().
GetStream()
static void Juniper.HTTP.GetStream (string url, string contentType, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a GET request and return the results as a stream of bytes
Parameters
url The URL to request
contentType The MIME of the expected response
resolve The callback to perform on success, with the stream payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 25 of file HTTP.cs.
         {
             prog?.Report(0);
             void progResolve(Stream resolveStream)
             {
                 prog?.Report(1);
                 resolve(resolveStream);
             }
             if (reject == null)
             {
                 reject = EmptyRejection;
             }
             try
             {
                 var request = MakeRequest("GET", url, contentType ?? "application/unknown");
                 var http = new HTTP(request, progResolve, reject, prog);
                 request.BeginGetResponse(new AsyncCallback(GetResponseCallback), http);
             }
             catch (Exception exp)
             {
                 reject(new Exception($"creating request object [{url}]", exp));
             }
         }
References Juniper.HTTP.EmptyRejection(), Juniper.HTTP.GetResponseCallback(), Juniper.HTTP.HTTP(), Juniper.HTTP.MakeRequest(), Juniper.HTTP.reject, Juniper.HTTP.request, and Juniper.HTTP.resolve.
Referenced by Juniper.HTTP.GetBytes(), Juniper.HTTP.GetByteStream(), Juniper.Unity.Data.StreamingAssets.GetCachedFile(), Juniper.HTTP.GetJSON(), and Juniper.HTTP.GetText().
GetText() [1/2]
static void Juniper.HTTP.GetText (string url, string contentType, Action< string > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a GET request and return the results as string
Parameters
url The URL to request
contentType The MIME of the expected response
resolve The callback to perform on success, with the string payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 104 of file HTTP.cs.
         {
             GetStream(
                 url,
                 contentType,
                 stream => resolve(stream.ReadString(prog)),
                 reject,
                 prog);
         }
References Juniper.HTTP.GetStream(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
Referenced by Juniper.HTTP.GetJSON(), and Juniper.HTTP.GetText().
GetText() [2/2]
static void Juniper.HTTP.GetText (string url, Action< string > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a GET request and return the results as string for the application/unknown MIME type
Parameters
url The URL to request
resolve The callback to perform on success, with the string payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 121 of file HTTP.cs.
         {
             GetText(url, "text/plain", resolve, reject, prog);
         }
References Juniper.HTTP.GetText(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
MakeRequest()
static HttpWebRequest Juniper.HTTP.MakeRequest (string method, string url, string contentType) inline static private
Create the basic request object.
Parameters
method GET/PUT/POST/etc.
url
contentType Also called MIME
Returns
Definition at line 360 of file HTTP.cs.
         {
             var request = (HttpWebRequest)WebRequest.Create(url);
             request.ContentType = contentType;
             request.Method = method;
             return request;
         }
References Juniper.HTTP.request.
Referenced by Juniper.HTTP.GetStream(), and Juniper.HTTP.PostStream().
PostObject< T, U >()
static void Juniper.HTTP.PostObject< T, U > (string url, U body, Action< T > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a POST request, serializing the body from an object to JSON, and return thet results as a JSON deserialized object.
Parameters
url The URL to request
body The body to object to serialize to the body of the POST request
resolve The callback to perform on success, with the deserialized object payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 230 of file HTTP.cs.
         {
             try
             {
                 byte[] buf = null;
                 using (var mem = new MemoryStream())
                 {
                     var writer = new StreamWriter(mem);
                     writer.Write(JsonConvert.SerializeObject(body));
                     mem.Flush();
                     buf = mem.GetBuffer();
                 }
                 PostStream(
                     url, "application/json",
                     buf.Length,
                     stream => stream.Write(buf, 0, buf.Length),
                     stream =>
                     {
                         using (var reader = new StreamReader(stream))
{
                             resolve(JsonConvert.DeserializeObject<T>(reader.ReadToEnd()));
                         }
                     },
                     reject,
                     prog);
             }
             catch (Exception exp)
             {
                 reject(exp);
             }
         }
References Juniper.HTTP.PostStream(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
PostStream() [1/2]
static void Juniper.HTTP.PostStream (string url, string mime, long bodyLength, Action< Stream > writeBody, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a POST request, writing the body through a stream, and return thet results as a stream.
Parameters
url The URL to request
mime The MIME type of both the request and response body
bodyLength The total length of the body that needs to be written
writeBody A callback function for writing the body to a stream
resolve The callback to perform on success, with the stream payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 161 of file HTTP.cs.
         {
             try
             {
                 var request = MakeRequest("POST", url, mime);
                 var http = new HTTP(request, bodyLength, writeBody, resolve, reject, prog);
                 request.BeginGetRequestStream(new AsyncCallback(GetRequestStream), http);
             }
             catch (Exception exp)
             {
                 reject(new Exception($"creating request object [{url}]", exp));
             }
         }
References Juniper.HTTP.GetRequestStream(), Juniper.HTTP.HTTP(), Juniper.HTTP.MakeRequest(), Juniper.HTTP.reject, Juniper.HTTP.request, Juniper.HTTP.resolve, and Juniper.HTTP.writeBody.
Referenced by Juniper.HTTP.PostObject< T, U >(), and Juniper.HTTP.PostStream().
PostStream() [2/2]
static void Juniper.HTTP.PostStream (string url, string mime, string body, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline static
Perform a POST request, writing the body through a stream, and return thet results as a stream.
Parameters
url The URL to request
mime The MIME type of both the request and response body
body The body to write to the POST request
resolve The callback to perform on success, with the stream payload
reject The callback to perform on error
prog An optional progress tracker. Defaults to null (no progress tracking).
Definition at line 184 of file HTTP.cs.
         {
             var buf = Encoding.UTF8.GetBytes(body);
             PostStream(
                 url, mime,
                 buf.Length,
                 stream => stream.Write(buf, 0, buf.Length),
                 resolve, reject, prog);
         }
References Juniper.HTTP.PostStream(), Juniper.HTTP.reject, and Juniper.HTTP.resolve.
SetReadResponse()
void Juniper.HTTP.SetReadResponse (HttpWebRequest request, Action< Stream > resolve, IProgress prog) inline private
Wraps the response reading callback with a progress report.
Parameters
request
resolve
prog
Definition at line 323 of file HTTP.cs.
         {
             this.resolve = stream =>
                 resolve(new ProgressStream(stream, request.ContentLength, prog));
         }
References Juniper.HTTP.request, and Juniper.HTTP.resolve.
Referenced by Juniper.HTTP.HTTP().
SetWriteBody()
void Juniper.HTTP.SetWriteBody (long bodyLength, Action< Stream > writeBody, IProgress prog) inline private
Wraps the body writing callback with a progress report.
Parameters
bodyLength
writeBody
prog
Definition at line 335 of file HTTP.cs.
         {
             this.writeBody = stream =>
             {
                 var writeProgress = new ProgressStream(stream, bodyLength, prog);
                 writeBody(writeProgress);
                 writeProgress.Flush();
             };
         }
References Juniper.HTTP.writeBody.
Referenced by Juniper.HTTP.HTTP().
Member Data Documentation
reject
readonly Action<Exception> Juniper.HTTP.reject private
The callback to use when there is an error.
Definition at line 281 of file HTTP.cs.
Referenced by Juniper.HTTP.GetBytes(), Juniper.HTTP.GetByteStream(), Juniper.HTTP.GetJSON(), Juniper.HTTP.GetObject< T >(), Juniper.HTTP.GetStream(), Juniper.HTTP.GetText(), Juniper.HTTP.HTTP(), Juniper.HTTP.PostObject< T, U >(), and Juniper.HTTP.PostStream().
request
readonly HttpWebRequest Juniper.HTTP.request private
The HTTP request that is being made to a remote server.
Definition at line 266 of file HTTP.cs.
Referenced by Juniper.HTTP.GetStream(), Juniper.HTTP.HTTP(), Juniper.HTTP.MakeRequest(), Juniper.HTTP.PostStream(), and Juniper.HTTP.SetReadResponse().
resolve
Action<Stream> Juniper.HTTP.resolve private
The callback to use when a byte stream has been requested.
Definition at line 276 of file HTTP.cs.
Referenced by Juniper.HTTP.GetBytes(), Juniper.HTTP.GetByteStream(), Juniper.HTTP.GetJSON(), Juniper.HTTP.GetObject< T >(), Juniper.HTTP.GetStream(), Juniper.HTTP.GetText(), Juniper.HTTP.HTTP(), Juniper.HTTP.PostObject< T, U >(), Juniper.HTTP.PostStream(), and Juniper.HTTP.SetReadResponse().
writeBody
Action<Stream> Juniper.HTTP.writeBody private
The callback to use when a request body needs to be written.
Definition at line 271 of file HTTP.cs.
Referenced by Juniper.HTTP.HTTP(), Juniper.HTTP.PostStream(), and Juniper.HTTP.SetWriteBody().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper.Common/src/Data/HTTP.cs