Juniper: Juniper.Animation.Tween Class Reference
Juniper.Animation.Tween Class Reference
Implementations for each of the values in TweenType. All functions receive a value t, representing the proportion of the way through the animation process we are calculating. All functions take an extra k parameter, for scaling tertiary effects; most functions do not use it. All functions return a value v, mapping the value t to one of the desired 'tween shapes.
Static Public Member Functions
static bool IsContinuous (TweenType tween)
static float Linear (float t, float k, Direction d)
The most basic form of `tween, values increase in proportion to time.
static float LinearContinuous (float t, float k, Direction d)
The most basic form of `tween, values increase in proportion to time.
static float Quadratic (float t, float k, Direction d)
Values increase in proportion to the square of time, meaning they start growing slowly and then grow quickly.
static float QuadraticContinuous (float t, float k, Direction d)
Values increase in proportion to the square of time.
static float Sine (float t, float k, Direction d)
Values increase on a sine curve, meaning they start growing quickly and then slow down.
static float SineContinuous (float t, float k, Direction d)
Values increase on a sine curve, meaning they start growing quickly and then slow down.
static float Bump (float t, float k, Direction d)
Similar to Sine, but values bump in the opposite direction slightly, before the beginning and the end of the curve.
static float BumpContinuous (float t, float k, Direction d)
Similar to Sine, but values bump in the opposite direction slightly, before the beginning and the end of the curve.
Static Public Attributes
static readonly Dictionary< TweenType, TweenFunc > Functions
A lookup for the tween functions, so we don't have to use reflection every time we want one.
Detailed Description
Implementations for each of the values in TweenType. All functions receive a value t, representing the proportion of the way through the animation process we are calculating. All functions take an extra k parameter, for scaling tertiary effects; most functions do not use it. All functions return a value v, mapping the value t to one of the desired 'tween shapes.
Definition at line 62 of file TweenType.cs.
Member Function Documentation
Bump()
static float Juniper.Animation.Tween.Bump (float t, float k, Direction d) inline static
Similar to Sine, but values bump in the opposite direction slightly, before the beginning and the end of the curve.
Parameters
t The proportional value, linearly progressing from 0 to 1.
k The constant value, input by the developer.
d The direction value, 1 for forward, -1 for backward.
Definition at line 176 of file TweenType.cs.
         {
             var a = t * Math.PI;
             return (float)(0.5f * (1 - Math.Cos(a)) - k * Math.Sin(2 * a));
         }
BumpContinuous()
static float Juniper.Animation.Tween.BumpContinuous (float t, float k, Direction d) inline static
Similar to Sine, but values bump in the opposite direction slightly, before the beginning and the end of the curve.
Parameters
t The proportional value, linearly progressing from 0 to 1.
k The constant value, input by the developer.
d The direction value, 1 for forward, -1 for backward.
Definition at line 189 of file TweenType.cs.
         {
             t = LinearContinuous(t, k, d);
             var a = t * Math.PI;
             return (float)(Math.Sin(0.5f * a) + k * Math.Sin(a));
         }
References Juniper.Animation.Tween.LinearContinuous().
IsContinuous()
static bool Juniper.Animation.Tween.IsContinuous (TweenType tween) inline static
Definition at line 64 of file TweenType.cs.
         {
             return tween == TweenType.LinearContinuous
                 || tween == TweenType.QuadraticContinuous
                 || tween == TweenType.SineContinuous
                 || tween == TweenType.BumpContinuous;
         }
Linear()
static float Juniper.Animation.Tween.Linear (float t, float k, Direction d) inline static
The most basic form of `tween, values increase in proportion to time.
Parameters
t The proportional value, linearly progressing from 0 to 1.
k The constant value, input by the developer.
d The direction value, 1 for forward, -1 for backward.
Definition at line 93 of file TweenType.cs.
         {
             return t;
         }
LinearContinuous()
static float Juniper.Animation.Tween.LinearContinuous (float t, float k, Direction d) inline static
The most basic form of `tween, values increase in proportion to time.
Parameters
t The proportional value, linearly progressing from 0 to 1.
k The constant value, input by the developer.
d The direction value, 1 for forward, -1 for backward.
Definition at line 104 of file TweenType.cs.
         {
             if (d == Direction.Forward)
             {
                 return t - 1;
             }
             else
             {
                 return 1 - t;
             }
         }
Referenced by Juniper.Animation.Tween.BumpContinuous(), Juniper.Animation.Tween.QuadraticContinuous(), and Juniper.Animation.Tween.SineContinuous().
Quadratic()
static float Juniper.Animation.Tween.Quadratic (float t, float k, Direction d) inline static
Values increase in proportion to the square of time, meaning they start growing slowly and then grow quickly.
Parameters
t The proportional value, linearly progressing from 0 to 1.
k The constant value, input by the developer.
d The direction value, 1 for forward, -1 for backward.
Definition at line 123 of file TweenType.cs.
         {
             return t * t;
         }
Referenced by Juniper.Animation.Tween.QuadraticContinuous().
QuadraticContinuous()
static float Juniper.Animation.Tween.QuadraticContinuous (float t, float k, Direction d) inline static
Values increase in proportion to the square of time.
Parameters
t The proportional value, linearly progressing from 0 to 1.
k The constant value, input by the developer.
d The direction value, 1 for forward, -1 for backward.
Definition at line 134 of file TweenType.cs.
         {
             t = LinearContinuous(t, k, d);
             return Math.Sign(t) * Quadratic(t, k, d);
         }
References Juniper.Animation.Tween.LinearContinuous(), and Juniper.Animation.Tween.Quadratic().
Sine()
static float Juniper.Animation.Tween.Sine (float t, float k, Direction d) inline static
Values increase on a sine curve, meaning they start growing quickly and then slow down.
Parameters
t
k
d
Returns
Definition at line 148 of file TweenType.cs.
         {
             var a = t * Math.PI;
             return (float)Math.Sin(a);
         }
SineContinuous()
static float Juniper.Animation.Tween.SineContinuous (float t, float k, Direction d) inline static
Values increase on a sine curve, meaning they start growing quickly and then slow down.
Parameters
t
k
d
Returns
Definition at line 163 of file TweenType.cs.
         {
             var a = LinearContinuous(t, k, d) * Math.PI;
             return (float)Math.Sin(a);
         }
References Juniper.Animation.Tween.LinearContinuous().
Member Data Documentation
Functions
readonly Dictionary<TweenType, TweenFunc> Juniper.Animation.Tween.Functions static
Initial value:
= new Dictionary<TweenType, TweenFunc>(6)
        {
            { TweenType.Linear, Linear },
            { TweenType.LinearContinuous, LinearContinuous },
            { TweenType.Quadratic, Quadratic },
            { TweenType.QuadraticContinuous, QuadraticContinuous },
            { TweenType.Sine, Sine },
            { TweenType.SineContinuous, SineContinuous },
            { TweenType.Bump, Bump },
            { TweenType.BumpContinuous, BumpContinuous }
        }
A lookup for the tween functions, so we don't have to use reflection every time we want one.
Definition at line 75 of file TweenType.cs.
Referenced by Juniper.Animation.PresentationTransition.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Animation/TweenType.cs