Juniper: Juniper.Animation.SpiralTransition Class Reference
Juniper.Animation.SpiralTransition Class Reference
Take an object in world-space and spiral it in to camera-locked space (faux-screen-space)
Public Member Functions
void Awake ()
Finds the transform of the main camera.
override void Enter (IProgress prog)
Fire the OnEnable event and perform the Enter transition.
void Enter ()
override void Exit (IProgress prog)
Fire the OnExiting event and perform the Exit transition.
void Exit ()
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
virtual void SkipExit ()
Task EnterAsync (IProgress prog=null)
Task ExitAsync (IProgress prog=null)
Public Attributes
Vector3 startOrientation = 90 * Vector3.right
The local rotation of the element when sitting in its original parent.
Vector3 endOrientation = 90 * Vector3.back
The local rotation of the element when it is parented tracking the camera.
bool fullScreen = true
Set to true if the transition is being used to make a video appear as if it is full-screen. The distance field will automatically be calculated to make the extents of the video fill the view port.
float distance = 0.2f
The distance from the camera at which the element should stop when the transition has finished entering. The value entered in the Editor for this field is ignored if fullScreen is set to true.
float length = 1
The amount of time, in seconds, that the transition should take.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
UnityEvent onStopped = new UnityEvent()
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Direction _curState
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void Update ()
Continuously update the location, rotation, and scale of the element.
override void RenderValue (float value)
Records the transition value so the Update function can use it.
override void OnEntering ()
Records the starting values so the enter transition can LERP over the values correctly.
override void OnExiting ()
Records the exiting values to make the update LERP undo the changes to the element.
override void Complete ()
Finish the transition, whatever is going on.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
virtual void OnStopped ()
Protected Attributes
bool skipEvents
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Properties
override float TransitionLength [get]
The amount of time, in seconds, that the transition should take.
Direction State [get, private set]
virtual bool IsComplete [get]
Returns true when State is Direction.Stopped
bool IsEntering [get]
bool IsExiting [get]
bool CanExit [get]
bool CanEnter [get]
bool IsRunning [get]
Returns true when State is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
Events
EventHandler< TransitionValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
EventHandler Stopped
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Private Attributes
Transform startParent
The object under which the element originally started.
Vector3 startPosition
The position at which the element started.
Vector3 startScale
The scale of the element at the start of the enter transition, or the end of the exit transition.
Vector3 endScale
The scale of the element at the end of the enter transition, or the start of the exit transition.
Transform camT
The camera, cached for faster access.
float tweenValue
The current transition state value, cached so the location and rotation can change with the camera after the transition has finished.
Detailed Description
Take an object in world-space and spiral it in to camera-locked space (faux-screen-space)
Definition at line 10 of file SpiralTransition.cs.
Member Function Documentation
Awake()
void Juniper.Animation.SpiralTransition.Awake () inline
Finds the transform of the main camera.
Definition at line 55 of file SpiralTransition.cs.
         {
             camT = DisplayManager.MainCamera.transform;
         }
References Juniper.Animation.SpiralTransition.camT, and Juniper.Display.AbstractDisplayManager.MainCamera.
Complete()
override void Juniper.Animation.AbstractTransitionController.Complete () inline protected virtual inherited
Finish the transition, whatever is going on.
Reimplemented from Juniper.AbstractStateController.
Definition at line 110 of file AbstractTransitionController.cs.
         {
             SetProgress(1);
             base.Complete();
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Animation.AbstractTransitionController.Update().
Enter() [1/2]
override void Juniper.Animation.AbstractTransitionController.Enter (IProgress prog) inline virtual inherited
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 92 of file AbstractTransitionController.cs.
         {
             base.Enter(prog);
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Widgets.TeleportPad.OnClick(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Animation.WorkflowStep.Show().
Enter() [2/2]
void Juniper.AbstractStateController.Enter () inline inherited
Definition at line 272 of file AbstractStateController.cs.
         {
             Enter(null);
         }
Referenced by Juniper.Widgets.MenuView.Enter(), Juniper.AbstractStateController.EnterAsync(), Juniper.Animation.FadeTransition.Fader(), Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.AbstractStateController.SkipEnter().
EnterAsync()
Task Juniper.AbstractStateController.EnterAsync (IProgress prog = null) inline inherited
Definition at line 331 of file AbstractStateController.cs.
         {
             return Stopper(Enter, prog);
         }
References Juniper.AbstractStateController.Enter(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Exit() [1/2]
override void Juniper.Animation.AbstractTransitionController.Exit (IProgress prog) inline virtual inherited
Fire the OnExiting event and perform the Exit transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 101 of file AbstractTransitionController.cs.
         {
             base.Exit(prog);
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Widgets.TeleportPad.Darth_Entered(), and Juniper.Widgets.Openable.SetOpen().
Exit() [2/2]
void Juniper.AbstractStateController.Exit () inline inherited
Definition at line 285 of file AbstractStateController.cs.
         {
             Exit(null);
         }
Referenced by Juniper.Widgets.MenuView.Exit(), Juniper.AbstractStateController.ExitAsync(), Juniper.Animation.FadeTransition.Fader(), and Juniper.AbstractStateController.SkipExit().
ExitAsync()
Task Juniper.AbstractStateController.ExitAsync (IProgress prog = null) inline inherited
Definition at line 336 of file AbstractStateController.cs.
         {
             return Stopper(Exit, prog);
         }
References Juniper.AbstractStateController.Exit(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), Juniper.MasterSceneController.RemoveSceneCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
OnEntered()
virtual void Juniper.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Animation.FadeTransition, and Juniper.Widgets.MenuCollection.
Definition at line 379 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onEntered != null)
                 {
                     onEntered.Invoke();
                 }
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entered, Juniper.AbstractStateController.onEntered, and Juniper.AbstractStateController.skipEvents.
OnEntering()
override void Juniper.Animation.SpiralTransition.OnEntering () inline protected virtual
Records the starting values so the enter transition can LERP over the values correctly.
Reimplemented from Juniper.Animation.AbstractTransitionController.
Definition at line 97 of file SpiralTransition.cs.
         {
             startParent = transform.parent;
             startPosition = transform.position;
             endScale = transform.localScale;
             transform.parent = null;
             startScale = transform.localScale;
             base.OnEntering();
         }
References Juniper.Animation.SpiralTransition.endScale, Juniper.Animation.SpiralTransition.startParent, Juniper.Animation.SpiralTransition.startPosition, and Juniper.Animation.SpiralTransition.startScale.
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 417 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onExited != null)
                 {
                     onExited.Invoke();
                 }
                 Exited?.Invoke(this, EventArgs.Empty);
             }
             enabled = false;
         }
References Juniper.AbstractStateController.Exited, Juniper.AbstractStateController.onExited, and Juniper.AbstractStateController.skipEvents.
OnExiting()
override void Juniper.Animation.SpiralTransition.OnExiting () inline protected virtual
Records the exiting values to make the update LERP undo the changes to the element.
Reimplemented from Juniper.Animation.AbstractTransitionController.
Definition at line 110 of file SpiralTransition.cs.
         {
             startScale = endScale;
             transform.parent = startParent;
             endScale = transform.localScale;
             base.OnExiting();
         }
References Juniper.Animation.SpiralTransition.endScale, Juniper.Animation.SpiralTransition.startParent, and Juniper.Animation.SpiralTransition.startScale.
OnStopped()
virtual void Juniper.AbstractStateController.OnStopped () inline protected virtual inherited
Definition at line 430 of file AbstractStateController.cs.
         {
             if (onStopped != null)
             {
                 onStopped?.Invoke();
             }
             Stopped?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.onStopped, and Juniper.AbstractStateController.Stopped.
RenderValue()
override void Juniper.Animation.SpiralTransition.RenderValue (float value) inline protected virtual
Records the transition value so the Update function can use it.
Parameters
value Value.
Implements Juniper.Animation.AbstractTransitionController.
Definition at line 89 of file SpiralTransition.cs.
         {
             tweenValue = value;
         }
References Juniper.Animation.SpiralTransition.tweenValue.
SkipEnter()
virtual void Juniper.AbstractStateController.SkipEnter () inline virtual inherited
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 309 of file AbstractStateController.cs.
         {
             if (!IsEntered)
             {
                 skipEvents = true;
                 Enter();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.IsEntered, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.MasterSceneController.Start().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 320 of file AbstractStateController.cs.
         {
             if (!IsExited)
             {
                 skipEvents = true;
                 Exit();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Exit(), Juniper.AbstractStateController.IsExited, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.Widgets.Tooltipable.Hide(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Update()
override void Juniper.Animation.SpiralTransition.Update () inline protected virtual
Continuously update the location, rotation, and scale of the element.
Reimplemented from Juniper.Animation.AbstractTransitionController.
Definition at line 63 of file SpiralTransition.cs.
         {
             base.Update();
             if (fullScreen)
             {
                 var mid = DisplayManager.MainCamera.ViewportToWorldPoint(Vector3.forward);
                 var top = DisplayManager.MainCamera.ViewportToWorldPoint(new Vector3(0, 1, 1));
                 var delta = top - mid;
                 mid *= 0.5f / delta.magnitude;
                 distance = mid.magnitude * 0.975f;
             }
             var rotationStart = startParent.rotation * Quaternion.Euler(startOrientation);
             var rotationEnd = camT.rotation * Quaternion.Euler(endOrientation);
             var endPosition = camT.position + distance * camT.forward;
             transform.rotation = Quaternion.Slerp(rotationStart, rotationEnd, tweenValue);
             transform.position = Vector3.Lerp(startPosition, endPosition, tweenValue);
             transform.localScale = Vector3.Lerp(startScale, endScale, tweenValue);
         }
References Juniper.Animation.SpiralTransition.camT, Juniper.Animation.SpiralTransition.distance, Juniper.Animation.SpiralTransition.endOrientation, Juniper.Animation.SpiralTransition.endScale, Juniper.Animation.SpiralTransition.fullScreen, Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.Animation.SpiralTransition.startOrientation, Juniper.Animation.SpiralTransition.startParent, Juniper.Animation.SpiralTransition.startPosition, Juniper.Animation.SpiralTransition.startScale, and Juniper.Animation.SpiralTransition.tweenValue.
Member Data Documentation
_curState
Direction Juniper.AbstractStateController._curState inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 117 of file AbstractStateController.cs.
attackTime
float Juniper.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 21 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnEntering(), and Juniper.Animation.AbstractTransitionController.OnExiting().
camT
Transform Juniper.Animation.SpiralTransition.camT private
The camera, cached for faster access.
Definition at line 141 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.Awake(), and Juniper.Animation.SpiralTransition.Update().
distance
float Juniper.Animation.SpiralTransition.distance = 0.2f
The distance from the camera at which the element should stop when the transition has finished entering. The value entered in the Editor for this field is ignored if fullScreen is set to true.
Definition at line 34 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.Update().
endOrientation
Vector3 Juniper.Animation.SpiralTransition.endOrientation = 90 * Vector3.back
The local rotation of the element when it is parented tracking the camera.
Definition at line 20 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.Update().
endScale
Vector3 Juniper.Animation.SpiralTransition.endScale private
The scale of the element at the end of the enter transition, or the start of the exit transition.
Definition at line 136 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.OnEntering(), Juniper.Animation.SpiralTransition.OnExiting(), and Juniper.Animation.SpiralTransition.Update().
fullScreen
bool Juniper.Animation.SpiralTransition.fullScreen = true
Set to true if the transition is being used to make a video appear as if it is full-screen. The distance field will automatically be calculated to make the extents of the video fill the view port.
Definition at line 27 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.Update().
length
float Juniper.Animation.SpiralTransition.length = 1
The amount of time, in seconds, that the transition should take.
Definition at line 39 of file SpiralTransition.cs.
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 38 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 29 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 56 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 47 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
onStopped
UnityEvent Juniper.AbstractStateController.onStopped = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 65 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped().
onValueChanged
UnityEvent Juniper.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 34 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
releaseTime
float Juniper.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 28 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnEntering(), and Juniper.Animation.AbstractTransitionController.OnExiting().
skipEvents
bool Juniper.AbstractStateController.skipEvents protected inherited
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Definition at line 166 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Complete(), Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.AbstractTransitionController.Exit(), Juniper.AbstractStateController.OnEntered(), Juniper.AbstractStateController.OnEntering(), Juniper.AbstractStateController.OnExited(), Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.SkipEnter(), and Juniper.AbstractStateController.SkipExit().
startOrientation
Vector3 Juniper.Animation.SpiralTransition.startOrientation = 90 * Vector3.right
The local rotation of the element when sitting in its original parent.
Definition at line 15 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.Update().
startParent
Transform Juniper.Animation.SpiralTransition.startParent private
The object under which the element originally started.
Definition at line 121 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.OnEntering(), Juniper.Animation.SpiralTransition.OnExiting(), and Juniper.Animation.SpiralTransition.Update().
startPosition
Vector3 Juniper.Animation.SpiralTransition.startPosition private
The position at which the element started.
Definition at line 126 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.OnEntering(), and Juniper.Animation.SpiralTransition.Update().
startScale
Vector3 Juniper.Animation.SpiralTransition.startScale private
The scale of the element at the start of the enter transition, or the end of the exit transition.
Definition at line 131 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.OnEntering(), Juniper.Animation.SpiralTransition.OnExiting(), and Juniper.Animation.SpiralTransition.Update().
tween
TweenType Juniper.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 39 of file AbstractTransitionController.cs.
tweenK
float Juniper.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 46 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.SetProgress().
tweenValue
float Juniper.Animation.SpiralTransition.tweenValue private
The current transition state value, cached so the location and rotation can change with the camera after the transition has finished.
Definition at line 147 of file SpiralTransition.cs.
Referenced by Juniper.Animation.SpiralTransition.RenderValue(), and Juniper.Animation.SpiralTransition.Update().
Property Documentation
CanEnter
bool Juniper.AbstractStateController.CanEnter get inherited
Definition at line 204 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsEntered && !IsEntering;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
CanExit
bool Juniper.AbstractStateController.CanExit get inherited
Definition at line 196 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsExited && !IsExiting;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get inherited
Returns true when State is Direction.Stopped
Definition at line 172 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Stopped;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntered
bool Juniper.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 226 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Forward;
             }
         }
Referenced by Juniper.AbstractStateController.SkipEnter(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntering
bool Juniper.AbstractStateController.IsEntering get inherited
Definition at line 180 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Forward;
             }
         }
IsExited
bool Juniper.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 237 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Reverse;
             }
         }
Referenced by Juniper.AbstractStateController.SkipExit(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsExiting
bool Juniper.AbstractStateController.IsExiting get inherited
Definition at line 188 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Reverse;
             }
         }
IsRunning
bool Juniper.AbstractStateController.IsRunning get inherited
Returns true when State is not Direction.Stopped
Definition at line 215 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Animation.AbstractTransitionController.Update().
State
Direction Juniper.AbstractStateController.State get private set inherited
Definition at line 120 of file AbstractStateController.cs.
         {
             get
             {
                 return _curState;
             }
             private set
             {
                 lastState = _curState;
                 _curState = value;
                 if (State != lastState)
                 {
                     if (State == Direction.Forward)
                     {
                         OnEntering();
                     }
                     else if (State == Direction.Reverse)
                     {
                         OnExiting();
                     }
                     else
                     {
                         OnStopped();
                         if (lastState == Direction.Forward)
{
                             OnEntered();
                         }
                         else if (lastState == Direction.Reverse)
{
                             OnExited();
                         }
                     }
                 }
             }
         }
Referenced by Juniper.AbstractStateController.Complete(), Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.AbstractStateController.SetState().
TransitionLength
override float Juniper.Animation.SpiralTransition.TransitionLength get
The amount of time, in seconds, that the transition should take.
Definition at line 45 of file SpiralTransition.cs.
         {
             get
             {
                 return length;
             }
         }
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 83 of file AbstractStateController.cs.
Referenced by Juniper.Widgets.MenuView.Awake(), Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 74 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 101 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 92 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExiting().
Stopped
EventHandler Juniper.AbstractStateController.Stopped inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 110 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped(), and Juniper.AbstractStateController.Stopper().
ValueChanged
EventHandler<TransitionValueChangedEventArgs> Juniper.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 52 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Animation/SpiralTransition.cs