Juniper: Hjg.Pngcs.Chunks.PngChunkICCP Class Reference
Hjg.Pngcs.Chunks.PngChunkICCP Class Reference
iCCP Chunk: see http://www.w3.org/TR/PNG/#11iCCP
Public Types
enum ChunkOrderingConstraint {
ChunkOrderingConstraint.NONE, ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT, ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT, ChunkOrderingConstraint.BEFORE_IDAT,
ChunkOrderingConstraint.NA
}
Restrictions for chunk ordering, for ancillary chunks
Public Member Functions
PngChunkICCP (ImageInfo info)
override ChunkOrderingConstraint GetOrderingConstraint ()
Get ordering constrain
override ChunkRaw CreateRawChunk ()
Serialization. Creates a Raw chunk, ready for write, from this chunk content
override void ParseFromRaw (ChunkRaw chunk)
Deserialization. Given a Raw chunk, just rad, fills this chunk content
override void CloneDataFromRead (PngChunk other)
Override to make a copy (normally deep) from other chunk
void SetProfileNameAndContent (String name, String profile)
Sets profile name and profile
void SetProfileNameAndContent (String name, byte[] profile)
Sets profile name and profile
String GetProfileName ()
byte [] GetProfile ()
This uncompresses the string!
String GetProfileAsString ()
sealed override bool AllowsMultiple ()
This is implemented in PngChunkMultiple/PngChunSingle
override int GetHashCode ()
override bool Equals (object obj)
ChunkRaw createEmptyChunk (int len, bool alloc)
override String ToString ()
Basic info: Id, length, Type name
Static Public Member Functions
static void FactoryRegister (String chunkId, Type type)
Registers a Chunk ID in the factory, to instantiate a given type
static T CloneChunk< T > (T chunk, ImageInfo info)
Public Attributes
const String ID = ChunkHelper.iCCP
readonly String Id
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
readonly bool Crit
Standard basic properties, implicit in the Id
Protected Attributes
readonly ImageInfo ImgInfo
Image basic info, mostly for some checks
Properties
bool Priority [get, set]
For writing. Queued chunks with high priority will be written as soon as possible
int ChunkGroup [get, set]
Chunk group where it was read or writen
int Length [get, set]
long Offset [get, set]
Private Attributes
String profileName
byte [] compressedProfile
Detailed Description
iCCP Chunk: see http://www.w3.org/TR/PNG/#11iCCP
Definition at line 14 of file PngChunkICCP.cs.
Member Enumeration Documentation
ChunkOrderingConstraint
enum Hjg.Pngcs.Chunks.PngChunk.ChunkOrderingConstraint strong inherited
Restrictions for chunk ordering, for ancillary chunks
Enumerator
NONE
No constraint, the chunk can go anywhere
BEFORE_PLTE_AND_IDAT
Before PLTE (palette) - and hence, also before IDAT
AFTER_PLTE_BEFORE_IDAT
After PLTE (palette), but before IDAT
BEFORE_IDAT
Before IDAT (before or after PLTE)
NA
Does not apply
Definition at line 54 of file PngChunk.cs.
{
             /// <summary>
             /// No constraint, the chunk can go anywhere
             /// </summary>
             NONE,
             /// <summary>
             /// Before PLTE (palette) - and hence, also before IDAT
             /// </summary>
             BEFORE_PLTE_AND_IDAT,
             /// <summary>
             /// After PLTE (palette), but before IDAT
             /// </summary>
             AFTER_PLTE_BEFORE_IDAT,
             /// <summary>
             /// Before IDAT (before or after PLTE)
             /// </summary>
             BEFORE_IDAT,
             /// <summary>
             /// Does not apply
             /// </summary>
             NA
         }
Constructor & Destructor Documentation
PngChunkICCP()
Hjg.Pngcs.Chunks.PngChunkICCP.PngChunkICCP (ImageInfo info) inline
Definition at line 21 of file PngChunkICCP.cs.
             : base(ID, info) {
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkICCP.CloneDataFromRead().
Member Function Documentation
AllowsMultiple()
sealed override bool Hjg.Pngcs.Chunks.PngChunkSingle.AllowsMultiple () inline virtual inherited
This is implemented in PngChunkMultiple/PngChunSingle
Returns
Allows more than one chunk of this type in a image
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 14 of file PngChunkSingle.cs.
{
             return false;
         }
CloneChunk< T >()
static T Hjg.Pngcs.Chunks.PngChunk.CloneChunk< T > (T chunk, ImageInfo info) inline static inherited
Type Constraints
T : PngChunk
Definition at line 185 of file PngChunk.cs.
                                                                        : PngChunk {
             PngChunk cn = FactoryFromId(chunk.Id, info);
             if ((Object)cn.GetType() != (Object)chunk.GetType())
                 throw new PngjException("bad class cloning chunk: " + cn.GetType() + " "
                         + chunk.GetType());
             cn.CloneDataFromRead(chunk);
             return (T)cn;
         }
References Hjg.Pngcs.Chunks.PngChunk.CloneDataFromRead(), and Hjg.Pngcs.Chunks.PngChunk.FactoryFromId().
CloneDataFromRead()
override void Hjg.Pngcs.Chunks.PngChunkICCP.CloneDataFromRead (PngChunk other) inline virtual
Override to make a copy (normally deep) from other chunk
Parameters
other
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 50 of file PngChunkICCP.cs.
{
             PngChunkICCP otherx = (PngChunkICCP)other;
             profileName = otherx.profileName;
             compressedProfile = new byte[otherx.compressedProfile.Length];
             System.Array.Copy(otherx.compressedProfile, compressedProfile, compressedProfile.Length);
         }
References Hjg.Pngcs.Chunks.PngChunkICCP.compressedProfile, Hjg.Pngcs.Chunks.PngChunkICCP.PngChunkICCP(), and Hjg.Pngcs.Chunks.PngChunkICCP.profileName.
createEmptyChunk()
ChunkRaw Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk (int len, bool alloc) inline inherited
Definition at line 179 of file PngChunk.cs.
{
             ChunkRaw c = new ChunkRaw(len, ChunkHelper.ToBytes(Id), alloc);
             return c;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
Referenced by Hjg.Pngcs.Chunks.PngChunkTEXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkGAMA.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTIME.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkOFFS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSTER.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPHYS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkUNKNOWN.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSRGB.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk().
CreateRawChunk()
override ChunkRaw Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk () inline virtual
Serialization. Creates a Raw chunk, ready for write, from this chunk content
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 30 of file PngChunkICCP.cs.
{
             ChunkRaw c = createEmptyChunk(profileName.Length + compressedProfile.Length + 2, true);
             System.Array.Copy((Array)(Hjg.Pngcs.Chunks.ChunkHelper.ToBytes(profileName)), 0, (Array)(c.Data), 0, profileName.Length);
             c.Data[profileName.Length] = 0;
             c.Data[profileName.Length + 1] = 0;
             System.Array.Copy((Array)(compressedProfile), 0, (Array)(c.Data), profileName.Length + 2, compressedProfile.Length);
             return c;
         }
References Hjg.Pngcs.Chunks.PngChunkICCP.compressedProfile, Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk(), Hjg.Pngcs.Chunks.ChunkRaw.Data, Hjg.Pngcs.Chunks.PngChunkICCP.profileName, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
Equals()
override bool Hjg.Pngcs.Chunks.PngChunkSingle.Equals (object obj) inline inherited
Definition at line 25 of file PngChunkSingle.cs.
{
             return (obj is PngChunkSingle && Id != null && Id.Equals(((PngChunkSingle)obj).Id));
         }
References Hjg.Pngcs.Chunks.PngChunk.Id.
FactoryRegister()
static void Hjg.Pngcs.Chunks.PngChunk.FactoryRegister (String chunkId, Type type) inline static inherited
Registers a Chunk ID in the factory, to instantiate a given type
This can be called by client code to register additional chunk types
Parameters
chunkId
type should extend PngChunkSingle or PngChunkMultiple
Definition at line 130 of file PngChunk.cs.
{
             factoryMap.Add(chunkId, type);
         }
References Hjg.Pngcs.Chunks.PngChunk.factoryMap.
GetHashCode()
override int Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode () inline inherited
Definition at line 18 of file PngChunkSingle.cs.
{
             int prime = 31;
             int result = 1;
             result = prime * result + ((Id == null) ? 0 : Id.GetHashCode());
             return result;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id.
GetOrderingConstraint()
override ChunkOrderingConstraint Hjg.Pngcs.Chunks.PngChunkICCP.GetOrderingConstraint () inline virtual
Get ordering constrain
Returns
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 25 of file PngChunkICCP.cs.
{
             return ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT;
         }
GetProfile()
byte [] Hjg.Pngcs.Chunks.PngChunkICCP.GetProfile () inline
This uncompresses the string!
Returns
Definition at line 86 of file PngChunkICCP.cs.
{
             return ChunkHelper.compressBytes(compressedProfile, false);
         }
References Hjg.Pngcs.Chunks.ChunkHelper.compressBytes(), and Hjg.Pngcs.Chunks.PngChunkICCP.compressedProfile.
Referenced by Hjg.Pngcs.Chunks.PngChunkICCP.GetProfileAsString().
GetProfileAsString()
String Hjg.Pngcs.Chunks.PngChunkICCP.GetProfileAsString () inline
Definition at line 90 of file PngChunkICCP.cs.
{
             return ChunkHelper.ToString(GetProfile());
         }
References Hjg.Pngcs.Chunks.PngChunkICCP.GetProfile(), and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
GetProfileName()
String Hjg.Pngcs.Chunks.PngChunkICCP.GetProfileName () inline
Definition at line 78 of file PngChunkICCP.cs.
{
             return profileName;
         }
References Hjg.Pngcs.Chunks.PngChunkICCP.profileName.
ParseFromRaw()
override void Hjg.Pngcs.Chunks.PngChunkICCP.ParseFromRaw (ChunkRaw c) inline virtual
Deserialization. Given a Raw chunk, just rad, fills this chunk content
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 39 of file PngChunkICCP.cs.
{
             int pos0 = Hjg.Pngcs.Chunks.ChunkHelper.PosNullByte(chunk.Data);
             profileName = Hjg.Pngcs.PngHelperInternal.charsetLatin1.GetString(chunk.Data, 0, pos0);
             int comp = (chunk.Data[pos0 + 1] & 0xff);
             if (comp != 0)
                 throw new Exception("bad compression for ChunkTypeICCP");
             int compdatasize = chunk.Data.Length - (pos0 + 2);
             compressedProfile = new byte[compdatasize];
             System.Array.Copy((Array)(chunk.Data), pos0 + 2, (Array)(compressedProfile), 0, compdatasize);
         }
References Hjg.Pngcs.PngHelperInternal.charsetLatin1, Hjg.Pngcs.Chunks.PngChunkICCP.compressedProfile, Hjg.Pngcs.Chunks.ChunkRaw.Data, Hjg.Pngcs.Chunks.ChunkHelper.PosNullByte(), and Hjg.Pngcs.Chunks.PngChunkICCP.profileName.
SetProfileNameAndContent() [1/2]
void Hjg.Pngcs.Chunks.PngChunkICCP.SetProfileNameAndContent (String name, String profile) inline
Sets profile name and profile
Parameters
name profile name
profile profile (latin1 string)
Definition at line 63 of file PngChunkICCP.cs.
{
             SetProfileNameAndContent(name, ChunkHelper.ToBytes(profileName));
         }
References Hjg.Pngcs.Chunks.PngChunkICCP.profileName, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
SetProfileNameAndContent() [2/2]
void Hjg.Pngcs.Chunks.PngChunkICCP.SetProfileNameAndContent (String name, byte [] profile) inline
Sets profile name and profile
Parameters
name profile name
profile profile (uncompressed)
Definition at line 72 of file PngChunkICCP.cs.
{
             profileName = name;
             compressedProfile = ChunkHelper.compressBytes(profile, true);
         }
References Hjg.Pngcs.Chunks.ChunkHelper.compressBytes(), Hjg.Pngcs.Chunks.PngChunkICCP.compressedProfile, and Hjg.Pngcs.Chunks.PngChunkICCP.profileName.
ToString()
override String Hjg.Pngcs.Chunks.PngChunk.ToString () inline inherited
Basic info: Id, length, Type name
Returns
Definition at line 204 of file PngChunk.cs.
{
             return "chunk id= " + Id + " (len=" + Length + " off=" + Offset +") c=" + GetType().Name;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id, Hjg.Pngcs.Chunks.PngChunk.Length, and Hjg.Pngcs.Chunks.PngChunk.Offset.
Member Data Documentation
compressedProfile
byte [] Hjg.Pngcs.Chunks.PngChunkICCP.compressedProfile private
Definition at line 19 of file PngChunkICCP.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkICCP.CloneDataFromRead(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.GetProfile(), Hjg.Pngcs.Chunks.PngChunkICCP.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkICCP.SetProfileNameAndContent().
Crit
readonly bool Hjg.Pngcs.Chunks.PngChunk.Crit inherited
Standard basic properties, implicit in the Id
Definition at line 32 of file PngChunk.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), and Hjg.Pngcs.PngReader.ReadChunk().
ID
const String Hjg.Pngcs.Chunks.PngChunkICCP.ID = ChunkHelper.iCCP
Definition at line 15 of file PngChunkICCP.cs.
Id
readonly String Hjg.Pngcs.Chunks.PngChunk.Id inherited
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
Definition at line 28 of file PngChunk.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkSingle.Equals(), Hjg.Pngcs.Chunks.ChunkHelper.Equivalent(), Hjg.Pngcs.Chunks.ChunksList.GetChunksKeys(), Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode(), Hjg.Pngcs.Chunks.ChunkPredicateId.Matches(), Hjg.Pngcs.Chunks.ChunkPredicateId2.Matches(), Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite(), Hjg.Pngcs.Chunks.PngChunk.ToString(), and Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
ImgInfo
readonly ImageInfo Hjg.Pngcs.Chunks.PngChunk.ImgInfo protected inherited
Image basic info, mostly for some checks
Definition at line 37 of file PngChunk.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetGray(), Hjg.Pngcs.Chunks.PngChunkSBIT.GetLen(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetRGB(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetRGB(), Hjg.Pngcs.Chunks.PngChunkSBIT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkHIST.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTRNS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.setIndexEntryAsTransparent(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetRGB(), and Hjg.Pngcs.Chunks.PngChunkBKGD.SetRGB().
profileName
String Hjg.Pngcs.Chunks.PngChunkICCP.profileName private
Definition at line 17 of file PngChunkICCP.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkICCP.CloneDataFromRead(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.GetProfileName(), Hjg.Pngcs.Chunks.PngChunkICCP.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkICCP.SetProfileNameAndContent().
Property Documentation
ChunkGroup
int Hjg.Pngcs.Chunks.PngChunk.ChunkGroup get set inherited
Chunk group where it was read or writen
Definition at line 46 of file PngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite(), Hjg.Pngcs.Chunks.ChunksList.ToStringFull(), and Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
Length
int Hjg.Pngcs.Chunks.PngChunk.Length get set inherited
Definition at line 48 of file PngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.PngChunk.Factory(), Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), Hjg.Pngcs.Chunks.PngChunkSkipped.PngChunkSkipped(), and Hjg.Pngcs.Chunks.PngChunk.ToString().
Offset
long Hjg.Pngcs.Chunks.PngChunk.Offset get set inherited
Definition at line 49 of file PngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), Hjg.Pngcs.PngReader.ReadChunk(), and Hjg.Pngcs.Chunks.PngChunk.ToString().
Priority
bool Hjg.Pngcs.Chunks.PngChunk.Priority get set inherited
For writing. Queued chunks with high priority will be written as soon as possible
Definition at line 42 of file PngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.PngChunk.PngChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/ThirdParty/Required/Hjg.Pngcs/Chunks/PngChunkICCP.cs