function L(tag: Language, englishName: string, localName: string): LanguageDescription {
    return {
        tag,
        englishName,
        localName,
        description: `${englishName} (${localName}) [${tag}]`
    };
}

function C(language: Language, tag: Culture, languageName: string, name: string): CultureDescription {
    return {
        language: LanguageDescriptions.get(language)!,
        tag,
        name,
        description: `${languageName} (${name}) [${tag}]`
    };
}

export const LanguageDescriptions = new Map<Language, LanguageDescription>([
    ["af", L("af", "Afrikaans", "Afrikaans")],
    ["am", L("am", "Amharic", "አማርኛ")],
    ["ar", L("ar", "Arabic", "العربية")],
    ["arn", L("arn", "Mapudungun", "Mapudungun")],
    ["as", L("as", "Assamese", "অসমীয়া")],
    ["az", L("az", "Azerbaijani", "Azərbaycan­lı")],
    ["ba", L("ba", "Bashkir", "Башҡорт")],
    ["be", L("be", "Belarusian", "беларуская")],
    ["bg", L("bg", "Bulgarian", "български")],
    ["bn", L("bn", "Bengali", "বাংলা")],
    ["bo", L("bo", "Tibetan", "བོད་ཡིག")],
    ["br", L("br", "Breton", "brezhoneg")],
    ["bs", L("bs", "Bosnian", "bosanski/босански")],
    ["ca", L("ca", "Catalan", "català")],
    ["co", L("co", "Corsican", "Corsu")],
    ["cs", L("cs", "Czech", "čeština")],
    ["cy", L("cy", "Welsh", "Cymraeg")],
    ["da", L("da", "Danish", "dansk")],
    ["de", L("de", "German", "Deutsch")],
    ["dsb", L("dsb", "Lower Sorbian", "dolnoserbšćina")],
    ["dv", L("dv", "Divehi", "ދިވެހިބަސް")],
    ["el", L("el", "Greek", "ελληνικά")],
    ["en", L("en", "English", "English")],
    ["es", L("es", "Spanish", "español")],
    ["et", L("et", "Estonian", "eesti")],
    ["eu", L("eu", "Basque", "euskara")],
    ["fa", L("fa", "Persian", "فارسى")],
    ["fi", L("fi", "Finnish", "suomi")],
    ["fil", L("fil", "Filipino", "Filipino")],
    ["fo", L("fo", "Faroese", "føroyskt")],
    ["fr", L("fr", "French", "français")],
    ["fy", L("fy", "Frisian", "Frysk")],
    ["ga", L("ga", "Irish", "Gaeilge")],
    ["gd", L("gd", "Scottish Gaelic", "Gàidhlig")],
    ["gl", L("gl", "Galician", "galego")],
    ["gsw", L("gsw", "Alsatian", "Elsässisch")],
    ["gu", L("gu", "Gujarati", "ગુજરાતી")],
    ["ha", L("ha", "Hausa", "Hausa")],
    ["he", L("he", "Hebrew", "עברית")],
    ["hi", L("hi", "Hindi", "हिंदी")],
    ["hr", L("hr", "Croatian", "hrvatski")],
    ["hsb", L("hsb", "Upper Sorbian", "hornjoserbšćina")],
    ["hu", L("hu", "Hungarian", "magyar")],
    ["hy", L("hy", "Armenian", "Հայերեն")],
    ["id", L("id", "Indonesian", "Bahasa Indonesia")],
    ["ig", L("ig", "Igbo", "Igbo")],
    ["ii", L("ii", "Yi", "ꆈꌠꁱꂷ")],
    ["is", L("is", "Icelandic", "íslenska")],
    ["it", L("it", "Italian", "italiano")],
    ["iu", L("iu", "Inuktitut", "Inuktitut /ᐃᓄᒃᑎᑐᑦ (ᑲᓇᑕ)")],
    ["ja", L("ja", "Japanese", "日本語")],
    ["jv", L("jv", "Javanese", "ꦧꦱꦗꦮ")],
    ["ka", L("ka", "Georgian", "ქართული")],
    ["kk", L("kk", "Kazakh", "Қазақша")],
    ["kl", L("kl", "Greenlandic", "kalaallisut")],
    ["km", L("km", "Khmer", "ខ្មែរ")],
    ["kn", L("kn", "Kannada", "ಕನ್ನಡ")],
    ["ko", L("ko", "Korean", "한국어/韓國語\n조선말/朝鮮말")],
    ["kok", L("kok", "Konkani", "कोंकणी")],
    ["ky", L("ky", "Kyrgyz", "Кыргыз")],
    ["lb", L("lb", "Luxembourgish", "Lëtzebuergesch")],
    ["lo", L("lo", "Lao", "ລາວ")],
    ["lt", L("lt", "Lithuanian", "lietuvių")],
    ["lv", L("lv", "Latvian", "latviešu")],
    ["mi", L("mi", "Maori", "Reo Māori")],
    ["mk", L("mk", "Macedonian", "македонски јазик")],
    ["ml", L("ml", "Malayalam", "മലയാളം")],
    ["mn", L("mn", "Mongolian", "Монгол хэл/ᠮᠤᠨᠭᠭᠤᠯ ᠬᠡᠯᠡ")],
    ["moh", L("moh", "Mohawk", "Kanien'kéha")],
    ["mr", L("mr", "Marathi", "मराठी")],
    ["ms", L("ms", "Malay", "Bahasa Malaysia")],
    ["mt", L("mt", "Maltese", "Malti")],
    ["my", L("my", "Burmese", "Myanmar")],
    ["nb", L("nb", "Norwegian (Bokmål)", "norsk (bokmål)")],
    ["ne", L("ne", "Nepali", "नेपाली (नेपाल)")],
    ["nl", L("nl", "Dutch", "Nederlands")],
    ["nn", L("nn", "Norwegian (Nynorsk)", "norsk (nynorsk)")],
    ["no", L("no", "Norwegian", "norsk")],
    ["st", L("st", "Sesotho", "Sesotho sa Leboa")],
    ["oc", L("oc", "Occitan", "Occitan")],
    ["or", L("or", "Odia", "ଓଡ଼ିଆ")],
    ["pa", L("pa", "Punjabi", "ਪੰਜਾਬੀ")],
    ["pl", L("pl", "Polish", "polski")],
    ["prs", L("prs", "Dari", "درى")],
    ["ps", L("ps", "Pashto", "پښتو")],
    ["pt", L("pt", "Portuguese", "Português")],
    ["quc", L("quc", "K'iche", "K'iche")],
    ["qu", L("qu", "Quechua", "runasimi")],
    ["rm", L("rm", "Romansh", "Rumantsch")],
    ["ro", L("ro", "Romanian", "română")],
    ["ru", L("ru", "Russian", "русский")],
    ["rw", L("rw", "Kinyarwanda", "Kinyarwanda")],
    ["sa", L("sa", "Sanskrit", "संस्कृत")],
    ["sah", L("sah", "Yakut", "саха")],
    ["se", L("se", "Sami (Northern)", "davvisámegiella")],
    ["si", L("si", "Sinhala", "සිංහල")],
    ["sk", L("sk", "Slovak", "slovenčina")],
    ["sl", L("sl", "Slovenian", "slovenski")],
    ["sma", L("sma", "Sami (Southern)", "åarjelsaemiengiele")],
    ["smj", L("smj", "Sami (Lule)", "julevusámegiella")],
    ["smn", L("smn", "Sami (Inari)", "sämikielâ")],
    ["sms", L("sms", "Sami (Skolt)", "sääm´ǩiõll")],
    ["so", L("so", "Sudanese", "لهجة سودانية")],
    ["sq", L("sq", "Albanian", "shqipe")],
    ["sr", L("sr", "Serbian", "srpski/српски")],
    ["su", L("su", "Sundanese", "ᮘᮞ ᮞᮥᮔ᮪ᮓ")],
    ["sv", L("sv", "Swedish", "svenska")],
    ["sw", L("sw", "Kiswahili", "Kiswahili")],
    ["syc", L("syc", "Syriac", "ܣܘܪܝܝܐ")],
    ["ta", L("ta", "Tamil", "தமிழ்")],
    ["te", L("te", "Telugu", "తెలుగు")],
    ["tg", L("tg", "Tajik", "Тоҷикӣ")],
    ["th", L("th", "Thai", "ไทย")],
    ["tk", L("tk", "Turkmen", "türkmençe")],
    ["tn", L("tn", "Tswana", "Setswana")],
    ["tr", L("tr", "Turkish", "Türkçe")],
    ["tt", L("tt", "Tatar", "Татарча")],
    ["tzm", L("tzm", "Tamazight", "Tamazight")],
    ["ug", L("ug", "Uyghur", "ئۇيغۇرچە")],
    ["uk", L("uk", "Ukrainian", "українська")],
    ["ur", L("ur", "Urdu", "اُردو")],
    ["uz", L("uz", "Uzbek", "U'zbek/Ўзбек")],
    ["vi", L("vi", "Vietnamese", "Tiếng Việt/㗂越")],
    ["wo", L("wo", "Wolof", "Wolof")],
    ["wuu", L("wuu", "Wu", "吴语")],
    ["xh", L("xh", "Xhosa", "isiXhosa")],
    ["yo", L("yo", "Yoruba", "Yoruba")],
    ["yue", L("yue", "Cantonese", "廣東話")],
    ["zh", L("zh", "Chinese", "中文")],
    ["zu", L("zu", "Zulu", "isiZulu")]
]);

export const CultureDescriptions = new Map<Culture, CultureDescription>([
    ["af-ZA", C("af", "af-ZA", "Afrikaans", "South Africa")],
    ["am-ET", C("am", "am-ET", "Amharic", "Ethiopia")],
    ["ar-AE", C("ar", "ar-AE", "Arabic", "United Arab Emirates")],
    ["ar-BH", C("ar", "ar-BH", "Arabic", "Bahrain")],
    ["ar-DZ", C("ar", "ar-DZ", "Arabic", "Algeria")],
    ["ar-EG", C("ar", "ar-EG", "Arabic", "Egypt")],
    ["ar-IQ", C("ar", "ar-IQ", "Arabic", "Iraq")],
    ["ar-JO", C("ar", "ar-JO", "Arabic", "Jordan")],
    ["ar-KW", C("ar", "ar-KW", "Arabic", "Kuwait")],
    ["ar-LB", C("ar", "ar-LB", "Arabic", "Lebanon")],
    ["ar-LY", C("ar", "ar-LY", "Arabic", "Libya")],
    ["ar-MA", C("ar", "ar-MA", "Arabic", "Morocco")],
    ["ar-OM", C("ar", "ar-OM", "Arabic", "Oman")],
    ["ar-QA", C("ar", "ar-QA", "Arabic", "Qatar")],
    ["ar-SA", C("ar", "ar-SA", "Arabic", "Saudi Arabia")],
    ["ar-SY", C("ar", "ar-SY", "Arabic", "Syria")],
    ["ar-TN", C("ar", "ar-TN", "Arabic", "Tunisia")],
    ["ar-YE", C("ar", "ar-YE", "Arabic", "Yemen")],
    ["az-AZ", C("az", "az-AZ", "Azerbaijani", "Latin, Azerbaijan")],
    ["bg-BG", C("bg", "bg-BG", "Bulgarian", "Bulgaria")],
    ["bn-BD", C("bn", "bn-BD", "Bangla", "Bangladesh")],
    ["bn-IN", C("bn", "bn-IN", "Bengali", "India")],
    ["bs-BA", C("bs", "bs-BA", "Bosnian", "Bosnia and Herzegovina")],
    ["ca-ES", C("ca", "ca-ES", "Catalan", "Spain")],
    ["cs-CZ", C("cs", "cs-CZ", "Czech", "Czechia")],
    ["cy-GB", C("cy", "cy-GB", "Welsh", "United Kingdom")],
    ["da-DK", C("da", "da-DK", "Danish", "Denmark")],
    ["de-AT", C("de", "de-AT", "German", "Austria")],
    ["de-CH", C("de", "de-CH", "German", "Switzerland")],
    ["de-DE", C("de", "de-DE", "German", "Germany")],
    ["el-GR", C("el", "el-GR", "Greek", "Greece")],
    ["en-AU", C("en", "en-AU", "English", "Australia")],
    ["en-CA", C("en", "en-CA", "English", "Canada")],
    ["en-GB", C("en", "en-GB", "English", "United Kingdom")],
    ["en-HK", C("en", "en-HK", "English", "Hong Kong SAR")],
    ["en-IE", C("en", "en-IE", "English", "Ireland")],
    ["en-IN", C("en", "en-IN", "English", "India")],
    ["en-KE", C("en", "en-KE", "English", "Kenya")],
    ["en-NG", C("en", "en-NG", "English", "Nigeria")],
    ["en-NZ", C("en", "en-NZ", "English", "New Zealand")],
    ["en-PH", C("en", "en-PH", "English", "Philippines")],
    ["en-SG", C("en", "en-SG", "English", "Singapore")],
    ["en-TZ", C("en", "en-TZ", "English", "Tanzania")],
    ["en-US", C("en", "en-US", "English", "United States")],
    ["en-ZA", C("en", "en-ZA", "English", "South Africa")],
    ["es-AR", C("es", "es-AR", "Spanish", "Argentina")],
    ["es-BO", C("es", "es-BO", "Spanish", "Bolivia")],
    ["es-CL", C("es", "es-CL", "Spanish", "Chile")],
    ["es-CO", C("es", "es-CO", "Spanish", "Colombia")],
    ["es-CR", C("es", "es-CR", "Spanish", "Costa Rica")],
    ["es-CU", C("es", "es-CU", "Spanish", "Cuba")],
    ["es-DO", C("es", "es-DO", "Spanish", "Dominican Republic")],
    ["es-EC", C("es", "es-EC", "Spanish", "Ecuador")],
    ["es-ES", C("es", "es-ES", "Spanish", "Spain")],
    ["es-GQ", C("es", "es-GQ", "Spanish", "Equatorial Guinea")],
    ["es-GT", C("es", "es-GT", "Spanish", "Guatemala")],
    ["es-HN", C("es", "es-HN", "Spanish", "Honduras")],
    ["es-MX", C("es", "es-MX", "Spanish", "Mexico")],
    ["es-NI", C("es", "es-NI", "Spanish", "Nicaragua")],
    ["es-PA", C("es", "es-PA", "Spanish", "Panama")],
    ["es-PE", C("es", "es-PE", "Spanish", "Peru")],
    ["es-PR", C("es", "es-PR", "Spanish", "Puerto Rico")],
    ["es-PY", C("es", "es-PY", "Spanish", "Paraguay")],
    ["es-SV", C("es", "es-SV", "Spanish", "El Salvador")],
    ["es-US", C("es", "es-US", "Spanish", "United States")],
    ["es-UY", C("es", "es-UY", "Spanish", "Uruguay")],
    ["es-VE", C("es", "es-VE", "Spanish", "Venezuela")],
    ["et-EE", C("et", "et-EE", "Estonian", "Estonia")],
    ["eu-ES", C("eu", "eu-ES", "Basqu", "undefined")],
    ["fa-IR", C("fa", "fa-IR", "Persian", "Iran")],
    ["fi-FI", C("fi", "fi-FI", "Finnish", "Finland")],
    ["fil-PH", C("fil", "fil-PH", "Filipino", "Philippines")],
    ["fr-BE", C("fr", "fr-BE", "French", "Belgium")],
    ["fr-CA", C("fr", "fr-CA", "French", "Canada")],
    ["fr-CH", C("fr", "fr-CH", "French", "Switzerland")],
    ["fr-FR", C("fr", "fr-FR", "French", "France")],
    ["ga-IE", C("ga", "ga-IE", "Irish", "Ireland")],
    ["gl-ES", C("gl", "gl-ES", "Galicia", "undefined")],
    ["gu-IN", C("gu", "gu-IN", "Gujarati", "India")],
    ["he-IL", C("he", "he-IL", "Hebrew", "Israel")],
    ["hi-IN", C("hi", "hi-IN", "Hindi", "India")],
    ["hr-HR", C("hr", "hr-HR", "Croatian", "Croatia")],
    ["hu-HU", C("hu", "hu-HU", "Hungarian", "Hungary")],
    ["hy-AM", C("hy", "hy-AM", "Armenian", "Armenia")],
    ["id-ID", C("id", "id-ID", "Indonesian", "Indonesia")],
    ["is-IS", C("is", "is-IS", "Icelandic", "Iceland")],
    ["it-IT", C("it", "it-IT", "Italian", "Italy")],
    ["ja-JP", C("ja", "ja-JP", "Japanese", "Japan")],
    ["jv-ID", C("jv", "jv-ID", "Javanese", "Latin, Indonesia")],
    ["ka-GE", C("ka", "ka-GE", "Georgian", "Georgia")],
    ["kk-KZ", C("kk", "kk-KZ", "Kazakh", "Kazakhstan")],
    ["km-KH", C("km", "km-KH", "Khmer", "Cambodia")],
    ["kn-IN", C("kn", "kn-IN", "Kannada", "India")],
    ["ko-KR", C("ko", "ko-KR", "Korean", "Korea")],
    ["lo-LA", C("lo", "lo-LA", "Lao", "Laos")],
    ["lt-LT", C("lt", "lt-LT", "Lithuanian", "Lithuania")],
    ["lv-LV", C("lv", "lv-LV", "Latvian", "Latvia")],
    ["mk-MK", C("mk", "mk-MK", "Macedonian", "North Macedonia")],
    ["ml-IN", C("ml", "ml-IN", "Malayalam", "India")],
    ["mn-MN", C("mn", "mn-MN", "Mongolian", "Mongolia")],
    ["mr-IN", C("mr", "mr-IN", "Marathi", "India")],
    ["ms-MY", C("ms", "ms-MY", "Malay", "Malaysia")],
    ["mt-MT", C("mt", "mt-MT", "Maltese", "Malta")],
    ["my-MM", C("my", "my-MM", "Burmese", "Myanmar")],
    ["nb-NO", C("nb", "nb-NO", "Norwegian", "Bokmål, Norway")],
    ["ne-NP", C("ne", "ne-NP", "Nepali", "Nepal")],
    ["nl-BE", C("nl", "nl-BE", "Dutch", "Belgium")],
    ["nl-NL", C("nl", "nl-NL", "Dutch", "Netherlands")],
    ["pl-PL", C("pl", "pl-PL", "Polish", "Poland")],
    ["ps-AF", C("ps", "ps-AF", "Pashto", "Afghanistan")],
    ["pt-BR", C("pt", "pt-BR", "Portuguese", "Brazil")],
    ["pt-PT", C("pt", "pt-PT", "Portuguese", "Portugal")],
    ["ro-RO", C("ro", "ro-RO", "Romanian", "Romania")],
    ["ru-RU", C("ru", "ru-RU", "Russian", "Russia")],
    ["si-LK", C("si", "si-LK", "Sinhala", "Sri Lanka")],
    ["sk-SK", C("sk", "sk-SK", "Slovak", "Slovakia")],
    ["sl-SI", C("sl", "sl-SI", "Slovenian", "Slovenia")],
    ["so-SO", C("so", "so-SO", "Somali", "Somalia")],
    ["sq-AL", C("sq", "sq-AL", "Albanian", "Albania")],
    ["sr-RS", C("sr", "sr-RS", "Serbian", "Cyrillic, Serbia")],
    ["su-ID", C("su", "su-ID", "Sundanese", "Indonesia")],
    ["sv-SE", C("sv", "sv-SE", "Swedish", "Sweden")],
    ["sw-KE", C("sw", "sw-KE", "Swahili", "Kenya")],
    ["sw-TZ", C("sw", "sw-TZ", "Swahili", "Tanzania")],
    ["ta-IN", C("ta", "ta-IN", "Tamil", "India")],
    ["ta-LK", C("ta", "ta-LK", "Tamil", "Sri Lanka")],
    ["ta-MY", C("ta", "ta-MY", "Tamil", "Malaysia")],
    ["ta-SG", C("ta", "ta-SG", "Tamil", "Singapore")],
    ["te-IN", C("te", "te-IN", "Telugu", "India")],
    ["th-TH", C("th", "th-TH", "Thai", "Thailand")],
    ["tr-TR", C("tr", "tr-TR", "Turkish", "Turkey")],
    ["uk-UA", C("uk", "uk-UA", "Ukrainian", "Ukraine")],
    ["ur-IN", C("ur", "ur-IN", "Urdu", "India")],
    ["ur-PK", C("ur", "ur-PK", "Urdu", "Pakistan")],
    ["uz-UZ", C("uz", "uz-UZ", "Uzbek", "Latin, Uzbekistan")],
    ["vi-VN", C("vi", "vi-VN", "Vietnamese", "Vietnam")],
    ["wuu-CN", C("wuu", "wuu-CN", "Chinese", "Wu, Simplified")],
    ["yue-CN", C("yue", "yue-CN", "Chinese", "Cantonese, Simplified")],
    ["zh-CN", C("zh", "zh-CN", "Chinese", "Mandarin, Simplified")],
    ["zh-CN-henan", C("zh", "zh-CN-henan", "Chinese", "Zhongyuan Mandarin Henan, Simplified")],
    ["zh-CN-liaoning", C("zh", "zh-CN-liaoning", "Chinese", "Northeastern Mandarin, Simplified")],
    ["zh-CN-shaanxi", C("zh", "zh-CN-shaanxi", "Chinese", "Zhongyuan Mandarin Shaanxi, Simplified")],
    ["zh-CN-shandong", C("zh", "zh-CN-shandong", "Chinese", "Jilu Mandarin, Simplified")],
    ["zh-CN-sichuan", C("zh", "zh-CN-sichuan", "Chinese", "Southwestern Mandarin, Simplified")],
    ["zh-HK", C("zh", "zh-HK", "Chinese", "Cantonese, Traditional")],
    ["zh-TW", C("zh", "zh-TW", "Chinese", "Taiwanese Mandarin, Traditional")],
    ["zu-ZA", C("zu", "zu-ZA", "Zulu", "South Africa")]
]);