Juniper: Juniper.World.GIS.Google.Geocoding.GeocodingRequest Class Reference
Juniper.World.GIS.Google.Geocoding.GeocodingRequest Class Reference
Public Member Functions
GeocodingRequest (string apiKey)
void SetBounds (LatLngPoint southWest, LatLngPoint northEast)
Protected Attributes
override string InternalCacheID
Properties
string Place [get, set]
string Address [get, set]
string PostalCodeFilter [get, set]
string CountryFilter [get, set]
string RouteHint [get, set]
string LocalityHint [get, set]
string AdministrativeAreaHint [get, set]
GeometryViewport? Bounds [get, set]
string Region [get, set]
string Language [get, set]
override Uri AuthenticatedURI [get]
Private Member Functions
void RefreshComponents ()
string SetComponent (AddressComponentTypes key, string value)
Private Attributes
string place_id
string address
readonly Dictionary< AddressComponentTypes, string > components = new Dictionary<AddressComponentTypes, string>()
GeometryViewport bounds
string region
Detailed Description
Definition at line 5 of file GeocodingRequest.cs.
Constructor & Destructor Documentation
GeocodingRequest()
Juniper.World.GIS.Google.Geocoding.GeocodingRequest.GeocodingRequest (string apiKey) inline
Definition at line 15 of file GeocodingRequest.cs.
             : base(apiKey)
         { }
Member Function Documentation
RefreshComponents()
void Juniper.World.GIS.Google.Geocoding.GeocodingRequest.RefreshComponents () inline private
Definition at line 45 of file GeocodingRequest.cs.
         {
             SetQuery(nameof(components), components?.ToString(":", "|"));
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingRequest.components.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingRequest.SetComponent().
SetBounds()
void Juniper.World.GIS.Google.Geocoding.GeocodingRequest.SetBounds (LatLngPoint southWest, LatLngPoint northEast) inline
Definition at line 87 of file GeocodingRequest.cs.
         {
             Bounds = new GeometryViewport(southWest, northEast);
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingRequest.Bounds.
SetComponent()
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.SetComponent (AddressComponentTypes key, string value) inline private
Definition at line 50 of file GeocodingRequest.cs.
         {
             components[key] = value;
             RefreshComponents();
             return value;
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingRequest.components, and Juniper.World.GIS.Google.Geocoding.GeocodingRequest.RefreshComponents().
Member Data Documentation
address
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.address private
Definition at line 8 of file GeocodingRequest.cs.
bounds
GeometryViewport Juniper.World.GIS.Google.Geocoding.GeocodingRequest.bounds private
Definition at line 12 of file GeocodingRequest.cs.
components
readonly Dictionary<AddressComponentTypes, string> Juniper.World.GIS.Google.Geocoding.GeocodingRequest.components = new Dictionary<AddressComponentTypes, string>() private
Definition at line 10 of file GeocodingRequest.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingRequest.RefreshComponents(), and Juniper.World.GIS.Google.Geocoding.GeocodingRequest.SetComponent().
InternalCacheID
override string Juniper.World.GIS.Google.AbstractGoogleMapsRequest< MediaTypeT >.InternalCacheID protected inherited
Definition at line 25 of file AbstractGoogleMapsRequest.cs.
place_id
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.place_id private
Definition at line 7 of file GeocodingRequest.cs.
region
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.region private
Definition at line 13 of file GeocodingRequest.cs.
Property Documentation
Address
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.Address get set
Definition at line 33 of file GeocodingRequest.cs.
         {
             get { return address; }
             set
             {
                 address = value;
                 SetQuery(nameof(address), address);
                 place_id = default;
                 RemoveQuery(nameof(place_id));
             }
         }
AdministrativeAreaHint
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.AdministrativeAreaHint get set
Definition at line 82 of file GeocodingRequest.cs.
         {
             get { return components.Get(AddressComponentTypes.administrative_area, default); }
             set { SetComponent(AddressComponentTypes.administrative_area, value); }
         }
AuthenticatedURI
override Uri Juniper.World.GIS.Google.AbstractGoogleMapsRequest< MediaTypeT >.AuthenticatedURI get protected inherited
Definition at line 29 of file AbstractGoogleMapsRequest.cs.
         {
             get
             {
                 var unsignedUri = base.AuthenticatedURI;
                 var unsignedUriBuilder = new UriBuilder(unsignedUri);
                 unsignedUriBuilder.AddQuery("key", apiKey);
                 var unsignedUriWithKey = unsignedUriBuilder.Uri;
                 if (string.IsNullOrEmpty(signingKey))
                 {
                     return unsignedUriWithKey;
                 }
                 else
                 {
                     var pkBytes = Convert.FromBase64String(signingKey.FromGoogleModifiedBase64());
 #pragma warning disable CA5350 // Do Not Use Weak Cryptographic Algorithms
                     // Google requires use of this particular hashing algorithm.
                     using var hasher = new HMACSHA1(pkBytes);
 #pragma warning restore CA5350 // Do Not Use Weak Cryptographic Algorithms
                     var urlBytes = Encoding.ASCII.GetBytes(unsignedUriWithKey.LocalPath + unsignedUriWithKey.Query);
                     var hash = hasher.ComputeHash(urlBytes);
                     var signature = Convert.ToBase64String(hash).ToGoogleModifiedBase64();
                     var signedUri = new UriBuilder(unsignedUriWithKey);
                     signedUri.AddQuery("signature", signature);
                     return signedUri.Uri;
                 }
             }
         }
Bounds
GeometryViewport? Juniper.World.GIS.Google.Geocoding.GeocodingRequest.Bounds get set
Definition at line 93 of file GeocodingRequest.cs.
         {
             get { return bounds; }
             set
             {
                 bounds = value;
                 SetQuery(
                     nameof(bounds),
                     bounds == null
                         ? null
                         : $"{bounds.SouthWest}|{bounds.NorthEast}");
             }
         }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingRequest.SetBounds().
CountryFilter
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.CountryFilter get set
Definition at line 64 of file GeocodingRequest.cs.
         {
             get { return components.Get(AddressComponentTypes.country, default); }
             set { SetComponent(AddressComponentTypes.country, value); }
         }
Language
string Juniper.World.GIS.Google.Geocoding.AbstractGeocodingRequest.Language get set inherited
Definition at line 13 of file AbstractGeocodingRequest.cs.
         {
             get { return language; }
             set
             {
                 language = value;
                 SetQuery(nameof(language), language);
             }
         }
LocalityHint
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.LocalityHint get set
Definition at line 76 of file GeocodingRequest.cs.
         {
             get { return components.Get(AddressComponentTypes.locality, default); }
             set { SetComponent(AddressComponentTypes.locality, value); }
         }
Place
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.Place get set
Definition at line 20 of file GeocodingRequest.cs.
         {
             get { return place_id; }
             set
             {
                 place_id = value;
                 SetQuery(nameof(place_id), place_id);
                 address = default;
                 RemoveQuery(nameof(address));
             }
         }
PostalCodeFilter
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.PostalCodeFilter get set
Definition at line 58 of file GeocodingRequest.cs.
         {
             get { return components.Get(AddressComponentTypes.postal_code, default); }
             set { SetComponent(AddressComponentTypes.postal_code, value); }
         }
Region
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.Region get set
Definition at line 107 of file GeocodingRequest.cs.
         {
             get { return region; }
             set
             {
                 region = value;
                 SetQuery(nameof(region), region);
             }
         }
RouteHint
string Juniper.World.GIS.Google.Geocoding.GeocodingRequest.RouteHint get set
Definition at line 70 of file GeocodingRequest.cs.
         {
             get { return components.Get(AddressComponentTypes.route, default); }
             set { SetComponent(AddressComponentTypes.route, value); }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/Geocoding/GeocodingRequest.cs