Juniper: Juniper.Unity.Haptics.DefaultHaptics Class Reference
Juniper.Unity.Haptics.DefaultHaptics Class Reference
When no specific haptic implementation is available, but we know the system supports haptics, we fallback to using Unity's built-in Vibrate function, which is pretty primitive.
Public Member Functions
void Awake ()
override void Cancel ()
Cancel the current vibration, whatever it is.
override void Play (HapticExpression expr)
Play a canned haptic pattern.
override void Play (params HapticPatternElement[] points)
Play a haptic pattern.
override void Play (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
override void Play (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
override void Vibrate (HapticPatternElement point)
Play a single element of a haptic pattern.
override void Vibrate (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
override void Vibrate (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
Protected Member Functions
override IEnumerator VibrateCoroutine (long milliseconds, float amplitude)
Play a single vibration of a set length of time.
virtual IEnumerator VibrateCoroutine (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
virtual IEnumerator PlayCoroutine (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
virtual IEnumerator PlayCoroutine (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
Private Member Functions
void Gamepad_GamepadAdded (object sender, Gamepad e)
void Gamepad_GamepadRemoved (object sender, Gamepad e)
void SetVibration (float amplitude)
Set a haptic pulse playing at a set amplitude.
Private Attributes
Gamepad gp
Detailed Description
When no specific haptic implementation is available, but we know the system supports haptics, we fallback to using Unity's built-in Vibrate function, which is pretty primitive.
Definition at line 24 of file DefaultHaptics.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Haptics.DefaultHaptics.Awake () inline
Definition at line 28 of file DefaultHaptics.cs.
         {
             gp = Gamepad.Gamepads.FirstOrDefault();
             if (gp == null)
             {
                 Gamepad.GamepadAdded += Gamepad_GamepadAdded;
                 Gamepad.GamepadRemoved += Gamepad_GamepadRemoved;
             }
         }
References Juniper.Unity.Haptics.DefaultHaptics.Gamepad_GamepadAdded(), Juniper.Unity.Haptics.DefaultHaptics.Gamepad_GamepadRemoved(), and Juniper.Unity.Haptics.DefaultHaptics.gp.
Cancel()
override void Juniper.Unity.Haptics.DefaultHaptics.Cancel () inline virtual
Cancel the current vibration, whatever it is.
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 77 of file DefaultHaptics.cs.
         {
             base.Cancel();
             SetVibration(0);
         }
References Juniper.Unity.Haptics.DefaultHaptics.SetVibration().
Gamepad_GamepadAdded()
void Juniper.Unity.Haptics.DefaultHaptics.Gamepad_GamepadAdded (object sender, Gamepad e) inline private
Definition at line 38 of file DefaultHaptics.cs.
         {
             gp = e;
         }
References Juniper.Unity.Haptics.DefaultHaptics.gp.
Referenced by Juniper.Unity.Haptics.DefaultHaptics.Awake().
Gamepad_GamepadRemoved()
void Juniper.Unity.Haptics.DefaultHaptics.Gamepad_GamepadRemoved (object sender, Gamepad e) inline private
Definition at line 43 of file DefaultHaptics.cs.
         {
             if (gp == e)
             {
                 gp = null;
             }
         }
References Juniper.Unity.Haptics.DefaultHaptics.gp.
Referenced by Juniper.Unity.Haptics.DefaultHaptics.Awake().
Play() [1/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (HapticExpression expr) inline virtual inherited
Play a canned haptic pattern.
Parameters
expr
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Reimplemented in Juniper.Unity.Haptics.WindowsMRHaptics.
Definition at line 23 of file AbstractHapticExpressor.cs.
         {
             HapticPatternElement.Play(this, expr);
         }
References Juniper.Unity.Haptics.HapticPatternElement.Play().
Play() [2/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (params HapticPatternElement [] points) inline virtual inherited
Play a haptic pattern.
Parameters
points
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 32 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(points));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [3/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern) inline virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 59 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [4/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern, float [] amplitudes) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 69 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern, amplitudes));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
PlayCoroutine() [1/2]
virtual IEnumerator Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern) inline protected virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Definition at line 97 of file AbstractHapticExpressor.cs.
         {
             float amplitude = 1;
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitude);
                 amplitude = 1 - amplitude;
             }
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Referenced by Juniper.Unity.Haptics.AbstractHapticExpressor.Play().
PlayCoroutine() [2/2]
virtual IEnumerator Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern, float [] amplitudes) inline protected virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Definition at line 112 of file AbstractHapticExpressor.cs.
         {
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitudes[i]);
             }
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
SetVibration()
void Juniper.Unity.Haptics.DefaultHaptics.SetVibration (float amplitude) inline private
Set a haptic pulse playing at a set amplitude.
Parameters
amplitude The strength of the vibration.
Definition at line 57 of file DefaultHaptics.cs.
         {
 #if UNITY_STANDALONE || UNITY_EDITOR
             GamePad.SetVibration(PlayerIndex.One, amplitude, amplitude);
 #elif UNITY_XR_WINDOWSMR_METRO
             if (gp != null)
             {
                 gp.Vibration = new GamepadVibration
                 {
                     LeftMotor = amplitude,
                     RightMotor = amplitude
                 };
             }
 #endif
         }
References Juniper.Unity.Haptics.DefaultHaptics.gp.
Referenced by Juniper.Unity.Haptics.DefaultHaptics.Cancel(), and Juniper.Unity.Haptics.DefaultHaptics.VibrateCoroutine().
Vibrate() [1/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (HapticPatternElement point) inline virtual inherited
Play a single element of a haptic pattern.
Parameters
point
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 41 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(point));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [2/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds) inline virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 50 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [3/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds, float amplitude) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 79 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds, amplitude));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
VibrateCoroutine() [1/2]
override IEnumerator Juniper.Unity.Haptics.DefaultHaptics.VibrateCoroutine (long milliseconds, float amplitude) inline protected virtual
Play a single vibration of a set length of time.
Parameters
milliseconds Milliseconds.
amplitude The strenght of vibration (ignored).
Implements Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 88 of file DefaultHaptics.cs.
         {
             var seconds = Units.Milliseconds.Seconds(milliseconds);
 #if UNITY_STANDALONE || UNITY_EDITOR || UNITY_XR_WINDOWSMR_METRO
             SetVibration(amplitude);
 #elif HAS_HAPTICS
             if (amplitude > 0.25f)
             {
                 var now = Time.time;
                 while (Time.time - now < seconds)
                 {
                     Handheld.Vibrate();
                     yield return null;
                 }
             }
             else
             {
 #endif
             yield return new WaitForSeconds(seconds);
 #if !UNITY_STANDALONE && !UNITY_EDITOR && !UNITY_XR_WINDOWSMR_METRO && HAS_HAPTICS
             }
 #endif
         }
References Juniper.Units.Milliseconds.Seconds(), and Juniper.Unity.Haptics.DefaultHaptics.SetVibration().
VibrateCoroutine() [2/2]
virtual IEnumerator Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine (long milliseconds) inline protected virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Definition at line 88 of file AbstractHapticExpressor.cs.
         {
             yield return VibrateCoroutine(milliseconds, 1);
         }
Referenced by Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine(), Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate(), and Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Member Data Documentation
gp
Gamepad Juniper.Unity.Haptics.DefaultHaptics.gp private
Definition at line 27 of file DefaultHaptics.cs.
Referenced by Juniper.Unity.Haptics.DefaultHaptics.Awake(), Juniper.Unity.Haptics.DefaultHaptics.Gamepad_GamepadAdded(), Juniper.Unity.Haptics.DefaultHaptics.Gamepad_GamepadRemoved(), and Juniper.Unity.Haptics.DefaultHaptics.SetVibration().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Haptics/DefaultHaptics.cs