Juniper: libStreamSDK.NativeMethods Class Reference
libStreamSDK.NativeMethods Class Reference
P/Invoke adapter for the MindWave ThinkGear C-API
Public Member Functions
static int TG_GetVersion ()
static int TG_GetNewConnectionId ()
static int TG_SetStreamLog (int connectionId, string filename)
static int TG_SetDataLog (int connectionId, string filename)
static int TG_WriteStreamLog (int connectionId, int insertTimestamp, string msg)
static int TG_WriteDataLog (int connectionId, int insertTimestamp, string msg)
static int TG_Connect (int connectionId, string serialPortName, int serialBaudrate, int serialDataFormat)
static int TG_ReadPackets (int connectionId, int numPackets)
static int TG_GetValueStatus (int connectionId, int dataType)
static float TG_GetValue (int connectionId, int dataType)
static int TG_SendByte (int connectionId, int b)
static int TG_SetBaudrate (int connectionId, int serialBaudrate)
static int TG_EnableAutoRead (int connectionId, int enable)
static void TG_Disconnect (int connectionId)
static void TG_FreeConnection (int connectionId)
static int MWM15_getFilterType (int connectionId)
static int MWM15_setFilterType (int connectionId, int filterType)
Static Public Member Functions
static int TG_GetValueStatus (int connectionId, DataType dataType)
static float TG_GetValue (int connectionId, DataType dataType)
Public Attributes
const int TG_MAX_CONNECTION_HANDLES = 128
Private Attributes
const string DLL_NAME = "thinkgear.dll"
Detailed Description
P/Invoke adapter for the MindWave ThinkGear C-API
Definition at line 9 of file NativeMethods.cs.
Member Function Documentation
MWM15_getFilterType()
static int libStreamSDK.NativeMethods.MWM15_getFilterType (int connectionId)
MWM15_setFilterType()
static int libStreamSDK.NativeMethods.MWM15_setFilterType (int connectionId, int filterType)
TG_Connect()
static int libStreamSDK.NativeMethods.TG_Connect (int connectionId, string serialPortName, int serialBaudrate, int serialDataFormat)
TG_Disconnect()
static void libStreamSDK.NativeMethods.TG_Disconnect (int connectionId)
TG_EnableAutoRead()
static int libStreamSDK.NativeMethods.TG_EnableAutoRead (int connectionId, int enable)
TG_FreeConnection()
static void libStreamSDK.NativeMethods.TG_FreeConnection (int connectionId)
TG_GetNewConnectionId()
static int libStreamSDK.NativeMethods.TG_GetNewConnectionId ()
TG_GetValue() [1/2]
static float libStreamSDK.NativeMethods.TG_GetValue (int connectionId, int dataType)
Referenced by libStreamSDK.NativeMethods.TG_GetValue().
TG_GetValue() [2/2]
static float libStreamSDK.NativeMethods.TG_GetValue (int connectionId, DataType dataType) inline static
Definition at line 53 of file NativeMethods.cs.
         {
             return TG_GetValue(connectionId, (int)dataType);
         }
References libStreamSDK.NativeMethods.TG_GetValue().
TG_GetValueStatus() [1/2]
static int libStreamSDK.NativeMethods.TG_GetValueStatus (int connectionId, int dataType)
Referenced by libStreamSDK.NativeMethods.TG_GetValueStatus().
TG_GetValueStatus() [2/2]
static int libStreamSDK.NativeMethods.TG_GetValueStatus (int connectionId, DataType dataType) inline static
Definition at line 45 of file NativeMethods.cs.
         {
             return TG_GetValueStatus(connectionId, (int)dataType);
         }
References libStreamSDK.NativeMethods.TG_GetValueStatus().
TG_GetVersion()
static int libStreamSDK.NativeMethods.TG_GetVersion ()
TG_ReadPackets()
static int libStreamSDK.NativeMethods.TG_ReadPackets (int connectionId, int numPackets)
TG_SendByte()
static int libStreamSDK.NativeMethods.TG_SendByte (int connectionId, int b)
TG_SetBaudrate()
static int libStreamSDK.NativeMethods.TG_SetBaudrate (int connectionId, int serialBaudrate)
TG_SetDataLog()
static int libStreamSDK.NativeMethods.TG_SetDataLog (int connectionId, string filename)
TG_SetStreamLog()
static int libStreamSDK.NativeMethods.TG_SetStreamLog (int connectionId, string filename)
TG_WriteDataLog()
static int libStreamSDK.NativeMethods.TG_WriteDataLog (int connectionId, int insertTimestamp, string msg)
TG_WriteStreamLog()
static int libStreamSDK.NativeMethods.TG_WriteStreamLog (int connectionId, int insertTimestamp, string msg)
Member Data Documentation
DLL_NAME
const string libStreamSDK.NativeMethods.DLL_NAME = "thinkgear.dll" private
Definition at line 14 of file NativeMethods.cs.
TG_MAX_CONNECTION_HANDLES
const int libStreamSDK.NativeMethods.TG_MAX_CONNECTION_HANDLES = 128
Definition at line 79 of file NativeMethods.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.NeuroSky/NativeMethods.cs