Juniper: Juniper.Compression.Zip.Decompressor Class Reference
Juniper.Compression.Zip.Decompressor Class Reference
Functions for dealing with Zip files.
Static Public Member Functions
static ZipArchive Open (FileInfo file)
static ZipArchive Open (string fileName)
static void CopyFile (this ZipArchive zip, string entryPath, Stream copyTo, IProgress prog=null)
Retrieves a single file from a zip file.
static void CopyFile (this ZipArchive zip, string entryPath, FileInfo copyToFile, IProgress prog=null)
static void CopyFile (this ZipArchive copyFromZip, string entryPath, string copyToFileName, IProgress prog=null)
static void CopyFile (Stream copyFromStream, string entryPath, Stream copyToStream, IProgress prog=null)
static void CopyFile (FileInfo copyFromFile, string entryPath, Stream copyToStream, IProgress prog=null)
static void CopyFile (string copyFromFileName, string entryPath, Stream copyToStream, IProgress prog=null)
static Stream GetFile (this ZipArchive zip, string entryPath, IProgress prog=null)
static Stream GetFile (Stream zipStream, string entryPath, IProgress prog=null)
static Stream GetFile (FileInfo file, string entryPath, IProgress prog=null)
static Stream GetFile (string fileName, string entryPath, IProgress prog=null)
static IEnumerable< CompressedFileInfo > Entries (this ZipArchive zip, IProgress prog=null)
Enumerates all of the entires in a single Zip archive so that it can be used more easily with c#'s for-each.
static IEnumerable< CompressedFileInfo > Entries (Stream stream, IProgress prog=null)
static IEnumerable< CompressedFileInfo > Entries (FileInfo file, IProgress prog=null)
static IEnumerable< CompressedFileInfo > Entries (string fileName, IProgress prog=null)
static void Decompress (this ZipArchive zip, DirectoryInfo outputDirectory, string entryPrefix=null, IProgress prog=null)
static void Decompress (Stream stream, DirectoryInfo outputDirectory, string entryPrefix=null, IProgress prog=null)
static void Decompress (Stream stream, string outputDirectoryName, string entryPrefix=null, IProgress prog=null)
static void Decompress (FileInfo zipFile, DirectoryInfo outputDirectory, string entryPrefix=null, IProgress prog=null)
static void Decompress (FileInfo zipFile, string outputDirectoryName, string entryPrefix=null, IProgress prog=null)
static void Decompress (string fileName, DirectoryInfo outputDirectory, string entryPrefix=null, IProgress prog=null)
static void Decompress (string fileName, string outputDirectoryName, string entryPrefix=null, IProgress prog=null)
Static Private Member Functions
static ZipArchive Open (Stream stream)
Detailed Description
Functions for dealing with Zip files.
Definition at line 13 of file Decompressor.cs.
Member Function Documentation
CopyFile() [1/6]
static void Juniper.Compression.Zip.Decompressor.CopyFile (this ZipArchive zip, string entryPath, Stream copyTo, IProgress prog = null) inline static
Retrieves a single file from a zip file.
Parameters
fileName The zip file in which to find the file.
entryPath The file to find in the zip file.
copyTo A stream to which to copy the file, before closing the zipFile.
prog A prog tracking object, defaults to null (i.e. no prog tracking).
Definition at line 63 of file Decompressor.cs.
         {
             if (zip is null)
             {
                 throw new ArgumentNullException(nameof(zip));
             }
             if (copyTo is null)
             {
                 throw new ArgumentNullException(nameof(copyTo));
             }
             var entry = zip.GetEntry(entryPath);
             if (entry is null)
             {
                 throw new FileNotFoundException($"Could not find file {entryPath} in the zip file.");
             }
             using var copyFrom = entry.Open();
             using var progStream = new ProgressStream(copyFrom, entry.Length, prog, false);
             progStream.CopyTo(copyTo);
         }
Referenced by Juniper.Compression.Zip.Decompressor.CopyFile().
CopyFile() [2/6]
static void Juniper.Compression.Zip.Decompressor.CopyFile (this ZipArchive zip, string entryPath, FileInfo copyToFile, IProgress prog = null) inline static
Definition at line 86 of file Decompressor.cs.
         {
             if (zip is null)
             {
                 throw new ArgumentNullException(nameof(zip));
             }
             if (copyToFile is null)
             {
                 throw new ArgumentNullException(nameof(copyToFile));
             }
             copyToFile.Directory.Create();
             using var copyTo = copyToFile.Create();
             zip.CopyFile(entryPath, copyTo, prog);
         }
CopyFile() [3/6]
static void Juniper.Compression.Zip.Decompressor.CopyFile (this ZipArchive copyFromZip, string entryPath, string copyToFileName, IProgress prog = null) inline static
Definition at line 103 of file Decompressor.cs.
         {
             if (copyFromZip is null)
             {
                 throw new ArgumentNullException(nameof(copyFromZip));
             }
             if (copyToFileName is null)
             {
                 throw new ArgumentNullException(nameof(copyToFileName));
             }
             if (copyToFileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(copyToFileName));
             }
             copyFromZip.CopyFile(entryPath, new FileInfo(copyToFileName), prog);
         }
CopyFile() [4/6]
static void Juniper.Compression.Zip.Decompressor.CopyFile (Stream copyFromStream, string entryPath, Stream copyToStream, IProgress prog = null) inline static
Definition at line 124 of file Decompressor.cs.
         {
             if (copyFromStream is null)
             {
                 throw new ArgumentNullException(nameof(copyFromStream));
             }
             if (copyToStream is null)
             {
                 throw new ArgumentNullException(nameof(copyToStream));
             }
             using var zip = Open(copyFromStream);
             zip.CopyFile(entryPath, copyToStream, prog);
         }
References Juniper.Compression.Zip.Decompressor.Open().
CopyFile() [5/6]
static void Juniper.Compression.Zip.Decompressor.CopyFile (FileInfo copyFromFile, string entryPath, Stream copyToStream, IProgress prog = null) inline static
Definition at line 140 of file Decompressor.cs.
         {
             if (copyFromFile is null)
             {
                 throw new ArgumentNullException(nameof(copyFromFile));
             }
             if (!copyFromFile.Exists)
             {
                 throw new FileNotFoundException("File not found", copyFromFile.FullName);
             }
             using var stream = copyFromFile.OpenRead();
             CopyFile(stream, entryPath, copyToStream, prog);
         }
References Juniper.Compression.Zip.Decompressor.CopyFile().
CopyFile() [6/6]
static void Juniper.Compression.Zip.Decompressor.CopyFile (string copyFromFileName, string entryPath, Stream copyToStream, IProgress prog = null) inline static
Definition at line 156 of file Decompressor.cs.
         {
             if (copyToStream is null)
             {
                 throw new ArgumentNullException(nameof(copyToStream));
             }
             if (copyFromFileName is null)
             {
                 throw new ArgumentNullException(nameof(copyFromFileName));
             }
             if (copyFromFileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(copyFromFileName));
             }
             CopyFile(new FileInfo(copyFromFileName), entryPath, copyToStream, prog);
         }
References Juniper.Compression.Zip.Decompressor.CopyFile().
Decompress() [1/7]
static void Juniper.Compression.Zip.Decompressor.Decompress (this ZipArchive zip, DirectoryInfo outputDirectory, string entryPrefix = null, IProgress prog = null) inline static
Definition at line 300 of file Decompressor.cs.
         {
             if (zip is null)
             {
                 throw new ArgumentNullException(nameof(zip));
             }
             if (outputDirectory is null)
             {
                 throw new ArgumentNullException(nameof(outputDirectory));
             }
             if (outputDirectory.IsJunction())
             {
                 return;
             }
             var noPrefix = string.IsNullOrEmpty(entryPrefix);
             var i = 0;
             foreach (var entry in zip.Entries)
             {
                 prog.Report(i++, zip.Entries.Count);
                 var fileName = entry.FullName;
                 if (noPrefix || fileName.StartsWith(entryPrefix, StringComparison.InvariantCulture))
                 {
                     if (!noPrefix)
                     {
                         fileName = fileName.Remove(0, entryPrefix.Length);
                     }
                     var outputPath = Path.Combine(outputDirectory.FullName, fileName);
                     var outputFile = new FileInfo(outputPath);
                     var outputFileDirectory = outputFile.Directory;
                     if (!outputFileDirectory.Exists)
                     {
                         outputFileDirectory.Create();
                     }
                     try
                     {
                         using var outputStream = outputFile.Create();
                         using var inputStream = entry.Open();
                         inputStream.CopyTo(outputStream);
                         outputStream.Flush();
                     }
                     catch { }
                 }
             }
             prog.Report(i, zip.Entries.Count);
         }
Referenced by Juniper.Compression.Zip.Decompressor.Decompress(), Juniper.ConfigurationManagement.JuniperPackage.Install(), and Juniper.IO.StreamingAssetsCacheLayer.UnpackAPKAsync().
Decompress() [2/7]
static void Juniper.Compression.Zip.Decompressor.Decompress (Stream stream, DirectoryInfo outputDirectory, string entryPrefix = null, IProgress prog = null) inline static
Definition at line 352 of file Decompressor.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             if (outputDirectory is null)
             {
                 throw new ArgumentNullException(nameof(outputDirectory));
             }
             using var zip = Open(stream);
             zip.Decompress(outputDirectory, entryPrefix, prog);
         }
References Juniper.Compression.Zip.Decompressor.Open().
Decompress() [3/7]
static void Juniper.Compression.Zip.Decompressor.Decompress (Stream stream, string outputDirectoryName, string entryPrefix = null, IProgress prog = null) inline static
Definition at line 368 of file Decompressor.cs.
         {
             if (outputDirectoryName is null)
             {
                 throw new ArgumentNullException(nameof(outputDirectoryName));
             }
             Decompress(stream, new DirectoryInfo(outputDirectoryName), entryPrefix, prog);
         }
References Juniper.Compression.Zip.Decompressor.Decompress().
Decompress() [4/7]
static void Juniper.Compression.Zip.Decompressor.Decompress (FileInfo zipFile, DirectoryInfo outputDirectory, string entryPrefix = null, IProgress prog = null) inline static
Definition at line 378 of file Decompressor.cs.
         {
             if (zipFile is null)
             {
                 throw new ArgumentNullException(nameof(zipFile));
             }
             if (!zipFile.Exists)
             {
                 throw new FileNotFoundException($"File not found: {zipFile.FullName}", zipFile.FullName);
             }
             var stream = zipFile.OpenRead();
             Decompress(stream, outputDirectory, entryPrefix, prog);
         }
References Juniper.Compression.Zip.Decompressor.Decompress().
Decompress() [5/7]
static void Juniper.Compression.Zip.Decompressor.Decompress (FileInfo zipFile, string outputDirectoryName, string entryPrefix = null, IProgress prog = null) inline static
Definition at line 394 of file Decompressor.cs.
         {
             if (outputDirectoryName is null)
             {
                 throw new ArgumentNullException(nameof(outputDirectoryName));
             }
             Decompress(zipFile, new DirectoryInfo(outputDirectoryName), entryPrefix, prog);
         }
References Juniper.Compression.Zip.Decompressor.Decompress().
Decompress() [6/7]
static void Juniper.Compression.Zip.Decompressor.Decompress (string fileName, DirectoryInfo outputDirectory, string entryPrefix = null, IProgress prog = null) inline static
Definition at line 404 of file Decompressor.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             Decompress(new FileInfo(fileName), outputDirectory, entryPrefix, prog);
         }
References Juniper.Compression.Zip.Decompressor.Decompress().
Decompress() [7/7]
static void Juniper.Compression.Zip.Decompressor.Decompress (string fileName, string outputDirectoryName, string entryPrefix = null, IProgress prog = null) inline static
Definition at line 419 of file Decompressor.cs.
         {
             if (outputDirectoryName is null)
             {
                 throw new ArgumentNullException(nameof(outputDirectoryName));
             }
             Decompress(fileName, new DirectoryInfo(outputDirectoryName), entryPrefix, prog);
         }
References Juniper.Compression.Zip.Decompressor.Decompress().
Entries() [1/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Zip.Decompressor.Entries (this ZipArchive zip, IProgress prog = null) inline static
Enumerates all of the entires in a single Zip archive so that it can be used more easily with c#'s for-each.
Parameters
zip A zipfile stream
prog A prog tracking object, defaults to null (i.e. no prog tracking).
Returns
A lazy collection of ZipArchiveEntry objects.
Definition at line 238 of file Decompressor.cs.
         {
             if (zip is null)
             {
                 throw new ArgumentNullException(nameof(zip));
             }
             var i = 0;
             foreach (var entry in zip.Entries)
             {
                 prog.Report(i++, zip.Entries.Count);
                 yield return new CompressedFileInfo(entry);
             }
             prog.Report(i, zip.Entries.Count);
         }
Referenced by Juniper.Compression.Zip.Decompressor.Entries(), Juniper.ConfigurationManagement.JuniperPackage.GetContentFiles(), and Juniper.IO.ZipFileCacheLayer.GetContentReferences().
Entries() [2/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Zip.Decompressor.Entries (Stream stream, IProgress prog = null) inline static
Definition at line 255 of file Decompressor.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             using var zip = Open(stream);
             foreach (var entry in zip.Entries(prog))
             {
                 yield return entry;
             }
         }
References Juniper.Compression.Zip.Decompressor.Open().
Entries() [3/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Zip.Decompressor.Entries (FileInfo file, IProgress prog = null) inline static
Definition at line 269 of file Decompressor.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             if (!file.Exists)
             {
                 throw new FileNotFoundException("File not found", file.FullName);
             }
             var stream = file.OpenRead();
             return Entries(stream, prog);
         }
References Juniper.Compression.Zip.Decompressor.Entries().
Entries() [4/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Zip.Decompressor.Entries (string fileName, IProgress prog = null) inline static
Definition at line 285 of file Decompressor.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return Entries(new FileInfo(fileName), prog);
         }
References Juniper.Compression.Zip.Decompressor.Entries().
GetFile() [1/4]
static Stream Juniper.Compression.Zip.Decompressor.GetFile (this ZipArchive zip, string entryPath, IProgress prog = null) inline static
Definition at line 176 of file Decompressor.cs.
         {
             if (zip is null)
             {
                 throw new ArgumentNullException(nameof(zip));
             }
             var entry = zip.GetEntry(entryPath);
             return new ProgressStream(entry.Open(), entry.Length, prog, true);
         }
Referenced by Juniper.Compression.Zip.Decompressor.GetFile(), and Juniper.IO.ZipFileCacheLayer.GetStreamAsync().
GetFile() [2/4]
static Stream Juniper.Compression.Zip.Decompressor.GetFile (Stream zipStream, string entryPath, IProgress prog = null) inline static
Definition at line 187 of file Decompressor.cs.
         {
             if (zipStream is null)
             {
                 throw new ArgumentNullException(nameof(zipStream));
             }
             var zip = Open(zipStream);
             var entry = zip.GetEntry(entryPath);
             var stream = new ZipArchiveEntryStream(zip, entry);
             return new ProgressStream(stream, entry.Length, prog, true);
         }
References Juniper.Compression.Zip.Decompressor.Open().
GetFile() [3/4]
static Stream Juniper.Compression.Zip.Decompressor.GetFile (FileInfo file, string entryPath, IProgress prog = null) inline static
Definition at line 200 of file Decompressor.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             if (!file.Exists)
             {
                 throw new FileNotFoundException("File not found", file.FullName);
             }
             var stream = file.OpenRead();
             return GetFile(stream, entryPath, prog);
         }
References Juniper.Compression.Zip.Decompressor.GetFile().
GetFile() [4/4]
static Stream Juniper.Compression.Zip.Decompressor.GetFile (string fileName, string entryPath, IProgress prog = null) inline static
Definition at line 216 of file Decompressor.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return GetFile(new FileInfo(fileName), entryPath, prog);
         }
References Juniper.Compression.Zip.Decompressor.GetFile().
Open() [1/3]
static ZipArchive Juniper.Compression.Zip.Decompressor.Open (Stream stream) inline static private
Definition at line 15 of file Decompressor.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             return new ZipArchive(stream);
         }
Referenced by Juniper.Compression.Zip.Decompressor.CopyFile(), Juniper.Compression.Zip.Decompressor.Decompress(), Juniper.Compression.Zip.Decompressor.Entries(), Juniper.Compression.Zip.Decompressor.GetFile(), Juniper.IO.ZipFileCacheLayer.IsCached(), and Juniper.Compression.Zip.Decompressor.Open().
Open() [2/3]
static ZipArchive Juniper.Compression.Zip.Decompressor.Open (FileInfo file) inline static
Definition at line 25 of file Decompressor.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             if (!file.Exists)
             {
                 throw new FileNotFoundException(file.FullName);
             }
             var stream = file.OpenRead();
             return Open(stream);
         }
References Juniper.Compression.Zip.Decompressor.Open().
Open() [3/3]
static ZipArchive Juniper.Compression.Zip.Decompressor.Open (string fileName) inline static
Definition at line 41 of file Decompressor.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return Open(new FileInfo(fileName));
         }
References Juniper.Compression.Zip.Decompressor.Open().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Compression/Zip/Decompressor.cs