Juniper: Juniper.Units.Radians Class Reference
Juniper.Units.Radians Class Reference
Conversions from radians
Static Public Member Functions
static float Degrees (float radians)
Convert from radians to degrees.
static float Gradians (float radians)
Convert from radians to gradians.
static float Hours (float radians)
Convert from radians to hours.
Public Attributes
const float PER_CIRCLE = (float)(2 * System.Math.PI)
Conversion factor from circles to radians.
const float PER_DEGREE = PER_CIRCLE / Units.Degrees.PER_CIRCLE
Conversion factor from degrees to radians.
const float PER_GRADIAN = PER_CIRCLE / Units.Gradians.PER_CIRCLE
Conversion factor from gradians to radians.
const float PER_HOUR = PER_CIRCLE / Units.Hours.PER_CIRCLE
Conversion factor from hours to radians.
Detailed Description
Conversions from radians
Definition at line 8 of file Radians.cs.
Member Function Documentation
Degrees()
static float Juniper.Units.Radians.Degrees (float radians) inline static
Convert from radians to degrees.
Parameters
radians The number of radians
Returns
The number of degrees
Definition at line 35 of file Radians.cs.
             {
                 return radians * Units.Degrees.PER_RADIAN;
             }
References Juniper.Units.Degrees.PER_RADIAN.
Referenced by Juniper.Units.UTM.LatLng(), Juniper.World.GIS.GeocentricEclipticSphericalPosition.ToEquitorial(), and Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal().
Gradians()
static float Juniper.Units.Radians.Gradians (float radians) inline static
Convert from radians to gradians.
Parameters
radians The number of radians
Returns
The number of gradians
Definition at line 45 of file Radians.cs.
             {
                 return radians * Units.Gradians.PER_RADIAN;
             }
References Juniper.Units.Gradians.PER_RADIAN.
Hours()
static float Juniper.Units.Radians.Hours (float radians) inline static
Convert from radians to hours.
Parameters
radians The number of radians
Returns
The number of hours
Definition at line 55 of file Radians.cs.
             {
                 return radians * Units.Hours.PER_RADIAN;
             }
References Juniper.Units.Hours.PER_RADIAN.
Member Data Documentation
PER_CIRCLE
const float Juniper.Units.Radians.PER_CIRCLE = (float)(2 * System.Math.PI)
Conversion factor from circles to radians.
Definition at line 13 of file Radians.cs.
PER_DEGREE
const float Juniper.Units.Radians.PER_DEGREE = PER_CIRCLE / Units.Degrees.PER_CIRCLE
Conversion factor from degrees to radians.
Definition at line 18 of file Radians.cs.
Referenced by Juniper.Units.Degrees.Radians().
PER_GRADIAN
const float Juniper.Units.Radians.PER_GRADIAN = PER_CIRCLE / Units.Gradians.PER_CIRCLE
Conversion factor from gradians to radians.
Definition at line 23 of file Radians.cs.
Referenced by Juniper.Units.Gradians.Radians().
PER_HOUR
const float Juniper.Units.Radians.PER_HOUR = PER_CIRCLE / Units.Hours.PER_CIRCLE
Conversion factor from hours to radians.
Definition at line 28 of file Radians.cs.
Referenced by Juniper.Units.Hours.Radians().
The documentation for this class was generated from the following file:
Juniper.Units/src/Angles/Radians.cs