Juniper: Juniper.Units.Milliseconds Class Reference
Juniper.Units.Milliseconds Class Reference
Conversions from milliseconds
Static Public Member Functions
static float Seconds (float ms)
Convert from milliseconds to seconds.
static float Minutes (float ms)
Convert from milliseconds to minutes.
static float Hours (float ms)
Convert from milliseconds to hours.
static float Days (float ms)
Convert from milliseconds to days.
static float Hertz (float ms)
Convert from milliseconds to hertz.
Public Attributes
const float PER_SECOND = 1000
Conversion factor from seconds to milliseconds.
const float PER_MINUTE = PER_SECOND * Units.Seconds.PER_MINUTE
Conversion factor from minutes to milliseconds.
const float PER_HOUR = PER_MINUTE * Units.Minutes.PER_HOUR
Conversion factor from hours to milliseconds.
const float PER_DAY = PER_HOUR * Units.Hours.PER_DAY
Conversion factor from days to milliseconds.
Detailed Description
Conversions from milliseconds
Definition at line 8 of file Milliseconds.cs.
Member Function Documentation
Days()
static float Juniper.Units.Milliseconds.Days (float ms) inline static
Convert from milliseconds to days.
Parameters
ms The number of ms
Returns
The number of days
Definition at line 65 of file Milliseconds.cs.
             {
                 return ms * Units.Days.PER_MILLISECOND;
             }
References Juniper.Units.Days.PER_MILLISECOND.
Hertz()
static float Juniper.Units.Milliseconds.Hertz (float ms) inline static
Convert from milliseconds to hertz.
Parameters
ms The number of ms
Returns
The number of hertz
Definition at line 75 of file Milliseconds.cs.
             {
                 return Units.Seconds.Hertz(Seconds(ms));
             }
References Juniper.Units.Seconds.Hertz(), and Juniper.Units.Milliseconds.Seconds().
Hours()
static float Juniper.Units.Milliseconds.Hours (float ms) inline static
Convert from milliseconds to hours.
Parameters
ms The number of ms
Returns
The number of hours
Definition at line 55 of file Milliseconds.cs.
             {
                 return ms * Units.Hours.PER_MILLISECOND;
             }
References Juniper.Units.Hours.PER_MILLISECOND.
Minutes()
static float Juniper.Units.Milliseconds.Minutes (float ms) inline static
Convert from milliseconds to minutes.
Parameters
ms The number of ms
Returns
The number of minutes
Definition at line 45 of file Milliseconds.cs.
             {
                 return ms * Units.Minutes.PER_MILLISECOND;
             }
References Juniper.Units.Minutes.PER_MILLISECOND.
Seconds()
static float Juniper.Units.Milliseconds.Seconds (float ms) inline static
Convert from milliseconds to seconds.
Parameters
ms The number of ms
Returns
The number of seconds
Definition at line 35 of file Milliseconds.cs.
             {
                 return ms * Units.Seconds.PER_MILLISECOND;
             }
References Juniper.Units.Seconds.PER_MILLISECOND.
Referenced by Juniper.Units.Milliseconds.Hertz(), Juniper.Units.Hertz.Milliseconds(), and Juniper.Haptics.DefaultHaptics.VibrateCoroutine().
Member Data Documentation
PER_DAY
const float Juniper.Units.Milliseconds.PER_DAY = PER_HOUR * Units.Hours.PER_DAY
Conversion factor from days to milliseconds.
Definition at line 28 of file Milliseconds.cs.
Referenced by Juniper.Units.Days.Milliseconds().
PER_HOUR
const float Juniper.Units.Milliseconds.PER_HOUR = PER_MINUTE * Units.Minutes.PER_HOUR
Conversion factor from hours to milliseconds.
Definition at line 23 of file Milliseconds.cs.
Referenced by Juniper.Units.Hours.Milliseconds().
PER_MINUTE
const float Juniper.Units.Milliseconds.PER_MINUTE = PER_SECOND * Units.Seconds.PER_MINUTE
Conversion factor from minutes to milliseconds.
Definition at line 18 of file Milliseconds.cs.
Referenced by Juniper.Units.Minutes.Milliseconds().
PER_SECOND
const float Juniper.Units.Milliseconds.PER_SECOND = 1000
Conversion factor from seconds to milliseconds.
Definition at line 13 of file Milliseconds.cs.
Referenced by Juniper.Units.Seconds.Milliseconds().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Units/src/Time/Milliseconds.cs