Juniper: BitMiracle.LibJpeg.Classic.JpegDestinationManager Class Reference
BitMiracle.LibJpeg.Classic.JpegDestinationManager Class Reference abstract
Data destination object for compression.
Public Member Functions
abstract void InitDestination ()
Initializes this instance.
abstract bool EmptyOutputBuffer ()
Empties output buffer.
abstract void TermDestination ()
Term_destinations this instance.
virtual bool EmitByte (int val)
Emits a byte.
Protected Member Functions
void InitInternalBuffer (byte[] buffer, int offset)
Initializes the internal buffer.
Properties
int FreeInBuffer [get, private set]
Gets the number of free bytes in buffer.
Private Attributes
byte [] buffer
int position
Detailed Description
Data destination object for compression.
Definition at line 6 of file JpegDestinationManager.cs.
Member Function Documentation
EmitByte()
virtual bool BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte (int val) inline virtual
Emits a byte.
Parameters
val The byte value.
Returns
true if operation succeed; otherwise, false
Definition at line 32 of file JpegDestinationManager.cs.
         {
             buffer[position] = (byte)val;
             position++;
             if (--FreeInBuffer == 0)
             {
                 if (!EmptyOutputBuffer())
                 {
                     return false;
                 }
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.buffer, BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmptyOutputBuffer(), BitMiracle.LibJpeg.Classic.JpegDestinationManager.FreeInBuffer, and BitMiracle.LibJpeg.Classic.JpegDestinationManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteS().
EmptyOutputBuffer()
abstract bool BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmptyOutputBuffer () pure virtual
Empties output buffer.
Returns
true if operation succeed; otherwise, false
Implemented in BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.
Referenced by BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte().
InitDestination()
abstract void BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitDestination () pure virtual
Initializes this instance.
Implemented in BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables().
InitInternalBuffer()
void BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer (byte [] buffer, int offset) inline protected
Initializes the internal buffer.
Parameters
buffer The buffer.
offset The offset.
Definition at line 53 of file JpegDestinationManager.cs.
         {
             this.buffer = buffer ?? throw new System.ArgumentNullException(nameof(buffer));
             FreeInBuffer = buffer.Length - offset;
             position = offset;
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.buffer, BitMiracle.LibJpeg.Classic.JpegDestinationManager.FreeInBuffer, and BitMiracle.LibJpeg.Classic.JpegDestinationManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.EmptyOutputBuffer(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.InitDestination().
TermDestination()
abstract void BitMiracle.LibJpeg.Classic.JpegDestinationManager.TermDestination () pure virtual
Term_destinations this instance.
Implemented in BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables().
Member Data Documentation
buffer
byte [] BitMiracle.LibJpeg.Classic.JpegDestinationManager.buffer private
Definition at line 8 of file JpegDestinationManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte(), and BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer().
position
int BitMiracle.LibJpeg.Classic.JpegDestinationManager.position private
Definition at line 9 of file JpegDestinationManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte(), and BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer().
Property Documentation
FreeInBuffer
int BitMiracle.LibJpeg.Classic.JpegDestinationManager.FreeInBuffer get private set protected
Gets the number of free bytes in buffer.
The number of free bytes in buffer.
Definition at line 64 of file JpegDestinationManager.cs.
 { get; private set; }
Referenced by BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte(), BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.TermDestination().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/JpegDestinationManager.cs