Juniper: Juniper.World.GIS.GeocentricEclipticSphericalPosition Struct Reference
Juniper.World.GIS.GeocentricEclipticSphericalPosition Struct Reference
Represents a bearing and distance to an object from the Earth's orbit.
Public Member Functions
GeocentricEclipticSphericalPosition (float beta, float lambda, float r)
Create a new bearing to an object.
EquitorialSphericalPosition ToEquitorial (float n)
This calculation is only good for the Sun, as it does not take the Ecliptic Latitude into consideration.
Static Public Member Functions
static GeocentricEclipticSphericalPosition FromJulianDay (float n)
Calculates the position of the Sun on the Ecliptic for the given Julian Day
Public Attributes
readonly float LatitudeDegrees
The number of degrees above the Earth's orbital disk at which to find the object.
readonly float LongitudeDegrees
The number of degrees along the Earth's orbital disk at which to find the object.
readonly float RadiusAU
The distance in Astronomical Units from the center of Earth's orbit to find the object.
Detailed Description
Represents a bearing and distance to an object from the Earth's orbit.
Definition at line 9 of file GeocentricEclipticSphericalPosition.cs.
Constructor & Destructor Documentation
GeocentricEclipticSphericalPosition()
Juniper.World.GIS.GeocentricEclipticSphericalPosition.GeocentricEclipticSphericalPosition (float beta, float lambda, float r) inline
Create a new bearing to an object.
Parameters
beta The latitude to the object, in degrees
lambda The longitude to the object, in degrees.
r The distance to the object, in Astronomical Units.
Definition at line 32 of file GeocentricEclipticSphericalPosition.cs.
         {
             LatitudeDegrees = beta;
             LongitudeDegrees = lambda;
             RadiusAU = r;
         }
References Juniper.World.GIS.GeocentricEclipticSphericalPosition.LatitudeDegrees, Juniper.World.GIS.GeocentricEclipticSphericalPosition.LongitudeDegrees, and Juniper.World.GIS.GeocentricEclipticSphericalPosition.RadiusAU.
Referenced by Juniper.World.GIS.GeocentricEclipticSphericalPosition.FromJulianDay().
Member Function Documentation
FromJulianDay()
static GeocentricEclipticSphericalPosition Juniper.World.GIS.GeocentricEclipticSphericalPosition.FromJulianDay (float n) inline static
Calculates the position of the Sun on the Ecliptic for the given Julian Day
Parameters
n The Julian Day
Returns
The position of the sun on the ecliptic
Definition at line 44 of file GeocentricEclipticSphericalPosition.cs.
         {
             var L_deg = Units.Repeat(280.460f + 0.9856474f * n, 360f);
             var g_deg = Units.Repeat(357.528f + 0.9856003f * n, 360f);
             var g_rad = Units.Degrees.Radians(g_deg);
             var sin_g = Math.Sin(g_rad);
             var cos_g = Math.Cos(g_rad);
             var lambda_deg = Units.Repeat((float)(L_deg + 1.915f * sin_g + 0.020f * 2 * sin_g * cos_g), 360);
             var R = 1.00014f - 0.01671f * cos_g - 0.00014f * (cos_g * cos_g - sin_g * sin_g);
             var ec = new GeocentricEclipticSphericalPosition(0, lambda_deg, (float)R);
             return ec;
         }
References Juniper.World.GIS.GeocentricEclipticSphericalPosition.GeocentricEclipticSphericalPosition(), Juniper.Units.Degrees.Radians(), and Juniper.Units.Repeat().
Referenced by Juniper.Units.LatLng.SunPosition().
ToEquitorial()
EquitorialSphericalPosition Juniper.World.GIS.GeocentricEclipticSphericalPosition.ToEquitorial (float n) inline
This calculation is only good for the Sun, as it does not take the Ecliptic Latitude into consideration.
Parameters
n The Julian Day
Returns
The position of the son on the equitorial plane
Definition at line 62 of file GeocentricEclipticSphericalPosition.cs.
         {
             var epsilon_deg = 23.439f - 0.0000004f * n;
             var epsilon_rad = Units.Degrees.Radians(epsilon_deg);
             var sin_epsilon = Math.Sin(epsilon_rad);
             var cos_epsilon = Math.Cos(epsilon_rad);
             var lambda_rad = Units.Degrees.Radians(LongitudeDegrees);
             var sin_lambda = Math.Sin(lambda_rad);
             var cos_lambda = Math.Cos(lambda_rad);
             var alpha_rad = (float)Math.Atan2(cos_epsilon * sin_lambda, cos_lambda);
             var delta_rad = (float)Math.Asin(sin_epsilon * sin_lambda);
             return new EquitorialSphericalPosition(
                 Units.Radians.Degrees(alpha_rad),
                 Units.Radians.Degrees(delta_rad),
                 RadiusAU);
         }
References Juniper.Units.Radians.Degrees(), Juniper.World.GIS.GeocentricEclipticSphericalPosition.LongitudeDegrees, Juniper.Units.Degrees.Radians(), and Juniper.World.GIS.GeocentricEclipticSphericalPosition.RadiusAU.
Referenced by Juniper.Units.LatLng.SunPosition().
Member Data Documentation
LatitudeDegrees
readonly float Juniper.World.GIS.GeocentricEclipticSphericalPosition.LatitudeDegrees
The number of degrees above the Earth's orbital disk at which to find the object.
Definition at line 14 of file GeocentricEclipticSphericalPosition.cs.
Referenced by Juniper.World.GIS.GeocentricEclipticSphericalPosition.GeocentricEclipticSphericalPosition().
LongitudeDegrees
readonly float Juniper.World.GIS.GeocentricEclipticSphericalPosition.LongitudeDegrees
The number of degrees along the Earth's orbital disk at which to find the object.
Definition at line 19 of file GeocentricEclipticSphericalPosition.cs.
Referenced by Juniper.World.GIS.GeocentricEclipticSphericalPosition.GeocentricEclipticSphericalPosition(), and Juniper.World.GIS.GeocentricEclipticSphericalPosition.ToEquitorial().
RadiusAU
readonly float Juniper.World.GIS.GeocentricEclipticSphericalPosition.RadiusAU
The distance in Astronomical Units from the center of Earth's orbit to find the object.
Definition at line 24 of file GeocentricEclipticSphericalPosition.cs.
Referenced by Juniper.World.GIS.GeocentricEclipticSphericalPosition.GeocentricEclipticSphericalPosition(), and Juniper.World.GIS.GeocentricEclipticSphericalPosition.ToEquitorial().
The documentation for this struct was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Units/src/Geo/GeocentricEclipticSphericalPosition.cs