Juniper: Juniper.Speech.KeywordRecognizer Class Reference
Juniper.Speech.KeywordRecognizer Class Reference
A class that implements basic functionality for systems that manage speech recognition and route out the events associated with recognizing keywords.
Public Member Functions
void AddKeywordable (Keywordable keywordable)
void RemoveKeywordable (Keywordable keywordable)
void Update ()
void OnDisable ()
Tear down the speech recognition system.
Static Public Member Functions
static void Pause ()
static void Resume ()
Public Attributes
const bool IsPermitted = true
float minimumIncompleteSimilarity = 0.85f
float minimumCompleteSimilarity = 0.7f
UnityEvent onRecognitionStarted
UnityEvent onRecognitionStopped
UnityEvent onRecognitionRecognizing
UnityEvent onRecognitionComplete
UnityEvent onRecognitionCanceled
UnityEvent onRecognitionError
Protected Member Functions
void OnRecognitionStarted ()
void OnRecognitionStopped ()
void OnRecognitionRecognizing ()
void OnRecognitionComplete ()
void OnRecognitionCanceled ()
void OnRecognitionError ()
void ProcessText (string text, bool isComplete)
void Setup ()
void TearDown ()
Protected Attributes
bool IsRunning
bool IsStopping
bool IsStarting
bool IsPaused
Properties
bool IsAvailable [get]
Reads as true if the current XR subsystem supports speech recognition.
Events
EventHandler RecognitionStarted
EventHandler RecognitionStopped
EventHandler RecognitionRecognizing
EventHandler RecognitionComplete
EventHandler RecognitionCanceled
EventHandler RecognitionError
Private Member Functions
void TearDownInternal ()
Static Private Member Functions
static bool IsWordChar (char c)
Private Attributes
readonly List< Keywordable > keywordables = new List<Keywordable>()
DateTime lastMatchTime
Keywordable lastReceiver
Keywordable resultReceiver
readonly object syncRoot = new object()
Static Private Attributes
static readonly TimeSpan DEBOUNCE_TIME = TimeSpan.FromMilliseconds(250)
Detailed Description
A class that implements basic functionality for systems that manage speech recognition and route out the events associated with recognizing keywords.
Definition at line 14 of file KeywordRecognizer.cs.
Member Function Documentation
AddKeywordable()
void Juniper.Speech.KeywordRecognizer.AddKeywordable (Keywordable keywordable) inline
Definition at line 122 of file KeywordRecognizer.cs.
         {
             lock (syncRoot)
             {
                 keywordables.MaybeAdd(keywordable);
             }
         }
References Juniper.Speech.KeywordRecognizer.keywordables, and Juniper.Speech.KeywordRecognizer.syncRoot.
IsWordChar()
static bool Juniper.Speech.KeywordRecognizer.IsWordChar (char c) inline static private
Definition at line 48 of file KeywordRecognizer.cs.
         {
             return char.IsLetter(c)
                 || char.IsWhiteSpace(c)
                 || char.IsNumber(c);
         }
Referenced by Juniper.Speech.KeywordRecognizer.ProcessText().
OnDisable()
void Juniper.Speech.KeywordRecognizer.OnDisable () inline
Tear down the speech recognition system.
Definition at line 227 of file KeywordRecognizer.cs.
         {
             TearDownInternal();
         }
References Juniper.Speech.KeywordRecognizer.TearDownInternal().
OnRecognitionCanceled()
void Juniper.Speech.KeywordRecognizer.OnRecognitionCanceled () inline protected
Definition at line 99 of file KeywordRecognizer.cs.
         {
             onRecognitionCanceled?.Invoke();
             RecognitionCanceled?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Speech.KeywordRecognizer.onRecognitionCanceled, and Juniper.Speech.KeywordRecognizer.RecognitionCanceled.
OnRecognitionComplete()
void Juniper.Speech.KeywordRecognizer.OnRecognitionComplete () inline protected
Definition at line 93 of file KeywordRecognizer.cs.
         {
             onRecognitionComplete?.Invoke();
             RecognitionComplete?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Speech.KeywordRecognizer.onRecognitionComplete, and Juniper.Speech.KeywordRecognizer.RecognitionComplete.
OnRecognitionError()
void Juniper.Speech.KeywordRecognizer.OnRecognitionError () inline protected
Definition at line 105 of file KeywordRecognizer.cs.
         {
             onRecognitionError?.Invoke();
             RecognitionError?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Speech.KeywordRecognizer.onRecognitionError, and Juniper.Speech.KeywordRecognizer.RecognitionError.
OnRecognitionRecognizing()
void Juniper.Speech.KeywordRecognizer.OnRecognitionRecognizing () inline protected
Definition at line 87 of file KeywordRecognizer.cs.
         {
             onRecognitionRecognizing?.Invoke();
             RecognitionRecognizing?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Speech.KeywordRecognizer.onRecognitionRecognizing, and Juniper.Speech.KeywordRecognizer.RecognitionRecognizing.
OnRecognitionStarted()
void Juniper.Speech.KeywordRecognizer.OnRecognitionStarted () inline protected
Definition at line 75 of file KeywordRecognizer.cs.
         {
             onRecognitionStarted?.Invoke();
             RecognitionStarted?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Speech.KeywordRecognizer.onRecognitionStarted, and Juniper.Speech.KeywordRecognizer.RecognitionStarted.
OnRecognitionStopped()
void Juniper.Speech.KeywordRecognizer.OnRecognitionStopped () inline protected
Definition at line 81 of file KeywordRecognizer.cs.
         {
             onRecognitionStopped?.Invoke();
             RecognitionStopped?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Speech.KeywordRecognizer.onRecognitionStopped, and Juniper.Speech.KeywordRecognizer.RecognitionStopped.
Pause()
static void Juniper.Speech.KeywordRecognizer.Pause () inline static
Definition at line 16 of file KeywordRecognizer.cs.
         {
             Microphone.End(string.Empty);
         }
ProcessText()
void Juniper.Speech.KeywordRecognizer.ProcessText (string text, bool isComplete) inline protected
Definition at line 138 of file KeywordRecognizer.cs.
         {
             if (!string.IsNullOrEmpty(text))
             {
                 var resultText = new string(text
                     .ToLowerInvariant()
                     .Where(IsWordChar)
                     .ToArray());
                 if (!string.IsNullOrEmpty(resultText))
                 {
                     var maxSimilarity = 0f;
                     Keywordable receiver = null;
                     string match = null;
                     foreach (var keywordable in keywordables)
                     {
                         foreach (var keyword in keywordable.keywords)
{
                             var similarity = keyword.Similarity(resultText);
                             if (similarity > maxSimilarity)
{
                                 match = keyword;
                                 maxSimilarity = similarity;
                                 receiver = keywordable;
                             }
                         }
                     }
                     ScreenDebugger.Print($"{text} => {resultText} = {match} ({Units.Converter.Label(maxSimilarity, Units.UnitOfMeasure.Proportion, Units.UnitOfMeasure.Percent)})");
                     if (isComplete && maxSimilarity < minimumCompleteSimilarity
                         || !isComplete && maxSimilarity < minimumIncompleteSimilarity)
                     {
                         receiver = null;
                     }
                     lock (syncRoot)
                     {
                         resultReceiver = receiver;
                     }
                 }
             }
         }
References Juniper.Speech.KeywordRecognizer.IsWordChar(), Juniper.Speech.KeywordRecognizer.keywordables, Juniper.Speech.KeywordRecognizer.minimumCompleteSimilarity, Juniper.Speech.KeywordRecognizer.minimumIncompleteSimilarity, System.ScreenDebugger.Print(), Juniper.Speech.KeywordRecognizer.resultReceiver, and Juniper.Speech.KeywordRecognizer.syncRoot.
RemoveKeywordable()
void Juniper.Speech.KeywordRecognizer.RemoveKeywordable (Keywordable keywordable) inline
Definition at line 130 of file KeywordRecognizer.cs.
         {
             lock (syncRoot)
             {
                 keywordables.Remove(keywordable);
             }
         }
References Juniper.Speech.KeywordRecognizer.keywordables, and Juniper.Speech.KeywordRecognizer.syncRoot.
Resume()
static void Juniper.Speech.KeywordRecognizer.Resume () inline static
Definition at line 21 of file KeywordRecognizer.cs.
         {
             Microphone.GetDeviceCaps(string.Empty, out _, out var maxFreq);
             Microphone.Start(string.Empty, true, 5, maxFreq);
         }
Setup()
void Juniper.Speech.KeywordRecognizer.Setup () inline protected
Definition at line 20 of file KeywordRecognizer.None.cs.
         {
             Debug.LogWarning("No speech recognition available");
         }
Referenced by Juniper.Speech.KeywordRecognizer.Update().
TearDown()
void Juniper.Speech.KeywordRecognizer.TearDown () inline protected
Definition at line 25 of file KeywordRecognizer.None.cs.
         {
         }
Referenced by Juniper.Speech.KeywordRecognizer.TearDownInternal().
TearDownInternal()
void Juniper.Speech.KeywordRecognizer.TearDownInternal () inline private
Definition at line 182 of file KeywordRecognizer.cs.
         {
             if (IsRunning && !IsStopping)
             {
                 TearDown();
             }
         }
References Juniper.Speech.KeywordRecognizer.IsRunning, Juniper.Speech.KeywordRecognizer.IsStopping, and Juniper.Speech.KeywordRecognizer.TearDown().
Referenced by Juniper.Speech.KeywordRecognizer.OnDisable().
Update()
void Juniper.Speech.KeywordRecognizer.Update () inline
Definition at line 192 of file KeywordRecognizer.cs.
         {
             if (IsAvailable)
             {
                 if (IsRunning && !IsPaused)
                 {
                     Keywordable receiver = null;
                     lock (syncRoot)
                     {
                         if (resultReceiver != null
                             && (resultReceiver != lastReceiver
                                 || (DateTime.Now - lastMatchTime) > DEBOUNCE_TIME))
{
                             lastReceiver = resultReceiver;
                             receiver = resultReceiver;
                             resultReceiver = null;
                         }
                         lastMatchTime = DateTime.Now;
                     }
                     if (receiver != null)
                     {
                         receiver.ActivateEvent();
                     }
                 }
                 else if (IsPermitted && !IsStarting)
                 {
                     Setup();
                 }
             }
         }
References Juniper.Input.AbstractShortcutable.ActivateEvent(), Juniper.Speech.KeywordRecognizer.DEBOUNCE_TIME, Juniper.Speech.KeywordRecognizer.IsAvailable, Juniper.Speech.KeywordRecognizer.IsPaused, Juniper.Speech.KeywordRecognizer.IsPermitted, Juniper.Speech.KeywordRecognizer.IsRunning, Juniper.Speech.KeywordRecognizer.IsStarting, Juniper.Speech.KeywordRecognizer.lastMatchTime, Juniper.Speech.KeywordRecognizer.lastReceiver, Juniper.Speech.KeywordRecognizer.resultReceiver, Juniper.Speech.KeywordRecognizer.Setup(), and Juniper.Speech.KeywordRecognizer.syncRoot.
Member Data Documentation
DEBOUNCE_TIME
readonly TimeSpan Juniper.Speech.KeywordRecognizer.DEBOUNCE_TIME = TimeSpan.FromMilliseconds(250) static private
Definition at line 190 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
IsPaused
bool Juniper.Speech.KeywordRecognizer.IsPaused protected
Definition at line 114 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
IsPermitted
const bool Juniper.Speech.KeywordRecognizer.IsPermitted = true
Definition at line 45 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
IsRunning
bool Juniper.Speech.KeywordRecognizer.IsRunning protected
Definition at line 111 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.TearDownInternal(), and Juniper.Speech.KeywordRecognizer.Update().
IsStarting
bool Juniper.Speech.KeywordRecognizer.IsStarting protected
Definition at line 113 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
IsStopping
bool Juniper.Speech.KeywordRecognizer.IsStopping protected
Definition at line 112 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.TearDownInternal().
keywordables
readonly List<Keywordable> Juniper.Speech.KeywordRecognizer.keywordables = new List<Keywordable>() private
Definition at line 116 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.AddKeywordable(), Juniper.Speech.KeywordRecognizer.ProcessText(), and Juniper.Speech.KeywordRecognizer.RemoveKeywordable().
lastMatchTime
DateTime Juniper.Speech.KeywordRecognizer.lastMatchTime private
Definition at line 117 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
lastReceiver
Keywordable Juniper.Speech.KeywordRecognizer.lastReceiver private
Definition at line 118 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
minimumCompleteSimilarity
float Juniper.Speech.KeywordRecognizer.minimumCompleteSimilarity = 0.7f
Definition at line 59 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.ProcessText().
minimumIncompleteSimilarity
float Juniper.Speech.KeywordRecognizer.minimumIncompleteSimilarity = 0.85f
Definition at line 56 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.ProcessText().
onRecognitionCanceled
UnityEvent Juniper.Speech.KeywordRecognizer.onRecognitionCanceled
Definition at line 65 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionCanceled().
onRecognitionComplete
UnityEvent Juniper.Speech.KeywordRecognizer.onRecognitionComplete
Definition at line 64 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionComplete().
onRecognitionError
UnityEvent Juniper.Speech.KeywordRecognizer.onRecognitionError
Definition at line 66 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionError().
onRecognitionRecognizing
UnityEvent Juniper.Speech.KeywordRecognizer.onRecognitionRecognizing
Definition at line 63 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionRecognizing().
onRecognitionStarted
UnityEvent Juniper.Speech.KeywordRecognizer.onRecognitionStarted
Definition at line 61 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionStarted().
onRecognitionStopped
UnityEvent Juniper.Speech.KeywordRecognizer.onRecognitionStopped
Definition at line 62 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionStopped().
resultReceiver
Keywordable Juniper.Speech.KeywordRecognizer.resultReceiver private
Definition at line 119 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.ProcessText(), and Juniper.Speech.KeywordRecognizer.Update().
syncRoot
readonly object Juniper.Speech.KeywordRecognizer.syncRoot = new object() private
Definition at line 120 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.AddKeywordable(), Juniper.Speech.KeywordRecognizer.ProcessText(), Juniper.Speech.KeywordRecognizer.RemoveKeywordable(), and Juniper.Speech.KeywordRecognizer.Update().
Property Documentation
IsAvailable
bool Juniper.Speech.KeywordRecognizer.IsAvailable get
Reads as true if the current XR subsystem supports speech recognition.
Definition at line 13 of file KeywordRecognizer.None.cs.
         {
             get
             {
                 return false;
             }
         }
Referenced by Juniper.Speech.KeywordRecognizer.Update().
Event Documentation
RecognitionCanceled
EventHandler Juniper.Speech.KeywordRecognizer.RecognitionCanceled
Definition at line 72 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionCanceled().
RecognitionComplete
EventHandler Juniper.Speech.KeywordRecognizer.RecognitionComplete
Definition at line 71 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionComplete().
RecognitionError
EventHandler Juniper.Speech.KeywordRecognizer.RecognitionError
Definition at line 73 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionError().
RecognitionRecognizing
EventHandler Juniper.Speech.KeywordRecognizer.RecognitionRecognizing
Definition at line 70 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionRecognizing().
RecognitionStarted
EventHandler Juniper.Speech.KeywordRecognizer.RecognitionStarted
Definition at line 68 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionStarted().
RecognitionStopped
EventHandler Juniper.Speech.KeywordRecognizer.RecognitionStopped
Definition at line 69 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.KeywordRecognizer.OnRecognitionStopped().
The documentation for this class was generated from the following files:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Speech/KeywordRecognizer.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Speech/KeywordRecognizer.None.cs