Juniper: Hjg.Pngcs.Zlib.ZlibStreamFactory Class Reference
Hjg.Pngcs.Zlib.ZlibStreamFactory Class Reference
Static Public Member Functions
static AZlibInputStream createZlibInputStream (Stream st, bool leaveOpen)
static AZlibInputStream createZlibInputStream (Stream st)
static AZlibOutputStream createZlibOutputStream (Stream st, int compressLevel, EDeflateCompressStrategy strat, bool leaveOpen)
static AZlibOutputStream createZlibOutputStream (Stream st)
static AZlibOutputStream createZlibOutputStream (Stream st, bool leaveOpen)
Detailed Description
Definition at line 10 of file ZlibStreamFactory.cs.
Member Function Documentation
createZlibInputStream() [1/2]
static AZlibInputStream Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibInputStream (Stream st, bool leaveOpen) inline static
Definition at line 12 of file ZlibStreamFactory.cs.
         {
             return new ZlibInputStream(st, leaveOpen);
         }
Referenced by Hjg.Pngcs.Chunks.ChunkHelper.compressBytes(), Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibInputStream(), and Hjg.Pngcs.PngReader.ReadFirstChunks().
createZlibInputStream() [2/2]
static AZlibInputStream Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibInputStream (Stream st) inline static
Definition at line 17 of file ZlibStreamFactory.cs.
         {
             return createZlibInputStream(st, false);
         }
References Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibInputStream().
createZlibOutputStream() [1/3]
static AZlibOutputStream Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibOutputStream (Stream st, int compressLevel, EDeflateCompressStrategy strat, bool leaveOpen) inline static
Definition at line 22 of file ZlibStreamFactory.cs.
         {
             return new ZlibOutputStream(st, compressLevel, strat, leaveOpen);
         }
Referenced by Hjg.Pngcs.Chunks.ChunkHelper.compressBytes(), Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibOutputStream(), and Hjg.Pngcs.PngWriter.init().
createZlibOutputStream() [2/3]
static AZlibOutputStream Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibOutputStream (Stream st) inline static
Definition at line 27 of file ZlibStreamFactory.cs.
         {
             return createZlibOutputStream(st, false);
         }
References Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibOutputStream().
createZlibOutputStream() [3/3]
static AZlibOutputStream Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibOutputStream (Stream st, bool leaveOpen) inline static
Definition at line 32 of file ZlibStreamFactory.cs.
         {
             return createZlibOutputStream(st, DeflateCompressLevel.DEFAULT, EDeflateCompressStrategy.Default, leaveOpen);
         }
References Hjg.Pngcs.Zlib.ZlibStreamFactory.createZlibOutputStream(), and Hjg.Pngcs.Zlib.DeflateCompressLevel.DEFAULT.
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/ThirdParty/Required/Hjg.Pngcs/Zlib/ZlibStreamFactory.cs