Juniper: Juniper.Statistics.AbstractCollectionStatistics< T > Class Template Reference
Juniper.Statistics.AbstractCollectionStatistics< T > Class Template Reference abstract
An abstract class for a collection wrapper that can automatically compute statistics on the values contained within.
Public Member Functions
IEnumerator< T > GetEnumerator ()
Returns an enumerator that iterates through the collection.
void Add (T item)
Adds an item to the collection, and recalculates the statistical values.
void AddRange (IEnumerable< T > collect)
void Clear ()
Clears the collection and resets the statistics to null.
bool Contains (T item)
Returns true if the give item is in the collection.
void CopyTo (T[] array, int arrayIndex)
Copies the elements of the collection to an Array, starting at a particular Array index.
bool Remove (T item)
Remove an item from the collection.
int IndexOf (T item)
Determines the index of the specified item in the underlying collection.
void Insert (int index, T item)
Insert an item at an arbitrary point in the collection.
void RemoveAt (int index)
Remove an item at the specified index from the collection.
bool Append (T value, int numStandardDeviations, int minSamples=2)
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Public Attributes
int Count => collect.Count
Returns the number of items in the collection.
bool IsReadOnly
Gets a value indicating whether this T:Juniper.Statistics.AbstractCollectionStatistics`1 is read only.
T? Delta
The difference between the Maximum and Minimum
T? Median
The midpoint between the Maximum and the Minimum
Protected Member Functions
AbstractCollectionStatistics (IList< T > collection, T zero, T one)
Creates a new collection analyzer out of a generic collection.
AbstractCollectionStatistics (int capacity, T zero, T one)
Creates a new collection analyzer with a RingBuffer as the underlying collection.
void RecomputeStatistics ()
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
void UpdateStatistics (T value)
abstract T Add (T a, T b)
abstract T Subtract (T a, T b)
abstract T Multiply (T a, T b)
abstract T Scale (T a, float b)
abstract T Divide (T a, float b)
abstract T Sqrt (T value)
abstract T Abs (T value)
abstract bool LessThan (T a, T b)
Properties
T? Maximum [get, protected set]
The maximum value in the collection (calculated during collection modification)
T? Minimum [get, protected set]
The minimum value in the collection (calculated during collection modification)
T? Mean [get, protected set]
The arithmetic mean of the values in the collection (calculated during collection modification)
T? Variance [get, protected set]
The square of the standard deviation of the values in the collection (calculated during collection modification)
T? StandardDeviation [get, protected set]
The standard deviation of the values in the collection (calculated during collection modification)
bool IsSaturated [get]
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
T this[int index] [get, set]
Gets or sets the element at the specified index.
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Returns an enumerator that iterates through the collection.
T? Add (T? a, T? b)
T? Subtract (T? a, T? b)
T? Multiply (T? a, T? b)
T? Scale (T? a, float b)
T? Divide (T? a, float b)
T Min (T? a, T b)
T Max (T? a, T b)
T? Sqrt (T? value)
T? Abs (T? value)
bool LessThan (T? a, T? b)
Private Attributes
readonly T Zero
readonly T One
IList< T > collect
The collection being wrapped.
T? max
T? min
T? mean
T? variance
T? standardDev
Detailed Description
An abstract class for a collection wrapper that can automatically compute statistics on the values contained within.
Type Constraints
T : struct
Definition at line 10 of file AbstractCollectionStatistics.cs.
Constructor & Destructor Documentation
AbstractCollectionStatistics() [1/2]
Juniper.Statistics.AbstractCollectionStatistics< T >.AbstractCollectionStatistics (IList< T > collection, T zero, T one) inline protected
Creates a new collection analyzer out of a generic collection.
Parameters
collection Collection.
zero Value representing addition identity
one Value representing multiplication identity
Definition at line 325 of file AbstractCollectionStatistics.cs.
         {
             collect = collection;
             Zero = zero;
             One = one;
         }
AbstractCollectionStatistics() [2/2]
Juniper.Statistics.AbstractCollectionStatistics< T >.AbstractCollectionStatistics (int capacity, T zero, T one) inline protected
Creates a new collection analyzer with a RingBuffer as the underlying collection.
Parameters
capacity Capacity.
Definition at line 336 of file AbstractCollectionStatistics.cs.
             : this(new RingBuffer<T>(capacity), zero, one)
         {
         }
Member Function Documentation
Abs() [1/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Abs (T value) protected pure virtual
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Abs(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append().
Abs() [2/2]
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Abs (T? value) inline private
Definition at line 539 of file AbstractCollectionStatistics.cs.
         {
             if (value == null)
             {
                 return null;
             }
             else
             {
                 return Abs(value.Value);
             }
         }
Add() [1/3]
void Juniper.Statistics.AbstractCollectionStatistics< T >.Add (T item) inline
Adds an item to the collection, and recalculates the statistical values.
Parameters
item
Definition at line 184 of file AbstractCollectionStatistics.cs.
         {
             collect.Add(item);
             UpdateStatistics(item);
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Add(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.AddRange(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Add() [2/3]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Add (T a, T b) protected pure virtual
Add() [3/3]
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Add (T? a, T? b) inline private
Definition at line 427 of file AbstractCollectionStatistics.cs.
         {
             if (a == null && b == null)
             {
                 return null;
             }
             else if (a == null)
             {
                 return b;
             }
             else if (b == null)
             {
                 return a;
             }
             else
             {
                 return Add(a.Value, b.Value);
             }
         }
AddRange()
void Juniper.Statistics.AbstractCollectionStatistics< T >.AddRange (IEnumerable< T > collect) inline
Definition at line 190 of file AbstractCollectionStatistics.cs.
         {
             foreach (var v in collect)
             {
                 Add(v);
             }
         }
Append()
bool Juniper.Statistics.AbstractCollectionStatistics< T >.Append (T value, int numStandardDeviations, int minSamples = 2) inline
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Parameters
value
numStandardDeviations
minSamples The minimum number of collected samples in the collection to have before rejecting outliers. MinSamples must be at least 2.
Returns
True if the item was added, false if it was rejected.
Definition at line 296 of file AbstractCollectionStatistics.cs.
         {
             var delta = Abs(Subtract(value, Mean));
             var isInlier = Count < 2
                 || Count < minSamples
                 || LessThan(delta, Scale(StandardDeviation, numStandardDeviations));
             if (isInlier)
             {
                 Add(value);
             }
             return isInlier;
         }
Clear()
void Juniper.Statistics.AbstractCollectionStatistics< T >.Clear () inline
Clears the collection and resets the statistics to null.
Definition at line 201 of file AbstractCollectionStatistics.cs.
         {
             collect.Clear();
             RecomputeStatistics();
         }
Referenced by Juniper.Widgets.QualityDegrader.Update().
Contains()
bool Juniper.Statistics.AbstractCollectionStatistics< T >.Contains (T item)
Returns true if the give item is in the collection.
Parameters
item The item to search for.
Returns
True if the item is found. False if it is not.
CopyTo()
void Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo (T [] array, int arrayIndex)
Copies the elements of the collection to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
arrayIndex The zero-based index in array at which copying begins.
Exceptions
System.ArgumentNullException array is null
System.ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from arrayIndex to the end of the destination array .
Divide() [1/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Divide (T a, float b) protected pure virtual
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Divide(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Divide() [2/2]
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Divide (T? a, float b) inline private
Definition at line 491 of file AbstractCollectionStatistics.cs.
         {
             if (a == null)
             {
                 return null;
             }
             else
             {
                 return Divide(a.Value, b);
             }
         }
GetEnumerator() [1/2]
IEnumerator<T> Juniper.Statistics.AbstractCollectionStatistics< T >.GetEnumerator ()
Returns an enumerator that iterates through the collection.
Returns
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.Statistics.AbstractCollectionStatistics< T >.GetEnumerator () private
Returns an enumerator that iterates through the collection.
Returns
IndexOf()
int Juniper.Statistics.AbstractCollectionStatistics< T >.IndexOf (T item)
Determines the index of the specified item in the underlying collection.
Parameters
item The object to location in the collection.
Returns
The index of item if found in the list; otherwise, -1.
If an object occurs multiple times in the list, the IndexOf method always returns the first instance found.
Insert()
void Juniper.Statistics.AbstractCollectionStatistics< T >.Insert (int index, T item) inline
Insert an item at an arbitrary point in the collection.
Parameters
index The index at which to insert item .
item The value to insert.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
Definition at line 266 of file AbstractCollectionStatistics.cs.
         {
             collect.Insert(index, item);
             UpdateStatistics(item);
         }
LessThan() [1/2]
abstract bool Juniper.Statistics.AbstractCollectionStatistics< T >.LessThan (T a, T b) protected pure virtual
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.LessThan(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Max(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Min().
LessThan() [2/2]
bool Juniper.Statistics.AbstractCollectionStatistics< T >.LessThan (T? a, T? b) inline private
Definition at line 551 of file AbstractCollectionStatistics.cs.
         {
             if (a == null || b == null)
             {
                 return true;
             }
             else
             {
                 return LessThan(a.Value, b.Value);
             }
         }
Max()
T Juniper.Statistics.AbstractCollectionStatistics< T >.Max (T? a, T b) inline private
Definition at line 515 of file AbstractCollectionStatistics.cs.
         {
             if (LessThan(a, b))
             {
                 return b;
             }
             else
             {
                 return a.Value;
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Min()
T Juniper.Statistics.AbstractCollectionStatistics< T >.Min (T? a, T b) inline private
Definition at line 503 of file AbstractCollectionStatistics.cs.
         {
             if (LessThan(a, b))
             {
                 return a.Value;
             }
             else
             {
                 return b;
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Multiply() [1/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Multiply (T a, T b) protected pure virtual
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Multiply(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Multiply() [2/2]
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Multiply (T? a, T? b) inline private
Definition at line 467 of file AbstractCollectionStatistics.cs.
         {
             if (a == null || b == null)
             {
                 return null;
             }
             else
             {
                 return Multiply(a.Value, b.Value);
             }
         }
RecomputeStatistics()
void Juniper.Statistics.AbstractCollectionStatistics< T >.RecomputeStatistics () inline protected
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
Definition at line 345 of file AbstractCollectionStatistics.cs.
         {
             Maximum = Minimum = Mean = Variance = StandardDeviation = null;
             if (Count > 0)
             {
                 Minimum = Scale(One, float.MaxValue);
                 Maximum = Scale(One, float.MinValue);
                 Mean = Zero;
                 foreach (var v in this)
                 {
                     Minimum = Min(Minimum, v);
                     Maximum = Max(Maximum, v);
                     Mean = Add(Mean, Divide(v, Count));
                 }
                 if (Count > 1)
                 {
                     Variance = Zero;
                     foreach (var v in this)
                     {
                         var residual = Subtract(v, Mean);
                         Variance = Add(Variance, Divide(Multiply(residual, residual), Count - 1));
                     }
                     StandardDeviation = Sqrt(Variance);
                 }
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Remove(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RemoveAt().
Remove()
bool Juniper.Statistics.AbstractCollectionStatistics< T >.Remove (T item) inline
Remove an item from the collection.
Parameters
item The value to remove.
Returns
True if the item existed in the buffer and was removed. False otherwise.
Definition at line 239 of file AbstractCollectionStatistics.cs.
         {
             var removed = collect.Remove(item);
             RecomputeStatistics();
             return removed;
         }
RemoveAt()
void Juniper.Statistics.AbstractCollectionStatistics< T >.RemoveAt (int index) inline
Remove an item at the specified index from the collection.
Parameters
index The index at which to remove an item.
Exceptions
System.ArgumentOutOfRangeException index is less than 0 or greater than Count - 1.
Definition at line 279 of file AbstractCollectionStatistics.cs.
         {
             collect.RemoveAt(index);
             RecomputeStatistics();
         }
Scale() [1/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Scale (T a, float b) protected pure virtual
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Scale(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Subtract(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Scale() [2/2]
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Scale (T? a, float b) inline private
Definition at line 479 of file AbstractCollectionStatistics.cs.
         {
             if (a == null)
             {
                 return null;
             }
             else
             {
                 return Scale(a.Value, b);
             }
         }
Sqrt() [1/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Sqrt (T value) protected pure virtual
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Sqrt(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Sqrt() [2/2]
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Sqrt (T? value) inline private
Definition at line 527 of file AbstractCollectionStatistics.cs.
         {
             if (value == null)
             {
                 return null;
             }
             else
             {
                 return Sqrt(value.Value);
             }
         }
Subtract() [1/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Subtract (T a, T b) protected pure virtual
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Subtract(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Subtract() [2/2]
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Subtract (T? a, T? b) inline private
Definition at line 447 of file AbstractCollectionStatistics.cs.
         {
             if (a == null && b == null)
             {
                 return null;
             }
             else if (a == null)
             {
                 return Scale(b, -1);
             }
             else if (b == null)
             {
                 return a;
             }
             else
             {
                 return Subtract(a.Value, b.Value);
             }
         }
UpdateStatistics()
void Juniper.Statistics.AbstractCollectionStatistics< T >.UpdateStatistics (T value) inline protected
Definition at line 375 of file AbstractCollectionStatistics.cs.
         {
             Minimum = Min(Minimum, value);
             Maximum = Max(Maximum, value);
             var prevMean = Mean;
             var residual = Subtract(value, prevMean);
             Mean = Add(prevMean, Divide(residual, Count));
             if (Count > 1)
             {
                 var secondResidual = Subtract(value, Mean);
                 var n2 = Count - 2;
                 var n1 = Count - 1;
                 Variance = Divide(
                     Add(
                         Scale(Variance, n2),
                         Multiply(residual, secondResidual)),
                     n1);
                 StandardDeviation = Sqrt(Variance);
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Add(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Insert().
Member Data Documentation
collect
IList<T> Juniper.Statistics.AbstractCollectionStatistics< T >.collect private
The collection being wrapped.
Definition at line 419 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Add(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.AddRange(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Clear(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Insert(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Remove(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RemoveAt().
Count
int Juniper.Statistics.AbstractCollectionStatistics< T >.Count => collect.Count
Returns the number of items in the collection.
Definition at line 111 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.World.CompassRose.PrintDebugReport(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Delta
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Delta
Initial value:
=>
            Subtract(Maximum, Minimum)
The difference between the Maximum and Minimum
Definition at line 144 of file AbstractCollectionStatistics.cs.
IsReadOnly
bool Juniper.Statistics.AbstractCollectionStatistics< T >.IsReadOnly
Initial value:
=>
            collect.IsReadOnly
Gets a value indicating whether this T:Juniper.Statistics.AbstractCollectionStatistics`1 is read only.
true if is read only; otherwise, false.
Definition at line 138 of file AbstractCollectionStatistics.cs.
max
T? Juniper.Statistics.AbstractCollectionStatistics< T >.max private
Definition at line 421 of file AbstractCollectionStatistics.cs.
mean
T? Juniper.Statistics.AbstractCollectionStatistics< T >.mean private
Definition at line 423 of file AbstractCollectionStatistics.cs.
Median
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Median
Initial value:
=>
            Add(Minimum, Divide(Delta, 2))
The midpoint between the Maximum and the Minimum
Definition at line 150 of file AbstractCollectionStatistics.cs.
min
T? Juniper.Statistics.AbstractCollectionStatistics< T >.min private
Definition at line 422 of file AbstractCollectionStatistics.cs.
One
readonly T Juniper.Statistics.AbstractCollectionStatistics< T >.One private
Definition at line 414 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics().
standardDev
T? Juniper.Statistics.AbstractCollectionStatistics< T >.standardDev private
Definition at line 425 of file AbstractCollectionStatistics.cs.
variance
T? Juniper.Statistics.AbstractCollectionStatistics< T >.variance private
Definition at line 424 of file AbstractCollectionStatistics.cs.
Zero
readonly T Juniper.Statistics.AbstractCollectionStatistics< T >.Zero private
Definition at line 414 of file AbstractCollectionStatistics.cs.
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.AbstractCollectionStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics().
Property Documentation
IsSaturated
bool Juniper.Statistics.AbstractCollectionStatistics< T >.IsSaturated get
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
true if is saturated; otherwise, false.
Definition at line 118 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (collect is RingBuffer<T>)
                 {
                     var buf = (RingBuffer<T>)collect;
                     return buf.IsSaturated;
                 }
                 else
                 {
                     return false;
                 }
             }
         }
Referenced by Juniper.Widgets.QualityDegrader.Update().
Maximum
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Maximum get protected set
The maximum value in the collection (calculated during collection modification)
Definition at line 16 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (max == null)
                 {
                     RecomputeStatistics();
                 }
                 return max;
             }
             protected set
             {
                 max = value;
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Mean
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Mean get protected set
The arithmetic mean of the values in the collection (calculated during collection modification)
Definition at line 54 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (mean == null)
                 {
                     RecomputeStatistics();
                 }
                 return mean;
             }
             protected set
             {
                 mean = value;
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Widgets.Shaker.PrintDebugReport(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), Juniper.World.CompassRose.SetNorth(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
Minimum
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Minimum get protected set
The minimum value in the collection (calculated during collection modification)
Definition at line 35 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (min == null)
                 {
                     RecomputeStatistics();
                 }
                 return min;
             }
             protected set
             {
                 min = value;
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
StandardDeviation
T? Juniper.Statistics.AbstractCollectionStatistics< T >.StandardDeviation get protected set
The standard deviation of the values in the collection (calculated during collection modification)
Definition at line 93 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (standardDev == null)
                 {
                     RecomputeStatistics();
                 }
                 return standardDev;
             }
             protected set
             {
                 standardDev = value;
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.Append(), Juniper.Widgets.Shaker.PrintDebugReport(), Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
this[int index]
T Juniper.Statistics.AbstractCollectionStatistics< T >.this[int index] get set
Gets or sets the element at the specified index.
Parameters
index An index into the buffer, modulated by the buffer length.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
The element at the specified index.
Definition at line 162 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 return collect[index];
             }
             set
             {
                 collect[index] = value;
             }
         }
Variance
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Variance get protected set
The square of the standard deviation of the values in the collection (calculated during collection modification)
Definition at line 74 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (variance == null)
                 {
                     RecomputeStatistics();
                 }
                 return variance;
             }
             protected set
             {
                 variance = value;
             }
         }
Referenced by Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.RecomputeStatistics(), and Juniper.Statistics.AbstractCollectionStatistics< Vector4 >.UpdateStatistics().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Statistics/AbstractCollectionStatistics.cs