export declare const anyChemical: import("./util").MediaType;
export declare const Chemical_X_Cdx: import("./util").MediaType;
export declare const Chemical_X_Cif: import("./util").MediaType;
export declare const Chemical_X_Cmdf: import("./util").MediaType;
export declare const Chemical_X_Cml: import("./util").MediaType;
export declare const Chemical_X_Csml: import("./util").MediaType;
export declare const Chemical_X_Pdb: import("./util").MediaType;
export declare const Chemical_X_Xyz: import("./util").MediaType;
export declare const allChemical: import("./util").MediaType[];
