export { MediaType, mediaTypeGuessByExtension, mediaTypeGuessByFileName, mediaTypeNormalizeFileName, mediaTypeParse, mediaTypesMatch } from "./util";
export declare const anyApplication: import("./util").MediaType;
export declare const allApplication: import("./util").MediaType[];
export declare const anyAudio: import("./util").MediaType;
export declare const allAudio: import("./util").MediaType[];
export declare const anyChemical: import("./util").MediaType;
export declare const allChemical: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyFont: import("./util").MediaType;
export declare const allFont: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyImage: import("./util").MediaType;
export declare const allImage: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyMessage: import("./util").MediaType;
export declare const allMessage: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyModel: import("./util").MediaType;
export declare const allModel: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyMultipart: import("./util").MediaType;
export declare const allMultipart: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyText: import("./util").MediaType;
export declare const allText: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyVideo: import("./util").MediaType;
export declare const allVideo: (import("./util").MediaType | import("./util").MediaType[])[];
export declare const anyXConference: import("./util").MediaType;
export declare const allXConference: import("./util").MediaType[];
export declare const anyXShader: import("./util").MediaType;
export declare const allXShader: (import("./util").MediaType | import("./util").MediaType[])[];
