export { MediaType, mediaTypeGuessByExtension, mediaTypeGuessByFileName, mediaTypeNormalizeFileName, mediaTypeParse, mediaTypesMatch } from "./util";
export declare const anyApplication: void;
export declare const allApplication: (void | import("./util").MediaType)[];
export declare const anyAudio: void;
export declare const allAudio: (void | import("./util").MediaType)[];
export declare const anyChemical: void;
export declare const allChemical: (void | void[])[];
export declare const anyFont: void;
export declare const allFont: (void | void[])[];
export declare const anyImage: void;
export declare const allImage: (void | import("./util").MediaType | void[])[];
export declare const anyMessage: void;
export declare const allMessage: (void | import("./util").MediaType | void[])[];
export declare const anyModel: void;
export declare const allModel: (void | void[])[];
export declare const anyMultipart: void;
export declare const allMultipart: (void | void[])[];
export declare const anyText: void;
export declare const allText: (void | import("./util").MediaType | void[])[];
export declare const anyVideo: void;
export declare const allVideo: (void | void[])[];
export declare const anyXConference: void;
export declare const allXConference: void[];
export declare const anyXShader: void;
export declare const allXShader: (void | void[])[];
