Juniper: Juniper.IO.MemoryCacheLayer Class Reference
Juniper.IO.MemoryCacheLayer Class Reference
Public Member Functions
virtual bool CanCache (ContentReference fileRef)
virtual bool IsCached (ContentReference fileRef)
Stream Create (ContentReference fileRef)
Task< Stream > GetStreamAsync (ContentReference fileRef, IProgress prog)
IEnumerable< ContentReference > GetContentReferences (MediaType ofType)
bool Delete (ContentReference fileRef)
Private Attributes
readonly ConcurrentDictionary< MediaType, ConcurrentDictionary< string, MemoryStream > > store = new ConcurrentDictionary<MediaType, ConcurrentDictionary<string, MemoryStream>>()
Detailed Description
Definition at line 8 of file MemoryCacheLayer.cs.
Member Function Documentation
CanCache()
virtual bool Juniper.IO.MemoryCacheLayer.CanCache (ContentReference fileRef) inline virtual
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 12 of file MemoryCacheLayer.cs.
         {
             return true;
         }
Create()
Stream Juniper.IO.MemoryCacheLayer.Create (ContentReference fileRef) inline
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 28 of file MemoryCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new System.ArgumentNullException(nameof(fileRef));
             }
             var subStore = store.Default(fileRef.ContentType);
             var mem = new MemoryStream();
             return subStore[fileRef.CacheID] = mem;
         }
References Juniper.IO.ContentReference.CacheID, Juniper.IO.ContentReference.ContentType, and Juniper.IO.MemoryCacheLayer.store.
Delete()
bool Juniper.IO.MemoryCacheLayer.Delete (ContentReference fileRef) inline
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 69 of file MemoryCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new System.ArgumentNullException(nameof(fileRef));
             }
             if (IsCached(fileRef))
             {
                 return store[fileRef.ContentType]
                     .TryRemove(fileRef.CacheID, out _);
             }
             else
             {
                 return false;
             }
         }
References Juniper.IO.ContentReference.CacheID, Juniper.IO.ContentReference.ContentType, Juniper.IO.MemoryCacheLayer.IsCached(), and Juniper.IO.MemoryCacheLayer.store.
GetContentReferences()
IEnumerable<ContentReference> Juniper.IO.MemoryCacheLayer.GetContentReferences (MediaType ofType) inline
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 58 of file MemoryCacheLayer.cs.
         {
             if (store.ContainsKey(ofType))
             {
                 foreach (var cacheID in store[ofType].Keys)
                 {
                     yield return cacheID + ofType;
                 }
             }
         }
References Juniper.IO.MemoryCacheLayer.store.
GetStreamAsync()
Task<Stream> Juniper.IO.MemoryCacheLayer.GetStreamAsync (ContentReference fileRef, IProgress prog) inline
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 40 of file MemoryCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new System.ArgumentNullException(nameof(fileRef));
             }
             if (!IsCached(fileRef))
             {
                 throw new FileNotFoundException("File not found in memory cache!", fileRef.ToString());
             }
             var data = store[fileRef.ContentType][fileRef.CacheID].ToArray();
             var stream = new MemoryStream(data);
             var progStream = new ProgressStream(stream, data.Length, prog, true);
             return Task.FromResult((Stream)progStream);
         }
References Juniper.IO.ContentReference.CacheID, Juniper.IO.ContentReference.ContentType, Juniper.IO.MemoryCacheLayer.IsCached(), Juniper.IO.MemoryCacheLayer.store, and Juniper.IO.ContentReference.ToString().
IsCached()
virtual bool Juniper.IO.MemoryCacheLayer.IsCached (ContentReference fileRef) inline virtual
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 17 of file MemoryCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new System.ArgumentNullException(nameof(fileRef));
             }
             return store.ContainsKey(fileRef.ContentType)
                 && store[fileRef.ContentType].ContainsKey(fileRef.CacheID);
         }
References Juniper.IO.ContentReference.CacheID, Juniper.IO.ContentReference.ContentType, and Juniper.IO.MemoryCacheLayer.store.
Referenced by Juniper.IO.MemoryCacheLayer.Delete(), and Juniper.IO.MemoryCacheLayer.GetStreamAsync().
Member Data Documentation
store
readonly ConcurrentDictionary<MediaType, ConcurrentDictionary<string, MemoryStream> > Juniper.IO.MemoryCacheLayer.store = new ConcurrentDictionary<MediaType, ConcurrentDictionary<string, MemoryStream>>() private
Definition at line 10 of file MemoryCacheLayer.cs.
Referenced by Juniper.IO.MemoryCacheLayer.Create(), Juniper.IO.MemoryCacheLayer.Delete(), Juniper.IO.MemoryCacheLayer.GetContentReferences(), Juniper.IO.MemoryCacheLayer.GetStreamAsync(), and Juniper.IO.MemoryCacheLayer.IsCached().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/MemoryCacheLayer.cs