Juniper: Juniper.UnityEditor.SerializedPropertyExt Class Reference
Juniper.UnityEditor.SerializedPropertyExt Class Reference
Static Public Member Functions
static T GetValue< T > (this SerializedProperty property)
static T GetObject< T > (this SerializedProperty property)
static T GetScriptableObject< T > (this SerializedProperty property)
Static Private Member Functions
static object GetObject (SerializedProperty property)
Static Private Attributes
static Regex arrayIndexPattern = new Regex("data\\[(\\w+)\\]", RegexOptions.Compiled)
The array index pattern.
Detailed Description
Definition at line 8 of file SerializedPropertyExt.cs.
Member Function Documentation
GetObject()
static object Juniper.UnityEditor.SerializedPropertyExt.GetObject (SerializedProperty property) inline static private
Definition at line 46 of file SerializedPropertyExt.cs.
         {
             object head = property.serializedObject.targetObject;
             var parts = property.propertyPath.Split('.');
             for (var i = 0; i < parts.Length && head != null; ++i)
             {
                 var part = parts[i];
                 if (part == "Array")
                 {
                     var indexStr = parts[++i];
                     var match = arrayIndexPattern.Match(indexStr);
                     var index = int.Parse(match.Groups[1].Value);
                     var arr = (object[])head;
                     if (0 <= index && index < arr.Length)
                     {
                         head = arr[index];
                     }
                     else
                     {
                         head = null;
                     }
                 }
                 else
                 {
                     var type = head.GetType();
                     var field = type.GetField(part, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                     head = field.GetValue(head);
                 }
             }
             return head;
         }
References Juniper.UnityEditor.SerializedPropertyExt.arrayIndexPattern.
Referenced by Juniper.UnityEditor.SerializedPropertyExt.GetObject< T >(), Juniper.UnityEditor.SerializedPropertyExt.GetScriptableObject< T >(), and Juniper.UnityEditor.SerializedPropertyExt.GetValue< T >().
GetObject< T >()
static T Juniper.UnityEditor.SerializedPropertyExt.GetObject< T > (this SerializedProperty property) inline static
Type Constraints
T : new()
Definition at line 23 of file SerializedPropertyExt.cs.
                                                                                : new()
         {
             return (T)GetObject(property);
         }
References Juniper.UnityEditor.SerializedPropertyExt.GetObject().
GetScriptableObject< T >()
static T Juniper.UnityEditor.SerializedPropertyExt.GetScriptableObject< T > (this SerializedProperty property) inline static
Type Constraints
T : ScriptableObject
Definition at line 28 of file SerializedPropertyExt.cs.
                                                                                          : ScriptableObject
         {
             var obj = GetObject(property);
             if (obj == null)
             {
                 return ScriptableObject.CreateInstance<T>();
             }
             else
             {
                 return (T)obj;
             }
         }
References Juniper.UnityEditor.SerializedPropertyExt.GetObject().
GetValue< T >()
static T Juniper.UnityEditor.SerializedPropertyExt.GetValue< T > (this SerializedProperty property) inline static
Type Constraints
T : struct
Definition at line 10 of file SerializedPropertyExt.cs.
                                                                               : struct
         {
             var value = GetObject(property);
             if (value == null)
             {
                 return default(T);
             }
             else
             {
                 return (T)value;
             }
         }
References Juniper.UnityEditor.SerializedPropertyExt.GetObject().
Member Data Documentation
arrayIndexPattern
Regex Juniper.UnityEditor.SerializedPropertyExt.arrayIndexPattern = new Regex("data\\[(\\w+)\\]", RegexOptions.Compiled) static private
The array index pattern.
Definition at line 44 of file SerializedPropertyExt.cs.
Referenced by Juniper.UnityEditor.SerializedPropertyExt.GetObject().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/SerializedPropertyExt.cs