Juniper: Juniper.Unity.Anchoring.AnchorStore Class Reference
Juniper.Unity.Anchoring.AnchorStore Class Reference
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This component creates the native anchor type for any given subsystem, and save it to its native anchor store.
Public Member Functions
void Awake ()
Acquires the anchorStore
override bool HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store.
override void ResetData ()
Delete saved anchors, if there are any.
bool DropAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
void WeighAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Protected Member Functions
override AnchorType FindAnchor (GameObject gameObject)
Finds any anchor components on the given object
override AnchorType LoadAnchor (string ID)
Loads an anchor out of a platform-specific anchor data store.
virtual AnchorType CreateAnchor (string ID, GameObject gameObject)
Creates a new anchor.
override AnchorType SynchronizeAnchor (string ID, GameObject gameObject)
Looks to see if the anchor was already in the data store, then loads it along with the objects scale if it was, or creates it and saves the scale if it wasn't.
override void DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor)
Removes an anchor along with its scale from the data store.
virtual bool IsGood (AnchorType anchor)
Checks to see if an anchor is valid.
virtual bool IsSaved (AnchorType anchor)
Checks to see if an anchor has been saved in the data store.
Static Protected Member Functions
static string MakeID (string name)
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
static bool HasValue (string name)
Check to see if a given name exists in the data store.
static void SaveValue< T > (string name, T value)
Saves a value to the data store.
static T LoadValue< T > (string name)
Gets a value back out of data store.
static bool DeleteValue (string name)
Removes a value from the data store.
Detailed Description
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This component creates the native anchor type for any given subsystem, and save it to its native anchor store.
Definition at line 17 of file AnchorStore.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Anchoring.ARKitAnchorStore.Awake () inline inherited
Acquires the anchorStore
Definition at line 18 of file ARKitAnchorStore.cs.
         {
             anchorStore = new UnityARAnchorManager();
         }
References Juniper.Unity.Anchoring.ARKitAnchorStore.anchorStore.
CreateAnchor()
virtual AnchorType Juniper.Unity.Anchoring.ARKitAnchorStore.CreateAnchor (string ID, GameObject gameObject) inline protected virtual inherited
Creates a new anchor.
Parameters
ID The name of the anchor to create.
gameObject The object to be anchored.
Returns
The new anchor.
Implements Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 49 of file ARKitAnchorStore.cs.
         {
             var anchor = gameObject.AddComponent<UnityARUserAnchorComponent>();
             anchorStore.Add(ID, anchor);
             return anchor;
         }
References Juniper.Unity.Anchoring.ARKitAnchorStore.anchorStore.
DeleteAnchor()
override void Juniper.Unity.Anchoring.ARKitAnchorStore.DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor) inline protected virtual inherited
Removes an anchor along with its scale from the data store.
Parameters
ID The name of the anchor to remove
gameObject The object that was anchored
anchor The anchor to destory
Reimplemented from Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 66 of file ARKitAnchorStore.cs.
         {
             gameObject.transform.SetParent(anchor.transform.parent, true);
             if (anchor.transform.childCount == 0)
             {
                 anchorStore.Remove(ID);
                 anchor.gameObject.Destroy();
             }
         }
References Juniper.Unity.Anchoring.ARKitAnchorStore.anchorStore.
DeleteValue()
static bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue (string name) inline static protected inherited
Removes a value from the data store.
Parameters
name
Returns
Definition at line 97 of file AbstractAnchorStore.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 PlayerPrefs.DeleteKey(key);
                 NameList = NameList.Where(k => k != name).ToArray();
                 PlayerPrefs.Save();
                 return true;
             }
             else
             {
                 return false;
             }
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DeleteAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.LoadValue< T >(), Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.ResetData(), and Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.WeighAnchor().
DropAnchor()
bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor (string ID, GameObject gameObject) inline inherited
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
Returns
true, if anchor existed on the object, existed in the datastore, or was successfully created, false otherwise.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 173 of file AbstractAnchorStore.cs.
         {
             if (string.IsNullOrEmpty(ID))
             {
                 throw new ArgumentException("Parameter must have a value.", nameof(ID));
             }
             var anchor = FindAnchor(gameObject);
             if (!IsSaved(anchor))
             {
                 anchor = SynchronizeAnchor(ID, gameObject);
             }
             return IsGood(anchor);
         }
Referenced by Juniper.Unity.Anchoring.Anchored.DropAnchor().
FindAnchor()
override AnchorType Juniper.Unity.Anchoring.ARKitAnchorStore.FindAnchor (GameObject gameObject) inline protected virtual inherited
Finds any anchor components on the given object
Parameters
gameObject The object that might have an anchor on it
Returns
Reimplemented from Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 38 of file ARKitAnchorStore.cs.
         {
             return base.FindAnchor(gameObject?.transform?.parent?.gameObject);
         }
HasAnchor()
override bool Juniper.Unity.Anchoring.ARKitAnchorStore.HasAnchor (string anchorID) inline virtual inherited
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store.
Returns
true, if anchor exists, false otherwise.
Parameters
anchorID Anchor identifier.
Implements Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 23 of file ARKitAnchorStore.cs.
         {
             return anchorStore.ContainsKey(anchorID);
         }
References Juniper.Unity.Anchoring.ARKitAnchorStore.anchorStore.
HasValue()
static bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasValue (string name) inline static protected inherited
Check to see if a given name exists in the data store.
Parameters
name
Returns
Definition at line 43 of file AbstractAnchorStore.cs.
         {
             return PlayerPrefs.HasKey(MakeID(name));
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.SynchronizeAnchor().
IsGood()
virtual bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsGood (AnchorType anchor) inline protected virtual inherited
Checks to see if an anchor is valid.
Parameters
anchor
Returns
Reimplemented in Juniper.Unity.Anchoring.HoloLensAnchorStore.
Definition at line 227 of file AbstractAnchorStore.cs.
         {
             return anchor != null;
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DropAnchor().
IsSaved()
virtual bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsSaved (AnchorType anchor) inline protected virtual inherited
Checks to see if an anchor has been saved in the data store.
Parameters
anchor The anchor to check against the data store
Returns
True, if the anchor has already been saved, false otherwise
Reimplemented in Juniper.Unity.Anchoring.HoloLensAnchorStore.
Definition at line 277 of file AbstractAnchorStore.cs.
         {
             return anchor != null;
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DropAnchor().
LoadAnchor()
override AnchorType Juniper.Unity.Anchoring.ARKitAnchorStore.LoadAnchor (string ID) inline protected virtual inherited
Loads an anchor out of a platform-specific anchor data store.
Parameters
ID The name of the anchor to load.
Returns
The persisted anchor.
Implements Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 43 of file ARKitAnchorStore.cs.
         {
             return anchorStore[ID];
         }
References Juniper.Unity.Anchoring.ARKitAnchorStore.anchorStore.
LoadValue< T >()
static T Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadValue< T > (string name) inline static protected inherited
Gets a value back out of data store.
Template Parameters
T
Parameters
name
Returns
Definition at line 74 of file AbstractAnchorStore.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 try
                 {
                     return JsonConvert.DeserializeObject<T>(PlayerPrefs.GetString(key));
                 }
                 catch
                 {
                     DeleteValue(name);
                 }
             }
             return default(T);
         }
MakeID()
static string Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID (string name) inline static protected inherited
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
Parameters
name A controllable part of the name, to be modified to be unique in the data store.
Returns
A name in the data store unique to AbstractAnchorStore.
Definition at line 28 of file AbstractAnchorStore.cs.
         {
             return ID_PREFIX + name;
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DeleteValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.HasValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.LoadValue< T >(), and Juniper.Unity.Anchoring.AbstractAnchorStore< MockWorldAnchor >.SaveValue< T >().
ResetData()
override void Juniper.Unity.Anchoring.ARKitAnchorStore.ResetData () inline virtual inherited
Delete saved anchors, if there are any.
Reimplemented from Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 31 of file ARKitAnchorStore.cs.
         {
             base.ResetData();
             anchorStore.Clear();
         }
References Juniper.Unity.Anchoring.ARKitAnchorStore.anchorStore.
SaveValue< T >()
static void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue< T > (string name, T value) inline static protected inherited
Saves a value to the data store.
Parameters
name The name of the object to save.
value The value to save.
Definition at line 53 of file AbstractAnchorStore.cs.
         {
             PlayerPrefs.SetString(MakeID(name), JsonConvert.SerializeObject(value));
             var names = NameList;
             if (!names.Contains(name))
             {
                 var n = names.ToList();
                 n.Add(name);
                 NameList = n.ToArray();
             }
             PlayerPrefs.Save();
         }
SynchronizeAnchor()
override AnchorType Juniper.Unity.Anchoring.ARKitAnchorStore.SynchronizeAnchor (string ID, GameObject gameObject) inline protected virtual inherited
Looks to see if the anchor was already in the data store, then loads it along with the objects scale if it was, or creates it and saves the scale if it wasn't.
Parameters
ID The name of the object to serialize
gameObject The object that is being anchored
Returns
The synchronized anchor
Reimplemented from Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 56 of file ARKitAnchorStore.cs.
         {
             var anchor = base.SynchronizeAnchor(ID, gameObject);
             if (anchor != null)
             {
                 gameObject.transform.SetParent(anchor.transform, true);
             }
             return anchor;
         }
WeighAnchor()
void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor (string ID, GameObject gameObject) inline inherited
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 240 of file AbstractAnchorStore.cs.
         {
             var anchor = FindAnchor(gameObject);
             if (anchor != null)
             {
                 DeleteAnchor(ID, gameObject, anchor);
                 DeleteValue(ID + "-scale");
             }
         }
Referenced by Juniper.Unity.Anchoring.Anchored.WeighAnchor().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Anchoring/AnchorStore.cs