Juniper: Juniper.ImageTracking.ARKitTrackableFoundEventHandler Class Reference
Juniper.ImageTracking.ARKitTrackableFoundEventHandler Class Reference
Public Member Functions
void OnValidate ()
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
void OnEnable ()
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
virtual void Update ()
Checks the tracking status of the target and fires any appropriate change/found/lost events.
void ForceFound ()
Forces the onFound event to fire.
void ForceLost ()
Forces the onLost event to fire.
void OnDisable ()
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
virtual void Awake ()
Registers for Vuforia's trackable event handlers.
Public Attributes
ARReferenceImagesSet imagesSet
The ARKit set of tracked images
ARReferenceImage image
One of the images from an ARKit set of tracked images.
bool Found
This value is set to true when the target has been found.
bool Safe = true
This value is set to true when the user is at a safe distance from the target.
bool Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Transform attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
float safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
BooleanEvent onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
UnityEvent onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
UnityEvent onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
UnityEvent onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
UnityEvent onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Events
EventHandler< TrackingStateChangeEventArgs > TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Detailed Description
Definition at line 5 of file ARKitTrackableFoundEventHandler.cs.
Member Function Documentation
Awake()
virtual void Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Awake () inline virtual inherited
Registers for Vuforia's trackable event handlers.
Definition at line 263 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (Find.Any(out TrackerKeeper keeper))
             {
                 keeper.Register(this);
             }
         }
ForceFound()
void Juniper.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound () inline inherited
Forces the onFound event to fire.
Definition at line 232 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasFound = false;
             Found = true;
             Extended = false;
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Found, and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
ForceLost()
void Juniper.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost () inline inherited
Forces the onLost event to fire.
Definition at line 243 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasFound = true;
             Found = false;
             Extended = false;
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Found, and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable().
OnDisable()
void Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable () inline inherited
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
Definition at line 254 of file AbstractTrackableFoundEventHandler.cs.
         {
             ForceLost();
             Update();
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Update().
OnEnable()
void Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnEnable () inline inherited
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
Definition at line 128 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasSafe = Safe = true;
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Safe, and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.wasSafe.
OnValidate()
void Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate () inline inherited
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
Definition at line 100 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (attachmentPoint == null)
             {
                 attachmentPoint = transform
                     .Children()
                     .FirstOrDefault(t =>
                         t.CompareTag(TAG_NAME));
                 if (attachmentPoint == null)
                 {
                     attachmentPoint = transform
                         .Children()
                         .FirstOrDefault(t =>
                             t.name == TRANSFORM_NAME);
                     if (attachmentPoint == null)
                     {
                         attachmentPoint = transform;
                     }
                 }
             }
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.attachmentPoint, Juniper.ImageTracking.AbstractTrackableFoundEventHandler.TAG_NAME, and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.TRANSFORM_NAME.
Update()
virtual void Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Update () inline virtual inherited
Checks the tracking status of the target and fires any appropriate change/found/lost events.
Definition at line 136 of file AbstractTrackableFoundEventHandler.cs.
         {
             OnFoundChanged();
             SafetyCheck();
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged(), and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable().
Member Data Documentation
attachmentPoint
Transform Juniper.ImageTracking.AbstractTrackableFoundEventHandler.attachmentPoint inherited
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
Definition at line 44 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate().
Extended
bool Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Extended inherited
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Definition at line 38 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound(), and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost().
Found
bool Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Found inherited
This value is set to true when the target has been found.
Definition at line 16 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound(), Juniper.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged(), Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged(), Juniper.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck(), and Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder().
image
ARReferenceImage Juniper.ImageTracking.ARKitTrackableFoundEventHandler.image
One of the images from an ARKit set of tracked images.
Definition at line 15 of file ARKitTrackableFoundEventHandler.cs.
imagesSet
ARReferenceImagesSet Juniper.ImageTracking.ARKitTrackableFoundEventHandler.imagesSet
The ARKit set of tracked images
Definition at line 10 of file ARKitTrackableFoundEventHandler.cs.
onFound
UnityEvent Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onFound = new UnityEvent() inherited
A Unity Event that fires when the target is first found.
Definition at line 68 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), and Juniper.ImageTracking.AbstractTrackerKeeper.Register().
onLost
UnityEvent Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onLost = new UnityEvent() inherited
A Unity Event that fires when the target is been completely lost.
Definition at line 73 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), and Juniper.ImageTracking.AbstractTrackerKeeper.Register().
onProximity
UnityEvent Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onProximity = new UnityEvent() inherited
A Unity Event that fires when the user gets too close to the target.
Definition at line 78 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.ImageTracking.AbstractTrackerKeeper.Register().
onSafe
UnityEvent Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onSafe = new UnityEvent() inherited
A Unity Event that fires when the user returns to a safe distance from the target.
Definition at line 83 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.ImageTracking.AbstractTrackerKeeper.Register().
onTrackingStateChange
BooleanEvent Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onTrackingStateChange = new BooleanEvent() inherited
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
Definition at line 56 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged().
Safe
bool Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Safe = true inherited
This value is set to true when the user is at a safe distance from the target.
Definition at line 27 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnEnable(), Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
safeDistance
float Juniper.ImageTracking.AbstractTrackableFoundEventHandler.safeDistance inherited
The minimum distance in meters from the target at which to consider the user "safe".
Definition at line 49 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
Event Documentation
TrackingStateChange
EventHandler<TrackingStateChangeEventArgs> Juniper.ImageTracking.AbstractTrackableFoundEventHandler.TrackingStateChange inherited
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Definition at line 63 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Platforms/ARKit/ARKitTrackableFoundEventHandler.cs