Juniper: Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler Class Reference
Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler Class Reference
Public Member Functions
void OnValidate ()
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
void OnEnable ()
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
virtual void Update ()
Checks the tracking status of the target and fires any appropriate change/found/lost events.
void ForceFound ()
Forces the onFound event to fire.
void ForceLost ()
Forces the onLost event to fire.
void OnDisable ()
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
virtual void Awake ()
Registers for Vuforia's trackable event handlers.
Public Attributes
bool Found
This value is set to true when the target has been found.
bool Safe = true
This value is set to true when the user is at a safe distance from the target.
bool Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Transform attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
float safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
BooleanEvent onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
UnityEvent onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
UnityEvent onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
UnityEvent onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
UnityEvent onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Events
EventHandler< TrackingStateChangeEventArgs > TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Private Member Functions
void SafetyCheck ()
Check to see if the user is standing at a comfortable distance from the object.
void OnSafeOrProximity ()
If the value of Safe has changed, fires the onSafe or onProximity event.
void OnFoundChanged ()
If the value of Found has changed, records the time at which the object was found, sets the visibility of the object, and fires the onFound, onLost, onTrackingStateChange, or the TrackingStateChange events.
void OnLostOrFound ()
Fires the onLost or onFound events.
void OnTrackingStateChanged ()
Firest the onTrackingStateChange and TrackingStateChange events.
Private Attributes
bool? wasFound
Whether or not Found was set on the previous frame, to make it easier to detect changes to it.
bool wasSafe = true
Whether or not Safe was set on the previou frame.
const string TAG_NAME = "Tracked Object Attachment Point"
The tag that the attachment point is expected to have.
const string TRANSFORM_NAME = "Attachment Point"
The name that the attachment point is expected to have.
Detailed Description
Definition at line 11 of file AbstractTrackableFoundEventHandler.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Awake () inline virtual
Registers for Vuforia's trackable event handlers.
Definition at line 251 of file AbstractTrackableFoundEventHandler.cs.
         {
             var keeper = ComponentExt.FindAny<TrackerKeeper>();
             keeper?.Register(this);
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
ForceFound()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound () inline
Forces the onFound event to fire.
Definition at line 220 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasFound = false;
             Found = true;
             Extended = false;
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
ForceLost()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost () inline
Forces the onLost event to fire.
Definition at line 231 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasFound = true;
             Found = false;
             Extended = false;
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable().
OnDisable()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable () inline
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
Definition at line 242 of file AbstractTrackableFoundEventHandler.cs.
         {
             ForceLost();
             Update();
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Update().
OnEnable()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnEnable () inline
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
Definition at line 116 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasSafe = Safe = true;
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Safe, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasSafe.
OnFoundChanged()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged () inline private
If the value of Found has changed, records the time at which the object was found, sets the visibility of the object, and fires the onFound, onLost, onTrackingStateChange, or the TrackingStateChange events.
Definition at line 178 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (Found != wasFound)
             {
                 this.SetVisible(Found);
                 OnTrackingStateChanged();
                 OnLostOrFound();
                 wasFound = Found;
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Update().
OnLostOrFound()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound () inline private
Fires the onLost or onFound events.
Definition at line 192 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (wasFound != null)
             {
                 if (Found)
                 {
                     onFound?.Invoke();
                 }
                 else
                 {
                     onLost?.Invoke();
                 }
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onFound, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onLost, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged().
OnSafeOrProximity()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity () inline private
If the value of Safe has changed, fires the onSafe or onProximity event.
Definition at line 155 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (Safe != wasSafe)
             {
                 if (Safe)
                 {
                     onSafe?.Invoke();
                 }
                 else
                 {
                     onProximity?.Invoke();
                 }
                 wasSafe = Safe;
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onProximity, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onSafe, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Safe, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasSafe.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
OnTrackingStateChanged()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged () inline private
Firest the onTrackingStateChange and TrackingStateChange events.
Definition at line 210 of file AbstractTrackableFoundEventHandler.cs.
         {
             onTrackingStateChange?.Invoke(Found);
             TrackingStateChange?.Invoke(this, new TrackingStateChangeEventArgs(this, Found));
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onTrackingStateChange, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TrackingStateChange.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged().
OnValidate()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate () inline
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
Definition at line 100 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (attachmentPoint == null)
             {
                 attachmentPoint = transform.Children().FirstOrDefault(t =>
                     t.tag == TAG_NAME)
                                            ?? transform.Children().FirstOrDefault(t =>
                                                t.name == TRANSFORM_NAME)
                                            ?? transform;
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.attachmentPoint, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TAG_NAME, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TRANSFORM_NAME.
SafetyCheck()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck () inline private
Check to see if the user is standing at a comfortable distance from the object.
Definition at line 133 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (Found)
             {
                 var camT = DisplayManager.MainCamera.transform;
                 var delta = transform.position - camT.position;
                 // we only care about the over-ground distance.
                 delta.y = 0;
                 //Add 10% to the safe distance to return to safety so we don't jitter
                 // over the edge.
                 Safe = Safe && delta.magnitude >= safeDistance
                     || !Safe && delta.magnitude >= safeDistance * 1.1f;
                 OnSafeOrProximity();
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, Juniper.Unity.Display.AbstractDisplayManager.MainCamera, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Safe, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.safeDistance.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Update().
Update()
virtual void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Update () inline virtual
Checks the tracking status of the target and fires any appropriate change/found/lost events.
Definition at line 124 of file AbstractTrackableFoundEventHandler.cs.
         {
             OnFoundChanged();
             SafetyCheck();
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable().
Member Data Documentation
attachmentPoint
Transform Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
Definition at line 44 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate().
Extended
bool Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Definition at line 38 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost().
Found
bool Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found
This value is set to true when the target has been found.
Definition at line 16 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onFound
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
Definition at line 68 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onLost
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
Definition at line 73 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onProximity
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
Definition at line 78 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onSafe
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Definition at line 83 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onTrackingStateChange
BooleanEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
Definition at line 56 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged().
Safe
bool Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Safe = true
This value is set to true when the user is at a safe distance from the target.
Definition at line 27 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnEnable(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
safeDistance
float Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
Definition at line 49 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
TAG_NAME
const string Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TAG_NAME = "Tracked Object Attachment Point" private
The tag that the attachment point is expected to have.
Definition at line 88 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate().
TRANSFORM_NAME
const string Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TRANSFORM_NAME = "Attachment Point" private
The name that the attachment point is expected to have.
Definition at line 93 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate().
wasFound
bool? Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasFound private
Whether or not Found was set on the previous frame, to make it easier to detect changes to it.
Definition at line 22 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound().
wasSafe
bool Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasSafe = true private
Whether or not Safe was set on the previou frame.
Definition at line 32 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnEnable(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity().
Event Documentation
TrackingStateChange
EventHandler<TrackingStateChangeEventArgs> Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Definition at line 63 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/ImageTracking/AbstractTrackableFoundEventHandler.cs