Juniper: Juniper.IO.ForkedStream Class Reference
Juniper.IO.ForkedStream Class Reference
Public Member Functions
ForkedStream (params Stream[] streams)
void AddStream (Stream stream)
override void Flush ()
override int Read (byte[] buffer, int offset, int count)
override long Seek (long offset, SeekOrigin origin)
override void SetLength (long value)
override void Write (byte[] buffer, int offset, int count)
override void WriteByte (byte value)
override void Close ()
Public Attributes
override bool CanRead => false
override long Length => streams[0].Length
Protected Member Functions
override void Dispose (bool disposing)
Properties
override bool CanSeek [get]
override bool CanWrite [get]
override long Position [get, set]
Private Attributes
readonly List< Stream > streams = new List<Stream>()
Detailed Description
Definition at line 6 of file ForkedStream.cs.
Constructor & Destructor Documentation
ForkedStream()
Juniper.IO.ForkedStream.ForkedStream (params Stream [] streams) inline
Definition at line 10 of file ForkedStream.cs.
         {
             this.streams.AddRange(streams);
         }
References Juniper.IO.ForkedStream.streams.
Member Function Documentation
AddStream()
void Juniper.IO.ForkedStream.AddStream (Stream stream) inline
Definition at line 15 of file ForkedStream.cs.
         {
             streams.Add(stream);
         }
References Juniper.IO.ForkedStream.streams.
Close()
override void Juniper.IO.ForkedStream.Close () inline
Definition at line 120 of file ForkedStream.cs.
         {
             foreach (var stream in streams)
             {
                 stream.Close();
             }
         }
References Juniper.IO.ForkedStream.streams.
Dispose()
override void Juniper.IO.ForkedStream.Dispose (bool disposing) inline protected
Definition at line 128 of file ForkedStream.cs.
         {
             base.Dispose(disposing);
             if (disposing)
             {
                 foreach (var stream in streams)
                 {
                     stream.Dispose();
                 }
                 streams.Clear();
             }
         }
References Juniper.IO.ForkedStream.streams.
Flush()
override void Juniper.IO.ForkedStream.Flush () inline
Definition at line 72 of file ForkedStream.cs.
         {
             foreach (var stream in streams)
             {
                 stream.Flush();
             }
         }
References Juniper.IO.ForkedStream.streams.
Read()
override int Juniper.IO.ForkedStream.Read (byte [] buffer, int offset, int count) inline
Definition at line 80 of file ForkedStream.cs.
         {
             throw new System.NotImplementedException();
         }
Seek()
override long Juniper.IO.ForkedStream.Seek (long offset, SeekOrigin origin) inline
Definition at line 85 of file ForkedStream.cs.
         {
             long position = 0;
             foreach (var stream in streams)
             {
                 position = stream.Seek(offset, origin);
             }
             return position;
         }
References Juniper.IO.ForkedStream.streams.
SetLength()
override void Juniper.IO.ForkedStream.SetLength (long value) inline
Definition at line 96 of file ForkedStream.cs.
         {
             foreach (var stream in streams)
             {
                 stream.SetLength(value);
             }
         }
References Juniper.IO.ForkedStream.streams.
Write()
override void Juniper.IO.ForkedStream.Write (byte [] buffer, int offset, int count) inline
Definition at line 104 of file ForkedStream.cs.
         {
             foreach (var stream in streams)
             {
                 stream.Write(buffer, offset, count);
             }
         }
References Juniper.IO.ForkedStream.streams.
WriteByte()
override void Juniper.IO.ForkedStream.WriteByte (byte value) inline
Definition at line 112 of file ForkedStream.cs.
         {
             foreach (var stream in streams)
             {
                 stream.WriteByte(value);
             }
         }
References Juniper.IO.ForkedStream.streams.
Member Data Documentation
CanRead
override bool Juniper.IO.ForkedStream.CanRead => false
Definition at line 20 of file ForkedStream.cs.
Length
override long Juniper.IO.ForkedStream.Length => streams[0].Length
Definition at line 54 of file ForkedStream.cs.
streams
readonly List<Stream> Juniper.IO.ForkedStream.streams = new List<Stream>() private
Definition at line 8 of file ForkedStream.cs.
Referenced by Juniper.IO.ForkedStream.AddStream(), Juniper.IO.ForkedStream.Close(), Juniper.IO.ForkedStream.Dispose(), Juniper.IO.ForkedStream.Flush(), Juniper.IO.ForkedStream.ForkedStream(), Juniper.IO.ForkedStream.Seek(), Juniper.IO.ForkedStream.SetLength(), Juniper.IO.ForkedStream.Write(), and Juniper.IO.ForkedStream.WriteByte().
Property Documentation
CanSeek
override bool Juniper.IO.ForkedStream.CanSeek get
Definition at line 23 of file ForkedStream.cs.
         {
             get
             {
                 foreach (var stream in streams)
                 {
                     if (!stream.CanSeek)
                     {
                         return false;
                     }
                 }
                 return true;
             }
         }
CanWrite
override bool Juniper.IO.ForkedStream.CanWrite get
Definition at line 39 of file ForkedStream.cs.
         {
             get
             {
                 foreach (var stream in streams)
                 {
                     if (!stream.CanWrite)
                     {
                         return false;
                     }
                 }
                 return true;
             }
         }
Position
override long Juniper.IO.ForkedStream.Position get set
Definition at line 57 of file ForkedStream.cs.
         {
             get
             {
                 return streams[0].Position;
             }
             set
             {
                 foreach (var stream in streams)
                 {
                     stream.Position = value;
                 }
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/ForkedStream.cs