Juniper: Juniper.World.GIS.Google.Geocoding.AddressComponent Class Reference
Juniper.World.GIS.Google.Geocoding.AddressComponent Class Reference
Public Member Functions
void GetObjectData (SerializationInfo info, StreamingContext context)
override bool Equals (object obj)
bool Equals (AddressComponent other)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static int HashAddressComponents (IEnumerable< AddressComponentTypes > types)
static bool operator== (AddressComponent left, AddressComponent right)
static bool operator != (AddressComponent left, AddressComponent right)
Properties
string Long_Name [get]
string Short_Name [get]
string [] TypeStrings [get]
HashSet< AddressComponentTypes > Types [get]
internal int Key [get]
Private Member Functions
AddressComponent (SerializationInfo info, StreamingContext context)
Static Private Attributes
static readonly string LONG_NAME_FIELD = nameof(Long_Name).ToLowerInvariant()
static readonly string SHORT_NAME_FIELD = nameof(Short_Name).ToLowerInvariant()
static readonly string TYPES_FIELD = nameof(Types).ToLowerInvariant()
Detailed Description
Definition at line 9 of file AddressComponent.cs.
Constructor & Destructor Documentation
AddressComponent()
Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent (SerializationInfo info, StreamingContext context) inline private
Definition at line 42 of file AddressComponent.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Long_Name = info.GetString(LONG_NAME_FIELD);
             Short_Name = info.GetString(SHORT_NAME_FIELD);
             TypeStrings = info.GetValue<string[]>(TYPES_FIELD);
             Types = new HashSet<AddressComponentTypes>(
                 from typeStr in TypeStrings
                 select Enum.TryParse<AddressComponentTypes>(typeStr, out var parsedType)
                     ? parsedType
                     : AddressComponentTypes.None);
             Key = HashAddressComponents(Types);
         }
References Juniper.World.GIS.Google.Geocoding.AddressComponent.HashAddressComponents(), Juniper.World.GIS.Google.Geocoding.AddressComponent.Key, Juniper.World.GIS.Google.Geocoding.AddressComponent.Long_Name, Juniper.World.GIS.Google.Geocoding.AddressComponent.LONG_NAME_FIELD, Juniper.World.GIS.Google.Geocoding.AddressComponent.Short_Name, Juniper.World.GIS.Google.Geocoding.AddressComponent.SHORT_NAME_FIELD, Juniper.World.GIS.Google.Geocoding.AddressComponent.Types, Juniper.World.GIS.Google.Geocoding.AddressComponent.TYPES_FIELD, and Juniper.World.GIS.Google.Geocoding.AddressComponent.TypeStrings.
Member Function Documentation
Equals() [1/2]
override bool Juniper.World.GIS.Google.Geocoding.AddressComponent.Equals (object obj) inline
Definition at line 73 of file AddressComponent.cs.
         {
             return obj is AddressComponent addr && Equals(addr);
         }
Equals() [2/2]
bool Juniper.World.GIS.Google.Geocoding.AddressComponent.Equals (AddressComponent other) inline
Definition at line 78 of file AddressComponent.cs.
         {
             return other is object
                 && Key == other.Key
                 && Long_Name == other.Long_Name;
         }
References Juniper.World.GIS.Google.Geocoding.AddressComponent.Key, and Juniper.World.GIS.Google.Geocoding.AddressComponent.Long_Name.
GetHashCode()
override int Juniper.World.GIS.Google.Geocoding.AddressComponent.GetHashCode () inline
Definition at line 103 of file AddressComponent.cs.
         {
             var hashCode = 644590467;
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(Long_Name);
             hashCode = (hashCode * -1521134295) + Key.GetHashCode();
             return hashCode;
         }
References Juniper.World.GIS.Google.Geocoding.AddressComponent.Key, and Juniper.World.GIS.Google.Geocoding.AddressComponent.Long_Name.
GetObjectData()
void Juniper.World.GIS.Google.Geocoding.AddressComponent.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 61 of file AddressComponent.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(LONG_NAME_FIELD, Long_Name);
             info.AddValue(SHORT_NAME_FIELD, Short_Name);
             info.AddValue(TYPES_FIELD, TypeStrings);
         }
References Juniper.World.GIS.Google.Geocoding.AddressComponent.Long_Name, Juniper.World.GIS.Google.Geocoding.AddressComponent.LONG_NAME_FIELD, Juniper.World.GIS.Google.Geocoding.AddressComponent.Short_Name, Juniper.World.GIS.Google.Geocoding.AddressComponent.SHORT_NAME_FIELD, Juniper.World.GIS.Google.Geocoding.AddressComponent.TYPES_FIELD, and Juniper.World.GIS.Google.Geocoding.AddressComponent.TypeStrings.
HashAddressComponents()
static int Juniper.World.GIS.Google.Geocoding.AddressComponent.HashAddressComponents (IEnumerable< AddressComponentTypes > types) inline static
Definition at line 15 of file AddressComponent.cs.
         {
             if (types is null)
             {
                 throw new ArgumentNullException(nameof(types));
             }
             var key = 0;
             foreach (var type in types)
             {
                 key ^= type.GetHashCode();
             }
             return key;
         }
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetAddressComponent().
operator !=()
static bool Juniper.World.GIS.Google.Geocoding.AddressComponent.operator != (AddressComponent left, AddressComponent right) inline static
Definition at line 91 of file AddressComponent.cs.
         {
             return !(left == right);
         }
operator==()
static bool Juniper.World.GIS.Google.Geocoding.AddressComponent.operator== (AddressComponent left, AddressComponent right) inline static
Definition at line 85 of file AddressComponent.cs.
         {
             return ReferenceEquals(left, right)
                 || (left is object && left.Equals(right));
         }
ToString()
override string Juniper.World.GIS.Google.Geocoding.AddressComponent.ToString () inline
Definition at line 96 of file AddressComponent.cs.
         {
             var t = TypeStrings.ToString("|");
             return $"{t}:{Long_Name}";
         }
References Juniper.World.GIS.Google.Geocoding.AddressComponent.TypeStrings.
Member Data Documentation
LONG_NAME_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.AddressComponent.LONG_NAME_FIELD = nameof(Long_Name).ToLowerInvariant() static private
Definition at line 11 of file AddressComponent.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), and Juniper.World.GIS.Google.Geocoding.AddressComponent.GetObjectData().
SHORT_NAME_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.AddressComponent.SHORT_NAME_FIELD = nameof(Short_Name).ToLowerInvariant() static private
Definition at line 12 of file AddressComponent.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), and Juniper.World.GIS.Google.Geocoding.AddressComponent.GetObjectData().
TYPES_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.AddressComponent.TYPES_FIELD = nameof(Types).ToLowerInvariant() static private
Definition at line 13 of file AddressComponent.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), and Juniper.World.GIS.Google.Geocoding.AddressComponent.GetObjectData().
Property Documentation
Key
internal int Juniper.World.GIS.Google.Geocoding.AddressComponent.Key get private
Definition at line 39 of file AddressComponent.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), Juniper.World.GIS.Google.Geocoding.AddressComponent.Equals(), and Juniper.World.GIS.Google.Geocoding.AddressComponent.GetHashCode().
Long_Name
string Juniper.World.GIS.Google.Geocoding.AddressComponent.Long_Name get
Definition at line 31 of file AddressComponent.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), Juniper.World.GIS.Google.Geocoding.AddressComponent.Equals(), Juniper.World.GIS.Google.Geocoding.AddressComponent.GetHashCode(), and Juniper.World.GIS.Google.Geocoding.AddressComponent.GetObjectData().
Short_Name
string Juniper.World.GIS.Google.Geocoding.AddressComponent.Short_Name get
Definition at line 33 of file AddressComponent.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), and Juniper.World.GIS.Google.Geocoding.AddressComponent.GetObjectData().
Types
HashSet<AddressComponentTypes> Juniper.World.GIS.Google.Geocoding.AddressComponent.Types get
Definition at line 37 of file AddressComponent.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent().
TypeStrings
string [] Juniper.World.GIS.Google.Geocoding.AddressComponent.TypeStrings get
Definition at line 35 of file AddressComponent.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.AddressComponent.AddressComponent(), Juniper.World.GIS.Google.Geocoding.AddressComponent.GetObjectData(), and Juniper.World.GIS.Google.Geocoding.AddressComponent.ToString().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/Geocoding/AddressComponent.cs