Juniper: Juniper.XR.TrackerKeeper Class Reference
Juniper.XR.TrackerKeeper Class Reference
Public Member Functions
TrackableFoundEventHandler Register (TrackableFoundEventHandler target)
Register's a target and its events for the aggregated events issued by TrackerKeeper.
void Update ()
Checks the current tracking status and fires the events to indicate any change in the tracking status.
void OnDestroy ()
Tears down the tracker keeper.
void LoadDataSet (string dataSetName)
Loads a set of Vuforia markers from disk and activates it at runtime.
void ResetPET ()
On Vuforia, resets the Persistent Extended Tracking, or starts it if it hasn't already been running.
void StartTracker ()
Starts the tracker without changing any dataset data that has already been configured.
void StartTrackerWithDataSet (string dataSetName)
Initializes tracking of a set of targets.
void StartTrackerWithDataSetForTarget (string dataSetName, string targetName)
Initializes tracking of a specific target.
void Reset ()
Stop object tracking while in picker
Public Attributes
bool usePET
Set to true to enable using Vuforia's Persistent Extended Tracking.
bool manageVuforiaFrameRate = true
Set to true to set the target framerate lower than normal when the tracker is active.
bool DebugReport
Set to true to print out a debug report on the screen.
UnityEvent onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
UnityEvent onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
UnityEvent onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
UnityEvent onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
UnityEvent onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
TransformEvent onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
TransformEvent onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
UnityEvent onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
TransformEvent onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
TransformEvent onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Properties
bool Tracking [get, private set]
Is set to true when the tracking system is initialized and running.
bool TargetFound [get]
Returns true when any target has been found and is tracking.
IEnumerator WaitForTracker [get]
A coroutine that waits for a Vuforia ObjectTracker to become available.
WaitUntil WaitForNotInitializing [get]
What for Vuforia's initialization state to no longer be "INITIALIZING".
bool HasTargets [get]
Returns true when there are any GoodTargets.
bool Safe [get]
This value is set to true when the user is at a safe distance from the target.
Private Member Functions
void Start ()
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
void StopTracking ()
Cancel tracking and disable Vuforia. This also forces the Lost event on all of the currently tracked targets.
void EnableDataSet (string dataSetName)
On Vuforia, enables a specific set of data, either image targets, object targets, or scanned model targets.
IEnumerator EnablePETCoroutine ()
Handles marking a target as found, and optionally enables Vuforia's Persistent Extended Tracking.
IEnumerator StartTrackerCoroutine (string dataSetName, string targetName)
Initializes tracking of a specific target.
void Start ()
Once all of the camera setup has finished, we can check to see if we can start a tracker data set.
void WithTarget (string label, ARImageAnchor anchorData, Action< TrackableFoundEventHandler > act=null)
Finds a target object by name and updates its state.
void UnityARSessionNativeInterface_ARImageAnchorAddedEvent (ARImageAnchor anchorData)
An event handler for the first time an image is found by ARKit.
void UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent (ARImageAnchor anchorData)
An event handler that executes every time ARKit updates its understanding of an image.
void UnityARSessionNativeInterface_ARImageAnchorRemovedEvent (ARImageAnchor anchorData)
An event handler that executes when ARKit loses track of an image.
UnityAction TargetFinder (TrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetProximity (TrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetSafe (TrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetLoser (TrackableFoundEventHandler target)
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
void OnAllTargetsLost ()
Triggers the onAllTargetsLost event.
void StartTrackerDelayed ()
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
void PrintDebugReport ()
If DebugReport is set to true, prints a report on the status of tracking.
Private Attributes
const int VUFORIA_INIT_ATTEMPTS = 3
The number of times to attempt initializing Vuforia before just giving up.
ObjectTracker tracker
The Vuforia Tracker API.
bool firstTime = true
Used for reseting Vuforia's tracker the first time the application is started.
bool usingPET
Is set to true when Persistent Extended Tracking is active.
int numUpdates = 0
The number updates to the AR Background Image texture since tracking started. This value is used to delay switching from camera initialization to the app until after we are sure the camera is really ready.
Dictionary< string, TrackableFoundEventHandler > targetsByName
On ARKit, a lookup of targets by name.
Dictionary< string, ARReferenceImagesSet > dataSetsByName
On ARKit, a lookup of the image sets by name.
bool hadAnyTargets
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
readonly List< TrackableFoundEventHandler > targets = new List<TrackableFoundEventHandler>()
All of the targets in the system.
bool wasTracking
The value of Tracking from the previous frame, to detect changes.
bool done
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
CameraClearFlags clearFags
The clear flags as they were set before the AR Tracker was enabled. Used to restore the value if the AR Tracker is disabled.
Detailed Description
Definition at line 19 of file TrackerKeeper.cs.
Member Function Documentation
EnableDataSet()
void Juniper.XR.TrackerKeeper.EnableDataSet (string dataSetName) inline private
On Vuforia, enables a specific set of data, either image targets, object targets, or scanned model targets.
Parameters
dataSetName Data set name.
Definition at line 386 of file TrackerKeeper.cs.
         {
             if (dataSetName != null)
             {
                 var dataSets = tracker.GetActiveDataSets();
                 foreach (var ds in dataSets)
                 {
                     tracker.DeactivateDataSet(ds);
                 }
                 LoadDataSet(dataSetName);
             }
         }
References Juniper.XR.TrackerKeeper.LoadDataSet(), and Juniper.XR.TrackerKeeper.tracker.
Referenced by Juniper.XR.TrackerKeeper.StartTrackerCoroutine().
EnablePETCoroutine()
IEnumerator Juniper.XR.TrackerKeeper.EnablePETCoroutine () inline private
Handles marking a target as found, and optionally enables Vuforia's Persistent Extended Tracking.
Returns
The coroutine.
Definition at line 444 of file TrackerKeeper.cs.
         {
             if (VuforiaUnityExt.HasPET && usePET && !usingPET)
             {
                 yield return WaitForTracker;
                 ResetPET();
                 usingPET = true;
             }
         }
References Vuforia.VuforiaUnityExt.HasPET, Juniper.XR.TrackerKeeper.ResetPET(), Juniper.XR.TrackerKeeper.usePET, Juniper.XR.TrackerKeeper.usingPET, and Juniper.XR.TrackerKeeper.WaitForTracker.
Referenced by Juniper.XR.TrackerKeeper.ResetPET().
LoadDataSet()
void Juniper.XR.TrackerKeeper.LoadDataSet (string dataSetName) inline
Loads a set of Vuforia markers from disk and activates it at runtime.
Parameters
dataSetName Data set name.
Definition at line 404 of file TrackerKeeper.cs.
         {
             if (tracker != null && !string.IsNullOrEmpty(dataSetName))
             {
                 var dataSets = tracker.GetActiveDataSets();
                 var targetPath = Path.Combine("Vuforia", dataSetName + ".xml");
                 var dataSet = dataSets.FirstOrDefault(ds =>
                     ds.Path == targetPath);
                 if (dataSet == null)
                 {
                     dataSet = tracker.CreateDataSet();
                     dataSet.Load(dataSetName);
                     tracker.ActivateDataSet(dataSet);
                 }
             }
         }
References Juniper.XR.TrackerKeeper.tracker.
Referenced by Juniper.XR.TrackerKeeper.EnableDataSet().
OnAllTargetsLost()
void Juniper.XR.TrackerKeeper.OnAllTargetsLost () inline private
Triggers the onAllTargetsLost event.
Definition at line 694 of file TrackerKeeper.cs.
         {
             if (Tracking)
             {
                 onAllTargetsLost?.Invoke();
             }
         }
References Juniper.XR.TrackerKeeper.onAllTargetsLost, and Juniper.XR.TrackerKeeper.Tracking.
Referenced by Juniper.XR.TrackerKeeper.Update().
OnDestroy()
void Juniper.XR.TrackerKeeper.OnDestroy ()
Tears down the tracker keeper.
PrintDebugReport()
void Juniper.XR.TrackerKeeper.PrintDebugReport () inline private
If DebugReport is set to true, prints a report on the status of tracking.
Definition at line 822 of file TrackerKeeper.cs.
         {
 #if VUFORIA
             ScreenDebugger.Print(tracker == null ? "No tracker" : "Has tracker");
             ScreenDebugger.Print(usingPET ? "Using PET" : "Not using PET");
 #endif
         }
References ScreenDebugger.Print(), Juniper.XR.TrackerKeeper.tracker, and Juniper.XR.TrackerKeeper.usingPET.
Referenced by Juniper.XR.TrackerKeeper.Update().
Register()
TrackableFoundEventHandler Juniper.XR.TrackerKeeper.Register (TrackableFoundEventHandler target) inline
Register's a target and its events for the aggregated events issued by TrackerKeeper.
Parameters
target Target.
Definition at line 233 of file TrackerKeeper.cs.
         {
             if (targets?.Contains(target) == false)
             {
                 targets.Add(target);
                 target.onFound.AddListener(TargetFinder(target));
                 target.onLost.AddListener(TargetLoser(target));
                 target.onProximity.AddListener(TargetProximity(target));
                 target.onSafe.AddListener(TargetSafe(target));
             }
             return target;
         }
References Juniper.XR.TrackableFoundEventHandler.onFound, Juniper.XR.TrackableFoundEventHandler.onLost, Juniper.XR.TrackableFoundEventHandler.onProximity, Juniper.XR.TrackableFoundEventHandler.onSafe, Juniper.XR.TrackerKeeper.TargetFinder(), Juniper.XR.TrackerKeeper.TargetLoser(), Juniper.XR.TrackerKeeper.TargetProximity(), Juniper.XR.TrackerKeeper.targets, and Juniper.XR.TrackerKeeper.TargetSafe().
Referenced by Juniper.XR.TrackerKeeper.Start().
Reset()
void Juniper.XR.TrackerKeeper.Reset () inline
Stop object tracking while in picker
Definition at line 806 of file TrackerKeeper.cs.
         {
             onTrackingStopping?.Invoke();
 #if VUFORIA
             StopTracking();
 #else
             Tracking = false;
 #endif
             Update();
         }
References Juniper.XR.TrackerKeeper.onTrackingStopping, Juniper.XR.TrackerKeeper.StopTracking(), Juniper.XR.TrackerKeeper.Tracking, and Juniper.XR.TrackerKeeper.Update().
ResetPET()
void Juniper.XR.TrackerKeeper.ResetPET () inline
On Vuforia, resets the Persistent Extended Tracking, or starts it if it hasn't already been running.
Definition at line 458 of file TrackerKeeper.cs.
         {
             if (usingPET && tracker != null)
             {
                 tracker.Stop();
                 tracker.Start();
             }
             else
             {
                 StartCoroutine(EnablePETCoroutine());
             }
         }
References Juniper.XR.TrackerKeeper.EnablePETCoroutine(), Juniper.XR.TrackerKeeper.tracker, and Juniper.XR.TrackerKeeper.usingPET.
Referenced by Juniper.XR.TrackerKeeper.EnablePETCoroutine(), and Juniper.XR.TrackerKeeper.StopTracking().
Start() [1/2]
void Juniper.XR.TrackerKeeper.Start () inline private
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
Definition at line 188 of file TrackerKeeper.cs.
         {
 #if VUFORIA && UNITY_ANDROID
             manageVuforiaFrameRate = true;
 #endif
             var firstTargets = this.FindAll<TrackableFoundEventHandler>()
 #if VUFORIA
                 .Union(from m in this.FindAll<ModelTargetBehaviour>()
                        select m.EnsureComponent<TrackableFoundEventHandler>().Value)
                 .Union(from m in this.FindAll<ImageTargetBehaviour>()
                        select m.EnsureComponent<TrackableFoundEventHandler>().Value)
                 .Union(from m in this.FindAll<ObjectTargetBehaviour>()
                        select m.EnsureComponent<TrackableFoundEventHandler>().Value)
 #endif
                 .Distinct()
                 .ToList();
             foreach (var target in firstTargets)
             {
                 Register(target);
             }
 #if ARKIT
             targetsByName = targets.ToDictionary(target =>
                 target.image.imageName);
             dataSetsByName = targets.Select(target =>
                 target.imagesSet)
                                     .Distinct()
                                     .ToDictionary(set =>
                                         set.resourceGroupName);
             ScreenDebugger.Print("Found {0} targets: {1}", targets.Length, string.Join(", ", targetsByName.Keys.ToArray()));
             ScreenDebugger.Print("Found {0} data sets: {1}", dataSetsByName.Count, string.Join(", ", dataSetsByName.Keys.ToArray()));
             UnityARSessionNativeInterface.ARImageAnchorAddedEvent += UnityARSessionNativeInterface_ARImageAnchorAddedEvent;
             UnityARSessionNativeInterface.ARImageAnchorUpdatedEvent += UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent;
             UnityARSessionNativeInterface.ARImageAnchorRemovedEvent += UnityARSessionNativeInterface_ARImageAnchorRemovedEvent;
 #endif
         }
References Juniper.XR.TrackerKeeper.dataSetsByName, Juniper.XR.TrackerKeeper.manageVuforiaFrameRate, ScreenDebugger.Print(), Juniper.XR.TrackerKeeper.Register(), Juniper.XR.TrackerKeeper.targets, Juniper.XR.TrackerKeeper.targetsByName, Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorAddedEvent(), Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorRemovedEvent(), and Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent().
Start() [2/2]
void Juniper.XR.TrackerKeeper.Start () inline private
Once all of the camera setup has finished, we can check to see if we can start a tracker data set.
Definition at line 555 of file TrackerKeeper.cs.
         {
             if (dataSetsByName.Count == 1)
             {
                 StartTracker(dataSetsByName.Keys.First());
             }
         }
References Juniper.XR.TrackerKeeper.dataSetsByName, and Juniper.XR.TrackerKeeper.StartTracker().
StartTracker()
void Juniper.XR.TrackerKeeper.StartTracker ()
Starts the tracker without changing any dataset data that has already been configured.
Referenced by Juniper.XR.TrackerKeeper.Start().
StartTrackerCoroutine()
IEnumerator Juniper.XR.TrackerKeeper.StartTrackerCoroutine (string dataSetName, string targetName) inline private
Initializes tracking of a specific target.
Returns
The tracker coroutine.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 490 of file TrackerKeeper.cs.
         {
             if (!VuforiaConfiguration.Instance.Vuforia.DelayedInitialization)
             {
                 VuforiaBehaviour.Instance.enabled = true;
                 yield return WaitForNotInitializing;
             }
             else
             {
                 VuforiaConfiguration.Instance.Vuforia.DelayedInitialization = false;
                 for (int i = 1; i <= VUFORIA_INIT_ATTEMPTS && VuforiaRuntime.Instance.InitializationState != VuforiaRuntime.InitState.INITIALIZED; ++i)
                 {
                     if (i > 1)
                     {
                         Debug.LogFormat("Initializating Vuforia failed. Retrying ({0} of {1})", i, VUFORIA_INIT_ATTEMPTS);
                         VuforiaRuntime.Instance.Deinit();
                     }
                     else
                     {
                         Debug.LogFormat("Initializing Vuforia ({0} of {1})", i, VUFORIA_INIT_ATTEMPTS);
                     }
                     if (VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.NOT_INITIALIZED)
                     {
                         VuforiaRuntime.Instance.InitVuforia();
                         VuforiaBehaviour.Instance.enabled = true;
                     }
                     yield return WaitForNotInitializing;
                 }
             }
             if (VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.INITIALIZED)
             {
                 yield return WaitForTracker;
                 if (tracker.IsActive)
                 {
                     tracker.Stop();
                     yield return new WaitUntil(() => !tracker.IsActive);
                 }
                 EnableDataSet(dataSetName);
                 if (!tracker.IsActive)
                 {
                     tracker.Start();
                     yield return new WaitUntil(() =>
                         tracker.IsActive);
                 }
             }
             else
             {
                 Debug.LogError("Failed to initialize Vuforia.");
             }
         }
References Juniper.XR.Debug, Juniper.XR.TrackerKeeper.EnableDataSet(), Juniper.XR.TrackerKeeper.tracker, Juniper.XR.TrackerKeeper.VUFORIA_INIT_ATTEMPTS, Juniper.XR.TrackerKeeper.WaitForNotInitializing, and Juniper.XR.TrackerKeeper.WaitForTracker.
Referenced by Juniper.XR.TrackerKeeper.StartTrackerWithDataSetForTarget().
StartTrackerDelayed()
void Juniper.XR.TrackerKeeper.StartTrackerDelayed () private
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
StartTrackerWithDataSet()
void Juniper.XR.TrackerKeeper.StartTrackerWithDataSet (string dataSetName) inline
Initializes tracking of a set of targets.
Parameters
dataSetName Data set name.
Definition at line 758 of file TrackerKeeper.cs.
         {
             ScreenDebugger.Print("Activating data set: {0}", dataSetName);
             StartTrackerWithDataSetForTarget(dataSetName, null);
         }
References ScreenDebugger.Print(), and Juniper.XR.TrackerKeeper.StartTrackerWithDataSetForTarget().
StartTrackerWithDataSetForTarget()
void Juniper.XR.TrackerKeeper.StartTrackerWithDataSetForTarget (string dataSetName, string targetName) inline
Initializes tracking of a specific target.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 769 of file TrackerKeeper.cs.
         {
             onTrackingStarting?.Invoke();
             var keyboard = this.FindAny<RunningMovement>();
             if (keyboard != null)
             {
                 keyboard.Destroy();
             }
 #if VUFORIA
             StartCoroutine(StartTrackerCoroutine(dataSetName, targetName));
 #elif ARKIT
             if (dataSetsByName.ContainsKey(dataSetName))
             {
                 var dataSet = dataSetsByName[dataSetName];
                 var camMgr = this.FindAny<UnityARCameraManager>();
                 if (camMgr == null)
                 {
                     Debug.LogError("No Unity AR Camera Manager!");
                 }
                 else
                 {
                     camMgr.detectionImages = dataSet;
                 }
                 tracking = true;
             }
 #endif
             Update();
         }
References Juniper.XR.TrackerKeeper.dataSetsByName, Juniper.XR.Debug, Juniper.XR.TrackerKeeper.onTrackingStarting, Juniper.XR.TrackerKeeper.StartTrackerCoroutine(), and Juniper.XR.TrackerKeeper.Update().
Referenced by Juniper.XR.TrackerKeeper.StartTrackerWithDataSet().
StopTracking()
void Juniper.XR.TrackerKeeper.StopTracking () inline private
Cancel tracking and disable Vuforia. This also forces the Lost event on all of the currently tracked targets.
Definition at line 346 of file TrackerKeeper.cs.
         {
             if (targets != null)
             {
                 foreach (var target in targets)
                 {
                     var modelBehaviour = target.GetComponent<ModelTargetBehaviour>();
                     if (modelBehaviour != null)
                     {
                         modelBehaviour.enabled = false;
                     }
                 }
             }
             ResetPET();
             if (tracker != null && tracker.IsActive)
             {
                 tracker.Stop();
             }
             if (Tracking)
             {
                 VuforiaBehaviour.Instance.enabled = false;
             }
             if (targets != null)
             {
                 foreach (var target in targets)
                 {
                     target.ForceLost();
                 }
             }
         }
References Juniper.XR.TrackerKeeper.ResetPET(), Juniper.XR.TrackerKeeper.targets, Juniper.XR.TrackerKeeper.tracker, and Juniper.XR.TrackerKeeper.Tracking.
Referenced by Juniper.XR.TrackerKeeper.Reset(), and Juniper.XR.TrackerKeeper.Update().
TargetFinder()
UnityAction Juniper.XR.TrackerKeeper.TargetFinder (TrackableFoundEventHandler target) private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Referenced by Juniper.XR.TrackerKeeper.Register().
TargetLoser()
UnityAction Juniper.XR.TrackerKeeper.TargetLoser (TrackableFoundEventHandler target) private
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
Returns
The loser.
Parameters
target Target.
Referenced by Juniper.XR.TrackerKeeper.Register().
TargetProximity()
UnityAction Juniper.XR.TrackerKeeper.TargetProximity (TrackableFoundEventHandler target) private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Referenced by Juniper.XR.TrackerKeeper.Register().
TargetSafe()
UnityAction Juniper.XR.TrackerKeeper.TargetSafe (TrackableFoundEventHandler target) private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Referenced by Juniper.XR.TrackerKeeper.Register().
UnityARSessionNativeInterface_ARImageAnchorAddedEvent()
void Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorAddedEvent (ARImageAnchor anchorData) inline private
An event handler for the first time an image is found by ARKit.
Parameters
anchorData Anchor data.
Definition at line 595 of file TrackerKeeper.cs.
         {
             WithTarget("Added", anchorData, target =>
                 target.ForceFound());
         }
References Juniper.XR.TrackerKeeper.WithTarget().
Referenced by Juniper.XR.TrackerKeeper.Start().
UnityARSessionNativeInterface_ARImageAnchorRemovedEvent()
void Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorRemovedEvent (ARImageAnchor anchorData) inline private
An event handler that executes when ARKit loses track of an image.
Parameters
anchorData Anchor data.
Definition at line 614 of file TrackerKeeper.cs.
         {
             WithTarget("Removed", anchorData, target =>
                 target.ForceLost());
         }
References Juniper.XR.TrackerKeeper.WithTarget().
Referenced by Juniper.XR.TrackerKeeper.Start().
UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent()
void Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent (ARImageAnchor anchorData) inline private
An event handler that executes every time ARKit updates its understanding of an image.
Parameters
anchorData Anchor data.
Definition at line 605 of file TrackerKeeper.cs.
         {
             WithTarget("Updated", anchorData);
         }
References Juniper.XR.TrackerKeeper.WithTarget().
Referenced by Juniper.XR.TrackerKeeper.Start().
Update()
void Juniper.XR.TrackerKeeper.Update () inline
Checks the current tracking status and fires the events to indicate any change in the tracking status.
Definition at line 251 of file TrackerKeeper.cs.
         {
 #if VUFORIA
             bool cameraRendering = VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.INITIALIZED
                 && VuforiaBehaviour.Instance.enabled
                 && VuforiaRenderer.Instance.VideoBackgroundTexture != null;
             Tracking = cameraRendering
                  && numUpdates > Application.targetFrameRate
                  && tracker != null
                  && tracker.IsActive;
             if (cameraRendering)
             {
                 ++numUpdates;
             }
 #endif
             if (Tracking && !wasTracking)
             {
                 clearFags = CameraExtensions.MainCamera.clearFlags;
                 CameraExtensions.MainCamera.clearFlags = CameraClearFlags.SolidColor;
                 CameraExtensions.MainCamera.backgroundColor = Color.black;
 #if VUFORIA
                 if (manageVuforiaFrameRate)
                 {
                     Application.targetFrameRate = 30;
                 }
                 if (firstTime)
                 {
                     firstTime = false;
                     StopTracking();
                     if (tracker != null)
                     {
                         tracker.Start();
                     }
                     VuforiaBehaviour.Instance.enabled = true;
                 }
 #endif
                 onTrackingStarted?.Invoke();
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         target.onFound?.Invoke();
                         if (!target.Safe)
{
                             target.onProximity?.Invoke();
                         }
                     }
                 }
                 if (targets.All(target => !target.Found))
                 {
                     OnAllTargetsLost();
                 }
             }
             else if (!Tracking && wasTracking)
             {
                 onTrackingStopped?.Invoke();
 #if VUFORIA
                 if (manageVuforiaFrameRate)
                 {
                     Application.targetFrameRate = 60;
                 }
                 numUpdates = 0;
 #endif
                 CameraExtensions.MainCamera.clearFlags = clearFags;
             }
             wasTracking = Tracking;
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.XR.TrackerKeeper.clearFags, Juniper.XR.TrackerKeeper.DebugReport, Juniper.XR.TrackerKeeper.firstTime, Juniper.CameraExtensions.MainCamera, Juniper.XR.TrackerKeeper.manageVuforiaFrameRate, Juniper.XR.TrackerKeeper.numUpdates, Juniper.XR.TrackerKeeper.OnAllTargetsLost(), Juniper.XR.TrackerKeeper.onTrackingStarted, Juniper.XR.TrackerKeeper.onTrackingStopped, Juniper.XR.TrackerKeeper.PrintDebugReport(), Juniper.XR.TrackerKeeper.StopTracking(), Juniper.XR.TrackerKeeper.targets, Juniper.XR.TrackerKeeper.tracker, Juniper.XR.TrackerKeeper.Tracking, and Juniper.XR.TrackerKeeper.wasTracking.
Referenced by Juniper.XR.TrackerKeeper.Reset(), and Juniper.XR.TrackerKeeper.StartTrackerWithDataSetForTarget().
WithTarget()
void Juniper.XR.TrackerKeeper.WithTarget (string label, ARImageAnchor anchorData, Action< TrackableFoundEventHandler > act = null) inline private
Finds a target object by name and updates its state.
Parameters
label A label to aid in debugging.
anchorData Anchor data.
act The action to perform once the target is found.
Definition at line 569 of file TrackerKeeper.cs.
         {
             ScreenDebugger.Print("{0} {1} [{2}]", label, anchorData.referenceImageName, tracking ? "tracking" : "not tracking");
             if (tracking)
             {
                 var targetName = anchorData.referenceImageName;
                 if (targetsByName.ContainsKey(targetName))
                 {
                     var target = targetsByName[targetName];
                     act?.Invoke(target);
                     target.transform.position = UnityARMatrixOps.GetPosition(anchorData.transform);
                     target.transform.rotation = UnityARMatrixOps.GetRotation(anchorData.transform);
                 }
                 else
                 {
                     ScreenDebugger.Print("Couldn't find {0}", targetName);
                     ScreenDebugger.Print("Names we recognize: {0}", string.Join(", ", targetsByName.Keys.ToArray()));
                 }
             }
         }
References ScreenDebugger.Print(), and Juniper.XR.TrackerKeeper.targetsByName.
Referenced by Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorAddedEvent(), Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorRemovedEvent(), and Juniper.XR.TrackerKeeper.UnityARSessionNativeInterface_ARImageAnchorUpdatedEvent().
Member Data Documentation
clearFags
CameraClearFlags Juniper.XR.TrackerKeeper.clearFags private
The clear flags as they were set before the AR Tracker was enabled. Used to restore the value if the AR Tracker is disabled.
Definition at line 182 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Update().
dataSetsByName
Dictionary<string, ARReferenceImagesSet> Juniper.XR.TrackerKeeper.dataSetsByName private
On ARKit, a lookup of the image sets by name.
Definition at line 74 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Start(), and Juniper.XR.TrackerKeeper.StartTrackerWithDataSetForTarget().
DebugReport
bool Juniper.XR.TrackerKeeper.DebugReport
Set to true to print out a debug report on the screen.
Definition at line 101 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Update().
done
bool Juniper.XR.TrackerKeeper.done private
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
Definition at line 106 of file TrackerKeeper.cs.
firstTime
bool Juniper.XR.TrackerKeeper.firstTime = true private
Used for reseting Vuforia's tracker the first time the application is started.
Definition at line 40 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Update().
hadAnyTargets
bool Juniper.XR.TrackerKeeper.hadAnyTargets private
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
Definition at line 81 of file TrackerKeeper.cs.
manageVuforiaFrameRate
bool Juniper.XR.TrackerKeeper.manageVuforiaFrameRate = true
Set to true to set the target framerate lower than normal when the tracker is active.
Definition at line 47 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Start(), and Juniper.XR.TrackerKeeper.Update().
numUpdates
int Juniper.XR.TrackerKeeper.numUpdates = 0 private
The number updates to the AR Background Image texture since tracking started. This value is used to delay switching from camera initialization to the app until after we are sure the camera is really ready.
Definition at line 62 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Update().
onAllTargetsLost
UnityEvent Juniper.XR.TrackerKeeper.onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
Definition at line 166 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.OnAllTargetsLost().
onAnyTargetFound
UnityEvent Juniper.XR.TrackerKeeper.onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
Definition at line 150 of file TrackerKeeper.cs.
onTargetFound
TransformEvent Juniper.XR.TrackerKeeper.onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
Definition at line 155 of file TrackerKeeper.cs.
onTargetLost
TransformEvent Juniper.XR.TrackerKeeper.onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
Definition at line 160 of file TrackerKeeper.cs.
onTargetProximity
TransformEvent Juniper.XR.TrackerKeeper.onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Definition at line 176 of file TrackerKeeper.cs.
onTargetSafe
TransformEvent Juniper.XR.TrackerKeeper.onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
Definition at line 171 of file TrackerKeeper.cs.
onTrackingStarted
UnityEvent Juniper.XR.TrackerKeeper.onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
Definition at line 134 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Update().
onTrackingStarting
UnityEvent Juniper.XR.TrackerKeeper.onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
Definition at line 129 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.StartTrackerWithDataSetForTarget().
onTrackingStopped
UnityEvent Juniper.XR.TrackerKeeper.onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
Definition at line 144 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Update().
onTrackingStopping
UnityEvent Juniper.XR.TrackerKeeper.onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
Definition at line 139 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Reset().
targets
readonly List<TrackableFoundEventHandler> Juniper.XR.TrackerKeeper.targets = new List<TrackableFoundEventHandler>() private
All of the targets in the system.
Definition at line 86 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Register(), Juniper.XR.TrackerKeeper.Start(), Juniper.XR.TrackerKeeper.StopTracking(), and Juniper.XR.TrackerKeeper.Update().
targetsByName
Dictionary<string, TrackableFoundEventHandler> Juniper.XR.TrackerKeeper.targetsByName private
On ARKit, a lookup of targets by name.
Definition at line 69 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Start(), and Juniper.XR.TrackerKeeper.WithTarget().
tracker
ObjectTracker Juniper.XR.TrackerKeeper.tracker private
The Vuforia Tracker API.
Definition at line 30 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.EnableDataSet(), Juniper.XR.TrackerKeeper.LoadDataSet(), Juniper.XR.TrackerKeeper.PrintDebugReport(), Juniper.XR.TrackerKeeper.ResetPET(), Juniper.XR.TrackerKeeper.StartTrackerCoroutine(), Juniper.XR.TrackerKeeper.StopTracking(), and Juniper.XR.TrackerKeeper.Update().
usePET
bool Juniper.XR.TrackerKeeper.usePET
Set to true to enable using Vuforia's Persistent Extended Tracking.
Definition at line 35 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.EnablePETCoroutine().
usingPET
bool Juniper.XR.TrackerKeeper.usingPET private
Is set to true when Persistent Extended Tracking is active.
Definition at line 55 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.EnablePETCoroutine(), Juniper.XR.TrackerKeeper.PrintDebugReport(), and Juniper.XR.TrackerKeeper.ResetPET().
VUFORIA_INIT_ATTEMPTS
const int Juniper.XR.TrackerKeeper.VUFORIA_INIT_ATTEMPTS = 3 private
The number of times to attempt initializing Vuforia before just giving up.
Definition at line 25 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.StartTrackerCoroutine().
wasTracking
bool Juniper.XR.TrackerKeeper.wasTracking private
The value of Tracking from the previous frame, to detect changes.
Definition at line 96 of file TrackerKeeper.cs.
Referenced by Juniper.XR.TrackerKeeper.Update().
Property Documentation
HasTargets
bool Juniper.XR.TrackerKeeper.HasTargets get
Returns true when there are any GoodTargets.
true if has targets; otherwise, false.
Definition at line 707 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Safe
bool Juniper.XR.TrackerKeeper.Safe get
This value is set to true when the user is at a safe distance from the target.
Definition at line 725 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found && !target.Safe)
                     {
                         return false;
                     }
                 }
                 return true;
             }
         }
TargetFound
bool Juniper.XR.TrackerKeeper.TargetFound get
Returns true when any target has been found and is tracking.
Definition at line 112 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Tracking
bool Juniper.XR.TrackerKeeper.Tracking get private set
Is set to true when the tracking system is initialized and running.
Definition at line 91 of file TrackerKeeper.cs.
 { get; private set; }
Referenced by Juniper.XR.TrackerKeeper.OnAllTargetsLost(), Juniper.XR.TrackerKeeper.Reset(), Juniper.XR.TrackerKeeper.StopTracking(), and Juniper.XR.TrackerKeeper.Update().
WaitForNotInitializing
WaitUntil Juniper.XR.TrackerKeeper.WaitForNotInitializing get private
What for Vuforia's initialization state to no longer be "INITIALIZING".
The wait for not initializing.
Definition at line 476 of file TrackerKeeper.cs.
         {
             get
             {
                 return new WaitUntil(() =>
                     VuforiaRuntime.Instance.InitializationState != VuforiaRuntime.InitState.INITIALIZING);
             }
         }
Referenced by Juniper.XR.TrackerKeeper.StartTrackerCoroutine().
WaitForTracker
IEnumerator Juniper.XR.TrackerKeeper.WaitForTracker get private
A coroutine that waits for a Vuforia ObjectTracker to become available.
The wait for tracker.
Definition at line 426 of file TrackerKeeper.cs.
         {
             get
             {
                 return new WaitUntil(() =>
                 {
                     if (tracker == null)
                     {
                         tracker = TrackerManager.Instance.GetTracker<ObjectTracker>();
                     }
                     return tracker != null;
                 });
             }
         }
Referenced by Juniper.XR.TrackerKeeper.EnablePETCoroutine(), and Juniper.XR.TrackerKeeper.StartTrackerCoroutine().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/XR/TrackerKeeper.cs