Juniper: Juniper.Units.EquitorialSpherical Class Reference
Juniper.Units.EquitorialSpherical Class Reference
Static Public Member Functions
static HorizontalSphericalPosition ToHorizontal (this EquitorialSphericalPosition value, LatLngPoint location, float n)
Convert Equitorial Spherical Position to Horizontal Spherical Position.
Detailed Description
Definition at line 9 of file EquitorialSpherical.cs.
Member Function Documentation
ToHorizontal()
static HorizontalSphericalPosition Juniper.Units.EquitorialSpherical.ToHorizontal (this EquitorialSphericalPosition value, LatLngPoint location, float n) inline static
Convert Equitorial Spherical Position to Horizontal Spherical Position.
Parameters
location The point on earth
n The Julian day
Returns
The elevation above the horizon
Definition at line 17 of file EquitorialSpherical.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             if (location is null)
             {
                 throw new ArgumentNullException(nameof(location));
             }
             var GMST = (18.697374558f + (24.06570982441908f * n)).Repeat(24);
             var LST = GMST + Degrees.Hours(location.Longitude);
             var RA = Degrees.Hours(value.RightAscensionDegrees);
             var H = Hours.Radians(LST - RA);
             var sin_H = Sin(H);
             var cos_H = Cos(H);
             var lat_rad = Degrees.Radians(location.Latitude);
             // var lng_rad = lng_deg * Deg2Rad;
             var delta_rad = Degrees.Radians(value.DeclinationDegrees);
             var sin_delta = Sin(delta_rad);
             var cos_delta = Cos(delta_rad);
             var sin_lat = Sin(lat_rad);
             var cos_lat = Cos(lat_rad);
             var sin_alt = (sin_delta * sin_lat) + (cos_delta * cos_lat * cos_H);
             var cos_alt = Sqrt(1 - (sin_alt * sin_alt));
             var sin_azm = sin_H * cos_delta / cos_alt;
             var cos_azm = (sin_delta - (sin_lat * sin_alt)) / (cos_lat * cos_alt);
             var altitude_rad = (float)Atan2(sin_alt, cos_alt);
             var azimuth_rad = (float)Atan2(sin_azm, cos_azm);
             return new HorizontalSphericalPosition(
                 Radians.Degrees(altitude_rad),
                 (180 - Radians.Degrees(azimuth_rad)).Repeat(360),
                 value.RadiusAU);
         }
References Juniper.World.GIS.EquitorialSphericalPosition.DeclinationDegrees, Juniper.Units.Radians.Degrees(), Juniper.Units.Degrees.Hours(), Juniper.World.GIS.LatLngPoint.Latitude, Juniper.World.GIS.LatLngPoint.Longitude, Juniper.Units.Degrees.Radians(), Juniper.Units.Hours.Radians(), Juniper.World.GIS.EquitorialSphericalPosition.RadiusAU, and Juniper.World.GIS.EquitorialSphericalPosition.RightAscensionDegrees.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/World/GIS/EquitorialSpherical.cs