Juniper: Juniper.Unity.ImageTracking.AbstractTrackerKeeper Class Reference
Juniper.Unity.ImageTracking.AbstractTrackerKeeper Class Reference
Public Member Functions
AbstractTrackableFoundEventHandler Register (AbstractTrackableFoundEventHandler target)
Register's a target and its events for the aggregated events issued by TrackerKeeper.
virtual void Update ()
Checks the current tracking status and fires the events to indicate any change in the tracking status.
void OnDestroy ()
Tears down the tracker keeper.
void StartTracker ()
Starts the tracker without changing any dataset data that has already been configured.
void StartTrackerWithDataSet (string dataSetName)
Initializes tracking of a set of targets.
void StartTrackerWithDataSetForTarget (string dataSetName, string targetName)
Initializes tracking of a specific target.
void Reset ()
Stop object tracking while in picker
Public Attributes
bool DebugReport
Set to true to print out a debug report on the screen.
UnityEvent onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
UnityEvent onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
UnityEvent onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
UnityEvent onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
UnityEvent onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
TransformEvent onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
TransformEvent onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
UnityEvent onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
TransformEvent onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
TransformEvent onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Protected Member Functions
virtual void Start ()
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
virtual void OnTrackingStarting (string dataSetName, string targetName)
virtual void OnTrackingStarted ()
virtual void OnTrackingStopping ()
virtual void OnTrackingStopped ()
virtual void PrintDebugReport ()
Protected Attributes
readonly List< AbstractTrackableFoundEventHandler > targets = new List<AbstractTrackableFoundEventHandler>()
All of the targets in the system.
Properties
bool Tracking [get, protected set]
Is set to true when the tracking system is initialized and running.
bool TargetFound [get]
Returns true when any target has been found and is tracking.
virtual IEnumerable< TrackableFoundEventHandler > FirstTargets [get]
bool HasTargets [get]
Returns true when there are any GoodTargets.
bool Safe [get]
This value is set to true when the user is at a safe distance from the target.
Private Member Functions
UnityAction TargetFinder (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetProximity (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetSafe (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetLoser (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
void OnAllTargetsLost ()
Triggers the onAllTargetsLost event.
void StartTrackerDelayed ()
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
Private Attributes
bool hadAnyTargets
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
bool wasTracking
The value of Tracking from the previous frame, to detect changes.
bool done
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
DisplayManager xr
Detailed Description
Definition at line 12 of file AbstractTrackerKeeper.cs.
Member Function Documentation
OnAllTargetsLost()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost () inline private
Triggers the onAllTargetsLost event.
Definition at line 314 of file AbstractTrackerKeeper.cs.
         {
             if (Tracking)
             {
                 onAllTargetsLost?.Invoke();
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onAllTargetsLost, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
OnDestroy()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnDestroy () inline
Tears down the tracker keeper.
Definition at line 230 of file AbstractTrackerKeeper.cs.
         {
             done = true;
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.done.
OnTrackingStarted()
virtual void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarted () inline protected virtual
Reimplemented in Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.
Definition at line 165 of file AbstractTrackerKeeper.cs.
         {
             onTrackingStarted?.Invoke();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStarted.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
OnTrackingStarting()
virtual void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting (string dataSetName, string targetName) inline protected virtual
Reimplemented in Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.
Definition at line 160 of file AbstractTrackerKeeper.cs.
         {
             onTrackingStarting?.Invoke();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStarting.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
OnTrackingStopped()
virtual void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopped () inline protected virtual
Reimplemented in Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.
Definition at line 175 of file AbstractTrackerKeeper.cs.
         {
             onTrackingStopped?.Invoke();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStopped.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
OnTrackingStopping()
virtual void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopping () inline protected virtual
Reimplemented in Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.
Definition at line 170 of file AbstractTrackerKeeper.cs.
         {
             onTrackingStopping?.Invoke();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStopping.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Reset().
PrintDebugReport()
virtual void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.PrintDebugReport () inline protected virtual
Reimplemented in Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.
Definition at line 180 of file AbstractTrackerKeeper.cs.
         {
         }
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
Register()
AbstractTrackableFoundEventHandler Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register (AbstractTrackableFoundEventHandler target) inline
Register's a target and its events for the aggregated events issued by TrackerKeeper.
Parameters
target Target.
Definition at line 146 of file AbstractTrackerKeeper.cs.
         {
             if (targets?.Contains(target) == false)
             {
                 targets.Add(target);
                 target.onFound.AddListener(TargetFinder(target));
                 target.onLost.AddListener(TargetLoser(target));
                 target.onProximity.AddListener(TargetProximity(target));
                 target.onSafe.AddListener(TargetSafe(target));
             }
             return target;
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onFound, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onLost, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onProximity, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onSafe, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetProximity(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.targets, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetSafe().
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Awake(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Start().
Reset()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Reset () inline
Stop object tracking while in picker
Definition at line 404 of file AbstractTrackerKeeper.cs.
         {
             OnTrackingStopping();
             Tracking = false;
             Update();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopping(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
Start()
virtual void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Start () inline protected virtual
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
Reimplemented in Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.
Definition at line 132 of file AbstractTrackerKeeper.cs.
         {
             xr = ComponentExt.FindAny<DisplayManager>();
             foreach (var target in FirstTargets.Distinct())
             {
                 Register(target);
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.FirstTargets, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.xr.
StartTracker()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTracker () inline
Starts the tracker without changing any dataset data that has already been configured.
Definition at line 363 of file AbstractTrackerKeeper.cs.
         {
             Invoke(nameof(StartTrackerDelayed), 1);
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed().
StartTrackerDelayed()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed () inline private
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
Definition at line 373 of file AbstractTrackerKeeper.cs.
         {
             StartTrackerWithDataSetForTarget(null, null);
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTracker().
StartTrackerWithDataSet()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSet (string dataSetName) inline
Initializes tracking of a set of targets.
Parameters
dataSetName Data set name.
Definition at line 382 of file AbstractTrackerKeeper.cs.
         {
             ScreenDebugger.Print($"Activating data set: {dataSetName}");
             StartTrackerWithDataSetForTarget(dataSetName, null);
         }
References System.ScreenDebugger.Print(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
StartTrackerWithDataSetForTarget()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget (string dataSetName, string targetName) inline
Initializes tracking of a specific target.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 393 of file AbstractTrackerKeeper.cs.
         {
             OnTrackingStarting(dataSetName, targetName);
             Update();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSet().
TargetFinder()
UnityAction Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Definition at line 240 of file AbstractTrackerKeeper.cs.
         {
             return () =>
             {
                 CancelInvoke(nameof(OnAllTargetsLost));
                 if (HasTargets && !hadAnyTargets && Tracking)
                 {
                     onAnyTargetFound?.Invoke();
                 }
                 onTargetFound?.Invoke(target.transform);
                 foreach (var otherTarget in targets)
                 {
                     if (otherTarget != target && otherTarget.Found)
                     {
                         otherTarget.ForceLost();
                     }
                 }
                 hadAnyTargets = HasTargets;
             };
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.hadAnyTargets, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.HasTargets, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onAnyTargetFound, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetFound, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.targets, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
TargetLoser()
UnityAction Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
Returns
The loser.
Parameters
target Target.
Definition at line 294 of file AbstractTrackerKeeper.cs.
         {
             return () =>
             {
                 onTargetLost?.Invoke(target.transform);
                 if (!HasTargets && hadAnyTargets)
                 {
                     hadAnyTargets = HasTargets;
                     if (!done)
                     {
                         Invoke(nameof(OnAllTargetsLost), 1);
                     }
                 }
             };
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.done, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.hadAnyTargets, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.HasTargets, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetLost.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
TargetProximity()
UnityAction Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetProximity (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Definition at line 270 of file AbstractTrackerKeeper.cs.
         {
             return () => onTargetProximity.Invoke(target.transform);
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetProximity.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
TargetSafe()
UnityAction Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetSafe (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Definition at line 280 of file AbstractTrackerKeeper.cs.
         {
             return () => onTargetSafe.Invoke(target.transform);
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetSafe.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
Update()
virtual void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update () inline virtual
Checks the current tracking status and fires the events to indicate any change in the tracking status.
Reimplemented in Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.
Definition at line 188 of file AbstractTrackerKeeper.cs.
         {
             if (Tracking && !wasTracking)
             {
                 xr.StartAR();
                 OnTrackingStarted();
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         target.onFound?.Invoke();
                         if (!target.Safe)
{
                             target.onProximity?.Invoke();
                         }
                     }
                 }
                 if (targets.All(target => !target.Found))
                 {
                     OnAllTargetsLost();
                 }
             }
             else if (!Tracking && wasTracking)
             {
                 xr.StopAR();
                 OnTrackingStopped();
             }
             wasTracking = Tracking;
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.DebugReport, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarted(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopped(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.PrintDebugReport(), Juniper.Unity.Display.AbstractDisplayManager.StartAR(), Juniper.Unity.Display.AbstractDisplayManager.StopAR(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.targets, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.wasTracking, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.xr.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Reset(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
Member Data Documentation
DebugReport
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.DebugReport
Set to true to print out a debug report on the screen.
Definition at line 41 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
done
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.done private
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
Definition at line 46 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnDestroy(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser().
hadAnyTargets
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.hadAnyTargets private
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
Definition at line 18 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser().
onAllTargetsLost
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
Definition at line 106 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost().
onAnyTargetFound
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
Definition at line 90 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onTargetFound
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
Definition at line 95 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onTargetLost
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
Definition at line 100 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser().
onTargetProximity
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Definition at line 116 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetProximity().
onTargetSafe
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
Definition at line 111 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetSafe().
onTrackingStarted
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
Definition at line 74 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarted().
onTrackingStarting
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
Definition at line 69 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting().
onTrackingStopped
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
Definition at line 84 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopped().
onTrackingStopping
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
Definition at line 79 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopping().
targets
readonly List<AbstractTrackableFoundEventHandler> Juniper.Unity.ImageTracking.AbstractTrackerKeeper.targets = new List<AbstractTrackableFoundEventHandler>() protected
All of the targets in the system.
Definition at line 23 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
wasTracking
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.wasTracking private
The value of Tracking from the previous frame, to detect changes.
Definition at line 36 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
xr
DisplayManager Juniper.Unity.ImageTracking.AbstractTrackerKeeper.xr private
Definition at line 118 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Start(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
Property Documentation
FirstTargets
virtual IEnumerable<TrackableFoundEventHandler> Juniper.Unity.ImageTracking.AbstractTrackerKeeper.FirstTargets get protected
Definition at line 121 of file AbstractTrackerKeeper.cs.
         {
             get
             {
                 return ComponentExt.FindAll<TrackableFoundEventHandler>();
             }
         }
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Start().
HasTargets
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.HasTargets get
Returns true when there are any GoodTargets.
true if has targets; otherwise, false.
Definition at line 327 of file AbstractTrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser().
Safe
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Safe get
This value is set to true when the user is at a safe distance from the target.
Definition at line 345 of file AbstractTrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found && !target.Safe)
                     {
                         return false;
                     }
                 }
                 return true;
             }
         }
TargetFound
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFound get
Returns true when any target has been found and is tracking.
Definition at line 52 of file AbstractTrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Tracking
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking get protected set
Is set to true when the tracking system is initialized and running.
Definition at line 29 of file AbstractTrackerKeeper.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Reset(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.Update(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/ImageTracking/AbstractTrackerKeeper.cs