Juniper: Juniper.HTTP.Server.Administration.NetSH.DeleteSslCert Class Reference
Juniper.HTTP.Server.Administration.NetSH.DeleteSslCert Class Reference
Public Member Functions
DeleteSslCert (IPEndPoint endPoint)
DeleteSslCert (IPAddress address, int port)
DeleteSslCert (string address, int port)
Task< int > RunAsync ()
int Run ()
Protected Member Functions
virtual async Task< int > RunAsync (IEnumerable< string > arguments)
Static Protected Member Functions
static IPEndPoint ValidateAddress (IPAddress address, int port)
static IPAddress ValidateAddress (string address)
Properties
IPEndPoint EndPoint [get, set]
override IEnumerable< string > Arguments [get]
bool UseShellExecute [get, set]
bool LoadUserProfile [get, set]
Encoding Encoding [get, set]
string TotalStandardOutput [get, private set]
string TotalStandardError [get, private set]
Events
EventHandler< StringEventArgs > Info
EventHandler< StringEventArgs > Warning
EventHandler< ErrorEventArgs > Err
Detailed Description
Definition at line 5 of file DeleteSslCert.cs.
Constructor & Destructor Documentation
DeleteSslCert() [1/3]
Juniper.HTTP.Server.Administration.NetSH.DeleteSslCert.DeleteSslCert (IPEndPoint endPoint) inline
Definition at line 8 of file DeleteSslCert.cs.
             : base("delete", endPoint)
         { }
DeleteSslCert() [2/3]
Juniper.HTTP.Server.Administration.NetSH.DeleteSslCert.DeleteSslCert (IPAddress address, int port) inline
Definition at line 12 of file DeleteSslCert.cs.
             : this(ValidateAddress(address, port))
         { }
DeleteSslCert() [3/3]
Juniper.HTTP.Server.Administration.NetSH.DeleteSslCert.DeleteSslCert (string address, int port) inline
Definition at line 16 of file DeleteSslCert.cs.
             : this(ValidateAddress(address), port)
         { }
Member Function Documentation
Run()
int Juniper.Processes.AbstractShellCommand.Run () inline inherited
Definition at line 58 of file AbstractShellCommand.cs.
         {
             return RunAsync().Result;
         }
References Juniper.Processes.AbstractShellCommand.RunAsync().
RunAsync() [1/2]
Task<int> Juniper.Processes.AbstractShellCommand.RunAsync () inline inherited
Definition at line 52 of file AbstractShellCommand.cs.
         {
             return RunAsync(Arguments);
         }
References Juniper.Processes.AbstractShellCommand.Arguments.
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.ExistsAsync(), Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync(), and Juniper.Processes.AbstractShellCommand.Run().
RunAsync() [2/2]
virtual async Task<int> Juniper.Processes.AbstractShellCommand.RunAsync (IEnumerable< string > arguments) inline protected virtual inherited
Reimplemented in Juniper.HTTP.Server.Administration.NetSH.AddFirewallRule, Juniper.HTTP.Server.Administration.NetSH.DeleteFirewallRule, and Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.
Definition at line 67 of file AbstractShellCommand.cs.
         {
             TotalStandardOutput = string.Empty;
             TotalStandardError = string.Empty;
             using var proc = new Process()
             {
                 StartInfo = new ProcessStartInfo(command)
                 {
                     Arguments = arguments.ToArray().Join(' '),
                     UseShellExecute = UseShellExecute,
                     LoadUserProfile = LoadUserProfile,
                     StandardErrorEncoding = Encoding,
                     StandardOutputEncoding = Encoding,
                     ErrorDialog = false,
                     CreateNoWindow = true,
                     RedirectStandardError = true,
                     RedirectStandardInput = true,
                     RedirectStandardOutput = true,
                     WindowStyle = ProcessWindowStyle.Hidden
                 }
             };
 #if DEBUG
             LastCommand = $"{Environment.CurrentDirectory}> {proc.StartInfo.FileName} {proc.StartInfo.Arguments}";
 #endif
             var outputAccum = new StringBuilder();
             void Proc_AccumOutputData(object sender, DataReceivedEventArgs e) => _ = outputAccum.AppendLine(e.Data);
             var errorAccum = new StringBuilder();
             void Proc_AccumErrorData(object sender, DataReceivedEventArgs e) => _ = errorAccum.AppendLine(e.Data);
             proc.OutputDataReceived += Proc_AccumOutputData;
             proc.OutputDataReceived += Proc_OutputDataReceived;
             proc.ErrorDataReceived += Proc_AccumErrorData;
             proc.ErrorDataReceived += Proc_ErrorDataReceived;
             try
             {
                 if (!proc.Start())
                 {
                     throw new InvalidOperationException("Could not start process.");
                 }
             }
             catch (Exception exp)
             {
                 exp.Data.Add("ProcessStart", proc.StartInfo);
                 OnError(exp);
                 throw;
             }
             proc.BeginOutputReadLine();
             proc.BeginErrorReadLine();
             await Task.Run(proc.WaitForExit)
                 .ConfigureAwait(false);
             TotalStandardOutput = outputAccum.ToString();
             TotalStandardError = errorAccum.ToString();
             proc.ErrorDataReceived -= Proc_ErrorDataReceived;
             proc.OutputDataReceived -= Proc_OutputDataReceived;
             proc.ErrorDataReceived -= Proc_AccumErrorData;
             proc.OutputDataReceived -= Proc_AccumOutputData;
             return proc.ExitCode;
         }
References Juniper.Processes.AbstractShellCommand.Arguments, Juniper.Processes.AbstractShellCommand.command, Juniper.Processes.AbstractShellCommand.Encoding, Juniper.Processes.AbstractShellCommand.LoadUserProfile, Juniper.Processes.AbstractShellCommand.OnError(), Juniper.Processes.AbstractShellCommand.Proc_ErrorDataReceived(), Juniper.Processes.AbstractShellCommand.Proc_OutputDataReceived(), Juniper.Processes.AbstractShellCommand.TotalStandardError, Juniper.Processes.AbstractShellCommand.TotalStandardOutput, and Juniper.Processes.AbstractShellCommand.UseShellExecute.
ValidateAddress() [1/2]
static IPEndPoint Juniper.HTTP.Server.Administration.NetSH.AbstractSslCertCommand.ValidateAddress (IPAddress address, int port) inline static protected inherited
Definition at line 12 of file AbstractSslCertCommand.cs.
         {
             if (address is null)
             {
                 throw new ArgumentNullException(nameof(address));
             }
             return new IPEndPoint(address, port);
         }
ValidateAddress() [2/2]
static IPAddress Juniper.HTTP.Server.Administration.NetSH.AbstractSslCertCommand.ValidateAddress (string address) inline static protected inherited
Definition at line 22 of file AbstractSslCertCommand.cs.
         {
             if (address is null)
             {
                 throw new ArgumentNullException(nameof(address));
             }
             if (address.Length == 0)
             {
                 throw new InvalidOperationException($"{nameof(address)} cannot be an empty string");
             }
             return IPAddress.Parse(address);
         }
Property Documentation
Arguments
override IEnumerable<string> Juniper.HTTP.Server.Administration.NetSH.AbstractSslCertCommand.Arguments get protected inherited
Definition at line 66 of file AbstractSslCertCommand.cs.
         {
             get
             {
                 yield return "http";
                 yield return command;
                 yield return "sslcert";
                 yield return $"ipport={EndPoint}";
             }
         }
Encoding
Encoding Juniper.Processes.AbstractShellCommand.Encoding get set inherited
Definition at line 26 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
EndPoint
IPEndPoint Juniper.HTTP.Server.Administration.NetSH.AbstractSslCertCommand.EndPoint get set inherited
Definition at line 40 of file AbstractSslCertCommand.cs.
         {
             get
             {
                 return endPoint;
             }
             set
             {
                 if (value is null)
                 {
                     throw new ArgumentNullException(nameof(value));
                 }
                 endPoint = value;
             }
         }
LoadUserProfile
bool Juniper.Processes.AbstractShellCommand.LoadUserProfile get set inherited
Definition at line 24 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
TotalStandardError
string Juniper.Processes.AbstractShellCommand.TotalStandardError get private set inherited
Definition at line 30 of file AbstractShellCommand.cs.
 { get; private set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
TotalStandardOutput
string Juniper.Processes.AbstractShellCommand.TotalStandardOutput get private set inherited
Definition at line 28 of file AbstractShellCommand.cs.
 { get; private set; }
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync(), Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.RunAsync(), Juniper.Processes.AbstractShellCommand.RunAsync(), Juniper.HTTP.Server.Administration.NetSH.DeleteFirewallRule.RunAsync(), and Juniper.HTTP.Server.Administration.NetSH.AddFirewallRule.RunAsync().
UseShellExecute
bool Juniper.Processes.AbstractShellCommand.UseShellExecute get set inherited
Definition at line 22 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
Event Documentation
Err
EventHandler<ErrorEventArgs> Juniper.Processes.AbstractShellCommand.Err inherited
Definition at line 20 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnError().
Info
EventHandler<StringEventArgs> Juniper.Processes.AbstractShellCommand.Info inherited
Definition at line 18 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnInfo().
Warning
EventHandler<StringEventArgs> Juniper.Processes.AbstractShellCommand.Warning inherited
Definition at line 19 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnWarning().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Server/Administration/NetSH/DeleteSslCert.cs