Juniper: Juniper.Unity.Audio.StreamableAudioClip Class Reference
Juniper.Unity.Audio.StreamableAudioClip Class Reference
Public Member Functions
IEnumerator Load (Action< AudioClip > resolve, Action< Exception > reject, IProgress prog=null)
Detailed Description
Definition at line 16 of file StreamableAudioClip.cs.
Member Function Documentation
Load()
IEnumerator Juniper.Unity.Audio.StreamableAudioClip.Load (Action< AudioClip > resolve, Action< Exception > reject, IProgress prog = null) inline
Definition at line 18 of file StreamableAudioClip.cs.
         {
             var info = new FileInfo(LoadPath);
             var ext = info.Extension.ToLowerInvariant();
             string mime = null;
             Func<Stream, RawAudio> decoder;
             if (ext == ".mp3")
             {
                 mime = "audio/mpeg";
                 decoder = Decoder.DecodeMP3;
             }
             else if (ext == ".wav")
             {
                 mime = "audio/wav";
                 decoder = Decoder.DecodeWAV;
             }
             else if (ext == ".ogg")
             {
                 mime = "audio/ogg";
                 decoder = Decoder.DecodeVorbis;
             }
             else
             {
                 throw new InvalidOperationException($"{ext} is not a recognized audio format ({LoadPath}).");
             }
             var audioTask = StreamingAssets.GetStream(
                 Application.temporaryCachePath,
                 LoadPath,
                 mime,
                 prog);
             yield return new WaitUntil(() => audioTask.IsCanceled || audioTask.IsCompleted || audioTask.IsFaulted);
             var audio = decoder(audioTask.Result.Value);
             try
             {
                 var clip = AudioClip.Create(
                     info.Name,
                     (int)audio.samples,
                     audio.channels,
                     audio.frequency,
                     true,
                     data => Decoder.FillBuffer(audio.stream, data));
                 clip.LoadAudioData();
                 prog?.Report(1);
                 resolve(clip);
             }
             catch (Exception exp)
             {
                 reject(exp);
             }
         }
References Juniper.Audio.Decoder.DecodeMP3(), Juniper.Audio.Decoder.DecodeVorbis(), Juniper.Audio.Decoder.DecodeWAV(), Juniper.Audio.Decoder.FillBuffer(), and Juniper.Unity.Data.StreamingAssets.GetStream().
Referenced by Juniper.Unity.Audio.AmbientAudio.Load().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Audio/StreamableAudioClip.cs