Juniper: Juniper.Unity.ImageTracking.VuforiaTrackerKeeper Class Reference
Juniper.Unity.ImageTracking.VuforiaTrackerKeeper Class Reference
Public Member Functions
override void Update ()
Checks the current tracking status and fires the events to indicate any change in the tracking status.
void LoadDataSet (string dataSetName)
Loads a set of Vuforia markers from disk and activates it at runtime.
void ResetPET ()
On Vuforia, resets the Persistent Extended Tracking, or starts it if it hasn't already been running.
TrackableFoundEventHandler Register (TrackableFoundEventHandler target)
Register's a target and its events for the aggregated events issued by TrackerKeeper.
void OnDestroy ()
Tears down the tracker keeper.
void StartTracker ()
Starts the tracker without changing any dataset data that has already been configured.
void StartTrackerWithDataSet (string dataSetName)
Initializes tracking of a set of targets.
void StartTrackerWithDataSetForTarget (string dataSetName, string targetName)
Initializes tracking of a specific target.
void Reset ()
Stop object tracking while in picker
Public Attributes
bool usePET
Set to true to enable using Vuforia's Persistent Extended Tracking.
bool manageVuforiaFrameRate = true
Set to true to set the target framerate lower than normal when the tracker is active.
bool DebugReport
Set to true to print out a debug report on the screen.
UnityEvent onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
UnityEvent onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
UnityEvent onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
UnityEvent onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
UnityEvent onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
TransformEvent onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
TransformEvent onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
UnityEvent onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
TransformEvent onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
TransformEvent onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Protected Member Functions
override void Start ()
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
override void OnTrackingStarting (string dataSetName, string targetName)
override void OnTrackingStarted ()
override void OnTrackingStopping ()
override void OnTrackingStopped ()
override void PrintDebugReport ()
If DebugReport is set to true, prints a report on the status of tracking.
Protected Attributes
override IEnumerable< TrackableFoundEventHandler > FirstTargets
readonly List< TrackableFoundEventHandler > targets = new List<TrackableFoundEventHandler>()
All of the targets in the system.
Properties
IEnumerator WaitForTracker [get]
A coroutine that waits for a Vuforia ObjectTracker to become available.
WaitUntil WaitForNotInitializing [get]
What for Vuforia's initialization state to no longer be "INITIALIZING".
bool Tracking [get, protected set]
Is set to true when the tracking system is initialized and running.
bool TargetFound [get]
Returns true when any target has been found and is tracking.
bool HasTargets [get]
Returns true when there are any GoodTargets.
bool Safe [get]
This value is set to true when the user is at a safe distance from the target.
Private Member Functions
void StopTracking ()
Cancel tracking and disable Vuforia. This also forces the Lost event on all of the currently tracked targets.
void EnableDataSet (string dataSetName)
On Vuforia, enables a specific set of data, either image targets, object targets, or scanned model targets.
IEnumerator EnablePETCoroutine ()
Handles marking a target as found, and optionally enables Vuforia's Persistent Extended Tracking.
IEnumerator StartTrackerCoroutine (string dataSetName, string targetName)
Initializes tracking of a specific target.
Private Attributes
const int VUFORIA_INIT_ATTEMPTS = 3
The number of times to attempt initializing Vuforia before just giving up.
ObjectTracker tracker
The Vuforia Tracker API.
bool firstTime = true
Used for reseting Vuforia's tracker the first time the application is started.
bool usingPET
Is set to true when Persistent Extended Tracking is active.
int numUpdates = 0
The number updates to the AR Background Image texture since tracking started. This value is used to delay switching from camera initialization to the app until after we are sure the camera is really ready.
Detailed Description
Definition at line 15 of file VuforiaTrackerKeeper.cs.
Member Function Documentation
EnableDataSet()
void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnableDataSet (string dataSetName) inline private
On Vuforia, enables a specific set of data, either image targets, object targets, or scanned model targets.
Parameters
dataSetName Data set name.
Definition at line 183 of file VuforiaTrackerKeeper.cs.
         {
             if (dataSetName != null)
             {
                 foreach (var ds in tracker.GetActiveDataSets())
                 {
                     tracker.DeactivateDataSet(ds);
                 }
                 LoadDataSet(dataSetName);
             }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.LoadDataSet(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StartTrackerCoroutine().
EnablePETCoroutine()
IEnumerator Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnablePETCoroutine () inline private
Handles marking a target as found, and optionally enables Vuforia's Persistent Extended Tracking.
Returns
The coroutine.
Definition at line 240 of file VuforiaTrackerKeeper.cs.
         {
             if (VuforiaUnityExt.HasPET && usePET && !usingPET)
             {
                 yield return WaitForTracker;
                 ResetPET();
                 usingPET = true;
             }
         }
References Vuforia.VuforiaUnityExt.HasPET, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.ResetPET(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.usePET, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.usingPET, and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.WaitForTracker.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.ResetPET().
LoadDataSet()
void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.LoadDataSet (string dataSetName) inline
Loads a set of Vuforia markers from disk and activates it at runtime.
Parameters
dataSetName Data set name.
Definition at line 200 of file VuforiaTrackerKeeper.cs.
         {
             if (tracker != null && !string.IsNullOrEmpty(dataSetName))
             {
                 var dataSets = tracker.GetActiveDataSets();
                 var targetPath = Path.Combine("Vuforia", dataSetName + ".xml");
                 var dataSet = dataSets.FirstOrDefault(ds =>
                     ds.Path == targetPath);
                 if (dataSet == null)
                 {
                     dataSet = tracker.CreateDataSet();
                     dataSet.Load(dataSetName);
                     tracker.ActivateDataSet(dataSet);
                 }
             }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnableDataSet().
OnDestroy()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnDestroy () inline inherited
Tears down the tracker keeper.
Definition at line 230 of file AbstractTrackerKeeper.cs.
         {
             done = true;
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.done.
OnTrackingStarted()
override void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStarted () inline protected virtual
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackerKeeper.
Definition at line 101 of file VuforiaTrackerKeeper.cs.
         {
             base.OnTrackingStarted();
                 if (manageVuforiaFrameRate)
                 {
                     Application.targetFrameRate = 30;
                 }
                 if (firstTime)
                 {
                     firstTime = false;
                     StopTracking();
                     if (tracker != null)
                     {
                         tracker.Start();
                     }
                     VuforiaBehaviour.Instance.enabled = true;
                 }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.firstTime, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.manageVuforiaFrameRate, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker.
OnTrackingStarting()
override void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStarting (string dataSetName, string targetName) inline protected virtual
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackerKeeper.
Definition at line 95 of file VuforiaTrackerKeeper.cs.
         {
             base.OnTrackingStarting(dataSetName, targetName);
             StartCoroutine(StartTrackerCoroutine(dataSetName, targetName));
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StartTrackerCoroutine().
OnTrackingStopped()
override void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStopped () inline protected virtual
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackerKeeper.
Definition at line 128 of file VuforiaTrackerKeeper.cs.
         {
             base.OnTrackingStopped();
                 if (manageVuforiaFrameRate)
                 {
                     Application.targetFrameRate = 60;
                 }
                 numUpdates = 0;
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.manageVuforiaFrameRate, and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.numUpdates.
OnTrackingStopping()
override void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStopping () inline protected virtual
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackerKeeper.
Definition at line 122 of file VuforiaTrackerKeeper.cs.
         {
             base.OnTrackingStopping();
             StopTracking();
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking().
PrintDebugReport()
override void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.PrintDebugReport () inline protected virtual
If DebugReport is set to true, prints a report on the status of tracking.
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackerKeeper.
Definition at line 348 of file VuforiaTrackerKeeper.cs.
         {
             ScreenDebugger.Print(tracker == null ? "No tracker" : "Has tracker");
             ScreenDebugger.Print(usingPET ? "Using PET" : "Not using PET");
         }
References System.ScreenDebugger.Print(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker, and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.usingPET.
Register()
TrackableFoundEventHandler Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register (TrackableFoundEventHandler target) inline inherited
Register's a target and its events for the aggregated events issued by TrackerKeeper.
Parameters
target Target.
Definition at line 146 of file AbstractTrackerKeeper.cs.
         {
             if (targets?.Contains(target) == false)
             {
                 targets.Add(target);
                 target.onFound.AddListener(TargetFinder(target));
                 target.onLost.AddListener(TargetLoser(target));
                 target.onProximity.AddListener(TargetProximity(target));
                 target.onSafe.AddListener(TargetSafe(target));
             }
             return target;
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onFound, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onLost, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onProximity, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onSafe, Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetProximity(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.targets, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetSafe().
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Awake(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Start().
Reset()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Reset () inline inherited
Stop object tracking while in picker
Definition at line 404 of file AbstractTrackerKeeper.cs.
         {
             OnTrackingStopping();
             Tracking = false;
             Update();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopping(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
ResetPET()
void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.ResetPET () inline
On Vuforia, resets the Persistent Extended Tracking, or starts it if it hasn't already been running.
Definition at line 254 of file VuforiaTrackerKeeper.cs.
         {
             if (usingPET && tracker != null)
             {
                 tracker.Stop();
                 tracker.Start();
             }
             else
             {
                 StartCoroutine(EnablePETCoroutine());
             }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnablePETCoroutine(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker, and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.usingPET.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnablePETCoroutine(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking().
Start()
override void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.Start () inline protected virtual
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackerKeeper.
Definition at line 68 of file VuforiaTrackerKeeper.cs.
         {
 #if UNITY_ANDROID
             manageVuforiaFrameRate = true;
 #endif
             base.Start();
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.manageVuforiaFrameRate.
StartTracker()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTracker () inline inherited
Starts the tracker without changing any dataset data that has already been configured.
Definition at line 363 of file AbstractTrackerKeeper.cs.
         {
             Invoke(nameof(StartTrackerDelayed), 1);
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed().
StartTrackerCoroutine()
IEnumerator Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StartTrackerCoroutine (string dataSetName, string targetName) inline private
Initializes tracking of a specific target.
Returns
The tracker coroutine.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 286 of file VuforiaTrackerKeeper.cs.
         {
             if (!VuforiaConfiguration.Instance.Vuforia.DelayedInitialization)
             {
                 VuforiaBehaviour.Instance.enabled = true;
                 yield return WaitForNotInitializing;
             }
             else
             {
                 VuforiaConfiguration.Instance.Vuforia.DelayedInitialization = false;
                 for (int i = 1; i <= VUFORIA_INIT_ATTEMPTS && VuforiaRuntime.Instance.InitializationState != VuforiaRuntime.InitState.INITIALIZED; ++i)
                 {
                     if (i > 1)
                     {
                         Debug.LogFormat("Initializating Vuforia failed. Retrying ({0} of {1})", i, VUFORIA_INIT_ATTEMPTS);
                         VuforiaRuntime.Instance.Deinit();
                     }
                     else
                     {
                         Debug.LogFormat("Initializing Vuforia ({0} of {1})", i, VUFORIA_INIT_ATTEMPTS);
                     }
                     if (VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.NOT_INITIALIZED)
                     {
                         VuforiaRuntime.Instance.InitVuforia();
                         VuforiaBehaviour.Instance.enabled = true;
                     }
                     yield return WaitForNotInitializing;
                 }
             }
             if (VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.INITIALIZED)
             {
                 yield return WaitForTracker;
                 if (tracker.IsActive)
                 {
                     tracker.Stop();
                     yield return new WaitUntil(() => !tracker.IsActive);
                 }
                 EnableDataSet(dataSetName);
                 if (!tracker.IsActive)
                 {
                     tracker.Start();
                     yield return new WaitUntil(() =>
                         tracker.IsActive);
                 }
             }
             else
             {
                 Debug.LogError("Failed to initialize Vuforia.");
             }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnableDataSet(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.VUFORIA_INIT_ATTEMPTS, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.WaitForNotInitializing, and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.WaitForTracker.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStarting().
StartTrackerWithDataSet()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSet (string dataSetName) inline inherited
Initializes tracking of a set of targets.
Parameters
dataSetName Data set name.
Definition at line 382 of file AbstractTrackerKeeper.cs.
         {
             ScreenDebugger.Print($"Activating data set: {dataSetName}");
             StartTrackerWithDataSetForTarget(dataSetName, null);
         }
References System.ScreenDebugger.Print(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
StartTrackerWithDataSetForTarget()
void Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget (string dataSetName, string targetName) inline inherited
Initializes tracking of a specific target.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 393 of file AbstractTrackerKeeper.cs.
         {
             OnTrackingStarting(dataSetName, targetName);
             Update();
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
Referenced by Juniper.Unity.ImageTracking.ARKitTrackerKeeper.Start(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSet().
StopTracking()
void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking () inline private
Cancel tracking and disable Vuforia. This also forces the Lost event on all of the currently tracked targets.
Definition at line 143 of file VuforiaTrackerKeeper.cs.
         {
             if (targets != null)
             {
                 foreach (var target in targets)
                 {
                     var modelBehaviour = target.GetComponent<ModelTargetBehaviour>();
                     if (modelBehaviour != null)
                     {
                         modelBehaviour.enabled = false;
                     }
                 }
             }
             ResetPET();
             if (tracker != null && tracker.IsActive)
             {
                 tracker.Stop();
             }
             if (Tracking)
             {
                 VuforiaBehaviour.Instance.enabled = false;
             }
             if (targets != null)
             {
                 foreach (var target in targets)
                 {
                     target.ForceLost();
                 }
             }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.ResetPET(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.targets, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStarted(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStopping().
Update()
override void Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.Update () inline virtual
Checks the current tracking status and fires the events to indicate any change in the tracking status.
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackerKeeper.
Definition at line 76 of file VuforiaTrackerKeeper.cs.
         {
             bool cameraRendering = VuforiaRuntime.Instance.InitializationState == VuforiaRuntime.InitState.INITIALIZED
                 && VuforiaBehaviour.Instance.enabled
                 && VuforiaRenderer.Instance.VideoBackgroundTexture != null;
             Tracking = cameraRendering
                  && numUpdates > Application.targetFrameRate
                  && tracker != null
                  && tracker.IsActive;
             if (cameraRendering)
             {
                 ++numUpdates;
             }
             base.Update();
         }
References Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.numUpdates, Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker, and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking.
Member Data Documentation
DebugReport
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.DebugReport inherited
Set to true to print out a debug report on the screen.
Definition at line 41 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
FirstTargets
override IEnumerable<TrackableFoundEventHandler> Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.FirstTargets protected
Initial value:
=>
            base.FirstTargets
                .Union(from m in this.FindAll<ModelTargetBehaviour>()
                       select m.EnsureComponent<TrackableFoundEventHandler>().Value)
                .Union(from m in this.FindAll<ImageTargetBehaviour>()
                       select m.EnsureComponent<TrackableFoundEventHandler>().Value)
                .Union(from m in this.FindAll<ObjectTargetBehaviour>()
                       select m.EnsureComponent<TrackableFoundEventHandler>().Value)
Definition at line 59 of file VuforiaTrackerKeeper.cs.
firstTime
bool Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.firstTime = true private
Used for reseting Vuforia's tracker the first time the application is started.
Definition at line 35 of file VuforiaTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStarted().
manageVuforiaFrameRate
bool Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.manageVuforiaFrameRate = true
Set to true to set the target framerate lower than normal when the tracker is active.
Definition at line 42 of file VuforiaTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStarted(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStopped(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.Start().
numUpdates
int Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.numUpdates = 0 private
The number updates to the AR Background Image texture since tracking started. This value is used to delay switching from camera initialization to the app until after we are sure the camera is really ready.
Definition at line 57 of file VuforiaTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStopped(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.Update().
onAllTargetsLost
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onAllTargetsLost = new UnityEvent() inherited
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
Definition at line 106 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost().
onAnyTargetFound
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onAnyTargetFound = new UnityEvent() inherited
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
Definition at line 90 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onTargetFound
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetFound = new TransformEvent() inherited
A Unity Event that occurs every time any target is found.
Definition at line 95 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onTargetLost
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetLost = new TransformEvent() inherited
A Unity Event that occurs every time any target is lost.
Definition at line 100 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser().
onTargetProximity
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetProximity = new TransformEvent() inherited
A UnityEvent that occurs when the user gets too close to a target.
Definition at line 116 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetProximity().
onTargetSafe
TransformEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTargetSafe = new TransformEvent() inherited
A UnityEvent that occurs when the user is at a safe distance from the target.
Definition at line 111 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetSafe().
onTrackingStarted
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStarted = new UnityEvent() inherited
A Unity Event that occurs when the tracking system has been initialized and started.
Definition at line 74 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarted().
onTrackingStarting
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStarting = new UnityEvent() inherited
A Unity Event that occurs when the tracking system is about to be initialized. and started.
Definition at line 69 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting().
onTrackingStopped
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStopped = new UnityEvent() inherited
A Unity Event that occurs when the tracking system has been shut down.
Definition at line 84 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopped().
onTrackingStopping
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackerKeeper.onTrackingStopping = new UnityEvent() inherited
A Unity Event that occurs when the tracking system is about to be shut down. and started.
Definition at line 79 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnTrackingStopping().
targets
readonly List<TrackableFoundEventHandler> Juniper.Unity.ImageTracking.AbstractTrackerKeeper.targets = new List<TrackableFoundEventHandler>() protected inherited
All of the targets in the system.
Definition at line 23 of file AbstractTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register(), Juniper.Unity.ImageTracking.ARKitTrackerKeeper.Start(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
tracker
ObjectTracker Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.tracker private
The Vuforia Tracker API.
Definition at line 25 of file VuforiaTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnableDataSet(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.LoadDataSet(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.OnTrackingStarted(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.PrintDebugReport(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.ResetPET(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StartTrackerCoroutine(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.Update().
usePET
bool Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.usePET
Set to true to enable using Vuforia's Persistent Extended Tracking.
Definition at line 30 of file VuforiaTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnablePETCoroutine().
usingPET
bool Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.usingPET private
Is set to true when Persistent Extended Tracking is active.
Definition at line 50 of file VuforiaTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnablePETCoroutine(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.PrintDebugReport(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.ResetPET().
VUFORIA_INIT_ATTEMPTS
const int Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.VUFORIA_INIT_ATTEMPTS = 3 private
The number of times to attempt initializing Vuforia before just giving up.
Definition at line 20 of file VuforiaTrackerKeeper.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StartTrackerCoroutine().
Property Documentation
HasTargets
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.HasTargets get inherited
Returns true when there are any GoodTargets.
true if has targets; otherwise, false.
Definition at line 327 of file AbstractTrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetLoser().
Safe
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Safe get inherited
This value is set to true when the user is at a safe distance from the target.
Definition at line 345 of file AbstractTrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found && !target.Safe)
                     {
                         return false;
                     }
                 }
                 return true;
             }
         }
TargetFound
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFound get inherited
Returns true when any target has been found and is tracking.
Definition at line 52 of file AbstractTrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Tracking
bool Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Tracking get protected set inherited
Is set to true when the tracking system is initialized and running.
Definition at line 29 of file AbstractTrackerKeeper.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), Juniper.Unity.ImageTracking.ARKitTrackerKeeper.OnTrackingStarting(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Reset(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StopTracking(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.Update(), Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update(), and Juniper.Unity.ImageTracking.ARKitTrackerKeeper.WithTarget().
WaitForNotInitializing
WaitUntil Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.WaitForNotInitializing get private
What for Vuforia's initialization state to no longer be "INITIALIZING".
The wait for not initializing.
Definition at line 272 of file VuforiaTrackerKeeper.cs.
         {
             get
             {
                 return new WaitUntil(() =>
                     VuforiaRuntime.Instance.InitializationState != VuforiaRuntime.InitState.INITIALIZING);
             }
         }
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StartTrackerCoroutine().
WaitForTracker
IEnumerator Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.WaitForTracker get private
A coroutine that waits for a Vuforia ObjectTracker to become available.
The wait for tracker.
Definition at line 222 of file VuforiaTrackerKeeper.cs.
         {
             get
             {
                 return new WaitUntil(() =>
                 {
                     if (tracker == null)
                     {
                         tracker = TrackerManager.Instance.GetTracker<ObjectTracker>();
                     }
                     return tracker != null;
                 });
             }
         }
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.EnablePETCoroutine(), and Juniper.Unity.ImageTracking.VuforiaTrackerKeeper.StartTrackerCoroutine().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/Vuforia/VuforiaTrackerKeeper.cs