Juniper: Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration Class Reference
Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration Class Reference
Public Member Functions
PlatformConfiguration ()
bool SwitchTarget ()
void InstallUnityPackages (IProgressReceiver prog=null)
void InstallRawPackages (IProgressReceiver prog=null)
void Activate (IProgressReceiver prog)
void UninstallRawPackages (IProgressReceiver prog=null)
void UninstallUnityPackages (IProgressReceiver prog=null)
Public Attributes
string Name
string CompilerDefine
string buildTarget
string spatializer
string androidSdkVersion
string iOSVersion
string wsaSubtarget
string [] vrSystems
string [] packages
Properties
BuildTarget BuildTarget [get]
BuildTargetGroup TargetGroup [get]
bool IsSupported [get]
IEnumerable< UnityXRPlatforms > XRPlatforms [get]
UnityPackage [] UninstallableUnityPackages [get, set]
UnityPackage [] IncludedUnityPackages [get, set]
UnityPackage [] ExcludedUnityPackages [get, set]
RawPackage [] UninstallableRawPackages [get, set]
RawPackage [] RawPackages [get, set]
List< string > CompilerDefines [get]
Private Member Functions
internal void Deactivate (PlatformConfiguration nextConfiguration)
Detailed Description
Definition at line 17 of file PlatformConfiguration.cs.
Constructor & Destructor Documentation
PlatformConfiguration()
Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration () inline
Definition at line 29 of file PlatformConfiguration.cs.
         {
             Name = null;
             CompilerDefine = null;
             buildTarget = null;
             vrSystems = null;
             packages = null;
             spatializer = null;
             androidSdkVersion = null;
             iOSVersion = null;
             wsaSubtarget = null;
         }
References Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.androidSdkVersion, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.buildTarget, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.CompilerDefine, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.iOSVersion, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Name, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.packages, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.spatializer, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.vrSystems, and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.wsaSubtarget.
Member Function Documentation
Activate()
void Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate (IProgressReceiver prog) inline
Definition at line 191 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(IncludedUnityPackages, progs[0], (pkg, p) => pkg.Activate(TargetGroup, p));
             Platforms.ForEachPackage(RawPackages, progs[1], (pkg, p) => pkg.Activate(TargetGroup, p));
             if (!string.IsNullOrEmpty(spatializer))
             {
                 var hasSpatializer = AudioSettings
                     .GetSpatializerPluginNames()
                     .Contains(spatializer);
                 if (hasSpatializer)
                 {
                     AudioSettings.SetSpatializerPluginName(spatializer);
                     AudioSettingsExt.SetAmbisonicDecoderPluginName(spatializer);
                 }
             }
             var supportedVRSDKs = PlayerSettings.GetAvailableVirtualRealitySDKs(TargetGroup);
             var vrSDKs = XRPlatforms
                 .Distinct()
                 .Select(x => x.ToString())
                 .Where(supportedVRSDKs.Contains)
                 .ToArray();
             var enableVR = vrSDKs.Any(sdk => sdk != "None");
             if (enableVR != PlayerSettings.GetVirtualRealitySupported(TargetGroup))
             {
                 PlayerSettings.SetVirtualRealitySupported(TargetGroup, enableVR);
                 if (enableVR && !vrSDKs.Matches(PlayerSettings.GetVirtualRealitySDKs(TargetGroup)))
                 {
                     PlayerSettings.SetVirtualRealitySDKs(TargetGroup, vrSDKs);
                 }
             }
             if (TargetGroup == BuildTargetGroup.WSA)
             {
                 EditorUserBuildSettings.wsaBuildAndRunDeployTarget = WSABuildAndRunDeployTarget.LocalMachine;
                 EditorUserBuildSettings.wsaUWPBuildType = WSAUWPBuildType.D3D;
                 PlayerSettings.WSA.inputSource = PlayerSettings.WSAInputSource.IndependentInputSource;
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.InternetClient, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.WebCam, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Bluetooth, true);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Microphone, ComponentExt.FindAny<KeywordRecognizer>() != null);
                 PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.Location, ComponentExt.FindAny<GPSLocation>() != null);
                 WSASubtarget sub;
                 if (Enum.TryParse(wsaSubtarget, out sub))
                 {
                     EditorUserBuildSettings.wsaSubtarget = sub;
                     PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.SpatialPerception, sub == WSASubtarget.HoloLens);
                 }
             }
             else if (TargetGroup == BuildTargetGroup.Android)
             {
                 AndroidSdkVersions sdkVersion;
                 if (Enum.TryParse(androidSdkVersion, out sdkVersion))
                 {
                     PlayerSettings.Android.minSdkVersion = (AndroidSdkVersions)Math.Max(
                         (int)PlayerSettings.Android.minSdkVersion,
                         (int)sdkVersion);
                 }
             }
             else if (TargetGroup == BuildTargetGroup.iOS)
             {
                 Version v;
                 if (Version.TryParse(iOSVersion, out v)
                     && PlayerSettingsExt.iOS.TargetOSVersion < v)
                 {
                     PlayerSettingsExt.iOS.TargetOSVersion = v;
                 }
             }
         }
References Juniper.UnityEditor.ConfigurationManagement.AbstractPackage.Activate(), Juniper.UnityEditor.ConfigurationManagement.RawPackage.Activate(), Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.androidSdkVersion, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.iOSVersion, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.RawPackages, Juniper.UnityEditor.AudioSettingsExt.SetAmbisonicDecoderPluginName(), Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.spatializer, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.TargetGroup, Juniper.UnityEditor.PlayerSettingsExt.iOS.TargetOSVersion, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.wsaSubtarget, and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.XRPlatforms.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Deactivate()
internal void Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Deactivate (PlatformConfiguration nextConfiguration) inline private
Definition at line 310 of file PlatformConfiguration.cs.
         {
             AudioSettings.SetSpatializerPluginName(null);
             AudioSettingsExt.SetAmbisonicDecoderPluginName(null);
             PlayerSettings.virtualRealitySupported = false;
             PlayerSettings.Android.androidTVCompatibility = false;
 #if UNITY_2018_2_OR_NEWER
             PlayerSettings.Android.ARCoreEnabled = false;
 #endif
             PlayerSettingsExt.iOS.RequiresARKitSupport = false;
             PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
             if (nextConfiguration.TargetGroup != TargetGroup)
             {
                 PlayerSettings.SetPlatformVuforiaEnabled(TargetGroup, false);
             }
         }
References Juniper.UnityEditor.PlayerSettingsExt.iOS.RequiresARKitSupport, Juniper.UnityEditor.AudioSettingsExt.SetAmbisonicDecoderPluginName(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.TargetGroup.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform().
InstallRawPackages()
void Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallRawPackages (IProgressReceiver prog = null) inline
Definition at line 186 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(RawPackages, prog, (pkg, p) => pkg.Install(p));
         }
References Juniper.UnityEditor.ConfigurationManagement.RawPackage.Install(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.RawPackages.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
InstallUnityPackages()
void Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages (IProgressReceiver prog = null) inline
Definition at line 160 of file PlatformConfiguration.cs.
         {
             var progs = prog.Split(2);
             Platforms.ForEachPackage(ExcludedUnityPackages, progs[0], (pkg, p) =>
 #if UNITY_2018_2_OR_NEWER
                 pkg.Uninstall(p)
 #else
                 pkg.Install(p)
 #endif
             );
             Platforms.ForEachPackage(IncludedUnityPackages, progs[1], (pkg, p) =>
             {
 #if UNITY_2018_2_OR_NEWER
                 if (pkg.Name != "com.unity.xr.magicleap")
                 {
                     pkg.Install(p);
                 }
 #else
                 if (pkg.Name != "com.unity.xr.magicleap" && !pkg.Name.StartsWith("com.unity.modules."))
                 {
                     pkg.Install(p);
                 }
 #endif
             });
         }
References Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.ExcludedUnityPackages, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages, Juniper.UnityEditor.ConfigurationManagement.UnityPackage.Install(), and Juniper.UnityEditor.ConfigurationManagement.UnityPackage.Uninstall().
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
SwitchTarget()
bool Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.SwitchTarget () inline
Definition at line 146 of file PlatformConfiguration.cs.
         {
             if (BuildTarget != EditorUserBuildSettings.activeBuildTarget)
             {
                 Debug.Log($"Switching build target from {EditorUserBuildSettings.activeBuildTarget} to {BuildTarget}.");
                 EditorUserBuildSettings.SwitchActiveBuildTargetAsync(TargetGroup, BuildTarget);
                 return true;
             }
             else
             {
                 return false;
             }
         }
References Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.BuildTarget, and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.TargetGroup.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
UninstallRawPackages()
void Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages (IProgressReceiver prog = null) inline
Definition at line 265 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(UninstallableRawPackages, prog, (pkg, p) => pkg.Uninstall(p));
         }
References Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallableRawPackages.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
UninstallUnityPackages()
void Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages (IProgressReceiver prog = null) inline
Definition at line 270 of file PlatformConfiguration.cs.
         {
             Platforms.ForEachPackage(UninstallableUnityPackages, prog, (pkg, p) => pkg.Uninstall(p));
         }
References Juniper.UnityEditor.ConfigurationManagement.UnityPackage.Uninstall(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallableUnityPackages.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Member Data Documentation
androidSdkVersion
string Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.androidSdkVersion
Definition at line 23 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
buildTarget
string Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.buildTarget
Definition at line 21 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
CompilerDefine
string Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.CompilerDefine
Definition at line 20 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
iOSVersion
string Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.iOSVersion
Definition at line 24 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
Name
string Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Name
Definition at line 19 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
packages
string [] Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.packages
Definition at line 27 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
spatializer
string Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.spatializer
Definition at line 22 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
vrSystems
string [] Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.vrSystems
Definition at line 26 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
wsaSubtarget
string Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.wsaSubtarget
Definition at line 25 of file PlatformConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.PlatformConfiguration().
Property Documentation
BuildTarget
BuildTarget Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.BuildTarget get
Definition at line 44 of file PlatformConfiguration.cs.
         {
             get
             {
                 var localBuildTarget = buildTarget;
                 if (localBuildTarget == "Standalone")
                 {
 #if UNITY_EDITOR_WIN
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneWindows);
                     }
 #elif UNITY_EDITOR_OSX
                     localBuildTarget = nameof(BuildTarget.StandaloneOSX);
 #else
                     if (Environment.Is64BitOperatingSystem)
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux64);
                     }
                     else
                     {
                         localBuildTarget = nameof(BuildTarget.StandaloneLinux);
                     }
 #endif
                 }
                 return (BuildTarget)Enum.Parse(typeof(BuildTarget), localBuildTarget);
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.SwitchTarget().
CompilerDefines
List<string> Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.CompilerDefines get
Definition at line 276 of file PlatformConfiguration.cs.
         {
             get
             {
                 var defines = Platforms.GetCompilerDefines(IncludedUnityPackages, RawPackages).ToList();
                 if (!string.IsNullOrEmpty(CompilerDefine))
                 {
                     defines.Add(CompilerDefine);
                 }
                 if (TargetGroup == BuildTargetGroup.Android)
                 {
                     for (var i = (int)PlayerSettings.Android.minSdkVersion; i > 0; --i)
                     {
                         if (Enum.IsDefined(typeof(AndroidSdkVersions), i))
{
                             defines.Add("ANDROID_API_" + i);
                             defines.Add("ANDROID_API_" + i + "_OR_GREATER");
                         }
                     }
                 }
                 else if (TargetGroup == BuildTargetGroup.iOS)
                 {
                     for (var i = PlayerSettingsExt.iOS.TargetOSVersion.Major; i > 0; --i)
                     {
                         defines.Add("IOS_VERSION_" + i);
                         defines.Add("IOS_VERSION_" + i + "_OR_GREATER");
                     }
                 }
                 return defines;
             }
         }
ExcludedUnityPackages
UnityPackage [] Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.ExcludedUnityPackages get set
Definition at line 130 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages().
IncludedUnityPackages
UnityPackage [] Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.IncludedUnityPackages get set
Definition at line 124 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages().
IsSupported
bool Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.IsSupported get
Definition at line 87 of file PlatformConfiguration.cs.
         {
             get
             {
 #if UNITY_2018_1_OR_NEWER
                 return BuildPipeline.IsBuildTargetSupported(TargetGroup, BuildTarget);
 #else
                 var moduleManager = System.Type.GetType("UnityEditor.Modules.ModuleManager,UnityEditor.dll");
                 var isPlatformSupportLoaded = moduleManager.GetMethod(
                     "IsPlatformSupportLoaded",
                     System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
                 var getTargetStringFromBuildTarget = moduleManager.GetMethod(
                     "GetTargetStringFromBuildTarget",
                     System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic);
                 var targetString = (string)getTargetStringFromBuildTarget.Invoke(null, new object[] {BuildTarget.tvOS});
                 return (bool)isPlatformSupportLoaded.Invoke(null,new object[] {targetString});
 #endif
             }
         }
RawPackages
RawPackage [] Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.RawPackages get set
Definition at line 142 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallRawPackages().
TargetGroup
BuildTargetGroup Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.TargetGroup get
Definition at line 78 of file PlatformConfiguration.cs.
         {
             get
             {
                 return BuildPipeline.GetBuildTargetGroup(BuildTarget);
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Deactivate(), and Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.SwitchTarget().
UninstallableRawPackages
RawPackage [] Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallableRawPackages get set
Definition at line 136 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages().
UninstallableUnityPackages
UnityPackage [] Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallableUnityPackages get set
Definition at line 118 of file PlatformConfiguration.cs.
         {
             get; internal set;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages().
XRPlatforms
IEnumerable<UnityXRPlatforms> Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.XRPlatforms get
Definition at line 108 of file PlatformConfiguration.cs.
         {
             get
             {
                 return from sys in vrSystems
                        select (UnityXRPlatforms)Enum.Parse(typeof(UnityXRPlatforms), sys);
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/ConfigurationManagement/PlatformConfiguration.cs