Juniper: Juniper.IO.ICacheSourceLayer Interface Reference
Juniper.IO.ICacheSourceLayer Interface Reference
Public Member Functions
bool IsCached (ContentReference fileRef)
Task< Stream > GetStreamAsync (ContentReference fileRef, IProgress prog)
IEnumerable< ContentReference > GetContentReferences (MediaType ofType)
Detailed Description
Definition at line 7 of file ICacheSourceLayer.cs.
Member Function Documentation
GetContentReferences()
IEnumerable<ContentReference> Juniper.IO.ICacheSourceLayer.GetContentReferences (MediaType ofType)
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.ZipFileCacheLayer, Juniper.IO.FileCacheLayer, Juniper.IO.MemoryCacheLayer, and Juniper.IO.StreamSourceLayer.
Referenced by Juniper.IO.ICacheSourceLayerExt.GetAsync< ResultT, MediaTypeT >().
GetStreamAsync()
Task<Stream> Juniper.IO.ICacheSourceLayer.GetStreamAsync (ContentReference fileRef, IProgress prog)
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.ZipFileCacheLayer, Juniper.IO.FileCacheLayer, Juniper.IO.MemoryCacheLayer, and Juniper.IO.StreamSourceLayer.
Referenced by Juniper.IO.ICacheDestinationLayerExt.CopyToAsync(), Juniper.IO.ICacheSourceLayerExt.GetAsync< ResultT, MediaTypeT >(), Juniper.IO.ICacheSourceLayerExt.LoadAsync< ResultT >(), Juniper.IO.ICacheSourceLayerExt.OpenAsync(), and Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync().
IsCached()
bool Juniper.IO.ICacheSourceLayer.IsCached (ContentReference fileRef)
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.ZipFileCacheLayer, Juniper.IO.StreamSourceLayer, Juniper.IO.FileCacheLayer, and Juniper.IO.MemoryCacheLayer.
Referenced by Juniper.IO.ICacheDestinationLayerExt.CopyToAsync().
The documentation for this interface was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/ICacheSourceLayer.cs