Juniper: Juniper.XR.CustomEditors.RawPackage Class Reference
Juniper.XR.CustomEditors.RawPackage Class Reference
Public Member Functions
RawPackage ()
override void Install (IProgressReceiver prog=null)
override void Activate (BuildTargetGroup targetGroup, IProgressReceiver prog=null)
override void Uninstall (IProgressReceiver prog=null)
Public Attributes
string spatializer
string androidSdkVersion
string iOSVersion
string wsaSubtarget
string InputZipFileName => Path.ChangeExtension(Path.Combine(ROOT_DIRECTORY, Name), "zip")
string Name
string CompilerDefine
Static Public Attributes
static string ROOT_DIRECTORY = PathExt.FixPath("Assets/Juniper/ThirdParty/Optional")
Static Private Member Functions
static void DeleteAll (IEnumerable< string > paths, Func< string, bool > tryDelete, IProgressReceiver prog)
Detailed Description
Definition at line 15 of file RawPackage.cs.
Constructor & Destructor Documentation
RawPackage()
Juniper.XR.CustomEditors.RawPackage.RawPackage () inline
Definition at line 24 of file RawPackage.cs.
         {
             spatializer = null;
             androidSdkVersion = null;
             iOSVersion = null;
             wsaSubtarget = null;
         }
References Juniper.XR.CustomEditors.RawPackage.androidSdkVersion, Juniper.XR.CustomEditors.RawPackage.iOSVersion, Juniper.XR.CustomEditors.RawPackage.spatializer, and Juniper.XR.CustomEditors.RawPackage.wsaSubtarget.
Member Function Documentation
Activate()
override void Juniper.XR.CustomEditors.RawPackage.Activate (BuildTargetGroup targetGroup, IProgressReceiver prog = null) inline virtual
Reimplemented from Juniper.XR.CustomEditors.AbstractPackage.
Definition at line 47 of file RawPackage.cs.
         {
             base.Activate(targetGroup, prog);
             if (!string.IsNullOrEmpty(spatializer))
             {
                 var hasSpatializer = AudioSettings
                     .GetSpatializerPluginNames()
                     .Contains(spatializer);
                 if (hasSpatializer)
                 {
                     AudioSettings.SetSpatializerPluginName(spatializer);
                     AudioSettingsExt.SetAmbisonicDecoderPluginName(spatializer);
                 }
             }
             if (Name == "Vuforia")
             {
                 PlayerSettings.SetPlatformVuforiaEnabled(targetGroup, true);
             }
             if (targetGroup == BuildTargetGroup.Android)
             {
                 if (Name == "GoogleARCore")
                 {
 #if UNITY_2018_2_OR_NEWER
                     PlayerSettings.Android.ARCoreEnabled = true;
 #endif
                 }
                 else if (Name == "GoogleVR")
                 {
                     FileExt.Copy(
                         PathExt.FixPath("Assets/GoogleVR/Plugins/Android/AndroidManifest-6DOF.xml"),
                         PathExt.FixPath("Assets/Plugins/Android/AndroidManifest.xml"),
                         true);
                 }
                 AndroidSdkVersions sdkVersion;
                 if (Enum.TryParse(androidSdkVersion, out sdkVersion))
                 {
                     PlayerSettings.Android.minSdkVersion = (AndroidSdkVersions)Math.Max(
                         (int)PlayerSettings.Android.minSdkVersion,
                         (int)sdkVersion);
                 }
             }
             else if (targetGroup == BuildTargetGroup.iOS)
             {
                 Version v;
                 if (Version.TryParse(iOSVersion, out v)
                     && PlayerSettingsExt.iOS.TargetOSVersion < v)
                 {
                     PlayerSettingsExt.iOS.TargetOSVersion = v;
                 }
                 if (Name == "UnityARKitPlugin")
                 {
                     PlayerSettingsExt.iOS.RequiresARKitSupport = true;
                     if (string.IsNullOrEmpty(PlayerSettings.iOS.cameraUsageDescription))
                     {
                         PlayerSettings.iOS.cameraUsageDescription = "Augmented reality camera view";
                     }
                 }
             }
             else if (targetGroup == BuildTargetGroup.WSA)
             {
                 WSASubtarget sub;
                 if (Enum.TryParse(wsaSubtarget, out sub))
                 {
                     EditorUserBuildSettings.wsaSubtarget = sub;
                     PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.SpatialPerception, sub == WSASubtarget.HoloLens);
                 }
             }
         }
References Juniper.XR.CustomEditors.RawPackage.androidSdkVersion, System.IO.FileExt.Copy(), System.IO.PathExt.FixPath(), Juniper.XR.CustomEditors.RawPackage.iOSVersion, Juniper.XR.CustomEditors.AbstractPackage.Name, UnityEditor.PlayerSettingsExt.iOS.RequiresARKitSupport, UnityEditor.AudioSettingsExt.SetAmbisonicDecoderPluginName(), Juniper.XR.CustomEditors.RawPackage.spatializer, UnityEditor.PlayerSettingsExt.iOS.TargetOSVersion, and Juniper.XR.CustomEditors.RawPackage.wsaSubtarget.
Referenced by Juniper.XR.CustomEditors.PlatformConfiguration.Activate().
DeleteAll()
static void Juniper.XR.CustomEditors.RawPackage.DeleteAll (IEnumerable< string > paths, Func< string, bool > tryDelete, IProgressReceiver prog) inline static private
Definition at line 123 of file RawPackage.cs.
         {
             prog?.SetProgress(0, "Deleting");
             var prefixedPath = paths
                 .Select(path => Path.Combine("Assets", path))
                 .ToArray();
             var subProgs = prog.Split(prefixedPath.Length);
             var index = 0;
             foreach (var path in prefixedPath)
             {
                 try
                 {
                     subProgs[index]?.SetProgress(0);
                     if (tryDelete(path))
                     {
                         subProgs[index]?.SetProgress(1);
                     }
                     ++index;
                 }
                 catch (OperationCanceledException)
                 {
                     throw;
                 }
                 catch (Exception exp)
                 {
                     Debug.LogException(exp);
                 }
             }
             prog?.SetProgress(1, "Deleted");
         }
References Juniper.Progress.IProgressReceiver.SetProgress().
Referenced by Juniper.XR.CustomEditors.RawPackage.Uninstall().
Install()
override void Juniper.XR.CustomEditors.RawPackage.Install (IProgressReceiver prog = null) inline virtual
Reimplemented from Juniper.XR.CustomEditors.AbstractPackage.
Definition at line 35 of file RawPackage.cs.
         {
             base.Install(prog);
             if (File.Exists(InputZipFileName))
             {
                 Zip.DecompressDirectory(InputZipFileName, "Assets", prog);
             }
             prog?.SetProgress(1);
         }
References Juniper.Data.Zip.DecompressDirectory(), and Juniper.XR.CustomEditors.RawPackage.InputZipFileName.
Uninstall()
override void Juniper.XR.CustomEditors.RawPackage.Uninstall (IProgressReceiver prog = null) inline virtual
Reimplemented from Juniper.XR.CustomEditors.AbstractPackage.
Definition at line 157 of file RawPackage.cs.
         {
             base.Uninstall(prog);
             var progs = prog.Split(4);
             var dirs = Zip.RecurseDirectories(InputZipFileName, progs[2]);
             var files = Zip.RecurseFiles(InputZipFileName, progs[0]);
             files = files
                 .Union(files.Select(file => file + ".meta"))
                 .Union(dirs.Select(dir => dir + ".meta"))
                 .Where(path => !path.EndsWith(".meta.meta"));
             DeleteAll(files, FileExt.TryDelete, progs[1]);
             DeleteAll(dirs.Reverse(), DirectoryExt.TryDelete, progs[3]);
         }
References Juniper.XR.CustomEditors.RawPackage.DeleteAll(), Juniper.XR.CustomEditors.RawPackage.InputZipFileName, Juniper.Data.Zip.RecurseDirectories(), Juniper.Data.Zip.RecurseFiles(), System.IO.FileExt.TryDelete(), and System.IO.DirectoryExt.TryDelete().
Member Data Documentation
androidSdkVersion
string Juniper.XR.CustomEditors.RawPackage.androidSdkVersion
Definition at line 20 of file RawPackage.cs.
Referenced by Juniper.XR.CustomEditors.RawPackage.Activate(), and Juniper.XR.CustomEditors.RawPackage.RawPackage().
CompilerDefine
string Juniper.XR.CustomEditors.AbstractPackage.CompilerDefine inherited
Definition at line 12 of file AbstractPackage.cs.
Referenced by Juniper.XR.CustomEditors.UnityPackage.UnityPackage().
InputZipFileName
string Juniper.XR.CustomEditors.RawPackage.InputZipFileName => Path.ChangeExtension(Path.Combine(ROOT_DIRECTORY, Name), "zip")
Definition at line 33 of file RawPackage.cs.
Referenced by Juniper.XR.CustomEditors.RawPackage.Install(), and Juniper.XR.CustomEditors.RawPackage.Uninstall().
iOSVersion
string Juniper.XR.CustomEditors.RawPackage.iOSVersion
Definition at line 21 of file RawPackage.cs.
Referenced by Juniper.XR.CustomEditors.RawPackage.Activate(), and Juniper.XR.CustomEditors.RawPackage.RawPackage().
Name
string Juniper.XR.CustomEditors.AbstractPackage.Name inherited
Definition at line 11 of file AbstractPackage.cs.
Referenced by Juniper.XR.CustomEditors.RawPackage.Activate(), Juniper.XR.CustomEditors.UnityPackage.Install(), Juniper.XR.CustomEditors.UnityPackage.Uninstall(), and Juniper.XR.CustomEditors.UnityPackage.UnityPackage().
ROOT_DIRECTORY
string Juniper.XR.CustomEditors.RawPackage.ROOT_DIRECTORY = PathExt.FixPath("Assets/Juniper/ThirdParty/Optional") static
Definition at line 17 of file RawPackage.cs.
Referenced by Juniper.XR.CustomEditors.Platforms.Platforms().
spatializer
string Juniper.XR.CustomEditors.RawPackage.spatializer
Definition at line 19 of file RawPackage.cs.
Referenced by Juniper.XR.CustomEditors.RawPackage.Activate(), and Juniper.XR.CustomEditors.RawPackage.RawPackage().
wsaSubtarget
string Juniper.XR.CustomEditors.RawPackage.wsaSubtarget
Definition at line 22 of file RawPackage.cs.
Referenced by Juniper.XR.CustomEditors.RawPackage.Activate(), and Juniper.XR.CustomEditors.RawPackage.RawPackage().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/XR/RawPackage.cs