Juniper: Juniper.Unity.Input.Speech.Keywordable Class Reference
Juniper.Unity.Input.Speech.Keywordable Class Reference
An object that can be fires an event when a particular keyword is uttered.
Public Member Functions
void Awake ()
Get the speech recognition manager.
void OnEnable ()
Trigger updating the current recognizable keyword set.
void Update ()
Check to see if the keyboard shortcut has been triggered.
Public Attributes
string [] keywords
The keywords that activate this event.
KeyCode shortcutKey = KeyCode.None
A keyboard shortcut to make development easier (and quieter, RE: open-floor plans).
UnityEvent onKeyword = new UnityEvent()
The event to trigger when the keyword is recognized. If you are programmatically wiring up events, prefer the Keyword event instead.
Protected Member Functions
virtual void OnKeyword ()
When a keyword is found (or a keyboard shortcut is triggered), fire the event (if it's valid).
Properties
IEnumerable< string > Keywords [get]
The keywords that activate this event.
bool HasKeywords [get]
Returns true when this component has more than one keyword defined and we were able to find the speech recognition manager.
Events
EventHandler Keyword
The event to trigger when the keyword is recognized. If you are programmatically wiring up events, prefer this event over the onKeyword event.
Private Member Functions
void OnKeyword (string word)
Respond to a keyword detected event. If the keyword was one that we care about in this component, then trigger the event.
void Start ()
On startup, register an event handler on the speech reconition manager for whenever keywords are detected.
Private Attributes
KeywordRecognizer keyer
The main speech recognition manager.
Detailed Description
An object that can be fires an event when a particular keyword is uttered.
Definition at line 16 of file Keywordable.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Input.Speech.Keywordable.Awake () inline
Get the speech recognition manager.
Definition at line 55 of file Keywordable.cs.
         {
             keyer = ComponentExt.FindAny<KeywordRecognizer>();
         }
References Juniper.Unity.Input.Speech.Keywordable.keyer.
OnEnable()
void Juniper.Unity.Input.Speech.Keywordable.OnEnable () inline
Trigger updating the current recognizable keyword set.
Definition at line 63 of file Keywordable.cs.
         {
             if (HasKeywords)
             {
                 keyer.RefreshKeywords();
             }
         }
References Juniper.Unity.Input.Speech.Keywordable.HasKeywords, Juniper.Unity.Input.Speech.Keywordable.keyer, and Juniper.Unity.Input.Speech.KeywordRecognizer.RefreshKeywords().
OnKeyword() [1/2]
virtual void Juniper.Unity.Input.Speech.Keywordable.OnKeyword () inline protected virtual
When a keyword is found (or a keyboard shortcut is triggered), fire the event (if it's valid).
Definition at line 85 of file Keywordable.cs.
         {
             onKeyword?.Invoke();
             Keyword?.Invoke(this, EventArgs.Empty);
             foreach (var button in GetComponents<IPointerClickHandler>())
             {
                 button?.OnPointerClick(null);
             }
         }
References Juniper.Unity.Input.Speech.Keywordable.Keyword, and Juniper.Unity.Input.Speech.Keywordable.onKeyword.
Referenced by Juniper.Unity.Input.Speech.Keywordable.OnKeyword(), Juniper.Unity.Input.Speech.Keywordable.Start(), and Juniper.Unity.Input.Speech.Keywordable.Update().
OnKeyword() [2/2]
void Juniper.Unity.Input.Speech.Keywordable.OnKeyword (string word) inline private
Respond to a keyword detected event. If the keyword was one that we care about in this component, then trigger the event.
Parameters
word Word.
Definition at line 119 of file Keywordable.cs.
         {
             if (Array.BinarySearch(keywords, word) >= 0)
             {
                 OnKeyword();
             }
         }
References Juniper.Unity.Input.Speech.Keywordable.keywords, and Juniper.Unity.Input.Speech.Keywordable.OnKeyword().
Start()
void Juniper.Unity.Input.Speech.Keywordable.Start () inline private
On startup, register an event handler on the speech reconition manager for whenever keywords are detected.
Definition at line 131 of file Keywordable.cs.
         {
             if (HasKeywords)
             {
                 keywords = (from keyword in keywords
                             let k = keyword.ToLowerInvariant()
                             orderby k
                             select k)
                         .Distinct()
                         .ToArray();
                 keyer.onKeywordRecognized.AddListener(OnKeyword);
             }
         }
References Juniper.Unity.Input.Speech.Keywordable.HasKeywords, Juniper.Unity.Input.Speech.Keywordable.keyer, Juniper.Unity.Input.Speech.Keywordable.keywords, Juniper.Unity.Input.Speech.Keywordable.OnKeyword(), and Juniper.Unity.Input.Speech.KeywordRecognizer.onKeywordRecognized.
Update()
void Juniper.Unity.Input.Speech.Keywordable.Update () inline
Check to see if the keyboard shortcut has been triggered.
Definition at line 74 of file Keywordable.cs.
         {
             if (shortcutKey != KeyCode.None && UnityEngine.Input.GetKeyDown(shortcutKey))
             {
                 OnKeyword();
             }
         }
References Juniper.Unity.Input.Speech.Keywordable.OnKeyword(), and Juniper.Unity.Input.Speech.Keywordable.shortcutKey.
Member Data Documentation
keyer
KeywordRecognizer Juniper.Unity.Input.Speech.Keywordable.keyer private
The main speech recognition manager.
Definition at line 99 of file Keywordable.cs.
Referenced by Juniper.Unity.Input.Speech.Keywordable.Awake(), Juniper.Unity.Input.Speech.Keywordable.OnEnable(), and Juniper.Unity.Input.Speech.Keywordable.Start().
keywords
string [] Juniper.Unity.Input.Speech.Keywordable.keywords
The keywords that activate this event.
Definition at line 21 of file Keywordable.cs.
Referenced by Juniper.Unity.Input.Speech.Keywordable.OnKeyword(), and Juniper.Unity.Input.Speech.Keywordable.Start().
onKeyword
UnityEvent Juniper.Unity.Input.Speech.Keywordable.onKeyword = new UnityEvent()
The event to trigger when the keyword is recognized. If you are programmatically wiring up events, prefer the Keyword event instead.
Definition at line 32 of file Keywordable.cs.
Referenced by Juniper.Unity.Input.Speech.Keywordable.OnKeyword().
shortcutKey
KeyCode Juniper.Unity.Input.Speech.Keywordable.shortcutKey = KeyCode.None
A keyboard shortcut to make development easier (and quieter, RE: open-floor plans).
Definition at line 26 of file Keywordable.cs.
Referenced by Juniper.Unity.Input.Speech.Keywordable.Update().
Property Documentation
HasKeywords
bool Juniper.Unity.Input.Speech.Keywordable.HasKeywords get private
Returns true when this component has more than one keyword defined and we were able to find the speech recognition manager.
true if has keywords; otherwise, false.
Definition at line 107 of file Keywordable.cs.
         {
             get
             {
                 return keywords != null && keywords.Length > 0 && keyer != null;
             }
         }
Referenced by Juniper.Unity.Input.Speech.Keywordable.OnEnable(), and Juniper.Unity.Input.Speech.Keywordable.Start().
Keywords
IEnumerable<string> Juniper.Unity.Input.Speech.Keywordable.Keywords get
The keywords that activate this event.
The keywords.
Definition at line 45 of file Keywordable.cs.
         {
             get
             {
                 return keywords;
             }
         }
Event Documentation
Keyword
EventHandler Juniper.Unity.Input.Speech.Keywordable.Keyword
The event to trigger when the keyword is recognized. If you are programmatically wiring up events, prefer this event over the onKeyword event.
Definition at line 38 of file Keywordable.cs.
Referenced by Juniper.Unity.Input.Speech.Keywordable.OnKeyword().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Speech/Keywordable.cs