Juniper: Juniper.Unity.AbstractStateController Class Reference
Juniper.Unity.AbstractStateController Class Reference
A subscene is a game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
Public Member Functions
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
virtual void Enter ()
Fire the OnEnable event and perform the Enter transition.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void Update ()
Checks to see if the state has changed and fires the right event for it.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
virtual void Exit ()
Fire the OnExiting event and perform the Exit transition.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Public Attributes
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Properties
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Attributes
Direction lastState
The value of state from the last frame, to check for changes in the value.
bool skipEvents
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
WaitUntil _waiter
Cached wait object, so we don't cause GC pressure recreating it all the time.
Detailed Description
A subscene is a game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
Definition at line 15 of file AbstractStateController.cs.
Member Function Documentation
Enter()
virtual void Juniper.Unity.AbstractStateController.Enter () inline virtual
Fire the OnEnable event and perform the Enter transition.
Reimplemented in Juniper.Unity.Animation.AbstractTransitionController, and Juniper.Unity.SubSceneController.
Definition at line 177 of file AbstractStateController.cs.
         {
             if (IsExited)
             {
                 state = Direction.Forward;
                 enabled = true;
                 this.SetTreeActive(true);
             }
         }
References Juniper.Unity.AbstractStateController.IsExited, and Juniper.Unity.AbstractStateController.state.
Exit()
virtual void Juniper.Unity.AbstractStateController.Exit () inline virtual
Fire the OnExiting event and perform the Exit transition.
Reimplemented in Juniper.Unity.Animation.AbstractTransitionController, and Juniper.Unity.SubSceneController.
Definition at line 267 of file AbstractStateController.cs.
         {
             if (IsEntered)
             {
                 state = Direction.Reverse;
                 OnExiting();
             }
         }
References Juniper.Unity.AbstractStateController.IsEntered, Juniper.Unity.AbstractStateController.OnExiting(), and Juniper.Unity.AbstractStateController.state.
HasCompleted()
bool Juniper.Unity.AbstractStateController.HasCompleted () inline
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 121 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.Unity.AbstractStateController.IsComplete.
OnDisable()
void Juniper.Unity.AbstractStateController.OnDisable () inline
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 298 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.Unity.AbstractStateController.OnExited().
OnEnable()
void Juniper.Unity.AbstractStateController.OnEnable () inline
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 193 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.Unity.AbstractStateController.OnEntering().
Referenced by Juniper.Unity.AbstractStateController.SkipEnter().
OnEntered()
virtual void Juniper.Unity.AbstractStateController.OnEntered () inline protected virtual
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 240 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntered?.Invoke();
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entered, Juniper.Unity.AbstractStateController.onEntered, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Update().
OnEntering()
virtual void Juniper.Unity.AbstractStateController.OnEntering () inline protected virtual
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 204 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntering?.Invoke();
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entering, Juniper.Unity.AbstractStateController.onEntering, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnEnable().
OnExited()
virtual void Juniper.Unity.AbstractStateController.OnExited () inline protected virtual
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, and Juniper.Unity.SubSceneController.
Definition at line 310 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExited?.Invoke();
                 Exited?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Exited, Juniper.Unity.AbstractStateController.onExited, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnDisable().
OnExiting()
virtual void Juniper.Unity.AbstractStateController.OnExiting () inline protected virtual
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 283 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExiting?.Invoke();
                 Exiting?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Exiting, Juniper.Unity.AbstractStateController.onExiting, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Exit(), and Juniper.Unity.AbstractStateController.SkipExit().
SkipEnter()
virtual void Juniper.Unity.AbstractStateController.SkipEnter () inline virtual
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Unity.Animation.AbstractTransitionController.
Definition at line 162 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Forward;
             OnEnable();
             lastState = Direction.Forward;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnEnable(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
SkipExit()
virtual void Juniper.Unity.AbstractStateController.SkipExit () inline virtual
Jump to the fully entered state without firing any events.
Definition at line 252 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnExiting(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
Update()
virtual void Juniper.Unity.AbstractStateController.Update () inline virtual
Checks to see if the state has changed and fires the right event for it.
Reimplemented in Juniper.Unity.Video.Video360, Juniper.Unity.Animation.AbstractTransitionController, Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.SubSceneController.
Definition at line 216 of file AbstractStateController.cs.
         {
             if (IsComplete && state != lastState)
             {
                 if (lastState == Direction.Forward)
                 {
                     OnEntered();
                 }
                 else if (lastState == Direction.Reverse)
                 {
                     enabled = false;
                 }
             }
             lastState = state;
         }
References Juniper.Unity.AbstractStateController.IsComplete, Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.AbstractStateController.state.
Referenced by Juniper.Unity.AbstractStateController.SkipEnter(), and Juniper.Unity.AbstractStateController.SkipExit().
Member Data Documentation
_waiter
WaitUntil Juniper.Unity.AbstractStateController._waiter private
Cached wait object, so we don't cause GC pressure recreating it all the time.
Definition at line 322 of file AbstractStateController.cs.
lastState
Direction Juniper.Unity.AbstractStateController.lastState private
The value of state from the last frame, to check for changes in the value.
Definition at line 99 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), and Juniper.Unity.AbstractStateController.Update().
onEntered
UnityEvent Juniper.Unity.AbstractStateController.onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 33 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.Unity.AbstractStateController.onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 24 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.Unity.AbstractStateController.onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 51 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.Unity.AbstractStateController.onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 42 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
skipEvents
bool Juniper.Unity.AbstractStateController.skipEvents private
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Definition at line 104 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered(), Juniper.Unity.AbstractStateController.OnEntering(), Juniper.Unity.AbstractStateController.OnExited(), Juniper.Unity.AbstractStateController.OnExiting(), Juniper.Unity.AbstractStateController.SkipEnter(), and Juniper.Unity.AbstractStateController.SkipExit().
state
Direction Juniper.Unity.AbstractStateController.state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 94 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), Juniper.Unity.Animation.AbstractTransitionController.Update(), and Juniper.Unity.AbstractStateController.Update().
Property Documentation
IsComplete
virtual bool Juniper.Unity.AbstractStateController.IsComplete get
Returns true when state is Direction.Stopped
Definition at line 110 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.HasCompleted(), and Juniper.Unity.AbstractStateController.Update().
IsEntered
bool Juniper.Unity.AbstractStateController.IsEntered get
Returns true when the state controller is in the "Entered" state.
Definition at line 141 of file AbstractStateController.cs.
         {
             get
             {
                 return enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Exit().
IsExited
bool Juniper.Unity.AbstractStateController.IsExited get
Returns true when the state controller is in the "Exited" state.
Definition at line 152 of file AbstractStateController.cs.
         {
             get
             {
                 return !enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Enter().
IsRunning
bool Juniper.Unity.AbstractStateController.IsRunning get
Returns true when state is not Direction.Stopped
Definition at line 130 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
Waiter
WaitUntil Juniper.Unity.AbstractStateController.Waiter get
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 329 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.Unity.AbstractStateController.Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 69 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.Unity.AbstractStateController.Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 60 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.Unity.AbstractStateController.Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 87 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.Unity.AbstractStateController.Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 78 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnExiting().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/AbstractStateController.cs