Juniper: Juniper.Imaging.IImageTranscoderExt Class Reference
Juniper.Imaging.IImageTranscoderExt Class Reference
Static Public Member Functions
static ToImageT Translate< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, FromImageT image)
static FromImageT Translate< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, ToImageT image)
static Task< ToImageT > TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, FromImageT image, IProgress prog)
static Task< ToImageT > TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, FromImageT image)
static Task< FromImageT > TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, ToImageT image, IProgress prog)
static Task< FromImageT > TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, ToImageT image)
Detailed Description
Definition at line 9 of file IImageTranscoderExt.cs.
Member Function Documentation
Translate< FromImageT, ToImageT >() [1/2]
static ToImageT Juniper.Imaging.IImageTranscoderExt.Translate< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, FromImageT image) inline static
Definition at line 11 of file IImageTranscoderExt.cs.
         {
             if (transcoder is null)
             {
                 throw new ArgumentNullException(nameof(transcoder));
             }
             return transcoder.Translate(image, null);
         }
References Juniper.Imaging.IImageTranscoder< FromImageT, ToImageT >.Translate().
Translate< FromImageT, ToImageT >() [2/2]
static FromImageT Juniper.Imaging.IImageTranscoderExt.Translate< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, ToImageT image) inline static
Definition at line 21 of file IImageTranscoderExt.cs.
         {
             if (transcoder is null)
             {
                 throw new ArgumentNullException(nameof(transcoder));
             }
             return transcoder.Translate(image, null);
         }
References Juniper.Imaging.IImageTranscoder< FromImageT, ToImageT >.Translate().
TranslateAsync< FromImageT, ToImageT >() [1/4]
static Task<ToImageT> Juniper.Imaging.IImageTranscoderExt.TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, FromImageT image, IProgress prog) inline static
Definition at line 31 of file IImageTranscoderExt.cs.
         {
             if (transcoder is null)
             {
                 throw new ArgumentNullException(nameof(transcoder));
             }
             return Task.Run(() => transcoder.Translate(image, prog));
         }
References Juniper.Imaging.IImageTranscoder< FromImageT, ToImageT >.Translate().
TranslateAsync< FromImageT, ToImageT >() [2/4]
static Task<ToImageT> Juniper.Imaging.IImageTranscoderExt.TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, FromImageT image) inline static
Definition at line 41 of file IImageTranscoderExt.cs.
         {
             if (transcoder is null)
             {
                 throw new ArgumentNullException(nameof(transcoder));
             }
             return transcoder.TranslateAsync(image, null);
         }
TranslateAsync< FromImageT, ToImageT >() [3/4]
static Task<FromImageT> Juniper.Imaging.IImageTranscoderExt.TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, ToImageT image, IProgress prog) inline static
Definition at line 51 of file IImageTranscoderExt.cs.
         {
             if (transcoder is null)
             {
                 throw new ArgumentNullException(nameof(transcoder));
             }
             return Task.Run(() => transcoder.Translate(image, prog));
         }
References Juniper.Imaging.IImageTranscoder< FromImageT, ToImageT >.Translate().
TranslateAsync< FromImageT, ToImageT >() [4/4]
static Task<FromImageT> Juniper.Imaging.IImageTranscoderExt.TranslateAsync< FromImageT, ToImageT > (this IImageTranscoder< FromImageT, ToImageT > transcoder, ToImageT image) inline static
Definition at line 61 of file IImageTranscoderExt.cs.
         {
             if (transcoder is null)
             {
                 throw new ArgumentNullException(nameof(transcoder));
             }
             return transcoder.TranslateAsync(image, null);
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Imaging/IImageTranscoderExt.cs