Juniper: Hjg.Pngcs.PngHelperInternal Class Reference
Hjg.Pngcs.PngHelperInternal Class Reference
Some utility static methods for internal use.
Static Public Member Functions
static CRC32 GetCRC ()
thread-singleton crc engine
static int DoubleToInt100000 (double d)
static double IntToDouble100000 (int i)
static void WriteInt2 (Stream os, int n)
static int ReadInt2 (Stream mask0)
-1 si eof
static int ReadInt4 (Stream mask0)
-1 si eof
static int ReadInt1fromByte (byte[] b, int offset)
static int ReadInt2fromBytes (byte[] b, int offset)
static int ReadInt4fromBytes (byte[] b, int offset)
static void WriteInt2tobytes (int n, byte[] b, int offset)
static void WriteInt4tobytes (int n, byte[] b, int offset)
static void WriteInt4 (Stream os, int n)
static void ReadBytes (Stream mask0, byte[] b, int offset, int len)
guaranteed to read exactly len bytes. throws error if it cant
static void SkipBytes (Stream ist, int len)
static void WriteBytes (Stream os, byte[] b)
static void WriteBytes (Stream os, byte[] b, int offset, int n)
static int ReadByte (Stream mask0)
static void WriteByte (Stream os, byte b)
static int UnfilterRowPaeth (int r, int a, int b, int c)
static int FilterPaethPredictor (int a, int b, int c)
Static Public Attributes
static readonly byte [] PNG_ID_SIGNATURE = { 256 - 119, 80, 78, 71, 13, 10, 26, 10 }
static readonly Encoding charsetLatin1 = Encoding.GetEncoding("ISO-8859-1")
Static Private Member Functions
static internal void Log (string p, Exception e)
Static Private Attributes
static CRC32 crc32Engine = null
Detailed Description
Some utility static methods for internal use.
Definition at line 12 of file PngHelperInternal.cs.
Member Function Documentation
DoubleToInt100000()
static int Hjg.Pngcs.PngHelperInternal.DoubleToInt100000 (double d) inline static
Definition at line 30 of file PngHelperInternal.cs.
         {
             return (int)((d * 100000.0) + 0.5);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk().
FilterPaethPredictor()
static int Hjg.Pngcs.PngHelperInternal.FilterPaethPredictor (int a, int b, int c) inline static
Definition at line 319 of file PngHelperInternal.cs.
         {
             // from http://www.libpng.org/pub/png/spec/1.2/PNG-Filters.html
             // a = left, b = above, c = upper left
             var p = a + b - c;// ; initial estimate
             var pa = p >= a ? p - a : a - p;
             var pb = p >= b ? p - b : b - p;
             var pc = p >= c ? p - c : c - p;
             // ; return nearest of a,b,c,
             // ; breaking ties in order a,b,c.
             if (pa <= pb && pa <= pc)
             {
                 return a;
             }
             else if (pb <= pc)
             {
                 return b;
             }
             else
             {
                 return c;
             }
         }
Referenced by Hjg.Pngcs.PngWriter.FilterRowPaeth(), Hjg.Pngcs.PngHelperInternal.UnfilterRowPaeth(), and Hjg.Pngcs.PngReader.UnfilterRowPaeth().
GetCRC()
static CRC32 Hjg.Pngcs.PngHelperInternal.GetCRC () inline static
thread-singleton crc engine
Definition at line 21 of file PngHelperInternal.cs.
         {
             return crc32Engine ??= new CRC32();
         }
References Hjg.Pngcs.PngHelperInternal.crc32Engine.
Referenced by Hjg.Pngcs.Chunks.ChunkRaw.ComputeCrc().
IntToDouble100000()
static double Hjg.Pngcs.PngHelperInternal.IntToDouble100000 (int i) inline static
Definition at line 35 of file PngHelperInternal.cs.
         {
             return i / 100000.0;
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkCHRM.ParseFromRaw().
Log()
static internal void Hjg.Pngcs.PngHelperInternal.Log (string p, Exception e) inline static private
Definition at line 343 of file PngHelperInternal.cs.
         {
             Console.Error.WriteLine(p);
             Console.Error.WriteLine(e.Message);
         }
ReadByte()
static int Hjg.Pngcs.PngHelperInternal.ReadByte (Stream mask0) inline static
Definition at line 280 of file PngHelperInternal.cs.
         {
             if (mask0 is null)
             {
                 throw new ArgumentNullException(nameof(mask0));
             }
             try
             {
                 return mask0.ReadByte();
             }
             catch (IOException e)
             {
                 throw new PngjOutputException(e);
             }
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkIHDR.ParseFromRaw().
ReadBytes()
static void Hjg.Pngcs.PngHelperInternal.ReadBytes (Stream mask0, byte [] b, int offset, int len) inline static
guaranteed to read exactly len bytes. throws error if it cant
Definition at line 171 of file PngHelperInternal.cs.
         {
             if (mask0 is null)
             {
                 throw new ArgumentNullException(nameof(mask0));
             }
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             if (len == 0)
             {
                 return;
             }
             try
             {
                 var read = 0;
                 while (read < len)
                 {
                     var n = mask0.Read(b, offset + read, len - read);
                     if (n < 1)
                     {
                         throw new Exception("error reading, " + n + " !=" + len);
                     }
                     read += n;
                 }
             }
             catch (IOException e)
             {
                 throw new PngjInputException("error reading", e);
             }
         }
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.Chunks.ChunkRaw.ReadChunkData(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadLastChunks(), and Hjg.Pngcs.PngReader.ReadRowRaw().
ReadInt1fromByte()
static int Hjg.Pngcs.PngHelperInternal.ReadInt1fromByte (byte [] b, int offset) inline static
Definition at line 104 of file PngHelperInternal.cs.
         {
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             return b[offset] & 0xff;
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkSBIT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkOFFS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkSRGB.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTIME.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkPHYS.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkSPLT.ParseFromRaw().
ReadInt2()
static int Hjg.Pngcs.PngHelperInternal.ReadInt2 (Stream mask0) inline static
-1 si eof
Definition at line 50 of file PngHelperInternal.cs.
         {
             if (mask0 is null)
             {
                 throw new ArgumentNullException(nameof(mask0));
             }
             try
             {
                 var b1 = mask0.ReadByte();
                 var b2 = mask0.ReadByte();
                 if (b1 == -1 || b2 == -1)
                 {
                     return -1;
                 }
                 return (b1 << 8) + b2;
             }
             catch (IOException e)
             {
                 throw new PngjInputException("error reading readInt2", e);
             }
         }
ReadInt2fromBytes()
static int Hjg.Pngcs.PngHelperInternal.ReadInt2fromBytes (byte [] b, int offset) inline static
Definition at line 114 of file PngHelperInternal.cs.
         {
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             return ((b[offset] & 0xff) << 16) | (b[offset + 1] & 0xff);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkTIME.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkHIST.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTRNS.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkSPLT.ParseFromRaw().
ReadInt4()
static int Hjg.Pngcs.PngHelperInternal.ReadInt4 (Stream mask0) inline static
-1 si eof
Definition at line 78 of file PngHelperInternal.cs.
         {
             if (mask0 is null)
             {
                 throw new ArgumentNullException(nameof(mask0));
             }
             try
             {
                 var b1 = mask0.ReadByte();
                 var b2 = mask0.ReadByte();
                 var b3 = mask0.ReadByte();
                 var b4 = mask0.ReadByte();
                 if (b1 == -1 || b2 == -1 || b3 == -1 || b4 == -1)
                 {
                     return -1;
                 }
                 return (b1 << 24) + (b2 << 16) + (b3 << 8) + b4;
             }
             catch (IOException e)
             {
                 throw new PngjInputException("error reading readInt4", e);
             }
         }
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.Chunks.PngChunkIHDR.ParseFromRaw(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.Chunks.ChunkRaw.ReadChunkData(), Hjg.Pngcs.PngReader.ReadFirstChunks(), and Hjg.Pngcs.PngReader.ReadLastChunks().
ReadInt4fromBytes()
static int Hjg.Pngcs.PngHelperInternal.ReadInt4fromBytes (byte [] b, int offset) inline static
Definition at line 124 of file PngHelperInternal.cs.
         {
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             return ((b[offset] & 0xff) << 24) | ((b[offset + 1] & 0xff) << 16)
                     | ((b[offset + 2] & 0xff) << 8) | (b[offset + 3] & 0xff);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkGAMA.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkOFFS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkCHRM.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkPHYS.ParseFromRaw().
SkipBytes()
static void Hjg.Pngcs.PngHelperInternal.SkipBytes (Stream ist, int len) inline static
Definition at line 208 of file PngHelperInternal.cs.
         {
             if (ist is null)
             {
                 throw new ArgumentNullException(nameof(ist));
             }
             var buf = new byte[8192 * 4];
             int read, remain = len;
             try
             {
                 while (remain > 0)
                 {
                     read = ist.Read(buf, 0, remain > buf.Length ? buf.Length : remain);
                     if (read < 0)
                     {
                         throw new PngjInputException("error reading (skipping) : EOF");
                     }
                     remain -= read;
                 }
             }
             catch (IOException e)
             {
                 throw new PngjInputException("error reading (skipping)", e);
             }
         }
Referenced by Hjg.Pngcs.PngReader.ReadChunk().
UnfilterRowPaeth()
static int Hjg.Pngcs.PngHelperInternal.UnfilterRowPaeth (int r, int a, int b, int c) inline static
Definition at line 314 of file PngHelperInternal.cs.
         { // a = left, b = above, c = upper left
             return (r + FilterPaethPredictor(a, b, c)) & 0xFF;
         }
References Hjg.Pngcs.PngHelperInternal.FilterPaethPredictor().
WriteByte()
static void Hjg.Pngcs.PngHelperInternal.WriteByte (Stream os, byte b) inline static
Definition at line 297 of file PngHelperInternal.cs.
         {
             if (os is null)
             {
                 throw new ArgumentNullException(nameof(os));
             }
             try
             {
                 os.WriteByte(b);
             }
             catch (IOException e)
             {
                 throw new PngjOutputException(e);
             }
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk().
WriteBytes() [1/2]
static void Hjg.Pngcs.PngHelperInternal.WriteBytes (Stream os, byte [] b) inline static
Definition at line 236 of file PngHelperInternal.cs.
         {
             if (os is null)
             {
                 throw new ArgumentNullException(nameof(os));
             }
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             try
             {
                 os.Write(b, 0, b.Length);
             }
             catch (IOException e)
             {
                 throw new PngjOutputException(e);
             }
         }
Referenced by Hjg.Pngcs.Chunks.ChunkRaw.WriteChunk(), Hjg.Pngcs.PngHelperInternal.WriteInt2(), Hjg.Pngcs.PngHelperInternal.WriteInt4(), and Hjg.Pngcs.PngWriter.WriteSignatureAndIHDR().
WriteBytes() [2/2]
static void Hjg.Pngcs.PngHelperInternal.WriteBytes (Stream os, byte [] b, int offset, int n) inline static
Definition at line 258 of file PngHelperInternal.cs.
         {
             if (os is null)
             {
                 throw new ArgumentNullException(nameof(os));
             }
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             try
             {
                 os.Write(b, offset, n);
             }
             catch (IOException e)
             {
                 throw new PngjOutputException(e);
             }
         }
WriteInt2()
static void Hjg.Pngcs.PngHelperInternal.WriteInt2 (Stream os, int n) inline static
Definition at line 40 of file PngHelperInternal.cs.
         {
             byte[] temp = { (byte)((n >> 8) & 0xff), (byte)(n & 0xff) };
             WriteBytes(os, temp);
         }
References Hjg.Pngcs.PngHelperInternal.WriteBytes().
Referenced by Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk().
WriteInt2tobytes()
static void Hjg.Pngcs.PngHelperInternal.WriteInt2tobytes (int n, byte [] b, int offset) inline static
Definition at line 135 of file PngHelperInternal.cs.
         {
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             b[offset] = (byte)((n >> 8) & 0xff);
             b[offset + 1] = (byte)(n & 0xff);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTIME.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk().
WriteInt4()
static void Hjg.Pngcs.PngHelperInternal.WriteInt4 (Stream os, int n) inline static
Definition at line 159 of file PngHelperInternal.cs.
         {
             var temp = new byte[4];
             WriteInt4tobytes(n, temp, 0);
             WriteBytes(os, temp);
             //Console.WriteLine("writing int " + n + " b=" + (sbyte)temp[0] + "," + (sbyte)temp[1] + "," + (sbyte)temp[2] + "," + (sbyte)temp[3]);
         }
References Hjg.Pngcs.PngHelperInternal.WriteBytes(), and Hjg.Pngcs.PngHelperInternal.WriteInt4tobytes().
Referenced by Hjg.Pngcs.Chunks.ChunkRaw.WriteChunk().
WriteInt4tobytes()
static void Hjg.Pngcs.PngHelperInternal.WriteInt4tobytes (int n, byte [] b, int offset) inline static
Definition at line 146 of file PngHelperInternal.cs.
         {
             if (b is null)
             {
                 throw new ArgumentNullException(nameof(b));
             }
             b[offset] = (byte)((n >> 24) & 0xff);
             b[offset + 1] = (byte)((n >> 16) & 0xff);
             b[offset + 2] = (byte)((n >> 8) & 0xff);
             b[offset + 3] = (byte)(n & 0xff);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkGAMA.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkOFFS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPHYS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkIHDR.CreateRawChunk(), and Hjg.Pngcs.PngHelperInternal.WriteInt4().
Member Data Documentation
charsetLatin1
readonly Encoding Hjg.Pngcs.PngHelperInternal.charsetLatin1 = Encoding.GetEncoding("ISO-8859-1") static
Definition at line 28 of file PngHelperInternal.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkTEXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTEXT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkICCP.ParseFromRaw(), Hjg.Pngcs.Chunks.ChunkHelper.ToBytes(), and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
crc32Engine
CRC32 Hjg.Pngcs.PngHelperInternal.crc32Engine = null static private
Definition at line 15 of file PngHelperInternal.cs.
Referenced by Hjg.Pngcs.PngHelperInternal.GetCRC().
PNG_ID_SIGNATURE
readonly byte [] Hjg.Pngcs.PngHelperInternal.PNG_ID_SIGNATURE = { 256 - 119, 80, 78, 71, 13, 10, 26, 10 } static
Definition at line 26 of file PngHelperInternal.cs.
Referenced by Hjg.Pngcs.PngReader.PngReader(), and Hjg.Pngcs.PngWriter.WriteSignatureAndIHDR().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/PngHelperInternal.cs