Juniper: Juniper.Animation.TranslationTransition Class Reference
Juniper.Animation.TranslationTransition Class Reference
Performs a sliding animation on scene transitions. The object's localPosition is the value that is changed, not the global world position.
Public Member Functions
override void Enter ()
Fire the OnEnable event and perform the Enter transition.
override void SkipEnter ()
override void Exit ()
Fire the OnExiting event and perform the Exit transition.
override void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
bool HasStopped ()
virtual void SkipExit ()
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Public Attributes
Vector3 Delta
The translation range the transition has to traverse.
float length = 0.25f
The amount of time it takes to complete the transition.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Protected Member Functions
virtual void Awake ()
Get the startPosition
override void RenderValue (float value)
Updates the localPosition of the transitioning object every frame the transition is active.
virtual void OnEnabled ()
virtual void OnDisabled ()
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Protected Attributes
const int ENTERING = 1
const int STOPPED = 0
const int EXITING = -1
int state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Properties
override float TransitionLength [get]
The amount of time it takes to complete the transition.
Vector3 EndPosition [get]
The location of the object after the transition has completed.
virtual bool IsComplete [get]
bool IsRunning [get]
WaitUntil Waiter [get]
Events
EventHandler< ValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Member Functions
void OnDrawGizmos ()
Draw the EndPosition to help visualize Delta.
Private Attributes
Vector3 startPosition
The location of the object when the object is first awoken.
Detailed Description
Performs a sliding animation on scene transitions. The object's localPosition is the value that is changed, not the global world position.
Definition at line 9 of file TranslationTransition.cs.
Member Function Documentation
Awake()
virtual void Juniper.Animation.TranslationTransition.Awake () inline protected virtual
Get the startPosition
Definition at line 52 of file TranslationTransition.cs.
         {
             startPosition = transform.localPosition;
         }
References Juniper.Animation.TranslationTransition.startPosition.
Enter()
override void Juniper.Animation.AbstractTransitionController.Enter () inline virtual inherited
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.FadeTransition.
Definition at line 60 of file AbstractTransitionController.cs.
         {
             StartTransition(ENTERING);
             base.Enter();
         }
References Juniper.AbstractStateController.ENTERING, and Juniper.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Widgets.Openable.SetOpen(), and Juniper.Animation.WorkflowStep.Show().
Exit()
override void Juniper.Animation.AbstractTransitionController.Exit () inline virtual inherited
Fire the OnExiting event and perform the Exit transition.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.FadeTransition.
Definition at line 74 of file AbstractTransitionController.cs.
         {
             StartTransition(EXITING);
             base.Exit();
         }
References Juniper.AbstractStateController.EXITING, and Juniper.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Widgets.Openable.SetOpen().
HasStopped()
bool Juniper.AbstractStateController.HasStopped () inline inherited
Definition at line 105 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.AbstractStateController.IsComplete.
OnDisable()
void Juniper.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 173 of file AbstractStateController.cs.
         {
             OnDisabled();
         }
References Juniper.AbstractStateController.OnDisabled().
OnDisabled()
virtual void Juniper.AbstractStateController.OnDisabled () inline protected virtual inherited
Reimplemented in Juniper.SubSceneController.
Definition at line 233 of file AbstractStateController.cs.
         {
             if (!skipEvent)
             {
                 OnExited();
             }
         }
References Juniper.AbstractStateController.OnExited(), and Juniper.AbstractStateController.skipEvent.
Referenced by Juniper.AbstractStateController.OnDisable().
OnDrawGizmos()
void Juniper.Animation.TranslationTransition.OnDrawGizmos () inline private
Draw the EndPosition to help visualize Delta.
Definition at line 62 of file TranslationTransition.cs.
         {
             Gizmos.DrawLine(transform.localPosition, EndPosition);
             Gizmos.DrawSphere(EndPosition, 0.1f);
         }
References Juniper.Animation.TranslationTransition.EndPosition.
OnEnable()
void Juniper.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 162 of file AbstractStateController.cs.
         {
             OnEnabled();
         }
References Juniper.AbstractStateController.OnEnabled().
Referenced by Juniper.AbstractStateController.Enter().
OnEnabled()
virtual void Juniper.AbstractStateController.OnEnabled () inline protected virtual inherited
Reimplemented in Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 225 of file AbstractStateController.cs.
         {
             if (!skipEvent)
             {
                 OnEntering();
             }
         }
References Juniper.AbstractStateController.OnEntering(), and Juniper.AbstractStateController.skipEvent.
Referenced by Juniper.AbstractStateController.OnEnable().
OnEntered()
virtual void Juniper.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Animation.FadeTransition.
Definition at line 260 of file AbstractStateController.cs.
         {
             onEntered?.Invoke();
             Entered?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.Entered, and Juniper.AbstractStateController.onEntered.
Referenced by Juniper.AbstractStateController.Update().
OnEntering()
virtual void Juniper.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 247 of file AbstractStateController.cs.
         {
             onEntering?.Invoke();
             Entering?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.Entering, and Juniper.AbstractStateController.onEntering.
Referenced by Juniper.AbstractStateController.OnEnabled().
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 286 of file AbstractStateController.cs.
         {
             onExited?.Invoke();
             Exited?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.Exited, and Juniper.AbstractStateController.onExited.
Referenced by Juniper.AbstractStateController.OnDisabled().
OnExiting()
virtual void Juniper.AbstractStateController.OnExiting () inline protected virtual inherited
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented in Juniper.Animation.FadeTransition, Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 273 of file AbstractStateController.cs.
         {
             onExiting?.Invoke();
             Exiting?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.Exiting, and Juniper.AbstractStateController.onExiting.
Referenced by Juniper.AbstractStateController.Exit().
RenderValue()
override void Juniper.Animation.TranslationTransition.RenderValue (float value) inline protected virtual
Updates the localPosition of the transitioning object every frame the transition is active.
Parameters
value
Implements Juniper.Animation.AbstractTransitionController.
Definition at line 74 of file TranslationTransition.cs.
         {
             transform.localPosition = Vector3.Lerp(startPosition, EndPosition, value);
         }
References Juniper.Animation.TranslationTransition.EndPosition, and Juniper.Animation.TranslationTransition.startPosition.
SkipEnter()
override void Juniper.Animation.AbstractTransitionController.SkipEnter () inline virtual inherited
Reimplemented from Juniper.AbstractStateController.
Definition at line 66 of file AbstractTransitionController.cs.
         {
             StartTransition(ENTERING);
             base.SkipEnter();
             SetProgress(0);
         }
References Juniper.AbstractStateController.ENTERING, Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.MasterSceneController.FadeOut().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Definition at line 146 of file AbstractStateController.cs.
         {
             skipEvent = true;
             Exit();
             Update();
             state = STOPPED;
             Update();
             skipEvent = false;
         }
References Juniper.AbstractStateController.Exit(), Juniper.AbstractStateController.skipEvent, Juniper.AbstractStateController.state, Juniper.AbstractStateController.STOPPED, and Juniper.AbstractStateController.Update().
Update()
override void Juniper.Animation.AbstractTransitionController.Update () inline virtual inherited
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.SpiralTransition.
Definition at line 84 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress > 0)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress - change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     SetProgress(0);
                     state = STOPPED;
                 }
             }
             base.Update();
         }
References Juniper.Animation.AbstractTransitionController.attack, Juniper.AbstractStateController.IsRunning, Juniper.Animation.AbstractTransitionController.progress, Juniper.Animation.AbstractTransitionController.release, Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.state, Juniper.AbstractStateController.STOPPED, and Juniper.Animation.AbstractTransitionController.TransitionLength.
Member Data Documentation
attackTime
float Juniper.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 18 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.StartTransition().
Delta
Vector3 Juniper.Animation.TranslationTransition.Delta
The translation range the transition has to traverse.
Definition at line 14 of file TranslationTransition.cs.
ENTERING
const int Juniper.AbstractStateController.ENTERING = 1 protected inherited
Definition at line 195 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Enter(), Juniper.AbstractStateController.Enter(), Juniper.Animation.AbstractTransitionController.SkipEnter(), Juniper.Animation.AbstractTransitionController.StartTransition(), Juniper.SubSceneController.Update(), and Juniper.AbstractStateController.Update().
EXITING
const int Juniper.AbstractStateController.EXITING = -1 protected inherited
Definition at line 199 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Exit(), Juniper.AbstractStateController.Exit(), Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.SubSceneController.Update(), and Juniper.AbstractStateController.Update().
length
float Juniper.Animation.TranslationTransition.length = 0.25f
The amount of time it takes to complete the transition.
Definition at line 19 of file TranslationTransition.cs.
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 33 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 24 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 51 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 42 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
onValueChanged
UnityEvent Juniper.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 31 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
releaseTime
float Juniper.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 25 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.StartTransition().
startPosition
Vector3 Juniper.Animation.TranslationTransition.startPosition private
The location of the object when the object is first awoken.
Definition at line 35 of file TranslationTransition.cs.
Referenced by Juniper.Animation.TranslationTransition.Awake(), and Juniper.Animation.TranslationTransition.RenderValue().
state
int Juniper.AbstractStateController.state protected inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 223 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.Exit(), Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), Juniper.Animation.AbstractTransitionController.StartTransition(), Juniper.SubSceneController.Update(), Juniper.Animation.AbstractTransitionController.Update(), and Juniper.AbstractStateController.Update().
STOPPED
const int Juniper.AbstractStateController.STOPPED = 0 protected inherited
Definition at line 197 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), Juniper.SubSceneController.Update(), and Juniper.Animation.AbstractTransitionController.Update().
tween
TweenType Juniper.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 36 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.StartTransition().
tweenK
float Juniper.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 43 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.SetProgress().
Property Documentation
EndPosition
Vector3 Juniper.Animation.TranslationTransition.EndPosition get private
The location of the object after the transition has completed.
The end position.
Definition at line 42 of file TranslationTransition.cs.
         {
             get
             {
                 return startPosition = Delta;
             }
         }
Referenced by Juniper.Animation.TranslationTransition.OnDrawGizmos(), and Juniper.Animation.TranslationTransition.RenderValue().
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get inherited
Definition at line 90 of file AbstractStateController.cs.
         {
             get
             {
                 return state == STOPPED;
             }
         }
Referenced by Juniper.AbstractStateController.HasStopped(), and Juniper.AbstractStateController.Update().
IsRunning
bool Juniper.AbstractStateController.IsRunning get inherited
Definition at line 98 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.SubSceneController.Update(), and Juniper.Animation.AbstractTransitionController.Update().
TransitionLength
override float Juniper.Animation.TranslationTransition.TransitionLength get
The amount of time it takes to complete the transition.
Definition at line 25 of file TranslationTransition.cs.
         {
             get
             {
                 return length;
             }
         }
Waiter
WaitUntil Juniper.AbstractStateController.Waiter get inherited
Definition at line 204 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(() => IsComplete);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 69 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 60 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 87 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 78 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
ValueChanged
EventHandler<ValueChangedEventArgs> Juniper.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 49 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Animation/TranslationTransition.cs