Juniper: System.Numerics.MathExt Class Reference
System.Numerics.MathExt Class Reference
Static Public Member Functions
static Juniper.Mathematics.Matrix3x2Serializable ToJuniperMatrix3x2Serializable (this Matrix3x2 v)
static Juniper.Mathematics.Matrix4x4Serializable ToJuniperMatrix4x4Serializable (this Matrix4x4 v)
static Accord.Math.Matrix4x4 ToAccordMatrix4x4 (this Matrix4x4 v)
static Juniper.Mathematics.Vector2Serializable ToJuniperVector2Serializable (this Vector2 v)
static Juniper.Mathematics.Vector3Serializable ToJuniperVector3Serializable (this Vector3 v)
static Accord.Math.Vector3 ToAccordVector3 (this Vector3 v)
static Juniper.Mathematics.Vector4Serializable ToJuniperVector4Serializable (this Vector4 v)
static Accord.Math.Vector4 ToAccordVector4 (this Vector4 v)
static Juniper.Mathematics.QuaternionSerializable ToJuniperQuaternionSerializable (this Quaternion q)
static Juniper.Mathematics.PlaneSerializable ToJuniperPlaneSerializable (this Plane p)
static Accord.Math.Plane ToAccordPlane (this Plane p)
static UnityEngine.Vector2 ToUnityVector2 (this Vector2 v)
static UnityEngine.Vector3 ToUnityVector3 (this Vector3 v)
static UnityEngine.Vector4 ToUnityVector4 (this Vector4 v)
static UnityEngine.Quaternion ToUnityQuaternion (this Quaternion q)
static UnityEngine.Matrix4x4 ToUnityMatrix4x4 (this Matrix4x4 m)
static UnityEngine.Plane ToUnityPlane (this Plane p)
Detailed Description
Definition at line 3 of file MathExt.cs.
Member Function Documentation
ToAccordMatrix4x4()
static Accord.Math.Matrix4x4 System.Numerics.MathExt.ToAccordMatrix4x4 (this Matrix4x4 v) inline static
Definition at line 22 of file MathExt.cs.
         {
             return new Accord.Math.Matrix4x4{
                 V00 = v.M11, V01 = v.M12, V02 = v.M13, V03 = v.M14,
                 V10 = v.M21, V11 = v.M22, V12 = v.M23, V13 = v.M24,
                 V20 = v.M31, V21 = v.M32, V22 = v.M33, V23 = v.M34,
                 V30 = v.M41, V31 = v.M42, V32 = v.M43, V33 = v.M44
             };
         }
ToAccordPlane()
static Accord.Math.Plane System.Numerics.MathExt.ToAccordPlane (this Plane p) inline static
Definition at line 67 of file MathExt.cs.
         {
             return new Accord.Math.Plane(p.Normal.ToAccordVector3(), p.D);
         }
ToAccordVector3()
static Accord.Math.Vector3 System.Numerics.MathExt.ToAccordVector3 (this Vector3 v) inline static
Definition at line 42 of file MathExt.cs.
         {
             return new Accord.Math.Vector3(v.X, v.Y, v.Z);
         }
ToAccordVector4()
static Accord.Math.Vector4 System.Numerics.MathExt.ToAccordVector4 (this Vector4 v) inline static
Definition at line 52 of file MathExt.cs.
         {
             return new Accord.Math.Vector4(v.X, v.Y, v.Z, v.W);
         }
ToJuniperMatrix3x2Serializable()
static Juniper.Mathematics.Matrix3x2Serializable System.Numerics.MathExt.ToJuniperMatrix3x2Serializable (this Matrix3x2 v) inline static
Definition at line 5 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Matrix3x2Serializable(
                 v.M11, v.M12,
                 v.M21, v.M22,
                 v.M31, v.M32);
         }
Referenced by Juniper.Mathematics.Matrix3x2Serializable.operator Matrix3x2Serializable().
ToJuniperMatrix4x4Serializable()
static Juniper.Mathematics.Matrix4x4Serializable System.Numerics.MathExt.ToJuniperMatrix4x4Serializable (this Matrix4x4 v) inline static
Definition at line 13 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Matrix4x4Serializable(
                 v.M11, v.M12, v.M13, v.M14,
                 v.M21, v.M22, v.M23, v.M24,
                 v.M31, v.M32, v.M33, v.M34,
                 v.M41, v.M42, v.M43, v.M44);
         }
Referenced by Juniper.Mathematics.Matrix4x4Serializable.operator Matrix4x4Serializable().
ToJuniperPlaneSerializable()
static Juniper.Mathematics.PlaneSerializable System.Numerics.MathExt.ToJuniperPlaneSerializable (this Plane p) inline static
Definition at line 62 of file MathExt.cs.
         {
             return new Juniper.Mathematics.PlaneSerializable(p.Normal.X, p.Normal.Y, p.Normal.Z, p.D);
         }
Referenced by Juniper.Mathematics.PlaneSerializable.operator PlaneSerializable().
ToJuniperQuaternionSerializable()
static Juniper.Mathematics.QuaternionSerializable System.Numerics.MathExt.ToJuniperQuaternionSerializable (this Quaternion q) inline static
Definition at line 57 of file MathExt.cs.
         {
             return new Juniper.Mathematics.QuaternionSerializable(q.X, q.Y, q.Z, q.W);
         }
Referenced by Juniper.Mathematics.QuaternionSerializable.operator QuaternionSerializable().
ToJuniperVector2Serializable()
static Juniper.Mathematics.Vector2Serializable System.Numerics.MathExt.ToJuniperVector2Serializable (this Vector2 v) inline static
Definition at line 32 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Vector2Serializable(v.X, v.Y);
         }
Referenced by Juniper.Mathematics.Vector2Serializable.operator Vector2Serializable().
ToJuniperVector3Serializable()
static Juniper.Mathematics.Vector3Serializable System.Numerics.MathExt.ToJuniperVector3Serializable (this Vector3 v) inline static
Definition at line 37 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Vector3Serializable(v.X, v.Y, v.Z);
         }
Referenced by Juniper.Mathematics.Vector3Serializable.operator Vector3Serializable().
ToJuniperVector4Serializable()
static Juniper.Mathematics.Vector4Serializable System.Numerics.MathExt.ToJuniperVector4Serializable (this Vector4 v) inline static
Definition at line 47 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Vector4Serializable(v.X, v.Y, v.Z, v.W);
         }
Referenced by Juniper.Mathematics.Vector4Serializable.operator Vector4Serializable().
ToUnityMatrix4x4()
static UnityEngine.Matrix4x4 System.Numerics.MathExt.ToUnityMatrix4x4 (this Matrix4x4 m) inline static
Definition at line 25 of file MathExt.cs.
         {
             return new UnityEngine.Matrix4x4
             {
                 m00 = m.M11, m01 = m.M12, m02 = m.M13, m03 = m.M14,
                 m10 = m.M21, m11 = m.M22, m12 = m.M23, m13 = m.M24,
                 m20 = m.M31, m21 = m.M32, m22 = m.M33, m23 = m.M34,
                 m30 = m.M41, m31 = m.M42, m32 = m.M43, m33 = m.M44
             };
         }
ToUnityPlane()
static UnityEngine.Plane System.Numerics.MathExt.ToUnityPlane (this Plane p) inline static
Definition at line 36 of file MathExt.cs.
         {
             return new UnityEngine.Plane(p.Normal.ToUnityVector3(), p.D);
         }
ToUnityQuaternion()
static UnityEngine.Quaternion System.Numerics.MathExt.ToUnityQuaternion (this Quaternion q) inline static
Definition at line 20 of file MathExt.cs.
         {
             return new UnityEngine.Quaternion(q.X, q.Y, q.Z, q.W);
         }
ToUnityVector2()
static UnityEngine.Vector2 System.Numerics.MathExt.ToUnityVector2 (this Vector2 v) inline static
Definition at line 5 of file MathExt.cs.
         {
             return new UnityEngine.Vector2(v.X, v.Y);
         }
ToUnityVector3()
static UnityEngine.Vector3 System.Numerics.MathExt.ToUnityVector3 (this Vector3 v) inline static
Definition at line 10 of file MathExt.cs.
         {
             return new UnityEngine.Vector3(v.X, v.Y, v.Z);
         }
ToUnityVector4()
static UnityEngine.Vector4 System.Numerics.MathExt.ToUnityVector4 (this Vector4 v) inline static
Definition at line 15 of file MathExt.cs.
         {
             return new UnityEngine.Vector4(v.X, v.Y, v.Z, v.W);
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/NETFX/Numerics/MathExt.cs