Juniper: Accord.Math.MathExt Class Reference
Accord.Math.MathExt Class Reference
Static Public Member Functions
static Juniper.Mathematics.Matrix4x4Serializable ToJuniperMatrix4x4Serializable (this Matrix4x4 v)
static System.Numerics.Matrix4x4 ToSystemMatrix4x4 (this Matrix4x4 v)
static Juniper.Mathematics.Vector3Serializable ToJuniperVector3Serializable (this Vector3 v)
static System.Numerics.Vector3 ToSystemVector3 (this Vector3 v)
static Juniper.Mathematics.Vector3Serializable ToJuniperVector3Serializable (this Point3 v)
static System.Numerics.Vector3 ToSystemVector3 (this Point3 v)
static Juniper.Mathematics.Vector4Serializable ToJuniperVector4Serializable (this Vector4 v)
static System.Numerics.Vector4 ToSystemVector4 (this Vector4 v)
static System.Numerics.Plane ToSystemPlane (this Plane p)
static Juniper.Mathematics.PlaneSerializable ToJuniperPlaneSerializable (this Plane p)
static UnityEngine.Vector3 ToUnityVector3 (this Vector3 v)
static UnityEngine.Vector3 ToUnityVector3 (this Point3 v)
static UnityEngine.Vector4 ToUnityVector4 (this Vector4 v)
static UnityEngine.Matrix4x4 ToUnityMatrix4x4 (this Matrix4x4 m)
static UnityEngine.Plane ToUnityPlane (this Plane p)
Detailed Description
Definition at line 5 of file MathExt.cs.
Member Function Documentation
ToJuniperMatrix4x4Serializable()
static Juniper.Mathematics.Matrix4x4Serializable Accord.Math.MathExt.ToJuniperMatrix4x4Serializable (this Matrix4x4 v) inline static
Definition at line 7 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Matrix4x4Serializable(
                 v.V00, v.V01, v.V02, v.V03,
                 v.V10, v.V11, v.V12, v.V13,
                 v.V20, v.V21, v.V22, v.V23,
                 v.V30, v.V31, v.V32, v.V33);
         }
Referenced by Juniper.Mathematics.Matrix4x4Serializable.operator Matrix4x4Serializable().
ToJuniperPlaneSerializable()
static Juniper.Mathematics.PlaneSerializable Accord.Math.MathExt.ToJuniperPlaneSerializable (this Plane p) inline static
Definition at line 60 of file MathExt.cs.
         {
             if (p is null)
             {
                 throw new ArgumentNullException(nameof(p));
             }
             return new Juniper.Mathematics.PlaneSerializable(p.A, p.B, p.C, p.Offset);
         }
Referenced by Juniper.Mathematics.PlaneSerializable.operator PlaneSerializable().
ToJuniperVector3Serializable() [1/2]
static Juniper.Mathematics.Vector3Serializable Accord.Math.MathExt.ToJuniperVector3Serializable (this Vector3 v) inline static
Definition at line 25 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Vector3Serializable(v.X, v.Y, v.Z);
         }
Referenced by Juniper.Mathematics.Vector3Serializable.operator Vector3Serializable().
ToJuniperVector3Serializable() [2/2]
static Juniper.Mathematics.Vector3Serializable Accord.Math.MathExt.ToJuniperVector3Serializable (this Point3 v) inline static
Definition at line 35 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Vector3Serializable(v.X, v.Y, v.Z);
         }
ToJuniperVector4Serializable()
static Juniper.Mathematics.Vector4Serializable Accord.Math.MathExt.ToJuniperVector4Serializable (this Vector4 v) inline static
Definition at line 45 of file MathExt.cs.
         {
             return new Juniper.Mathematics.Vector4Serializable(v.X, v.Y, v.Z, v.W);
         }
Referenced by Juniper.Mathematics.Vector4Serializable.operator Vector4Serializable().
ToSystemMatrix4x4()
static System.Numerics.Matrix4x4 Accord.Math.MathExt.ToSystemMatrix4x4 (this Matrix4x4 v) inline static
Definition at line 16 of file MathExt.cs.
         {
             return new System.Numerics.Matrix4x4(
                 v.V00, v.V01, v.V02, v.V03,
                 v.V10, v.V11, v.V12, v.V13,
                 v.V20, v.V21, v.V22, v.V23,
                 v.V30, v.V31, v.V32, v.V33);
         }
ToSystemPlane()
static System.Numerics.Plane Accord.Math.MathExt.ToSystemPlane (this Plane p) inline static
Definition at line 55 of file MathExt.cs.
         {
             return new System.Numerics.Plane(p.Normal.ToSystemVector3(), p.Offset);
         }
ToSystemVector3() [1/2]
static System.Numerics.Vector3 Accord.Math.MathExt.ToSystemVector3 (this Vector3 v) inline static
Definition at line 30 of file MathExt.cs.
         {
             return new System.Numerics.Vector3(v.X, v.Y, v.Z);
         }
ToSystemVector3() [2/2]
static System.Numerics.Vector3 Accord.Math.MathExt.ToSystemVector3 (this Point3 v) inline static
Definition at line 40 of file MathExt.cs.
         {
             return new System.Numerics.Vector3(v.X, v.Y, v.Z);
         }
ToSystemVector4()
static System.Numerics.Vector4 Accord.Math.MathExt.ToSystemVector4 (this Vector4 v) inline static
Definition at line 50 of file MathExt.cs.
         {
             return new System.Numerics.Vector4(v.X, v.Y, v.Z, v.W);
         }
ToUnityMatrix4x4()
static UnityEngine.Matrix4x4 Accord.Math.MathExt.ToUnityMatrix4x4 (this Matrix4x4 m) inline static
Definition at line 22 of file MathExt.cs.
         {
             return new UnityEngine.Matrix4x4
             {
                 m00 = m.V00, m01 = m.V01, m02 = m.V02, m03 = m.V03,
                 m10 = m.V10, m11 = m.V11, m12 = m.V12, m13 = m.V13,
                 m20 = m.V20, m21 = m.V21, m22 = m.V22, m23 = m.V23,
                 m30 = m.V30, m31 = m.V31, m32 = m.V32, m33 = m.V33
             };
         }
ToUnityPlane()
static UnityEngine.Plane Accord.Math.MathExt.ToUnityPlane (this Plane p) inline static
Definition at line 33 of file MathExt.cs.
         {
             if (p is null)
             {
                 throw new ArgumentNullException(nameof(p));
             }
             return new UnityEngine.Plane(p.Normal.ToUnityVector3(), p.Offset);
         }
ToUnityVector3() [1/2]
static UnityEngine.Vector3 Accord.Math.MathExt.ToUnityVector3 (this Vector3 v) inline static
Definition at line 7 of file MathExt.cs.
         {
             return new UnityEngine.Vector3(v.X, v.Y, v.Z);
         }
ToUnityVector3() [2/2]
static UnityEngine.Vector3 Accord.Math.MathExt.ToUnityVector3 (this Point3 v) inline static
Definition at line 12 of file MathExt.cs.
         {
             return new UnityEngine.Vector3(v.X, v.Y, v.Z);
         }
ToUnityVector4()
static UnityEngine.Vector4 Accord.Math.MathExt.ToUnityVector4 (this Vector4 v) inline static
Definition at line 17 of file MathExt.cs.
         {
             return new UnityEngine.Vector4(v.X, v.Y, v.Z, v.W);
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Accord/Math/MathExt.cs