Juniper: Juniper.Security.ICredentialReceiver Interface Reference
Juniper.Security.ICredentialReceiver Interface Reference
Public Member Functions
void ReceiveCredentials (string[] args)
Properties
string CredentialFile [get]
Detailed Description
Definition at line 3 of file ICredentialReceiver.cs.
Member Function Documentation
ReceiveCredentials()
void Juniper.Security.ICredentialReceiver.ReceiveCredentials (string [] args)
Implemented in Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.
Referenced by Juniper.Security.ICredentialReceiverExt.ClearCredentials(), Juniper.CredentialResolver.OnPreprocessBuild(), and Juniper.Security.ICredentialReceiverExt.ReceiveCredentials().
Property Documentation
CredentialFile
string Juniper.Security.ICredentialReceiver.CredentialFile get
Definition at line 5 of file ICredentialReceiver.cs.
 { get; }
Referenced by Juniper.Security.ICredentialReceiverExt.ReceiveCredentials().
The documentation for this interface was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Security/ICredentialReceiver.cs