Juniper: Juniper.Collections.Route< ValueT > Class Template Reference
Juniper.Collections.Route< ValueT > Class Template Reference
Public Member Functions
Route (float cost, ValueT firstNode, ValueT secondNode, params ValueT[] nodes)
void GetObjectData (SerializationInfo info, StreamingContext context)
override string ToString ()
override bool Equals (object obj)
bool Equals (Route< ValueT > other)
int CompareTo (object obj)
int CompareTo (Route< ValueT > other)
bool Contains (ValueT x)
bool Contains (Route< ValueT > other)
bool CanConnectTo (Route< ValueT > other)
bool Parallels (Route< ValueT > other)
bool Intersects (Route< ValueT > other)
override int GetHashCode ()
Static Public Member Functions
static Route< ValueT > operator+ (Route< ValueT > left, Route< ValueT > right)
static Route< ValueT > operator ~ (Route< ValueT > path)
static bool operator== (Route< ValueT > left, Route< ValueT > right)
static bool operator != (Route< ValueT > left, Route< ValueT > right)
static bool operator< (Route< ValueT > left, Route< ValueT > right)
static bool operator > (Route< ValueT > left, Route< ValueT > right)
static bool operator<= (Route< ValueT > left, Route< ValueT > right)
static bool operator >= (Route< ValueT > left, Route< ValueT > right)
Public Attributes
IReadOnlyList< ValueT > Nodes => nodes
int Count => nodes.Length
bool IsConnection => Count == 2
bool IsPath => Count > 2
ValueT Start => nodes.FirstOrDefault()
ValueT End => nodes.LastOrDefault()
Protected Member Functions
Route???? (SerializationInfo info, StreamingContext context)
Properties
float Cost [get]
internal bool IsValid [get]
Private Member Functions
Route (bool validate, IEnumerable< ValueT > edges, float cost)
bool Contain (Route< ValueT > other)
Private Attributes
readonly ValueT [] nodes
Detailed Description
Type Constraints
ValueT : IComparable<ValueT>
Definition at line 10 of file Route.cs.
Constructor & Destructor Documentation
Route() [1/2]
Juniper.Collections.Route< ValueT >.Route (bool validate, IEnumerable< ValueT > edges, float cost) inline private
Definition at line 119 of file Route.cs.
         {
             IsValid = true;
             nodes = edges.ToArray();
             if (!validate && nodes.Length < 2)
             {
                 IsValid = false;
             }
             for (var i = 0; i < nodes.Length - 1; ++i)
             {
                 for (var j = i + 1; j < nodes.Length; ++j)
                 {
                     if (nodes[i].Equals(nodes[j]))
                     {
                         if (validate)
{
                             throw new InvalidOperationException($"Edges must be a collection of distinct values. Found a duplicate at indices {i.ToString(CultureInfo.CurrentCulture)} and {j.ToString(CultureInfo.CurrentCulture)}");
                         }
                         else
{
                             IsValid = false;
                         }
                     }
                 }
             }
             Cost = cost;
         }
Route() [2/2]
Juniper.Collections.Route< ValueT >.Route (float cost, ValueT firstNode, ValueT secondNode, params ValueT [] nodes) inline
Definition at line 151 of file Route.cs.
             : this(true, nodes.Prepend(secondNode).Prepend(firstNode), cost)
         { }
Member Function Documentation
CanConnectTo()
bool Juniper.Collections.Route< ValueT >.CanConnectTo (Route< ValueT > other) inline
Definition at line 282 of file Route.cs.
         {
             return other is object
                 && (Start.Equals(other.Start)
                     || Start.Equals(other.End)
                     || End.Equals(other.Start)
                     || End.Equals(other.End))
                 && !Parallels(other)
                 && !Intersects(other);
         }
CompareTo() [1/2]
int Juniper.Collections.Route< ValueT >.CompareTo (object obj) inline
Definition at line 206 of file Route.cs.
         {
             return CompareTo(obj as Route<ValueT>);
         }
Referenced by Juniper.Collections.Route< NodeT >.CompareTo(), and Juniper.Collections.Route< NodeT >.Equals().
CompareTo() [2/2]
int Juniper.Collections.Route< ValueT >.CompareTo (Route< ValueT > other) inline
Definition at line 211 of file Route.cs.
         {
             if (other is null)
             {
                 return -1;
             }
             else if (Parallels(other))
             {
                 if (Cost == other.Cost)
                 {
                     return Count.CompareTo(other.Count);
                 }
                 else
                 {
                     return Cost.CompareTo(other.Cost);
                 }
             }
             else if (End.Equals(other.End))
             {
                 return Start.CompareTo(other.Start);
             }
             else
             {
                 return End.CompareTo(other.End);
             }
         }
Contain()
bool Juniper.Collections.Route< ValueT >.Contain (Route< ValueT > other) inline private
Definition at line 255 of file Route.cs.
         {
             var offset = Array.IndexOf(nodes, other.nodes[0]);
             if (offset == -1)
             {
                 return false;
             }
             var end = offset + other.Count - 1;
             if (!(0 <= end && end < nodes.Length))
             {
                 return false;
             }
             for (var i = 0; i < other.Count; ++i)
             {
                 var a = nodes[i + offset];
                 var b = other.nodes[i];
                 if (!a.Equals(b))
                 {
                     return false;
                 }
             }
             return true;
         }
Referenced by Juniper.Collections.Route< NodeT >.Contains().
Contains() [1/2]
bool Juniper.Collections.Route< ValueT >.Contains (ValueT x) inline
Definition at line 238 of file Route.cs.
         {
             return nodes.Contains(x);
         }
Contains() [2/2]
bool Juniper.Collections.Route< ValueT >.Contains (Route< ValueT > other) inline
Definition at line 243 of file Route.cs.
         {
             if (other is null
                 || nodes.Length < other.Count)
             {
                 return false;
             }
             return Contain(other)
                 || Contain(~other);
         }
Equals() [1/2]
override bool Juniper.Collections.Route< ValueT >.Equals (object obj) inline
Definition at line 195 of file Route.cs.
         {
             return obj is Route<ValueT> other
                 && Equals(other);
         }
Referenced by Juniper.Collections.Route< NodeT >.Equals(), and Juniper.Collections.Route< NodeT >.Route().
Equals() [2/2]
bool Juniper.Collections.Route< ValueT >.Equals (Route< ValueT > other) inline
Definition at line 201 of file Route.cs.
         {
             return CompareTo(other) == 0;
         }
GetHashCode()
override int Juniper.Collections.Route< ValueT >.GetHashCode () inline
Definition at line 329 of file Route.cs.
         {
             var hashCode = 1944944578;
             hashCode = (hashCode * -1521134295) + Cost.GetHashCode();
             var nodes = this.nodes.AsEnumerable();
             if(Start.CompareTo(End) > 0)
             {
                 nodes = nodes.Reverse();
             }
             foreach (var node in nodes)
             {
                 hashCode = (hashCode * -1521134295) + EqualityComparer<ValueT>.Default.GetHashCode(node);
             }
             return hashCode;
         }
GetObjectData()
void Juniper.Collections.Route< ValueT >.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 162 of file Route.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(nameof(Cost), Cost);
             info.AddValue(nameof(nodes), nodes);
         }
Intersects()
bool Juniper.Collections.Route< ValueT >.Intersects (Route< ValueT > other) inline
Definition at line 300 of file Route.cs.
         {
             if (other is null)
             {
                 return false;
             }
             else
             {
                 for (var i = 0; i < nodes.Length; ++i)
                 {
                     var a = nodes[i];
                     var isInternalA = i != 0 && i != nodes.Length - 1;
                     for (var j = 0; j < other.nodes.Length; ++j)
                     {
                         var b = other.nodes[j];
                         var isInternalB = j != 0 && j != other.nodes.Length - 1;
                         if (a.Equals(b)
                             && (isInternalA
                                 || isInternalB))
{
                             return true;
                         }
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Collections.Route< NodeT >.CanConnectTo().
operator !=()
static bool Juniper.Collections.Route< ValueT >.operator != (Route< ValueT > left, Route< ValueT > right) inline static
Definition at line 90 of file Route.cs.
         {
             return !(left == right);
         }
operator >()
static bool Juniper.Collections.Route< ValueT >.operator > (Route< ValueT > left, Route< ValueT > right) inline static
Definition at line 101 of file Route.cs.
         {
             return (left is object && left.CompareTo(right) == 1)
                 || (right is object && right.CompareTo(left) == -1);
         }
operator >=()
static bool Juniper.Collections.Route< ValueT >.operator >= (Route< ValueT > left, Route< ValueT > right) inline static
Definition at line 112 of file Route.cs.
         {
             return left > right || left == right;
         }
operator ~()
static Route<ValueT> Juniper.Collections.Route< ValueT >.operator ~ (Route< ValueT > path) inline static
Definition at line 73 of file Route.cs.
         {
             if (path is null)
             {
                 return null;
             }
             return new Route<ValueT>(true, path.nodes.Reverse(), path.Cost);
         }
operator+()
static Route<ValueT> Juniper.Collections.Route< ValueT >.operator+ (Route< ValueT > left, Route< ValueT > right) inline static
Definition at line 17 of file Route.cs.
         {
             if (left is null)
             {
                 throw new ArgumentNullException(nameof(left));
             }
             if (right is null)
             {
                 throw new ArgumentNullException(nameof(right));
             }
             if (!left.CanConnectTo(right))
             {
                 if (left.Intersects(right))
                 {
                     throw new InvalidOperationException($"The provided routes overlap:\n\t{left}\n\t{right}");
                 }
                 else if (left.Parallels(right))
                 {
                     throw new InvalidOperationException($"The provided routes start and end at the same location:\n\t{left}\n\t{right}");
                 }
                 else
                 {
                     throw new InvalidOperationException($"The ends of the provided routes do not match:\n\t{left}\n\t{right}");
                 }
             }
             var newNodes = new ValueT[left.Count + right.Count - 1];
             var reverseNodes = left.Start.Equals(right.Start) || left.Start.Equals(right.End);
             var reverseExtra = left.Start.Equals(right.Start) || left.End.Equals(right.End);
             reverseExtra = reverseExtra != reverseNodes;
             Array.Copy(left.nodes, newNodes, left.Count);
             if (reverseNodes)
             {
                 Array.Reverse(newNodes, 0, left.Count);
             }
             Array.Copy(
                 right.nodes,
                 reverseExtra
                     ? 0
                     : 1,
                 newNodes,
                 left.Count,
                 right.Count - 1);
             if (reverseExtra)
             {
                 Array.Reverse(newNodes, left.Count, right.Count - 1);
             }
             return new Route<ValueT>(false, newNodes, left.Cost + right.Cost);
         }
operator<()
static bool Juniper.Collections.Route< ValueT >.operator< (Route< ValueT > left, Route< ValueT > right) inline static
Definition at line 95 of file Route.cs.
         {
             return (left is object && left.CompareTo(right) == -1)
                 || (right is object && right.CompareTo(left) == 1);
         }
operator<=()
static bool Juniper.Collections.Route< ValueT >.operator<= (Route< ValueT > left, Route< ValueT > right) inline static
Definition at line 107 of file Route.cs.
         {
             return left < right || left == right;
         }
operator==()
static bool Juniper.Collections.Route< ValueT >.operator== (Route< ValueT > left, Route< ValueT > right) inline static
Definition at line 83 of file Route.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.CompareTo(right) == 0)
                 || (right is object && right.CompareTo(left) == 0);
         }
Parallels()
bool Juniper.Collections.Route< ValueT >.Parallels (Route< ValueT > other) inline
Definition at line 293 of file Route.cs.
         {
             return other is object
                 && ((Start.Equals(other.Start) && End.Equals(other.End))
                     || (Start.Equals(other.End) && End.Equals(other.Start)));
         }
Referenced by Juniper.Collections.Route< NodeT >.CanConnectTo(), and Juniper.Collections.Route< NodeT >.CompareTo().
Route????()
Juniper.Collections.Route< ValueT >.Route???? (SerializationInfo info, StreamingContext context) inline protected
Definition at line 156 of file Route.cs.
             : this(false,
                 info?.GetValue<ValueT[]>(nameof(nodes)),
                 info?.GetSingle(nameof(Cost)) ?? throw new ArgumentNullException(nameof(info)))
         { }
ToString()
override string Juniper.Collections.Route< ValueT >.ToString () inline
Definition at line 173 of file Route.cs.
         {
             var pathString = string.Join(" -> ", nodes);
             return $"[{Cost.ToString(CultureInfo.CurrentCulture)}] {pathString}";
         }
Member Data Documentation
Count
int Juniper.Collections.Route< ValueT >.Count => nodes.Length
Definition at line 183 of file Route.cs.
Referenced by Juniper.Collections.Route< NodeT >.CompareTo(), Juniper.Collections.Route< NodeT >.Contain(), and Juniper.Collections.Route< NodeT >.Contains().
End
ValueT Juniper.Collections.Route< ValueT >.End => nodes.LastOrDefault()
Definition at line 193 of file Route.cs.
Referenced by Juniper.Collections.Route< NodeT >.CanConnectTo(), Juniper.Collections.Route< NodeT >.CompareTo(), Juniper.Collections.Route< NodeT >.GetHashCode(), and Juniper.Collections.Route< NodeT >.Parallels().
IsConnection
bool Juniper.Collections.Route< ValueT >.IsConnection => Count == 2
Definition at line 187 of file Route.cs.
IsPath
bool Juniper.Collections.Route< ValueT >.IsPath => Count > 2
Definition at line 189 of file Route.cs.
nodes
readonly ValueT [] Juniper.Collections.Route< ValueT >.nodes private
Definition at line 117 of file Route.cs.
Referenced by Juniper.Collections.Route< NodeT >.Contain(), Juniper.Collections.Route< NodeT >.Contains(), Juniper.Collections.Route< NodeT >.GetHashCode(), Juniper.Collections.Route< NodeT >.GetObjectData(), Juniper.Collections.Route< NodeT >.Intersects(), Juniper.Collections.Route< NodeT >.operator ~(), Juniper.Collections.Route< NodeT >.Route(), and Juniper.Collections.Route< NodeT >.ToString().
Nodes
IReadOnlyList<ValueT> Juniper.Collections.Route< ValueT >.Nodes => nodes
Definition at line 181 of file Route.cs.
Start
ValueT Juniper.Collections.Route< ValueT >.Start => nodes.FirstOrDefault()
Definition at line 191 of file Route.cs.
Referenced by Juniper.Collections.Route< NodeT >.CanConnectTo(), Juniper.Collections.Route< NodeT >.CompareTo(), Juniper.Collections.Route< NodeT >.GetHashCode(), and Juniper.Collections.Route< NodeT >.Parallels().
Property Documentation
Cost
float Juniper.Collections.Route< ValueT >.Cost get
Definition at line 179 of file Route.cs.
 { get; }
Referenced by Juniper.Collections.Route< NodeT >.CompareTo(), Juniper.Collections.Route< NodeT >.GetHashCode(), Juniper.Collections.Route< NodeT >.GetObjectData(), Juniper.Collections.Route< NodeT >.operator ~(), and Juniper.Collections.Route< NodeT >.Route().
IsValid
internal bool Juniper.Collections.Route< ValueT >.IsValid get private
Definition at line 185 of file Route.cs.
 { get; }
Referenced by Juniper.Collections.Route< NodeT >.Route().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Collections/Route.cs