Juniper: Juniper.Unity.Input.OculusInputModule Class Reference
Juniper.Unity.Input.OculusInputModule Class Reference
Public Member Functions
override bool Install (bool reset)
Install, with or without a full reset.
override void Uninstall ()
Remove platform-specific features from the object.
void AddPointer (IPointerDevice pointer)
void WithPointer (Action< IPointerDevice > onPointerAvailable)
virtual void Reinstall ()
Reinstall the object with a full reset.
T MakePointer< T > (Transform parent, string path)
override void Process ()
Find all the pointers and fire raycaster events for them.
PointerEventData Clone (int pointerDataID, PointerEventData original)
void EnableMouse (bool value)
void EnableGaze (bool value)
void EnableTouch (bool value)
void EnableHands (bool value)
void EnableControllers (bool value)
Public Attributes
readonly List< IPointerDevice > Devices = new List<IPointerDevice>()
GameObject pointerPrefab
Set to the clonable object that should be used for the pointer probe.
PointerFoundEvent onPointerFound
Toggle enableControllersToggle
Toggle enableMouseToggle
Toggle enableTouchToggle
Toggle enableHandsToggle
Toggle enableGazeToggle
GazePointer gazePointer
Mouse mouse
TouchPoint [] touches
MotionController [] motionControllers
HandTracker [] handTrackers
Protected Member Functions
override void Awake ()
Protected Attributes
StageExtensions stage
Properties
bool AnyPointerDragging [get]
Events
EventHandler< PointerFoundEventArgs > PointerFound
Detailed Description
Definition at line 10 of file OculusInputModule.cs.
Member Function Documentation
AddPointer()
void Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer (IPointerDevice pointer) inline inherited
Definition at line 67 of file AbstractUnifiedInputModule.cs.
         {
             if (!Devices.Contains(pointer) && !newDevices.Contains(pointer))
             {
                 newDevices.Add(pointer);
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, and Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Start().
Awake()
override void Juniper.Unity.Input.AbstractUnifiedInputModule.Awake () inline protected inherited
Definition at line 100 of file AbstractUnifiedInputModule.cs.
         {
             base.Awake();
             Install(false);
 #if UNITY_MODULES_UI
             if (enableGazeToggle != null)
             {
                 enableGazeToggle.onValueChanged.AddListener(EnableGaze);
                 enableGazeToggle.isOn = PlayerPrefs.GetInt(ENABLE_GAZE_KEY, 0) == 1;
                 gazePointer.SetActive(enableGazeToggle.isOn);
             }
             if (enableHandsToggle != null)
             {
                 enableHandsToggle.onValueChanged.AddListener(EnableHands);
                 enableHandsToggle.isOn = PlayerPrefs.GetInt(ENABLE_HANDS_KEY, 0) == 1;
                 foreach (var handTracker in handTrackers)
                 {
                     handTracker.SetActive(enableHandsToggle.isOn);
                 }
             }
             if (enableControllersToggle != null)
             {
                 enableControllersToggle.onValueChanged.AddListener(EnableControllers);
                 enableControllersToggle.isOn = PlayerPrefs.GetInt(ENABLE_CONTROLLERS_KEY, 1) == 1;
                 foreach (var motionController in motionControllers)
                 {
                     motionController.SetActive(enableControllersToggle.isOn);
                 }
             }
             if (enableMouseToggle != null)
             {
                 enableMouseToggle.onValueChanged.AddListener(EnableMouse);
                 enableMouseToggle.isOn = PlayerPrefs.GetInt(ENABLE_MOUSE_KEY, 1) == 1;
                 mouse.SetActive(enableMouseToggle.isOn);
             }
             if (enableTouchToggle != null)
             {
                 enableTouchToggle.onValueChanged.AddListener(EnableTouch);
                 enableTouchToggle.isOn = PlayerPrefs.GetInt(ENABLE_TOUCH_KEY, Application.isMobilePlatform ? 1 : 0) == 1;
                 foreach (var touch in touches)
                 {
                     touch.SetActive(enableTouchToggle.isOn);
                 }
             }
 #endif
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_CONTROLLERS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_GAZE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_HANDS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_MOUSE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_TOUCH_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableControllersToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableGazeToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableHandsToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableMouseToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableTouchToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.gazePointer, Juniper.Unity.Input.AbstractUnifiedInputModule.handTrackers, Juniper.Unity.Input.AbstractUnifiedInputModule.Install(), Juniper.Unity.Input.AbstractUnifiedInputModule.motionControllers, Juniper.Unity.Input.AbstractUnifiedInputModule.mouse, and Juniper.Unity.Input.AbstractUnifiedInputModule.touches.
Clone()
PointerEventData Juniper.Unity.Input.AbstractUnifiedInputModule.Clone (int pointerDataID, PointerEventData original) inline inherited
Definition at line 292 of file AbstractUnifiedInputModule.cs.
         {
             PointerEventData clone;
             GetPointerData(pointerDataID, out clone, true);
             clone.delta = original.delta;
             clone.position = original.position;
             clone.scrollDelta = original.scrollDelta;
             clone.pointerEnter = original.pointerEnter;
             clone.useDragThreshold = original.useDragThreshold;
             clone.pointerCurrentRaycast = original.pointerCurrentRaycast;
             if (original.clickCount == -1)
             {
                 clone.eligibleForClick = false;
                 clone.clickCount = 0;
             }
             return clone;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone().
EnableControllers()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers (bool value) inline inherited
Definition at line 435 of file AbstractUnifiedInputModule.cs.
         {
             foreach (var motionController in motionControllers)
             {
                 motionController.SetActive(value);
             }
             if(enableControllersToggle != null && enableControllersToggle.isOn != value)
             {
                 enableControllersToggle.isOn = value;
             }
             PlayerPrefs.SetInt(ENABLE_CONTROLLERS_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_CONTROLLERS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.enableControllersToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.motionControllers.
Referenced by Juniper.Unity.Input.AbstractMobileInputModule.Awake(), Juniper.Unity.Input.MagicLeapInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Awake().
EnableGaze()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze (bool value) inline inherited
Definition at line 396 of file AbstractUnifiedInputModule.cs.
         {
             gazePointer.SetActive(value);
             if (enableGazeToggle != null && enableGazeToggle.isOn != value)
             {
                 enableGazeToggle.isOn = value;
             }
             PlayerPrefs.SetInt(ENABLE_GAZE_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_GAZE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.enableGazeToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.gazePointer.
Referenced by Juniper.Unity.Input.AbstractMobileInputModule.Awake(), Juniper.Unity.Input.MagicLeapInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Awake().
EnableHands()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands (bool value) inline inherited
Definition at line 421 of file AbstractUnifiedInputModule.cs.
         {
             foreach (var handTracker in handTrackers)
             {
                 handTracker.SetActive(value);
             }
             if (enableHandsToggle != null && enableHandsToggle.isOn != value)
             {
                 enableHandsToggle.isOn = value;
             }
             PlayerPrefs.SetInt(ENABLE_HANDS_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_HANDS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.enableHandsToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.handTrackers.
Referenced by Juniper.Unity.Input.AbstractMobileInputModule.Awake(), Juniper.Unity.Input.MagicLeapInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Awake().
EnableMouse()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse (bool value) inline inherited
Definition at line 385 of file AbstractUnifiedInputModule.cs.
         {
             mouse.SetActive(value);
             if (enableMouseToggle != null && enableMouseToggle.isOn != value)
             {
                 enableMouseToggle.isOn = value;
             }
             PlayerPrefs.SetInt(ENABLE_MOUSE_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_MOUSE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.enableMouseToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.mouse.
Referenced by Juniper.Unity.Input.AbstractMobileInputModule.Awake(), Juniper.Unity.Input.MagicLeapInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Awake().
EnableTouch()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch (bool value) inline inherited
Definition at line 407 of file AbstractUnifiedInputModule.cs.
         {
             foreach (var touch in touches)
             {
                 touch.SetActive(value);
             }
             if (enableTouchToggle != null && enableTouchToggle.isOn != value)
             {
                 enableTouchToggle.isOn = value;
             }
             PlayerPrefs.SetInt(ENABLE_TOUCH_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_TOUCH_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.enableTouchToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.touches.
Referenced by Juniper.Unity.Input.AbstractMobileInputModule.Awake(), Juniper.Unity.Input.MagicLeapInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Awake().
Install()
override bool Juniper.Unity.Input.OculusInputModule.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfuly. False if the installable should be recycled and tried again.
Reimplemented from Juniper.Unity.Input.AbstractUnifiedInputModule.
Definition at line 12 of file OculusInputModule.cs.
         {
             var baseInstall = base.Install(reset);
             this.EnsureComponent<OVRManager>();
             return baseInstall;
         }
MakePointer< T >()
T Juniper.Unity.Input.AbstractUnifiedInputModule.MakePointer< T > (Transform parent, string path) inline inherited
Type Constraints
T : Component
T : IPointerDevice
Definition at line 199 of file AbstractUnifiedInputModule.cs.
                     : Component, IPointerDevice
         {
             return parent.EnsureTransform(path)
                 .EnsureComponent<T>();
         }
Process()
override void Juniper.Unity.Input.AbstractUnifiedInputModule.Process () inline inherited
Find all the pointers and fire raycaster events for them.
Definition at line 265 of file AbstractUnifiedInputModule.cs.
         {
             foreach (var pointer in newDevices)
             {
                 Devices.Add(pointer);
                 OnPointerFound(pointer);
             }
             newDevices.Clear();
             foreach (var pointer in Devices)
             {
                 if (pointer.IsEnabled)
                 {
                     PointerEventData evtData;
                     GetPointerData(pointer.PointerDataID, out evtData, true);
                     evtData.delta = pointer.ScreenDelta;
                     evtData.position = pointer.ScreenPoint;
                     evtData.scrollDelta = pointer.ScrollDelta;
                     evtData.useDragThreshold = eventSystem.pixelDragThreshold > 0;
                     evtData.pointerCurrentRaycast = UpdateRay(pointer, evtData);
                     pointer.Process(evtData, eventSystem.pixelDragThreshold * eventSystem.pixelDragThreshold);
                 }
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices, Juniper.Unity.Input.AbstractUnifiedInputModule.OnPointerFound(), and Juniper.Unity.Input.AbstractUnifiedInputModule.UpdateRay().
Reinstall()
virtual void Juniper.Unity.Input.AbstractUnifiedInputModule.Reinstall () inline virtual inherited
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 153 of file AbstractUnifiedInputModule.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
Uninstall()
override void Juniper.Unity.Input.OculusInputModule.Uninstall () inline virtual
Remove platform-specific features from the object.
Reimplemented from Juniper.Unity.Input.AbstractUnifiedInputModule.
Definition at line 21 of file OculusInputModule.cs.
         {
             base.Uninstall();
             this.RemoveComponent<OVRManager>();
         }
WithPointer()
void Juniper.Unity.Input.AbstractUnifiedInputModule.WithPointer (Action< IPointerDevice > onPointerAvailable) inline inherited
Definition at line 75 of file AbstractUnifiedInputModule.cs.
         {
             if (Devices.Count > 0)
             {
                 onPointerAvailable(Devices[0]);
             }
             else
             {
                 EventHandler<PointerFoundEventArgs> subAct = null;
                 subAct = new EventHandler<PointerFoundEventArgs>((sender, args) =>
                 {
                     PointerFound -= subAct;
                     onPointerAvailable(args.device);
                 });
                 PointerFound += subAct;
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, and Juniper.Unity.Input.AbstractUnifiedInputModule.PointerFound.
Referenced by Juniper.Unity.Input.HoverCraft.Awake().
Member Data Documentation
Devices
readonly List<IPointerDevice> Juniper.Unity.Input.AbstractUnifiedInputModule.Devices = new List<IPointerDevice>() inherited
Definition at line 21 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.AbstractUnifiedInputModule.WithPointer().
enableControllersToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableControllersToggle inherited
Definition at line 54 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers().
enableGazeToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableGazeToggle inherited
Definition at line 58 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze().
enableHandsToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableHandsToggle inherited
Definition at line 57 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands().
enableMouseToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableMouseToggle inherited
Definition at line 55 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse().
enableTouchToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableTouchToggle inherited
Definition at line 56 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch().
gazePointer
GazePointer Juniper.Unity.Input.AbstractUnifiedInputModule.gazePointer inherited
Definition at line 61 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
handTrackers
HandTracker [] Juniper.Unity.Input.AbstractUnifiedInputModule.handTrackers inherited
Definition at line 65 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
motionControllers
MotionController [] Juniper.Unity.Input.AbstractUnifiedInputModule.motionControllers inherited
Definition at line 64 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
mouse
Mouse Juniper.Unity.Input.AbstractUnifiedInputModule.mouse inherited
Definition at line 62 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
onPointerFound
PointerFoundEvent Juniper.Unity.Input.AbstractUnifiedInputModule.onPointerFound inherited
Definition at line 44 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.OnPointerFound().
pointerPrefab
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.pointerPrefab inherited
Set to the clonable object that should be used for the pointer probe.
Definition at line 42 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
stage
StageExtensions Juniper.Unity.Input.AbstractUnifiedInputModule.stage protected inherited
Definition at line 98 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
touches
TouchPoint [] Juniper.Unity.Input.AbstractUnifiedInputModule.touches inherited
Definition at line 63 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
Property Documentation
AnyPointerDragging
bool Juniper.Unity.Input.AbstractUnifiedInputModule.AnyPointerDragging get inherited
Definition at line 24 of file AbstractUnifiedInputModule.cs.
         {
             get
             {
                 foreach (var device in Devices)
                 {
                     if (device.IsDragging)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Unity.Input.CameraControl.Update().
Event Documentation
PointerFound
EventHandler<PointerFoundEventArgs> Juniper.Unity.Input.AbstractUnifiedInputModule.PointerFound inherited
Definition at line 46 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.OnPointerFound(), and Juniper.Unity.Input.AbstractUnifiedInputModule.WithPointer().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/Oculus/OculusInputModule.cs