Juniper: Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration Class Reference
Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration Class Reference
Public Member Functions
void Commit ()
Static Public Member Functions
static ProjectConfiguration Load ()
Properties
int BuildStep [get, set]
PlatformTypes CurrentPlatform [get]
PlatformTypes?? NextPlatform [get, set]
Events
Func< bool > PlatformChanged
Action PlatformChangeConfirmed
Private Member Functions
void Save ()
Private Attributes
const string CONFIG_FILE_NAME = "juniper.json"
int buildStep
PlatformTypes currentPlatform
PlatformTypes nextPlatform
Detailed Description
Definition at line 8 of file ProjectConfiguration.cs.
Member Function Documentation
Commit()
void Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Commit () inline
Definition at line 41 of file ProjectConfiguration.cs.
         {
             buildStep = 0;
             currentPlatform = NextPlatform;
             nextPlatform = PlatformTypes.None;
             Save();
         }
References Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.buildStep, Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.currentPlatform, Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.nextPlatform, Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.NextPlatform, and Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Save().
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareProject().
Load()
static ProjectConfiguration Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Load () inline static
Definition at line 12 of file ProjectConfiguration.cs.
         {
             try
             {
                 if (File.Exists(CONFIG_FILE_NAME))
                 {
                     return JsonConvert.DeserializeObject<ProjectConfiguration>(File.ReadAllText(CONFIG_FILE_NAME));
                 }
             }
             catch
             {
             }
             return new ProjectConfiguration();
         }
References Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.CONFIG_FILE_NAME.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
Save()
void Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Save () inline private
Definition at line 49 of file ProjectConfiguration.cs.
         {
             FileExt.WriteAllText(CONFIG_FILE_NAME, JsonConvert.SerializeObject(this));
         }
References Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.CONFIG_FILE_NAME, and System.IO.FileExt.WriteAllText().
Referenced by Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Commit().
Member Data Documentation
buildStep
int Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.buildStep private
Definition at line 29 of file ProjectConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Commit().
CONFIG_FILE_NAME
const string Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.CONFIG_FILE_NAME = "juniper.json" private
Definition at line 10 of file ProjectConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Load(), and Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Save().
currentPlatform
PlatformTypes Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.currentPlatform private
Definition at line 32 of file ProjectConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Commit().
nextPlatform
PlatformTypes Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.nextPlatform private
Definition at line 35 of file ProjectConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Commit().
Property Documentation
BuildStep
int Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.BuildStep get set
Definition at line 56 of file ProjectConfiguration.cs.
         {
             get
             {
                 return buildStep - 1;
             }
             set
             {
                 buildStep = value + 1;
                 Save();
             }
         }
CurrentPlatform
PlatformTypes Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.CurrentPlatform get
Definition at line 71 of file ProjectConfiguration.cs.
         {
             get
             {
                 return currentPlatform;
             }
         }
NextPlatform
PlatformTypes?? Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.NextPlatform get set
Definition at line 80 of file ProjectConfiguration.cs.
         {
             get
             {
                 return nextPlatform;
             }
             set
             {
                 var lastValue = nextPlatform;
                 nextPlatform = value;
                 if (PlatformChanged?.Invoke() != false)
                 {
                     Save();
                     if (value != PlatformTypes.None)
                     {
                         PlatformChangeConfirmed?.Invoke();
                     }
                 }
                 else
                 {
                     nextPlatform = lastValue;
                 }
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Commit(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged().
Event Documentation
PlatformChangeConfirmed
Action Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.PlatformChangeConfirmed
Definition at line 39 of file ProjectConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
PlatformChanged
Func<bool> Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.PlatformChanged
Definition at line 37 of file ProjectConfiguration.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Editor/ConfigurationManagement/ProjectConfiguration.cs