Juniper: Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler Class Reference
Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler Class Reference
Public Member Functions
override void Awake ()
Registers for Vuforia's trackable event handlers.
override void Update ()
Checks the tracking status of the target and fires any appropriate change/found/lost events.
void OnTrackableStateChanged (TrackableBehaviour.Status previousStatus, TrackableBehaviour.Status newStatus)
Updates the tracking state of the target when Unity's OnTrackableStateChange event is fired.
void OnValidate ()
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
void OnEnable ()
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
void ForceFound ()
Forces the onFound event to fire.
void ForceLost ()
Forces the onLost event to fire.
void OnDisable ()
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
Public Attributes
bool DebugReport
Set to true to make the update loop print a debug report.
bool Found
This value is set to true when the target has been found.
bool Safe = true
This value is set to true when the user is at a safe distance from the target.
bool Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Transform attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
float safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
BooleanEvent onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
UnityEvent onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
UnityEvent onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
UnityEvent onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
UnityEvent onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Events
EventHandler< TrackingStateChangeEventArgs > TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Private Member Functions
void OnDestroy ()
When running on Vuforia, de-registers the listeners for Vuforia's tracking state changed events.
void PrintDebugReport ()
If DebugReport is set to true, prints a report on the status of tracking.
Private Attributes
TrackableBehaviour trackable
The Vuforia tracked object.
Detailed Description
Definition at line 8 of file VuforiaTrackableFoundEventHandler.cs.
Member Function Documentation
Awake()
override void Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.Awake () inline virtual
Registers for Vuforia's trackable event handlers.
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.
Definition at line 22 of file VuforiaTrackableFoundEventHandler.cs.
         {
             trackable = GetComponentInChildren<TrackableBehaviour>();
             trackable.RegisterTrackableEventHandler(this);
             base.Awake();
         }
References Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.trackable.
ForceFound()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound () inline inherited
Forces the onFound event to fire.
Definition at line 220 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasFound = false;
             Found = true;
             Extended = false;
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
ForceLost()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost () inline inherited
Forces the onLost event to fire.
Definition at line 231 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasFound = true;
             Found = false;
             Extended = false;
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasFound.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable().
OnDestroy()
void Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.OnDestroy () inline private
When running on Vuforia, de-registers the listeners for Vuforia's tracking state changed events.
Definition at line 43 of file VuforiaTrackableFoundEventHandler.cs.
         {
             trackable.UnregisterTrackableEventHandler(this);
         }
References Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.trackable.
OnDisable()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnDisable () inline inherited
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
Definition at line 242 of file AbstractTrackableFoundEventHandler.cs.
         {
             ForceLost();
             Update();
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Update().
OnEnable()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnEnable () inline inherited
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
Definition at line 116 of file AbstractTrackableFoundEventHandler.cs.
         {
             wasSafe = Safe = true;
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Safe, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.wasSafe.
OnTrackableStateChanged()
void Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.OnTrackableStateChanged (TrackableBehaviour.Status previousStatus, TrackableBehaviour.Status newStatus) inline
Updates the tracking state of the target when Unity's OnTrackableStateChange event is fired.
Parameters
previousStatus Previous status.
newStatus New status.
Definition at line 53 of file VuforiaTrackableFoundEventHandler.cs.
         {
             if (DebugReport)
             {
                 ScreenDebugger.Print("[{0}] {1} => {2}", trackable.TrackableName, previousStatus, newStatus);
             }
             Extended = trackable.CurrentStatus == TrackableBehaviour.Status.EXTENDED_TRACKED;
             Found = trackable.CurrentStatus == TrackableBehaviour.Status.DETECTED
                 || trackable.CurrentStatus == TrackableBehaviour.Status.TRACKED
                 || Extended;
         }
References Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.DebugReport, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, System.ScreenDebugger.Print(), and Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.trackable.
OnValidate()
void Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate () inline inherited
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
Definition at line 100 of file AbstractTrackableFoundEventHandler.cs.
         {
             if (attachmentPoint == null)
             {
                 attachmentPoint = transform.Children().FirstOrDefault(t =>
                     t.tag == TAG_NAME)
                                            ?? transform.Children().FirstOrDefault(t =>
                                                t.name == TRANSFORM_NAME)
                                            ?? transform;
             }
         }
References Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.attachmentPoint, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TAG_NAME, and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TRANSFORM_NAME.
PrintDebugReport()
void Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.PrintDebugReport () inline private
If DebugReport is set to true, prints a report on the status of tracking.
Definition at line 71 of file VuforiaTrackableFoundEventHandler.cs.
         {
             if (DebugReport)
             {
                 if (trackable == null)
                 {
                     ScreenDebugger.Print($"[{name}] No trackable object!");
                 }
                 else
                 {
                     var msg = Extended ? "extended" : Found ? "FOUND" : "";
                     ScreenDebugger.Print($"[{name}] {trackable.TrackableName} -> {msg}");
                 }
             }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.DebugReport, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found, System.ScreenDebugger.Print(), and Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.trackable.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.Update().
Update()
override void Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.Update () inline virtual
Checks the tracking status of the target and fires any appropriate change/found/lost events.
Reimplemented from Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.
Definition at line 30 of file VuforiaTrackableFoundEventHandler.cs.
         {
             base.Update();
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.DebugReport, and Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.PrintDebugReport().
Member Data Documentation
attachmentPoint
Transform Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.attachmentPoint inherited
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
Definition at line 44 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnValidate().
DebugReport
bool Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.DebugReport
Set to true to make the update loop print a debug report.
Definition at line 20 of file VuforiaTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.OnTrackableStateChanged(), Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.PrintDebugReport(), and Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.Update().
Extended
bool Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Extended inherited
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Definition at line 38 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.OnTrackableStateChanged(), and Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.PrintDebugReport().
Found
bool Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Found inherited
This value is set to true when the target has been found.
Definition at line 16 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceFound(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.ForceLost(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnFoundChanged(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.OnTrackableStateChanged(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged(), Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.PrintDebugReport(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onFound
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onFound = new UnityEvent() inherited
A Unity Event that fires when the target is first found.
Definition at line 68 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onLost
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onLost = new UnityEvent() inherited
A Unity Event that fires when the target is been completely lost.
Definition at line 73 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnLostOrFound(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onProximity
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onProximity = new UnityEvent() inherited
A Unity Event that fires when the user gets too close to the target.
Definition at line 78 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onSafe
UnityEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onSafe = new UnityEvent() inherited
A Unity Event that fires when the user returns to a safe distance from the target.
Definition at line 83 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onTrackingStateChange
BooleanEvent Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.onTrackingStateChange = new BooleanEvent() inherited
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
Definition at line 56 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged().
Safe
bool Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.Safe = true inherited
This value is set to true when the user is at a safe distance from the target.
Definition at line 27 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnEnable(), Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
safeDistance
float Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.safeDistance inherited
The minimum distance in meters from the target at which to consider the user "safe".
Definition at line 49 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.SafetyCheck().
trackable
TrackableBehaviour Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.trackable private
The Vuforia tracked object.
Definition at line 15 of file VuforiaTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.Awake(), Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.OnDestroy(), Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.OnTrackableStateChanged(), and Juniper.Unity.ImageTracking.VuforiaTrackableFoundEventHandler.PrintDebugReport().
Event Documentation
TrackingStateChange
EventHandler<TrackingStateChangeEventArgs> Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.TrackingStateChange inherited
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Definition at line 63 of file AbstractTrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.AbstractTrackableFoundEventHandler.OnTrackingStateChanged().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/Vuforia/VuforiaTrackableFoundEventHandler.cs