Juniper: Juniper.MediaType.Video Class Reference
Juniper.MediaType.Video Class Reference
Public Member Functions
override bool Matches (string fileName)
bool Matches (FileInfo file)
string AddExtension (string fileName)
bool Equals (string other)
override bool Equals (object obj)
bool Equals (MediaType other)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static MediaType Parse (string value)
static IReadOnlyCollection< MediaType > ParseAll (string[] acceptTypes)
static bool TryParse (string value, out MediaType type)
static IReadOnlyList< MediaType > GuessByFileName (string fileName)
static IReadOnlyList< MediaType > GuessByFile (FileInfo file)
static MediaType Lookup (string value)
static ContentReference operator+ (string cacheID, MediaType contentType)
static implicit operator string (MediaType mediaType)
static bool operator== (MediaType left, MediaType right)
static bool operator== (MediaType left, string right)
static bool operator== (string left, MediaType right)
static bool operator != (MediaType left, MediaType right)
static bool operator != (MediaType left, string right)
static bool operator != (string left, MediaType right)
Static Public Attributes
static readonly Video AnyVideo = new Video("*")
static readonly Video BMPEG = new Video("bmpeg")
static readonly Video BT656 = new Video("bt656")
static readonly Video CelB = new Video("celb")
static readonly Video DV = new Video("dv")
static readonly Video Encaprtp = new Video("encaprtp")
static readonly Video Example = new Video("example")
static readonly Video Flexfec = new Video("flexfec")
static readonly Video H261 = new Video("h261", new string[] { "h261" })
static readonly Video H263 = new Video("h263", new string[] { "h263" })
static readonly Video H263_1998 = new Video("h263-1998")
static readonly Video H263_2000 = new Video("h263-2000")
static readonly Video H264 = new Video("h264", new string[] { "h264" })
static readonly Video H264_RCDO = new Video("h264-rcdo")
static readonly Video H264_SVC = new Video("h264-svc")
static readonly Video H265 = new Video("h265")
static readonly Video IsoSegment = new Video("iso.segment")
static readonly Video JPEG = new Video("jpeg", new string[] { "jpgv" })
static readonly Video Jpeg2000 = new Video("jpeg2000")
static readonly Video Jpm = new Video("jpm", new string[] { "jpm", "jpgm" })
static readonly Video Mj2 = new Video("mj2", new string[] { "mj2", "mjp2" })
static readonly Video MP1S = new Video("mp1s")
static readonly Video MP2P = new Video("mp2p")
static readonly Video MP2T = new Video("mp2t")
static readonly Video Mp4 = new Video("mp4", new string[] { "mp4", "mp4v", "mpg4" })
static readonly Video MP4V_ES = new Video("mp4v-es")
static readonly Video Mpeg = new Video("mpeg", new string[] { "mpeg", "mpg", "mpe", "m1v", "m2v" })
static readonly Video Mpeg4_Generic = new Video("mpeg4-generic")
static readonly Video MPV = new Video("mpv")
static readonly Video Nv = new Video("nv")
static readonly Video Ogg = new Video("ogg", new string[] { "ogv" })
static readonly Video Parityfec = new Video("parityfec")
static readonly Video Pointer = new Video("pointer")
static readonly Video Quicktime = new Video("quicktime", new string[] { "qt", "mov" })
static readonly Video Raptorfec = new Video("raptorfec")
static readonly Video Raw = new Video("raw")
static readonly Video Rtp_Enc_Aescm128 = new Video("rtp-enc-aescm128")
static readonly Video Rtploopback = new Video("rtploopback")
static readonly Video Rtx = new Video("rtx")
static readonly Video Smpte291 = new Video("smpte291")
static readonly Video SMPTE292M = new Video("smpte292m")
static readonly Video Ulpfec = new Video("ulpfec")
static readonly Video Vc1 = new Video("vc1")
static readonly Video Vc2 = new Video("vc2")
static readonly Video Vendor1d_Interleaved_Parityfec = new Video("1d-interleaved-parityfec")
static readonly Video Vendor3gpp = new Video("3gpp", new string[] { "3gp" })
static readonly Video Vendor3gpp_Tt = new Video("3gpp-tt")
static readonly Video Vendor3gpp2 = new Video("3gpp2", new string[] { "3g2" })
static readonly Video VendorCCTV = new Video("vnd.cctv")
static readonly Video VendorDeceHd = new Video("vnd.dece.hd", new string[] { "uvh", "uvvh" })
static readonly Video VendorDeceMobile = new Video("vnd.dece.mobile", new string[] { "uvm", "uvvm" })
static readonly Video VendorDeceMp4 = new Video("vnd.dece.mp4")
static readonly Video VendorDecePd = new Video("vnd.dece.pd", new string[] { "uvp", "uvvp" })
static readonly Video VendorDeceSd = new Video("vnd.dece.sd", new string[] { "uvs", "uvvs" })
static readonly Video VendorDeceVideo = new Video("vnd.dece.video", new string[] { "uvv", "uvvv" })
static readonly Video VendorDirectvMpeg = new Video("vnd.directv.mpeg")
static readonly Video VendorDirectvMpeg_Tts = new Video("vnd.directv.mpeg-tts")
static readonly Video VendorDlnaMpeg_Tts = new Video("vnd.dlna.mpeg-tts")
static readonly Video VendorDvbFile = new Video("vnd.dvb.file", new string[] { "dvb" })
static readonly Video VendorFvt = new Video("vnd.fvt", new string[] { "fvt" })
static readonly Video VendorHnsVideo = new Video("vnd.hns.video")
static readonly Video VendorIptvforum1dparityfec_1010 = new Video("vnd.iptvforum.1dparityfec-1010")
static readonly Video VendorIptvforum1dparityfec_2005 = new Video("vnd.iptvforum.1dparityfec-2005")
static readonly Video VendorIptvforum2dparityfec_1010 = new Video("vnd.iptvforum.2dparityfec-1010")
static readonly Video VendorIptvforum2dparityfec_2005 = new Video("vnd.iptvforum.2dparityfec-2005")
static readonly Video VendorIptvforumTtsavc = new Video("vnd.iptvforum.ttsavc")
static readonly Video VendorIptvforumTtsmpeg2 = new Video("vnd.iptvforum.ttsmpeg2")
static readonly Video VendorMotorolaVideo = new Video("vnd.motorola.video")
static readonly Video VendorMotorolaVideop = new Video("vnd.motorola.videop")
static readonly Video VendorMpegurl = new Video("vnd.mpegurl", new string[] { "mxu", "m4u" })
static readonly Video VendorMs_PlayreadyMediaPyv = new Video("vnd.ms-playready.media.pyv", new string[] { "pyv" })
static readonly Video VendorNokiaInterleaved_Multimedia = new Video("vnd.nokia.interleaved-multimedia")
static readonly Video VendorNokiaMp4vr = new Video("vnd.nokia.mp4vr")
static readonly Video VendorNokiaVideovoip = new Video("vnd.nokia.videovoip")
static readonly Video VendorObjectvideo = new Video("vnd.objectvideo")
static readonly Video VendorRadgamettoolsBink = new Video("vnd.radgamettools.bink")
static readonly Video VendorRadgamettoolsSmacker = new Video("vnd.radgamettools.smacker")
static readonly Video VendorSealedmediaSoftsealMov = new Video("vnd.sealedmedia.softseal.mov")
static readonly Video VendorSealedMpeg1 = new Video("vnd.sealed.mpeg1")
static readonly Video VendorSealedMpeg4 = new Video("vnd.sealed.mpeg4")
static readonly Video VendorSealedSwf = new Video("vnd.sealed.swf")
static readonly Video VendorUvvuMp4 = new Video("vnd.uvvu.mp4", new string[] { "uvu", "uvvu" })
static readonly Video VendorVivo = new Video("vnd.vivo", new string[] { "viv" })
static readonly Video VendorYoutubeYt = new Video("vnd.youtube.yt")
static readonly Video VP8 = new Video("vp8")
static readonly Video Webm = new Video("webm", new string[] { "webm" })
static readonly Video X_F4v = new Video("x-f4v", new string[] { "f4v" })
static readonly Video X_Fli = new Video("x-fli", new string[] { "fli" })
static readonly Video X_Flv = new Video("x-flv", new string[] { "flv" })
static readonly Video X_M4v = new Video("x-m4v", new string[] { "m4v" })
static readonly Video X_Matroska = new Video("x-matroska", new string[] { "mkv", "mk3d", "mks" })
static readonly Video X_Mng = new Video("x-mng", new string[] { "mng" })
static readonly Video X_Ms_Asf = new Video("x-ms-asf", new string[] { "asf", "asx" })
static readonly Video X_Ms_Vob = new Video("x-ms-vob", new string[] { "vob" })
static readonly Video X_Ms_Wm = new Video("x-ms-wm", new string[] { "wm" })
static readonly Video X_Ms_Wmv = new Video("x-ms-wmv", new string[] { "wmv" })
static readonly Video X_Ms_Wmx = new Video("x-ms-wmx", new string[] { "wmx" })
static readonly Video X_Ms_Wvx = new Video("x-ms-wvx", new string[] { "wvx" })
static readonly Video X_Msvideo = new Video("x-msvideo", new string[] { "avi" })
static readonly Video X_Sgi_Movie = new Video("x-sgi-movie", new string[] { "movie" })
static readonly Video X_Smv = new Video("x-smv", new string[] { "smv" })
static new readonly Video [] Values
static readonly MediaType Any = new MediaType("*/*")
static readonly IReadOnlyCollection< MediaType > All = new MediaType[] { Any }
Properties
string Value [get]
string TypeName [get]
string SubTypeName [get]
float Weight [get]
ReadOnlyCollection< string > Extensions [get]
string PrimaryExtension [get]
Private Member Functions
Video (string value, string[] extensions)
Video (string value)
Detailed Description
Definition at line 7 of file Video.cs.
Constructor & Destructor Documentation
Video() [1/2]
Juniper.MediaType.Video.Video (string value, string [] extensions) inline private
Definition at line 9 of file Video.cs.
 : base("video/" + value, extensions) { }
Video() [2/2]
Juniper.MediaType.Video.Video (string value) inline private
Definition at line 11 of file Video.cs.
 : this(value, null) { }
Member Function Documentation
AddExtension()
string Juniper.MediaType.AddExtension (string fileName) inline inherited
Definition at line 310 of file MediaType.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (PrimaryExtension is object)
             {
                 var currentExtension = PathExt.GetShortExtension(fileName);
                 if (Extensions.IndexOf(currentExtension) == -1)
                 {
                     fileName += "." + PrimaryExtension;
                 }
             }
             return fileName;
         }
References Juniper.MediaType.Extensions, System.IO.PathExt.GetShortExtension(), and Juniper.MediaType.PrimaryExtension.
Referenced by Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), and Juniper.IO.ContentReference.operator string().
Equals() [1/3]
bool Juniper.MediaType.Equals (string other) inline inherited
Definition at line 329 of file MediaType.cs.
         {
             return TryParse(other, out var type)
                 && Equals(type);
         }
References Juniper.MediaType.TryParse().
Referenced by Juniper.MediaType.Equals().
Equals() [2/3]
override bool Juniper.MediaType.Equals (object obj) inline inherited
Definition at line 335 of file MediaType.cs.
         {
             return (obj is MediaType type && Equals(type))
                 || (obj is string str && Equals(str));
         }
References Juniper.MediaType.Equals().
Equals() [3/3]
bool Juniper.MediaType.Equals (MediaType other) inline inherited
Definition at line 341 of file MediaType.cs.
         {
             return other is object
                 && (TypeName == "*"
                     || other.TypeName == "*"
                     || TypeName == other.TypeName)
                 && (SubTypeName == "*"
                     || other.SubTypeName == "*"
                     || SubTypeName == other.SubTypeName);
         }
References Juniper.MediaType.SubTypeName, and Juniper.MediaType.TypeName.
GetHashCode()
override int Juniper.MediaType.GetHashCode () inline inherited
Definition at line 397 of file MediaType.cs.
         {
             var hashCode = -1006577490;
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(TypeName);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(SubTypeName);
             hashCode = (hashCode * -1521134295) + Weight.GetHashCode();
             hashCode = (hashCode * -1521134295) + EqualityComparer<ReadOnlyCollection<string>>.Default.GetHashCode(Extensions);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(PrimaryExtension);
             return hashCode;
         }
References Juniper.MediaType.Extensions, Juniper.MediaType.PrimaryExtension, Juniper.MediaType.SubTypeName, Juniper.MediaType.TypeName, and Juniper.MediaType.Weight.
GuessByFile()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFile (FileInfo file) inline static inherited
Definition at line 155 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return GuessByFileName(file.Name);
         }
References Juniper.MediaType.GuessByFileName().
Referenced by Juniper.HTTP.Server.HttpListenerResponseExt.SendFileAsync().
GuessByFileName()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFileName (string fileName) inline static inherited
Definition at line 144 of file MediaType.cs.
         {
             if (string.IsNullOrEmpty(fileName))
             {
                 throw new ArgumentException("Must provide a valid fileName", nameof(fileName));
             }
             var ext = Path.GetExtension(fileName);
             return GuessByExtension(ref ext);
         }
References Juniper.MediaType.GuessByExtension().
Referenced by Juniper.MediaType.GuessByFile(), and Juniper.MediaType.Matches().
Lookup()
static MediaType Juniper.MediaType.Lookup (string value) inline static inherited
Definition at line 165 of file MediaType.cs.
         {
             // Trim off the weight, if one exists
             var parts = value.SplitX(';');
             if (parts.Length > 0)
             {
                 value = parts[0];
             }
             if (byValue.ContainsKey(value))
             {
                 return byValue[value];
             }
             var name = Array.Find(parts, p => p.Length > 0);
             if (string.IsNullOrEmpty(name))
             {
                 return Lookup("unknown/unknown");
             }
             else
             {
                 return new Unknown(name);
             }
         }
References Juniper.MediaType.byValue.
Matches() [1/2]
override bool Juniper.MediaType.Video.Matches (string fileName) inline virtual
Reimplemented from Juniper.MediaType.
Definition at line 15 of file Video.cs.
             {
                 if (ReferenceEquals(this, AnyVideo))
                 {
                     return Values.Any(x => x.Matches(fileName));
                 }
                 else
                 {
                     return base.Matches(fileName);
                 }
             }
References Juniper.MediaType.Any, Juniper.MediaType.Video.AnyVideo, Juniper.MediaType.Matches(), and Juniper.MediaType.Video.Values.
Matches() [2/2]
bool Juniper.MediaType.Matches (FileInfo file) inline inherited
Definition at line 300 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return Matches(file.Name);
         }
References Juniper.MediaType.Matches().
operator !=() [1/3]
static bool Juniper.MediaType.operator != (MediaType left, MediaType right) inline static inherited
Definition at line 358 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [2/3]
static bool Juniper.MediaType.operator != (MediaType left, string right) inline static inherited
Definition at line 369 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [3/3]
static bool Juniper.MediaType.operator != (string left, MediaType right) inline static inherited
Definition at line 380 of file MediaType.cs.
         {
             return !(left == right);
         }
operator string()
static implicit Juniper.MediaType.operator string (MediaType mediaType) inline static inherited
Definition at line 196 of file MediaType.cs.
         {
             return mediaType?.ToString();
         }
operator+()
static ContentReference Juniper.MediaType.operator+ (string cacheID, MediaType contentType) inline static inherited
Definition at line 191 of file MediaType.cs.
         {
             return new ContentReference(cacheID, contentType);
         }
operator==() [1/3]
static bool Juniper.MediaType.operator== (MediaType left, MediaType right) inline static inherited
Definition at line 352 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [2/3]
static bool Juniper.MediaType.operator== (MediaType left, string right) inline static inherited
Definition at line 363 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [3/3]
static bool Juniper.MediaType.operator== (string left, MediaType right) inline static inherited
Definition at line 374 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (right is object && right.Equals(left));
         }
Parse()
static MediaType Juniper.MediaType.Parse (string value) inline static inherited
Definition at line 40 of file MediaType.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             if (TryParse(value, out var type))
             {
                 return type;
             }
             else
             {
                 throw new ArgumentException($"Type value does not match expected pattern {TYPE_PATTERN.ToString()}", nameof(value));
             }
         }
References Juniper.MediaType.TryParse().
ParseAll()
static IReadOnlyCollection<MediaType> Juniper.MediaType.ParseAll (string [] acceptTypes) inline static inherited
Definition at line 57 of file MediaType.cs.
         {
             if (acceptTypes is null || acceptTypes.Length == 0)
             {
                 return All;
             }
             else
             {
                 return InternalParseAll(acceptTypes).ToArray();
             }
         }
References Juniper.MediaType.All, and Juniper.MediaType.InternalParseAll().
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable().
ToString()
override string Juniper.MediaType.ToString () inline inherited
Definition at line 385 of file MediaType.cs.
         {
             if (Weight == 1)
             {
                 return Value;
             }
             else
             {
                 return weightedValue;
             }
         }
References Juniper.MediaType.Value, Juniper.MediaType.Weight, and Juniper.MediaType.weightedValue.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.ListDirectoryAsync().
TryParse()
static bool Juniper.MediaType.TryParse (string value, out MediaType type) inline static inherited
Definition at line 83 of file MediaType.cs.
         {
             type = null;
             if (value is null)
             {
                 return false;
             }
             var match = TYPE_PATTERN.Match(value);
             if (!match.Success)
             {
                 return false;
             }
             var typeName = match.Groups[1].Value;
             var subTypeName = match.Groups[2].Value;
             var rawValue = typeName + "/" + subTypeName;
             if (match.Groups.Count == 4
                 && float.TryParse(
                     match.Groups[3].Value,
                     NumberStyles.Integer | NumberStyles.AllowDecimalPoint,
                     CultureInfo.InvariantCulture,
                     out var weight))
             {
                 type = new MediaType(typeName, subTypeName, weight);
             }
             else if (byValue.ContainsKey(rawValue))
             {
                 type = byValue[rawValue];
             }
             else
             {
                 type = new MediaType(typeName, subTypeName);
             }
             return type is object;
         }
References Juniper.MediaType.byValue, Juniper.MediaType.MediaType(), and Juniper.MediaType.TYPE_PATTERN.
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.InternalParseAll(), Juniper.MediaType.Parse(), and Juniper.Processes.ProcessArgs.TryGetMediaType().
Member Data Documentation
All
readonly IReadOnlyCollection<MediaType> Juniper.MediaType.All = new MediaType[] { Any } static inherited
Definition at line 38 of file MediaType.cs.
Referenced by Juniper.MediaType.ParseAll().
Any
readonly MediaType Juniper.MediaType.Any = new MediaType("*/*") static inherited
Definition at line 36 of file MediaType.cs.
Referenced by Juniper.MediaType.Application.Matches(), Juniper.MediaType.Audio.Matches(), Juniper.MediaType.Chemical.Matches(), Juniper.MediaType.Font.Matches(), Juniper.MediaType.Image.Matches(), Juniper.MediaType.Message.Matches(), Juniper.MediaType.Model.Matches(), Juniper.MediaType.Multipart.Matches(), Juniper.MediaType.Text.Matches(), Juniper.MediaType.Video.Matches(), and Juniper.MediaType.XConference.Matches().
AnyVideo
readonly Video Juniper.MediaType.Video.AnyVideo = new Video("*") static
Definition at line 13 of file Video.cs.
Referenced by Juniper.MediaType.Video.Matches().
BMPEG
readonly Video Juniper.MediaType.Video.BMPEG = new Video("bmpeg") static
Definition at line 7 of file Video.Values.cs.
BT656
readonly Video Juniper.MediaType.Video.BT656 = new Video("bt656") static
Definition at line 8 of file Video.Values.cs.
CelB
readonly Video Juniper.MediaType.Video.CelB = new Video("celb") static
Definition at line 9 of file Video.Values.cs.
DV
readonly Video Juniper.MediaType.Video.DV = new Video("dv") static
Definition at line 10 of file Video.Values.cs.
Encaprtp
readonly Video Juniper.MediaType.Video.Encaprtp = new Video("encaprtp") static
Definition at line 11 of file Video.Values.cs.
Example
readonly Video Juniper.MediaType.Video.Example = new Video("example") static
Definition at line 12 of file Video.Values.cs.
Flexfec
readonly Video Juniper.MediaType.Video.Flexfec = new Video("flexfec") static
Definition at line 13 of file Video.Values.cs.
H261
readonly Video Juniper.MediaType.Video.H261 = new Video("h261", new string[] { "h261" }) static
Definition at line 14 of file Video.Values.cs.
H263
readonly Video Juniper.MediaType.Video.H263 = new Video("h263", new string[] { "h263" }) static
Definition at line 15 of file Video.Values.cs.
H263_1998
readonly Video Juniper.MediaType.Video.H263_1998 = new Video("h263-1998") static
Definition at line 16 of file Video.Values.cs.
H263_2000
readonly Video Juniper.MediaType.Video.H263_2000 = new Video("h263-2000") static
Definition at line 17 of file Video.Values.cs.
H264
readonly Video Juniper.MediaType.Video.H264 = new Video("h264", new string[] { "h264" }) static
Definition at line 18 of file Video.Values.cs.
H264_RCDO
readonly Video Juniper.MediaType.Video.H264_RCDO = new Video("h264-rcdo") static
Definition at line 19 of file Video.Values.cs.
H264_SVC
readonly Video Juniper.MediaType.Video.H264_SVC = new Video("h264-svc") static
Definition at line 20 of file Video.Values.cs.
H265
readonly Video Juniper.MediaType.Video.H265 = new Video("h265") static
Definition at line 21 of file Video.Values.cs.
IsoSegment
readonly Video Juniper.MediaType.Video.IsoSegment = new Video("iso.segment") static
Definition at line 22 of file Video.Values.cs.
JPEG
readonly Video Juniper.MediaType.Video.JPEG = new Video("jpeg", new string[] { "jpgv" }) static
Definition at line 23 of file Video.Values.cs.
Jpeg2000
readonly Video Juniper.MediaType.Video.Jpeg2000 = new Video("jpeg2000") static
Definition at line 24 of file Video.Values.cs.
Jpm
readonly Video Juniper.MediaType.Video.Jpm = new Video("jpm", new string[] { "jpm", "jpgm" }) static
Definition at line 25 of file Video.Values.cs.
Mj2
readonly Video Juniper.MediaType.Video.Mj2 = new Video("mj2", new string[] { "mj2", "mjp2" }) static
Definition at line 26 of file Video.Values.cs.
MP1S
readonly Video Juniper.MediaType.Video.MP1S = new Video("mp1s") static
Definition at line 27 of file Video.Values.cs.
MP2P
readonly Video Juniper.MediaType.Video.MP2P = new Video("mp2p") static
Definition at line 28 of file Video.Values.cs.
MP2T
readonly Video Juniper.MediaType.Video.MP2T = new Video("mp2t") static
Definition at line 29 of file Video.Values.cs.
Mp4
readonly Video Juniper.MediaType.Video.Mp4 = new Video("mp4", new string[] { "mp4", "mp4v", "mpg4" }) static
Definition at line 30 of file Video.Values.cs.
MP4V_ES
readonly Video Juniper.MediaType.Video.MP4V_ES = new Video("mp4v-es") static
Definition at line 31 of file Video.Values.cs.
Mpeg
readonly Video Juniper.MediaType.Video.Mpeg = new Video("mpeg", new string[] { "mpeg", "mpg", "mpe", "m1v", "m2v" }) static
Definition at line 32 of file Video.Values.cs.
Mpeg4_Generic
readonly Video Juniper.MediaType.Video.Mpeg4_Generic = new Video("mpeg4-generic") static
Definition at line 33 of file Video.Values.cs.
MPV
readonly Video Juniper.MediaType.Video.MPV = new Video("mpv") static
Definition at line 34 of file Video.Values.cs.
Nv
readonly Video Juniper.MediaType.Video.Nv = new Video("nv") static
Definition at line 35 of file Video.Values.cs.
Ogg
readonly Video Juniper.MediaType.Video.Ogg = new Video("ogg", new string[] { "ogv" }) static
Definition at line 36 of file Video.Values.cs.
Parityfec
readonly Video Juniper.MediaType.Video.Parityfec = new Video("parityfec") static
Definition at line 37 of file Video.Values.cs.
Pointer
readonly Video Juniper.MediaType.Video.Pointer = new Video("pointer") static
Definition at line 38 of file Video.Values.cs.
Quicktime
readonly Video Juniper.MediaType.Video.Quicktime = new Video("quicktime", new string[] { "qt", "mov" }) static
Definition at line 39 of file Video.Values.cs.
Raptorfec
readonly Video Juniper.MediaType.Video.Raptorfec = new Video("raptorfec") static
Definition at line 40 of file Video.Values.cs.
Raw
readonly Video Juniper.MediaType.Video.Raw = new Video("raw") static
Definition at line 41 of file Video.Values.cs.
Rtp_Enc_Aescm128
readonly Video Juniper.MediaType.Video.Rtp_Enc_Aescm128 = new Video("rtp-enc-aescm128") static
Definition at line 42 of file Video.Values.cs.
Rtploopback
readonly Video Juniper.MediaType.Video.Rtploopback = new Video("rtploopback") static
Definition at line 43 of file Video.Values.cs.
Rtx
readonly Video Juniper.MediaType.Video.Rtx = new Video("rtx") static
Definition at line 44 of file Video.Values.cs.
Smpte291
readonly Video Juniper.MediaType.Video.Smpte291 = new Video("smpte291") static
Definition at line 45 of file Video.Values.cs.
SMPTE292M
readonly Video Juniper.MediaType.Video.SMPTE292M = new Video("smpte292m") static
Definition at line 46 of file Video.Values.cs.
Ulpfec
readonly Video Juniper.MediaType.Video.Ulpfec = new Video("ulpfec") static
Definition at line 47 of file Video.Values.cs.
Values
new readonly Video [] Juniper.MediaType.Video.Values static
Definition at line 108 of file Video.Values.cs.
Referenced by Juniper.MediaType.Video.Matches().
Vc1
readonly Video Juniper.MediaType.Video.Vc1 = new Video("vc1") static
Definition at line 48 of file Video.Values.cs.
Vc2
readonly Video Juniper.MediaType.Video.Vc2 = new Video("vc2") static
Definition at line 49 of file Video.Values.cs.
Vendor1d_Interleaved_Parityfec
readonly Video Juniper.MediaType.Video.Vendor1d_Interleaved_Parityfec = new Video("1d-interleaved-parityfec") static
Definition at line 50 of file Video.Values.cs.
Vendor3gpp
readonly Video Juniper.MediaType.Video.Vendor3gpp = new Video("3gpp", new string[] { "3gp" }) static
Definition at line 51 of file Video.Values.cs.
Vendor3gpp2
readonly Video Juniper.MediaType.Video.Vendor3gpp2 = new Video("3gpp2", new string[] { "3g2" }) static
Definition at line 53 of file Video.Values.cs.
Vendor3gpp_Tt
readonly Video Juniper.MediaType.Video.Vendor3gpp_Tt = new Video("3gpp-tt") static
Definition at line 52 of file Video.Values.cs.
VendorCCTV
readonly Video Juniper.MediaType.Video.VendorCCTV = new Video("vnd.cctv") static
Definition at line 54 of file Video.Values.cs.
VendorDeceHd
readonly Video Juniper.MediaType.Video.VendorDeceHd = new Video("vnd.dece.hd", new string[] { "uvh", "uvvh" }) static
Definition at line 55 of file Video.Values.cs.
VendorDeceMobile
readonly Video Juniper.MediaType.Video.VendorDeceMobile = new Video("vnd.dece.mobile", new string[] { "uvm", "uvvm" }) static
Definition at line 56 of file Video.Values.cs.
VendorDeceMp4
readonly Video Juniper.MediaType.Video.VendorDeceMp4 = new Video("vnd.dece.mp4") static
Definition at line 57 of file Video.Values.cs.
VendorDecePd
readonly Video Juniper.MediaType.Video.VendorDecePd = new Video("vnd.dece.pd", new string[] { "uvp", "uvvp" }) static
Definition at line 58 of file Video.Values.cs.
VendorDeceSd
readonly Video Juniper.MediaType.Video.VendorDeceSd = new Video("vnd.dece.sd", new string[] { "uvs", "uvvs" }) static
Definition at line 59 of file Video.Values.cs.
VendorDeceVideo
readonly Video Juniper.MediaType.Video.VendorDeceVideo = new Video("vnd.dece.video", new string[] { "uvv", "uvvv" }) static
Definition at line 60 of file Video.Values.cs.
VendorDirectvMpeg
readonly Video Juniper.MediaType.Video.VendorDirectvMpeg = new Video("vnd.directv.mpeg") static
Definition at line 61 of file Video.Values.cs.
VendorDirectvMpeg_Tts
readonly Video Juniper.MediaType.Video.VendorDirectvMpeg_Tts = new Video("vnd.directv.mpeg-tts") static
Definition at line 62 of file Video.Values.cs.
VendorDlnaMpeg_Tts
readonly Video Juniper.MediaType.Video.VendorDlnaMpeg_Tts = new Video("vnd.dlna.mpeg-tts") static
Definition at line 63 of file Video.Values.cs.
VendorDvbFile
readonly Video Juniper.MediaType.Video.VendorDvbFile = new Video("vnd.dvb.file", new string[] { "dvb" }) static
Definition at line 64 of file Video.Values.cs.
VendorFvt
readonly Video Juniper.MediaType.Video.VendorFvt = new Video("vnd.fvt", new string[] { "fvt" }) static
Definition at line 65 of file Video.Values.cs.
VendorHnsVideo
readonly Video Juniper.MediaType.Video.VendorHnsVideo = new Video("vnd.hns.video") static
Definition at line 66 of file Video.Values.cs.
VendorIptvforum1dparityfec_1010
readonly Video Juniper.MediaType.Video.VendorIptvforum1dparityfec_1010 = new Video("vnd.iptvforum.1dparityfec-1010") static
Definition at line 67 of file Video.Values.cs.
VendorIptvforum1dparityfec_2005
readonly Video Juniper.MediaType.Video.VendorIptvforum1dparityfec_2005 = new Video("vnd.iptvforum.1dparityfec-2005") static
Definition at line 68 of file Video.Values.cs.
VendorIptvforum2dparityfec_1010
readonly Video Juniper.MediaType.Video.VendorIptvforum2dparityfec_1010 = new Video("vnd.iptvforum.2dparityfec-1010") static
Definition at line 69 of file Video.Values.cs.
VendorIptvforum2dparityfec_2005
readonly Video Juniper.MediaType.Video.VendorIptvforum2dparityfec_2005 = new Video("vnd.iptvforum.2dparityfec-2005") static
Definition at line 70 of file Video.Values.cs.
VendorIptvforumTtsavc
readonly Video Juniper.MediaType.Video.VendorIptvforumTtsavc = new Video("vnd.iptvforum.ttsavc") static
Definition at line 71 of file Video.Values.cs.
VendorIptvforumTtsmpeg2
readonly Video Juniper.MediaType.Video.VendorIptvforumTtsmpeg2 = new Video("vnd.iptvforum.ttsmpeg2") static
Definition at line 72 of file Video.Values.cs.
VendorMotorolaVideo
readonly Video Juniper.MediaType.Video.VendorMotorolaVideo = new Video("vnd.motorola.video") static
Definition at line 73 of file Video.Values.cs.
VendorMotorolaVideop
readonly Video Juniper.MediaType.Video.VendorMotorolaVideop = new Video("vnd.motorola.videop") static
Definition at line 74 of file Video.Values.cs.
VendorMpegurl
readonly Video Juniper.MediaType.Video.VendorMpegurl = new Video("vnd.mpegurl", new string[] { "mxu", "m4u" }) static
Definition at line 75 of file Video.Values.cs.
VendorMs_PlayreadyMediaPyv
readonly Video Juniper.MediaType.Video.VendorMs_PlayreadyMediaPyv = new Video("vnd.ms-playready.media.pyv", new string[] { "pyv" }) static
Definition at line 76 of file Video.Values.cs.
VendorNokiaInterleaved_Multimedia
readonly Video Juniper.MediaType.Video.VendorNokiaInterleaved_Multimedia = new Video("vnd.nokia.interleaved-multimedia") static
Definition at line 77 of file Video.Values.cs.
VendorNokiaMp4vr
readonly Video Juniper.MediaType.Video.VendorNokiaMp4vr = new Video("vnd.nokia.mp4vr") static
Definition at line 78 of file Video.Values.cs.
VendorNokiaVideovoip
readonly Video Juniper.MediaType.Video.VendorNokiaVideovoip = new Video("vnd.nokia.videovoip") static
Definition at line 79 of file Video.Values.cs.
VendorObjectvideo
readonly Video Juniper.MediaType.Video.VendorObjectvideo = new Video("vnd.objectvideo") static
Definition at line 80 of file Video.Values.cs.
VendorRadgamettoolsBink
readonly Video Juniper.MediaType.Video.VendorRadgamettoolsBink = new Video("vnd.radgamettools.bink") static
Definition at line 81 of file Video.Values.cs.
VendorRadgamettoolsSmacker
readonly Video Juniper.MediaType.Video.VendorRadgamettoolsSmacker = new Video("vnd.radgamettools.smacker") static
Definition at line 82 of file Video.Values.cs.
VendorSealedmediaSoftsealMov
readonly Video Juniper.MediaType.Video.VendorSealedmediaSoftsealMov = new Video("vnd.sealedmedia.softseal.mov") static
Definition at line 83 of file Video.Values.cs.
VendorSealedMpeg1
readonly Video Juniper.MediaType.Video.VendorSealedMpeg1 = new Video("vnd.sealed.mpeg1") static
Definition at line 84 of file Video.Values.cs.
VendorSealedMpeg4
readonly Video Juniper.MediaType.Video.VendorSealedMpeg4 = new Video("vnd.sealed.mpeg4") static
Definition at line 85 of file Video.Values.cs.
VendorSealedSwf
readonly Video Juniper.MediaType.Video.VendorSealedSwf = new Video("vnd.sealed.swf") static
Definition at line 86 of file Video.Values.cs.
VendorUvvuMp4
readonly Video Juniper.MediaType.Video.VendorUvvuMp4 = new Video("vnd.uvvu.mp4", new string[] { "uvu", "uvvu" }) static
Definition at line 87 of file Video.Values.cs.
VendorVivo
readonly Video Juniper.MediaType.Video.VendorVivo = new Video("vnd.vivo", new string[] { "viv" }) static
Definition at line 88 of file Video.Values.cs.
VendorYoutubeYt
readonly Video Juniper.MediaType.Video.VendorYoutubeYt = new Video("vnd.youtube.yt") static
Definition at line 89 of file Video.Values.cs.
VP8
readonly Video Juniper.MediaType.Video.VP8 = new Video("vp8") static
Definition at line 90 of file Video.Values.cs.
Webm
readonly Video Juniper.MediaType.Video.Webm = new Video("webm", new string[] { "webm" }) static
Definition at line 91 of file Video.Values.cs.
X_F4v
readonly Video Juniper.MediaType.Video.X_F4v = new Video("x-f4v", new string[] { "f4v" }) static
Definition at line 92 of file Video.Values.cs.
X_Fli
readonly Video Juniper.MediaType.Video.X_Fli = new Video("x-fli", new string[] { "fli" }) static
Definition at line 93 of file Video.Values.cs.
X_Flv
readonly Video Juniper.MediaType.Video.X_Flv = new Video("x-flv", new string[] { "flv" }) static
Definition at line 94 of file Video.Values.cs.
X_M4v
readonly Video Juniper.MediaType.Video.X_M4v = new Video("x-m4v", new string[] { "m4v" }) static
Definition at line 95 of file Video.Values.cs.
X_Matroska
readonly Video Juniper.MediaType.Video.X_Matroska = new Video("x-matroska", new string[] { "mkv", "mk3d", "mks" }) static
Definition at line 96 of file Video.Values.cs.
X_Mng
readonly Video Juniper.MediaType.Video.X_Mng = new Video("x-mng", new string[] { "mng" }) static
Definition at line 97 of file Video.Values.cs.
X_Ms_Asf
readonly Video Juniper.MediaType.Video.X_Ms_Asf = new Video("x-ms-asf", new string[] { "asf", "asx" }) static
Definition at line 98 of file Video.Values.cs.
X_Ms_Vob
readonly Video Juniper.MediaType.Video.X_Ms_Vob = new Video("x-ms-vob", new string[] { "vob" }) static
Definition at line 99 of file Video.Values.cs.
X_Ms_Wm
readonly Video Juniper.MediaType.Video.X_Ms_Wm = new Video("x-ms-wm", new string[] { "wm" }) static
Definition at line 100 of file Video.Values.cs.
X_Ms_Wmv
readonly Video Juniper.MediaType.Video.X_Ms_Wmv = new Video("x-ms-wmv", new string[] { "wmv" }) static
Definition at line 101 of file Video.Values.cs.
X_Ms_Wmx
readonly Video Juniper.MediaType.Video.X_Ms_Wmx = new Video("x-ms-wmx", new string[] { "wmx" }) static
Definition at line 102 of file Video.Values.cs.
X_Ms_Wvx
readonly Video Juniper.MediaType.Video.X_Ms_Wvx = new Video("x-ms-wvx", new string[] { "wvx" }) static
Definition at line 103 of file Video.Values.cs.
X_Msvideo
readonly Video Juniper.MediaType.Video.X_Msvideo = new Video("x-msvideo", new string[] { "avi" }) static
Definition at line 104 of file Video.Values.cs.
X_Sgi_Movie
readonly Video Juniper.MediaType.Video.X_Sgi_Movie = new Video("x-sgi-movie", new string[] { "movie" }) static
Definition at line 105 of file Video.Values.cs.
X_Smv
readonly Video Juniper.MediaType.Video.X_Smv = new Video("x-smv", new string[] { "smv" }) static
Definition at line 106 of file Video.Values.cs.
Property Documentation
Extensions
ReadOnlyCollection<string> Juniper.MediaType.Extensions get inherited
Definition at line 211 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.UpdateLookupTables().
PrimaryExtension
string Juniper.MediaType.PrimaryExtension get inherited
Definition at line 213 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
SubTypeName
string Juniper.MediaType.SubTypeName get inherited
Definition at line 207 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
TypeName
string Juniper.MediaType.TypeName get inherited
Definition at line 205 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
Value
string Juniper.MediaType.Value get inherited
Definition at line 203 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.MediaType(), Juniper.MediaType.ToString(), and Juniper.MediaType.UpdateLookupTables().
Weight
float Juniper.MediaType.Weight get inherited
Definition at line 209 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.ToString().
The documentation for this class was generated from the following files:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Video.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Video.Values.cs