Juniper: Juniper.Zip.Decompressor Class Reference
Juniper.Zip.Decompressor Class Reference
Functions for dealing with Zip files.
Static Public Member Functions
static Stream GetFile (string zipFile, string filePath, IProgress prog=null)
Retrieves a single file from a zip file.
static void DecompressDirectory (string inputZipFile, string outputDirectory, IProgress prog=null, Action< Exception > error=null)
Dump the contents of a zip file out to disk.
static IEnumerable< ZipEntry > ZipEntries (string inputZipFile, IProgress prog=null)
Lists all of the entries (both files and directories) in a zip file.
static IEnumerable< string > RecurseFiles (string inputZipFile, IProgress prog=null)
Lists all of the files in a zip file.
static IEnumerable< string > RecurseDirectories (string inputZipFile, IProgress prog=null)
Lists all of the directories in a zip file.
Static Private Member Functions
static Decompressor ()
Detailed Description
Functions for dealing with Zip files.
Definition at line 15 of file Decompressor.cs.
Constructor & Destructor Documentation
Decompressor()
static Juniper.Zip.Decompressor.Decompressor () inline static private
Definition at line 22 of file Decompressor.cs.
         {
             ZipStrings.UseUnicode = true;
         }
Member Function Documentation
DecompressDirectory()
static void Juniper.Zip.Decompressor.DecompressDirectory (string inputZipFile, string outputDirectory, IProgress prog = null, Action< Exception > error = null) inline static
Dump the contents of a zip file out to disk.
Parameters
inputZipFile The zip file to decompress
outputDirectory The location to which to dump the files.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
error A callback for any errors that occur. Defaults to null (i.e. no error reporting).
Definition at line 62 of file Decompressor.cs.
         {
             prog?.Report(0);
             if (!File.Exists(inputZipFile))
             {
                 throw new FileNotFoundException("File not found! " + inputZipFile, inputZipFile);
             }
             else
             {
                 using (var zf = new ZipFile(inputZipFile))
                 {
                     zf.IsStreamOwner = true;
                     prog.ForEach(zf.Cast<ZipEntry>(), (zipEntry, p) =>
                     {
                         var fullZipToPath = Path.Combine(outputDirectory, zipEntry.Name);
                         if (zipEntry.IsDirectory)
{
                             DirectoryExt.CreateDirectory(fullZipToPath);
                         }
                         else if (zipEntry.IsFile
                             && (!File.Exists(fullZipToPath)
                                 || FileExt.TryDelete(fullZipToPath)))
{
                             var directoryName = Path.GetDirectoryName(fullZipToPath);
                             if (directoryName.Length > 0)
{
                                 DirectoryExt.CreateDirectory(directoryName);
                             }
                             using (var zipStream = zf.GetInputStream(zipEntry))
                             using (var streamWriter = new ProgressStream(File.Create(fullZipToPath), zipEntry.Size, p))
{
                                 zipStream.CopyTo(streamWriter);
                             }
                         }
                     }, error);
                 }
             }
         }
References System.IO.DirectoryExt.CreateDirectory(), and System.IO.FileExt.TryDelete().
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Install().
GetFile()
static Stream Juniper.Zip.Decompressor.GetFile (string zipFile, string filePath, IProgress prog = null) inline static
Retrieves a single file from a zip file.
Parameters
zipFile The zip file in which to find the file.
filePath The file to find in the zip file.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Definition at line 33 of file Decompressor.cs.
         {
             prog?.Report(0);
             using (var file = new ZipFile(zipFile))
             {
                 file.IsStreamOwner = true;
                 var entryIndex = file.FindEntry(filePath, true);
                 if (entryIndex > -1)
                 {
                     var entry = file[entryIndex];
                     using (var stream = file.GetInputStream(entry))
                     {
                         return new ProgressStream(stream, entry.Size, prog);
                     }
                 }
                 else
                 {
                     throw new FileNotFoundException($"Could not find file {filePath} in zip file {zipFile}", $"{zipFile}::{filePath}");
                 }
             }
         }
RecurseDirectories()
static IEnumerable<string> Juniper.Zip.Decompressor.RecurseDirectories (string inputZipFile, IProgress prog = null) inline static
Lists all of the directories in a zip file.
Parameters
inputZipFile A filepath to the zip file to scan.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Returns
A lazy collection of ZipEntries that are directories.
Definition at line 154 of file Decompressor.cs.
         {
             foreach (var zipEntry in ZipEntries(inputZipFile, prog))
             {
                 if (zipEntry.IsDirectory)
                 {
                     yield return PathExt.FixPath(zipEntry.Name);
                 }
             }
         }
References System.IO.PathExt.FixPath().
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall().
RecurseFiles()
static IEnumerable<string> Juniper.Zip.Decompressor.RecurseFiles (string inputZipFile, IProgress prog = null) inline static
Lists all of the files in a zip file.
Parameters
inputZipFile A filepath to the zip file to scan.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Returns
A lazy collection of ZipEntries that are files.
Definition at line 137 of file Decompressor.cs.
         {
             foreach (var zipEntry in ZipEntries(inputZipFile, prog))
             {
                 if (zipEntry.IsFile)
                 {
                     yield return PathExt.FixPath(zipEntry.Name);
                 }
             }
         }
References System.IO.PathExt.FixPath().
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall().
ZipEntries()
static IEnumerable<ZipEntry> Juniper.Zip.Decompressor.ZipEntries (string inputZipFile, IProgress prog = null) inline static
Lists all of the entries (both files and directories) in a zip file.
Parameters
inputZipFile A filepath to the zip file to scan.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Returns
A lazy collection of ZipEntries
Definition at line 108 of file Decompressor.cs.
         {
             prog?.Report(0);
             if (File.Exists(inputZipFile))
             {
                 using (var zf = new ZipFile(inputZipFile))
                 {
                     zf.IsStreamOwner = true;
                     var progs = prog.Split(zf.Count);
                     for (var i = 0; i < zf.Count; ++i)
                     {
                         var p = progs[i];
                         p?.Report(0);
                         yield return zf[i];
                     }
                 }
             }
             prog?.Report(1);
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Zip/Decompressor.cs