Juniper: Juniper.Sound.DefaultInteractionAudio Class Reference
Juniper.Sound.DefaultInteractionAudio Class Reference
Public Member Functions
virtual void Install (bool reset)
Install, with or without a full reset.
void Reinstall ()
Reinstall the object with a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
virtual void Awake ()
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
CachingStrategy GetCachingStrategy ()
async Task< AudioClip > PreloadSpeech (string text, string voiceName, float rateChange, float pitchChange)
float PlayAction (Interaction action, Transform pose, AbstractHapticDevice haptics, bool randomizePitch)
float PlayAction (Interaction action, Transform pose, AbstractHapticDevice haptics)
float PlayAction (Interaction action, Transform pose, bool randomizePitch)
float PlayAction (Interaction action, Transform pose)
float PlayAction (Interaction action, AbstractHapticDevice haptics, bool randomizePitch)
float PlayAction (Interaction action, AbstractHapticDevice haptics)
float PlayAction (Interaction action, bool randomizePitch)
float PlayAction (Interaction action)
float PlayAudioClip (AudioClip clip, Transform pose, bool randomizePitch)
float PlayAudioClip (AudioClip clip, Transform pose)
float PlayAudioClip (AudioClip clip, bool randomizePitch)
float PlayAudioClip (AudioClip clip)
async Task EnableDopplerAsync (bool value)
AudioSource Spatialize (AudioSource audioSource, AudioMixerGroup group)
AudioSource Spatialize (AudioSource audioSource)
void SetDefaultMixerGroup (AudioSource audioSource)
void StopZone (string zoneName)
void PauseZone (string zoneName)
void PlayZone (string zoneName)
Static Public Member Functions
static HapticExpression GetHapticExpressions (Interaction action)
Converts an Interaction into a haptic expression to be able to play.
Public Attributes
string CachePrefix
A sub directory in StreamingAssets to which TTS audio files will be cached.
AudioClipCollection soundOnClosed
The sound to play when an Widgets.Openable object has been closed.
AudioClipCollection soundOnDisabled
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
AudioClipCollection soundOnDragged
The sound to play when a Widgets.Draggable has been moved more than 10cm.
AudioClipCollection soundOnEntered
The sound to play when a cursor first hovers over any Widgets.Touchable.
AudioClipCollection soundOnError
The sound to play when an operation needs to indicate an error.
AudioClipCollection soundOnExited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
AudioClipCollection soundOnOpened
The sound to play when an Widgets.Openable object has been opened.
AudioClipCollection soundOnReleased
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
AudioClipCollection soundOnScrolled
The sound to play when a scrollable section is moved a certain distance.
AudioClipCollection soundOnSelected
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
AudioClipCollection soundOnSuccess
The sound to play when a long-running operating needs to indicate success.
AudioClip soundOnStartUp
The sound to play when the application first starts up.
AudioClip soundOnShutDown
The sound to play right before the application shuts down.
AudioMixerGroup defaultMixerGroup
The audio mixer to use with ResonanceAudio
float dopplerLevel = 0.68f
Protected Member Functions
virtual void UninstallSpatialization (AudioSource audioSource)
virtual AudioSource InternalSpatialize (AudioSource audioSource, AudioMixerGroup group)
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Protected Attributes
AudioListener listener
Properties
bool IsTextToSpeechAvailable [get]
virtual string DefaultAudioMixer [get]
Detailed Description
Definition at line 3 of file DefaultInteractionAudio.cs.
Member Function Documentation
Awake()
virtual void Juniper.Sound.AbstractInteractionAudio.Awake () inline virtual inherited
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
Definition at line 241 of file InteractionAudio.cs.
         {
 #if UNITY_EDITOR
             this.ReceiveCredentials();
 #endif
             Install(false);
             camT = DisplayManager.MainCamera.transform;
 #if UNITY_MODULES_AUDIO
             startUp = new SingleAudioClipCollection(soundOnStartUp, false);
             shutDown = new SingleAudioClipCollection(soundOnShutDown, false);
             InitializeInteractionAudioSources();
 #endif
             if (!string.IsNullOrEmpty(azureRegion)
                 && !string.IsNullOrEmpty(azureApiKey)
                 && !string.IsNullOrEmpty(azureResourceName))
             {
                 var cache = GetCachingStrategy();
                 tts = new TextToSpeechClient(
                     azureRegion,
                     azureApiKey,
                     azureResourceName,
                     new JsonFactory<Voice[]>(),
 #if UNITY_STANDALONE_WIN || UNITY_WSA
                     AudioFormat.Audio24KHz160KbitrateMonoMP3,
 #else
                     AudioFormat.Riff16KHz16BitMonoPCM,
 #endif
                     new NAudioAudioDataDecoder(),
                     cache);
             }
         }
References Juniper.Sound.AudioFormat.Audio24KHz160KbitrateMonoMP3, Juniper.Sound.AbstractInteractionAudio.azureApiKey, Juniper.Sound.AbstractInteractionAudio.azureRegion, Juniper.Sound.AbstractInteractionAudio.azureResourceName, Juniper.Sound.AbstractInteractionAudio.camT, Juniper.Sound.AbstractInteractionAudio.GetCachingStrategy(), Juniper.Sound.AbstractInteractionAudio.InitializeInteractionAudioSources(), Juniper.Sound.AbstractInteractionAudio.Install(), Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.Sound.AudioFormat.Riff16KHz16BitMonoPCM, Juniper.Sound.AbstractInteractionAudio.shutDown, Juniper.Sound.AbstractInteractionAudio.soundOnShutDown, Juniper.Sound.AbstractInteractionAudio.soundOnStartUp, Juniper.Sound.AbstractInteractionAudio.startUp, and Juniper.Sound.AbstractInteractionAudio.tts.
EnableDopplerAsync()
async Task Juniper.Sound.AbstractInteractionAudio.EnableDopplerAsync (bool value) inline inherited
Definition at line 491 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             await JuniperSystem.OnMainThreadAsync(() =>
             {
                 var audioSources = Find.All<AudioSource>();
                 var doppler = value ? dopplerLevel : 0;
                 foreach (var audioSource in audioSources)
                 {
                     audioSource.dopplerLevel = doppler;
                 }
             });
 #endif
             // burn a frame
             await Task.Yield();
         }
References Juniper.JuniperSystem.OnMainThreadAsync().
GetCachingStrategy()
CachingStrategy Juniper.Sound.AbstractInteractionAudio.GetCachingStrategy () inline inherited
Definition at line 278 of file InteractionAudio.cs.
         {
             if (string.IsNullOrEmpty(CachePrefix))
             {
                 return new CachingStrategy
                 {
                     new StreamingAssetsCacheLayer(Path.Combine("Azure", "CognitiveServices"))
                 };
             }
             else
             {
                 return new CachingStrategy
                 {
                     new StreamingAssetsCacheLayer(Path.Combine(CachePrefix, "Azure", "CognitiveServices"))
                 };
             }
         }
References Juniper.Sound.AbstractInteractionAudio.CachePrefix.
Referenced by Juniper.Sound.AbstractInteractionAudio.Awake().
GetHapticExpressions()
static HapticExpression Juniper.Sound.AbstractInteractionAudio.GetHapticExpressions (Interaction action) inline static inherited
Converts an Interaction into a haptic expression to be able to play.
Returns
The haptic expressions.
Parameters
action Action.
Definition at line 58 of file InteractionAudio.cs.
         {
             switch (action)
             {
                 case Interaction.Closed:
                 return HapticExpression.Heavy;
                 case Interaction.PressedDisabled:
                 case Interaction.ClickedDisabled:
                 return HapticExpression.Warning;
                 case Interaction.DraggingStarted:
                 case Interaction.Dragged:
                 case Interaction.DraggingEnded:
                 return HapticExpression.SelectionChange;
                 case Interaction.Error:
                 return HapticExpression.Error;
                 case Interaction.Opened:
                 return HapticExpression.Medium;
                 case Interaction.Clicked:
                 return HapticExpression.Light;
                 case Interaction.Success:
                 return HapticExpression.Success;
                 default:
                 return HapticExpression.None;
             }
         }
Install()
virtual void Juniper.Sound.AbstractInteractionAudio.Install (bool reset) inline virtual inherited
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IO.IInstallable.
Definition at line 177 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             listener = DisplayManager.MainCamera.Ensure<AudioListener>();
 #endif
         }
References Juniper.Sound.AbstractInteractionAudio.listener, and Juniper.Display.AbstractDisplayManager.MainCamera.
Referenced by Juniper.Sound.AbstractInteractionAudio.Awake(), and Juniper.Sound.AbstractInteractionAudio.Reinstall().
InternalSpatialize()
virtual AudioSource Juniper.Sound.AbstractInteractionAudio.InternalSpatialize (AudioSource audioSource, AudioMixerGroup group) inline protected virtual inherited
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Parameters
audioSource
group
Returns
Definition at line 660 of file InteractionAudio.cs.
         {
             audioSource.outputAudioMixerGroup = group == null
                 ? defaultMixerGroup
                 : group;
             audioSource.spatialBlend = 1;
             audioSource.spatialize = true;
             audioSource.spatializePostEffects = true;
             audioSource.dopplerLevel = dopplerLevel;
             return audioSource;
         }
PauseZone()
void Juniper.Sound.AbstractInteractionAudio.PauseZone (string zoneName) inline inherited
Definition at line 689 of file InteractionAudio.cs.
         {
             JuniperSystem.OnMainThread(() =>
             {
                 var audioSources = Find.All<AudioSource>(a => !a.CompareTag(INTERACTION_SOUND_TAG));
                 foreach (var audioSource in audioSources)
                 {
                     if (audioSource.IsInZone(zoneName)
                         && audioSource.isPlaying)
                     {
                         audioSource.Pause();
                     }
                 }
             });
         }
References Juniper.JuniperSystem.OnMainThread().
PlayAction() [1/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action, Transform pose, AbstractHapticDevice haptics, bool randomizePitch) inline inherited
Definition at line 384 of file InteractionAudio.cs.
         {
             if (action == Interaction.None)
             {
                 return 0;
             }
             else
             {
                 if (haptics != null)
                 {
                     var expr = GetHapticExpressions(action);
                     if (expr != HapticExpression.None)
                     {
                         haptics.Play(expr);
                     }
                 }
 #if UNITY_MODULES_AUDIO
                 var clips = GetClipCollection(action);
                 var reallyRandomize = randomizePitch && clips?.RandomizeClipPitch == true;
                 var clip = clips?.Random();
                 if (clip != null)
                 {
                     return PlayAudioClip(clip, pose, reallyRandomize);
                 }
 #endif
                 return 0;
             }
         }
References Juniper.Haptics.AbstractHapticDevice.Play().
PlayAction() [2/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action, Transform pose, AbstractHapticDevice haptics) inline inherited
Definition at line 414 of file InteractionAudio.cs.
         {
             return PlayAction(action, pose, haptics, false);
         }
PlayAction() [3/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action, Transform pose, bool randomizePitch) inline inherited
Definition at line 419 of file InteractionAudio.cs.
         {
             return PlayAction(action, pose, null, randomizePitch);
         }
PlayAction() [4/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action, Transform pose) inline inherited
Definition at line 424 of file InteractionAudio.cs.
         {
             return PlayAction(action, pose, null, false);
         }
PlayAction() [5/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action, AbstractHapticDevice haptics, bool randomizePitch) inline inherited
Definition at line 429 of file InteractionAudio.cs.
         {
             return PlayAction(action, camT, haptics, randomizePitch);
         }
PlayAction() [6/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action, AbstractHapticDevice haptics) inline inherited
Definition at line 434 of file InteractionAudio.cs.
         {
             return PlayAction(action, camT, haptics, false);
         }
PlayAction() [7/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action, bool randomizePitch) inline inherited
Definition at line 439 of file InteractionAudio.cs.
         {
             return PlayAction(action, camT, null, randomizePitch);
         }
PlayAction() [8/8]
float Juniper.Sound.AbstractInteractionAudio.PlayAction (Interaction action) inline inherited
Definition at line 444 of file InteractionAudio.cs.
         {
             return PlayAction(action, camT, null, false);
         }
PlayAudioClip() [1/4]
float Juniper.Sound.AbstractInteractionAudio.PlayAudioClip (AudioClip clip, Transform pose, bool randomizePitch) inline inherited
Definition at line 449 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             var audioSource = GetAudioSource(clip);
             audioSource.loop = false;
             if (randomizePitch)
             {
                 audioSource.pitch = UnityEngine.Random.Range(0.9f, 1.1f);
             }
             audioSource.transform.position = pose.position;
             var deltaP = listener.transform.position - audioSource.transform.position;
             if (deltaP.sqrMagnitude < 0.0625f)
             {
                 audioSource.transform.position +=
                     0.25f * listener.transform.forward
                     + 0.125f * listener.transform.up
                     + 0.05f * listener.transform.right;
             }
             audioSource.transform.rotation = pose.rotation;
             audioSource.Activate();
             audioSource.Play();
             return audioSource.clip.length;
 #else
             return 0;
 #endif
         }
PlayAudioClip() [2/4]
float Juniper.Sound.AbstractInteractionAudio.PlayAudioClip (AudioClip clip, Transform pose) inline inherited
Definition at line 477 of file InteractionAudio.cs.
         {
             return PlayAudioClip(clip, pose, false);
         }
PlayAudioClip() [3/4]
float Juniper.Sound.AbstractInteractionAudio.PlayAudioClip (AudioClip clip, bool randomizePitch) inline inherited
Definition at line 481 of file InteractionAudio.cs.
         {
             return PlayAudioClip(clip, camT, randomizePitch);
         }
PlayAudioClip() [4/4]
float Juniper.Sound.AbstractInteractionAudio.PlayAudioClip (AudioClip clip) inline inherited
Definition at line 486 of file InteractionAudio.cs.
         {
             return PlayAudioClip(clip, camT, false);
         }
PlayZone()
void Juniper.Sound.AbstractInteractionAudio.PlayZone (string zoneName) inline inherited
Definition at line 705 of file InteractionAudio.cs.
         {
             JuniperSystem.OnMainThread(() =>
             {
                 var audioSources = Find.All<AudioSource>(a => !a.CompareTag(INTERACTION_SOUND_TAG));
                 foreach (var audioSource in audioSources)
                 {
                     if (!audioSource.IsInZone(zoneName)
                         && audioSource.isPlaying)
                     {
                         audioSource.Stop();
                     }
                     else if (audioSource.playOnAwake
                         && !audioSource.isPlaying)
                     {
                         audioSource.Activate();
                         audioSource.Play();
                     }
                 }
             });
         }
References Juniper.JuniperSystem.OnMainThread().
PreloadSpeech()
async Task<AudioClip> Juniper.Sound.AbstractInteractionAudio.PreloadSpeech (string text, string voiceName, float rateChange, float pitchChange) inline inherited
Definition at line 296 of file InteractionAudio.cs.
         {
             var audioData = await tts.GetDecodedAudioAsync(text, voiceName, rateChange, pitchChange);
             var reader = new BinaryReader(audioData.DataStream);
             var clip = AudioClip.Create(
                 text,
                 (int)audioData.Samples,
                 audioData.Format.Channels,
                 audioData.Format.SampleRate,
                 true,
                 floats =>
                 {
                     for (int i = 0; i < floats.Length; ++i)
                     {
                         floats[i] = reader.ReadSingle();
                     }
                 },
                 pos =>
                 {
                     reader.BaseStream.Position = pos;
                 });
             clip.LoadAudioData();
             return clip;
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync(), and Juniper.Sound.AbstractInteractionAudio.tts.
Reinstall()
void Juniper.Sound.AbstractInteractionAudio.Reinstall () inline inherited
Reinstall the object with a full reset.
Implements Juniper.IO.IInstallable.
Definition at line 184 of file InteractionAudio.cs.
         {
             Install(true);
         }
References Juniper.Sound.AbstractInteractionAudio.Install().
SetDefaultMixerGroup()
void Juniper.Sound.AbstractInteractionAudio.SetDefaultMixerGroup (AudioSource audioSource) inline inherited
Definition at line 571 of file InteractionAudio.cs.
         {
             audioSource.outputAudioMixerGroup = defaultMixerGroup;
         }
Spatialize() [1/2]
AudioSource Juniper.Sound.AbstractInteractionAudio.Spatialize (AudioSource audioSource, AudioMixerGroup group) inline inherited
Definition at line 561 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, group);
         }
Spatialize() [2/2]
AudioSource Juniper.Sound.AbstractInteractionAudio.Spatialize (AudioSource audioSource) inline inherited
Definition at line 566 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, defaultMixerGroup);
         }
StopZone()
void Juniper.Sound.AbstractInteractionAudio.StopZone (string zoneName) inline inherited
Definition at line 673 of file InteractionAudio.cs.
         {
             JuniperSystem.OnMainThread(() =>
             {
                 var audioSources = Find.All<AudioSource>(a => !a.CompareTag(INTERACTION_SOUND_TAG));
                 foreach (var audioSource in audioSources)
                 {
                     if (audioSource.IsInZone(zoneName)
                         && audioSource.isPlaying)
                     {
                         audioSource.Stop();
                     }
                 }
             });
         }
References Juniper.JuniperSystem.OnMainThread().
Uninstall()
virtual void Juniper.Sound.AbstractInteractionAudio.Uninstall () inline virtual inherited
Remove platform-specific features from the object.
Implements Juniper.IO.IInstallable.
Definition at line 224 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             DisplayManager.MainCamera.Ensure<AudioListener>();
             FindAudioSources();
             foreach (var audioSource in audioSources)
             {
                 UninstallSpatialization(audioSource);
             }
 #endif
         }
References Juniper.Sound.AbstractInteractionAudio.audioSources, Juniper.Sound.AbstractInteractionAudio.FindAudioSources(), Juniper.Display.AbstractDisplayManager.MainCamera, and Juniper.Sound.AbstractInteractionAudio.UninstallSpatialization().
UninstallSpatialization()
virtual void Juniper.Sound.AbstractInteractionAudio.UninstallSpatialization (AudioSource audioSource) inline protected virtual inherited
Definition at line 576 of file InteractionAudio.cs.
         { }
Referenced by Juniper.Sound.AbstractInteractionAudio.Uninstall().
Member Data Documentation
CachePrefix
string Juniper.Sound.AbstractInteractionAudio.CachePrefix inherited
A sub directory in StreamingAssets to which TTS audio files will be cached.
Definition at line 94 of file InteractionAudio.cs.
Referenced by Juniper.Sound.AbstractInteractionAudio.GetCachingStrategy().
defaultMixerGroup
AudioMixerGroup Juniper.Sound.AbstractInteractionAudio.defaultMixerGroup inherited
The audio mixer to use with ResonanceAudio
Definition at line 583 of file InteractionAudio.cs.
dopplerLevel
float Juniper.Sound.AbstractInteractionAudio.dopplerLevel = 0.68f inherited
Definition at line 586 of file InteractionAudio.cs.
listener
AudioListener Juniper.Sound.AbstractInteractionAudio.listener protected inherited
Definition at line 522 of file InteractionAudio.cs.
Referenced by Juniper.Sound.AbstractInteractionAudio.Install().
soundOnClosed
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnClosed inherited
The sound to play when an Widgets.Openable object has been closed.
Definition at line 100 of file InteractionAudio.cs.
soundOnDisabled
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnDisabled inherited
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
Definition at line 106 of file InteractionAudio.cs.
soundOnDragged
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnDragged inherited
The sound to play when a Widgets.Draggable has been moved more than 10cm.
Definition at line 111 of file InteractionAudio.cs.
soundOnEntered
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnEntered inherited
The sound to play when a cursor first hovers over any Widgets.Touchable.
Definition at line 116 of file InteractionAudio.cs.
soundOnError
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnError inherited
The sound to play when an operation needs to indicate an error.
Definition at line 121 of file InteractionAudio.cs.
soundOnExited
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnExited inherited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
Definition at line 127 of file InteractionAudio.cs.
soundOnOpened
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnOpened inherited
The sound to play when an Widgets.Openable object has been opened.
Definition at line 132 of file InteractionAudio.cs.
soundOnReleased
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnReleased inherited
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
Definition at line 137 of file InteractionAudio.cs.
soundOnScrolled
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnScrolled inherited
The sound to play when a scrollable section is moved a certain distance.
Definition at line 142 of file InteractionAudio.cs.
soundOnSelected
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnSelected inherited
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
Definition at line 147 of file InteractionAudio.cs.
soundOnShutDown
AudioClip Juniper.Sound.AbstractInteractionAudio.soundOnShutDown inherited
The sound to play right before the application shuts down.
Definition at line 520 of file InteractionAudio.cs.
Referenced by Juniper.Sound.AbstractInteractionAudio.Awake().
soundOnStartUp
AudioClip Juniper.Sound.AbstractInteractionAudio.soundOnStartUp inherited
The sound to play when the application first starts up.
Definition at line 515 of file InteractionAudio.cs.
Referenced by Juniper.Sound.AbstractInteractionAudio.Awake().
soundOnSuccess
AudioClipCollection Juniper.Sound.AbstractInteractionAudio.soundOnSuccess inherited
The sound to play when a long-running operating needs to indicate success.
Definition at line 152 of file InteractionAudio.cs.
Property Documentation
DefaultAudioMixer
virtual string Juniper.Sound.AbstractInteractionAudio.DefaultAudioMixer get protected inherited
Definition at line 589 of file InteractionAudio.cs.
         {
             get
             {
                 return "defaultAudioMixer";
             }
         }
IsTextToSpeechAvailable
bool Juniper.Sound.AbstractInteractionAudio.IsTextToSpeechAvailable get inherited
Definition at line 155 of file InteractionAudio.cs.
         {
             get
             {
                 return tts != null
                     && tts.IsAvailable == true;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Sound/DefaultInteractionAudio.cs