Juniper: Juniper.Mathematics.AbstractStatisticsCollection< T > Class Template Reference
Juniper.Mathematics.AbstractStatisticsCollection< T > Class Template Reference abstract
An abstract class for a collection wrapper that can automatically compute statistics on the values contained within.
Public Member Functions
IEnumerator< T > GetEnumerator ()
Returns an enumerator that iterates through the collection.
void Add (T item)
Adds an item to the collection, and recalculates the statistical values.
void Clear ()
Clears the collection and resets the statistics to null.
bool Contains (T item)
Returns true if the give item is in the collection.
void CopyTo (T[] array, int arrayIndex)
Copies the elements of the collection to an Array, starting at a particular Array index.
bool Remove (T item)
Remove an item from the collection.
int IndexOf (T item)
Determines the index of the specified item in the underlying collection.
void Insert (int index, T item)
Insert an item at an arbitrary point in the collection.
void RemoveAt (int index)
Remove an item at the specified index from the collection.
bool Append (T value, int numStandardDeviations, int minSamples=2)
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Public Attributes
int Count => collect.Count
Returns the number of items in the collection.
bool IsReadOnly => collect.IsReadOnly
Gets a value indicating whether this collection is read only.
T? Delta => Subtract(Maximum, Minimum)
The difference between the Maximum and Minimum
T? Median => Add(Minimum, Divide(Delta, 2))
The midpoint between the Maximum and the Minimum
Protected Member Functions
AbstractStatisticsCollection (IList< T > collection, T zero, T min, T max)
Creates a new collection analyzer out of a generic collection.
AbstractStatisticsCollection (int capacity, T zero, T min, T max)
Creates a new collection analyzer with a RingBuffer as the underlying collection.
void RecomputeStatistics ()
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
void UpdateStatistics (T value)
Recalculate statistics that don't need to perform a full collection scan.
abstract T Add (T a, T b)
Implementing classes can define how two values get added (because C# generics cannot specify operator constraints)
abstract T Subtract (T a, T b)
Implementing classes can define how two values get subtracted (because C# generics cannot specify operator constraints)
abstract T Multiply (T a, T b)
Implementing classes can define how two values get multiplied (because C# generics cannot specify operator constraints)
abstract T Scale (T a, float b)
Implementing classes can define how a value gets scaled by a scalar (because C# generics cannot specify operator constraints)
abstract T Divide (T a, float b)
Implementing classes can define how a value gets divided by a scalar (because C# generics cannot specify operator constraints)
abstract T Sqrt (T value)
Implementing classes can define how calculate the square root of a value (because C# generics cannot specify operator constraints)
abstract T Abs (T value)
Implementing classes can define how calculate the absolute value of a value (because C# generics cannot specify operator constraints)
abstract bool LessThan (T a, T b)
Implementing classes can define how two values get compared (because C# generics cannot specify operator constraints)
Properties
T? Maximum [get, private set]
The maximum value in the list, if there are any values in the list.
T? Minimum [get, private set]
The minimum value in the list, if there are any values in the list.
T? Mean [get, private set]
The arithmetic mean of the values in the list, if there are any values in the list.
T? Variance [get, private set]
The variance of all the values in the list, if there are any values in the list.
T? StandardDeviation [get, private set]
The standard deviation of all the values in the list, if there are any values in the list.
bool IsSaturated [get]
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
T this[int index] [get, set]
Gets or sets the element at the specified index.
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Returns an enumerator that iterates through the collection.
T? Add (T? a, T? b)
Coalesces null values for performing Add(T, T).
T? Subtract (T? a, T? b)
Coalesces null values for performing Subtract(T, T).
T? Multiply (T? a, T? b)
Coalesces null values for performing Multiply(T, T).
T? Scale (T? a, float b)
Coalesces null values for performing Scale(T, float).
T? Divide (T? a, float b)
Coalesces null values for performing Divide(T, float).
T Min (T? a, T b)
Coalesces null values for performing Min(T, T).
T Max (T? a, T b)
Coalesces null values for performing Max(T, T).
T? Sqrt (T? value)
Coalesces null values for performing Sqrt(T).
T? Abs (T? value)
Coalesces null values for performing Abs(T, T).
bool LessThan (T? a, T? b)
Coalesces null values for performing LessThan(T, T).
Private Attributes
readonly T Zero
The value that represents 0 for T.
readonly T MinValue
The value that represents the minimum vaule for T (e.g. float.MinValue).
readonly T MaxValue
The value that represents the maximum value for T (e.g.
readonly IList< T > collect
The collection being wrapped.
Detailed Description
An abstract class for a collection wrapper that can automatically compute statistics on the values contained within.
Type Constraints
T : struct
Definition at line 12 of file AbstractStatisticsCollection.cs.
Constructor & Destructor Documentation
AbstractStatisticsCollection() [1/2]
Juniper.Mathematics.AbstractStatisticsCollection< T >.AbstractStatisticsCollection (IList< T > collection, T zero, T min, T max) inline protected
Creates a new collection analyzer out of a generic collection.
Parameters
collection Collection.
zero The value that represents Zero for T
min The value that represents Minimum value for T
max The value that represents Minimum value for T
Definition at line 298 of file AbstractStatisticsCollection.cs.
         {
             collect = collection;
             Zero = zero;
             MinValue = min;
             MaxValue = max;
         }
AbstractStatisticsCollection() [2/2]
Juniper.Mathematics.AbstractStatisticsCollection< T >.AbstractStatisticsCollection (int capacity, T zero, T min, T max) inline protected
Creates a new collection analyzer with a RingBuffer as the underlying collection.
Parameters
capacity Capacity.
zero The value that represents Zero for T
one The value that represents One for T
Definition at line 312 of file AbstractStatisticsCollection.cs.
             : this(new RingBuffer<T>(capacity), zero, min, max)
         {
         }
Member Function Documentation
Abs() [1/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Abs (T value) protected pure virtual
Implementing classes can define how calculate the absolute value of a value (because C# generics cannot specify operator constraints)
Parameters
value
Returns
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Abs(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append().
Abs() [2/2]
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Abs (T? value) inline private
Coalesces null values for performing Abs(T, T).
Parameters
value
Returns
Definition at line 583 of file AbstractStatisticsCollection.cs.
         {
             if (value is null)
             {
                 return null;
             }
             else
             {
                 return Abs(value.Value);
             }
         }
Add() [1/3]
void Juniper.Mathematics.AbstractStatisticsCollection< T >.Add (T item) inline
Adds an item to the collection, and recalculates the statistical values.
Parameters
item
Definition at line 161 of file AbstractStatisticsCollection.cs.
         {
             collect.Add(item);
             UpdateStatistics(item);
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Add(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Add() [2/3]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Add (T a, T b) protected pure virtual
Implementing classes can define how two values get added (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Add() [3/3]
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Add (T? a, T? b) inline private
Coalesces null values for performing Add(T, T).
Parameters
a
b
Returns
Definition at line 455 of file AbstractStatisticsCollection.cs.
         {
             return Add(a ?? Zero, b ?? Zero);
         }
Append()
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.Append (T value, int numStandardDeviations, int minSamples = 2) inline
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Parameters
value
numStandardDeviations
minSamples The minimum number of collected samples in the collection to have before rejecting outliers. MinSamples must be at least 2.
Returns
True if the item was added, false if it was rejected.
Definition at line 275 of file AbstractStatisticsCollection.cs.
         {
             var delta = Abs(Subtract(value, Mean));
             var isInlier = Count < 2
                 || Count < minSamples
                 || LessThan(delta, Scale(StandardDeviation, numStandardDeviations));
             if (isInlier)
             {
                 Add(value);
             }
             return isInlier;
         }
Clear()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.Clear () inline
Clears the collection and resets the statistics to null.
Definition at line 170 of file AbstractStatisticsCollection.cs.
         {
             collect.Clear();
             Minimum = null;
             Maximum = null;
             Mean = null;
             Variance = null;
             StandardDeviation = null;
         }
Referenced by Juniper.Widgets.QualityDegrader.Update().
Contains()
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.Contains (T item) inline
Returns true if the give item is in the collection.
Parameters
item The item to search for.
Returns
True if the item is found. False if it is not.
Definition at line 185 of file AbstractStatisticsCollection.cs.
         {
             return collect.Contains(item);
         }
CopyTo()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.CopyTo (T [] array, int arrayIndex) inline
Copies the elements of the collection to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
arrayIndex The zero-based index in array at which copying begins.
Exceptions
System.ArgumentNullException array is null
System.ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from arrayIndex to the end of the destination array .
Definition at line 206 of file AbstractStatisticsCollection.cs.
         {
             collect.CopyTo(array, arrayIndex);
         }
Divide() [1/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Divide (T a, float b) protected pure virtual
Implementing classes can define how a value gets divided by a scalar (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Divide(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Divide() [2/2]
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Divide (T? a, float b) inline private
Coalesces null values for performing Divide(T, float).
Parameters
a
b
Returns
Definition at line 513 of file AbstractStatisticsCollection.cs.
         {
             if (a is null)
             {
                 return null;
             }
             else
             {
                 return Divide(a.Value, b);
             }
         }
GetEnumerator() [1/2]
IEnumerator<T> Juniper.Mathematics.AbstractStatisticsCollection< T >.GetEnumerator () inline
Returns an enumerator that iterates through the collection.
Returns
Definition at line 138 of file AbstractStatisticsCollection.cs.
         {
             for (var i = 0; i < collect.Count; ++i)
             {
                 yield return collect[i];
             }
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.GetEnumerator().
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.Mathematics.AbstractStatisticsCollection< T >.GetEnumerator () inline private
Returns an enumerator that iterates through the collection.
Returns
Definition at line 150 of file AbstractStatisticsCollection.cs.
         {
 #pragma warning disable HAA0401 // Possible allocation of reference type enumerator
             return GetEnumerator();
 #pragma warning restore HAA0401 // Possible allocation of reference type enumerator
         }
IndexOf()
int Juniper.Mathematics.AbstractStatisticsCollection< T >.IndexOf (T item) inline
Determines the index of the specified item in the underlying collection.
Parameters
item The object to location in the collection.
Returns
The index of item if found in the list; otherwise, -1.
If an object occurs multiple times in the list, the IndexOf method always returns the first instance found.
Definition at line 232 of file AbstractStatisticsCollection.cs.
         {
             return collect.IndexOf(item);
         }
Insert()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.Insert (int index, T item) inline
Insert an item at an arbitrary point in the collection.
Parameters
index The index at which to insert item .
item The value to insert.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
Definition at line 245 of file AbstractStatisticsCollection.cs.
         {
             collect.Insert(index, item);
             UpdateStatistics(item);
         }
LessThan() [1/2]
abstract bool Juniper.Mathematics.AbstractStatisticsCollection< T >.LessThan (T a, T b) protected pure virtual
Implementing classes can define how two values get compared (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.LessThan(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Max(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Min().
LessThan() [2/2]
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.LessThan (T? a, T? b) inline private
Coalesces null values for performing LessThan(T, T).
Parameters
a
b
Returns
Definition at line 601 of file AbstractStatisticsCollection.cs.
         {
             if (a is null || b is null)
             {
                 return false;
             }
             else
             {
                 return LessThan(a.Value, b.Value);
             }
         }
Max()
T Juniper.Mathematics.AbstractStatisticsCollection< T >.Max (T? a, T b) inline private
Coalesces null values for performing Max(T, T).
Parameters
a
b
Returns
Definition at line 549 of file AbstractStatisticsCollection.cs.
         {
             if (a is object && LessThan(b, a.Value))
             {
                 return a.Value;
             }
             else
             {
                 return b;
             }
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Min()
T Juniper.Mathematics.AbstractStatisticsCollection< T >.Min (T? a, T b) inline private
Coalesces null values for performing Min(T, T).
Parameters
a
b
Returns
Definition at line 531 of file AbstractStatisticsCollection.cs.
         {
             if (a is object && LessThan(a.Value, b))
             {
                 return a.Value;
             }
             else
             {
                 return b;
             }
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Multiply() [1/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Multiply (T a, T b) protected pure virtual
Implementing classes can define how two values get multiplied (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Multiply(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Multiply() [2/2]
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Multiply (T? a, T? b) inline private
Coalesces null values for performing Multiply(T, T).
Parameters
a
b
Returns
Definition at line 477 of file AbstractStatisticsCollection.cs.
         {
             if (a is null || b is null)
             {
                 return null;
             }
             else
             {
                 return Multiply(a.Value, b.Value);
             }
         }
RecomputeStatistics()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.RecomputeStatistics () inline protected
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
Definition at line 321 of file AbstractStatisticsCollection.cs.
         {
             Maximum = Minimum = Mean = Variance = StandardDeviation = null;
             if (Count > 0)
             {
                 Minimum = MaxValue;
                 Maximum = MinValue;
                 for (var i = 0; i < Count; ++i)
                 {
                     var v = this[i];
                     Minimum = Min(Minimum, v);
                     Maximum = Max(Maximum, v);
                     Mean = Add(Mean, Divide(v, Count));
                 }
                 if (Count > 1)
                 {
                     Variance = Zero;
                     for (var i = 0; i < Count; ++i)
                     {
                         var v = this[i];
                         var residual = Subtract(v, Mean);
                         Variance = Add(Variance, Divide(Multiply(residual, residual), Count - 1));
                     }
                     StandardDeviation = Sqrt(Variance);
                 }
             }
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Remove(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RemoveAt().
Remove()
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.Remove (T item) inline
Remove an item from the collection.
Parameters
item The value to remove.
Returns
True if the item existed in the buffer and was removed. False otherwise.
Definition at line 216 of file AbstractStatisticsCollection.cs.
         {
             var removed = collect.Remove(item);
             RecomputeStatistics();
             return removed;
         }
RemoveAt()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.RemoveAt (int index) inline
Remove an item at the specified index from the collection.
Parameters
index The index at which to remove an item.
Exceptions
System.ArgumentOutOfRangeException index is less than 0 or greater than Count - 1.
Definition at line 258 of file AbstractStatisticsCollection.cs.
         {
             collect.RemoveAt(index);
             RecomputeStatistics();
         }
Scale() [1/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Scale (T a, float b) protected pure virtual
Implementing classes can define how a value gets scaled by a scalar (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Scale(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Scale() [2/2]
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Scale (T? a, float b) inline private
Coalesces null values for performing Scale(T, float).
Parameters
a
b
Returns
Definition at line 495 of file AbstractStatisticsCollection.cs.
         {
             if (a is null)
             {
                 return null;
             }
             else
             {
                 return Scale(a.Value, b);
             }
         }
Sqrt() [1/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Sqrt (T value) protected pure virtual
Implementing classes can define how calculate the square root of a value (because C# generics cannot specify operator constraints)
Parameters
value
Returns
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Sqrt(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Sqrt() [2/2]
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Sqrt (T? value) inline private
Coalesces null values for performing Sqrt(T).
Parameters
value
Returns
Definition at line 566 of file AbstractStatisticsCollection.cs.
         {
             if (value is null)
             {
                 return null;
             }
             else
             {
                 return Sqrt(value.Value);
             }
         }
Subtract() [1/2]
abstract T Juniper.Mathematics.AbstractStatisticsCollection< T >.Subtract (T a, T b) protected pure virtual
Implementing classes can define how two values get subtracted (because C# generics cannot specify operator constraints)
Parameters
a
b
Returns
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Subtract(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Subtract() [2/2]
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Subtract (T? a, T? b) inline private
Coalesces null values for performing Subtract(T, T).
Parameters
a
b
Returns
Definition at line 466 of file AbstractStatisticsCollection.cs.
         {
             return Subtract(a ?? Zero, b ?? Zero);
         }
UpdateStatistics()
void Juniper.Mathematics.AbstractStatisticsCollection< T >.UpdateStatistics (T value) inline protected
Recalculate statistics that don't need to perform a full collection scan.
Parameters
value
Definition at line 356 of file AbstractStatisticsCollection.cs.
         {
             Minimum = Min(Minimum, value);
             Maximum = Max(Maximum, value);
             var prevMean = Mean;
             var residual = Subtract(value, prevMean);
             Mean = Add(prevMean, Divide(residual, Count));
             if (Count > 1)
             {
                 var secondResidual = Subtract(value, Mean);
                 var n2 = Count - 2;
                 var n1 = Count - 1;
                 Variance = Divide(
                     Add(
                         Scale(Variance, n2),
                         Multiply(residual, secondResidual)),
                     n1);
                 StandardDeviation = Sqrt(Variance);
             }
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Add(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Insert().
Member Data Documentation
collect
readonly IList<T> Juniper.Mathematics.AbstractStatisticsCollection< T >.collect private
The collection being wrapped.
Definition at line 32 of file AbstractStatisticsCollection.cs.
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.AbstractStatisticsCollection(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Add(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Clear(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Contains(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.CopyTo(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.GetEnumerator(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.IndexOf(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Insert(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Remove(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RemoveAt().
Count
int Juniper.Mathematics.AbstractStatisticsCollection< T >.Count => collect.Count
Returns the number of items in the collection.
Definition at line 77 of file AbstractStatisticsCollection.cs.
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append(), Juniper.World.CompassRose.PrintDebugReport(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Delta
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Delta => Subtract(Maximum, Minimum)
The difference between the Maximum and Minimum
Definition at line 107 of file AbstractStatisticsCollection.cs.
IsReadOnly
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.IsReadOnly => collect.IsReadOnly
Gets a value indicating whether this collection is read only.
true if is read only; otherwise, false.
Definition at line 102 of file AbstractStatisticsCollection.cs.
MaxValue
readonly T Juniper.Mathematics.AbstractStatisticsCollection< T >.MaxValue private
The value that represents the maximum value for T (e.g.
float.MinValue).
Definition at line 27 of file AbstractStatisticsCollection.cs.
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.AbstractStatisticsCollection(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics().
Median
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Median => Add(Minimum, Divide(Delta, 2))
The midpoint between the Maximum and the Minimum
Definition at line 112 of file AbstractStatisticsCollection.cs.
MinValue
readonly T Juniper.Mathematics.AbstractStatisticsCollection< T >.MinValue private
The value that represents the minimum vaule for T (e.g. float.MinValue).
Definition at line 22 of file AbstractStatisticsCollection.cs.
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.AbstractStatisticsCollection(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics().
Zero
readonly T Juniper.Mathematics.AbstractStatisticsCollection< T >.Zero private
The value that represents 0 for T.
Definition at line 17 of file AbstractStatisticsCollection.cs.
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.AbstractStatisticsCollection(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Add(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Subtract().
Property Documentation
IsSaturated
bool Juniper.Mathematics.AbstractStatisticsCollection< T >.IsSaturated get
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
true if is saturated; otherwise, false.
Definition at line 84 of file AbstractStatisticsCollection.cs.
         {
             get
             {
                 if (collect is RingBuffer<T> buf)
                 {
                     return buf.IsSaturated;
                 }
                 else
                 {
                     return false;
                 }
             }
         }
Referenced by Juniper.Widgets.QualityDegrader.Update().
Maximum
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Maximum get private set
The maximum value in the list, if there are any values in the list.
Definition at line 38 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Clear(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Mean
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Mean get private set
The arithmetic mean of the values in the list, if there are any values in the list.
Definition at line 54 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Clear(), Juniper.Widgets.Shaker.PrintDebugReport(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), Juniper.World.CompassRose.SetNorth(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
Minimum
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Minimum get private set
The minimum value in the list, if there are any values in the list.
Definition at line 46 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Clear(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
StandardDeviation
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.StandardDeviation get private set
The standard deviation of all the values in the list, if there are any values in the list.
Definition at line 70 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Append(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Clear(), Juniper.Widgets.Shaker.PrintDebugReport(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
this[int index]
T Juniper.Mathematics.AbstractStatisticsCollection< T >.this[int index] get set
Gets or sets the element at the specified index.
Parameters
index An index into the buffer, modulated by the buffer length.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
The element at the specified index.
Definition at line 123 of file AbstractStatisticsCollection.cs.
         {
             get
             {
                 return collect[index];
             }
             set
             {
                 collect[index] = value;
             }
         }
Variance
T? Juniper.Mathematics.AbstractStatisticsCollection< T >.Variance get private set
The variance of all the values in the list, if there are any values in the list.
Definition at line 62 of file AbstractStatisticsCollection.cs.
         {
             get; private set;
         }
Referenced by Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.Clear(), Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.RecomputeStatistics(), and Juniper.Mathematics.AbstractStatisticsCollection< Vector4 >.UpdateStatistics().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Mathematics/AbstractStatisticsCollection.cs