Juniper: Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT > Class Template Reference
Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT > Class Template Reference
Public Member Functions
GoogleMapsClient (string apiKey, string signingKey, IJsonFactory< MetadataTypeT > metadataDecoder, IJsonFactory< GeocodingResponse > geocodingDecoder, CachingStrategy cache)
void ClearError ()
bool IsMetadataCached (string pano)
bool IsImageCached (string pano)
Task< GeocodingResponse > ReverseGeocodeAsync (LatLngPoint latLng, IProgress prog=null)
async Task< MetadataTypeT > GetMetadataAsync (string pano, int searchRadius=50, IProgress prog=null)
async Task< MetadataTypeT > SearchMetadataAsync (string placeName, int searchRadius=50, IProgress prog=null)
async Task< MetadataTypeT > GetMetadataAsync (LatLngPoint latLng, int searchRadius=50, IProgress prog=null)
async Task< MetadataTypeT > SearchMetadataAsync (string searchLocation, string searchPano, LatLngPoint searchPoint, int searchRadius, IProgress prog=null)
async Task< MetadataTypeT > FindClosestMetadataAsync (LatLngPoint point, int searchRadius)
async Task< Stream > GetImageAsync (string pano, int fov, int heading, int pitch, IProgress prog=null)
Public Attributes
string Status => lastError?.Message ?? "NONE"
IEnumerable<(ContentReference fileRef, MetadataTypeT metadata)> CachedMetadataFiles
IReadOnlyCollection< MetadataTypeT > CachedMetadata
Private Member Functions
async Task< T > LoadAsync< T > (IDeserializer< T > deserializer, ContentReference fileRef, IProgress prog)
MetadataTypeT Cache (MetadataTypeT metadata)
Private Attributes
readonly IJsonFactory< GeocodingResponse > geocodingDecoder
readonly IJsonFactory< MetadataTypeT > metadataDecoder
readonly Dictionary< string, MetadataTypeT > metadataCache = new Dictionary<string, MetadataTypeT>()
readonly List< string > knownImages = new List<string>()
readonly string apiKey
readonly string signingKey
readonly CachingStrategy cache
Exception lastError
Detailed Description
Type Constraints
MetadataTypeT : MetadataResponse
Definition at line 16 of file GoogleMapsClient.cs.
Constructor & Destructor Documentation
GoogleMapsClient()
Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient (string apiKey, string signingKey, IJsonFactory< MetadataTypeT > metadataDecoder, IJsonFactory< GeocodingResponse > geocodingDecoder, CachingStrategy cache) inline
Definition at line 30 of file GoogleMapsClient.cs.
         {
             this.apiKey = apiKey ?? throw new ArgumentNullException(nameof(apiKey));
             this.signingKey = signingKey ?? throw new ArgumentNullException(nameof(signingKey));
             this.metadataDecoder = metadataDecoder ?? throw new ArgumentNullException(nameof(metadataDecoder));
             this.geocodingDecoder = geocodingDecoder ?? throw new ArgumentNullException(nameof(geocodingDecoder));
             this.cache = cache ?? throw new ArgumentNullException(nameof(cache));
             foreach (var (fileRef, metadata) in cache.Get(metadataDecoder))
             {
                 if (metadata.Location != null)
                 {
                     _ = Cache(metadata);
                     var imageRef = metadata.Pano_ID + MediaType.Image.Jpeg;
                     if (cache.IsCached(imageRef))
                     {
                         knownImages.Add(metadata.Pano_ID);
                     }
                 }
                 else
                 {
                     _ = cache.Delete(fileRef);
                 }
             }
             foreach(var fileRef in cache.GetContentReferences(MediaType.Image.Jpeg))
             {
                 knownImages.Add(fileRef.CacheID);
             }
             knownImages.Sort();
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.apiKey, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.cache, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.Cache(), Juniper.IO.CachingStrategy.Delete(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.geocodingDecoder, Juniper.IO.CachingStrategy.GetContentReferences(), Juniper.IO.CachingStrategy.IsCached(), Juniper.MediaType.Image.Jpeg, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.knownImages, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataDecoder, and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.signingKey.
Member Function Documentation
Cache()
MetadataTypeT Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.Cache (MetadataTypeT metadata) inline private
Definition at line 191 of file GoogleMapsClient.cs.
         {
             if (metadata != null)
             {
                 metadataCache[metadata.Location.ToString(CultureInfo.InvariantCulture)] = metadata;
                 metadataCache[metadata.Pano_ID] = metadata;
             }
             return metadata;
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataCache.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
ClearError()
void Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.ClearError () inline
Definition at line 66 of file GoogleMapsClient.cs.
         {
             lastError = null;
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.lastError.
FindClosestMetadataAsync()
async Task<MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.FindClosestMetadataAsync (LatLngPoint point, int searchRadius) inline
Definition at line 202 of file GoogleMapsClient.cs.
         {
             var closestMetadata = await GetMetadataAsync(point, searchRadius, null)
                 .ConfigureAwait(false);
             var minDistance = closestMetadata?.Location.Distance(point)
                 ?? float.MaxValue;
             foreach (var metadata in metadataCache.Values)
             {
                 var distance = point.Distance(metadata.Location);
                 if (distance < minDistance)
                 {
                     minDistance = distance;
                     closestMetadata = metadata;
                 }
             }
             return closestMetadata;
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataCache.
GetImageAsync()
async Task<Stream> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetImageAsync (string pano, int fov, int heading, int pitch, IProgress prog = null) inline
Definition at line 222 of file GoogleMapsClient.cs.
         {
             var imageStream = await cache.GetStreamAsync(new ImageRequest(apiKey, signingKey, new Size(640, 640))
             {
                 Pano = pano,
                 FOV = fov,
                 Heading = heading,
                 Pitch = pitch
             }, prog).ConfigureAwait(false);
             if(imageStream is object
                 && knownImages.MaybeAdd(pano))
             {
                 knownImages.Sort();
             }
             return imageStream;
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.apiKey, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.cache, Juniper.IO.CachingStrategy.GetStreamAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.knownImages, and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.signingKey.
GetMetadataAsync() [1/2]
async Task<MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync (string pano, int searchRadius = 50, IProgress prog = null) inline
Definition at line 128 of file GoogleMapsClient.cs.
         {
             return Cache(await LoadAsync(metadataDecoder, new MetadataRequest(apiKey, signingKey)
             {
                 Pano = pano,
                 Radius = searchRadius
             }, prog).ConfigureAwait(false));
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.apiKey, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.Cache(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataDecoder, and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.signingKey.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.FindClosestMetadataAsync(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
GetMetadataAsync() [2/2]
async Task<MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync (LatLngPoint latLng, int searchRadius = 50, IProgress prog = null) inline
Definition at line 146 of file GoogleMapsClient.cs.
         {
             return Cache(await LoadAsync(metadataDecoder, new MetadataRequest(apiKey, signingKey)
             {
                 Location = latLng,
                 Radius = searchRadius
             }, prog).ConfigureAwait(false));
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.apiKey, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.Cache(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataDecoder, and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.signingKey.
IsImageCached()
bool Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.IsImageCached (string pano) inline
Definition at line 82 of file GoogleMapsClient.cs.
         {
             return knownImages.BinarySearch(pano) >= 0;
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.knownImages.
IsMetadataCached()
bool Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.IsMetadataCached (string pano) inline
Definition at line 77 of file GoogleMapsClient.cs.
         {
             return metadataCache.ContainsKey(pano);
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataCache.
LoadAsync< T >()
async Task<T> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.LoadAsync< T > (IDeserializer< T > deserializer, ContentReference fileRef, IProgress prog) inline private
Definition at line 87 of file GoogleMapsClient.cs.
         {
             var value = await cache
                 .LoadAsync(deserializer, fileRef, prog)
                 .ConfigureAwait(false);
             if (value is MetadataTypeT metadata)
             {
                 if (metadata.Status != System.Net.HttpStatusCode.OK
                     || string.IsNullOrEmpty(metadata.Pano_ID)
                     || metadata.Location is null)
                 {
                     if (cache.IsCached(fileRef))
                     {
                         _ = cache.Delete(fileRef);
                     }
                     value = default;
                 }
                 else
                 {
                     var metadataRef = new ContentReference(metadata.Pano_ID, MediaType.Application.Json);
                     if (!cache.IsCached(metadataRef))
                     {
                         await cache
                             .CopyToAsync(fileRef, cache, metadataRef)
                             .ConfigureAwait(false);
                     }
                 }
             }
             return value;
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.cache, Juniper.IO.CachingStrategy.Delete(), Juniper.IO.CachingStrategy.IsCached(), and Juniper.MediaType.Application.Json.
ReverseGeocodeAsync()
Task<GeocodingResponse> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.ReverseGeocodeAsync (LatLngPoint latLng, IProgress prog = null) inline
Definition at line 120 of file GoogleMapsClient.cs.
         {
             return LoadAsync(geocodingDecoder, new ReverseGeocodingRequest(apiKey)
             {
                 Location = latLng
             }, prog);
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.apiKey, and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.geocodingDecoder.
SearchMetadataAsync() [1/2]
async Task<MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync (string placeName, int searchRadius = 50, IProgress prog = null) inline
Definition at line 137 of file GoogleMapsClient.cs.
         {
             return Cache(await LoadAsync(metadataDecoder, new MetadataRequest(apiKey, signingKey)
             {
                 Place = placeName,
                 Radius = searchRadius
             }, prog).ConfigureAwait(false));
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.apiKey, Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.Cache(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataDecoder, and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.signingKey.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
SearchMetadataAsync() [2/2]
async Task<MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync (string searchLocation, string searchPano, LatLngPoint searchPoint, int searchRadius, IProgress prog = null) inline
Definition at line 155 of file GoogleMapsClient.cs.
         {
             try
             {
                 if (metadataCache.ContainsKey(searchLocation))
                 {
                     return metadataCache[searchLocation];
                 }
                 var metaSubProgs = prog.Split("Searching by Pano_ID", "Searching by Lat/Lng", "Searching by Location Name");
                 if (searchPano != null)
                 {
                     return await GetMetadataAsync(searchPano, searchRadius, metaSubProgs[0])
                         .ConfigureAwait(false);
                 }
                 if (searchPoint != null)
                 {
                     return await GetMetadataAsync(searchPoint, searchRadius, metaSubProgs[1])
                         .ConfigureAwait(false);
                 }
                 if (searchLocation != null)
                 {
                     return await SearchMetadataAsync(searchLocation, searchRadius, metaSubProgs[2])
                         .ConfigureAwait(false);
                 }
                 return default;
             }
             finally
             {
                 prog.Report(1);
             }
         }
References Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataCache, and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
Member Data Documentation
apiKey
readonly string Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.apiKey private
Definition at line 24 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetImageAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.ReverseGeocodeAsync(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
cache
readonly CachingStrategy Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.cache private
Definition at line 26 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetImageAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.LoadAsync< T >().
CachedMetadata
IReadOnlyCollection<MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.CachedMetadata
Initial value:
=>
            metadataCache.Values.ToArray()
Definition at line 74 of file GoogleMapsClient.cs.
CachedMetadataFiles
IEnumerable<(ContentReference fileRef, MetadataTypeT metadata)> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.CachedMetadataFiles
Initial value:
=>
            cache.Get(metadataDecoder)
Definition at line 71 of file GoogleMapsClient.cs.
geocodingDecoder
readonly IJsonFactory<GeocodingResponse> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.geocodingDecoder private
Definition at line 19 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.ReverseGeocodeAsync().
knownImages
readonly List<string> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.knownImages = new List<string>() private
Definition at line 22 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetImageAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.IsImageCached().
lastError
Exception Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.lastError private
Definition at line 28 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.ClearError().
metadataCache
readonly Dictionary<string, MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataCache = new Dictionary<string, MetadataTypeT>() private
Definition at line 21 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.Cache(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.FindClosestMetadataAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.IsMetadataCached(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
metadataDecoder
readonly IJsonFactory<MetadataTypeT> Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.metadataDecoder private
Definition at line 20 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
signingKey
readonly string Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.signingKey private
Definition at line 25 of file GoogleMapsClient.cs.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetImageAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetMetadataAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.SearchMetadataAsync().
Status
string Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.Status => lastError?.Message ?? "NONE"
Definition at line 64 of file GoogleMapsClient.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/GoogleMapsClient.cs