Juniper: Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient Class Reference
Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient Class Reference
Public Member Functions
TextToSpeechStreamClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat, CachingStrategy cache)
TextToSpeechStreamClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat)
async Task< Stream > GetAudioDataStreamAsync (string text, string voiceName, float rateChange=0, float pitchChange=0)
Task< Stream > GetAudioDataStreamAsync (string text, Voice voice, float rateChange=0, float pitchChange=0)
void ClearError ()
async Task< Voice[]> GetVoicesAsync ()
Protected Member Functions
async Task< string > GetAuthTokenAsync ()
Properties
virtual AudioFormat OutputFormat [get, set]
string AzureRegion [get]
CachingStrategy Cache [get]
bool IsAvailable = true [get, protected set]
Private Attributes
readonly string azureResourceName
Detailed Description
Definition at line 10 of file TextToSpeechStreamClient.cs.
Constructor & Destructor Documentation
TextToSpeechStreamClient() [1/2]
Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.TextToSpeechStreamClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat, CachingStrategy cache) inline
Definition at line 14 of file TextToSpeechStreamClient.cs.
             : base(azureRegion, azureSubscriptionKey, voiceListDecoder, cache)
         {
             if (string.IsNullOrEmpty(azureResourceName))
             {
                 throw new ArgumentException("Must provide a resource name that is tied to the subscription", nameof(azureResourceName));
             }
             this.azureResourceName = azureResourceName;
             OutputFormat = outputFormat
                 ?? throw new ArgumentException("Must provide an audio output format", nameof(outputFormat));
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.azureResourceName, and Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.OutputFormat.
TextToSpeechStreamClient() [2/2]
Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.TextToSpeechStreamClient (string azureRegion, string azureSubscriptionKey, string azureResourceName, IJsonDecoder< Voice[]> voiceListDecoder, AudioFormat outputFormat) inline
Definition at line 30 of file TextToSpeechStreamClient.cs.
             : this(azureRegion, azureSubscriptionKey, azureResourceName, voiceListDecoder, outputFormat, null)
         { }
Member Function Documentation
ClearError()
void Juniper.Speech.Azure.CognitiveServices.VoicesClient.ClearError () inline inherited
Definition at line 49 of file VoicesClient.cs.
         {
             IsAvailable = true;
         }
References Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable.
GetAudioDataStreamAsync() [1/2]
async Task<Stream> Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync (string text, string voiceName, float rateChange = 0, float pitchChange = 0) inline
Definition at line 34 of file TextToSpeechStreamClient.cs.
         {
             if (string.IsNullOrEmpty(text))
             {
                 throw new ArgumentException("Must provide some text to generate speech.", nameof(text));
             }
             if (string.IsNullOrEmpty(voiceName))
             {
                 throw new ArgumentException("Must provide a voice to generate speech.", nameof(voiceName));
             }
             try
             {
                 var ttsRequest = new TextToSpeechRequest(AzureRegion, azureResourceName, OutputFormat)
                 {
                     Text = text,
                     VoiceName = voiceName,
                     RateChange = rateChange,
                     PitchChange = pitchChange
                 };
                 if (!Cache.IsCached(ttsRequest))
                 {
                     ttsRequest.AuthToken = await GetAuthTokenAsync()
                         .ConfigureAwait(false);
                 }
                 return await Cache.OpenAsync(ttsRequest)
                     .ConfigureAwait(false);
             }
             catch
             {
                 IsAvailable = false;
                 throw;
             }
         }
References Juniper.Speech.Azure.CognitiveServices.AbstractAzureSpeechRequest< MediaTypeT >.AuthToken, Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion, Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.azureResourceName, Juniper.Speech.Azure.CognitiveServices.VoicesClient.Cache, Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable, Juniper.IO.CachingStrategy.IsCached(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.OutputFormat.
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechClient.GetDecodedAudioAsync().
GetAudioDataStreamAsync() [2/2]
Task<Stream> Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync (string text, Voice voice, float rateChange = 0, float pitchChange = 0) inline
Definition at line 72 of file TextToSpeechStreamClient.cs.
         {
             return GetAudioDataStreamAsync(text, voice?.ShortName, rateChange, pitchChange);
         }
References Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync().
GetAuthTokenAsync()
async Task<string> Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync () inline protected inherited
Definition at line 54 of file VoicesClient.cs.
         {
             try
             {
                 if (string.IsNullOrEmpty(authToken))
                 {
                     var plainText = new StringFactory();
                     var authRequest = new AuthTokenRequest(AzureRegion, azureSubscriptionKey);
                     authToken = await authRequest.DecodeAsync(plainText)
                         .ConfigureAwait(false);
                 }
                 return authToken;
             }
             catch
             {
                 IsAvailable = false;
                 throw;
             }
         }
References Juniper.Speech.Azure.CognitiveServices.VoicesClient.authToken, Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion, Juniper.Speech.Azure.CognitiveServices.VoicesClient.azureSubscriptionKey, and Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable.
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync().
GetVoicesAsync()
async Task<Voice[]> Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync () inline inherited
Definition at line 75 of file VoicesClient.cs.
         {
             try
             {
                 if (voices is null)
                 {
                     var voiceListRequest = new VoiceListRequest(AzureRegion);
                     if (!Cache.IsCached(voiceListRequest))
                     {
                         voiceListRequest.AuthToken = await GetAuthTokenAsync()
                             .ConfigureAwait(false);
                     }
                     voices = await Cache.LoadAsync(voiceListDecoder, voiceListRequest)
                         .ConfigureAwait(false);
                 }
                 return voices;
             }
             catch
             {
                 IsAvailable = false;
                 throw;
             }
         }
References Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion, Juniper.Speech.Azure.CognitiveServices.VoicesClient.Cache, Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable, Juniper.IO.CachingStrategy.IsCached(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.voiceListDecoder, and Juniper.Speech.Azure.CognitiveServices.VoicesClient.voices.
Member Data Documentation
azureResourceName
readonly string Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.azureResourceName private
Definition at line 12 of file TextToSpeechStreamClient.cs.
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.TextToSpeechStreamClient().
Property Documentation
AzureRegion
string Juniper.Speech.Azure.CognitiveServices.VoicesClient.AzureRegion get protected inherited
Definition at line 16 of file VoicesClient.cs.
 { get; }
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.VoicesClient().
Cache
CachingStrategy Juniper.Speech.Azure.CognitiveServices.VoicesClient.Cache get protected inherited
Definition at line 17 of file VoicesClient.cs.
 { get; }
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.VoicesClient().
IsAvailable
bool Juniper.Speech.Azure.CognitiveServices.VoicesClient.IsAvailable = true get protected set inherited
Definition at line 47 of file VoicesClient.cs.
 { get; protected set; } = true;
Referenced by Juniper.Speech.Azure.CognitiveServices.VoicesClient.ClearError(), Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetAuthTokenAsync(), and Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync().
OutputFormat
virtual AudioFormat Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.OutputFormat get set
Definition at line 28 of file TextToSpeechStreamClient.cs.
 { get; set; }
Referenced by Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), and Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.TextToSpeechStreamClient().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Azure/CognitiveServices/TextToSpeechStreamClient.cs