Juniper: Juniper.NeuroSky.MindWaveAdapter Class Reference
Juniper.NeuroSky.MindWaveAdapter Class Reference
An adapter for the NeuroSky MindWave device, converting the raw data elements to an object model.
Public Member Functions
MindWaveAdapter ()
Sets up a new connection to the MindWave device.
MindWaveAdapter (string serialPortName, Baudrate baudrate=DEFAULT_BAUD_RATE, SerialDataFormat format=DEFAULT_SERIAL_FORMAT, FilterType filterType=DEFAULT_MAINS_FILTER)
Setups up a new connection to the MindWave device.
MindWaveAdapter (string serialPortName, Baudrate baudrate, FilterType filterType=DEFAULT_MAINS_FILTER)
Setups up a new connection to the MindWave device.
MindWaveAdapter (string serialPortName, SerialDataFormat format, FilterType filterType=DEFAULT_MAINS_FILTER)
Setups up a new connection to the MindWave device.
MindWaveAdapter (string serialPortName, FilterType filterType)
Setups up a new connection to the MindWave device.
void Connect (string serialPortName, SerialDataFormat format)
Connect to a device.
void Connect (string serialPortName, Baudrate baudrate=DEFAULT_BAUD_RATE, SerialDataFormat format=DEFAULT_SERIAL_FORMAT)
Connect to a device.
void WriteStreamLog (int insertTimestamp, string msg)
void WriteDataLog (int insertTimestamp, string msg)
int ReadPackets (int numPackets)
bool DataValueChanged (DataType dataType)
float? GetDataValue (DataType dataType)
void SendByte (byte b)
Send a single byte to the device.
void Disconnect ()
Release the connection to the device.
void Dispose ()
Release and clean up the connection to the device.
Static Public Member Functions
static MindWaveAdapter FindAdapter (Baudrate baudrate=DEFAULT_BAUD_RATE, SerialDataFormat format=DEFAULT_SERIAL_FORMAT, FilterType filterType=DEFAULT_MAINS_FILTER)
Search the serial ports for a device that conforms to the expected MindWave behaviour.
static MindWaveAdapter FindAdapter (Baudrate baudrate, FilterType filterType=DEFAULT_MAINS_FILTER)
Search the serial ports for a device that conforms to the expected MindWave behaviour.
static MindWaveAdapter FindAdapter (SerialDataFormat format, FilterType filterType=DEFAULT_MAINS_FILTER)
Search the serial ports for a device that conforms to the expected MindWave behaviour.
static MindWaveAdapter FindAdapter (FilterType filterType)
Search the serial ports for a device that conforms to the expected MindWave behaviour.
Protected Member Functions
virtual void Dispose (bool disposing)
Release and clean up the connection to the device.
Properties
static int Version [get]
The firmware version for the device.
FilterType?? MainsFrequency [get, set]
Get or set the frequency of the mains electricity that needs to be filtered out of the brainwave signal.
Baudrate?? SerialBaudRate [get, set]
Get or set the serial communication rate.
bool? EnableAutoRead [get, set]
string StreamLogFileName [get, set]
bool? EnableStreamLog [get, set]
string DataLogFileName [get, set]
bool? EnableDataLog [get, set]
float? Battery [get]
float? PoorSignal [get]
float? Attention [get]
float? Meditation [get]
float? Delta [get]
float? Theta [get]
float? Alpha1 [get]
float? Alpha2 [get]
float? Beta1 [get]
float? Beta2 [get]
float? Gamma1 [get]
float? Gamma2 [get]
Private Attributes
const Baudrate DEFAULT_BAUD_RATE = Baudrate.TG_BAUD_9600
The serial communication baud rate to try.
const FilterType DEFAULT_MAINS_FILTER = FilterType.MWM15_FILTER_TYPE_60HZ
The mains electricity frequency to filter out of the signal.
const SerialDataFormat DEFAULT_SERIAL_FORMAT = SerialDataFormat.TG_STREAM_PACKETS
The format of the serial packets being sent by the device.
readonly int connectionId
The ID to use when calling the ThinkGear C-API functions.
string streamFileName
The file to read from, when reading data from a stored data file.
string dataFileName
File to which to log data.
bool connected
Flag to indicate whether or not a connection to the device has been made.
bool streamLogEnabled
Flag to indicate whether or not the connection is being used on a data log file, rather than a real device.
bool dataLogEnabled
Flag to indicate whether or not data is being logged to a file.
bool autoReadEnabled
Flag to indicate whether or not the device should be sending packets without requesting them.
Baudrate? baudrate
Serial communications rate.
FilterType? mainsFilter
Mains electricity frequency for filtering it out of the brainwave signal.
bool valueDisposed
Tracks whether or not the connection has already been disposed.
Detailed Description
An adapter for the NeuroSky MindWave device, converting the raw data elements to an object model.
Definition at line 12 of file MindWaveAdapter.cs.
Constructor & Destructor Documentation
MindWaveAdapter() [1/5]
Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter () inline
Sets up a new connection to the MindWave device.
Exceptions
IndexOutOfRangeException Thrown when too many connections have been made to the device.
OutOfMemoryException Thrown when there isn't enough memory on the device to allocate a new connection.
Definition at line 149 of file MindWaveAdapter.cs.
         {
             connectionId = TG_GetNewConnectionId();
             switch (connectionId)
             {
                 case -1:
                 throw new IndexOutOfRangeException("Too many connections have been made to the device.");
                 case -2:
                 throw new OutOfMemoryException("Not enough free memory to allocate a new connection.");
             }
         }
References Juniper.NeuroSky.MindWaveAdapter.connectionId.
Referenced by Juniper.NeuroSky.MindWaveAdapter.FindAdapter().
MindWaveAdapter() [2/5]
Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter (string serialPortName, Baudrate baudrate = DEFAULT_BAUD_RATE, SerialDataFormat format = DEFAULT_SERIAL_FORMAT, FilterType filterType = DEFAULT_MAINS_FILTER) inline
Setups up a new connection to the MindWave device.
Parameters
serialPortName
baudrate
format
filterType
Exceptions
IndexOutOfRangeException Thrown when too many connections have been made to the device.
OutOfMemoryException Thrown when there isn't enough memory on the device to allocate a new connection.
Definition at line 174 of file MindWaveAdapter.cs.
             : this()
         {
             Connect(serialPortName, baudrate, format);
             MainsFrequency = filterType;
         }
References Juniper.NeuroSky.MindWaveAdapter.baudrate, Juniper.NeuroSky.MindWaveAdapter.Connect(), and Juniper.NeuroSky.MindWaveAdapter.MainsFrequency.
MindWaveAdapter() [3/5]
Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter (string serialPortName, Baudrate baudrate, FilterType filterType = DEFAULT_MAINS_FILTER) inline
Setups up a new connection to the MindWave device.
Parameters
serialPortName
baudrate
filterType
Exceptions
IndexOutOfRangeException Thrown when too many connections have been made to the device.
OutOfMemoryException Thrown when there isn't enough memory on the device to allocate a new connection.
Definition at line 193 of file MindWaveAdapter.cs.
             : this(serialPortName, baudrate, DEFAULT_SERIAL_FORMAT, filterType) { }
MindWaveAdapter() [4/5]
Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter (string serialPortName, SerialDataFormat format, FilterType filterType = DEFAULT_MAINS_FILTER) inline
Setups up a new connection to the MindWave device.
Parameters
serialPortName
format
filterType
Exceptions
IndexOutOfRangeException Thrown when too many connections have been made to the device.
OutOfMemoryException Thrown when there isn't enough memory on the device to allocate a new connection.
Definition at line 208 of file MindWaveAdapter.cs.
             : this(serialPortName, DEFAULT_BAUD_RATE, format, filterType) { }
MindWaveAdapter() [5/5]
Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter (string serialPortName, FilterType filterType) inline
Setups up a new connection to the MindWave device.
Parameters
serialPortName
filterType
Exceptions
IndexOutOfRangeException Thrown when too many connections have been made to the device.
OutOfMemoryException Thrown when there isn't enough memory on the device to allocate a new connection.
Definition at line 222 of file MindWaveAdapter.cs.
             : this(serialPortName, DEFAULT_BAUD_RATE, DEFAULT_SERIAL_FORMAT, filterType) { }
Member Function Documentation
Connect() [1/2]
void Juniper.NeuroSky.MindWaveAdapter.Connect (string serialPortName, SerialDataFormat format) inline
Connect to a device.
Parameters
serialPortName
format
Definition at line 296 of file MindWaveAdapter.cs.
         {
             Connect(serialPortName, SerialBaudRate, format);
         }
References Juniper.NeuroSky.MindWaveAdapter.SerialBaudRate.
Referenced by Juniper.NeuroSky.MindWaveAdapter.DataValueChanged(), Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter(), Juniper.NeuroSky.MindWaveAdapter.ReadPackets(), and Juniper.NeuroSky.MindWaveAdapter.SendByte().
Connect() [2/2]
void Juniper.NeuroSky.MindWaveAdapter.Connect (string serialPortName, Baudrate baudrate = DEFAULT_BAUD_RATE, SerialDataFormat format = DEFAULT_SERIAL_FORMAT) inline
Connect to a device.
Parameters
serialPortName
baudrate
format
Exceptions
InvalidOperationException Thrown when a valid connection ID hasn't been allocated, or when baudrate is invalid for the device, or when format is invalid for the device.
Exception Thrown when serialPortName can't be opened for communication.
Definition at line 313 of file MindWaveAdapter.cs.
         {
             if (connected)
             {
                 Disconnect();
             }
             switch (TG_Connect(connectionId, serialPortName, baudrate, format))
             {
                 case -1:
                 throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                 case -2:
                 throw new Exception(serialPortName + " could not be opened as a serial communication port. Check that the name is a valid COM port on your system.");
                 case -3:
                 throw new InvalidOperationException(nameof(baudrate) + " is not a valid TG_BAUD_* value.");
                 case -4:
                 throw new InvalidOperationException(nameof(format) + " is not a valid TG_STREAM_* type.");
             }
             this.baudrate = baudrate;
             connected = true;
         }
References Juniper.NeuroSky.MindWaveAdapter.baudrate, Juniper.NeuroSky.MindWaveAdapter.connected, Juniper.NeuroSky.MindWaveAdapter.connectionId, and Juniper.NeuroSky.MindWaveAdapter.Disconnect().
DataValueChanged()
bool Juniper.NeuroSky.MindWaveAdapter.DataValueChanged (DataType dataType) inline
Definition at line 508 of file MindWaveAdapter.cs.
         {
             if (!connected)
             {
                 throw new InvalidOperationException("Cannot read from a closed connection. Please call " + nameof(Connect));
             }
             return TG_GetValueStatus(connectionId, dataType) != 0;
         }
References Juniper.NeuroSky.MindWaveAdapter.Connect(), Juniper.NeuroSky.MindWaveAdapter.connected, and Juniper.NeuroSky.MindWaveAdapter.connectionId.
Disconnect()
void Juniper.NeuroSky.MindWaveAdapter.Disconnect () inline
Release the connection to the device.
Definition at line 658 of file MindWaveAdapter.cs.
         {
             connected = false;
             TG_Disconnect(connectionId);
         }
References Juniper.NeuroSky.MindWaveAdapter.connected, and Juniper.NeuroSky.MindWaveAdapter.connectionId.
Referenced by Juniper.NeuroSky.MindWaveAdapter.Connect(), and Juniper.NeuroSky.MindWaveAdapter.Dispose().
Dispose() [1/2]
virtual void Juniper.NeuroSky.MindWaveAdapter.Dispose (bool disposing) inline protected virtual
Release and clean up the connection to the device.
Parameters
disposing
Definition at line 673 of file MindWaveAdapter.cs.
         {
             if (!valueDisposed)
             {
                 if (disposing)
                 {
                     if (connected)
                     {
                         Disconnect();
                     }
                     TG_FreeConnection(connectionId);
                 }
                 valueDisposed = true;
             }
         }
References Juniper.NeuroSky.MindWaveAdapter.connected, Juniper.NeuroSky.MindWaveAdapter.connectionId, Juniper.NeuroSky.MindWaveAdapter.Disconnect(), and Juniper.NeuroSky.MindWaveAdapter.valueDisposed.
Dispose() [2/2]
void Juniper.NeuroSky.MindWaveAdapter.Dispose () inline
Release and clean up the connection to the device.
Definition at line 694 of file MindWaveAdapter.cs.
         {
             Dispose(true);
         }
FindAdapter() [1/4]
static MindWaveAdapter Juniper.NeuroSky.MindWaveAdapter.FindAdapter (Baudrate baudrate = DEFAULT_BAUD_RATE, SerialDataFormat format = DEFAULT_SERIAL_FORMAT, FilterType filterType = DEFAULT_MAINS_FILTER) inline static
Search the serial ports for a device that conforms to the expected MindWave behaviour.
Parameters
baudrate
format
filterType
Returns
Definition at line 47 of file MindWaveAdapter.cs.
         {
             foreach (var portName in System.IO.Ports.SerialPort.GetPortNames())
             {
                 try
                 {
                     return new MindWaveAdapter(portName, baudrate, format, filterType);
                 }
                 catch
                 {
                 }
             }
             return null;
         }
References Juniper.NeuroSky.MindWaveAdapter.baudrate, and Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter().
Referenced by Juniper.NeuroSky.MindWaveAdapter.FindAdapter().
FindAdapter() [2/4]
static MindWaveAdapter Juniper.NeuroSky.MindWaveAdapter.FindAdapter (Baudrate baudrate, FilterType filterType = DEFAULT_MAINS_FILTER) inline static
Search the serial ports for a device that conforms to the expected MindWave behaviour.
Parameters
baudrate
filterType
Returns
Definition at line 69 of file MindWaveAdapter.cs.
         {
             return FindAdapter(baudrate, DEFAULT_SERIAL_FORMAT, filterType);
         }
References Juniper.NeuroSky.MindWaveAdapter.baudrate, Juniper.NeuroSky.MindWaveAdapter.DEFAULT_SERIAL_FORMAT, and Juniper.NeuroSky.MindWaveAdapter.FindAdapter().
FindAdapter() [3/4]
static MindWaveAdapter Juniper.NeuroSky.MindWaveAdapter.FindAdapter (SerialDataFormat format, FilterType filterType = DEFAULT_MAINS_FILTER) inline static
Search the serial ports for a device that conforms to the expected MindWave behaviour.
Parameters
format
filterType
Returns
Definition at line 80 of file MindWaveAdapter.cs.
         {
             return FindAdapter(DEFAULT_BAUD_RATE, format, filterType);
         }
References Juniper.NeuroSky.MindWaveAdapter.DEFAULT_BAUD_RATE, and Juniper.NeuroSky.MindWaveAdapter.FindAdapter().
FindAdapter() [4/4]
static MindWaveAdapter Juniper.NeuroSky.MindWaveAdapter.FindAdapter (FilterType filterType) inline static
Search the serial ports for a device that conforms to the expected MindWave behaviour.
Parameters
filterType
Returns
Definition at line 90 of file MindWaveAdapter.cs.
         {
             return FindAdapter(DEFAULT_BAUD_RATE, DEFAULT_SERIAL_FORMAT, filterType);
         }
References Juniper.NeuroSky.MindWaveAdapter.DEFAULT_BAUD_RATE, Juniper.NeuroSky.MindWaveAdapter.DEFAULT_SERIAL_FORMAT, and Juniper.NeuroSky.MindWaveAdapter.FindAdapter().
GetDataValue()
float? Juniper.NeuroSky.MindWaveAdapter.GetDataValue (DataType dataType) inline
Definition at line 518 of file MindWaveAdapter.cs.
         {
             if (connected)
             {
                 return TG_GetValue(connectionId, dataType);
             }
             else
             {
                 return null;
             }
         }
References Juniper.NeuroSky.MindWaveAdapter.connected, and Juniper.NeuroSky.MindWaveAdapter.connectionId.
ReadPackets()
int Juniper.NeuroSky.MindWaveAdapter.ReadPackets (int numPackets) inline
Definition at line 481 of file MindWaveAdapter.cs.
         {
             if (autoReadEnabled)
             {
                 return -1;
             }
             if (!connected)
             {
                 throw new InvalidOperationException("Cannot read from a closed connection. Please call " + nameof(Connect));
             }
             var bytesRead = TG_ReadPackets(connectionId, numPackets);
             switch (bytesRead)
             {
                 case -1:
                 throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                 case -2:
                 return 0;
                 case -3:
                 throw new Exception("I/O Error");
                 default:
                 return bytesRead;
             }
         }
References Juniper.NeuroSky.MindWaveAdapter.autoReadEnabled, Juniper.NeuroSky.MindWaveAdapter.Connect(), Juniper.NeuroSky.MindWaveAdapter.connected, and Juniper.NeuroSky.MindWaveAdapter.connectionId.
SendByte()
void Juniper.NeuroSky.MindWaveAdapter.SendByte (byte b) inline
Send a single byte to the device.
Parameters
b The byte to send.
Exceptions
InvalidOperationException Thrown when there is no connection, or if the connectionID is invalid, or if ThinkGear adapter is connected to a file stream log of data, rather than a real device.
Exception Thrown when some other, unexpected error occurs on the device.
Definition at line 637 of file MindWaveAdapter.cs.
         {
             if (!connected)
             {
                 throw new InvalidOperationException("Cannot write to a closed connection. Please call " + nameof(Connect));
             }
             switch (TG_SendByte(connectionId, b))
             {
                 case -1:
                 throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                 case -2:
                 throw new InvalidOperationException("Device is connected to a file stream, not a device.");
                 case -3:
                 throw new Exception("I/O Error");
             }
         }
References Juniper.NeuroSky.MindWaveAdapter.Connect(), Juniper.NeuroSky.MindWaveAdapter.connected, and Juniper.NeuroSky.MindWaveAdapter.connectionId.
WriteDataLog()
void Juniper.NeuroSky.MindWaveAdapter.WriteDataLog (int insertTimestamp, string msg) inline
Definition at line 462 of file MindWaveAdapter.cs.
         {
             if (!EnableDataLog)
             {
                 EnableDataLog = true;
             }
             if (EnableDataLog)
             {
                 switch (TG_WriteDataLog(connectionId, insertTimestamp, msg))
                 {
                     case -1:
                     throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                     case -2:
                     throw new Exception("Stream log is not open for writing.");
                 }
             }
         }
References Juniper.NeuroSky.MindWaveAdapter.connectionId, and Juniper.NeuroSky.MindWaveAdapter.EnableDataLog.
WriteStreamLog()
void Juniper.NeuroSky.MindWaveAdapter.WriteStreamLog (int insertTimestamp, string msg) inline
Definition at line 401 of file MindWaveAdapter.cs.
         {
             if (!EnableStreamLog)
             {
                 EnableStreamLog = true;
             }
             if (EnableStreamLog)
             {
                 switch (TG_WriteStreamLog(connectionId, insertTimestamp, msg))
                 {
                     case -1:
                     throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                     case -2:
                     throw new Exception("Stream log is not open for writing.");
                 }
             }
         }
References Juniper.NeuroSky.MindWaveAdapter.connectionId, and Juniper.NeuroSky.MindWaveAdapter.EnableStreamLog.
Member Data Documentation
autoReadEnabled
bool Juniper.NeuroSky.MindWaveAdapter.autoReadEnabled private
Flag to indicate whether or not the device should be sending packets without requesting them.
Definition at line 128 of file MindWaveAdapter.cs.
Referenced by Juniper.NeuroSky.MindWaveAdapter.ReadPackets().
baudrate
Baudrate? Juniper.NeuroSky.MindWaveAdapter.baudrate private
Serial communications rate.
Definition at line 133 of file MindWaveAdapter.cs.
Referenced by Juniper.NeuroSky.MindWaveAdapter.Connect(), Juniper.NeuroSky.MindWaveAdapter.FindAdapter(), and Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter().
connected
bool Juniper.NeuroSky.MindWaveAdapter.connected private
Flag to indicate whether or not a connection to the device has been made.
Definition at line 113 of file MindWaveAdapter.cs.
Referenced by Juniper.NeuroSky.MindWaveAdapter.Connect(), Juniper.NeuroSky.MindWaveAdapter.DataValueChanged(), Juniper.NeuroSky.MindWaveAdapter.Disconnect(), Juniper.NeuroSky.MindWaveAdapter.Dispose(), Juniper.NeuroSky.MindWaveAdapter.GetDataValue(), Juniper.NeuroSky.MindWaveAdapter.ReadPackets(), and Juniper.NeuroSky.MindWaveAdapter.SendByte().
connectionId
readonly int Juniper.NeuroSky.MindWaveAdapter.connectionId private
The ID to use when calling the ThinkGear C-API functions.
Definition at line 98 of file MindWaveAdapter.cs.
Referenced by Juniper.NeuroSky.MindWaveAdapter.Connect(), Juniper.NeuroSky.MindWaveAdapter.DataValueChanged(), Juniper.NeuroSky.MindWaveAdapter.Disconnect(), Juniper.NeuroSky.MindWaveAdapter.Dispose(), Juniper.NeuroSky.MindWaveAdapter.GetDataValue(), Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter(), Juniper.NeuroSky.MindWaveAdapter.ReadPackets(), Juniper.NeuroSky.MindWaveAdapter.SendByte(), Juniper.NeuroSky.MindWaveAdapter.WriteDataLog(), and Juniper.NeuroSky.MindWaveAdapter.WriteStreamLog().
dataFileName
string Juniper.NeuroSky.MindWaveAdapter.dataFileName private
File to which to log data.
Definition at line 108 of file MindWaveAdapter.cs.
dataLogEnabled
bool Juniper.NeuroSky.MindWaveAdapter.dataLogEnabled private
Flag to indicate whether or not data is being logged to a file.
Definition at line 123 of file MindWaveAdapter.cs.
DEFAULT_BAUD_RATE
const Baudrate Juniper.NeuroSky.MindWaveAdapter.DEFAULT_BAUD_RATE = Baudrate.TG_BAUD_9600 private
The serial communication baud rate to try.
Definition at line 28 of file MindWaveAdapter.cs.
Referenced by Juniper.NeuroSky.MindWaveAdapter.FindAdapter().
DEFAULT_MAINS_FILTER
const FilterType Juniper.NeuroSky.MindWaveAdapter.DEFAULT_MAINS_FILTER = FilterType.MWM15_FILTER_TYPE_60HZ private
The mains electricity frequency to filter out of the signal.
Definition at line 33 of file MindWaveAdapter.cs.
DEFAULT_SERIAL_FORMAT
const SerialDataFormat Juniper.NeuroSky.MindWaveAdapter.DEFAULT_SERIAL_FORMAT = SerialDataFormat.TG_STREAM_PACKETS private
The format of the serial packets being sent by the device.
Definition at line 38 of file MindWaveAdapter.cs.
Referenced by Juniper.NeuroSky.MindWaveAdapter.FindAdapter().
mainsFilter
FilterType? Juniper.NeuroSky.MindWaveAdapter.mainsFilter private
Mains electricity frequency for filtering it out of the brainwave signal.
Definition at line 138 of file MindWaveAdapter.cs.
streamFileName
string Juniper.NeuroSky.MindWaveAdapter.streamFileName private
The file to read from, when reading data from a stored data file.
Definition at line 103 of file MindWaveAdapter.cs.
streamLogEnabled
bool Juniper.NeuroSky.MindWaveAdapter.streamLogEnabled private
Flag to indicate whether or not the connection is being used on a data log file, rather than a real device.
Definition at line 118 of file MindWaveAdapter.cs.
valueDisposed
bool Juniper.NeuroSky.MindWaveAdapter.valueDisposed private
Tracks whether or not the connection has already been disposed.
Definition at line 667 of file MindWaveAdapter.cs.
Referenced by Juniper.NeuroSky.MindWaveAdapter.Dispose().
Property Documentation
Alpha1
float? Juniper.NeuroSky.MindWaveAdapter.Alpha1 get
Definition at line 579 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_ALPHA1);
             }
         }
Alpha2
float? Juniper.NeuroSky.MindWaveAdapter.Alpha2 get
Definition at line 587 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_ALPHA2);
             }
         }
Attention
float? Juniper.NeuroSky.MindWaveAdapter.Attention get
Definition at line 547 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_ATTENTION);
             }
         }
Battery
float? Juniper.NeuroSky.MindWaveAdapter.Battery get
Definition at line 531 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_BATTERY);
             }
         }
Beta1
float? Juniper.NeuroSky.MindWaveAdapter.Beta1 get
Definition at line 595 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_BETA1);
             }
         }
Beta2
float? Juniper.NeuroSky.MindWaveAdapter.Beta2 get
Definition at line 603 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_BETA2);
             }
         }
DataLogFileName
string Juniper.NeuroSky.MindWaveAdapter.DataLogFileName get set
Definition at line 421 of file MindWaveAdapter.cs.
         {
             get
             {
                 return dataFileName;
             }
             set
             {
                 dataFileName = value;
                 EnableDataLog = !string.IsNullOrEmpty(dataFileName);
             }
         }
Delta
float? Juniper.NeuroSky.MindWaveAdapter.Delta get
Definition at line 563 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_DELTA);
             }
         }
EnableAutoRead
bool? Juniper.NeuroSky.MindWaveAdapter.EnableAutoRead get set
Definition at line 337 of file MindWaveAdapter.cs.
         {
             get
             {
                 return autoReadEnabled;
             }
             set
             {
                 switch (TG_EnableAutoRead(connectionId, value ? 1 : 0))
                 {
                     case -1:
                     throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                     case -2:
                     throw new Exception("Unable to start auto-reading.");
                     case -3:
                     throw new Exception("Error while disabling auto-reading.");
                 }
                 autoReadEnabled = value;
             }
         }
EnableDataLog
bool? Juniper.NeuroSky.MindWaveAdapter.EnableDataLog get set
Definition at line 435 of file MindWaveAdapter.cs.
         {
             get
             {
                 return dataLogEnabled;
             }
             set
             {
                 if (string.IsNullOrEmpty(dataFileName))
                 {
                     value = false;
                 }
                 dataLogEnabled = false;
                 switch (TG_SetDataLog(connectionId, value ? dataFileName : null))
                 {
                     case -1:
                     throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                     case -2:
                     throw new Exception(dataFileName + " could not be opened for writing.");
                 }
                 dataLogEnabled = true;
             }
         }
Referenced by Juniper.NeuroSky.MindWaveAdapter.WriteDataLog().
EnableStreamLog
bool? Juniper.NeuroSky.MindWaveAdapter.EnableStreamLog get set
Definition at line 374 of file MindWaveAdapter.cs.
         {
             get
             {
                 return streamLogEnabled;
             }
             set
             {
                 if (string.IsNullOrEmpty(streamFileName))
                 {
                     value = false;
                 }
                 streamLogEnabled = false;
                 switch (TG_SetStreamLog(connectionId, value ? streamFileName : null))
                 {
                     case -1:
                     throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                     case -2:
                     throw new Exception(streamFileName + " could not be opened for writing.");
                 }
                 streamLogEnabled = true;
             }
         }
Referenced by Juniper.NeuroSky.MindWaveAdapter.WriteStreamLog().
Gamma1
float? Juniper.NeuroSky.MindWaveAdapter.Gamma1 get
Definition at line 611 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_GAMMA1);
             }
         }
Gamma2
float? Juniper.NeuroSky.MindWaveAdapter.Gamma2 get
Definition at line 619 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_GAMMA2);
             }
         }
MainsFrequency
FilterType?? Juniper.NeuroSky.MindWaveAdapter.MainsFrequency get set
Get or set the frequency of the mains electricity that needs to be filtered out of the brainwave signal.
Definition at line 229 of file MindWaveAdapter.cs.
         {
             get
             {
                 if (connected)
                 {
                     var value = MWM15_getFilterType(connectionId);
                     if (value < 0)
                     {
                         throw new Exception("Error while getting Filter Type on device.");
                     }
                     else if (value > 0)
                     {
                         mainsFilter = (FilterType)value;
                     }
                 }
                 return mainsFilter ?? DEFAULT_MAINS_FILTER;
             }
             set
             {
                 if (MWM15_setFilterType(connectionId, value) < 0)
                 {
                     throw new Exception("Error while setting Filter Type on device.");
                 }
                 mainsFilter = value;
             }
         }
Referenced by Juniper.NeuroSky.MindWaveAdapter.MindWaveAdapter().
Meditation
float? Juniper.NeuroSky.MindWaveAdapter.Meditation get
Definition at line 555 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_MEDITATION);
             }
         }
PoorSignal
float? Juniper.NeuroSky.MindWaveAdapter.PoorSignal get
Definition at line 539 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_POOR_SIGNAL);
             }
         }
SerialBaudRate
Baudrate?? Juniper.NeuroSky.MindWaveAdapter.SerialBaudRate get set
Get or set the serial communication rate.
Definition at line 262 of file MindWaveAdapter.cs.
         {
             get
             {
                 return baudrate ?? DEFAULT_BAUD_RATE;
             }
             set
             {
                 if (!connected)
                 {
                     throw new InvalidOperationException("Cannot write to a closed connection. Please call " + nameof(Connect));
                 }
                 switch (TG_SetBaudrate(connectionId, value))
                 {
                     case -1:
                     throw new InvalidOperationException("Invalid connection ID: " + connectionId);
                     case -2:
                     throw new InvalidOperationException(nameof(value) + " is not a valid TG_BAUD_* value.");
                     case -3:
                     throw new Exception("An error occured while attempting to set the baudrate on the device.");
                     case -4:
                     throw new InvalidOperationException("Device is connected to a file stream, not a device.");
                 }
                 baudrate = value;
             }
         }
Referenced by Juniper.NeuroSky.MindWaveAdapter.Connect().
StreamLogFileName
string Juniper.NeuroSky.MindWaveAdapter.StreamLogFileName get set
Definition at line 360 of file MindWaveAdapter.cs.
         {
             get
             {
                 return streamFileName;
             }
             set
             {
                 streamFileName = value;
                 EnableStreamLog = !string.IsNullOrEmpty(streamFileName);
             }
         }
Theta
float? Juniper.NeuroSky.MindWaveAdapter.Theta get
Definition at line 571 of file MindWaveAdapter.cs.
         {
             get
             {
                 return GetDataValue(DataType.TG_DATA_THETA);
             }
         }
Version
int Juniper.NeuroSky.MindWaveAdapter.Version static get
The firmware version for the device.
Definition at line 18 of file MindWaveAdapter.cs.
         {
             get
             {
                 return TG_GetVersion();
             }
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.NeuroSky/MindWaveAdapter.cs