Juniper: Juniper.HTTP.Server.HttpServer Class Reference
Juniper.HTTP.Server.HttpServer Class Reference
A wrapper around HttpListener that handles routing, HTTPS, and a default start page for DEBUG running.
Public Member Functions
HttpServer ()
bool SetOptions (Dictionary< string, string > options)
void Add (params object[] controllers)
T GetController< T > ()
void Stop ()
Stop server and dispose all functions.
virtual void Start ()
void Dispose ()
Protected Member Functions
void OnInfo (string message)
void OnInfo (object sender, StringEventArgs e)
void OnWarning (string message)
void OnWarning (object sender, StringEventArgs e)
void OnError (Exception exp)
void OnError (object sender, ErrorEventArgs e)
virtual void Dispose (bool disposing)
Properties
static bool IsAdministrator [get]
ushort? HttpPort [get, set]
ushort? HttpsPort [get, set]
The port on which to listen for HTTPS connections.
int ListenerCount [get, set]
Gets or sets the maximum connections. Any connections beyond the max will wait indefinitely until a connection becomes available.
string Domain [get, set]
The domain name that this server serves. This is necessary to be able to automatically assign a TLS certificate to the process to handle HTTPS connections. The TLS certifcate and authority chain must be installed in the Windows Certificate Store (certmgr).
bool AutoAssignCertificate [get, set]
Set to true if the server should attempt to run netsh to assign a certificate to the application before starting the server.
bool IsRunning [get]
Events
EventHandler< StringEventArgs > Log
Event for handling Common Log Format logs.
EventHandler< StringEventArgs > Info
Event for handling information-level logs.
EventHandler< StringEventArgs > Warning
Event for handling error logs that don't stop execution.
EventHandler< ErrorEventArgs > Err
Event for handling error logs that prevent execution.
Private Member Functions
bool Check (bool isValid, string message)
void BanController_BanAdded (object sender, EventArgs< CIDRBlock > e)
async Task AddBanAsync (CIDRBlock block)
void BanController_BanRemoved (object sender, EventArgs< CIDRBlock > e)
void GetTLSParameters (out Guid guid, out string certHash)
bool TryAssignCertToApp (string certHash, Guid appGuid, out string message)
void AddController< T > (T controller)
void ProductionHttpUsageWarning ()
void AttemptCertificateAssignment ()
void SetPrefix (string protocol, ushort port)
AuthenticationSchemes GetAuthenticationSchemeForRequest (HttpListenerRequest request)
void Listen ()
void Cleanup ()
async Task HandleConnectionAsync ()
async Task ExecuteRoutesAsync (HttpListenerContext context)
async Task HandleErrorsAsync (HttpListenerResponse response, HttpListenerRequest request)
async Task CleanupConnectionAsync (HttpListenerResponse response, HttpListenerRequest request)
void OnLog (object sender, StringEventArgs e)
void ShowRoutes ()
Static Private Member Functions
static Task< bool > BanExistsAsync (string name)
static async Task RemoveBanAsync (CIDRBlock e)
Private Attributes
readonly Thread listenThread
readonly Thread cleanupThread
readonly HttpListener listener
readonly List< object > controllers = new List<object>()
readonly List< AbstractResponse > routes = new List<AbstractResponse>()
readonly ConcurrentBag< Task > waiters = new ConcurrentBag<Task>()
bool disposedValue = false
Detailed Description
A wrapper around HttpListener that handles routing, HTTPS, and a default start page for DEBUG running.
Definition at line 26 of file HttpServer.cs.
Constructor & Destructor Documentation
HttpServer()
Juniper.HTTP.Server.HttpServer.HttpServer () inline
Begin constructing a server.
MaxConnections = 100.
ListenAddress =
DEBUG: localhost
RELEASE: *
Server doesn't start listening until Start is called.
Definition at line 132 of file HttpServer.cs.
         {
             ListenerCount = 100;
             listenThread = new Thread(Listen);
             cleanupThread = new Thread(Cleanup);
             listener = new HttpListener
             {
                 AuthenticationSchemeSelectorDelegate = GetAuthenticationSchemeForRequest
             };
         }
References Juniper.HTTP.Server.HttpServer.Cleanup(), Juniper.HTTP.Server.HttpServer.cleanupThread, Juniper.HTTP.Server.HttpServer.GetAuthenticationSchemeForRequest(), Juniper.HTTP.Server.HttpServer.Listen(), Juniper.HTTP.Server.HttpServer.listener, Juniper.HTTP.Server.HttpServer.ListenerCount, and Juniper.HTTP.Server.HttpServer.listenThread.
Member Function Documentation
Add()
void Juniper.HTTP.Server.HttpServer.Add (params object [] controllers) inline
Definition at line 390 of file HttpServer.cs.
         {
             if (controllers is null)
             {
                 throw new ArgumentNullException(nameof(controllers));
             }
             for (var i = 0; i < controllers.Length; i++)
             {
                 var controller = controllers[i];
                 if (controller is null)
                 {
                     throw new NullReferenceException($"Encountered a null value at index {i}.");
                 }
                 var flags = BindingFlags.Public | BindingFlags.Static;
                 var type = controller as Type ?? controller.GetType();
                 if (controller is Type)
                 {
                     controller = null;
                 }
                 else
                 {
                     flags |= BindingFlags.Instance;
                     AddController(controller);
                 }
                 foreach (var method in type.GetMethods(flags))
                 {
                     var route = method.GetCustomAttribute<RouteAttribute>();
                     if (route is object)
                     {
                         var parameters = method.GetParameters();
                         if (method.ReturnType == typeof(Task)
                             && parameters.Length > 0
                             && parameters.Length == route.ParameterCount
                             && parameters.Skip(1).All(p => p.ParameterType == typeof(string)))
{
                             var contextParamType = parameters[0].ParameterType;
                             var isHttp = contextParamType == typeof(HttpListenerContext);
                             var isWebSocket = contextParamType == typeof(ServerWebSocketConnection);
                             object source = null;
                             if (!method.IsStatic)
{
                                 source = controller;
                             }
                             if (isHttp)
{
                                 AddController(new HttpRoute(source, method, route));
                             }
                             else if (isWebSocket)
{
                                 if (route.Authentication != AuthenticationSchemes.Anonymous)
{
                                     throw new InvalidOperationException("WebSockets do not support authentication");
                                 }
                                 AddController(new WebSocketRoute(source, method, route));
                             }
                             else
{
                                 throw new InvalidOperationException($@"Method {type.Name}::{method.Name} must have a signature:
     (System.Net.HttpListenerContext, string...) => Task
 or
     (Juniper.HTTP.Server.ServerWebSocketConnection, string...) => Task");
                             }
                         }
                     }
                 }
             }
         }
References Juniper.HTTP.Server.HttpServer.controllers.
Referenced by Juniper.HTTP.Server.HttpServer.SetOptions().
AddBanAsync()
async Task Juniper.HTTP.Server.HttpServer.AddBanAsync (CIDRBlock block) inline private
Definition at line 284 of file HttpServer.cs.
         {
             OnInfo($"Adding ban to firewall: {block}");
             var name = $"Ban {block}";
             var exists = await BanExistsAsync(name).ConfigureAwait(false);
             if (!exists)
             {
                 var add = new AddFirewallRule(name, FirewallRuleDirection.In, FirewallRuleAction.Block, block);
                 await add.RunAsync()
                     .ConfigureAwait(false);
             }
         }
References Juniper.HTTP.Server.HttpServer.BanExistsAsync(), and Juniper.HTTP.Server.HttpServer.OnInfo().
Referenced by Juniper.HTTP.Server.HttpServer.BanController_BanAdded().
AddController< T >()
void Juniper.HTTP.Server.HttpServer.AddController< T > (T controller) inline private
Type Constraints
T : class
Definition at line 465 of file HttpServer.cs.
                                                             : class
         {
             if (controller is AbstractResponse handler)
             {
                 handler.Server = this;
                 routes.Add(handler);
             }
             if (controller is IInfoSource infoSource)
             {
                 infoSource.Info += OnInfo;
             }
             if (controller is IInfoDestination infoDest)
             {
                 Info += infoDest.OnInfo;
             }
             if (controller is IWarningSource warningSource)
             {
                 warningSource.Warning += OnWarning;
             }
             if (controller is IWarningDestination warningDest)
             {
                 Warning += warningDest.OnWarning;
             }
             if (controller is IErrorSource errorSource)
             {
                 errorSource.Err += OnError;
             }
             if (controller is IErrorDestination errorDest)
             {
                 Err += errorDest.OnError;
             }
             if (controller is INCSALogSource nCSALogSource)
             {
                 nCSALogSource.Log += OnLog;
             }
             if (controller is INCSALogDestination nCSALogDest)
             {
                 Log += nCSALogDest.OnLog;
             }
             controllers.Add(controller);
         }
References Juniper.HTTP.Server.HttpServer.controllers, Juniper.HTTP.Server.HttpServer.Err, Juniper.HTTP.Server.HttpServer.Info, Juniper.HTTP.Server.HttpServer.Log, Juniper.HTTP.Server.HttpServer.OnError(), Juniper.HTTP.Server.HttpServer.OnInfo(), Juniper.HTTP.Server.HttpServer.OnLog(), Juniper.HTTP.Server.HttpServer.OnWarning(), Juniper.HTTP.Server.HttpServer.routes, and Juniper.HTTP.Server.HttpServer.Warning.
AttemptCertificateAssignment()
void Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment () inline private
Definition at line 659 of file HttpServer.cs.
         {
             var platform = Environment.OSVersion.Platform;
             if (HttpsPort is object
                 && AutoAssignCertificate
                 && (platform == PlatformID.Win32NT
                     || platform == PlatformID.Win32Windows
                     || platform == PlatformID.Win32S))
             {
                 if (string.IsNullOrEmpty(Domain))
                 {
                     OnWarning("No domain was specified. Can't auto-assign a TLS certificate.");
                 }
 #if !NETCOREAPP && !NETSTANDARD
                 else
                 {
                     GetTLSParameters(out var guid, out var certHash);
                     if (string.IsNullOrEmpty(certHash))
                     {
                         OnWarning("No TLS cert found!");
                     }
                     else
                     {
                         if (!TryAssignCertToApp(certHash, guid, out var message))
{
                             OnWarning($@"Couldn't configure the certificate correctly:
     Application GUID: {guid}
     TLS cert: {certHash}
     {message}");
                         }
                     }
                 }
 #else
                 else
                 {
                     OnWarning($"Don't know how to assign certificates on this platform: {platform}");
                 }
 #endif
             }
         }
References Juniper.HTTP.Server.HttpServer.AutoAssignCertificate, Juniper.HTTP.Server.HttpServer.Domain, Juniper.HTTP.Server.HttpServer.GetTLSParameters(), Juniper.HTTP.Server.HttpServer.HttpsPort, Juniper.HTTP.Server.HttpServer.OnWarning(), and Juniper.HTTP.Server.HttpServer.TryAssignCertToApp().
Referenced by Juniper.HTTP.Server.HttpServer.Start().
BanController_BanAdded()
void Juniper.HTTP.Server.HttpServer.BanController_BanAdded (object sender, EventArgs< CIDRBlock > e) inline private
Definition at line 274 of file HttpServer.cs.
         {
             _ = Task.Run(() => AddBanAsync(e.Value));
         }
References Juniper.HTTP.Server.HttpServer.AddBanAsync(), and Juniper.EventArgs< T >.Value.
Referenced by Juniper.HTTP.Server.HttpServer.SetOptions().
BanController_BanRemoved()
void Juniper.HTTP.Server.HttpServer.BanController_BanRemoved (object sender, EventArgs< CIDRBlock > e) inline private
Definition at line 297 of file HttpServer.cs.
         {
             _ = Task.Run(() => RemoveBanAsync(e.Value));
         }
References Juniper.HTTP.Server.HttpServer.RemoveBanAsync(), and Juniper.EventArgs< T >.Value.
Referenced by Juniper.HTTP.Server.HttpServer.SetOptions().
BanExistsAsync()
static Task<bool> Juniper.HTTP.Server.HttpServer.BanExistsAsync (string name) inline static private
Definition at line 279 of file HttpServer.cs.
         {
             return new GetFirewallRule(name).ExistsAsync();
         }
References Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.ExistsAsync().
Referenced by Juniper.HTTP.Server.HttpServer.AddBanAsync(), and Juniper.HTTP.Server.HttpServer.RemoveBanAsync().
Check()
bool Juniper.HTTP.Server.HttpServer.Check (bool isValid, string message) inline private
Definition at line 264 of file HttpServer.cs.
         {
             if (!isValid)
             {
                 OnError(new ArgumentException(message));
             }
             return isValid;
         }
References Juniper.HTTP.Server.HttpServer.OnError().
Referenced by Juniper.HTTP.Server.HttpServer.SetOptions().
Cleanup()
void Juniper.HTTP.Server.HttpServer.Cleanup () inline private
Definition at line 749 of file HttpServer.cs.
         {
             while (listener.IsListening)
             {
                 if (!waiters.IsEmpty
                     && waiters.TryTake(out var task)
                     && task.IsRunning())
                 {
                     waiters.Add(task);
                 }
             }
         }
References Juniper.HTTP.Server.HttpServer.listener, and Juniper.HTTP.Server.HttpServer.waiters.
Referenced by Juniper.HTTP.Server.HttpServer.HttpServer().
CleanupConnectionAsync()
async Task Juniper.HTTP.Server.HttpServer.CleanupConnectionAsync (HttpListenerResponse response, HttpListenerRequest request) inline private
Definition at line 839 of file HttpServer.cs.
         {
             response.StatusDescription = HttpStatusDescription.Get(response.StatusCode);
             await HandleErrorsAsync(response, request)
                 .ConfigureAwait(false);
             await response
                 .OutputStream
                 .FlushAsync()
                 .ConfigureAwait(true);
             if (!request.IsWebSocketRequest)
             {
                 response.Close();
             }
         }
References System.Net.HttpStatusDescription.Get(), and Juniper.HTTP.Server.HttpServer.HandleErrorsAsync().
Referenced by Juniper.HTTP.Server.HttpServer.HandleConnectionAsync().
Dispose() [1/2]
virtual void Juniper.HTTP.Server.HttpServer.Dispose (bool disposing) inline protected virtual
Definition at line 902 of file HttpServer.cs.
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     if (IsRunning)
                     {
                         Stop();
                     }
                     using (listener) { }
                     foreach (var controller in controllers)
                     {
                         if (controller is IDisposable disposable)
{
                             disposable.Dispose();
                         }
                     }
                     controllers.Clear();
                 }
                 disposedValue = true;
             }
         }
References Juniper.HTTP.Server.HttpServer.controllers, Juniper.HTTP.Server.HttpServer.disposedValue, Juniper.HTTP.Server.HttpServer.IsRunning, Juniper.HTTP.Server.HttpServer.listener, and Juniper.HTTP.Server.HttpServer.Stop().
Dispose() [2/2]
void Juniper.HTTP.Server.HttpServer.Dispose () inline
Definition at line 931 of file HttpServer.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             GC.SuppressFinalize(this);
         }
ExecuteRoutesAsync()
async Task Juniper.HTTP.Server.HttpServer.ExecuteRoutesAsync (HttpListenerContext context) inline private
Definition at line 804 of file HttpServer.cs.
         {
             foreach (var route in routes)
             {
                 if (route.IsContextMatch(context))
                 {
                     await route.ExecuteAsync(context)
                         .ConfigureAwait(false);
                 }
             }
         }
References Juniper.HTTP.Server.HttpServer.routes.
Referenced by Juniper.HTTP.Server.HttpServer.HandleConnectionAsync().
GetAuthenticationSchemeForRequest()
AuthenticationSchemes Juniper.HTTP.Server.HttpServer.GetAuthenticationSchemeForRequest (HttpListenerRequest request) inline private
Definition at line 722 of file HttpServer.cs.
         {
             var auth = (from route in routes
                         where route.IsRequestMatch(request)
                         orderby Math.Abs(route.Priority)
                         select route.Authentication)
                 .FirstOrDefault();
             if (auth == AuthenticationSchemes.None)
             {
                 auth = AuthenticationSchemes.Anonymous;
             }
             return auth;
         }
References Juniper.HTTP.Server.HttpServer.routes.
Referenced by Juniper.HTTP.Server.HttpServer.HttpServer().
GetController< T >()
T Juniper.HTTP.Server.HttpServer.GetController< T > () inline
Type Constraints
T : class
Definition at line 516 of file HttpServer.cs.
                     : class
         {
             return (T)controllers
                 .Find(c => c is T);
         }
References Juniper.HTTP.Server.HttpServer.controllers.
GetTLSParameters()
void Juniper.HTTP.Server.HttpServer.GetTLSParameters (out Guid guid, out string certHash) inline private
Definition at line 315 of file HttpServer.cs.
         {
             var asm = Assembly.GetExecutingAssembly();
             guid = System.Runtime.InteropServices.Marshal.GetTypeLibGuidForAssembly(asm);
             certHash = null;
             using var store = new System.Security.Cryptography.X509Certificates.X509Store(
                 System.Security.Cryptography.X509Certificates.StoreLocation.LocalMachine);
             store.Open(System.Security.Cryptography.X509Certificates.OpenFlags.ReadOnly);
             certHash = (from cert in store.Certificates.Cast<System.Security.Cryptography.X509Certificates.X509Certificate2>()
                         where cert.Subject == "CN=" + Domain
                           && DateTime.TryParse(cert.GetEffectiveDateString(), out var effectiveDate)
                           && DateTime.TryParse(cert.GetExpirationDateString(), out var expirationDate)
                           && effectiveDate <= DateTime.Now
                           && DateTime.Now < expirationDate
                         select cert.Thumbprint)
                        .FirstOrDefault();
         }
References Juniper.HTTP.Server.HttpServer.Domain.
Referenced by Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment().
HandleConnectionAsync()
async Task Juniper.HTTP.Server.HttpServer.HandleConnectionAsync () inline private
Definition at line 762 of file HttpServer.cs.
         {
             var context = await listener.GetContextAsync()
                     .ConfigureAwait(false);
             var response = context.Response;
             var request = context.Request;
             var headers = request.Headers;
             response.SetStatus(HttpStatusCode.Continue);
 #if DEBUG
             PrintHeader(context);
 #endif
             try
             {
                 await ExecuteRoutesAsync(context)
                     .ConfigureAwait(false); ;
             }
 #pragma warning disable CA1031 // Do not catch general exception types
             catch (Exception exp)
             {
                 OnError(exp);
                 response.SetStatus(HttpStatusCode.InternalServerError);
 #if DEBUG
                 await response.SendTextAsync(exp.Unroll())
                     .ConfigureAwait(false);
 #endif
             }
 #pragma warning restore CA1031 // Do not catch general exception types
             finally
             {
 #if DEBUG
                 PrintFooter(context);
                 OnInfo("");
 #endif
                 await CleanupConnectionAsync(response, request)
                     .ConfigureAwait(false);
             }
         }
References Juniper.HTTP.Server.HttpServer.CleanupConnectionAsync(), Juniper.HTTP.Server.HttpServer.ExecuteRoutesAsync(), Juniper.HTTP.Server.HttpServer.listener, Juniper.HTTP.Server.HttpServer.OnError(), and Juniper.HTTP.Server.HttpServer.OnInfo().
Referenced by Juniper.HTTP.Server.HttpServer.Listen().
HandleErrorsAsync()
async Task Juniper.HTTP.Server.HttpServer.HandleErrorsAsync (HttpListenerResponse response, HttpListenerRequest request) inline private
Definition at line 816 of file HttpServer.cs.
         {
             if (response.StatusCode >= 400)
             {
                 var message = $"{request.RawUrl}: {response.StatusDescription}";
                 if (response.StatusCode >= 500)
                 {
                     OnError(new HttpListenerException(response.StatusCode, message));
                 }
                 else
                 {
                     OnWarning(message);
                 }
 #if DEBUG
                 await response.SendTextAsync(message)
 #else
                 await Task.CompletedTask
 #endif
                     .ConfigureAwait(false);
             }
         }
References Juniper.HTTP.Server.HttpServer.OnError(), and Juniper.HTTP.Server.HttpServer.OnWarning().
Referenced by Juniper.HTTP.Server.HttpServer.CleanupConnectionAsync().
Listen()
void Juniper.HTTP.Server.HttpServer.Listen () inline private
Definition at line 738 of file HttpServer.cs.
         {
             while (listener.IsListening)
             {
                 if (waiters.Count < ListenerCount)
                 {
                     waiters.Add(HandleConnectionAsync());
                 }
             }
         }
References Juniper.HTTP.Server.HttpServer.HandleConnectionAsync(), Juniper.HTTP.Server.HttpServer.listener, Juniper.HTTP.Server.HttpServer.ListenerCount, and Juniper.HTTP.Server.HttpServer.waiters.
Referenced by Juniper.HTTP.Server.HttpServer.HttpServer().
OnError() [1/2]
void Juniper.HTTP.Server.HttpServer.OnError (Exception exp) inline protected
Definition at line 888 of file HttpServer.cs.
         {
             Err?.Invoke(this, new ErrorEventArgs(exp));
         }
References Juniper.HTTP.Server.HttpServer.Err.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.Check(), Juniper.HTTP.Server.HttpServer.HandleConnectionAsync(), Juniper.HTTP.Server.HttpServer.HandleErrorsAsync(), Juniper.HTTP.Server.HttpServer.Start(), Juniper.HTTP.Server.HttpServer.Stop(), and Juniper.HTTP.Server.HttpServer.TryAssignCertToApp().
OnError() [2/2]
void Juniper.HTTP.Server.HttpServer.OnError (object sender, ErrorEventArgs e) inline protected
Definition at line 894 of file HttpServer.cs.
         {
             Err?.Invoke(sender, e);
         }
References Juniper.HTTP.Server.HttpServer.Err.
OnInfo() [1/2]
void Juniper.HTTP.Server.HttpServer.OnInfo (string message) inline protected
Definition at line 864 of file HttpServer.cs.
         {
             Info?.Invoke(this, new StringEventArgs(message));
         }
References Juniper.HTTP.Server.HttpServer.Info.
Referenced by Juniper.HTTP.Server.HttpServer.AddBanAsync(), Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.HandleConnectionAsync(), Juniper.HTTP.Server.HttpServer.SetOptions(), Juniper.HTTP.Server.HttpServer.ShowRoutes(), Juniper.HTTP.Server.HttpServer.Start(), Juniper.HTTP.Server.HttpServer.Stop(), and Juniper.HTTP.Server.HttpServer.TryAssignCertToApp().
OnInfo() [2/2]
void Juniper.HTTP.Server.HttpServer.OnInfo (object sender, StringEventArgs e) inline protected
Definition at line 870 of file HttpServer.cs.
         {
             Info?.Invoke(sender, e);
         }
References Juniper.HTTP.Server.HttpServer.Info.
OnLog()
void Juniper.HTTP.Server.HttpServer.OnLog (object sender, StringEventArgs e) inline private
Definition at line 858 of file HttpServer.cs.
         {
             Log?.Invoke(sender, e);
         }
References Juniper.HTTP.Server.HttpServer.Log.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), and Juniper.HTTP.Server.HttpServer.Stop().
OnWarning() [1/2]
void Juniper.HTTP.Server.HttpServer.OnWarning (string message) inline protected
Definition at line 876 of file HttpServer.cs.
         {
             Warning?.Invoke(this, new StringEventArgs(message));
         }
References Juniper.HTTP.Server.HttpServer.Warning.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment(), Juniper.HTTP.Server.HttpServer.HandleErrorsAsync(), Juniper.HTTP.Server.HttpServer.ProductionHttpUsageWarning(), Juniper.HTTP.Server.HttpServer.SetOptions(), Juniper.HTTP.Server.HttpServer.Stop(), and Juniper.HTTP.Server.HttpServer.TryAssignCertToApp().
OnWarning() [2/2]
void Juniper.HTTP.Server.HttpServer.OnWarning (object sender, StringEventArgs e) inline protected
Definition at line 882 of file HttpServer.cs.
         {
             Warning?.Invoke(sender, e);
         }
References Juniper.HTTP.Server.HttpServer.Warning.
ProductionHttpUsageWarning()
void Juniper.HTTP.Server.HttpServer.ProductionHttpUsageWarning () inline private
Definition at line 641 of file HttpServer.cs.
         {
 #if !DEBUG
             var httpRoutes = from route in routes
                                 where !(route is HttpToHttpsRedirect)
                                 && !(route is BanHammer)
                                 && !(route is NCSALogger)
                                 && !(route is UnhandledRequestTrap)
                                 && route.Protocols.HasFlag(HttpProtocols.HTTP)
                                 select route;
             if (httpRoutes.Any())
             {
                 OnWarning("Maybe don't run unencrypted HTTP in production, k?");
             }
 #endif
         }
References Juniper.HTTP.Server.HttpServer.OnWarning(), and Juniper.HTTP.Server.HttpServer.routes.
Referenced by Juniper.HTTP.Server.HttpServer.Start().
RemoveBanAsync()
static async Task Juniper.HTTP.Server.HttpServer.RemoveBanAsync (CIDRBlock e) inline static private
Definition at line 302 of file HttpServer.cs.
         {
             var name = $"Ban {e}";
             var exists = await BanExistsAsync(name).ConfigureAwait(false);
             if (exists)
             {
                 var delete = new DeleteFirewallRule(name);
                 await delete.RunAsync()
                     .ConfigureAwait(false);
             }
         }
References Juniper.HTTP.Server.HttpServer.BanExistsAsync().
Referenced by Juniper.HTTP.Server.HttpServer.BanController_BanRemoved().
SetOptions()
bool Juniper.HTTP.Server.HttpServer.SetOptions (Dictionary< string, string > options) inline
Definition at line 144 of file HttpServer.cs.
         {
             if (options is null)
             {
                 throw new ArgumentNullException(nameof(options));
             }
             // Echo options
             OnInfo("Startup parameters are:");
             foreach (var param in options)
             {
                 OnInfo($"\t{param.Key} = {param.Value}");
             }
             var hasHttpsPort = options.TryGetUInt16("https", out var httpsPort);
             var hasHttpPort = options.TryGetUInt16("http", out var httpPort);
             var hasPort = Check(
                 hasHttpsPort || hasHttpPort,
                 "Must specify at least one of --https or --http");
             var hasDomain = Check(
                 options.TryGetValue("domain", out var domain),
                 "No domain specified");
             var isValidAssignCert = Check(
                 options.TryGetBool("assignCert", out var assignCert)
                 && hasDomain
                 || !options.ContainsKey("assignCert"),
                 "Must provide the --domain option to auto-assign a certificate");
             var isValidListenCount = Check(
                 options.TryGetInt32("listeners", out var listenerCount)
                 && listenerCount > 0
                 || !options.ContainsKey("listeners"),
                 "--listeners value must be greater than zero.");
             if (listenerCount == 0)
             {
                 listenerCount = 10;
             }
             var hasLogPath = Check(
                 options.TryGetValue("log", out var logPath),
                 "No logging path");
             var hasBansPath = Check(
                 options.TryGetValue("bans", out var bansPath),
                 "Path to ban file does not exist.");
             var hasContentPath = options.TryGetValue("path", out var contentPath);
             var isValidContentPath = Check(
                 !hasContentPath || Directory.Exists(contentPath),
                 "Path to static content directory does not exist");
             if (hasContentPath && !isValidContentPath)
             {
                 OnWarning($"Content directory was attempted from: {new DirectoryInfo(contentPath).FullName}");
             }
             if (hasDomain && hasPort)
             {
                 // Set options on server
                 Domain = domain;
                 if (isValidAssignCert)
                 {
                     AutoAssignCertificate = assignCert;
                 }
                 if (hasHttpPort)
                 {
                     HttpPort = httpPort;
                 }
                 if (hasHttpsPort)
                 {
                     HttpsPort = httpsPort;
                     if (hasHttpPort)
                     {
                         Add(new HttpToHttpsRedirect(httpsPort));
                     }
                 }
                 if (isValidListenCount)
                 {
                     ListenerCount = listenerCount;
                 }
                 if (isValidContentPath
                     && hasContentPath)
                 {
                     Add(new StaticFileServer(contentPath));
                 }
                 if (hasLogPath)
                 {
                     Add(new NCSALogger(logPath));
                 }
                 if (IsAdministrator)
                 {
                     var banController = hasBansPath
                         ? new BanHammer(bansPath)
                         : new BanHammer();
 #if !NETCOREAPP && !NETSTANDARD
                     banController.BanAdded += BanController_BanAdded;
                     banController.BanRemoved += BanController_BanRemoved;
 #endif
                     Add(banController);
                 }
                 return true;
             }
             return false;
         }
References Juniper.HTTP.Server.HttpServer.Add(), Juniper.HTTP.Server.HttpServer.AutoAssignCertificate, Juniper.HTTP.Server.HttpServer.BanController_BanAdded(), Juniper.HTTP.Server.HttpServer.BanController_BanRemoved(), Juniper.HTTP.Server.HttpServer.Check(), Juniper.HTTP.Server.HttpServer.Domain, Juniper.HTTP.Server.HttpServer.HttpPort, Juniper.HTTP.Server.HttpServer.HttpsPort, Juniper.HTTP.Server.HttpServer.IsAdministrator, Juniper.HTTP.Server.HttpServer.ListenerCount, Juniper.HTTP.Server.HttpServer.OnInfo(), and Juniper.HTTP.Server.HttpServer.OnWarning().
SetPrefix()
void Juniper.HTTP.Server.HttpServer.SetPrefix (string protocol, ushort port) inline private
Definition at line 701 of file HttpServer.cs.
         {
             if (!string.IsNullOrEmpty(protocol)
                 && port >= 0)
             {
                 var uri = new UriBuilder
                 {
                     Scheme = protocol,
 #if DEBUG
                     Host = "localhost",
 #else
                     Host = "*",
 #endif
                     Port = port
                 };
                 listener.Prefixes.Add(uri.ToString());
             }
         }
References Juniper.HTTP.Server.HttpServer.listener.
Referenced by Juniper.HTTP.Server.HttpServer.Start().
ShowRoutes()
void Juniper.HTTP.Server.HttpServer.ShowRoutes () inline private
Definition at line 939 of file HttpServer.cs.
         {
             OnInfo("Found routes:");
             var table = new string[routes.Count + 1, 8];
             table[0, 0] = "";
             table[0, 1] = "Type";
             table[0, 2] = "Method";
             table[0, 3] = "Priority";
             table[0, 4] = "Protocol";
             table[0, 5] = "Method";
             table[0, 6] = "Status";
             table[0, 7] = "Authentication";
             for (var i = 0; i < routes.Count; i++)
             {
                 var route = routes[i];
                 table[i + 1, 0] = route.Enabled ? "Y" : "N";
                 var sepIndex = route.Name.IndexOf("::", StringComparison.Ordinal);
                 if (sepIndex < 0)
                 {
                     table[i + 1, 1] = route.Name;
                 }
                 else
                 {
                     table[i + 1, 1] = route.Name.Substring(0, sepIndex);
                     table[i + 1, 2] = route.Name.Substring(sepIndex + 2);
                 }
                 table[i + 1, 3] = route.Priority.ToString(CultureInfo.InvariantCulture);
                 table[i + 1, 4] = route.Protocols.ToString();
                 table[i + 1, 5] = route.Methods.ToString();
                 table[i + 1, 6] = route.StatusCodes.ToString();
                 if (route.Authentication == AbstractResponse.AllAuthSchemes)
                 {
                     table[i + 1, 7] = "Any";
                 }
                 else
                 {
                     table[i + 1, 7] = route.Authentication.ToString();
                 }
             }
             var columnSizes = new int[table.GetLength(1)];
             for (var x = 0; x < table.GetLength(0); ++x)
             {
                 for (var y = 0; y < table.GetLength(1); ++y)
                 {
                     if (table[x, y] is null)
                     {
                         table[x, y] = string.Empty;
                     }
                     columnSizes[y] = Math.Max(columnSizes[y], table[x, y].Length);
                 }
             }
             var totalWidth = columnSizes.Sum() + (columnSizes.Length * 3) + 1;
             var sb = new StringBuilder();
             for (var x = 0; x < table.GetLength(0); ++x)
             {
                 _ = sb.Clear();
                 for (var y = 0; y < table.GetLength(1); ++y)
                 {
                     var formatter = $"| {{0,-{columnSizes[y]}}} ";
                     _ = sb.AppendFormat(CultureInfo.InvariantCulture, formatter, table[x, y]);
                 }
                 _ = sb.Append("|");
                 OnInfo(sb.ToString());
                 if (x == 0)
                 {
                     _ = sb.Clear();
                     for (var y = 0; y < totalWidth; ++y)
                     {
                         _ = sb.Append("-");
                     }
                     OnInfo(sb.ToString());
                 }
             }
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.AllAuthSchemes, Juniper.HTTP.Server.HttpServer.OnInfo(), and Juniper.HTTP.Server.HttpServer.routes.
Referenced by Juniper.HTTP.Server.HttpServer.Start().
Start()
virtual void Juniper.HTTP.Server.HttpServer.Start () inline virtual
Definition at line 590 of file HttpServer.cs.
         {
             OnInfo("Starting server");
 #if DEBUG
             var redirector = GetController<HttpToHttpsRedirect>();
             //redirector.Enabled = false;
 #endif
             if (routes.Count > 0)
             {
                 routes.Sort();
                 ShowRoutes();
             }
             AttemptCertificateAssignment();
             if (HttpPort is null
                 && HttpsPort is null)
             {
                 OnError(new InvalidOperationException("No HTTP or HTTPS port specified."));
             }
             else
             {
                 if (HttpsPort is object)
                 {
                     ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
                     SetPrefix("https", HttpsPort.Value);
                 }
                 if (HttpPort is object)
                 {
                     SetPrefix("http", HttpPort.Value);
                     ProductionHttpUsageWarning();
                 }
                 if (!listener.IsListening)
                 {
                     OnInfo($"Listening on:");
                     foreach (var prefix in listener.Prefixes)
                     {
                         OnInfo($"\t{prefix}");
                     }
                     listener.Start();
                     listenThread.Start();
                     cleanupThread.Start();
                 }
             }
         }
References Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment(), Juniper.HTTP.Server.HttpServer.cleanupThread, Juniper.HTTP.Server.HttpServer.HttpPort, Juniper.HTTP.Server.HttpServer.HttpsPort, Juniper.HTTP.Server.HttpServer.listener, Juniper.HTTP.Server.HttpServer.listenThread, Juniper.HTTP.Server.HttpServer.OnError(), Juniper.HTTP.Server.HttpServer.OnInfo(), Juniper.HTTP.Server.HttpServer.ProductionHttpUsageWarning(), Juniper.HTTP.Server.HttpServer.routes, Juniper.HTTP.Server.HttpServer.SetPrefix(), and Juniper.HTTP.Server.HttpServer.ShowRoutes().
Stop()
void Juniper.HTTP.Server.HttpServer.Stop () inline
Stop server and dispose all functions.
Definition at line 535 of file HttpServer.cs.
         {
             OnInfo("Stopping server");
             foreach (var controller in controllers)
             {
                 if (controller is IInfoSource infoSource)
                 {
                     infoSource.Info -= OnInfo;
                 }
                 if (controller is IInfoDestination infoDest)
                 {
                     Info -= infoDest.OnInfo;
                 }
                 if (controller is IWarningSource warningSource)
                 {
                     warningSource.Warning -= OnWarning;
                 }
                 if (controller is IWarningDestination warningDest)
                 {
                     Warning -= warningDest.OnWarning;
                 }
                 if (controller is IErrorSource errorSource)
                 {
                     errorSource.Err -= OnError;
                 }
                 if (controller is IErrorDestination errorDest)
                 {
                     Err -= errorDest.OnError;
                 }
                 if (controller is INCSALogSource nCSALogSource)
                 {
                     nCSALogSource.Log -= OnLog;
                 }
                 if (controller is INCSALogDestination nCSALogDest)
                 {
                     Log -= nCSALogDest.OnLog;
                 }
             }
             listener.Stop();
             listener.Close();
             var end = DateTime.Now.AddSeconds(3);
             while (listenThread.IsAlive && DateTime.Now < end)
             {
                 Thread.Yield();
             }
         }
References Juniper.HTTP.Server.HttpServer.controllers, Juniper.HTTP.Server.HttpServer.Err, Juniper.HTTP.Server.HttpServer.Info, Juniper.HTTP.Server.HttpServer.listener, Juniper.HTTP.Server.HttpServer.listenThread, Juniper.HTTP.Server.HttpServer.Log, Juniper.HTTP.Server.HttpServer.OnError(), Juniper.HTTP.Server.HttpServer.OnInfo(), Juniper.HTTP.Server.HttpServer.OnLog(), Juniper.HTTP.Server.HttpServer.OnWarning(), and Juniper.HTTP.Server.HttpServer.Warning.
Referenced by Juniper.HTTP.Server.HttpServer.Dispose().
TryAssignCertToApp()
bool Juniper.HTTP.Server.HttpServer.TryAssignCertToApp (string certHash, Guid appGuid, out string message) inline private
Definition at line 336 of file HttpServer.cs.
         {
             var endpoint = new IPEndPoint(IPAddress.Parse("0.0.0.0"), HttpsPort.Value);
             var showCert = new ShowSslCert(endpoint);
             showCert.Info += OnInfo;
             showCert.Warning += OnWarning;
             showCert.Err += OnError;
             _ = showCert.Run();
             showCert.Info -= OnInfo;
             showCert.Warning -= OnWarning;
             showCert.Err -= OnError;
             if (showCert.TotalStandardOutput.Contains(appGuid.ToString()))
             {
                 message = null;
                 return true;
             }
             if (showCert.TotalStandardOutput.Contains(endpoint.ToString()))
             {
                 var deleteCert = new DeleteSslCert(endpoint);
                 deleteCert.Info += OnInfo;
                 deleteCert.Warning += OnWarning;
                 deleteCert.Err += OnError;
                 _ = deleteCert.Run();
                 deleteCert.Info -= OnInfo;
                 deleteCert.Warning -= OnWarning;
                 deleteCert.Err -= OnError;
             }
             var addCert = new AddSslCert(endpoint, certHash, appGuid);
             addCert.Info += OnInfo;
             addCert.Warning += OnWarning;
             addCert.Err += OnError;
             _ = addCert.Run();
             addCert.Info -= OnInfo;
             addCert.Warning -= OnWarning;
             addCert.Err -= OnError;
             message = addCert.TotalStandardOutput;
             return !message.Contains("The parameter is incorrect.");
         }
References Juniper.HTTP.Server.HttpServer.HttpsPort, Juniper.HTTP.Server.HttpServer.OnError(), Juniper.HTTP.Server.HttpServer.OnInfo(), and Juniper.HTTP.Server.HttpServer.OnWarning().
Referenced by Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment().
Member Data Documentation
cleanupThread
readonly Thread Juniper.HTTP.Server.HttpServer.cleanupThread private
Definition at line 47 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.HttpServer(), and Juniper.HTTP.Server.HttpServer.Start().
controllers
readonly List<object> Juniper.HTTP.Server.HttpServer.controllers = new List<object>() private
Definition at line 49 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.Add(), Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.Dispose(), Juniper.HTTP.Server.HttpServer.GetController< T >(), and Juniper.HTTP.Server.HttpServer.Stop().
disposedValue
bool Juniper.HTTP.Server.HttpServer.disposedValue = false private
Definition at line 900 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.Dispose().
listener
readonly HttpListener Juniper.HTTP.Server.HttpServer.listener private
Definition at line 48 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.Cleanup(), Juniper.HTTP.Server.HttpServer.Dispose(), Juniper.HTTP.Server.HttpServer.HandleConnectionAsync(), Juniper.HTTP.Server.HttpServer.HttpServer(), Juniper.HTTP.Server.HttpServer.Listen(), Juniper.HTTP.Server.HttpServer.SetPrefix(), Juniper.HTTP.Server.HttpServer.Start(), and Juniper.HTTP.Server.HttpServer.Stop().
listenThread
readonly Thread Juniper.HTTP.Server.HttpServer.listenThread private
Definition at line 46 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.HttpServer(), Juniper.HTTP.Server.HttpServer.Start(), and Juniper.HTTP.Server.HttpServer.Stop().
routes
readonly List<AbstractResponse> Juniper.HTTP.Server.HttpServer.routes = new List<AbstractResponse>() private
Definition at line 50 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.ExecuteRoutesAsync(), Juniper.HTTP.Server.HttpServer.GetAuthenticationSchemeForRequest(), Juniper.HTTP.Server.HttpServer.ProductionHttpUsageWarning(), Juniper.HTTP.Server.HttpServer.ShowRoutes(), and Juniper.HTTP.Server.HttpServer.Start().
waiters
readonly ConcurrentBag<Task> Juniper.HTTP.Server.HttpServer.waiters = new ConcurrentBag<Task>() private
Definition at line 51 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.Cleanup(), and Juniper.HTTP.Server.HttpServer.Listen().
Property Documentation
AutoAssignCertificate
bool Juniper.HTTP.Server.HttpServer.AutoAssignCertificate get set
Set to true if the server should attempt to run netsh to assign a certificate to the application before starting the server.
Definition at line 97 of file HttpServer.cs.
 { get; set; }
Referenced by Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment(), and Juniper.HTTP.Server.HttpServer.SetOptions().
Domain
string Juniper.HTTP.Server.HttpServer.Domain get set
The domain name that this server serves. This is necessary to be able to automatically assign a TLS certificate to the process to handle HTTPS connections. The TLS certifcate and authority chain must be installed in the Windows Certificate Store (certmgr).
The domain.
Definition at line 91 of file HttpServer.cs.
 { get; set; }
Referenced by Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment(), Juniper.HTTP.Server.HttpServer.GetTLSParameters(), and Juniper.HTTP.Server.HttpServer.SetOptions().
HttpPort
ushort? Juniper.HTTP.Server.HttpServer.HttpPort get set
The port on which to listen for insecure HTTP connections.
WARNING: only use this in testing, or to redirect users to the HTTPS version of the request.
The HTTP port.
Definition at line 63 of file HttpServer.cs.
 { get; set; }
Referenced by Juniper.HTTP.Server.HttpServer.SetOptions(), and Juniper.HTTP.Server.HttpServer.Start().
HttpsPort
ushort? Juniper.HTTP.Server.HttpServer.HttpsPort get set
The port on which to listen for HTTPS connections.
The HTTPS port.
Definition at line 71 of file HttpServer.cs.
 { get; set; }
Referenced by Juniper.HTTP.Server.HttpServer.AttemptCertificateAssignment(), Juniper.HTTP.Server.HttpServer.SetOptions(), Juniper.HTTP.Server.HttpServer.Start(), and Juniper.HTTP.Server.HttpServer.TryAssignCertToApp().
IsAdministrator
bool Juniper.HTTP.Server.HttpServer.IsAdministrator static get
Definition at line 33 of file HttpServer.cs.
         {
             get
             {
 #if !NETCOREAPP && !NETSTANDARD
                 var identity = System.Security.Principal.WindowsIdentity.GetCurrent();
                 var principal = new System.Security.Principal.WindowsPrincipal(identity);
                 return principal.IsInRole(System.Security.Principal.WindowsBuiltInRole.Administrator);
 #else
                 return false;
 #endif
             }
         }
Referenced by Juniper.HTTP.Server.HttpServer.SetOptions().
IsRunning
bool Juniper.HTTP.Server.HttpServer.IsRunning get
Definition at line 524 of file HttpServer.cs.
         {
             get
             {
                 return listener.IsListening
                     && listenThread.IsAlive;
             }
         }
Referenced by Juniper.HTTP.Server.HttpServer.Dispose().
ListenerCount
int Juniper.HTTP.Server.HttpServer.ListenerCount get set
Gets or sets the maximum connections. Any connections beyond the max will wait indefinitely until a connection becomes available.
The maximum connections.
Definition at line 80 of file HttpServer.cs.
 { get; set; }
Referenced by Juniper.HTTP.Server.HttpServer.HttpServer(), Juniper.HTTP.Server.HttpServer.Listen(), and Juniper.HTTP.Server.HttpServer.SetOptions().
Event Documentation
Err
EventHandler<ErrorEventArgs> Juniper.HTTP.Server.HttpServer.Err
Event for handling error logs that prevent execution.
Definition at line 117 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.OnError(), and Juniper.HTTP.Server.HttpServer.Stop().
Info
EventHandler<StringEventArgs> Juniper.HTTP.Server.HttpServer.Info
Event for handling information-level logs.
Definition at line 107 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.OnInfo(), and Juniper.HTTP.Server.HttpServer.Stop().
Log
EventHandler<StringEventArgs> Juniper.HTTP.Server.HttpServer.Log
Event for handling Common Log Format logs.
Definition at line 102 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.OnLog(), and Juniper.HTTP.Server.HttpServer.Stop().
Warning
EventHandler<StringEventArgs> Juniper.HTTP.Server.HttpServer.Warning
Event for handling error logs that don't stop execution.
Definition at line 112 of file HttpServer.cs.
Referenced by Juniper.HTTP.Server.HttpServer.AddController< T >(), Juniper.HTTP.Server.HttpServer.OnWarning(), and Juniper.HTTP.Server.HttpServer.Stop().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Server/HttpServer.cs