Juniper: Hjg.Pngcs.Chunks.PngChunkPLTE Class Reference
Hjg.Pngcs.Chunks.PngChunkPLTE Class Reference
PLTE Palette chunk: this is the only optional critical chunk
Public Types
enum ChunkOrderingConstraint {
ChunkOrderingConstraint.NONE, ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT, ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT, ChunkOrderingConstraint.BEFORE_IDAT,
ChunkOrderingConstraint.NA
}
Restrictions for chunk ordering, for ancillary chunks
Public Member Functions
PngChunkPLTE (ImageInfo info)
override ChunkOrderingConstraint GetOrderingConstraint ()
Get ordering constrain
override ChunkRaw CreateRawChunk ()
Serialization. Creates a Raw chunk, ready for write, from this chunk content
override void ParseFromRaw (ChunkRaw chunk)
Deserialization. Given a Raw chunk, just rad, fills this chunk content
override void CloneDataFromRead (PngChunk other)
Override to make a copy (normally deep) from other chunk
void SetNentries (int nentries)
Also allocates array
int GetNentries ()
void SetEntry (int n, int r, int g, int b)
int GetEntry (int n)
as packed RGB8
void GetEntryRgb (int index, int[] rgb, int offset)
Gets n'th entry, filling 3 positions of given array, at given offset
void GetEntryRgb (int n, int[] rgb)
shortcut: GetEntryRgb(index, int[] rgb, 0)
int MinBitDepth ()
minimum allowed bit depth, given palette size
sealed override bool AllowsMultiple ()
This is implemented in PngChunkMultiple/PngChunSingle
override int GetHashCode ()
override bool Equals (object obj)
ChunkRaw createEmptyChunk (int len, bool alloc)
override String ToString ()
Basic info: Id, length, Type name
Static Public Member Functions
static void FactoryRegister (String chunkId, Type type)
Registers a Chunk ID in the factory, to instantiate a given type
static T CloneChunk< T > (T chunk, ImageInfo info)
Public Attributes
const String ID = ChunkHelper.PLTE
readonly String Id
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
readonly bool Crit
Standard basic properties, implicit in the Id
Protected Attributes
readonly ImageInfo ImgInfo
Image basic info, mostly for some checks
Properties
bool Priority [get, set]
For writing. Queued chunks with high priority will be written as soon as possible
int ChunkGroup [get, set]
Chunk group where it was read or writen
int Length [get, set]
long Offset [get, set]
Private Attributes
int nentries = 0
int [] entries
Detailed Description
PLTE Palette chunk: this is the only optional critical chunk
http://www.w3.org/TR/PNG/#11PLTE
Definition at line 16 of file PngChunkPLTE.cs.
Member Enumeration Documentation
ChunkOrderingConstraint
enum Hjg.Pngcs.Chunks.PngChunk.ChunkOrderingConstraint strong inherited
Restrictions for chunk ordering, for ancillary chunks
Enumerator
NONE
No constraint, the chunk can go anywhere
BEFORE_PLTE_AND_IDAT
Before PLTE (palette) - and hence, also before IDAT
AFTER_PLTE_BEFORE_IDAT
After PLTE (palette), but before IDAT
BEFORE_IDAT
Before IDAT (before or after PLTE)
NA
Does not apply
Definition at line 54 of file PngChunk.cs.
{
             /// <summary>
             /// No constraint, the chunk can go anywhere
             /// </summary>
             NONE,
             /// <summary>
             /// Before PLTE (palette) - and hence, also before IDAT
             /// </summary>
             BEFORE_PLTE_AND_IDAT,
             /// <summary>
             /// After PLTE (palette), but before IDAT
             /// </summary>
             AFTER_PLTE_BEFORE_IDAT,
             /// <summary>
             /// Before IDAT (before or after PLTE)
             /// </summary>
             BEFORE_IDAT,
             /// <summary>
             /// Does not apply
             /// </summary>
             NA
         }
Constructor & Destructor Documentation
PngChunkPLTE()
Hjg.Pngcs.Chunks.PngChunkPLTE.PngChunkPLTE (ImageInfo info) inline
Definition at line 26 of file PngChunkPLTE.cs.
             : base(ID, info) {
             this.nentries = 0;
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkPLTE.CloneDataFromRead().
Member Function Documentation
AllowsMultiple()
sealed override bool Hjg.Pngcs.Chunks.PngChunkSingle.AllowsMultiple () inline virtual inherited
This is implemented in PngChunkMultiple/PngChunSingle
Returns
Allows more than one chunk of this type in a image
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 14 of file PngChunkSingle.cs.
{
             return false;
         }
CloneChunk< T >()
static T Hjg.Pngcs.Chunks.PngChunk.CloneChunk< T > (T chunk, ImageInfo info) inline static inherited
Type Constraints
T : PngChunk
Definition at line 185 of file PngChunk.cs.
                                                                        : PngChunk {
             PngChunk cn = FactoryFromId(chunk.Id, info);
             if ((Object)cn.GetType() != (Object)chunk.GetType())
                 throw new PngjException("bad class cloning chunk: " + cn.GetType() + " "
                         + chunk.GetType());
             cn.CloneDataFromRead(chunk);
             return (T)cn;
         }
References Hjg.Pngcs.Chunks.PngChunk.CloneDataFromRead(), and Hjg.Pngcs.Chunks.PngChunk.FactoryFromId().
CloneDataFromRead()
override void Hjg.Pngcs.Chunks.PngChunkPLTE.CloneDataFromRead (PngChunk other) inline virtual
Override to make a copy (normally deep) from other chunk
Parameters
other
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 57 of file PngChunkPLTE.cs.
{
             PngChunkPLTE otherx = (PngChunkPLTE)other;
             this.SetNentries(otherx.GetNentries());
             System.Array.Copy((Array)(otherx.entries), 0, (Array)(entries), 0, nentries);
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.entries, Hjg.Pngcs.Chunks.PngChunkPLTE.GetNentries(), Hjg.Pngcs.Chunks.PngChunkPLTE.nentries, Hjg.Pngcs.Chunks.PngChunkPLTE.PngChunkPLTE(), and Hjg.Pngcs.Chunks.PngChunkPLTE.SetNentries().
createEmptyChunk()
ChunkRaw Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk (int len, bool alloc) inline inherited
Definition at line 179 of file PngChunk.cs.
{
             ChunkRaw c = new ChunkRaw(len, ChunkHelper.ToBytes(Id), alloc);
             return c;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
Referenced by Hjg.Pngcs.Chunks.PngChunkTEXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkGAMA.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTIME.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkOFFS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSTER.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPHYS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkUNKNOWN.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSRGB.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk().
CreateRawChunk()
override ChunkRaw Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk () inline virtual
Serialization. Creates a Raw chunk, ready for write, from this chunk content
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 36 of file PngChunkPLTE.cs.
{
             int len = 3 * nentries;
             int[] rgb = new int[3];
             ChunkRaw c = createEmptyChunk(len, true);
             for (int n = 0, i = 0; n < nentries; n++) {
                 GetEntryRgb(n, rgb);
                 c.Data[i++] = (byte)rgb[0];
                 c.Data[i++] = (byte)rgb[1];
                 c.Data[i++] = (byte)rgb[2];
             }
             return c;
         }
References Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk(), Hjg.Pngcs.Chunks.ChunkRaw.Data, Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntryRgb(), and Hjg.Pngcs.Chunks.PngChunkPLTE.nentries.
Equals()
override bool Hjg.Pngcs.Chunks.PngChunkSingle.Equals (object obj) inline inherited
Definition at line 25 of file PngChunkSingle.cs.
{
             return (obj is PngChunkSingle && Id != null && Id.Equals(((PngChunkSingle)obj).Id));
         }
References Hjg.Pngcs.Chunks.PngChunk.Id.
FactoryRegister()
static void Hjg.Pngcs.Chunks.PngChunk.FactoryRegister (String chunkId, Type type) inline static inherited
Registers a Chunk ID in the factory, to instantiate a given type
This can be called by client code to register additional chunk types
Parameters
chunkId
type should extend PngChunkSingle or PngChunkMultiple
Definition at line 130 of file PngChunk.cs.
{
             factoryMap.Add(chunkId, type);
         }
References Hjg.Pngcs.Chunks.PngChunk.factoryMap.
GetEntry()
int Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntry (int n) inline
as packed RGB8
Parameters
n
Returns
Definition at line 89 of file PngChunkPLTE.cs.
{
             return entries[n];
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.entries.
GetEntryRgb() [1/2]
void Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntryRgb (int index, int [] rgb, int offset) inline
Gets n'th entry, filling 3 positions of given array, at given offset
Parameters
index
rgb
offset
Definition at line 100 of file PngChunkPLTE.cs.
{
             int v = entries[index];
             rgb[offset ] = ((v & 0xff0000) >> 16);
             rgb[offset + 1] = ((v & 0xff00) >> 8);
             rgb[offset + 2] = (v & 0xff);
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.entries.
Referenced by Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntryRgb(), and Hjg.Pngcs.ImageLineHelper.Palette2rgb().
GetEntryRgb() [2/2]
void Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntryRgb (int n, int [] rgb) inline
shortcut: GetEntryRgb(index, int[] rgb, 0)
Parameters
n
rgb
Definition at line 112 of file PngChunkPLTE.cs.
{
             GetEntryRgb(n, rgb, 0);
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntryRgb().
GetHashCode()
override int Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode () inline inherited
Definition at line 18 of file PngChunkSingle.cs.
{
             int prime = 31;
             int result = 1;
             result = prime * result + ((Id == null) ? 0 : Id.GetHashCode());
             return result;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id.
GetNentries()
int Hjg.Pngcs.Chunks.PngChunkPLTE.GetNentries () inline
Definition at line 76 of file PngChunkPLTE.cs.
{
             return nentries;
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.nentries.
Referenced by Hjg.Pngcs.Chunks.PngChunkPLTE.CloneDataFromRead().
GetOrderingConstraint()
override ChunkOrderingConstraint Hjg.Pngcs.Chunks.PngChunkPLTE.GetOrderingConstraint () inline virtual
Get ordering constrain
Returns
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 32 of file PngChunkPLTE.cs.
{
             return ChunkOrderingConstraint.NA;
         }
MinBitDepth()
int Hjg.Pngcs.Chunks.PngChunkPLTE.MinBitDepth () inline
minimum allowed bit depth, given palette size
Returns
1-2-4-8
Definition at line 120 of file PngChunkPLTE.cs.
{
             if (nentries <= 2)
                 return 1;
             else if (nentries <= 4)
                 return 2;
             else if (nentries <= 16)
                 return 4;
             else
                 return 8;
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.nentries.
ParseFromRaw()
override void Hjg.Pngcs.Chunks.PngChunkPLTE.ParseFromRaw (ChunkRaw c) inline virtual
Deserialization. Given a Raw chunk, just rad, fills this chunk content
Implements Hjg.Pngcs.Chunks.PngChunk.
Definition at line 49 of file PngChunkPLTE.cs.
{
             SetNentries(chunk.Len / 3);
             for (int n = 0, i = 0; n < nentries; n++) {
                 SetEntry(n, (int)(chunk.Data[i++] & 0xff), (int)(chunk.Data[i++] & 0xff),
                         (int)(chunk.Data[i++] & 0xff));
             }
         }
References Hjg.Pngcs.Chunks.ChunkRaw.Data, Hjg.Pngcs.Chunks.ChunkRaw.Len, Hjg.Pngcs.Chunks.PngChunkPLTE.nentries, Hjg.Pngcs.Chunks.PngChunkPLTE.SetEntry(), and Hjg.Pngcs.Chunks.PngChunkPLTE.SetNentries().
SetEntry()
void Hjg.Pngcs.Chunks.PngChunkPLTE.SetEntry (int n, int r, int g, int b) inline
Definition at line 80 of file PngChunkPLTE.cs.
{
             entries[n] = ((r << 16) | (g << 8) | b);
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.entries.
Referenced by Hjg.Pngcs.Chunks.PngChunkPLTE.ParseFromRaw().
SetNentries()
void Hjg.Pngcs.Chunks.PngChunkPLTE.SetNentries (int nentries) inline
Also allocates array
Parameters
nentries 1-256
Definition at line 67 of file PngChunkPLTE.cs.
{
             this.nentries = nentries;
             if (nentries < 1 || nentries > 256)
                 throw new PngjException("invalid pallette - nentries=" + nentries);
             if (entries == null || entries.Length != nentries) { // alloc
                 entries = new int[nentries];
             }
         }
References Hjg.Pngcs.Chunks.PngChunkPLTE.entries, and Hjg.Pngcs.Chunks.PngChunkPLTE.nentries.
Referenced by Hjg.Pngcs.Chunks.PngChunkPLTE.CloneDataFromRead(), and Hjg.Pngcs.Chunks.PngChunkPLTE.ParseFromRaw().
ToString()
override String Hjg.Pngcs.Chunks.PngChunk.ToString () inline inherited
Basic info: Id, length, Type name
Returns
Definition at line 204 of file PngChunk.cs.
{
             return "chunk id= " + Id + " (len=" + Length + " off=" + Offset +") c=" + GetType().Name;
         }
References Hjg.Pngcs.Chunks.PngChunk.Id, Hjg.Pngcs.Chunks.PngChunk.Length, and Hjg.Pngcs.Chunks.PngChunk.Offset.
Member Data Documentation
Crit
readonly bool Hjg.Pngcs.Chunks.PngChunk.Crit inherited
Standard basic properties, implicit in the Id
Definition at line 32 of file PngChunk.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), and Hjg.Pngcs.PngReader.ReadChunk().
entries
int [] Hjg.Pngcs.Chunks.PngChunkPLTE.entries private
Definition at line 24 of file PngChunkPLTE.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkPLTE.CloneDataFromRead(), Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntry(), Hjg.Pngcs.Chunks.PngChunkPLTE.GetEntryRgb(), Hjg.Pngcs.Chunks.PngChunkPLTE.SetEntry(), and Hjg.Pngcs.Chunks.PngChunkPLTE.SetNentries().
ID
const String Hjg.Pngcs.Chunks.PngChunkPLTE.ID = ChunkHelper.PLTE
Definition at line 17 of file PngChunkPLTE.cs.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.GetPLTE().
Id
readonly String Hjg.Pngcs.Chunks.PngChunk.Id inherited
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
Definition at line 28 of file PngChunk.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngChunk.createEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkSingle.Equals(), Hjg.Pngcs.Chunks.ChunkHelper.Equivalent(), Hjg.Pngcs.Chunks.ChunksList.GetChunksKeys(), Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode(), Hjg.Pngcs.Chunks.ChunkPredicateId.Matches(), Hjg.Pngcs.Chunks.ChunkPredicateId2.Matches(), Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite(), Hjg.Pngcs.Chunks.PngChunk.ToString(), and Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
ImgInfo
readonly ImageInfo Hjg.Pngcs.Chunks.PngChunk.ImgInfo protected inherited
Image basic info, mostly for some checks
Definition at line 37 of file PngChunk.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetGray(), Hjg.Pngcs.Chunks.PngChunkSBIT.GetLen(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetRGB(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetRGB(), Hjg.Pngcs.Chunks.PngChunkSBIT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkHIST.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTRNS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.setIndexEntryAsTransparent(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetRGB(), and Hjg.Pngcs.Chunks.PngChunkBKGD.SetRGB().
nentries
int Hjg.Pngcs.Chunks.PngChunkPLTE.nentries = 0 private
Definition at line 19 of file PngChunkPLTE.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkPLTE.CloneDataFromRead(), Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.GetNentries(), Hjg.Pngcs.Chunks.PngChunkPLTE.MinBitDepth(), Hjg.Pngcs.Chunks.PngChunkPLTE.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkPLTE.SetNentries().
Property Documentation
ChunkGroup
int Hjg.Pngcs.Chunks.PngChunk.ChunkGroup get set inherited
Chunk group where it was read or writen
Definition at line 46 of file PngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite(), Hjg.Pngcs.Chunks.ChunksList.ToStringFull(), and Hjg.Pngcs.Chunks.ChunksListForWrite.writeChunks().
Length
int Hjg.Pngcs.Chunks.PngChunk.Length get set inherited
Definition at line 48 of file PngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.PngChunk.Factory(), Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), Hjg.Pngcs.Chunks.PngChunkSkipped.PngChunkSkipped(), and Hjg.Pngcs.Chunks.PngChunk.ToString().
Offset
long Hjg.Pngcs.Chunks.PngChunk.Offset get set inherited
Definition at line 49 of file PngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.PngChunk.PngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), Hjg.Pngcs.PngReader.ReadChunk(), and Hjg.Pngcs.Chunks.PngChunk.ToString().
Priority
bool Hjg.Pngcs.Chunks.PngChunk.Priority get set inherited
For writing. Queued chunks with high priority will be written as soon as possible
Definition at line 42 of file PngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.PngChunk.PngChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.shouldWrite().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/ThirdParty/Required/Hjg.Pngcs/Chunks/PngChunkPLTE.cs