Juniper: Juniper.Console.ConsoleBuffer.NativeMethods Class Reference
Juniper.Console.ConsoleBuffer.NativeMethods Class Reference
Classes
struct CONSOLE_FONT_INFO_EX
struct COORD
struct POINT
struct RECT
Private Types
enum CONSOLE_MODES {
CONSOLE_MODES.ENABLE_PROCESSED_INPUT = 0x0001, CONSOLE_MODES.ENABLE_PROCESSED_OUTPUT = 0x0001, CONSOLE_MODES.ENABLE_LINE_INPUT = 0x0002, CONSOLE_MODES.ENABLE_WRAP_AT_EOL_OUTPUT = 0x0002,
CONSOLE_MODES.ENABLE_ECHO_INPUT = 0x0004, CONSOLE_MODES.ENABLE_VIRTUAL_TERMINAL_PROCESSING = 0x0004, CONSOLE_MODES.ENABLE_WINDOW_INPUT = 0x0008, CONSOLE_MODES.DISABLE_NEWLINE_AUTO_RETURN = 0x0008,
CONSOLE_MODES.ENABLE_MOUSE_INPUT = 0x0010, CONSOLE_MODES.ENABLE_LVB_GRID_WORLDWIDE = 0x0010, CONSOLE_MODES.ENABLE_INSERT_MODE = 0x0020, CONSOLE_MODES.ENABLE_QUICK_EDIT_MODE = 0x0040,
CONSOLE_MODES.ENABLE_EXTENDED_FLAGS = 0x0080, CONSOLE_MODES.ENABLE_VIRTUAL_TERMINAL_INPUT = 0x0200
}
Private Member Functions
static internal short GetKeyState (int key)
static internal bool GetCursorPos (out POINT point)
static internal IntPtr GetStdHandle (int nStdHandle)
static internal bool GetCurrentConsoleFontEx (IntPtr consoleOutput, bool maximumWindow, ref CONSOLE_FONT_INFO_EX lpConsoleCurrentFontEx)
static internal bool SetCurrentConsoleFontEx (IntPtr consoleOutput, bool maximumWindow, CONSOLE_FONT_INFO_EX consoleCurrentFontEx)
static internal bool GetConsoleMode (IntPtr console, out CONSOLE_MODES mode)
static internal bool SetConsoleMode (IntPtr consoleOutput, CONSOLE_MODES mode)
Private Attributes
internal const int STD_INPUT_HANDLE = -10
internal const int STD_OUTPUT_HANDLE = -11
internal const int STD_ERROR_HANDLE = -12
internal const int TMPF_TRUETYPE = 4
internal const int LF_FACESIZE = 32
Static Private Attributes
static internal readonly IntPtr INVALID_HANDLE_VALUE = new IntPtr(-1)
Detailed Description
Definition at line 552 of file ConsoleBuffer.cs.
Member Enumeration Documentation
CONSOLE_MODES
enum Juniper.Console.ConsoleBuffer.NativeMethods.CONSOLE_MODES strong private
Enumerator
ENABLE_PROCESSED_INPUT
ENABLE_PROCESSED_OUTPUT
ENABLE_LINE_INPUT
ENABLE_WRAP_AT_EOL_OUTPUT
ENABLE_ECHO_INPUT
ENABLE_VIRTUAL_TERMINAL_PROCESSING
ENABLE_WINDOW_INPUT
DISABLE_NEWLINE_AUTO_RETURN
ENABLE_MOUSE_INPUT
ENABLE_LVB_GRID_WORLDWIDE
ENABLE_INSERT_MODE
ENABLE_QUICK_EDIT_MODE
ENABLE_EXTENDED_FLAGS
ENABLE_VIRTUAL_TERMINAL_INPUT
Definition at line 586 of file ConsoleBuffer.cs.
             {
                 ENABLE_PROCESSED_INPUT = 0x0001,
                 ENABLE_PROCESSED_OUTPUT = 0x0001,
                 ENABLE_LINE_INPUT = 0x0002,
                 ENABLE_WRAP_AT_EOL_OUTPUT = 0x0002,
                 ENABLE_ECHO_INPUT = 0x0004,
                 ENABLE_VIRTUAL_TERMINAL_PROCESSING = 0x0004,
                 ENABLE_WINDOW_INPUT = 0x0008,
                 DISABLE_NEWLINE_AUTO_RETURN = 0x0008,
                 ENABLE_MOUSE_INPUT = 0x0010,
                 ENABLE_LVB_GRID_WORLDWIDE = 0x0010,
                 ENABLE_INSERT_MODE = 0x0020,
                 ENABLE_QUICK_EDIT_MODE = 0x0040,
                 ENABLE_EXTENDED_FLAGS = 0x0080,
                 ENABLE_VIRTUAL_TERMINAL_INPUT = 0x0200
             }
Member Function Documentation
GetConsoleMode()
static internal bool Juniper.Console.ConsoleBuffer.NativeMethods.GetConsoleMode (IntPtr console, out CONSOLE_MODES mode) private
Referenced by Juniper.Console.ConsoleBuffer.IsConsoleModeEnabled(), and Juniper.Console.ConsoleBuffer.SetConsoleModeEnabled().
GetCurrentConsoleFontEx()
static internal bool Juniper.Console.ConsoleBuffer.NativeMethods.GetCurrentConsoleFontEx (IntPtr consoleOutput, bool maximumWindow, ref CONSOLE_FONT_INFO_EX lpConsoleCurrentFontEx) private
Referenced by Juniper.Console.ConsoleBuffer.SetFont().
GetCursorPos()
static internal bool Juniper.Console.ConsoleBuffer.NativeMethods.GetCursorPos (out POINT point) private
GetKeyState()
static internal short Juniper.Console.ConsoleBuffer.NativeMethods.GetKeyState (int key) private
Referenced by Juniper.Console.ConsoleBuffer.IsKeyDown().
GetStdHandle()
static internal IntPtr Juniper.Console.ConsoleBuffer.NativeMethods.GetStdHandle (int nStdHandle) private
SetConsoleMode()
static internal bool Juniper.Console.ConsoleBuffer.NativeMethods.SetConsoleMode (IntPtr consoleOutput, CONSOLE_MODES mode) private
Referenced by Juniper.Console.ConsoleBuffer.SetConsoleModeEnabled().
SetCurrentConsoleFontEx()
static internal bool Juniper.Console.ConsoleBuffer.NativeMethods.SetCurrentConsoleFontEx (IntPtr consoleOutput, bool maximumWindow, CONSOLE_FONT_INFO_EX consoleCurrentFontEx) private
Referenced by Juniper.Console.ConsoleBuffer.SetFont(), and Juniper.Console.ConsoleBuffer.SetFontSize().
Member Data Documentation
INVALID_HANDLE_VALUE
internal readonly IntPtr Juniper.Console.ConsoleBuffer.NativeMethods.INVALID_HANDLE_VALUE = new IntPtr(-1) static private
Definition at line 609 of file ConsoleBuffer.cs.
LF_FACESIZE
internal const int Juniper.Console.ConsoleBuffer.NativeMethods.LF_FACESIZE = 32 private
Definition at line 608 of file ConsoleBuffer.cs.
STD_ERROR_HANDLE
internal const int Juniper.Console.ConsoleBuffer.NativeMethods.STD_ERROR_HANDLE = -12 private
Definition at line 606 of file ConsoleBuffer.cs.
STD_INPUT_HANDLE
internal const int Juniper.Console.ConsoleBuffer.NativeMethods.STD_INPUT_HANDLE = -10 private
Definition at line 604 of file ConsoleBuffer.cs.
STD_OUTPUT_HANDLE
internal const int Juniper.Console.ConsoleBuffer.NativeMethods.STD_OUTPUT_HANDLE = -11 private
Definition at line 605 of file ConsoleBuffer.cs.
TMPF_TRUETYPE
internal const int Juniper.Console.ConsoleBuffer.NativeMethods.TMPF_TRUETYPE = 4 private
Definition at line 607 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.SetFont().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Console/ConsoleBuffer.cs