Juniper: Juniper.Unity.Input.CameraControl Class Reference
Juniper.Unity.Input.CameraControl Class Reference
Public Types
enum Mode {
Mode.None, Mode.Auto, Mode.Mouse, Mode.Gamepad,
Mode.Touch, Mode.MagicWindow
}
enum MouseButton { MouseButton.Left, MouseButton.Right, MouseButton.Middle, MouseButton.None = ~0 }
Public Member Functions
void Awake ()
void Start ()
void Update ()
Public Attributes
Mode mode = Mode.Auto
bool setMouseLock = true
If we are running on a desktop system, set this value to true to lock the mouse cursor to the application window.
MouseButton requiredMouseButton = MouseButton.None
int requiredTouchCount = 1
float dragThreshold = 2
bool disableHorizontal
bool disableVertical
float sensitivityX = 0.5f
How quickly the mouse moves horizontally
float sensitivityY = 0.5f
How quickly the mouse moves vertically
float minimumY = -45F
Minimum vertical value
float maximumY = 85F
Maximum vertical value
UnityEvent onModeChange
Properties
bool MouseLockingEnabled [get]
Vector3 AxialMovement [get]
Vector3 MeanTouchPointMovement [get]
Events
Action< Mode > ModeChange
Private Member Functions
void OnModeChange ()
bool GestureSatisfied (Mode mode)
Vector3 PointerMovement (Mode mode)
Quaternion OrientationDelta (Mode mode, bool disableVertical)
bool DragRequired (Mode mode)
bool DragSatisfied (Mode mode)
void CheckMouseLock ()
void CheckMode (Mode mode, bool disableVertical)
Private Attributes
Mode lastMode = Mode.None
const float MOUSE_SENSITIVITY_SCALE = 50
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
const float TOUCH_SENSITIVITY_SCALE = 1
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
bool firstTime = true
Quaternion lastGyro = Quaternion.identity
StageExtensions stage
readonly Dictionary< Mode, bool > dragged = new Dictionary<Mode, bool>()
readonly Dictionary< Mode, bool > wasGestureSatisfied = new Dictionary<Mode, bool>()
readonly Dictionary< Mode, float > dragDistance = new Dictionary<Mode, float>()
UnifiedInputModule input
Static Private Attributes
static Quaternion NEUTRAL_POSITION_RESET = Quaternion.Euler(90f, 0f, 0f)
static Quaternion FLIP_IMAGE = Quaternion.Euler(0f, 0f, 180f)
Detailed Description
Definition at line 13 of file CameraControl.cs.
Member Enumeration Documentation
Mode
enum Juniper.Unity.Input.CameraControl.Mode strong
Enumerator
None
Auto
Mouse
Gamepad
Touch
MagicWindow
Definition at line 18 of file CameraControl.cs.
         {
             None,
             Auto,
             Mouse,
             Gamepad,
             Touch,
             MagicWindow
         }
MouseButton
enum Juniper.Unity.Input.CameraControl.MouseButton strong
Enumerator
Left
Right
Middle
None
Definition at line 45 of file CameraControl.cs.
         {
             Left,
             Right,
             Middle,
             None = ~0
         }
Member Function Documentation
Awake()
void Juniper.Unity.Input.CameraControl.Awake () inline
Definition at line 115 of file CameraControl.cs.
         {
             stage = ComponentExt.FindAny<StageExtensions>();
             foreach (var mode in Enum.GetValues(typeof(Mode)))
             {
                 wasGestureSatisfied[(Mode)mode] = false;
             }
         }
References Juniper.Unity.Input.CameraControl.mode, Juniper.Unity.Input.CameraControl.stage, and Juniper.Unity.Input.CameraControl.wasGestureSatisfied.
CheckMode()
void Juniper.Unity.Input.CameraControl.CheckMode (Mode mode, bool disableVertical) inline private
Definition at line 323 of file CameraControl.cs.
         {
             var gest = GestureSatisfied(mode);
             var wasGest = wasGestureSatisfied[mode];
             if (gest)
             {
                 if (!wasGest)
                 {
                     dragged[mode] = false;
                     dragDistance[mode] = 0;
                 }
                 if (DragSatisfied(mode))
                 {
                     stage.RotateView(OrientationDelta(mode, disableVertical), minimumY, maximumY);
                 }
             }
             wasGestureSatisfied[mode] = gest;
         }
References Juniper.Unity.Input.CameraControl.disableVertical, Juniper.Unity.Input.CameraControl.dragDistance, Juniper.Unity.Input.CameraControl.dragged, Juniper.Unity.Input.CameraControl.DragSatisfied(), Juniper.Unity.Input.CameraControl.GestureSatisfied(), Juniper.Unity.Input.CameraControl.maximumY, Juniper.Unity.Input.CameraControl.minimumY, Juniper.Unity.Input.CameraControl.mode, Juniper.Unity.Input.CameraControl.OrientationDelta(), Juniper.Unity.StageExtensions.RotateView(), Juniper.Unity.Input.CameraControl.stage, and Juniper.Unity.Input.CameraControl.wasGestureSatisfied.
Referenced by Juniper.Unity.Input.CameraControl.Update().
CheckMouseLock()
void Juniper.Unity.Input.CameraControl.CheckMouseLock () inline private
Definition at line 266 of file CameraControl.cs.
         {
             if (MouseLockingEnabled)
             {
                 if (UnityInput.mousePresent && (firstTime || UnityInput.GetMouseButtonDown(0)))
                 {
                     firstTime = false;
                     Cursor.lockState = CursorLockMode.Locked;
                 }
 #if UNITY_2018_1_OR_NEWER
                 else if (UnityInput.GetKeyDown(KeyCode.Escape))
                 {
                     Cursor.lockState = CursorLockMode.None;
                 }
 #endif
                 Cursor.visible = Cursor.lockState == CursorLockMode.None
                     || Cursor.lockState == CursorLockMode.Confined;
             }
             else if (Cursor.lockState != CursorLockMode.None)
             {
                 Cursor.lockState = CursorLockMode.None;
                 Cursor.visible = true;
             }
         }
References Juniper.Unity.Input.CameraControl.firstTime, and Juniper.Unity.Input.CameraControl.MouseLockingEnabled.
Referenced by Juniper.Unity.Input.CameraControl.Update().
DragRequired()
bool Juniper.Unity.Input.CameraControl.DragRequired (Mode mode) inline private
Definition at line 241 of file CameraControl.cs.
         {
             return mode == Mode.Touch
                 || (mode == Mode.Mouse
                     && requiredMouseButton != MouseButton.None);
         }
References Juniper.Unity.Input.CameraControl.mode, and Juniper.Unity.Input.CameraControl.requiredMouseButton.
Referenced by Juniper.Unity.Input.CameraControl.DragSatisfied().
DragSatisfied()
bool Juniper.Unity.Input.CameraControl.DragSatisfied (Mode mode) inline private
Definition at line 248 of file CameraControl.cs.
         {
             if (!DragRequired(mode))
             {
                 return true;
             }
             else
             {
                 var move = PointerMovement(mode);
                 if (DragRequired(mode) && !dragged.Get(mode, false))
                 {
                     dragDistance[mode] = dragDistance.Get(mode, 0) + (move.magnitude / Screen.dpi);
                     dragged[mode] = Units.Inches.Millimeters(dragDistance[mode]) > dragThreshold;
                 }
                 return dragged[mode];
             }
         }
References Juniper.Unity.Input.CameraControl.dragDistance, Juniper.Unity.Input.CameraControl.dragged, Juniper.Unity.Input.CameraControl.DragRequired(), Juniper.Unity.Input.CameraControl.dragThreshold, Juniper.Units.Inches.Millimeters(), Juniper.Unity.Input.CameraControl.mode, and Juniper.Unity.Input.CameraControl.PointerMovement().
Referenced by Juniper.Unity.Input.CameraControl.CheckMode().
GestureSatisfied()
bool Juniper.Unity.Input.CameraControl.GestureSatisfied (Mode mode) inline private
Definition at line 130 of file CameraControl.cs.
         {
             if (mode == Mode.None)
             {
                 return false;
             }
             else if (mode == Mode.Gamepad || mode == Mode.MagicWindow)
             {
                 return true;
             }
             else if (mode == Mode.Touch)
             {
                 if (UnityInput.touchCount != requiredTouchCount)
                 {
                     return false;
                 }
                 else
                 {
                     var touchPhase = UnityInput.GetTouch(requiredTouchCount - 1).phase;
                     return touchPhase == TouchPhase.Began
                         || touchPhase == TouchPhase.Moved
                         || touchPhase == TouchPhase.Stationary;
                 }
             }
             else
             {
                 var btn = (int)requiredMouseButton;
                 var pressed = requiredMouseButton == MouseButton.None || UnityInput.GetMouseButton(btn);
                 var down = requiredMouseButton != MouseButton.None && UnityInput.GetMouseButtonDown(btn);
                 return pressed && !down && (!MouseLockingEnabled || Cursor.lockState == CursorLockMode.Locked);
             }
         }
References Juniper.Unity.Input.CameraControl.mode, Juniper.Unity.Input.CameraControl.MouseLockingEnabled, Juniper.Unity.Input.CameraControl.requiredMouseButton, and Juniper.Unity.Input.CameraControl.requiredTouchCount.
Referenced by Juniper.Unity.Input.CameraControl.CheckMode().
OnModeChange()
void Juniper.Unity.Input.CameraControl.OnModeChange () inline private
Definition at line 97 of file CameraControl.cs.
         {
             onModeChange?.Invoke();
             ModeChange?.Invoke(mode);
         }
References Juniper.Unity.Input.CameraControl.mode, Juniper.Unity.Input.CameraControl.ModeChange, and Juniper.Unity.Input.CameraControl.onModeChange.
Referenced by Juniper.Unity.Input.CameraControl.Update().
OrientationDelta()
Quaternion Juniper.Unity.Input.CameraControl.OrientationDelta (Mode mode, bool disableVertical) inline private
Definition at line 203 of file CameraControl.cs.
         {
             if (mode == Mode.MagicWindow)
             {
                 var endQuat = NEUTRAL_POSITION_RESET
                         * UnityInput.gyro.attitude
                         * FLIP_IMAGE;
                 var dRot = Quaternion.Inverse(lastGyro) * endQuat;
                 lastGyro = endQuat;
                 return dRot;
             }
             else
             {
                 var move = PointerMovement(mode);
                 if (disableVertical)
                 {
                     move.x = 0;
                 }
                 else
                 {
                     move.x *= sensitivityX;
                 }
                 if (disableHorizontal)
                 {
                     move.y = 0;
                 }
                 else
                 {
                     move.y *= sensitivityY;
                 }
                 move.z = 0;
                 return Quaternion.Euler(move);
             }
         }
References Juniper.Unity.Input.CameraControl.disableHorizontal, Juniper.Unity.Input.CameraControl.disableVertical, Juniper.Unity.Input.CameraControl.FLIP_IMAGE, Juniper.Unity.Input.CameraControl.lastGyro, Juniper.Unity.Input.CameraControl.mode, Juniper.Unity.Input.CameraControl.NEUTRAL_POSITION_RESET, Juniper.Unity.Input.CameraControl.PointerMovement(), Juniper.Unity.Input.CameraControl.sensitivityX, and Juniper.Unity.Input.CameraControl.sensitivityY.
Referenced by Juniper.Unity.Input.CameraControl.CheckMode().
PointerMovement()
Vector3 Juniper.Unity.Input.CameraControl.PointerMovement (Mode mode) inline private
Definition at line 163 of file CameraControl.cs.
         {
             switch (mode)
             {
                 case Mode.Mouse:
                 case Mode.Gamepad:
                 return AxialMovement;
                 case Mode.Touch:
                 return MeanTouchPointMovement;
                 default:
                 return Vector3.zero;
             }
         }
References Juniper.Unity.Input.CameraControl.AxialMovement, Juniper.Unity.Input.CameraControl.MeanTouchPointMovement, and Juniper.Unity.Input.CameraControl.mode.
Referenced by Juniper.Unity.Input.CameraControl.DragSatisfied(), and Juniper.Unity.Input.CameraControl.OrientationDelta().
Start()
void Juniper.Unity.Input.CameraControl.Start () inline
Definition at line 125 of file CameraControl.cs.
         {
             input = ComponentExt.FindAny<UnifiedInputModule>();
         }
References Juniper.Unity.Input.CameraControl.input.
Update()
void Juniper.Unity.Input.CameraControl.Update () inline
Definition at line 292 of file CameraControl.cs.
         {
             if (mode != lastMode)
             {
                 OnModeChange();
                 lastMode = mode;
             }
             CheckMouseLock();
             if (!input.AnyPointerDragging || Cursor.lockState == CursorLockMode.Locked)
             {
                 CheckMode(mode, disableVertical);
                 if (mode == Mode.MagicWindow)
                 {
                     CheckMode(Mode.Touch, true);
                 }
                 else if (mode == Mode.Gamepad)
                 {
                     if (Application.isMobilePlatform)
                     {
                         CheckMode(Mode.Touch, disableVertical);
                     }
                     else
                     {
                         CheckMode(Mode.Mouse, disableVertical);
                     }
                 }
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.AnyPointerDragging, Juniper.Unity.Input.CameraControl.CheckMode(), Juniper.Unity.Input.CameraControl.CheckMouseLock(), Juniper.Unity.Input.CameraControl.disableVertical, Juniper.Unity.Input.CameraControl.input, Juniper.Unity.Input.CameraControl.lastMode, Juniper.Unity.Input.CameraControl.mode, and Juniper.Unity.Input.CameraControl.OnModeChange().
Member Data Documentation
disableHorizontal
bool Juniper.Unity.Input.CameraControl.disableHorizontal
Definition at line 57 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OrientationDelta().
disableVertical
bool Juniper.Unity.Input.CameraControl.disableVertical
Definition at line 58 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.CheckMode(), Juniper.Unity.Input.CameraControl.OrientationDelta(), and Juniper.Unity.Input.CameraControl.Update().
dragDistance
readonly Dictionary<Mode, float> Juniper.Unity.Input.CameraControl.dragDistance = new Dictionary<Mode, float>() private
Definition at line 111 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.CheckMode(), and Juniper.Unity.Input.CameraControl.DragSatisfied().
dragged
readonly Dictionary<Mode, bool> Juniper.Unity.Input.CameraControl.dragged = new Dictionary<Mode, bool>() private
Definition at line 109 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.CheckMode(), and Juniper.Unity.Input.CameraControl.DragSatisfied().
dragThreshold
float Juniper.Unity.Input.CameraControl.dragThreshold = 2
Definition at line 55 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.DragSatisfied().
firstTime
bool Juniper.Unity.Input.CameraControl.firstTime = true private
Definition at line 103 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.CheckMouseLock().
FLIP_IMAGE
Quaternion Juniper.Unity.Input.CameraControl.FLIP_IMAGE = Quaternion.Euler(0f, 0f, 180f) static private
Definition at line 16 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OrientationDelta().
input
UnifiedInputModule Juniper.Unity.Input.CameraControl.input private
Definition at line 113 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.Start(), and Juniper.Unity.Input.CameraControl.Update().
lastGyro
Quaternion Juniper.Unity.Input.CameraControl.lastGyro = Quaternion.identity private
Definition at line 105 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OrientationDelta().
lastMode
Mode Juniper.Unity.Input.CameraControl.lastMode = Mode.None private
Definition at line 29 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.Update().
maximumY
float Juniper.Unity.Input.CameraControl.maximumY = 85F
Maximum vertical value
Definition at line 92 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.CheckMode().
minimumY
float Juniper.Unity.Input.CameraControl.minimumY = -45F
Minimum vertical value
Definition at line 87 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.CheckMode().
mode
Mode Juniper.Unity.Input.CameraControl.mode = Mode.Auto
Definition at line 28 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.Awake(), Juniper.Unity.Input.CameraControl.CheckMode(), Juniper.Unity.Input.CameraControl.DragRequired(), Juniper.Unity.Input.CameraControl.DragSatisfied(), Juniper.Unity.Input.CameraControl.GestureSatisfied(), Juniper.Unity.Display.AbstractPassthroughDisplayManager.OnARModeChange(), Juniper.Unity.Input.CameraControl.OnModeChange(), Juniper.Unity.Input.CameraControl.OrientationDelta(), Juniper.Unity.Input.CameraControl.PointerMovement(), Juniper.Unity.Display.NoDisplayManager.Start(), Juniper.Unity.Display.AbstractPassthroughDisplayManager.Start(), and Juniper.Unity.Input.CameraControl.Update().
MOUSE_SENSITIVITY_SCALE
const float Juniper.Unity.Input.CameraControl.MOUSE_SENSITIVITY_SCALE = 50 private
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
Definition at line 64 of file CameraControl.cs.
NEUTRAL_POSITION_RESET
Quaternion Juniper.Unity.Input.CameraControl.NEUTRAL_POSITION_RESET = Quaternion.Euler(90f, 0f, 0f) static private
Definition at line 15 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OrientationDelta().
onModeChange
UnityEvent Juniper.Unity.Input.CameraControl.onModeChange
Definition at line 94 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OnModeChange().
requiredMouseButton
MouseButton Juniper.Unity.Input.CameraControl.requiredMouseButton = MouseButton.None
Definition at line 53 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.DragRequired(), and Juniper.Unity.Input.CameraControl.GestureSatisfied().
requiredTouchCount
int Juniper.Unity.Input.CameraControl.requiredTouchCount = 1
Definition at line 54 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.GestureSatisfied().
sensitivityX
float Juniper.Unity.Input.CameraControl.sensitivityX = 0.5f
How quickly the mouse moves horizontally
Definition at line 76 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OrientationDelta().
sensitivityY
float Juniper.Unity.Input.CameraControl.sensitivityY = 0.5f
How quickly the mouse moves vertically
Definition at line 82 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OrientationDelta().
setMouseLock
bool Juniper.Unity.Input.CameraControl.setMouseLock = true
If we are running on a desktop system, set this value to true to lock the mouse cursor to the application window.
Definition at line 35 of file CameraControl.cs.
stage
StageExtensions Juniper.Unity.Input.CameraControl.stage private
Definition at line 107 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.Awake(), and Juniper.Unity.Input.CameraControl.CheckMode().
TOUCH_SENSITIVITY_SCALE
const float Juniper.Unity.Input.CameraControl.TOUCH_SENSITIVITY_SCALE = 1 private
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
Definition at line 70 of file CameraControl.cs.
wasGestureSatisfied
readonly Dictionary<Mode, bool> Juniper.Unity.Input.CameraControl.wasGestureSatisfied = new Dictionary<Mode, bool>() private
Definition at line 110 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.Awake(), and Juniper.Unity.Input.CameraControl.CheckMode().
Property Documentation
AxialMovement
Vector3 Juniper.Unity.Input.CameraControl.AxialMovement get private
Definition at line 180 of file CameraControl.cs.
         {
             get
             {
                 return MOUSE_SENSITIVITY_SCALE * new Vector3(
                     -UnityInput.GetAxis("Mouse Y"),
                     UnityInput.GetAxis("Mouse X"));
             }
         }
Referenced by Juniper.Unity.Input.CameraControl.PointerMovement().
MeanTouchPointMovement
Vector3 Juniper.Unity.Input.CameraControl.MeanTouchPointMovement get private
Definition at line 190 of file CameraControl.cs.
         {
             get
             {
                 var delta = Vector2.zero;
                 for (var i = 0; i < UnityInput.touchCount; ++i)
                 {
                     delta += UnityInput.GetTouch(i).deltaPosition / UnityInput.touchCount;
                 }
                 delta = new Vector2(delta.y, -delta.x);
                 return TOUCH_SENSITIVITY_SCALE * delta;
             }
         }
Referenced by Juniper.Unity.Input.CameraControl.PointerMovement().
MouseLockingEnabled
bool Juniper.Unity.Input.CameraControl.MouseLockingEnabled get
Definition at line 38 of file CameraControl.cs.
         {
             get
             {
                 return setMouseLock && mode == Mode.Mouse;
             }
         }
Referenced by Juniper.Unity.Input.CameraControl.CheckMouseLock(), and Juniper.Unity.Input.CameraControl.GestureSatisfied().
Event Documentation
ModeChange
Action<Mode> Juniper.Unity.Input.CameraControl.ModeChange
Definition at line 95 of file CameraControl.cs.
Referenced by Juniper.Unity.Input.CameraControl.OnModeChange().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/CameraControl.cs