Juniper: Juniper.Widgets.Clickable Class Reference
Juniper.Widgets.Clickable Class Reference
An object that can be Touched on a screen or Clicked with a mouse and fires an event in response.
Public Member Functions
virtual void OnPointerClick (PointerEventData eventData)
Trigger the onClick/Click events, if they are valid.
virtual void OnClick ()
Trigger the onClick/click events, if they are valid;
void ActivateClick ()
void OnLongPress (PointerEventData evt)
This method executes when the user presses on a control and does not release before the "long-press timeout" occurs. The "long-press timeout" is defined in Input.Pointers.MappedButton<ButtonIDType>.THRESHOLD_LONG_PRESS.
virtual void OnLongPress ()
void OnLongPressUpdate (PointerEventData evt)
In the process of registering a Long Press event, the receiving control has the option to update its visual representationi based on how long the user has been pressing it.
bool IsInteractable ()
Should interaction with this control continue, or be prevented with an "denied" notification to the user?
void SetDisabled (bool value)
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
void ToggleEnabled ()
Toggles the boolean value of the disabled field.
virtual void Update ()
Update the physics state of the control, and enable/disable Disabled view on DisabledChanged.
virtual void OnPointerEnter (PointerEventData eventData)
React to the pointer hovering over the control.
virtual void OnPointerExit (PointerEventData eventData)
React to the pointer leaving the control and no longer hovering over it.
virtual void OnPointerDown (PointerEventData eventData)
React to the primary button being pressed on the control.
virtual void OnPointerUp (PointerEventData eventData)
React to the primary button being released from the control.
Public Attributes
UnityEvent onClick
The event to call when the button is enabled and clicked. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr Click.
UnityEvent onLongPress
InputButton clickButton
The button we are expecting to use to interact with this object.
bool disabled
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occurring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Vector3 pointerPosition
The place near the control that the pointer was pointing.
Static Public Attributes
static string [] PART_NAMES
The names of the animation states that Touchable expects.
Protected Member Functions
virtual void LateUpdate ()
Saves the state of the flags from the current frame to have them for the next frame.
string ShowState (string enabledPart)
Trigger the animation or swap the gameObjects to show the current control UI state.
void GetPosition (PointerEventData eventData)
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Protected Attributes
Vector3 lastPointerPosition
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
Properties
bool IsDisabled [get, set]
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
bool PointerPositionChanged [get]
Returns true when pointerPosition has changed since the last frame.
Events
EventHandler Click
The event to call when the button is enabled and clicked. You should only use this verison if you are programmatically attaching event listenters. if you are using the Unity Editor, you should prefer onClick.
EventHandler LongPress
Detailed Description
An object that can be Touched on a screen or Clicked with a mouse and fires an event in response.
Definition at line 16 of file Clickable.cs.
Member Function Documentation
ActivateClick()
void Juniper.Widgets.Clickable.ActivateClick () inline
Definition at line 61 of file Clickable.cs.
         {
             if (!IsDisabled)
             {
                 OnClick();
             }
         }
References Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.Clickable.OnClick().
GetPosition()
void Juniper.Widgets.AbstractTouchable.GetPosition (PointerEventData eventData) inline protected inherited
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Parameters
eventData Event data.
Definition at line 222 of file AbstractTouchable.cs.
         {
             pointerPosition = eventData.pointerCurrentRaycast.worldPosition;
             eventData.Use();
         }
References Juniper.Widgets.AbstractTouchable.pointerPosition.
Referenced by Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.Clickable.OnPointerClick(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Widgets.AbstractTouchable.OnPointerUp().
IsInteractable()
bool Juniper.Widgets.AbstractTouchable.IsInteractable () inline inherited
Should interaction with this control continue, or be prevented with an "denied" notification to the user?
Returns
True when the control can proceed with processing, False when the user needs to be told to stahp.
Implements Juniper.Events.IInteractable.
Definition at line 59 of file AbstractTouchable.cs.
 { return !disabled; }
References Juniper.Widgets.AbstractTouchable.disabled.
LateUpdate()
virtual void Juniper.Widgets.AbstractTouchable.LateUpdate () inline protected virtual inherited
Saves the state of the flags from the current frame to have them for the next frame.
Reimplemented in Juniper.Widgets.AbstractValued, Juniper.Widgets.Draggable, and Juniper.Widgets.Openable.
Definition at line 183 of file AbstractTouchable.cs.
         {
             wasDisabled = IsDisabled;
             lastPointerPosition = pointerPosition;
         }
References Juniper.Widgets.AbstractTouchable.IsDisabled, Juniper.Widgets.AbstractTouchable.lastPointerPosition, Juniper.Widgets.AbstractTouchable.pointerPosition, and Juniper.Widgets.AbstractTouchable.wasDisabled.
OnClick()
virtual void Juniper.Widgets.Clickable.OnClick () inline virtual
Trigger the onClick/click events, if they are valid;
Reimplemented in Juniper.Widgets.TeleportPad.
Definition at line 55 of file Clickable.cs.
         {
             onClick?.Invoke();
             Click?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Widgets.Clickable.Click, and Juniper.Widgets.Clickable.onClick.
Referenced by Juniper.Widgets.Clickable.ActivateClick(), and Juniper.Widgets.Clickable.OnPointerClick().
OnLongPress() [1/2]
void Juniper.Widgets.Clickable.OnLongPress (PointerEventData evt) inline
This method executes when the user presses on a control and does not release before the "long-press timeout" occurs. The "long-press timeout" is defined in Input.Pointers.MappedButton<ButtonIDType>.THRESHOLD_LONG_PRESS.
Parameters
evt
Implements Juniper.Events.ILongPressHandler.
Definition at line 69 of file Clickable.cs.
         {
             if (evt.button == clickButton && !IsDisabled)
             {
                 OnLongPress();
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.Clickable.OnLongPress().
OnLongPress() [2/2]
virtual void Juniper.Widgets.Clickable.OnLongPress () inline virtual
Definition at line 77 of file Clickable.cs.
         {
             onLongPress?.Invoke();
             LongPress?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Widgets.Clickable.LongPress, and Juniper.Widgets.Clickable.onLongPress.
Referenced by Juniper.Widgets.Clickable.OnLongPress().
OnLongPressUpdate()
void Juniper.Widgets.Clickable.OnLongPressUpdate (PointerEventData evt) inline
In the process of registering a Long Press event, the receiving control has the option to update its visual representationi based on how long the user has been pressing it.
Parameters
evt
Implements Juniper.Events.ILongPressHandler.
Definition at line 83 of file Clickable.cs.
         {
             if (evt.button == clickButton && !IsDisabled)
             {
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, and Juniper.Widgets.AbstractTouchable.IsDisabled.
OnPointerClick()
virtual void Juniper.Widgets.Clickable.OnPointerClick (PointerEventData eventData) inline virtual
Trigger the onClick/Click events, if they are valid.
Parameters
eventData
Reimplemented in Juniper.Widgets.Openable.
Definition at line 43 of file Clickable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 OnClick();
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.Clickable.OnClick().
OnPointerDown()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerDown (PointerEventData eventData) inline virtual inherited
React to the primary button being pressed on the control.
Parameters
eventData Event data.
Definition at line 258 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton)
             {
                 if (IsDisabled)
                 {
                     ShowState("Disabled");
                 }
                 else
                 {
                     GetPosition(eventData);
                     ShowState("Pressed");
                 }
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerEnter()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerEnter (PointerEventData eventData) inline virtual inherited
React to the pointer hovering over the control.
Parameters
eventData Event data.
Definition at line 232 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerExit()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerExit (PointerEventData eventData) inline virtual inherited
React to the pointer leaving the control and no longer hovering over it.
Parameters
eventData Event data.
Definition at line 245 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Normal");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerUp()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerUp (PointerEventData eventData) inline virtual inherited
React to the primary button being released from the control.
Parameters
eventData Event data.
Definition at line 278 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
SetDisabled()
void Juniper.Widgets.AbstractTouchable.SetDisabled (bool value) inline inherited
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
Parameters
value
Definition at line 124 of file AbstractTouchable.cs.
         {
             IsDisabled = value;
         }
References Juniper.Widgets.AbstractTouchable.IsDisabled.
ShowState()
string Juniper.Widgets.AbstractTouchable.ShowState (string enabledPart) inline protected inherited
Trigger the animation or swap the gameObjects to show the current control UI state.
Returns
The state.
Parameters
enabledPart Enabled part.
Definition at line 207 of file AbstractTouchable.cs.
         {
             enabledPart = NormalizePart(enabledPart);
             if (animator != null)
             {
                 animator.Play(enabledPart);
             }
             return enabledPart;
         }
References Juniper.Widgets.AbstractTouchable.animator, Juniper.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Animation.AbstractAnimator.Play().
Referenced by Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Widgets.AbstractTouchable.Update().
ToggleEnabled()
void Juniper.Widgets.AbstractTouchable.ToggleEnabled () inline inherited
Toggles the boolean value of the disabled field.
Definition at line 132 of file AbstractTouchable.cs.
         {
             IsDisabled = !IsDisabled;
         }
References Juniper.Widgets.AbstractTouchable.IsDisabled.
Update()
virtual void Juniper.Widgets.AbstractTouchable.Update () inline virtual inherited
Update the physics state of the control, and enable/disable Disabled view on DisabledChanged.
Reimplemented in Juniper.Widgets.Rotatable, and Juniper.Widgets.Openable.
Definition at line 168 of file AbstractTouchable.cs.
         {
             if (DisabledDown)
             {
                 ShowState(PART_NAMES.Last());
             }
             else if (DisabledUp)
             {
                 ShowState(PART_NAMES[0]);
             }
         }
References Juniper.Widgets.AbstractTouchable.DisabledDown, Juniper.Widgets.AbstractTouchable.DisabledUp, Juniper.Widgets.AbstractTouchable.PART_NAMES, and Juniper.Widgets.AbstractTouchable.ShowState().
Referenced by Juniper.Widgets.AbstractValued.SetValue().
Member Data Documentation
clickButton
InputButton Juniper.Widgets.AbstractTouchable.clickButton inherited
The button we are expecting to use to interact with this object.
Definition at line 42 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.Clickable.OnLongPress(), Juniper.Widgets.Clickable.OnLongPressUpdate(), Juniper.Widgets.Clickable.OnPointerClick(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Widgets.AbstractTouchable.OnPointerUp().
disabled
bool Juniper.Widgets.AbstractTouchable.disabled inherited
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occurring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Definition at line 57 of file AbstractTouchable.cs.
Referenced by Juniper.Settings.AccessibilitySettings.Device.EnableButton(), and Juniper.Widgets.AbstractTouchable.IsInteractable().
lastPointerPosition
Vector3 Juniper.Widgets.AbstractTouchable.lastPointerPosition protected inherited
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
Definition at line 146 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.LateUpdate(), and Juniper.Widgets.AbstractValued.OnDrag().
onClick
UnityEvent Juniper.Widgets.Clickable.onClick
The event to call when the button is enabled and clicked. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr Click.
Definition at line 26 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnClick().
onLongPress
UnityEvent Juniper.Widgets.Clickable.onLongPress
Definition at line 28 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnLongPress().
PART_NAMES
string [] Juniper.Widgets.AbstractTouchable.PART_NAMES static inherited
Initial value:
=
        {
            "Normal",
            "Hovered",
            "Pressed",
            "Opened",
            "Disabled"
        }
The names of the animation states that Touchable expects.
Definition at line 30 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.Awake(), Juniper.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Widgets.AbstractTouchable.Update().
pointerPosition
Vector3 Juniper.Widgets.AbstractTouchable.pointerPosition inherited
The place near the control that the pointer was pointing.
Definition at line 140 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.LateUpdate(), Juniper.Widgets.AbstractValued.OnBeginDrag(), and Juniper.Widgets.AbstractValued.OnDrag().
Property Documentation
IsDisabled
bool Juniper.Widgets.AbstractTouchable.IsDisabled get set inherited
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
Definition at line 107 of file AbstractTouchable.cs.
         {
             get
             {
                 return !isActiveAndEnabled || disabled;
             }
             set
             {
                 disabled = value;
             }
         }
Referenced by Juniper.Widgets.Clickable.ActivateClick(), Juniper.Widgets.AbstractTouchable.LateUpdate(), Juniper.Widgets.Rotatable.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.Rotatable.OnDrag(), Juniper.Widgets.Draggable.OnDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.Clickable.OnLongPress(), Juniper.Widgets.Clickable.OnLongPressUpdate(), Juniper.Widgets.Clickable.OnPointerClick(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Widgets.AbstractTouchable.SetDisabled(), Juniper.Widgets.Openable.SetOpen(), Juniper.Widgets.AbstractTouchable.ToggleEnabled(), and Juniper.Widgets.Rotatable.Update().
PointerPositionChanged
bool Juniper.Widgets.AbstractTouchable.PointerPositionChanged get protected inherited
Returns true when pointerPosition has changed since the last frame.
true if pointer position changed; otherwise, false.
Definition at line 153 of file AbstractTouchable.cs.
         {
             get
             {
                 return pointerPosition != lastPointerPosition;
             }
         }
Event Documentation
Click
EventHandler Juniper.Widgets.Clickable.Click
The event to call when the button is enabled and clicked. You should only use this verison if you are programmatically attaching event listenters. if you are using the Unity Editor, you should prefer onClick.
Definition at line 35 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnClick(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnDisable(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnEnable().
LongPress
EventHandler Juniper.Widgets.Clickable.LongPress
Definition at line 37 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnLongPress().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Widgets/Clickable.cs