Juniper: Juniper.MediaType.Model Class Reference
Juniper.MediaType.Model Class Reference
Public Member Functions
override bool Matches (string fileName)
bool Matches (FileInfo file)
string AddExtension (string fileName)
bool Equals (string other)
override bool Equals (object obj)
bool Equals (MediaType other)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static MediaType Parse (string value)
static IReadOnlyCollection< MediaType > ParseAll (string[] acceptTypes)
static bool TryParse (string value, out MediaType type)
static IReadOnlyList< MediaType > GuessByFileName (string fileName)
static IReadOnlyList< MediaType > GuessByFile (FileInfo file)
static MediaType Lookup (string value)
static ContentReference operator+ (string cacheID, MediaType contentType)
static implicit operator string (MediaType mediaType)
static bool operator== (MediaType left, MediaType right)
static bool operator== (MediaType left, string right)
static bool operator== (string left, MediaType right)
static bool operator != (MediaType left, MediaType right)
static bool operator != (MediaType left, string right)
static bool operator != (string left, MediaType right)
Static Public Attributes
static readonly Model AnyModel = new Model("*")
static readonly Model Example = new Model("example")
static readonly Model Gltf_Binary = new Model("gltf-binary")
static readonly Model GltfJson = new Model("gltf+json", new string[] { "json" })
static readonly Model Iges = new Model("iges", new string[] { "igs", "iges" })
static readonly Model Mesh = new Model("mesh", new string[] { "msh", "mesh", "silo" })
static readonly Model Stl = new Model("stl")
static readonly Model Vendor3mf = new Model("3mf")
static readonly Model VendorColladaXml = new Model("vnd.collada+xml", new string[] { "dae" })
static readonly Model VendorDwf = new Model("vnd.dwf", new string[] { "dwf" })
static readonly Model VendorFlatland3dml = new Model("vnd.flatland.3dml")
static readonly Model VendorGdl = new Model("vnd.gdl", new string[] { "gdl" })
static readonly Model VendorGs_Gdl = new Model("vnd.gs-gdl")
static readonly Model VendorGsGdl = new Model("vnd.gs.gdl")
static readonly Model VendorGtw = new Model("vnd.gtw", new string[] { "gtw" })
static readonly Model VendorMomlXml = new Model("vnd.moml+xml", new string[] { "xml" })
static readonly Model VendorMts = new Model("vnd.mts", new string[] { "mts" })
static readonly Model VendorOpengex = new Model("vnd.opengex")
static readonly Model VendorParasolidTransmitBinary = new Model("vnd.parasolid.transmit.binary")
static readonly Model VendorParasolidTransmitText = new Model("vnd.parasolid.transmit.text")
static readonly Model VendorRosetteAnnotated_Data_Model = new Model("vnd.rosette.annotated-data-model")
static readonly Model VendorUsdzZip = new Model("vnd.usdz+zip", new string[] { "zip" })
static readonly Model VendorValveSourceCompiled_Map = new Model("vnd.valve.source.compiled-map")
static readonly Model VendorVtu = new Model("vnd.vtu", new string[] { "vtu" })
static readonly Model Vrml = new Model("vrml", new string[] { "wrl", "vrml" })
static readonly Model X3d_Vrml = new Model("x3d-vrml")
static readonly Model X3dBinary = new Model("x3d+binary", new string[] { "x3db", "x3dbz" })
static readonly Model X3dFastinfoset = new Model("x3d+fastinfoset", new string[] { "fastinfoset" })
static readonly Model X3dVrml = new Model("x3d+vrml", new string[] { "x3dv", "x3dvz" })
static readonly Model X3dXml = new Model("x3d+xml", new string[] { "x3d", "x3dz" })
static new readonly Model [] Values
static readonly MediaType Any = new MediaType("*/*")
static readonly IReadOnlyCollection< MediaType > All = new MediaType[] { Any }
Properties
string Value [get]
string TypeName [get]
string SubTypeName [get]
float Weight [get]
ReadOnlyCollection< string > Extensions [get]
string PrimaryExtension [get]
Private Member Functions
Model (string value, string[] extensions)
Model (string value)
Detailed Description
Definition at line 7 of file Model.cs.
Constructor & Destructor Documentation
Model() [1/2]
Juniper.MediaType.Model.Model (string value, string [] extensions) inline private
Definition at line 9 of file Model.cs.
 : base("model/" + value, extensions) { }
Model() [2/2]
Juniper.MediaType.Model.Model (string value) inline private
Definition at line 11 of file Model.cs.
 : this(value, null) { }
Member Function Documentation
AddExtension()
string Juniper.MediaType.AddExtension (string fileName) inline inherited
Definition at line 310 of file MediaType.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (PrimaryExtension is object)
             {
                 var currentExtension = PathExt.GetShortExtension(fileName);
                 if (Extensions.IndexOf(currentExtension) == -1)
                 {
                     fileName += "." + PrimaryExtension;
                 }
             }
             return fileName;
         }
References Juniper.MediaType.Extensions, System.IO.PathExt.GetShortExtension(), and Juniper.MediaType.PrimaryExtension.
Referenced by Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), and Juniper.IO.ContentReference.operator string().
Equals() [1/3]
bool Juniper.MediaType.Equals (string other) inline inherited
Definition at line 329 of file MediaType.cs.
         {
             return TryParse(other, out var type)
                 && Equals(type);
         }
References Juniper.MediaType.TryParse().
Referenced by Juniper.MediaType.Equals().
Equals() [2/3]
override bool Juniper.MediaType.Equals (object obj) inline inherited
Definition at line 335 of file MediaType.cs.
         {
             return (obj is MediaType type && Equals(type))
                 || (obj is string str && Equals(str));
         }
References Juniper.MediaType.Equals().
Equals() [3/3]
bool Juniper.MediaType.Equals (MediaType other) inline inherited
Definition at line 341 of file MediaType.cs.
         {
             return other is object
                 && (TypeName == "*"
                     || other.TypeName == "*"
                     || TypeName == other.TypeName)
                 && (SubTypeName == "*"
                     || other.SubTypeName == "*"
                     || SubTypeName == other.SubTypeName);
         }
References Juniper.MediaType.SubTypeName, and Juniper.MediaType.TypeName.
GetHashCode()
override int Juniper.MediaType.GetHashCode () inline inherited
Definition at line 397 of file MediaType.cs.
         {
             var hashCode = -1006577490;
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(TypeName);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(SubTypeName);
             hashCode = (hashCode * -1521134295) + Weight.GetHashCode();
             hashCode = (hashCode * -1521134295) + EqualityComparer<ReadOnlyCollection<string>>.Default.GetHashCode(Extensions);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(PrimaryExtension);
             return hashCode;
         }
References Juniper.MediaType.Extensions, Juniper.MediaType.PrimaryExtension, Juniper.MediaType.SubTypeName, Juniper.MediaType.TypeName, and Juniper.MediaType.Weight.
GuessByFile()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFile (FileInfo file) inline static inherited
Definition at line 155 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return GuessByFileName(file.Name);
         }
References Juniper.MediaType.GuessByFileName().
Referenced by Juniper.HTTP.Server.HttpListenerResponseExt.SendFileAsync().
GuessByFileName()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFileName (string fileName) inline static inherited
Definition at line 144 of file MediaType.cs.
         {
             if (string.IsNullOrEmpty(fileName))
             {
                 throw new ArgumentException("Must provide a valid fileName", nameof(fileName));
             }
             var ext = Path.GetExtension(fileName);
             return GuessByExtension(ref ext);
         }
References Juniper.MediaType.GuessByExtension().
Referenced by Juniper.MediaType.GuessByFile(), and Juniper.MediaType.Matches().
Lookup()
static MediaType Juniper.MediaType.Lookup (string value) inline static inherited
Definition at line 165 of file MediaType.cs.
         {
             // Trim off the weight, if one exists
             var parts = value.SplitX(';');
             if (parts.Length > 0)
             {
                 value = parts[0];
             }
             if (byValue.ContainsKey(value))
             {
                 return byValue[value];
             }
             var name = Array.Find(parts, p => p.Length > 0);
             if (string.IsNullOrEmpty(name))
             {
                 return Lookup("unknown/unknown");
             }
             else
             {
                 return new Unknown(name);
             }
         }
References Juniper.MediaType.byValue.
Matches() [1/2]
override bool Juniper.MediaType.Model.Matches (string fileName) inline virtual
Reimplemented from Juniper.MediaType.
Definition at line 15 of file Model.cs.
             {
                 if (ReferenceEquals(this, AnyModel))
                 {
                     return Values.Any(x => x.Matches(fileName));
                 }
                 else
                 {
                     return base.Matches(fileName);
                 }
             }
References Juniper.MediaType.Any, Juniper.MediaType.Model.AnyModel, Juniper.MediaType.Matches(), and Juniper.MediaType.Model.Values.
Matches() [2/2]
bool Juniper.MediaType.Matches (FileInfo file) inline inherited
Definition at line 300 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return Matches(file.Name);
         }
References Juniper.MediaType.Matches().
operator !=() [1/3]
static bool Juniper.MediaType.operator != (MediaType left, MediaType right) inline static inherited
Definition at line 358 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [2/3]
static bool Juniper.MediaType.operator != (MediaType left, string right) inline static inherited
Definition at line 369 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [3/3]
static bool Juniper.MediaType.operator != (string left, MediaType right) inline static inherited
Definition at line 380 of file MediaType.cs.
         {
             return !(left == right);
         }
operator string()
static implicit Juniper.MediaType.operator string (MediaType mediaType) inline static inherited
Definition at line 196 of file MediaType.cs.
         {
             return mediaType?.ToString();
         }
operator+()
static ContentReference Juniper.MediaType.operator+ (string cacheID, MediaType contentType) inline static inherited
Definition at line 191 of file MediaType.cs.
         {
             return new ContentReference(cacheID, contentType);
         }
operator==() [1/3]
static bool Juniper.MediaType.operator== (MediaType left, MediaType right) inline static inherited
Definition at line 352 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [2/3]
static bool Juniper.MediaType.operator== (MediaType left, string right) inline static inherited
Definition at line 363 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [3/3]
static bool Juniper.MediaType.operator== (string left, MediaType right) inline static inherited
Definition at line 374 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (right is object && right.Equals(left));
         }
Parse()
static MediaType Juniper.MediaType.Parse (string value) inline static inherited
Definition at line 40 of file MediaType.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             if (TryParse(value, out var type))
             {
                 return type;
             }
             else
             {
                 throw new ArgumentException($"Type value does not match expected pattern {TYPE_PATTERN.ToString()}", nameof(value));
             }
         }
References Juniper.MediaType.TryParse().
ParseAll()
static IReadOnlyCollection<MediaType> Juniper.MediaType.ParseAll (string [] acceptTypes) inline static inherited
Definition at line 57 of file MediaType.cs.
         {
             if (acceptTypes is null || acceptTypes.Length == 0)
             {
                 return All;
             }
             else
             {
                 return InternalParseAll(acceptTypes).ToArray();
             }
         }
References Juniper.MediaType.All, and Juniper.MediaType.InternalParseAll().
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable().
ToString()
override string Juniper.MediaType.ToString () inline inherited
Definition at line 385 of file MediaType.cs.
         {
             if (Weight == 1)
             {
                 return Value;
             }
             else
             {
                 return weightedValue;
             }
         }
References Juniper.MediaType.Value, Juniper.MediaType.Weight, and Juniper.MediaType.weightedValue.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.ListDirectoryAsync().
TryParse()
static bool Juniper.MediaType.TryParse (string value, out MediaType type) inline static inherited
Definition at line 83 of file MediaType.cs.
         {
             type = null;
             if (value is null)
             {
                 return false;
             }
             var match = TYPE_PATTERN.Match(value);
             if (!match.Success)
             {
                 return false;
             }
             var typeName = match.Groups[1].Value;
             var subTypeName = match.Groups[2].Value;
             var rawValue = typeName + "/" + subTypeName;
             if (match.Groups.Count == 4
                 && float.TryParse(
                     match.Groups[3].Value,
                     NumberStyles.Integer | NumberStyles.AllowDecimalPoint,
                     CultureInfo.InvariantCulture,
                     out var weight))
             {
                 type = new MediaType(typeName, subTypeName, weight);
             }
             else if (byValue.ContainsKey(rawValue))
             {
                 type = byValue[rawValue];
             }
             else
             {
                 type = new MediaType(typeName, subTypeName);
             }
             return type is object;
         }
References Juniper.MediaType.byValue, Juniper.MediaType.MediaType(), and Juniper.MediaType.TYPE_PATTERN.
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.InternalParseAll(), Juniper.MediaType.Parse(), and Juniper.Processes.ProcessArgs.TryGetMediaType().
Member Data Documentation
All
readonly IReadOnlyCollection<MediaType> Juniper.MediaType.All = new MediaType[] { Any } static inherited
Definition at line 38 of file MediaType.cs.
Referenced by Juniper.MediaType.ParseAll().
Any
readonly MediaType Juniper.MediaType.Any = new MediaType("*/*") static inherited
Definition at line 36 of file MediaType.cs.
Referenced by Juniper.MediaType.Application.Matches(), Juniper.MediaType.Audio.Matches(), Juniper.MediaType.Chemical.Matches(), Juniper.MediaType.Font.Matches(), Juniper.MediaType.Image.Matches(), Juniper.MediaType.Message.Matches(), Juniper.MediaType.Model.Matches(), Juniper.MediaType.Multipart.Matches(), Juniper.MediaType.Text.Matches(), Juniper.MediaType.Video.Matches(), and Juniper.MediaType.XConference.Matches().
AnyModel
readonly Model Juniper.MediaType.Model.AnyModel = new Model("*") static
Definition at line 13 of file Model.cs.
Referenced by Juniper.MediaType.Model.Matches().
Example
readonly Model Juniper.MediaType.Model.Example = new Model("example") static
Definition at line 7 of file Model.Values.cs.
Gltf_Binary
readonly Model Juniper.MediaType.Model.Gltf_Binary = new Model("gltf-binary") static
Definition at line 8 of file Model.Values.cs.
GltfJson
readonly Model Juniper.MediaType.Model.GltfJson = new Model("gltf+json", new string[] { "json" }) static
Definition at line 9 of file Model.Values.cs.
Iges
readonly Model Juniper.MediaType.Model.Iges = new Model("iges", new string[] { "igs", "iges" }) static
Definition at line 10 of file Model.Values.cs.
Mesh
readonly Model Juniper.MediaType.Model.Mesh = new Model("mesh", new string[] { "msh", "mesh", "silo" }) static
Definition at line 11 of file Model.Values.cs.
Stl
readonly Model Juniper.MediaType.Model.Stl = new Model("stl") static
Definition at line 12 of file Model.Values.cs.
Values
new readonly Model [] Juniper.MediaType.Model.Values static
Definition at line 37 of file Model.Values.cs.
Referenced by Juniper.MediaType.Model.Matches().
Vendor3mf
readonly Model Juniper.MediaType.Model.Vendor3mf = new Model("3mf") static
Definition at line 13 of file Model.Values.cs.
VendorColladaXml
readonly Model Juniper.MediaType.Model.VendorColladaXml = new Model("vnd.collada+xml", new string[] { "dae" }) static
Definition at line 14 of file Model.Values.cs.
VendorDwf
readonly Model Juniper.MediaType.Model.VendorDwf = new Model("vnd.dwf", new string[] { "dwf" }) static
Definition at line 15 of file Model.Values.cs.
VendorFlatland3dml
readonly Model Juniper.MediaType.Model.VendorFlatland3dml = new Model("vnd.flatland.3dml") static
Definition at line 16 of file Model.Values.cs.
VendorGdl
readonly Model Juniper.MediaType.Model.VendorGdl = new Model("vnd.gdl", new string[] { "gdl" }) static
Definition at line 17 of file Model.Values.cs.
VendorGs_Gdl
readonly Model Juniper.MediaType.Model.VendorGs_Gdl = new Model("vnd.gs-gdl") static
Definition at line 18 of file Model.Values.cs.
VendorGsGdl
readonly Model Juniper.MediaType.Model.VendorGsGdl = new Model("vnd.gs.gdl") static
Definition at line 19 of file Model.Values.cs.
VendorGtw
readonly Model Juniper.MediaType.Model.VendorGtw = new Model("vnd.gtw", new string[] { "gtw" }) static
Definition at line 20 of file Model.Values.cs.
VendorMomlXml
readonly Model Juniper.MediaType.Model.VendorMomlXml = new Model("vnd.moml+xml", new string[] { "xml" }) static
Definition at line 21 of file Model.Values.cs.
VendorMts
readonly Model Juniper.MediaType.Model.VendorMts = new Model("vnd.mts", new string[] { "mts" }) static
Definition at line 22 of file Model.Values.cs.
VendorOpengex
readonly Model Juniper.MediaType.Model.VendorOpengex = new Model("vnd.opengex") static
Definition at line 23 of file Model.Values.cs.
VendorParasolidTransmitBinary
readonly Model Juniper.MediaType.Model.VendorParasolidTransmitBinary = new Model("vnd.parasolid.transmit.binary") static
Definition at line 24 of file Model.Values.cs.
VendorParasolidTransmitText
readonly Model Juniper.MediaType.Model.VendorParasolidTransmitText = new Model("vnd.parasolid.transmit.text") static
Definition at line 25 of file Model.Values.cs.
VendorRosetteAnnotated_Data_Model
readonly Model Juniper.MediaType.Model.VendorRosetteAnnotated_Data_Model = new Model("vnd.rosette.annotated-data-model") static
Definition at line 26 of file Model.Values.cs.
VendorUsdzZip
readonly Model Juniper.MediaType.Model.VendorUsdzZip = new Model("vnd.usdz+zip", new string[] { "zip" }) static
Definition at line 27 of file Model.Values.cs.
VendorValveSourceCompiled_Map
readonly Model Juniper.MediaType.Model.VendorValveSourceCompiled_Map = new Model("vnd.valve.source.compiled-map") static
Definition at line 28 of file Model.Values.cs.
VendorVtu
readonly Model Juniper.MediaType.Model.VendorVtu = new Model("vnd.vtu", new string[] { "vtu" }) static
Definition at line 29 of file Model.Values.cs.
Vrml
readonly Model Juniper.MediaType.Model.Vrml = new Model("vrml", new string[] { "wrl", "vrml" }) static
Definition at line 30 of file Model.Values.cs.
X3d_Vrml
readonly Model Juniper.MediaType.Model.X3d_Vrml = new Model("x3d-vrml") static
Definition at line 31 of file Model.Values.cs.
X3dBinary
readonly Model Juniper.MediaType.Model.X3dBinary = new Model("x3d+binary", new string[] { "x3db", "x3dbz" }) static
Definition at line 32 of file Model.Values.cs.
X3dFastinfoset
readonly Model Juniper.MediaType.Model.X3dFastinfoset = new Model("x3d+fastinfoset", new string[] { "fastinfoset" }) static
Definition at line 33 of file Model.Values.cs.
X3dVrml
readonly Model Juniper.MediaType.Model.X3dVrml = new Model("x3d+vrml", new string[] { "x3dv", "x3dvz" }) static
Definition at line 34 of file Model.Values.cs.
X3dXml
readonly Model Juniper.MediaType.Model.X3dXml = new Model("x3d+xml", new string[] { "x3d", "x3dz" }) static
Definition at line 35 of file Model.Values.cs.
Property Documentation
Extensions
ReadOnlyCollection<string> Juniper.MediaType.Extensions get inherited
Definition at line 211 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.UpdateLookupTables().
PrimaryExtension
string Juniper.MediaType.PrimaryExtension get inherited
Definition at line 213 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
SubTypeName
string Juniper.MediaType.SubTypeName get inherited
Definition at line 207 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
TypeName
string Juniper.MediaType.TypeName get inherited
Definition at line 205 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
Value
string Juniper.MediaType.Value get inherited
Definition at line 203 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.MediaType(), Juniper.MediaType.ToString(), and Juniper.MediaType.UpdateLookupTables().
Weight
float Juniper.MediaType.Weight get inherited
Definition at line 209 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.ToString().
The documentation for this class was generated from the following files:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Model.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Model.Values.cs