Juniper: Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT > Class Template Reference
Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT > Class Template Reference
Public Member Functions
void ReceiveCredentials (string[] args)
override void Awake ()
void OnEnable ()
void OnDisable ()
override void Enter (IProgress prog)
Fire the OnEnable event and perform the Enter transition.
void SetLocation (string location)
void Update ()
void SwitchToScene (string sceneName)
void ShowScene (string sceneName)
void ShowView (string viewName)
void Quit ()
void Enter ()
void Exit ()
virtual void Exit (IProgress prog)
Fire the OnExiting event and perform the Exit transition.
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
virtual void SkipExit ()
Task EnterAsync (IProgress prog=null)
Task ExitAsync (IProgress prog=null)
Public Attributes
int searchRadius = 50
float [] searchFOVs
string searchLocation
bool unloadSceneOnExit = true
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
UnityEvent onStopped = new UnityEvent()
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Direction _curState
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void Complete ()
Finish the transition, whatever is going on.
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
virtual void OnStopped ()
Protected Attributes
bool skipEvents
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Properties
abstract string CachePrefix [get]
string CredentialFile [get]
bool IsBusy [get]
Direction State [get, private set]
virtual bool IsComplete [get]
Returns true when State is Direction.Stopped
bool IsEntering [get]
bool IsExiting [get]
bool CanExit [get]
bool CanEnter [get]
bool IsRunning [get]
Returns true when State is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
Events
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
EventHandler Stopped
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Private Member Functions
async Task CaptureCubemap (PhotosphereJig photosphere)
void Photosphere_Complete (PhotosphereJig jig, bool captureCubemap)
Texture2D Photosphere_CubemapNeeded (Photosphere source)
async Task< Texture2D > Photosphere_ImageNeeded (PhotosphereJig source, int fov, int heading, int pitch)
Texture2D Decode (Stream imageStream)
void NavPlane_Click (object sender, EventArgs e)
void SyncData (IProgress prog)
async Task SearchPoint ()
async Task SearchData (string searchPano, LatLngPoint searchPoint, IProgress prog)
async Task< PhotosphereJig > GetPhotosphere ()
bool ParseSearchParams (string searchLocation, out string searchPano, out LatLngPoint searchPoint)
LatLngPoint GetRelativeLatLng (Vector3 cursorPosition)
Vector3 GetRelativeVector3 (MetadataTypeT metadata)
Private Attributes
readonly Dictionary< string, Transform > navPointers = new Dictionary<string, Transform>()
string gmapsApiKey
string gmapsSigningKey
LatLngPoint origin
Vector3 cursorPosition
Vector3 lastCursorPosition
string navPointerPano
MetadataTypeT metadata
GoogleMapsClient< MetadataTypeT > gmaps
GPSLocation gps
PhotosphereManager photospheres
Clickable navPlane
Avatar avatar
Transform navPointer
UnifiedInputModule input
CachingStrategy cache
IImageCodec< Texture2D > codec
PhotosphereJig lastSphere
UnityTexture2DProcessor processor
Task searchTask
LoadingBar loadingBar
Task captureTask
readonly HashSet< string > imageNeededSet = new HashSet<string>()
Static Private Attributes
static readonly Regex GMAPS_URL_PANO_PATTERN
static readonly Regex GMAPS_URL_LATLNG_PATTERN
static readonly CubemapFace [] CAPTURE_CUBEMAP_FACES
static readonly Texture2D [] CAPTURE_CUBEMAP_SUB_IMAGES = new Texture2D[CAPTURE_CUBEMAP_FACES.Length]
Detailed Description
Type Constraints
MetadataTypeT : MetadataResponse
Definition at line 23 of file AbstractGoogleStreetView.cs.
Member Function Documentation
Awake()
override void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.Awake () inline virtual
Reimplemented from Juniper.SubSceneController.
Definition at line 124 of file AbstractGoogleStreetView.cs.
         {
             base.Awake();
             processor = new UnityTexture2DProcessor();
             Find.Any(out loadingBar);
             Find.Any(out gps);
             if (!this.FindClosest(out photospheres))
             {
                 photospheres = this.Ensure<PhotosphereManager>();
             }
             Find.Any(out avatar);
             navPlane = avatar.GroundPlane.Ensure<Clickable>();
             navPlane.Activate();
             navPointer = transform.Find("NavPointer");
             if (navPointer != null)
             {
                 navPointer.Deactivate();
             }
             Find.Any(out input);
             cache = new CachingStrategy();
 #if UNITY_EDITOR
             this.ReceiveCredentials();
             locationInput = this.Ensure<EditorTextInput>();
             locationInput.OnSubmit.AddListener(new UnityAction<string>(SetLocation));
             if (!string.IsNullOrEmpty(locationInput.value))
             {
                 SetLocation(locationInput.value);
             }
             else if (gps != null && gps.HasCoord)
             {
                 SetLocation(gps.Coord.ToString());
             }
             var myPictures = Environment.GetFolderPath(Environment.SpecialFolder.MyPictures);
             var oldCubemapPath = Path.Combine(myPictures, "GoogleMaps");
             var oldGmapsPath = Path.Combine(oldCubemapPath, "streetview", "maps", "api");
             cache.AddBackup(new FileCacheLayer(oldCubemapPath));
             cache.AddBackup(new FileCacheLayer(oldGmapsPath));
 #else
             if(gps != null && gps.HasCoord)
             {
                 SetLocation(gps.Coord.ToString());
             }
 #endif
             var newGmapsPath = Path.Combine(CachePrefix, "Google", "StreetView");
             cache.Add(new StreamingAssetsCacheLayer(newGmapsPath));
             codec = new UnityTexture2DCodec(MediaType.Image.Jpeg);
             var metadataDecoder = new JsonFactory<MetadataTypeT>();
             var geocodingDecoder = new JsonFactory<GeocodingResponse>();
             gmaps = new GoogleMapsClient<MetadataTypeT>(gmapsApiKey, gmapsSigningKey, metadataDecoder, geocodingDecoder, cache);
             photospheres.CubemapNeeded += Photosphere_CubemapNeeded;
             photospheres.SetIO(cache, codec);
             photospheres.SetDetailLevels(searchFOVs);
         }
CaptureCubemap()
async Task Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.CaptureCubemap (PhotosphereJig photosphere) inline private
Definition at line 213 of file AbstractGoogleStreetView.cs.
         {
             try
             {
                 var fileRef = photosphere.name + codec.ContentType;
                 if (cache.IsCached(fileRef))
                 {
                     Debug.Log("Cubemap already cached");
                 }
                 else
                 {
                     loadingBar.Activate();
                     const int dim = 2048;
                     Cubemap cubemap = null;
                     Texture2D img = null;
                     await loadingBar.RunAsync(
                         ("Rendering cubemap", async (prog) =>
{
                             cubemap = await JuniperSystem.OnMainThreadAsync(() =>
{
                                 prog.Report(0);
                                 var cb = new Cubemap(dim, TextureFormat.RGB24, false);
                                 cb.Apply();
                                 var curMask = DisplayManager.MainCamera.cullingMask;
                                 DisplayManager.MainCamera.cullingMask = LayerMask.GetMask(Photosphere.PHOTOSPHERE_LAYER_ARR);
                                 var curRotation = DisplayManager.MainCamera.transform.rotation;
                                 DisplayManager.MainCamera.transform.rotation = Quaternion.identity;
                                 DisplayManager.MainCamera.RenderToCubemap(cb, 63);
                                 DisplayManager.MainCamera.cullingMask = curMask;
                                 DisplayManager.MainCamera.transform.rotation = curRotation;
                                 prog.Report(1);
                                 return cb;
                             });
                         }
                     ),
                         ("Copying cubemap faces", async (prog) =>
{
                             for (var f = 0; f < CAPTURE_CUBEMAP_FACES.Length; ++f)
{
                                 await JuniperSystem.OnMainThreadAsync(() =>
{
                                     prog.Report(f, CAPTURE_CUBEMAP_FACES.Length, CAPTURE_CUBEMAP_FACES[f].ToString());
                                     var pixels = cubemap.GetPixels(CAPTURE_CUBEMAP_FACES[f]);
                                     var texture = new Texture2D(cubemap.width, cubemap.height);
                                     texture.SetPixels(pixels);
                                     texture.Apply();
                                     CAPTURE_CUBEMAP_SUB_IMAGES[f] = texture;
                                     prog.Report(f + 1, CAPTURE_CUBEMAP_FACES.Length);
                                 });
                             }
                         }
                     ),
                         ("Concatenating faces", async (prog) =>
{
                             img = await JuniperSystem.OnMainThreadAsync(() =>
                                 processor.Concatenate(ImageData.CubeCross(CAPTURE_CUBEMAP_SUB_IMAGES), prog));
                         }
                     ),
                         ("Saving image", (prog) =>
                             JuniperSystem.OnMainThreadAsync(() => cache.Save(codec, fileRef, img))));
                     loadingBar.Deactivate();
                 }
                 await JuniperSystem.OnMainThreadAsync(photosphere.DestroyJig);
                 var anyDestroyed = await JuniperSystem.OnMainThreadAsync(() =>
                 {
                     var any = false;
                     foreach (var texture in CAPTURE_CUBEMAP_SUB_IMAGES)
                     {
                         if (texture != null)
{
                             any = true;
                             Destroy(texture);
                         }
                     }
                     return any;
                 });
                 if (anyDestroyed)
                 {
                     Resources.UnloadUnusedAssets();
                     GC.Collect();
                 }
                 photosphere.enabled = false;
                 await Task.Yield();
                 photosphere.enabled = true;
             }
             catch (Exception exp)
             {
                 Debug.LogError("Cubemap capture error");
                 Debug.LogException(exp, this);
                 throw;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_Complete().
Complete()
virtual void Juniper.AbstractStateController.Complete () inline protected virtual inherited
Finish the transition, whatever is going on.
Reimplemented in Juniper.Animation.AbstractTransitionController.
Definition at line 301 of file AbstractStateController.cs.
         {
             State = Direction.Stopped;
         }
References Juniper.AbstractStateController.State.
Referenced by Juniper.Widgets.MenuCollection.Enter(), Juniper.Widgets.MenuCollection.ExitingCouroutine(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnExiting(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), and Juniper.Widgets.MenuView.Trans_EnteredExited().
Decode()
Texture2D Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.Decode (Stream imageStream) inline private
Definition at line 363 of file AbstractGoogleStreetView.cs.
         {
             return codec.Deserialize(imageStream);
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_CubemapNeeded(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_ImageNeeded().
Enter() [1/2]
void Juniper.AbstractStateController.Enter () inline inherited
Definition at line 272 of file AbstractStateController.cs.
         {
             Enter(null);
         }
Referenced by Juniper.Widgets.MenuView.Enter(), Juniper.AbstractStateController.EnterAsync(), Juniper.Animation.FadeTransition.Fader(), Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.AbstractStateController.SkipEnter().
Enter() [2/2]
override void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.Enter (IProgress prog) inline virtual
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 376 of file AbstractGoogleStreetView.cs.
         {
             base.Enter(prog);
             SyncData(prog);
         }
EnterAsync()
Task Juniper.AbstractStateController.EnterAsync (IProgress prog = null) inline inherited
Definition at line 331 of file AbstractStateController.cs.
         {
             return Stopper(Enter, prog);
         }
References Juniper.AbstractStateController.Enter(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Exit() [1/2]
void Juniper.AbstractStateController.Exit () inline inherited
Definition at line 285 of file AbstractStateController.cs.
         {
             Exit(null);
         }
Referenced by Juniper.Widgets.MenuView.Exit(), Juniper.AbstractStateController.ExitAsync(), Juniper.Animation.FadeTransition.Fader(), and Juniper.AbstractStateController.SkipExit().
Exit() [2/2]
virtual void Juniper.AbstractStateController.Exit (IProgress prog) inline virtual inherited
Fire the OnExiting event and perform the Exit transition.
Reimplemented in Juniper.Animation.AbstractTransitionController, and Juniper.Widgets.MenuView.
Definition at line 293 of file AbstractStateController.cs.
         {
             SetState(prog, Direction.Reverse);
         }
References Juniper.AbstractStateController.SetState().
ExitAsync()
Task Juniper.AbstractStateController.ExitAsync (IProgress prog = null) inline inherited
Definition at line 336 of file AbstractStateController.cs.
         {
             return Stopper(Exit, prog);
         }
References Juniper.AbstractStateController.Exit(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), Juniper.MasterSceneController.RemoveSceneCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
GetPhotosphere()
async Task<PhotosphereJig> Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.GetPhotosphere () inline private
Definition at line 542 of file AbstractGoogleStreetView.cs.
         {
             var jig = await JuniperSystem.OnMainThreadAsync(() =>
                 photospheres.GetPhotosphere<PhotosphereJig>(metadata.Pano_ID));
             if (!imageNeededSet.Contains(metadata.Pano_ID))
             {
                 imageNeededSet.Add(metadata.Pano_ID);
                 jig.ImageNeeded += Photosphere_ImageNeeded;
 #if UNITY_EDITOR
                 jig.Complete += Photosphere_Complete;
 #endif
             }
             return jig;
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData().
GetRelativeLatLng()
LatLngPoint Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.GetRelativeLatLng (Vector3 cursorPosition) inline private
Definition at line 593 of file AbstractGoogleStreetView.cs.
         {
             var curUTM = origin.ToUTM();
             var curVec = curUTM.ToVector3();
             var nextVec = cursorPosition + curVec;
             nextVec.y = 0;
             var nextPoint = nextVec.ToUTM(curUTM.Zone, curUTM.Hemisphere).ToLatLng();
             return nextPoint;
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchPoint().
GetRelativeVector3()
Vector3 Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.GetRelativeVector3 (MetadataTypeT metadata) inline private
Definition at line 603 of file AbstractGoogleStreetView.cs.
         {
             var nextUTM = metadata.Location.ToUTM();
             var nextVec = nextUTM.ToVector3();
             var start = origin.ToVector3();
             var delta = nextVec - start;
             return delta;
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
NavPlane_Click()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.NavPlane_Click (object sender, EventArgs e) inline private
Definition at line 368 of file AbstractGoogleStreetView.cs.
         {
             if (!IsBusy && !string.IsNullOrEmpty(navPointerPano))
             {
                 searchLocation = navPointerPano;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnDisable(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnEnable().
OnDisable()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.OnDisable () inline
Definition at line 197 of file AbstractGoogleStreetView.cs.
         {
             navPlane.Click -= NavPlane_Click;
         }
OnEnable()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.OnEnable () inline
Definition at line 192 of file AbstractGoogleStreetView.cs.
         {
             navPlane.Click += NavPlane_Click;
         }
OnEntered()
virtual void Juniper.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Animation.FadeTransition, and Juniper.Widgets.MenuCollection.
Definition at line 379 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onEntered != null)
                 {
                     onEntered.Invoke();
                 }
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entered, Juniper.AbstractStateController.onEntered, and Juniper.AbstractStateController.skipEvents.
OnEntering()
virtual void Juniper.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Animation.AbstractTransitionController, Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 360 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onEntering != null)
                 {
                     onEntering?.Invoke();
                 }
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entering, Juniper.AbstractStateController.onEntering, and Juniper.AbstractStateController.skipEvents.
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 417 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onExited != null)
                 {
                     onExited.Invoke();
                 }
                 Exited?.Invoke(this, EventArgs.Empty);
             }
             enabled = false;
         }
References Juniper.AbstractStateController.Exited, Juniper.AbstractStateController.onExited, and Juniper.AbstractStateController.skipEvents.
OnExiting()
override void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.OnExiting () inline protected virtual
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented from Juniper.AbstractStateController.
Definition at line 382 of file AbstractGoogleStreetView.cs.
         {
             base.OnExiting();
             Complete();
         }
OnStopped()
virtual void Juniper.AbstractStateController.OnStopped () inline protected virtual inherited
Definition at line 430 of file AbstractStateController.cs.
         {
             if (onStopped != null)
             {
                 onStopped?.Invoke();
             }
             Stopped?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.onStopped, and Juniper.AbstractStateController.Stopped.
ParseSearchParams()
bool Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.ParseSearchParams (string searchLocation, out string searchPano, out LatLngPoint searchPoint) inline private
Definition at line 557 of file AbstractGoogleStreetView.cs.
         {
             searchPano = null;
             searchPoint = null;
             if (!string.IsNullOrEmpty(searchLocation))
             {
                 var panoMatch = GMAPS_URL_PANO_PATTERN.Match(searchLocation);
                 var latLngMatch = GMAPS_URL_LATLNG_PATTERN.Match(searchLocation);
                 if (panoMatch.Success && MetadataResponse.IsPano(panoMatch.Groups[1].Value))
                 {
                     searchPano = panoMatch.Groups[1].Value;
                 }
                 else if (MetadataResponse.IsPano(searchLocation))
                 {
                     searchPano = searchLocation;
                 }
                 if (latLngMatch.Success && LatLngPoint.TryParse(latLngMatch.Groups[1].Value, out var point))
                 {
                     searchPoint = point;
                 }
                 else if (LatLngPoint.TryParse(searchLocation, out var point2))
                 {
                     searchPoint = point2;
                 }
             }
             return metadata == null
                 || searchPano != null
                     && metadata.Pano_ID != searchPano
                 || searchPoint != null
                     && searchPoint.Distance(metadata.Location) > 3f;
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
Photosphere_Complete()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.Photosphere_Complete (PhotosphereJig jig, bool captureCubemap) inline private
Definition at line 319 of file AbstractGoogleStreetView.cs.
         {
             loadingBar.Deactivate();
             jig.ImageNeeded -= Photosphere_ImageNeeded;
             jig.Complete -= Photosphere_Complete;
             if (captureCubemap)
             {
                 captureTask = CaptureCubemap(jig);
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetPhotosphere(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_Complete().
Photosphere_CubemapNeeded()
Texture2D Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.Photosphere_CubemapNeeded (Photosphere source) inline private
Definition at line 331 of file AbstractGoogleStreetView.cs.
         {
             var cubemapRef = source.CubemapName + codec.ContentType;
             if (cache == null
                 || codec == null
                 || string.IsNullOrEmpty(source.CubemapName)
                 || !cache.IsCached(cubemapRef))
             {
                 return null;
             }
             else
             {
                 using (var stream = cache.OpenAsync(cubemapRef).Result)
                 {
                     return Decode(stream);
                 }
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
Photosphere_ImageNeeded()
async Task<Texture2D> Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.Photosphere_ImageNeeded (PhotosphereJig source, int fov, int heading, int pitch) inline private
Definition at line 350 of file AbstractGoogleStreetView.cs.
         {
             if (gmaps == null
                 || codec == null)
             {
                 return null;
             }
             else
             {
                 return Decode(await gmaps.GetImageAsync(source.CubemapName, fov, heading, pitch));
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetPhotosphere(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_Complete().
Quit()
void Juniper.SubSceneController.Quit () inline inherited
Definition at line 38 of file SubSceneController.cs.
         {
             master.Quit();
         }
References Juniper.SubSceneController.master, and Juniper.MasterSceneController.Quit().
ReceiveCredentials()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.ReceiveCredentials (string [] args) inline
Implements Juniper.Security.ICredentialReceiver.
Definition at line 99 of file AbstractGoogleStreetView.cs.
         {
             if (args == null)
             {
                 gmapsApiKey = null;
                 gmapsSigningKey = null;
             }
             else
             {
                 gmapsApiKey = args[0];
                 gmapsSigningKey = args[1];
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
SearchData()
async Task Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.SearchData (string searchPano, LatLngPoint searchPoint, IProgress prog) inline private
Definition at line 482 of file AbstractGoogleStreetView.cs.
         {
             prog.Report(0);
             metadata = await gmaps.SearchMetadataAsync(searchLocation, searchPano, searchPoint, searchRadius, prog)
                 .ConfigureAwait(false);
             if (metadata != null)
             {
                 searchPoint = metadata.Location;
                 searchLocation = searchPano = metadata.Pano_ID;
                 if (lastSphere == null)
                 {
                     origin = metadata.Location;
                 }
                 if (gps != null)
                 {
                     gps.FakeCoord = true;
                     gps.Coord = metadata.Location;
                 }
 #if UNITY_EDITOR
                 if (locationInput != null)
                 {
                     locationInput.value = searchLocation;
                 }
 #endif
                 loadingBar.Activate();
                 var curSphere = await GetPhotosphere();
                 if (lastSphere != null)
                 {
                     await JuniperSystem.OnMainThreadAsync(lastSphere.Deactivate);
                 }
                 await JuniperSystem.OnMainThreadAsync(curSphere.Activate);
                 if (lastSphere == null)
                 {
                     await prog.WaitOnAsync(curSphere, "Loading photosphere");
                     Complete();
                 }
                 await JuniperSystem.OnMainThreadAsync(() =>
                 {
                     avatar.transform.position = GetRelativeVector3(metadata);
                     curSphere.transform.position = avatar.Head.position;
                 });
                 prog.Report(1);
                 lastSphere = curSphere;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
SearchPoint()
async Task Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.SearchPoint () inline private
Definition at line 470 of file AbstractGoogleStreetView.cs.
         {
             lastCursorPosition = cursorPosition;
             var point = GetRelativeLatLng(cursorPosition);
             var closestMetadata = await gmaps.FindClosestMetadataAsync(point, searchRadius)
                 .ConfigureAwait(false);
             if (closestMetadata != null)
             {
                 navPointerPano = closestMetadata.Pano_ID;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
SetLocation()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.SetLocation (string location) inline
Definition at line 388 of file AbstractGoogleStreetView.cs.
         {
             searchLocation = location;
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
ShowScene()
void Juniper.SubSceneController.ShowScene (string sceneName) inline inherited
Definition at line 28 of file SubSceneController.cs.
         {
             master.ShowScene(sceneName);
         }
References Juniper.SubSceneController.master, and Juniper.MasterSceneController.ShowScene().
ShowView()
void Juniper.SubSceneController.ShowView (string viewName) inline inherited
Definition at line 33 of file SubSceneController.cs.
         {
             master.ShowView(viewName);
         }
References Juniper.SubSceneController.master, and Juniper.MasterSceneController.ShowView().
SkipEnter()
virtual void Juniper.AbstractStateController.SkipEnter () inline virtual inherited
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 309 of file AbstractStateController.cs.
         {
             if (!IsEntered)
             {
                 skipEvents = true;
                 Enter();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.IsEntered, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.MasterSceneController.Start().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 320 of file AbstractStateController.cs.
         {
             if (!IsExited)
             {
                 skipEvents = true;
                 Exit();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Exit(), Juniper.AbstractStateController.IsExited, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.Widgets.Tooltipable.Hide(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
SwitchToScene()
void Juniper.SubSceneController.SwitchToScene (string sceneName) inline inherited
Definition at line 23 of file SubSceneController.cs.
         {
             master.SwitchToScene(sceneName, !unloadSceneOnExit);
         }
References Juniper.SubSceneController.master, Juniper.MasterSceneController.SwitchToScene(), and Juniper.SubSceneController.unloadSceneOnExit.
Referenced by Juniper.Widgets.MenuCollection.ReturnToMainMenu().
SyncData()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.SyncData (IProgress prog) inline private
Definition at line 449 of file AbstractGoogleStreetView.cs.
         {
             var isNewSearch = ParseSearchParams(searchLocation, out var searchPano, out var searchPoint);
             if (isNewSearch)
             {
                 searchTask = SearchData(searchPano, searchPoint, prog)
                     .ContinueWith(JuniperSystem.LogError, TaskContinuationOptions.OnlyOnFaulted);
             }
             else if (origin != null
                 && metadata != null
                 && input.ActiveController != null)
             {
                 cursorPosition = input.ActiveController.CursorPosition;
                 var cursorDelta = cursorPosition - lastCursorPosition;
                 if (cursorDelta.magnitude > 0.1f)
                 {
                     searchTask = SearchPoint();
                 }
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Enter(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
Update()
void Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.Update () inline
Definition at line 393 of file AbstractGoogleStreetView.cs.
         {
             if (origin != null)
             {
                 foreach (var metadata in gmaps.CachedMetadata)
                 {
                     if (!navPointers.ContainsKey(metadata.Pano_ID))
                     {
                         var position = GetRelativeVector3(metadata);
                         if (position.magnitude < 1000)
{
                             var newPointer = Instantiate(navPointer);
                             newPointer.parent = navPointer.parent;
                             newPointer.position = position;
                             newPointer.name = "jump-to-" + metadata.Pano_ID;
                             newPointer.Activate();
                             navPointers[metadata.Pano_ID] = newPointer;
                         }
                     }
                 }
             }
             if (!string.IsNullOrEmpty(navPointerPano))
             {
                 foreach (var pointer in navPointers)
                 {
                     var renderer = pointer.Value.GetComponentInChildren<MeshRenderer>();
                     var material = renderer.GetMaterial();
                     var color = Color.red;
                     if (pointer.Key == navPointerPano)
                     {
                         color = Color.green;
                     }
                     else if (gmaps.IsImageCached(pointer.Key))
                     {
                         color = Color.blue;
                     }
                     material.SetColor("_Color", color);
                 }
             }
             if (IsEntered && IsComplete)
             {
                 if (!IsBusy)
                 {
                     SyncData(null);
                 }
                 else if (lastSphere != null)
                 {
                     loadingBar.Report(lastSphere.ProgressToComplete);
                 }
             }
         }
Member Data Documentation
_curState
Direction Juniper.AbstractStateController._curState inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 117 of file AbstractStateController.cs.
avatar
Avatar Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.avatar private
Definition at line 68 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData().
cache
CachingStrategy Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.cache private
Definition at line 71 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_CubemapNeeded().
CAPTURE_CUBEMAP_FACES
readonly CubemapFace [] Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.CAPTURE_CUBEMAP_FACES static private
Initial value:
= new[] {
            CubemapFace.NegativeY,
            CubemapFace.NegativeX,
            CubemapFace.PositiveZ,
            CubemapFace.PositiveX,
            CubemapFace.NegativeZ,
            CubemapFace.PositiveY
        }
Definition at line 202 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap().
CAPTURE_CUBEMAP_SUB_IMAGES
readonly Texture2D [] Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.CAPTURE_CUBEMAP_SUB_IMAGES = new Texture2D[CAPTURE_CUBEMAP_FACES.Length] static private
Definition at line 211 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap().
captureTask
Task Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.captureTask private
Definition at line 78 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_Complete().
codec
IImageCodec<Texture2D> Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.codec private
Definition at line 72 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Decode(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_CubemapNeeded(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_ImageNeeded().
cursorPosition
Vector3 Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.cursorPosition private
Definition at line 59 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetRelativeLatLng(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchPoint(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
gmaps
GoogleMapsClient<MetadataTypeT> Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.gmaps private
Definition at line 64 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_ImageNeeded(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchPoint(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
GMAPS_URL_LATLNG_PATTERN
readonly Regex Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.GMAPS_URL_LATLNG_PATTERN static private
Initial value:
=
            new Regex("https?://www\\.google\\.com/maps/@(-?\\d+\\.\\d+,-?\\d+\\.\\d+)", RegexOptions.Compiled)
Definition at line 29 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.ParseSearchParams().
GMAPS_URL_PANO_PATTERN
readonly Regex Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.GMAPS_URL_PANO_PATTERN static private
Initial value:
=
            new Regex("https?://www\\.google\\.com/maps/@-?\\d+\\.\\d+,-?\\d+\\.\\d+(?:,[a-zA-Z0-9.]+)*/data=(?:![a-z0-9]+)*!1s([a-zA-Z0-9_\\-]+)(?:![a-z0-9]+)*", RegexOptions.Compiled)
Definition at line 26 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.ParseSearchParams().
gmapsApiKey
string Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.gmapsApiKey private
Definition at line 36 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.ReceiveCredentials().
gmapsSigningKey
string Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.gmapsSigningKey private
Definition at line 40 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.ReceiveCredentials().
gps
GPSLocation Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.gps private
Definition at line 65 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData().
imageNeededSet
readonly HashSet<string> Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.imageNeededSet = new HashSet<string>() private
Definition at line 540 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetPhotosphere().
input
UnifiedInputModule Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.input private
Definition at line 70 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
lastCursorPosition
Vector3 Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.lastCursorPosition private
Definition at line 60 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchPoint(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
lastSphere
PhotosphereJig Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.lastSphere private
Definition at line 73 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
loadingBar
LoadingBar Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.loadingBar private
Definition at line 76 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_Complete(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
metadata
MetadataTypeT Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.metadata private
Definition at line 63 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetPhotosphere(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetRelativeVector3(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.ParseSearchParams(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
navPlane
Clickable Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.navPlane private
Definition at line 67 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnDisable(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnEnable().
navPointer
Transform Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.navPointer private
Definition at line 69 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
navPointerPano
string Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.navPointerPano private
Definition at line 61 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.NavPlane_Click(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchPoint(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
navPointers
readonly Dictionary<string, Transform> Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.navPointers = new Dictionary<string, Transform>() private
Definition at line 32 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 38 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 29 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 56 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 47 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
onStopped
UnityEvent Juniper.AbstractStateController.onStopped = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 65 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped().
origin
LatLngPoint Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.origin private
Definition at line 58 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetRelativeLatLng(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetRelativeVector3(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
photospheres
PhotosphereManager Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.photospheres private
Definition at line 66 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.GetPhotosphere().
processor
UnityTexture2DProcessor Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.processor private
Definition at line 74 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap().
searchFOVs
float [] Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.searchFOVs
Initial value:
=
        {
            90,
            60,
            30
        }
Definition at line 46 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
searchLocation
string Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.searchLocation
Definition at line 54 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.NavPlane_Click(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.ParseSearchParams(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SetLocation(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
searchRadius
int Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.searchRadius = 50
Definition at line 44 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchPoint().
searchTask
Task Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.searchTask private
Definition at line 75 of file AbstractGoogleStreetView.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
skipEvents
bool Juniper.AbstractStateController.skipEvents protected inherited
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Definition at line 166 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Complete(), Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.AbstractTransitionController.Exit(), Juniper.AbstractStateController.OnEntered(), Juniper.AbstractStateController.OnEntering(), Juniper.AbstractStateController.OnExited(), Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.SkipEnter(), and Juniper.AbstractStateController.SkipExit().
unloadSceneOnExit
bool Juniper.SubSceneController.unloadSceneOnExit = true inherited
Definition at line 15 of file SubSceneController.cs.
Referenced by Juniper.SubSceneController.SwitchToScene().
Property Documentation
CachePrefix
abstract string Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.CachePrefix get protected
Definition at line 42 of file AbstractGoogleStreetView.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
CanEnter
bool Juniper.AbstractStateController.CanEnter get inherited
Definition at line 204 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsEntered && !IsEntering;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
CanExit
bool Juniper.AbstractStateController.CanExit get inherited
Definition at line 196 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsExited && !IsExiting;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
CredentialFile
string Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.CredentialFile get
Definition at line 90 of file AbstractGoogleStreetView.cs.
         {
             get
             {
                 var userProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
                 var keyFile = Path.Combine(userProfile, "Projects", "DevKeys", "google-streetview.txt");
                 return keyFile;
             }
         }
IsBusy
bool Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataTypeT >.IsBusy get
Definition at line 114 of file AbstractGoogleStreetView.cs.
         {
             get
             {
                 return searchTask.IsRunning()
                     || captureTask.IsRunning()
                     || lastSphere != null
                         && lastSphere.IsBusy;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.NavPlane_Click(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get inherited
Returns true when State is Direction.Stopped
Definition at line 172 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Stopped;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntered
bool Juniper.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 226 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Forward;
             }
         }
Referenced by Juniper.AbstractStateController.SkipEnter(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntering
bool Juniper.AbstractStateController.IsEntering get inherited
Definition at line 180 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Forward;
             }
         }
IsExited
bool Juniper.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 237 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Reverse;
             }
         }
Referenced by Juniper.AbstractStateController.SkipExit(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsExiting
bool Juniper.AbstractStateController.IsExiting get inherited
Definition at line 188 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Reverse;
             }
         }
IsRunning
bool Juniper.AbstractStateController.IsRunning get inherited
Returns true when State is not Direction.Stopped
Definition at line 215 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Animation.AbstractTransitionController.Update().
State
Direction Juniper.AbstractStateController.State get private set inherited
Definition at line 120 of file AbstractStateController.cs.
         {
             get
             {
                 return _curState;
             }
             private set
             {
                 lastState = _curState;
                 _curState = value;
                 if (State != lastState)
                 {
                     if (State == Direction.Forward)
                     {
                         OnEntering();
                     }
                     else if (State == Direction.Reverse)
                     {
                         OnExiting();
                     }
                     else
                     {
                         OnStopped();
                         if (lastState == Direction.Forward)
{
                             OnEntered();
                         }
                         else if (lastState == Direction.Reverse)
{
                             OnExited();
                         }
                     }
                 }
             }
         }
Referenced by Juniper.AbstractStateController.Complete(), Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.AbstractStateController.SetState().
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 83 of file AbstractStateController.cs.
Referenced by Juniper.Widgets.MenuView.Awake(), Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 74 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 101 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 92 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExiting().
Stopped
EventHandler Juniper.AbstractStateController.Stopped inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 110 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped(), and Juniper.AbstractStateController.Stopper().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/World/GIS/Google/AbstractGoogleStreetView.cs