Juniper: Juniper.Input.ViveFocusInputModule Class Reference
Juniper.Input.ViveFocusInputModule Class Reference
Public Types
enum Mode {
Mode.None, Mode.Auto = ~None, Mode.Mouse = 1, Mode.Touch = 2,
Mode.Gaze = 4, Mode.Motion = 8, Mode.Hands = 16, Mode.HasFloorPosition = 32,
Mode.Desktop = Mouse, Mode.Touchscreen = Touch | Gaze, Mode.SeatedVR = Mouse | Gaze | Motion, Mode.StandingVR = Gaze | Motion | HasFloorPosition,
Mode.HeadsetAR = Gaze | Motion | Hands | HasFloorPosition
}
Public Member Functions
override void Install (bool reset)
Install, with or without a full reset.
void AddPointer (IPointerDevice pointer)
virtual void Reinstall ()
Reinstall the object with a full reset.
T MakePointer< T > (Transform parent, string path)
virtual void Uninstall ()
Remove platform-specific features from the object.
PointerEventData Clone (int pointerDataID, PointerEventData original)
override void Process ()
Find all the pointers and fire raycaster events for them.
void EnableMouse (bool value, bool savePref)
void EnableGaze (bool value, bool savePref)
void EnableTouch (bool value, bool savePref)
void EnableHands (bool value, bool savePref)
void EnableControllers (bool value, bool savePref)
Public Attributes
readonly List< IPointerDevice > Devices = new List<IPointerDevice>(12)
IPointerDevice PrimaryPointer
Mode mode = Mode.Auto
GameObject pointerPrefab
Set to the clonable object that should be used for the pointer probe.
Toggle enableControllersToggle
Toggle enableMouseToggle
Toggle enableTouchToggle
Toggle enableHandsToggle
Toggle enableGazeToggle
GazePointer gazePointer
Mouse mouse
TouchPoint [] touches
MotionController [] motionControllers
HandTracker [] handTrackers
int ControllerLayer
float canvasOffset = 0.2f
Protected Member Functions
override void Awake ()
Protected Attributes
Avatar stage
Properties
bool AnyPointerDragging [get]
Detailed Description
Definition at line 5 of file ViveFocusInputModule.cs.
Member Enumeration Documentation
Mode
enum Juniper.Input.AbstractUnifiedInputModule.Mode strong inherited
Enumerator
None
Auto
Mouse
Touch
Gaze
Motion
Hands
HasFloorPosition
Desktop
Touchscreen
SeatedVR
StandingVR
HeadsetAR
Definition at line 52 of file UnifiedInputModule.cs.
         {
             None,
             Auto = ~None,
             Mouse = 1,
             Touch = 2,
             Gaze = 4,
             Motion = 8,
             Hands = 16,
             HasFloorPosition = 32,
             Desktop = Mouse,
             Touchscreen = Touch | Gaze,
             SeatedVR = Mouse | Gaze | Motion,
             StandingVR = Gaze | Motion | HasFloorPosition,
             HeadsetAR = Gaze | Motion | Hands | HasFloorPosition
         }
Member Function Documentation
AddPointer()
void Juniper.Input.AbstractUnifiedInputModule.AddPointer (IPointerDevice pointer) inline inherited
Implements Juniper.Input.IInputModule.
Definition at line 137 of file UnifiedInputModule.cs.
         {
             if (pointer != null
                 && !Devices.Contains(pointer)
                 && !newDevices.Contains(pointer))
             {
                 newDevices.Add(pointer);
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.Devices, and Juniper.Input.AbstractUnifiedInputModule.newDevices.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start().
Awake()
override void Juniper.Input.AbstractUnifiedInputModule.Awake () inline protected inherited
Definition at line 155 of file UnifiedInputModule.cs.
         {
             base.Awake();
             Install(false);
             ControllerLayer = Devices
                 .Union(newDevices)
                 .Select(d => (int?)d.Layer)
                 .FirstOrDefault()
                 ?? LayerMask.NameToLayer("Ignore Raycast");
 #if UNITY_MODULES_UI
             SetupDevice(ENABLE_GAZE_KEY, enableGazeToggle, EnableGaze);
             SetupDevice(ENABLE_HANDS_KEY, enableHandsToggle, EnableHands);
             SetupDevice(ENABLE_CONTROLLERS_KEY, enableControllersToggle, EnableControllers);
             SetupDevice(ENABLE_MOUSE_KEY, enableMouseToggle, EnableMouse);
             SetupDevice(ENABLE_TOUCH_KEY, enableTouchToggle, EnableTouch);
 #endif
         }
References Juniper.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Input.AbstractUnifiedInputModule.Devices, Juniper.Input.AbstractUnifiedInputModule.ENABLE_CONTROLLERS_KEY, Juniper.Input.AbstractUnifiedInputModule.ENABLE_GAZE_KEY, Juniper.Input.AbstractUnifiedInputModule.ENABLE_HANDS_KEY, Juniper.Input.AbstractUnifiedInputModule.ENABLE_MOUSE_KEY, Juniper.Input.AbstractUnifiedInputModule.ENABLE_TOUCH_KEY, Juniper.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Input.AbstractUnifiedInputModule.enableControllersToggle, Juniper.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Input.AbstractUnifiedInputModule.enableGazeToggle, Juniper.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Input.AbstractUnifiedInputModule.enableHandsToggle, Juniper.Input.AbstractUnifiedInputModule.EnableMouse(), Juniper.Input.AbstractUnifiedInputModule.enableMouseToggle, Juniper.Input.AbstractUnifiedInputModule.EnableTouch(), Juniper.Input.AbstractUnifiedInputModule.enableTouchToggle, Juniper.Input.AbstractUnifiedInputModule.Install(), Juniper.Input.AbstractUnifiedInputModule.newDevices, and Juniper.Input.AbstractUnifiedInputModule.SetupDevice().
Clone()
PointerEventData Juniper.Input.AbstractUnifiedInputModule.Clone (int pointerDataID, PointerEventData original) inline inherited
Implements Juniper.Input.IInputModule.
Definition at line 342 of file UnifiedInputModule.cs.
         {
             PointerEventData clone;
             GetPointerData(pointerDataID, out clone, true);
             clone.delta = original.delta;
             clone.position = original.position;
             clone.scrollDelta = original.scrollDelta;
             clone.pointerEnter = original.pointerEnter;
             clone.useDragThreshold = original.useDragThreshold;
             clone.pointerCurrentRaycast = original.pointerCurrentRaycast;
             if (original.clickCount == -1)
             {
                 clone.eligibleForClick = false;
                 clone.clickCount = 0;
             }
             return clone;
         }
EnableControllers()
void Juniper.Input.AbstractUnifiedInputModule.EnableControllers (bool value, bool savePref) inline inherited
Implements Juniper.Input.IInputModule.
Definition at line 585 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_CONTROLLERS_KEY, value, motionControllers.LastOrDefault(), savePref, EnableControllers
 #if UNITY_UI_MODULES
                 , enableControllersToggle
 #endif
                 );
         }
References Juniper.Input.AbstractUnifiedInputModule.ENABLE_CONTROLLERS_KEY, Juniper.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Input.AbstractUnifiedInputModule.enableControllersToggle, Juniper.Input.AbstractUnifiedInputModule.EnableDevice(), and Juniper.Input.AbstractUnifiedInputModule.motionControllers.
EnableGaze()
void Juniper.Input.AbstractUnifiedInputModule.EnableGaze (bool value, bool savePref) inline inherited
Implements Juniper.Input.IInputModule.
Definition at line 534 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_GAZE_KEY, value, gazePointer, savePref, gazePointer.SetActive
 #if UNITY_UI_MODULES
                 , enableGazeToggle
 #endif
                 );
         }
References Juniper.Input.AbstractUnifiedInputModule.ENABLE_GAZE_KEY, Juniper.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Input.AbstractUnifiedInputModule.enableGazeToggle, and Juniper.Input.AbstractUnifiedInputModule.gazePointer.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), Juniper.Input.AbstractUnifiedInputModule.Process(), and Juniper.Input.AbstractUnifiedInputModule.Uninstall().
EnableHands()
void Juniper.Input.AbstractUnifiedInputModule.EnableHands (bool value, bool savePref) inline inherited
Implements Juniper.Input.IInputModule.
Definition at line 568 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_HANDS_KEY, value, handTrackers.LastOrDefault(), savePref, EnableHands
 #if UNITY_UI_MODULES
                 , enableHandsToggle
 #endif
                 );
         }
References Juniper.Input.AbstractUnifiedInputModule.ENABLE_HANDS_KEY, Juniper.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Input.AbstractUnifiedInputModule.enableHandsToggle, and Juniper.Input.AbstractUnifiedInputModule.handTrackers.
EnableMouse()
void Juniper.Input.AbstractUnifiedInputModule.EnableMouse (bool value, bool savePref) inline inherited
Implements Juniper.Input.IInputModule.
Definition at line 525 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_MOUSE_KEY, value, mouse, savePref, mouse.SetActive
 #if UNITY_UI_MODULES
                 , enableMouseToggle
 #endif
                 );
         }
References Juniper.Input.AbstractUnifiedInputModule.ENABLE_MOUSE_KEY, Juniper.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Input.AbstractUnifiedInputModule.enableMouseToggle, and Juniper.Input.AbstractUnifiedInputModule.mouse.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), Juniper.Input.AbstractUnifiedInputModule.Process(), and Juniper.Input.AbstractUnifiedInputModule.Uninstall().
EnableTouch()
void Juniper.Input.AbstractUnifiedInputModule.EnableTouch (bool value, bool savePref) inline inherited
Implements Juniper.Input.IInputModule.
Definition at line 551 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_TOUCH_KEY, value, touches[0], savePref, EnableTouches
 #if UNITY_UI_MODULES
                 , enableTouchToggle
 #endif
                 );
         }
References Juniper.Input.AbstractUnifiedInputModule.ENABLE_TOUCH_KEY, Juniper.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Input.AbstractUnifiedInputModule.EnableTouches(), Juniper.Input.AbstractUnifiedInputModule.enableTouchToggle, and Juniper.Input.AbstractUnifiedInputModule.touches.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), Juniper.Input.AbstractUnifiedInputModule.Process(), and Juniper.Input.AbstractUnifiedInputModule.Uninstall().
Install()
override void Juniper.Input.ViveFocusInputModule.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Reimplemented from Juniper.Input.AbstractUnifiedInputModule.
Definition at line 7 of file ViveFocusInputModule.cs.
         {
             base.Install(reset);
             if (!reset && mode == Mode.Auto)
             {
                 mode = Mode.StandingVR;
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.mode.
MakePointer< T >()
T Juniper.Input.AbstractUnifiedInputModule.MakePointer< T > (Transform parent, string path) inline inherited
Implements Juniper.Input.IInputModule.
Type Constraints
T : Component
T : IPointerDevice
Definition at line 256 of file UnifiedInputModule.cs.
                     : Component, IPointerDevice
         {
             var p = parent.Ensure<Transform>(path)
                 .Ensure<T>();
             p.tag = "GameController";
             p.Value.Layer = LayerMask.NameToLayer("Ignore Raycast");
             return p;
         }
Process()
override void Juniper.Input.AbstractUnifiedInputModule.Process () inline inherited
Find all the pointers and fire raycaster events for them.
Implements Juniper.Input.IInputModule.
Definition at line 365 of file UnifiedInputModule.cs.
         {
             Devices.AddRange(newDevices);
             newDevices.Clear();
             var motion = mode.HasFlag(Mode.Motion);
             var hands = mode.HasFlag(Mode.Hands);
             var mouse = mode.HasFlag(Mode.Mouse)
                 && this.mouse.IsConnected;
             var touch = mode.HasFlag(Mode.Touch)
                 && TouchConnected
                 && !motion
                 && !hands;
             var gaze = mode.HasFlag(Mode.Gaze)
                 && !mouse
                 && !TouchConnected
                 && !MotionConnected
                 && !HandsConnected;
             EnableControllers(motion, false);
             EnableHands(hands, false);
             EnableMouse(mouse, false);
             EnableTouch(touch, false);
             EnableGaze(gaze, false);
             foreach (var pointer in Devices)
             {
                 pointer.Layer = ControllerLayer;
                 if (pointer.IsEnabled)
                 {
                     PointerEventData evtData;
                     GetPointerData(pointer.PointerDataID, out evtData, true);
                     evtData.delta = pointer.ScreenDelta;
                     evtData.position = pointer.ScreenPoint;
                     evtData.scrollDelta = pointer.ScrollDelta;
                     evtData.useDragThreshold = eventSystem.pixelDragThreshold > 0;
                     UpdateRay(pointer, evtData);
                     pointer.Process(evtData, eventSystem.pixelDragThreshold * eventSystem.pixelDragThreshold);
                 }
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Input.AbstractUnifiedInputModule.Devices, Juniper.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Input.AbstractUnifiedInputModule.EnableMouse(), Juniper.Input.AbstractUnifiedInputModule.EnableTouch(), Juniper.Input.AbstractUnifiedInputModule.HandsConnected, Juniper.Input.AbstractUnifiedInputModule.mode, Juniper.Input.AbstractUnifiedInputModule.MotionConnected, Juniper.Input.AbstractUnifiedInputModule.mouse, Juniper.Input.AbstractUnifiedInputModule.newDevices, Juniper.Input.AbstractUnifiedInputModule.TouchConnected, and Juniper.Input.AbstractUnifiedInputModule.UpdateRay().
Reinstall()
virtual void Juniper.Input.AbstractUnifiedInputModule.Reinstall () inline virtual inherited
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 212 of file UnifiedInputModule.cs.
         {
             Install(true);
         }
References Juniper.Input.AbstractUnifiedInputModule.Install().
Uninstall()
virtual void Juniper.Input.AbstractUnifiedInputModule.Uninstall () inline virtual inherited
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Input.DaydreamInputModule.
Definition at line 266 of file UnifiedInputModule.cs.
         {
             EnableHands(true, false);
             EnableControllers(true, false);
             EnableGaze(true, false);
             EnableTouch(true, false);
             EnableMouse(true, false);
         }
References Juniper.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Input.AbstractUnifiedInputModule.EnableMouse(), and Juniper.Input.AbstractUnifiedInputModule.EnableTouch().
Member Data Documentation
canvasOffset
float Juniper.Input.AbstractUnifiedInputModule.canvasOffset = 0.2f inherited
Definition at line 448 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.RaycastAll().
ControllerLayer
int Juniper.Input.AbstractUnifiedInputModule.ControllerLayer inherited
Definition at line 153 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), Juniper.Animation.FadeTransition.OnEntered(), Juniper.Animation.FadeTransition.OnExiting(), and Juniper.Input.AbstractUnifiedInputModule.Process().
Devices
readonly List<IPointerDevice> Juniper.Input.AbstractUnifiedInputModule.Devices = new List<IPointerDevice>(12) inherited
Definition at line 70 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.AddPointer(), Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.Process().
enableControllersToggle
Toggle Juniper.Input.AbstractUnifiedInputModule.enableControllersToggle inherited
Definition at line 104 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.EnableControllers().
enableGazeToggle
Toggle Juniper.Input.AbstractUnifiedInputModule.enableGazeToggle inherited
Definition at line 108 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.EnableGaze().
enableHandsToggle
Toggle Juniper.Input.AbstractUnifiedInputModule.enableHandsToggle inherited
Definition at line 107 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.EnableHands().
enableMouseToggle
Toggle Juniper.Input.AbstractUnifiedInputModule.enableMouseToggle inherited
Definition at line 105 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.EnableMouse().
enableTouchToggle
Toggle Juniper.Input.AbstractUnifiedInputModule.enableTouchToggle inherited
Definition at line 106 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.EnableTouch().
gazePointer
GazePointer Juniper.Input.AbstractUnifiedInputModule.gazePointer inherited
Definition at line 131 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.EnableGaze(), and Juniper.Input.AbstractUnifiedInputModule.Install().
handTrackers
HandTracker [] Juniper.Input.AbstractUnifiedInputModule.handTrackers inherited
Definition at line 135 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.EnableHands(), and Juniper.Input.AbstractUnifiedInputModule.Install().
mode
Mode Juniper.Input.AbstractUnifiedInputModule.mode = Mode.Auto inherited
Definition at line 74 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractMobileInputModule.Install(), Juniper.Input.StandaloneInputModule.Install(), Juniper.Input.ViveFocusInputModule.Install(), Juniper.Input.WindowsMRInputModule.Install(), Juniper.Input.DaydreamInputModule.Install(), Juniper.Input.AbstractUnifiedInputModule.Install(), Juniper.Input.AbstractUnifiedInputModule.Process(), and Juniper.Input.WindowsMRInputModule.UpdateModule().
motionControllers
MotionController [] Juniper.Input.AbstractUnifiedInputModule.motionControllers inherited
Definition at line 134 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.EnableControllers(), and Juniper.Input.AbstractUnifiedInputModule.Install().
mouse
Mouse Juniper.Input.AbstractUnifiedInputModule.mouse inherited
Definition at line 132 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.EnableMouse(), Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
pointerPrefab
GameObject Juniper.Input.AbstractUnifiedInputModule.pointerPrefab inherited
Set to the clonable object that should be used for the pointer probe.
Definition at line 95 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install().
PrimaryPointer
IPointerDevice Juniper.Input.AbstractUnifiedInputModule.PrimaryPointer inherited
Definition at line 72 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.EnableDevice(), and Juniper.Input.HoverCraft.Update().
stage
Avatar Juniper.Input.AbstractUnifiedInputModule.stage protected inherited
Definition at line 151 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install().
touches
TouchPoint [] Juniper.Input.AbstractUnifiedInputModule.touches inherited
Definition at line 133 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.EnableTouch(), Juniper.Input.AbstractUnifiedInputModule.EnableTouches(), and Juniper.Input.AbstractUnifiedInputModule.Install().
Property Documentation
AnyPointerDragging
bool Juniper.Input.AbstractUnifiedInputModule.AnyPointerDragging get inherited
Definition at line 77 of file UnifiedInputModule.cs.
         {
             get
             {
                 foreach (var device in Devices)
                 {
                     if (device.IsDragging)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Input.CameraControl.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Platforms/ViveFocus/ViveFocusInputModule.cs