Juniper: Juniper.Units.Seconds Class Reference
Juniper.Units.Seconds Class Reference
Conversions from seconds
Static Public Member Functions
static float Milliseconds (float seconds)
Convert from seconds to milliseconds.
static float Minutes (float seconds)
Convert from seconds to minutes.
static float Hours (float seconds)
Convert from seconds to hours.
static float Days (float seconds)
Convert from seconds to days.
static float Hertz (float seconds)
Convert from seconds to hertz.
Public Attributes
const float PER_MILLISECOND = 1 / Units.Milliseconds.PER_SECOND
Conversion factor from milliseconds to seconds.
const float PER_MINUTE = 60
Conversion factor from mminutes to seconds.
const float PER_HOUR = PER_MINUTE * Units.Minutes.PER_HOUR
Conversion factor from hours to seconds.
const float PER_DAY = PER_HOUR * Units.Hours.PER_DAY
Conversion factor from days to seconds.
Detailed Description
Conversions from seconds
Definition at line 8 of file Seconds.cs.
Member Function Documentation
Days()
static float Juniper.Units.Seconds.Days (float seconds) inline static
Convert from seconds to days.
Parameters
seconds The number of seconds
Returns
the number of days
Definition at line 65 of file Seconds.cs.
             {
                 return seconds * Units.Days.PER_SECOND;
             }
References Juniper.Units.Days.PER_SECOND.
Hertz()
static float Juniper.Units.Seconds.Hertz (float seconds) inline static
Convert from seconds to hertz.
Parameters
seconds The number of seconds
Returns
the number of hertz
Definition at line 75 of file Seconds.cs.
             {
                 return 1 / seconds;
             }
Referenced by Juniper.Units.Days.Hertz(), Juniper.Units.Minutes.Hertz(), Juniper.Units.Milliseconds.Hertz(), and Juniper.Units.Hours.Hertz().
Hours()
static float Juniper.Units.Seconds.Hours (float seconds) inline static
Convert from seconds to hours.
Parameters
seconds The number of seconds
Returns
the number of hours
Definition at line 55 of file Seconds.cs.
             {
                 return seconds * Units.Hours.PER_SECOND;
             }
References Juniper.Units.Hours.PER_SECOND.
Milliseconds()
static float Juniper.Units.Seconds.Milliseconds (float seconds) inline static
Convert from seconds to milliseconds.
Parameters
seconds The number of seconds
Returns
the number of milliseconds
Definition at line 35 of file Seconds.cs.
             {
                 return seconds * Units.Milliseconds.PER_SECOND;
             }
References Juniper.Units.Milliseconds.PER_SECOND.
Minutes()
static float Juniper.Units.Seconds.Minutes (float seconds) inline static
Convert from seconds to minutes.
Parameters
seconds The number of seconds
Returns
the number of minutes
Definition at line 45 of file Seconds.cs.
             {
                 return seconds * Units.Minutes.PER_SECOND;
             }
References Juniper.Units.Minutes.PER_SECOND.
Member Data Documentation
PER_DAY
const float Juniper.Units.Seconds.PER_DAY = PER_HOUR * Units.Hours.PER_DAY
Conversion factor from days to seconds.
Definition at line 28 of file Seconds.cs.
Referenced by Juniper.Units.Days.Seconds().
PER_HOUR
const float Juniper.Units.Seconds.PER_HOUR = PER_MINUTE * Units.Minutes.PER_HOUR
Conversion factor from hours to seconds.
Definition at line 23 of file Seconds.cs.
Referenced by Juniper.Units.Hours.Seconds().
PER_MILLISECOND
const float Juniper.Units.Seconds.PER_MILLISECOND = 1 / Units.Milliseconds.PER_SECOND
Conversion factor from milliseconds to seconds.
Definition at line 13 of file Seconds.cs.
Referenced by Juniper.Units.Milliseconds.Seconds().
PER_MINUTE
const float Juniper.Units.Seconds.PER_MINUTE = 60
Conversion factor from mminutes to seconds.
Definition at line 18 of file Seconds.cs.
Referenced by Juniper.Units.Minutes.Seconds().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Units/src/Time/Seconds.cs