Juniper: Juniper.Puzzles.TetrisGame Class Reference
Juniper.Puzzles.TetrisGame Class Reference
Public Member Functions
TetrisGame (int width, int height)
TetrisGame (int[,] grid)
void Reset ()
void Update (TimeSpan sinceLastDraw)
void SetLeft (bool value)
void SetRight (bool value)
void SetFlip (bool value)
void SetDrop (bool value)
void TetrisClearRow (int row)
override string ToString ()
void Clear ()
Clear the entire board
void Clear (int x, int y)
Clear a single point on the puzzle grid
void Clear (bool order, int ordinal)
Clear a row or a column on the puzzle grid
void Clear (int left, int top, int width, int height)
Clear a rectangular block on the puzzle grid
void Clear (int[,] mask)
Batch clear specific points on the grid
void Clear (int left, int top, int[,] shape)
Clear an irregularly shaped area of the board
void Clear (int left, int top, Puzzle shape)
void Fill (int value)
Fill the entire puzzle grid with a single value
void Fill (bool order, int ordinal, int value)
Fill a row or column with a single value
void Fill (int left, int top, int width, int height, int value)
Fill a rectangular portion of the board
void Fill (Random prand)
Use a pseudorandom number generator to fill the entire board
void Fill ()
Use a pseudorandom number generator to fill the entire board
void Fill (int left, int top, Puzzle piece)
Copy a puzzle piece on top of the current puzzle at a specific location.
void Fill (int left, int top, int[,] shape)
Fill a specific area with a shape. Ignores empty tiles in the shape.
void ShiftColumnsDown ()
Make tiles above empty spots shift down into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
void ShiftColumnsUp ()
Make tiles below empty spots shift up into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
void ShiftColumnsLeft ()
Make tiles to the right empty spots shift left into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
void ShiftColumnsRight ()
Make tiles to the left empty spots shift right into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
bool IsInBounds (int x, int y)
Determine if a point is within the bounds of the board
bool IsInBounds (int x, int y, int width, int height)
Determine if a rectangle is completely contained within the board
bool IsInBounds (int x, int y, int[,] shape)
Determine if a shape is completely contained within the board
bool IsInBounds (int x, int y, Puzzle shape)
Determine if a puzzle piece is completely contained within the board
int CompareTo (Puzzle p)
Compares two puzzles to see if they match.
override bool Equals (object obj)
Compare two puzzles to see if they match element-for-element
override int GetHashCode ()
A recommended override if one overrides the Equals method
void Swap (int x1, int y1, int x2, int y2)
Swap two specific points on the puzzle
void Swap (bool order, int ordinal1, int ordinal2)
Swap two rows or two columns
void Swap (int x1, int y1, int x2, int y2, int width, int height)
Swap two rectangular areas that have the same dimensions but do not overlap
Puzzle Rotate (bool direction)
Rotate the puzzle by 90 degrees in either a clockwise or counterclockwise direction
Puzzle Duplicate ()
Creates a copy of the current puzzle
bool IsFull ()
Check to see if the board is full
bool IsFull (bool order, int ordinal)
Check to see if a row or column is full
bool IsFull (int x, int y, int width, int height)
Check to see if a rectangular area is full
bool IsFull (int x, int y, int[,] shape)
Check to see if a mask shape is full
bool IsFull (int x, int y, Puzzle shape)
Check to see if a puzzle piece shape is full
bool IsEmpty ()
bool IsEmpty (bool order, int ordinal)
bool IsEmpty (int x, int y, int width, int height)
bool IsEmpty (int x, int y, int[,] shape)
bool IsEmpty (int x, int y, Puzzle shape)
Static Public Member Functions
static bool RectsIntersect (int x1, int y1, int x2, int y2, int width, int height)
Check if two rectangles, of the same size in different locations, overlap each other.
static bool operator== (Puzzle left, Puzzle right)
static bool operator != (Puzzle left, Puzzle right)
static bool operator< (Puzzle left, Puzzle right)
static bool operator<= (Puzzle left, Puzzle right)
static bool operator > (Puzzle left, Puzzle right)
static bool operator >= (Puzzle left, Puzzle right)
Public Attributes
int Width => grid.GetWidth()
Gets the width of the puzzle grid
int Height => grid.GetHeight()
Gets the height of the puzzle grid
Static Public Attributes
static readonly int EmptyTile = -1
static readonly bool RowOrder = true
static readonly bool ColumnOrder = !RowOrder
static readonly bool Clockwise = true
static readonly bool CounterClockwise = !Clockwise
Properties
Puzzle Next [get, private set]
Puzzle Current [get, private set]
int CursorX [get, private set]
int CursorY [get, private set]
int Score [get, private set]
bool GameOver [get, private set]
int this[int x, int y] [get, set]
Gets or sets a specific value on the puzzle grid
int [,] Grid [get, set]
Gets or sets the raw puzzle grid array
Events
EventHandler Thump
EventHandler< IntegerEventArgs > LineClear
EventHandler Flip
Private Member Functions
void UpdateSpeed (double deltaLinesPerSecond)
void MoveLeft ()
void MoveRight ()
void PlayThump ()
void PlayLineClear (int numLines)
void PlayFlip ()
Static Private Member Functions
static int [,] MakeEmptyGrid (int width, int height)
Private Attributes
bool isLeftDown
bool isRightDown
bool isFlipDown
bool isDropDown
double advanceRate
double moveRate
double flipRate
double millisPerAdvance
double millisPerMove
double millisPerFlip
double millisPerDrop
double sinceLastMove
double sinceLastAdvance
double sinceLastFlip
double sinceLastDrop
double sincePieceEntered
Static Private Attributes
static readonly Puzzle [] pieces
static readonly Random rand = new Random()
Detailed Description
Definition at line 5 of file TetrisGame.cs.
Constructor & Destructor Documentation
TetrisGame() [1/2]
Juniper.Puzzles.TetrisGame.TetrisGame (int width, int height) inline
Definition at line 69 of file TetrisGame.cs.
             : this(MakeEmptyGrid(width, height))
         { }
TetrisGame() [2/2]
Juniper.Puzzles.TetrisGame.TetrisGame (int grid[,]) inline
Definition at line 73 of file TetrisGame.cs.
             : base(grid)
         {
             Reset();
         }
References Juniper.Puzzles.TetrisGame.Reset().
Member Function Documentation
Clear() [1/7]
void Juniper.Puzzles.Puzzle.Clear () inline inherited
Clear the entire board
Definition at line 127 of file Puzzle.cs.
         {
             Clear(0, 0, Width, Height);
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.Clear().
Clear() [2/7]
void Juniper.Puzzles.Puzzle.Clear (int x, int y) inline inherited
Clear a single point on the puzzle grid
Parameters
x
y
Definition at line 137 of file Puzzle.cs.
         {
             Clear(x, y, 1, 1);
         }
References Juniper.Puzzles.Puzzle.Clear().
Clear() [3/7]
void Juniper.Puzzles.Puzzle.Clear (bool order, int ordinal) inline inherited
Clear a row or a column on the puzzle grid
Parameters
order Puzzle.RowOrder to clear a row, Puzzle.ColumnOrder to clear a column
ordinal the row or column index to clear
Definition at line 147 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 Clear(0, ordinal, Width, 1);
             }
             else
             {
                 Clear(ordinal, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
Clear() [4/7]
void Juniper.Puzzles.Puzzle.Clear (int left, int top, int width, int height) inline inherited
Clear a rectangular block on the puzzle grid
Parameters
left
top
width
height
Definition at line 166 of file Puzzle.cs.
         {
             Fill(left, top, width, height, EmptyTile);
         }
References Juniper.Puzzles.Puzzle.EmptyTile, and Juniper.Puzzles.Puzzle.Fill().
Clear() [5/7]
void Juniper.Puzzles.Puzzle.Clear (int mask[,]) inline inherited
Batch clear specific points on the grid
Parameters
mask a 2D array of flags marking points that should be cleared. The array should be as large as the puzzle grid
Definition at line 176 of file Puzzle.cs.
         {
             if (mask != null
                 && mask.GetWidth() == Width
                 && mask.GetHeight() == Height)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (mask[x, y] != EmptyTile)
{
                             grid[x, y] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Clear() [6/7]
void Juniper.Puzzles.Puzzle.Clear (int left, int top, int shape[,]) inline inherited
Clear an irregularly shaped area of the board
Parameters
left
top
shape a 2D array of flags marking points that should be cleared.
Definition at line 201 of file Puzzle.cs.
         {
             if (shape != null)
             {
                 for (var x = left; x < shape.GetWidth() + left; ++x)
                 {
                     if (x >= 0 && x < Width)
                     {
                         for (var y = top; y < shape.GetHeight() + top; ++y)
{
                             if (y >= 0 && y < Height && shape[x - left, y - top] != EmptyTile)
{
                                 grid[x, y] = EmptyTile;
                             }
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Clear() [7/7]
void Juniper.Puzzles.Puzzle.Clear (int left, int top, Puzzle shape) inline inherited
Definition at line 221 of file Puzzle.cs.
         {
             if (shape != null)
             {
                 Clear(left, top, shape.grid);
             }
         }
References Juniper.Puzzles.Puzzle.Clear(), and Juniper.Puzzles.Puzzle.grid.
CompareTo()
int Juniper.Puzzles.Puzzle.CompareTo (Puzzle p) inline inherited
Compares two puzzles to see if they match.
Parameters
p
Returns
+1 if the dimensions do not match -1 if at least one of the points do not match 0 if the puzzles are equivalent
Definition at line 509 of file Puzzle.cs.
         {
             if (p is null)
             {
                 throw new ArgumentNullException(nameof(p));
             }
             if (Width == p.Width && Height == p.Height)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (this[x, y] != p[x, y])
{
                             return -1;
                         }
                     }
                 }
                 return 0;
             }
             return +1;
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.Equals().
Duplicate()
Puzzle Juniper.Puzzles.Puzzle.Duplicate () inline inherited
Creates a copy of the current puzzle
Returns
Definition at line 670 of file Puzzle.cs.
         {
             return new Puzzle(grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.Puzzle().
Equals()
override bool Juniper.Puzzles.Puzzle.Equals (object obj) inline inherited
Compare two puzzles to see if they match element-for-element
Parameters
obj
Returns
Definition at line 539 of file Puzzle.cs.
         {
             if (obj is Puzzle)
             {
                 return CompareTo(obj as Puzzle) == 0;
             }
             return false;
         }
References Juniper.Puzzles.Puzzle.CompareTo().
Fill() [1/7]
void Juniper.Puzzles.Puzzle.Fill (int value) inline inherited
Fill the entire puzzle grid with a single value
Parameters
value
Definition at line 233 of file Puzzle.cs.
         {
             Fill(0, 0, Width, Height, value);
         }
References Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Fill() [2/7]
void Juniper.Puzzles.Puzzle.Fill (bool order, int ordinal, int value) inline inherited
Fill a row or column with a single value
Parameters
order Puzzle.RowOrder to fill a row, Puzzle.ColumnOrder to fill a column
ordinal the row or column index to fill
value
Definition at line 244 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 Fill(0, ordinal, Width, 1, value);
             }
             else
             {
                 Fill(ordinal, 0, 1, Height, value);
             }
         }
References Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
Fill() [3/7]
void Juniper.Puzzles.Puzzle.Fill (int left, int top, int width, int height, int value) inline inherited
Fill a rectangular portion of the board
Parameters
left
top
width
height
value
Definition at line 264 of file Puzzle.cs.
         {
             for (var x = left; x < left + width && x < Width; ++x)
             {
                 if (x >= 0)
                 {
                     for (var y = top; y < top + height && y < Height; ++y)
                     {
                         if (y >= 0)
{
                             grid[x, y] = value;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Fill() [4/7]
void Juniper.Puzzles.Puzzle.Fill (Random prand) inline inherited
Use a pseudorandom number generator to fill the entire board
Parameters
prand
Definition at line 285 of file Puzzle.cs.
         {
             if (prand != null)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         grid[x, y] = prand.Next();
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Fill() [5/7]
void Juniper.Puzzles.Puzzle.Fill () inline inherited
Use a pseudorandom number generator to fill the entire board
Definition at line 302 of file Puzzle.cs.
         {
             Fill(new Random());
         }
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.Fill(), and Juniper.Puzzles.TetrisGame.Update().
Fill() [6/7]
void Juniper.Puzzles.Puzzle.Fill (int left, int top, Puzzle piece) inline inherited
Copy a puzzle piece on top of the current puzzle at a specific location.
Parameters
left
top
piece
Definition at line 313 of file Puzzle.cs.
         {
             if (piece != null)
             {
                 Fill(left, top, piece.grid);
             }
         }
References Juniper.Puzzles.Puzzle.Fill(), and Juniper.Puzzles.Puzzle.grid.
Fill() [7/7]
void Juniper.Puzzles.Puzzle.Fill (int left, int top, int shape[,]) inline inherited
Fill a specific area with a shape. Ignores empty tiles in the shape.
Parameters
left
top
shape
Definition at line 327 of file Puzzle.cs.
         {
             if (shape != null)
             {
                 for (var x = left; x < left + shape.GetWidth() && x < Width; ++x)
                 {
                     if (x >= 0)
                     {
                         for (var y = top; y < top + shape.GetHeight() && y < Height; ++y)
{
                             if (y >= 0 && shape[x - left, y - top] != EmptyTile)
{
                                 grid[x, y] = shape[x - left, y - top];
                             }
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
GetHashCode()
override int Juniper.Puzzles.Puzzle.GetHashCode () inline inherited
A recommended override if one overrides the Equals method
Returns
Definition at line 553 of file Puzzle.cs.
         {
             return grid.GetHashCode();
         }
References Juniper.Puzzles.Puzzle.grid.
IsEmpty() [1/5]
bool Juniper.Puzzles.Puzzle.IsEmpty () inline inherited
Definition at line 766 of file Puzzle.cs.
         {
             return IsEmpty(0, 0, Width, Height);
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), and Juniper.Puzzles.TetrisGame.Update().
IsEmpty() [2/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (bool order, int ordinal) inline inherited
Definition at line 771 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 return IsEmpty(0, ordinal, Width, 1);
             }
             else
             {
                 return IsEmpty(ordinal, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
IsEmpty() [3/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (int x, int y, int width, int height) inline inherited
Definition at line 783 of file Puzzle.cs.
         {
             for (var dx = 0; dx < width; ++dx)
             {
                 for (var dy = 0; dy < height; ++dy)
                 {
                     if (this[x + dx, y + dy] != EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsEmpty() [4/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (int x, int y, int shape[,]) inline inherited
Definition at line 799 of file Puzzle.cs.
         {
             if (shape == null || shape.Length == 0)
             {
                 return false;
             }
             for (var dx = 0; dx < shape.GetWidth(); ++dx)
             {
                 for (var dy = 0; dy < shape.GetHeight(); ++dy)
                 {
                     if (shape[dx, dy] != EmptyTile && this[x + dx, y + dy] != EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsEmpty() [5/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (int x, int y, Puzzle shape) inline inherited
Definition at line 820 of file Puzzle.cs.
         {
             return shape != null && IsEmpty(x, y, shape.grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.IsEmpty().
IsFull() [1/5]
bool Juniper.Puzzles.Puzzle.IsFull () inline inherited
Check to see if the board is full
Returns
Definition at line 679 of file Puzzle.cs.
         {
             return IsFull(0, 0, Width, Height);
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.IsFull(), and Juniper.Puzzles.TetrisGame.Update().
IsFull() [2/5]
bool Juniper.Puzzles.Puzzle.IsFull (bool order, int ordinal) inline inherited
Check to see if a row or column is full
Parameters
order
ordinal
Returns
Definition at line 690 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 return IsFull(0, ordinal, Width, 1);
             }
             else
             {
                 return IsFull(ordinal, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
IsFull() [3/5]
bool Juniper.Puzzles.Puzzle.IsFull (int x, int y, int width, int height) inline inherited
Check to see if a rectangular area is full
Parameters
x
y
width
height
Returns
Definition at line 710 of file Puzzle.cs.
         {
             for (var dx = 0; dx < width; ++dx)
             {
                 for (var dy = 0; dy < height; ++dy)
                 {
                     if (this[x + dx, y + dy] == EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsFull() [4/5]
bool Juniper.Puzzles.Puzzle.IsFull (int x, int y, int shape[,]) inline inherited
Check to see if a mask shape is full
Parameters
x
y
shape
Returns
Definition at line 733 of file Puzzle.cs.
         {
             if (shape == null || shape.Length == 0)
             {
                 return false;
             }
             for (var dx = 0; dx < shape.GetWidth(); ++dx)
             {
                 for (var dy = 0; dy < shape.GetHeight(); ++dy)
                 {
                     if (shape[dx, dy] != EmptyTile && this[x + dx, y + dy] == EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsFull() [5/5]
bool Juniper.Puzzles.Puzzle.IsFull (int x, int y, Puzzle shape) inline inherited
Check to see if a puzzle piece shape is full
Parameters
x
y
shape
Returns
Definition at line 761 of file Puzzle.cs.
         {
             return shape != null && IsFull(x, y, shape.grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.IsFull().
IsInBounds() [1/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y) inline inherited
Determine if a point is within the bounds of the board
Parameters
x
y
Returns
Definition at line 442 of file Puzzle.cs.
         {
             return x >= 0 && x < Width
                 && y >= 0 && y < Height;
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), Juniper.Puzzles.Puzzle.Swap(), Juniper.Puzzles.TetrisGame.TetrisClearRow(), and Juniper.Puzzles.TetrisGame.Update().
IsInBounds() [2/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y, int width, int height) inline inherited
Determine if a rectangle is completely contained within the board
Parameters
x
y
width
height
Returns
Definition at line 456 of file Puzzle.cs.
         {
             return IsInBounds(x, y) && IsInBounds(x + width - 1, y + height - 1);
         }
References Juniper.Puzzles.Puzzle.IsInBounds().
IsInBounds() [3/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y, int shape[,]) inline inherited
Determine if a shape is completely contained within the board
Parameters
x
y
shape
Returns
Definition at line 468 of file Puzzle.cs.
         {
             if (shape != null && shape.Length > 0)
             {
                 for (var dx = 0; dx < shape.GetWidth(); ++dx)
                 {
                     for (var dy = 0; dy < shape.GetHeight(); ++dy)
                     {
{
                             if (shape[dx, dy] != EmptyTile && !IsInBounds(x + dx, y + dy))
{
                                 return false;
                             }
                         }
                     }
                 }
                 return true;
             }
             return false;
         }
References Juniper.Puzzles.Puzzle.EmptyTile, and Juniper.Puzzles.Puzzle.IsInBounds().
IsInBounds() [4/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y, Puzzle shape) inline inherited
Determine if a puzzle piece is completely contained within the board
Parameters
x
y
shape
Returns
Definition at line 497 of file Puzzle.cs.
         {
             return shape != null && IsInBounds(x, y, shape.grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.IsInBounds().
MakeEmptyGrid()
static int [,] Juniper.Puzzles.TetrisGame.MakeEmptyGrid (int width, int height) inline static private
Definition at line 55 of file TetrisGame.cs.
         {
             var grid = new int[width, height];
             for (var x = 0; x < width; ++x)
             {
                 for (var y = 0; y < height; ++y)
                 {
                     grid[x, y] = -1;
                 }
             }
             return grid;
         }
References Juniper.Puzzles.Puzzle.grid.
MoveLeft()
void Juniper.Puzzles.TetrisGame.MoveLeft () inline private
Definition at line 106 of file TetrisGame.cs.
         {
             if (IsInBounds(CursorX - 1, CursorY, Current)
                         && IsEmpty(CursorX - 1, CursorY, Current))
             {
                 CursorX--;
             }
         }
References Juniper.Puzzles.TetrisGame.Current, Juniper.Puzzles.TetrisGame.CursorX, Juniper.Puzzles.TetrisGame.CursorY, Juniper.Puzzles.Puzzle.IsEmpty(), and Juniper.Puzzles.Puzzle.IsInBounds().
Referenced by Juniper.Puzzles.TetrisGame.Update().
MoveRight()
void Juniper.Puzzles.TetrisGame.MoveRight () inline private
Definition at line 115 of file TetrisGame.cs.
         {
             if (IsInBounds(CursorX + 1, CursorY, Current)
                         && IsEmpty(CursorX + 1, CursorY, Current))
             {
                 CursorX++;
             }
         }
References Juniper.Puzzles.TetrisGame.Current, Juniper.Puzzles.TetrisGame.CursorX, Juniper.Puzzles.TetrisGame.CursorY, Juniper.Puzzles.Puzzle.IsEmpty(), and Juniper.Puzzles.Puzzle.IsInBounds().
Referenced by Juniper.Puzzles.TetrisGame.Update().
operator !=()
static bool Juniper.Puzzles.Puzzle.operator != (Puzzle left, Puzzle right) inline static inherited
Definition at line 831 of file Puzzle.cs.
         {
             return !(left == right);
         }
operator >()
static bool Juniper.Puzzles.Puzzle.operator > (Puzzle left, Puzzle right) inline static inherited
Definition at line 847 of file Puzzle.cs.
         {
             return left is object && left.CompareTo(right) > 0;
         }
operator >=()
static bool Juniper.Puzzles.Puzzle.operator >= (Puzzle left, Puzzle right) inline static inherited
Definition at line 852 of file Puzzle.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.CompareTo(right) >= 0);
         }
operator<()
static bool Juniper.Puzzles.Puzzle.operator< (Puzzle left, Puzzle right) inline static inherited
Definition at line 836 of file Puzzle.cs.
         {
             return (left is null && right is object)
                 || (left is object  && left.CompareTo(right) < 0);
         }
operator<=()
static bool Juniper.Puzzles.Puzzle.operator<= (Puzzle left, Puzzle right) inline static inherited
Definition at line 842 of file Puzzle.cs.
         {
             return left is null || left.CompareTo(right) <= 0;
         }
operator==()
static bool Juniper.Puzzles.Puzzle.operator== (Puzzle left, Puzzle right) inline static inherited
Definition at line 825 of file Puzzle.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
PlayFlip()
void Juniper.Puzzles.TetrisGame.PlayFlip () inline private
Definition at line 287 of file TetrisGame.cs.
         {
             Flip?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Puzzles.TetrisGame.Flip.
Referenced by Juniper.Puzzles.TetrisGame.Update().
PlayLineClear()
void Juniper.Puzzles.TetrisGame.PlayLineClear (int numLines) inline private
Definition at line 282 of file TetrisGame.cs.
         {
             LineClear?.Invoke(this, new IntegerEventArgs(numLines));
         }
References Juniper.Puzzles.TetrisGame.LineClear.
Referenced by Juniper.Puzzles.TetrisGame.Update().
PlayThump()
void Juniper.Puzzles.TetrisGame.PlayThump () inline private
Definition at line 277 of file TetrisGame.cs.
         {
             Thump?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Puzzles.TetrisGame.Thump.
Referenced by Juniper.Puzzles.TetrisGame.Update().
RectsIntersect()
static bool Juniper.Puzzles.Puzzle.RectsIntersect (int x1, int y1, int x2, int y2, int width, int height) inline static inherited
Check if two rectangles, of the same size in different locations, overlap each other.
Parameters
x1
y1
x2
y2
width
height
Returns
Definition at line 625 of file Puzzle.cs.
         {
             System.Drawing.Rectangle a, b;
             a = new System.Drawing.Rectangle(x1, y1, width, height);
             b = new System.Drawing.Rectangle(x2, y2, width, height);
             return a.IntersectsWith(b);
         }
Referenced by Juniper.Puzzles.Puzzle.Swap().
Reset()
void Juniper.Puzzles.TetrisGame.Reset () inline
Definition at line 79 of file TetrisGame.cs.
         {
             advanceRate = 3;
             flipRate = 8;
             moveRate = 10;
             millisPerFlip = 1000 / flipRate;
             millisPerMove = 1000 / moveRate;
             UpdateSpeed(0);
             Current = pieces[rand.Next(pieces.Length)];
             Next = pieces[rand.Next(pieces.Length)];
             CursorX = Width / 2;
             CursorY = 0;
             Score = 0;
             GameOver = false;
             sinceLastMove = sinceLastAdvance = sinceLastFlip = sinceLastDrop = sincePieceEntered = 0.0;
         }
References Juniper.Puzzles.TetrisGame.advanceRate, Juniper.Puzzles.TetrisGame.Current, Juniper.Puzzles.TetrisGame.CursorX, Juniper.Puzzles.TetrisGame.CursorY, Juniper.Puzzles.TetrisGame.flipRate, Juniper.Puzzles.TetrisGame.GameOver, Juniper.Puzzles.TetrisGame.millisPerFlip, Juniper.Puzzles.TetrisGame.millisPerMove, Juniper.Puzzles.TetrisGame.moveRate, Juniper.Puzzles.TetrisGame.Next, Juniper.Puzzles.TetrisGame.pieces, Juniper.Puzzles.TetrisGame.rand, Juniper.Puzzles.TetrisGame.Score, Juniper.Puzzles.TetrisGame.sinceLastAdvance, Juniper.Puzzles.TetrisGame.sinceLastDrop, Juniper.Puzzles.TetrisGame.sinceLastFlip, Juniper.Puzzles.TetrisGame.sinceLastMove, Juniper.Puzzles.TetrisGame.sincePieceEntered, Juniper.Puzzles.TetrisGame.UpdateSpeed(), and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.TetrisGame.TetrisGame().
Rotate()
Puzzle Juniper.Puzzles.Puzzle.Rotate (bool direction) inline inherited
Rotate the puzzle by 90 degrees in either a clockwise or counterclockwise direction
Parameters
direction
Returns
A new puzzle that represents the rotated puzzle
Definition at line 638 of file Puzzle.cs.
         {
             var q = new Puzzle(Height, Width);
             if (direction == Clockwise)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         q[q.Width - y - 1, x] = this[x, y];
                     }
                 }
             }
             else
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         q[y, q.Height - x - 1] = this[x, y];
                     }
                 }
             }
             return q;
         }
References Juniper.Puzzles.Puzzle.Clockwise, Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.Puzzle(), and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.TetrisGame.Update().
SetDrop()
void Juniper.Puzzles.TetrisGame.SetDrop (bool value) inline
Definition at line 254 of file TetrisGame.cs.
         {
             isDropDown = value;
         }
References Juniper.Puzzles.TetrisGame.isDropDown.
SetFlip()
void Juniper.Puzzles.TetrisGame.SetFlip (bool value) inline
Definition at line 249 of file TetrisGame.cs.
         {
             isFlipDown = value;
         }
References Juniper.Puzzles.TetrisGame.isFlipDown.
SetLeft()
void Juniper.Puzzles.TetrisGame.SetLeft (bool value) inline
Definition at line 239 of file TetrisGame.cs.
         {
             isLeftDown = value;
         }
References Juniper.Puzzles.TetrisGame.isLeftDown.
SetRight()
void Juniper.Puzzles.TetrisGame.SetRight (bool value) inline
Definition at line 244 of file TetrisGame.cs.
         {
             isRightDown = value;
         }
References Juniper.Puzzles.TetrisGame.isRightDown.
ShiftColumnsDown()
void Juniper.Puzzles.Puzzle.ShiftColumnsDown () inline inherited
Make tiles above empty spots shift down into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 351 of file Puzzle.cs.
         {
             for (var x = 0; x < Width; ++x)
             {
                 for (var y = Height - 1; y > 0; --y)
                 {
                     for (var y2 = y - 1; y2 >= 0; --y2)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x, y];
                             grid[x, y2] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
ShiftColumnsLeft()
void Juniper.Puzzles.Puzzle.ShiftColumnsLeft () inline inherited
Make tiles to the right empty spots shift left into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 396 of file Puzzle.cs.
         {
             for (var x = 0; x < Width - 1; ++x)
             {
                 for (var x2 = x + 1; x2 < Width; ++x2)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x2, y];
                             grid[x2, y] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
ShiftColumnsRight()
void Juniper.Puzzles.Puzzle.ShiftColumnsRight () inline inherited
Make tiles to the left empty spots shift right into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 418 of file Puzzle.cs.
         {
             for (var x = Width - 1; x > 0; --x)
             {
                 for (var x2 = x - 1; x2 >= 0; --x2)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x2, y];
                             grid[x2, y] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
ShiftColumnsUp()
void Juniper.Puzzles.Puzzle.ShiftColumnsUp () inline inherited
Make tiles below empty spots shift up into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 374 of file Puzzle.cs.
         {
             for (var x = 0; x < Width; ++x)
             {
                 for (var y = 0; y < Height - 1; ++y)
                 {
                     for (var y2 = y + 1; y2 < Height; ++y2)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x, y2];
                             grid[x, y2] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Swap() [1/3]
void Juniper.Puzzles.Puzzle.Swap (int x1, int y1, int x2, int y2) inline inherited
Swap two specific points on the puzzle
Parameters
x1
y1
x2
y2
Definition at line 565 of file Puzzle.cs.
         {
             Swap(x1, y1, x2, y2, 1, 1);
         }
Referenced by Juniper.Puzzles.Puzzle.Swap().
Swap() [2/3]
void Juniper.Puzzles.Puzzle.Swap (bool order, int ordinal1, int ordinal2) inline inherited
Swap two rows or two columns
Parameters
order
ordinal1
ordinal2
Definition at line 576 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 Swap(0, ordinal1, 0, ordinal2, Width, 1);
             }
             else
             {
                 Swap(ordinal1, 0, ordinal2, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.RowOrder, Juniper.Puzzles.Puzzle.Swap(), and Juniper.Puzzles.Puzzle.Width.
Swap() [3/3]
void Juniper.Puzzles.Puzzle.Swap (int x1, int y1, int x2, int y2, int width, int height) inline inherited
Swap two rectangular areas that have the same dimensions but do not overlap
Parameters
x1
y1
x2
y2
width
height
Definition at line 597 of file Puzzle.cs.
         {
             int temp;
             if (IsInBounds(x1, y1, width, height) && IsInBounds(x2, y2, width, height)
                 && !RectsIntersect(x1, y1, x2, y2, width, height))
             {
                 for (var x = 0; x < width; ++x)
                 {
                     for (var y = 0; y < height; ++y)
                     {
                         temp = grid[x1 + x, y1 + y];
                         grid[x1 + x, y1 + y] = grid[x2 + x, y2 + y];
                         grid[x2 + x, y2 + y] = temp;
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.IsInBounds(), and Juniper.Puzzles.Puzzle.RectsIntersect().
TetrisClearRow()
void Juniper.Puzzles.TetrisGame.TetrisClearRow (int row) inline
Definition at line 259 of file TetrisGame.cs.
         {
             if (IsInBounds(0, row))
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = row; y > 0; --y)
                     {
                         this[x, y] = this[x, y - 1];
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.IsInBounds(), and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.TetrisGame.Update().
ToString()
override string Juniper.Puzzles.Puzzle.ToString () inline inherited
Definition at line 51 of file Puzzle.cs.
         {
             var sb = new StringBuilder();
             for (var y = 0; y < Height; ++y)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     sb.AppendFormat(CultureInfo.InvariantCulture, "{0},", grid[x, y]);
                 }
                 sb.AppendLine();
             }
             return sb.ToString();
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Update()
void Juniper.Puzzles.TetrisGame.Update (TimeSpan sinceLastDraw) inline
Definition at line 124 of file TetrisGame.cs.
         {
             if (!IsEmpty(RowOrder, 0))
             {
                 GameOver = true;
             }
             if (!GameOver)
             {
                 if (isLeftDown || isRightDown)
                 {
                     sinceLastMove += sinceLastDraw.TotalMilliseconds;
                     if (sinceLastMove >= millisPerMove)
                     {
                         sinceLastMove -= millisPerMove;
                         if (isLeftDown)
{
                             MoveLeft();
                         }
                         if (isRightDown)
{
                             MoveRight();
                         }
                     }
                 }
                 else
                 {
                     sinceLastMove = millisPerMove;
                 }
                 if (isFlipDown)
                 {
                     sinceLastFlip += sinceLastDraw.TotalMilliseconds;
                     if (sinceLastFlip >= millisPerFlip)
                     {
                         sinceLastFlip -= millisPerFlip;
                         var pre = Current.Rotate(Clockwise);
                         PlayFlip();
                         if (isFlipDown && IsInBounds(CursorX, CursorY, pre)
                             && IsEmpty(CursorX, CursorY, pre))
{
                             Current = pre;
                         }
                     }
                 }
                 else
                 {
                     sinceLastFlip = millisPerFlip;
                 }
                 if (isDropDown && sincePieceEntered >= 500.0)
                 {
                     sinceLastDrop += sinceLastDraw.TotalMilliseconds;
                     if (sinceLastDrop >= millisPerDrop)
                     {
                         sinceLastDrop -= millisPerDrop;
                         if (IsInBounds(CursorX, CursorY + 1, Current)
                                 && IsEmpty(CursorX, CursorY + 1, Current))
{
                             CursorY++;
                         }
                     }
                 }
                 else
                 {
                     sinceLastDrop = millisPerDrop;
                 }
                 if (!isDropDown)
                 {
                     sinceLastAdvance += sinceLastDraw.TotalMilliseconds;
                     sincePieceEntered += sinceLastDraw.TotalMilliseconds;
                     if (sinceLastAdvance >= millisPerAdvance)
                     {
                         sinceLastAdvance -= millisPerAdvance;
                         if (IsEmpty(CursorX, CursorY + 1, Current)
                             && IsInBounds(CursorX, CursorY + 1, Current))
{
                             CursorY++;
                         }
                         else
{
                             Fill(CursorX, CursorY, Current);
                             PlayThump();
                             Current = Next;
                             Next = pieces[rand.Next(pieces.Length)];
                             sincePieceEntered = 0.0;
                             CursorX = Width / 2;
                             CursorY = 0;
                         }
                         var clearCount = 0;
                         for (var y = 0; y < Height; ++y)
{
                             if (IsFull(RowOrder, y))
{
                                 TetrisClearRow(y);
                                 clearCount++;
                             }
                         }
                         if (clearCount > 0)
{
                             PlayLineClear(clearCount);
                             Score += clearCount * clearCount * 100;
                             UpdateSpeed(1);
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.Clockwise, Juniper.Puzzles.TetrisGame.Current, Juniper.Puzzles.TetrisGame.CursorX, Juniper.Puzzles.TetrisGame.CursorY, Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.TetrisGame.GameOver, Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.TetrisGame.isDropDown, Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.TetrisGame.isFlipDown, Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.TetrisGame.isLeftDown, Juniper.Puzzles.TetrisGame.isRightDown, Juniper.Puzzles.TetrisGame.millisPerAdvance, Juniper.Puzzles.TetrisGame.millisPerDrop, Juniper.Puzzles.TetrisGame.millisPerFlip, Juniper.Puzzles.TetrisGame.millisPerMove, Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), Juniper.Puzzles.TetrisGame.Next, Juniper.Puzzles.TetrisGame.pieces, Juniper.Puzzles.TetrisGame.PlayFlip(), Juniper.Puzzles.TetrisGame.PlayLineClear(), Juniper.Puzzles.TetrisGame.PlayThump(), Juniper.Puzzles.TetrisGame.rand, Juniper.Puzzles.Puzzle.Rotate(), Juniper.Puzzles.Puzzle.RowOrder, Juniper.Puzzles.TetrisGame.Score, Juniper.Puzzles.TetrisGame.sinceLastAdvance, Juniper.Puzzles.TetrisGame.sinceLastDrop, Juniper.Puzzles.TetrisGame.sinceLastFlip, Juniper.Puzzles.TetrisGame.sinceLastMove, Juniper.Puzzles.TetrisGame.sincePieceEntered, Juniper.Puzzles.TetrisGame.TetrisClearRow(), Juniper.Puzzles.TetrisGame.UpdateSpeed(), and Juniper.Puzzles.Puzzle.Width.
UpdateSpeed()
void Juniper.Puzzles.TetrisGame.UpdateSpeed (double deltaLinesPerSecond) inline private
Definition at line 99 of file TetrisGame.cs.
         {
             advanceRate += deltaLinesPerSecond;
             millisPerAdvance = 1000 / advanceRate;
             millisPerDrop = millisPerAdvance / 10;
         }
References Juniper.Puzzles.TetrisGame.advanceRate, Juniper.Puzzles.TetrisGame.millisPerAdvance, and Juniper.Puzzles.TetrisGame.millisPerDrop.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
Member Data Documentation
advanceRate
double Juniper.Puzzles.TetrisGame.advanceRate private
Definition at line 31 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.UpdateSpeed().
Clockwise
readonly bool Juniper.Puzzles.Puzzle.Clockwise = true static inherited
Definition at line 16 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Rotate(), and Juniper.Puzzles.TetrisGame.Update().
ColumnOrder
readonly bool Juniper.Puzzles.Puzzle.ColumnOrder = !RowOrder static inherited
Definition at line 15 of file Puzzle.cs.
CounterClockwise
readonly bool Juniper.Puzzles.Puzzle.CounterClockwise = !Clockwise static inherited
Definition at line 17 of file Puzzle.cs.
EmptyTile
readonly int Juniper.Puzzles.Puzzle.EmptyTile = -1 static inherited
Definition at line 13 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Console.IConsoleBufferExt.DrawPuzzle(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.Puzzle.Puzzle(), Juniper.Puzzles.Puzzle.ShiftColumnsDown(), Juniper.Puzzles.Puzzle.ShiftColumnsLeft(), Juniper.Puzzles.Puzzle.ShiftColumnsRight(), and Juniper.Puzzles.Puzzle.ShiftColumnsUp().
flipRate
double Juniper.Puzzles.TetrisGame.flipRate private
Definition at line 33 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset().
Height
int Juniper.Puzzles.Puzzle.Height => grid.GetHeight() inherited
Gets the height of the puzzle grid
Definition at line 73 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.CompareTo(), Juniper.Console.IConsoleBufferExt.DrawPuzzle(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.Puzzle.Rotate(), Juniper.Puzzles.Puzzle.ShiftColumnsDown(), Juniper.Puzzles.Puzzle.ShiftColumnsLeft(), Juniper.Puzzles.Puzzle.ShiftColumnsRight(), Juniper.Puzzles.Puzzle.ShiftColumnsUp(), Juniper.Puzzles.Puzzle.Swap(), Juniper.Puzzles.Puzzle.ToString(), and Juniper.Puzzles.TetrisGame.Update().
isDropDown
bool Juniper.Puzzles.TetrisGame.isDropDown private
Definition at line 30 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.SetDrop(), and Juniper.Puzzles.TetrisGame.Update().
isFlipDown
bool Juniper.Puzzles.TetrisGame.isFlipDown private
Definition at line 29 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.SetFlip(), and Juniper.Puzzles.TetrisGame.Update().
isLeftDown
bool Juniper.Puzzles.TetrisGame.isLeftDown private
Definition at line 27 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.SetLeft(), and Juniper.Puzzles.TetrisGame.Update().
isRightDown
bool Juniper.Puzzles.TetrisGame.isRightDown private
Definition at line 28 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.SetRight(), and Juniper.Puzzles.TetrisGame.Update().
millisPerAdvance
double Juniper.Puzzles.TetrisGame.millisPerAdvance private
Definition at line 34 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Update(), and Juniper.Puzzles.TetrisGame.UpdateSpeed().
millisPerDrop
double Juniper.Puzzles.TetrisGame.millisPerDrop private
Definition at line 37 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Update(), and Juniper.Puzzles.TetrisGame.UpdateSpeed().
millisPerFlip
double Juniper.Puzzles.TetrisGame.millisPerFlip private
Definition at line 36 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
millisPerMove
double Juniper.Puzzles.TetrisGame.millisPerMove private
Definition at line 35 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
moveRate
double Juniper.Puzzles.TetrisGame.moveRate private
Definition at line 32 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset().
pieces
readonly Puzzle [] Juniper.Puzzles.TetrisGame.pieces static private
Initial value:
=
            {
            new Puzzle(new int[,] { {  1,  1, 1, 1 } }),
            new Puzzle(new int[,] { {  2,  2 },
                                    {  2,  2 } }),
            new Puzzle(new int[,] { { -1,  3, -1 },
                                    {  3,  3,  3 } }),
            new Puzzle(new int[,] { {  4,  4, -1 },
                                    { -1,  4,  4 } }),
            new Puzzle(new int[,] { { -1,  5,  5 },
                                    {  5,  5, -1 } }),
            new Puzzle(new int[,] { {  6, -1, -1 },
                                    {  6,  6,  6 } }),
            new Puzzle(new int[,] { { -1, -1,  7 },
                                    {  7,  7,  7 } })
        }
Definition at line 7 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
rand
readonly Random Juniper.Puzzles.TetrisGame.rand = new Random() static private
Definition at line 25 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
RowOrder
readonly bool Juniper.Puzzles.Puzzle.RowOrder = true static inherited
Definition at line 14 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.Swap(), and Juniper.Puzzles.TetrisGame.Update().
sinceLastAdvance
double Juniper.Puzzles.TetrisGame.sinceLastAdvance private
Definition at line 39 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
sinceLastDrop
double Juniper.Puzzles.TetrisGame.sinceLastDrop private
Definition at line 41 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
sinceLastFlip
double Juniper.Puzzles.TetrisGame.sinceLastFlip private
Definition at line 40 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
sinceLastMove
double Juniper.Puzzles.TetrisGame.sinceLastMove private
Definition at line 38 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
sincePieceEntered
double Juniper.Puzzles.TetrisGame.sincePieceEntered private
Definition at line 42 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
Width
int Juniper.Puzzles.Puzzle.Width => grid.GetWidth() inherited
Gets the width of the puzzle grid
Definition at line 69 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.CompareTo(), Juniper.Console.IConsoleBufferExt.DrawPuzzle(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.TetrisGame.Reset(), Juniper.Puzzles.Puzzle.Rotate(), Juniper.Puzzles.Puzzle.ShiftColumnsDown(), Juniper.Puzzles.Puzzle.ShiftColumnsLeft(), Juniper.Puzzles.Puzzle.ShiftColumnsRight(), Juniper.Puzzles.Puzzle.ShiftColumnsUp(), Juniper.Puzzles.Puzzle.Swap(), Juniper.Puzzles.TetrisGame.TetrisClearRow(), Juniper.Puzzles.Puzzle.ToString(), and Juniper.Puzzles.TetrisGame.Update().
Property Documentation
Current
Puzzle Juniper.Puzzles.TetrisGame.Current get private set
Definition at line 46 of file TetrisGame.cs.
 { get; private set; }
Referenced by Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
CursorX
int Juniper.Puzzles.TetrisGame.CursorX get private set
Definition at line 48 of file TetrisGame.cs.
 { get; private set; }
Referenced by Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
CursorY
int Juniper.Puzzles.TetrisGame.CursorY get private set
Definition at line 49 of file TetrisGame.cs.
 { get; private set; }
Referenced by Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
GameOver
bool Juniper.Puzzles.TetrisGame.GameOver get private set
Definition at line 53 of file TetrisGame.cs.
 { get; private set; }
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
Grid
int [,] Juniper.Puzzles.Puzzle.Grid get set inherited
Gets or sets the raw puzzle grid array
Definition at line 105 of file Puzzle.cs.
         {
             get
             {
                 return grid;
             }
             set
             {
                 if (value != null && value.GetWidth() != 0 && value.GetHeight() != 0)
                 {
                     grid = new int[value.GetWidth(), value.GetHeight()];
                     Array.Copy(value, grid, value.Length);
                 }
                 else
                 {
                     throw new ArgumentException("Invalid initialization grid");
                 }
             }
         }
Referenced by Juniper.Puzzles.Puzzle.Puzzle().
Next
Puzzle Juniper.Puzzles.TetrisGame.Next get private set
Definition at line 44 of file TetrisGame.cs.
 { get; private set; }
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
Score
int Juniper.Puzzles.TetrisGame.Score get private set
Definition at line 51 of file TetrisGame.cs.
 { get; private set; }
Referenced by Juniper.Puzzles.TetrisGame.Reset(), and Juniper.Puzzles.TetrisGame.Update().
this[int x, int y]
int Juniper.Puzzles.Puzzle.this[int x, int y] get set inherited
Gets or sets a specific value on the puzzle grid
Parameters
x
y
Returns
Definition at line 82 of file Puzzle.cs.
         {
             get
             {
                 if (IsInBounds(x, y))
                 {
                     return grid[x, y];
                 }
                 return EmptyTile;
             }
             set
             {
                 if (IsInBounds(x, y))
                 {
                     grid[x, y] = value;
                 }
             }
         }
Event Documentation
Flip
EventHandler Juniper.Puzzles.TetrisGame.Flip
Definition at line 275 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.PlayFlip().
LineClear
EventHandler<IntegerEventArgs> Juniper.Puzzles.TetrisGame.LineClear
Definition at line 274 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.PlayLineClear().
Thump
EventHandler Juniper.Puzzles.TetrisGame.Thump
Definition at line 273 of file TetrisGame.cs.
Referenced by Juniper.Puzzles.TetrisGame.PlayThump().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Puzzles/TetrisGame.cs