Juniper: Juniper.HTTP.Server.CIDRBlock Class Reference
Juniper.HTTP.Server.CIDRBlock Class Reference
Public Member Functions
int CompareTo (CIDRBlock other)
CIDRBlock (IPAddress start, IPAddress end)
CIDRBlock (IPAddress start)
CIDRBlock (IPAddress start, int bitmaskLength)
override string ToString ()
Returns a string that represents the current CIDR Block. This is represented as the stringified Start address, separated from the BitmaskLength with a '/' character.
bool Contains (IPAddress item)
Determines whether the ICollection<T> contains a specific value.
bool Overlaps (CIDRBlock other)
float DistanceTo (CIDRBlock other)
CIDRBlock Combine (CIDRBlock right)
IEnumerator< IPAddress > GetEnumerator ()
void CopyTo (IPAddress[] array, int arrayIndex)
Copies the elements of the ICollection<T> to an Array, starting at a particular Array index.
bool Remove (IPAddress item)
Not supported.
void Add (IPAddress item)
Not supported.
void Clear ()
Not supported.
bool Equals (CIDRBlock other)
override bool Equals (object obj)
override int GetHashCode ()
Static Public Member Functions
static CIDRBlock [] Load (Stream stream)
static CIDRBlock [] Load (FileInfo file)
static CIDRBlock [] Load (string fileName)
static void Save (IEnumerable< CIDRBlock > blocks, Stream stream)
static void Save (IEnumerable< CIDRBlock > blocks, FileInfo file)
static void Save (IEnumerable< CIDRBlock > blocks, string fileName)
static CIDRBlock Parse (string value)
static bool TryParse (string value, out CIDRBlock block)
static int CompareAddresses (IPAddress left, IPAddress right)
static CIDRBlock operator+ (CIDRBlock left, CIDRBlock right)
static bool operator== (CIDRBlock left, CIDRBlock right)
static bool operator != (CIDRBlock left, CIDRBlock right)
static bool operator< (CIDRBlock left, CIDRBlock right)
static bool operator<= (CIDRBlock left, CIDRBlock right)
static bool operator > (CIDRBlock left, CIDRBlock right)
static bool operator >= (CIDRBlock left, CIDRBlock right)
Public Attributes
bool IsReadOnly => true
AddressFamily AddressFamily => Start.AddressFamily
Properties
int Count [get]
IPAddress Start [get]
IPAddress End [get]
IPAddress SubnetMask [get]
int BitmaskLength [get]
Private Member Functions
CIDRBlock (IPAddress start, IPAddress end, int bitmaskLength)
void ValidateOther (CIDRBlock other)
IEnumerator IEnumerable. GetEnumerator ()
Static Private Member Functions
static void ValidateAddressFamily (IPAddress start)
static void ValidateStart (IPAddress start)
static void ValidateEnd (IPAddress start, IPAddress end)
static void ValidateBitmaskLength (IPAddress start, int bitmaskLength)
static int CompareBytes (byte[] left, byte[] right)
static void ValidateStartEndOrder (IPAddress start, IPAddress end)
static int CalculateBitmaskLength (IPAddress start, IPAddress end)
static IPAddress CalculateEnd (IPAddress start, int bitmaskLength)
static IPAddress CalculateSubnetMask (byte[] startBytes, int bitmaskLength)
Private Attributes
readonly byte [] startBytes
readonly byte [] endBytes
Static Private Attributes
static readonly Dictionary< AddressFamily, int > BitLengths
Detailed Description
Definition at line 12 of file CIDRBlock.cs.
Constructor & Destructor Documentation
CIDRBlock() [1/4]
Juniper.HTTP.Server.CIDRBlock.CIDRBlock (IPAddress start, IPAddress end, int bitmaskLength) inline private
Definition at line 435 of file CIDRBlock.cs.
         {
             Start = start ?? throw new ArgumentNullException(nameof(start));
             End = end ?? throw new ArgumentNullException(nameof(end));
             startBytes = start.GetAddressBytes();
             endBytes = end.GetAddressBytes();
             BitmaskLength = bitmaskLength;
             Count = 0;
             for (var i = 0; i < startBytes.Length; ++i)
             {
                 Count *= byte.MaxValue;
                 Count += endBytes[i] - startBytes[i];
             }
             ++Count;
             SubnetMask = CalculateSubnetMask(startBytes, bitmaskLength);
         }
References Juniper.HTTP.Server.CIDRBlock.BitmaskLength, Juniper.HTTP.Server.CIDRBlock.CalculateSubnetMask(), Juniper.HTTP.Server.CIDRBlock.Count, Juniper.HTTP.Server.CIDRBlock.End, Juniper.HTTP.Server.CIDRBlock.endBytes, Juniper.HTTP.Server.CIDRBlock.Start, Juniper.HTTP.Server.CIDRBlock.startBytes, and Juniper.HTTP.Server.CIDRBlock.SubnetMask.
Referenced by Juniper.HTTP.Server.CIDRBlock.Combine(), Juniper.HTTP.Server.CIDRBlock.Parse(), and Juniper.HTTP.Server.CIDRBlock.TryParse().
CIDRBlock() [2/4]
Juniper.HTTP.Server.CIDRBlock.CIDRBlock (IPAddress start, IPAddress end) inline
Definition at line 458 of file CIDRBlock.cs.
             : this(start, end, CalculateBitmaskLength(start, end))
         { }
CIDRBlock() [3/4]
Juniper.HTTP.Server.CIDRBlock.CIDRBlock (IPAddress start) inline
Definition at line 462 of file CIDRBlock.cs.
             : this(start, start)
         { }
CIDRBlock() [4/4]
Juniper.HTTP.Server.CIDRBlock.CIDRBlock (IPAddress start, int bitmaskLength) inline
Definition at line 467 of file CIDRBlock.cs.
             : this(start, CalculateEnd(start, bitmaskLength), bitmaskLength)
         { }
Member Function Documentation
Add()
void Juniper.HTTP.Server.CIDRBlock.Add (IPAddress item) inline
Not supported.
Exceptions
NotSupportedException The ICollection<T> is read-only.
Definition at line 654 of file CIDRBlock.cs.
         {
             throw new NotSupportedException("This collection is read-only.");
         }
CalculateBitmaskLength()
static int Juniper.HTTP.Server.CIDRBlock.CalculateBitmaskLength (IPAddress start, IPAddress end) inline static private
Definition at line 326 of file CIDRBlock.cs.
         {
             ValidateStart(start);
             ValidateEnd(start, end);
             ValidateStartEndOrder(start, end);
             var startBytes = start.GetAddressBytes();
             var endBytes = end.GetAddressBytes();
             var bitmaskLength = 0;
             for (var i = 0; i < startBytes.Length; ++i)
             {
                 if (startBytes[i] == endBytes[i])
                 {
                     bitmaskLength += Units.Bits.PER_BYTE;
                 }
                 else
                 {
                     byte mask = 0x80;
                     for (var j = 0; j < Units.Bits.PER_BYTE; ++j)
                     {
                         if (((startBytes[i] ^ endBytes[i]) & mask) == 0)
{
                             ++bitmaskLength;
                         }
                         else
{
                             break;
                         }
                         mask >>= 1;
                     }
                     break;
                 }
             }
             return bitmaskLength;
         }
References Juniper.HTTP.Server.CIDRBlock.endBytes, Juniper.HTTP.Server.CIDRBlock.startBytes, Juniper.HTTP.Server.CIDRBlock.ValidateEnd(), Juniper.HTTP.Server.CIDRBlock.ValidateStart(), and Juniper.HTTP.Server.CIDRBlock.ValidateStartEndOrder().
CalculateEnd()
static IPAddress Juniper.HTTP.Server.CIDRBlock.CalculateEnd (IPAddress start, int bitmaskLength) inline static private
Definition at line 366 of file CIDRBlock.cs.
         {
             ValidateStart(start);
             ValidateBitmaskLength(start, bitmaskLength);
             var startBytes = start.GetAddressBytes();
             var endBytes = startBytes.ToArray();
             for (var i = 0; i < startBytes.Length; ++i)
             {
                 endBytes[i] = startBytes[i];
                 if (bitmaskLength >= Units.Bits.PER_BYTE)
                 {
                     bitmaskLength -= Units.Bits.PER_BYTE;
                 }
                 else
                 {
                     endBytes[i] |= (byte)(byte.MaxValue >> bitmaskLength);
                     for (var j = i + 1; j < startBytes.Length; ++j)
                     {
                         endBytes[j] = byte.MaxValue;
                     }
                     break;
                 }
             }
             return new IPAddress(endBytes);
         }
References Juniper.HTTP.Server.CIDRBlock.endBytes, Juniper.HTTP.Server.CIDRBlock.startBytes, Juniper.HTTP.Server.CIDRBlock.ValidateBitmaskLength(), and Juniper.HTTP.Server.CIDRBlock.ValidateStart().
CalculateSubnetMask()
static IPAddress Juniper.HTTP.Server.CIDRBlock.CalculateSubnetMask (byte [] startBytes, int bitmaskLength) inline static private
Definition at line 398 of file CIDRBlock.cs.
         {
             var subnetBytes = new byte[startBytes.Length];
             for (var i = 0; i < subnetBytes.Length; ++i)
             {
                 if (bitmaskLength >= Units.Bits.PER_BYTE)
                 {
                     subnetBytes[i] = byte.MaxValue;
                     bitmaskLength -= Units.Bits.PER_BYTE;
                 }
                 else
                 {
                     subnetBytes[i] = (byte)(byte.MaxValue << (Units.Bits.PER_BYTE - bitmaskLength));
                     break;
                 }
             }
             return new IPAddress(subnetBytes);
         }
References Juniper.HTTP.Server.CIDRBlock.startBytes.
Referenced by Juniper.HTTP.Server.CIDRBlock.CIDRBlock().
Clear()
void Juniper.HTTP.Server.CIDRBlock.Clear () inline
Not supported.
Exceptions
NotSupportedException The ICollection<T> is read-only.
Definition at line 663 of file CIDRBlock.cs.
         {
             throw new NotSupportedException("This collection is read-only.");
         }
Combine()
CIDRBlock Juniper.HTTP.Server.CIDRBlock.Combine (CIDRBlock right) inline
Definition at line 558 of file CIDRBlock.cs.
         {
             ValidateOther(right);
             var left = this;
             if (CompareBytes(left.startBytes, right.startBytes) > 0)
             {
                 var temp = left;
                 left = right;
                 right = temp;
             }
             return new CIDRBlock(left.Start, right.End);
         }
References Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), Juniper.HTTP.Server.CIDRBlock.CompareBytes(), and Juniper.HTTP.Server.CIDRBlock.ValidateOther().
CompareAddresses()
static int Juniper.HTTP.Server.CIDRBlock.CompareAddresses (IPAddress left, IPAddress right) inline static
Definition at line 288 of file CIDRBlock.cs.
         {
             if (left is null)
             {
                 throw new ArgumentNullException(nameof(left));
             }
             if (right is null)
             {
                 throw new ArgumentNullException(nameof(right));
             }
             if (left.AddressFamily != right.AddressFamily)
             {
                 throw new InvalidOperationException($"Cannot combine two blocks of different Address Family's. Expected {left.AddressFamily}. Got {right.AddressFamily}");
             }
             return CompareBytes(left.GetAddressBytes(), right.GetAddressBytes());
         }
References Juniper.HTTP.Server.CIDRBlock.CompareBytes().
Referenced by Juniper.HTTP.Server.CIDRBlock.CompareTo(), and Juniper.HTTP.Server.CIDRBlock.ValidateStartEndOrder().
CompareBytes()
static int Juniper.HTTP.Server.CIDRBlock.CompareBytes (byte [] left, byte [] right) inline static private
Definition at line 256 of file CIDRBlock.cs.
         {
             if (left is null)
             {
                 throw new ArgumentNullException(nameof(left));
             }
             if (right is null)
             {
                 throw new ArgumentNullException(nameof(right));
             }
             if (left.Length != right.Length)
             {
                 throw new InvalidOperationException("Byte array lengths must match");
             }
             for (var i = 0; i < left.Length; ++i)
             {
                 if (left[i] < right[i])
                 {
                     return -1;
                 }
                 else if (left[i] > right[i])
                 {
                     return 1;
                 }
             }
             return 0;
         }
Referenced by Juniper.HTTP.Server.CIDRBlock.Combine(), and Juniper.HTTP.Server.CIDRBlock.CompareAddresses().
CompareTo()
int Juniper.HTTP.Server.CIDRBlock.CompareTo (CIDRBlock other) inline
Definition at line 308 of file CIDRBlock.cs.
         {
             if (other is null)
             {
                 return -1;
             }
             return CompareAddresses(Start, other.Start);
         }
References Juniper.HTTP.Server.CIDRBlock.CompareAddresses(), and Juniper.HTTP.Server.CIDRBlock.Start.
Contains()
bool Juniper.HTTP.Server.CIDRBlock.Contains (IPAddress item) inline
Determines whether the ICollection<T> contains a specific value.
Parameters
item The object to locate in the ICollection<T>.
Returns
true if item is found in the ICollection<T>; otherwise, false.
Exceptions
ArgumentNullException item is null.
Definition at line 492 of file CIDRBlock.cs.
         {
             if (item is null)
             {
                 throw new ArgumentNullException(nameof(item));
             }
             if (item.AddressFamily != AddressFamily)
             {
                 return false;
             }
             var itemBytes = item.GetAddressBytes();
             for (var i = 0; i < itemBytes.Length; ++i)
             {
                 if (startBytes[i] > itemBytes[i]
                     || itemBytes[i] > endBytes[i])
                 {
                     return false;
                 }
             }
             return true;
         }
References Juniper.HTTP.Server.CIDRBlock.AddressFamily, Juniper.HTTP.Server.CIDRBlock.endBytes, and Juniper.HTTP.Server.CIDRBlock.startBytes.
Referenced by Juniper.HTTP.Server.CIDRBlock.Overlaps().
CopyTo()
void Juniper.HTTP.Server.CIDRBlock.CopyTo (IPAddress [] array, int arrayIndex) inline
Copies the elements of the ICollection<T> to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection<T>. The Array must have zero-based indexing.
arrayIndex The zero-based index in array at which copying begins.
Exceptions
ArgumentNullException array is null.
ArgumentOutOfRangeException arrayIndex is less than 0.
ArgumentException The number of elements in the source ICollection<T> is greater than the available space from arrayIndex to the end of the destination array .
Definition at line 617 of file CIDRBlock.cs.
         {
             if (array is null)
             {
                 throw new ArgumentNullException(nameof(array));
             }
             if (arrayIndex < 0)
             {
                 throw new ArgumentOutOfRangeException(nameof(arrayIndex));
             }
             if (Count > array.Length - arrayIndex)
             {
                 throw new ArgumentException("The number of elements in this collection is greater than the available space in the destination array.");
             }
             foreach (var address in this)
             {
                 array[arrayIndex++] = address;
             }
         }
References Juniper.HTTP.Server.CIDRBlock.Count.
DistanceTo()
float Juniper.HTTP.Server.CIDRBlock.DistanceTo (CIDRBlock other) inline
Definition at line 540 of file CIDRBlock.cs.
         {
             ValidateOther(other);
             var start = endBytes;
             var end = other.startBytes;
             var distance = 0f;
             for (var i = 0; i < start.Length; ++i)
             {
                 distance *= byte.MaxValue;
                 distance += end[i] - start[i];
             }
             return distance;
         }
References Juniper.HTTP.Server.CIDRBlock.endBytes, Juniper.HTTP.Server.CIDRBlock.startBytes, and Juniper.HTTP.Server.CIDRBlock.ValidateOther().
Equals() [1/2]
bool Juniper.HTTP.Server.CIDRBlock.Equals (CIDRBlock other) inline
Definition at line 668 of file CIDRBlock.cs.
         {
             return other is object
                 && other.Start == Start
                 && other.End == End;
         }
References Juniper.HTTP.Server.CIDRBlock.End, and Juniper.HTTP.Server.CIDRBlock.Start.
Referenced by Juniper.HTTP.Server.CIDRBlock.Equals().
Equals() [2/2]
override bool Juniper.HTTP.Server.CIDRBlock.Equals (object obj) inline
Definition at line 675 of file CIDRBlock.cs.
         {
             return obj is CIDRBlock block
                 && Equals(block);
         }
References Juniper.HTTP.Server.CIDRBlock.Equals().
GetEnumerator() [1/2]
IEnumerator IEnumerable. Juniper.HTTP.Server.CIDRBlock.GetEnumerator () inline private
Definition at line 583 of file CIDRBlock.cs.
         {
             return GetEnumerator();
         }
GetEnumerator() [2/2]
IEnumerator<IPAddress> Juniper.HTTP.Server.CIDRBlock.GetEnumerator () inline
Definition at line 588 of file CIDRBlock.cs.
         {
             var itemBytes = startBytes.ToArray();
             for (var i = 0; i < Count; ++i)
             {
                 yield return new IPAddress(itemBytes);
                 for (var j = itemBytes.Length - 1; j >= 0; --j)
                 {
                     ++itemBytes[j];
                     if (itemBytes[j] != 0)
                     {
                         break;
                     }
                 }
             }
         }
References Juniper.HTTP.Server.CIDRBlock.Count, and Juniper.HTTP.Server.CIDRBlock.startBytes.
GetHashCode()
override int Juniper.HTTP.Server.CIDRBlock.GetHashCode () inline
Definition at line 681 of file CIDRBlock.cs.
         {
             var hashCode = -1676728671;
             hashCode = (hashCode * -1521134295) + EqualityComparer<IPAddress>.Default.GetHashCode(Start);
             hashCode = (hashCode * -1521134295) + EqualityComparer<IPAddress>.Default.GetHashCode(End);
             return hashCode;
         }
References Juniper.HTTP.Default, Juniper.HTTP.Server.CIDRBlock.End, and Juniper.HTTP.Server.CIDRBlock.Start.
Load() [1/3]
static CIDRBlock [] Juniper.HTTP.Server.CIDRBlock.Load (Stream stream) inline static
Definition at line 23 of file CIDRBlock.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             if (!stream.CanRead)
             {
                 throw new AccessViolationException($"Cannot read from {nameof(stream)}.");
             }
             var blocks = new List<CIDRBlock>();
             using (var reader = new StreamReader(stream))
             {
                 while (!reader.EndOfStream)
                 {
                     var line = reader.ReadLine();
                     if (TryParse(line, out var block))
                     {
                         blocks.Add(block);
                     }
                 }
             }
             return blocks.ToArray();
         }
References Juniper.HTTP.Server.CIDRBlock.TryParse().
Referenced by Juniper.HTTP.Server.CIDRBlock.Load().
Load() [2/3]
static CIDRBlock [] Juniper.HTTP.Server.CIDRBlock.Load (FileInfo file) inline static
Definition at line 51 of file CIDRBlock.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             if (!file.Exists)
             {
                 return Array.Empty<CIDRBlock>();
             }
             using var stream = file.OpenRead();
             return Load(stream);
         }
References Juniper.HTTP.Server.CIDRBlock.Load().
Load() [3/3]
static CIDRBlock [] Juniper.HTTP.Server.CIDRBlock.Load (string fileName) inline static
Definition at line 67 of file CIDRBlock.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return Load(new FileInfo(fileName));
         }
References Juniper.HTTP.Server.CIDRBlock.Load().
operator !=()
static bool Juniper.HTTP.Server.CIDRBlock.operator != (CIDRBlock left, CIDRBlock right) inline static
Definition at line 695 of file CIDRBlock.cs.
         {
             return !(left == right);
         }
operator >()
static bool Juniper.HTTP.Server.CIDRBlock.operator > (CIDRBlock left, CIDRBlock right) inline static
Definition at line 713 of file CIDRBlock.cs.
         {
             return left is object
                 && left.CompareTo(right) > 0;
         }
operator >=()
static bool Juniper.HTTP.Server.CIDRBlock.operator >= (CIDRBlock left, CIDRBlock right) inline static
Definition at line 719 of file CIDRBlock.cs.
         {
             return left is null
                 ? right is null
                 : left.CompareTo(right) >= 0;
         }
operator+()
static CIDRBlock Juniper.HTTP.Server.CIDRBlock.operator+ (CIDRBlock left, CIDRBlock right) inline static
Definition at line 573 of file CIDRBlock.cs.
         {
             if (left is null)
             {
                 throw new ArgumentNullException(nameof(left));
             }
             return left.Combine(right);
         }
operator<()
static bool Juniper.HTTP.Server.CIDRBlock.operator< (CIDRBlock left, CIDRBlock right) inline static
Definition at line 700 of file CIDRBlock.cs.
         {
             return left is null
                 ? right is object
                 : left.CompareTo(right) < 0;
         }
operator<=()
static bool Juniper.HTTP.Server.CIDRBlock.operator<= (CIDRBlock left, CIDRBlock right) inline static
Definition at line 707 of file CIDRBlock.cs.
         {
             return left is null
                 || left.CompareTo(right) <= 0;
         }
operator==()
static bool Juniper.HTTP.Server.CIDRBlock.operator== (CIDRBlock left, CIDRBlock right) inline static
Definition at line 689 of file CIDRBlock.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
Overlaps()
bool Juniper.HTTP.Server.CIDRBlock.Overlaps (CIDRBlock other) inline
Definition at line 517 of file CIDRBlock.cs.
         {
             return other is object
                 && (Contains(other.Start)
                     || Contains(other.End)
                     || other.Contains(Start)
                     || other.Contains(End));
         }
References Juniper.HTTP.Server.CIDRBlock.Contains(), Juniper.HTTP.Server.CIDRBlock.End, and Juniper.HTTP.Server.CIDRBlock.Start.
Parse()
static CIDRBlock Juniper.HTTP.Server.CIDRBlock.Parse (string value) inline static
Definition at line 142 of file CIDRBlock.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             if (value.Length == 0)
             {
                 throw new FormatException("Empty string does not specify a valid CIDR block.");
             }
             var parts = value.SplitX('/');
             if (parts.Length > 2)
             {
                 throw new FormatException($"'{value}' does not specify a valid CIDR block. It contains more than one '/' character.");
             }
             var startString = parts[0];
             if (!IPAddress.TryParse(startString, out var start))
             {
                 throw new FormatException($"'{value}' does not specify a valid CIDR block. The first half is not a valid IP address.");
             }
             ValidateAddressFamily(start);
             if (parts.Length == 1)
             {
                 return new CIDRBlock(start);
             }
             else
             {
                 var bitmaskLengthString = parts[1];
                 if (!int.TryParse(bitmaskLengthString, out var bitmaskLength))
                 {
                     throw new FormatException($"'{value}' does not specify a valid CIDR block. The second half is not a valid int value.");
                 }
                 ValidateBitmaskLength(start, bitmaskLength);
                 return new CIDRBlock(start, bitmaskLength);
             }
         }
References Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), Juniper.HTTP.Server.CIDRBlock.TryParse(), Juniper.HTTP.Server.CIDRBlock.ValidateAddressFamily(), and Juniper.HTTP.Server.CIDRBlock.ValidateBitmaskLength().
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.FindBlocks().
Remove()
bool Juniper.HTTP.Server.CIDRBlock.Remove (IPAddress item) inline
Not supported.
Parameters
item
Exceptions
NotSupportedException The ICollection<T> is read-only.
Definition at line 645 of file CIDRBlock.cs.
         {
             throw new NotSupportedException("This collection is read-only.");
         }
Save() [1/3]
static void Juniper.HTTP.Server.CIDRBlock.Save (IEnumerable< CIDRBlock > blocks, Stream stream) inline static
Definition at line 82 of file CIDRBlock.cs.
         {
             if (blocks is null)
             {
                 throw new ArgumentNullException(nameof(blocks));
             }
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             if (!stream.CanWrite)
             {
                 throw new AccessViolationException($"Cannot write to {nameof(stream)}.");
             }
             using var writer = new StreamWriter(stream);
             foreach (var block in blocks)
             {
                 writer.WriteLine(block.ToString());
             }
         }
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch(), and Juniper.HTTP.Server.CIDRBlock.Save().
Save() [2/3]
static void Juniper.HTTP.Server.CIDRBlock.Save (IEnumerable< CIDRBlock > blocks, FileInfo file) inline static
Definition at line 106 of file CIDRBlock.cs.
         {
             if (blocks is null)
             {
                 throw new ArgumentNullException(nameof(blocks));
             }
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             using var stream = file.Create();
             Save(blocks, stream);
         }
References Juniper.HTTP.Server.CIDRBlock.Save().
Save() [3/3]
static void Juniper.HTTP.Server.CIDRBlock.Save (IEnumerable< CIDRBlock > blocks, string fileName) inline static
Definition at line 122 of file CIDRBlock.cs.
         {
             if (blocks is null)
             {
                 throw new ArgumentNullException(nameof(blocks));
             }
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             Save(blocks, new FileInfo(fileName));
         }
References Juniper.HTTP.Server.CIDRBlock.Save().
ToString()
override string Juniper.HTTP.Server.CIDRBlock.ToString () inline
Returns a string that represents the current CIDR Block. This is represented as the stringified Start address, separated from the BitmaskLength with a '/' character.
Returns
A string that represents the current object.
Definition at line 477 of file CIDRBlock.cs.
         {
             return Start.ToString()
                 + "/"
                 + BitmaskLength.ToString(CultureInfo.InvariantCulture);
         }
References Juniper.HTTP.Server.CIDRBlock.BitmaskLength, and Juniper.HTTP.Server.CIDRBlock.Start.
TryParse()
static bool Juniper.HTTP.Server.CIDRBlock.TryParse (string value, out CIDRBlock block) inline static
Definition at line 187 of file CIDRBlock.cs.
         {
             block = null;
             if (value is object)
             {
                 var parts = value.SplitX('/');
                 if (parts.Length == 0 || parts.Length > 2)
                 {
                     return false;
                 }
                 else if (IPAddress.TryParse(parts[0], out var start))
                 {
                     if (parts.Length == 1)
                     {
                         block = new CIDRBlock(start);
                     }
                     else if (int.TryParse(parts[1], out var bitmaskLength)
                         && BitLengths.ContainsKey(start.AddressFamily)
                         && bitmaskLength <= BitLengths[start.AddressFamily])
                     {
                         block = new CIDRBlock(start, bitmaskLength);
                     }
                 }
             }
             return block is object;
         }
References Juniper.HTTP.Server.CIDRBlock.BitLengths, and Juniper.HTTP.Server.CIDRBlock.CIDRBlock().
Referenced by Juniper.HTTP.Server.CIDRBlock.Load(), and Juniper.HTTP.Server.CIDRBlock.Parse().
ValidateAddressFamily()
static void Juniper.HTTP.Server.CIDRBlock.ValidateAddressFamily (IPAddress start) inline static private
Definition at line 217 of file CIDRBlock.cs.
         {
             if (!BitLengths.ContainsKey(start.AddressFamily))
             {
                 throw new NotSupportedException($"{start.AddressFamily.ToString()} is not a supported address type.");
             }
         }
References Juniper.HTTP.Server.CIDRBlock.BitLengths.
Referenced by Juniper.HTTP.Server.CIDRBlock.Parse(), and Juniper.HTTP.Server.CIDRBlock.ValidateStart().
ValidateBitmaskLength()
static void Juniper.HTTP.Server.CIDRBlock.ValidateBitmaskLength (IPAddress start, int bitmaskLength) inline static private
Definition at line 248 of file CIDRBlock.cs.
         {
             if (bitmaskLength > BitLengths[start.AddressFamily])
             {
                 throw new ArgumentOutOfRangeException(nameof(bitmaskLength), $"{bitmaskLength.ToString(CultureInfo.CurrentCulture)} is too large for {start.AddressFamily.ToString()} addresses. Expected: {BitLengths[start.AddressFamily].ToString(CultureInfo.CurrentCulture)}");
             }
         }
References Juniper.HTTP.Server.CIDRBlock.BitLengths.
Referenced by Juniper.HTTP.Server.CIDRBlock.CalculateEnd(), and Juniper.HTTP.Server.CIDRBlock.Parse().
ValidateEnd()
static void Juniper.HTTP.Server.CIDRBlock.ValidateEnd (IPAddress start, IPAddress end) inline static private
Definition at line 235 of file CIDRBlock.cs.
         {
             if (end is null)
             {
                 throw new ArgumentNullException(nameof(end));
             }
             if (start.AddressFamily != end.AddressFamily)
             {
                 throw new InvalidOperationException($"Both {nameof(start)} and {nameof(end)} addresses must be of the same family: {nameof(start)} is {start.AddressFamily.ToString()} and {nameof(end)} is {end.AddressFamily.ToString()}");
             }
         }
Referenced by Juniper.HTTP.Server.CIDRBlock.CalculateBitmaskLength().
ValidateOther()
void Juniper.HTTP.Server.CIDRBlock.ValidateOther (CIDRBlock other) inline private
Definition at line 526 of file CIDRBlock.cs.
         {
             if (other is null)
             {
                 throw new ArgumentNullException(nameof(other));
             }
             if (other.AddressFamily != AddressFamily)
             {
                 throw new InvalidOperationException($"Cannot combine two blocks of different Address Family's. Expected {AddressFamily}. Got {other.AddressFamily}");
             }
         }
References Juniper.HTTP.Server.CIDRBlock.AddressFamily.
Referenced by Juniper.HTTP.Server.CIDRBlock.Combine(), and Juniper.HTTP.Server.CIDRBlock.DistanceTo().
ValidateStart()
static void Juniper.HTTP.Server.CIDRBlock.ValidateStart (IPAddress start) inline static private
Definition at line 225 of file CIDRBlock.cs.
         {
             if (start is null)
             {
                 throw new ArgumentNullException(nameof(start));
             }
             ValidateAddressFamily(start);
         }
References Juniper.HTTP.Server.CIDRBlock.ValidateAddressFamily().
Referenced by Juniper.HTTP.Server.CIDRBlock.CalculateBitmaskLength(), and Juniper.HTTP.Server.CIDRBlock.CalculateEnd().
ValidateStartEndOrder()
static void Juniper.HTTP.Server.CIDRBlock.ValidateStartEndOrder (IPAddress start, IPAddress end) inline static private
Definition at line 318 of file CIDRBlock.cs.
         {
             if (CompareAddresses(start, end) > 0)
             {
                 throw new InvalidOperationException($"{nameof(end)} address must be greater than or equal to {nameof(start)} address.");
             }
         }
References Juniper.HTTP.Server.CIDRBlock.CompareAddresses().
Referenced by Juniper.HTTP.Server.CIDRBlock.CalculateBitmaskLength().
Member Data Documentation
AddressFamily
AddressFamily Juniper.HTTP.Server.CIDRBlock.AddressFamily => Start.AddressFamily
Definition at line 431 of file CIDRBlock.cs.
Referenced by Juniper.HTTP.Server.CIDRBlock.Contains(), and Juniper.HTTP.Server.CIDRBlock.ValidateOther().
BitLengths
readonly Dictionary<AddressFamily, int> Juniper.HTTP.Server.CIDRBlock.BitLengths static private
Initial value:
= new Dictionary<AddressFamily, int>
        {
            [AddressFamily.InterNetwork] = Units.Bits.PER_BYTE * 4,
            [AddressFamily.InterNetworkV6] = Units.Bits.PER_BYTE * 16
        }
Definition at line 17 of file CIDRBlock.cs.
Referenced by Juniper.HTTP.Server.CIDRBlock.TryParse(), Juniper.HTTP.Server.CIDRBlock.ValidateAddressFamily(), and Juniper.HTTP.Server.CIDRBlock.ValidateBitmaskLength().
endBytes
readonly byte [] Juniper.HTTP.Server.CIDRBlock.endBytes private
Definition at line 419 of file CIDRBlock.cs.
Referenced by Juniper.HTTP.Server.CIDRBlock.CalculateBitmaskLength(), Juniper.HTTP.Server.CIDRBlock.CalculateEnd(), Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), Juniper.HTTP.Server.CIDRBlock.Contains(), and Juniper.HTTP.Server.CIDRBlock.DistanceTo().
IsReadOnly
bool Juniper.HTTP.Server.CIDRBlock.IsReadOnly => true
Definition at line 421 of file CIDRBlock.cs.
startBytes
readonly byte [] Juniper.HTTP.Server.CIDRBlock.startBytes private
Definition at line 418 of file CIDRBlock.cs.
Referenced by Juniper.HTTP.Server.CIDRBlock.CalculateBitmaskLength(), Juniper.HTTP.Server.CIDRBlock.CalculateEnd(), Juniper.HTTP.Server.CIDRBlock.CalculateSubnetMask(), Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), Juniper.HTTP.Server.CIDRBlock.Contains(), Juniper.HTTP.Server.CIDRBlock.DistanceTo(), and Juniper.HTTP.Server.CIDRBlock.GetEnumerator().
Property Documentation
BitmaskLength
int Juniper.HTTP.Server.CIDRBlock.BitmaskLength get
Definition at line 433 of file CIDRBlock.cs.
 { get; }
Referenced by Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), and Juniper.HTTP.Server.CIDRBlock.ToString().
Count
int Juniper.HTTP.Server.CIDRBlock.Count get
Definition at line 423 of file CIDRBlock.cs.
 { get; }
Referenced by Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), Juniper.HTTP.Server.CIDRBlock.CopyTo(), and Juniper.HTTP.Server.CIDRBlock.GetEnumerator().
End
IPAddress Juniper.HTTP.Server.CIDRBlock.End get
Definition at line 427 of file CIDRBlock.cs.
 { get; }
Referenced by Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), Juniper.HTTP.Server.CIDRBlock.Equals(), Juniper.HTTP.Server.CIDRBlock.GetHashCode(), and Juniper.HTTP.Server.CIDRBlock.Overlaps().
Start
IPAddress Juniper.HTTP.Server.CIDRBlock.Start get
Definition at line 425 of file CIDRBlock.cs.
 { get; }
Referenced by Juniper.HTTP.Server.CIDRBlock.CIDRBlock(), Juniper.HTTP.Server.CIDRBlock.CompareTo(), Juniper.HTTP.Server.CIDRBlock.Equals(), Juniper.HTTP.Server.CIDRBlock.GetHashCode(), Juniper.HTTP.Server.CIDRBlock.Overlaps(), and Juniper.HTTP.Server.CIDRBlock.ToString().
SubnetMask
IPAddress Juniper.HTTP.Server.CIDRBlock.SubnetMask get
Definition at line 429 of file CIDRBlock.cs.
 { get; }
Referenced by Juniper.HTTP.Server.CIDRBlock.CIDRBlock().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Server/CIDRBlock.cs