Juniper: Juniper.Speech.Keywordable Class Reference
Juniper.Speech.Keywordable Class Reference
An object that can be fires an event when a particular keyword is uttered.
Public Member Functions
override bool IsInteractable ()
void SetTooltips ()
void ActivateEvent ()
Public Attributes
string [] keywords
The keywords that activate this event.
UnityEvent onActivated = new UnityEvent()
The event that fires when the shortcut key is activated. You should only prefer to use this version of the event over Activated in the Unity Editor, where standard .NET events are inexplicably unavailable.
bool interactable = true
Protected Member Functions
override void OnEnable ()
override void OnDisable ()
virtual void Awake ()
virtual void Update ()
Protected Attributes
UnifiedInputModule input
Properties
IEnumerable< string > Keywords [get]
The keywords that activate this event.
string DefaultDescription [get]
The default text to set to a tooltip for this set of keywords.
Events
EventHandler Activated
The event that fires when the shortcut key is activated. You should prefer to use this event over onActivated whenever possible, such as wiring up events programmatically.
Private Member Functions
void SetTooltips (bool force)
Detailed Description
An object that can be fires an event when a particular keyword is uttered.
Definition at line 14 of file Keywordable.cs.
Member Function Documentation
ActivateEvent()
void Juniper.Input.AbstractShortcutable.ActivateEvent () inline inherited
Definition at line 88 of file AbstractShortcutable.cs.
         {
             if (IsInteractable())
             {
                 onActivated?.Invoke();
                 Activated?.Invoke(this, EventArgs.Empty);
                 input.ClickButtons(GetComponents<IPointerClickHandler>());
             }
         }
References Juniper.Input.AbstractShortcutable.Activated, Juniper.Input.AbstractUnifiedInputModule.ClickButtons(), Juniper.Input.AbstractShortcutable.input, Juniper.Input.AbstractShortcutable.IsInteractable(), and Juniper.Input.AbstractShortcutable.onActivated.
Referenced by Juniper.Speech.KeywordRecognizer.Update().
Awake()
virtual void Juniper.Input.AbstractShortcutable.Awake () inline protected virtual inherited
Definition at line 49 of file AbstractShortcutable.cs.
         {
             Find.Any(out input);
             var parentControl = GetComponent<IPointerClickHandler>();
             if (parentControl is UnityEngine.UI.Selectable selectable)
             {
                 isParentEnabled = selectable.IsInteractable;
             }
             else if (parentControl is AbstractTouchable touchable)
             {
                 isParentEnabled = touchable.IsInteractable;
             }
             else
             {
                 isParentEnabled = AlwaysEnabled;
             }
         }
References Juniper.Input.AbstractShortcutable.AlwaysEnabled(), Juniper.Input.AbstractShortcutable.input, and Juniper.Input.AbstractShortcutable.isParentEnabled.
IsInteractable()
override bool Juniper.Speech.Keywordable.IsInteractable () inline virtual
Reimplemented from Juniper.Input.AbstractShortcutable.
Definition at line 22 of file Keywordable.cs.
         {
             return base.IsInteractable()
                 && input.VoiceEnabled;
         }
References Juniper.Input.AbstractShortcutable.input, and Juniper.Input.AbstractUnifiedInputModule.VoiceEnabled.
OnDisable()
override void Juniper.Speech.Keywordable.OnDisable () inline protected virtual
Implements Juniper.Input.AbstractShortcutable.
Definition at line 110 of file Keywordable.cs.
         {
             if (input != null && input.Voice != null)
             {
                 input.Voice.RemoveKeywordable(this);
             }
         }
References Juniper.Input.AbstractShortcutable.input, and Juniper.Input.AbstractUnifiedInputModule.Voice.
OnEnable()
override void Juniper.Speech.Keywordable.OnEnable () inline protected virtual
Implements Juniper.Input.AbstractShortcutable.
Definition at line 102 of file Keywordable.cs.
         {
             if (input != null && input.Voice != null)
             {
                 input.Voice.AddKeywordable(this);
             }
         }
References Juniper.Input.AbstractShortcutable.input, and Juniper.Input.AbstractUnifiedInputModule.Voice.
SetTooltips() [1/2]
void Juniper.Speech.Keywordable.SetTooltips () inline
Definition at line 56 of file Keywordable.cs.
         {
             SetTooltips(true);
         }
SetTooltips() [2/2]
void Juniper.Speech.Keywordable.SetTooltips (bool force) inline private
Definition at line 61 of file Keywordable.cs.
         {
             var tooltip = GetComponent<Tooltipable>();
             if (tooltip != null
                 && (force || string.IsNullOrEmpty(tooltip.Text)))
             {
                 tooltip.Text = DefaultDescription;
             }
         }
References Juniper.Speech.Keywordable.DefaultDescription.
Update()
virtual void Juniper.Input.AbstractShortcutable.Update () inline protected virtual inherited
Definition at line 71 of file AbstractShortcutable.cs.
         {
             var isInteractable = IsInteractable();
             if (isInteractable != wasInteractable)
             {
                 wasInteractable = isInteractable;
                 if (isInteractable)
                 {
                     OnEnable();
                 }
                 else
                 {
                     OnDisable();
                 }
             }
         }
References Juniper.Input.AbstractShortcutable.IsInteractable(), Juniper.Input.AbstractShortcutable.OnDisable(), Juniper.Input.AbstractShortcutable.OnEnable(), and Juniper.Input.AbstractShortcutable.wasInteractable.
Member Data Documentation
input
UnifiedInputModule Juniper.Input.AbstractShortcutable.input protected inherited
Definition at line 35 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent(), Juniper.Input.AbstractShortcutable.Awake(), Juniper.Speech.Keywordable.IsInteractable(), Juniper.Input.AbstractShortcutable.IsInteractable(), Juniper.Input.Keyboardable.OnDisable(), Juniper.Speech.Keywordable.OnDisable(), Juniper.Input.Keyboardable.OnEnable(), and Juniper.Speech.Keywordable.OnEnable().
interactable
bool Juniper.Input.AbstractShortcutable.interactable = true inherited
Definition at line 37 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.IsInteractable().
keywords
string [] Juniper.Speech.Keywordable.keywords
The keywords that activate this event.
Definition at line 20 of file Keywordable.cs.
Referenced by Juniper.Settings.AccessibilitySettings.Device.Update().
onActivated
UnityEvent Juniper.Input.AbstractShortcutable.onActivated = new UnityEvent() inherited
The event that fires when the shortcut key is activated. You should only prefer to use this version of the event over Activated in the Unity Editor, where standard .NET events are inexplicably unavailable.
Definition at line 26 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent().
Property Documentation
DefaultDescription
string Juniper.Speech.Keywordable.DefaultDescription get private
The default text to set to a tooltip for this set of keywords.
Definition at line 75 of file Keywordable.cs.
         {
             get
             {
                 if (keywords == null || keywords.Length == 0)
                 {
                     return string.Empty;
                 }
                 else if (keywords.Length == 1)
                 {
                     return $"Say \"{keywords[0]}\" to activate.";
                 }
                 else if (keywords.Length == 2)
                 {
                     return $"Say \"{keywords[0]}\" or \"{keywords[1]}\" to activate.";
                 }
                 else
                 {
                     var last = keywords.Last();
                     var list = keywords.Take(keywords.Length - 1);
                     var first = string.Join(", ", (from word in list
                                                    select '"' + word + '"'));
                     return $"Say {first} or \"{last}\" to activate.";
                 }
             }
         }
Referenced by Juniper.Speech.Keywordable.SetTooltips().
Keywords
IEnumerable<string> Juniper.Speech.Keywordable.Keywords get
The keywords that activate this event.
The keywords.
Definition at line 33 of file Keywordable.cs.
         {
             get
             {
                 return keywords;
             }
         }
Event Documentation
Activated
EventHandler Juniper.Input.AbstractShortcutable.Activated inherited
The event that fires when the shortcut key is activated. You should prefer to use this event over onActivated whenever possible, such as wiring up events programmatically.
Definition at line 32 of file AbstractShortcutable.cs.
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Speech/Keywordable.cs