Juniper: Juniper.Puzzles.Puzzle Class Reference
Juniper.Puzzles.Puzzle Class Reference
A physical representation of a puzzle as a 2D array of tile pieces. The grid can be manipulated in various ways to help facilitate rapid puzzle creations.
Public Member Functions
Puzzle (int gridWidth, int gridHeight)
Create an empty puzzle grid with a specified width and height
Puzzle (int[,] grid)
Create a puzzle grid from a 2D array of values
override string ToString ()
void Clear ()
Clear the entire board
void Clear (int x, int y)
Clear a single point on the puzzle grid
void Clear (bool order, int ordinal)
Clear a row or a column on the puzzle grid
void Clear (int left, int top, int width, int height)
Clear a rectangular block on the puzzle grid
void Clear (int[,] mask)
Batch clear specific points on the grid
void Clear (int left, int top, int[,] shape)
Clear an irregularly shaped area of the board
void Clear (int left, int top, Puzzle shape)
void Fill (int value)
Fill the entire puzzle grid with a single value
void Fill (bool order, int ordinal, int value)
Fill a row or column with a single value
void Fill (int left, int top, int width, int height, int value)
Fill a rectangular portion of the board
void Fill (Random prand)
Use a pseudorandom number generator to fill the entire board
void Fill ()
Use a pseudorandom number generator to fill the entire board
void Fill (int left, int top, Puzzle piece)
Copy a puzzle piece on top of the current puzzle at a specific location.
void Fill (int left, int top, int[,] shape)
Fill a specific area with a shape. Ignores empty tiles in the shape.
void ShiftColumnsDown ()
Make tiles above empty spots shift down into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
void ShiftColumnsUp ()
Make tiles below empty spots shift up into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
void ShiftColumnsLeft ()
Make tiles to the right empty spots shift left into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
void ShiftColumnsRight ()
Make tiles to the left empty spots shift right into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
bool IsInBounds (int x, int y)
Determine if a point is within the bounds of the board
bool IsInBounds (int x, int y, int width, int height)
Determine if a rectangle is completely contained within the board
bool IsInBounds (int x, int y, int[,] shape)
Determine if a shape is completely contained within the board
bool IsInBounds (int x, int y, Puzzle shape)
Determine if a puzzle piece is completely contained within the board
int CompareTo (Puzzle p)
Compares two puzzles to see if they match.
override bool Equals (object obj)
Compare two puzzles to see if they match element-for-element
override int GetHashCode ()
A recommended override if one overrides the Equals method
void Swap (int x1, int y1, int x2, int y2)
Swap two specific points on the puzzle
void Swap (bool order, int ordinal1, int ordinal2)
Swap two rows or two columns
void Swap (int x1, int y1, int x2, int y2, int width, int height)
Swap two rectangular areas that have the same dimensions but do not overlap
Puzzle Rotate (bool direction)
Rotate the puzzle by 90 degrees in either a clockwise or counterclockwise direction
Puzzle Duplicate ()
Creates a copy of the current puzzle
bool IsFull ()
Check to see if the board is full
bool IsFull (bool order, int ordinal)
Check to see if a row or column is full
bool IsFull (int x, int y, int width, int height)
Check to see if a rectangular area is full
bool IsFull (int x, int y, int[,] shape)
Check to see if a mask shape is full
bool IsFull (int x, int y, Puzzle shape)
Check to see if a puzzle piece shape is full
bool IsEmpty ()
bool IsEmpty (bool order, int ordinal)
bool IsEmpty (int x, int y, int width, int height)
bool IsEmpty (int x, int y, int[,] shape)
bool IsEmpty (int x, int y, Puzzle shape)
Static Public Member Functions
static bool RectsIntersect (int x1, int y1, int x2, int y2, int width, int height)
Check if two rectangles, of the same size in different locations, overlap each other.
static bool operator== (Puzzle left, Puzzle right)
static bool operator != (Puzzle left, Puzzle right)
static bool operator< (Puzzle left, Puzzle right)
static bool operator<= (Puzzle left, Puzzle right)
static bool operator > (Puzzle left, Puzzle right)
static bool operator >= (Puzzle left, Puzzle right)
Public Attributes
int Width => grid.GetWidth()
Gets the width of the puzzle grid
int Height => grid.GetHeight()
Gets the height of the puzzle grid
Static Public Attributes
static readonly int EmptyTile = -1
static readonly bool RowOrder = true
static readonly bool ColumnOrder = !RowOrder
static readonly bool Clockwise = true
static readonly bool CounterClockwise = !Clockwise
Properties
int this[int x, int y] [get, set]
Gets or sets a specific value on the puzzle grid
int [,] Grid [get, set]
Gets or sets the raw puzzle grid array
Private Attributes
int [,] grid
Detailed Description
A physical representation of a puzzle as a 2D array of tile pieces. The grid can be manipulated in various ways to help facilitate rapid puzzle creations.
Definition at line 11 of file Puzzle.cs.
Constructor & Destructor Documentation
Puzzle() [1/2]
Juniper.Puzzles.Puzzle.Puzzle (int gridWidth, int gridHeight) inline
Create an empty puzzle grid with a specified width and height
Parameters
gridWidth
gridHeight
Definition at line 25 of file Puzzle.cs.
         {
             if (gridWidth <= 0 || gridHeight <= 0)
             {
                 throw new ArgumentException("Width and height dimensions must be greater than 0");
             }
             grid = new int[gridWidth, gridHeight];
             for (var y = 0; y < gridHeight; ++y)
             {
                 for (var x = 0; x < gridWidth; ++x)
                 {
                     grid[x, y] = EmptyTile;
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, and Juniper.Puzzles.Puzzle.grid.
Referenced by Juniper.Puzzles.Puzzle.Duplicate(), and Juniper.Puzzles.Puzzle.Rotate().
Puzzle() [2/2]
Juniper.Puzzles.Puzzle.Puzzle (int grid[,]) inline
Create a puzzle grid from a 2D array of values
Parameters
grid
Definition at line 46 of file Puzzle.cs.
         {
             Grid = grid;
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.Grid.
Member Function Documentation
Clear() [1/7]
void Juniper.Puzzles.Puzzle.Clear () inline
Clear the entire board
Definition at line 127 of file Puzzle.cs.
         {
             Clear(0, 0, Width, Height);
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.Clear().
Clear() [2/7]
void Juniper.Puzzles.Puzzle.Clear (int x, int y) inline
Clear a single point on the puzzle grid
Parameters
x
y
Definition at line 137 of file Puzzle.cs.
         {
             Clear(x, y, 1, 1);
         }
References Juniper.Puzzles.Puzzle.Clear().
Clear() [3/7]
void Juniper.Puzzles.Puzzle.Clear (bool order, int ordinal) inline
Clear a row or a column on the puzzle grid
Parameters
order Puzzle.RowOrder to clear a row, Puzzle.ColumnOrder to clear a column
ordinal the row or column index to clear
Definition at line 147 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 Clear(0, ordinal, Width, 1);
             }
             else
             {
                 Clear(ordinal, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
Clear() [4/7]
void Juniper.Puzzles.Puzzle.Clear (int left, int top, int width, int height) inline
Clear a rectangular block on the puzzle grid
Parameters
left
top
width
height
Definition at line 166 of file Puzzle.cs.
         {
             Fill(left, top, width, height, EmptyTile);
         }
References Juniper.Puzzles.Puzzle.EmptyTile, and Juniper.Puzzles.Puzzle.Fill().
Clear() [5/7]
void Juniper.Puzzles.Puzzle.Clear (int mask[,]) inline
Batch clear specific points on the grid
Parameters
mask a 2D array of flags marking points that should be cleared. The array should be as large as the puzzle grid
Definition at line 176 of file Puzzle.cs.
         {
             if (mask != null
                 && mask.GetWidth() == Width
                 && mask.GetHeight() == Height)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (mask[x, y] != EmptyTile)
{
                             grid[x, y] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Clear() [6/7]
void Juniper.Puzzles.Puzzle.Clear (int left, int top, int shape[,]) inline
Clear an irregularly shaped area of the board
Parameters
left
top
shape a 2D array of flags marking points that should be cleared.
Definition at line 201 of file Puzzle.cs.
         {
             if (shape != null)
             {
                 for (var x = left; x < shape.GetWidth() + left; ++x)
                 {
                     if (x >= 0 && x < Width)
                     {
                         for (var y = top; y < shape.GetHeight() + top; ++y)
{
                             if (y >= 0 && y < Height && shape[x - left, y - top] != EmptyTile)
{
                                 grid[x, y] = EmptyTile;
                             }
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Clear() [7/7]
void Juniper.Puzzles.Puzzle.Clear (int left, int top, Puzzle shape) inline
Definition at line 221 of file Puzzle.cs.
         {
             if (shape != null)
             {
                 Clear(left, top, shape.grid);
             }
         }
References Juniper.Puzzles.Puzzle.Clear(), and Juniper.Puzzles.Puzzle.grid.
CompareTo()
int Juniper.Puzzles.Puzzle.CompareTo (Puzzle p) inline
Compares two puzzles to see if they match.
Parameters
p
Returns
+1 if the dimensions do not match -1 if at least one of the points do not match 0 if the puzzles are equivalent
Definition at line 509 of file Puzzle.cs.
         {
             if (p is null)
             {
                 throw new ArgumentNullException(nameof(p));
             }
             if (Width == p.Width && Height == p.Height)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (this[x, y] != p[x, y])
{
                             return -1;
                         }
                     }
                 }
                 return 0;
             }
             return +1;
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.Equals().
Duplicate()
Puzzle Juniper.Puzzles.Puzzle.Duplicate () inline
Creates a copy of the current puzzle
Returns
Definition at line 670 of file Puzzle.cs.
         {
             return new Puzzle(grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.Puzzle().
Equals()
override bool Juniper.Puzzles.Puzzle.Equals (object obj) inline
Compare two puzzles to see if they match element-for-element
Parameters
obj
Returns
Definition at line 539 of file Puzzle.cs.
         {
             if (obj is Puzzle)
             {
                 return CompareTo(obj as Puzzle) == 0;
             }
             return false;
         }
References Juniper.Puzzles.Puzzle.CompareTo().
Fill() [1/7]
void Juniper.Puzzles.Puzzle.Fill (int value) inline
Fill the entire puzzle grid with a single value
Parameters
value
Definition at line 233 of file Puzzle.cs.
         {
             Fill(0, 0, Width, Height, value);
         }
References Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Fill() [2/7]
void Juniper.Puzzles.Puzzle.Fill (bool order, int ordinal, int value) inline
Fill a row or column with a single value
Parameters
order Puzzle.RowOrder to fill a row, Puzzle.ColumnOrder to fill a column
ordinal the row or column index to fill
value
Definition at line 244 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 Fill(0, ordinal, Width, 1, value);
             }
             else
             {
                 Fill(ordinal, 0, 1, Height, value);
             }
         }
References Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
Fill() [3/7]
void Juniper.Puzzles.Puzzle.Fill (int left, int top, int width, int height, int value) inline
Fill a rectangular portion of the board
Parameters
left
top
width
height
value
Definition at line 264 of file Puzzle.cs.
         {
             for (var x = left; x < left + width && x < Width; ++x)
             {
                 if (x >= 0)
                 {
                     for (var y = top; y < top + height && y < Height; ++y)
                     {
                         if (y >= 0)
{
                             grid[x, y] = value;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Fill() [4/7]
void Juniper.Puzzles.Puzzle.Fill (Random prand) inline
Use a pseudorandom number generator to fill the entire board
Parameters
prand
Definition at line 285 of file Puzzle.cs.
         {
             if (prand != null)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         grid[x, y] = prand.Next();
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Fill() [5/7]
void Juniper.Puzzles.Puzzle.Fill () inline
Use a pseudorandom number generator to fill the entire board
Definition at line 302 of file Puzzle.cs.
         {
             Fill(new Random());
         }
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.Fill(), and Juniper.Puzzles.TetrisGame.Update().
Fill() [6/7]
void Juniper.Puzzles.Puzzle.Fill (int left, int top, Puzzle piece) inline
Copy a puzzle piece on top of the current puzzle at a specific location.
Parameters
left
top
piece
Definition at line 313 of file Puzzle.cs.
         {
             if (piece != null)
             {
                 Fill(left, top, piece.grid);
             }
         }
References Juniper.Puzzles.Puzzle.Fill(), and Juniper.Puzzles.Puzzle.grid.
Fill() [7/7]
void Juniper.Puzzles.Puzzle.Fill (int left, int top, int shape[,]) inline
Fill a specific area with a shape. Ignores empty tiles in the shape.
Parameters
left
top
shape
Definition at line 327 of file Puzzle.cs.
         {
             if (shape != null)
             {
                 for (var x = left; x < left + shape.GetWidth() && x < Width; ++x)
                 {
                     if (x >= 0)
                     {
                         for (var y = top; y < top + shape.GetHeight() && y < Height; ++y)
{
                             if (y >= 0 && shape[x - left, y - top] != EmptyTile)
{
                                 grid[x, y] = shape[x - left, y - top];
                             }
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
GetHashCode()
override int Juniper.Puzzles.Puzzle.GetHashCode () inline
A recommended override if one overrides the Equals method
Returns
Definition at line 553 of file Puzzle.cs.
         {
             return grid.GetHashCode();
         }
References Juniper.Puzzles.Puzzle.grid.
IsEmpty() [1/5]
bool Juniper.Puzzles.Puzzle.IsEmpty () inline
Definition at line 766 of file Puzzle.cs.
         {
             return IsEmpty(0, 0, Width, Height);
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), and Juniper.Puzzles.TetrisGame.Update().
IsEmpty() [2/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (bool order, int ordinal) inline
Definition at line 771 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 return IsEmpty(0, ordinal, Width, 1);
             }
             else
             {
                 return IsEmpty(ordinal, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
IsEmpty() [3/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (int x, int y, int width, int height) inline
Definition at line 783 of file Puzzle.cs.
         {
             for (var dx = 0; dx < width; ++dx)
             {
                 for (var dy = 0; dy < height; ++dy)
                 {
                     if (this[x + dx, y + dy] != EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsEmpty() [4/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (int x, int y, int shape[,]) inline
Definition at line 799 of file Puzzle.cs.
         {
             if (shape == null || shape.Length == 0)
             {
                 return false;
             }
             for (var dx = 0; dx < shape.GetWidth(); ++dx)
             {
                 for (var dy = 0; dy < shape.GetHeight(); ++dy)
                 {
                     if (shape[dx, dy] != EmptyTile && this[x + dx, y + dy] != EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsEmpty() [5/5]
bool Juniper.Puzzles.Puzzle.IsEmpty (int x, int y, Puzzle shape) inline
Definition at line 820 of file Puzzle.cs.
         {
             return shape != null && IsEmpty(x, y, shape.grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.IsEmpty().
IsFull() [1/5]
bool Juniper.Puzzles.Puzzle.IsFull () inline
Check to see if the board is full
Returns
Definition at line 679 of file Puzzle.cs.
         {
             return IsFull(0, 0, Width, Height);
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.IsFull(), and Juniper.Puzzles.TetrisGame.Update().
IsFull() [2/5]
bool Juniper.Puzzles.Puzzle.IsFull (bool order, int ordinal) inline
Check to see if a row or column is full
Parameters
order
ordinal
Returns
Definition at line 690 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 return IsFull(0, ordinal, Width, 1);
             }
             else
             {
                 return IsFull(ordinal, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.RowOrder, and Juniper.Puzzles.Puzzle.Width.
IsFull() [3/5]
bool Juniper.Puzzles.Puzzle.IsFull (int x, int y, int width, int height) inline
Check to see if a rectangular area is full
Parameters
x
y
width
height
Returns
Definition at line 710 of file Puzzle.cs.
         {
             for (var dx = 0; dx < width; ++dx)
             {
                 for (var dy = 0; dy < height; ++dy)
                 {
                     if (this[x + dx, y + dy] == EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsFull() [4/5]
bool Juniper.Puzzles.Puzzle.IsFull (int x, int y, int shape[,]) inline
Check to see if a mask shape is full
Parameters
x
y
shape
Returns
Definition at line 733 of file Puzzle.cs.
         {
             if (shape == null || shape.Length == 0)
             {
                 return false;
             }
             for (var dx = 0; dx < shape.GetWidth(); ++dx)
             {
                 for (var dy = 0; dy < shape.GetHeight(); ++dy)
                 {
                     if (shape[dx, dy] != EmptyTile && this[x + dx, y + dy] == EmptyTile)
                     {
                         return false;
                     }
                 }
             }
             return true;
         }
References Juniper.Puzzles.Puzzle.EmptyTile.
IsFull() [5/5]
bool Juniper.Puzzles.Puzzle.IsFull (int x, int y, Puzzle shape) inline
Check to see if a puzzle piece shape is full
Parameters
x
y
shape
Returns
Definition at line 761 of file Puzzle.cs.
         {
             return shape != null && IsFull(x, y, shape.grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.IsFull().
IsInBounds() [1/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y) inline
Determine if a point is within the bounds of the board
Parameters
x
y
Returns
Definition at line 442 of file Puzzle.cs.
         {
             return x >= 0 && x < Width
                 && y >= 0 && y < Height;
         }
References Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.TetrisGame.MoveLeft(), Juniper.Puzzles.TetrisGame.MoveRight(), Juniper.Puzzles.Puzzle.Swap(), Juniper.Puzzles.TetrisGame.TetrisClearRow(), and Juniper.Puzzles.TetrisGame.Update().
IsInBounds() [2/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y, int width, int height) inline
Determine if a rectangle is completely contained within the board
Parameters
x
y
width
height
Returns
Definition at line 456 of file Puzzle.cs.
         {
             return IsInBounds(x, y) && IsInBounds(x + width - 1, y + height - 1);
         }
References Juniper.Puzzles.Puzzle.IsInBounds().
IsInBounds() [3/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y, int shape[,]) inline
Determine if a shape is completely contained within the board
Parameters
x
y
shape
Returns
Definition at line 468 of file Puzzle.cs.
         {
             if (shape != null && shape.Length > 0)
             {
                 for (var dx = 0; dx < shape.GetWidth(); ++dx)
                 {
                     for (var dy = 0; dy < shape.GetHeight(); ++dy)
                     {
{
                             if (shape[dx, dy] != EmptyTile && !IsInBounds(x + dx, y + dy))
{
                                 return false;
                             }
                         }
                     }
                 }
                 return true;
             }
             return false;
         }
References Juniper.Puzzles.Puzzle.EmptyTile, and Juniper.Puzzles.Puzzle.IsInBounds().
IsInBounds() [4/4]
bool Juniper.Puzzles.Puzzle.IsInBounds (int x, int y, Puzzle shape) inline
Determine if a puzzle piece is completely contained within the board
Parameters
x
y
shape
Returns
Definition at line 497 of file Puzzle.cs.
         {
             return shape != null && IsInBounds(x, y, shape.grid);
         }
References Juniper.Puzzles.Puzzle.grid, and Juniper.Puzzles.Puzzle.IsInBounds().
operator !=()
static bool Juniper.Puzzles.Puzzle.operator != (Puzzle left, Puzzle right) inline static
Definition at line 831 of file Puzzle.cs.
         {
             return !(left == right);
         }
operator >()
static bool Juniper.Puzzles.Puzzle.operator > (Puzzle left, Puzzle right) inline static
Definition at line 847 of file Puzzle.cs.
         {
             return left is object && left.CompareTo(right) > 0;
         }
operator >=()
static bool Juniper.Puzzles.Puzzle.operator >= (Puzzle left, Puzzle right) inline static
Definition at line 852 of file Puzzle.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.CompareTo(right) >= 0);
         }
operator<()
static bool Juniper.Puzzles.Puzzle.operator< (Puzzle left, Puzzle right) inline static
Definition at line 836 of file Puzzle.cs.
         {
             return (left is null && right is object)
                 || (left is object  && left.CompareTo(right) < 0);
         }
operator<=()
static bool Juniper.Puzzles.Puzzle.operator<= (Puzzle left, Puzzle right) inline static
Definition at line 842 of file Puzzle.cs.
         {
             return left is null || left.CompareTo(right) <= 0;
         }
operator==()
static bool Juniper.Puzzles.Puzzle.operator== (Puzzle left, Puzzle right) inline static
Definition at line 825 of file Puzzle.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
RectsIntersect()
static bool Juniper.Puzzles.Puzzle.RectsIntersect (int x1, int y1, int x2, int y2, int width, int height) inline static
Check if two rectangles, of the same size in different locations, overlap each other.
Parameters
x1
y1
x2
y2
width
height
Returns
Definition at line 625 of file Puzzle.cs.
         {
             System.Drawing.Rectangle a, b;
             a = new System.Drawing.Rectangle(x1, y1, width, height);
             b = new System.Drawing.Rectangle(x2, y2, width, height);
             return a.IntersectsWith(b);
         }
Referenced by Juniper.Puzzles.Puzzle.Swap().
Rotate()
Puzzle Juniper.Puzzles.Puzzle.Rotate (bool direction) inline
Rotate the puzzle by 90 degrees in either a clockwise or counterclockwise direction
Parameters
direction
Returns
A new puzzle that represents the rotated puzzle
Definition at line 638 of file Puzzle.cs.
         {
             var q = new Puzzle(Height, Width);
             if (direction == Clockwise)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         q[q.Width - y - 1, x] = this[x, y];
                     }
                 }
             }
             else
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         q[y, q.Height - x - 1] = this[x, y];
                     }
                 }
             }
             return q;
         }
References Juniper.Puzzles.Puzzle.Clockwise, Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.Puzzle(), and Juniper.Puzzles.Puzzle.Width.
Referenced by Juniper.Puzzles.TetrisGame.Update().
ShiftColumnsDown()
void Juniper.Puzzles.Puzzle.ShiftColumnsDown () inline
Make tiles above empty spots shift down into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 351 of file Puzzle.cs.
         {
             for (var x = 0; x < Width; ++x)
             {
                 for (var y = Height - 1; y > 0; --y)
                 {
                     for (var y2 = y - 1; y2 >= 0; --y2)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x, y];
                             grid[x, y2] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
ShiftColumnsLeft()
void Juniper.Puzzles.Puzzle.ShiftColumnsLeft () inline
Make tiles to the right empty spots shift left into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 396 of file Puzzle.cs.
         {
             for (var x = 0; x < Width - 1; ++x)
             {
                 for (var x2 = x + 1; x2 < Width; ++x2)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x2, y];
                             grid[x2, y] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
ShiftColumnsRight()
void Juniper.Puzzles.Puzzle.ShiftColumnsRight () inline
Make tiles to the left empty spots shift right into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 418 of file Puzzle.cs.
         {
             for (var x = Width - 1; x > 0; --x)
             {
                 for (var x2 = x - 1; x2 >= 0; --x2)
                 {
                     for (var y = 0; y < Height; ++y)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x2, y];
                             grid[x2, y] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
ShiftColumnsUp()
void Juniper.Puzzles.Puzzle.ShiftColumnsUp () inline
Make tiles below empty spots shift up into the empty spot, leaving an empty spot behind them. This is a modification of Insertion Sort, and is an O(n^3) operation.
Definition at line 374 of file Puzzle.cs.
         {
             for (var x = 0; x < Width; ++x)
             {
                 for (var y = 0; y < Height - 1; ++y)
                 {
                     for (var y2 = y + 1; y2 < Height; ++y2)
                     {
                         if (grid[x, y] == EmptyTile)
{
                             grid[x, y] = grid[x, y2];
                             grid[x, y2] = EmptyTile;
                         }
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Swap() [1/3]
void Juniper.Puzzles.Puzzle.Swap (int x1, int y1, int x2, int y2) inline
Swap two specific points on the puzzle
Parameters
x1
y1
x2
y2
Definition at line 565 of file Puzzle.cs.
         {
             Swap(x1, y1, x2, y2, 1, 1);
         }
Referenced by Juniper.Puzzles.Puzzle.Swap().
Swap() [2/3]
void Juniper.Puzzles.Puzzle.Swap (bool order, int ordinal1, int ordinal2) inline
Swap two rows or two columns
Parameters
order
ordinal1
ordinal2
Definition at line 576 of file Puzzle.cs.
         {
             if (order == RowOrder)
             {
                 Swap(0, ordinal1, 0, ordinal2, Width, 1);
             }
             else
             {
                 Swap(ordinal1, 0, ordinal2, 0, 1, Height);
             }
         }
References Juniper.Puzzles.Puzzle.Height, Juniper.Puzzles.Puzzle.RowOrder, Juniper.Puzzles.Puzzle.Swap(), and Juniper.Puzzles.Puzzle.Width.
Swap() [3/3]
void Juniper.Puzzles.Puzzle.Swap (int x1, int y1, int x2, int y2, int width, int height) inline
Swap two rectangular areas that have the same dimensions but do not overlap
Parameters
x1
y1
x2
y2
width
height
Definition at line 597 of file Puzzle.cs.
         {
             int temp;
             if (IsInBounds(x1, y1, width, height) && IsInBounds(x2, y2, width, height)
                 && !RectsIntersect(x1, y1, x2, y2, width, height))
             {
                 for (var x = 0; x < width; ++x)
                 {
                     for (var y = 0; y < height; ++y)
                     {
                         temp = grid[x1 + x, y1 + y];
                         grid[x1 + x, y1 + y] = grid[x2 + x, y2 + y];
                         grid[x2 + x, y2 + y] = temp;
                     }
                 }
             }
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.IsInBounds(), and Juniper.Puzzles.Puzzle.RectsIntersect().
ToString()
override string Juniper.Puzzles.Puzzle.ToString () inline
Definition at line 51 of file Puzzle.cs.
         {
             var sb = new StringBuilder();
             for (var y = 0; y < Height; ++y)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     sb.AppendFormat(CultureInfo.InvariantCulture, "{0},", grid[x, y]);
                 }
                 sb.AppendLine();
             }
             return sb.ToString();
         }
References Juniper.Puzzles.Puzzle.grid, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Member Data Documentation
Clockwise
readonly bool Juniper.Puzzles.Puzzle.Clockwise = true static
Definition at line 16 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Rotate(), and Juniper.Puzzles.TetrisGame.Update().
ColumnOrder
readonly bool Juniper.Puzzles.Puzzle.ColumnOrder = !RowOrder static
Definition at line 15 of file Puzzle.cs.
CounterClockwise
readonly bool Juniper.Puzzles.Puzzle.CounterClockwise = !Clockwise static
Definition at line 17 of file Puzzle.cs.
EmptyTile
readonly int Juniper.Puzzles.Puzzle.EmptyTile = -1 static
Definition at line 13 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Console.IConsoleBufferExt.DrawPuzzle(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.Puzzle.Puzzle(), Juniper.Puzzles.Puzzle.ShiftColumnsDown(), Juniper.Puzzles.Puzzle.ShiftColumnsLeft(), Juniper.Puzzles.Puzzle.ShiftColumnsRight(), and Juniper.Puzzles.Puzzle.ShiftColumnsUp().
grid
int [,] Juniper.Puzzles.Puzzle.grid private
Definition at line 18 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.Duplicate(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.GetHashCode(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.TetrisGame.MakeEmptyGrid(), Juniper.Puzzles.Puzzle.Puzzle(), Juniper.Puzzles.Puzzle.ShiftColumnsDown(), Juniper.Puzzles.Puzzle.ShiftColumnsLeft(), Juniper.Puzzles.Puzzle.ShiftColumnsRight(), Juniper.Puzzles.Puzzle.ShiftColumnsUp(), Juniper.Puzzles.Puzzle.Swap(), and Juniper.Puzzles.Puzzle.ToString().
Height
int Juniper.Puzzles.Puzzle.Height => grid.GetHeight()
Gets the height of the puzzle grid
Definition at line 73 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.CompareTo(), Juniper.Console.IConsoleBufferExt.DrawPuzzle(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.Puzzle.Rotate(), Juniper.Puzzles.Puzzle.ShiftColumnsDown(), Juniper.Puzzles.Puzzle.ShiftColumnsLeft(), Juniper.Puzzles.Puzzle.ShiftColumnsRight(), Juniper.Puzzles.Puzzle.ShiftColumnsUp(), Juniper.Puzzles.Puzzle.Swap(), Juniper.Puzzles.Puzzle.ToString(), and Juniper.Puzzles.TetrisGame.Update().
RowOrder
readonly bool Juniper.Puzzles.Puzzle.RowOrder = true static
Definition at line 14 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.Swap(), and Juniper.Puzzles.TetrisGame.Update().
Width
int Juniper.Puzzles.Puzzle.Width => grid.GetWidth()
Gets the width of the puzzle grid
Definition at line 69 of file Puzzle.cs.
Referenced by Juniper.Puzzles.Puzzle.Clear(), Juniper.Puzzles.Puzzle.CompareTo(), Juniper.Console.IConsoleBufferExt.DrawPuzzle(), Juniper.Puzzles.Puzzle.Fill(), Juniper.Puzzles.Puzzle.IsEmpty(), Juniper.Puzzles.Puzzle.IsFull(), Juniper.Puzzles.Puzzle.IsInBounds(), Juniper.Puzzles.TetrisGame.Reset(), Juniper.Puzzles.Puzzle.Rotate(), Juniper.Puzzles.Puzzle.ShiftColumnsDown(), Juniper.Puzzles.Puzzle.ShiftColumnsLeft(), Juniper.Puzzles.Puzzle.ShiftColumnsRight(), Juniper.Puzzles.Puzzle.ShiftColumnsUp(), Juniper.Puzzles.Puzzle.Swap(), Juniper.Puzzles.TetrisGame.TetrisClearRow(), Juniper.Puzzles.Puzzle.ToString(), and Juniper.Puzzles.TetrisGame.Update().
Property Documentation
Grid
int [,] Juniper.Puzzles.Puzzle.Grid get set
Gets or sets the raw puzzle grid array
Definition at line 105 of file Puzzle.cs.
         {
             get
             {
                 return grid;
             }
             set
             {
                 if (value != null && value.GetWidth() != 0 && value.GetHeight() != 0)
                 {
                     grid = new int[value.GetWidth(), value.GetHeight()];
                     Array.Copy(value, grid, value.Length);
                 }
                 else
                 {
                     throw new ArgumentException("Invalid initialization grid");
                 }
             }
         }
Referenced by Juniper.Puzzles.Puzzle.Puzzle().
this[int x, int y]
int Juniper.Puzzles.Puzzle.this[int x, int y] get set
Gets or sets a specific value on the puzzle grid
Parameters
x
y
Returns
Definition at line 82 of file Puzzle.cs.
         {
             get
             {
                 if (IsInBounds(x, y))
                 {
                     return grid[x, y];
                 }
                 return EmptyTile;
             }
             set
             {
                 if (IsInBounds(x, y))
                 {
                     grid[x, y] = value;
                 }
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Puzzles/Puzzle.cs