Juniper: Hjg.Pngcs.Chunks.PngChunkSPLT Class Reference
Hjg.Pngcs.Chunks.PngChunkSPLT Class Reference
sPLT chunk: http://www.w3.org/TR/PNG/#11sPLT
Public Types
enum ChunkOrderingConstraint {
ChunkOrderingConstraint.NONE, ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT, ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT, ChunkOrderingConstraint.BEFORE_IDAT,
ChunkOrderingConstraint.NA
}
Restrictions for chunk ordering, for ancillary chunks
Public Member Functions
PngChunkSPLT (ImageInfo info)
override ChunkOrderingConstraint GetOrderingConstraint ()
Get ordering constrain
override ChunkRaw CreateRawChunk ()
Serialization. Creates a Raw chunk, ready for write, from this chunk content
override void ParseFromRaw (ChunkRaw c)
Deserialization. Given a Raw chunk, just rad, fills this chunk content
override void CloneDataFromRead (AbstractPngChunk other)
Override to make a copy (normally deep) from other chunk
int GetNentries ()
sealed override bool AllowsMultiple ()
This is implemented in PngChunkMultiple/PngChunSingle
ChunkRaw CreateEmptyChunk (int len, bool alloc)
override string ToString ()
Basic info: Id, length, Type name
Static Public Member Functions
static void FactoryRegister (string chunkId, Type type)
Registers a Chunk ID in the factory, to instantiate a given type
static T CloneChunk< T > (T chunk, ImageInfo info)
Public Attributes
const string ID = ChunkHelper.sPLT
Properties
string PalName [get, set]
Must be unique in image
int SampleDepth [get, set]
8-16
int [] Palette [get, set]
5 elements per entry
string Id [get]
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
bool Crit [get]
Standard basic properties, implicit in the Id
bool Pub [get]
bool Safe [get]
ImageInfo ImgInfo [get]
Image basic info, mostly for some checks
bool Priority [get, set]
For writing. Queued chunks with high priority will be written as soon as possible
int ChunkGroup [get, set]
Chunk group where it was read or writen
int Length [get, set]
long Offset [get, set]
Private Member Functions
void CloneData (PngChunkSPLT other)
Detailed Description
sPLT chunk: http://www.w3.org/TR/PNG/#11sPLT
Definition at line 8 of file PngChunkSPLT.cs.
Member Enumeration Documentation
ChunkOrderingConstraint
enum Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkOrderingConstraint strong inherited
Restrictions for chunk ordering, for ancillary chunks
Enumerator
NONE
No constraint, the chunk can go anywhere
BEFORE_PLTE_AND_IDAT
Before PLTE (palette) - and hence, also before IDAT
AFTER_PLTE_BEFORE_IDAT
After PLTE (palette), but before IDAT
BEFORE_IDAT
Before IDAT (before or after PLTE)
NA
Does not apply
Definition at line 55 of file AbstractPngChunk.cs.
         {
             /// <summary>
             /// No constraint, the chunk can go anywhere
             /// </summary>
             NONE,
             /// <summary>
             /// Before PLTE (palette) - and hence, also before IDAT
             /// </summary>
             BEFORE_PLTE_AND_IDAT,
             /// <summary>
             /// After PLTE (palette), but before IDAT
             /// </summary>
             AFTER_PLTE_BEFORE_IDAT,
             /// <summary>
             /// Before IDAT (before or after PLTE)
             /// </summary>
             BEFORE_IDAT,
             /// <summary>
             /// Does not apply
             /// </summary>
             NA
         }
Constructor & Destructor Documentation
PngChunkSPLT()
Hjg.Pngcs.Chunks.PngChunkSPLT.PngChunkSPLT (ImageInfo info) inline
Definition at line 27 of file PngChunkSPLT.cs.
             : base(ID, info)
         {
             PalName = "";
         }
References Hjg.Pngcs.Chunks.PngChunkSPLT.PalName.
Member Function Documentation
AllowsMultiple()
sealed override bool Hjg.Pngcs.Chunks.PngChunkMultiple.AllowsMultiple () inline virtual inherited
This is implemented in PngChunkMultiple/PngChunSingle
Returns
Allows more than one chunk of this type in a image
Implements Hjg.Pngcs.Chunks.AbstractPngChunk.
Definition at line 13 of file PngChunkMultiple.cs.
         {
             return true;
         }
CloneChunk< T >()
static T Hjg.Pngcs.Chunks.AbstractPngChunk.CloneChunk< T > (T chunk, ImageInfo info) inline static inherited
Type Constraints
T : AbstractPngChunk
Definition at line 217 of file AbstractPngChunk.cs.
                                                                        : AbstractPngChunk
         {
             if (chunk is null)
             {
                 throw new ArgumentNullException(nameof(chunk));
             }
             var cn = FactoryFromId(chunk.Id, info);
             if (cn.GetType() != (object)chunk.GetType())
             {
                 throw new PngjException("bad class cloning chunk: " + cn.GetType() + " "
                         + chunk.GetType());
             }
             cn.CloneDataFromRead(chunk);
             return (T)cn;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId().
CloneData()
void Hjg.Pngcs.Chunks.PngChunkSPLT.CloneData (PngChunkSPLT other) inline private
Definition at line 138 of file PngChunkSPLT.cs.
         {
             if (other is null)
             {
                 throw new System.ArgumentNullException(nameof(other));
             }
             PalName = other.PalName;
             SampleDepth = other.SampleDepth;
             Palette = new int[other.Palette.Length];
             System.Array.Copy(other.Palette, 0, Palette, 0, Palette.Length);
         }
References Hjg.Pngcs.Chunks.PngChunkSPLT.Palette, Hjg.Pngcs.Chunks.PngChunkSPLT.PalName, and Hjg.Pngcs.Chunks.PngChunkSPLT.SampleDepth.
Referenced by Hjg.Pngcs.Chunks.PngChunkSPLT.CloneDataFromRead().
CloneDataFromRead()
override void Hjg.Pngcs.Chunks.PngChunkSPLT.CloneDataFromRead (AbstractPngChunk other) inline virtual
Override to make a copy (normally deep) from other chunk
Parameters
other
Implements Hjg.Pngcs.Chunks.AbstractPngChunk.
Definition at line 133 of file PngChunkSPLT.cs.
         {
             CloneData((PngChunkSPLT)other);
         }
References Hjg.Pngcs.Chunks.PngChunkSPLT.CloneData().
CreateEmptyChunk()
ChunkRaw Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk (int len, bool alloc) inline inherited
Definition at line 209 of file AbstractPngChunk.cs.
         {
             var c = new ChunkRaw(len, ChunkHelper.ToBytes(Id), alloc);
             return c;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.Id, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
Referenced by Hjg.Pngcs.Chunks.PngChunkTEXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkUNKNOWN.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkGAMA.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkOFFS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSTER.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTIME.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSRGB.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPHYS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk().
CreateRawChunk()
override ChunkRaw Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk () inline virtual
Serialization. Creates a Raw chunk, ready for write, from this chunk content
Implements Hjg.Pngcs.Chunks.AbstractPngChunk.
Definition at line 38 of file PngChunkSPLT.cs.
         {
             using var ba = new MemoryStream();
             ChunkHelper.WriteBytesToStream(ba, ChunkHelper.ToBytes(PalName));
             ba.WriteByte(0); // separator
             ba.WriteByte((byte)SampleDepth);
             var nentries = GetNentries();
             for (var n = 0; n < nentries; n++)
             {
                 for (var i = 0; i < 4; i++)
                 {
                     if (SampleDepth == 8)
                     {
                         PngHelperInternal.WriteByte(ba, (byte)Palette[(n * 5) + i]);
                     }
                     else
                     {
                         PngHelperInternal.WriteInt2(ba, Palette[(n * 5) + i]);
                     }
                 }
                 PngHelperInternal.WriteInt2(ba, Palette[(n * 5) + 4]);
             }
             var b = ba.ToArray();
             var chunk = CreateEmptyChunk(b.Length, false);
             chunk.Data = b;
             return chunk;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.GetNentries(), Hjg.Pngcs.Chunks.PngChunkSPLT.Palette, Hjg.Pngcs.Chunks.PngChunkSPLT.PalName, Hjg.Pngcs.Chunks.PngChunkSPLT.SampleDepth, Hjg.Pngcs.Chunks.ChunkHelper.ToBytes(), Hjg.Pngcs.PngHelperInternal.WriteByte(), Hjg.Pngcs.Chunks.ChunkHelper.WriteBytesToStream(), and Hjg.Pngcs.PngHelperInternal.WriteInt2().
FactoryRegister()
static void Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryRegister (string chunkId, Type type) inline static inherited
Registers a Chunk ID in the factory, to instantiate a given type
This can be called by client code to register additional chunk types
Parameters
chunkId
type should extend PngChunkSingle or PngChunkMultiple
Definition at line 140 of file AbstractPngChunk.cs.
         {
             factoryMap.Add(chunkId, type);
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.factoryMap.
GetNentries()
int Hjg.Pngcs.Chunks.PngChunkSPLT.GetNentries () inline
Definition at line 151 of file PngChunkSPLT.cs.
         {
             return Palette.Length / 5;
         }
References Hjg.Pngcs.Chunks.PngChunkSPLT.Palette.
Referenced by Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk().
GetOrderingConstraint()
override ChunkOrderingConstraint Hjg.Pngcs.Chunks.PngChunkSPLT.GetOrderingConstraint () inline virtual
Get ordering constrain
Returns
Implements Hjg.Pngcs.Chunks.AbstractPngChunk.
Definition at line 33 of file PngChunkSPLT.cs.
         {
             return ChunkOrderingConstraint.BEFORE_IDAT;
         }
ParseFromRaw()
override void Hjg.Pngcs.Chunks.PngChunkSPLT.ParseFromRaw (ChunkRaw c) inline virtual
Deserialization. Given a Raw chunk, just rad, fills this chunk content
Implements Hjg.Pngcs.Chunks.AbstractPngChunk.
Definition at line 68 of file PngChunkSPLT.cs.
         {
             if (c is null)
             {
                 throw new System.ArgumentNullException(nameof(c));
             }
             var t = -1;
             for (var i = 0; i < c.Data.Length; i++)
             { // look for first zero
                 if (c.Data[i] == 0)
                 {
                     t = i;
                     break;
                 }
             }
             if (t <= 0 || t > c.Data.Length - 2)
             {
                 throw new PngjException("bad sPLT chunk: no separator found");
             }
             PalName = ChunkHelper.ToString(c.Data, 0, t);
             SampleDepth = PngHelperInternal.ReadInt1fromByte(c.Data, t + 1);
             t += 2;
             var nentries = (c.Data.Length - t) / (SampleDepth == 8 ? 6 : 10);
             Palette = new int[nentries * 5];
             int r;
             int g;
             int b;
             int a;
             int f;
             int ne;
             ne = 0;
             for (var i = 0; i < nentries; i++)
             {
                 if (SampleDepth == 8)
                 {
                     r = PngHelperInternal.ReadInt1fromByte(c.Data, t++);
                     g = PngHelperInternal.ReadInt1fromByte(c.Data, t++);
                     b = PngHelperInternal.ReadInt1fromByte(c.Data, t++);
                     a = PngHelperInternal.ReadInt1fromByte(c.Data, t++);
                 }
                 else
                 {
                     r = PngHelperInternal.ReadInt2fromBytes(c.Data, t);
                     t += 2;
                     g = PngHelperInternal.ReadInt2fromBytes(c.Data, t);
                     t += 2;
                     b = PngHelperInternal.ReadInt2fromBytes(c.Data, t);
                     t += 2;
                     a = PngHelperInternal.ReadInt2fromBytes(c.Data, t);
                     t += 2;
                 }
                 f = PngHelperInternal.ReadInt2fromBytes(c.Data, t);
                 t += 2;
                 Palette[ne++] = r;
                 Palette[ne++] = g;
                 Palette[ne++] = b;
                 Palette[ne++] = a;
                 Palette[ne++] = f;
             }
         }
References Hjg.Pngcs.Chunks.ChunkRaw.Data, Hjg.Pngcs.Chunks.PngChunkSPLT.Palette, Hjg.Pngcs.Chunks.PngChunkSPLT.PalName, Hjg.Pngcs.PngHelperInternal.ReadInt1fromByte(), Hjg.Pngcs.PngHelperInternal.ReadInt2fromBytes(), Hjg.Pngcs.Chunks.PngChunkSPLT.SampleDepth, and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
ToString()
override string Hjg.Pngcs.Chunks.AbstractPngChunk.ToString () inline inherited
Basic info: Id, length, Type name
Returns
Definition at line 250 of file AbstractPngChunk.cs.
         {
             return $"chunk id= {Id} (len={Length.ToString(CultureInfo.CurrentCulture)} off={Offset.ToString(CultureInfo.CurrentCulture)}) c={GetType().Name}";
         }
Member Data Documentation
ID
const string Hjg.Pngcs.Chunks.PngChunkSPLT.ID = ChunkHelper.sPLT
Definition at line 10 of file PngChunkSPLT.cs.
Property Documentation
ChunkGroup
int Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkGroup get set inherited
Chunk group where it was read or writen
Definition at line 47 of file AbstractPngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
Crit
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Crit get inherited
Standard basic properties, implicit in the Id
Definition at line 30 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), and Hjg.Pngcs.PngReader.ReadChunk().
Id
string Hjg.Pngcs.Chunks.AbstractPngChunk.Id get inherited
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
Definition at line 25 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkSingle.Equals(), Hjg.Pngcs.Chunks.ChunkHelper.Equivalent(), Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode(), Hjg.Pngcs.Chunks.ChunkPredicateId.Matches(), Hjg.Pngcs.Chunks.ChunkPredicateId2.Matches(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
ImgInfo
ImageInfo Hjg.Pngcs.Chunks.AbstractPngChunk.ImgInfo get protected inherited
Image basic info, mostly for some checks
Definition at line 37 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetGray(), Hjg.Pngcs.Chunks.PngChunkSBIT.GetLen(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetRGB(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetRGB(), Hjg.Pngcs.Chunks.PngChunkSBIT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkHIST.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTRNS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetIndexEntryAsTransparent(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetRGB(), and Hjg.Pngcs.Chunks.PngChunkBKGD.SetRGB().
Length
int Hjg.Pngcs.Chunks.AbstractPngChunk.Length get set inherited
Definition at line 49 of file AbstractPngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.AbstractPngChunk.Factory(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), and Hjg.Pngcs.Chunks.PngChunkSkipped.PngChunkSkipped().
Offset
long Hjg.Pngcs.Chunks.AbstractPngChunk.Offset get set inherited
Definition at line 50 of file AbstractPngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), and Hjg.Pngcs.PngReader.ReadChunk().
Palette
int [] Hjg.Pngcs.Chunks.PngChunkSPLT.Palette get set
5 elements per entry
Definition at line 25 of file PngChunkSPLT.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.PngChunkSPLT.CloneData(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.GetNentries(), and Hjg.Pngcs.Chunks.PngChunkSPLT.ParseFromRaw().
PalName
string Hjg.Pngcs.Chunks.PngChunkSPLT.PalName get set
Must be unique in image
Definition at line 15 of file PngChunkSPLT.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.PngChunkSPLT.CloneData(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), Hjg.Pngcs.Chunks.ChunkPredicateId2.Matches(), Hjg.Pngcs.Chunks.PngChunkSPLT.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkSPLT.PngChunkSPLT().
Priority
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Priority get set inherited
For writing. Queued chunks with high priority will be written as soon as possible
Definition at line 42 of file AbstractPngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
Pub
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Pub get inherited
Definition at line 31 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk().
Safe
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Safe get inherited
Definition at line 32 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk().
SampleDepth
int Hjg.Pngcs.Chunks.PngChunkSPLT.SampleDepth get set
8-16
Definition at line 20 of file PngChunkSPLT.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.PngChunkSPLT.CloneData(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSPLT.ParseFromRaw().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Chunks/PngChunkSPLT.cs