Juniper: Juniper.World.GIS.DatumWGS_84 Class Reference
Juniper.World.GIS.DatumWGS_84 Class Reference
A model of the Earth.
Public Attributes
const double FalseNorthing = 10000000.0
const double equatorialRadius = 6378137
const double pointScaleFactor = 0.9996
const double E0 = 500000
const double A = (equatorialRadius / (1 + n)) * (1 + (n * n / 4) + (n * n * n * n / 64))
const double flattening = 1 / invF
Static Public Attributes
static readonly double e = Sqrt(1 - (flatteningComp * flatteningComp))
static readonly double esq = 1 - (flatteningComp * flatteningComp)
static readonly double e0sq = e * e / (1 - (e * e))
static readonly double alpha1 = 1 - (esq * ((1.0 / 4.0) + (esq * ((3.0 / 64.0) + (5.0 * esq / 256.0)))))
static readonly double alpha2 = esq * ((3.0 / 8.0) + (esq * ((3.0 / 32.0) + (45.0 * esq / 1024.0))))
static readonly double alpha3 = esq * esq * ((15.0 / 256.0) + (esq * 45.0 / 1024.0))
static readonly double alpha4 = esq * esq * esq * (35.0 / 3072.0)
static readonly double [] beta
static readonly double [] delta
Private Attributes
const double invF = 298.257223563
const double n = flattening / (2 - flattening)
const double flatteningComp = 1 - flattening
Detailed Description
A model of the Earth.
Definition at line 8 of file Datum.cs.
Member Data Documentation
A
const double Juniper.World.GIS.DatumWGS_84.A = (equatorialRadius / (1 + n)) * (1 + (n * n / 4) + (n * n * n * n / 64))
Definition at line 16 of file Datum.cs.
Referenced by Juniper.Units.UTM.ToLatLng().
alpha1
readonly double Juniper.World.GIS.DatumWGS_84.alpha1 = 1 - (esq * ((1.0 / 4.0) + (esq * ((3.0 / 64.0) + (5.0 * esq / 256.0))))) static
Definition at line 25 of file Datum.cs.
Referenced by Juniper.Units.LatLng.ToUTM().
alpha2
readonly double Juniper.World.GIS.DatumWGS_84.alpha2 = esq * ((3.0 / 8.0) + (esq * ((3.0 / 32.0) + (45.0 * esq / 1024.0)))) static
Definition at line 26 of file Datum.cs.
Referenced by Juniper.Units.LatLng.ToUTM().
alpha3
readonly double Juniper.World.GIS.DatumWGS_84.alpha3 = esq * esq * ((15.0 / 256.0) + (esq * 45.0 / 1024.0)) static
Definition at line 27 of file Datum.cs.
Referenced by Juniper.Units.LatLng.ToUTM().
alpha4
readonly double Juniper.World.GIS.DatumWGS_84.alpha4 = esq * esq * esq * (35.0 / 3072.0) static
Definition at line 28 of file Datum.cs.
Referenced by Juniper.Units.LatLng.ToUTM().
beta
readonly double [] Juniper.World.GIS.DatumWGS_84.beta static
Initial value:
= {
            (n / 2) - (2 * n * n / 3) + (37 * n * n * n / 96),
            (n * n / 48) + (n * n * n / 15),
            17 * n * n * n / 480
        }
Definition at line 30 of file Datum.cs.
Referenced by Juniper.Units.UTM.ToLatLng().
delta
readonly double [] Juniper.World.GIS.DatumWGS_84.delta static
Initial value:
= {
            (2 * n) - (2 * n * n / 3),
            (7 * n * n / 3) - (8 * n * n * n / 5),
            56 * n * n * n / 15
        }
Definition at line 36 of file Datum.cs.
Referenced by Juniper.Units.UTM.ToLatLng().
e
readonly double Juniper.World.GIS.DatumWGS_84.e = Sqrt(1 - (flatteningComp * flatteningComp)) static
Definition at line 21 of file Datum.cs.
Referenced by Juniper.Units.LatLng.ToUTM().
E0
const double Juniper.World.GIS.DatumWGS_84.E0 = 500000
Definition at line 14 of file Datum.cs.
Referenced by Juniper.Units.UTM.ToLatLng(), and Juniper.Units.LatLng.ToUTM().
e0sq
readonly double Juniper.World.GIS.DatumWGS_84.e0sq = e * e / (1 - (e * e)) static
Definition at line 23 of file Datum.cs.
Referenced by Juniper.Units.LatLng.ToUTM().
equatorialRadius
const double Juniper.World.GIS.DatumWGS_84.equatorialRadius = 6378137
Definition at line 12 of file Datum.cs.
Referenced by Juniper.World.GIS.LatLngPointExt.SphericalMercator(), and Juniper.Units.LatLng.ToUTM().
esq
readonly double Juniper.World.GIS.DatumWGS_84.esq = 1 - (flatteningComp * flatteningComp) static
Definition at line 22 of file Datum.cs.
FalseNorthing
const double Juniper.World.GIS.DatumWGS_84.FalseNorthing = 10000000.0
Definition at line 10 of file Datum.cs.
Referenced by Juniper.Units.UTM.ToLatLng(), and Juniper.Units.LatLng.ToUTM().
flattening
const double Juniper.World.GIS.DatumWGS_84.flattening = 1 / invF
Definition at line 17 of file Datum.cs.
flatteningComp
const double Juniper.World.GIS.DatumWGS_84.flatteningComp = 1 - flattening private
Definition at line 19 of file Datum.cs.
invF
const double Juniper.World.GIS.DatumWGS_84.invF = 298.257223563 private
Definition at line 11 of file Datum.cs.
n
const double Juniper.World.GIS.DatumWGS_84.n = flattening / (2 - flattening) private
Definition at line 18 of file Datum.cs.
pointScaleFactor
const double Juniper.World.GIS.DatumWGS_84.pointScaleFactor = 0.9996
Definition at line 13 of file Datum.cs.
Referenced by Juniper.Units.UTM.ToLatLng().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/World/GIS/Datum.cs