Juniper: Juniper.Unity.JuniperPlatform Class Reference
Juniper.Unity.JuniperPlatform Class Reference
Public Member Functions
void Awake ()
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
virtual void Reinstall ()
void Reset ()
void OnValidate ()
void Install (bool reset)
void Uninstall ()
Static Public Member Functions
static JuniperPlatform Ensure ()
Public Attributes
PlatformTypes CurrentPlatform
SystemTypes System
DisplayTypes DisplayType
DisplayTypes SupportedDisplayType
AugmentedRealityTypes ARMode
AugmentedRealityTypes SupportedARMode
Options Option
Static Public Attributes
static readonly PlatformTypes CURRENT_PLATFORM
Properties
static bool VRPlatformHasPassthrough [get]
static bool IsARCapablePlatform [get]
Detailed Description
Definition at line 12 of file JuniperPlatform.cs.
Member Function Documentation
Awake()
void Juniper.Unity.JuniperPlatform.Awake () inline
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
Definition at line 146 of file JuniperPlatform.cs.
         {
             var scenes = ComponentExt.FindAny<MasterSceneController>();
             if (scenes != null && scenes.gameObject.scene != gameObject.scene)
             {
                 gameObject.Destroy();
             }
             else
             {
                 Install(false);
             }
         }
References Juniper.Unity.JuniperPlatform.Install().
Ensure()
static JuniperPlatform Juniper.Unity.JuniperPlatform.Ensure () inline static
Definition at line 112 of file JuniperPlatform.cs.
         {
             var head = DisplayManager.MainCamera?.transform;
             if (head == null)
             {
                 head = new GameObject().AddComponent<Camera>().transform;
                 head.gameObject.tag = "MainCamera";
             }
             head.gameObject.name = "Head (Camera)";
             var stage = head.parent;
             if (stage == null)
             {
                 stage = new GameObject("Stage").transform;
                 head.Reparent(stage);
             }
             var userRig = stage.parent;
             if (userRig == null)
             {
                 userRig = new GameObject("UserRig").transform;
                 stage.Reparent(userRig);
             }
             return userRig.EnsureComponent<JuniperPlatform>();
         }
References Juniper.Unity.Display.AbstractDisplayManager.MainCamera.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Install(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareScene().
Install()
void Juniper.Unity.JuniperPlatform.Install (bool reset) inline
Implements Juniper.IInstallable.
Definition at line 184 of file JuniperPlatform.cs.
         {
             reset &= Application.isEditor;
 #if UNITY_EDITOR
             OnValidate();
 #endif
             this.EnsureComponent<EventSystem>();
             this.EnsureComponent<UnifiedInputModule>();
             this.EnsureComponent<AnchorStore>();
             this.EnsureComponent<InteractionAudio>();
             this.EnsureComponent<MasterSceneController>();
             this.EnsureComponent<PermissionHandler>();
             DisplayManager.MainCamera.transform.parent.EnsureComponent<StageExtensions>();
             DisplayManager.MainCamera.EnsureComponent<DisplayManager>();
         }
References Juniper.Unity.Display.AbstractDisplayManager.MainCamera, and Juniper.Unity.JuniperPlatform.OnValidate().
Referenced by Juniper.Unity.JuniperPlatform.Awake(), and Juniper.Unity.JuniperPlatform.Reinstall().
OnValidate()
void Juniper.Unity.JuniperPlatform.OnValidate () inline
Definition at line 171 of file JuniperPlatform.cs.
         {
             CurrentPlatform = CURRENT_PLATFORM;
             System = Platform.GetSystem(CURRENT_PLATFORM);
             SupportedDisplayType = Platform.GetDisplayType(CURRENT_PLATFORM);
             SupportedARMode = Platform.GetARType(CURRENT_PLATFORM);
             Option = Platform.GetOption(CURRENT_PLATFORM);
             DisplayType = DisplayTypes.Monoscopic;
             ARMode = AugmentedRealityTypes.None;
         }
References Juniper.Unity.JuniperPlatform.ARMode, Juniper.Unity.JuniperPlatform.CURRENT_PLATFORM, Juniper.Unity.JuniperPlatform.CurrentPlatform, Juniper.Unity.JuniperPlatform.DisplayType, Juniper.Platform.GetARType(), Juniper.Platform.GetDisplayType(), Juniper.Platform.GetOption(), Juniper.Platform.GetSystem(), Juniper.Unity.JuniperPlatform.Option, Juniper.Unity.JuniperPlatform.SupportedARMode, and Juniper.Unity.JuniperPlatform.SupportedDisplayType.
Referenced by Juniper.Unity.JuniperPlatform.Install().
Reinstall()
virtual void Juniper.Unity.JuniperPlatform.Reinstall () inline virtual
Implements Juniper.IInstallable.
Definition at line 159 of file JuniperPlatform.cs.
         {
             Install(true);
         }
References Juniper.Unity.JuniperPlatform.Install().
Referenced by Juniper.Unity.JuniperPlatform.Reset().
Reset()
void Juniper.Unity.JuniperPlatform.Reset () inline
Definition at line 166 of file JuniperPlatform.cs.
         {
             Reinstall();
         }
References Juniper.Unity.JuniperPlatform.Reinstall().
Uninstall()
void Juniper.Unity.JuniperPlatform.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 203 of file JuniperPlatform.cs.
         {
         }
Member Data Documentation
ARMode
AugmentedRealityTypes Juniper.Unity.JuniperPlatform.ARMode
Definition at line 104 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Awake(), Juniper.Unity.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Unity.Animation.FadeTransition.OnEntered(), Juniper.Unity.Animation.FadeTransition.OnExiting(), Juniper.Unity.JuniperPlatform.OnValidate(), Juniper.Unity.Display.AbstractDisplayManager.ToggleAR(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
CURRENT_PLATFORM
readonly PlatformTypes Juniper.Unity.JuniperPlatform.CURRENT_PLATFORM static
Initial value:
=
            PlatformTypes.AndroidARCore
Definition at line 14 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.JuniperPlatform.OnValidate(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
CurrentPlatform
PlatformTypes Juniper.Unity.JuniperPlatform.CurrentPlatform
Definition at line 92 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.JuniperPlatform.OnValidate(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
DisplayType
DisplayTypes Juniper.Unity.JuniperPlatform.DisplayType
Definition at line 98 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Awake(), Juniper.Unity.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Unity.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Unity.JuniperPlatform.OnValidate(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
Option
Options Juniper.Unity.JuniperPlatform.Option
Definition at line 110 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Awake(), Juniper.Unity.JuniperPlatform.OnValidate(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
SupportedARMode
AugmentedRealityTypes Juniper.Unity.JuniperPlatform.SupportedARMode
Definition at line 107 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.JuniperPlatform.OnValidate(), and Juniper.Unity.Display.AbstractDisplayManager.StartAR().
SupportedDisplayType
DisplayTypes Juniper.Unity.JuniperPlatform.SupportedDisplayType
Definition at line 101 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.JuniperPlatform.OnValidate(), and Juniper.Unity.Display.AbstractDisplayManager.StartXRDisplay().
System
SystemTypes Juniper.Unity.JuniperPlatform.System
Definition at line 95 of file JuniperPlatform.cs.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Awake(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
Property Documentation
IsARCapablePlatform
bool Juniper.Unity.JuniperPlatform.IsARCapablePlatform static get
Definition at line 78 of file JuniperPlatform.cs.
         {
             get
             {
                 return CURRENT_PLATFORM == PlatformTypes.UWP
                     || CURRENT_PLATFORM == PlatformTypes.IOS
                     || CURRENT_PLATFORM == PlatformTypes.IOSARKit
                     || CURRENT_PLATFORM == PlatformTypes.Android
                     || CURRENT_PLATFORM == PlatformTypes.AndroidARCore
                     || CURRENT_PLATFORM == PlatformTypes.MagicLeap
                     || CURRENT_PLATFORM == PlatformTypes.UWPHoloLens;
             }
         }
Referenced by Juniper.Unity.Display.AbstractDisplayManager.ChangeDisplayType().
VRPlatformHasPassthrough
bool Juniper.Unity.JuniperPlatform.VRPlatformHasPassthrough static get
Definition at line 67 of file JuniperPlatform.cs.
         {
             get
             {
                 return CURRENT_PLATFORM == PlatformTypes.AndroidDaydream
                     || CURRENT_PLATFORM == PlatformTypes.AndroidViveFocus
                     || CURRENT_PLATFORM == PlatformTypes.StandaloneSteamVR
                     || CURRENT_PLATFORM == PlatformTypes.UWPWindowsMR;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/JuniperPlatform.cs