Juniper: Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType > Class Template Reference
Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType > Class Template Reference abstract
A store for points in space that the system will restore on second-run.
Public Member Functions
virtual void ResetData ()
Delete saved anchors, if there are any.
bool DropAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
void WeighAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
abstract bool HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
Protected Member Functions
virtual AnchorType SaveAnchor (string ID, GameObject gameObject)
virtual bool IsGood (AnchorType anchor)
virtual void DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor)
virtual AnchorType FindAnchor (GameObject gameObject)
virtual bool IsSaved (AnchorType anchor)
abstract AnchorType CreateAnchor (string ID, GameObject gameObject)
abstract AnchorType LoadAnchor (string ID)
Static Protected Member Functions
static string MakeID (string name)
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
static bool HasValue (string name)
static void SaveValue (string name, object value)
Saves a value to PlayerPrefs.
static T LoadValue< T > (string name)
Gets a value back out of PlayerPrefs.
static bool DeleteValue (string name)
Removes a value from the PlayerPrefs.
Properties
static string [] NameList [get, set]
A list of all keys for all objects stored in PlayerPrefs along with the anchor store.
Static Private Attributes
static readonly string ID_PREFIX = typeof(AbstractAnchorStore<AnchorType>).FullName + "::"
A prefix to add to names to make IDs unique to AbstractAnchorStore.
static readonly string KEY_LIST_KEY = MakeID("KEY_LIST")
The place where the names of all of the saved values are stored.
static readonly string [] EMPTY_STRING_ARRAY = new string[0]
An empty array for returning without creating the empty array all the time.
Detailed Description
A store for points in space that the system will restore on second-run.
Type Constraints
AnchorType : MonoBehaviour
Definition at line 12 of file AbstractAnchorStore.cs.
Member Function Documentation
CreateAnchor()
abstract AnchorType Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.CreateAnchor (string ID, GameObject gameObject) protected pure virtual
Implemented in Juniper.Unity.Anchoring.ARKitAnchorStore, and Juniper.Unity.Anchoring.MockAnchorStore.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
DeleteAnchor()
virtual void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor) inline protected virtual
Reimplemented in Juniper.Unity.Anchoring.ARKitAnchorStore, and Juniper.Unity.Anchoring.ARCoreAnchorStore.
Definition at line 225 of file AbstractAnchorStore.cs.
         {
             DeleteValue(ID);
             anchor.Destroy();
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue().
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor().
DeleteValue()
static bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue (string name) inline static protected
Removes a value from the PlayerPrefs.
Parameters
name
Returns
Definition at line 125 of file AbstractAnchorStore.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 PlayerPrefs.DeleteKey(key);
                 NameList = NameList.Where(k => k != name).ToArray();
                 return true;
             }
             else
             {
                 return false;
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.NameList.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.ResetData(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor().
DropAnchor()
bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor (string ID, GameObject gameObject) inline
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
Returns
true, if anchor existed on the object, existed in the datastore, or was successfully created, false otherwise.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 165 of file AbstractAnchorStore.cs.
         {
             if (string.IsNullOrEmpty(ID))
             {
                 throw new ArgumentException("Parameter must have a value.", nameof(ID));
             }
             var anchor = FindAnchor(gameObject);
             if (!IsSaved(anchor))
             {
                 anchor = SaveAnchor(ID, gameObject);
             }
             return IsGood(anchor);
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.FindAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsGood(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsSaved(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
Referenced by Juniper.Unity.Anchoring.Anchored.DropAnchor().
FindAnchor()
virtual AnchorType Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.FindAnchor (GameObject gameObject) inline protected virtual
Reimplemented in Juniper.Unity.Anchoring.ARKitAnchorStore.
Definition at line 231 of file AbstractAnchorStore.cs.
         {
             return gameObject?.GetComponent<AnchorType>();
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor().
HasAnchor()
abstract bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasAnchor (string anchorID) pure virtual
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
Returns
true, if anchor exists, false otherwise.
Parameters
anchorID Anchor identifier.
Implemented in Juniper.Unity.Anchoring.ARKitAnchorStore, Juniper.Unity.Anchoring.ARCoreAnchorStore, and Juniper.Unity.Anchoring.MockAnchorStore.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
HasValue()
static bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasValue (string name) inline static protected
Definition at line 76 of file AbstractAnchorStore.cs.
         {
             return PlayerPrefs.HasKey(MakeID(name));
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID().
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
IsGood()
virtual bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsGood (AnchorType anchor) inline protected virtual
Definition at line 202 of file AbstractAnchorStore.cs.
         {
             return anchor != null;
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor().
IsSaved()
virtual bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsSaved (AnchorType anchor) inline protected virtual
Definition at line 236 of file AbstractAnchorStore.cs.
         {
             return anchor != null;
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor().
LoadAnchor()
abstract AnchorType Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadAnchor (string ID) protected pure virtual
Implemented in Juniper.Unity.Anchoring.ARKitAnchorStore, Juniper.Unity.Anchoring.ARCoreAnchorStore, and Juniper.Unity.Anchoring.MockAnchorStore.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
LoadValue< T >()
static T Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadValue< T > (string name) inline static protected
Gets a value back out of PlayerPrefs.
Template Parameters
T
Parameters
name
Returns
Definition at line 107 of file AbstractAnchorStore.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 return JsonConvert.DeserializeObject<T>(PlayerPrefs.GetString(key));
             }
             else
             {
                 return default(T);
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID().
MakeID()
static string Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID (string name) inline static protected
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
Parameters
name A controllable part of the name, to be modified to be unique in PlayerPrefs.
Returns
A name in PlayerPrefs unique to AbstractAnchorStore.
Definition at line 28 of file AbstractAnchorStore.cs.
         {
             return ID_PREFIX + name;
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.ID_PREFIX.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadValue< T >(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue().
ResetData()
virtual void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.ResetData () inline virtual
Delete saved anchors, if there are any.
Reimplemented in Juniper.Unity.Anchoring.ARKitAnchorStore, Juniper.Unity.Anchoring.ARCoreAnchorStore, and Juniper.Unity.Anchoring.MockAnchorStore.
Definition at line 143 of file AbstractAnchorStore.cs.
         {
             foreach (var name in NameList)
             {
                 DeleteValue(name);
             }
             NameList = null;
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.NameList.
SaveAnchor()
virtual AnchorType Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor (string ID, GameObject gameObject) inline protected virtual
Reimplemented in Juniper.Unity.Anchoring.ARKitAnchorStore, and Juniper.Unity.Anchoring.ARCoreAnchorStore.
Definition at line 181 of file AbstractAnchorStore.cs.
         {
             var scaleID = ID + "-scale";
             AnchorType anchor;
             if (HasAnchor(ID))
             {
                 anchor = LoadAnchor(ID);
                 if (HasValue(scaleID))
                 {
                     gameObject.transform.localScale = LoadValue<Vector3>(scaleID);
                 }
             }
             else
             {
                 anchor = CreateAnchor(ID, gameObject);
                 SaveValue(scaleID, gameObject.transform.localScale);
             }
             return anchor;
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.CreateAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadAnchor(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue().
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor().
SaveValue()
static void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue (string name, object value) inline static protected
Saves a value to PlayerPrefs.
Parameters
name The name of the object to save.
value The value to save.
Definition at line 86 of file AbstractAnchorStore.cs.
         {
             PlayerPrefs.SetString(MakeID(name), JsonConvert.SerializeObject(value));
             var names = NameList;
             if (names.Contains(name))
             {
                 PlayerPrefs.Save();
             }
             else
             {
                 NameList = names.Append(name).ToArray();
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.NameList.
Referenced by Juniper.Unity.Anchoring.MockAnchorStore.CreateAnchor(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
WeighAnchor()
void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor (string ID, GameObject gameObject) inline
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 215 of file AbstractAnchorStore.cs.
         {
             var anchor = FindAnchor(gameObject);
             if (anchor != null)
             {
                 DeleteAnchor(ID, gameObject, anchor);
                 DeleteValue(ID + "-scale");
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.FindAnchor().
Referenced by Juniper.Unity.Anchoring.Anchored.WeighAnchor().
Member Data Documentation
EMPTY_STRING_ARRAY
readonly string [] Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.EMPTY_STRING_ARRAY = new string[0] static private
An empty array for returning without creating the empty array all the time.
Definition at line 41 of file AbstractAnchorStore.cs.
ID_PREFIX
readonly string Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.ID_PREFIX = typeof(AbstractAnchorStore<AnchorType>).FullName + "::" static private
A prefix to add to names to make IDs unique to AbstractAnchorStore.
Definition at line 19 of file AbstractAnchorStore.cs.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID().
KEY_LIST_KEY
readonly string Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.KEY_LIST_KEY = MakeID("KEY_LIST") static private
The place where the names of all of the saved values are stored.
Definition at line 36 of file AbstractAnchorStore.cs.
Property Documentation
NameList
string [] Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.NameList static get set private
A list of all keys for all objects stored in PlayerPrefs along with the anchor store.
Definition at line 47 of file AbstractAnchorStore.cs.
         {
             get
             {
                 if (PlayerPrefs.HasKey(KEY_LIST_KEY))
                 {
                     return JsonConvert.DeserializeObject<string[]>(PlayerPrefs.GetString(KEY_LIST_KEY));
                 }
                 else
                 {
                     return EMPTY_STRING_ARRAY;
                 }
             }
             set
             {
                 if (value == null)
                 {
                     PlayerPrefs.DeleteKey(KEY_LIST_KEY);
                 }
                 else
                 {
                     PlayerPrefs.SetString(KEY_LIST_KEY, JsonConvert.SerializeObject(value));
                 }
                 PlayerPrefs.Save();
             }
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.ResetData(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Anchoring/AbstractAnchorStore.cs