Juniper: Juniper.Unity.Widgets.ListView Class Reference
Juniper.Unity.Widgets.ListView Class Reference
Public Types
enum SelectionMode { SelectionMode.None, SelectionMode.Single, SelectionMode.SingleToggle, SelectionMode.Multiple }
Public Member Functions
void Awake ()
void Clear ()
ListViewItem GetItem (string key)
bool ContainsItem (string key)
void AddItems< T > (IEnumerable< T > items, Func< T, string > getKey, Func< T, string > getText)
ListViewItem AddItem (string text, object dataItem, string key)
void ClearSelection ()
void SetSelection (IEnumerable< string > keys)
void SetSelection (string key)
void RemoveItem (string key)
Public Attributes
SelectionMode selectionMode = SelectionMode.Single
Font font
int fontSize = 24
Color normalBackgroundColor = Color.grey
Color highlightBackgroundColor = Color.Lerp(Color.white, Color.grey, 0.5f)
Color normalColor = Color.white
Color disabledColor = Color.grey
Color highlightColor = Color.black
UnityEvent onSelectionChanged
Properties
List< ListViewItem > Items = new List<ListViewItem>(10) [get]
List< ListViewItem > Selection = new List<ListViewItem>(10) [get]
ListViewItem FirstSelectedItem [get]
ScrollRect Container [get]
Private Member Functions
void ChangeSelection (ListViewItem selected)
void SetSelection (List< ListViewItem > newSelection)
Private Attributes
int count
Static Private Attributes
static readonly List< ListViewItem > EMPTY_SELECTION = new List<ListViewItem>()
Detailed Description
Definition at line 11 of file ListView.cs.
Member Enumeration Documentation
SelectionMode
enum Juniper.Unity.Widgets.ListView.SelectionMode strong
Enumerator
None
Single
SingleToggle
Multiple
Definition at line 23 of file ListView.cs.
         {
             None,
             Single,
             SingleToggle,
             Multiple
         }
Member Function Documentation
AddItem()
ListViewItem Juniper.Unity.Widgets.ListView.AddItem (string text, object dataItem, string key) inline
Definition at line 77 of file ListView.cs.
         {
             var item = new GameObject().AddComponent<ListViewItem>();
             item.transform.SetParent(Container.content, false);
             Items.Add(item);
             item.Key = key;
             item.Text = text;
             item.DataItem = dataItem;
             item.normalColor = normalColor;
             item.disabledColor = disabledColor;
             item.BackgroundColor = normalBackgroundColor;
             item.Font = font;
             item.FontSize = fontSize;
             item.RemoveAllListeners();
             item.AddListener(() =>
                 ChangeSelection(item));
             item.transform.SetSiblingIndex(count++);
             return item;
         }
References Juniper.Unity.Widgets.ListView.ChangeSelection(), Juniper.Unity.Widgets.ListView.Container, Juniper.Unity.Widgets.ListView.count, Juniper.Unity.Widgets.ListView.disabledColor, Juniper.Unity.Widgets.ListView.font, Juniper.Unity.Widgets.ListView.fontSize, Juniper.Unity.Widgets.ListView.Items, Juniper.Unity.Widgets.ListView.normalBackgroundColor, and Juniper.Unity.Widgets.ListView.normalColor.
Referenced by Juniper.Unity.Widgets.FileSelector.AddEntry(), and Juniper.Unity.Widgets.ListView.AddItems< T >().
AddItems< T >()
void Juniper.Unity.Widgets.ListView.AddItems< T > (IEnumerable< T > items, Func< T, string > getKey, Func< T, string > getText) inline
Definition at line 69 of file ListView.cs.
         {
             foreach (var item in items)
             {
                 AddItem(getText(item), item, getKey(item));
             }
         }
References Juniper.Unity.Widgets.ListView.AddItem().
Awake()
void Juniper.Unity.Widgets.ListView.Awake () inline
Definition at line 43 of file ListView.cs.
         {
             GetComponentsInChildren(true, Items);
         }
References Juniper.Unity.Widgets.ListView.Items.
ChangeSelection()
void Juniper.Unity.Widgets.ListView.ChangeSelection (ListViewItem selected) inline private
Definition at line 139 of file ListView.cs.
         {
             var wasInSelection = Selection.Contains(selected);
             var newSelection = Selection.ToList();
             if (selectionMode != SelectionMode.Multiple)
             {
                 newSelection.Clear();
             }
             else if (wasInSelection)
             {
                 newSelection.Remove(selected);
             }
             if (selectionMode == SelectionMode.Single
                 || (!wasInSelection && selectionMode != SelectionMode.None))
             {
                 newSelection.Add(selected);
             }
             SetSelection(newSelection);
         }
References Juniper.Unity.Widgets.ListView.Selection, Juniper.Unity.Widgets.ListView.selectionMode, and Juniper.Unity.Widgets.ListView.SetSelection().
Referenced by Juniper.Unity.Widgets.ListView.AddItem().
Clear()
void Juniper.Unity.Widgets.ListView.Clear () inline
Definition at line 48 of file ListView.cs.
         {
             foreach (var item in Items)
             {
                 item.gameObject.Destroy();
             }
             Items.Clear();
             Selection.Clear();
             count = 0;
         }
References Juniper.Unity.Widgets.ListView.count, Juniper.Unity.Widgets.ListView.Items, and Juniper.Unity.Widgets.ListView.Selection.
Referenced by Juniper.Unity.Widgets.FileSelector.ReadDirectory().
ClearSelection()
void Juniper.Unity.Widgets.ListView.ClearSelection () inline
Definition at line 101 of file ListView.cs.
         {
             SetSelection(EMPTY_SELECTION);
         }
References Juniper.Unity.Widgets.ListView.EMPTY_SELECTION, and Juniper.Unity.Widgets.ListView.SetSelection().
ContainsItem()
bool Juniper.Unity.Widgets.ListView.ContainsItem (string key) inline
Definition at line 64 of file ListView.cs.
         {
             return GetItem(key) != null;
         }
References Juniper.Unity.Widgets.ListView.GetItem().
GetItem()
ListViewItem Juniper.Unity.Widgets.ListView.GetItem (string key) inline
Definition at line 59 of file ListView.cs.
         {
             return Items.FirstOrDefault(i => i.Key == key);
         }
References Juniper.Unity.Widgets.ListView.Items.
Referenced by Juniper.Unity.Widgets.ListView.ContainsItem(), Juniper.Unity.Widgets.ListView.RemoveItem(), and Juniper.Unity.Widgets.ListView.SetSelection().
RemoveItem()
void Juniper.Unity.Widgets.ListView.RemoveItem (string key) inline
Definition at line 116 of file ListView.cs.
         {
             var item = GetItem(key);
             if (item != null)
             {
                 Items.Remove(item);
                 item.gameObject.Destroy();
                 --count;
             }
         }
References Juniper.Unity.Widgets.ListView.count, Juniper.Unity.Widgets.ListView.GetItem(), and Juniper.Unity.Widgets.ListView.Items.
SetSelection() [1/3]
void Juniper.Unity.Widgets.ListView.SetSelection (IEnumerable< string > keys) inline
Definition at line 106 of file ListView.cs.
         {
             SetSelection(keys.Select(GetItem).ToList());
         }
References Juniper.Unity.Widgets.ListView.GetItem().
Referenced by Juniper.Unity.Widgets.ListView.ChangeSelection(), Juniper.Unity.Widgets.ListView.ClearSelection(), and Juniper.Unity.Widgets.ListView.SetSelection().
SetSelection() [2/3]
void Juniper.Unity.Widgets.ListView.SetSelection (string key) inline
Definition at line 111 of file ListView.cs.
         {
             SetSelection(new[] { GetItem(key) }.ToList());
         }
References Juniper.Unity.Widgets.ListView.GetItem(), and Juniper.Unity.Widgets.ListView.SetSelection().
SetSelection() [3/3]
void Juniper.Unity.Widgets.ListView.SetSelection (List< ListViewItem > newSelection) inline private
Definition at line 162 of file ListView.cs.
         {
             var changed = newSelection.Count != Selection.Count
                 || !newSelection.All(Selection.Contains);
             if (changed)
             {
                 Selection.Clear();
                 Selection.AddRange(newSelection);
                 foreach (var item in Items)
                 {
                     var highlight = Selection.Contains(item);
                     item.BackgroundColor = highlight ? highlightBackgroundColor : normalBackgroundColor;
                     item.normalColor = highlight ? highlightColor : normalColor;
                 }
                 onSelectionChanged?.Invoke();
             }
         }
References Juniper.Unity.Widgets.ListView.highlightBackgroundColor, Juniper.Unity.Widgets.ListView.highlightColor, Juniper.Unity.Widgets.ListView.Items, Juniper.Unity.Widgets.ListView.normalBackgroundColor, Juniper.Unity.Widgets.ListView.normalColor, Juniper.Unity.Widgets.ListView.onSelectionChanged, and Juniper.Unity.Widgets.ListView.Selection.
Member Data Documentation
count
int Juniper.Unity.Widgets.ListView.count private
Definition at line 129 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.AddItem(), Juniper.Unity.Widgets.ListView.Clear(), and Juniper.Unity.Widgets.ListView.RemoveItem().
disabledColor
Color Juniper.Unity.Widgets.ListView.disabledColor = Color.grey
Definition at line 19 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.AddItem().
EMPTY_SELECTION
readonly List<ListViewItem> Juniper.Unity.Widgets.ListView.EMPTY_SELECTION = new List<ListViewItem>() static private
Definition at line 128 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.ClearSelection().
font
Font Juniper.Unity.Widgets.ListView.font
Definition at line 14 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.AddItem().
fontSize
int Juniper.Unity.Widgets.ListView.fontSize = 24
Definition at line 15 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.AddItem().
highlightBackgroundColor
Color Juniper.Unity.Widgets.ListView.highlightBackgroundColor = Color.Lerp(Color.white, Color.grey, 0.5f)
Definition at line 17 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.SetSelection().
highlightColor
Color Juniper.Unity.Widgets.ListView.highlightColor = Color.black
Definition at line 20 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.SetSelection().
normalBackgroundColor
Color Juniper.Unity.Widgets.ListView.normalBackgroundColor = Color.grey
Definition at line 16 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.AddItem(), and Juniper.Unity.Widgets.ListView.SetSelection().
normalColor
Color Juniper.Unity.Widgets.ListView.normalColor = Color.white
Definition at line 18 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.AddItem(), and Juniper.Unity.Widgets.ListView.SetSelection().
onSelectionChanged
UnityEvent Juniper.Unity.Widgets.ListView.onSelectionChanged
Definition at line 21 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.SetSelection().
selectionMode
SelectionMode Juniper.Unity.Widgets.ListView.selectionMode = SelectionMode.Single
Definition at line 13 of file ListView.cs.
Referenced by Juniper.Unity.Widgets.ListView.ChangeSelection().
Property Documentation
Container
ScrollRect Juniper.Unity.Widgets.ListView.Container get private
Definition at line 132 of file ListView.cs.
         {
             get
             {
                 return GetComponent<ScrollRect>();
             }
         }
Referenced by Juniper.Unity.Widgets.ListView.AddItem().
FirstSelectedItem
ListViewItem Juniper.Unity.Widgets.ListView.FirstSelectedItem get
Definition at line 36 of file ListView.cs.
         {
             get
             {
                 return Selection.FirstOrDefault();
             }
         }
Items
List<ListViewItem> Juniper.Unity.Widgets.ListView.Items = new List<ListViewItem>(10) get
Definition at line 31 of file ListView.cs.
 { get; } = new List<ListViewItem>(10);
Referenced by Juniper.Unity.Widgets.ListView.AddItem(), Juniper.Unity.Widgets.ListView.Awake(), Juniper.Unity.Widgets.ListView.Clear(), Juniper.Unity.Widgets.ListView.GetItem(), Juniper.Unity.Widgets.ListView.RemoveItem(), and Juniper.Unity.Widgets.ListView.SetSelection().
Selection
List<ListViewItem> Juniper.Unity.Widgets.ListView.Selection = new List<ListViewItem>(10) get
Definition at line 33 of file ListView.cs.
 { get; } = new List<ListViewItem>(10);
Referenced by Juniper.Unity.Widgets.ListView.ChangeSelection(), Juniper.Unity.Widgets.ListView.Clear(), and Juniper.Unity.Widgets.ListView.SetSelection().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Widgets/ListView.cs