Juniper: Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType > Class Template Reference
Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType > Class Template Reference
Public Member Functions
void Install (ButtonMapper< VirtualTouchPadButton > mapper, GameObject eventParent)
void Install (ButtonMapper< VirtualTriggerButton > mapper, GameObject eventParent)
string MakePointerName (Hands hand)
void Install (ButtonMapper< ButtonIDType > mapper, GameObject eventParent)
void Uninstall (GameObject eventParent)
Protected Member Functions
void AddButton (VirtualTouchPadButton outButton, InputButton? inButton=null)
void AddButton (VirtualTriggerButton outButton, InputButton? inButton=null)
void AddButton (ButtonIDType outButton, InputButton? inButton=null)
Properties
override string PointerNameStub [get]
Type HandType [get]
abstract ? HandIDType this[Hands hand] [get]
Private Attributes
readonly Dictionary< VirtualTouchPadButton, InputEventButton > touchPadButtons = new Dictionary<VirtualTouchPadButton, InputEventButton>()
readonly Dictionary< VirtualTriggerButton, InputEventButton > triggerButtons = new Dictionary<VirtualTriggerButton, InputEventButton>()
Detailed Description
Type Constraints
HandIDType : struct
HandIDType : IComparable
ButtonIDType : struct
Definition at line 14 of file AbstractMotionController.cs.
Member Function Documentation
AddButton() [1/3]
void Juniper.Unity.Input.Pointers.AbstractPointerConfiguration< ButtonIDType >.AddButton (ButtonIDType outButton, InputButton? inButton = null) inline protected inherited
Definition at line 24 of file AbstractPointerDevice.cs.
         {
             nativeButtons.Add(outButton, inButton == null ? InputEventButton.None : (InputEventButton)inButton.Value);
         }
AddButton() [2/3]
void Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.AddButton (VirtualTouchPadButton outButton, InputButton? inButton = null) inline protected
Definition at line 30 of file AbstractMotionController.cs.
         {
             touchPadButtons.Add(outButton, inButton == null ? InputEventButton.None : (InputEventButton)inButton.Value);
         }
AddButton() [3/3]
void Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.AddButton (VirtualTriggerButton outButton, InputButton? inButton = null) inline protected
Definition at line 35 of file AbstractMotionController.cs.
         {
             triggerButtons.Add(outButton, inButton == null ? InputEventButton.None : (InputEventButton)inButton.Value);
         }
Install() [1/3]
void Juniper.Unity.Input.Pointers.AbstractPointerConfiguration< ButtonIDType >.Install (ButtonMapper< ButtonIDType > mapper, GameObject eventParent) inline inherited
Definition at line 29 of file AbstractPointerDevice.cs.
         {
             mapper.Install(eventParent, nativeButtons);
         }
Install() [2/3]
void Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.Install (ButtonMapper< VirtualTouchPadButton > mapper, GameObject eventParent) inline
Definition at line 40 of file AbstractMotionController.cs.
         {
             mapper.Install(eventParent, touchPadButtons);
         }
Install() [3/3]
void Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.Install (ButtonMapper< VirtualTriggerButton > mapper, GameObject eventParent) inline
Definition at line 45 of file AbstractMotionController.cs.
         {
             mapper.Install(eventParent, triggerButtons);
         }
MakePointerName()
string Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointerConfiguration< HandIDType, ButtonIDType >.MakePointerName (Hands hand) inline inherited
Definition at line 23 of file AbstractHandedPointer.cs.
         {
             return $"{hand}{PointerNameStub}";
         }
Uninstall()
void Juniper.Unity.Input.Pointers.AbstractPointerConfiguration< ButtonIDType >.Uninstall (GameObject eventParent) inline inherited
Definition at line 34 of file AbstractPointerDevice.cs.
         {
             foreach (var evt in eventParent.GetComponents<ButtonEvent>())
             {
                 evt.Destroy();
             }
         }
Member Data Documentation
touchPadButtons
readonly Dictionary<VirtualTouchPadButton, InputEventButton> Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.touchPadButtons = new Dictionary<VirtualTouchPadButton, InputEventButton>() private
Definition at line 27 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.AddButton(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.Install().
triggerButtons
readonly Dictionary<VirtualTriggerButton, InputEventButton> Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.triggerButtons = new Dictionary<VirtualTriggerButton, InputEventButton>() private
Definition at line 28 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.AddButton(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.Install().
Property Documentation
HandType
Type Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointerConfiguration< HandIDType, ButtonIDType >.HandType get inherited
Definition at line 16 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return typeof(HandIDType);
             }
         }
PointerNameStub
override string Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.PointerNameStub get protected
Definition at line 20 of file AbstractMotionController.cs.
         {
             get
             {
                 return "MotionController";
             }
         }
this[Hands hand]
abstract ? HandIDType Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointerConfiguration< HandIDType, ButtonIDType >.this[Hands hand] get inherited
Definition at line 33 of file AbstractHandedPointer.cs.
 { get; }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/Pointers/Motion/AbstractMotionController.cs