Juniper: Juniper.Anchoring.AnchorStore Class Reference
Juniper.Anchoring.AnchorStore Class Reference
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This component creates the native anchor type for any given subsystem, and save it to its native anchor store.
Public Member Functions
void Awake ()
Acquires the anchorStore
void ResetData ()
Delete saved anchors, if there are any.
bool HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
bool DropAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
void WeighAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Static Private Member Functions
static AnchorType GetAnchor (GameObject gameObject)
Private Attributes
UnityARAnchorManager anchorManager
The collection in which anchors are stored. This value's type changes depending on certain compliation flags.
WorldAnchorStore anchorStore
Detailed Description
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This component creates the native anchor type for any given subsystem, and save it to its native anchor store.
Definition at line 34 of file AnchorStore.cs.
Member Function Documentation
Awake()
void Juniper.Anchoring.AnchorStore.Awake () inline
Acquires the anchorStore
Definition at line 53 of file AnchorStore.cs.
         {
 #if ARKIT
             anchorManager = new UnityARAnchorManager();
 #elif HOLOLENS
             WorldAnchorStore.GetAsync(new WorldAnchorStore.GetAsyncDelegate(store =>
                 anchorStore = store));
 #endif
         }
References Juniper.Anchoring.AnchorStore.anchorManager, and Juniper.Anchoring.AnchorStore.anchorStore.
DropAnchor()
bool Juniper.Anchoring.AnchorStore.DropAnchor (string ID, GameObject gameObject) inline
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
Returns
true, if anchor existed on the object, existed in the datastore, or was successfully created, false otherwise.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 99 of file AnchorStore.cs.
         {
             if (string.IsNullOrEmpty(ID))
             {
                 throw new ArgumentException("Parameter must have a value.", nameof(ID));
             }
             var scaleID = ID + "-scale";
             var anchor = GetAnchor(gameObject);
             if (anchor == null
 #if HOLOLENS
                 && anchorStore != null
 #endif
                )
             {
                 if (HasAnchor(ID))
                 {
 #if ARCORE || ARKIT || MAGIC_LEAP
                     anchor = anchorStore[ID];
 #elif HOLOLENS
                     anchor = anchorStore.Load(ID, gameObject);
 #else
                     var anchorStr = PlayerPrefs.GetString(ID);
                     anchor = gameObject.AddComponent<MockWorldAnchor>();
                     var anchorState = JsonConvert.DeserializeObject<MockWorldAnchor.Pose>(anchorStr);
                     anchor.state = anchorState;
 #endif
                     if (PlayerPrefs.HasKey(scaleID))
                     {
                         gameObject.transform.localScale = JsonConvert.DeserializeObject<Vector3>(PlayerPrefs.GetString(scaleID));
                     }
                 }
                 else
                 {
 #if ARCORE
                     var pose = new Pose(
                         gameObject.transform.position,
                         gameObject.transform.rotation);
                     anchor = Session.CreateAnchor(pose);
                     anchorStore.Add(ID, anchor);
 #elif ARKIT
                     anchor = gameObject.AddComponent<UnityARUserAnchorComponent>();
                     anchorStore.Add(ID, anchor);
 #elif HOLOLENS
                     anchor = gameObject.AddComponent<UnityEngine.XR.WSA.WorldAnchor>();
                     anchorStore.Save(ID, anchor);
 #elif MAGIC_LEAP
                     anchor = gameObject.AddComponent<MLPersistentBehavior>();
                     anchor.UniqueId = ID;
                     anchorStore.Add(ID, anchor);
 #else
                     var t = gameObject.transform;
                     anchor = gameObject.AddComponent<MockWorldAnchor>();
                     anchor.state = new MockWorldAnchor.Pose
                     {
                         position = t.position,
                         rotation = t.rotation
                     };
                     PlayerPrefs.SetString(ID, JsonConvert.SerializeObject(anchor.state));
 #endif
                     PlayerPrefs.SetString(scaleID, JsonConvert.SerializeObject(gameObject.transform.localScale));
                 }
 #if ARCORE || ARKIT || MAGIC_LEAP
                 if (anchor != null)
                 {
                     gameObject.transform.SetParent(anchor.transform, true);
                 }
 #endif
             }
 #if HOLOLENS
             return anchor?.isLocated == true;
 #else
             return anchor != null;
 #endif
         }
References Juniper.Anchoring.AnchorStore.anchorStore, Juniper.Anchoring.AnchorStore.GetAnchor(), Juniper.Anchoring.AnchorStore.HasAnchor(), Juniper.Anchoring.MockWorldAnchor.Pose.position, and Juniper.Anchoring.MockWorldAnchor.state.
Referenced by Juniper.Anchoring.Anchored.DropAnchor().
GetAnchor()
static AnchorType Juniper.Anchoring.AnchorStore.GetAnchor (GameObject gameObject) inline static private
Definition at line 213 of file AnchorStore.cs.
         {
 #if ARCORE || ARKIT
             gameObject = gameObject.transform.parent?.gameObject;
 #endif
             return gameObject?.GetComponent<AnchorType>();
         }
Referenced by Juniper.Anchoring.AnchorStore.DropAnchor(), and Juniper.Anchoring.AnchorStore.WeighAnchor().
HasAnchor()
bool Juniper.Anchoring.AnchorStore.HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
Returns
true, if anchor exists, false otherwise.
Parameters
anchorID Anchor identifier.
Referenced by Juniper.Anchoring.AnchorStore.DropAnchor().
ResetData()
void Juniper.Anchoring.AnchorStore.ResetData () inline
Delete saved anchors, if there are any.
Definition at line 66 of file AnchorStore.cs.
         {
             PlayerPrefs.DeleteAll();
             anchorStore.Clear();
         }
References Juniper.Anchoring.AnchorStore.anchorStore.
WeighAnchor()
void Juniper.Anchoring.AnchorStore.WeighAnchor (string ID, GameObject gameObject) inline
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 189 of file AnchorStore.cs.
         {
             var anchor = GetAnchor(gameObject);
             if (anchor != null)
             {
 #if ARCORE || ARKIT || MAGIC_LEAP
                 gameObject.transform.SetParent(anchor.transform.parent, true);
                 if (anchor.transform.childCount == 0)
                 {
                     anchorStore.Remove(ID);
                     anchor.gameObject.Destroy();
                 }
 #elif HOLOLENS
                 anchor.Destroy();
                 anchorStore.Delete(ID);
 #else
                 PlayerPrefs.DeleteKey(ID);
                 anchor.Destroy();
 #endif
                 PlayerPrefs.DeleteKey(ID + "-scale");
             }
         }
References Juniper.Anchoring.AnchorStore.anchorStore, and Juniper.Anchoring.AnchorStore.GetAnchor().
Referenced by Juniper.Anchoring.Anchored.WeighAnchor().
Member Data Documentation
anchorManager
UnityARAnchorManager Juniper.Anchoring.AnchorStore.anchorManager private
The collection in which anchors are stored. This value's type changes depending on certain compliation flags.
Definition at line 41 of file AnchorStore.cs.
Referenced by Juniper.Anchoring.AnchorStore.Awake().
anchorStore
WorldAnchorStore Juniper.Anchoring.AnchorStore.anchorStore private
Definition at line 45 of file AnchorStore.cs.
Referenced by Juniper.Anchoring.AnchorStore.Awake(), Juniper.Anchoring.AnchorStore.DropAnchor(), Juniper.Anchoring.AnchorStore.ResetData(), and Juniper.Anchoring.AnchorStore.WeighAnchor().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Assets/Juniper/Scripts/Unity/Anchoring/AnchorStore.cs