Juniper: Juniper.Imaging.Size Class Reference
Juniper.Imaging.Size Class Reference
Public Member Functions
Size (int width, int height)
void GetObjectData (SerializationInfo info, StreamingContext context)
override bool Equals (object obj)
bool Equals (Size other)
string ToString (IFormatProvider formatter)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static bool TryParse (string widthXHeight, out Size size)
static Size Parse (string widthXHeight)
static bool operator== (Size left, Size right)
static bool operator != (Size left, Size right)
static operator string (Size size)
Properties
int Width [get]
int Height [get]
Private Member Functions
Size (SerializationInfo info, StreamingContext context)
Static Private Attributes
static readonly Regex SizePattern = new Regex("^(\\d+)x(\\d+)$", RegexOptions.Compiled)
static readonly string WIDTH_FIELD = nameof(Width).ToLowerInvariant()
static readonly string HEIGHT_FIELD = nameof(Height).ToLowerInvariant()
Detailed Description
Definition at line 9 of file Size.cs.
Constructor & Destructor Documentation
Size() [1/2]
Juniper.Imaging.Size.Size (int width, int height) inline
Definition at line 49 of file Size.cs.
         {
             Width = width;
             Height = height;
         }
References Juniper.Imaging.Size.Height, and Juniper.Imaging.Size.Width.
Referenced by Juniper.Imaging.Size.TryParse().
Size() [2/2]
Juniper.Imaging.Size.Size (SerializationInfo info, StreamingContext context) inline private
Definition at line 56 of file Size.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Width = info.GetInt32(WIDTH_FIELD);
             Height = info.GetInt32(HEIGHT_FIELD);
         }
References Juniper.Imaging.Size.Height, Juniper.Imaging.Size.HEIGHT_FIELD, Juniper.Imaging.Size.Width, and Juniper.Imaging.Size.WIDTH_FIELD.
Member Function Documentation
Equals() [1/2]
override bool Juniper.Imaging.Size.Equals (object obj) inline
Definition at line 78 of file Size.cs.
         {
             return obj is Size size && Equals(size);
         }
Equals() [2/2]
bool Juniper.Imaging.Size.Equals (Size other) inline
Definition at line 83 of file Size.cs.
         {
             return other is object
                 && Width == other.Width
                 && Height == other.Height;
         }
References Juniper.Imaging.Size.Height, and Juniper.Imaging.Size.Width.
GetHashCode()
override int Juniper.Imaging.Size.GetHashCode () inline
Definition at line 108 of file Size.cs.
         {
             var hashCode = 859600377;
             hashCode = (hashCode * -1521134295) + Width.GetHashCode();
             hashCode = (hashCode * -1521134295) + Height.GetHashCode();
             return hashCode;
         }
References Juniper.Imaging.Size.Height, and Juniper.Imaging.Size.Width.
GetObjectData()
void Juniper.Imaging.Size.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 67 of file Size.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(WIDTH_FIELD, Width);
             info.AddValue(HEIGHT_FIELD, Height);
         }
References Juniper.Imaging.Size.Height, Juniper.Imaging.Size.HEIGHT_FIELD, Juniper.Imaging.Size.Width, and Juniper.Imaging.Size.WIDTH_FIELD.
operator !=()
static bool Juniper.Imaging.Size.operator != (Size left, Size right) inline static
Definition at line 96 of file Size.cs.
         {
             return !(left == right);
         }
operator string()
static Juniper.Imaging.Size.operator string (Size size) inline explicit static
Definition at line 124 of file Size.cs.
         {
             return size?.ToString(CultureInfo.InvariantCulture);
         }
References Juniper.Imaging.Size.ToString().
operator==()
static bool Juniper.Imaging.Size.operator== (Size left, Size right) inline static
Definition at line 90 of file Size.cs.
         {
             return ReferenceEquals(left, right)
                 || (left is object && left.Equals(right));
         }
Parse()
static Size Juniper.Imaging.Size.Parse (string widthXHeight) inline static
Definition at line 34 of file Size.cs.
         {
             if (TryParse(widthXHeight, out var size))
             {
                 return size;
             }
             else
             {
                 throw new FormatException("Input string must be format \"[width]x[height]\", where width and height are positive integers");
             }
         }
References Juniper.Imaging.Size.TryParse().
ToString() [1/2]
string Juniper.Imaging.Size.ToString (IFormatProvider formatter) inline
Definition at line 101 of file Size.cs.
         {
             return Width.ToString(formatter)
                 + "x"
                 + Height.ToString(formatter);
         }
References Juniper.Imaging.Size.Height, and Juniper.Imaging.Size.Width.
Referenced by Juniper.Imaging.Size.operator string().
ToString() [2/2]
override string Juniper.Imaging.Size.ToString () inline
Definition at line 117 of file Size.cs.
         {
             return Width.ToString()
                 + "x"
                 + Height.ToString();
         }
References Juniper.Imaging.Size.Height, and Juniper.Imaging.Size.Width.
TryParse()
static bool Juniper.Imaging.Size.TryParse (string widthXHeight, out Size size) inline static
Definition at line 15 of file Size.cs.
         {
             var match = SizePattern.Match(widthXHeight);
             if (!match.Success)
             {
                 size = default;
             }
             else
             {
                 var widthString = match.Captures[1].Value;
                 var heightString = match.Captures[2].Value;
                 var width = int.Parse(widthString, CultureInfo.InvariantCulture);
                 var height = int.Parse(heightString, CultureInfo.InvariantCulture);
                 size = new Size(width, height);
             }
             return match.Success;
         }
References Juniper.Imaging.Size.Size(), and Juniper.Imaging.Size.SizePattern.
Referenced by Juniper.Imaging.Size.Parse(), and Juniper.Processes.ProcessArgs.TryGetSize().
Member Data Documentation
HEIGHT_FIELD
readonly string Juniper.Imaging.Size.HEIGHT_FIELD = nameof(Height).ToLowerInvariant() static private
Definition at line 13 of file Size.cs.
Referenced by Juniper.Imaging.Size.GetObjectData(), and Juniper.Imaging.Size.Size().
SizePattern
readonly Regex Juniper.Imaging.Size.SizePattern = new Regex("^(\\d+)x(\\d+)$", RegexOptions.Compiled) static private
Definition at line 11 of file Size.cs.
Referenced by Juniper.Imaging.Size.TryParse().
WIDTH_FIELD
readonly string Juniper.Imaging.Size.WIDTH_FIELD = nameof(Width).ToLowerInvariant() static private
Definition at line 12 of file Size.cs.
Referenced by Juniper.Imaging.Size.GetObjectData(), and Juniper.Imaging.Size.Size().
Property Documentation
Height
int Juniper.Imaging.Size.Height get
Definition at line 47 of file Size.cs.
 { get; }
Referenced by Juniper.Imaging.Size.Equals(), Juniper.Imaging.Size.GetHashCode(), Juniper.Imaging.ImageDataProcessor.GetHeight(), Juniper.Imaging.Size.GetObjectData(), Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.Size.Size(), Juniper.Imaging.Size.ToString(), Juniper.Imaging.GDIImageDataTranscoder.Translate(), Juniper.Imaging.HjgPngcsImageDataTranscoder.Translate(), and Juniper.Imaging.LibJpegNETImageDataTranscoder.Translate().
Width
int Juniper.Imaging.Size.Width get
Definition at line 46 of file Size.cs.
 { get; }
Referenced by Juniper.Imaging.Size.Equals(), Juniper.Imaging.Size.GetHashCode(), Juniper.Imaging.Size.GetObjectData(), Juniper.Imaging.ImageDataProcessor.GetWidth(), Juniper.Imaging.ImageInfo.ImageInfo(), Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.Size.Size(), Juniper.Imaging.Size.ToString(), Juniper.Imaging.GDIImageDataTranscoder.Translate(), Juniper.Imaging.HjgPngcsImageDataTranscoder.Translate(), and Juniper.Imaging.LibJpegNETImageDataTranscoder.Translate().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Imaging/Size.cs