Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegUtils Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegUtils Class Reference
Static Public Member Functions
static int RIGHT_SHIFT (int x, int shft)
static int DESCALE (int x, int n)
static long jdiv_round_up (long a, long b)
Compute a/b rounded up to next integer, ie, ceil(a/b) Assumes a >= 0, b > 0
static int jround_up (int a, int b)
Compute a rounded up to next multiple of b, ie, ceil(a/b)*b Assumes a >= 0, b > 0
static void jcopy_sample_rows (ComponentBuffer input_array, int source_row, byte[][] output_array, int dest_row, int num_rows, int num_cols)
Copy some rows of samples from one place to another. num_rows rows are copied from input_array[source_row++] to output_array[dest_row++]; these areas may overlap for duplication. The source and destination arrays must be at least as wide as num_cols.
static void jcopy_sample_rows (ComponentBuffer input_array, int source_row, ComponentBuffer output_array, int dest_row, int num_rows, int num_cols)
static void jcopy_sample_rows (byte[][] input_array, int source_row, byte[][] output_array, int dest_row, int num_rows, int num_cols)
Static Public Attributes
static readonly int [] jpeg_natural_order
static readonly int [] jpeg_natural_order7
static readonly int [] jpeg_natural_order6
static readonly int [] jpeg_natural_order5
static readonly int [] jpeg_natural_order4
static readonly int [] jpeg_natural_order3
static readonly int [] jpeg_natural_order2
static readonly int [] jpeg_aritab = Array.Empty<int>()
Detailed Description
Definition at line 12 of file JpegUtils.cs.
Member Function Documentation
DESCALE()
static int BitMiracle.LibJpeg.Classic.Internal.JpegUtils.DESCALE (int x, int n) inline static
Definition at line 130 of file JpegUtils.cs.
         {
             return RIGHT_SHIFT(x + (1 << (n - 1)), n);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.FAST_INTEGER_MULTIPLY(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FastIntegerMultiply(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.StartPass().
jcopy_sample_rows() [1/3]
static void BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jcopy_sample_rows (ComponentBuffer input_array, int source_row, byte output_array[][], int dest_row, int num_rows, int num_cols) inline static
Copy some rows of samples from one place to another. num_rows rows are copied from input_array[source_row++] to output_array[dest_row++]; these areas may overlap for duplication. The source and destination arrays must be at least as wide as num_cols.
Definition at line 163 of file JpegUtils.cs.
         {
             for (var row = 0; row < num_rows; row++)
             {
                 Buffer.BlockCopy(input_array[source_row + row], 0, output_array[dest_row + row], 0, num_cols);
             }
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.ExpandBottomEdge(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayscaleConvert(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.H2V2UpSample(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.IntUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample(), and BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessContext().
jcopy_sample_rows() [2/3]
static void BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jcopy_sample_rows (ComponentBuffer input_array, int source_row, ComponentBuffer output_array, int dest_row, int num_rows, int num_cols) inline static
Definition at line 171 of file JpegUtils.cs.
         {
             for (var row = 0; row < num_rows; row++)
             {
                 Buffer.BlockCopy(input_array[source_row + row], 0, output_array[dest_row + row], 0, num_cols);
             }
         }
jcopy_sample_rows() [3/3]
static void BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jcopy_sample_rows (byte input_array[][], int source_row, byte output_array[][], int dest_row, int num_rows, int num_cols) inline static
Definition at line 179 of file JpegUtils.cs.
         {
             for (var row = 0; row < num_rows; row++)
             {
                 Buffer.BlockCopy(input_array[source_row++], 0, output_array[dest_row++], 0, num_cols);
             }
         }
jdiv_round_up()
static long BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jdiv_round_up (long a, long b) inline static
Compute a/b rounded up to next integer, ie, ceil(a/b) Assumes a >= 0, b > 0
Definition at line 142 of file JpegUtils.cs.
         {
             return (a + b - 1L) / b;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.JpegCoreOutputDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), and BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup().
jround_up()
static int BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jround_up (int a, int b) inline static
Compute a rounded up to next multiple of b, ie, ceil(a/b)*b Assumes a >= 0, b > 0
Definition at line 151 of file JpegUtils.cs.
         {
             a += b - 1;
             return a - (a % b);
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.JpegDCoefController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.MyCCoefController(), and BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler().
RIGHT_SHIFT()
static int BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT (int x, int shft) inline static
Definition at line 121 of file JpegUtils.cs.
         {
             return x >> shft;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegUtils.DESCALE(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.FAST_INTEGER_MULTIPLY(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FastIntegerMultiply(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct16x16(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDctISlow(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.Pass2FsDither(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.QuantizeFsDither(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
Member Data Documentation
jpeg_aritab
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_aritab = Array.Empty<int>() static
Definition at line 112 of file JpegUtils.cs.
jpeg_natural_order
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order static
Initial value:
=
        {
             0,  1,  8, 16,  9,  2,  3, 10,
            17, 24, 32, 25, 18, 11,  4,  5,
            12, 19, 26, 33, 40, 48, 41, 34,
            27, 20, 13,  6,  7, 14, 21, 28,
            35, 42, 49, 56, 57, 50, 43, 36,
            29, 22, 15, 23, 30, 37, 44, 51,
            58, 59, 52, 45, 38, 31, 39, 46,
            53, 60, 61, 54, 47, 55, 62, 63,
            63, 63, 63, 63, 63, 63, 63, 63,
            63, 63, 63, 63, 63, 63, 63, 63
        }
Definition at line 27 of file JpegUtils.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
jpeg_natural_order2
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order2 static
Initial value:
=
        {
             0,  1,  8,  9,
            63, 63, 63, 63, 63, 63, 63, 63,
            63, 63, 63, 63, 63, 63, 63, 63
        }
Definition at line 103 of file JpegUtils.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
jpeg_natural_order3
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order3 static
Initial value:
=
        {
             0,  1,  8, 16,  9,  2, 10, 17,
            18,
            63, 63, 63, 63, 63, 63, 63, 63,
            63, 63, 63, 63, 63, 63, 63, 63
        }
Definition at line 93 of file JpegUtils.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
jpeg_natural_order4
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order4 static
Initial value:
=
        {
             0,  1,  8, 16,  9,  2,  3, 10,
            17, 24, 25, 18, 11, 19, 26, 27,
            63, 63, 63, 63, 63, 63, 63, 63,
            63, 63, 63, 63, 63, 63, 63, 63
        }
Definition at line 83 of file JpegUtils.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
jpeg_natural_order5
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order5 static
Initial value:
=
        {
             0,  1,  8, 16,  9,  2,  3, 10,
            17, 24, 32, 25, 18, 11,  4, 12,
            19, 26, 33, 34, 27, 20, 28, 35,
            36,
            63, 63, 63, 63, 63, 63, 63, 63,
            63, 63, 63, 63, 63, 63, 63, 63
        }
Definition at line 71 of file JpegUtils.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
jpeg_natural_order6
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order6 static
Initial value:
=
        {
             0,  1,  8, 16,  9,  2,  3, 10,
            17, 24, 32, 25, 18, 11,  4,  5,
            12, 19, 26, 33, 40, 41, 34, 27,
            20, 13, 21, 28, 35, 42, 43, 36,
            29, 37, 44, 45,
            63, 63, 63, 63, 63, 63, 63, 63,
            63, 63, 63, 63, 63, 63, 63, 63
        }
Definition at line 58 of file JpegUtils.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
jpeg_natural_order7
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order7 static
Initial value:
=
        {
             0,  1,  8, 16,  9,  2,  3, 10,
            17, 24, 32, 25, 18, 11,  4,  5,
            12, 19, 26, 33, 40, 48, 41, 34,
            27, 20, 13,  6, 14, 21, 28, 35,
            42, 49, 50, 43, 36, 29, 22, 30,
            37, 44, 51, 52, 45, 38, 46, 53,
            54,
            63, 63, 63, 63, 63, 63, 63, 63,
            63, 63, 63, 63, 63, 63, 63, 63
        }
Definition at line 43 of file JpegUtils.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegUtils.cs