Juniper: BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder Class Reference
BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder Class Reference
Expanded entropy encoder object for Huffman encoding.
Classes
class CDerivedTable
class SavableState
Public Member Functions
HuffmanEntropyEncoder (JpegCompressStruct cinfo)
override void StartPass (bool gather_statistics)
Initialize for a Huffman-compressed scan. If gather_statistics is true, we do not output anything during the scan, just count the Huffman symbols used and generate Huffman code tables.
delegate bool EncodeMcuDelegate (JBlock[][] MCU_data)
delegate void FinishPassDelegate ()
Protected Member Functions
void JpegGenOptimalTable (JHuffmanTable htbl, long[] freq)
Properties
EncodeMcuDelegate encodeMcu [get, set]
FinishPassDelegate finishPass [get, set]
Private Member Functions
bool EncodeMcuHuffman (JBlock[][] MCU_data)
Encode and output one MCU's worth of Huffman-compressed coefficients.
void FinishPassHuffman ()
Finish up at the end of a Huffman-compressed scan.
bool EncodeMcuGather (JBlock[][] MCU_data)
Trial-encode one MCU's worth of Huffman-compressed coefficients. No data is actually output, so no suspension return is possible.
void FinishPassGather ()
Finish up a statistics-gathering pass and create the new Huffman tables.
bool EncodeOneBlock (SavableState state, short[] block, int last_dc_val, CDerivedTable dctbl, CDerivedTable actbl)
Encode a single block's worth of coefficients
void HTestOneBlock (short[] block, int last_dc_val, long[] dc_counts, long[] ac_counts)
bool EmitByteS (int val)
void EmitByteE (int val)
bool EmitBitsS (SavableState state, int code, int size)
Only the right 24 bits of put_buffer are used; the valid bits are left-justified in this part. At most 16 bits can be passed to emit_bits in one call, and we never retain more than 7 bits in put_buffer between calls, so 24 bits are sufficient.
void EmitBitsE (int code, int size)
bool FlushBitsS (SavableState state)
void FlushBitsE ()
void EmitDCSymbol (int tbl_no, int symbol)
void EmitACSymbol (int tbl_no, int symbol)
void EmitBufferedBits (uint offset, uint nbits)
void EmitEOBRun ()
bool EmitRestartS (SavableState state, int restart_num)
Emit a restart marker and resynchronize predictions.
void EmitRestartE (int restart_num)
bool EncodeMcuDCFirst (JBlock[][] MCU_data)
MCU encoding for DC initial scan (either spectral selection, or first pass of successive approximation).
bool EncodeMcuACFirst (JBlock[][] MCU_data)
MCU encoding for AC initial scan (either spectral selection, or first pass of successive approximation).
bool EncodeMcuDCRefine (JBlock[][] MCU_data)
MCU encoding for DC successive approximation refinement scan. Note: we assume such scans can be multi-component, although the spec is not very clear on the point.
bool EncodeMcuACRefine (JBlock[][] MCU_data)
MCU encoding for AC successive approximation refinement scan.
void JpegMakeCDerivedTable (bool isDC, int tblno, ref CDerivedTable dtbl)
Expand a Huffman table definition into the derived format Compute the derived values for a Huffman table. This routine also performs some validation checks on the table.
Static Private Member Functions
static int IRightShift (int x, int shft)
IRIGHT_SHIFT is like RIGHT_SHIFT, but works on int rather than int. We assume that int right shift is unsigned if int right shift is, which should be safe.
Private Attributes
const int MAX_COEF_BITS = 10
const int MAX_CORR_BITS = 1000
readonly SavableState saved = new SavableState()
int restartsToGo
int nextRestartNum
readonly CDerivedTable [] dcDerivedTables = new CDerivedTable[JpegConstants.NUM_HUFF_TBLS]
readonly CDerivedTable [] acDerivedTables = new CDerivedTable[JpegConstants.NUM_HUFF_TBLS]
readonly long [][] dcCountPtrs = new long[JpegConstants.NUM_HUFF_TBLS][]
readonly long [][] acCountPtrs = new long[JpegConstants.NUM_HUFF_TBLS][]
bool gatherStatistics
readonly JpegCompressStruct cinfo
int acTblNo
uint EOBRUN
uint BE
char [] bitBuffer
Detailed Description
Expanded entropy encoder object for Huffman encoding.
Definition at line 22 of file HuffmanEntropyEncoder.cs.
Constructor & Destructor Documentation
HuffmanEntropyEncoder()
BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder (JpegCompressStruct cinfo) inline
Definition at line 95 of file HuffmanEntropyEncoder.cs.
         {
             this.cinfo = cinfo;
             /* Mark tables unallocated */
             for (var i = 0; i < JpegConstants.NUM_HUFF_TBLS; i++)
             {
                 dcDerivedTables[i] = acDerivedTables[i] = null;
                 dcCountPtrs[i] = acCountPtrs[i] = null;
             }
             if (this.cinfo.m_progressive_mode)
             {
                 /* needed only in AC refinement scan */
                 bitBuffer = null;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acDerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.bitBuffer, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcDerivedTables, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, and BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS.
Member Function Documentation
EmitACSymbol()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol (int tbl_no, int symbol) inline private
Definition at line 803 of file HuffmanEntropyEncoder.cs.
         {
             if (gatherStatistics)
             {
                 acCountPtrs[tbl_no][symbol]++;
             }
             else
             {
                 var tbl = acDerivedTables[tbl_no];
                 EmitBitsE(tbl.ehufco[symbol], tbl.ehufsi[symbol]);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acDerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.gatherStatistics.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine().
EmitBitsE()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE (int code, int size) inline private
Outputting bits to the file
Only the right 24 bits of put_buffer are used; the valid bits are left-justified in this part. At most 16 bits can be passed to emit_bits in one call, and we never retain more than 7 bits in put_buffer between calls, so 24 bits are sufficient.
Emit some bits, unless we are in gather mode
Definition at line 727 of file HuffmanEntropyEncoder.cs.
         {
             /* This routine is heavily used, so it's worth coding tightly. */
             /* if size is 0, caller used an invalid Huffman table entry */
             if (size == 0)
             {
                 cinfo.ErrExit(JMessageCode.JERR_HUFF_MISSING_CODE);
             }
             if (gatherStatistics)
             {
                 /* do nothing if we're only getting stats */
                 return;
             }
             var local_put_buffer = code & ((1 << size) - 1); /* mask off any extra bits in code */
             var put_bits = size + saved.put_bits;       /* new number of bits in buffer */
             local_put_buffer <<= 24 - put_bits; /* align incoming bits */
             local_put_buffer |= saved.put_buffer; /* and merge with old buffer contents */
             while (put_bits >= 8)
             {
                 var c = (local_put_buffer >> 16) & 0xFF;
                 EmitByteE(c);
                 if (c == 0xFF)
                 {
                     /* need to stuff a zero byte? */
                     EmitByteE(0);
                 }
                 local_put_buffer <<= 8;
                 put_bits -= 8;
             }
             saved.put_buffer = local_put_buffer; /* update variables */
             saved.put_bits = put_bits;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteE(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.gatherStatistics, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.put_bits, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.put_buffer, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBufferedBits(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitDCSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsE().
EmitBitsS()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS (SavableState state, int code, int size) inline private
Only the right 24 bits of put_buffer are used; the valid bits are left-justified in this part. At most 16 bits can be passed to emit_bits in one call, and we never retain more than 7 bits in put_buffer between calls, so 24 bits are sufficient.
Emit some bits; return true if successful, false if must suspend
Definition at line 669 of file HuffmanEntropyEncoder.cs.
         {
             /* This routine is heavily used, so it's worth coding tightly. */
             /* if size is 0, caller used an invalid Huffman table entry */
             if (size == 0)
             {
                 cinfo.ErrExit(JMessageCode.JERR_HUFF_MISSING_CODE);
             }
             /* mask off any extra bits in code */
             var put_buffer = code & ((1 << size) - 1);
             /* new number of bits in buffer */
             var put_bits = size + state.put_bits;
             put_buffer <<= 24 - put_bits; /* align incoming bits */
             /* and merge with old buffer contents */
             put_buffer |= state.put_buffer;
             while (put_bits >= 8)
             {
                 var c = (put_buffer >> 16) & 0xFF;
                 if (!EmitByteS(c))
                 {
                     return false;
                 }
                 if (c == 0xFF)
                 {
                     /* need to stuff a zero byte? */
                     if (!EmitByteS(0))
                     {
                         return false;
                     }
                 }
                 put_buffer <<= 8;
                 put_bits -= 8;
             }
             state.put_buffer = put_buffer; /* update state variables */
             state.put_bits = put_bits;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteS(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit().
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsS().
EmitBufferedBits()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBufferedBits (uint offset, uint nbits) inline private
Definition at line 817 of file HuffmanEntropyEncoder.cs.
         {
             if (gatherStatistics)
             {
                 /* no real work */
                 return;
             }
             for (var i = 0; i < nbits; i++)
             {
                 EmitBitsE(bitBuffer[offset + i], 1);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.bitBuffer, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.gatherStatistics.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine().
EmitByteE()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteE (int val) inline private
Definition at line 657 of file HuffmanEntropyEncoder.cs.
         {
             _ = cinfo.m_dest.EmitByte(val);
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE().
EmitByteS()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteS (int val) inline private
Definition at line 652 of file HuffmanEntropyEncoder.cs.
         {
             return cinfo.m_dest.EmitByte(val);
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartS().
EmitDCSymbol()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitDCSymbol (int tbl_no, int symbol) inline private
Definition at line 790 of file HuffmanEntropyEncoder.cs.
         {
             if (gatherStatistics)
             {
                 dcCountPtrs[tbl_no][symbol]++;
             }
             else
             {
                 var tbl = dcDerivedTables[tbl_no];
                 EmitBitsE(tbl.ehufco[symbol], tbl.ehufsi[symbol]);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcDerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.gatherStatistics.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst().
EmitEOBRun()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun () inline private
Definition at line 832 of file HuffmanEntropyEncoder.cs.
         {
             if (EOBRUN > 0)
             {
                 /* if there is any pending EOBRUN */
                 var temp = EOBRUN;
                 var nbits = 0;
                 while ((temp >>= 1) != 0)
                 {
                     nbits++;
                 }
                 /* safety check: shouldn't happen given limited correction-bit buffer */
                 if (nbits > 14)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_HUFF_MISSING_CODE);
                 }
                 EmitACSymbol(acTblNo, nbits << 4);
                 if (nbits != 0)
                 {
                     EmitBitsE((int)EOBRUN, nbits);
                 }
                 EOBRUN = 0;
                 /* Emit any buffered correction bits */
                 EmitBufferedBits(0, BE);
                 BE = 0;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acTblNo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.BE, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBufferedBits(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EOBRUN, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit().
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman().
EmitRestartE()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE (int restart_num) inline private
Definition at line 895 of file HuffmanEntropyEncoder.cs.
         {
             EmitEOBRun();
             if (!gatherStatistics)
             {
                 FlushBitsE();
                 EmitByteE(0xFF);
                 EmitByteE((int)(JpegMarker.RST0 + restart_num));
             }
             if (cinfo.m_Ss == 0)
             {
                 /* Re-initialize DC predictions to 0 */
                 for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
                 {
                     saved.last_dc_val[ci] = 0;
                 }
             }
             else
             {
                 /* Re-initialize all AC-related fields to 0 */
                 EOBRUN = 0;
                 BE = 0;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.BE, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EOBRUN, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.gatherStatistics, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.last_dc_val, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine().
EmitRestartS()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartS (SavableState state, int restart_num) inline private
Emit a restart marker and resynchronize predictions.
Definition at line 867 of file HuffmanEntropyEncoder.cs.
         {
             if (!FlushBitsS(state))
             {
                 return false;
             }
             if (!EmitByteS(0xFF))
             {
                 return false;
             }
             if (!EmitByteS((int)(JpegMarker.RST0 + restart_num)))
             {
                 return false;
             }
             /* Re-initialize DC predictions to 0 */
             for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
             {
                 state.last_dc_val[ci] = 0;
             }
             /* The restart counter is not updated until we successfully write the MCU. */
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsS(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman().
EncodeMcuACFirst()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst (JBlock MCU_data[][]) inline private
MCU encoding for AC initial scan (either spectral selection, or first pass of successive approximation).
Definition at line 1028 of file HuffmanEntropyEncoder.cs.
         {
             /* Emit restart marker if needed */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     EmitRestartE(nextRestartNum);
                 }
             }
             var natural_order = cinfo.natural_order;
             /* Encode the AC coefficients per section G.1.2.2, fig. G.3 */
             /* r = run length of zeros */
             var r = 0;
             for (var k = cinfo.m_Ss; k <= cinfo.m_Se; k++)
             {
                 int temp = MCU_data[0][0][natural_order[k]];
                 if (temp == 0)
                 {
                     r++;
                     continue;
                 }
                 /* We must apply the point transform by Al.  For AC coefficients this
                  * is an integer division with rounding towards 0.  To do this portably
                  * in C, we shift after obtaining the absolute value; so the code is
                  * interwoven with finding the abs value (temp) and output bits (temp2).
                  */
                 int temp2;
                 if (temp < 0)
                 {
                     temp = -temp;       /* temp is abs value of input */
                     temp >>= cinfo.m_Al;        /* apply the point transform */
                     /* For a negative coef, want temp2 = bitwise complement of abs(coef) */
                     temp2 = ~temp;
                 }
                 else
                 {
                     temp >>= cinfo.m_Al;        /* apply the point transform */
                     temp2 = temp;
                 }
                 /* Watch out for case that nonzero coef is zero after point transform */
                 if (temp == 0)
                 {
                     r++;
                     continue;
                 }
                 /* Emit any pending EOBRUN */
                 if (EOBRUN > 0)
                 {
                     EmitEOBRun();
                 }
                 /* if run length > 15, must emit special run-length-16 codes (0xF0) */
                 while (r > 15)
                 {
                     EmitACSymbol(acTblNo, 0xF0);
                     r -= 16;
                 }
                 /* Find the number of bits needed for the magnitude of the coefficient */
                 var nbits = 1;          /* there must be at least one 1 bit */
                 while ((temp >>= 1) != 0)
                 {
                     nbits++;
                 }
                 /* Check for out-of-range coefficient values */
                 if (nbits > MAX_COEF_BITS)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_DCT_COEF);
                 }
                 /* Count/emit Huffman symbol for run length / number of bits */
                 EmitACSymbol(acTblNo, (r << 4) + nbits);
                 /* Emit that number of bits of the value, if positive, */
                 /* or the complement of its magnitude, if negative. */
                 EmitBitsE(temp2, nbits);
                 r = 0;          /* reset zero run length */
             }
             if (r > 0)
             {
                 /* If there are trailing zeroes, */
                 EOBRUN++;      /* count an EOB */
                 if (EOBRUN == 0x7FFF)
                 {
                     EmitEOBRun();   /* force it out to avoid overflow */
                 }
             }
             /* Update restart-interval state too */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     restartsToGo = cinfo.m_restart_interval;
                     nextRestartNum++;
                     nextRestartNum &= 7;
                 }
                 restartsToGo--;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acTblNo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EOBRUN, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_COEF_BITS, BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.nextRestartNum, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
EncodeMcuACRefine()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine (JBlock MCU_data[][]) inline private
MCU encoding for AC successive approximation refinement scan.
Definition at line 1183 of file HuffmanEntropyEncoder.cs.
         {
             /* Emit restart marker if needed */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     EmitRestartE(nextRestartNum);
                 }
             }
             /* Encode the MCU data block */
             /* It is convenient to make a pre-pass to determine the transformed
              * coefficients' absolute values and the EOB position.
              */
             var EOB = 0;
             var natural_order = cinfo.natural_order;
             var absvalues = new int[JpegConstants.DCTSIZE2];
             for (var k = cinfo.m_Ss; k <= cinfo.m_Se; k++)
             {
                 int temp = MCU_data[0][0][natural_order[k]];
                 /* We must apply the point transform by Al.  For AC coefficients this
                  * is an integer division with rounding towards 0.  To do this portably
                  * in C, we shift after obtaining the absolute value.
                  */
                 if (temp < 0)
                 {
                     temp = -temp;       /* temp is abs value of input */
                 }
                 temp >>= cinfo.m_Al;        /* apply the point transform */
                 absvalues[k] = temp;    /* save abs value for main pass */
                 if (temp == 1)
                 {
                     /* EOB = index of last newly-nonzero coef */
                     EOB = k;
                 }
             }
             /* Encode the AC coefficients per section G.1.2.3, fig. G.7 */
             var r = 0;          /* r = run length of zeros */
             uint BR = 0;         /* BR = count of buffered bits added now */
             var bitBufferOffset = BE; /* Append bits to buffer */
             for (var k = cinfo.m_Ss; k <= cinfo.m_Se; k++)
             {
                 var temp = absvalues[k];
                 if (temp == 0)
                 {
                     r++;
                     continue;
                 }
                 /* Emit any required ZRLs, but not if they can be folded into EOB */
                 while (r > 15 && k <= EOB)
                 {
                     /* emit any pending EOBRUN and the BE correction bits */
                     EmitEOBRun();
                     /* Emit ZRL */
                     EmitACSymbol(acTblNo, 0xF0);
                     r -= 16;
                     /* Emit buffered correction bits that must be associated with ZRL */
                     EmitBufferedBits(bitBufferOffset, BR);
                     bitBufferOffset = 0;/* BE bits are gone now */
                     BR = 0;
                 }
                 /* If the coef was previously nonzero, it only needs a correction bit.
                  * NOTE: a straight translation of the spec's figure G.7 would suggest
                  * that we also need to test r > 15.  But if r > 15, we can only get here
                  * if k > EOB, which implies that this coefficient is not 1.
                  */
                 if (temp > 1)
                 {
                     /* The correction bit is the next bit of the absolute value. */
                     bitBuffer[bitBufferOffset + BR] = (char)(temp & 1);
                     BR++;
                     continue;
                 }
                 /* Emit any pending EOBRUN and the BE correction bits */
                 EmitEOBRun();
                 /* Count/emit Huffman symbol for run length / number of bits */
                 EmitACSymbol(acTblNo, (r << 4) + 1);
                 /* Emit output bit for newly-nonzero coef */
                 temp = (MCU_data[0][0][natural_order[k]] < 0) ? 0 : 1;
                 EmitBitsE(temp, 1);
                 /* Emit buffered correction bits that must be associated with this code */
                 EmitBufferedBits(bitBufferOffset, BR);
                 bitBufferOffset = 0;/* BE bits are gone now */
                 BR = 0;
                 r = 0;          /* reset zero run length */
             }
             if (r > 0 || BR > 0)
             {
                 /* If there are trailing zeroes, */
                 EOBRUN++;      /* count an EOB */
                 BE += BR;      /* concat my correction bits to older ones */
                 /* We force out the EOB if we risk either:
                  * 1. overflow of the EOB counter;
                  * 2. overflow of the correction bit buffer during the next MCU.
                  */
                 if (EOBRUN == 0x7FFF || BE > (MAX_CORR_BITS - JpegConstants.DCTSIZE2 + 1))
                 {
                     EmitEOBRun();
                 }
             }
             /* Update restart-interval state too */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     restartsToGo = cinfo.m_restart_interval;
                     nextRestartNum++;
                     nextRestartNum &= 7;
                 }
                 restartsToGo--;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acTblNo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.BE, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.bitBuffer, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBufferedBits(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EOBRUN, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_CORR_BITS, BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.nextRestartNum, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
EncodeMcuDCFirst()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst (JBlock MCU_data[][]) inline private
MCU encoding for DC initial scan (either spectral selection, or first pass of successive approximation).
Definition at line 941 of file HuffmanEntropyEncoder.cs.
         {
             /* Emit restart marker if needed */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     EmitRestartE(nextRestartNum);
                 }
             }
             /* Encode the MCU data blocks */
             for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
             {
                 var ci = cinfo.m_MCU_membership[blkn];
                 var tbl = cinfo.Component_info[cinfo.m_cur_comp_info[ci]].Dc_tbl_no;
                 /* Compute the DC value after the required point transform by Al.
                  * This is simply an arithmetic right shift.
                  */
                 var temp = IRightShift(MCU_data[blkn][0][0], cinfo.m_Al);
                 /* DC differences are figured on the point-transformed values. */
                 var temp2 = temp - saved.last_dc_val[ci];
                 saved.last_dc_val[ci] = temp;
                 /* Encode the DC coefficient difference per section G.1.2.1 */
                 temp = temp2;
                 if (temp < 0)
                 {
                     /* temp is abs value of input */
                     temp = -temp;
                     /* For a negative input, want temp2 = bitwise complement of abs(input) */
                     /* This code assumes we are on a two's complement machine */
                     temp2--;
                 }
                 /* Find the number of bits needed for the magnitude of the coefficient */
                 var nbits = 0;
                 while (temp != 0)
                 {
                     nbits++;
                     temp >>= 1;
                 }
                 /* Check for out-of-range coefficient values.
                  * Since we're encoding a difference, the range limit is twice as much.
                  */
                 if (nbits > MAX_COEF_BITS + 1)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_DCT_COEF);
                 }
                 /* Count/emit the Huffman-coded symbol for the number of bits */
                 EmitDCSymbol(tbl, nbits);
                 /* Emit that number of bits of the value, if positive, */
                 /* or the complement of its magnitude, if negative. */
                 if (nbits != 0)
                 {
                     /* emit_bits rejects calls with size 0 */
                     EmitBitsE(temp2, nbits);
                 }
             }
             /* Update restart-interval state too */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     restartsToGo = cinfo.m_restart_interval;
                     nextRestartNum++;
                     nextRestartNum &= 7;
                 }
                 restartsToGo--;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitDCSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.IRightShift(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.last_dc_val, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_COEF_BITS, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.nextRestartNum, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
EncodeMcuDCRefine()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine (JBlock MCU_data[][]) inline private
MCU encoding for DC successive approximation refinement scan. Note: we assume such scans can be multi-component, although the spec is not very clear on the point.
Definition at line 1145 of file HuffmanEntropyEncoder.cs.
         {
             /* Emit restart marker if needed */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     EmitRestartE(nextRestartNum);
                 }
             }
             /* Encode the MCU data blocks */
             for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
             {
                 /* We simply emit the Al'th bit of the DC coefficient value. */
                 int temp = MCU_data[blkn][0][0];
                 EmitBitsE(temp >> cinfo.m_Al, 1);
             }
             /* Update restart-interval state too */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     restartsToGo = cinfo.m_restart_interval;
                     nextRestartNum++;
                     nextRestartNum &= 7;
                 }
                 restartsToGo--;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.nextRestartNum, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
EncodeMcuDelegate()
delegate bool BitMiracle.LibJpeg.Classic.Internal.JpegEntropyEncoder.EncodeMcuDelegate (JBlock MCU_data[][]) inherited
EncodeMcuGather()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather (JBlock MCU_data[][]) inline private
Trial-encode one MCU's worth of Huffman-compressed coefficients. No data is actually output, so no suspension return is possible.
Definition at line 344 of file HuffmanEntropyEncoder.cs.
         {
             /* Take care of restart intervals if needed */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     /* Re-initialize DC predictions to 0 */
                     for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
                     {
                         saved.last_dc_val[ci] = 0;
                     }
                     /* Update restart state */
                     restartsToGo = cinfo.m_restart_interval;
                 }
                 restartsToGo--;
             }
             for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
             {
                 var ci = cinfo.m_MCU_membership[blkn];
                 var compptr = cinfo.Component_info[cinfo.m_cur_comp_info[ci]];
                 HTestOneBlock(MCU_data[blkn][0].data, saved.last_dc_val[ci],
                     dcCountPtrs[compptr.Dc_tbl_no],
                     acCountPtrs[compptr.Ac_tbl_no]);
                 saved.last_dc_val[ci] = MCU_data[blkn][0][0];
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.last_dc_val, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
EncodeMcuHuffman()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman (JBlock MCU_data[][]) inline private
Encode and output one MCU's worth of Huffman-compressed coefficients.
Definition at line 259 of file HuffmanEntropyEncoder.cs.
         {
             /* Load up working state */
             var state = new SavableState();
             state.ASSIGN_STATE(saved);
             /* Emit restart marker if needed */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     if (!EmitRestartS(state, nextRestartNum))
                     {
                         return false;
                     }
                 }
             }
             /* Encode the MCU data blocks */
             for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
             {
                 var ci = cinfo.m_MCU_membership[blkn];
                 var compptr = cinfo.Component_info[cinfo.m_cur_comp_info[ci]];
                 if (!EncodeOneBlock(state, MCU_data[blkn][0].data, state.last_dc_val[ci],
                     dcDerivedTables[compptr.Dc_tbl_no],
                     acDerivedTables[compptr.Ac_tbl_no]))
                 {
                     return false;
                 }
                 /* Update last_dc_val */
                 state.last_dc_val[ci] = MCU_data[blkn][0][0];
             }
             /* Completed MCU, so update state */
             saved.ASSIGN_STATE(state);
             /* Update restart-interval state too */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     restartsToGo = cinfo.m_restart_interval;
                     nextRestartNum++;
                     nextRestartNum &= 7;
                 }
                 restartsToGo--;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acDerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.ASSIGN_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcDerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.nextRestartNum, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
EncodeOneBlock()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock (SavableState state, short [] block, int last_dc_val, CDerivedTable dctbl, CDerivedTable actbl) inline private
Encode a single block's worth of coefficients
Definition at line 434 of file HuffmanEntropyEncoder.cs.
         {
             /* Encode the DC coefficient difference per section F.1.2.1 */
             var temp = block[0] - last_dc_val;
             var temp2 = temp;
             if (temp < 0)
             {
                 temp = -temp;       /* temp is abs value of input */
                 /* For a negative input, want temp2 = bitwise complement of abs(input) */
                 /* This code assumes we are on a two's complement machine */
                 temp2--;
             }
             /* Find the number of bits needed for the magnitude of the coefficient */
             var nbits = 0;
             while (temp != 0)
             {
                 nbits++;
                 temp >>= 1;
             }
             /* Check for out-of-range coefficient values.
              * Since we're encoding a difference, the range limit is twice as much.
              */
             if (nbits > MAX_COEF_BITS + 1)
             {
                 cinfo.ErrExit(JMessageCode.JERR_BAD_DCT_COEF);
             }
             /* Emit the Huffman-coded symbol for the number of bits */
             if (!EmitBitsS(state, dctbl.ehufco[nbits], dctbl.ehufsi[nbits]))
             {
                 return false;
             }
             /* Emit that number of bits of the value, if positive, */
             /* or the complement of its magnitude, if negative. */
             if (nbits != 0)
             {
                 /* emit_bits rejects calls with size 0 */
                 if (!EmitBitsS(state, temp2, nbits))
                 {
                     return false;
                 }
             }
             /* Encode the AC coefficients per section F.1.2.2 */
             var r = 0;          /* r = run length of zeros */
             var natural_order = cinfo.natural_order;
             var Se = cinfo.lim_Se;
             for (var k = 1; k <= Se; k++)
             {
                 temp2 = block[natural_order[k]];
                 if (temp2 == 0)
                 {
                     r++;
                 }
                 else
                 {
                     /* if run length > 15, must emit special run-length-16 codes (0xF0) */
                     while (r > 15)
                     {
                         if (!EmitBitsS(state, actbl.ehufco[0xF0], actbl.ehufsi[0xF0]))
{
                             return false;
                         }
                         r -= 16;
                     }
                     temp = temp2;
                     if (temp < 0)
                     {
                         temp = -temp;       /* temp is abs value of input */
                         /* This code assumes we are on a two's complement machine */
                         temp2--;
                     }
                     /* Find the number of bits needed for the magnitude of the coefficient */
                     nbits = 1;      /* there must be at least one 1 bit */
                     while ((temp >>= 1) != 0)
                     {
                         nbits++;
                     }
                     /* Check for out-of-range coefficient values */
                     if (nbits > MAX_COEF_BITS)
                     {
                         cinfo.ErrExit(JMessageCode.JERR_BAD_DCT_COEF);
                     }
                     /* Emit Huffman symbol for run length / number of bits */
                     temp = (r << 4) + nbits;
                     if (!EmitBitsS(state, actbl.ehufco[temp], actbl.ehufsi[temp]))
                     {
                         return false;
                     }
                     /* Emit that number of bits of the value, if positive, */
                     /* or the complement of its magnitude, if negative. */
                     if (!EmitBitsS(state, temp2, nbits))
                     {
                         return false;
                     }
                     r = 0;
                 }
             }
             /* If the last coef(s) were zero, emit an end-of-block code */
             if (r > 0)
             {
                 if (!EmitBitsS(state, actbl.ehufco[0], actbl.ehufsi[0]))
                 {
                     return false;
                 }
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.CDerivedTable.ehufco, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.CDerivedTable.ehufsi, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.lim_Se, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_COEF_BITS, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman().
FinishPassDelegate()
delegate void BitMiracle.LibJpeg.Classic.Internal.JpegEntropyEncoder.FinishPassDelegate () inherited
FinishPassGather()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather () inline private
Finish up a statistics-gathering pass and create the new Huffman tables.
Definition at line 380 of file HuffmanEntropyEncoder.cs.
         {
             if (cinfo.m_progressive_mode)
             {
                 /* Flush out buffered data (all we care about is counting the EOB symbol) */
                 EmitEOBRun();
             }
             /* It's important not to apply jpeg_gen_optimal_table more than once
              * per table, because it clobbers the input frequency counts!
              */
             var did_dc = new bool[JpegConstants.NUM_HUFF_TBLS];
             var did_ac = new bool[JpegConstants.NUM_HUFF_TBLS];
             for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
             {
                 var compptr = cinfo.Component_info[cinfo.m_cur_comp_info[ci]];
                 /* DC needs no table for refinement scan */
                 if (cinfo.m_Ss == 0 && cinfo.m_Ah == 0)
                 {
                     var dctbl = compptr.Dc_tbl_no;
                     if (!did_dc[dctbl])
                     {
                         if (cinfo.m_dc_huff_tbl_ptrs[dctbl] is null)
{
                             cinfo.m_dc_huff_tbl_ptrs[dctbl] = new JHuffmanTable();
                         }
                         JpegGenOptimalTable(cinfo.m_dc_huff_tbl_ptrs[dctbl], dcCountPtrs[dctbl]);
                         did_dc[dctbl] = true;
                     }
                 }
                 /* AC needs no table when not present */
                 if (cinfo.m_Se != 0)
                 {
                     var actbl = compptr.Ac_tbl_no;
                     if (!did_ac[actbl])
                     {
                         if (cinfo.m_ac_huff_tbl_ptrs[actbl] is null)
{
                             cinfo.m_ac_huff_tbl_ptrs[actbl] = new JHuffmanTable();
                         }
                         JpegGenOptimalTable(cinfo.m_ac_huff_tbl_ptrs[actbl], acCountPtrs[actbl]);
                         did_ac[actbl] = true;
                     }
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegGenOptimalTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, and BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
FinishPassHuffman()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman () inline private
Finish up at the end of a Huffman-compressed scan.
Definition at line 315 of file HuffmanEntropyEncoder.cs.
         {
             if (cinfo.m_progressive_mode)
             {
                 /* Flush out any buffered data */
                 EmitEOBRun();
                 FlushBitsE();
             }
             else
             {
                 /* Load up working state ... flush_bits needs it */
                 var state = new SavableState();
                 state.ASSIGN_STATE(saved);
                 /* Flush out the last data */
                 if (!FlushBitsS(state))
                 {
                     cinfo.ErrExit(JMessageCode.JERR_CANT_SUSPEND);
                 }
                 /* Update state */
                 saved.ASSIGN_STATE(state);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.ASSIGN_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsS(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
FlushBitsE()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsE () inline private
Definition at line 782 of file HuffmanEntropyEncoder.cs.
         {
             EmitBitsE(0x7F, 7); /* fill any partial byte with ones */
             saved.put_buffer = 0;     /* and reset bit-buffer to empty */
             saved.put_bits = 0;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.put_bits, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.put_buffer, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman().
FlushBitsS()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsS (SavableState state) inline private
Definition at line 770 of file HuffmanEntropyEncoder.cs.
         {
             if (!EmitBitsS(state, 0x7F, 7)) /* fill any partial byte with ones */
             {
                 return false;
             }
             state.put_buffer = 0;  /* and reset bit-buffer to empty */
             state.put_bits = 0;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartS(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman().
HTestOneBlock()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock (short [] block, int last_dc_val, long [] dc_counts, long [] ac_counts) inline private
Huffman coding optimization.
We first scan the supplied data and count the number of uses of each symbol that is to be Huffman-coded. (This process MUST agree with the code above.) Then we build a Huffman coding tree for the observed counts. Symbols which are not needed at all for the particular image are not assigned any code, which saves space in the DHT marker as well as in the compressed data.
Definition at line 566 of file HuffmanEntropyEncoder.cs.
         {
             /* Encode the DC coefficient difference per section F.1.2.1 */
             var temp = block[0] - last_dc_val;
             if (temp < 0)
             {
                 temp = -temp;
             }
             /* Find the number of bits needed for the magnitude of the coefficient */
             var nbits = 0;
             while (temp != 0)
             {
                 nbits++;
                 temp >>= 1;
             }
             /* Check for out-of-range coefficient values.
              * Since we're encoding a difference, the range limit is twice as much.
              */
             if (nbits > MAX_COEF_BITS + 1)
             {
                 cinfo.ErrExit(JMessageCode.JERR_BAD_DCT_COEF);
             }
             /* Count the Huffman symbol for the number of bits */
             dc_counts[nbits]++;
             /* Encode the AC coefficients per section F.1.2.2 */
             var r = 0;          /* r = run length of zeros */
             var Se = cinfo.lim_Se;
             var natural_order = cinfo.natural_order;
             for (var k = 1; k <= Se; k++)
             {
                 temp = block[natural_order[k]];
                 if (temp == 0)
                 {
                     r++;
                 }
                 else
                 {
                     /* if run length > 15, must emit special run-length-16 codes (0xF0) */
                     while (r > 15)
                     {
                         ac_counts[0xF0]++;
                         r -= 16;
                     }
                     /* Find the number of bits needed for the magnitude of the coefficient */
                     if (temp < 0)
                     {
                         temp = -temp;
                     }
                     /* Find the number of bits needed for the magnitude of the coefficient */
                     nbits = 1;      /* there must be at least one 1 bit */
                     while ((temp >>= 1) != 0)
                     {
                         nbits++;
                     }
                     /* Check for out-of-range coefficient values */
                     if (nbits > MAX_COEF_BITS)
                     {
                         cinfo.ErrExit(JMessageCode.JERR_BAD_DCT_COEF);
                     }
                     /* Count Huffman symbol for run length / number of bits */
                     ac_counts[(r << 4) + nbits]++;
                     r = 0;
                 }
             }
             /* If the last coef(s) were zero, emit an end-of-block code */
             if (r > 0)
             {
                 ac_counts[0]++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.lim_Se, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_COEF_BITS, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather().
IRightShift()
static int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.IRightShift (int x, int shft) inline static private
IRIGHT_SHIFT is like RIGHT_SHIFT, but works on int rather than int. We assume that int right shift is unsigned if int right shift is, which should be safe.
Definition at line 927 of file HuffmanEntropyEncoder.cs.
         {
             if (x < 0)
             {
                 return (x >> shft) | ((~0) << (16 - shft));
             }
             return x >> shft;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst().
JpegGenOptimalTable()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegGenOptimalTable (JHuffmanTable htbl, long [] freq) inline protected
Generate the best Huffman code table for the given counts, fill htbl.
The JPEG standard requires that no symbol be assigned a codeword of all one bits (so that padding bits added at the end of a compressed segment can't look like a valid code). Because of the canonical ordering of codewords, this just means that there must be an unused slot in the longest codeword length category. Section K.2 of the JPEG spec suggests reserving such a slot by pretending that symbol 256 is a valid symbol with count 1. In theory that's not optimal; giving it count zero but including it in the symbol set anyway should give a better Huffman code. But the theoretically better code actually seems to come out worse in practice, because it produces more all-ones bytes (which incur stuffed zero bytes in the final file). In any case the difference is tiny.
The JPEG standard requires Huffman codes to be no more than 16 bits long. If some symbols have a very small but nonzero probability, the Huffman tree must be adjusted to meet the code length restriction. We currently use the adjustment method suggested in JPEG section K.2. This method is not optimal; it may not choose the best possible limited-length code. But typically only very-low-frequency symbols will be given less-than-optimal lengths, so the code is almost optimal. Experimental comparisons against an optimal limited-length-code algorithm indicate that the difference is microscopic — usually less than a hundredth of a percent of total size. So the extra complexity of an optimal algorithm doesn't seem worthwhile.
Definition at line 1451 of file HuffmanEntropyEncoder.cs.
         {
             const int MAX_CLEN = 32;     /* assumed maximum initial code length */
             var bits = new byte[MAX_CLEN + 1];   /* bits[k] = # of symbols with code length k */
             var codesize = new int[257];      /* codesize[k] = code length of symbol k */
             var others = new int[257];        /* next symbol in current branch of tree */
             int c1, c2;
             int p, i, j;
             long v;
             /* This algorithm is explained in section K.2 of the JPEG standard */
             for (i = 0; i < 257; i++)
             {
                 others[i] = -1;     /* init links to empty */
             }
             freq[256] = 1;      /* make sure 256 has a nonzero count */
             /* Including the pseudo-symbol 256 in the Huffman procedure guarantees
             * that no real symbol is given code-value of all ones, because 256
             * will be placed last in the largest codeword category.
             */
             /* Huffman's basic algorithm to assign optimal code lengths to symbols */
             for (; ; )
             {
                 /* Find the smallest nonzero frequency, set c1 = its symbol */
                 /* In case of ties, take the larger symbol number */
                 c1 = -1;
                 v = 1000000000L;
                 for (i = 0; i <= 256; i++)
                 {
                     if (freq[i] != 0 && freq[i] <= v)
                     {
                         v = freq[i];
                         c1 = i;
                     }
                 }
                 /* Find the next smallest nonzero frequency, set c2 = its symbol */
                 /* In case of ties, take the larger symbol number */
                 c2 = -1;
                 v = 1000000000L;
                 for (i = 0; i <= 256; i++)
                 {
                     if (freq[i] != 0 && freq[i] <= v && i != c1)
                     {
                         v = freq[i];
                         c2 = i;
                     }
                 }
                 /* Done if we've merged everything into one frequency */
                 if (c2 < 0)
                 {
                     break;
                 }
                 /* Else merge the two counts/trees */
                 freq[c1] += freq[c2];
                 freq[c2] = 0;
                 /* Increment the codesize of everything in c1's tree branch */
                 codesize[c1]++;
                 while (others[c1] >= 0)
                 {
                     c1 = others[c1];
                     codesize[c1]++;
                 }
                 others[c1] = c2;        /* chain c2 onto c1's tree branch */
                 /* Increment the codesize of everything in c2's tree branch */
                 codesize[c2]++;
                 while (others[c2] >= 0)
                 {
                     c2 = others[c2];
                     codesize[c2]++;
                 }
             }
             /* Now count the number of symbols of each code length */
             for (i = 0; i <= 256; i++)
             {
                 if (codesize[i] != 0)
                 {
                     /* The JPEG standard seems to think that this can't happen, */
                     /* but I'm paranoid... */
                     if (codesize[i] > MAX_CLEN)
                     {
                         cinfo.ErrExit(JMessageCode.JERR_HUFF_CLEN_OVERFLOW);
                     }
                     bits[codesize[i]]++;
                 }
             }
             /* JPEG doesn't allow symbols with code lengths over 16 bits, so if the pure
             * Huffman procedure assigned any such lengths, we must adjust the coding.
             * Here is what the JPEG spec says about how this next bit works:
             * Since symbols are paired for the longest Huffman code, the symbols are
             * removed from this length category two at a time.  The prefix for the pair
             * (which is one bit shorter) is allocated to one of the pair; then,
             * skipping the BITS entry for that prefix length, a code word from the next
             * shortest nonzero BITS entry is converted into a prefix for two code words
             * one bit longer.
             */
             for (i = MAX_CLEN; i > 16; i--)
             {
                 while (bits[i] > 0)
                 {
                     j = i - 2;      /* find length of new prefix to be used */
                     while (bits[j] == 0)
                     {
                         j--;
                     }
                     bits[i] -= 2;       /* remove two symbols */
                     bits[i - 1]++;      /* one goes in this length */
                     bits[j + 1] += 2;       /* two new symbols in this length */
                     bits[j]--;      /* symbol of this length is now a prefix */
                 }
             }
             /* Remove the count for the pseudo-symbol 256 from the largest codelength */
             while (bits[i] == 0)        /* find largest codelength still in use */
             {
                 i--;
             }
             bits[i]--;
             /* Return final symbol counts (only for lengths 0..16) */
             Buffer.BlockCopy(bits, 0, htbl.Bits, 0, htbl.Bits.Length);
             /* Return a list of the symbols sorted by code length */
             /* It's not real clear to me why we don't need to consider the codelength
             * changes made above, but the JPEG spec seems to think this works.
             */
             p = 0;
             for (i = 1; i <= MAX_CLEN; i++)
             {
                 for (j = 0; j <= 255; j++)
                 {
                     if (codesize[j] == i)
                     {
                         htbl.Huffval[p] = (byte)j;
                         p++;
                     }
                 }
             }
             /* Set sent_table false so updated table will be written to JPEG file. */
             htbl.SentTable = false;
         }
References BitMiracle.LibJpeg.Classic.JHuffmanTable.Bits, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JHuffmanTable.Huffval, and BitMiracle.LibJpeg.Classic.JHuffmanTable.SentTable.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather().
JpegMakeCDerivedTable()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable (bool isDC, int tblno, ref CDerivedTable dtbl) inline private
Expand a Huffman table definition into the derived format Compute the derived values for a Huffman table. This routine also performs some validation checks on the table.
Definition at line 1323 of file HuffmanEntropyEncoder.cs.
         {
             /* Note that huffsize[] and huffcode[] are filled in code-length order,
             * paralleling the order of the symbols themselves in htbl.huffval[].
             */
             /* Find the input Huffman table */
             if (tblno < 0 || tblno >= JpegConstants.NUM_HUFF_TBLS)
             {
                 cinfo.ErrExit(JMessageCode.JERR_NO_HUFF_TABLE, tblno);
             }
             var htbl = isDC ? cinfo.m_dc_huff_tbl_ptrs[tblno] : cinfo.m_ac_huff_tbl_ptrs[tblno];
             if (htbl is null)
             {
                 cinfo.ErrExit(JMessageCode.JERR_NO_HUFF_TABLE, tblno);
             }
             /* Allocate a workspace if we haven't already done so. */
             if (dtbl is null)
             {
                 dtbl = new CDerivedTable();
             }
             /* Figure C.1: make table of Huffman code length for each symbol */
             var p = 0;
             var huffsize = new char[257];
             for (var l = 1; l <= 16; l++)
             {
                 int i = htbl.Bits[l];
                 if (p + i > 256)    /* protect against table overrun */
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
                 }
                 while (i-- != 0)
                 {
                     huffsize[p++] = (char)l;
                 }
             }
             huffsize[p] = (char)0;
             var lastp = p;
             /* Figure C.2: generate the codes themselves */
             /* We also validate that the counts represent a legal Huffman code tree. */
             var code = 0;
             int si = huffsize[0];
             p = 0;
             var huffcode = new int[257];
             while (huffsize[p] != 0)
             {
                 while (huffsize[p] == si)
                 {
                     huffcode[p++] = code;
                     code++;
                 }
                 /* code is now 1 more than the last code used for codelength si; but
                 * it must still fit in si bits, since no code is allowed to be all ones.
                 */
                 if (code >= (1 << si))
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
                 }
                 code <<= 1;
                 si++;
             }
             /* Figure C.3: generate encoding tables */
             /* These are code and size indexed by symbol value */
             /* Set all codeless symbols to have code length 0;
             * this lets us detect duplicate VAL entries here, and later
             * allows emit_bits to detect any attempt to emit such symbols.
             */
             Array.Clear(dtbl.ehufsi, 0, dtbl.ehufsi.Length);
             /* This is also a convenient place to check for out-of-range
             * and duplicated VAL entries.  We allow 0..255 for AC symbols
             * but only 0..15 for DC.  (We could constrain them further
             * based on data depth and mode, but this seems enough.)
             */
             var maxsymbol = isDC ? 15 : 255;
             for (p = 0; p < lastp; p++)
             {
                 int i = htbl.Huffval[p];
                 if (i > maxsymbol || dtbl.ehufsi[i] != 0)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
                 }
                 dtbl.ehufco[i] = huffcode[p];
                 dtbl.ehufsi[i] = huffsize[p];
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs, and BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
StartPass()
override void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass (bool gather_statistics) inline virtual
Initialize for a Huffman-compressed scan. If gather_statistics is true, we do not output anything during the scan, just count the Huffman symbols used and generate Huffman code tables.
Implements BitMiracle.LibJpeg.Classic.Internal.JpegEntropyEncoder.
Definition at line 118 of file HuffmanEntropyEncoder.cs.
         {
             gatherStatistics = gather_statistics;
             if (gather_statistics)
             {
                 finishPass = FinishPassGather;
             }
             else
             {
                 finishPass = FinishPassHuffman;
             }
             if (cinfo.m_progressive_mode)
             {
                 /* We assume the scan parameters are already validated. */
                 /* Select execution routine */
                 if (cinfo.m_Ah == 0)
                 {
                     if (cinfo.m_Ss == 0)
                     {
                         encodeMcu = EncodeMcuDCFirst;
                     }
                     else
                     {
                         encodeMcu = EncodeMcuACFirst;
                     }
                 }
                 else
                 {
                     if (cinfo.m_Ss == 0)
                     {
                         encodeMcu = EncodeMcuDCRefine;
                     }
                     else
                     {
                         encodeMcu = EncodeMcuACRefine;
                         /* AC refinement needs a correction bit buffer */
                         if (bitBuffer is null)
{
                             bitBuffer = new char[MAX_CORR_BITS];
                         }
                     }
                 }
                 /* Initialize AC stuff */
                 acTblNo = cinfo.Component_info[cinfo.m_cur_comp_info[0]].Ac_tbl_no;
                 EOBRUN = 0;
                 BE = 0;
             }
             else
             {
                 if (gather_statistics)
                 {
                     encodeMcu = EncodeMcuGather;
                 }
                 else
                 {
                     encodeMcu = EncodeMcuHuffman;
                 }
             }
             for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
             {
                 var compptr = cinfo.Component_info[cinfo.m_cur_comp_info[ci]];
                 /* DC needs no table for refinement scan */
                 if (cinfo.m_Ss == 0 && cinfo.m_Ah == 0)
                 {
                     var tbl = compptr.Dc_tbl_no;
                     if (gather_statistics)
                     {
                         /* Check for invalid table index */
                         /* (make_c_derived_tbl does this in the other path) */
                         if (tbl < 0 || tbl >= JpegConstants.NUM_HUFF_TBLS)
{
                             cinfo.ErrExit(JMessageCode.JERR_NO_HUFF_TABLE, tbl);
                         }
                         /* Allocate and zero the statistics tables */
                         /* Note that jpeg_gen_optimal_table expects 257 entries in each table! */
                         if (dcCountPtrs[tbl] is null)
{
                             dcCountPtrs[tbl] = new long[257];
                         }
                         else
{
                             Array.Clear(dcCountPtrs[tbl], 0, dcCountPtrs[tbl].Length);
                         }
                     }
                     else
                     {
                         /* Compute derived values for Huffman tables */
                         /* We may do this more than once for a table, but it's not expensive */
                         JpegMakeCDerivedTable(true, tbl, ref dcDerivedTables[tbl]);
                     }
                     /* Initialize DC predictions to 0 */
                     saved.last_dc_val[ci] = 0;
                 }
                 /* AC needs no table when not present */
                 if (cinfo.m_Se != 0)
                 {
                     var tbl = compptr.Ac_tbl_no;
                     if (gather_statistics)
                     {
                         if (tbl < 0 || tbl >= JpegConstants.NUM_HUFF_TBLS)
{
                             cinfo.ErrExit(JMessageCode.JERR_NO_HUFF_TABLE, tbl);
                         }
                         if (acCountPtrs[tbl] is null)
{
                             acCountPtrs[tbl] = new long[257];
                         }
                         else
{
                             Array.Clear(acCountPtrs[tbl], 0, acCountPtrs[tbl].Length);
                         }
                     }
                     else
                     {
                         JpegMakeCDerivedTable(false, tbl, ref acDerivedTables[tbl]);
                     }
                 }
             }
             /* Initialize bit buffer to empty */
             saved.put_buffer = 0;
             saved.put_bits = 0;
             /* Initialize restart stuff */
             restartsToGo = cinfo.m_restart_interval;
             nextRestartNum = 0;
         }
References BitMiracle.LibJpeg.Classic.JpegComponentInfo.Ac_tbl_no, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acDerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acTblNo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.BE, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.bitBuffer, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcCountPtrs, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcDerivedTables, BitMiracle.LibJpeg.Classic.Internal.JpegEntropyEncoder.encodeMcu, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EOBRUN, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegEntropyEncoder.finishPass, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.gatherStatistics, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.last_dc_val, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_CORR_BITS, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.nextRestartNum, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.put_bits, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.SavableState.put_buffer, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved.
Member Data Documentation
acCountPtrs
readonly long [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acCountPtrs = new long[JpegConstants.NUM_HUFF_TBLS][] private
Definition at line 79 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
acDerivedTables
readonly CDerivedTable [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acDerivedTables = new CDerivedTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 75 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
acTblNo
int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.acTblNo private
Definition at line 89 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
BE
uint BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.BE private
Definition at line 91 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
bitBuffer
char [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.bitBuffer private
Definition at line 92 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBufferedBits(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
cinfo
readonly JpegCompressStruct BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.cinfo private
Definition at line 86 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegGenOptimalTable(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
dcCountPtrs
readonly long [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcCountPtrs = new long[JpegConstants.NUM_HUFF_TBLS][] private
Definition at line 78 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitDCSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
dcDerivedTables
readonly CDerivedTable [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.dcDerivedTables = new CDerivedTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 74 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitDCSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
EOBRUN
uint BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EOBRUN private
Definition at line 90 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
gatherStatistics
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.gatherStatistics private
Definition at line 84 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitACSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBufferedBits(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitDCSymbol(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
MAX_COEF_BITS
const int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_COEF_BITS = 10 private
Definition at line 29 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock().
MAX_CORR_BITS
const int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.MAX_CORR_BITS = 1000 private
Definition at line 36 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
nextRestartNum
int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.nextRestartNum private
Definition at line 71 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
restartsToGo
int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.restartsToGo private
Definition at line 70 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
saved
readonly SavableState BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.saved = new SavableState() private
Definition at line 67 of file HuffmanEntropyEncoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FlushBitsE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
Property Documentation
encodeMcu
EncodeMcuDelegate BitMiracle.LibJpeg.Classic.Internal.JpegEntropyEncoder.encodeMcu get set inherited
Definition at line 11 of file JpegEntropyEncoder.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
finishPass
FinishPassDelegate BitMiracle.LibJpeg.Classic.Internal.JpegEntropyEncoder.finishPass get set inherited
Definition at line 12 of file JpegEntropyEncoder.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/HuffmanEntropyEncoder.cs