Juniper: Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType > Class Template Reference
Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType > Class Template Reference abstract
Public Types
enum InputButtonExt { InputButtonExt.None = 0, InputButtonExt.Left = InputButton.Left + 1, InputButtonExt.Right = InputButton.Right + 1, InputButtonExt.Middle = InputButton.Middle + 1 }
enum FilterType { FilterType.None, FilterType.Kalman, FilterType.IntegrationWithInterpolation }
Public Member Functions
override bool IsButtonPressed (VirtualTouchPadButton button)
override bool IsButtonDown (VirtualTouchPadButton button)
override bool IsButtonUp (VirtualTouchPadButton button)
override void Install ()
override void Uninstall ()
override void Process (PointerEventData evtData, float pixelDragThreshold, GameObject lastTarget)
override bool IsButtonPressed (InputButton button)
override bool IsButtonPressed (int button)
abstract bool IsButtonPressed (ButtonIDType button)
override bool IsButtonUp (InputButton button)
override bool IsButtonUp (int button)
abstract bool IsButtonUp (ButtonIDType button)
override bool IsButtonDown (InputButton button)
override bool IsButtonDown (int button)
abstract bool IsButtonDown (ButtonIDType button)
virtual void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
void Reset ()
virtual void SetProbe (Probe p)
void OnDrawGizmos ()
virtual void Update ()
Static Public Member Functions
static string HandName (HandIDType handID)
Public Attributes
bool IsNonDominantHand => !IsDominantHand
bool Connected
GameObject target
float dragDistance
The distance the pointer has been moved while the primary selection button has been pressed.
float grabDistance
The distance from the pointer origin to the object that was grabbed during a drag operation. This is used to update the location of the pointer on subsequent frames by updating the old raycast result, rather than computing a new one. In this way, we achieve the "Fork Lift" mode in smartphone AR for picking up objects and moving them around by moving our physical bodies.
FilterType filterType
Vector3 MeasuredEndPoint
int filterOrder = 0
int processNoise
float measurementNoise = 1
InputButtonEvent onInputButtonDown
InputButtonEvent onInputButtonUp
InputButtonEvent onInputButtonClick
VirtualTouchPadButtonEvent onVirtualTouchPadButtonDown
VirtualTouchPadButtonEvent onVirtualTouchPadButtonUp
VirtualTouchPadButtonEvent onVirtualTouchPadButtonClick
IntegerEvent onButtonDown
IntegerEvent onButtonUp
IntegerEvent onButtonClick
virtual float MinimumPointerDistance
The minimum distance from the camera at which to place the pointer.
virtual float MaximumPointerDistance
Material LaserPointerMaterial
bool IsEnabled
bool IsDisabled => !IsEnabled
Returns true when the device is supposed to be disabled.
PhysicsRaycaster Raycaster
Camera EventCamera
The camera the pointer uses to point at Canvas objects.
Vector3 InteractionDirection => (InteractionEndPoint - transform.position).normalized
The direction the pointer is pointing, from InteractionOrigin to InteractionEndPoint.
virtual bool AnyButtonPressed
bool showProbe = true
Protected Member Functions
override void InternalUpdate ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
void AddButton (ButtonIDType outButton, InputButton? inButton=null)
void AddButton (VirtualTouchPadButton outButton, InputButton? inButton=null)
void DumpEnum ()
virtual void OnInputButtonDown (InputButton button)
virtual void OnInputButtonUp (InputButton button)
virtual void OnInputButtonClick (InputButton button)
virtual void OnVirtualTouchPadButtonDown (VirtualTouchPadButton button)
virtual void OnVirtualTouchPadButtonUp (VirtualTouchPadButton button)
virtual void OnVirtualTouchPadButtonClick (VirtualTouchPadButton button)
void OnButtonDown (int button)
void OnButtonUp (int button)
void OnButtonClick (int button)
Static Protected Member Functions
static Vector2 Round2Square (Vector2 point)
static Vector2 Square2Round (Vector2 point)
Protected Attributes
UnifiedInputModule config
Probe probe
The cursor probe that shows the physical location of the current selection.
StageExtensions stage
Properties
static HandIDType [] HANDS [get]
abstract Vector2 SquareTouchPoint [get]
abstract Vector2 RoundTouchPoint [get]
abstract bool IsCharging [get]
abstract float BatteryLevel [get]
abstract bool IsLeftHand [get]
abstract bool IsRightHand [get]
abstract bool IsDominantHand [get]
abstract Vector3 Acceleration [get]
abstract Vector3 RotationRate [get]
virtual HandIDType HandID [get, set]
abstract bool TouchPadTouched [get]
abstract bool TouchPadTouchedDown [get]
abstract bool TouchPadTouchedUp [get]
abstract bool TouchPadPressed [get]
abstract bool TouchPadPressedDown [get]
abstract bool TouchPadPressedUp [get]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
AbstractHapticDevice Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
abstract bool IsConnected [get]
Vector3 InteractionEndPoint [get]
The target at and through which the pointer rays fire.
int PointerID [get, private set]
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
string ProbeName [get, private set]
IMotionFilter interactionEndPointFilter [get, private set]
Retrieves the interaction audio system for playing interaction sounds.
Events
Action< object, InputButtonEventArgs > InputButtonDown
Action< object, InputButtonEventArgs > InputButtonUp
Action< object, InputButtonEventArgs > InputButtonClick
Action< object, VirtualTouchPadButtonEventArgs > VirtualTouchPadButtonDown
Action< object, VirtualTouchPadButtonEventArgs > VirtualTouchPadButtonUp
Action< object, VirtualTouchPadButtonEventArgs > VirtualTouchPadButtonClick
Action< object, ButtonEventArgs > ButtonDown
Action< object, ButtonEventArgs > ButtonUp
Action< object, ButtonEventArgs > ButtonClick
Private Member Functions
bool VirtualButtonInBounds (VirtualTouchPadButton button)
Private Attributes
const float BUTTON_RADIUS = 0.25f
const float DIM = 0.75f
Vector2? lastTouchPosition
HandIDType _handID
Static Private Attributes
static readonly Dictionary< VirtualTouchPadButton, Vector2 > BUTTON_CENTERS
static ConfigType probeNameConfig
static HandIDType [] _hands
Detailed Description
Type Constraints
HandIDType : struct
HandIDType : IComparable
ButtonIDType : struct
ButtonIDType : IComparable
ConfigType : AbstractProbeNameConfiguration<HandIDType>
ConfigType : new()
HapticsType : AbstractHapticDevice
Definition at line 11 of file AbstractMotionController.cs.
Member Enumeration Documentation
FilterType
enum Juniper.Input.Pointers.BaseAbstractPointerDevice.FilterType strong inherited
Enumerator
None
Kalman
IntegrationWithInterpolation
Definition at line 105 of file BaseAbstractPointerDevice.cs.
         {
             None,
             Kalman,
             IntegrationWithInterpolation
         }
InputButtonExt
enum Juniper.Input.Pointers.BaseAbstractPointerDevice.InputButtonExt strong inherited
Enumerator
None
Left
Right
Middle
Definition at line 97 of file BaseAbstractPointerDevice.cs.
         {
             None = 0,
             Left = InputButton.Left + 1,
             Right = InputButton.Right + 1,
             Middle = InputButton.Middle + 1
         }
Member Function Documentation
AddButton() [1/2]
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.AddButton (ButtonIDType outButton, InputButton? inButton = null) inline protected inherited
Definition at line 154 of file AbstractPointerDevice.cs.
         {
             nativeToUnity.MaybeAdd(outButton, inButton);
             var t = typeof(ButtonIDType);
             if (t.IsEnum)
             {
                 var value = Convert.ToInt32(outButton);
                 nativeToInt.MaybeAdd(outButton, value);
                 intToNative.MaybeAdd(value, outButton);
             }
             if (inButton != null)
             {
                 unityToNative.MaybeAdd(inButton.Value, outButton);
             }
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.intToNative, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.nativeToInt, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.nativeToUnity, and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.unityToNative.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.DumpEnum().
AddButton() [2/2]
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.AddButton (VirtualTouchPadButton outButton, InputButton? inButton = null) inline protected inherited
Definition at line 171 of file AbstractPointerDevice.cs.
         {
             virtualToUnity.MaybeAdd(outButton, inButton);
             if (inButton != null)
             {
                 unityToVirtual.MaybeAdd(inButton.Value, outButton);
             }
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.unityToVirtual, and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.virtualToUnity.
Awake()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.Awake () inline virtual inherited
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Definition at line 246 of file BaseAbstractPointerDevice.cs.
         {
             Install();
             config = this.FindAny<UnifiedInputModule>();
 #if UNITY_MODULES_AUDIO
             Audio = this.FindAny<InteractionAudio>();
 #endif
             stage = this.FindAny<StageExtensions>();
             ProbeName = name;
             config.AddPointer(this);
         }
References Juniper.Input.UnifiedInputModule.AddPointer(), Juniper.Input.Pointers.BaseAbstractPointerDevice.config, Juniper.Input.Pointers.BaseAbstractPointerDevice.Install(), Juniper.Input.Pointers.BaseAbstractPointerDevice.ProbeName, and Juniper.Input.Pointers.BaseAbstractPointerDevice.stage.
DumpEnum()
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.DumpEnum () inline protected inherited
Definition at line 180 of file AbstractPointerDevice.cs.
         {
             foreach (var value in Enum.GetValues(typeof(ButtonIDType)))
             {
                 AddButton((ButtonIDType)value);
             }
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.AddButton().
HandName()
static string Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.HandName (HandIDType handID) inline static
Definition at line 70 of file AbstractMotionController.cs.
         {
             var t = typeof(HandIDType);
             if (handID.Equals(probeNameConfig.PrimaryHandID))
             {
                 return "PrimaryPointer";
             }
             else if (handID.Equals(probeNameConfig.SecondaryHandID))
             {
                 return "SecondaryPointer";
             }
             else if (t.IsEnum)
             {
                 return "MotionController" + Convert.ChangeType(handID, t.GetEnumUnderlyingType());
             }
             else
             {
                 return "MotionController" + handID;
             }
         }
Install()
override void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Install () virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
InternalUpdate()
override void Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.InternalUpdate () inline protected virtual
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
Definition at line 148 of file AbstractMotionController.cs.
         {
             if (TouchPadTouched)
             {
                 var touchPos = SquareTouchPoint;
                 if (lastTouchPosition != null)
                 {
                     ScrollDelta = touchPos - lastTouchPosition.Value;
                 }
                 lastTouchPosition = touchPos;
             }
             else
             {
                 ScrollDelta = Vector2.zero;
                 lastTouchPosition = null;
             }
             if (probe != null)
             {
                 probe.TouchPoint = RoundTouchPoint;
             }
         }
IsButtonDown() [1/4]
override bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonDown (VirtualTouchPadButton button) virtual
Reimplemented from Juniper.Input.Pointers.BaseAbstractPointerDevice.
IsButtonDown() [2/4]
override bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonDown (InputButton button) virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
IsButtonDown() [3/4]
override bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonDown (int button) virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
IsButtonDown() [4/4]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonDown (ButtonIDType button) pure virtual inherited
IsButtonPressed() [1/4]
override bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonPressed (VirtualTouchPadButton button) virtual
Reimplemented from Juniper.Input.Pointers.BaseAbstractPointerDevice.
IsButtonPressed() [2/4]
override bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonPressed (InputButton button) virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
IsButtonPressed() [3/4]
override bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonPressed (int button) virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
IsButtonPressed() [4/4]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonPressed (ButtonIDType button) pure virtual inherited
IsButtonUp() [1/4]
override bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonUp (VirtualTouchPadButton button) virtual
Reimplemented from Juniper.Input.Pointers.BaseAbstractPointerDevice.
IsButtonUp() [2/4]
override bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonUp (InputButton button) virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
IsButtonUp() [3/4]
override bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonUp (int button) virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
IsButtonUp() [4/4]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonUp (ButtonIDType button) pure virtual inherited
OnButtonClick()
void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonClick (int button) inline protected inherited
Definition at line 407 of file BaseAbstractPointerDevice.cs.
         {
             onButtonClick?.Invoke(button);
             ButtonClick?.Invoke(this, new ButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.ButtonClick, and Juniper.Input.Pointers.BaseAbstractPointerDevice.onButtonClick.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnButtonDown()
void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonDown (int button) inline protected inherited
Definition at line 395 of file BaseAbstractPointerDevice.cs.
         {
             onButtonDown?.Invoke(button);
             ButtonDown?.Invoke(this, new ButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.ButtonDown, and Juniper.Input.Pointers.BaseAbstractPointerDevice.onButtonDown.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnButtonUp()
void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonUp (int button) inline protected inherited
Definition at line 401 of file BaseAbstractPointerDevice.cs.
         {
             onButtonUp?.Invoke(button);
             ButtonUp?.Invoke(this, new ButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.ButtonUp, and Juniper.Input.Pointers.BaseAbstractPointerDevice.onButtonUp.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnDrawGizmos()
void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnDrawGizmos () inline inherited
Definition at line 281 of file BaseAbstractPointerDevice.cs.
         {
             if (Application.isPlaying)
             {
                 Gizmos.color = Color.green;
                 Gizmos.DrawWireSphere(InteractionEndPoint, 0.1f);
                 Gizmos.color = Color.red;
                 Gizmos.DrawWireSphere(MeasuredEndPoint, 0.075f);
             }
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.InteractionEndPoint, and Juniper.Input.Pointers.BaseAbstractPointerDevice.MeasuredEndPoint.
OnInputButtonClick()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonClick (InputButton button) inline protected virtual inherited
Definition at line 371 of file BaseAbstractPointerDevice.cs.
         {
             onInputButtonClick?.Invoke(button);
             InputButtonClick?.Invoke(this, new InputButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.InputButtonClick, and Juniper.Input.Pointers.BaseAbstractPointerDevice.onInputButtonClick.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnInputButtonDown()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonDown (InputButton button) inline protected virtual inherited
Definition at line 359 of file BaseAbstractPointerDevice.cs.
         {
             onInputButtonDown?.Invoke(button);
             InputButtonDown?.Invoke(this, new InputButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.InputButtonDown, and Juniper.Input.Pointers.BaseAbstractPointerDevice.onInputButtonDown.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnInputButtonUp()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonUp (InputButton button) inline protected virtual inherited
Definition at line 365 of file BaseAbstractPointerDevice.cs.
         {
             onInputButtonUp?.Invoke(button);
             InputButtonUp?.Invoke(this, new InputButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.InputButtonUp, and Juniper.Input.Pointers.BaseAbstractPointerDevice.onInputButtonUp.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnVirtualTouchPadButtonClick()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonClick (VirtualTouchPadButton button) inline protected virtual inherited
Definition at line 389 of file BaseAbstractPointerDevice.cs.
         {
             onVirtualTouchPadButtonClick?.Invoke(button);
             VirtualTouchPadButtonClick?.Invoke(this, new VirtualTouchPadButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.onVirtualTouchPadButtonClick, and Juniper.Input.Pointers.BaseAbstractPointerDevice.VirtualTouchPadButtonClick.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnVirtualTouchPadButtonDown()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonDown (VirtualTouchPadButton button) inline protected virtual inherited
Definition at line 377 of file BaseAbstractPointerDevice.cs.
         {
             onVirtualTouchPadButtonDown?.Invoke(button);
             VirtualTouchPadButtonDown?.Invoke(this, new VirtualTouchPadButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.onVirtualTouchPadButtonDown, and Juniper.Input.Pointers.BaseAbstractPointerDevice.VirtualTouchPadButtonDown.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
OnVirtualTouchPadButtonUp()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonUp (VirtualTouchPadButton button) inline protected virtual inherited
Definition at line 383 of file BaseAbstractPointerDevice.cs.
         {
             onVirtualTouchPadButtonUp?.Invoke(button);
             VirtualTouchPadButtonUp?.Invoke(this, new VirtualTouchPadButtonEventArgs(this, button));
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.onVirtualTouchPadButtonUp, and Juniper.Input.Pointers.BaseAbstractPointerDevice.VirtualTouchPadButtonUp.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process().
Process()
override void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Process (PointerEventData evtData, float pixelDragThreshold, GameObject lastTarget) inline virtual inherited
Implements Juniper.Input.Pointers.BaseAbstractPointerDevice.
Definition at line 33 of file AbstractPointerDevice.cs.
         {
             foreach (var button in nativeToUnity.Keys)
             {
                 evtData.button = nativeToUnity[button] ?? InputButton.Left;
                 var up = IsButtonUp(button);
                 var down = IsButtonDown(button);
                 var pressed = IsButtonPressed(button);
                 if (down)
                 {
                     inputButtonDownTime[evtData.button] = Time.time;
                     if (nativeToUnity.ContainsKey(button))
                     {
                         OnInputButtonDown(evtData.button);
                     }
                     if (nativeToInt.ContainsKey(button))
                     {
                         OnButtonDown(nativeToInt[button]);
                     }
                 }
                 if (up)
                 {
                     if (nativeToUnity.ContainsKey(button))
                     {
                         OnInputButtonUp(evtData.button);
                     }
                     if (nativeToInt.ContainsKey(button))
                     {
                         OnButtonUp(nativeToInt[button]);
                     }
                     if (inputButtonDownTime.ContainsKey(evtData.button)
                         && (Time.time - inputButtonDownTime[evtData.button]) >= CLICK_THRESHOLD)
                     {
                         if (nativeToUnity.ContainsKey(button))
{
                             OnInputButtonClick(evtData.button);
                         }
                         if (nativeToInt.ContainsKey(button))
{
                             OnButtonClick(nativeToInt[button]);
                         }
                     }
                 }
                 ProcessButton(
                     evtData,
                     pixelDragThreshold,
                     lastTarget,
                     pressed,
                     down,
                     up);
             }
             foreach (var button in virtualToUnity.Keys)
             {
                 evtData.button = virtualToUnity[button] ?? InputButton.Left;
                 var up = IsButtonUp(button);
                 var down = IsButtonDown(button);
                 var pressed = IsButtonPressed(button);
                 if (down)
                 {
                     virtualTouchPadButtonDownTime[button] = Time.time;
                     OnVirtualTouchPadButtonDown(button);
                 }
                 if (up)
                 {
                     OnVirtualTouchPadButtonUp(button);
                     if (virtualTouchPadButtonDownTime.ContainsKey(button)
                         && (Time.time - virtualTouchPadButtonDownTime[button]) >= CLICK_THRESHOLD)
                     {
                         OnVirtualTouchPadButtonClick(button);
                     }
                 }
                 ProcessButton(
                     evtData,
                     pixelDragThreshold,
                     lastTarget,
                     pressed,
                     down,
                     up);
             }
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.CLICK_THRESHOLD, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.inputButtonDownTime, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonDown(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonPressed(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.IsButtonUp(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.nativeToInt, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.nativeToUnity, Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonClick(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonDown(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonUp(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonClick(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonDown(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonUp(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonClick(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonDown(), Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonUp(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.ProcessButton(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.virtualTouchPadButtonDownTime, and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.virtualToUnity.
Reset()
void Juniper.Input.Pointers.BaseAbstractPointerDevice.Reset () inherited
Round2Square()
static Vector2 Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Round2Square (Vector2 point) inline static protected
Definition at line 112 of file AbstractMotionController.cs.
         {
             var pLen = point.magnitude;
             if (pLen > 0)
             {
                 var onUnitCircle = point / pLen;
                 float mx = Mathf.Abs(onUnitCircle.x),
                     my = Mathf.Abs(onUnitCircle.y);
                 var onUnitSquare = onUnitCircle;
                 if (mx > my)
                 {
                     onUnitSquare /= mx;
                 }
                 else if (my > 0)
                 {
                     onUnitSquare /= my;
                 }
                 point *= onUnitSquare.magnitude;
             }
             return point;
         }
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.Square2Round().
SetProbe()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.SetProbe (Probe p) inline virtual inherited
Definition at line 268 of file BaseAbstractPointerDevice.cs.
         {
             if (probe != p)
             {
                 if (probe != null)
                 {
                     probe.gameObject.Destroy();
                 }
                 probe = p ?? FindProbe();
             }
         }
References Juniper.Input.Pointers.BaseAbstractPointerDevice.FindProbe(), and Juniper.Input.Pointers.BaseAbstractPointerDevice.probe.
Square2Round()
static Vector2 Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Square2Round (Vector2 point) inline static protected
Definition at line 136 of file AbstractMotionController.cs.
         {
             var pLen = point.magnitude;
             if (pLen > 0)
             {
                 var onUnitCircle = point / pLen;
                 var onUnitSquare = Round2Square(onUnitCircle);
                 point /= onUnitSquare.magnitude;
             }
             return point;
         }
Uninstall()
override void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.Uninstall () inline virtual inherited
Reimplemented from Juniper.Input.Pointers.BaseAbstractPointerDevice.
Definition at line 26 of file AbstractPointerDevice.cs.
         {
             base.Uninstall();
             this.RemoveComponent<AbstractHapticDevice>();
         }
Update()
virtual void Juniper.Input.Pointers.BaseAbstractPointerDevice.Update () inline virtual inherited
Definition at line 292 of file BaseAbstractPointerDevice.cs.
         {
             Connected = IsConnected;
             probe?.AlignProbe(InteractionDirection, transform.up, MaximumPointerDistance);
             if (IsEnabled)
             {
                 InternalUpdate();
             }
             if (probe != null)
             {
                 probe.SetActive(IsEnabled && showProbe);
                 probe.LaserPointerMaterial = LaserPointerMaterial;
             }
             lastProbe = probe;
         }
References Juniper.Input.Pointers.Probe.AlignProbe(), Juniper.Input.Pointers.BaseAbstractPointerDevice.Connected, Juniper.Input.Pointers.BaseAbstractPointerDevice.InteractionDirection, Juniper.Input.Pointers.BaseAbstractPointerDevice.InternalUpdate(), Juniper.Input.Pointers.BaseAbstractPointerDevice.IsConnected, Juniper.Input.Pointers.BaseAbstractPointerDevice.IsEnabled, Juniper.Input.Pointers.Probe.LaserPointerMaterial, Juniper.Input.Pointers.BaseAbstractPointerDevice.LaserPointerMaterial, Juniper.Input.Pointers.BaseAbstractPointerDevice.lastProbe, Juniper.Input.Pointers.BaseAbstractPointerDevice.MaximumPointerDistance, Juniper.Input.Pointers.BaseAbstractPointerDevice.probe, and Juniper.Input.Pointers.BaseAbstractPointerDevice.showProbe.
VirtualButtonInBounds()
bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.VirtualButtonInBounds (VirtualTouchPadButton button) inline private
Definition at line 197 of file AbstractMotionController.cs.
         {
             if (button == VirtualTouchPadButton.Any)
             {
                 return true;
             }
             else if (BUTTON_CENTERS.ContainsKey(button))
             {
                 var delta = SquareTouchPoint - BUTTON_CENTERS[button];
                 return delta.magnitude <= BUTTON_RADIUS;
             }
             else
             {
                 return false;
             }
         }
Member Data Documentation
_handID
HandIDType Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >._handID private
Definition at line 195 of file AbstractMotionController.cs.
_hands
HandIDType [] Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >._hands static private
Definition at line 191 of file AbstractMotionController.cs.
AnyButtonPressed
virtual bool Juniper.Input.Pointers.BaseAbstractPointerDevice.AnyButtonPressed inherited
Initial value:
=>
            IsButtonPressed(InputButton.Left)
            || IsButtonPressed(InputButton.Right)
            || IsButtonPressed(InputButton.Middle)
            || IsButtonPressed(VirtualTouchPadButton.Any)
Definition at line 237 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.ProcessButton().
BUTTON_CENTERS
readonly Dictionary<VirtualTouchPadButton, Vector2> Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.BUTTON_CENTERS static private
Initial value:
= new Dictionary<VirtualTouchPadButton, Vector2>
        {
            { VirtualTouchPadButton.Center, new Vector2(0, 0) },
            { VirtualTouchPadButton.Top, new Vector2(0, DIM) },
            { VirtualTouchPadButton.Right, new Vector2(DIM, 0) },
            { VirtualTouchPadButton.Bottom, new Vector2(0, -DIM) },
            { VirtualTouchPadButton.Left, new Vector2(-DIM, 0) },
            { VirtualTouchPadButton.TopLeft, new Vector2(DIM, -DIM) },
            { VirtualTouchPadButton.TopRight, new Vector2(DIM, DIM) },
            { VirtualTouchPadButton.BottomLeft, new Vector2(-DIM, -DIM) },
            { VirtualTouchPadButton.BottomRight, new Vector2(DIM, -DIM) },
        }
Definition at line 174 of file AbstractMotionController.cs.
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.VirtualButtonInBounds().
BUTTON_RADIUS
const float Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.BUTTON_RADIUS = 0.25f private
Definition at line 171 of file AbstractMotionController.cs.
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.VirtualButtonInBounds().
config
UnifiedInputModule Juniper.Input.Pointers.BaseAbstractPointerDevice.config protected inherited
Definition at line 332 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Awake().
Connected
bool Juniper.Input.Pointers.BaseAbstractPointerDevice.Connected inherited
Definition at line 25 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Update().
DIM
const float Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.DIM = 0.75f private
Definition at line 172 of file AbstractMotionController.cs.
dragDistance
float Juniper.Input.Pointers.BaseAbstractPointerDevice.dragDistance inherited
The distance the pointer has been moved while the primary selection button has been pressed.
Definition at line 34 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.TestDrag().
EventCamera
Camera Juniper.Input.Pointers.BaseAbstractPointerDevice.EventCamera inherited
Initial value:
=>
            probe?.EventCamera
The camera the pointer uses to point at Canvas objects.
Definition at line 156 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.UnifiedInputModule.UpdateRay().
filterOrder
int Juniper.Input.Pointers.BaseAbstractPointerDevice.filterOrder = 0 inherited
Definition at line 53 of file BaseAbstractPointerDevice.cs.
filterType
FilterType Juniper.Input.Pointers.BaseAbstractPointerDevice.filterType inherited
Definition at line 47 of file BaseAbstractPointerDevice.cs.
grabDistance
float Juniper.Input.Pointers.BaseAbstractPointerDevice.grabDistance inherited
The distance from the pointer origin to the object that was grabbed during a drag operation. This is used to update the location of the pointer on subsequent frames by updating the old raycast result, rather than computing a new one. In this way, we achieve the "Fork Lift" mode in smartphone AR for picking up objects and moving them around by moving our physical bodies.
Definition at line 45 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.ProcessButton().
InteractionDirection
Vector3 Juniper.Input.Pointers.BaseAbstractPointerDevice.InteractionDirection => (InteractionEndPoint - transform.position).normalized inherited
The direction the pointer is pointing, from InteractionOrigin to InteractionEndPoint.
The interaction direction.
Definition at line 163 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Update(), and Juniper.Input.UnifiedInputModule.UpdateRay().
IsDisabled
bool Juniper.Input.Pointers.BaseAbstractPointerDevice.IsDisabled => !IsEnabled inherited
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 148 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.HoverCraft.Update().
IsEnabled
bool Juniper.Input.Pointers.BaseAbstractPointerDevice.IsEnabled inherited
Initial value:
=>
            isActiveAndEnabled && IsConnected
Definition at line 141 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Update().
IsNonDominantHand
bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsNonDominantHand => !IsDominantHand
Definition at line 52 of file AbstractMotionController.cs.
LaserPointerMaterial
Material Juniper.Input.Pointers.BaseAbstractPointerDevice.LaserPointerMaterial inherited
Definition at line 121 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Update().
lastTouchPosition
Vector2? Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.lastTouchPosition private
Definition at line 193 of file AbstractMotionController.cs.
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.InternalUpdate().
MaximumPointerDistance
virtual float Juniper.Input.Pointers.BaseAbstractPointerDevice.MaximumPointerDistance inherited
Initial value:
=>
            Mathf.Min(10f, 0.9f * CameraExtensions.MainCamera.farClipPlane)
Definition at line 118 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Update().
MeasuredEndPoint
Vector3 Juniper.Input.Pointers.BaseAbstractPointerDevice.MeasuredEndPoint inherited
Definition at line 50 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnDrawGizmos().
measurementNoise
float Juniper.Input.Pointers.BaseAbstractPointerDevice.measurementNoise = 1 inherited
Definition at line 59 of file BaseAbstractPointerDevice.cs.
MinimumPointerDistance
virtual float Juniper.Input.Pointers.BaseAbstractPointerDevice.MinimumPointerDistance inherited
Initial value:
=>
            Mathf.Max(1.5f, 1.1f * CameraExtensions.MainCamera.nearClipPlane)
The minimum distance from the camera at which to place the pointer.
Definition at line 115 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.UnifiedInputModule.UpdateRay().
onButtonClick
IntegerEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onButtonClick inherited
Definition at line 77 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonClick().
onButtonDown
IntegerEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onButtonDown inherited
Definition at line 73 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonDown().
onButtonUp
IntegerEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onButtonUp inherited
Definition at line 75 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonUp().
onInputButtonClick
InputButtonEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onInputButtonClick inherited
Definition at line 65 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonClick().
onInputButtonDown
InputButtonEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onInputButtonDown inherited
Definition at line 61 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonDown().
onInputButtonUp
InputButtonEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onInputButtonUp inherited
Definition at line 63 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonUp().
onVirtualTouchPadButtonClick
VirtualTouchPadButtonEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onVirtualTouchPadButtonClick inherited
Definition at line 71 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonClick().
onVirtualTouchPadButtonDown
VirtualTouchPadButtonEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onVirtualTouchPadButtonDown inherited
Definition at line 67 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonDown().
onVirtualTouchPadButtonUp
VirtualTouchPadButtonEvent Juniper.Input.Pointers.BaseAbstractPointerDevice.onVirtualTouchPadButtonUp inherited
Definition at line 69 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonUp().
probe
Probe Juniper.Input.Pointers.BaseAbstractPointerDevice.probe protected inherited
The cursor probe that shows the physical location of the current selection.
Definition at line 339 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.InternalUpdate(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.ProcessButton(), Juniper.Input.Pointers.BaseAbstractPointerDevice.SetProbe(), and Juniper.Input.Pointers.BaseAbstractPointerDevice.Update().
probeNameConfig
ConfigType Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.probeNameConfig static private
Definition at line 189 of file AbstractMotionController.cs.
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.HandName().
processNoise
int Juniper.Input.Pointers.BaseAbstractPointerDevice.processNoise inherited
Definition at line 56 of file BaseAbstractPointerDevice.cs.
Raycaster
PhysicsRaycaster Juniper.Input.Pointers.BaseAbstractPointerDevice.Raycaster inherited
Initial value:
=>
            probe?.Raycaster
Definition at line 150 of file BaseAbstractPointerDevice.cs.
showProbe
bool Juniper.Input.Pointers.BaseAbstractPointerDevice.showProbe = true inherited
Definition at line 334 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Update().
stage
StageExtensions Juniper.Input.Pointers.BaseAbstractPointerDevice.stage protected inherited
Definition at line 342 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Awake().
target
GameObject Juniper.Input.Pointers.BaseAbstractPointerDevice.target inherited
Definition at line 28 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.ProcessButton(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.TestEnterExit(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.TestUpDown().
Property Documentation
Acceleration
abstract Vector3 Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Acceleration get
Definition at line 54 of file AbstractMotionController.cs.
 { get; }
BatteryLevel
abstract float Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.BatteryLevel get
Definition at line 44 of file AbstractMotionController.cs.
 { get; }
EventTarget
IEventSystemHandler Juniper.Input.Pointers.BaseAbstractPointerDevice.EventTarget get set inherited
Definition at line 124 of file BaseAbstractPointerDevice.cs.
 { get; set; }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.ProcessButton(), and Juniper.Input.HoverCraft.Update().
HandID
virtual HandIDType Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.HandID get set
Definition at line 59 of file AbstractMotionController.cs.
         {
             get => _handID;
             set
             {
                 if (!HandID.Equals(value))
                 {
                     _handID = value;
                 }
             }
         }
HANDS
HandIDType [] Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.HANDS static get
Definition at line 19 of file AbstractMotionController.cs.
         {
             get
             {
                 if (_hands == null)
                 {
                     if (probeNameConfig == null)
                     {
                         probeNameConfig = new ConfigType();
                     }
                     _hands = probeNameConfig
                         .Values
                         .Distinct()
                         .ToArray();
                 }
                 return _hands;
             }
         }
Haptics
AbstractHapticDevice Juniper.Input.Pointers.BaseAbstractPointerDevice.Haptics get protected set inherited
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 137 of file BaseAbstractPointerDevice.cs.
 { get; protected set; }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType >.ProcessButton().
InteractionEndPoint
Vector3 Juniper.Input.Pointers.BaseAbstractPointerDevice.InteractionEndPoint get inherited
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 170 of file BaseAbstractPointerDevice.cs.
         {
             get
             {
                 MeasuredEndPoint = transform.position + (MinimumPointerDistance * transform.forward);
                 if (filterOrder == 0 || filterType == FilterType.None)
                 {
                     return MeasuredEndPoint;
                 }
                 else
                 {
                     if (filterType != lastFilterType)
                     {
                         interactionEndPointFilter = null;
                         lastFilterType = filterType;
                     }
                     if (interactionEndPointFilter == null)
                     {
                         if (filterType == FilterType.IntegrationWithInterpolation)
{
                             interactionEndPointFilter = new IntegrationpMotionFilter();
                         }
                         else if (filterType == FilterType.Kalman)
{
                             interactionEndPointFilter = new KalmanMotionFilter();
                         }
                     }
                     interactionEndPointFilter.Update(MeasuredEndPoint, filterOrder, measurementNoise, processNoise);
                     return interactionEndPointFilter.Position;
                 }
             }
         }
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnDrawGizmos(), and Juniper.Input.UnifiedInputModule.UpdateRay().
interactionEndPointFilter
IMotionFilter Juniper.Input.Pointers.BaseAbstractPointerDevice.interactionEndPointFilter get private set protected inherited
Retrieves the interaction audio system for playing interaction sounds.
Definition at line 351 of file BaseAbstractPointerDevice.cs.
 { get; private set; }
IsCharging
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsCharging get
Definition at line 42 of file AbstractMotionController.cs.
 { get; }
IsConnected
abstract bool Juniper.Input.Pointers.BaseAbstractPointerDevice.IsConnected get inherited
Definition at line 139 of file BaseAbstractPointerDevice.cs.
 { get; }
Referenced by Juniper.Input.Pointers.GazePointer.InternalUpdate(), and Juniper.Input.Pointers.BaseAbstractPointerDevice.Update().
IsDominantHand
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsDominantHand get
Definition at line 50 of file AbstractMotionController.cs.
 { get; }
IsLeftHand
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsLeftHand get
Definition at line 46 of file AbstractMotionController.cs.
 { get; }
IsRightHand
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsRightHand get
Definition at line 48 of file AbstractMotionController.cs.
 { get; }
LockedOnTarget
bool Juniper.Input.Pointers.BaseAbstractPointerDevice.LockedOnTarget get set inherited
Definition at line 123 of file BaseAbstractPointerDevice.cs.
 { get; set; }
Referenced by Juniper.Input.UnifiedInputModule.UpdateRay().
PointerID
int Juniper.Input.Pointers.BaseAbstractPointerDevice.PointerID get private set inherited
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
The pointer identifier.
Definition at line 210 of file BaseAbstractPointerDevice.cs.
 { get; private set; }
ProbeName
string Juniper.Input.Pointers.BaseAbstractPointerDevice.ProbeName get private set inherited
Definition at line 213 of file BaseAbstractPointerDevice.cs.
         {
             get => _probeName;
             private set
             {
                 if (value != ProbeName)
                 {
                     if (probe != null)
                     {
                         probe.gameObject.Destroy();
                         probe = null;
                     }
                     _probeName = value;
                     if (ProbeName != null)
                     {
                         PointerID = ProbeName.GetHashCode();
                     }
                     SetProbe(FindProbe());
                 }
             }
         }
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.Awake(), and Juniper.Input.Pointers.BaseAbstractPointerDevice.FindProbe().
RotationRate
abstract Vector3 Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.RotationRate get
Definition at line 56 of file AbstractMotionController.cs.
 { get; }
RoundTouchPoint
abstract Vector2 Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.RoundTouchPoint get
Definition at line 40 of file AbstractMotionController.cs.
 { get; }
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.InternalUpdate().
ScrollDelta
Vector2 Juniper.Input.Pointers.BaseAbstractPointerDevice.ScrollDelta get protected set inherited
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 130 of file BaseAbstractPointerDevice.cs.
 { get; protected set; }
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.InternalUpdate().
SquareTouchPoint
abstract Vector2 Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.SquareTouchPoint get
Definition at line 38 of file AbstractMotionController.cs.
 { get; }
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.InternalUpdate(), and Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.VirtualButtonInBounds().
TouchPadPressed
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadPressed get protected
Definition at line 106 of file AbstractMotionController.cs.
 { get; }
TouchPadPressedDown
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadPressedDown get protected
Definition at line 108 of file AbstractMotionController.cs.
 { get; }
TouchPadPressedUp
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadPressedUp get protected
Definition at line 110 of file AbstractMotionController.cs.
 { get; }
TouchPadTouched
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadTouched get protected
Definition at line 100 of file AbstractMotionController.cs.
 { get; }
Referenced by Juniper.Input.Pointers.AbstractMotionController< int, KeyCode, NoProbeNameConfiguration, NoHaptics >.InternalUpdate().
TouchPadTouchedDown
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadTouchedDown get protected
Definition at line 102 of file AbstractMotionController.cs.
 { get; }
TouchPadTouchedUp
abstract bool Juniper.Input.Pointers.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadTouchedUp get protected
Definition at line 104 of file AbstractMotionController.cs.
 { get; }
Event Documentation
ButtonClick
Action<object, ButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.ButtonClick inherited
Definition at line 95 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonClick().
ButtonDown
Action<object, ButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.ButtonDown inherited
Definition at line 91 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonDown().
ButtonUp
Action<object, ButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.ButtonUp inherited
Definition at line 93 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnButtonUp().
InputButtonClick
Action<object, InputButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.InputButtonClick inherited
Definition at line 83 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonClick().
InputButtonDown
Action<object, InputButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.InputButtonDown inherited
Definition at line 79 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonDown().
InputButtonUp
Action<object, InputButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.InputButtonUp inherited
Definition at line 81 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnInputButtonUp().
VirtualTouchPadButtonClick
Action<object, VirtualTouchPadButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.VirtualTouchPadButtonClick inherited
Definition at line 89 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonClick().
VirtualTouchPadButtonDown
Action<object, VirtualTouchPadButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.VirtualTouchPadButtonDown inherited
Definition at line 85 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonDown().
VirtualTouchPadButtonUp
Action<object, VirtualTouchPadButtonEventArgs> Juniper.Input.Pointers.BaseAbstractPointerDevice.VirtualTouchPadButtonUp inherited
Definition at line 87 of file BaseAbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.BaseAbstractPointerDevice.OnVirtualTouchPadButtonUp().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Input/Pointers/AbstractMotionController.cs