Juniper: Juniper.Unity.Haptics.WindowsMRHaptics Class Reference
Juniper.Unity.Haptics.WindowsMRHaptics Class Reference
Public Member Functions
override void Play (HapticExpression expr)
Play a canned haptic pattern.
override void Cancel ()
Cancel vibrationa
override void Play (params HapticPatternElement[] points)
Play a haptic pattern.
override void Play (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
override void Play (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
override void Vibrate (HapticPatternElement point)
Play a single element of a haptic pattern.
override void Vibrate (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
override void Vibrate (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
Protected Member Functions
override IEnumerator VibrateCoroutine (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
virtual IEnumerator VibrateCoroutine (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
virtual IEnumerator PlayCoroutine (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
virtual IEnumerator PlayCoroutine (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
Properties
uint ControllerID [get, set]
Private Member Functions
async void GetController ()
Private Attributes
SimpleHapticsController controller
Dictionary< ushort, SimpleHapticsControllerFeedback > expressions
SimpleHapticsControllerFeedback buzz
SimpleHapticsControllerFeedback click
SimpleHapticsControllerFeedback press
SimpleHapticsControllerFeedback release
uint _controllerID
Detailed Description
Definition at line 15 of file WindowsMRHaptics.cs.
Member Function Documentation
Cancel()
override void Juniper.Unity.Haptics.WindowsMRHaptics.Cancel () inline virtual
Cancel vibrationa
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 114 of file WindowsMRHaptics.cs.
         {
             base.Cancel();
             controller?.StopFeedback();
         }
References Juniper.Unity.Haptics.WindowsMRHaptics.controller.
GetController()
async void Juniper.Unity.Haptics.WindowsMRHaptics.GetController () inline private
Definition at line 35 of file WindowsMRHaptics.cs.
         {
             var access = await VibrationDevice.RequestAccessAsync();
             if (access == VibrationAccessStatus.Allowed)
             {
                 var mgr = SpatialInteractionManager.GetForCurrentView();
                 var calendar = new Calendar();
                 var timestamp = PerceptionTimestampHelper.FromHistoricalTargetTime(calendar.GetDateTime());
                 controller = (from s in mgr.GetDetectedSourcesAtTimestamp(timestamp)
                               where s.Source.Id == ControllerID
                               select s.Source.Controller.SimpleHapticsController)
                             .FirstOrDefault();
                 expressions = new Dictionary<ushort, SimpleHapticsControllerFeedback>();
                 if (controller != null)
                 {
                     foreach (var fb in controller.SupportedFeedback)
                     {
                         if (fb.Waveform == KnownSimpleHapticsControllerWaveforms.BuzzContinuous)
{
                             buzz = fb;
                         }
                         else if (fb.Waveform == KnownSimpleHapticsControllerWaveforms.Click)
{
                             click = fb;
                         }
                         else if (fb.Waveform == KnownSimpleHapticsControllerWaveforms.Press)
{
                             press = fb;
                         }
                         else if (fb.Waveform == KnownSimpleHapticsControllerWaveforms.Release)
{
                             release = fb;
                         }
                         expressions[fb.Waveform] = fb;
                     }
                 }
             }
         }
References Juniper.Unity.Haptics.WindowsMRHaptics.buzz, Juniper.Unity.Haptics.WindowsMRHaptics.click, Juniper.Unity.Haptics.WindowsMRHaptics.controller, Juniper.Unity.Haptics.WindowsMRHaptics.ControllerID, Juniper.Unity.Haptics.WindowsMRHaptics.expressions, Juniper.Unity.Haptics.WindowsMRHaptics.press, and Juniper.Unity.Haptics.WindowsMRHaptics.release.
Play() [1/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (params HapticPatternElement [] points) inline virtual inherited
Play a haptic pattern.
Parameters
points
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 32 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(points));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [2/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern) inline virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 59 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [3/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern, float [] amplitudes) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 69 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern, amplitudes));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [4/4]
override void Juniper.Unity.Haptics.WindowsMRHaptics.Play (HapticExpression expr) inline virtual
Play a canned haptic pattern.
Parameters
expr
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 78 of file WindowsMRHaptics.cs.
         {
             if (controller != null)
             {
                 if (expr == HapticExpression.Click)
                 {
                     controller.SendHapticFeedback(click);
                 }
                 else if (expr == HapticExpression.Press)
                 {
                     controller.SendHapticFeedback(press);
                 }
                 else if (expr == HapticExpression.Release)
                 {
                     controller.SendHapticFeedback(release);
                 }
                 else
                 {
                     base.Play(expr);
                 }
             }
         }
References Juniper.Unity.Haptics.WindowsMRHaptics.click, Juniper.Unity.Haptics.WindowsMRHaptics.controller, Juniper.Unity.Haptics.WindowsMRHaptics.press, and Juniper.Unity.Haptics.WindowsMRHaptics.release.
PlayCoroutine() [1/2]
virtual IEnumerator Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern) inline protected virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Definition at line 97 of file AbstractHapticExpressor.cs.
         {
             float amplitude = 1;
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitude);
                 amplitude = 1 - amplitude;
             }
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Referenced by Juniper.Unity.Haptics.AbstractHapticExpressor.Play().
PlayCoroutine() [2/2]
virtual IEnumerator Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern, float [] amplitudes) inline protected virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Definition at line 112 of file AbstractHapticExpressor.cs.
         {
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitudes[i]);
             }
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [1/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (HapticPatternElement point) inline virtual inherited
Play a single element of a haptic pattern.
Parameters
point
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 41 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(point));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [2/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds) inline virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 50 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [3/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds, float amplitude) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 79 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds, amplitude));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
VibrateCoroutine() [1/2]
virtual IEnumerator Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine (long milliseconds) inline protected virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Definition at line 88 of file AbstractHapticExpressor.cs.
         {
             yield return VibrateCoroutine(milliseconds, 1);
         }
Referenced by Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine(), Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate(), and Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
VibrateCoroutine() [2/2]
override IEnumerator Juniper.Unity.Haptics.WindowsMRHaptics.VibrateCoroutine (long milliseconds, float amplitude) inline protected virtual
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 101 of file WindowsMRHaptics.cs.
         {
             var seconds = Units.Milliseconds.Seconds(milliseconds);
             if (expressions.ContainsKey(KnownSimpleHapticsControllerWaveforms.BuzzContinuous))
             {
                 controller?.SendHapticFeedbackForDuration(
                     expressions[KnownSimpleHapticsControllerWaveforms.BuzzContinuous],
                     amplitude,
                     TimeSpan.FromSeconds(seconds));
             }
             yield return new WaitForSeconds(seconds);
         }
References Juniper.Unity.Haptics.WindowsMRHaptics.controller, Juniper.Unity.Haptics.WindowsMRHaptics.expressions, and Juniper.Units.Milliseconds.Seconds().
Member Data Documentation
_controllerID
uint Juniper.Unity.Haptics.WindowsMRHaptics._controllerID private
Definition at line 24 of file WindowsMRHaptics.cs.
buzz
SimpleHapticsControllerFeedback Juniper.Unity.Haptics.WindowsMRHaptics.buzz private
Definition at line 19 of file WindowsMRHaptics.cs.
Referenced by Juniper.Unity.Haptics.WindowsMRHaptics.GetController().
click
SimpleHapticsControllerFeedback Juniper.Unity.Haptics.WindowsMRHaptics.click private
Definition at line 20 of file WindowsMRHaptics.cs.
Referenced by Juniper.Unity.Haptics.WindowsMRHaptics.GetController(), and Juniper.Unity.Haptics.WindowsMRHaptics.Play().
controller
SimpleHapticsController Juniper.Unity.Haptics.WindowsMRHaptics.controller private
Definition at line 17 of file WindowsMRHaptics.cs.
Referenced by Juniper.Unity.Haptics.WindowsMRHaptics.Cancel(), Juniper.Unity.Haptics.WindowsMRHaptics.GetController(), Juniper.Unity.Haptics.WindowsMRHaptics.Play(), and Juniper.Unity.Haptics.WindowsMRHaptics.VibrateCoroutine().
expressions
Dictionary<ushort, SimpleHapticsControllerFeedback> Juniper.Unity.Haptics.WindowsMRHaptics.expressions private
Definition at line 18 of file WindowsMRHaptics.cs.
Referenced by Juniper.Unity.Haptics.WindowsMRHaptics.GetController(), and Juniper.Unity.Haptics.WindowsMRHaptics.VibrateCoroutine().
press
SimpleHapticsControllerFeedback Juniper.Unity.Haptics.WindowsMRHaptics.press private
Definition at line 21 of file WindowsMRHaptics.cs.
Referenced by Juniper.Unity.Haptics.WindowsMRHaptics.GetController(), and Juniper.Unity.Haptics.WindowsMRHaptics.Play().
release
SimpleHapticsControllerFeedback Juniper.Unity.Haptics.WindowsMRHaptics.release private
Definition at line 22 of file WindowsMRHaptics.cs.
Referenced by Juniper.Unity.Haptics.WindowsMRHaptics.GetController(), and Juniper.Unity.Haptics.WindowsMRHaptics.Play().
Property Documentation
ControllerID
uint Juniper.Unity.Haptics.WindowsMRHaptics.ControllerID get set
Definition at line 26 of file WindowsMRHaptics.cs.
         {
             get { return _controllerID; }
             set
             {
                 _controllerID = value;
                 GetController();
             }
         }
Referenced by Juniper.Unity.Haptics.WindowsMRHaptics.GetController().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/WindowsMR/WindowsMRHaptics.cs