Juniper: Juniper.Widgets.TabPanelMenu Class Reference
Juniper.Widgets.TabPanelMenu Class Reference
Public Member Functions
void Awake ()
void Show (string name)
Private Member Functions
void ActivateButton (TabPanelButton clickedButton)
Private Attributes
TabPanelButton [] tabButtons
Detailed Description
Definition at line 7 of file TabPanelMenu.cs.
Member Function Documentation
ActivateButton()
void Juniper.Widgets.TabPanelMenu.ActivateButton (TabPanelButton clickedButton) inline private
Definition at line 37 of file TabPanelMenu.cs.
         {
             foreach (var tabButton in tabButtons)
             {
                 tabButton.SetActive(tabButton == clickedButton);
             }
         }
References Juniper.Widgets.TabPanelMenu.tabButtons.
Referenced by Juniper.Widgets.TabPanelMenu.Awake(), and Juniper.Widgets.TabPanelMenu.Show().
Awake()
void Juniper.Widgets.TabPanelMenu.Awake () inline
Definition at line 9 of file TabPanelMenu.cs.
         {
             tabButtons = GetComponentsInChildren<TabPanelButton>();
             foreach (var tabButton in tabButtons)
             {
                 tabButton.SetActive(true);
                 tabButton.AddListener(() =>
                     ActivateButton(tabButton));
             }
             if (tabButtons.Length > 0)
             {
                 ActivateButton(tabButtons.First());
             }
         }
References Juniper.Widgets.TabPanelMenu.ActivateButton(), and Juniper.Widgets.TabPanelMenu.tabButtons.
Show()
void Juniper.Widgets.TabPanelMenu.Show (string name) inline
Definition at line 26 of file TabPanelMenu.cs.
         {
             var child = transform.Find(name);
             if (child != null)
             {
                 ActivateButton(child.GetComponent<TabPanelButton>());
             }
         }
References Juniper.Widgets.TabPanelMenu.ActivateButton().
Member Data Documentation
tabButtons
TabPanelButton [] Juniper.Widgets.TabPanelMenu.tabButtons private
Definition at line 35 of file TabPanelMenu.cs.
Referenced by Juniper.Widgets.TabPanelMenu.ActivateButton(), and Juniper.Widgets.TabPanelMenu.Awake().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/TabPanelMenu.cs