Juniper: Juniper.Widgets.AttentionDirector Class Reference
Juniper.Widgets.AttentionDirector Class Reference
Shows a pointer that directs the user to where to look next.
Public Member Functions
void Play (string anim)
Play one of the animations on the attention director.
void Awake ()
Get the pointer graphic objects, the main camera, the animator, and the main view system. Disable the graphics for the pointer.
void Scan (Action onFound)
Executes an animation that tells the user that they should be searching for a target.
void Scan ()
IEnumerator ScanCoroutine (Action onFound)
Executes an animation that tells the user that they should be searching for a target.
IEnumerator ScanCoroutine ()
void Found ()
Executes an animation and a sound indicating to the user that the target has been found.
void Lost ()
Executes an animation and a sound indicating to the user that the target has been lost.
IEnumerator SetTargetCoroutine (Component target)
Set the attention director to targeting a specific object, without showing the optional center image.
void SetTarget (Component target, Action onTargetFound)
Set the attention director to targeting a specific object, without showing the optional center image.
void Update ()
Updates the pointer graphics if the option to show them has changed, and checks to see how close we are to the target, updating the location of the arrow graphic if we haven't found it yet, or activating the callback function if we have.
Public Attributes
float shrinkSpeed = 0.5f
How quickly the object should vanish away
float minDistance = 0.01f
The threshold at which to consider an object "in view"
Properties
Vector3 Target [get]
The point we are trying to find with the attention director.
Private Member Functions
IEnumerator PlayAction (Interaction action, string animation)
Private Attributes
Action onTargetFound
The callback to execute when the target is found.
Transform targetTrans
The optional object we are targeting.
Transform lastTargetTrans
The object we were targeting in the last frame.
Vector3 targetPos
The position in space that we are targeting, if there is no distinct target object.
Vector3 lastTargetPosition
The position in space that we were targeting last frame.
Transform pointer
The pointer graphic.
Transform arrow
The arrow on the edge of the pointer graphic, pointer the user to the direction to turn.
Vector3 tagRange
The offset from the center at which the arrow is located.
Transform image
An optional image to display in the center of the attention director. Maybe use it for displaying instructions to the user the first time they see the attention director.
bool showImage
Whether or not to show the optional center image.
bool showPointer
Whether or not to show the pointer graphic at all.
bool wasShowImage
Whether or not the optional center image was visible in the last frame.
bool wasShowPointer
Whether or not the pointer graphic was visible in the last frame.
AbstractAnimator animator
An optional animation object to show different attention director states.
InteractionAudio interaction
Detailed Description
Shows a pointer that directs the user to where to look next.
Definition at line 27 of file AttentionDirector.cs.
Member Function Documentation
Awake()
void Juniper.Widgets.AttentionDirector.Awake () inline
Get the pointer graphic objects, the main camera, the animator, and the main view system. Disable the graphics for the pointer.
Definition at line 170 of file AttentionDirector.cs.
         {
 #if UNITY_MODULES_AUDIO
             Find.Any(out interaction);
 #endif
             pointer = transform.Find("Pointer");
             arrow = pointer.Find("Tag");
             tagRange = arrow.localPosition;
             image = transform.Find("Image");
 #if UNITY_MODULES_ANIMATION
             animator = this.Ensure<UnityAnimator>();
 #endif
             pointer.SetActive(false);
             image.SetActive(false);
         }
References Juniper.Widgets.AttentionDirector.animator, Juniper.Widgets.AttentionDirector.arrow, Juniper.Widgets.AttentionDirector.image, Juniper.Widgets.AttentionDirector.interaction, Juniper.Widgets.AttentionDirector.pointer, and Juniper.Widgets.AttentionDirector.tagRange.
Found()
void Juniper.Widgets.AttentionDirector.Found () inline
Executes an animation and a sound indicating to the user that the target has been found.
Definition at line 239 of file AttentionDirector.cs.
         {
             this.Run(PlayAction(Interaction.Success, "Found"));
         }
References Juniper.Widgets.AttentionDirector.PlayAction().
Lost()
void Juniper.Widgets.AttentionDirector.Lost () inline
Executes an animation and a sound indicating to the user that the target has been lost.
Definition at line 247 of file AttentionDirector.cs.
         {
             this.Run(PlayAction(Interaction.Error, "Lost"));
         }
References Juniper.Widgets.AttentionDirector.PlayAction().
Play()
void Juniper.Widgets.AttentionDirector.Play (string anim) inline
Play one of the animations on the attention director.
Parameters
anim Animation.
Definition at line 156 of file AttentionDirector.cs.
         {
 #if UNITY_MODULES_ANIMATION
             if (animator != null)
             {
                 animator.Play(anim);
             }
 #endif
         }
References Juniper.Widgets.AttentionDirector.animator, and Juniper.Animation.AbstractAnimator.Play().
PlayAction()
IEnumerator Juniper.Widgets.AttentionDirector.PlayAction (Interaction action, string animation) inline private
Definition at line 219 of file AttentionDirector.cs.
         {
             this.Activate();
 #if UNITY_MODULES_AUDIO
             if (interaction != null)
             {
                 interaction.PlayAction(action, transform);
             }
 #endif
 #if UNITY_MODULES_ANIMATION
             return animator.PlayCoroutine(animation);
 #else
             return null;
 #endif
         }
References Juniper.Widgets.AttentionDirector.animator, Juniper.Widgets.AttentionDirector.interaction, and Juniper.Animation.AbstractAnimator.PlayCoroutine().
Referenced by Juniper.Widgets.AttentionDirector.Found(), and Juniper.Widgets.AttentionDirector.Lost().
Scan() [1/2]
void Juniper.Widgets.AttentionDirector.Scan (Action onFound) inline
Executes an animation that tells the user that they should be searching for a target.
Definition at line 190 of file AttentionDirector.cs.
         {
             this.Run(ScanCoroutine(onFound));
         }
References Juniper.Widgets.AttentionDirector.ScanCoroutine().
Scan() [2/2]
void Juniper.Widgets.AttentionDirector.Scan () inline
Definition at line 195 of file AttentionDirector.cs.
         {
             Scan(null);
         }
ScanCoroutine() [1/2]
IEnumerator Juniper.Widgets.AttentionDirector.ScanCoroutine (Action onFound) inline
Executes an animation that tells the user that they should be searching for a target.
Definition at line 203 of file AttentionDirector.cs.
         {
             this.Activate();
             SetTarget(null, onFound);
 #if UNITY_MODULES_ANIMATION
             return animator.PlayCoroutine("Scan");
 #else
             return null;
 #endif
         }
References Juniper.Widgets.AttentionDirector.animator, Juniper.Animation.AbstractAnimator.PlayCoroutine(), and Juniper.Widgets.AttentionDirector.SetTarget().
ScanCoroutine() [2/2]
IEnumerator Juniper.Widgets.AttentionDirector.ScanCoroutine () inline
Definition at line 214 of file AttentionDirector.cs.
         {
             return ScanCoroutine(null);
         }
Referenced by Juniper.Widgets.AttentionDirector.Scan().
SetTarget()
void Juniper.Widgets.AttentionDirector.SetTarget (Component target, Action onTargetFound) inline
Set the attention director to targeting a specific object, without showing the optional center image.
Parameters
target Target.
onTargetFound On target found.
Definition at line 274 of file AttentionDirector.cs.
         {
             this.Activate();
             if (target != null)
             {
                 targetTrans = target.transform;
                 showImage = false;
                 showPointer = true;
             }
             else
             {
                 showImage = true;
                 showPointer = false;
             }
             this.onTargetFound = onTargetFound;
         }
References Juniper.Widgets.AttentionDirector.onTargetFound, Juniper.Widgets.AttentionDirector.showImage, Juniper.Widgets.AttentionDirector.showPointer, and Juniper.Widgets.AttentionDirector.targetTrans.
Referenced by Juniper.Widgets.AttentionDirector.ScanCoroutine(), and Juniper.Widgets.AttentionDirector.SetTargetCoroutine().
SetTargetCoroutine()
IEnumerator Juniper.Widgets.AttentionDirector.SetTargetCoroutine (Component target) inline
Set the attention director to targeting a specific object, without showing the optional center image.
Returns
The target coroutine.
Parameters
target Target.
Definition at line 258 of file AttentionDirector.cs.
         {
             var found = false;
             SetTarget(target, () => found = true);
             while (!found)
             {
                 yield return null;
             }
         }
References Juniper.Widgets.AttentionDirector.SetTarget().
Update()
void Juniper.Widgets.AttentionDirector.Update () inline
Updates the pointer graphics if the option to show them has changed, and checks to see how close we are to the target, updating the location of the arrow graphic if we haven't found it yet, or activating the callback function if we have.
Definition at line 297 of file AttentionDirector.cs.
         {
             if (showImage != wasShowImage)
             {
                 image.SetActive(showImage);
             }
             if (showPointer != wasShowPointer)
             {
                 pointer.SetActive(showPointer);
             }
             var origin = transform.position;
             var fwd = transform.forward;
             if (!targetTrans.IsActivated())
             {
                 targetTrans = null;
             }
             if (Target != Vector3.zero)
             {
                 var dir = (Target - origin).normalized;
                 var right = Vector3.Dot(dir, transform.right) * transform.right;
                 var up = Vector3.Dot(dir, transform.up) * transform.up;
                 var point = up + right;
                 pointer.rotation = Quaternion.LookRotation(point, transform.forward);
                 var toTarget = DisplayManager.MainCamera.WorldToViewportPoint(Target);
                 toTarget.z = 0;
                 var targetDistance = toTarget.magnitude / 2;
                 arrow.localPosition = Mathf.Clamp01(targetDistance) * tagRange;
                 var distance = 1 - Vector3.Dot(fwd, dir);
                 if (distance < minDistance && onTargetFound != null)
                 {
                     // The callback could call AttentionDirector::Target, so if we call onTargetFound
                     // before nulling it, we'll break the callback.
                     var cb = onTargetFound;
                     onTargetFound = null;
                     cb();
                 }
             }
 #if UNITY_EDITOR
             if (UnityEngine.Input.GetKeyDown(KeyCode.F)
                 && Find.Any(out RunningMovement mouse))
             {
                 mouse.transform.LookAt(Target, Vector3.up);
             }
 #endif
             wasShowImage = showImage;
             wasShowPointer = showPointer;
         }
References Juniper.Widgets.AttentionDirector.arrow, Juniper.Widgets.AttentionDirector.image, Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.Widgets.AttentionDirector.minDistance, Juniper.Widgets.AttentionDirector.onTargetFound, Juniper.Widgets.AttentionDirector.pointer, Juniper.Widgets.AttentionDirector.showImage, Juniper.Widgets.AttentionDirector.showPointer, Juniper.Widgets.AttentionDirector.tagRange, Juniper.Widgets.AttentionDirector.Target, Juniper.Widgets.AttentionDirector.targetTrans, Juniper.Widgets.AttentionDirector.wasShowImage, and Juniper.Widgets.AttentionDirector.wasShowPointer.
Member Data Documentation
animator
AbstractAnimator Juniper.Widgets.AttentionDirector.animator private
An optional animation object to show different attention director states.
Definition at line 110 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Awake(), Juniper.Widgets.AttentionDirector.Play(), Juniper.Widgets.AttentionDirector.PlayAction(), and Juniper.Widgets.AttentionDirector.ScanCoroutine().
arrow
Transform Juniper.Widgets.AttentionDirector.arrow private
The arrow on the edge of the pointer graphic, pointer the user to the direction to turn.
Definition at line 73 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Awake(), and Juniper.Widgets.AttentionDirector.Update().
image
Transform Juniper.Widgets.AttentionDirector.image private
An optional image to display in the center of the attention director. Maybe use it for displaying instructions to the user the first time they see the attention director.
Definition at line 84 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Awake(), and Juniper.Widgets.AttentionDirector.Update().
interaction
InteractionAudio Juniper.Widgets.AttentionDirector.interaction private
Definition at line 114 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Awake(), and Juniper.Widgets.AttentionDirector.PlayAction().
lastTargetPosition
Vector3 Juniper.Widgets.AttentionDirector.lastTargetPosition private
The position in space that we were targeting last frame.
Definition at line 63 of file AttentionDirector.cs.
lastTargetTrans
Transform Juniper.Widgets.AttentionDirector.lastTargetTrans private
The object we were targeting in the last frame.
Definition at line 53 of file AttentionDirector.cs.
minDistance
float Juniper.Widgets.AttentionDirector.minDistance = 0.01f
The threshold at which to consider an object "in view"
Definition at line 38 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Update().
onTargetFound
Action Juniper.Widgets.AttentionDirector.onTargetFound private
The callback to execute when the target is found.
Definition at line 43 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.SetTarget(), and Juniper.Widgets.AttentionDirector.Update().
pointer
Transform Juniper.Widgets.AttentionDirector.pointer private
The pointer graphic.
Definition at line 68 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Awake(), and Juniper.Widgets.AttentionDirector.Update().
showImage
bool Juniper.Widgets.AttentionDirector.showImage private
Whether or not to show the optional center image.
Definition at line 89 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.SetTarget(), and Juniper.Widgets.AttentionDirector.Update().
showPointer
bool Juniper.Widgets.AttentionDirector.showPointer private
Whether or not to show the pointer graphic at all.
Definition at line 94 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.SetTarget(), and Juniper.Widgets.AttentionDirector.Update().
shrinkSpeed
float Juniper.Widgets.AttentionDirector.shrinkSpeed = 0.5f
How quickly the object should vanish away
Definition at line 32 of file AttentionDirector.cs.
tagRange
Vector3 Juniper.Widgets.AttentionDirector.tagRange private
The offset from the center at which the arrow is located.
Definition at line 78 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Awake(), and Juniper.Widgets.AttentionDirector.Update().
targetPos
Vector3 Juniper.Widgets.AttentionDirector.targetPos private
The position in space that we are targeting, if there is no distinct target object.
Definition at line 58 of file AttentionDirector.cs.
targetTrans
Transform Juniper.Widgets.AttentionDirector.targetTrans private
The optional object we are targeting.
Definition at line 48 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.SetTarget(), and Juniper.Widgets.AttentionDirector.Update().
wasShowImage
bool Juniper.Widgets.AttentionDirector.wasShowImage private
Whether or not the optional center image was visible in the last frame.
Definition at line 99 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Update().
wasShowPointer
bool Juniper.Widgets.AttentionDirector.wasShowPointer private
Whether or not the pointer graphic was visible in the last frame.
Definition at line 104 of file AttentionDirector.cs.
Referenced by Juniper.Widgets.AttentionDirector.Update().
Property Documentation
Target
Vector3 Juniper.Widgets.AttentionDirector.Target get
The point we are trying to find with the attention director.
Definition at line 121 of file AttentionDirector.cs.
         {
             get
             {
                 if (targetTrans != lastTargetTrans
                     || targetTrans != null
                     && targetTrans.position != lastTargetPosition)
                 {
                     if (targetTrans == null)
                     {
                         lastTargetPosition = targetPos = Vector3.zero;
                         showPointer = false;
                     }
                     else
                     {
                         lastTargetPosition = targetTrans.position;
                         var tt = targetTrans
                             .GetComponentsInChildren<Tooltipable>()
                             .Select(t => t.tooltip)
                             .ToArray();
                         targetPos = targetTrans
                             .gameObject
                             .Center(tt);
                     }
                     lastTargetTrans = targetTrans;
                 }
                 return targetPos;
             }
         }
Referenced by Juniper.Widgets.AttentionDirector.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Widgets/AttentionDirector.cs