Juniper: Juniper.Unity.Widgets.VideoVader Class Reference
Juniper.Unity.Widgets.VideoVader Class Reference
Manages the life-cycle of a video that can be faded out or faded in.
Public Member Functions
void Awake ()
Retrieves the video player and its fader.
void FireComplete ()
override void Enter ()
Start the transition animation in the forward direction.
override void SkipEnter ()
Jump the transition to the ENTERED state, without animating through the ENTERING state.
override void Exit ()
Start the transition animation in the outward direction.
override void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Public Attributes
float restartTimeout = 10
The number of seconds a video may remain hidden until it resets to the beginning.
float lingerTimeout = 0
The number of second to wait after the video has ended to trigger the next state.
UnityEvent onComplete = new UnityEvent()
A Unity Event that fires when the video has finished playing.
float minAlpha = 0
The minimum opacity of the object, where 0 = completely transparent.
float maxAlpha = 1
The maximum opacity of the object, where 1 = completely opaque.
float length = 0.25f
The amount of time it takes to complete the transition.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
override void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
override void RenderValue (float value)
Updates the size of the transitioning object every frame the transition is active.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Properties
override float TransitionLength [get]
The amount of time it takes to complete the transition.
float DeltaAlpha [get]
The scale range the transition has to traverse.
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler< ValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Member Functions
void RestartVideo ()
Reset the video to the beginning if the user lost tracking for a long time.
void Finish ()
Trigger the timeout for the finisher.
void OnFinish ()
Finish out the video state.
Private Attributes
VideoPlayer player
The vide player that is to be faded in and out.
Detailed Description
Manages the life-cycle of a video that can be faded out or faded in.
Definition at line 13 of file VideoVader.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Widgets.VideoVader.Awake () inline
Retrieves the video player and its fader.
Definition at line 42 of file VideoVader.cs.
         {
 #if UNITY_MODULES_VIDEO
             player = GetComponent<VideoPlayer>();
             this.EnsureComponent<DetectVideoEnd>()
                 .Value
                 .onVideoEnd
                 .AddListener(Finish);
 #endif
         }
References Juniper.Unity.Widgets.VideoVader.Finish(), and Juniper.Unity.Widgets.VideoVader.player.
Enter()
override void Juniper.Unity.Animation.AbstractTransitionController.Enter () inline virtual inherited
Start the transition animation in the forward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 63 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.Enter();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.Widgets.TeleportPad.OnClick(), Juniper.Unity.MasterSceneController.QuitCoroutine(), Juniper.Unity.Widgets.Openable.SetOpen(), and Juniper.Unity.Animation.WorkflowStep.Show().
Exit()
override void Juniper.Unity.Animation.AbstractTransitionController.Exit () inline virtual inherited
Start the transition animation in the outward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 84 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Reverse);
             base.Exit();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.Unity.Widgets.Openable.SetOpen().
Finish()
void Juniper.Unity.Widgets.VideoVader.Finish () inline private
Trigger the timeout for the finisher.
Definition at line 86 of file VideoVader.cs.
         {
             Invoke(nameof(OnFinish), lingerTimeout);
         }
References Juniper.Unity.Widgets.VideoVader.lingerTimeout, and Juniper.Unity.Widgets.VideoVader.OnFinish().
Referenced by Juniper.Unity.Widgets.VideoVader.Awake(), and Juniper.Unity.Widgets.VideoVader.FireComplete().
FireComplete()
void Juniper.Unity.Widgets.VideoVader.FireComplete () inline
Definition at line 78 of file VideoVader.cs.
         {
             Finish();
         }
References Juniper.Unity.Widgets.VideoVader.Finish().
HasCompleted()
bool Juniper.Unity.AbstractStateController.HasCompleted () inline inherited
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 121 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.Unity.AbstractStateController.IsComplete.
OnDisable()
void Juniper.Unity.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 298 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.Unity.AbstractStateController.OnExited().
OnEnable()
void Juniper.Unity.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 193 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.Unity.AbstractStateController.OnEntering().
Referenced by Juniper.Unity.AbstractStateController.SkipEnter().
OnEntered()
virtual void Juniper.Unity.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 240 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntered?.Invoke();
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entered, Juniper.Unity.AbstractStateController.onEntered, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Update().
OnEntering()
override void Juniper.Unity.Widgets.VideoVader.OnEntering () inline protected virtual
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 63 of file VideoVader.cs.
         {
             base.OnEntering();
             CancelInvoke(nameof(RestartVideo));
 #if UNITY_MODULES_VIDEO
             player.Stop();
             player.Play();
 #endif
         }
References Juniper.Unity.Widgets.VideoVader.player, and Juniper.Unity.Widgets.VideoVader.RestartVideo().
OnExited()
virtual void Juniper.Unity.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, and Juniper.Unity.SubSceneController.
Definition at line 310 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExited?.Invoke();
                 Exited?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Exited, Juniper.Unity.AbstractStateController.onExited, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnDisable().
OnExiting()
override void Juniper.Unity.Widgets.VideoVader.OnExiting () inline protected virtual
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 73 of file VideoVader.cs.
         {
             Invoke(nameof(RestartVideo), restartTimeout);
         }
References Juniper.Unity.Widgets.VideoVader.restartTimeout, and Juniper.Unity.Widgets.VideoVader.RestartVideo().
OnFinish()
void Juniper.Unity.Widgets.VideoVader.OnFinish () inline private
Finish out the video state.
Definition at line 94 of file VideoVader.cs.
         {
             onComplete?.Invoke();
         }
References Juniper.Unity.Widgets.VideoVader.onComplete.
Referenced by Juniper.Unity.Widgets.VideoVader.Finish().
RenderValue()
override void Juniper.Unity.Widgets.VideoVader.RenderValue (float value) inline protected virtual
Updates the size of the transitioning object every frame the transition is active.
Parameters
value
Reimplemented from Juniper.Unity.Animation.AlphaTransition.
Definition at line 99 of file VideoVader.cs.
         {
 #if UNITY_MODULES_VIDEO
             if (player.renderMode == VideoRenderMode.CameraNearPlane
                || player.renderMode == VideoRenderMode.CameraFarPlane)
             {
                 var o = Mathf.Clamp01(minAlpha + value * DeltaAlpha);
                 player.targetCameraAlpha = o;
             }
             else
             {
 #endif
                 base.RenderValue(value);
 #if UNITY_MODULES_VIDEO
             }
 #endif
         }
References Juniper.Unity.Animation.AlphaTransition.DeltaAlpha, Juniper.Unity.Animation.AlphaTransition.minAlpha, and Juniper.Unity.Widgets.VideoVader.player.
RestartVideo()
void Juniper.Unity.Widgets.VideoVader.RestartVideo () inline private
Reset the video to the beginning if the user lost tracking for a long time.
Definition at line 56 of file VideoVader.cs.
         {
 #if UNITY_MODULES_VIDEO
             player.Stop();
 #endif
         }
References Juniper.Unity.Widgets.VideoVader.player.
Referenced by Juniper.Unity.Widgets.VideoVader.OnEntering(), and Juniper.Unity.Widgets.VideoVader.OnExiting().
SkipEnter()
override void Juniper.Unity.Animation.AbstractTransitionController.SkipEnter () inline virtual inherited
Jump the transition to the ENTERED state, without animating through the ENTERING state.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 73 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.SkipEnter();
             SetProgress(0);
         }
References Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut().
SkipExit()
virtual void Juniper.Unity.AbstractStateController.SkipExit () inline virtual inherited
Jump to the fully entered state without firing any events.
Definition at line 252 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnExiting(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
Update()
override void Juniper.Unity.Animation.AbstractTransitionController.Update () inline virtual inherited
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented from Juniper.Unity.AbstractStateController.
Reimplemented in Juniper.Unity.Animation.SpiralTransition.
Definition at line 94 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress > 0)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress - change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     SetProgress(0);
                     state = Direction.Stopped;
                 }
             }
             base.Update();
         }
References Juniper.Unity.Animation.AbstractTransitionController.attack, Juniper.Unity.AbstractStateController.IsRunning, Juniper.Unity.Animation.AbstractTransitionController.progress, Juniper.Unity.Animation.AbstractTransitionController.release, Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.state, and Juniper.Unity.Animation.AbstractTransitionController.TransitionLength.
Member Data Documentation
attackTime
float Juniper.Unity.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 18 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
length
float Juniper.Unity.Animation.AlphaTransition.length = 0.25f inherited
The amount of time it takes to complete the transition.
Definition at line 24 of file AlphaTransition.cs.
lingerTimeout
float Juniper.Unity.Widgets.VideoVader.lingerTimeout = 0
The number of second to wait after the video has ended to trigger the next state.
Definition at line 32 of file VideoVader.cs.
Referenced by Juniper.Unity.Widgets.VideoVader.Finish().
maxAlpha
float Juniper.Unity.Animation.AlphaTransition.maxAlpha = 1 inherited
The maximum opacity of the object, where 1 = completely opaque.
Definition at line 19 of file AlphaTransition.cs.
minAlpha
float Juniper.Unity.Animation.AlphaTransition.minAlpha = 0 inherited
The minimum opacity of the object, where 0 = completely transparent.
Definition at line 14 of file AlphaTransition.cs.
Referenced by Juniper.Unity.Animation.AlphaTransition.RenderValue(), and Juniper.Unity.Widgets.VideoVader.RenderValue().
onComplete
UnityEvent Juniper.Unity.Widgets.VideoVader.onComplete = new UnityEvent()
A Unity Event that fires when the video has finished playing.
Definition at line 37 of file VideoVader.cs.
Referenced by Juniper.Unity.Widgets.VideoVader.OnFinish().
onEntered
UnityEvent Juniper.Unity.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 33 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.Unity.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 24 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.Unity.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 51 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.Unity.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 42 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
onValueChanged
UnityEvent Juniper.Unity.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 31 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
player
VideoPlayer Juniper.Unity.Widgets.VideoVader.player private
The vide player that is to be faded in and out.
Definition at line 20 of file VideoVader.cs.
Referenced by Juniper.Unity.Widgets.VideoVader.Awake(), Juniper.Unity.Widgets.VideoVader.OnEntering(), Juniper.Unity.Widgets.VideoVader.RenderValue(), and Juniper.Unity.Widgets.VideoVader.RestartVideo().
releaseTime
float Juniper.Unity.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 25 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
restartTimeout
float Juniper.Unity.Widgets.VideoVader.restartTimeout = 10
The number of seconds a video may remain hidden until it resets to the beginning.
Definition at line 27 of file VideoVader.cs.
Referenced by Juniper.Unity.Widgets.VideoVader.OnExiting().
state
Direction Juniper.Unity.AbstractStateController.state inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 94 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), Juniper.Unity.Animation.AbstractTransitionController.Update(), and Juniper.Unity.AbstractStateController.Update().
tween
TweenType Juniper.Unity.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 36 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
tweenK
float Juniper.Unity.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 43 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
Property Documentation
DeltaAlpha
float Juniper.Unity.Animation.AlphaTransition.DeltaAlpha get protected inherited
The scale range the transition has to traverse.
Definition at line 41 of file AlphaTransition.cs.
         {
             get
             {
                 return maxAlpha - minAlpha;
             }
         }
Referenced by Juniper.Unity.Animation.AlphaTransition.RenderValue(), and Juniper.Unity.Widgets.VideoVader.RenderValue().
IsComplete
virtual bool Juniper.Unity.AbstractStateController.IsComplete get inherited
Returns true when state is Direction.Stopped
Definition at line 110 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.HasCompleted(), and Juniper.Unity.AbstractStateController.Update().
IsEntered
bool Juniper.Unity.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 141 of file AbstractStateController.cs.
         {
             get
             {
                 return enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Exit().
IsExited
bool Juniper.Unity.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 152 of file AbstractStateController.cs.
         {
             get
             {
                 return !enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Enter().
IsRunning
bool Juniper.Unity.AbstractStateController.IsRunning get inherited
Returns true when state is not Direction.Stopped
Definition at line 130 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
TransitionLength
override float Juniper.Unity.Animation.AlphaTransition.TransitionLength get inherited
The amount of time it takes to complete the transition.
Definition at line 30 of file AlphaTransition.cs.
         {
             get
             {
                 return length;
             }
         }
Waiter
WaitUntil Juniper.Unity.AbstractStateController.Waiter get inherited
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 329 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.Unity.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 69 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.Unity.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 60 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.Unity.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 87 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.Unity.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 78 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnExiting().
ValueChanged
EventHandler<ValueChangedEventArgs> Juniper.Unity.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 49 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/VideoVader.cs