Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster Class Reference
Master control module
Public Member Functions
JpegCompMaster (JpegCompressStruct cinfo, bool transcode_only)
void PrepareForPass ()
void PassStartup ()
void FinishPass ()
Finish up at end of pass.
bool IsLastPass ()
bool MustCallPassStartup ()
Private Types
enum PassType { PassType.Main, PassType.HuffmanOptimization, PassType.Output }
Private Member Functions
void PrepareForMainPass ()
bool PrepareForHuffmanOptimizationPass ()
void PrepareForOutputPass ()
void SelectScanParameters ()
void PerScanSetup ()
Do computations that are needed before processing a JPEG scan cinfo.comps_in_scan and cinfo.cur_comp_info[] are already set
Private Attributes
readonly JpegCompressStruct m_cinfo
bool m_call_pass_startup
bool m_is_last_pass
PassType m_pass_type
int m_pass_number
readonly int m_total_passes
int m_scan_number
Detailed Description
Master control module
Definition at line 8 of file JpegCompMaster.cs.
Member Enumeration Documentation
PassType
enum BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PassType strong private
Enumerator
Main
HuffmanOptimization
Output
Definition at line 10 of file JpegCompMaster.cs.
         {
             Main,      /* input data, also do first output step */
             HuffmanOptimization,  /* Huffman code optimization pass */
             Output     /* data output pass */
         }
Constructor & Destructor Documentation
JpegCompMaster()
BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.JpegCompMaster (JpegCompressStruct cinfo, bool transcode_only) inline
Definition at line 29 of file JpegCompMaster.cs.
         {
             m_cinfo = cinfo;
             if (transcode_only)
             {
                 /* no main pass in transcoding */
                 if (cinfo.optimizeEntropyCoding)
                 {
                     m_pass_type = PassType.HuffmanOptimization;
                 }
                 else
                 {
                     m_pass_type = PassType.Output;
                 }
             }
             else
             {
                 /* for normal compression, first pass is always this type: */
                 m_pass_type = PassType.Main;
             }
             if (cinfo.optimizeEntropyCoding)
             {
                 m_total_passes = cinfo.m_num_scans * 2;
             }
             else
             {
                 m_total_passes = cinfo.m_num_scans;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_type, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_total_passes, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding.
Member Function Documentation
FinishPass()
void BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass () inline
Finish up at end of pass.
Definition at line 126 of file JpegCompMaster.cs.
         {
             /* The entropy coder always needs an end-of-pass call,
             * either to analyze statistics or to flush its output buffer.
             */
             m_cinfo.m_entropy.finishPass();
             /* Update state for next pass */
             switch (m_pass_type)
             {
                 case PassType.Main:
                 /* next pass is either output of scan 0 (after optimization)
                 * or output of scan 1 (if no optimization).
                 */
                 m_pass_type = PassType.Output;
                 if (!m_cinfo.optimizeEntropyCoding)
                 {
                     m_scan_number++;
                 }
                 break;
                 case PassType.HuffmanOptimization:
                 /* next pass is always output of current scan */
                 m_pass_type = PassType.Output;
                 break;
                 case PassType.Output:
                 /* next pass is either optimization or output of next scan */
                 if (m_cinfo.optimizeEntropyCoding)
                 {
                     m_pass_type = PassType.HuffmanOptimization;
                 }
                 m_scan_number++;
                 break;
             }
             m_pass_number++;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_number, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_type, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_scan_number, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress().
IsLastPass()
bool BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.IsLastPass () inline
Definition at line 165 of file JpegCompMaster.cs.
         {
             return m_is_last_pass;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_is_last_pass.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress().
MustCallPassStartup()
bool BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.MustCallPassStartup () inline
Definition at line 170 of file JpegCompMaster.cs.
         {
             return m_call_pass_startup;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_call_pass_startup.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines().
PassStartup()
void BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PassStartup () inline
Special start-of-pass hook.
This is called by jpeg_write_scanlines if call_pass_startup is true. In single-pass processing, we need this hook because we don't want to write frame/scan headers during jpeg_start_compress; we want to let the application write COM markers etc. between jpeg_start_compress and the jpeg_write_scanlines loop. In multi-pass processing, this routine is not used.
Definition at line 115 of file JpegCompMaster.cs.
         {
             m_cinfo.m_master.m_call_pass_startup = false; /* reset flag so call only once */
             m_cinfo.m_marker.WriteFrameHeader();
             m_cinfo.m_marker.WriteScanHeader();
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_master.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines().
PerScanSetup()
void BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup () inline private
Do computations that are needed before processing a JPEG scan cinfo.comps_in_scan and cinfo.cur_comp_info[] are already set
Definition at line 299 of file JpegCompMaster.cs.
         {
             if (m_cinfo.m_comps_in_scan == 1)
             {
                 /* Noninterleaved (single-component) scan */
                 var compIndex = m_cinfo.m_cur_comp_info[0];
                 var compptr = m_cinfo.Component_info[compIndex];
                 /* Overall image size in MCUs */
                 m_cinfo.m_MCUs_per_row = compptr.Width_in_blocks;
                 m_cinfo.m_MCU_rows_in_scan = compptr.height_in_blocks;
                 /* For noninterleaved scan, always one block per MCU */
                 compptr.MCU_width = 1;
                 compptr.MCU_height = 1;
                 compptr.MCU_blocks = 1;
                 compptr.MCU_sample_width = compptr.DCT_h_scaled_size;
                 compptr.last_col_width = 1;
                 /* For noninterleaved scans, it is convenient to define last_row_height
                 * as the number of block rows present in the last iMCU row.
                 */
                 var tmp = compptr.height_in_blocks % compptr.V_samp_factor;
                 if (tmp == 0)
                 {
                     tmp = compptr.V_samp_factor;
                 }
                 compptr.last_row_height = tmp;
                 /* Prepare array describing MCU composition */
                 m_cinfo.m_blocks_in_MCU = 1;
                 m_cinfo.m_MCU_membership[0] = 0;
             }
             else
             {
                 /* Interleaved (multi-component) scan */
                 if (m_cinfo.m_comps_in_scan <= 0 || m_cinfo.m_comps_in_scan > JpegConstants.MAX_COMPS_IN_SCAN)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_COMPONENT_COUNT, m_cinfo.m_comps_in_scan, JpegConstants.MAX_COMPS_IN_SCAN);
                 }
                 /* Overall image size in MCUs */
                 m_cinfo.m_MCUs_per_row = (int)JpegUtils.jdiv_round_up(
                     m_cinfo.jpeg_width, m_cinfo.m_max_h_samp_factor * m_cinfo.BlockSize);
                 m_cinfo.m_MCU_rows_in_scan = (int)JpegUtils.jdiv_round_up(
                     m_cinfo.jpeg_height, m_cinfo.m_max_v_samp_factor * m_cinfo.BlockSize);
                 m_cinfo.m_blocks_in_MCU = 0;
                 for (var ci = 0; ci < m_cinfo.m_comps_in_scan; ci++)
                 {
                     var compIndex = m_cinfo.m_cur_comp_info[ci];
                     var compptr = m_cinfo.Component_info[compIndex];
                     /* Sampling factors give # of blocks of component in each MCU */
                     compptr.MCU_width = compptr.H_samp_factor;
                     compptr.MCU_height = compptr.V_samp_factor;
                     compptr.MCU_blocks = compptr.MCU_width * compptr.MCU_height;
                     compptr.MCU_sample_width = compptr.MCU_width * compptr.DCT_h_scaled_size;
                     /* Figure number of non-dummy blocks in last MCU column & row */
                     var tmp = compptr.Width_in_blocks % compptr.MCU_width;
                     if (tmp == 0)
                     {
                         tmp = compptr.MCU_width;
                     }
                     compptr.last_col_width = tmp;
                     tmp = compptr.height_in_blocks % compptr.MCU_height;
                     if (tmp == 0)
                     {
                         tmp = compptr.MCU_height;
                     }
                     compptr.last_row_height = tmp;
                     /* Prepare array describing MCU composition */
                     var mcublks = compptr.MCU_blocks;
                     if (m_cinfo.m_blocks_in_MCU + mcublks > JpegConstants.C_MAX_BLOCKS_IN_MCU)
                     {
                         m_cinfo.ErrExit(JMessageCode.JERR_BAD_MCU_SIZE);
                     }
                     while (mcublks-- > 0)
                     {
                         m_cinfo.m_MCU_membership[m_cinfo.m_blocks_in_MCU++] = ci;
                     }
                 }
             }
             /* Convert restart specified in rows to actual MCU count. */
             /* Note that count must fit in 16 bits, so we provide limiting. */
             if (m_cinfo.m_restart_in_rows > 0)
             {
                 var nominal = m_cinfo.m_restart_in_rows * m_cinfo.m_MCUs_per_row;
                 m_cinfo.m_restart_interval = Math.Min(nominal, 65535);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegConstants.C_MAX_BLOCKS_IN_MCU, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jdiv_round_up(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_width, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_max_h_samp_factor, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_max_v_samp_factor, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCU_rows_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCUs_per_row, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_in_rows, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPS_IN_SCAN, and BitMiracle.LibJpeg.Classic.JpegComponentInfo.MCU_width.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass().
PrepareForHuffmanOptimizationPass()
bool BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass () inline private
Definition at line 206 of file JpegCompMaster.cs.
         {
             /* Do Huffman optimization for a scan after the first one. */
             SelectScanParameters();
             PerScanSetup();
             if (m_cinfo.m_Ss != 0 || m_cinfo.m_Ah == 0)
             {
                 m_cinfo.m_entropy.StartPass(true);
                 m_cinfo.m_coef.StartPass(JBufMode.CrankDest);
                 m_call_pass_startup = false;
                 return false;
             }
             /* Special case: Huffman DC refinement scans need no Huffman table
             * and therefore we can skip the optimization pass for them.
             */
             m_pass_type = PassType.Output;
             m_pass_number++;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_call_pass_startup, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_number, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_type, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass().
PrepareForMainPass()
void BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass () inline private
Definition at line 175 of file JpegCompMaster.cs.
         {
             /* Initial pass: will collect input data, and do either Huffman
             * optimization or data output for the first scan.
             */
             SelectScanParameters();
             PerScanSetup();
             if (!m_cinfo.m_raw_data_in)
             {
                 m_cinfo.m_cconvert.StartPass();
                 m_cinfo.m_prep.StartPass(JBufMode.PassThrough);
             }
             m_cinfo.m_fdct.StartPass();
             m_cinfo.m_entropy.StartPass(m_cinfo.optimizeEntropyCoding);
             m_cinfo.m_coef.StartPass(m_total_passes > 1 ? JBufMode.SaveAndPass : JBufMode.PassThrough);
             m_cinfo.m_main.start_pass(JBufMode.PassThrough);
             if (m_cinfo.optimizeEntropyCoding)
             {
                 /* No immediate data output; postpone writing frame/scan headers */
                 m_call_pass_startup = false;
             }
             else
             {
                 /* Will write frame/scan headers at first jpeg_write_scanlines call */
                 m_call_pass_startup = true;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_call_pass_startup, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cconvert, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_fdct, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_main, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_prep, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_raw_data_in, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_total_passes, BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass().
PrepareForOutputPass()
void BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass () inline private
Definition at line 228 of file JpegCompMaster.cs.
         {
             /* Do a data-output pass. */
             /* We need not repeat per-scan setup if prior optimization pass did it. */
             if (!m_cinfo.optimizeEntropyCoding)
             {
                 SelectScanParameters();
                 PerScanSetup();
             }
             m_cinfo.m_entropy.StartPass(false);
             m_cinfo.m_coef.StartPass(JBufMode.CrankDest);
             /* We emit frame/scan headers now */
             if (m_scan_number == 0)
             {
                 m_cinfo.m_marker.WriteFrameHeader();
             }
             m_cinfo.m_marker.WriteScanHeader();
             m_call_pass_startup = false;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_call_pass_startup, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_scan_number, BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass().
PrepareForPass()
void BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass () inline
Per-pass setup.
This is called at the beginning of each pass. We determine which modules will be active during this pass and give them appropriate start_pass calls. We also set is_last_pass to indicate whether any more passes will be required.
Definition at line 71 of file JpegCompMaster.cs.
         {
             switch (m_pass_type)
             {
                 case PassType.Main:
                 PrepareForMainPass();
                 break;
                 case PassType.HuffmanOptimization:
                 if (!PrepareForHuffmanOptimizationPass())
                 {
                     break;
                 }
                 PrepareForOutputPass();
                 break;
                 case PassType.Output:
                 PrepareForOutputPass();
                 break;
                 default:
                 m_cinfo.ErrExit(JMessageCode.JERR_NOT_COMPILED);
                 break;
             }
             m_is_last_pass = (m_pass_number == m_total_passes - 1);
             /* Set up progress monitor's pass info if present */
             if (m_cinfo.prog is object)
             {
                 m_cinfo.prog.CompletedPasses = m_pass_number;
                 m_cinfo.prog.TotalPasses = m_total_passes;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_is_last_pass, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_number, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_type, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_total_passes, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass().
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression().
SelectScanParameters()
void BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters () inline private
Definition at line 252 of file JpegCompMaster.cs.
         {
             if (m_cinfo.m_scan_info is object)
             {
                 /* Prepare for current scan --- the script is already validated */
                 var scanInfo = m_cinfo.m_scan_info[m_scan_number];
                 m_cinfo.m_comps_in_scan = scanInfo.comps_in_scan;
                 for (var ci = 0; ci < scanInfo.comps_in_scan; ci++)
                 {
                     m_cinfo.m_cur_comp_info[ci] = scanInfo.component_index[ci];
                 }
                 if (m_cinfo.m_progressive_mode)
                 {
                     m_cinfo.m_Ss = scanInfo.Ss;
                     m_cinfo.m_Se = scanInfo.Se;
                     m_cinfo.m_Ah = scanInfo.Ah;
                     m_cinfo.m_Al = scanInfo.Al;
                     return;
                 }
             }
             else
             {
                 /* Prepare for single sequential-JPEG scan containing all components */
                 if (m_cinfo.m_num_components > JpegConstants.MAX_COMPS_IN_SCAN)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_COMPONENT_COUNT, m_cinfo.m_num_components, JpegConstants.MAX_COMPS_IN_SCAN);
                 }
                 m_cinfo.m_comps_in_scan = m_cinfo.m_num_components;
                 for (var ci = 0; ci < m_cinfo.m_num_components; ci++)
                 {
                     m_cinfo.m_cur_comp_info[ci] = ci;
                 }
             }
             m_cinfo.m_Ss = 0;
             m_cinfo.m_Se = (m_cinfo.BlockSize * m_cinfo.BlockSize) - 1;
             m_cinfo.m_Ah = 0;
             m_cinfo.m_Al = 0;
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Al, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_scan_info, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_scan_number, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, and BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPS_IN_SCAN.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass().
Member Data Documentation
m_call_pass_startup
bool BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_call_pass_startup private
Definition at line 19 of file JpegCompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.MustCallPassStartup(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass().
m_cinfo
readonly JpegCompressStruct BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_cinfo private
Definition at line 17 of file JpegCompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.JpegCompMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PassStartup(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters().
m_is_last_pass
bool BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_is_last_pass private
Definition at line 20 of file JpegCompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.IsLastPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass().
m_pass_number
int BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_number private
Definition at line 24 of file JpegCompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass().
m_pass_type
PassType BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_pass_type private
Definition at line 22 of file JpegCompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.JpegCompMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass().
m_scan_number
int BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_scan_number private
Definition at line 27 of file JpegCompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters().
m_total_passes
readonly int BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.m_total_passes private
Definition at line 25 of file JpegCompMaster.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.JpegCompMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegCompMaster.cs