Juniper: BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager Class Reference
BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager Class Reference
Expanded data destination object for output to Stream
Public Member Functions
MyDestinationManager (JpegCompressStruct cinfo, Stream alreadyOpenFile)
override void InitDestination ()
Initialize destination — called by jpeg_start_compress before any data is actually written.
override bool EmptyOutputBuffer ()
override void TermDestination ()
virtual bool EmitByte (int val)
Emits a byte.
Protected Member Functions
void InitInternalBuffer (byte[] buffer, int offset)
Initializes the internal buffer.
Properties
int FreeInBuffer [get, private set]
Gets the number of free bytes in buffer.
Private Member Functions
void WriteBuffer (int dataCount)
Private Attributes
const int OUTPUT_BUF_SIZE = 4096
readonly JpegCompressStruct m_cinfo
readonly Stream m_outfile
byte [] m_buffer
Detailed Description
Expanded data destination object for output to Stream
Definition at line 19 of file MyDestinationManager.cs.
Constructor & Destructor Documentation
MyDestinationManager()
BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.MyDestinationManager (JpegCompressStruct cinfo, Stream alreadyOpenFile) inline
Definition at line 28 of file MyDestinationManager.cs.
         {
             m_cinfo = cinfo;
             m_outfile = alreadyOpenFile;
         }
References BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_cinfo, and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_outfile.
Member Function Documentation
EmitByte()
virtual bool BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte (int val) inline virtual inherited
Emits a byte.
Parameters
val The byte value.
Returns
true if operation succeed; otherwise, false
Definition at line 32 of file JpegDestinationManager.cs.
         {
             buffer[position] = (byte)val;
             position++;
             if (--FreeInBuffer == 0)
             {
                 if (!EmptyOutputBuffer())
                 {
                     return false;
                 }
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.buffer, BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmptyOutputBuffer(), BitMiracle.LibJpeg.Classic.JpegDestinationManager.FreeInBuffer, and BitMiracle.LibJpeg.Classic.JpegDestinationManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteE(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteS().
EmptyOutputBuffer()
override bool BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.EmptyOutputBuffer () inline virtual
Empty the output buffer — called whenever buffer fills up.
In typical applications, this should write the entire output buffer (ignoring the current state of next_output_byte and free_in_buffer), reset the pointer and count to the start of the buffer, and return true indicating that the buffer has been dumped.
In applications that need to be able to suspend compression due to output overrun, a false return indicates that the buffer cannot be emptied now. In this situation, the compressor will return to its caller (possibly with an indication that it has not accepted all the supplied scanlines). The application should resume compression after it has made more room in the output buffer. Note that there are substantial restrictions on the use of suspension — see the documentation.
When suspending, the compressor will back up to a convenient restart point (typically the start of the current MCU). next_output_byte and free_in_buffer indicate where the restart point will be if the current call returns false. Data beyond this point will be regenerated after resumption, so do not write it out when emptying the buffer externally.
Implements BitMiracle.LibJpeg.Classic.JpegDestinationManager.
Definition at line 70 of file MyDestinationManager.cs.
         {
             WriteBuffer(m_buffer.Length);
             InitInternalBuffer(m_buffer, 0);
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_buffer, and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer().
InitDestination()
override void BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.InitDestination () inline virtual
Initialize destination — called by jpeg_start_compress before any data is actually written.
Implements BitMiracle.LibJpeg.Classic.JpegDestinationManager.
Definition at line 38 of file MyDestinationManager.cs.
         {
             /* Allocate the output buffer --- it will be released when done with image */
             m_buffer = new byte[OUTPUT_BUF_SIZE];
             InitInternalBuffer(m_buffer, 0);
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_buffer, and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.OUTPUT_BUF_SIZE.
InitInternalBuffer()
void BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer (byte [] buffer, int offset) inline protected inherited
Initializes the internal buffer.
Parameters
buffer The buffer.
offset The offset.
Definition at line 53 of file JpegDestinationManager.cs.
         {
             this.buffer = buffer ?? throw new System.ArgumentNullException(nameof(buffer));
             FreeInBuffer = buffer.Length - offset;
             position = offset;
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.buffer, BitMiracle.LibJpeg.Classic.JpegDestinationManager.FreeInBuffer, and BitMiracle.LibJpeg.Classic.JpegDestinationManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.EmptyOutputBuffer(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.InitDestination().
TermDestination()
override void BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.TermDestination () inline virtual
Terminate destination — called by jpeg_finish_compress after all data has been written. Usually needs to flush buffer.
NB: not called by jpeg_abort or jpeg_destroy; surrounding application must deal with any cleanup that should happen even for error exit.
Implements BitMiracle.LibJpeg.Classic.JpegDestinationManager.
Definition at line 88 of file MyDestinationManager.cs.
         {
             var datacount = m_buffer.Length - FreeInBuffer;
             /* Write any data remaining in the buffer */
             if (datacount > 0)
             {
                 WriteBuffer(datacount);
             }
             m_outfile.Flush();
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.FreeInBuffer, BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_buffer, BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_outfile, and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer().
WriteBuffer()
void BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer (int dataCount) inline private
Definition at line 101 of file MyDestinationManager.cs.
         {
             try
             {
                 m_outfile.Write(m_buffer, 0, dataCount);
             }
             catch (IOException e)
             {
                 m_cinfo.TraceMS(0, JMessageCode.JERR_FILE_WRITE, e.Message);
                 m_cinfo.ErrExit(JMessageCode.JERR_FILE_WRITE);
             }
             catch (NotSupportedException e)
             {
                 m_cinfo.TraceMS(0, JMessageCode.JERR_FILE_WRITE, e.Message);
                 m_cinfo.ErrExit(JMessageCode.JERR_FILE_WRITE);
             }
             catch (ObjectDisposedException e)
             {
                 m_cinfo.TraceMS(0, JMessageCode.JERR_FILE_WRITE, e.Message);
                 m_cinfo.ErrExit(JMessageCode.JERR_FILE_WRITE);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_buffer, BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_outfile, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.EmptyOutputBuffer(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.TermDestination().
Member Data Documentation
m_buffer
byte [] BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_buffer private
Definition at line 26 of file MyDestinationManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.EmptyOutputBuffer(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.InitDestination(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.TermDestination(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer().
m_cinfo
readonly JpegCompressStruct BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_cinfo private
Definition at line 23 of file MyDestinationManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.MyDestinationManager(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer().
m_outfile
readonly Stream BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.m_outfile private
Definition at line 25 of file MyDestinationManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.MyDestinationManager(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.TermDestination(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer().
OUTPUT_BUF_SIZE
const int BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.OUTPUT_BUF_SIZE = 4096 private
Definition at line 21 of file MyDestinationManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.InitDestination().
Property Documentation
FreeInBuffer
int BitMiracle.LibJpeg.Classic.JpegDestinationManager.FreeInBuffer get private set protected inherited
Gets the number of free bytes in buffer.
The number of free bytes in buffer.
Definition at line 64 of file JpegDestinationManager.cs.
 { get; private set; }
Referenced by BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte(), BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitInternalBuffer(), and BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.TermDestination().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/MyDestinationManager.cs