Juniper: Juniper.HTTP.Server.Controllers.WebSocketPool Class Reference
Juniper.HTTP.Server.Controllers.WebSocketPool Class Reference
Public Member Functions
async Task< ServerWebSocketConnection > GetAsync (HttpListenerContext context)
Static Public Member Functions
static void SetUserToken (string userName, string token)
Public Attributes
IReadOnlyCollection< ServerWebSocketConnection > Sockets => sockets.Values
Private Member Functions
void Socket_Closed (object sender, EventArgs e)
Private Attributes
readonly Dictionary< int, ServerWebSocketConnection > sockets = new Dictionary<int, ServerWebSocketConnection>()
Static Private Attributes
static readonly Dictionary< string, string > userNames = new Dictionary<string, string>()
Detailed Description
Definition at line 9 of file WebSocketPool.cs.
Member Function Documentation
GetAsync()
async Task<ServerWebSocketConnection> Juniper.HTTP.Server.Controllers.WebSocketPool.GetAsync (HttpListenerContext context) inline
Definition at line 42 of file WebSocketPool.cs.
         {
             if (context is null)
             {
                 throw new ArgumentNullException(nameof(context));
             }
             var id = context.GetHashCode();
             if (!sockets.ContainsKey(id))
             {
                 var token = context.Request.Headers["Sec-WebSocket-Protocol"];
                 if (token is object && !userNames.ContainsKey(token))
                 {
                     context.Response.SetStatus(HttpStatusCode.Unauthorized);
                 }
                 else
                 {
                     var wsContext = await context.AcceptWebSocketAsync(token)
                         .ConfigureAwait(false);
                     var socket = new ServerWebSocketConnection(context, wsContext.WebSocket, userNames.Get(token));
                     socket.Closed += Socket_Closed;
                     sockets.Add(id, socket);
                 }
             }
             return sockets[id];
         }
References Juniper.HTTP.WebSocketConnection< WebSocketT >.Closed, Juniper.HTTP.Server.Controllers.WebSocketPool.Socket_Closed(), Juniper.HTTP.Server.Controllers.WebSocketPool.sockets, and Juniper.HTTP.Server.Controllers.WebSocketPool.userNames.
Referenced by Juniper.HTTP.Server.Controllers.WebSocketRoute.InvokeAsync().
SetUserToken()
static void Juniper.HTTP.Server.Controllers.WebSocketPool.SetUserToken (string userName, string token) inline static
Definition at line 12 of file WebSocketPool.cs.
         {
             lock (userNames)
             {
                 userNames[token] = userName;
             }
         }
References Juniper.HTTP.Server.Controllers.WebSocketPool.userNames.
Socket_Closed()
void Juniper.HTTP.Server.Controllers.WebSocketPool.Socket_Closed (object sender, EventArgs e) inline private
Definition at line 24 of file WebSocketPool.cs.
         {
             if (sender is ServerWebSocketConnection socket)
             {
                 socket.Closed -= Socket_Closed;
                 socket.Dispose();
                 var keys = (from s in sockets
                             where socket == s.Value
                             select s.Key);
                 foreach (var key in keys)
                 {
                     _ = sockets.Remove(key);
                 }
             }
         }
References Juniper.HTTP.Server.Controllers.WebSocketPool.sockets.
Referenced by Juniper.HTTP.Server.Controllers.WebSocketPool.GetAsync().
Member Data Documentation
sockets
readonly Dictionary<int, ServerWebSocketConnection> Juniper.HTTP.Server.Controllers.WebSocketPool.sockets = new Dictionary<int, ServerWebSocketConnection>() private
Definition at line 20 of file WebSocketPool.cs.
Referenced by Juniper.HTTP.Server.Controllers.WebSocketPool.GetAsync(), and Juniper.HTTP.Server.Controllers.WebSocketPool.Socket_Closed().
Sockets
IReadOnlyCollection<ServerWebSocketConnection> Juniper.HTTP.Server.Controllers.WebSocketPool.Sockets => sockets.Values
Definition at line 22 of file WebSocketPool.cs.
userNames
readonly Dictionary<string, string> Juniper.HTTP.Server.Controllers.WebSocketPool.userNames = new Dictionary<string, string>() static private
Definition at line 11 of file WebSocketPool.cs.
Referenced by Juniper.HTTP.Server.Controllers.WebSocketPool.GetAsync(), and Juniper.HTTP.Server.Controllers.WebSocketPool.SetUserToken().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Server/Controllers/WebSocketPool.cs