Juniper: System.ScreenDebugger Class Reference
System.ScreenDebugger Class Reference
The ScreenDebugger component is a global logging system that has the option of piping its output to a TextMesh visible on the screen. This can be handy for printing out logging information on mobile devices without having to explicitly attach a mobile device debugger.
Public Member Functions
ScreenDebugger ()
When the ScreenDebugger is instantiated, that instance is saved statically to be accessible to all code.
void LateUpdate ()
Renders all text in lines to the text output.
void AddLine (string msg)
Add lines to the debug output in a way that Unity Events can handle
void ClearScreen ()
Remove any text that is in the debugger view right now.
Static Public Member Functions
static void Clear ()
Clear out the text display
static void PrintException (Exception exp, string label)
Print an exception formatted succinctly for printing to the console. The label field helps locate the origin of the exception.
static void PrintVector (Vector2 vector, string label)
Print a Vector with components to 3 significant figures.
static void PrintVector (Vector3 vector, string label)
Print a Vector with components to 3 significant figures.
static void PrintVector (Vector4 vector, string label)
Print a Vector with components to 3 significant figures.
static void PrintFormat (string format, params object[] args)
Print a formatted string
static void Print (string msg)
Print a simple message
Private Member Functions
void Awake ()
void GetControls ()
Private Attributes
TextComponentWrapper text
The text element to which the output is rendered.
Static Private Attributes
static readonly List< string > lines = new List<string>(10)
The text that will be rendered out to the TextMesh at the end of the frame.
static ScreenDebugger instance
The screen debugger instance, a singleton.
Detailed Description
The ScreenDebugger component is a global logging system that has the option of piping its output to a TextMesh visible on the screen. This can be handy for printing out logging information on mobile devices without having to explicitly attach a mobile device debugger.
Definition at line 17 of file ScreenDebugger.cs.
Constructor & Destructor Documentation
ScreenDebugger()
System.ScreenDebugger.ScreenDebugger () inline
When the ScreenDebugger is instantiated, that instance is saved statically to be accessible to all code.
Definition at line 23 of file ScreenDebugger.cs.
         {
             instance = this;
         }
References System.ScreenDebugger.instance.
Member Function Documentation
AddLine()
void System.ScreenDebugger.AddLine (string msg) inline
Add lines to the debug output in a way that Unity Events can handle
Parameters
msg Message.
Definition at line 173 of file ScreenDebugger.cs.
         {
             lines.Add(msg);
             Debug.Log(msg);
         }
References System.ScreenDebugger.lines.
Awake()
void System.ScreenDebugger.Awake () inline private
Definition at line 123 of file ScreenDebugger.cs.
         {
             GetControls();
             if(text != null)
             {
                 ClearScreen();
             }
         }
References System.ScreenDebugger.ClearScreen(), System.ScreenDebugger.GetControls(), and System.ScreenDebugger.text.
Clear()
static void System.ScreenDebugger.Clear () inline static
Clear out the text display
Definition at line 31 of file ScreenDebugger.cs.
         {
             if (instance != null)
             {
                 instance.ClearScreen();
             }
         }
References System.ScreenDebugger.ClearScreen(), and System.ScreenDebugger.instance.
ClearScreen()
void System.ScreenDebugger.ClearScreen () inline
Remove any text that is in the debugger view right now.
Definition at line 182 of file ScreenDebugger.cs.
         {
             lines.Clear();
             text.Text = string.Empty;
         }
References System.ScreenDebugger.lines, Juniper.Widgets.TextComponentWrapper.Text, and System.ScreenDebugger.text.
Referenced by System.ScreenDebugger.Awake(), and System.ScreenDebugger.Clear().
GetControls()
void System.ScreenDebugger.GetControls () inline private
Definition at line 139 of file ScreenDebugger.cs.
         {
             if (text == null)
             {
                 text = this.Ensure<TextComponentWrapper>();
             }
         }
References System.ScreenDebugger.text.
Referenced by System.ScreenDebugger.Awake().
LateUpdate()
void System.ScreenDebugger.LateUpdate () inline
Renders all text in lines to the text output.
Definition at line 150 of file ScreenDebugger.cs.
         {
             if (lines.Count > 0)
             {
                 var log = string.Join(Environment.NewLine, lines);
                 Debug.Log(log);
                 var formatted = from msg in lines
                                 select $"{Time.frameCount}: {msg}";
                 var output = string.Join(Environment.NewLine, formatted);
                 if (text != null)
                 {
                     text.Text = output;
                 }
                 lines.Clear();
             }
         }
References System.ScreenDebugger.lines, Juniper.Widgets.TextComponentWrapper.Text, and System.ScreenDebugger.text.
Print()
static void System.ScreenDebugger.Print (string msg) inline static
Print a simple message
Parameters
msg Message.
Definition at line 94 of file ScreenDebugger.cs.
         {
             if (instance != null && lines != null)
             {
                 lines.Add(msg);
             }
             else
             {
                 Debug.Log(msg);
             }
         }
References System.ScreenDebugger.instance, and System.ScreenDebugger.lines.
Referenced by Juniper.World.GIS.SunPosition.PrintDebugReport(), Juniper.World.LightEstimation.OutdoorLightEstimate.PrintDebugReport(), Juniper.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), Juniper.World.CompassRose.PrintDebugReport(), Juniper.Widgets.Shaker.PrintDebugReport(), Juniper.World.LightEstimation.AbstractLightEstimate.PrintDebugReport(), Juniper.World.GIS.GPSLocation.PrintDebugReport(), Juniper.World.Climate.Weather.PrintDebugReport(), System.ScreenDebugger.PrintException(), System.ScreenDebugger.PrintFormat(), System.ScreenDebugger.PrintVector(), Juniper.Speech.KeywordRecognizer.ProcessText(), Juniper.ImageTracking.ARKitTrackerKeeper.Start(), Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSet(), Juniper.MasterSceneController.SwitchToSceneCoroutine(), Juniper.Display.DefaultDisplayManager.Update(), Juniper.Widgets.QualityDegrader.Update(), and Juniper.ImageTracking.ARKitTrackerKeeper.WithTarget().
PrintException()
static void System.ScreenDebugger.PrintException (Exception exp, string label) inline static
Print an exception formatted succinctly for printing to the console. The label field helps locate the origin of the exception.
Parameters
exp Exp.
label Label.
Definition at line 45 of file ScreenDebugger.cs.
         {
             Print(exp.ToShortString(label));
         }
References System.ScreenDebugger.Print().
Referenced by Juniper.World.CompassRose.PrintDebugReport().
PrintFormat()
static void System.ScreenDebugger.PrintFormat (string format, params object [] args) inline static
Print a formatted string
Parameters
format Format.
args Arguments.
Definition at line 85 of file ScreenDebugger.cs.
         {
             Print(string.Format(format, args));
         }
References System.ScreenDebugger.Print().
Referenced by Juniper.World.GIS.SunPosition.PrintDebugReport(), Juniper.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), Juniper.Widgets.Shaker.PrintDebugReport(), Juniper.World.LightEstimation.AbstractLightEstimate.PrintDebugReport(), and Juniper.World.GIS.GPSLocation.PrintDebugReport().
PrintVector() [1/3]
static void System.ScreenDebugger.PrintVector (Vector2 vector, string label) inline static
Print a Vector with components to 3 significant figures.
Parameters
vector Vector.
label Label.
Definition at line 55 of file ScreenDebugger.cs.
         {
             Print($"[{label}] <{vector.x.Label(UnitOfMeasure.Meters, 3)}, {vector.y.Label(UnitOfMeasure.Meters, 3)}>");
         }
References System.ScreenDebugger.Print().
PrintVector() [2/3]
static void System.ScreenDebugger.PrintVector (Vector3 vector, string label) inline static
Print a Vector with components to 3 significant figures.
Parameters
vector Vector.
label Label.
Definition at line 65 of file ScreenDebugger.cs.
         {
             Print($"[{label}] <{vector.x.Label(UnitOfMeasure.Meters, 3)}, {vector.y.Label(UnitOfMeasure.Meters, 3)}, {vector.z.Label(UnitOfMeasure.Meters, 3)}>");
         }
References System.ScreenDebugger.Print().
PrintVector() [3/3]
static void System.ScreenDebugger.PrintVector (Vector4 vector, string label) inline static
Print a Vector with components to 3 significant figures.
Parameters
vector Vector.
label Label.
Definition at line 75 of file ScreenDebugger.cs.
         {
             Print($"[{label}] <{vector.x.Label(UnitOfMeasure.Meters, 3)}, {vector.y.Label(UnitOfMeasure.Meters, 3)}, {vector.z.Label(UnitOfMeasure.Meters, 3)}, {vector.z.Label(UnitOfMeasure.Meters, 4)}>");
         }
References System.ScreenDebugger.Print().
Member Data Documentation
instance
ScreenDebugger System.ScreenDebugger.instance static private
The screen debugger instance, a singleton.
Definition at line 114 of file ScreenDebugger.cs.
Referenced by System.ScreenDebugger.Clear(), System.ScreenDebugger.Print(), and System.ScreenDebugger.ScreenDebugger().
lines
readonly List<string> System.ScreenDebugger.lines = new List<string>(10) static private
The text that will be rendered out to the TextMesh at the end of the frame.
Definition at line 109 of file ScreenDebugger.cs.
Referenced by System.ScreenDebugger.AddLine(), System.ScreenDebugger.ClearScreen(), System.ScreenDebugger.LateUpdate(), and System.ScreenDebugger.Print().
text
TextComponentWrapper System.ScreenDebugger.text private
The text element to which the output is rendered.
Definition at line 121 of file ScreenDebugger.cs.
Referenced by System.ScreenDebugger.Awake(), System.ScreenDebugger.ClearScreen(), System.ScreenDebugger.GetControls(), and System.ScreenDebugger.LateUpdate().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/ScreenDebugger.cs