Juniper: BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler Class Reference
BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler Class Reference
Public Member Functions
MyMergedUpSampler (JpegDecompressStruct cinfo)
override void StartPass ()
Initialize for an upsampling pass.
override void UpSample (ComponentBuffer[] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, byte[][] output_buf, ref int out_row_ctr, int out_rows_avail)
bool NeedContextRows ()
Properties
bool m_need_context_rows [get, set]
Private Member Functions
void Merged1VUpSample (ComponentBuffer[] input_buf, ref int in_row_group_ctr, byte[][] output_buf, ref int out_row_ctr)
Control routine to do upsampling (and color conversion). The control routine just handles the row buffering considerations. 1:1 vertical sampling case: much easier, never need a spare row.
void Merged2VUpSample (ComponentBuffer[] input_buf, ref int in_row_group_ctr, byte[][] output_buf, ref int out_row_ctr, int out_rows_avail)
Control routine to do upsampling (and color conversion). The control routine just handles the row buffering considerations. 2:1 vertical sampling case: may need a spare row.
void H2V1MergedUpSample (ComponentBuffer[] input_buf, int in_row_group_ctr, byte[][] output_buf, int outRow)
Upsample and color convert for the case of 2:1 horizontal and 1:1 vertical.
void H2V2MergedUpSample (ComponentBuffer[] input_buf, int in_row_group_ctr, byte[][] output_buf)
Upsample and color convert for the case of 2:1 horizontal and 2:1 vertical.
void BuildYccRgbTable ()
Initialize tables for YCbCr->RGB colorspace conversion. This is taken directly from jpeg_color_deconverter; see that file for more info.
void BuildBgYccRgbTable ()
Initialize tables for BG_YCC->RGB colorspace conversion. This is taken directly from jpeg_color_deconverter; see that file for more info.
Static Private Member Functions
static int Fix (double x)
Private Attributes
const int SCALEBITS = 16
const int ONE_HALF = 1 << (SCALEBITS - 1)
readonly JpegDecompressStruct m_cinfo
readonly bool m_use_2v_upsample
int [] m_Cr_r_tab
int [] m_Cb_b_tab
int [] m_Cr_g_tab
int [] m_Cb_g_tab
readonly byte [] m_spare_row
bool m_spare_full
readonly int m_out_row_width
int m_rows_to_go
Detailed Description
Definition at line 31 of file MyMergedUpSampler.cs.
Constructor & Destructor Documentation
MyMergedUpSampler()
BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler (JpegDecompressStruct cinfo) inline
Definition at line 57 of file MyMergedUpSampler.cs.
         {
             m_cinfo = cinfo;
             m_need_context_rows = false;
             m_out_row_width = cinfo.outputWidth * cinfo.outColorComponents;
             if (cinfo.m_maxVSampleFactor == 2)
             {
                 m_use_2v_upsample = true;
                 /* Allocate a spare row buffer */
                 m_spare_row = new byte[m_out_row_width];
             }
             else
             {
                 m_use_2v_upsample = false;
             }
             if (cinfo.jpegColorSpace == JColorSpace.JCS_BG_YCC)
             {
                 BuildBgYccRgbTable();
             }
             else
             {
                 BuildYccRgbTable();
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.jpegColorSpace, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_maxVSampleFactor, BitMiracle.LibJpeg.Classic.Internal.JpegUpSampler.m_need_context_rows, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_out_row_width, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_spare_row, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_use_2v_upsample, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorComponents, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth.
Member Function Documentation
BuildBgYccRgbTable()
void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable () inline private
Initialize tables for BG_YCC->RGB colorspace conversion. This is taken directly from jpeg_color_deconverter; see that file for more info.
Definition at line 382 of file MyMergedUpSampler.cs.
         {
             /* Wide gamut case, bg-sYCC */
             m_Cr_r_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_b_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cr_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             for (int i = 0, x = -JpegConstants.CENTERJSAMPLE; i <= JpegConstants.MAXJSAMPLE; i++, x++)
             {
                 /* i is the actual input pixel value, in the range 0..MAXJSAMPLE */
                 /* The Cb or Cr value we are thinking of is x = i - CENTERJSAMPLE */
                 /* Cr=>R value is nearest int to 2.804 * x */
                 m_Cr_r_tab[i] = JpegUtils.RIGHT_SHIFT((Fix(2.804) * x) + ONE_HALF, SCALEBITS);
                 /* Cb=>B value is nearest int to 3.544 * x */
                 m_Cb_b_tab[i] = JpegUtils.RIGHT_SHIFT((Fix(3.544) * x) + ONE_HALF, SCALEBITS);
                 /* Cr=>G value is scaled-up -1.428272572 * x */
                 m_Cr_g_tab[i] = -Fix(1.428272572) * x;
                 /* Cb=>G value is scaled-up -0.688272572 * x */
                 /* We also add in ONE_HALF so that need not do it in inner loop */
                 m_Cb_g_tab[i] = (-Fix(0.688272572) * x) + ONE_HALF;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Fix(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.ONE_HALF, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler().
BuildYccRgbTable()
void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable () inline private
Initialize tables for YCbCr->RGB colorspace conversion. This is taken directly from jpeg_color_deconverter; see that file for more info.
Definition at line 350 of file MyMergedUpSampler.cs.
         {
             /* Normal case, sYCC */
             m_Cr_r_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_b_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cr_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             for (int i = 0, x = -JpegConstants.CENTERJSAMPLE; i <= JpegConstants.MAXJSAMPLE; i++, x++)
             {
                 /* i is the actual input pixel value, in the range 0..MAXJSAMPLE */
                 /* The Cb or Cr value we are thinking of is x = i - CENTERJSAMPLE */
                 /* Cr=>R value is nearest int to 1.402 * x */
                 m_Cr_r_tab[i] = JpegUtils.RIGHT_SHIFT((Fix(1.402) * x) + ONE_HALF, SCALEBITS);
                 /* Cb=>B value is nearest int to 1.772 * x */
                 m_Cb_b_tab[i] = JpegUtils.RIGHT_SHIFT((Fix(1.772) * x) + ONE_HALF, SCALEBITS);
                 /* Cr=>G value is scaled-up -0.714136286 * x */
                 m_Cr_g_tab[i] = -Fix(0.714136286) * x;
                 /* Cb=>G value is scaled-up -0.344136286 * x */
                 /* We also add in ONE_HALF so that need not do it in inner loop */
                 m_Cb_g_tab[i] = (-Fix(0.344136286) * x) + ONE_HALF;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Fix(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.ONE_HALF, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler().
Fix()
static int BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Fix (double x) inline static private
Definition at line 410 of file MyMergedUpSampler.cs.
         {
             return (int)((x * (1L << SCALEBITS)) + 0.5);
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable().
H2V1MergedUpSample()
void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample (ComponentBuffer [] input_buf, int in_row_group_ctr, byte output_buf[][], int outRow) inline private
Upsample and color convert for the case of 2:1 horizontal and 1:1 vertical.
Definition at line 199 of file MyMergedUpSampler.cs.
         {
             var inputIndex0 = 0;
             var inputIndex1 = 0;
             var inputIndex2 = 0;
             var outputIndex = 0;
             var limit = m_cinfo.m_sample_range_limit;
             var limitOffset = m_cinfo.m_sampleRangeLimitOffset;
             /* Loop for each pair of output pixels */
             for (var col = m_cinfo.outputWidth >> 1; col > 0; col--)
             {
                 /* Do the chroma part of the calculation */
                 int cb = input_buf[1][in_row_group_ctr][inputIndex1];
                 inputIndex1++;
                 int cr = input_buf[2][in_row_group_ctr][inputIndex2];
                 inputIndex2++;
                 var cred = m_Cr_r_tab[cr];
                 var cgreen = JpegUtils.RIGHT_SHIFT(m_Cb_g_tab[cb] + m_Cr_g_tab[cr], SCALEBITS);
                 var cblue = m_Cb_b_tab[cb];
                 /* Fetch 2 Y values and emit 2 pixels */
                 int y = input_buf[0][in_row_group_ctr][inputIndex0];
                 inputIndex0++;
                 output_buf[outRow][outputIndex + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[outRow][outputIndex + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[outRow][outputIndex + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
                 outputIndex += JpegConstants.RGB_PIXELSIZE;
                 y = input_buf[0][in_row_group_ctr][inputIndex0];
                 inputIndex0++;
                 output_buf[outRow][outputIndex + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[outRow][outputIndex + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[outRow][outputIndex + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
                 outputIndex += JpegConstants.RGB_PIXELSIZE;
             }
             /* If image width is odd, do the last output column separately */
             if ((m_cinfo.outputWidth & 1) != 0)
             {
                 int cb = input_buf[1][in_row_group_ctr][inputIndex1];
                 int cr = input_buf[2][in_row_group_ctr][inputIndex2];
                 var cred = m_Cr_r_tab[cr];
                 var cgreen = JpegUtils.RIGHT_SHIFT(m_Cb_g_tab[cb] + m_Cr_g_tab[cr], SCALEBITS);
                 var cblue = m_Cb_b_tab[cb];
                 int y = input_buf[0][in_row_group_ctr][inputIndex0];
                 output_buf[outRow][outputIndex + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[outRow][outputIndex + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[outRow][outputIndex + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sample_range_limit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sampleRangeLimitOffset, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged1VUpSample().
H2V2MergedUpSample()
void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample (ComponentBuffer [] input_buf, int in_row_group_ctr, byte output_buf[][]) inline private
Upsample and color convert for the case of 2:1 horizontal and 2:1 vertical.
Definition at line 260 of file MyMergedUpSampler.cs.
         {
             var inputRow00 = in_row_group_ctr * 2;
             var inputIndex00 = 0;
             var inputRow01 = (in_row_group_ctr * 2) + 1;
             var inputIndex01 = 0;
             var inputIndex1 = 0;
             var inputIndex2 = 0;
             var outIndex0 = 0;
             var outIndex1 = 0;
             var limit = m_cinfo.m_sample_range_limit;
             var limitOffset = m_cinfo.m_sampleRangeLimitOffset;
             /* Loop for each group of output pixels */
             for (var col = m_cinfo.outputWidth >> 1; col > 0; col--)
             {
                 /* Do the chroma part of the calculation */
                 int cb = input_buf[1][in_row_group_ctr][inputIndex1];
                 inputIndex1++;
                 int cr = input_buf[2][in_row_group_ctr][inputIndex2];
                 inputIndex2++;
                 var cred = m_Cr_r_tab[cr];
                 var cgreen = JpegUtils.RIGHT_SHIFT(m_Cb_g_tab[cb] + m_Cr_g_tab[cr], SCALEBITS);
                 var cblue = m_Cb_b_tab[cb];
                 /* Fetch 4 Y values and emit 4 pixels */
                 int y = input_buf[0][inputRow00][inputIndex00];
                 inputIndex00++;
                 output_buf[0][outIndex0 + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[0][outIndex0 + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[0][outIndex0 + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
                 outIndex0 += JpegConstants.RGB_PIXELSIZE;
                 y = input_buf[0][inputRow00][inputIndex00];
                 inputIndex00++;
                 output_buf[0][outIndex0 + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[0][outIndex0 + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[0][outIndex0 + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
                 outIndex0 += JpegConstants.RGB_PIXELSIZE;
                 y = input_buf[0][inputRow01][inputIndex01];
                 inputIndex01++;
                 output_buf[1][outIndex1 + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[1][outIndex1 + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[1][outIndex1 + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
                 outIndex1 += JpegConstants.RGB_PIXELSIZE;
                 y = input_buf[0][inputRow01][inputIndex01];
                 inputIndex01++;
                 output_buf[1][outIndex1 + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[1][outIndex1 + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[1][outIndex1 + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
                 outIndex1 += JpegConstants.RGB_PIXELSIZE;
             }
             /* If image width is odd, do the last output column separately */
             if ((m_cinfo.outputWidth & 1) != 0)
             {
                 int cb = input_buf[1][in_row_group_ctr][inputIndex1];
                 int cr = input_buf[2][in_row_group_ctr][inputIndex2];
                 var cred = m_Cr_r_tab[cr];
                 var cgreen = JpegUtils.RIGHT_SHIFT(m_Cb_g_tab[cb] + m_Cr_g_tab[cr], SCALEBITS);
                 var cblue = m_Cb_b_tab[cb];
                 int y = input_buf[0][inputRow00][inputIndex00];
                 output_buf[0][outIndex0 + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[0][outIndex0 + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[0][outIndex0 + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
                 y = input_buf[0][inputRow01][inputIndex01];
                 output_buf[1][outIndex1 + JpegConstants.RGB_RED] = limit[limitOffset + y + cred];
                 output_buf[1][outIndex1 + JpegConstants.RGB_GREEN] = limit[limitOffset + y + cgreen];
                 output_buf[1][outIndex1 + JpegConstants.RGB_BLUE] = limit[limitOffset + y + cblue];
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sample_range_limit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sampleRangeLimitOffset, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample().
Merged1VUpSample()
void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged1VUpSample (ComponentBuffer [] input_buf, ref int in_row_group_ctr, byte output_buf[][], ref int out_row_ctr) inline private
Control routine to do upsampling (and color conversion). The control routine just handles the row buffering considerations. 1:1 vertical sampling case: much easier, never need a spare row.
Definition at line 114 of file MyMergedUpSampler.cs.
         {
             /* Just do the upsampling. */
             H2V1MergedUpSample(input_buf, in_row_group_ctr, output_buf, out_row_ctr);
             /* Adjust counts */
             out_row_ctr++;
             in_row_group_ctr++;
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample().
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.UpSample().
Merged2VUpSample()
void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample (ComponentBuffer [] input_buf, ref int in_row_group_ctr, byte output_buf[][], ref int out_row_ctr, int out_rows_avail) inline private
Control routine to do upsampling (and color conversion). The control routine just handles the row buffering considerations. 2:1 vertical sampling case: may need a spare row.
Definition at line 129 of file MyMergedUpSampler.cs.
         {
             int num_rows;        /* number of rows returned to caller */
             if (m_spare_full)
             {
                 /* If we have a spare row saved from a previous cycle, just return it. */
                 var temp = new byte[1][];
                 temp[0] = m_spare_row;
                 JpegUtils.jcopy_sample_rows(temp, 0, output_buf, out_row_ctr, 1, m_out_row_width);
                 num_rows = 1;
                 m_spare_full = false;
             }
             else
             {
                 /* Figure number of rows to return to caller. */
                 num_rows = 2;
                 /* Not more than the distance to the end of the image. */
                 if (num_rows > m_rows_to_go)
                 {
                     num_rows = m_rows_to_go;
                 }
                 /* And not more than what the client can accept: */
                 out_rows_avail -= out_row_ctr;
                 if (num_rows > out_rows_avail)
                 {
                     num_rows = out_rows_avail;
                 }
                 /* Create output pointer array for upsampler. */
                 var work_ptrs = new byte[2][];
                 work_ptrs[0] = output_buf[out_row_ctr];
                 if (num_rows > 1)
                 {
                     work_ptrs[1] = output_buf[out_row_ctr + 1];
                 }
                 else
                 {
                     work_ptrs[1] = m_spare_row;
                     m_spare_full = true;
                 }
                 /* Now do the upsampling. */
                 H2V2MergedUpSample(input_buf, in_row_group_ctr, work_ptrs);
             }
             /* Adjust counts */
             out_row_ctr += num_rows;
             m_rows_to_go -= num_rows;
             /* When the buffer is emptied, declare this input row group consumed */
             if (!m_spare_full)
             {
                 in_row_group_ctr++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jcopy_sample_rows(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_out_row_width, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_rows_to_go, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_spare_full, and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_spare_row.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.UpSample().
NeedContextRows()
bool BitMiracle.LibJpeg.Classic.Internal.JpegUpSampler.NeedContextRows () inline inherited
Definition at line 13 of file JpegUpSampler.cs.
         {
             return m_need_context_rows;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegUpSampler.m_need_context_rows.
StartPass()
override void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.StartPass () inline virtual
Initialize for an upsampling pass.
Implements BitMiracle.LibJpeg.Classic.Internal.JpegUpSampler.
Definition at line 88 of file MyMergedUpSampler.cs.
         {
             /* Mark the spare buffer empty */
             m_spare_full = false;
             /* Initialize total-height counter for detecting bottom of image */
             m_rows_to_go = m_cinfo.outputHeight;
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_rows_to_go, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_spare_full, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight.
UpSample()
override void BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.UpSample (ComponentBuffer [] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, byte output_buf[][], ref int out_row_ctr, int out_rows_avail) inline virtual
Implements BitMiracle.LibJpeg.Classic.Internal.JpegUpSampler.
Definition at line 97 of file MyMergedUpSampler.cs.
         {
             if (m_use_2v_upsample)
             {
                 Merged2VUpSample(input_buf, ref in_row_group_ctr, output_buf, ref out_row_ctr, out_rows_avail);
             }
             else
             {
                 Merged1VUpSample(input_buf, ref in_row_group_ctr, output_buf, ref out_row_ctr);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_use_2v_upsample, BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged1VUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample().
Member Data Documentation
m_Cb_b_tab
int [] BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_b_tab private
Definition at line 42 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample().
m_Cb_g_tab
int [] BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cb_g_tab private
Definition at line 44 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample().
m_cinfo
readonly JpegDecompressStruct BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_cinfo private
Definition at line 36 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.StartPass().
m_Cr_g_tab
int [] BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_g_tab private
Definition at line 43 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample().
m_Cr_r_tab
int [] BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_Cr_r_tab private
Definition at line 41 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample().
m_out_row_width
readonly int BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_out_row_width private
Definition at line 54 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler().
m_rows_to_go
int BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_rows_to_go private
Definition at line 55 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.StartPass().
m_spare_full
bool BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_spare_full private
Definition at line 52 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.StartPass().
m_spare_row
readonly byte [] BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_spare_row private
Definition at line 51 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Merged2VUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler().
m_use_2v_upsample
readonly bool BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.m_use_2v_upsample private
Definition at line 38 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.UpSample().
ONE_HALF
const int BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.ONE_HALF = 1 << (SCALEBITS - 1) private
Definition at line 34 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable().
SCALEBITS
const int BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.SCALEBITS = 16 private
Definition at line 33 of file MyMergedUpSampler.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.Fix(), BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V1MergedUpSample(), and BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.H2V2MergedUpSample().
Property Documentation
m_need_context_rows
bool BitMiracle.LibJpeg.Classic.Internal.JpegUpSampler.m_need_context_rows get set protected inherited
Definition at line 8 of file JpegUpSampler.cs.
 { get; set; } /* true if need rows above & below */
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyMergedUpSampler.MyMergedUpSampler(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), and BitMiracle.LibJpeg.Classic.Internal.JpegUpSampler.NeedContextRows().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/MyMergedUpSampler.cs