Juniper: Hjg.Pngcs.Zlib.ZlibOutputStream Class Reference
Hjg.Pngcs.Zlib.ZlibOutputStream Class Reference
Public Member Functions
ZlibOutputStream (Stream st, int compressLevel, EDeflateCompressStrategy strat, bool leaveOpen)
override void WriteByte (byte value)
override void Write (byte[] array, int offset, int count)
override void Close ()
override void Flush ()
override string GetImplementationId ()
mainly for debugging
override void SetLength (long value)
override long Seek (long offset, SeekOrigin origin)
override int Read (byte[] buffer, int offset, int count)
Public Attributes
override bool CanSeek => false
override long Length => throw new NotSupportedException()
override bool CanRead => false
override bool CanWrite => true
override bool CanTimeout => false
Protected Member Functions
override void Dispose (bool disposing)
Properties
Stream RawStream [get, set]
bool LeaveOpen [get]
int CompressLevel [get, set]
EDeflateCompressStrategy Strategy [get]
override long Position [get, set]
Private Member Functions
void InitStream ()
void DoInit ()
Private Attributes
DeflateStream deflateStream
readonly Adler32 adler32 = new Adler32()
bool initdone = false
bool closed = false
Detailed Description
Definition at line 6 of file ZlibOutputStream.cs.
Constructor & Destructor Documentation
ZlibOutputStream()
Hjg.Pngcs.Zlib.ZlibOutputStream.ZlibOutputStream (Stream st, int compressLevel, EDeflateCompressStrategy strat, bool leaveOpen) inline
Definition at line 8 of file ZlibOutputStream.cs.
             : base(st, compressLevel, strat, leaveOpen)
         {
         }
Member Function Documentation
Close()
override void Hjg.Pngcs.Zlib.ZlibOutputStream.Close () inline
Definition at line 55 of file ZlibOutputStream.cs.
         {
             if (!initdone)
             {
                 DoInit(); // can happen if never called write
             }
             if (closed)
             {
                 return;
             }
             closed = true;
             // sigh ... no only must I close the parent stream to force a flush, but I must save a reference
             // raw stream because (apparently) Close() sets it to null (shame on you, MS developers)
             if (deflateStream is object)
             {
                 deflateStream.Close();
             }
             else
             {         // second hack: empty input?
                 RawStream.WriteByte(3);
                 RawStream.WriteByte(0);
             }
             // add crc
             var crcv = adler32.GetValue();
             RawStream.WriteByte((byte)((crcv >> 24) & 0xFF));
             RawStream.WriteByte((byte)((crcv >> 16) & 0xFF));
             RawStream.WriteByte((byte)((crcv >> 8) & 0xFF));
             RawStream.WriteByte((byte)(crcv & 0xFF));
             if (!LeaveOpen)
             {
                 RawStream.Close();
             }
         }
References Hjg.Pngcs.Zlib.ZlibOutputStream.adler32, Hjg.Pngcs.Zlib.ZlibOutputStream.closed, Hjg.Pngcs.Zlib.ZlibOutputStream.deflateStream, Hjg.Pngcs.Zlib.ZlibOutputStream.DoInit(), Hjg.Pngcs.Zlib.Adler32.GetValue(), Hjg.Pngcs.Zlib.ZlibOutputStream.initdone, Hjg.Pngcs.Zlib.AZlibOutputStream.LeaveOpen, and Hjg.Pngcs.Zlib.AZlibOutputStream.RawStream.
Dispose()
override void Hjg.Pngcs.Zlib.AZlibOutputStream.Dispose (bool disposing) inline protected inherited
Definition at line 24 of file AZlibOutputStream.cs.
         {
             if (disposing && !LeaveOpen)
             {
                 RawStream.Dispose();
             }
             base.Dispose(disposing);
         }
References Hjg.Pngcs.Zlib.AZlibOutputStream.LeaveOpen, and Hjg.Pngcs.Zlib.AZlibOutputStream.RawStream.
Referenced by Hjg.Pngcs.PngWriter.Dispose().
DoInit()
void Hjg.Pngcs.Zlib.ZlibOutputStream.DoInit () inline private
Definition at line 114 of file ZlibOutputStream.cs.
         {
             if (initdone)
             {
                 return;
             }
             initdone = true;
             // http://stackoverflow.com/a/2331025/277304
             const int cmf = 0x78;
             var flg = 218;  // sorry about the following lines
             if (CompressLevel >= 5 && CompressLevel <= 6)
             {
                 flg = 156;
             }
             else if (CompressLevel >= 3 && CompressLevel <= 4)
             {
                 flg = 94;
             }
             else if (CompressLevel <= 2)
             {
                 flg = 1;
             }
             flg -= (((cmf * 256) + flg) % 31); // just in case
             if (flg < 0)
             {
                 flg += 31;
             }
             RawStream.WriteByte(cmf);
             RawStream.WriteByte((byte)flg);
         }
References Hjg.Pngcs.Zlib.AZlibOutputStream.CompressLevel, Hjg.Pngcs.Zlib.ZlibOutputStream.initdone, and Hjg.Pngcs.Zlib.AZlibOutputStream.RawStream.
Referenced by Hjg.Pngcs.Zlib.ZlibOutputStream.Close(), Hjg.Pngcs.Zlib.ZlibOutputStream.Write(), and Hjg.Pngcs.Zlib.ZlibOutputStream.WriteByte().
Flush()
override void Hjg.Pngcs.Zlib.ZlibOutputStream.Flush () inline
Definition at line 148 of file ZlibOutputStream.cs.
         {
             deflateStream?.Flush();
         }
References Hjg.Pngcs.Zlib.ZlibOutputStream.deflateStream.
GetImplementationId()
override string Hjg.Pngcs.Zlib.ZlibOutputStream.GetImplementationId () inline virtual
mainly for debugging
Returns
Implements Hjg.Pngcs.Zlib.AZlibOutputStream.
Definition at line 153 of file ZlibOutputStream.cs.
         {
             return "Zlib deflater: .Net CLR 4.5";
         }
InitStream()
void Hjg.Pngcs.Zlib.ZlibOutputStream.InitStream () inline private
Definition at line 91 of file ZlibOutputStream.cs.
         {
             if (deflateStream is object)
             {
                 return;
             }
             // I must create the DeflateStream only if necessary, because of its bug with empty input (sigh)
             // I must create with leaveopen=true always and do the closing myself, because MS moronic implementation of DeflateStream: I cant force a flush of the underlying stream witouth closing (sigh bis)
             var clevel = CompressionLevel.Optimal;
             // thaks for the granularity, MS!
             if (CompressLevel >= 1 && CompressLevel <= 5)
             {
                 clevel = CompressionLevel.Fastest;
             }
             else if (CompressLevel == 0)
             {
                 clevel = CompressionLevel.NoCompression;
             }
             deflateStream = new DeflateStream(RawStream, clevel, true);
         }
References Hjg.Pngcs.Zlib.AZlibOutputStream.CompressLevel, Hjg.Pngcs.Zlib.ZlibOutputStream.deflateStream, and Hjg.Pngcs.Zlib.AZlibOutputStream.RawStream.
Referenced by Hjg.Pngcs.Zlib.ZlibOutputStream.Write(), and Hjg.Pngcs.Zlib.ZlibOutputStream.WriteByte().
Read()
override int Hjg.Pngcs.Zlib.AZlibOutputStream.Read (byte [] buffer, int offset, int count) inline inherited
Definition at line 54 of file AZlibOutputStream.cs.
         {
             throw new NotSupportedException();
         }
Seek()
override long Hjg.Pngcs.Zlib.AZlibOutputStream.Seek (long offset, SeekOrigin origin) inline inherited
Definition at line 41 of file AZlibOutputStream.cs.
         {
             throw new NotSupportedException();
         }
SetLength()
override void Hjg.Pngcs.Zlib.AZlibOutputStream.SetLength (long value) inline inherited
Definition at line 34 of file AZlibOutputStream.cs.
         {
             throw new NotImplementedException();
         }
Write()
override void Hjg.Pngcs.Zlib.ZlibOutputStream.Write (byte [] array, int offset, int count) inline
Definition at line 34 of file ZlibOutputStream.cs.
         {
             if (count == 0)
             {
                 return;
             }
             if (!initdone)
             {
                 DoInit();
             }
             if (deflateStream is null)
             {
                 InitStream();
             }
             deflateStream.Write(array, offset, count);
             adler32.Update(array, offset, count);
         }
References Hjg.Pngcs.Zlib.ZlibOutputStream.adler32, Hjg.Pngcs.Zlib.ZlibOutputStream.deflateStream, Hjg.Pngcs.Zlib.ZlibOutputStream.DoInit(), Hjg.Pngcs.Zlib.ZlibOutputStream.initdone, Hjg.Pngcs.Zlib.ZlibOutputStream.InitStream(), and Hjg.Pngcs.Zlib.Adler32.Update().
WriteByte()
override void Hjg.Pngcs.Zlib.ZlibOutputStream.WriteByte (byte value) inline
Definition at line 18 of file ZlibOutputStream.cs.
         {
             if (!initdone)
             {
                 DoInit();
             }
             if (deflateStream is null)
             {
                 InitStream();
             }
             base.WriteByte(value);
             adler32.Update(value);
         }
References Hjg.Pngcs.Zlib.ZlibOutputStream.adler32, Hjg.Pngcs.Zlib.ZlibOutputStream.deflateStream, Hjg.Pngcs.Zlib.ZlibOutputStream.DoInit(), Hjg.Pngcs.Zlib.ZlibOutputStream.initdone, Hjg.Pngcs.Zlib.ZlibOutputStream.InitStream(), and Hjg.Pngcs.Zlib.Adler32.Update().
Member Data Documentation
adler32
readonly Adler32 Hjg.Pngcs.Zlib.ZlibOutputStream.adler32 = new Adler32() private
Definition at line 14 of file ZlibOutputStream.cs.
Referenced by Hjg.Pngcs.Zlib.ZlibOutputStream.Close(), Hjg.Pngcs.Zlib.ZlibOutputStream.Write(), and Hjg.Pngcs.Zlib.ZlibOutputStream.WriteByte().
CanRead
override bool Hjg.Pngcs.Zlib.AZlibOutputStream.CanRead => false inherited
Definition at line 59 of file AZlibOutputStream.cs.
CanSeek
override bool Hjg.Pngcs.Zlib.AZlibOutputStream.CanSeek => false inherited
Definition at line 39 of file AZlibOutputStream.cs.
CanTimeout
override bool Hjg.Pngcs.Zlib.AZlibOutputStream.CanTimeout => false inherited
Definition at line 63 of file AZlibOutputStream.cs.
CanWrite
override bool Hjg.Pngcs.Zlib.AZlibOutputStream.CanWrite => true inherited
Definition at line 61 of file AZlibOutputStream.cs.
closed
bool Hjg.Pngcs.Zlib.ZlibOutputStream.closed = false private
Definition at line 16 of file ZlibOutputStream.cs.
Referenced by Hjg.Pngcs.Zlib.ZlibOutputStream.Close().
deflateStream
DeflateStream Hjg.Pngcs.Zlib.ZlibOutputStream.deflateStream private
Definition at line 13 of file ZlibOutputStream.cs.
Referenced by Hjg.Pngcs.Zlib.ZlibOutputStream.Close(), Hjg.Pngcs.Zlib.ZlibOutputStream.Flush(), Hjg.Pngcs.Zlib.ZlibOutputStream.InitStream(), Hjg.Pngcs.Zlib.ZlibOutputStream.Write(), and Hjg.Pngcs.Zlib.ZlibOutputStream.WriteByte().
initdone
bool Hjg.Pngcs.Zlib.ZlibOutputStream.initdone = false private
Definition at line 15 of file ZlibOutputStream.cs.
Referenced by Hjg.Pngcs.Zlib.ZlibOutputStream.Close(), Hjg.Pngcs.Zlib.ZlibOutputStream.DoInit(), Hjg.Pngcs.Zlib.ZlibOutputStream.Write(), and Hjg.Pngcs.Zlib.ZlibOutputStream.WriteByte().
Length
override long Hjg.Pngcs.Zlib.AZlibOutputStream.Length => throw new NotSupportedException() inherited
Definition at line 52 of file AZlibOutputStream.cs.
Property Documentation
CompressLevel
int Hjg.Pngcs.Zlib.AZlibOutputStream.CompressLevel get set protected inherited
Definition at line 12 of file AZlibOutputStream.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Zlib.AZlibOutputStream.AZlibOutputStream(), Hjg.Pngcs.Zlib.ZlibOutputStream.DoInit(), and Hjg.Pngcs.Zlib.ZlibOutputStream.InitStream().
LeaveOpen
bool Hjg.Pngcs.Zlib.AZlibOutputStream.LeaveOpen get protected inherited
Definition at line 10 of file AZlibOutputStream.cs.
 { get; }
Referenced by Hjg.Pngcs.Zlib.AZlibOutputStream.AZlibOutputStream(), Hjg.Pngcs.Zlib.ZlibOutputStream.Close(), and Hjg.Pngcs.Zlib.AZlibOutputStream.Dispose().
Position
override long Hjg.Pngcs.Zlib.AZlibOutputStream.Position get set inherited
Definition at line 47 of file AZlibOutputStream.cs.
         {
             get { throw new NotSupportedException(); }
             set { throw new NotSupportedException(); }
         }
RawStream
Stream Hjg.Pngcs.Zlib.AZlibOutputStream.RawStream get set protected inherited
Definition at line 8 of file AZlibOutputStream.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Zlib.AZlibOutputStream.AZlibOutputStream(), Hjg.Pngcs.Zlib.ZlibOutputStream.Close(), Hjg.Pngcs.Zlib.AZlibOutputStream.Dispose(), Hjg.Pngcs.Zlib.ZlibOutputStream.DoInit(), and Hjg.Pngcs.Zlib.ZlibOutputStream.InitStream().
Strategy
EDeflateCompressStrategy Hjg.Pngcs.Zlib.AZlibOutputStream.Strategy get protected inherited
Definition at line 14 of file AZlibOutputStream.cs.
 { get; }
Referenced by Hjg.Pngcs.Zlib.AZlibOutputStream.AZlibOutputStream().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Zlib/ZlibOutputStream.cs