Juniper: Juniper.Audio.AmbientAudio Class Reference
Juniper.Audio.AmbientAudio Class Reference
Public Member Functions
override void Awake ()
override void Load (IProgress prog=null)
override void Enter ()
Fire the OnEnable event and perform the Enter transition.
override void Exit ()
Triggers the exit process and then deactivates the subscene.
override void Update ()
Checks to see if the state has changed and fires the right event for it.
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Public Attributes
StreamableAudioClip audioClip
bool spatialize
float spatialBlend
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Protected Attributes
bool deactivateOnExit = true
Whether or not to deactivate the subscene when it has finished exiting.
Properties
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Attributes
AudioSource player
Detailed Description
Definition at line 10 of file AmbientAudio.cs.
Member Function Documentation
Awake()
override void Juniper.Audio.AmbientAudio.Awake () inline virtual
Reimplemented from Juniper.SubSceneController.
Definition at line 38 of file AmbientAudio.cs.
         {
             base.Awake();
             var audio = ComponentExt.FindAny<InteractionAudio>();
             player = this.Ensure<AudioSource>();
             player.outputAudioMixerGroup = audio.defaultMixerGroup;
             player.playOnAwake = false;
             player.loop = true;
             player.spatialize = spatialize;
             player.spatialBlend = spatialBlend;
         }
References Juniper.Audio.AmbientAudio.player, Juniper.Audio.AmbientAudio.spatialBlend, and Juniper.Audio.AmbientAudio.spatialize.
Enter()
override void Juniper.SubSceneController.Enter () inline virtual inherited
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 31 of file SubSceneController.cs.
         {
             isExitingPreviousScene = true;
             foreach (var subScene in CurrentSubScenes)
             {
                 subScene.Exit();
             }
             base.Enter();
         }
References Juniper.SubSceneController.CurrentSubScenes, and Juniper.SubSceneController.isExitingPreviousScene.
Referenced by Juniper.Audio.AmbientAudio.Load(), and Juniper.Video.Video360.Load().
Exit()
override void Juniper.SubSceneController.Exit () inline virtual inherited
Triggers the exit process and then deactivates the subscene.
Returns
The coroutine.
Reimplemented from Juniper.AbstractStateController.
Definition at line 46 of file SubSceneController.cs.
         {
             if (isActiveAndEnabled)
             {
                 foreach (var child in Exitable)
                 {
                     child.Exit();
                 }
             }
             base.Exit();
         }
References Juniper.SubSceneController.Exitable.
HasCompleted()
bool Juniper.AbstractStateController.HasCompleted () inline inherited
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 123 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.AbstractStateController.IsComplete.
Load()
override void Juniper.Audio.AmbientAudio.Load (IProgress prog = null) inline virtual
Reimplemented from Juniper.SubSceneController.
Definition at line 51 of file AmbientAudio.cs.
         {
             prog?.Report(0);
             Enter();
             StartCoroutine(audioClip.Load(
                 clip =>
                 {
                     player.clip = clip;
                     player.Play();
                 },
                 exp =>
                 {
                     ScreenDebugger.PrintException(exp, "AmbientAudio");
                     prog?.Report(1);
                 },
                 prog));
         }
References Juniper.Audio.AmbientAudio.audioClip, Juniper.SubSceneController.Enter(), and Juniper.Audio.StreamableAudioClip.Load().
OnDisable()
void Juniper.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 300 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.AbstractStateController.OnExited().
OnEnable()
void Juniper.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 195 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.AbstractStateController.OnEntering().
Referenced by Juniper.AbstractStateController.SkipEnter().
OnEntered()
virtual void Juniper.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Animation.FadeTransition.
Definition at line 242 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntered?.Invoke();
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entered, Juniper.AbstractStateController.onEntered, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.AbstractStateController.Update().
OnEntering()
virtual void Juniper.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 206 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntering?.Invoke();
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entering, Juniper.AbstractStateController.onEntering, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.AbstractStateController.OnEnable().
OnExited()
override void Juniper.SubSceneController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Reimplemented from Juniper.AbstractStateController.
Definition at line 85 of file SubSceneController.cs.
         {
             base.OnExited();
             if (deactivateOnExit)
             {
                 this.Deactivate();
             }
         }
References Juniper.SubSceneController.deactivateOnExit.
OnExiting()
virtual void Juniper.AbstractStateController.OnExiting () inline protected virtual inherited
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented in Juniper.Animation.FadeTransition, Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 285 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExiting?.Invoke();
                 Exiting?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Exiting, Juniper.AbstractStateController.onExiting, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.AbstractStateController.Exit(), and Juniper.AbstractStateController.SkipExit().
SkipEnter()
virtual void Juniper.AbstractStateController.SkipEnter () inline virtual inherited
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Animation.AbstractTransitionController.
Definition at line 164 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Forward;
             OnEnable();
             lastState = Direction.Forward;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.AbstractStateController.lastState, Juniper.AbstractStateController.OnEnable(), Juniper.AbstractStateController.skipEvents, Juniper.AbstractStateController.state, and Juniper.AbstractStateController.Update().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Jump to the fully entered state without firing any events.
Definition at line 254 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.AbstractStateController.lastState, Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.skipEvents, Juniper.AbstractStateController.state, and Juniper.AbstractStateController.Update().
Update()
override void Juniper.SubSceneController.Update () inline virtual inherited
Checks to see if the state has changed and fires the right event for it.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Video.Video360.
Definition at line 58 of file SubSceneController.cs.
         {
             if (IsRunning)
             {
                 if (state == Direction.Forward && !isExitingPreviousScene && AllComplete(Enterable)
                     || state == Direction.Reverse && AllComplete(Exitable))
                 {
                     state = Direction.Stopped;
                 }
                 else if (state == Direction.Forward && isExitingPreviousScene && AllComplete(CurrentSubScenes))
                 {
                     isExitingPreviousScene = false;
                     foreach (var child in Enterable)
                     {
                         child.Enter();
                     }
                 }
             }
             base.Update();
         }
References Juniper.SubSceneController.AllComplete(), Juniper.SubSceneController.CurrentSubScenes, Juniper.SubSceneController.Enterable, Juniper.SubSceneController.Exitable, Juniper.SubSceneController.isExitingPreviousScene, Juniper.AbstractStateController.IsRunning, and Juniper.AbstractStateController.state.
Member Data Documentation
audioClip
StreamableAudioClip Juniper.Audio.AmbientAudio.audioClip
Definition at line 12 of file AmbientAudio.cs.
Referenced by Juniper.Audio.AmbientAudio.Load().
deactivateOnExit
bool Juniper.SubSceneController.deactivateOnExit = true protected inherited
Whether or not to deactivate the subscene when it has finished exiting.
Definition at line 83 of file SubSceneController.cs.
Referenced by Juniper.SubSceneController.OnExited().
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 35 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 26 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 53 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 44 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
player
AudioSource Juniper.Audio.AmbientAudio.player private
Definition at line 20 of file AmbientAudio.cs.
Referenced by Juniper.Audio.AmbientAudio.Awake().
spatialBlend
float Juniper.Audio.AmbientAudio.spatialBlend
Definition at line 18 of file AmbientAudio.cs.
Referenced by Juniper.Audio.AmbientAudio.Awake().
spatialize
bool Juniper.Audio.AmbientAudio.spatialize
Definition at line 15 of file AmbientAudio.cs.
Referenced by Juniper.Audio.AmbientAudio.Awake().
state
Direction Juniper.AbstractStateController.state inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 96 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.Exit(), Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), Juniper.Animation.AbstractTransitionController.StartTransition(), Juniper.SubSceneController.Update(), Juniper.Animation.AbstractTransitionController.Update(), and Juniper.AbstractStateController.Update().
Property Documentation
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get inherited
Returns true when state is Direction.Stopped
Definition at line 112 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.AbstractStateController.HasCompleted(), and Juniper.AbstractStateController.Update().
IsEntered
bool Juniper.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 143 of file AbstractStateController.cs.
         {
             get
             {
                 return isActiveAndEnabled;
             }
         }
Referenced by Juniper.AbstractStateController.Exit().
IsExited
bool Juniper.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 154 of file AbstractStateController.cs.
         {
             get
             {
                 return !isActiveAndEnabled;
             }
         }
Referenced by Juniper.AbstractStateController.Enter().
IsRunning
bool Juniper.AbstractStateController.IsRunning get inherited
Returns true when state is not Direction.Stopped
Definition at line 132 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.SubSceneController.Update(), and Juniper.Animation.AbstractTransitionController.Update().
Waiter
WaitUntil Juniper.AbstractStateController.Waiter get inherited
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 331 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 71 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 62 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 89 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 80 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExiting().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Audio/AmbientAudio.cs