Juniper: Juniper.XR.Platform Class Reference
Juniper.XR.Platform Class Reference
Utility functions for manipulating platform enumerations.
Static Public Member Functions
static PlatformTypes Compose (SystemTypes sys, DisplayTypes display, AugmentedRealityTypes ar, Options opt)
Combine flags for a platform into a single identifier.
static Options GetOption (PlatformTypes p)
Get the Option out of a PlatformType.
static AugmentedRealityTypes GetARType (PlatformTypes p)
Get the AugmentedRealityType out of the PlatformType.
static DisplayTypes GetDisplayType (PlatformTypes p)
Get the DisplayType out of the PlatformType.
static SystemTypes GetSystem (PlatformTypes p)
Get the SystemType out of the PlatformType.
Public Attributes
const int AR_OFFSET = 5
The range of bit flags to set for AugmentedRealityTypes.
const int DISPLAY_OFFSET = AR_OFFSET + 2
The range of bit flags to set for DisplayTypes.
const int SYS_OFFSET = DISPLAY_OFFSET + 2
The range of bit flags to set for SystemTypes.
Static Private Member Functions
static int Get (PlatformTypes p, int start, int end)
Get a range of bit fields out of a PlatformType.
Private Attributes
const int TOTAL_OFFSET = SYS_OFFSET + 5
The range of bit flags to set for Options.
Detailed Description
Utility functions for manipulating platform enumerations.
Definition at line 133 of file PlatformEnums.cs.
Member Function Documentation
Compose()
static PlatformTypes Juniper.XR.Platform.Compose (SystemTypes sys, DisplayTypes display, AugmentedRealityTypes ar, Options opt) inline static
Combine flags for a platform into a single identifier.
Parameters
sys
display
ar
opt
Returns
Definition at line 163 of file PlatformEnums.cs.
         {
             return (PlatformTypes)((int)sys << SYS_OFFSET | (int)display << DISPLAY_OFFSET | (int)ar << AR_OFFSET | (int)opt);
         }
References Juniper.XR.Platform.AR_OFFSET, Juniper.XR.Platform.DISPLAY_OFFSET, and Juniper.XR.Platform.SYS_OFFSET.
Get()
static int Juniper.XR.Platform.Get (PlatformTypes p, int start, int end) inline static private
Get a range of bit fields out of a PlatformType.
Parameters
p
start
end
Returns
Definition at line 175 of file PlatformEnums.cs.
         {
             return (((1 << start) - 1) & (int)p) >> end;
         }
Referenced by Juniper.XR.Platform.GetARType(), Juniper.XR.Platform.GetDisplayType(), Juniper.XR.Platform.GetOption(), and Juniper.XR.Platform.GetSystem().
GetARType()
static AugmentedRealityTypes Juniper.XR.Platform.GetARType (PlatformTypes p) inline static
Get the AugmentedRealityType out of the PlatformType.
Parameters
p
Returns
Definition at line 195 of file PlatformEnums.cs.
         {
             return (AugmentedRealityTypes)Get(p, DISPLAY_OFFSET, AR_OFFSET);
         }
References Juniper.XR.Platform.AR_OFFSET, Juniper.XR.Platform.DISPLAY_OFFSET, and Juniper.XR.Platform.Get().
GetDisplayType()
static DisplayTypes Juniper.XR.Platform.GetDisplayType (PlatformTypes p) inline static
Get the DisplayType out of the PlatformType.
Parameters
p
Returns
Definition at line 205 of file PlatformEnums.cs.
         {
             return (DisplayTypes)Get(p, SYS_OFFSET, DISPLAY_OFFSET);
         }
References Juniper.XR.Platform.DISPLAY_OFFSET, Juniper.XR.Platform.Get(), and Juniper.XR.Platform.SYS_OFFSET.
GetOption()
static Options Juniper.XR.Platform.GetOption (PlatformTypes p) inline static
Get the Option out of a PlatformType.
Parameters
p
Returns
Definition at line 185 of file PlatformEnums.cs.
         {
             return (Options)Get(p, AR_OFFSET, 0);
         }
References Juniper.XR.Platform.AR_OFFSET, and Juniper.XR.Platform.Get().
GetSystem()
static SystemTypes Juniper.XR.Platform.GetSystem (PlatformTypes p) inline static
Get the SystemType out of the PlatformType.
Parameters
p
Returns
Definition at line 215 of file PlatformEnums.cs.
         {
             return (SystemTypes)Get(p, TOTAL_OFFSET, SYS_OFFSET);
         }
References Juniper.XR.Platform.Get(), Juniper.XR.Platform.SYS_OFFSET, and Juniper.XR.Platform.TOTAL_OFFSET.
Member Data Documentation
AR_OFFSET
const int Juniper.XR.Platform.AR_OFFSET = 5
The range of bit flags to set for AugmentedRealityTypes.
Definition at line 138 of file PlatformEnums.cs.
Referenced by Juniper.XR.Platform.Compose(), Juniper.XR.Platform.GetARType(), and Juniper.XR.Platform.GetOption().
DISPLAY_OFFSET
const int Juniper.XR.Platform.DISPLAY_OFFSET = AR_OFFSET + 2
The range of bit flags to set for DisplayTypes.
Definition at line 143 of file PlatformEnums.cs.
Referenced by Juniper.XR.Platform.Compose(), Juniper.XR.Platform.GetARType(), and Juniper.XR.Platform.GetDisplayType().
SYS_OFFSET
const int Juniper.XR.Platform.SYS_OFFSET = DISPLAY_OFFSET + 2
The range of bit flags to set for SystemTypes.
Definition at line 148 of file PlatformEnums.cs.
Referenced by Juniper.XR.Platform.Compose(), Juniper.XR.Platform.GetDisplayType(), and Juniper.XR.Platform.GetSystem().
TOTAL_OFFSET
const int Juniper.XR.Platform.TOTAL_OFFSET = SYS_OFFSET + 5 private
The range of bit flags to set for Options.
Definition at line 153 of file PlatformEnums.cs.
Referenced by Juniper.XR.Platform.GetSystem().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.XR/PlatformEnums.cs