Juniper: Juniper.Primrose.Grammar Class Reference
Juniper.Primrose.Grammar Class Reference
A Grammar is a collection of rules for processing text into tokens. Tokens are special characters that tell us about the structure of the text, things like keywords, curly braces, numbers, etc. After the text is tokenized, the tokens get a rough processing pass that groups them into larger elements that can be rendered in color on the screen. As tokens are discovered, they are removed from the text being processed, so order is important.Grammar rules are applied in the order they are specified, and more than one rule can produce the same token type. SeePrimrose.Text.Rule for a list of valid token names.
Public Member Functions
Grammar (string grammarName, params Rule[] rules)
Initializes a new instance of the Grammar class.
virtual List< Token > Tokenize (string text)
Static Public Attributes
static readonly Grammar Basic = new Basic()
A grammar and an interpreter for a BASIC-like language.
static readonly Grammar HTML
A grammar for HyperText Markup Language.
static readonly Grammar JavaScript
A grammar for the JavaScript programming language.
static readonly Grammar PlainText
A grammar that makes displaying plain text work with the text editor designed for syntax highlighting.
static readonly Grammar TestResults
A grammar for displaying the results of Unit Tests.
Properties
string Name [get]
A user-friendly name for the grammar, to be able to include it in an options listing
Rule [] Rules [get]
A collection of rules to apply to tokenize text. The rules should be an array of two-element arrays. The first element should be a token name (see Primrose.Text.Rule for a list of valid token names), followed by a regular expression that selects the token out of the source code.
Private Member Functions
void CrudeParsing (List< Token > tokens)
Detailed Description
A Grammar is a collection of rules for processing text into tokens. Tokens are special characters that tell us about the structure of the text, things like keywords, curly braces, numbers, etc. After the text is tokenized, the tokens get a rough processing pass that groups them into larger elements that can be rendered in color on the screen. As tokens are discovered, they are removed from the text being processed, so order is important.Grammar rules are applied in the order they are specified, and more than one rule can produce the same token type. SeePrimrose.Text.Rule for a list of valid token names.
para>A plain-text "grammar".
para>Plain text does not actually have a grammar that needs to be processed. However, to get the text to work with the rendering system, a basic grammar is necessary to be able to break the text up into lines and prepare it for rendering.
code>var plainTextGrammar = new Primrose.Text.Grammar(// The name is for displaying in options views. "Plain-text", [ // Text needs at least the newlines token, or else every line will attempt to render as a single line and the line count won't work.
\ ["newlines", /(?:\r\n|\r|\n)/]);"
A grammar for BASIC
The BASIC programming language is now defunct, but a grammar for it to display in Primrose is quite easy to build.
var basicGrammar = new Primrose.Text.Grammar("BASIC",
 // Grammar rules are applied in the order they are specified.\n\
[
// Text needs at least the newlines token, or else every line will attempt to render as a single line and the line count won't work.\n\
[ \"newlines\", /(?:\\r\\n|\\r|\\n)/ ],\n\
// BASIC programs used to require the programmer type in her own line numbers. The start at the beginning of the line.\n\
[ \"lineNumbers\", /^\\d+\\s+/ ],\n\
// Comments were lines that started with the keyword \"REM\" (for REMARK) and ran to the end of the line. They did not have to be numbered, because they were not executable and were stripped out by the interpreter.\n\
[ \"startLineComments\", /^REM\\s/ ],\n\
// Both double-quoted and single-quoted strings were not always supported, but in this case, I'm just demonstrating how it would be done for both.\n\
[ \"strings\", /\"(?:\\\\\"|[^\"])*\"/ ],\n\
[ \"strings\", /'(?:\\\\'|[^'])*'/ ],\n\
// Numbers are an optional dash, followed by a optional digits, followed by optional period, followed by 1 or more required digits. This allows us to match both integers and decimal numbers, both positive and negative, with or without leading zeroes for decimal numbers between (-1, 1).\n\
[ \"numbers\", /-?(?:(?:\\b\\d*)?\\.)?\\b\\d+\\b/ ],\n\
@verbatim
// Keywords are really just a list of different words we want to match, surrounded by the \"word boundary\" selector \"\\b\".\n\
[ \"keywords\",\n\
  /\\b(?:RESTORE | REPEAT | RETURN | LOAD | LABEL | DATA | READ | THEN | ELSE | FOR | DIM | LET | IF | TO | STEP | NEXT | WHILE | WEND | UNTIL | GOTO | GOSUB | ON | TAB | AT | END | STOP | PRINT | INPUT | RND | INT | CLS | CLK | LEN)\\b /\n\
],\n\
// Sometimes things we want to treat as keywords have different meanings in different locations. We can specify rules for tokens more than once.\n\
[ \"keywords\", /^DEF FN/ ],\n\
// These are all treated as mathematical operations.\n\
  [ \"operators\",\n\
    / (?:\\+|;|,|-|\\*\\*|\\*|\\/|>=|<=|=|<>|<|>|OR|AND|NOT|MOD|\\(|\\)|\\[|\\])/\n\
  ],\n\
  // Once everything else has been matched, the left over blocks of words are treated as variable and function names.\n\
  [ \"identifiers\", /\\w+\\$?/ ]\n\
]);"
}]
@endverbatim
</example>
Definition at line 60 of file Grammar.cs.
Constructor & Destructor Documentation
Grammar()
Juniper.Primrose.Grammar.Grammar (string grammarName, params Rule [] rules) inline
Initializes a new instance of the Grammar class.
Parameters
grammarName A user-friendly name for the grammar, to be able to include it in an options listing.
rules A collection of rules to apply to tokenize text. The rules should be an array of two-element arrays. The first element should be a token name (see Primrose.Text.Rule for a list of valid token names), followed by a regular expression that selects the token out of the source code.
Definition at line 76 of file Grammar.cs.
         {
             string commentDelim = null;
             string stringDelim = null;
             var line = 0;
             for (var i = 0; i < tokens.Count; ++i)
             {
References Juniper.Primrose.Grammar.Name, and Juniper.Primrose.Grammar.Rules.
Member Function Documentation
CrudeParsing()
void Juniper.Primrose.Grammar.CrudeParsing (List< Token > tokens) inline private
Definition at line 84 of file Grammar.cs.
                 {
                     ++line;
                 }
                 if (stringDelim is object)
                 {
                     if (t.Type == "stringDelim"
                         && t.Value == stringDelim
                         && (i == 0
                             || tokens[i - 1].Value[tokens[i - 1].Value.Length - 1] != '\\'))
                     {
                         stringDelim = null;
                     }
                     if (t.Type != "newlines")
                     {
                         t.Type = "strings";
                     }
                 }
                 else if (commentDelim is object)
                 {
                     if ((commentDelim == "startBlockComments"
                             && t.Type == "endBlockComments")
                         || (commentDelim == "startLineComments"
                             && t.Type == "newlines"))
                     {
                         commentDelim = null;
                     }
                     if (t.Type != "newlines")
                     {
                         t.Type = "comments";
                     }
                 }
                 else if (t.Type == "stringDelim")
                 {
                     stringDelim = t.Value;
                     t.Type = "strings";
                 }
                 else if (t.Type == "startBlockComments"
                     || t.Type == "startLineComments")
                 {
                     commentDelim = t.Type;
                     t.Type = "comments";
                 }
             }
             // recombine like-tokens
             for (var i = tokens.Count - 1; i > 0; --i)
             {
                 var p = tokens[i - 1];
                 var t = tokens[i];
                 if (p.Type == t.Type && p.Type != "newlines")
                 {
                     p.Value += t.Value;
                     _ = tokens.Splice(i, 1);
                 }
             }
         }
         /*
         pliny.method({
           parent: "Primrose.Text.Grammar",
           name: "tokenize",
           parameters: [{
             name: "text",
             type: "String",
Referenced by Juniper.Primrose.Grammar.Tokenize().
Tokenize()
virtual List<Token> Juniper.Primrose.Grammar.Tokenize (string text) inline virtual
Reimplemented in Juniper.Primrose.Basic.
Definition at line 199 of file Grammar.cs.
             {
                 var rule = Rules[i];
                 for (var j = 0; j < tokens.Count; ++j)
                 {
                     rule.CarveOutMatchedToken(tokens, j);
                 }
             }
             CrudeParsing(tokens);
             return tokens;
         }
         //private static HtmlDocument document = null;
         //public string ToHTML(string txt, Theme theme = null)
         //{
         //    if (theme is null)
         //    {
         //        theme = Theme.DefaultTheme;
References Juniper.Primrose.Rule.CarveOutMatchedToken(), Juniper.Primrose.Grammar.CrudeParsing(), and Juniper.Primrose.Grammar.Rules.
Member Data Documentation
Basic
readonly Grammar Juniper.Primrose.Grammar.Basic = new Basic() static
A grammar and an interpreter for a BASIC-like language.
Definition at line 8 of file Grammar.cs.
HTML
readonly Grammar Juniper.Primrose.Grammar.HTML static
Initial value:
= new Grammar(
            "HTML",
            new Rule("newlines", new Regex("(?:\\r\\n|\\r|\\n)")),
            new Rule("startBlockComments", new Regex("(?:<| &lt;)!--")),
            new Rule("endBlockComments", new Regex("--(?:>|&gt;)")),
            new Rule("stringDelim", new Regex("(\"|')")),
            new Rule("numbers", new Regex("-?(?:(?:\\b\\d*)?\\.)?\\b\\d+\\b")),
            new Rule("keywords", new Regex("(?:<|&lt;)\\/?(html|base|head|link|meta|style|title|address|article|aside|footer|header|h1|h2|h3|h4|h5|h6|hgroup|nav|section|dd|div|dl|dt|figcaption|figure|hr|li|main|ol|p|pre|ul|a|abbr|b|bdi|bdo|br|cite|code|data|dfn|em|i|kbd|mark|q|rp|rt|rtc|ruby|s|samp|small|span|strong|sub|sup|time|u|var|wbr|area|audio|img|map|track|video|embed|object|param|source|canvas|noscript|script|del|ins|caption|col|colgroup|table|tbody|td|tfoot|th|thead|tr|button|datalist|fieldset|form|input|label|legend|meter|optgroup|option|output|progress|select|textarea|details|dialog|menu|menuitem|summary|content|element|shadow|template|acronym|applet|basefont|big|blink|center|command|content|dir|font|frame|frameset|isindex|keygen|listing|marquee|multicol|nextid|noembed|plaintext|spacer|strike|tt|xmp)\\b")),
            new Rule("members", new Regex("(\\w+)=")))
A grammar for HyperText Markup Language.
Definition at line 10 of file HTML.cs.
JavaScript
readonly Grammar Juniper.Primrose.Grammar.JavaScript static
Initial value:
= new Grammar(
            "JavaScript",
            new Rule("newlines", new Regex("(?:\\r\\n|\\r|\\n)")),
            new Rule("startBlockComments", new Regex("\\/\\*")),
            new Rule("endBlockComments", new Regex("\\*\\/")),
            new Rule("regexes", new Regex("(?:^|,|;|\\(|\\[|\\{)(?:\\s*)(\\/(?:\\\\\\/|[^\\n\\/])+\\/)")),
            new Rule("stringDelim", new Regex("(\"|')")),
            new Rule("startLineComments", new Regex("\\/\\/.*$", RegexOptions.Multiline)),
            new Rule("numbers", new Regex("-?(?:(?:\\b\\d*)?\\.)?\\b\\d+\\b")),
            new Rule("keywords", new Regex("\\b(?:break|case|catch|class|const|continue|debugger|default|delete|do|else|export|finally|for|function|if|import|in|instanceof|let|new|return|super|switch|this|throw|try|typeof|var|void|while|with)\\b")),
            new Rule("functions", new Regex("(\\w+)(?:\\s*\\()")),
            new Rule("members", new Regex("(\\w+)\\.")),
            new Rule("members", new Regex("((\\w+\\.)+)(\\w+)")))
A grammar for the JavaScript programming language.
Definition at line 10 of file JavaScript.cs.
PlainText
readonly Grammar Juniper.Primrose.Grammar.PlainText static
Initial value:
= new Grammar(
            "PlainText",
            new Rule("newlines", new Regex("(?:\\r\\n|\\r|\\n)")))
A grammar that makes displaying plain text work with the text editor designed for syntax highlighting.
Definition at line 10 of file PlainText.cs.
TestResults
readonly Grammar Juniper.Primrose.Grammar.TestResults static
Initial value:
= new Grammar(
            "TestResults",
            new Rule("newlines", new Regex("(?:\\r\\n|\\r|\\n)")),
            new Rule("numbers", new Regex("(\\[)(o+)")),
            new Rule("numbers", new Regex("(\\d+ succeeded), 0 failed")),
            new Rule("numbers", new Regex("^    Successes:")),
            new Rule("functions", new Regex("(x+)\\]")),
            new Rule("functions", new Regex("[1-9]\\d* failed")),
            new Rule("functions", new Regex("^Failures:")),
            new Rule("comments", new Regex("(\\d + ms:)(.*) ")),
            new Rule("keywords", new Regex("(Test results for )(\\w +):")),
            new Rule("strings", new Regex("\\w +")))
A grammar for displaying the results of Unit Tests.
Definition at line 10 of file TestResults.cs.
Property Documentation
Name
string Juniper.Primrose.Grammar.Name get
A user-friendly name for the grammar, to be able to include it in an options listing
Definition at line 65 of file Grammar.cs.
 {
Referenced by Juniper.Primrose.Grammar.Grammar().
Rules
Rule [] Juniper.Primrose.Grammar.Rules get
A collection of rules to apply to tokenize text. The rules should be an array of two-element arrays. The first element should be a token name (see Primrose.Text.Rule for a list of valid token names), followed by a regular expression that selects the token out of the source code.
Definition at line 69 of file Grammar.cs.
 {
Referenced by Juniper.Primrose.Grammar.Grammar(), and Juniper.Primrose.Grammar.Tokenize().
The documentation for this class was generated from the following files:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Primrose/Grammar.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Primrose/Grammars/HTML.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Primrose/Grammars/JavaScript.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Primrose/Grammars/PlainText.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Primrose/Grammars/TestResults.cs