Juniper: BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder Class Reference
BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder Class Reference
Classes
class SavableState
Public Member Functions
HuffmanEntropyDecoder (JpegDecompressStruct cinfo)
override void StartPass ()
Initialize for a Huffman-compressed scan.
void FinishPassHuffman ()
delegate bool DecodeMcuDelegate (JBlock[] MCU_data)
delegate void FinishPassDelegate ()
Static Protected Member Functions
static int JpegHuffmanDecode (ref BitreadWorkingState state, int get_buffer, int bits_left, DDerivedTable htbl, int min_bits)
Properties
DecodeMcuDelegate decodeMcu [get, set]
FinishPassDelegate finishPass [get, set]
Private Member Functions
bool DecodeMcuFull (JBlock[] MCU_data)
Decode one MCU's worth of Huffman-compressed coefficients, full-size blocks.
bool DecodeMcuSub (JBlock[] MCU_data)
Decode one MCU's worth of Huffman-compressed coefficients, partial blocks.
bool DecodeMcuDCFirst (JBlock[] MCU_data)
MCU decoding for DC initial scan (either spectral selection, or first pass of successive approximation).
bool DecodeMcuACFirst (JBlock[] MCU_data)
MCU decoding for AC initial scan (either spectral selection, or first pass of successive approximation).
bool DecodeMcuDCRefine (JBlock[] MCU_data)
MCU decoding for DC successive approximation refinement scan. Note: we assume such scans can be multi-component, although the spec is not very clear on the point.
bool DecodeMcuACRefine (JBlock[] MCU_data)
bool ProcessRestart ()
Check for a restart marker and resynchronize decoder. Returns false if must suspend.
void BITREAD_LOAD_STATE (BitreadPermState bitstate, out int get_buffer, out int bits_left, ref BitreadWorkingState br_state)
void JpegMakeDDerivedTable (bool isDC, int tblno, ref DDerivedTable dtbl)
Expand a Huffman table definition into the derived format This routine also performs some validation checks on the table.
Static Private Member Functions
static int HUFF_EXTEND (int x, int s)
static void BITREAD_SAVE_STATE (ref BitreadPermState bitstate, int get_buffer, int bits_left)
static void CHECK_BIT_BUFFER (ref BitreadWorkingState state, int nbits, ref int get_buffer, ref int bits_left)
static int GET_BITS (int nbits, int get_buffer, ref int bits_left)
static int PEEK_BITS (int nbits, int get_buffer, int bits_left)
static void DROP_BITS (int nbits, ref int bits_left)
static void HUFF_DECODE (out int result, ref BitreadWorkingState state, DDerivedTable htbl, ref int get_buffer, ref int bits_left)
static void JpegFillBitBuffer (ref BitreadWorkingState state, int get_buffer, int bits_left, int nbits)
Private Attributes
const int BIT_BUF_SIZE = 32
const int MIN_GET_BITS = BIT_BUF_SIZE - 7
BitreadPermState bitState
readonly SavableState saved = new SavableState()
bool insufficientData
int restartsToGo
readonly DDerivedTable [] DerivedTables = new DDerivedTable[JpegConstants.NUM_HUFF_TBLS]
DDerivedTable acDerivedTable
readonly DDerivedTable [] dcDerivedTables = new DDerivedTable[JpegConstants.NUM_HUFF_TBLS]
readonly DDerivedTable [] acDerivedTables = new DDerivedTable[JpegConstants.NUM_HUFF_TBLS]
readonly DDerivedTable [] dcCurTables = new DDerivedTable[JpegConstants.D_MAX_BLOCKS_IN_MCU]
readonly DDerivedTable [] acCurTables = new DDerivedTable[JpegConstants.D_MAX_BLOCKS_IN_MCU]
readonly int [] coefLimit = new int[JpegConstants.D_MAX_BLOCKS_IN_MCU]
readonly JpegDecompressStruct cinfo
Static Private Attributes
static readonly int [] bmask
static readonly int [][] jpeg_zigzag_order
static readonly int [][] jpeg_zigzag_order7
static readonly int [][] jpeg_zigzag_order6
static readonly int [][] jpeg_zigzag_order5
static readonly int [][] jpeg_zigzag_order4
static readonly int [][] jpeg_zigzag_order3
static readonly int [][] jpeg_zigzag_order2
Detailed Description
Expanded entropy decoder object for Huffman decoding.
The savable_state subrecord contains fields that change within an MCU, but must not be updated permanently until we complete the MCU.
Definition at line 23 of file HuffmanEntropyDecoder.cs.
Constructor & Destructor Documentation
HuffmanEntropyDecoder()
BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder (JpegDecompressStruct cinfo) inline
Definition at line 176 of file HuffmanEntropyDecoder.cs.
         {
             this.cinfo = cinfo;
             finishPass = FinishPassHuffman;
             if (this.cinfo.progressiveMode)
             {
                 /* Create progression status table */
                 cinfo.coefBits = new int[cinfo.numComponents][];
                 for (var i = 0; i < cinfo.numComponents; i++)
                 {
                     cinfo.coefBits[i] = new int[JpegConstants.DCTSIZE2];
                 }
                 for (var ci = 0; ci < cinfo.numComponents; ci++)
                 {
                     for (var i = 0; i < JpegConstants.DCTSIZE2; i++)
                     {
                         cinfo.coefBits[ci][i] = -1;
                     }
                 }
                 /* Mark derived tables unallocated */
                 for (var i = 0; i < JpegConstants.NUM_HUFF_TBLS; i++)
                 {
                     DerivedTables[i] = null;
                 }
             }
             else
             {
                 /* Mark tables unallocated */
                 for (var i = 0; i < JpegConstants.NUM_HUFF_TBLS; i++)
                 {
                     dcDerivedTables[i] = null;
                     acDerivedTables[i] = null;
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acDerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.coefBits, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.dcDerivedTables, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DerivedTables, BitMiracle.LibJpeg.Classic.Internal.JpegEntropyDecoder.finishPass, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.progressiveMode.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegFillBitBuffer().
Member Function Documentation
BITREAD_LOAD_STATE()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE (BitreadPermState bitstate, out int get_buffer, out int bits_left, ref BitreadWorkingState br_state) inline private
Definition at line 1311 of file HuffmanEntropyDecoder.cs.
         {
             br_state.cinfo = cinfo;
             get_buffer = bitstate.getBuffer;
             bits_left = bitstate.bitsLeft;
         }
References BitMiracle.LibJpeg.Classic.Internal.BitreadPermState.bitsLeft, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, and BitMiracle.LibJpeg.Classic.Internal.BitreadPermState.getBuffer.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub().
BITREAD_SAVE_STATE()
static void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_SAVE_STATE (ref BitreadPermState bitstate, int get_buffer, int bits_left) inline static private
Definition at line 1318 of file HuffmanEntropyDecoder.cs.
         {
             bitstate.getBuffer = get_buffer;
             bitstate.bitsLeft = bits_left;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub().
CHECK_BIT_BUFFER()
static void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER (ref BitreadWorkingState state, int nbits, ref int get_buffer, ref int bits_left) inline static private
Definition at line 1341 of file HuffmanEntropyDecoder.cs.
         {
             if (bits_left < nbits)
             {
                 JpegFillBitBuffer(ref state, get_buffer, bits_left, nbits);
                 get_buffer = state.getBuffer;
                 bits_left = state.bitsLeft;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegFillBitBuffer().
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegHuffmanDecode().
DecodeMcuACFirst()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst (JBlock [] MCU_data) inline private
MCU decoding for AC initial scan (either spectral selection, or first pass of successive approximation).
Definition at line 919 of file HuffmanEntropyDecoder.cs.
         {
             /* Process restart marker if needed; may have to suspend */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     if (!ProcessRestart())
                     {
                         return false;
                     }
                 }
             }
             /* If we've run out of data, just leave the MCU set to zeroes.
              * This way, we return uniform gray for the remainder of the segment.
              */
             if (!insufficientData)
             {
                 /* Load up working state.
                  * We can avoid loading/saving bitread state if in an EOB run.
                  */
                 var EOBRUN = saved.EOBRUN; /* only part of saved state we need */
                 var natural_order = cinfo.natural_order;
                 /* There is always only one block per MCU */
                 if (EOBRUN != 0)
                 {
                     /* if it's a band of zeroes... */
                     /* ...process it now (we do nothing) */
                     EOBRUN--;
                 }
                 else
                 {
                     var br_state = new BitreadWorkingState();
                     BITREAD_LOAD_STATE(bitState, out var get_buffer, out var bits_left, ref br_state);
                     for (var k = cinfo.m_Ss; k <= cinfo.m_Se; k++)
                     {
                         HUFF_DECODE(out var s, ref br_state, acDerivedTable, ref get_buffer, ref bits_left);
                         var r = s >> 4;
                         s &= 15;
                         if (s != 0)
{
                             k += r;
                             CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                             r = GET_BITS(s, get_buffer, ref bits_left);
                             s = HUFF_EXTEND(r, s);
                             /* Scale and output coefficient in natural (dezigzagged) order */
                             MCU_data[0][natural_order[k]] = (short)(s << cinfo.m_Al);
                         }
                         else
{
                             if (r != 15)
{
                                 /* EOBr, run length is 2^r + appended bits */
                                 if (r != 0)
{
                                     /* EOBr, r > 0 */
                                     EOBRUN = (uint)(1 << r);
                                     CHECK_BIT_BUFFER(ref br_state, r, ref get_buffer, ref bits_left);
                                     r = GET_BITS(r, get_buffer, ref bits_left);
                                     EOBRUN += (uint)r;
                                     EOBRUN--;        /* this band is processed at this moment */
                                 }
                                 break;      /* force end-of-band */
                             }
                             k += 15;        /* ZRL: skip 15 zeroes in band */
                         }
                     }
                     BITREAD_SAVE_STATE(ref bitState, get_buffer, bits_left);
                 }
                 /* Completed MCU, so update state */
                 saved.EOBRUN = EOBRUN; /* only part of saved state we need */
             }
             /* Account for restart interval (no-op if not using restarts) */
             restartsToGo--;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acDerivedTable, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_SAVE_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.EOBRUN, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_EXTEND(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.natural_order, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
DecodeMcuACRefine()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine (JBlock [] MCU_data) inline private
Definition at line 1067 of file HuffmanEntropyDecoder.cs.
         {
             /* Process restart marker if needed; may have to suspend */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     if (!ProcessRestart())
                     {
                         return false;
                     }
                 }
             }
             /* If we've run out of data, don't modify the MCU.
              */
             if (!insufficientData)
             {
                 var p1 = 1 << cinfo.m_Al;    /* 1 in the bit position being coded */
                 var m1 = -1 << cinfo.m_Al; /* -1 in the bit position being coded */
                 var natural_order = cinfo.natural_order;
                 /* Load up working state */
                 var br_state = new BitreadWorkingState();
                 BITREAD_LOAD_STATE(bitState, out var get_buffer, out var bits_left, ref br_state);
                 var EOBRUN = saved.EOBRUN; /* only part of saved state we need */
                 /* If we are forced to suspend, we must undo the assignments to any newly
                  * nonzero coefficients in the block, because otherwise we'd get confused
                  * next time about which coefficients were already nonzero.
                  * But we need not undo addition of bits to already-nonzero coefficients;
                  * instead, we can test the current bit to see if we already did it.
                  */
                 var num_newnz = 0;
                 var newnz_pos = new int[JpegConstants.DCTSIZE2];
                 /* initialize coefficient loop counter to start of band */
                 var k = cinfo.m_Ss;
                 if (EOBRUN == 0)
                 {
                     do
                     {
                         HUFF_DECODE(out var s, ref br_state, acDerivedTable, ref get_buffer, ref bits_left);
                         var r = s >> 4;
                         s &= 15;
                         if (s != 0)
{
                             if (s != 1)
{
                                 /* size of new coef should always be 1 */
                                 cinfo.WarnMS(JMessageCode.JWRN_HUFF_BAD_CODE);
                             }
                             CHECK_BIT_BUFFER(ref br_state, 1, ref get_buffer, ref bits_left);
                             if (GET_BITS(1, get_buffer, ref bits_left) != 0)
{
                                 /* newly nonzero coef is positive */
                                 s = p1;
                             }
                             else
{
                                 /* newly nonzero coef is negative */
                                 s = m1;
                             }
                         }
                         else
{
                             if (r != 15)
{
                                 EOBRUN = (uint)(1 << r);    /* EOBr, run length is 2^r + appended bits */
                                 if (r != 0)
{
                                     CHECK_BIT_BUFFER(ref br_state, r, ref get_buffer, ref bits_left);
                                     r = GET_BITS(r, get_buffer, ref bits_left);
                                     EOBRUN += (uint)r;
                                 }
                                 break;      /* rest of block is handled by EOB logic */
                             }
                             /* note s = 0 for processing ZRL */
                         }
                         /* Advance over already-nonzero coefs and r still-zero coefs,
                          * appending correction bits to the nonzeroes.  A correction bit is 1
                          * if the absolute value of the coefficient must be increased.
                          */
                         do
{
                             var blockIndex = natural_order[k];
                             var thiscoef = MCU_data[0][blockIndex];
                             if (thiscoef != 0)
{
                                 CHECK_BIT_BUFFER(ref br_state, 1, ref get_buffer, ref bits_left);
                                 if (GET_BITS(1, get_buffer, ref bits_left) != 0)
{
                                     if ((thiscoef & p1) == 0)
{
                                         /* do nothing if already set it */
                                         if (thiscoef >= 0)
{
                                             MCU_data[0][blockIndex] += (short)p1;
                                         }
                                         else
{
                                             MCU_data[0][blockIndex] += (short)m1;
                                         }
                                     }
                                 }
                             }
                             else if (--r < 0)
{
                                 break;      /* reached target zero coefficient */
                             }
                             k++;
                         }
                         while (k <= cinfo.m_Se);
                         if (s != 0)
{
                             var pos = natural_order[k];
                             /* Output newly nonzero coefficient */
                             MCU_data[0][pos] = (short)s;
                             /* Remember its position in case we have to suspend */
                             newnz_pos[num_newnz++] = pos;
                         }
                         k++;
                     } while (k <= cinfo.m_Se);
                 }
                 if (EOBRUN != 0)
                 {
                     /* Scan any remaining coefficient positions after the end-of-band
                      * (the last newly nonzero coefficient, if any).  Append a correction
                      * bit to each already-nonzero coefficient.  A correction bit is 1
                      * if the absolute value of the coefficient must be increased.
                      */
                     do
                     {
                         var blockIndex = natural_order[k];
                         var thiscoef = MCU_data[0][blockIndex];
                         if (thiscoef != 0)
{
                             CHECK_BIT_BUFFER(ref br_state, 1, ref get_buffer, ref bits_left);
                             if (GET_BITS(1, get_buffer, ref bits_left) != 0)
{
                                 if ((thiscoef & p1) == 0)
{
                                     /* do nothing if already changed it */
                                     if (thiscoef >= 0)
{
                                         MCU_data[0][blockIndex] += (short)p1;
                                     }
                                     else
{
                                         MCU_data[0][blockIndex] += (short)m1;
                                     }
                                 }
                             }
                         }
                         k++;
                     } while (k <= cinfo.m_Se);
                     /* Count one block completed in EOB run */
                     EOBRUN--;
                 }
                 /* Completed MCU, so update state */
                 BITREAD_SAVE_STATE(ref bitState, get_buffer, bits_left);
                 saved.EOBRUN = EOBRUN; /* only part of saved state we need */
             }
             /* Account for restart interval (no-op if not using restarts) */
             restartsToGo--;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acDerivedTable, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_SAVE_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.EOBRUN, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.natural_order, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
DecodeMcuDCFirst()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst (JBlock [] MCU_data) inline private
MCU decoding for DC initial scan (either spectral selection, or first pass of successive approximation).
Definition at line 853 of file HuffmanEntropyDecoder.cs.
         {
             /* Process restart marker if needed; may have to suspend */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     if (!ProcessRestart())
                     {
                         return false;
                     }
                 }
             }
             /* If we've run out of data, just leave the MCU set to zeroes.
              * This way, we return uniform gray for the remainder of the segment.
              */
             if (!insufficientData)
             {
                 /* Load up working state */
                 var br_state = new BitreadWorkingState();
                 BITREAD_LOAD_STATE(bitState, out var get_buffer, out var bits_left, ref br_state);
                 var state = new SavableState();
                 state.Assign(saved);
                 /* Outer loop handles each block in the MCU */
                 for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
                 {
                     var ci = cinfo.m_MCU_membership[blkn];
                     /* Decode a single block's worth of coefficients */
                     /* Section F.2.2.1: decode the DC coefficient difference */
                     HUFF_DECODE(out var s, ref br_state, DerivedTables[cinfo.CompInfo[cinfo.m_cur_comp_info[ci]].Dc_tbl_no], ref get_buffer, ref bits_left);
                     if (s != 0)
                     {
                         CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                         var r = GET_BITS(s, get_buffer, ref bits_left);
                         s = HUFF_EXTEND(r, s);
                     }
                     /* Convert DC difference to actual value, update last_dc_val */
                     s += state.last_dc_val[ci];
                     state.last_dc_val[ci] = s;
                     /* Scale and output the coefficient (assumes jpeg_natural_order[0]=0) */
                     MCU_data[blkn][0] = (short)(s << cinfo.m_Al);
                 }
                 /* Completed MCU, so update state */
                 BITREAD_SAVE_STATE(ref bitState, get_buffer, bits_left);
                 saved.Assign(state);
             }
             /* Account for restart interval (no-op if not using restarts) */
             restartsToGo--;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.Assign(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_SAVE_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_EXTEND(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
DecodeMcuDCRefine()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine (JBlock [] MCU_data) inline private
MCU decoding for DC successive approximation refinement scan. Note: we assume such scans can be multi-component, although the spec is not very clear on the point.
Definition at line 1017 of file HuffmanEntropyDecoder.cs.
         {
             /* Process restart marker if needed; may have to suspend */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     if (!ProcessRestart())
                     {
                         return false;
                     }
                 }
             }
             /* Not worth the cycles to check insufficient_data here,
              * since we will not change the data anyway if we read zeroes.
              */
             /* Load up working state */
             var br_state = new BitreadWorkingState();
             BITREAD_LOAD_STATE(bitState, out var get_buffer, out var bits_left, ref br_state);
             var p1 = 1 << cinfo.m_Al;
             /* Outer loop handles each block in the MCU */
             for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
             {
                 /* Encoded data is simply the next bit of the two's-complement DC value */
                 CHECK_BIT_BUFFER(ref br_state, 1, ref get_buffer, ref bits_left);
                 if (GET_BITS(1, get_buffer, ref bits_left) != 0)
                 {
                     /* 1 in the bit position being coded */
                     MCU_data[blkn][0] = (short)((ushort)MCU_data[blkn][0] | p1);
                 }
                 /* Note: since we use |=, repeating the assignment later is safe */
             }
             /* Completed MCU, so update state */
             BITREAD_SAVE_STATE(ref bitState, get_buffer, bits_left);
             /* Account for restart interval (no-op if not using restarts) */
             restartsToGo--;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_SAVE_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
DecodeMcuDelegate()
delegate bool BitMiracle.LibJpeg.Classic.Internal.JpegEntropyDecoder.DecodeMcuDelegate (JBlock [] MCU_data) inherited
DecodeMcuFull()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull (JBlock [] MCU_data) inline private
Decode one MCU's worth of Huffman-compressed coefficients, full-size blocks.
Definition at line 549 of file HuffmanEntropyDecoder.cs.
         {
             /* Process restart marker if needed; may have to suspend */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     if (!ProcessRestart())
                     {
                         return false;
                     }
                 }
             }
             /* If we've run out of data, just leave the MCU set to zeroes.
              * This way, we return uniform gray for the remainder of the segment.
              */
             if (!insufficientData)
             {
                 /* Load up working state */
                 var br_state = new BitreadWorkingState();
                 BITREAD_LOAD_STATE(bitState, out var get_buffer, out var bits_left, ref br_state);
                 var state = new SavableState();
                 state.Assign(saved);
                 /* Outer loop handles each block in the MCU */
                 for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
                 {
                     /* Decode a single block's worth of coefficients */
                     /* Section F.2.2.1: decode the DC coefficient difference */
                     var htbl = dcCurTables[blkn];
                     HUFF_DECODE(out var s, ref br_state, htbl, ref get_buffer, ref bits_left);
                     htbl = acCurTables[blkn];
                     var k = 1;
                     var coef_limit = coefLimit[blkn];
                     var endThisBlock = false;
                     if (coef_limit != 0)
                     {
                         /* Convert DC difference to actual value, update last_dc_val */
                         if (s != 0)
{
                             CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                             var r = GET_BITS(s, get_buffer, ref bits_left);
                             s = HUFF_EXTEND(r, s);
                         }
                         var ci = cinfo.m_MCU_membership[blkn];
                         s += state.last_dc_val[ci];
                         state.last_dc_val[ci] = s;
                         /* Output the DC coefficient */
                         MCU_data[blkn][0] = (short)s;
                         /* Section F.2.2.2: decode the AC coefficients */
                         /* Since zeroes are skipped, output area must be cleared beforehand */
                         for (; k < coef_limit; k++)
{
                             HUFF_DECODE(out s, ref br_state, htbl, ref get_buffer, ref bits_left);
                             var r = s >> 4;
                             s &= 15;
                             if (s != 0)
{
                                 k += r;
                                 CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                                 r = GET_BITS(s, get_buffer, ref bits_left);
                                 s = HUFF_EXTEND(r, s);
                                 /* Output coefficient in natural (dezigzagged) order.
                                  * Note: the extra entries in jpeg_natural_order[] will save us
                                  * if k >= DCTSIZE2, which could happen if the data is corrupted.
                                  */
                                 MCU_data[blkn][JpegUtils.jpeg_natural_order[k]] = (short)s;
                             }
                             else
{
                                 if (r != 15)
{
                                     endThisBlock = true;
                                     break;
                                 }
                                 k += 15;
                             }
                         }
                     }
                     else if (s != 0)
                     {
                         CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                         DROP_BITS(s, ref bits_left);
                     }
                     if (endThisBlock)
                     {
                         continue;
                     }
                     /* Section F.2.2.2: decode the AC coefficients */
                     /* In this path we just discard the values */
                     for (; k < JpegConstants.DCTSIZE2; k++)
                     {
                         HUFF_DECODE(out s, ref br_state, htbl, ref get_buffer, ref bits_left);
                         var r = s >> 4;
                         s &= 15;
                         if (s != 0)
{
                             k += r;
                             CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                             DROP_BITS(s, ref bits_left);
                         }
                         else
{
                             if (r != 15)
{
                                 break;
                             }
                             k += 15;
                         }
                     }
                 }
                 /* Completed MCU, so update state */
                 BITREAD_SAVE_STATE(ref bitState, get_buffer, bits_left);
                 saved.Assign(state);
             }
             /* Account for restart interval (no-op if not using restarts) */
             restartsToGo--;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acCurTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.Assign(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_SAVE_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.coefLimit, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.dcCurTables, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DROP_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_EXTEND(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
DecodeMcuSub()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub (JBlock [] MCU_data) inline private
Decode one MCU's worth of Huffman-compressed coefficients, partial blocks.
Definition at line 693 of file HuffmanEntropyDecoder.cs.
         {
             /* Process restart marker if needed; may have to suspend */
             if (cinfo.m_restart_interval != 0)
             {
                 if (restartsToGo == 0)
                 {
                     if (!ProcessRestart())
                     {
                         return false;
                     }
                 }
             }
             /* If we've run out of data, just leave the MCU set to zeroes.
              * This way, we return uniform gray for the remainder of the segment.
              */
             if (!insufficientData)
             {
                 var natural_order = cinfo.natural_order;
                 var Se = cinfo.m_Se;
                 /* Load up working state */
                 var br_state = new BitreadWorkingState();
                 BITREAD_LOAD_STATE(bitState, out var get_buffer, out var bits_left, ref br_state);
                 var state = new SavableState();
                 state.Assign(saved);
                 /* Outer loop handles each block in the MCU */
                 for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
                 {
                     /* Decode a single block's worth of coefficients */
                     /* Section F.2.2.1: decode the DC coefficient difference */
                     var htbl = dcCurTables[blkn];
                     HUFF_DECODE(out var s, ref br_state, htbl, ref get_buffer, ref bits_left);
                     htbl = acCurTables[blkn];
                     var k = 1;
                     var coef_limit = coefLimit[blkn];
                     if (coef_limit != 0)
                     {
                         /* Convert DC difference to actual value, update last_dc_val */
                         if (s != 0)
{
                             CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                             var r = GET_BITS(s, get_buffer, ref bits_left);
                             s = HUFF_EXTEND(r, s);
                         }
                         var ci = cinfo.m_MCU_membership[blkn];
                         s += state.last_dc_val[ci];
                         state.last_dc_val[ci] = s;
                         /* Output the DC coefficient */
                         MCU_data[blkn][0] = (short)s;
                         /* Section F.2.2.2: decode the AC coefficients */
                         /* Since zeroes are skipped, output area must be cleared beforehand */
                         for (; k < coef_limit; k++)
{
                             HUFF_DECODE(out s, ref br_state, htbl, ref get_buffer, ref bits_left);
                             var r = s >> 4;
                             s &= 15;
                             if (s != 0)
{
                                 k += r;
                                 CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                                 r = GET_BITS(s, get_buffer, ref bits_left);
                                 s = HUFF_EXTEND(r, s);
                                 /* Output coefficient in natural (dezigzagged) order.
                                  * Note: the extra entries in natural_order[] will save us
                                  * if k >= Se, which could happen if the data is corrupted.
                                  */
                                 MCU_data[blkn][natural_order[k]] = (short)s;
                             }
                             else
{
                                 if (r != 15)
{
                                     continue;
                                 }
                                 k += 15;
                             }
                         }
                     }
                     else if (s != 0)
                     {
                         CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                         DROP_BITS(s, ref bits_left);
                     }
                     /* Section F.2.2.2: decode the AC coefficients */
                     /* In this path we just discard the values */
                     for (; k <= Se; k++)
                     {
                         HUFF_DECODE(out s, ref br_state, htbl, ref get_buffer, ref bits_left);
                         var r = s >> 4;
                         s &= 15;
                         if (s != 0)
{
                             k += r;
                             CHECK_BIT_BUFFER(ref br_state, s, ref get_buffer, ref bits_left);
                             DROP_BITS(s, ref bits_left);
                         }
                         else
{
                             if (r != 15)
{
                                 break;
                             }
                             k += 15;
                         }
                     }
                 }
                 /* Completed MCU, so update state */
                 BITREAD_SAVE_STATE(ref bitState, get_buffer, bits_left);
                 saved.Assign(state);
             }
             /* Account for restart interval (no-op if not using restarts) */
             restartsToGo--;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acCurTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.Assign(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_SAVE_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.coefLimit, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.dcCurTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DROP_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_EXTEND(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.natural_order, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
DROP_BITS()
static void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DROP_BITS (int nbits, ref int bits_left) inline static private
Definition at line 1361 of file HuffmanEntropyDecoder.cs.
         {
             bits_left -= nbits;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE().
FinishPassDelegate()
delegate void BitMiracle.LibJpeg.Classic.Internal.JpegEntropyDecoder.FinishPassDelegate () inherited
FinishPassHuffman()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.FinishPassHuffman () inline
Definition at line 1259 of file HuffmanEntropyDecoder.cs.
         {
             /* Throw away any unused bits remaining in bit buffer; */
             /* include any full bytes in next_marker's count of discarded bytes */
             cinfo.m_marker.SkipBytes(bitState.bitsLeft / 8);
             bitState.bitsLeft = 0;
         }
References BitMiracle.LibJpeg.Classic.Internal.BitreadPermState.bitsLeft, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart().
GET_BITS()
static int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS (int nbits, int get_buffer, ref int bits_left) inline static private
Definition at line 1351 of file HuffmanEntropyDecoder.cs.
         {
             return (get_buffer >> (bits_left -= nbits)) & bmask[nbits];
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bmask.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegHuffmanDecode().
HUFF_DECODE()
static void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE (out int result, ref BitreadWorkingState state, DDerivedTable htbl, ref int get_buffer, ref int bits_left) inline static private
Definition at line 1382 of file HuffmanEntropyDecoder.cs.
         {
             var nb = 0;
             var doSlow = false;
             if (bits_left < JpegConstants.HUFF_LOOKAHEAD)
             {
                 JpegFillBitBuffer(ref state, get_buffer, bits_left, 0);
                 get_buffer = state.getBuffer;
                 bits_left = state.bitsLeft;
                 if (bits_left < JpegConstants.HUFF_LOOKAHEAD)
                 {
                     nb = 1;
                     doSlow = true;
                 }
             }
             if (!doSlow)
             {
                 var look = PEEK_BITS(JpegConstants.HUFF_LOOKAHEAD, get_buffer, bits_left);
                 if ((nb = htbl.lookNBits[look]) != 0)
                 {
                     DROP_BITS(nb, ref bits_left);
                     result = htbl.lookSym[look];
                     return;
                 }
                 nb = JpegConstants.HUFF_LOOKAHEAD + 1;
             }
             result = JpegHuffmanDecode(ref state, get_buffer, bits_left, htbl, nb);
             get_buffer = state.getBuffer;
             bits_left = state.bitsLeft;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DROP_BITS(), BitMiracle.LibJpeg.Classic.JpegConstants.HUFF_LOOKAHEAD, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegFillBitBuffer(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegHuffmanDecode(), BitMiracle.LibJpeg.Classic.Internal.DDerivedTable.lookNBits, BitMiracle.LibJpeg.Classic.Internal.DDerivedTable.lookSym, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.PEEK_BITS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub().
HUFF_EXTEND()
static int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_EXTEND (int x, int s) inline static private
Definition at line 1306 of file HuffmanEntropyDecoder.cs.
         {
             return x <= bmask[s - 1] ? x - bmask[s] : x;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bmask.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub().
JpegFillBitBuffer()
static void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegFillBitBuffer (ref BitreadWorkingState state, int get_buffer, int bits_left, int nbits) inline static private
Definition at line 1420 of file HuffmanEntropyDecoder.cs.
         {
             /* Attempt to load at least MIN_GET_BITS bits into get_buffer. */
             /* (It is assumed that no request will be for more than that many bits.) */
             /* We fail to do so only if we hit a marker or are forced to suspend. */
             var noMoreBytes = false;
             if (state.cinfo.m_unreadMarker == 0)
             {
                 /* cannot advance past a marker */
                 while (bits_left < MIN_GET_BITS)
                 {
                     _ = state.cinfo.m_src.GetByte(out var c);
                     /* If it's 0xFF, check and discard stuffed zero byte */
                     if (c == 0xFF)
                     {
                         /* Loop here to discard any padding FF's on terminating marker,
                         * so that we can save a valid unread_marker value.  NOTE: we will
                         * accept multiple FF's followed by a 0 as meaning a single FF data
                         * byte.  This data pattern is not valid according to the standard.
                         */
                         do
{
                             _ = state.cinfo.m_src.GetByte(out c);
                         }
                         while (c == 0xFF);
                         if (c == 0)
{
                             /* Found FF/00, which represents an FF data byte */
                             c = 0xFF;
                         }
                         else
{
                             /* Oops, it's actually a marker indicating end of compressed data.
                             * Save the marker code for later use.
                             * Fine point: it might appear that we should save the marker into
                             * bitread working state, not straight into permanent state.  But
                             * once we have hit a marker, we cannot need to suspend within the
                             * current MCU, because we will read no more bytes from the data
                             * source.  So it is OK to update permanent state right away.
                             */
                             state.cinfo.m_unreadMarker = c;
                             /* See if we need to insert some fake zero bits. */
                             noMoreBytes = true;
                             break;
                         }
                     }
                     /* OK, load c into get_buffer */
                     get_buffer = (get_buffer << 8) | c;
                     bits_left += 8;
                 } /* end while */
             }
             else
             {
                 noMoreBytes = true;
             }
             if (noMoreBytes)
             {
                 /* We get here if we've read the marker that terminates the compressed
                 * data segment.  There should be enough bits in the buffer register
                 * to satisfy the request; if so, no problem.
                 */
                 if (nbits > bits_left)
                 {
                     /* Uh-oh.  Report corrupted data to user and stuff zeroes into
                     * the data stream, so that we can produce some kind of image.
                     * We use a nonvolatile flag to ensure that only one warning message
                     * appears per data segment.
                     */
                     var entropy = (HuffmanEntropyDecoder)state.cinfo.m_entropy;
                     if (!entropy.insufficientData)
                     {
                         state.cinfo.WarnMS(JMessageCode.JWRN_HIT_MARKER);
                         entropy.insufficientData = true;
                     }
                     /* Fill the buffer with zero bits */
                     get_buffer <<= MIN_GET_BITS - bits_left;
                     bits_left = MIN_GET_BITS;
                 }
             }
             /* Unload the local registers */
             state.getBuffer = get_buffer;
             state.bitsLeft = bits_left;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.MIN_GET_BITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE().
JpegHuffmanDecode()
static int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegHuffmanDecode (ref BitreadWorkingState state, int get_buffer, int bits_left, DDerivedTable htbl, int min_bits) inline static protected
Definition at line 1658 of file HuffmanEntropyDecoder.cs.
         {
             /* HUFF_DECODE has determined that the code is at least min_bits */
             /* bits long, so fetch that many bits in one swoop. */
             var l = min_bits;
             CHECK_BIT_BUFFER(ref state, l, ref get_buffer, ref bits_left);
             var code = GET_BITS(l, get_buffer, ref bits_left);
             /* Collect the rest of the Huffman code one bit at a time. */
             /* This is per Figure F.16 in the JPEG spec. */
             while (code > htbl.maxCode[l])
             {
                 code <<= 1;
                 CHECK_BIT_BUFFER(ref state, 1, ref get_buffer, ref bits_left);
                 code |= GET_BITS(1, get_buffer, ref bits_left);
                 l++;
             }
             /* Unload the local registers */
             state.getBuffer = get_buffer;
             state.bitsLeft = bits_left;
             /* With garbage input we may reach the sentinel value l = 17. */
             if (l > 16)
             {
                 state.cinfo.WarnMS(JMessageCode.JWRN_HUFF_BAD_CODE);
                 /* fake a zero as the safest result */
                 return 0;
             }
             return htbl.pub.Huffval[code + htbl.valOffset[l]];
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.CHECK_BIT_BUFFER(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.JHuffmanTable.Huffval, BitMiracle.LibJpeg.Classic.Internal.DDerivedTable.maxCode, BitMiracle.LibJpeg.Classic.Internal.DDerivedTable.pub, and BitMiracle.LibJpeg.Classic.Internal.DDerivedTable.valOffset.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE().
JpegMakeDDerivedTable()
void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable (bool isDC, int tblno, ref DDerivedTable dtbl) inline private
Expand a Huffman table definition into the derived format This routine also performs some validation checks on the table.
Definition at line 1516 of file HuffmanEntropyDecoder.cs.
         {
             /* Note that huffsize[] and huffcode[] are filled in code-length order,
             * paralleling the order of the symbols themselves in htbl.huffval[].
             */
             /* Find the input Huffman table */
             if (tblno < 0 || tblno >= JpegConstants.NUM_HUFF_TBLS)
             {
                 cinfo.ErrExit(JMessageCode.JERR_NO_HUFF_TABLE, tblno);
             }
             var htbl = isDC ? cinfo.m_dc_huff_tbl_ptrs[tblno] : cinfo.m_ac_huff_tbl_ptrs[tblno];
             if (htbl is null)
             {
                 cinfo.ErrExit(JMessageCode.JERR_NO_HUFF_TABLE, tblno);
             }
             /* Allocate a workspace if we haven't already done so. */
             if (dtbl is null)
             {
                 dtbl = new DDerivedTable();
             }
             dtbl.pub = htbl;       /* fill in back link */
             /* Figure C.1: make table of Huffman code length for each symbol */
             var p = 0;
             var huffsize = new char[257];
             for (var l = 1; l <= 16; l++)
             {
                 int i = htbl.Bits[l];
                 if (p + i > 256)    /* protect against table overrun */
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
                 }
                 while (i-- != 0)
                 {
                     huffsize[p++] = (char)l;
                 }
             }
             huffsize[p] = (char)0;
             var numsymbols = p;
             /* Figure C.2: generate the codes themselves */
             /* We also validate that the counts represent a legal Huffman code tree. */
             var code = 0;
             int si = huffsize[0];
             var huffcode = new int[257];
             p = 0;
             while (huffsize[p] != 0)
             {
                 while (huffsize[p] == si)
                 {
                     huffcode[p++] = code;
                     code++;
                 }
                 /* code is now 1 more than the last code used for codelength si; but
                 * it must still fit in si bits, since no code is allowed to be all ones.
                 */
                 if (code >= (1 << si))
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
                 }
                 code <<= 1;
                 si++;
             }
             /* Figure F.15: generate decoding tables for bit-sequential decoding */
             p = 0;
             for (var l = 1; l <= 16; l++)
             {
                 if (htbl.Bits[l] != 0)
                 {
                     /* valoffset[l] = huffval[] index of 1st symbol of code length l,
                     * minus the minimum code of length l
                     */
                     dtbl.valOffset[l] = p - huffcode[p];
                     p += htbl.Bits[l];
                     dtbl.maxCode[l] = huffcode[p - 1]; /* maximum code of length l */
                 }
                 else
                 {
                     /* -1 if no codes of this length */
                     dtbl.maxCode[l] = -1;
                 }
             }
             dtbl.maxCode[17] = 0xFFFFF; /* ensures jpeg_huff_decode terminates */
             /* Compute lookahead tables to speed up decoding.
             * First we set all the table entries to 0, indicating "too long";
             * then we iterate through the Huffman codes that are short enough and
             * fill in all the entries that correspond to bit sequences starting
             * with that code.
             */
             Array.Clear(dtbl.lookNBits, 0, dtbl.lookNBits.Length);
             p = 0;
             for (var l = 1; l <= JpegConstants.HUFF_LOOKAHEAD; l++)
             {
                 for (var i = 1; i <= htbl.Bits[l]; i++, p++)
                 {
                     /* l = current code's length, p = its index in huffcode[] & huffval[]. */
                     /* Generate left-justified code followed by all possible bit sequences */
                     var lookbits = huffcode[p] << (JpegConstants.HUFF_LOOKAHEAD - l);
                     for (var ctr = 1 << (JpegConstants.HUFF_LOOKAHEAD - l); ctr > 0; ctr--)
                     {
                         dtbl.lookNBits[lookbits] = l;
                         dtbl.lookSym[lookbits] = htbl.Huffval[p];
                         lookbits++;
                     }
                 }
             }
             /* Validate symbols as being reasonable.
             * For AC tables, we make no check, but accept all byte values 0..255.
             * For DC tables, we require the symbols to be in range 0..15.
             * (Tighter bounds could be applied depending on the data depth and mode,
             * but this is sufficient to ensure safe decoding.)
             */
             if (isDC)
             {
                 for (var i = 0; i < numsymbols; i++)
                 {
                     int sym = htbl.Huffval[i];
                     if (sym > 15)
                     {
                         cinfo.ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
                     }
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegConstants.HUFF_LOOKAHEAD, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dc_huff_tbl_ptrs, and BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
PEEK_BITS()
static int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.PEEK_BITS (int nbits, int get_buffer, int bits_left) inline static private
Definition at line 1356 of file HuffmanEntropyDecoder.cs.
         {
             return (get_buffer >> (bits_left - nbits)) & bmask[nbits];
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bmask.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_DECODE().
ProcessRestart()
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart () inline private
Check for a restart marker and resynchronize decoder. Returns false if must suspend.
Definition at line 1271 of file HuffmanEntropyDecoder.cs.
         {
             FinishPassHuffman();
             /* Advance past the RSTn marker */
             if (!cinfo.m_marker.ReadRestartMarker())
             {
                 return false;
             }
             /* Re-initialize DC predictions to 0 */
             for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
             {
                 saved.last_dc_val[ci] = 0;
             }
             /* Re-init EOB run count, too */
             saved.EOBRUN = 0;
             /* Reset restart counter */
             restartsToGo = cinfo.m_restart_interval;
             /* Reset out-of-data flag, unless read_restart_marker left us smack up
              * against a marker.  In that case we will end up treating the next data
              * segment as empty, and we can avoid producing bogus output pixels by
              * leaving the flag set.
              */
             if (cinfo.m_unreadMarker == 0)
             {
                 insufficientData = false;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.EOBRUN, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.last_dc_val, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo, and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub().
StartPass()
override void BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass () inline virtual
Initialize for a Huffman-compressed scan.
Implements BitMiracle.LibJpeg.Classic.Internal.JpegEntropyDecoder.
Definition at line 219 of file HuffmanEntropyDecoder.cs.
         {
             if (cinfo.progressiveMode)
             {
                 var bad = false;
                 /* Validate progressive scan parameters */
                 if (cinfo.m_Ss == 0)
                 {
                     if (cinfo.m_Se != 0)
                     {
                         bad = true;
                     }
                 }
                 else
                 {
                     /* need not check Ss/Se < 0 since they came from unsigned bytes */
                     if (cinfo.m_Se < cinfo.m_Ss || cinfo.m_Se > cinfo.lim_Se)
                     {
                         bad = true;
                     }
                     /* AC scans may have only one component */
                     if (cinfo.m_comps_in_scan != 1)
                     {
                         bad = true;
                     }
                 }
                 if (cinfo.m_Ah != 0)
                 {
                     /* Successive approximation refinement scan: must have Al = Ah-1. */
                     if (cinfo.m_Ah - 1 != cinfo.m_Al)
                     {
                         bad = true;
                     }
                 }
                 if (cinfo.m_Al > 13)
                 {
                     /* need not check for < 0 */
                     /* Arguably the maximum Al value should be less than 13 for 8-bit precision,
                      * but the spec doesn't say so, and we try to be liberal about what we
                      * accept.  Note: large Al values could result in out-of-range DC
                      * coefficients during early scans, leading to bizarre displays due to
                      * overflows in the IDCT math.  But we won't crash.
                      */
                     bad = true;
                 }
                 if (bad)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_PROGRESSION,
                         cinfo.m_Ss, cinfo.m_Se, cinfo.m_Ah, cinfo.m_Al);
                 }
                 /* Update progression status, and verify that scan order is legal.
                  * Note that inter-scan inconsistencies are treated as warnings
                  * not fatal errors ... not clear if this is right way to behave.
                  */
                 for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
                 {
                     var cindex = cinfo.CompInfo[cinfo.m_cur_comp_info[ci]].Component_index;
                     if (cinfo.m_Ss != 0 && cinfo.coefBits[cindex][0] < 0)
                     {
                         /* AC without prior DC scan */
                         cinfo.WarnMS(JMessageCode.JWRN_BOGUS_PROGRESSION, cindex, 0);
                     }
                     for (var coefi = cinfo.m_Ss; coefi <= cinfo.m_Se; coefi++)
                     {
                         var expected = cinfo.coefBits[cindex][coefi];
                         if (expected < 0)
{
                             expected = 0;
                         }
                         if (cinfo.m_Ah != expected)
{
                             cinfo.WarnMS(JMessageCode.JWRN_BOGUS_PROGRESSION, cindex, coefi);
                         }
                         cinfo.coefBits[cindex][coefi] = cinfo.m_Al;
                     }
                 }
                 /* Select MCU decoding routine */
                 if (cinfo.m_Ah == 0)
                 {
                     if (cinfo.m_Ss == 0)
                     {
                         decodeMcu = DecodeMcuDCFirst;
                     }
                     else
                     {
                         decodeMcu = DecodeMcuACFirst;
                     }
                 }
                 else if (cinfo.m_Ss == 0)
                 {
                     decodeMcu = DecodeMcuDCRefine;
                 }
                 else
                 {
                     decodeMcu = DecodeMcuACRefine;
                 }
                 for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
                 {
                     var compptr = cinfo.CompInfo[cinfo.m_cur_comp_info[ci]];
                     /* Make sure requested tables are present, and compute derived tables.
                      * We may build same derived table more than once, but it's not expensive.
                      */
                     if (cinfo.m_Ss == 0)
                     {
                         if (cinfo.m_Ah == 0)
{
                             /* DC refinement needs no table */
                             var tbl = compptr.Dc_tbl_no;
                             JpegMakeDDerivedTable(true, tbl, ref DerivedTables[tbl]);
                         }
                     }
                     else
                     {
                         var tbl = compptr.Ac_tbl_no;
                         JpegMakeDDerivedTable(false, tbl, ref DerivedTables[tbl]);
                         /* remember the single active table */
                         acDerivedTable = DerivedTables[tbl];
                     }
                     /* Initialize DC predictions to 0 */
                     saved.last_dc_val[ci] = 0;
                 }
                 /* Initialize private state variables */
                 saved.EOBRUN = 0;
             }
             else
             {
                 /* Check that the scan parameters Ss, Se, Ah/Al are OK for sequential JPEG.
                  * This ought to be an error condition, but we make it a warning because
                  * there are some baseline files out there with all zeroes in these bytes.
                  */
                 if (cinfo.m_Ss != 0
                     || cinfo.m_Ah != 0
                     || cinfo.m_Al != 0
                     || ((cinfo.isBaseline
                             || cinfo.m_Se < JpegConstants.DCTSIZE2)
                         && cinfo.m_Se != cinfo.lim_Se))
                 {
                     cinfo.WarnMS(JMessageCode.JWRN_NOT_SEQUENTIAL);
                 }
                 /* Select MCU decoding routine */
                 /* We retain the hard-coded case for full-size blocks.
                  * This is not necessary, but it appears that this version is slightly
                  * more performant in the given implementation.
                  * With an improved implementation we would prefer a single optimized
                  * function.
                  */
                 if (cinfo.lim_Se != JpegConstants.DCTSIZE2 - 1)
                 {
                     decodeMcu = DecodeMcuSub;
                 }
                 else
                 {
                     decodeMcu = DecodeMcuFull;
                 }
                 for (var ci = 0; ci < cinfo.m_comps_in_scan; ci++)
                 {
                     var componentInfo = cinfo.CompInfo[cinfo.m_cur_comp_info[ci]];
                     /* Compute derived values for Huffman tables */
                     /* We may do this more than once for a table, but it's not expensive */
                     var tbl = componentInfo.Dc_tbl_no;
                     JpegMakeDDerivedTable(true, tbl, ref dcDerivedTables[tbl]);
                     if (cinfo.lim_Se != 0)
                     {
                         /* AC needs no table when not present */
                         tbl = componentInfo.Ac_tbl_no;
                         JpegMakeDDerivedTable(false, tbl, ref acDerivedTables[tbl]);
                     }
                     /* Initialize DC predictions to 0 */
                     saved.last_dc_val[ci] = 0;
                 }
                 /* Precalculate decoding info for each block in an MCU of this scan */
                 for (var blkn = 0; blkn < cinfo.m_blocks_in_MCU; blkn++)
                 {
                     var ci = cinfo.m_MCU_membership[blkn];
                     var componentInfo = cinfo.CompInfo[cinfo.m_cur_comp_info[ci]];
                     /* Precalculate which table to use for each block */
                     dcCurTables[blkn] = dcDerivedTables[componentInfo.Dc_tbl_no];
                     acCurTables[blkn] = acDerivedTables[componentInfo.Ac_tbl_no];
                     /* Decide whether we really care about the coefficient values */
                     if (componentInfo.component_needed)
                     {
                         ci = componentInfo.DCT_v_scaled_size;
                         var i = componentInfo.DCT_h_scaled_size;
                         switch (cinfo.lim_Se)
{
                             case 0:
                             coefLimit[blkn] = 1;
                             break;
                             case 3:
                             if (ci <= 0 || ci > 2)
{
                                 ci = 2;
                             }
                             if (i <= 0 || i > 2)
{
                                 i = 2;
                             }
                             coefLimit[blkn] = 1 + jpeg_zigzag_order2[ci - 1][i - 1];
                             break;
                             case 8:
                             if (ci <= 0 || ci > 3)
{
                                 ci = 3;
                             }
                             if (i <= 0 || i > 3)
{
                                 i = 3;
                             }
                             coefLimit[blkn] = 1 + jpeg_zigzag_order3[ci - 1][i - 1];
                             break;
                             case 15:
                             if (ci <= 0 || ci > 4)
{
                                 ci = 4;
                             }
                             if (i <= 0 || i > 4)
{
                                 i = 4;
                             }
                             coefLimit[blkn] = 1 + jpeg_zigzag_order4[ci - 1][i - 1];
                             break;
                             case 24:
                             if (ci <= 0 || ci > 5)
{
                                 ci = 5;
                             }
                             if (i <= 0 || i > 5)
{
                                 i = 5;
                             }
                             coefLimit[blkn] = 1 + jpeg_zigzag_order5[ci - 1][i - 1];
                             break;
                             case 35:
                             if (ci <= 0 || ci > 6)
{
                                 ci = 6;
                             }
                             if (i <= 0 || i > 6)
{
                                 i = 6;
                             }
                             coefLimit[blkn] = 1 + jpeg_zigzag_order6[ci - 1][i - 1];
                             break;
                             case 48:
                             if (ci <= 0 || ci > 7)
{
                                 ci = 7;
                             }
                             if (i <= 0 || i > 7)
{
                                 i = 7;
                             }
                             coefLimit[blkn] = 1 + jpeg_zigzag_order7[ci - 1][i - 1];
                             break;
                             default:
                             if (ci <= 0 || ci > 8)
{
                                 ci = 8;
                             }
                             if (i <= 0 || i > 8)
{
                                 i = 8;
                             }
                             coefLimit[blkn] = 1 + jpeg_zigzag_order[ci - 1][i - 1];
                             break;
                         }
                     }
                     else
                     {
                         coefLimit[blkn] = 0;
                     }
                 }
                 /* Initialize bitread state variables */
                 bitState.bitsLeft = 0;
                 bitState.getBuffer = 0;
                 insufficientData = false;
                 /* Initialize restart counter */
                 restartsToGo = cinfo.m_restart_interval;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acCurTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acDerivedTable, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acDerivedTables, BitMiracle.LibJpeg.Classic.Internal.BitreadPermState.bitsLeft, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.coefBits, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.coefLimit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_index, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.dcCurTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.dcDerivedTables, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.JpegEntropyDecoder.decodeMcu, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DerivedTables, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.EOBRUN, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.BitreadPermState.getBuffer, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.isBaseline, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order2, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order3, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order4, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order5, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order6, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order7, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.SavableState.last_dc_val, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.lim_Se, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Al, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_blocks_in_MCU, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_MCU_membership, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.progressiveMode, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo, BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Member Data Documentation
acCurTables
readonly DDerivedTable [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acCurTables = new DDerivedTable[JpegConstants.D_MAX_BLOCKS_IN_MCU] private
Definition at line 169 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
acDerivedTable
DDerivedTable BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acDerivedTable private
Definition at line 157 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
acDerivedTables
readonly DDerivedTable [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.acDerivedTables = new DDerivedTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 163 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
BIT_BUF_SIZE
const int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BIT_BUF_SIZE = 32 private
Definition at line 41 of file HuffmanEntropyDecoder.cs.
bitState
BitreadPermState BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bitState private
Definition at line 145 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.FinishPassHuffman(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
bmask
readonly int [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.bmask static private
Initial value:
=
        {
            0, 0x0001, 0x0003, 0x0007, 0x000F, 0x001F, 0x003F, 0x007F, 0x00FF,
            0x01FF, 0x03FF, 0x07FF, 0x0FFF, 0x1FFF, 0x3FFF, 0x7FFF
        }
Definition at line 61 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.GET_BITS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HUFF_EXTEND(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.PEEK_BITS().
cinfo
readonly JpegDecompressStruct BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.cinfo private
Definition at line 174 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.BITREAD_LOAD_STATE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
coefLimit
readonly int [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.coefLimit = new int[JpegConstants.D_MAX_BLOCKS_IN_MCU] private
Definition at line 172 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
dcCurTables
readonly DDerivedTable [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.dcCurTables = new DDerivedTable[JpegConstants.D_MAX_BLOCKS_IN_MCU] private
Definition at line 168 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
dcDerivedTables
readonly DDerivedTable [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.dcDerivedTables = new DDerivedTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 162 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
DerivedTables
readonly DDerivedTable [] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DerivedTables = new DDerivedTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 155 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
insufficientData
bool BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.insufficientData private
Definition at line 149 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
jpeg_zigzag_order
readonly int [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order static private
Initial value:
=
        {
            new int[] {  0,  1,  5,  6, 14, 15, 27, 28 },
            new int[] {  2,  4,  7, 13, 16, 26, 29, 42 },
            new int[] {  3,  8, 12, 17, 25, 30, 41, 43 },
            new int[] {  9, 11, 18, 24, 31, 40, 44, 53 },
            new int[] { 10, 19, 23, 32, 39, 45, 52, 54 },
            new int[] { 20, 22, 33, 38, 46, 51, 55, 60 },
            new int[] { 21, 34, 37, 47, 50, 56, 59, 61 },
            new int[] { 35, 36, 48, 49, 57, 58, 62, 63 }
        }
Definition at line 67 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
jpeg_zigzag_order2
readonly int [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order2 static private
Initial value:
=
        {
            new int[] { 0, 1 },
            new int[] { 2, 3 }
        }
Definition at line 124 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
jpeg_zigzag_order3
readonly int [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order3 static private
Initial value:
=
        {
            new int[] { 0, 1, 5 },
            new int[] { 2, 4, 6 },
            new int[] { 3, 7, 8 }
        }
Definition at line 117 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
jpeg_zigzag_order4
readonly int [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order4 static private
Initial value:
=
        {
            new int[] { 0,  1,  5,  6 },
            new int[] { 2,  4,  7, 12 },
            new int[] { 3,  8, 11, 13 },
            new int[] { 9, 10, 14, 15 }
        }
Definition at line 109 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
jpeg_zigzag_order5
readonly int [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order5 static private
Initial value:
=
        {
            new int[] {  0,  1,  5,  6, 14 },
            new int[] {  2,  4,  7, 13, 15 },
            new int[] {  3,  8, 12, 16, 21 },
            new int[] {  9, 11, 17, 20, 22 },
            new int[] { 10, 18, 19, 23, 24 }
        }
Definition at line 100 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
jpeg_zigzag_order6
readonly int [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order6 static private
Initial value:
=
        {
            new int[] {  0,  1,  5,  6, 14, 15 },
            new int[] {  2,  4,  7, 13, 16, 25 },
            new int[] {  3,  8, 12, 17, 24, 26 },
            new int[] {  9, 11, 18, 23, 27, 32 },
            new int[] { 10, 19, 22, 28, 31, 33 },
            new int[] { 20, 21, 29, 30, 34, 35 }
        }
Definition at line 90 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
jpeg_zigzag_order7
readonly int [][] BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.jpeg_zigzag_order7 static private
Initial value:
=
        {
            new int[] {  0,  1,  5,  6, 14, 15, 27 },
            new int[] {  2,  4,  7, 13, 16, 26, 28 },
            new int[] {  3,  8, 12, 17, 25, 29, 38 },
            new int[] {  9, 11, 18, 24, 30, 37, 39 },
            new int[] { 10, 19, 23, 31, 36, 40, 45 },
            new int[] { 20, 22, 32, 35, 41, 44, 46 },
            new int[] { 21, 33, 34, 42, 43, 47, 48 }
        }
Definition at line 79 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
MIN_GET_BITS
const int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.MIN_GET_BITS = BIT_BUF_SIZE - 7 private
Definition at line 56 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegFillBitBuffer().
restartsToGo
int BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.restartsToGo private
Definition at line 150 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
saved
readonly SavableState BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.saved = new SavableState() private
Definition at line 146 of file HuffmanEntropyDecoder.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuFull(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuSub(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.ProcessRestart(), and BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
Property Documentation
decodeMcu
DecodeMcuDelegate BitMiracle.LibJpeg.Classic.Internal.JpegEntropyDecoder.decodeMcu get set inherited
Definition at line 11 of file JpegEntropyDecoder.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass().
finishPass
FinishPassDelegate BitMiracle.LibJpeg.Classic.Internal.JpegEntropyDecoder.finishPass get set inherited
Definition at line 12 of file JpegEntropyDecoder.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.HuffmanEntropyDecoder().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/HuffmanEntropyDecoder.cs