Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter Class Reference
Marker writing
Public Member Functions
JpegMarkerWriter (JpegCompressStruct cinfo)
void WriteFileHeader ()
Write datastream header. This consists of an SOI and optional APPn markers. We recommend use of the JFIF marker, but not the Adobe marker, when using YCbCr or grayscale data. The JFIF marker is also used for other standard JPEG colorspaces. The Adobe marker is helpful to distinguish RGB, CMYK, and YCCK colorspaces. Note that an application can write additional header markers after jpeg_start_compress returns.
void WriteFrameHeader ()
Write frame header. This consists of DQT and SOFn markers, a conditional LSE marker and a conditional pseudo SOS marker. Note that we do not emit the SOF until we have emitted the DQT(s). This avoids compatibility problems with incorrect implementations that try to error-check the quant table numbers as soon as they see the SOF.
void WriteScanHeader ()
Write scan header. This consists of DHT or DAC markers, optional DRI, and SOS. Compressed data will be written following the SOS.
void WriteFileTrailer ()
Write datastream trailer.
void WriteTablesOnly ()
Write an abbreviated table-specification datastream. This consists of SOI, DQT and DHT tables, and EOI. Any table that is defined and not marked sent_table = true will be emitted. Note that all tables will be marked sent_table = true at exit.
void WriteMarkerHeader (int marker, int datalen)
Emit an arbitrary marker header
void WriteMarkerByte (byte val)
Emit one byte of marker parameters following write_marker_header
Private Member Functions
void EmitSOS ()
Emit a SOS marker
void EmitLseIct ()
Emit an LSE inverse color transform specification marker
void EmitSOF (JpegMarker code)
Emit a SOF marker
void EmitAdobeApp14 ()
Emit an Adobe APP14 marker
void EmitDRI ()
Emit a DRI marker
void EmitDHT (int index, bool is_ac)
Emit a DHT marker
int EmitDQT (int index)
Emit a DQT marker
void EmitDAC ()
void EmitPseudoSOS ()
Emit a pseudo SOS marker
void EmitJfifApp0 ()
Emit a JFIF-compliant APP0 marker
void EmitMarker (JpegMarker mark)
Emit a marker code
void Emit2Bytes (int value)
Emit a 2-byte integer; these are always MSB first in JPEG files
void EmitByte (int val)
Emit a byte
Private Attributes
readonly JpegCompressStruct m_cinfo
int m_last_restart_interval
Detailed Description
Marker writing
Definition at line 10 of file JpegMarkerWriter.cs.
Constructor & Destructor Documentation
JpegMarkerWriter()
BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.JpegMarkerWriter (JpegCompressStruct cinfo) inline
Definition at line 15 of file JpegMarkerWriter.cs.
         {
             m_cinfo = cinfo;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo.
Member Function Documentation
Emit2Bytes()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes (int value) inline private
Emit a 2-byte integer; these are always MSB first in JPEG files
Definition at line 641 of file JpegMarkerWriter.cs.
         {
             EmitByte((value >> 8) & 0xFF);
             EmitByte(value & 0xFF);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitAdobeApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitPseudoSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader().
EmitAdobeApp14()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitAdobeApp14 () inline private
Emit an Adobe APP14 marker
Definition at line 363 of file JpegMarkerWriter.cs.
         {
             /*
              * Length of APP14 block    (2 bytes)
              * Block ID         (5 bytes - ASCII "Adobe")
              * Version Number       (2 bytes - currently 100)
              * Flags0           (2 bytes - currently 0)
              * Flags1           (2 bytes - currently 0)
              * Color transform      (1 byte)
              *
              * Although Adobe TN 5116 mentions Version = 101, all the Adobe files
              * now in circulation seem to use Version = 100, so that's what we write.
              *
              * We write the color transform byte as 1 if the JPEG color space is
              * YCbCr, 2 if it's YCCK, 0 otherwise.  Adobe's definition has to do with
              * whether the encoder performed a transformation, which is pretty useless.
              */
             EmitMarker(JpegMarker.APP14);
             Emit2Bytes(2 + 5 + 2 + 2 + 2 + 1); /* length */
             EmitByte(0x41); /* Identifier: ASCII "Adobe" */
             EmitByte(0x64);
             EmitByte(0x6F);
             EmitByte(0x62);
             EmitByte(0x65);
             Emit2Bytes(100);    /* Version */
             Emit2Bytes(0);  /* Flags0 */
             Emit2Bytes(0);  /* Flags1 */
             switch (m_cinfo.m_jpeg_color_space)
             {
                 case JColorSpace.JCS_YCbCr:
                 EmitByte(1);    /* Color transform = 1 */
                 break;
                 case JColorSpace.JCS_YCCK:
                 EmitByte(2);    /* Color transform = 2 */
                 break;
                 default:
                 EmitByte(0);    /* Color transform = 0 */
                 break;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_jpeg_color_space.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader().
EmitByte()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte (int val) inline private
Emit a byte
Definition at line 650 of file JpegMarkerWriter.cs.
         {
             if (!m_cinfo.m_dest.EmitByte(val))
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_CANT_SUSPEND);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegDestinationManager.EmitByte(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitAdobeApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitPseudoSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerByte().
EmitDAC()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC () inline private
Definition at line 517 of file JpegMarkerWriter.cs.
         {
             var dc_in_use = new byte[JpegConstants.NUM_ARITH_TBLS];
             var ac_in_use = new byte[JpegConstants.NUM_ARITH_TBLS];
             for (var i = 0; i < m_cinfo.m_comps_in_scan; i++)
             {
                 var compptr = m_cinfo.Component_info[m_cinfo.m_cur_comp_info[i]];
                 /* DC needs no table for refinement scan */
                 if (m_cinfo.m_Ss == 0 && m_cinfo.m_Ah == 0)
                 {
                     dc_in_use[compptr.Dc_tbl_no] = 1;
                 }
                 /* AC needs no table when not present */
                 if (m_cinfo.m_Se != 0)
                 {
                     ac_in_use[compptr.Ac_tbl_no] = 1;
                 }
             }
             var length = 0;
             for (var i = 0; i < JpegConstants.NUM_ARITH_TBLS; i++)
             {
                 length += dc_in_use[i] + ac_in_use[i];
             }
             if (length != 0)
             {
                 EmitMarker(JpegMarker.DAC);
                 Emit2Bytes((length * 2) + 2);
                 for (var i = 0; i < JpegConstants.NUM_ARITH_TBLS; i++)
                 {
                     if (dc_in_use[i] != 0)
                     {
                         EmitByte(i);
                         EmitByte(m_cinfo.arith_dc_L[i] + (m_cinfo.arith_dc_U[i] << 4));
                     }
                     if (ac_in_use[i] != 0)
                     {
                         EmitByte(i + 0x10);
                         EmitByte(m_cinfo.arith_ac_K[i]);
                     }
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_ac_K, BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_dc_L, BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_dc_U, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss, and BitMiracle.LibJpeg.Classic.JpegConstants.NUM_ARITH_TBLS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
EmitDHT()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT (int index, bool is_ac) inline private
Emit a DHT marker
Definition at line 422 of file JpegMarkerWriter.cs.
         {
             var htbl = m_cinfo.m_dc_huff_tbl_ptrs[index];
             if (is_ac)
             {
                 htbl = m_cinfo.m_ac_huff_tbl_ptrs[index];
                 index += 0x10; /* output index has AC bit set */
             }
             if (htbl is null)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_NO_HUFF_TABLE, index);
             }
             if (!htbl.SentTable)
             {
                 EmitMarker(JpegMarker.DHT);
                 var length = 0;
                 for (var i = 1; i <= 16; i++)
                 {
                     length += htbl.Bits[i];
                 }
                 Emit2Bytes(length + 2 + 1 + 16);
                 EmitByte(index);
                 for (var i = 1; i <= 16; i++)
                 {
                     EmitByte(htbl.Bits[i]);
                 }
                 for (var i = 0; i < length; i++)
                 {
                     EmitByte(htbl.Huffval[i]);
                 }
                 htbl.SentTable = true;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
EmitDQT()
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT (int index) inline private
Emit a DQT marker
Parameters
index The index.
Returns
the precision used (0 = 8bits, 1 = 16bits) for baseline checking
Definition at line 468 of file JpegMarkerWriter.cs.
         {
             var qtbl = m_cinfo.m_quant_tbl_ptrs[index];
             if (qtbl is null)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_NO_QUANT_TABLE, index);
             }
             var prec = 0;
             for (var i = 0; i <= m_cinfo.lim_Se; i++)
             {
                 if (qtbl.quantBal[m_cinfo.natural_order[i]] > 255)
                 {
                     prec = 1;
                 }
             }
             if (!qtbl.SentTable)
             {
                 EmitMarker(JpegMarker.DQT);
                 Emit2Bytes((prec != 0)
                     ? (m_cinfo.lim_Se * 2) + 2 + 1 + 2
                     : m_cinfo.lim_Se + 1 + 1 + 2);
                 EmitByte(index + (prec << 4));
                 for (var i = 0; i <= m_cinfo.lim_Se; i++)
                 {
                     /* The table entries must be emitted in zigzag order. */
                     int qval = qtbl.quantBal[m_cinfo.natural_order[i]];
                     if (prec != 0)
                     {
                         EmitByte(qval >> 8);
                     }
                     EmitByte(qval & 0xFF);
                 }
                 qtbl.SentTable = true;
             }
             return prec;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.lim_Se, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
EmitDRI()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDRI () inline private
Emit a DRI marker
Definition at line 410 of file JpegMarkerWriter.cs.
         {
             EmitMarker(JpegMarker.DRI);
             Emit2Bytes(4);  /* fixed length */
             Emit2Bytes(m_cinfo.m_restart_interval);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
EmitJfifApp0()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0 () inline private
Emit a JFIF-compliant APP0 marker
Definition at line 586 of file JpegMarkerWriter.cs.
         {
             /*
              * Length of APP0 block (2 bytes)
              * Block ID         (4 bytes - ASCII "JFIF")
              * Zero byte            (1 byte to terminate the ID string)
              * Version Major, Minor (2 bytes - major first)
              * Units            (1 byte - 0x00 = none, 0x01 = inch, 0x02 = cm)
              * Xdpu         (2 bytes - dots per unit horizontal)
              * Ydpu         (2 bytes - dots per unit vertical)
              * Thumbnail X size     (1 byte)
              * Thumbnail Y size     (1 byte)
              */
             EmitMarker(JpegMarker.APP0);
             Emit2Bytes(2 + 4 + 1 + 2 + 1 + 2 + 2 + 1 + 1); /* length */
             EmitByte(0x4A); /* Identifier: ASCII "JFIF" */
             EmitByte(0x46);
             EmitByte(0x49);
             EmitByte(0x46);
             EmitByte(0);
             EmitByte(m_cinfo.m_JFIF_major_version); /* Version fields */
             EmitByte(m_cinfo.m_JFIF_minor_version);
             EmitByte((int)m_cinfo.m_density_unit); /* Pixel size information */
             Emit2Bytes(m_cinfo.m_X_density);
             Emit2Bytes(m_cinfo.m_Y_density);
             EmitByte(0);        /* No thumbnail image */
             EmitByte(0);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_density_unit, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_major_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_minor_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_X_density, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Y_density.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader().
EmitLseIct()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct () inline private
Emit an LSE inverse color transform specification marker
Definition at line 301 of file JpegMarkerWriter.cs.
         {
             /* Support only 1 transform */
             if (m_cinfo.ColorTransform != JColorTransform.JCT_SUBTRACT_GREEN || m_cinfo.Num_components < 3)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             EmitMarker(JpegMarker.JPG8);
             Emit2Bytes(24); /* fixed length */
             EmitByte(0x0D); /* ID inverse transform specification */
             Emit2Bytes(JpegConstants.MAXJSAMPLE); /* MAXTRANS */
             EmitByte(3);        /* Nt=3 */
             EmitByte(m_cinfo.Component_info[1].Component_id);
             EmitByte(m_cinfo.Component_info[0].Component_id);
             EmitByte(m_cinfo.Component_info[2].Component_id);
             EmitByte(0x80); /* F1: CENTER1=1, NORM1=0 */
             Emit2Bytes(0);  /* A(1,1)=0 */
             Emit2Bytes(0);  /* A(1,2)=0 */
             EmitByte(0);    /* F2: CENTER2=0, NORM2=0 */
             Emit2Bytes(1);  /* A(2,1)=1 */
             Emit2Bytes(0);  /* A(2,2)=0 */
             EmitByte(0);    /* F3: CENTER3=0, NORM3=0 */
             Emit2Bytes(1);  /* A(3,1)=1 */
             Emit2Bytes(0);  /* A(3,2)=0 */
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.ColorTransform, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_id, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.Num_components.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
EmitMarker()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker (JpegMarker mark) inline private
Emit a marker code
Definition at line 632 of file JpegMarkerWriter.cs.
         {
             EmitByte(0xFF);
             EmitByte((int)mark);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitAdobeApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitPseudoSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileTrailer(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
EmitPseudoSOS()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitPseudoSOS () inline private
Emit a pseudo SOS marker
Definition at line 570 of file JpegMarkerWriter.cs.
         {
             EmitMarker(JpegMarker.SOS);
             Emit2Bytes(2 + 1 + 3); /* length */
             EmitByte(0); /* Ns */
             EmitByte(0); /* Ss */
             EmitByte((m_cinfo.BlockSize * m_cinfo.BlockSize) - 1); /* Se */
             EmitByte(0); /* Ah/Al */
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
EmitSOF()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF (JpegMarker code) inline private
Emit a SOF marker
Definition at line 333 of file JpegMarkerWriter.cs.
         {
             EmitMarker(code);
             Emit2Bytes((3 * m_cinfo.m_num_components) + 2 + 5 + 1); /* length */
             /* Make sure image isn't bigger than SOF field can handle */
             if (m_cinfo.jpeg_height > 65535 || m_cinfo.jpeg_width > 65535)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_IMAGE_TOO_BIG, 65535);
             }
             EmitByte(m_cinfo.m_data_precision);
             Emit2Bytes(m_cinfo.jpeg_height);
             Emit2Bytes(m_cinfo.jpeg_width);
             EmitByte(m_cinfo.m_num_components);
             for (var ci = 0; ci < m_cinfo.m_num_components; ci++)
             {
                 var componentInfo = m_cinfo.Component_info[ci];
                 EmitByte(componentInfo.Component_id);
                 EmitByte((componentInfo.H_samp_factor << 4) + componentInfo.V_samp_factor);
                 EmitByte(componentInfo.Quant_tbl_no);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_width, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_data_precision, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
EmitSOS()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS () inline private
Emit a SOS marker
Definition at line 266 of file JpegMarkerWriter.cs.
         {
             EmitMarker(JpegMarker.SOS);
             Emit2Bytes((2 * m_cinfo.m_comps_in_scan) + 2 + 1 + 3); /* length */
             EmitByte(m_cinfo.m_comps_in_scan);
             for (var i = 0; i < m_cinfo.m_comps_in_scan; i++)
             {
                 var componentIndex = m_cinfo.m_cur_comp_info[i];
                 var compptr = m_cinfo.Component_info[componentIndex];
                 EmitByte(compptr.Component_id);
                 /* We emit 0 for unused field(s); this is recommended by the P&M text
                  * but does not seem to be specified in the standard.
                  */
                 /* DC needs no table for refinement scan */
                 var td = (m_cinfo.m_Ss == 0 && m_cinfo.m_Ah == 0) ? compptr.Dc_tbl_no : 0;
                 /* AC needs no table when not present */
                 var ta = (m_cinfo.m_Se != 0) ? compptr.Ac_tbl_no : 0;
                 EmitByte((td << 4) + ta);
             }
             EmitByte(m_cinfo.m_Ss);
             EmitByte(m_cinfo.m_Se);
             EmitByte((m_cinfo.m_Ah << 4) + m_cinfo.m_Al);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Al, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
WriteFileHeader()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader () inline
Write datastream header. This consists of an SOI and optional APPn markers. We recommend use of the JFIF marker, but not the Adobe marker, when using YCbCr or grayscale data. The JFIF marker is also used for other standard JPEG colorspaces. The Adobe marker is helpful to distinguish RGB, CMYK, and YCCK colorspaces. Note that an application can write additional header markers after jpeg_start_compress returns.
Definition at line 30 of file JpegMarkerWriter.cs.
         {
             EmitMarker(JpegMarker.SOI);  /* first the SOI */
             /* SOI is defined to reset restart interval to 0 */
             m_last_restart_interval = 0;
             if (m_cinfo.m_write_JFIF_header)   /* next an optional JFIF APP0 */
             {
                 EmitJfifApp0();
             }
             if (m_cinfo.m_write_Adobe_marker) /* next an optional Adobe APP14 */
             {
                 EmitAdobeApp14();
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitAdobeApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_last_restart_interval, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_write_Adobe_marker, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_write_JFIF_header.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection().
WriteFileTrailer()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileTrailer () inline
Write datastream trailer.
Definition at line 190 of file JpegMarkerWriter.cs.
         {
             EmitMarker(JpegMarker.EOI);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker().
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress().
WriteFrameHeader()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader () inline
Write frame header. This consists of DQT and SOFn markers, a conditional LSE marker and a conditional pseudo SOS marker. Note that we do not emit the SOF until we have emitted the DQT(s). This avoids compatibility problems with incorrect implementations that try to error-check the quant table numbers as soon as they see the SOF.
Definition at line 56 of file JpegMarkerWriter.cs.
         {
             /* Emit DQT for each quantization table.
              * Note that emit_dqt() suppresses any duplicate tables.
              */
             var prec = 0;
             for (var ci = 0; ci < m_cinfo.m_num_components; ci++)
             {
                 prec += EmitDQT(m_cinfo.Component_info[ci].Quant_tbl_no);
             }
             /* now prec is nonzero iff there are any 16-bit quant tables. */
             /* Check for a non-baseline specification.
              * Note we assume that Huffman table numbers won't be changed later.
              */
             bool is_baseline;
             if (m_cinfo.arith_code
                 || m_cinfo.m_progressive_mode
                 || m_cinfo.m_data_precision != 8
                 || m_cinfo.BlockSize != JpegConstants.DCTSIZE)
             {
                 is_baseline = false;
             }
             else
             {
                 is_baseline = true;
                 for (var ci = 0; ci < m_cinfo.m_num_components; ci++)
                 {
                     if (m_cinfo.Component_info[ci].Dc_tbl_no > 1 || m_cinfo.Component_info[ci].Ac_tbl_no > 1)
                     {
                         is_baseline = false;
                     }
                 }
                 if (prec != 0 && is_baseline)
                 {
                     is_baseline = false;
                     /* If it's baseline except for quantizer size, warn the user */
                     m_cinfo.TraceMS(0, JMessageCode.JTRC_16BIT_TABLES);
                 }
             }
             /* Emit the proper SOF marker */
             if (m_cinfo.arith_code)
             {
                 if (m_cinfo.m_progressive_mode)
                 {
                     EmitSOF(JpegMarker.SOF10); /* SOF code for progressive arithmetic */
                 }
                 else
                 {
                     EmitSOF(JpegMarker.SOF9);  /* SOF code for sequential arithmetic */
                 }
             }
             else if (m_cinfo.m_progressive_mode)
             {
                 EmitSOF(JpegMarker.SOF2);    /* SOF code for progressive Huffman */
             }
             else if (is_baseline)
             {
                 EmitSOF(JpegMarker.SOF0);    /* SOF code for baseline implementation */
             }
             else
             {
                 EmitSOF(JpegMarker.SOF1);    /* SOF code for non-baseline Huffman file */
             }
             /* Check to emit LSE inverse color transform specification marker */
             if (m_cinfo.ColorTransform != JColorTransform.JCT_NONE)
             {
                 EmitLseIct();
             }
             /* Check to emit pseudo SOS marker */
             if (m_cinfo.m_progressive_mode && m_cinfo.BlockSize != JpegConstants.DCTSIZE)
             {
                 EmitPseudoSOS();
             }
         }
References BitMiracle.LibJpeg.Classic.JpegComponentInfo.Ac_tbl_no, BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_code, BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegCompressStruct.ColorTransform, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitPseudoSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_data_precision, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Quant_tbl_no, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
WriteMarkerByte()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerByte (byte val) inline
Emit one byte of marker parameters following write_marker_header
Definition at line 254 of file JpegMarkerWriter.cs.
         {
             EmitByte(val);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte().
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMByte().
WriteMarkerHeader()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader (int marker, int datalen) inline
Emit an arbitrary marker header
Definition at line 239 of file JpegMarkerWriter.cs.
         {
             if (datalen > 65533)     /* safety check */
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             EmitMarker((JpegMarker)marker);
             Emit2Bytes(datalen + 2);    /* total length */
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.Emit2Bytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader().
WriteScanHeader()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader () inline
Write scan header. This consists of DHT or DAC markers, optional DRI, and SOS. Compressed data will be written following the SOS.
Definition at line 142 of file JpegMarkerWriter.cs.
         {
             if (m_cinfo.arith_code)
             {
                 /* Emit arith conditioning info.  We may have some duplication
                  * if the file has multiple scans, but it's so small it's hardly
                  * worth worrying about.
                  */
                 EmitDAC();
             }
             else
             {
                 /* Emit Huffman tables.
                  * Note that emit_dht() suppresses any duplicate tables.
                  */
                 for (var i = 0; i < m_cinfo.m_comps_in_scan; i++)
                 {
                     var compptr = m_cinfo.Component_info[m_cinfo.m_cur_comp_info[i]];
                     /* DC needs no table for refinement scan */
                     if (m_cinfo.m_Ss == 0 && m_cinfo.m_Ah == 0)
                     {
                         EmitDHT(compptr.Dc_tbl_no, false);
                     }
                     /* AC needs no table when not present */
                     if (m_cinfo.m_Se != 0)
                     {
                         EmitDHT(compptr.Ac_tbl_no, true);
                     }
                 }
                 /* Emit DRI if required --- note that DRI value could change for each scan.
                  * We avoid wasting space with unnecessary DRIs, however.
                  */
                 if (m_cinfo.m_restart_interval != m_last_restart_interval)
                 {
                     EmitDRI();
                     m_last_restart_interval = m_cinfo.m_restart_interval;
                 }
                 EmitSOS();
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_code, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_last_restart_interval, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss.
WriteTablesOnly()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly () inline
Write an abbreviated table-specification datastream. This consists of SOI, DQT and DHT tables, and EOI. Any table that is defined and not marked sent_table = true will be emitted. Note that all tables will be marked sent_table = true at exit.
Definition at line 201 of file JpegMarkerWriter.cs.
         {
             EmitMarker(JpegMarker.SOI);
             for (var i = 0; i < JpegConstants.NUM_QUANT_TBLS; i++)
             {
                 if (m_cinfo.m_quant_tbl_ptrs[i] is object)
                 {
                     EmitDQT(i);
                 }
             }
             for (var i = 0; i < JpegConstants.NUM_HUFF_TBLS; i++)
             {
                 if (m_cinfo.m_dc_huff_tbl_ptrs[i] is object)
                 {
                     EmitDHT(i, false);
                 }
                 if (m_cinfo.m_ac_huff_tbl_ptrs[i] is object)
                 {
                     EmitDHT(i, true);
                 }
             }
             EmitMarker(JpegMarker.EOI);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS, and BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables().
Member Data Documentation
m_cinfo
readonly JpegCompressStruct BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_cinfo private
Definition at line 12 of file JpegMarkerWriter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitAdobeApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitPseudoSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.JpegMarkerWriter(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
m_last_restart_interval
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.m_last_restart_interval private
Definition at line 13 of file JpegMarkerWriter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegMarkerWriter.cs