Juniper: Hjg.Pngcs.Chunks.ChunksListForWrite Class Reference
Hjg.Pngcs.Chunks.ChunksListForWrite Class Reference
Chunks written or queued to be written http://www.w3.org/TR/PNG/#table53
Public Member Functions
List< AbstractPngChunk > GetQueuedById (string id)
Same as getById(), but looking in the queued chunks
List< AbstractPngChunk > GetQueuedById (string id, string innerid)
Same as getById(), but looking in the queued chunks
AbstractPngChunk GetQueuedById1 (string id, string innerid, bool failIfMultiple)
Same as getById(), but looking in the queued chunks
AbstractPngChunk GetQueuedById1 (string id, bool failIfMultiple)
Same as getById1(), but looking in the queued chunks
AbstractPngChunk GetQueuedById1 (string id)
Same as getById1(), but looking in the queued chunks
bool RemoveChunk (AbstractPngChunk c)
Remove Chunk: only from queued
bool Queue (AbstractPngChunk chunk)
Adds chunk to queue
Dictionary< string, int > GetChunksKeys ()
Keys of processed (read or writen) chunks
void AppendReadChunk (AbstractPngChunk chunk, int chunkGroup)
Adds chunk in next position. This is used only by the pngReader
List< AbstractPngChunk > GetById (string id)
All chunks with this ID
List< AbstractPngChunk > GetById (string id, string innerid)
Same as ID, but we an additional discriminator for textual keys
AbstractPngChunk GetById1 (string id)
Returns only one chunk
AbstractPngChunk GetById1 (string id, bool failIfMultiple)
Returns only one chunk
AbstractPngChunk GetById1 (string id, string innerid, bool failIfMultiple)
Sames as GetById1(string id, bool failIfMultiple) but allows an additional innerid
List< AbstractPngChunk > GetEquivalent (AbstractPngChunk chunk)
Finds all chunks "equivalent" to this one
override string ToString ()
Only the amount of chunks
string ToStringFull ()
Detailed information, for debugging
Public Attributes
List< AbstractPngChunk > Chunks => new List<AbstractPngChunk>(PngChunks)
Returns a copy of the chunk list (but the chunks are not copied)
Properties
List< AbstractPngChunk > PngChunks [get]
Includes all chunks, but IDAT is a single pseudo chunk without data
Private Member Functions
internal ChunksListForWrite (ImageInfo info)
internal int WriteChunks (Stream os, int currentGroup)
internal List< AbstractPngChunk > GetQueuedChunks ()
chunks not yet writen - does not include IHDR, IDAT, END, perhaps yes PLTE
Static Private Member Functions
static bool ShouldWrite (AbstractPngChunk c, int currentGroup)
Private Attributes
readonly List< AbstractPngChunk > queuedChunks
readonly Dictionary< string, int > alreadyWrittenKeys
Detailed Description
Chunks written or queued to be written http://www.w3.org/TR/PNG/#table53
Definition at line 11 of file ChunksListForWrite.cs.
Constructor & Destructor Documentation
ChunksListForWrite()
internal Hjg.Pngcs.Chunks.ChunksListForWrite.ChunksListForWrite (ImageInfo info) inline private
Definition at line 18 of file ChunksListForWrite.cs.
             : base(info)
         {
             queuedChunks = new List<AbstractPngChunk>();
             alreadyWrittenKeys = new Dictionary<string, int>();
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.alreadyWrittenKeys, and Hjg.Pngcs.Chunks.ChunksListForWrite.queuedChunks.
Member Function Documentation
AppendReadChunk()
void Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk (AbstractPngChunk chunk, int chunkGroup) inline inherited
Adds chunk in next position. This is used only by the pngReader
Parameters
chunk
chunkGroup
Definition at line 76 of file ChunksList.cs.
         {
             if (chunk is null)
             {
                 throw new ArgumentNullException(nameof(chunk));
             }
             chunk.ChunkGroup = chunkGroup;
             PngChunks.Add(chunk);
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkGroup, and Hjg.Pngcs.Chunks.ChunksList.PngChunks.
Referenced by Hjg.Pngcs.PngReader.ReadChunk(), and Hjg.Pngcs.PngReader.ReadFirstChunks().
GetById() [1/2]
List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksList.GetById (string id) inline inherited
All chunks with this ID
The GetBy... methods never include queued chunks
Parameters
id
Returns
List, empty if none
Definition at line 93 of file ChunksList.cs.
         {
             return GetById(id, null);
         }
Referenced by Hjg.Pngcs.Chunks.ChunksList.GetById1(), and Hjg.Pngcs.Chunks.PngMetadata.GetTxtsForKey().
GetById() [2/2]
List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksList.GetById (string id, string innerid) inline inherited
Same as ID, but we an additional discriminator for textual keys
If innerid!=null and the chunk is PngChunkTextVar or PngChunkSPLT, it's filtered by that id
Parameters
id
innerid Only used for text and SPLT chunks
Returns
List, empty if none
Definition at line 105 of file ChunksList.cs.
         {
             return GetXById(PngChunks, id, innerid);
         }
References Hjg.Pngcs.Chunks.ChunksList.GetXById(), and Hjg.Pngcs.Chunks.ChunksList.PngChunks.
GetById1() [1/3]
AbstractPngChunk Hjg.Pngcs.Chunks.ChunksList.GetById1 (string id) inline inherited
Returns only one chunk
Parameters
id
Returns
First chunk found, null if not found
Definition at line 115 of file ChunksList.cs.
         {
             return GetById1(id, false);
         }
Referenced by Hjg.Pngcs.Chunks.ChunksList.GetById1(), Hjg.Pngcs.Chunks.PngMetadata.GetDpi(), Hjg.Pngcs.Chunks.PngMetadata.GetPLTE(), Hjg.Pngcs.Chunks.PngMetadata.GetTime(), and Hjg.Pngcs.Chunks.PngMetadata.GetTRNS().
GetById1() [2/3]
AbstractPngChunk Hjg.Pngcs.Chunks.ChunksList.GetById1 (string id, bool failIfMultiple) inline inherited
Returns only one chunk
Parameters
id
failIfMultiple true, and more than one found: exception
Returns
null if not found
Definition at line 126 of file ChunksList.cs.
         {
             return GetById1(id, null, failIfMultiple);
         }
References Hjg.Pngcs.Chunks.ChunksList.GetById1().
GetById1() [3/3]
AbstractPngChunk Hjg.Pngcs.Chunks.ChunksList.GetById1 (string id, string innerid, bool failIfMultiple) inline inherited
Sames as GetById1(string id, bool failIfMultiple) but allows an additional innerid
Parameters
id
innerid
failIfMultiple true, and more than one found: exception
Returns
null if not found
Definition at line 138 of file ChunksList.cs.
         {
             var list = GetById(id, innerid);
             if (list.Count == 0)
             {
                 return null;
             }
             if (list.Count > 1 && (failIfMultiple || !list[0].AllowsMultiple()))
             {
                 throw new PngjException("unexpected multiple chunks id=" + id);
             }
             return list[list.Count - 1];
         }
References Hjg.Pngcs.Chunks.ChunksList.GetById().
GetChunksKeys()
Dictionary<string, int> Hjg.Pngcs.Chunks.ChunksList.GetChunksKeys () inline inherited
Keys of processed (read or writen) chunks
Returns
key:chunk id, val: number of occurrences
Definition at line 40 of file ChunksList.cs.
         {
             var ck = new Dictionary<string, int>();
             foreach (var c in PngChunks)
             {
                 ck[c.Id] = ck.ContainsKey(c.Id) ? ck[c.Id] + 1 : 1;
             }
             return ck;
         }
References Hjg.Pngcs.Chunks.ChunksList.PngChunks.
GetEquivalent()
List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksList.GetEquivalent (AbstractPngChunk chunk) inline inherited
Finds all chunks "equivalent" to this one
Parameters
chunk
Returns
Empty if nothing found
Definition at line 159 of file ChunksList.cs.
         {
             return ChunkHelper.FilterList(PngChunks, new ChunkPredicateEquiv(chunk));
         }
References Hjg.Pngcs.Chunks.ChunkHelper.FilterList(), and Hjg.Pngcs.Chunks.ChunksList.PngChunks.
GetQueuedById() [1/2]
List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById (string id) inline
Same as getById(), but looking in the queued chunks
Parameters
id
Returns
Definition at line 30 of file ChunksListForWrite.cs.
         {
             return GetQueuedById(id, null);
         }
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById1().
GetQueuedById() [2/2]
List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById (string id, string innerid) inline
Same as getById(), but looking in the queued chunks
Parameters
id
innerid
Returns
Definition at line 41 of file ChunksListForWrite.cs.
         {
             return GetXById(queuedChunks, id, innerid);
         }
References Hjg.Pngcs.Chunks.ChunksList.GetXById(), and Hjg.Pngcs.Chunks.ChunksListForWrite.queuedChunks.
GetQueuedById1() [1/3]
AbstractPngChunk Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById1 (string id, string innerid, bool failIfMultiple) inline
Same as getById(), but looking in the queued chunks
Parameters
id
innerid
failIfMultiple
Returns
Definition at line 53 of file ChunksListForWrite.cs.
         {
             var list = GetQueuedById(id, innerid);
             if (list.Count == 0)
             {
                 return null;
             }
             if (list.Count > 1 && (failIfMultiple || !list[0].AllowsMultiple()))
             {
                 throw new PngjException("unexpected multiple chunks id=" + id);
             }
             return list[list.Count - 1];
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById().
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById1().
GetQueuedById1() [2/3]
AbstractPngChunk Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById1 (string id, bool failIfMultiple) inline
Same as getById1(), but looking in the queued chunks
Parameters
id
failIfMultiple
Returns
Definition at line 75 of file ChunksListForWrite.cs.
         {
             return GetQueuedById1(id, null, failIfMultiple);
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById1().
GetQueuedById1() [3/3]
AbstractPngChunk Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById1 (string id) inline
Same as getById1(), but looking in the queued chunks
Parameters
id
Returns
Definition at line 85 of file ChunksListForWrite.cs.
         {
             return GetQueuedById1(id, false);
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById1().
GetQueuedChunks()
internal List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedChunks () inline private
chunks not yet writen - does not include IHDR, IDAT, END, perhaps yes PLTE
Returns
THis is not a copy! Don't modify
Definition at line 216 of file ChunksListForWrite.cs.
         {
             return queuedChunks;
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.queuedChunks.
Referenced by Hjg.Pngcs.PngWriter.WriteLastChunks().
Queue()
bool Hjg.Pngcs.Chunks.ChunksListForWrite.Queue (AbstractPngChunk chunk) inline
Adds chunk to queue
Does not check for duplicated or anything
Parameters
chunk
Returns
Definition at line 110 of file ChunksListForWrite.cs.
         {
             queuedChunks.Add(chunk);
             return true;
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.queuedChunks.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks().
RemoveChunk()
bool Hjg.Pngcs.Chunks.ChunksListForWrite.RemoveChunk (AbstractPngChunk c) inline
Remove Chunk: only from queued
WARNING: this depends on chunk.Equals() implementation, which is straightforward for SingleChunks. For MultipleChunks, it will normally check for reference equality!
Parameters
c
Returns
Definition at line 99 of file ChunksListForWrite.cs.
         {
             return queuedChunks.Remove(c);
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.queuedChunks.
ShouldWrite()
static bool Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite (AbstractPngChunk c, int currentGroup) inline static private
this should be called only for ancillary chunks and PLTE (groups 1 - 3 - 5)
Definition at line 120 of file ChunksListForWrite.cs.
         {
             if (currentGroup == CHUNK_GROUP_2_PLTE)
             {
                 return c.Id.Equals(ChunkHelper.PLTE, System.StringComparison.Ordinal);
             }
             if (currentGroup % 2 == 0)
             {
                 throw new PngjOutputException("bad chunk group?");
             }
             int minChunkGroup;
             int maxChunkGroup;
             if (c.MustGoBeforePLTE())
             {
                 minChunkGroup = maxChunkGroup = ChunksList.CHUNK_GROUP_1_AFTERIDHR;
             }
             else if (c.MustGoBeforeIDAT())
             {
                 maxChunkGroup = ChunksList.CHUNK_GROUP_3_AFTERPLTE;
                 minChunkGroup = c.MustGoAfterPLTE() ? ChunksList.CHUNK_GROUP_3_AFTERPLTE
                         : ChunksList.CHUNK_GROUP_1_AFTERIDHR;
             }
             else
             {
                 maxChunkGroup = ChunksList.CHUNK_GROUP_5_AFTERIDAT;
                 minChunkGroup = ChunksList.CHUNK_GROUP_1_AFTERIDHR;
             }
             var preferred = maxChunkGroup;
             if (c.Priority)
             {
                 preferred = minChunkGroup;
             }
             if (ChunkHelper.IsUnknown(c) && c.ChunkGroup > 0)
             {
                 preferred = c.ChunkGroup;
             }
             if (currentGroup == preferred)
             {
                 return true;
             }
             if (currentGroup > preferred && currentGroup <= maxChunkGroup)
             {
                 return true;
             }
             return false;
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_1_AFTERIDHR, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_2_PLTE, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_3_AFTERPLTE, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_5_AFTERIDAT, Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkGroup, Hjg.Pngcs.Chunks.AbstractPngChunk.Id, Hjg.Pngcs.Chunks.ChunkHelper.IsUnknown(), Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoAfterPLTE(), Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforeIDAT(), Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforePLTE(), Hjg.Pngcs.Chunks.ChunkHelper.PLTE, and Hjg.Pngcs.Chunks.AbstractPngChunk.Priority.
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
ToString()
override string Hjg.Pngcs.Chunks.ChunksList.ToString () inline inherited
Only the amount of chunks
Returns
Definition at line 168 of file ChunksList.cs.
         {
             return "ChunkList: read: " + PngChunks.Count.ToString(CultureInfo.CurrentCulture);
         }
References Hjg.Pngcs.Chunks.ChunksList.PngChunks.
Referenced by Hjg.Pngcs.Chunks.ChunksList.ToStringFull().
ToStringFull()
string Hjg.Pngcs.Chunks.ChunksList.ToStringFull () inline inherited
Detailed information, for debugging
Returns
Definition at line 177 of file ChunksList.cs.
         {
             var sb = new StringBuilder(ToString());
             _ = sb.Append("\n Read:\n");
             foreach (var chunk in PngChunks)
             {
                 _ = sb.Append(chunk)
                   .Append(" G=")
                   .Append(chunk.ChunkGroup)
                   .Append('\n');
             }
             return sb.ToString();
         }
References Hjg.Pngcs.Chunks.ChunksList.PngChunks, and Hjg.Pngcs.Chunks.ChunksList.ToString().
WriteChunks()
internal int Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks (Stream os, int currentGroup) inline private
Definition at line 174 of file ChunksListForWrite.cs.
         {
             var written = new List<int>();
             for (var i = 0; i < queuedChunks.Count; i++)
             {
                 var c = queuedChunks[i];
                 if (!ShouldWrite(c, currentGroup))
                 {
                     continue;
                 }
                 if (ChunkHelper.IsCritical(c.Id)
                     && !c.Id.Equals(ChunkHelper.PLTE, System.StringComparison.Ordinal))
                 {
                     throw new PngjOutputException("bad chunk queued: " + c);
                 }
                 if (alreadyWrittenKeys.ContainsKey(c.Id) && !c.AllowsMultiple())
                 {
                     throw new PngjOutputException("duplicated chunk does not allow multiple: " + c);
                 }
                 c.Write(os);
                 PngChunks.Add(c);
                 alreadyWrittenKeys[c.Id] = alreadyWrittenKeys.ContainsKey(c.Id) ? alreadyWrittenKeys[c.Id] + 1 : 1;
                 written.Add(i);
                 c.ChunkGroup = currentGroup;
             }
             for (var k = written.Count - 1; k >= 0; k--)
             {
                 queuedChunks.RemoveAt(written[k]);
             }
             return written.Count;
         }
References Hjg.Pngcs.Chunks.ChunksListForWrite.alreadyWrittenKeys, Hjg.Pngcs.Chunks.ChunkHelper.IsCritical(), Hjg.Pngcs.Chunks.ChunkHelper.PLTE, Hjg.Pngcs.Chunks.ChunksList.PngChunks, Hjg.Pngcs.Chunks.ChunksListForWrite.queuedChunks, and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
Referenced by Hjg.Pngcs.PngWriter.WriteFirstChunks(), and Hjg.Pngcs.PngWriter.WriteLastChunks().
Member Data Documentation
alreadyWrittenKeys
readonly Dictionary<string, int> Hjg.Pngcs.Chunks.ChunksListForWrite.alreadyWrittenKeys private
Definition at line 16 of file ChunksListForWrite.cs.
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.ChunksListForWrite(), and Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
Chunks
List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksList.Chunks => new List<AbstractPngChunk>(PngChunks) inherited
Returns a copy of the chunk list (but the chunks are not copied)
This should not be used for general metadata handling
Returns
Definition at line 57 of file ChunksList.cs.
queuedChunks
readonly List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksListForWrite.queuedChunks private
Definition at line 13 of file ChunksListForWrite.cs.
Referenced by Hjg.Pngcs.Chunks.ChunksListForWrite.ChunksListForWrite(), Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedById(), Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedChunks(), Hjg.Pngcs.Chunks.ChunksListForWrite.Queue(), Hjg.Pngcs.Chunks.ChunksListForWrite.RemoveChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
Property Documentation
PngChunks
List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunksList.PngChunks get protected inherited
Includes all chunks, but IDAT is a single pseudo chunk without data
Definition at line 26 of file ChunksList.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), Hjg.Pngcs.Chunks.ChunksList.ChunksList(), Hjg.Pngcs.Chunks.ChunksList.GetById(), Hjg.Pngcs.Chunks.ChunksList.GetChunksKeys(), Hjg.Pngcs.Chunks.ChunksList.GetEquivalent(), Hjg.Pngcs.Chunks.ChunksList.ToString(), Hjg.Pngcs.Chunks.ChunksList.ToStringFull(), and Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Chunks/ChunksListForWrite.cs