Juniper: Juniper.Units.Days Class Reference
Juniper.Units.Days Class Reference
Conversions from days
Static Public Member Functions
static float Milliseconds (float days)
Convert from days to milliseconds.
static float Seconds (float days)
Convert from days to seconds.
static float Minutes (float days)
Convert from days to minutes.
static float Hours (float days)
Convert from days to hours.
static float Hertz (float days)
Convert from days to hertz.
Public Attributes
const float PER_MILLISECOND = 1 / Units.Milliseconds.PER_DAY
Conversion factor from milliseconds to days.
const float PER_SECOND = 1 / Units.Seconds.PER_DAY
Conversion factor from seconds to days.
const float PER_MINUTE = 1 / Units.Minutes.PER_DAY
Conversion factor from minutes to days.
const float PER_HOUR = 1 / Units.Hours.PER_DAY
Conversion factor from hours to days.
Detailed Description
Conversions from days
Definition at line 8 of file Days.cs.
Member Function Documentation
Hertz()
static float Juniper.Units.Days.Hertz (float days) inline static
Convert from days to hertz.
Parameters
days The number of days
Returns
The number of hertz
Definition at line 75 of file Days.cs.
             {
                 return Units.Seconds.Hertz(Seconds(days));
             }
References Juniper.Units.Seconds.Hertz(), and Juniper.Units.Days.Seconds().
Hours()
static float Juniper.Units.Days.Hours (float days) inline static
Convert from days to hours.
Parameters
days The number of days
Returns
The number of hours
Definition at line 65 of file Days.cs.
             {
                 return days * Units.Hours.PER_DAY;
             }
References Juniper.Units.Hours.PER_DAY.
Milliseconds()
static float Juniper.Units.Days.Milliseconds (float days) inline static
Convert from days to milliseconds.
Parameters
days The number of days
Returns
The number of milliseconds
Definition at line 35 of file Days.cs.
             {
                 return days * Units.Milliseconds.PER_DAY;
             }
References Juniper.Units.Milliseconds.PER_DAY.
Minutes()
static float Juniper.Units.Days.Minutes (float days) inline static
Convert from days to minutes.
Parameters
days The number of days
Returns
The number of minutes
Definition at line 55 of file Days.cs.
             {
                 return days * Units.Minutes.PER_DAY;
             }
References Juniper.Units.Minutes.PER_DAY.
Seconds()
static float Juniper.Units.Days.Seconds (float days) inline static
Convert from days to seconds.
Parameters
days The number of days
Returns
The number of seconds
Definition at line 45 of file Days.cs.
             {
                 return days * Units.Seconds.PER_DAY;
             }
References Juniper.Units.Seconds.PER_DAY.
Referenced by Juniper.Units.Hertz.Days(), and Juniper.Units.Days.Hertz().
Member Data Documentation
PER_HOUR
const float Juniper.Units.Days.PER_HOUR = 1 / Units.Hours.PER_DAY
Conversion factor from hours to days.
Definition at line 28 of file Days.cs.
Referenced by Juniper.Units.Hours.Days().
PER_MILLISECOND
const float Juniper.Units.Days.PER_MILLISECOND = 1 / Units.Milliseconds.PER_DAY
Conversion factor from milliseconds to days.
Definition at line 13 of file Days.cs.
Referenced by Juniper.Units.Milliseconds.Days().
PER_MINUTE
const float Juniper.Units.Days.PER_MINUTE = 1 / Units.Minutes.PER_DAY
Conversion factor from minutes to days.
Definition at line 23 of file Days.cs.
Referenced by Juniper.Units.Minutes.Days().
PER_SECOND
const float Juniper.Units.Days.PER_SECOND = 1 / Units.Seconds.PER_DAY
Conversion factor from seconds to days.
Definition at line 18 of file Days.cs.
Referenced by Juniper.Units.Seconds.Days().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper.Units/src/Time/Days.cs