Juniper: System.Net.HttpWebRequestExt Class Reference
System.Net.HttpWebRequestExt Class Reference
Utility functions and extension methods on HttpWebRequest queries
Static Public Member Functions
static HttpWebRequest Create (Uri uri)
Creates a new HttpWebRequest object for a given URI with the "Upgrade-Insecure-Requests" header already set to True.
static HttpWebRequest Create (string url)
Creates a new HttpWebRequest object for a given URI with the "Upgrade-Insecure-Requests" header already set to True.
static HttpWebRequest Header< T > (this HttpWebRequest request, string name, T value)
Adds an HTTP header to a HttpWebRequest, providing a literate interface for adding headers to requests. The header value will be converted to a string with its type's default ToString method.
static HttpWebRequest DoNotTrack (this HttpWebRequest request)
Adds the "DNT" header, set to True (1), for a given request.
static HttpWebRequest Host (this HttpWebRequest request, string host)
static HttpWebRequest UserAgent (this HttpWebRequest request, string agent)
static HttpWebRequest Referer (this HttpWebRequest request, string referer)
static HttpWebRequest FetchMode (this HttpWebRequest request, string mode)
static HttpWebRequest FetchSite (this HttpWebRequest request, string site)
static HttpWebRequest Accept (this HttpWebRequest request, string type)
Sets the Accept header for the HTTP request.
static HttpWebRequest TransferEncoding (this HttpWebRequest request, string encoding)
Sets the TransferEncoding header for the HTTP request.
static HttpWebRequest AcceptEncoding (this HttpWebRequest request, string encoding)
Sets the Accept-Encoding header for the HTTP request.
static HttpWebRequest AcceptLanguage (this HttpWebRequest request, string language)
static HttpWebRequest IfRange (this HttpWebRequest request, string value)
static HttpWebRequest KeepAlive (this HttpWebRequest request)
Sets the KeepAlive header to True.
static HttpWebRequest Cookie (this HttpWebRequest request, string keyValue, string domain)
static HttpWebRequest Cookie (this HttpWebRequest request, string key, string value, string domain)
static HttpWebRequest Method (this HttpWebRequest request, HttpMethods method)
Sets the method for the HTTP request.
static HttpWebRequest BasicAuth (this HttpWebRequest request, string userName, string password)
Sets the Authorization header for the request, using Basic HTTP auth.
static async Task WriteBodyAsync (this HttpWebRequest request, Func< BodyInfo > getInfo, Action< Stream > writeBody, IProgress prog=null)
Writes a body to an HttpWebRequest. Writing HTTP bodies with HttpWebRequest requires certain operations be done in a specific order, an order that might not make sense for every calling site. This method enforces that order.
static async Task< HttpWebResponse > DeleteAsync (this HttpWebRequest request, Func< BodyInfo > getInfo, Action< Stream > writeBody, IProgress prog)
Perform a DELETE request, writing the body through a stream, and return the results as a stream.
static Task< HttpWebResponse > DeleteAsync (this HttpWebRequest request)
Perform a DELETE request, writing the body through a stream, and return the results as a stream.
static async Task< HttpWebResponse > GetAsync (this HttpWebRequest request)
Perform a GET request and return the results as a stream of bytes
Detailed Description
Utility functions and extension methods on HttpWebRequest queries
Definition at line 12 of file HttpWebRequestExt.cs.
Member Function Documentation
Accept()
static HttpWebRequest System.Net.HttpWebRequestExt.Accept (this HttpWebRequest request, string type) inline static
Sets the Accept header for the HTTP request.
Parameters
request The request to which to add the Header
type The Content-Type to use as the Header value.
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
var request = HttpWebRequestExt.Create("https://www.example.com"); request.Header("Keep-Alive", 1) .Header("DNT", 1") .Accept(MediaType.Text.Plain");
Definition at line 186 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.Accept = type;
             return request;
         }
AcceptEncoding()
static HttpWebRequest System.Net.HttpWebRequestExt.AcceptEncoding (this HttpWebRequest request, string encoding) inline static
Sets the Accept-Encoding header for the HTTP request.
Parameters
request The request to which to add the Header
type The encoding string to use as the Header value.
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
var request = HttpWebRequestExt.Create("https://www.example.com"); request.Header("Keep-Alive", 1) .Header("DNT", 1") .Accept(MediaType.Text.Plain") .Encoding("utf-8");
Definition at line 235 of file HttpWebRequestExt.cs.
         {
             request.Header("Accept-Encoding", encoding);
             return request;
         }
AcceptLanguage()
static HttpWebRequest System.Net.HttpWebRequestExt.AcceptLanguage (this HttpWebRequest request, string language) inline static
Definition at line 241 of file HttpWebRequestExt.cs.
         {
             request.Header("Accept-Language", language);
             return request;
         }
BasicAuth()
static HttpWebRequest System.Net.HttpWebRequestExt.BasicAuth (this HttpWebRequest request, string userName, string password) inline static
Sets the Authorization header for the request, using Basic HTTP auth.
Parameters
userName Basic HTTP authentication user name.
password Basic HTTP authentication user password.
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
Definition at line 345 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             if (!string.IsNullOrEmpty(userName) && !string.IsNullOrEmpty(password))
             {
                 var authPair = userName + ":" + password;
                 var authBytes = Text.Encoding.UTF8.GetBytes(authPair);
                 var auth64 = Convert.ToBase64String(authBytes);
                 request.Header("Authorization", "Basic " + auth64);
             }
             return request;
         }
Cookie() [1/2]
static HttpWebRequest System.Net.HttpWebRequestExt.Cookie (this HttpWebRequest request, string keyValue, string domain) inline static
Definition at line 276 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             if (keyValue is null)
             {
                 throw new ArgumentNullException(nameof(keyValue));
             }
             var parts = keyValue.SplitX('=');
             return request.Cookie(parts[0], parts[1], domain);
         }
Referenced by System.Net.HttpWebRequestExt.Cookie().
Cookie() [2/2]
static HttpWebRequest System.Net.HttpWebRequestExt.Cookie (this HttpWebRequest request, string key, string value, string domain) inline static
Definition at line 292 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             if (key is null)
             {
                 throw new ArgumentNullException(nameof(key));
             }
             if (key.Length == 0)
             {
                 throw new ArgumentException("Key must have a value.", nameof(key));
             }
             var cookie = new Cookie(key, value, string.Empty, domain);
             request.CookieContainer ??= new CookieContainer();
             request.CookieContainer.Add(cookie);
             return request;
         }
References System.Net.HttpWebRequestExt.Cookie().
Create() [1/2]
static HttpWebRequest System.Net.HttpWebRequestExt.Create (Uri uri) inline static
Creates a new HttpWebRequest object for a given URI with the "Upgrade-Insecure-Requests" header already set to True.
Parameters
uri The Uri object for which to create the request.
Returns
An HttpWebRequest object.
Definition at line 20 of file HttpWebRequestExt.cs.
         {
             if (uri is null)
             {
                 throw new ArgumentNullException(nameof(uri));
             }
             var request = (HttpWebRequest)WebRequest.Create(uri);
             if (uri.Scheme == "http")
             {
                 request.Header("Upgrade-Insecure-Requests", 1);
             }
             return request;
         }
Referenced by System.Net.HttpWebRequestExt.Create(), Juniper.World.Climate.OpenWeatherMap.OWMWeather.GetIconAsync< T >(), and Juniper.World.Climate.OpenWeatherMap.API.GetWeatherReportAsync().
Create() [2/2]
static HttpWebRequest System.Net.HttpWebRequestExt.Create (string url) inline static
Creates a new HttpWebRequest object for a given URI with the "Upgrade-Insecure-Requests" header already set to True.
Parameters
uri A string value that represents a URI.
Returns
An HttpWebRequest object.
Definition at line 42 of file HttpWebRequestExt.cs.
         {
             return Create(new Uri(url));
         }
References System.Net.HttpWebRequestExt.Create().
DeleteAsync() [1/2]
static async Task<HttpWebResponse> System.Net.HttpWebRequestExt.DeleteAsync (this HttpWebRequest request, Func< BodyInfo > getInfo, Action< Stream > writeBody, IProgress prog) inline static
Perform a DELETE request, writing the body through a stream, and return the results as a stream.
Parameters
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 420 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request = request.Method(HttpMethods.DELETE);
             await request
                 .WriteBodyAsync(getInfo, writeBody, prog)
                 .ConfigureAwait(false);
             return (HttpWebResponse)await request.GetResponseAsync()
                 .ConfigureAwait(false);
         }
DeleteAsync() [2/2]
static Task<HttpWebResponse> System.Net.HttpWebRequestExt.DeleteAsync (this HttpWebRequest request) inline static
Perform a DELETE request, writing the body through a stream, and return the results as a stream.
Parameters
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 440 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             return request.DeleteAsync(null, null, null);
         }
DoNotTrack()
static HttpWebRequest System.Net.HttpWebRequestExt.DoNotTrack (this HttpWebRequest request) inline static
Adds the "DNT" header, set to True (1), for a given request.
Parameters
request The request to which to add the header
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
var request = HttpWebRequestExt.Create("https://www.example.com"); request.Header("Keep-Alive", 1) .DoNotTrack() .Header("Accept", MediaType.Text.Plain");
Definition at line 108 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.Header("DNT", 1);
             return request;
         }
FetchMode()
static HttpWebRequest System.Net.HttpWebRequestExt.FetchMode (this HttpWebRequest request, string mode) inline static
Definition at line 152 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.Header("Sec-Fetch-Mode", mode);
             return request;
         }
FetchSite()
static HttpWebRequest System.Net.HttpWebRequestExt.FetchSite (this HttpWebRequest request, string site) inline static
Definition at line 163 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.Header("Sec-Fetch-Site", site);
             return request;
         }
GetAsync()
static async Task<HttpWebResponse> System.Net.HttpWebRequestExt.GetAsync (this HttpWebRequest request) inline static
Perform a GET request and return the results as a stream of bytes
Parameters
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 455 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             return (HttpWebResponse)await request
                 .Method(HttpMethods.GET)
                 .GetResponseAsync()
                 .ConfigureAwait(false);
         }
Header< T >()
static HttpWebRequest System.Net.HttpWebRequestExt.Header< T > (this HttpWebRequest request, string name, T value) inline static
Adds an HTTP header to a HttpWebRequest, providing a literate interface for adding headers to requests. The header value will be converted to a string with its type's default ToString method.
Template Parameters
T The type of the value for the header that is being added to the request.
Parameters
request The request to which to add the header
name The name of the header that is being added to the request
value The value of the header that is being added to the request. Boolean values get converted to "1" for True and "0" for False.
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
var request = HttpWebRequestExt.Create("https://www.example.com"); request.Header("Keep-Alive", 1) .Header("DNT", 1") .Header("Accept", MediaType.Text.Plain");
Definition at line 64 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             if (name is null)
             {
                 throw new ArgumentNullException(nameof(name));
             }
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             string valueString;
             if (value is bool b)
             {
                 valueString = b
                     ? "1"
                     : "0";
             }
             else
             {
                 valueString = value.ToString();
             }
             request.Headers.Add(name, valueString);
             return request;
         }
Host()
static HttpWebRequest System.Net.HttpWebRequestExt.Host (this HttpWebRequest request, string host) inline static
Definition at line 119 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.Host = host;
             return request;
         }
IfRange()
static HttpWebRequest System.Net.HttpWebRequestExt.IfRange (this HttpWebRequest request, string value) inline static
Definition at line 247 of file HttpWebRequestExt.cs.
         {
             request.Header("If-Range", value);
             return request;
         }
KeepAlive()
static HttpWebRequest System.Net.HttpWebRequestExt.KeepAlive (this HttpWebRequest request) inline static
Sets the KeepAlive header to True.
Parameters
request The request to which to add the Header
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
var request = HttpWebRequestExt.Create("https://www.example.com"); request.Header("Keep-Alive", 1) .Header("DNT", 1") .Accept(MediaType.Text.Plain") .KeepAlive();
Definition at line 265 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.KeepAlive = true;
             return request;
         }
Method()
static HttpWebRequest System.Net.HttpWebRequestExt.Method (this HttpWebRequest request, HttpMethods method) inline static
Sets the method for the HTTP request.
Parameters
request The request to which to add the Header
method The HTTP method to use for the request.
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
var request = HttpWebRequestExt.Create("https://www.example.com"); request.Method(HttpMethod.GET) .Header("Keep-Alive", 1) .Header("DNT", 1") .Accept(MediaType.Text.Plain");
Definition at line 328 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.Method = method.ToString();
             return request;
         }
Referer()
static HttpWebRequest System.Net.HttpWebRequestExt.Referer (this HttpWebRequest request, string referer) inline static
Definition at line 141 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.Referer = referer;
             return request;
         }
TransferEncoding()
static HttpWebRequest System.Net.HttpWebRequestExt.TransferEncoding (this HttpWebRequest request, string encoding) inline static
Sets the TransferEncoding header for the HTTP request.
Parameters
request The request to which to add the Header
type The encoding string to use as the Header value.
Returns
The request that was passed as the first argument, so that literate calls may be chained together.
var request = HttpWebRequestExt.Create("https://www.example.com"); request.Header("Keep-Alive", 1) .Header("DNT", 1") .Accept(MediaType.Text.Plain") .Encoding("utf-8");
Definition at line 210 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.SendChunked = true;
             request.TransferEncoding = encoding;
             return request;
         }
UserAgent()
static HttpWebRequest System.Net.HttpWebRequestExt.UserAgent (this HttpWebRequest request, string agent) inline static
Definition at line 130 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             request.UserAgent = agent;
             return request;
         }
WriteBodyAsync()
static async Task System.Net.HttpWebRequestExt.WriteBodyAsync (this HttpWebRequest request, Func< BodyInfo > getInfo, Action< Stream > writeBody, IProgress prog = null) inline static
Writes a body to an HttpWebRequest. Writing HTTP bodies with HttpWebRequest requires certain operations be done in a specific order, an order that might not make sense for every calling site. This method enforces that order.
Parameters
request The request to which to write the
getInfo
writeBody
Returns
Definition at line 372 of file HttpWebRequestExt.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             if (getInfo is null)
             {
                 throw new ArgumentNullException(nameof(getInfo));
             }
             if (writeBody is null)
             {
                 throw new ArgumentNullException(nameof(writeBody));
             }
             var info = getInfo();
             if (info is object)
             {
                 if (info.MIMEType is object)
                 {
                     request.ContentType = info.MIMEType;
                 }
                 if (info.Length >= 0)
                 {
                     request.ContentLength = info.Length;
                     if (info.Length > 0)
                     {
                         using var stream = await request
                             .GetRequestStreamAsync()
                             .ConfigureAwait(false);
                         using var progStream = new ProgressStream(stream, info.Length, prog, true);
                         writeBody(stream);
                         await progStream.FlushAsync()
                             .ConfigureAwait(false);
                     }
                 }
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/NETFX/Net/HttpWebRequestExt.cs