Juniper: Juniper.World.LightEstimation.LightMeasurement Class Reference
Juniper.World.LightEstimation.LightMeasurement Class Reference
Abstracts the measurement of light intensity from camera frames for Augmented Reality Light Estimation. This component executes in edit mode.
Public Member Functions
virtual void Awake ()
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void Install (bool reset)
Install, with or without a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
void Update ()
Check to see if the ARCore light estimation has been updated.
Public Attributes
bool useFake
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
float Intensity = 0.8f
The fake intensity value to use if UseFakeIntensity is true.
Color Color = Color.white
The fake color to use if UseFakeIntensity is true.
bool DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Protected Member Functions
virtual void UpdateMeasurement ()
virtual void PrintDebugReport ()
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Protected Attributes
float lastIntensity
Light estimate updates happen concurrently with frame updates. This value stores the last light intensity measurement that was calculated, for use in the current render frame.
Color lastColor
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
Properties
virtual bool UseFakeIntensity [get]
Returns true if the user has requested a fake intensity, or the application is running in the Unity Editor.
Color ColorEstimate [get]
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
float IntensityEstimate [get]
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Detailed Description
Abstracts the measurement of light intensity from camera frames for Augmented Reality Light Estimation. This component executes in edit mode.
Definition at line 14 of file LightMeasurement.cs.
Member Function Documentation
Awake()
virtual void Juniper.World.LightEstimation.AbstractLightMeasurement.Awake () inline virtual inherited
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
Definition at line 109 of file LightMeasurement.cs.
         {
             Install(false);
             SetFakeValues();
         }
References Juniper.World.LightEstimation.AbstractLightMeasurement.Install(), and Juniper.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
Install()
virtual void Juniper.World.LightEstimation.AbstractLightMeasurement.Install (bool reset) inline virtual inherited
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IO.IInstallable.
Definition at line 130 of file LightMeasurement.cs.
         {
         }
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.Awake(), and Juniper.World.LightEstimation.AbstractLightMeasurement.Reinstall().
PrintDebugReport()
virtual void Juniper.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport () inline protected virtual inherited
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Definition at line 175 of file LightMeasurement.cs.
         {
             if (UseFakeIntensity)
             {
                 ScreenDebugger.Print("Using fake light estimate");
             }
             ScreenDebugger.PrintFormat("  Raw: int {0:0.000} col {1}", IntensityEstimate, ColorEstimate);
         }
References Juniper.World.LightEstimation.AbstractLightMeasurement.ColorEstimate, Juniper.World.LightEstimation.AbstractLightMeasurement.IntensityEstimate, System.ScreenDebugger.Print(), System.ScreenDebugger.PrintFormat(), and Juniper.World.LightEstimation.AbstractLightMeasurement.UseFakeIntensity.
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.Update().
Reinstall()
virtual void Juniper.World.LightEstimation.AbstractLightMeasurement.Reinstall () inline virtual inherited
Reinstall the object with a full reset.
Implements Juniper.IO.IInstallable.
Definition at line 116 of file LightMeasurement.cs.
         {
             Install(true);
         }
References Juniper.World.LightEstimation.AbstractLightMeasurement.Install().
Uninstall()
virtual void Juniper.World.LightEstimation.AbstractLightMeasurement.Uninstall () inline virtual inherited
Remove platform-specific features from the object.
Implements Juniper.IO.IInstallable.
Definition at line 134 of file LightMeasurement.cs.
         {
         }
Update()
void Juniper.World.LightEstimation.AbstractLightMeasurement.Update () inline inherited
Check to see if the ARCore light estimation has been updated.
Definition at line 150 of file LightMeasurement.cs.
         {
             if (UseFakeIntensity)
             {
                 SetFakeValues();
             }
             else
             {
                 UpdateMeasurement();
             }
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.World.LightEstimation.AbstractLightMeasurement.DebugReport, Juniper.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), Juniper.World.LightEstimation.AbstractLightMeasurement.SetFakeValues(), Juniper.World.LightEstimation.AbstractLightMeasurement.UpdateMeasurement(), and Juniper.World.LightEstimation.AbstractLightMeasurement.UseFakeIntensity.
UpdateMeasurement()
virtual void Juniper.World.LightEstimation.AbstractLightMeasurement.UpdateMeasurement () inline protected virtual inherited
Definition at line 167 of file LightMeasurement.cs.
         {
         }
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.Update().
Member Data Documentation
Color
Color Juniper.World.LightEstimation.AbstractLightMeasurement.Color = Color.white inherited
The fake color to use if UseFakeIntensity is true.
Definition at line 72 of file LightMeasurement.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
DebugReport
bool Juniper.World.LightEstimation.AbstractLightMeasurement.DebugReport inherited
When set to true, the Update loop will include printing out the internal values of the component;
Definition at line 77 of file LightMeasurement.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.Update().
Intensity
float Juniper.World.LightEstimation.AbstractLightMeasurement.Intensity = 0.8f inherited
The fake intensity value to use if UseFakeIntensity is true.
Definition at line 67 of file LightMeasurement.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
lastColor
Color Juniper.World.LightEstimation.AbstractLightMeasurement.lastColor protected inherited
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
Definition at line 43 of file LightMeasurement.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.SetFakeValues(), and Juniper.World.LightEstimation.ARKitLightMeasurement.UnityARSessionNativeInterface_ARFrameUpdatedEvent().
lastIntensity
float Juniper.World.LightEstimation.AbstractLightMeasurement.lastIntensity protected inherited
Light estimate updates happen concurrently with frame updates. This value stores the last light intensity measurement that was calculated, for use in the current render frame.
Definition at line 37 of file LightMeasurement.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.SetFakeValues(), and Juniper.World.LightEstimation.ARKitLightMeasurement.UnityARSessionNativeInterface_ARFrameUpdatedEvent().
useFake
bool Juniper.World.LightEstimation.AbstractLightMeasurement.useFake inherited
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
Definition at line 49 of file LightMeasurement.cs.
Property Documentation
ColorEstimate
Color Juniper.World.LightEstimation.AbstractLightMeasurement.ColorEstimate get inherited
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light color estimate.
Definition at line 85 of file LightMeasurement.cs.
         {
             get
             {
                 return lastColor;
             }
         }
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.World.LightEstimation.AbstractLightEstimate.Update().
IntensityEstimate
float Juniper.World.LightEstimation.AbstractLightMeasurement.IntensityEstimate get inherited
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light intensity estimate.
Definition at line 98 of file LightMeasurement.cs.
         {
             get
             {
                 return lastIntensity;
             }
         }
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.World.LightEstimation.AbstractLightEstimate.Update().
UseFakeIntensity
virtual bool Juniper.World.LightEstimation.AbstractLightMeasurement.UseFakeIntensity get protected inherited
Returns true if the user has requested a fake intensity, or the application is running in the Unity Editor.
true if use fake intensity; otherwise, false.
Definition at line 57 of file LightMeasurement.cs.
         {
             get
             {
                 return useFake || Application.isEditor;
             }
         }
Referenced by Juniper.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.World.LightEstimation.AbstractLightMeasurement.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/LightEstimation/LightMeasurement.cs