Juniper: Juniper.Terminal.ConsoleCommandProcessor Class Reference
Juniper.Terminal.ConsoleCommandProcessor Class Reference
Public Member Functions
void Pump ()
void Execute (ConsoleKey key)
void PrintUsage ()
void Add (ConsoleKey key, string description, Action action)
void Add ((ConsoleKey key, string description, Action action) entry)
bool ContainsKey (ConsoleKey key)
bool TryGetValue (ConsoleKey key, out NamedAction value)
IEnumerator< KeyValuePair< ConsoleKey, NamedAction > > GetEnumerator ()
void SetLogLevel (int direction)
void OnInfo (object sender, StringEventArgs e)
void OnInfo (ConsoleColor color, string msg)
void OnInfo (string msg)
void OnLog (object sender, StringEventArgs e)
void OnWarning (object sender, StringEventArgs e)
void OnError (object sender, ErrorEventArgs e)
void OnError (ErrorEventArgs e)
Static Public Member Functions
static string GetName (uint logLevel)
Public Attributes
IEnumerable< ConsoleKey > Keys => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Keys
IEnumerable< NamedAction > Values => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Values
int Count => actions.Count
Properties
NamedAction this[ConsoleKey key] [get]
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
void Log< T > (uint level, Action< string > logger, ConsoleColor foreground, T e)
void Log< T > (uint level, Action< string > logger, ConsoleColor foreground, ConsoleColor background, T e)
Private Attributes
readonly Dictionary< ConsoleKey, NamedAction > actions = new Dictionary<ConsoleKey, NamedAction>()
uint logLevel = 0
Detailed Description
Definition at line 13 of file ConsoleCommandProcessor.cs.
Member Function Documentation
Add() [1/2]
void Juniper.Terminal.ConsoleCommandProcessor.Add (ConsoleKey key, string description, Action action) inline
Definition at line 94 of file ConsoleCommandProcessor.cs.
         {
             actions.Add(key, (description, action));
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions.
Referenced by Juniper.Terminal.ConsoleCommandProcessor.Add().
Add() [2/2]
void Juniper.Terminal.ConsoleCommandProcessor.Add ((ConsoleKey key, string description, Action action) entry) inline
Definition at line 99 of file ConsoleCommandProcessor.cs.
         {
             var (key, description, action) = entry;
             Add(key, description, action);
         }
References Juniper.Terminal.ConsoleCommandProcessor.Add().
ContainsKey()
bool Juniper.Terminal.ConsoleCommandProcessor.ContainsKey (ConsoleKey key) inline
Definition at line 105 of file ConsoleCommandProcessor.cs.
         {
             return actions.ContainsKey(key);
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions.
Execute()
void Juniper.Terminal.ConsoleCommandProcessor.Execute (ConsoleKey key) inline
Definition at line 40 of file ConsoleCommandProcessor.cs.
         {
             actions[key].Invoke();
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions.
Referenced by Juniper.Terminal.ConsoleCommandProcessor.Pump().
GetEnumerator() [1/2]
IEnumerator<KeyValuePair<ConsoleKey, NamedAction> > Juniper.Terminal.ConsoleCommandProcessor.GetEnumerator () inline
Definition at line 115 of file ConsoleCommandProcessor.cs.
         {
             return ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).GetEnumerator();
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions.
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.Terminal.ConsoleCommandProcessor.GetEnumerator () inline private
Definition at line 120 of file ConsoleCommandProcessor.cs.
         {
             return ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).GetEnumerator();
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions.
GetName()
static string Juniper.Terminal.ConsoleCommandProcessor.GetName (uint logLevel) inline static
Definition at line 135 of file ConsoleCommandProcessor.cs.
         {
             return logLevel switch
             {
                 0 => "Verbose",
                 1 => "Log",
                 2 => "Warning",
                 3 => "Error",
                 _ => "N/A"
             };
         }
References Juniper.Terminal.ConsoleCommandProcessor.logLevel.
Log< T >() [1/2]
void Juniper.Terminal.ConsoleCommandProcessor.Log< T > (uint level, Action< string > logger, ConsoleColor foreground, T e) inline private
Definition at line 147 of file ConsoleCommandProcessor.cs.
         {
             Log(level, logger, foreground, Console.BackgroundColor, e);
         }
Log< T >() [2/2]
void Juniper.Terminal.ConsoleCommandProcessor.Log< T > (uint level, Action< string > logger, ConsoleColor foreground, ConsoleColor background, T e) inline private
Definition at line 152 of file ConsoleCommandProcessor.cs.
         {
             if (level >= logLevel)
             {
                 using var scope = new ColorScope(background, foreground);
                 logger($"[{GetName(level)}] {e?.ToString()}");
             }
         }
References Juniper.Terminal.ConsoleCommandProcessor.logLevel.
OnError() [1/2]
void Juniper.Terminal.ConsoleCommandProcessor.OnError (object sender, ErrorEventArgs e) inline
Implements Juniper.Logging.IErrorDestination.
Definition at line 192 of file ConsoleCommandProcessor.cs.
         {
             Log(3, Console.Error.WriteLine, Red, e);
         }
OnError() [2/2]
void Juniper.Terminal.ConsoleCommandProcessor.OnError (ErrorEventArgs e) inline
Definition at line 198 of file ConsoleCommandProcessor.cs.
         {
             Log(3, Console.Error.WriteLine, Red, e);
         }
OnInfo() [1/3]
void Juniper.Terminal.ConsoleCommandProcessor.OnInfo (object sender, StringEventArgs e) inline
Implements Juniper.Logging.IInfoDestination.
Definition at line 162 of file ConsoleCommandProcessor.cs.
         {
             OnInfo(e?.Value);
         }
OnInfo() [2/3]
void Juniper.Terminal.ConsoleCommandProcessor.OnInfo (ConsoleColor color, string msg) inline
Definition at line 168 of file ConsoleCommandProcessor.cs.
         {
             Log(0, Console.WriteLine, color, msg);
         }
OnInfo() [3/3]
void Juniper.Terminal.ConsoleCommandProcessor.OnInfo (string msg) inline
Definition at line 174 of file ConsoleCommandProcessor.cs.
         {
             Log(0, Console.WriteLine, White, msg);
         }
OnLog()
void Juniper.Terminal.ConsoleCommandProcessor.OnLog (object sender, StringEventArgs e) inline
Implements Juniper.Logging.INCSALogDestination.
Definition at line 180 of file ConsoleCommandProcessor.cs.
         {
             Log(1, Console.WriteLine, Cyan, e);
         }
OnWarning()
void Juniper.Terminal.ConsoleCommandProcessor.OnWarning (object sender, StringEventArgs e) inline
Implements Juniper.Logging.IWarningDestination.
Definition at line 186 of file ConsoleCommandProcessor.cs.
         {
             Log(2, Console.WriteLine, Yellow, e);
         }
PrintUsage()
void Juniper.Terminal.ConsoleCommandProcessor.PrintUsage () inline
Definition at line 45 of file ConsoleCommandProcessor.cs.
         {
             var maxKeyLen = (from key in actions.Keys
                              let keyName = key.ToString()
                              select keyName.Length)
                         .Max();
             var format = $"  {{0,-{maxKeyLen}}} : {{1}}";
             var lines = (from command in actions
                          select string.Format(CultureInfo.InvariantCulture, format, command.Key, command.Value.Name))
                          .Prepend("Usage:")
                          .Prepend("")
                          .Append("")
                          .ToArray();
             var maxLen = lines.Max(l => l.Length);
             for (var i = 0; i < lines.Length; ++i)
             {
                 while (lines[i].Length <= maxLen)
                 {
                     lines[i] += " ";
                 }
                 lines[i] = " " + lines[i];
             }
             Console.WriteLine();
             using var scope = new ColorScope(DarkGray, Yellow);
             foreach (var line in lines)
             {
                 Console.WriteLine(line);
             }
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions.
Referenced by Juniper.Terminal.ConsoleCommandProcessor.Pump().
Pump()
void Juniper.Terminal.ConsoleCommandProcessor.Pump () inline
Definition at line 24 of file ConsoleCommandProcessor.cs.
         {
             if (Console.KeyAvailable)
             {
                 var keyInfo = Console.ReadKey(true);
                 if (actions.ContainsKey(keyInfo.Key))
                 {
                     Execute(keyInfo.Key);
                 }
                 else
                 {
                     PrintUsage();
                 }
             }
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions, Juniper.Terminal.ConsoleCommandProcessor.Execute(), and Juniper.Terminal.ConsoleCommandProcessor.PrintUsage().
SetLogLevel()
void Juniper.Terminal.ConsoleCommandProcessor.SetLogLevel (int direction) inline
Definition at line 125 of file ConsoleCommandProcessor.cs.
         {
             var nextLogLevel = (uint)(logLevel + direction);
             if (nextLogLevel < 4)
             {
                 logLevel = nextLogLevel;
                 Console.WriteLine($"Logging level is now {GetName(logLevel)}");
             }
         }
References Juniper.Terminal.ConsoleCommandProcessor.logLevel.
TryGetValue()
bool Juniper.Terminal.ConsoleCommandProcessor.TryGetValue (ConsoleKey key, out NamedAction value) inline
Definition at line 110 of file ConsoleCommandProcessor.cs.
         {
             return actions.TryGetValue(key, out value);
         }
References Juniper.Terminal.ConsoleCommandProcessor.actions.
Member Data Documentation
actions
readonly Dictionary<ConsoleKey, NamedAction> Juniper.Terminal.ConsoleCommandProcessor.actions = new Dictionary<ConsoleKey, NamedAction>() private
Definition at line 20 of file ConsoleCommandProcessor.cs.
Referenced by Juniper.Terminal.ConsoleCommandProcessor.Add(), Juniper.Terminal.ConsoleCommandProcessor.ContainsKey(), Juniper.Terminal.ConsoleCommandProcessor.Execute(), Juniper.Terminal.ConsoleCommandProcessor.GetEnumerator(), Juniper.Terminal.ConsoleCommandProcessor.PrintUsage(), Juniper.Terminal.ConsoleCommandProcessor.Pump(), and Juniper.Terminal.ConsoleCommandProcessor.TryGetValue().
Count
int Juniper.Terminal.ConsoleCommandProcessor.Count => actions.Count
Definition at line 84 of file ConsoleCommandProcessor.cs.
Keys
IEnumerable<ConsoleKey> Juniper.Terminal.ConsoleCommandProcessor.Keys => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Keys
Definition at line 80 of file ConsoleCommandProcessor.cs.
logLevel
uint Juniper.Terminal.ConsoleCommandProcessor.logLevel = 0 private
Definition at line 22 of file ConsoleCommandProcessor.cs.
Referenced by Juniper.Terminal.ConsoleCommandProcessor.GetName(), Juniper.Terminal.ConsoleCommandProcessor.Log< T >(), and Juniper.Terminal.ConsoleCommandProcessor.SetLogLevel().
Values
IEnumerable<NamedAction> Juniper.Terminal.ConsoleCommandProcessor.Values => ((IReadOnlyDictionary<ConsoleKey, NamedAction>)actions).Values
Definition at line 82 of file ConsoleCommandProcessor.cs.
Property Documentation
this[ConsoleKey key]
NamedAction Juniper.Terminal.ConsoleCommandProcessor.this[ConsoleKey key] get
Definition at line 87 of file ConsoleCommandProcessor.cs.
         {
             get
             {
                 return actions[key];
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Terminal/ConsoleCommandProcessor.cs