Juniper: Juniper.ConfigurationManagement.JuniperOptionalPackageManager Class Reference
Juniper.ConfigurationManagement.JuniperOptionalPackageManager Class Reference
An editor to respond to changes in XRSystem.
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void ShowJuniperWindow ()
Static Private Member Functions
static void DrawOptionalPackages (PackageReference[] requiredPackages)
static void DrawStatus (PlatformType selectedPlatform, BuildTargetGroup targetGroup)
Private Attributes
const string MENU_NAME = "Juniper/"
const int buttonWidthValue = 100
Static Private Attributes
static readonly GUIContent TITLE = new GUIContent("Juniper - Optional Packages")
static readonly GUILayoutOption nameFieldWidth = GUILayout.Width(200)
static readonly GUILayoutOption buttonWidth = GUILayout.Width(buttonWidthValue)
static readonly TableView optionalPackageTable
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 22 of file JuniperOptionalPackageInstaller.cs.
Member Function Documentation
DrawOptionalPackages()
static void Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages (PackageReference [] requiredPackages) inline static private
Definition at line 71 of file JuniperOptionalPackageInstaller.cs.
         {
             var optionalPackages = from versions in Project.PackageDatabase.Values
                                    let highest = versions.OrderByDescending(p => p.Version).FirstOrDefault()
                                    where !requiredPackages.Any(p => p.PackageID == highest.PackageID)
                                     && !highest.ForRemoval
                                     && !Project.IsInstalled(highest)
                                    orderby highest.Source, highest.PackageID, highest.VersionSpec
                                    select highest;
             using (optionalPackageTable.Begin())
             {
                 var drawn = 0;
                 foreach (var req in optionalPackages)
                 {
                     ++drawn;
                     using (new HGroup())
                     {
                         var isAvailable = Project.IsAvailable(req);
                         EditorGUILayout.LabelField(req.Source.ToString(), nameFieldWidth);
                         EditorGUILayout.LabelField(req.Name);
                         EditorGUILayout.LabelField(req.VersionSpec, nameFieldWidth);
                         using (new EnabledScope(isAvailable))
{
                             if (GUILayout.Button(isAvailable
                                 ? "Install"
                                 : "Not available", buttonWidth))
{
                                 var pkg = Project.PackageDatabase.ContainsKey(req.PackageID)
                                     ? Project.PackageDatabase[req.PackageID].FirstOrDefault(req.Equals)
                                     : null;
                                 if (pkg is null)
{
                                     Debug.LogWarning("Couldn't find pakage " + req);
                                 }
                                 else
{
                                     pkg.Install();
                                 }
                             }
                         }
                     }
                 }
                 if (drawn == 0)
                 {
                     EditorGUILayout.LabelField("None", EditorStyles.centeredGreyMiniLabel);
                 }
             }
         }
References UnityEditor.TableView.Begin(), Juniper.ConfigurationManagement.JuniperOptionalPackageManager.buttonWidth, Juniper.XR.Debug, Juniper.ConfigurationManagement.PackageReference.ForRemoval, Juniper.ConfigurationManagement.Project.IsAvailable(), Juniper.ConfigurationManagement.Project.IsInstalled(), Juniper.ConfigurationManagement.JuniperOptionalPackageManager.nameFieldWidth, Juniper.ConfigurationManagement.JuniperOptionalPackageManager.optionalPackageTable, and Juniper.ConfigurationManagement.Project.PackageDatabase.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.OnGUI().
DrawStatus()
static void Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawStatus (PlatformType selectedPlatform, BuildTargetGroup targetGroup) inline static private
Definition at line 125 of file JuniperOptionalPackageInstaller.cs.
         {
             using (new Header("Status"))
             {
                 EditorGUILayoutExt.LabeledField("Current platform", nameFieldWidth, selectedPlatform, nameFieldWidth);
                 EditorGUILayoutExt.LabeledField("Current build target", nameFieldWidth, targetGroup, nameFieldWidth);
             }
         }
References Juniper.ConfigurationManagement.JuniperOptionalPackageManager.nameFieldWidth.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.OnGUI().
OnGUI()
void Juniper.ConfigurationManagement.JuniperOptionalPackageManager.OnGUI () inline
Definition at line 46 of file JuniperOptionalPackageInstaller.cs.
         {
             titleContent = TITLE;
             if (EditorApplication.isCompiling)
             {
                 EditorGUILayout.LabelField("Compiling...");
             }
             else
             {
                 var platforms = Platforms.Load();
                 var selectedPlatform = ProjectConfiguration.Platform;
                 var currentConfiguration = platforms.Configurations[selectedPlatform];
                 var targetGroup = currentConfiguration.GetTargetGroup();
                 DrawStatus(selectedPlatform, targetGroup);
                 var requiredPackages = platforms.Packages
                     .Union(currentConfiguration.Packages)
                     .ToArray();
                 DrawOptionalPackages(requiredPackages);
             }
         }
References Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages(), Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawStatus(), Juniper.ConfigurationManagement.Platforms.Load(), Juniper.ProjectConfiguration.Platform, and Juniper.ConfigurationManagement.JuniperOptionalPackageManager.TITLE.
ShowJuniperWindow()
static void Juniper.ConfigurationManagement.JuniperOptionalPackageManager.ShowJuniperWindow () inline static
Definition at line 25 of file JuniperOptionalPackageInstaller.cs.
         {
             EditorWindow.GetWindow<JuniperOptionalPackageManager>();
         }
Member Data Documentation
buttonWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperOptionalPackageManager.buttonWidth = GUILayout.Width(buttonWidthValue) static private
Definition at line 36 of file JuniperOptionalPackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages().
buttonWidthValue
const int Juniper.ConfigurationManagement.JuniperOptionalPackageManager.buttonWidthValue = 100 private
Definition at line 33 of file JuniperOptionalPackageInstaller.cs.
MENU_NAME
const string Juniper.ConfigurationManagement.JuniperOptionalPackageManager.MENU_NAME = "Juniper/" private
Definition at line 30 of file JuniperOptionalPackageInstaller.cs.
nameFieldWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperOptionalPackageManager.nameFieldWidth = GUILayout.Width(200) static private
Definition at line 35 of file JuniperOptionalPackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages(), and Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawStatus().
optionalPackageTable
readonly TableView Juniper.ConfigurationManagement.JuniperOptionalPackageManager.optionalPackageTable static private
Initial value:
= new TableView(
            "Optional Packages",
            ("Source", nameFieldWidth),
            ("Name", null),
            ("Version", nameFieldWidth),
            ("", buttonWidth)
        )
Definition at line 38 of file JuniperOptionalPackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages().
TITLE
readonly GUIContent Juniper.ConfigurationManagement.JuniperOptionalPackageManager.TITLE = new GUIContent("Juniper - Optional Packages") static private
Definition at line 31 of file JuniperOptionalPackageInstaller.cs.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.OnGUI().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Plugins/Editor/Juniper/ConfigurationManagement/JuniperOptionalPackageInstaller.cs