Juniper: Juniper.Progress.StaticProgress Class Reference
Juniper.Progress.StaticProgress Class Reference
Public Member Functions
StaticProgress ()
void SetProgress (float progress, string status=null)
Static Public Attributes
static IProgress COMPLETE = new StaticProgress(1)
Properties
float Progress [get, private set]
Private Member Functions
StaticProgress (float value)
Detailed Description
Definition at line 3 of file StaticProgress.cs.
Constructor & Destructor Documentation
StaticProgress() [1/2]
Juniper.Progress.StaticProgress.StaticProgress (float value) inline private
Definition at line 7 of file StaticProgress.cs.
         {
             SetProgress(value);
         }
References Juniper.Progress.StaticProgress.SetProgress().
StaticProgress() [2/2]
Juniper.Progress.StaticProgress.StaticProgress () inline
Definition at line 12 of file StaticProgress.cs.
         {
             SetProgress(0);
         }
References Juniper.Progress.StaticProgress.SetProgress().
Member Function Documentation
SetProgress()
void Juniper.Progress.StaticProgress.SetProgress (float progress, string status = null)
Implements Juniper.Progress.IProgressReceiver.
Referenced by Juniper.Progress.StaticProgress.StaticProgress().
Member Data Documentation
COMPLETE
IProgress Juniper.Progress.StaticProgress.COMPLETE = new StaticProgress(1) static
Definition at line 5 of file StaticProgress.cs.
Referenced by Juniper.MasterSceneController.LoadScene().
Property Documentation
Progress
float Juniper.Progress.StaticProgress.Progress get private set
Definition at line 17 of file StaticProgress.cs.
 { get; private set; }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Progress/StaticProgress.cs