Juniper: Juniper.Unity.Animation.FadeTransition Class Reference
Juniper.Unity.Animation.FadeTransition Class Reference
Performs a fade-in/fade-out animation on scene transitions.
Public Member Functions
void Awake ()
Retrieves component references and sets up event handlers.
virtual void Reinstall ()
Resets the object to its initial state.
void Install (bool reset)
Installs necessary components and initializes their default values.
void Uninstall ()
There are no components to uninstall from this component.
void Fader (Action act)
Adds the provided action to a queue of actions that will be executed in between a fade-out and fade-in cycle. This is useful for hiding long processing actions that would cause the VR view to stutter.
override void Enter ()
Start the transition animation in the forward direction.
override void SkipEnter ()
Jump the transition to the ENTERED state, without animating through the ENTERING state.
override void Exit ()
Start the transition animation in the outward direction.
override void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Static Public Member Functions
static PooledComponent< FadeTransition > Ensure (Transform parent)
Setup the necessary gameObjects and components to make a fader box appears in front of the camera.
Public Attributes
AudioClip fadeOutSound
The sound to play when the view fades out.
AudioClip fadeInSound
The sound to play when the view fades back in.
float fadeLength = 0.25f
If Unity's audio subsystem is not available, or the fade-in/fade-out sounds are not configured, this is the default length of time to run the fade-in/fade-out transition.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void RenderValue (float value)
As the fade transition updates, sets the opacity of the view blocker graphic.
override void OnEntered ()
Saves the last clear color, culling mask, and ambient light mode, then prepares the camera to render the special "faded out" view, which allows TransparentFX objects to still be visible, so we can have simple UI elements still visible while the view is faded out. If Unity's audio subsystem is available, switches the audio source to use the fade-in sound for the next transition. Also, executes and queued actions that are waiting for the fade transition to complete.
override void OnExiting ()
Restores the camera's rendering and lighting modes to what it was before the fade-out.
override void OnExited ()
If Unity's audio subsystem is available, switches the audio source to use the fade-out sound for the next transition.
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Properties
override float???? TransitionLength [get]
The amount of time the fade transition takes to complete. If a fade sound is provided, this will be based on the length of the sound clip. Otherwise, it's 1/4th of a second.
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler< ValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Member Functions
void FadeTransition_Enter_Exiting (object sender, EventArgs e)
Play the fade-in/fade-out sound
Private Attributes
DisplayManager display
Used to check the current ARMode to determine how to restore the camera clear mode.
AudioSource aud
The audio source on which to play the fade-in/fade-out sounds.
UnifiedInputModule input
Renderer r
The renderer for the current object.
MaterialPropertyBlock props
Used to change values in the material, without globally changing the material.
readonly List< Action > actions = new List<Action>(5)
A queue of actions to perform when the fader has finished fading out, before it fades back in.
Color lastColor
The clear-color that was used before the fade-out transition started.
int lastCameraCullingMask
The culling-mask that was used before the fade-out transition started.
int lastControllerLayer
The layers the controllers are rendered on. This is used to make sure the controllers are still visible while the scene is faded out.
AmbientMode lastAmbientMode
The ambient light mode that was used before the fade-out transition was started.
Detailed Description
Performs a fade-in/fade-out animation on scene transitions.
Definition at line 16 of file FadeTransition.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Animation.FadeTransition.Awake () inline
Retrieves component references and sets up event handlers.
Definition at line 90 of file FadeTransition.cs.
         {
             Install(false);
             Entering += FadeTransition_Enter_Exiting;
             Exiting += FadeTransition_Enter_Exiting;
             r = GetComponent<Renderer>();
             props = new MaterialPropertyBlock();
             display = ComponentExt.FindAny<DisplayManager>();
             input = ComponentExt.FindAny<UnifiedInputModule>();
         }
References Juniper.Unity.Animation.FadeTransition.display, Juniper.Unity.AbstractStateController.Entering, Juniper.Unity.AbstractStateController.Exiting, Juniper.Unity.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Unity.Animation.FadeTransition.input, Juniper.Unity.Animation.FadeTransition.Install(), Juniper.Unity.Animation.FadeTransition.props, and Juniper.Unity.Animation.FadeTransition.r.
Ensure()
static PooledComponent<FadeTransition> Juniper.Unity.Animation.FadeTransition.Ensure (Transform parent) inline static
Setup the necessary gameObjects and components to make a fader box appears in front of the camera.
Returns
Definition at line 71 of file FadeTransition.cs.
         {
             var fader = parent.Ensure<Transform>("Fader", () =>
                 GameObject.CreatePrimitive(PrimitiveType.Quad))
                 .Ensure<FadeTransition>();
 #if UNITY_MODULES_PHYSICS
             if (fader.IsNew)
             {
                 fader.Value.Remove<Collider>();
             }
 #endif
             return fader;
         }
Referenced by Juniper.Unity.MasterSceneController.SetupFader().
Enter()
override void Juniper.Unity.Animation.AbstractTransitionController.Enter () inline virtual inherited
Start the transition animation in the forward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 65 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.Enter();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.Widgets.TeleportPad.OnClick(), Juniper.Unity.MasterSceneController.QuitCoroutine(), Juniper.Unity.Widgets.Openable.SetOpen(), and Juniper.Unity.Animation.WorkflowStep.Show().
Exit()
override void Juniper.Unity.Animation.AbstractTransitionController.Exit () inline virtual inherited
Start the transition animation in the outward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 85 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Reverse);
             base.Exit();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.Unity.Widgets.Openable.SetOpen().
Fader()
void Juniper.Unity.Animation.FadeTransition.Fader (Action act) inline
Adds the provided action to a queue of actions that will be executed in between a fade-out and fade-in cycle. This is useful for hiding long processing actions that would cause the VR view to stutter.
Parameters
act The action lambda expression to run
Definition at line 186 of file FadeTransition.cs.
         {
             if (actions.Count == 0)
             {
                 actions.Add(() =>
                 {
                     act();
                     Exit();
                 });
             }
             else
             {
                 actions.Add(act);
             }
             Enter();
         }
References Juniper.Unity.Animation.FadeTransition.actions, Juniper.Unity.Animation.AbstractTransitionController.Enter(), and Juniper.Unity.Animation.AbstractTransitionController.Exit().
FadeTransition_Enter_Exiting()
void Juniper.Unity.Animation.FadeTransition.FadeTransition_Enter_Exiting (object sender, EventArgs e) inline private
Play the fade-in/fade-out sound
Definition at line 227 of file FadeTransition.cs.
         {
 #if UNITY_MODULES_AUDIO
             aud.Play();
 #endif
         }
References Juniper.Unity.Animation.FadeTransition.aud.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake().
HasCompleted()
bool Juniper.Unity.AbstractStateController.HasCompleted () inline inherited
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 123 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.Unity.AbstractStateController.IsComplete.
Install()
void Juniper.Unity.Animation.FadeTransition.Install (bool reset) inline
Installs necessary components and initializes their default values.
Implements Juniper.IInstallable.
Definition at line 127 of file FadeTransition.cs.
         {
 #if UNITY_MODULES_AUDIO
 #if UNITY_EDITOR
             if (reset)
             {
                 fadeOutSound = ResourceExt.EditorLoadAsset<AudioClip>("Assets/Juniper/Audio/Star Trek/hologram_off_2.mp3");
                 fadeInSound = ResourceExt.EditorLoadAsset<AudioClip>("Assets/Juniper/Audio/Star Trek/hologrid_online.mp3");
             }
 #endif
             aud = this.Ensure<AudioSource>();
             aud.playOnAwake = false;
             aud.clip = fadeOutSound;
 #endif
         }
References Juniper.Unity.Animation.FadeTransition.aud, Juniper.Unity.Animation.FadeTransition.fadeInSound, and Juniper.Unity.Animation.FadeTransition.fadeOutSound.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.Animation.FadeTransition.Reinstall().
OnDisable()
void Juniper.Unity.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 300 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.Unity.AbstractStateController.OnExited().
OnEnable()
void Juniper.Unity.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 195 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.Unity.AbstractStateController.OnEntering().
Referenced by Juniper.Unity.AbstractStateController.SkipEnter().
OnEntered()
override void Juniper.Unity.Animation.FadeTransition.OnEntered () inline protected virtual
Saves the last clear color, culling mask, and ambient light mode, then prepares the camera to render the special "faded out" view, which allows TransparentFX objects to still be visible, so we can have simple UI elements still visible while the view is faded out. If Unity's audio subsystem is available, switches the audio source to use the fade-in sound for the next transition. Also, executes and queued actions that are waiting for the fade transition to complete.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 242 of file FadeTransition.cs.
         {
             base.OnEntered();
             lastColor = DisplayManager.BackgroundColor;
             lastCameraCullingMask = DisplayManager.CullingMask;
             lastControllerLayer = input.ControllerLayer;
             lastAmbientMode = RenderSettings.ambientMode;
             if (display.ARMode == AugmentedRealityTypes.None)
             {
                 DisplayManager.ClearFlags = CameraClearFlags.Color;
                 DisplayManager.BackgroundColor = ColorExt.TransparentBlack;
             }
             input.ControllerLayer = LayerMask.NameToLayer("TransparentFX");
             DisplayManager.CullingMask = LayerMask.GetMask("TransparentFX");
             RenderSettings.ambientMode = AmbientMode.Flat;
 #if UNITY_MODULES_AUDIO
             aud.clip = fadeInSound;
 #endif
             foreach (var action in actions)
             {
                 try
                 {
                     action();
                 }
                 catch (Exception exp)
                 {
                     Debug.LogError(exp);
                 }
             }
             actions.Clear();
         }
References Juniper.Unity.Animation.FadeTransition.actions, Juniper.Unity.Display.AbstractDisplayManager.ARMode, Juniper.Unity.Animation.FadeTransition.aud, Juniper.Unity.Display.AbstractDisplayManager.BackgroundColor, Juniper.Unity.Display.AbstractDisplayManager.ClearFlags, Juniper.Unity.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Unity.Display.AbstractDisplayManager.CullingMask, Juniper.XR.Debug, Juniper.Unity.Animation.FadeTransition.display, Juniper.Unity.Animation.FadeTransition.fadeInSound, Juniper.Unity.Animation.FadeTransition.input, Juniper.Unity.Animation.FadeTransition.lastAmbientMode, Juniper.Unity.Animation.FadeTransition.lastCameraCullingMask, Juniper.Unity.Animation.FadeTransition.lastColor, Juniper.Unity.Animation.FadeTransition.lastControllerLayer, and UnityEngine.ColorExt.TransparentBlack.
OnEntering()
virtual void Juniper.Unity.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 206 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntering?.Invoke();
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entering, Juniper.Unity.AbstractStateController.onEntering, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnEnable().
OnExited()
override void Juniper.Unity.Animation.FadeTransition.OnExited () inline protected virtual
If Unity's audio subsystem is available, switches the audio source to use the fade-out sound for the next transition.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 302 of file FadeTransition.cs.
         {
 #if UNITY_MODULES_AUDIO
             aud.clip = fadeOutSound;
 #endif
         }
References Juniper.Unity.Animation.FadeTransition.aud, and Juniper.Unity.Animation.FadeTransition.fadeOutSound.
OnExiting()
override void Juniper.Unity.Animation.FadeTransition.OnExiting () inline protected virtual
Restores the camera's rendering and lighting modes to what it was before the fade-out.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 283 of file FadeTransition.cs.
         {
             base.OnExiting();
             if (display.ARMode == AugmentedRealityTypes.None)
             {
                 DisplayManager.ClearFlags = CameraClearFlags.Skybox;
                 DisplayManager.BackgroundColor = lastColor;
             }
             DisplayManager.CullingMask = lastCameraCullingMask;
             input.ControllerLayer = lastControllerLayer;
             RenderSettings.ambientMode = lastAmbientMode;
         }
References Juniper.Unity.Display.AbstractDisplayManager.ARMode, Juniper.Unity.Display.AbstractDisplayManager.BackgroundColor, Juniper.Unity.Display.AbstractDisplayManager.ClearFlags, Juniper.Unity.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Unity.Display.AbstractDisplayManager.CullingMask, Juniper.Unity.Animation.FadeTransition.display, Juniper.Unity.Animation.FadeTransition.input, Juniper.Unity.Animation.FadeTransition.lastAmbientMode, Juniper.Unity.Animation.FadeTransition.lastCameraCullingMask, Juniper.Unity.Animation.FadeTransition.lastColor, and Juniper.Unity.Animation.FadeTransition.lastControllerLayer.
Reinstall()
virtual void Juniper.Unity.Animation.FadeTransition.Reinstall () inline virtual
Resets the object to its initial state.
Implements Juniper.IInstallable.
Definition at line 107 of file FadeTransition.cs.
         {
             Install(true);
         }
References Juniper.Unity.Animation.FadeTransition.Install().
RenderValue()
override void Juniper.Unity.Animation.FadeTransition.RenderValue (float value) inline protected virtual
As the fade transition updates, sets the opacity of the view blocker graphic.
Parameters
value
Implements Juniper.Unity.Animation.AbstractTransitionController.
Definition at line 155 of file FadeTransition.cs.
         {
             if (props != null)
             {
                 props.SetFloat("_Alpha", Mathf.Clamp01(value));
                 r.SetPropertyBlock(props);
             }
         }
References Juniper.Unity.Animation.FadeTransition.props, and Juniper.Unity.Animation.FadeTransition.r.
SkipEnter()
override void Juniper.Unity.Animation.AbstractTransitionController.SkipEnter () inline virtual inherited
Jump the transition to the ENTERED state, without animating through the ENTERING state.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 74 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.SkipEnter();
             SetProgress(0);
         }
References Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut().
SkipExit()
virtual void Juniper.Unity.AbstractStateController.SkipExit () inline virtual inherited
Jump to the fully entered state without firing any events.
Definition at line 254 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnExiting(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
Uninstall()
void Juniper.Unity.Animation.FadeTransition.Uninstall () inline
There are no components to uninstall from this component.
Implements Juniper.IInstallable.
Definition at line 147 of file FadeTransition.cs.
         {
         }
Update()
override void Juniper.Unity.Animation.AbstractTransitionController.Update () inline virtual inherited
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented from Juniper.Unity.AbstractStateController.
Reimplemented in Juniper.Unity.Animation.SpiralTransition.
Definition at line 95 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress > 0)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress - change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     SetProgress(0);
                     state = Direction.Stopped;
                 }
             }
             base.Update();
         }
References Juniper.Unity.Animation.AbstractTransitionController.attack, Juniper.Unity.AbstractStateController.IsRunning, Juniper.Unity.Animation.AbstractTransitionController.progress, Juniper.Unity.Animation.AbstractTransitionController.release, Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.state, and Juniper.Unity.Animation.AbstractTransitionController.TransitionLength.
Member Data Documentation
actions
readonly List<Action> Juniper.Unity.Animation.FadeTransition.actions = new List<Action>(5) private
A queue of actions to perform when the fader has finished fading out, before it fades back in.
Definition at line 178 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Fader(), and Juniper.Unity.Animation.FadeTransition.OnEntered().
attackTime
float Juniper.Unity.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 20 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
aud
AudioSource Juniper.Unity.Animation.FadeTransition.aud private
The audio source on which to play the fade-in/fade-out sounds.
Definition at line 38 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Unity.Animation.FadeTransition.Install(), Juniper.Unity.Animation.FadeTransition.OnEntered(), and Juniper.Unity.Animation.FadeTransition.OnExited().
display
DisplayManager Juniper.Unity.Animation.FadeTransition.display private
Used to check the current ARMode to determine how to restore the camera clear mode.
Definition at line 21 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), Juniper.Unity.Animation.FadeTransition.OnEntered(), and Juniper.Unity.Animation.FadeTransition.OnExiting().
fadeInSound
AudioClip Juniper.Unity.Animation.FadeTransition.fadeInSound
The sound to play when the view fades back in.
Definition at line 33 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Install(), and Juniper.Unity.Animation.FadeTransition.OnEntered().
fadeLength
float Juniper.Unity.Animation.FadeTransition.fadeLength = 0.25f
If Unity's audio subsystem is not available, or the fade-in/fade-out sounds are not configured, this is the default length of time to run the fade-in/fade-out transition.
Definition at line 46 of file FadeTransition.cs.
fadeOutSound
AudioClip Juniper.Unity.Animation.FadeTransition.fadeOutSound
The sound to play when the view fades out.
Definition at line 28 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Install(), and Juniper.Unity.Animation.FadeTransition.OnExited().
input
UnifiedInputModule Juniper.Unity.Animation.FadeTransition.input private
Definition at line 64 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), Juniper.Unity.Animation.FadeTransition.OnEntered(), and Juniper.Unity.Animation.FadeTransition.OnExiting().
lastAmbientMode
AmbientMode Juniper.Unity.Animation.FadeTransition.lastAmbientMode private
The ambient light mode that was used before the fade-out transition was started.
Definition at line 222 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.OnEntered(), and Juniper.Unity.Animation.FadeTransition.OnExiting().
lastCameraCullingMask
int Juniper.Unity.Animation.FadeTransition.lastCameraCullingMask private
The culling-mask that was used before the fade-out transition started.
Definition at line 211 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.OnEntered(), and Juniper.Unity.Animation.FadeTransition.OnExiting().
lastColor
Color Juniper.Unity.Animation.FadeTransition.lastColor private
The clear-color that was used before the fade-out transition started.
Definition at line 206 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.OnEntered(), and Juniper.Unity.Animation.FadeTransition.OnExiting().
lastControllerLayer
int Juniper.Unity.Animation.FadeTransition.lastControllerLayer private
The layers the controllers are rendered on. This is used to make sure the controllers are still visible while the scene is faded out.
Definition at line 217 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.OnEntered(), and Juniper.Unity.Animation.FadeTransition.OnExiting().
onEntered
UnityEvent Juniper.Unity.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 35 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.Unity.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 26 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.Unity.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 53 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.Unity.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 44 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
onValueChanged
UnityEvent Juniper.Unity.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 33 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
props
MaterialPropertyBlock Juniper.Unity.Animation.FadeTransition.props private
Used to change values in the material, without globally changing the material.
Definition at line 172 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.Animation.FadeTransition.RenderValue().
r
Renderer Juniper.Unity.Animation.FadeTransition.r private
The renderer for the current object.
Definition at line 167 of file FadeTransition.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.Animation.FadeTransition.RenderValue().
releaseTime
float Juniper.Unity.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 27 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
state
Direction Juniper.Unity.AbstractStateController.state inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 96 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), Juniper.Unity.Animation.AbstractTransitionController.Update(), and Juniper.Unity.AbstractStateController.Update().
tween
TweenType Juniper.Unity.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 38 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
tweenK
float Juniper.Unity.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 45 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
Property Documentation
IsComplete
virtual bool Juniper.Unity.AbstractStateController.IsComplete get inherited
Returns true when state is Direction.Stopped
Definition at line 112 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.HasCompleted(), and Juniper.Unity.AbstractStateController.Update().
IsEntered
bool Juniper.Unity.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 143 of file AbstractStateController.cs.
         {
             get
             {
                 return isActiveAndEnabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Exit().
IsExited
bool Juniper.Unity.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 154 of file AbstractStateController.cs.
         {
             get
             {
                 return !isActiveAndEnabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Enter().
IsRunning
bool Juniper.Unity.AbstractStateController.IsRunning get inherited
Returns true when state is not Direction.Stopped
Definition at line 132 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
TransitionLength
override float???? Juniper.Unity.Animation.FadeTransition.TransitionLength get
The amount of time the fade transition takes to complete. If a fade sound is provided, this will be based on the length of the sound clip. Otherwise, it's 1/4th of a second.
Definition at line 53 of file FadeTransition.cs.
         {
             get
             {
                 return
 #if UNITY_MODULES_AUDIO
                     aud?.clip?.length ??
 #endif
                     fadeLength;
             }
         }
Waiter
WaitUntil Juniper.Unity.AbstractStateController.Waiter get inherited
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 331 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.Unity.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 71 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.Unity.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 62 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.Unity.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 89 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.Unity.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 80 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnExiting().
ValueChanged
EventHandler<ValueChangedEventArgs> Juniper.Unity.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 51 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Animation/FadeTransition.cs