Juniper: Juniper.Console.ConsoleBuffer Class Reference
Juniper.Console.ConsoleBuffer Class Reference
Classes
class NativeMethods
Public Member Functions
ConsoleBuffer (int gridSize)
ConsoleBuffer (int gridSize, int width, int height)
bool IsInBounds (int x, int y)
Determine if a point is within the bounds of the board
ConsoleColor GetBackgroundColor (int x, int y)
void Draw (int x, int y, char c, ConsoleColor f, ConsoleColor b)
void Flush ()
void Prompt (string message, bool pause)
Static Public Member Functions
static bool IsKeyDown (int key)
static void SetFont (int index)
static void SetFont (string fontFace)
static void SetFontSize (int width, int height)
Public Attributes
int AbsoluteLeft => 0
int AbsoluteRight => Width - 1
int AbsoluteTop => 0
int AbsoluteBottom => Height - 1
int Width => grid1?.GetWidth() ?? -1
int Height => grid1?.GetHeight() ?? -1
Static Public Attributes
static int x
static bool ExtendedModeEnabled
Properties
static int int y CursorPosition [get]
static bool EchoInputEnabled [get, set]
static bool InsertEnabled [get, set]
static bool LineInputEnabled [get, set]
static bool MouseInputEnabled [get, set]
static bool ProcessedInputEnabled [get, set]
static bool ProcessedOutputEnabled [get, set]
static bool WrapAtEOLEnabled [get, set]
static bool QuickEditModeEnabled [get, set]
static bool WindowInputEnabled [get, set]
static bool VirtualTerminalInputEnabled [get, set]
static bool VirtualTerminalProcessingEnabled [get, set]
static bool NewLineAutoReturnEnabled [get, set]
static bool LVBGridWorldWideEnabled [get, set]
Events
EventHandler< SizeChangedEventArgs > SizeChanged
Private Member Functions
internal ConsoleBuffer (int gridSize, NativeMethods.COORD size)
void ConsoleBuffer_CancelKeyPress (object sender, ConsoleCancelEventArgs e)
~ConsoleBuffer ()
void Teardown ()
void CheckGrids ()
Static Private Member Functions
static void CheckCursor (int x, int y)
static bool IsConsoleModeEnabled (IntPtr handle, NativeMethods.CONSOLE_MODES desiredMode)
static void SetConsoleModeEnabled (IntPtr handle, NativeMethods.CONSOLE_MODES addMode, bool enabled)
Private Attributes
readonly ConsoleColor startFore
readonly ConsoleColor startBack
ConsoleColor lastBack
ConsoleColor lastFore
ConsoleColor [,] back1
ConsoleColor [,] back2
ConsoleColor [,] fore1
ConsoleColor [,] fore2
char [,] grid1
char [,] grid2
Static Private Attributes
static readonly bool IsWindows
static readonly IntPtr outputHandle
static readonly IntPtr inputHandle
Detailed Description
Definition at line 10 of file ConsoleBuffer.cs.
Constructor & Destructor Documentation
ConsoleBuffer() [1/3]
Juniper.Console.ConsoleBuffer.ConsoleBuffer (int gridSize) inline
Definition at line 50 of file ConsoleBuffer.cs.
             : this(gridSize, WindowWidth, WindowHeight - 1)
         { }
ConsoleBuffer() [2/3]
internal Juniper.Console.ConsoleBuffer.ConsoleBuffer (int gridSize, NativeMethods.COORD size) inline private
Definition at line 54 of file ConsoleBuffer.cs.
             : this(gridSize, size.X, size.Y)
         { }
ConsoleBuffer() [3/3]
Juniper.Console.ConsoleBuffer.ConsoleBuffer (int gridSize, int width, int height) inline
Definition at line 58 of file ConsoleBuffer.cs.
         {
             if (IsWindows)
             {
                 SetFontSize(gridSize, gridSize);
             }
             width = Math.Min(width, LargestWindowWidth);
             height = Math.Min(height, LargestWindowHeight - 1);
             OutputEncoding = Encoding.Unicode;
             lastFore = startFore = ForegroundColor;
             lastBack = startBack = BackgroundColor;
             SetWindowSize(width, height + 1);
             SetBufferSize(width, height + 1);
             SetWindowPosition(0, 0);
             CheckGrids();
         }
References Juniper.Console.ConsoleBuffer.CheckGrids(), Juniper.Console.ConsoleBuffer.IsWindows, Juniper.Console.ConsoleBuffer.lastBack, Juniper.Console.ConsoleBuffer.lastFore, Juniper.Console.ConsoleBuffer.SetFontSize(), Juniper.Console.ConsoleBuffer.startBack, and Juniper.Console.ConsoleBuffer.startFore.
~ConsoleBuffer()
Juniper.Console.ConsoleBuffer.~ConsoleBuffer () inline private
Definition at line 86 of file ConsoleBuffer.cs.
         {
             Teardown();
         }
References Juniper.Console.ConsoleBuffer.Teardown().
Member Function Documentation
CheckCursor()
static void Juniper.Console.ConsoleBuffer.CheckCursor (int x, int y) inline static private
Definition at line 204 of file ConsoleBuffer.cs.
         {
             var rowChanged = y != CursorTop;
             var colChanged = x != CursorLeft;
             if (rowChanged && colChanged)
             {
                 SetCursorPosition(x, y);
             }
             else if (colChanged)
             {
                 CursorLeft = x;
             }
             else if (rowChanged)
             {
                 CursorTop = y;
             }
         }
References Juniper.Console.ConsoleBuffer.x.
Referenced by Juniper.Console.ConsoleBuffer.Flush().
CheckGrids()
void Juniper.Console.ConsoleBuffer.CheckGrids () inline private
Definition at line 121 of file ConsoleBuffer.cs.
         {
             var oldWidth = Width;
             var oldHeight = Height;
             var newWidth = WindowWidth;
             var newHeight = WindowHeight - 1;
             if (newWidth != oldWidth
                 || newHeight != oldHeight)
             {
                 var lastBack1 = back1;
                 var lastBack2 = back2;
                 var lastFore1 = fore1;
                 var lastFore2 = fore2;
                 var lastGrid1 = grid1;
                 var lastGrid2 = grid2;
                 back1 = new ConsoleColor[newWidth, newHeight];
                 back2 = new ConsoleColor[newWidth, newHeight];
                 fore1 = new ConsoleColor[newWidth, newHeight];
                 fore2 = new ConsoleColor[newWidth, newHeight];
                 grid1 = new char[newWidth, newHeight];
                 grid2 = new char[newWidth, newHeight];
                 Clear();
                 CursorVisible = false;
                 SizeChanged?.Invoke(this, new SizeChangedEventArgs(oldWidth, oldHeight, newWidth, newHeight));
             }
         }
References Juniper.Console.ConsoleBuffer.back1, Juniper.Console.ConsoleBuffer.back2, Juniper.Console.ConsoleBuffer.fore1, Juniper.Console.ConsoleBuffer.fore2, Juniper.Console.ConsoleBuffer.grid1, Juniper.Console.ConsoleBuffer.grid2, Juniper.Console.ConsoleBuffer.Height, Juniper.Console.ConsoleBuffer.SizeChanged, and Juniper.Console.ConsoleBuffer.Width.
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer(), and Juniper.Console.ConsoleBuffer.Flush().
ConsoleBuffer_CancelKeyPress()
void Juniper.Console.ConsoleBuffer.ConsoleBuffer_CancelKeyPress (object sender, ConsoleCancelEventArgs e) inline private
Definition at line 80 of file ConsoleBuffer.cs.
         {
             Teardown();
             e.Cancel = true;
         }
References Juniper.Console.ConsoleBuffer.Teardown().
Draw()
void Juniper.Console.ConsoleBuffer.Draw (int x, int y, char c, ConsoleColor f, ConsoleColor b) inline
Implements Juniper.Console.IConsoleBuffer.
Definition at line 151 of file ConsoleBuffer.cs.
         {
             if (IsInBounds(x, y))
             {
                 back1[x, y] = b;
                 fore1[x, y] = f;
                 grid1[x, y] = c;
             }
         }
References Juniper.Console.ConsoleBuffer.back1, Juniper.Console.ConsoleBuffer.fore1, Juniper.Console.ConsoleBuffer.grid1, Juniper.Console.ConsoleBuffer.IsInBounds(), and Juniper.Console.ConsoleBuffer.x.
Referenced by Juniper.Console.ConsoleBuffer.Prompt().
Flush()
void Juniper.Console.ConsoleBuffer.Flush () inline
Definition at line 161 of file ConsoleBuffer.cs.
         {
             for (var y = 0; y < Height; ++y)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     var changed = grid1[x, y] != grid2[x, y]
                         || fore1[x, y] != fore2[x, y]
                         || back1[x, y] != back2[x, y];
                     if (changed)
                     {
                         CheckCursor(x, y);
                         if (fore1[x, y] != lastFore)
{
                             lastFore = ForegroundColor = fore1[x, y];
                         }
                         if (back1[x, y] != lastBack)
{
                             lastBack = BackgroundColor = back1[x, y];
                         }
                         if (x < Width - 1)
{
                             Write(grid1[x, y]);
                         }
                         else
{
                             WriteLine(grid1[x, y]);
                         }
                     }
                     fore2[x, y] = fore1[x, y];
                     back2[x, y] = back1[x, y];
                     grid2[x, y] = grid1[x, y];
                 }
             }
             CheckGrids();
         }
References Juniper.Console.ConsoleBuffer.back1, Juniper.Console.ConsoleBuffer.back2, Juniper.Console.ConsoleBuffer.CheckCursor(), Juniper.Console.ConsoleBuffer.CheckGrids(), Juniper.Console.ConsoleBuffer.fore1, Juniper.Console.ConsoleBuffer.fore2, Juniper.Console.ConsoleBuffer.grid1, Juniper.Console.ConsoleBuffer.grid2, Juniper.Console.ConsoleBuffer.Height, Juniper.Console.ConsoleBuffer.lastBack, Juniper.Console.ConsoleBuffer.lastFore, Juniper.Console.ConsoleBuffer.Width, and Juniper.Console.ConsoleBuffer.x.
Referenced by Juniper.Console.ConsoleBuffer.Prompt().
GetBackgroundColor()
ConsoleColor Juniper.Console.ConsoleBuffer.GetBackgroundColor (int x, int y) inline
Implements Juniper.Console.IConsoleBuffer.
Definition at line 109 of file ConsoleBuffer.cs.
         {
             if (IsInBounds(x, y))
             {
                 return back1[x, y];
             }
             else
             {
                 return ConsoleColor.Black;
             }
         }
References Juniper.Console.ConsoleBuffer.back1, Juniper.Console.ConsoleBuffer.IsInBounds(), and Juniper.Console.ConsoleBuffer.x.
IsConsoleModeEnabled()
static bool Juniper.Console.ConsoleBuffer.IsConsoleModeEnabled (IntPtr handle, NativeMethods.CONSOLE_MODES desiredMode) inline static private
Definition at line 338 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return false;
             }
             if (!NativeMethods.GetConsoleMode(handle, out var mode))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
             return (mode & desiredMode) != 0;
         }
References Juniper.Console.ConsoleBuffer.NativeMethods.GetConsoleMode(), and Juniper.Console.ConsoleBuffer.IsWindows.
IsInBounds()
bool Juniper.Console.ConsoleBuffer.IsInBounds (int x, int y) inline
Determine if a point is within the bounds of the board
Parameters
x
y
Returns
Definition at line 103 of file ConsoleBuffer.cs.
         {
             return x >= 0 && x < Width
                 && y >= 0 && y < Height;
         }
References Juniper.Console.ConsoleBuffer.Height, Juniper.Console.ConsoleBuffer.Width, and Juniper.Console.ConsoleBuffer.x.
Referenced by Juniper.Console.ConsoleBuffer.Draw(), and Juniper.Console.ConsoleBuffer.GetBackgroundColor().
IsKeyDown()
static bool Juniper.Console.ConsoleBuffer.IsKeyDown (int key) inline static
Definition at line 241 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return false;
             }
             return NativeMethods.GetKeyState(key) < 0;
         }
References Juniper.Console.ConsoleBuffer.NativeMethods.GetKeyState(), and Juniper.Console.ConsoleBuffer.IsWindows.
Prompt()
void Juniper.Console.ConsoleBuffer.Prompt (string message, bool pause) inline
Definition at line 222 of file ConsoleBuffer.cs.
         {
             if (message is null)
             {
                 throw new ArgumentNullException(nameof(message));
             }
             this.Draw(0, Height - 1, message, ConsoleColor.Red, ConsoleColor.DarkRed);
             Flush();
             CursorLeft = message.Length;
             CursorTop = Height - 1;
             if (pause)
             {
                 _ = ReadKey(true);
             }
         }
References Juniper.Console.ConsoleBuffer.Draw(), Juniper.Console.ConsoleBuffer.Flush(), and Juniper.Console.ConsoleBuffer.Height.
SetConsoleModeEnabled()
static void Juniper.Console.ConsoleBuffer.SetConsoleModeEnabled (IntPtr handle, NativeMethods.CONSOLE_MODES addMode, bool enabled) inline static private
Definition at line 353 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return;
             }
             if (!NativeMethods.GetConsoleMode(handle, out var curMode))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
             var nextMode = curMode;
             if (enabled)
             {
                 nextMode |= addMode;
             }
             else
             {
                 nextMode &= ~addMode;
             }
             if (!NativeMethods.SetConsoleMode(outputHandle, nextMode))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
         }
References Juniper.Console.ConsoleBuffer.NativeMethods.GetConsoleMode(), Juniper.Console.ConsoleBuffer.IsWindows, Juniper.Console.ConsoleBuffer.outputHandle, and Juniper.Console.ConsoleBuffer.NativeMethods.SetConsoleMode().
SetFont() [1/2]
static void Juniper.Console.ConsoleBuffer.SetFont (int index) inline static
Definition at line 265 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return;
             }
             var info = new NativeMethods.CONSOLE_FONT_INFO_EX();
             info.cbSize = (uint)Marshal.SizeOf(info);
             info.nFont = (uint)index;
             if (!NativeMethods.SetCurrentConsoleFontEx(outputHandle, false, info))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
         }
References Juniper.Console.ConsoleBuffer.NativeMethods.CONSOLE_FONT_INFO_EX.cbSize, Juniper.Console.ConsoleBuffer.IsWindows, Juniper.Console.ConsoleBuffer.outputHandle, and Juniper.Console.ConsoleBuffer.NativeMethods.SetCurrentConsoleFontEx().
SetFont() [2/2]
static void Juniper.Console.ConsoleBuffer.SetFont (string fontFace) inline static
Definition at line 281 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return;
             }
             if (fontFace is null)
             {
                 throw new ArgumentNullException(nameof(fontFace));
             }
             unsafe
             {
                 var info = new NativeMethods.CONSOLE_FONT_INFO_EX();
                 info.cbSize = (uint)Marshal.SizeOf(info);
                 if (!NativeMethods.GetCurrentConsoleFontEx(outputHandle, false, ref info))
                 {
                     throw new Win32Exception(Marshal.GetLastWin32Error());
                 }
                 var curFontFace = string.Intern(new string(info.FaceName));
                 if (curFontFace != fontFace)
                 {
                     var newInfo = new NativeMethods.CONSOLE_FONT_INFO_EX();
                     newInfo.cbSize = (uint)Marshal.SizeOf(newInfo);
                     newInfo.FontFamily = NativeMethods.TMPF_TRUETYPE;
                     var ptr = new IntPtr(newInfo.FaceName);
                     Marshal.Copy(fontFace.ToCharArray(), 0, ptr, fontFace.Length);
                     var size = Math.Max(info.dwFontSize.X, info.dwFontSize.Y);
                     newInfo.dwFontSize = new NativeMethods.COORD(size, size);
                     newInfo.FontWeight = info.FontWeight;
                     if (!NativeMethods.SetCurrentConsoleFontEx(outputHandle, false, newInfo))
                     {
                         throw new Win32Exception(Marshal.GetLastWin32Error());
                     }
                 }
             }
         }
References Juniper.Console.ConsoleBuffer.NativeMethods.CONSOLE_FONT_INFO_EX.cbSize, Juniper.Console.ConsoleBuffer.NativeMethods.GetCurrentConsoleFontEx(), Juniper.Console.ConsoleBuffer.IsWindows, Juniper.Console.ConsoleBuffer.outputHandle, Juniper.Console.ConsoleBuffer.NativeMethods.SetCurrentConsoleFontEx(), and Juniper.Console.ConsoleBuffer.NativeMethods.TMPF_TRUETYPE.
SetFontSize()
static void Juniper.Console.ConsoleBuffer.SetFontSize (int width, int height) inline static
Definition at line 321 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return;
             }
             var info = new NativeMethods.CONSOLE_FONT_INFO_EX();
             info.cbSize = (uint)Marshal.SizeOf(info);
             info.dwFontSize.X = (short)width;
             info.dwFontSize.Y = (short)height;
             if (!NativeMethods.SetCurrentConsoleFontEx(outputHandle, false, info))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
         }
References Juniper.Console.ConsoleBuffer.NativeMethods.CONSOLE_FONT_INFO_EX.cbSize, Juniper.Console.ConsoleBuffer.IsWindows, Juniper.Console.ConsoleBuffer.outputHandle, and Juniper.Console.ConsoleBuffer.NativeMethods.SetCurrentConsoleFontEx().
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer().
Teardown()
void Juniper.Console.ConsoleBuffer.Teardown () inline private
Definition at line 91 of file ConsoleBuffer.cs.
         {
             ForegroundColor = startFore;
             BackgroundColor = startBack;
         }
References Juniper.Console.ConsoleBuffer.startBack, and Juniper.Console.ConsoleBuffer.startFore.
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer_CancelKeyPress(), and Juniper.Console.ConsoleBuffer.~ConsoleBuffer().
Member Data Documentation
AbsoluteBottom
int Juniper.Console.ConsoleBuffer.AbsoluteBottom => Height - 1
Definition at line 44 of file ConsoleBuffer.cs.
AbsoluteLeft
int Juniper.Console.ConsoleBuffer.AbsoluteLeft => 0
Definition at line 41 of file ConsoleBuffer.cs.
AbsoluteRight
int Juniper.Console.ConsoleBuffer.AbsoluteRight => Width - 1
Definition at line 42 of file ConsoleBuffer.cs.
AbsoluteTop
int Juniper.Console.ConsoleBuffer.AbsoluteTop => 0
Definition at line 43 of file ConsoleBuffer.cs.
back1
ConsoleColor [,] Juniper.Console.ConsoleBuffer.back1 private
Definition at line 34 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), Juniper.Console.ConsoleBuffer.Draw(), Juniper.Console.ConsoleBuffer.Flush(), and Juniper.Console.ConsoleBuffer.GetBackgroundColor().
back2
ConsoleColor [,] Juniper.Console.ConsoleBuffer.back2 private
Definition at line 35 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), and Juniper.Console.ConsoleBuffer.Flush().
ExtendedModeEnabled
bool Juniper.Console.ConsoleBuffer.ExtendedModeEnabled static
Initial value:
=>
            IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_EXTENDED_FLAGS)
Definition at line 484 of file ConsoleBuffer.cs.
fore1
ConsoleColor [,] Juniper.Console.ConsoleBuffer.fore1 private
Definition at line 36 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), Juniper.Console.ConsoleBuffer.Draw(), and Juniper.Console.ConsoleBuffer.Flush().
fore2
ConsoleColor [,] Juniper.Console.ConsoleBuffer.fore2 private
Definition at line 37 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), and Juniper.Console.ConsoleBuffer.Flush().
grid1
char [,] Juniper.Console.ConsoleBuffer.grid1 private
Definition at line 38 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), Juniper.Console.ConsoleBuffer.Draw(), and Juniper.Console.ConsoleBuffer.Flush().
grid2
char [,] Juniper.Console.ConsoleBuffer.grid2 private
Definition at line 39 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), and Juniper.Console.ConsoleBuffer.Flush().
Height
int Juniper.Console.ConsoleBuffer.Height => grid1?.GetHeight() ?? -1
Definition at line 46 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), Juniper.Console.ConsoleBuffer.Flush(), Juniper.Console.ConsoleBuffer.IsInBounds(), and Juniper.Console.ConsoleBuffer.Prompt().
inputHandle
readonly IntPtr Juniper.Console.ConsoleBuffer.inputHandle static private
Initial value:
= IsWindows
            ? NativeMethods.GetStdHandle(NativeMethods.STD_INPUT_HANDLE)
            : NativeMethods.INVALID_HANDLE_VALUE
Definition at line 26 of file ConsoleBuffer.cs.
IsWindows
readonly bool Juniper.Console.ConsoleBuffer.IsWindows static private
Initial value:
= Environment.OSVersion.Platform == PlatformID.Win32NT
            || Environment.OSVersion.Platform == PlatformID.Win32S
            || Environment.OSVersion.Platform == PlatformID.Win32Windows
            || Environment.OSVersion.Platform == PlatformID.WinCE
Definition at line 14 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer(), Juniper.Console.ConsoleBuffer.IsConsoleModeEnabled(), Juniper.Console.ConsoleBuffer.IsKeyDown(), Juniper.Console.ConsoleBuffer.SetConsoleModeEnabled(), Juniper.Console.ConsoleBuffer.SetFont(), and Juniper.Console.ConsoleBuffer.SetFontSize().
lastBack
ConsoleColor Juniper.Console.ConsoleBuffer.lastBack private
Definition at line 32 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer(), and Juniper.Console.ConsoleBuffer.Flush().
lastFore
ConsoleColor Juniper.Console.ConsoleBuffer.lastFore private
Definition at line 33 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer(), and Juniper.Console.ConsoleBuffer.Flush().
outputHandle
readonly IntPtr Juniper.Console.ConsoleBuffer.outputHandle static private
Initial value:
= IsWindows
            ? NativeMethods.GetStdHandle(NativeMethods.STD_OUTPUT_HANDLE)
            : NativeMethods.INVALID_HANDLE_VALUE
Definition at line 22 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.SetConsoleModeEnabled(), Juniper.Console.ConsoleBuffer.SetFont(), and Juniper.Console.ConsoleBuffer.SetFontSize().
startBack
readonly ConsoleColor Juniper.Console.ConsoleBuffer.startBack private
Definition at line 31 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer(), and Juniper.Console.ConsoleBuffer.Teardown().
startFore
readonly ConsoleColor Juniper.Console.ConsoleBuffer.startFore private
Definition at line 30 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.ConsoleBuffer(), and Juniper.Console.ConsoleBuffer.Teardown().
Width
int Juniper.Console.ConsoleBuffer.Width => grid1?.GetWidth() ?? -1
Definition at line 45 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids(), Juniper.Console.ConsoleBuffer.Flush(), and Juniper.Console.ConsoleBuffer.IsInBounds().
x
int Juniper.Console.ConsoleBuffer.x static
Definition at line 251 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckCursor(), Juniper.Console.ConsoleBuffer.NativeMethods.COORD.COORD(), Juniper.Console.ConsoleBuffer.Draw(), Juniper.Console.ConsoleBuffer.Flush(), Juniper.Console.ConsoleBuffer.GetBackgroundColor(), Juniper.Console.ConsoleBuffer.IsInBounds(), and Juniper.Console.ConsoleBuffer.NativeMethods.POINT.POINT().
Property Documentation
CursorPosition
int int y Juniper.Console.ConsoleBuffer.CursorPosition static get private
Definition at line 252 of file ConsoleBuffer.cs.
         {
             get
             {
                 if (!IsWindows
                     || !NativeMethods.GetCursorPos(out var point))
                 {
                     return default;
                 }
                 return (point.X, point.Y);
             }
         }
EchoInputEnabled
bool Juniper.Console.ConsoleBuffer.EchoInputEnabled static get set
Definition at line 382 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_ECHO_INPUT);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_ECHO_INPUT, value);
             }
         }
InsertEnabled
bool Juniper.Console.ConsoleBuffer.InsertEnabled static get set
Definition at line 395 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_INSERT_MODE);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_INSERT_MODE | NativeMethods.CONSOLE_MODES.ENABLE_EXTENDED_FLAGS, value);
             }
         }
LineInputEnabled
bool Juniper.Console.ConsoleBuffer.LineInputEnabled static get set
Definition at line 408 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_LINE_INPUT);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_LINE_INPUT, value);
             }
         }
LVBGridWorldWideEnabled
bool Juniper.Console.ConsoleBuffer.LVBGridWorldWideEnabled static get set
Definition at line 540 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_LVB_GRID_WORLDWIDE);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_LVB_GRID_WORLDWIDE, value);
             }
         }
MouseInputEnabled
bool Juniper.Console.ConsoleBuffer.MouseInputEnabled static get set
Definition at line 421 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_MOUSE_INPUT);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_MOUSE_INPUT, value);
             }
         }
NewLineAutoReturnEnabled
bool Juniper.Console.ConsoleBuffer.NewLineAutoReturnEnabled static get set
Definition at line 527 of file ConsoleBuffer.cs.
         {
             get
             {
                 return !IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.DISABLE_NEWLINE_AUTO_RETURN);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.DISABLE_NEWLINE_AUTO_RETURN, !value);
             }
         }
ProcessedInputEnabled
bool Juniper.Console.ConsoleBuffer.ProcessedInputEnabled static get set
Definition at line 434 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_PROCESSED_INPUT);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_PROCESSED_INPUT, value);
             }
         }
ProcessedOutputEnabled
bool Juniper.Console.ConsoleBuffer.ProcessedOutputEnabled static get set
Definition at line 447 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(outputHandle, NativeMethods.CONSOLE_MODES.ENABLE_PROCESSED_OUTPUT);
             }
             set
             {
                 SetConsoleModeEnabled(outputHandle, NativeMethods.CONSOLE_MODES.ENABLE_PROCESSED_OUTPUT, value);
             }
         }
QuickEditModeEnabled
bool Juniper.Console.ConsoleBuffer.QuickEditModeEnabled static get set
Definition at line 472 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_QUICK_EDIT_MODE);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_QUICK_EDIT_MODE | NativeMethods.CONSOLE_MODES.ENABLE_EXTENDED_FLAGS, value);
             }
         }
VirtualTerminalInputEnabled
bool Juniper.Console.ConsoleBuffer.VirtualTerminalInputEnabled static get set
Definition at line 501 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_VIRTUAL_TERMINAL_INPUT);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_VIRTUAL_TERMINAL_INPUT, value);
             }
         }
VirtualTerminalProcessingEnabled
bool Juniper.Console.ConsoleBuffer.VirtualTerminalProcessingEnabled static get set
Definition at line 514 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_VIRTUAL_TERMINAL_PROCESSING);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_VIRTUAL_TERMINAL_PROCESSING, value);
             }
         }
WindowInputEnabled
bool Juniper.Console.ConsoleBuffer.WindowInputEnabled static get set
Definition at line 488 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_WINDOW_INPUT);
             }
             set
             {
                 SetConsoleModeEnabled(inputHandle, NativeMethods.CONSOLE_MODES.ENABLE_WINDOW_INPUT, value);
             }
         }
WrapAtEOLEnabled
bool Juniper.Console.ConsoleBuffer.WrapAtEOLEnabled static get set
Definition at line 460 of file ConsoleBuffer.cs.
         {
             get
             {
                 return IsConsoleModeEnabled(outputHandle, NativeMethods.CONSOLE_MODES.ENABLE_WRAP_AT_EOL_OUTPUT);
             }
             set
             {
                 SetConsoleModeEnabled(outputHandle, NativeMethods.CONSOLE_MODES.ENABLE_WRAP_AT_EOL_OUTPUT, value);
             }
         }
Event Documentation
SizeChanged
EventHandler<SizeChangedEventArgs> Juniper.Console.ConsoleBuffer.SizeChanged
Definition at line 48 of file ConsoleBuffer.cs.
Referenced by Juniper.Console.ConsoleBuffer.CheckGrids().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Console/ConsoleBuffer.cs