Juniper: Juniper.Processes.AbstractShellCommand Class Reference
Juniper.Processes.AbstractShellCommand Class Reference
Public Member Functions
Task< int > RunAsync ()
int Run ()
Protected Member Functions
AbstractShellCommand (string command)
virtual async Task< int > RunAsync (IEnumerable< string > arguments)
Properties
bool UseShellExecute [get, set]
bool LoadUserProfile [get, set]
Encoding Encoding [get, set]
string TotalStandardOutput [get, private set]
string TotalStandardError [get, private set]
abstract IEnumerable< string > Arguments [get]
Events
EventHandler< StringEventArgs > Info
EventHandler< StringEventArgs > Warning
EventHandler< ErrorEventArgs > Err
Private Member Functions
void Proc_OutputDataReceived (object sender, DataReceivedEventArgs e)
void Proc_ErrorDataReceived (object sender, DataReceivedEventArgs e)
void OnInfo (string message)
void OnWarning (string message)
void OnError (Exception exp)
Private Attributes
readonly string command
Detailed Description
Definition at line 13 of file AbstractShellCommand.cs.
Constructor & Destructor Documentation
AbstractShellCommand()
Juniper.Processes.AbstractShellCommand.AbstractShellCommand (string command) inline protected
Definition at line 32 of file AbstractShellCommand.cs.
         {
             if (command is null)
             {
                 throw new ArgumentNullException(nameof(command));
             }
             if (command.Length == 0)
             {
                 throw new InvalidOperationException($"{nameof(command)} cannot be an empty string.");
             }
             this.command = command;
         }
References Juniper.Processes.AbstractShellCommand.command.
Member Function Documentation
OnError()
void Juniper.Processes.AbstractShellCommand.OnError (Exception exp) inline private
Definition at line 159 of file AbstractShellCommand.cs.
         {
             Err?.Invoke(this, new ErrorEventArgs(exp));
         }
References Juniper.Processes.AbstractShellCommand.Err.
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
OnInfo()
void Juniper.Processes.AbstractShellCommand.OnInfo (string message) inline private
Definition at line 147 of file AbstractShellCommand.cs.
         {
             Info?.Invoke(this, new StringEventArgs(message));
         }
References Juniper.Processes.AbstractShellCommand.Info.
Referenced by Juniper.Processes.AbstractShellCommand.Proc_OutputDataReceived().
OnWarning()
void Juniper.Processes.AbstractShellCommand.OnWarning (string message) inline private
Definition at line 153 of file AbstractShellCommand.cs.
         {
             Warning?.Invoke(this, new StringEventArgs(message));
         }
References Juniper.Processes.AbstractShellCommand.Warning.
Referenced by Juniper.Processes.AbstractShellCommand.Proc_ErrorDataReceived().
Proc_ErrorDataReceived()
void Juniper.Processes.AbstractShellCommand.Proc_ErrorDataReceived (object sender, DataReceivedEventArgs e) inline private
Definition at line 141 of file AbstractShellCommand.cs.
         {
             OnWarning(e.Data);
         }
References Juniper.Processes.AbstractShellCommand.OnWarning().
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
Proc_OutputDataReceived()
void Juniper.Processes.AbstractShellCommand.Proc_OutputDataReceived (object sender, DataReceivedEventArgs e) inline private
Definition at line 136 of file AbstractShellCommand.cs.
         {
             OnInfo(e.Data);
         }
References Juniper.Processes.AbstractShellCommand.OnInfo().
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
Run()
int Juniper.Processes.AbstractShellCommand.Run () inline
Definition at line 58 of file AbstractShellCommand.cs.
         {
             return RunAsync().Result;
         }
References Juniper.Processes.AbstractShellCommand.RunAsync().
RunAsync() [1/2]
Task<int> Juniper.Processes.AbstractShellCommand.RunAsync () inline
Definition at line 52 of file AbstractShellCommand.cs.
         {
             return RunAsync(Arguments);
         }
References Juniper.Processes.AbstractShellCommand.Arguments.
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.ExistsAsync(), Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync(), and Juniper.Processes.AbstractShellCommand.Run().
RunAsync() [2/2]
virtual async Task<int> Juniper.Processes.AbstractShellCommand.RunAsync (IEnumerable< string > arguments) inline protected virtual
Reimplemented in Juniper.HTTP.Server.Administration.NetSH.AddFirewallRule, Juniper.HTTP.Server.Administration.NetSH.DeleteFirewallRule, and Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.
Definition at line 67 of file AbstractShellCommand.cs.
         {
             TotalStandardOutput = string.Empty;
             TotalStandardError = string.Empty;
             using var proc = new Process()
             {
                 StartInfo = new ProcessStartInfo(command)
                 {
                     Arguments = arguments.ToArray().Join(' '),
                     UseShellExecute = UseShellExecute,
                     LoadUserProfile = LoadUserProfile,
                     StandardErrorEncoding = Encoding,
                     StandardOutputEncoding = Encoding,
                     ErrorDialog = false,
                     CreateNoWindow = true,
                     RedirectStandardError = true,
                     RedirectStandardInput = true,
                     RedirectStandardOutput = true,
                     WindowStyle = ProcessWindowStyle.Hidden
                 }
             };
 #if DEBUG
             LastCommand = $"{Environment.CurrentDirectory}> {proc.StartInfo.FileName} {proc.StartInfo.Arguments}";
 #endif
             var outputAccum = new StringBuilder();
             void Proc_AccumOutputData(object sender, DataReceivedEventArgs e) => _ = outputAccum.AppendLine(e.Data);
             var errorAccum = new StringBuilder();
             void Proc_AccumErrorData(object sender, DataReceivedEventArgs e) => _ = errorAccum.AppendLine(e.Data);
             proc.OutputDataReceived += Proc_AccumOutputData;
             proc.OutputDataReceived += Proc_OutputDataReceived;
             proc.ErrorDataReceived += Proc_AccumErrorData;
             proc.ErrorDataReceived += Proc_ErrorDataReceived;
             try
             {
                 if (!proc.Start())
                 {
                     throw new InvalidOperationException("Could not start process.");
                 }
             }
             catch (Exception exp)
             {
                 exp.Data.Add("ProcessStart", proc.StartInfo);
                 OnError(exp);
                 throw;
             }
             proc.BeginOutputReadLine();
             proc.BeginErrorReadLine();
             await Task.Run(proc.WaitForExit)
                 .ConfigureAwait(false);
             TotalStandardOutput = outputAccum.ToString();
             TotalStandardError = errorAccum.ToString();
             proc.ErrorDataReceived -= Proc_ErrorDataReceived;
             proc.OutputDataReceived -= Proc_OutputDataReceived;
             proc.ErrorDataReceived -= Proc_AccumErrorData;
             proc.OutputDataReceived -= Proc_AccumOutputData;
             return proc.ExitCode;
         }
References Juniper.Processes.AbstractShellCommand.Arguments, Juniper.Processes.AbstractShellCommand.command, Juniper.Processes.AbstractShellCommand.Encoding, Juniper.Processes.AbstractShellCommand.LoadUserProfile, Juniper.Processes.AbstractShellCommand.OnError(), Juniper.Processes.AbstractShellCommand.Proc_ErrorDataReceived(), Juniper.Processes.AbstractShellCommand.Proc_OutputDataReceived(), Juniper.Processes.AbstractShellCommand.TotalStandardError, Juniper.Processes.AbstractShellCommand.TotalStandardOutput, and Juniper.Processes.AbstractShellCommand.UseShellExecute.
Member Data Documentation
command
readonly string Juniper.Processes.AbstractShellCommand.command private
Definition at line 16 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.AbstractShellCommand(), and Juniper.Processes.AbstractShellCommand.RunAsync().
Property Documentation
Arguments
abstract IEnumerable<string> Juniper.Processes.AbstractShellCommand.Arguments get protected
Definition at line 48 of file AbstractShellCommand.cs.
         {
             get;
         }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
Encoding
Encoding Juniper.Processes.AbstractShellCommand.Encoding get set
Definition at line 26 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
LoadUserProfile
bool Juniper.Processes.AbstractShellCommand.LoadUserProfile get set
Definition at line 24 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
TotalStandardError
string Juniper.Processes.AbstractShellCommand.TotalStandardError get private set
Definition at line 30 of file AbstractShellCommand.cs.
 { get; private set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
TotalStandardOutput
string Juniper.Processes.AbstractShellCommand.TotalStandardOutput get private set
Definition at line 28 of file AbstractShellCommand.cs.
 { get; private set; }
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync(), Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.RunAsync(), Juniper.Processes.AbstractShellCommand.RunAsync(), Juniper.HTTP.Server.Administration.NetSH.DeleteFirewallRule.RunAsync(), and Juniper.HTTP.Server.Administration.NetSH.AddFirewallRule.RunAsync().
UseShellExecute
bool Juniper.Processes.AbstractShellCommand.UseShellExecute get set
Definition at line 22 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
Event Documentation
Err
EventHandler<ErrorEventArgs> Juniper.Processes.AbstractShellCommand.Err
Definition at line 20 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnError().
Info
EventHandler<StringEventArgs> Juniper.Processes.AbstractShellCommand.Info
Definition at line 18 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnInfo().
Warning
EventHandler<StringEventArgs> Juniper.Processes.AbstractShellCommand.Warning
Definition at line 19 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnWarning().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Processes/AbstractShellCommand.cs