Juniper: Juniper.Animation.FadeTransition Class Reference
Juniper.Animation.FadeTransition Class Reference
Performs a fade-in/fade-out animation on scene transitions.
Public Member Functions
void Awake ()
Retrieves component references and sets up event handlers.
virtual void Reinstall ()
Resets the object to its initial state.
void Install (bool reset)
Installs necessary components and initializes their default values.
void Uninstall ()
There are no components to uninstall from this component.
void Fader (Action act)
Adds the provided action to a queue of actions that will be executed in between a fade-out and fade-in cycle. This is useful for hiding long processing actions that would cause the VR view to stutter.
override void Enter (IProgress prog)
Fire the OnEnable event and perform the Enter transition.
void Enter ()
override void Exit (IProgress prog)
Fire the OnExiting event and perform the Exit transition.
void Exit ()
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
virtual void SkipExit ()
Task EnterAsync (IProgress prog=null)
Task ExitAsync (IProgress prog=null)
Static Public Member Functions
static PooledComponent< FadeTransition > Ensure (Transform parent)
Setup the necessary gameObjects and components to make a fader box appears in front of the camera.
Public Attributes
AudioClip fadeOutSound
The sound to play when the view fades out.
float volume = 0.5f
float fadeLength = 0.5f
If Unity's audio subsystem is not available, or the fade-in/fade-out sounds are not configured, this is the default length of time to run the fade-in/fade-out transition.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
UnityEvent onStopped = new UnityEvent()
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Direction _curState
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void RenderValue (float value)
As the fade transition updates, sets the opacity of the view blocker graphic.
override void OnEntered ()
Saves the last clear color, culling mask, and ambient light mode, then prepares the camera to render the special "faded out" view, which allows TransparentFX objects to still be visible, so we can have simple UI elements still visible while the view is faded out. If Unity's audio subsystem is available, switches the audio source to use the fade-in sound for the next transition. Also, executes and queued actions that are waiting for the fade transition to complete.
override void OnExiting ()
Restores the camera's rendering and lighting modes to what it was before the fade-out.
override void Complete ()
Finish the transition, whatever is going on.
override void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
virtual void OnStopped ()
Protected Attributes
bool skipEvents
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Properties
override float TransitionLength [get]
The amount of time the fade transition takes to complete. If a fade sound is provided, this will be based on the length of the sound clip. Otherwise, it's 1/4th of a second.
Direction State [get, private set]
virtual bool IsComplete [get]
Returns true when State is Direction.Stopped
bool IsEntering [get]
bool IsExiting [get]
bool CanExit [get]
bool CanEnter [get]
bool IsRunning [get]
Returns true when State is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
Events
EventHandler< TransitionValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
EventHandler Stopped
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Private Member Functions
void FadeTransition_Enter_Exiting (object sender, EventArgs e)
Play the fade-in/fade-out sound
Private Attributes
AudioSource aud
The audio source on which to play the fade-in/fade-out sounds.
UnifiedInputModule input
The input module that will tell use what layer the controllers are on, so we don't fade them out.
Color fadeOutColor
Renderer r
The renderer for the current object.
MaterialPropertyBlock props
Used to change values in the material, without globally changing the material.
readonly List< Action > actions = new List<Action>(5)
A queue of actions to perform when the fader has finished fading out, before it fades back in.
Color lastColor
The clear-color that was used before the fade-out transition started.
int lastCameraCullingMask
The culling-mask that was used before the fade-out transition started.
int lastControllerLayer
The layers the controllers are rendered on. This is used to make sure the controllers are still visible while the scene is faded out.
AmbientMode lastAmbientMode
The ambient light mode that was used before the fade-out transition was started.
Detailed Description
Performs a fade-in/fade-out animation on scene transitions.
Definition at line 17 of file FadeTransition.cs.
Member Function Documentation
Awake()
void Juniper.Animation.FadeTransition.Awake () inline
Retrieves component references and sets up event handlers.
Definition at line 85 of file FadeTransition.cs.
         {
             Install(false);
             Entering += FadeTransition_Enter_Exiting;
             Exiting += FadeTransition_Enter_Exiting;
             r = GetComponent<Renderer>();
             props = new MaterialPropertyBlock();
             var material = r.GetMaterial();
             fadeOutColor = material.GetColor("_Color");
             Find.Any(out input);
         }
References Juniper.AbstractStateController.Entering, Juniper.AbstractStateController.Exiting, Juniper.Animation.FadeTransition.fadeOutColor, Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Animation.FadeTransition.input, Juniper.Animation.FadeTransition.Install(), Juniper.Animation.FadeTransition.props, and Juniper.Animation.FadeTransition.r.
Complete()
override void Juniper.Animation.AbstractTransitionController.Complete () inline protected virtual inherited
Finish the transition, whatever is going on.
Reimplemented from Juniper.AbstractStateController.
Definition at line 110 of file AbstractTransitionController.cs.
         {
             SetProgress(1);
             base.Complete();
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Animation.AbstractTransitionController.Update().
Ensure()
static PooledComponent<FadeTransition> Juniper.Animation.FadeTransition.Ensure (Transform parent) inline static
Setup the necessary gameObjects and components to make a fader box appears in front of the camera.
Returns
Definition at line 66 of file FadeTransition.cs.
         {
             var fader = parent.Ensure<Transform>("Fader", () =>
                 GameObject.CreatePrimitive(PrimitiveType.Quad))
                 .Ensure<FadeTransition>();
 #if UNITY_MODULES_PHYSICS
             if (fader.IsNew)
             {
                 fader.Value.Remove<Collider>();
             }
 #endif
             return fader;
         }
Referenced by Juniper.MasterSceneController.SetupFader().
Enter() [1/2]
override void Juniper.Animation.AbstractTransitionController.Enter (IProgress prog) inline virtual inherited
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 92 of file AbstractTransitionController.cs.
         {
             base.Enter(prog);
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Widgets.TeleportPad.OnClick(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Animation.WorkflowStep.Show().
Enter() [2/2]
void Juniper.AbstractStateController.Enter () inline inherited
Definition at line 272 of file AbstractStateController.cs.
         {
             Enter(null);
         }
Referenced by Juniper.Widgets.MenuView.Enter(), Juniper.AbstractStateController.EnterAsync(), Juniper.Animation.FadeTransition.Fader(), Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.AbstractStateController.SkipEnter().
EnterAsync()
Task Juniper.AbstractStateController.EnterAsync (IProgress prog = null) inline inherited
Definition at line 331 of file AbstractStateController.cs.
         {
             return Stopper(Enter, prog);
         }
References Juniper.AbstractStateController.Enter(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Exit() [1/2]
override void Juniper.Animation.AbstractTransitionController.Exit (IProgress prog) inline virtual inherited
Fire the OnExiting event and perform the Exit transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 101 of file AbstractTransitionController.cs.
         {
             base.Exit(prog);
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Widgets.TeleportPad.Darth_Entered(), and Juniper.Widgets.Openable.SetOpen().
Exit() [2/2]
void Juniper.AbstractStateController.Exit () inline inherited
Definition at line 285 of file AbstractStateController.cs.
         {
             Exit(null);
         }
Referenced by Juniper.Widgets.MenuView.Exit(), Juniper.AbstractStateController.ExitAsync(), Juniper.Animation.FadeTransition.Fader(), and Juniper.AbstractStateController.SkipExit().
ExitAsync()
Task Juniper.AbstractStateController.ExitAsync (IProgress prog = null) inline inherited
Definition at line 336 of file AbstractStateController.cs.
         {
             return Stopper(Exit, prog);
         }
References Juniper.AbstractStateController.Exit(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), Juniper.MasterSceneController.RemoveSceneCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Fader()
void Juniper.Animation.FadeTransition.Fader (Action act) inline
Adds the provided action to a queue of actions that will be executed in between a fade-out and fade-in cycle. This is useful for hiding long processing actions that would cause the VR view to stutter.
Parameters
act The action lambda expression to run
Definition at line 182 of file FadeTransition.cs.
         {
             if (actions.Count == 0)
             {
                 actions.Add(new Action(Exit));
             }
             actions.Insert(actions.Count - 1, act);
             Enter();
         }
References Juniper.Animation.FadeTransition.actions, Juniper.AbstractStateController.Enter(), and Juniper.AbstractStateController.Exit().
FadeTransition_Enter_Exiting()
void Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting (object sender, EventArgs e) inline private
Play the fade-in/fade-out sound
Definition at line 217 of file FadeTransition.cs.
         {
 #if UNITY_MODULES_AUDIO
             if (State == Direction.Forward)
             {
                 aud.volume = volume;
                 aud.Play();
             }
 #endif
         }
References Juniper.Animation.FadeTransition.aud, Juniper.AbstractStateController.State, and Juniper.Animation.FadeTransition.volume.
Referenced by Juniper.Animation.FadeTransition.Awake().
Install()
void Juniper.Animation.FadeTransition.Install (bool reset) inline
Installs necessary components and initializes their default values.
Implements Juniper.IO.IInstallable.
Definition at line 124 of file FadeTransition.cs.
         {
 #if UNITY_MODULES_AUDIO
 #if UNITY_EDITOR
             if (reset)
             {
                 fadeOutSound = ResourceExt.EditorLoadAsset<AudioClip>("Assets/Juniper/Assets/Audio/Star Trek/hologram_off_2.mp3");
             }
 #endif
             aud = this.Ensure<AudioSource>();
             aud.playOnAwake = false;
             aud.clip = fadeOutSound;
 #endif
         }
References Juniper.Animation.FadeTransition.aud, and Juniper.Animation.FadeTransition.fadeOutSound.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.Animation.FadeTransition.Reinstall().
OnEntered()
override void Juniper.Animation.FadeTransition.OnEntered () inline protected virtual
Saves the last clear color, culling mask, and ambient light mode, then prepares the camera to render the special "faded out" view, which allows TransparentFX objects to still be visible, so we can have simple UI elements still visible while the view is faded out. If Unity's audio subsystem is available, switches the audio source to use the fade-in sound for the next transition. Also, executes and queued actions that are waiting for the fade transition to complete.
Reimplemented from Juniper.AbstractStateController.
Definition at line 236 of file FadeTransition.cs.
         {
             base.OnEntered();
             lastColor = DisplayManager.BackgroundColor;
             lastCameraCullingMask = DisplayManager.CullingMask;
             lastControllerLayer = input.ControllerLayer;
             lastAmbientMode = RenderSettings.ambientMode;
             Find.Any(out JuniperSystem sys);
             if (sys.m_ARMode == AugmentedRealityTypes.None)
             {
                 DisplayManager.ClearFlags = CameraClearFlags.Color;
                 DisplayManager.BackgroundColor = fadeOutColor;
             }
             input.ControllerLayer = LayerMask.NameToLayer("TransparentFX");
             DisplayManager.CullingMask = LayerMask.GetMask("TransparentFX");
             RenderSettings.ambientMode = AmbientMode.Flat;
             foreach (var action in actions)
             {
                 try
                 {
                     action();
                 }
 #pragma warning disable CA1031 // Do not catch general exception types
                 catch (Exception exp)
                 {
                     Debug.LogError(exp);
                 }
 #pragma warning restore CA1031 // Do not catch general exception types
             }
             actions.Clear();
         }
References Juniper.Animation.FadeTransition.actions, Juniper.Display.AbstractDisplayManager.BackgroundColor, Juniper.Display.AbstractDisplayManager.ClearFlags, Juniper.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Display.AbstractDisplayManager.CullingMask, Juniper.XR.Debug, Juniper.Animation.FadeTransition.fadeOutColor, Juniper.Animation.FadeTransition.input, Juniper.Animation.FadeTransition.lastAmbientMode, Juniper.Animation.FadeTransition.lastCameraCullingMask, Juniper.Animation.FadeTransition.lastColor, and Juniper.Animation.FadeTransition.lastControllerLayer.
OnEntering()
override void Juniper.Animation.AbstractTransitionController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 120 of file AbstractTransitionController.cs.
         {
             attack = attackTime;
             release = releaseTime;
             SetProgress(0);
             base.OnEntering();
         }
References Juniper.Animation.AbstractTransitionController.attack, Juniper.Animation.AbstractTransitionController.attackTime, Juniper.Animation.AbstractTransitionController.release, Juniper.Animation.AbstractTransitionController.releaseTime, and Juniper.Animation.AbstractTransitionController.SetProgress().
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 417 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onExited != null)
                 {
                     onExited.Invoke();
                 }
                 Exited?.Invoke(this, EventArgs.Empty);
             }
             enabled = false;
         }
References Juniper.AbstractStateController.Exited, Juniper.AbstractStateController.onExited, and Juniper.AbstractStateController.skipEvents.
OnExiting()
override void Juniper.Animation.FadeTransition.OnExiting () inline protected virtual
Restores the camera's rendering and lighting modes to what it was before the fade-out.
Reimplemented from Juniper.Animation.AbstractTransitionController.
Definition at line 277 of file FadeTransition.cs.
         {
             base.OnExiting();
             Find.Any(out JuniperSystem sys);
             if (sys.m_ARMode == AugmentedRealityTypes.None)
             {
                 DisplayManager.ClearFlags = CameraClearFlags.Skybox;
                 DisplayManager.BackgroundColor = lastColor;
             }
             DisplayManager.CullingMask = lastCameraCullingMask;
             input.ControllerLayer = lastControllerLayer;
             RenderSettings.ambientMode = lastAmbientMode;
         }
References Juniper.Display.AbstractDisplayManager.BackgroundColor, Juniper.Display.AbstractDisplayManager.ClearFlags, Juniper.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Display.AbstractDisplayManager.CullingMask, Juniper.Animation.FadeTransition.input, Juniper.Animation.FadeTransition.lastAmbientMode, Juniper.Animation.FadeTransition.lastCameraCullingMask, Juniper.Animation.FadeTransition.lastColor, and Juniper.Animation.FadeTransition.lastControllerLayer.
OnStopped()
virtual void Juniper.AbstractStateController.OnStopped () inline protected virtual inherited
Definition at line 430 of file AbstractStateController.cs.
         {
             if (onStopped != null)
             {
                 onStopped?.Invoke();
             }
             Stopped?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.onStopped, and Juniper.AbstractStateController.Stopped.
Reinstall()
virtual void Juniper.Animation.FadeTransition.Reinstall () inline virtual
Resets the object to its initial state.
Implements Juniper.IO.IInstallable.
Definition at line 104 of file FadeTransition.cs.
         {
             Install(true);
         }
References Juniper.Animation.FadeTransition.Install().
RenderValue()
override void Juniper.Animation.FadeTransition.RenderValue (float value) inline protected virtual
As the fade transition updates, sets the opacity of the view blocker graphic.
Parameters
value
Implements Juniper.Animation.AbstractTransitionController.
Definition at line 151 of file FadeTransition.cs.
         {
             if (props != null)
             {
                 props.SetFloat("_Alpha", Mathf.Clamp01(value));
                 r.SetPropertyBlock(props);
             }
         }
References Juniper.Animation.FadeTransition.props, and Juniper.Animation.FadeTransition.r.
SkipEnter()
virtual void Juniper.AbstractStateController.SkipEnter () inline virtual inherited
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 309 of file AbstractStateController.cs.
         {
             if (!IsEntered)
             {
                 skipEvents = true;
                 Enter();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.IsEntered, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.MasterSceneController.Start().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 320 of file AbstractStateController.cs.
         {
             if (!IsExited)
             {
                 skipEvents = true;
                 Exit();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Exit(), Juniper.AbstractStateController.IsExited, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.Widgets.Tooltipable.Hide(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Uninstall()
void Juniper.Animation.FadeTransition.Uninstall () inline
There are no components to uninstall from this component.
Implements Juniper.IO.IInstallable.
Definition at line 143 of file FadeTransition.cs.
         {
         }
Update()
virtual void Juniper.Animation.AbstractTransitionController.Update () inline protected virtual inherited
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented in Juniper.Animation.SpiralTransition.
Definition at line 140 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress < 1)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress + change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     Complete();
                 }
             }
         }
References Juniper.Animation.AbstractTransitionController.attack, Juniper.Animation.AbstractTransitionController.Complete(), Juniper.AbstractStateController.IsRunning, Juniper.Animation.AbstractTransitionController.progress, Juniper.Animation.AbstractTransitionController.release, Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.Animation.AbstractTransitionController.TransitionLength.
Referenced by Juniper.Animation.AbstractTransitionController.Complete(), Juniper.Animation.AbstractTransitionController.Enter(), and Juniper.Animation.AbstractTransitionController.Exit().
Member Data Documentation
_curState
Direction Juniper.AbstractStateController._curState inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 117 of file AbstractStateController.cs.
actions
readonly List<Action> Juniper.Animation.FadeTransition.actions = new List<Action>(5) private
A queue of actions to perform when the fader has finished fading out, before it fades back in.
Definition at line 174 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.Fader(), and Juniper.Animation.FadeTransition.OnEntered().
attackTime
float Juniper.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 21 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnEntering(), and Juniper.Animation.AbstractTransitionController.OnExiting().
aud
AudioSource Juniper.Animation.FadeTransition.aud private
The audio source on which to play the fade-in/fade-out sounds.
Definition at line 29 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), and Juniper.Animation.FadeTransition.Install().
fadeLength
float Juniper.Animation.FadeTransition.fadeLength = 0.5f
If Unity's audio subsystem is not available, or the fade-in/fade-out sounds are not configured, this is the default length of time to run the fade-in/fade-out transition.
Definition at line 39 of file FadeTransition.cs.
fadeOutColor
Color Juniper.Animation.FadeTransition.fadeOutColor private
Definition at line 59 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.Animation.FadeTransition.OnEntered().
fadeOutSound
AudioClip Juniper.Animation.FadeTransition.fadeOutSound
The sound to play when the view fades out.
Definition at line 24 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.Install(), and Juniper.MasterSceneController.QuitCoroutine().
input
UnifiedInputModule Juniper.Animation.FadeTransition.input private
The input module that will tell use what layer the controllers are on, so we don't fade them out.
Definition at line 57 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
lastAmbientMode
AmbientMode Juniper.Animation.FadeTransition.lastAmbientMode private
The ambient light mode that was used before the fade-out transition was started.
Definition at line 212 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
lastCameraCullingMask
int Juniper.Animation.FadeTransition.lastCameraCullingMask private
The culling-mask that was used before the fade-out transition started.
Definition at line 201 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
lastColor
Color Juniper.Animation.FadeTransition.lastColor private
The clear-color that was used before the fade-out transition started.
Definition at line 196 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
lastControllerLayer
int Juniper.Animation.FadeTransition.lastControllerLayer private
The layers the controllers are rendered on. This is used to make sure the controllers are still visible while the scene is faded out.
Definition at line 207 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Animation.FadeTransition.OnExiting().
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 38 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 29 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 56 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 47 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
onStopped
UnityEvent Juniper.AbstractStateController.onStopped = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 65 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped().
onValueChanged
UnityEvent Juniper.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 34 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
props
MaterialPropertyBlock Juniper.Animation.FadeTransition.props private
Used to change values in the material, without globally changing the material.
Definition at line 168 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.Animation.FadeTransition.RenderValue().
r
Renderer Juniper.Animation.FadeTransition.r private
The renderer for the current object.
Definition at line 163 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.Animation.FadeTransition.RenderValue().
releaseTime
float Juniper.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 28 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnEntering(), and Juniper.Animation.AbstractTransitionController.OnExiting().
skipEvents
bool Juniper.AbstractStateController.skipEvents protected inherited
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Definition at line 166 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Complete(), Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.AbstractTransitionController.Exit(), Juniper.AbstractStateController.OnEntered(), Juniper.AbstractStateController.OnEntering(), Juniper.AbstractStateController.OnExited(), Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.SkipEnter(), and Juniper.AbstractStateController.SkipExit().
tween
TweenType Juniper.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 39 of file AbstractTransitionController.cs.
tweenK
float Juniper.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 46 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.SetProgress().
volume
float Juniper.Animation.FadeTransition.volume = 0.5f
Definition at line 31 of file FadeTransition.cs.
Referenced by Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), and Juniper.MasterSceneController.QuitCoroutine().
Property Documentation
CanEnter
bool Juniper.AbstractStateController.CanEnter get inherited
Definition at line 204 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsEntered && !IsEntering;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
CanExit
bool Juniper.AbstractStateController.CanExit get inherited
Definition at line 196 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsExited && !IsExiting;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get inherited
Returns true when State is Direction.Stopped
Definition at line 172 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Stopped;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntered
bool Juniper.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 226 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Forward;
             }
         }
Referenced by Juniper.AbstractStateController.SkipEnter(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntering
bool Juniper.AbstractStateController.IsEntering get inherited
Definition at line 180 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Forward;
             }
         }
IsExited
bool Juniper.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 237 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Reverse;
             }
         }
Referenced by Juniper.AbstractStateController.SkipExit(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsExiting
bool Juniper.AbstractStateController.IsExiting get inherited
Definition at line 188 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Reverse;
             }
         }
IsRunning
bool Juniper.AbstractStateController.IsRunning get inherited
Returns true when State is not Direction.Stopped
Definition at line 215 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Animation.AbstractTransitionController.Update().
State
Direction Juniper.AbstractStateController.State get private set inherited
Definition at line 120 of file AbstractStateController.cs.
         {
             get
             {
                 return _curState;
             }
             private set
             {
                 lastState = _curState;
                 _curState = value;
                 if (State != lastState)
                 {
                     if (State == Direction.Forward)
                     {
                         OnEntering();
                     }
                     else if (State == Direction.Reverse)
                     {
                         OnExiting();
                     }
                     else
                     {
                         OnStopped();
                         if (lastState == Direction.Forward)
{
                             OnEntered();
                         }
                         else if (lastState == Direction.Reverse)
{
                             OnExited();
                         }
                     }
                 }
             }
         }
Referenced by Juniper.AbstractStateController.Complete(), Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.AbstractStateController.SetState().
TransitionLength
override float Juniper.Animation.FadeTransition.TransitionLength get
The amount of time the fade transition takes to complete. If a fade sound is provided, this will be based on the length of the sound clip. Otherwise, it's 1/4th of a second.
Definition at line 46 of file FadeTransition.cs.
         {
             get
             {
                 return fadeLength / 2;
             }
         }
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 83 of file AbstractStateController.cs.
Referenced by Juniper.Widgets.MenuView.Awake(), Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 74 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 101 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 92 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExiting().
Stopped
EventHandler Juniper.AbstractStateController.Stopped inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 110 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped(), and Juniper.AbstractStateController.Stopper().
ValueChanged
EventHandler<TransitionValueChangedEventArgs> Juniper.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 52 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Animation/FadeTransition.cs