Juniper: BitMiracle.LibJpeg.Classic.JpegCommonStruct Class Reference
BitMiracle.LibJpeg.Classic.JpegCommonStruct Class Reference
Base class for both JPEG compressor and decompresor.
Public Member Functions
void JpegAbort ()
void JpegDestroy ()
void ErrExit (JMessageCode code)
Used for fatal errors (print message and exit).
void ErrExit (JMessageCode code, params object[] args)
Used for fatal errors (print message and exit).
void ErrExit (int code, params object[] args)
Used for fatal errors (print message and exit).
void WarnMS (JMessageCode code)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void WarnMS (JMessageCode code, params object[] args)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void WarnMS (int code, params object[] args)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void TraceMS (int lvl, JMessageCode code)
Shows informational and debugging messages.
void TraceMS (int lvl, JMessageCode code, params object[] args)
Shows informational and debugging messages.
void TraceMS (int lvl, int code, params object[] args)
Shows informational and debugging messages.
Static Public Member Functions
static JVirtArray< byte > CreateSamplesArray (int samplesPerRow, int numberOfRows)
Creates the array of samples.
static JVirtArray< JBlock > CreateBlocksArray (int blocksPerRow, int numberOfRows)
Creates the array of blocks.
static byte [][] AllocJpegSamples (int samplesPerRow, int numberOfRows)
Creates 2-D sample array.
Static Public Attributes
static string Copyright => "Copyright (C) 2008-2018, Bit Miracle"
Gets the LibJpeg's copyright.
Protected Member Functions
JpegCommonStruct ()
Base constructor.
JpegCommonStruct (JpegErrorMessage errorManager)
Base constructor.
Properties
abstract bool IsDecompressor [get]
Gets a value indicating whether this instance is Jpeg decompressor.
JpegProgressManager?? Progress [get, set]
Progress monitor.
JpegErrorMessage?? Err [get, set]
Error handler module.
static string Version [get]
Gets the version of LibJpeg.
Private Types
enum JpegState {
JpegState.DESTROYED = 0, JpegState.CSTATE_START = 100, JpegState.CSTATE_SCANNING = 101, JpegState.CSTATE_RAW_OK = 102,
JpegState.CSTATE_WRCOEFS = 103, JpegState.DSTATE_START = 200, JpegState.DSTATE_INHEADER = 201, JpegState.DSTATE_READY = 202,
JpegState.DSTATE_PRELOAD = 203, JpegState.DSTATE_PRESCAN = 204, JpegState.DSTATE_SCANNING = 205, JpegState.DSTATE_RAW_OK = 206,
JpegState.DSTATE_BUFIMAGE = 207, JpegState.DSTATE_BUFPOST = 208, JpegState.DSTATE_RDCOEFS = 209, JpegState.DSTATE_STOPPING = 210
}
Static Private Member Functions
static JBlock [][] AllocJpegBlocks (int blocksPerRow, int numberOfRows)
Private Attributes
internal JpegErrorMessage jpgError
internal JpegProgressManager prog
internal JpegState globalState
Detailed Description
Base class for both JPEG compressor and decompresor.
Routines that are to be used by both halves of the library are declared to receive an instance of this class. There are no actual instances of JpegCommonStruct, only of JpegCompressStruct and JpegDecompressStruct
Definition at line 21 of file JpegCommonStruct.cs.
Member Enumeration Documentation
JpegState
enum BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegState strong private
Enumerator
DESTROYED
CSTATE_START
CSTATE_SCANNING
CSTATE_RAW_OK
CSTATE_WRCOEFS
DSTATE_START
DSTATE_INHEADER
DSTATE_READY
DSTATE_PRELOAD
DSTATE_PRESCAN
DSTATE_SCANNING
DSTATE_RAW_OK
DSTATE_BUFIMAGE
DSTATE_BUFPOST
DSTATE_RDCOEFS
DSTATE_STOPPING
Definition at line 23 of file JpegCommonStruct.cs.
         {
             DESTROYED = 0,
             CSTATE_START = 100,     /* after create_compress */
             CSTATE_SCANNING = 101,  /* start_compress done, write_scanlines OK */
             CSTATE_RAW_OK = 102,    /* start_compress done, write_raw_data OK */
             CSTATE_WRCOEFS = 103,   /* jpeg_write_coefficients done */
             DSTATE_START = 200,     /* after create_decompress */
             DSTATE_INHEADER = 201,  /* reading header markers, no SOS yet */
             DSTATE_READY = 202,     /* found SOS, ready for start_decompress */
             DSTATE_PRELOAD = 203,   /* reading multiscan file in start_decompress*/
             DSTATE_PRESCAN = 204,   /* performing dummy pass for 2-pass quant */
             DSTATE_SCANNING = 205,  /* start_decompress done, read_scanlines OK */
             DSTATE_RAW_OK = 206,    /* start_decompress done, read_raw_data OK */
             DSTATE_BUFIMAGE = 207,  /* expecting jpeg_start_output */
             DSTATE_BUFPOST = 208,   /* looking for SOS/EOI in jpeg_finish_output */
             DSTATE_RDCOEFS = 209,   /* reading file in jpeg_read_coefficients */
             DSTATE_STOPPING = 210   /* looking for EOI in jpeg_finish_decompress */
         }
Constructor & Destructor Documentation
JpegCommonStruct() [1/2]
BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegCommonStruct () inline protected
Base constructor.
See also
JpegCompressStruct, JpegDecompressStruct
Definition at line 56 of file JpegCommonStruct.cs.
                                      : this(new JpegErrorMessage())
         {
         }
JpegCommonStruct() [2/2]
BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegCommonStruct (JpegErrorMessage errorManager) inline protected
Base constructor.
Parameters
errorManager The error manager.
See also
JpegCompressStruct, JpegDecompressStruct
Definition at line 66 of file JpegCommonStruct.cs.
         {
             Err = errorManager;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.Err.
Member Function Documentation
AllocJpegBlocks()
static JBlock [][] BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegBlocks (int blocksPerRow, int numberOfRows) inline static private
Definition at line 170 of file JpegCommonStruct.cs.
         {
             var result = new JBlock[numberOfRows][];
             for (var i = 0; i < numberOfRows; ++i)
             {
                 result[i] = new JBlock[blocksPerRow];
                 for (var j = 0; j < blocksPerRow; ++j)
                 {
                     result[i][j] = new JBlock();
                 }
             }
             return result;
         }
Referenced by BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateBlocksArray().
AllocJpegSamples()
static byte [][] BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples (int samplesPerRow, int numberOfRows) inline static
Creates 2-D sample array.
Parameters
samplesPerRow The number of samples per row.
numberOfRows The number of rows.
Returns
The array of samples.
Definition at line 158 of file JpegCommonStruct.cs.
         {
             var result = new byte[numberOfRows][];
             for (var i = 0; i < numberOfRows; ++i)
             {
                 result[i] = new byte[samplesPerRow];
             }
             return result;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColorIndex(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColormap(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateSamplesArray(), BitMiracle.LibJpeg.Jpeg.Decompress(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.JpegCMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), and BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler().
CreateBlocksArray()
static JVirtArray<JBlock> BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateBlocksArray (int blocksPerRow, int numberOfRows) inline static
Creates the array of blocks.
Parameters
blocksPerRow The number of blocks in row.
numberOfRows The number of rows.
Returns
The array of blocks.
See also
JBlock
Definition at line 147 of file JpegCommonStruct.cs.
         {
             return new JVirtArray<JBlock>(blocksPerRow, numberOfRows, AllocJpegBlocks);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegBlocks().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.JpegDCoefController(), and BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.MyCCoefController().
CreateSamplesArray()
static JVirtArray<byte> BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateSamplesArray (int samplesPerRow, int numberOfRows) inline static
Creates the array of samples.
Parameters
samplesPerRow The number of samples in row.
numberOfRows The number of rows.
Returns
The array of samples.
Definition at line 135 of file JpegCommonStruct.cs.
         {
             return new JVirtArray<byte>(samplesPerRow, numberOfRows, AllocJpegSamples);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController().
ErrExit() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (JMessageCode code) inline
Used for fatal errors (print message and exit).
Parameters
code The message code.
Definition at line 238 of file JpegCommonStruct.cs.
         {
             ErrExit((int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.JVirtArray< BitMiracle.LibJpeg.Classic.JBlock >.Access(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.AddHuffTable(), BitMiracle.LibJpeg.Classic.Internal.ArithEntropyDecoder.ArithEntropyDecoder(), BitMiracle.LibJpeg.Classic.Internal.ArithEntropyEncoder.ArithEntropyEncoder(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.ColorQuantize(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.ColorQuantize(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressData(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.MySourceManager.FillInputBuffer(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.Inverse(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMainController(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultColorspace(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct9x9(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegGenOptimalTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegHasMultipleScans(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct9x9(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegInputComplete(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.LatchQuantTables(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.My1PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.NewColorMap(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.SelectNColors(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.start_pass(), BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.UpSampleComponent(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader().
ErrExit() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (JMessageCode code, params object [] args) inline
Used for fatal errors (print message and exit).
Parameters
code The message code.
args The parameters of message.
Definition at line 248 of file JpegCommonStruct.cs.
         {
             ErrExit((int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit().
ErrExit() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (int code, params object [] args) inline
Used for fatal errors (print message and exit).
Parameters
code The message code.
args The parameters of message.
Definition at line 258 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.ErrorExit();
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.ErrorExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
JpegAbort()
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort () inline
Abort processing of a JPEG compression or decompression operation, but don't destroy the object itself.
Closing a data source or destination, if necessary, is the application's responsibility.
Definition at line 198 of file JpegCommonStruct.cs.
         {
             /* Reset overall state for possible reuse of object */
             if (IsDecompressor)
             {
                 globalState = JpegState.DSTATE_START;
                 /* Try to keep application from accessing now-deleted marker list.
                  * A bit kludgy to do it here, but this is the most central place.
                  */
                 if (this is JpegDecompressStruct s)
                 {
                     s.m_marker_list = null;
                 }
             }
             else
             {
                 globalState = JpegState.CSTATE_START;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.IsDecompressor.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAbortCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegAbortDecompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader().
JpegDestroy()
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegDestroy () inline
Destruction of a JPEG object.
Closing a data source or destination, if necessary, is the application's responsibility.
Definition at line 226 of file JpegCommonStruct.cs.
         {
             // mark it destroyed
             globalState = JpegState.DESTROYED;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState.
TraceMS() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, JMessageCode code) inline
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
See also
JpegErrorMessage.EmitMessage
Definition at line 306 of file JpegCommonStruct.cs.
         {
             TraceMS(lvl, (int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColormap(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.SelectColors(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
TraceMS() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, JMessageCode code, params object [] args) inline
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
args The parameters of message.
See also
JpegErrorMessage.EmitMessage
Definition at line 318 of file JpegCommonStruct.cs.
         {
             TraceMS(lvl, (int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
TraceMS() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, int code, params object [] args) inline
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
args The parameters of message.
See also
JpegErrorMessage.EmitMessage
Definition at line 330 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.EmitMessage(lvl);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
WarnMS() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (JMessageCode code) inline
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
Definition at line 271 of file JpegCommonStruct.cs.
         {
             WarnMS((int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.MySourceManager.FillInputBuffer(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
WarnMS() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (JMessageCode code, params object [] args) inline
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
args The parameters of message.
Definition at line 281 of file JpegCommonStruct.cs.
         {
             WarnMS((int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
WarnMS() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (int code, params object [] args) inline
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
args The parameters of message.
Definition at line 291 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.EmitMessage(-1);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
Member Data Documentation
Copyright
string BitMiracle.LibJpeg.Classic.JpegCommonStruct.Copyright => "Copyright (C) 2008-2018, Bit Miracle" static
Gets the LibJpeg's copyright.
The copyright.
Definition at line 127 of file JpegCommonStruct.cs.
globalState
internal JpegState BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState private
Definition at line 49 of file JpegCommonStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputInHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputStart(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegDestroy(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegHasMultipleScans(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegInputComplete(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup().
jpgError
internal JpegErrorMessage BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError private
Definition at line 44 of file JpegCommonStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
prog
internal JpegProgressManager BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog private
Definition at line 47 of file JpegCommonStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.OutputPassSetup(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.TransdecodeMasterSelection().
Property Documentation
Err
JpegErrorMessage?? BitMiracle.LibJpeg.Classic.JpegCommonStruct.Err get set
Error handler module.
The error manager.
Error handling
Definition at line 96 of file JpegCommonStruct.cs.
         {
             get { return jpgError; }
             set { jpgError = value ?? throw new ArgumentNullException(nameof(value)); }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegCommonStruct().
IsDecompressor
abstract bool BitMiracle.LibJpeg.Classic.JpegCommonStruct.IsDecompressor get
Gets a value indicating whether this instance is Jpeg decompressor.
true if this is Jpeg decompressor; otherwise, false.
Definition at line 77 of file JpegCommonStruct.cs.
 { get; }
Referenced by BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort().
Progress
JpegProgressManager?? BitMiracle.LibJpeg.Classic.JpegCommonStruct.Progress get set
Progress monitor.
The progress manager.
Default value: null.
Definition at line 85 of file JpegCommonStruct.cs.
         {
             get { return prog; }
             set { prog = value ?? throw new ArgumentNullException(nameof(value)); }
         }
Version
string BitMiracle.LibJpeg.Classic.JpegCommonStruct.Version static get
Gets the version of LibJpeg.
The version of LibJpeg.
Definition at line 106 of file JpegCommonStruct.cs.
         {
             get
             {
                 var assembly = typeof(JpegCommonStruct).GetTypeInfo().Assembly;
                 var assemblyName = new AssemblyName(assembly.FullName);
                 var version = assemblyName.Version;
                 var versionString = version.Major.ToString(CultureInfo.InvariantCulture) +
                     "." + version.Minor.ToString(CultureInfo.InvariantCulture);
                 versionString += "." + version.Build.ToString(CultureInfo.InvariantCulture);
                 versionString += "." + version.Revision.ToString(CultureInfo.InvariantCulture);
                 return versionString;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/JpegCommonStruct.cs