Juniper: Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType > Class Template Reference
Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType > Class Template Reference
Public Member Functions
void Install (ButtonMapper< VirtualTouchPadButton > mapper, GameObject eventParent)
void Install (ButtonMapper< VirtualTriggerButton > mapper, GameObject eventParent)
string MakePointerName (Hands hand)
void Install (ButtonMapper< ButtonIDType > mapper, GameObject eventParent)
void Uninstall (GameObject eventParent)
Protected Member Functions
void AddButton (VirtualTouchPadButton outButton, InputButton? inButton=null)
void AddButton (VirtualTriggerButton outButton, InputButton? inButton=null)
void AddButton (ButtonIDType outButton, InputButton? inButton=null)
Properties
override string PointerNameStub [get]
Type HandType [get]
abstract ? HandIDType this[Hands hand] [get]
Private Attributes
readonly Dictionary< VirtualTouchPadButton, InputEventButton > touchPadButtons = new Dictionary<VirtualTouchPadButton, InputEventButton>(11)
readonly Dictionary< VirtualTriggerButton, InputEventButton > triggerButtons = new Dictionary<VirtualTriggerButton, InputEventButton>(3)
Detailed Description
Type Constraints
HandIDType : struct
HandIDType : IComparable
ButtonIDType : struct
Definition at line 12 of file AbstractMotionControllerConfiguration.cs.
Member Function Documentation
AddButton() [1/3]
void Juniper.Input.Pointers.AbstractPointerConfiguration< ButtonIDType >.AddButton (ButtonIDType outButton, InputButton? inButton = null) inline protected inherited
Definition at line 17 of file AbstractPointerConfiguration.cs.
         {
             nativeButtons.Add(outButton, inButton == null ? InputEventButton.None : (InputEventButton)inButton.Value);
         }
AddButton() [2/3]
void Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.AddButton (VirtualTouchPadButton outButton, InputButton? inButton = null) inline protected
Definition at line 28 of file AbstractMotionControllerConfiguration.cs.
         {
             touchPadButtons.Add(outButton, inButton == null ? InputEventButton.None : (InputEventButton)inButton.Value);
         }
AddButton() [3/3]
void Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.AddButton (VirtualTriggerButton outButton, InputButton? inButton = null) inline protected
Definition at line 33 of file AbstractMotionControllerConfiguration.cs.
         {
             triggerButtons.Add(outButton, inButton == null ? InputEventButton.None : (InputEventButton)inButton.Value);
         }
Install() [1/3]
void Juniper.Input.Pointers.AbstractPointerConfiguration< ButtonIDType >.Install (ButtonMapper< ButtonIDType > mapper, GameObject eventParent) inline inherited
Definition at line 22 of file AbstractPointerConfiguration.cs.
         {
             mapper.Install(eventParent, nativeButtons);
         }
Install() [2/3]
void Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.Install (ButtonMapper< VirtualTouchPadButton > mapper, GameObject eventParent) inline
Definition at line 38 of file AbstractMotionControllerConfiguration.cs.
         {
             mapper.Install(eventParent, touchPadButtons);
         }
Install() [3/3]
void Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.Install (ButtonMapper< VirtualTriggerButton > mapper, GameObject eventParent) inline
Definition at line 43 of file AbstractMotionControllerConfiguration.cs.
         {
             mapper.Install(eventParent, triggerButtons);
         }
MakePointerName()
string Juniper.Input.Pointers.Motion.AbstractHandedPointerConfiguration< HandIDType, ButtonIDType >.MakePointerName (Hands hand) inline inherited
Definition at line 20 of file AbstractHandedPointerConfiguration.cs.
         {
             return $"{hand}{PointerNameStub}";
         }
Uninstall()
void Juniper.Input.Pointers.AbstractPointerConfiguration< ButtonIDType >.Uninstall (GameObject eventParent) inline inherited
Definition at line 27 of file AbstractPointerConfiguration.cs.
         {
             foreach (var evt in eventParent.GetComponents<ButtonEvent>())
             {
                 evt.Destroy();
             }
         }
Member Data Documentation
touchPadButtons
readonly Dictionary<VirtualTouchPadButton, InputEventButton> Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.touchPadButtons = new Dictionary<VirtualTouchPadButton, InputEventButton>(11) private
Definition at line 25 of file AbstractMotionControllerConfiguration.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.AddButton(), and Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.Install().
triggerButtons
readonly Dictionary<VirtualTriggerButton, InputEventButton> Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.triggerButtons = new Dictionary<VirtualTriggerButton, InputEventButton>(3) private
Definition at line 26 of file AbstractMotionControllerConfiguration.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.AddButton(), and Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.Install().
Property Documentation
HandType
Type Juniper.Input.Pointers.Motion.AbstractHandedPointerConfiguration< HandIDType, ButtonIDType >.HandType get inherited
Definition at line 13 of file AbstractHandedPointerConfiguration.cs.
         {
             get
             {
                 return typeof(HandIDType);
             }
         }
PointerNameStub
override string Juniper.Input.Pointers.Motion.AbstractMotionControllerConfiguration< HandIDType, ButtonIDType >.PointerNameStub get protected
Definition at line 18 of file AbstractMotionControllerConfiguration.cs.
         {
             get
             {
                 return "MotionController";
             }
         }
this[Hands hand]
abstract ? HandIDType Juniper.Input.Pointers.Motion.AbstractHandedPointerConfiguration< HandIDType, ButtonIDType >.this[Hands hand] get inherited
Definition at line 30 of file AbstractHandedPointerConfiguration.cs.
 { get; }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/Pointers/Motion/AbstractMotionControllerConfiguration.cs