Juniper: UnityEngine.AudioSourceExt Class Reference
UnityEngine.AudioSourceExt Class Reference
Extensions methods for AudioSource
Static Public Member Functions
static AudioSource Spatialize (this AudioSource audioSource, AudioMixerGroup group)
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
static AudioSource Spatialize (this AudioSource audioSource, bool loop)
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
static AudioSource Spatialize (this AudioSource audioSource)
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Detailed Description
Extensions methods for AudioSource
Definition at line 12 of file AudioSourceExt.cs.
Member Function Documentation
Spatialize() [1/3]
static AudioSource UnityEngine.AudioSourceExt.Spatialize (this AudioSource audioSource, AudioMixerGroup group) inline static
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Parameters
audioSource
group
Returns
Definition at line 21 of file AudioSourceExt.cs.
         {
             return InteractionAudio.Spatialize(audioSource, false, group);
         }
References Juniper.Unity.Audio.InteractionAudio.Spatialize().
Spatialize() [2/3]
static AudioSource UnityEngine.AudioSourceExt.Spatialize (this AudioSource audioSource, bool loop) inline static
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Parameters
audioSource
loop
Returns
Definition at line 33 of file AudioSourceExt.cs.
         {
             return InteractionAudio.Spatialize(audioSource, loop, null);
         }
References Juniper.Unity.Audio.InteractionAudio.Spatialize().
Spatialize() [3/3]
static AudioSource UnityEngine.AudioSourceExt.Spatialize (this AudioSource audioSource) inline static
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Parameters
audioSource
Returns
Definition at line 44 of file AudioSourceExt.cs.
         {
             return InteractionAudio.Spatialize(audioSource, false, null);
         }
References Juniper.Unity.Audio.InteractionAudio.Spatialize().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Extensions/UnityEngine/AudioSourceExt.cs