Juniper: Juniper.Units.Angle Struct Reference
Juniper.Units.Angle Struct Reference
Represents an angle in degrees that doesn't wrap around to 0 when iterating past 360 degrees. It does this by making the update the smallest delta of value plus whole rotations. e.g. if the current value is 359, setting the value to 1 will actually return as 361, as Abs(361 - 351) < Abs(1 - 351).
Public Member Functions
Angle (float v, float r)
Create an angle value at set starting point
void GetObjectData (SerializationInfo info, StreamingContext context)
Angle (float v)
Create an angle value at set starting point
float ToSingle ()
Automatically unwrap the value of the Angle, to be able to use with other API fields that expect angle values in degrees.
Angle Xor (float v)
Create a new Angle struct that represents the smallest turn from the old Angle struct in either the clockwise or counter-clockwise direction that matches the new angle.
Angle Mod (float v)
Whole-number divide the angle and save the remainder, and minimize rotation to the new value
Angle Add (float v)
Add to the angle, and minimize rotation to the new value
Angle Subtract (float v)
Subtract from the angle, and minimize rotation to the new value
Angle Multiply (float v)
Multiply the angle, and minimize rotation to the new value
Angle Divide (float v)
Divide the angle, and minimize rotation to the new value
override bool Equals (object obj)
Compares two angles to see if they represent the same position on a circle.
bool Equals (Angle other)
override int GetHashCode ()
Serves as a hash function for a UnityEngine.Angle object.
override string ToString ()
Static Public Member Functions
static implicit operator float (Angle a)
Automatically unwrap the value of the Angle, to be able to use with other API fields that expect angle values in degrees.
static Angle FromSingle (float f)
Wrap an angle value in the Angle struct. Useful for using System.Linq.Enumerable.Cast{T} on a collection of Angles.
static operator Angle (float f)
Wrap an angle value in the Angle struct. Useful for using System.Linq.Enumerable.Cast{T} on a collection of Angles.
static Angle operator ^ (Angle a, float v)
Create a new Angle struct that represents the smallest turn from the old Angle struct in either the clockwise or counter-clockwise direction that matches the new angle.
static Angle operator % (Angle a, float v)
Whole-number divide the angle and save the remainder, and minimize rotation to the new value
static Angle operator+ (Angle a, float v)
Add to the angle, and minimize rotation to the new value
static Angle operator - (Angle a, float v)
Subtract from the angle, and minimize rotation to the new value
static Angle operator * (Angle a, float v)
Multiply the angle, and minimize rotation to the new value
static Angle operator/ (Angle a, float v)
Divide the angle, and minimize rotation to the new value
static bool operator== (Angle left, Angle right)
Compares two angles to see if they represent the same position on a circle.
static bool operator != (Angle left, Angle right)
Compares two angles to see if they do not represent the same position on a circle.
static operator string (Angle value)
Private Member Functions
Angle (SerializationInfo info, StreamingContext context)
Angle Update (float v1)
Performs the min-distance-edit operation, given the new, desired angle value.
Static Private Member Functions
static float Repeat (float v)
Private Attributes
readonly float currentValue
The current value of the angle,
readonly float rotations
The number of whole-circle rotations, times 360, we had to take to get to the current value.
Detailed Description
Represents an angle in degrees that doesn't wrap around to 0 when iterating past 360 degrees. It does this by making the update the smallest delta of value plus whole rotations. e.g. if the current value is 359, setting the value to 1 will actually return as 361, as Abs(361 - 351) < Abs(1 - 351).
Definition at line 15 of file Angle.cs.
Constructor & Destructor Documentation
Angle() [1/3]
Juniper.Units.Angle.Angle (float v, float r) inline
Create an angle value at set starting point
Parameters
v
r
You should try to instantiate the Angle at a value that is close to the first runtime-value you would receive. The system does not work well for values that oscillate over ~180 degree changes.
Definition at line 27 of file Angle.cs.
         {
             currentValue = v;
             rotations = r;
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.rotations.
Referenced by Juniper.Units.Angle.FromSingle(), and Juniper.Units.Angle.Update().
Angle() [2/3]
Juniper.Units.Angle.Angle (SerializationInfo info, StreamingContext context) inline private
Definition at line 34 of file Angle.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             currentValue = info.GetSingle("angle");
             rotations = 0;
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.rotations.
Angle() [3/3]
Juniper.Units.Angle.Angle (float v) inline
Create an angle value at set starting point
Parameters
v
r
You should try to instantiate the Angle at a value that is close to the first runtime-value you would receive. The system does not work well for values that oscillate over ~180 degree changes.
Definition at line 65 of file Angle.cs.
                               : this(v, 0)
         {
         }
Member Function Documentation
Add()
Angle Juniper.Units.Angle.Add (float v) inline
Add to the angle, and minimize rotation to the new value
Parameters
v The scalar by which to add.
Returns
The minimized value of clamp(a + v, 0, 360)
Definition at line 162 of file Angle.cs.
         {
             return Update(currentValue + v);
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Update().
Referenced by Juniper.Units.Angle.operator+().
Divide()
Angle Juniper.Units.Angle.Divide (float v) inline
Divide the angle, and minimize rotation to the new value
Parameters
v The scalar by which to divide.
Returns
The minimized value of clamp(a / v, 0, 360)
Definition at line 225 of file Angle.cs.
         {
             return Update(currentValue / v);
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Update().
Referenced by Juniper.Units.Angle.operator/().
Equals() [1/2]
override bool Juniper.Units.Angle.Equals (object obj) inline
Compares two angles to see if they represent the same position on a circle.
Parameters
obj
Returns
Definition at line 246 of file Angle.cs.
         {
             return obj is Angle angle && Equals(angle);
         }
Equals() [2/2]
bool Juniper.Units.Angle.Equals (Angle other) inline
Definition at line 251 of file Angle.cs.
         {
             var l = Repeat(currentValue);
             var r = Repeat(other.currentValue);
             return l.Equals(r);
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Repeat().
FromSingle()
static Angle Juniper.Units.Angle.FromSingle (float f) inline static
Wrap an angle value in the Angle struct. Useful for using System.Linq.Enumerable.Cast{T} on a collection of Angles.
Parameters
f An angle in degrees
Definition at line 94 of file Angle.cs.
         {
             return new Angle(f);
         }
References Juniper.Units.Angle.Angle().
Referenced by Juniper.Units.Angle.operator Angle().
GetHashCode()
override int Juniper.Units.Angle.GetHashCode () inline
Serves as a hash function for a UnityEngine.Angle object.
Returns
A hash code for this instance that is suitable for use in hashing algorithms and data structures such as a hash table.
Definition at line 302 of file Angle.cs.
         {
             return Repeat(currentValue).GetHashCode();
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Repeat().
GetObjectData()
void Juniper.Units.Angle.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 45 of file Angle.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue("angle", Repeat(currentValue));
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Repeat().
Mod()
Angle Juniper.Units.Angle.Mod (float v) inline
Whole-number divide the angle and save the remainder, and minimize rotation to the new value
Parameters
v The scalar by which to divide.
Returns
The minimized value of clamp(a % v, 0, 360)
Definition at line 141 of file Angle.cs.
         {
             return Update(currentValue % v);
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Update().
Referenced by Juniper.Units.Angle.operator %().
Multiply()
Angle Juniper.Units.Angle.Multiply (float v) inline
Multiply the angle, and minimize rotation to the new value
Parameters
v The scalar by which to multiply.
Returns
The minimized value of clamp(a * v, 0, 360)
Definition at line 204 of file Angle.cs.
         {
             return Update(currentValue * v);
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Update().
Referenced by Juniper.Units.Angle.operator *().
operator !=()
static bool Juniper.Units.Angle.operator != (Angle left, Angle right) inline static
Compares two angles to see if they do not represent the same position on a circle.
Parameters
left
right
Returns
Definition at line 275 of file Angle.cs.
         {
             return !(left == right);
         }
operator %()
static Angle Juniper.Units.Angle.operator % (Angle a, float v) inline static
Whole-number divide the angle and save the remainder, and minimize rotation to the new value
Parameters
a The angle to divide.
v The scalar by which to divide.
Returns
The minimized value of clamp(a % v, 0, 360)
Definition at line 152 of file Angle.cs.
         {
             return a.Mod(v);
         }
References Juniper.Units.Angle.Mod().
operator *()
static Angle Juniper.Units.Angle.operator * (Angle a, float v) inline static
Multiply the angle, and minimize rotation to the new value
Parameters
a The angle to multiply.
v The scalar by which to multiply.
Returns
The minimized value of clamp(a * v, 0, 360)
Definition at line 215 of file Angle.cs.
         {
             return a.Multiply(v);
         }
References Juniper.Units.Angle.Multiply().
operator -()
static Angle Juniper.Units.Angle.operator - (Angle a, float v) inline static
Subtract from the angle, and minimize rotation to the new value
Parameters
a The angle to subtract from.
v The scalar by which to subtract.
Returns
The minimized value of clamp(a - v, 0, 360)
Definition at line 194 of file Angle.cs.
         {
             return a.Subtract(v);
         }
References Juniper.Units.Angle.Subtract().
operator ^()
static Angle Juniper.Units.Angle.operator ^ (Angle a, float v) inline static
Create a new Angle struct that represents the smallest turn from the old Angle struct in either the clockwise or counter-clockwise direction that matches the new angle.
Parameters
a The old Angle struct.
v The new angle value, in degrees.
Returns
The new Angle struct that minimizes the likelihood of spinning around in weird circles.
Definition at line 131 of file Angle.cs.
         {
             return a.Xor(v);
         }
References Juniper.Units.Angle.Xor().
operator Angle()
static Juniper.Units.Angle.operator Angle (float f) inline explicit static
Wrap an angle value in the Angle struct. Useful for using System.Linq.Enumerable.Cast{T} on a collection of Angles.
Parameters
f An angle in degrees
Definition at line 104 of file Angle.cs.
         {
             return FromSingle(f);
         }
References Juniper.Units.Angle.FromSingle().
operator float()
static implicit Juniper.Units.Angle.operator float (Angle a) inline static
Automatically unwrap the value of the Angle, to be able to use with other API fields that expect angle values in degrees.
Parameters
a An Angle object.
Definition at line 84 of file Angle.cs.
         {
             return a.ToSingle();
         }
References Juniper.Units.Angle.ToSingle().
operator string()
static Juniper.Units.Angle.operator string (Angle value) inline explicit static
Definition at line 359 of file Angle.cs.
         {
             return value.ToString();
         }
References Juniper.Units.Angle.ToString().
operator+()
static Angle Juniper.Units.Angle.operator+ (Angle a, float v) inline static
Add to the angle, and minimize rotation to the new value
Parameters
a The angle to add to.
v The scalar by which to add.
Returns
The minimized value of clamp(a + v, 0, 360)
Definition at line 173 of file Angle.cs.
         {
             return a.Add(v);
         }
References Juniper.Units.Angle.Add().
operator/()
static Angle Juniper.Units.Angle.operator/ (Angle a, float v) inline static
Divide the angle, and minimize rotation to the new value
Parameters
a The angle to divide.
v The scalar by which to divide.
Returns
The minimized value of clamp(a / v, 0, 360)
Definition at line 236 of file Angle.cs.
         {
             return a.Divide(v);
         }
References Juniper.Units.Angle.Divide().
operator==()
static bool Juniper.Units.Angle.operator== (Angle left, Angle right) inline static
Compares two angles to see if they represent the same position on a circle.
Parameters
left
right
Returns
Definition at line 264 of file Angle.cs.
         {
             return left.Equals(right);
         }
Repeat()
static float Juniper.Units.Angle.Repeat (float v) inline static private
Definition at line 280 of file Angle.cs.
         {
             while (v >= 360)
             {
                 v -= 360;
             }
             while (v < 0)
             {
                 v += 360;
             }
             return v;
         }
Referenced by Juniper.Units.Angle.Equals(), Juniper.Units.Angle.GetHashCode(), Juniper.Units.Angle.GetObjectData(), and Juniper.Units.Angle.Update().
Subtract()
Angle Juniper.Units.Angle.Subtract (float v) inline
Subtract from the angle, and minimize rotation to the new value
Parameters
v The scalar by which to subtract.
Returns
The minimized value of clamp(a - v, 0, 360)
Definition at line 183 of file Angle.cs.
         {
             return Update(currentValue - v);
         }
References Juniper.Units.Angle.currentValue, and Juniper.Units.Angle.Update().
Referenced by Juniper.Units.Angle.operator -().
ToSingle()
float Juniper.Units.Angle.ToSingle () inline
Automatically unwrap the value of the Angle, to be able to use with other API fields that expect angle values in degrees.
Parameters
a An Angle object.
Definition at line 74 of file Angle.cs.
         {
             return currentValue;
         }
References Juniper.Units.Angle.currentValue.
Referenced by Juniper.Units.Angle.operator float().
ToString()
override string Juniper.Units.Angle.ToString () inline
Definition at line 354 of file Angle.cs.
         {
             return currentValue.Label(UnitOfMeasure.Degrees);
         }
References Juniper.Units.Angle.currentValue.
Referenced by Juniper.Units.Angle.operator string().
Update()
Angle Juniper.Units.Angle.Update (float v1) inline private
Performs the min-distance-edit operation, given the new, desired angle value.
Returns
The update.
Parameters
v1 V1.
Definition at line 322 of file Angle.cs.
         {
             var r = rotations;
             var v0 = currentValue;
             v1 = Repeat(v1);
             float d1;
             float d2;
             float d3;
             do
             {
                 // figure out if it is adding the raw value, or whole rotations of the value, that
                 // results in a smaller magnitude of change.
                 d1 = v1 + r - v0;
                 d2 = Abs(d1 + 360);
                 d3 = Abs(d1 - 360);
                 d1 = Abs(d1);
                 if (d2 < d1 && d2 < d3)
                 {
                     r += 360;
                 }
                 else if (d3 < d1)
                 {
                     r -= 360;
                 }
             } while (d1 > d2 || d1 > d3);
             return new Angle(v1 + r, r);
         }
References Juniper.Units.Angle.Angle(), Juniper.Units.Angle.currentValue, Juniper.Units.Angle.Repeat(), and Juniper.Units.Angle.rotations.
Referenced by Juniper.Units.Angle.Add(), Juniper.Units.Angle.Divide(), Juniper.Units.Angle.Mod(), Juniper.Units.Angle.Multiply(), Juniper.Units.Angle.Subtract(), and Juniper.Units.Angle.Xor().
Xor()
Angle Juniper.Units.Angle.Xor (float v) inline
Create a new Angle struct that represents the smallest turn from the old Angle struct in either the clockwise or counter-clockwise direction that matches the new angle.
Parameters
v The new angle value, in degrees.
Returns
The new Angle struct that minimizes the likelihood of spinning around in weird circles.
Definition at line 117 of file Angle.cs.
         {
             return Update(v);
         }
References Juniper.Units.Angle.Update().
Referenced by Juniper.Units.Angle.operator ^().
Member Data Documentation
currentValue
readonly float Juniper.Units.Angle.currentValue private
The current value of the angle,
Definition at line 310 of file Angle.cs.
Referenced by Juniper.Units.Angle.Add(), Juniper.Units.Angle.Angle(), Juniper.Units.Angle.Divide(), Juniper.Units.Angle.Equals(), Juniper.Units.Angle.GetHashCode(), Juniper.Units.Angle.GetObjectData(), Juniper.Units.Angle.Mod(), Juniper.Units.Angle.Multiply(), Juniper.Units.Angle.Subtract(), Juniper.Units.Angle.ToSingle(), Juniper.Units.Angle.ToString(), and Juniper.Units.Angle.Update().
rotations
readonly float Juniper.Units.Angle.rotations private
The number of whole-circle rotations, times 360, we had to take to get to the current value.
Definition at line 315 of file Angle.cs.
Referenced by Juniper.Units.Angle.Angle(), and Juniper.Units.Angle.Update().
The documentation for this struct was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Units/Angles/Angle.cs