Juniper: Juniper.ConfigurationManagement.JuniperPlatformSelector Class Reference
Juniper.ConfigurationManagement.JuniperPlatformSelector Class Reference
An editor to respond to changes in XRSystem.
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void ShowJuniperWindow ()
Static Private Member Functions
static void DrawStatus (Platforms platforms, PlatformType selectedPlatform, PlatformConfiguration currentConfiguration, BuildTargetGroup targetGroup)
Private Attributes
const string MENU_NAME = "Juniper/"
const int buttonWidthValue = 100
Static Private Attributes
static readonly GUIContent TITLE = new GUIContent("Juniper - Platform")
static readonly GUILayoutOption nameFieldWidth = GUILayout.Width(200)
static readonly GUILayoutOption buttonWidth = GUILayout.Width(buttonWidthValue)
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 21 of file JuniperPlatformSelector.cs.
Member Function Documentation
DrawStatus()
static void Juniper.ConfigurationManagement.JuniperPlatformSelector.DrawStatus (Platforms platforms, PlatformType selectedPlatform, PlatformConfiguration currentConfiguration, BuildTargetGroup targetGroup) inline static private
Definition at line 56 of file JuniperPlatformSelector.cs.
         {
             using (new Header("Status"))
             {
                 EditorGUILayoutExt.LabeledField("Current platform", nameFieldWidth, selectedPlatform, nameFieldWidth);
                 EditorGUILayoutExt.LabeledField("Current build target", nameFieldWidth, targetGroup, nameFieldWidth);
                 if (targetGroup == BuildTargetGroup.Android)
                 {
                     EditorGUILayoutExt.LabeledField("Min Android SDK version", nameFieldWidth, currentConfiguration.AndroidSdkVersion, nameFieldWidth);
                 }
                 using (new HGroup())
                 {
                     EditorGUILayout.LabelField("Change platform", nameFieldWidth);
                     selectedPlatform = (PlatformType)EditorGUILayout.EnumPopup(selectedPlatform, nameFieldWidth);
                     if (selectedPlatform != ProjectConfiguration.Platform)
                     {
                         var nextPlatform = platforms.Configurations[selectedPlatform];
                         if (nextPlatform.IsSupported())
{
                             ProjectConfiguration.Platform = nextPlatform.Name;
                             nextPlatform.SwitchTarget();
                         }
                         else
{
                             EditorUtility.DisplayDialog(
                                "Juniper",
                                $"The platform {selectedPlatform} is not supported on your current system.",
                                "OK");
                         }
                     }
                 }
                 using (new EnabledScope(!currentConfiguration.IsActivated()))
                 {
                     if (GUILayout.Button("Activate", buttonWidth))
                     {
                         currentConfiguration.Activate();
                     }
                 }
             }
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.ConfigurationManagement.PlatformConfiguration.AndroidSdkVersion, Juniper.ConfigurationManagement.JuniperPlatformSelector.buttonWidth, Juniper.ConfigurationManagement.Platforms.Configurations, Juniper.ConfigurationManagement.PlatformConfiguration.IsActivated(), Juniper.ConfigurationManagement.JuniperPlatformSelector.nameFieldWidth, and Juniper.ProjectConfiguration.Platform.
Referenced by Juniper.ConfigurationManagement.JuniperPlatformSelector.OnGUI().
OnGUI()
void Juniper.ConfigurationManagement.JuniperPlatformSelector.OnGUI () inline
Definition at line 37 of file JuniperPlatformSelector.cs.
         {
             titleContent = TITLE;
             if (EditorApplication.isCompiling)
             {
                 EditorGUILayout.LabelField("Compiling...");
             }
             else
             {
                 var platforms = Platforms.Load();
                 var selectedPlatform = ProjectConfiguration.Platform;
                 var currentConfiguration = platforms.Configurations[selectedPlatform];
                 var targetGroup = currentConfiguration.GetTargetGroup();
                 DrawStatus(platforms, selectedPlatform, currentConfiguration, targetGroup);
             }
         }
References Juniper.ConfigurationManagement.JuniperPlatformSelector.DrawStatus(), Juniper.ConfigurationManagement.Platforms.Load(), Juniper.ProjectConfiguration.Platform, and Juniper.ConfigurationManagement.JuniperPlatformSelector.TITLE.
ShowJuniperWindow()
static void Juniper.ConfigurationManagement.JuniperPlatformSelector.ShowJuniperWindow () inline static
Definition at line 24 of file JuniperPlatformSelector.cs.
         {
             EditorWindow.GetWindow<JuniperPlatformSelector>();
         }
Member Data Documentation
buttonWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperPlatformSelector.buttonWidth = GUILayout.Width(buttonWidthValue) static private
Definition at line 35 of file JuniperPlatformSelector.cs.
Referenced by Juniper.ConfigurationManagement.JuniperPlatformSelector.DrawStatus().
buttonWidthValue
const int Juniper.ConfigurationManagement.JuniperPlatformSelector.buttonWidthValue = 100 private
Definition at line 32 of file JuniperPlatformSelector.cs.
MENU_NAME
const string Juniper.ConfigurationManagement.JuniperPlatformSelector.MENU_NAME = "Juniper/" private
Definition at line 29 of file JuniperPlatformSelector.cs.
nameFieldWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperPlatformSelector.nameFieldWidth = GUILayout.Width(200) static private
Definition at line 34 of file JuniperPlatformSelector.cs.
Referenced by Juniper.ConfigurationManagement.JuniperPlatformSelector.DrawStatus().
TITLE
readonly GUIContent Juniper.ConfigurationManagement.JuniperPlatformSelector.TITLE = new GUIContent("Juniper - Platform") static private
Definition at line 30 of file JuniperPlatformSelector.cs.
Referenced by Juniper.ConfigurationManagement.JuniperPlatformSelector.OnGUI().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Editor Plugins/ConfigurationManagement/JuniperPlatformSelector.cs