Juniper: Juniper.Primrose.BasicInterpreter Class Reference
Juniper.Primrose.BasicInterpreter Class Reference
Public Member Functions
BasicInterpreter (string source, Line tokens)
void Interpret ()
bool ConditionalReturn (bool cond)
Events
EventHandler< Action< Func< string, byte[]> > > LoadFile
EventHandler< Action< string > > Input
EventHandler< StringEventArgs > Output
EventHandler< ErrorEventArgs > RuntimeError
EventHandler ClearScreen
EventHandler ContinueNext
EventHandler Done
Private Member Functions
void OnOutput (string msg)
void OnInput (Action< string > resume)
void OnError (Line line, string script, Exception exp)
void OnClearScreen ()
bool OnClearScreen (Line line)
byte [] OnLoadFile (string fileName)
void OnNext ()
void OnDone ()
bool IsFunction (Token t)
string Evaluate (Line line)
bool Translate (Line line)
bool LoadData (Line line)
bool PauseBeforeComplete (Line line)
bool Process (Line line)
bool SetProgramCounter (Line line)
void OnError (string msg)
Line GetLine (int i)
bool LabelLine (Line line)
bool NoOp (Line line)
bool GoToSubroutine (Line line)
bool SetRepeat (Line line)
bool DeclareVariable (Line line)
bool Print (Line line)
bool CheckConditional (Line line)
bool WaitForInput (Line line)
bool OnStatement (Line line)
bool UntilLoop (Line line)
int FindNext (string str)
bool WhileLoop (Line line)
bool ForLoop (Line line)
bool StackReturn (Line line)
bool LoadCodeFile (Line line)
bool ReadData (Line line)
bool RestoreData (Line line)
bool DefineFunction (Line line)
Static Private Member Functions
static Token ToNum (int i)
static Token ToStr (string str)
static object Eval (string script)
Private Attributes
readonly Dictionary< string, Func< Line, bool > > commands
readonly Dictionary< string, object > state
readonly string source
readonly Dictionary< int, Line > program = new Dictionary<int, Line>()
readonly List< int > lineNumbers = new List<int>()
readonly List< Line > lines = new List<Line>()
readonly Random random = new Random()
readonly Stack< Token > returnStack = new Stack<Token>()
readonly Dictionary< int, int > forLoopCounters = new Dictionary<int, int>()
readonly List< string > data = new List<string>()
int counter = 0
bool isDone = false
int dataCounter = 0
Static Private Attributes
static readonly string [] FOR_LOOP_DELIMS = new[] { "=", "TO", "STEP" }
static readonly Token EQUAL_SIGN = new Token("=", "operators")
static readonly DateTime EPOCH = new DateTime(1970, 1, 1, 0, 0, 0)
static readonly Dictionary< string, string > tokenMap
Detailed Description
Definition at line 12 of file BasicInterpreter.cs.
Constructor & Destructor Documentation
BasicInterpreter()
Juniper.Primrose.BasicInterpreter.BasicInterpreter (string source, Line tokens) inline
Definition at line 56 of file BasicInterpreter.cs.
         {
             if (tokens is null)
             {
                 throw new ArgumentNullException(nameof(tokens));
             }
             commands = new Dictionary<string, Func<Line, bool>>
                 {
                     { "DIM", DeclareVariable },
                     { "LET", Translate },
                     { "PRINT", Print },
                     { "GOTO", SetProgramCounter },
                     { "IF", CheckConditional },
                     { "INPUT", WaitForInput },
                     { "END", PauseBeforeComplete },
                     { "STOP", PauseBeforeComplete },
                     { "REM", NoOp },
                     { "'", NoOp },
                     { "CLS", OnClearScreen },
                     { "ON", OnStatement },
                     { "GOSUB", GoToSubroutine },
                     { "RETURN", StackReturn },
                     { "LOAD", LoadCodeFile },
                     { "DATA", LoadData },
                     { "READ", ReadData },
                     { "RESTORE", RestoreData },
                     { "REPEAT", SetRepeat },
                     { "UNTIL", UntilLoop },
                     { "DEF FN", DefineFunction },
                     { "WHILE", WhileLoop },
                     { "WEND", StackReturn },
                     { "FOR", ForLoop },
                     { "NEXT", StackReturn },
                     { "LABEL", LabelLine }
                 };
             state = new Dictionary<string, object>
                 {
                     { "INT", new Func<float, int>(v => (int) v) },
                     { "CLK", new Func<float>(() => (float)(DateTime.Now - EPOCH).TotalHours) },
                     { "LEN", new Func<string, int>(str => str.Length) },
                     { "POW", new Func<float, float, float>((b, e) => (float)Math.Pow(b, e)) },
                     { "LINE", new Func<int>(() => lineNumbers[counter]) },
                     { "RND", new Func<float>(() => (float)random.NextDouble()) },
                     { "TAB", new Func<int, string>(num =>
                     {
                         var str = "";
                         for(var i = 0; i < num; ++i)
{
                             str += '\t';
                         }
                         return str;
                     }) }
                 };
             this.source = source;
             // Remove comments and whitespace, and do a light translation of
             // operator tokens.
             var currentLine = new Line();
             while (tokens.Count > 0)
             {
                 var token = tokens[0];
                 tokens.RemoveAt(0);
                 if (token.Type == "newlines")
                 {
                     currentLine = new Line();
                     lines.Add(currentLine);
                 }
                 else if (token.Type != "regular" && token.Type != "comments")
                 {
                     token.Value = tokenMap.Get(token.Value, token.Value);
                     currentLine.Add(token);
                 }
             }
             // Parse the line numbers for the program
             int? lastLineNumber = null;
             for (var i = 0; i < lines.Count; ++i)
             {
                 var line = lines[i];
                 if (line.Count > 0)
                 {
                     var lineNumberToken = line[0];
                     line.RemoveAt(0);
                     // If the first token of a line is not actually a line number,
                     // we will auto-generate a line number and re-insert the token
                     // to be processed as normal code.
                     if (lineNumberToken.Type != "lineNumbers")
                     {
                         line.Insert(0, lineNumberToken);
                         lineNumberToken = ToNum((lastLineNumber ?? -1) + 1);
                     }
                     var lineNumber = int.Parse(
                         lineNumberToken.Value,
                         NumberStyles.AllowLeadingWhite
                             | NumberStyles.AllowTrailingWhite,
                         CultureInfo.InvariantCulture);
                     // Line numbers should be ordered correctly, or we throw a syntax error.
                     if (lastLineNumber.HasValue && lineNumber <= lastLineNumber)
                     {
                         throw new Exception($"expected line number greater than {lastLineNumber.Value.ToString(CultureInfo.CurrentCulture)}, but received {lineNumberToken.Value}.");
                     }
                     // deleting empty lines
                     else if (line.Count > 0)
                     {
                         lineNumberToken.Value = lineNumber.ToString(CultureInfo.InvariantCulture);
                         lineNumbers.Add(lineNumber);
                         program[lineNumber] = line;
                     }
                     lastLineNumber = lineNumber;
                 }
             }
         }
References Juniper.Primrose.BasicInterpreter.CheckConditional(), Juniper.Primrose.BasicInterpreter.commands, Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.DeclareVariable(), Juniper.Primrose.BasicInterpreter.DefineFunction(), Juniper.Primrose.BasicInterpreter.EPOCH, Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.GoToSubroutine(), Juniper.Primrose.BasicInterpreter.LabelLine(), Juniper.Primrose.BasicInterpreter.lineNumbers, Juniper.Primrose.BasicInterpreter.lines, Juniper.Primrose.BasicInterpreter.LoadCodeFile(), Juniper.Primrose.BasicInterpreter.LoadData(), Juniper.Primrose.BasicInterpreter.NoOp(), Juniper.Primrose.BasicInterpreter.OnClearScreen(), Juniper.Primrose.BasicInterpreter.OnStatement(), Juniper.Primrose.BasicInterpreter.PauseBeforeComplete(), Juniper.Primrose.BasicInterpreter.Print(), Juniper.Primrose.BasicInterpreter.program, Juniper.Primrose.BasicInterpreter.random, Juniper.Primrose.BasicInterpreter.ReadData(), Juniper.Primrose.BasicInterpreter.RestoreData(), Juniper.Primrose.BasicInterpreter.SetProgramCounter(), Juniper.Primrose.BasicInterpreter.SetRepeat(), Juniper.Primrose.BasicInterpreter.source, Juniper.Primrose.BasicInterpreter.StackReturn(), Juniper.Primrose.BasicInterpreter.state, Juniper.Primrose.BasicInterpreter.tokenMap, Juniper.Primrose.BasicInterpreter.ToNum(), Juniper.Primrose.BasicInterpreter.Translate(), Juniper.Primrose.BasicInterpreter.UntilLoop(), Juniper.Primrose.BasicInterpreter.WaitForInput(), and Juniper.Primrose.BasicInterpreter.WhileLoop().
Member Function Documentation
CheckConditional()
bool Juniper.Primrose.BasicInterpreter.CheckConditional (Line line) inline private
Definition at line 594 of file BasicInterpreter.cs.
         {
             var thenIndex = -1;
             var elseIndex = -1;
             for (var i = 0; i < line.Count; ++i)
             {
                 if (line[i].Type == "keywords" && line[i].Value == "THEN")
                 {
                     thenIndex = i;
                 }
                 else if (line[i].Type == "keywords" && line[i].Value == "ELSE")
                 {
                     elseIndex = i;
                 }
             }
             if (thenIndex == -1)
             {
                 OnError("Expected THEN clause.");
             }
             else
             {
                 var condition = line.GetRange(0, thenIndex);
                 for (var i = 0; i < condition.Count; ++i)
                 {
                     var t = condition[i];
                     if (t.Type == "operators" && t.Value == "=")
                     {
                         t.Value = "==";
                     }
                 }
                 Line elseClause = null;
                 Line thenClause;
                 if (elseIndex == -1)
                 {
                     thenClause = line.GetRange(thenIndex + 1, line.Count - thenIndex - 1);
                 }
                 else
                 {
                     thenClause = line.GetRange(thenIndex + 1, elseIndex - thenIndex - 1);
                     elseClause = line.GetRange(elseIndex + 1, line.Count - elseIndex - 1);
                 }
                 if (Evaluate(condition) == "True")
                 {
                     return Process(thenClause);
                 }
                 else if (elseClause is object)
                 {
                     return Process(elseClause);
                 }
             }
             return true;
         }
References Juniper.Primrose.BasicInterpreter.Evaluate(), Juniper.Primrose.BasicInterpreter.OnError(), and Juniper.Primrose.BasicInterpreter.Process().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
ConditionalReturn()
bool Juniper.Primrose.BasicInterpreter.ConditionalReturn (bool cond) inline
Definition at line 720 of file BasicInterpreter.cs.
         {
             var ret = true;
             if (cond && returnStack.Count > 0)
             {
                 var val = returnStack.Pop();
                 ret = SetProgramCounter(new Line { val });
             }
             return ret;
         }
References Juniper.Primrose.BasicInterpreter.returnStack, and Juniper.Primrose.BasicInterpreter.SetProgramCounter().
Referenced by Juniper.Primrose.BasicInterpreter.StackReturn(), and Juniper.Primrose.BasicInterpreter.UntilLoop().
DeclareVariable()
bool Juniper.Primrose.BasicInterpreter.DeclareVariable (Line line) inline private
Definition at line 456 of file BasicInterpreter.cs.
         {
             var decl = new Line();
             var decls = new List<Line> { decl };
             var nest = 0;
             for (var i = 0; i < line.Count; ++i)
             {
                 var t = line[i];
                 if (t.Value == "(")
                 {
                     ++nest;
                 }
                 else if (t.Value == ")")
                 {
                     --nest;
                 }
                 if (nest == 0 && t.Value == ",")
                 {
                     decl = new Line();
                     decls.Add(decl);
                 }
                 else
                 {
                     decl.Add(t);
                 }
             }
             for (var i = 0; i < decls.Count; ++i)
             {
                 decl = decls[i];
                 var idToken = decl[0];
                 decl.RemoveAt(0);
                 if (idToken.Type != "identifiers")
                 {
                     OnError("Identifier expected: " + idToken.Value);
                 }
                 else
                 {
                     var id = idToken.Value;
                     object val = null;
                     if (decl[0].Value == "("
                         && decl.Last().Value == ")")
                     {
                         var sizes = new List<int>();
                         for (var j = 1; j < decl.Count - 1; ++j)
{
                             if (decl[j].Type == "numbers")
{
                                 sizes.Add(int.Parse(decl[j].Value, CultureInfo.InvariantCulture));
                             }
                         }
                         if (sizes.Count == 0)
{
                             val = new List<object>();
                         }
                         else
{
                             val = new object[sizes[0]];
                             var queue = new Queue<object[]> { (object[])val };
                             for (var j = 1; j < sizes.Count; ++j)
{
                                 var size = sizes[j];
                                 for (int k = 0, l = queue.Count; k < l; ++k)
{
                                     var arr = queue.Dequeue();
                                     for (var m = 0; m < arr.Length; ++m)
{
                                         var subArr = new object[size];
                                         arr[m] = subArr;
                                         if (j < sizes.Count - 1)
{
                                             queue.Enqueue(subArr);
                                         }
                                     }
                                 }
                             }
                         }
                     }
                     state[id] = val;
                 }
             }
             return true;
         }
References Juniper.Primrose.BasicInterpreter.OnError(), and Juniper.Primrose.BasicInterpreter.state.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
DefineFunction()
bool Juniper.Primrose.BasicInterpreter.DefineFunction (Line line) inline private
Definition at line 861 of file BasicInterpreter.cs.
         {
             var nameToken = line[0];
             line.RemoveAt(0);
             var name = nameToken.Value;
             var signature = "";
             var body = "";
             var fillSig = true;
             for (var i = 0; i < line.Count; ++i)
             {
                 var t = line[i];
                 if (t.Type == "operators" && t.Value == "=")
                 {
                     fillSig = false;
                 }
                 else if (fillSig)
                 {
                     signature += t.Value;
                 }
                 else
                 {
                     body += t.Value;
                 }
             }
             name = "FN" + name;
             var script = "(function " + name + signature + "{ return " + body +
               "; })";
             state[name] = Eval(script); // jshint ignore:line
             return true;
         }
References Juniper.Primrose.BasicInterpreter.Eval(), and Juniper.Primrose.BasicInterpreter.state.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
Eval()
static object Juniper.Primrose.BasicInterpreter.Eval (string script) inline static private
Definition at line 896 of file BasicInterpreter.cs.
         {
             if (string.IsNullOrEmpty(script))
             {
                 throw new ArgumentNullException(nameof(script));
             }
             throw new NotImplementedException();
         }
Referenced by Juniper.Primrose.BasicInterpreter.DefineFunction().
Evaluate()
string Juniper.Primrose.BasicInterpreter.Evaluate (Line line) inline private
Definition at line 270 of file BasicInterpreter.cs.
         {
             var script = "";
             for (var i = 0; i < line.Count; ++i)
             {
                 var t = line[i];
                 var nest = 0;
                 if (t.Type == "identifiers"
                     && !IsFunction(t)
                     && i < line.Count - 1
                     && line[i + 1].Value == "(")
                 {
                     for (var j = i + 1; j < line.Count; ++j)
                     {
                         var t2 = line[j];
                         if (t2.Value == "(")
{
                             if (nest == 0)
{
                                 t2.Value = "[";
                             }
                             ++nest;
                         }
                         else if (t2.Value == ")")
{
                             --nest;
                             if (nest == 0)
{
                                 t2.Value = "]";
                             }
                         }
                         else if (t2.Value == "," && nest == 1)
{
                             t2.Value = "][";
                         }
                         if (nest == 0)
{
                             break;
                         }
                     }
                 }
                 script += t.Value;
             }
             //with ( state ) { // jshint ignore:line
             try
             {
                 return null;
                 //return eval2(script); // jshint ignore:line
             }
             catch (Exception exp)
             {
                 OnError(line, script, exp);
                 return null;
             }
             //}
         }
References Juniper.Primrose.BasicInterpreter.IsFunction(), and Juniper.Primrose.BasicInterpreter.OnError().
Referenced by Juniper.Primrose.BasicInterpreter.CheckConditional(), Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.LoadCodeFile(), Juniper.Primrose.BasicInterpreter.OnStatement(), Juniper.Primrose.BasicInterpreter.Print(), Juniper.Primrose.BasicInterpreter.SetProgramCounter(), Juniper.Primrose.BasicInterpreter.Translate(), Juniper.Primrose.BasicInterpreter.UntilLoop(), Juniper.Primrose.BasicInterpreter.WaitForInput(), and Juniper.Primrose.BasicInterpreter.WhileLoop().
FindNext()
int Juniper.Primrose.BasicInterpreter.FindNext (string str) inline private
Definition at line 738 of file BasicInterpreter.cs.
         {
             for (var i = counter + 1; i < lineNumbers.Count; ++i)
             {
                 var l = GetLine(i);
                 if (l[0].Value == str)
                 {
                     return i;
                 }
             }
             return lineNumbers.Count;
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.GetLine(), and Juniper.Primrose.BasicInterpreter.lineNumbers.
Referenced by Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.ReadData(), and Juniper.Primrose.BasicInterpreter.WhileLoop().
ForLoop()
bool Juniper.Primrose.BasicInterpreter.ForLoop (Line line) inline private
Definition at line 767 of file BasicInterpreter.cs.
         {
             var n = lineNumbers[counter];
             var varExpr = new Line();
             var fromExpr = new Line();
             var toExpr = new Line();
             var skipExpr = new Line();
             var arrs = new[] { varExpr, fromExpr, toExpr, skipExpr };
             var a = 0;
             for (var i = 0; i < line.Count; ++i)
             {
                 var t = line[i];
                 if (t.Value == FOR_LOOP_DELIMS[a])
                 {
                     if (a == 0)
                     {
                         varExpr.Add(t);
                     }
                     ++a;
                 }
                 else
                 {
                     arrs[a].Add(t);
                 }
             }
             var skip = 1;
             if (skipExpr.Count > 0)
             {
                 skip = int.Parse(Evaluate(skipExpr), CultureInfo.InvariantCulture);
             }
             if (!forLoopCounters.ContainsKey(n))
             {
                 forLoopCounters[n] = int.Parse(Evaluate(fromExpr), CultureInfo.InvariantCulture);
             }
             var end = int.Parse(Evaluate(toExpr), CultureInfo.InvariantCulture);
             var cond = forLoopCounters[n] <= end;
             if (!cond)
             {
                 _ = forLoopCounters.Remove(n);
                 counter = FindNext("NEXT");
             }
             else
             {
                 varExpr.Add(ToNum(forLoopCounters[n]));
                 _ = Process(varExpr);
                 forLoopCounters[n] += skip;
                 returnStack.Push(ToNum(lineNumbers[counter]));
             }
             return true;
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.Evaluate(), Juniper.Primrose.BasicInterpreter.FindNext(), Juniper.Primrose.BasicInterpreter.FOR_LOOP_DELIMS, Juniper.Primrose.BasicInterpreter.forLoopCounters, Juniper.Primrose.BasicInterpreter.lineNumbers, Juniper.Primrose.BasicInterpreter.Process(), Juniper.Primrose.BasicInterpreter.returnStack, and Juniper.Primrose.BasicInterpreter.ToNum().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
GetLine()
Line Juniper.Primrose.BasicInterpreter.GetLine (int i) inline private
Definition at line 414 of file BasicInterpreter.cs.
         {
             if (0 <= i && i < lineNumbers.Count)
             {
                 var lineNumber = lineNumbers[i];
                 if (program.ContainsKey(lineNumber))
                 {
                     var line = program[lineNumber];
                     if (line is object)
                     {
                         return line.Clone();
                     }
                 }
             }
             return null;
         }
References Juniper.Primrose.BasicInterpreter.lineNumbers, and Juniper.Primrose.BasicInterpreter.program.
Referenced by Juniper.Primrose.BasicInterpreter.FindNext(), Juniper.Primrose.BasicInterpreter.Interpret(), and Juniper.Primrose.BasicInterpreter.ReadData().
GoToSubroutine()
bool Juniper.Primrose.BasicInterpreter.GoToSubroutine (Line line) inline private
Definition at line 444 of file BasicInterpreter.cs.
         {
             returnStack.Push(ToNum(lineNumbers[counter + 1]));
             return SetProgramCounter(line);
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.lineNumbers, Juniper.Primrose.BasicInterpreter.returnStack, Juniper.Primrose.BasicInterpreter.SetProgramCounter(), and Juniper.Primrose.BasicInterpreter.ToNum().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
Interpret()
void Juniper.Primrose.BasicInterpreter.Interpret () inline
Implements Juniper.Primrose.IInterpreter.
Definition at line 245 of file BasicInterpreter.cs.
         {
             if (!isDone)
             {
                 var goNext = true;
                 while (goNext)
                 {
                     var line = GetLine(counter);
                     goNext = Process(line);
                     ++counter;
                 }
             }
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.GetLine(), Juniper.Primrose.BasicInterpreter.isDone, and Juniper.Primrose.BasicInterpreter.Process().
IsFunction()
bool Juniper.Primrose.BasicInterpreter.IsFunction (Token t) inline private
Definition at line 259 of file BasicInterpreter.cs.
         {
             if (t is object
                 && state.ContainsKey(t.Value))
             {
                 return state[t.Value] is Delegate;
             }
             return false;
         }
References Juniper.Primrose.BasicInterpreter.state, and Juniper.Primrose.Token.Value.
Referenced by Juniper.Primrose.BasicInterpreter.Evaluate().
LabelLine()
bool Juniper.Primrose.BasicInterpreter.LabelLine (Line line) inline private
Definition at line 432 of file BasicInterpreter.cs.
         {
             line.Add(EQUAL_SIGN);
             line.Add(ToNum(lineNumbers[counter]));
             return Translate(line);
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.EQUAL_SIGN, Juniper.Primrose.BasicInterpreter.lineNumbers, Juniper.Primrose.BasicInterpreter.ToNum(), and Juniper.Primrose.BasicInterpreter.Translate().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
LoadCodeFile()
bool Juniper.Primrose.BasicInterpreter.LoadCodeFile (Line line) inline private
Definition at line 829 of file BasicInterpreter.cs.
         {
             var fileName = Evaluate(line);
             var data = OnLoadFile(fileName);
             _ = Encoding.UTF8.GetString(data);
             OnError("Don't know what to do with loading files yet");
             return false;
         }
References Juniper.Primrose.BasicInterpreter.data, Juniper.Primrose.BasicInterpreter.Evaluate(), Juniper.Primrose.BasicInterpreter.OnError(), and Juniper.Primrose.BasicInterpreter.OnLoadFile().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
LoadData()
bool Juniper.Primrose.BasicInterpreter.LoadData (Line line) inline private
Definition at line 336 of file BasicInterpreter.cs.
         {
             while (line.Count > 0)
             {
                 var t = line[0];
                 line.RemoveAt(0);
                 if (t.Type != "operators")
                 {
                     data.Add(t.Value);
                 }
             }
             return true;
         }
References Juniper.Primrose.BasicInterpreter.data.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
NoOp()
bool Juniper.Primrose.BasicInterpreter.NoOp (Line line) inline private
Definition at line 439 of file BasicInterpreter.cs.
         {
             return true;
         }
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
OnClearScreen() [1/2]
void Juniper.Primrose.BasicInterpreter.OnClearScreen () inline private
Definition at line 212 of file BasicInterpreter.cs.
         {
             ClearScreen?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Primrose.BasicInterpreter.ClearScreen.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), and Juniper.Primrose.BasicInterpreter.OnClearScreen().
OnClearScreen() [2/2]
bool Juniper.Primrose.BasicInterpreter.OnClearScreen (Line line) inline private
Definition at line 218 of file BasicInterpreter.cs.
         {
             OnClearScreen();
             return true;
         }
References Juniper.Primrose.BasicInterpreter.OnClearScreen().
OnDone()
void Juniper.Primrose.BasicInterpreter.OnDone () inline private
Definition at line 240 of file BasicInterpreter.cs.
         {
             Done?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Primrose.BasicInterpreter.Done.
Referenced by Juniper.Primrose.BasicInterpreter.PauseBeforeComplete().
OnError() [1/2]
void Juniper.Primrose.BasicInterpreter.OnError (Line line, string script, Exception exp) inline private
Definition at line 206 of file BasicInterpreter.cs.
         {
             RuntimeError?.Invoke(this, new ErrorEventArgs(new RuntimeException(source, line, script, exp)));
         }
References Juniper.Primrose.BasicInterpreter.RuntimeError, and Juniper.Primrose.BasicInterpreter.source.
Referenced by Juniper.Primrose.BasicInterpreter.CheckConditional(), Juniper.Primrose.BasicInterpreter.DeclareVariable(), Juniper.Primrose.BasicInterpreter.Evaluate(), and Juniper.Primrose.BasicInterpreter.LoadCodeFile().
OnError() [2/2]
void Juniper.Primrose.BasicInterpreter.OnError (string msg) inline private
Definition at line 409 of file BasicInterpreter.cs.
         {
             throw new Exception($"At line {lineNumbers[counter].ToString(CultureInfo.InvariantCulture)}: {msg}");
         }
OnInput()
void Juniper.Primrose.BasicInterpreter.OnInput (Action< string > resume) inline private
Definition at line 193 of file BasicInterpreter.cs.
         {
             if (Input is object)
             {
                 resume(null);
             }
             else
             {
                 Input(this, resume);
             }
         }
References Juniper.Primrose.BasicInterpreter.Input.
Referenced by Juniper.Primrose.BasicInterpreter.PauseBeforeComplete(), and Juniper.Primrose.BasicInterpreter.WaitForInput().
OnLoadFile()
byte [] Juniper.Primrose.BasicInterpreter.OnLoadFile (string fileName) inline private
Definition at line 225 of file BasicInterpreter.cs.
         {
             byte[] data = null;
             LoadFile?.Invoke(this, loader =>
                 data = loader(fileName));
             return data;
         }
References Juniper.Primrose.BasicInterpreter.data, and Juniper.Primrose.BasicInterpreter.LoadFile.
Referenced by Juniper.Primrose.BasicInterpreter.LoadCodeFile().
OnNext()
void Juniper.Primrose.BasicInterpreter.OnNext () inline private
Definition at line 234 of file BasicInterpreter.cs.
         {
             ContinueNext?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Primrose.BasicInterpreter.ContinueNext.
Referenced by Juniper.Primrose.BasicInterpreter.WaitForInput().
OnOutput()
void Juniper.Primrose.BasicInterpreter.OnOutput (string msg) inline private
Definition at line 187 of file BasicInterpreter.cs.
         {
             Output?.Invoke(this, new StringEventArgs(msg));
         }
References Juniper.Primrose.BasicInterpreter.Output.
Referenced by Juniper.Primrose.BasicInterpreter.PauseBeforeComplete(), and Juniper.Primrose.BasicInterpreter.Print().
OnStatement()
bool Juniper.Primrose.BasicInterpreter.OnStatement (Line line) inline private
Definition at line 682 of file BasicInterpreter.cs.
         {
             var idxExpr = new Line();
             var targets = new Line();
             while (line.Count > 0
                 && (line[0].Type != "keywords"
                     || line[0].Value != "GOTO"))
             {
                 var idx = line[0];
                 line.RemoveAt(0);
                 idxExpr.Add(idx);
             }
             if (line.Count > 0)
             {
                 line.RemoveAt(0); // burn the goto;
                 for (var i = 0; i < line.Count; ++i)
                 {
                     var t = line[i];
                     if (t.Type != "operators"
                         || t.Value != ",")
                     {
                         targets.Add(t);
                     }
                 }
                 var idx = int.Parse(Evaluate(idxExpr), CultureInfo.InvariantCulture) - 1;
                 if (0 <= idx && idx < targets.Count)
                 {
                     return SetProgramCounter(new Line { targets[idx] });
                 }
             }
             return true;
         }
References Juniper.Primrose.BasicInterpreter.Evaluate(), and Juniper.Primrose.BasicInterpreter.SetProgramCounter().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
PauseBeforeComplete()
bool Juniper.Primrose.BasicInterpreter.PauseBeforeComplete (Line line) inline private
Definition at line 351 of file BasicInterpreter.cs.
         {
             OnOutput("PROGRAM COMPLETE - PRESS RETURN TO FINISH.");
             OnInput(_ =>
             {
                 isDone = true;
                 OnDone();
             });
             return false;
         }
References Juniper.Primrose.BasicInterpreter.isDone, Juniper.Primrose.BasicInterpreter.OnDone(), Juniper.Primrose.BasicInterpreter.OnInput(), and Juniper.Primrose.BasicInterpreter.OnOutput().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), and Juniper.Primrose.BasicInterpreter.Process().
Print()
bool Juniper.Primrose.BasicInterpreter.Print (Line line) inline private
Definition at line 545 of file BasicInterpreter.cs.
         {
             var endLine = "\n";
             var nest = 0;
             line = line.Select((t, i) =>
             {
                 t = t.Clone();
                 if (t.Type == "operators")
                 {
                     if (t.Value == ",")
                     {
                         if (nest == 0)
{
                             t.Value = "+ \", \" + ";
                         }
                     }
                     else if (t.Value == ";")
                     {
                         t.Value = "+ \" \"";
                         if (i < line.Count - 1)
{
                             t.Value += " + ";
                         }
                         else
{
                             endLine = "";
                         }
                     }
                     else if (t.Value == "(")
                     {
                         ++nest;
                     }
                     else if (t.Value == ")")
                     {
                         --nest;
                     }
                 }
                 return t;
             })
                 .ToList();
             var txt = Evaluate(line) ?? "";
             OnOutput(txt + endLine);
             return true;
         }
References Juniper.Primrose.BasicInterpreter.Evaluate(), and Juniper.Primrose.BasicInterpreter.OnOutput().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), and Juniper.Primrose.BasicInterpreter.WaitForInput().
Process()
bool Juniper.Primrose.BasicInterpreter.Process (Line line) inline private
Definition at line 362 of file BasicInterpreter.cs.
         {
             if (line?.Count > 0)
             {
                 var op = line[0];
                 line.RemoveAt(0);
                 if (op is object)
                 {
                     if (op.Type == "lineNumbers")
                     {
                         return SetProgramCounter(new Line { op });
                     }
                     else if (commands.ContainsKey(op.Value))
                     {
                         return commands[op.Value](line);
                     }
                     else if (state.ContainsKey(op.Value)
                         || (line.Count > 0
                             && line[0].Type == "operators"
                             && line[0].Value == "="))
                     {
                         line.Insert(0, op);
                         return Translate(line);
                     }
                     else
                     {
                         throw new Exception("Unknown command. >>> " + op.Value);
                     }
                 }
             }
             return PauseBeforeComplete(null);
         }
References Juniper.Primrose.BasicInterpreter.commands, Juniper.Primrose.BasicInterpreter.PauseBeforeComplete(), Juniper.Primrose.BasicInterpreter.SetProgramCounter(), Juniper.Primrose.BasicInterpreter.state, and Juniper.Primrose.BasicInterpreter.Translate().
Referenced by Juniper.Primrose.BasicInterpreter.CheckConditional(), Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.Interpret(), and Juniper.Primrose.BasicInterpreter.ReadData().
ReadData()
bool Juniper.Primrose.BasicInterpreter.ReadData (Line line) inline private
Definition at line 840 of file BasicInterpreter.cs.
         {
             if (data.Count == 0)
             {
                 var dataLine = FindNext("DATA");
                 _ = Process(GetLine(dataLine));
             }
             var value = data[dataCounter];
             ++dataCounter;
             line.Add(EQUAL_SIGN);
             line.Add(ToNum(int.Parse(value, CultureInfo.InvariantCulture)));
             return Translate(line);
         }
References Juniper.Primrose.BasicInterpreter.data, Juniper.Primrose.BasicInterpreter.dataCounter, Juniper.Primrose.BasicInterpreter.EQUAL_SIGN, Juniper.Primrose.BasicInterpreter.FindNext(), Juniper.Primrose.BasicInterpreter.GetLine(), Juniper.Primrose.BasicInterpreter.Process(), Juniper.Primrose.BasicInterpreter.ToNum(), and Juniper.Primrose.BasicInterpreter.Translate().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
RestoreData()
bool Juniper.Primrose.BasicInterpreter.RestoreData (Line line) inline private
Definition at line 855 of file BasicInterpreter.cs.
         {
             dataCounter = 0;
             return true;
         }
References Juniper.Primrose.BasicInterpreter.dataCounter.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
SetProgramCounter()
bool Juniper.Primrose.BasicInterpreter.SetProgramCounter (Line line) inline private
Definition at line 396 of file BasicInterpreter.cs.
         {
             var lineNumber = int.Parse(Evaluate(line), CultureInfo.InvariantCulture);
             counter = -1;
             while (counter < lineNumbers.Count - 1
                 && lineNumbers[counter + 1] < lineNumber)
             {
                 ++counter;
             }
             return true;
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.Evaluate(), and Juniper.Primrose.BasicInterpreter.lineNumbers.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), Juniper.Primrose.BasicInterpreter.ConditionalReturn(), Juniper.Primrose.BasicInterpreter.GoToSubroutine(), Juniper.Primrose.BasicInterpreter.OnStatement(), and Juniper.Primrose.BasicInterpreter.Process().
SetRepeat()
bool Juniper.Primrose.BasicInterpreter.SetRepeat (Line line) inline private
Definition at line 450 of file BasicInterpreter.cs.
         {
             returnStack.Push(ToNum(lineNumbers[counter]));
             return true;
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.lineNumbers, Juniper.Primrose.BasicInterpreter.returnStack, and Juniper.Primrose.BasicInterpreter.ToNum().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
StackReturn()
bool Juniper.Primrose.BasicInterpreter.StackReturn (Line line) inline private
Definition at line 824 of file BasicInterpreter.cs.
         {
             return ConditionalReturn(true);
         }
References Juniper.Primrose.BasicInterpreter.ConditionalReturn().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
ToNum()
static Token Juniper.Primrose.BasicInterpreter.ToNum (int i) inline static private
Definition at line 27 of file BasicInterpreter.cs.
         {
             return new Token(i.ToString(CultureInfo.InvariantCulture), "numbers");
         }
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.GoToSubroutine(), Juniper.Primrose.BasicInterpreter.LabelLine(), Juniper.Primrose.BasicInterpreter.ReadData(), Juniper.Primrose.BasicInterpreter.SetRepeat(), Juniper.Primrose.BasicInterpreter.WaitForInput(), and Juniper.Primrose.BasicInterpreter.WhileLoop().
ToStr()
static Token Juniper.Primrose.BasicInterpreter.ToStr (string str) inline static private
Definition at line 32 of file BasicInterpreter.cs.
         {
             return new Token("\"" + str
                 .Replace("\n", "\\n")
                 .Replace("\"", "\\\"") + "\"", "strings");
         }
Referenced by Juniper.Primrose.BasicInterpreter.WaitForInput().
Translate()
bool Juniper.Primrose.BasicInterpreter.Translate (Line line) inline private
Definition at line 330 of file BasicInterpreter.cs.
         {
             _ = Evaluate(line);
             return true;
         }
References Juniper.Primrose.BasicInterpreter.Evaluate().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), Juniper.Primrose.BasicInterpreter.LabelLine(), Juniper.Primrose.BasicInterpreter.Process(), and Juniper.Primrose.BasicInterpreter.ReadData().
UntilLoop()
bool Juniper.Primrose.BasicInterpreter.UntilLoop (Line line) inline private
Definition at line 732 of file BasicInterpreter.cs.
         {
             var cond = Evaluate(line) == "True";
             return ConditionalReturn(cond);
         }
References Juniper.Primrose.BasicInterpreter.ConditionalReturn(), and Juniper.Primrose.BasicInterpreter.Evaluate().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
WaitForInput()
bool Juniper.Primrose.BasicInterpreter.WaitForInput (Line line) inline private
Definition at line 652 of file BasicInterpreter.cs.
         {
             var toVar = line[line.Count - 1];
             line.RemoveAt(line.Count - 1);
             if (line.Count > 0)
             {
                 _ = Print(line);
             }
             OnInput(str =>
             {
                 str = str.ToUpperInvariant();
                 Token valueToken = null;
                 if (int.TryParse(str, out var num))
                 {
                     valueToken = ToNum(num);
                 }
                 else
                 {
                     valueToken = ToStr(str);
                 }
                 _ = Evaluate(new Line { toVar, EQUAL_SIGN, valueToken });
                 OnNext();
             });
             return false;
         }
References Juniper.Primrose.BasicInterpreter.EQUAL_SIGN, Juniper.Primrose.BasicInterpreter.Evaluate(), Juniper.Primrose.BasicInterpreter.OnInput(), Juniper.Primrose.BasicInterpreter.OnNext(), Juniper.Primrose.BasicInterpreter.Print(), Juniper.Primrose.BasicInterpreter.ToNum(), and Juniper.Primrose.BasicInterpreter.ToStr().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
WhileLoop()
bool Juniper.Primrose.BasicInterpreter.WhileLoop (Line line) inline private
Definition at line 752 of file BasicInterpreter.cs.
         {
             var cond = Evaluate(line) == "True";
             if (!cond)
             {
                 counter = FindNext("WEND");
             }
             else
             {
                 returnStack.Push(ToNum(lineNumbers[counter]));
             }
             return true;
         }
References Juniper.Primrose.BasicInterpreter.counter, Juniper.Primrose.BasicInterpreter.Evaluate(), Juniper.Primrose.BasicInterpreter.FindNext(), Juniper.Primrose.BasicInterpreter.lineNumbers, Juniper.Primrose.BasicInterpreter.returnStack, and Juniper.Primrose.BasicInterpreter.ToNum().
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
Member Data Documentation
commands
readonly Dictionary<string, Func<Line, bool> > Juniper.Primrose.BasicInterpreter.commands private
Definition at line 39 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), and Juniper.Primrose.BasicInterpreter.Process().
counter
int Juniper.Primrose.BasicInterpreter.counter = 0 private
Definition at line 52 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), Juniper.Primrose.BasicInterpreter.FindNext(), Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.GoToSubroutine(), Juniper.Primrose.BasicInterpreter.Interpret(), Juniper.Primrose.BasicInterpreter.LabelLine(), Juniper.Primrose.BasicInterpreter.SetProgramCounter(), Juniper.Primrose.BasicInterpreter.SetRepeat(), and Juniper.Primrose.BasicInterpreter.WhileLoop().
data
readonly List<string> Juniper.Primrose.BasicInterpreter.data = new List<string>() private
Definition at line 50 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.LoadCodeFile(), Juniper.Primrose.BasicInterpreter.LoadData(), Juniper.Primrose.BasicInterpreter.OnLoadFile(), and Juniper.Primrose.BasicInterpreter.ReadData().
dataCounter
int Juniper.Primrose.BasicInterpreter.dataCounter = 0 private
Definition at line 54 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.ReadData(), and Juniper.Primrose.BasicInterpreter.RestoreData().
EPOCH
readonly DateTime Juniper.Primrose.BasicInterpreter.EPOCH = new DateTime(1970, 1, 1, 0, 0, 0) static private
Definition at line 16 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
EQUAL_SIGN
readonly Token Juniper.Primrose.BasicInterpreter.EQUAL_SIGN = new Token("=", "operators") static private
Definition at line 15 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.LabelLine(), Juniper.Primrose.BasicInterpreter.ReadData(), and Juniper.Primrose.BasicInterpreter.WaitForInput().
FOR_LOOP_DELIMS
readonly string [] Juniper.Primrose.BasicInterpreter.FOR_LOOP_DELIMS = new[] { "=", "TO", "STEP" } static private
Definition at line 14 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.ForLoop().
forLoopCounters
readonly Dictionary<int, int> Juniper.Primrose.BasicInterpreter.forLoopCounters = new Dictionary<int, int>() private
Definition at line 49 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.ForLoop().
isDone
bool Juniper.Primrose.BasicInterpreter.isDone = false private
Definition at line 53 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.Interpret(), and Juniper.Primrose.BasicInterpreter.PauseBeforeComplete().
lineNumbers
readonly List<int> Juniper.Primrose.BasicInterpreter.lineNumbers = new List<int>() private
Definition at line 45 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), Juniper.Primrose.BasicInterpreter.FindNext(), Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.GetLine(), Juniper.Primrose.BasicInterpreter.GoToSubroutine(), Juniper.Primrose.BasicInterpreter.LabelLine(), Juniper.Primrose.BasicInterpreter.SetProgramCounter(), Juniper.Primrose.BasicInterpreter.SetRepeat(), and Juniper.Primrose.BasicInterpreter.WhileLoop().
lines
readonly List<Line> Juniper.Primrose.BasicInterpreter.lines = new List<Line>() private
Definition at line 46 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
program
readonly Dictionary<int, Line> Juniper.Primrose.BasicInterpreter.program = new Dictionary<int, Line>() private
Definition at line 44 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), and Juniper.Primrose.BasicInterpreter.GetLine().
random
readonly Random Juniper.Primrose.BasicInterpreter.random = new Random() private
Definition at line 47 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
returnStack
readonly Stack<Token> Juniper.Primrose.BasicInterpreter.returnStack = new Stack<Token>() private
Definition at line 48 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.ConditionalReturn(), Juniper.Primrose.BasicInterpreter.ForLoop(), Juniper.Primrose.BasicInterpreter.GoToSubroutine(), Juniper.Primrose.BasicInterpreter.SetRepeat(), and Juniper.Primrose.BasicInterpreter.WhileLoop().
source
readonly string Juniper.Primrose.BasicInterpreter.source private
Definition at line 42 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), and Juniper.Primrose.BasicInterpreter.OnError().
state
readonly Dictionary<string, object> Juniper.Primrose.BasicInterpreter.state private
Definition at line 40 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter(), Juniper.Primrose.BasicInterpreter.DeclareVariable(), Juniper.Primrose.BasicInterpreter.DefineFunction(), Juniper.Primrose.BasicInterpreter.IsFunction(), and Juniper.Primrose.BasicInterpreter.Process().
tokenMap
readonly Dictionary<string, string> Juniper.Primrose.BasicInterpreter.tokenMap static private
Initial value:
= new Dictionary<string, string>
            {
                { "OR", "||" },
                { "AND", "&&" },
                { "NOT", "!" },
                { "MOD", "%" },
                { "<>", "!=" }
            }
Definition at line 18 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.BasicInterpreter().
Event Documentation
ClearScreen
EventHandler Juniper.Primrose.BasicInterpreter.ClearScreen
Definition at line 182 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.OnClearScreen().
ContinueNext
EventHandler Juniper.Primrose.BasicInterpreter.ContinueNext
Definition at line 183 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.OnNext().
Done
EventHandler Juniper.Primrose.BasicInterpreter.Done
Definition at line 184 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.OnDone().
Input
EventHandler<Action<string> > Juniper.Primrose.BasicInterpreter.Input
Definition at line 178 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.OnInput().
LoadFile
EventHandler<Action<Func<string, byte[]> > > Juniper.Primrose.BasicInterpreter.LoadFile
Definition at line 177 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.OnLoadFile().
Output
EventHandler<StringEventArgs> Juniper.Primrose.BasicInterpreter.Output
Definition at line 180 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.OnOutput().
RuntimeError
EventHandler<ErrorEventArgs> Juniper.Primrose.BasicInterpreter.RuntimeError
Definition at line 181 of file BasicInterpreter.cs.
Referenced by Juniper.Primrose.BasicInterpreter.OnError().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Primrose/Grammars/BasicInterpreter.cs