Juniper: ScreenDebugger Class Reference
ScreenDebugger Class Reference
The ScreenDebugger component is a global logging system that has the option of piping its output to a TextMesh visible on the screen. This can be handy for printing out logging information on mobile devices without having to explicitly attach a mobile device debugger.
Public Member Functions
ScreenDebugger ()
When the ScreenDebugger is instantiated, that instance is saved statically to be accessible to all code.
void AddLine (string msg)
Add lines to the debug output in a way that Unity Events can handle
void Awake ()
Finds the text component to which the output will be rendered.
void LateUpdate ()
Renders all text in lines to the text output.
Static Public Member Functions
static void Print (Exception exp, string label)
Print an exception formatted succinctly for printing to the console. The label field helps locate the origin of the exception.
static void Print (Vector3 vector, string label)
Print a Vector with components to 3 significant figures.
static void Print (string format, params object[] args)
Print a formatted string
static void Print (string msg)
Print a simple message
Private Attributes
TextElementType text
The text element to which the output is rendered.
Static Private Attributes
static List< string > lines
The text that will be rendered out to the TextMesh at the end of the frame.
static ScreenDebugger instance
The screen debugger instance, a singleton.
Detailed Description
The ScreenDebugger component is a global logging system that has the option of piping its output to a TextMesh visible on the screen. This can be handy for printing out logging information on mobile devices without having to explicitly attach a mobile device debugger.
Definition at line 19 of file ScreenDebugger.cs.
Constructor & Destructor Documentation
ScreenDebugger()
ScreenDebugger.ScreenDebugger ()
When the ScreenDebugger is instantiated, that instance is saved statically to be accessible to all code.
Member Function Documentation
AddLine()
void ScreenDebugger.AddLine (string msg) inline
Add lines to the debug output in a way that Unity Events can handle
Parameters
msg Message.
Definition at line 73 of file ScreenDebugger.cs.
     {
         lines.Add(msg);
         Debug.Log(msg);
     }
References lines.
Awake()
void ScreenDebugger.Awake ()
Finds the text component to which the output will be rendered.
LateUpdate()
void ScreenDebugger.LateUpdate () inline
Renders all text in lines to the text output.
Definition at line 88 of file ScreenDebugger.cs.
     {
         if (lines == null)
         {
             lines = new List<string>();
         }
         else if (lines.Count > 0)
         {
             var arr = (from msg in lines
                        select string.Format("{0}: {1}", Time.frameCount, msg))
                 .ToArray();
             var output = string.Join(Environment.NewLine, arr);
             if (text != null)
             {
                 text.text = output;
             }
             lines.Clear();
         }
     }
References lines, and text.
Print() [1/4]
static void ScreenDebugger.Print (Exception exp, string label) static
Print an exception formatted succinctly for printing to the console. The label field helps locate the origin of the exception.
Parameters
exp Exp.
label Label.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Loop(), Juniper.XR.TrackableFoundEventHandler.OnTrackableStateChanged(), Juniper.World.SunPosition.PrintDebugReport(), Juniper.World.OutdoorLightEstimate.PrintDebugReport(), Juniper.XR.TrackableFoundEventHandler.PrintDebugReport(), Juniper.World.CompassRose.PrintDebugReport(), Juniper.World.Climate.Weather.PrintDebugReport(), Juniper.World.IndoorLightEstimate.PrintDebugReport(), Juniper.Widgets.Shaker.PrintDebugReport(), Juniper.World.GPSLocation.PrintDebugReport(), Juniper.World.LightMeasurement.PrintDebugReport(), Juniper.XR.TrackerKeeper.PrintDebugReport(), Juniper.XR.TrackerKeeper.Start(), Juniper.XR.TrackerKeeper.StartTrackerWithDataSet(), Juniper.Widgets.QualityDegrader.Update(), and Juniper.XR.TrackerKeeper.WithTarget().
Print() [2/4]
static void ScreenDebugger.Print (Vector3 vector, string label) static
Print a Vector with components to 3 significant figures.
Parameters
vector Vector.
label Label.
Print() [3/4]
static void ScreenDebugger.Print (string format, params object [] args) static
Print a formatted string
Parameters
format Format.
args Arguments.
Print() [4/4]
static void ScreenDebugger.Print (string msg) inline static
Print a simple message
Parameters
msg Message.
Definition at line 57 of file ScreenDebugger.cs.
     {
         if (instance != null && lines != null)
         {
             lines.Add(msg);
         }
         else
         {
             Debug.Log(msg);
         }
     }
References instance, and lines.
Member Data Documentation
instance
ScreenDebugger ScreenDebugger.instance static private
The screen debugger instance, a singleton.
Definition at line 116 of file ScreenDebugger.cs.
Referenced by Print().
lines
List<string> ScreenDebugger.lines static private
The text that will be rendered out to the TextMesh at the end of the frame.
Definition at line 111 of file ScreenDebugger.cs.
Referenced by AddLine(), LateUpdate(), and Print().
text
TextElementType ScreenDebugger.text private
The text element to which the output is rendered.
Definition at line 121 of file ScreenDebugger.cs.
Referenced by LateUpdate().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/ScreenDebugger.cs