Juniper: Juniper.Unity.Animation.ChildSwapAnimator Class Reference
Juniper.Unity.Animation.ChildSwapAnimator Class Reference
An animator for UIs that swap out child components as visible/invisible. Only one such component is allowed on a gameObject at a time.
Public Member Functions
void Awake ()
override bool HasState (string name)
Returns true if a transform named name is a child of this transform.
override IEnumerator PlayCoroutine (string name)
Sets the child transform named in name to Active, while all other child transforms named in stateNames are set to Inactive.
void Play (string name)
Play an animation immediately, with no chance to wait for its completion.
Static Public Member Functions
static AbstractAnimator GetAnimator (GameObject parent, string[] parts)
Creates the right Animator subclass for a given gameObject. If the gameObject has a Unity Animator on it, GetAnimator will create a UnityAnimator. If the gameObject has child transforms that match the Interaction system's state names, then GetAnimator will create a ChildSwapAnimator.
Public Attributes
string [] stateNames
The names of the child transforms to swap around.
Private Attributes
Dictionary< string, Vector3 > scales
Detailed Description
An animator for UIs that swap out child components as visible/invisible. Only one such component is allowed on a gameObject at a time.
Definition at line 14 of file ChildSwapAnimator.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Animation.ChildSwapAnimator.Awake () inline
Definition at line 23 of file ChildSwapAnimator.cs.
         {
             scales = stateNames.ToDictionary(
                 s => s,
                 s => this.Query(s)?.localScale ?? Vector3.one);
         }
References Juniper.Unity.Animation.ChildSwapAnimator.scales, and Juniper.Unity.Animation.ChildSwapAnimator.stateNames.
GetAnimator()
static AbstractAnimator Juniper.Unity.Animation.AbstractAnimator.GetAnimator (GameObject parent, string [] parts) inline static inherited
Creates the right Animator subclass for a given gameObject. If the gameObject has a Unity Animator on it, GetAnimator will create a UnityAnimator. If the gameObject has child transforms that match the Interaction system's state names, then GetAnimator will create a ChildSwapAnimator.
Parameters
parent
parts
Returns
Definition at line 23 of file AbstractAnimator.cs.
         {
             var animator = parent.GetComponent<AbstractAnimator>();
             var defaultState = parts[0];
             if (animator == null)
             {
 #if UNITY_MODULES_ANIMATION
                 var anim = parent.GetComponent<Animator>();
                 if (anim != null && UnityAnimator.AnimatorHasState(anim, defaultState))
                 {
                     animator = parent.EnsureComponent<UnityAnimator>().Value;
                 }
                 else
 #endif
                 if (parent.transform.childCount > 0 && parent.transform.Find(defaultState))
                 {
                     var swapper = parent.EnsureComponent<ChildSwapAnimator>().Value;
                     swapper.stateNames = parts;
                     animator = swapper;
                 }
             }
             return animator;
         }
References Juniper.Unity.Animation.ChildSwapAnimator.stateNames.
Referenced by Juniper.Unity.Widgets.AbstractTouchable.Awake().
HasState()
override bool Juniper.Unity.Animation.ChildSwapAnimator.HasState (string name) inline virtual
Returns true if a transform named name is a child of this transform.
Parameters
name
Returns
Implements Juniper.Unity.Animation.AbstractAnimator.
Definition at line 35 of file ChildSwapAnimator.cs.
         {
             return transform.Find(name) != null;
         }
Play()
void Juniper.Unity.Animation.AbstractAnimator.Play (string name) inline inherited
Play an animation immediately, with no chance to wait for its completion.
Parameters
name
Definition at line 60 of file AbstractAnimator.cs.
         {
             StartCoroutine(PlayCoroutine(name));
         }
References Juniper.Unity.Animation.AbstractAnimator.PlayCoroutine().
Referenced by Juniper.Unity.Widgets.AbstractTouchable.ShowState().
PlayCoroutine()
override IEnumerator Juniper.Unity.Animation.ChildSwapAnimator.PlayCoroutine (string name) inline virtual
Sets the child transform named in name to Active, while all other child transforms named in stateNames are set to Inactive.
Parameters
name
Returns
An enumerator suitable for using in a Unity coroutine.
Implements Juniper.Unity.Animation.AbstractAnimator.
Definition at line 46 of file ChildSwapAnimator.cs.
         {
             foreach (var key in stateNames)
             {
                 var obj = this.Query(key);
                 if (obj != null)
                 {
                     obj.SetActive(key == name);
                     if (Application.isPlaying)
                     {
                         obj.localScale = scales.Get(key, Vector3.one);
                     }
                 }
             }
             yield return null;
         }
References Juniper.Unity.Animation.ChildSwapAnimator.scales, and Juniper.Unity.Animation.ChildSwapAnimator.stateNames.
Member Data Documentation
scales
Dictionary<string, Vector3> Juniper.Unity.Animation.ChildSwapAnimator.scales private
Definition at line 21 of file ChildSwapAnimator.cs.
Referenced by Juniper.Unity.Animation.ChildSwapAnimator.Awake(), and Juniper.Unity.Animation.ChildSwapAnimator.PlayCoroutine().
stateNames
string [] Juniper.Unity.Animation.ChildSwapAnimator.stateNames
The names of the child transforms to swap around.
Definition at line 19 of file ChildSwapAnimator.cs.
Referenced by Juniper.Unity.Animation.ChildSwapAnimator.Awake(), Juniper.Unity.Animation.AbstractAnimator.GetAnimator(), and Juniper.Unity.Animation.ChildSwapAnimator.PlayCoroutine().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Animation/ChildSwapAnimator.cs