Juniper: Juniper.Sound.Beats.VMU Class Reference
Juniper.Sound.Beats.VMU Class Reference
Public Member Functions
void Start ()
void BlinkMeasure ()
void BlinkBeat ()
void SetVMU (float[] spectrum)
Public Attributes
Transform Prefab
Vector3 BarScale = new Vector3(0.1f, 4f, 0.1f)
BeatDetector detector
Private Member Functions
void Update ()
Private Attributes
Slider progress
readonly List< Transform > bars = new List<Transform>()
bool hasLayout
Detailed Description
Definition at line 8 of file VMU.cs.
Member Function Documentation
BlinkBeat()
void Juniper.Sound.Beats.VMU.BlinkBeat () inline
Definition at line 32 of file VMU.cs.
         {
         }
BlinkMeasure()
void Juniper.Sound.Beats.VMU.BlinkMeasure () inline
Definition at line 28 of file VMU.cs.
         {
         }
SetVMU()
void Juniper.Sound.Beats.VMU.SetVMU (float [] spectrum) inline
Definition at line 36 of file VMU.cs.
         {
             while (bars.Count < spectrum.Length)
             {
                 var bar = Instantiate(Prefab);
                 bar.SetParent(transform);
                 bar.localPosition = Vector3.zero;
                 bar.localRotation = new Quaternion(0, 0, 0, 1);
                 bar.localScale = new Vector3(1, 1, 1);
                 bars.Add(bar);
             }
             while (bars.Count > spectrum.Length)
             {
                 var last = bars.Count - 1;
                 var bar = bars[last];
                 bars.RemoveAt(last);
                 Destroy(bar.gameObject);
             }
             var offset = 0.5f * (bars.Count - 1);
             for (var i = 0; i < bars.Count; ++i)
             {
                 var bar = bars[i];
                 var scale = BarScale;
                 scale.y *= spectrum[i];
                 bar.localScale = scale;
                 if (!hasLayout)
                 {
                     bar.transform.localPosition = new Vector3(BarScale.x * (i - offset), 0, 0);
                 }
             }
         }
References Juniper.Sound.Beats.VMU.bars, Juniper.Sound.Beats.VMU.BarScale, Juniper.Sound.Beats.VMU.hasLayout, and Juniper.Sound.Beats.VMU.Prefab.
Start()
void Juniper.Sound.Beats.VMU.Start () inline
Definition at line 17 of file VMU.cs.
         {
             transform.ClearChildren();
             hasLayout = GetComponent<HorizontalLayoutGroup>() != null || GetComponent<VerticalLayoutGroup>() != null;
             progress = this.Query<Slider>("../Progress");
             if (hasLayout)
             {
                 BarScale = new Vector3(1, 10, 1);
             }
         }
References Juniper.Sound.Beats.VMU.BarScale, Juniper.Sound.Beats.VMU.hasLayout, and Juniper.Sound.Beats.VMU.progress.
Update()
void Juniper.Sound.Beats.VMU.Update () inline private
Definition at line 70 of file VMU.cs.
         {
             progress.value = detector.Progress;
         }
References Juniper.Sound.Beats.VMU.detector, Juniper.Sound.Beats.VMU.progress, and Juniper.Sound.Beats.BeatDetector.Progress.
Member Data Documentation
bars
readonly List<Transform> Juniper.Sound.Beats.VMU.bars = new List<Transform>() private
Definition at line 14 of file VMU.cs.
Referenced by Juniper.Sound.Beats.VMU.SetVMU().
BarScale
Vector3 Juniper.Sound.Beats.VMU.BarScale = new Vector3(0.1f, 4f, 0.1f)
Definition at line 11 of file VMU.cs.
Referenced by Juniper.Sound.Beats.VMU.SetVMU(), and Juniper.Sound.Beats.VMU.Start().
detector
BeatDetector Juniper.Sound.Beats.VMU.detector
Definition at line 13 of file VMU.cs.
Referenced by Juniper.Sound.Beats.VMU.Update().
hasLayout
bool Juniper.Sound.Beats.VMU.hasLayout private
Definition at line 15 of file VMU.cs.
Referenced by Juniper.Sound.Beats.VMU.SetVMU(), and Juniper.Sound.Beats.VMU.Start().
Prefab
Transform Juniper.Sound.Beats.VMU.Prefab
Definition at line 10 of file VMU.cs.
Referenced by Juniper.Sound.Beats.VMU.SetVMU().
progress
Slider Juniper.Sound.Beats.VMU.progress private
Definition at line 12 of file VMU.cs.
Referenced by Juniper.Sound.Beats.VMU.Start(), and Juniper.Sound.Beats.VMU.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Sound/Beats/VMU.cs