Juniper: BitMiracle.LibJpeg.Jpeg Class Reference
BitMiracle.LibJpeg.Jpeg Class Reference
Internal wrapper for classic jpeg compressor and decompressor
Public Member Functions
void Compress (IRawImage source, Stream output)
Compresses any image described as ICompressSource to JPEG
void Decompress (Stream jpeg, IDecompressDestination destination)
Decompresses JPEG image to any image described as ICompressDestination
delegate bool MarkerParser (Jpeg decompressor)
Delegate for application-supplied marker processing methods. Need not pass marker code since it is stored in cinfo.unread_marker.
void SetMarkerProcessor (int markerCode, MarkerParser routine)
Properties
CompressionParameters?? CompressionParameters [get, set]
Advanced users may set specific parameters of compression
DecompressionParameters?? DecompressionParameters [get, set]
Advanced users may set specific parameters of decompression
JpegCompressStruct ClassicCompressor = new JpegCompressStruct(new JpegErrorMessage()) [get]
JpegDecompressStruct ClassicDecompressor = new JpegDecompressStruct(new JpegErrorMessage()) [get]
Private Member Functions
void beforeDecompress (Stream jpeg)
Tunes decompressor
LoadedImageAttributes getImageParametersFromDecompressor ()
void applyParameters (DecompressionParameters parameters)
void applyParameters (CompressionParameters parameters)
Private Attributes
CompressionParameters m_compressionParameters = new CompressionParameters()
DecompressionParameters m_decompressionParameters = new DecompressionParameters()
Detailed Description
Internal wrapper for classic jpeg compressor and decompressor
Definition at line 12 of file Jpeg.cs.
Member Function Documentation
applyParameters() [1/2]
void BitMiracle.LibJpeg.Jpeg.applyParameters (DecompressionParameters parameters) inline private
Definition at line 179 of file Jpeg.cs.
         {
             Debug.Assert(parameters is object);
             if (parameters.OutColorspace != Colorspace.Unknown)
             {
                 ClassicDecompressor.Out_color_space = (JColorSpace)parameters.OutColorspace;
             }
             ClassicDecompressor.Scale_num = parameters.ScaleNumerator;
             ClassicDecompressor.Scale_denom = parameters.ScaleDenominator;
             ClassicDecompressor.Buffered_image = parameters.BufferedImage;
             ClassicDecompressor.Raw_data_out = parameters.RawDataOut;
             ClassicDecompressor.Dct_method = (JDctMethod)parameters.DCTMethod;
             ClassicDecompressor.Dither_mode = (JDitherMode)parameters.DitherMode;
             ClassicDecompressor.Do_fancy_upsampling = parameters.DoFancyUpsampling;
             ClassicDecompressor.Do_block_smoothing = parameters.DoBlockSmoothing;
             ClassicDecompressor.Quantize_colors = parameters.QuantizeColors;
             ClassicDecompressor.Two_pass_quantize = parameters.TwoPassQuantize;
             ClassicDecompressor.Desired_number_of_colors = parameters.DesiredNumberOfColors;
             ClassicDecompressor.Enable_1pass_quant = parameters.EnableOnePassQuantizer;
             ClassicDecompressor.Enable_external_quant = parameters.EnableExternalQuant;
             ClassicDecompressor.Enable_2pass_quant = parameters.EnableTwoPassQuantizer;
             ClassicDecompressor.Err.TraceLevel = parameters.TraceLevel;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Buffered_image, BitMiracle.LibJpeg.DecompressionParameters.BufferedImage, BitMiracle.LibJpeg.Jpeg.ClassicDecompressor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Dct_method, BitMiracle.LibJpeg.DecompressionParameters.DCTMethod, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Desired_number_of_colors, BitMiracle.LibJpeg.DecompressionParameters.DesiredNumberOfColors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Dither_mode, BitMiracle.LibJpeg.DecompressionParameters.DitherMode, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Do_block_smoothing, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Do_fancy_upsampling, BitMiracle.LibJpeg.DecompressionParameters.DoBlockSmoothing, BitMiracle.LibJpeg.DecompressionParameters.DoFancyUpsampling, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Enable_1pass_quant, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Enable_2pass_quant, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Enable_external_quant, BitMiracle.LibJpeg.DecompressionParameters.EnableExternalQuant, BitMiracle.LibJpeg.DecompressionParameters.EnableOnePassQuantizer, BitMiracle.LibJpeg.DecompressionParameters.EnableTwoPassQuantizer, BitMiracle.LibJpeg.Classic.JpegCommonStruct.Err, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Out_color_space, BitMiracle.LibJpeg.DecompressionParameters.OutColorspace, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Quantize_colors, BitMiracle.LibJpeg.DecompressionParameters.QuantizeColors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Raw_data_out, BitMiracle.LibJpeg.DecompressionParameters.RawDataOut, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Scale_denom, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Scale_num, BitMiracle.LibJpeg.DecompressionParameters.ScaleDenominator, BitMiracle.LibJpeg.DecompressionParameters.ScaleNumerator, BitMiracle.LibJpeg.DecompressionParameters.TraceLevel, BitMiracle.LibJpeg.Classic.JpegErrorMessage.TraceLevel, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Two_pass_quantize, and BitMiracle.LibJpeg.DecompressionParameters.TwoPassQuantize.
Referenced by BitMiracle.LibJpeg.Jpeg.beforeDecompress(), and BitMiracle.LibJpeg.Jpeg.Compress().
applyParameters() [2/2]
void BitMiracle.LibJpeg.Jpeg.applyParameters (CompressionParameters parameters) inline private
Definition at line 205 of file Jpeg.cs.
         {
             Debug.Assert(parameters is object);
             ClassicCompressor.SmoothingFactor = parameters.SmoothingFactor;
             ClassicCompressor.JpegSetQuality(parameters.Quality, true);
             if (parameters.SimpleProgressive)
             {
                 ClassicCompressor.JpegSimpleProgression();
             }
         }
References BitMiracle.LibJpeg.Jpeg.ClassicCompressor, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetQuality(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.CompressionParameters.Quality, BitMiracle.LibJpeg.CompressionParameters.SimpleProgressive, BitMiracle.LibJpeg.CompressionParameters.SmoothingFactor, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.SmoothingFactor.
beforeDecompress()
void BitMiracle.LibJpeg.Jpeg.beforeDecompress (Stream jpeg) inline private
Tunes decompressor
Parameters
jpeg Stream with input compressed JPEG data
Definition at line 133 of file Jpeg.cs.
         {
             ClassicDecompressor.JpegStdioSrc(jpeg);
             /* Read file header, set default decompression parameters */
             ClassicDecompressor.JpegReadHeader(true);
             applyParameters(m_decompressionParameters);
             ClassicDecompressor.JpegCalcOutputDimensions();
         }
References BitMiracle.LibJpeg.Jpeg.applyParameters(), BitMiracle.LibJpeg.Jpeg.ClassicDecompressor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStdioSrc(), and BitMiracle.LibJpeg.Jpeg.m_decompressionParameters.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
Compress()
void BitMiracle.LibJpeg.Jpeg.Compress (IRawImage source, Stream output) inline
Compresses any image described as ICompressSource to JPEG
Parameters
source Contains description of input image
output Stream for output of compressed JPEG
Definition at line 40 of file Jpeg.cs.
         {
             if (source is null)
             {
                 throw new ArgumentNullException(nameof(source));
             }
             if (output is null)
             {
                 throw new ArgumentNullException(nameof(output));
             }
             ClassicCompressor.Image_width = source.Width;
             ClassicCompressor.Image_height = source.Height;
             ClassicCompressor.In_color_space = (JColorSpace)source.Colorspace;
             ClassicCompressor.Input_components = source.ComponentsPerPixel;
             //m_compressor.Data_precision = source.DataPrecision;
             ClassicCompressor.JpegSetDefaults();
             //we need to set density parameters after setting of default jpeg parameters
             //m_compressor.Density_unit = source.DensityUnit;
             //m_compressor.X_density = (short)source.DensityX;
             //m_compressor.Y_density = (short)source.DensityY;
             applyParameters(m_compressionParameters);
             // Specify data destination for compression
             ClassicCompressor.JpegStdioDest(output);
             // Start compression
             ClassicCompressor.JpegStartCompression(true);
             // Process  pixels
             source.BeginRead();
             while (ClassicCompressor.Next_scanline < ClassicCompressor.Image_height)
             {
                 var row = source.GetPixelRow();
                 var rowForDecompressor = new byte[1][];
                 rowForDecompressor[0] = row ?? throw new InvalidDataException("Row of pixels is null");
                 ClassicCompressor.JpegWriteScanlines(rowForDecompressor, 1);
             }
             source.EndRead();
             // Finish compression and release memory
             ClassicCompressor.JpegFinishCompress();
         }
References BitMiracle.LibJpeg.Jpeg.applyParameters(), BitMiracle.LibJpeg.IRawImage.BeginRead(), BitMiracle.LibJpeg.Jpeg.ClassicCompressor, BitMiracle.LibJpeg.IRawImage.Colorspace, BitMiracle.LibJpeg.IRawImage.ComponentsPerPixel, BitMiracle.LibJpeg.IRawImage.EndRead(), BitMiracle.LibJpeg.IRawImage.GetPixelRow(), BitMiracle.LibJpeg.IRawImage.Height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Image_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Image_width, BitMiracle.LibJpeg.Classic.JpegCompressStruct.In_color_space, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Input_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStdioDest(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Jpeg.m_compressionParameters, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Next_scanline, and BitMiracle.LibJpeg.IRawImage.Width.
Decompress()
void BitMiracle.LibJpeg.Jpeg.Decompress (Stream jpeg, IDecompressDestination destination) inline
Decompresses JPEG image to any image described as ICompressDestination
Parameters
jpeg Stream with JPEG data
destination Stream for output of compressed JPEG
Definition at line 94 of file Jpeg.cs.
         {
             if (jpeg is null)
             {
                 throw new ArgumentNullException(nameof(jpeg));
             }
             if (destination is null)
             {
                 throw new ArgumentNullException(nameof(destination));
             }
             beforeDecompress(jpeg);
             // Start decompression
             ClassicDecompressor.JpegStartDecompress();
             var parameters = getImageParametersFromDecompressor();
             destination.SetImageAttributes(parameters);
             destination.BeginWrite();
             /* Process data */
             while (ClassicDecompressor.Output_scanline < ClassicDecompressor.Output_height)
             {
                 var row = JpegCommonStruct.AllocJpegSamples(ClassicDecompressor.Output_width * ClassicDecompressor.Output_components, 1);
                 ClassicDecompressor.JpegReadScanlines(row, 1);
                 destination.ProcessPixelsRow(row[0]);
             }
             destination.EndWrite();
             // Finish decompression and release memory.
             ClassicDecompressor.JpegFinishDecompress();
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples(), BitMiracle.LibJpeg.Jpeg.beforeDecompress(), BitMiracle.LibJpeg.IDecompressDestination.BeginWrite(), BitMiracle.LibJpeg.Jpeg.ClassicDecompressor, BitMiracle.LibJpeg.IDecompressDestination.EndWrite(), BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_components, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_height, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_scanline, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_width, BitMiracle.LibJpeg.IDecompressDestination.ProcessPixelsRow(), and BitMiracle.LibJpeg.IDecompressDestination.SetImageAttributes().
getImageParametersFromDecompressor()
LoadedImageAttributes BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor () inline private
Definition at line 143 of file Jpeg.cs.
         {
             return new LoadedImageAttributes
             {
                 Colorspace = (Colorspace)ClassicDecompressor.Out_color_space,
                 QuantizeColors = ClassicDecompressor.Quantize_colors,
                 Width = ClassicDecompressor.Output_width,
                 Height = ClassicDecompressor.Output_height,
                 ComponentsPerSample = ClassicDecompressor.Out_color_components,
                 Components = ClassicDecompressor.Output_components,
                 ActualNumberOfColors = ClassicDecompressor.ActualNumberOfColors,
                 Colormap = ClassicDecompressor.Colormap,
                 DensityUnit = ClassicDecompressor.DensityUnit,
                 DensityX = ClassicDecompressor.XDensity,
                 DensityY = ClassicDecompressor.YDensity
             };
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.ActualNumberOfColors, BitMiracle.LibJpeg.Jpeg.ClassicDecompressor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Colormap, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DensityUnit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Out_color_components, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Out_color_space, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_components, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_height, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Output_width, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.Quantize_colors, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.XDensity, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.YDensity.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
MarkerParser()
delegate bool BitMiracle.LibJpeg.Jpeg.MarkerParser (Jpeg decompressor)
Delegate for application-supplied marker processing methods. Need not pass marker code since it is stored in cinfo.unread_marker.
SetMarkerProcessor()
void BitMiracle.LibJpeg.Jpeg.SetMarkerProcessor (int markerCode, MarkerParser routine) inline
Definition at line 172 of file Jpeg.cs.
         {
             bool f(JpegDecompressStruct _) => routine(this);
             ClassicDecompressor.JpegSetMarkerProcessor(markerCode, f);
         }
References BitMiracle.LibJpeg.Jpeg.ClassicDecompressor, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegSetMarkerProcessor().
Member Data Documentation
m_compressionParameters
CompressionParameters BitMiracle.LibJpeg.Jpeg.m_compressionParameters = new CompressionParameters() private
Definition at line 14 of file Jpeg.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
m_decompressionParameters
DecompressionParameters BitMiracle.LibJpeg.Jpeg.m_decompressionParameters = new DecompressionParameters() private
Definition at line 15 of file Jpeg.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.beforeDecompress().
Property Documentation
ClassicCompressor
JpegCompressStruct BitMiracle.LibJpeg.Jpeg.ClassicCompressor = new JpegCompressStruct(new JpegErrorMessage()) get
Definition at line 161 of file Jpeg.cs.
 { get; } = new JpegCompressStruct(new JpegErrorMessage());
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), and BitMiracle.LibJpeg.Jpeg.Compress().
ClassicDecompressor
JpegDecompressStruct BitMiracle.LibJpeg.Jpeg.ClassicDecompressor = new JpegDecompressStruct(new JpegErrorMessage()) get
Definition at line 163 of file Jpeg.cs.
 { get; } = new JpegDecompressStruct(new JpegErrorMessage());
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), BitMiracle.LibJpeg.Jpeg.beforeDecompress(), BitMiracle.LibJpeg.Jpeg.Decompress(), BitMiracle.LibJpeg.Jpeg.getImageParametersFromDecompressor(), and BitMiracle.LibJpeg.Jpeg.SetMarkerProcessor().
CompressionParameters
CompressionParameters?? BitMiracle.LibJpeg.Jpeg.CompressionParameters get set
Advanced users may set specific parameters of compression
Definition at line 21 of file Jpeg.cs.
         {
             get { return m_compressionParameters; }
             set { m_compressionParameters = value ?? throw new ArgumentNullException(nameof(value)); }
         }
DecompressionParameters
DecompressionParameters?? BitMiracle.LibJpeg.Jpeg.DecompressionParameters get set
Advanced users may set specific parameters of decompression
Definition at line 30 of file Jpeg.cs.
         {
             get { return m_decompressionParameters; }
             set { m_decompressionParameters = value ?? throw new ArgumentNullException(nameof(value)); }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Jpeg.cs