Juniper: Juniper.Animation.AbstractAnimator Class Reference
Juniper.Animation.AbstractAnimator Class Reference abstract
An abstraction layer over different ways of showing UI state. Only one such component is allowed on a gameObject at a time.
Public Member Functions
abstract IEnumerator PlayCoroutine (string name)
Execute an animation and return an IEnumerator that can be used to yield in a coroutine for asynchronous execution.
abstract IEnumerator BlendCoroutine (string fromName, string toName, float amount)
void Play (string name)
Play an animation immediately, with no chance to wait for its completion.
void Blend (string fromName, string toName, float amount)
abstract bool HasState (string name)
Returns true in child classes to indicate they support the given state message.
Static Public Member Functions
static AbstractAnimator GetAnimator (GameObject parent, string[] parts)
Creates the right Animator subclass for a given gameObject. If the gameObject has a Unity Animator on it, GetAnimator will create a UnityAnimator. If the gameObject has child transforms that match the Interaction system's state names, then GetAnimator will create a ChildSwapAnimator.
Detailed Description
An abstraction layer over different ways of showing UI state. Only one such component is allowed on a gameObject at a time.
Definition at line 12 of file AbstractAnimator.cs.
Member Function Documentation
Blend()
void Juniper.Animation.AbstractAnimator.Blend (string fromName, string toName, float amount)
Referenced by Juniper.Widgets.AbstractTouchable.BlendState().
BlendCoroutine()
abstract IEnumerator Juniper.Animation.AbstractAnimator.BlendCoroutine (string fromName, string toName, float amount) pure virtual
Implemented in Juniper.Animation.ChildSwapAnimator.
GetAnimator()
static AbstractAnimator Juniper.Animation.AbstractAnimator.GetAnimator (GameObject parent, string [] parts) inline static
Creates the right Animator subclass for a given gameObject. If the gameObject has a Unity Animator on it, GetAnimator will create a UnityAnimator. If the gameObject has child transforms that match the Interaction system's state names, then GetAnimator will create a ChildSwapAnimator.
Parameters
parent
parts
Returns
Definition at line 23 of file AbstractAnimator.cs.
         {
             var animator = parent.GetComponent<AbstractAnimator>();
             var defaultState = parts[0];
             if (animator == null)
             {
 #if UNITY_MODULES_ANIMATION
                 var anim = parent.GetComponent<Animator>();
                 if (anim != null && UnityAnimator.AnimatorHasState(anim, defaultState))
                 {
                     animator = parent.EnsureComponent<UnityAnimator>().Value;
                 }
                 else
 #endif
                 if (parent.transform.childCount > 0 && parent.transform.Find(defaultState))
                 {
                     var swapper = parent.EnsureComponent<ChildSwapAnimator>().Value;
                     swapper.stateNames = parts;
                     animator = swapper;
                 }
             }
             return animator;
         }
References Juniper.Animation.ChildSwapAnimator.stateNames.
HasState()
abstract bool Juniper.Animation.AbstractAnimator.HasState (string name) pure virtual
Returns true in child classes to indicate they support the given state message.
Parameters
name The animation state to check for
Returns
True or False
Implemented in Juniper.Animation.ChildSwapAnimator.
Referenced by Juniper.Widgets.AbstractTouchable.NormalizePart().
Play()
void Juniper.Animation.AbstractAnimator.Play (string name)
Play an animation immediately, with no chance to wait for its completion.
Parameters
name
Referenced by Juniper.Widgets.AbstractTouchable.ShowState().
PlayCoroutine()
abstract IEnumerator Juniper.Animation.AbstractAnimator.PlayCoroutine (string name) pure virtual
Execute an animation and return an IEnumerator that can be used to yield in a coroutine for asynchronous execution.
Parameters
name
Returns
Implemented in Juniper.Animation.ChildSwapAnimator.
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Unity/Animation/AbstractAnimator.cs