Juniper: Juniper.Unity.Haptics.AndroidAPI1Haptics Class Reference
Juniper.Unity.Haptics.AndroidAPI1Haptics Class Reference
Implements haptic feedback for Android API levels less than 26. Vibration amplitude is not available as an option, only pulse length.
Public Member Functions
override void Cancel ()
Cancel the current vibration, whatever it is.
override void Play (HapticExpression expr)
Play a canned haptic pattern.
override void Play (params HapticPatternElement[] points)
Play a haptic pattern.
override void Play (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
override void Play (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
override void Vibrate (HapticPatternElement point)
Play a single element of a haptic pattern.
override void Vibrate (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
override void Vibrate (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
Protected Member Functions
override IEnumerator VibrateCoroutine (long milliseconds, float amplitude)
Play a single vibration of a set length of time.
override IEnumerator PlayCoroutine (long[] pattern, float[] amplitudes)
Play a patterned vibration, where all of the vibrations are the same amplitude, the default amplitude.
virtual void Awake ()
Get the vibrator service. This can't be done in a static constructor because it crashes the Unity player when JNI objects are accessed at startup.
override IEnumerator VibrateCoroutine (long milliseconds)
Play a single vibration of a set length of time.
override IEnumerator PlayCoroutine (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
Static Protected Attributes
static AndroidJavaObject vibrator
The vibrator service.
Detailed Description
Implements haptic feedback for Android API levels less than 26. Vibration amplitude is not available as an option, only pulse length.
Definition at line 14 of file AndroidAPI1Haptics.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.Awake () inline protected virtual inherited
Get the vibrator service. This can't be done in a static constructor because it crashes the Unity player when JNI objects are accessed at startup.
Reimplemented in Juniper.Unity.Haptics.AndroidAPI26Haptics.
Definition at line 26 of file AbstractAndroidAPIHaptics.cs.
         {
             if (vibrator == null)
             {
                 var unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
                 var currentActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
                 vibrator = currentActivity.Call<AndroidJavaObject>("getSystemService", "vibrator");
             }
         }
References Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator.
Cancel()
override void Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.Cancel () inline virtual inherited
Cancel the current vibration, whatever it is.
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 39 of file AbstractAndroidAPIHaptics.cs.
         {
             base.Cancel();
             vibrator.Call("cancel");
         }
References Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator.
Play() [1/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (HapticExpression expr) inline virtual inherited
Play a canned haptic pattern.
Parameters
expr
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Reimplemented in Juniper.Unity.Haptics.iOS10Haptics.
Definition at line 23 of file AbstractHapticExpressor.cs.
         {
             HapticPatternElement.Play(this, expr);
         }
References Juniper.Unity.Haptics.HapticPatternElement.Play().
Play() [2/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (params HapticPatternElement [] points) inline virtual inherited
Play a haptic pattern.
Parameters
points
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 32 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(points));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [3/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern) inline virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 59 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [4/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern, float [] amplitudes) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 69 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern, amplitudes));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
PlayCoroutine() [1/2]
override IEnumerator Juniper.Unity.Haptics.AndroidAPI1Haptics.PlayCoroutine (long [] pattern, float [] amplitudes) inline protected virtual
Play a patterned vibration, where all of the vibrations are the same amplitude, the default amplitude.
Parameters
pattern Pattern.
amplitudes Strength of vibrations (ignored).
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 39 of file AndroidAPI1Haptics.cs.
         {
             if (pattern.Length > 0)
             {
                 var collapsedPattern = new List<long>();
                 var lastAmp = false;
                 for (var i = 0; i < pattern.Length; ++i)
                 {
                     var curAmp = amplitudes[i] > 0.25f;
                     if (collapsedPattern.Count == 0 || curAmp != lastAmp)
                     {
                         collapsedPattern.Add(0);
                     }
                     collapsedPattern[collapsedPattern.Count - 1] += pattern[i];
                     lastAmp = curAmp;
                 }
                 yield return PlayCoroutine(collapsedPattern.ToArray());
             }
         }
PlayCoroutine() [2/2]
override IEnumerator Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.PlayCoroutine (long [] pattern) inline protected virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Reimplemented in Juniper.Unity.Haptics.AndroidAPI26Haptics.
Definition at line 59 of file AbstractAndroidAPIHaptics.cs.
         {
             vibrator.Call("vibrate", pattern, -1);
             yield return new WaitForSeconds(pattern.Sum() * 0.001f);
         }
References Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator.
Vibrate() [1/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (HapticPatternElement point) inline virtual inherited
Play a single element of a haptic pattern.
Parameters
point
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 41 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(point));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [2/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds) inline virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 50 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [3/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds, float amplitude) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 79 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds, amplitude));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
VibrateCoroutine() [1/2]
override IEnumerator Juniper.Unity.Haptics.AndroidAPI1Haptics.VibrateCoroutine (long milliseconds, float amplitude) inline protected virtual
Play a single vibration of a set length of time.
Parameters
milliseconds Milliseconds.
amplitude Strength of vibration (ignored).
Implements Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 21 of file AndroidAPI1Haptics.cs.
         {
             if (amplitude > 0.25f)
             {
                 yield return VibrateCoroutine(milliseconds);
             }
             else
             {
                 yield return new WaitForSeconds(milliseconds * 0.001f);
             }
         }
VibrateCoroutine() [2/2]
override IEnumerator Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.VibrateCoroutine (long milliseconds) inline protected virtual inherited
Play a single vibration of a set length of time.
Parameters
milliseconds Milliseconds.
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Reimplemented in Juniper.Unity.Haptics.AndroidAPI26Haptics.
Definition at line 49 of file AbstractAndroidAPIHaptics.cs.
         {
             vibrator.Call("vibrate", milliseconds);
             yield return new WaitForSeconds(milliseconds * 0.001f);
         }
References Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator.
Member Data Documentation
vibrator
AndroidJavaObject Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator static protected inherited
The vibrator service.
Definition at line 20 of file AbstractAndroidAPIHaptics.cs.
Referenced by Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.Awake(), Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.Cancel(), Juniper.Unity.Haptics.AndroidAPI26Haptics.CreateVibrationEffect(), Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.PlayCoroutine(), and Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.VibrateCoroutine().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/Android/AndroidAPI1Haptics.cs