Juniper: Juniper.IO.ISerializerExt Class Reference
Juniper.IO.ISerializerExt Class Reference
Static Public Member Functions
static void Serialize< T > (this ISerializer< T > serializer, HttpWebRequest request, MediaType type, T value)
static void Serialize< T > (this ISerializer< T > serializer, HttpListenerResponse response, MediaType type, T value)
static Task SerializeAsync< T, U > (this ISerializer< T > serializer, WebSocketConnection< U > socket, T value)
static Task SerializeAsync< T, U > (this ISerializer< T > serializer, WebSocketConnection< U > socket, string message, T value)
static byte [] Serialize< T > (this ISerializer< T > serializer, T value)
static void Serialize< T > (this ISerializer< T > serializer, FileInfo file, T value)
static void Serialize< T > (this ISerializer< T > serializer, string fileName, T value)
static string ToString< T > (this ISerializer< T > serializer, T value)
Detailed Description
Definition at line 12 of file ISerializerExt.cs.
Member Function Documentation
Serialize< T >() [1/5]
static void Juniper.IO.ISerializerExt.Serialize< T > (this ISerializer< T > serializer, HttpWebRequest request, MediaType type, T value) inline static
Definition at line 14 of file ISerializerExt.cs.
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             using var stream = request.GetRequestStream();
             request.ContentType = type;
             request.ContentLength = serializer.Serialize(stream, value);
         }
References Juniper.IO.ISerializer< in in T >.Serialize().
Serialize< T >() [2/5]
static void Juniper.IO.ISerializerExt.Serialize< T > (this ISerializer< T > serializer, HttpListenerResponse response, MediaType type, T value) inline static
Definition at line 31 of file ISerializerExt.cs.
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             response.ContentType = type;
             response.ContentLength64 = serializer.Serialize(response.OutputStream, value);
         }
References Juniper.IO.ISerializer< in in T >.Serialize().
Serialize< T >() [3/5]
static byte [] Juniper.IO.ISerializerExt.Serialize< T > (this ISerializer< T > serializer, T value) inline static
Definition at line 85 of file ISerializerExt.cs.
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             using var mem = new MemoryStream();
             serializer.Serialize(mem, value);
             mem.Flush();
             return mem.ToArray();
         }
References Juniper.IO.ISerializer< in in T >.Serialize().
Serialize< T >() [4/5]
static void Juniper.IO.ISerializerExt.Serialize< T > (this ISerializer< T > serializer, FileInfo file, T value) inline static
Definition at line 99 of file ISerializerExt.cs.
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             using var stream = file.Open(FileMode.Create, FileAccess.Write, FileShare.Read);
             serializer.Serialize(stream, value);
         }
References Juniper.IO.ISerializer< in in T >.Serialize().
Serialize< T >() [5/5]
static void Juniper.IO.ISerializerExt.Serialize< T > (this ISerializer< T > serializer, string fileName, T value) inline static
Definition at line 115 of file ISerializerExt.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             serializer.Serialize(new FileInfo(fileName), value);
         }
References Juniper.IO.ISerializer< in in T >.Serialize().
SerializeAsync< T, U >() [1/2]
static Task Juniper.IO.ISerializerExt.SerializeAsync< T, U > (this ISerializer< T > serializer, WebSocketConnection< U > socket, T value) inline static
Type Constraints
U : WebSocket
Definition at line 47 of file ISerializerExt.cs.
                     : WebSocket
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             if (socket is null)
             {
                 throw new ArgumentNullException(nameof(socket));
             }
             var data = serializer.Serialize(value);
             return socket.SendAsync(data);
         }
SerializeAsync< T, U >() [2/2]
static Task Juniper.IO.ISerializerExt.SerializeAsync< T, U > (this ISerializer< T > serializer, WebSocketConnection< U > socket, string message, T value) inline static
Type Constraints
U : WebSocket
Definition at line 64 of file ISerializerExt.cs.
                     : WebSocket
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             if (socket is null)
             {
                 throw new ArgumentNullException(nameof(socket));
             }
             if (message is null)
             {
                 throw new ArgumentNullException(nameof(message));
             }
             return socket.SendAsync(message, value, serializer);
         }
ToString< T >()
static string Juniper.IO.ISerializerExt.ToString< T > (this ISerializer< T > serializer, T value) inline static
Definition at line 130 of file ISerializerExt.cs.
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             return Encoding.UTF8.GetString(serializer.Serialize(value));
         }
References Juniper.IO.ISerializer< in in T >.Serialize().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/ISerializerExt.cs