Juniper: Juniper.MediaType.Audio Class Reference
Juniper.MediaType.Audio Class Reference
Public Member Functions
override bool Matches (string fileName)
bool Matches (FileInfo file)
string AddExtension (string fileName)
bool Equals (string other)
override bool Equals (object obj)
bool Equals (MediaType other)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static MediaType Parse (string value)
static IReadOnlyCollection< MediaType > ParseAll (string[] acceptTypes)
static bool TryParse (string value, out MediaType type)
static IReadOnlyList< MediaType > GuessByFileName (string fileName)
static IReadOnlyList< MediaType > GuessByFile (FileInfo file)
static MediaType Lookup (string value)
static ContentReference operator+ (string cacheID, MediaType contentType)
static implicit operator string (MediaType mediaType)
static bool operator== (MediaType left, MediaType right)
static bool operator== (MediaType left, string right)
static bool operator== (string left, MediaType right)
static bool operator != (MediaType left, MediaType right)
static bool operator != (MediaType left, string right)
static bool operator != (string left, MediaType right)
Static Public Attributes
static readonly Audio AnyAudio = new Audio("*")
static readonly Audio Aac = new Audio("aac")
static readonly Audio Ac3 = new Audio("ac3")
static readonly Audio Adpcm = new Audio("adpcm", new string[] { "adp" })
static readonly Audio AMR = new Audio("amr")
static readonly Audio AMR_WB = new Audio("amr-wb")
static readonly Audio Amr_WbPlus = new Audio("amr-wb+")
static readonly Audio Aptx = new Audio("aptx")
static readonly Audio Asc = new Audio("asc")
static readonly Audio ATRAC_ADVANCED_LOSSLESS = new Audio("atrac-advanced-lossless")
static readonly Audio ATRAC_X = new Audio("atrac-x")
static readonly Audio ATRAC3 = new Audio("atrac3")
static readonly Audio Basic = new Audio("basic", new string[] { "au", "snd" })
static readonly Audio BV16 = new Audio("bv16")
static readonly Audio BV32 = new Audio("bv32")
static readonly Audio Clearmode = new Audio("clearmode")
static readonly Audio CN = new Audio("cn")
static readonly Audio DAT12 = new Audio("dat12")
static readonly Audio Dls = new Audio("dls")
static readonly Audio Dsr_Es201108 = new Audio("dsr-es201108")
static readonly Audio Dsr_Es202050 = new Audio("dsr-es202050")
static readonly Audio Dsr_Es202211 = new Audio("dsr-es202211")
static readonly Audio Dsr_Es202212 = new Audio("dsr-es202212")
static readonly Audio DV = new Audio("dv")
static readonly Audio DVI4 = new Audio("dvi4")
static readonly Audio Eac3 = new Audio("eac3")
static readonly Audio Encaprtp = new Audio("encaprtp")
static readonly Audio EVRC = new Audio("evrc")
static readonly Audio EVRC_QCP = new Audio("evrc-qcp")
static readonly Audio EVRC0 = new Audio("evrc0")
static readonly Audio EVRC1 = new Audio("evrc1")
static readonly Audio EVRCB = new Audio("evrcb")
static readonly Audio EVRCB0 = new Audio("evrcb0")
static readonly Audio EVRCB1 = new Audio("evrcb1")
static readonly Audio EVRCNW = new Audio("evrcnw")
static readonly Audio EVRCNW0 = new Audio("evrcnw0")
static readonly Audio EVRCNW1 = new Audio("evrcnw1")
static readonly Audio EVRCWB = new Audio("evrcwb")
static readonly Audio EVRCWB0 = new Audio("evrcwb0")
static readonly Audio EVRCWB1 = new Audio("evrcwb1")
static readonly Audio EVS = new Audio("evs")
static readonly Audio Example = new Audio("example")
static readonly Audio Flexfec = new Audio("flexfec")
static readonly Audio Fwdred = new Audio("fwdred")
static readonly Audio G711_0 = new Audio("g711-0")
static readonly Audio G719 = new Audio("g719")
static readonly Audio G722 = new Audio("g722")
static readonly Audio G7221 = new Audio("g7221")
static readonly Audio G723 = new Audio("g723")
static readonly Audio G726_16 = new Audio("g726-16")
static readonly Audio G726_24 = new Audio("g726-24")
static readonly Audio G726_32 = new Audio("g726-32")
static readonly Audio G726_40 = new Audio("g726-40")
static readonly Audio G728 = new Audio("g728")
static readonly Audio G729 = new Audio("g729")
static readonly Audio G7291 = new Audio("g7291")
static readonly Audio G729D = new Audio("g729d")
static readonly Audio G729E = new Audio("g729e")
static readonly Audio GSM = new Audio("gsm")
static readonly Audio GSM_EFR = new Audio("gsm-efr")
static readonly Audio GSM_HR_08 = new Audio("gsm-hr-08")
static readonly Audio ILBC = new Audio("ilbc")
static readonly Audio Ip_Mr_v25 = new Audio("ip-mr_v2.5")
static readonly Audio Isac = new Audio("isac")
static readonly Audio L16 = new Audio("l16")
static readonly Audio L20 = new Audio("l20")
static readonly Audio L24 = new Audio("l24")
static readonly Audio L8 = new Audio("l8")
static readonly Audio LPC = new Audio("lpc")
static readonly Audio MELP = new Audio("melp")
static readonly Audio MELP1200 = new Audio("melp1200")
static readonly Audio MELP2400 = new Audio("melp2400")
static readonly Audio MELP600 = new Audio("melp600")
static readonly Audio Midi = new Audio("midi", new string[] { "mid", "midi", "kar", "rmi" })
static readonly Audio Mobile_Xmf = new Audio("mobile-xmf")
static readonly Audio Mp4 = new Audio("mp4", new string[] { "m4a", "mp4a" })
static readonly Audio MP4A_LATM = new Audio("mp4a-latm")
static readonly Audio MPA = new Audio("mpa")
static readonly Audio Mpa_Robust = new Audio("mpa-robust")
static readonly Audio Mpeg = new Audio("mpeg", new string[] { "mp3", "mp2", "mp2a", "mpga", "m2a", "m3a" })
static readonly Audio Mpeg4_Generic = new Audio("mpeg4-generic")
static readonly Audio Musepack = new Audio("musepack")
static readonly Audio Ogg = new Audio("ogg", new string[] { "ogg", "oga", "spx" })
static readonly Audio Opus = new Audio("opus")
static readonly Audio Parityfec = new Audio("parityfec")
static readonly Audio PCMA = new Audio("pcma")
static readonly Audio PCMA_WB = new Audio("pcma-wb")
static readonly Audio PCMU = new Audio("pcmu")
static readonly Audio PCMU_WB = new Audio("pcmu-wb")
static readonly Audio PrsSid = new Audio("prs.sid")
static readonly Audio Qcelp = new Audio("qcelp")
static readonly Audio Raptorfec = new Audio("raptorfec")
static readonly Audio RED = new Audio("red")
static readonly Audio Rtp_Enc_Aescm128 = new Audio("rtp-enc-aescm128")
static readonly Audio Rtp_Midi = new Audio("rtp-midi")
static readonly Audio Rtploopback = new Audio("rtploopback")
static readonly Audio Rtx = new Audio("rtx")
static readonly Audio S3m = new Audio("s3m", new string[] { "s3m" })
static readonly Audio Silk = new Audio("silk", new string[] { "sil" })
static readonly Audio SMV = new Audio("smv")
static readonly Audio SMV_QCP = new Audio("smv-qcp")
static readonly Audio SMV0 = new Audio("smv0")
static readonly Audio Sp_Midi = new Audio("sp-midi")
static readonly Audio Speex = new Audio("speex")
static readonly Audio T140c = new Audio("t140c")
static readonly Audio T38 = new Audio("t38")
static readonly Audio Telephone_Event = new Audio("telephone-event")
static readonly Audio TETRA_ACELP = new Audio("tetra_acelp")
static readonly Audio TETRA_ACELP_BB = new Audio("tetra_acelp_bb")
static readonly Audio Tone = new Audio("tone")
static readonly Audio UEMCLIP = new Audio("uemclip")
static readonly Audio Ulpfec = new Audio("ulpfec")
static readonly Audio Usac = new Audio("usac")
static readonly Audio VDVI = new Audio("vdvi")
static readonly Audio Vendor1d_Interleaved_Parityfec = new Audio("1d-interleaved-parityfec")
static readonly Audio Vendor32kadpcm = new Audio("32kadpcm")
static readonly Audio Vendor3gpp = new Audio("3gpp")
static readonly Audio Vendor3gpp2 = new Audio("3gpp2")
static readonly Audio Vendor3gppIufp = new Audio("vnd.3gpp.iufp")
static readonly Audio Vendor4SB = new Audio("vnd.4sb")
static readonly Audio VendorAudiokoz = new Audio("vnd.audiokoz")
static readonly Audio VendorCELP = new Audio("vnd.celp")
static readonly Audio VendorCiscoNse = new Audio("vnd.cisco.nse")
static readonly Audio VendorCmlesRadio_Events = new Audio("vnd.cmles.radio-events")
static readonly Audio VendorCnsAnp1 = new Audio("vnd.cns.anp1")
static readonly Audio VendorCnsInf1 = new Audio("vnd.cns.inf1")
static readonly Audio VendorDeceAudio = new Audio("vnd.dece.audio", new string[] { "uva", "uvva" })
static readonly Audio VendorDigital_Winds = new Audio("vnd.digital-winds", new string[] { "eol" })
static readonly Audio VendorDlnaAdts = new Audio("vnd.dlna.adts")
static readonly Audio VendorDolbyHeaac1 = new Audio("vnd.dolby.heaac.1")
static readonly Audio VendorDolbyHeaac2 = new Audio("vnd.dolby.heaac.2")
static readonly Audio VendorDolbyMlp = new Audio("vnd.dolby.mlp")
static readonly Audio VendorDolbyMps = new Audio("vnd.dolby.mps")
static readonly Audio VendorDolbyPl2 = new Audio("vnd.dolby.pl2")
static readonly Audio VendorDolbyPl2x = new Audio("vnd.dolby.pl2x")
static readonly Audio VendorDolbyPl2z = new Audio("vnd.dolby.pl2z")
static readonly Audio VendorDolbyPulse1 = new Audio("vnd.dolby.pulse.1")
static readonly Audio VendorDra = new Audio("vnd.dra", new string[] { "dra" })
static readonly Audio VendorDts = new Audio("vnd.dts", new string[] { "dts" })
static readonly Audio VendorDtsHd = new Audio("vnd.dts.hd", new string[] { "dtshd" })
static readonly Audio VendorDtsUhd = new Audio("vnd.dts.uhd")
static readonly Audio VendorDvbFile = new Audio("vnd.dvb.file")
static readonly Audio VendorEveradPlj = new Audio("vnd.everad.plj")
static readonly Audio VendorHnsAudio = new Audio("vnd.hns.audio")
static readonly Audio VendorLucentVoice = new Audio("vnd.lucent.voice", new string[] { "lvp" })
static readonly Audio VendorMs_PlayreadyMediaPya = new Audio("vnd.ms-playready.media.pya", new string[] { "pya" })
static readonly Audio VendorNokiaMobile_Xmf = new Audio("vnd.nokia.mobile-xmf")
static readonly Audio VendorNortelVbk = new Audio("vnd.nortel.vbk")
static readonly Audio VendorNueraEcelp4800 = new Audio("vnd.nuera.ecelp4800", new string[] { "ecelp4800" })
static readonly Audio VendorNueraEcelp7470 = new Audio("vnd.nuera.ecelp7470", new string[] { "ecelp7470" })
static readonly Audio VendorNueraEcelp9600 = new Audio("vnd.nuera.ecelp9600", new string[] { "ecelp9600" })
static readonly Audio VendorOctelSbc = new Audio("vnd.octel.sbc")
static readonly Audio VendorPresonusMultitrack = new Audio("vnd.presonus.multitrack")
static readonly Audio VendorQcelp = new Audio("vnd.qcelp")
static readonly Audio VendorRhetorex32kadpcm = new Audio("vnd.rhetorex.32kadpcm")
static readonly Audio VendorRip = new Audio("vnd.rip", new string[] { "rip" })
static readonly Audio VendorSealedmediaSoftsealMpeg = new Audio("vnd.sealedmedia.softseal.mpeg")
static readonly Audio VendorVmxCvsd = new Audio("vnd.vmx.cvsd")
static readonly Audio VMR_WB = new Audio("vmr-wb")
static readonly Audio Vorbis = new Audio("vorbis")
static readonly Audio Vorbis_Config = new Audio("vorbis-config")
static readonly Audio Webm = new Audio("webm", new string[] { "weba" })
static readonly Audio X_Aac = new Audio("x-aac", new string[] { "aac" })
static readonly Audio X_Aiff = new Audio("x-aiff", new string[] { "aif", "aiff", "aifc" })
static readonly Audio X_Caf = new Audio("x-caf", new string[] { "caf" })
static readonly Audio X_Flac = new Audio("x-flac", new string[] { "flac" })
static readonly Audio X_Matroska = new Audio("x-matroska", new string[] { "mka" })
static readonly Audio X_Mpegurl = new Audio("x-mpegurl", new string[] { "m3u" })
static readonly Audio X_Ms_Wax = new Audio("x-ms-wax", new string[] { "wax" })
static readonly Audio X_Ms_Wma = new Audio("x-ms-wma", new string[] { "wma" })
static readonly Audio X_Pn_Realaudio = new Audio("x-pn-realaudio", new string[] { "ram", "ra" })
static readonly Audio X_Pn_Realaudio_Plugin = new Audio("x-pn-realaudio-plugin", new string[] { "rmp" })
static readonly Audio X_Tta = new Audio("x-tta")
static readonly Audio X_Wav = new Audio("x-wav", new string[] { "wav" })
static readonly Audio Xm = new Audio("xm", new string[] { "xm" })
static new readonly Audio [] Values
static readonly MediaType Any = new MediaType("*/*")
static readonly IReadOnlyCollection< MediaType > All = new MediaType[] { Any }
Properties
string Value [get]
string TypeName [get]
string SubTypeName [get]
float Weight [get]
ReadOnlyCollection< string > Extensions [get]
string PrimaryExtension [get]
Private Member Functions
Audio (string value, string[] extensions)
Audio (string value)
Detailed Description
Definition at line 7 of file Audio.cs.
Constructor & Destructor Documentation
Audio() [1/2]
Juniper.MediaType.Audio.Audio (string value, string [] extensions) inline private
Definition at line 9 of file Audio.cs.
 : base("audio/" + value, extensions) { }
Audio() [2/2]
Juniper.MediaType.Audio.Audio (string value) inline private
Definition at line 11 of file Audio.cs.
 : this(value, null) { }
Member Function Documentation
AddExtension()
string Juniper.MediaType.AddExtension (string fileName) inline inherited
Definition at line 310 of file MediaType.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (PrimaryExtension is object)
             {
                 var currentExtension = PathExt.GetShortExtension(fileName);
                 if (Extensions.IndexOf(currentExtension) == -1)
                 {
                     fileName += "." + PrimaryExtension;
                 }
             }
             return fileName;
         }
References Juniper.MediaType.Extensions, System.IO.PathExt.GetShortExtension(), and Juniper.MediaType.PrimaryExtension.
Referenced by Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), and Juniper.IO.ContentReference.operator string().
Equals() [1/3]
bool Juniper.MediaType.Equals (string other) inline inherited
Definition at line 329 of file MediaType.cs.
         {
             return TryParse(other, out var type)
                 && Equals(type);
         }
References Juniper.MediaType.TryParse().
Referenced by Juniper.MediaType.Equals().
Equals() [2/3]
override bool Juniper.MediaType.Equals (object obj) inline inherited
Definition at line 335 of file MediaType.cs.
         {
             return (obj is MediaType type && Equals(type))
                 || (obj is string str && Equals(str));
         }
References Juniper.MediaType.Equals().
Equals() [3/3]
bool Juniper.MediaType.Equals (MediaType other) inline inherited
Definition at line 341 of file MediaType.cs.
         {
             return other is object
                 && (TypeName == "*"
                     || other.TypeName == "*"
                     || TypeName == other.TypeName)
                 && (SubTypeName == "*"
                     || other.SubTypeName == "*"
                     || SubTypeName == other.SubTypeName);
         }
References Juniper.MediaType.SubTypeName, and Juniper.MediaType.TypeName.
GetHashCode()
override int Juniper.MediaType.GetHashCode () inline inherited
Definition at line 397 of file MediaType.cs.
         {
             var hashCode = -1006577490;
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(TypeName);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(SubTypeName);
             hashCode = (hashCode * -1521134295) + Weight.GetHashCode();
             hashCode = (hashCode * -1521134295) + EqualityComparer<ReadOnlyCollection<string>>.Default.GetHashCode(Extensions);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(PrimaryExtension);
             return hashCode;
         }
References Juniper.MediaType.Extensions, Juniper.MediaType.PrimaryExtension, Juniper.MediaType.SubTypeName, Juniper.MediaType.TypeName, and Juniper.MediaType.Weight.
GuessByFile()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFile (FileInfo file) inline static inherited
Definition at line 155 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return GuessByFileName(file.Name);
         }
References Juniper.MediaType.GuessByFileName().
Referenced by Juniper.HTTP.Server.HttpListenerResponseExt.SendFileAsync().
GuessByFileName()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFileName (string fileName) inline static inherited
Definition at line 144 of file MediaType.cs.
         {
             if (string.IsNullOrEmpty(fileName))
             {
                 throw new ArgumentException("Must provide a valid fileName", nameof(fileName));
             }
             var ext = Path.GetExtension(fileName);
             return GuessByExtension(ref ext);
         }
References Juniper.MediaType.GuessByExtension().
Referenced by Juniper.MediaType.GuessByFile(), and Juniper.MediaType.Matches().
Lookup()
static MediaType Juniper.MediaType.Lookup (string value) inline static inherited
Definition at line 165 of file MediaType.cs.
         {
             // Trim off the weight, if one exists
             var parts = value.SplitX(';');
             if (parts.Length > 0)
             {
                 value = parts[0];
             }
             if (byValue.ContainsKey(value))
             {
                 return byValue[value];
             }
             var name = Array.Find(parts, p => p.Length > 0);
             if (string.IsNullOrEmpty(name))
             {
                 return Lookup("unknown/unknown");
             }
             else
             {
                 return new Unknown(name);
             }
         }
References Juniper.MediaType.byValue.
Matches() [1/2]
override bool Juniper.MediaType.Audio.Matches (string fileName) inline virtual
Reimplemented from Juniper.MediaType.
Definition at line 15 of file Audio.cs.
             {
                 if (ReferenceEquals(this, AnyAudio))
                 {
                     return Values.Any(x => x.Matches(fileName));
                 }
                 else
                 {
                     return base.Matches(fileName);
                 }
             }
References Juniper.MediaType.Any, Juniper.MediaType.Audio.AnyAudio, Juniper.MediaType.Matches(), and Juniper.MediaType.Audio.Values.
Matches() [2/2]
bool Juniper.MediaType.Matches (FileInfo file) inline inherited
Definition at line 300 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return Matches(file.Name);
         }
References Juniper.MediaType.Matches().
operator !=() [1/3]
static bool Juniper.MediaType.operator != (MediaType left, MediaType right) inline static inherited
Definition at line 358 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [2/3]
static bool Juniper.MediaType.operator != (MediaType left, string right) inline static inherited
Definition at line 369 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [3/3]
static bool Juniper.MediaType.operator != (string left, MediaType right) inline static inherited
Definition at line 380 of file MediaType.cs.
         {
             return !(left == right);
         }
operator string()
static implicit Juniper.MediaType.operator string (MediaType mediaType) inline static inherited
Definition at line 196 of file MediaType.cs.
         {
             return mediaType?.ToString();
         }
operator+()
static ContentReference Juniper.MediaType.operator+ (string cacheID, MediaType contentType) inline static inherited
Definition at line 191 of file MediaType.cs.
         {
             return new ContentReference(cacheID, contentType);
         }
operator==() [1/3]
static bool Juniper.MediaType.operator== (MediaType left, MediaType right) inline static inherited
Definition at line 352 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [2/3]
static bool Juniper.MediaType.operator== (MediaType left, string right) inline static inherited
Definition at line 363 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [3/3]
static bool Juniper.MediaType.operator== (string left, MediaType right) inline static inherited
Definition at line 374 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (right is object && right.Equals(left));
         }
Parse()
static MediaType Juniper.MediaType.Parse (string value) inline static inherited
Definition at line 40 of file MediaType.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             if (TryParse(value, out var type))
             {
                 return type;
             }
             else
             {
                 throw new ArgumentException($"Type value does not match expected pattern {TYPE_PATTERN.ToString()}", nameof(value));
             }
         }
References Juniper.MediaType.TryParse().
ParseAll()
static IReadOnlyCollection<MediaType> Juniper.MediaType.ParseAll (string [] acceptTypes) inline static inherited
Definition at line 57 of file MediaType.cs.
         {
             if (acceptTypes is null || acceptTypes.Length == 0)
             {
                 return All;
             }
             else
             {
                 return InternalParseAll(acceptTypes).ToArray();
             }
         }
References Juniper.MediaType.All, and Juniper.MediaType.InternalParseAll().
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable().
ToString()
override string Juniper.MediaType.ToString () inline inherited
Definition at line 385 of file MediaType.cs.
         {
             if (Weight == 1)
             {
                 return Value;
             }
             else
             {
                 return weightedValue;
             }
         }
References Juniper.MediaType.Value, Juniper.MediaType.Weight, and Juniper.MediaType.weightedValue.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.ListDirectoryAsync().
TryParse()
static bool Juniper.MediaType.TryParse (string value, out MediaType type) inline static inherited
Definition at line 83 of file MediaType.cs.
         {
             type = null;
             if (value is null)
             {
                 return false;
             }
             var match = TYPE_PATTERN.Match(value);
             if (!match.Success)
             {
                 return false;
             }
             var typeName = match.Groups[1].Value;
             var subTypeName = match.Groups[2].Value;
             var rawValue = typeName + "/" + subTypeName;
             if (match.Groups.Count == 4
                 && float.TryParse(
                     match.Groups[3].Value,
                     NumberStyles.Integer | NumberStyles.AllowDecimalPoint,
                     CultureInfo.InvariantCulture,
                     out var weight))
             {
                 type = new MediaType(typeName, subTypeName, weight);
             }
             else if (byValue.ContainsKey(rawValue))
             {
                 type = byValue[rawValue];
             }
             else
             {
                 type = new MediaType(typeName, subTypeName);
             }
             return type is object;
         }
References Juniper.MediaType.byValue, Juniper.MediaType.MediaType(), and Juniper.MediaType.TYPE_PATTERN.
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.InternalParseAll(), Juniper.MediaType.Parse(), and Juniper.Processes.ProcessArgs.TryGetMediaType().
Member Data Documentation
Aac
readonly Audio Juniper.MediaType.Audio.Aac = new Audio("aac") static
Definition at line 7 of file Audio.Values.cs.
Ac3
readonly Audio Juniper.MediaType.Audio.Ac3 = new Audio("ac3") static
Definition at line 8 of file Audio.Values.cs.
Adpcm
readonly Audio Juniper.MediaType.Audio.Adpcm = new Audio("adpcm", new string[] { "adp" }) static
Definition at line 9 of file Audio.Values.cs.
All
readonly IReadOnlyCollection<MediaType> Juniper.MediaType.All = new MediaType[] { Any } static inherited
Definition at line 38 of file MediaType.cs.
Referenced by Juniper.MediaType.ParseAll().
AMR
readonly Audio Juniper.MediaType.Audio.AMR = new Audio("amr") static
Definition at line 10 of file Audio.Values.cs.
AMR_WB
readonly Audio Juniper.MediaType.Audio.AMR_WB = new Audio("amr-wb") static
Definition at line 11 of file Audio.Values.cs.
Amr_WbPlus
readonly Audio Juniper.MediaType.Audio.Amr_WbPlus = new Audio("amr-wb+") static
Definition at line 12 of file Audio.Values.cs.
Any
readonly MediaType Juniper.MediaType.Any = new MediaType("*/*") static inherited
Definition at line 36 of file MediaType.cs.
Referenced by Juniper.MediaType.Application.Matches(), Juniper.MediaType.XConference.Matches(), Juniper.MediaType.Video.Matches(), Juniper.MediaType.Text.Matches(), Juniper.MediaType.Multipart.Matches(), Juniper.MediaType.Model.Matches(), Juniper.MediaType.Message.Matches(), Juniper.MediaType.Image.Matches(), Juniper.MediaType.Font.Matches(), Juniper.MediaType.Chemical.Matches(), and Juniper.MediaType.Audio.Matches().
AnyAudio
readonly Audio Juniper.MediaType.Audio.AnyAudio = new Audio("*") static
Definition at line 13 of file Audio.cs.
Referenced by Juniper.MediaType.Audio.Matches().
Aptx
readonly Audio Juniper.MediaType.Audio.Aptx = new Audio("aptx") static
Definition at line 13 of file Audio.Values.cs.
Asc
readonly Audio Juniper.MediaType.Audio.Asc = new Audio("asc") static
Definition at line 14 of file Audio.Values.cs.
ATRAC3
readonly Audio Juniper.MediaType.Audio.ATRAC3 = new Audio("atrac3") static
Definition at line 17 of file Audio.Values.cs.
ATRAC_ADVANCED_LOSSLESS
readonly Audio Juniper.MediaType.Audio.ATRAC_ADVANCED_LOSSLESS = new Audio("atrac-advanced-lossless") static
Definition at line 15 of file Audio.Values.cs.
ATRAC_X
readonly Audio Juniper.MediaType.Audio.ATRAC_X = new Audio("atrac-x") static
Definition at line 16 of file Audio.Values.cs.
Basic
readonly Audio Juniper.MediaType.Audio.Basic = new Audio("basic", new string[] { "au", "snd" }) static
Definition at line 18 of file Audio.Values.cs.
BV16
readonly Audio Juniper.MediaType.Audio.BV16 = new Audio("bv16") static
Definition at line 19 of file Audio.Values.cs.
BV32
readonly Audio Juniper.MediaType.Audio.BV32 = new Audio("bv32") static
Definition at line 20 of file Audio.Values.cs.
Clearmode
readonly Audio Juniper.MediaType.Audio.Clearmode = new Audio("clearmode") static
Definition at line 21 of file Audio.Values.cs.
CN
readonly Audio Juniper.MediaType.Audio.CN = new Audio("cn") static
Definition at line 22 of file Audio.Values.cs.
DAT12
readonly Audio Juniper.MediaType.Audio.DAT12 = new Audio("dat12") static
Definition at line 23 of file Audio.Values.cs.
Dls
readonly Audio Juniper.MediaType.Audio.Dls = new Audio("dls") static
Definition at line 24 of file Audio.Values.cs.
Dsr_Es201108
readonly Audio Juniper.MediaType.Audio.Dsr_Es201108 = new Audio("dsr-es201108") static
Definition at line 25 of file Audio.Values.cs.
Dsr_Es202050
readonly Audio Juniper.MediaType.Audio.Dsr_Es202050 = new Audio("dsr-es202050") static
Definition at line 26 of file Audio.Values.cs.
Dsr_Es202211
readonly Audio Juniper.MediaType.Audio.Dsr_Es202211 = new Audio("dsr-es202211") static
Definition at line 27 of file Audio.Values.cs.
Dsr_Es202212
readonly Audio Juniper.MediaType.Audio.Dsr_Es202212 = new Audio("dsr-es202212") static
Definition at line 28 of file Audio.Values.cs.
DV
readonly Audio Juniper.MediaType.Audio.DV = new Audio("dv") static
Definition at line 29 of file Audio.Values.cs.
DVI4
readonly Audio Juniper.MediaType.Audio.DVI4 = new Audio("dvi4") static
Definition at line 30 of file Audio.Values.cs.
Eac3
readonly Audio Juniper.MediaType.Audio.Eac3 = new Audio("eac3") static
Definition at line 31 of file Audio.Values.cs.
Encaprtp
readonly Audio Juniper.MediaType.Audio.Encaprtp = new Audio("encaprtp") static
Definition at line 32 of file Audio.Values.cs.
EVRC
readonly Audio Juniper.MediaType.Audio.EVRC = new Audio("evrc") static
Definition at line 33 of file Audio.Values.cs.
EVRC0
readonly Audio Juniper.MediaType.Audio.EVRC0 = new Audio("evrc0") static
Definition at line 35 of file Audio.Values.cs.
EVRC1
readonly Audio Juniper.MediaType.Audio.EVRC1 = new Audio("evrc1") static
Definition at line 36 of file Audio.Values.cs.
EVRC_QCP
readonly Audio Juniper.MediaType.Audio.EVRC_QCP = new Audio("evrc-qcp") static
Definition at line 34 of file Audio.Values.cs.
EVRCB
readonly Audio Juniper.MediaType.Audio.EVRCB = new Audio("evrcb") static
Definition at line 37 of file Audio.Values.cs.
EVRCB0
readonly Audio Juniper.MediaType.Audio.EVRCB0 = new Audio("evrcb0") static
Definition at line 38 of file Audio.Values.cs.
EVRCB1
readonly Audio Juniper.MediaType.Audio.EVRCB1 = new Audio("evrcb1") static
Definition at line 39 of file Audio.Values.cs.
EVRCNW
readonly Audio Juniper.MediaType.Audio.EVRCNW = new Audio("evrcnw") static
Definition at line 40 of file Audio.Values.cs.
EVRCNW0
readonly Audio Juniper.MediaType.Audio.EVRCNW0 = new Audio("evrcnw0") static
Definition at line 41 of file Audio.Values.cs.
EVRCNW1
readonly Audio Juniper.MediaType.Audio.EVRCNW1 = new Audio("evrcnw1") static
Definition at line 42 of file Audio.Values.cs.
EVRCWB
readonly Audio Juniper.MediaType.Audio.EVRCWB = new Audio("evrcwb") static
Definition at line 43 of file Audio.Values.cs.
EVRCWB0
readonly Audio Juniper.MediaType.Audio.EVRCWB0 = new Audio("evrcwb0") static
Definition at line 44 of file Audio.Values.cs.
EVRCWB1
readonly Audio Juniper.MediaType.Audio.EVRCWB1 = new Audio("evrcwb1") static
Definition at line 45 of file Audio.Values.cs.
EVS
readonly Audio Juniper.MediaType.Audio.EVS = new Audio("evs") static
Definition at line 46 of file Audio.Values.cs.
Example
readonly Audio Juniper.MediaType.Audio.Example = new Audio("example") static
Definition at line 47 of file Audio.Values.cs.
Flexfec
readonly Audio Juniper.MediaType.Audio.Flexfec = new Audio("flexfec") static
Definition at line 48 of file Audio.Values.cs.
Fwdred
readonly Audio Juniper.MediaType.Audio.Fwdred = new Audio("fwdred") static
Definition at line 49 of file Audio.Values.cs.
G711_0
readonly Audio Juniper.MediaType.Audio.G711_0 = new Audio("g711-0") static
Definition at line 50 of file Audio.Values.cs.
G719
readonly Audio Juniper.MediaType.Audio.G719 = new Audio("g719") static
Definition at line 51 of file Audio.Values.cs.
G722
readonly Audio Juniper.MediaType.Audio.G722 = new Audio("g722") static
Definition at line 52 of file Audio.Values.cs.
G7221
readonly Audio Juniper.MediaType.Audio.G7221 = new Audio("g7221") static
Definition at line 53 of file Audio.Values.cs.
G723
readonly Audio Juniper.MediaType.Audio.G723 = new Audio("g723") static
Definition at line 54 of file Audio.Values.cs.
G726_16
readonly Audio Juniper.MediaType.Audio.G726_16 = new Audio("g726-16") static
Definition at line 55 of file Audio.Values.cs.
G726_24
readonly Audio Juniper.MediaType.Audio.G726_24 = new Audio("g726-24") static
Definition at line 56 of file Audio.Values.cs.
G726_32
readonly Audio Juniper.MediaType.Audio.G726_32 = new Audio("g726-32") static
Definition at line 57 of file Audio.Values.cs.
G726_40
readonly Audio Juniper.MediaType.Audio.G726_40 = new Audio("g726-40") static
Definition at line 58 of file Audio.Values.cs.
G728
readonly Audio Juniper.MediaType.Audio.G728 = new Audio("g728") static
Definition at line 59 of file Audio.Values.cs.
G729
readonly Audio Juniper.MediaType.Audio.G729 = new Audio("g729") static
Definition at line 60 of file Audio.Values.cs.
G7291
readonly Audio Juniper.MediaType.Audio.G7291 = new Audio("g7291") static
Definition at line 61 of file Audio.Values.cs.
G729D
readonly Audio Juniper.MediaType.Audio.G729D = new Audio("g729d") static
Definition at line 62 of file Audio.Values.cs.
G729E
readonly Audio Juniper.MediaType.Audio.G729E = new Audio("g729e") static
Definition at line 63 of file Audio.Values.cs.
GSM
readonly Audio Juniper.MediaType.Audio.GSM = new Audio("gsm") static
Definition at line 64 of file Audio.Values.cs.
GSM_EFR
readonly Audio Juniper.MediaType.Audio.GSM_EFR = new Audio("gsm-efr") static
Definition at line 65 of file Audio.Values.cs.
GSM_HR_08
readonly Audio Juniper.MediaType.Audio.GSM_HR_08 = new Audio("gsm-hr-08") static
Definition at line 66 of file Audio.Values.cs.
ILBC
readonly Audio Juniper.MediaType.Audio.ILBC = new Audio("ilbc") static
Definition at line 67 of file Audio.Values.cs.
Ip_Mr_v25
readonly Audio Juniper.MediaType.Audio.Ip_Mr_v25 = new Audio("ip-mr_v2.5") static
Definition at line 68 of file Audio.Values.cs.
Isac
readonly Audio Juniper.MediaType.Audio.Isac = new Audio("isac") static
Definition at line 69 of file Audio.Values.cs.
L16
readonly Audio Juniper.MediaType.Audio.L16 = new Audio("l16") static
Definition at line 70 of file Audio.Values.cs.
L20
readonly Audio Juniper.MediaType.Audio.L20 = new Audio("l20") static
Definition at line 71 of file Audio.Values.cs.
L24
readonly Audio Juniper.MediaType.Audio.L24 = new Audio("l24") static
Definition at line 72 of file Audio.Values.cs.
L8
readonly Audio Juniper.MediaType.Audio.L8 = new Audio("l8") static
Definition at line 73 of file Audio.Values.cs.
LPC
readonly Audio Juniper.MediaType.Audio.LPC = new Audio("lpc") static
Definition at line 74 of file Audio.Values.cs.
MELP
readonly Audio Juniper.MediaType.Audio.MELP = new Audio("melp") static
Definition at line 75 of file Audio.Values.cs.
MELP1200
readonly Audio Juniper.MediaType.Audio.MELP1200 = new Audio("melp1200") static
Definition at line 76 of file Audio.Values.cs.
MELP2400
readonly Audio Juniper.MediaType.Audio.MELP2400 = new Audio("melp2400") static
Definition at line 77 of file Audio.Values.cs.
MELP600
readonly Audio Juniper.MediaType.Audio.MELP600 = new Audio("melp600") static
Definition at line 78 of file Audio.Values.cs.
Midi
readonly Audio Juniper.MediaType.Audio.Midi = new Audio("midi", new string[] { "mid", "midi", "kar", "rmi" }) static
Definition at line 79 of file Audio.Values.cs.
Mobile_Xmf
readonly Audio Juniper.MediaType.Audio.Mobile_Xmf = new Audio("mobile-xmf") static
Definition at line 80 of file Audio.Values.cs.
Mp4
readonly Audio Juniper.MediaType.Audio.Mp4 = new Audio("mp4", new string[] { "m4a", "mp4a" }) static
Definition at line 81 of file Audio.Values.cs.
MP4A_LATM
readonly Audio Juniper.MediaType.Audio.MP4A_LATM = new Audio("mp4a-latm") static
Definition at line 82 of file Audio.Values.cs.
MPA
readonly Audio Juniper.MediaType.Audio.MPA = new Audio("mpa") static
Definition at line 83 of file Audio.Values.cs.
Mpa_Robust
readonly Audio Juniper.MediaType.Audio.Mpa_Robust = new Audio("mpa-robust") static
Definition at line 84 of file Audio.Values.cs.
Mpeg
readonly Audio Juniper.MediaType.Audio.Mpeg = new Audio("mpeg", new string[] { "mp3", "mp2", "mp2a", "mpga", "m2a", "m3a" }) static
Definition at line 85 of file Audio.Values.cs.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream().
Mpeg4_Generic
readonly Audio Juniper.MediaType.Audio.Mpeg4_Generic = new Audio("mpeg4-generic") static
Definition at line 86 of file Audio.Values.cs.
Musepack
readonly Audio Juniper.MediaType.Audio.Musepack = new Audio("musepack") static
Definition at line 87 of file Audio.Values.cs.
Ogg
readonly Audio Juniper.MediaType.Audio.Ogg = new Audio("ogg", new string[] { "ogg", "oga", "spx" }) static
Definition at line 88 of file Audio.Values.cs.
Opus
readonly Audio Juniper.MediaType.Audio.Opus = new Audio("opus") static
Definition at line 89 of file Audio.Values.cs.
Parityfec
readonly Audio Juniper.MediaType.Audio.Parityfec = new Audio("parityfec") static
Definition at line 90 of file Audio.Values.cs.
PCMA
readonly Audio Juniper.MediaType.Audio.PCMA = new Audio("pcma") static
Definition at line 91 of file Audio.Values.cs.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.MakeAudioFormat(), and Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream().
PCMA_WB
readonly Audio Juniper.MediaType.Audio.PCMA_WB = new Audio("pcma-wb") static
Definition at line 92 of file Audio.Values.cs.
PCMU
readonly Audio Juniper.MediaType.Audio.PCMU = new Audio("pcmu") static
Definition at line 93 of file Audio.Values.cs.
PCMU_WB
readonly Audio Juniper.MediaType.Audio.PCMU_WB = new Audio("pcmu-wb") static
Definition at line 94 of file Audio.Values.cs.
PrsSid
readonly Audio Juniper.MediaType.Audio.PrsSid = new Audio("prs.sid") static
Definition at line 95 of file Audio.Values.cs.
Qcelp
readonly Audio Juniper.MediaType.Audio.Qcelp = new Audio("qcelp") static
Definition at line 96 of file Audio.Values.cs.
Raptorfec
readonly Audio Juniper.MediaType.Audio.Raptorfec = new Audio("raptorfec") static
Definition at line 97 of file Audio.Values.cs.
RED
readonly Audio Juniper.MediaType.Audio.RED = new Audio("red") static
Definition at line 98 of file Audio.Values.cs.
Rtp_Enc_Aescm128
readonly Audio Juniper.MediaType.Audio.Rtp_Enc_Aescm128 = new Audio("rtp-enc-aescm128") static
Definition at line 99 of file Audio.Values.cs.
Rtp_Midi
readonly Audio Juniper.MediaType.Audio.Rtp_Midi = new Audio("rtp-midi") static
Definition at line 100 of file Audio.Values.cs.
Rtploopback
readonly Audio Juniper.MediaType.Audio.Rtploopback = new Audio("rtploopback") static
Definition at line 101 of file Audio.Values.cs.
Rtx
readonly Audio Juniper.MediaType.Audio.Rtx = new Audio("rtx") static
Definition at line 102 of file Audio.Values.cs.
S3m
readonly Audio Juniper.MediaType.Audio.S3m = new Audio("s3m", new string[] { "s3m" }) static
Definition at line 103 of file Audio.Values.cs.
Silk
readonly Audio Juniper.MediaType.Audio.Silk = new Audio("silk", new string[] { "sil" }) static
Definition at line 104 of file Audio.Values.cs.
SMV
readonly Audio Juniper.MediaType.Audio.SMV = new Audio("smv") static
Definition at line 105 of file Audio.Values.cs.
SMV0
readonly Audio Juniper.MediaType.Audio.SMV0 = new Audio("smv0") static
Definition at line 107 of file Audio.Values.cs.
SMV_QCP
readonly Audio Juniper.MediaType.Audio.SMV_QCP = new Audio("smv-qcp") static
Definition at line 106 of file Audio.Values.cs.
Sp_Midi
readonly Audio Juniper.MediaType.Audio.Sp_Midi = new Audio("sp-midi") static
Definition at line 108 of file Audio.Values.cs.
Speex
readonly Audio Juniper.MediaType.Audio.Speex = new Audio("speex") static
Definition at line 109 of file Audio.Values.cs.
T140c
readonly Audio Juniper.MediaType.Audio.T140c = new Audio("t140c") static
Definition at line 110 of file Audio.Values.cs.
T38
readonly Audio Juniper.MediaType.Audio.T38 = new Audio("t38") static
Definition at line 111 of file Audio.Values.cs.
Telephone_Event
readonly Audio Juniper.MediaType.Audio.Telephone_Event = new Audio("telephone-event") static
Definition at line 112 of file Audio.Values.cs.
TETRA_ACELP
readonly Audio Juniper.MediaType.Audio.TETRA_ACELP = new Audio("tetra_acelp") static
Definition at line 113 of file Audio.Values.cs.
TETRA_ACELP_BB
readonly Audio Juniper.MediaType.Audio.TETRA_ACELP_BB = new Audio("tetra_acelp_bb") static
Definition at line 114 of file Audio.Values.cs.
Tone
readonly Audio Juniper.MediaType.Audio.Tone = new Audio("tone") static
Definition at line 115 of file Audio.Values.cs.
UEMCLIP
readonly Audio Juniper.MediaType.Audio.UEMCLIP = new Audio("uemclip") static
Definition at line 116 of file Audio.Values.cs.
Ulpfec
readonly Audio Juniper.MediaType.Audio.Ulpfec = new Audio("ulpfec") static
Definition at line 117 of file Audio.Values.cs.
Usac
readonly Audio Juniper.MediaType.Audio.Usac = new Audio("usac") static
Definition at line 118 of file Audio.Values.cs.
Values
new readonly Audio [] Juniper.MediaType.Audio.Values static
Definition at line 185 of file Audio.Values.cs.
Referenced by Juniper.MediaType.Audio.Matches().
VDVI
readonly Audio Juniper.MediaType.Audio.VDVI = new Audio("vdvi") static
Definition at line 119 of file Audio.Values.cs.
Vendor1d_Interleaved_Parityfec
readonly Audio Juniper.MediaType.Audio.Vendor1d_Interleaved_Parityfec = new Audio("1d-interleaved-parityfec") static
Definition at line 120 of file Audio.Values.cs.
Vendor32kadpcm
readonly Audio Juniper.MediaType.Audio.Vendor32kadpcm = new Audio("32kadpcm") static
Definition at line 121 of file Audio.Values.cs.
Vendor3gpp
readonly Audio Juniper.MediaType.Audio.Vendor3gpp = new Audio("3gpp") static
Definition at line 122 of file Audio.Values.cs.
Vendor3gpp2
readonly Audio Juniper.MediaType.Audio.Vendor3gpp2 = new Audio("3gpp2") static
Definition at line 123 of file Audio.Values.cs.
Vendor3gppIufp
readonly Audio Juniper.MediaType.Audio.Vendor3gppIufp = new Audio("vnd.3gpp.iufp") static
Definition at line 124 of file Audio.Values.cs.
Vendor4SB
readonly Audio Juniper.MediaType.Audio.Vendor4SB = new Audio("vnd.4sb") static
Definition at line 125 of file Audio.Values.cs.
VendorAudiokoz
readonly Audio Juniper.MediaType.Audio.VendorAudiokoz = new Audio("vnd.audiokoz") static
Definition at line 126 of file Audio.Values.cs.
VendorCELP
readonly Audio Juniper.MediaType.Audio.VendorCELP = new Audio("vnd.celp") static
Definition at line 127 of file Audio.Values.cs.
VendorCiscoNse
readonly Audio Juniper.MediaType.Audio.VendorCiscoNse = new Audio("vnd.cisco.nse") static
Definition at line 128 of file Audio.Values.cs.
VendorCmlesRadio_Events
readonly Audio Juniper.MediaType.Audio.VendorCmlesRadio_Events = new Audio("vnd.cmles.radio-events") static
Definition at line 129 of file Audio.Values.cs.
VendorCnsAnp1
readonly Audio Juniper.MediaType.Audio.VendorCnsAnp1 = new Audio("vnd.cns.anp1") static
Definition at line 130 of file Audio.Values.cs.
VendorCnsInf1
readonly Audio Juniper.MediaType.Audio.VendorCnsInf1 = new Audio("vnd.cns.inf1") static
Definition at line 131 of file Audio.Values.cs.
VendorDeceAudio
readonly Audio Juniper.MediaType.Audio.VendorDeceAudio = new Audio("vnd.dece.audio", new string[] { "uva", "uvva" }) static
Definition at line 132 of file Audio.Values.cs.
VendorDigital_Winds
readonly Audio Juniper.MediaType.Audio.VendorDigital_Winds = new Audio("vnd.digital-winds", new string[] { "eol" }) static
Definition at line 133 of file Audio.Values.cs.
VendorDlnaAdts
readonly Audio Juniper.MediaType.Audio.VendorDlnaAdts = new Audio("vnd.dlna.adts") static
Definition at line 134 of file Audio.Values.cs.
VendorDolbyHeaac1
readonly Audio Juniper.MediaType.Audio.VendorDolbyHeaac1 = new Audio("vnd.dolby.heaac.1") static
Definition at line 135 of file Audio.Values.cs.
VendorDolbyHeaac2
readonly Audio Juniper.MediaType.Audio.VendorDolbyHeaac2 = new Audio("vnd.dolby.heaac.2") static
Definition at line 136 of file Audio.Values.cs.
VendorDolbyMlp
readonly Audio Juniper.MediaType.Audio.VendorDolbyMlp = new Audio("vnd.dolby.mlp") static
Definition at line 137 of file Audio.Values.cs.
VendorDolbyMps
readonly Audio Juniper.MediaType.Audio.VendorDolbyMps = new Audio("vnd.dolby.mps") static
Definition at line 138 of file Audio.Values.cs.
VendorDolbyPl2
readonly Audio Juniper.MediaType.Audio.VendorDolbyPl2 = new Audio("vnd.dolby.pl2") static
Definition at line 139 of file Audio.Values.cs.
VendorDolbyPl2x
readonly Audio Juniper.MediaType.Audio.VendorDolbyPl2x = new Audio("vnd.dolby.pl2x") static
Definition at line 140 of file Audio.Values.cs.
VendorDolbyPl2z
readonly Audio Juniper.MediaType.Audio.VendorDolbyPl2z = new Audio("vnd.dolby.pl2z") static
Definition at line 141 of file Audio.Values.cs.
VendorDolbyPulse1
readonly Audio Juniper.MediaType.Audio.VendorDolbyPulse1 = new Audio("vnd.dolby.pulse.1") static
Definition at line 142 of file Audio.Values.cs.
VendorDra
readonly Audio Juniper.MediaType.Audio.VendorDra = new Audio("vnd.dra", new string[] { "dra" }) static
Definition at line 143 of file Audio.Values.cs.
VendorDts
readonly Audio Juniper.MediaType.Audio.VendorDts = new Audio("vnd.dts", new string[] { "dts" }) static
Definition at line 144 of file Audio.Values.cs.
VendorDtsHd
readonly Audio Juniper.MediaType.Audio.VendorDtsHd = new Audio("vnd.dts.hd", new string[] { "dtshd" }) static
Definition at line 145 of file Audio.Values.cs.
VendorDtsUhd
readonly Audio Juniper.MediaType.Audio.VendorDtsUhd = new Audio("vnd.dts.uhd") static
Definition at line 146 of file Audio.Values.cs.
VendorDvbFile
readonly Audio Juniper.MediaType.Audio.VendorDvbFile = new Audio("vnd.dvb.file") static
Definition at line 147 of file Audio.Values.cs.
VendorEveradPlj
readonly Audio Juniper.MediaType.Audio.VendorEveradPlj = new Audio("vnd.everad.plj") static
Definition at line 148 of file Audio.Values.cs.
VendorHnsAudio
readonly Audio Juniper.MediaType.Audio.VendorHnsAudio = new Audio("vnd.hns.audio") static
Definition at line 149 of file Audio.Values.cs.
VendorLucentVoice
readonly Audio Juniper.MediaType.Audio.VendorLucentVoice = new Audio("vnd.lucent.voice", new string[] { "lvp" }) static
Definition at line 150 of file Audio.Values.cs.
VendorMs_PlayreadyMediaPya
readonly Audio Juniper.MediaType.Audio.VendorMs_PlayreadyMediaPya = new Audio("vnd.ms-playready.media.pya", new string[] { "pya" }) static
Definition at line 151 of file Audio.Values.cs.
VendorNokiaMobile_Xmf
readonly Audio Juniper.MediaType.Audio.VendorNokiaMobile_Xmf = new Audio("vnd.nokia.mobile-xmf") static
Definition at line 152 of file Audio.Values.cs.
VendorNortelVbk
readonly Audio Juniper.MediaType.Audio.VendorNortelVbk = new Audio("vnd.nortel.vbk") static
Definition at line 153 of file Audio.Values.cs.
VendorNueraEcelp4800
readonly Audio Juniper.MediaType.Audio.VendorNueraEcelp4800 = new Audio("vnd.nuera.ecelp4800", new string[] { "ecelp4800" }) static
Definition at line 154 of file Audio.Values.cs.
VendorNueraEcelp7470
readonly Audio Juniper.MediaType.Audio.VendorNueraEcelp7470 = new Audio("vnd.nuera.ecelp7470", new string[] { "ecelp7470" }) static
Definition at line 155 of file Audio.Values.cs.
VendorNueraEcelp9600
readonly Audio Juniper.MediaType.Audio.VendorNueraEcelp9600 = new Audio("vnd.nuera.ecelp9600", new string[] { "ecelp9600" }) static
Definition at line 156 of file Audio.Values.cs.
VendorOctelSbc
readonly Audio Juniper.MediaType.Audio.VendorOctelSbc = new Audio("vnd.octel.sbc") static
Definition at line 157 of file Audio.Values.cs.
VendorPresonusMultitrack
readonly Audio Juniper.MediaType.Audio.VendorPresonusMultitrack = new Audio("vnd.presonus.multitrack") static
Definition at line 158 of file Audio.Values.cs.
VendorQcelp
readonly Audio Juniper.MediaType.Audio.VendorQcelp = new Audio("vnd.qcelp") static
Definition at line 161 of file Audio.Values.cs.
VendorRhetorex32kadpcm
readonly Audio Juniper.MediaType.Audio.VendorRhetorex32kadpcm = new Audio("vnd.rhetorex.32kadpcm") static
Definition at line 163 of file Audio.Values.cs.
VendorRip
readonly Audio Juniper.MediaType.Audio.VendorRip = new Audio("vnd.rip", new string[] { "rip" }) static
Definition at line 164 of file Audio.Values.cs.
VendorSealedmediaSoftsealMpeg
readonly Audio Juniper.MediaType.Audio.VendorSealedmediaSoftsealMpeg = new Audio("vnd.sealedmedia.softseal.mpeg") static
Definition at line 165 of file Audio.Values.cs.
VendorVmxCvsd
readonly Audio Juniper.MediaType.Audio.VendorVmxCvsd = new Audio("vnd.vmx.cvsd") static
Definition at line 166 of file Audio.Values.cs.
VMR_WB
readonly Audio Juniper.MediaType.Audio.VMR_WB = new Audio("vmr-wb") static
Definition at line 167 of file Audio.Values.cs.
Vorbis
readonly Audio Juniper.MediaType.Audio.Vorbis = new Audio("vorbis") static
Definition at line 168 of file Audio.Values.cs.
Vorbis_Config
readonly Audio Juniper.MediaType.Audio.Vorbis_Config = new Audio("vorbis-config") static
Definition at line 169 of file Audio.Values.cs.
Webm
readonly Audio Juniper.MediaType.Audio.Webm = new Audio("webm", new string[] { "weba" }) static
Definition at line 170 of file Audio.Values.cs.
X_Aac
readonly Audio Juniper.MediaType.Audio.X_Aac = new Audio("x-aac", new string[] { "aac" }) static
Definition at line 171 of file Audio.Values.cs.
X_Aiff
readonly Audio Juniper.MediaType.Audio.X_Aiff = new Audio("x-aiff", new string[] { "aif", "aiff", "aifc" }) static
Definition at line 172 of file Audio.Values.cs.
X_Caf
readonly Audio Juniper.MediaType.Audio.X_Caf = new Audio("x-caf", new string[] { "caf" }) static
Definition at line 173 of file Audio.Values.cs.
X_Flac
readonly Audio Juniper.MediaType.Audio.X_Flac = new Audio("x-flac", new string[] { "flac" }) static
Definition at line 174 of file Audio.Values.cs.
X_Matroska
readonly Audio Juniper.MediaType.Audio.X_Matroska = new Audio("x-matroska", new string[] { "mka" }) static
Definition at line 175 of file Audio.Values.cs.
X_Mpegurl
readonly Audio Juniper.MediaType.Audio.X_Mpegurl = new Audio("x-mpegurl", new string[] { "m3u" }) static
Definition at line 176 of file Audio.Values.cs.
X_Ms_Wax
readonly Audio Juniper.MediaType.Audio.X_Ms_Wax = new Audio("x-ms-wax", new string[] { "wax" }) static
Definition at line 177 of file Audio.Values.cs.
X_Ms_Wma
readonly Audio Juniper.MediaType.Audio.X_Ms_Wma = new Audio("x-ms-wma", new string[] { "wma" }) static
Definition at line 178 of file Audio.Values.cs.
X_Pn_Realaudio
readonly Audio Juniper.MediaType.Audio.X_Pn_Realaudio = new Audio("x-pn-realaudio", new string[] { "ram", "ra" }) static
Definition at line 179 of file Audio.Values.cs.
X_Pn_Realaudio_Plugin
readonly Audio Juniper.MediaType.Audio.X_Pn_Realaudio_Plugin = new Audio("x-pn-realaudio-plugin", new string[] { "rmp" }) static
Definition at line 180 of file Audio.Values.cs.
X_Tta
readonly Audio Juniper.MediaType.Audio.X_Tta = new Audio("x-tta") static
Definition at line 181 of file Audio.Values.cs.
X_Wav
readonly Audio Juniper.MediaType.Audio.X_Wav = new Audio("x-wav", new string[] { "wav" }) static
Definition at line 182 of file Audio.Values.cs.
Referenced by Juniper.Sound.NAudioAudioDataDecoder.MakeDecodingStream().
Xm
readonly Audio Juniper.MediaType.Audio.Xm = new Audio("xm", new string[] { "xm" }) static
Definition at line 183 of file Audio.Values.cs.
Property Documentation
Extensions
ReadOnlyCollection<string> Juniper.MediaType.Extensions get inherited
Definition at line 211 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.UpdateLookupTables().
PrimaryExtension
string Juniper.MediaType.PrimaryExtension get inherited
Definition at line 213 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
SubTypeName
string Juniper.MediaType.SubTypeName get inherited
Definition at line 207 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
TypeName
string Juniper.MediaType.TypeName get inherited
Definition at line 205 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
Value
string Juniper.MediaType.Value get inherited
Definition at line 203 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.MediaType(), Juniper.MediaType.ToString(), and Juniper.MediaType.UpdateLookupTables().
Weight
float Juniper.MediaType.Weight get inherited
Definition at line 209 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.ToString().
The documentation for this class was generated from the following files:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Audio.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Audio.Values.cs