Juniper: Juniper.Imaging.IImageProcessor< T > Interface Template Reference
Juniper.Imaging.IImageProcessor< T > Interface Template Reference
Public Member Functions
int GetWidth (T img)
int GetHeight (T img)
int GetComponents (T img)
T Concatenate (T[,] images, IProgress prog=null)
Detailed Description
Definition at line 6 of file IImageProcessor.cs.
Member Function Documentation
Concatenate()
T Juniper.Imaging.IImageProcessor< T >.Concatenate (T images[,], IProgress prog = null)
Referenced by Juniper.Imaging.IImageProcessorExt.ConcatenateAsync< T >().
GetComponents()
int Juniper.Imaging.IImageProcessor< T >.GetComponents (T img)
Referenced by Juniper.Imaging.IImageProcessorExt.ValidateImages< T >().
GetHeight()
int Juniper.Imaging.IImageProcessor< T >.GetHeight (T img)
Referenced by Juniper.Imaging.IImageProcessorExt.ValidateImages< T >().
GetWidth()
int Juniper.Imaging.IImageProcessor< T >.GetWidth (T img)
Referenced by Juniper.Imaging.IImageProcessorExt.ValidateImages< T >().
The documentation for this interface was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Imaging/IImageProcessor.cs