Juniper: Juniper.XR.XRSystem Class Reference
Juniper.XR.XRSystem Class Reference
Public Member Functions
void Awake ()
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
void Reset ()
void Install ()
void Uninstall ()
void OnValidate ()
void SetDisplayType (int type)
Converts the type number to a TrackingType enumeration value and switches the runtime subsystem.
void Update ()
Determines which XR Subsystem needs to be started for the current set of configuration parameters.
Static Public Member Functions
static void Ensure ()
Public Attributes
PlatformTypes Platform
PlatformExtensionTypes [] Extensions
DisplayTypes DisplayType
AugmentedRealityTypes ARType
Static Public Attributes
static PlatformTypes CurrentPlatform
Private Member Functions
bool StartDisplay ()
void RequestPermissions ()
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Static Private Member Functions
static bool StartXRDevice (string xrDeviceName)
Starts up one of Unity's XR platforms.
Private Attributes
DisplayTypes lastDisplayType
AugmentedRealityTypes lastARType
Detailed Description
Definition at line 20 of file XRSystem.cs.
Member Function Documentation
Awake()
void Juniper.XR.XRSystem.Awake () inline
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
Definition at line 200 of file XRSystem.cs.
         {
             var scenes = this.FindAny<MasterSceneController>();
             if (scenes != null && scenes.gameObject.scene != gameObject.scene)
             {
                 gameObject.Destroy();
             }
             else
             {
                 Install();
 #if UNITY_MODULES_AUDIO
                 r2.AudioSourceNeeded += CreateNewAudioSource;
 #endif
                 if (Application.isPlaying)
                 {
                     RequestPermissions();
                 }
             }
         }
References Juniper.XR.XRSystem.Install(), and Juniper.XR.XRSystem.RequestPermissions().
Ensure()
static void Juniper.XR.XRSystem.Ensure () inline static
Definition at line 172 of file XRSystem.cs.
         {
             var camT = CameraExtensions.MainCamera.transform;
             var stage = camT.parent;
             if (stage == null)
             {
                 stage = new GameObject().transform;
                 camT.Reparent(stage);
             }
             var userRig = stage.parent;
             if (userRig == null)
             {
                 userRig = new GameObject().transform;
                 stage.Reparent(userRig);
             }
             userRig.EnsureComponent<XRSystem>();
         }
References Juniper.CameraExtensions.MainCamera.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Install().
Install()
void Juniper.XR.XRSystem.Install () inline
Implements Juniper.IInstallable.
Definition at line 225 of file XRSystem.cs.
         {
 #if UNITY_MODULES_AUDIO
             r2 = this.EnsureComponent<InteractionAudio>();
 #endif
             this.EnsureComponent<AnchorStore>();
             this.EnsureComponent<EventSystem>();
             CameraExtensions.MainCamera.transform.parent.EnsureComponent<StageExtensions>();
             CameraExtensions.MainCamera.EnsureComponent<CameraExtensions>();
             this.EnsureComponent<UnifiedInputModule>();
         }
References Juniper.CameraExtensions.MainCamera.
Referenced by Juniper.XR.XRSystem.Awake().
OnValidate()
void Juniper.XR.XRSystem.OnValidate ()
RequestPermissions()
void Juniper.XR.XRSystem.RequestPermissions () inline private
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Definition at line 256 of file XRSystem.cs.
         {
 #if UNITY_IOS
             var auth = UserAuthorization.WebCam;
             var speech = this.FindAny<Input.Speech.KeywordRecognizer>();
             if (speech != null && speech.IsAvailable)
             {
                 auth |= UserAuthorization.Microphone;
             }
             Application.RequestUserAuthorization(auth);
 #endif
         }
Referenced by Juniper.XR.XRSystem.Awake().
Reset()
void Juniper.XR.XRSystem.Reset ()
SetDisplayType()
void Juniper.XR.XRSystem.SetDisplayType (int type)
Converts the type number to a TrackingType enumeration value and switches the runtime subsystem.
Parameters
type Type.
StartDisplay()
bool Juniper.XR.XRSystem.StartDisplay () inline private
Definition at line 128 of file XRSystem.cs.
         {
             if (DisplayType == DisplayTypes.AudioOnly
                 || DisplayType == DisplayTypes.Monoscopic
                 || CurrentPlatform == PlatformTypes.AndroidViveFocus)
             {
                 return StartXRDevice("None");
             }
             else if (CurrentPlatform == PlatformTypes.Android
                 || CurrentPlatform == PlatformTypes.AndroidARCore
                 || CurrentPlatform == PlatformTypes.IOS
                 || CurrentPlatform == PlatformTypes.IOSARKit
                 || CurrentPlatform == PlatformTypes.UWP)
             {
                 return StartXRDevice("cardboard");
             }
             else if (CurrentPlatform == PlatformTypes.AndroidDaydream)
             {
                 return StartXRDevice("daydream");
             }
             else if (CurrentPlatform == PlatformTypes.AndroidOculus
                 || CurrentPlatform == PlatformTypes.StandaloneOculus)
             {
                 return StartXRDevice("oculus");
             }
             else if (CurrentPlatform == PlatformTypes.UWPHoloLens
                 || CurrentPlatform == PlatformTypes.UWPWindowsMR)
             {
                 return StartXRDevice("windowsmr");
             }
             else if (CurrentPlatform == PlatformTypes.MagicLeap)
             {
                 return StartXRDevice("lumin");
             }
             else if (CurrentPlatform == PlatformTypes.StandaloneSteamVR)
             {
                 return StartXRDevice("openvr");
             }
             else
             {
                 return false;
             }
         }
References Juniper.XR.XRSystem.CurrentPlatform, Juniper.XR.XRSystem.DisplayType, and Juniper.XR.XRSystem.StartXRDevice().
Referenced by Juniper.XR.XRSystem.Update().
StartXRDevice()
static bool Juniper.XR.XRSystem.StartXRDevice (string xrDeviceName) inline static private
Starts up one of Unity's XR platforms.
Parameters
xrDeviceName Xr device name.
Definition at line 101 of file XRSystem.cs.
         {
 #if UNITY_MODULES_XR
             if (XRSettings.loadedDeviceName == xrDeviceName)
             {
                 return true;
             }
             else if (XRSettings.supportedDevices.Contains(xrDeviceName))
             {
                 XRSettings.LoadDeviceByName(xrDeviceName);
                 return true;
             }
             else
             {
                 Debug.LogErrorFormat(
                     "XR Device '{0}' is not available. Current is '{1}'. Available are '{2}'.",
                     xrDeviceName,
                     XRSettings.loadedDeviceName,
                     string.Join(", ", XRSettings.supportedDevices));
                 return false;
             }
 #else
             return false;
 #endif
         }
References Juniper.XR.Debug.
Referenced by Juniper.XR.XRSystem.StartDisplay().
Uninstall()
void Juniper.XR.XRSystem.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 239 of file XRSystem.cs.
 { }
Update()
void Juniper.XR.XRSystem.Update () inline
Determines which XR Subsystem needs to be started for the current set of configuration parameters.
Definition at line 283 of file XRSystem.cs.
         {
             if (DisplayType != lastDisplayType)
             {
                 string errorMessage = null;
                 try
                 {
                     if (!StartDisplay())
                     {
                         errorMessage = "Unsupported platform";
                     }
                 }
                 catch (Exception exp)
                 {
                     errorMessage = exp.Message;
                 }
                 if (string.IsNullOrEmpty(errorMessage))
                 {
                     lastDisplayType = DisplayType;
                 }
                 else
                 {
                     Debug.LogErrorFormat("Could not change display type. Reason: {0}", errorMessage);
                     DisplayType = lastDisplayType;
                 }
             }
             if (CurrentPlatform == PlatformTypes.MagicLeap
                || CurrentPlatform == PlatformTypes.UWPHoloLens)
             {
                 ARType = AugmentedRealityTypes.Holographic;
             }
             else if (CurrentPlatform == PlatformTypes.AndroidARCore
                 || CurrentPlatform == PlatformTypes.IOSARKit
                 || (ARType == AugmentedRealityTypes.Holographic
                     && (CurrentPlatform == PlatformTypes.Android
                         || CurrentPlatform == PlatformTypes.AndroidDaydream
                         || CurrentPlatform == PlatformTypes.AndroidViveFocus
                         || CurrentPlatform == PlatformTypes.IOS
                         || CurrentPlatform == PlatformTypes.Standalone
                         || CurrentPlatform == PlatformTypes.StandaloneSteamVR
                         || CurrentPlatform == PlatformTypes.UWP
                         || CurrentPlatform == PlatformTypes.UWPWindowsMR)))
             {
                 ARType = AugmentedRealityTypes.PassthroughCamera;
             }
             else if (CurrentPlatform == PlatformTypes.AndroidOculus
                 || CurrentPlatform == PlatformTypes.StandaloneOculus)
             {
                 ARType = AugmentedRealityTypes.None;
             }
             if (ARType != lastARType)
             {
                 lastARType = ARType;
             }
         }
References Juniper.XR.XRSystem.ARType, Juniper.XR.XRSystem.CurrentPlatform, Juniper.XR.Debug, Juniper.XR.XRSystem.DisplayType, Juniper.XR.XRSystem.lastARType, Juniper.XR.XRSystem.lastDisplayType, and Juniper.XR.XRSystem.StartDisplay().
Member Data Documentation
ARType
AugmentedRealityTypes Juniper.XR.XRSystem.ARType
Initial value:
=
            AugmentedRealityTypes.Holographic
Definition at line 80 of file XRSystem.cs.
Referenced by Juniper.XR.XRSystem.Update().
CurrentPlatform
PlatformTypes Juniper.XR.XRSystem.CurrentPlatform static
Initial value:
=>
            PlatformTypes.MagicLeap
Definition at line 22 of file XRSystem.cs.
Referenced by Juniper.XR.XRSystem.StartDisplay(), and Juniper.XR.XRSystem.Update().
DisplayType
DisplayTypes Juniper.XR.XRSystem.DisplayType
Initial value:
=
            DisplayTypes.Stereo
Definition at line 69 of file XRSystem.cs.
Referenced by Juniper.XR.XRSystem.StartDisplay(), and Juniper.XR.XRSystem.Update().
Extensions
PlatformExtensionTypes [] Juniper.XR.XRSystem.Extensions
Definition at line 67 of file XRSystem.cs.
lastARType
AugmentedRealityTypes Juniper.XR.XRSystem.lastARType private
Definition at line 91 of file XRSystem.cs.
Referenced by Juniper.XR.XRSystem.Update().
lastDisplayType
DisplayTypes Juniper.XR.XRSystem.lastDisplayType private
Definition at line 78 of file XRSystem.cs.
Referenced by Juniper.XR.XRSystem.Update().
Platform
PlatformTypes Juniper.XR.XRSystem.Platform
Definition at line 64 of file XRSystem.cs.
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/XR/XRSystem.cs