Juniper: Hjg.Pngcs.ImageLine Class Reference
Hjg.Pngcs.ImageLine Class Reference
Lightweight wrapper for an image scanline, for read and write
Public Types
enum ESampleType { ESampleType.INT, ESampleType.BYTE }
Public Member Functions
ImageLine (ImageInfo imgInfo)
ImageLine (ImageInfo imgInfo, ESampleType stype)
ImageLine (ImageInfo imgInfo, ESampleType stype, bool unpackedMode)
Constructs an ImageLine
ImageLine UnpackToNewImageLine ()
ImageLine PackToNewImageLine ()
int [] GetScanlineInt ()
byte [] GetScanlineByte ()
bool IsInt ()
bool IsByte ()
override string ToString ()
Properties
ImageInfo ImgInfo [get]
ImageInfo (readonly inmutable)
int [] Scanline [get]
Samples of an image line
byte [] ScanlineB [get]
Same as Scanline, but with one byte per sample. Only one of Scanline and ScanlineB is valid - this depends on SampleType}
int Rown [get, set]
tracks the current row number (from 0 to rows-1)
int ElementsPerRow [get]
Hown many elements has the scanline array =imgInfo.samplePerRowPacked, if packed, imgInfo.samplePerRow elsewhere
int MaxSampleVal [get]
Maximum sample value that this line admits: typically 255; less if bitdepth less than 8, 65535 if 16bits
ESampleType SampleType [get]
Determines if samples are stored in integers or in bytes
bool SamplesUnpacked [get]
True: each scanline element is a sample. False: each scanline element has severals samples packed in a byte
FilterType FilterUsed [get, set]
informational only ; filled by the reader
Private Member Functions
internal ImageLine (ImageInfo imgInfo, ESampleType stype, bool unpackedMode, int[] sci, byte[] scb)
internal void SetScanLine (int[] b)
Makes a deep copy
internal int [] GetScanLineCopy (int[] b)
Makes a deep copy
Static Private Member Functions
static internal void UnpackInplaceInt (ImageInfo iminfo, int[] src, int[] dst, bool Scale)
static internal void PackInplaceInt (ImageInfo iminfo, int[] src, int[] dst, bool scaled)
static internal void UnpackInplaceByte (ImageInfo iminfo, byte[] src, byte[] dst, bool scale)
static internal void PackInplaceByte (ImageInfo iminfo, byte[] src, byte[] dst, bool scaled)
static internal int GetMaskForPackedFormats (int bitDepth)
static internal int GetMaskForPackedFormatsLs (int bitDepth)
Private Attributes
internal readonly int channels
internal readonly int bitDepth
Detailed Description
Lightweight wrapper for an image scanline, for read and write
It can be (usually it is) reused while iterating over the image lines See scanline field doc, to understand the format. /remarks>
Definition at line 9 of file ImageLine.cs.
Member Enumeration Documentation
ESampleType
enum Hjg.Pngcs.ImageLine.ESampleType strong
Enumerator
INT
BYTE
Definition at line 64 of file ImageLine.cs.
         {
             INT, // 4 bytes per sample
             BYTE // 1 byte per sample
         }
Constructor & Destructor Documentation
ImageLine() [1/4]
Hjg.Pngcs.ImageLine.ImageLine (ImageInfo imgInfo) inline
Definition at line 86 of file ImageLine.cs.
             : this(imgInfo, ESampleType.INT, false)
         {
         }
Referenced by Hjg.Pngcs.ImageLine.PackToNewImageLine(), and Hjg.Pngcs.ImageLine.UnpackToNewImageLine().
ImageLine() [2/4]
Hjg.Pngcs.ImageLine.ImageLine (ImageInfo imgInfo, ESampleType stype) inline
Definition at line 91 of file ImageLine.cs.
             : this(imgInfo, stype, false)
         {
         }
ImageLine() [3/4]
Hjg.Pngcs.ImageLine.ImageLine (ImageInfo imgInfo, ESampleType stype, bool unpackedMode) inline
Constructs an ImageLine
Parameters
imgInfo Inmutable copy of PNG ImageInfo
stype Storage for samples:INT (default) or BYTE
unpackedMode If true and bitdepth less than 8, samples are unpacked. This has no effect if biddepth 8 or 16
Definition at line 102 of file ImageLine.cs.
             : this(imgInfo, stype, unpackedMode, null, null)
         {
         }
ImageLine() [4/4]
internal Hjg.Pngcs.ImageLine.ImageLine (ImageInfo imgInfo, ESampleType stype, bool unpackedMode, int [] sci, byte [] scb) inline private
Definition at line 107 of file ImageLine.cs.
         {
             ImgInfo = imgInfo ?? throw new System.ArgumentNullException(nameof(imgInfo));
             channels = imgInfo.Channels;
             bitDepth = imgInfo.BitDepth;
             FilterUsed = FilterType.FILTER_UNKNOWN;
             SampleType = stype;
             SamplesUnpacked = unpackedMode || !imgInfo.Packed;
             ElementsPerRow = SamplesUnpacked ? imgInfo.SamplesPerRow
                 : imgInfo.SamplesPerRowPacked;
             if (stype == ESampleType.INT)
             {
                 Scanline = sci ?? (new int[ElementsPerRow]);
                 ScanlineB = null;
                 MaxSampleVal = bitDepth == 16 ? 0xFFFF : GetMaskForPackedFormatsLs(bitDepth);
             }
             else if (stype == ESampleType.BYTE)
             {
                 ScanlineB = scb ?? (new byte[ElementsPerRow]);
                 Scanline = null;
                 MaxSampleVal = bitDepth == 16 ? 0xFF : GetMaskForPackedFormatsLs(bitDepth);
             }
             else
             {
                 throw new PngjInternalException("bad ImageLine initialization");
             }
             Rown = -1;
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.ImageLine.bitDepth, Hjg.Pngcs.ImageInfo.Channels, Hjg.Pngcs.ImageLine.channels, Hjg.Pngcs.ImageLine.ElementsPerRow, Hjg.Pngcs.ImageLine.FilterUsed, Hjg.Pngcs.ImageLine.GetMaskForPackedFormatsLs(), Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.MaxSampleVal, Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.ImageLine.Rown, Hjg.Pngcs.ImageInfo.SamplesPerRow, Hjg.Pngcs.ImageInfo.SamplesPerRowPacked, Hjg.Pngcs.ImageLine.SamplesUnpacked, Hjg.Pngcs.ImageLine.SampleType, Hjg.Pngcs.ImageLine.Scanline, and Hjg.Pngcs.ImageLine.ScanlineB.
Member Function Documentation
GetMaskForPackedFormats()
static internal int Hjg.Pngcs.ImageLine.GetMaskForPackedFormats (int bitDepth) inline static private
Definition at line 395 of file ImageLine.cs.
         { // Utility function for pack/unpack
             if (bitDepth == 4)
             {
                 return 0xf0;
             }
             else if (bitDepth == 2)
             {
                 return 0xc0;
             }
             else if (bitDepth == 1)
             {
                 return 0x80;
             }
             else
             {
                 return 0xff;
             }
         }
References Hjg.Pngcs.ImageLine.bitDepth.
GetMaskForPackedFormatsLs()
static internal int Hjg.Pngcs.ImageLine.GetMaskForPackedFormatsLs (int bitDepth) inline static private
Definition at line 415 of file ImageLine.cs.
         { // Utility function for pack/unpack
             if (bitDepth == 4)
             {
                 return 0x0f;
             }
             else if (bitDepth == 2)
             {
                 return 0x03;
             }
             else if (bitDepth == 1)
             {
                 return 0x01;
             }
             else
             {
                 return 0xff;
             }
         }
References Hjg.Pngcs.ImageLine.bitDepth.
Referenced by Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.PackInplaceByte(), Hjg.Pngcs.ImageLine.PackInplaceInt(), Hjg.Pngcs.ImageLine.UnpackInplaceByte(), and Hjg.Pngcs.ImageLine.UnpackInplaceInt().
GetScanlineByte()
byte [] Hjg.Pngcs.ImageLine.GetScanlineByte () inline
Definition at line 374 of file ImageLine.cs.
         {
             return ScanlineB;
         }
References Hjg.Pngcs.ImageLine.ScanlineB.
GetScanLineCopy()
internal int [] Hjg.Pngcs.ImageLine.GetScanLineCopy (int [] b) inline private
Makes a deep copy
You should rarely use this
Parameters
b
Definition at line 328 of file ImageLine.cs.
         {
             if (b is null || b.Length < Scanline.Length)
             {
                 b = new int[Scanline.Length];
             }
             System.Array.Copy(Scanline, 0, b, 0, Scanline.Length);
             return b;
         }
References Hjg.Pngcs.ImageLine.Scanline.
GetScanlineInt()
int [] Hjg.Pngcs.ImageLine.GetScanlineInt () inline
Definition at line 369 of file ImageLine.cs.
         {
             return Scanline;
         }
References Hjg.Pngcs.ImageLine.Scanline.
IsByte()
bool Hjg.Pngcs.ImageLine.IsByte () inline
Definition at line 384 of file ImageLine.cs.
         {
             return SampleType == ESampleType.BYTE;
         }
References Hjg.Pngcs.ImageLine.SampleType.
IsInt()
bool Hjg.Pngcs.ImageLine.IsInt () inline
Definition at line 379 of file ImageLine.cs.
         {
             return SampleType == ESampleType.INT;
         }
References Hjg.Pngcs.ImageLine.SampleType.
Referenced by Hjg.Pngcs.ImageLineHelper.GetPixelToARGB8(), Hjg.Pngcs.ImageLineHelper.ReadDouble(), Hjg.Pngcs.ImageLineHelper.SetPixel(), Hjg.Pngcs.ImageLineHelper.SetPixelFromARGB8(), and Hjg.Pngcs.ImageLineHelper.WriteDouble().
PackInplaceByte()
static internal void Hjg.Pngcs.ImageLine.PackInplaceByte (ImageInfo iminfo, byte [] src, byte [] dst, bool scaled) inline static private
size original: samplesPerRow sizeFinal: samplesPerRowPacked (trailing elements are trash!)
Definition at line 270 of file ImageLine.cs.
         {
             var bitDepth = iminfo.BitDepth;
             if (bitDepth >= 8)
             {
                 return; // nothing to do
             }
             var mask0 = (byte)GetMaskForPackedFormatsLs(bitDepth);
             var scalefactor = (byte)(8 - bitDepth);
             var offset0 = (byte)(8 - bitDepth);
             byte v, v0;
             var offset = 8 - bitDepth;
             v0 = src[0]; // first value is special
             dst[0] = 0;
             if (scaled)
             {
                 v0 >>= scalefactor;
             }
             v0 = (byte)((v0 & mask0) << offset);
             for (int i = 0, j = 0; j < iminfo.SamplesPerRow; j++)
             {
                 v = src[j];
                 if (scaled)
                 {
                     v >>= scalefactor;
                 }
                 dst[i] |= (byte)((v & mask0) << offset);
                 offset -= bitDepth;
                 if (offset < 0)
                 {
                     offset = offset0;
                     i++;
                     dst[i] = 0;
                 }
             }
             dst[0] |= v0;
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.ImageLine.bitDepth, Hjg.Pngcs.ImageLine.GetMaskForPackedFormatsLs(), and Hjg.Pngcs.ImageInfo.SamplesPerRow.
Referenced by Hjg.Pngcs.PngWriter.EncodeRowFromByte(), Hjg.Pngcs.ImageLineHelper.Pack(), and Hjg.Pngcs.ImageLine.PackToNewImageLine().
PackInplaceInt()
static internal void Hjg.Pngcs.ImageLine.PackInplaceInt (ImageInfo iminfo, int [] src, int [] dst, bool scaled) inline static private
Definition at line 181 of file ImageLine.cs.
         {
             var bitDepth = iminfo.BitDepth;
             if (bitDepth >= 8)
             {
                 return; // nothing to do
             }
             var mask0 = GetMaskForPackedFormatsLs(bitDepth);
             var scalefactor = 8 - bitDepth;
             var offset0 = 8 - bitDepth;
             int v, v0;
             var offset = 8 - bitDepth;
             v0 = src[0]; // first value is special for in place
             dst[0] = 0;
             if (scaled)
             {
                 v0 >>= scalefactor;
             }
             v0 = ((v0 & mask0) << offset);
             for (int i = 0, j = 0; j < iminfo.SamplesPerRow; j++)
             {
                 v = src[j];
                 if (scaled)
                 {
                     v >>= scalefactor;
                 }
                 dst[i] |= ((v & mask0) << offset);
                 offset -= bitDepth;
                 if (offset < 0)
                 {
                     offset = offset0;
                     i++;
                     dst[i] = 0;
                 }
             }
             dst[0] |= v0;
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.ImageLine.bitDepth, Hjg.Pngcs.ImageLine.GetMaskForPackedFormatsLs(), and Hjg.Pngcs.ImageInfo.SamplesPerRow.
Referenced by Hjg.Pngcs.PngWriter.EncodeRowFromInt(), Hjg.Pngcs.ImageLineHelper.Pack(), and Hjg.Pngcs.ImageLine.PackToNewImageLine().
PackToNewImageLine()
ImageLine Hjg.Pngcs.ImageLine.PackToNewImageLine () inline
Definition at line 354 of file ImageLine.cs.
         {
             var newline = new ImageLine(ImgInfo, SampleType, false);
             if (SampleType == ESampleType.INT)
             {
                 PackInplaceInt(ImgInfo, Scanline, newline.Scanline, false);
             }
             else
             {
                 PackInplaceByte(ImgInfo, ScanlineB, newline.ScanlineB, false);
             }
             return newline;
         }
References Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.PackInplaceByte(), Hjg.Pngcs.ImageLine.PackInplaceInt(), Hjg.Pngcs.ImageLine.SampleType, Hjg.Pngcs.ImageLine.Scanline, and Hjg.Pngcs.ImageLine.ScanlineB.
SetScanLine()
internal void Hjg.Pngcs.ImageLine.SetScanLine (int [] b) inline private
Makes a deep copy
You should rarely use this
Parameters
b
Definition at line 318 of file ImageLine.cs.
         { // makes copy
             System.Array.Copy(b, 0, Scanline, 0, Scanline.Length);
         }
References Hjg.Pngcs.ImageLine.Scanline.
ToString()
override string Hjg.Pngcs.ImageLine.ToString () inline
Definition at line 389 of file ImageLine.cs.
         {
             return "row=" + Rown + " cols=" + ImgInfo.Cols + " bpc=" + ImgInfo.BitDepth
                     + " size=" + Scanline.Length;
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.ImageInfo.Cols, Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.Rown, and Hjg.Pngcs.ImageLine.Scanline.
UnpackInplaceByte()
static internal void Hjg.Pngcs.ImageLine.UnpackInplaceByte (ImageInfo iminfo, byte [] src, byte [] dst, bool scale) inline static private
Definition at line 224 of file ImageLine.cs.
         {
             var bitDepth = iminfo.BitDepth;
             if (bitDepth >= 8)
             {
                 return; // nothing to do
             }
             var mask0 = GetMaskForPackedFormatsLs(bitDepth);
             var scalefactor = 8 - bitDepth;
             var offset0 = (8 * iminfo.SamplesPerRowPacked) - (bitDepth * iminfo.SamplesPerRow);
             int mask, offset, v;
             if (offset0 != 8)
             {
                 mask = mask0 << offset0;
                 offset = offset0; // how many bits to shift the mask to the right to recover mask0
             }
             else
             {
                 mask = mask0;
                 offset = 0;
             }
             for (int j = iminfo.SamplesPerRow - 1, i = iminfo.SamplesPerRowPacked - 1; j >= 0; j--)
             {
                 v = (src[i] & mask) >> offset;
                 if (scale)
                 {
                     v <<= scalefactor;
                 }
                 dst[j] = (byte)v;
                 mask <<= bitDepth;
                 offset += bitDepth;
                 if (offset == 8)
                 {
                     mask = mask0;
                     offset = 0;
                     i--;
                 }
             }
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.ImageLine.bitDepth, Hjg.Pngcs.ImageLine.GetMaskForPackedFormatsLs(), Hjg.Pngcs.ImageInfo.SamplesPerRow, and Hjg.Pngcs.ImageInfo.SamplesPerRowPacked.
Referenced by Hjg.Pngcs.PngReader.DecodeLastReadRowToByte(), Hjg.Pngcs.ImageLineHelper.Unpack(), and Hjg.Pngcs.ImageLine.UnpackToNewImageLine().
UnpackInplaceInt()
static internal void Hjg.Pngcs.ImageLine.UnpackInplaceInt (ImageInfo iminfo, int [] src, int [] dst, bool Scale) inline static private
Definition at line 137 of file ImageLine.cs.
         {
             var bitDepth = iminfo.BitDepth;
             if (bitDepth >= 8)
             {
                 return; // nothing to do
             }
             var mask0 = GetMaskForPackedFormatsLs(bitDepth);
             var scalefactor = 8 - bitDepth;
             var offset0 = (8 * iminfo.SamplesPerRowPacked) - (bitDepth * iminfo.SamplesPerRow);
             int mask, offset, v;
             if (offset0 != 8)
             {
                 mask = mask0 << offset0;
                 offset = offset0; // how many bits to shift the mask to the right to recover mask0
             }
             else
             {
                 mask = mask0;
                 offset = 0;
             }
             for (int j = iminfo.SamplesPerRow - 1, i = iminfo.SamplesPerRowPacked - 1; j >= 0; j--)
             {
                 v = (src[i] & mask) >> offset;
                 if (Scale)
                 {
                     v <<= scalefactor;
                 }
                 dst[j] = v;
                 mask <<= bitDepth;
                 offset += bitDepth;
                 if (offset == 8)
                 {
                     mask = mask0;
                     offset = 0;
                     i--;
                 }
             }
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.ImageLine.bitDepth, Hjg.Pngcs.ImageLine.GetMaskForPackedFormatsLs(), Hjg.Pngcs.ImageInfo.SamplesPerRow, and Hjg.Pngcs.ImageInfo.SamplesPerRowPacked.
Referenced by Hjg.Pngcs.PngReader.DecodeLastReadRowToInt(), Hjg.Pngcs.ImageLineHelper.Unpack(), and Hjg.Pngcs.ImageLine.UnpackToNewImageLine().
UnpackToNewImageLine()
ImageLine Hjg.Pngcs.ImageLine.UnpackToNewImageLine () inline
Definition at line 339 of file ImageLine.cs.
         {
             var newline = new ImageLine(ImgInfo, SampleType, true);
             if (SampleType == ESampleType.INT)
             {
                 UnpackInplaceInt(ImgInfo, Scanline, newline.Scanline, false);
             }
             else
             {
                 UnpackInplaceByte(ImgInfo, ScanlineB, newline.ScanlineB, false);
             }
             return newline;
         }
References Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.ImgInfo, Hjg.Pngcs.ImageLine.SampleType, Hjg.Pngcs.ImageLine.Scanline, Hjg.Pngcs.ImageLine.ScanlineB, Hjg.Pngcs.ImageLine.UnpackInplaceByte(), and Hjg.Pngcs.ImageLine.UnpackInplaceInt().
Referenced by Hjg.Pngcs.ImageLineHelper.Palette2rgb().
Member Data Documentation
bitDepth
internal readonly int Hjg.Pngcs.ImageLine.bitDepth private
Definition at line 51 of file ImageLine.cs.
Referenced by Hjg.Pngcs.ImageLine.GetMaskForPackedFormats(), Hjg.Pngcs.ImageLine.GetMaskForPackedFormatsLs(), Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.PackInplaceByte(), Hjg.Pngcs.ImageLine.PackInplaceInt(), Hjg.Pngcs.ImageLine.UnpackInplaceByte(), and Hjg.Pngcs.ImageLine.UnpackInplaceInt().
channels
internal readonly int Hjg.Pngcs.ImageLine.channels private
Definition at line 50 of file ImageLine.cs.
Referenced by Hjg.Pngcs.ImageLineHelper.GetPixelToARGB8(), Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLineHelper.SetPixel(), and Hjg.Pngcs.ImageLineHelper.SetPixelFromARGB8().
Property Documentation
ElementsPerRow
int Hjg.Pngcs.ImageLine.ElementsPerRow get
Hown many elements has the scanline array =imgInfo.samplePerRowPacked, if packed, imgInfo.samplePerRow elsewhere
Definition at line 57 of file ImageLine.cs.
 { get; }
Referenced by Hjg.Pngcs.ImageLine.ImageLine().
FilterUsed
FilterType Hjg.Pngcs.ImageLine.FilterUsed get set
informational only ; filled by the reader
Definition at line 84 of file ImageLine.cs.
 { get; set; }
Referenced by Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.PngReader.ReadRowByte(), and Hjg.Pngcs.PngReader.ReadRowInt().
ImgInfo
ImageInfo Hjg.Pngcs.ImageLine.ImgInfo get
ImageInfo (readonly inmutable)
Definition at line 14 of file ImageLine.cs.
 { get; }
Referenced by Hjg.Pngcs.ImageLineHelper.GetPixelToARGB8(), Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.PackToNewImageLine(), Hjg.Pngcs.ImageLineHelper.Palette2rgb(), Hjg.Pngcs.ImageLineHelper.SetPixel(), Hjg.Pngcs.ImageLineHelper.SetPixelFromARGB8(), Hjg.Pngcs.ImageLine.ToString(), and Hjg.Pngcs.ImageLine.UnpackToNewImageLine().
MaxSampleVal
int Hjg.Pngcs.ImageLine.MaxSampleVal get
Maximum sample value that this line admits: typically 255; less if bitdepth less than 8, 65535 if 16bits
Definition at line 62 of file ImageLine.cs.
 { get; }
Referenced by Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLineHelper.ReadDouble(), Hjg.Pngcs.ImageLineHelper.SetPixel(), and Hjg.Pngcs.ImageLineHelper.WriteDouble().
Rown
int Hjg.Pngcs.ImageLine.Rown get set
tracks the current row number (from 0 to rows-1)
Definition at line 48 of file ImageLine.cs.
 { get; set; }
Referenced by Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), and Hjg.Pngcs.ImageLine.ToString().
SamplesUnpacked
bool Hjg.Pngcs.ImageLine.SamplesUnpacked get
True: each scanline element is a sample. False: each scanline element has severals samples packed in a byte
Definition at line 79 of file ImageLine.cs.
 { get; }
Referenced by Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLineHelper.Palette2rgb(), and Hjg.Pngcs.PngWriter.WriteRow().
SampleType
ESampleType Hjg.Pngcs.ImageLine.SampleType get
Determines if samples are stored in integers or in bytes
Definition at line 73 of file ImageLine.cs.
 { get; }
Referenced by Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.IsByte(), Hjg.Pngcs.ImageLine.IsInt(), Hjg.Pngcs.ImageLine.PackToNewImageLine(), Hjg.Pngcs.ImageLineHelper.Palette2rgb(), Hjg.Pngcs.PngReader.ReadRow(), Hjg.Pngcs.ImageLine.UnpackToNewImageLine(), and Hjg.Pngcs.PngWriter.WriteRow().
Scanline
int [] Hjg.Pngcs.ImageLine.Scanline get
Samples of an image line
The 'scanline' is an array of integers, corresponds to an image line (row) Except for 'packed' formats (gray/indexed with 1-2-4 bitdepth) each int is a "sample" (one for channel), (0-255 or 0-65535) in the respective PNG sequence sequence : (R G B R G B...) or (R G B A R G B A...) or (g g g ...) or (i i i) (palette index)
For bitdepth 1/2/4 ,and if samplesUnpacked=false, each value is a PACKED byte! To get an unpacked copy, see Pack() and its inverse Unpack()
To convert a indexed line to RGB balues, see ImageLineHelper.PalIdx2RGB() (cant do the reverse)
Definition at line 37 of file ImageLine.cs.
 { get; }
Referenced by Hjg.Pngcs.ImageLineHelper.GetPixelToARGB8(), Hjg.Pngcs.ImageLine.GetScanLineCopy(), Hjg.Pngcs.ImageLine.GetScanlineInt(), Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.PackToNewImageLine(), Hjg.Pngcs.ImageLineHelper.Palette2rgb(), Hjg.Pngcs.ImageLineHelper.ReadDouble(), Hjg.Pngcs.PngReader.ReadRowInt(), Hjg.Pngcs.ImageLineHelper.SetPixel(), Hjg.Pngcs.ImageLineHelper.SetPixelFromARGB8(), Hjg.Pngcs.ImageLine.SetScanLine(), Hjg.Pngcs.ImageLine.ToString(), Hjg.Pngcs.ImageLine.UnpackToNewImageLine(), Hjg.Pngcs.ImageLineHelper.WriteDouble(), and Hjg.Pngcs.PngWriter.WriteRow().
ScanlineB
byte [] Hjg.Pngcs.ImageLine.ScanlineB get
Same as Scanline, but with one byte per sample. Only one of Scanline and ScanlineB is valid - this depends on SampleType}
Definition at line 43 of file ImageLine.cs.
 { get; }
Referenced by Hjg.Pngcs.ImageLineHelper.GetPixelToARGB8(), Hjg.Pngcs.ImageLine.GetScanlineByte(), Hjg.Pngcs.ImageLine.ImageLine(), Hjg.Pngcs.ImageLine.PackToNewImageLine(), Hjg.Pngcs.ImageLineHelper.Palette2rgb(), Hjg.Pngcs.ImageLineHelper.ReadDouble(), Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.ImageLineHelper.SetPixel(), Hjg.Pngcs.ImageLineHelper.SetPixelFromARGB8(), Hjg.Pngcs.ImageLine.UnpackToNewImageLine(), Hjg.Pngcs.ImageLineHelper.WriteDouble(), and Hjg.Pngcs.PngWriter.WriteRow().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/ImageLine.cs