Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader Class Reference
Marker reading and parsing
Public Member Functions
JpegMarkerReader (JpegDecompressStruct cinfo)
Initialize the marker reader module. This is called only once, when the decompression object is created.
void ResetMarkerReader ()
Reset marker processing state to begin a fresh datastream.
ReadResult ReadMarkers ()
bool ReadRestartMarker ()
bool NextMarker ()
void JpegSetMarkerProcessor (int marker_code, JpegDecompressStruct.JpegMarkerParserMethod routine)
Install a special processing method for COM or APPn markers.
void JpegSaveMarkers (int marker_code, int length_limit)
bool SawSOI ()
bool SawSOF ()
int NextRestartNumber ()
int DiscardedByteCount ()
void SkipBytes (int count)
Private Member Functions
void GetSOI ()
Process an SOI marker
bool GetSOF (bool is_baseline, bool is_prog, bool is_arith)
Process a SOFn marker
bool GetSOS ()
Process a SOS marker
bool GetDAC ()
Process a DAC marker
bool GetDHT ()
Process a DHT marker
bool GetDQT ()
Process a DQT marker
bool GetDRI ()
Process a DRI marker
bool GetLSE ()
Process an LSE marker
bool FirstMarker ()
Like next_marker, but used to obtain the initial SOI marker. For this marker, we do not allow preceding garbage or fill; otherwise, we might well scan an entire input file before realizing it ain't JPEG. If an application wants to process non-JFIF files, it must seek to the SOI before calling the JPEG library.
Static Private Member Functions
static bool SaveMarker (JpegDecompressStruct cinfo)
Save an APPn or COM marker into the marker list
static bool SkipVariable (JpegDecompressStruct cinfo)
Skip over an unknown or uninteresting variable-length marker
static bool GetInterestingAppN (JpegDecompressStruct cinfo)
Process an APP0 or APP14 marker without saving it
static void ExamineApp0 (JpegDecompressStruct cinfo, byte[] data, int datalen, int remaining)
Examine first few bytes from an APP0. Take appropriate action if it is a JFIF marker. datalen is # of bytes at data[], remaining is length of rest of marker data.
static void ExamineApp14 (JpegDecompressStruct cinfo, byte[] data, int datalen, int remaining)
Examine first few bytes from an APP14. Take appropriate action if it is an Adobe marker. datalen is # of bytes at data[], remaining is length of rest of marker data.
Private Attributes
const int APP0_DATA_LEN = 14
const int APP14_DATA_LEN = 12
const int APPN_DATA_LEN = 14
readonly JpegDecompressStruct m_cinfo
JpegDecompressStruct.JpegMarkerParserMethod m_process_COM
readonly JpegDecompressStruct.JpegMarkerParserMethod [] m_process_APPn = new JpegDecompressStruct.JpegMarkerParserMethod[16]
int m_length_limit_COM
readonly int [] m_length_limit_APPn = new int[16]
bool m_saw_SOI
bool m_saw_SOF
int m_next_restart_num
int m_discarded_bytes
JpegMarkerStruct m_cur_marker
int m_bytes_read
Detailed Description
Marker reading and parsing
Definition at line 16 of file JpegMarkerReader.cs.
Constructor & Destructor Documentation
JpegMarkerReader()
BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader (JpegDecompressStruct cinfo) inline
Initialize the marker reader module. This is called only once, when the decompression object is created.
Definition at line 46 of file JpegMarkerReader.cs.
         {
             m_cinfo = cinfo;
             /* Initialize COM/APPn processing.
             * By default, we examine and then discard APP0 and APP14,
             * but simply discard COM and all other APPn.
             */
             m_process_COM = SkipVariable;
             for (var i = 0; i < 16; i++)
             {
                 m_process_APPn[i] = SkipVariable;
                 m_length_limit_APPn[i] = 0;
             }
             m_process_APPn[0] = GetInterestingAppN;
             m_process_APPn[14] = GetInterestingAppN;
             /* Reset marker processing state */
             ResetMarkerReader();
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_length_limit_APPn, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_APPn, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_COM, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable().
Member Function Documentation
DiscardedByteCount()
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.DiscardedByteCount () inline
Definition at line 520 of file JpegMarkerReader.cs.
         {
             return m_discarded_bytes;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_discarded_bytes.
ExamineApp0()
static void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0 (JpegDecompressStruct cinfo, byte [] data, int datalen, int remaining) inline static private
Examine first few bytes from an APP0. Take appropriate action if it is a JFIF marker. datalen is # of bytes at data[], remaining is length of rest of marker data.
Definition at line 760 of file JpegMarkerReader.cs.
         {
             var totallen = datalen + remaining;
             if (datalen >= APP0_DATA_LEN
                 && data[0] == 0x4A
                 && data[1] == 0x46
                 && data[2] == 0x49
                 && data[3] == 0x46
                 && data[4] == 0)
             {
                 /* Found JFIF APP0 marker: save info */
                 cinfo.m_saw_JFIF_marker = true;
                 cinfo.m_JFIF_major_version = data[5];
                 cinfo.m_JFIF_minor_version = data[6];
                 cinfo.m_densityUnit = (DensityUnit)data[7];
                 cinfo.m_xDensity = (short)((data[8] << 8) + data[9]);
                 cinfo.m_yDensity = (short)((data[10] << 8) + data[11]);
                 /* Check version.
                  * Major version must be 1 or 2, anything else signals an incompatible change.
                  * (We used to treat this as an error, but now it's a nonfatal warning,
                  * because some bozo at Hijaak couldn't read the spec.)
                  * Minor version should be 0..2, but process anyway if newer.
                  */
                 if (cinfo.m_JFIF_major_version != 1 && cinfo.m_JFIF_major_version != 2)
                 {
                     cinfo.WarnMS(JMessageCode.JWRN_JFIF_MAJOR, cinfo.m_JFIF_major_version, cinfo.m_JFIF_minor_version);
                 }
                 /* Generate trace messages */
                 cinfo.TraceMS(1, JMessageCode.JTRC_JFIF, cinfo.m_JFIF_major_version, cinfo.m_JFIF_minor_version, cinfo.m_xDensity,
                                 cinfo.m_yDensity, cinfo.m_densityUnit);
                 /* Validate thumbnail dimensions and issue appropriate messages */
                 if ((data[12] | data[13]) != 0)
                 {
                     cinfo.TraceMS(1, JMessageCode.JTRC_JFIF_THUMBNAIL, data[12], data[13]);
                 }
                 totallen -= APP0_DATA_LEN;
                 if (totallen != (data[12] * data[13] * 3))
                 {
                     cinfo.TraceMS(1, JMessageCode.JTRC_JFIF_BADTHUMBNAILSIZE, totallen);
                 }
             }
             else if (datalen >= 6 && data[0] == 0x4A && data[1] == 0x46 && data[2] == 0x58 && data[3] == 0x58 && data[4] == 0)
             {
                 /* Found JFIF "JFXX" extension APP0 marker */
                 /* The library doesn't actually do anything with these,
                  * but we try to produce a helpful trace message.
                  */
                 switch (data[5])
                 {
                     case 0x10:
                     cinfo.TraceMS(1, JMessageCode.JTRC_THUMB_JPEG, totallen);
                     break;
                     case 0x11:
                     cinfo.TraceMS(1, JMessageCode.JTRC_THUMB_PALETTE, totallen);
                     break;
                     case 0x13:
                     cinfo.TraceMS(1, JMessageCode.JTRC_THUMB_RGB, totallen);
                     break;
                     default:
                     cinfo.TraceMS(1, JMessageCode.JTRC_JFIF_EXTENSION, data[5], totallen);
                     break;
                 }
             }
             else
             {
                 /* Start of APP0 does not match "JFIF" or "JFXX", or too short */
                 cinfo.TraceMS(1, JMessageCode.JTRC_APP0, totallen);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APP0_DATA_LEN, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_densityUnit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_major_version, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_minor_version, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_JFIF_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_xDensity, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_yDensity, BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker().
ExamineApp14()
static void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14 (JpegDecompressStruct cinfo, byte [] data, int datalen, int remaining) inline static private
Examine first few bytes from an APP14. Take appropriate action if it is an Adobe marker. datalen is # of bytes at data[], remaining is length of rest of marker data.
Definition at line 840 of file JpegMarkerReader.cs.
         {
             if (datalen >= APP14_DATA_LEN
                 && data[0] == 0x41
                 && data[1] == 0x64
                 && data[2] == 0x6F
                 && data[3] == 0x62
                 && data[4] == 0x65)
             {
                 /* Found Adobe APP14 marker */
                 var version = (data[5] << 8) + data[6];
                 var flags0 = (data[7] << 8) + data[8];
                 var flags1 = (data[9] << 8) + data[10];
                 int transform = data[11];
                 cinfo.TraceMS(1, JMessageCode.JTRC_ADOBE, version, flags0, flags1, transform);
                 cinfo.m_saw_Adobe_marker = true;
                 cinfo.m_Adobe_transform = (byte)transform;
             }
             else
             {
                 /* Start of APP14 does not match "Adobe", or too short */
                 cinfo.TraceMS(1, JMessageCode.JTRC_APP14, datalen + remaining);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APP14_DATA_LEN, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Adobe_transform, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_Adobe_marker, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker().
FirstMarker()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker () inline private
Like next_marker, but used to obtain the initial SOI marker. For this marker, we do not allow preceding garbage or fill; otherwise, we might well scan an entire input file before realizing it ain't JPEG. If an application wants to process non-JFIF files, it must seek to the SOI before calling the JPEG library.
Definition at line 1715 of file JpegMarkerReader.cs.
         {
             if (!m_cinfo.m_src.GetByte(out var c))
             {
                 return false;
             }
             if (!m_cinfo.m_src.GetByte(out var c2))
             {
                 return false;
             }
             if (c != 0xFF || c2 != (int)JpegMarker.SOI)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_NO_SOI, c, c2);
             }
             m_cinfo.m_unreadMarker = c2;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetDAC()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC () inline private
Process a DAC marker
Definition at line 1204 of file JpegMarkerReader.cs.
         {
             if (!m_cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             length -= 2;
             while (length > 0)
             {
                 if (!m_cinfo.m_src.GetByte(out var index))
                 {
                     return false;
                 }
                 if (!m_cinfo.m_src.GetByte(out var val))
                 {
                     return false;
                 }
                 length -= 2;
                 m_cinfo.TraceMS(1, JMessageCode.JTRC_DAC, index, val);
                 if (index < 0 || index >= (2 * JpegConstants.NUM_ARITH_TBLS))
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_DAC_INDEX, index);
                 }
                 if (index >= JpegConstants.NUM_ARITH_TBLS)
                 { /* define AC table */
                     m_cinfo.arithAcK[index - JpegConstants.NUM_ARITH_TBLS] = (byte)val;
                 }
                 else
                 {          /* define DC table */
                     m_cinfo.arithDcL[index] = (byte)(val & 0x0F);
                     m_cinfo.arithDcU[index] = (byte)(val >> 4);
                     if (m_cinfo.arithDcL[index] > m_cinfo.arithDcU[index])
                     {
                         m_cinfo.ErrExit(JMessageCode.JERR_DAC_VALUE, val);
                     }
                 }
             }
             if (length != 0)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithAcK, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithDcL, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithDcU, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_ARITH_TBLS, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetDHT()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT () inline private
Process a DHT marker
Definition at line 1259 of file JpegMarkerReader.cs.
         {
             if (!m_cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             length -= 2;
             var bits = new byte[17];
             var huffval = new byte[256];
             while (length > 16)
             {
                 if (!m_cinfo.m_src.GetByte(out var index))
                 {
                     return false;
                 }
                 m_cinfo.TraceMS(1, JMessageCode.JTRC_DHT, index);
                 bits[0] = 0;
                 var count = 0;
                 for (var i = 1; i <= 16; i++)
                 {
                     if (!m_cinfo.m_src.GetByte(out var temp))
                     {
                         return false;
                     }
                     bits[i] = (byte)temp;
                     count += bits[i];
                 }
                 length -= 1 + 16;
                 m_cinfo.TraceMS(2, JMessageCode.JTRC_HUFFBITS, bits[1], bits[2], bits[3], bits[4], bits[5], bits[6], bits[7], bits[8]);
                 m_cinfo.TraceMS(2, JMessageCode.JTRC_HUFFBITS, bits[9], bits[10], bits[11], bits[12], bits[13], bits[14], bits[15], bits[16]);
                 /* Here we just do minimal validation of the counts to avoid walking
                  * off the end of our table space. huff_entropy_decoder will check more carefully.
                  */
                 if (count > 256 || count > length)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
                 }
                 for (var i = 0; i < count; i++)
                 {
                     if (!m_cinfo.m_src.GetByte(out var temp))
                     {
                         return false;
                     }
                     huffval[i] = (byte)temp;
                 }
                 length -= count;
                 JHuffmanTable htblptr;
                 if ((index & 0x10) != 0)
                 {
                     /* AC table definition */
                     index -= 0x10;
                     if (m_cinfo.m_ac_huff_tbl_ptrs[index] is null)
                     {
                         m_cinfo.m_ac_huff_tbl_ptrs[index] = new JHuffmanTable();
                     }
                     htblptr = m_cinfo.m_ac_huff_tbl_ptrs[index];
                 }
                 else
                 {
                     /* DC table definition */
                     if (m_cinfo.m_dc_huff_tbl_ptrs[index] is null)
                     {
                         m_cinfo.m_dc_huff_tbl_ptrs[index] = new JHuffmanTable();
                     }
                     htblptr = m_cinfo.m_dc_huff_tbl_ptrs[index];
                 }
                 if (index < 0 || index >= JpegConstants.NUM_HUFF_TBLS)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_DHT_INDEX, index);
                 }
                 Buffer.BlockCopy(bits, 0, htblptr.Bits, 0, htblptr.Bits.Length);
                 Buffer.BlockCopy(huffval, 0, htblptr.Huffval, 0, htblptr.Huffval.Length);
             }
             if (length != 0)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JHuffmanTable.Bits, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JHuffmanTable.Huffval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dc_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetDQT()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT () inline private
Process a DQT marker
Definition at line 1360 of file JpegMarkerReader.cs.
         {
             if (!m_cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             length -= 2;
             while (length > 0)
             {
                 length--;
                 if (!m_cinfo.m_src.GetByte(out var n))
                 {
                     return false;
                 }
                 var prec = n >> 4;
                 n &= 0x0F;
                 m_cinfo.TraceMS(1, JMessageCode.JTRC_DQT, n, prec);
                 if (n >= JpegConstants.NUM_QUANT_TBLS)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_DQT_INDEX, n);
                 }
                 if (m_cinfo.m_quant_tbl_ptrs[n] is null)
                 {
                     m_cinfo.m_quant_tbl_ptrs[n] = new JQuantTable();
                 }
                 var quant_ptr = m_cinfo.m_quant_tbl_ptrs[n];
                 int count;
                 if (prec != 0)
                 {
                     if (length < JpegConstants.DCTSIZE2 * 2)
                     {
                         /* Initialize full table for safety. */
                         for (var i = 0; i < JpegConstants.DCTSIZE2; i++)
{
                             quant_ptr.quantBal[i] = 1;
                         }
                         count = length >> 1;
                     }
                     else
                     {
                         count = JpegConstants.DCTSIZE2;
                     }
                 }
                 else if (length < JpegConstants.DCTSIZE2)
                 {
                     /* Initialize full table for safety. */
                     for (var i = 0; i < JpegConstants.DCTSIZE2; i++)
                     {
                         quant_ptr.quantBal[i] = 1;
                     }
                     count = length;
                 }
                 else
                 {
                     count = JpegConstants.DCTSIZE2;
                 }
                 var natural_order = count switch
                 {
                     (2 * 2) => JpegUtils.jpeg_natural_order2,
                     (3 * 3) => JpegUtils.jpeg_natural_order3,
                     (4 * 4) => JpegUtils.jpeg_natural_order4,
                     (5 * 5) => JpegUtils.jpeg_natural_order5,
                     (6 * 6) => JpegUtils.jpeg_natural_order6,
                     (7 * 7) => JpegUtils.jpeg_natural_order7,
                     _ => JpegUtils.jpeg_natural_order,
                 };
                 for (var i = 0; i < count; i++)
                 {
                     int tmp;
                     if (prec != 0)
                     {
                         if (!m_cinfo.m_src.GetTwoBytes(out var temp))
{
                             return false;
                         }
                         tmp = temp;
                     }
                     else
                     {
                         if (!m_cinfo.m_src.GetByte(out var temp))
{
                             return false;
                         }
                         tmp = temp;
                     }
                     /* We convert the zigzag-order table to natural array order. */
                     quant_ptr.quantBal[natural_order[i]] = (short)tmp;
                 }
                 if (m_cinfo.jpgError.m_traceLevel >= 2)
                 {
                     for (var i = 0; i < JpegConstants.DCTSIZE2; i += 8)
                     {
                         m_cinfo.TraceMS(2, JMessageCode.JTRC_QUANTVALS, quant_ptr.quantBal[i],
                             quant_ptr.quantBal[i + 1], quant_ptr.quantBal[i + 2],
                             quant_ptr.quantBal[i + 3], quant_ptr.quantBal[i + 4],
                             quant_ptr.quantBal[i + 5], quant_ptr.quantBal[i + 6], quant_ptr.quantBal[i + 7]);
                     }
                 }
                 length -= count;
                 if (prec != 0)
                 {
                     length -= count;
                 }
             }
             if (length != 0)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order2, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order3, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order4, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order5, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order6, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order7, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS, BitMiracle.LibJpeg.Classic.JQuantTable.quantBal, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetDRI()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI () inline private
Process a DRI marker
Definition at line 1492 of file JpegMarkerReader.cs.
         {
             if (!m_cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             if (length != 4)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out var temp))
             {
                 return false;
             }
             var tmp = temp;
             m_cinfo.TraceMS(1, JMessageCode.JTRC_DRI, tmp);
             m_cinfo.m_restart_interval = tmp;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetInterestingAppN()
static bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN (JpegDecompressStruct cinfo) inline static private
Process an APP0 or APP14 marker without saving it
Definition at line 691 of file JpegMarkerReader.cs.
         {
             if (!cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             length -= 2;
             /* get the interesting part of the marker data */
             var numtoread = 0;
             if (length >= APPN_DATA_LEN)
             {
                 numtoread = APPN_DATA_LEN;
             }
             else if (length > 0)
             {
                 numtoread = length;
             }
             var b = new byte[APPN_DATA_LEN];
             for (var i = 0; i < numtoread; i++)
             {
                 if (!cinfo.m_src.GetByte(out var temp))
                 {
                     return false;
                 }
                 b[i] = (byte)temp;
             }
             length -= numtoread;
             /* process it */
             switch ((JpegMarker)cinfo.m_unreadMarker)
             {
                 case JpegMarker.APP0:
                 ExamineApp0(cinfo, b, numtoread, length);
                 break;
                 case JpegMarker.APP14:
                 ExamineApp14(cinfo, b, numtoread, length);
                 break;
                 default:
                 /* can't get here unless jpeg_save_markers chooses wrong processor */
                 cinfo.ErrExit(JMessageCode.JERR_UNKNOWN_MARKER, cinfo.m_unreadMarker);
                 break;
             }
             /* skip any remaining data -- could be lots */
             if (length > 0)
             {
                 cinfo.m_src.SkipInputData(length);
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APPN_DATA_LEN, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, and BitMiracle.LibJpeg.Classic.JpegSourceManager.SkipInputData().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers().
GetLSE()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE () inline private
Process an LSE marker
Definition at line 1519 of file JpegMarkerReader.cs.
         {
             if (!m_cinfo.m_marker.m_saw_SOF)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_SOF_BEFORE, "LSE");
             }
             if (m_cinfo.numComponents < 3)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             if (length != 24)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             if (!m_cinfo.m_src.GetByte(out var tmp))
             {
                 return false;
             }
             if (tmp != 0x0D)
             {
                 /* ID inverse transform specification */
                 m_cinfo.ErrExit(JMessageCode.JERR_UNKNOWN_MARKER, m_cinfo.m_unreadMarker);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out tmp))
             {
                 return false;
             }
             if (tmp != JpegConstants.MAXJSAMPLE)
             {
                 /* MAXTRANS */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetByte(out tmp))
             {
                 return false;
             }
             if (tmp != 3)
             {
                 /* Nt=3 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetByte(out var cid))
             {
                 return false;
             }
             if (cid != m_cinfo.CompInfo[1].Component_id)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetByte(out cid))
             {
                 return false;
             }
             if (cid != m_cinfo.CompInfo[0].Component_id)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetByte(out cid))
             {
                 return false;
             }
             if (cid != m_cinfo.CompInfo[2].Component_id)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetByte(out tmp))
             {
                 return false;
             }
             if (tmp != 0x80)
             {
                 /* F1: CENTER1=1, NORM1=0 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out tmp))
             {
                 return false;
             }
             if (tmp != 0)
             {
                 /* A(1,1)=0 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out tmp))
             {
                 return false;
             }
             if (tmp != 0)
             {
                 /* A(1,2)=0 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetByte(out tmp))
             {
                 return false;
             }
             if (tmp != 0)
             {
                 /* F2: CENTER2=0, NORM2=0 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out tmp))
             {
                 return false;
             }
             if (tmp != 1)
             {
                 /* A(2,1)=1 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out tmp))
             {
                 return false;
             }
             if (tmp != 0)
             {
                 /* A(2,2)=0 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetByte(out tmp))
             {
                 return false;
             }
             if (tmp != 0)
             {
                 /* F3: CENTER3=0, NORM3=0 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out tmp))
             {
                 return false;
             }
             if (tmp != 1)
             {
                 /* A(3,1)=1 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             if (!m_cinfo.m_src.GetTwoBytes(out tmp))
             {
                 return false;
             }
             if (tmp != 0)
             {
                 /* A(3,2)=0 */
                 m_cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             /* OK, valid transform that we can handle. */
             m_cinfo.color_transform = JColorTransform.JCT_SUBTRACT_GREEN;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.color_transform, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_id, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetSOF()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF (bool is_baseline, bool is_prog, bool is_arith) inline private
Process a SOFn marker
Definition at line 931 of file JpegMarkerReader.cs.
         {
             m_cinfo.isBaseline = is_baseline;
             m_cinfo.progressiveMode = is_prog;
             m_cinfo.arithCode = is_arith;
             if (!m_cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             if (!m_cinfo.m_src.GetByte(out m_cinfo.m_dataPrecision))
             {
                 return false;
             }
             if (!m_cinfo.m_src.GetTwoBytes(out var temp))
             {
                 return false;
             }
             m_cinfo.imageHeight = temp;
             if (!m_cinfo.m_src.GetTwoBytes(out temp))
             {
                 return false;
             }
             m_cinfo.imageWidth = temp;
             if (!m_cinfo.m_src.GetByte(out m_cinfo.numComponents))
             {
                 return false;
             }
             length -= 8;
             m_cinfo.TraceMS(1, JMessageCode.JTRC_SOF, m_cinfo.m_unreadMarker,
                 m_cinfo.imageWidth, m_cinfo.imageHeight, m_cinfo.numComponents);
             if (m_cinfo.m_marker.m_saw_SOF)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_SOF_DUPLICATE);
             }
             /* We don't support files in which the image height is initially specified */
             /* as 0 and is later redefined by DNL.  As long as we have to check that,  */
             /* might as well have a general sanity check. */
             if (m_cinfo.imageHeight <= 0 || m_cinfo.imageWidth <= 0 || m_cinfo.numComponents <= 0)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_EMPTY_IMAGE);
             }
             if (length != (m_cinfo.numComponents * 3))
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             if (m_cinfo.CompInfo is null)
             {
                 /* do only once, even if suspend */
                 m_cinfo.CompInfo = JpegComponentInfo.CreateArrayOfComponents(m_cinfo.numComponents);
             }
             for (var ci = 0; ci < m_cinfo.numComponents; ci++)
             {
                 //jpeg_component_info compptr = m_cinfo.Comp_info[ci];
                 if (!m_cinfo.m_src.GetByte(out var c))
                 {
                     return false;
                 }
                 /* Check to see whether component id has already been seen   */
                 /* (in violation of the spec, but unfortunately seen in some */
                 /* files).  If so, create "fake" component id equal to the   */
                 /* max id seen so far + 1. */
                 var componentInfoIndex = 0;
                 JpegComponentInfo compptr;
                 for (var i = 0; i < ci; i++, componentInfoIndex++)
                 {
                     compptr = m_cinfo.CompInfo[componentInfoIndex];
                     if (c == compptr.Component_id)
                     {
                         componentInfoIndex = 0;
                         compptr = m_cinfo.CompInfo[componentInfoIndex];
                         c = compptr.Component_id;
                         componentInfoIndex++;
                         _ = m_cinfo.CompInfo[componentInfoIndex];
                         for (i = 1; i < ci; i++, componentInfoIndex++)
{
                             compptr = m_cinfo.CompInfo[componentInfoIndex];
                             if (compptr.Component_id > c)
{
                                 c = compptr.Component_id;
                             }
                         }
                         c++;
                         break;
                     }
                 }
                 compptr = m_cinfo.CompInfo[componentInfoIndex];
                 compptr.Component_id = c;
                 compptr.Component_index = ci;
                 if (!m_cinfo.m_src.GetByte(out c))
                 {
                     return false;
                 }
                 compptr.H_samp_factor = (c >> 4) & 15;
                 compptr.V_samp_factor = c & 15;
                 if (!m_cinfo.m_src.GetByte(out var quant_tbl_no))
                 {
                     return false;
                 }
                 compptr.Quant_tbl_no = quant_tbl_no;
                 m_cinfo.TraceMS(1, JMessageCode.JTRC_SOF_COMPONENT, compptr.Component_id,
                     compptr.H_samp_factor, compptr.V_samp_factor,
                     compptr.Quant_tbl_no);
             }
             m_cinfo.m_marker.m_saw_SOF = true;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.arithCode, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_id, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_index, BitMiracle.LibJpeg.Classic.JpegComponentInfo.CreateArrayOfComponents(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JpegComponentInfo.H_samp_factor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.imageWidth, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.isBaseline, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_dataPrecision, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.progressiveMode, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Quant_tbl_no, BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), and BitMiracle.LibJpeg.Classic.JpegComponentInfo.V_samp_factor.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetSOI()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI () inline private
Process an SOI marker
Definition at line 898 of file JpegMarkerReader.cs.
         {
             m_cinfo.TraceMS(1, JMessageCode.JTRC_SOI);
             if (m_cinfo.m_marker.m_saw_SOI)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_SOI_DUPLICATE);
             }
             /* Reset all parameters that are defined to be reset by SOI */
             m_cinfo.m_restart_interval = 0;
             /* Set initial assumptions for colorspace etc */
             m_cinfo.jpegColorSpace = JColorSpace.JCS_UNKNOWN;
             m_cinfo.color_transform = JColorTransform.JCT_NONE;
             m_cinfo.m_CCIR601_sampling = false; /* Assume non-CCIR sampling??? */
             m_cinfo.m_saw_JFIF_marker = false;
             m_cinfo.m_JFIF_major_version = 1; /* set default JFIF APP0 values */
             m_cinfo.m_JFIF_minor_version = 1;
             m_cinfo.m_densityUnit = DensityUnit.Unknown;
             m_cinfo.m_xDensity = 1;
             m_cinfo.m_yDensity = 1;
             m_cinfo.m_saw_Adobe_marker = false;
             m_cinfo.m_Adobe_transform = 0;
             m_cinfo.m_marker.m_saw_SOI = true;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.color_transform, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.jpegColorSpace, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Adobe_transform, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_CCIR601_sampling, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_densityUnit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_major_version, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_JFIF_minor_version, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_Adobe_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_saw_JFIF_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_xDensity, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_yDensity, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
GetSOS()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS () inline private
Process a SOS marker
Definition at line 1067 of file JpegMarkerReader.cs.
         {
             if (!m_cinfo.m_marker.m_saw_SOF)
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_SOF_BEFORE, "SOS");
             }
             if (!m_cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             /* Number of components */
             if (!m_cinfo.m_src.GetByte(out var n))
             {
                 return false;
             }
             m_cinfo.TraceMS(1, JMessageCode.JTRC_SOS, n);
             if (length != ((n * 2) + 6)
                 || n > JpegConstants.MAX_COMPS_IN_SCAN
                 || (n == 0
                     && m_cinfo.progressiveMode))
             {
                 /* pseudo SOS marker only allowed in progressive mode */
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_LENGTH);
             }
             m_cinfo.m_comps_in_scan = n;
             /* Collect the component-spec parameters */
             for (var i = 0; i < n; i++)
             {
                 if (!m_cinfo.m_src.GetByte(out var c))
                 {
                     return false;
                 }
                 /* Detect the case where component id's are not unique, and, if so, */
                 /* create a fake component id using the same logic as in get_sof.   */
                 /* Note:  This also ensures that all of the SOF components are      */
                 /* referenced in the single scan case, which prevents access to     */
                 /* uninitialized memory in later decoding stages. */
                 for (var ci = 0; ci < i; ci++)
                 {
                     var componentInfo = m_cinfo.CompInfo[m_cinfo.m_cur_comp_info[ci]];
                     if (c == componentInfo.Component_id)
                     {
                         componentInfo = m_cinfo.CompInfo[m_cinfo.m_cur_comp_info[0]];
                         c = componentInfo.Component_id;
                         for (ci = 1; ci < i; ci++)
{
                             componentInfo = m_cinfo.CompInfo[m_cinfo.m_cur_comp_info[ci]];
                             if (componentInfo.Component_id > c)
{
                                 c = componentInfo.Component_id;
                             }
                         }
                         c++;
                         break;
                     }
                 }
                 var idFound = false;
                 var foundIndex = -1;
                 for (var ci = 0; ci < m_cinfo.numComponents; ci++)
                 {
                     if (c == m_cinfo.CompInfo[ci].Component_id)
                     {
                         foundIndex = ci;
                         idFound = true;
                         break;
                     }
                 }
                 if (!idFound)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_BAD_COMPONENT_ID, c);
                 }
                 m_cinfo.m_cur_comp_info[i] = foundIndex;
                 if (!m_cinfo.m_src.GetByte(out c))
                 {
                     return false;
                 }
                 m_cinfo.CompInfo[foundIndex].Dc_tbl_no = (c >> 4) & 15;
                 m_cinfo.CompInfo[foundIndex].Ac_tbl_no = c & 15;
                 m_cinfo.TraceMS(1, JMessageCode.JTRC_SOS_COMPONENT,
                     m_cinfo.CompInfo[foundIndex].Component_id,
                     m_cinfo.CompInfo[foundIndex].Dc_tbl_no,
                     m_cinfo.CompInfo[foundIndex].Ac_tbl_no);
             }
             /* Collect the additional scan parameters Ss, Se, Ah/Al. */
             if (!m_cinfo.m_src.GetByte(out var temp))
             {
                 return false;
             }
             m_cinfo.m_Ss = temp;
             if (!m_cinfo.m_src.GetByte(out temp))
             {
                 return false;
             }
             m_cinfo.m_Se = temp;
             if (!m_cinfo.m_src.GetByte(out temp))
             {
                 return false;
             }
             m_cinfo.m_Ah = (temp >> 4) & 15;
             m_cinfo.m_Al = temp & 15;
             m_cinfo.TraceMS(1, JMessageCode.JTRC_SOS_PARAMS, m_cinfo.m_Ss, m_cinfo.m_Se, m_cinfo.m_Ah, m_cinfo.m_Al);
             /* Prepare to scan data & restart markers */
             m_cinfo.m_marker.m_next_restart_num = 0;
             /* Count another (non-pseudo) SOS marker */
             if (n != 0)
             {
                 m_cinfo.inputScanNumber++;
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegComponentInfo.Ac_tbl_no, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_id, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.inputScanNumber, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ah, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Al, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_comps_in_scan, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cur_comp_info, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Se, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_Ss, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPS_IN_SCAN, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.progressiveMode, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
JpegSaveMarkers()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers (int marker_code, int length_limit) inline
Definition at line 457 of file JpegMarkerReader.cs.
         {
             /* Choose processor routine to use.
              * APP0/APP14 have special requirements.
              */
             JpegDecompressStruct.JpegMarkerParserMethod processor;
             if (length_limit != 0)
             {
                 processor = SaveMarker;
                 /* If saving APP0/APP14, save at least enough for our internal use. */
                 if (marker_code == (int)JpegMarker.APP0 && length_limit < APP0_DATA_LEN)
                 {
                     length_limit = APP0_DATA_LEN;
                 }
                 else if (marker_code == (int)JpegMarker.APP14 && length_limit < APP14_DATA_LEN)
                 {
                     length_limit = APP14_DATA_LEN;
                 }
             }
             else
             {
                 processor = SkipVariable;
                 /* If discarding APP0/APP14, use our regular on-the-fly processor. */
                 if (marker_code == (int)JpegMarker.APP0 || marker_code == (int)JpegMarker.APP14)
                 {
                     processor = GetInterestingAppN;
                 }
             }
             if (marker_code == (int)JpegMarker.COM)
             {
                 m_process_COM = processor;
                 m_length_limit_COM = length_limit;
             }
             else if (marker_code >= (int)JpegMarker.APP0 && marker_code <= (int)JpegMarker.APP15)
             {
                 m_process_APPn[marker_code - (int)JpegMarker.APP0] = processor;
                 m_length_limit_APPn[marker_code - (int)JpegMarker.APP0] = length_limit;
             }
             else
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_UNKNOWN_MARKER, marker_code);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APP0_DATA_LEN, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APP14_DATA_LEN, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegMarkerParserMethod(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_length_limit_APPn, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_length_limit_COM, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_APPn, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_COM, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable().
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegSaveMarkers().
JpegSetMarkerProcessor()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor (int marker_code, JpegDecompressStruct.JpegMarkerParserMethod routine) inline
Install a special processing method for COM or APPn markers.
Definition at line 441 of file JpegMarkerReader.cs.
         {
             if (marker_code == (int)JpegMarker.COM)
             {
                 m_process_COM = routine;
             }
             else if (marker_code >= (int)JpegMarker.APP0 && marker_code <= (int)JpegMarker.APP15)
             {
                 m_process_APPn[marker_code - (int)JpegMarker.APP0] = routine;
             }
             else
             {
                 m_cinfo.ErrExit(JMessageCode.JERR_UNKNOWN_MARKER, marker_code);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_APPn, and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_COM.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegSetMarkerProcessor().
NextMarker()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker () inline
Find the next JPEG marker, save it in cinfo.unread_marker. Returns false if had to suspend before reaching a marker; in that case cinfo.unread_marker is unchanged.
Note that the result might not be a valid marker code, but it will never be 0 or FF.
Definition at line 378 of file JpegMarkerReader.cs.
         {
             int c;
             while (true)
             {
                 if (!m_cinfo.m_src.GetByte(out c))
                 {
                     return false;
                 }
                 /* Skip any non-FF bytes.
                  * This may look a bit inefficient, but it will not occur in a valid file.
                  * We sync after each discarded byte so that a suspending data source
                  * can discard the byte from its buffer.
                  */
                 while (c != 0xFF)
                 {
                     m_cinfo.m_marker.m_discarded_bytes++;
                     if (!m_cinfo.m_src.GetByte(out c))
                     {
                         return false;
                     }
                 }
                 /* This loop swallows any duplicate FF bytes.  Extra FFs are legal as
                  * pad bytes, so don't count them in discarded_bytes.  We assume there
                  * will not be so many consecutive FF bytes as to overflow a suspending
                  * data source's input buffer.
                  */
                 do
                 {
                     if (!m_cinfo.m_src.GetByte(out c))
                     {
                         return false;
                     }
                 }
                 while (c == 0xFF);
                 if (c != 0)
                 {
                     /* found a valid marker, exit loop */
                     break;
                 }
                 /* Reach here if we found a stuffed-zero data sequence (FF/00).
                  * Discard it and loop back to try again.
                  */
                 m_cinfo.m_marker.m_discarded_bytes += 2;
             }
             if (m_cinfo.m_marker.m_discarded_bytes != 0)
             {
                 m_cinfo.WarnMS(JMessageCode.JWRN_EXTRANEOUS_DATA, m_cinfo.m_marker.m_discarded_bytes, c);
                 m_cinfo.m_marker.m_discarded_bytes = 0;
             }
             m_cinfo.m_unreadMarker = c;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker().
NextRestartNumber()
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextRestartNumber () inline
Definition at line 515 of file JpegMarkerReader.cs.
         {
             return m_next_restart_num;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_next_restart_num.
ReadMarkers()
ReadResult BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers () inline
Read markers until SOS or EOI.
Returns same codes as are defined for jpeg_consume_input: JPEG_SUSPENDED, JPEG_REACHED_SOS, or JPEG_REACHED_EOI.
Note: This function may return a pseudo SOS marker(with zero component number) for treat by input controller's consume_input. consume_input itself should filter out (skip) the pseudo marker after processing for the caller.
Definition at line 96 of file JpegMarkerReader.cs.
         {
             /* Outer loop repeats once for each marker. */
             while (true)
             {
                 /* Collect the marker proper, unless we already did. */
                 /* NB: first_marker() enforces the requirement that SOI appear first. */
                 if (m_cinfo.m_unreadMarker == 0)
                 {
                     if (!m_cinfo.m_marker.m_saw_SOI)
                     {
                         if (!FirstMarker())
{
                             return ReadResult.JPEG_SUSPENDED;
                         }
                     }
                     else if (!NextMarker())
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                 }
                 /* At this point m_cinfo.unread_marker contains the marker code and the
                  * input point is just past the marker proper, but before any parameters.
                  * A suspension will cause us to return with this state still true.
                  */
                 switch ((JpegMarker)m_cinfo.m_unreadMarker)
                 {
                     case JpegMarker.SOI:
                     GetSOI();
                     break;
                     case JpegMarker.SOF0:
                     /* Baseline */
                     if (!GetSOF(true, false, false))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.SOF1:
                     /* Extended sequential, Huffman */
                     if (!GetSOF(false, false, false))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.SOF2:
                     /* Progressive, Huffman */
                     if (!GetSOF(false, true, false))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.SOF9:
                     /* Extended sequential, arithmetic */
                     if (!GetSOF(false, false, true))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.SOF10:
                     /* Progressive, arithmetic */
                     if (!GetSOF(false, true, true))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     /* Currently unsupported SOFn types */
                     case JpegMarker.SOF3:
                     /* Lossless, Huffman */
                     case JpegMarker.SOF5:
                     /* Differential sequential, Huffman */
                     case JpegMarker.SOF6:
                     /* Differential progressive, Huffman */
                     case JpegMarker.SOF7:
                     /* Differential lossless, Huffman */
                     case JpegMarker.JPG:
                     /* Reserved for JPEG extensions */
                     case JpegMarker.SOF11:
                     /* Lossless, arithmetic */
                     case JpegMarker.SOF13:
                     /* Differential sequential, arithmetic */
                     case JpegMarker.SOF14:
                     /* Differential progressive, arithmetic */
                     case JpegMarker.SOF15:
                     /* Differential lossless, arithmetic */
                     m_cinfo.ErrExit(JMessageCode.JERR_SOF_UNSUPPORTED, m_cinfo.m_unreadMarker);
                     break;
                     case JpegMarker.SOS:
                     if (!GetSOS())
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     m_cinfo.m_unreadMarker = 0;   /* processed the marker */
                     return ReadResult.JPEG_REACHED_SOS;
                     case JpegMarker.EOI:
                     m_cinfo.TraceMS(1, JMessageCode.JTRC_EOI);
                     m_cinfo.m_unreadMarker = 0;   /* processed the marker */
                     return ReadResult.JPEG_REACHED_EOI;
                     case JpegMarker.DAC:
                     if (!GetDAC())
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.DHT:
                     if (!GetDHT())
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.DQT:
                     if (!GetDQT())
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.DRI:
                     if (!GetDRI())
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.JPG8:
                     if (!GetLSE())
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.APP0:
                     case JpegMarker.APP1:
                     case JpegMarker.APP2:
                     case JpegMarker.APP3:
                     case JpegMarker.APP4:
                     case JpegMarker.APP5:
                     case JpegMarker.APP6:
                     case JpegMarker.APP7:
                     case JpegMarker.APP8:
                     case JpegMarker.APP9:
                     case JpegMarker.APP10:
                     case JpegMarker.APP11:
                     case JpegMarker.APP12:
                     case JpegMarker.APP13:
                     case JpegMarker.APP14:
                     case JpegMarker.APP15:
                     if (!m_cinfo.m_marker.m_process_APPn[m_cinfo.m_unreadMarker - (int)JpegMarker.APP0](m_cinfo))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     case JpegMarker.COM:
                     if (!m_cinfo.m_marker.m_process_COM(m_cinfo))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     /* these are all parameterless */
                     case JpegMarker.RST0:
                     case JpegMarker.RST1:
                     case JpegMarker.RST2:
                     case JpegMarker.RST3:
                     case JpegMarker.RST4:
                     case JpegMarker.RST5:
                     case JpegMarker.RST6:
                     case JpegMarker.RST7:
                     case JpegMarker.TEM:
                     m_cinfo.TraceMS(1, JMessageCode.JTRC_PARMLESS_MARKER, m_cinfo.m_unreadMarker);
                     break;
                     case JpegMarker.DNL:
                     /* Ignore DNL ... perhaps the wrong thing */
                     if (!SkipVariable(m_cinfo))
                     {
                         return ReadResult.JPEG_SUSPENDED;
                     }
                     break;
                     default:
                     /* must be DHP, EXP, JPGn, or RESn */
                     /* For now, we treat the reserved markers as fatal errors since they are
                      * likely to be used to signal incompatible JPEG Part 3 extensions.
                      * Once the JPEG 3 version-number marker is well defined, this code
                      * ought to change!
                      */
                     m_cinfo.ErrExit(JMessageCode.JERR_UNKNOWN_MARKER, m_cinfo.m_unreadMarker);
                     break;
                 }
                 /* Successfully processed marker, so reset state variable */
                 m_cinfo.m_unreadMarker = 0;
             } /* end loop */
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
ReadRestartMarker()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker () inline
Read a restart marker, which is expected to appear next in the datastream; if the marker is not there, take appropriate recovery action. Returns false if suspension is required.
Made public for use by entropy decoder only
This is called by the entropy decoder after it has read an appropriate number of MCUs. cinfo.unread_marker may be nonzero if the entropy decoder has already read a marker from the data source. Under normal conditions cinfo.unread_marker will be reset to 0 before returning; if not reset, it holds a marker which the decoder will be unable to read past.
Definition at line 333 of file JpegMarkerReader.cs.
         {
             /* Obtain a marker unless we already did. */
             /* Note that next_marker will complain if it skips any data. */
             if (m_cinfo.m_unreadMarker == 0)
             {
                 if (!NextMarker())
                 {
                     return false;
                 }
             }
             if (m_cinfo.m_unreadMarker == ((int)JpegMarker.RST0 + m_cinfo.m_marker.m_next_restart_num))
             {
                 /* Normal case --- swallow the marker and let entropy decoder continue */
                 m_cinfo.TraceMS(3, JMessageCode.JTRC_RST, m_cinfo.m_marker.m_next_restart_num);
                 m_cinfo.m_unreadMarker = 0;
             }
             else
             {
                 /* Uh-oh, the restart markers have been messed up. */
                 /* Let the data source manager determine how to resync. */
                 if (!m_cinfo.m_src.ReSyncToRestart(m_cinfo, m_cinfo.m_marker.m_next_restart_num))
                 {
                     return false;
                 }
             }
             /* Update next-restart state */
             m_cinfo.m_marker.m_next_restart_num = (m_cinfo.m_marker.m_next_restart_num + 1) & 7;
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
ResetMarkerReader()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader () inline
Reset marker processing state to begin a fresh datastream.
Definition at line 72 of file JpegMarkerReader.cs.
         {
             m_cinfo.CompInfo = null;        /* until allocated by get_sof */
             m_cinfo.inputScanNumber = 0;       /* no SOS seen yet */
             m_cinfo.m_unreadMarker = 0;       /* no pending marker */
             m_saw_SOI = false;        /* set internal state too */
             m_saw_SOF = false;
             m_discarded_bytes = 0;
             m_cur_marker = null;
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.inputScanNumber, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cur_marker, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_discarded_bytes, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_saw_SOF, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_saw_SOI, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader().
SaveMarker()
static bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker (JpegDecompressStruct cinfo) inline static private
Save an APPn or COM marker into the marker list
Definition at line 533 of file JpegMarkerReader.cs.
         {
             var cur_marker = cinfo.m_marker.m_cur_marker;
             var length = 0;
             int bytes_read;
             int data_length;
             var dataOffset = 0;
             byte[] data;
             if (cur_marker is null)
             {
                 /* begin reading a marker */
                 if (!cinfo.m_src.GetTwoBytes(out length))
                 {
                     return false;
                 }
                 length -= 2;
                 if (length >= 0)
                 {
                     /* watch out for bogus length word */
                     /* figure out how much we want to save */
                     int limit;
                     if (cinfo.m_unreadMarker == (int)JpegMarker.COM)
                     {
                         limit = cinfo.m_marker.m_length_limit_COM;
                     }
                     else
                     {
                         limit = cinfo.m_marker.m_length_limit_APPn[cinfo.m_unreadMarker - (int)JpegMarker.APP0];
                     }
                     if (length < limit)
                     {
                         limit = length;
                     }
                     /* allocate and initialize the marker item */
                     cur_marker = new JpegMarkerStruct((byte)cinfo.m_unreadMarker, length, limit);
                     /* data area is just beyond the jpeg_marker_struct */
                     data = cur_marker.Data;
                     cinfo.m_marker.m_cur_marker = cur_marker;
                     cinfo.m_marker.m_bytes_read = 0;
                     bytes_read = 0;
                     data_length = limit;
                 }
                 else
                 {
                     /* deal with bogus length word */
                     bytes_read = data_length = 0;
                     data = null;
                 }
             }
             else
             {
                 /* resume reading a marker */
                 bytes_read = cinfo.m_marker.m_bytes_read;
                 data_length = cur_marker.Data.Length;
                 data = cur_marker.Data;
                 dataOffset = bytes_read;
             }
             byte[] tempData = null;
             if (data_length != 0)
             {
                 tempData = new byte[data.Length];
             }
             while (bytes_read < data_length)
             {
                 /* move the restart point to here */
                 cinfo.m_marker.m_bytes_read = bytes_read;
                 /* If there's not at least one byte in buffer, suspend */
                 if (!cinfo.m_src.MakeByteAvailable())
                 {
                     return false;
                 }
                 /* Copy bytes with reasonable rapidity */
                 var read = cinfo.m_src.GetBytes(tempData, data_length - bytes_read);
                 Buffer.BlockCopy(tempData, 0, data, dataOffset, read);
                 bytes_read += read;
                 dataOffset += read;
             }
             /* Done reading what we want to read */
             if (cur_marker is object)
             {
                 /* will be null if bogus length word */
                 /* Add new marker to end of list */
                 cinfo.m_marker_list.Add(cur_marker);
                 /* Reset pointer & calc remaining data length */
                 data = cur_marker.Data;
                 dataOffset = 0;
                 length = cur_marker.OriginalLength - data_length;
             }
             /* Reset to initial state for next marker */
             cinfo.m_marker.m_cur_marker = null;
             var currentMarker = (JpegMarker)cinfo.m_unreadMarker;
             if (data_length != 0 && (currentMarker == JpegMarker.APP0 || currentMarker == JpegMarker.APP14))
             {
                 tempData = new byte[data.Length];
                 Buffer.BlockCopy(data, dataOffset, tempData, 0, data.Length - dataOffset);
             }
             /* Process the marker if interesting; else just make a generic trace msg */
             switch ((JpegMarker)cinfo.m_unreadMarker)
             {
                 case JpegMarker.APP0:
                 ExamineApp0(cinfo, tempData, data_length, length);
                 break;
                 case JpegMarker.APP14:
                 ExamineApp14(cinfo, tempData, data_length, length);
                 break;
                 default:
                 cinfo.TraceMS(1, JMessageCode.JTRC_MISC_MARKER, cinfo.m_unreadMarker, data_length + length);
                 break;
             }
             /* skip any remaining data -- could be lots */
             if (length > 0)
             {
                 cinfo.m_src.SkipInputData(length);
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetBytes(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker_list, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.JpegSourceManager.MakeByteAvailable(), BitMiracle.LibJpeg.Classic.JpegSourceManager.SkipInputData(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers().
SawSOF()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SawSOF () inline
Definition at line 510 of file JpegMarkerReader.cs.
         {
             return m_saw_SOF;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_saw_SOF.
SawSOI()
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SawSOI () inline
Definition at line 505 of file JpegMarkerReader.cs.
         {
             return m_saw_SOI;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_saw_SOI.
SkipBytes()
void BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipBytes (int count) inline
Definition at line 525 of file JpegMarkerReader.cs.
         {
             m_discarded_bytes += count;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_discarded_bytes.
SkipVariable()
static bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable (JpegDecompressStruct cinfo) inline static private
Skip over an unknown or uninteresting variable-length marker
Definition at line 669 of file JpegMarkerReader.cs.
         {
             if (!cinfo.m_src.GetTwoBytes(out var length))
             {
                 return false;
             }
             length -= 2;
             cinfo.TraceMS(1, JMessageCode.JTRC_MISC_MARKER, cinfo.m_unreadMarker, length);
             if (length > 0)
             {
                 cinfo.m_src.SkipInputData(length);
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_src, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.JpegSourceManager.SkipInputData(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers().
Member Data Documentation
APP0_DATA_LEN
const int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APP0_DATA_LEN = 14 private
Definition at line 18 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers().
APP14_DATA_LEN
const int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APP14_DATA_LEN = 12 private
Definition at line 19 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers().
APPN_DATA_LEN
const int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.APPN_DATA_LEN = 14 private
Definition at line 20 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN().
m_bytes_read
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_bytes_read private
Definition at line 39 of file JpegMarkerReader.cs.
m_cinfo
readonly JpegDecompressStruct BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cinfo private
Definition at line 22 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader().
m_cur_marker
JpegMarkerStruct BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_cur_marker private
Definition at line 38 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader().
m_discarded_bytes
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_discarded_bytes private
Definition at line 35 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.DiscardedByteCount(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipBytes().
m_length_limit_APPn
readonly int [] BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_length_limit_APPn = new int[16] private
Definition at line 30 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers().
m_length_limit_COM
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_length_limit_COM private
Definition at line 29 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers().
m_next_restart_num
int BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_next_restart_num private
Definition at line 34 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextRestartNumber().
m_process_APPn
readonly JpegDecompressStruct.JpegMarkerParserMethod [] BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_APPn = new JpegDecompressStruct.JpegMarkerParserMethod[16] private
Definition at line 26 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor().
m_process_COM
JpegDecompressStruct.JpegMarkerParserMethod BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_process_COM private
Definition at line 25 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegMarkerReader(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor().
m_saw_SOF
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_saw_SOF private
Definition at line 33 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SawSOF().
m_saw_SOI
bool BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.m_saw_SOI private
Definition at line 32 of file JpegMarkerReader.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ResetMarkerReader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SawSOI().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegMarkerReader.cs