Juniper: Juniper.Events.ButtonEventEditor Class Reference
Juniper.Events.ButtonEventEditor Class Reference
Public Member Functions
override void OnInspectorGUI ()
Private Attributes
const string FIELD_ONCLICK = nameof(_.onClick)
const string FIELD_ONDOUBLECLICK = nameof(_.onDoubleClick)
const string FIELD_ONLONGPRESS = nameof(_.onLongPress)
const string FIELD_ONDOWN = nameof(_.onDown)
const string FIELD_ONUP = nameof(_.onUp)
Static Private Attributes
static readonly ButtonEvent _
static readonly GUIContent ButtonTypeLabel = new GUIContent("Button Type")
static readonly GUIContent ButtonValueLabel = new GUIContent("Button Value")
Detailed Description
Definition at line 11 of file ButtonEventEditor.cs.
Member Function Documentation
OnInspectorGUI()
override void Juniper.Events.ButtonEventEditor.OnInspectorGUI () inline
Definition at line 23 of file ButtonEventEditor.cs.
         {
             serializedObject.Update();
             var value = (ButtonEvent)serializedObject.targetObject;
             var enumTypes = value.GetSupportedButtonTypes().ToArray();
             var enumTypeNames = enumTypes.Select(t => t.FullName).ToArray();
             var selectedTypeIndex = ArrayUtility.IndexOf(enumTypeNames, value.buttonTypeName);
             selectedTypeIndex = EditorGUILayout.Popup(ButtonTypeLabel, selectedTypeIndex, enumTypeNames);
             var destroy = false;
             if (0 <= selectedTypeIndex)
             {
                 value.buttonTypeName = enumTypeNames[selectedTypeIndex];
                 var enumType = enumTypes[selectedTypeIndex];
                 var enumStrings = Enum.GetNames(enumType);
                 var selectedValueIndex = ArrayUtility.IndexOf(enumStrings, value.buttonValueName);
                 selectedValueIndex = EditorGUILayout.Popup(ButtonValueLabel, selectedValueIndex, enumStrings);
                 if (0 > selectedValueIndex)
                 {
                     value.buttonValueName = null;
                 }
                 else
                 {
                     var buttonValueName = enumStrings[selectedValueIndex];
                     var key = ButtonEvent.FormatKey(value.buttonTypeName, buttonValueName);
                     var matching = value.GetComponents<ButtonEvent>()
                         .Count(e => e.Key == key && e != value);
                     if (matching <= 0)
                     {
                         value.buttonValueName = buttonValueName;
                     }
                     else if (EditorUtility.DisplayDialog("Error", $"A ButtonEvent for {key} already exists. Do you want to delete this ButtonEvent? If you keep this ButtonEvent, its Button Value will be reverted to its previous value.", "Delete", "Keep"))
                     {
                         destroy = true;
                     }
                 }
             }
             if (destroy)
             {
                 value.Destroy();
             }
             else
             {
                 EditorGUILayout.PropertyField(serializedObject.FindProperty(FIELD_ONDOWN));
                 EditorGUILayout.PropertyField(serializedObject.FindProperty(FIELD_ONCLICK));
                 EditorGUILayout.PropertyField(serializedObject.FindProperty(FIELD_ONDOUBLECLICK));
                 EditorGUILayout.PropertyField(serializedObject.FindProperty(FIELD_ONLONGPRESS));
                 EditorGUILayout.PropertyField(serializedObject.FindProperty(FIELD_ONUP));
                 serializedObject.ApplyModifiedProperties();
             }
         }
References Juniper.Events.ButtonEventEditor.ButtonTypeLabel, Juniper.Events.ButtonEventEditor.ButtonValueLabel, Juniper.Events.ButtonEventEditor.FIELD_ONCLICK, Juniper.Events.ButtonEventEditor.FIELD_ONDOUBLECLICK, Juniper.Events.ButtonEventEditor.FIELD_ONDOWN, Juniper.Events.ButtonEventEditor.FIELD_ONLONGPRESS, Juniper.Events.ButtonEventEditor.FIELD_ONUP, and Juniper.Events.ButtonEvent.FormatKey().
Member Data Documentation
_
readonly ButtonEvent Juniper.Events.ButtonEventEditor._ static private
Definition at line 13 of file ButtonEventEditor.cs.
ButtonTypeLabel
readonly GUIContent Juniper.Events.ButtonEventEditor.ButtonTypeLabel = new GUIContent("Button Type") static private
Definition at line 20 of file ButtonEventEditor.cs.
Referenced by Juniper.Events.ButtonEventEditor.OnInspectorGUI().
ButtonValueLabel
readonly GUIContent Juniper.Events.ButtonEventEditor.ButtonValueLabel = new GUIContent("Button Value") static private
Definition at line 21 of file ButtonEventEditor.cs.
Referenced by Juniper.Events.ButtonEventEditor.OnInspectorGUI().
FIELD_ONCLICK
const string Juniper.Events.ButtonEventEditor.FIELD_ONCLICK = nameof(_.onClick) private
Definition at line 14 of file ButtonEventEditor.cs.
Referenced by Juniper.Events.ButtonEventEditor.OnInspectorGUI().
FIELD_ONDOUBLECLICK
const string Juniper.Events.ButtonEventEditor.FIELD_ONDOUBLECLICK = nameof(_.onDoubleClick) private
Definition at line 15 of file ButtonEventEditor.cs.
Referenced by Juniper.Events.ButtonEventEditor.OnInspectorGUI().
FIELD_ONDOWN
const string Juniper.Events.ButtonEventEditor.FIELD_ONDOWN = nameof(_.onDown) private
Definition at line 17 of file ButtonEventEditor.cs.
Referenced by Juniper.Events.ButtonEventEditor.OnInspectorGUI().
FIELD_ONLONGPRESS
const string Juniper.Events.ButtonEventEditor.FIELD_ONLONGPRESS = nameof(_.onLongPress) private
Definition at line 16 of file ButtonEventEditor.cs.
Referenced by Juniper.Events.ButtonEventEditor.OnInspectorGUI().
FIELD_ONUP
const string Juniper.Events.ButtonEventEditor.FIELD_ONUP = nameof(_.onUp) private
Definition at line 18 of file ButtonEventEditor.cs.
Referenced by Juniper.Events.ButtonEventEditor.OnInspectorGUI().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/Events/ButtonEventEditor.cs