Juniper: Juniper.Unity.Input.Speech.KeywordRecognizer Class Reference
Juniper.Unity.Input.Speech.KeywordRecognizer Class Reference
A class that implements basic functionality for systems that manage speech recognition and route out the events associated with recognizing keywords.
Public Member Functions
void RefreshKeywords ()
Find all of the keyword-responding components that are currently active in the scene, collect up their keywords, and register them return them as a set-array to be registered with the speech recognition system.
void OnEnable ()
Initialize the speech recognition system.
void OnDisable ()
Tear down the speech recognition system.
Public Attributes
const bool IsAvailable = true
Reads as true if the current XR subsystem supports speech recognition.
StringEvent onKeywordRecognized = new StringEvent()
Respond to the speech recognition system having detected a keyword. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr KeywordRecognized.
Protected Member Functions
void OnKeywordRecognized (string keyword)
Invokes onKeywordRecognized and KeywordRecognized.
Protected Attributes
string [] keywords
The keywords for which to listen.
Events
EventHandler< KeywordRecognizedEventArgs > KeywordRecognized
Respond to the speech recognition system having detected a keyword. You should only use this version if you are programmatically attaching event listeners. If you are attaching events in the Unity Editor, you should preferr onKeywordRecognized.
Private Member Functions
void Recognizer_OnPhraseRecognized (UnityEngine.Windows.Speech.PhraseRecognizedEventArgs args)
When speech is recognized, forward it into the keyword recognizer.
Private Attributes
UnityEngine.Windows.Speech.KeywordRecognizer recognizer
The real recognizer.
Detailed Description
A class that implements basic functionality for systems that manage speech recognition and route out the events associated with recognizing keywords.
Definition at line 15 of file KeywordRecognizer.cs.
Member Function Documentation
OnDisable()
void Juniper.Unity.Input.Speech.KeywordRecognizer.OnDisable () inline
Tear down the speech recognition system.
Definition at line 114 of file KeywordRecognizer.cs.
         {
 #if UNITY_WSA
             if (recognizer != null)
             {
                 recognizer.OnPhraseRecognized -= Recognizer_OnPhraseRecognized;
                 recognizer.Stop();
                 recognizer.Dispose();
                 recognizer = null;
             }
 #endif
         }
References Juniper.Unity.Input.Speech.KeywordRecognizer.recognizer, and Juniper.Unity.Input.Speech.KeywordRecognizer.Recognizer_OnPhraseRecognized().
Referenced by Juniper.Unity.Input.Speech.KeywordRecognizer.OnEnable().
OnEnable()
void Juniper.Unity.Input.Speech.KeywordRecognizer.OnEnable () inline
Initialize the speech recognition system.
Definition at line 97 of file KeywordRecognizer.cs.
         {
 #if UNITY_WSA
             OnDisable();
             if (keywords != null && keywords.Length > 0)
             {
                 recognizer = new UnityEngine.Windows.Speech.KeywordRecognizer(keywords);
                 recognizer.OnPhraseRecognized += Recognizer_OnPhraseRecognized;
                 recognizer.Start();
             }
 #endif
         }
References Juniper.Unity.Input.Speech.KeywordRecognizer.keywords, Juniper.Unity.Input.Speech.KeywordRecognizer.OnDisable(), Juniper.Unity.Input.Speech.KeywordRecognizer.recognizer, and Juniper.Unity.Input.Speech.KeywordRecognizer.Recognizer_OnPhraseRecognized().
OnKeywordRecognized()
void Juniper.Unity.Input.Speech.KeywordRecognizer.OnKeywordRecognized (string keyword) inline protected
Invokes onKeywordRecognized and KeywordRecognized.
Parameters
keyword Keyword.
Definition at line 63 of file KeywordRecognizer.cs.
         {
             onKeywordRecognized?.Invoke(keyword);
             KeywordRecognized?.Invoke(this, new KeywordRecognizedEventArgs(keyword));
         }
References Juniper.Unity.Input.Speech.KeywordRecognizer.KeywordRecognized, and Juniper.Unity.Input.Speech.KeywordRecognizer.onKeywordRecognized.
Referenced by Juniper.Unity.Input.Speech.KeywordRecognizer.Recognizer_OnPhraseRecognized().
Recognizer_OnPhraseRecognized()
void Juniper.Unity.Input.Speech.KeywordRecognizer.Recognizer_OnPhraseRecognized (UnityEngine.Windows.Speech.PhraseRecognizedEventArgs args) inline private
When speech is recognized, forward it into the keyword recognizer.
Parameters
args Arguments.
Definition at line 37 of file KeywordRecognizer.cs.
         {
             OnKeywordRecognized(args.text);
         }
References Juniper.Unity.Input.Speech.KeywordRecognizer.OnKeywordRecognized().
Referenced by Juniper.Unity.Input.Speech.KeywordRecognizer.OnDisable(), and Juniper.Unity.Input.Speech.KeywordRecognizer.OnEnable().
RefreshKeywords()
void Juniper.Unity.Input.Speech.KeywordRecognizer.RefreshKeywords () inline
Find all of the keyword-responding components that are currently active in the scene, collect up their keywords, and register them return them as a set-array to be registered with the speech recognition system.
Returns
The active keywords.
Definition at line 75 of file KeywordRecognizer.cs.
         {
             this.WithLock(() =>
             {
                 keywords = (from comp in Resources.FindObjectsOfTypeAll<MonoBehaviour>()
                             where (Application.isPlaying || comp.gameObject.scene.isLoaded)
                             && comp is IKeywordTriggered
                             let trigger = (IKeywordTriggered)comp
                             where trigger.Keywords != null
                             from keyword in trigger.Keywords
                             where !string.IsNullOrEmpty(keyword)
                             select keyword)
                 .Distinct()
                 .ToArray();
                 Array.Sort(keywords);
             });
         }
References Juniper.Input.Speech.IKeywordTriggered.Keywords, and Juniper.Unity.Input.Speech.KeywordRecognizer.keywords.
Referenced by Juniper.Unity.Input.Speech.Keywordable.OnEnable().
Member Data Documentation
IsAvailable
const bool Juniper.Unity.Input.Speech.KeywordRecognizer.IsAvailable = true
Reads as true if the current XR subsystem supports speech recognition.
Definition at line 26 of file KeywordRecognizer.cs.
keywords
string [] Juniper.Unity.Input.Speech.KeywordRecognizer.keywords protected
The keywords for which to listen.
Definition at line 20 of file KeywordRecognizer.cs.
Referenced by Juniper.Unity.Input.Speech.KeywordRecognizer.OnEnable(), and Juniper.Unity.Input.Speech.KeywordRecognizer.RefreshKeywords().
onKeywordRecognized
StringEvent Juniper.Unity.Input.Speech.KeywordRecognizer.onKeywordRecognized = new StringEvent()
Respond to the speech recognition system having detected a keyword. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr KeywordRecognized.
Definition at line 50 of file KeywordRecognizer.cs.
Referenced by Juniper.Unity.Input.Speech.KeywordRecognizer.OnKeywordRecognized(), and Juniper.Unity.Input.Speech.Keywordable.Start().
recognizer
UnityEngine.Windows.Speech.KeywordRecognizer Juniper.Unity.Input.Speech.KeywordRecognizer.recognizer private
The real recognizer.
Definition at line 31 of file KeywordRecognizer.cs.
Referenced by Juniper.Unity.Input.Speech.KeywordRecognizer.OnDisable(), and Juniper.Unity.Input.Speech.KeywordRecognizer.OnEnable().
Event Documentation
KeywordRecognized
EventHandler<KeywordRecognizedEventArgs> Juniper.Unity.Input.Speech.KeywordRecognizer.KeywordRecognized
Respond to the speech recognition system having detected a keyword. You should only use this version if you are programmatically attaching event listeners. If you are attaching events in the Unity Editor, you should preferr onKeywordRecognized.
Definition at line 57 of file KeywordRecognizer.cs.
Referenced by Juniper.Unity.Input.Speech.KeywordRecognizer.OnKeywordRecognized().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Speech/KeywordRecognizer.cs