Juniper: Juniper.SerializedPropertyExt Class Reference
Juniper.SerializedPropertyExt Class Reference
Static Public Member Functions
static void SetValue< T > (this SerializedProperty property, T value)
static T GetObject< T > (this SerializedProperty property)
static T GetScriptableObject< T > (this SerializedProperty property)
Static Private Member Functions
static FieldInfo object object Parent GetObject (SerializedProperty property)
Static Private Attributes
static readonly Regex arrayIndexPattern = new Regex("data\\[(\\w+)\\]", RegexOptions.Compiled)
The array index pattern.
static FieldInfo Field
static FieldInfo object Object
Detailed Description
Definition at line 11 of file SerializedPropertyExt.cs.
Member Function Documentation
GetObject()
static FieldInfo object object Parent Juniper.SerializedPropertyExt.GetObject (SerializedProperty property) inline static private
Definition at line 70 of file SerializedPropertyExt.cs.
         {
             object head = property.serializedObject.targetObject;
             var parts = property.propertyPath.Split('.');
             for (var i = 0; i < parts.Length && head != null; ++i)
             {
                 var part = parts[i];
                 if (part == "Array")
                 {
                     var indexStr = parts[++i];
                     var match = arrayIndexPattern.Match(indexStr);
                     var index = int.Parse(match.Groups[1].Value, CultureInfo.InvariantCulture);
                     var arr = (object[])head;
                     if (0 <= index && index < arr.Length)
                     {
                         head = arr[index];
                     }
                     else
                     {
                         head = null;
                     }
                 }
                 else
                 {
                     var type = head.GetType();
                     var field = type.GetField(part, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
                     var parent = head;
                     head = field.GetValue(head);
                     if (i == parts.Length - 1)
                     {
                         return (field, head, parent);
                     }
                 }
             }
             return default;
         }
Referenced by Juniper.SerializedPropertyExt.GetObject< T >(), Juniper.SerializedPropertyExt.GetScriptableObject< T >(), and Juniper.SerializedPropertyExt.SetValue< T >().
GetObject< T >()
static T Juniper.SerializedPropertyExt.GetObject< T > (this SerializedProperty property) inline static
Definition at line 29 of file SerializedPropertyExt.cs.
         {
             if (property is null)
             {
                 throw new System.ArgumentNullException(nameof(property));
             }
             var obj = GetObject(property);
             if (obj == default || obj.Object == default)
             {
                 return default;
             }
             else
             {
                 return (T)obj.Object;
             }
         }
References Juniper.SerializedPropertyExt.GetObject().
GetScriptableObject< T >()
static T Juniper.SerializedPropertyExt.GetScriptableObject< T > (this SerializedProperty property) inline static
Type Constraints
T : ScriptableObject
Definition at line 47 of file SerializedPropertyExt.cs.
                                                                                          : ScriptableObject
         {
             if (property is null)
             {
                 throw new System.ArgumentNullException(nameof(property));
             }
             var obj = GetObject(property);
             if (obj == default || obj.Object == default)
             {
                 return ScriptableObject.CreateInstance<T>();
             }
             else
             {
                 return (T)obj.Object;
             }
         }
References Juniper.SerializedPropertyExt.GetObject().
SetValue< T >()
static void Juniper.SerializedPropertyExt.SetValue< T > (this SerializedProperty property, T value) inline static
Definition at line 13 of file SerializedPropertyExt.cs.
         {
             if (property is null)
             {
                 throw new System.ArgumentNullException(nameof(property));
             }
             var obj = GetObject(property);
             if (obj != default
                 && obj.Parent != default
                 && obj.Object != default)
             {
                 obj.Field.SetValue(obj.Parent, value);
             }
         }
References Juniper.SerializedPropertyExt.GetObject().
Member Data Documentation
arrayIndexPattern
readonly Regex Juniper.SerializedPropertyExt.arrayIndexPattern = new Regex("data\\[(\\w+)\\]", RegexOptions.Compiled) static private
The array index pattern.
Definition at line 68 of file SerializedPropertyExt.cs.
Field
FieldInfo Juniper.SerializedPropertyExt.Field static private
Definition at line 70 of file SerializedPropertyExt.cs.
Object
FieldInfo object Juniper.SerializedPropertyExt.Object static private
Definition at line 70 of file SerializedPropertyExt.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.UnityEditor/SerializedPropertyExt.cs