import { Color, LineBasicMaterial, LineBasicMaterialParameters, Material, MeshBasicMaterial, MeshBasicMaterialParameters, MeshPhongMaterial, MeshPhongMaterialParameters, MeshPhysicalMaterial, MeshStandardMaterial, Object3D, ShaderMaterial, ShaderMaterialParameters, SpriteMaterial, SpriteMaterialParameters } from "three";
import { LineMaterial, LineMaterialParameters } from "./examples/lines/LineMaterial";
export type SolidMaterial = MeshBasicMaterial | MeshPhongMaterial | ShaderMaterial;
export type SolidMaterialOpts = MeshBasicMaterialParameters | MeshPhongMaterialParameters | ShaderMaterialParameters;
export declare function solid(options: MeshBasicMaterialParameters): MeshBasicMaterial;
export declare function solidTransparent(options: MeshBasicMaterialParameters): MeshBasicMaterial;
export declare function lit(options: MeshPhongMaterialParameters): MeshPhongMaterial;
export declare function litTransparent(options: MeshPhongMaterialParameters): MeshPhongMaterial;
export declare function line(options: LineBasicMaterialParameters): LineBasicMaterial;
export declare function lineTransparent(options: LineBasicMaterialParameters): LineBasicMaterial;
export declare function line2(options: LineMaterialParameters): LineMaterial;
export declare function sprite(options: SpriteMaterialParameters): SpriteMaterial;
export declare function spriteTransparent(options: SpriteMaterialParameters): SpriteMaterial;
export type MaterialConverter<OldMatT extends Material, NewMatT extends Material> = (oldMat: OldMatT) => NewMatT;
export declare function convertMaterials<OldMatT extends Material, NewMatT extends Material>(root: Object3D, convertMaterial: MaterialConverter<OldMatT, NewMatT>): void;
export declare function materialStandardToBasic(oldMat: MeshStandardMaterial): MeshBasicMaterial;
export declare function materialStandardToPhong(oldMat: MeshStandardMaterial): MeshPhongMaterial;
export declare function materialPhongToBasic(oldMat: MeshPhongMaterial): MeshBasicMaterial;
export declare function materialPhysicalToPhong(oldMat: MeshPhysicalMaterial): MeshPhongMaterial;
export type ColorOpts = (Color | number | string);
export declare const black = 0;
export declare const blue = 255;
export declare const green = 65280;
export declare const cyan = 65535;
export declare const red = 16711680;
export declare const magenta = 16711935;
export declare const yellow = 16776960;
export declare const grey = 12632256;
export declare const white = 16777215;
export declare const colorBlack: Color;
export declare const colorBlue: Color;
export declare const colorGreen: Color;
export declare const colorCyan: Color;
export declare const colorRed: Color;
export declare const colorMagenta: Color;
export declare const colorYellow: Color;
export declare const colorGrey: Color;
export declare const colorWhite: Color;
export declare const solidBlack: MeshBasicMaterial;
export declare const solidBlue: MeshBasicMaterial;
export declare const solidGreen: MeshBasicMaterial;
export declare const solidCyan: MeshBasicMaterial;
export declare const solidRed: MeshBasicMaterial;
export declare const solidMagenta: MeshBasicMaterial;
export declare const solidYellow: MeshBasicMaterial;
export declare const solidGrey: MeshBasicMaterial;
export declare const solidWhite: MeshBasicMaterial;
export declare function solidTransparentBlack(opacity: number): MeshBasicMaterial;
export declare function solidTransparentBlue(opacity: number): MeshBasicMaterial;
export declare function solidTransparentGreen(opacity: number): MeshBasicMaterial;
export declare function solidTransparentCyan(opacity: number): MeshBasicMaterial;
export declare function solidTransparentRed(opacity: number): MeshBasicMaterial;
export declare function solidTransparentMagenta(opacity: number): MeshBasicMaterial;
export declare function solidTransparentYellow(opacity: number): MeshBasicMaterial;
export declare function solidTransparentGrey(opacity: number): MeshBasicMaterial;
export declare function solidTransparentWhite(opacity: number): MeshBasicMaterial;
export declare const litBlack: MeshPhongMaterial;
export declare const litBlue: MeshPhongMaterial;
export declare const litGreen: MeshPhongMaterial;
export declare const litCyan: MeshPhongMaterial;
export declare const litRed: MeshPhongMaterial;
export declare const litMagenta: MeshPhongMaterial;
export declare const litYellow: MeshPhongMaterial;
export declare const litGrey: MeshPhongMaterial;
export declare const litWhite: MeshPhongMaterial;
export declare function litTransparentBlack(opacity: number): MeshPhongMaterial;
export declare function litTransparentBlue(opacity: number): MeshPhongMaterial;
export declare function litTransparentGreen(opacity: number): MeshPhongMaterial;
export declare function litTransparentCyan(opacity: number): MeshPhongMaterial;
export declare function litTransparentRed(opacity: number): MeshPhongMaterial;
export declare function litTransparentMagenta(opacity: number): MeshPhongMaterial;
export declare function litTransparentYellow(opacity: number): MeshPhongMaterial;
export declare function litTransparentGrey(opacity: number): MeshPhongMaterial;
export declare function litTransparentWhite(opacity: number): MeshPhongMaterial;
export declare const lineBlack: LineBasicMaterial;
export declare const lineBlue: LineBasicMaterial;
export declare const lineGreen: LineBasicMaterial;
export declare const lineCyan: LineBasicMaterial;
export declare const lineRed: LineBasicMaterial;
export declare const lineMagenta: LineBasicMaterial;
export declare const lineYellow: LineBasicMaterial;
export declare const lineGrey: LineBasicMaterial;
export declare const lineWhite: LineBasicMaterial;
export declare function lineTransparentBlack(opacity: number): LineBasicMaterial;
export declare function lineTransparentBlue(opacity: number): LineBasicMaterial;
export declare function lineTransparentGreen(opacity: number): LineBasicMaterial;
export declare function lineTransparentCyan(opacity: number): LineBasicMaterial;
export declare function lineTransparentRed(opacity: number): LineBasicMaterial;
export declare function lineTransparentMagenta(opacity: number): LineBasicMaterial;
export declare function lineTransparentYellow(opacity: number): LineBasicMaterial;
export declare function lineTransparentGrey(opacity: number): LineBasicMaterial;
export declare function lineTransparentWhite(opacity: number): LineBasicMaterial;
export declare const spriteBlack: SpriteMaterial;
export declare const spriteBlue: SpriteMaterial;
export declare const spriteGreen: SpriteMaterial;
export declare const spriteCyan: SpriteMaterial;
export declare const spriteRed: SpriteMaterial;
export declare const spriteMagenta: SpriteMaterial;
export declare const spriteYellow: SpriteMaterial;
export declare const spriteGrey: SpriteMaterial;
export declare const spriteWhite: SpriteMaterial;
export declare function spriteTransparentBlack(opacity: number): SpriteMaterial;
export declare function spriteTransparentBlue(opacity: number): SpriteMaterial;
export declare function spriteTransparentGreen(opacity: number): SpriteMaterial;
export declare function spriteTransparentCyan(opacity: number): SpriteMaterial;
export declare function spriteTransparentRed(opacity: number): SpriteMaterial;
export declare function spriteTransparentMagenta(opacity: number): SpriteMaterial;
export declare function spriteTransparentYellow(opacity: number): SpriteMaterial;
export declare function spriteTransparentGrey(opacity: number): SpriteMaterial;
export declare function spriteTransparentWhite(opacity: number): SpriteMaterial;
//# sourceMappingURL=materials.d.ts.map