Juniper: Juniper.Unity.Input.Pointers.IProbe Interface Reference
Juniper.Unity.Input.Pointers.IProbe Interface Reference
Public Member Functions
void AlignProbe (Vector3 dir, Vector3 up)
void SetCursor (bool targeted, bool pressed, Vector3 targetPosition, Vector3 targetForward)
void SetGaze (float gazeProgress)
void Destroy ()
void SetActive (bool active)
Properties
Transform Cursor [get]
PhysicsRaycaster Raycaster [get]
Vector2 TouchPoint [get, set]
Material LaserPointerMaterial [get, set]
bool CanGaze [get, set]
Detailed Description
Definition at line 6 of file IProbe.cs.
Member Function Documentation
AlignProbe()
void Juniper.Unity.Input.Pointers.IProbe.AlignProbe (Vector3 dir, Vector3 up)
Implemented in Juniper.Unity.Input.Pointers.Probe.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
Destroy()
void Juniper.Unity.Input.Pointers.IProbe.Destroy ()
Implemented in Juniper.Unity.Input.Pointers.Probe.
SetActive()
void Juniper.Unity.Input.Pointers.IProbe.SetActive (bool active)
Implemented in Juniper.Unity.Input.Pointers.Probe.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
SetCursor()
void Juniper.Unity.Input.Pointers.IProbe.SetCursor (bool targeted, bool pressed, Vector3 targetPosition, Vector3 targetForward)
Implemented in Juniper.Unity.Input.Pointers.Probe.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
SetGaze()
void Juniper.Unity.Input.Pointers.IProbe.SetGaze (float gazeProgress)
Implemented in Juniper.Unity.Input.Pointers.Probe.
Property Documentation
CanGaze
bool Juniper.Unity.Input.Pointers.IProbe.CanGaze get set
Definition at line 31 of file IProbe.cs.
         {
             get;
             set;
         }
Cursor
Transform Juniper.Unity.Input.Pointers.IProbe.Cursor get
Definition at line 9 of file IProbe.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
LaserPointerMaterial
Material Juniper.Unity.Input.Pointers.IProbe.LaserPointerMaterial get set
Definition at line 25 of file IProbe.cs.
         {
             get;
             set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
Raycaster
PhysicsRaycaster Juniper.Unity.Input.Pointers.IProbe.Raycaster get
Definition at line 14 of file IProbe.cs.
         {
             get;
         }
TouchPoint
Vector2 Juniper.Unity.Input.Pointers.IProbe.TouchPoint get set
Definition at line 19 of file IProbe.cs.
         {
             get;
             set;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate().
The documentation for this interface was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Pointers/IProbe.cs