Juniper: Juniper.IO.IDeserializerGenericExt Class Reference
Juniper.IO.IDeserializerGenericExt Class Reference
Static Public Member Functions
static ResultT Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, Stream stream, long length, IProgress prog)
static ResultT Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, byte[] data, IProgress prog=null)
static ResultT Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, FileInfo file, IProgress prog=null)
static ResultT Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, string fileName, IProgress prog=null)
static ResultT Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, IReadOnlyCollection< byte > data, IProgress prog=null)
static ResultT Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpWebResponse response, IProgress prog=null)
static ResultT Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpListenerRequest request, IProgress prog=null)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpWebResponse response, out ResultT value, IProgress prog=null)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpListenerRequest request, out ResultT value, IProgress prog=null)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, Stream stream, out ResultT value)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, Stream stream, out ResultT value, long length, IProgress prog=null)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, byte[] data, out ResultT value, IProgress prog=null)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, IReadOnlyCollection< byte > data, out ResultT value, IProgress prog=null)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, FileInfo file, out ResultT value, IProgress prog=null)
static bool TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, string fileName, out ResultT value, IProgress prog=null)
static ResultT Parse< ResultT > (this IDeserializer< ResultT > deserializer, string text, IProgress prog=null)
static bool TryParse< ResultT > (this IDeserializer< ResultT > deserializer, string text, out ResultT value, IProgress prog=null)
Detailed Description
Definition at line 11 of file IDeserializerGenericExt.cs.
Member Function Documentation
Deserialize< ResultT >() [1/7]
static ResultT Juniper.IO.IDeserializerGenericExt.Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, Stream stream, long length, IProgress prog) inline static
Definition at line 13 of file IDeserializerGenericExt.cs.
         {
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             using var progStream = new ProgressStream(stream, length, prog, false);
             return deserializer.Deserialize(progStream);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
Deserialize< ResultT >() [2/7]
static ResultT Juniper.IO.IDeserializerGenericExt.Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, byte [] data, IProgress prog = null) inline static
Definition at line 29 of file IDeserializerGenericExt.cs.
         {
             if (data is null)
             {
                 throw new ArgumentNullException(nameof(data));
             }
             using var stream = new MemoryStream(data);
             return deserializer.Deserialize(stream, data.Length, prog);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
Deserialize< ResultT >() [3/7]
static ResultT Juniper.IO.IDeserializerGenericExt.Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, FileInfo file, IProgress prog = null) inline static
Definition at line 40 of file IDeserializerGenericExt.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             if (!file.Exists)
             {
                 throw new FileNotFoundException("File not found!", file.FullName);
             }
             using var stream = file.OpenRead();
             return deserializer.Deserialize(stream, file.Length, prog);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
Deserialize< ResultT >() [4/7]
static ResultT Juniper.IO.IDeserializerGenericExt.Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, string fileName, IProgress prog = null) inline static
Definition at line 56 of file IDeserializerGenericExt.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return deserializer.Deserialize(new FileInfo(fileName), prog);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
Deserialize< ResultT >() [5/7]
static ResultT Juniper.IO.IDeserializerGenericExt.Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, IReadOnlyCollection< byte > data, IProgress prog = null) inline static
Definition at line 71 of file IDeserializerGenericExt.cs.
         {
             if (data is null)
             {
                 throw new ArgumentNullException(nameof(data));
             }
             return deserializer.Deserialize(data.ToArray(), prog);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
Deserialize< ResultT >() [6/7]
static ResultT Juniper.IO.IDeserializerGenericExt.Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpWebResponse response, IProgress prog = null) inline static
Definition at line 81 of file IDeserializerGenericExt.cs.
         {
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             using var stream = response.GetResponseStream();
             return deserializer.Deserialize(stream, response.ContentLength, prog);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
Deserialize< ResultT >() [7/7]
static ResultT Juniper.IO.IDeserializerGenericExt.Deserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpListenerRequest request, IProgress prog = null) inline static
Definition at line 97 of file IDeserializerGenericExt.cs.
         {
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             using var stream = request.InputStream;
             return deserializer.Deserialize(stream, request.ContentLength64, prog);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
Parse< ResultT >()
static ResultT Juniper.IO.IDeserializerGenericExt.Parse< ResultT > (this IDeserializer< ResultT > deserializer, string text, IProgress prog = null) inline static
Definition at line 224 of file IDeserializerGenericExt.cs.
         {
             if (text is null)
             {
                 throw new ArgumentNullException(nameof(text));
             }
             using var stream = new MemoryStream(Encoding.UTF8.GetBytes(text));
             return deserializer.Deserialize(stream, stream.Length, prog);
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
TryDeserialize< ResultT >() [1/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpWebResponse response, out ResultT value, IProgress prog = null) inline static
Definition at line 113 of file IDeserializerGenericExt.cs.
         {
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             using var stream = response.GetResponseStream();
             return deserializer.TryDeserialize(stream, out value, response.ContentLength, prog);
         }
TryDeserialize< ResultT >() [2/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, HttpListenerRequest request, out ResultT value, IProgress prog = null) inline static
Definition at line 129 of file IDeserializerGenericExt.cs.
         {
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             using var stream = request.InputStream;
             return deserializer.TryDeserialize(stream, out value, request.ContentLength64, prog);
         }
TryDeserialize< ResultT >() [3/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, Stream stream, out ResultT value) inline static
Definition at line 145 of file IDeserializerGenericExt.cs.
         {
             if (deserializer is null)
             {
                 throw new ArgumentNullException(nameof(deserializer));
             }
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             try
             {
                 value = deserializer.Deserialize(stream);
                 return true;
             }
 #pragma warning disable CA1031 // Do not catch general exception types
             catch
             {
                 value = default;
                 return false;
             }
 #pragma warning restore CA1031 // Do not catch general exception types
         }
References Juniper.IO.IDeserializer< out out ResultT >.Deserialize().
TryDeserialize< ResultT >() [4/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, Stream stream, out ResultT value, long length, IProgress prog = null) inline static
Definition at line 171 of file IDeserializerGenericExt.cs.
         {
             using var progStream = new ProgressStream(stream, length, prog, false);
             return deserializer.TryDeserialize(progStream, out value);
         }
TryDeserialize< ResultT >() [5/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, byte [] data, out ResultT value, IProgress prog = null) inline static
Definition at line 177 of file IDeserializerGenericExt.cs.
         {
             if (data is null)
             {
                 throw new ArgumentNullException(nameof(data));
             }
             using var stream = new MemoryStream(data);
             return deserializer.TryDeserialize(stream, out value, data.Length, prog);
         }
TryDeserialize< ResultT >() [6/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, IReadOnlyCollection< byte > data, out ResultT value, IProgress prog = null) inline static
Definition at line 188 of file IDeserializerGenericExt.cs.
         {
             if (data is null)
             {
                 throw new ArgumentNullException(nameof(data));
             }
             return deserializer.TryDeserialize(data.ToArray(), out value, prog);
         }
TryDeserialize< ResultT >() [7/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, FileInfo file, out ResultT value, IProgress prog = null) inline static
Definition at line 198 of file IDeserializerGenericExt.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             using var stream = file.OpenRead();
             return deserializer.TryDeserialize(stream, out value, file.Length, prog);
         }
TryDeserialize< ResultT >() [8/8]
static bool Juniper.IO.IDeserializerGenericExt.TryDeserialize< ResultT > (this IDeserializer< ResultT > deserializer, string fileName, out ResultT value, IProgress prog = null) inline static
Definition at line 209 of file IDeserializerGenericExt.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return deserializer.TryDeserialize(new FileInfo(fileName), out value, prog);
         }
TryParse< ResultT >()
static bool Juniper.IO.IDeserializerGenericExt.TryParse< ResultT > (this IDeserializer< ResultT > deserializer, string text, out ResultT value, IProgress prog = null) inline static
Definition at line 235 of file IDeserializerGenericExt.cs.
         {
             if (text is null)
             {
                 throw new ArgumentNullException(nameof(text));
             }
             using var stream = new MemoryStream(Encoding.UTF8.GetBytes(text));
             return deserializer.TryDeserialize(stream, out value, stream.Length, prog);
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/IDeserializerGenericExt.cs