Juniper: Juniper.ConfigurationManagement.Platforms Class Reference
Juniper.ConfigurationManagement.Platforms Class Reference
Public Member Functions
void GetObjectData (SerializationInfo info, StreamingContext context)
Static Public Member Functions
static Platforms Load ()
Properties
IReadOnlyList< PackageReference > Packages [get]
IReadOnlyDictionary< PlatformType, PlatformConfiguration > Configurations [get]
Private Member Functions
Platforms (SerializationInfo info, StreamingContext context)
Static Private Attributes
static Platforms platforms
Detailed Description
Definition at line 13 of file Platforms.cs.
Constructor & Destructor Documentation
Platforms()
Juniper.ConfigurationManagement.Platforms.Platforms (SerializationInfo info, StreamingContext context) inline private
Definition at line 33 of file Platforms.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Packages = info.GetValue<string[]>(nameof(Packages))
                 .Select(str => new PackageReference(str))
                 .ToArray();
             Configurations = info.GetValue<PlatformConfiguration[]>(nameof(Configurations))
                 .ToDictionary(c => c.Name);
         }
References Juniper.ConfigurationManagement.Platforms.Configurations, and Juniper.ConfigurationManagement.Platforms.Packages.
Member Function Documentation
GetObjectData()
void Juniper.ConfigurationManagement.Platforms.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 47 of file Platforms.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(nameof(Packages), Packages.Select(p => p.PackageSpec).ToArray());
             info.AddValue(nameof(Configurations), Configurations.Values.ToArray());
         }
References Juniper.ConfigurationManagement.Platforms.Configurations, and Juniper.ConfigurationManagement.Platforms.Packages.
Load()
static Platforms Juniper.ConfigurationManagement.Platforms.Load () inline static
Definition at line 16 of file Platforms.cs.
         {
             if (platforms is null)
             {
                 var configFactory = new JsonFactory<Platforms>();
                 var juniperPlatformsFileName = Path.Combine(Project.JuniperAssetPath, "platforms.json");
                 platforms = configFactory.Deserialize(juniperPlatformsFileName);
             }
             return platforms;
         }
References Juniper.ConfigurationManagement.Project.JuniperAssetPath, and Juniper.ConfigurationManagement.Platforms.platforms.
Referenced by Juniper.ConfigurationManagement.JuniperPlatformSelector.OnGUI(), Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.OnGUI(), Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI(), Juniper.ConfigurationManagement.JuniperOptionalPackageManager.OnGUI(), and Juniper.ConfigurationManagement.JuniperInstalledPackageManager.OnGUI().
Member Data Documentation
platforms
Platforms Juniper.ConfigurationManagement.Platforms.platforms static private
Definition at line 15 of file Platforms.cs.
Referenced by Juniper.ConfigurationManagement.Platforms.Load().
Property Documentation
Configurations
IReadOnlyDictionary<PlatformType, PlatformConfiguration> Juniper.ConfigurationManagement.Platforms.Configurations get
Definition at line 30 of file Platforms.cs.
 { get; }
Referenced by Juniper.ConfigurationManagement.JuniperPlatformSelector.DrawStatus(), Juniper.ConfigurationManagement.Platforms.GetObjectData(), and Juniper.ConfigurationManagement.Platforms.Platforms().
Packages
IReadOnlyList<PackageReference> Juniper.ConfigurationManagement.Platforms.Packages get
Definition at line 28 of file Platforms.cs.
 { get; }
Referenced by Juniper.ConfigurationManagement.Platforms.GetObjectData(), and Juniper.ConfigurationManagement.Platforms.Platforms().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.UnityEditor/ConfigurationManagement/Platforms.cs