Juniper: Hjg.Pngcs.PngWriter Class Reference
Hjg.Pngcs.PngWriter Class Reference
Writes a PNG image, line by line.
Public Member Functions
PngWriter (Stream outputStream, ImageInfo imgInfo)
Constructs a PngWriter from a outputStream, with no filename information
PngWriter (Stream outputStream, ImageInfo imgInfo, string filename)
Constructs a PngWriter from a outputStream, with optional filename or description
void CopyChunksFirst (PngReader reader, int copy_mask)
void CopyChunksLast (PngReader reader, int copy_mask)
double ComputeCompressionRatio ()
Computes compressed size/raw size, approximate
void End ()
Finalizes the image creation and closes the file stream.
string GetFilename ()
Filename or description, from the optional constructor argument.
void WriteRow (ImageLine imgline, int rownumber)
this uses the row number from the imageline!
void WriteRow (int[] newrow)
void WriteRow (int[] newrow, int rown)
void WriteRowInt (int[] newrow, int rown)
Writes a full image row.
void WriteRowByte (byte[] newrow, int rown)
void WriteRowsInt (int[][] image)
void WriteRowsByte (byte[][] image)
PngMetadata GetMetadata ()
ChunksListForWrite GetChunksList ()
void SetFilterType (FilterType filterType)
Sets internal prediction filter type, or strategy to choose it.
void SetUseUnPackedMode (bool useUnpackedMode)
void Dispose ()
Properties
ImageInfo ImgInfo [get]
Basic image info, inmutable
EDeflateCompressStrategy CompressionStrategy [get, set]
int CompLevel [get, set]
zip compression level (0 - 9)
bool ShouldCloseStream [get, set]
true: closes stream after ending write
int IdatMaxSize [get, set]
Maximum size of IDAT chunks
int CurrentChunkGroup [get, private set]
number of chunk group (0-6) last writen, or currently writing
Private Member Functions
void Init ()
init: is called automatically before writing the first row
void ReportResultsForFilter (int rown, FilterType type, bool tentative)
void WriteEndChunk ()
void WriteFirstChunks ()
void WriteLastChunks ()
void WriteSignatureAndIHDR ()
Write id signature and also "IHDR" chunk
void EncodeRowFromByte (byte[] row)
void EncodeRowFromInt (int[] row)
void FilterRow (int rown)
void PrepareEncodeRow (int rown)
void FilterAndSend (int rown)
void FilterRowAverage ()
void FilterRowNone ()
void FilterRowPaeth ()
void FilterRowSub ()
void FilterRowUp ()
void CopyChunks (PngReader reader, int copy_mask, bool onlyAfterIdat)
copy chunks from reader - copy_mask : see ChunksToWrite.COPY_XXX If we are after idat, only considers those chunks after IDAT in PngReader TODO: this should be more customizable
void Dispose (bool disposing)
Private Attributes
readonly string filename
filename, or description - merely informative, can be empty
FilterWriteStrategy filterStrat
readonly PngMetadata metadata
A high level wrapper of a ChunksList : list of written/queued chunks
readonly ChunksListForWrite chunksList
written/queued chunks
byte [] rowb
raw current row, as array of bytes,counting from 1 (index 0 is reserved for filter type)
byte [] rowbprev
previuos raw row
readonly byte [] rowbfilter
raw current row, after filtered
int rowNum = -1
readonly Stream outputStream
PngIDatChunkOutputStream datStream
AZlibOutputStream datStreamDeflated
readonly int [] histox = new int[256]
bool unpackedMode
bool needsPack
bool disposedValue = false
Detailed Description
Writes a PNG image, line by line.
Definition at line 13 of file PngWriter.cs.
Constructor & Destructor Documentation
PngWriter() [1/2]
Hjg.Pngcs.PngWriter.PngWriter (Stream outputStream, ImageInfo imgInfo) inline
Constructs a PngWriter from a outputStream, with no filename information
Parameters
outputStream
imgInfo
Definition at line 104 of file PngWriter.cs.
             : this(outputStream, imgInfo, "[NO FILENAME AVAILABLE]")
         {
         }
PngWriter() [2/2]
Hjg.Pngcs.PngWriter.PngWriter (Stream outputStream, ImageInfo imgInfo, string filename) inline
Constructs a PngWriter from a outputStream, with optional filename or description
After construction nothing is writen yet. You still can set some parameters (compression, filters) and queue chunks before start writing the pixels.
See also FileHelper.createPngWriter()
Parameters
outputStream Opened stream for binary writing
imgInfo Basic image parameters
filename Optional, can be the filename or a description.
Definition at line 122 of file PngWriter.cs.
         {
             this.outputStream = outputStream ?? throw new ArgumentNullException(nameof(outputStream));
             ImgInfo = imgInfo ?? throw new ArgumentNullException(nameof(imgInfo));
             this.filename = filename ?? "";
             // defaults settings
             CompLevel = 6;
             ShouldCloseStream = true;
             IdatMaxSize = 0; // use default
             CompressionStrategy = EDeflateCompressStrategy.Filtered;
             // prealloc
             //scanline = new int[imgInfo.SamplesPerRowPacked];
             rowb = new byte[imgInfo.BytesPerRow + 1];
             rowbprev = new byte[rowb.Length];
             rowbfilter = new byte[rowb.Length];
             chunksList = new ChunksListForWrite(ImgInfo);
             metadata = new PngMetadata(chunksList);
             filterStrat = new FilterWriteStrategy(ImgInfo, FilterType.FILTER_DEFAULT);
             unpackedMode = false;
             needsPack = unpackedMode && imgInfo.Packed;
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.PngWriter.chunksList, Hjg.Pngcs.PngWriter.CompLevel, Hjg.Pngcs.PngWriter.CompressionStrategy, Hjg.Pngcs.PngWriter.filename, Hjg.Pngcs.PngWriter.filterStrat, Hjg.Pngcs.PngWriter.IdatMaxSize, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.metadata, Hjg.Pngcs.PngWriter.needsPack, Hjg.Pngcs.PngWriter.outputStream, Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.PngWriter.rowb, Hjg.Pngcs.PngWriter.rowbfilter, Hjg.Pngcs.PngWriter.rowbprev, Hjg.Pngcs.PngWriter.ShouldCloseStream, and Hjg.Pngcs.PngWriter.unpackedMode.
Member Function Documentation
ComputeCompressionRatio()
double Hjg.Pngcs.PngWriter.ComputeCompressionRatio () inline
Computes compressed size/raw size, approximate
Actually: compressed size = total size of IDAT data , raw size = uncompressed pixel bytes = rows * (bytesPerRow + 1)
Returns
Definition at line 598 of file PngWriter.cs.
         {
             if (CurrentChunkGroup < ChunksList.CHUNK_GROUP_6_END)
             {
                 throw new PngjException("must be called after End()");
             }
             var compressed = (double)datStream.GetCountFlushed();
             double raw = (ImgInfo.BytesPerRow + 1) * ImgInfo.Rows;
             return compressed / raw;
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_6_END, Hjg.Pngcs.PngWriter.CurrentChunkGroup, Hjg.Pngcs.PngWriter.datStream, Hjg.Pngcs.ProgressiveOutputStream.GetCountFlushed(), Hjg.Pngcs.PngWriter.ImgInfo, and Hjg.Pngcs.ImageInfo.Rows.
CopyChunks()
void Hjg.Pngcs.PngWriter.CopyChunks (PngReader reader, int copy_mask, bool onlyAfterIdat) inline private
copy chunks from reader - copy_mask : see ChunksToWrite.COPY_XXX If we are after idat, only considers those chunks after IDAT in PngReader TODO: this should be more customizable
Definition at line 490 of file PngWriter.cs.
         {
             if (reader is null)
             {
                 throw new ArgumentNullException(nameof(reader));
             }
             var idatDone = CurrentChunkGroup >= ChunksList.CHUNK_GROUP_4_IDAT;
             if (onlyAfterIdat && reader.CurrentChunkGroup < ChunksList.CHUNK_GROUP_6_END)
             {
                 throw new PngjException("tried to copy last chunks but reader has not ended");
             }
             foreach (var chunk in reader.GetChunksList().Chunks)
             {
                 var group = chunk.ChunkGroup;
                 if (group < ChunksList.CHUNK_GROUP_4_IDAT && idatDone)
                 {
                     continue;
                 }
                 var copy = false;
                 if (chunk.Crit)
                 {
                     if (chunk.Id.Equals(ChunkHelper.PLTE, StringComparison.Ordinal))
                     {
                         if (ImgInfo.Indexed && ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_PALETTE))
{
                             copy = true;
                         }
                         if (!ImgInfo.Greyscale && ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_ALL))
{
                             copy = true;
                         }
                     }
                 }
                 else
                 { // ancillary
                     var text = (chunk is AbstractPngChunkTextVar);
                     var safe = chunk.Safe;
                     // notice that these if are not exclusive
                     if (ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_ALL))
                     {
                         copy = true;
                     }
                     if (safe && ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_ALL_SAFE))
                     {
                         copy = true;
                     }
                     if (chunk.Id.Equals(ChunkHelper.tRNS, StringComparison.Ordinal)
                             && ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_TRANSPARENCY))
                     {
                         copy = true;
                     }
                     if (chunk.Id.Equals(ChunkHelper.pHYs, StringComparison.Ordinal)
                         && ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_PHYS))
                     {
                         copy = true;
                     }
                     if (text
                         && ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_TEXTUAL))
                     {
                         copy = true;
                     }
                     if (((ChunkHelper.MaskMatch(copy_mask, ChunkCopyBehaviour.COPY_ALMOSTALL)
                             && !ChunkHelper.IsUnknown(chunk))
                             || text
                             || chunk.Id.Equals(ChunkHelper.hIST, StringComparison.Ordinal)
                             || chunk.Id.Equals(ChunkHelper.tIME, StringComparison.Ordinal)))
                     {
                         copy = true;
                     }
                     if (chunk is PngChunkSkipped)
                     {
                         copy = false;
                     }
                 }
                 if (copy)
                 {
                     _ = chunksList.Queue(AbstractPngChunk.CloneChunk(chunk, ImgInfo));
                 }
             }
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_4_IDAT, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_6_END, Hjg.Pngcs.PngWriter.chunksList, Hjg.Pngcs.Chunks.ChunkCopyBehaviour.COPY_ALL, Hjg.Pngcs.Chunks.ChunkCopyBehaviour.COPY_ALL_SAFE, Hjg.Pngcs.Chunks.ChunkCopyBehaviour.COPY_ALMOSTALL, Hjg.Pngcs.Chunks.ChunkCopyBehaviour.COPY_PALETTE, Hjg.Pngcs.Chunks.ChunkCopyBehaviour.COPY_PHYS, Hjg.Pngcs.Chunks.ChunkCopyBehaviour.COPY_TEXTUAL, Hjg.Pngcs.Chunks.ChunkCopyBehaviour.COPY_TRANSPARENCY, Hjg.Pngcs.PngWriter.CurrentChunkGroup, Hjg.Pngcs.PngReader.CurrentChunkGroup, Hjg.Pngcs.ImageInfo.Greyscale, Hjg.Pngcs.Chunks.ChunkHelper.hIST, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.ImageInfo.Indexed, Hjg.Pngcs.Chunks.ChunkHelper.IsUnknown(), Hjg.Pngcs.Chunks.ChunkHelper.MaskMatch(), Hjg.Pngcs.Chunks.ChunkHelper.pHYs, Hjg.Pngcs.Chunks.ChunkHelper.PLTE, Hjg.Pngcs.Chunks.ChunksListForWrite.Queue(), Hjg.Pngcs.Chunks.ChunkHelper.tIME, and Hjg.Pngcs.Chunks.ChunkHelper.tRNS.
Referenced by Hjg.Pngcs.PngWriter.CopyChunksFirst(), and Hjg.Pngcs.PngWriter.CopyChunksLast().
CopyChunksFirst()
void Hjg.Pngcs.PngWriter.CopyChunksFirst (PngReader reader, int copy_mask) inline
Definition at line 582 of file PngWriter.cs.
         {
             CopyChunks(reader, copy_mask, false);
         }
References Hjg.Pngcs.PngWriter.CopyChunks().
CopyChunksLast()
void Hjg.Pngcs.PngWriter.CopyChunksLast (PngReader reader, int copy_mask) inline
Definition at line 587 of file PngWriter.cs.
         {
             CopyChunks(reader, copy_mask, true);
         }
References Hjg.Pngcs.PngWriter.CopyChunks().
Dispose() [1/2]
void Hjg.Pngcs.PngWriter.Dispose (bool disposing) inline private
Definition at line 783 of file PngWriter.cs.
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     datStream?.Dispose();
                     datStreamDeflated?.Dispose();
                     outputStream.Dispose();
                 }
                 disposedValue = true;
             }
         }
References Hjg.Pngcs.PngWriter.datStream, Hjg.Pngcs.PngWriter.datStreamDeflated, Hjg.Pngcs.Zlib.AZlibOutputStream.Dispose(), Hjg.Pngcs.PngIDatChunkOutputStream.Dispose(), Hjg.Pngcs.PngWriter.disposedValue, and Hjg.Pngcs.PngWriter.outputStream.
Dispose() [2/2]
void Hjg.Pngcs.PngWriter.Dispose () inline
Definition at line 799 of file PngWriter.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
         }
EncodeRowFromByte()
void Hjg.Pngcs.PngWriter.EncodeRowFromByte (byte [] row) inline private
Definition at line 262 of file PngWriter.cs.
         {
             if (row.Length == ImgInfo.SamplesPerRowPacked && !needsPack)
             {
                 // some duplication of code - because this case is typical and it works faster this way
                 var j = 1;
                 if (ImgInfo.BitDepth <= 8)
                 {
                     foreach (var x in row)
                     { // optimized
                         rowb[j++] = x;
                     }
                 }
                 else
                 { // 16 bitspc
                     foreach (var x in row)
                     { // optimized
                         rowb[j] = x;
                         j += 2;
                     }
                 }
             }
             else
             {
                 // perhaps we need to pack?
                 if (row.Length >= ImgInfo.SamplesPerRow && needsPack)
                 {
                     ImageLine.PackInplaceByte(ImgInfo, row, row, false); // row is packed in place!
                 }
                 if (ImgInfo.BitDepth <= 8)
                 {
                     for (int i = 0, j = 1; i < ImgInfo.SamplesPerRowPacked; i++)
                     {
                         rowb[j++] = row[i];
                     }
                 }
                 else
                 { // 16 bitspc
                     for (int i = 0, j = 1; i < ImgInfo.SamplesPerRowPacked; i++)
                     {
                         rowb[j++] = row[i];
                         rowb[j++] = 0;
                     }
                 }
             }
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.needsPack, Hjg.Pngcs.ImageLine.PackInplaceByte(), Hjg.Pngcs.PngWriter.rowb, Hjg.Pngcs.ImageInfo.SamplesPerRow, and Hjg.Pngcs.ImageInfo.SamplesPerRowPacked.
Referenced by Hjg.Pngcs.PngWriter.WriteRowByte().
EncodeRowFromInt()
void Hjg.Pngcs.PngWriter.EncodeRowFromInt (int [] row) inline private
Definition at line 310 of file PngWriter.cs.
         {
             if (row.Length == ImgInfo.SamplesPerRowPacked && !needsPack)
             {
                 // some duplication of code - because this case is typical and it works faster this way
                 var j = 1;
                 if (ImgInfo.BitDepth <= 8)
                 {
                     foreach (var x in row)
                     { // optimized
                         rowb[j++] = (byte)x;
                     }
                 }
                 else
                 { // 16 bitspc
                     foreach (var x in row)
                     { // optimized
                         rowb[j++] = (byte)(x >> 8);
                         rowb[j++] = (byte)(x);
                     }
                 }
             }
             else
             {
                 // perhaps we need to pack?
                 if (row.Length >= ImgInfo.SamplesPerRow && needsPack)
                 {
                     ImageLine.PackInplaceInt(ImgInfo, row, row, false); // row is packed in place!
                 }
                 if (ImgInfo.BitDepth <= 8)
                 {
                     for (int i = 0, j = 1; i < ImgInfo.SamplesPerRowPacked; i++)
                     {
                         rowb[j++] = (byte)(row[i]);
                     }
                 }
                 else
                 { // 16 bitspc
                     for (int i = 0, j = 1; i < ImgInfo.SamplesPerRowPacked; i++)
                     {
                         rowb[j++] = (byte)(row[i] >> 8);
                         rowb[j++] = (byte)(row[i]);
                     }
                 }
             }
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.needsPack, Hjg.Pngcs.ImageLine.PackInplaceInt(), Hjg.Pngcs.PngWriter.rowb, Hjg.Pngcs.ImageInfo.SamplesPerRow, and Hjg.Pngcs.ImageInfo.SamplesPerRowPacked.
Referenced by Hjg.Pngcs.PngWriter.WriteRowInt().
End()
void Hjg.Pngcs.PngWriter.End () inline
Finalizes the image creation and closes the file stream.
This MUST be called after writing the lines.
Definition at line 616 of file PngWriter.cs.
         {
             if (rowNum != ImgInfo.Rows - 1)
             {
                 throw new PngjOutputException("all rows have not been written");
             }
             try
             {
                 datStreamDeflated.Close();
                 datStream.Close();
                 WriteLastChunks();
                 WriteEndChunk();
                 if (ShouldCloseStream)
                 {
                     outputStream.Close();
                 }
             }
             catch (IOException e)
             {
                 throw new PngjOutputException(e);
             }
         }
References Hjg.Pngcs.PngIDatChunkOutputStream.Close(), Hjg.Pngcs.PngWriter.datStream, Hjg.Pngcs.PngWriter.datStreamDeflated, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.outputStream, Hjg.Pngcs.PngWriter.rowNum, Hjg.Pngcs.ImageInfo.Rows, Hjg.Pngcs.PngWriter.ShouldCloseStream, Hjg.Pngcs.PngWriter.WriteEndChunk(), and Hjg.Pngcs.PngWriter.WriteLastChunks().
FilterAndSend()
void Hjg.Pngcs.PngWriter.FilterAndSend (int rown) inline private
Definition at line 426 of file PngWriter.cs.
         {
             FilterRow(rown);
             datStreamDeflated.Write(rowbfilter, 0, ImgInfo.BytesPerRow + 1);
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.PngWriter.datStreamDeflated, Hjg.Pngcs.PngWriter.FilterRow(), Hjg.Pngcs.PngWriter.ImgInfo, and Hjg.Pngcs.PngWriter.rowbfilter.
Referenced by Hjg.Pngcs.PngWriter.WriteRowByte(), and Hjg.Pngcs.PngWriter.WriteRowInt().
FilterRow()
void Hjg.Pngcs.PngWriter.FilterRow (int rown) inline private
Definition at line 358 of file PngWriter.cs.
         {
             // warning: filters operation rely on: "previos row" (rowbprev) is
             // initialized to 0 the first time
             if (filterStrat.ShouldTestAll(rown))
             {
                 FilterRowNone();
                 ReportResultsForFilter(rown, FilterType.FILTER_NONE, true);
                 FilterRowSub();
                 ReportResultsForFilter(rown, FilterType.FILTER_SUB, true);
                 FilterRowUp();
                 ReportResultsForFilter(rown, FilterType.FILTER_UP, true);
                 FilterRowAverage();
                 ReportResultsForFilter(rown, FilterType.FILTER_AVERAGE, true);
                 FilterRowPaeth();
                 ReportResultsForFilter(rown, FilterType.FILTER_PAETH, true);
             }
             var filterType = filterStrat.GimmeFilterType(rown, true);
             rowbfilter[0] = (byte)(int)filterType;
             switch (filterType)
             {
                 case Hjg.Pngcs.FilterType.FILTER_NONE:
                 FilterRowNone();
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_SUB:
                 FilterRowSub();
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_UP:
                 FilterRowUp();
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_AVERAGE:
                 FilterRowAverage();
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_PAETH:
                 FilterRowPaeth();
                 break;
                 default:
                 throw new PngjOutputException("Filter type " + filterType + " not implemented");
             }
             ReportResultsForFilter(rown, filterType, false);
         }
References Hjg.Pngcs.PngWriter.FilterRowAverage(), Hjg.Pngcs.PngWriter.FilterRowNone(), Hjg.Pngcs.PngWriter.FilterRowPaeth(), Hjg.Pngcs.PngWriter.FilterRowSub(), Hjg.Pngcs.PngWriter.FilterRowUp(), Hjg.Pngcs.PngWriter.filterStrat, Hjg.Pngcs.FilterWriteStrategy.GimmeFilterType(), Hjg.Pngcs.PngWriter.ReportResultsForFilter(), Hjg.Pngcs.PngWriter.rowbfilter, and Hjg.Pngcs.FilterWriteStrategy.ShouldTestAll().
Referenced by Hjg.Pngcs.PngWriter.FilterAndSend().
FilterRowAverage()
void Hjg.Pngcs.PngWriter.FilterRowAverage () inline private
Definition at line 432 of file PngWriter.cs.
         {
             int i;
             int j;
             var imax = ImgInfo.BytesPerRow;
             for (j = 1 - ImgInfo.BytesPixel, i = 1; i <= imax; i++, j++)
             {
                 rowbfilter[i] = (byte)(rowb[i] - ((rowbprev[i] + (j > 0 ? rowb[j] : 0)) / 2));
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.ImageInfo.BytesPixel, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.rowb, Hjg.Pngcs.PngWriter.rowbfilter, and Hjg.Pngcs.PngWriter.rowbprev.
Referenced by Hjg.Pngcs.PngWriter.FilterRow().
FilterRowNone()
void Hjg.Pngcs.PngWriter.FilterRowNone () inline private
Definition at line 443 of file PngWriter.cs.
         {
             for (var i = 1; i <= ImgInfo.BytesPerRow; i++)
             {
                 rowbfilter[i] = rowb[i];
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.rowb, and Hjg.Pngcs.PngWriter.rowbfilter.
Referenced by Hjg.Pngcs.PngWriter.FilterRow().
FilterRowPaeth()
void Hjg.Pngcs.PngWriter.FilterRowPaeth () inline private
Definition at line 451 of file PngWriter.cs.
         {
             int i;
             int j;
             var imax = ImgInfo.BytesPerRow;
             for (j = 1 - ImgInfo.BytesPixel, i = 1; i <= imax; i++, j++)
             {
                 rowbfilter[i] = (byte)(rowb[i] - PngHelperInternal.FilterPaethPredictor(j > 0 ? rowb[j] : 0,
                         rowbprev[i], j > 0 ? rowbprev[j] : 0));
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.ImageInfo.BytesPixel, Hjg.Pngcs.PngHelperInternal.FilterPaethPredictor(), Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.rowb, Hjg.Pngcs.PngWriter.rowbfilter, and Hjg.Pngcs.PngWriter.rowbprev.
Referenced by Hjg.Pngcs.PngWriter.FilterRow().
FilterRowSub()
void Hjg.Pngcs.PngWriter.FilterRowSub () inline private
Definition at line 463 of file PngWriter.cs.
         {
             for (var i = 1; i <= ImgInfo.BytesPixel; i++)
             {
                 rowbfilter[i] = rowb[i];
             }
             for (int j = 1, i = ImgInfo.BytesPixel + 1; i <= ImgInfo.BytesPerRow; i++, j++)
             {
                 rowbfilter[i] = (byte)(rowb[i] - rowb[j]);
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.ImageInfo.BytesPixel, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.rowb, and Hjg.Pngcs.PngWriter.rowbfilter.
Referenced by Hjg.Pngcs.PngWriter.FilterRow().
FilterRowUp()
void Hjg.Pngcs.PngWriter.FilterRowUp () inline private
Definition at line 476 of file PngWriter.cs.
         {
             for (var i = 1; i <= ImgInfo.BytesPerRow; i++)
             {
                 rowbfilter[i] = (byte)(rowb[i] - rowbprev[i]);
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.rowb, Hjg.Pngcs.PngWriter.rowbfilter, and Hjg.Pngcs.PngWriter.rowbprev.
Referenced by Hjg.Pngcs.PngWriter.FilterRow().
GetChunksList()
ChunksListForWrite Hjg.Pngcs.PngWriter.GetChunksList () inline
Definition at line 756 of file PngWriter.cs.
         {
             return chunksList;
         }
References Hjg.Pngcs.PngWriter.chunksList.
GetFilename()
string Hjg.Pngcs.PngWriter.GetFilename () inline
Filename or description, from the optional constructor argument.
Returns
Definition at line 644 of file PngWriter.cs.
         {
             return filename;
         }
References Hjg.Pngcs.PngWriter.filename.
GetMetadata()
PngMetadata Hjg.Pngcs.PngWriter.GetMetadata () inline
Definition at line 751 of file PngWriter.cs.
         {
             return metadata;
         }
References Hjg.Pngcs.PngWriter.metadata.
Init()
void Hjg.Pngcs.PngWriter.Init () inline private
init: is called automatically before writing the first row
Definition at line 148 of file PngWriter.cs.
         {
             datStream = new PngIDatChunkOutputStream(outputStream, IdatMaxSize);
             datStreamDeflated = new ZlibOutputStream(datStream, CompLevel, CompressionStrategy, true);
             WriteSignatureAndIHDR();
             WriteFirstChunks();
         }
References Hjg.Pngcs.PngWriter.CompLevel, Hjg.Pngcs.PngWriter.CompressionStrategy, Hjg.Pngcs.PngWriter.datStream, Hjg.Pngcs.PngWriter.datStreamDeflated, Hjg.Pngcs.PngWriter.IdatMaxSize, Hjg.Pngcs.PngWriter.outputStream, Hjg.Pngcs.PngWriter.WriteFirstChunks(), and Hjg.Pngcs.PngWriter.WriteSignatureAndIHDR().
Referenced by Hjg.Pngcs.PngWriter.PrepareEncodeRow().
PrepareEncodeRow()
void Hjg.Pngcs.PngWriter.PrepareEncodeRow (int rown) inline private
Definition at line 407 of file PngWriter.cs.
         {
             if (datStream is null)
             {
                 Init();
             }
             rowNum++;
             if (rown >= 0 && rowNum != rown)
             {
                 throw new PngjOutputException("rows must be written in order: expected:" + rowNum
                         + " passed:" + rown);
             }
             // swap
             var tmp = rowb;
             rowb = rowbprev;
             rowbprev = tmp;
         }
References Hjg.Pngcs.PngWriter.datStream, Hjg.Pngcs.PngWriter.Init(), Hjg.Pngcs.PngWriter.rowb, Hjg.Pngcs.PngWriter.rowbprev, and Hjg.Pngcs.PngWriter.rowNum.
Referenced by Hjg.Pngcs.PngWriter.WriteRowByte(), and Hjg.Pngcs.PngWriter.WriteRowInt().
ReportResultsForFilter()
void Hjg.Pngcs.PngWriter.ReportResultsForFilter (int rown, FilterType type, bool tentative) inline private
Definition at line 156 of file PngWriter.cs.
         {
             for (var i = 0; i < histox.Length; i++)
             {
                 histox[i] = 0;
             }
             var s = 0;
             int v;
             for (var i = 1; i <= ImgInfo.BytesPerRow; i++)
             {
                 v = rowbfilter[i];
                 if (v < 0)
                 {
                     s -= v;
                 }
                 else
                 {
                     s += v;
                 }
                 histox[v & 0xFF]++;
             }
             filterStrat.FillResultsForFilter(rown, type, s, histox, tentative);
         }
References Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.FilterWriteStrategy.FillResultsForFilter(), Hjg.Pngcs.PngWriter.filterStrat, Hjg.Pngcs.PngWriter.histox, Hjg.Pngcs.PngWriter.ImgInfo, and Hjg.Pngcs.PngWriter.rowbfilter.
Referenced by Hjg.Pngcs.PngWriter.FilterRow().
SetFilterType()
void Hjg.Pngcs.PngWriter.SetFilterType (FilterType filterType) inline
Sets internal prediction filter type, or strategy to choose it.
This must be called just after constructor, before starting writing.
Recommended values: DEFAULT (default) or AGGRESIVE
Parameters
filterType One of the five prediction types or strategy to choose it
Definition at line 769 of file PngWriter.cs.
         {
             filterStrat = new FilterWriteStrategy(ImgInfo, filterType);
         }
References Hjg.Pngcs.PngWriter.filterStrat, and Hjg.Pngcs.PngWriter.ImgInfo.
SetUseUnPackedMode()
void Hjg.Pngcs.PngWriter.SetUseUnPackedMode (bool useUnpackedMode) inline
Definition at line 774 of file PngWriter.cs.
         {
             unpackedMode = useUnpackedMode;
             needsPack = unpackedMode && ImgInfo.Packed;
         }
References Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.PngWriter.needsPack, Hjg.Pngcs.ImageInfo.Packed, and Hjg.Pngcs.PngWriter.unpackedMode.
Referenced by Hjg.Pngcs.PngWriter.WriteRow().
WriteEndChunk()
void Hjg.Pngcs.PngWriter.WriteEndChunk () inline private
Definition at line 183 of file PngWriter.cs.
         {
             var c = new PngChunkIEND(ImgInfo);
             c.CreateRawChunk().WriteChunk(outputStream);
         }
References Hjg.Pngcs.PngWriter.ImgInfo, and Hjg.Pngcs.PngWriter.outputStream.
Referenced by Hjg.Pngcs.PngWriter.End().
WriteFirstChunks()
void Hjg.Pngcs.PngWriter.WriteFirstChunks () inline private
Definition at line 189 of file PngWriter.cs.
         {
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_1_AFTERIDHR;
             _ = chunksList.WriteChunks(outputStream, CurrentChunkGroup);
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_2_PLTE;
             var nw = chunksList.WriteChunks(outputStream, CurrentChunkGroup);
             if (nw > 0 && ImgInfo.Greyscale)
             {
                 throw new PngjOutputException("cannot write palette for this format");
             }
             if (nw == 0 && ImgInfo.Indexed)
             {
                 throw new PngjOutputException("missing palette");
             }
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_3_AFTERPLTE;
             _ = chunksList.WriteChunks(outputStream, CurrentChunkGroup);
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_4_IDAT;
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_1_AFTERIDHR, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_2_PLTE, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_3_AFTERPLTE, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_4_IDAT, Hjg.Pngcs.PngWriter.chunksList, Hjg.Pngcs.PngWriter.CurrentChunkGroup, Hjg.Pngcs.ImageInfo.Greyscale, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.ImageInfo.Indexed, Hjg.Pngcs.PngWriter.outputStream, and Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
Referenced by Hjg.Pngcs.PngWriter.Init().
WriteLastChunks()
void Hjg.Pngcs.PngWriter.WriteLastChunks () inline private
Definition at line 210 of file PngWriter.cs.
         { // not including end
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_5_AFTERIDAT;
             _ = chunksList.WriteChunks(outputStream, CurrentChunkGroup);
             // should not be unwriten chunks
             var pending = chunksList.GetQueuedChunks();
             if (pending.Count > 0)
             {
                 throw new PngjOutputException(pending.Count + " chunks were not written! Eg: " + pending[0].ToString());
             }
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_6_END;
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_5_AFTERIDAT, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_6_END, Hjg.Pngcs.PngWriter.chunksList, Hjg.Pngcs.PngWriter.CurrentChunkGroup, Hjg.Pngcs.Chunks.ChunksListForWrite.GetQueuedChunks(), Hjg.Pngcs.PngWriter.outputStream, and Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
Referenced by Hjg.Pngcs.PngWriter.End().
WriteRow() [1/3]
void Hjg.Pngcs.PngWriter.WriteRow (ImageLine imgline, int rownumber) inline
this uses the row number from the imageline!
Definition at line 653 of file PngWriter.cs.
         {
             if (imgline is null)
             {
                 throw new ArgumentNullException(nameof(imgline));
             }
             SetUseUnPackedMode(imgline.SamplesUnpacked);
             if (imgline.SampleType == ImageLine.ESampleType.INT)
             {
                 WriteRowInt(imgline.Scanline, rownumber);
             }
             else
             {
                 WriteRowByte(imgline.ScanlineB, rownumber);
             }
         }
References Hjg.Pngcs.ImageLine.SamplesUnpacked, Hjg.Pngcs.ImageLine.SampleType, Hjg.Pngcs.ImageLine.Scanline, Hjg.Pngcs.ImageLine.ScanlineB, Hjg.Pngcs.PngWriter.SetUseUnPackedMode(), Hjg.Pngcs.PngWriter.WriteRowByte(), and Hjg.Pngcs.PngWriter.WriteRowInt().
Referenced by Hjg.Pngcs.PngWriter.WriteRow().
WriteRow() [2/3]
void Hjg.Pngcs.PngWriter.WriteRow (int [] newrow) inline
Definition at line 671 of file PngWriter.cs.
         {
             WriteRow(newrow, -1);
         }
References Hjg.Pngcs.PngWriter.WriteRow().
WriteRow() [3/3]
void Hjg.Pngcs.PngWriter.WriteRow (int [] newrow, int rown) inline
Definition at line 676 of file PngWriter.cs.
         {
             WriteRowInt(newrow, rown);
         }
References Hjg.Pngcs.PngWriter.WriteRowInt().
WriteRowByte()
void Hjg.Pngcs.PngWriter.WriteRowByte (byte [] newrow, int rown) inline
Definition at line 705 of file PngWriter.cs.
         {
             if (newrow is null)
             {
                 throw new ArgumentNullException(nameof(newrow));
             }
             PrepareEncodeRow(rown);
             EncodeRowFromByte(newrow);
             FilterAndSend(rown);
         }
References Hjg.Pngcs.PngWriter.EncodeRowFromByte(), Hjg.Pngcs.PngWriter.FilterAndSend(), and Hjg.Pngcs.PngWriter.PrepareEncodeRow().
Referenced by Hjg.Pngcs.PngWriter.WriteRow(), and Hjg.Pngcs.PngWriter.WriteRowsByte().
WriteRowInt()
void Hjg.Pngcs.PngWriter.WriteRowInt (int [] newrow, int rown) inline
Writes a full image row.
This must be called sequentially from n=0 to n=rows-1 One integer per sample , in the natural order: R G B R G B ... (or R G B A R G B A... if has alpha) The values should be between 0 and 255 for 8 bitspc images, and between 0- 65535 form 16 bitspc images (this applies also to the alpha channel if present) The array can be reused.
Parameters
newrow Array of pixel values
rown Number of row, from 0 (top) to rows-1 (bottom)
Definition at line 693 of file PngWriter.cs.
         {
             if (newrow is null)
             {
                 throw new ArgumentNullException(nameof(newrow));
             }
             PrepareEncodeRow(rown);
             EncodeRowFromInt(newrow);
             FilterAndSend(rown);
         }
References Hjg.Pngcs.PngWriter.EncodeRowFromInt(), Hjg.Pngcs.PngWriter.FilterAndSend(), and Hjg.Pngcs.PngWriter.PrepareEncodeRow().
Referenced by Hjg.Pngcs.PngWriter.WriteRow(), and Hjg.Pngcs.PngWriter.WriteRowsInt().
WriteRowsByte()
void Hjg.Pngcs.PngWriter.WriteRowsByte (byte image[][]) inline
Writes all the pixels, calling writeRowByte() for each image row
Definition at line 738 of file PngWriter.cs.
         {
             if (image is null)
             {
                 throw new ArgumentNullException(nameof(image));
             }
             for (var i = 0; i < ImgInfo.Rows; i++)
             {
                 WriteRowByte(image[i], i);
             }
         }
References Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.ImageInfo.Rows, and Hjg.Pngcs.PngWriter.WriteRowByte().
WriteRowsInt()
void Hjg.Pngcs.PngWriter.WriteRowsInt (int image[][]) inline
Writes all the pixels, calling writeRowInt() for each image row
Definition at line 721 of file PngWriter.cs.
         {
             if (image is null)
             {
                 throw new ArgumentNullException(nameof(image));
             }
             for (var i = 0; i < ImgInfo.Rows; i++)
             {
                 WriteRowInt(image[i], i);
             }
         }
References Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.ImageInfo.Rows, and Hjg.Pngcs.PngWriter.WriteRowInt().
WriteSignatureAndIHDR()
void Hjg.Pngcs.PngWriter.WriteSignatureAndIHDR () inline private
Write id signature and also "IHDR" chunk
Definition at line 228 of file PngWriter.cs.
         {
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_0_IDHR;
             PngHelperInternal.WriteBytes(outputStream, Hjg.Pngcs.PngHelperInternal.PNG_ID_SIGNATURE); // signature
             var ihdr = new PngChunkIHDR(ImgInfo)
             {
                 // http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html
                 Cols = ImgInfo.Cols,
                 Rows = ImgInfo.Rows,
                 Bitspc = ImgInfo.BitDepth
             };
             var colormodel = 0;
             if (ImgInfo.Alpha)
             {
                 colormodel |= 0x04;
             }
             if (!ImgInfo.Greyscale)
             {
                 colormodel |= 0x02;
             }
             if (ImgInfo.Indexed)
             {
                 colormodel |= 0x01;
             }
             ihdr.Colormodel = colormodel;
             ihdr.Compmeth = 0; // compression method 0=deflate
             ihdr.Filmeth = 0; // filter method (0)
             ihdr.Interlaced = 0; // never interlace
             ihdr.CreateRawChunk().WriteChunk(outputStream);
         }
References Hjg.Pngcs.ImageInfo.Alpha, Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_0_IDHR, Hjg.Pngcs.ImageInfo.Cols, Hjg.Pngcs.PngWriter.CurrentChunkGroup, Hjg.Pngcs.ImageInfo.Greyscale, Hjg.Pngcs.PngWriter.ImgInfo, Hjg.Pngcs.ImageInfo.Indexed, Hjg.Pngcs.PngWriter.outputStream, Hjg.Pngcs.PngHelperInternal.PNG_ID_SIGNATURE, Hjg.Pngcs.ImageInfo.Rows, and Hjg.Pngcs.PngHelperInternal.WriteBytes().
Referenced by Hjg.Pngcs.PngWriter.Init().
Member Data Documentation
chunksList
readonly ChunksListForWrite Hjg.Pngcs.PngWriter.chunksList private
written/queued chunks
Definition at line 63 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.PngWriter.GetChunksList(), Hjg.Pngcs.PngWriter.PngWriter(), Hjg.Pngcs.PngWriter.WriteFirstChunks(), and Hjg.Pngcs.PngWriter.WriteLastChunks().
datStream
PngIDatChunkOutputStream Hjg.Pngcs.PngWriter.datStream private
Definition at line 89 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.ComputeCompressionRatio(), Hjg.Pngcs.PngWriter.Dispose(), Hjg.Pngcs.PngWriter.End(), Hjg.Pngcs.PngWriter.Init(), and Hjg.Pngcs.PngWriter.PrepareEncodeRow().
datStreamDeflated
AZlibOutputStream Hjg.Pngcs.PngWriter.datStreamDeflated private
Definition at line 90 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.Dispose(), Hjg.Pngcs.PngWriter.End(), Hjg.Pngcs.PngWriter.FilterAndSend(), and Hjg.Pngcs.PngWriter.Init().
disposedValue
bool Hjg.Pngcs.PngWriter.disposedValue = false private
Definition at line 781 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.Dispose().
filename
readonly string Hjg.Pngcs.PngWriter.filename private
filename, or description - merely informative, can be empty
Definition at line 24 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.GetFilename(), and Hjg.Pngcs.PngWriter.PngWriter().
filterStrat
FilterWriteStrategy Hjg.Pngcs.PngWriter.filterStrat private
Definition at line 26 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.FilterRow(), Hjg.Pngcs.PngWriter.PngWriter(), Hjg.Pngcs.PngWriter.ReportResultsForFilter(), and Hjg.Pngcs.PngWriter.SetFilterType().
histox
readonly int [] Hjg.Pngcs.PngWriter.histox = new int[256] private
Definition at line 92 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.ReportResultsForFilter().
metadata
readonly PngMetadata Hjg.Pngcs.PngWriter.metadata private
A high level wrapper of a ChunksList : list of written/queued chunks
Definition at line 58 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.GetMetadata(), and Hjg.Pngcs.PngWriter.PngWriter().
needsPack
bool Hjg.Pngcs.PngWriter.needsPack private
Definition at line 97 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.EncodeRowFromByte(), Hjg.Pngcs.PngWriter.EncodeRowFromInt(), Hjg.Pngcs.PngWriter.PngWriter(), and Hjg.Pngcs.PngWriter.SetUseUnPackedMode().
outputStream
readonly Stream Hjg.Pngcs.PngWriter.outputStream private
Definition at line 87 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.Dispose(), Hjg.Pngcs.PngWriter.End(), Hjg.Pngcs.PngWriter.Init(), Hjg.Pngcs.PngWriter.PngWriter(), Hjg.Pngcs.PngWriter.WriteEndChunk(), Hjg.Pngcs.PngWriter.WriteFirstChunks(), Hjg.Pngcs.PngWriter.WriteLastChunks(), and Hjg.Pngcs.PngWriter.WriteSignatureAndIHDR().
rowb
byte [] Hjg.Pngcs.PngWriter.rowb private
raw current row, as array of bytes,counting from 1 (index 0 is reserved for filter type)
Definition at line 68 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.EncodeRowFromByte(), Hjg.Pngcs.PngWriter.EncodeRowFromInt(), Hjg.Pngcs.PngWriter.FilterRowAverage(), Hjg.Pngcs.PngWriter.FilterRowNone(), Hjg.Pngcs.PngWriter.FilterRowPaeth(), Hjg.Pngcs.PngWriter.FilterRowSub(), Hjg.Pngcs.PngWriter.FilterRowUp(), Hjg.Pngcs.PngWriter.PngWriter(), and Hjg.Pngcs.PngWriter.PrepareEncodeRow().
rowbfilter
readonly byte [] Hjg.Pngcs.PngWriter.rowbfilter private
raw current row, after filtered
Definition at line 78 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.FilterAndSend(), Hjg.Pngcs.PngWriter.FilterRow(), Hjg.Pngcs.PngWriter.FilterRowAverage(), Hjg.Pngcs.PngWriter.FilterRowNone(), Hjg.Pngcs.PngWriter.FilterRowPaeth(), Hjg.Pngcs.PngWriter.FilterRowSub(), Hjg.Pngcs.PngWriter.FilterRowUp(), Hjg.Pngcs.PngWriter.PngWriter(), and Hjg.Pngcs.PngWriter.ReportResultsForFilter().
rowbprev
byte [] Hjg.Pngcs.PngWriter.rowbprev private
previuos raw row
Definition at line 73 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.FilterRowAverage(), Hjg.Pngcs.PngWriter.FilterRowPaeth(), Hjg.Pngcs.PngWriter.FilterRowUp(), Hjg.Pngcs.PngWriter.PngWriter(), and Hjg.Pngcs.PngWriter.PrepareEncodeRow().
rowNum
int Hjg.Pngcs.PngWriter.rowNum = -1 private
Definition at line 86 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.End(), and Hjg.Pngcs.PngWriter.PrepareEncodeRow().
unpackedMode
bool Hjg.Pngcs.PngWriter.unpackedMode private
Definition at line 95 of file PngWriter.cs.
Referenced by Hjg.Pngcs.PngWriter.PngWriter(), and Hjg.Pngcs.PngWriter.SetUseUnPackedMode().
Property Documentation
CompLevel
int Hjg.Pngcs.PngWriter.CompLevel get set
zip compression level (0 - 9)
default:6
9 is the maximum compression
Definition at line 40 of file PngWriter.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngWriter.Init(), and Hjg.Pngcs.PngWriter.PngWriter().
CompressionStrategy
EDeflateCompressStrategy Hjg.Pngcs.PngWriter.CompressionStrategy get set
Deflate algortithm compression strategy
Definition at line 31 of file PngWriter.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngWriter.Init(), and Hjg.Pngcs.PngWriter.PngWriter().
CurrentChunkGroup
int Hjg.Pngcs.PngWriter.CurrentChunkGroup get private set
number of chunk group (0-6) last writen, or currently writing
see ChunksList.CHUNK_GROUP_NNN
Definition at line 84 of file PngWriter.cs.
 { get; private set; }
Referenced by Hjg.Pngcs.PngWriter.ComputeCompressionRatio(), Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.PngWriter.WriteFirstChunks(), Hjg.Pngcs.PngWriter.WriteLastChunks(), and Hjg.Pngcs.PngWriter.WriteSignatureAndIHDR().
IdatMaxSize
int Hjg.Pngcs.PngWriter.IdatMaxSize get set
Maximum size of IDAT chunks
0=use default (PngIDatChunkOutputStream 32768)
Definition at line 53 of file PngWriter.cs.
 { get; set; } //
Referenced by Hjg.Pngcs.PngWriter.Init(), and Hjg.Pngcs.PngWriter.PngWriter().
ImgInfo
ImageInfo Hjg.Pngcs.PngWriter.ImgInfo get
Basic image info, inmutable
Definition at line 19 of file PngWriter.cs.
 { get; }
Referenced by Hjg.Pngcs.PngWriter.ComputeCompressionRatio(), Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.PngWriter.EncodeRowFromByte(), Hjg.Pngcs.PngWriter.EncodeRowFromInt(), Hjg.Pngcs.PngWriter.End(), Hjg.Pngcs.PngWriter.FilterAndSend(), Hjg.Pngcs.PngWriter.FilterRowAverage(), Hjg.Pngcs.PngWriter.FilterRowNone(), Hjg.Pngcs.PngWriter.FilterRowPaeth(), Hjg.Pngcs.PngWriter.FilterRowSub(), Hjg.Pngcs.PngWriter.FilterRowUp(), Hjg.Pngcs.PngWriter.PngWriter(), Hjg.Pngcs.PngWriter.ReportResultsForFilter(), Hjg.Pngcs.PngWriter.SetFilterType(), Hjg.Pngcs.PngWriter.SetUseUnPackedMode(), Hjg.Pngcs.PngWriter.WriteEndChunk(), Hjg.Pngcs.PngWriter.WriteFirstChunks(), Hjg.Pngcs.PngWriter.WriteRowsByte(), Hjg.Pngcs.PngWriter.WriteRowsInt(), and Hjg.Pngcs.PngWriter.WriteSignatureAndIHDR().
ShouldCloseStream
bool Hjg.Pngcs.PngWriter.ShouldCloseStream get set
true: closes stream after ending write
Definition at line 45 of file PngWriter.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngWriter.End(), and Hjg.Pngcs.PngWriter.PngWriter().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/PngWriter.cs