Juniper: Juniper.ConfigurationManagement.JuniperInstalledPackageManager Class Reference
Juniper.ConfigurationManagement.JuniperInstalledPackageManager Class Reference
An editor to respond to changes in XRSystem.
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void ShowJuniperWindow ()
Static Private Member Functions
static void DrawInstalledPackages (List< string > defines)
static void DrawStatus (PlatformType selectedPlatform, BuildTargetGroup targetGroup)
Private Attributes
const string MENU_NAME = "Juniper/"
const int buttonWidthValue = 100
Static Private Attributes
static readonly GUIContent TITLE = new GUIContent("Juniper - Installed Packages")
static readonly GUILayoutOption nameFieldWidth = GUILayout.Width(200)
static readonly GUILayoutOption buttonWidth = GUILayout.Width(buttonWidthValue)
static readonly TableView installedPackageTable
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 23 of file JuniperInstalledPackageManager.cs.
Member Function Documentation
DrawInstalledPackages()
static void Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawInstalledPackages (List< string > defines) inline static private
Definition at line 71 of file JuniperInstalledPackageManager.cs.
         {
             var installed = from versions in Project.PackageDatabase.Values
                             from package in versions
                             where package.IsInstalled
                             orderby package.Source, package.PackageID, package.VersionSpec
                             select package;
             using (installedPackageTable.Begin())
             {
                 var drawn = 0;
                 foreach (var pkg in installed)
                 {
                     ++drawn;
                     using (new HGroup())
                     {
                         EditorGUILayout.LabelField(pkg.Source.ToString(), nameFieldWidth);
                         EditorGUILayout.LabelField(pkg.Name);
                         EditorGUILayout.LabelField(pkg.VersionSpec, nameFieldWidth);
                         using (new EnabledScope(!defines.Contains(pkg.CompilerDefine)))
{
                             if (GUILayout.Button("Activate", buttonWidth))
{
                                 pkg.Activate();
                             }
                         }
                     }
                 }
                 if (drawn == 0)
                 {
                     EditorGUILayout.LabelField("None", EditorStyles.centeredGreyMiniLabel);
                 }
             }
         }
References UnityEditor.TableView.Begin(), Juniper.ConfigurationManagement.JuniperInstalledPackageManager.buttonWidth, Juniper.ConfigurationManagement.JuniperInstalledPackageManager.installedPackageTable, Juniper.ConfigurationManagement.JuniperInstalledPackageManager.nameFieldWidth, and Juniper.ConfigurationManagement.Project.PackageDatabase.
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.OnGUI().
DrawStatus()
static void Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawStatus (PlatformType selectedPlatform, BuildTargetGroup targetGroup) inline static private
Definition at line 109 of file JuniperInstalledPackageManager.cs.
         {
             using (new Header("Status"))
             {
                 EditorGUILayoutExt.LabeledField("Current platform", nameFieldWidth, selectedPlatform, nameFieldWidth);
                 EditorGUILayoutExt.LabeledField("Current build target", nameFieldWidth, targetGroup, nameFieldWidth);
             }
         }
References Juniper.ConfigurationManagement.JuniperInstalledPackageManager.nameFieldWidth.
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.OnGUI().
OnGUI()
void Juniper.ConfigurationManagement.JuniperInstalledPackageManager.OnGUI () inline
Definition at line 48 of file JuniperInstalledPackageManager.cs.
         {
             titleContent = TITLE;
             if (EditorApplication.isCompiling)
             {
                 EditorGUILayout.LabelField("Compiling...");
             }
             else
             {
                 var platforms = Platforms.Load();
                 var selectedPlatform = ProjectConfiguration.Platform;
                 var currentConfiguration = platforms.Configurations[selectedPlatform];
                 var targetGroup = currentConfiguration.GetTargetGroup();
                 DrawStatus(selectedPlatform, targetGroup);
                 var defines = Project.GetDefines();
                 DrawInstalledPackages(defines);
             }
         }
References Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawInstalledPackages(), Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawStatus(), Juniper.ConfigurationManagement.Project.GetDefines(), Juniper.ConfigurationManagement.Platforms.Load(), Juniper.ProjectConfiguration.Platform, and Juniper.ConfigurationManagement.JuniperInstalledPackageManager.TITLE.
ShowJuniperWindow()
static void Juniper.ConfigurationManagement.JuniperInstalledPackageManager.ShowJuniperWindow () inline static
Definition at line 26 of file JuniperInstalledPackageManager.cs.
         {
             EditorWindow.GetWindow<JuniperInstalledPackageManager>();
         }
Member Data Documentation
buttonWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperInstalledPackageManager.buttonWidth = GUILayout.Width(buttonWidthValue) static private
Definition at line 37 of file JuniperInstalledPackageManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawInstalledPackages().
buttonWidthValue
const int Juniper.ConfigurationManagement.JuniperInstalledPackageManager.buttonWidthValue = 100 private
Definition at line 34 of file JuniperInstalledPackageManager.cs.
installedPackageTable
readonly TableView Juniper.ConfigurationManagement.JuniperInstalledPackageManager.installedPackageTable static private
Initial value:
= new TableView(
            "Installed Packages",
            ("Source", nameFieldWidth),
            ("Name", null),
            ("Version", nameFieldWidth),
            ("", buttonWidth)
        )
Definition at line 39 of file JuniperInstalledPackageManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawInstalledPackages().
MENU_NAME
const string Juniper.ConfigurationManagement.JuniperInstalledPackageManager.MENU_NAME = "Juniper/" private
Definition at line 31 of file JuniperInstalledPackageManager.cs.
nameFieldWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperInstalledPackageManager.nameFieldWidth = GUILayout.Width(200) static private
Definition at line 36 of file JuniperInstalledPackageManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawInstalledPackages(), and Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawStatus().
TITLE
readonly GUIContent Juniper.ConfigurationManagement.JuniperInstalledPackageManager.TITLE = new GUIContent("Juniper - Installed Packages") static private
Definition at line 32 of file JuniperInstalledPackageManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.OnGUI().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Editor Plugins/ConfigurationManagement/JuniperInstalledPackageManager.cs