Juniper: Juniper.Units.Degrees Class Reference
Juniper.Units.Degrees Class Reference
Conversions from degrees
Static Public Member Functions
static float Radians (float degrees)
Convert from degrees to radians.
static float Gradians (float degrees)
Convert from degrees to gradians.
static float Hours (float degrees)
Convert from degrees to hours.
Public Attributes
const float PER_CIRCLE = 360f
Conversion factor from circles to degrees.
const float PER_RADIAN = PER_CIRCLE / Units.Radians.PER_CIRCLE
Conversion factor from radians to degrees.
const float PER_GRADIAN = PER_CIRCLE / Units.Gradians.PER_CIRCLE
Conversion factor from gradians to degrees.
const float PER_HOUR = PER_CIRCLE / Units.Hours.PER_DAY
Conversion factor from hours to degrees.
Detailed Description
Conversions from degrees
Definition at line 8 of file Degrees.cs.
Member Function Documentation
Gradians()
static float Juniper.Units.Degrees.Gradians (float degrees) inline static
Convert from degrees to gradians.
Parameters
degrees The number of degrees
Returns
The number of gradians
Definition at line 45 of file Degrees.cs.
             {
                 return degrees * Units.Gradians.PER_DEGREE;
             }
References Juniper.Units.Gradians.PER_DEGREE.
Hours()
static float Juniper.Units.Degrees.Hours (float degrees) inline static
Convert from degrees to hours.
Parameters
degrees The number of degrees
Returns
The number of hours
Definition at line 55 of file Degrees.cs.
             {
                 return degrees * Units.Hours.PER_DEGREE;
             }
References Juniper.Units.Hours.PER_DEGREE.
Referenced by Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal().
Radians()
static float Juniper.Units.Degrees.Radians (float degrees) inline static
Convert from degrees to radians.
Parameters
degrees The number of degrees
Returns
The number of radians
Definition at line 35 of file Degrees.cs.
             {
                 return degrees * Units.Radians.PER_DEGREE;
             }
References Juniper.Units.Radians.PER_DEGREE.
Referenced by Juniper.World.GIS.GeocentricEclipticSphericalPosition.FromJulianDay(), Juniper.World.GIS.LatLngPointExt.SphericalMercator(), Juniper.World.GIS.GeocentricEclipticSphericalPosition.ToEquitorial(), and Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal().
Member Data Documentation
PER_CIRCLE
const float Juniper.Units.Degrees.PER_CIRCLE = 360f
Conversion factor from circles to degrees.
Definition at line 13 of file Degrees.cs.
PER_GRADIAN
const float Juniper.Units.Degrees.PER_GRADIAN = PER_CIRCLE / Units.Gradians.PER_CIRCLE
Conversion factor from gradians to degrees.
Definition at line 23 of file Degrees.cs.
Referenced by Juniper.Units.Gradians.Degrees().
PER_HOUR
const float Juniper.Units.Degrees.PER_HOUR = PER_CIRCLE / Units.Hours.PER_DAY
Conversion factor from hours to degrees.
Definition at line 28 of file Degrees.cs.
Referenced by Juniper.Units.Hours.Degrees().
PER_RADIAN
const float Juniper.Units.Degrees.PER_RADIAN = PER_CIRCLE / Units.Radians.PER_CIRCLE
Conversion factor from radians to degrees.
Definition at line 18 of file Degrees.cs.
Referenced by Juniper.Units.Radians.Degrees().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper.Units/src/Angles/Degrees.cs