Juniper: Juniper.Collections.NAryTree< T > Class Template Reference
Juniper.Collections.NAryTree< T > Class Template Reference
A node in an N-ary tree.
Public Member Functions
NAryTree ()
NAryTree (T value)
Creates a root node with no children.
void Add (T node, Func< T, T, bool > isChildOf)
Add an element as a child of the node.
NAryTree< T > Remove (T node)
IEnumerable< NAryTree< T > > Where (Func< NAryTree< T >, bool > predicate, TreeTraversalOrder order=TreeTraversalOrder.BreadthFirst)
IEnumerable< NAryTree< T > > Flatten (TreeTraversalOrder order=TreeTraversalOrder.BreadthFirst)
Perform an operation over the trie, using a local stack instead of the function call stack frame.
StateT Accumulate< StateT > (TreeTraversalOrder order, StateT state, Func< StateT, NAryTree< T >, StateT > act)
Perform an operation over the trie, using a local stack instead of the function call stack frame.
override string ToString ()
Print out a debugging string.
Public Attributes
bool IsLeaf => Children.Count == 0
Returns true if there are no child nodes.
bool IsRoot => Parent is null
Returns true if this node has no parent node.
Properties
T Value [get, set]
The value stored in this node.
List< NAryTree< T > > Children = new List<NAryTree<T>>() [get]
All nodes below the current node.
NAryTree< T > Parent [get, set]
The next node above the current node.
int Count [get, private set]
int Depth [get]
How deep into the tree is this branch
Private Member Functions
NAryTree (T value, NAryTree< T > parent)
Detailed Description
A node in an N-ary tree.
Template Parameters
T Any type of object
Type Constraints
T : IEquatable<T>
Definition at line 11 of file NAryTree.cs.
Constructor & Destructor Documentation
NAryTree() [1/3]
Juniper.Collections.NAryTree< T >.NAryTree () inline
Definition at line 31 of file NAryTree.cs.
         { }
NAryTree() [2/3]
Juniper.Collections.NAryTree< T >.NAryTree (T value) inline
Creates a root node with no children.
Parameters
value The value to store at the root.
Definition at line 38 of file NAryTree.cs.
         {
             Value = value;
         }
References Juniper.Collections.NAryTree< T >.Value.
NAryTree() [3/3]
Juniper.Collections.NAryTree< T >.NAryTree (T value, NAryTree< T > parent) inline private
Definition at line 43 of file NAryTree.cs.
             : this(value)
         {
             Parent = parent;
         }
References Juniper.Collections.NAryTree< T >.Parent.
Member Function Documentation
Accumulate< StateT >()
StateT Juniper.Collections.NAryTree< T >.Accumulate< StateT > (TreeTraversalOrder order, StateT state, Func< StateT, NAryTree< T >, StateT > act) inline
Perform an operation over the trie, using a local stack instead of the function call stack frame.
Parameters
act Act.
Definition at line 182 of file NAryTree.cs.
         {
             foreach (var child in Flatten(order))
             {
                 state = act(state, child);
             }
             return state;
         }
References Juniper.Collections.NAryTree< T >.Flatten().
Add()
void Juniper.Collections.NAryTree< T >.Add (T node, Func< T, T, bool > isChildOf) inline
Add an element as a child of the node.
Parameters
node The node to add.
Definition at line 82 of file NAryTree.cs.
         {
             if (Value is null)
             {
                 Value = node;
             }
             else
             {
                 var q = new Queue<NAryTree<T>>
                 {
                     this
                 };
                 NAryTree<T> lastParent = null;
                 while (q.Count > 0)
                 {
                     var here = q.Dequeue();
                     if (isChildOf(here.Value, node))
                     {
                         ++here.Count;
                         lastParent = here;
                         q.AddRange(here.Children);
                     }
                 }
                 if (lastParent != null)
                 {
                     lastParent.Children.Add(new NAryTree<T>(node, lastParent));
                 }
             }
         }
References Juniper.Collections.NAryTree< T >.Children, Juniper.Collections.NAryTree< T >.Count, and Juniper.Collections.NAryTree< T >.Value.
Flatten()
IEnumerable<NAryTree<T> > Juniper.Collections.NAryTree< T >.Flatten (TreeTraversalOrder order = TreeTraversalOrder.BreadthFirst) inline
Perform an operation over the trie, using a local stack instead of the function call stack frame.
Definition at line 172 of file NAryTree.cs.
         {
             return Where(_ => true, order);
         }
References Juniper.Collections.NAryTree< T >.Where().
Referenced by Juniper.Collections.NAryTree< T >.Accumulate< StateT >().
Remove()
NAryTree<T> Juniper.Collections.NAryTree< T >.Remove (T node) inline
Definition at line 114 of file NAryTree.cs.
         {
             var q = new Queue<NAryTree<T>>
             {
                 this
             };
             NAryTree<T> found = null;
             while (q.Count > 0 && found is null)
             {
                 var here = q.Dequeue();
                 if (here.Value.Equals(node))
                 {
                     found = here;
                 }
                 else
                 {
                     q.AddRange(here.Children);
                 }
             }
             if (found != null)
             {
                 found.Parent.Count -= found.Count;
                 _ = found.Parent.Children.Remove(found);
                 found.Parent = null;
             }
             return found;
         }
References Juniper.Collections.NAryTree< T >.Count, and Juniper.Collections.NAryTree< T >.Parent.
ToString()
override string Juniper.Collections.NAryTree< T >.ToString () inline
Print out a debugging string.
Returns
A text representation of the tree.
Definition at line 196 of file NAryTree.cs.
         {
             return Accumulate(TreeTraversalOrder.DepthFirst, new StringBuilder(), (sb, here) =>
             {
                 for (var i = 0; i < here.Depth; ++i)
                 {
                     _ = sb.Append("--");
                 }
                 _ = sb.AppendLine(here.Value.ToString());
                 return sb;
             }).ToString();
         }
Where()
IEnumerable<NAryTree<T> > Juniper.Collections.NAryTree< T >.Where (Func< NAryTree< T >, bool > predicate, TreeTraversalOrder order = TreeTraversalOrder.BreadthFirst) inline
Definition at line 145 of file NAryTree.cs.
         {
             // how to do recursion without killing the function call stack
             var items = new List<NAryTree<T>>
             {
                 this
             };
             while (items.Count > 0)
             {
                 var index = (order == TreeTraversalOrder.BreadthFirst)
                     ? 0
                     : items.Count - 1;
                 var here = items[index];
                 items.RemoveAt(index);
                 if (predicate(here))
                 {
                     yield return here;
                     items.AddRange(here.Children);
                 }
             }
         }
Referenced by Juniper.Collections.NAryTree< T >.Flatten().
Member Data Documentation
IsLeaf
bool Juniper.Collections.NAryTree< T >.IsLeaf => Children.Count == 0
Returns true if there are no child nodes.
Definition at line 71 of file NAryTree.cs.
IsRoot
bool Juniper.Collections.NAryTree< T >.IsRoot => Parent is null
Returns true if this node has no parent node.
Definition at line 76 of file NAryTree.cs.
Property Documentation
Children
List<NAryTree<T> > Juniper.Collections.NAryTree< T >.Children = new List<NAryTree<T>>() get
All nodes below the current node.
Definition at line 22 of file NAryTree.cs.
 { get; } = new List<NAryTree<T>>();
Referenced by Juniper.Collections.NAryTree< T >.Add().
Count
int Juniper.Collections.NAryTree< T >.Count get private set
Definition at line 29 of file NAryTree.cs.
 { get; private set; }
Referenced by Juniper.Collections.NAryTree< T >.Add(), and Juniper.Collections.NAryTree< T >.Remove().
Depth
int Juniper.Collections.NAryTree< T >.Depth get protected
How deep into the tree is this branch
Definition at line 53 of file NAryTree.cs.
         {
             get
             {
                 var depth = 0;
                 var here = this;
                 while (here is object)
                 {
                     ++depth;
                     here = here.Parent;
                 }
                 return depth;
             }
         }
Parent
NAryTree<T> Juniper.Collections.NAryTree< T >.Parent get set protected
The next node above the current node.
Definition at line 27 of file NAryTree.cs.
 { get; set; }
Referenced by Juniper.Collections.NAryTree< T >.NAryTree(), and Juniper.Collections.NAryTree< T >.Remove().
Value
T Juniper.Collections.NAryTree< T >.Value get set
The value stored in this node.
Definition at line 17 of file NAryTree.cs.
 { get; internal set; }
Referenced by Juniper.Collections.NAryTree< T >.Add(), and Juniper.Collections.NAryTree< T >.NAryTree().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Collections/NAryTree.cs