Juniper: Juniper.StageExtensions Class Reference
Juniper.StageExtensions Class Reference
Public Member Functions
virtual void Awake ()
virtual void Reinstall ()
void Reset ()
void Install (bool reset)
void Uninstall ()
T MakePointer< T > (Transform parent, string path)
void RotateView (Quaternion dQuat, float minX, float maxX)
void SetVelocity (Vector3 v)
void FixedUpdate ()
Public Attributes
float defaultAvatarHeight = 1.75f
When running on systems that do not understand the relationship between the camera and the ground (marker-tracking AR, 3DOF VR), this is the height that is used for the camera off of the ground.
Private Member Functions
void EnableMouse (bool value)
void EnableGaze (bool value)
void EnableTouch (bool value)
void EnableHands (bool value)
void EnableControllers (bool value)
Static Private Member Functions
static GameObject MakeShadowCaster (PrimitiveType type, Vector3? scale, Vector3? position=null)
Private Attributes
const string ENABLE_GAZE_KEY = "GazePointer"
const string ENABLE_MOUSE_KEY = "MousePointer"
const string ENABLE_TOUCH_KEY = "TouchPointers"
const string ENABLE_HANDS_KEY = "HandPointers"
const string ENABLE_CONTROLLERS_KEY = "MotionControllers"
GazePointer gazePointer
Mouse mouse
TouchPoint [] touches
MotionController [] motionControllers
HandTracker [] handTrackers
Transform Head
Transform Hands
Transform Body
Vector3 velocity
Detailed Description
Definition at line 21 of file StageExtensions.cs.
Member Function Documentation
Awake()
virtual void Juniper.StageExtensions.Awake () inline virtual
Definition at line 77 of file StageExtensions.cs.
         {
             Install(false);
 #if UNITY_MODULES_UI
             if (enableGazeToggle != null)
             {
                 enableGazeToggle.onValueChanged.AddListener(EnableGaze);
                 enableGazeToggle.isOn = PlayerPrefs.GetInt(ENABLE_GAZE_KEY, 0) == 1;
                 gazePointer.SetActive(enableGazeToggle.isOn);
             }
             if (enableHandsToggle != null)
             {
                 enableHandsToggle.onValueChanged.AddListener(EnableHands);
                 enableHandsToggle.isOn = PlayerPrefs.GetInt(ENABLE_HANDS_KEY, 0) == 1;
                 foreach (var handTracker in handTrackers)
                 {
                     handTracker.SetActive(enableHandsToggle.isOn);
                 }
             }
             if (enableControllersToggle != null)
             {
                 enableControllersToggle.onValueChanged.AddListener(EnableControllers);
                 enableControllersToggle.isOn = PlayerPrefs.GetInt(ENABLE_CONTROLLERS_KEY, 1) == 1;
                 foreach (var motionController in motionControllers)
                 {
                     motionController.SetActive(enableControllersToggle.isOn);
                 }
             }
             if (enableMouseToggle != null)
             {
                 enableMouseToggle.onValueChanged.AddListener(EnableMouse);
                 enableMouseToggle.isOn = PlayerPrefs.GetInt(ENABLE_MOUSE_KEY, 1) == 1;
                 mouse.SetActive(enableMouseToggle.isOn);
             }
             if (enableTouchToggle != null)
             {
                 enableTouchToggle.onValueChanged.AddListener(EnableTouch);
                 enableTouchToggle.isOn = PlayerPrefs.GetInt(ENABLE_TOUCH_KEY, Application.isMobilePlatform ? 1 : 0) == 1;
                 foreach (var touch in touches)
                 {
                     touch.SetActive(enableTouchToggle.isOn);
                 }
             }
 #endif
 #if ARKIT || ARCORE || HOLOLENS || MAGIC_LEAP
             usePhysicsBasedMovement = false;
 #endif
 #if UNITY_MODULES_PHYSICS
             BodyShape.enabled = usePhysicsBasedMovement;
 #endif
         }
References Juniper.StageExtensions.ENABLE_CONTROLLERS_KEY, Juniper.StageExtensions.ENABLE_GAZE_KEY, Juniper.StageExtensions.ENABLE_HANDS_KEY, Juniper.StageExtensions.ENABLE_MOUSE_KEY, Juniper.StageExtensions.ENABLE_TOUCH_KEY, Juniper.StageExtensions.EnableControllers(), Juniper.StageExtensions.EnableGaze(), Juniper.StageExtensions.EnableHands(), Juniper.StageExtensions.EnableMouse(), Juniper.StageExtensions.EnableTouch(), Juniper.StageExtensions.gazePointer, Juniper.StageExtensions.handTrackers, Juniper.StageExtensions.Install(), Juniper.StageExtensions.motionControllers, Juniper.StageExtensions.mouse, and Juniper.StageExtensions.touches.
EnableControllers()
void Juniper.StageExtensions.EnableControllers (bool value) inline private
Definition at line 170 of file StageExtensions.cs.
         {
             foreach (var motionController in motionControllers)
             {
                 motionController.SetActive(value);
             }
             PlayerPrefs.SetInt(ENABLE_CONTROLLERS_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.StageExtensions.ENABLE_CONTROLLERS_KEY, and Juniper.StageExtensions.motionControllers.
Referenced by Juniper.StageExtensions.Awake().
EnableGaze()
void Juniper.StageExtensions.EnableGaze (bool value) inline private
Definition at line 143 of file StageExtensions.cs.
         {
             gazePointer.SetActive(value);
             PlayerPrefs.SetInt(ENABLE_GAZE_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.StageExtensions.ENABLE_GAZE_KEY, and Juniper.StageExtensions.gazePointer.
Referenced by Juniper.StageExtensions.Awake().
EnableHands()
void Juniper.StageExtensions.EnableHands (bool value) inline private
Definition at line 160 of file StageExtensions.cs.
         {
             foreach (var handTracker in handTrackers)
             {
                 handTracker.SetActive(value);
             }
             PlayerPrefs.SetInt(ENABLE_HANDS_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.StageExtensions.ENABLE_HANDS_KEY, and Juniper.StageExtensions.handTrackers.
Referenced by Juniper.StageExtensions.Awake().
EnableMouse()
void Juniper.StageExtensions.EnableMouse (bool value) inline private
Definition at line 136 of file StageExtensions.cs.
         {
             mouse.SetActive(value);
             PlayerPrefs.SetInt(ENABLE_MOUSE_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.StageExtensions.ENABLE_MOUSE_KEY, and Juniper.StageExtensions.mouse.
Referenced by Juniper.StageExtensions.Awake().
EnableTouch()
void Juniper.StageExtensions.EnableTouch (bool value) inline private
Definition at line 150 of file StageExtensions.cs.
         {
             foreach (var touch in touches)
             {
                 touch.SetActive(value);
             }
             PlayerPrefs.SetInt(ENABLE_TOUCH_KEY, value ? 1 : 0);
             PlayerPrefs.Save();
         }
References Juniper.StageExtensions.ENABLE_TOUCH_KEY, and Juniper.StageExtensions.touches.
Referenced by Juniper.StageExtensions.Awake().
FixedUpdate()
void Juniper.StageExtensions.FixedUpdate () inline
Definition at line 329 of file StageExtensions.cs.
         {
 #if UNITY_MODULES_PHYSICS
             if (usePhysicsBasedMovement)
             {
                 var acceleration = (velocity - BodyPhysics.velocity) / Time.fixedDeltaTime;
                 BodyPhysics.AddForce(acceleration, ForceMode.Acceleration);
             }
             else
             {
 #endif
                 transform.position += velocity * Time.fixedDeltaTime;
 #if UNITY_MODULES_PHYSICS
             }
 #endif
             var userCenter = Head.position - transform.position;
 #if UNITY_MODULES_PHYSICS
             if (usePhysicsBasedMovement)
             {
                 var center = userCenter;
                 center.y = -0.5f * defaultAvatarHeight;
                 BodyShape.center = Quaternion.Inverse(transform.rotation) * center;
                 // Make the hands follow the camera position, but not the rotation. On Daydream
                 // systems, the system can figure out the right orientation for the controller as
                 // you rotate your body in place, but it can't figure out the position relative
                 // to the 6DOF tracking of the headset.
                 Body.position = BodyShape.transform.position + userCenter;
             }
 #else
             Body.position = userCenter;
 #endif
 #if !MAGIC_LEAP
             Hands.position = Body.position;
 #endif
         }
References Juniper.StageExtensions.Body, Juniper.StageExtensions.defaultAvatarHeight, Juniper.StageExtensions.Head, and Juniper.StageExtensions.velocity.
Install()
void Juniper.StageExtensions.Install (bool reset) inline
Implements Juniper.IInstallable.
Definition at line 213 of file StageExtensions.cs.
         {
             reset &= Application.isEditor;
             gameObject.layer = LayerMask.NameToLayer("Ignore Raycast");
             Head = this.EnsureTransform("Head (Camera)");
             var headShadow = Head.EnsureTransform("HeadShadow", () =>
                 MakeShadowCaster(
                     PrimitiveType.Sphere,
                     new Vector3(0.384284f, 0.3163f, 0.3831071f)));
             headShadow.Value.EnsureTransform("Goggles", () =>
                 MakeShadowCaster(
                     PrimitiveType.Cube,
                     new Vector3(0.85f, 0.5f, 0.5f),
                     new Vector3(0, 0, 0.311f)));
             Hands = this.EnsureTransform("Hands");
             Body = this.EnsureTransform("Body", () =>
                 MakeShadowCaster(
                     PrimitiveType.Capsule,
                     new Vector3(0.5f, 0.5f * defaultAvatarHeight, 0.5f)));
 #if UNITY_MODULES_PHYSICS
             BodyShape = this.EnsureComponent<CapsuleCollider>((bodyShape) =>
             {
                 bodyShape.SetMaterial(shoes);
                 bodyShape.height = defaultAvatarHeight;
                 bodyShape.radius = 0.25f;
                 bodyShape.direction = (int)CartesianAxis.Y;
             });
             BodyPhysics = this.EnsureComponent<Rigidbody>((phys) =>
             {
                 phys.mass = 80;
                 phys.constraints = RigidbodyConstraints.FreezeRotation;
             });
             BodyPhysics.useGravity = false;
             var grounder = BodyPhysics.EnsureComponent<Grounded>().Value;
             grounder.WhenGrounded(() =>
             {
                 BodyPhysics.useGravity = useGravity;
                 grounder.Destroy();
             });
 #endif
             this.WithLock(() =>
             {
                 gazePointer = MakePointer<GazePointer>(Head, "GazePointer");
                 mouse = MakePointer<Mouse>(Head, "Mouse");
                 touches = new TouchPoint[10];
                 for (var i = 0; i < touches.Length; ++i)
                 {
                     touches[i] = MakePointer<TouchPoint>(Head, "Touches/TouchPoint" + i);
                     touches[i].fingerID = i;
                 }
                 motionControllers = MotionController.MakeMotionControllers(name =>
                     MakePointer<MotionController>(Hands, name));
                 handTrackers = HandTracker.MakeHandTrackers(name =>
                     MakePointer<HandTracker>(Hands, name));
             });
             this.RemoveComponent<AbstractVelocityLocomotion>();
             gameObject.AddComponent<DefaultLocomotion>();
         }
References Juniper.StageExtensions.Body, Juniper.StageExtensions.defaultAvatarHeight, Juniper.Input.Pointers.Screen.TouchPoint.fingerID, Juniper.StageExtensions.gazePointer, Juniper.StageExtensions.handTrackers, Juniper.StageExtensions.Head, Juniper.Input.Pointers.Motion.HandTracker.MakeHandTrackers(), Juniper.Input.Pointers.Motion.MotionController.MakeMotionControllers(), Juniper.StageExtensions.MakeShadowCaster(), Juniper.StageExtensions.motionControllers, Juniper.StageExtensions.mouse, Juniper.StageExtensions.touches, and Juniper.Anchoring.Grounded.WhenGrounded().
Referenced by Juniper.StageExtensions.Awake(), and Juniper.StageExtensions.Reinstall().
MakePointer< T >()
T Juniper.StageExtensions.MakePointer< T > (Transform parent, string path) inline
Type Constraints
T : Component
T : IPointerDevice
Definition at line 290 of file StageExtensions.cs.
                     : Component, IPointerDevice
         {
             var trans = parent.EnsureTransform(path).Value;
             return trans.EnsureComponent<T>().Value;
         }
MakeShadowCaster()
static GameObject Juniper.StageExtensions.MakeShadowCaster (PrimitiveType type, Vector3? scale, Vector3? position = null) inline static private
Definition at line 194 of file StageExtensions.cs.
         {
             var caster = GameObject.CreatePrimitive(type);
             caster.transform.localScale = scale ?? Vector3.one;
             caster.transform.localPosition = position ?? Vector3.zero;
             var casterRenderer = caster.GetComponent<Renderer>();
             casterRenderer.lightProbeUsage = LightProbeUsage.Off;
             casterRenderer.reflectionProbeUsage = ReflectionProbeUsage.Off;
             casterRenderer.shadowCastingMode = ShadowCastingMode.ShadowsOnly;
             casterRenderer.receiveShadows = false;
             casterRenderer.motionVectorGenerationMode = MotionVectorGenerationMode.ForceNoMotion;
 #if UNITY_MODULES_PHYSICS
             caster.GetComponent<Collider>()?.Destroy();
 #endif
             return caster;
         }
Referenced by Juniper.StageExtensions.Install().
Reinstall()
virtual void Juniper.StageExtensions.Reinstall () inline virtual
Implements Juniper.IInstallable.
Definition at line 180 of file StageExtensions.cs.
         {
             Install(true);
         }
References Juniper.StageExtensions.Install().
Referenced by Juniper.StageExtensions.Reset().
Reset()
void Juniper.StageExtensions.Reset () inline
Definition at line 187 of file StageExtensions.cs.
         {
             Reinstall();
         }
References Juniper.StageExtensions.Reinstall().
RotateView()
void Juniper.StageExtensions.RotateView (Quaternion dQuat, float minX, float maxX) inline
Definition at line 297 of file StageExtensions.cs.
         {
             var quat = Head.rotation * dQuat;
             var eul = quat.eulerAngles;
             transform.localRotation = Quaternion.AngleAxis(eul.y, Vector3.up);
             var x = eul.x;
             if (x > 180)
             {
                 x -= 360;
             }
             x = Mathf.Max(minX, Mathf.Min(maxX, x));
             Head.localRotation = Quaternion.AngleAxis(x, Vector3.right);
         }
References Juniper.StageExtensions.Head.
Referenced by Juniper.Input.CameraControl.CheckMode().
SetVelocity()
void Juniper.StageExtensions.SetVelocity (Vector3 v) inline
Definition at line 317 of file StageExtensions.cs.
         {
             velocity = Body.rotation * v;
 #if UNITY_MODULES_PHYSICS
             if (usePhysicsBasedMovement)
             {
                 velocity.y = BodyPhysics.velocity.y;
             }
 #endif
         }
References Juniper.StageExtensions.Body, and Juniper.StageExtensions.velocity.
Referenced by Juniper.Input.AbstractVelocityLocomotion.Update().
Uninstall()
void Juniper.StageExtensions.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 286 of file StageExtensions.cs.
         {
         }
Member Data Documentation
Body
Transform Juniper.StageExtensions.Body private
Definition at line 75 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.FixedUpdate(), Juniper.StageExtensions.Install(), and Juniper.StageExtensions.SetVelocity().
defaultAvatarHeight
float Juniper.StageExtensions.defaultAvatarHeight = 1.75f
When running on systems that do not understand the relationship between the camera and the ground (marker-tracking AR, 3DOF VR), this is the height that is used for the camera off of the ground.
Definition at line 29 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.FixedUpdate(), and Juniper.StageExtensions.Install().
ENABLE_CONTROLLERS_KEY
const string Juniper.StageExtensions.ENABLE_CONTROLLERS_KEY = "MotionControllers" private
Definition at line 58 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), and Juniper.StageExtensions.EnableControllers().
ENABLE_GAZE_KEY
const string Juniper.StageExtensions.ENABLE_GAZE_KEY = "GazePointer" private
Definition at line 54 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), and Juniper.StageExtensions.EnableGaze().
ENABLE_HANDS_KEY
const string Juniper.StageExtensions.ENABLE_HANDS_KEY = "HandPointers" private
Definition at line 57 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), and Juniper.StageExtensions.EnableHands().
ENABLE_MOUSE_KEY
const string Juniper.StageExtensions.ENABLE_MOUSE_KEY = "MousePointer" private
Definition at line 55 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), and Juniper.StageExtensions.EnableMouse().
ENABLE_TOUCH_KEY
const string Juniper.StageExtensions.ENABLE_TOUCH_KEY = "TouchPointers" private
Definition at line 56 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), and Juniper.StageExtensions.EnableTouch().
gazePointer
GazePointer Juniper.StageExtensions.gazePointer private
Definition at line 68 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), Juniper.StageExtensions.EnableGaze(), and Juniper.StageExtensions.Install().
Hands
Transform Juniper.StageExtensions.Hands private
Definition at line 74 of file StageExtensions.cs.
handTrackers
HandTracker [] Juniper.StageExtensions.handTrackers private
Definition at line 72 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), Juniper.StageExtensions.EnableHands(), and Juniper.StageExtensions.Install().
Head
Transform Juniper.StageExtensions.Head private
Definition at line 73 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.FixedUpdate(), Juniper.StageExtensions.Install(), and Juniper.StageExtensions.RotateView().
motionControllers
MotionController [] Juniper.StageExtensions.motionControllers private
Definition at line 71 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), Juniper.StageExtensions.EnableControllers(), and Juniper.StageExtensions.Install().
mouse
Mouse Juniper.StageExtensions.mouse private
Definition at line 69 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), Juniper.StageExtensions.EnableMouse(), and Juniper.StageExtensions.Install().
touches
TouchPoint [] Juniper.StageExtensions.touches private
Definition at line 70 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.Awake(), Juniper.StageExtensions.EnableTouch(), and Juniper.StageExtensions.Install().
velocity
Vector3 Juniper.StageExtensions.velocity private
Definition at line 315 of file StageExtensions.cs.
Referenced by Juniper.StageExtensions.FixedUpdate(), and Juniper.StageExtensions.SetVelocity().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/StageExtensions.cs