Juniper: Juniper.Unity.World.LightEstimation.LightMeasurement Class Reference
Juniper.Unity.World.LightEstimation.LightMeasurement Class Reference
Abstracts the measurement of light intensity from camera frames for Augmented Reality Light Estimation. This component executes in edit mode.
Public Member Functions
override void Awake ()
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
override bool Install (bool reset)
override void Uninstall ()
virtual void Reinstall ()
void Reset ()
void Update ()
Check to see if the ARCore light estimation has been updated.
Public Attributes
bool useCustomAnalyzer
Set to true to use the custom image analyzer when running Vuforia. This is mostly only useful on Android for Vuforia v7.1.
bool useFake
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
float Intensity = 0.8f
The fake intensity value to use if UseFakeIntensity is true.
Color Color = Color.white
The fake color to use if UseFakeIntensity is true.
bool DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Protected Member Functions
override void InternalUpdate ()
override void PrintDebugReport ()
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
virtual void UpdateMeasurement ()
Protected Attributes
override bool UseFakeIntensity
float lastIntensity
Light estimate updates happen concurrently with frame updates. This value stores the last light intesity measurement that was calculated, for use in the current render frame.
Color lastColor
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
Properties
Color ColorEstimate [get]
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
float IntensityEstimate [get]
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Detailed Description
Abstracts the measurement of light intensity from camera frames for Augmented Reality Light Estimation. This component executes in edit mode.
Definition at line 10 of file LightMeasurement.cs.
Member Function Documentation
Awake()
override void Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.Awake () inline virtual inherited
Find the current XR system configuration, and setup the correct light estimation functions for the current platform.
Reimplemented from Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.
Definition at line 50 of file VuforiaLightMeasurement.cs.
         {
             base.Awake();
             if (Application.isPlaying)
             {
                 if (VuforiaUnityExt.HasLightEstimation && !useCustomAnalyzer)
                 {
                     StartCoroutine(GetIlluminationManagerCoroutine());
                 }
                 else
                 {
                     analyzer.imageAnalyzer = GetAveragePixelIntensity;
                 }
             }
         }
References Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.analyzer, Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetAveragePixelIntensity(), Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetIlluminationManagerCoroutine(), Vuforia.VuforiaUnityExt.HasLightEstimation, Juniper.Unity.Imaging.VuforiaImageAnalyzer.imageAnalyzer, and Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.useCustomAnalyzer.
Install()
override bool Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.Install (bool reset) inline virtual inherited
Reimplemented from Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.
Definition at line 67 of file VuforiaLightMeasurement.cs.
         {
             var baseInstall = base.Install(reset);
             analyzer = this.EnsureComponent<VuforiaImageAnalyzer>();
             return baseInstall;
         }
References Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.analyzer.
InternalUpdate()
override void Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.InternalUpdate () inline protected inherited
Definition at line 83 of file VuforiaLightMeasurement.cs.
         {
             base.InternalUpdate();
             if (illumination != null)
             {
                 if (illumination.AmbientIntensity != null)
                 {
                     lastIntensity = illumination.AmbientIntensity.Value / 1000f;
                 }
                 if (illumination.AmbientColorTemperature != null)
                 {
                     lastColor = illumination.AmbientColorTemperature.Value.FromKelvinToColor();
                 }
             }
         }
References Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.illumination, Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastColor, and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastIntensity.
PrintDebugReport()
override void Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.PrintDebugReport () inline protected virtual inherited
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Reimplemented from Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.
Definition at line 157 of file VuforiaLightMeasurement.cs.
         {
             base.PrintDebugReport();
             if (illumination == null)
             {
                 if (analyzer == null)
                 {
                     ScreenDebugger.Print("No illumination manager or image analyzer");
                 }
                 else
                 {
                     if (!analyzer.Running)
                     {
                         ScreenDebugger.Print("Image analyzer is not running");
                     }
                     ScreenDebugger.Print("Image analyzer image format is {0}", VuforiaImageAnalyzer.ImageFormat);
                 }
             }
             else
             {
                 if (illumination.AmbientIntensity == null)
                 {
                     ScreenDebugger.Print("Illumination manager doesn't have an estimate");
                 }
             }
         }
References Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.analyzer, Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.illumination, Juniper.Unity.Imaging.VuforiaImageAnalyzer.ImageFormat, System.ScreenDebugger.Print(), and Juniper.Data.AbstractBackgroundRepeatingThread.Running.
Reinstall()
virtual void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reinstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 94 of file AbstractLightMeasurement.cs.
         {
             Install(true);
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Install().
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reset().
Reset()
void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reset () inline inherited
Definition at line 101 of file AbstractLightMeasurement.cs.
         {
             Reinstall();
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Reinstall().
Uninstall()
override void Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.Uninstall () inline virtual inherited
Reimplemented from Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.
Definition at line 76 of file VuforiaLightMeasurement.cs.
         {
             base.Uninstall();
             this.RemoveComponent<VuforiaImageAnalyzer>();
         }
Update()
void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update () inline inherited
Check to see if the ARCore light estimation has been updated.
Definition at line 130 of file AbstractLightMeasurement.cs.
         {
             if (UseFakeIntensity)
             {
                 SetFakeValues();
             }
             else
             {
                 UpdateMeasurement();
             }
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.DebugReport, Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues(), Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UpdateMeasurement(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UseFakeIntensity.
UpdateMeasurement()
virtual void Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.UpdateMeasurement () inline protected virtual inherited
Definition at line 147 of file AbstractLightMeasurement.cs.
         {
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update().
Member Data Documentation
Color
Color Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Color = Color.white inherited
The fake color to use if UseFakeIntensity is true.
Definition at line 50 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetAveragePixelIntensity(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
DebugReport
bool Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.DebugReport inherited
When set to true, the Update loop will include printing out the internal values of the component;
Definition at line 55 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Update().
Intensity
float Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.Intensity = 0.8f inherited
The fake intensity value to use if UseFakeIntensity is true.
Definition at line 45 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
lastColor
Color Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastColor protected inherited
Light estimate updates happen concurrently with frame updates. This value stores the last light color measurement that was calculated, for use in the current render frame.
Definition at line 21 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetAveragePixelIntensity(), Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.InternalUpdate(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
lastIntensity
float Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.lastIntensity protected inherited
Light estimate updates happen concurrently with frame updates. This value stores the last light intesity measurement that was calculated, for use in the current render frame.
Definition at line 15 of file AbstractLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.GetAveragePixelIntensity(), Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.InternalUpdate(), and Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.SetFakeValues().
useCustomAnalyzer
bool Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.useCustomAnalyzer inherited
Set to true to use the custom image analyzer when running Vuforia. This is mostly only useful on Android for Vuforia v7.1.
Definition at line 17 of file VuforiaLightMeasurement.cs.
Referenced by Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.Awake().
useFake
bool Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.useFake inherited
When set to true, the light estimate values this component returns will be fake values set in the Unity Editor below.
Definition at line 27 of file AbstractLightMeasurement.cs.
UseFakeIntensity
override bool Juniper.Unity.World.LightEstimation.VuforiaLightMeasurement.UseFakeIntensity protected inherited
Initial value:
=>
            base.UseFakeIntensity
            || (illumination == null && analyzer == null)
            || (illumination != null && illumination.AmbientIntensity == null)
            || (analyzer != null
                && (!analyzer.Running || VuforiaImageAnalyzer.ImageFormat == null))
Definition at line 43 of file VuforiaLightMeasurement.cs.
Property Documentation
ColorEstimate
Color Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.ColorEstimate get inherited
Subsystems with light estimation capability should override this method to return the light temperature. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light color estimate.
Definition at line 63 of file AbstractLightMeasurement.cs.
         {
             get
             {
                 return lastColor;
             }
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.Unity.World.LightEstimation.AbstractLightEstimate.Update().
IntensityEstimate
float Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.IntensityEstimate get inherited
Subsystems with light estimation capability should override this method to return the estimation. Otherwise, a default value is returned that matches a typical, sunny day.
Returns
The light intensity estimate.
Definition at line 76 of file AbstractLightMeasurement.cs.
         {
             get
             {
                 return lastIntensity;
             }
         }
Referenced by Juniper.Unity.World.LightEstimation.AbstractLightMeasurement.PrintDebugReport(), and Juniper.Unity.World.LightEstimation.AbstractLightEstimate.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/World/LightEstimation/LightMeasurement.cs