Juniper: Juniper.StateControllerTests Class Reference
Juniper.StateControllerTests Class Reference
Classes
class MockStateController
Public Member Functions
void SetUp ()
void TearDown ()
void EnterActivatesObject ()
void EnterEnablesObject ()
void EnterFiresEntering ()
IEnumerator EnterFiresEntered ()
void EnterDoesntFireExiting ()
IEnumerator EnterDoesntFireExited ()
IEnumerator EnterCompletesAsynchronously ()
IEnumerator EnterDoesntDisable ()
IEnumerator EnterDoesntDeactivate ()
IEnumerator ExitFiresExiting ()
IEnumerator ExitFiresExited ()
IEnumerator ExitDoesntFireEntering ()
IEnumerator ExitDoesntFireEntered ()
IEnumerator ExitCompletesAsynchronously ()
IEnumerator ExitDisables ()
IEnumerator ExitDoesntDeactivate ()
void SetEnabledFiresEntering ()
IEnumerator SetEnabledFiresEntered ()
void SetEnabledDoesntFireExiting ()
IEnumerator SetEnabledDoesntFireExited ()
IEnumerator SetEnabledCompletesAsynchronously ()
IEnumerator SetEnabledDoesntDisable ()
IEnumerator SetEnabledDoesntDeactivate ()
Private Attributes
GameObject go
MockStateController stater
Detailed Description
Definition at line 11 of file StateControllerTests.cs.
Member Function Documentation
EnterActivatesObject()
void Juniper.StateControllerTests.EnterActivatesObject () inline
Definition at line 34 of file StateControllerTests.cs.
         {
             stater.Enter();
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.go, and Juniper.StateControllerTests.stater.
EnterCompletesAsynchronously()
IEnumerator Juniper.StateControllerTests.EnterCompletesAsynchronously () inline
Definition at line 97 of file StateControllerTests.cs.
         {
             stater.Enter();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.IsComplete);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.IsComplete, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
EnterDoesntDeactivate()
IEnumerator Juniper.StateControllerTests.EnterDoesntDeactivate () inline
Definition at line 124 of file StateControllerTests.cs.
         {
             stater.Enter();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.go, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
EnterDoesntDisable()
IEnumerator Juniper.StateControllerTests.EnterDoesntDisable () inline
Definition at line 109 of file StateControllerTests.cs.
         {
             stater.Enter();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.enabled);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
EnterDoesntFireExited()
IEnumerator Juniper.StateControllerTests.EnterDoesntFireExited () inline
Definition at line 83 of file StateControllerTests.cs.
         {
             Assert.IsFalse(stater.FiredExited);
             stater.Enter();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsFalse(stater.FiredExited);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.FiredExited, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
EnterDoesntFireExiting()
void Juniper.StateControllerTests.EnterDoesntFireExiting () inline
Definition at line 73 of file StateControllerTests.cs.
         {
             Assert.IsFalse(stater.FiredExiting);
             stater.Enter();
             Assert.IsFalse(stater.FiredExiting);
         }
References Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.FiredExiting, and Juniper.StateControllerTests.stater.
EnterEnablesObject()
void Juniper.StateControllerTests.EnterEnablesObject () inline
Definition at line 42 of file StateControllerTests.cs.
         {
             stater.Enter();
             Assert.IsTrue(stater.enabled);
         }
References Juniper.AbstractStateController.Enter(), and Juniper.StateControllerTests.stater.
EnterFiresEntered()
IEnumerator Juniper.StateControllerTests.EnterFiresEntered () inline
Definition at line 59 of file StateControllerTests.cs.
         {
             Assert.IsFalse(stater.FiredEntered);
             stater.Enter();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.FiredEntered);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.FiredEntered, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
EnterFiresEntering()
void Juniper.StateControllerTests.EnterFiresEntering () inline
Definition at line 50 of file StateControllerTests.cs.
         {
             Assert.IsFalse(stater.FiredEntering);
             stater.Enter();
             Assert.IsTrue(stater.FiredEntering);
         }
References Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.FiredEntering, and Juniper.StateControllerTests.stater.
ExitCompletesAsynchronously()
IEnumerator Juniper.StateControllerTests.ExitCompletesAsynchronously () inline
Definition at line 213 of file StateControllerTests.cs.
         {
             stater.Enter();
             stater.Complete();
             yield return stater.Waiter;
             stater.Exit();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.IsComplete);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.Exit(), Juniper.StateControllerTests.MockStateController.IsComplete, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
ExitDisables()
IEnumerator Juniper.StateControllerTests.ExitDisables () inline
Definition at line 229 of file StateControllerTests.cs.
         {
             stater.Enter();
             stater.Complete();
             yield return stater.Waiter;
             stater.Exit();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsFalse(stater.enabled);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.Exit(), Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
ExitDoesntDeactivate()
IEnumerator Juniper.StateControllerTests.ExitDoesntDeactivate () inline
Definition at line 246 of file StateControllerTests.cs.
         {
             stater.Enter();
             stater.Complete();
             yield return stater.Waiter;
             stater.Exit();
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.Exit(), Juniper.StateControllerTests.go, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
ExitDoesntFireEntered()
IEnumerator Juniper.StateControllerTests.ExitDoesntFireEntered () inline
Definition at line 195 of file StateControllerTests.cs.
         {
             stater.Enter();
             stater.Complete();
             yield return stater.Waiter;
             stater.Exit();
             Assert.IsFalse(stater.FiredEntered);
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsFalse(stater.FiredEntered);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.Exit(), Juniper.StateControllerTests.MockStateController.FiredEntered, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
ExitDoesntFireEntering()
IEnumerator Juniper.StateControllerTests.ExitDoesntFireEntering () inline
Definition at line 177 of file StateControllerTests.cs.
         {
             stater.Enter();
             stater.Complete();
             yield return stater.Waiter;
             stater.Exit();
             Assert.IsFalse(stater.FiredEntering);
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsFalse(stater.FiredEntering);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.Exit(), Juniper.StateControllerTests.MockStateController.FiredEntering, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
ExitFiresExited()
IEnumerator Juniper.StateControllerTests.ExitFiresExited () inline
Definition at line 157 of file StateControllerTests.cs.
         {
             stater.Enter();
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.FiredExited);
             stater.Exit();
             Assert.IsFalse(stater.FiredExited);
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.FiredExited);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.Exit(), Juniper.StateControllerTests.MockStateController.FiredExited, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
ExitFiresExiting()
IEnumerator Juniper.StateControllerTests.ExitFiresExiting () inline
Definition at line 138 of file StateControllerTests.cs.
         {
             stater.Enter();
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.FiredExiting);
             stater.Exit();
             Assert.IsTrue(stater.FiredExiting);
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.StateControllerTests.MockStateController.Exit(), Juniper.StateControllerTests.MockStateController.FiredExiting, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
SetEnabledCompletesAsynchronously()
IEnumerator Juniper.StateControllerTests.SetEnabledCompletesAsynchronously () inline
Definition at line 317 of file StateControllerTests.cs.
         {
             go.Activate();
             stater.enabled = true;
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.IsComplete);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.StateControllerTests.go, Juniper.StateControllerTests.MockStateController.IsComplete, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
SetEnabledDoesntDeactivate()
IEnumerator Juniper.StateControllerTests.SetEnabledDoesntDeactivate () inline
Definition at line 349 of file StateControllerTests.cs.
         {
             go.Activate();
             stater.enabled = true;
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(go.activeInHierarchy);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.StateControllerTests.go, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
SetEnabledDoesntDisable()
IEnumerator Juniper.StateControllerTests.SetEnabledDoesntDisable () inline
Definition at line 333 of file StateControllerTests.cs.
         {
             go.Activate();
             stater.enabled = true;
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.enabled);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.StateControllerTests.go, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
SetEnabledDoesntFireExited()
IEnumerator Juniper.StateControllerTests.SetEnabledDoesntFireExited () inline
Definition at line 298 of file StateControllerTests.cs.
         {
             go.Activate();
             Assert.IsFalse(stater.FiredExited);
             stater.enabled = true;
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsFalse(stater.FiredExited);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.StateControllerTests.MockStateController.FiredExited, Juniper.StateControllerTests.go, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
SetEnabledDoesntFireExiting()
void Juniper.StateControllerTests.SetEnabledDoesntFireExiting () inline
Definition at line 288 of file StateControllerTests.cs.
         {
             go.Activate();
             Assert.IsFalse(stater.FiredExiting);
             stater.enabled = true;
             Assert.IsFalse(stater.FiredExiting);
         }
References Juniper.StateControllerTests.MockStateController.FiredExiting, Juniper.StateControllerTests.go, and Juniper.StateControllerTests.stater.
SetEnabledFiresEntered()
IEnumerator Juniper.StateControllerTests.SetEnabledFiresEntered () inline
Definition at line 273 of file StateControllerTests.cs.
         {
             go.Activate();
             Assert.IsFalse(stater.FiredEntered);
             stater.enabled = true;
             yield return null;
             stater.Complete();
             yield return stater.Waiter;
             Assert.IsFalse(stater.IsTimedOut, "timed out");
             Assert.IsTrue(stater.FiredEntered);
         }
References Juniper.StateControllerTests.MockStateController.Complete(), Juniper.StateControllerTests.MockStateController.FiredEntered, Juniper.StateControllerTests.go, Juniper.StateControllerTests.MockStateController.IsTimedOut, Juniper.StateControllerTests.stater, and Juniper.AbstractStateController.Waiter.
SetEnabledFiresEntering()
void Juniper.StateControllerTests.SetEnabledFiresEntering () inline
Definition at line 263 of file StateControllerTests.cs.
         {
             go.Activate();
             Assert.IsFalse(stater.FiredEntering);
             stater.enabled = true;
             Assert.IsTrue(stater.FiredEntering);
         }
References Juniper.StateControllerTests.MockStateController.FiredEntering, Juniper.StateControllerTests.go, and Juniper.StateControllerTests.stater.
SetUp()
void Juniper.StateControllerTests.SetUp () inline
Definition at line 14 of file StateControllerTests.cs.
         {
             go = Utils.CreatePrimitive(PrimitiveType.Cube);
             go.Deactivate();
             stater = go.AddComponent<MockStateController>();
             stater.enabled = false;
         }
References Juniper.StateControllerTests.go, and Juniper.StateControllerTests.stater.
TearDown()
void Juniper.StateControllerTests.TearDown () inline
Definition at line 24 of file StateControllerTests.cs.
         {
             stater.Destroy();
             stater = null;
             go.Destroy();
             go = null;
         }
References Juniper.StateControllerTests.go, and Juniper.StateControllerTests.stater.
Member Data Documentation
go
GameObject Juniper.StateControllerTests.go private
Definition at line 364 of file StateControllerTests.cs.
Referenced by Juniper.StateControllerTests.EnterActivatesObject(), Juniper.StateControllerTests.EnterDoesntDeactivate(), Juniper.StateControllerTests.ExitDoesntDeactivate(), Juniper.StateControllerTests.SetEnabledCompletesAsynchronously(), Juniper.StateControllerTests.SetEnabledDoesntDeactivate(), Juniper.StateControllerTests.SetEnabledDoesntDisable(), Juniper.StateControllerTests.SetEnabledDoesntFireExited(), Juniper.StateControllerTests.SetEnabledDoesntFireExiting(), Juniper.StateControllerTests.SetEnabledFiresEntered(), Juniper.StateControllerTests.SetEnabledFiresEntering(), Juniper.StateControllerTests.SetUp(), and Juniper.StateControllerTests.TearDown().
stater
MockStateController Juniper.StateControllerTests.stater private
Definition at line 366 of file StateControllerTests.cs.
Referenced by Juniper.StateControllerTests.EnterActivatesObject(), Juniper.StateControllerTests.EnterCompletesAsynchronously(), Juniper.StateControllerTests.EnterDoesntDeactivate(), Juniper.StateControllerTests.EnterDoesntDisable(), Juniper.StateControllerTests.EnterDoesntFireExited(), Juniper.StateControllerTests.EnterDoesntFireExiting(), Juniper.StateControllerTests.EnterEnablesObject(), Juniper.StateControllerTests.EnterFiresEntered(), Juniper.StateControllerTests.EnterFiresEntering(), Juniper.StateControllerTests.ExitCompletesAsynchronously(), Juniper.StateControllerTests.ExitDisables(), Juniper.StateControllerTests.ExitDoesntDeactivate(), Juniper.StateControllerTests.ExitDoesntFireEntered(), Juniper.StateControllerTests.ExitDoesntFireEntering(), Juniper.StateControllerTests.ExitFiresExited(), Juniper.StateControllerTests.ExitFiresExiting(), Juniper.StateControllerTests.SetEnabledCompletesAsynchronously(), Juniper.StateControllerTests.SetEnabledDoesntDeactivate(), Juniper.StateControllerTests.SetEnabledDoesntDisable(), Juniper.StateControllerTests.SetEnabledDoesntFireExited(), Juniper.StateControllerTests.SetEnabledDoesntFireExiting(), Juniper.StateControllerTests.SetEnabledFiresEntered(), Juniper.StateControllerTests.SetEnabledFiresEntering(), Juniper.StateControllerTests.SetUp(), and Juniper.StateControllerTests.TearDown().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Tests/Juniper/StateControllerTests.cs