Juniper: Juniper.World.GIS.Google.TimeZone.TimeZoneResponse Class Reference
Juniper.World.GIS.Google.TimeZone.TimeZoneResponse Class Reference
Public Member Functions
void GetObjectData (SerializationInfo info, StreamingContext context)
Protected Member Functions
TimeZoneResponse (SerializationInfo info, StreamingContext context)
Properties
HttpStatusCode Status [get]
string ErrorMessage [get]
long DstOffset [get]
long RawOffset [get]
string TimeZoneId [get]
string TimeZoneName [get]
Static Private Attributes
static readonly string STATUS_FIELD = nameof(Status).ToLowerInvariant()
static readonly string DST_OFFSET_FIELD = nameof(DstOffset).ToLowerInvariant()
static readonly string RAW_OFFSET_FIELD = nameof(RawOffset).ToLowerInvariant()
static readonly string TIME_ZONE_ID_FIELD = nameof(TimeZoneId).ToLowerInvariant()
static readonly string TIME_ZONE_NAME_FIELD = nameof(TimeZoneName).ToLowerInvariant()
static readonly string ERROR_MESSAGE_FIELD = nameof(ErrorMessage).ToLowerInvariant()
Detailed Description
Definition at line 10 of file TimeZoneResponse.cs.
Constructor & Destructor Documentation
TimeZoneResponse()
Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse (SerializationInfo info, StreamingContext context) inline protected
Definition at line 32 of file TimeZoneResponse.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Status = info.GetString(STATUS_FIELD).MapToStatusCode();
             if (Status == HttpStatusCode.OK)
             {
                 DstOffset = info.GetInt64(DST_OFFSET_FIELD);
                 RawOffset = info.GetInt64(RAW_OFFSET_FIELD);
                 TimeZoneId = info.GetString(TIME_ZONE_ID_FIELD);
                 TimeZoneName = info.GetString(TIME_ZONE_NAME_FIELD);
             }
             else if (Status != HttpStatusCode.NoContent)
             {
                 ErrorMessage = info.GetString(ERROR_MESSAGE_FIELD);
             }
         }
References Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.DST_OFFSET_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.DstOffset, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.ERROR_MESSAGE_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.ErrorMessage, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.RAW_OFFSET_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.RawOffset, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.Status, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.STATUS_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TIME_ZONE_ID_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TIME_ZONE_NAME_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneId, and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneName.
Member Function Documentation
GetObjectData()
void Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 54 of file TimeZoneResponse.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(STATUS_FIELD, Status.ToGoogleString());
             if (Status == HttpStatusCode.OK)
             {
                 info.AddValue(DST_OFFSET_FIELD, DstOffset);
                 info.AddValue(RAW_OFFSET_FIELD, RawOffset);
                 info.AddValue(TIME_ZONE_ID_FIELD, TimeZoneId);
                 info.AddValue(TIME_ZONE_NAME_FIELD, TimeZoneName);
             }
             else if (Status != HttpStatusCode.NoContent)
             {
                 info.AddValue(ERROR_MESSAGE_FIELD, ErrorMessage);
             }
         }
References Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.DST_OFFSET_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.DstOffset, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.ERROR_MESSAGE_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.ErrorMessage, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.RAW_OFFSET_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.RawOffset, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.Status, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.STATUS_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TIME_ZONE_ID_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TIME_ZONE_NAME_FIELD, Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneId, and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneName.
Member Data Documentation
DST_OFFSET_FIELD
readonly string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.DST_OFFSET_FIELD = nameof(DstOffset).ToLowerInvariant() static private
Definition at line 13 of file TimeZoneResponse.cs.
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
ERROR_MESSAGE_FIELD
readonly string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.ERROR_MESSAGE_FIELD = nameof(ErrorMessage).ToLowerInvariant() static private
Definition at line 17 of file TimeZoneResponse.cs.
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
RAW_OFFSET_FIELD
readonly string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.RAW_OFFSET_FIELD = nameof(RawOffset).ToLowerInvariant() static private
Definition at line 14 of file TimeZoneResponse.cs.
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
STATUS_FIELD
readonly string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.STATUS_FIELD = nameof(Status).ToLowerInvariant() static private
Definition at line 12 of file TimeZoneResponse.cs.
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
TIME_ZONE_ID_FIELD
readonly string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TIME_ZONE_ID_FIELD = nameof(TimeZoneId).ToLowerInvariant() static private
Definition at line 15 of file TimeZoneResponse.cs.
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
TIME_ZONE_NAME_FIELD
readonly string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TIME_ZONE_NAME_FIELD = nameof(TimeZoneName).ToLowerInvariant() static private
Definition at line 16 of file TimeZoneResponse.cs.
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
Property Documentation
DstOffset
long Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.DstOffset get
Definition at line 23 of file TimeZoneResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
ErrorMessage
string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.ErrorMessage get
Definition at line 21 of file TimeZoneResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
RawOffset
long Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.RawOffset get
Definition at line 25 of file TimeZoneResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
Status
HttpStatusCode Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.Status get
Definition at line 19 of file TimeZoneResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
TimeZoneId
string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneId get
Definition at line 27 of file TimeZoneResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
TimeZoneName
string Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneName get
Definition at line 29 of file TimeZoneResponse.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.GetObjectData(), and Juniper.World.GIS.Google.TimeZone.TimeZoneResponse.TimeZoneResponse().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/TimeZone/TimeZoneResponse.cs