Juniper: System.IO.PathExt Class Reference
System.IO.PathExt Class Reference
A static class containing a few functions that the normal System.IO.Path class does not contain.
Static Public Member Functions
static string FixPath (string path)
Converts paths specified in any combination of forward- or back-slashes to the correct slash for the current system.
static string [] PathParts (string path)
static string Abs2Rel (string fullPath, string directory)
Creates a file path that is relative to the currently-edited demo path.
static string GetLongExtension (string path)
static string GetShortExtension (string path)
static string RemoveShortExtension (string name)
static string RemoveLongExtension (string name)
static string Abs2Rel (string fullPath)
static string Rel2Abs (string relativePath, string directory)
Resolves an absolute path from a path that is relative to the currently-edited demo path.
static string Rel2Abs (string relativePath)
Static Private Member Functions
static string Remove (string name, string ext)
Static Private Attributes
static readonly char [] INVALID_CHARS
static readonly char [] INVALID_START_CHARS
Detailed Description
A static class containing a few functions that the normal System.IO.Path class does not contain.
Definition at line 9 of file PathExt.cs.
Member Function Documentation
Abs2Rel() [1/2]
static string System.IO.PathExt.Abs2Rel (string fullPath, string directory) inline static
Creates a file path that is relative to the currently-edited demo path.
Returns
The relative path.
Parameters
fullPath Full path.
directory The directory from which to consider the relative path. If no value is provided (i.e. null or empty string), then the current working directory is used.
Definition at line 71 of file PathExt.cs.
         {
             if (!Path.IsPathRooted(fullPath))
             {
                 return fullPath;
             }
             else
             {
                 if (string.IsNullOrEmpty(directory))
                 {
                     directory = Environment.CurrentDirectory;
                 }
                 var partsA = PathParts(directory);
                 var partsB = PathParts(fullPath);
                 var counter = 0;
                 while (counter < partsA.Length
                        && counter < partsB.Length
                        && partsA[counter] == partsB[counter])
                 {
                     ++counter;
                 }
                 if (counter == partsB.Length - 1)
                 {
                     return null;
                 }
                 else
                 {
                     var aLen = partsA.Length - counter;
                     var bLen = partsB.Length - counter;
                     var parts = new string[aLen + bLen];
                     for (var i = 0; i < aLen; ++i)
                     {
                         parts[i] = "..";
                     }
                     Array.Copy(partsB, counter, parts, aLen, bLen);
                     return Path.Combine(parts);
                 }
             }
         }
References System.IO.PathExt.PathParts().
Referenced by System.IO.PathExt.Abs2Rel().
Abs2Rel() [2/2]
static string System.IO.PathExt.Abs2Rel (string fullPath) inline static
Definition at line 177 of file PathExt.cs.
         {
             return Abs2Rel(fullPath, null);
         }
References System.IO.PathExt.Abs2Rel().
FixPath()
static string System.IO.PathExt.FixPath (string path) inline static
Converts paths specified in any combination of forward- or back-slashes to the correct slash for the current system.
Parameters
path The path to fix.
Returns
The same path, but with the wrong slashes replaced with the right slashes.
On Windows, if a path is specified with forward slashes, a value with backslashes is returned.
Definition at line 26 of file PathExt.cs.
         {
             path = path.NormalizePath();
             var parts = path.SplitX(Path.DirectorySeparatorChar);
             var sb = new StringBuilder();
             for (var i = 0; i < parts.Length; ++i)
             {
                 if (i > 0)
                 {
                     sb.Append(Path.DirectorySeparatorChar);
                 }
                 var subParts = i == 0
                     ? parts[i].Split(INVALID_START_CHARS)
                     : parts[i].Split(INVALID_CHARS);
                 for (var j = 0; j < subParts.Length; ++j)
                 {
                     if (j > 0)
                     {
                         sb.Append('_');
                     }
                     sb.Append(subParts[j]);
                 }
             }
             return sb.ToString();
         }
References System.IO.PathExt.INVALID_CHARS, and System.IO.PathExt.INVALID_START_CHARS.
Referenced by Juniper.ConfigurationManagement.JuniperPackage.Activate(), UnityEngine.ResourceExt.LoadAsset< T >(), and System.IO.PathExt.PathParts().
GetLongExtension()
static string System.IO.PathExt.GetLongExtension (string path) inline static
Definition at line 116 of file PathExt.cs.
         {
             if (path is null)
             {
                 throw new ArgumentNullException(nameof(path));
             }
             var i = path.IndexOf('.');
             if (i <= 0)
             {
                 return null;
             }
             else
             {
                 return path.Substring(i + 1);
             }
         }
Referenced by System.IO.PathExt.RemoveLongExtension().
GetShortExtension()
static string System.IO.PathExt.GetShortExtension (string path) inline static
Definition at line 134 of file PathExt.cs.
         {
             if (path is null)
             {
                 throw new ArgumentNullException(nameof(path));
             }
             var i = path.LastIndexOf('.');
             if (i <= 0)
             {
                 return null;
             }
             else
             {
                 return path.Substring(i + 1);
             }
         }
Referenced by Juniper.MediaType.AddExtension(), and System.IO.PathExt.RemoveShortExtension().
PathParts()
static string [] System.IO.PathExt.PathParts (string path) inline static
Definition at line 57 of file PathExt.cs.
         {
             return FixPath(path).SplitX(Path.DirectorySeparatorChar);
         }
References System.IO.PathExt.FixPath().
Referenced by System.IO.PathExt.Abs2Rel(), Juniper.Compression.CompressedFileInfoExt.Directories(), and System.IO.PathExt.Rel2Abs().
Rel2Abs() [1/2]
static string System.IO.PathExt.Rel2Abs (string relativePath, string directory) inline static
Resolves an absolute path from a path that is relative to the currently-edited demo path.
Returns
The absolute path.
Parameters
relativePath Relative path.
directory The directory from which to consider the relative path. If no value is provided (i.e. null or empty string), then the current working directory is used.
Definition at line 191 of file PathExt.cs.
         {
             if (Path.IsPathRooted(relativePath))
             {
                 return relativePath;
             }
             else
             {
                 if (string.IsNullOrEmpty(directory))
                 {
                     directory = Environment.CurrentDirectory;
                 }
                 var partsA = PathParts(directory).ToList();
                 var partsB = PathParts(relativePath).ToList();
                 while (partsA.Count > 0
                        && partsB.Count > 0
                        && partsB[0] == "..")
                 {
                     partsA.RemoveAt(partsA.Count - 1);
                     partsB.RemoveAt(0);
                 }
                 if (partsB.Count == 0)
                 {
                     return null;
                 }
                 else
                 {
                     var parts = partsA
                         .Concat(partsB)
                         .ToArray();
                     // Handle Windows drive letters
                     if (Path.VolumeSeparatorChar == ':' && parts[0].Last() == Path.VolumeSeparatorChar)
                     {
                         parts[0] += Path.DirectorySeparatorChar;
                         parts[0] += Path.DirectorySeparatorChar;
                     }
                     return Path.Combine(parts);
                 }
             }
         }
References System.IO.PathExt.PathParts().
Referenced by System.IO.PathExt.Rel2Abs().
Rel2Abs() [2/2]
static string System.IO.PathExt.Rel2Abs (string relativePath) inline static
Definition at line 237 of file PathExt.cs.
         {
             return Rel2Abs(relativePath, null);
         }
References System.IO.PathExt.Rel2Abs().
Remove()
static string System.IO.PathExt.Remove (string name, string ext) inline static private
Definition at line 152 of file PathExt.cs.
         {
             if (name is null)
             {
                 throw new ArgumentNullException(nameof(name));
             }
             if (ext is object)
             {
                 name = name.Substring(0, name.Length - ext.Length - 1);
             }
             return name;
         }
Referenced by System.IO.PathExt.RemoveLongExtension(), and System.IO.PathExt.RemoveShortExtension().
RemoveLongExtension()
static string System.IO.PathExt.RemoveLongExtension (string name) inline static
Definition at line 172 of file PathExt.cs.
         {
             return Remove(name, GetLongExtension(name));
         }
References System.IO.PathExt.GetLongExtension(), and System.IO.PathExt.Remove().
RemoveShortExtension()
static string System.IO.PathExt.RemoveShortExtension (string name) inline static
Definition at line 167 of file PathExt.cs.
         {
             return Remove(name, GetShortExtension(name));
         }
References System.IO.PathExt.GetShortExtension(), and System.IO.PathExt.Remove().
Referenced by Juniper.IO.FileCacheLayer.GetContentReferences(), and Juniper.IO.ZipFileCacheLayer.GetContentReferences().
Member Data Documentation
INVALID_CHARS
readonly char [] System.IO.PathExt.INVALID_CHARS static private
Initial value:
= Path.GetInvalidFileNameChars()
            .Where(c => c != Path.DirectorySeparatorChar)
            .ToArray()
Definition at line 11 of file PathExt.cs.
Referenced by System.IO.PathExt.FixPath().
INVALID_START_CHARS
readonly char [] System.IO.PathExt.INVALID_START_CHARS static private
Initial value:
= INVALID_CHARS
            .Where(c => c != ':')
            .ToArray()
Definition at line 15 of file PathExt.cs.
Referenced by System.IO.PathExt.FixPath().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/NETFX/IO/PathExt.cs