Juniper: Juniper.Speech.Azure.AbstractAzureRequest< MediaTypeT > Class Template Reference
Juniper.Speech.Azure.AbstractAzureRequest< MediaTypeT > Class Template Reference
Public Member Functions
override bool Equals (object obj)
bool Equals (ContentReference other)
override async Task< Stream > GetStreamAsync (IProgress prog=null)
override int GetHashCode ()
override string ToString ()
Static Public Member Functions
static bool operator== (ContentReference left, ContentReference right)
static bool operator != (ContentReference left, ContentReference right)
static operator string (ContentReference fileRef)
static FileInfo operator+ (DirectoryInfo directory, ContentReference fileRef)
static FileInfo operator+ (ContentReference fileRef, DirectoryInfo directory)
Public Attributes
override MediaType ContentType => MediaType
sealed override string CacheID
sealed override bool DoNotCache
Protected Member Functions
AbstractAzureRequest (HttpMethods method, string region, string component, string path, MediaTypeT contentType, bool hasRequestBody)
void SetQuery (string key, string value)
void SetQuery< U > (string key, U value)
void AddQuery (string key, string value)
void AddQuery< U > (string key, U value)
void RemoveQuery (string key)
bool RemoveQuery (string key, string value)
bool RemoveQuery< U > (string key, U value)
virtual void ModifyRequest (HttpWebRequest request)
virtual BodyInfo GetBodyInfo ()
virtual void WriteBody (Stream stream)
Static Protected Member Functions
static Uri AddPath (Uri baseURI, string path)
Protected Attributes
virtual Uri AuthenticatedURI => BaseURI
Properties
MediaTypeT MediaType [get]
virtual Uri BaseURI [get]
string? StandardRequestCacheID [get]
abstract string InternalCacheID [get]
string FileName [get]
Static Private Member Functions
static Uri MakeURI (string region, string component)
Detailed Description
Type Constraints
MediaTypeT : MediaType
Definition at line 8 of file AbstractAzureRequest.cs.
Constructor & Destructor Documentation
AbstractAzureRequest()
Juniper.Speech.Azure.AbstractAzureRequest< MediaTypeT >.AbstractAzureRequest (HttpMethods method, string region, string component, string path, MediaTypeT contentType, bool hasRequestBody) inline protected
Definition at line 16 of file AbstractAzureRequest.cs.
             : base(method, AddPath(MakeURI(region, component), path), contentType, hasRequestBody)
         { }
Member Function Documentation
AddPath()
static Uri Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.AddPath (Uri baseURI, string path) inline static protected inherited
Definition at line 16 of file AbstractRequest.cs.
         {
             var uriBuilder = new UriBuilder(baseURI);
             uriBuilder.Path = Path.Combine(uriBuilder.Path, path);
             return uriBuilder.Uri;
         }
AddQuery()
void Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.AddQuery (string key, string value) inline protected inherited
Definition at line 129 of file AbstractRequest.cs.
         {
             SetQuery(key, value, true);
         }
AddQuery< U >()
void Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.AddQuery< U > (string key, U value) inline protected inherited
Definition at line 134 of file AbstractRequest.cs.
         {
             SetQuery(key, value.ToString());
         }
Equals() [1/2]
override bool Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.Equals (object obj) inline inherited
Definition at line 47 of file AbstractRequest.cs.
         {
             return obj is object
                 && obj is AbstractRequest<MediaTypeT> req
                 && req.CacheID == CacheID;
         }
Equals() [2/2]
bool Juniper.IO.ContentReference.Equals (ContentReference other) inline inherited
Definition at line 78 of file ContentReference.cs.
         {
             return other is object
                 && other.ContentType == ContentType
                 && other.CacheID == CacheID;
         }
References Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
Referenced by Juniper.IO.ContentReference.Equals().
GetBodyInfo()
virtual BodyInfo Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.GetBodyInfo () inline protected virtual inherited
Definition at line 167 of file AbstractRequest.cs.
         {
             return null;
         }
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.GetStreamAsync().
GetHashCode()
override int Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.GetHashCode () inline inherited
Definition at line 214 of file AbstractRequest.cs.
         {
             var hashCode = 1106372483;
             hashCode = hashCode * -1521134295 + base.GetHashCode();
             hashCode = hashCode * -1521134295 + method.GetHashCode();
             hashCode = hashCode * -1521134295 + hasRequestBody.GetHashCode();
             hashCode = hashCode * -1521134295 + EqualityComparer<IDictionary<string, List<string>>>.Default.GetHashCode(queryParams);
             hashCode = hashCode * -1521134295 + EqualityComparer<MediaType>.Default.GetHashCode(ContentType);
             hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(CacheID);
             hashCode = hashCode * -1521134295 + EqualityComparer<Uri>.Default.GetHashCode(BaseURI);
             return hashCode;
         }
GetStreamAsync()
override async Task<Stream> Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.GetStreamAsync (IProgress prog = null) inline virtual inherited
Implements Juniper.IO.AbstractStreamSource.
Definition at line 174 of file AbstractRequest.cs.
         {
             var request = (HttpWebRequest)WebRequest.Create(AuthenticatedURI);
             request = request.Method(method);
             if (AuthenticatedURI.Scheme == "http")
             {
                 request.Header("Upgrade-Insecure-Requests", 1);
             }
             if (MediaType is object)
             {
                 request.Accept = MediaType;
             }
             ModifyRequest(request);
             if (hasRequestBody)
             {
                 var progs = prog.Split("Requesting", "Retrieving");
                 prog = progs[1];
                 await request.WriteBodyAsync(GetBodyInfo, WriteBody, progs[0])
                     .ConfigureAwait(false);
             }
             else
             {
                 request.ContentLength = 0;
             }
             var response = (HttpWebResponse)await request
                 .GetResponseAsync()
                 .ConfigureAwait(false);
             return new ProgressStream(
                 response.GetResponseStream(),
                 response.ContentLength,
                 prog, false);
         }
MakeURI()
static Uri Juniper.Speech.Azure.AbstractAzureRequest< MediaTypeT >.MakeURI (string region, string component) inline static private
Definition at line 11 of file AbstractAzureRequest.cs.
         {
             return new Uri($"https://{region}.{component}.microsoft.com/");
         }
ModifyRequest()
virtual void Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.ModifyRequest (HttpWebRequest request) inline protected virtual inherited
Reimplemented in Juniper.Speech.Azure.CognitiveServices.AbstractAzureSpeechRequest< MediaTypeT >.
Definition at line 165 of file AbstractRequest.cs.
 { }
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.GetStreamAsync().
operator !=()
static bool Juniper.IO.ContentReference.operator != (ContentReference left, ContentReference right) inline static inherited
Definition at line 16 of file ContentReference.cs.
         {
             return !(left == right);
         }
operator string()
static Juniper.IO.ContentReference.operator string (ContentReference fileRef) inline explicit static inherited
Definition at line 21 of file ContentReference.cs.
         {
             if (fileRef is null)
             {
                 return null;
             }
             return fileRef.ContentType.AddExtension(fileRef.CacheID);
         }
References Juniper.MediaType.AddExtension(), Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
operator+() [1/2]
static FileInfo Juniper.IO.ContentReference.operator+ (DirectoryInfo directory, ContentReference fileRef) inline static inherited
Definition at line 31 of file ContentReference.cs.
         {
             if (directory is null)
             {
                 return null;
             }
             if (fileRef is null)
             {
                 return null;
             }
             var fileName = (string)fileRef;
             return new FileInfo(Path.Combine(directory.FullName, fileName));
         }
operator+() [2/2]
static FileInfo Juniper.IO.ContentReference.operator+ (ContentReference fileRef, DirectoryInfo directory) inline static inherited
Definition at line 47 of file ContentReference.cs.
         {
             return directory + fileRef;
         }
operator==()
static bool Juniper.IO.ContentReference.operator== (ContentReference left, ContentReference right) inline static inherited
Definition at line 10 of file ContentReference.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
RemoveQuery() [1/2]
void Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.RemoveQuery (string key) inline protected inherited
Definition at line 139 of file AbstractRequest.cs.
         {
             queryParams.Remove(key);
         }
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.RemoveQuery< U >(), and Juniper.HTTP.REST.AbstractRequest< MediaType >.SetQuery().
RemoveQuery() [2/2]
bool Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.RemoveQuery (string key, string value) inline protected inherited
Definition at line 144 of file AbstractRequest.cs.
         {
             var removed = false;
             if (queryParams.ContainsKey(key))
             {
                 var list = queryParams[key];
                 removed = list.Remove(value);
                 if (list.Count == 0)
                 {
                     queryParams.Remove(key);
                 }
             }
             return removed;
         }
RemoveQuery< U >()
bool Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.RemoveQuery< U > (string key, U value) inline protected inherited
Definition at line 160 of file AbstractRequest.cs.
         {
             return RemoveQuery(key, value.ToString());
         }
SetQuery()
void Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.SetQuery (string key, string value) inline protected inherited
Definition at line 119 of file AbstractRequest.cs.
         {
             SetQuery(key, value, false);
         }
SetQuery< U >()
void Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.SetQuery< U > (string key, U value) inline protected inherited
Definition at line 124 of file AbstractRequest.cs.
         {
             SetQuery(key, value.ToString());
         }
ToString()
override string Juniper.IO.ContentReference.ToString () inline inherited
Definition at line 91 of file ContentReference.cs.
         {
             return string.Format(CultureInfo.InvariantCulture, "{0} ({1})", CacheID, ContentType);
         }
References Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
Referenced by Juniper.IO.FileCacheLayer.Create(), Juniper.IO.MemoryCacheLayer.GetStreamAsync(), and Juniper.IO.FileCacheLayer.GetStreamAsync().
WriteBody()
virtual void Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.WriteBody (Stream stream) inline protected virtual inherited
Definition at line 172 of file AbstractRequest.cs.
 { }
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.GetStreamAsync().
Member Data Documentation
AuthenticatedURI
virtual Uri Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.AuthenticatedURI => BaseURI protected inherited
Definition at line 66 of file AbstractRequest.cs.
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.GetStreamAsync().
CacheID
sealed override string Juniper.IO.AbstractStreamSource.CacheID inherited
Initial value:
=>
            InternalCacheID
Definition at line 16 of file AbstractStreamSource.cs.
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.Equals(), and Juniper.HTTP.REST.AbstractRequest< MediaType >.GetHashCode().
ContentType
override MediaType Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.ContentType => MediaType inherited
Definition at line 45 of file AbstractRequest.cs.
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.GetHashCode().
DoNotCache
sealed override bool Juniper.IO.AbstractStreamSource.DoNotCache inherited
Initial value:
=>
            CacheID is null
Definition at line 19 of file AbstractStreamSource.cs.
Property Documentation
BaseURI
virtual Uri Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.BaseURI get protected inherited
Definition at line 55 of file AbstractRequest.cs.
         {
             get
             {
                 var uriBuilder = new UriBuilder(serviceURI)
                 {
                     Query = queryParams.ToString("=", "&")
                 };
                 return uriBuilder.Uri;
             }
         }
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.GetHashCode().
FileName
string Juniper.IO.ContentReference.FileName get inherited
Definition at line 97 of file ContentReference.cs.
         {
             get
             {
                 var nameStub = CacheID;
                 var fileStub = new FileInfo(nameStub);
                 nameStub = fileStub.Name;
                 if (ContentType.PrimaryExtension is object)
                 {
                     return $"{nameStub}.{ContentType.PrimaryExtension}";
                 }
                 else
                 {
                     return nameStub;
                 }
             }
         }
Referenced by Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync().
InternalCacheID
abstract string Juniper.IO.AbstractStreamSource.InternalCacheID get protected inherited
Definition at line 22 of file AbstractStreamSource.cs.
 { get; }
MediaType
MediaTypeT Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.MediaType get inherited
Definition at line 41 of file AbstractRequest.cs.
         {
             get;
         }
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.GetStreamAsync().
StandardRequestCacheID
string? Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.StandardRequestCacheID get protected inherited
Definition at line 69 of file AbstractRequest.cs.
         {
             get
             {
                 var invalid = Path.GetInvalidFileNameChars();
                 var parts = (BaseURI.Host + BaseURI.PathAndQuery)
                     .SplitX('/');
                 var sb = new StringBuilder();
                 for (var i = 0; i < parts.Length; ++i)
                 {
                     var part = parts[i];
                     for (var j = 0; j < part.Length; ++j)
                     {
                         sb.Append(invalid.Contains(part[j])
                             ? '_'
                             : part[j]);
                     }
                     if (i < parts.Length - 1)
                     {
                         sb.Append(Path.DirectorySeparatorChar);
                     }
                 }
                 return sb.ToString();
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Azure/AbstractAzureRequest.cs