Juniper: Hjg.Pngcs.ProgressiveOutputStream Class Reference
Hjg.Pngcs.ProgressiveOutputStream Class Reference abstract
stream that outputs to memory and allows to flush fragments every 'size' bytes to some other destination
Public Member Functions
ProgressiveOutputStream (int size_0)
override void Close ()
override void Flush ()
override void Write (byte[] b, int off, int len)
void Write (byte[] b)
long GetCountFlushed ()
Protected Member Functions
abstract void FlushBuffer (byte[] b, int n)
Private Member Functions
void CheckFlushBuffer (bool forced)
if it's time to flush data (or if forced==true) calls abstract method flushBuffer() and cleans those bytes from own buffer
Private Attributes
readonly int size
long countFlushed = 0
Detailed Description
stream that outputs to memory and allows to flush fragments every 'size' bytes to some other destination
Definition at line 15 of file ProgressiveOutputStream.cs.
Constructor & Destructor Documentation
ProgressiveOutputStream()
Hjg.Pngcs.ProgressiveOutputStream.ProgressiveOutputStream (int size_0) inline
Definition at line 19 of file ProgressiveOutputStream.cs.
{
             this.size = size_0;
             if (size < 8) throw new PngjException("bad size for ProgressiveOutputStream: " + size);
         }
References Hjg.Pngcs.ProgressiveOutputStream.size.
Member Function Documentation
CheckFlushBuffer()
void Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer (bool forced) inline private
if it's time to flush data (or if forced==true) calls abstract method flushBuffer() and cleans those bytes from own buffer
Definition at line 50 of file ProgressiveOutputStream.cs.
{
             int count = (int)Position;
             byte[] buf = GetBuffer();
             while (forced || count >= size) {
                 int nb = size;
                 if (nb > count)
                     nb = count;
                 if (nb == 0)
                     return;
                 FlushBuffer(buf, nb);
                 countFlushed += nb;
                 int bytesleft = count - nb;
                 count = bytesleft;
                 Position = count;
                 if (bytesleft > 0)
                     System.Array.Copy((Array)(buf), nb, (Array)(buf), 0, bytesleft);
             }
         }
References Hjg.Pngcs.ProgressiveOutputStream.countFlushed, Hjg.Pngcs.ProgressiveOutputStream.FlushBuffer(), and Hjg.Pngcs.ProgressiveOutputStream.size.
Referenced by Hjg.Pngcs.ProgressiveOutputStream.Flush(), and Hjg.Pngcs.ProgressiveOutputStream.Write().
Close()
override void Hjg.Pngcs.ProgressiveOutputStream.Close () inline
Definition at line 24 of file ProgressiveOutputStream.cs.
{
             Flush();
             base.Close();
         }
References Hjg.Pngcs.ProgressiveOutputStream.Flush().
Flush()
override void Hjg.Pngcs.ProgressiveOutputStream.Flush () inline
Definition at line 29 of file ProgressiveOutputStream.cs.
{
             base.Flush();
             CheckFlushBuffer(true);
         }
References Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer().
Referenced by Hjg.Pngcs.ProgressiveOutputStream.Close(), and Hjg.Pngcs.PngIDatChunkOutputStream.Close().
FlushBuffer()
abstract void Hjg.Pngcs.ProgressiveOutputStream.FlushBuffer (byte [] b, int n) protected pure virtual
Implemented in Hjg.Pngcs.PngIDatChunkOutputStream.
Referenced by Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer().
GetCountFlushed()
long Hjg.Pngcs.ProgressiveOutputStream.GetCountFlushed () inline
Definition at line 71 of file ProgressiveOutputStream.cs.
{
             return countFlushed;
         }
References Hjg.Pngcs.ProgressiveOutputStream.countFlushed.
Referenced by Hjg.Pngcs.PngWriter.ComputeCompressionRatio().
Write() [1/2]
override void Hjg.Pngcs.ProgressiveOutputStream.Write (byte [] b, int off, int len) inline
Definition at line 34 of file ProgressiveOutputStream.cs.
{
             base.Write(b, off, len);
             CheckFlushBuffer(false);
         }
References Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer().
Referenced by Hjg.Pngcs.ProgressiveOutputStream.Write().
Write() [2/2]
void Hjg.Pngcs.ProgressiveOutputStream.Write (byte [] b) inline
Definition at line 39 of file ProgressiveOutputStream.cs.
{
             Write(b, 0, b.Length);
             CheckFlushBuffer(false);
         }
References Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer(), and Hjg.Pngcs.ProgressiveOutputStream.Write().
Member Data Documentation
countFlushed
long Hjg.Pngcs.ProgressiveOutputStream.countFlushed = 0 private
Definition at line 17 of file ProgressiveOutputStream.cs.
Referenced by Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer(), and Hjg.Pngcs.ProgressiveOutputStream.GetCountFlushed().
size
readonly int Hjg.Pngcs.ProgressiveOutputStream.size private
Definition at line 16 of file ProgressiveOutputStream.cs.
Referenced by Hjg.Pngcs.ProgressiveOutputStream.CheckFlushBuffer(), and Hjg.Pngcs.ProgressiveOutputStream.ProgressiveOutputStream().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/ThirdParty/Required/Hjg.Pngcs/ProgressiveOutputStream.cs