Juniper: Juniper.Unity.Audio.AbstractInteractionAudio Class Reference
Juniper.Unity.Audio.AbstractInteractionAudio Class Reference
The audio portion of the interaction system.
Public Member Functions
AudioSource Spatialize (AudioSource audioSource, bool loop, AudioMixerGroup group)
AudioSource Spatialize (AudioSource audioSource, bool loop)
AudioSource Spatialize (AudioSource audioSource, AudioMixerGroup group)
AudioSource Spatialize (AudioSource audioSource)
virtual void Install (bool reset)
Install, with or without a full reset.
void Reinstall ()
Reinstall the object with a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
virtual void Awake ()
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
void Start ()
void OnValidate ()
Static Public Member Functions
static HapticExpression GetHapticExpressions (Interaction action)
Converts an Interaction into a haptic expression to be able to play.
static float Play (Interaction action, AbstractHapticDevice haptics)
Play the specified action at the camera position using the specified haptics, with no callback.
static float Play (Interaction action, Transform pose, AbstractHapticDevice haptics)
Play the specified action using the specified pose and haptic subsystem, with no callback.
static float Play (Interaction action, AbstractHapticDevice haptics, Action onComplete)
Play the specified action at the camera position using the specified haptics, with a callback on completion.
static float Play (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete)
Play the specified action using the specified pose and haptic subsystem, with a callback on completion.
Public Attributes
AudioMixerGroup defaultMixerGroup
The audio mixer to use with ResonanceAudio
GameObject volumeSlider
AudioClipCollection soundOnClosed
The sound to play when an Widgets.Openable object has been closed.
AudioClipCollection soundOnDisabled
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
AudioClipCollection soundOnDragged
The sound to play when a Widgets.Draggable has been moved more than 10cm.
AudioClipCollection soundOnEntered
The sound to play when a cursor first hovers over any Widgets.Touchable.
AudioClipCollection soundOnError
The sound to play when an operation needs to indicate an error.
AudioClipCollection soundOnExited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
AudioClipCollection soundOnOpened
The sound to play when an Widgets.Openable object has been opened.
AudioClipCollection soundOnReleased
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
AudioClipCollection soundOnScrolled
The sound to play when a scrollable section is moved a certain distance.
AudioClipCollection soundOnSelected
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
AudioClipCollection soundOnSuccess
The sound to play when a long-running operating needs to indicate success.
AudioClip soundOnStartUp
The sound to play when the application first starts up.
AudioClip soundOnShutDown
The sound to play right before the application shuts down.
Protected Member Functions
virtual AudioSource InternalSpatialize (AudioSource audioSource, bool loop, AudioMixerGroup group)
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Protected Attributes
AudioListener listener
Properties
virtual string DefaultAudioMixer [get]
float???? Volume [get, set]
Private Member Functions
void Volume_ValueChange (object sender, float value)
IAudioClipCollection GetClipCollection (Interaction action)
Converts an Interaction into a set of audio clips to be able to play.
IEnumerator Wait (float seconds, Action onComplete)
Waits a set number of seconds and then executes a callback function.
float Play_Internal (Interaction action, AbstractHapticDevice haptics)
float Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics)
float Play_Internal (Interaction action, AbstractHapticDevice haptics, Action onComplete)
float Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete)
void PlayHaptics (Interaction action, AbstractHapticDevice haptics)
Executes the haptic feedback portion of the interaction.
float PlayClip (Interaction action, Transform pose)
Plays the audio portion of the interaction.
AudioSource GetAudioSource (AudioClip clip)
Find or create a free Audio Source out of the pool.
AudioSource CreateNewAudioSource ()
Private Attributes
const string MASTER_VOLUME_KEY = "MasterVolume"
IValuedControl< float > volume
IAudioClipCollection startUp
The sound to play on application startup.
IAudioClipCollection shutDown
The sound to play on application shutdown.
List< AudioSource > audioSources
A pool of audio sources that can be moved around to play sounds wherever they are needed. The Play(Interaction, Transform, AbstractHapticDevice, Action) method will find whichever one is currently not playing and use it, or create a new one if all audio sources are currently playing. It starts out with 5 audio sources by default so that applications don't have to grow the collection right away.
Transform camT
The main camera, which also has the user's ears.
const float E = (float)Math.E
Static Private Attributes
static AbstractInteractionAudio instance
Detailed Description
The audio portion of the interaction system.
Definition at line 43 of file InteractionAudio.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Audio.AbstractInteractionAudio.Awake () inline virtual
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
Definition at line 275 of file InteractionAudio.cs.
         {
             if (instance != null)
             {
                 Debug.LogWarning("Juniper: There can be only one! (R2D2)");
                 this.Destroy();
             }
             else
             {
                 Install(false);
                 instance = this;
                 camT = DisplayManager.MainCamera.transform;
 #if UNITY_MODULES_AUDIO
                 startUp = new SingleAudioClipCollection(soundOnStartUp, false);
                 shutDown = new SingleAudioClipCollection(soundOnShutDown, false);
                 audioSources = new List<AudioSource>(10);
                 if (volumeSlider != null)
                 {
                     volume = volumeSlider.GetSlider();
                     volume.ValueChange += Volume_ValueChange;
                 }
 #endif
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.audioSources, Juniper.Unity.Audio.AbstractInteractionAudio.camT, Juniper.Unity.Audio.AbstractInteractionAudio.Install(), Juniper.Unity.Audio.AbstractInteractionAudio.instance, Juniper.Unity.Display.AbstractDisplayManager.MainCamera, Juniper.Unity.Audio.AbstractInteractionAudio.shutDown, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnShutDown, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnStartUp, Juniper.Unity.Audio.AbstractInteractionAudio.startUp, Juniper.Unity.Widgets.IValuedControl< T >.ValueChange, Juniper.Unity.Audio.AbstractInteractionAudio.volume, Juniper.Unity.Audio.AbstractInteractionAudio.Volume_ValueChange(), and Juniper.Unity.Audio.AbstractInteractionAudio.volumeSlider.
CreateNewAudioSource()
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource () inline private
Definition at line 543 of file InteractionAudio.cs.
         {
             var audioSource = Spatialize(
                 new GameObject().AddComponent<AudioSource>(),
                 false,
                 defaultMixerGroup);
             audioSources.Add(audioSource);
             audioSource.name = "AudioSource" + audioSources.Count.ToString("00");
             return audioSource;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.audioSources, Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup, and Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize().
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetAudioSource(), and Juniper.Unity.Audio.AbstractInteractionAudio.Start().
GetAudioSource()
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.GetAudioSource (AudioClip clip) inline private
Find or create a free Audio Source out of the pool.
Returns
The audio source.
Definition at line 532 of file InteractionAudio.cs.
         {
             var source = audioSources
                 .Where(a => !a.isPlaying)
                 .OrderByDescending(a => a.clip == clip)
                 .FirstOrDefault()
                 ?? CreateNewAudioSource();
             source.clip = clip;
             return source;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.audioSources, and Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource().
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.PlayClip().
GetClipCollection()
IAudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection (Interaction action) inline private
Converts an Interaction into a set of audio clips to be able to play.
Returns
The audio clip.
Parameters
action Action.
Definition at line 344 of file InteractionAudio.cs.
         {
             switch (action)
             {
                 case Interaction.Closed:
                 return soundOnClosed;
                 case Interaction.Disabled:
                 return soundOnDisabled;
                 case Interaction.DraggingStarted:
                 case Interaction.Dragged:
                 case Interaction.DraggingEnded:
                 return soundOnDragged;
                 case Interaction.Scrolled:
                 return soundOnScrolled;
                 case Interaction.Entered:
                 return soundOnEntered;
                 case Interaction.Error:
                 return soundOnError;
                 case Interaction.Exited:
                 return soundOnExited;
                 case Interaction.Opened:
                 return soundOnOpened;
                 case Interaction.Released:
                 return soundOnReleased;
                 case Interaction.Clicked:
                 return soundOnSelected;
                 case Interaction.Success:
                 return soundOnSuccess;
 #if UNITY_MODULES_AUDIO
                 case Interaction.StartUp:
                 return startUp;
                 case Interaction.ShutDown:
                 return shutDown;
 #endif
                 default:
                 return null;
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.shutDown, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnClosed, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnDisabled, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnDragged, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnEntered, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnError, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnExited, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnOpened, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnReleased, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnScrolled, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnSelected, Juniper.Unity.Audio.AbstractInteractionAudio.soundOnSuccess, and Juniper.Unity.Audio.AbstractInteractionAudio.startUp.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.PlayClip().
GetHapticExpressions()
static HapticExpression Juniper.Unity.Audio.AbstractInteractionAudio.GetHapticExpressions (Interaction action) inline static
Converts an Interaction into a haptic expression to be able to play.
Returns
The haptic expressions.
Parameters
action Action.
Definition at line 50 of file InteractionAudio.cs.
         {
             switch (action)
             {
                 case Interaction.Closed:
                 return HapticExpression.Heavy;
                 case Interaction.Disabled:
                 return HapticExpression.Warning;
                 case Interaction.DraggingStarted:
                 case Interaction.Dragged:
                 case Interaction.DraggingEnded:
                 return HapticExpression.SelectionChange;
                 case Interaction.Error:
                 return HapticExpression.Error;
                 case Interaction.Opened:
                 return HapticExpression.Medium;
                 case Interaction.Clicked:
                 return HapticExpression.Light;
                 case Interaction.Success:
                 return HapticExpression.Success;
                 default:
                 return HapticExpression.None;
             }
         }
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.PlayHaptics().
Install()
virtual void Juniper.Unity.Audio.AbstractInteractionAudio.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Audio.ResonanceInteractionAudio.
Definition at line 242 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             listener = DisplayManager.MainCamera.Ensure<AudioListener>();
 #endif
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.listener, and Juniper.Unity.Display.AbstractDisplayManager.MainCamera.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.Audio.AbstractInteractionAudio.Reinstall().
InternalSpatialize()
virtual AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize (AudioSource audioSource, bool loop, AudioMixerGroup group) inline protected virtual
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Parameters
audioSource
loop
group
Returns
Reimplemented in Juniper.Unity.Audio.ResonanceInteractionAudio, and Juniper.Unity.Audio.WindowsMRInteractionAudio.
Definition at line 599 of file InteractionAudio.cs.
         {
             audioSource.loop = loop;
             audioSource.outputAudioMixerGroup = group ?? defaultMixerGroup;
             audioSource.spatialBlend = 1;
             audioSource.spatialize = true;
             audioSource.spatializePostEffects = true;
             return audioSource;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize().
OnValidate()
void Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate () inline
Definition at line 510 of file InteractionAudio.cs.
         {
             if (defaultMixerGroup == null)
             {
                 defaultMixerGroup =
                     (from g in Resources.FindObjectsOfTypeAll<AudioMixerGroup>()
                      where g.audioMixer.name == DefaultAudioMixer
                      orderby g.name == "Master" descending
                      select g)
                         .FirstOrDefault();
             }
             if (defaultMixerGroup != null)
             {
                 Volume = PlayerPrefs.GetFloat(MASTER_VOLUME_KEY, 1);
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.DefaultAudioMixer, Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup, Juniper.Unity.Audio.AbstractInteractionAudio.MASTER_VOLUME_KEY, and Juniper.Unity.Audio.AbstractInteractionAudio.Volume.
Play() [1/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, AbstractHapticDevice haptics) inline static
Play the specified action at the camera position using the specified haptics, with no callback.
Returns
The play.
Parameters
action Action.
haptics Haptics.
Definition at line 88 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, haptics) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Referenced by Juniper.Unity.Widgets.AttentionDirector.FoundCoroutine(), Juniper.Unity.Widgets.AttentionDirector.LostCoroutine(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
Play() [2/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, Transform pose, AbstractHapticDevice haptics) inline static
Play the specified action using the specified pose and haptic subsystem, with no callback.
Returns
The play.
Parameters
action Action.
pose Pose.
haptics Haptics.
Definition at line 100 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, pose, haptics) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play() [3/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, AbstractHapticDevice haptics, Action onComplete) inline static
Play the specified action at the camera position using the specified haptics, with a callback on completion.
Returns
The play.
Parameters
action Action.
haptics Haptics.
onComplete
Definition at line 113 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, haptics, onComplete) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play() [4/4]
static float Juniper.Unity.Audio.AbstractInteractionAudio.Play (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete) inline static
Play the specified action using the specified pose and haptic subsystem, with a callback on completion.
Returns
The play.
Parameters
action Action.
pose Pose.
haptics Haptics.
onComplete
Definition at line 127 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, pose, haptics, onComplete) ?? 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.instance, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play_Internal() [1/4]
float Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal (Interaction action, AbstractHapticDevice haptics) inline private
Definition at line 408 of file InteractionAudio.cs.
         {
             return Play_Internal(action, camT, haptics, null);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.camT.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Play(), and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play_Internal() [2/4]
float Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics) inline private
Definition at line 413 of file InteractionAudio.cs.
         {
             return Play_Internal(action, pose, haptics, null);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play_Internal() [3/4]
float Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal (Interaction action, AbstractHapticDevice haptics, Action onComplete) inline private
Definition at line 418 of file InteractionAudio.cs.
         {
             return Play_Internal(action, camT, haptics, onComplete);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.camT, and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Play_Internal() [4/4]
float Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete) inline private
Definition at line 423 of file InteractionAudio.cs.
         {
             if (action == Interaction.None)
             {
                 return 0;
             }
             else
             {
                 PlayHaptics(action, haptics);
                 var len = PlayClip(action, pose);
                 if (onComplete != null)
                 {
                     StartCoroutine(Wait(len, onComplete));
                 }
                 return len;
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.PlayClip(), Juniper.Unity.Audio.AbstractInteractionAudio.PlayHaptics(), and Juniper.Unity.Audio.AbstractInteractionAudio.Wait().
PlayClip()
float Juniper.Unity.Audio.AbstractInteractionAudio.PlayClip (Interaction action, Transform pose) inline private
Plays the audio portion of the interaction.
Returns
The clip.
Parameters
action Action.
pose Pose.
Definition at line 461 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             var clips = GetClipCollection(action);
             var clip = clips?.Random();
             if (clip != null)
             {
                 var audioSource = GetAudioSource(clip);
                 if (clips.RandomizeClipPitch)
                 {
                     audioSource.pitch = UnityEngine.Random.Range(0.9f, 1.1f);
                 }
                 audioSource.transform.position = pose.position;
                 audioSource.transform.rotation = pose.rotation;
                 audioSource.Play();
                 return audioSource.clip.length;
             }
 #endif
             return 0;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.GetAudioSource(), and Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
PlayHaptics()
void Juniper.Unity.Audio.AbstractInteractionAudio.PlayHaptics (Interaction action, AbstractHapticDevice haptics) inline private
Executes the haptic feedback portion of the interaction.
Parameters
action Action.
haptics Haptics.
Definition at line 446 of file InteractionAudio.cs.
         {
             var expr = GetHapticExpressions(action);
             if (expr != HapticExpression.None)
             {
                 haptics?.Play(expr);
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.GetHapticExpressions(), and Juniper.Unity.Haptics.AbstractHapticDevice.Play().
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Reinstall()
void Juniper.Unity.Audio.AbstractInteractionAudio.Reinstall () inline
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 250 of file InteractionAudio.cs.
         {
             Install(true);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.Install().
Spatialize() [1/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource, bool loop, AudioMixerGroup group) inline
Definition at line 134 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, loop, group);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Referenced by Juniper.Unity.Video.Video360.CreateAudioTracks(), Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource(), and Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine().
Spatialize() [2/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource, bool loop) inline
Definition at line 139 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, loop, defaultMixerGroup);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup, and Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Spatialize() [3/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource, AudioMixerGroup group) inline
Definition at line 144 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, false, group);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Spatialize() [4/4]
AudioSource Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize (AudioSource audioSource) inline
Definition at line 149 of file InteractionAudio.cs.
         {
             return InternalSpatialize(audioSource, false, defaultMixerGroup);
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup, and Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize().
Start()
void Juniper.Unity.Audio.AbstractInteractionAudio.Start () inline
Definition at line 487 of file InteractionAudio.cs.
         {
             for (var i = 0; i < 5; ++i)
             {
                 CreateNewAudioSource();
             }
             Volume = PlayerPrefs.GetFloat(MASTER_VOLUME_KEY, 1);
             if (volume != null)
             {
                 volume.value = Volume;
             }
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource(), Juniper.Unity.Audio.AbstractInteractionAudio.MASTER_VOLUME_KEY, Juniper.Unity.Widgets.IValuedControl< T >.value, Juniper.Unity.Audio.AbstractInteractionAudio.volume, and Juniper.Unity.Audio.AbstractInteractionAudio.Volume.
Uninstall()
virtual void Juniper.Unity.Audio.AbstractInteractionAudio.Uninstall () inline virtual
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Audio.ResonanceInteractionAudio.
Definition at line 264 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             DisplayManager.MainCamera.Ensure<AudioListener>();
 #endif
         }
References Juniper.Unity.Display.AbstractDisplayManager.MainCamera.
Volume_ValueChange()
void Juniper.Unity.Audio.AbstractInteractionAudio.Volume_ValueChange (object sender, float value) inline private
Definition at line 304 of file InteractionAudio.cs.
         {
             Volume = value;
         }
References Juniper.Unity.Audio.AbstractInteractionAudio.Volume.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake().
Wait()
IEnumerator Juniper.Unity.Audio.AbstractInteractionAudio.Wait (float seconds, Action onComplete) inline private
Waits a set number of seconds and then executes a callback function.
Returns
The wait.
Parameters
seconds Seconds.
onComplete On complete.
Definition at line 402 of file InteractionAudio.cs.
         {
             yield return new WaitForSeconds(seconds);
             onComplete();
         }
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
Member Data Documentation
audioSources
List<AudioSource> Juniper.Unity.Audio.AbstractInteractionAudio.audioSources private
A pool of audio sources that can be moved around to play sounds wherever they are needed. The Play(Interaction, Transform, AbstractHapticDevice, Action) method will find whichever one is currently not playing and use it, or create a new one if all audio sources are currently playing. It starts out with 5 audio sources by default so that applications don't have to grow the collection right away.
Definition at line 330 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource(), and Juniper.Unity.Audio.AbstractInteractionAudio.GetAudioSource().
camT
Transform Juniper.Unity.Audio.AbstractInteractionAudio.camT private
The main camera, which also has the user's ears.
Definition at line 337 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.Audio.AbstractInteractionAudio.Play_Internal().
defaultMixerGroup
AudioMixerGroup Juniper.Unity.Audio.AbstractInteractionAudio.defaultMixerGroup
The audio mixer to use with ResonanceAudio
Definition at line 160 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.CreateNewAudioSource(), Juniper.Unity.Audio.AbstractInteractionAudio.InternalSpatialize(), Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate(), and Juniper.Unity.Audio.AbstractInteractionAudio.Spatialize().
E
const float Juniper.Unity.Audio.AbstractInteractionAudio.E = (float)Math.E private
Definition at line 485 of file InteractionAudio.cs.
instance
AbstractInteractionAudio Juniper.Unity.Audio.AbstractInteractionAudio.instance static private
Definition at line 309 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.Audio.AbstractInteractionAudio.Play().
listener
AudioListener Juniper.Unity.Audio.AbstractInteractionAudio.listener protected
Definition at line 239 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.ResonanceInteractionAudio.Install(), and Juniper.Unity.Audio.AbstractInteractionAudio.Install().
MASTER_VOLUME_KEY
const string Juniper.Unity.Audio.AbstractInteractionAudio.MASTER_VOLUME_KEY = "MasterVolume" private
Definition at line 235 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate(), and Juniper.Unity.Audio.AbstractInteractionAudio.Start().
shutDown
IAudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.shutDown private
The sound to play on application shutdown.
Definition at line 321 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnClosed
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnClosed
The sound to play when an Widgets.Openable object has been closed.
Definition at line 168 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnDisabled
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnDisabled
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
Definition at line 174 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnDragged
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnDragged
The sound to play when a Widgets.Draggable has been moved more than 10cm.
Definition at line 179 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnEntered
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnEntered
The sound to play when a cursor first hovers over any Widgets.Touchable.
Definition at line 184 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnError
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnError
The sound to play when an operation needs to indicate an error.
Definition at line 189 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnExited
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnExited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
Definition at line 195 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnOpened
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnOpened
The sound to play when an Widgets.Openable object has been opened.
Definition at line 200 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnReleased
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnReleased
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
Definition at line 205 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnScrolled
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnScrolled
The sound to play when a scrollable section is moved a certain distance.
Definition at line 210 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnSelected
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnSelected
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
Definition at line 215 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
soundOnShutDown
AudioClip Juniper.Unity.Audio.AbstractInteractionAudio.soundOnShutDown
The sound to play right before the application shuts down.
Definition at line 233 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake().
soundOnStartUp
AudioClip Juniper.Unity.Audio.AbstractInteractionAudio.soundOnStartUp
The sound to play when the application first starts up.
Definition at line 228 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake().
soundOnSuccess
AudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.soundOnSuccess
The sound to play when a long-running operating needs to indicate success.
Definition at line 220 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
startUp
IAudioClipCollection Juniper.Unity.Audio.AbstractInteractionAudio.startUp private
The sound to play on application startup.
Definition at line 316 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.Audio.AbstractInteractionAudio.GetClipCollection().
volume
IValuedControl<float> Juniper.Unity.Audio.AbstractInteractionAudio.volume private
Definition at line 237 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.Audio.AbstractInteractionAudio.Start().
volumeSlider
GameObject Juniper.Unity.Audio.AbstractInteractionAudio.volumeSlider
Definition at line 162 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.Awake(), and Juniper.Unity.MasterSceneController.SetupSystemInterface().
Property Documentation
DefaultAudioMixer
virtual string Juniper.Unity.Audio.AbstractInteractionAudio.DefaultAudioMixer get protected
Definition at line 503 of file InteractionAudio.cs.
         {
             get
             {
                 return "defaultAudioMixer";
             }
         }
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate().
Volume
float???? Juniper.Unity.Audio.AbstractInteractionAudio.Volume get set
Definition at line 557 of file InteractionAudio.cs.
         {
             set
             {
 #if UNITY_MODULES_AUDIO
                 PlayerPrefs.SetFloat(MASTER_VOLUME_KEY, value);
                 PlayerPrefs.Save();
                 var log = Mathf.Log(value) * 11.5f;
                 if (float.IsInfinity(log))
                 {
                     log = -1000;
                 }
                 defaultMixerGroup
                     ?.audioMixer
                     ?.SetFloat("Volume", log);
 #endif
             }
             get
             {
                 float value = 0;
 #if UNITY_MODULES_AUDIO
                 if (defaultMixerGroup?.audioMixer?.GetFloat("Volume", out value) == true)
                 {
                     value = Mathf.Pow(E, value / 11.5f);
                 }
 #endif
                 return value;
             }
         }
Referenced by Juniper.Unity.Audio.AbstractInteractionAudio.OnValidate(), Juniper.Unity.Audio.AbstractInteractionAudio.Start(), and Juniper.Unity.Audio.AbstractInteractionAudio.Volume_ValueChange().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Audio/InteractionAudio.cs