Juniper: System.Collections.Generic.NaturalSortComparer Class Reference
System.Collections.Generic.NaturalSortComparer Class Reference
Sorts a collection of strings, by first splitting out any numbers and treating them as numbers, rather than lexicographic strings.
Public Member Functions
NaturalSortComparer (bool inAscendingOrder=true)
Creates a new NaturalSortComparer.
int Compare (string x, string y)
Compare two strings to see where they should be in relation to each other within a collection.
Private Member Functions
int IComparer< string >. Compare (string x, string y)
Finish implementing the IComparer<T> interface.
Static Private Member Functions
static int PartCompare (string left, string right)
Compares two subparts of a string to see if they are numbers.
Private Attributes
readonly bool isAscending
Whether or not to sort in ascending or descending order.
Dictionary< string, string[]> table = new Dictionary<string, string[]>()
Used to memoize strings to their split representation.
Detailed Description
Sorts a collection of strings, by first splitting out any numbers and treating them as numbers, rather than lexicographic strings.
var files = new List\<string\> { "file003", "file1", "file04", "file02" };
files.Sort(new NatrualSortComparer());
files.Matches(new []{ "file1", "file02", "file003", "file04" }); // --> true
Definition at line 14 of file NaturalSortComparer.cs.
Constructor & Destructor Documentation
NaturalSortComparer()
System.Collections.Generic.NaturalSortComparer.NaturalSortComparer (bool inAscendingOrder = true) inline
Creates a new NaturalSortComparer.
Parameters
inAscendingOrder Set to false to reverse the order of the sort. Defaults to true.
Definition at line 22 of file NaturalSortComparer.cs.
         {
             isAscending = inAscendingOrder;
         }
References System.Collections.Generic.NaturalSortComparer.isAscending.
Member Function Documentation
Compare() [1/2]
int System.Collections.Generic.NaturalSortComparer.Compare (string x, string y) inline
Compare two strings to see where they should be in relation to each other within a collection.
Parameters
x The left string.
y The right string.
Returns
An integer representing the direction the in which to move the items.
Definition at line 33 of file NaturalSortComparer.cs.
         {
             if (x == y)
             {
                 return 0;
             }
             else
             {
                 if (!table.TryGetValue(x, out var x1))
                 {
                     x1 = Regex.Split(x.Replace(" ", ""), "([0-9]+)");
                     table.Add(x, x1);
                 }
                 if (!table.TryGetValue(y, out var y1))
                 {
                     y1 = Regex.Split(y.Replace(" ", ""), "([0-9]+)");
                     table.Add(y, y1);
                 }
                 int returnVal;
                 for (var i = 0; i < x1.Length && i < y1.Length; i++)
                 {
                     if (x1[i] != y1[i])
                     {
                         returnVal = PartCompare(x1[i], y1[i]);
                         return isAscending ? returnVal : -returnVal;
                     }
                 }
                 if (y1.Length > x1.Length)
                 {
                     returnVal = 1;
                 }
                 else if (x1.Length > y1.Length)
                 {
                     returnVal = -1;
                 }
                 else
                 {
                     returnVal = 0;
                 }
                 return isAscending ? returnVal : -returnVal;
             }
         }
References System.Collections.Generic.NaturalSortComparer.isAscending, System.Collections.Generic.NaturalSortComparer.PartCompare(), and System.Collections.Generic.NaturalSortComparer.table.
Referenced by Juniper.Unity.Collections.TextureSortComparer.Compare(), and System.Collections.Generic.NaturalSortComparer.Compare().
Compare() [2/2]
int IComparer<string>. System.Collections.Generic.NaturalSortComparer.Compare (string x, string y) inline private
Finish implementing the IComparer<T> interface.
Returns
The collections. generic. IC omparer< system. string>. compare.
Parameters
x The x coordinate.
y The y coordinate.
Definition at line 85 of file NaturalSortComparer.cs.
         {
             return Compare(x, y);
         }
References System.Collections.Generic.NaturalSortComparer.Compare().
PartCompare()
static int System.Collections.Generic.NaturalSortComparer.PartCompare (string left, string right) inline static private
Compares two subparts of a string to see if they are numbers.
Parameters
left The subpart of the first string.
right The subpart of the second string.
Returns
A comparison shift amount, usable for sorting algorithms.
Definition at line 106 of file NaturalSortComparer.cs.
         {
             if (!int.TryParse(left, out var x)
                 || !int.TryParse(right, out var y))
             {
                 return string.Compare(left, right, StringComparison.Ordinal);
             }
             else
             {
                 return x.CompareTo(y);
             }
         }
Referenced by System.Collections.Generic.NaturalSortComparer.Compare().
Member Data Documentation
isAscending
readonly bool System.Collections.Generic.NaturalSortComparer.isAscending private
Whether or not to sort in ascending or descending order.
Definition at line 93 of file NaturalSortComparer.cs.
Referenced by System.Collections.Generic.NaturalSortComparer.Compare(), and System.Collections.Generic.NaturalSortComparer.NaturalSortComparer().
table
Dictionary<string, string[]> System.Collections.Generic.NaturalSortComparer.table = new Dictionary<string, string[]>() private
Used to memoize strings to their split representation.
Definition at line 98 of file NaturalSortComparer.cs.
Referenced by System.Collections.Generic.NaturalSortComparer.Compare().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper.Common/src/Extensions/NETFX/Collections/Generic/NaturalSortComparer.cs