Juniper: Juniper.Angle Struct Reference
Juniper.Angle Struct Reference
Represents an angle in degrees that doesn't wrap around to 0 when iterating past 360 degrees. It does this by making the update the smallest delta of value plus whole rotations. e.g. if the current value is 359, setting the value to 1 will actually return as 361, as Abs(361 - 351) < Abs(1 - 351).
Public Member Functions
Angle (float v, float r=0)
Create an angle value at set starting point
override bool Equals (object obj)
Compares two angles to see if they represent the same position on a circle.
override int GetHashCode ()
Serves as a hash function for a T:UnityEngine.Angle object.
Static Public Member Functions
static implicit operator float (Angle a)
Automatically unwrap the value of the Angle, to be able to use with other API fields that expect angle values in degrees.
static operator Angle (float f)
Wrap an angle value in the Angle struct. Useful for using System.Linq.Enumerable.Cast{T} on a collection of Angles.
static Angle operator ^ (Angle a, float v)
Create a new Angle struct that represents the smallest turn from the old Angle struct in either the clockwise or counter-clockwise direction that matches the new angle.
static Angle operator % (Angle a, float v)
Whole-number divide the angle and save the remainder, and minimize rotation to the new value
static Angle operator+ (Angle a, float v)
Add to the angle, and minimize rotation to the new value
static Angle operator - (Angle a, float v)
Subtract from the angle, and minimize rotation to the new value
static Angle operator * (Angle a, float v)
Multiply the angle, and minimize rotation to the new value
static Angle operator/ (Angle a, float v)
Divide the angle, and minimize rotation to the new value
static bool operator== (Angle a, Angle b)
Compares two angles to see if they represent the same position on a circle.
static bool operator != (Angle a, Angle b)
Compares two angles to see if they do not represent the same position on a circle.
Private Member Functions
Angle Update (float v1)
Performs the min-distance-edit operation, given the new, desired angle value.
Static Private Member Functions
static float Repeat (float v)
Private Attributes
readonly float currentValue
The current value of the angle,
readonly float rotations
The number of whole-circle rotations, times 360, we had to take to get to the current value.
Detailed Description
Represents an angle in degrees that doesn't wrap around to 0 when iterating past 360 degrees. It does this by making the update the smallest delta of value plus whole rotations. e.g. if the current value is 359, setting the value to 1 will actually return as 361, as Abs(361 - 351) < Abs(1 - 351).
Definition at line 11 of file Angle.cs.
Constructor & Destructor Documentation
Angle()
Juniper.Angle.Angle (float v, float r = 0) inline
Create an angle value at set starting point
Parameters
v
r
You should try to instantiate the Angle at a value that is close to the first runtime-value you would receive. The system does not work well for values that oscillate over ~180 degree changes.
Definition at line 23 of file Angle.cs.
         {
             currentValue = v;
             rotations = r;
         }
References Juniper.Angle.currentValue, and Juniper.Angle.rotations.
Referenced by Juniper.Angle.Equals(), Juniper.Angle.operator Angle(), and Juniper.Angle.Update().
Member Function Documentation
Equals()
override bool Juniper.Angle.Equals (object obj) inline
Compares two angles to see if they represent the same position on a circle.
Parameters
obj
Returns
Definition at line 158 of file Angle.cs.
         {
             if (obj is Angle)
             {
                 var angle2 = (Angle)obj;
                 var f1 = Repeat(currentValue);
                 var f2 = Repeat(angle2.currentValue);
                 return f1.Equals(f2);
             }
             else
             {
                 return false;
             }
         }
References Juniper.Angle.Angle(), Juniper.Angle.currentValue, and Juniper.Angle.Repeat().
Referenced by Juniper.Angle.operator !=(), and Juniper.Angle.operator==().
GetHashCode()
override int Juniper.Angle.GetHashCode () inline
Serves as a hash function for a T:UnityEngine.Angle object.
Returns
A hash code for this instance that is suitable for use in hashing algorithms and data structures such as a hash table.
Definition at line 180 of file Angle.cs.
         {
             return Repeat(currentValue).GetHashCode();
         }
References Juniper.Angle.currentValue, and Juniper.Angle.Repeat().
operator !=()
static bool Juniper.Angle.operator != (Angle a, Angle b) inline static
Compares two angles to see if they do not represent the same position on a circle.
Parameters
a
b
Returns
Definition at line 135 of file Angle.cs.
         {
             return !a.Equals(b);
         }
References Juniper.Angle.Equals().
operator %()
static Angle Juniper.Angle.operator % (Angle a, float v) inline static
Whole-number divide the angle and save the remainder, and minimize rotation to the new value
Parameters
a The angle to divide.
v The scalar by which to divide.
Returns
The minimized value of clamp(a % v, 0, 360)
Definition at line 69 of file Angle.cs.
         {
             return a.Update(a.currentValue % v);
         }
References Juniper.Angle.currentValue, and Juniper.Angle.Update().
operator *()
static Angle Juniper.Angle.operator * (Angle a, float v) inline static
Multiply the angle, and minimize rotation to the new value
Parameters
a The angle to multiply.
v The scalar by which to multiply.
Returns
The minimized value of clamp(a * v, 0, 360)
Definition at line 102 of file Angle.cs.
         {
             return a.Update(a.currentValue * v);
         }
References Juniper.Angle.currentValue, and Juniper.Angle.Update().
operator -()
static Angle Juniper.Angle.operator - (Angle a, float v) inline static
Subtract from the angle, and minimize rotation to the new value
Parameters
a The angle to subtract from.
v The scalar by which to subtract.
Returns
The minimized value of clamp(a - v, 0, 360)
Definition at line 91 of file Angle.cs.
         {
             return a.Update(a.currentValue - v);
         }
References Juniper.Angle.currentValue, and Juniper.Angle.Update().
operator ^()
static Angle Juniper.Angle.operator ^ (Angle a, float v) inline static
Create a new Angle struct that represents the smallest turn from the old Angle struct in either the clockwise or counter-clockwise direction that matches the new angle.
Parameters
a The old Angle struct.
v The new angle value, in degrees.
Returns
The new Angle struct that minimizes the likelihood of spinning around in weird circles.
Definition at line 58 of file Angle.cs.
         {
             return a.Update(v);
         }
References Juniper.Angle.Update().
operator Angle()
static Juniper.Angle.operator Angle (float f) inline explicit static
Wrap an angle value in the Angle struct. Useful for using System.Linq.Enumerable.Cast{T} on a collection of Angles.
Parameters
f An angle in degrees
Definition at line 44 of file Angle.cs.
         {
             return new Angle(f);
         }
References Juniper.Angle.Angle().
operator float()
static implicit Juniper.Angle.operator float (Angle a) inline static
Automatically unwrap the value of the Angle, to be able to use with other API fields that expect angle values in degrees.
Parameters
a An Angle object.
Definition at line 34 of file Angle.cs.
         {
             return a.currentValue;
         }
References Juniper.Angle.currentValue.
operator+()
static Angle Juniper.Angle.operator+ (Angle a, float v) inline static
Add to the angle, and minimize rotation to the new value
Parameters
a The angle to add to.
v The scalar by which to add.
Returns
The minimized value of clamp(a + v, 0, 360)
Definition at line 80 of file Angle.cs.
         {
             return a.Update(a.currentValue + v);
         }
References Juniper.Angle.currentValue, and Juniper.Angle.Update().
operator/()
static Angle Juniper.Angle.operator/ (Angle a, float v) inline static
Divide the angle, and minimize rotation to the new value
Parameters
a The angle to divide.
v The scalar by which to divide.
Returns
The minimized value of clamp(a / v, 0, 360)
Definition at line 113 of file Angle.cs.
         {
             return a.Update(a.currentValue / v);
         }
References Juniper.Angle.currentValue, and Juniper.Angle.Update().
operator==()
static bool Juniper.Angle.operator== (Angle a, Angle b) inline static
Compares two angles to see if they represent the same position on a circle.
Parameters
a
b
Returns
Definition at line 124 of file Angle.cs.
         {
             return a.Equals(b);
         }
References Juniper.Angle.Equals().
Repeat()
static float Juniper.Angle.Repeat (float v) inline static private
Definition at line 140 of file Angle.cs.
         {
             while (v >= 360)
             {
                 v -= 360;
             }
             while (v < 0)
             {
                 v += 360;
             }
             return v;
         }
Referenced by Juniper.Angle.Equals(), Juniper.Angle.GetHashCode(), and Juniper.Angle.Update().
Update()
Angle Juniper.Angle.Update (float v1) inline private
Performs the min-distance-edit operation, given the new, desired angle value.
Returns
The update.
Parameters
v1 V1.
Definition at line 200 of file Angle.cs.
         {
             float r = rotations,
                 v0 = currentValue;
             v1 = Repeat(v1);
             float d1, d2, d3;
             do
             {
                 // figure out if it is adding the raw value, or whole rotations of the value, that
                 // results in a smaller magnitude of change.
                 d1 = v1 + r - v0;
                 d2 = Math.Abs(d1 + 360);
                 d3 = Math.Abs(d1 - 360);
                 d1 = Math.Abs(d1);
                 if (d2 < d1 && d2 < d3)
                 {
                     r += 360;
                 }
                 else if (d3 < d1)
                 {
                     r -= 360;
                 }
             } while (d1 > d2 || d1 > d3);
             return new Angle(v1 + r, r);
         }
References Juniper.Angle.Angle(), Juniper.Angle.currentValue, Juniper.Angle.Repeat(), and Juniper.Angle.rotations.
Referenced by Juniper.Angle.operator %(), Juniper.Angle.operator *(), Juniper.Angle.operator -(), Juniper.Angle.operator ^(), Juniper.Angle.operator+(), and Juniper.Angle.operator/().
Member Data Documentation
currentValue
readonly float Juniper.Angle.currentValue private
The current value of the angle,
Definition at line 188 of file Angle.cs.
Referenced by Juniper.Angle.Angle(), Juniper.Angle.Equals(), Juniper.Angle.GetHashCode(), Juniper.Angle.operator %(), Juniper.Angle.operator *(), Juniper.Angle.operator -(), Juniper.Angle.operator float(), Juniper.Angle.operator+(), Juniper.Angle.operator/(), and Juniper.Angle.Update().
rotations
readonly float Juniper.Angle.rotations private
The number of whole-circle rotations, times 360, we had to take to get to the current value.
Definition at line 193 of file Angle.cs.
Referenced by Juniper.Angle.Angle(), and Juniper.Angle.Update().
The documentation for this struct was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Angle.cs