Juniper: System.DateTimeExt Class Reference
System.DateTimeExt Class Reference
Static Public Member Functions
static DateTime UnixTimestampToDateTime (this double timeStamp)
Converts time representations.
static DateTime UnixTimestampToDateTime (this long timeStamp)
Converts time representations.
static float ToJulianDays (this DateTime time)
Converts time representations.
Static Private Attributes
static DateTime epoch = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
The minimum time, according to Unix.
Detailed Description
Definition at line 3 of file DateTimeExt.cs.
Member Function Documentation
ToJulianDays()
static float System.DateTimeExt.ToJulianDays (this DateTime time) inline static
Converts time representations.
Parameters
time A structured date represntation.
Returns
The number of days since the Celestial Julian Day Calculation Epoch (Day 2451545 on the Julian Calendar).
Definition at line 43 of file DateTimeExt.cs.
         {
             const float JDEpoch = 2451545f;
             // Julian Day
             var jdDate = new DateTime(time.Year, time.Month, time.Day, 12, 0, 0);
             if (time.Hour < 12)
             {
                 jdDate = jdDate.AddDays(-1);
             }
             var delta = time - jdDate;
             var Y = jdDate.Year;
             var M = jdDate.Month;
             var D = jdDate.Day;
             // use integer division explicitly
             var JD = (1461 * (Y + 4800 + (M - 14) / 12)) / 4
                 + (367 * (M - 2 - 12 * ((M - 14) / 12))) / 12
                 - (3 * ((Y + 4900 + (M - 14) / 12) / 100)) / 4
                 + D - 32075;
             return JD + (float)delta.TotalDays - JDEpoch;
         }
UnixTimestampToDateTime() [1/2]
static DateTime System.DateTimeExt.UnixTimestampToDateTime (this double timeStamp) inline static
Converts time representations.
Parameters
timeStamp The number of seconds since the Unix Epoch (Midnight, January 1st, 1970)
Returns
A structured date representation.
Definition at line 18 of file DateTimeExt.cs.
         {
             return epoch.AddSeconds(timeStamp).ToLocalTime();
         }
References System.DateTimeExt.epoch.
Referenced by System.DateTimeExt.UnixTimestampToDateTime().
UnixTimestampToDateTime() [2/2]
static DateTime System.DateTimeExt.UnixTimestampToDateTime (this long timeStamp) inline static
Converts time representations.
Parameters
timeStamp The number of seconds since the Unix Epoch (Midnight, January 1st, 1970)
Returns
A structured date representation.
Definition at line 30 of file DateTimeExt.cs.
         {
             return UnixTimestampToDateTime((double)timeStamp);
         }
References System.DateTimeExt.UnixTimestampToDateTime().
Member Data Documentation
epoch
DateTime System.DateTimeExt.epoch = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc) static private
The minimum time, according to Unix.
Definition at line 9 of file DateTimeExt.cs.
Referenced by System.DateTimeExt.UnixTimestampToDateTime().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper.Units/src/DateTimeExt.cs