@setlocal enableextensions
@call ..\src\init-project.bat "Android" "Juniper - Android"
@call ..\src\init-project.bat "AndroidARCore" "Juniper - AndroidARCore"
@call ..\src\init-project.bat "AndroidOculus" "Juniper - AndroidOculus"
@call ..\src\init-project.bat "IOS" "Juniper - IOS"
@call ..\src\init-project.bat "IOSARKit" "Juniper - IOSARKit"
@call ..\src\init-project.bat "MagicLeap" "Juniper - MagicLeap"
@call ..\src\init-project.bat "Standalone" "Juniper - Standalone"
@call ..\src\init-project.bat "StandaloneOculus" "Juniper - StandaloneOculus"
@call ..\src\init-project.bat "StandaloneSteamVR" "Juniper - StandaloneSteamVR"
@call ..\src\init-project.bat "UWP" "Juniper - UWP"
@call ..\src\init-project.bat "UWPHoloLens" "Juniper - UWPHoloLens"
@call ..\src\init-project.bat "UWPWindowsMR" "Juniper - UWPWindowsMR"
@call ..\src\init-project.bat "WebGL" "Juniper - WebGL"