mkdir "Juniper - Android\Assets"
mkdir "Juniper - AndroidARCore\Assets"
mkdir "Juniper - AndroidCardboard\Assets"
mkdir "Juniper - AndroidDaydream\Assets"
mkdir "Juniper - AndroidOculus\Assets"
mkdir "Juniper - AndroidPicoG2\Assets"
mkdir "Juniper - AndroidViveFocus\Assets"
mkdir "Juniper - IOS\Assets"
mkdir "Juniper - IOSARKit\Assets"
mkdir "Juniper - IOSCardboard\Assets"
mkdir "Juniper - Standalone\Assets"
mkdir "Juniper - StandaloneOculus\Assets"
mkdir "Juniper - StandaloneSteamVR\Assets"
mkdir "Juniper - UWP\Assets"
mkdir "Juniper - UWPWindowsMR\Assets"
mkdir "Juniper - UWPHoloLens\Assets"
mkdir "Juniper - MagicLeap\Assets"
mkdir "Juniper - WebGL\Assets"

mklink /J "Juniper - Android\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidARCore\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidCardboard\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidDaydream\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidOculus\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidPicoG2\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidViveFocus\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - IOS\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - IOSARKit\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - IOSCardboard\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - Standalone\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - StandaloneOculus\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - StandaloneSteamVR\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - UWP\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - UWPWindowsMR\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - UWPHoloLens\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - MagicLeap\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - WebGL\Assets\Juniper" "..\src\Juniper\Assets\Juniper"

mklink /H "Juniper - Android\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - AndroidARCore\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - AndroidCardboard\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - AndroidDaydream\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - AndroidOculus\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - AndroidPicoG2\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - AndroidViveFocus\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - IOS\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - IOSARKit\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - IOSCardboard\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - Standalone\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - StandaloneOculus\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - StandaloneSteamVR\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - UWP\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - UWPWindowsMR\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - UWPHoloLens\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - MagicLeap\Assets\csc.rsp" "..\src\Juniper\csc.rsp"
mklink /H "Juniper - WebGL\Assets\csc.rsp" "..\src\Juniper\csc.rsp"

mkdir "Juniper - Android\Assets\Plugins"
mkdir "Juniper - AndroidARCore\Assets\Plugins"
mkdir "Juniper - AndroidCardboard\Assets\Plugins"
mkdir "Juniper - AndroidDaydream\Assets\Plugins"
mkdir "Juniper - AndroidOculus\Assets\Plugins"
mkdir "Juniper - AndroidPicoG2\Assets\Plugins"
mkdir "Juniper - AndroidViveFocus\Assets\Plugins"
mkdir "Juniper - IOS\Assets\Plugins"
mkdir "Juniper - IOSARKit\Assets\Plugins"
mkdir "Juniper - IOSCardboard\Assets\Plugins"
mkdir "Juniper - Standalone\Assets\Plugins"
mkdir "Juniper - StandaloneOculus\Assets\Plugins"
mkdir "Juniper - StandaloneSteamVR\Assets\Plugins"
mkdir "Juniper - UWP\Assets\Plugins"
mkdir "Juniper - UWPWindowsMR\Assets\Plugins"
mkdir "Juniper - UWPHoloLens\Assets\Plugins"
mkdir "Juniper - MagicLeap\Assets\Plugins"
mkdir "Juniper - WebGL\Assets\Plugins"

mklink /J "Juniper - Android\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - AndroidARCore\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - AndroidCardboard\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - AndroidDaydream\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - AndroidOculus\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - AndroidPicoG2\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - AndroidViveFocus\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - IOS\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - IOSARKit\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - IOSCardboard\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - Standalone\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - StandaloneOculus\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - StandaloneSteamVR\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - UWP\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - UWPWindowsMR\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - UWPHoloLens\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - MagicLeap\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"
mklink /J "Juniper - WebGL\Assets\Plugins\Juniper" "..\src\Juniper\Plugins\Juniper"


mkdir "Juniper - Android\Assets\Plugins\Editor"
mkdir "Juniper - AndroidARCore\Assets\Plugins\Editor"
mkdir "Juniper - AndroidCardboard\Assets\Plugins\Editor"
mkdir "Juniper - AndroidDaydream\Assets\Plugins\Editor"
mkdir "Juniper - AndroidOculus\Assets\Plugins\Editor"
mkdir "Juniper - AndroidPicoG2\Assets\Plugins\Editor"
mkdir "Juniper - AndroidViveFocus\Assets\Plugins\Editor"
mkdir "Juniper - IOS\Assets\Plugins\Editor"
mkdir "Juniper - IOSARKit\Assets\Plugins\Editor"
mkdir "Juniper - IOSCardboard\Assets\Plugins\Editor"
mkdir "Juniper - Standalone\Assets\Plugins\Editor"
mkdir "Juniper - StandaloneOculus\Assets\Plugins\Editor"
mkdir "Juniper - StandaloneSteamVR\Assets\Plugins\Editor"
mkdir "Juniper - UWP\Assets\Plugins\Editor"
mkdir "Juniper - UWPWindowsMR\Assets\Plugins\Editor"
mkdir "Juniper - UWPHoloLens\Assets\Plugins\Editor"
mkdir "Juniper - MagicLeap\Assets\Plugins\Editor"
mkdir "Juniper - WebGL\Assets\Plugins\Editor"

mklink /J "Juniper - Android\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - AndroidARCore\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - AndroidCardboard\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - AndroidDaydream\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - AndroidOculus\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - AndroidPicoG2\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - AndroidViveFocus\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - IOS\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - IOSARKit\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - IOSCardboard\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - Standalone\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - StandaloneOculus\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - StandaloneSteamVR\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - UWP\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - UWPWindowsMR\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - UWPHoloLens\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - MagicLeap\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"
mklink /J "Juniper - WebGL\Assets\Plugins\Editor\Juniper" "..\src\Juniper\Plugins\Editor\Juniper"


mklink /J "Juniper - AndroidARCore\Assets\GoogleARCore\" "..\src\Juniper\Assets\GoogleARCore"
mklink /J "Juniper - AndroidARCore\Assets\PlayServicesResolver\" "..\src\Juniper\Assets\PlayServicesResolver"

mklink /J "Juniper - AndroidCardboard\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - AndroidDaydream\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - AndroidPicoG2\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - AndroidViveFocus\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - IOSCardboard\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - StandaloneSteamVR\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"

mklink /J "Juniper - AndroidDaydream\Assets\GoogleVR" "..\src\Juniper\Assets\GoogleVR"

mklink /J "Juniper - AndroidOculus\Assets\Oculus" "..\src\Juniper\Assets\Oculus"
mklink /J "Juniper - StandaloneOculus\Assets\Oculus" "..\src\Juniper\Assets\Oculus"

mklink /J "Juniper - AndroidPicoG2\Assets\PicoMobileSDK" "..\src\Juniper\Assets\PicoMobileSDK"

mklink /J "Juniper - AndroidViveFocus\Assets\WaveVR" "..\src\Juniper\Assets\WaveVR"

mklink /J "Juniper - Standalone\Assets\Tobii" "..\src\Juniper\Assets\Tobii"