mkdir "Juniper - Android\Assets"
mkdir "Juniper - AndroidARCore\Assets"
mkdir "Juniper - AndroidCardboard\Assets"
mkdir "Juniper - AndroidDaydream\Assets"
mkdir "Juniper - AndroidOculus\Assets"
mkdir "Juniper - AndroidPicoG2\Assets"
mkdir "Juniper - AndroidViveFocus\Assets"
mkdir "Juniper - IOS\Assets"
mkdir "Juniper - IOSARKit\Assets"
mkdir "Juniper - IOSCardboard\Assets"
mkdir "Juniper - Standalone\Assets"
mkdir "Juniper - StandaloneOculus\Assets"
mkdir "Juniper - StandaloneSteamVR\Assets"
mkdir "Juniper - UWP\Assets"
mkdir "Juniper - UWPWindowsMR\Assets"
mkdir "Juniper - UWPHoloLens\Assets"
mkdir "Juniper - MagicLeap\Assets"
mkdir "Juniper - WebGL\Assets"

mklink /J "Juniper - Android\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidARCore\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidCardboard\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidDaydream\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidOculus\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidPicoG2\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - AndroidViveFocus\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - IOS\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - IOSARKit\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - IOSCardboard\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - Standalone\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - StandaloneOculus\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - StandaloneSteamVR\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - UWP\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - UWPWindowsMR\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - UWPHoloLens\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - MagicLeap\Assets\Juniper" "..\src\Juniper\Assets\Juniper"
mklink /J "Juniper - WebGL\Assets\Juniper" "..\src\Juniper\Assets\Juniper"

mklink /J "Juniper - Android\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - AndroidARCore\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - AndroidCardboard\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - AndroidDaydream\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - AndroidOculus\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - AndroidPicoG2\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - AndroidViveFocus\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - IOS\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - IOSARKit\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - IOSCardboard\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - Standalone\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - StandaloneOculus\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - StandaloneSteamVR\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - UWP\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - UWPWindowsMR\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - UWPHoloLens\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - MagicLeap\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"
mklink /J "Juniper - WebGL\Assets\TextMesh Pro" "..\src\Juniper\Assets\TextMesh Pro"

mklink /J "Juniper - AndroidARCore\Assets\GoogleARCore\" "..\src\Juniper\Assets\GoogleARCore"
mklink /J "Juniper - AndroidARCore\Assets\PlayServicesResolver\" "..\src\Juniper\Assets\PlayServicesResolver"

mklink /J "Juniper - AndroidCardboard\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - AndroidDaydream\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - AndroidPicoG2\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - AndroidViveFocus\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - IOSCardboard\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"
mklink /J "Juniper - StandaloneSteamVR\Assets\ResonanceAudio\" "..\src\Juniper\Assets\ResonanceAudio"

mklink /J "Juniper - AndroidDaydream\Assets\GoogleVR" "..\src\Juniper\Assets\GoogleVR"

mklink /J "Juniper - AndroidOculus\Assets\Oculus" "..\src\Juniper\Assets\Oculus"
mklink /J "Juniper - StandaloneOculus\Assets\Oculus" "..\src\Juniper\Assets\Oculus"

mklink /J "Juniper - AndroidPicoG2\Assets\PicoMobileSDK" "..\src\Juniper\Assets\PicoMobileSDK"

mklink /J "Juniper - AndroidViveFocus\Assets\WaveVR" "..\src\Juniper\Assets\WaveVR"

mklink /J "Juniper - Standalone\Assets\Tobii" "..\src\Juniper\Assets\Tobii"