Juniper: Juniper.Unity.PermissionHandler Class Reference
Juniper.Unity.PermissionHandler Class Reference
Public Member Functions
void Awake ()
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
virtual void Reinstall ()
void Reset ()
void Install (bool reset)
void Uninstall ()
Detailed Description
Definition at line 11 of file PermissionHandler.cs.
Member Function Documentation
Awake()
void Juniper.Unity.PermissionHandler.Awake () inline
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Definition at line 16 of file PermissionHandler.cs.
         {
             Install(false);
 #if UNITY_IOS
             if(Application.isPlaying)
             {
                 var auth = UserAuthorization.WebCam;
                 var speech = ComponentExt.FindAny<Input.Speech.KeywordRecognizer>();
                 if (speech != null && speech.IsAvailable)
                 {
                     auth |= UserAuthorization.Microphone;
                 }
                 Application.RequestUserAuthorization(auth);
             }
 #endif
         }
References Juniper.Unity.PermissionHandler.Install().
Install()
void Juniper.Unity.PermissionHandler.Install (bool reset) inline
Implements Juniper.IInstallable.
Definition at line 47 of file PermissionHandler.cs.
         {
 #if MAGIC_LEAP
             this.EnsureComponent<PrivilegeRequester>();
 #endif
         }
Referenced by Juniper.Unity.PermissionHandler.Awake(), and Juniper.Unity.PermissionHandler.Reinstall().
Reinstall()
virtual void Juniper.Unity.PermissionHandler.Reinstall () inline virtual
Implements Juniper.IInstallable.
Definition at line 33 of file PermissionHandler.cs.
         {
             Install(true);
         }
References Juniper.Unity.PermissionHandler.Install().
Referenced by Juniper.Unity.PermissionHandler.Reset().
Reset()
void Juniper.Unity.PermissionHandler.Reset () inline
Definition at line 40 of file PermissionHandler.cs.
         {
             Reinstall();
         }
References Juniper.Unity.PermissionHandler.Reinstall().
Uninstall()
void Juniper.Unity.PermissionHandler.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 54 of file PermissionHandler.cs.
         {
 #if MAGIC_LEAP
             this.RemoveComponent<PrivilegeRequester>();
 #endif
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/PermissionHandler.cs