Juniper: Juniper.Speech.NoKeywordRecognizer Class Reference
Juniper.Speech.NoKeywordRecognizer Class Reference
Public Member Functions
void RefreshKeywords ()
Find all of the keyword-responding components that are currently active in the scene, collect up their keywords, and register them return them as a set-array to be registered with the speech recognition system.
void OnEnable ()
Initialize the speech recognition system.
void OnDisable ()
Tear down the speech recognition system.
Public Attributes
const bool IsAvailable = false
Reads as true if the current XR subsystem supports speech recognition.
StringEvent onKeywordRecognized = new StringEvent()
Respond to the speech recognition system having detected a keyword. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should prefer KeywordRecognized.
Protected Member Functions
override void Setup ()
override void TearDown ()
void OnKeywordRecognized (string keyword)
Invokes onKeywordRecognized and KeywordRecognized.
Protected Attributes
string [] keywords
The keywords for which to listen.
Events
EventHandler< KeywordRecognizedEventArgs > KeywordRecognized
Respond to the speech recognition system having detected a keyword. You should only use this version if you are programmatically attaching event listeners. If you are attaching events in the Unity Editor, you should prefer onKeywordRecognized.
Detailed Description
Definition at line 5 of file NoKeywordRecognizer.cs.
Member Function Documentation
OnDisable()
void Juniper.Speech.AbstractKeywordRecognizer.OnDisable () inline inherited
Tear down the speech recognition system.
Definition at line 87 of file KeywordRecognizer.cs.
         {
             TearDown();
         }
References Juniper.Speech.AbstractKeywordRecognizer.TearDown().
OnEnable()
void Juniper.Speech.AbstractKeywordRecognizer.OnEnable () inline inherited
Initialize the speech recognition system.
Definition at line 79 of file KeywordRecognizer.cs.
         {
             RefreshKeywords();
         }
References Juniper.Speech.AbstractKeywordRecognizer.RefreshKeywords().
OnKeywordRecognized()
void Juniper.Speech.AbstractKeywordRecognizer.OnKeywordRecognized (string keyword) inline protected inherited
Invokes onKeywordRecognized and KeywordRecognized.
Parameters
keyword Keyword.
Definition at line 48 of file KeywordRecognizer.cs.
         {
             onKeywordRecognized?.Invoke(keyword);
             KeywordRecognized?.Invoke(this, new KeywordRecognizedEventArgs(keyword));
         }
References Juniper.Speech.AbstractKeywordRecognizer.KeywordRecognized, and Juniper.Speech.AbstractKeywordRecognizer.onKeywordRecognized.
RefreshKeywords()
void Juniper.Speech.AbstractKeywordRecognizer.RefreshKeywords () inline inherited
Find all of the keyword-responding components that are currently active in the scene, collect up their keywords, and register them return them as a set-array to be registered with the speech recognition system.
Returns
The active keywords.
Implements Juniper.Speech.IKeywordRecognizer.
Definition at line 60 of file KeywordRecognizer.cs.
         {
             TearDown();
             keywords = (from comp in ComponentExt.FindAll<MonoBehaviour>()
                         where comp is IKeywordTriggered
                         let trigger = (IKeywordTriggered)comp
                         where trigger.Keywords != null
                         from keyword in trigger.Keywords
                         where !string.IsNullOrEmpty(keyword)
                         select keyword)
                 .Distinct()
                 .OrderBy(x => x)
                 .ToArray();
             Setup();
         }
References Juniper.Speech.IKeywordTriggered.Keywords, Juniper.Speech.AbstractKeywordRecognizer.keywords, Juniper.Speech.AbstractKeywordRecognizer.Setup(), and Juniper.Speech.AbstractKeywordRecognizer.TearDown().
Referenced by Juniper.Speech.Keywordable.OnEnable(), and Juniper.Speech.AbstractKeywordRecognizer.OnEnable().
Setup()
override void Juniper.Speech.NoKeywordRecognizer.Setup () inline protected virtual
Implements Juniper.Speech.AbstractKeywordRecognizer.
Definition at line 12 of file NoKeywordRecognizer.cs.
         {
             Debug.Log("No speech recognition available");
         }
TearDown()
override void Juniper.Speech.NoKeywordRecognizer.TearDown () inline protected virtual
Implements Juniper.Speech.AbstractKeywordRecognizer.
Definition at line 17 of file NoKeywordRecognizer.cs.
         {
         }
Member Data Documentation
IsAvailable
const bool Juniper.Speech.NoKeywordRecognizer.IsAvailable = false
Reads as true if the current XR subsystem supports speech recognition.
Definition at line 10 of file NoKeywordRecognizer.cs.
keywords
string [] Juniper.Speech.AbstractKeywordRecognizer.keywords protected inherited
The keywords for which to listen.
Definition at line 28 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.AbstractKeywordRecognizer.RefreshKeywords().
onKeywordRecognized
StringEvent Juniper.Speech.AbstractKeywordRecognizer.onKeywordRecognized = new StringEvent() inherited
Respond to the speech recognition system having detected a keyword. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should prefer KeywordRecognized.
Definition at line 35 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.AbstractKeywordRecognizer.OnKeywordRecognized(), and Juniper.Speech.Keywordable.Start().
Event Documentation
KeywordRecognized
EventHandler<KeywordRecognizedEventArgs> Juniper.Speech.AbstractKeywordRecognizer.KeywordRecognized inherited
Respond to the speech recognition system having detected a keyword. You should only use this version if you are programmatically attaching event listeners. If you are attaching events in the Unity Editor, you should prefer onKeywordRecognized.
Definition at line 42 of file KeywordRecognizer.cs.
Referenced by Juniper.Speech.AbstractKeywordRecognizer.OnKeywordRecognized().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Speech/NoKeywordRecognizer.cs