Juniper: Juniper.IO.ICacheDestinationLayer Interface Reference
Juniper.IO.ICacheDestinationLayer Interface Reference
Public Member Functions
bool CanCache (ContentReference fileRef)
Stream Create (ContentReference fileRef)
bool Delete (ContentReference fileRef)
bool IsCached (ContentReference fileRef)
Task< Stream > GetStreamAsync (ContentReference fileRef, IProgress prog)
IEnumerable< ContentReference > GetContentReferences (MediaType ofType)
Detailed Description
Definition at line 5 of file ICacheDestinationLayer.cs.
Member Function Documentation
CanCache()
bool Juniper.IO.ICacheDestinationLayer.CanCache (ContentReference fileRef)
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.FileCacheLayer, Juniper.World.GIS.Google.GoogleMapsCacheLayer, and Juniper.IO.MemoryCacheLayer.
Create()
Stream Juniper.IO.ICacheDestinationLayer.Create (ContentReference fileRef)
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.FileCacheLayer, and Juniper.IO.MemoryCacheLayer.
Referenced by Juniper.IO.ICacheDestinationLayerExt.CopyToAsync(), Juniper.IO.ICacheDestinationLayerExt.Save< ResultType >(), and Juniper.IO.ICacheDestinationLayerExt.SaveJson< ResultType >().
Delete()
bool Juniper.IO.ICacheDestinationLayer.Delete (ContentReference fileRef)
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.FileCacheLayer, and Juniper.IO.MemoryCacheLayer.
GetContentReferences()
IEnumerable<ContentReference> Juniper.IO.ICacheSourceLayer.GetContentReferences (MediaType ofType) inherited
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.ZipFileCacheLayer, Juniper.IO.FileCacheLayer, Juniper.IO.MemoryCacheLayer, and Juniper.IO.StreamSourceLayer.
Referenced by Juniper.IO.ICacheSourceLayerExt.GetAsync< ResultT, MediaTypeT >().
GetStreamAsync()
Task<Stream> Juniper.IO.ICacheSourceLayer.GetStreamAsync (ContentReference fileRef, IProgress prog) inherited
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.ZipFileCacheLayer, Juniper.IO.FileCacheLayer, Juniper.IO.MemoryCacheLayer, and Juniper.IO.StreamSourceLayer.
Referenced by Juniper.IO.ICacheDestinationLayerExt.CopyToAsync(), Juniper.IO.ICacheSourceLayerExt.GetAsync< ResultT, MediaTypeT >(), Juniper.IO.ICacheSourceLayerExt.LoadAsync< ResultT >(), Juniper.IO.ICacheSourceLayerExt.OpenAsync(), and Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync().
IsCached()
bool Juniper.IO.ICacheSourceLayer.IsCached (ContentReference fileRef) inherited
Implemented in Juniper.IO.CachingStrategy, Juniper.IO.ZipFileCacheLayer, Juniper.IO.StreamSourceLayer, Juniper.IO.FileCacheLayer, and Juniper.IO.MemoryCacheLayer.
Referenced by Juniper.IO.ICacheDestinationLayerExt.CopyToAsync().
The documentation for this interface was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/ICacheDestinationLayer.cs