Juniper: Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType > Class Template Reference
Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType > Class Template Reference
Public Member Functions
void Install (GameObject eventParent, Dictionary< ButtonIDType, InputEventButton > buttonMapping)
void AddButton (GameObject eventParent, ButtonIDType buttonID, InputEventButton buttonValue)
void RemoveButton (ButtonIDType buttonID)
bool IsButtonDown (InputButton button)
bool IsButtonUp (InputButton button)
bool IsButtonPressed (InputButton button)
IEventSystemHandler Process (PointerEventData eventData, float pixelDragThresholdSquared)
Properties
bool IsDragging [get]
Events
Action< Interaction > InteractionNeeded
Func< ButtonIDType, bool > ButtonDownNeeded
Func< ButtonIDType, bool > ButtonUpNeeded
Func< ButtonIDType, bool > ButtonPressedNeeded
Func< int, PointerEventData, PointerEventData > ClonedPointerEventNeeded
Private Member Functions
bool OnButtonDownNeeded (ButtonIDType button)
bool OnButtonUpNeeded (ButtonIDType button)
bool OnButtonPressedNeeded (ButtonIDType button)
PointerEventData OnClonedPointerEventNeeded (int pointerID, PointerEventData donor)
void OnInteractionNeeded (Interaction action)
MappedButton< ButtonIDType > FindMappedButton (InputButton inputBtn)
Private Attributes
readonly List< MappedButton< ButtonIDType > > buttons = new List<MappedButton<ButtonIDType>>(5)
Detailed Description
Type Constraints
ButtonIDType : struct
Definition at line 15 of file ButtonMapper.cs.
Member Function Documentation
AddButton()
void Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.AddButton (GameObject eventParent, ButtonIDType buttonID, InputEventButton buttonValue) inline
Definition at line 57 of file ButtonMapper.cs.
         {
             var btn = new MappedButton<ButtonIDType>(buttonID, buttonValue, eventParent);
             btn.ButtonDownNeeded += OnButtonDownNeeded;
             btn.ButtonUpNeeded += OnButtonUpNeeded;
             btn.ButtonPressedNeeded += OnButtonPressedNeeded;
             btn.ClonedPointerEventNeeded += OnClonedPointerEventNeeded;
             btn.InteractionNeeded += OnInteractionNeeded;
             buttons.Add(btn);
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.AddButton(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Install().
FindMappedButton()
MappedButton<ButtonIDType> Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.FindMappedButton (InputButton inputBtn) inline private
Definition at line 108 of file ButtonMapper.cs.
         {
             foreach (var button in buttons)
             {
                 if (button.UnityInputButton == inputBtn)
                 {
                     return button;
                 }
             }
             return null;
         }
Referenced by Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.IsButtonDown(), Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.IsButtonPressed(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.IsButtonUp().
Install()
void Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.Install (GameObject eventParent, Dictionary< ButtonIDType, InputEventButton > buttonMapping) inline
Definition at line 38 of file ButtonMapper.cs.
         {
             buttons.Clear();
             foreach (var pair in buttonMapping)
             {
                 AddButton(eventParent, pair.Key, pair.Value);
             }
             foreach (var evt in eventParent.GetComponents<ButtonEvent>())
             {
                 if (string.IsNullOrEmpty(evt.buttonTypeName)
                     || string.IsNullOrEmpty(evt.buttonValueName))
                 {
                     evt.Destroy();
                 }
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerConfiguration< KeyCode >.Install(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionControllerConfiguration< InteractionSourceHandedness, WindowsMRButtons >.Install().
IsButtonDown()
bool Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.IsButtonDown (InputButton button) inline
Definition at line 120 of file ButtonMapper.cs.
         {
             return FindMappedButton(button)?.IsDown == true;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown().
IsButtonPressed()
bool Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.IsButtonPressed (InputButton button) inline
Definition at line 130 of file ButtonMapper.cs.
         {
             return FindMappedButton(button)?.IsPressed == true;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonPressed().
IsButtonUp()
bool Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.IsButtonUp (InputButton button) inline
Definition at line 125 of file ButtonMapper.cs.
         {
             return FindMappedButton(button)?.IsUp == true;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp().
OnButtonDownNeeded()
bool Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.OnButtonDownNeeded (ButtonIDType button) inline private
Definition at line 83 of file ButtonMapper.cs.
         {
             return ButtonDownNeeded?.Invoke(button) == true;
         }
Referenced by Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.AddButton(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.RemoveButton().
OnButtonPressedNeeded()
bool Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.OnButtonPressedNeeded (ButtonIDType button) inline private
Definition at line 93 of file ButtonMapper.cs.
         {
             return ButtonPressedNeeded?.Invoke(button) == true;
         }
Referenced by Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.AddButton(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.RemoveButton().
OnButtonUpNeeded()
bool Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.OnButtonUpNeeded (ButtonIDType button) inline private
Definition at line 88 of file ButtonMapper.cs.
         {
             return ButtonUpNeeded?.Invoke(button) == true;
         }
Referenced by Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.AddButton(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.RemoveButton().
OnClonedPointerEventNeeded()
PointerEventData Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.OnClonedPointerEventNeeded (int pointerID, PointerEventData donor) inline private
Definition at line 98 of file ButtonMapper.cs.
         {
             return ClonedPointerEventNeeded?.Invoke(pointerID, donor);
         }
Referenced by Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.AddButton(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.RemoveButton().
OnInteractionNeeded()
void Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.OnInteractionNeeded (Interaction action) inline private
Definition at line 103 of file ButtonMapper.cs.
         {
             InteractionNeeded?.Invoke(action);
         }
Referenced by Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.AddButton(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.RemoveButton().
Process()
IEventSystemHandler Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.Process (PointerEventData eventData, float pixelDragThresholdSquared) inline
Definition at line 135 of file ButtonMapper.cs.
         {
             IEventSystemHandler eventTarget = null;
             foreach (var btn in buttons)
             {
                 eventTarget = btn.Process(eventData, pixelDragThresholdSquared);
             }
             return eventTarget;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.ProcessButtons().
RemoveButton()
void Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.RemoveButton (ButtonIDType buttonID) inline
Definition at line 68 of file ButtonMapper.cs.
         {
             var btn = buttons.FirstOrDefault(b => b.button.Equals(buttonID));
             if (btn != null)
             {
                 buttons.Remove(btn);
                 btn.ButtonDownNeeded -= OnButtonDownNeeded;
                 btn.ButtonUpNeeded -= OnButtonUpNeeded;
                 btn.ButtonPressedNeeded -= OnButtonPressedNeeded;
                 btn.ClonedPointerEventNeeded += OnClonedPointerEventNeeded;
                 btn.InteractionNeeded -= OnInteractionNeeded;
                 btn.Destroy();
             }
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.RemoveButton().
Member Data Documentation
buttons
readonly List<MappedButton<ButtonIDType> > Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.buttons = new List<MappedButton<ButtonIDType>>(5) private
Definition at line 28 of file ButtonMapper.cs.
Referenced by Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.AddButton(), Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.FindMappedButton(), Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Install(), Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.RemoveButton().
Property Documentation
IsDragging
bool Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.IsDragging get
Definition at line 31 of file ButtonMapper.cs.
         {
             get
             {
                 return buttons.Any((btn) => btn.IsPressed && !btn.IsDown);
             }
         }
Event Documentation
ButtonDownNeeded
Func<ButtonIDType, bool> Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.ButtonDownNeeded
Definition at line 20 of file ButtonMapper.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.OnButtonDownNeeded().
ButtonPressedNeeded
Func<ButtonIDType, bool> Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.ButtonPressedNeeded
Definition at line 24 of file ButtonMapper.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.OnButtonPressedNeeded().
ButtonUpNeeded
Func<ButtonIDType, bool> Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.ButtonUpNeeded
Definition at line 22 of file ButtonMapper.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.OnButtonUpNeeded().
ClonedPointerEventNeeded
Func<int, PointerEventData, PointerEventData> Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.ClonedPointerEventNeeded
Definition at line 26 of file ButtonMapper.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.OnClonedPointerEventNeeded().
InteractionNeeded
Action<Interaction> Juniper.Unity.Input.Pointers.ButtonMapper< ButtonIDType >.InteractionNeeded
Definition at line 18 of file ButtonMapper.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Unity.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.OnInteractionNeeded().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/Pointers/ButtonMapper.cs