Juniper: Juniper.Units.Hours Class Reference
Juniper.Units.Hours Class Reference
Conversions from hours
Static Public Member Functions
static float Nanoseconds (float hours)
Convert from hours to nanoseconds.
static float Ticks (float hours)
Convert from hours to ticks.
static float Microseconds (float hours)
Convert from hours to microseconds.
static float Milliseconds (float hours)
Convert from hours to milliseconds.
static float Seconds (float hours)
Convert from hours to seconds.
static float Minutes (float hours)
Convert from hours to minutes.
static float Days (float hours)
Convert from hours to days.
static float Degrees (float hours)
Convert from hours to degrees.
static float Radians (float hours)
Convert from hours to radians.
static float Hertz (float hours)
Convert from hours to hertz.
static IEnumerator Wait (float hours)
Create an enumerator that doesn't resolve until the time limit is reached.
Public Attributes
const float PER_NANOSECOND = 1 / Units.Nanoseconds.PER_HOUR
Conversion factor from nanoseconds to hours.
const float PER_TICK = 1 / Units.Ticks.PER_HOUR
Conversion factor from ticks to hours.
const float PER_MICROSECOND = 1 / Units.Microseconds.PER_HOUR
Conversion factor from microseconds to hours.
const float PER_MILLISECOND = 1 / Units.Milliseconds.PER_HOUR
Conversion factor from milliseconds to hours.
const float PER_SECOND = 1 / Units.Seconds.PER_HOUR
Conversion factor from seconds to hours.
const float PER_MINUTE = 1 / Units.Minutes.PER_HOUR
Conversion factor from minutes to hours.
const float PER_DAY = 24f
Conversion factor from days to hours.
const float PER_DEGREE = PER_DAY / Units.Degrees.PER_CIRCLE
Conversion factor from degrees to hours.
const float PER_RADIAN = PER_DAY / Units.Radians.PER_CIRCLE
Conversion factor from radians to hours.
const float PER_GRADIAN = PER_DAY / Units.Gradians.PER_CIRCLE
Conversion factor from gradians to hours.
const float PER_CIRCLE = PER_DAY
Conversion factor from circles to hours.
Detailed Description
Conversions from hours
Definition at line 9 of file Hours.cs.
Member Function Documentation
Days()
static float Juniper.Units.Hours.Days (float hours) inline static
Convert from hours to days.
Parameters
hours The number of hours
Returns
The number of days
Definition at line 131 of file Hours.cs.
         {
             return hours * Units.Days.PER_HOUR;
         }
References Juniper.Units.Units.
Degrees()
static float Juniper.Units.Hours.Degrees (float hours) inline static
Convert from hours to degrees.
Parameters
hours The number of hours
Returns
The number of degrees
Definition at line 141 of file Hours.cs.
         {
             return hours * Units.Degrees.PER_HOUR;
         }
References Juniper.Units.Units.
Hertz()
static float Juniper.Units.Hours.Hertz (float hours) inline static
Convert from hours to hertz.
Parameters
hours The number of hours
Returns
The number of hertz
Definition at line 161 of file Hours.cs.
         {
             return Units.Seconds.Hertz(Seconds(hours));
         }
References Juniper.Units.Hours.Seconds(), and Juniper.Units.Units.
Microseconds()
static float Juniper.Units.Hours.Microseconds (float hours) inline static
Convert from hours to microseconds.
Parameters
hours The number of hours
Returns
The number of microseconds
Definition at line 91 of file Hours.cs.
         {
             return hours * Units.Microseconds.PER_HOUR;
         }
References Juniper.Units.Units.
Milliseconds()
static float Juniper.Units.Hours.Milliseconds (float hours) inline static
Convert from hours to milliseconds.
Parameters
hours The number of hours
Returns
The number of milliseconds
Definition at line 101 of file Hours.cs.
         {
             return hours * Units.Milliseconds.PER_HOUR;
         }
References Juniper.Units.Units.
Minutes()
static float Juniper.Units.Hours.Minutes (float hours) inline static
Convert from hours to minutes.
Parameters
hours The number of hours
Returns
The number of minutes
Definition at line 121 of file Hours.cs.
         {
             return hours * Units.Minutes.PER_HOUR;
         }
References Juniper.Units.Units.
Nanoseconds()
static float Juniper.Units.Hours.Nanoseconds (float hours) inline static
Convert from hours to nanoseconds.
Parameters
hours The number of hours
Returns
The number of nanoseconds
Definition at line 71 of file Hours.cs.
         {
             return hours * Units.Nanoseconds.PER_HOUR;
         }
References Juniper.Units.Units.
Radians()
static float Juniper.Units.Hours.Radians (float hours) inline static
Convert from hours to radians.
Parameters
hours The number of hours
Returns
The number of radians
Definition at line 151 of file Hours.cs.
         {
             return hours * Units.Radians.PER_HOUR;
         }
References Juniper.Units.Units.
Referenced by Juniper.Units.EquitorialSpherical.ToHorizontal().
Seconds()
static float Juniper.Units.Hours.Seconds (float hours) inline static
Convert from hours to seconds.
Parameters
hours The number of hours
Returns
The number of seconds
Definition at line 111 of file Hours.cs.
         {
             return hours * Units.Seconds.PER_HOUR;
         }
References Juniper.Units.Units.
Referenced by Juniper.Units.Hours.Hertz().
Ticks()
static float Juniper.Units.Hours.Ticks (float hours) inline static
Convert from hours to ticks.
Parameters
hours The number of hours
Returns
The number of ticks
Definition at line 81 of file Hours.cs.
         {
             return hours * Units.Ticks.PER_HOUR;
         }
References Juniper.Units.Units.
Wait()
static IEnumerator Juniper.Units.Hours.Wait (float hours) inline static
Create an enumerator that doesn't resolve until the time limit is reached.
Parameters
hours
Returns
Definition at line 171 of file Hours.cs.
         {
             var start = DateTime.Now;
             var ts = TimeSpan.FromHours(hours);
             while ((DateTime.Now - start) < ts)
             {
                 yield return null;
             }
         }
Member Data Documentation
PER_CIRCLE
const float Juniper.Units.Hours.PER_CIRCLE = PER_DAY
Conversion factor from circles to hours.
Definition at line 64 of file Hours.cs.
PER_DAY
const float Juniper.Units.Hours.PER_DAY = 24f
Conversion factor from days to hours.
Definition at line 44 of file Hours.cs.
PER_DEGREE
const float Juniper.Units.Hours.PER_DEGREE = PER_DAY / Units.Degrees.PER_CIRCLE
Conversion factor from degrees to hours.
Definition at line 49 of file Hours.cs.
PER_GRADIAN
const float Juniper.Units.Hours.PER_GRADIAN = PER_DAY / Units.Gradians.PER_CIRCLE
Conversion factor from gradians to hours.
Definition at line 59 of file Hours.cs.
PER_MICROSECOND
const float Juniper.Units.Hours.PER_MICROSECOND = 1 / Units.Microseconds.PER_HOUR
Conversion factor from microseconds to hours.
Definition at line 24 of file Hours.cs.
PER_MILLISECOND
const float Juniper.Units.Hours.PER_MILLISECOND = 1 / Units.Milliseconds.PER_HOUR
Conversion factor from milliseconds to hours.
Definition at line 29 of file Hours.cs.
PER_MINUTE
const float Juniper.Units.Hours.PER_MINUTE = 1 / Units.Minutes.PER_HOUR
Conversion factor from minutes to hours.
Definition at line 39 of file Hours.cs.
PER_NANOSECOND
const float Juniper.Units.Hours.PER_NANOSECOND = 1 / Units.Nanoseconds.PER_HOUR
Conversion factor from nanoseconds to hours.
Definition at line 14 of file Hours.cs.
PER_RADIAN
const float Juniper.Units.Hours.PER_RADIAN = PER_DAY / Units.Radians.PER_CIRCLE
Conversion factor from radians to hours.
Definition at line 54 of file Hours.cs.
PER_SECOND
const float Juniper.Units.Hours.PER_SECOND = 1 / Units.Seconds.PER_HOUR
Conversion factor from seconds to hours.
Definition at line 34 of file Hours.cs.
PER_TICK
const float Juniper.Units.Hours.PER_TICK = 1 / Units.Ticks.PER_HOUR
Conversion factor from ticks to hours.
Definition at line 19 of file Hours.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Units/Time/Hours.cs