Juniper: Juniper.MasterSceneController Class Reference
Juniper.MasterSceneController Class Reference
Manages loading SubSceneController components (scenes that are additively loaded into a "main" scene), as well as transitioning between them.
Public Member Functions
void Update ()
void SwitchToSceneName (string sceneName, bool skipFadeOut=false)
A subscene is a root game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
void Quit ()
Quit out of the application, making sure any exit transitions for the current scene are ran first.
virtual void Awake ()
Disable any subScenes that are alive in the main scene.
virtual void Reinstall ()
void Reset ()
void Install (bool reset)
void Uninstall ()
void LoadAllScenes ()
void OnValidate ()
Static Public Member Functions
static void QuitApp ()
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Public Attributes
LoadingBar loadingBar
Image splash
GameObject optionsInterface
Material sceneFaderMaterial
The material to apply to Darth Fader.
bool loadAll = true
bool exitOnEscape = true
string [] subSceneNames
All of the scene files to load. Use the "truncated scene path" format for these paths. Truncated scene paths do not need to reference the "Assets/" (it is assumed) and do not need the ".unity" file extension.
IEnumerable< SubSceneController > SubScenes
All of the SubSceneController references in the project.
SubSceneController [] CurrentSubScenes
All of the active SubSceneControllers
Protected Member Functions
virtual void Start ()
Wait until the Start method to load the scenes so the MasterSceneController or any child class of it can be found by the newly loaded scenes more reliably.
Properties
static IEnumerable< Scene > AllScenes [get]
Get all of the scenes defined in the Build settings.
Private Member Functions
void FadeOut (bool skipFadeOut)
IEnumerator SwitchToSceneNameCoroutine (string subSceneName, bool skipFadeOut=false)
IEnumerator LoadingCompleteCoroutine ()
IEnumerator LoadAllScenesCoroutine2 ()
IEnumerator LoadAllScenesCoroutine (IProgressReceiver prog=null)
Use this function by right-clicking in the editor to open up all the scenes in additive mode.
void LoadFirstScene ()
void LoadScenes_MenuItem ()
Use this function by right-clicking in the editor to open up all the scenes in additive mode.
void SetBuildSettings ()
Scene? GetScene (string sceneName, string path)
Get a scene by name (or path, if we're running in the editor).
IEnumerator LoadScenePathCoroutine (string path, IProgressReceiver prog)
void Flatten ()
Copy all of the root scene objects out of the sub scenes and into the master scene, removing the subscenes along the way. This can also be executed from the editor by accessing the component's context menu and selecting "Flatten".
IEnumerator QuitCoroutine ()
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Static Private Member Functions
static IProgress LoadScene (string scenePath, string sceneName)
Get a scene by name (or path, if we're running in the editor).
static string GetSceneNameFromPath (string path)
static bool IsScenePathLoaded (string path)
static void Exit ()
Close the application.
Private Attributes
const string SceneNamePatternStr = "([^/]+)\\.unity$"
Parse the scene name.
FadeTransition darth
bool wasLocked
A flag that indicates the cursor was locked on the previous frame.
Static Private Attributes
static readonly Regex SceneNamePattern = new Regex(SceneNamePatternStr, RegexOptions.Compiled)
Parse the scene name.
Detailed Description
Manages loading SubSceneController components (scenes that are additively loaded into a "main" scene), as well as transitioning between them.
Definition at line 35 of file MasterSceneController.cs.
Member Function Documentation
Awake()
virtual void Juniper.MasterSceneController.Awake () inline virtual
Disable any subScenes that are alive in the main scene.
Definition at line 230 of file MasterSceneController.cs.
         {
             Install(false);
             // Unity hacks the sense of null, creating a value reference that compares to null,
             // but doesn't work with the null coallescing operator. So we make it actually,
             // really null here.
             if (splash == null)
             {
                 splash = null;
             }
             if (optionsInterface == null)
             {
                 optionsInterface = null;
             }
             optionsInterface?.Deactivate();
             splash?.Activate();
             darth = ComponentExt.FindAny<FadeTransition>();
             foreach (var subScene in FindObjectsOfType<SubSceneController>())
             {
                 subScene.Deactivate();
             }
         }
References Juniper.MasterSceneController.darth, Juniper.MasterSceneController.Install(), Juniper.MasterSceneController.optionsInterface, and Juniper.MasterSceneController.splash.
Exit()
static void Juniper.MasterSceneController.Exit () inline static private
Close the application.
Definition at line 488 of file MasterSceneController.cs.
         {
             if (Application.isPlaying)
             {
 #if UNITY_EDITOR
                 EditorApplication.isPlaying = false;
 #else
                 Application.Quit();
 #endif
             }
         }
Referenced by Juniper.MasterSceneController.QuitApp(), and Juniper.MasterSceneController.QuitCoroutine().
FadeOut()
void Juniper.MasterSceneController.FadeOut (bool skipFadeOut) inline private
Definition at line 176 of file MasterSceneController.cs.
         {
             if (skipFadeOut)
             {
                 darth?.SkipEnter();
             }
             else
             {
                 darth?.Enter();
             }
         }
References Juniper.MasterSceneController.darth, Juniper.Animation.FadeTransition.Enter(), and Juniper.Animation.AbstractTransitionController.SkipEnter().
Referenced by Juniper.MasterSceneController.Start(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
Flatten()
void Juniper.MasterSceneController.Flatten () inline private
Copy all of the root scene objects out of the sub scenes and into the master scene, removing the subscenes along the way. This can also be executed from the editor by accessing the component's context menu and selecting "Flatten".
Definition at line 628 of file MasterSceneController.cs.
         {
             var curScene = gameObject.scene;
             if (subSceneNames.Length > 0)
             {
                 var newPath = curScene.path.Replace(".unity", ".original.unity");
                 FileExt.Copy(curScene.path, newPath, true);
                 foreach (var path in subSceneNames)
                 {
                     var sceneName = SceneNamePattern.Match(path).Groups[1].Value;
                     var scene = SceneManager.GetSceneByPath(path);
                     if (!scene.IsValid())
                     {
                         scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Additive);
                     }
                     SceneManager.MergeScenes(scene, curScene);
                 }
                 subSceneNames = new string[0];
                 EditorSceneManager.SaveScene(curScene);
             }
             EditorBuildSettings.scenes = new[]
             {
                 new EditorBuildSettingsScene(curScene.path, true)
             };
         }
References System.IO.FileExt.Copy(), Juniper.MasterSceneController.SceneNamePattern, and Juniper.MasterSceneController.subSceneNames.
GetScene()
Scene? Juniper.MasterSceneController.GetScene (string sceneName, string path) inline private
Get a scene by name (or path, if we're running in the editor).
Returns
The scene.
Parameters
sceneName Scene name.
path Path.
Definition at line 552 of file MasterSceneController.cs.
         {
             if (IsScenePathLoaded(path))
             {
                 return SceneManager.GetSceneByPath(path);
             }
             else
             {
 #if UNITY_EDITOR
                 if (Application.isPlaying)
                 {
 #endif
                     SceneManager.LoadScene(sceneName, LoadSceneMode.Additive);
                     return SceneManager.GetSceneByPath(path);
 #if UNITY_EDITOR
                 }
                 else
                 {
                     return EditorSceneManager.OpenScene(path, OpenSceneMode.Additive);
                 }
 #endif
             }
         }
References Juniper.MasterSceneController.IsScenePathLoaded().
Referenced by Juniper.MasterSceneController.LoadScenePathCoroutine().
GetSceneNameFromPath()
static string Juniper.MasterSceneController.GetSceneNameFromPath (string path) static private
Referenced by Juniper.MasterSceneController.LoadFirstScene(), and Juniper.MasterSceneController.LoadScenePathCoroutine().
Install()
void Juniper.MasterSceneController.Install (bool reset) inline
Implements Juniper.IInstallable.
Definition at line 266 of file MasterSceneController.cs.
         {
             reset &= Application.isEditor;
 #if UNITY_EDITOR
             if (sceneFaderMaterial == null || reset)
             {
                 sceneFaderMaterial = AssetDatabase.LoadAssetAtPath<Material>(PathExt.FixPath("Assets/Juniper/Materials/FaderMaterial.mat"));
             }
 #endif
             var fader = FadeTransition.Ensure(CameraExtensions.MainCamera.transform);
             if (fader.IsNew || reset)
             {
                 fader.Value.GetComponent<Renderer>().SetMaterial(sceneFaderMaterial);
                 fader.Value.transform.localPosition = Mathf.Max(0.5f, 1.2f * CameraExtensions.MainCamera.nearClipPlane) * Vector3.forward;
                 fader.Value.transform.localScale = 2 * Vector3.one;
             }
             var sys = transform.EnsureTransform("SystemUserInterface");
             if (sys.IsNew)
             {
                 sys.Value.transform.localPosition = 1.5f * Vector3.forward;
                 var follow = sys.EnsureComponent<FollowMainCamera>().Value;
                 follow.followDistance = 1.5f;
             }
             var bar = LoadingBar.Ensure(sys);
             if (bar.IsNew)
             {
                 bar.Value.transform.localPosition = (2f / 3f) * Vector3.down;
                 bar.Value.transform.localScale = new Vector3(1f, 0.1f, 0.1f);
                 loadingBar = bar;
             }
 #if UNITY_MODULES_UI
             var canv = sys.Value.EnsureTransform("Canvas")
                 .Value
                 .EnsureComponent<Canvas>((c) =>
                 {
                     c.renderMode = RenderMode.WorldSpace;
                     c.SetRectangle(Vector3.zero, 0.5f * Vector2.one, 0.5f * Vector2.one, 1000, 1000, 0.5f * Vector2.one)
                         .SetScale(new Vector3(0.001f, 0.001f, 1));
                     var io = ComponentExt.FindAny<UnifiedInputModule>();
                     io?.AddRaycaster(c.GetComponent<GraphicRaycaster>());
                     var debugText = c
                         .EnsureRectTransform("DebugText")
                         .Value
                         .EnsureComponent<Text>((d) =>
{
                             d.gameObject.layer = LayerMask.NameToLayer("TransparentFX");
                             d.raycastTarget = false;
                             d.font = Resources.GetBuiltinResource<Font>("Arial.ttf");
                             d.supportRichText = false;
                             d.alignment = TextAnchor.UpperLeft;
                             d.horizontalOverflow = HorizontalWrapMode.Wrap;
                             d.verticalOverflow = VerticalWrapMode.Truncate;
                             d.color = Color.green;
                             d.fontSize = 50;
                             d.GetComponent<RectTransform>()
                              .SetRectangle(Vector3.zero, Vector2.zero, Vector2.one, Vector2.up);
                         });
                     debugText.Value.EnsureComponent<ScreenDebugger>();
                 });
             canv.Value.EnsureComponent<GraphicRaycaster>();
             if (splash == null)
             {
                 splash = canv
                     .Value
                     .EnsureRectTransform("SplashImage")
                     .Value
                     .EnsureComponent<Image>((splashImg) =>
                     {
 #if UNITY_EDITOR
                         splashImg.sprite = AssetDatabase.LoadAssetAtPath<Sprite>(PathExt.FixPath("Assets/Juniper/Textures/gear.png"));
 #endif
                         splashImg.SetRectangle(Vector3.zero, Vector2.zero, Vector2.one, 0.5f * Vector2.one);
                     });
             }
             if (optionsInterface == null)
             {
                 var opts = canv.Value.EnsureRectTransform("Options");
                 optionsInterface = opts.Value.gameObject;
                 if (opts.IsNew)
                 {
                     opts.SetRectangle(Vector3.zero, Vector2.zero, Vector2.one, 0.5f * Vector2.one);
                     var icon = opts
                         .EnsureRectTransform("Image")
                         .EnsureComponent<Image>().Value;
 #if UNITY_EDITOR
                     icon.sprite = AssetDatabase.LoadAssetAtPath<Sprite>(PathExt.FixPath("Assets/Juniper/Textures/gear.png"));
 #endif
                     icon.SetRectangle(Vector3.zero, Vector2.zero, Vector2.zero, 100, 100, Vector2.zero);
 #if UNITY_TEXTMESHPRO
                     var optionsPanel = opts
                         .EnsureRectTransform("OptionsPanel")
                         .SetRectangle(Vector3.zero, Vector2.zero, Vector2.one, 100, 100, 0.5f * Vector2.one);
                     var toggle = icon.EnsureComponent<Toggle>().Value;
                     toggle.isOn = true;
                     toggle.onValueChanged.AddListener(optionsPanel.SetActive);
                     var volumePanel = optionsPanel
                         .EnsureRectTransform("Volume")
                         .SetRectangle(350 * Vector2.down, 0.5f * Vector2.up, new Vector2(1, 0.5f), optionsPanel.rect.width, 100, 0.5f * Vector2.one);
                     var volumeLabel = volumePanel
                         .EnsureRectTransform("VolumeLabel")
                         .SetRectangle(370 * Vector2.left, 0.5f * Vector2.right, new Vector2(0.5f, 1), 260, volumePanel.rect.height, 0.5f * Vector2.one)
                         .EnsureComponent<TMPro.TextMeshProUGUI>()
                         .Value;
                     volumeLabel.text = "Volume";
                     var volumeSlider = volumePanel
                         .EnsureRectTransform("VolumeSlider")
                         .SetRectangle(new Vector3(533, 40), Vector2.zero, Vector2.one, volumePanel.rect.width - volumeLabel.rectTransform.rect.width, volumePanel.rect.height - 80, 0.5f * Vector2.one)
                         .SetScale(3.5f * Vector3.one)
                         .EnsureComponent<Slider>()
                         .Value;
                     var aud = ComponentExt.FindAny<InteractionAudio>();
                     if (aud != null)
                     {
                         aud.volumeSlider = volumeSlider.gameObject;
                     }
 #endif
                 }
             }
 #endif
         }
References Juniper.Widgets.LoadingBar.Ensure(), Juniper.Animation.FadeTransition.Ensure(), System.IO.PathExt.FixPath(), Juniper.Widgets.FollowMainCamera.followDistance, Juniper.MasterSceneController.loadingBar, Juniper.CameraExtensions.MainCamera, Juniper.MasterSceneController.optionsInterface, Juniper.MasterSceneController.sceneFaderMaterial, Juniper.MasterSceneController.splash, and Juniper.Audio.InteractionAudio.volumeSlider.
Referenced by Juniper.MasterSceneController.Awake().
IsScenePathLoaded()
static bool Juniper.MasterSceneController.IsScenePathLoaded (string path) inline static private
Definition at line 479 of file MasterSceneController.cs.
         {
             var scene = SceneManager.GetSceneByPath(path);
             return scene.IsValid() && scene.isLoaded;
         }
Referenced by Juniper.MasterSceneController.GetScene(), and Juniper.MasterSceneController.LoadScenePathCoroutine().
LoadAllScenes()
void Juniper.MasterSceneController.LoadAllScenes ()
Referenced by Juniper.MasterSceneController.Start().
LoadAllScenesCoroutine()
IEnumerator Juniper.MasterSceneController.LoadAllScenesCoroutine (IProgressReceiver prog = null) inline private
Use this function by right-clicking in the editor to open up all the scenes in additive mode.
Definition at line 442 of file MasterSceneController.cs.
         {
             prog?.SetProgress(0);
             if (subSceneNames?.Length > 0)
             {
                 var split = prog.Split(subSceneNames.Length);
                 for (var i = 0; i < subSceneNames.Length; ++i)
                 {
                     yield return LoadScenePathCoroutine(subSceneNames[i], split[i]);
                 }
             }
             prog?.SetProgress(1);
         }
References Juniper.MasterSceneController.LoadScenePathCoroutine(), and Juniper.MasterSceneController.subSceneNames.
Referenced by Juniper.MasterSceneController.LoadAllScenesCoroutine2(), and Juniper.MasterSceneController.LoadScenes_MenuItem().
LoadAllScenesCoroutine2()
IEnumerator Juniper.MasterSceneController.LoadAllScenesCoroutine2 () inline private
Definition at line 432 of file MasterSceneController.cs.
         {
             loadingBar?.Activate();
             yield return LoadAllScenesCoroutine(loadingBar);
             yield return LoadingCompleteCoroutine();
         }
References Juniper.MasterSceneController.LoadAllScenesCoroutine(), Juniper.MasterSceneController.loadingBar, and Juniper.MasterSceneController.LoadingCompleteCoroutine().
LoadFirstScene()
void Juniper.MasterSceneController.LoadFirstScene () inline private
Definition at line 458 of file MasterSceneController.cs.
         {
             var path = subSceneNames.FirstOrDefault();
             if (string.IsNullOrEmpty(path))
             {
                 throw new InvalidOperationException("[Juniper.MasterSceneController::LoadFirstScene] No subscenes defined.");
             }
             else
             {
                 var name = GetSceneNameFromPath(path);
                 if (string.IsNullOrEmpty(name))
                 {
                     throw new InvalidOperationException("[Juniper.MasterSceneController::LoadFirstScene] Could not find scene " + path);
                 }
                 else
                 {
                     SwitchToSceneName(name, true);
                 }
             }
         }
References Juniper.MasterSceneController.GetSceneNameFromPath(), Juniper.MasterSceneController.subSceneNames, and Juniper.MasterSceneController.SwitchToSceneName().
Referenced by Juniper.MasterSceneController.Start().
LoadingCompleteCoroutine()
IEnumerator Juniper.MasterSceneController.LoadingCompleteCoroutine () inline private
Definition at line 209 of file MasterSceneController.cs.
         {
             loadingBar?.SetProgress(1);
             yield return loadingBar?.Waiter;
             splash?.Deactivate();
             loadingBar?.Deactivate();
             optionsInterface?.Activate();
             darth?.Exit();
             yield return darth?.Waiter;
         }
References Juniper.MasterSceneController.darth, Juniper.Animation.FadeTransition.Exit(), Juniper.MasterSceneController.loadingBar, Juniper.MasterSceneController.optionsInterface, Juniper.Widgets.LoadingBar.SetProgress(), Juniper.MasterSceneController.splash, Juniper.Widgets.LoadingBar.Waiter, and Juniper.AbstractStateController.Waiter.
Referenced by Juniper.MasterSceneController.LoadAllScenesCoroutine2(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
LoadScene()
static IProgress Juniper.MasterSceneController.LoadScene (string scenePath, string sceneName) inline static private
Get a scene by name (or path, if we're running in the editor).
Returns
The scene.
Parameters
sceneName Scene name.
path Path.
Definition at line 60 of file MasterSceneController.cs.
         {
             if (Application.isPlaying)
             {
                 var op = SceneManager.LoadSceneAsync(sceneName, LoadSceneMode.Additive);
                 if (op != null)
                 {
                     return new UnityAsyncOperationProgress(op);
                 }
             }
 #if UNITY_EDITOR
             else
             {
                 EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Additive);
             }
 #endif
             return StaticProgress.COMPLETE;
         }
References Juniper.Progress.StaticProgress.COMPLETE.
Referenced by Juniper.MasterSceneController.LoadScenePathCoroutine().
LoadScenePathCoroutine()
IEnumerator Juniper.MasterSceneController.LoadScenePathCoroutine (string path, IProgressReceiver prog) inline private
Definition at line 576 of file MasterSceneController.cs.
         {
             prog?.SetProgress(0);
             var sceneName = GetSceneNameFromPath(path);
             var split = prog.Split(2);
             var sceneLoadProg = split[0];
             var subSceneLoadProg = split[1];
             if (IsScenePathLoaded(path))
             {
                 sceneLoadProg?.SetProgress(1);
                 yield return sceneName + " already loaded.";
             }
             else
             {
                 var op = LoadScene(path, sceneName);
                 while (!op.IsComplete())
                 {
                     sceneLoadProg?.SetProgress(op.Progress);
                     yield return sceneName + " " + (prog?.Progress)?.ToString("P1") ?? "N/A";
                 }
             }
             Scene? scene = null;
             while (scene == null)
             {
                 scene = GetScene(sceneName, path);
                 yield return sceneName + " " + (prog?.Progress)?.ToString("P1") ?? "N/A";
             }
             var toLoad = from root in scene.Value.GetRootGameObjects()
                          from subScene in root.GetComponentsInChildren<SubSceneController>(true)
                          select subScene;
             subSceneLoadProg.ForEach(toLoad, (ss, p) => ss.Load(p), Debug.LogException);
             while (prog?.IsComplete() == false)
             {
                 yield return sceneName + " " + (prog?.Progress)?.ToString("P1") ?? "N/A";
             }
         }
References Juniper.MasterSceneController.GetScene(), Juniper.MasterSceneController.GetSceneNameFromPath(), Juniper.MasterSceneController.IsScenePathLoaded(), Juniper.MasterSceneController.LoadScene(), Juniper.Progress.IProgress.Progress, and Juniper.Progress.IProgressReceiver.SetProgress().
Referenced by Juniper.MasterSceneController.LoadAllScenesCoroutine(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
LoadScenes_MenuItem()
void Juniper.MasterSceneController.LoadScenes_MenuItem () inline private
Use this function by right-clicking in the editor to open up all the scenes in additive mode.
Definition at line 506 of file MasterSceneController.cs.
         {
             var iter = LoadAllScenesCoroutine(new UnityEditorProgressDialog("Loading scenes"));
             while (iter.MoveNext())
             {
                 var obj = iter.Current;
                 if (obj is IEnumerator)
                 {
                     var subIter = (IEnumerator)obj;
                     while (subIter?.MoveNext() == true)
                     {
                         print(subIter.Current);
                     }
                 }
                 else
                 {
                     print(obj);
                 }
             }
             EditorUtility.ClearProgressBar();
         }
References Juniper.MasterSceneController.LoadAllScenesCoroutine().
OnValidate()
void Juniper.MasterSceneController.OnValidate ()
Quit()
void Juniper.MasterSceneController.Quit ()
Quit out of the application, making sure any exit transitions for the current scene are ran first.
QuitApp()
static void Juniper.MasterSceneController.QuitApp () inline static
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Definition at line 41 of file MasterSceneController.cs.
         {
             var master = ComponentExt.FindAny<MasterSceneController>();
             if (master == null)
             {
                 Exit();
             }
             else
             {
                 master.Quit();
             }
         }
References Juniper.MasterSceneController.Exit().
Referenced by Juniper.MasterSceneController.Update(), and Juniper.CameraExtensions.Update().
QuitCoroutine()
IEnumerator Juniper.MasterSceneController.QuitCoroutine () inline private
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Definition at line 664 of file MasterSceneController.cs.
         {
             foreach (var subScene in CurrentSubScenes)
             {
                 subScene.Exit();
             }
             yield return new WaitUntil(() =>
                 CurrentSubScenes.All(subScene =>
                     subScene.IsComplete));
             if (darth != null)
             {
                 darth.Enter();
                 yield return darth.Waiter;
             }
             Exit();
         }
References Juniper.MasterSceneController.CurrentSubScenes, Juniper.MasterSceneController.darth, Juniper.Animation.FadeTransition.Enter(), Juniper.MasterSceneController.Exit(), and Juniper.AbstractStateController.Waiter.
Reinstall()
virtual void Juniper.MasterSceneController.Reinstall () virtual
Implements Juniper.IInstallable.
Reset()
void Juniper.MasterSceneController.Reset ()
SetBuildSettings()
void Juniper.MasterSceneController.SetBuildSettings () inline private
Definition at line 532 of file MasterSceneController.cs.
         {
             if (!Application.isPlaying && !string.IsNullOrEmpty(gameObject?.scene.path))
             {
                 EditorBuildSettings.scenes = (from path in subSceneNames
                                               where File.Exists(path)
                                               select new EditorBuildSettingsScene(path, true))
                    .Prepend(new EditorBuildSettingsScene(gameObject.scene.path, true))
                    .ToArray();
             }
         }
References Juniper.MasterSceneController.subSceneNames.
Start()
virtual void Juniper.MasterSceneController.Start () inline protected virtual
Wait until the Start method to load the scenes so the MasterSceneController or any child class of it can be found by the newly loaded scenes more reliably.
Definition at line 415 of file MasterSceneController.cs.
         {
             FadeOut(true);
             if (loadAll)
             {
                 Invoke(nameof(LoadAllScenes), 0.5f);
             }
             else
             {
                 Invoke(nameof(LoadFirstScene), 0.5f);
             }
         }
References Juniper.MasterSceneController.FadeOut(), Juniper.MasterSceneController.loadAll, Juniper.MasterSceneController.LoadAllScenes(), and Juniper.MasterSceneController.LoadFirstScene().
SwitchToSceneName()
void Juniper.MasterSceneController.SwitchToSceneName (string sceneName, bool skipFadeOut = false)
A subscene is a root game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
Parameters
sceneName
Returns
Referenced by Juniper.MasterSceneController.LoadFirstScene().
SwitchToSceneNameCoroutine()
IEnumerator Juniper.MasterSceneController.SwitchToSceneNameCoroutine (string subSceneName, bool skipFadeOut = false) inline private
Definition at line 188 of file MasterSceneController.cs.
         {
             loadingBar?.Activate();
             loadingBar?.SetProgress(0);
             if (!skipFadeOut)
             {
                 FadeOut(skipFadeOut);
                 yield return darth?.Waiter;
             }
             var split = loadingBar?.Split(2);
             var parts = subSceneName.Split('.');
             var sceneName = parts[0];
             var sceneFileName = sceneName + ".unity";
             var scenePath = Array.Find(subSceneNames, s => s.EndsWith(sceneFileName));
             yield return LoadScenePathCoroutine(scenePath, split[0]);
             yield return LoadingCompleteCoroutine();
         }
References Juniper.MasterSceneController.darth, Juniper.MasterSceneController.FadeOut(), Juniper.MasterSceneController.loadingBar, Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.MasterSceneController.LoadScenePathCoroutine(), Juniper.Widgets.LoadingBar.SetProgress(), Juniper.MasterSceneController.subSceneNames, and Juniper.AbstractStateController.Waiter.
Uninstall()
void Juniper.MasterSceneController.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 409 of file MasterSceneController.cs.
 { }
Update()
void Juniper.MasterSceneController.Update () inline
Definition at line 154 of file MasterSceneController.cs.
         {
             if (exitOnEscape && !wasLocked && UnityEngine.Input.GetKeyDown(KeyCode.Escape))
             {
                 QuitApp();
             }
             wasLocked = Cursor.lockState != CursorLockMode.None;
         }
References Juniper.MasterSceneController.exitOnEscape, Juniper.MasterSceneController.QuitApp(), and Juniper.MasterSceneController.wasLocked.
Member Data Documentation
CurrentSubScenes
SubSceneController [] Juniper.MasterSceneController.CurrentSubScenes
Initial value:
=>
            (from scene in SubScenes
             where scene.isActiveAndEnabled
             select scene)
                .ToArray()
All of the active SubSceneControllers
The current sub scenes.
Definition at line 148 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.QuitCoroutine().
darth
FadeTransition Juniper.MasterSceneController.darth private
Definition at line 115 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Awake(), Juniper.MasterSceneController.FadeOut(), Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
exitOnEscape
bool Juniper.MasterSceneController.exitOnEscape = true
Definition at line 96 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Update().
loadAll
bool Juniper.MasterSceneController.loadAll = true
Definition at line 94 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Start().
loadingBar
LoadingBar Juniper.MasterSceneController.loadingBar
Definition at line 82 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Install(), Juniper.MasterSceneController.LoadAllScenesCoroutine2(), Juniper.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
optionsInterface
GameObject Juniper.MasterSceneController.optionsInterface
Definition at line 86 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Awake(), Juniper.MasterSceneController.Install(), and Juniper.MasterSceneController.LoadingCompleteCoroutine().
sceneFaderMaterial
Material Juniper.MasterSceneController.sceneFaderMaterial
The material to apply to Darth Fader.
Definition at line 92 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Install().
SceneNamePattern
readonly Regex Juniper.MasterSceneController.SceneNamePattern = new Regex(SceneNamePatternStr, RegexOptions.Compiled) static private
Parse the scene name.
Definition at line 113 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Flatten().
SceneNamePatternStr
const string Juniper.MasterSceneController.SceneNamePatternStr = "([^/]+)\\.unity$" private
Parse the scene name.
Definition at line 108 of file MasterSceneController.cs.
splash
Image Juniper.MasterSceneController.splash
Definition at line 84 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Awake(), Juniper.MasterSceneController.Install(), and Juniper.MasterSceneController.LoadingCompleteCoroutine().
subSceneNames
string [] Juniper.MasterSceneController.subSceneNames
All of the scene files to load. Use the "truncated scene path" format for these paths. Truncated scene paths do not need to reference the "Assets/" (it is assumed) and do not need the ".unity" file extension.
Definition at line 103 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Flatten(), Juniper.MasterSceneController.LoadAllScenesCoroutine(), Juniper.MasterSceneController.LoadFirstScene(), Juniper.MasterSceneController.SetBuildSettings(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
SubScenes
IEnumerable<SubSceneController> Juniper.MasterSceneController.SubScenes
Initial value:
=>
            ComponentExt.FindAll<SubSceneController>()
All of the SubSceneController references in the project.
The sub scenes.
Definition at line 141 of file MasterSceneController.cs.
wasLocked
bool Juniper.MasterSceneController.wasLocked private
A flag that indicates the cursor was locked on the previous frame.
Definition at line 120 of file MasterSceneController.cs.
Referenced by Juniper.MasterSceneController.Update().
Property Documentation
AllScenes
IEnumerable<Scene> Juniper.MasterSceneController.AllScenes static get
Get all of the scenes defined in the Build settings.
All scenes.
Definition at line 127 of file MasterSceneController.cs.
         {
             get
             {
                 for (var i = 0; i < SceneManager.sceneCount; ++i)
                 {
                     yield return SceneManager.GetSceneAt(i);
                 }
             }
         }
Referenced by UnityEngine.RectTransformExt.Query< T >(), and UnityEngine.TransformExt.Query< T >().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/MasterSceneController.cs