Juniper: Juniper.Wait Class Reference
Juniper.Wait Class Reference
Static Public Member Functions
static IEnumerator Until (DateTime end)
static IEnumerator Minutes (float minutes)
static IEnumerator Seconds (float seconds)
static IEnumerator Milliseconds (float milliseconds)
Detailed Description
Definition at line 6 of file Wait.cs.
Member Function Documentation
Milliseconds()
static IEnumerator Juniper.Wait.Milliseconds (float milliseconds) inline static
Definition at line 26 of file Wait.cs.
         {
             return Until(DateTime.Now.AddMilliseconds(milliseconds));
         }
References Juniper.Wait.Until().
Minutes()
static IEnumerator Juniper.Wait.Minutes (float minutes) inline static
Definition at line 16 of file Wait.cs.
         {
             return Until(DateTime.Now.AddMinutes(minutes));
         }
References Juniper.Wait.Until().
Seconds()
static IEnumerator Juniper.Wait.Seconds (float seconds) inline static
Definition at line 21 of file Wait.cs.
         {
             return Until(DateTime.Now.AddSeconds(seconds));
         }
References Juniper.Wait.Until().
Referenced by Juniper.Animation.UnityAnimator.PlayCoroutine().
Until()
static IEnumerator Juniper.Wait.Until (DateTime end) inline static
Definition at line 8 of file Wait.cs.
         {
             while (DateTime.Now < end)
             {
                 yield return null;
             }
         }
Referenced by Juniper.Wait.Milliseconds(), Juniper.Wait.Minutes(), and Juniper.Wait.Seconds().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Wait.cs