Juniper: Juniper.Imaging.PhotosphereManager Class Reference
Juniper.Imaging.PhotosphereManager Class Reference
Public Member Functions
void SetDetailLevels (float[] fovs)
T GetPhotosphere< T > (string key)
void RemovePhotosphere (string key)
void SetIO (CachingStrategy cache, IImageCodec< Texture2D > codec)
Properties
int Count [get]
Events
TextureNeeded CubemapNeeded
CubemapRotationNeeded RotationNeeded
Action< Photosphere > PhotosphereReady
Private Member Functions
bool Photo_CheckIsCubemapAvailable (Photosphere source)
Texture2D Photo_CubemapNeeded (Photosphere source)
void Photo_Ready (Photosphere obj)
void CreatePhotosphere< T > (string key)
void Initialize< T > (T photo)
float Photo_GetRotation (Photosphere source)
Static Private Member Functions
static Vector2 [] MakeTestAngles (float fov, bool allAngles)
Private Attributes
internal int [] FOVs
internal Vector2 [][] fovTestAngles
internal int [] lodLevelRequirements
readonly Dictionary< string, Photosphere > photospheres = new Dictionary<string, Photosphere>()
Photosphere curSphere
CachingStrategy cache
IImageCodec< Texture2D > codec
Detailed Description
Definition at line 11 of file PhotosphereManager.cs.
Member Function Documentation
CreatePhotosphere< T >()
void Juniper.Imaging.PhotosphereManager.CreatePhotosphere< T > (string key) inline private
Type Constraints
T : Photosphere
Definition at line 112 of file PhotosphereManager.cs.
                     : Photosphere
         {
             var photoGo = new GameObject(key);
             photoGo.Deactivate();
             photoGo.transform.SetParent(transform, true);
             var photo = photoGo.Ensure<T>().Value;
             photo.CubemapName = key;
             Initialize(photo);
         }
Referenced by Juniper.Imaging.PhotosphereManager.GetPhotosphere< T >().
GetPhotosphere< T >()
T Juniper.Imaging.PhotosphereManager.GetPhotosphere< T > (string key) inline
Type Constraints
T : Photosphere
Definition at line 81 of file PhotosphereManager.cs.
                     : Photosphere
         {
             if (curSphere == null || curSphere.CubemapName != key)
             {
                 if (!photospheres.ContainsKey(key))
                 {
                     CreatePhotosphere<T>(key);
                 }
                 curSphere = photospheres[key];
             }
             return (T)curSphere;
         }
References Juniper.Imaging.PhotosphereManager.CreatePhotosphere< T >(), Juniper.Imaging.Photosphere.CubemapName, Juniper.Imaging.PhotosphereManager.curSphere, and Juniper.Imaging.PhotosphereManager.photospheres.
Initialize< T >()
void Juniper.Imaging.PhotosphereManager.Initialize< T > (T photo) inline private
Type Constraints
T : Photosphere
Definition at line 149 of file PhotosphereManager.cs.
                     : Photosphere
         {
             if (!photospheres.ContainsKey(photo.CubemapName))
             {
                 photo.enabled = false;
                 photo.Ready += Photo_Ready;
                 photo.GetCubemap += Photo_CubemapNeeded;
                 photo.CheckIsCubemapAvailable += Photo_CheckIsCubemapAvailable;
                 photo.GetRotation += Photo_GetRotation;
 #if UNITY_EDITOR
                 photo.SetRotation += Photo_SetRotation;
                 photo.SetPosition += Photo_SetPosition;
 #endif
                 photospheres.Add(photo.CubemapName, photo);
             }
         }
References Juniper.Imaging.PhotosphereManager.Photo_CheckIsCubemapAvailable(), Juniper.Imaging.PhotosphereManager.Photo_CubemapNeeded(), Juniper.Imaging.PhotosphereManager.Photo_GetRotation(), Juniper.Imaging.PhotosphereManager.Photo_Ready(), Juniper.Imaging.PhotosphereManager.photospheres, and Juniper.Imaging.Photosphere.Ready.
MakeTestAngles()
static Vector2 [] Juniper.Imaging.PhotosphereManager.MakeTestAngles (float fov, bool allAngles) inline static private
Definition at line 13 of file PhotosphereManager.cs.
         {
             var list = new List<Vector2>();
             for (var ay = -180f; ay < 180; ay += fov)
             {
                 for (var ax = -90f; ax <= 90f; ax += fov)
                 {
                     if (Mathf.Abs(ax) != 90 || ay == 0 || allAngles)
                     {
                         list.Add(new Vector2(ay, ax));
                     }
                 }
             }
             return list
                 .Distinct()
                 .OrderBy(x => x.magnitude)
                 .ToArray();
         }
Referenced by Juniper.Imaging.PhotosphereManager.SetDetailLevels().
Photo_CheckIsCubemapAvailable()
bool Juniper.Imaging.PhotosphereManager.Photo_CheckIsCubemapAvailable (Photosphere source) inline private
Definition at line 97 of file PhotosphereManager.cs.
         {
             return cache.IsCached(source.CubemapName + codec.ContentType);
         }
References Juniper.Imaging.PhotosphereManager.cache, Juniper.Imaging.PhotosphereManager.codec, Juniper.Imaging.Photosphere.CubemapName, and Juniper.IO.CachingStrategy.IsCached().
Referenced by Juniper.Imaging.PhotosphereManager.Initialize< T >().
Photo_CubemapNeeded()
Texture2D Juniper.Imaging.PhotosphereManager.Photo_CubemapNeeded (Photosphere source) inline private
Definition at line 102 of file PhotosphereManager.cs.
         {
             return CubemapNeeded?.Invoke(source);
         }
References Juniper.Imaging.PhotosphereManager.CubemapNeeded.
Referenced by Juniper.Imaging.PhotosphereManager.Initialize< T >().
Photo_GetRotation()
float Juniper.Imaging.PhotosphereManager.Photo_GetRotation (Photosphere source) inline private
Definition at line 180 of file PhotosphereManager.cs.
         {
             return RotationNeeded?.Invoke(source) ?? 0;
         }
References Juniper.Imaging.PhotosphereManager.RotationNeeded.
Referenced by Juniper.Imaging.PhotosphereManager.Initialize< T >().
Photo_Ready()
void Juniper.Imaging.PhotosphereManager.Photo_Ready (Photosphere obj) inline private
Definition at line 107 of file PhotosphereManager.cs.
         {
             PhotosphereReady?.Invoke(obj);
         }
References Juniper.Imaging.PhotosphereManager.PhotosphereReady.
Referenced by Juniper.Imaging.PhotosphereManager.Initialize< T >().
RemovePhotosphere()
void Juniper.Imaging.PhotosphereManager.RemovePhotosphere (string key) inline
Definition at line 124 of file PhotosphereManager.cs.
         {
             var sphere = transform.Find(key);
             if (sphere != null)
             {
                 if (photospheres.ContainsKey(key))
                 {
                     photospheres.Remove(key);
                 }
                 sphere.gameObject.DestroyImmediate();
             }
         }
References Juniper.Imaging.PhotosphereManager.photospheres.
SetDetailLevels()
void Juniper.Imaging.PhotosphereManager.SetDetailLevels (float [] fovs) inline
Definition at line 56 of file PhotosphereManager.cs.
         {
             FOVs = new int[fovs.Length];
             fovTestAngles = new Vector2[fovs.Length][];
             var requiredAngles = new Vector2[fovs.Length][];
             for (int f = 0; f < fovs.Length; ++f)
             {
                 FOVs[f] = (int)fovs[f];
                 fovTestAngles[f] = MakeTestAngles(fovs[f], true);
                 requiredAngles[f] = MakeTestAngles(fovs[f], false);
             }
             lodLevelRequirements = requiredAngles
                 .Select(a => a.Length)
                 .ToArray();
         }
References Juniper.Imaging.PhotosphereManager.FOVs, Juniper.Imaging.PhotosphereManager.fovTestAngles, Juniper.Imaging.PhotosphereManager.lodLevelRequirements, and Juniper.Imaging.PhotosphereManager.MakeTestAngles().
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
SetIO()
void Juniper.Imaging.PhotosphereManager.SetIO (CachingStrategy cache, IImageCodec< Texture2D > codec) inline
Definition at line 137 of file PhotosphereManager.cs.
         {
             this.cache = cache;
             this.codec = codec;
             var existing = GetComponentsInChildren<Photosphere>();
             foreach (var photo in existing)
             {
                 photo.Deactivate();
                 Initialize(photo);
             }
         }
References Juniper.Imaging.PhotosphereManager.cache, and Juniper.Imaging.PhotosphereManager.codec.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
Member Data Documentation
cache
CachingStrategy Juniper.Imaging.PhotosphereManager.cache private
Definition at line 53 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereManager.Photo_CheckIsCubemapAvailable(), and Juniper.Imaging.PhotosphereManager.SetIO().
codec
IImageCodec<Texture2D> Juniper.Imaging.PhotosphereManager.codec private
Definition at line 54 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereManager.Photo_CheckIsCubemapAvailable(), and Juniper.Imaging.PhotosphereManager.SetIO().
curSphere
Photosphere Juniper.Imaging.PhotosphereManager.curSphere private
Definition at line 40 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereManager.GetPhotosphere< T >().
FOVs
internal int [] Juniper.Imaging.PhotosphereManager.FOVs private
Definition at line 34 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereJig.DetailLevelCompleteCount(), Juniper.Imaging.PhotosphereManager.SetDetailLevels(), Juniper.Imaging.PhotosphereJig.Update(), and Juniper.Imaging.PhotosphereJig.UpdatePhotosphere().
fovTestAngles
internal Vector2 [][] Juniper.Imaging.PhotosphereManager.fovTestAngles private
Definition at line 35 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereManager.SetDetailLevels(), and Juniper.Imaging.PhotosphereJig.UpdatePhotosphere().
lodLevelRequirements
internal int [] Juniper.Imaging.PhotosphereManager.lodLevelRequirements private
Definition at line 36 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereJig.DetailLevelCompleteCount(), Juniper.Imaging.PhotosphereManager.SetDetailLevels(), and Juniper.Imaging.PhotosphereJig.Update().
photospheres
readonly Dictionary<string, Photosphere> Juniper.Imaging.PhotosphereManager.photospheres = new Dictionary<string, Photosphere>() private
Definition at line 38 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereManager.GetPhotosphere< T >(), Juniper.Imaging.PhotosphereManager.Initialize< T >(), and Juniper.Imaging.PhotosphereManager.RemovePhotosphere().
Property Documentation
Count
int Juniper.Imaging.PhotosphereManager.Count get
Definition at line 74 of file PhotosphereManager.cs.
         {
             get
             {
                 return photospheres.Count;
             }
         }
Event Documentation
CubemapNeeded
TextureNeeded Juniper.Imaging.PhotosphereManager.CubemapNeeded
Definition at line 42 of file PhotosphereManager.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), and Juniper.Imaging.PhotosphereManager.Photo_CubemapNeeded().
PhotosphereReady
Action<Photosphere> Juniper.Imaging.PhotosphereManager.PhotosphereReady
Definition at line 51 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereManager.Photo_Ready().
RotationNeeded
CubemapRotationNeeded Juniper.Imaging.PhotosphereManager.RotationNeeded
Definition at line 44 of file PhotosphereManager.cs.
Referenced by Juniper.Imaging.PhotosphereManager.Photo_GetRotation().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Imaging/PhotosphereManager.cs