Juniper: Juniper.ConfigurationManagement.Project Class Reference
Juniper.ConfigurationManagement.Project Class Reference
Static Public Member Functions
static bool IsAvailable (PackageReference pkg)
static bool IsInstalled (PackageReference pkg)
static List< string > CleanupDefines (IEnumerable< string > defs)
static List< string > GetDefines (BuildTargetGroup targetGroup)
static void AddCompilerDefine (string compilerDefine)
static void RemoveCompilerDefine (string compilerDefine)
static void Recompile ()
static List< string > GetDefines ()
static void SetDefines (BuildTargetGroup targetGroup, List< string > nextDefines, bool forceRecompile)
static void SetDefines (BuildTargetGroup targetGroup, List< string > nextDefines)
static void SetDefines (List< string > nextDefines, bool forceRecompile)
static void SetDefines (List< string > nextDefines)
Static Public Attributes
static string UnityAssetsPath => Path.Combine(UnityProjectRoot, "Assets")
static string PluginsPath => Path.Combine(UnityProjectRoot, "Plugins")
static string JuniperAssetStoreCachePath => Path.Combine(UnityProjectRoot, "AssetStore")
static string JuniperAssetPath => Path.Combine(UnityAssetsPath, "Juniper")
static string JuniperPlatformsFileName => Path.Combine(JuniperAssetPath, "platforms.json")
static string JuniperDefinesFileName => Path.Combine(JuniperAssetPath, "defines.json")
static readonly string AppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
static readonly string UserProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)
static readonly string UserDownloads = Path.Combine(UserProfile, "Downloads")
static readonly string AssetStoreRoot = Path.Combine(AppData, "Unity", "Asset Store-5.x")
static readonly string UserAssetStoreRoot = Path.Combine(UserProfile, "Projects", "Packages")
static BuildTargetGroup CurrentBuildTargetGroup
Properties
static IReadOnlyDictionary< string, IReadOnlyCollection< AbstractPackage > > PackageDatabase [get]
static string UnityProjectRoot [get, set]
static string UnityEditorRoot [get]
Private Attributes
const string RECOMPILE_SLUG = "RECOMPILE_SLUG"
Static Private Attributes
static string unityProjectDirectoryName
static IReadOnlyDictionary< string, IReadOnlyCollection< AbstractPackage > > packageDB
static string unityEditorDirectoryName
Detailed Description
Definition at line 11 of file Project.cs.
Member Function Documentation
AddCompilerDefine()
static void Juniper.ConfigurationManagement.Project.AddCompilerDefine (string compilerDefine) inline static
Definition at line 154 of file Project.cs.
         {
             var defines = GetDefines();
             defines.Add(compilerDefine);
             SetDefines(defines);
         }
References Juniper.ConfigurationManagement.Project.GetDefines(), and Juniper.ConfigurationManagement.Project.SetDefines().
Referenced by Juniper.ConfigurationManagement.AbstractPackage.Activate(), and Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI().
CleanupDefines()
static List<string> Juniper.ConfigurationManagement.Project.CleanupDefines (IEnumerable< string > defs) inline static
Definition at line 129 of file Project.cs.
         {
             var defines = defs.Distinct().ToList();
             defines.RemoveAll(string.IsNullOrWhiteSpace);
             defines.Sort();
             // move the slug to the end, if it exists
             if (defines.Contains(RECOMPILE_SLUG))
             {
                 defines.Remove(RECOMPILE_SLUG);
                 defines.Add(RECOMPILE_SLUG);
             }
             return defines;
         }
References Juniper.ConfigurationManagement.Project.RECOMPILE_SLUG.
Referenced by Juniper.ConfigurationManagement.Project.GetDefines(), and Juniper.ConfigurationManagement.Project.SetDefines().
GetDefines() [1/2]
static List<string> Juniper.ConfigurationManagement.Project.GetDefines (BuildTargetGroup targetGroup) inline static
Definition at line 145 of file Project.cs.
         {
             var defString = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);
             var defArray = defString.SplitX(';');
             var defines = CleanupDefines(defArray);
             defines.Remove(RECOMPILE_SLUG);
             return defines;
         }
References Juniper.ConfigurationManagement.Project.CleanupDefines(), and Juniper.ConfigurationManagement.Project.RECOMPILE_SLUG.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.ConfigurationManagement.PlatformConfiguration.IsActivated(), Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI(), and Juniper.ConfigurationManagement.JuniperInstalledPackageManager.OnGUI().
GetDefines() [2/2]
static List<string> Juniper.ConfigurationManagement.Project.GetDefines () inline static
Definition at line 185 of file Project.cs.
         {
             return GetDefines(CurrentBuildTargetGroup);
         }
References Juniper.ConfigurationManagement.Project.CurrentBuildTargetGroup.
Referenced by Juniper.ConfigurationManagement.Project.AddCompilerDefine(), Juniper.ConfigurationManagement.Project.Recompile(), Juniper.ConfigurationManagement.Project.RemoveCompilerDefine(), and Juniper.ConfigurationManagement.Project.SetDefines().
IsAvailable()
static bool Juniper.ConfigurationManagement.Project.IsAvailable (PackageReference pkg) inline static
Definition at line 32 of file Project.cs.
         {
             if (pkg is null)
             {
                 throw new ArgumentNullException(nameof(pkg));
             }
             if (pkg is AbstractPackage p)
             {
                 return p.Available;
             }
             else
             {
                 return PackageDatabase.ContainsKey(pkg.PackageID)
                      && PackageDatabase[pkg.PackageID].Any(pkg.Equals);
             }
         }
References Juniper.ConfigurationManagement.PackageReference.Equals(), Juniper.ConfigurationManagement.Project.PackageDatabase, and Juniper.ConfigurationManagement.PackageReference.PackageID.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages(), and Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages().
IsInstalled()
static bool Juniper.ConfigurationManagement.Project.IsInstalled (PackageReference pkg) inline static
Definition at line 50 of file Project.cs.
         {
             if (pkg is null)
             {
                 throw new ArgumentNullException(nameof(pkg));
             }
             if (pkg is AbstractPackage p)
             {
                 return p.IsInstalled;
             }
             else
             {
                 return PackageDatabase.ContainsKey(pkg.PackageID)
                      && PackageDatabase[pkg.PackageID].Any(p => p.IsInstalled);
             }
         }
References Juniper.ConfigurationManagement.Project.PackageDatabase, and Juniper.ConfigurationManagement.PackageReference.PackageID.
Referenced by Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages(), and Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages().
Recompile()
static void Juniper.ConfigurationManagement.Project.Recompile () inline static
Definition at line 168 of file Project.cs.
         {
             var defines = GetDefines();
             if(defines.Contains(RECOMPILE_SLUG))
             {
                 defines.Remove(RECOMPILE_SLUG);
             }
             else
             {
                 defines.Add(RECOMPILE_SLUG);
             }
             SetDefines(defines);
         }
References Juniper.ConfigurationManagement.Project.GetDefines(), Juniper.ConfigurationManagement.Project.RECOMPILE_SLUG, and Juniper.ConfigurationManagement.Project.SetDefines().
RemoveCompilerDefine()
static void Juniper.ConfigurationManagement.Project.RemoveCompilerDefine (string compilerDefine) inline static
Definition at line 161 of file Project.cs.
         {
             var defines = GetDefines();
             defines.Remove(compilerDefine);
             SetDefines(defines);
         }
References Juniper.ConfigurationManagement.Project.GetDefines(), and Juniper.ConfigurationManagement.Project.SetDefines().
Referenced by Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI().
SetDefines() [1/4]
static void Juniper.ConfigurationManagement.Project.SetDefines (BuildTargetGroup targetGroup, List< string > nextDefines, bool forceRecompile) inline static
Definition at line 190 of file Project.cs.
         {
             nextDefines = CleanupDefines(nextDefines);
             var currentDefines = GetDefines(targetGroup);
             if (nextDefines.Matches(currentDefines) && forceRecompile)
             {
                 if (nextDefines.Contains(RECOMPILE_SLUG))
                 {
                     nextDefines.Remove(RECOMPILE_SLUG);
                 }
                 else
                 {
                     nextDefines.Add(RECOMPILE_SLUG);
                 }
             }
             if (!nextDefines.Matches(currentDefines))
             {
                 var defString = string.Join(";", nextDefines);
                 PlayerSettings.SetScriptingDefineSymbolsForGroup(targetGroup, defString);
             }
         }
References Juniper.ConfigurationManagement.Project.CleanupDefines(), Juniper.ConfigurationManagement.Project.GetDefines(), and Juniper.ConfigurationManagement.Project.RECOMPILE_SLUG.
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.ConfigurationManagement.Project.AddCompilerDefine(), Juniper.ConfigurationManagement.Project.Recompile(), Juniper.ConfigurationManagement.Project.RemoveCompilerDefine(), and Juniper.ConfigurationManagement.Project.SetDefines().
SetDefines() [2/4]
static void Juniper.ConfigurationManagement.Project.SetDefines (BuildTargetGroup targetGroup, List< string > nextDefines) inline static
Definition at line 213 of file Project.cs.
         {
             SetDefines(targetGroup, nextDefines, false);
         }
References Juniper.ConfigurationManagement.Project.SetDefines().
SetDefines() [3/4]
static void Juniper.ConfigurationManagement.Project.SetDefines (List< string > nextDefines, bool forceRecompile) inline static
Definition at line 218 of file Project.cs.
         {
             SetDefines(CurrentBuildTargetGroup, nextDefines, forceRecompile);
         }
References Juniper.ConfigurationManagement.Project.CurrentBuildTargetGroup, and Juniper.ConfigurationManagement.Project.SetDefines().
SetDefines() [4/4]
static void Juniper.ConfigurationManagement.Project.SetDefines (List< string > nextDefines) inline static
Definition at line 223 of file Project.cs.
         {
             SetDefines(nextDefines, false);
         }
References Juniper.ConfigurationManagement.Project.SetDefines().
Member Data Documentation
AppData
readonly string Juniper.ConfigurationManagement.Project.AppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) static
Definition at line 119 of file Project.cs.
AssetStoreRoot
readonly string Juniper.ConfigurationManagement.Project.AssetStoreRoot = Path.Combine(AppData, "Unity", "Asset Store-5.x") static
Definition at line 125 of file Project.cs.
Referenced by Juniper.ConfigurationManagement.AssetStorePackage.Load().
CurrentBuildTargetGroup
BuildTargetGroup Juniper.ConfigurationManagement.Project.CurrentBuildTargetGroup static
Initial value:
=>
            BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget)
Definition at line 182 of file Project.cs.
Referenced by Juniper.ConfigurationManagement.JuniperPackage.Activate(), Juniper.ConfigurationManagement.Project.GetDefines(), and Juniper.ConfigurationManagement.Project.SetDefines().
JuniperAssetPath
string Juniper.ConfigurationManagement.Project.JuniperAssetPath => Path.Combine(UnityAssetsPath, "Juniper") static
Definition at line 113 of file Project.cs.
JuniperAssetStoreCachePath
string Juniper.ConfigurationManagement.Project.JuniperAssetStoreCachePath => Path.Combine(UnityProjectRoot, "AssetStore") static
Definition at line 111 of file Project.cs.
Referenced by Juniper.ConfigurationManagement.JuniperPackage.Load().
JuniperDefinesFileName
string Juniper.ConfigurationManagement.Project.JuniperDefinesFileName => Path.Combine(JuniperAssetPath, "defines.json") static
Definition at line 117 of file Project.cs.
JuniperPlatformsFileName
string Juniper.ConfigurationManagement.Project.JuniperPlatformsFileName => Path.Combine(JuniperAssetPath, "platforms.json") static
Definition at line 115 of file Project.cs.
Referenced by Juniper.ConfigurationManagement.Platforms.Load().
packageDB
IReadOnlyDictionary<string, IReadOnlyCollection<AbstractPackage> > Juniper.ConfigurationManagement.Project.packageDB static private
Definition at line 17 of file Project.cs.
PluginsPath
string Juniper.ConfigurationManagement.Project.PluginsPath => Path.Combine(UnityProjectRoot, "Plugins") static
Definition at line 109 of file Project.cs.
RECOMPILE_SLUG
const string Juniper.ConfigurationManagement.Project.RECOMPILE_SLUG = "RECOMPILE_SLUG" private
Definition at line 13 of file Project.cs.
Referenced by Juniper.ConfigurationManagement.Project.CleanupDefines(), Juniper.ConfigurationManagement.Project.GetDefines(), Juniper.ConfigurationManagement.Project.Recompile(), and Juniper.ConfigurationManagement.Project.SetDefines().
UnityAssetsPath
string Juniper.ConfigurationManagement.Project.UnityAssetsPath => Path.Combine(UnityProjectRoot, "Assets") static
Definition at line 107 of file Project.cs.
unityEditorDirectoryName
string Juniper.ConfigurationManagement.Project.unityEditorDirectoryName static private
Definition at line 85 of file Project.cs.
unityProjectDirectoryName
string Juniper.ConfigurationManagement.Project.unityProjectDirectoryName static private
Definition at line 15 of file Project.cs.
UserAssetStoreRoot
readonly string Juniper.ConfigurationManagement.Project.UserAssetStoreRoot = Path.Combine(UserProfile, "Projects", "Packages") static
Definition at line 127 of file Project.cs.
Referenced by Juniper.ConfigurationManagement.AssetStorePackage.Load().
UserDownloads
readonly string Juniper.ConfigurationManagement.Project.UserDownloads = Path.Combine(UserProfile, "Downloads") static
Definition at line 123 of file Project.cs.
Referenced by Juniper.ConfigurationManagement.AssetStorePackage.Load().
UserProfile
readonly string Juniper.ConfigurationManagement.Project.UserProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile) static
Definition at line 121 of file Project.cs.
Property Documentation
PackageDatabase
IReadOnlyDictionary<string, IReadOnlyCollection<AbstractPackage> > Juniper.ConfigurationManagement.Project.PackageDatabase static get
Definition at line 20 of file Project.cs.
         {
             get
             {
                 if (packageDB is null)
                 {
                     packageDB = AbstractPackage.Load();
                 }
                 return packageDB;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperInstalledPackageManager.DrawInstalledPackages(), Juniper.ConfigurationManagement.JuniperOptionalPackageManager.DrawOptionalPackages(), Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages(), Juniper.ConfigurationManagement.Project.IsAvailable(), and Juniper.ConfigurationManagement.Project.IsInstalled().
UnityEditorRoot
string Juniper.ConfigurationManagement.Project.UnityEditorRoot static get
Definition at line 88 of file Project.cs.
         {
             get
             {
                 if (unityEditorDirectoryName is null)
                 {
                     unityEditorDirectoryName = Environment.GetEnvironmentVariable("UNITY_ROOT");
                     if (unityEditorDirectoryName is null)
                     {
                         var exe = new FileInfo(Assembly.GetEntryAssembly().Location);
                         if (exe.Name == "Unity.exe")
{
                             unityEditorDirectoryName = exe.Directory.Parent.FullName;
                         }
                     }
                 }
                 return unityEditorDirectoryName;
             }
         }
Referenced by Juniper.ConfigurationManagement.UnityPackage.Load().
UnityProjectRoot
string Juniper.ConfigurationManagement.Project.UnityProjectRoot static get set
Definition at line 69 of file Project.cs.
         {
             get
             {
                 if (unityProjectDirectoryName is null)
                 {
                     unityProjectDirectoryName = Environment.CurrentDirectory;
                 }
                 return unityProjectDirectoryName;
             }
             set
             {
                 unityProjectDirectoryName = value;
             }
         }
Referenced by Juniper.ConfigurationManagement.UnityPackageManifest.Load(), and Juniper.ConfigurationManagement.UnityPackageManifest.Save().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.UnityEditor/ConfigurationManagement/Project.cs