Juniper: Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType > Class Template Reference
Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType > Class Template Reference abstract
Public Member Functions
virtual void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
virtual void Install (bool reset)
virtual void Uninstall ()
virtual void Reinstall ()
void Reset ()
virtual void SetProbe (Probe p)
Vector2 ScreenFromWorld (Vector3 worldPoint)
Vector2 ScreenFromViewport (Vector2 viewportPoint)
Vector2 ViewportFromWorld (Vector3 worldPoint)
Vector2 ViewportFromScreen (Vector2 screenPoint)
Vector3 WorldFromScreen (Vector2 screenPoint)
Vector3 WorldFromViewport (Vector2 viewportPoint)
void Update ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
virtual void PlayInteraction (Interaction action)
virtual void Process (PointerEventData evtData, float pixelDragThresholdSquared)
virtual bool IsButtonPressed (InputButton button)
abstract bool IsButtonPressed (ButtonIDType button)
bool IsButtonPressed (PointerEventData.InputButton button)
virtual bool IsButtonUp (InputButton button)
abstract bool IsButtonUp (ButtonIDType button)
bool IsButtonUp (PointerEventData.InputButton button)
virtual bool IsButtonDown (InputButton button)
abstract bool IsButtonDown (ButtonIDType button)
bool IsButtonDown (PointerEventData.InputButton button)
Public Attributes
Hands _hand
bool Connected
Material LaserPointerMaterial
bool showProbe = true
AbstractMotionFilter motionFilter
Protected Member Functions
virtual IEventSystemHandler ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared)
abstract void InternalUpdate ()
Protected Attributes
readonly ButtonMapper< ButtonIDType > nativeButtons = new ButtonMapper<ButtonIDType>()
Vector3 pointerOffset
Probe probe
The cursor probe that shows the physical location of the current selection.
UnifiedInputModule eventManager
StageExtensions stage
Static Protected Attributes
static readonly Vector2 VIEWPORT_MIDPOINT
static readonly ConfigType PointerConfig
Properties
virtual Hands Hand [get, set]
HandIDType? NativeHandID [get, protected set]
bool IsLeftHand [get]
bool IsRightHand [get]
abstract bool IsDominantHand [get]
bool IsNonDominantHand [get]
override Vector3 WorldPoint [get]
override Vector2 ScreenPoint [get]
override Vector2 ViewportPoint [get]
static Vector2 SCREEN_MIDPOINT [get]
Type ButtonType [get]
float MinimumPointerDistance [get]
The minimum distance from the camera at which to place the pointer.
float MaximumPointerDistance [get]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
abstract bool IsConnected [get]
bool IsEnabled [get]
bool IsDisabled [get]
Returns true when the device is supposed to be disabled.
PhysicsRaycaster? Raycaster [get]
Camera? EventCamera [get]
The camera the pointer uses to point at Canvas objects.
int PointerID [get, set]
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
virtual bool AnyButtonPressed [get]
string ProbeName [get, private set]
Vector3 LastWorldPoint [get, private set]
Vector2 ScreenDelta [get]
Vector3??? InteractionEndPoint [get]
The target at and through which the pointer rays fire.
Vector3 InteractionDirection [get]
The direction the pointer is pointing, from InteractionOrigin to InteractionEndPoint.
UnifiedInputModule InputModule [get, set]
virtual bool IsDragging [get]
HapticsType Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
string name [get]
string name [get]
bool isActiveAndEnabled [get]
Transform transform [get]
Detailed Description
Type Constraints
HandIDType : struct
HandIDType : IComparable
ButtonIDType : struct
ConfigType : AbstractHandedPointerConfiguration
ConfigType : HandIDType
ConfigType : ButtonIDType
ConfigType : new()
HapticsType : AbstractHapticDevice
Definition at line 36 of file AbstractHandedPointer.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake () inline virtual inherited
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 187 of file AbstractPointerDevice.cs.
         {
             Install(false);
             eventManager = ComponentExt.FindAny<UnifiedInputModule>();
             stage = ComponentExt.FindAny<StageExtensions>();
             pointerOffset = MinimumPointerDistance * Vector3.forward;
             ProbeName = name;
             Haptics = this.EnsureComponent<HapticsType>();
             nativeButtons.ButtonDownNeeded += IsButtonDown;
             nativeButtons.ButtonUpNeeded += IsButtonUp;
             nativeButtons.ButtonPressedNeeded += IsButtonPressed;
             nativeButtons.ClonedPointerEventNeeded += Clone;
             nativeButtons.InteractionNeeded += PlayInteraction;
             eventManager.AddPointer(this);
         }
References Juniper.Unity.Input.UnifiedInputModule.AddPointer(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.eventManager, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MinimumPointerDistance, Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.name, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProbeName, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.stage.
Install()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install (bool reset) inline virtual inherited
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 208 of file AbstractPointerDevice.cs.
         {
             reset &= Application.isEditor;
             PointerConfig.Install(nativeButtons, gameObject);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reinstall().
InternalUpdate()
abstract void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InternalUpdate () protected pure virtual inherited
Implemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >, and Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, HapticsType, ConfigType >.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
IsButtonDown() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonDown (PointerEventData.InputButton button) inherited
IsButtonDown() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown (InputButton button) inline virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 520 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonDown(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
IsButtonDown() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonPressed() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonPressed (PointerEventData.InputButton button) inherited
IsButtonPressed() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed (InputButton button) inline virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 510 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonPressed(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
IsButtonPressed() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonUp() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonUp (PointerEventData.InputButton button) inherited
IsButtonUp() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp (InputButton button) inline virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 515 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonUp(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
IsButtonUp() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
PlayInteraction()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction (Interaction action) inline virtual inherited
Definition at line 448 of file AbstractPointerDevice.cs.
         {
             if (Time.time > finishTime)
             {
                 finishTime = Time.time + InteractionAudio.Play(action, probe.Cursor, Haptics);
             }
         }
References Juniper.Unity.Input.Pointers.Probe.Cursor, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.finishTime, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics, Juniper.Unity.Audio.InteractionAudio.Play(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.TestEnterExit().
Process()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process (PointerEventData evtData, float pixelDragThresholdSquared) inline virtual inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 461 of file AbstractPointerDevice.cs.
         {
             if (!IsDragging)
             {
                 TestEnterExit(evtData);
             }
             EventTarget = ProcessButtons(evtData, pixelDragThresholdSquared);
             if (evtData.clickCount == -1)
             {
                 evtData.clickCount = 0;
             }
             LastWorldPoint = evtData.pointerCurrentRaycast.worldPosition;
             probe?.SetCursor(
                 evtData.pointerCurrentRaycast.gameObject != null,
                 AnyButtonPressed,
                 LastWorldPoint,
                 Quaternion.LookRotation(evtData.pointerCurrentRaycast.worldNormal));
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.AnyButtonPressed, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventTarget, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastWorldPoint, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons(), Juniper.Unity.Input.Pointers.Probe.SetCursor(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.TestEnterExit().
ProcessButtons()
virtual IEventSystemHandler Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared) inline protected virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 484 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.Process(evtData, pixelDragThresholdSquared);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
Reinstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reinstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 220 of file AbstractPointerDevice.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install().
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reset().
Reset()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reset () inline inherited
Definition at line 227 of file AbstractPointerDevice.cs.
         {
             Reinstall();
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reinstall().
ScreenFromViewport()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 318 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ViewportToScreenPoint(viewportPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
ScreenFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 313 of file AbstractPointerDevice.cs.
         {
             return EventCamera.WorldToScreenPoint(worldPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
SetProbe()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SetProbe (Probe p) inline virtual inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 259 of file AbstractPointerDevice.cs.
         {
             if (probe != p)
             {
                 if (probe != null)
                 {
                     probe.gameObject.Destroy();
                 }
                 probe = p ?? FindProbe();
             }
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.FindProbe(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe.
Uninstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Uninstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 215 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Uninstall(gameObject);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig.
Update()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update () inline inherited
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Definition at line 388 of file AbstractPointerDevice.cs.
         {
             if (motionFilter != lastMotionFilter)
             {
 #if UNITY_EDITOR
                 parent = motionFilter;
 #endif
                 motionFilter = Instantiate(motionFilter);
                 lastMotionFilter = motionFilter;
             }
 #if UNITY_EDITOR
             motionFilter?.Copy(parent);
 #endif
             Connected = IsConnected;
             if (probe != null)
             {
                 probe.SetActive(IsEnabled && showProbe);
                 probe.LaserPointerMaterial = LaserPointerMaterial;
             }
             if (IsEnabled)
             {
                 motionFilter?.UpdateState(WorldPoint);
                 InternalUpdate();
                 probe?.AlignProbe(InteractionDirection, transform.up, MaximumPointerDistance);
             }
         }
References Juniper.Unity.Input.Pointers.Probe.AlignProbe(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Connected, Juniper.Unity.Statistics.AbstractMotionFilter.Copy(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InteractionDirection, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsConnected, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsEnabled, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LaserPointerMaterial, Juniper.Unity.Input.Pointers.Probe.LaserPointerMaterial, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.lastMotionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MaximumPointerDistance, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.motionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.parent, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.showProbe, Juniper.Unity.Input.Pointers.IPointerDevice.transform, Juniper.Unity.Statistics.AbstractMotionFilter.UpdateState(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldPoint.
ViewportFromScreen()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 333 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ScreenToViewportPoint(screenPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
ViewportFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 328 of file AbstractPointerDevice.cs.
         {
             return EventCamera.WorldToViewportPoint(worldPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
WorldFromScreen()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 343 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ScreenToWorldPoint((Vector3)screenPoint + pointerOffset);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset.
WorldFromViewport()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 348 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ViewportToWorldPoint((Vector3)viewportPoint + pointerOffset);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset.
Member Data Documentation
_hand
Hands Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >._hand
Definition at line 44 of file AbstractHandedPointer.cs.
Connected
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Connected inherited
Definition at line 77 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
eventManager
UnifiedInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.eventManager protected inherited
Definition at line 419 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
LaserPointerMaterial
Material Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LaserPointerMaterial inherited
Definition at line 100 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
motionFilter
AbstractMotionFilter Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.motionFilter inherited
Definition at line 358 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
nativeButtons
readonly ButtonMapper<ButtonIDType> Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons = new ButtonMapper<ButtonIDType>() protected inherited
Definition at line 74 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons().
PointerConfig
readonly ConfigType Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig static protected inherited
Initial value:
=
            new ConfigType()
Definition at line 63 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Uninstall().
pointerOffset
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset protected inherited
Definition at line 90 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport().
probe
Probe Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe protected inherited
The cursor probe that shows the physical location of the current selection.
Definition at line 245 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SetProbe(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
showProbe
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.showProbe = true inherited
Definition at line 234 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
stage
StageExtensions Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.stage protected inherited
Definition at line 421 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
VIEWPORT_MIDPOINT
readonly Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.VIEWPORT_MIDPOINT static protected inherited
Initial value:
=
            0.5f * Vector2.one
Definition at line 60 of file AbstractPointerDevice.cs.
Property Documentation
AnyButtonPressed
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.AnyButtonPressed get inherited
Definition at line 175 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return IsButtonPressed(InputButton.Left)
                     || IsButtonPressed(InputButton.Right)
                     || IsButtonPressed(InputButton.Middle);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
ButtonType
Type Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ButtonType get inherited
Definition at line 67 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return typeof(ButtonIDType);
             }
         }
EventCamera
Camera? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera get inherited
The camera the pointer uses to point at Canvas objects.
Definition at line 158 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.EventCamera;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromViewport(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromWorld(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromScreen(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromWorld(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport().
EventTarget
IEventSystemHandler Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventTarget get set inherited
Definition at line 108 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
Hand
virtual Hands Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.Hand get set
Definition at line 47 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return _hand;
             }
             set
             {
                 _hand = value;
                 NativeHandID = PointerConfig[value];
             }
         }
Haptics
HapticsType Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics get protected set inherited
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 442 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction().
InputModule
UnifiedInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InputModule get set inherited
Definition at line 424 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Clone(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone().
InteractionDirection
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InteractionDirection get inherited
The direction the pointer is pointing, from InteractionOrigin to InteractionEndPoint.
The interaction direction.
Definition at line 377 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (InteractionEndPoint - transform.position).normalized;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< KeyCode, HapticsType, TouchPointConfiguration >.InternalUpdate(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
InteractionEndPoint
Vector3??? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InteractionEndPoint get inherited
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 365 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return motionFilter?.PredictedPosition ?? WorldPoint;
             }
         }
isActiveAndEnabled
bool Juniper.Unity.Input.Pointers.IPointerDevice.isActiveAndEnabled get inherited
Definition at line 16 of file IPointerDevice.cs.
         {
             get;
         }
IsConnected
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsConnected get inherited
Definition at line 122 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
IsDisabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDisabled get inherited
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 139 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return !IsEnabled;
             }
         }
IsDominantHand
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsDominantHand get
Definition at line 81 of file AbstractHandedPointer.cs.
         {
             get;
         }
IsDragging
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging get inherited
Definition at line 429 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return nativeButtons.AnyDragging;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
IsEnabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsEnabled get inherited
Definition at line 127 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return isActiveAndEnabled && IsConnected;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
IsLeftHand
bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsLeftHand get
Definition at line 65 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return Hand == Hands.Left;
             }
         }
IsNonDominantHand
bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsNonDominantHand get
Definition at line 86 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return !IsDominantHand;
             }
         }
IsRightHand
bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsRightHand get
Definition at line 73 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return Hand == Hands.Right;
             }
         }
LastWorldPoint
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastWorldPoint get private set inherited
Definition at line 296 of file AbstractPointerDevice.cs.
         {
             get; private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
LockedOnTarget
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LockedOnTarget get set inherited
Definition at line 103 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
MaximumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MaximumPointerDistance get inherited
Definition at line 93 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Min(10f, 0.9f * DisplayManager.MainCamera.farClipPlane);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
MinimumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MinimumPointerDistance get inherited
The minimum distance from the camera at which to place the pointer.
Definition at line 83 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Max(1.5f, 1.1f * DisplayManager.MainCamera.nearClipPlane);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
name [1/2]
string Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.name get inherited
Definition at line 7 of file IPointerButtons.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
name [2/2]
string Juniper.Unity.Input.Pointers.IPointerDevice.name get inherited
Definition at line 11 of file IPointerDevice.cs.
         {
             get;
         }
NativeHandID
HandIDType? Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.NativeHandID get protected set
Definition at line 60 of file AbstractHandedPointer.cs.
         {
             get; protected set;
         }
PointerID
int Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerID get set inherited
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
The pointer identifier.
Definition at line 170 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
ProbeName
string Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProbeName get private set inherited
Definition at line 273 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return _probeName;
             }
             private set
             {
                 if (value != ProbeName)
                 {
                     if (probe != null)
                     {
                         probe.gameObject.Destroy();
                         probe = null;
                     }
                     _probeName = value;
                     SetProbe(FindProbe());
                 }
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.FindProbe().
Raycaster
PhysicsRaycaster? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Raycaster get inherited
Definition at line 147 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.Raycaster;
             }
         }
SCREEN_MIDPOINT
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SCREEN_MIDPOINT static get protected inherited
Definition at line 53 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return new Vector2(UnityEngine.Screen.width / 2, UnityEngine.Screen.height / 2);
             }
         }
ScreenDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenDelta get inherited
Definition at line 301 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenPoint - ScreenFromWorld(LastWorldPoint);
             }
         }
ScreenPoint
override Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.ScreenPoint get
Definition at line 102 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return ScreenFromWorld(InteractionEndPoint);
             }
         }
ScrollDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScrollDelta get protected set inherited
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 117 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate().
transform
Transform Juniper.Unity.Input.Pointers.IPointerDevice.transform get inherited
Definition at line 21 of file IPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.FindProbe(), Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< KeyCode, HapticsType, TouchPointConfiguration >.InternalUpdate(), Juniper.Unity.Input.HoverCraft.Update(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update(), and Juniper.Unity.Input.UnifiedInputModule.UpdateRay().
ViewportPoint
override Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.ViewportPoint get
Definition at line 110 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return ViewportFromWorld(InteractionEndPoint);
             }
         }
WorldPoint
override Vector3 Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.WorldPoint get
Definition at line 94 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return transform.position + (MinimumPointerDistance * transform.forward);
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Pointers/Motion/AbstractHandedPointer.cs