Juniper: Juniper.Unity.SubSceneController Class Reference
Juniper.Unity.SubSceneController Class Reference
SubSceneControllers are used by the MasterSceneController to manage workflow through an application. They are parts of a greater scene that are loaded additively, with transitions between them. They are meant for keeping subsections of the application compartmentalized from each other, to discourage tightly coupling dependencies between different functional portions of the application.
Public Member Functions
virtual void Awake ()
virtual void Load (IProgressReceiver prog=null)
override void Enter ()
Fire the OnEnable event and perform the Enter transition.
override void Exit ()
Triggers the exit process and then deactivates the subscene.
override void Update ()
Checks to see if the state has changed and fires the right event for it.
void CopyStreamingAssets ()
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Public Attributes
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Protected Attributes
bool deactivateOnExit = true
Whether or not to deactivate the subscene when it has finished exiting.
Properties
IEnumerable< AbstractTransitionController > Enterable [get]
childTransitions that are not enabled, but exist on active game objects.
IEnumerable< AbstractTransitionController > Exitable [get]
Active and enabled childTransitions.
IEnumerable< SubSceneController > CurrentSubScenes [get]
Get all of the sub scenes that have been entered that are not the current sub scene.
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Member Functions
bool AllComplete (IEnumerable< AbstractStateController > subScenes)
Returns true when all of the parameter subScenes are SubSceneController.IsComplete.
Private Attributes
AbstractTransitionController [] childTransitions
All of the StateControllers that are in this gameObject's hierarchy (including itself), but not this SubSceneController.
bool isExitingPreviousScene
Detailed Description
SubSceneControllers are used by the MasterSceneController to manage workflow through an application. They are parts of a greater scene that are loaded additively, with transitions between them. They are meant for keeping subsections of the application compartmentalized from each other, to discourage tightly coupling dependencies between different functional portions of the application.
Definition at line 18 of file SubSceneController.cs.
Member Function Documentation
AllComplete()
bool Juniper.Unity.SubSceneController.AllComplete (IEnumerable< AbstractStateController > subScenes) inline private
Returns true when all of the parameter subScenes are SubSceneController.IsComplete.
Returns
The complete.
Parameters
subScenes Sub scenes.
Definition at line 151 of file SubSceneController.cs.
         {
             foreach (var subScene in subScenes)
             {
                 if (subScene.IsRunning)
                 {
                     return false;
                 }
             }
             return true;
         }
Referenced by Juniper.Unity.SubSceneController.Update().
Awake()
virtual void Juniper.Unity.SubSceneController.Awake () inline virtual
Definition at line 20 of file SubSceneController.cs.
         {
             childTransitions = GetComponentsInChildren<AbstractTransitionController>(true);
         }
References Juniper.Unity.SubSceneController.childTransitions.
CopyStreamingAssets()
void Juniper.Unity.SubSceneController.CopyStreamingAssets () inline
Definition at line 166 of file SubSceneController.cs.
         {
         }
Enter()
override void Juniper.Unity.SubSceneController.Enter () inline virtual
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 31 of file SubSceneController.cs.
         {
             isExitingPreviousScene = true;
             foreach (var subScene in CurrentSubScenes)
             {
                 subScene.Exit();
             }
             base.Enter();
         }
References Juniper.Unity.SubSceneController.CurrentSubScenes, and Juniper.Unity.SubSceneController.isExitingPreviousScene.
Exit()
override void Juniper.Unity.SubSceneController.Exit () inline virtual
Triggers the exit process and then deactivates the subscene.
Returns
The coroutine.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 46 of file SubSceneController.cs.
         {
             if (isActiveAndEnabled)
             {
                 foreach (var child in Exitable)
                 {
                     child.Exit();
                 }
             }
             base.Exit();
         }
References Juniper.Unity.SubSceneController.Exitable.
HasCompleted()
bool Juniper.Unity.AbstractStateController.HasCompleted () inline inherited
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 121 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.Unity.AbstractStateController.IsComplete.
Load()
virtual void Juniper.Unity.SubSceneController.Load (IProgressReceiver prog = null) inline virtual
Definition at line 25 of file SubSceneController.cs.
         {
             prog?.SetProgress(1);
         }
OnDisable()
void Juniper.Unity.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 298 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.Unity.AbstractStateController.OnExited().
OnEnable()
void Juniper.Unity.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 193 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.Unity.AbstractStateController.OnEntering().
Referenced by Juniper.Unity.AbstractStateController.SkipEnter().
OnEntered()
virtual void Juniper.Unity.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 240 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntered?.Invoke();
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entered, Juniper.Unity.AbstractStateController.onEntered, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Update().
OnEntering()
virtual void Juniper.Unity.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 204 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntering?.Invoke();
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entering, Juniper.Unity.AbstractStateController.onEntering, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnEnable().
OnExited()
override void Juniper.Unity.SubSceneController.OnExited () inline protected virtual
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 85 of file SubSceneController.cs.
         {
             base.OnExited();
             if (deactivateOnExit)
             {
                 this.Deactivate();
             }
         }
References Juniper.Unity.SubSceneController.deactivateOnExit.
OnExiting()
virtual void Juniper.Unity.AbstractStateController.OnExiting () inline protected virtual inherited
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 283 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExiting?.Invoke();
                 Exiting?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Exiting, Juniper.Unity.AbstractStateController.onExiting, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Exit(), and Juniper.Unity.AbstractStateController.SkipExit().
SkipEnter()
virtual void Juniper.Unity.AbstractStateController.SkipEnter () inline virtual inherited
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Unity.Animation.AbstractTransitionController.
Definition at line 162 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Forward;
             OnEnable();
             lastState = Direction.Forward;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnEnable(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
SkipExit()
virtual void Juniper.Unity.AbstractStateController.SkipExit () inline virtual inherited
Jump to the fully entered state without firing any events.
Definition at line 252 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnExiting(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
Update()
override void Juniper.Unity.SubSceneController.Update () inline virtual
Checks to see if the state has changed and fires the right event for it.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 58 of file SubSceneController.cs.
         {
             if (IsRunning)
             {
                 if (state == Direction.Forward && !isExitingPreviousScene && AllComplete(Enterable)
                     || state == Direction.Reverse && AllComplete(Exitable))
                 {
                     state = Direction.Stopped;
                 }
                 else if (state == Direction.Forward && isExitingPreviousScene && AllComplete(CurrentSubScenes))
                 {
                     isExitingPreviousScene = false;
                     foreach (var child in Enterable)
                     {
                         child.Enter();
                     }
                 }
             }
             base.Update();
         }
References Juniper.Unity.SubSceneController.AllComplete(), Juniper.Unity.SubSceneController.CurrentSubScenes, Juniper.Unity.SubSceneController.Enterable, Juniper.Unity.SubSceneController.Exitable, Juniper.Unity.SubSceneController.isExitingPreviousScene, Juniper.Unity.AbstractStateController.IsRunning, and Juniper.Unity.AbstractStateController.state.
Member Data Documentation
childTransitions
AbstractTransitionController [] Juniper.Unity.SubSceneController.childTransitions private
All of the StateControllers that are in this gameObject's hierarchy (including itself), but not this SubSceneController.
The child state controllers.
Definition at line 100 of file SubSceneController.cs.
Referenced by Juniper.Unity.SubSceneController.Awake().
deactivateOnExit
bool Juniper.Unity.SubSceneController.deactivateOnExit = true protected
Whether or not to deactivate the subscene when it has finished exiting.
Definition at line 83 of file SubSceneController.cs.
Referenced by Juniper.Unity.SubSceneController.OnExited().
isExitingPreviousScene
bool Juniper.Unity.SubSceneController.isExitingPreviousScene private
Definition at line 102 of file SubSceneController.cs.
Referenced by Juniper.Unity.SubSceneController.Enter(), and Juniper.Unity.SubSceneController.Update().
onEntered
UnityEvent Juniper.Unity.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 33 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.Unity.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 24 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.Unity.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 51 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.Unity.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 42 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
state
Direction Juniper.Unity.AbstractStateController.state inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 94 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), Juniper.Unity.Animation.AbstractTransitionController.Update(), and Juniper.Unity.AbstractStateController.Update().
Property Documentation
CurrentSubScenes
IEnumerable<SubSceneController> Juniper.Unity.SubSceneController.CurrentSubScenes get private
Get all of the sub scenes that have been entered that are not the current sub scene.
The current sub scenes.
Definition at line 137 of file SubSceneController.cs.
         {
             get
             {
                 return from scene in FindObjectsOfType<SubSceneController>()
                        where scene.enabled && scene != this
                        select scene;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Enter(), and Juniper.Unity.SubSceneController.Update().
Enterable
IEnumerable<AbstractTransitionController> Juniper.Unity.SubSceneController.Enterable get private
childTransitions that are not enabled, but exist on active game objects.
The enterable.
Definition at line 109 of file SubSceneController.cs.
         {
             get
             {
                 return from trans in childTransitions
                        where !trans.enabled
                        select trans;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update().
Exitable
IEnumerable<AbstractTransitionController> Juniper.Unity.SubSceneController.Exitable get private
Active and enabled childTransitions.
The exitable.
Definition at line 123 of file SubSceneController.cs.
         {
             get
             {
                 return from trans in childTransitions
                        where trans.enabled
                        select trans;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Exit(), and Juniper.Unity.SubSceneController.Update().
IsComplete
virtual bool Juniper.Unity.AbstractStateController.IsComplete get inherited
Returns true when state is Direction.Stopped
Definition at line 110 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.HasCompleted(), and Juniper.Unity.AbstractStateController.Update().
IsEntered
bool Juniper.Unity.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 141 of file AbstractStateController.cs.
         {
             get
             {
                 return enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Exit().
IsExited
bool Juniper.Unity.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 152 of file AbstractStateController.cs.
         {
             get
             {
                 return !enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Enter().
IsRunning
bool Juniper.Unity.AbstractStateController.IsRunning get inherited
Returns true when state is not Direction.Stopped
Definition at line 130 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
Waiter
WaitUntil Juniper.Unity.AbstractStateController.Waiter get inherited
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 329 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.Unity.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 69 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.Unity.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 60 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.Unity.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 87 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.Unity.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 78 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnExiting().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/SubSceneController.cs