Juniper: Juniper.Collections.PriorityQueue< T > Class Template Reference
Juniper.Collections.PriorityQueue< T > Class Template Reference
A queue data structure that places emphasis on some items over others.
Classes
class PQComparer
A default Comparer to use when a comparer is not defined. If the type implements the IComparable<T> or IComparable interface, then it will use the object's own CompareTo method.
Public Member Functions
PriorityQueue ()
Default constructor, uses natural ordering comparator for objects
PriorityQueue (IEnumerable< T > values)
PriorityQueue (IComparer< T > comparer)
Constructor using explicit comparer for objects
PriorityQueue (IComparer< T > comparer, IEnumerable< T > values)
void Clear ()
removes all the objects from the priority queue
bool Contains (T item)
Performs a linear search for the provided item. WARNING: this method has an O(n^2) runtime profile. Use with caution.
void CopyTo (T[] array, int index)
T Dequeue ()
Removes an item from the front of the queue
void Enqueue (T item)
Adds an item to the queue, using the natural order of the object type if no Comparer is provided during construction of the PriorityQueue.
void Add (T item)
IEnumerator< T > GetEnumerator ()
Retrieves a generic enumerator over the objects of the queue
T Peek ()
Returns an item from the front of the queue without removing it
T [] ToArray ()
Create an array out of the queue
bool Remove (T item)
Public Attributes
int Count => q.Count
get the number of elements in the collection
bool IsSynchronized => true
Get the status of this collection as a synchronized collection
object SyncRoot => q
The object to use for locking when using the queue in a multithreaded environment
bool IsReadOnly => false
Properties
IComparer< T > Comparer [get]
Retrieve the comparer to use with the objects being added to the queue
Private Member Functions
void ICollection. CopyTo (Array arr, int startIndex)
IEnumerator IEnumerable. GetEnumerator ()
Retrieves an enumerator over the objects of the queue
Private Attributes
readonly List< T > q = new List<T>()
Detailed Description
A queue data structure that places emphasis on some items over others.
Template Parameters
T The type of objects that will be placed in the PriorityQueue
Type Constraints
T : IComparable<T>
Definition at line 17 of file PriorityQueue.cs.
Constructor & Destructor Documentation
PriorityQueue() [1/4]
Juniper.Collections.PriorityQueue< T >.PriorityQueue () inline
Default constructor, uses natural ordering comparator for objects
Definition at line 28 of file PriorityQueue.cs.
             : this(new PQComparer(), Array.Empty<T>())
         { }
PriorityQueue() [2/4]
Juniper.Collections.PriorityQueue< T >.PriorityQueue (IEnumerable< T > values) inline
Definition at line 32 of file PriorityQueue.cs.
             : this(new PQComparer(), values)
         { }
PriorityQueue() [3/4]
Juniper.Collections.PriorityQueue< T >.PriorityQueue (IComparer< T > comparer) inline
Constructor using explicit comparer for objects
Parameters
comparer
Definition at line 40 of file PriorityQueue.cs.
             : this(comparer, Array.Empty<T>())
         { }
PriorityQueue() [4/4]
Juniper.Collections.PriorityQueue< T >.PriorityQueue (IComparer< T > comparer, IEnumerable< T > values) inline
Definition at line 44 of file PriorityQueue.cs.
         {
             if (values is null)
             {
                 throw new ArgumentNullException(nameof(values));
             }
             Comparer = comparer ?? throw new ArgumentNullException(nameof(comparer));
             foreach (var value in values)
             {
                 Enqueue(value);
             }
         }
References Juniper.Collections.PriorityQueue< T >.Comparer, and Juniper.Collections.PriorityQueue< T >.Enqueue().
Member Function Documentation
Add()
void Juniper.Collections.PriorityQueue< T >.Add (T item) inline
Definition at line 137 of file PriorityQueue.cs.
         {
             //figure out which queue to add the object to
             int addIndex;
             for (addIndex = 0; addIndex < q.Count; ++addIndex)
             {
                 var t = q[addIndex];
                 var n = Comparer.Compare(t, item);
                 if (n == 1)
                 {
                     break;
                 }
             }
             q.Insert(addIndex, item);
         }
References Juniper.Collections.PriorityQueue< T >.Comparer, and Juniper.Collections.PriorityQueue< T >.q.
Clear()
void Juniper.Collections.PriorityQueue< T >.Clear () inline
removes all the objects from the priority queue
Definition at line 84 of file PriorityQueue.cs.
         {
             q.Clear();
         }
References Juniper.Collections.PriorityQueue< T >.q.
Contains()
bool Juniper.Collections.PriorityQueue< T >.Contains (T item) inline
Performs a linear search for the provided item. WARNING: this method has an O(n^2) runtime profile. Use with caution.
Returns
Definition at line 95 of file PriorityQueue.cs.
         {
             return q.Contains(item);
         }
References Juniper.Collections.PriorityQueue< T >.q.
CopyTo() [1/2]
void Juniper.Collections.PriorityQueue< T >.CopyTo (T [] array, int index) inline
Copies the queue elements to an existing one-dimensional array, starting at the specified index array.
Throws an exception if the supplied array is null, the index is less than zero or greater than the length of the array, or would result in the items going outside of the array bounds.
Parameters
array
index
Definition at line 112 of file PriorityQueue.cs.
         {
             q.CopyTo(array, index);
         }
References Juniper.Collections.PriorityQueue< T >.q.
Referenced by Juniper.Collections.PriorityQueue< T >.CopyTo().
CopyTo() [2/2]
void ICollection. Juniper.Collections.PriorityQueue< T >.CopyTo (Array arr, int startIndex) inline private
Definition at line 181 of file PriorityQueue.cs.
         {
             var temp = new T[Count];
             CopyTo(temp, 0);
             for (var i = 0; i < temp.Length; ++i)
             {
                 arr.SetValue(temp[i], startIndex + i);
             }
         }
References Juniper.Collections.PriorityQueue< T >.CopyTo(), and Juniper.Collections.PriorityQueue< T >.Count.
Dequeue()
T Juniper.Collections.PriorityQueue< T >.Dequeue () inline
Removes an item from the front of the queue
Definition at line 120 of file PriorityQueue.cs.
         {
             var obj = q[0];
             q.RemoveAt(0);
             return obj;
         }
References Juniper.Collections.PriorityQueue< T >.q.
Enqueue()
void Juniper.Collections.PriorityQueue< T >.Enqueue (T item) inline
Adds an item to the queue, using the natural order of the object type if no Comparer is provided during construction of the PriorityQueue.
Parameters
item The object to add
Definition at line 132 of file PriorityQueue.cs.
         {
             ((ICollection<T>)this).Add(item);
         }
Referenced by Juniper.Collections.PriorityQueue< T >.PriorityQueue().
GetEnumerator() [1/2]
IEnumerator<T> Juniper.Collections.PriorityQueue< T >.GetEnumerator () inline
Retrieves a generic enumerator over the objects of the queue
Returns
Definition at line 158 of file PriorityQueue.cs.
         {
             return q.GetEnumerator();
         }
References Juniper.Collections.PriorityQueue< T >.q.
Referenced by Juniper.Collections.PriorityQueue< T >.GetEnumerator().
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.Collections.PriorityQueue< T >.GetEnumerator () inline private
Retrieves an enumerator over the objects of the queue
Returns
Definition at line 195 of file PriorityQueue.cs.
         {
             return GetEnumerator();
         }
References Juniper.Collections.PriorityQueue< T >.GetEnumerator().
Peek()
T Juniper.Collections.PriorityQueue< T >.Peek () inline
Returns an item from the front of the queue without removing it
Returns
Definition at line 167 of file PriorityQueue.cs.
         {
             return q[0];
         }
References Juniper.Collections.PriorityQueue< T >.q.
Remove()
bool Juniper.Collections.PriorityQueue< T >.Remove (T item) inline
Definition at line 200 of file PriorityQueue.cs.
         {
             return q.Remove(item);
         }
References Juniper.Collections.PriorityQueue< T >.q.
ToArray()
T [] Juniper.Collections.PriorityQueue< T >.ToArray () inline
Create an array out of the queue
Returns
Definition at line 176 of file PriorityQueue.cs.
         {
             return q.ToArray();
         }
References Juniper.Collections.PriorityQueue< T >.q.
Member Data Documentation
Count
int Juniper.Collections.PriorityQueue< T >.Count => q.Count
get the number of elements in the collection
Definition at line 67 of file PriorityQueue.cs.
Referenced by Juniper.Collections.PriorityQueue< T >.CopyTo().
IsReadOnly
bool Juniper.Collections.PriorityQueue< T >.IsReadOnly => false
Definition at line 79 of file PriorityQueue.cs.
IsSynchronized
bool Juniper.Collections.PriorityQueue< T >.IsSynchronized => true
Get the status of this collection as a synchronized collection
Definition at line 72 of file PriorityQueue.cs.
q
readonly List<T> Juniper.Collections.PriorityQueue< T >.q = new List<T>() private
Definition at line 23 of file PriorityQueue.cs.
Referenced by Juniper.Collections.PriorityQueue< T >.Add(), Juniper.Collections.PriorityQueue< T >.Clear(), Juniper.Collections.PriorityQueue< T >.Contains(), Juniper.Collections.PriorityQueue< T >.CopyTo(), Juniper.Collections.PriorityQueue< T >.Dequeue(), Juniper.Collections.PriorityQueue< T >.GetEnumerator(), Juniper.Collections.PriorityQueue< T >.Peek(), Juniper.Collections.PriorityQueue< T >.Remove(), and Juniper.Collections.PriorityQueue< T >.ToArray().
SyncRoot
object Juniper.Collections.PriorityQueue< T >.SyncRoot => q
The object to use for locking when using the queue in a multithreaded environment
Definition at line 77 of file PriorityQueue.cs.
Property Documentation
Comparer
IComparer<T> Juniper.Collections.PriorityQueue< T >.Comparer get
Retrieve the comparer to use with the objects being added to the queue
Definition at line 62 of file PriorityQueue.cs.
 { get; }
Referenced by Juniper.Collections.PriorityQueue< T >.Add(), and Juniper.Collections.PriorityQueue< T >.PriorityQueue().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Collections/PriorityQueue.cs