Juniper: Juniper.Statistics.KalmanMotionFilter Class Reference
Juniper.Statistics.KalmanMotionFilter Class Reference
Public Member Functions
override void Copy (AbstractMotionFilter filter)
override void UpdateState (Vector3 point)
Public Attributes
uint componentCount = 2
float measurementNoise = 10
uint processNoiseScale = 100
float processNoiseExponent = 1
override Vector3 Position
Properties
uint ComponentCount [get, set]
uint Dimension [get, set]
DiscreteKalmanFilter< Vector3[], Vector3 > Kalman [get, set]
override Vector3? PredictedPosition [get]
Private Member Functions
uint X (uint i)
uint Y (uint i)
uint Z (uint i)
Vector3 [] FromArray (double[] arr)
double [] ToArray (Vector3[] vecs)
double [,] GetProcessNoise (Func< uint, double > getProcNoiseForVec)
double [,] MakePositionMeasurementMatrix ()
double [,] MakeTransitionMatrix ()
Private Attributes
float mNoise
uint procNoiseK
float procNoiseE
const uint VectorSize = 3
Vector3? lastPoint
Detailed Description
Definition at line 14 of file KalmanMotionFilter.cs.
Member Function Documentation
Copy()
override void Juniper.Statistics.KalmanMotionFilter.Copy (AbstractMotionFilter filter) inline virtual
Implements Juniper.Statistics.AbstractMotionFilter.
Definition at line 55 of file KalmanMotionFilter.cs.
         {
             if (filter is KalmanMotionFilter)
             {
                 var f = (KalmanMotionFilter)filter;
                 componentCount = f.componentCount;
                 measurementNoise = f.measurementNoise;
                 processNoiseScale = f.processNoiseScale;
             }
         }
References Juniper.Statistics.KalmanMotionFilter.componentCount, Juniper.Statistics.KalmanMotionFilter.measurementNoise, and Juniper.Statistics.KalmanMotionFilter.processNoiseScale.
FromArray()
Vector3 [] Juniper.Statistics.KalmanMotionFilter.FromArray (double [] arr) inline private
Definition at line 117 of file KalmanMotionFilter.cs.
         {
             var vecs = new Vector3[ComponentCount];
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 vecs[i].x = (float)arr[X(i)];
                 vecs[i].y = (float)arr[Y(i)];
                 vecs[i].z = (float)arr[Z(i)];
             }
             return vecs;
         }
References Juniper.Statistics.KalmanMotionFilter.ComponentCount, Juniper.Statistics.KalmanMotionFilter.X(), Juniper.Statistics.KalmanMotionFilter.Y(), and Juniper.Statistics.KalmanMotionFilter.Z().
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
GetProcessNoise()
double [,] Juniper.Statistics.KalmanMotionFilter.GetProcessNoise (Func< uint, double > getProcNoiseForVec) inline private
Definition at line 141 of file KalmanMotionFilter.cs.
         {
             var vec = new double[Dimension];
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 for (uint x = 0; x < VectorSize; ++x)
                 {
                     vec[i * VectorSize + x] = getProcNoiseForVec(i);
                 }
             }
             return Matrix.Diagonal((int)Dimension, vec);
         }
References Juniper.Statistics.KalmanMotionFilter.ComponentCount, Juniper.Statistics.KalmanMotionFilter.Dimension, and Juniper.Statistics.KalmanMotionFilter.VectorSize.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
MakePositionMeasurementMatrix()
double [,] Juniper.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix () inline private
Definition at line 154 of file KalmanMotionFilter.cs.
         {
             var m = new double[VectorSize, ComponentCount * VectorSize];
             for (uint i = 0; i < VectorSize; ++i)
             {
                 m[i, i * ComponentCount] = 1;
             }
             return m;
         }
References Juniper.Statistics.KalmanMotionFilter.ComponentCount, and Juniper.Statistics.KalmanMotionFilter.VectorSize.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
MakeTransitionMatrix()
double [,] Juniper.Statistics.KalmanMotionFilter.MakeTransitionMatrix () inline private
Definition at line 164 of file KalmanMotionFilter.cs.
         {
             var t = Time.fixedDeltaTime;
             var parts = new double[ComponentCount];
             double accum = 1;
             for (uint i = 0; i < ComponentCount; ++i)
             {
                 parts[i] = accum * Mathf.Pow(t, i);
                 accum /= i + 1;
             }
             var m = new double[Dimension, Dimension];
             for (uint y = 0; y < Dimension; ++y)
             {
                 uint chunkRow = y % ComponentCount;
                 for (uint x = 0; x < ComponentCount - chunkRow; ++x)
                 {
                     m[y, y + x] = parts[x];
                 }
             }
             return m;
         }
References Juniper.Statistics.KalmanMotionFilter.ComponentCount, and Juniper.Statistics.KalmanMotionFilter.Dimension.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
ToArray()
double [] Juniper.Statistics.KalmanMotionFilter.ToArray (Vector3 [] vecs) inline private
Definition at line 129 of file KalmanMotionFilter.cs.
         {
             var arr = new double[Dimension];
             for (uint i = 0; i < vecs.Length; ++i)
             {
                 arr[X(i)] = vecs[i].x;
                 arr[Y(i)] = vecs[i].y;
                 arr[Z(i)] = vecs[i].z;
             }
             return arr;
         }
References Juniper.Statistics.KalmanMotionFilter.Dimension, Juniper.Statistics.KalmanMotionFilter.X(), Juniper.Statistics.KalmanMotionFilter.Y(), and Juniper.Statistics.KalmanMotionFilter.Z().
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
UpdateState()
override void Juniper.Statistics.KalmanMotionFilter.UpdateState (Vector3 point) inline virtual
Implements Juniper.Statistics.AbstractMotionFilter.
Definition at line 69 of file KalmanMotionFilter.cs.
         {
             componentCount = Math.Max(1, componentCount);
             if (Kalman != null
                 && componentCount == ComponentCount
                 && Mathf.Approximately(measurementNoise, mNoise)
                 && processNoiseScale == procNoiseK
                 && Mathf.Approximately(processNoiseExponent, procNoiseE))
             {
                 Kalman.Correct(point);
             }
             else
             {
                 ComponentCount = componentCount;
                 Dimension = VectorSize * ComponentCount;
                 mNoise = measurementNoise;
                 procNoiseK = processNoiseScale;
                 procNoiseE = processNoiseExponent;
                 var initialState = new Vector3[ComponentCount];
                 initialState[0] = lastPoint ?? point;
                 Kalman = new DiscreteKalmanFilter<Vector3[], Vector3>(
                     initialState,
                     GetProcessNoise(_ => processNoiseScale),
                     (int)VectorSize,
                     0,
                     ToArray,
                     FromArray,
                     x => new double[] { x.x, x.y, x.z })
                 {
                     ProcessNoise = GetProcessNoise(i =>
                         Mathf.Pow(processNoiseScale, processNoiseExponent * (i + 1))),
                     MeasurementMatrix = MakePositionMeasurementMatrix(),
                     TransitionMatrix = MakeTransitionMatrix(),
                     MeasurementNoise = Matrix.Diagonal((int)VectorSize, (double)measurementNoise)
                 };
                 if (lastPoint != null)
                 {
                     Kalman.Correct(point);
                 }
                 Kalman.Predict();
                 lastPoint = point;
             }
         }
References Juniper.Statistics.KalmanMotionFilter.componentCount, Juniper.Statistics.KalmanMotionFilter.ComponentCount, Juniper.Statistics.KalmanMotionFilter.Dimension, Juniper.Statistics.KalmanMotionFilter.FromArray(), Juniper.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Statistics.KalmanMotionFilter.Kalman, Juniper.Statistics.KalmanMotionFilter.lastPoint, Juniper.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix(), Juniper.Statistics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Statistics.KalmanMotionFilter.measurementNoise, Juniper.Statistics.KalmanMotionFilter.mNoise, Juniper.Statistics.KalmanMotionFilter.processNoiseExponent, Juniper.Statistics.KalmanMotionFilter.processNoiseScale, Juniper.Statistics.KalmanMotionFilter.procNoiseE, Juniper.Statistics.KalmanMotionFilter.procNoiseK, Juniper.Statistics.KalmanMotionFilter.ToArray(), and Juniper.Statistics.KalmanMotionFilter.VectorSize.
X()
uint Juniper.Statistics.KalmanMotionFilter.X (uint i) private
Referenced by Juniper.Statistics.KalmanMotionFilter.FromArray(), and Juniper.Statistics.KalmanMotionFilter.ToArray().
Y()
uint Juniper.Statistics.KalmanMotionFilter.Y (uint i) private
Referenced by Juniper.Statistics.KalmanMotionFilter.FromArray(), and Juniper.Statistics.KalmanMotionFilter.ToArray().
Z()
uint Juniper.Statistics.KalmanMotionFilter.Z (uint i) private
Referenced by Juniper.Statistics.KalmanMotionFilter.FromArray(), and Juniper.Statistics.KalmanMotionFilter.ToArray().
Member Data Documentation
componentCount
uint Juniper.Statistics.KalmanMotionFilter.componentCount = 2
Definition at line 16 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.Copy(), and Juniper.Statistics.KalmanMotionFilter.UpdateState().
lastPoint
Vector3? Juniper.Statistics.KalmanMotionFilter.lastPoint private
Definition at line 67 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
measurementNoise
float Juniper.Statistics.KalmanMotionFilter.measurementNoise = 10
Definition at line 19 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.Copy(), and Juniper.Statistics.KalmanMotionFilter.UpdateState().
mNoise
float Juniper.Statistics.KalmanMotionFilter.mNoise private
Definition at line 20 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
Position
override Vector3 Juniper.Statistics.KalmanMotionFilter.Position
Initial value:
=>
            Kalman?.State[0] ?? Vector3.zero
Definition at line 51 of file KalmanMotionFilter.cs.
processNoiseExponent
float Juniper.Statistics.KalmanMotionFilter.processNoiseExponent = 1
Definition at line 26 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
processNoiseScale
uint Juniper.Statistics.KalmanMotionFilter.processNoiseScale = 100
Definition at line 22 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.Copy(), and Juniper.Statistics.KalmanMotionFilter.UpdateState().
procNoiseE
float Juniper.Statistics.KalmanMotionFilter.procNoiseE private
Definition at line 28 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
procNoiseK
uint Juniper.Statistics.KalmanMotionFilter.procNoiseK private
Definition at line 23 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
VectorSize
const uint Juniper.Statistics.KalmanMotionFilter.VectorSize = 3 private
Definition at line 30 of file KalmanMotionFilter.cs.
Referenced by Juniper.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix(), and Juniper.Statistics.KalmanMotionFilter.UpdateState().
Property Documentation
ComponentCount
uint Juniper.Statistics.KalmanMotionFilter.ComponentCount get set private
Definition at line 17 of file KalmanMotionFilter.cs.
 { get; set; }
Referenced by Juniper.Statistics.KalmanMotionFilter.FromArray(), Juniper.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Statistics.KalmanMotionFilter.MakePositionMeasurementMatrix(), Juniper.Statistics.KalmanMotionFilter.MakeTransitionMatrix(), and Juniper.Statistics.KalmanMotionFilter.UpdateState().
Dimension
uint Juniper.Statistics.KalmanMotionFilter.Dimension get set private
Definition at line 32 of file KalmanMotionFilter.cs.
 { get; set; }
Referenced by Juniper.Statistics.KalmanMotionFilter.GetProcessNoise(), Juniper.Statistics.KalmanMotionFilter.MakeTransitionMatrix(), Juniper.Statistics.KalmanMotionFilter.ToArray(), and Juniper.Statistics.KalmanMotionFilter.UpdateState().
Kalman
DiscreteKalmanFilter<Vector3[], Vector3> Juniper.Statistics.KalmanMotionFilter.Kalman get set private
Definition at line 34 of file KalmanMotionFilter.cs.
 { get; set; }
Referenced by Juniper.Statistics.KalmanMotionFilter.UpdateState().
PredictedPosition
override Vector3? Juniper.Statistics.KalmanMotionFilter.PredictedPosition get
Definition at line 43 of file KalmanMotionFilter.cs.
         {
             get
             {
                 Kalman?.Predict();
                 return Position;
             }
         }
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Unity/Statistics/KalmanMotionFilter.cs