namespace Juniper;

public partial class MediaType
{
    public static readonly Image Image_Aces = new("aces");
    public static readonly Image Image_Apng = new("apng", "apng");
    public static readonly Image Image_Avci = new("avci");
    public static readonly Image Image_Avcs = new("avcs");
    public static readonly Image Image_Avif = new("avif", "avif");
    public static readonly Image Image_Bmp = new("bmp", "bmp");
    public static readonly Image Image_Cgm = new("cgm", "cgm");
    public static readonly Image Image_Dicom_Rle = new("dicom-rle");
    public static readonly Image Image_Emf = new("emf");
    public static readonly Image Image_Example = new("example");
    public static readonly Image Image_EXR = new("x-exr", "exr");
    public static readonly Image Image_Fits = new("fits");
    public static readonly Image Image_G3fax = new("g3fax", "g3");
    public static readonly Image Image_Gif = new("gif", "gif");
    public static readonly Image Image_Heic = new("heic");
    public static readonly Image Image_Heic_Sequence = new("heic-sequence");
    public static readonly Image Image_Heif = new("heif");
    public static readonly Image Image_Heif_Sequence = new("heif-sequence");
    public static readonly Image Image_Hej2k = new("hej2k");
    public static readonly Image Image_Hsj2 = new("hsj2");
    public static readonly Image Image_Ief = new("ief", "ief");
    public static readonly Image Image_Jls = new("jls");
    public static readonly Image Image_Jp2 = new("jp2");
    public static readonly Image Image_Jpeg = new("jpeg", "jpeg", "jpg", "jpe");
    public static readonly Image Image_Jph = new("jph");
    public static readonly Image Image_Jphc = new("jphc");
    public static readonly Image Image_Jpm = new("jpm");
    public static readonly Image Image_Jpx = new("jpx");
    public static readonly Image Image_Jxr = new("jxr");
    public static readonly Image Image_JxrA = new("jxra");
    public static readonly Image Image_JxrS = new("jxrs");
    public static readonly Image Image_Jxs = new("jxs");
    public static readonly Image Image_Jxsc = new("jxsc");
    public static readonly Image Image_Jxsi = new("jxsi");
    public static readonly Image Image_Jxss = new("jxss");
    public static readonly Image Image_Ktx = new("ktx", "ktx");
    public static readonly Image Image_Naplps = new("naplps");
    public static readonly Image Image_Pjpeg = new("pjpeg");
    public static readonly Image Image_Png = new("png", "png");
    public static readonly Image Image_PrsBtif = new("prs.btif", "btif");
    public static readonly Image Image_PrsPti = new("prs.pti");
    public static readonly Image Image_Pwg_Raster = new("pwg-raster");
    public static readonly Image Image_Raw = new("x-raw", "raw");
    public static readonly Image Image_Sgi = new("sgi", "sgi");
    public static readonly Image Image_SvgXml = new("svg+xml", "svg", "svgz");
    public static readonly Image Image_T38 = new("t38");
    public static readonly Image Image_Tiff = new("tiff", "tiff", "tif");
    public static readonly Image Image_Tiff_Fx = new("tiff-fx");
    public static readonly Image Image_Vendor_AdobePhotoshop = new("vnd.adobe.photoshop", "psd");
    public static readonly Image Image_Vendor_AirzipAcceleratorAzv = new("vnd.airzip.accelerator.azv");
    public static readonly Image Image_Vendor_CnsInf2 = new("vnd.cns.inf2");
    public static readonly Image Image_Vendor_DeceGraphic = new("vnd.dece.graphic", "uvi", "uvvi", "uvg", "uvvg");
    public static readonly Image Image_Vendor_Djvu = new("vnd.djvu", "djvu", "djv");
    public static readonly Image Image_Vendor_DvbSubtitle = new("vnd.dvb.subtitle", "sub");
    public static readonly Image Image_Vendor_Dwg = new("vnd.dwg", "dwg");
    public static readonly Image Image_Vendor_Dxf = new("vnd.dxf", "dxf");
    public static readonly Image Image_Vendor_Fastbidsheet = new("vnd.fastbidsheet", "fbs");
    public static readonly Image Image_Vendor_Fpx = new("vnd.fpx", "fpx");
    public static readonly Image Image_Vendor_Fst = new("vnd.fst", "fst");
    public static readonly Image Image_Vendor_FujixeroxEdmics_Mmr = new("vnd.fujixerox.edmics-mmr", "mmr");
    public static readonly Image Image_Vendor_FujixeroxEdmics_Rlc = new("vnd.fujixerox.edmics-rlc", "rlc");
    public static readonly Image Image_Vendor_GlobalgraphicsPgb = new("vnd.globalgraphics.pgb");
    public static readonly Image Image_Vendor_MicrosoftIcon = new("vnd.microsoft.icon", "ico");
    public static readonly Image Image_Vendor_Mix = new("vnd.mix");
    public static readonly Image Image_Vendor_MozillaApng = new("vnd.mozilla.apng");
    public static readonly Image Image_Vendor_Ms_Dds = new("vnd.ms-dds", "dds");
    public static readonly Image Image_Vendor_Ms_Modi = new("vnd.ms-modi", "mdi");
    public static readonly Image Image_Vendor_Ms_Photo = new("vnd.ms-photo", "wdp");
    public static readonly Image Image_Vendor_Net_Fpx = new("vnd.net-fpx", "npx");
    public static readonly Image Image_Vendor_Radiance = new("vnd.radiance");
    public static readonly Image Image_Vendor_SealedmediaSoftsealGif = new("vnd.sealedmedia.softseal.gif");
    public static readonly Image Image_Vendor_SealedmediaSoftsealJpg = new("vnd.sealedmedia.softseal.jpg");
    public static readonly Image Image_Vendor_SealedPng = new("vnd.sealed.png");
    public static readonly Image Image_Vendor_Svf = new("vnd.svf");
    public static readonly Image Image_Vendor_TencentTap = new("vnd.tencent.tap");
    public static readonly Image Image_Vendor_ValveSourceTexture = new("vnd.valve.source.texture");
    public static readonly Image Image_Vendor_WapWbmp = new("vnd.wap.wbmp", "wbmp");
    public static readonly Image Image_Vendor_Xiff = new("vnd.xiff", "xif");
    public static readonly Image Image_Vendor_ZbrushPcx = new("vnd.zbrush.pcx");
    public static readonly Image Image_Webp = new("webp", "webp");
    public static readonly Image Image_Wmf = new("wmf");
    public static readonly Image Image_X_3ds = new("x-3ds", "3ds");
    public static readonly Image Image_X_Cmu_Raster = new("x-cmu-raster", "ras");
    public static readonly Image Image_X_Cmx = new("x-cmx", "cmx");

    [System.Obsolete("DEPRECATED in favor of image/emf")]
    public static readonly Image Image_X_Emf = new("x-emf");

    public static readonly Image Image_X_Freehand = new("x-freehand", "fh", "fhc", "fh4", "fh5", "fh7");
    public static readonly Image Image_X_Icon = new("x-icon", "ico");
    public static readonly Image Image_X_Mrsid_Image = new("x-mrsid-image", "sid");
    public static readonly Image Image_X_Ms_Bmp = new("x-ms-bmp");
    public static readonly Image Image_X_Pcx = new("x-pcx", "pcx");
    public static readonly Image Image_X_Pict = new("x-pict", "pic", "pct");
    public static readonly Image Image_X_Portable_Anymap = new("x-portable-anymap", "pnm");
    public static readonly Image Image_X_Portable_Bitmap = new("x-portable-bitmap", "pbm");
    public static readonly Image Image_X_Portable_Graymap = new("x-portable-graymap", "pgm");
    public static readonly Image Image_X_Portable_Pixmap = new("x-portable-pixmap", "ppm");
    public static readonly Image Image_X_Rgb = new("x-rgb", "rgb");
    public static readonly Image Image_X_Tga = new("x-tga", "tga");

    [System.Obsolete("DEPRECATED in favor of image/wmf")]
    public static readonly Image Image_X_Wmf = new("x-wmf");

    public static readonly Image Image_X_Xbitmap = new("x-xbitmap", "xbm");
    public static readonly Image Image_X_Xcf = new("x-xcf");
    public static readonly Image Image_X_Xpixmap = new("x-xpixmap", "xpm");
    public static readonly Image Image_X_Xwindowdump = new("x-xwindowdump", "xwd");
}
