Juniper: Juniper.Units.Ratio Class Reference
Juniper.Units.Ratio Class Reference
Conversions from ratios. These conversions are only available for direct conversion, as they require two parameters.
Static Public Member Functions
static float Percent (float a, float b)
Convert a ratio of two numbers to a percentage.
static float Proportion (float a, float b)
Convert a ratio of two numbers to a proportion.
Detailed Description
Conversions from ratios. These conversions are only available for direct conversion, as they require two parameters.
Definition at line 9 of file Ratio.cs.
Member Function Documentation
Percent()
static float Juniper.Units.Ratio.Percent (float a, float b) inline static
Convert a ratio of two numbers to a percentage.
Parameters
a The amount to compare to b
b The amount that a is being compared to
Returns
The percentage of the whole that a represents
Definition at line 17 of file Ratio.cs.
             {
                 return Units.Proportion.Percent(Proportion(a, b));
             }
References Juniper.Units.Proportion.Percent(), and Juniper.Units.Ratio.Proportion().
Proportion()
static float Juniper.Units.Ratio.Proportion (float a, float b) inline static
Convert a ratio of two numbers to a proportion.
Parameters
a The amount to compare to b
b The amount that a is being compared to
Returns
The proportion of the whole that a represents
Definition at line 28 of file Ratio.cs.
             {
                 return a / (a + b);
             }
Referenced by Juniper.Units.Ratio.Percent().
The documentation for this class was generated from the following file:
Juniper.Units/src/Proportion/Ratio.cs