Juniper: System.IO.DirectoryExt Class Reference
System.IO.DirectoryExt Class Reference
Extension methods and helper functions for dealing with Directories.
Static Public Member Functions
static IEnumerable< string > RecurseFiles (string path)
Recurses through all subdirectories in a given directory to find all files contained within.
static IEnumerable< string > RecurseDirectories (string path)
Recurses through all subdirectories in a given directory to find all subdirectories contained within.
static bool TryDelete (string path)
Attempts to delete a directory, swallowing any errors along the way.
static void CreateDirectory (string dir)
Creates a directory, if the directory is semi-valid.
Detailed Description
Extension methods and helper functions for dealing with Directories.
Definition at line 8 of file DirectoryExt.cs.
Member Function Documentation
CreateDirectory()
static void System.IO.DirectoryExt.CreateDirectory (string dir) inline static
Creates a directory, if the directory is semi-valid.
Parameters
dir The directory name to create. This could be an absolute directory path or a path relative to the current working directory.
Definition at line 81 of file DirectoryExt.cs.
         {
             if (!string.IsNullOrWhiteSpace(dir))
             {
                 Directory.CreateDirectory(dir);
             }
         }
Referenced by System.IO.FileExt.Copy(), Juniper.Data.Zip.DecompressDirectory(), Juniper.Unity.Data.StreamingAssets.GetOrCacheFile(), and System.IO.FileExt.WriteAllText().
RecurseDirectories()
static IEnumerable<string> System.IO.DirectoryExt.RecurseDirectories (string path) inline static
Recurses through all subdirectories in a given directory to find all subdirectories contained within.
Parameters
path The parent directory to recurse.
Returns
A lazy collection of directory names in both path and all subdirectories of path .
Definition at line 36 of file DirectoryExt.cs.
         {
             var q = new Queue<string>() { path };
             while (q.Count > 0)
             {
                 var here = q.Dequeue();
                 foreach (var subDir in Directory.GetDirectories(here))
                 {
                     q.Enqueue(subDir);
                     yield return subDir;
                 }
             }
         }
RecurseFiles()
static IEnumerable<string> System.IO.DirectoryExt.RecurseFiles (string path) inline static
Recurses through all subdirectories in a given directory to find all files contained within.
Parameters
path The parent directory to recurse.
Returns
A lazy collection of filenames in both path and all subdirectories of path .
Definition at line 16 of file DirectoryExt.cs.
         {
             var q = new Queue<string>() { path };
             while (q.Count > 0)
             {
                 var here = q.Dequeue();
                 q.AddRange(Directory.GetDirectories(here));
                 foreach (var file in Directory.GetFiles(here))
                 {
                     yield return file;
                 }
             }
         }
TryDelete()
static bool System.IO.DirectoryExt.TryDelete (string path) inline static
Attempts to delete a directory, swallowing any errors along the way.
Parameters
path The directory to delete.
Returns
True, if the directory was deleted. False, if the directory doesn't exist or it couldn't be deleted (e.g. a process has a file-lock on a file within the directory).
Definition at line 59 of file DirectoryExt.cs.
         {
             if (Directory.Exists(path))
             {
                 try
                 {
                     Directory.Delete(path);
                     return true;
                 }
                 catch
                 {
                 }
             }
             return false;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Extensions/NETFX/IO/DirectoryExt.cs