Juniper: Juniper.Haptics.iOS10Haptics Class Reference
Juniper.Haptics.iOS10Haptics Class Reference
iOS 10 Taptic Feedback. /// How to Generate Haptic Feedback with UIFeedbackGenerator
Classes
class NativeMethods
Public Member Functions
void Awake ()
Initializes a new instance of the T:Juniper.Haptics.iOS10Haptics class.
override void Play (HapticExpression expr)
Play a canned haptic pattern.
override void Cancel ()
Cancel vibrationa
override void Play (params HapticPatternElement[] points)
Play a haptic pattern.
override void Play (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
override void Play (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
override void Vibrate (HapticPatternElement point)
Play a single element of a haptic pattern.
override void Vibrate (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
override void Vibrate (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
Protected Member Functions
override IEnumerator VibrateCoroutine (long milliseconds, float amplitude)
Playing arbitrary haptic patterns is not supported on iOS.
virtual IEnumerator VibrateCoroutine (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
virtual IEnumerator PlayCoroutine (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
virtual IEnumerator PlayCoroutine (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
Private Member Functions
void OnDestroy ()
Releases all resource used by the T:Juniper.Haptics.iOS10Haptics object.
Detailed Description
iOS 10 Taptic Feedback. /// How to Generate Haptic Feedback with UIFeedbackGenerator
Definition at line 11 of file iOS10Haptics.cs.
Member Function Documentation
Awake()
void Juniper.Haptics.iOS10Haptics.Awake ()
Initializes a new instance of the T:Juniper.Haptics.iOS10Haptics class.
Cancel()
override void Juniper.Haptics.AbstractHapticExpressor.Cancel () virtual inherited
Cancel vibrationa
Implements Juniper.Haptics.AbstractHapticDevice.
Reimplemented in Juniper.Haptics.DefaultHaptics, and Juniper.Haptics.AbstractAndroidAPIHaptics.
Referenced by Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine().
OnDestroy()
void Juniper.Haptics.iOS10Haptics.OnDestroy () private
Releases all resource used by the T:Juniper.Haptics.iOS10Haptics object.
Play() [1/4]
override void Juniper.Haptics.AbstractHapticExpressor.Play (params HapticPatternElement [] points) virtual inherited
Play a haptic pattern.
Parameters
points
Implements Juniper.Haptics.AbstractHapticDevice.
Play() [2/4]
override void Juniper.Haptics.iOS10Haptics.Play (HapticExpression expr) inline virtual
Play a canned haptic pattern.
Parameters
expr
Reimplemented from Juniper.Haptics.AbstractHapticExpressor.
Definition at line 46 of file iOS10Haptics.cs.
         {
             if (expr != HapticExpression.None)
             {
                 NativeMethods.PlayTaptic((uint)expr);
             }
         }
References Juniper.Haptics.iOS10Haptics.NativeMethods.PlayTaptic().
Play() [3/4]
override void Juniper.Haptics.AbstractHapticExpressor.Play (long [] pattern) virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Implements Juniper.Haptics.AbstractHapticDevice.
Play() [4/4]
override void Juniper.Haptics.AbstractHapticExpressor.Play (long [] pattern, float [] amplitudes) virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Implements Juniper.Haptics.AbstractHapticDevice.
PlayCoroutine() [1/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern) inline protected virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Reimplemented in Juniper.Haptics.AndroidAPI26Haptics, and Juniper.Haptics.AbstractAndroidAPIHaptics.
Definition at line 81 of file AbstractHapticExpressor.cs.
         {
             float amplitude = 1;
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitude);
                 amplitude = 1 - amplitude;
             }
         }
References Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
PlayCoroutine() [2/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine (long [] pattern, float [] amplitudes) inline protected virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Reimplemented in Juniper.Haptics.AndroidAPI26Haptics, and Juniper.Haptics.AndroidAPI1Haptics.
Definition at line 96 of file AbstractHapticExpressor.cs.
         {
             for (var i = 0; i < pattern.Length; ++i)
             {
                 yield return VibrateCoroutine(pattern[i], amplitudes[i]);
             }
         }
References Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [1/3]
override void Juniper.Haptics.AbstractHapticExpressor.Vibrate (HapticPatternElement point) virtual inherited
Play a single element of a haptic pattern.
Parameters
point
Implements Juniper.Haptics.AbstractHapticDevice.
Vibrate() [2/3]
override void Juniper.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds) virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Implements Juniper.Haptics.AbstractHapticDevice.
Vibrate() [3/3]
override void Juniper.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds, float amplitude) virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Haptics.AbstractHapticDevice.
VibrateCoroutine() [1/2]
override IEnumerator Juniper.Haptics.iOS9Haptics.VibrateCoroutine (long milliseconds, float amplitude) inline protected virtual inherited
Playing arbitrary haptic patterns is not supported on iOS.
Exceptions
T:System.NotImplementedException
Implements Juniper.Haptics.AbstractHapticExpressor.
Definition at line 17 of file iOS9Haptics.cs.
         {
             throw new NotImplementedException("Playing arbitrary haptic patterns is not supported on iOS.");
         }
VibrateCoroutine() [2/2]
virtual IEnumerator Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine (long milliseconds) inline protected virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Reimplemented in Juniper.Haptics.AndroidAPI26Haptics, and Juniper.Haptics.AbstractAndroidAPIHaptics.
Definition at line 72 of file AbstractHapticExpressor.cs.
         {
             yield return VibrateCoroutine(milliseconds, 1);
         }
Referenced by Juniper.Haptics.AbstractHapticExpressor.PlayCoroutine(), and Juniper.Haptics.AbstractHapticExpressor.VibrateCoroutine().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/iOS/iOS10Haptics.cs