Juniper: Juniper.ImageTracking.AbstractTrackerKeeper Class Reference
Juniper.ImageTracking.AbstractTrackerKeeper Class Reference
Public Member Functions
AbstractTrackableFoundEventHandler Register (AbstractTrackableFoundEventHandler target)
Register's a target and its events for the aggregated events issued by TrackerKeeper.
virtual void Update ()
Checks the current tracking status and fires the events to indicate any change in the tracking status.
void OnDestroy ()
Tears down the tracker keeper.
void StartTracker ()
Starts the tracker without changing any dataset data that has already been configured.
void StartTrackerWithDataSet (string dataSetName)
Initializes tracking of a set of targets.
void StartTrackerWithDataSetForTarget (string dataSetName, string targetName)
Initializes tracking of a specific target.
Public Attributes
bool DebugReport
Set to true to print out a debug report on the screen.
UnityEvent onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
UnityEvent onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
UnityEvent onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
UnityEvent onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
UnityEvent onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
TransformEvent onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
TransformEvent onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
UnityEvent onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
TransformEvent onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
TransformEvent onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Protected Member Functions
virtual void Start ()
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
virtual void OnTrackingStarting (string dataSetName, string targetName)
virtual void OnTrackingStarted ()
virtual void OnTrackingStopping ()
virtual void OnTrackingStopped ()
virtual void PrintDebugReport ()
Protected Attributes
readonly List< AbstractTrackableFoundEventHandler > targets = new List<AbstractTrackableFoundEventHandler>(10)
All of the targets in the system.
Properties
bool Tracking [get, protected set]
Is set to true when the tracking system is initialized and running.
bool TargetFound [get]
Returns true when any target has been found and is tracking.
virtual IEnumerable< TrackableFoundEventHandler > FirstTargets [get]
bool HasTargets [get]
Returns true when there are any GoodTargets.
bool Safe [get]
This value is set to true when the user is at a safe distance from the target.
Private Member Functions
UnityAction TargetFinder (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetProximity (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetSafe (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle finding a given target.
UnityAction TargetLoser (AbstractTrackableFoundEventHandler target)
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
void OnAllTargetsLost ()
Triggers the onAllTargetsLost event.
void StartTrackerDelayed ()
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
Private Attributes
bool hadAnyTargets
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
bool wasTracking
The value of Tracking from the previous frame, to detect changes.
bool done
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
DisplayManager xr
Detailed Description
Definition at line 27 of file TrackerKeeper.cs.
Member Function Documentation
OnAllTargetsLost()
void Juniper.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost () inline private
Triggers the onAllTargetsLost event.
Definition at line 329 of file TrackerKeeper.cs.
         {
             if (Tracking)
             {
                 onAllTargetsLost?.Invoke();
             }
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.onAllTargetsLost, and Juniper.ImageTracking.AbstractTrackerKeeper.Tracking.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.ImageTracking.AbstractTrackerKeeper.TargetLoser(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
OnDestroy()
void Juniper.ImageTracking.AbstractTrackerKeeper.OnDestroy () inline
Tears down the tracker keeper.
Definition at line 245 of file TrackerKeeper.cs.
         {
             done = true;
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.done.
OnTrackingStarted()
virtual void Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStarted () inline protected virtual
Definition at line 180 of file TrackerKeeper.cs.
         {
             onTrackingStarted?.Invoke();
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStarted.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Update().
OnTrackingStarting()
virtual void Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting (string dataSetName, string targetName) inline protected virtual
Reimplemented in Juniper.ImageTracking.ARKitTrackerKeeper.
Definition at line 175 of file TrackerKeeper.cs.
         {
             onTrackingStarting?.Invoke();
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStarting.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
OnTrackingStopped()
virtual void Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStopped () inline protected virtual
Definition at line 190 of file TrackerKeeper.cs.
         {
             onTrackingStopped?.Invoke();
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStopped.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Update().
OnTrackingStopping()
virtual void Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStopping () inline protected virtual
Definition at line 185 of file TrackerKeeper.cs.
         {
             onTrackingStopping?.Invoke();
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStopping.
PrintDebugReport()
virtual void Juniper.ImageTracking.AbstractTrackerKeeper.PrintDebugReport () inline protected virtual
Definition at line 195 of file TrackerKeeper.cs.
         {
         }
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Update().
Register()
AbstractTrackableFoundEventHandler Juniper.ImageTracking.AbstractTrackerKeeper.Register (AbstractTrackableFoundEventHandler target) inline
Register's a target and its events for the aggregated events issued by TrackerKeeper.
Parameters
target Target.
Definition at line 161 of file TrackerKeeper.cs.
         {
             if (targets?.Contains(target) == false)
             {
                 targets.Add(target);
                 target.onFound.AddListener(TargetFinder(target));
                 target.onLost.AddListener(TargetLoser(target));
                 target.onProximity.AddListener(TargetProximity(target));
                 target.onSafe.AddListener(TargetSafe(target));
             }
             return target;
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onFound, Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onLost, Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onProximity, Juniper.ImageTracking.AbstractTrackableFoundEventHandler.onSafe, Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.ImageTracking.AbstractTrackerKeeper.TargetLoser(), Juniper.ImageTracking.AbstractTrackerKeeper.TargetProximity(), Juniper.ImageTracking.AbstractTrackerKeeper.targets, and Juniper.ImageTracking.AbstractTrackerKeeper.TargetSafe().
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Start().
Start()
virtual void Juniper.ImageTracking.AbstractTrackerKeeper.Start () inline protected virtual
Finds all of the targetable objects and makes sure they all have TrackableFoundEventHandler s, wiring up the onFound and onLost events of each.
Reimplemented in Juniper.ImageTracking.ARKitTrackerKeeper.
Definition at line 147 of file TrackerKeeper.cs.
         {
             Find.Any(out xr);
             foreach (var target in FirstTargets.Distinct())
             {
                 Register(target);
             }
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.FirstTargets, Juniper.ImageTracking.AbstractTrackerKeeper.Register(), and Juniper.ImageTracking.AbstractTrackerKeeper.xr.
StartTracker()
void Juniper.ImageTracking.AbstractTrackerKeeper.StartTracker () inline
Starts the tracker without changing any dataset data that has already been configured.
Definition at line 378 of file TrackerKeeper.cs.
         {
             Invoke(nameof(StartTrackerDelayed), 1);
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed().
StartTrackerDelayed()
void Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed () inline private
Starts the tracker without changing any dataset data that has already been configured. This method is the target of StartTracker to start after a second of delay to allow the camera feed to catch up.
Definition at line 388 of file TrackerKeeper.cs.
         {
             StartTrackerWithDataSetForTarget(null, null);
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.StartTracker().
StartTrackerWithDataSet()
void Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSet (string dataSetName) inline
Initializes tracking of a set of targets.
Parameters
dataSetName Data set name.
Definition at line 397 of file TrackerKeeper.cs.
         {
             ScreenDebugger.Print($"Activating data set: {dataSetName}");
             StartTrackerWithDataSetForTarget(dataSetName, null);
         }
References System.ScreenDebugger.Print(), and Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
StartTrackerWithDataSetForTarget()
void Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget (string dataSetName, string targetName) inline
Initializes tracking of a specific target.
Parameters
dataSetName Data set name.
targetName Target name.
Definition at line 408 of file TrackerKeeper.cs.
         {
             OnTrackingStarting(dataSetName, targetName);
             Update();
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
Referenced by Juniper.ImageTracking.ARKitTrackerKeeper.Start(), Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerDelayed(), and Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSet().
TargetFinder()
UnityAction Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Definition at line 255 of file TrackerKeeper.cs.
         {
             return () =>
             {
                 CancelInvoke(nameof(OnAllTargetsLost));
                 if (HasTargets && !hadAnyTargets && Tracking)
                 {
                     onAnyTargetFound?.Invoke();
                 }
                 onTargetFound?.Invoke(target.transform);
                 foreach (var otherTarget in targets)
                 {
                     if (otherTarget != target && otherTarget.Found)
                     {
                         otherTarget.ForceLost();
                     }
                 }
                 hadAnyTargets = HasTargets;
             };
         }
References Juniper.ImageTracking.AbstractTrackableFoundEventHandler.Found, Juniper.ImageTracking.AbstractTrackerKeeper.hadAnyTargets, Juniper.ImageTracking.AbstractTrackerKeeper.HasTargets, Juniper.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), Juniper.ImageTracking.AbstractTrackerKeeper.onAnyTargetFound, Juniper.ImageTracking.AbstractTrackerKeeper.onTargetFound, Juniper.ImageTracking.AbstractTrackerKeeper.targets, and Juniper.ImageTracking.AbstractTrackerKeeper.Tracking.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Register().
TargetLoser()
UnityAction Juniper.ImageTracking.AbstractTrackerKeeper.TargetLoser (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle losing a given target. The event handler will fire the targetChanged event if the lost target was the CurrentTarget. If losing this target means that there are no tracked targets, then the onAllTargetsLost event is fired. Finally, Vuforia's Persistent Extended Tracking is reset, if it was active.
Returns
The loser.
Parameters
target Target.
Definition at line 309 of file TrackerKeeper.cs.
         {
             return () =>
             {
                 onTargetLost?.Invoke(target.transform);
                 if (!HasTargets && hadAnyTargets)
                 {
                     hadAnyTargets = HasTargets;
                     if (!done)
                     {
                         Invoke(nameof(OnAllTargetsLost), 1);
                     }
                 }
             };
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.done, Juniper.ImageTracking.AbstractTrackerKeeper.hadAnyTargets, Juniper.ImageTracking.AbstractTrackerKeeper.HasTargets, Juniper.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), and Juniper.ImageTracking.AbstractTrackerKeeper.onTargetLost.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Register().
TargetProximity()
UnityAction Juniper.ImageTracking.AbstractTrackerKeeper.TargetProximity (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Definition at line 285 of file TrackerKeeper.cs.
         {
             return () => onTargetProximity.Invoke(target.transform);
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.onTargetProximity.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Register().
TargetSafe()
UnityAction Juniper.ImageTracking.AbstractTrackerKeeper.TargetSafe (AbstractTrackableFoundEventHandler target) inline private
Creates an event handler that can handle finding a given target.
Returns
The finder.
Parameters
target Target.
Definition at line 295 of file TrackerKeeper.cs.
         {
             return () => onTargetSafe.Invoke(target.transform);
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.onTargetSafe.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Register().
Update()
virtual void Juniper.ImageTracking.AbstractTrackerKeeper.Update () inline virtual
Checks the current tracking status and fires the events to indicate any change in the tracking status.
Definition at line 203 of file TrackerKeeper.cs.
         {
             if (Tracking && !wasTracking)
             {
                 xr.StartAR();
                 OnTrackingStarted();
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         target.onFound?.Invoke();
                         if (!target.Safe)
{
                             target.onProximity?.Invoke();
                         }
                     }
                 }
                 if (targets.All(target => !target.Found))
                 {
                     OnAllTargetsLost();
                 }
             }
             else if (!Tracking && wasTracking)
             {
                 xr.StopAR();
                 OnTrackingStopped();
             }
             wasTracking = Tracking;
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.ImageTracking.AbstractTrackerKeeper.DebugReport, Juniper.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStarted(), Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStopped(), Juniper.ImageTracking.AbstractTrackerKeeper.PrintDebugReport(), Juniper.Display.AbstractDisplayManager.StartAR(), Juniper.Display.AbstractDisplayManager.StopAR(), Juniper.ImageTracking.AbstractTrackerKeeper.targets, Juniper.ImageTracking.AbstractTrackerKeeper.Tracking, Juniper.ImageTracking.AbstractTrackerKeeper.wasTracking, and Juniper.ImageTracking.AbstractTrackerKeeper.xr.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.StartTrackerWithDataSetForTarget().
Member Data Documentation
DebugReport
bool Juniper.ImageTracking.AbstractTrackerKeeper.DebugReport
Set to true to print out a debug report on the screen.
Definition at line 56 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Update().
done
bool Juniper.ImageTracking.AbstractTrackerKeeper.done private
Gets set to true when the application is shutting down, to prevent the invocation of any methods.
Definition at line 61 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.OnDestroy(), and Juniper.ImageTracking.AbstractTrackerKeeper.TargetLoser().
hadAnyTargets
bool Juniper.ImageTracking.AbstractTrackerKeeper.hadAnyTargets private
When true, indicates that targets where available and tracked on the previous frame. Used to detect when all targets have been lost.
Definition at line 33 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.ImageTracking.AbstractTrackerKeeper.TargetLoser().
onAllTargetsLost
UnityEvent Juniper.ImageTracking.AbstractTrackerKeeper.onAllTargetsLost = new UnityEvent()
A UnityEvent that occurs when all targets have been lost. If more than one target is currently being tracked, this event will not fire until all of them are lost.
Definition at line 121 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost().
onAnyTargetFound
UnityEvent Juniper.ImageTracking.AbstractTrackerKeeper.onAnyTargetFound = new UnityEvent()
A Unity Event that occurs when the first target is found, after having no targets tracked. This event does not fire if any subsequent targets are found.
Definition at line 105 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onTargetFound
TransformEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTargetFound = new TransformEvent()
A Unity Event that occurs every time any target is found.
Definition at line 110 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder().
onTargetLost
TransformEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTargetLost = new TransformEvent()
A Unity Event that occurs every time any target is lost.
Definition at line 115 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetLoser().
onTargetProximity
TransformEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTargetProximity = new TransformEvent()
A UnityEvent that occurs when the user gets too close to a target.
Definition at line 131 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetProximity().
onTargetSafe
TransformEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTargetSafe = new TransformEvent()
A UnityEvent that occurs when the user is at a safe distance from the target.
Definition at line 126 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetSafe().
onTrackingStarted
UnityEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStarted = new UnityEvent()
A Unity Event that occurs when the tracking system has been initialized and started.
Definition at line 89 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStarted().
onTrackingStarting
UnityEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStarting = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be initialized. and started.
Definition at line 84 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStarting().
onTrackingStopped
UnityEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStopped = new UnityEvent()
A Unity Event that occurs when the tracking system has been shut down.
Definition at line 99 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStopped().
onTrackingStopping
UnityEvent Juniper.ImageTracking.AbstractTrackerKeeper.onTrackingStopping = new UnityEvent()
A Unity Event that occurs when the tracking system is about to be shut down. and started.
Definition at line 94 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.OnTrackingStopping().
targets
readonly List<AbstractTrackableFoundEventHandler> Juniper.ImageTracking.AbstractTrackerKeeper.targets = new List<AbstractTrackableFoundEventHandler>(10) protected
All of the targets in the system.
Definition at line 38 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Register(), Juniper.ImageTracking.ARKitTrackerKeeper.Start(), Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
wasTracking
bool Juniper.ImageTracking.AbstractTrackerKeeper.wasTracking private
The value of Tracking from the previous frame, to detect changes.
Definition at line 51 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Update().
xr
DisplayManager Juniper.ImageTracking.AbstractTrackerKeeper.xr private
Definition at line 133 of file TrackerKeeper.cs.
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Start(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
Property Documentation
FirstTargets
virtual IEnumerable<TrackableFoundEventHandler> Juniper.ImageTracking.AbstractTrackerKeeper.FirstTargets get protected
Definition at line 136 of file TrackerKeeper.cs.
         {
             get
             {
                 return Find.All<TrackableFoundEventHandler>();
             }
         }
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.Start().
HasTargets
bool Juniper.ImageTracking.AbstractTrackerKeeper.HasTargets get
Returns true when there are any GoodTargets.
true if has targets; otherwise, false.
Definition at line 342 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder(), and Juniper.ImageTracking.AbstractTrackerKeeper.TargetLoser().
Safe
bool Juniper.ImageTracking.AbstractTrackerKeeper.Safe get
This value is set to true when the user is at a safe distance from the target.
Definition at line 360 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found && !target.Safe)
                     {
                         return false;
                     }
                 }
                 return true;
             }
         }
TargetFound
bool Juniper.ImageTracking.AbstractTrackerKeeper.TargetFound get
Returns true when any target has been found and is tracking.
Definition at line 67 of file TrackerKeeper.cs.
         {
             get
             {
                 foreach (var target in targets)
                 {
                     if (target.Found)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Tracking
bool Juniper.ImageTracking.AbstractTrackerKeeper.Tracking get protected set
Is set to true when the tracking system is initialized and running.
Definition at line 44 of file TrackerKeeper.cs.
         {
             get; protected set;
         }
Referenced by Juniper.ImageTracking.AbstractTrackerKeeper.OnAllTargetsLost(), Juniper.ImageTracking.ARKitTrackerKeeper.OnTrackingStarting(), Juniper.ImageTracking.AbstractTrackerKeeper.TargetFinder(), Juniper.ImageTracking.AbstractTrackerKeeper.Update(), and Juniper.ImageTracking.ARKitTrackerKeeper.WithTarget().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/ImageTracking/TrackerKeeper.cs