Juniper: UnityEngine.Find Class Reference
UnityEngine.Find Class Reference
Static Public Member Functions
static T Any< T > (Func< T, bool > filter)
Find any object in any scene that is of a certain type.
static bool Any< T > (Func< T, bool > filter, out T value)
static T Any< T > ()
Find any object in any scene that is of a certain type.
static bool Any< T > (out T value)
static T FindClosest< T > (this Component obj)
Find a component that is loosely related to another component.
static bool FindClosest< T > (this Component obj, out T value)
static IEnumerable< T > All< T > ()
Find all objects in any scene that is of a certain type.
static void All< T > (ref List< T > container)
static IEnumerable< T > All< T > (Func< T, bool > filter)
Find all objects in any scene that is of a certain type.
static void All< T > (Func< T, bool > filter, ref List< T > container)
Find all objects in any scene that is of a certain type.
static IEnumerable< T > FindAll< T > (this Scene scene)
Find all objects in the specified scene that is of a certain type.
static void FindAll< T > (this Scene scene, ref List< T > container)
static IEnumerable< T > FindAll< T > (this Scene scene, Func< T, bool > filter)
Find all objects in the specified scene that is of a certain type.
static void FindAll< T > (this Scene scene, Func< T, bool > filter, ref List< T > container)
Detailed Description
Definition at line 9 of file Find.cs.
Member Function Documentation
All< T >() [1/4]
static IEnumerable<T> UnityEngine.Find.All< T > () inline static
Find all objects in any scene that is of a certain type.
Template Parameters
T
Returns
Definition at line 93 of file Find.cs.
         {
             var objs = Resources.FindObjectsOfTypeAll<Object>();
             for (var i = 0; i < objs.Length; ++i)
             {
                 var o = objs[i];
                 if (o is T obj)
                 {
                     yield return obj;
                 }
             }
         }
Referenced by UnityEngine.Find.All< T >(), and UnityEngine.Find.Any< T >().
All< T >() [2/4]
static void UnityEngine.Find.All< T > (ref List< T > container) inline static
Definition at line 106 of file Find.cs.
         {
             if (container == null)
             {
                 container = new List<T>();
             }
             container.AddRange(All<T>());
         }
References UnityEngine.Find.All< T >().
All< T >() [3/4]
static IEnumerable<T> UnityEngine.Find.All< T > (Func< T, bool > filter) inline static
Find all objects in any scene that is of a certain type.
Template Parameters
T
Parameters
filter
Returns
Definition at line 121 of file Find.cs.
         {
             foreach (var obj in All<T>())
             {
                 if (filter(obj))
                 {
                     yield return obj;
                 }
             }
         }
References UnityEngine.Find.All< T >().
All< T >() [4/4]
static void UnityEngine.Find.All< T > (Func< T, bool > filter, ref List< T > container) inline static
Find all objects in any scene that is of a certain type.
Template Parameters
T
Parameters
filter
Returns
Definition at line 138 of file Find.cs.
         {
             if (container == null)
             {
                 container = new List<T>();
             }
             container.AddRange(All(filter));
         }
Any< T >() [1/4]
static T UnityEngine.Find.Any< T > (Func< T, bool > filter) inline static
Find any object in any scene that is of a certain type.
Template Parameters
T
Parameters
filter
Returns
Definition at line 18 of file Find.cs.
         {
             return All(filter).FirstOrDefault();
         }
Any< T >() [2/4]
static bool UnityEngine.Find.Any< T > (Func< T, bool > filter, out T value) inline static
Type Constraints
T : class
Definition at line 23 of file Find.cs.
                     : class
         {
             value = Any(filter);
             return value != default;
         }
Any< T >() [3/4]
static T UnityEngine.Find.Any< T > () inline static
Find any object in any scene that is of a certain type.
Template Parameters
T
Returns
Definition at line 35 of file Find.cs.
         {
             return All<T>().FirstOrDefault();
         }
References UnityEngine.Find.All< T >().
Referenced by UnityEngine.Find.Any< T >(), and UnityEngine.Find.FindClosest< T >().
Any< T >() [4/4]
static bool UnityEngine.Find.Any< T > (out T value) inline static
Type Constraints
T : class
Definition at line 40 of file Find.cs.
                     : class
         {
             value = Any<T>();
             return value != default;
         }
References UnityEngine.Find.Any< T >().
FindAll< T >() [1/4]
static IEnumerable<T> UnityEngine.Find.FindAll< T > (this Scene scene) inline static
Find all objects in the specified scene that is of a certain type.
Template Parameters
T
Parameters
scene
Returns
Definition at line 153 of file Find.cs.
         {
             if (scene.isLoaded || !string.IsNullOrEmpty(scene.name))
             {
                 foreach (var o in scene.GetRootGameObjects())
                 {
                     foreach (var c in o.GetComponentsInChildren<T>(true))
                     {
                         yield return c;
                     }
                 }
             }
         }
FindAll< T >() [2/4]
static void UnityEngine.Find.FindAll< T > (this Scene scene, ref List< T > container) inline static
Definition at line 167 of file Find.cs.
         {
             if (container == null)
             {
                 container = new List<T>();
             }
             container.AddRange(scene.FindAll<T>());
         }
FindAll< T >() [3/4]
static IEnumerable<T> UnityEngine.Find.FindAll< T > (this Scene scene, Func< T, bool > filter) inline static
Find all objects in the specified scene that is of a certain type.
Template Parameters
T
Parameters
scene
filter
Returns
Definition at line 183 of file Find.cs.
         {
             foreach (var c in scene.FindAll<T>())
             {
                 if (filter(c))
                 {
                     yield return c;
                 }
             }
         }
FindAll< T >() [4/4]
static void UnityEngine.Find.FindAll< T > (this Scene scene, Func< T, bool > filter, ref List< T > container) inline static
Definition at line 194 of file Find.cs.
         {
             if (container == null)
             {
                 container = new List<T>();
             }
             container.AddRange(scene.FindAll(filter));
         }
FindClosest< T >() [1/2]
static T UnityEngine.Find.FindClosest< T > (this Component obj) inline static
Find a component that is loosely related to another component.
Template Parameters
T
Parameters
obj
Returns
Type Constraints
T : class
Definition at line 53 of file Find.cs.
                     : class
         {
             if (obj is null)
             {
                 throw new ArgumentNullException(nameof(obj));
             }
             var v = obj.GetComponent<T>();
             if (v == default)
             {
                 obj.GetComponentInChildren<T>();
             }
             if (v == default)
             {
                 v = obj.GetComponentInParent<T>();
             }
             if (v == default)
             {
                 v = Any<T>();
             }
             return v;
         }
References UnityEngine.Find.Any< T >().
FindClosest< T >() [2/2]
static bool UnityEngine.Find.FindClosest< T > (this Component obj, out T value) inline static
Type Constraints
T : class
Definition at line 81 of file Find.cs.
                     : class
         {
             value = obj.FindClosest<T>();
             return value != default;
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Unity/Extensions/UnityEngine/Find.cs