Juniper: Juniper.Unity.AbstractPermissionHandler Class Reference
Juniper.Unity.AbstractPermissionHandler Class Reference
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Public Member Functions
void Awake ()
virtual void Reinstall ()
void Reset ()
virtual bool Install (bool reset)
virtual void Uninstall ()
Detailed Description
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Definition at line 8 of file AbstractPermissionHandler.cs.
Member Function Documentation
Awake()
void Juniper.Unity.AbstractPermissionHandler.Awake () inline
Definition at line 10 of file AbstractPermissionHandler.cs.
         {
             Install(false);
         }
References Juniper.Unity.AbstractPermissionHandler.Install().
Install()
virtual bool Juniper.Unity.AbstractPermissionHandler.Install (bool reset) inline virtual
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.iOSPermissionHandler.
Definition at line 27 of file AbstractPermissionHandler.cs.
         {
             return true;
         }
Referenced by Juniper.Unity.AbstractPermissionHandler.Awake(), and Juniper.Unity.AbstractPermissionHandler.Reinstall().
Reinstall()
virtual void Juniper.Unity.AbstractPermissionHandler.Reinstall () inline virtual
Implements Juniper.IInstallable.
Definition at line 15 of file AbstractPermissionHandler.cs.
         {
             Install(true);
         }
References Juniper.Unity.AbstractPermissionHandler.Install().
Referenced by Juniper.Unity.AbstractPermissionHandler.Reset().
Reset()
void Juniper.Unity.AbstractPermissionHandler.Reset () inline
Definition at line 21 of file AbstractPermissionHandler.cs.
         {
             Reinstall();
         }
References Juniper.Unity.AbstractPermissionHandler.Reinstall().
Uninstall()
virtual void Juniper.Unity.AbstractPermissionHandler.Uninstall () inline virtual
Implements Juniper.IInstallable.
Definition at line 32 of file AbstractPermissionHandler.cs.
         {
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/AbstractPermissionHandler.cs