Juniper: Juniper.Logic.LogicConstructor Class Reference
Juniper.Logic.LogicConstructor Class Reference
Static Public Member Functions
static IExpression< ItemT > Empty< ItemT > ()
static IExpression< ItemT > Expr< ItemT > (ItemT value)
static IExpression< ItemT > Not< ItemT > (IExpression< ItemT > expr)
static IExpression< ItemT > Not< ItemT > (ItemT item)
static IExpression< ItemT > And< ItemT > (IEnumerable< IExpression< ItemT >> exprs)
static IExpression< ItemT > And< ItemT > (params IExpression< ItemT >[] exprs)
static IExpression< ItemT > And< ItemT > (IEnumerable< ItemT > items)
static IExpression< ItemT > And< ItemT > (params ItemT[] items)
static IExpression< ItemT > Or< ItemT > (IEnumerable< IExpression< ItemT >> exprs)
static IExpression< ItemT > Or< ItemT > (params IExpression< ItemT >[] exprs)
static IExpression< ItemT > Or< ItemT > (IEnumerable< ItemT > items)
static IExpression< ItemT > Or< ItemT > (params ItemT[] items)
static IExpression< ItemT > Xor< ItemT > (IEnumerable< IExpression< ItemT >> exprs)
static IExpression< ItemT > Xor< ItemT > (params IExpression< ItemT >[] exprs)
static IExpression< ItemT > Xor< ItemT > (IEnumerable< ItemT > items)
static IExpression< ItemT > Xor< ItemT > (params ItemT[] items)
Static Private Member Functions
static IEnumerable< IExpression< ItemT > > Exprs< ItemT > (IEnumerable< ItemT > items)
Detailed Description
Definition at line 6 of file LogicConstructor.cs.
Member Function Documentation
And< ItemT >() [1/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.And< ItemT > (IEnumerable< IExpression< ItemT >> exprs) inline static
Definition at line 35 of file LogicConstructor.cs.
         {
             if (exprs is null)
             {
                 throw new System.ArgumentNullException(nameof(exprs));
             }
             IExpression<ItemT> expr = null;
             var count = 0;
             foreach (var x in exprs)
             {
                 if (expr is null)
                 {
                     expr = x;
                 }
                 else
                 {
                     expr = new AndExpression<ItemT>(expr, x);
                 }
                 ++count;
             }
             return expr ?? Empty<ItemT>();
         }
References Juniper.Logic.LogicConstructor.Empty< ItemT >().
And< ItemT >() [2/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.And< ItemT > (params IExpression< ItemT > [] exprs) inline static
Definition at line 60 of file LogicConstructor.cs.
         {
             return And((IEnumerable<IExpression<ItemT>>)exprs);
         }
And< ItemT >() [3/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.And< ItemT > (IEnumerable< ItemT > items) inline static
Definition at line 65 of file LogicConstructor.cs.
         {
             return And(Exprs(items));
         }
And< ItemT >() [4/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.And< ItemT > (params ItemT [] items) inline static
Definition at line 70 of file LogicConstructor.cs.
         {
             return And((IEnumerable<ItemT>)items);
         }
Empty< ItemT >()
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Empty< ItemT > () inline static
Definition at line 8 of file LogicConstructor.cs.
         {
             return new EmptyExpression<ItemT>();
         }
Referenced by Juniper.Logic.LogicConstructor.And< ItemT >(), Juniper.Logic.LogicConstructor.Or< ItemT >(), and Juniper.Logic.LogicConstructor.Xor< ItemT >().
Expr< ItemT >()
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Expr< ItemT > (ItemT value) inline static
Definition at line 13 of file LogicConstructor.cs.
         {
             return new ItemExpression<ItemT>(value);
         }
Exprs< ItemT >()
static IEnumerable<IExpression<ItemT> > Juniper.Logic.LogicConstructor.Exprs< ItemT > (IEnumerable< ItemT > items) inline static private
Definition at line 18 of file LogicConstructor.cs.
         {
             return items
                 .Select(Expr)
                 .ToArray();
         }
Not< ItemT >() [1/2]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Not< ItemT > (IExpression< ItemT > expr) inline static
Definition at line 25 of file LogicConstructor.cs.
         {
             return new NotExpression<ItemT>(expr);
         }
Not< ItemT >() [2/2]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Not< ItemT > (ItemT item) inline static
Definition at line 30 of file LogicConstructor.cs.
         {
             return Not(Expr(item));
         }
Or< ItemT >() [1/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Or< ItemT > (IEnumerable< IExpression< ItemT >> exprs) inline static
Definition at line 75 of file LogicConstructor.cs.
         {
             if (exprs is null)
             {
                 throw new System.ArgumentNullException(nameof(exprs));
             }
             IExpression<ItemT> expr = null;
             var count = 0;
             foreach (var x in exprs)
             {
                 if (expr is null)
                 {
                     expr = x;
                 }
                 else
                 {
                     expr = new OrExpression<ItemT>(expr, x);
                 }
                 ++count;
             }
             return expr ?? Empty<ItemT>();
         }
References Juniper.Logic.LogicConstructor.Empty< ItemT >().
Or< ItemT >() [2/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Or< ItemT > (params IExpression< ItemT > [] exprs) inline static
Definition at line 100 of file LogicConstructor.cs.
         {
             return Or((IEnumerable<IExpression<ItemT>>)exprs);
         }
Or< ItemT >() [3/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Or< ItemT > (IEnumerable< ItemT > items) inline static
Definition at line 105 of file LogicConstructor.cs.
         {
             return Or(Exprs(items));
         }
Or< ItemT >() [4/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Or< ItemT > (params ItemT [] items) inline static
Definition at line 110 of file LogicConstructor.cs.
         {
             return Or((IEnumerable<ItemT>)items);
         }
Xor< ItemT >() [1/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Xor< ItemT > (IEnumerable< IExpression< ItemT >> exprs) inline static
Definition at line 115 of file LogicConstructor.cs.
         {
             if (exprs is null)
             {
                 throw new System.ArgumentNullException(nameof(exprs));
             }
             IExpression<ItemT> expr = null;
             var count = 0;
             foreach (var x in exprs)
             {
                 if (expr is null)
                 {
                     expr = x;
                 }
                 else
                 {
                     expr = new XorExpression<ItemT>(expr, x);
                 }
                 ++count;
             }
             return expr ?? Empty<ItemT>();
         }
References Juniper.Logic.LogicConstructor.Empty< ItemT >().
Xor< ItemT >() [2/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Xor< ItemT > (params IExpression< ItemT > [] exprs) inline static
Definition at line 140 of file LogicConstructor.cs.
         {
             return Xor((IEnumerable<IExpression<ItemT>>)exprs);
         }
Xor< ItemT >() [3/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Xor< ItemT > (IEnumerable< ItemT > items) inline static
Definition at line 145 of file LogicConstructor.cs.
         {
             return Xor(Exprs(items));
         }
Xor< ItemT >() [4/4]
static IExpression<ItemT> Juniper.Logic.LogicConstructor.Xor< ItemT > (params ItemT [] items) inline static
Definition at line 150 of file LogicConstructor.cs.
         {
             return Xor((IEnumerable<ItemT>)items);
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Logic/LogicConstructor.cs