Juniper: Juniper.Unity.Widgets.AttentionDirector Class Reference
Juniper.Unity.Widgets.AttentionDirector Class Reference
Shows a pointer that directs the user to where to look next.
Public Member Functions
void Play (string anim)
Play one of the animations on the attention director.
void Awake ()
Get the pointer graphic objects, the main camera, the animator, and the main view system. Disable the graphics for the pointer.
void Scan (Action onFound=null)
Executes an animation that tells the user that they should be searching for a target.
IEnumerator ScanCoroutine (Action onFound=null)
Executes an animation that tells the user that they should be searching for a target.
void Found ()
Executes an animation and a sound indicatingn to the user that the target has been found.
IEnumerator FoundCoroutine ()
Executes an animation and a sound indicating to the user that the target has been found.
void Lost ()
Executes an animation and a sound indicating to the user that the target has been lost.
IEnumerator LostCoroutine ()
Executes an animation and a sound indicating to the user that the target has been lost.
IEnumerator SetTargetCoroutine (Component target)
Set the attenion director to targeting a specific object, withouth showing the optional center image.
void SetTarget (Component target, Action onTargetFound)
Set the attenion director to targeting a specific object, withouth showing the optional center image.
void Update ()
Updates the pointer graphics if the option to show them has changed, and checks to see how close we are to the target, updating the location of the arrow graphic if we haven't found it yet, or activating the callback function if we have.
Public Attributes
float shrinkSpeed = 0.5f
How quickly the object should vanish away
float minDistance = 0.01f
The threshold at which to consider an object "in view"
Properties
Vector3 Target [get]
The point we are trying to find with the attention director.
Private Attributes
Action onTargetFound
The callback to execute when the target is found.
Transform targetTrans
The optional object we are targeting.
Transform lastTargetTrans
The object we were targeting in the last frame.
Vector3 targetPos
The position in space that we are targeting, if there is no distinct target object.
Vector3 lastTargetPosition
The position in space that we were targeting last frame.
Transform pointer
The pointer graphic.
Transform arrow
The arrow on the edge of the pointer graphic, pointer the user to the direction to turn.
Vector3 tagRange
The offset from the center at which the arrow is located.
Transform image
An optional image to display in the center of the attention director. Maybe use it for displaying instructions to the user the first time they see the attention director.
bool showImage
Whether or not to show the optional center image.
bool showPointer
Whether or not to show the pointer graphic at all.
bool wasShowImage
Whether or not the optional center image was visible in the last frame.
bool wasShowPointer
Whether or not the pointer graphic was visible in the last frame.
AbstractAnimator animator
An optional animation object to show different attention director states.
Detailed Description
Shows a pointer that directs the user to where to look next.
Definition at line 24 of file AttentionDirector.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Widgets.AttentionDirector.Awake () inline
Get the pointer graphic objects, the main camera, the animator, and the main view system. Disable the graphics for the pointer.
Definition at line 80 of file AttentionDirector.cs.
         {
             pointer = transform.Find("Pointer");
             arrow = pointer.Find("Tag");
             tagRange = arrow.localPosition;
             image = transform.Find("Image");
 #if UNITY_MODULES_ANIMATION
             animator = this.Ensure<UnityAnimator>();
 #endif
             pointer.SetActive(false);
             image.SetActive(false);
         }
References Juniper.Unity.Widgets.AttentionDirector.animator, Juniper.Unity.Widgets.AttentionDirector.arrow, Juniper.Unity.Widgets.AttentionDirector.image, Juniper.Unity.Widgets.AttentionDirector.pointer, and Juniper.Unity.Widgets.AttentionDirector.tagRange.
Found()
void Juniper.Unity.Widgets.AttentionDirector.Found () inline
Executes an animation and a sound indicatingn to the user that the target has been found.
Definition at line 119 of file AttentionDirector.cs.
         {
             StartCoroutine(FoundCoroutine());
         }
References Juniper.Unity.Widgets.AttentionDirector.FoundCoroutine().
FoundCoroutine()
IEnumerator Juniper.Unity.Widgets.AttentionDirector.FoundCoroutine () inline
Executes an animation and a sound indicating to the user that the target has been found.
Definition at line 127 of file AttentionDirector.cs.
         {
             this.Activate();
 #if UNITY_MODULES_AUDIO
             InteractionAudio.Play(Interaction.Success, transform, null);
 #endif
 #if UNITY_MODULES_ANIMATION
             return animator.PlayCoroutine("Found");
 #else
             return null;
 #endif
         }
References Juniper.Unity.Widgets.AttentionDirector.animator, Juniper.Unity.Audio.AbstractInteractionAudio.Play(), and Juniper.Unity.Animation.AbstractAnimator.PlayCoroutine().
Referenced by Juniper.Unity.Widgets.AttentionDirector.Found().
Lost()
void Juniper.Unity.Widgets.AttentionDirector.Lost () inline
Executes an animation and a sound indicating to the user that the target has been lost.
Definition at line 143 of file AttentionDirector.cs.
         {
             StartCoroutine(LostCoroutine());
         }
References Juniper.Unity.Widgets.AttentionDirector.LostCoroutine().
LostCoroutine()
IEnumerator Juniper.Unity.Widgets.AttentionDirector.LostCoroutine () inline
Executes an animation and a sound indicating to the user that the target has been lost.
Returns
The coroutine.
Definition at line 152 of file AttentionDirector.cs.
         {
             this.Activate();
 #if UNITY_MODULES_AUDIO
             InteractionAudio.Play(Interaction.Error, transform, null);
 #endif
 #if UNITY_MODULES_ANIMATION
             return animator.PlayCoroutine("Lost");
 #else
             return null;
 #endif
         }
References Juniper.Unity.Widgets.AttentionDirector.animator, Juniper.Unity.Audio.AbstractInteractionAudio.Play(), and Juniper.Unity.Animation.AbstractAnimator.PlayCoroutine().
Referenced by Juniper.Unity.Widgets.AttentionDirector.Lost().
Play()
void Juniper.Unity.Widgets.AttentionDirector.Play (string anim) inline
Play one of the animations on the attention director.
Parameters
anim Animation.
Definition at line 69 of file AttentionDirector.cs.
         {
 #if UNITY_MODULES_ANIMATION
             animator?.Play(anim);
 #endif
         }
References Juniper.Unity.Widgets.AttentionDirector.animator, and Juniper.Unity.Animation.AbstractAnimator.Play().
Scan()
void Juniper.Unity.Widgets.AttentionDirector.Scan (Action onFound = null) inline
Executes an animation that tells the user that they should be searching for a target.
Definition at line 97 of file AttentionDirector.cs.
         {
             StartCoroutine(ScanCoroutine(onFound));
         }
References Juniper.Unity.Widgets.AttentionDirector.ScanCoroutine().
ScanCoroutine()
IEnumerator Juniper.Unity.Widgets.AttentionDirector.ScanCoroutine (Action onFound = null) inline
Executes an animation that tells the user that they should be searching for a target.
Definition at line 105 of file AttentionDirector.cs.
         {
             this.Activate();
             SetTarget(null, onFound);
 #if UNITY_MODULES_ANIMATION
             return animator.PlayCoroutine("Scan");
 #else
             return null;
 #endif
         }
References Juniper.Unity.Widgets.AttentionDirector.animator, Juniper.Unity.Animation.AbstractAnimator.PlayCoroutine(), and Juniper.Unity.Widgets.AttentionDirector.SetTarget().
Referenced by Juniper.Unity.Widgets.AttentionDirector.Scan().
SetTarget()
void Juniper.Unity.Widgets.AttentionDirector.SetTarget (Component target, Action onTargetFound) inline
Set the attenion director to targeting a specific object, withouth showing the optional center image.
Parameters
target Target.
onTargetFound On target found.
Definition at line 184 of file AttentionDirector.cs.
         {
             this.Activate();
             if (target != null)
             {
                 targetTrans = target.transform;
                 showImage = false;
                 showPointer = true;
             }
             else
             {
                 showImage = true;
                 showPointer = false;
             }
             this.onTargetFound = onTargetFound;
         }
References Juniper.Unity.Widgets.AttentionDirector.onTargetFound, Juniper.Unity.Widgets.AttentionDirector.showImage, Juniper.Unity.Widgets.AttentionDirector.showPointer, and Juniper.Unity.Widgets.AttentionDirector.targetTrans.
Referenced by Juniper.Unity.Widgets.AttentionDirector.ScanCoroutine(), and Juniper.Unity.Widgets.AttentionDirector.SetTargetCoroutine().
SetTargetCoroutine()
IEnumerator Juniper.Unity.Widgets.AttentionDirector.SetTargetCoroutine (Component target) inline
Set the attenion director to targeting a specific object, withouth showing the optional center image.
Returns
The target coroutine.
Parameters
target Target.
Definition at line 171 of file AttentionDirector.cs.
         {
             var found = false;
             SetTarget(target, () => found = true);
             return new WaitUntil(() => found);
         }
References Juniper.Unity.Widgets.AttentionDirector.SetTarget().
Update()
void Juniper.Unity.Widgets.AttentionDirector.Update () inline
Updates the pointer graphics if the option to show them has changed, and checks to see how close we are to the target, updating the location of the arrow graphic if we haven't found it yet, or activating the callback function if we have.
Definition at line 207 of file AttentionDirector.cs.
         {
             if (showImage != wasShowImage)
             {
                 image.SetActive(showImage);
             }
             if (showPointer != wasShowPointer)
             {
                 pointer.SetActive(showPointer);
             }
             var origin = transform.position;
             var fwd = transform.forward;
             if (!targetTrans.IsActivated())
             {
                 targetTrans = null;
             }
             if (Target != Vector3.zero)
             {
                 var dir = (Target - origin).normalized;
                 var right = Vector3.Dot(dir, transform.right) * transform.right;
                 var up = Vector3.Dot(dir, transform.up) * transform.up;
                 var point = up + right;
                 pointer.rotation = Quaternion.LookRotation(point, transform.forward);
                 var toTarget = DisplayManager.MainCamera.WorldToViewportPoint(Target);
                 toTarget.z = 0;
                 var targetDistance = toTarget.magnitude / 2;
                 arrow.localPosition = Mathf.Clamp01(targetDistance) * tagRange;
                 var distance = 1 - Vector3.Dot(fwd, dir);
                 if (distance < minDistance && onTargetFound != null)
                 {
                     // The callback could call AttentionDirector::Target, so if we call onTargetFound
                     // before nulling it, we'll break the callback.
                     var cb = onTargetFound;
                     onTargetFound = null;
                     cb();
                 }
             }
             if (Application.isEditor && UnityEngine.Input.GetKeyDown(KeyCode.F))
             {
                 var mouse = ComponentExt.FindAny<RunningMovement>();
                 if (mouse != null)
                 {
                     mouse.transform.LookAt(Target, Vector3.up);
                 }
             }
             wasShowImage = showImage;
             wasShowPointer = showPointer;
         }
References Juniper.Unity.Widgets.AttentionDirector.arrow, Juniper.Unity.Widgets.AttentionDirector.image, Juniper.Unity.Display.AbstractDisplayManager.MainCamera, Juniper.Unity.Widgets.AttentionDirector.minDistance, Juniper.Unity.Widgets.AttentionDirector.onTargetFound, Juniper.Unity.Widgets.AttentionDirector.pointer, Juniper.Unity.Widgets.AttentionDirector.showImage, Juniper.Unity.Widgets.AttentionDirector.showPointer, Juniper.Unity.Widgets.AttentionDirector.tagRange, Juniper.Unity.Widgets.AttentionDirector.Target, Juniper.Unity.Widgets.AttentionDirector.targetTrans, Juniper.Unity.Widgets.AttentionDirector.wasShowImage, and Juniper.Unity.Widgets.AttentionDirector.wasShowPointer.
Member Data Documentation
animator
AbstractAnimator Juniper.Unity.Widgets.AttentionDirector.animator private
An optional animation object to show different attention director states.
Definition at line 334 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Awake(), Juniper.Unity.Widgets.AttentionDirector.FoundCoroutine(), Juniper.Unity.Widgets.AttentionDirector.LostCoroutine(), Juniper.Unity.Widgets.AttentionDirector.Play(), and Juniper.Unity.Widgets.AttentionDirector.ScanCoroutine().
arrow
Transform Juniper.Unity.Widgets.AttentionDirector.arrow private
The arrow on the edge of the pointer graphic, pointer the user to the direction to turn.
Definition at line 297 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Awake(), and Juniper.Unity.Widgets.AttentionDirector.Update().
image
Transform Juniper.Unity.Widgets.AttentionDirector.image private
An optional image to display in the center of the attention director. Maybe use it for displaying instructions to the user the first time they see the attention director.
Definition at line 308 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Awake(), and Juniper.Unity.Widgets.AttentionDirector.Update().
lastTargetPosition
Vector3 Juniper.Unity.Widgets.AttentionDirector.lastTargetPosition private
The position in space that we were targeting last frame.
Definition at line 287 of file AttentionDirector.cs.
lastTargetTrans
Transform Juniper.Unity.Widgets.AttentionDirector.lastTargetTrans private
The object we were targeting in the last frame.
Definition at line 277 of file AttentionDirector.cs.
minDistance
float Juniper.Unity.Widgets.AttentionDirector.minDistance = 0.01f
The threshold at which to consider an object "in view"
Definition at line 35 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Update().
onTargetFound
Action Juniper.Unity.Widgets.AttentionDirector.onTargetFound private
The callback to execute when the target is found.
Definition at line 267 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.SetTarget(), and Juniper.Unity.Widgets.AttentionDirector.Update().
pointer
Transform Juniper.Unity.Widgets.AttentionDirector.pointer private
The pointer graphic.
Definition at line 292 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Awake(), and Juniper.Unity.Widgets.AttentionDirector.Update().
showImage
bool Juniper.Unity.Widgets.AttentionDirector.showImage private
Whether or not to show the optional center image.
Definition at line 313 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.SetTarget(), and Juniper.Unity.Widgets.AttentionDirector.Update().
showPointer
bool Juniper.Unity.Widgets.AttentionDirector.showPointer private
Whether or not to show the pointer graphic at all.
Definition at line 318 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.SetTarget(), and Juniper.Unity.Widgets.AttentionDirector.Update().
shrinkSpeed
float Juniper.Unity.Widgets.AttentionDirector.shrinkSpeed = 0.5f
How quickly the object should vanish away
Definition at line 29 of file AttentionDirector.cs.
tagRange
Vector3 Juniper.Unity.Widgets.AttentionDirector.tagRange private
The offset from the center at which the arrow is located.
Definition at line 302 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Awake(), and Juniper.Unity.Widgets.AttentionDirector.Update().
targetPos
Vector3 Juniper.Unity.Widgets.AttentionDirector.targetPos private
The position in space that we are targeting, if there is no distinct target object.
Definition at line 282 of file AttentionDirector.cs.
targetTrans
Transform Juniper.Unity.Widgets.AttentionDirector.targetTrans private
The optional object we are targeting.
Definition at line 272 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.SetTarget(), and Juniper.Unity.Widgets.AttentionDirector.Update().
wasShowImage
bool Juniper.Unity.Widgets.AttentionDirector.wasShowImage private
Whether or not the optional center image was visible in the last frame.
Definition at line 323 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Update().
wasShowPointer
bool Juniper.Unity.Widgets.AttentionDirector.wasShowPointer private
Whether or not the pointer graphic was visible in the last frame.
Definition at line 328 of file AttentionDirector.cs.
Referenced by Juniper.Unity.Widgets.AttentionDirector.Update().
Property Documentation
Target
Vector3 Juniper.Unity.Widgets.AttentionDirector.Target get
The point we are trying to find with the attention director.
Definition at line 41 of file AttentionDirector.cs.
         {
             get
             {
                 if (targetTrans != lastTargetTrans || targetTrans != null && targetTrans.position != lastTargetPosition)
                 {
                     if (targetTrans == null)
                     {
                         lastTargetPosition = targetPos = Vector3.zero;
                         showPointer = false;
                     }
                     else
                     {
                         lastTargetPosition = targetTrans.position;
                         var tt = targetTrans.GetComponentInChildren<Tooltip>();
                         targetPos = targetTrans.gameObject.Center(tt);
                     }
                     lastTargetTrans = targetTrans;
                 }
                 return targetPos;
             }
         }
Referenced by Juniper.Unity.Widgets.AttentionDirector.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Widgets/AttentionDirector.cs