Juniper: Juniper.Animation.AlphaTransition Class Reference
Juniper.Animation.AlphaTransition Class Reference
Performs a shrinking/growing animation on scene transitions.
Public Member Functions
override void Enter (IProgress prog)
Fire the OnEnable event and perform the Enter transition.
void Enter ()
override void Exit (IProgress prog)
Fire the OnExiting event and perform the Exit transition.
void Exit ()
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
virtual void SkipExit ()
Task EnterAsync (IProgress prog=null)
Task ExitAsync (IProgress prog=null)
Public Attributes
float minAlpha = 0
The minimum opacity of the object, where 0 = completely transparent.
float maxAlpha = 1
The maximum opacity of the object, where 1 = completely opaque.
float length = 0.25f
The amount of time it takes to complete the transition.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
UnityEvent onStopped = new UnityEvent()
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Direction _curState
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void RenderValue (float value)
Updates the size of the transitioning object every frame the transition is active.
override void Complete ()
Finish the transition, whatever is going on.
override void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
override void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
virtual void OnStopped ()
Protected Attributes
bool skipEvents
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Properties
override float TransitionLength [get]
The amount of time it takes to complete the transition.
float DeltaAlpha [get]
The scale range the transition has to traverse.
Direction State [get, private set]
virtual bool IsComplete [get]
Returns true when State is Direction.Stopped
bool IsEntering [get]
bool IsExiting [get]
bool CanExit [get]
bool CanEnter [get]
bool IsRunning [get]
Returns true when State is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
Events
EventHandler< TransitionValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
EventHandler Stopped
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Private Attributes
Material transitionMaterial
The material on which the opacity is being set.
Detailed Description
Performs a shrinking/growing animation on scene transitions.
Definition at line 11 of file AlphaTransition.cs.
Member Function Documentation
Complete()
override void Juniper.Animation.AbstractTransitionController.Complete () inline protected virtual inherited
Finish the transition, whatever is going on.
Reimplemented from Juniper.AbstractStateController.
Definition at line 110 of file AbstractTransitionController.cs.
         {
             SetProgress(1);
             base.Complete();
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Animation.AbstractTransitionController.Update().
Enter() [1/2]
override void Juniper.Animation.AbstractTransitionController.Enter (IProgress prog) inline virtual inherited
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 92 of file AbstractTransitionController.cs.
         {
             base.Enter(prog);
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Widgets.TeleportPad.OnClick(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Animation.WorkflowStep.Show().
Enter() [2/2]
void Juniper.AbstractStateController.Enter () inline inherited
Definition at line 272 of file AbstractStateController.cs.
         {
             Enter(null);
         }
Referenced by Juniper.Widgets.MenuView.Enter(), Juniper.AbstractStateController.EnterAsync(), Juniper.Animation.FadeTransition.Fader(), Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.AbstractStateController.SkipEnter().
EnterAsync()
Task Juniper.AbstractStateController.EnterAsync (IProgress prog = null) inline inherited
Definition at line 331 of file AbstractStateController.cs.
         {
             return Stopper(Enter, prog);
         }
References Juniper.AbstractStateController.Enter(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Exit() [1/2]
override void Juniper.Animation.AbstractTransitionController.Exit (IProgress prog) inline virtual inherited
Fire the OnExiting event and perform the Exit transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 101 of file AbstractTransitionController.cs.
         {
             base.Exit(prog);
             if (skipEvents)
             {
                 Update();
             }
         }
References Juniper.AbstractStateController.skipEvents, and Juniper.Animation.AbstractTransitionController.Update().
Referenced by Juniper.Widgets.TeleportPad.Darth_Entered(), and Juniper.Widgets.Openable.SetOpen().
Exit() [2/2]
void Juniper.AbstractStateController.Exit () inline inherited
Definition at line 285 of file AbstractStateController.cs.
         {
             Exit(null);
         }
Referenced by Juniper.Widgets.MenuView.Exit(), Juniper.AbstractStateController.ExitAsync(), Juniper.Animation.FadeTransition.Fader(), and Juniper.AbstractStateController.SkipExit().
ExitAsync()
Task Juniper.AbstractStateController.ExitAsync (IProgress prog = null) inline inherited
Definition at line 336 of file AbstractStateController.cs.
         {
             return Stopper(Exit, prog);
         }
References Juniper.AbstractStateController.Exit(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), Juniper.MasterSceneController.RemoveSceneCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
OnEntered()
virtual void Juniper.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Animation.FadeTransition, and Juniper.Widgets.MenuCollection.
Definition at line 379 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onEntered != null)
                 {
                     onEntered.Invoke();
                 }
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entered, Juniper.AbstractStateController.onEntered, and Juniper.AbstractStateController.skipEvents.
OnEntering()
override void Juniper.Animation.AbstractTransitionController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 120 of file AbstractTransitionController.cs.
         {
             attack = attackTime;
             release = releaseTime;
             SetProgress(0);
             base.OnEntering();
         }
References Juniper.Animation.AbstractTransitionController.attack, Juniper.Animation.AbstractTransitionController.attackTime, Juniper.Animation.AbstractTransitionController.release, Juniper.Animation.AbstractTransitionController.releaseTime, and Juniper.Animation.AbstractTransitionController.SetProgress().
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 417 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onExited != null)
                 {
                     onExited.Invoke();
                 }
                 Exited?.Invoke(this, EventArgs.Empty);
             }
             enabled = false;
         }
References Juniper.AbstractStateController.Exited, Juniper.AbstractStateController.onExited, and Juniper.AbstractStateController.skipEvents.
OnExiting()
override void Juniper.Animation.AbstractTransitionController.OnExiting () inline protected virtual inherited
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented from Juniper.AbstractStateController.
Reimplemented in Juniper.Animation.FadeTransition, Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 128 of file AbstractTransitionController.cs.
         {
             attack = releaseTime;
             release = attackTime;
             SetProgress(0);
             base.OnExiting();
         }
References Juniper.Animation.AbstractTransitionController.attack, Juniper.Animation.AbstractTransitionController.attackTime, Juniper.Animation.AbstractTransitionController.release, Juniper.Animation.AbstractTransitionController.releaseTime, and Juniper.Animation.AbstractTransitionController.SetProgress().
OnStopped()
virtual void Juniper.AbstractStateController.OnStopped () inline protected virtual inherited
Definition at line 430 of file AbstractStateController.cs.
         {
             if (onStopped != null)
             {
                 onStopped?.Invoke();
             }
             Stopped?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.onStopped, and Juniper.AbstractStateController.Stopped.
RenderValue()
override void Juniper.Animation.AlphaTransition.RenderValue (float value) inline protected virtual
Updates the size of the transitioning object every frame the transition is active.
Parameters
value
Implements Juniper.Animation.AbstractTransitionController.
Reimplemented in Juniper.Widgets.VideoVader.
Definition at line 54 of file AlphaTransition.cs.
         {
             if (transitionMaterial == null)
             {
                 var rend = GetComponent<Renderer>();
                 if (rend != null)
                 {
                     transitionMaterial = rend.GetMaterial();
                 }
             }
             if (transitionMaterial != null)
             {
                 var o = Mathf.Clamp01(minAlpha + value * DeltaAlpha);
                 transitionMaterial.SetFloat("_Alpha", o);
             }
         }
References Juniper.Animation.AlphaTransition.DeltaAlpha, Juniper.Animation.AlphaTransition.minAlpha, and Juniper.Animation.AlphaTransition.transitionMaterial.
SkipEnter()
virtual void Juniper.AbstractStateController.SkipEnter () inline virtual inherited
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 309 of file AbstractStateController.cs.
         {
             if (!IsEntered)
             {
                 skipEvents = true;
                 Enter();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.IsEntered, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.MasterSceneController.Start().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 320 of file AbstractStateController.cs.
         {
             if (!IsExited)
             {
                 skipEvents = true;
                 Exit();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Exit(), Juniper.AbstractStateController.IsExited, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.Widgets.Tooltipable.Hide(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Update()
virtual void Juniper.Animation.AbstractTransitionController.Update () inline protected virtual inherited
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented in Juniper.Animation.SpiralTransition.
Definition at line 140 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress < 1)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress + change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     Complete();
                 }
             }
         }
References Juniper.Animation.AbstractTransitionController.attack, Juniper.Animation.AbstractTransitionController.Complete(), Juniper.AbstractStateController.IsRunning, Juniper.Animation.AbstractTransitionController.progress, Juniper.Animation.AbstractTransitionController.release, Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.Animation.AbstractTransitionController.TransitionLength.
Referenced by Juniper.Animation.AbstractTransitionController.Complete(), Juniper.Animation.AbstractTransitionController.Enter(), and Juniper.Animation.AbstractTransitionController.Exit().
Member Data Documentation
_curState
Direction Juniper.AbstractStateController._curState inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 117 of file AbstractStateController.cs.
attackTime
float Juniper.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 21 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnEntering(), and Juniper.Animation.AbstractTransitionController.OnExiting().
length
float Juniper.Animation.AlphaTransition.length = 0.25f
The amount of time it takes to complete the transition.
Definition at line 26 of file AlphaTransition.cs.
maxAlpha
float Juniper.Animation.AlphaTransition.maxAlpha = 1
The maximum opacity of the object, where 1 = completely opaque.
Definition at line 21 of file AlphaTransition.cs.
minAlpha
float Juniper.Animation.AlphaTransition.minAlpha = 0
The minimum opacity of the object, where 0 = completely transparent.
Definition at line 16 of file AlphaTransition.cs.
Referenced by Juniper.Animation.AlphaTransition.RenderValue(), and Juniper.Widgets.VideoVader.RenderValue().
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 38 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 29 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 56 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 47 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
onStopped
UnityEvent Juniper.AbstractStateController.onStopped = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 65 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped().
onValueChanged
UnityEvent Juniper.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 34 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
releaseTime
float Juniper.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 28 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnEntering(), and Juniper.Animation.AbstractTransitionController.OnExiting().
skipEvents
bool Juniper.AbstractStateController.skipEvents protected inherited
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Definition at line 166 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Complete(), Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.AbstractTransitionController.Exit(), Juniper.AbstractStateController.OnEntered(), Juniper.AbstractStateController.OnEntering(), Juniper.AbstractStateController.OnExited(), Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.SkipEnter(), and Juniper.AbstractStateController.SkipExit().
transitionMaterial
Material Juniper.Animation.AlphaTransition.transitionMaterial private
The material on which the opacity is being set.
Definition at line 75 of file AlphaTransition.cs.
Referenced by Juniper.Animation.AlphaTransition.RenderValue().
tween
TweenType Juniper.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 39 of file AbstractTransitionController.cs.
tweenK
float Juniper.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 46 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.SetProgress().
Property Documentation
CanEnter
bool Juniper.AbstractStateController.CanEnter get inherited
Definition at line 204 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsEntered && !IsEntering;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
CanExit
bool Juniper.AbstractStateController.CanExit get inherited
Definition at line 196 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsExited && !IsExiting;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
DeltaAlpha
float Juniper.Animation.AlphaTransition.DeltaAlpha get protected
The scale range the transition has to traverse.
Definition at line 43 of file AlphaTransition.cs.
         {
             get
             {
                 return maxAlpha - minAlpha;
             }
         }
Referenced by Juniper.Animation.AlphaTransition.RenderValue(), and Juniper.Widgets.VideoVader.RenderValue().
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get inherited
Returns true when State is Direction.Stopped
Definition at line 172 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Stopped;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntered
bool Juniper.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 226 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Forward;
             }
         }
Referenced by Juniper.AbstractStateController.SkipEnter(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntering
bool Juniper.AbstractStateController.IsEntering get inherited
Definition at line 180 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Forward;
             }
         }
IsExited
bool Juniper.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 237 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Reverse;
             }
         }
Referenced by Juniper.AbstractStateController.SkipExit(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsExiting
bool Juniper.AbstractStateController.IsExiting get inherited
Definition at line 188 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Reverse;
             }
         }
IsRunning
bool Juniper.AbstractStateController.IsRunning get inherited
Returns true when State is not Direction.Stopped
Definition at line 215 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Animation.AbstractTransitionController.Update().
State
Direction Juniper.AbstractStateController.State get private set inherited
Definition at line 120 of file AbstractStateController.cs.
         {
             get
             {
                 return _curState;
             }
             private set
             {
                 lastState = _curState;
                 _curState = value;
                 if (State != lastState)
                 {
                     if (State == Direction.Forward)
                     {
                         OnEntering();
                     }
                     else if (State == Direction.Reverse)
                     {
                         OnExiting();
                     }
                     else
                     {
                         OnStopped();
                         if (lastState == Direction.Forward)
{
                             OnEntered();
                         }
                         else if (lastState == Direction.Reverse)
{
                             OnExited();
                         }
                     }
                 }
             }
         }
Referenced by Juniper.AbstractStateController.Complete(), Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.AbstractStateController.SetState().
TransitionLength
override float Juniper.Animation.AlphaTransition.TransitionLength get
The amount of time it takes to complete the transition.
Definition at line 32 of file AlphaTransition.cs.
         {
             get
             {
                 return length;
             }
         }
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 83 of file AbstractStateController.cs.
Referenced by Juniper.Widgets.MenuView.Awake(), Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 74 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 101 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 92 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExiting().
Stopped
EventHandler Juniper.AbstractStateController.Stopped inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 110 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped(), and Juniper.AbstractStateController.Stopper().
ValueChanged
EventHandler<TransitionValueChangedEventArgs> Juniper.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 52 of file AbstractTransitionController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Animation/AlphaTransition.cs