Juniper: Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager Class Reference
Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager Class Reference
An editor to respond to changes in XRSystem.
Static Public Member Functions
static bool SetAndroid_MenuItem_Validate ()
static void SetAndroid_MenuItem ()
static bool SetAndroid_ARCore_MenuItem_Validate ()
static void SetAndroid_ARCore_MenuItem ()
static bool SetAndroid_Cardboard_MenuItem_Validate ()
static void SetAndroid_Cardboard_MenuItem ()
static bool SetAndroid_Daydream_MenuItem_Validate ()
static void SetAndroid_Daydream_MenuItem ()
static bool SetAndroid_Oculus_MenuItem_Validate ()
static void SetAndroid_Oculus_MenuItem ()
static bool SetAndroid_ViveFocus_MenuItem_Validate ()
static void SetAndroid_ViveFocus_MenuItem ()
static bool SetIOS_MenuItem_Validate ()
static void SetIOS_MenuItem ()
static bool SetIOS_ARKit_MenuItem_Validate ()
static void SetIOS_ARKit_MenuItem ()
static bool SetIOS_Cardboard_MenuItem_Validate ()
static void SetIOS_Cardboard_MenuItem ()
static bool SetStandalone_MenuItem_Validate ()
static void SetStandalone_MenuItem ()
static bool SetStandalone_Oculus_MenuItem_Validate ()
static void SetStandalone_Oculus_MenuItem ()
static bool SetStandalone_SteamVR_MenuItem_Validate ()
static void SetStandalone_SteamVR_MenuItem ()
static bool SetUWP_MenuItem_Validate ()
static void SetUWP_MenuItem ()
static bool SetUWP_WindowsMR_MenuItem_Validate ()
static void SetUWP_WindowsMR_MenuItem ()
static bool SetUWP_HoloLens_MenuItem_Validate ()
static void SetUWP_HoloLens_MenuItem ()
static bool SetMagicLeap_MenuItem_Validate ()
static void SetMagicLeap_MenuItem ()
static void ClearProgressDialog_MenuItem ()
static void Other_ResetConfiguration ()
static bool Other_ResumeBuild_Validate ()
static void Other_ResumeBuild ()
static void Other_Recompile_Menu ()
static void RefreshPackages ()
static void ActivatePlatform ()
static void PrepareScene ()
Properties
static int BuildProgress [get, set]
static PlatformTypes CurrentPlatform [get]
static PlatformTypes DesiredPlatform [get]
static bool BuildInProgress [get]
static bool RebuildNeeded [get]
static PlatformTypes NextPlatform [get, set]
static PlatformConfiguration LastConfiguration [get]
static PlatformConfiguration NextConfiguration [get]
static string [] JUNIPER_DEFINES [get]
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
Static Private Member Functions
static JuniperConfigurationManager ()
static bool Config_PlatformChanged ()
static string ThirdPartyDefines (BuildTargetGroup targetGroup)
static bool MenuCheck (PlatformTypes p)
static void Uninstall ()
static void Install ()
static void OnCancel ()
static void OnCancel (bool canceledByUser)
static void OnEditorUpdate (Action resolve, Action reject=null, Func< bool > test=null)
static void DelayedUpdate (IProgressReceiver prog, float maxTime, Action onComplete)
static List< string > FormatDefines (ref string definesString)
static IProgressReceiver PrepareBuildStep (int offset, string prefix=null)
static void WithProgress (string prefix, Action< IProgressReceiver > act)
static void Recompile (bool advanceBuildStep, string nextDefinesString=null)
static void RecompilePlatformInternal ()
static IEnumerable< IInstallable > GetInstallables ()
static void ResumeBuild ()
static void StartBuild ()
static void DeactivatePlatform ()
Private Attributes
const string MENU_NAME = "Juniper/"
const string ANDROID_MENU_NAME = MENU_NAME + "Android/"
const string IOS_MENU_NAME = MENU_NAME + "IOS/"
const string STANDALONE_MENU_NAME = MENU_NAME + "Standalone/"
const string UWP_MENU_NAME = MENU_NAME + "UWP/"
const string OTHER_MENU_NAME = MENU_NAME + "Other/"
const string RECOMPILE_SLUG = "RECOMPILE_SLUG"
Static Private Attributes
static readonly ProjectConfiguration config
static string LastPrefix
static readonly Action [] STAGES
static readonly string MANIFEST_FILE = PathExt.FixPath("Packages/manifest.json")
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 24 of file JuniperConfigurationManager.cs.
Constructor & Destructor Documentation
JuniperConfigurationManager()
static Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager () inline static private
Definition at line 30 of file JuniperConfigurationManager.cs.
         {
             config = ProjectConfiguration.Load();
             config.PlatformChanged += Config_PlatformChanged;
             config.PlatformChangeConfirmed += StartBuild;
             if (RebuildNeeded)
             {
                 OnEditorUpdate(() =>
                     NextPlatform = DesiredPlatform,
                     () => EditorUtility.DisplayDialog("Juniper", "Could not change platform.", "OK"));
             }
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DesiredPlatform, Juniper.Unity.ConfigurationManagement.ProjectConfiguration.Load(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), Juniper.Unity.ConfigurationManagement.ProjectConfiguration.PlatformChangeConfirmed, Juniper.Unity.ConfigurationManagement.ProjectConfiguration.PlatformChanged, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RebuildNeeded, and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
Member Function Documentation
ActivatePlatform()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform () inline static
Definition at line 665 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Activating Platform " + NextPlatform, _ =>
             {
                 var newDefinesString = ThirdPartyDefines(NextConfiguration.TargetGroup);
                 var newDefines = newDefinesString.Split(';').ToList();
                 newDefines.MaybeAddRange(NextConfiguration.CompilerDefines);
                 Recompile(true, string.Join(";", newDefines));
             });
         }
References Juniper.Unity.ConfigurationManagement.PlatformConfiguration.CompilerDefines, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.TargetGroup, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
ClearProgressDialog_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ClearProgressDialog_MenuItem () inline static
Definition at line 406 of file JuniperConfigurationManager.cs.
         {
             EditorUtility.ClearProgressBar();
         }
Config_PlatformChanged()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged () inline static private
Definition at line 102 of file JuniperConfigurationManager.cs.
         {
             if (!Platforms.Instance.PlatformDB[config.NextPlatform].IsSupported)
             {
                 EditorUtility.DisplayDialog(
                    "Juniper",
                    $"The platform {config.NextPlatform} is not supported on your current system.",
                    "OK");
                 return false;
             }
             else
             {
                 return config.NextPlatform == PlatformTypes.None
                     || (config.NextPlatform != CurrentPlatform
                         && EditorUtility.DisplayDialog(
                             "Juniper",
                             $"You are about to change the platfrom from {CurrentPlatform} to {config.NextPlatform}. Do you want to continue?",
                             "Change platform",
                             "Don't change platform"));
             }
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform, Juniper.Unity.ConfigurationManagement.Platforms.Instance, Juniper.Unity.ConfigurationManagement.ProjectConfiguration.NextPlatform, and Juniper.Unity.ConfigurationManagement.Platforms.PlatformDB.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
DeactivatePlatform()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform () inline static private
Definition at line 618 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Resetting to base configuration", _ =>
             {
                 Installable.UninstallAll(GetInstallables);
                 LastConfiguration.Deactivate(NextConfiguration, ThirdPartyDefines(NextConfiguration.TargetGroup));
                 Recompile(true, ThirdPartyDefines(LastConfiguration.TargetGroup));
             });
         }
References Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Deactivate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.TargetGroup, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines(), Juniper.Installable.UninstallAll(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
DelayedUpdate()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate (IProgressReceiver prog, float maxTime, Action onComplete) inline static private
Definition at line 485 of file JuniperConfigurationManager.cs.
         {
             prog?.SetProgress(0);
             var startTime = DateTime.Now;
             OnEditorUpdate(() =>
             {
                 EditorUtility.ClearProgressBar();
                 onComplete();
             }, OnCancel, () =>
             {
                 var age = (float)(DateTime.Now - startTime).TotalSeconds;
                 prog?.SetProgress(age, maxTime);
                 return age > maxTime;
             });
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), and Juniper.Progress.IProgressReceiver.SetProgress().
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile().
FormatDefines()
static List<string> Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.FormatDefines (ref string definesString) inline static private
Definition at line 501 of file JuniperConfigurationManager.cs.
         {
             var defines = definesString?.Split(';')?.ToList() ?? new List<string>();
             defines.Sort();
             // move the slug to the end, if it exists
             if (defines.Contains(RECOMPILE_SLUG))
             {
                 defines.Remove(RECOMPILE_SLUG);
                 defines.Add(RECOMPILE_SLUG);
             }
             definesString = string.Join(";", defines);
             return defines;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile().
GetInstallables()
static IEnumerable<IInstallable> Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.GetInstallables () inline static private
Definition at line 586 of file JuniperConfigurationManager.cs.
         {
             return ComponentExt
                 .FindAll<Component>()
                 .OfType<IInstallable>();
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Install(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareScene(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Uninstall().
Install()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Install () inline static private
Definition at line 398 of file JuniperConfigurationManager.cs.
         {
             Uninstall();
             JuniperPlatform.Ensure();
             Installable.InstallAll(GetInstallables);
         }
References Juniper.Unity.JuniperPlatform.Ensure(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), Juniper.Installable.InstallAll(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Uninstall().
MenuCheck()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck (PlatformTypes p) inline static private
Definition at line 166 of file JuniperConfigurationManager.cs.
         {
             return CurrentPlatform != p && Platforms.Instance.PlatformDB[p].IsSupported;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform, Juniper.Unity.ConfigurationManagement.Platforms.Instance, and Juniper.Unity.ConfigurationManagement.Platforms.PlatformDB.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem_Validate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem_Validate(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem_Validate().
OnCancel() [1/2]
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnCancel () inline static private
Definition at line 442 of file JuniperConfigurationManager.cs.
         {
             OnCancel(true);
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareScene(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
OnCancel() [2/2]
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnCancel (bool canceledByUser) inline static private
Definition at line 447 of file JuniperConfigurationManager.cs.
         {
             if (canceledByUser)
             {
                 Debug.LogWarning("Canceled by user");
             }
             EditorUtility.ClearProgressBar();
             BuildProgress = -1;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildProgress.
OnEditorUpdate()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate (Action resolve, Action reject = null, Func< bool > test = null) inline static private
Definition at line 457 of file JuniperConfigurationManager.cs.
         {
             if (test == null)
             {
                 test = () => true;
             }
             EditorApplication.CallbackFunction exec = null;
             exec = () =>
             {
                 if (test())
                 {
                     try
                     {
                         EditorApplication.update -= exec;
                         resolve();
                     }
                     catch (OperationCanceledException)
                     {
                         EditorApplication.update -= exec;
                         reject();
                     }
                 }
             };
             EditorApplication.update += exec;
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareScene().
Other_Recompile_Menu()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu () inline static
Definition at line 430 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Recompiling platform " + NextPlatform, _ =>
                 RecompilePlatformInternal());
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Other_ResetConfiguration()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_ResetConfiguration () inline static
Definition at line 412 of file JuniperConfigurationManager.cs.
         {
             StartBuild();
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
Other_ResumeBuild()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild () inline static
Definition at line 424 of file JuniperConfigurationManager.cs.
         {
             ResumeBuild();
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
Other_ResumeBuild_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild_Validate () inline static
Definition at line 418 of file JuniperConfigurationManager.cs.
         {
             return BuildInProgress;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress.
PrepareBuildStep()
static IProgressReceiver Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep (int offset, string prefix = null) inline static private
Definition at line 519 of file JuniperConfigurationManager.cs.
         {
             LastPrefix = prefix ?? LastPrefix;
             var step = BuildProgress - offset + 1;
             var msg = $"Juniper ({step} of {STAGES.Length}): {LastPrefix}";
             return new UnityEditorProgressDialog(msg)
                 .Subdivide(step + BuildProgress, 2 * STAGES.Length, LastPrefix);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.LastPrefix, and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.STAGES.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
PrepareScene()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareScene () inline static
Definition at line 676 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Preparing scene", _ =>
             {
                 var xr = JuniperPlatform.Ensure();
                 var scene = xr.gameObject.scene;
                 config.Commit();
                 OnCancel(false);
                 Installable.InstallAll(GetInstallables);
                 EditorSceneManager.MarkSceneDirty(scene);
                 if (EditorUtility.DisplayDialog("Juniper", "Done! Save scene?", "Save", "Cancel"))
                 {
                     OnEditorUpdate(() =>
                     EditorSceneManager.SaveScene(scene));
                 }
             });
         }
References Juniper.Unity.ConfigurationManagement.ProjectConfiguration.Commit(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.Unity.JuniperPlatform.Ensure(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), Juniper.Installable.InstallAll(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Recompile()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile (bool advanceBuildStep, string nextDefinesString = null) inline static private
Definition at line 546 of file JuniperConfigurationManager.cs.
         {
             if (advanceBuildStep)
             {
                 ++BuildProgress;
             }
             var targetGroup = BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget);
             var prog = PrepareBuildStep(1);
             var currentDefinesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);
             var currentDefines = FormatDefines(ref currentDefinesString);
             var nextDefines = FormatDefines(ref nextDefinesString);
             if (nextDefines.Matches(currentDefines))
             {
                 if (nextDefines.Contains(RECOMPILE_SLUG))
                 {
                     nextDefines.Remove(RECOMPILE_SLUG);
                 }
                 else
                 {
                     nextDefines.Add(RECOMPILE_SLUG);
                 }
             }
             nextDefines.RemoveAll(string.IsNullOrWhiteSpace);
             nextDefinesString = string.Join(";", nextDefines);
             PlayerSettings.SetScriptingDefineSymbolsForGroup(targetGroup, nextDefinesString);
             DelayedUpdate(prog, 30, () => Debug.LogWarning("Timeout!!!"));
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.FormatDefines(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal().
RecompilePlatformInternal()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal () inline static private
Definition at line 578 of file JuniperConfigurationManager.cs.
         {
             var newDefinesString = ThirdPartyDefines(NextConfiguration.TargetGroup);
             var newDefines = newDefinesString.Split(';').ToList();
             newDefines.MaybeAddRange(NextConfiguration.CompilerDefines);
             Recompile(false, string.Join(";", newDefines));
         }
References Juniper.Unity.ConfigurationManagement.PlatformConfiguration.CompilerDefines, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.TargetGroup, and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines().
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu().
RefreshPackages()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages () inline static
Definition at line 628 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Refreshing packages " + NextPlatform, prog =>
             {
                 var progs = prog.Split(5);
                 LastConfiguration.UninstallRawPackages(progs[0]);
                 var manifest = JObject.Parse(File.ReadAllText(MANIFEST_FILE));
                 var deps = manifest["dependencies"] as JObject;
                 if (deps == null)
                 {
                     deps = new JObject();
                     manifest.Add("dependencies", deps);
                 }
                 UnityPackage.Dependencies = deps;
                 LastConfiguration.UninstallUnityPackages(progs[1]);
                 NextConfiguration.InstallUnityPackages(progs[2]);
                 var txt = manifest.ToString(Formatting.Indented);
                 FileExt.WriteAllText(MANIFEST_FILE, txt);
                 NextConfiguration.InstallRawPackages(progs[3]);
                 NextConfiguration.Activate(progs[4]);
                 if (!NextConfiguration.SwitchTarget())
                 {
                     ++BuildProgress;
                     AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate | ImportAssetOptions.ImportRecursive);
                     if (!EditorApplication.isCompiling)
                     {
                         ResumeBuild();
                     }
                 }
             });
         }
References Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.Unity.ConfigurationManagement.UnityPackage.Dependencies, Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallRawPackages(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MANIFEST_FILE, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.SwitchTarget(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages(), Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress(), and System.IO.FileExt.WriteAllText().
ResumeBuild()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild () inline static private
Definition at line 602 of file JuniperConfigurationManager.cs.
         {
             if (BuildInProgress)
             {
                 STAGES[BuildProgress].Invoke();
             }
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress, Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.STAGES.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
SetAndroid_ARCore_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem () inline static
Definition at line 190 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidARCore;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_ARCore_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem_Validate () inline static
Definition at line 184 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidARCore);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Cardboard_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem () inline static
Definition at line 202 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidCardboard;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Cardboard_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem_Validate () inline static
Definition at line 196 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidCardboard);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Daydream_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem () inline static
Definition at line 214 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidDaydream;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Daydream_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem_Validate () inline static
Definition at line 208 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidDaydream);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem () inline static
Definition at line 178 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.Android;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem_Validate () inline static
Definition at line 172 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.Android);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Oculus_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem () inline static
Definition at line 226 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidOculus;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Oculus_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem_Validate () inline static
Definition at line 220 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidOculus);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_ViveFocus_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem () inline static
Definition at line 238 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidViveFocus;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_ViveFocus_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem_Validate () inline static
Definition at line 232 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidViveFocus);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_ARKit_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem () inline static
Definition at line 268 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOSARKit;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_ARKit_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem_Validate () inline static
Definition at line 262 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOSARKit);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_Cardboard_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem () inline static
Definition at line 280 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOSCardboard;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_Cardboard_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem_Validate () inline static
Definition at line 274 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOSCardboard);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem () inline static
Definition at line 256 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOS;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem_Validate () inline static
Definition at line 250 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOS);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetMagicLeap_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem () inline static
Definition at line 380 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.MagicLeap;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetMagicLeap_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem_Validate () inline static
Definition at line 374 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.MagicLeap);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem () inline static
Definition at line 298 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.Standalone;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem_Validate () inline static
Definition at line 292 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.Standalone);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_Oculus_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem () inline static
Definition at line 310 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.StandaloneOculus;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_Oculus_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem_Validate () inline static
Definition at line 304 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.StandaloneOculus);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_SteamVR_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem () inline static
Definition at line 322 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.StandaloneSteamVR;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_SteamVR_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem_Validate () inline static
Definition at line 316 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.StandaloneSteamVR);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_HoloLens_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem () inline static
Definition at line 364 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWPHoloLens;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_HoloLens_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem_Validate () inline static
Definition at line 358 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWPHoloLens);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem () inline static
Definition at line 340 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWP;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem_Validate () inline static
Definition at line 334 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWP);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_WindowsMR_MenuItem()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem () inline static
Definition at line 352 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWPWindowsMR;
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_WindowsMR_MenuItem_Validate()
static bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem_Validate () inline static
Definition at line 346 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWPWindowsMR);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
StartBuild()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.StartBuild () inline static private
Definition at line 612 of file JuniperConfigurationManager.cs.
         {
             BuildProgress = 0;
             DeactivatePlatform();
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform().
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_ResetConfiguration().
ThirdPartyDefines()
static string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines (BuildTargetGroup targetGroup) inline static private
Definition at line 152 of file JuniperConfigurationManager.cs.
         {
             var oldDefinesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);
             var oldDefines = oldDefinesString.Split(';');
             var newDefines = oldDefines.Exclude(JUNIPER_DEFINES);
             return string.Join(";", newDefines);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JUNIPER_DEFINES.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal().
Uninstall()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Uninstall () inline static private
Definition at line 392 of file JuniperConfigurationManager.cs.
         {
             Installable.UninstallAll(GetInstallables);
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), and Juniper.Installable.UninstallAll().
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Install().
WithProgress()
static void Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.WithProgress (string prefix, Action< IProgressReceiver > act) inline static private
Definition at line 528 of file JuniperConfigurationManager.cs.
         {
             try
             {
                 var prog = PrepareBuildStep(0, prefix);
                 prog.SetProgress(0);
                 act(prog);
             }
             catch (OperationCanceledException)
             {
                 OnCancel();
             }
             catch (Exception exp)
             {
                 Debug.LogException(exp);
             }
         }
References Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep().
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareScene(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Member Data Documentation
ANDROID_MENU_NAME
const string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ANDROID_MENU_NAME = MENU_NAME + "Android/" private
Definition at line 164 of file JuniperConfigurationManager.cs.
config
readonly ProjectConfiguration Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.config static private
Definition at line 28 of file JuniperConfigurationManager.cs.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareScene().
IOS_MENU_NAME
const string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.IOS_MENU_NAME = MENU_NAME + "IOS/" private
Definition at line 247 of file JuniperConfigurationManager.cs.
LastPrefix
string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.LastPrefix static private
Definition at line 517 of file JuniperConfigurationManager.cs.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep().
MANIFEST_FILE
readonly string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MANIFEST_FILE = PathExt.FixPath("Packages/manifest.json") static private
Definition at line 610 of file JuniperConfigurationManager.cs.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
MENU_NAME
const string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MENU_NAME = "Juniper/" private
Definition at line 26 of file JuniperConfigurationManager.cs.
OTHER_MENU_NAME
const string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OTHER_MENU_NAME = MENU_NAME + "Other/" private
Definition at line 389 of file JuniperConfigurationManager.cs.
RECOMPILE_SLUG
const string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG = "RECOMPILE_SLUG" private
Definition at line 440 of file JuniperConfigurationManager.cs.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.FormatDefines(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile().
STAGES
readonly Action [] Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.STAGES static private
Initial value:
=
        {
            DeactivatePlatform,
            RefreshPackages,
            ActivatePlatform,
            PrepareScene
        }
Definition at line 593 of file JuniperConfigurationManager.cs.
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
STANDALONE_MENU_NAME
const string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.STANDALONE_MENU_NAME = MENU_NAME + "Standalone/" private
Definition at line 289 of file JuniperConfigurationManager.cs.
UWP_MENU_NAME
const string Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.UWP_MENU_NAME = MENU_NAME + "UWP/" private
Definition at line 331 of file JuniperConfigurationManager.cs.
Property Documentation
BuildInProgress
bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress static get private
Definition at line 74 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return 0 <= BuildProgress && BuildProgress < STAGES.Length;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild_Validate(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
BuildProgress
int Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.BuildProgress static get set private
Definition at line 45 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.BuildStep;
             }
             set
             {
                 config.BuildStep = value;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
CurrentPlatform
PlatformTypes Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform static get private
Definition at line 58 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return JuniperPlatform.CURRENT_PLATFORM;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
DesiredPlatform
PlatformTypes Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DesiredPlatform static get private
Definition at line 66 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.CurrentPlatform;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
JUNIPER_DEFINES
string [] Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JUNIPER_DEFINES static get private
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
Definition at line 145 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return Platforms.Instance.AllCompilerDefines;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines().
LastConfiguration
PlatformConfiguration Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration static get private
Definition at line 125 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return Platforms.Instance.PlatformDB.Get(CurrentPlatform);
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
NextConfiguration
PlatformConfiguration Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration static get private
Definition at line 133 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return Platforms.Instance.PlatformDB.Get(NextPlatform);
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
NextPlatform
PlatformTypes Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.NextPlatform static get set private
Definition at line 90 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.NextPlatform;
             }
             set
             {
                 config.NextPlatform = value;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem(), Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem(), and Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem().
RebuildNeeded
bool Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.RebuildNeeded static get private
Definition at line 82 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return DesiredPlatform != CurrentPlatform && !BuildInProgress;
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/ConfigurationManagement/JuniperConfigurationManager.cs