Juniper: Juniper.Unity.Events.TimedEvent Class Reference
Juniper.Unity.Events.TimedEvent Class Reference
A component that can be used to trigger events after a set amount of time. Useful for automatically advancing between story views, or delaying action after user input.
Public Member Functions
void Awake ()
If playOnAwake is set to true, starts the firing timer.
void Stop ()
Stop the timer, if it's looping in a repeat.
void Play ()
Starts the delay timer.
Public Attributes
bool playOnAwake
Whether or not the event timer should start automatically when the component comes awake.
float delay
The amount of time, in seconds, to allow to elapse before triggering the event.
bool repeat
Whether or not the event timer should repeat after it has actuated.
UnityEvent onTimeout = new UnityEvent()
The event to occur when the timer has finished counting down.
Events
EventHandler Timeout
The event to occur when the timer has finished counting down.
Private Member Functions
void Fire ()
Runs a delay timer and then executes the event.
Detailed Description
A component that can be used to trigger events after a set amount of time. Useful for automatically advancing between story views, or delaying action after user input.
Definition at line 12 of file TimedEvent.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Events.TimedEvent.Awake () inline
If playOnAwake is set to true, starts the firing timer.
Definition at line 42 of file TimedEvent.cs.
         {
             if (playOnAwake)
             {
                 Play();
             }
         }
References Juniper.Unity.Events.TimedEvent.Play(), and Juniper.Unity.Events.TimedEvent.playOnAwake.
Fire()
void Juniper.Unity.Events.TimedEvent.Fire () inline private
Runs a delay timer and then executes the event.
Returns
The coroutine.
Definition at line 77 of file TimedEvent.cs.
         {
             onTimeout?.Invoke();
             Timeout?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Unity.Events.TimedEvent.onTimeout, and Juniper.Unity.Events.TimedEvent.Timeout.
Referenced by Juniper.Unity.Events.TimedEvent.Play().
Play()
void Juniper.Unity.Events.TimedEvent.Play () inline
Starts the delay timer.
Definition at line 61 of file TimedEvent.cs.
         {
             if (repeat)
             {
                 InvokeRepeating("Fire", delay, delay);
             }
             else
             {
                 Invoke(nameof(Fire), delay);
             }
         }
References Juniper.Unity.Events.TimedEvent.delay, Juniper.Unity.Events.TimedEvent.Fire(), and Juniper.Unity.Events.TimedEvent.repeat.
Referenced by Juniper.Unity.Events.TimedEvent.Awake().
Stop()
void Juniper.Unity.Events.TimedEvent.Stop () inline
Stop the timer, if it's looping in a repeat.
Definition at line 53 of file TimedEvent.cs.
         {
             CancelInvoke();
         }
Member Data Documentation
delay
float Juniper.Unity.Events.TimedEvent.delay
The amount of time, in seconds, to allow to elapse before triggering the event.
Definition at line 22 of file TimedEvent.cs.
Referenced by Juniper.Unity.Events.TimedEvent.Play().
onTimeout
UnityEvent Juniper.Unity.Events.TimedEvent.onTimeout = new UnityEvent()
The event to occur when the timer has finished counting down.
Definition at line 32 of file TimedEvent.cs.
Referenced by Juniper.Unity.Events.TimedEvent.Fire().
playOnAwake
bool Juniper.Unity.Events.TimedEvent.playOnAwake
Whether or not the event timer should start automatically when the component comes awake.
Definition at line 17 of file TimedEvent.cs.
Referenced by Juniper.Unity.Events.TimedEvent.Awake().
repeat
bool Juniper.Unity.Events.TimedEvent.repeat
Whether or not the event timer should repeat after it has actuated.
Definition at line 27 of file TimedEvent.cs.
Referenced by Juniper.Unity.Events.TimedEvent.Play().
Event Documentation
Timeout
EventHandler Juniper.Unity.Events.TimedEvent.Timeout
The event to occur when the timer has finished counting down.
Definition at line 37 of file TimedEvent.cs.
Referenced by Juniper.Unity.Events.TimedEvent.Fire().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Events/TimedEvent.cs