Juniper: Juniper.Data.OneShotThread Class Reference
Juniper.Data.OneShotThread Class Reference
Run any System.Action in a background thread that starts right away.
Static Public Member Functions
static void Run (Action run)
Creates a background thread that starts right away, executing an action along the way.
Public Attributes
virtual bool Running
Returns true when the background thread is still running.
Protected Member Functions
override void Execute ()
Peform the thread's desired operation.
void OnError (Exception exp)
Trigger the Error event handler, if it has any listeners attached to it.
virtual void Awake ()
Create a background thread runner in a stopped state.
void Begin ()
Get the background thread up and running.
virtual void OnBegin ()
Respond to the thread starting.
Events
EventHandler< BackgroundThreadErrorEventArgs > Error
An event that triggers if the background operation throws an exception.
Private Member Functions
OneShotThread (Action run)
Initialize a thread that runs only once, providing a body for the thread.
Private Attributes
readonly Action callback
The callback to run as the body of the thread.
Detailed Description
Run any System.Action in a background thread that starts right away.
Definition at line 8 of file OneShotThread.cs.
Constructor & Destructor Documentation
OneShotThread()
Juniper.Data.OneShotThread.OneShotThread (Action run) inline private
Initialize a thread that runs only once, providing a body for the thread.
Parameters
run
Definition at line 40 of file OneShotThread.cs.
         {
             callback = run;
         }
References Juniper.Data.OneShotThread.callback.
Referenced by Juniper.Data.OneShotThread.Run().
Member Function Documentation
Awake()
virtual void Juniper.Data.AbstractBackgroundThread.Awake () protected virtual inherited
Create a background thread runner in a stopped state.
Reimplemented in Juniper.Data.AbstractBackgroundRepeatingThread.
Begin()
void Juniper.Data.AbstractBackgroundThread.Begin () inline protected inherited
Get the background thread up and running.
Definition at line 43 of file AbstractBackgroundThread.cs.
         {
             if (!Running)
             {
                 OnBegin();
                 Task.Run(new Action(Run));
             }
         }
References Juniper.Data.AbstractBackgroundThread.OnBegin(), Juniper.Data.AbstractBackgroundThread.Run(), and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.XR.VuforiaImageAnalyzer.Update().
Execute()
override void Juniper.Data.OneShotThread.Execute () protected virtual
Peform the thread's desired operation.
Implements Juniper.Data.AbstractBackgroundThread.
OnBegin()
virtual void Juniper.Data.AbstractBackgroundThread.OnBegin () protected virtual inherited
Respond to the thread starting.
Reimplemented in Juniper.Data.AbstractBackgroundRepeatingThread.
Referenced by Juniper.Data.AbstractBackgroundThread.Begin().
OnError()
void Juniper.Data.AbstractBackgroundThread.OnError (Exception exp) inline protected inherited
Trigger the Error event handler, if it has any listeners attached to it.
Parameters
exp
Definition at line 26 of file AbstractBackgroundThread.cs.
         {
             if (Running)
             {
                 Error?.Invoke(this, new BackgroundThreadErrorEventArgs(exp));
             }
         }
References Juniper.Data.AbstractBackgroundThread.Error, and Juniper.Data.AbstractBackgroundThread.Running.
Referenced by Juniper.Data.AbstractBackgroundRepeatingThread.Execute(), and Juniper.Data.AbstractBackgroundThread.Run().
Run()
static void Juniper.Data.OneShotThread.Run (Action run) inline static
Creates a background thread that starts right away, executing an action along the way.
Parameters
run The action to execute when the thread runs
Returns
The background thread object that is doing the executing.
Definition at line 15 of file OneShotThread.cs.
         {
 #if NETFX_CORE
             System.Threading.Tasks.Task.Run(act).Start();;
 #else
             var t = new OneShotThread(run);
             t.Begin();
 #endif
         }
References Juniper.Data.OneShotThread.OneShotThread().
Member Data Documentation
callback
readonly Action Juniper.Data.OneShotThread.callback private
The callback to run as the body of the thread.
Definition at line 34 of file OneShotThread.cs.
Referenced by Juniper.Data.OneShotThread.OneShotThread().
Running
virtual bool Juniper.Data.AbstractBackgroundThread.Running inherited
Initial value:
=>
            running
Returns true when the background thread is still running.
Definition at line 19 of file AbstractBackgroundThread.cs.
Referenced by Juniper.Data.AbstractBackgroundThread.Begin(), and Juniper.Data.AbstractBackgroundThread.OnError().
Event Documentation
Error
EventHandler<BackgroundThreadErrorEventArgs> Juniper.Data.AbstractBackgroundThread.Error inherited
An event that triggers if the background operation throws an exception.
Definition at line 14 of file AbstractBackgroundThread.cs.
Referenced by Juniper.Data.AbstractBackgroundThread.OnError().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Common/Data/OneShotThread.cs