Juniper: Hjg.Pngcs.Chunks.PngMetadata Class Reference
Hjg.Pngcs.Chunks.PngMetadata Class Reference
Image Metadata, wrapper over a ChunksList
Public Member Functions
void QueueChunk (AbstractPngChunk chunk, bool lazyOverwrite)
Queues the chunk at the writer
void QueueChunk (AbstractPngChunk chunk)
Queues the chunk at the writer
double [] GetDpi ()
Returns physical resolution, in DPI, in both coordinates
void SetDpi (double dpix, double dpiy)
Sets physical resolution, in DPI
void SetDpi (double dpi)
Sets physical resolution, in DPI, both value in x and y dimensions
PngChunkTIME SetTimeNow (int nsecs)
Creates a TIME chunk, nsecs in the past from now.
PngChunkTIME SetTimeNow ()
Creates a TIME chunk with current time.
PngChunkTIME SetTimeYMDHMS (int year, int mon, int day, int hour, int min, int sec)
Creates a TIME chunk with given date and time
PngChunkTIME GetTime ()
Gets image timestamp, TIME chunk
string GetTimeAsString ()
Gets image timestamp, TIME chunk, as a string
AbstractPngChunkTextVar SetText (string key, string val, bool useLatin1, bool compress)
Creates a text chunk and enqueues it
AbstractPngChunkTextVar SetText (string key, string val)
Creates a plain text chunk (tEXT) and enqueues it
List< AbstractPngChunkTextVar > GetTxtsForKey (string key)
Retrieves all text chunks with a given key
string GetTxtForKey (string key)
Joins all strings for a given key
PngChunkPLTE GetPLTE ()
PngChunkPLTE CreatePLTEChunk ()
PngChunkTRNS GetTRNS ()
PngChunkTRNS CreateTRNSChunk ()
Private Member Functions
internal PngMetadata (ChunksList chunks)
ChunksListForWrite getChunkListW ()
Private Attributes
readonly ChunksList chunkList
readonly bool ReadOnly
Detailed Description
Image Metadata, wrapper over a ChunksList
Additional image info, apart from the ImageInfo and the pixels themselves. Includes Palette and ancillary chunks. This class provides a wrapper over the collection of chunks of a image (read or to write) and provides some high level methods to access them
Definition at line 12 of file PngMetadata.cs.
Constructor & Destructor Documentation
PngMetadata()
internal Hjg.Pngcs.Chunks.PngMetadata.PngMetadata (ChunksList chunks) inline private
Definition at line 17 of file PngMetadata.cs.
         {
             chunkList = chunks;
             ReadOnly = !(chunks is ChunksListForWrite);
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, and Hjg.Pngcs.Chunks.PngMetadata.ReadOnly.
Member Function Documentation
CreatePLTEChunk()
PngChunkPLTE Hjg.Pngcs.Chunks.PngMetadata.CreatePLTEChunk () inline
Definition at line 265 of file PngMetadata.cs.
         {
             var plte = new PngChunkPLTE(chunkList.imageInfo);
             QueueChunk(plte);
             return plte;
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.imageInfo, and Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
CreateTRNSChunk()
PngChunkTRNS Hjg.Pngcs.Chunks.PngMetadata.CreateTRNSChunk () inline
Creates a new empty TRNS chunk, queues it for write and return it to the caller, who should fill its entries
Definition at line 287 of file PngMetadata.cs.
         {
             var trns = new PngChunkTRNS(chunkList.imageInfo);
             QueueChunk(trns);
             return trns;
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.imageInfo, and Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
getChunkListW()
ChunksListForWrite Hjg.Pngcs.Chunks.PngMetadata.getChunkListW () inline private
Definition at line 52 of file PngMetadata.cs.
         {
             return (ChunksListForWrite)chunkList;
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
GetDpi()
double [] Hjg.Pngcs.Chunks.PngMetadata.GetDpi () inline
Returns physical resolution, in DPI, in both coordinates
Returns
[dpix,dpiy], -1 if not set or unknown dimensions
Definition at line 64 of file PngMetadata.cs.
         {
             var c = chunkList.GetById1(ChunkHelper.pHYs, true);
             if (c is null)
             {
                 return new double[] { -1, -1 };
             }
             else
             {
                 return ((PngChunkPHYS)c).GetAsDpi2();
             }
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.GetById1(), and Hjg.Pngcs.Chunks.ChunkHelper.pHYs.
GetPLTE()
PngChunkPLTE Hjg.Pngcs.Chunks.PngMetadata.GetPLTE () inline
Definition at line 260 of file PngMetadata.cs.
         {
             return (PngChunkPLTE)chunkList.GetById1(PngChunkPLTE.ID);
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.GetById1(), and Hjg.Pngcs.Chunks.PngChunkPLTE.ID.
GetTime()
PngChunkTIME Hjg.Pngcs.Chunks.PngMetadata.GetTime () inline
Gets image timestamp, TIME chunk
Returns
TIME chunk, null if not present
Definition at line 144 of file PngMetadata.cs.
         {
             return (PngChunkTIME)chunkList.GetById1(ChunkHelper.tIME);
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.GetById1(), and Hjg.Pngcs.Chunks.ChunkHelper.tIME.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.GetTimeAsString().
GetTimeAsString()
string Hjg.Pngcs.Chunks.PngMetadata.GetTimeAsString () inline
Gets image timestamp, TIME chunk, as a string
Returns
Formated TIME, empty string if not present
Definition at line 153 of file PngMetadata.cs.
         {
             var c = GetTime();
             return c is null ? "" : c.GetAsString();
         }
References Hjg.Pngcs.Chunks.PngMetadata.GetTime().
GetTRNS()
PngChunkTRNS Hjg.Pngcs.Chunks.PngMetadata.GetTRNS () inline
Returns the TRNS chunk, if present
Returns
null if not present
Definition at line 278 of file PngMetadata.cs.
         {
             return (PngChunkTRNS)chunkList.GetById1(PngChunkTRNS.ID);
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.GetById1(), and Hjg.Pngcs.Chunks.PngChunkTRNS.ID.
GetTxtForKey()
string Hjg.Pngcs.Chunks.PngMetadata.GetTxtForKey (string key) inline
Joins all strings for a given key
Parameters
key Key
Returns
Concatenated (with newlines) if several found, empty string if none
You'd perhaps prefer GetTxtsForKey
Definition at line 243 of file PngMetadata.cs.
         {
             var t = "";
             var li = GetTxtsForKey(key);
             if (li.Count == 0)
             {
                 return t;
             }
             foreach (var c in li)
             {
                 t = t + c.Val + "\n";
             }
             return t.Trim();
         }
References Hjg.Pngcs.Chunks.PngMetadata.GetTxtsForKey().
GetTxtsForKey()
List<AbstractPngChunkTextVar> Hjg.Pngcs.Chunks.PngMetadata.GetTxtsForKey (string key) inline
Retrieves all text chunks with a given key
Parameters
key Key
Returns
Empty list if nothing found
Can mix tEXt zTXt and iTXt chunks
Definition at line 216 of file PngMetadata.cs.
         {
             var li = new List<AbstractPngChunkTextVar>();
             foreach (var c in chunkList.GetById(ChunkHelper.tEXt, key))
             {
                 li.Add((AbstractPngChunkTextVar)c);
             }
             foreach (var c in chunkList.GetById(PngChunkZTXT.ID, key))
             {
                 li.Add((AbstractPngChunkTextVar)c);
             }
             foreach (var c in chunkList.GetById(ChunkHelper.iTXt, key))
             {
                 li.Add((AbstractPngChunkTextVar)c);
             }
             return li;
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.GetById(), Hjg.Pngcs.Chunks.PngChunkZTXT.ID, Hjg.Pngcs.Chunks.ChunkHelper.iTXt, and Hjg.Pngcs.Chunks.ChunkHelper.tEXt.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.GetTxtForKey().
QueueChunk() [1/2]
void Hjg.Pngcs.Chunks.PngMetadata.QueueChunk (AbstractPngChunk chunk, bool lazyOverwrite) inline
Queues the chunk at the writer
Parameters
chunk Chunk, ready for write
lazyOverwrite Ovewrite lazily equivalent chunks
Warning: the overwriting applies to equivalent chunks, see ChunkPredicateEquiv and will only make sense for queued (not yet writen) chunks
Definition at line 29 of file PngMetadata.cs.
         {
             var cl = getChunkListW();
             if (ReadOnly)
             {
                 throw new PngjException("cannot set chunk : readonly metadata");
             }
             if (lazyOverwrite)
             {
                 ChunkHelper.TrimList(cl.GetQueuedChunks(), new ChunkPredicateEquiv(chunk));
             }
             cl.Queue(chunk);
         }
References Hjg.Pngcs.Chunks.PngMetadata.getChunkListW(), Hjg.Pngcs.Chunks.PngMetadata.ReadOnly, and Hjg.Pngcs.Chunks.ChunkHelper.TrimList().
Referenced by Hjg.Pngcs.Chunks.PngMetadata.CreatePLTEChunk(), Hjg.Pngcs.Chunks.PngMetadata.CreateTRNSChunk(), Hjg.Pngcs.Chunks.PngMetadata.QueueChunk(), Hjg.Pngcs.Chunks.PngMetadata.SetDpi(), Hjg.Pngcs.Chunks.PngMetadata.SetText(), Hjg.Pngcs.Chunks.PngMetadata.SetTimeNow(), and Hjg.Pngcs.Chunks.PngMetadata.SetTimeYMDHMS().
QueueChunk() [2/2]
void Hjg.Pngcs.Chunks.PngMetadata.QueueChunk (AbstractPngChunk chunk) inline
Queues the chunk at the writer
Parameters
chunk Chunk, ready for write
Definition at line 47 of file PngMetadata.cs.
         {
             QueueChunk(chunk, true);
         }
References Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
SetDpi() [1/2]
void Hjg.Pngcs.Chunks.PngMetadata.SetDpi (double dpix, double dpiy) inline
Sets physical resolution, in DPI
This is a utility method that creates and enqueues a PHYS chunk
Parameters
dpix Resolution in x
dpiy Resolution in y
Definition at line 83 of file PngMetadata.cs.
         {
             var c = new PngChunkPHYS(chunkList.imageInfo);
             c.SetAsDpi2(dpix, dpiy);
             QueueChunk(c);
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.imageInfo, and Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
Referenced by Hjg.Pngcs.Chunks.PngMetadata.SetDpi().
SetDpi() [2/2]
void Hjg.Pngcs.Chunks.PngMetadata.SetDpi (double dpi) inline
Sets physical resolution, in DPI, both value in x and y dimensions
This is a utility method that creates and enqueues a PHYS chunk
Parameters
dpi Resolution in dpi
Definition at line 95 of file PngMetadata.cs.
         {
             SetDpi(dpi, dpi);
         }
References Hjg.Pngcs.Chunks.PngMetadata.SetDpi().
SetText() [1/2]
AbstractPngChunkTextVar Hjg.Pngcs.Chunks.PngMetadata.SetText (string key, string val, bool useLatin1, bool compress) inline
Creates a text chunk and enqueues it
Parameters
key Key. Short and ASCII string
val Text.
useLatin1 Flag. If false, will use UTF-8 (iTXt)
compress Flag. Uses zTXt chunk.
Returns
The created and enqueued chunk
Definition at line 169 of file PngMetadata.cs.
         {
             if (compress && !useLatin1)
             {
                 throw new PngjException("cannot compress non latin text");
             }
             AbstractPngChunkTextVar c;
             if (useLatin1)
             {
                 if (compress)
                 {
                     c = new PngChunkZTXT(chunkList.imageInfo);
                 }
                 else
                 {
                     c = new PngChunkTEXT(chunkList.imageInfo);
                 }
             }
             else
             {
                 c = new PngChunkITXT(chunkList.imageInfo);
                 ((PngChunkITXT)c).SetLangtag(key); // we use the same orig tag (this is not quite right)
             }
             c.SetKeyVal(key, val);
             QueueChunk(c, true);
             return c;
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.imageInfo, Hjg.Pngcs.Chunks.PngMetadata.QueueChunk(), and Hjg.Pngcs.Chunks.AbstractPngChunkTextVar.SetKeyVal().
Referenced by Hjg.Pngcs.Chunks.PngMetadata.SetText().
SetText() [2/2]
AbstractPngChunkTextVar Hjg.Pngcs.Chunks.PngMetadata.SetText (string key, string val) inline
Creates a plain text chunk (tEXT) and enqueues it
Parameters
key Key
val Text
Returns
The created and enqueued chunk
Definition at line 205 of file PngMetadata.cs.
         {
             return SetText(key, val, false, false);
         }
References Hjg.Pngcs.Chunks.PngMetadata.SetText().
SetTimeNow() [1/2]
PngChunkTIME Hjg.Pngcs.Chunks.PngMetadata.SetTimeNow (int nsecs) inline
Creates a TIME chunk, nsecs in the past from now.
Parameters
nsecs Seconds in the past. If negative, it's a future time
Returns
The created and queued chunk
Definition at line 105 of file PngMetadata.cs.
         {
             var c = new PngChunkTIME(chunkList.imageInfo);
             c.SetNow(nsecs);
             QueueChunk(c);
             return c;
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.imageInfo, and Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
SetTimeNow() [2/2]
PngChunkTIME Hjg.Pngcs.Chunks.PngMetadata.SetTimeNow () inline
Creates a TIME chunk with current time.
Returns
The created and queued chunk
Definition at line 117 of file PngMetadata.cs.
         {
             return SetTimeNow(0);
         }
SetTimeYMDHMS()
PngChunkTIME Hjg.Pngcs.Chunks.PngMetadata.SetTimeYMDHMS (int year, int mon, int day, int hour, int min, int sec) inline
Creates a TIME chunk with given date and time
Parameters
year Year
mon Month (1-12)
day Day of month (1-31)
hour Hour (0-23)
min Minute (0-59)
sec Seconds (0-59)
Returns
The created and queued chunk
Definition at line 132 of file PngMetadata.cs.
         {
             var c = new PngChunkTIME(chunkList.imageInfo);
             c.SetYMDHMS(year, mon, day, hour, min, sec);
             QueueChunk(c, true);
             return c;
         }
References Hjg.Pngcs.Chunks.PngMetadata.chunkList, Hjg.Pngcs.Chunks.ChunksList.imageInfo, and Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
Member Data Documentation
chunkList
readonly ChunksList Hjg.Pngcs.Chunks.PngMetadata.chunkList private
Definition at line 14 of file PngMetadata.cs.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.CreatePLTEChunk(), Hjg.Pngcs.Chunks.PngMetadata.CreateTRNSChunk(), Hjg.Pngcs.Chunks.PngMetadata.getChunkListW(), Hjg.Pngcs.Chunks.PngMetadata.GetDpi(), Hjg.Pngcs.Chunks.PngMetadata.GetPLTE(), Hjg.Pngcs.Chunks.PngMetadata.GetTime(), Hjg.Pngcs.Chunks.PngMetadata.GetTRNS(), Hjg.Pngcs.Chunks.PngMetadata.GetTxtsForKey(), Hjg.Pngcs.Chunks.PngMetadata.PngMetadata(), Hjg.Pngcs.Chunks.PngMetadata.SetDpi(), Hjg.Pngcs.Chunks.PngMetadata.SetText(), Hjg.Pngcs.Chunks.PngMetadata.SetTimeNow(), and Hjg.Pngcs.Chunks.PngMetadata.SetTimeYMDHMS().
ReadOnly
readonly bool Hjg.Pngcs.Chunks.PngMetadata.ReadOnly private
Definition at line 15 of file PngMetadata.cs.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.PngMetadata(), and Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Chunks/PngMetadata.cs