Juniper: BitMiracle.LibJpeg.Classic.JpegSourceManager Class Reference
BitMiracle.LibJpeg.Classic.JpegSourceManager Class Reference abstract
Data source object for decompression.
Public Member Functions
abstract void InitSource ()
Initializes this instance.
abstract bool FillInputBuffer ()
Fills input buffer
virtual void SkipInputData (int num_bytes)
Skip data - used to skip over a potentially large amount of uninteresting data (such as an APPn marker).
virtual bool ReSyncToRestart (JpegDecompressStruct cinfo, int desired)
This is the default resync_to_restart method for data source managers to use if they don't have any better approach.
virtual void TermSource ()
Terminate source - called by jpeg_finish_decompress after all data has been read. Often a no-op.
virtual bool GetTwoBytes (out int V)
Reads two bytes interpreted as an unsigned 16-bit integer.
virtual bool GetByte (out int V)
Read a byte into variable V. If must suspend, take the specified action (typically "return false").
virtual int GetBytes (byte[] dest, int amount)
Gets the bytes.
virtual bool MakeByteAvailable ()
Functions for fetching data from the data source module.
Protected Member Functions
void InitInternalBuffer (byte[] buffer, int size)
Initializes the internal buffer.
Private Attributes
byte [] nextInputByte
int bytesInBuffer
int position
Detailed Description
Data source object for decompression.
Definition at line 6 of file JpegSourceManager.cs.
Member Function Documentation
FillInputBuffer()
abstract bool BitMiracle.LibJpeg.Classic.JpegSourceManager.FillInputBuffer () pure virtual
Fills input buffer
Returns
true if operation succeed; otherwise, false
Implemented in BitMiracle.LibJpeg.Classic.Internal.MySourceManager.
Referenced by BitMiracle.LibJpeg.Classic.JpegSourceManager.MakeByteAvailable(), and BitMiracle.LibJpeg.Classic.JpegSourceManager.SkipInputData().
GetByte()
virtual bool BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte (out int V) inline virtual
Read a byte into variable V. If must suspend, take the specified action (typically "return false").
Parameters
V The result.
Returns
true if operation succeed; otherwise, false
Definition at line 238 of file JpegSourceManager.cs.
         {
             if (!MakeByteAvailable())
             {
                 V = 0;
                 return false;
             }
             bytesInBuffer--;
             V = nextInputByte[position];
             position++;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.bytesInBuffer, BitMiracle.LibJpeg.Classic.JpegSourceManager.MakeByteAvailable(), BitMiracle.LibJpeg.Classic.JpegSourceManager.nextInputByte, and BitMiracle.LibJpeg.Classic.JpegSourceManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker().
GetBytes()
virtual int BitMiracle.LibJpeg.Classic.JpegSourceManager.GetBytes (byte [] dest, int amount) inline virtual
Gets the bytes.
Parameters
dest The destination.
amount The amount.
Returns
The number of available bytes.
Definition at line 258 of file JpegSourceManager.cs.
         {
             if (dest is null)
             {
                 throw new System.ArgumentNullException(nameof(dest));
             }
             var avail = amount;
             if (avail > bytesInBuffer)
             {
                 avail = bytesInBuffer;
             }
             for (var i = 0; i < avail; i++)
             {
                 dest[i] = nextInputByte[position];
                 position++;
                 bytesInBuffer--;
             }
             return avail;
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.bytesInBuffer, BitMiracle.LibJpeg.Classic.JpegSourceManager.nextInputByte, and BitMiracle.LibJpeg.Classic.JpegSourceManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker().
GetTwoBytes()
virtual bool BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes (out int V) inline virtual
Reads two bytes interpreted as an unsigned 16-bit integer.
Parameters
V The result.
Returns
true if operation succeed; otherwise, false
Definition at line 209 of file JpegSourceManager.cs.
         {
             if (!MakeByteAvailable())
             {
                 V = 0;
                 return false;
             }
             bytesInBuffer--;
             V = nextInputByte[position] << 8;
             position++;
             if (!MakeByteAvailable())
             {
                 return false;
             }
             bytesInBuffer--;
             V += nextInputByte[position];
             position++;
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.bytesInBuffer, BitMiracle.LibJpeg.Classic.JpegSourceManager.MakeByteAvailable(), BitMiracle.LibJpeg.Classic.JpegSourceManager.nextInputByte, and BitMiracle.LibJpeg.Classic.JpegSourceManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable().
InitInternalBuffer()
void BitMiracle.LibJpeg.Classic.JpegSourceManager.InitInternalBuffer (byte [] buffer, int size) inline protected
Initializes the internal buffer.
Parameters
buffer The buffer.
size The size.
Definition at line 28 of file JpegSourceManager.cs.
         {
             bytesInBuffer = size;
             nextInputByte = buffer;
             position = 0;
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.bytesInBuffer, BitMiracle.LibJpeg.Classic.JpegSourceManager.nextInputByte, and BitMiracle.LibJpeg.Classic.JpegSourceManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MySourceManager.Attach(), and BitMiracle.LibJpeg.Classic.Internal.MySourceManager.FillInputBuffer().
InitSource()
abstract void BitMiracle.LibJpeg.Classic.JpegSourceManager.InitSource () pure virtual
Initializes this instance.
Implemented in BitMiracle.LibJpeg.Classic.Internal.MySourceManager.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInputStart().
MakeByteAvailable()
virtual bool BitMiracle.LibJpeg.Classic.JpegSourceManager.MakeByteAvailable () inline virtual
Functions for fetching data from the data source module.
Returns
true if operation succeed; otherwise, false
At all times, cinfo.src.next_input_byte and .bytes_in_buffer reflect the current restart point; we update them only when we have reached a suitable place to restart if a suspension occurs.
Definition at line 288 of file JpegSourceManager.cs.
         {
             if (bytesInBuffer == 0)
             {
                 if (!FillInputBuffer())
                 {
                     return false;
                 }
             }
             return true;
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.bytesInBuffer, and BitMiracle.LibJpeg.Classic.JpegSourceManager.FillInputBuffer().
Referenced by BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker().
ReSyncToRestart()
virtual bool BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart (JpegDecompressStruct cinfo, int desired) inline virtual
This is the default resync_to_restart method for data source managers to use if they don't have any better approach.
Parameters
cinfo An instance of JpegDecompressStruct
desired The desired
Returns
false if suspension is required.
That method assumes that no backtracking is possible. Some data source managers may be able to back up, or may have additional knowledge about the data which permits a more intelligent recovery strategy; such managers would presumably supply their own resync method.
read_restart_marker calls resync_to_restart if it finds a marker other than the restart marker it was expecting. (This code is not used unless a nonzero restart interval has been declared.) cinfo.unread_marker is the marker code actually found (might be anything, except 0 or FF). The desired restart marker number (0..7) is passed as a parameter.
This routine is supposed to apply whatever error recovery strategy seems appropriate in order to position the input stream to the next data segment. Note that cinfo.unread_marker is treated as a marker appearing before the current data-source input point; usually it should be reset to zero before returning.
This implementation is substantially constrained by wanting to treat the input as a data stream; this means we can't back up. Therefore, we have only the following actions to work with:
Simply discard the marker and let the entropy decoder resume at next byte of file.
Read forward until we find another marker, discarding intervening data. (In theory we could look ahead within the current bufferload, without having to discard data if we don't find the desired marker. This idea is not implemented here, in part because it makes behavior dependent on buffer size and chance buffer-boundary positions.)
Leave the marker unread (by failing to zero cinfo.unread_marker). This will cause the entropy decoder to process an empty data segment, inserting dummy zeroes, and then we will reprocess the marker.
#2 is appropriate if we think the desired marker lies ahead, while #3 is appropriate if the found marker is a future restart marker (indicating that we have missed the desired restart marker, probably because it got corrupted).
We apply #2 or #3 if the found marker is a restart marker no more than two counts behind or ahead of the expected one. We also apply #2 if the found marker is not a legal JPEG marker code (it's certainly bogus data). If the found marker is a restart marker more than 2 counts away, we do #1 (too much risk that the marker is erroneous; with luck we will be able to resync at some future point).
For any valid non-restart JPEG marker, we apply #3. This keeps us from overrunning the end of a scan. An implementation limited to single-scan files might find it better to apply #2 for markers other than EOI, since any other marker would have to be bogus data in that case.
Definition at line 127 of file JpegSourceManager.cs.
         {
             if (cinfo is null)
             {
                 throw new System.ArgumentNullException(nameof(cinfo));
             }
             /* Always put up a warning. */
             cinfo.WarnMS(JMessageCode.JWRN_MUST_RESYNC, cinfo.m_unreadMarker, desired);
             while (true)
             {
                 /* Outer loop handles repeated decision after scanning forward. */
                 int action;
                 if (cinfo.m_unreadMarker < (int)JpegMarker.SOF0)
                 {
                     /* invalid marker */
                     action = 2;
                 }
                 else if (cinfo.m_unreadMarker < (int)JpegMarker.RST0
                     || cinfo.m_unreadMarker > (int)JpegMarker.RST7)
                 {
                     /* valid non-restart marker */
                     action = 3;
                 }
                 else if (cinfo.m_unreadMarker == ((int)JpegMarker.RST0 + ((desired + 1) & 7))
                     || cinfo.m_unreadMarker == ((int)JpegMarker.RST0 + ((desired + 2) & 7)))
                 {
                     /* one of the next two expected restarts */
                     action = 3;
                 }
                 else if (cinfo.m_unreadMarker == ((int)JpegMarker.RST0 + ((desired - 1) & 7))
                     || cinfo.m_unreadMarker == ((int)JpegMarker.RST0 + ((desired - 2) & 7)))
                 {
                     /* a prior restart, so advance */
                     action = 2;
                 }
                 else
                 {
                     /* desired restart or too far away */
                     action = 1;
                 }
                 cinfo.TraceMS(4, JMessageCode.JTRC_RECOVERY_ACTION, cinfo.m_unreadMarker, action);
                 switch (action)
                 {
                     case 1:
                     /* Discard marker and let entropy decoder resume processing. */
                     cinfo.m_unreadMarker = 0;
                     return true;
                     case 2:
                     /* Scan to the next marker, and repeat the decision loop. */
                     if (!cinfo.m_marker.NextMarker())
                     {
                         return false;
                     }
                     break;
                     case 3:
                     /* Return without advancing past this marker. */
                     /* Entropy decoder will be forced to process an empty segment. */
                     return true;
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_unreadMarker, BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker().
SkipInputData()
virtual void BitMiracle.LibJpeg.Classic.JpegSourceManager.SkipInputData (int num_bytes) inline virtual
Skip data - used to skip over a potentially large amount of uninteresting data (such as an APPn marker).
Parameters
num_bytes The number of bytes to skip.
Writers of suspendable-input applications must note that skip_input_data is not granted the right to give a suspension return. If the skip extends beyond the data currently in the buffer, the buffer can be marked empty so that the next read will cause a fill_input_buffer call that can suspend. Arranging for additional bytes to be discarded before reloading the input buffer is the application writer's problem.
Definition at line 46 of file JpegSourceManager.cs.
         {
             /* Just a dumb implementation for now.  Could use fseek() except
             * it doesn't work on pipes.  Not clear that being smart is worth
             * any trouble anyway --- large skips are infrequent.
             */
             if (num_bytes > 0)
             {
                 while (num_bytes > bytesInBuffer)
                 {
                     num_bytes -= bytesInBuffer;
                     FillInputBuffer();
                     /* note we assume that fill_input_buffer will never return false,
                     * so suspension need not be handled.
                     */
                 }
                 position += num_bytes;
                 bytesInBuffer -= num_bytes;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegSourceManager.bytesInBuffer, BitMiracle.LibJpeg.Classic.JpegSourceManager.FillInputBuffer(), and BitMiracle.LibJpeg.Classic.JpegSourceManager.position.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable().
TermSource()
virtual void BitMiracle.LibJpeg.Classic.JpegSourceManager.TermSource () inline virtual
Terminate source - called by jpeg_finish_decompress after all data has been read. Often a no-op.
NB: not called by jpeg_abort or jpeg_destroy; surrounding application must deal with any cleanup that should happen even for error exit.
Definition at line 200 of file JpegSourceManager.cs.
         {
         }
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress().
Member Data Documentation
bytesInBuffer
int BitMiracle.LibJpeg.Classic.JpegSourceManager.bytesInBuffer private
Definition at line 9 of file JpegSourceManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetBytes(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JpegSourceManager.InitInternalBuffer(), BitMiracle.LibJpeg.Classic.JpegSourceManager.MakeByteAvailable(), and BitMiracle.LibJpeg.Classic.JpegSourceManager.SkipInputData().
nextInputByte
byte [] BitMiracle.LibJpeg.Classic.JpegSourceManager.nextInputByte private
Definition at line 8 of file JpegSourceManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetBytes(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), and BitMiracle.LibJpeg.Classic.JpegSourceManager.InitInternalBuffer().
position
int BitMiracle.LibJpeg.Classic.JpegSourceManager.position private
Definition at line 10 of file JpegSourceManager.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegSourceManager.GetByte(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetBytes(), BitMiracle.LibJpeg.Classic.JpegSourceManager.GetTwoBytes(), BitMiracle.LibJpeg.Classic.JpegSourceManager.InitInternalBuffer(), and BitMiracle.LibJpeg.Classic.JpegSourceManager.SkipInputData().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/JpegSourceManager.cs