Juniper: Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager Class Reference
Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager Class Reference
An editor to respond to changes in XRSystem.
Static Public Member Functions
static bool SetAndroid_MenuItem_Validate ()
static void SetAndroid_MenuItem ()
static bool SetAndroid_ARCore_MenuItem_Validate ()
static void SetAndroid_ARCore_MenuItem ()
static bool SetAndroid_Cardboard_MenuItem_Validate ()
static void SetAndroid_Cardboard_MenuItem ()
static bool SetAndroid_Daydream_MenuItem_Validate ()
static void SetAndroid_Daydream_MenuItem ()
static bool SetAndroid_Oculus_MenuItem_Validate ()
static void SetAndroid_Oculus_MenuItem ()
static bool SetAndroid_PicoG2_MenuItem_Validate ()
static void SetAndroid_PicoG2_MenuItem ()
static bool SetAndroid_ViveFocus_MenuItem_Validate ()
static void SetAndroid_ViveFocus_MenuItem ()
static bool SetIOS_MenuItem_Validate ()
static void SetIOS_MenuItem ()
static bool SetIOS_ARKit_MenuItem_Validate ()
static void SetIOS_ARKit_MenuItem ()
static bool SetIOS_Cardboard_MenuItem_Validate ()
static void SetIOS_Cardboard_MenuItem ()
static bool SetStandalone_MenuItem_Validate ()
static void SetStandalone_MenuItem ()
static bool SetStandalone_Oculus_MenuItem_Validate ()
static void SetStandalone_Oculus_MenuItem ()
static bool SetStandalone_SteamVR_MenuItem_Validate ()
static void SetStandalone_SteamVR_MenuItem ()
static bool SetUWP_MenuItem_Validate ()
static void SetUWP_MenuItem ()
static bool SetUWP_WindowsMR_MenuItem_Validate ()
static void SetUWP_WindowsMR_MenuItem ()
static bool SetUWP_HoloLens_MenuItem_Validate ()
static void SetUWP_HoloLens_MenuItem ()
static bool SetMagicLeap_MenuItem_Validate ()
static void SetMagicLeap_MenuItem ()
static bool SetWebGL_MenuItem_Validate ()
static void SetWebGL_MenuItem ()
static void ClearProgressDialog_MenuItem ()
static void Other_ResetConfiguration ()
static bool Other_ResumeBuild_Validate ()
static void Other_ResumeBuild ()
static void RefreshPackages ()
static void PrepareProject ()
Properties
static int BuildProgress [get, set]
static PlatformTypes CurrentPlatform [get]
static PlatformTypes DesiredPlatform [get]
static bool BuildInProgress [get]
static bool RebuildNeeded [get]
static PlatformTypes NextPlatform [get, set]
static PlatformConfiguration LastConfiguration [get]
static PlatformConfiguration NextConfiguration [get]
static string [] JUNIPER_DEFINES [get]
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
Static Private Member Functions
static JuniperConfigurationManager ()
static bool Config_PlatformChanged ()
static bool MenuCheck (PlatformTypes p)
static void OnCancel ()
static void OnCancel (bool canceledByUser)
static void OnEditorUpdate (Action resolve, Action reject=null, Func< bool > test=null)
static void DelayedUpdate (IProgress prog, float maxTime, Action onComplete)
static List< string > CleanupDefines (IEnumerable< string > defs)
static IProgress PrepareBuildStep (int offset, string prefix=null)
static void WithProgress (string prefix, Action< IProgress > act)
static void Recompile (bool advanceBuildStep, params PlatformConfiguration[] platforms)
static void InternalCompile (bool advanceBuildStep, params PlatformConfiguration[] platforms)
static void ResumeBuild ()
static void StartBuild ()
static void DeactivatePlatform ()
Private Attributes
const string MENU_NAME = "Juniper/"
const string ANDROID_MENU_NAME = MENU_NAME + "Android/"
const string IOS_MENU_NAME = MENU_NAME + "IOS/"
const string STANDALONE_MENU_NAME = MENU_NAME + "Standalone/"
const string UWP_MENU_NAME = MENU_NAME + "UWP/"
const string OTHER_MENU_NAME = MENU_NAME + "Other/"
const string RECOMPILE_SLUG = "RECOMPILE_SLUG"
Static Private Attributes
static readonly ProjectConfiguration config
static string LastPrefix
static readonly Action [] STAGES
static readonly string MANIFEST_FILE
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 25 of file JuniperConfigurationManager.cs.
Constructor & Destructor Documentation
JuniperConfigurationManager()
static Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager () inline static private
Definition at line 31 of file JuniperConfigurationManager.cs.
         {
             config = ProjectConfiguration.Load();
             config.PlatformChanged += Config_PlatformChanged;
             config.PlatformChangeConfirmed += StartBuild;
             if (RebuildNeeded)
             {
                 OnEditorUpdate(() =>
                     NextPlatform = DesiredPlatform,
                     () => EditorUtility.DisplayDialog("Juniper", "Could not change platform.", "OK"));
             }
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DesiredPlatform, Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Load(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.PlatformChangeConfirmed, Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.PlatformChanged, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RebuildNeeded, and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
Member Function Documentation
CleanupDefines()
static List<string> Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.CleanupDefines (IEnumerable< string > defs) inline static private
Definition at line 509 of file JuniperConfigurationManager.cs.
         {
             var defines = defs.Distinct().ToList();
             defines.RemoveAll(string.IsNullOrWhiteSpace);
             defines.Sort();
             // move the slug to the end, if it exists
             if (defines.Contains(RECOMPILE_SLUG))
             {
                 defines.Remove(RECOMPILE_SLUG);
                 defines.Add(RECOMPILE_SLUG);
             }
             return defines;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalCompile().
ClearProgressDialog_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ClearProgressDialog_MenuItem () inline static
Definition at line 421 of file JuniperConfigurationManager.cs.
         {
             EditorUtility.ClearProgressBar();
         }
Config_PlatformChanged()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged () inline static private
Definition at line 103 of file JuniperConfigurationManager.cs.
         {
             var platforms = new Platforms();
             if (!platforms.PlatformDB[config.NextPlatform].IsSupported)
             {
                 EditorUtility.DisplayDialog(
                    "Juniper",
                    $"The platform {config.NextPlatform} is not supported on your current system.",
                    "OK");
                 return false;
             }
             else
             {
                 return config.NextPlatform == PlatformTypes.None
                     || (config.NextPlatform != CurrentPlatform
                         && EditorUtility.DisplayDialog(
                             "Juniper",
                             $"You are about to change the platform from {CurrentPlatform} to {config.NextPlatform}. Do you want to continue?",
                             "Change platform",
                             "Don't change platform"));
             }
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform, and Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.NextPlatform.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
DeactivatePlatform()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform () inline static private
Definition at line 652 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Resetting to base configuration", _ =>
             {
                 JuniperPlatform.Uninstall();
                 LastConfiguration.Deactivate(NextConfiguration);
                 Recompile(true, LastConfiguration, NextConfiguration);
             });
         }
References Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Deactivate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.Unity.JuniperPlatform.Uninstall(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
DelayedUpdate()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate (IProgress prog, float maxTime, Action onComplete) inline static private
Definition at line 493 of file JuniperConfigurationManager.cs.
         {
             prog?.Report(0);
             var startTime = DateTime.Now;
             OnEditorUpdate(() =>
             {
                 EditorUtility.ClearProgressBar();
                 onComplete();
             }, OnCancel, () =>
             {
                 var age = (float)(DateTime.Now - startTime).TotalSeconds;
                 prog?.Report(age, maxTime);
                 return age > maxTime;
             });
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), and Juniper.Progress.IProgress.Report().
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Recompile().
InternalCompile()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalCompile (bool advanceBuildStep, params PlatformConfiguration [] platforms) inline static private
Definition at line 564 of file JuniperConfigurationManager.cs.
         {
             if (advanceBuildStep)
             {
                 ++BuildProgress;
             }
             var commonDefines = platforms
                 .SelectMany(p => p.CompilerDefines)
                 .GroupBy(d => d)
                 .Where(defs => defs.Count() == platforms.Length)
                 .SelectMany(defs => defs)
                 .Distinct()
                 .ToList();
             var currentDefines = CleanupDefines(PlayerSettings
                 .GetScriptingDefineSymbolsForGroup(platforms[0].TargetGroup)
                 .Split(';'))
                 .ToList();
             var nonJuniper = currentDefines
                 .Exclude(JUNIPER_DEFINES)
                 .Where(def => !def.StartsWith("NO_UNITY"))
                 .Distinct()
                 .ToList();
             var nextDefines = nonJuniper
                 .Union(commonDefines)
                 .ToList();
             nextDefines = CleanupDefines(nextDefines);
             if (nextDefines.Matches(currentDefines))
             {
                 if (nextDefines.Contains(RECOMPILE_SLUG))
                 {
                     nextDefines.Remove(RECOMPILE_SLUG);
                 }
                 else
                 {
                     nextDefines.Add(RECOMPILE_SLUG);
                 }
             }
             var nextDefinesString = string.Join(";", nextDefines);
             var targetGroups = platforms
                 .Select(p => p.TargetGroup)
                 .Distinct()
                 .Reverse()
                 .ToArray();
             foreach(var targetGroup in targetGroups)
             {
                 PlayerSettings.SetScriptingDefineSymbolsForGroup(targetGroup, nextDefinesString);
             }
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.CleanupDefines(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JUNIPER_DEFINES, and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Recompile(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
MenuCheck()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck (PlatformTypes p) inline static private
Definition at line 159 of file JuniperConfigurationManager.cs.
         {
             return CurrentPlatform != p && new Platforms().PlatformDB[p].IsSupported;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform, and Juniper.UnityEditor.ConfigurationManagement.Platforms.PlatformDB.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_PicoG2_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem_Validate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem_Validate(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetWebGL_MenuItem_Validate().
OnCancel() [1/2]
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnCancel () inline static private
Definition at line 450 of file JuniperConfigurationManager.cs.
         {
             OnCancel(true);
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareProject(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
OnCancel() [2/2]
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnCancel (bool canceledByUser) inline static private
Definition at line 455 of file JuniperConfigurationManager.cs.
         {
             if (canceledByUser)
             {
                 Debug.LogWarning("Canceled by user");
             }
             EditorUtility.ClearProgressBar();
             BuildProgress = -1;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, and Juniper.XR.Debug.
OnEditorUpdate()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate (Action resolve, Action reject = null, Func< bool > test = null) inline static private
Definition at line 465 of file JuniperConfigurationManager.cs.
         {
             if (test == null)
             {
                 test = () => true;
             }
             EditorApplication.CallbackFunction exec = null;
             exec = () =>
             {
                 if (test())
                 {
                     try
                     {
                         EditorApplication.update -= exec;
                         resolve();
                     }
                     catch (OperationCanceledException)
                     {
                         EditorApplication.update -= exec;
                         reject();
                     }
                 }
             };
             EditorApplication.update += exec;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
Other_ResetConfiguration()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Other_ResetConfiguration () inline static
Definition at line 427 of file JuniperConfigurationManager.cs.
         {
             StartBuild();
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
Other_ResumeBuild()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild () inline static
Definition at line 439 of file JuniperConfigurationManager.cs.
         {
             ResumeBuild();
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
Other_ResumeBuild_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild_Validate () inline static
Definition at line 433 of file JuniperConfigurationManager.cs.
         {
             return BuildInProgress;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress.
PrepareBuildStep()
static IProgress Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep (int offset, string prefix = null) inline static private
Definition at line 527 of file JuniperConfigurationManager.cs.
         {
             LastPrefix = prefix ?? LastPrefix;
             var step = BuildProgress - offset + 1;
             var msg = $"Juniper ({step} of {STAGES.Length}): {LastPrefix}";
             return new UnityEditorProgressDialog(msg)
                 .Subdivide(step + BuildProgress, 2 * STAGES.Length, LastPrefix);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.LastPrefix, and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.STAGES.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Recompile(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
PrepareProject()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareProject () inline static
Definition at line 703 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Preparing project", prog =>
             {
                 NextConfiguration.Activate(prog);
                 JuniperPlatform.Install(true);
                 config.Commit();
                 OnCancel(false);
             });
         }
References Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.UnityEditor.ConfigurationManagement.ProjectConfiguration.Commit(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.Unity.JuniperPlatform.Install(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Recompile()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Recompile (bool advanceBuildStep, params PlatformConfiguration [] platforms) inline static private
Definition at line 555 of file JuniperConfigurationManager.cs.
         {
             var prog = PrepareBuildStep(1);
             InternalCompile(advanceBuildStep, platforms);
             DelayedUpdate(prog, 30, () => Debug.LogWarning("Timeout!!!"));
         }
References Juniper.XR.Debug, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalCompile(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep().
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform().
RefreshPackages()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages () inline static
Definition at line 662 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Refreshing packages " + NextPlatform, prog =>
             {
                 var progs = prog.Split(4);
                 LastConfiguration.UninstallRawPackages(progs[0]);
                 var manifest = JObject.Parse(File.ReadAllText(MANIFEST_FILE));
                 var deps = (JObject)manifest["dependencies"];
                 if (deps == null)
                 {
                     deps = new JObject();
                     manifest.Add("dependencies", deps);
                 }
                 UnityPackage.Dependencies = deps;
                 LastConfiguration.UninstallUnityPackages(progs[1]);
                 NextConfiguration.InstallUnityPackages(progs[2]);
                 var txt = manifest.ToString(Formatting.Indented);
                 FileExt.WriteAllText(MANIFEST_FILE, txt);
                 NextConfiguration.InstallRawPackages(progs[3]);
                 if (NextConfiguration.TargetSwitchNeeded)
                 {
                     InternalCompile(false, NextConfiguration);
                     NextConfiguration.SwitchTarget();
                 }
                 else
                 {
                     InternalCompile(true, NextConfiguration);
                     AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate | ImportAssetOptions.ImportRecursive);
                     if (!EditorApplication.isCompiling)
                     {
                         ResumeBuild();
                     }
                 }
             });
         }
References Juniper.UnityEditor.ConfigurationManagement.UnityPackage.Dependencies, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallRawPackages(), Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalCompile(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MANIFEST_FILE, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild(), Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.SwitchTarget(), Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.TargetSwitchNeeded, Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages(), Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.WithProgress(), and System.IO.FileExt.WriteAllText().
ResumeBuild()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild () inline static private
Definition at line 630 of file JuniperConfigurationManager.cs.
         {
             if (BuildInProgress)
             {
                 STAGES[BuildProgress].Invoke();
             }
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.STAGES.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
SetAndroid_ARCore_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem () inline static
Definition at line 191 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidARCore;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_ARCore_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem_Validate () inline static
Definition at line 181 of file JuniperConfigurationManager.cs.
         {
 #if UNITY_2018_2_OR_NEWER
             return MenuCheck(PlatformTypes.AndroidARCore);
 #else
             return false;
 #endif
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Cardboard_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem () inline static
Definition at line 203 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidCardboard;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Cardboard_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem_Validate () inline static
Definition at line 197 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidCardboard);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Daydream_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem () inline static
Definition at line 215 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidDaydream;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Daydream_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem_Validate () inline static
Definition at line 209 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidDaydream);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem () inline static
Definition at line 175 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.Android;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem_Validate () inline static
Definition at line 169 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.Android);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Oculus_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem () inline static
Definition at line 227 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidOculus;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Oculus_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem_Validate () inline static
Definition at line 221 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidOculus);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_PicoG2_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_PicoG2_MenuItem () inline static
Definition at line 239 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidPicoG2;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_PicoG2_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_PicoG2_MenuItem_Validate () inline static
Definition at line 233 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidPicoG2);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_ViveFocus_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem () inline static
Definition at line 251 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidViveFocus;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_ViveFocus_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem_Validate () inline static
Definition at line 245 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidViveFocus);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_ARKit_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem () inline static
Definition at line 281 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOSARKit;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_ARKit_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem_Validate () inline static
Definition at line 275 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOSARKit);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_Cardboard_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem () inline static
Definition at line 293 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOSCardboard;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_Cardboard_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem_Validate () inline static
Definition at line 287 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOSCardboard);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem () inline static
Definition at line 269 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOS;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem_Validate () inline static
Definition at line 263 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOS);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetMagicLeap_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem () inline static
Definition at line 393 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.MagicLeap;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetMagicLeap_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem_Validate () inline static
Definition at line 387 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.MagicLeap);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem () inline static
Definition at line 311 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.Standalone;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem_Validate () inline static
Definition at line 305 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.Standalone);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_Oculus_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem () inline static
Definition at line 323 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.StandaloneOculus;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_Oculus_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem_Validate () inline static
Definition at line 317 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.StandaloneOculus);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_SteamVR_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem () inline static
Definition at line 335 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.StandaloneSteamVR;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_SteamVR_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem_Validate () inline static
Definition at line 329 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.StandaloneSteamVR);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_HoloLens_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem () inline static
Definition at line 377 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWPHoloLens;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_HoloLens_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem_Validate () inline static
Definition at line 371 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWPHoloLens);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem () inline static
Definition at line 353 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWP;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem_Validate () inline static
Definition at line 347 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWP);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_WindowsMR_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem () inline static
Definition at line 365 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWPWindowsMR;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_WindowsMR_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem_Validate () inline static
Definition at line 359 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWPWindowsMR);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetWebGL_MenuItem()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetWebGL_MenuItem () inline static
Definition at line 409 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.WebGL;
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetWebGL_MenuItem_Validate()
static bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetWebGL_MenuItem_Validate () inline static
Definition at line 403 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.WebGL);
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
StartBuild()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.StartBuild () inline static private
Definition at line 646 of file JuniperConfigurationManager.cs.
         {
             BuildProgress = 0;
             DeactivatePlatform();
         }
References Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform().
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Other_ResetConfiguration().
WithProgress()
static void Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.WithProgress (string prefix, Action< IProgress > act) inline static private
Definition at line 536 of file JuniperConfigurationManager.cs.
         {
             try
             {
                 Debug.Log("Juniper: " + prefix);
                 var prog = PrepareBuildStep(0, prefix);
                 prog.Report(0);
                 act(prog);
             }
             catch (OperationCanceledException)
             {
                 OnCancel();
             }
             catch (Exception exp)
             {
                 Debug.LogException(exp);
             }
         }
References Juniper.XR.Debug, Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep().
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareProject(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Member Data Documentation
ANDROID_MENU_NAME
const string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ANDROID_MENU_NAME = MENU_NAME + "Android/" private
Definition at line 166 of file JuniperConfigurationManager.cs.
config
readonly ProjectConfiguration Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.config static private
Definition at line 29 of file JuniperConfigurationManager.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareProject().
IOS_MENU_NAME
const string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.IOS_MENU_NAME = MENU_NAME + "IOS/" private
Definition at line 260 of file JuniperConfigurationManager.cs.
LastPrefix
string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.LastPrefix static private
Definition at line 525 of file JuniperConfigurationManager.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep().
MANIFEST_FILE
readonly string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MANIFEST_FILE static private
Initial value:
= PathExt.FixPath(
            "UnityPackageManager/manifest.json"
        )
Definition at line 638 of file JuniperConfigurationManager.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
MENU_NAME
const string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MENU_NAME = "Juniper/" private
Definition at line 27 of file JuniperConfigurationManager.cs.
OTHER_MENU_NAME
const string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OTHER_MENU_NAME = MENU_NAME + "Other/" private
Definition at line 418 of file JuniperConfigurationManager.cs.
RECOMPILE_SLUG
const string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG = "RECOMPILE_SLUG" private
Definition at line 448 of file JuniperConfigurationManager.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.CleanupDefines(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalCompile().
STAGES
readonly Action [] Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.STAGES static private
Initial value:
=
        {
            DeactivatePlatform,
            RefreshPackages,
            PrepareProject
        }
Definition at line 622 of file JuniperConfigurationManager.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
STANDALONE_MENU_NAME
const string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.STANDALONE_MENU_NAME = MENU_NAME + "Standalone/" private
Definition at line 302 of file JuniperConfigurationManager.cs.
UWP_MENU_NAME
const string Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.UWP_MENU_NAME = MENU_NAME + "UWP/" private
Definition at line 344 of file JuniperConfigurationManager.cs.
Property Documentation
BuildInProgress
bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress static get private
Definition at line 75 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return 0 <= BuildProgress && BuildProgress < STAGES.Length;
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild_Validate(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
BuildProgress
int Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.BuildProgress static get set private
Definition at line 46 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.BuildStep;
             }
             set
             {
                 config.BuildStep = value;
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalCompile(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
CurrentPlatform
PlatformTypes Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform static get private
Definition at line 59 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return JuniperPlatform.CurrentPlatform;
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
DesiredPlatform
PlatformTypes Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DesiredPlatform static get private
Definition at line 67 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.CurrentPlatform;
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
JUNIPER_DEFINES
string [] Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JUNIPER_DEFINES static get private
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
Definition at line 147 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 var platforms = new Platforms();
                 var d = platforms.AllCompilerDefines.ToList();
                 d.Add(RECOMPILE_SLUG);
                 return d.Distinct().ToArray();
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalCompile().
LastConfiguration
PlatformConfiguration Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration static get private
Definition at line 127 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return new Platforms().PlatformDB.Get(CurrentPlatform);
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
NextConfiguration
PlatformConfiguration Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration static get private
Definition at line 135 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return new Platforms().PlatformDB.Get(NextPlatform);
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.PrepareProject(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
NextPlatform
PlatformTypes Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.NextPlatform static get set private
Definition at line 91 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.NextPlatform;
             }
             set
             {
                 config.NextPlatform = value;
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_PicoG2_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem(), Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.SetWebGL_MenuItem().
RebuildNeeded
bool Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.RebuildNeeded static get private
Definition at line 83 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return DesiredPlatform != CurrentPlatform && !BuildInProgress;
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Editor/ConfigurationManagement/JuniperConfigurationManager.cs