import { G } from "./EmojiGroup";
import {
    kissMark,
    loveLetter,
    beatingHeart,
    brokenHeart,
    twoHearts,
    sparklingHeart,
    growingHeart,
    heartWithArrow,
    blueHeart,
    greenHeart,
    yellowHeart,
    purpleHeart,
    heartWithRibbon,
    revolvingHearts,
    heartDecoration,
    blackHeart,
    whiteHeart,
    brownHeart,
    orangeHeart,
    heartExclamation,
    redHeart,
} from ".";

export const love = /*@__PURE__*/ G(
    "Love", "Hearts and kisses", {
        kissMark,
        loveLetter,
        beatingHeart,
        brokenHeart,
        twoHearts,
        sparklingHeart,
        growingHeart,
        heartWithArrow,
        blueHeart,
        greenHeart,
        yellowHeart,
        purpleHeart,
        heartWithRibbon,
        revolvingHearts,
        heartDecoration,
        blackHeart,
        whiteHeart,
        brownHeart,
        orangeHeart,
        heartExclamation,
        redHeart,
    });
