Juniper: Juniper.World.GIS.Google.MapTiles.MarkerStyle Class Reference
Juniper.World.GIS.Google.MapTiles.MarkerStyle Class Reference
Public Member Functions
MarkerStyle (string color=null, char label=char.MinValue, MarkerSize size=MarkerSize.normal)
void GetObjectData (SerializationInfo info, StreamingContext context)
override string ToString ()
override bool Equals (object obj)
bool Equals (MarkerStyle other)
override int GetHashCode ()
Static Public Member Functions
static MarkerStyle CustomIcon (Uri image)
static MarkerStyle CustomIcon (Uri image, MarkerAnchorPosition anchorPosition)
static MarkerStyle CustomIcon (Uri image, int anchorX, int anchorY)
static operator string (MarkerStyle style)
static bool operator== (MarkerStyle left, MarkerStyle right)
static bool operator != (MarkerStyle left, MarkerStyle right)
Private Member Functions
MarkerStyle (string style)
MarkerStyle (SerializationInfo info, StreamingContext context)
Private Attributes
readonly string styleDef
Detailed Description
Definition at line 10 of file MarkerStyle.cs.
Constructor & Destructor Documentation
MarkerStyle() [1/3]
Juniper.World.GIS.Google.MapTiles.MarkerStyle.MarkerStyle (string style) inline private
Definition at line 29 of file MarkerStyle.cs.
         {
             styleDef = style;
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.styleDef.
Referenced by Juniper.World.GIS.Google.MapTiles.MarkerStyle.CustomIcon().
MarkerStyle() [2/3]
Juniper.World.GIS.Google.MapTiles.MarkerStyle.MarkerStyle (string color = null, char label = char.MinValue, MarkerSize size = MarkerSize.normal) inline
Definition at line 34 of file MarkerStyle.cs.
         {
             if (label != char.MinValue && !char.IsLetterOrDigit(label))
             {
                 throw new ArgumentException("Value must be an uppercase letter A-Z or a digit 0-9.", nameof(label));
             }
             var sb = new StringBuilder();
             void delim(bool check, string name, string value)
             {
                 if (check)
                 {
                     if (sb.Length > 0)
                     {
                         sb.Append('|');
                     }
                     sb.Append(name);
                     sb.Append(':');
                     sb.Append(value);
                 }
             }
             delim(size != MarkerSize.normal, nameof(size), size.ToString());
             delim(!string.IsNullOrEmpty(color), nameof(color), color);
             delim(char.IsLetterOrDigit(label), nameof(label), label.ToString(CultureInfo.InvariantCulture));
             styleDef = sb.ToString();
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.styleDef.
MarkerStyle() [3/3]
Juniper.World.GIS.Google.MapTiles.MarkerStyle.MarkerStyle (SerializationInfo info, StreamingContext context) inline private
Definition at line 66 of file MarkerStyle.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             throw new NotImplementedException();
         }
Member Function Documentation
CustomIcon() [1/3]
static MarkerStyle Juniper.World.GIS.Google.MapTiles.MarkerStyle.CustomIcon (Uri image) inline static
Definition at line 12 of file MarkerStyle.cs.
         {
             return new MarkerStyle($"icon:{image}");
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.MarkerStyle().
CustomIcon() [2/3]
static MarkerStyle Juniper.World.GIS.Google.MapTiles.MarkerStyle.CustomIcon (Uri image, MarkerAnchorPosition anchorPosition) inline static
Definition at line 17 of file MarkerStyle.cs.
         {
             return new MarkerStyle($"anchor:{anchorPosition.ToString()}:icon:{image}");
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.MarkerStyle().
CustomIcon() [3/3]
static MarkerStyle Juniper.World.GIS.Google.MapTiles.MarkerStyle.CustomIcon (Uri image, int anchorX, int anchorY) inline static
Definition at line 22 of file MarkerStyle.cs.
         {
             return new MarkerStyle($"anchor:{anchorX.ToString(CultureInfo.InvariantCulture)},{anchorY.ToString(CultureInfo.InvariantCulture)}|icon:{image}");
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.MarkerStyle().
Equals() [1/2]
override bool Juniper.World.GIS.Google.MapTiles.MarkerStyle.Equals (object obj) inline
Definition at line 96 of file MarkerStyle.cs.
         {
             return obj is MarkerStyle style && Equals(style);
         }
Equals() [2/2]
bool Juniper.World.GIS.Google.MapTiles.MarkerStyle.Equals (MarkerStyle other) inline
Definition at line 101 of file MarkerStyle.cs.
         {
             return other is object
                 && styleDef == other.styleDef;
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.styleDef.
GetHashCode()
override int Juniper.World.GIS.Google.MapTiles.MarkerStyle.GetHashCode () inline
Definition at line 107 of file MarkerStyle.cs.
         {
             return -340221435 + EqualityComparer<string>.Default.GetHashCode(styleDef);
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.styleDef.
GetObjectData()
void Juniper.World.GIS.Google.MapTiles.MarkerStyle.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 76 of file MarkerStyle.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             throw new NotImplementedException();
         }
operator !=()
static bool Juniper.World.GIS.Google.MapTiles.MarkerStyle.operator != (MarkerStyle left, MarkerStyle right) inline static
Definition at line 118 of file MarkerStyle.cs.
         {
             return !(left == right);
         }
References Juniper.World.GIS.Google.MapTiles.left, and Juniper.World.GIS.Google.MapTiles.right.
operator string()
static Juniper.World.GIS.Google.MapTiles.MarkerStyle.operator string (MarkerStyle style) inline explicit static
Definition at line 91 of file MarkerStyle.cs.
         {
             return style?.ToString();
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.ToString().
operator==()
static bool Juniper.World.GIS.Google.MapTiles.MarkerStyle.operator== (MarkerStyle left, MarkerStyle right) inline static
Definition at line 112 of file MarkerStyle.cs.
         {
             return ReferenceEquals(left, right)
                 || (left is object && left.Equals(right));
         }
References Juniper.World.GIS.Google.MapTiles.left, and Juniper.World.GIS.Google.MapTiles.right.
ToString()
override string Juniper.World.GIS.Google.MapTiles.MarkerStyle.ToString () inline
Definition at line 86 of file MarkerStyle.cs.
         {
             return styleDef;
         }
References Juniper.World.GIS.Google.MapTiles.MarkerStyle.styleDef.
Referenced by Juniper.World.GIS.Google.MapTiles.MarkerStyle.operator string().
Member Data Documentation
styleDef
readonly string Juniper.World.GIS.Google.MapTiles.MarkerStyle.styleDef private
Definition at line 27 of file MarkerStyle.cs.
Referenced by Juniper.World.GIS.Google.MapTiles.MarkerStyle.Equals(), Juniper.World.GIS.Google.MapTiles.MarkerStyle.GetHashCode(), Juniper.World.GIS.Google.MapTiles.MarkerStyle.MarkerStyle(), and Juniper.World.GIS.Google.MapTiles.MarkerStyle.ToString().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/MapTiles/MarkerStyle.cs