Juniper: Juniper.Unity.Animation.WorkflowStep Class Reference
Juniper.Unity.Animation.WorkflowStep Class Reference
A series of workflow steps can be used to show different UI elements and have other transitions and logic applied as they are flipped through in sequence.
Public Member Functions
WorkflowStep (Transform view, string animationClip)
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
WorkflowStep (Transform view)
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
WorkflowStep (Transform view, Action action)
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
WorkflowStep (Action action)
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
WorkflowStep (Transform view, string animationClip, Action action)
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
void Show (Animator model)
Enter the step, playing any optionals animations on the provided model and finally executing the optional logic.
Properties
AbstractTransitionController? Transition [get]
Get the StateController from step, if one exists.
Private Member Functions
void SetButtonsEnabled (bool enabled)
Sets all of the contained buttons to either enabled or disabled.
void DisableButtons ()
Sets all of the contained buttons to disabled.
void EnableButtons ()
Sets all of the contained buttons to enabled.
Private Attributes
readonly Transform step
The (optional) UI element to display when the step is active.
readonly Button [] buttons
Any clicky buttons that are included in step.
readonly string animationClipName
The (optional) animation to play on a 3D model when the step is entered.
readonly Action act
The (optional) ancillary logic to execute when the step is entered.
Detailed Description
A series of workflow steps can be used to show different UI elements and have other transitions and logic applied as they are flipped through in sequence.
Definition at line 17 of file WorkflowStep.cs.
Constructor & Destructor Documentation
WorkflowStep() [1/5]
Juniper.Unity.Animation.WorkflowStep.WorkflowStep (Transform view, string animationClip) inline
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
Parameters
view View.
animationClip Animation clip.
Definition at line 24 of file WorkflowStep.cs.
             : this(view, animationClip, null)
         {
         }
WorkflowStep() [2/5]
Juniper.Unity.Animation.WorkflowStep.WorkflowStep (Transform view) inline
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
Parameters
view View.
Definition at line 33 of file WorkflowStep.cs.
             : this(view, null, null)
         {
         }
WorkflowStep() [3/5]
Juniper.Unity.Animation.WorkflowStep.WorkflowStep (Transform view, Action action) inline
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
Parameters
view View.
action Action.
Definition at line 43 of file WorkflowStep.cs.
             : this(view, null, action)
         {
         }
WorkflowStep() [4/5]
Juniper.Unity.Animation.WorkflowStep.WorkflowStep (Action action) inline
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
Parameters
action Action.
Definition at line 52 of file WorkflowStep.cs.
             : this(null, null, action)
         {
         }
WorkflowStep() [5/5]
Juniper.Unity.Animation.WorkflowStep.WorkflowStep (Transform view, string animationClip, Action action) inline
Initializes a new instance of the T:Juniper.Animation.WorkflowStep class.
Parameters
view View.
animationClip Animation clip.
action Action.
Definition at line 63 of file WorkflowStep.cs.
         {
             step = view;
 #if UNITY_MODULES_ANIMATION
             animationClipName = animationClip;
 #endif
             act = action;
             if (step != null)
             {
                 buttons = step.GetComponentsInChildren<Button>(true).ToArray();
                 foreach (var btn in buttons)
                 {
                     btn.onClick.AddListener(DisableButtons);
                 }
             }
         }
References Juniper.Unity.Animation.WorkflowStep.act, Juniper.Unity.Animation.WorkflowStep.animationClipName, Juniper.Unity.Animation.WorkflowStep.buttons, Juniper.Unity.Animation.WorkflowStep.DisableButtons(), and Juniper.Unity.Animation.WorkflowStep.step.
Member Function Documentation
DisableButtons()
void Juniper.Unity.Animation.WorkflowStep.DisableButtons () inline private
Sets all of the contained buttons to disabled.
Definition at line 161 of file WorkflowStep.cs.
         {
             SetButtonsEnabled(false);
         }
References Juniper.Unity.Animation.WorkflowStep.SetButtonsEnabled().
Referenced by Juniper.Unity.Animation.WorkflowStep.WorkflowStep().
EnableButtons()
void Juniper.Unity.Animation.WorkflowStep.EnableButtons () inline private
Sets all of the contained buttons to enabled.
Definition at line 169 of file WorkflowStep.cs.
         {
             SetButtonsEnabled(true);
         }
References Juniper.Unity.Animation.WorkflowStep.SetButtonsEnabled().
Referenced by Juniper.Unity.Animation.WorkflowStep.Show().
SetButtonsEnabled()
void Juniper.Unity.Animation.WorkflowStep.SetButtonsEnabled (bool enabled) inline private
Sets all of the contained buttons to either enabled or disabled.
Parameters
enabled If set to true enabled.
Definition at line 147 of file WorkflowStep.cs.
         {
             if (buttons != null)
             {
                 foreach (var btn in buttons)
                 {
                     btn.interactable = enabled;
                 }
             }
         }
References Juniper.Unity.Animation.WorkflowStep.buttons.
Referenced by Juniper.Unity.Animation.WorkflowStep.DisableButtons(), and Juniper.Unity.Animation.WorkflowStep.EnableButtons().
Show()
void Juniper.Unity.Animation.WorkflowStep.Show (Animator model) inline
Enter the step, playing any optionals animations on the provided model and finally executing the optional logic.
Returns
The coroutine.
Parameters
model Model.
Definition at line 99 of file WorkflowStep.cs.
         {
             EnableButtons();
             var trans = Transition;
             trans?.Enter();
             if (trans == null)
             {
                 step?.Activate();
             }
 #if UNITY_MODULES_ANIMATION
             if (animationClipName != null)
             {
                 model.Play(animationClipName);
             }
 #endif
             act?.Invoke();
         }
References Juniper.Unity.Animation.WorkflowStep.act, Juniper.Unity.Animation.WorkflowStep.animationClipName, Juniper.Unity.Animation.WorkflowStep.EnableButtons(), Juniper.Unity.Animation.AbstractTransitionController.Enter(), Juniper.Unity.Animation.WorkflowStep.step, and Juniper.Unity.Animation.WorkflowStep.Transition.
Member Data Documentation
act
readonly Action Juniper.Unity.Animation.WorkflowStep.act private
The (optional) ancillary logic to execute when the step is entered.
Definition at line 141 of file WorkflowStep.cs.
Referenced by Juniper.Unity.Animation.WorkflowStep.Show(), and Juniper.Unity.Animation.WorkflowStep.WorkflowStep().
animationClipName
readonly string Juniper.Unity.Animation.WorkflowStep.animationClipName private
The (optional) animation to play on a 3D model when the step is entered.
Definition at line 135 of file WorkflowStep.cs.
Referenced by Juniper.Unity.Animation.WorkflowStep.Show(), and Juniper.Unity.Animation.WorkflowStep.WorkflowStep().
buttons
readonly Button [] Juniper.Unity.Animation.WorkflowStep.buttons private
Any clicky buttons that are included in step.
Definition at line 129 of file WorkflowStep.cs.
Referenced by Juniper.Unity.Animation.WorkflowStep.SetButtonsEnabled(), and Juniper.Unity.Animation.WorkflowStep.WorkflowStep().
step
readonly Transform Juniper.Unity.Animation.WorkflowStep.step private
The (optional) UI element to display when the step is active.
Definition at line 124 of file WorkflowStep.cs.
Referenced by Juniper.Unity.Animation.WorkflowStep.Show(), and Juniper.Unity.Animation.WorkflowStep.WorkflowStep().
Property Documentation
Transition
AbstractTransitionController? Juniper.Unity.Animation.WorkflowStep.Transition get
Get the StateController from step, if one exists.
The transition.
Definition at line 86 of file WorkflowStep.cs.
         {
             get
             {
                 return step?.GetComponent<AbstractTransitionController>();
             }
         }
Referenced by Juniper.Unity.Animation.WorkflowStep.Show().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Animation/WorkflowStep.cs