Juniper: Juniper.Platform Class Reference
Juniper.Platform Class Reference
Static Public Member Functions
static PlatformTypes Compose (SystemTypes sys, DisplayTypes display, AugmentedRealityTypes ar, Options opt)
static Options GetOption (PlatformTypes p)
static AugmentedRealityTypes GetARType (PlatformTypes p)
static DisplayTypes GetDisplayType (PlatformTypes p)
static SystemTypes GetSystem (PlatformTypes p)
Public Attributes
const int AR_OFFSET = 5
const int DISPLAY_OFFSET = AR_OFFSET + 2
const int SYS_OFFSET = DISPLAY_OFFSET + 2
Static Private Member Functions
static int Get (PlatformTypes p, int start, int end)
Private Attributes
const int TOTAL_OFFSET = SYS_OFFSET + 5
Detailed Description
Definition at line 47 of file PlatformEnums.cs.
Member Function Documentation
Compose()
static PlatformTypes Juniper.Platform.Compose (SystemTypes sys, DisplayTypes display, AugmentedRealityTypes ar, Options opt) inline static
Definition at line 54 of file PlatformEnums.cs.
         {
             return (PlatformTypes)((int)sys << SYS_OFFSET | (int)display << DISPLAY_OFFSET | (int)ar << AR_OFFSET | (int)opt);
         }
References Juniper.Platform.AR_OFFSET, Juniper.Platform.DISPLAY_OFFSET, and Juniper.Platform.SYS_OFFSET.
Get()
static int Juniper.Platform.Get (PlatformTypes p, int start, int end) inline static private
Definition at line 59 of file PlatformEnums.cs.
         {
             return (((1 << start) - 1) & (int)p) >> end;
         }
Referenced by Juniper.Platform.GetARType(), Juniper.Platform.GetDisplayType(), Juniper.Platform.GetOption(), and Juniper.Platform.GetSystem().
GetARType()
static AugmentedRealityTypes Juniper.Platform.GetARType (PlatformTypes p) inline static
Definition at line 69 of file PlatformEnums.cs.
         {
             return (AugmentedRealityTypes)Get(p, DISPLAY_OFFSET, AR_OFFSET);
         }
References Juniper.Platform.AR_OFFSET, Juniper.Platform.DISPLAY_OFFSET, and Juniper.Platform.Get().
GetDisplayType()
static DisplayTypes Juniper.Platform.GetDisplayType (PlatformTypes p) inline static
Definition at line 74 of file PlatformEnums.cs.
         {
             return (DisplayTypes)Get(p, SYS_OFFSET, DISPLAY_OFFSET);
         }
References Juniper.Platform.DISPLAY_OFFSET, Juniper.Platform.Get(), and Juniper.Platform.SYS_OFFSET.
GetOption()
static Options Juniper.Platform.GetOption (PlatformTypes p) inline static
Definition at line 64 of file PlatformEnums.cs.
         {
             return (Options)Get(p, AR_OFFSET, 0);
         }
References Juniper.Platform.AR_OFFSET, and Juniper.Platform.Get().
GetSystem()
static SystemTypes Juniper.Platform.GetSystem (PlatformTypes p) inline static
Definition at line 79 of file PlatformEnums.cs.
         {
             return (SystemTypes)Get(p, TOTAL_OFFSET, SYS_OFFSET);
         }
References Juniper.Platform.Get(), Juniper.Platform.SYS_OFFSET, and Juniper.Platform.TOTAL_OFFSET.
Member Data Documentation
AR_OFFSET
const int Juniper.Platform.AR_OFFSET = 5
Definition at line 49 of file PlatformEnums.cs.
Referenced by Juniper.Platform.Compose(), Juniper.Platform.GetARType(), and Juniper.Platform.GetOption().
DISPLAY_OFFSET
const int Juniper.Platform.DISPLAY_OFFSET = AR_OFFSET + 2
Definition at line 50 of file PlatformEnums.cs.
Referenced by Juniper.Platform.Compose(), Juniper.Platform.GetARType(), and Juniper.Platform.GetDisplayType().
SYS_OFFSET
const int Juniper.Platform.SYS_OFFSET = DISPLAY_OFFSET + 2
Definition at line 51 of file PlatformEnums.cs.
Referenced by Juniper.Platform.Compose(), Juniper.Platform.GetDisplayType(), and Juniper.Platform.GetSystem().
TOTAL_OFFSET
const int Juniper.Platform.TOTAL_OFFSET = SYS_OFFSET + 5 private
Definition at line 52 of file PlatformEnums.cs.
Referenced by Juniper.Platform.GetSystem().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/PlatformEnums.cs