Juniper: Juniper.ConfigurationManagement.UnityPackageManifest Class Reference
Juniper.ConfigurationManagement.UnityPackageManifest Class Reference
Public Member Functions
void Save ()
void GetObjectData (SerializationInfo info, StreamingContext context)
bool ContainsKey (string key)
bool Remove (string key)
bool TryGetValue (string key, out PackageReference value)
void Clear ()
void Add (PackageReference pkg)
void Remove (PackageReference pkg)
Static Public Member Functions
static UnityPackageManifest Load ()
Public Attributes
ICollection< string > Keys => dependencies.Keys
ICollection< PackageReference > Values => dependencies.Values
Properties
PackageReference this[string key] [get, set]
Private Member Functions
UnityPackageManifest (SerializationInfo info, StreamingContext context)
Private Attributes
readonly Dictionary< string, PackageReference > dependencies
Static Private Attributes
static UnityPackageManifest manifest
Detailed Description
Don't give this class the IDictionary<string, string> interface, as it breaks the deserialization process.
Definition at line 16 of file UnityPackageManifest.cs.
Constructor & Destructor Documentation
UnityPackageManifest()
Juniper.ConfigurationManagement.UnityPackageManifest.UnityPackageManifest (SerializationInfo info, StreamingContext context) inline private
Definition at line 61 of file UnityPackageManifest.cs.
         {
             var dict = info.GetValue<Dictionary<string, string>>(nameof(dependencies));
             dependencies = dict.ToDictionary(kv => kv.Key, kv => new PackageReference(PackageReference.FormatUnityPackageManagerSpec(kv.Key, kv.Value)));
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies, and Juniper.ConfigurationManagement.PackageReference.FormatUnityPackageManagerSpec().
Member Function Documentation
Add()
void Juniper.ConfigurationManagement.UnityPackageManifest.Add (PackageReference pkg) inline
Definition at line 98 of file UnityPackageManifest.cs.
         {
             if (pkg is null)
             {
                 throw new ArgumentNullException(nameof(pkg));
             }
             if (pkg.ForRemoval)
             {
                 Remove(pkg);
             }
             else
             {
                 dependencies[pkg.PackageID] = pkg;
                 Save();
             }
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies, Juniper.ConfigurationManagement.PackageReference.ForRemoval, Juniper.ConfigurationManagement.PackageReference.PackageID, Juniper.ConfigurationManagement.UnityPackageManifest.Remove(), and Juniper.ConfigurationManagement.UnityPackageManifest.Save().
Referenced by Juniper.ConfigurationManagement.UnityPackage.Install().
Clear()
void Juniper.ConfigurationManagement.UnityPackageManifest.Clear () inline
Definition at line 93 of file UnityPackageManifest.cs.
         {
             dependencies.Clear();
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies.
ContainsKey()
bool Juniper.ConfigurationManagement.UnityPackageManifest.ContainsKey (string key) inline
Definition at line 78 of file UnityPackageManifest.cs.
         {
             return dependencies.ContainsKey(key);
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies.
Referenced by Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages().
GetObjectData()
void Juniper.ConfigurationManagement.UnityPackageManifest.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 67 of file UnityPackageManifest.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             var dict = dependencies.ToDictionary(kv => kv.Key, kv => kv.Value.VersionSpec);
             info.AddValue(nameof(dependencies), dict);
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies.
Load()
static UnityPackageManifest Juniper.ConfigurationManagement.UnityPackageManifest.Load () inline static
Definition at line 21 of file UnityPackageManifest.cs.
         {
             if (manifest is null)
             {
                 var unityPackageManifestPath = Path.Combine(Project.UnityProjectRoot, "Packages", "manifest.json");
                 var factory = new JsonFactory<UnityPackageManifest>();
                 manifest = factory.Deserialize(unityPackageManifestPath);
             }
             return manifest;
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.manifest, and Juniper.ConfigurationManagement.Project.UnityProjectRoot.
Referenced by Juniper.ConfigurationManagement.UnityPackage.Install(), and Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.OnGUI().
Remove() [1/2]
bool Juniper.ConfigurationManagement.UnityPackageManifest.Remove (string key) inline
Definition at line 83 of file UnityPackageManifest.cs.
         {
             return dependencies.Remove(key);
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies.
Referenced by Juniper.ConfigurationManagement.UnityPackageManifest.Add(), and Juniper.ConfigurationManagement.JuniperRequiredPackageInstaller.DrawRequiredPackages().
Remove() [2/2]
void Juniper.ConfigurationManagement.UnityPackageManifest.Remove (PackageReference pkg) inline
Definition at line 116 of file UnityPackageManifest.cs.
         {
             if (pkg is null)
             {
                 throw new ArgumentNullException(nameof(pkg));
             }
             if (dependencies.ContainsKey(pkg.PackageID))
             {
                 dependencies.Remove(pkg.PackageID);
             }
             Save();
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies, Juniper.ConfigurationManagement.PackageReference.PackageID, and Juniper.ConfigurationManagement.UnityPackageManifest.Save().
Save()
void Juniper.ConfigurationManagement.UnityPackageManifest.Save () inline
Definition at line 33 of file UnityPackageManifest.cs.
         {
             var unityPackageManifestPath = Path.Combine(Project.UnityProjectRoot, "Packages", "manifest.json");
             var factory = new JsonFactory<UnityPackageManifest>();
             factory.Serialize(unityPackageManifestPath, this);
         }
References Juniper.ConfigurationManagement.Project.UnityProjectRoot.
Referenced by Juniper.ConfigurationManagement.UnityPackageManifest.Add(), and Juniper.ConfigurationManagement.UnityPackageManifest.Remove().
TryGetValue()
bool Juniper.ConfigurationManagement.UnityPackageManifest.TryGetValue (string key, out PackageReference value) inline
Definition at line 88 of file UnityPackageManifest.cs.
         {
             return dependencies.TryGetValue(key, out value);
         }
References Juniper.ConfigurationManagement.UnityPackageManifest.dependencies.
Member Data Documentation
dependencies
readonly Dictionary<string, PackageReference> Juniper.ConfigurationManagement.UnityPackageManifest.dependencies private
Definition at line 41 of file UnityPackageManifest.cs.
Referenced by Juniper.ConfigurationManagement.UnityPackageManifest.Add(), Juniper.ConfigurationManagement.UnityPackageManifest.Clear(), Juniper.ConfigurationManagement.UnityPackageManifest.ContainsKey(), Juniper.ConfigurationManagement.UnityPackageManifest.GetObjectData(), Juniper.ConfigurationManagement.UnityPackageManifest.Remove(), Juniper.ConfigurationManagement.UnityPackageManifest.TryGetValue(), and Juniper.ConfigurationManagement.UnityPackageManifest.UnityPackageManifest().
Keys
ICollection<string> Juniper.ConfigurationManagement.UnityPackageManifest.Keys => dependencies.Keys
Definition at line 43 of file UnityPackageManifest.cs.
manifest
UnityPackageManifest Juniper.ConfigurationManagement.UnityPackageManifest.manifest static private
Definition at line 19 of file UnityPackageManifest.cs.
Referenced by Juniper.ConfigurationManagement.UnityPackageManifest.Load().
Values
ICollection<PackageReference> Juniper.ConfigurationManagement.UnityPackageManifest.Values => dependencies.Values
Definition at line 45 of file UnityPackageManifest.cs.
Property Documentation
this[string key]
PackageReference Juniper.ConfigurationManagement.UnityPackageManifest.this[string key] get set
Definition at line 48 of file UnityPackageManifest.cs.
         {
             get
             {
                 return dependencies[key];
             }
             set
             {
                 dependencies[key] = value;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.UnityEditor/ConfigurationManagement/UnityPackageManifest.cs