Juniper: Juniper.Terminal.ConsoleBuffer.NativeMethods Class Reference
Juniper.Terminal.ConsoleBuffer.NativeMethods Class Reference
Classes
struct CONSOLE_FONT_INFO_EX
struct COORD
struct POINT
Private Member Functions
static internal bool GetCursorPos (out POINT point)
static internal IntPtr GetStdHandle (int nStdHandle)
static internal bool SetCurrentConsoleFontEx (IntPtr consoleOutput, bool maximumWindow, CONSOLE_FONT_INFO_EX consoleCurrentFontEx)
Private Attributes
internal const int STD_OUTPUT_HANDLE = -11
internal const int LF_FACESIZE = 32
Static Private Attributes
static internal readonly IntPtr INVALID_HANDLE_VALUE = new IntPtr(-1)
Detailed Description
Definition at line 255 of file ConsoleBuffer.cs.
Member Function Documentation
GetCursorPos()
static internal bool Juniper.Terminal.ConsoleBuffer.NativeMethods.GetCursorPos (out POINT point) private
GetStdHandle()
static internal IntPtr Juniper.Terminal.ConsoleBuffer.NativeMethods.GetStdHandle (int nStdHandle) private
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer().
SetCurrentConsoleFontEx()
static internal bool Juniper.Terminal.ConsoleBuffer.NativeMethods.SetCurrentConsoleFontEx (IntPtr consoleOutput, bool maximumWindow, CONSOLE_FONT_INFO_EX consoleCurrentFontEx) private
Referenced by Juniper.Terminal.ConsoleBuffer.SetFontSize().
Member Data Documentation
INVALID_HANDLE_VALUE
internal readonly IntPtr Juniper.Terminal.ConsoleBuffer.NativeMethods.INVALID_HANDLE_VALUE = new IntPtr(-1) static private
Definition at line 271 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer().
LF_FACESIZE
internal const int Juniper.Terminal.ConsoleBuffer.NativeMethods.LF_FACESIZE = 32 private
Definition at line 270 of file ConsoleBuffer.cs.
STD_OUTPUT_HANDLE
internal const int Juniper.Terminal.ConsoleBuffer.NativeMethods.STD_OUTPUT_HANDLE = -11 private
Definition at line 269 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Terminal/ConsoleBuffer.cs