Juniper: Juniper.Unity.Widgets.LoadingBar Class Reference
Juniper.Unity.Widgets.LoadingBar Class Reference
Public Member Functions
void Report (float progress)
void Report (float progress, string status)
Report progress to a listener implementation.
void Awake ()
void Update ()
Static Public Member Functions
static PooledComponent< LoadingBar > Ensure (Transform parent, int transparentLayer)
Properties
float Progress [get, private set]
float TargetValue [get, set]
WaitUntil Waiter [get]
Private Attributes
Transform indicator
WaitUntil _waiter
Detailed Description
Definition at line 9 of file LoadingBar.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Widgets.LoadingBar.Awake () inline
Definition at line 55 of file LoadingBar.cs.
         {
             indicator = this.Query("Center/Indicator");
         }
References Juniper.Unity.Widgets.LoadingBar.indicator.
Ensure()
static PooledComponent<LoadingBar> Juniper.Unity.Widgets.LoadingBar.Ensure (Transform parent, int transparentLayer) inline static
Definition at line 11 of file LoadingBar.cs.
         {
             var bar = parent.Ensure<Transform>("LoadingBar/Center/Indicator", () =>
                 GameObject.CreatePrimitive(PrimitiveType.Cube))
                 .Value
                 .parent
                 .parent
                 .Ensure<LoadingBar>();
 #if UNITY_MODULES_PHYSICS
             if (bar.IsNew)
             {
                 foreach (var collider in bar.Value.GetComponentsInChildren<Collider>())
                 {
                     collider.Destroy();
                 }
             }
 #endif
             var queue = new Queue<Transform>
             {
                 bar.Value.transform
             };
             while (queue.Count > 0)
             {
                 var here = queue.Dequeue();
                 queue.AddRange(here.Children());
                 here.gameObject.layer = transparentLayer;
             }
             return bar;
         }
Referenced by Juniper.Unity.MasterSceneController.SetupSystemInterface().
Report() [1/2]
void Juniper.Unity.Widgets.LoadingBar.Report (float progress) inline
Definition at line 45 of file LoadingBar.cs.
         {
             Report(progress, null);
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Report() [2/2]
void Juniper.Unity.Widgets.LoadingBar.Report (float progress, string status) inline
Report progress to a listener implementation.
Parameters
progress
status
Implements Juniper.Progress.IProgress.
Definition at line 50 of file LoadingBar.cs.
         {
             TargetValue = progress;
         }
References Juniper.Unity.Widgets.LoadingBar.TargetValue.
Update()
void Juniper.Unity.Widgets.LoadingBar.Update () inline
Definition at line 60 of file LoadingBar.cs.
         {
             Progress = Mathf.Lerp(Progress, TargetValue, 0.1f);
             var s = indicator.transform.localScale;
             s.x = Progress;
             indicator.transform.localScale = s;
             indicator.transform.localPosition = new Vector3(0.5f * (Progress - 1), 0, 0);
         }
References Juniper.Unity.Widgets.LoadingBar.indicator, Juniper.Unity.Widgets.LoadingBar.Progress, and Juniper.Unity.Widgets.LoadingBar.TargetValue.
Member Data Documentation
_waiter
WaitUntil Juniper.Unity.Widgets.LoadingBar._waiter private
Definition at line 81 of file LoadingBar.cs.
indicator
Transform Juniper.Unity.Widgets.LoadingBar.indicator private
Definition at line 69 of file LoadingBar.cs.
Referenced by Juniper.Unity.Widgets.LoadingBar.Awake(), and Juniper.Unity.Widgets.LoadingBar.Update().
Property Documentation
Progress
float Juniper.Unity.Widgets.LoadingBar.Progress get private set
Definition at line 72 of file LoadingBar.cs.
         {
             get; private set;
         }
Referenced by Juniper.Unity.Widgets.LoadingBar.Update().
TargetValue
float Juniper.Unity.Widgets.LoadingBar.TargetValue get set
Definition at line 77 of file LoadingBar.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Widgets.LoadingBar.Report(), and Juniper.Unity.Widgets.LoadingBar.Update().
Waiter
WaitUntil Juniper.Unity.Widgets.LoadingBar.Waiter get
Definition at line 84 of file LoadingBar.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(this.IsComplete);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Widgets/LoadingBar.cs