Juniper: Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType > Class Template Reference
Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType > Class Template Reference abstract
Public Member Functions
void AddButton (VirtualTouchPadButton buttonID, InputEventButton buttonValue)
void RemoveButton (VirtualTouchPadButton buttonID)
void AddButton (VirtualTriggerButton buttonID, InputEventButton buttonValue)
void RemoveButton (VirtualTriggerButton buttonID)
override void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
override void Install (bool reset)
Install, with or without a full reset.
bool IsButtonPressed (VirtualTouchPadButton button)
bool IsButtonDown (VirtualTouchPadButton button)
bool IsButtonUp (VirtualTouchPadButton button)
bool IsButtonPressed (VirtualTriggerButton button)
bool IsButtonDown (VirtualTriggerButton button)
bool IsButtonUp (VirtualTriggerButton button)
override bool IsButtonPressed (InputButton button)
override bool IsButtonUp (InputButton button)
override bool IsButtonDown (InputButton button)
void AddButton (ButtonIDType buttonID, InputEventButton buttonValue)
Add a new button mapping to the pointer.
void RemoveButton (ButtonIDType buttonID)
Remove a button mapping from the pointer.
void Start ()
virtual void Uninstall ()
Remove platform-specific features from the object.
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void OnProbeFound ()
Vector2 ScreenFromWorld (Vector3 worldPoint)
Vector2 ScreenFromViewport (Vector2 viewportPoint)
Vector2 ViewportFromWorld (Vector3 worldPoint)
Vector2 ViewportFromScreen (Vector2 screenPoint)
Vector3 WorldFromScreen (Vector2 screenPoint)
Vector3 WorldFromViewport (Vector2 viewportPoint)
virtual void Update ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
virtual void PlayInteraction (Interaction action)
virtual void Process (PointerEventData evtData, float pixelDragThresholdSquared)
abstract bool IsButtonPressed (ButtonIDType button)
Implementers should return true while the button is depressed.
bool IsButtonPressed (PointerEventData.InputButton button)
abstract bool IsButtonUp (ButtonIDType button)
Implementers should return true when the button is first released.
bool IsButtonUp (PointerEventData.InputButton button)
abstract bool IsButtonDown (ButtonIDType button)
Implementers should return true when a button is first depressed.
bool IsButtonDown (PointerEventData.InputButton button)
Static Public Member Functions
static T [] MakeControllers< T > (Func< string, T > MakePointer)
Public Attributes
Hands _hand
bool Connected
Material LaserPointerMaterial
bool showProbe = true
AbstractMotionFilter motionFilter
Protected Member Functions
override void InternalUpdate ()
override IEventSystemHandler ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared)
PointerEventData Clone (int pointerDataID, PointerEventData evtData)
abstract AbstractHapticDevice MakeHapticsDevice ()
Protected Attributes
readonly ButtonMapper< VirtualTouchPadButton > touchPadButtons = new ButtonMapper<VirtualTouchPadButton>()
readonly ButtonMapper< VirtualTriggerButton > triggerButtons = new ButtonMapper<VirtualTriggerButton>()
readonly ButtonMapper< ButtonIDType > nativeButtons = new ButtonMapper<ButtonIDType>()
Vector3 pointerOffset
IProbe probe
The cursor probe that shows the physical location of the current selection.
AbstractUnifiedInputModule eventManager
Avatar stage
Static Protected Attributes
static readonly Vector2 VIEWPORT_MIDPOINT
static readonly ConfigType PointerConfig
Properties
override bool IsDragging [get]
abstract float Trigger [get]
abstract Vector2 SquareTouchPoint [get]
abstract Vector2 RoundTouchPoint [get]
override bool AnyButtonPressed [get]
abstract bool TouchPadTouched [get]
abstract bool TouchPadTouchedDown [get]
abstract bool TouchPadTouchedUp [get]
abstract bool TouchPadPressed [get]
abstract bool TouchPadPressedDown [get]
abstract bool TouchPadPressedUp [get]
virtual Hands Hand [get, set]
virtual ? HandIDType NativeHandID [get, protected set]
bool IsLeftHand [get]
bool IsRightHand [get]
abstract bool IsDominantHand [get]
bool IsNonDominantHand [get]
override Vector3 WorldPoint [get]
Type ButtonType [get]
int PointerDataID [get]
float MinimumPointerDistance [get]
The minimum distance from the camera at which to place the pointer.
float MaximumPointerDistance [get]
int Layer [get, set]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
abstract bool IsConnected [get]
bool IsEnabled [get]
bool IsDisabled [get]
Returns true when the device is supposed to be disabled.
PhysicsRaycaster? Raycaster [get]
string ProbeName [get]
Vector3 Origin [get]
Vector3 LastOrigin [get, private set]
Vector3 OriginDelta [get]
Vector3 LastWorldPoint [get, private set]
Vector3 WorldDelta [get]
Vector3??? SmoothedWorldPoint [get]
The target at and through which the pointer rays fire.
Vector3 LastSmoothedWorldPoint [get, private set]
Vector3 SmoothedWorldPointDelta [get]
Vector3 Direction [get]
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
Vector3 LastDirection [get]
Vector2 ScreenPoint [get]
Vector2 LastScreenPoint [get]
Vector2 ScreenDelta [get]
Vector2 ViewportPoint [get]
Vector2 LastViewportPoint [get]
Vector2 ViewportDelta [get]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
IInputModule InputModule [get]
AbstractHapticDevice Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
Transform transform [get]
bool isActiveAndEnabled [get]
Private Member Functions
bool VirtualButtonInBounds (VirtualTouchPadButton button)
bool VirtualTriggerButtonThreshold (VirtualTriggerButton button, float triggerValue)
Private Attributes
const float BUTTON_RADIUS = 0.25f
const float DIM = 0.75f
float lastTrigger
Vector2? lastTouchPosition
Static Private Attributes
static readonly Dictionary< VirtualTouchPadButton, Vector2 > BUTTON_CENTERS
static readonly Dictionary< VirtualTriggerButton, float > TRIGGER_THRESHOLDS
Detailed Description
Type Constraints
HandIDType : struct
HandIDType : IComparable
ButtonIDType : struct
ConfigType : AbstractMotionControllerConfiguration
ConfigType : HandIDType
ConfigType : ButtonIDType
ConfigType : new()
Definition at line 37 of file MotionController.cs.
Member Function Documentation
AddButton() [1/3]
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AddButton (ButtonIDType buttonID, InputEventButton buttonValue) inline inherited
Add a new button mapping to the pointer.
Parameters
buttonID
buttonValue
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
Definition at line 39 of file AbstractPointerDevice.cs.
         {
             nativeButtons.AddButton(gameObject, buttonID, buttonValue);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
AddButton() [2/3]
void Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.AddButton (VirtualTouchPadButton buttonID, InputEventButton buttonValue) inline
Definition at line 71 of file MotionController.cs.
         {
             touchPadButtons.AddButton(gameObject, buttonID, buttonValue);
         }
AddButton() [3/3]
void Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.AddButton (VirtualTriggerButton buttonID, InputEventButton buttonValue) inline
Definition at line 83 of file MotionController.cs.
         {
             triggerButtons.AddButton(gameObject, buttonID, buttonValue);
         }
Awake()
override void Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.Awake () inline virtual
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Reimplemented from Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.
Definition at line 103 of file MotionController.cs.
         {
             base.Awake();
             touchPadButtons.ButtonDownNeeded += IsButtonDown;
             touchPadButtons.ButtonUpNeeded += IsButtonUp;
             touchPadButtons.ButtonPressedNeeded += IsButtonPressed;
             touchPadButtons.ClonedPointerEventNeeded += Clone;
             touchPadButtons.InteractionNeeded += PlayInteraction;
             triggerButtons.ButtonDownNeeded += IsButtonDown;
             triggerButtons.ButtonUpNeeded += IsButtonUp;
             triggerButtons.ButtonPressedNeeded += IsButtonPressed;
             triggerButtons.ClonedPointerEventNeeded += Clone;
             triggerButtons.InteractionNeeded += PlayInteraction;
         }
Clone()
PointerEventData Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone (int pointerDataID, PointerEventData evtData) inline protected inherited
Definition at line 492 of file AbstractPointerDevice.cs.
         {
             return InputModule?.Clone(pointerDataID, evtData);
         }
References Juniper.Input.IInputModule.Clone(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InputModule.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
Install()
override void Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Reimplemented from Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.
Definition at line 120 of file MotionController.cs.
         {
             base.Install(reset);
             PointerConfig.Install(touchPadButtons, gameObject);
             PointerConfig.Install(triggerButtons, gameObject);
 #if UNITY_EDITOR
             if (LaserPointerMaterial == null)
             {
                 LaserPointerMaterial = ResourceExt.EditorLoadAsset<Material>("Assets/Juniper/Materials/LaserPointer.mat");
             }
 #endif
         }
InternalUpdate()
override void Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.InternalUpdate () inline protected virtual
Reimplemented from Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.
Definition at line 227 of file MotionController.cs.
         {
             if (TouchPadTouched)
             {
                 var touchPos = SquareTouchPoint;
                 if (lastTouchPosition != null)
                 {
                     ScrollDelta = touchPos - lastTouchPosition.Value;
                 }
                 lastTouchPosition = touchPos;
             }
             else
             {
                 ScrollDelta = Vector2.zero;
                 lastTouchPosition = null;
             }
             lastTrigger = Trigger;
             if (probe != null)
             {
                 probe.TouchPoint = RoundTouchPoint;
             }
         }
IsButtonDown() [1/5]
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonDown (VirtualTouchPadButton button) inline
Implements Juniper.Input.Pointers.Motion.IMotionController.
Definition at line 159 of file MotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressedDown;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake().
IsButtonDown() [2/5]
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonDown (VirtualTriggerButton button) inline
Implements Juniper.Input.Pointers.Motion.IMotionController.
Definition at line 174 of file MotionController.cs.
         {
             return VirtualTriggerButtonThreshold(button, Trigger)
                 && !VirtualTriggerButtonThreshold(button, lastTrigger);
         }
IsButtonDown() [3/5]
bool Juniper.Input.Pointers.IPointerDevice.IsButtonDown (PointerEventData.InputButton button) inherited
IsButtonDown() [4/5]
override bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonDown (InputButton button) inline virtual
Reimplemented from Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.
Definition at line 275 of file MotionController.cs.
         {
             return base.IsButtonDown(button)
                 || touchPadButtons.IsButtonDown(button)
                 || triggerButtons.IsButtonDown(button);
         }
IsButtonDown() [5/5]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown (ButtonIDType button) pure virtual inherited
Implementers should return true when a button is first depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonPressed() [1/5]
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonPressed (VirtualTouchPadButton button) inline
Implements Juniper.Input.Pointers.Motion.IMotionController.
Definition at line 154 of file MotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressed;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake().
IsButtonPressed() [2/5]
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonPressed (VirtualTriggerButton button) inline
Implements Juniper.Input.Pointers.Motion.IMotionController.
Definition at line 169 of file MotionController.cs.
         {
             return VirtualTriggerButtonThreshold(button, Trigger);
         }
IsButtonPressed() [3/5]
bool Juniper.Input.Pointers.IPointerDevice.IsButtonPressed (PointerEventData.InputButton button) inherited
IsButtonPressed() [4/5]
override bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonPressed (InputButton button) inline virtual
Reimplemented from Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.
Definition at line 261 of file MotionController.cs.
         {
             return base.IsButtonPressed(button)
                 || touchPadButtons.IsButtonPressed(button)
                 || triggerButtons.IsButtonPressed(button);
         }
IsButtonPressed() [5/5]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed (ButtonIDType button) pure virtual inherited
Implementers should return true while the button is depressed.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonUp() [1/5]
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonUp (VirtualTouchPadButton button) inline
Implements Juniper.Input.Pointers.Motion.IMotionController.
Definition at line 164 of file MotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressedUp;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake().
IsButtonUp() [2/5]
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonUp (VirtualTriggerButton button) inline
Implements Juniper.Input.Pointers.Motion.IMotionController.
Definition at line 180 of file MotionController.cs.
         {
             return !VirtualTriggerButtonThreshold(button, Trigger)
                 && VirtualTriggerButtonThreshold(button, lastTrigger);
         }
IsButtonUp() [3/5]
bool Juniper.Input.Pointers.IPointerDevice.IsButtonUp (PointerEventData.InputButton button) inherited
IsButtonUp() [4/5]
override bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsButtonUp (InputButton button) inline virtual
Reimplemented from Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.
Definition at line 268 of file MotionController.cs.
         {
             return base.IsButtonUp(button)
                 || touchPadButtons.IsButtonUp(button)
                 || triggerButtons.IsButtonUp(button);
         }
IsButtonUp() [5/5]
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp (ButtonIDType button) pure virtual inherited
Implementers should return true when the button is first released.
Parameters
button
Returns
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
MakeControllers< T >()
static T [] Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.MakeControllers< T > (Func< string, T > MakePointer) inline static inherited
Type Constraints
T : AbstractHandedPointer
T : HandIDType
T : ButtonIDType
T : ConfigType
Definition at line 17 of file AbstractHandedPointer.cs.
                     : AbstractHandedPointer<HandIDType, ButtonIDType, ConfigType>
         {
             return new[] {
                 MakeMotionController(MakePointer, Hands.Left),
                 MakeMotionController(MakePointer, Hands.Right)
             };
         }
MakeHapticsDevice()
abstract AbstractHapticDevice Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MakeHapticsDevice () protected pure virtual inherited
Implemented in Juniper.Input.Pointers.Motion.AbstractHandTracker< HandIDType, ButtonIDType, ConfigType >.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
OnProbeFound()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound () inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 213 of file AbstractPointerDevice.cs.
         {
             if (probe == null)
             {
                 probe = Probe.Ensure(transform, ProbeName);
             }
         }
References Juniper.Input.Pointers.Probe.Ensure(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProbeName, and Juniper.Input.Pointers.IPointerDevice.transform.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install().
PlayInteraction()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction (Interaction action) inline virtual inherited
Definition at line 483 of file AbstractPointerDevice.cs.
         {
             if (Time.unscaledTime > finishTime || action != lastAction)
             {
                 lastAction = action;
                 finishTime = Time.unscaledTime + InteractionAudio.Play(action, probe.Cursor, Haptics);
             }
         }
References Juniper.Input.Pointers.IProbe.Cursor, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.finishTime, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastAction, Juniper.Audio.AbstractInteractionAudio.Play(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit().
Process()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process (PointerEventData evtData, float pixelDragThresholdSquared) inline virtual inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 497 of file AbstractPointerDevice.cs.
         {
             if (!IsDragging)
             {
                 TestEnterExit(evtData);
             }
             EventTarget = ProcessButtons(evtData, pixelDragThresholdSquared);
             if (evtData.clickCount == -1)
             {
                 evtData.clickCount = 0;
             }
             LastWorldPoint = evtData.pointerCurrentRaycast.worldPosition;
             LastSmoothedWorldPoint = SmoothedWorldPoint;
             LastOrigin = Origin;
             probe?.SetCursor(
                 evtData.pointerCurrentRaycast.gameObject != null,
                 AnyButtonPressed,
                 LastWorldPoint,
                 evtData.pointerCurrentRaycast.worldNormal);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AnyButtonPressed, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.EventTarget, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDragging, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastOrigin, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastSmoothedWorldPoint, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastWorldPoint, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Origin, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons(), Juniper.Input.Pointers.IProbe.SetCursor(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPoint, and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.TestEnterExit().
ProcessButtons()
override IEventSystemHandler Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared) inline protected virtual
Reimplemented from Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.
Definition at line 252 of file MotionController.cs.
         {
             var a = base.ProcessButtons(evtData, pixelDragThresholdSquared);
             var b = touchPadButtons.Process(evtData, pixelDragThresholdSquared);
             var c = triggerButtons.Process(evtData, pixelDragThresholdSquared);
             return a ?? b ?? c;
         }
Reinstall()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Reinstall () inline virtual inherited
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 191 of file AbstractPointerDevice.cs.
         {
             Install(true);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install().
RemoveButton() [1/3]
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.RemoveButton (ButtonIDType buttonID) inline inherited
Remove a button mapping from the pointer.
Parameters
buttonID
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
Definition at line 44 of file AbstractPointerDevice.cs.
         {
             nativeButtons.RemoveButton(buttonID);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons.
RemoveButton() [2/3]
void Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.RemoveButton (VirtualTouchPadButton buttonID) inline
Definition at line 76 of file MotionController.cs.
         {
             touchPadButtons.RemoveButton(buttonID);
         }
RemoveButton() [3/3]
void Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.RemoveButton (VirtualTriggerButton buttonID) inline
Definition at line 88 of file MotionController.cs.
         {
             triggerButtons.RemoveButton(buttonID);
         }
ScreenFromViewport()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 378 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToScreenPoint(viewportPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
ScreenFromWorld()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 372 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToScreenPoint(worldPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
Start()
void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start () inline inherited
Definition at line 175 of file AbstractPointerDevice.cs.
         {
             eventManager.AddPointer(this);
         }
References Juniper.Input.AbstractUnifiedInputModule.AddPointer(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager.
Uninstall()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Uninstall () inline virtual inherited
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 186 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Uninstall(gameObject);
         }
References Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig.
Update()
virtual void Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update () inline virtual inherited
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Definition at line 419 of file AbstractPointerDevice.cs.
         {
             if (motionFilter != lastMotionFilter)
             {
 #if UNITY_EDITOR
                 parentMotionFilter = motionFilter;
 #endif
                 motionFilter = Instantiate(motionFilter);
                 lastMotionFilter = motionFilter;
             }
 #if UNITY_EDITOR
             motionFilter?.Copy(parentMotionFilter);
 #endif
             Connected = IsConnected;
             if (probe != null)
             {
                 probe.SetActive(IsEnabled && showProbe);
                 probe.LaserPointerMaterial = LaserPointerMaterial;
             }
             if (IsEnabled)
             {
                 motionFilter?.UpdateState(WorldPoint);
                 InternalUpdate();
                 probe?.AlignProbe(Direction, transform.up);
             }
         }
References Juniper.Input.Pointers.IProbe.AlignProbe(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Connected, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InternalUpdate(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsConnected, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsEnabled, Juniper.Input.Pointers.IProbe.LaserPointerMaterial, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LaserPointerMaterial, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.lastMotionFilter, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.motionFilter, Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe, Juniper.Input.Pointers.IProbe.SetActive(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.showProbe, Juniper.Input.Pointers.IPointerDevice.transform, Juniper.Statistics.AbstractMotionFilter.UpdateState(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldPoint.
ViewportFromScreen()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 390 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToViewportPoint(screenPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
ViewportFromWorld()
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 384 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.WorldToViewportPoint(worldPoint);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, and Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer().
VirtualButtonInBounds()
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.VirtualButtonInBounds (VirtualTouchPadButton button) inline private
Definition at line 282 of file MotionController.cs.
         {
             return button == VirtualTouchPadButton.Any
                 || (BUTTON_CENTERS.ContainsKey(button)
                     && (SquareTouchPoint - BUTTON_CENTERS[button]).magnitude <= BUTTON_RADIUS);
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonPressed(), and Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp().
VirtualTriggerButtonThreshold()
bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.VirtualTriggerButtonThreshold (VirtualTriggerButton button, float triggerValue) inline private
Definition at line 289 of file MotionController.cs.
         {
             return TRIGGER_THRESHOLDS.ContainsKey(button)
                 && triggerValue > TRIGGER_THRESHOLDS[button];
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonPressed(), and Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp().
WorldFromScreen()
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 396 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ScreenToWorldPoint((Vector3)screenPoint + pointerOffset);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset.
WorldFromViewport()
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Input.Pointers.IPointerDevice.
Definition at line 402 of file AbstractPointerDevice.cs.
         {
             DisplayManager.MoveEventCameraToPointer(this);
             return DisplayManager.EventCamera.ViewportToWorldPoint((Vector3)viewportPoint + pointerOffset);
         }
References Juniper.Display.AbstractDisplayManager.EventCamera, Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset.
Member Data Documentation
_hand
Hands Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >._hand inherited
Definition at line 40 of file AbstractHandedPointer.cs.
BUTTON_CENTERS
readonly Dictionary<VirtualTouchPadButton, Vector2> Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.BUTTON_CENTERS static private
Initial value:
= new Dictionary<VirtualTouchPadButton, Vector2>(9)
        {
            { VirtualTouchPadButton.Center, new Vector2(0, 0) },
            { VirtualTouchPadButton.Top, new Vector2(0, DIM) },
            { VirtualTouchPadButton.Right, new Vector2(DIM, 0) },
            { VirtualTouchPadButton.Bottom, new Vector2(0, -DIM) },
            { VirtualTouchPadButton.Left, new Vector2(-DIM, 0) },
            { VirtualTouchPadButton.TopLeft, new Vector2(DIM, -DIM) },
            { VirtualTouchPadButton.TopRight, new Vector2(DIM, DIM) },
            { VirtualTouchPadButton.BottomLeft, new Vector2(-DIM, -DIM) },
            { VirtualTouchPadButton.BottomRight, new Vector2(DIM, -DIM) },
        }
Definition at line 47 of file MotionController.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.VirtualButtonInBounds().
BUTTON_RADIUS
const float Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.BUTTON_RADIUS = 0.25f private
Definition at line 44 of file MotionController.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.VirtualButtonInBounds().
Connected
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Connected inherited
Definition at line 50 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
DIM
const float Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.DIM = 0.75f private
Definition at line 45 of file MotionController.cs.
eventManager
AbstractUnifiedInputModule Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.eventManager protected inherited
Definition at line 450 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start().
LaserPointerMaterial
Material Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LaserPointerMaterial inherited
Definition at line 81 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
lastTouchPosition
Vector2? Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.lastTouchPosition private
Definition at line 152 of file MotionController.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate().
lastTrigger
float Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.lastTrigger private
Definition at line 140 of file MotionController.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown(), and Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp().
motionFilter
AbstractMotionFilter Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.motionFilter inherited
Definition at line 413 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.MakeMotionController< T >(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
nativeButtons
readonly ButtonMapper<ButtonIDType> Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.nativeButtons = new ButtonMapper<ButtonIDType>() protected inherited
Definition at line 37 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.AddButton(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonDown(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonPressed(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsButtonUp(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProcessButtons(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.RemoveButton().
PointerConfig
readonly ConfigType Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerConfig static protected inherited
Initial value:
=
            new ConfigType()
Definition at line 26 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Install(), Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.MakeMotionController< T >(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Uninstall().
pointerOffset
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.pointerOffset protected inherited
Definition at line 71 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromScreen(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldFromViewport().
probe
IProbe Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.probe protected inherited
The cursor probe that shows the physical location of the current selection.
Definition at line 211 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
showProbe
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.showProbe = true inherited
Definition at line 205 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
stage
Avatar Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.stage protected inherited
Definition at line 460 of file AbstractPointerDevice.cs.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
touchPadButtons
readonly ButtonMapper<VirtualTouchPadButton> Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.touchPadButtons = new ButtonMapper<VirtualTouchPadButton>() protected
Definition at line 69 of file MotionController.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.AddButton(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonPressed(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.ProcessButtons(), and Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.RemoveButton().
TRIGGER_THRESHOLDS
readonly Dictionary<VirtualTriggerButton, float> Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.TRIGGER_THRESHOLDS static private
Initial value:
= new Dictionary<VirtualTriggerButton, float>(3)
        {
            { VirtualTriggerButton.Off, 0.1f },
            { VirtualTriggerButton.On, 0.2f },
            { VirtualTriggerButton.Full, 0.8f }
        }
Definition at line 62 of file MotionController.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.VirtualTriggerButtonThreshold().
triggerButtons
readonly ButtonMapper<VirtualTriggerButton> Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.triggerButtons = new ButtonMapper<VirtualTriggerButton>() protected
Definition at line 81 of file MotionController.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.AddButton(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Awake(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.Install(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonPressed(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.ProcessButtons(), and Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.RemoveButton().
VIEWPORT_MIDPOINT
readonly Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.VIEWPORT_MIDPOINT static protected inherited
Initial value:
=
            0.5f * Vector2.one
Definition at line 23 of file AbstractPointerDevice.cs.
Property Documentation
AnyButtonPressed
override bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.AnyButtonPressed get
Definition at line 187 of file MotionController.cs.
         {
             get
             {
                 return base.AnyButtonPressed
                     || IsButtonPressed(VirtualTouchPadButton.Any)
                     || IsButtonPressed(VirtualTriggerButton.On)
                     || IsButtonPressed(VirtualTriggerButton.Full);
             }
         }
ButtonType
Type Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ButtonType get inherited
Definition at line 30 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return typeof(ButtonIDType);
             }
         }
Direction
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Direction get inherited
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
The interaction direction.
Definition at line 300 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (SmoothedWorldPoint - Origin).normalized;
             }
         }
EventTarget
IEventSystemHandler Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.EventTarget get set inherited
Definition at line 107 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Hand
virtual Hands Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.Hand get set inherited
Definition at line 43 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return _hand;
             }
             set
             {
                 _hand = value;
                 NativeHandID = PointerConfig[value];
             }
         }
Haptics
AbstractHapticDevice Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Haptics get protected set inherited
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 476 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PlayInteraction().
InputModule
IInputModule Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.InputModule get inherited
Definition at line 453 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return eventManager;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Clone().
isActiveAndEnabled
bool Juniper.Input.Pointers.IPointerDevice.isActiveAndEnabled get inherited
Definition at line 44 of file IPointerDevice.cs.
         {
             get;
         }
IsConnected
abstract bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsConnected get inherited
Definition at line 112 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
IsDisabled
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsDisabled get inherited
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 129 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return !IsEnabled;
             }
         }
IsDominantHand
abstract bool Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.IsDominantHand get inherited
Definition at line 77 of file AbstractHandedPointer.cs.
         {
             get;
         }
IsDragging
override bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.IsDragging get
Definition at line 94 of file MotionController.cs.
         {
             get
             {
                 return base.IsDragging
                     || EventTarget != null && touchPadButtons.IsDragging
                     || EventTarget != null && triggerButtons.IsDragging;
             }
         }
IsEnabled
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.IsEnabled get inherited
Definition at line 117 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return isActiveAndEnabled && IsConnected;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
IsLeftHand
bool Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.IsLeftHand get inherited
Definition at line 61 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return Hand == Hands.Left;
             }
         }
IsNonDominantHand
bool Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.IsNonDominantHand get inherited
Definition at line 82 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return !IsDominantHand;
             }
         }
IsRightHand
bool Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.IsRightHand get inherited
Definition at line 69 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return Hand == Hands.Right;
             }
         }
LastDirection
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastDirection get inherited
Definition at line 308 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (LastSmoothedWorldPoint - LastOrigin).normalized;
             }
         }
LastOrigin
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastOrigin get private set inherited
Definition at line 238 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
LastScreenPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastScreenPoint get inherited
Definition at line 324 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(LastSmoothedWorldPoint);
             }
         }
LastSmoothedWorldPoint
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastSmoothedWorldPoint get private set inherited
Definition at line 282 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
LastViewportPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastViewportPoint get inherited
Definition at line 348 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(LastSmoothedWorldPoint);
             }
         }
LastWorldPoint
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LastWorldPoint get private set inherited
Definition at line 257 of file AbstractPointerDevice.cs.
         {
             get; private set;
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
Layer
int Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Layer get set inherited
Definition at line 84 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return gameObject.layer;
             }
             set
             {
                 if (value != gameObject.layer)
                 {
                     foreach (var trans in transform.FamilyTree())
                     {
                         trans.gameObject.layer = value;
                     }
                 }
             }
         }
LockedOnTarget
bool Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.LockedOnTarget get set inherited
Definition at line 102 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
MaximumPointerDistance
float Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MaximumPointerDistance get inherited
Definition at line 74 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Min(10f, 0.9f * DisplayManager.MainCamera.farClipPlane);
             }
         }
MinimumPointerDistance
float Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.MinimumPointerDistance get inherited
The minimum distance from the camera at which to place the pointer.
Definition at line 64 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Max(1.5f, 1.1f * DisplayManager.MainCamera.nearClipPlane);
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Awake().
NativeHandID
virtual ? HandIDType Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.NativeHandID get protected set inherited
Definition at line 56 of file AbstractHandedPointer.cs.
         {
             get; protected set;
         }
Origin
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Origin get inherited
Definition at line 230 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return transform.position;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
OriginDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OriginDelta get inherited
Definition at line 244 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Origin - LastOrigin;
             }
         }
PointerDataID
int Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.PointerDataID get inherited
Definition at line 53 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return GetInstanceID();
             }
         }
ProbeName
string Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ProbeName get inherited
Definition at line 222 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return name + "-probe";
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound().
Raycaster
PhysicsRaycaster? Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Raycaster get inherited
Definition at line 137 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.Raycaster;
             }
         }
RoundTouchPoint
abstract Vector2 Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.RoundTouchPoint get
Definition at line 148 of file MotionController.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate().
ScreenDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenDelta get inherited
Definition at line 332 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenPoint - LastScreenPoint;
             }
         }
ScreenPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScreenPoint get inherited
Definition at line 316 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(SmoothedWorldPoint);
             }
         }
ScrollDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ScrollDelta get protected set inherited
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 368 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate().
SmoothedWorldPoint
Vector3??? Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPoint get inherited
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 274 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return motionFilter?.PredictedPosition ?? WorldPoint;
             }
         }
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Process().
SmoothedWorldPointDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.SmoothedWorldPointDelta get inherited
Definition at line 288 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return SmoothedWorldPoint - LastSmoothedWorldPoint;
             }
         }
SquareTouchPoint
abstract Vector2 Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.SquareTouchPoint get
Definition at line 143 of file MotionController.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate(), and Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.VirtualButtonInBounds().
TouchPadPressed
abstract bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.TouchPadPressed get protected
Definition at line 213 of file MotionController.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonPressed().
TouchPadPressedDown
abstract bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.TouchPadPressedDown get protected
Definition at line 218 of file MotionController.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown().
TouchPadPressedUp
abstract bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.TouchPadPressedUp get protected
Definition at line 223 of file MotionController.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp().
TouchPadTouched
abstract bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.TouchPadTouched get protected
Definition at line 198 of file MotionController.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate().
TouchPadTouchedDown
abstract bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.TouchPadTouchedDown get protected
Definition at line 203 of file MotionController.cs.
         {
             get;
         }
TouchPadTouchedUp
abstract bool Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.TouchPadTouchedUp get protected
Definition at line 208 of file MotionController.cs.
         {
             get;
         }
transform
Transform Juniper.Input.Pointers.IPointerDevice.transform get inherited
Definition at line 12 of file IPointerDevice.cs.
 { get;  }
Referenced by Juniper.Display.AbstractDisplayManager.MoveEventCameraToPointer(), Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.OnProbeFound(), and Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Update().
Trigger
abstract float Juniper.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType >.Trigger get
Definition at line 136 of file MotionController.cs.
         {
             get;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.InternalUpdate(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonDown(), Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonPressed(), and Juniper.Input.Pointers.Motion.AbstractMotionController< WVR_DeviceType, WVR_InputId, ViveFocusMotionControllerConfiguration >.IsButtonUp().
ViewportDelta
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportDelta get inherited
Definition at line 356 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportPoint - LastViewportPoint;
             }
         }
ViewportPoint
Vector2 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.ViewportPoint get inherited
Definition at line 340 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(SmoothedWorldPoint);
             }
         }
WorldDelta
Vector3 Juniper.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.WorldDelta get inherited
Definition at line 262 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return WorldPoint - LastWorldPoint;
             }
         }
WorldPoint
override Vector3 Juniper.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType >.WorldPoint get inherited
Definition at line 90 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return transform.position + (MinimumPointerDistance * transform.forward);
             }
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/Pointers/Motion/MotionController.cs