Juniper: Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType > Class Template Reference
Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType > Class Template Reference abstract
Public Member Functions
override void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
override bool Install (bool reset)
bool IsButtonPressed (VirtualTouchPadButton button)
bool IsButtonDown (VirtualTouchPadButton button)
bool IsButtonUp (VirtualTouchPadButton button)
bool IsButtonPressed (VirtualTriggerButton button)
bool IsButtonDown (VirtualTriggerButton button)
bool IsButtonUp (VirtualTriggerButton button)
override bool IsButtonPressed (InputButton button)
override bool IsButtonUp (InputButton button)
override bool IsButtonDown (InputButton button)
void Start ()
virtual void Uninstall ()
virtual void Reinstall ()
virtual void SetProbe (Probe p)
Vector2 ScreenFromWorld (Vector3 worldPoint)
Vector2 ScreenFromViewport (Vector2 viewportPoint)
Vector2 ViewportFromWorld (Vector3 worldPoint)
Vector2 ViewportFromScreen (Vector2 screenPoint)
Vector3 WorldFromScreen (Vector2 screenPoint)
Vector3 WorldFromViewport (Vector2 viewportPoint)
virtual void Update ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
virtual void PlayInteraction (Interaction action)
virtual void Process (PointerEventData evtData, float pixelDragThresholdSquared)
abstract bool IsButtonPressed (ButtonIDType button)
bool IsButtonPressed (PointerEventData.InputButton button)
abstract bool IsButtonUp (ButtonIDType button)
bool IsButtonUp (PointerEventData.InputButton button)
abstract bool IsButtonDown (ButtonIDType button)
bool IsButtonDown (PointerEventData.InputButton button)
Public Attributes
Hands _hand
bool Connected
Material LaserPointerMaterial
bool showProbe = true
AbstractMotionFilter motionFilter
Protected Member Functions
override void InternalUpdate ()
override IEventSystemHandler ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared)
void DraggableChanged (bool dragging)
Static Protected Member Functions
static Vector2 Round2Square (Vector2 point)
static Vector2 Square2Round (Vector2 point)
Protected Attributes
readonly ButtonMapper< VirtualTouchPadButton > touchPadButtons = new ButtonMapper<VirtualTouchPadButton>()
readonly ButtonMapper< VirtualTriggerButton > triggerButtons = new ButtonMapper<VirtualTriggerButton>()
readonly ButtonMapper< ButtonIDType > nativeButtons = new ButtonMapper<ButtonIDType>()
Vector3 pointerOffset
Probe probe
The cursor probe that shows the physical location of the current selection.
AbstractUnifiedInputModule eventManager
StageExtensions stage
Static Protected Attributes
static readonly Vector2 VIEWPORT_MIDPOINT
static readonly ConfigType PointerConfig
Properties
abstract float Trigger [get]
abstract Vector2 SquareTouchPoint [get]
abstract Vector2 RoundTouchPoint [get]
override bool AnyButtonPressed [get]
abstract bool TouchPadTouched [get]
abstract bool TouchPadTouchedDown [get]
abstract bool TouchPadTouchedUp [get]
abstract bool TouchPadPressed [get]
abstract bool TouchPadPressedDown [get]
abstract bool TouchPadPressedUp [get]
virtual Hands Hand [get, set]
HandIDType? NativeHandID [get, protected set]
bool IsLeftHand [get]
bool IsRightHand [get]
abstract bool IsDominantHand [get]
bool IsNonDominantHand [get]
override Vector3 WorldPoint [get]
Type ButtonType [get]
float MinimumPointerDistance [get]
The minimum distance from the camera at which to place the pointer.
float MaximumPointerDistance [get]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
abstract bool IsConnected [get]
bool IsEnabled [get]
bool IsDisabled [get]
Returns true when the device is supposed to be disabled.
PhysicsRaycaster? Raycaster [get]
Camera? EventCamera [get]
The camera the pointer uses to point at Canvas objects.
int PointerID [get, set]
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
string ProbeName [get, private set]
Vector3 Origin [get]
Vector3 LastOrigin [get, private set]
Vector3 OriginDelta [get]
Vector3 LastWorldPoint [get, private set]
Vector3 WorldDelta [get]
Vector3??? SmoothedWorldPoint [get]
The target at and through which the pointer rays fire.
Vector3 LastSmoothedWorldPoint [get, private set]
Vector3 SmoothedWorldPointDelta [get]
Vector3 Direction [get]
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
Vector3 LastDirection [get]
Vector2 ScreenPoint [get]
Vector2 LastScreenPoint [get]
Vector2 ScreenDelta [get]
Vector2 ViewportPoint [get]
Vector2 LastViewportPoint [get]
Vector2 ViewportDelta [get]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
AbstractUnifiedInputModule InputModule [get]
bool IsDragging [get, private set]
HapticsType Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
string name [get]
string name [get]
bool isActiveAndEnabled [get]
Private Member Functions
PointerEventData Clone (PointerEventData evtData, VirtualTouchPadButton button)
PointerEventData Clone (PointerEventData evtData, VirtualTriggerButton button)
bool VirtualButtonInBounds (VirtualTouchPadButton button)
bool VirtualTriggerButtonThreshold (VirtualTriggerButton button, float triggerValue)
Private Attributes
const float BUTTON_RADIUS = 0.25f
const float DIM = 0.75f
float lastTrigger
Vector2? lastTouchPosition
Static Private Attributes
static readonly Dictionary< VirtualTouchPadButton, Vector2 > BUTTON_CENTERS
static readonly Dictionary< VirtualTriggerButton, float > TRIGGER_THRESHOLDS
Detailed Description
Type Constraints
HandIDType : struct
HandIDType : IComparable
ButtonIDType : struct
ConfigType : AbstractMotionControllerConfiguration
ConfigType : HandIDType
ConfigType : ButtonIDType
ConfigType : new()
HapticsType : AbstractHapticDevice
Definition at line 50 of file AbstractMotionController.cs.
Member Function Documentation
Awake()
override void Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Awake () inline virtual
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Reimplemented from Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 86 of file AbstractMotionController.cs.
         {
             base.Awake();
             touchPadButtons.ButtonDownNeeded += IsButtonDown;
             touchPadButtons.ButtonUpNeeded += IsButtonUp;
             touchPadButtons.ButtonPressedNeeded += IsButtonPressed;
             touchPadButtons.ClonedPointerEventNeeded += Clone;
             touchPadButtons.InteractionNeeded += PlayInteraction;
             touchPadButtons.DraggableChanged += DraggableChanged;
             triggerButtons.ButtonDownNeeded += IsButtonDown;
             triggerButtons.ButtonUpNeeded += IsButtonUp;
             triggerButtons.ButtonPressedNeeded += IsButtonPressed;
             triggerButtons.ClonedPointerEventNeeded += Clone;
             triggerButtons.InteractionNeeded += PlayInteraction;
             triggerButtons.DraggableChanged += DraggableChanged;
         }
Clone() [1/2]
PointerEventData Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Clone (PointerEventData evtData, VirtualTouchPadButton button) inline private
Definition at line 124 of file AbstractMotionController.cs.
         {
             return InputModule?.Clone(evtData, touchPadButtons.ToInt32(button) + 100);
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake().
Clone() [2/2]
PointerEventData Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Clone (PointerEventData evtData, VirtualTriggerButton button) inline private
Definition at line 129 of file AbstractMotionController.cs.
         {
             return InputModule?.Clone(evtData, triggerButtons.ToInt32(button) + 200);
         }
DraggableChanged()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.DraggableChanged (bool dragging) inline protected inherited
Definition at line 190 of file AbstractPointerDevice.cs.
         {
             IsDragging = dragging;
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
Install()
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Install (bool reset) inline virtual
Reimplemented from Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 105 of file AbstractMotionController.cs.
         {
             reset &= Application.isEditor;
             base.Install(reset);
             PointerConfig.Install(touchPadButtons, gameObject);
             PointerConfig.Install(triggerButtons, gameObject);
 #if UNITY_EDITOR
             if (LaserPointerMaterial == null)
             {
                 LaserPointerMaterial = ComponentExt.EditorLoadAsset<Material>("Assets/Juniper/Materials/LaserPointer.mat");
             }
 #endif
             return true;
         }
InternalUpdate()
override void Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.InternalUpdate () inline protected virtual
Implements Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 262 of file AbstractMotionController.cs.
         {
             if (TouchPadTouched)
             {
                 var touchPos = SquareTouchPoint;
                 if (lastTouchPosition != null)
                 {
                     ScrollDelta = touchPos - lastTouchPosition.Value;
                 }
                 lastTouchPosition = touchPos;
             }
             else
             {
                 ScrollDelta = Vector2.zero;
                 lastTouchPosition = null;
             }
             lastTrigger = Trigger;
             if (probe != null)
             {
                 probe.TouchPoint = RoundTouchPoint;
             }
         }
IsButtonDown() [1/5]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonDown (VirtualTouchPadButton button) inline
Implements Juniper.Unity.Input.Pointers.Motion.IMotionController.
Definition at line 158 of file AbstractMotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressedDown;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake().
IsButtonDown() [2/5]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonDown (VirtualTriggerButton button) inline
Implements Juniper.Unity.Input.Pointers.Motion.IMotionController.
Definition at line 173 of file AbstractMotionController.cs.
         {
             return VirtualTriggerButtonThreshold(button, Trigger)
                 && !VirtualTriggerButtonThreshold(button, lastTrigger);
         }
IsButtonDown() [3/5]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonDown (PointerEventData.InputButton button) inherited
IsButtonDown() [4/5]
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonDown (InputButton button) inline virtual
Reimplemented from Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 310 of file AbstractMotionController.cs.
         {
             return base.IsButtonDown(button)
                 || touchPadButtons.IsButtonDown(button)
                 || triggerButtons.IsButtonDown(button);
         }
IsButtonDown() [5/5]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonPressed() [1/5]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonPressed (VirtualTouchPadButton button) inline
Implements Juniper.Unity.Input.Pointers.Motion.IMotionController.
Definition at line 153 of file AbstractMotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressed;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake().
IsButtonPressed() [2/5]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonPressed (VirtualTriggerButton button) inline
Implements Juniper.Unity.Input.Pointers.Motion.IMotionController.
Definition at line 168 of file AbstractMotionController.cs.
         {
             return VirtualTriggerButtonThreshold(button, Trigger);
         }
IsButtonPressed() [3/5]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonPressed (PointerEventData.InputButton button) inherited
IsButtonPressed() [4/5]
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonPressed (InputButton button) inline virtual
Reimplemented from Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 296 of file AbstractMotionController.cs.
         {
             return base.IsButtonPressed(button)
                 || touchPadButtons.IsButtonPressed(button)
                 || triggerButtons.IsButtonPressed(button);
         }
IsButtonPressed() [5/5]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonUp() [1/5]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonUp (VirtualTouchPadButton button) inline
Implements Juniper.Unity.Input.Pointers.Motion.IMotionController.
Definition at line 163 of file AbstractMotionController.cs.
         {
             return VirtualButtonInBounds(button) && TouchPadPressedUp;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake().
IsButtonUp() [2/5]
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonUp (VirtualTriggerButton button) inline
Implements Juniper.Unity.Input.Pointers.Motion.IMotionController.
Definition at line 179 of file AbstractMotionController.cs.
         {
             return !VirtualTriggerButtonThreshold(button, Trigger)
                 && VirtualTriggerButtonThreshold(button, lastTrigger);
         }
IsButtonUp() [3/5]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonUp (PointerEventData.InputButton button) inherited
IsButtonUp() [4/5]
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsButtonUp (InputButton button) inline virtual
Reimplemented from Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 303 of file AbstractMotionController.cs.
         {
             return base.IsButtonUp(button)
                 || touchPadButtons.IsButtonUp(button)
                 || triggerButtons.IsButtonUp(button);
         }
IsButtonUp() [5/5]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
PlayInteraction()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction (Interaction action) inline virtual inherited
Definition at line 535 of file AbstractPointerDevice.cs.
         {
             if (Time.time > finishTime || action != lastAction)
             {
                 lastAction = action;
                 finishTime = Time.time + InteractionAudio.Play(action, probe.Cursor, Haptics);
             }
         }
References Juniper.Unity.Input.Pointers.Probe.Cursor, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.finishTime, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.lastAction, Juniper.Unity.Audio.InteractionAudio.Play(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.TestEnterExit().
Process()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process (PointerEventData evtData, float pixelDragThresholdSquared) inline virtual inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 549 of file AbstractPointerDevice.cs.
         {
             if (!IsDragging)
             {
                 TestEnterExit(evtData);
             }
             EventTarget = ProcessButtons(evtData, pixelDragThresholdSquared);
             if (evtData.clickCount == -1)
             {
                 evtData.clickCount = 0;
             }
             LastWorldPoint = evtData.pointerCurrentRaycast.worldPosition;
             LastSmoothedWorldPoint = SmoothedWorldPoint;
             LastOrigin = Origin;
             probe?.SetCursor(
                 evtData.pointerCurrentRaycast.gameObject != null,
                 AnyButtonPressed,
                 LastWorldPoint,
                 evtData.pointerCurrentRaycast.worldNormal);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.AnyButtonPressed, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventTarget, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastOrigin, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastSmoothedWorldPoint, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastWorldPoint, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Origin, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons(), Juniper.Unity.Input.Pointers.Probe.SetCursor(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SmoothedWorldPoint, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.TestEnterExit().
ProcessButtons()
override IEventSystemHandler Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared) inline protected virtual
Reimplemented from Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 287 of file AbstractMotionController.cs.
         {
             var a = base.ProcessButtons(evtData, pixelDragThresholdSquared);
             var b = touchPadButtons.Process(evtData, pixelDragThresholdSquared);
             var c = triggerButtons.Process(evtData, pixelDragThresholdSquared);
             return a ?? b ?? c;
         }
Reinstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reinstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 214 of file AbstractPointerDevice.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install().
Round2Square()
static Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Round2Square (Vector2 point) inline static protected
Definition at line 226 of file AbstractMotionController.cs.
         {
             var pLen = point.magnitude;
             if (pLen > 0)
             {
                 var onUnitCircle = point / pLen;
                 float mx = Mathf.Abs(onUnitCircle.x),
                     my = Mathf.Abs(onUnitCircle.y);
                 var onUnitSquare = onUnitCircle;
                 if (mx > my)
                 {
                     onUnitSquare /= mx;
                 }
                 else if (my > 0)
                 {
                     onUnitSquare /= my;
                 }
                 point *= onUnitSquare.magnitude;
             }
             return point;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Square2Round().
ScreenFromViewport()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 437 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ViewportToScreenPoint(viewportPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
ScreenFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 432 of file AbstractPointerDevice.cs.
         {
             return EventCamera.WorldToScreenPoint(worldPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
SetProbe()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SetProbe (Probe p) inline virtual inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 253 of file AbstractPointerDevice.cs.
         {
             if (probe != p)
             {
                 if (probe != null)
                 {
                     probe.gameObject.Destroy();
                 }
                 probe = p ?? FindProbe();
             }
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.FindProbe(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe.
Square2Round()
static Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Square2Round (Vector2 point) inline static protected
Definition at line 250 of file AbstractMotionController.cs.
         {
             var pLen = point.magnitude;
             if (pLen > 0)
             {
                 var onUnitCircle = point / pLen;
                 var onUnitSquare = Round2Square(onUnitCircle);
                 point /= onUnitSquare.magnitude;
             }
             return point;
         }
Start()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Start () inline inherited
Definition at line 195 of file AbstractPointerDevice.cs.
         {
             eventManager.AddPointer(this);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.eventManager.
Uninstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Uninstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 209 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Uninstall(gameObject);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig.
Update()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update () inline virtual inherited
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Definition at line 473 of file AbstractPointerDevice.cs.
         {
             if (motionFilter != lastMotionFilter)
             {
 #if UNITY_EDITOR
                 parent = motionFilter;
 #endif
                 motionFilter = Instantiate(motionFilter);
                 lastMotionFilter = motionFilter;
             }
 #if UNITY_EDITOR
             motionFilter?.Copy(parent);
 #endif
             Connected = IsConnected;
             if (probe != null)
             {
                 probe.SetActive(IsEnabled && showProbe);
                 probe.LaserPointerMaterial = LaserPointerMaterial;
             }
             if (IsEnabled)
             {
                 motionFilter?.UpdateState(WorldPoint);
                 InternalUpdate();
                 probe?.AlignProbe(Direction, transform.up, MaximumPointerDistance);
             }
         }
References Juniper.Unity.Input.Pointers.Probe.AlignProbe(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Connected, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsConnected, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsEnabled, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LaserPointerMaterial, Juniper.Unity.Input.Pointers.Probe.LaserPointerMaterial, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.lastMotionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MaximumPointerDistance, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.motionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.showProbe, Juniper.Unity.Statistics.AbstractMotionFilter.UpdateState(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldPoint.
ViewportFromScreen()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 447 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ScreenToViewportPoint(screenPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
ViewportFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 442 of file AbstractPointerDevice.cs.
         {
             return EventCamera.WorldToViewportPoint(worldPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
VirtualButtonInBounds()
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.VirtualButtonInBounds (VirtualTouchPadButton button) inline private
Definition at line 317 of file AbstractMotionController.cs.
         {
             return button == VirtualTouchPadButton.Any
                 || (BUTTON_CENTERS.ContainsKey(button)
                     && (SquareTouchPoint - BUTTON_CENTERS[button]).magnitude <= BUTTON_RADIUS);
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonDown(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonPressed(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonUp().
VirtualTriggerButtonThreshold()
bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.VirtualTriggerButtonThreshold (VirtualTriggerButton button, float triggerValue) inline private
Definition at line 324 of file AbstractMotionController.cs.
         {
             return TRIGGER_THRESHOLDS.ContainsKey(button)
                 && triggerValue > TRIGGER_THRESHOLDS[button];
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonDown(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonPressed(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonUp().
WorldFromScreen()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 452 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ScreenToWorldPoint((Vector3)screenPoint + pointerOffset);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset.
WorldFromViewport()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 457 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ViewportToWorldPoint((Vector3)viewportPoint + pointerOffset);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset.
Member Data Documentation
_hand
Hands Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >._hand inherited
Definition at line 44 of file AbstractHandedPointer.cs.
BUTTON_CENTERS
readonly Dictionary<VirtualTouchPadButton, Vector2> Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.BUTTON_CENTERS static private
Initial value:
= new Dictionary<VirtualTouchPadButton, Vector2>
        {
            { VirtualTouchPadButton.Center, new Vector2(0, 0) },
            { VirtualTouchPadButton.Top, new Vector2(0, DIM) },
            { VirtualTouchPadButton.Right, new Vector2(DIM, 0) },
            { VirtualTouchPadButton.Bottom, new Vector2(0, -DIM) },
            { VirtualTouchPadButton.Left, new Vector2(-DIM, 0) },
            { VirtualTouchPadButton.TopLeft, new Vector2(DIM, -DIM) },
            { VirtualTouchPadButton.TopRight, new Vector2(DIM, DIM) },
            { VirtualTouchPadButton.BottomLeft, new Vector2(-DIM, -DIM) },
            { VirtualTouchPadButton.BottomRight, new Vector2(DIM, -DIM) },
        }
Definition at line 61 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.VirtualButtonInBounds().
BUTTON_RADIUS
const float Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.BUTTON_RADIUS = 0.25f private
Definition at line 58 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.VirtualButtonInBounds().
Connected
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Connected inherited
Definition at line 69 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
DIM
const float Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.DIM = 0.75f private
Definition at line 59 of file AbstractMotionController.cs.
eventManager
AbstractUnifiedInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.eventManager protected inherited
Definition at line 504 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Start().
LaserPointerMaterial
Material Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LaserPointerMaterial inherited
Definition at line 92 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
lastTouchPosition
Vector2? Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.lastTouchPosition private
Definition at line 151 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate().
lastTrigger
float Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.lastTrigger private
Definition at line 139 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonDown(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonUp().
motionFilter
AbstractMotionFilter Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.motionFilter inherited
Definition at line 467 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
nativeButtons
readonly ButtonMapper<ButtonIDType> Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons = new ButtonMapper<ButtonIDType>() protected inherited
Definition at line 66 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons().
PointerConfig
readonly ConfigType Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig static protected inherited
Initial value:
=
            new ConfigType()
Definition at line 55 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Uninstall().
pointerOffset
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset protected inherited
Definition at line 82 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport().
probe
Probe Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe protected inherited
The cursor probe that shows the physical location of the current selection.
Definition at line 239 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SetProbe(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
showProbe
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.showProbe = true inherited
Definition at line 228 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
stage
StageExtensions Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.stage protected inherited
Definition at line 514 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
touchPadButtons
readonly ButtonMapper<VirtualTouchPadButton> Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.touchPadButtons = new ButtonMapper<VirtualTouchPadButton>() protected
Definition at line 83 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Clone(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonDown(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonPressed(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonUp(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.ProcessButtons().
TRIGGER_THRESHOLDS
readonly Dictionary<VirtualTriggerButton, float> Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TRIGGER_THRESHOLDS static private
Initial value:
= new Dictionary<VirtualTriggerButton, float>
        {
            { VirtualTriggerButton.Off, 0.1f },
            { VirtualTriggerButton.On, 0.2f },
            { VirtualTriggerButton.Full, 0.8f }
        }
Definition at line 76 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.VirtualTriggerButtonThreshold().
triggerButtons
readonly ButtonMapper<VirtualTriggerButton> Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.triggerButtons = new ButtonMapper<VirtualTriggerButton>() protected
Definition at line 84 of file AbstractMotionController.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Clone(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonDown(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonPressed(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonUp(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.ProcessButtons().
VIEWPORT_MIDPOINT
readonly Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.VIEWPORT_MIDPOINT static protected inherited
Initial value:
=
            0.5f * Vector2.one
Definition at line 52 of file AbstractPointerDevice.cs.
Property Documentation
AnyButtonPressed
override bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.AnyButtonPressed get
Definition at line 186 of file AbstractMotionController.cs.
         {
             get
             {
                 return base.AnyButtonPressed
                     || IsButtonPressed(VirtualTouchPadButton.Any)
                     || IsButtonPressed(VirtualTriggerButton.On)
                     || IsButtonPressed(VirtualTriggerButton.Full);
             }
         }
ButtonType
Type Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ButtonType get inherited
Definition at line 59 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return typeof(ButtonIDType);
             }
         }
Direction
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Direction get inherited
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
The interaction direction.
Definition at line 360 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (SmoothedWorldPoint - Origin).normalized;
             }
         }
EventCamera
Camera? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera get inherited
The camera the pointer uses to point at Canvas objects.
Definition at line 141 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.EventCamera;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromViewport(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromWorld(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromScreen(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromWorld(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport().
EventTarget
IEventSystemHandler Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventTarget get set inherited
Definition at line 100 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
Hand
virtual Hands Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.Hand get set inherited
Definition at line 47 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return _hand;
             }
             set
             {
                 _hand = value;
                 NativeHandID = PointerConfig[value];
             }
         }
Haptics
HapticsType Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics get protected set inherited
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 528 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction().
InputModule
AbstractUnifiedInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InputModule get inherited
Definition at line 507 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return eventManager;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Clone(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone().
isActiveAndEnabled
bool Juniper.Unity.Input.Pointers.IPointerDevice.isActiveAndEnabled get inherited
Definition at line 41 of file IPointerDevice.cs.
         {
             get;
         }
IsConnected
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsConnected get inherited
Definition at line 105 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
IsDisabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDisabled get inherited
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 122 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return !IsEnabled;
             }
         }
IsDominantHand
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsDominantHand get inherited
Definition at line 81 of file AbstractHandedPointer.cs.
         {
             get;
         }
IsDragging
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging get private set inherited
Definition at line 517 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.DraggableChanged(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
IsEnabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsEnabled get inherited
Definition at line 110 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return isActiveAndEnabled && IsConnected;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
IsLeftHand
bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsLeftHand get inherited
Definition at line 65 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return Hand == Hands.Left;
             }
         }
IsNonDominantHand
bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsNonDominantHand get inherited
Definition at line 86 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return !IsDominantHand;
             }
         }
IsRightHand
bool Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.IsRightHand get inherited
Definition at line 73 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return Hand == Hands.Right;
             }
         }
LastDirection
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastDirection get inherited
Definition at line 368 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (LastSmoothedWorldPoint - LastOrigin).normalized;
             }
         }
LastOrigin
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastOrigin get private set inherited
Definition at line 298 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
LastScreenPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastScreenPoint get inherited
Definition at line 384 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(LastSmoothedWorldPoint);
             }
         }
LastSmoothedWorldPoint
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastSmoothedWorldPoint get private set inherited
Definition at line 342 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
LastViewportPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastViewportPoint get inherited
Definition at line 408 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(LastSmoothedWorldPoint);
             }
         }
LastWorldPoint
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastWorldPoint get private set inherited
Definition at line 317 of file AbstractPointerDevice.cs.
         {
             get; private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
LockedOnTarget
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LockedOnTarget get set inherited
Definition at line 95 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
MaximumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MaximumPointerDistance get inherited
Definition at line 85 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Min(10f, 0.9f * DisplayManager.MainCamera.farClipPlane);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
MinimumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MinimumPointerDistance get inherited
The minimum distance from the camera at which to place the pointer.
Definition at line 75 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Max(1.5f, 1.1f * DisplayManager.MainCamera.nearClipPlane);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
name [1/2]
string Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.name get inherited
Definition at line 7 of file IPointerButtons.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
name [2/2]
string Juniper.Unity.Input.Pointers.IPointerDevice.name get inherited
Definition at line 26 of file IPointerDevice.cs.
         {
             get;
         }
NativeHandID
HandIDType? Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.NativeHandID get protected set inherited
Definition at line 60 of file AbstractHandedPointer.cs.
         {
             get; protected set;
         }
Origin
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Origin get inherited
Definition at line 290 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return transform.position;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
OriginDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.OriginDelta get inherited
Definition at line 304 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Origin - LastOrigin;
             }
         }
PointerID
int Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerID get set inherited
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
The pointer identifier.
Definition at line 153 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
ProbeName
string Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProbeName get private set inherited
Definition at line 267 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return _probeName;
             }
             private set
             {
                 if (value != ProbeName)
                 {
                     if (probe != null)
                     {
                         probe.gameObject.Destroy();
                         probe = null;
                     }
                     _probeName = value;
                     SetProbe(FindProbe());
                 }
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.FindProbe().
Raycaster
PhysicsRaycaster? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Raycaster get inherited
Definition at line 130 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.Raycaster;
             }
         }
RoundTouchPoint
abstract Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.RoundTouchPoint get
Definition at line 147 of file AbstractMotionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate().
ScreenDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenDelta get inherited
Definition at line 392 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenPoint - LastScreenPoint;
             }
         }
ScreenPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenPoint get inherited
Definition at line 376 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(SmoothedWorldPoint);
             }
         }
ScrollDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScrollDelta get protected set inherited
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 428 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate().
SmoothedWorldPoint
Vector3??? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SmoothedWorldPoint get inherited
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 334 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return motionFilter?.PredictedPosition ?? WorldPoint;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
SmoothedWorldPointDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SmoothedWorldPointDelta get inherited
Definition at line 348 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return SmoothedWorldPoint - LastSmoothedWorldPoint;
             }
         }
SquareTouchPoint
abstract Vector2 Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.SquareTouchPoint get
Definition at line 142 of file AbstractMotionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.VirtualButtonInBounds().
TouchPadPressed
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadPressed get protected
Definition at line 212 of file AbstractMotionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonPressed().
TouchPadPressedDown
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadPressedDown get protected
Definition at line 217 of file AbstractMotionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonDown().
TouchPadPressedUp
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadPressedUp get protected
Definition at line 222 of file AbstractMotionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonUp().
TouchPadTouched
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadTouched get protected
Definition at line 197 of file AbstractMotionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate().
TouchPadTouchedDown
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadTouchedDown get protected
Definition at line 202 of file AbstractMotionController.cs.
         {
             get;
         }
TouchPadTouchedUp
abstract bool Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.TouchPadTouchedUp get protected
Definition at line 207 of file AbstractMotionController.cs.
         {
             get;
         }
Trigger
abstract float Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.Trigger get
Definition at line 135 of file AbstractMotionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonDown(), Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonPressed(), and Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.IsButtonUp().
ViewportDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportDelta get inherited
Definition at line 416 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportPoint - LastViewportPoint;
             }
         }
ViewportPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportPoint get inherited
Definition at line 400 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(SmoothedWorldPoint);
             }
         }
WorldDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldDelta get inherited
Definition at line 322 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return WorldPoint - LastWorldPoint;
             }
         }
WorldPoint
override Vector3 Juniper.Unity.Input.Pointers.Motion.AbstractHandedPointer< HandIDType, ButtonIDType, ConfigType, HapticsType >.WorldPoint get inherited
Definition at line 94 of file AbstractHandedPointer.cs.
         {
             get
             {
                 return transform.position + (MinimumPointerDistance * transform.forward);
             }
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Pointers/Motion/AbstractMotionController.cs