Juniper: System.IO.FileExt Class Reference
System.IO.FileExt Class Reference
Static Public Member Functions
static bool TryDelete (string path)
Attempts to delete a file, swallowing any errors along the way.
static bool TryDelete (this FileInfo file)
static void Copy (string src, string dest, bool overwrite)
Creates a copy of a file, making sure the destination directory exists.
static void WriteAllText (string path, string text)
Writes the given text to a file, ensuring the parent directory for the file actually exists.
Detailed Description
Definition at line 3 of file FileExt.cs.
Member Function Documentation
Copy()
static void System.IO.FileExt.Copy (string src, string dest, bool overwrite) inline static
Creates a copy of a file, making sure the destination directory exists.
Parameters
src The filepath to copy.
dest The filepath to make for the new file.
overwrite Set to true to overwrite any files that may already exist in the destination directory. If false, and the destination file already exists, an error is thrown.
Definition at line 60 of file FileExt.cs.
         {
             var destDir = Path.GetDirectoryName(dest);
             DirectoryExt.CreateDirectory(destDir);
             File.Copy(src, dest, overwrite);
         }
References System.IO.DirectoryExt.CreateDirectory().
Referenced by Juniper.ConfigurationManagement.JuniperPackage.Activate().
TryDelete() [1/2]
static bool System.IO.FileExt.TryDelete (string path) inline static
Attempts to delete a file, swallowing any errors along the way.
Parameters
path The file to delete.
Returns
True, if the file was deleted. False, if the file doesn't exist or it couldn't be deleted (e.g. a process has a file-lock on it).
Definition at line 14 of file FileExt.cs.
         {
             if (!string.IsNullOrEmpty(path)
                 && File.Exists(path))
             {
                 try
                 {
                     File.Delete(path);
                     return true;
                 }
 #pragma warning disable CA1031 // Do not catch general exception types
                 catch
                 {
                 }
 #pragma warning restore CA1031 // Do not catch general exception types
             }
             return false;
         }
TryDelete() [2/2]
static bool System.IO.FileExt.TryDelete (this FileInfo file) inline static
Definition at line 34 of file FileExt.cs.
         {
             if (file?.Exists == true)
             {
                 try
                 {
                     file.Delete();
                     return true;
                 }
 #pragma warning disable CA1031 // Do not catch general exception types
                 catch
                 { }
 #pragma warning restore CA1031 // Do not catch general exception types
             }
             return false;
         }
WriteAllText()
static void System.IO.FileExt.WriteAllText (string path, string text) inline static
Writes the given text to a file, ensuring the parent directory for the file actually exists.
Parameters
path The filepath to write.
text The content to write to the file.
Definition at line 73 of file FileExt.cs.
         {
             var dir = Path.GetDirectoryName(path);
             DirectoryExt.CreateDirectory(dir);
             File.WriteAllText(path, text);
         }
References System.IO.DirectoryExt.CreateDirectory().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/NETFX/IO/FileExt.cs