Juniper: Juniper.Audio.Decoder Class Reference
Juniper.Audio.Decoder Class Reference
Decoders for a few types of audio files.
Static Public Member Functions
static RawAudio DecodeMP3 (Stream audioStream)
Decodes MP3 files into a raw stream of PCM bytes.
static RawAudio DecodeWAV (Stream audioStream)
Decodes WAV files into a raw stream of PCM bytes.
static RawAudio DecodeVorbis (Stream audioStream)
Decodes OGG files into a raw stream of PCM bytes.
static void FillBuffer (Stream stream, float[] data)
Reads a stream and fills a PCM buffer with data.
Static Private Member Functions
static RawAudio Decode (WaveStream reader)
Run the decoder and return the audio data with information.
Detailed Description
Decoders for a few types of audio files.
Definition at line 14 of file Decoder.cs.
Member Function Documentation
Decode()
static RawAudio Juniper.Audio.Decoder.Decode (WaveStream reader) inline static private
Run the decoder and return the audio data with information.
Parameters
reader
Definition at line 20 of file Decoder.cs.
         {
             var format = reader.WaveFormat;
             var bytesPerSample = format.Channels * format.BitsPerSample / 8;
             return new RawAudio
             {
                 stream = reader,
                 samples = reader.Length / bytesPerSample,
                 channels = format.Channels,
                 frequency = format.SampleRate
             };
         }
Referenced by Juniper.Audio.Decoder.DecodeMP3(), Juniper.Audio.Decoder.DecodeVorbis(), and Juniper.Audio.Decoder.DecodeWAV().
DecodeMP3()
static RawAudio Juniper.Audio.Decoder.DecodeMP3 (Stream audioStream) inline static
Decodes MP3 files into a raw stream of PCM bytes.
Parameters
audioStream
Returns
Definition at line 38 of file Decoder.cs.
         {
             return Decode(new Mp3FileReader(audioStream, wf => new Mp3FrameDecompressor(wf)));
         }
References Juniper.Audio.Decoder.Decode().
Referenced by Juniper.Unity.Audio.StreamableAudioClip.Load().
DecodeVorbis()
static RawAudio Juniper.Audio.Decoder.DecodeVorbis (Stream audioStream) inline static
Decodes OGG files into a raw stream of PCM bytes.
Parameters
audioStream
Returns
Definition at line 58 of file Decoder.cs.
         {
             return Decode(new VorbisWaveReader(audioStream));
         }
References Juniper.Audio.Decoder.Decode().
Referenced by Juniper.Unity.Audio.StreamableAudioClip.Load().
DecodeWAV()
static RawAudio Juniper.Audio.Decoder.DecodeWAV (Stream audioStream) inline static
Decodes WAV files into a raw stream of PCM bytes.
Parameters
audioStream
Returns
Definition at line 48 of file Decoder.cs.
         {
             return Decode(new WaveFileReader(audioStream));
         }
References Juniper.Audio.Decoder.Decode().
Referenced by Juniper.Unity.Audio.StreamableAudioClip.Load().
FillBuffer()
static void Juniper.Audio.Decoder.FillBuffer (Stream stream, float [] data) inline static
Reads a stream and fills a PCM buffer with data.
Parameters
stream
data
Definition at line 68 of file Decoder.cs.
         {
             var buf = new byte[sizeof(float) / sizeof(byte)];
             for (var i = 0; i < data.Length; ++i)
             {
                 stream.Read(buf, 0, buf.Length);
                 data[i] = BitConverter.ToSingle(buf, 0);
             }
         }
Referenced by Juniper.Unity.Audio.StreamableAudioClip.Load().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Audio/Decoder.cs