Juniper: Juniper.Compression.Tar.GZip.Decompressor Class Reference
Juniper.Compression.Tar.GZip.Decompressor Class Reference
Functions for dealing with TarGz files.
Static Public Member Functions
static IEnumerable< string > FindUnityPackages (params string[] searchPaths)
Find all of the UnityPackage files in all subdirectories of the given root search directories.
static IEnumerable< CompressedFileInfo > UnityPackageEntries (string packageFileName)
Read the names of all the files contained in a .unitypackage file.
static IEnumerable< CompressedFileInfo > UnityPackageEntries (FileInfo packageFile)
static TarArchive Open (FileInfo file)
static TarArchive Open (string fileName)
static IEnumerable< CompressedFileInfo > Entries (this TarArchive tar, IProgress prog=null)
Enumerates all of the entires in a single Zip archive so that it can be used more easily with c#'s for-each.
static IEnumerable< CompressedFileInfo > Entries (Stream stream, IProgress prog=null)
static IEnumerable< CompressedFileInfo > Entries (FileInfo file, IProgress prog=null)
static IEnumerable< CompressedFileInfo > Entries (string fileName, IProgress prog=null)
Detailed Description
Functions for dealing with TarGz files.
Definition at line 14 of file Decompressor.cs.
Member Function Documentation
Entries() [1/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Tar.GZip.Decompressor.Entries (this TarArchive tar, IProgress prog = null) inline static
Enumerates all of the entires in a single Zip archive so that it can be used more easily with c#'s for-each.
Parameters
tar A zipfile stream
prog A prog tracking object, defaults to null (i.e. no prog tracking).
Returns
A lazy collection of ZipArchiveEntry objects.
Definition at line 134 of file Decompressor.cs.
         {
             if (tar is null)
             {
                 throw new ArgumentNullException(nameof(tar));
             }
             var i = 0;
             foreach (var entry in tar.Entries)
             {
                 prog.Report(i++, tar.Entries.Count);
                 yield return new CompressedFileInfo(entry);
             }
             prog.Report(i, tar.Entries.Count);
         }
Referenced by Juniper.Compression.Tar.GZip.Decompressor.Entries().
Entries() [2/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Tar.GZip.Decompressor.Entries (Stream stream, IProgress prog = null) inline static
Definition at line 151 of file Decompressor.cs.
         {
             if (stream is GZipStream gzStream)
             {
                 using var tar = new TarArchive(gzStream);
                 return tar.Entries(prog);
             }
             else
             {
                 using var gzStream2 = new GZipStream(stream, CompressionMode.Decompress);
                 using var tar = new TarArchive(gzStream2);
                 return tar.Entries(prog);
             }
         }
Entries() [3/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Tar.GZip.Decompressor.Entries (FileInfo file, IProgress prog = null) inline static
Definition at line 166 of file Decompressor.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             using var stream = file.OpenRead();
             foreach (var entry in Entries(stream, prog))
             {
                 yield return entry;
             }
         }
References Juniper.Compression.Tar.GZip.Decompressor.Entries().
Entries() [4/4]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Tar.GZip.Decompressor.Entries (string fileName, IProgress prog = null) inline static
Definition at line 180 of file Decompressor.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return Entries(new FileInfo(fileName), prog);
         }
References Juniper.Compression.Tar.GZip.Decompressor.Entries().
FindUnityPackages()
static IEnumerable<string> Juniper.Compression.Tar.GZip.Decompressor.FindUnityPackages (params string [] searchPaths) inline static
Find all of the UnityPackage files in all subdirectories of the given root search directories.
Parameters
searchPaths
Returns
Definition at line 22 of file Decompressor.cs.
         {
             return from path in searchPaths
                    where Directory.Exists(path)
                    from file in Directory.GetFiles(path, "*.unitypackage", SearchOption.AllDirectories)
                    select file;
         }
Open() [1/2]
static TarArchive Juniper.Compression.Tar.GZip.Decompressor.Open (FileInfo file) inline static
Definition at line 96 of file Decompressor.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             if (!file.Exists)
             {
                 throw new FileNotFoundException("File not found!", file.FullName);
             }
             using var stream = new GZipStream(file.OpenRead(), CompressionMode.Decompress);
             return new TarArchive(stream);
         }
Referenced by Juniper.Compression.Tar.GZip.Decompressor.Open(), and Juniper.Compression.Tar.GZip.Decompressor.UnityPackageEntries().
Open() [2/2]
static TarArchive Juniper.Compression.Tar.GZip.Decompressor.Open (string fileName) inline static
Definition at line 112 of file Decompressor.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (fileName.Length == 0)
             {
                 throw new ArgumentException("path must not be empty string", nameof(fileName));
             }
             return Open(new FileInfo(fileName));
         }
References Juniper.Compression.Tar.GZip.Decompressor.Open().
UnityPackageEntries() [1/2]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Tar.GZip.Decompressor.UnityPackageEntries (string packageFileName) inline static
Read the names of all the files contained in a .unitypackage file.
Parameters
packageFileName The .unitypackage file to read
Returns
A lazy collection of filenames.
Definition at line 35 of file Decompressor.cs.
         {
             if (packageFileName is null)
             {
                 throw new ArgumentNullException(nameof(packageFileName));
             }
             if (packageFileName.Length == 0)
             {
                 throw new ArgumentException("Value must not be an empty string.", nameof(packageFileName));
             }
             return UnityPackageEntries(new FileInfo(packageFileName));
         }
Referenced by Juniper.ConfigurationManagement.AssetStorePackage.GetContentFiles().
UnityPackageEntries() [2/2]
static IEnumerable<CompressedFileInfo> Juniper.Compression.Tar.GZip.Decompressor.UnityPackageEntries (FileInfo packageFile) inline static
Definition at line 50 of file Decompressor.cs.
         {
             if (packageFile is null)
             {
                 throw new ArgumentNullException(nameof(packageFile));
             }
             if (!packageFile.Exists)
             {
                 throw new FileNotFoundException("File not found! " + packageFile.FullName, packageFile.FullName);
             }
             using var tar = Open(packageFile);
             var paths = new Dictionary<string, string>();
             var sizes = new Dictionary<string, long>();
             foreach (var entry in tar.Entries)
             {
                 var parts = entry.FullName.Split('/');
                 if (parts.Length == 2)
                 {
                     var guid = parts[0];
                     var item = parts[1];
                     if (item.Equals("asset", StringComparison.InvariantCulture))
                     {
                         sizes[guid] = item.Length;
                     }
                     else if (item.Equals("pathname", StringComparison.InvariantCulture))
                     {
                         using var stream = entry.Open();
                         using var streamReader = new StreamReader(stream);
                         paths[guid] = streamReader.ReadLine();
                     }
                     if (paths.ContainsKey(guid)
                         && sizes.ContainsKey(guid))
                     {
                         var path = paths[guid];
                         var size = sizes[guid];
                         paths.Remove(guid);
                         sizes.Remove(guid);
                         yield return new CompressedFileInfo(path, true, size);
                     }
                 }
             }
         }
References Juniper.Compression.Tar.GZip.Decompressor.Open().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Compression/Tar.GZip/Decompressor.cs