Juniper: Juniper.Input.AbstractPollingKeyEventSource< KeyT > Class Template Reference
Juniper.Input.AbstractPollingKeyEventSource< KeyT > Class Template Reference abstract
Public Member Functions
AbstractPollingKeyEventSource ()
override void Start ()
override void Stop ()
void AddKeyAlias (string name, params KeyT[] keys)
bool IsDown (string name)
Protected Member Functions
abstract bool IsKeyDown (KeyT key)
void UpdateStates ()
Properties
Dictionary< KeyT, bool > KeyState = new Dictionary<KeyT, bool>() [get]
IReadOnlyCollection< KeyT > Keys [get, private set]
Events
EventHandler< KeyChangeEvent > KeyChanged
EventHandler< KeyEvent > KeyDown
EventHandler< KeyEvent > KeyUp
Private Member Functions
void Update ()
Private Attributes
readonly Thread poller
Detailed Description
Definition at line 5 of file AbstractPollingKeyEventSource.cs.
Constructor & Destructor Documentation
AbstractPollingKeyEventSource()
Juniper.Input.AbstractPollingKeyEventSource< KeyT >.AbstractPollingKeyEventSource () inline
Definition at line 10 of file AbstractPollingKeyEventSource.cs.
         {
             var threadStart = new ThreadStart(Update);
             poller = new Thread(threadStart);
         }
Member Function Documentation
AddKeyAlias()
void Juniper.Input.AbstractKeyEventSource< KeyT >.AddKeyAlias (string name, params KeyT [] keys) inline inherited
Definition at line 77 of file AbstractKeyEventSource.cs.
         {
             lock (KeyState)
             {
                 foreach (var key in keys)
                 {
                     KeyState[key] = false;
                 }
                 aliases[name] = keys;
                 aliasState[name] = false;
                 events[name] = new KeyEvent(name);
                 upEvents[name] = new KeyChangeEvent(name, false);
                 downEvents[name] = new KeyChangeEvent(name, true);
             }
         }
IsDown()
bool Juniper.Input.AbstractKeyEventSource< KeyT >.IsDown (string name) inline inherited
Definition at line 94 of file AbstractKeyEventSource.cs.
         {
             return aliasState[name];
         }
IsKeyDown()
abstract bool Juniper.Input.AbstractPollingKeyEventSource< KeyT >.IsKeyDown (KeyT key) protected pure virtual
Referenced by Juniper.Input.AbstractPollingKeyEventSource< Key >.Update().
Start()
override void Juniper.Input.AbstractPollingKeyEventSource< KeyT >.Start () inline virtual
Reimplemented from Juniper.Input.AbstractKeyEventSource< KeyT >.
Definition at line 16 of file AbstractPollingKeyEventSource.cs.
         {
             base.Start();
             poller.Start();
         }
Stop()
override void Juniper.Input.AbstractPollingKeyEventSource< KeyT >.Stop () inline virtual
Reimplemented from Juniper.Input.AbstractKeyEventSource< KeyT >.
Definition at line 22 of file AbstractPollingKeyEventSource.cs.
         {
             base.Stop();
             poller.Join();
         }
Update()
void Juniper.Input.AbstractPollingKeyEventSource< KeyT >.Update () inline private
Definition at line 28 of file AbstractPollingKeyEventSource.cs.
         {
             while (poller.ThreadState == ThreadState.Running)
             {
                 lock (KeyState)
                 {
                     foreach (var key in Keys)
                     {
                         KeyState[key] = IsKeyDown(key);
                     }
                     UpdateStates();
                 }
             }
         }
Referenced by Juniper.Input.AbstractPollingKeyEventSource< Key >.AbstractPollingKeyEventSource().
UpdateStates()
void Juniper.Input.AbstractKeyEventSource< KeyT >.UpdateStates () inline protected inherited
Definition at line 42 of file AbstractKeyEventSource.cs.
         {
             foreach (var name in names)
             {
                 var wasDown = aliasState[name];
                 var isDown = true;
                 foreach (var key in aliases[name])
                 {
                     isDown &= KeyState[key];
                 }
                 aliasState[name] = isDown;
                 if (isDown != wasDown)
                 {
                     if (isDown)
                     {
                         origin.DoCallBack(() =>
{
                             KeyDown?.Invoke(this, events[name]);
                             KeyChanged?.Invoke(this, downEvents[name]);
                         });
                     }
                     else
                     {
                         origin.DoCallBack(() =>
{
                             KeyUp?.Invoke(this, events[name]);
                             KeyChanged?.Invoke(this, upEvents[name]);
                         });
                     }
                 }
             }
         }
Referenced by Juniper.Input.AbstractPollingKeyEventSource< Key >.Update().
Member Data Documentation
poller
readonly Thread Juniper.Input.AbstractPollingKeyEventSource< KeyT >.poller private
Definition at line 8 of file AbstractPollingKeyEventSource.cs.
Referenced by Juniper.Input.AbstractPollingKeyEventSource< Key >.AbstractPollingKeyEventSource(), Juniper.Input.AbstractPollingKeyEventSource< Key >.Start(), Juniper.Input.AbstractPollingKeyEventSource< Key >.Stop(), and Juniper.Input.AbstractPollingKeyEventSource< Key >.Update().
Property Documentation
Keys
IReadOnlyCollection<KeyT> Juniper.Input.AbstractKeyEventSource< KeyT >.Keys get private set protected inherited
Definition at line 23 of file AbstractKeyEventSource.cs.
 { get; private set; }
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.Start(), and Juniper.Input.AbstractPollingKeyEventSource< Key >.Update().
KeyState
Dictionary<KeyT, bool> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyState = new Dictionary<KeyT, bool>() get protected inherited
Definition at line 21 of file AbstractKeyEventSource.cs.
 { get; } = new Dictionary<KeyT, bool>();
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AddKeyAlias(), Juniper.Input.AbstractKeyEventSource< Keys >.Start(), Juniper.Input.AbstractPollingKeyEventSource< Key >.Update(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
Event Documentation
KeyChanged
EventHandler<KeyChangeEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyChanged inherited
Definition at line 11 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
KeyDown
EventHandler<KeyEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyDown inherited
Definition at line 12 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
KeyUp
EventHandler<KeyEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyUp inherited
Definition at line 13 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Input/AbstractPollingKeyEventSource.cs