Juniper: Juniper.Unity.Widgets.DetectVideoEnd Class Reference
Juniper.Unity.Widgets.DetectVideoEnd Class Reference
Detects when a video player has played past the end of a video clip, either terminally or looping.
Public Member Functions
void Awake ()
Retrieves the video player component on this game object.
void OnEnable ()
Resets the playing status to false.
void Update ()
Checks to see if the video has reached the last frame.
Public Attributes
UnityEvent onVideoEnd = new UnityEvent()
A Unity Event that is fired when the video has reached its end.
Events
EventHandler VideoEnd
A standard .NET event that is fired when the video has reached its end.
Private Member Functions
void OnVideoEnd ()
Fires the onVideoEnd and VideoEnd events.
void Player_LoopPointReached (VideoPlayer source)
Triggers OnVideoEnd when the player has looped.
Private Attributes
VideoPlayer player
The video player on which we are attempting to detect an end.
bool wasPlaying
The isPlaying status of the video from the previous frame, to be able to detect changes between frames.
Detailed Description
Detects when a video player has played past the end of a video clip, either terminally or looping.
Definition at line 16 of file DetectVideoEnd.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Widgets.DetectVideoEnd.Awake () inline
Retrieves the video player component on this game object.
Definition at line 53 of file DetectVideoEnd.cs.
         {
             player = GetComponent<VideoPlayer>();
             player.loopPointReached += Player_LoopPointReached;
         }
References Juniper.Unity.Widgets.DetectVideoEnd.player, and Juniper.Unity.Widgets.DetectVideoEnd.Player_LoopPointReached().
OnEnable()
void Juniper.Unity.Widgets.DetectVideoEnd.OnEnable () inline
Resets the playing status to false.
Definition at line 71 of file DetectVideoEnd.cs.
         {
             wasPlaying = false;
         }
References Juniper.Unity.Widgets.DetectVideoEnd.wasPlaying.
OnVideoEnd()
void Juniper.Unity.Widgets.DetectVideoEnd.OnVideoEnd () inline private
Fires the onVideoEnd and VideoEnd events.
Definition at line 44 of file DetectVideoEnd.cs.
         {
             onVideoEnd?.Invoke();
             VideoEnd?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Unity.Widgets.DetectVideoEnd.onVideoEnd, and Juniper.Unity.Widgets.DetectVideoEnd.VideoEnd.
Referenced by Juniper.Unity.Widgets.DetectVideoEnd.Player_LoopPointReached(), and Juniper.Unity.Widgets.DetectVideoEnd.Update().
Player_LoopPointReached()
void Juniper.Unity.Widgets.DetectVideoEnd.Player_LoopPointReached (VideoPlayer source) inline private
Triggers OnVideoEnd when the player has looped.
Parameters
source Source.
Definition at line 63 of file DetectVideoEnd.cs.
         {
             OnVideoEnd();
         }
References Juniper.Unity.Widgets.DetectVideoEnd.OnVideoEnd().
Referenced by Juniper.Unity.Widgets.DetectVideoEnd.Awake().
Update()
void Juniper.Unity.Widgets.DetectVideoEnd.Update () inline
Checks to see if the video has reached the last frame.
Definition at line 79 of file DetectVideoEnd.cs.
         {
             if (player.isPlaying && !player.isLooping)
             {
                 var isPlaying = player.frame < (long)player.frameCount;
                 if (!isPlaying && wasPlaying)
                 {
                     OnVideoEnd();
                 }
                 wasPlaying = isPlaying;
             }
         }
References Juniper.Unity.Widgets.DetectVideoEnd.OnVideoEnd(), Juniper.Unity.Widgets.DetectVideoEnd.player, and Juniper.Unity.Widgets.DetectVideoEnd.wasPlaying.
Member Data Documentation
onVideoEnd
UnityEvent Juniper.Unity.Widgets.DetectVideoEnd.onVideoEnd = new UnityEvent()
A Unity Event that is fired when the video has reached its end.
Definition at line 34 of file DetectVideoEnd.cs.
Referenced by Juniper.Unity.Widgets.DetectVideoEnd.OnVideoEnd().
player
VideoPlayer Juniper.Unity.Widgets.DetectVideoEnd.player private
The video player on which we are attempting to detect an end.
Definition at line 23 of file DetectVideoEnd.cs.
Referenced by Juniper.Unity.Widgets.DetectVideoEnd.Awake(), and Juniper.Unity.Widgets.DetectVideoEnd.Update().
wasPlaying
bool Juniper.Unity.Widgets.DetectVideoEnd.wasPlaying private
The isPlaying status of the video from the previous frame, to be able to detect changes between frames.
Definition at line 29 of file DetectVideoEnd.cs.
Referenced by Juniper.Unity.Widgets.DetectVideoEnd.OnEnable(), and Juniper.Unity.Widgets.DetectVideoEnd.Update().
Event Documentation
VideoEnd
EventHandler Juniper.Unity.Widgets.DetectVideoEnd.VideoEnd
A standard .NET event that is fired when the video has reached its end.
Definition at line 39 of file DetectVideoEnd.cs.
Referenced by Juniper.Unity.Widgets.DetectVideoEnd.OnVideoEnd().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Widgets/DetectVideoEnd.cs