Juniper: Juniper.Threading.ManagedRequest< T > Class Template Reference
Juniper.Threading.ManagedRequest< T > Class Template Reference
A ManagedRequest is a AbstractBackgroundRepeatingThread that keeps a parameterized type value as its work result.
Public Member Functions
ManagedRequest (float pollRate=DEFAULT_POLL_RATE, float timeout=DEFAULT_TIMEOUT)
Create an object that runs an HTTP request process in a background thread on a regular interval, firing events on error or success.
void RetryIn (float seconds)
Clear out all errors and schedule a new request.
void Stop ()
Signal to the background thread that it should stop the repeatition process and shut down.
Public Attributes
const float DEFAULT_POLL_RATE = 30
The default number of seconds between data polls
const float DEFAULT_TIMEOUT = 3
The default number of seconds to wait on an HTTP request to consider it timed out
Protected Member Functions
override void Loop ()
If we aren't waiting on a response to a previous request, wait until the request time is nigh, then issue the request. If we are waiting on a response to a previous request, then check how long it has taken, and issue the TimeOut event if it has taken too long.
override void Awake ()
Create a new background thread, initialized in a non-running, non-shutting down state.
override void OnBegin ()
Code to execute when the thread first starts.
override void Execute ()
The routine that runs on the background thread.
void OnError (Exception exp)
Trigger the Error event handler, if it has any listeners attached to it.
void Begin ()
Get the background thread up and running.
Properties
DateTime NextRequest [get, private set]
The timestamp at which the next request will be performed.
DateTime? LastRequest [get, private set]
The timestamp (if any) at which the most recent request was performed.
DateTime? LastResponse [get, private set]
The timestamp (if any) at which the most recent response was received.
Exception LastError [get, private set]
The timestamp (if any) at which the most recent error was received.
float TimeoutRate [get, set]
The current rate at which requests are considered timed out.
float PollRate [get, set]
The current rate at which requests are issued.
TimeSpan? SinceRequest [get]
The that that has passed since the last request (if any) was performed.
float? SinceRequestSeconds [get]
The number of seconds that have passed since the last request (if any) was performed.
TimeSpan UntilNextRequest [get]
The amount of time until the next request is performed.
float UntilNextRequestSeconds [get]
The number of seconds until the next request is performed.
bool Errored [get]
Returns true if there has been an error or timeout since the last request, before a response could occur.
TimeSpan? SinceResponse [get]
The amount of time since the last response (if any).
float? SinceResponseSeconds [get]
The number of seconds since the last response (if any).
bool IsTimedOut [get]
Returns true if there has been no response in a set amount of time since the last request.
TimeSpan? ResponseTime [get]
The amount of time that passed between the last request (if any) and last response (if any)
float??? ResponseTimeSeconds [get]
The number of seconds that passed between the last request (if any) and last response (if any)
override bool Running [get]
Returns true if the thread is still running and not in the middle of shutting down
Events
EventHandler< ManagedRequestReadyEventArgs< T > > Ready
Capture when the request poller is ready.
EventHandler< ManagedRequestMessageArgs< T > > Message
Capture when the request poller returns a good result.
EventHandler< BackgroundThreadErrorEventArgs > ServerError
Capture when the request poller returns an error result.
EventHandler TimedOut
Capture when the request poller times out.
EventHandler< BackgroundThreadErrorEventArgs > Error
An event that triggers if the background operation throws an exception.
Private Member Functions
void OnReady (Action< T > onSuccess, Action< Exception > onError)
Execute the Ready event, if it has listeners attached to it.
void OnMessage (T args)
Execute the Message event, if it has listeners attached to it.
void OnServerError (Exception exp)
Execute the ServerError event, if it has listeners attached to it.
void OnTimedOut ()
Execute the TimedOut event, if it has listeners attached to it.
void OnSuccess (T obj)
When the request is successful, issue the Message event. OnMessage(T)
Private Attributes
bool wasTimedOut
Whether or not the thread had timed out waiting to a response from its last request.
Detailed Description
A ManagedRequest is a AbstractBackgroundRepeatingThread that keeps a parameterized type value as its work result.
Template Parameters
T The type of the work result.
Definition at line 10 of file ManagedRequest.cs.
Constructor & Destructor Documentation
ManagedRequest()
Juniper.Threading.ManagedRequest< T >.ManagedRequest (float pollRate = DEFAULT_POLL_RATE, float timeout = DEFAULT_TIMEOUT) inline
Create an object that runs an HTTP request process in a background thread on a regular interval, firing events on error or success.
Parameters
pollRate The number of seconds between data polls. Defaults to DEFAULT_POLL_RATE.
timeout The number of seconds to wait on an HTTP request to consider it timed out. Defaults to DEFAULT_TIMEOUT.
Definition at line 31 of file ManagedRequest.cs.
         {
             PollRate = pollRate;
             TimeoutRate = timeout;
             NextRequest = DateTime.Now.AddSeconds(pollRate / 4);
         }
References Juniper.Threading.ManagedRequest< T >.NextRequest, Juniper.Threading.ManagedRequest< T >.PollRate, and Juniper.Threading.ManagedRequest< T >.TimeoutRate.
Member Function Documentation
Awake()
override void Juniper.Threading.AbstractBackgroundRepeatingThread.Awake () inline protected virtual inherited
Create a new background thread, initialized in a non-running, non-shutting down state.
Reimplemented from Juniper.Threading.AbstractBackgroundThread.
Definition at line 32 of file AbstractBackgroundRepeatingThread.cs.
         {
             base.Awake();
             stopping = false;
         }
References Juniper.Threading.AbstractBackgroundRepeatingThread.stopping.
Begin()
void Juniper.Threading.AbstractBackgroundThread.Begin () inline protected inherited
Get the background thread up and running.
Definition at line 50 of file AbstractBackgroundThread.cs.
         {
             if (!Running)
             {
                 OnBegin();
                 Task.Run(new Action(Run));
             }
         }
References Juniper.Threading.AbstractBackgroundThread.OnBegin(), Juniper.Threading.AbstractBackgroundThread.Run(), and Juniper.Threading.AbstractBackgroundThread.Running.
Execute()
override void Juniper.Threading.AbstractBackgroundRepeatingThread.Execute () inline protected virtual inherited
The routine that runs on the background thread.
Implements Juniper.Threading.AbstractBackgroundThread.
Definition at line 50 of file AbstractBackgroundRepeatingThread.cs.
         {
             while (!stopping)
             {
                 try
                 {
                     Loop();
                 }
                 catch (Exception exp)
                 {
                     OnError(exp);
                 }
             }
         }
References Juniper.Threading.AbstractBackgroundRepeatingThread.Loop(), Juniper.Threading.AbstractBackgroundThread.OnError(), and Juniper.Threading.AbstractBackgroundRepeatingThread.stopping.
Loop()
override void Juniper.Threading.ManagedRequest< T >.Loop () inline protected virtual
If we aren't waiting on a response to a previous request, wait until the request time is nigh, then issue the request. If we are waiting on a response to a previous request, then check how long it has taken, and issue the TimeOut event if it has taken too long.
Implements Juniper.Threading.AbstractBackgroundRepeatingThread.
Definition at line 293 of file ManagedRequest.cs.
         {
             if (UntilNextRequestSeconds <= 0)
             {
                 var now = DateTime.Now;
                 LastRequest = now;
                 NextRequest = now.AddSeconds(PollRate);
                 LastResponse = null;
                 OnReady(OnSuccess, OnServerError);
             }
             if (IsTimedOut && !wasTimedOut)
             {
                 OnTimedOut();
             }
             wasTimedOut = IsTimedOut;
         }
References Juniper.Threading.ManagedRequest< T >.IsTimedOut, Juniper.Threading.ManagedRequest< T >.LastRequest, Juniper.Threading.ManagedRequest< T >.LastResponse, Juniper.Threading.ManagedRequest< T >.NextRequest, Juniper.Threading.ManagedRequest< T >.OnReady(), Juniper.Threading.ManagedRequest< T >.OnServerError(), Juniper.Threading.ManagedRequest< T >.OnSuccess(), Juniper.Threading.ManagedRequest< T >.OnTimedOut(), Juniper.Threading.ManagedRequest< T >.PollRate, Juniper.Threading.ManagedRequest< T >.UntilNextRequestSeconds, and Juniper.Threading.ManagedRequest< T >.wasTimedOut.
OnBegin()
override void Juniper.Threading.AbstractBackgroundRepeatingThread.OnBegin () inline protected virtual inherited
Code to execute when the thread first starts.
Reimplemented from Juniper.Threading.AbstractBackgroundThread.
Definition at line 41 of file AbstractBackgroundRepeatingThread.cs.
         {
             base.OnBegin();
             stopping = false;
         }
References Juniper.Threading.AbstractBackgroundRepeatingThread.stopping.
OnError()
void Juniper.Threading.AbstractBackgroundThread.OnError (Exception exp) inline protected inherited
Trigger the Error event handler, if it has any listeners attached to it.
Parameters
exp
Definition at line 31 of file AbstractBackgroundThread.cs.
         {
             if (Running)
             {
                 Error?.Invoke(this, new BackgroundThreadErrorEventArgs(exp));
             }
         }
References Juniper.Threading.AbstractBackgroundThread.Error, and Juniper.Threading.AbstractBackgroundThread.Running.
Referenced by Juniper.Threading.AbstractBackgroundRepeatingThread.Execute(), and Juniper.Threading.AbstractBackgroundThread.Run().
OnMessage()
void Juniper.Threading.ManagedRequest< T >.OnMessage (T args) inline private
Execute the Message event, if it has listeners attached to it.
Parameters
args
Definition at line 72 of file ManagedRequest.cs.
         {
             if (Running)
             {
                 Message?.Invoke(this, new ManagedRequestMessageArgs<T>(args));
             }
         }
References Juniper.Threading.ManagedRequest< T >.Message, and Juniper.Threading.AbstractBackgroundRepeatingThread.Running.
Referenced by Juniper.Threading.ManagedRequest< T >.OnSuccess().
OnReady()
void Juniper.Threading.ManagedRequest< T >.OnReady (Action< T > onSuccess, Action< Exception > onError) inline private
Execute the Ready event, if it has listeners attached to it.
Parameters
onSuccess
onError
Definition at line 63 of file ManagedRequest.cs.
         {
             Ready?.Invoke(this, new ManagedRequestReadyEventArgs<T>(onSuccess, onError));
         }
References Juniper.Threading.ManagedRequest< T >.Ready.
Referenced by Juniper.Threading.ManagedRequest< T >.Loop().
OnServerError()
void Juniper.Threading.ManagedRequest< T >.OnServerError (Exception exp) inline private
Execute the ServerError event, if it has listeners attached to it.
Parameters
exp
Definition at line 84 of file ManagedRequest.cs.
         {
             if (Running)
             {
                 ServerError?.Invoke(this, new BackgroundThreadErrorEventArgs(exp));
             }
         }
References Juniper.Threading.AbstractBackgroundRepeatingThread.Running, and Juniper.Threading.ManagedRequest< T >.ServerError.
Referenced by Juniper.Threading.ManagedRequest< T >.Loop().
OnSuccess()
void Juniper.Threading.ManagedRequest< T >.OnSuccess (T obj) inline private
When the request is successful, issue the Message event. OnMessage(T)
Parameters
obj
Definition at line 320 of file ManagedRequest.cs.
         {
             LastResponse = DateTime.Now;
             OnMessage(obj);
         }
References Juniper.Threading.ManagedRequest< T >.LastResponse, and Juniper.Threading.ManagedRequest< T >.OnMessage().
Referenced by Juniper.Threading.ManagedRequest< T >.Loop().
OnTimedOut()
void Juniper.Threading.ManagedRequest< T >.OnTimedOut () inline private
Execute the TimedOut event, if it has listeners attached to it.
Definition at line 95 of file ManagedRequest.cs.
         {
             if (Running)
             {
                 TimedOut?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Threading.AbstractBackgroundRepeatingThread.Running, and Juniper.Threading.ManagedRequest< T >.TimedOut.
Referenced by Juniper.Threading.ManagedRequest< T >.Loop().
RetryIn()
void Juniper.Threading.ManagedRequest< T >.RetryIn (float seconds) inline
Clear out all errors and schedule a new request.
Parameters
seconds The number of seconds from now at which to start the next request.
Definition at line 280 of file ManagedRequest.cs.
         {
             LastRequest = null;
             NextRequest = DateTime.Now.AddSeconds(seconds);
             LastError = null;
             LastResponse = null;
         }
References Juniper.Threading.ManagedRequest< T >.LastError, Juniper.Threading.ManagedRequest< T >.LastRequest, Juniper.Threading.ManagedRequest< T >.LastResponse, and Juniper.Threading.ManagedRequest< T >.NextRequest.
Stop()
void Juniper.Threading.AbstractBackgroundRepeatingThread.Stop () inline inherited
Signal to the background thread that it should stop the repeatition process and shut down.
Definition at line 24 of file AbstractBackgroundRepeatingThread.cs.
         {
             stopping = true;
         }
References Juniper.Threading.AbstractBackgroundRepeatingThread.stopping.
Member Data Documentation
DEFAULT_POLL_RATE
const float Juniper.Threading.ManagedRequest< T >.DEFAULT_POLL_RATE = 30
The default number of seconds between data polls
Definition at line 15 of file ManagedRequest.cs.
DEFAULT_TIMEOUT
const float Juniper.Threading.ManagedRequest< T >.DEFAULT_TIMEOUT = 3
The default number of seconds to wait on an HTTP request to consider it timed out
Definition at line 20 of file ManagedRequest.cs.
wasTimedOut
bool Juniper.Threading.ManagedRequest< T >.wasTimedOut private
Whether or not the thread had timed out waiting to a response from its last request.
Definition at line 314 of file ManagedRequest.cs.
Referenced by Juniper.Threading.ManagedRequest< T >.Loop().
Property Documentation
Errored
bool Juniper.Threading.ManagedRequest< T >.Errored get
Returns true if there has been an error or timeout since the last request, before a response could occur.
Definition at line 207 of file ManagedRequest.cs.
         {
             get
             {
                 return LastError != null || IsTimedOut;
             }
         }
IsTimedOut
bool Juniper.Threading.ManagedRequest< T >.IsTimedOut get
Returns true if there has been no response in a set amount of time since the last request.
Definition at line 247 of file ManagedRequest.cs.
         {
             get
             {
                 return SinceResponse == null && SinceRequestSeconds > TimeoutRate;
             }
         }
Referenced by Juniper.Threading.ManagedRequest< T >.Loop().
LastError
Exception Juniper.Threading.ManagedRequest< T >.LastError get private set
The timestamp (if any) at which the most recent error was received.
Definition at line 131 of file ManagedRequest.cs.
         {
             get; private set;
         }
Referenced by Juniper.Threading.ManagedRequest< T >.RetryIn().
LastRequest
DateTime? Juniper.Threading.ManagedRequest< T >.LastRequest get private set
The timestamp (if any) at which the most recent request was performed.
Definition at line 115 of file ManagedRequest.cs.
         {
             get; private set;
         }
Referenced by Juniper.Threading.ManagedRequest< T >.Loop(), and Juniper.Threading.ManagedRequest< T >.RetryIn().
LastResponse
DateTime? Juniper.Threading.ManagedRequest< T >.LastResponse get private set
The timestamp (if any) at which the most recent response was received.
Definition at line 123 of file ManagedRequest.cs.
         {
             get; private set;
         }
Referenced by Juniper.Threading.ManagedRequest< T >.Loop(), Juniper.Threading.ManagedRequest< T >.OnSuccess(), and Juniper.Threading.ManagedRequest< T >.RetryIn().
NextRequest
DateTime Juniper.Threading.ManagedRequest< T >.NextRequest get private set
The timestamp at which the next request will be performed.
Definition at line 107 of file ManagedRequest.cs.
         {
             get; private set;
         }
Referenced by Juniper.Threading.ManagedRequest< T >.Loop(), Juniper.Threading.ManagedRequest< T >.ManagedRequest(), and Juniper.Threading.ManagedRequest< T >.RetryIn().
PollRate
float Juniper.Threading.ManagedRequest< T >.PollRate get set
The current rate at which requests are issued.
Definition at line 147 of file ManagedRequest.cs.
         {
             get; set;
         }
Referenced by Juniper.Threading.ManagedRequest< T >.Loop(), and Juniper.Threading.ManagedRequest< T >.ManagedRequest().
ResponseTime
TimeSpan? Juniper.Threading.ManagedRequest< T >.ResponseTime get
The amount of time that passed between the last request (if any) and last response (if any)
Definition at line 258 of file ManagedRequest.cs.
         {
             get
             {
                 return LastResponse - LastRequest;
             }
         }
ResponseTimeSeconds
float??? Juniper.Threading.ManagedRequest< T >.ResponseTimeSeconds get
The number of seconds that passed between the last request (if any) and last response (if any)
Definition at line 269 of file ManagedRequest.cs.
         {
             get
             {
                 return (float?)ResponseTime?.TotalSeconds;
             }
         }
Running
override bool Juniper.Threading.AbstractBackgroundRepeatingThread.Running get inherited
Returns true if the thread is still running and not in the middle of shutting down
Definition at line 14 of file AbstractBackgroundRepeatingThread.cs.
         {
             get
             {
                 return base.Running && !stopping;
             }
         }
Referenced by Juniper.Threading.ManagedRequest< T >.OnMessage(), Juniper.Threading.ManagedRequest< T >.OnServerError(), and Juniper.Threading.ManagedRequest< T >.OnTimedOut().
SinceRequest
TimeSpan? Juniper.Threading.ManagedRequest< T >.SinceRequest get
The that that has passed since the last request (if any) was performed.
Definition at line 155 of file ManagedRequest.cs.
         {
             get
             {
                 return DateTime.Now - LastRequest;
             }
         }
SinceRequestSeconds
float? Juniper.Threading.ManagedRequest< T >.SinceRequestSeconds get
The number of seconds that have passed since the last request (if any) was performed.
Definition at line 166 of file ManagedRequest.cs.
         {
             get
             {
                 if (SinceRequest == null)
                 {
                     return null;
                 }
                 else
                 {
                     return (float)SinceRequest.Value.TotalSeconds;
                 }
             }
         }
SinceResponse
TimeSpan? Juniper.Threading.ManagedRequest< T >.SinceResponse get
The amount of time since the last response (if any).
Definition at line 218 of file ManagedRequest.cs.
         {
             get
             {
                 return DateTime.Now - LastResponse;
             }
         }
SinceResponseSeconds
float? Juniper.Threading.ManagedRequest< T >.SinceResponseSeconds get
The number of seconds since the last response (if any).
Definition at line 229 of file ManagedRequest.cs.
         {
             get
             {
                 if (SinceResponse == null)
                 {
                     return null;
                 }
                 else
                 {
                     return (float)SinceResponse.Value.TotalSeconds;
                 }
             }
         }
TimeoutRate
float Juniper.Threading.ManagedRequest< T >.TimeoutRate get set
The current rate at which requests are considered timed out.
Definition at line 139 of file ManagedRequest.cs.
         {
             get; set;
         }
Referenced by Juniper.Threading.ManagedRequest< T >.ManagedRequest().
UntilNextRequest
TimeSpan Juniper.Threading.ManagedRequest< T >.UntilNextRequest get
The amount of time until the next request is performed.
Definition at line 184 of file ManagedRequest.cs.
         {
             get
             {
                 return NextRequest - DateTime.Now;
             }
         }
UntilNextRequestSeconds
float Juniper.Threading.ManagedRequest< T >.UntilNextRequestSeconds get
The number of seconds until the next request is performed.
Definition at line 195 of file ManagedRequest.cs.
         {
             get
             {
                 return (float)UntilNextRequest.TotalSeconds;
             }
         }
Referenced by Juniper.Threading.ManagedRequest< T >.Loop().
Event Documentation
Error
EventHandler<BackgroundThreadErrorEventArgs> Juniper.Threading.AbstractBackgroundThread.Error inherited
An event that triggers if the background operation throws an exception.
Definition at line 14 of file AbstractBackgroundThread.cs.
Referenced by Juniper.Threading.AbstractBackgroundThread.OnError().
Message
EventHandler<ManagedRequestMessageArgs<T> > Juniper.Threading.ManagedRequest< T >.Message
Capture when the request poller returns a good result.
Definition at line 46 of file ManagedRequest.cs.
Referenced by Juniper.Threading.ManagedRequest< T >.OnMessage().
Ready
EventHandler<ManagedRequestReadyEventArgs<T> > Juniper.Threading.ManagedRequest< T >.Ready
Capture when the request poller is ready.
Definition at line 41 of file ManagedRequest.cs.
Referenced by Juniper.Threading.ManagedRequest< T >.OnReady().
ServerError
EventHandler<BackgroundThreadErrorEventArgs> Juniper.Threading.ManagedRequest< T >.ServerError
Capture when the request poller returns an error result.
Definition at line 51 of file ManagedRequest.cs.
Referenced by Juniper.Threading.ManagedRequest< T >.OnServerError().
TimedOut
EventHandler Juniper.Threading.ManagedRequest< T >.TimedOut
Capture when the request poller times out.
Definition at line 56 of file ManagedRequest.cs.
Referenced by Juniper.Threading.ManagedRequest< T >.OnTimedOut().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Threading/ManagedRequest.cs