Juniper: Juniper.Widgets.AbstractTouchable Class Reference
Juniper.Widgets.AbstractTouchable Class Reference
The base class for all interactive, AR-compatible, GUI controls /// This class is abstract to avoid it being used directly as a component. You must subclass this component and create a new component out of it.
Public Member Functions
void SetDisabled (bool value)
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
void ToggleEnabled ()
Toggles the boolean value of the disabled field.
virtual void OnPointerEnter (PointerEventData eventData)
Reqct to the pointer hovering over the control.
virtual void OnPointerExit (PointerEventData eventData)
React to the pointer leaving the control and no longer hovering over it.
virtual void OnPointerDown (PointerEventData eventData)
React to the primary button being pressed on the control.
virtual void OnPointerUp (PointerEventData eventData)
React to the primary button being released from the control.
Public Attributes
InputButton clickButton
The button we are expecting to use to interact with this object.
bool disabled
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occuring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Vector3 pointerPosition
The place near the control that the pointer was pointing.
Static Public Attributes
static string [] PART_NAMES
The names of the animation states that Touchable expects.
Protected Member Functions
virtual void Awake ()
Get the Rigidbody, AbstractAnimator, AudioSource, and InteractionAudio for this control.
virtual void Update ()
Update the physics state of the control, and enable/disable Disabled view on DisabledChanged.
virtual void LateUpdate ()
Saves the state of the flags from the current frame to have them for the next frame.
string ShowState (string enabledPart)
Trigger the animation or swap the gameObjects to show the current control UI state.
void GetPosition (PointerEventData eventData)
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Protected Attributes
Vector3 lastPointerPosition
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
Properties
bool DisabledChanged [get]
Returns true when the value of IsDisabled changes from one frame to the next.
bool DisabledDown [get]
Returns true when the value of IsDisabled goes from false to true.
bool DisabledUp [get]
Returns true when the value of IsDisabled goes from true to false.
bool IsDisabled [get, set]
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
bool PointerPositionChanged [get]
Returns true when pointerPosition has changed since the last frame.
Private Member Functions
string NormalizePart (string enabledPart)
Private Attributes
AbstractAnimator animator
An object responsible for changing the visible representation of the control when the control's state changes.
bool? wasDisabled
The value of IsDisabled in the last frame.
Detailed Description
The base class for all interactive, AR-compatible, GUI controls /// This class is abstract to avoid it being used directly as a component. You must subclass this component and create a new component out of it.
Definition at line 23 of file AbstractTouchable.cs.
Member Function Documentation
Awake()
virtual void Juniper.Widgets.AbstractTouchable.Awake () inline protected virtual
Get the Rigidbody, AbstractAnimator, AudioSource, and InteractionAudio for this control.
Reimplemented in Juniper.Widgets.AbstractValued, Juniper.Widgets.Openable, and Juniper.Widgets.Rotatable.
Definition at line 161 of file AbstractTouchable.cs.
         {
             animator = AbstractAnimator.GetAnimator(gameObject, PART_NAMES);
         }
References Juniper.Widgets.AbstractTouchable.animator, Juniper.Animation.AbstractAnimator.GetAnimator(), and Juniper.Widgets.AbstractTouchable.PART_NAMES.
GetPosition()
void Juniper.Widgets.AbstractTouchable.GetPosition (PointerEventData eventData) inline protected
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Parameters
eventData Event data.
Definition at line 219 of file AbstractTouchable.cs.
         {
             pointerPosition = eventData.pointerCurrentRaycast.worldPosition;
             eventData.Use();
         }
References Juniper.Widgets.AbstractTouchable.pointerPosition.
Referenced by Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Widgets.AbstractTouchable.OnPointerUp().
LateUpdate()
virtual void Juniper.Widgets.AbstractTouchable.LateUpdate () inline protected virtual
Saves the state of the flags from the current frame to have them for the next frame.
Reimplemented in Juniper.Widgets.AbstractValued, Juniper.Widgets.Draggable, and Juniper.Widgets.Openable.
Definition at line 184 of file AbstractTouchable.cs.
         {
             wasDisabled = IsDisabled;
             lastPointerPosition = pointerPosition;
         }
References Juniper.Widgets.AbstractTouchable.IsDisabled, Juniper.Widgets.AbstractTouchable.lastPointerPosition, Juniper.Widgets.AbstractTouchable.pointerPosition, and Juniper.Widgets.AbstractTouchable.wasDisabled.
NormalizePart()
string Juniper.Widgets.AbstractTouchable.NormalizePart (string enabledPart) inline private
Definition at line 190 of file AbstractTouchable.cs.
         {
             // If the desired state doesn't have a graphics object to display, then just display
             // the default state.
             if (enabledPart == null || !animator.HasState(enabledPart))
             {
                 enabledPart = PART_NAMES[0];
             }
             return enabledPart;
         }
References Juniper.Widgets.AbstractTouchable.animator, Juniper.Animation.AbstractAnimator.HasState(), and Juniper.Widgets.AbstractTouchable.PART_NAMES.
Referenced by Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerDown()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerDown (PointerEventData eventData) inline virtual
React to the primary button being pressed on the control.
Parameters
eventData Event data.
Definition at line 255 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton)
             {
                 if (IsDisabled)
                 {
                     ShowState("Disabled");
                 }
                 else
                 {
                     GetPosition(eventData);
                     ShowState("Pressed");
                 }
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerEnter()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerEnter (PointerEventData eventData) inline virtual
Reqct to the pointer hovering over the control.
Parameters
eventData Event data.
Definition at line 229 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerExit()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerExit (PointerEventData eventData) inline virtual
React to the pointer leaving the control and no longer hovering over it.
Parameters
eventData Event data.
Definition at line 242 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Normal");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerUp()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerUp (PointerEventData eventData) inline virtual
React to the primary button being released from the control.
Parameters
eventData Event data.
Definition at line 275 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
SetDisabled()
void Juniper.Widgets.AbstractTouchable.SetDisabled (bool value) inline
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
Parameters
value
Definition at line 121 of file AbstractTouchable.cs.
         {
             IsDisabled = value;
         }
References Juniper.Widgets.AbstractTouchable.IsDisabled.
ShowState()
string Juniper.Widgets.AbstractTouchable.ShowState (string enabledPart) inline protected
Trigger the animation or swap the gameObjects to show the current control UI state.
Returns
The state.
Parameters
enabledPart Enabled part.
Definition at line 207 of file AbstractTouchable.cs.
         {
             enabledPart = NormalizePart(enabledPart);
             animator?.Play(enabledPart);
             return enabledPart;
         }
References Juniper.Widgets.AbstractTouchable.animator, Juniper.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Animation.AbstractAnimator.Play().
Referenced by Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Widgets.AbstractTouchable.Update().
ToggleEnabled()
void Juniper.Widgets.AbstractTouchable.ToggleEnabled () inline
Toggles the boolean value of the disabled field.
Definition at line 129 of file AbstractTouchable.cs.
         {
             IsDisabled = !IsDisabled;
         }
References Juniper.Widgets.AbstractTouchable.IsDisabled.
Update()
virtual void Juniper.Widgets.AbstractTouchable.Update () inline protected virtual
Update the physics state of the control, and enable/disable Disabled view on DisabledChanged.
Reimplemented in Juniper.Widgets.Rotatable, and Juniper.Widgets.Openable.
Definition at line 169 of file AbstractTouchable.cs.
         {
             if (DisabledDown)
             {
                 ShowState(PART_NAMES.Last());
             }
             else if (DisabledUp)
             {
                 ShowState(PART_NAMES[0]);
             }
         }
References Juniper.Widgets.AbstractTouchable.DisabledDown, Juniper.Widgets.AbstractTouchable.DisabledUp, Juniper.Widgets.AbstractTouchable.PART_NAMES, and Juniper.Widgets.AbstractTouchable.ShowState().
Referenced by Juniper.Widgets.AbstractValued.SetValue().
Member Data Documentation
animator
AbstractAnimator Juniper.Widgets.AbstractTouchable.animator private
An object responsible for changing the visible representation of the control when the control's state changes.
Definition at line 49 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.Awake(), Juniper.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Widgets.AbstractTouchable.ShowState().
clickButton
InputButton Juniper.Widgets.AbstractTouchable.clickButton
The button we are expecting to use to interact with this object.
Definition at line 43 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.Clickable.OnLongPress(), Juniper.Widgets.Clickable.OnLongPressUpdate(), Juniper.Widgets.Clickable.OnPointerClick(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Widgets.AbstractTouchable.OnPointerUp().
disabled
bool Juniper.Widgets.AbstractTouchable.disabled
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occuring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Definition at line 56 of file AbstractTouchable.cs.
lastPointerPosition
Vector3 Juniper.Widgets.AbstractTouchable.lastPointerPosition protected
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
Definition at line 143 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.LateUpdate(), and Juniper.Widgets.AbstractValued.OnDrag().
PART_NAMES
string [] Juniper.Widgets.AbstractTouchable.PART_NAMES static
Initial value:
=
        {
            "Normal",
            "Hovered",
            "Pressed",
            "Opened",
            "Disabled"
        }
The names of the animation states that Touchable expects.
Definition at line 31 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.Awake(), Juniper.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Widgets.AbstractTouchable.Update().
pointerPosition
Vector3 Juniper.Widgets.AbstractTouchable.pointerPosition
The place near the control that the pointer was pointing.
Definition at line 137 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.LateUpdate(), Juniper.Widgets.AbstractValued.OnBeginDrag(), and Juniper.Widgets.AbstractValued.OnDrag().
wasDisabled
bool? Juniper.Widgets.AbstractTouchable.wasDisabled private
The value of IsDisabled in the last frame.
Definition at line 61 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.LateUpdate().
Property Documentation
DisabledChanged
bool Juniper.Widgets.AbstractTouchable.DisabledChanged get private
Returns true when the value of IsDisabled changes from one frame to the next.
true if disabled changed; otherwise, false.
Definition at line 68 of file AbstractTouchable.cs.
         {
             get
             {
                 return IsDisabled != wasDisabled;
             }
         }
DisabledDown
bool Juniper.Widgets.AbstractTouchable.DisabledDown get private
Returns true when the value of IsDisabled goes from false to true.
true if disabled down; otherwise, false.
Definition at line 80 of file AbstractTouchable.cs.
         {
             get
             {
                 return DisabledChanged && IsDisabled;
             }
         }
Referenced by Juniper.Widgets.AbstractTouchable.Update().
DisabledUp
bool Juniper.Widgets.AbstractTouchable.DisabledUp get private
Returns true when the value of IsDisabled goes from true to false.
true if disabled up; otherwise, false.
Definition at line 92 of file AbstractTouchable.cs.
         {
             get
             {
                 return DisabledChanged && !IsDisabled;
             }
         }
Referenced by Juniper.Widgets.AbstractTouchable.Update().
IsDisabled
bool Juniper.Widgets.AbstractTouchable.IsDisabled get set
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
Definition at line 104 of file AbstractTouchable.cs.
         {
             get
             {
                 return !isActiveAndEnabled || disabled;
             }
             set
             {
                 disabled = value;
             }
         }
Referenced by Juniper.Widgets.AbstractTouchable.LateUpdate(), Juniper.Widgets.Rotatable.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.Rotatable.OnDrag(), Juniper.Widgets.Draggable.OnDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.Clickable.OnLongPress(), Juniper.Widgets.Clickable.OnLongPressUpdate(), Juniper.Widgets.Clickable.OnPointerClick(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Widgets.AbstractTouchable.SetDisabled(), Juniper.Widgets.Openable.SetOpen(), Juniper.Widgets.AbstractTouchable.ToggleEnabled(), and Juniper.Widgets.Rotatable.Update().
PointerPositionChanged
bool Juniper.Widgets.AbstractTouchable.PointerPositionChanged get protected
Returns true when pointerPosition has changed since the last frame.
true if pointer position changed; otherwise, false.
Definition at line 150 of file AbstractTouchable.cs.
         {
             get
             {
                 return pointerPosition != lastPointerPosition;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/AbstractTouchable.cs