Juniper: Juniper.Console.IConsoleBuffer Interface Reference
Juniper.Console.IConsoleBuffer Interface Reference
Public Member Functions
void Draw (int x, int y, char c, ConsoleColor f, ConsoleColor b)
ConsoleColor GetBackgroundColor (int x, int y)
Properties
int AbsoluteLeft [get]
int AbsoluteRight [get]
int AbsoluteTop [get]
int AbsoluteBottom [get]
int Height [get]
int Width [get]
Detailed Description
Definition at line 5 of file IConsoleBuffer.cs.
Member Function Documentation
Draw()
void Juniper.Console.IConsoleBuffer.Draw (int x, int y, char c, ConsoleColor f, ConsoleColor b)
Implemented in Juniper.Console.ConsoleBuffer, and Juniper.Console.ConsoleBufferSubdivision.
Referenced by Juniper.Console.ConsoleBufferSubdivision.Draw(), Juniper.Console.IConsoleBufferExt.Draw(), Juniper.Console.IConsoleBufferExt.DrawPuzzle(), Juniper.Console.IConsoleBufferExt.Fill(), and Juniper.Console.IConsoleBufferExt.Stroke().
GetBackgroundColor()
ConsoleColor Juniper.Console.IConsoleBuffer.GetBackgroundColor (int x, int y)
Implemented in Juniper.Console.ConsoleBuffer, and Juniper.Console.ConsoleBufferSubdivision.
Referenced by Juniper.Console.IConsoleBufferExt.Draw(), Juniper.Console.ConsoleBufferSubdivision.GetBackgroundColor(), and Juniper.Console.IConsoleBufferExt.Stroke().
Property Documentation
AbsoluteBottom
int Juniper.Console.IConsoleBuffer.AbsoluteBottom get
Definition at line 10 of file IConsoleBuffer.cs.
 { get; }
AbsoluteLeft
int Juniper.Console.IConsoleBuffer.AbsoluteLeft get
Definition at line 7 of file IConsoleBuffer.cs.
 { get; }
AbsoluteRight
int Juniper.Console.IConsoleBuffer.AbsoluteRight get
Definition at line 8 of file IConsoleBuffer.cs.
 { get; }
AbsoluteTop
int Juniper.Console.IConsoleBuffer.AbsoluteTop get
Definition at line 9 of file IConsoleBuffer.cs.
 { get; }
Height
int Juniper.Console.IConsoleBuffer.Height get
Definition at line 11 of file IConsoleBuffer.cs.
 { get; }
Referenced by Juniper.Console.IConsoleBufferExt.Fill().
Width
int Juniper.Console.IConsoleBuffer.Width get
Definition at line 12 of file IConsoleBuffer.cs.
 { get; }
Referenced by Juniper.Console.IConsoleBufferExt.Fill().
The documentation for this interface was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Console/IConsoleBuffer.cs