Juniper: Juniper.Unity.Input.Speech.AbstractKeywordRecognizer Class Reference
Juniper.Unity.Input.Speech.AbstractKeywordRecognizer Class Reference abstract
A class that implements basic functionality for systems that manage speech recognition and route out the events associated with recognizing keywords.
Public Member Functions
void RefreshKeywords ()
Find all of the keyword-responding components that are currently active in the scene, collect up their keywords, and register them return them as a set-array to be registered with the speech recognition system.
void OnEnable ()
Initialize the speech recognition system.
void OnDisable ()
Tear down the speech recognition system.
Public Attributes
StringEvent onKeywordRecognized = new StringEvent()
Respond to the speech recognition system having detected a keyword. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should prefer KeywordRecognized.
Protected Member Functions
void OnKeywordRecognized (string keyword)
Invokes onKeywordRecognized and KeywordRecognized.
abstract void Setup ()
abstract void TearDown ()
Protected Attributes
string [] keywords
The keywords for which to listen.
Events
EventHandler< KeywordRecognizedEventArgs > KeywordRecognized
Respond to the speech recognition system having detected a keyword. You should only use this version if you are programmatically attaching event listeners. If you are attaching events in the Unity Editor, you should prefer onKeywordRecognized.
Detailed Description
A class that implements basic functionality for systems that manage speech recognition and route out the events associated with recognizing keywords.
Definition at line 26 of file KeywordRecognizer.cs.
Member Function Documentation
OnDisable()
void Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.OnDisable () inline
Tear down the speech recognition system.
Definition at line 90 of file KeywordRecognizer.cs.
         {
             TearDown();
         }
References Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.TearDown().
OnEnable()
void Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.OnEnable () inline
Initialize the speech recognition system.
Definition at line 82 of file KeywordRecognizer.cs.
         {
             RefreshKeywords();
         }
References Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.RefreshKeywords().
OnKeywordRecognized()
void Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.OnKeywordRecognized (string keyword) inline protected
Invokes onKeywordRecognized and KeywordRecognized.
Parameters
keyword Keyword.
Definition at line 51 of file KeywordRecognizer.cs.
         {
             onKeywordRecognized?.Invoke(keyword);
             KeywordRecognized?.Invoke(this, new KeywordRecognizedEventArgs(keyword));
         }
References Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.KeywordRecognized, and Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.onKeywordRecognized.
RefreshKeywords()
void Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.RefreshKeywords () inline
Find all of the keyword-responding components that are currently active in the scene, collect up their keywords, and register them return them as a set-array to be registered with the speech recognition system.
Returns
The active keywords.
Implements Juniper.Unity.Speech.IKeywordRecognizer.
Definition at line 63 of file KeywordRecognizer.cs.
         {
             TearDown();
             keywords = (from comp in ComponentExt.FindAll<MonoBehaviour>()
                         where comp is IKeywordTriggered
                         let trigger = (IKeywordTriggered)comp
                         where trigger.Keywords != null
                         from keyword in trigger.Keywords
                         where !string.IsNullOrEmpty(keyword)
                         select keyword)
                 .Distinct()
                 .OrderBy(x => x)
                 .ToArray();
             Setup();
         }
References Juniper.Speech.IKeywordTriggered.Keywords, Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.keywords, Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.Setup(), and Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.TearDown().
Referenced by Juniper.Unity.Input.Speech.Keywordable.OnEnable(), and Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.OnEnable().
Setup()
abstract void Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.Setup () protected pure virtual
Implemented in Juniper.Unity.Input.Speech.NoKeywordRecognizer.
Referenced by Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.RefreshKeywords().
TearDown()
abstract void Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.TearDown () protected pure virtual
Implemented in Juniper.Unity.Input.Speech.NoKeywordRecognizer.
Referenced by Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.OnDisable(), and Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.RefreshKeywords().
Member Data Documentation
keywords
string [] Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.keywords protected
The keywords for which to listen.
Definition at line 31 of file KeywordRecognizer.cs.
Referenced by Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.RefreshKeywords().
onKeywordRecognized
StringEvent Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.onKeywordRecognized = new StringEvent()
Respond to the speech recognition system having detected a keyword. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should prefer KeywordRecognized.
Definition at line 38 of file KeywordRecognizer.cs.
Referenced by Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.OnKeywordRecognized(), and Juniper.Unity.Input.Speech.Keywordable.Start().
Event Documentation
KeywordRecognized
EventHandler<KeywordRecognizedEventArgs> Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.KeywordRecognized
Respond to the speech recognition system having detected a keyword. You should only use this version if you are programmatically attaching event listeners. If you are attaching events in the Unity Editor, you should prefer onKeywordRecognized.
Definition at line 45 of file KeywordRecognizer.cs.
Referenced by Juniper.Unity.Input.Speech.AbstractKeywordRecognizer.OnKeywordRecognized().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/Speech/KeywordRecognizer.cs