Juniper: Juniper.Console.IConsoleBufferExt Class Reference
Juniper.Console.IConsoleBufferExt Class Reference
Static Public Member Functions
static IConsoleBuffer Window (this IConsoleBuffer buffer, int x, int y, int width, int height)
static void Clear (this IConsoleBuffer buffer)
static void Fill (this IConsoleBuffer buffer, ConsoleColor b)
static void Fill (this IConsoleBuffer buffer, int x, int y, int width, int height, ConsoleColor b)
static void Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, char vertSideToken, char horizSideToken, char ulToken, char urToken, char llToken, char lrToken, ConsoleColor f)
static void Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, BoxDrawingSet set, ConsoleColor f)
static void Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, BoxDrawingSet set, ConsoleColor f, ConsoleColor b)
static void Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, char vertSideToken, char horizSideToken, char ulToken, char urToken, char llToken, char lrToken, ConsoleColor f, ConsoleColor b)
static void Draw (this IConsoleBuffer buffer, int x, int y, char c, ConsoleColor f)
static void Draw (this IConsoleBuffer buffer, int x, int y, string s, ConsoleColor f, ConsoleColor b)
static void Draw (this IConsoleBuffer buffer, int x, int y, string s, ConsoleColor f)
static void DrawPuzzle (this IConsoleBuffer buf, int x, int y, Puzzle p)
Detailed Description
Definition at line 8 of file IConsoleBufferExt.cs.
Member Function Documentation
Clear()
static void Juniper.Console.IConsoleBufferExt.Clear (this IConsoleBuffer buffer) inline static
Definition at line 20 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             buffer.Fill(ConsoleColor.Black);
         }
Draw() [1/3]
static void Juniper.Console.IConsoleBufferExt.Draw (this IConsoleBuffer buffer, int x, int y, char c, ConsoleColor f) inline static
Definition at line 115 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             buffer.Draw(x, y, c, f, buffer.GetBackgroundColor(x, y));
         }
References Juniper.Console.IConsoleBuffer.Draw(), and Juniper.Console.IConsoleBuffer.GetBackgroundColor().
Draw() [2/3]
static void Juniper.Console.IConsoleBufferExt.Draw (this IConsoleBuffer buffer, int x, int y, string s, ConsoleColor f, ConsoleColor b) inline static
Definition at line 125 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             if (s is null)
             {
                 throw new ArgumentNullException(nameof(s));
             }
             for (var dx = 0; dx < s.Length; ++dx)
             {
                 buffer.Draw(x + dx, y, s[dx], f, b);
             }
         }
References Juniper.Console.IConsoleBuffer.Draw().
Draw() [3/3]
static void Juniper.Console.IConsoleBufferExt.Draw (this IConsoleBuffer buffer, int x, int y, string s, ConsoleColor f) inline static
Definition at line 143 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             if (s is null)
             {
                 throw new ArgumentNullException(nameof(s));
             }
             for (var dx = 0; dx < s.Length; ++dx)
             {
                 buffer.Draw(x + dx, y, s[dx], f);
             }
         }
References Juniper.Console.IConsoleBuffer.Draw().
DrawPuzzle()
static void Juniper.Console.IConsoleBufferExt.DrawPuzzle (this IConsoleBuffer buf, int x, int y, Puzzle p) inline static
Definition at line 161 of file IConsoleBufferExt.cs.
         {
             if (buf is null)
             {
                 throw new ArgumentNullException(nameof(buf));
             }
             if (p is null)
             {
                 throw new ArgumentNullException(nameof(p));
             }
             for (var dx = 0; dx < p.Width; ++dx)
             {
                 for (var dy = 0; dy < p.Height; ++dy)
                 {
                     if (p[dx, dy] != Puzzle.EmptyTile)
                     {
                         buf.Draw(x + dx, y + dy, '#', (ConsoleColor)(p[dx, dy] + 8), (ConsoleColor)p[dx, dy]);
                     }
                 }
             }
         }
References Juniper.Console.IConsoleBuffer.Draw(), Juniper.Puzzles.Puzzle.EmptyTile, Juniper.Puzzles.Puzzle.Height, and Juniper.Puzzles.Puzzle.Width.
Fill() [1/2]
static void Juniper.Console.IConsoleBufferExt.Fill (this IConsoleBuffer buffer, ConsoleColor b) inline static
Definition at line 30 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             buffer.Fill(0, 0, buffer.Width, buffer.Height, b);
         }
References Juniper.Console.IConsoleBuffer.Height, and Juniper.Console.IConsoleBuffer.Width.
Fill() [2/2]
static void Juniper.Console.IConsoleBufferExt.Fill (this IConsoleBuffer buffer, int x, int y, int width, int height, ConsoleColor b) inline static
Definition at line 40 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             for (var dx = 0; dx < width; ++dx)
             {
                 for (var dy = 0; dy < height; ++dy)
                 {
                     buffer.Draw(x + dx, y + dy, ' ', ConsoleColor.Gray, b);
                 }
             }
         }
References Juniper.Console.IConsoleBuffer.Draw().
Stroke() [1/4]
static void Juniper.Console.IConsoleBufferExt.Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, char vertSideToken, char horizSideToken, char ulToken, char urToken, char llToken, char lrToken, ConsoleColor f) inline static
Definition at line 56 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             buffer.Stroke(x, y, width, height, vertSideToken, horizSideToken, ulToken, urToken, llToken, lrToken, f, buffer.GetBackgroundColor(x, y));
         }
References Juniper.Console.IConsoleBuffer.GetBackgroundColor().
Stroke() [2/4]
static void Juniper.Console.IConsoleBufferExt.Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, BoxDrawingSet set, ConsoleColor f) inline static
Definition at line 66 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             buffer.Stroke(x, y, width, height, set, f, buffer.GetBackgroundColor(x, y));
         }
References Juniper.Console.IConsoleBuffer.GetBackgroundColor().
Stroke() [3/4]
static void Juniper.Console.IConsoleBufferExt.Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, BoxDrawingSet set, ConsoleColor f, ConsoleColor b) inline static
Definition at line 76 of file IConsoleBufferExt.cs.
         {
             if (set is null)
             {
                 throw new ArgumentNullException(nameof(set));
             }
             buffer.Stroke(x, y, width, height, set.Vertical, set.Horizontal, set.UpperLeft, set.UpperRight, set.LowerLeft, set.LowerRight, f, b);
         }
Stroke() [4/4]
static void Juniper.Console.IConsoleBufferExt.Stroke (this IConsoleBuffer buffer, int x, int y, int width, int height, char vertSideToken, char horizSideToken, char ulToken, char urToken, char llToken, char lrToken, ConsoleColor f, ConsoleColor b) inline static
Definition at line 86 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             var right = x + width - 1;
             var bottom = y + height - 1;
             buffer.Draw(x, y, ulToken, f, b);
             buffer.Draw(right, y, urToken, f, b);
             buffer.Draw(x, bottom, llToken, f, b);
             buffer.Draw(right, bottom, lrToken, f, b);
             for (var dx = x + 1; dx < right; ++dx)
             {
                 buffer.Draw(dx, y, horizSideToken, f, b);
                 buffer.Draw(dx, bottom, horizSideToken, f, b);
             }
             for (var dy = y + 1; dy < bottom; ++dy)
             {
                 buffer.Draw(x, dy, vertSideToken, f, b);
                 buffer.Draw(right, dy, vertSideToken, f, b);
             }
         }
References Juniper.Console.IConsoleBuffer.Draw().
Window()
static IConsoleBuffer Juniper.Console.IConsoleBufferExt.Window (this IConsoleBuffer buffer, int x, int y, int width, int height) inline static
Definition at line 10 of file IConsoleBufferExt.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             return new ConsoleBufferSubdivision(buffer, x, y, width, height);
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Console/IConsoleBufferExt.cs