Juniper: Juniper.Unity.Animation.AlphaTransition Class Reference
Juniper.Unity.Animation.AlphaTransition Class Reference
Performs a shrinking/growing animation on scene transitions.
Public Member Functions
override void Enter ()
Start the transition animation in the forward direction.
override void SkipEnter ()
Jump the transition to the ENTERED state, without animating through the ENTERING state.
override void Exit ()
Start the transition animation in the outward direction.
override void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Public Attributes
float minAlpha = 0
The minimum opacity of the object, where 0 = completely transparent.
float maxAlpha = 1
The maximum opacity of the object, where 1 = completely opaque.
float length = 0.25f
The amount of time it takes to complete the transition.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void RenderValue (float value)
Updates the size of the transitioning object every frame the transition is active.
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Properties
override float TransitionLength [get]
The amount of time it takes to complete the transition.
float DeltaAlpha [get]
The scale range the transition has to traverse.
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler< ValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Attributes
Material transitionMaterial
The material on which the opacity is being set.
Detailed Description
Performs a shrinking/growing animation on scene transitions.
Definition at line 9 of file AlphaTransition.cs.
Member Function Documentation
Enter()
override void Juniper.Unity.Animation.AbstractTransitionController.Enter () inline virtual inherited
Start the transition animation in the forward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 65 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.Enter();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.Widgets.TeleportPad.OnClick(), Juniper.Unity.MasterSceneController.QuitCoroutine(), Juniper.Unity.Widgets.Openable.SetOpen(), and Juniper.Unity.Animation.WorkflowStep.Show().
Exit()
override void Juniper.Unity.Animation.AbstractTransitionController.Exit () inline virtual inherited
Start the transition animation in the outward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 85 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Reverse);
             base.Exit();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.Unity.Widgets.Openable.SetOpen().
HasCompleted()
bool Juniper.Unity.AbstractStateController.HasCompleted () inline inherited
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 123 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.Unity.AbstractStateController.IsComplete.
OnDisable()
void Juniper.Unity.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 300 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.Unity.AbstractStateController.OnExited().
OnEnable()
void Juniper.Unity.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 195 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.Unity.AbstractStateController.OnEntering().
Referenced by Juniper.Unity.AbstractStateController.SkipEnter().
OnEntered()
virtual void Juniper.Unity.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 242 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntered?.Invoke();
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entered, Juniper.Unity.AbstractStateController.onEntered, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Update().
OnEntering()
virtual void Juniper.Unity.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 206 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntering?.Invoke();
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entering, Juniper.Unity.AbstractStateController.onEntering, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnEnable().
OnExited()
virtual void Juniper.Unity.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, and Juniper.Unity.SubSceneController.
Definition at line 312 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExited?.Invoke();
                 Exited?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Exited, Juniper.Unity.AbstractStateController.onExited, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnDisable().
OnExiting()
virtual void Juniper.Unity.AbstractStateController.OnExiting () inline protected virtual inherited
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 285 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExiting?.Invoke();
                 Exiting?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Exiting, Juniper.Unity.AbstractStateController.onExiting, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Exit(), and Juniper.Unity.AbstractStateController.SkipExit().
RenderValue()
override void Juniper.Unity.Animation.AlphaTransition.RenderValue (float value) inline protected virtual
Updates the size of the transitioning object every frame the transition is active.
Parameters
value
Implements Juniper.Unity.Animation.AbstractTransitionController.
Reimplemented in Juniper.Unity.Widgets.VideoVader.
Definition at line 52 of file AlphaTransition.cs.
         {
             if (transitionMaterial == null)
             {
                 transitionMaterial = GetComponent<Renderer>()?.GetMaterial();
             }
             if (transitionMaterial != null)
             {
                 var o = Mathf.Clamp01(minAlpha + value * DeltaAlpha);
                 transitionMaterial.SetFloat("_Alpha", o);
             }
         }
References Juniper.Unity.Animation.AlphaTransition.DeltaAlpha, Juniper.Unity.Animation.AlphaTransition.minAlpha, and Juniper.Unity.Animation.AlphaTransition.transitionMaterial.
SkipEnter()
override void Juniper.Unity.Animation.AbstractTransitionController.SkipEnter () inline virtual inherited
Jump the transition to the ENTERED state, without animating through the ENTERING state.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 74 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.SkipEnter();
             SetProgress(0);
         }
References Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut().
SkipExit()
virtual void Juniper.Unity.AbstractStateController.SkipExit () inline virtual inherited
Jump to the fully entered state without firing any events.
Definition at line 254 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnExiting(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
Update()
override void Juniper.Unity.Animation.AbstractTransitionController.Update () inline virtual inherited
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented from Juniper.Unity.AbstractStateController.
Reimplemented in Juniper.Unity.Animation.SpiralTransition.
Definition at line 95 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress > 0)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress - change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     SetProgress(0);
                     state = Direction.Stopped;
                 }
             }
             base.Update();
         }
References Juniper.Unity.Animation.AbstractTransitionController.attack, Juniper.Unity.AbstractStateController.IsRunning, Juniper.Unity.Animation.AbstractTransitionController.progress, Juniper.Unity.Animation.AbstractTransitionController.release, Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.state, and Juniper.Unity.Animation.AbstractTransitionController.TransitionLength.
Member Data Documentation
attackTime
float Juniper.Unity.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 20 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
length
float Juniper.Unity.Animation.AlphaTransition.length = 0.25f
The amount of time it takes to complete the transition.
Definition at line 24 of file AlphaTransition.cs.
maxAlpha
float Juniper.Unity.Animation.AlphaTransition.maxAlpha = 1
The maximum opacity of the object, where 1 = completely opaque.
Definition at line 19 of file AlphaTransition.cs.
minAlpha
float Juniper.Unity.Animation.AlphaTransition.minAlpha = 0
The minimum opacity of the object, where 0 = completely transparent.
Definition at line 14 of file AlphaTransition.cs.
Referenced by Juniper.Unity.Animation.AlphaTransition.RenderValue(), and Juniper.Unity.Widgets.VideoVader.RenderValue().
onEntered
UnityEvent Juniper.Unity.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 35 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.Unity.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 26 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.Unity.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 53 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.Unity.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 44 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
onValueChanged
UnityEvent Juniper.Unity.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 33 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
releaseTime
float Juniper.Unity.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 27 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
state
Direction Juniper.Unity.AbstractStateController.state inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 96 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), Juniper.Unity.Animation.AbstractTransitionController.Update(), and Juniper.Unity.AbstractStateController.Update().
transitionMaterial
Material Juniper.Unity.Animation.AlphaTransition.transitionMaterial private
The material on which the opacity is being set.
Definition at line 69 of file AlphaTransition.cs.
Referenced by Juniper.Unity.Animation.AlphaTransition.RenderValue().
tween
TweenType Juniper.Unity.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 38 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
tweenK
float Juniper.Unity.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 45 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
Property Documentation
DeltaAlpha
float Juniper.Unity.Animation.AlphaTransition.DeltaAlpha get protected
The scale range the transition has to traverse.
Definition at line 41 of file AlphaTransition.cs.
         {
             get
             {
                 return maxAlpha - minAlpha;
             }
         }
Referenced by Juniper.Unity.Animation.AlphaTransition.RenderValue(), and Juniper.Unity.Widgets.VideoVader.RenderValue().
IsComplete
virtual bool Juniper.Unity.AbstractStateController.IsComplete get inherited
Returns true when state is Direction.Stopped
Definition at line 112 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.HasCompleted(), and Juniper.Unity.AbstractStateController.Update().
IsEntered
bool Juniper.Unity.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 143 of file AbstractStateController.cs.
         {
             get
             {
                 return isActiveAndEnabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Exit().
IsExited
bool Juniper.Unity.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 154 of file AbstractStateController.cs.
         {
             get
             {
                 return !isActiveAndEnabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Enter().
IsRunning
bool Juniper.Unity.AbstractStateController.IsRunning get inherited
Returns true when state is not Direction.Stopped
Definition at line 132 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
TransitionLength
override float Juniper.Unity.Animation.AlphaTransition.TransitionLength get
The amount of time it takes to complete the transition.
Definition at line 30 of file AlphaTransition.cs.
         {
             get
             {
                 return length;
             }
         }
Waiter
WaitUntil Juniper.Unity.AbstractStateController.Waiter get inherited
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 331 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.Unity.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 71 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.Unity.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 62 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.Unity.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 89 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.Unity.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 80 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnExiting().
ValueChanged
EventHandler<ValueChangedEventArgs> Juniper.Unity.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 51 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Animation/AlphaTransition.cs