Juniper: Juniper.Unity.ConfigurationManagement.RawPackage Class Reference
Juniper.Unity.ConfigurationManagement.RawPackage Class Reference
Public Member Functions
RawPackage ()
override void Install (IProgressReceiver prog=null)
override void Activate (BuildTargetGroup targetGroup, IProgressReceiver prog=null)
override void Uninstall (IProgressReceiver prog=null)
Public Attributes
string spatializer
string androidSdkVersion
string iOSVersion
string wsaSubtarget
string Name
string CompilerDefine
Static Public Attributes
static string ROOT_DIRECTORY = PathExt.FixPath("Assets/Juniper/ThirdParty/Optional")
Properties
string InputZipFileName [get]
Static Private Member Functions
static void DeleteAll (IEnumerable< string > paths, Func< string, bool > tryDelete, IProgressReceiver prog)
Detailed Description
Definition at line 17 of file RawPackage.cs.
Constructor & Destructor Documentation
RawPackage()
Juniper.Unity.ConfigurationManagement.RawPackage.RawPackage () inline
Definition at line 26 of file RawPackage.cs.
         {
             spatializer = null;
             androidSdkVersion = null;
             iOSVersion = null;
             wsaSubtarget = null;
         }
References Juniper.Unity.ConfigurationManagement.RawPackage.androidSdkVersion, Juniper.Unity.ConfigurationManagement.RawPackage.iOSVersion, Juniper.Unity.ConfigurationManagement.RawPackage.spatializer, and Juniper.Unity.ConfigurationManagement.RawPackage.wsaSubtarget.
Member Function Documentation
Activate()
override void Juniper.Unity.ConfigurationManagement.RawPackage.Activate (BuildTargetGroup targetGroup, IProgressReceiver prog = null) inline virtual
Reimplemented from Juniper.Unity.ConfigurationManagement.AbstractPackage.
Definition at line 55 of file RawPackage.cs.
         {
             base.Activate(targetGroup, prog);
             if (!string.IsNullOrEmpty(spatializer))
             {
                 var hasSpatializer = AudioSettings
                     .GetSpatializerPluginNames()
                     .Contains(spatializer);
                 if (hasSpatializer)
                 {
                     AudioSettings.SetSpatializerPluginName(spatializer);
                     AudioSettingsExt.SetAmbisonicDecoderPluginName(spatializer);
                 }
             }
             if (Name == "Vuforia")
             {
                 PlayerSettings.SetPlatformVuforiaEnabled(targetGroup, true);
             }
             if (targetGroup == BuildTargetGroup.Android)
             {
                 if (Name == "GoogleARCore")
                 {
 #if UNITY_2018_2_OR_NEWER
                     PlayerSettings.Android.ARCoreEnabled = true;
 #endif
                 }
                 else if (Name == "GoogleVR")
                 {
                     FileExt.Copy(
                         PathExt.FixPath("Assets/GoogleVR/Plugins/Android/AndroidManifest-6DOF.xml"),
                         PathExt.FixPath("Assets/Plugins/Android/AndroidManifest.xml"),
                         true);
                 }
                 AndroidSdkVersions sdkVersion;
                 if (Enum.TryParse(androidSdkVersion, out sdkVersion))
                 {
                     PlayerSettings.Android.minSdkVersion = (AndroidSdkVersions)Math.Max(
                         (int)PlayerSettings.Android.minSdkVersion,
                         (int)sdkVersion);
                 }
             }
             else if (targetGroup == BuildTargetGroup.iOS)
             {
                 Version v;
                 if (Version.TryParse(iOSVersion, out v)
                     && PlayerSettingsExt.iOS.TargetOSVersion < v)
                 {
                     PlayerSettingsExt.iOS.TargetOSVersion = v;
                 }
                 if (Name == "UnityARKitPlugin")
                 {
                     PlayerSettingsExt.iOS.RequiresARKitSupport = true;
                     if (string.IsNullOrEmpty(PlayerSettings.iOS.cameraUsageDescription))
                     {
                         PlayerSettings.iOS.cameraUsageDescription = "Augmented reality camera view";
                     }
                 }
             }
             else if (targetGroup == BuildTargetGroup.WSA)
             {
                 WSASubtarget sub;
                 if (Enum.TryParse(wsaSubtarget, out sub))
                 {
                     EditorUserBuildSettings.wsaSubtarget = sub;
                     PlayerSettings.WSA.SetCapability(PlayerSettings.WSACapability.SpatialPerception, sub == WSASubtarget.HoloLens);
                 }
             }
         }
References Juniper.Unity.ConfigurationManagement.RawPackage.androidSdkVersion, System.IO.FileExt.Copy(), System.IO.PathExt.FixPath(), Juniper.Unity.ConfigurationManagement.RawPackage.iOSVersion, Juniper.Unity.ConfigurationManagement.AbstractPackage.Name, UnityEditor.PlayerSettingsExt.iOS.RequiresARKitSupport, UnityEditor.AudioSettingsExt.SetAmbisonicDecoderPluginName(), Juniper.Unity.ConfigurationManagement.RawPackage.spatializer, UnityEditor.PlayerSettingsExt.iOS.TargetOSVersion, and Juniper.Unity.ConfigurationManagement.RawPackage.wsaSubtarget.
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.Activate().
DeleteAll()
static void Juniper.Unity.ConfigurationManagement.RawPackage.DeleteAll (IEnumerable< string > paths, Func< string, bool > tryDelete, IProgressReceiver prog) inline static private
Definition at line 131 of file RawPackage.cs.
         {
             prog?.SetProgress(0, "Deleting");
             var prefixedPath = paths
                 .Select(path => Path.Combine("Assets", path))
                 .ToArray();
             var subProgs = prog.Split(prefixedPath.Length);
             var index = 0;
             foreach (var path in prefixedPath)
             {
                 try
                 {
                     subProgs[index]?.SetProgress(0);
                     if (tryDelete(path))
                     {
                         subProgs[index]?.SetProgress(1);
                     }
                     ++index;
                 }
                 catch (OperationCanceledException)
                 {
                     throw;
                 }
                 catch (Exception exp)
                 {
                     Debug.LogException(exp);
                 }
             }
             prog?.SetProgress(1, "Deleted");
         }
References Juniper.Progress.IProgressReceiver.SetProgress().
Referenced by Juniper.Unity.ConfigurationManagement.RawPackage.Uninstall().
Install()
override void Juniper.Unity.ConfigurationManagement.RawPackage.Install (IProgressReceiver prog = null) inline virtual
Reimplemented from Juniper.Unity.ConfigurationManagement.AbstractPackage.
Definition at line 43 of file RawPackage.cs.
         {
             base.Install(prog);
             if (File.Exists(InputZipFileName))
             {
                 Zip.DecompressDirectory(InputZipFileName, "Assets", prog);
             }
             prog?.SetProgress(1);
         }
References Juniper.Data.Zip.DecompressDirectory(), and Juniper.Unity.ConfigurationManagement.RawPackage.InputZipFileName.
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.InstallRawPackages().
Uninstall()
override void Juniper.Unity.ConfigurationManagement.RawPackage.Uninstall (IProgressReceiver prog = null) inline virtual
Reimplemented from Juniper.Unity.ConfigurationManagement.AbstractPackage.
Definition at line 165 of file RawPackage.cs.
         {
             base.Uninstall(prog);
             var progs = prog.Split(4);
             var dirs = Zip.RecurseDirectories(InputZipFileName, progs[2]);
             var files = Zip.RecurseFiles(InputZipFileName, progs[0]);
             files = files
                 .Union(files.Select(file => file + ".meta"))
                 .Union(dirs.Select(dir => dir + ".meta"))
                 .Where(path => !path.EndsWith(".meta.meta"));
             DeleteAll(files, FileExt.TryDelete, progs[1]);
             DeleteAll(dirs.Reverse(), DirectoryExt.TryDelete, progs[3]);
         }
References Juniper.Unity.ConfigurationManagement.RawPackage.DeleteAll(), Juniper.Unity.ConfigurationManagement.RawPackage.InputZipFileName, Juniper.Data.Zip.RecurseDirectories(), Juniper.Data.Zip.RecurseFiles(), System.IO.FileExt.TryDelete(), and System.IO.DirectoryExt.TryDelete().
Referenced by Juniper.Unity.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages().
Member Data Documentation
androidSdkVersion
string Juniper.Unity.ConfigurationManagement.RawPackage.androidSdkVersion
Definition at line 22 of file RawPackage.cs.
Referenced by Juniper.Unity.ConfigurationManagement.RawPackage.Activate(), and Juniper.Unity.ConfigurationManagement.RawPackage.RawPackage().
CompilerDefine
string Juniper.Unity.ConfigurationManagement.AbstractPackage.CompilerDefine inherited
Definition at line 10 of file AbstractPackage.cs.
Referenced by Juniper.Unity.ConfigurationManagement.Platforms.GetCompilerDefines(), and Juniper.Unity.ConfigurationManagement.UnityPackage.UnityPackage().
iOSVersion
string Juniper.Unity.ConfigurationManagement.RawPackage.iOSVersion
Definition at line 23 of file RawPackage.cs.
Referenced by Juniper.Unity.ConfigurationManagement.RawPackage.Activate(), and Juniper.Unity.ConfigurationManagement.RawPackage.RawPackage().
Name
string Juniper.Unity.ConfigurationManagement.AbstractPackage.Name inherited
Definition at line 9 of file AbstractPackage.cs.
Referenced by Juniper.Unity.ConfigurationManagement.RawPackage.Activate(), Juniper.Unity.ConfigurationManagement.UnityPackage.Install(), Juniper.Unity.ConfigurationManagement.UnityPackage.Uninstall(), and Juniper.Unity.ConfigurationManagement.UnityPackage.UnityPackage().
ROOT_DIRECTORY
string Juniper.Unity.ConfigurationManagement.RawPackage.ROOT_DIRECTORY = PathExt.FixPath("Assets/Juniper/ThirdParty/Optional") static
Definition at line 19 of file RawPackage.cs.
Referenced by Juniper.Unity.ConfigurationManagement.Platforms.Platforms().
spatializer
string Juniper.Unity.ConfigurationManagement.RawPackage.spatializer
Definition at line 21 of file RawPackage.cs.
Referenced by Juniper.Unity.ConfigurationManagement.RawPackage.Activate(), and Juniper.Unity.ConfigurationManagement.RawPackage.RawPackage().
wsaSubtarget
string Juniper.Unity.ConfigurationManagement.RawPackage.wsaSubtarget
Definition at line 24 of file RawPackage.cs.
Referenced by Juniper.Unity.ConfigurationManagement.RawPackage.Activate(), and Juniper.Unity.ConfigurationManagement.RawPackage.RawPackage().
Property Documentation
InputZipFileName
string Juniper.Unity.ConfigurationManagement.RawPackage.InputZipFileName get
Definition at line 36 of file RawPackage.cs.
         {
             get
             {
                 return Path.ChangeExtension(Path.Combine(ROOT_DIRECTORY, Name), "zip");
             }
         }
Referenced by Juniper.Unity.ConfigurationManagement.RawPackage.Install(), and Juniper.Unity.ConfigurationManagement.RawPackage.Uninstall().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/ConfigurationManagement/RawPackage.cs