Juniper: Juniper.Unity.Data.StreamingAssets Class Reference
Juniper.Unity.Data.StreamingAssets Class Reference
Get files out of the Unity StreamingAssets folder.
Static Public Member Functions
static string FormatPath (string dataPath, string subPath)
static void GetCachedFile (string cacheDirectory, string path, TimeSpan ttl, string mime, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog=null)
Open a file as an stream of bytes and save it to a cached location. On subsequent loads, open from the cached location.
static void GetCachedFile (string cacheDirectory, string path, TimeSpan ttl, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetCachedFile (string cacheDirectory, string path, string mime, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetCachedFile (string cacheDirectory, string path, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetStream (string cacheDirectory, string path, TimeSpan ttl, string mime, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog=null)
Open a file as an stream of bytes.
static void GetStream (string cacheDirectory, string path, TimeSpan ttl, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetStream (string cacheDirectory, string path, string mime, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetStream (string cacheDirectory, string path, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetBytes (string cacheDirectory, string path, TimeSpan ttl, string mime, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog=null)
Open a file as an array of bytes.
static void GetBytes (string cacheDirectory, string path, TimeSpan ttl, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetBytes (string cacheDirectory, string path, string mime, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetBytes (string cacheDirectory, string path, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetText (string cacheDirectory, string path, TimeSpan ttl, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog=null)
Open a file as a text string
static void GetText (string cacheDirectory, string path, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog=null)
static void GetJSONObject< T > (string cacheDirectory, string path, TimeSpan ttl, Action< T > resolve, Action< Exception > reject, IProgressReceiver prog=null)
Open a file as a deserialized JSON object.
static void GetJSONObject< T > (string cacheDirectory, string path, Action< T > resolve, Action< Exception > reject, IProgressReceiver prog=null)
Static Public Attributes
static TimeSpan DEFAULT_TTL = TimeSpan.Zero
Static Private Member Functions
static bool FileIsGood (string path, TimeSpan ttl)
static void GetOrCacheFile (string cacheDirectory, string fileName, TimeSpan ttl, Action< Action< Stream >> getStreamResolver, Action< string > resolve, IProgressReceiver prog=null)
Private Attributes
const string NetworkPathPatternStr = "^https?://"
Parse out the network path.
Static Private Attributes
static readonly Regex NetworkPathPattern = new Regex(NetworkPathPatternStr, RegexOptions.Compiled)
Parse out the network path.
Detailed Description
Get files out of the Unity StreamingAssets folder.
Definition at line 17 of file StreamingAssets.cs.
Member Function Documentation
FileIsGood()
static bool Juniper.Unity.Data.StreamingAssets.FileIsGood (string path, TimeSpan ttl) inline static private
Definition at line 260 of file StreamingAssets.cs.
         {
             return File.Exists(path) && File.GetCreationTime(path) - DateTime.Now <= ttl;
         }
Referenced by Juniper.Unity.Data.StreamingAssets.GetOrCacheFile().
FormatPath()
static string Juniper.Unity.Data.StreamingAssets.FormatPath (string dataPath, string subPath) inline static
Definition at line 21 of file StreamingAssets.cs.
         {
             var parts = new List<string>();
             if (!NetworkPathPattern.IsMatch(subPath))
             {
 #if UNITY_EDITOR || PLATFORM_WSA || PLATFORM_STANDALONE
                 parts.Add(dataPath);
                 parts.Add("StreamingAssets");
 #elif UNITY_IOS
                 parts.Add(dataPath);
                 parts.Add("Raw");
 #elif UNITY_ANDROID
                 parts.Add("jar:file:/");
                 parts.Add(dataPath + "!");
                 parts.Add("assets");
 #endif
             }
             parts.Add(subPath);
             var path = parts.ToArray().Join();
             if (NetworkPathPattern.IsMatch(path))
             {
                 path = path.Replace('\\', '/');
             }
             return path;
         }
References Juniper.Unity.Data.StreamingAssets.NetworkPathPattern.
GetBytes() [1/4]
static void Juniper.Unity.Data.StreamingAssets.GetBytes (string cacheDirectory, string path, TimeSpan ttl, string mime, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Open a file as an array of bytes.
Parameters
path The full path to the file in question
ttl The maximum age after which to consider a cached file invalidated.
mime The mime type of the file, in case we have to request the file over the 'net.
resolve A callback to receive the file asynchronously.
reject A callback for when there is an error.
Returns
Progress tracking object
Definition at line 173 of file StreamingAssets.cs.
         {
             GetStream(cacheDirectory, path, ttl, mime, stream => resolve(stream.ReadBytes()), reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.GetStream().
Referenced by Juniper.Unity.Data.StreamingAssets.GetBytes().
GetBytes() [2/4]
static void Juniper.Unity.Data.StreamingAssets.GetBytes (string cacheDirectory, string path, TimeSpan ttl, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 178 of file StreamingAssets.cs.
         {
             GetBytes(cacheDirectory, path, ttl, "application/octet-stream", resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.GetBytes().
GetBytes() [3/4]
static void Juniper.Unity.Data.StreamingAssets.GetBytes (string cacheDirectory, string path, string mime, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 183 of file StreamingAssets.cs.
         {
             GetBytes(cacheDirectory, path, DEFAULT_TTL, mime, resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL, and Juniper.Unity.Data.StreamingAssets.GetBytes().
GetBytes() [4/4]
static void Juniper.Unity.Data.StreamingAssets.GetBytes (string cacheDirectory, string path, Action< byte[]> resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 188 of file StreamingAssets.cs.
         {
             GetBytes(cacheDirectory, path, DEFAULT_TTL, "application/octet-stream", resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL, and Juniper.Unity.Data.StreamingAssets.GetBytes().
GetCachedFile() [1/4]
static void Juniper.Unity.Data.StreamingAssets.GetCachedFile (string cacheDirectory, string path, TimeSpan ttl, string mime, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Open a file as an stream of bytes and save it to a cached location. On subsequent loads, open from the cached location.
Parameters
path The full path to the file in question
ttl The maximum age after which to consider a cached file invalidated.
mime The mime type of the file, in case we have to request the file over the 'net.
resolve A callback to receive the file stream asynchronously.
reject A callback for when there is an error.
Returns
Progress tracking object
Definition at line 63 of file StreamingAssets.cs.
         {
             prog?.SetProgress(0);
             Action<string> progResolve = (string resolvePath) =>
             {
                 prog?.SetProgress(1);
                 resolve(resolvePath);
             };
             try
             {
                 if (NetworkPathPattern.IsMatch(path))
                 {
                     var uri = new Uri(path);
                     GetOrCacheFile(
                         cacheDirectory,
                         uri.PathAndQuery,
                         ttl,
                         streamResolve => HTTP.GetStream(path, mime, streamResolve, reject, prog),
                         progResolve,
                         prog);
                 }
 #if UNITY_ANDROID
                 else if (AndroidJarPattern.IsMatch(path))
                 {
                     var match = AndroidJarPattern.Match(path);
                     var apk = match.Groups[1].Value;
                     path = match.Groups[2].Value;
                     GetOrCacheFile(
                         cacheDirectory,
                         path,
                         ttl,
                         streamResolve => Zip.GetFile(apk, path, streamResolve, reject, prog),
                         progResolve,
                         prog);
                 }
 #endif
                 else if (File.Exists(path))
                 {
                     progResolve(path);
                 }
                 else
                 {
                     throw new FileNotFoundException("Could not find file " + path, path);
                 }
             }
             catch (Exception exp)
             {
                 reject(exp);
             }
         }
References Juniper.Unity.Data.StreamingAssets.GetOrCacheFile(), Juniper.HTTP.GetStream(), and Juniper.Unity.Data.StreamingAssets.NetworkPathPattern.
Referenced by Juniper.Unity.Data.StreamingAssets.GetCachedFile(), and Juniper.Unity.Data.StreamingAssets.GetStream().
GetCachedFile() [2/4]
static void Juniper.Unity.Data.StreamingAssets.GetCachedFile (string cacheDirectory, string path, TimeSpan ttl, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 116 of file StreamingAssets.cs.
         {
             GetCachedFile(cacheDirectory, path, ttl, "application/octet-stream", resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.GetCachedFile().
GetCachedFile() [3/4]
static void Juniper.Unity.Data.StreamingAssets.GetCachedFile (string cacheDirectory, string path, string mime, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 121 of file StreamingAssets.cs.
         {
             GetCachedFile(cacheDirectory, path, DEFAULT_TTL, mime, resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL, and Juniper.Unity.Data.StreamingAssets.GetCachedFile().
GetCachedFile() [4/4]
static void Juniper.Unity.Data.StreamingAssets.GetCachedFile (string cacheDirectory, string path, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 126 of file StreamingAssets.cs.
         {
             GetCachedFile(cacheDirectory, path, DEFAULT_TTL, "application/octet-stream", resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL, and Juniper.Unity.Data.StreamingAssets.GetCachedFile().
GetJSONObject< T >() [1/2]
static void Juniper.Unity.Data.StreamingAssets.GetJSONObject< T > (string cacheDirectory, string path, TimeSpan ttl, Action< T > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Open a file as a deserialized JSON object.
Template Parameters
T The type of the object to deserialize to
Parameters
path The full path to the file in question
ttl The maximum age after which to consider a cached file invalidated.
mime The mime type of the file, in case we have to request the file over the 'net.
resolve A callback to receive the file asynchronously.
reject A callback for when there is an error.
Returns
Progress tracking object
Definition at line 226 of file StreamingAssets.cs.
         {
             GetStream(cacheDirectory, path, ttl, "application/json", stream => resolve(stream.ReadObject<T>()), reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.GetStream().
GetJSONObject< T >() [2/2]
static void Juniper.Unity.Data.StreamingAssets.GetJSONObject< T > (string cacheDirectory, string path, Action< T > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 231 of file StreamingAssets.cs.
         {
             GetJSONObject(cacheDirectory, path, DEFAULT_TTL, resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL.
GetOrCacheFile()
static void Juniper.Unity.Data.StreamingAssets.GetOrCacheFile (string cacheDirectory, string fileName, TimeSpan ttl, Action< Action< Stream >> getStreamResolver, Action< string > resolve, IProgressReceiver prog = null) inline static private
Definition at line 265 of file StreamingAssets.cs.
         {
             prog?.SetProgress(0);
             Action<string> progResolve = (string resolvePath) =>
             {
                 prog?.SetProgress(1);
                 resolve(resolvePath);
             };
             var cachePath = Uri.EscapeUriString(Path.Combine(cacheDirectory, fileName));
             if (FileIsGood(cachePath, ttl))
             {
                 progResolve(cachePath);
             }
             else
             {
                 var dir = Path.GetDirectoryName(cachePath);
                 getStreamResolver(stream =>
                 {
                     DirectoryExt.CreateDirectory(dir);
                     using (var file = new FileStream(cachePath, FileMode.Create))
                     {
                         stream.Pipe(file, prog);
                     }
                     progResolve(cachePath);
                 });
             }
         }
References System.IO.DirectoryExt.CreateDirectory(), and Juniper.Unity.Data.StreamingAssets.FileIsGood().
Referenced by Juniper.Unity.Data.StreamingAssets.GetCachedFile().
GetStream() [1/4]
static void Juniper.Unity.Data.StreamingAssets.GetStream (string cacheDirectory, string path, TimeSpan ttl, string mime, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Open a file as an stream of bytes.
Parameters
path The full path to the file in question
ttl The maximum age after which to consider a cached file invalidated.
mime The mime type of the file, in case we have to request the file over the 'net.
resolve A callback to receive the file stream asynchronously.
reject A callback for when there is an error.
Returns
Progress tracking object
Definition at line 142 of file StreamingAssets.cs.
         {
             GetCachedFile(cacheDirectory, path, ttl, mime, cachedPath => resolve(File.OpenRead(cachedPath)), reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.GetCachedFile().
Referenced by Juniper.Unity.Data.StreamingAssets.GetBytes(), Juniper.Unity.Data.StreamingAssets.GetJSONObject< T >(), Juniper.Unity.Data.StreamingAssets.GetStream(), and Juniper.Unity.Data.StreamingAssets.GetText().
GetStream() [2/4]
static void Juniper.Unity.Data.StreamingAssets.GetStream (string cacheDirectory, string path, TimeSpan ttl, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 147 of file StreamingAssets.cs.
         {
             GetStream(cacheDirectory, path, ttl, null, resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.GetStream().
GetStream() [3/4]
static void Juniper.Unity.Data.StreamingAssets.GetStream (string cacheDirectory, string path, string mime, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 152 of file StreamingAssets.cs.
         {
             GetStream(cacheDirectory, path, DEFAULT_TTL, mime, resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL, and Juniper.Unity.Data.StreamingAssets.GetStream().
GetStream() [4/4]
static void Juniper.Unity.Data.StreamingAssets.GetStream (string cacheDirectory, string path, Action< Stream > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 157 of file StreamingAssets.cs.
         {
             GetStream(cacheDirectory, path, DEFAULT_TTL, null, resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL, and Juniper.Unity.Data.StreamingAssets.GetStream().
GetText() [1/2]
static void Juniper.Unity.Data.StreamingAssets.GetText (string cacheDirectory, string path, TimeSpan ttl, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Open a file as a text string
Parameters
path The full path to the file in question
ttl The maximum age after which to consider a cached file invalidated.
mime The mime type of the file, in case we have to request the file over the 'net.
resolve A callback to receive the file asynchronously.
reject A callback for when there is an error.
Returns
Progress tracking object
Definition at line 204 of file StreamingAssets.cs.
         {
             GetStream(cacheDirectory, path, ttl, "text/plain", stream => resolve(stream.ReadString()), reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.GetStream().
Referenced by Juniper.Unity.Data.StreamingAssets.GetText().
GetText() [2/2]
static void Juniper.Unity.Data.StreamingAssets.GetText (string cacheDirectory, string path, Action< string > resolve, Action< Exception > reject, IProgressReceiver prog = null) inline static
Definition at line 209 of file StreamingAssets.cs.
         {
             GetText(cacheDirectory, path, DEFAULT_TTL, resolve, reject, prog);
         }
References Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL, and Juniper.Unity.Data.StreamingAssets.GetText().
Member Data Documentation
DEFAULT_TTL
TimeSpan Juniper.Unity.Data.StreamingAssets.DEFAULT_TTL = TimeSpan.Zero static
Definition at line 19 of file StreamingAssets.cs.
Referenced by Juniper.Unity.Data.StreamingAssets.GetBytes(), Juniper.Unity.Data.StreamingAssets.GetCachedFile(), Juniper.Unity.Data.StreamingAssets.GetJSONObject< T >(), Juniper.Unity.Data.StreamingAssets.GetStream(), and Juniper.Unity.Data.StreamingAssets.GetText().
NetworkPathPattern
readonly Regex Juniper.Unity.Data.StreamingAssets.NetworkPathPattern = new Regex(NetworkPathPatternStr, RegexOptions.Compiled) static private
Parse out the network path.
Definition at line 244 of file StreamingAssets.cs.
Referenced by Juniper.Unity.Data.StreamingAssets.FormatPath(), and Juniper.Unity.Data.StreamingAssets.GetCachedFile().
NetworkPathPatternStr
const string Juniper.Unity.Data.StreamingAssets.NetworkPathPatternStr = "^https?://" private
Parse out the network path.
Definition at line 239 of file StreamingAssets.cs.
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Data/StreamingAssets.cs