Juniper: Juniper.Widgets.MenuCollection Class Reference
Juniper.Widgets.MenuCollection Class Reference
Public Member Functions
void SetReturnMenuView (string nextView)
void ReturnToMainMenu ()
void ShowMenuView (string name)
override void Awake ()
void Start ()
override void Enter (IProgress prog)
Fire the OnEnable event and perform the Enter transition.
void SwitchToScene (string sceneName)
void ShowScene (string sceneName)
void ShowView (string viewName)
void Quit ()
void Enter ()
void Exit ()
virtual void Exit (IProgress prog)
Fire the OnExiting event and perform the Exit transition.
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
virtual void SkipExit ()
Task EnterAsync (IProgress prog=null)
Task ExitAsync (IProgress prog=null)
Public Attributes
string mainMenuView
bool unloadSceneOnExit = true
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
UnityEvent onStopped = new UnityEvent()
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Direction _curState
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
override void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void Complete ()
Finish the transition, whatever is going on.
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
virtual void OnStopped ()
Protected Attributes
bool skipEvents
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Properties
Direction State [get, private set]
virtual bool IsComplete [get]
Returns true when State is Direction.Stopped
bool IsEntering [get]
bool IsExiting [get]
bool CanExit [get]
bool CanEnter [get]
bool IsRunning [get]
Returns true when State is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
Events
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
EventHandler Stopped
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Private Member Functions
IEnumerator ShowMenuViewCoroutine (string name)
void AddView (MenuView view)
IEnumerator ExitingCouroutine ()
Private Attributes
readonly Dictionary< string, MenuView > views = new Dictionary<string, MenuView>()
string nextView
Detailed Description
Definition at line 11 of file MenuCollection.cs.
Member Function Documentation
AddView()
void Juniper.Widgets.MenuCollection.AddView (MenuView view) inline private
Definition at line 76 of file MenuCollection.cs.
         {
             views.Add(view.name, view);
         }
References Juniper.Widgets.MenuCollection.views.
Referenced by Juniper.Widgets.MenuCollection.Awake().
Awake()
override void Juniper.Widgets.MenuCollection.Awake () inline virtual
Reimplemented from Juniper.SubSceneController.
Definition at line 52 of file MenuCollection.cs.
         {
             base.Awake();
             nextView = mainMenuView;
             this.views.Clear();
             var views = GetComponentsInChildren<MenuView>(true);
             foreach (var view in views)
             {
                 AddView(view);
             }
         }
References Juniper.Widgets.MenuCollection.AddView(), Juniper.Widgets.MenuCollection.mainMenuView, Juniper.Widgets.MenuCollection.nextView, and Juniper.Widgets.MenuCollection.views.
Complete()
virtual void Juniper.AbstractStateController.Complete () inline protected virtual inherited
Finish the transition, whatever is going on.
Reimplemented in Juniper.Animation.AbstractTransitionController.
Definition at line 301 of file AbstractStateController.cs.
         {
             State = Direction.Stopped;
         }
References Juniper.AbstractStateController.State.
Referenced by Juniper.Widgets.MenuCollection.Enter(), Juniper.Widgets.MenuCollection.ExitingCouroutine(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.OnExiting(), Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SearchData(), Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), and Juniper.Widgets.MenuView.Trans_EnteredExited().
Enter() [1/2]
override void Juniper.Widgets.MenuCollection.Enter (IProgress prog) inline virtual
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.AbstractStateController.
Definition at line 81 of file MenuCollection.cs.
         {
             base.Enter(prog);
             prog.Report(1);
             Complete();
         }
References Juniper.AbstractStateController.Complete().
Enter() [2/2]
void Juniper.AbstractStateController.Enter () inline inherited
Definition at line 272 of file AbstractStateController.cs.
         {
             Enter(null);
         }
Referenced by Juniper.Widgets.MenuView.Enter(), Juniper.AbstractStateController.EnterAsync(), Juniper.Animation.FadeTransition.Fader(), Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.AbstractStateController.SkipEnter().
EnterAsync()
Task Juniper.AbstractStateController.EnterAsync (IProgress prog = null) inline inherited
Definition at line 331 of file AbstractStateController.cs.
         {
             return Stopper(Enter, prog);
         }
References Juniper.AbstractStateController.Enter(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Exit() [1/2]
void Juniper.AbstractStateController.Exit () inline inherited
Definition at line 285 of file AbstractStateController.cs.
         {
             Exit(null);
         }
Referenced by Juniper.Widgets.MenuView.Exit(), Juniper.AbstractStateController.ExitAsync(), Juniper.Animation.FadeTransition.Fader(), and Juniper.AbstractStateController.SkipExit().
Exit() [2/2]
virtual void Juniper.AbstractStateController.Exit (IProgress prog) inline virtual inherited
Fire the OnExiting event and perform the Exit transition.
Reimplemented in Juniper.Animation.AbstractTransitionController, and Juniper.Widgets.MenuView.
Definition at line 293 of file AbstractStateController.cs.
         {
             SetState(prog, Direction.Reverse);
         }
References Juniper.AbstractStateController.SetState().
ExitAsync()
Task Juniper.AbstractStateController.ExitAsync (IProgress prog = null) inline inherited
Definition at line 336 of file AbstractStateController.cs.
         {
             return Stopper(Exit, prog);
         }
References Juniper.AbstractStateController.Exit(), and Juniper.AbstractStateController.Stopper().
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), Juniper.MasterSceneController.RemoveSceneCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
ExitingCouroutine()
IEnumerator Juniper.Widgets.MenuCollection.ExitingCouroutine () inline private
Definition at line 100 of file MenuCollection.cs.
         {
             yield return ShowMenuViewCoroutine(null);
             Complete();
         }
References Juniper.AbstractStateController.Complete(), and Juniper.Widgets.MenuCollection.ShowMenuViewCoroutine().
Referenced by Juniper.Widgets.MenuCollection.OnExiting().
OnEntered()
override void Juniper.Widgets.MenuCollection.OnEntered () inline protected virtual
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented from Juniper.AbstractStateController.
Definition at line 88 of file MenuCollection.cs.
         {
             base.OnEntered();
             ShowMenuView(nextView);
         }
References Juniper.Widgets.MenuCollection.nextView, and Juniper.Widgets.MenuCollection.ShowMenuView().
OnEntering()
virtual void Juniper.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Animation.AbstractTransitionController, Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 360 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onEntering != null)
                 {
                     onEntering?.Invoke();
                 }
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entering, Juniper.AbstractStateController.onEntering, and Juniper.AbstractStateController.skipEvents.
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 417 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 if (onExited != null)
                 {
                     onExited.Invoke();
                 }
                 Exited?.Invoke(this, EventArgs.Empty);
             }
             enabled = false;
         }
References Juniper.AbstractStateController.Exited, Juniper.AbstractStateController.onExited, and Juniper.AbstractStateController.skipEvents.
OnExiting()
override void Juniper.Widgets.MenuCollection.OnExiting () inline protected virtual
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented from Juniper.AbstractStateController.
Definition at line 94 of file MenuCollection.cs.
         {
             base.OnExiting();
             this.Run(ExitingCouroutine());
         }
References Juniper.Widgets.MenuCollection.ExitingCouroutine().
OnStopped()
virtual void Juniper.AbstractStateController.OnStopped () inline protected virtual inherited
Definition at line 430 of file AbstractStateController.cs.
         {
             if (onStopped != null)
             {
                 onStopped?.Invoke();
             }
             Stopped?.Invoke(this, EventArgs.Empty);
         }
References Juniper.AbstractStateController.onStopped, and Juniper.AbstractStateController.Stopped.
Quit()
void Juniper.SubSceneController.Quit () inline inherited
Definition at line 38 of file SubSceneController.cs.
         {
             master.Quit();
         }
References Juniper.SubSceneController.master, and Juniper.MasterSceneController.Quit().
ReturnToMainMenu()
void Juniper.Widgets.MenuCollection.ReturnToMainMenu () inline
Definition at line 23 of file MenuCollection.cs.
         {
             SetReturnMenuView(mainMenuView);
             SwitchToScene(gameObject.scene.name);
         }
References Juniper.Widgets.MenuCollection.mainMenuView, Juniper.Widgets.MenuCollection.SetReturnMenuView(), and Juniper.SubSceneController.SwitchToScene().
SetReturnMenuView()
void Juniper.Widgets.MenuCollection.SetReturnMenuView (string nextView) inline
Definition at line 18 of file MenuCollection.cs.
         {
             this.nextView = nextView;
         }
References Juniper.Widgets.MenuCollection.nextView.
Referenced by Juniper.Widgets.MenuCollection.ReturnToMainMenu().
ShowMenuView()
void Juniper.Widgets.MenuCollection.ShowMenuView (string name) inline
Definition at line 29 of file MenuCollection.cs.
         {
             this.Run(ShowMenuViewCoroutine(name));
         }
References Juniper.Widgets.MenuCollection.ShowMenuViewCoroutine().
Referenced by Juniper.Widgets.MenuCollection.OnEntered().
ShowMenuViewCoroutine()
IEnumerator Juniper.Widgets.MenuCollection.ShowMenuViewCoroutine (string name) inline private
Definition at line 34 of file MenuCollection.cs.
         {
             foreach (var view in views)
             {
                 if (view.Key != name && view.Value.CanExit)
                 {
                     yield return view.Value.ExitAsync().AsCoroutine();
                     view.Value.Deactivate();
                 }
             }
             if (name != null)
             {
                 views[name].Activate();
                 yield return views[name].EnterAsync().AsCoroutine();
             }
         }
References Juniper.Widgets.MenuCollection.views.
Referenced by Juniper.Widgets.MenuCollection.ExitingCouroutine(), and Juniper.Widgets.MenuCollection.ShowMenuView().
ShowScene()
void Juniper.SubSceneController.ShowScene (string sceneName) inline inherited
Definition at line 28 of file SubSceneController.cs.
         {
             master.ShowScene(sceneName);
         }
References Juniper.SubSceneController.master, and Juniper.MasterSceneController.ShowScene().
ShowView()
void Juniper.SubSceneController.ShowView (string viewName) inline inherited
Definition at line 33 of file SubSceneController.cs.
         {
             master.ShowView(viewName);
         }
References Juniper.SubSceneController.master, and Juniper.MasterSceneController.ShowView().
SkipEnter()
virtual void Juniper.AbstractStateController.SkipEnter () inline virtual inherited
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 309 of file AbstractStateController.cs.
         {
             if (!IsEntered)
             {
                 skipEvents = true;
                 Enter();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.IsEntered, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.MasterSceneController.Start().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual inherited
Reimplemented in Juniper.Widgets.MenuView.
Definition at line 320 of file AbstractStateController.cs.
         {
             if (!IsExited)
             {
                 skipEvents = true;
                 Exit();
                 Complete();
                 skipEvents = false;
             }
         }
References Juniper.AbstractStateController.Complete(), Juniper.AbstractStateController.Exit(), Juniper.AbstractStateController.IsExited, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.Widgets.Tooltipable.Hide(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
Start()
void Juniper.Widgets.MenuCollection.Start () inline
Definition at line 67 of file MenuCollection.cs.
         {
             foreach (var view in views.Values)
             {
                 view.SkipExit();
                 view.Deactivate();
             }
         }
References Juniper.Widgets.MenuCollection.views.
SwitchToScene()
void Juniper.SubSceneController.SwitchToScene (string sceneName) inline inherited
Definition at line 23 of file SubSceneController.cs.
         {
             master.SwitchToScene(sceneName, !unloadSceneOnExit);
         }
References Juniper.SubSceneController.master, Juniper.MasterSceneController.SwitchToScene(), and Juniper.SubSceneController.unloadSceneOnExit.
Referenced by Juniper.Widgets.MenuCollection.ReturnToMainMenu().
Member Data Documentation
_curState
Direction Juniper.AbstractStateController._curState inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 117 of file AbstractStateController.cs.
mainMenuView
string Juniper.Widgets.MenuCollection.mainMenuView
Definition at line 15 of file MenuCollection.cs.
Referenced by Juniper.Widgets.MenuCollection.Awake(), and Juniper.Widgets.MenuCollection.ReturnToMainMenu().
nextView
string Juniper.Widgets.MenuCollection.nextView private
Definition at line 16 of file MenuCollection.cs.
Referenced by Juniper.Widgets.MenuCollection.Awake(), Juniper.Widgets.MenuCollection.OnEntered(), and Juniper.Widgets.MenuCollection.SetReturnMenuView().
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 38 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 29 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 56 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 47 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
onStopped
UnityEvent Juniper.AbstractStateController.onStopped = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 65 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped().
skipEvents
bool Juniper.AbstractStateController.skipEvents protected inherited
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Definition at line 166 of file AbstractStateController.cs.
Referenced by Juniper.Animation.AbstractTransitionController.Complete(), Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.AbstractTransitionController.Exit(), Juniper.AbstractStateController.OnEntered(), Juniper.AbstractStateController.OnEntering(), Juniper.AbstractStateController.OnExited(), Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.SkipEnter(), and Juniper.AbstractStateController.SkipExit().
unloadSceneOnExit
bool Juniper.SubSceneController.unloadSceneOnExit = true inherited
Definition at line 15 of file SubSceneController.cs.
Referenced by Juniper.SubSceneController.SwitchToScene().
views
readonly Dictionary<string, MenuView> Juniper.Widgets.MenuCollection.views = new Dictionary<string, MenuView>() private
Definition at line 13 of file MenuCollection.cs.
Referenced by Juniper.Widgets.MenuCollection.AddView(), Juniper.Widgets.MenuCollection.Awake(), Juniper.Widgets.MenuCollection.ShowMenuViewCoroutine(), and Juniper.Widgets.MenuCollection.Start().
Property Documentation
CanEnter
bool Juniper.AbstractStateController.CanEnter get inherited
Definition at line 204 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsEntered && !IsEntering;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.ShowTooltip(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
CanExit
bool Juniper.AbstractStateController.CanExit get inherited
Definition at line 196 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsExited && !IsExiting;
             }
         }
Referenced by Juniper.Widgets.Tooltipable.HideTooltipCoroutine(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get inherited
Returns true when State is Direction.Stopped
Definition at line 172 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Stopped;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntered
bool Juniper.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 226 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Forward;
             }
         }
Referenced by Juniper.AbstractStateController.SkipEnter(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Update().
IsEntering
bool Juniper.AbstractStateController.IsEntering get inherited
Definition at line 180 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Forward;
             }
         }
IsExited
bool Juniper.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 237 of file AbstractStateController.cs.
         {
             get
             {
                 return IsComplete && lastState == Direction.Reverse;
             }
         }
Referenced by Juniper.AbstractStateController.SkipExit(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
IsExiting
bool Juniper.AbstractStateController.IsExiting get inherited
Definition at line 188 of file AbstractStateController.cs.
         {
             get
             {
                 return State == Direction.Reverse;
             }
         }
IsRunning
bool Juniper.AbstractStateController.IsRunning get inherited
Returns true when State is not Direction.Stopped
Definition at line 215 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Animation.AbstractTransitionController.Update().
State
Direction Juniper.AbstractStateController.State get private set inherited
Definition at line 120 of file AbstractStateController.cs.
         {
             get
             {
                 return _curState;
             }
             private set
             {
                 lastState = _curState;
                 _curState = value;
                 if (State != lastState)
                 {
                     if (State == Direction.Forward)
                     {
                         OnEntering();
                     }
                     else if (State == Direction.Reverse)
                     {
                         OnExiting();
                     }
                     else
                     {
                         OnStopped();
                         if (lastState == Direction.Forward)
{
                             OnEntered();
                         }
                         else if (lastState == Direction.Reverse)
{
                             OnExited();
                         }
                     }
                 }
             }
         }
Referenced by Juniper.AbstractStateController.Complete(), Juniper.Animation.FadeTransition.FadeTransition_Enter_Exiting(), Juniper.Animation.AbstractTransitionController.SetProgress(), and Juniper.AbstractStateController.SetState().
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 83 of file AbstractStateController.cs.
Referenced by Juniper.Widgets.MenuView.Awake(), Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 74 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 101 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 92 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExiting().
Stopped
EventHandler Juniper.AbstractStateController.Stopped inherited
An event that occurs when the controller has finished going through the Enter or Exit transition. Prefer Stopped if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onStopped. If you are waiting for this event in a subclass of StateController, prefer overriding the OnStopped method.
Definition at line 110 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnStopped(), and Juniper.AbstractStateController.Stopper().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Widgets/MenuCollection.cs