Juniper: Juniper.IO.ProgressAggregator Class Reference
Juniper.IO.ProgressAggregator Class Reference
Public Member Functions
ProgressAggregator (IProgress parent, long numParts)
Split a progress tracker into numParts sub-trackers.
ProgressAggregator (IProgress parent, params string[] prefixes)
Split a progress tracker into sub-trackers with the provided prefixes, one per prefix.
void ReportWithStatus (float progress, string status)
Report progress to a listener implementation.
IEnumerator< IProgress > GetEnumerator ()
Public Attributes
float Progress => subProgs.Sum(p => p.Progress) / subProgs.Length
int Count => subProgs.Length
Properties
string Status [get, private set]
IProgress this[int index] [get]
Private Member Functions
ProgressAggregator (IProgress parent)
IEnumerator IEnumerable. GetEnumerator ()
Private Attributes
readonly ProgressSubdivision [] subProgs
readonly IProgress parent
Detailed Description
Definition at line 8 of file ProgressAggregator.cs.
Constructor & Destructor Documentation
ProgressAggregator() [1/3]
Juniper.IO.ProgressAggregator.ProgressAggregator (IProgress parent) inline private
Definition at line 15 of file ProgressAggregator.cs.
         {
             this.parent = parent;
         }
References Juniper.IO.ProgressAggregator.parent.
ProgressAggregator() [2/3]
Juniper.IO.ProgressAggregator.ProgressAggregator (IProgress parent, long numParts) inline
Split a progress tracker into numParts sub-trackers.
Parameters
parent
numParts
prefix
Returns
Definition at line 27 of file ProgressAggregator.cs.
             : this(parent)
         {
             if (numParts <= 0)
             {
                 throw new ArgumentException("Number of subdivisions must be at least 1.", nameof(numParts));
             }
             subProgs = new ProgressSubdivision[numParts];
             for (var i = 0; i < numParts; ++i)
             {
                 subProgs[i] = new ProgressSubdivision(this);
             }
         }
References Juniper.IO.ProgressAggregator.subProgs.
ProgressAggregator() [3/3]
Juniper.IO.ProgressAggregator.ProgressAggregator (IProgress parent, params string [] prefixes) inline
Split a progress tracker into sub-trackers with the provided prefixes, one per prefix.
Parameters
parent
prefixes
Returns
Definition at line 48 of file ProgressAggregator.cs.
             : this(parent)
         {
             if (prefixes.Length == 0)
             {
                 throw new ArgumentException("Must provide at least 1 prefix", nameof(prefixes));
             }
             subProgs = (from prefix in prefixes
                         select new ProgressSubdivision(this, prefix))
                        .ToArray();
         }
References Juniper.IO.ProgressAggregator.subProgs.
Member Function Documentation
GetEnumerator() [1/2]
IEnumerator<IProgress> Juniper.IO.ProgressAggregator.GetEnumerator () inline
Definition at line 81 of file ProgressAggregator.cs.
         {
             foreach (var prog in subProgs)
             {
                 yield return prog;
             }
         }
References Juniper.IO.ProgressAggregator.subProgs.
Referenced by Juniper.IO.ProgressAggregator.GetEnumerator().
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.IO.ProgressAggregator.GetEnumerator () inline private
Definition at line 89 of file ProgressAggregator.cs.
         {
             return GetEnumerator();
         }
References Juniper.IO.ProgressAggregator.GetEnumerator().
ReportWithStatus()
void Juniper.IO.ProgressAggregator.ReportWithStatus (float progress, string status) inline
Report progress to a listener implementation.
Parameters
progress
status
Implements Juniper.IO.IProgress.
Definition at line 75 of file ProgressAggregator.cs.
         {
             Status = status;
             parent?.ReportWithStatus(Progress, Status);
         }
References Juniper.IO.ProgressAggregator.parent, Juniper.IO.ProgressAggregator.Progress, Juniper.IO.IProgress.ReportWithStatus(), and Juniper.IO.ProgressAggregator.Status.
Member Data Documentation
Count
int Juniper.IO.ProgressAggregator.Count => subProgs.Length
Definition at line 65 of file ProgressAggregator.cs.
parent
readonly IProgress Juniper.IO.ProgressAggregator.parent private
Definition at line 13 of file ProgressAggregator.cs.
Referenced by Juniper.IO.ProgressAggregator.ProgressAggregator(), and Juniper.IO.ProgressAggregator.ReportWithStatus().
Progress
float Juniper.IO.ProgressAggregator.Progress => subProgs.Sum(p => p.Progress) / subProgs.Length
Definition at line 63 of file ProgressAggregator.cs.
Referenced by Juniper.IO.ProgressAggregator.ReportWithStatus().
subProgs
readonly ProgressSubdivision [] Juniper.IO.ProgressAggregator.subProgs private
Definition at line 12 of file ProgressAggregator.cs.
Referenced by Juniper.IO.ProgressAggregator.GetEnumerator(), and Juniper.IO.ProgressAggregator.ProgressAggregator().
Property Documentation
Status
string Juniper.IO.ProgressAggregator.Status get private set
Definition at line 61 of file ProgressAggregator.cs.
 { get; private set; }
Referenced by Juniper.IO.ProgressAggregator.ReportWithStatus().
this[int index]
IProgress Juniper.IO.ProgressAggregator.this[int index] get
Definition at line 68 of file ProgressAggregator.cs.
         {
             get
             {
                 return subProgs[index];
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/ProgressAggregator.cs