Juniper: Juniper.HTTP.Requester Class Reference
Juniper.HTTP.Requester Class Reference
Perform HTTP queries
Static Public Member Functions
static async Task< StreamResult > PostStream (string url, string userName, string password, Func< Stream, BodyInfo > writeBody, string acceptType, IProgress prog=null)
Perform a POST request, writing the body through a stream, and return the results as a stream.
static Task< StreamResult > PostStream (string url, string userName, string password, Func< Stream, BodyInfo > writeBody, IProgress prog=null)
Perform a POST request, writing the body through a stream, and return the results as a stream.
static Task< StreamResult > PostStream (string url, Func< Stream, BodyInfo > writeBody, string acceptType, IProgress prog=null)
Perform a POST request, writing the body through a stream, and return the results as a stream.
static Task< StreamResult > PostStream (string url, Func< Stream, BodyInfo > writeBody, IProgress prog=null)
Perform a POST request, writing the body through a stream, and return the results as a stream.
static async Task< StreamResult > GetStream (string url, string userName, string password, string acceptType, IProgress prog=null)
Perform a GET request and return the results as a stream of bytes
static Task< StreamResult > GetStream (string url, string userName, string password, IProgress prog=null)
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
static Task< StreamResult > GetStream (string url, string acceptType, IProgress prog=null)
Perform a GET request and return the results as a stream of bytes
static Task< StreamResult > GetStream (string url, IProgress prog=null)
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
Static Private Member Functions
static HttpWebRequest MakeRequest (string method, string url, string userName, string password, string acceptType)
Create the basic request object.
static async Task< StreamResult > HandleResponse (HttpWebRequest request, IProgress prog=null)
Reads the body from an HTTP response.
Detailed Description
Perform HTTP queries
Definition at line 13 of file HTTP.cs.
Member Function Documentation
GetStream() [1/4]
static async Task<StreamResult> Juniper.HTTP.Requester.GetStream (string url, string userName, string password, string acceptType, IProgress prog = null) inline static
Perform a GET request and return the results as a stream of bytes
Parameters
url The URL to request
acceptType The MIME of the expected response
resolve The callback to perform on success, with the HTTP status code and a stream payload
userName Basic HTTP authentication user name.
password Basic HTTP authentication user password.
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 155 of file HTTP.cs.
         {
             var request = MakeRequest("GET", url, userName, password, acceptType);
             return await HandleResponse(request, prog);
         }
References Juniper.HTTP.Requester.HandleResponse(), and Juniper.HTTP.Requester.MakeRequest().
Referenced by Juniper.Data.AbstractService.GetObject< ResponseT >(), Juniper.Unity.Data.StreamingAssets.GetStream(), Juniper.HTTP.Requester.GetStream(), and Juniper.World.Climate.OpenWeatherMap.API.Request().
GetStream() [2/4]
static Task<StreamResult> Juniper.HTTP.Requester.GetStream (string url, string userName, string password, IProgress prog = null) inline static
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
Parameters
url The URL to request
userName Basic HTTP authentication user name.
password Basic HTTP authentication user password.
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 170 of file HTTP.cs.
         {
             return GetStream(url, userName, password, "application/octet-stream", prog);
         }
References Juniper.HTTP.Requester.GetStream().
GetStream() [3/4]
static Task<StreamResult> Juniper.HTTP.Requester.GetStream (string url, string acceptType, IProgress prog = null) inline static
Perform a GET request and return the results as a stream of bytes
Parameters
url The URL to request
acceptType The MIME of the expected response
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 182 of file HTTP.cs.
         {
             return GetStream(url, null, null, acceptType, prog);
         }
References Juniper.HTTP.Requester.GetStream().
GetStream() [4/4]
static Task<StreamResult> Juniper.HTTP.Requester.GetStream (string url, IProgress prog = null) inline static
Perform a GET request and return the results as an array of bytes, for the application/unknown MIME type
Parameters
url The URL to request
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 194 of file HTTP.cs.
         {
             return GetStream(url, null, null, "application/octet-stream", prog);
         }
References Juniper.HTTP.Requester.GetStream().
HandleResponse()
static async Task<StreamResult> Juniper.HTTP.Requester.HandleResponse (HttpWebRequest request, IProgress prog = null) inline static private
Reads the body from an HTTP response.
Parameters
request The request that initiated the response
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 52 of file HTTP.cs.
         {
             using (var response = (HttpWebResponse)await request.GetResponseAsync())
             {
                 if (response.ContentLength == 0)
                 {
                     return new StreamResult(
                         response.StatusCode,
                         null,
                         null);
                 }
                 else
                 {
                     return new StreamResult(
                         response.StatusCode,
                         response.ContentType,
                         new ProgressStream(response.GetResponseStream(), response.ContentLength, prog));
                 }
             }
         }
Referenced by Juniper.HTTP.Requester.GetStream(), and Juniper.HTTP.Requester.PostStream().
MakeRequest()
static HttpWebRequest Juniper.HTTP.Requester.MakeRequest (string method, string url, string userName, string password, string acceptType) inline static private
Create the basic request object.
Parameters
method GET/PUT/POST/etc.
url
userName Basic HTTP authentication user name.
password Basic HTTP authentication user password.
acceptType The MIME type of the expected response.
Returns
A web request object
Definition at line 24 of file HTTP.cs.
         {
             var request = (HttpWebRequest)WebRequest.Create(url);
             request.Method = method;
             if (!string.IsNullOrEmpty(userName) && !string.IsNullOrEmpty(password))
             {
                 var authPair = userName + ":" + password;
                 var authBytes = Encoding.UTF8.GetBytes(authPair);
                 var auth64 = Convert.ToBase64String(authBytes);
                 request.Headers.Add("Authorization", "Basic " + auth64);
             }
             if (!string.IsNullOrEmpty(acceptType))
             {
                 request.Accept = acceptType;
             }
             return request;
         }
Referenced by Juniper.HTTP.Requester.GetStream(), and Juniper.HTTP.Requester.PostStream().
PostStream() [1/4]
static async Task<StreamResult> Juniper.HTTP.Requester.PostStream (string url, string userName, string password, Func< Stream, BodyInfo > writeBody, string acceptType, IProgress prog = null) inline static
Perform a POST request, writing the body through a stream, and return the results as a stream.
Parameters
url The URL to request
userName Basic HTTP authentication user name.
password Basic HTTP authentication user password.
writeBody A callback function for writing the body to a stream
acceptType The MIME of the expected response
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 83 of file HTTP.cs.
         {
             var request = MakeRequest("POST", url, userName, password, acceptType);
             using (var stream = await request.GetRequestStreamAsync())
             {
                 var contentInfo = writeBody(stream);
                 if (contentInfo.Length > 0)
                 {
                     request.ContentLength = contentInfo.Length;
                     if (!string.IsNullOrEmpty(contentInfo.MIMEType))
                     {
                         request.ContentType = contentInfo.MIMEType;
                     }
                 }
             }
             return await HandleResponse(request, prog);
         }
References Juniper.HTTP.Requester.HandleResponse(), and Juniper.HTTP.Requester.MakeRequest().
Referenced by Juniper.Data.AbstractService.PostObject< ResponseT, BodyT >(), and Juniper.HTTP.Requester.PostStream().
PostStream() [2/4]
static Task<StreamResult> Juniper.HTTP.Requester.PostStream (string url, string userName, string password, Func< Stream, BodyInfo > writeBody, IProgress prog = null) inline static
Perform a POST request, writing the body through a stream, and return the results as a stream.
Parameters
url The URL to request
userName Basic HTTP authentication user name.
password Basic HTTP authentication user password.
writeBody A callback function for writing the body to a stream
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 113 of file HTTP.cs.
         {
             return PostStream(url, userName, password, writeBody, "application/octet-stream", prog);
         }
References Juniper.HTTP.Requester.PostStream().
PostStream() [3/4]
static Task<StreamResult> Juniper.HTTP.Requester.PostStream (string url, Func< Stream, BodyInfo > writeBody, string acceptType, IProgress prog = null) inline static
Perform a POST request, writing the body through a stream, and return the results as a stream.
Parameters
url The URL to request
writeBody A callback function for writing the body to a stream
acceptType The MIME of the expected response
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 126 of file HTTP.cs.
         {
             return PostStream(url, null, null, writeBody, acceptType, prog);
         }
References Juniper.HTTP.Requester.PostStream().
PostStream() [4/4]
static Task<StreamResult> Juniper.HTTP.Requester.PostStream (string url, Func< Stream, BodyInfo > writeBody, IProgress prog = null) inline static
Perform a POST request, writing the body through a stream, and return the results as a stream.
Parameters
url The URL to request
contentLength The total length of the body that needs to be written
contentType The MIME type of both the request and response body
writeBody A callback function for writing the body to a stream
prog Progress tracker (defaults to no progress tracking)
Returns
A stream that contains the response body, and an HTTP status code
Definition at line 140 of file HTTP.cs.
         {
             return PostStream(url, null, null, writeBody, "application/octet-stream", prog);
         }
References Juniper.HTTP.Requester.PostStream().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.HTTP/HTTP.cs