Juniper: Juniper.Unity.ImageTracking.TrackableFoundEventHandler Class Reference
Juniper.Unity.ImageTracking.TrackableFoundEventHandler Class Reference
Trackable object–like images, scanned objects, and model generated targets– come and go out of the user's view. This component manages events around those target apperances, abstracting away platform details.
Public Member Functions
void OnValidate ()
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
void OnEnable ()
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
void Update ()
Checks the tracking status of the target and fires any appropriate change/found/lost events.
void ForceFound ()
Forces the onFound event to fire.
void ForceLost ()
Forces the onLost event to fire.
void OnDisable ()
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
void Awake ()
Registers for Vuforia's trackable event handlers.
void OnTrackableStateChanged (TrackableBehaviour.Status previousStatus, TrackableBehaviour.Status newStatus)
Updates the tracking state of the target when Unity's OnTrackableStateChange event is fired.
Public Attributes
ARReferenceImagesSet imagesSet
The ARKit set of tracked images
ARReferenceImage image
One of the images from an ARKit set of tracked images.
bool Found
This value is set to true when the target has been found.
bool Safe = true
This value is set to true when the user is at a safe distance from the target.
bool Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Transform attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
float safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
bool DebugReport
Set to true to make the update loop print a debug report.
BooleanEvent onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
UnityEvent onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
UnityEvent onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
UnityEvent onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
UnityEvent onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Events
EventHandler< TrackingStateChangeEventArgs > TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Private Member Functions
void PrintDebugReport ()
If DebugReport is set to true, prints a report on the status of tracking.
void SafetyCheck ()
Check to see if the user is standing at a comfortable distance from the object.
void OnSafeOrProximity ()
If the value of Safe has changed, fires the onSafe or onProximity event.
void OnFoundChanged ()
If the value of Found has changed, records the time at which the object was found, sets the visibility of the object, and fires the onFound, onLost, onTrackingStateChange, or the TrackingStateChange events.
void OnLostOrFound ()
Fires the onLost or onFound events.
void OnTrackingStateChanged ()
Firest the onTrackingStateChange and TrackingStateChange events.
void OnDestroy ()
When running on Vuforia, de-registers the listeners for Vuforia's tracking state changed events.
Private Attributes
TrackableBehaviour trackable
The Vuforia tracked object.
bool? wasFound
Whether or not Found was set on the previous frame, to make it easier to detect changes to it.
bool wasSafe = true
Whether or not Safe was set on the previou frame.
const string TAG_NAME = "Tracked Object Attachment Point"
The tag that the attachment point is expected to have.
const string TRANSFORM_NAME = "Attachment Point"
The name that the attachment point is expected to have.
Detailed Description
Trackable object–like images, scanned objects, and model generated targets– come and go out of the user's view. This component manages events around those target apperances, abstracting away platform details.
Definition at line 24 of file TrackableFoundEventHandler.cs.
Member Function Documentation
Awake()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Awake () inline
Registers for Vuforia's trackable event handlers.
Definition at line 315 of file TrackableFoundEventHandler.cs.
         {
 #if VUFORIA
             trackable = GetComponentInChildren<TrackableBehaviour>();
             trackable.RegisterTrackableEventHandler(this);
 #endif
             var keeper = ComponentExt.FindAny<TrackerKeeper>();
             keeper?.Register(this);
         }
References Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.trackable.
ForceFound()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceFound () inline
Forces the onFound event to fire.
Definition at line 284 of file TrackableFoundEventHandler.cs.
         {
             wasFound = false;
             Found = true;
             Extended = false;
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasFound.
ForceLost()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceLost () inline
Forces the onLost event to fire.
Definition at line 295 of file TrackableFoundEventHandler.cs.
         {
             wasFound = true;
             Found = false;
             Extended = false;
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasFound.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnDisable().
OnDestroy()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnDestroy () inline private
When running on Vuforia, de-registers the listeners for Vuforia's tracking state changed events.
Definition at line 330 of file TrackableFoundEventHandler.cs.
         {
             trackable.UnregisterTrackableEventHandler(this);
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.trackable.
OnDisable()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnDisable () inline
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
Definition at line 306 of file TrackableFoundEventHandler.cs.
         {
             ForceLost();
             Update();
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceLost(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Update().
OnEnable()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnEnable () inline
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
Definition at line 156 of file TrackableFoundEventHandler.cs.
         {
             wasSafe = Safe = true;
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Safe, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasSafe.
OnFoundChanged()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnFoundChanged () inline private
If the value of Found has changed, records the time at which the object was found, sets the visibility of the object, and fires the onFound, onLost, onTrackingStateChange, or the TrackingStateChange events.
Definition at line 242 of file TrackableFoundEventHandler.cs.
         {
             if (Found != wasFound)
             {
                 this.SetVisible(Found);
                 OnTrackingStateChanged();
                 OnLostOrFound();
                 wasFound = Found;
             }
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnLostOrFound(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackingStateChanged(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasFound.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Update().
OnLostOrFound()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnLostOrFound () inline private
Fires the onLost or onFound events.
Definition at line 256 of file TrackableFoundEventHandler.cs.
         {
             if (wasFound != null)
             {
                 if (Found)
                 {
                     onFound?.Invoke();
                 }
                 else
                 {
                     onLost?.Invoke();
                 }
             }
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onFound, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onLost, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasFound.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnFoundChanged().
OnSafeOrProximity()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnSafeOrProximity () inline private
If the value of Safe has changed, fires the onSafe or onProximity event.
Definition at line 219 of file TrackableFoundEventHandler.cs.
         {
             if (Safe != wasSafe)
             {
                 if (Safe)
                 {
                     onSafe?.Invoke();
                 }
                 else
                 {
                     onProximity?.Invoke();
                 }
                 wasSafe = Safe;
             }
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onProximity, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onSafe, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Safe, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasSafe.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.SafetyCheck().
OnTrackableStateChanged()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackableStateChanged (TrackableBehaviour.Status previousStatus, TrackableBehaviour.Status newStatus) inline
Updates the tracking state of the target when Unity's OnTrackableStateChange event is fired.
Parameters
previousStatus Previous status.
newStatus New status.
Definition at line 340 of file TrackableFoundEventHandler.cs.
         {
             if (DebugReport)
             {
                 ScreenDebugger.Print("[{0}] {1} => {2}", trackable.TrackableName, previousStatus, newStatus);
             }
             Extended = trackable.CurrentStatus == TrackableBehaviour.Status.EXTENDED_TRACKED;
             Found = trackable.CurrentStatus == TrackableBehaviour.Status.DETECTED
                 || trackable.CurrentStatus == TrackableBehaviour.Status.TRACKED
                 || Extended;
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.DebugReport, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, System.ScreenDebugger.Print(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.trackable.
OnTrackingStateChanged()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackingStateChanged () inline private
Firest the onTrackingStateChange and TrackingStateChange events.
Definition at line 274 of file TrackableFoundEventHandler.cs.
         {
             onTrackingStateChange?.Invoke(Found);
             TrackingStateChange?.Invoke(this, new TrackingStateChangeEventArgs(this, Found));
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onTrackingStateChange, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.TrackingStateChange.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnFoundChanged().
OnValidate()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnValidate () inline
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
Definition at line 140 of file TrackableFoundEventHandler.cs.
         {
             if (attachmentPoint == null)
             {
                 attachmentPoint = transform.Children().FirstOrDefault(t =>
                     t.tag == TAG_NAME)
                                            ?? transform.Children().FirstOrDefault(t =>
                                                t.name == TRANSFORM_NAME)
                                            ?? transform;
             }
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.attachmentPoint, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.TAG_NAME, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.TRANSFORM_NAME.
PrintDebugReport()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.PrintDebugReport () inline private
If DebugReport is set to true, prints a report on the status of tracking.
Definition at line 177 of file TrackableFoundEventHandler.cs.
         {
             if (DebugReport)
             {
 #if VUFORIA
                 if (trackable == null)
                 {
                     ScreenDebugger.Print("[{0}] No trackable object!", name);
                 }
                 else
                 {
                     ScreenDebugger.Print("[{0}] {1} -> {2}", name, trackable.TrackableName, Extended ? "extended" : Found ? "FOUND" : "");
                 }
 #endif
             }
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.DebugReport, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Extended, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, System.ScreenDebugger.Print(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.trackable.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Update().
SafetyCheck()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.SafetyCheck () inline private
Check to see if the user is standing at a comfortable distance from the object.
Definition at line 197 of file TrackableFoundEventHandler.cs.
         {
             if (Found)
             {
                 var camT = DisplayManager.MainCamera.transform;
                 var delta = transform.position - camT.position;
                 // we only care about the over-ground distance.
                 delta.y = 0;
                 //Add 10% to the safe distance to return to safety so we don't jitter
                 // over the edge.
                 Safe = Safe && delta.magnitude >= safeDistance
                     || !Safe && delta.magnitude >= safeDistance * 1.1f;
                 OnSafeOrProximity();
             }
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found, Juniper.Unity.Display.AbstractDisplayManager.MainCamera, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnSafeOrProximity(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Safe, and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.safeDistance.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Update().
Update()
void Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Update () inline
Checks the tracking status of the target and fires any appropriate change/found/lost events.
Definition at line 164 of file TrackableFoundEventHandler.cs.
         {
             OnFoundChanged();
             SafetyCheck();
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.Unity.ImageTracking.TrackableFoundEventHandler.DebugReport, Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnFoundChanged(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.PrintDebugReport(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.SafetyCheck().
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnDisable().
Member Data Documentation
attachmentPoint
Transform Juniper.Unity.ImageTracking.TrackableFoundEventHandler.attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
Definition at line 79 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnValidate().
DebugReport
bool Juniper.Unity.ImageTracking.TrackableFoundEventHandler.DebugReport
Set to true to make the update loop print a debug report.
Definition at line 89 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackableStateChanged(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.PrintDebugReport(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Update().
Extended
bool Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Definition at line 73 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceFound(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceLost(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackableStateChanged(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.PrintDebugReport().
Found
bool Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Found
This value is set to true when the target has been found.
Definition at line 51 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceFound(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceLost(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnFoundChanged(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnLostOrFound(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackableStateChanged(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackingStateChanged(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.PrintDebugReport(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.SafetyCheck(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.TargetFinder().
image
ARReferenceImage Juniper.Unity.ImageTracking.TrackableFoundEventHandler.image
One of the images from an ARKit set of tracked images.
Definition at line 45 of file TrackableFoundEventHandler.cs.
imagesSet
ARReferenceImagesSet Juniper.Unity.ImageTracking.TrackableFoundEventHandler.imagesSet
The ARKit set of tracked images
Definition at line 40 of file TrackableFoundEventHandler.cs.
onFound
UnityEvent Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
Definition at line 108 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnLostOrFound(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onLost
UnityEvent Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
Definition at line 113 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnLostOrFound(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onProximity
UnityEvent Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
Definition at line 118 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onSafe
UnityEvent Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Definition at line 123 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Register().
onTrackingStateChange
BooleanEvent Juniper.Unity.ImageTracking.TrackableFoundEventHandler.onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
Definition at line 96 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackingStateChanged().
Safe
bool Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Safe = true
This value is set to true when the user is at a safe distance from the target.
Definition at line 62 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnEnable(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.SafetyCheck().
safeDistance
float Juniper.Unity.ImageTracking.TrackableFoundEventHandler.safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
Definition at line 84 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.SafetyCheck().
TAG_NAME
const string Juniper.Unity.ImageTracking.TrackableFoundEventHandler.TAG_NAME = "Tracked Object Attachment Point" private
The tag that the attachment point is expected to have.
Definition at line 128 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnValidate().
trackable
TrackableBehaviour Juniper.Unity.ImageTracking.TrackableFoundEventHandler.trackable private
The Vuforia tracked object.
Definition at line 33 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.Awake(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnDestroy(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackableStateChanged(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.PrintDebugReport().
TRANSFORM_NAME
const string Juniper.Unity.ImageTracking.TrackableFoundEventHandler.TRANSFORM_NAME = "Attachment Point" private
The name that the attachment point is expected to have.
Definition at line 133 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnValidate().
wasFound
bool? Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasFound private
Whether or not Found was set on the previous frame, to make it easier to detect changes to it.
Definition at line 57 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceFound(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.ForceLost(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnFoundChanged(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnLostOrFound().
wasSafe
bool Juniper.Unity.ImageTracking.TrackableFoundEventHandler.wasSafe = true private
Whether or not Safe was set on the previou frame.
Definition at line 67 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnEnable(), and Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnSafeOrProximity().
Event Documentation
TrackingStateChange
EventHandler<TrackingStateChangeEventArgs> Juniper.Unity.ImageTracking.TrackableFoundEventHandler.TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Definition at line 103 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.Unity.ImageTracking.TrackableFoundEventHandler.OnTrackingStateChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/ImageTracking/TrackableFoundEventHandler.cs