Juniper: Juniper.IO.AbstractStreamSource Class Reference
Juniper.IO.AbstractStreamSource Class Reference abstract
Public Member Functions
abstract Task< Stream > GetStreamAsync (IProgress prog=null)
bool Equals (ContentReference other)
override bool Equals (object obj)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static bool operator== (ContentReference left, ContentReference right)
static bool operator != (ContentReference left, ContentReference right)
static operator string (ContentReference fileRef)
static FileInfo operator+ (DirectoryInfo directory, ContentReference fileRef)
static FileInfo operator+ (ContentReference fileRef, DirectoryInfo directory)
Public Attributes
sealed override string CacheID
sealed override bool DoNotCache
Protected Member Functions
AbstractStreamSource (MediaType contentType)
AbstractStreamSource (string cacheID, MediaType contentType)
Properties
abstract string InternalCacheID [get]
virtual MediaType ContentType [get]
string FileName [get]
Detailed Description
Definition at line 6 of file AbstractStreamSource.cs.
Constructor & Destructor Documentation
AbstractStreamSource() [1/2]
Juniper.IO.AbstractStreamSource.AbstractStreamSource (MediaType contentType) inline protected
Definition at line 8 of file AbstractStreamSource.cs.
             : base(contentType)
         { }
AbstractStreamSource() [2/2]
Juniper.IO.AbstractStreamSource.AbstractStreamSource (string cacheID, MediaType contentType) inline protected
Definition at line 12 of file AbstractStreamSource.cs.
             : base(cacheID, contentType)
         { }
Member Function Documentation
Equals() [1/2]
bool Juniper.IO.ContentReference.Equals (ContentReference other) inline inherited
Definition at line 78 of file ContentReference.cs.
         {
             return other is object
                 && other.ContentType == ContentType
                 && other.CacheID == CacheID;
         }
References Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
Referenced by Juniper.IO.ContentReference.Equals().
Equals() [2/2]
override bool Juniper.IO.ContentReference.Equals (object obj) inline inherited
Definition at line 85 of file ContentReference.cs.
         {
             return obj is ContentReference other
                 && Equals(other);
         }
References Juniper.IO.ContentReference.Equals().
GetHashCode()
override int Juniper.IO.ContentReference.GetHashCode () inline inherited
Definition at line 114 of file ContentReference.cs.
         {
             var hashCode = -1239926094;
             hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(CacheID);
             hashCode = hashCode * -1521134295 + EqualityComparer<MediaType>.Default.GetHashCode(ContentType);
             return hashCode;
         }
References Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
GetStreamAsync()
abstract Task<Stream> Juniper.IO.AbstractStreamSource.GetStreamAsync (IProgress prog = null) pure virtual
Implemented in Juniper.HTTP.REST.AbstractRequest< MediaTypeT >.
Referenced by Juniper.IO.StreamSourceExt.DecodeAsync< ResultT >(), Juniper.IO.StreamSourceExt.GetStreamAsync(), and Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync().
operator !=()
static bool Juniper.IO.ContentReference.operator != (ContentReference left, ContentReference right) inline static inherited
Definition at line 16 of file ContentReference.cs.
         {
             return !(left == right);
         }
operator string()
static Juniper.IO.ContentReference.operator string (ContentReference fileRef) inline explicit static inherited
Definition at line 21 of file ContentReference.cs.
         {
             if (fileRef is null)
             {
                 return null;
             }
             return fileRef.ContentType.AddExtension(fileRef.CacheID);
         }
References Juniper.MediaType.AddExtension(), Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
operator+() [1/2]
static FileInfo Juniper.IO.ContentReference.operator+ (DirectoryInfo directory, ContentReference fileRef) inline static inherited
Definition at line 31 of file ContentReference.cs.
         {
             if (directory is null)
             {
                 return null;
             }
             if (fileRef is null)
             {
                 return null;
             }
             var fileName = (string)fileRef;
             return new FileInfo(Path.Combine(directory.FullName, fileName));
         }
operator+() [2/2]
static FileInfo Juniper.IO.ContentReference.operator+ (ContentReference fileRef, DirectoryInfo directory) inline static inherited
Definition at line 47 of file ContentReference.cs.
         {
             return directory + fileRef;
         }
operator==()
static bool Juniper.IO.ContentReference.operator== (ContentReference left, ContentReference right) inline static inherited
Definition at line 10 of file ContentReference.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
ToString()
override string Juniper.IO.ContentReference.ToString () inline inherited
Definition at line 91 of file ContentReference.cs.
         {
             return string.Format(CultureInfo.InvariantCulture, "{0} ({1})", CacheID, ContentType);
         }
References Juniper.IO.ContentReference.CacheID, and Juniper.IO.ContentReference.ContentType.
Referenced by Juniper.IO.FileCacheLayer.Create(), Juniper.IO.MemoryCacheLayer.GetStreamAsync(), and Juniper.IO.FileCacheLayer.GetStreamAsync().
Member Data Documentation
CacheID
sealed override string Juniper.IO.AbstractStreamSource.CacheID
Initial value:
=>
            InternalCacheID
Definition at line 16 of file AbstractStreamSource.cs.
Referenced by Juniper.HTTP.REST.AbstractRequest< MediaType >.Equals(), and Juniper.HTTP.REST.AbstractRequest< MediaType >.GetHashCode().
DoNotCache
sealed override bool Juniper.IO.AbstractStreamSource.DoNotCache
Initial value:
=>
            CacheID is null
Definition at line 19 of file AbstractStreamSource.cs.
Property Documentation
ContentType
virtual MediaType Juniper.IO.ContentReference.ContentType get inherited
Definition at line 69 of file ContentReference.cs.
         {
             get;
         }
Referenced by Juniper.IO.ContentReference.ContentReference(), Juniper.IO.MemoryCacheLayer.Create(), Juniper.IO.MemoryCacheLayer.Delete(), Juniper.IO.ContentReference.Equals(), Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), Juniper.IO.ContentReference.GetHashCode(), Juniper.IO.MemoryCacheLayer.GetStreamAsync(), Juniper.IO.MemoryCacheLayer.IsCached(), Juniper.IO.ContentReference.operator string(), Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync(), and Juniper.IO.ContentReference.ToString().
FileName
string Juniper.IO.ContentReference.FileName get inherited
Definition at line 97 of file ContentReference.cs.
         {
             get
             {
                 var nameStub = CacheID;
                 var fileStub = new FileInfo(nameStub);
                 nameStub = fileStub.Name;
                 if (ContentType.PrimaryExtension is object)
                 {
                     return $"{nameStub}.{ContentType.PrimaryExtension}";
                 }
                 else
                 {
                     return nameStub;
                 }
             }
         }
Referenced by Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync().
InternalCacheID
abstract string Juniper.IO.AbstractStreamSource.InternalCacheID get protected
Definition at line 22 of file AbstractStreamSource.cs.
 { get; }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/AbstractStreamSource.cs