Juniper: BitMiracle.LibJpeg.BitmapDestination Class Reference
BitMiracle.LibJpeg.BitmapDestination Class Reference
Public Member Functions
BitmapDestination (Stream output)
void SetImageAttributes (LoadedImageAttributes parameters)
Implementor of this interface should process image properties received from decompressor.
void BeginWrite ()
Startup: normally writes the file header. In this module we may as well postpone everything until finish_output.
void ProcessPixelsRow (byte[] row)
Write some pixel data.
void EndWrite ()
Finish up at the end of the file. Here is where we really output the BMP file.
Properties
Stream Output [get]
Private Member Functions
void PutGrayRow (byte[] row)
This version is for grayscale OR quantized color output
void PutRgbRow (byte[] row)
This version is for writing 24-bit pixels
void PutCmykRow (byte[] row)
This version is for writing 24-bit pixels
void WriteHeader ()
Write a Windows-style BMP file header, including colormap if needed
byte [] CreateBitmapInfoHeader (int bits_per_pixel, int cmap_entries)
void FillBitmapInfoHeader (int bitsPerPixel, int cmap_entries, byte[] infoHeader)
byte [] CreateBitmapV4InfoHeader (int bitsPerPixel)
void WriteColormap (int map_colors, int map_entry_size)
Write the colormap. Windows uses BGR0 map entries; OS/2 uses BGR entries.
void WritePixels ()
Static Private Member Functions
static byte [] CreateBitmapFileHeader (int offsetToPixels, int fileSize)
static void PUT_2B (byte[] array, int offset, int value)
static void PUT_4B (byte[] array, int offset, int value)
Private Attributes
byte [][] m_pixels
int m_rowWidth
int m_currentRow
LoadedImageAttributes m_parameters
Detailed Description
Definition at line 8 of file BitmapDestination.cs.
Constructor & Destructor Documentation
BitmapDestination()
BitMiracle.LibJpeg.BitmapDestination.BitmapDestination (Stream output) inline
Definition at line 17 of file BitmapDestination.cs.
         {
             Output = output;
         }
References BitMiracle.LibJpeg.BitmapDestination.Output.
Member Function Documentation
BeginWrite()
void BitMiracle.LibJpeg.BitmapDestination.BeginWrite () inline
Startup: normally writes the file header. In this module we may as well postpone everything until finish_output.
Implements BitMiracle.LibJpeg.IDecompressDestination.
Definition at line 33 of file BitmapDestination.cs.
         {
             //Determine width of rows in the BMP file (padded to 4-byte boundary).
             m_rowWidth = m_parameters.Width * m_parameters.Components;
             while (m_rowWidth % 4 != 0)
             {
                 m_rowWidth++;
             }
             m_pixels = new byte[m_rowWidth][];
             for (var i = 0; i < m_rowWidth; i++)
             {
                 m_pixels[i] = new byte[m_parameters.Height];
             }
             m_currentRow = 0;
         }
References BitMiracle.LibJpeg.LoadedImageAttributes.Components, BitMiracle.LibJpeg.LoadedImageAttributes.Height, BitMiracle.LibJpeg.BitmapDestination.m_currentRow, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.m_pixels, BitMiracle.LibJpeg.BitmapDestination.m_rowWidth, and BitMiracle.LibJpeg.LoadedImageAttributes.Width.
CreateBitmapFileHeader()
static byte [] BitMiracle.LibJpeg.BitmapDestination.CreateBitmapFileHeader (int offsetToPixels, int fileSize) inline static private
Definition at line 194 of file BitmapDestination.cs.
         {
             var bmpfileheader = new byte[14];
             bmpfileheader[0] = 0x42;    /* first 2 bytes are ASCII 'B', 'M' */
             bmpfileheader[1] = 0x4D;
             PUT_4B(bmpfileheader, 2, fileSize);
             /* we leave bfReserved1 & bfReserved2 = 0 */
             PUT_4B(bmpfileheader, 10, offsetToPixels); /* bfOffBits */
             return bmpfileheader;
         }
References BitMiracle.LibJpeg.BitmapDestination.PUT_4B().
Referenced by BitMiracle.LibJpeg.BitmapDestination.WriteHeader().
CreateBitmapInfoHeader()
byte [] BitMiracle.LibJpeg.BitmapDestination.CreateBitmapInfoHeader (int bits_per_pixel, int cmap_entries) inline private
Definition at line 205 of file BitmapDestination.cs.
         {
             var bmpinfoheader = new byte[40];
             FillBitmapInfoHeader(bits_per_pixel, cmap_entries, bmpinfoheader);
             return bmpinfoheader;
         }
References BitMiracle.LibJpeg.BitmapDestination.FillBitmapInfoHeader().
Referenced by BitMiracle.LibJpeg.BitmapDestination.WriteHeader().
CreateBitmapV4InfoHeader()
byte [] BitMiracle.LibJpeg.BitmapDestination.CreateBitmapV4InfoHeader (int bitsPerPixel) inline private
Definition at line 234 of file BitmapDestination.cs.
         {
             var infoHeader = new byte[40 + 68];
             FillBitmapInfoHeader(bitsPerPixel, 0, infoHeader);
             PUT_4B(infoHeader, 56, 0x02); /* CSType == 0x02 (CMYK) */
             return infoHeader;
         }
References BitMiracle.LibJpeg.BitmapDestination.FillBitmapInfoHeader(), and BitMiracle.LibJpeg.BitmapDestination.PUT_4B().
Referenced by BitMiracle.LibJpeg.BitmapDestination.WriteHeader().
EndWrite()
void BitMiracle.LibJpeg.BitmapDestination.EndWrite () inline
Finish up at the end of the file. Here is where we really output the BMP file.
Implements BitMiracle.LibJpeg.IDecompressDestination.
Definition at line 76 of file BitmapDestination.cs.
         {
             WriteHeader();
             WritePixels();
             /* Make sure we wrote the output file OK */
             Output.Flush();
         }
References BitMiracle.LibJpeg.BitmapDestination.Output, BitMiracle.LibJpeg.BitmapDestination.WriteHeader(), and BitMiracle.LibJpeg.BitmapDestination.WritePixels().
FillBitmapInfoHeader()
void BitMiracle.LibJpeg.BitmapDestination.FillBitmapInfoHeader (int bitsPerPixel, int cmap_entries, byte [] infoHeader) inline private
Definition at line 212 of file BitmapDestination.cs.
         {
             /* Fill the info header (Microsoft calls this a BITMAPINFOHEADER) */
             PUT_2B(infoHeader, 0, infoHeader.Length);   /* biSize */
             PUT_4B(infoHeader, 4, m_parameters.Width); /* biWidth */
             PUT_4B(infoHeader, 8, m_parameters.Height); /* biHeight */
             PUT_2B(infoHeader, 12, 1);   /* biPlanes - must be 1 */
             PUT_2B(infoHeader, 14, bitsPerPixel); /* biBitCount */
             /* we leave biCompression = 0, for none */
             /* we leave biSizeImage = 0; this is correct for uncompressed data */
             if (m_parameters.DensityUnit == DensityUnit.DotsCm)
             {
                 /* if have density in dots/cm, then */
                 PUT_4B(infoHeader, 24, m_parameters.DensityX * 100); /* XPels/M */
                 PUT_4B(infoHeader, 28, m_parameters.DensityY * 100); /* XPels/M */
             }
             PUT_2B(infoHeader, 32, cmap_entries); /* biClrUsed */
             /* we leave biClrImportant = 0 */
         }
References BitMiracle.LibJpeg.LoadedImageAttributes.DensityUnit, BitMiracle.LibJpeg.LoadedImageAttributes.DensityX, BitMiracle.LibJpeg.LoadedImageAttributes.DensityY, BitMiracle.LibJpeg.LoadedImageAttributes.Height, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.PUT_2B(), BitMiracle.LibJpeg.BitmapDestination.PUT_4B(), and BitMiracle.LibJpeg.LoadedImageAttributes.Width.
Referenced by BitMiracle.LibJpeg.BitmapDestination.CreateBitmapInfoHeader(), and BitMiracle.LibJpeg.BitmapDestination.CreateBitmapV4InfoHeader().
ProcessPixelsRow()
void BitMiracle.LibJpeg.BitmapDestination.ProcessPixelsRow (byte [] row) inline
Write some pixel data.
Implements BitMiracle.LibJpeg.IDecompressDestination.
Definition at line 54 of file BitmapDestination.cs.
         {
             if (m_parameters.Colorspace == Colorspace.Grayscale || m_parameters.QuantizeColors)
             {
                 PutGrayRow(row);
             }
             else if (m_parameters.Colorspace == Colorspace.CMYK)
             {
                 PutCmykRow(row);
             }
             else
             {
                 PutRgbRow(row);
             }
             ++m_currentRow;
         }
References BitMiracle.LibJpeg.LoadedImageAttributes.Colorspace, BitMiracle.LibJpeg.BitmapDestination.m_currentRow, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.PutCmykRow(), BitMiracle.LibJpeg.BitmapDestination.PutGrayRow(), BitMiracle.LibJpeg.BitmapDestination.PutRgbRow(), and BitMiracle.LibJpeg.LoadedImageAttributes.QuantizeColors.
PUT_2B()
static void BitMiracle.LibJpeg.BitmapDestination.PUT_2B (byte [] array, int offset, int value) inline static private
Definition at line 329 of file BitmapDestination.cs.
         {
             array[offset] = (byte)(value & 0xFF);
             array[offset + 1] = (byte)((value >> 8) & 0xFF);
         }
Referenced by BitMiracle.LibJpeg.BitmapDestination.FillBitmapInfoHeader().
PUT_4B()
static void BitMiracle.LibJpeg.BitmapDestination.PUT_4B (byte [] array, int offset, int value) inline static private
Definition at line 335 of file BitmapDestination.cs.
         {
             array[offset] = (byte)(value & 0xFF);
             array[offset + 1] = (byte)((value >> 8) & 0xFF);
             array[offset + 2] = (byte)((value >> 16) & 0xFF);
             array[offset + 3] = (byte)((value >> 24) & 0xFF);
         }
Referenced by BitMiracle.LibJpeg.BitmapDestination.CreateBitmapFileHeader(), BitMiracle.LibJpeg.BitmapDestination.CreateBitmapV4InfoHeader(), and BitMiracle.LibJpeg.BitmapDestination.FillBitmapInfoHeader().
PutCmykRow()
void BitMiracle.LibJpeg.BitmapDestination.PutCmykRow (byte [] row) inline private
This version is for writing 24-bit pixels
Definition at line 119 of file BitmapDestination.cs.
         {
             /* Transfer data.  Note destination values must be in BGR order
              * (even though Microsoft's own documents say the opposite).
              */
             for (var i = 0; i < m_parameters.Width; ++i)
             {
                 var firstComponent = i * 4;
                 m_pixels[firstComponent][m_currentRow] = row[firstComponent + 2];
                 m_pixels[firstComponent + 1][m_currentRow] = row[firstComponent + 1];
                 m_pixels[firstComponent + 2][m_currentRow] = row[firstComponent + 0];
                 m_pixels[firstComponent + 3][m_currentRow] = row[firstComponent + 3];
             }
         }
References BitMiracle.LibJpeg.BitmapDestination.m_currentRow, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.m_pixels, and BitMiracle.LibJpeg.LoadedImageAttributes.Width.
Referenced by BitMiracle.LibJpeg.BitmapDestination.ProcessPixelsRow().
PutGrayRow()
void BitMiracle.LibJpeg.BitmapDestination.PutGrayRow (byte [] row) inline private
This version is for grayscale OR quantized color output
Definition at line 88 of file BitmapDestination.cs.
         {
             for (var i = 0; i < m_parameters.Width; ++i)
             {
                 m_pixels[i][m_currentRow] = row[i];
             }
         }
References BitMiracle.LibJpeg.BitmapDestination.m_currentRow, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.m_pixels, and BitMiracle.LibJpeg.LoadedImageAttributes.Width.
Referenced by BitMiracle.LibJpeg.BitmapDestination.ProcessPixelsRow().
PutRgbRow()
void BitMiracle.LibJpeg.BitmapDestination.PutRgbRow (byte [] row) inline private
This version is for writing 24-bit pixels
Definition at line 99 of file BitmapDestination.cs.
         {
             /* Transfer data.  Note destination values must be in BGR order
              * (even though Microsoft's own documents say the opposite).
              */
             for (var i = 0; i < m_parameters.Width; ++i)
             {
                 var firstComponent = i * 3;
                 var red = row[firstComponent];
                 var green = row[firstComponent + 1];
                 var blue = row[firstComponent + 2];
                 m_pixels[firstComponent][m_currentRow] = blue;
                 m_pixels[firstComponent + 1][m_currentRow] = green;
                 m_pixels[firstComponent + 2][m_currentRow] = red;
             }
         }
References BitMiracle.LibJpeg.BitmapDestination.m_currentRow, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.m_pixels, and BitMiracle.LibJpeg.LoadedImageAttributes.Width.
Referenced by BitMiracle.LibJpeg.BitmapDestination.ProcessPixelsRow().
SetImageAttributes()
void BitMiracle.LibJpeg.BitmapDestination.SetImageAttributes (LoadedImageAttributes parameters) inline
Implementor of this interface should process image properties received from decompressor.
Parameters
parameters Image properties
Implements BitMiracle.LibJpeg.IDecompressDestination.
Definition at line 24 of file BitmapDestination.cs.
         {
             m_parameters = parameters ?? throw new ArgumentNullException(nameof(parameters));
         }
References BitMiracle.LibJpeg.BitmapDestination.m_parameters.
WriteColormap()
void BitMiracle.LibJpeg.BitmapDestination.WriteColormap (int map_colors, int map_entry_size) inline private
Write the colormap. Windows uses BGR0 map entries; OS/2 uses BGR entries.
Definition at line 248 of file BitmapDestination.cs.
         {
             var colormap = m_parameters.Colormap;
             var num_colors = m_parameters.ActualNumberOfColors;
             int i;
             if (colormap is object)
             {
                 if (m_parameters.ComponentsPerSample == 3)
                 {
                     /* Normal case with RGB colormap */
                     for (i = 0; i < num_colors; i++)
                     {
                         Output.WriteByte(colormap[2][i]);
                         Output.WriteByte(colormap[1][i]);
                         Output.WriteByte(colormap[0][i]);
                         if (map_entry_size == 4)
{
                             Output.WriteByte(0);
                         }
                     }
                 }
                 else
                 {
                     /* Grayscale colormap (only happens with grayscale quantization) */
                     for (i = 0; i < num_colors; i++)
                     {
                         Output.WriteByte(colormap[0][i]);
                         Output.WriteByte(colormap[0][i]);
                         Output.WriteByte(colormap[0][i]);
                         if (map_entry_size == 4)
{
                             Output.WriteByte(0);
                         }
                     }
                 }
             }
             else
             {
                 /* If no colormap, must be grayscale data.  Generate a linear "map". */
                 for (i = 0; i < 256; i++)
                 {
                     Output.WriteByte((byte)i);
                     Output.WriteByte((byte)i);
                     Output.WriteByte((byte)i);
                     if (map_entry_size == 4)
                     {
                         Output.WriteByte(0);
                     }
                 }
             }
             /* Pad colormap with zeros to ensure specified number of colormap entries */
             if (i > map_colors)
             {
                 throw new InvalidOperationException("Too many colors");
             }
             for (; i < map_colors; i++)
             {
                 Output.WriteByte(0);
                 Output.WriteByte(0);
                 Output.WriteByte(0);
                 if (map_entry_size == 4)
                 {
                     Output.WriteByte(0);
                 }
             }
         }
References BitMiracle.LibJpeg.LoadedImageAttributes.ActualNumberOfColors, BitMiracle.LibJpeg.LoadedImageAttributes.Colormap, BitMiracle.LibJpeg.LoadedImageAttributes.ComponentsPerSample, BitMiracle.LibJpeg.BitmapDestination.m_parameters, and BitMiracle.LibJpeg.BitmapDestination.Output.
Referenced by BitMiracle.LibJpeg.BitmapDestination.WriteHeader().
WriteHeader()
void BitMiracle.LibJpeg.BitmapDestination.WriteHeader () inline private
Write a Windows-style BMP file header, including colormap if needed
Definition at line 137 of file BitmapDestination.cs.
         {
             int bits_per_pixel;
             int cmap_entries;
             /* Compute colormap size and total file size */
             if (m_parameters.Colorspace == Colorspace.Grayscale || m_parameters.QuantizeColors)
             {
                 bits_per_pixel = 8;
                 cmap_entries = 256;
             }
             else
             {
                 cmap_entries = 0;
                 if (m_parameters.Colorspace == Colorspace.RGB)
                 {
                     bits_per_pixel = 24;
                 }
                 else if (m_parameters.Colorspace == Colorspace.CMYK)
                 {
                     bits_per_pixel = 32;
                 }
                 else
                 {
                     throw new InvalidOperationException();
                 }
             }
             byte[] infoHeader;
             if (m_parameters.Colorspace == Colorspace.RGB)
             {
                 infoHeader = CreateBitmapInfoHeader(bits_per_pixel, cmap_entries);
             }
             else
             {
                 infoHeader = CreateBitmapV4InfoHeader(bits_per_pixel);
             }
             /* File size */
             const int fileHeaderSize = 14;
             var infoHeaderSize = infoHeader.Length;
             var paletteSize = cmap_entries * 4;
             var offsetToPixels = fileHeaderSize + infoHeaderSize + paletteSize; /* Header and colormap */
             var fileSize = offsetToPixels + (m_rowWidth * m_parameters.Height);
             var fileHeader = CreateBitmapFileHeader(offsetToPixels, fileSize);
             Output.Write(fileHeader, 0, fileHeader.Length);
             Output.Write(infoHeader, 0, infoHeader.Length);
             if (cmap_entries > 0)
             {
                 WriteColormap(cmap_entries, 4);
             }
         }
References BitMiracle.LibJpeg.LoadedImageAttributes.Colorspace, BitMiracle.LibJpeg.BitmapDestination.CreateBitmapFileHeader(), BitMiracle.LibJpeg.BitmapDestination.CreateBitmapInfoHeader(), BitMiracle.LibJpeg.BitmapDestination.CreateBitmapV4InfoHeader(), BitMiracle.LibJpeg.LoadedImageAttributes.Height, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.m_rowWidth, BitMiracle.LibJpeg.BitmapDestination.Output, BitMiracle.LibJpeg.LoadedImageAttributes.QuantizeColors, and BitMiracle.LibJpeg.BitmapDestination.WriteColormap().
Referenced by BitMiracle.LibJpeg.BitmapDestination.EndWrite().
WritePixels()
void BitMiracle.LibJpeg.BitmapDestination.WritePixels () inline private
Definition at line 318 of file BitmapDestination.cs.
         {
             for (var row = m_parameters.Height - 1; row >= 0; --row)
             {
                 for (var col = 0; col < m_rowWidth; ++col)
                 {
                     Output.WriteByte(m_pixels[col][row]);
                 }
             }
         }
References BitMiracle.LibJpeg.LoadedImageAttributes.Height, BitMiracle.LibJpeg.BitmapDestination.m_parameters, BitMiracle.LibJpeg.BitmapDestination.m_pixels, BitMiracle.LibJpeg.BitmapDestination.m_rowWidth, and BitMiracle.LibJpeg.BitmapDestination.Output.
Referenced by BitMiracle.LibJpeg.BitmapDestination.EndWrite().
Member Data Documentation
m_currentRow
int BitMiracle.LibJpeg.BitmapDestination.m_currentRow private
Definition at line 14 of file BitmapDestination.cs.
Referenced by BitMiracle.LibJpeg.BitmapDestination.BeginWrite(), BitMiracle.LibJpeg.BitmapDestination.ProcessPixelsRow(), BitMiracle.LibJpeg.BitmapDestination.PutCmykRow(), BitMiracle.LibJpeg.BitmapDestination.PutGrayRow(), and BitMiracle.LibJpeg.BitmapDestination.PutRgbRow().
m_parameters
LoadedImageAttributes BitMiracle.LibJpeg.BitmapDestination.m_parameters private
Definition at line 15 of file BitmapDestination.cs.
Referenced by BitMiracle.LibJpeg.BitmapDestination.BeginWrite(), BitMiracle.LibJpeg.BitmapDestination.FillBitmapInfoHeader(), BitMiracle.LibJpeg.BitmapDestination.ProcessPixelsRow(), BitMiracle.LibJpeg.BitmapDestination.PutCmykRow(), BitMiracle.LibJpeg.BitmapDestination.PutGrayRow(), BitMiracle.LibJpeg.BitmapDestination.PutRgbRow(), BitMiracle.LibJpeg.BitmapDestination.SetImageAttributes(), BitMiracle.LibJpeg.BitmapDestination.WriteColormap(), BitMiracle.LibJpeg.BitmapDestination.WriteHeader(), and BitMiracle.LibJpeg.BitmapDestination.WritePixels().
m_pixels
byte [][] BitMiracle.LibJpeg.BitmapDestination.m_pixels private
Definition at line 10 of file BitmapDestination.cs.
Referenced by BitMiracle.LibJpeg.BitmapDestination.BeginWrite(), BitMiracle.LibJpeg.BitmapDestination.PutCmykRow(), BitMiracle.LibJpeg.BitmapDestination.PutGrayRow(), BitMiracle.LibJpeg.BitmapDestination.PutRgbRow(), and BitMiracle.LibJpeg.BitmapDestination.WritePixels().
m_rowWidth
int BitMiracle.LibJpeg.BitmapDestination.m_rowWidth private
Definition at line 12 of file BitmapDestination.cs.
Referenced by BitMiracle.LibJpeg.BitmapDestination.BeginWrite(), BitMiracle.LibJpeg.BitmapDestination.WriteHeader(), and BitMiracle.LibJpeg.BitmapDestination.WritePixels().
Property Documentation
Output
Stream BitMiracle.LibJpeg.BitmapDestination.Output get
Definition at line 22 of file BitmapDestination.cs.
 { get; }
Referenced by BitMiracle.LibJpeg.BitmapDestination.BitmapDestination(), BitMiracle.LibJpeg.BitmapDestination.EndWrite(), BitMiracle.LibJpeg.BitmapDestination.WriteColormap(), BitMiracle.LibJpeg.BitmapDestination.WriteHeader(), and BitMiracle.LibJpeg.BitmapDestination.WritePixels().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/BitmapDestination.cs