Juniper: Juniper.Unity.Anchoring.MockAnchorStore Class Reference
Juniper.Unity.Anchoring.MockAnchorStore Class Reference
Public Member Functions
override bool HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
override void ResetData ()
Delete saved anchors, if there are any.
bool DropAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
void WeighAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Protected Member Functions
override AnchorType LoadAnchor (string ID)
override AnchorType CreateAnchor (string ID, GameObject gameObject)
virtual AnchorType SaveAnchor (string ID, GameObject gameObject)
virtual bool IsGood (AnchorType anchor)
virtual void DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor)
virtual AnchorType FindAnchor (GameObject gameObject)
virtual bool IsSaved (AnchorType anchor)
Static Protected Member Functions
static string MakeID (string name)
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
static bool HasValue (string name)
static void SaveValue (string name, object value)
Saves a value to PlayerPrefs.
static T LoadValue< T > (string name)
Gets a value back out of PlayerPrefs.
static bool DeleteValue (string name)
Removes a value from the PlayerPrefs.
Private Attributes
Dictionary< string, AnchorType > anchorStore = new Dictionary<string, AnchorType>()
Detailed Description
Definition at line 9 of file MockAnchorStore.cs.
Member Function Documentation
CreateAnchor()
override AnchorType Juniper.Unity.Anchoring.MockAnchorStore.CreateAnchor (string ID, GameObject gameObject) inline protected virtual
Implements Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 36 of file MockAnchorStore.cs.
         {
             var t = gameObject.transform;
             var anchor = gameObject.AddComponent<MockWorldAnchor>();
             anchor.state = new MockWorldAnchor.Pose
             {
                 position = t.position,
                 rotation = t.rotation
             };
             SaveValue(ID, anchor.state);
             return anchor;
         }
References Juniper.Unity.Anchoring.MockWorldAnchor.Pose.position, Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue(), and Juniper.Unity.Anchoring.MockWorldAnchor.state.
DeleteAnchor()
virtual void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor) inline protected virtual inherited
Reimplemented in Juniper.Unity.Anchoring.ARKitAnchorStore, and Juniper.Unity.Anchoring.ARCoreAnchorStore.
Definition at line 225 of file AbstractAnchorStore.cs.
         {
             DeleteValue(ID);
             anchor.Destroy();
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue().
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor().
DeleteValue()
static bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue (string name) inline static protected inherited
Removes a value from the PlayerPrefs.
Parameters
name
Returns
Definition at line 125 of file AbstractAnchorStore.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 PlayerPrefs.DeleteKey(key);
                 NameList = NameList.Where(k => k != name).ToArray();
                 return true;
             }
             else
             {
                 return false;
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.NameList.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.ResetData(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor().
DropAnchor()
bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor (string ID, GameObject gameObject) inline inherited
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
Returns
true, if anchor existed on the object, existed in the datastore, or was successfully created, false otherwise.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 165 of file AbstractAnchorStore.cs.
         {
             if (string.IsNullOrEmpty(ID))
             {
                 throw new ArgumentException("Parameter must have a value.", nameof(ID));
             }
             var anchor = FindAnchor(gameObject);
             if (!IsSaved(anchor))
             {
                 anchor = SaveAnchor(ID, gameObject);
             }
             return IsGood(anchor);
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.FindAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsGood(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsSaved(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
Referenced by Juniper.Unity.Anchoring.Anchored.DropAnchor().
FindAnchor()
virtual AnchorType Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.FindAnchor (GameObject gameObject) inline protected virtual inherited
Reimplemented in Juniper.Unity.Anchoring.ARKitAnchorStore.
Definition at line 231 of file AbstractAnchorStore.cs.
         {
             return gameObject?.GetComponent<AnchorType>();
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor().
HasAnchor()
override bool Juniper.Unity.Anchoring.MockAnchorStore.HasAnchor (string anchorID) inline virtual
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
Returns
true, if anchor exists, false otherwise.
Parameters
anchorID Anchor identifier.
Implements Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 13 of file MockAnchorStore.cs.
         {
             return anchorStore.ContainsKey(anchorID);
         }
References Juniper.Unity.Anchoring.MockAnchorStore.anchorStore.
HasValue()
static bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasValue (string name) inline static protected inherited
Definition at line 76 of file AbstractAnchorStore.cs.
         {
             return PlayerPrefs.HasKey(MakeID(name));
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID().
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
IsGood()
virtual bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsGood (AnchorType anchor) inline protected virtual inherited
Definition at line 202 of file AbstractAnchorStore.cs.
         {
             return anchor != null;
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor().
IsSaved()
virtual bool Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.IsSaved (AnchorType anchor) inline protected virtual inherited
Definition at line 236 of file AbstractAnchorStore.cs.
         {
             return anchor != null;
         }
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor().
LoadAnchor()
override AnchorType Juniper.Unity.Anchoring.MockAnchorStore.LoadAnchor (string ID) inline protected virtual
Implements Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 28 of file MockAnchorStore.cs.
         {
             var anchor = gameObject.AddComponent<MockWorldAnchor>();
             anchor.state = LoadValue<MockWorldAnchor.Pose>(ID);
             return anchor;
         }
References Juniper.Unity.Anchoring.MockWorldAnchor.state.
LoadValue< T >()
static T Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadValue< T > (string name) inline static protected inherited
Gets a value back out of PlayerPrefs.
Template Parameters
T
Parameters
name
Returns
Definition at line 107 of file AbstractAnchorStore.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 return JsonConvert.DeserializeObject<T>(PlayerPrefs.GetString(key));
             }
             else
             {
                 return default(T);
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID().
MakeID()
static string Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID (string name) inline static protected inherited
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
Parameters
name A controllable part of the name, to be modified to be unique in PlayerPrefs.
Returns
A name in PlayerPrefs unique to AbstractAnchorStore.
Definition at line 28 of file AbstractAnchorStore.cs.
         {
             return ID_PREFIX + name;
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.ID_PREFIX.
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadValue< T >(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue().
ResetData()
override void Juniper.Unity.Anchoring.MockAnchorStore.ResetData () inline virtual
Delete saved anchors, if there are any.
Reimplemented from Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 21 of file MockAnchorStore.cs.
         {
             base.ResetData();
             anchorStore.Clear();
         }
References Juniper.Unity.Anchoring.MockAnchorStore.anchorStore.
SaveAnchor()
virtual AnchorType Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor (string ID, GameObject gameObject) inline protected virtual inherited
Reimplemented in Juniper.Unity.Anchoring.ARKitAnchorStore, and Juniper.Unity.Anchoring.ARCoreAnchorStore.
Definition at line 181 of file AbstractAnchorStore.cs.
         {
             var scaleID = ID + "-scale";
             AnchorType anchor;
             if (HasAnchor(ID))
             {
                 anchor = LoadAnchor(ID);
                 if (HasValue(scaleID))
                 {
                     gameObject.transform.localScale = LoadValue<Vector3>(scaleID);
                 }
             }
             else
             {
                 anchor = CreateAnchor(ID, gameObject);
                 SaveValue(scaleID, gameObject.transform.localScale);
             }
             return anchor;
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.CreateAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.HasValue(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.LoadAnchor(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue().
Referenced by Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor().
SaveValue()
static void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue (string name, object value) inline static protected inherited
Saves a value to PlayerPrefs.
Parameters
name The name of the object to save.
value The value to save.
Definition at line 86 of file AbstractAnchorStore.cs.
         {
             PlayerPrefs.SetString(MakeID(name), JsonConvert.SerializeObject(value));
             var names = NameList;
             if (names.Contains(name))
             {
                 PlayerPrefs.Save();
             }
             else
             {
                 NameList = names.Append(name).ToArray();
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.MakeID(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.NameList.
Referenced by Juniper.Unity.Anchoring.MockAnchorStore.CreateAnchor(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.SaveAnchor().
WeighAnchor()
void Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor (string ID, GameObject gameObject) inline inherited
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 215 of file AbstractAnchorStore.cs.
         {
             var anchor = FindAnchor(gameObject);
             if (anchor != null)
             {
                 DeleteAnchor(ID, gameObject, anchor);
                 DeleteValue(ID + "-scale");
             }
         }
References Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteAnchor(), Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue(), and Juniper.Unity.Anchoring.AbstractAnchorStore< AnchorType >.FindAnchor().
Referenced by Juniper.Unity.Anchoring.Anchored.WeighAnchor().
Member Data Documentation
anchorStore
Dictionary<string, AnchorType> Juniper.Unity.Anchoring.MockAnchorStore.anchorStore = new Dictionary<string, AnchorType>() private
Definition at line 11 of file MockAnchorStore.cs.
Referenced by Juniper.Unity.Anchoring.MockAnchorStore.HasAnchor(), and Juniper.Unity.Anchoring.MockAnchorStore.ResetData().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Anchoring/MockAnchorStore.cs