Juniper: Juniper.XR.Pose Struct Reference
Juniper.XR.Pose Struct Reference
Public Member Functions
Pose (Vector3Serializable position, QuaternionSerializable orientation)
Pose (float px, float py, float pz, float ox, float oy, float oz, float ow)
void GetObjectData (SerializationInfo info, StreamingContext context)
override bool Equals (object obj)
bool Equals (Pose other)
override int GetHashCode ()
Static Public Member Functions
static bool operator== (Pose left, Pose right)
static bool operator != (Pose left, Pose right)
Static Public Attributes
static readonly Pose Identity = new Pose(0, 0, 0, 0, 0, 0, 1)
Properties
Vector3Serializable Position [get]
QuaternionSerializable Orientation [get]
Private Member Functions
Pose??? (SerializationInfo info, StreamingContext context)
Detailed Description
Definition at line 9 of file Pose.cs.
Constructor & Destructor Documentation
Pose() [1/2]
Juniper.XR.Pose.Pose (Vector3Serializable position, QuaternionSerializable orientation) inline
Definition at line 16 of file Pose.cs.
         {
             Position = position;
             Orientation = orientation;
         }
References Juniper.XR.Pose.Orientation, and Juniper.XR.Pose.Position.
Pose() [2/2]
Juniper.XR.Pose.Pose (float px, float py, float pz, float ox, float oy, float oz, float ow) inline
Definition at line 22 of file Pose.cs.
             : this(new Vector3Serializable(px, py, pz), new QuaternionSerializable(ox, oy, oz, ow))
         { }
Member Function Documentation
Equals() [1/2]
override bool Juniper.XR.Pose.Equals (object obj) inline
Definition at line 43 of file Pose.cs.
         {
             return obj is Pose other
                 && Equals(other);
         }
Equals() [2/2]
bool Juniper.XR.Pose.Equals (Pose other) inline
Definition at line 49 of file Pose.cs.
         {
             return Position.Equals(other.Position)
                 && Orientation.Equals(other.Orientation);
         }
References Juniper.Mathematics.Vector3Serializable.Equals(), Juniper.Mathematics.QuaternionSerializable.Equals(), Juniper.XR.Pose.Orientation, and Juniper.XR.Pose.Position.
GetHashCode()
override int Juniper.XR.Pose.GetHashCode () inline
Definition at line 55 of file Pose.cs.
         {
             return Position.GetHashCode()
                 ^ Orientation.GetHashCode();
         }
References Juniper.Mathematics.Vector3Serializable.GetHashCode(), Juniper.Mathematics.QuaternionSerializable.GetHashCode(), Juniper.XR.Pose.Orientation, and Juniper.XR.Pose.Position.
GetObjectData()
void Juniper.XR.Pose.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 32 of file Pose.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddVector3(nameof(Position), Position);
             info.AddQuaternion(nameof(Orientation), Orientation);
         }
References Juniper.XR.Pose.Orientation, and Juniper.XR.Pose.Position.
operator !=()
static bool Juniper.XR.Pose.operator != (Pose left, Pose right) inline static
Definition at line 66 of file Pose.cs.
         {
             return !(left == right);
         }
operator==()
static bool Juniper.XR.Pose.operator== (Pose left, Pose right) inline static
Definition at line 61 of file Pose.cs.
         {
             return left.Equals(right);
         }
Pose???()
Juniper.XR.Pose.Pose??? (SerializationInfo info, StreamingContext context) inline private
Definition at line 27 of file Pose.cs.
             : this(info?.GetVector3(nameof(Position)) ?? throw new ArgumentNullException(nameof(info)),
                 info.GetQuaternion(nameof(Orientation)))
         { }
Member Data Documentation
Identity
readonly Pose Juniper.XR.Pose.Identity = new Pose(0, 0, 0, 0, 0, 0, 1) static
Definition at line 11 of file Pose.cs.
Property Documentation
Orientation
QuaternionSerializable Juniper.XR.Pose.Orientation get
Definition at line 14 of file Pose.cs.
 { get; }
Referenced by Juniper.XR.Pose.Equals(), Juniper.XR.Pose.GetHashCode(), Juniper.XR.Pose.GetObjectData(), and Juniper.XR.Pose.Pose().
Position
Vector3Serializable Juniper.XR.Pose.Position get
Definition at line 13 of file Pose.cs.
 { get; }
Referenced by Juniper.XR.Pose.Equals(), Juniper.XR.Pose.GetHashCode(), Juniper.XR.Pose.GetObjectData(), and Juniper.XR.Pose.Pose().
The documentation for this struct was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/XR/Pose.cs