Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegDPostController Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegDPostController Class Reference
Decompression postprocessing (color quantization buffer control)
Public Member Functions
JpegDPostController (JpegDecompressStruct cinfo, bool need_full_buffer)
Initialize postprocessing controller.
void StartPass (JBufMode pass_mode)
Initialize for a processing pass.
void PostProcessData (ComponentBuffer[] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, byte[][] output_buf, ref int out_row_ctr, int out_rows_avail)
Private Types
enum ProcessorType { ProcessorType.OnePass, ProcessorType.PrePass, ProcessorType.Upsample, ProcessorType.SecondPass }
Private Member Functions
void PostProcess1Pass (ComponentBuffer[] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, byte[][] output_buf, ref int out_row_ctr, int out_rows_avail)
Process some data in the one-pass (strip buffer) case. This is used for color precision reduction as well as one-pass quantization.
void PostProcessPrepass (ComponentBuffer[] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, ref int out_row_ctr)
Process some data in the first pass of 2-pass quantization.
void PostProcess2Pass (byte[][] output_buf, ref int out_row_ctr, int out_rows_avail)
Process some data in the second pass of 2-pass quantization.
Private Attributes
ProcessorType m_processor
readonly JpegDecompressStruct m_cinfo
readonly JVirtArray< byte > m_whole_image
byte [][] m_buffer
readonly int m_strip_height
int m_starting_row
int m_next_row
Detailed Description
Decompression postprocessing (color quantization buffer control)
Definition at line 18 of file JpegDPostController.cs.
Member Enumeration Documentation
ProcessorType
enum BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.ProcessorType strong private
Enumerator
OnePass
PrePass
Upsample
SecondPass
Definition at line 20 of file JpegDPostController.cs.
         {
             OnePass,
             PrePass,
             Upsample,
             SecondPass
         }
Constructor & Destructor Documentation
JpegDPostController()
BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController (JpegDecompressStruct cinfo, bool need_full_buffer) inline
Initialize postprocessing controller.
Definition at line 47 of file JpegDPostController.cs.
         {
             m_cinfo = cinfo;
             /* Create the quantization buffer, if needed */
             if (cinfo.quantizeColors)
             {
                 /* The buffer strip height is max_v_samp_factor, which is typically
                 * an efficient number of rows for upsampling to return.
                 * (In the presence of output rescaling, we might want to be smarter?)
                 */
                 m_strip_height = cinfo.m_maxVSampleFactor;
                 if (need_full_buffer)
                 {
                     /* Two-pass color quantization: need full-image storage. */
                     /* We round up the number of rows to a multiple of the strip height. */
                     m_whole_image = JpegCommonStruct.CreateSamplesArray(
                         cinfo.outputWidth * cinfo.outColorComponents,
                         JpegUtils.jround_up(cinfo.outputHeight, m_strip_height));
                     m_whole_image.ErrorProcessor = cinfo;
                 }
                 else
                 {
                     /* One-pass color quantization: just make a strip buffer. */
                     m_buffer = JpegCommonStruct.AllocJpegSamples(
                         cinfo.outputWidth * cinfo.outColorComponents, m_strip_height);
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateSamplesArray(), BitMiracle.LibJpeg.Classic.JVirtArray< T >.ErrorProcessor, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jround_up(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_buffer, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_maxVSampleFactor, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_strip_height, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_whole_image, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors.
Member Function Documentation
PostProcess1Pass()
void BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess1Pass (ComponentBuffer [] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, byte output_buf[][], ref int out_row_ctr, int out_rows_avail) inline private
Process some data in the one-pass (strip buffer) case. This is used for color precision reduction as well as one-pass quantization.
Definition at line 159 of file JpegDPostController.cs.
         {
             /* Fill the buffer, but not more than what we can dump out in one go. */
             /* Note we rely on the upsampler to detect bottom of image. */
             var max_rows = out_rows_avail - out_row_ctr;
             if (max_rows > m_strip_height)
             {
                 max_rows = m_strip_height;
             }
             var num_rows = 0;
             m_cinfo.m_upsample.UpSample(input_buf, ref in_row_group_ctr, in_row_groups_avail, m_buffer, ref num_rows, max_rows);
             /* Quantize and emit data. */
             m_cinfo.m_cquantize.ColorQuantize(m_buffer, 0, output_buf, out_row_ctr, num_rows);
             out_row_ctr += num_rows;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_buffer, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cquantize, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_strip_height, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_upsample.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData().
PostProcess2Pass()
void BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass (byte output_buf[][], ref int out_row_ctr, int out_rows_avail) inline private
Process some data in the second pass of 2-pass quantization.
Definition at line 214 of file JpegDPostController.cs.
         {
             int num_rows, max_rows;
             /* Reposition virtual buffer if at start of strip. */
             if (m_next_row == 0)
             {
                 m_buffer = m_whole_image.Access(m_starting_row, m_strip_height);
             }
             /* Determine number of rows to emit. */
             num_rows = m_strip_height - m_next_row; /* available in strip */
             max_rows = out_rows_avail - out_row_ctr; /* available in output area */
             if (num_rows > max_rows)
             {
                 num_rows = max_rows;
             }
             /* We have to check bottom of image here, can't depend on upsampler. */
             max_rows = m_cinfo.outputHeight - m_starting_row;
             if (num_rows > max_rows)
             {
                 num_rows = max_rows;
             }
             /* Quantize and emit data. */
             m_cinfo.m_cquantize.ColorQuantize(m_buffer, m_next_row, output_buf, out_row_ctr, num_rows);
             out_row_ctr += num_rows;
             /* Advance if we filled the strip. */
             m_next_row += num_rows;
             if (m_next_row >= m_strip_height)
             {
                 m_starting_row += m_strip_height;
                 m_next_row = 0;
             }
         }
References BitMiracle.LibJpeg.Classic.JVirtArray< T >.Access(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_buffer, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cquantize, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_next_row, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_starting_row, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_strip_height, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_whole_image, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputHeight.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData().
PostProcessData()
void BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData (ComponentBuffer [] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, byte output_buf[][], ref int out_row_ctr, int out_rows_avail) inline
Definition at line 133 of file JpegDPostController.cs.
         {
             switch (m_processor)
             {
                 case ProcessorType.OnePass:
                 PostProcess1Pass(input_buf, ref in_row_group_ctr, in_row_groups_avail, output_buf, ref out_row_ctr, out_rows_avail);
                 break;
                 case ProcessorType.PrePass:
                 PostProcessPrepass(input_buf, ref in_row_group_ctr, in_row_groups_avail, ref out_row_ctr);
                 break;
                 case ProcessorType.Upsample:
                 m_cinfo.m_upsample.UpSample(input_buf, ref in_row_group_ctr, in_row_groups_avail, output_buf, ref out_row_ctr, out_rows_avail);
                 break;
                 case ProcessorType.SecondPass:
                 PostProcess2Pass(output_buf, ref out_row_ctr, out_rows_avail);
                 break;
                 default:
                 m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
                 break;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_processor, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_upsample, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess1Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass().
PostProcessPrepass()
void BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass (ComponentBuffer [] input_buf, ref int in_row_group_ctr, int in_row_groups_avail, ref int out_row_ctr) inline private
Process some data in the first pass of 2-pass quantization.
Definition at line 180 of file JpegDPostController.cs.
         {
             int old_next_row, num_rows;
             /* Reposition virtual buffer if at start of strip. */
             if (m_next_row == 0)
             {
                 m_buffer = m_whole_image.Access(m_starting_row, m_strip_height);
             }
             /* Upsample some data (up to a strip height's worth). */
             old_next_row = m_next_row;
             m_cinfo.m_upsample.UpSample(input_buf, ref in_row_group_ctr, in_row_groups_avail, m_buffer, ref m_next_row, m_strip_height);
             /* Allow quantizer to scan new data.  No data is emitted, */
             /* but we advance out_row_ctr so outer loop can tell when we're done. */
             if (m_next_row > old_next_row)
             {
                 num_rows = m_next_row - old_next_row;
                 m_cinfo.m_cquantize.ColorQuantize(m_buffer, old_next_row, null, 0, num_rows);
                 out_row_ctr += num_rows;
             }
             /* Advance if we filled the strip. */
             if (m_next_row >= m_strip_height)
             {
                 m_starting_row += m_strip_height;
                 m_next_row = 0;
             }
         }
References BitMiracle.LibJpeg.Classic.JVirtArray< T >.Access(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_buffer, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_cinfo, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_cquantize, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_next_row, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_starting_row, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_strip_height, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_upsample, and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_whole_image.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData().
StartPass()
void BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass (JBufMode pass_mode) inline
Initialize for a processing pass.
Definition at line 81 of file JpegDPostController.cs.
         {
             switch (pass_mode)
             {
                 case JBufMode.PassThrough:
                 if (m_cinfo.quantizeColors)
                 {
                     /* Single-pass processing with color quantization. */
                     m_processor = ProcessorType.OnePass;
                     /* We could be doing buffered-image output before starting a 2-pass
                      * color quantization; in that case, jinit_d_post_controller did not
                      * allocate a strip buffer.  Use the virtual-array buffer as workspace.
                      */
                     if (m_buffer is null)
                     {
                         m_buffer = m_whole_image.Access(0, m_strip_height);
                     }
                 }
                 else
                 {
                     /* For single-pass processing without color quantization,
                      * I have no work to do; just call the upsampler directly.
                      */
                     m_processor = ProcessorType.Upsample;
                 }
                 break;
                 case JBufMode.SaveAndPass:
                 /* First pass of 2-pass quantization */
                 if (m_whole_image is null)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_BAD_BUFFER_MODE);
                 }
                 m_processor = ProcessorType.PrePass;
                 break;
                 case JBufMode.CrankDest:
                 /* Second pass of 2-pass quantization */
                 if (m_whole_image is null)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_BAD_BUFFER_MODE);
                 }
                 m_processor = ProcessorType.SecondPass;
                 break;
                 default:
                 m_cinfo.ErrExit(JMessageCode.JERR_BAD_BUFFER_MODE);
                 break;
             }
             m_starting_row = m_next_row = 0;
         }
References BitMiracle.LibJpeg.Classic.JVirtArray< T >.Access(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_buffer, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_next_row, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_processor, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_starting_row, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_strip_height, BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_whole_image, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors.
Member Data Documentation
m_buffer
byte [][] BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_buffer private
Definition at line 38 of file JpegDPostController.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess1Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
m_cinfo
readonly JpegDecompressStruct BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_cinfo private
Definition at line 30 of file JpegDPostController.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess1Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
m_next_row
int BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_next_row private
Definition at line 42 of file JpegDPostController.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
m_processor
ProcessorType BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_processor private
Definition at line 28 of file JpegDPostController.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
m_starting_row
int BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_starting_row private
Definition at line 41 of file JpegDPostController.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
m_strip_height
readonly int BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_strip_height private
Definition at line 39 of file JpegDPostController.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess1Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
m_whole_image
readonly JVirtArray<byte> BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.m_whole_image private
Definition at line 37 of file JpegDPostController.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegDPostController.cs