Juniper: Juniper.Unity.EditableDateTime Struct Reference
Juniper.Unity.EditableDateTime Struct Reference
A wrapper around System.DateTime that makes it possible to edit values in the Unity Editor.
Public Member Functions
EditableDateTime (DateTime time)
Initializes a new structure for editing DateTime values in the Unity Editor.
override bool Equals (object obj)
Determines whether the specified object is equal to the current T:UnityEngine.EditableDateTime.
override int GetHashCode ()
Serves as a hash function for a T:UnityEngine.EditableDateTime object.
Static Public Member Functions
static implicit operator DateTime (EditableDateTime val)
Automatically convert the EditableDateTime to a DateTime, meaning you can use an EditableDateTime anywhere you can use a DateTime.
static implicit operator EditableDateTime (DateTime val)
Automatically convert the DateTime to an EditableDateTime, meaning you can use an DateTime anywhere you can use a EditableDateTime.
static bool operator== (EditableDateTime a, EditableDateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified UnityEngine.EditableDateTime.
static bool operator != (EditableDateTime a, EditableDateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified UnityEngine.EditableDateTime.
static bool operator== (EditableDateTime a, DateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified System.DateTime.
static bool operator != (EditableDateTime a, DateTime b)
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified System.DateTime.
static bool operator== (DateTime a, EditableDateTime b)
Determines whether a specified instance of System.DateTime is equal to another specified UnityEngine.EditableDateTime.
static bool operator != (DateTime a, EditableDateTime b)
Determines whether a specified instance of System.DateTime is not equal to another specified UnityEngine.EditableDateTime.
Public Attributes
DateTimeKind Kind
Unspecified, UTC, or Local.
int Year
The year.
Month Month
The month.
int Day
The day. If the day is not valid for the month, it will be reset to the next previous valid day.
int Hour
The hour.
int Minute
The minute.
int Second
The second.
int Millisecond
The millisecond.
Static Public Attributes
static TimeSpan TestOffset = new TimeSpan(0, 0, 0)
When testing applications running at different times, you can set this value to change the time the application thinks it is currently.
Properties
static DateTime Now [get]
Gets the current system time, plus any TestOffset.
DateTime Value [get, set]
Gets or sets the underlying DateTime value.
bool Changed [get]
Check to see if the input date values are different from the saved DateTime values.
Private Attributes
DateTime lastValue
The underlying DateTime value.
Detailed Description
A wrapper around System.DateTime that makes it possible to edit values in the Unity Editor.
Definition at line 11 of file EditableDateTime.cs.
Constructor & Destructor Documentation
EditableDateTime()
Juniper.Unity.EditableDateTime.EditableDateTime (DateTime time) inline
Initializes a new structure for editing DateTime values in the Unity Editor.
Parameters
time Time.
Definition at line 70 of file EditableDateTime.cs.
         {
             lastValue = time;
             Year = lastValue.Year;
             Month = (Month)lastValue.Month;
             Day = lastValue.Day;
             Hour = lastValue.Hour;
             Minute = lastValue.Minute;
             Second = lastValue.Second;
             Millisecond = lastValue.Millisecond;
             Kind = lastValue.Kind;
         }
References Juniper.Unity.EditableDateTime.Day, Juniper.Unity.EditableDateTime.Hour, Juniper.Unity.EditableDateTime.Kind, Juniper.Unity.EditableDateTime.lastValue, Juniper.Unity.EditableDateTime.Millisecond, Juniper.Unity.EditableDateTime.Minute, Juniper.Unity.EditableDateTime.Month, Juniper.Unity.EditableDateTime.Second, and Juniper.Unity.EditableDateTime.Year.
Referenced by Juniper.Unity.EditableDateTime.Equals(), and Juniper.Unity.EditableDateTime.operator EditableDateTime().
Member Function Documentation
Equals()
override bool Juniper.Unity.EditableDateTime.Equals (object obj) inline
Determines whether the specified object is equal to the current T:UnityEngine.EditableDateTime.
Parameters
obj The object to compare with the current T:UnityEngine.EditableDateTime.
Returns
true if the specified object is equal to the current T:UnityEngine.EditableDateTime; otherwise, false.
Definition at line 232 of file EditableDateTime.cs.
         {
             if (obj is EditableDateTime)
             {
                 var edt = (EditableDateTime)obj;
                 return edt.Value == Value;
             }
             else if (obj is DateTime)
             {
                 var dt = (DateTime)obj;
                 return dt == Value;
             }
             else
             {
                 return false;
             }
         }
References Juniper.Unity.EditableDateTime.EditableDateTime(), and Juniper.Unity.EditableDateTime.Value.
Referenced by Juniper.Unity.EditableDateTime.operator !=(), and Juniper.Unity.EditableDateTime.operator==().
GetHashCode()
override int Juniper.Unity.EditableDateTime.GetHashCode () inline
Serves as a hash function for a T:UnityEngine.EditableDateTime object.
Returns
A hash code for this instance that is suitable for use in hashing algorithms and data structures such as a hash table.
Definition at line 257 of file EditableDateTime.cs.
         {
             return Value.GetHashCode();
         }
References Juniper.Unity.EditableDateTime.Value.
operator !=() [1/3]
static bool Juniper.Unity.EditableDateTime.operator != (EditableDateTime a, EditableDateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are not equal; otherwise, false.
Definition at line 171 of file EditableDateTime.cs.
         {
             return !a.Equals(b);
         }
References Juniper.Unity.EditableDateTime.Equals().
operator !=() [2/3]
static bool Juniper.Unity.EditableDateTime.operator != (EditableDateTime a, DateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is not equal to another specified System.DateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second System.DateTime to compare.
Returns
true if a and b are not equal; otherwise, false.
Definition at line 195 of file EditableDateTime.cs.
         {
             return !a.Equals(b);
         }
References Juniper.Unity.EditableDateTime.Equals().
operator !=() [3/3]
static bool Juniper.Unity.EditableDateTime.operator != (DateTime a, EditableDateTime b) inline static
Determines whether a specified instance of System.DateTime is not equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first System.DateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are not equal; otherwise, false.
Definition at line 219 of file EditableDateTime.cs.
         {
             return !a.Equals(b);
         }
operator DateTime()
static implicit Juniper.Unity.EditableDateTime.operator DateTime (EditableDateTime val) inline static
Automatically convert the EditableDateTime to a DateTime, meaning you can use an EditableDateTime anywhere you can use a DateTime.
Returns
The unwrapped DateTime.
Parameters
val Value.
Definition at line 136 of file EditableDateTime.cs.
         {
             return val.Value;
         }
References Juniper.Unity.EditableDateTime.Value.
operator EditableDateTime()
static implicit Juniper.Unity.EditableDateTime.operator EditableDateTime (DateTime val) inline static
Automatically convert the DateTime to an EditableDateTime, meaning you can use an DateTime anywhere you can use a EditableDateTime.
Returns
The DateTime, wrapped in an EditableDateTime
Parameters
val Value.
Definition at line 147 of file EditableDateTime.cs.
         {
             return new EditableDateTime(val);
         }
References Juniper.Unity.EditableDateTime.EditableDateTime().
operator==() [1/3]
static bool Juniper.Unity.EditableDateTime.operator== (EditableDateTime a, EditableDateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are equal; otherwise, false.
Definition at line 159 of file EditableDateTime.cs.
         {
             return a.Equals(b);
         }
References Juniper.Unity.EditableDateTime.Equals().
operator==() [2/3]
static bool Juniper.Unity.EditableDateTime.operator== (EditableDateTime a, DateTime b) inline static
Determines whether a specified instance of UnityEngine.EditableDateTime is equal to another specified System.DateTime.
Parameters
a The first UnityEngine.EditableDateTime to compare.
b The second System.DateTime to compare.
Returns
true if a and b are equal; otherwise, false.
Definition at line 183 of file EditableDateTime.cs.
         {
             return a.Equals(b);
         }
References Juniper.Unity.EditableDateTime.Equals().
operator==() [3/3]
static bool Juniper.Unity.EditableDateTime.operator== (DateTime a, EditableDateTime b) inline static
Determines whether a specified instance of System.DateTime is equal to another specified UnityEngine.EditableDateTime.
Parameters
a The first System.DateTime to compare.
b The second UnityEngine.EditableDateTime to compare.
Returns
true if a and b are equal; otherwise, false.
Definition at line 207 of file EditableDateTime.cs.
         {
             return a.Equals(b);
         }
Member Data Documentation
Day
int Juniper.Unity.EditableDateTime.Day
The day. If the day is not valid for the month, it will be reset to the next previous valid day.
Definition at line 40 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
Hour
int Juniper.Unity.EditableDateTime.Hour
The hour.
Definition at line 46 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
Kind
DateTimeKind Juniper.Unity.EditableDateTime.Kind
Unspecified, UTC, or Local.
Definition at line 22 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
lastValue
DateTime Juniper.Unity.EditableDateTime.lastValue private
The underlying DateTime value.
Definition at line 265 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
Millisecond
int Juniper.Unity.EditableDateTime.Millisecond
The millisecond.
Definition at line 64 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
Minute
int Juniper.Unity.EditableDateTime.Minute
The minute.
Definition at line 52 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
Month
Month Juniper.Unity.EditableDateTime.Month
The month.
Definition at line 33 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
Second
int Juniper.Unity.EditableDateTime.Second
The second.
Definition at line 58 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
TestOffset
TimeSpan Juniper.Unity.EditableDateTime.TestOffset = new TimeSpan(0, 0, 0) static
When testing applications running at different times, you can set this value to change the time the application thinks it is currently.
Definition at line 17 of file EditableDateTime.cs.
Year
int Juniper.Unity.EditableDateTime.Year
The year.
Definition at line 28 of file EditableDateTime.cs.
Referenced by Juniper.Unity.EditableDateTime.EditableDateTime().
Property Documentation
Changed
bool Juniper.Unity.EditableDateTime.Changed get private
Check to see if the input date values are different from the saved DateTime values.
true if any of the values are different, false otherwise.
Definition at line 272 of file EditableDateTime.cs.
         {
             get
             {
                 return Year != lastValue.Year
                     || Month != (Month)lastValue.Month
                     || Day != lastValue.Day
                     || Hour != lastValue.Hour
                     || Minute != lastValue.Minute
                     || Second != lastValue.Second
                     || Millisecond != lastValue.Millisecond
                     || Kind != lastValue.Kind;
             }
         }
Now
DateTime Juniper.Unity.EditableDateTime.Now static get
Gets the current system time, plus any TestOffset.
The now.
Definition at line 88 of file EditableDateTime.cs.
         {
             get
             {
                 return DateTime.Now + TestOffset;
             }
         }
Referenced by Juniper.Unity.World.SunPosition.GetTime(), Juniper.Unity.World.GPSLocation.PrintDebugReport(), and Juniper.Unity.World.Climate.Weather.Update().
Value
DateTime Juniper.Unity.EditableDateTime.Value get set
Gets or sets the underlying DateTime value.
The value.
Definition at line 100 of file EditableDateTime.cs.
         {
             get
             {
                 if (Changed)
                 {
                     while (Day > DateTime.DaysInMonth(Year, (int)Month))
                     {
                         --Day;
                     }
                     lastValue = new DateTime(Year, (int)Month, Day, Hour, Minute, Second, Millisecond, Kind);
                 }
                 return lastValue;
             }
             set
             {
                 lastValue = value;
                 Year = value.Year;
                 Month = (Month)value.Month;
                 Day = value.Day;
                 Hour = value.Hour;
                 Minute = value.Minute;
                 Second = value.Second;
                 Millisecond = value.Millisecond;
                 Kind = value.Kind;
             }
         }
Referenced by Juniper.Unity.EditableDateTime.Equals(), Juniper.Unity.EditableDateTime.GetHashCode(), Juniper.Unity.World.SunPosition.GetTime(), and Juniper.Unity.EditableDateTime.operator DateTime().
The documentation for this struct was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/EditableDateTime.cs