Juniper: Juniper.Input.AbstractKeyEventSource< KeyT > Class Template Reference
Juniper.Input.AbstractKeyEventSource< KeyT > Class Template Reference
Public Member Functions
virtual void Start ()
virtual void Stop ()
void AddKeyAlias (string name, params KeyT[] keys)
bool IsDown (string name)
Protected Member Functions
AbstractKeyEventSource ()
void UpdateStates ()
Properties
Dictionary< KeyT, bool > KeyState = new Dictionary<KeyT, bool>() [get]
IReadOnlyCollection< KeyT > Keys [get, private set]
Events
EventHandler< KeyChangeEvent > KeyChanged
EventHandler< KeyEvent > KeyDown
EventHandler< KeyEvent > KeyUp
Private Attributes
readonly Dictionary< string, KeyT[]> aliases = new Dictionary<string, KeyT[]>()
readonly Dictionary< string, KeyEvent > events = new Dictionary<string, KeyEvent>()
readonly Dictionary< string, KeyChangeEvent > upEvents = new Dictionary<string, KeyChangeEvent>()
readonly Dictionary< string, KeyChangeEvent > downEvents = new Dictionary<string, KeyChangeEvent>()
readonly Dictionary< string, bool > aliasState = new Dictionary<string, bool>()
string [] names
readonly Context origin
Detailed Description
Definition at line 9 of file AbstractKeyEventSource.cs.
Constructor & Destructor Documentation
AbstractKeyEventSource()
Juniper.Input.AbstractKeyEventSource< KeyT >.AbstractKeyEventSource () inline protected
Definition at line 29 of file AbstractKeyEventSource.cs.
         {
             origin = Thread.CurrentContext;
         }
Member Function Documentation
AddKeyAlias()
void Juniper.Input.AbstractKeyEventSource< KeyT >.AddKeyAlias (string name, params KeyT [] keys) inline
Definition at line 77 of file AbstractKeyEventSource.cs.
         {
             lock (KeyState)
             {
                 foreach (var key in keys)
                 {
                     KeyState[key] = false;
                 }
                 aliases[name] = keys;
                 aliasState[name] = false;
                 events[name] = new KeyEvent(name);
                 upEvents[name] = new KeyChangeEvent(name, false);
                 downEvents[name] = new KeyChangeEvent(name, true);
             }
         }
IsDown()
bool Juniper.Input.AbstractKeyEventSource< KeyT >.IsDown (string name) inline
Definition at line 94 of file AbstractKeyEventSource.cs.
         {
             return aliasState[name];
         }
Start()
virtual void Juniper.Input.AbstractKeyEventSource< KeyT >.Start () inline virtual
Reimplemented in Juniper.Input.AbstractPollingKeyEventSource< KeyT >, and Juniper.Input.WinFormsKeyEventSource.
Definition at line 34 of file AbstractKeyEventSource.cs.
         {
             Keys = KeyState.Keys.ToArray();
             names = aliases.Keys.ToArray();
         }
Stop()
virtual void Juniper.Input.AbstractKeyEventSource< KeyT >.Stop () inline virtual
Reimplemented in Juniper.Input.AbstractPollingKeyEventSource< KeyT >, and Juniper.Input.WinFormsKeyEventSource.
Definition at line 40 of file AbstractKeyEventSource.cs.
 { }
UpdateStates()
void Juniper.Input.AbstractKeyEventSource< KeyT >.UpdateStates () inline protected
Definition at line 42 of file AbstractKeyEventSource.cs.
         {
             foreach (var name in names)
             {
                 var wasDown = aliasState[name];
                 var isDown = true;
                 foreach (var key in aliases[name])
                 {
                     isDown &= KeyState[key];
                 }
                 aliasState[name] = isDown;
                 if (isDown != wasDown)
                 {
                     if (isDown)
                     {
                         origin.DoCallBack(() =>
{
                             KeyDown?.Invoke(this, events[name]);
                             KeyChanged?.Invoke(this, downEvents[name]);
                         });
                     }
                     else
                     {
                         origin.DoCallBack(() =>
{
                             KeyUp?.Invoke(this, events[name]);
                             KeyChanged?.Invoke(this, upEvents[name]);
                         });
                     }
                 }
             }
         }
Referenced by Juniper.Input.AbstractPollingKeyEventSource< Key >.Update().
Member Data Documentation
aliases
readonly Dictionary<string, KeyT[]> Juniper.Input.AbstractKeyEventSource< KeyT >.aliases = new Dictionary<string, KeyT[]>() private
Definition at line 15 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AddKeyAlias(), Juniper.Input.AbstractKeyEventSource< Keys >.Start(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
aliasState
readonly Dictionary<string, bool> Juniper.Input.AbstractKeyEventSource< KeyT >.aliasState = new Dictionary<string, bool>() private
Definition at line 19 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AddKeyAlias(), Juniper.Input.AbstractKeyEventSource< Keys >.IsDown(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
downEvents
readonly Dictionary<string, KeyChangeEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.downEvents = new Dictionary<string, KeyChangeEvent>() private
Definition at line 18 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AddKeyAlias(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
events
readonly Dictionary<string, KeyEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.events = new Dictionary<string, KeyEvent>() private
Definition at line 16 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AddKeyAlias(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
names
string [] Juniper.Input.AbstractKeyEventSource< KeyT >.names private
Definition at line 25 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.Start(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
origin
readonly Context Juniper.Input.AbstractKeyEventSource< KeyT >.origin private
Definition at line 27 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AbstractKeyEventSource(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
upEvents
readonly Dictionary<string, KeyChangeEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.upEvents = new Dictionary<string, KeyChangeEvent>() private
Definition at line 17 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AddKeyAlias(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
Property Documentation
Keys
IReadOnlyCollection<KeyT> Juniper.Input.AbstractKeyEventSource< KeyT >.Keys get private set protected
Definition at line 23 of file AbstractKeyEventSource.cs.
 { get; private set; }
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.Start(), and Juniper.Input.AbstractPollingKeyEventSource< Key >.Update().
KeyState
Dictionary<KeyT, bool> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyState = new Dictionary<KeyT, bool>() get protected
Definition at line 21 of file AbstractKeyEventSource.cs.
 { get; } = new Dictionary<KeyT, bool>();
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.AddKeyAlias(), Juniper.Input.AbstractKeyEventSource< Keys >.Start(), Juniper.Input.AbstractPollingKeyEventSource< Key >.Update(), and Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
Event Documentation
KeyChanged
EventHandler<KeyChangeEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyChanged
Definition at line 11 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
KeyDown
EventHandler<KeyEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyDown
Definition at line 12 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
KeyUp
EventHandler<KeyEvent> Juniper.Input.AbstractKeyEventSource< KeyT >.KeyUp
Definition at line 13 of file AbstractKeyEventSource.cs.
Referenced by Juniper.Input.AbstractKeyEventSource< Keys >.UpdateStates().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/Input/AbstractKeyEventSource.cs