Juniper: Juniper.Unity.Animation.SpiralTransition Class Reference
Juniper.Unity.Animation.SpiralTransition Class Reference
Take an object in world-space and spiral it in to camera-locked space (faux-screen-space)
Public Member Functions
void Awake ()
Finds the transform of the main camera.
override void Update ()
Continuously update the location, rotation, and scale of the element.
override void Enter ()
Start the transition animation in the forward direction.
override void SkipEnter ()
Jump the transition to the ENTERED state, without animating through the ENTERING state.
override void Exit ()
Start the transition animation in the outward direction.
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Public Attributes
Vector3 startOrientation = 90 * Vector3.right
The local rotation of the element when sitting in its original parent.
Vector3 endOrientation = 90 * Vector3.back
The local rotation of the element when it is parented tracking the camera.
bool fullScreen = true
Set to true if the transition is being used to make a video appear as if it is full-screen. The distance field will automatically be calculated to make the extents of the video fill the viewport.
float distance = 0.2f
The distance from the camera at which the element should stop when the transition has finished entering. The value entered in the Editor for this field is ignored if fullScreen is set to true.
float length = 1
The amount of time, in seconds, that the transition should take.
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
override void RenderValue (float value)
Records the transition value so the Update function can use it.
override void OnEntering ()
Records the starting values so the enter transition can LERP over the values correctly.
override void OnExiting ()
Records the exiting values to make the update LERP undo the changes to the element.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Properties
override float TransitionLength [get]
The amount of time, in seconds, that the transition should take.
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler< ValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Attributes
Transform startParent
The object under which the element originally started.
Vector3 startPosition
The position at which the element started.
Vector3 startScale
The scale of the element at the start of the enter transition, or the end of the exit transition.
Vector3 endScale
The scale of the element at the end of the enter transition, or the start of the exit transition.
Transform camT
The camera, cached for faster access.
float tweenValue
The current transition state value, cached so the location and rotation can change with the camera after the transition has finished.
Detailed Description
Take an object in world-space and spiral it in to camera-locked space (faux-screen-space)
Definition at line 10 of file SpiralTransition.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Animation.SpiralTransition.Awake () inline
Finds the transform of the main camera.
Definition at line 55 of file SpiralTransition.cs.
         {
             camT = DisplayManager.MainCamera.transform;
         }
References Juniper.Unity.Animation.SpiralTransition.camT, and Juniper.Unity.Display.AbstractDisplayManager.MainCamera.
Enter()
override void Juniper.Unity.Animation.AbstractTransitionController.Enter () inline virtual inherited
Start the transition animation in the forward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 63 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.Enter();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.Widgets.TeleportPad.OnClick(), Juniper.Unity.MasterSceneController.QuitCoroutine(), Juniper.Unity.Widgets.Openable.SetOpen(), and Juniper.Unity.Animation.WorkflowStep.Show().
Exit()
override void Juniper.Unity.Animation.AbstractTransitionController.Exit () inline virtual inherited
Start the transition animation in the outward direction.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 84 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Reverse);
             base.Exit();
         }
References Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.Widgets.TeleportPad.Darth_Entered(), Juniper.Unity.Animation.FadeTransition.Fader(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.Unity.Widgets.Openable.SetOpen().
HasCompleted()
bool Juniper.Unity.AbstractStateController.HasCompleted () inline inherited
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 121 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.Unity.AbstractStateController.IsComplete.
OnDisable()
void Juniper.Unity.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 298 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.Unity.AbstractStateController.OnExited().
OnEnable()
void Juniper.Unity.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 193 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.Unity.AbstractStateController.OnEntering().
Referenced by Juniper.Unity.AbstractStateController.SkipEnter().
OnEntered()
virtual void Juniper.Unity.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 240 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntered?.Invoke();
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Entered, Juniper.Unity.AbstractStateController.onEntered, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.Update().
OnEntering()
override void Juniper.Unity.Animation.SpiralTransition.OnEntering () inline protected virtual
Records the starting values so the enter transition can LERP over the values correctly.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 97 of file SpiralTransition.cs.
         {
             startParent = transform.parent;
             startPosition = transform.position;
             endScale = transform.localScale;
             transform.parent = null;
             startScale = transform.localScale;
             base.OnEntering();
         }
References Juniper.Unity.Animation.SpiralTransition.endScale, Juniper.Unity.Animation.SpiralTransition.startParent, Juniper.Unity.Animation.SpiralTransition.startPosition, and Juniper.Unity.Animation.SpiralTransition.startScale.
OnExited()
virtual void Juniper.Unity.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, and Juniper.Unity.SubSceneController.
Definition at line 310 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExited?.Invoke();
                 Exited?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.AbstractStateController.Exited, Juniper.Unity.AbstractStateController.onExited, and Juniper.Unity.AbstractStateController.skipEvents.
Referenced by Juniper.Unity.AbstractStateController.OnDisable().
OnExiting()
override void Juniper.Unity.Animation.SpiralTransition.OnExiting () inline protected virtual
Records the exiting values to make the update LERP undo the changes to the element.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 110 of file SpiralTransition.cs.
         {
             startScale = endScale;
             transform.parent = startParent;
             endScale = transform.localScale;
             base.OnExiting();
         }
References Juniper.Unity.Animation.SpiralTransition.endScale, Juniper.Unity.Animation.SpiralTransition.startParent, and Juniper.Unity.Animation.SpiralTransition.startScale.
RenderValue()
override void Juniper.Unity.Animation.SpiralTransition.RenderValue (float value) inline protected virtual
Records the transition value so the Update function can use it.
Parameters
value Value.
Implements Juniper.Unity.Animation.AbstractTransitionController.
Definition at line 89 of file SpiralTransition.cs.
         {
             tweenValue = value;
         }
References Juniper.Unity.Animation.SpiralTransition.tweenValue.
SkipEnter()
override void Juniper.Unity.Animation.AbstractTransitionController.SkipEnter () inline virtual inherited
Jump the transition to the ENTERED state, without animating through the ENTERING state.
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 73 of file AbstractTransitionController.cs.
         {
             StartTransition(Direction.Forward);
             base.SkipEnter();
             SetProgress(0);
         }
References Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut().
SkipExit()
virtual void Juniper.Unity.AbstractStateController.SkipExit () inline virtual inherited
Jump to the fully entered state without firing any events.
Definition at line 252 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.Unity.AbstractStateController.lastState, Juniper.Unity.AbstractStateController.OnExiting(), Juniper.Unity.AbstractStateController.skipEvents, Juniper.Unity.AbstractStateController.state, and Juniper.Unity.AbstractStateController.Update().
Update()
override void Juniper.Unity.Animation.SpiralTransition.Update () inline virtual
Continuously update the location, rotation, and scale of the element.
Reimplemented from Juniper.Unity.Animation.AbstractTransitionController.
Definition at line 63 of file SpiralTransition.cs.
         {
             base.Update();
             if (fullScreen)
             {
                 var mid = DisplayManager.MainCamera.ViewportToWorldPoint(Vector3.forward);
                 var top = DisplayManager.MainCamera.ViewportToWorldPoint(new Vector3(0, 1, 1));
                 var delta = top - mid;
                 mid *= 0.5f / delta.magnitude;
                 distance = mid.magnitude * 0.975f;
             }
             var rotationStart = startParent.rotation * Quaternion.Euler(startOrientation);
             var rotationEnd = camT.rotation * Quaternion.Euler(endOrientation);
             var endPosition = camT.position + distance * camT.forward;
             transform.rotation = Quaternion.Slerp(rotationStart, rotationEnd, tweenValue);
             transform.position = Vector3.Lerp(startPosition, endPosition, tweenValue);
             transform.localScale = Vector3.Lerp(startScale, endScale, tweenValue);
         }
References Juniper.Unity.Animation.SpiralTransition.camT, Juniper.Unity.Animation.SpiralTransition.distance, Juniper.Unity.Animation.SpiralTransition.endOrientation, Juniper.Unity.Animation.SpiralTransition.endScale, Juniper.Unity.Animation.SpiralTransition.fullScreen, Juniper.Unity.Display.AbstractDisplayManager.MainCamera, Juniper.Unity.Animation.SpiralTransition.startOrientation, Juniper.Unity.Animation.SpiralTransition.startParent, Juniper.Unity.Animation.SpiralTransition.startPosition, Juniper.Unity.Animation.SpiralTransition.startScale, and Juniper.Unity.Animation.SpiralTransition.tweenValue.
Member Data Documentation
attackTime
float Juniper.Unity.Animation.AbstractTransitionController.attackTime inherited
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 18 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
camT
Transform Juniper.Unity.Animation.SpiralTransition.camT private
The camera, cached for faster access.
Definition at line 141 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.Awake(), and Juniper.Unity.Animation.SpiralTransition.Update().
distance
float Juniper.Unity.Animation.SpiralTransition.distance = 0.2f
The distance from the camera at which the element should stop when the transition has finished entering. The value entered in the Editor for this field is ignored if fullScreen is set to true.
Definition at line 34 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.Update().
endOrientation
Vector3 Juniper.Unity.Animation.SpiralTransition.endOrientation = 90 * Vector3.back
The local rotation of the element when it is parented tracking the camera.
Definition at line 20 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.Update().
endScale
Vector3 Juniper.Unity.Animation.SpiralTransition.endScale private
The scale of the element at the end of the enter transition, or the start of the exit transition.
Definition at line 136 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.OnEntering(), Juniper.Unity.Animation.SpiralTransition.OnExiting(), and Juniper.Unity.Animation.SpiralTransition.Update().
fullScreen
bool Juniper.Unity.Animation.SpiralTransition.fullScreen = true
Set to true if the transition is being used to make a video appear as if it is full-screen. The distance field will automatically be calculated to make the extents of the video fill the viewport.
Definition at line 27 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.Update().
length
float Juniper.Unity.Animation.SpiralTransition.length = 1
The amount of time, in seconds, that the transition should take.
Definition at line 39 of file SpiralTransition.cs.
onEntered
UnityEvent Juniper.Unity.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 33 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.Unity.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 24 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.Unity.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 51 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.Unity.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 42 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
onValueChanged
UnityEvent Juniper.Unity.Animation.AbstractTransitionController.onValueChanged = new UnityEvent() inherited
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 31 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
releaseTime
float Juniper.Unity.Animation.AbstractTransitionController.releaseTime inherited
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 25 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
startOrientation
Vector3 Juniper.Unity.Animation.SpiralTransition.startOrientation = 90 * Vector3.right
The local rotation of the element when sitting in its original parent.
Definition at line 15 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.Update().
startParent
Transform Juniper.Unity.Animation.SpiralTransition.startParent private
The object under which the element originally started.
Definition at line 121 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.OnEntering(), Juniper.Unity.Animation.SpiralTransition.OnExiting(), and Juniper.Unity.Animation.SpiralTransition.Update().
startPosition
Vector3 Juniper.Unity.Animation.SpiralTransition.startPosition private
The position at which the element started.
Definition at line 126 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.OnEntering(), and Juniper.Unity.Animation.SpiralTransition.Update().
startScale
Vector3 Juniper.Unity.Animation.SpiralTransition.startScale private
The scale of the element at the start of the enter transition, or the end of the exit transition.
Definition at line 131 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.OnEntering(), Juniper.Unity.Animation.SpiralTransition.OnExiting(), and Juniper.Unity.Animation.SpiralTransition.Update().
state
Direction Juniper.Unity.AbstractStateController.state inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 94 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), Juniper.Unity.Animation.AbstractTransitionController.Update(), and Juniper.Unity.AbstractStateController.Update().
tween
TweenType Juniper.Unity.Animation.AbstractTransitionController.tween inherited
The method to use to pre-compute the transition value.
Definition at line 36 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
tweenK
float Juniper.Unity.Animation.AbstractTransitionController.tweenK inherited
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 43 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
tweenValue
float Juniper.Unity.Animation.SpiralTransition.tweenValue private
The current transition state value, cached so the location and rotation can change with the camera after the transition has finished.
Definition at line 147 of file SpiralTransition.cs.
Referenced by Juniper.Unity.Animation.SpiralTransition.RenderValue(), and Juniper.Unity.Animation.SpiralTransition.Update().
Property Documentation
IsComplete
virtual bool Juniper.Unity.AbstractStateController.IsComplete get inherited
Returns true when state is Direction.Stopped
Definition at line 110 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.HasCompleted(), and Juniper.Unity.AbstractStateController.Update().
IsEntered
bool Juniper.Unity.AbstractStateController.IsEntered get inherited
Returns true when the state controller is in the "Entered" state.
Definition at line 141 of file AbstractStateController.cs.
         {
             get
             {
                 return enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Exit().
IsExited
bool Juniper.Unity.AbstractStateController.IsExited get inherited
Returns true when the state controller is in the "Exited" state.
Definition at line 152 of file AbstractStateController.cs.
         {
             get
             {
                 return !enabled;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.Enter().
IsRunning
bool Juniper.Unity.AbstractStateController.IsRunning get inherited
Returns true when state is not Direction.Stopped
Definition at line 130 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
TransitionLength
override float Juniper.Unity.Animation.SpiralTransition.TransitionLength get
The amount of time, in seconds, that the transition should take.
Definition at line 45 of file SpiralTransition.cs.
         {
             get
             {
                 return length;
             }
         }
Waiter
WaitUntil Juniper.Unity.AbstractStateController.Waiter get inherited
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 329 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.Unity.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 69 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.Unity.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 60 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.Unity.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 87 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.Unity.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 78 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnExiting().
ValueChanged
EventHandler<ValueChangedEventArgs> Juniper.Unity.Animation.AbstractTransitionController.ValueChanged inherited
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 49 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Animation/SpiralTransition.cs