Juniper: Juniper.AbstractStateController Class Reference
Juniper.AbstractStateController Class Reference
A subscene is a game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
Public Member Functions
bool HasCompleted ()
A method for the IsComplete property to be used with the Waiter object.
virtual void SkipEnter ()
Jump to the fully entered state without firing any events.
virtual void Enter ()
Fire the OnEnable event and perform the Enter transition.
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
virtual void Update ()
Checks to see if the state has changed and fires the right event for it.
virtual void SkipExit ()
Jump to the fully entered state without firing any events.
virtual void Exit ()
Fire the OnExiting event and perform the Exit transition.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Public Attributes
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Direction state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Protected Member Functions
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Properties
virtual bool IsComplete [get]
Returns true when state is Direction.Stopped
bool IsRunning [get]
Returns true when state is not Direction.Stopped
bool IsEntered [get]
Returns true when the state controller is in the "Entered" state.
bool IsExited [get]
Returns true when the state controller is in the "Exited" state.
WaitUntil Waiter [get]
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Events
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Attributes
Direction lastState
The value of state from the last frame, to check for changes in the value.
bool skipEvents
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
WaitUntil _waiter
Cached wait object, so we don't cause GC pressure recreating it all the time.
Detailed Description
A subscene is a game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
Definition at line 17 of file AbstractStateController.cs.
Member Function Documentation
Enter()
virtual void Juniper.AbstractStateController.Enter () inline virtual
Fire the OnEnable event and perform the Enter transition.
Reimplemented in Juniper.Animation.AbstractTransitionController, and Juniper.SubSceneController.
Definition at line 179 of file AbstractStateController.cs.
         {
             if (IsExited)
             {
                 state = Direction.Forward;
                 enabled = true;
                 this.SetTreeActive(true);
             }
         }
References Juniper.AbstractStateController.IsExited, and Juniper.AbstractStateController.state.
Exit()
virtual void Juniper.AbstractStateController.Exit () inline virtual
Fire the OnExiting event and perform the Exit transition.
Reimplemented in Juniper.Animation.AbstractTransitionController, and Juniper.SubSceneController.
Definition at line 269 of file AbstractStateController.cs.
         {
             if (IsEntered)
             {
                 state = Direction.Reverse;
                 OnExiting();
             }
         }
References Juniper.AbstractStateController.IsEntered, Juniper.AbstractStateController.OnExiting(), and Juniper.AbstractStateController.state.
HasCompleted()
bool Juniper.AbstractStateController.HasCompleted () inline
A method for the IsComplete property to be used with the Waiter object.
Returns
Definition at line 123 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.AbstractStateController.IsComplete.
OnDisable()
void Juniper.AbstractStateController.OnDisable () inline
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 300 of file AbstractStateController.cs.
         {
             OnExited();
         }
References Juniper.AbstractStateController.OnExited().
OnEnable()
void Juniper.AbstractStateController.OnEnable () inline
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntering method.
Definition at line 195 of file AbstractStateController.cs.
         {
             OnEntering();
         }
References Juniper.AbstractStateController.OnEntering().
Referenced by Juniper.AbstractStateController.SkipEnter().
OnEntered()
virtual void Juniper.AbstractStateController.OnEntered () inline protected virtual
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Animation.FadeTransition.
Definition at line 242 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntered?.Invoke();
                 Entered?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entered, Juniper.AbstractStateController.onEntered, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.AbstractStateController.Update().
OnEntering()
virtual void Juniper.AbstractStateController.OnEntering () inline protected virtual
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Reimplemented in Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 206 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onEntering?.Invoke();
                 Entering?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Entering, Juniper.AbstractStateController.onEntering, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.AbstractStateController.OnEnable().
OnExited()
virtual void Juniper.AbstractStateController.OnExited () inline protected virtual
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Reimplemented in Juniper.Animation.FadeTransition, and Juniper.SubSceneController.
Definition at line 312 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExited?.Invoke();
                 Exited?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Exited, Juniper.AbstractStateController.onExited, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.AbstractStateController.OnDisable().
OnExiting()
virtual void Juniper.AbstractStateController.OnExiting () inline protected virtual
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented in Juniper.Animation.FadeTransition, Juniper.Animation.SpiralTransition, and Juniper.Widgets.VideoVader.
Definition at line 285 of file AbstractStateController.cs.
         {
             if (!skipEvents)
             {
                 onExiting?.Invoke();
                 Exiting?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.AbstractStateController.Exiting, Juniper.AbstractStateController.onExiting, and Juniper.AbstractStateController.skipEvents.
Referenced by Juniper.AbstractStateController.Exit(), and Juniper.AbstractStateController.SkipExit().
SkipEnter()
virtual void Juniper.AbstractStateController.SkipEnter () inline virtual
Jump to the fully entered state without firing any events.
Reimplemented in Juniper.Animation.AbstractTransitionController.
Definition at line 164 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Forward;
             OnEnable();
             lastState = Direction.Forward;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.AbstractStateController.lastState, Juniper.AbstractStateController.OnEnable(), Juniper.AbstractStateController.skipEvents, Juniper.AbstractStateController.state, and Juniper.AbstractStateController.Update().
SkipExit()
virtual void Juniper.AbstractStateController.SkipExit () inline virtual
Jump to the fully entered state without firing any events.
Definition at line 254 of file AbstractStateController.cs.
         {
             skipEvents = true;
             lastState = Direction.Stopped;
             state = Direction.Reverse;
             OnExiting();
             lastState = Direction.Reverse;
             state = Direction.Stopped;
             Update();
             skipEvents = false;
         }
References Juniper.AbstractStateController.lastState, Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.skipEvents, Juniper.AbstractStateController.state, and Juniper.AbstractStateController.Update().
Update()
virtual void Juniper.AbstractStateController.Update () inline virtual
Checks to see if the state has changed and fires the right event for it.
Reimplemented in Juniper.Video.Video360, Juniper.Animation.AbstractTransitionController, Juniper.Animation.SpiralTransition, and Juniper.SubSceneController.
Definition at line 218 of file AbstractStateController.cs.
         {
             if (IsComplete && state != lastState)
             {
                 if (lastState == Direction.Forward)
                 {
                     OnEntered();
                 }
                 else if (lastState == Direction.Reverse)
                 {
                     enabled = false;
                 }
             }
             lastState = state;
         }
References Juniper.AbstractStateController.IsComplete, Juniper.AbstractStateController.lastState, Juniper.AbstractStateController.OnEntered(), and Juniper.AbstractStateController.state.
Referenced by Juniper.AbstractStateController.SkipEnter(), and Juniper.AbstractStateController.SkipExit().
Member Data Documentation
_waiter
WaitUntil Juniper.AbstractStateController._waiter private
Cached wait object, so we don't cause GC pressure recreating it all the time.
Definition at line 324 of file AbstractStateController.cs.
lastState
Direction Juniper.AbstractStateController.lastState private
The value of state from the last frame, to check for changes in the value.
Definition at line 101 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), and Juniper.AbstractStateController.Update().
onEntered
UnityEvent Juniper.AbstractStateController.onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 35 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.AbstractStateController.onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 26 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.AbstractStateController.onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 53 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.AbstractStateController.onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 44 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExiting().
skipEvents
bool Juniper.AbstractStateController.skipEvents private
Used to avoid firing the status update events for the SkipEnter/SkipExit functions.
Definition at line 106 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered(), Juniper.AbstractStateController.OnEntering(), Juniper.AbstractStateController.OnExited(), Juniper.AbstractStateController.OnExiting(), Juniper.AbstractStateController.SkipEnter(), and Juniper.AbstractStateController.SkipExit().
state
Direction Juniper.AbstractStateController.state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 96 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.Enter(), Juniper.AbstractStateController.Exit(), Juniper.Animation.AbstractTransitionController.SetProgress(), Juniper.AbstractStateController.SkipEnter(), Juniper.AbstractStateController.SkipExit(), Juniper.Animation.AbstractTransitionController.StartTransition(), Juniper.SubSceneController.Update(), Juniper.Animation.AbstractTransitionController.Update(), and Juniper.AbstractStateController.Update().
Property Documentation
IsComplete
virtual bool Juniper.AbstractStateController.IsComplete get
Returns true when state is Direction.Stopped
Definition at line 112 of file AbstractStateController.cs.
         {
             get
             {
                 return state == Direction.Stopped;
             }
         }
Referenced by Juniper.AbstractStateController.HasCompleted(), and Juniper.AbstractStateController.Update().
IsEntered
bool Juniper.AbstractStateController.IsEntered get
Returns true when the state controller is in the "Entered" state.
Definition at line 143 of file AbstractStateController.cs.
         {
             get
             {
                 return isActiveAndEnabled;
             }
         }
Referenced by Juniper.AbstractStateController.Exit().
IsExited
bool Juniper.AbstractStateController.IsExited get
Returns true when the state controller is in the "Exited" state.
Definition at line 154 of file AbstractStateController.cs.
         {
             get
             {
                 return !isActiveAndEnabled;
             }
         }
Referenced by Juniper.AbstractStateController.Enter().
IsRunning
bool Juniper.AbstractStateController.IsRunning get
Returns true when state is not Direction.Stopped
Definition at line 132 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.SubSceneController.Update(), and Juniper.Animation.AbstractTransitionController.Update().
Waiter
WaitUntil Juniper.AbstractStateController.Waiter get
Retrieves a cached waiter object. The object is cached so we don't cause unnecessary GC pressure. Use it to wait for the transition to run to completion.
Definition at line 331 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(HasCompleted);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.MasterSceneController.LoadingCompleteCoroutine(), Juniper.MasterSceneController.QuitCoroutine(), and Juniper.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.AbstractStateController.Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 71 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnEntered(), and Juniper.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.AbstractStateController.Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 62 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.AbstractStateController.Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 89 of file AbstractStateController.cs.
Referenced by Juniper.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.AbstractStateController.Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 80 of file AbstractStateController.cs.
Referenced by Juniper.Animation.FadeTransition.Awake(), and Juniper.AbstractStateController.OnExiting().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/AbstractStateController.cs