Juniper: BitMiracle.LibJpeg.Classic.JVirtArray< T > Class Template Reference
BitMiracle.LibJpeg.Classic.JVirtArray< T > Class Template Reference
JPEG virtual array.
Public Member Functions
T [][] Access (int startRow, int numberOfRows)
Access the part of a virtual array.
Properties
JpegCommonStruct ErrorProcessor [get, set]
Gets or sets the error processor.
Private Member Functions
internal delegate T [][] Allocator (int width, int height)
internal JVirtArray (int width, int height, Allocator allocator)
Request a virtual 2-D array
Private Attributes
readonly T [][] buffer
Detailed Description
JPEG virtual array.
Template Parameters
T The type of array's elements.
You can't create virtual array manually. For creation use methods JpegCommonStruct.CreateSamplesArray and JpegCommonStruct.CreateBlocksArray.
Definition at line 29 of file JVirtArray.cs.
Constructor & Destructor Documentation
JVirtArray()
internal BitMiracle.LibJpeg.Classic.JVirtArray< T >.JVirtArray (int width, int height, Allocator allocator) inline private
Request a virtual 2-D array
Parameters
width Width of array
height Total virtual array height
allocator The allocator.
Definition at line 41 of file JVirtArray.cs.
         {
             ErrorProcessor = null;
             buffer = allocator(width, height);
             Debug.Assert(buffer is object);
         }
Member Function Documentation
Access()
T [][] BitMiracle.LibJpeg.Classic.JVirtArray< T >.Access (int startRow, int numberOfRows) inline
Access the part of a virtual array.
Parameters
startRow The first row in required block.
numberOfRows The number of required rows.
Returns
The required part of virtual array.
Definition at line 66 of file JVirtArray.cs.
         {
             /* debugging check */
             if (startRow + numberOfRows > buffer.Length)
             {
                 if (ErrorProcessor is object)
                 {
                     ErrorProcessor.ErrExit(JMessageCode.JERR_BAD_VIRTUAL_ACCESS);
                 }
                 else
                 {
                     throw new InvalidOperationException("Bogus virtual array access");
                 }
             }
             /* Return proper part of the buffer */
             var ret = new T[numberOfRows][];
             for (var i = 0; i < numberOfRows; i++)
             {
                 ret[i] = buffer[startRow + i];
             }
             return ret;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcess2Pass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessPrepass(), and BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass().
Allocator()
internal delegate T [][] BitMiracle.LibJpeg.Classic.JVirtArray< T >.Allocator (int width, int height) private
Member Data Documentation
buffer
readonly T [][] BitMiracle.LibJpeg.Classic.JVirtArray< T >.buffer private
Definition at line 33 of file JVirtArray.cs.
Referenced by BitMiracle.LibJpeg.Classic.JVirtArray< BitMiracle.LibJpeg.Classic.JBlock >.Access(), and BitMiracle.LibJpeg.Classic.JVirtArray< BitMiracle.LibJpeg.Classic.JBlock >.JVirtArray().
Property Documentation
ErrorProcessor
JpegCommonStruct BitMiracle.LibJpeg.Classic.JVirtArray< T >.ErrorProcessor get set
Gets or sets the error processor.
The error processor.
Default value: null
Uses only for calling jpeg_common_struct.ERREXIT on error.
Definition at line 58 of file JVirtArray.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.JVirtArray< BitMiracle.LibJpeg.Classic.JBlock >.Access(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), and BitMiracle.LibJpeg.Classic.JVirtArray< BitMiracle.LibJpeg.Classic.JBlock >.JVirtArray().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/JVirtArray.cs