Juniper: Juniper.World.LightEstimation.AbstractLightEstimate Class Reference
Juniper.World.LightEstimation.AbstractLightEstimate Class Reference
Public Member Functions
void Awake ()
Retrieves the light to which this component is attached, and makes sure there is a LightMeasurement component attached.
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void Install (bool reset)
Install, with or without a full reset.
void Uninstall ()
Remove platform-specific features from the object.
Public Attributes
bool SetAmbientLight = true
When set to true, the lighting estimate will modify the global ambient light setting for the scene.
float ambientScale = 1f
When SetAmbientLight is true, scales the ambient light intensity estimate to control the brightness of the overall scene.
bool SetDirectionalLight = true
When set to true, the lighting estimate will modify the intensity and direction of the Light on which this component is attached.
float directionalScale = 1f
When SetDirectionalLight is set to true, scales the directional light intensity estimate to control the brightness of incident light and cast shadows.
float shadowScale = 1f
This value scales the shadow strength estimate, making shadows stronger or lighter, depending on the balance between ambient and directional light.
float CloudCoverScale = 0.5f
This value scales the cloud cover report value, modifying the balance of light between ambient and directional and potentially softening shadows.
bool DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Protected Member Functions
float RampIntensity (float rawIntensityEstimate)
Raw intensity values need to be ramped to make sense as a Unity scene light intensity value.
virtual void Update ()
Applies the light estimation process, and optionally prints a debug report.
Protected Attributes
Light sun
The light to which this component is attached.
LightMeasurement measurement
The AR subsystem for measuring light strength in a camera frame.
Static Protected Attributes
static Vector3 overhead = new Vector3(90, 0, 0)
A static orientation for the straight above zenith.
Properties
abstract float CloudCover [get]
Gets the estimated cloud cover.
abstract bool HasSunRotation [get]
Defaults to false. Overriding classes can indicate they have a rotation value to make the base class update the sun light's rotation value. Otherwise, it will not be modified from whatever the user set in the Unity Editor.
abstract Vector3 SunRotation [get]
Gets a rotation quaternion that will put the "sun dot" of Unity's default skybox into the correct position in the sky.
Private Member Functions
void PrintDebugReport (float ambientIntensity, Color ambientColor, float directionalIntensity, Color directionalColor, float shadowStrength)
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Detailed Description
Definition at line 7 of file AbstractLightEstimate.cs.
Member Function Documentation
Awake()
void Juniper.World.LightEstimation.AbstractLightEstimate.Awake () inline
Retrieves the light to which this component is attached, and makes sure there is a LightMeasurement component attached.
Definition at line 124 of file AbstractLightEstimate.cs.
         {
             Install(false);
         }
References Juniper.World.LightEstimation.AbstractLightEstimate.Install().
Install()
virtual void Juniper.World.LightEstimation.AbstractLightEstimate.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.World.LightEstimation.OutdoorLightEstimate.
Definition at line 143 of file AbstractLightEstimate.cs.
         {
             sun = GetComponent<Light>();
 #if UNITY_EDITOR
             if (reset)
             {
                 name = "Sun";
                 sun.type = LightType.Directional;
                 sun.shadows = LightShadows.Soft;
                 sun.lightmapBakeType = LightmapBakeType.Mixed;
                 RenderSettings.sun = sun;
                 var sunRig = transform.parent;
                 if (sunRig == null)
                 {
                     sunRig = new GameObject().transform;
                     transform.SetParent(sunRig, false);
                 }
                 sunRig.name = "SunRig";
                 sunRig.Ensure<CompassRose>();
             }
 #endif
             this.Ensure<GPSLocation>();
             this.Ensure<SunPosition>();
             this.Ensure<LightMeasurement>();
             measurement = this.Ensure<LightMeasurement>();
         }
References Juniper.World.LightEstimation.AbstractLightEstimate.measurement, and Juniper.World.LightEstimation.AbstractLightEstimate.sun.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Awake(), and Juniper.World.LightEstimation.AbstractLightEstimate.Reinstall().
PrintDebugReport()
void Juniper.World.LightEstimation.AbstractLightEstimate.PrintDebugReport (float ambientIntensity, Color ambientColor, float directionalIntensity, Color directionalColor, float shadowStrength) inline private
If DebugReport is set to true, prints a report that displays the status of the component and the values it is using for the light estimation.
Parameters
ambientIntensity Ambient intensity.
ambientColor Ambient color.
directionalIntensity Directional intensity.
directionalColor Directional color.
shadowStrength Shadow strength.
Definition at line 238 of file AbstractLightEstimate.cs.
         {
             if (measurement == null)
             {
                 ScreenDebugger.Print("  no light measurement");
             }
             ScreenDebugger.Print($"  Sun Position: <{SunRotation.x.Label(UnitOfMeasure.Degrees, 4)}, {SunRotation.y.Label(UnitOfMeasure.Degrees, 4)}, {SunRotation.z.Label(UnitOfMeasure.Degrees, 4)}>");
             ScreenDebugger.PrintFormat("  Ambient: int {0:0.000} col {1}", ambientIntensity, ambientColor);
             ScreenDebugger.PrintFormat("  Directional: int {0:0.000} col {1}", directionalIntensity, directionalColor);
             ScreenDebugger.PrintFormat("  Shadow strength: {0:0.000}", shadowStrength);
             if (sun == null)
             {
                 ScreenDebugger.Print("  no directional light");
             }
             else
             {
                 ScreenDebugger.Print($"  sun orientation: {sun.transform.eulerAngles}");
             }
         }
References Juniper.World.LightEstimation.AbstractLightEstimate.measurement, System.ScreenDebugger.Print(), System.ScreenDebugger.PrintFormat(), and Juniper.World.LightEstimation.AbstractLightEstimate.sun.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
RampIntensity()
float Juniper.World.LightEstimation.AbstractLightEstimate.RampIntensity (float rawIntensityEstimate) inline protected
Raw intensity values need to be ramped to make sense as a Unity scene light intensity value.
Returns
The intensity.
Parameters
rawIntensityEstimate Raw intensity estimate.
Definition at line 100 of file AbstractLightEstimate.cs.
         {
             const float linearRampThreshold = 0.8f;
             const float middleGray = 0.18f;
             const float inclination = 0.4f;
             const float beta = (linearRampThreshold / inclination) - 1.0f;
             const float alpha = (beta + 1.0f) / beta * linearRampThreshold;
             var normalizedIntensity = rawIntensityEstimate / middleGray;
             if (normalizedIntensity < 1.0f)
             {
                 return normalizedIntensity * linearRampThreshold;
             }
             else
             {
                 return alpha * (1.0f - (1.0f / ((beta * normalizedIntensity) + 1.0f)));
             }
         }
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
Reinstall()
virtual void Juniper.World.LightEstimation.AbstractLightEstimate.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 129 of file AbstractLightEstimate.cs.
         {
             Install(true);
         }
References Juniper.World.LightEstimation.AbstractLightEstimate.Install().
Uninstall()
void Juniper.World.LightEstimation.AbstractLightEstimate.Uninstall () inline
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 175 of file AbstractLightEstimate.cs.
         {
         }
Update()
virtual void Juniper.World.LightEstimation.AbstractLightEstimate.Update () inline protected virtual
Applies the light estimation process, and optionally prints a debug report.
Reimplemented in Juniper.World.LightEstimation.OutdoorLightEstimate.
Definition at line 182 of file AbstractLightEstimate.cs.
         {
             float hue, sat;
             Color.RGBToHSV(measurement.ColorEstimate, out hue, out sat, out _);
             var rampedIntensity = RampIntensity(measurement.IntensityEstimate);
             var cloudCover = CloudCover * CloudCoverScale * 2;
             var ambientIntensityEstimate = cloudCover * rampedIntensity;
             var directionalIntensityEstimate = (1 - cloudCover) * rampedIntensity;
             var ambientIntensity = ambientScale * ambientIntensityEstimate;
             var ambientColor = Color.HSVToRGB(hue, sat, ambientIntensity);
             var directionalIntensity = directionalScale * directionalIntensityEstimate;
             var directionalColor = Color.HSVToRGB(hue, sat, directionalIntensity);
             var shadowStrength = Mathf.Clamp(shadowScale * directionalIntensityEstimate * (1 - ambientIntensityEstimate), 0f, 1f);
             if (SetDirectionalLight && sun != null && (!sun.gameObject.isStatic || !Application.isPlaying))
             {
                 if (!Application.isPlaying)
                 {
                     sun.color = directionalColor;
                     sun.intensity = directionalIntensity;
                     sun.shadowStrength = shadowStrength;
                 }
                 if (HasSunRotation)
                 {
                     sun.transform.localRotation = Quaternion.Euler(SunRotation);
                 }
             }
             if (SetAmbientLight)
             {
                 RenderSettings.ambientLight = ambientColor;
                 RenderSettings.ambientIntensity = ambientIntensity;
             }
             Shader.SetGlobalFloat("_GlobalLightEstimation", ambientIntensityEstimate);
             if (DebugReport)
             {
                 PrintDebugReport(ambientIntensity, ambientColor, directionalIntensity, directionalColor, shadowStrength);
             }
         }
References Juniper.World.LightEstimation.AbstractLightEstimate.ambientScale, Juniper.World.LightEstimation.AbstractLightEstimate.CloudCover, Juniper.World.LightEstimation.AbstractLightEstimate.CloudCoverScale, Juniper.World.LightEstimation.AbstractLightMeasurement.ColorEstimate, Juniper.World.LightEstimation.AbstractLightEstimate.DebugReport, Juniper.World.LightEstimation.AbstractLightEstimate.directionalScale, Juniper.World.LightEstimation.AbstractLightEstimate.HasSunRotation, Juniper.World.LightEstimation.AbstractLightMeasurement.IntensityEstimate, Juniper.World.LightEstimation.AbstractLightEstimate.measurement, Juniper.World.LightEstimation.AbstractLightEstimate.PrintDebugReport(), Juniper.World.LightEstimation.AbstractLightEstimate.RampIntensity(), Juniper.World.LightEstimation.AbstractLightEstimate.SetAmbientLight, Juniper.World.LightEstimation.AbstractLightEstimate.SetDirectionalLight, Juniper.World.LightEstimation.AbstractLightEstimate.shadowScale, Juniper.World.LightEstimation.AbstractLightEstimate.sun, and Juniper.World.LightEstimation.AbstractLightEstimate.SunRotation.
Member Data Documentation
ambientScale
float Juniper.World.LightEstimation.AbstractLightEstimate.ambientScale = 1f
When SetAmbientLight is true, scales the ambient light intensity estimate to control the brightness of the overall scene.
Definition at line 18 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
CloudCoverScale
float Juniper.World.LightEstimation.AbstractLightEstimate.CloudCoverScale = 0.5f
This value scales the cloud cover report value, modifying the balance of light between ambient and directional and potentially softening shadows.
Definition at line 43 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
DebugReport
bool Juniper.World.LightEstimation.AbstractLightEstimate.DebugReport
When set to true, the Update loop will include printing out the internal values of the component;
Definition at line 48 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.OutdoorLightEstimate.Update(), and Juniper.World.LightEstimation.AbstractLightEstimate.Update().
directionalScale
float Juniper.World.LightEstimation.AbstractLightEstimate.directionalScale = 1f
When SetDirectionalLight is set to true, scales the directional light intensity estimate to control the brightness of incident light and cast shadows.
Definition at line 30 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
measurement
LightMeasurement Juniper.World.LightEstimation.AbstractLightEstimate.measurement protected
The AR subsystem for measuring light strength in a camera frame.
Definition at line 63 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Install(), Juniper.World.LightEstimation.AbstractLightEstimate.PrintDebugReport(), and Juniper.World.LightEstimation.AbstractLightEstimate.Update().
overhead
Vector3 Juniper.World.LightEstimation.AbstractLightEstimate.overhead = new Vector3(90, 0, 0) static protected
A static orientation for the straight above zenith.
Definition at line 53 of file AbstractLightEstimate.cs.
SetAmbientLight
bool Juniper.World.LightEstimation.AbstractLightEstimate.SetAmbientLight = true
When set to true, the lighting estimate will modify the global ambient light setting for the scene.
Definition at line 12 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
SetDirectionalLight
bool Juniper.World.LightEstimation.AbstractLightEstimate.SetDirectionalLight = true
When set to true, the lighting estimate will modify the intensity and direction of the Light on which this component is attached.
Definition at line 24 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
shadowScale
float Juniper.World.LightEstimation.AbstractLightEstimate.shadowScale = 1f
This value scales the shadow strength estimate, making shadows stronger or lighter, depending on the balance between ambient and directional light.
Definition at line 36 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
sun
Light Juniper.World.LightEstimation.AbstractLightEstimate.sun protected
The light to which this component is attached.
Definition at line 58 of file AbstractLightEstimate.cs.
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Install(), Juniper.World.LightEstimation.AbstractLightEstimate.PrintDebugReport(), and Juniper.World.LightEstimation.AbstractLightEstimate.Update().
Property Documentation
CloudCover
abstract float Juniper.World.LightEstimation.AbstractLightEstimate.CloudCover get protected
Gets the estimated cloud cover.
The cloud cover.
Definition at line 70 of file AbstractLightEstimate.cs.
         {
             get;
         }
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
HasSunRotation
abstract bool Juniper.World.LightEstimation.AbstractLightEstimate.HasSunRotation get protected
Defaults to false. Overriding classes can indicate they have a rotation value to make the base class update the sun light's rotation value. Otherwise, it will not be modified from whatever the user set in the Unity Editor.
true if has sun rotation; otherwise, false.
Definition at line 81 of file AbstractLightEstimate.cs.
         {
             get;
         }
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
SunRotation
abstract Vector3 Juniper.World.LightEstimation.AbstractLightEstimate.SunRotation get protected
Gets a rotation quaternion that will put the "sun dot" of Unity's default skybox into the correct position in the sky.
The sun rotation.
Definition at line 91 of file AbstractLightEstimate.cs.
         {
             get;
         }
Referenced by Juniper.World.LightEstimation.AbstractLightEstimate.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/LightEstimation/AbstractLightEstimate.cs