Juniper: UnityEngine.ComponentExt Class Reference
UnityEngine.ComponentExt Class Reference
Extension methods for Unity's Component class.
Static Public Member Functions
static void WithLock (this Component src, Action act)
ARCore looks for certain things as soon as the component is enabled, so we have to delay it. First, we disable the object hierarchy in question. Then, we execute the code to create the ARCore objects. Finally, we re-enable the hierarchy.
static bool IsActivated (this Component parent)
Check to see if a component is valid (not-null) and activated.
static Task< bool > IsActivatedAsync (this Component parent)
static void SetTreeActive (this Component parent, bool active)
Set the active state for the whole hierarchy from an object on up through its parent transforms. Useful for making absolutely sure a particular object is activated.
static void SetActive (this Component parent, bool active)
Set the active state for the GameObject of any particular Component. Just a useful shortcut.
static Task SetActiveAsync (this Component parent, bool active)
static void Activate (this Component parent)
A shortcut for
static Task ActivateAsync (this Component parent)
static void Deactivate (this Component parent)
A shortcut for
static Task DeactivateAsync (this Component parent)
static void DestroyImmediate (this Object obj)
static void Destroy (this Object obj)
static T Query< T > (this Component parent, string path)
static Transform Query (this Component parent, string path)
Search through a series of Transforms and child transforms, defined as a set of forward-slash delimited names. Use ".." to select the parent transform.
static bool GetVisible (this Component parent)
Check to see if an object is associated with an active renderer.
static void SetVisible (this Component parent, bool visible)
For any renderers on the parent , sets its enabled property to visible . For any child transforms, calls SetActive(Component, bool) with visible as the value.
static bool HasComponent< T > (this Component parent)
static PooledComponent< T > Ensure< T > (this Component obj, Predicate< T > predicate)
Attempts to get a component of type T from obj . If one is not available, this function creates one on the gameObject and returns that.
static PooledComponent< T > Ensure< T > (this Component obj)
static PooledComponent< Transform > EnsureParent (this Component obj, string name, Transform skip)
static bool Remove< T > (this Component obj)
Checks to see if a gameObject has a particular component and, if it does, destroys it.
static PooledComponent< T > Ensure< T > (this Component obj, string path, string creationPath, Func< GameObject > create)
Fill in a path of Transforms with other Transforms as necessary. Useful for creating complex Transform hierarchies very quickly.
static PooledComponent< T > Ensure< T > (this Component obj, string path, string creationPath)
static PooledComponent< T > Ensure< T > (this Component obj, string path, Func< GameObject > create)
Fill in a path of Transforms with other Transforms as necessary. Useful for creating complex Transform hierarchies very quickly.
static PooledComponent< T > Ensure< T > (this Component obj, string path)
static string GetRelativeName (this Component child, Component root)
static string GetZoneName (this Component child)
static bool IsInZone (this Component child, string zoneName)
Detailed Description
Extension methods for Unity's Component class.
Definition at line 14 of file ComponentExt.cs.
Member Function Documentation
Activate()
static void UnityEngine.ComponentExt.Activate (this Component parent) inline static
A shortcut for
SetActive(true) . Also useful for feeding to higher-order functions that expect parameterless functions.
Parameters
parent Parent.
Definition at line 78 of file ComponentExt.cs.
         {
             parent.gameObject.Activate();
         }
ActivateAsync()
static Task UnityEngine.ComponentExt.ActivateAsync (this Component parent) inline static
Definition at line 83 of file ComponentExt.cs.
         {
             return JuniperSystem.OnMainThreadAsync(parent.Activate);
         }
References Juniper.JuniperSystem.OnMainThreadAsync().
Deactivate()
static void UnityEngine.ComponentExt.Deactivate (this Component parent) inline static
A shortcut for
SetActive(false) . Also useful for feeding to higher-order functions that expect parameterless functions.
Parameters
parent Parent.
Definition at line 96 of file ComponentExt.cs.
         {
             parent.gameObject.Deactivate();
         }
DeactivateAsync()
static Task UnityEngine.ComponentExt.DeactivateAsync (this Component parent) inline static
Definition at line 101 of file ComponentExt.cs.
         {
             return JuniperSystem.OnMainThreadAsync(parent.Deactivate);
         }
References Juniper.JuniperSystem.OnMainThreadAsync().
Destroy()
static void UnityEngine.ComponentExt.Destroy (this Object obj) inline static
Definition at line 111 of file ComponentExt.cs.
         {
             Object.Destroy(obj);
         }
DestroyImmediate()
static void UnityEngine.ComponentExt.DestroyImmediate (this Object obj) inline static
Definition at line 106 of file ComponentExt.cs.
         {
             Object.DestroyImmediate(obj);
         }
Ensure< T >() [1/6]
static PooledComponent<T> UnityEngine.ComponentExt.Ensure< T > (this Component obj, Predicate< T > predicate) inline static
Attempts to get a component of type T from obj . If one is not available, this function creates one on the gameObject and returns that.
Returns
The component.
Parameters
obj Object.
Template Parameters
T A subclass of type Component.
Type Constraints
T : Component
Definition at line 251 of file ComponentExt.cs.
                                                                                                        : Component
         {
             return obj.gameObject.Ensure(predicate);
         }
Ensure< T >() [2/6]
static PooledComponent<T> UnityEngine.ComponentExt.Ensure< T > (this Component obj) inline static
Type Constraints
T : Component
Definition at line 256 of file ComponentExt.cs.
                     : Component
         {
             return obj.gameObject.Ensure<T>();
         }
Ensure< T >() [3/6]
static PooledComponent<T> UnityEngine.ComponentExt.Ensure< T > (this Component obj, string path, string creationPath, Func< GameObject > create) inline static
Fill in a path of Transforms with other Transforms as necessary. Useful for creating complex Transform hierarchies very quickly.
Returns
The transform.
Parameters
obj Object.
path Path.
creationPath
create
Type Constraints
T : Transform
Definition at line 303 of file ComponentExt.cs.
                     : Transform
         {
             if (creationPath == null)
             {
                 creationPath = path;
             }
             var trans = obj.transform.Query(path);
             var isNew = trans == null;
             if (isNew)
             {
                 var parts = creationPath.Split('/');
                 var name = parts.LastOrDefault();
                 if (create == null)
                 {
                     create = () => new GameObject();
                 }
                 trans = create().transform;
                 trans.name = name;
                 Transform parent;
                 if (parts.Length == 1)
                 {
                     parent = obj.transform;
                 }
                 else if (parts.Length == 0 || (parts.Length == 2 && parts[0].Length == 0))
                 {
                     parent = null;
                 }
                 else
                 {
                     var parentPath = string.Join("/", parts
                         .Take(parts.Length - 1)
                         .ToArray());
                     parent = obj.Ensure<T>(parentPath);
                 }
                 trans.SetParent(parent, false);
             }
             return new PooledComponent<T>(trans.gameObject, isNew);
         }
Ensure< T >() [4/6]
static PooledComponent<T> UnityEngine.ComponentExt.Ensure< T > (this Component obj, string path, string creationPath) inline static
Type Constraints
T : Transform
Definition at line 349 of file ComponentExt.cs.
                     : Transform
         {
             return obj.Ensure<T>(path, creationPath, null);
         }
Ensure< T >() [5/6]
static PooledComponent<T> UnityEngine.ComponentExt.Ensure< T > (this Component obj, string path, Func< GameObject > create) inline static
Fill in a path of Transforms with other Transforms as necessary. Useful for creating complex Transform hierarchies very quickly.
Returns
The transform.
Parameters
obj Object.
path Path.
create
Type Constraints
T : Transform
Definition at line 363 of file ComponentExt.cs.
                     : Transform
         {
             return obj.Ensure<T>(path, null, create);
         }
Ensure< T >() [6/6]
static PooledComponent<T> UnityEngine.ComponentExt.Ensure< T > (this Component obj, string path) inline static
Type Constraints
T : Transform
Definition at line 369 of file ComponentExt.cs.
                     : Transform
         {
             return obj.Ensure<T>(path, null, null);
         }
EnsureParent()
static PooledComponent<Transform> UnityEngine.ComponentExt.EnsureParent (this Component obj, string name, Transform skip) inline static
Definition at line 262 of file ComponentExt.cs.
         {
             var parent = obj.transform.parent;
             if (parent == null || parent == skip)
             {
                 parent = new GameObject(name).transform;
                 obj.transform.SetParent(parent, false);
                 return new PooledComponent<Transform>(parent, true);
             }
             else
             {
                 parent.name = name;
                 return new PooledComponent<Transform>(parent, false);
             }
         }
GetRelativeName()
static string UnityEngine.ComponentExt.GetRelativeName (this Component child, Component root) inline static
Definition at line 375 of file ComponentExt.cs.
         {
             var parent = child.transform.parent;
             string transName = child.name;
             while (parent != root.transform)
             {
                 transName = parent.name + "/" + transName;
                 parent = parent.parent;
             }
             return transName;
         }
GetVisible()
static bool UnityEngine.ComponentExt.GetVisible (this Component parent) inline static
Check to see if an object is associated with an active renderer.
Returns
true, if the Component has a sibling Compoent that is an enabled Renderer, false otherwise.
Parameters
parent Parent.
Definition at line 211 of file ComponentExt.cs.
         {
             var r = parent.GetComponent<Renderer>();
             return r != null
                 && r.enabled;
         }
GetZoneName()
static string UnityEngine.ComponentExt.GetZoneName (this Component child) inline static
Definition at line 388 of file ComponentExt.cs.
         {
             return JuniperSystem.OnMainThread(() =>
             {
                 var zone = child.GetComponent<Zone>();
                 if (zone != null)
                 {
                     return zone.zoneName;
                 }
                 else
                 {
                     return null;
                 }
             });
         }
References Juniper.JuniperSystem.OnMainThread(), and Juniper.World.Zone.zoneName.
HasComponent< T >()
static bool UnityEngine.ComponentExt.HasComponent< T > (this Component parent) inline static
Definition at line 239 of file ComponentExt.cs.
         {
             return parent.GetComponent<T>() != null;
         }
IsActivated()
static bool UnityEngine.ComponentExt.IsActivated (this Component parent) inline static
Check to see if a component is valid (not-null) and activated.
Parameters
parent The component to check
Definition at line 34 of file ComponentExt.cs.
         {
             return parent.gameObject.IsActivated();
         }
IsActivatedAsync()
static Task<bool> UnityEngine.ComponentExt.IsActivatedAsync (this Component parent) inline static
Definition at line 39 of file ComponentExt.cs.
         {
             return JuniperSystem.OnMainThreadAsync(parent.IsActivated);
         }
References Juniper.JuniperSystem.OnMainThreadAsync().
IsInZone()
static bool UnityEngine.ComponentExt.IsInZone (this Component child, string zoneName) inline static
Definition at line 404 of file ComponentExt.cs.
         {
             return child.GetZoneName() == zoneName;
         }
Query()
static Transform UnityEngine.ComponentExt.Query (this Component parent, string path) inline static
Search through a series of Transforms and child transforms, defined as a set of forward-slash delimited names. Use ".." to select the parent transform.
Template Parameters
T
Parameters
parent
path
Returns
Definition at line 137 of file ComponentExt.cs.
         {
             var parts = path.Split('/');
             var top = new List<Transform>(5) { parent.transform };
             for (var i = 0; i < parts.Length; ++i)
             {
                 var part = parts[i];
                 if (part != ".")
                 {
                     var next = new List<Transform>(5);
                     foreach (var here in top)
                     {
                         if (here == null)
{
                             next.Add((from scene in MasterSceneController.AllScenes
                                       from gameObject in scene.GetRootGameObjects()
                                       where gameObject.name == part
                                       select gameObject.transform)
                                 .FirstOrDefault());
                         }
                         else if (part == "*")
{
                             next.AddRange(here.Children());
                         }
                         else if (part == "..")
{
                             next.Add(here.parent);
                         }
                         else if (part.Length > 0)
{
                             var child = here.Find(part);
                             if (child != null)
{
                                 next.Add(child);
                             }
                         }
                         else
{
                             next.Add(null);
                         }
                     }
                     if (next.Count == 0 && i < parts.Length - 1)
                     {
                         return null;
                     }
                     else
                     {
                         top = next;
                     }
                 }
             }
             top.RemoveAll(x => x == null);
             if (top.Count > 0)
             {
                 return top[0].transform;
             }
             else
             {
                 return null;
             }
         }
References Juniper.MasterSceneController.AllScenes.
Query< T >()
static T UnityEngine.ComponentExt.Query< T > (this Component parent, string path) inline static
Definition at line 116 of file ComponentExt.cs.
         {
             var trans = parent.Query(path);
             if (trans == null)
             {
                 return default;
             }
             else
             {
                 return trans.GetComponent<T>();
             }
         }
Remove< T >()
static bool UnityEngine.ComponentExt.Remove< T > (this Component obj) inline static
Checks to see if a gameObject has a particular component and, if it does, destroys it.
Returns
true, if component existed to be destroy, false otherwise.
Parameters
obj The gameObject from which to remove the component.
Template Parameters
T A subclass of type Component.
Type Constraints
T : Component
Definition at line 284 of file ComponentExt.cs.
                                                                  : Component
         {
             var o = obj.GetComponent<T>();
             if (o != null)
             {
                 o.DestroyImmediate();
             }
             return o != null;
         }
SetActive()
static void UnityEngine.ComponentExt.SetActive (this Component parent, bool active) inline static
Set the active state for the GameObject of any particular Component. Just a useful shortcut.
Parameters
parent Parent.
active If set to true active.
Definition at line 60 of file ComponentExt.cs.
         {
             parent.gameObject.SetActive(active);
         }
SetActiveAsync()
static Task UnityEngine.ComponentExt.SetActiveAsync (this Component parent, bool active) inline static
Definition at line 65 of file ComponentExt.cs.
         {
             return JuniperSystem.OnMainThreadAsync(() => parent.SetActive(active));
         }
References Juniper.JuniperSystem.OnMainThreadAsync().
SetTreeActive()
static void UnityEngine.ComponentExt.SetTreeActive (this Component parent, bool active) inline static
Set the active state for the whole hierarchy from an object on up through its parent transforms. Useful for making absolutely sure a particular object is activated.
Parameters
parent Parent.
active If set to true active.
Definition at line 50 of file ComponentExt.cs.
         {
             parent.gameObject.SetTreeActive(active);
         }
SetVisible()
static void UnityEngine.ComponentExt.SetVisible (this Component parent, bool visible) inline static
For any renderers on the parent , sets its enabled property to visible . For any child transforms, calls SetActive(Component, bool) with visible as the value.
Parameters
parent
visible
Definition at line 225 of file ComponentExt.cs.
         {
             var r = parent.GetComponent<Renderer>();
             if (r != null)
             {
                 r.enabled = visible;
             }
             foreach (Transform child in parent.transform)
             {
                 child.SetActive(visible);
             }
         }
WithLock()
static void UnityEngine.ComponentExt.WithLock (this Component src, Action act) inline static
ARCore looks for certain things as soon as the component is enabled, so we have to delay it. First, we disable the object hierarchy in question. Then, we execute the code to create the ARCore objects. Finally, we re-enable the hierarchy.
Parameters
src
act
Definition at line 23 of file ComponentExt.cs.
         {
             src.Deactivate();
             act();
             src.Activate();
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Extensions/UnityEngine/ComponentExt.cs