Juniper: Juniper.Data.Zip Class Reference
Juniper.Data.Zip Class Reference
Functions for dealing with Zip files.
Static Public Member Functions
static void GetFile (string zipFile, string filePath, Action< Stream > resolve, Action< Exception > reject, IProgress prog=null)
Retrieves a single file from a zip file.
static void CompressDirectory (string inputDirectory, string outputZipFile, int level, IProgress prog=null, Action< Exception > error=null)
Makes a zip file out of the contents of a directory.
static void DecompressDirectory (string inputZipFile, string outputDirectory, IProgress prog=null, Action< Exception > error=null)
Dump the contents of a zip file out to disk.
static IEnumerable< ZipEntry > ZipEntries (string inputZipFile, IProgress prog=null)
Lists all of the entries (both files and directories) in a zip file.
static IEnumerable< string > RecurseFiles (string inputZipFile, IProgress prog=null)
Lists all of the files in a zip file.
static IEnumerable< string > RecurseDirectories (string inputZipFile, IProgress prog=null)
Lists all of the directories in a zip file.
Static Private Member Functions
static Zip ()
Force SharpZipLib to use any code page that is available on the runtime system, rather than stubbornly insisting on trying to use IBM437, which is only available by default on Windows.
Detailed Description
Functions for dealing with Zip files.
Definition at line 15 of file Zip.cs.
Constructor & Destructor Documentation
Zip()
static Juniper.Data.Zip.Zip () inline static private
Force SharpZipLib to use any code page that is available on the runtime system, rather than stubbornly insisting on trying to use IBM437, which is only available by default on Windows.
Definition at line 22 of file Zip.cs.
         {
             ZipConstants.DefaultCodePage = 0;
         }
Member Function Documentation
CompressDirectory()
static void Juniper.Data.Zip.CompressDirectory (string inputDirectory, string outputZipFile, int level, IProgress prog = null, Action< Exception > error = null) inline static
Makes a zip file out of the contents of a directory.
Parameters
inputDirectory The directory to zip
outputZipFile The filepath of the zip file to create
level The zip compression level to use. Min is 0, max is 9.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
error A callback for any errors that occur. Defaults to null (i.e. no error reporting).
Definition at line 66 of file Zip.cs.
         {
             prog?.Report(0);
             if (Directory.Exists(inputDirectory))
             {
                 using (var fileStream = File.Create(outputZipFile))
                 using (var zipStream = new ZipOutputStream(fileStream))
                 {
                     zipStream.IsStreamOwner = false;
                     // To permit the zip to be unpacked by built-in extractor in WinXP and
                     // Server2003, WinZip 8, Java, and other older code, you need to do one of the
                     // following: Specify UseZip64.Off, or set the Size. If the file may be bigger
                     // than 4GB, or you do not need WinXP built-in compatibility, you do not need
                     // either, but the zip will be in Zip64 format which not all utilities can understand.
                     zipStream.UseZip64 = UseZip64.Off;
                     zipStream.SetLevel(Math.Max(0, Math.Min(9, level)));
                     var baseDirectory = new DirectoryInfo(inputDirectory);
                     var files = baseDirectory.RecurseFiles().ToArray();
                     prog.ForEach(files, (fi, p) =>
                     {
                         var shortName = PathExt.Abs2Rel(fi.FullName, baseDirectory.FullName);
                         var entryName = ZipEntry.CleanName(shortName);
                         var newEntry = new ZipEntry(entryName)
{
                             DateTime = fi.LastWriteTime,
                             Size = fi.Length
                         };
                         zipStream.PutNextEntry(newEntry);
                         using (var streamReader = fi.OpenRead())
{
                             streamReader.Pipe(zipStream, p);
                         }
                         zipStream.CloseEntry();
                     }, error);
                 }
             }
             prog?.Report(1);
         }
References System.IO.PathExt.Abs2Rel().
DecompressDirectory()
static void Juniper.Data.Zip.DecompressDirectory (string inputZipFile, string outputDirectory, IProgress prog = null, Action< Exception > error = null) inline static
Dump the contents of a zip file out to disk.
Parameters
inputZipFile The zip file to decompress
outputDirectory The location to which to dump the files.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
error A callback for any errors that occur. Defaults to null (i.e. no error reporting).
Definition at line 117 of file Zip.cs.
         {
             prog?.Report(0);
             if (!File.Exists(inputZipFile))
             {
                 throw new FileNotFoundException("File not found! " + inputZipFile, inputZipFile);
             }
             else
             {
                 using (var zf = new ZipFile(inputZipFile))
                 {
                     zf.IsStreamOwner = true;
                     prog.ForEach(zf.Cast<ZipEntry>(), (zipEntry, p) =>
                     {
                         var fullZipToPath = Path.Combine(outputDirectory, zipEntry.Name);
                         if (zipEntry.IsDirectory)
{
                             DirectoryExt.CreateDirectory(fullZipToPath);
                         }
                         else if (zipEntry.IsFile)
{
                             var okToWrite = !File.Exists(fullZipToPath);
                             if (!okToWrite)
{
                                 okToWrite = FileExt.TryDelete(fullZipToPath);
                             }
                             if (okToWrite)
{
                                 var directoryName = Path.GetDirectoryName(fullZipToPath);
                                 if (directoryName.Length > 0)
{
                                     DirectoryExt.CreateDirectory(directoryName);
                                 }
                                 using (var zipStream = zf.GetInputStream(zipEntry))
                                 using (var streamWriter = File.Create(fullZipToPath))
{
                                     zipStream.Pipe(streamWriter, p);
                                 }
                             }
                         }
                     }, error);
                 }
             }
         }
References System.IO.DirectoryExt.CreateDirectory().
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Install().
GetFile()
static void Juniper.Data.Zip.GetFile (string zipFile, string filePath, Action< Stream > resolve, Action< Exception > reject, IProgress prog = null) inline static
Retrieves a single file from a zip file.
Parameters
zipFile The zip file in which to find the file.
filePath The file to find in the zip file.
resolve A callback to recieve the file stream for the requested file.
reject A callback if the file does not exist.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Definition at line 35 of file Zip.cs.
         {
             prog?.Report(0);
             using (var file = new ZipFile(zipFile))
             {
                 file.IsStreamOwner = true;
                 var entryIndex = file.FindEntry(filePath, true);
                 if (entryIndex > -1)
                 {
                     var entry = file[entryIndex];
                     using (var stream = file.GetInputStream(entry))
                     {
                         resolve(new ProgressStream(stream, prog));
                     }
                 }
                 else
                 {
                     reject(new FileNotFoundException($"Could not find file {filePath} in zip file {zipFile}", $"{zipFile}::{filePath}"));
                 }
             }
             prog?.Report(1);
         }
RecurseDirectories()
static IEnumerable<string> Juniper.Data.Zip.RecurseDirectories (string inputZipFile, IProgress prog = null) inline static
Lists all of the directories in a zip file.
Parameters
inputZipFile A filepath to the zip file to scan.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Returns
A lazy collection of ZipEntries that are directories.
Definition at line 216 of file Zip.cs.
         {
             foreach (var zipEntry in ZipEntries(inputZipFile, prog))
             {
                 if (zipEntry.IsDirectory)
                 {
                     yield return PathExt.FixPath(zipEntry.Name);
                 }
             }
         }
References System.IO.PathExt.FixPath().
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall().
RecurseFiles()
static IEnumerable<string> Juniper.Data.Zip.RecurseFiles (string inputZipFile, IProgress prog = null) inline static
Lists all of the files in a zip file.
Parameters
inputZipFile A filepath to the zip file to scan.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Returns
A lazy collection of ZipEntries that are files.
Definition at line 199 of file Zip.cs.
         {
             foreach (var zipEntry in ZipEntries(inputZipFile, prog))
             {
                 if (zipEntry.IsFile)
                 {
                     yield return PathExt.FixPath(zipEntry.Name);
                 }
             }
         }
References System.IO.PathExt.FixPath().
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall().
ZipEntries()
static IEnumerable<ZipEntry> Juniper.Data.Zip.ZipEntries (string inputZipFile, IProgress prog = null) inline static
Lists all of the entries (both files and directories) in a zip file.
Parameters
inputZipFile A filepath to the zip file to scan.
prog A progress tracking object, defaults to null (i.e. no progress tracking).
Returns
A lazy collection of ZipEntries
Definition at line 170 of file Zip.cs.
         {
             prog?.Report(0);
             if (File.Exists(inputZipFile))
             {
                 using (var zf = new ZipFile(inputZipFile))
                 {
                     zf.IsStreamOwner = true;
                     var progs = prog.Split(zf.Count);
                     for (var i = 0; i < zf.Count; ++i)
                     {
                         var p = progs[i];
                         p?.Report(0);
                         yield return zf[i];
                     }
                 }
             }
             prog?.Report(1);
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Data/Zip.cs