Juniper: Juniper.Animation.UnityAnimator Class Reference
Juniper.Animation.UnityAnimator Class Reference
Abstract over Unity's Animator class for 3D models. Requires an Animator object on the current gameObject. Only one such component is allowed on a gameObject at a time.
Public Member Functions
void Awake ()
Get the Animator on the current gameObject.
override bool HasState (string name)
Returns true in child classes to indicate they support the given state message.
override IEnumerator PlayCoroutine (string name)
Execute an animation and return an IEnumerator that can be used to yield in a coroutine for asynchronous execution.
void Play (string name)
Play an animation immediately, with no chance to wait for its completion.
Static Public Member Functions
static bool AnimatorHasState (Animator animator, string name)
Check to see if the current animation has the desired clip.
static AbstractAnimator GetAnimator (GameObject parent, string[] parts)
Creates the right Animator subclass for a given gameObject. If the gameObject has a Unity Animator on it, GetAnimator will create a UnityAnimator. If the gameObject has child transforms that match the Interaction system's state names, then GetAnimator will create a ChildSwapAnimator.
Private Attributes
Animator animator
The animator over which we are abstracting.
Detailed Description
Abstract over Unity's Animator class for 3D models. Requires an Animator object on the current gameObject. Only one such component is allowed on a gameObject at a time.
Definition at line 16 of file UnityAnimator.cs.
Member Function Documentation
AnimatorHasState()
static bool Juniper.Animation.UnityAnimator.AnimatorHasState (Animator animator, string name) inline static
Check to see if the current animation has the desired clip.
Parameters
animator
name
Returns
Definition at line 24 of file UnityAnimator.cs.
         {
             if (animator != null
                 && animator.runtimeAnimatorController != null
                 && animator.runtimeAnimatorController.animationClips != null)
             {
                 foreach (var clip in animator.runtimeAnimatorController.animationClips)
                 {
                     if (clip.name == name)
                     {
                         return true;
                     }
                 }
             }
             return false;
         }
References Juniper.Animation.UnityAnimator.animator.
Referenced by Juniper.Animation.AbstractAnimator.GetAnimator(), and Juniper.Animation.UnityAnimator.HasState().
Awake()
void Juniper.Animation.UnityAnimator.Awake () inline
Get the Animator on the current gameObject.
Definition at line 45 of file UnityAnimator.cs.
         {
             animator = GetComponent<Animator>();
         }
References Juniper.Animation.UnityAnimator.animator.
GetAnimator()
static AbstractAnimator Juniper.Animation.AbstractAnimator.GetAnimator (GameObject parent, string [] parts) inline static inherited
Creates the right Animator subclass for a given gameObject. If the gameObject has a Unity Animator on it, GetAnimator will create a UnityAnimator. If the gameObject has child transforms that match the Interaction system's state names, then GetAnimator will create a ChildSwapAnimator.
Parameters
parent
parts
Returns
Definition at line 23 of file AbstractAnimator.cs.
         {
             var animator = parent.GetComponent<AbstractAnimator>();
             var defaultState = parts[0];
             if (animator == null)
             {
 #if UNITY_MODULES_ANIMATION
                 var anim = parent.GetComponent<Animator>();
                 if (anim != null && UnityAnimator.AnimatorHasState(anim, defaultState))
                 {
                     animator = parent.Ensure<UnityAnimator>();
                 }
                 else
 #endif
                 if (parent.transform.childCount > 0 && parent.transform.Find(defaultState))
                 {
                     var swapper = parent.Ensure<ChildSwapAnimator>();
                     swapper.Value.stateNames = parts;
                     animator = swapper;
                 }
             }
             return animator;
         }
References Juniper.Animation.UnityAnimator.AnimatorHasState(), and Juniper.Animation.ChildSwapAnimator.stateNames.
Referenced by Juniper.Widgets.AbstractTouchable.Awake().
HasState()
override bool Juniper.Animation.UnityAnimator.HasState (string name) inline virtual
Returns true in child classes to indicate they support the given state message.
Parameters
name The animation state to check for
Returns
True or False
Implements Juniper.Animation.AbstractAnimator.
Definition at line 55 of file UnityAnimator.cs.
         {
             return AnimatorHasState(animator, name);
         }
References Juniper.Animation.UnityAnimator.animator, and Juniper.Animation.UnityAnimator.AnimatorHasState().
Play()
void Juniper.Animation.AbstractAnimator.Play (string name) inline inherited
Play an animation immediately, with no chance to wait for its completion.
Parameters
name
Definition at line 60 of file AbstractAnimator.cs.
         {
             if (isActiveAndEnabled)
             {
                 this.Run(PlayCoroutine(name));
             }
         }
References Juniper.Animation.AbstractAnimator.PlayCoroutine().
Referenced by Juniper.Widgets.AttentionDirector.Play(), and Juniper.Widgets.AbstractTouchable.ShowState().
PlayCoroutine()
override IEnumerator Juniper.Animation.UnityAnimator.PlayCoroutine (string name) inline virtual
Execute an animation and return an IEnumerator that can be used to yield in a coroutine for asynchronous execution.
Parameters
name
Returns
Implements Juniper.Animation.AbstractAnimator.
Definition at line 66 of file UnityAnimator.cs.
         {
             if (animator != null
                 && animator.runtimeAnimatorController != null)
             {
                 animator.Play(name);
                 var animationState = animator.GetCurrentAnimatorStateInfo(0);
                 var len = animationState.length;
                 yield return Wait.Seconds(len);
                 animationState = animator.GetCurrentAnimatorStateInfo(0);
                 yield return Wait.Seconds(animationState.length - len);
             }
         }
References Juniper.Animation.UnityAnimator.animator, and Juniper.Wait.Seconds().
Member Data Documentation
animator
Animator Juniper.Animation.UnityAnimator.animator private
The animator over which we are abstracting.
Definition at line 84 of file UnityAnimator.cs.
Referenced by Juniper.Animation.UnityAnimator.AnimatorHasState(), Juniper.Animation.UnityAnimator.Awake(), Juniper.Animation.UnityAnimator.HasState(), and Juniper.Animation.UnityAnimator.PlayCoroutine().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Animation/UnityAnimator.cs