Juniper: Juniper.IO.ICacheDestinationLayerExt Class Reference
Juniper.IO.ICacheDestinationLayerExt Class Reference
Static Public Member Functions
static async Task CopyToAsync (this ICacheSourceLayer fromLayer, ContentReference fromRef, ICacheDestinationLayer toLayer, ContentReference toRef, IProgress prog=null)
static void Save< ResultType > (this ICacheDestinationLayer layer, ISerializer< ResultType > serializer, ContentReference fileRef, ResultType value)
Detailed Description
Definition at line 6 of file ICacheDestinationLayerExt.cs.
Member Function Documentation
CopyToAsync()
static async Task Juniper.IO.ICacheDestinationLayerExt.CopyToAsync (this ICacheSourceLayer fromLayer, ContentReference fromRef, ICacheDestinationLayer toLayer, ContentReference toRef, IProgress prog = null) inline static
Definition at line 8 of file ICacheDestinationLayerExt.cs.
         {
             if (fromLayer is null)
             {
                 throw new ArgumentNullException(nameof(fromLayer));
             }
             if (fromRef is null)
             {
                 throw new ArgumentNullException(nameof(fromRef));
             }
             if (toLayer is null)
             {
                 throw new ArgumentNullException(nameof(toLayer));
             }
             if (toRef is null)
             {
                 throw new ArgumentNullException(nameof(toRef));
             }
             if (fromLayer.IsCached(fromRef))
             {
                 using var inStream = await fromLayer
                     .GetStreamAsync(fromRef, prog)
                     .ConfigureAwait(false);
                 using var outStream = toLayer.Create(toRef);
                 await inStream
                     .CopyToAsync(outStream)
                     .ConfigureAwait(false);
             }
         }
References Juniper.IO.ICacheDestinationLayer.Create(), Juniper.IO.ICacheSourceLayer.GetStreamAsync(), and Juniper.IO.ICacheSourceLayer.IsCached().
Save< ResultType >()
static void Juniper.IO.ICacheDestinationLayerExt.Save< ResultType > (this ICacheDestinationLayer layer, ISerializer< ResultType > serializer, ContentReference fileRef, ResultType value) inline static
Definition at line 47 of file ICacheDestinationLayerExt.cs.
         {
             if (layer is null)
             {
                 throw new ArgumentNullException(nameof(layer));
             }
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             using var stream = layer.Create(fileRef);
             serializer.Serialize(stream, value);
         }
References Juniper.IO.ICacheDestinationLayer.Create(), and Juniper.IO.ISerializer< in in T >.Serialize().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/ICacheDestinationLayerExt.cs