import {
    anticlockwiseTriangleHeadedBottomUShapedArrow,
    anticlockwiseTriangleHeadedLeftUShapedArrow, anticlockwiseTriangleHeadedOpenCircleArrow, anticlockwiseTriangleHeadedRightUShapedArrow, anticlockwiseTriangleHeadedTopUShapedArrow, clockwiseTriangleHeadedOpenCircleArrow, clockwiseVerticalArrows, counterclockwiseArrowsButton, dashedTriangleHeadedRightwardsArrow, downArrow, downLeftArrow, downRightArrow, downwardsArrowWithLargeTriangleArrowhead, downwardsArrowWithMediumTriangleArrowhead, downwardsArrowWithSmallTriangleArrowhead, downwardsTriangleArrowhead, downwardsTriangleHeadedArrow, downwardsTriangleHeadedArrowLeftwardsOfUpwardsTriangleHeadedArrow, downwardsTriangleHeadedArrowToBar, downwardsTriangleHeadedArrowWithBoldShaft, downwardsTriangleHeadedArrowWithDoubleHorizontalStroke, downwardsTriangleHeadedArrowWithHeavyShaft, downwardsTriangleHeadedArrowWithLongTipLeftwards,
    downwardsTriangleHeadedArrowWithLongTipRightwards, downwardsTriangleHeadedArrowWithMediumShaft, downwardsTriangleHeadedArrowWithNarrowShaft, downwardsTriangleHeadedArrowWithVeryHeavyShaft, downwardsTriangleHeadedDashedArrow, downwardsTriangleHeadedPairedArrows, downwardsTriangleHeadedZigzagArrow, downwardsTwoHeadedArrowWithTriangleArrowheads, downwardsWhiteArrowWithinTriangleArrowhead, heavyDashedTriangleHeadedRightwardsArrow, heavyTriangleHeadedRightwardsArrow, leftArrow, leftArrowCurvingRight, leftRightArrow, leftRightTriangleHeadedArrow, leftwardsArrowWithLargeTriangleArrowhead, leftwardsArrowWithMediumTriangleArrowhead, leftwardsArrowWithSmallTriangleArrowhead, leftwardsTriangleArrowhead, leftwardsTriangleHeadedArrow, leftwardsTriangleHeadedArrowOverRightardsTriangleHeadedArrow, leftwardsTriangleHeadedArrowToBar, leftwardsTriangleHeadedArrowWithBoldShaft, leftwardsTriangleHeadedArrowWithDoubleHorizontalStroke, leftwardsTriangleHeadedArrowWithHeavyShaft, leftwardsTriangleHeadedArrowWithLongTipDownwards, leftwardsTriangleHeadedArrowWithLongTipUpwards, leftwardsTriangleHeadedArrowWithMediumShaft, leftwardsTriangleHeadedArrowWithNarrowShaft, leftwardsTriangleHeadedArrowWithVeryHeavyShaft, leftwardsTriangleHeadedDashedArrow, leftwardsTriangleHeadedPairedArrows, leftwardsTwoHeadedArrowWithTriangleArrowheads, leftwardsWhiteArrowWithinTriangleArrowhead, northEastTriangleHeadedArrow, northEastTriangleHeadedArrowToBar, northWestTriangleHeadedArrow, northWestTriangleHeadedArrowToBar, rightArrow, rightArrowCurvingDown, rightArrowCurvingLeft, rightArrowCurvingUp, rightwardsArrowWithLargeTriangleArrowhead, rightwardsArrowWithMediumTriangleArrowhead, rightwardsArrowWithSmallTriangleArrowhead, rightwardsTriangleArrowhead, rightwardsTriangleHeadedArrow, rightwardsTriangleHeadedArrowOverLeftwardsTriangleHeadedArrow, rightwardsTriangleHeadedArrowToBar, rightwardsTriangleHeadedArrowWithBoldShaft, rightwardsTriangleHeadedArrowWithDoubleHorizontalStroke, rightwardsTriangleHeadedArrowWithHeavyShaft, rightwardsTriangleHeadedArrowWithLongTipDownwards, rightwardsTriangleHeadedArrowWithLongTipUpwards, rightwardsTriangleHeadedArrowWithMediumShaft, rightwardsTriangleHeadedArrowWithNarrowShaft, rightwardsTriangleHeadedArrowWithVeryHeavyShaft, rightwardsTriangleHeadedDashedArrow, rightwardsTriangleHeadedPairedArrows, rightwardsTwoHeadedArrowWithTriangleArrowheads, rightwardsWhiteArrowWithinTriangleArrowhead, southEastTriangleHeadedArrow, southEastTriangleHeadedArrowToBar, southWestTriangleHeadedArrow, southWestTriangleHeadedArrowToBar, triangleHeadedRightwardsArrow, upArrow, upDownArrow, upDownTriangleHeadedArrow, upLeftArrow, upRightArrow, upwardsArrowWithLargeTriangleArrowhead, upwardsArrowWithMediumTriangleArrowhead, upwardsArrowWithSmallTriangleArrowhead, upwardsTriangleArrowhead, upwardsTriangleHeadedArrow, upwardsTriangleHeadedArrowLeftwardsOfDownwardsTriangleHeadedArrow, upwardsTriangleHeadedArrowToBar, upwardsTriangleHeadedArrowWithBoldShaft, upwardsTriangleHeadedArrowWithDoubleHorizontalStroke, upwardsTriangleHeadedArrowWithHeavyShaft, upwardsTriangleHeadedArrowWithLongTipLeftwards,
    upwardsTriangleHeadedArrowWithLongTipRightwards, upwardsTriangleHeadedArrowWithMediumShaft, upwardsTriangleHeadedArrowWithNarrowShaft, upwardsTriangleHeadedArrowWithVeryHeavyShaft, upwardsTriangleHeadedDashedArrow, upwardsTriangleHeadedPairedArrows, upwardsTwoHeadedArrowWithTriangleArrowheads, upwardsWhiteArrowWithinTriangleArrowhead
} from ".";
import { EmojiGroup } from "./EmojiGroup";




export const arrows = /*@__PURE__*/ new EmojiGroup(
    "Arrows", "Arrows pointing in different directions",
    triangleHeadedRightwardsArrow,
    heavyTriangleHeadedRightwardsArrow,
    dashedTriangleHeadedRightwardsArrow,
    heavyDashedTriangleHeadedRightwardsArrow,
    downwardsTriangleHeadedZigzagArrow,
    leftwardsTriangleHeadedArrow,
    upwardsTriangleHeadedArrow,
    rightwardsTriangleHeadedArrow,
    downwardsTriangleHeadedArrow,
    leftRightTriangleHeadedArrow,
    upDownTriangleHeadedArrow,
    northWestTriangleHeadedArrow,
    northEastTriangleHeadedArrow,
    southEastTriangleHeadedArrow,
    southWestTriangleHeadedArrow,
    leftwardsTriangleHeadedDashedArrow,
    upwardsTriangleHeadedDashedArrow,
    rightwardsTriangleHeadedDashedArrow,
    downwardsTriangleHeadedDashedArrow,
    clockwiseTriangleHeadedOpenCircleArrow,
    anticlockwiseTriangleHeadedOpenCircleArrow,
    leftwardsTriangleHeadedArrowToBar,
    upwardsTriangleHeadedArrowToBar,
    rightwardsTriangleHeadedArrowToBar,
    downwardsTriangleHeadedArrowToBar,
    northWestTriangleHeadedArrowToBar,
    northEastTriangleHeadedArrowToBar,
    southEastTriangleHeadedArrowToBar,
    southWestTriangleHeadedArrowToBar,
    leftwardsTriangleHeadedArrowWithDoubleHorizontalStroke,
    upwardsTriangleHeadedArrowWithDoubleHorizontalStroke,
    rightwardsTriangleHeadedArrowWithDoubleHorizontalStroke,
    downwardsTriangleHeadedArrowWithDoubleHorizontalStroke,
    leftwardsTriangleHeadedArrowOverRightardsTriangleHeadedArrow,
    upwardsTriangleHeadedArrowLeftwardsOfDownwardsTriangleHeadedArrow,
    rightwardsTriangleHeadedArrowOverLeftwardsTriangleHeadedArrow,
    downwardsTriangleHeadedArrowLeftwardsOfUpwardsTriangleHeadedArrow,
    leftwardsTriangleHeadedPairedArrows,
    upwardsTriangleHeadedPairedArrows,
    rightwardsTriangleHeadedPairedArrows,
    downwardsTriangleHeadedPairedArrows,
    anticlockwiseTriangleHeadedRightUShapedArrow,
    anticlockwiseTriangleHeadedBottomUShapedArrow,
    anticlockwiseTriangleHeadedLeftUShapedArrow,
    anticlockwiseTriangleHeadedTopUShapedArrow,
    downwardsTriangleHeadedArrowWithLongTipLeftwards,
    downwardsTriangleHeadedArrowWithLongTipRightwards,
    upwardsTriangleHeadedArrowWithLongTipLeftwards,
    upwardsTriangleHeadedArrowWithLongTipRightwards,
    leftwardsTriangleHeadedArrowWithLongTipUpwards,
    rightwardsTriangleHeadedArrowWithLongTipUpwards,
    leftwardsTriangleHeadedArrowWithLongTipDownwards,
    rightwardsTriangleHeadedArrowWithLongTipDownwards,
    leftwardsTwoHeadedArrowWithTriangleArrowheads,
    upwardsTwoHeadedArrowWithTriangleArrowheads,
    rightwardsTwoHeadedArrowWithTriangleArrowheads,
    downwardsTwoHeadedArrowWithTriangleArrowheads,
    leftwardsArrowWithSmallTriangleArrowhead,
    upwardsArrowWithSmallTriangleArrowhead,
    rightwardsArrowWithSmallTriangleArrowhead,
    downwardsArrowWithSmallTriangleArrowhead,
    leftwardsArrowWithMediumTriangleArrowhead,
    upwardsArrowWithMediumTriangleArrowhead,
    rightwardsArrowWithMediumTriangleArrowhead,
    downwardsArrowWithMediumTriangleArrowhead,
    leftwardsArrowWithLargeTriangleArrowhead,
    upwardsArrowWithLargeTriangleArrowhead,
    rightwardsArrowWithLargeTriangleArrowhead,
    downwardsArrowWithLargeTriangleArrowhead,
    leftwardsTriangleHeadedArrowWithNarrowShaft,
    upwardsTriangleHeadedArrowWithNarrowShaft,
    rightwardsTriangleHeadedArrowWithNarrowShaft,
    downwardsTriangleHeadedArrowWithNarrowShaft,
    leftwardsTriangleHeadedArrowWithMediumShaft,
    upwardsTriangleHeadedArrowWithMediumShaft,
    rightwardsTriangleHeadedArrowWithMediumShaft,
    downwardsTriangleHeadedArrowWithMediumShaft,
    leftwardsTriangleHeadedArrowWithBoldShaft,
    upwardsTriangleHeadedArrowWithBoldShaft,
    rightwardsTriangleHeadedArrowWithBoldShaft,
    downwardsTriangleHeadedArrowWithBoldShaft,
    leftwardsTriangleHeadedArrowWithHeavyShaft,
    upwardsTriangleHeadedArrowWithHeavyShaft,
    rightwardsTriangleHeadedArrowWithHeavyShaft,
    downwardsTriangleHeadedArrowWithHeavyShaft,
    leftwardsTriangleHeadedArrowWithVeryHeavyShaft,
    upwardsTriangleHeadedArrowWithVeryHeavyShaft,
    rightwardsTriangleHeadedArrowWithVeryHeavyShaft,
    downwardsTriangleHeadedArrowWithVeryHeavyShaft,
    leftwardsTriangleArrowhead,
    upwardsTriangleArrowhead,
    rightwardsTriangleArrowhead,
    downwardsTriangleArrowhead,
    leftwardsWhiteArrowWithinTriangleArrowhead,
    upwardsWhiteArrowWithinTriangleArrowhead,
    rightwardsWhiteArrowWithinTriangleArrowhead,
    downwardsWhiteArrowWithinTriangleArrowhead,
    clockwiseVerticalArrows,
    counterclockwiseArrowsButton,
    leftRightArrow,
    upDownArrow,
    upLeftArrow,
    upRightArrow,
    downRightArrow,
    downLeftArrow,
    rightArrowCurvingLeft,
    leftArrowCurvingRight,
    rightArrow,
    rightArrowCurvingUp,
    rightArrowCurvingDown,
    leftArrow,
    upArrow,
    downArrow);
