Juniper: Juniper.World.GIS.Google.Geocoding.GeometryResult Class Reference
Juniper.World.GIS.Google.Geocoding.GeometryResult Class Reference
Public Member Functions
void GetObjectData (SerializationInfo info, StreamingContext context)
Protected Member Functions
GeometryResult (SerializationInfo info, StreamingContext context)
Properties
LatLngPoint Location [get]
string LocationTypeString [get]
GeometryLocationType Location_Type [get]
GeometryViewport Viewport [get]
GeometryViewport Bounds [get]
Static Private Attributes
static readonly string LOCATION_FIELD = nameof(Location).ToLowerInvariant()
static readonly string LOCATION_TYPE_FIELD = nameof(Location_Type).ToLowerInvariant()
static readonly string VIEWPORT_FIELD = nameof(Viewport).ToLowerInvariant()
Detailed Description
Definition at line 7 of file GeometryResult.cs.
Constructor & Destructor Documentation
GeometryResult()
Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult (SerializationInfo info, StreamingContext context) inline protected
Definition at line 24 of file GeometryResult.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Location = info.GetValue<LatLngPoint>(LOCATION_FIELD);
             LocationTypeString = info.GetString(LOCATION_TYPE_FIELD);
             Location_Type = Enum.TryParse<GeometryLocationType>(LocationTypeString, out var type)
                 ? type
                 : GeometryLocationType.Unknown;
             Viewport = info.GetValue<GeometryViewport>(VIEWPORT_FIELD);
             foreach (var field in info)
             {
                 switch (field.Name)
                 {
                     case nameof(Bounds):
                     Bounds = info.GetValue<GeometryViewport>(field.Name);
                     break;
                 }
             }
         }
References Juniper.World.GIS.Google.Geocoding.GeometryResult.Bounds, Juniper.World.GIS.Google.Geocoding.GeometryResult.Location, Juniper.World.GIS.Google.Geocoding.GeometryResult.LOCATION_FIELD, Juniper.World.GIS.Google.Geocoding.GeometryResult.Location_Type, Juniper.World.GIS.Google.Geocoding.GeometryResult.LOCATION_TYPE_FIELD, Juniper.World.GIS.Google.Geocoding.GeometryResult.LocationTypeString, Juniper.World.GIS.Google.Geocoding.GeometryResult.Viewport, and Juniper.World.GIS.Google.Geocoding.GeometryResult.VIEWPORT_FIELD.
Member Function Documentation
GetObjectData()
void Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 48 of file GeometryResult.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(LOCATION_FIELD, new
             {
                 lat = Location.Latitude,
                 lng = Location.Longitude
             });
             info.AddValue(LOCATION_TYPE_FIELD, Location_Type.ToString());
             info.AddValue(VIEWPORT_FIELD, Viewport);
         }
References Juniper.World.GIS.LatLngPoint.Latitude, Juniper.World.GIS.Google.Geocoding.GeometryResult.Location, Juniper.World.GIS.Google.Geocoding.GeometryResult.LOCATION_FIELD, Juniper.World.GIS.Google.Geocoding.GeometryResult.Location_Type, Juniper.World.GIS.Google.Geocoding.GeometryResult.LOCATION_TYPE_FIELD, Juniper.World.GIS.LatLngPoint.Longitude, Juniper.World.GIS.Google.Geocoding.GeometryResult.Viewport, and Juniper.World.GIS.Google.Geocoding.GeometryResult.VIEWPORT_FIELD.
Member Data Documentation
LOCATION_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeometryResult.LOCATION_FIELD = nameof(Location).ToLowerInvariant() static private
Definition at line 9 of file GeometryResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult(), and Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData().
LOCATION_TYPE_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeometryResult.LOCATION_TYPE_FIELD = nameof(Location_Type).ToLowerInvariant() static private
Definition at line 10 of file GeometryResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult(), and Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData().
VIEWPORT_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeometryResult.VIEWPORT_FIELD = nameof(Viewport).ToLowerInvariant() static private
Definition at line 11 of file GeometryResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult(), and Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData().
Property Documentation
Bounds
GeometryViewport Juniper.World.GIS.Google.Geocoding.GeometryResult.Bounds get
Definition at line 21 of file GeometryResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult().
Location
LatLngPoint Juniper.World.GIS.Google.Geocoding.GeometryResult.Location get
Definition at line 13 of file GeometryResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult(), and Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData().
Location_Type
GeometryLocationType Juniper.World.GIS.Google.Geocoding.GeometryResult.Location_Type get
Definition at line 17 of file GeometryResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult(), and Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData().
LocationTypeString
string Juniper.World.GIS.Google.Geocoding.GeometryResult.LocationTypeString get
Definition at line 15 of file GeometryResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult().
Viewport
GeometryViewport Juniper.World.GIS.Google.Geocoding.GeometryResult.Viewport get
Definition at line 19 of file GeometryResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryResult.GeometryResult(), and Juniper.World.GIS.Google.Geocoding.GeometryResult.GetObjectData().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/Geocoding/GeometryResult.cs