Juniper: System.Collections.Generic.RingBuffer< T > Class Template Reference
System.Collections.Generic.RingBuffer< T > Class Template Reference
A collection of fixed size that overwrites the oldest items when the collection is full.
Public Member Functions
RingBuffer (int capacity)
Create a RingBuffer of fixed size. RingBuffers are not resizable.
IEnumerator< T > GetEnumerator ()
Returns an enumerator that iterates through the collection.
bool Contains (T item)
Returns true if the give item is in the collection.
void CopyTo (T[] array, int startIndex, int destinationIndex, int count)
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
void CopyTo (T[] array, int destinationIndex, int count)
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
void CopyTo (T[] array, int destinationIndex)
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
void CopyTo (T[] array)
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
bool Remove (T item)
Remove an item from the buffer.
int IndexOf (T item)
Determines the index of the specified item in the RingBuffer{T}.
virtual void Clear ()
Empty the buffer.
virtual void Add (T item)
Add an item to the buffer, overwriting the oldest values if the buffer is full.
virtual void Insert (int index, T item)
Insert an item at an arbitrary point in the buffer.
virtual void RemoveAt (int index)
Remove an item at the specified index from the buffer.
Properties
int Start [get, set]
The beginning of the collection in a fixed array. The collection moves once it IsSaturated, old values get dropped out and new values appended.
int End [get, set]
The end of the collection in a fixed array. Before the collection IsSaturated, the array is not completely utilized and we need to know where the unused part begins.
bool IsSaturated [get]
Returns true if all slots in the ring buffer have values.
int Count [get]
Returns the number of items in the buffer, up to the buffer size.
bool IsReadOnly [get]
Always returns false
T this[int index] [get, set]
Gets or sets the element at the specified index.
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Returns an enumerator that iterates through the collection.
Private Attributes
readonly int width
The total number of ring buffer indices, which is one more than the ring buffer's actual capacity.
readonly T [] buffer
The array in which ring buffer values are stored.
int start
The index into buffer at which the ring buffer starts.
int end
The index into buffer after which the ring buffer ends.
Detailed Description
A collection of fixed size that overwrites the oldest items when the collection is full.
Template Parameters
T Any type.
Definition at line 9 of file RingBuffer.cs.
Constructor & Destructor Documentation
RingBuffer()
System.Collections.Generic.RingBuffer< T >.RingBuffer (int capacity) inline
Create a RingBuffer of fixed size. RingBuffers are not resizable.
Parameters
capacity A starting capacity.
var ring = new RingBuffer{string}(100); // creates a buffer with 100 empty slots for strings.
Definition at line 83 of file RingBuffer.cs.
         {
             if (capacity == 0)
             {
                 throw new ArgumentOutOfRangeException(nameof(capacity), "Capacity must be greater than 0");
             }
             buffer = new T[capacity];
             width = capacity + 1;
             start = end = 0;
         }
References System.Collections.Generic.RingBuffer< T >.buffer, System.Collections.Generic.RingBuffer< T >.end, System.Collections.Generic.RingBuffer< T >.start, and System.Collections.Generic.RingBuffer< T >.width.
Member Function Documentation
Add()
virtual void System.Collections.Generic.RingBuffer< T >.Add (T item) inline virtual
Add an item to the buffer, overwriting the oldest values if the buffer is full.
Parameters
item The value to add to the collection.
var buffer = new RingBuffer{int}(5); buffer.Add(3); // { 3 } buffer.Add(1); // { 3, 1 } buffer.Add(4); // { 3, 1, 4 } buffer.Add(1); // { 3, 1, 4, 1 } buffer.Add(5); // { 3, 1, 4, 1, 5 } buffer.Add(9); // { 1, 4, 1, 5, 9 } buffer.Add(2); // { 4, 1, 5, 9, 2 }
Definition at line 431 of file RingBuffer.cs.
         {
             buffer[End % buffer.Length] = item;
             ++End;
         }
References System.Collections.Generic.RingBuffer< T >.buffer, and System.Collections.Generic.RingBuffer< T >.End.
Clear()
virtual void System.Collections.Generic.RingBuffer< T >.Clear () inline virtual
Empty the buffer.
Only sets the Start and End pointers back to their starting value. Doesn't overwrite values that were in the buffer.
var buffer = new RingBuffer{int}(3); buffer.Add(3); // { 3 } buffer.Add(1); // { 3, 1 } buffer.Add(4); // { 3, 1, 4 } buffer.Clear(); // { } buffer.Add(1); // { 1 } buffer.Add(5); // { 1, 5 }
Definition at line 417 of file RingBuffer.cs.
         {
             start = end = 0;
         }
References System.Collections.Generic.RingBuffer< T >.end, and System.Collections.Generic.RingBuffer< T >.start.
Contains()
bool System.Collections.Generic.RingBuffer< T >.Contains (T item) inline
Returns true if the give item is in the collection.
Parameters
item The item to search for.
Returns
True if the item is found. False if it is not.
var buffer = new RingBuffer{int}(5); buffer.Add(3); // { 3 } buffer.Add(1); // { 3, 1 } buffer.Add(4); // { 3, 1, 4 } buffer.Add(1); // { 3, 1, 4, 1 } buffer.Add(5); // { 3, 1, 4, 1, 5 } buffer.Add(9); // { 1, 4, 1, 5, 9 } buffer.Add(2); // { 4, 1, 5, 9, 2 } buffer.Contains(3); // –> false buffer.Contains(1); // –> true
Definition at line 199 of file RingBuffer.cs.
         {
             return IndexOf(item) != -1;
         }
References System.Collections.Generic.RingBuffer< T >.IndexOf().
CopyTo() [1/4]
void System.Collections.Generic.RingBuffer< T >.CopyTo (T [] array, int startIndex, int destinationIndex, int count) inline
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
startIndex The zero-based index in the source buffer at which to start copying.
destinationIndex The zero-based index in array at which copying begins.
count The number of elements out of the source array to copy to the destination array.
Exceptions
ArgumentNullException array is null
ArgumentOutOfRangeException destinationIndex is less than 0.
ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from destinationIndex to the end of the destination array .
var buffer = new RingBuffer{int}(3); buffer.Add(3); buffer.Add(1); buffer.Add(4); /// int[] arr = new int[3]; // arr -> { 0, 0, 0 } buffer.CopyTo(arr, 0, 0, 3); // arr -> { 3, 1, 4 } buffer.CopyTo(arr, 1, 0, 2); // arr -> { 1, 4, 4 } buffer.CopyTo(arr, 0, 1, 2); // arr -> { 1, 3, 1 } buffer.CopyTo(arr, 1, 0, 3); // throws ArgumentException buffer.CopyTo(arr, 0, 1, 3); // throws ArgumentException
Definition at line 236 of file RingBuffer.cs.
         {
             if (array == null)
             {
                 throw new ArgumentNullException(nameof(array));
             }
             else if (startIndex < 0 || Count <= startIndex)
             {
                 throw new ArgumentOutOfRangeException(nameof(startIndex));
             }
             else if (destinationIndex < 0)
             {
                 throw new ArgumentOutOfRangeException(nameof(destinationIndex));
             }
             else if (destinationIndex + count > array.Length)
             {
                 throw new ArgumentException("The number of elements in the source ICollection<T> is greater than the available space from arrayIndex to the end of the destination array.");
             }
             if (Start < End)
             {
                 Array.Copy(buffer, Start, array, destinationIndex, End - Start);
             }
             else
             {
                 Array.Copy(buffer, Start, array, destinationIndex, count - Start);
                 Array.Copy(buffer, 0, array, destinationIndex + count - Start, End + 1);
             }
         }
References System.Collections.Generic.RingBuffer< T >.buffer, System.Collections.Generic.RingBuffer< T >.Count, System.Collections.Generic.RingBuffer< T >.End, and System.Collections.Generic.RingBuffer< T >.Start.
Referenced by System.Collections.Generic.RingBuffer< T >.CopyTo().
CopyTo() [2/4]
void System.Collections.Generic.RingBuffer< T >.CopyTo (T [] array, int destinationIndex, int count) inline
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
destinationIndex The zero-based index in array at which copying begins.
count The number of elements out of the source array to copy to the destination array.
Exceptions
ArgumentNullException array is null
ArgumentOutOfRangeException destinationIndex is less than 0.
ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from destinationIndex to the end of the destination array .
var buffer = new RingBuffer{int}(3); buffer.Add(3); buffer.Add(1); buffer.Add(4); /// int[] arr = new int[3]; // arr -> { 0, 0, 0 } buffer.CopyTo(arr, 0, 3); // arr -> { 3, 1, 4 } buffer.CopyTo(arr, 1, 2); // arr -> { 3, 3, 1 } buffer.CopyTo(arr, 1, 3); // throws ArgumentException
Definition at line 294 of file RingBuffer.cs.
         {
             CopyTo(array, 0, destinationIndex, count);
         }
References System.Collections.Generic.RingBuffer< T >.CopyTo().
CopyTo() [3/4]
void System.Collections.Generic.RingBuffer< T >.CopyTo (T [] array, int destinationIndex) inline
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
destinationIndex The zero-based index in array at which copying begins.
Exceptions
ArgumentNullException array is null
ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from destinationIndex to the end of the destination array .
var buffer = new RingBuffer{int}(3); buffer.Add(3); buffer.Add(1); buffer.Add(4); /// int[] arr = new int[3]; // arr -> { 0, 0, 0 } buffer.CopyTo(arr, 2); // arr -> { 3, 1, 0 } buffer.CopyTo(arr, 3); // arr -> { 3, 1, 4 } buffer.CopyTo(arr, 4); // throws ArgumentException
Definition at line 320 of file RingBuffer.cs.
         {
             CopyTo(array, 0, destinationIndex, Count);
         }
References System.Collections.Generic.RingBuffer< T >.CopyTo(), and System.Collections.Generic.RingBuffer< T >.Count.
CopyTo() [4/4]
void System.Collections.Generic.RingBuffer< T >.CopyTo (T [] array) inline
Copies the elements of the RingBuffer{T} to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
Exceptions
ArgumentNullException array is null
ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space in the destination array .
var buffer = new RingBuffer{int}(3); buffer.Add(3); buffer.Add(1); buffer.Add(4); /// int[] arr = new int[4]; // arr -> { 0, 0, 0, 0 } buffer.CopyTo(arr); // arr -> { 3, 1, 4, 0 } int[] arr = new int[4]; // arr -> { 0, 0, 0 } buffer.CopyTo(arr); // arr -> { 3, 1, 4 } int[] arr = new int[2]; // arr -> { 0, 0 } buffer.CopyTo(arr); // throws ArgumentException
Definition at line 344 of file RingBuffer.cs.
         {
             CopyTo(array, 0, 0, Count);
         }
References System.Collections.Generic.RingBuffer< T >.CopyTo(), and System.Collections.Generic.RingBuffer< T >.Count.
GetEnumerator() [1/2]
IEnumerator<T> System.Collections.Generic.RingBuffer< T >.GetEnumerator () inline
Returns an enumerator that iterates through the collection.
Returns
Definition at line 183 of file RingBuffer.cs.
         {
             return buffer.AsEnumerable().GetEnumerator();
         }
References System.Collections.Generic.RingBuffer< T >.buffer.
GetEnumerator() [2/2]
IEnumerator IEnumerable. System.Collections.Generic.RingBuffer< T >.GetEnumerator () inline private
Returns an enumerator that iterates through the collection.
Returns
Definition at line 505 of file RingBuffer.cs.
         {
             return buffer.GetEnumerator();
         }
References System.Collections.Generic.RingBuffer< T >.buffer.
IndexOf()
int System.Collections.Generic.RingBuffer< T >.IndexOf (T item) inline
Determines the index of the specified item in the RingBuffer{T}.
Parameters
item The object to location in the RingBuffer{T}.
Returns
The index of item if found in the list; otherwise, -1.
If an object occurs multiple times in the list, the IndexOf method always returns the first instance found.
var buffer = new RingBuffer{int}(3); /// buffer.Add(3); buffer.IndexOf(3); // –> 0 buffer.IndexOf(1); // –> -1 buffer.IndexOf(4); // –> -1 buffer.IndexOf(1); // –> -1 buffer.IndexOf(5); // –> -1 /// buffer.Add(1); buffer.IndexOf(3); // –> 0 buffer.IndexOf(1); // –> 1 buffer.IndexOf(4); // –> -1 buffer.IndexOf(1); // –> 1 buffer.IndexOf(5); // –> -1 /// buffer.Add(4); buffer.IndexOf(3); // –> 0 buffer.IndexOf(1); // –> 1 buffer.IndexOf(4); // –> 2 buffer.IndexOf(1); // –> 1 buffer.IndexOf(5); // –> -1 /// buffer.Add(1); buffer.IndexOf(3); // –> -1 buffer.IndexOf(1); // –> 0 buffer.IndexOf(4); // –> 1 buffer.IndexOf(1); // –> 2 buffer.IndexOf(5); // –> -1 /// buffer.Add(5); buffer.IndexOf(3); // –> -1 buffer.IndexOf(1); // –> 1 buffer.IndexOf(4); // –> 0 buffer.IndexOf(1); // –> 1 buffer.IndexOf(5); // –> 2
Definition at line 393 of file RingBuffer.cs.
         {
             for (var i = 0; i < Count; ++i)
             {
                 if (Equals(this[i], item))
                 {
                     return i;
                 }
             }
             return -1;
         }
References System.Collections.Generic.RingBuffer< T >.Count.
Referenced by System.Collections.Generic.RingBuffer< T >.Contains(), and System.Collections.Generic.RingBuffer< T >.Remove().
Insert()
virtual void System.Collections.Generic.RingBuffer< T >.Insert (int index, T item) inline virtual
Insert an item at an arbitrary point in the buffer.
Parameters
index The index at which to insert item .
item The value to insert.
Exceptions
ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
If the buffer is full, the oldest item will be dropped before the insertion is made. It's somewhat difficult to intuit the results, especially when inserting at index 0. The buffer always maintains that buffer.Insert(n, x); buffer[n] == x;, so inserting at index 0 when the buffer is full looks like overwriting index 0.
var buffer = new RingBuffer{int}(4); buffer.Insert(0, 5); // { 5 } buffer.Insert(0, 7); // { 7, 5 } buffer.Insert(1, 3); // { 7, 3, 5 } buffer.Insert(1, 13); // { 7, 13, 3, 5 } buffer.Insert(2, 2); // { 13, 3, 2, 5 } buffer.Insert(0, 17); // { 17, 3, 2, 5 }
Definition at line 456 of file RingBuffer.cs.
         {
             if (index < 0 || Count < index)
             {
                 throw new ArgumentOutOfRangeException(nameof(index));
             }
             ++End;
             for (var i = Count - 1; i > index; --i)
             {
                 this[i] = this[i - 1];
             }
             this[index] = item;
         }
References System.Collections.Generic.RingBuffer< T >.Count, and System.Collections.Generic.RingBuffer< T >.End.
Remove()
bool System.Collections.Generic.RingBuffer< T >.Remove (T item) inline
Remove an item from the buffer.
Parameters
item The value to remove.
Returns
True if the item existed in the buffer and was removed. False otherwise.
var buffer = new RingBuffer{int}(3); buffer.Add(3); // { 3 } buffer.Add(1); // { 3, 1 } buffer.Add(4); // { 3, 1, 4 } buffer.Remove(1); // { 3, 4 } buffer.Add(5); // { 3, 4, 5 } buffer.Add(6); // { 4, 5, 6 } buffer.Remove(3); // { 4, 5, 6 } buffer.Remove(4); // { 5, 6 }
Definition at line 360 of file RingBuffer.cs.
         {
             var i = IndexOf(item);
             var remove = i != -1;
             if (remove)
             {
                 RemoveAt(i);
             }
             return remove;
         }
References System.Collections.Generic.RingBuffer< T >.IndexOf(), and System.Collections.Generic.RingBuffer< T >.RemoveAt().
RemoveAt()
virtual void System.Collections.Generic.RingBuffer< T >.RemoveAt (int index) inline virtual
Remove an item at the specified index from the buffer.
Parameters
index The index at which to remove an item.
Exceptions
ArgumentOutOfRangeException index is less than 0 or greater than Count - 1.
var buffer = new RingBuffer{int}(4); buffer.Add(3); // { 3 } buffer.Add(1); // { 3, 1 } buffer.Add(4); // { 3, 1, 4 } buffer.Add(1); // { 3, 1, 4, 1 } buffer.Add(5); // { 3, 1, 4, 1, 5 } buffer.Add(9); // { 1, 4, 1, 5, 9 } buffer.Add(2); // { 4, 1, 5, 9, 2 } buffer.RemoveAt(2); // { 4, 1, 9, 2 } buffer.RemoveAt(0); // { 1, 9, 2 } buffer.RemoveAt(2); // { 1, 9 } buffer.RemoveAt(0); // { 9 } buffer.RemoveAt(0); // { } buffer.RemoveAt(0); // throws ArgumentOutOfRangeException
Definition at line 487 of file RingBuffer.cs.
         {
             if (index < 0 || Count <= index)
             {
                 throw new ArgumentOutOfRangeException(nameof(index));
             }
             for (var i = index; i < Count - 1; ++i)
             {
                 this[i] = this[i + 1];
             }
             --End;
         }
References System.Collections.Generic.RingBuffer< T >.Count, and System.Collections.Generic.RingBuffer< T >.End.
Referenced by System.Collections.Generic.RingBuffer< T >.Remove().
Member Data Documentation
buffer
readonly T [] System.Collections.Generic.RingBuffer< T >.buffer private
The array in which ring buffer values are stored.
Definition at line 19 of file RingBuffer.cs.
Referenced by System.Collections.Generic.RingBuffer< T >.Add(), System.Collections.Generic.RingBuffer< T >.CopyTo(), System.Collections.Generic.RingBuffer< T >.GetEnumerator(), and System.Collections.Generic.RingBuffer< T >.RingBuffer().
end
int System.Collections.Generic.RingBuffer< T >.end private
The index into buffer after which the ring buffer ends.
Definition at line 51 of file RingBuffer.cs.
Referenced by System.Collections.Generic.RingBuffer< T >.Clear(), and System.Collections.Generic.RingBuffer< T >.RingBuffer().
start
int System.Collections.Generic.RingBuffer< T >.start private
The index into buffer at which the ring buffer starts.
Definition at line 24 of file RingBuffer.cs.
Referenced by System.Collections.Generic.RingBuffer< T >.Clear(), and System.Collections.Generic.RingBuffer< T >.RingBuffer().
width
readonly int System.Collections.Generic.RingBuffer< T >.width private
The total number of ring buffer indices, which is one more than the ring buffer's actual capacity.
Definition at line 14 of file RingBuffer.cs.
Referenced by System.Collections.Generic.RingBuffer< T >.RingBuffer().
Property Documentation
Count
int System.Collections.Generic.RingBuffer< T >.Count get
Returns the number of items in the buffer, up to the buffer size.
var buffer = new RingBuffer{int}(5); // buffer.Count == 0 buffer.Add(3); // buffer.Count == 1 buffer.Add(1); // buffer.Count == 2 buffer.Add(4); // buffer.Count == 3 buffer.Add(1); // buffer.Count == 4 buffer.Add(5); // buffer.Count == 5 buffer.Add(9); // buffer.Count == 5 buffer.Add(2); // buffer.Count == 5
Definition at line 116 of file RingBuffer.cs.
         {
             get
             {
                 if (End >= Start)
                 {
                     return End - Start;
                 }
                 else
                 {
                     return End - Start + width;
                 }
             }
         }
Referenced by System.Collections.Generic.RingBuffer< T >.CopyTo(), System.Collections.Generic.RingBuffer< T >.IndexOf(), System.Collections.Generic.RingBuffer< T >.Insert(), and System.Collections.Generic.RingBuffer< T >.RemoveAt().
End
int System.Collections.Generic.RingBuffer< T >.End get set private
The end of the collection in a fixed array. Before the collection IsSaturated, the array is not completely utilized and we need to know where the unused part begins.
Definition at line 59 of file RingBuffer.cs.
         {
             get
             {
                 return end;
             }
             set
             {
                 var direction = Math.Sign(value - end);
                 end = (value + width) % width;
                 if (start == end)
                 {
                     Start += direction;
                 }
             }
         }
Referenced by System.Collections.Generic.RingBuffer< T >.Add(), System.Collections.Generic.RingBuffer< T >.CopyTo(), System.Collections.Generic.RingBuffer< T >.Insert(), and System.Collections.Generic.RingBuffer< T >.RemoveAt().
IsReadOnly
bool System.Collections.Generic.RingBuffer< T >.IsReadOnly get
Always returns false
Definition at line 134 of file RingBuffer.cs.
         {
             get
             {
                 return false;
             }
         }
IsSaturated
bool System.Collections.Generic.RingBuffer< T >.IsSaturated get
Returns true if all slots in the ring buffer have values.
Definition at line 99 of file RingBuffer.cs.
         {
             get
             {
                 return Count == width - 1;
             }
         }
Start
int System.Collections.Generic.RingBuffer< T >.Start get set private
The beginning of the collection in a fixed array. The collection moves once it IsSaturated, old values get dropped out and new values appended.
Definition at line 31 of file RingBuffer.cs.
         {
             get
             {
                 return start;
             }
             set
             {
                 var direction = Math.Sign(value - start);
                 start = (value + width) % width;
                 if (start == end)
                 {
                     End += direction;
                 }
             }
         }
Referenced by System.Collections.Generic.RingBuffer< T >.CopyTo().
this[int index]
T System.Collections.Generic.RingBuffer< T >.this[int index] get set
Gets or sets the element at the specified index.
Parameters
index An index into the buffer, modulated by the buffer length.
Exceptions
ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
The element at the specified index.
var buffer = new RingBuffer{int}(5); buffer.Add(3); // buffer[0] == 3 buffer.Add(1); // buffer[0] == 3, buffer[1] == 1 buffer.Add(4); // buffer[0] == 3, buffer[1] == 1, buffer[2] == 4 buffer.Add(1); // buffer[0] == 3, buffer[1] == 1, buffer[2] == 4, buffer[3] == 1 buffer.Add(5); // buffer[0] == 3, buffer[1] == 1, buffer[2] == 4, buffer[3] == 1, buffer[4] == 5 buffer.Add(9); // buffer[0] == 1, buffer[1] == 4, buffer[2] == 1, buffer[3] == 5, buffer[4] == 9 buffer.Add(2); // buffer[0] == 4, buffer[1] == 1, buffer[2] == 5, buffer[3] == 9, buffer[4] == 2 buffer[2] = 7; // buffer[0] == 4, buffer[1] == 1, buffer[2] == 7, buffer[3] == 9, buffer[4] == 2
Definition at line 160 of file RingBuffer.cs.
         {
             get
             {
                 if (index < 0 || index >= Count)
                 {
                     throw new ArgumentOutOfRangeException(nameof(index), $"Index must be between 0 and {Count}");
                 }
                 return buffer[(Start + index) % buffer.Length];
             }
             set
             {
                 if (index < 0 || index >= Count)
                 {
                     throw new ArgumentOutOfRangeException(nameof(index), $"Index must be between 0 and {Count}");
                 }
                 buffer[(Start + index) % buffer.Length] = value;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Extensions/NETFX/Collections/Generic/RingBuffer.cs