Juniper: Juniper.XR.CameraControl Class Reference
Juniper.XR.CameraControl Class Reference
Public Types
enum Mode {
Mode.None, Mode.Auto, Mode.Mouse, Mode.Gamepad,
Mode.Touch, Mode.MagicWindow
}
enum MouseButton { MouseButton.Left, MouseButton.Right, MouseButton.Middle, MouseButton.None = ~0 }
Public Member Functions
void Awake ()
void Update ()
Public Attributes
Mode mode = Mode.Mouse
bool setMouseLock = true
If we are running on a desktop system, set this value to true to lock the mouse cursor to the application window.
MouseButton requiredMouseButton
int requiredTouchCount = 1
float dragThreshold = 10
bool disableHorizontal
bool disableVertical
float sensitivityX = 0.5f
How quickly the mouse moves horizontally
float sensitivityY = 0.5f
How quickly the mouse moves vertically
float minimumY = -45F
Minimum vertical value
float maximumY = 85F
Maximum vertical value
float InterpolationFactor = 0.25f
A scale factor for the global XRSystem.InterpolationFactor. Using scale factors on the global factor makes it easier to coordinate interpolation of movements, making it easier to define harmonic relationshiops or specifically avoid them.
Protected Attributes
Quaternion dRot = Quaternion.identity
How much to rotate by, this frame.
StageExtensions stage
Properties
Vector3 MeanTouchPointMovement [get]
Private Member Functions
bool GestureSatisfied (Mode mode)
Vector3 PointerMovement (Mode mode)
bool DragRequired (Mode mode)
bool DragSatisfied (Mode mode)
void CheckMode (Mode mode, bool disableVertical)
Quaternion OrientationDelta (Mode mode, bool disableVertical)
Private Attributes
const float MOUSE_SENSITIVITY_SCALE = 100
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
const float TOUCH_SENSITIVITY_SCALE = 5
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
Transform camT
readonly Dictionary< Mode, bool > dragged = new Dictionary<Mode, bool>()
readonly Dictionary< Mode, bool > wasGestureSatisfied = new Dictionary<Mode, bool>()
readonly Dictionary< Mode, float > dragDistance = new Dictionary<Mode, float>()
Vector3 AxialMovement
Quaternion lastGyro = Quaternion.identity
Static Private Attributes
static Quaternion NEUTRAL_POSITION_RESET = Quaternion.Euler (90f, 0f, 0f)
static Quaternion FLIP_IMAGE = Quaternion.Euler (0f, 0f, 180f)
Detailed Description
Definition at line 11 of file CameraControl.cs.
Member Enumeration Documentation
Mode
enum Juniper.XR.CameraControl.Mode strong
Enumerator
None
Auto
Mouse
Gamepad
Touch
MagicWindow
Definition at line 16 of file CameraControl.cs.
         {
             None,
             Auto,
             Mouse,
             Gamepad,
             Touch,
             MagicWindow
         }
MouseButton
enum Juniper.XR.CameraControl.MouseButton strong
Enumerator
Left
Right
Middle
None
Definition at line 34 of file CameraControl.cs.
         {
             Left,
             Right,
             Middle,
             None = ~0
         }
Member Function Documentation
Awake()
void Juniper.XR.CameraControl.Awake () inline
Definition at line 103 of file CameraControl.cs.
         {
             camT = GetComponent<Camera>().transform;
             stage = this.FindAny<StageExtensions>();
             if (mode == Mode.Auto)
             {
 #if MAGIC_WINDOW
                 gyro.enabled = true;
                 compensateSensors = true;
                 mode = Mode.MagicWindow;
 #elif GOOGLEVR
                 if (setMouseLock && Application.isEditor && UnifiedInputModule.AnyActiveGoogleInstantPreview)
                 {
                     setMouseLock = false;
                 }
                 var joystick = GetJoystickNames().FirstOrDefault();
                 if (UnifiedInputModule.AnyActiveGoogleInstantPreview)
                 {
                     mode = Mode.None;
                 }
                 else if (mousePresent)
                 {
                     mode = Mode.Mouse;
                 }
                 else if (!string.IsNullOrEmpty(joystick))
                 {
                     mode = Mode.Gamepad;
                 }
 #elif !UNITY_EDITOR && (UNITY_ANDROID || UNITY_IOS)
                 var joystick = GetJoystickNames().FirstOrDefault();
                 if (touchSupported)
                 {
                     mode = Mode.Touch;
                 }
                 else if (mousePresent)
                 {
                     mode = Mode.Mouse;
                 }
                 else if (!string.IsNullOrEmpty(joystick))
                 {
                     mode = Mode.Gamepad;
                 }
 #else
                 var joystick = GetJoystickNames().FirstOrDefault();
                 if (!string.IsNullOrEmpty(joystick))
                 {
                     mode = Mode.Gamepad;
                 }
                 else if (mousePresent)
                 {
                     mode = Mode.Mouse;
                 }
                 else if (touchSupported)
                 {
                     mode = Mode.Touch;
                 }
 #endif
             }
             if (setMouseLock)
             {
                 Cursor.lockState = CursorLockMode.Locked;
             }
             else
             {
                 Cursor.lockState = CursorLockMode.None;
             }
         }
References Juniper.XR.CameraControl.camT, Juniper.XR.CameraControl.mode, Juniper.XR.CameraControl.setMouseLock, and Juniper.XR.CameraControl.stage.
CheckMode()
void Juniper.XR.CameraControl.CheckMode (Mode mode, bool disableVertical) inline private
Definition at line 278 of file CameraControl.cs.
         {
             if (!GestureSatisfied(mode))
             {
                 dragged[mode] = false;
                 dragDistance[mode] = 0;
             }
             else if (wasGestureSatisfied.Get(mode, false) && DragSatisfied(mode))
             {
                 var pos = camT.position;
                 var dRot = OrientationDelta(mode, disableVertical);
                 var endQuat = camT.rotation * dRot;
                 var endEul = endQuat.eulerAngles;
                 stage.transform.rotation = Quaternion.AngleAxis(endEul.y, Vector3.up);
                 endEul.z = 0;
                 camT.rotation = Quaternion.Euler(endEul);
                 camT.position = pos;
                 stage.UserCenter = camT.position - stage.transform.position;
             }
             wasGestureSatisfied[mode] = GestureSatisfied(mode);
         }
References Juniper.XR.CameraControl.camT, Juniper.XR.CameraControl.disableVertical, Juniper.XR.CameraControl.dragDistance, Juniper.XR.CameraControl.dragged, Juniper.XR.CameraControl.DragSatisfied(), Juniper.XR.CameraControl.dRot, Juniper.XR.CameraControl.GestureSatisfied(), Juniper.XR.CameraControl.mode, Juniper.XR.CameraControl.OrientationDelta(), Juniper.XR.CameraControl.stage, Juniper.StageExtensions.UserCenter, and Juniper.XR.CameraControl.wasGestureSatisfied.
Referenced by Juniper.XR.CameraControl.Update().
DragRequired()
bool Juniper.XR.CameraControl.DragRequired (Mode mode) private
Referenced by Juniper.XR.CameraControl.DragSatisfied().
DragSatisfied()
bool Juniper.XR.CameraControl.DragSatisfied (Mode mode) inline private
Definition at line 235 of file CameraControl.cs.
         {
             if (!DragRequired(mode))
             {
                 return true;
             }
             else
             {
                 var move = PointerMovement(mode);
                 if (DragRequired(mode) && !dragged.Get(mode, false))
                 {
                     dragDistance[mode] = dragDistance.Get(mode, 0) + (move.magnitude / Screen.dpi);
                     dragged[mode] = Units.Inches.Millimeters(dragDistance[mode]) > dragThreshold;
                 }
                 return dragged[mode];
             }
         }
References Juniper.XR.CameraControl.dragDistance, Juniper.XR.CameraControl.dragged, Juniper.XR.CameraControl.DragRequired(), Juniper.XR.CameraControl.dragThreshold, Juniper.Units.Inches.Millimeters(), Juniper.XR.CameraControl.mode, and Juniper.XR.CameraControl.PointerMovement().
Referenced by Juniper.XR.CameraControl.CheckMode().
GestureSatisfied()
bool Juniper.XR.CameraControl.GestureSatisfied (Mode mode) inline private
Definition at line 176 of file CameraControl.cs.
         {
             if (mode == Mode.None)
             {
                 return false;
             }
             else if (mode == Mode.Gamepad || mode == Mode.MagicWindow)
             {
                 return true;
             }
             else if (mode == Mode.Touch)
             {
                 return touchCount == requiredTouchCount;
             }
             else
             {
                 var pressed = requiredMouseButton == MouseButton.None || GetMouseButton((int)requiredMouseButton);
                 return pressed && (!setMouseLock || Cursor.lockState == CursorLockMode.Locked);
             }
         }
References Juniper.XR.CameraControl.mode, Juniper.XR.CameraControl.requiredMouseButton, Juniper.XR.CameraControl.requiredTouchCount, and Juniper.XR.CameraControl.setMouseLock.
Referenced by Juniper.XR.CameraControl.CheckMode().
OrientationDelta()
Quaternion Juniper.XR.CameraControl.OrientationDelta (Mode mode, bool disableVertical) inline private
Definition at line 306 of file CameraControl.cs.
         {
             if (mode == Mode.MagicWindow)
             {
                 var endQuat = NEUTRAL_POSITION_RESET
                         * gyro.attitude
                         * FLIP_IMAGE;
                 var dRot = Quaternion.Inverse(lastGyro) * endQuat;
                 lastGyro = endQuat;
                 return dRot;
             }
             else
             {
                 var move = PointerMovement(mode);
                 if (disableVertical)
                 {
                     move.x = 0;
                 }
                 else
                 {
                     move.x *= sensitivityX;
                 }
                 if (disableHorizontal)
                 {
                     move.y = 0;
                 }
                 else
                 {
                     move.y *= sensitivityY;
                 }
                 move.z = 0;
                 return Quaternion.Slerp(dRot, Quaternion.Euler(move), InterpolationFactor);
             }
         }
References Juniper.XR.CameraControl.disableHorizontal, Juniper.XR.CameraControl.disableVertical, Juniper.XR.CameraControl.dRot, Juniper.XR.CameraControl.FLIP_IMAGE, Juniper.XR.CameraControl.InterpolationFactor, Juniper.XR.CameraControl.lastGyro, Juniper.XR.CameraControl.mode, Juniper.XR.CameraControl.NEUTRAL_POSITION_RESET, Juniper.XR.CameraControl.PointerMovement(), Juniper.XR.CameraControl.sensitivityX, and Juniper.XR.CameraControl.sensitivityY.
Referenced by Juniper.XR.CameraControl.CheckMode().
PointerMovement()
Vector3 Juniper.XR.CameraControl.PointerMovement (Mode mode) inline private
Definition at line 197 of file CameraControl.cs.
         {
             switch (mode)
             {
                 case Mode.Mouse:
                 case Mode.Gamepad:
                     return AxialMovement;
                 case Mode.Touch:
                     return MeanTouchPointMovement;
                 default:
                     return Vector3.zero;
             }
         }
References Juniper.XR.CameraControl.AxialMovement, Juniper.XR.CameraControl.MeanTouchPointMovement, and Juniper.XR.CameraControl.mode.
Referenced by Juniper.XR.CameraControl.DragSatisfied(), and Juniper.XR.CameraControl.OrientationDelta().
Update()
void Juniper.XR.CameraControl.Update () inline
Definition at line 253 of file CameraControl.cs.
         {
             if (mousePresent && setMouseLock)
             {
                 Cursor.visible = Application.isEditor && Cursor.lockState == CursorLockMode.None;
                 if (GetMouseButtonDown(0))
                 {
                     Cursor.lockState = CursorLockMode.Locked;
                 }
 #if UNITY_2018_1_OR_NEWER
                 else if (GetKeyDown(KeyCode.Escape))
                 {
                     Cursor.lockState = CursorLockMode.None;
                 }
 #endif
             }
             CheckMode(mode, disableVertical);
             if (mode == Mode.MagicWindow)
             {
                 CheckMode(Mode.Touch, true);
             }
         }
References Juniper.XR.CameraControl.CheckMode(), Juniper.XR.CameraControl.disableVertical, Juniper.XR.CameraControl.mode, and Juniper.XR.CameraControl.setMouseLock.
Member Data Documentation
AxialMovement
Vector3 Juniper.XR.CameraControl.AxialMovement private
Initial value:
=>
            MOUSE_SENSITIVITY_SCALE * new Vector3(
                    -GetAxis("Mouse Y"),
                    GetAxis("Mouse X"))
Definition at line 213 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.PointerMovement().
camT
Transform Juniper.XR.CameraControl.camT private
Definition at line 95 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.Awake(), and Juniper.XR.CameraControl.CheckMode().
disableHorizontal
bool Juniper.XR.CameraControl.disableHorizontal
Definition at line 46 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.OrientationDelta().
disableVertical
bool Juniper.XR.CameraControl.disableVertical
Definition at line 47 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.CheckMode(), Juniper.XR.CameraControl.OrientationDelta(), and Juniper.XR.CameraControl.Update().
dragDistance
readonly Dictionary<Mode, float> Juniper.XR.CameraControl.dragDistance = new Dictionary<Mode, float>() private
Definition at line 101 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.CheckMode(), and Juniper.XR.CameraControl.DragSatisfied().
dragged
readonly Dictionary<Mode, bool> Juniper.XR.CameraControl.dragged = new Dictionary<Mode, bool>() private
Definition at line 99 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.CheckMode(), and Juniper.XR.CameraControl.DragSatisfied().
dragThreshold
float Juniper.XR.CameraControl.dragThreshold = 10
Definition at line 44 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.DragSatisfied().
dRot
Quaternion Juniper.XR.CameraControl.dRot = Quaternion.identity protected
How much to rotate by, this frame.
Definition at line 93 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.CheckMode(), and Juniper.XR.CameraControl.OrientationDelta().
FLIP_IMAGE
Quaternion Juniper.XR.CameraControl.FLIP_IMAGE = Quaternion.Euler (0f, 0f, 180f) static private
Definition at line 14 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.OrientationDelta().
InterpolationFactor
float Juniper.XR.CameraControl.InterpolationFactor = 0.25f
A scale factor for the global XRSystem.InterpolationFactor. Using scale factors on the global factor makes it easier to coordinate interpolation of movements, making it easier to define harmonic relationshiops or specifically avoid them.
Definition at line 88 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.OrientationDelta().
lastGyro
Quaternion Juniper.XR.CameraControl.lastGyro = Quaternion.identity private
Definition at line 304 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.OrientationDelta().
maximumY
float Juniper.XR.CameraControl.maximumY = 85F
Maximum vertical value
Definition at line 81 of file CameraControl.cs.
minimumY
float Juniper.XR.CameraControl.minimumY = -45F
Minimum vertical value
Definition at line 76 of file CameraControl.cs.
mode
Mode Juniper.XR.CameraControl.mode = Mode.Mouse
Definition at line 26 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.Awake(), Juniper.XR.CameraControl.CheckMode(), Juniper.XR.CameraControl.DragSatisfied(), Juniper.XR.CameraControl.GestureSatisfied(), Juniper.XR.CameraControl.OrientationDelta(), Juniper.XR.CameraControl.PointerMovement(), and Juniper.XR.CameraControl.Update().
MOUSE_SENSITIVITY_SCALE
const float Juniper.XR.CameraControl.MOUSE_SENSITIVITY_SCALE = 100 private
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
Definition at line 53 of file CameraControl.cs.
NEUTRAL_POSITION_RESET
Quaternion Juniper.XR.CameraControl.NEUTRAL_POSITION_RESET = Quaternion.Euler (90f, 0f, 0f) static private
Definition at line 13 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.OrientationDelta().
requiredMouseButton
MouseButton Juniper.XR.CameraControl.requiredMouseButton
Definition at line 42 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.GestureSatisfied().
requiredTouchCount
int Juniper.XR.CameraControl.requiredTouchCount = 1
Definition at line 43 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.GestureSatisfied().
sensitivityX
float Juniper.XR.CameraControl.sensitivityX = 0.5f
How quickly the mouse moves horizontally
Definition at line 65 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.OrientationDelta().
sensitivityY
float Juniper.XR.CameraControl.sensitivityY = 0.5f
How quickly the mouse moves vertically
Definition at line 71 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.OrientationDelta().
setMouseLock
bool Juniper.XR.CameraControl.setMouseLock = true
If we are running on a desktop system, set this value to true to lock the mouse cursor to the application window.
Definition at line 32 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.Awake(), Juniper.XR.CameraControl.GestureSatisfied(), and Juniper.XR.CameraControl.Update().
stage
StageExtensions Juniper.XR.CameraControl.stage protected
Definition at line 97 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.Awake(), and Juniper.XR.CameraControl.CheckMode().
TOUCH_SENSITIVITY_SCALE
const float Juniper.XR.CameraControl.TOUCH_SENSITIVITY_SCALE = 5 private
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
Definition at line 59 of file CameraControl.cs.
wasGestureSatisfied
readonly Dictionary<Mode, bool> Juniper.XR.CameraControl.wasGestureSatisfied = new Dictionary<Mode, bool>() private
Definition at line 100 of file CameraControl.cs.
Referenced by Juniper.XR.CameraControl.CheckMode().
Property Documentation
MeanTouchPointMovement
Vector3 Juniper.XR.CameraControl.MeanTouchPointMovement get private
Definition at line 219 of file CameraControl.cs.
         {
             get
             {
                 var delta = Vector2.zero;
                 for (var i = 0; i < touchCount; ++i)
                 {
                     delta += GetTouch(i).deltaPosition / touchCount;
                 }
                 delta = new Vector2(delta.y, -delta.x);
                 return TOUCH_SENSITIVITY_SCALE * delta;
             }
         }
Referenced by Juniper.XR.CameraControl.PointerMovement().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/XR/CameraControl.cs