Juniper: Juniper.HTTP.Server.Controllers.BanHammer Class Reference
Juniper.HTTP.Server.Controllers.BanHammer Class Reference
Public Member Functions
BanHammer (IEnumerable< CIDRBlock > blocks=null)
BanHammer (Stream banFileStream)
BanHammer (FileInfo banFile)
BanHammer (string banFileName)
override bool IsRequestMatch (HttpListenerRequest request)
bool IsProtocolMatch (HttpListenerRequest request)
bool IsMethodMatch (HttpListenerRequest request)
bool IsPatternMatch (HttpListenerRequest request)
bool IsAcceptable (HttpListenerRequest request)
bool IsStatusCodeMatch (HttpListenerResponse response)
bool IsHeaderMatch (HttpListenerRequest request)
virtual bool IsContextMatch (HttpListenerContext context)
async Task ExecuteAsync (HttpListenerContext context)
override bool Equals (object obj)
bool Equals (AbstractResponse other)
override string ToString ()
int CompareTo (object obj)
virtual int CompareTo (AbstractResponse other)
override int GetHashCode ()
Static Public Member Functions
static bool operator== (AbstractResponse left, AbstractResponse right)
static bool operator != (AbstractResponse left, AbstractResponse right)
static bool operator< (AbstractResponse left, AbstractResponse right)
static bool operator > (AbstractResponse left, AbstractResponse right)
static bool operator<= (AbstractResponse left, AbstractResponse right)
static bool operator >= (AbstractResponse left, AbstractResponse right)
Public Attributes
const AuthenticationSchemes AllAuthSchemes
const HttpProtocols AllProtocols = HttpProtocols.All
const HttpMethods AllMethods = HttpMethods.All
Static Public Attributes
static readonly Regex AllRoutes = new Regex(".*", RegexOptions.Compiled)
static readonly IExpression< HttpStatusCode > DefaultCode = Expr(HttpStatusCode.Continue)
static readonly IExpression< HttpStatusCode > AllStatusCodes = Empty<HttpStatusCode>()
static readonly IExpression< MediaType > AnyMediaTypes = Empty<MediaType>()
static readonly IExpression<(string Key, string Value)> NoHeaders = Empty<(string Key, string Value)>()
Protected Member Functions
override Task InvokeAsync (HttpListenerContext context)
AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name=null)
AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, MediaType acceptType, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name=null)
AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name=null)
AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, MediaType acceptType, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name=null)
AbstractResponse?? (int priority, HttpProtocols protocol, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name=null)
AbstractResponse?? (int priority, HttpProtocols protocol, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name=null)
AbstractResponse???? (int priority, HttpProtocols protocols, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, MediaType acceptType, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name=null)
AbstractResponse???? (int priority, HttpProtocols protocols, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, MediaType acceptType, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name=null)
void OnInfo (string message)
void OnWarning (string message)
void OnError (Exception exp)
Properties
List< CIDRBlock > Blocks = new List<CIDRBlock>() [get]
string Name [get]
Regex Pattern [get]
string RegexSource [get]
int ParameterCount [get]
int Priority [get]
HttpProtocols Protocols [get]
HttpMethods Methods [get]
AuthenticationSchemes Authentication [get]
IExpression< HttpStatusCode > StatusCodes [get]
IExpression< MediaType > Accept [get]
IExpression<(string Key, string Value)> Headers [get]
bool Enabled = true [get, set]
Events
EventHandler< EventArgs< CIDRBlock > > BanAdded
EventHandler< EventArgs< CIDRBlock > > BanRemoved
EventHandler< StringEventArgs > Info
EventHandler< StringEventArgs > Warning
EventHandler< ErrorEventArgs > Err
Private Member Functions
CIDRBlock GetMatchingBlock (IPAddress address)
void OnBanAdded (CIDRBlock block)
void OnBanRemoved (CIDRBlock block)
Private Attributes
readonly FileInfo banFile
Detailed Description
Definition at line 9 of file BanHammer.cs.
Constructor & Destructor Documentation
BanHammer() [1/4]
Juniper.HTTP.Server.Controllers.BanHammer.BanHammer (IEnumerable< CIDRBlock > blocks = null) inline
Definition at line 18 of file BanHammer.cs.
             : base(int.MinValue,
                 AllProtocols,
                 AllMethods,
                 AllRoutes,
                 AllAuthSchemes,
                 AnyMediaTypes,
                 AllStatusCodes,
                 NoHeaders)
         {
             if (blocks != null)
             {
                 Blocks.AddRange(blocks);
                 Blocks.Sort();
             }
         }
References Juniper.HTTP.Server.Controllers.BanHammer.Blocks.
BanHammer() [2/4]
Juniper.HTTP.Server.Controllers.BanHammer.BanHammer (Stream banFileStream) inline
Definition at line 35 of file BanHammer.cs.
             : this(CIDRBlock.Load(banFileStream))
         { }
BanHammer() [3/4]
Juniper.HTTP.Server.Controllers.BanHammer.BanHammer (FileInfo banFile) inline
Definition at line 39 of file BanHammer.cs.
             : this(CIDRBlock.Load(banFile))
         {
             this.banFile = banFile;
         }
References Juniper.HTTP.Server.Controllers.BanHammer.banFile.
BanHammer() [4/4]
Juniper.HTTP.Server.Controllers.BanHammer.BanHammer (string banFileName) inline
Definition at line 45 of file BanHammer.cs.
             : this(CIDRBlock.Load(banFileName))
         {
             banFile = new FileInfo(banFileName);
         }
References Juniper.HTTP.Server.Controllers.BanHammer.banFile.
Member Function Documentation
AbstractResponse??() [1/2]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse?? (int priority, HttpProtocols protocol, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 116 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocol,
                 Methods = methods,
                 StatusCodes = Expr(statusCode),
                 Authentication = authSchemes,
                 Accept = acceptTypes,
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
AbstractResponse??() [2/2]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse?? (int priority, HttpProtocols protocol, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 203 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocol,
                 Methods = methods,
                 StatusCodes = Expr(statusCode),
                 Authentication = authSchemes,
                 Accept = acceptTypes,
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
AbstractResponse????() [1/2]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse???? (int priority, HttpProtocols protocols, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, MediaType acceptType, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 160 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocols,
                 Methods = methods,
                 StatusCodes = Expr(statusCode),
                 Authentication = authSchemes,
                 Accept = Expr(acceptType ?? throw new ArgumentNullException(nameof(acceptType))),
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
AbstractResponse????() [2/2]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse???? (int priority, HttpProtocols protocols, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, MediaType acceptType, HttpStatusCode statusCode, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 247 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocols,
                 Methods = methods,
                 StatusCodes = Expr(statusCode),
                 Authentication = authSchemes,
                 Accept = Expr(acceptType ?? throw new ArgumentNullException(nameof(acceptType))),
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
AbstractResponse??????() [1/4]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 94 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocols,
                 Methods = methods,
                 StatusCodes = statusCodes ?? throw new ArgumentNullException(nameof(statusCodes)),
                 Authentication = authSchemes,
                 Accept = acceptTypes ?? throw new ArgumentNullException(nameof(acceptTypes)),
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
AbstractResponse??????() [2/4]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, Regex pattern, AuthenticationSchemes authSchemes, MediaType acceptType, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 138 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocols,
                 Methods = methods,
                 StatusCodes = statusCodes ?? throw new ArgumentNullException(nameof(statusCodes)),
                 Authentication = authSchemes,
                 Accept = Expr(acceptType ?? throw new ArgumentNullException(nameof(acceptType))),
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
AbstractResponse??????() [3/4]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, IExpression< MediaType > acceptTypes, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 181 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocols,
                 Methods = methods,
                 StatusCodes = statusCodes ?? throw new ArgumentNullException(nameof(statusCodes)),
                 Authentication = authSchemes,
                 Accept = acceptTypes ?? throw new ArgumentNullException(nameof(acceptTypes)),
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
AbstractResponse??????() [4/4]
Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse?????? (int priority, HttpProtocols protocols, HttpMethods methods, string pattern, AuthenticationSchemes authSchemes, MediaType acceptType, IExpression< HttpStatusCode > statusCodes, IExpression<(string Key, string Value)> headers, string name = null) inline protected inherited
Definition at line 225 of file AbstractResponse.cs.
             : this(new RouteAttribute(pattern)
             {
                 Priority = priority,
                 Protocols = protocols,
                 Methods = methods,
                 StatusCodes = statusCodes ?? throw new ArgumentNullException(nameof(statusCodes)),
                 Authentication = authSchemes,
                 Accept = Expr(acceptType ?? throw new ArgumentNullException(nameof(acceptType))),
                 Headers = headers ?? throw new ArgumentNullException(nameof(headers))
             }, name)
         { }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
CompareTo() [1/2]
int Juniper.HTTP.Server.Controllers.AbstractResponse.CompareTo (object obj) inline inherited
Definition at line 409 of file AbstractResponse.cs.
         {
             return CompareTo(obj as AbstractResponse);
         }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.Equals().
CompareTo() [2/2]
virtual int Juniper.HTTP.Server.Controllers.AbstractResponse.CompareTo (AbstractResponse other) inline virtual inherited
Reimplemented in Juniper.HTTP.Server.Controllers.AbstractRoute.
Definition at line 414 of file AbstractResponse.cs.
         {
             if (other is null)
             {
                 // sort null values to the end of the collection.
                 return -1;
             }
             else
             {
                 // smaller Priority numbers before larger Priority numbers (i.e. int.MaxValue being the "Highest Priority")
                 var priorityCompare = ((double)Priority - other.Priority).Clamp();
                 var patternCompare = string.CompareOrdinal(RegexSource, other.RegexSource).Clamp();
                 var protocolCompare = 0;
                 if (this.HasHttps() && !other.HasHttps())
                 {
                     protocolCompare = -1;
                 }
                 else if (other.HasHttps() && !this.HasHttps())
                 {
                     protocolCompare = 1;
                 }
                 var comparison = priorityCompare;
                 comparison = (comparison << 1) + patternCompare;
                 comparison = (comparison << 1) + protocolCompare;
                 return comparison.Clamp();
             }
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, and Juniper.HTTP.Server.Controllers.AbstractResponse.RegexSource.
Equals() [1/2]
override bool Juniper.HTTP.Server.Controllers.AbstractResponse.Equals (object obj) inline inherited
Definition at line 393 of file AbstractResponse.cs.
         {
             return obj is AbstractResponse other
                 && Equals(other);
         }
Equals() [2/2]
bool Juniper.HTTP.Server.Controllers.AbstractResponse.Equals (AbstractResponse other) inline inherited
Definition at line 399 of file AbstractResponse.cs.
         {
             return CompareTo(other) == 0;
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.CompareTo().
ExecuteAsync()
async Task Juniper.HTTP.Server.Controllers.AbstractResponse.ExecuteAsync (HttpListenerContext context) inline inherited
Definition at line 360 of file AbstractResponse.cs.
         {
             if (context is null)
             {
                 throw new ArgumentNullException(nameof(context));
             }
             var request = context.Request;
             var response = context.Response;
             if (!IsMethodMatch(request))
             {
                 response.SetStatus(HttpStatusCode.MethodNotAllowed);
                 response.StatusDescription = $"Expected: {Methods}. Was {request.HttpMethod}";
             }
             else if (!IsAcceptable(request))
             {
                 response.SetStatus(HttpStatusCode.NotAcceptable);
                 response.StatusDescription = $"Expected: {Accept}. Was {request.AcceptTypes.Join("|")}";
             }
             else if (!IsHeaderMatch(request))
             {
                 response.SetStatus(HttpStatusCode.BadRequest);
             }
             else
             {
                 await InvokeAsync(context)
                     .ConfigureAwait(false);
             }
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.InvokeAsync(), Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable(), Juniper.HTTP.Server.Controllers.AbstractResponse.IsHeaderMatch(), and Juniper.HTTP.Server.Controllers.AbstractResponse.IsMethodMatch().
GetHashCode()
override int Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode () inline inherited
Definition at line 445 of file AbstractResponse.cs.
         {
             var hashCode = -40035775;
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(Name);
             hashCode = (hashCode * -1521134295) + EqualityComparer<Regex>.Default.GetHashCode(Pattern);
             hashCode = (hashCode * -1521134295) + Priority.GetHashCode();
             hashCode = (hashCode * -1521134295) + Protocols.GetHashCode();
             hashCode = (hashCode * -1521134295) + Methods.GetHashCode();
             hashCode = (hashCode * -1521134295) + StatusCodes.GetHashCode();
             hashCode = (hashCode * -1521134295) + Authentication.GetHashCode();
             hashCode = (hashCode * -1521134295) + Accept.GetHashCode();
             hashCode = (hashCode * -1521134295) + Headers.GetHashCode();
             return hashCode;
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication, Juniper.HTTP.Default, Juniper.HTTP.Server.Controllers.AbstractResponse.Headers, Juniper.HTTP.Server.Controllers.AbstractResponse.Methods, Juniper.HTTP.Server.Controllers.AbstractResponse.Name, Juniper.HTTP.Server.Controllers.AbstractResponse.Pattern, Juniper.HTTP.Server.Controllers.AbstractResponse.Priority, Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols, and Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
GetMatchingBlock()
CIDRBlock Juniper.HTTP.Server.Controllers.BanHammer.GetMatchingBlock (IPAddress address) inline private
Definition at line 51 of file BanHammer.cs.
         {
             return Blocks.Find(block => block.Contains(address));
         }
References Juniper.HTTP.Server.Controllers.BanHammer.Blocks.
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.InvokeAsync(), and Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch().
InvokeAsync()
override Task Juniper.HTTP.Server.Controllers.BanHammer.InvokeAsync (HttpListenerContext context) inline protected virtual
Implements Juniper.HTTP.Server.Controllers.AbstractResponse.
Definition at line 121 of file BanHammer.cs.
         {
             var request = context.Request;
             var response = context.Response;
             var block = GetMatchingBlock(request.RemoteEndPoint.Address);
             OnInfo($"{request.RemoteEndPoint} is banned by {block}.");
             response.SetStatus(HttpStatusCode.Unauthorized);
             return Task.CompletedTask;
         }
References Juniper.HTTP.Server.Controllers.BanHammer.GetMatchingBlock(), and Juniper.HTTP.Server.Controllers.AbstractResponse.OnInfo().
IsAcceptable()
bool Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable (HttpListenerRequest request) inline inherited
Definition at line 305 of file AbstractResponse.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             var requestedTypes = MediaType.ParseAll(request.AcceptTypes);
             return requestedTypes.Any(t1 => Accept.Evaluate(Always.Eq(t1)));
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Accept, and Juniper.MediaType.ParseAll().
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.ExecuteAsync(), and Juniper.HTTP.Server.Controllers.StaticFileServer.InvokeAsync().
IsContextMatch()
virtual bool Juniper.HTTP.Server.Controllers.AbstractResponse.IsContextMatch (HttpListenerContext context) inline virtual inherited
Definition at line 337 of file AbstractResponse.cs.
         {
             if (context is null)
             {
                 throw new ArgumentNullException(nameof(context));
             }
             return IsStatusCodeMatch(context.Response)
                 && IsRequestMatch(context.Request);
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.IsRequestMatch(), and Juniper.HTTP.Server.Controllers.AbstractResponse.IsStatusCodeMatch().
IsHeaderMatch()
bool Juniper.HTTP.Server.Controllers.AbstractResponse.IsHeaderMatch (HttpListenerRequest request) inline inherited
Definition at line 322 of file AbstractResponse.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             var headers = request.Headers;
             return Headers.Evaluate(h =>
                 (h.Value is null && headers[h.Key] is null)
                 || (h.Value is object && h.Value.Equals(
                         request.Headers[h.Key],
                         StringComparison.InvariantCultureIgnoreCase)));
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Headers.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.ExecuteAsync().
IsMethodMatch()
bool Juniper.HTTP.Server.Controllers.AbstractResponse.IsMethodMatch (HttpListenerRequest request) inline inherited
Definition at line 282 of file AbstractResponse.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             var reqMethod = request.HttpMethod;
             var hasMethod = Enum.TryParse<HttpMethods>(reqMethod, true, out var verb);
             var isMethodMatch = (Methods & verb) != 0;
             return hasMethod && isMethodMatch;
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Methods.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.ExecuteAsync().
IsPatternMatch()
bool Juniper.HTTP.Server.Controllers.AbstractResponse.IsPatternMatch (HttpListenerRequest request) inline inherited
Definition at line 295 of file AbstractResponse.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             return Pattern.IsMatch(request.Url.PathAndQuery);
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Pattern.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsRequestMatch().
IsProtocolMatch()
bool Juniper.HTTP.Server.Controllers.AbstractResponse.IsProtocolMatch (HttpListenerRequest request) inline inherited
Definition at line 269 of file AbstractResponse.cs.
         {
             if (request is null)
             {
                 throw new ArgumentNullException(nameof(request));
             }
             var reqProtocol = request.Url.Scheme;
             var hasProtocol = Enum.TryParse<HttpProtocols>(reqProtocol, true, out var protocol);
             var isProtocolMatch = (Protocols & protocol) != 0;
             return hasProtocol && isProtocolMatch;
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsRequestMatch().
IsRequestMatch()
override bool Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch (HttpListenerRequest request) inline virtual
Reimplemented from Juniper.HTTP.Server.Controllers.AbstractResponse.
Definition at line 56 of file BanHammer.cs.
         {
             if (!base.IsRequestMatch(request))
             {
                 return false;
             }
             var block = GetMatchingBlock(request.RemoteEndPoint.Address);
             if (block is object)
             {
                 return true;
             }
             if (request.Url.PathAndQuery.ContainsIgnoreCase(".php"))
             {
                 var added = new List<CIDRBlock>();
                 var removed = new List<CIDRBlock>();
                 block = new CIDRBlock(request.RemoteEndPoint.Address);
                 OnWarning($"Auto-banning {block}");
                 added.Add(block);
                 Blocks.Add(block);
                 Blocks.Sort();
                 for (var i = Blocks.Count - 1; i > 0; --i)
                 {
                     var right = Blocks[i];
                     var left = Blocks[i - 1];
                     if (left.Overlaps(right))
                     {
                         Blocks[i - 1] = left + right;
                         Blocks.RemoveAt(i);
                         _ = added.Remove(left);
                         _ = removed.MaybeAdd(left);
                         _ = added.Remove(right);
                         _ = removed.MaybeAdd(right);
                         _ = removed.Remove(Blocks[i - 1]);
                         _ = added.MaybeAdd(Blocks[i - 1]);
                     }
                 }
                 foreach (var b in removed)
                 {
                     OnBanRemoved(b);
                 }
                 foreach (var b in added)
                 {
                     OnBanAdded(b);
                 }
                 if (banFile is object)
                 {
                     CIDRBlock.Save(Blocks, banFile);
                 }
                 return true;
             }
             return false;
         }
References Juniper.HTTP.Server.Controllers.BanHammer.banFile, Juniper.HTTP.Server.Controllers.BanHammer.Blocks, Juniper.HTTP.Server.Controllers.BanHammer.GetMatchingBlock(), Juniper.HTTP.Server.Controllers.BanHammer.OnBanAdded(), Juniper.HTTP.Server.Controllers.BanHammer.OnBanRemoved(), Juniper.HTTP.Server.Controllers.AbstractResponse.OnWarning(), and Juniper.HTTP.Server.CIDRBlock.Save().
IsStatusCodeMatch()
bool Juniper.HTTP.Server.Controllers.AbstractResponse.IsStatusCodeMatch (HttpListenerResponse response) inline inherited
Definition at line 316 of file AbstractResponse.cs.
         {
             var curStatus = response.GetStatus();
             return StatusCodes.Evaluate(Always.Eq(curStatus));
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsContextMatch().
OnBanAdded()
void Juniper.HTTP.Server.Controllers.BanHammer.OnBanAdded (CIDRBlock block) inline private
Definition at line 131 of file BanHammer.cs.
         {
             BanAdded?.Invoke(this, new EventArgs<CIDRBlock>(block));
         }
References Juniper.HTTP.Server.Controllers.BanHammer.BanAdded.
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch().
OnBanRemoved()
void Juniper.HTTP.Server.Controllers.BanHammer.OnBanRemoved (CIDRBlock block) inline private
Definition at line 136 of file BanHammer.cs.
         {
             BanRemoved?.Invoke(this, new EventArgs<CIDRBlock>(block));
         }
References Juniper.HTTP.Server.Controllers.BanHammer.BanRemoved.
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch().
OnError()
void Juniper.HTTP.Server.Controllers.AbstractResponse.OnError (Exception exp) inline protected inherited
Definition at line 507 of file AbstractResponse.cs.
         {
             Err?.Invoke(this, new ErrorEventArgs(exp));
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Err.
OnInfo()
void Juniper.HTTP.Server.Controllers.AbstractResponse.OnInfo (string message) inline protected inherited
Definition at line 495 of file AbstractResponse.cs.
         {
             Info?.Invoke(this, new StringEventArgs(message));
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Info.
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.InvokeAsync().
OnWarning()
void Juniper.HTTP.Server.Controllers.AbstractResponse.OnWarning (string message) inline protected inherited
Definition at line 501 of file AbstractResponse.cs.
         {
             Warning?.Invoke(this, new StringEventArgs(message));
         }
References Juniper.HTTP.Server.Controllers.AbstractResponse.Warning.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.InvokeAsync(), and Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch().
operator !=()
static bool Juniper.HTTP.Server.Controllers.AbstractResponse.operator != (AbstractResponse left, AbstractResponse right) inline static inherited
Definition at line 467 of file AbstractResponse.cs.
         {
             return !(left == right);
         }
operator >()
static bool Juniper.HTTP.Server.Controllers.AbstractResponse.operator > (AbstractResponse left, AbstractResponse right) inline static inherited
Definition at line 478 of file AbstractResponse.cs.
         {
             return (left is object && left.CompareTo(right) == 1)
                 || (right is object && right.CompareTo(left) == -1);
         }
operator >=()
static bool Juniper.HTTP.Server.Controllers.AbstractResponse.operator >= (AbstractResponse left, AbstractResponse right) inline static inherited
Definition at line 489 of file AbstractResponse.cs.
         {
             return left > right || left == right;
         }
operator<()
static bool Juniper.HTTP.Server.Controllers.AbstractResponse.operator< (AbstractResponse left, AbstractResponse right) inline static inherited
Definition at line 472 of file AbstractResponse.cs.
         {
             return (left is object && left.CompareTo(right) == -1)
                 || (right is object && right.CompareTo(left) == 1);
         }
operator<=()
static bool Juniper.HTTP.Server.Controllers.AbstractResponse.operator<= (AbstractResponse left, AbstractResponse right) inline static inherited
Definition at line 484 of file AbstractResponse.cs.
         {
             return left < right || left == right;
         }
operator==()
static bool Juniper.HTTP.Server.Controllers.AbstractResponse.operator== (AbstractResponse left, AbstractResponse right) inline static inherited
Definition at line 460 of file AbstractResponse.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.CompareTo(right) == 0)
                 || (right is object && right.CompareTo(left) == 0);
         }
ToString()
override string Juniper.HTTP.Server.Controllers.AbstractResponse.ToString () inline inherited
Definition at line 404 of file AbstractResponse.cs.
         {
             return $"{Name}[{Priority,10}]: {Protocols} {Methods} {StatusCodes} {Authentication}";
         }
Member Data Documentation
AllAuthSchemes
const AuthenticationSchemes Juniper.HTTP.Server.Controllers.AbstractResponse.AllAuthSchemes inherited
Initial value:
= AuthenticationSchemes.Digest
            | AuthenticationSchemes.Negotiate
            | AuthenticationSchemes.Ntlm
            | AuthenticationSchemes.Basic
            | AuthenticationSchemes.Anonymous
Definition at line 23 of file AbstractResponse.cs.
Referenced by Juniper.HTTP.Server.HttpServer.ShowRoutes().
AllMethods
const HttpMethods Juniper.HTTP.Server.Controllers.AbstractResponse.AllMethods = HttpMethods.All inherited
Definition at line 31 of file AbstractResponse.cs.
AllProtocols
const HttpProtocols Juniper.HTTP.Server.Controllers.AbstractResponse.AllProtocols = HttpProtocols.All inherited
Definition at line 29 of file AbstractResponse.cs.
AllRoutes
readonly Regex Juniper.HTTP.Server.Controllers.AbstractResponse.AllRoutes = new Regex(".*", RegexOptions.Compiled) static inherited
Definition at line 33 of file AbstractResponse.cs.
AllStatusCodes
readonly IExpression<HttpStatusCode> Juniper.HTTP.Server.Controllers.AbstractResponse.AllStatusCodes = Empty<HttpStatusCode>() static inherited
Definition at line 37 of file AbstractResponse.cs.
AnyMediaTypes
readonly IExpression<MediaType> Juniper.HTTP.Server.Controllers.AbstractResponse.AnyMediaTypes = Empty<MediaType>() static inherited
Definition at line 39 of file AbstractResponse.cs.
banFile
readonly FileInfo Juniper.HTTP.Server.Controllers.BanHammer.banFile private
Definition at line 11 of file BanHammer.cs.
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.BanHammer(), and Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch().
DefaultCode
readonly IExpression<HttpStatusCode> Juniper.HTTP.Server.Controllers.AbstractResponse.DefaultCode = Expr(HttpStatusCode.Continue) static inherited
Definition at line 35 of file AbstractResponse.cs.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse().
NoHeaders
readonly IExpression<(string Key, string Value)> Juniper.HTTP.Server.Controllers.AbstractResponse.NoHeaders = Empty<(string Key, string Value)>() static inherited
Definition at line 41 of file AbstractResponse.cs.
Property Documentation
Accept
IExpression<MediaType> Juniper.HTTP.Server.Controllers.AbstractResponse.Accept get inherited
Definition at line 61 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse????(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??????(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable(), Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute(), and Juniper.HTTP.Server.Controllers.WebSocketRoute.ValidateRoute().
Authentication
AuthenticationSchemes Juniper.HTTP.Server.Controllers.AbstractResponse.Authentication get inherited
Definition at line 57 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse????(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??????(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute(), and Juniper.HTTP.Server.Controllers.WebSocketRoute.ValidateRoute().
Blocks
List<CIDRBlock> Juniper.HTTP.Server.Controllers.BanHammer.Blocks = new List<CIDRBlock>() get
Definition at line 13 of file BanHammer.cs.
 { get; } = new List<CIDRBlock>();
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.BanHammer(), Juniper.HTTP.Server.Controllers.BanHammer.GetMatchingBlock(), and Juniper.HTTP.Server.Controllers.BanHammer.IsRequestMatch().
Enabled
bool Juniper.HTTP.Server.Controllers.AbstractResponse.Enabled = true get set inherited
Definition at line 65 of file AbstractResponse.cs.
 { get; set; } = true;
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsRequestMatch().
Headers
IExpression<(string Key, string Value)> Juniper.HTTP.Server.Controllers.AbstractResponse.Headers get inherited
Definition at line 63 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse????(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??????(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), Juniper.HTTP.Server.Controllers.AbstractResponse.IsHeaderMatch(), Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute(), and Juniper.HTTP.Server.Controllers.WebSocketRoute.ValidateRoute().
Methods
HttpMethods Juniper.HTTP.Server.Controllers.AbstractResponse.Methods get inherited
Definition at line 55 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse????(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??????(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), Juniper.HTTP.Server.Controllers.AbstractResponse.IsMethodMatch(), and Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute().
Name
string Juniper.HTTP.Server.Controllers.AbstractResponse.Name get inherited
Definition at line 43 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), and Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute().
ParameterCount
int Juniper.HTTP.Server.Controllers.AbstractResponse.ParameterCount get inherited
Definition at line 49 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse().
Pattern
Regex Juniper.HTTP.Server.Controllers.AbstractResponse.Pattern get inherited
Definition at line 45 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractRoute.Equals(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), Juniper.HTTP.Server.Controllers.AbstractRoute.InvokeAsync(), and Juniper.HTTP.Server.Controllers.AbstractResponse.IsPatternMatch().
Priority
int Juniper.HTTP.Server.Controllers.AbstractResponse.Priority get inherited
Definition at line 51 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse????(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??????(), Juniper.HTTP.Server.Controllers.AbstractResponse.CompareTo(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), and Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute().
Protocols
HttpProtocols Juniper.HTTP.Server.Controllers.AbstractResponse.Protocols get inherited
Definition at line 53 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse????(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??????(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), Juniper.HTTP.Server.Controllers.AbstractResponse.IsProtocolMatch(), and Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute().
RegexSource
string Juniper.HTTP.Server.Controllers.AbstractResponse.RegexSource get inherited
Definition at line 47 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractRoute.CompareTo(), and Juniper.HTTP.Server.Controllers.AbstractResponse.CompareTo().
StatusCodes
IExpression<HttpStatusCode> Juniper.HTTP.Server.Controllers.AbstractResponse.StatusCodes get inherited
Definition at line 59 of file AbstractResponse.cs.
 { get; }
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse????(), Juniper.HTTP.Server.Controllers.AbstractResponse.AbstractResponse??????(), Juniper.HTTP.Server.Controllers.AbstractResponse.GetHashCode(), Juniper.HTTP.Server.Controllers.AbstractResponse.IsStatusCodeMatch(), and Juniper.HTTP.Server.Controllers.HttpRoute.ValidateRoute().
Event Documentation
BanAdded
EventHandler<EventArgs<CIDRBlock> > Juniper.HTTP.Server.Controllers.BanHammer.BanAdded
Definition at line 15 of file BanHammer.cs.
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.OnBanAdded().
BanRemoved
EventHandler<EventArgs<CIDRBlock> > Juniper.HTTP.Server.Controllers.BanHammer.BanRemoved
Definition at line 16 of file BanHammer.cs.
Referenced by Juniper.HTTP.Server.Controllers.BanHammer.OnBanRemoved().
Err
EventHandler<ErrorEventArgs> Juniper.HTTP.Server.Controllers.AbstractResponse.Err inherited
Definition at line 71 of file AbstractResponse.cs.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.OnError().
Info
EventHandler<StringEventArgs> Juniper.HTTP.Server.Controllers.AbstractResponse.Info inherited
Definition at line 69 of file AbstractResponse.cs.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.OnInfo().
Warning
EventHandler<StringEventArgs> Juniper.HTTP.Server.Controllers.AbstractResponse.Warning inherited
Definition at line 70 of file AbstractResponse.cs.
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.OnWarning().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Server/Controllers/BanHammer.cs