Juniper: Juniper.XR.GoogleARCoreGroundPlaneVisualizer Class Reference
Juniper.XR.GoogleARCoreGroundPlaneVisualizer Class Reference
Visualizes a TrackedPlane in the Unity scene.
Public Member Functions
void Reset ()
void Install ()
void Uninstall ()
Static Public Member Functions
static GoogleARCoreGroundPlaneVisualizer Initialize (TrackedPlane plane)
Initializes the TrackedPlaneVisualizer with a TrackedPlane.
Public Attributes
Mesh mesh
A mesh object for rendering the polygon.
Properties
Material CurrentGroundMeshMaterial [get, set]
Private Member Functions
void Awake ()
Creates the mesh, mesh renderer, and mesh collider.
[instance initializer]
void Update ()
Looks for new tracked planes and creates meshes for them.
void UpdateMeshIfNeeded ()
Update mesh with a list of Vector3 and plane's center position.
Private Attributes
TrackedPlane trackedPlane
The ARCore tracked plane object.
List< Vector3 > previousFrameMeshVertices = new List<Vector3>()
Keeps the previous frame's mesh polygon to avoid mesh update every frame.
List< Vector3 > meshVertices = new List<Vector3>()
The mesh polygon for the current frame.
int [] meshIndices
The ordering of vertices in the polygon.
MeshRenderer meshRenderer
The renderer for mesh.
MeshCollider meshCollider
A collider for mesh.
Static Private Attributes
static int count = 0
The number of ground planes that are currently being tracked.
Detailed Description
Visualizes a TrackedPlane in the Unity scene.
Definition at line 13 of file GoogleARCoreGroundPlaneVisualizer.cs.
Member Function Documentation
[instance initializer]()
Juniper.XR.GoogleARCoreGroundPlaneVisualizer.[instance initializer] () inline private
Awake()
void Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Awake () private
Creates the mesh, mesh renderer, and mesh collider.
Initialize()
static GoogleARCoreGroundPlaneVisualizer Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Initialize (TrackedPlane plane) inline static
Initializes the TrackedPlaneVisualizer with a TrackedPlane.
Parameters
plane The plane to vizualize.
Definition at line 24 of file GoogleARCoreGroundPlaneVisualizer.cs.
         {
             var planeObject = new GameObject(string.Format("GroundPlane_{0}", count++));
             var gpv = planeObject.AddComponent<GoogleARCoreGroundPlaneVisualizer>();
             gpv.trackedPlane = plane;
             var planeVisualizer = planeObject.AddComponent<TrackedPlaneVisualizer>();
             planeVisualizer.Initialize(plane);
             return gpv;
         }
References Juniper.XR.GoogleARCoreGroundPlaneVisualizer.count, and Juniper.XR.GoogleARCoreGroundPlaneVisualizer.trackedPlane.
Referenced by Juniper.XR.Ground.Update().
Install()
void Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Install ()
Implements Juniper.IInstallable.
Reset()
void Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Reset ()
Uninstall()
void Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 85 of file GoogleARCoreGroundPlaneVisualizer.cs.
 { }
Update()
void Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Update () inline private
Looks for new tracked planes and creates meshes for them.
Definition at line 90 of file GoogleARCoreGroundPlaneVisualizer.cs.
         {
             if (trackedPlane != null)
             {
                 if (trackedPlane.SubsumedBy != null)
                 {
                     Destroy(gameObject);
                 }
                 else if (Session.Status != SessionStatus.Tracking)
                 {
                     meshCollider.enabled = meshRenderer.enabled = false;
                 }
                 else
                 {
                     meshCollider.enabled = meshRenderer.enabled = true;
                     UpdateMeshIfNeeded();
                 }
             }
         }
References Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshCollider, Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshRenderer, Juniper.XR.GoogleARCoreGroundPlaneVisualizer.trackedPlane, and Juniper.XR.GoogleARCoreGroundPlaneVisualizer.UpdateMeshIfNeeded().
UpdateMeshIfNeeded()
void Juniper.XR.GoogleARCoreGroundPlaneVisualizer.UpdateMeshIfNeeded () inline private
Update mesh with a list of Vector3 and plane's center position.
Definition at line 119 of file GoogleARCoreGroundPlaneVisualizer.cs.
         {
             trackedPlane.GetBoundaryPolygon(meshVertices);
             if (!previousFrameMeshVertices.Matches(meshVertices))
             {
                 previousFrameMeshVertices.Clear();
                 previousFrameMeshVertices.AddRange(meshVertices);
                 // A_______B |\ | | \ | | \ | | \ | | \| D-------C
                 int planePolygonCount = meshVertices.Count - 2;
                 meshIndices = new int[planePolygonCount * 3];
                 for (int i = 1; i < planePolygonCount - 1; ++i)
                 {
                     int A = 0;
                     int B = i;
                     int C = i + 1;
                     int n = i * 3;
                     meshIndices[n] = A;
                     meshIndices[n + 1] = B;
                     meshIndices[n + 2] = C;
                 }
                 float minY = float.MaxValue,
                     minX = float.MaxValue,
                     maxX = float.MinValue,
                     minZ = float.MaxValue,
                     maxZ = float.MinValue;
                 for (int i = 0; i < meshVertices.Count; ++i)
                 {
                     var v = meshVertices[i];
                     minY = Mathf.Min(minY, v.y);
                     minX = Mathf.Min(minX, v.x);
                     maxX = Mathf.Max(maxX, v.x);
                     minZ = Mathf.Min(minZ, v.z);
                     maxZ = Mathf.Max(maxZ, v.z);
                 }
                 float midX = 0.5f * (minX + maxX),
                     midZ = 0.5f * (minZ + maxZ);
                 var loc = new Vector3(midX, minY, midZ);
                 for (int i = 0; i < meshVertices.Count; ++i)
                 {
                     meshVertices[i] -= loc;
                 }
                 transform.position = loc;
                 mesh.Clear();
                 mesh.SetVertices(meshVertices);
                 mesh.SetIndices(meshIndices, MeshTopology.Triangles, 0);
             }
         }
References Juniper.XR.GoogleARCoreGroundPlaneVisualizer.mesh, Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshIndices, Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshVertices, Juniper.XR.GoogleARCoreGroundPlaneVisualizer.previousFrameMeshVertices, and Juniper.XR.GoogleARCoreGroundPlaneVisualizer.trackedPlane.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Update().
Member Data Documentation
count
int Juniper.XR.GoogleARCoreGroundPlaneVisualizer.count = 0 static private
The number of ground planes that are currently being tracked.
Definition at line 18 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Initialize().
mesh
Mesh Juniper.XR.GoogleARCoreGroundPlaneVisualizer.mesh
A mesh object for rendering the polygon.
Definition at line 57 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.UpdateMeshIfNeeded().
meshCollider
MeshCollider Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshCollider private
A collider for mesh.
Definition at line 67 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Update().
meshIndices
int [] Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshIndices private
The ordering of vertices in the polygon.
Definition at line 52 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.UpdateMeshIfNeeded().
meshRenderer
MeshRenderer Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshRenderer private
The renderer for mesh.
Definition at line 62 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Update().
meshVertices
List<Vector3> Juniper.XR.GoogleARCoreGroundPlaneVisualizer.meshVertices = new List<Vector3>() private
The mesh polygon for the current frame.
Definition at line 47 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.UpdateMeshIfNeeded().
previousFrameMeshVertices
List<Vector3> Juniper.XR.GoogleARCoreGroundPlaneVisualizer.previousFrameMeshVertices = new List<Vector3>() private
Keeps the previous frame's mesh polygon to avoid mesh update every frame.
Definition at line 42 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.UpdateMeshIfNeeded().
trackedPlane
TrackedPlane Juniper.XR.GoogleARCoreGroundPlaneVisualizer.trackedPlane private
The ARCore tracked plane object.
Definition at line 37 of file GoogleARCoreGroundPlaneVisualizer.cs.
Referenced by Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Initialize(), Juniper.XR.GoogleARCoreGroundPlaneVisualizer.Update(), and Juniper.XR.GoogleARCoreGroundPlaneVisualizer.UpdateMeshIfNeeded().
Property Documentation
CurrentGroundMeshMaterial
Material Juniper.XR.GoogleARCoreGroundPlaneVisualizer.CurrentGroundMeshMaterial get set
Definition at line 111 of file GoogleARCoreGroundPlaneVisualizer.cs.
         {
             get { return meshRenderer.GetMaterial(); }
             set { meshRenderer.SetMaterial(value); }
         }
Referenced by Juniper.XR.Ground.Update().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/XR/GoogleARCoreGroundPlaneVisualizer.cs