Juniper: Juniper.Installable Class Reference
Juniper.Installable Class Reference
Static Public Member Functions
static int InstallAll (Func< IEnumerable< IInstallable >> getInstallables)
static void UninstallAll (Func< IEnumerable< IInstallable >> getInstallables)
Detailed Description
Definition at line 16 of file IInstallable.cs.
Member Function Documentation
InstallAll()
static int Juniper.Installable.InstallAll (Func< IEnumerable< IInstallable >> getInstallables) inline static
Definition at line 18 of file IInstallable.cs.
         {
             var installed = new List<IInstallable>();
             var keepFinding = true;
             for (var i = 0; i < 10 && keepFinding; ++i)
             {
                 keepFinding = false;
                 foreach (var installable in getInstallables())
                 {
                     if (!installed.Contains(installable))
                     {
                         keepFinding = true;
                         if (installable.Install(true))
{
                             installed.Add(installable);
                         }
                     }
                 }
             }
             return getInstallables().Count() - installed.Count;
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.InternalInstall().
UninstallAll()
static void Juniper.Installable.UninstallAll (Func< IEnumerable< IInstallable >> getInstallables) inline static
Definition at line 41 of file IInstallable.cs.
         {
             foreach (var installable in getInstallables())
             {
                 installable.Uninstall();
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.Uninstall().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/IInstallable.cs