Juniper: Hjg.Pngcs.PngCsUtils Class Reference
Hjg.Pngcs.PngCsUtils Class Reference
Utility functions for C# porting
Static Private Member Functions
static internal bool arraysEqual4 (byte[] ar1, byte[] ar2)
static internal bool arraysEqual (byte[] a1, byte[] a2)
Detailed Description
Utility functions for C# porting
Definition at line 7 of file PngCsUtils.cs.
Member Function Documentation
arraysEqual()
static internal bool Hjg.Pngcs.PngCsUtils.arraysEqual (byte [] a1, byte [] a2) inline static private
Definition at line 17 of file PngCsUtils.cs.
         {
             if (a1.Length != a2.Length)
             {
                 return false;
             }
             for (var i = 0; i < a1.Length; i++)
             {
                 if (a1[i] != a2[i])
                 {
                     return false;
                 }
             }
             return true;
         }
Referenced by Hjg.Pngcs.PngReader.PngReader().
arraysEqual4()
static internal bool Hjg.Pngcs.PngCsUtils.arraysEqual4 (byte [] ar1, byte [] ar2) inline static private
Definition at line 9 of file PngCsUtils.cs.
         {
             return (ar1[0] == ar2[0]) &&
                    (ar1[1] == ar2[1]) &&
                    (ar1[2] == ar2[2]) &&
                    (ar1[3] == ar2[3]);
         }
Referenced by Hjg.Pngcs.PngIDatChunkInputStream.EndChunkGoForNext(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadFirstChunks(), and Hjg.Pngcs.PngReader.ReadLastChunks().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/PngCsUtils.cs