Juniper: Juniper.Widgets.Openable Class Reference
Juniper.Widgets.Openable Class Reference
A control that is a container of other controls that are hidden until the control is clicked.
Public Member Functions
void SetOpen (bool value)
If the control is not disabled, sets the open state.
void ToggleOpen ()
If the control is closed, open it. If it's open, close it.
override void OnPointerClick (PointerEventData eventData)
If the control is not disabled, toggles the open state.
void OnLongPress (PointerEventData evt)
void OnLongPressUpdate (PointerEventData evt)
void SetDisabled (bool value)
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
void ToggleEnabled ()
Toggles the boolean value of the disabled field.
virtual void OnPointerEnter (PointerEventData eventData)
Reqct to the pointer hovering over the control.
virtual void OnPointerExit (PointerEventData eventData)
React to the pointer leaving the control and no longer hovering over it.
virtual void OnPointerDown (PointerEventData eventData)
React to the primary button being pressed on the control.
virtual void OnPointerUp (PointerEventData eventData)
React to the primary button being released from the control.
Public Attributes
Transform payload
The scene sub-graph to show when this control is opened.
bool Open
Is the control in its open state?
bool OpenChanged
Did the Open state change since the last frame?
bool Opened
Did the control Open on this frame?
bool Closed
Did the value of Open become false on this frame?
UnityEvent onClick
The event to call when the button is enabled and clicked. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr Click.
UnityEvent onLongPress
InputButton clickButton
The button we are expecting to use to interact with this object.
bool disabled
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occuring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Vector3 pointerPosition
The place near the control that the pointer was pointing.
Static Public Attributes
static string [] PART_NAMES
The names of the animation states that Touchable expects.
Protected Member Functions
override void Awake ()
Finds the payload and checks to see if it's already open.
override void Update ()
Make sure the state hasn't changed outside of our control.
override void LateUpdate ()
Save whether or not the control was open.
virtual void OnClick ()
Trigger the onClick/click events, if they are valid;
virtual void OnLongPress ()
string ShowState (string enabledPart)
Trigger the animation or swap the gameObjects to show the current control UI state.
void GetPosition (PointerEventData eventData)
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Protected Attributes
Vector3 lastPointerPosition
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
bool PointerPositionChanged
Returns true when pointerPosition has changed since the last frame.
Properties
bool IsDisabled [get, set]
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
Events
EventHandler Click
The event to call when the button is enabled and clicked. You should only use this verison if you are programmatically attaching event listenters. if you are using the Unity Editor, you should prefer onClick.
EventHandler LongPress
Private Attributes
AbstractTransitionController stater
If the payload has a TransitionController on it, then Openable will use it as part of the open/close process.
bool wasOpen
The Open state of the container from the last frame. On startup, there is no "last frame", so the value initializes to null for three-value logic.
Detailed Description
A control that is a container of other controls that are hidden until the control is clicked.
Definition at line 14 of file Openable.cs.
Member Function Documentation
Awake()
override void Juniper.Widgets.Openable.Awake () inline protected virtual
Finds the payload and checks to see if it's already open.
Reimplemented from Juniper.Widgets.AbstractTouchable.
Definition at line 93 of file Openable.cs.
         {
             payload = transform.Find("Payload");
             stater = payload.GetComponent<AbstractTransitionController>();
             base.Awake();
         }
References Juniper.Widgets.Openable.payload, and Juniper.Widgets.Openable.stater.
GetPosition()
void Juniper.Widgets.AbstractTouchable.GetPosition (PointerEventData eventData) inline protected inherited
Saves the worldSpace position of any pointer events that were fired on this object. The worldSpace position is then used by Draggable objects to figure out where to move them.
Parameters
eventData Event data.
Definition at line 195 of file AbstractTouchable.cs.
         {
             pointerPosition = eventData.pointerCurrentRaycast.worldPosition;
             eventData.Use();
         }
References Juniper.Widgets.AbstractTouchable.pointerPosition.
Referenced by Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Widgets.AbstractTouchable.OnPointerUp().
LateUpdate()
override void Juniper.Widgets.Openable.LateUpdate () inline protected virtual
Save whether or not the control was open.
Reimplemented from Juniper.Widgets.AbstractTouchable.
Definition at line 125 of file Openable.cs.
         {
             base.LateUpdate();
             wasOpen = Open;
         }
References Juniper.Widgets.Openable.Open, and Juniper.Widgets.Openable.wasOpen.
OnClick()
virtual void Juniper.Widgets.Clickable.OnClick () inline protected virtual inherited
Trigger the onClick/click events, if they are valid;
Reimplemented in Juniper.Widgets.TeleportPad.
Definition at line 52 of file Clickable.cs.
         {
             onClick?.Invoke();
             Click?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Widgets.Clickable.Click, and Juniper.Widgets.Clickable.onClick.
Referenced by Juniper.Widgets.Clickable.OnPointerClick().
OnLongPress() [1/2]
void Juniper.Widgets.Clickable.OnLongPress (PointerEventData evt) inline inherited
Implements Juniper.Events.ILongPressHandler.
Definition at line 58 of file Clickable.cs.
         {
             if (evt.button == clickButton && !IsDisabled)
             {
                 OnLongPress();
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.Clickable.OnLongPress().
OnLongPress() [2/2]
virtual void Juniper.Widgets.Clickable.OnLongPress () inline protected virtual inherited
Definition at line 66 of file Clickable.cs.
         {
             onLongPress?.Invoke();
             LongPress?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Widgets.Clickable.LongPress, and Juniper.Widgets.Clickable.onLongPress.
Referenced by Juniper.Widgets.Clickable.OnLongPress().
OnLongPressUpdate()
void Juniper.Widgets.Clickable.OnLongPressUpdate (PointerEventData evt) inline inherited
Implements Juniper.Events.ILongPressHandler.
Definition at line 72 of file Clickable.cs.
         {
             if (evt.button == clickButton && !IsDisabled)
             {
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, and Juniper.Widgets.AbstractTouchable.IsDisabled.
OnPointerClick()
override void Juniper.Widgets.Openable.OnPointerClick (PointerEventData eventData) inline virtual
If the control is not disabled, toggles the open state.
Parameters
eventData Event data.
Reimplemented from Juniper.Widgets.Clickable.
Definition at line 84 of file Openable.cs.
         {
             base.OnPointerClick(eventData);
             ToggleOpen();
         }
References Juniper.Widgets.Openable.ToggleOpen().
OnPointerDown()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerDown (PointerEventData eventData) inline virtual inherited
React to the primary button being pressed on the control.
Parameters
eventData Event data.
Definition at line 231 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton)
             {
                 if (IsDisabled)
                 {
                     ShowState("Disabled");
                 }
                 else
                 {
                     GetPosition(eventData);
                     ShowState("Pressed");
                 }
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerEnter()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerEnter (PointerEventData eventData) inline virtual inherited
Reqct to the pointer hovering over the control.
Parameters
eventData Event data.
Definition at line 205 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerExit()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerExit (PointerEventData eventData) inline virtual inherited
React to the pointer leaving the control and no longer hovering over it.
Parameters
eventData Event data.
Definition at line 218 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Normal");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
OnPointerUp()
virtual void Juniper.Widgets.AbstractTouchable.OnPointerUp (PointerEventData eventData) inline virtual inherited
React to the primary button being released from the control.
Parameters
eventData Event data.
Definition at line 251 of file AbstractTouchable.cs.
         {
             if (eventData.button == clickButton && !IsDisabled)
             {
                 GetPosition(eventData);
                 ShowState("Hovered");
             }
         }
References Juniper.Widgets.AbstractTouchable.clickButton, Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.IsDisabled, and Juniper.Widgets.AbstractTouchable.ShowState().
SetDisabled()
void Juniper.Widgets.AbstractTouchable.SetDisabled (bool value) inherited
Set whether or not the control should operate in the "Disabled" state. See IsDisabled for more information.
Parameters
value
SetOpen()
void Juniper.Widgets.Openable.SetOpen (bool value) inline
If the control is not disabled, sets the open state.
Parameters
value If set to true value.
Definition at line 50 of file Openable.cs.
         {
             if (!IsDisabled && Open != value)
             {
                 Open = value;
                 if (stater == null)
                 {
                     payload.SetActive(Open);
                 }
                 else if (value)
                 {
                     payload.Activate();
                     stater.Enter();
                 }
                 else
                 {
                     stater.Exit();
                     payload.Deactivate();
                 }
                 ShowState(value ? "Opened" : "Closed");
             }
         }
References Juniper.Animation.AbstractTransitionController.Enter(), Juniper.Animation.AbstractTransitionController.Exit(), Juniper.Widgets.AbstractTouchable.IsDisabled, Juniper.Widgets.Openable.Open, Juniper.Widgets.Openable.payload, Juniper.Widgets.AbstractTouchable.ShowState(), and Juniper.Widgets.Openable.stater.
Referenced by Juniper.Widgets.Openable.Update().
ShowState()
string Juniper.Widgets.AbstractTouchable.ShowState (string enabledPart) inline protected inherited
Trigger the animation or swap the gameObjects to show the current control UI state.
Returns
The state.
Parameters
enabledPart Enabled part.
Definition at line 183 of file AbstractTouchable.cs.
         {
             enabledPart = NormalizePart(enabledPart);
             animator?.Play(enabledPart);
             return enabledPart;
         }
References Juniper.Widgets.AbstractTouchable.animator, Juniper.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Animation.AbstractAnimator.Play().
Referenced by Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Widgets.AbstractTouchable.Update().
ToggleEnabled()
void Juniper.Widgets.AbstractTouchable.ToggleEnabled () inherited
Toggles the boolean value of the disabled field.
ToggleOpen()
void Juniper.Widgets.Openable.ToggleOpen ()
If the control is closed, open it. If it's open, close it.
Referenced by Juniper.Widgets.Openable.OnPointerClick().
Update()
override void Juniper.Widgets.Openable.Update () inline protected virtual
Make sure the state hasn't changed outside of our control.
Reimplemented from Juniper.Widgets.AbstractTouchable.
Definition at line 105 of file Openable.cs.
         {
             base.Update();
             if (Open == wasOpen)
             {
                 Open = payload.IsActivated();
             }
             else
             {
                 // replay the change
                 Open = !Open;
                 wasOpen = !wasOpen;
                 SetOpen(wasOpen);
             }
         }
References Juniper.Widgets.Openable.Open, Juniper.Widgets.Openable.payload, Juniper.Widgets.Openable.SetOpen(), and Juniper.Widgets.Openable.wasOpen.
Member Data Documentation
clickButton
InputButton Juniper.Widgets.AbstractTouchable.clickButton inherited
The button we are expecting to use to interact with this object.
Definition at line 45 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.Clickable.OnLongPress(), Juniper.Widgets.Clickable.OnLongPressUpdate(), Juniper.Widgets.Clickable.OnPointerClick(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), and Juniper.Widgets.AbstractTouchable.OnPointerUp().
Closed
bool Juniper.Widgets.Openable.Closed
Initial value:
=>
            OpenChanged && !Open
Did the value of Open become false on this frame?
true if closed; otherwise, false.
Definition at line 43 of file Openable.cs.
disabled
bool Juniper.Widgets.AbstractTouchable.disabled inherited
Should the control run in a "disabled" state? It is still actively executing code, it's just preventing the main data-function of the control from occuring. There is still a need to show a different UI and react to user input to indicate the control is disabled.
Definition at line 58 of file AbstractTouchable.cs.
lastPointerPosition
Vector3 Juniper.Widgets.AbstractTouchable.lastPointerPosition protected inherited
The AbstractTouchable.pointerPosition from the previous frame, used for calculating how far the pointer has moved since the last frame.
Definition at line 126 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.LateUpdate(), and Juniper.Widgets.AbstractValued.OnDrag().
onClick
UnityEvent Juniper.Widgets.Clickable.onClick inherited
The event to call when the button is enabled and clicked. You should only use this version in the Unity Editor. If you are programmatically attaching event listeners, you should preferr Click.
Definition at line 24 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnClick().
onLongPress
UnityEvent Juniper.Widgets.Clickable.onLongPress inherited
Definition at line 26 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnLongPress().
Open
bool Juniper.Widgets.Openable.Open
Is the control in its open state?
Definition at line 24 of file Openable.cs.
Referenced by Juniper.Widgets.Openable.LateUpdate(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Widgets.Openable.Update().
OpenChanged
bool Juniper.Widgets.Openable.OpenChanged
Initial value:
=>
            Open != wasOpen
Did the Open state change since the last frame?
Definition at line 29 of file Openable.cs.
Opened
bool Juniper.Widgets.Openable.Opened
Initial value:
=>
            OpenChanged && Open
Did the control Open on this frame?
true if opened; otherwise, false.
Definition at line 36 of file Openable.cs.
PART_NAMES
string [] Juniper.Widgets.AbstractTouchable.PART_NAMES static inherited
Initial value:
=
        {
            "Normal",
            "Hovered",
            "Pressed",
            "Opened",
            "Disabled"
        }
The names of the animation states that Touchable expects.
Definition at line 33 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.NormalizePart(), and Juniper.Widgets.AbstractTouchable.Update().
payload
Transform Juniper.Widgets.Openable.payload
The scene sub-graph to show when this control is opened.
Definition at line 19 of file Openable.cs.
Referenced by Juniper.Widgets.Openable.Awake(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Widgets.Openable.Update().
pointerPosition
Vector3 Juniper.Widgets.AbstractTouchable.pointerPosition inherited
The place near the control that the pointer was pointing.
Definition at line 120 of file AbstractTouchable.cs.
Referenced by Juniper.Widgets.AbstractTouchable.GetPosition(), Juniper.Widgets.AbstractTouchable.LateUpdate(), Juniper.Widgets.AbstractValued.OnBeginDrag(), and Juniper.Widgets.AbstractValued.OnDrag().
PointerPositionChanged
bool Juniper.Widgets.AbstractTouchable.PointerPositionChanged protected inherited
Initial value:
=>
            pointerPosition != lastPointerPosition
Returns true when pointerPosition has changed since the last frame.
true if pointer position changed; otherwise, false.
Definition at line 132 of file AbstractTouchable.cs.
stater
AbstractTransitionController Juniper.Widgets.Openable.stater private
If the payload has a TransitionController on it, then Openable will use it as part of the open/close process.
Definition at line 135 of file Openable.cs.
Referenced by Juniper.Widgets.Openable.Awake(), and Juniper.Widgets.Openable.SetOpen().
wasOpen
bool Juniper.Widgets.Openable.wasOpen private
The Open state of the container from the last frame. On startup, there is no "last frame", so the value initializes to null for three-value logic.
Definition at line 141 of file Openable.cs.
Referenced by Juniper.Widgets.Openable.LateUpdate(), and Juniper.Widgets.Openable.Update().
Property Documentation
IsDisabled
bool Juniper.Widgets.AbstractTouchable.IsDisabled get set inherited
Returns true if the gameObject is not active, if the MonoBehaviour is not enabled, or if the Statable state has been set to Disabled.
Definition at line 91 of file AbstractTouchable.cs.
         {
             get
             {
                 return !isActiveAndEnabled || disabled;
             }
             set
             {
                 disabled = value;
             }
         }
Referenced by Juniper.Widgets.AbstractTouchable.LateUpdate(), Juniper.Widgets.Rotatable.OnBeginDrag(), Juniper.Widgets.AbstractValued.OnBeginDrag(), Juniper.Widgets.Rotatable.OnDrag(), Juniper.Widgets.Draggable.OnDrag(), Juniper.Widgets.AbstractValued.OnDrag(), Juniper.Widgets.AbstractValued.OnEndDrag(), Juniper.Widgets.Clickable.OnLongPress(), Juniper.Widgets.Clickable.OnLongPressUpdate(), Juniper.Widgets.Clickable.OnPointerClick(), Juniper.Widgets.AbstractTouchable.OnPointerDown(), Juniper.Widgets.AbstractTouchable.OnPointerEnter(), Juniper.Widgets.AbstractTouchable.OnPointerExit(), Juniper.Widgets.AbstractTouchable.OnPointerUp(), Juniper.Widgets.Openable.SetOpen(), and Juniper.Widgets.Rotatable.Update().
Event Documentation
Click
EventHandler Juniper.Widgets.Clickable.Click inherited
The event to call when the button is enabled and clicked. You should only use this verison if you are programmatically attaching event listenters. if you are using the Unity Editor, you should prefer onClick.
Definition at line 33 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnClick().
LongPress
EventHandler Juniper.Widgets.Clickable.LongPress inherited
Definition at line 35 of file Clickable.cs.
Referenced by Juniper.Widgets.Clickable.OnLongPress().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/Openable.cs