Juniper: Juniper.HTTP.WebSocketConnection< WebSocketT > Class Template Reference
Juniper.HTTP.WebSocketConnection< WebSocketT > Class Template Reference
Public Member Functions
Task SendAsync (string msg)
Task SendAsync< ValueT > (string message, ValueT value, ISerializer< ValueT > serializer)
Task SendAsync (byte[] buffer)
Task SendAsync (IReadOnlyCollection< byte > buffer)
async Task CloseAsync (WebSocketCloseStatus closeState=WebSocketCloseStatus.NormalClosure)
void Dispose ()
Public Attributes
const int DEFAULT_RX_BUFFER_SIZE = 1000
The default rx buffer size 1KiB
const int DEFAULT_DATA_BUFFER_SIZE = 10000000
The default data buffer size is 10MiB
WebSocketState State => Socket.State
Protected Member Functions
WebSocketConnection (int rxBufferSize=DEFAULT_RX_BUFFER_SIZE, int dataBufferSize=DEFAULT_DATA_BUFFER_SIZE)
virtual void Dispose (bool disposing)
Properties
WebSocketT? Socket [get, set]
Events
EventHandler< StringEventArgs > Message
EventHandler< BufferEventArgs > Data
EventHandler< DataMessageEventArgs > DataMessage
EventHandler< ErrorEventArgs > Error
EventHandler Connecting
EventHandler Connected
EventHandler Closing
EventHandler Closed
EventHandler Aborted
Private Member Functions
async Task UpdateAsync ()
async Task ReceiveAsync ()
void WebSocketConnection_Data (object sender, BufferEventArgs e)
async Task SendAsync (byte[] buffer, WebSocketMessageType messageType)
void OnDebug (string msg)
void OnMessage (string msg)
void OnData (byte[] data)
void OnDataMessage (DataMessageEventArgs dataMsg)
void OnError (string label, Exception exp)
void OnConnecting ()
void OnConnected ()
void OnClosing ()
void OnClosed ()
void OnAborted ()
Private Attributes
WebSocketT socket
readonly byte [] rxBuffer
readonly ArraySegment< byte > rxSegment
readonly int dataBufferSize
bool disposedValue = false
Detailed Description
Type Constraints
WebSocketT : WebSocket
Definition at line 15 of file WebSocketConnection.cs.
Constructor & Destructor Documentation
WebSocketConnection()
Juniper.HTTP.WebSocketConnection< WebSocketT >.WebSocketConnection (int rxBufferSize = DEFAULT_RX_BUFFER_SIZE, int dataBufferSize = DEFAULT_DATA_BUFFER_SIZE) inline protected
Definition at line 61 of file WebSocketConnection.cs.
         {
             this.dataBufferSize = dataBufferSize;
             rxBuffer = new byte[rxBufferSize];
             rxSegment = new ArraySegment<byte>(rxBuffer);
             Data += WebSocketConnection_Data;
             _ = Task.Run(UpdateAsync).ConfigureAwait(false);
         }
Member Function Documentation
CloseAsync()
async Task Juniper.HTTP.WebSocketConnection< WebSocketT >.CloseAsync (WebSocketCloseStatus closeState = WebSocketCloseStatus.NormalClosure) inline
Definition at line 243 of file WebSocketConnection.cs.
         {
             OnDebug("Closing");
             OnClosing();
             var closeMessage = closeState == WebSocketCloseStatus.NormalClosure
                 ? null
                 : closeState.ToString();
             await Socket
                 .CloseAsync(closeState, closeMessage, CancellationToken.None)
                 .ConfigureAwait(false);
             while (State == WebSocketState.Open
                 || State == WebSocketState.CloseSent)
             {
                 await Task.Yield();
             }
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
Dispose() [1/2]
virtual void Juniper.HTTP.WebSocketConnection< WebSocketT >.Dispose (bool disposing) inline protected virtual
Reimplemented in Juniper.HTTP.Server.ServerWebSocketConnection.
Definition at line 266 of file WebSocketConnection.cs.
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     Socket.Dispose();
                 }
                 disposedValue = true;
             }
         }
Dispose() [2/2]
void Juniper.HTTP.WebSocketConnection< WebSocketT >.Dispose () inline
Definition at line 280 of file WebSocketConnection.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
             GC.SuppressFinalize(this);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.Dispose().
OnAborted()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnAborted () inline private
Definition at line 347 of file WebSocketConnection.cs.
         {
             Aborted?.Invoke(this, EventArgs.Empty);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
OnClosed()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnClosed () inline private
Definition at line 341 of file WebSocketConnection.cs.
         {
             Closed?.Invoke(this, EventArgs.Empty);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
OnClosing()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnClosing () inline private
Definition at line 335 of file WebSocketConnection.cs.
         {
             Closing?.Invoke(this, EventArgs.Empty);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.CloseAsync().
OnConnected()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnConnected () inline private
Definition at line 329 of file WebSocketConnection.cs.
         {
             Connected?.Invoke(this, EventArgs.Empty);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
OnConnecting()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnConnecting () inline private
Definition at line 323 of file WebSocketConnection.cs.
         {
             Connecting?.Invoke(this, EventArgs.Empty);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
OnData()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnData (byte [] data) inline private
Definition at line 305 of file WebSocketConnection.cs.
         {
             Data?.Invoke(this, new BufferEventArgs(data));
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync().
OnDataMessage()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnDataMessage (DataMessageEventArgs dataMsg) inline private
Definition at line 311 of file WebSocketConnection.cs.
         {
             DataMessage?.Invoke(this, dataMsg);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.WebSocketConnection_Data().
OnDebug()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnDebug (string msg) inline private
Definition at line 291 of file WebSocketConnection.cs.
         {
 #if DEBUG
             Debug?.Invoke(this, new StringEventArgs(msg));
 #endif
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.CloseAsync(), Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync(), Juniper.HTTP.WebSocketConnection< WebSocket >.SendAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.SendAsync< ValueT >().
OnError()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnError (string label, Exception exp) inline private
Definition at line 317 of file WebSocketConnection.cs.
         {
             Error?.Invoke(this, new ErrorEventArgs(new Exception(label, exp)));
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
OnMessage()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.OnMessage (string msg) inline private
Definition at line 299 of file WebSocketConnection.cs.
         {
             Message?.Invoke(this, new StringEventArgs(msg));
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync().
ReceiveAsync()
async Task Juniper.HTTP.WebSocketConnection< WebSocketT >.ReceiveAsync () inline private
Definition at line 131 of file WebSocketConnection.cs.
         {
             var accum = new List<byte>();
             bool done;
             WebSocketMessageType msgType;
             do
             {
                 var result = await Socket
                     .ReceiveAsync(rxSegment, CancellationToken.None)
                     .ConfigureAwait(false);
                 msgType = result.MessageType;
                 accum.AddRange(rxBuffer.Take(result.Count));
                 done = result.EndOfMessage;
                 if (accum.Count > dataBufferSize)
                 {
                     done = true;
                     await CloseAsync(WebSocketCloseStatus.MessageTooBig)
                         .ConfigureAwait(false);
                 }
             } while (!done);
             var data = accum.ToArray();
             if (msgType == WebSocketMessageType.Text)
             {
                 OnMessage(Encoding.UTF8.GetString(data));
             }
             else if (msgType == WebSocketMessageType.Binary)
             {
                 OnData(data);
             }
             else if (msgType == WebSocketMessageType.Close)
             {
                 OnDebug(msgType.ToString());
                 await CloseAsync()
                     .ConfigureAwait(false);
             }
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
SendAsync() [1/4]
Task Juniper.HTTP.WebSocketConnection< WebSocketT >.SendAsync (string msg) inline
Definition at line 184 of file WebSocketConnection.cs.
         {
             if (msg is null)
             {
                 throw new ArgumentNullException(nameof(msg));
             }
             OnDebug($"Send: {msg}");
             return SendAsync(Encoding.UTF8.GetBytes(msg), WebSocketMessageType.Text);
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.SendAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.SendAsync< ValueT >().
SendAsync() [2/4]
Task Juniper.HTTP.WebSocketConnection< WebSocketT >.SendAsync (byte [] buffer) inline
Definition at line 209 of file WebSocketConnection.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             return SendAsync(buffer, WebSocketMessageType.Binary);
         }
SendAsync() [3/4]
Task Juniper.HTTP.WebSocketConnection< WebSocketT >.SendAsync (IReadOnlyCollection< byte > buffer) inline
Definition at line 219 of file WebSocketConnection.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             return SendAsync(buffer.ToArray(), WebSocketMessageType.Binary);
         }
SendAsync() [4/4]
async Task Juniper.HTTP.WebSocketConnection< WebSocketT >.SendAsync (byte [] buffer, WebSocketMessageType messageType) inline private
Definition at line 229 of file WebSocketConnection.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             var segment = new ArraySegment<byte>(buffer.ToArray());
             OnDebug($"Send: {buffer.Length.ToString(CultureInfo.CurrentCulture)} bytes. Type: {messageType.ToString()}.");
             await Socket
                 .SendAsync(segment, messageType, true, CancellationToken.None)
                 .ConfigureAwait(false);
         }
SendAsync< ValueT >()
Task Juniper.HTTP.WebSocketConnection< WebSocketT >.SendAsync< ValueT > (string message, ValueT value, ISerializer< ValueT > serializer) inline
Definition at line 195 of file WebSocketConnection.cs.
         {
             if (serializer is null)
             {
                 throw new ArgumentNullException(nameof(serializer));
             }
             OnDebug($"Send: {value} => {message}");
             var data = serializer.Serialize(value);
             var dataMessage = new DataMessage(message, data);
             var msgSerializer = new BinaryFactory<DataMessage>();
             return SendAsync(msgSerializer.Serialize(dataMessage));
         }
UpdateAsync()
async Task Juniper.HTTP.WebSocketConnection< WebSocketT >.UpdateAsync () inline private
Definition at line 75 of file WebSocketConnection.cs.
         {
             try
             {
                 while (Socket is null)
                 {
                     await Task.Yield();
                 }
                 while (State == WebSocketState.None)
                 {
                     await Task.Yield();
                 }
                 if (State == WebSocketState.Connecting)
                 {
                     OnConnecting();
                 }
                 while (State == WebSocketState.Connecting)
                 {
                     await Task.Yield();
                 }
                 if (State == WebSocketState.Open)
                 {
                     OnConnected();
                 }
                 while (State == WebSocketState.Open
                     || State == WebSocketState.CloseSent)
                 {
                     await ReceiveAsync()
                         .ConfigureAwait(false);
                 }
             }
             catch (Exception exp)
             {
                 OnError("Update", exp);
             }
             finally
             {
                 if (State == WebSocketState.Aborted)
                 {
                     OnAborted();
                 }
                 else if (State == WebSocketState.CloseReceived)
                 {
                     await CloseAsync()
                         .ConfigureAwait(false);
                 }
                 OnClosed();
             }
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.WebSocketConnection().
WebSocketConnection_Data()
void Juniper.HTTP.WebSocketConnection< WebSocketT >.WebSocketConnection_Data (object sender, BufferEventArgs e) inline private
Definition at line 172 of file WebSocketConnection.cs.
         {
             if (DataMessage is object)
             {
                 var dataMessageDeserializer = new BinaryFactory<DataMessageEventArgs>();
                 if (dataMessageDeserializer.TryDeserialize(e.Value.ToArray(), out var dataMsg))
                 {
                     OnDataMessage(dataMsg);
                 }
             }
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.WebSocketConnection().
Member Data Documentation
dataBufferSize
readonly int Juniper.HTTP.WebSocketConnection< WebSocketT >.dataBufferSize private
Definition at line 59 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.WebSocketConnection().
DEFAULT_DATA_BUFFER_SIZE
const int Juniper.HTTP.WebSocketConnection< WebSocketT >.DEFAULT_DATA_BUFFER_SIZE = 10000000
The default data buffer size is 10MiB
Definition at line 27 of file WebSocketConnection.cs.
DEFAULT_RX_BUFFER_SIZE
const int Juniper.HTTP.WebSocketConnection< WebSocketT >.DEFAULT_RX_BUFFER_SIZE = 1000
The default rx buffer size 1KiB
Definition at line 22 of file WebSocketConnection.cs.
disposedValue
bool Juniper.HTTP.WebSocketConnection< WebSocketT >.disposedValue = false private
Definition at line 264 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.Dispose().
rxBuffer
readonly byte [] Juniper.HTTP.WebSocketConnection< WebSocketT >.rxBuffer private
Definition at line 57 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.WebSocketConnection().
rxSegment
readonly ArraySegment<byte> Juniper.HTTP.WebSocketConnection< WebSocketT >.rxSegment private
Definition at line 58 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.WebSocketConnection().
socket
WebSocketT Juniper.HTTP.WebSocketConnection< WebSocketT >.socket private
Definition at line 29 of file WebSocketConnection.cs.
State
WebSocketState Juniper.HTTP.WebSocketConnection< WebSocketT >.State => Socket.State
Definition at line 73 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.CloseAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
Property Documentation
Socket
WebSocketT? Juniper.HTTP.WebSocketConnection< WebSocketT >.Socket get set protected
Definition at line 31 of file WebSocketConnection.cs.
         {
             get
             {
                 return socket;
             }
             set
             {
                 socket?.Dispose();
                 socket = value;
             }
         }
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.CloseAsync(), Juniper.HTTP.WebSocketConnection< WebSocket >.Dispose(), Juniper.HTTP.WebSocketConnection< WebSocket >.ReceiveAsync(), Juniper.HTTP.WebSocketConnection< WebSocket >.SendAsync(), and Juniper.HTTP.WebSocketConnection< WebSocket >.UpdateAsync().
Event Documentation
Aborted
EventHandler Juniper.HTTP.WebSocketConnection< WebSocketT >.Aborted
Definition at line 51 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.OnAborted().
Closed
EventHandler Juniper.HTTP.WebSocketConnection< WebSocketT >.Closed
Definition at line 50 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler(), Juniper.HTTP.Server.Controllers.WebSocketPool.GetAsync(), Juniper.HTTP.WebSocketConnection< WebSocket >.OnClosed(), and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_Closed().
Closing
EventHandler Juniper.HTTP.WebSocketConnection< WebSocketT >.Closing
Definition at line 49 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.OnClosing().
Connected
EventHandler Juniper.HTTP.WebSocketConnection< WebSocketT >.Connected
Definition at line 48 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.OnConnected().
Connecting
EventHandler Juniper.HTTP.WebSocketConnection< WebSocketT >.Connecting
Definition at line 47 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.OnConnecting().
Data
EventHandler<BufferEventArgs> Juniper.HTTP.WebSocketConnection< WebSocketT >.Data
Definition at line 44 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.OnData(), and Juniper.HTTP.WebSocketConnection< WebSocket >.WebSocketConnection().
DataMessage
EventHandler<DataMessageEventArgs> Juniper.HTTP.WebSocketConnection< WebSocketT >.DataMessage
Definition at line 45 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler(), Juniper.HTTP.WebSocketConnection< WebSocket >.SendAsync< ValueT >(), and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_Closed().
Error
EventHandler<ErrorEventArgs> Juniper.HTTP.WebSocketConnection< WebSocketT >.Error
Definition at line 46 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.OnError().
Message
EventHandler<StringEventArgs> Juniper.HTTP.WebSocketConnection< WebSocketT >.Message
Definition at line 43 of file WebSocketConnection.cs.
Referenced by Juniper.HTTP.WebSocketConnection< WebSocket >.OnMessage().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/HTTP/WebSocketConnection.cs