Juniper: Juniper.Unity.Input.UnifiedInputModule Class Reference
Juniper.Unity.Input.UnifiedInputModule Class Reference
Finds all of the IPointerDevice s and fires raycaster events for all of them.
Classes
class PointerFoundEvent
Public Member Functions
void AddPointer (IPointerDevice pointer)
void WithPointer (Action< IPointerDevice > onPointerAvailable)
virtual void Reinstall ()
override void Process ()
Find all the pointers and fire raycaster events for them.
PointerEventData Clone (PointerEventData original, int offset)
void Install (bool reset)
void Uninstall ()
override void UpdateModule ()
Manages the input controllers, either motion controllers on WindowsMR headsets, or hand tracking on HoloLens.
Public Attributes
readonly List< IPointerDevice > Devices = new List<IPointerDevice>()
GameObject pointerPrefab
Set to the clonable object that should be used for the pointer probe.
PointerFoundEvent onPointerFound
Protected Member Functions
override void Awake ()
override void Reset ()
Protected Attributes
StageExtensions stage
Events
EventHandler< PointerFoundEventArgs > PointerFound
Private Member Functions
void OnPointerFound (IPointerDevice pointer)
RaycastResult UpdateRay (IPointerDevice pointer, Vector3 lastPointerPosition, PointerEventData evtData)
void RaycastAll (IPointerDevice pointer, PointerEventData eventData)
Fire a raycast using all of the GraphicRaycasters in the system, plus the one PhysicsRaycaster that is associated with the event Camera.
Static Private Member Functions
static int RaycastComparer (RaycastResult lhs, RaycastResult rhs)
A method for sorting raycasts.
Private Attributes
readonly List< IPointerDevice > newDevices = new List<IPointerDevice>()
Detailed Description
Finds all of the IPointerDevice s and fires raycaster events for all of them.
Definition at line 19 of file UnifiedInputModule.cs.
Member Function Documentation
AddPointer()
void Juniper.Unity.Input.UnifiedInputModule.AddPointer (IPointerDevice pointer) inline
Definition at line 33 of file UnifiedInputModule.cs.
         {
             if (!Devices.Contains(pointer) && !newDevices.Contains(pointer))
             {
                 pointer.PointerID = Devices.Count * 10000;
                 pointer.InputModule = this;
                 newDevices.Add(pointer);
             }
         }
References Juniper.Unity.Input.UnifiedInputModule.Devices, Juniper.Unity.Input.Pointers.IPointerDevice.InputModule, Juniper.Unity.Input.UnifiedInputModule.newDevices, and Juniper.Unity.Input.Pointers.IPointerDevice.PointerID.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
Awake()
override void Juniper.Unity.Input.UnifiedInputModule.Awake () inline protected
Definition at line 73 of file UnifiedInputModule.cs.
         {
             base.Awake();
             Install(false);
             stage = ComponentExt.FindAny<StageExtensions>();
 #if GOOGLEVR
             var gci = GetComponent<GvrControllerInput>();
             var gee = GetComponent<GvrEditorEmulator>();
             gci.enabled = gee.enabled = AnyActiveGoogleInstantPreview;
 #endif
         }
References Juniper.Unity.Input.UnifiedInputModule.Install(), and Juniper.Unity.Input.UnifiedInputModule.stage.
Clone()
PointerEventData Juniper.Unity.Input.UnifiedInputModule.Clone (PointerEventData original, int offset) inline
Definition at line 193 of file UnifiedInputModule.cs.
         {
             PointerEventData clone;
             GetPointerData(original.pointerId + offset, out clone, true);
             clone.delta = original.delta;
             clone.position = original.position;
             clone.scrollDelta = original.scrollDelta;
             clone.pointerEnter = original.pointerEnter;
             clone.useDragThreshold = original.useDragThreshold;
             clone.pointerCurrentRaycast = original.pointerCurrentRaycast;
             if (original.clickCount == -1)
             {
                 clone.eligibleForClick = false;
                 clone.clickCount = 0;
             }
             return clone;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Clone(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone().
Install()
void Juniper.Unity.Input.UnifiedInputModule.Install (bool reset) inline
Implements Juniper.IInstallable.
Definition at line 297 of file UnifiedInputModule.cs.
         {
             reset &= Application.isEditor;
 #if UNITY_EDITOR
             if (pointerPrefab == null)
             {
                 pointerPrefab = UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(System.IO.PathExt.FixPath("Assets/Juniper/Prefabs/DiskProbe.prefab"));
             }
 #endif
 #if OCULUS
             this.EnsureComponent<OVRManager>();
 #elif GOOGLEVR
             this.EnsureComponent<GvrControllerInput>();
             this.EnsureComponent<GvrEditorEmulator>();
 #if UNITY_EDITOR
             var ip = UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(
                 System.IO.PathExt.FixPath("Assets/GoogleVR/Prefabs/InstantPreview/GvrInstantPreviewMain.prefab"));
             UnityEditor.PrefabUtility.InstantiatePrefab(ip);
 #endif
 #endif
         }
References System.IO.PathExt.FixPath(), and Juniper.Unity.Input.UnifiedInputModule.pointerPrefab.
Referenced by Juniper.Unity.Input.UnifiedInputModule.Awake(), and Juniper.Unity.Input.UnifiedInputModule.Reinstall().
OnPointerFound()
void Juniper.Unity.Input.UnifiedInputModule.OnPointerFound (IPointerDevice pointer) inline private
Definition at line 157 of file UnifiedInputModule.cs.
         {
             PointerFound?.Invoke(this, new PointerFoundEventArgs(pointer));
             onPointerFound?.Invoke(pointer);
         }
References Juniper.Unity.Input.UnifiedInputModule.onPointerFound, and Juniper.Unity.Input.UnifiedInputModule.PointerFound.
Referenced by Juniper.Unity.Input.UnifiedInputModule.Process().
Process()
override void Juniper.Unity.Input.UnifiedInputModule.Process () inline
Find all the pointers and fire raycaster events for them.
Definition at line 166 of file UnifiedInputModule.cs.
         {
             foreach (var pointer in newDevices)
             {
                 Devices.Add(pointer);
                 OnPointerFound(pointer);
             }
             newDevices.Clear();
             foreach (var pointer in Devices)
             {
                 if (pointer.IsEnabled)
                 {
                     PointerEventData evtData;
                     GetPointerData(pointer.PointerID, out evtData, true);
                     evtData.delta = pointer.ScreenDelta;
                     evtData.position = pointer.ScreenPoint;
                     evtData.scrollDelta = pointer.ScrollDelta;
                     evtData.useDragThreshold = eventSystem.pixelDragThreshold > 0;
                     evtData.pointerCurrentRaycast = UpdateRay(pointer, pointer.transform.position, evtData);
                     pointer.Process(evtData, eventSystem.pixelDragThreshold * eventSystem.pixelDragThreshold);
                 }
             }
         }
References Juniper.Unity.Input.UnifiedInputModule.Devices, Juniper.Unity.Input.UnifiedInputModule.newDevices, Juniper.Unity.Input.UnifiedInputModule.OnPointerFound(), and Juniper.Unity.Input.UnifiedInputModule.UpdateRay().
RaycastAll()
void Juniper.Unity.Input.UnifiedInputModule.RaycastAll (IPointerDevice pointer, PointerEventData eventData) inline private
Fire a raycast using all of the GraphicRaycasters in the system, plus the one PhysicsRaycaster that is associated with the event Camera.
Parameters
pointer Pointer.
eventData Event data.
Definition at line 259 of file UnifiedInputModule.cs.
         {
             m_RaycastResultCache.Clear();
 #if UNITY_MODULES_PHYSICS
             pointer.Raycaster?.Raycast(eventData, m_RaycastResultCache);
 #endif
 #if UNITY_MODULES_UI
             foreach (var raycaster in raycasters)
             {
                 if (raycaster.isActiveAndEnabled)
                 {
                     var canv = raycaster.GetComponent<Canvas>();
                     if (pointer.EventCamera.IsInView(canv))
                     {
                         canv.worldCamera = pointer.EventCamera;
                         var start = m_RaycastResultCache.Count;
                         raycaster.Raycast(eventData, m_RaycastResultCache);
                         for (var i = start; i < m_RaycastResultCache.Count; ++i)
{
                             var ray = m_RaycastResultCache[i];
                             ray.worldNormal = canv.transform.forward;
                             var pos = (Vector3)ray.screenPosition;
                             pos.z = ray.distance + 0.35f;
                             ray.worldPosition = pointer.EventCamera.ScreenToWorldPoint(pos);
                             m_RaycastResultCache[i] = ray;
                         }
                     }
                 }
             }
 #endif
             m_RaycastResultCache.Sort(RaycastComparer);
         }
References Juniper.Unity.Input.UnifiedInputModule.RaycastComparer(), and Juniper.Unity.Input.Pointers.IPointerDevice.Raycaster.
Referenced by Juniper.Unity.Input.UnifiedInputModule.UpdateRay().
RaycastComparer()
static int Juniper.Unity.Input.UnifiedInputModule.RaycastComparer (RaycastResult lhs, RaycastResult rhs) inline static private
A method for sorting raycasts.
Returns
The comparer.
Parameters
lhs Lhs.
rhs Rhs.
Definition at line 128 of file UnifiedInputModule.cs.
         {
             if (lhs.module.eventCamera != null
                 && rhs.module.eventCamera != null)
             {
                 return lhs.distance.CompareTo(rhs.distance);
             }
             else if (lhs.module.sortOrderPriority != rhs.module.sortOrderPriority)
             {
                 return lhs.module.sortOrderPriority.CompareTo(rhs.module.sortOrderPriority);
             }
             else if (lhs.module.renderOrderPriority != rhs.module.renderOrderPriority)
             {
                 return lhs.module.renderOrderPriority.CompareTo(rhs.module.renderOrderPriority);
             }
             else if (lhs.depth != rhs.depth)
             {
                 return rhs.depth.CompareTo(lhs.depth);
             }
             else if (Mathf.Abs(lhs.distance - rhs.distance) > 0.00001f)
             {
                 return lhs.distance.CompareTo(rhs.distance);
             }
             else
             {
                 return lhs.index.CompareTo(rhs.index);
             }
         }
Referenced by Juniper.Unity.Input.UnifiedInputModule.RaycastAll().
Reinstall()
virtual void Juniper.Unity.Input.UnifiedInputModule.Reinstall () inline virtual
Implements Juniper.IInstallable.
Definition at line 88 of file UnifiedInputModule.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.UnifiedInputModule.Install().
Referenced by Juniper.Unity.Input.UnifiedInputModule.Reset().
Reset()
override void Juniper.Unity.Input.UnifiedInputModule.Reset () inline protected
Definition at line 95 of file UnifiedInputModule.cs.
         {
             base.Reset();
             Reinstall();
         }
References Juniper.Unity.Input.UnifiedInputModule.Reinstall().
Uninstall()
void Juniper.Unity.Input.UnifiedInputModule.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 323 of file UnifiedInputModule.cs.
         {
 #if OCULUS
             this.RemoveComponent<OVRManager>();
 #elif GOOGLEVR
             this.RemoveComponent<GvrEditorEmulator>();
             this.RemoveComponent<GvrControllerInput>();
             var ip = ComponentExt.FindAny<InstantPreviewHelper>();
             if (ip != null)
             {
                 ip.gameObject.Destroy();
             }
 #endif
         }
References UnityEngine.ComponentExt.Destroy().
UpdateModule()
override void Juniper.Unity.Input.UnifiedInputModule.UpdateModule () inline
Manages the input controllers, either motion controllers on WindowsMR headsets, or hand tracking on HoloLens.
Definition at line 344 of file UnifiedInputModule.cs.
         {
             base.UpdateModule();
             Pointers.Motion.MotionController.UpdateReadings();
         }
UpdateRay()
RaycastResult Juniper.Unity.Input.UnifiedInputModule.UpdateRay (IPointerDevice pointer, Vector3 lastPointerPosition, PointerEventData evtData) inline private
Definition at line 213 of file UnifiedInputModule.cs.
         {
             var ray = evtData.pointerCurrentRaycast;
             if (pointer.LockedOnTarget)
             {
                 var from = ray.worldPosition - lastPointerPosition;
                 var to = ray.distance * (pointer.InteractionEndPoint - pointer.transform.position);
                 var delta = to - from;
                 var rot = Quaternion.FromToRotation(from.normalized, to.normalized);
                 ray.gameObject = evtData.pointerPress;
                 ray.worldPosition = (rot * ray.worldPosition) + delta;
                 ray.worldNormal = rot * ray.worldNormal;
                 ray.screenPosition = evtData.position;
             }
             else
             {
                 RaycastAll(pointer, evtData);
                 if (m_RaycastResultCache.Count > 0)
                 {
                     ray = m_RaycastResultCache[0];
                     evtData.hovered.Clear();
                     foreach (var r in m_RaycastResultCache)
                     {
                         evtData.hovered.Add(r.gameObject);
                     }
                 }
                 else
                 {
                     ray.Clear();
                     ray.worldPosition = pointer.InteractionEndPoint;
                     ray.distance = pointer.MinimumPointerDistance;
                     ray.worldNormal = -pointer.InteractionDirection;
                     ray.screenPosition = evtData.position;
                 }
             }
             return ray;
         }
References Juniper.Unity.Input.Pointers.IPointerDevice.InteractionDirection, Juniper.Unity.Input.Pointers.IPointerDevice.InteractionEndPoint, Juniper.Unity.Input.Pointers.IPointerDevice.LockedOnTarget, Juniper.Unity.Input.Pointers.IPointerDevice.MinimumPointerDistance, Juniper.Unity.Input.UnifiedInputModule.RaycastAll(), and Juniper.Unity.Input.Pointers.IPointerDevice.transform.
Referenced by Juniper.Unity.Input.UnifiedInputModule.Process().
WithPointer()
void Juniper.Unity.Input.UnifiedInputModule.WithPointer (Action< IPointerDevice > onPointerAvailable) inline
Definition at line 43 of file UnifiedInputModule.cs.
         {
             if (Devices.Count > 0)
             {
                 onPointerAvailable(Devices[0]);
             }
             else
             {
                 EventHandler<PointerFoundEventArgs> subAct = null;
                 subAct = new EventHandler<PointerFoundEventArgs>((sender, args) =>
                 {
                     PointerFound -= subAct;
                     onPointerAvailable(args.device);
                 });
                 PointerFound += subAct;
             }
         }
References Juniper.Unity.Input.UnifiedInputModule.Devices, and Juniper.Unity.Input.UnifiedInputModule.PointerFound.
Referenced by Juniper.Unity.Input.HoverCraft.Awake().
Member Data Documentation
Devices
readonly List<IPointerDevice> Juniper.Unity.Input.UnifiedInputModule.Devices = new List<IPointerDevice>()
Definition at line 22 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.UnifiedInputModule.AddPointer(), Juniper.Unity.Input.UnifiedInputModule.Process(), and Juniper.Unity.Input.UnifiedInputModule.WithPointer().
newDevices
readonly List<IPointerDevice> Juniper.Unity.Input.UnifiedInputModule.newDevices = new List<IPointerDevice>() private
Definition at line 21 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.UnifiedInputModule.AddPointer(), and Juniper.Unity.Input.UnifiedInputModule.Process().
onPointerFound
PointerFoundEvent Juniper.Unity.Input.UnifiedInputModule.onPointerFound
Definition at line 29 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.UnifiedInputModule.OnPointerFound().
pointerPrefab
GameObject Juniper.Unity.Input.UnifiedInputModule.pointerPrefab
Set to the clonable object that should be used for the pointer probe.
Definition at line 27 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.UnifiedInputModule.Install().
stage
StageExtensions Juniper.Unity.Input.UnifiedInputModule.stage protected
Definition at line 65 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.UnifiedInputModule.Awake().
Event Documentation
PointerFound
EventHandler<PointerFoundEventArgs> Juniper.Unity.Input.UnifiedInputModule.PointerFound
Definition at line 31 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.UnifiedInputModule.OnPointerFound(), and Juniper.Unity.Input.UnifiedInputModule.WithPointer().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/UnifiedInputModule.cs