Juniper: Juniper.Terminal.ConsoleBuffer Class Reference
Juniper.Terminal.ConsoleBuffer Class Reference
Classes
class NativeMethods
Public Member Functions
ConsoleBuffer (int gridSize)
ConsoleBuffer (int gridSize, int width, int height)
bool IsInBounds (int x, int y)
Determine if a point is within the bounds of the board
ConsoleColor GetBackgroundColor (int x, int y)
void Draw (int x, int y, char c, ConsoleColor f, ConsoleColor b)
void Flush ()
void Prompt (string message, bool pause)
void SetFontSize (int width, int height)
Public Attributes
int AbsoluteLeft => 0
int AbsoluteRight => Width - 1
int AbsoluteTop => 0
int AbsoluteBottom => Height - 1
int Width => tiles1?.GetWidth() ?? -1
int Height => tiles1?.GetHeight() ?? -1
Static Public Attributes
static readonly bool IsWindows
static int x
Events
EventHandler< SizeChangedEventArgs > SizeChanged
Private Member Functions
internal ConsoleBuffer (int gridSize, NativeMethods.COORD size)
void ConsoleBuffer_CancelKeyPress (object sender, ConsoleCancelEventArgs e)
~ConsoleBuffer ()
void Teardown ()
void CheckGrids ()
Static Private Member Functions
static void CheckCursor (int x, int y)
static int int y GetCursorPosition ()
Private Attributes
readonly IntPtr outputHandle
readonly ConsoleColor startFore
readonly ConsoleColor startBack
ConsoleColor lastBack
ConsoleColor lastFore
Tile [,] tiles1
Tile [,] tiles2
Detailed Description
Definition at line 12 of file ConsoleBuffer.cs.
Constructor & Destructor Documentation
ConsoleBuffer() [1/3]
Juniper.Terminal.ConsoleBuffer.ConsoleBuffer (int gridSize) inline
Definition at line 42 of file ConsoleBuffer.cs.
             : this(gridSize, WindowWidth, WindowHeight - 1)
         { }
ConsoleBuffer() [2/3]
internal Juniper.Terminal.ConsoleBuffer.ConsoleBuffer (int gridSize, NativeMethods.COORD size) inline private
Definition at line 46 of file ConsoleBuffer.cs.
             : this(gridSize, size.X, size.Y)
         { }
ConsoleBuffer() [3/3]
Juniper.Terminal.ConsoleBuffer.ConsoleBuffer (int gridSize, int width, int height) inline
Definition at line 50 of file ConsoleBuffer.cs.
         {
             if (IsWindows)
             {
                 outputHandle = IsWindows
                    ? NativeMethods.GetStdHandle(NativeMethods.STD_OUTPUT_HANDLE)
                    : NativeMethods.INVALID_HANDLE_VALUE;
                 SetFontSize(gridSize, gridSize);
             }
             width = Math.Min(width, LargestWindowWidth);
             height = Math.Min(height, LargestWindowHeight - 1);
             OutputEncoding = Encoding.Unicode;
             lastFore = startFore = ForegroundColor;
             lastBack = startBack = BackgroundColor;
             SetWindowSize(width, height + 1);
             SetBufferSize(width, height + 1);
             CheckGrids();
         }
References Juniper.Terminal.ConsoleBuffer.CheckGrids(), Juniper.Terminal.ConsoleBuffer.NativeMethods.GetStdHandle(), Juniper.Terminal.ConsoleBuffer.NativeMethods.INVALID_HANDLE_VALUE, Juniper.Terminal.ConsoleBuffer.IsWindows, Juniper.Terminal.ConsoleBuffer.lastBack, Juniper.Terminal.ConsoleBuffer.lastFore, Juniper.Terminal.ConsoleBuffer.outputHandle, Juniper.Terminal.ConsoleBuffer.SetFontSize(), Juniper.Terminal.ConsoleBuffer.startBack, Juniper.Terminal.ConsoleBuffer.startFore, and Juniper.Terminal.ConsoleBuffer.NativeMethods.STD_OUTPUT_HANDLE.
~ConsoleBuffer()
Juniper.Terminal.ConsoleBuffer.~ConsoleBuffer () inline private
Definition at line 80 of file ConsoleBuffer.cs.
         {
             Teardown();
         }
References Juniper.Terminal.ConsoleBuffer.Teardown().
Member Function Documentation
CheckCursor()
static void Juniper.Terminal.ConsoleBuffer.CheckCursor (int x, int y) inline static private
Definition at line 186 of file ConsoleBuffer.cs.
         {
             var rowChanged = y != CursorTop;
             var colChanged = x != CursorLeft;
             if (rowChanged && colChanged)
             {
                 SetCursorPosition(x, y);
             }
             else if (colChanged)
             {
                 CursorLeft = x;
             }
             else if (rowChanged)
             {
                 CursorTop = y;
             }
         }
References Juniper.Terminal.ConsoleBuffer.x.
Referenced by Juniper.Terminal.ConsoleBuffer.Flush().
CheckGrids()
void Juniper.Terminal.ConsoleBuffer.CheckGrids () inline private
Definition at line 115 of file ConsoleBuffer.cs.
         {
             var oldWidth = Width;
             var oldHeight = Height;
             var newWidth = WindowWidth;
             var newHeight = WindowHeight - 1;
             if (newWidth != oldWidth
                 || newHeight != oldHeight)
             {
                 var lastTiles1 = tiles1;
                 var lastTiles2 = tiles2;
                 tiles1 = new Tile[newWidth, newHeight];
                 tiles2 = new Tile[newWidth, newHeight];
                 Clear();
                 CursorVisible = false;
                 SizeChanged?.Invoke(this, new SizeChangedEventArgs(oldWidth, oldHeight, newWidth, newHeight));
             }
         }
References Juniper.Terminal.ConsoleBuffer.Height, Juniper.Terminal.ConsoleBuffer.SizeChanged, Juniper.Terminal.ConsoleBuffer.tiles1, Juniper.Terminal.ConsoleBuffer.tiles2, and Juniper.Terminal.ConsoleBuffer.Width.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer(), and Juniper.Terminal.ConsoleBuffer.Flush().
ConsoleBuffer_CancelKeyPress()
void Juniper.Terminal.ConsoleBuffer.ConsoleBuffer_CancelKeyPress (object sender, ConsoleCancelEventArgs e) inline private
Definition at line 74 of file ConsoleBuffer.cs.
         {
             Teardown();
             e.Cancel = true;
         }
References Juniper.Terminal.ConsoleBuffer.Teardown().
Draw()
void Juniper.Terminal.ConsoleBuffer.Draw (int x, int y, char c, ConsoleColor f, ConsoleColor b) inline
Implements Juniper.Terminal.IConsoleBuffer.
Definition at line 137 of file ConsoleBuffer.cs.
         {
             if (IsInBounds(x, y))
             {
                 tiles1[x, y].Back = b;
                 tiles1[x, y].Fore = f;
                 tiles1[x, y].Token = c;
             }
         }
References Juniper.Puzzles.Tile.Back, Juniper.Puzzles.Tile.Fore, Juniper.Terminal.ConsoleBuffer.IsInBounds(), Juniper.Terminal.ConsoleBuffer.tiles1, Juniper.Puzzles.Tile.Token, and Juniper.Terminal.ConsoleBuffer.x.
Referenced by Juniper.Terminal.ConsoleBuffer.Prompt().
Flush()
void Juniper.Terminal.ConsoleBuffer.Flush () inline
Definition at line 147 of file ConsoleBuffer.cs.
         {
             for (var y = 0; y < Height; ++y)
             {
                 for (var x = 0; x < Width; ++x)
                 {
                     var t1 = tiles1[x, y];
                     if (!t1.Equals(tiles2[x, y]))
                     {
                         CheckCursor(x, y);
                         if (t1.Fore != lastFore)
{
                             lastFore = ForegroundColor = t1.Fore;
                         }
                         if (t1.Back != lastBack)
{
                             lastBack = BackgroundColor = t1.Back;
                         }
                         if (x < Width - 1)
{
                             Write(t1.Token);
                         }
                         else
{
                             WriteLine(t1.Token);
                         }
                     }
                     tiles2[x, y] = t1;
                 }
             }
             CheckGrids();
         }
References Juniper.Terminal.ConsoleBuffer.CheckCursor(), Juniper.Terminal.ConsoleBuffer.CheckGrids(), Juniper.Terminal.ConsoleBuffer.Height, Juniper.Terminal.ConsoleBuffer.lastBack, Juniper.Terminal.ConsoleBuffer.lastFore, Juniper.Terminal.ConsoleBuffer.tiles1, Juniper.Terminal.ConsoleBuffer.tiles2, Juniper.Terminal.ConsoleBuffer.Width, and Juniper.Terminal.ConsoleBuffer.x.
Referenced by Juniper.Terminal.ConsoleBuffer.Prompt().
GetBackgroundColor()
ConsoleColor Juniper.Terminal.ConsoleBuffer.GetBackgroundColor (int x, int y) inline
Implements Juniper.Terminal.IConsoleBuffer.
Definition at line 103 of file ConsoleBuffer.cs.
         {
             if (IsInBounds(x, y))
             {
                 return tiles1[x, y].Back;
             }
             else
             {
                 return ConsoleColor.Black;
             }
         }
References Juniper.Puzzles.Tile.Back, Juniper.Terminal.ConsoleBuffer.IsInBounds(), Juniper.Terminal.ConsoleBuffer.tiles1, and Juniper.Terminal.ConsoleBuffer.x.
GetCursorPosition()
static int int y Juniper.Terminal.ConsoleBuffer.GetCursorPosition () inline static private
Definition at line 223 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return default;
             }
             if (!NativeMethods.GetCursorPos(out var point))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
             return (point.X, point.Y);
         }
IsInBounds()
bool Juniper.Terminal.ConsoleBuffer.IsInBounds (int x, int y) inline
Determine if a point is within the bounds of the board
Parameters
x
y
Returns
Definition at line 97 of file ConsoleBuffer.cs.
         {
             return x >= 0 && x < Width
                 && y >= 0 && y < Height;
         }
References Juniper.Terminal.ConsoleBuffer.Height, Juniper.Terminal.ConsoleBuffer.Width, and Juniper.Terminal.ConsoleBuffer.x.
Referenced by Juniper.Terminal.ConsoleBuffer.Draw(), and Juniper.Terminal.ConsoleBuffer.GetBackgroundColor().
Prompt()
void Juniper.Terminal.ConsoleBuffer.Prompt (string message, bool pause) inline
Definition at line 204 of file ConsoleBuffer.cs.
         {
             if (message is null)
             {
                 throw new ArgumentNullException(nameof(message));
             }
             this.Draw(0, Height - 1, message, ConsoleColor.Red, ConsoleColor.DarkRed);
             Flush();
             CursorLeft = message.Length;
             CursorTop = Height - 1;
             if (pause)
             {
                 _ = ReadKey(true);
             }
         }
References Juniper.Terminal.ConsoleBuffer.Draw(), Juniper.Terminal.ConsoleBuffer.Flush(), and Juniper.Terminal.ConsoleBuffer.Height.
SetFontSize()
void Juniper.Terminal.ConsoleBuffer.SetFontSize (int width, int height) inline
Definition at line 238 of file ConsoleBuffer.cs.
         {
             if (!IsWindows)
             {
                 return;
             }
             var info = new NativeMethods.CONSOLE_FONT_INFO_EX();
             info.cbSize = (uint)Marshal.SizeOf(info);
             info.dwFontSize.X = (short)width;
             info.dwFontSize.Y = (short)height;
             if (!NativeMethods.SetCurrentConsoleFontEx(outputHandle, false, info))
             {
                 throw new Win32Exception(Marshal.GetLastWin32Error());
             }
         }
References Juniper.Terminal.ConsoleBuffer.NativeMethods.CONSOLE_FONT_INFO_EX.cbSize, Juniper.Terminal.ConsoleBuffer.IsWindows, Juniper.Terminal.ConsoleBuffer.outputHandle, and Juniper.Terminal.ConsoleBuffer.NativeMethods.SetCurrentConsoleFontEx().
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer().
Teardown()
void Juniper.Terminal.ConsoleBuffer.Teardown () inline private
Definition at line 85 of file ConsoleBuffer.cs.
         {
             ForegroundColor = startFore;
             BackgroundColor = startBack;
         }
References Juniper.Terminal.ConsoleBuffer.startBack, and Juniper.Terminal.ConsoleBuffer.startFore.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer_CancelKeyPress(), and Juniper.Terminal.ConsoleBuffer.~ConsoleBuffer().
Member Data Documentation
AbsoluteBottom
int Juniper.Terminal.ConsoleBuffer.AbsoluteBottom => Height - 1
Definition at line 36 of file ConsoleBuffer.cs.
AbsoluteLeft
int Juniper.Terminal.ConsoleBuffer.AbsoluteLeft => 0
Definition at line 33 of file ConsoleBuffer.cs.
AbsoluteRight
int Juniper.Terminal.ConsoleBuffer.AbsoluteRight => Width - 1
Definition at line 34 of file ConsoleBuffer.cs.
AbsoluteTop
int Juniper.Terminal.ConsoleBuffer.AbsoluteTop => 0
Definition at line 35 of file ConsoleBuffer.cs.
Height
int Juniper.Terminal.ConsoleBuffer.Height => tiles1?.GetHeight() ?? -1
Definition at line 38 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.CheckGrids(), Juniper.Terminal.ConsoleBuffer.Flush(), Juniper.Terminal.ConsoleBuffer.IsInBounds(), and Juniper.Terminal.ConsoleBuffer.Prompt().
IsWindows
readonly bool Juniper.Terminal.ConsoleBuffer.IsWindows static
Initial value:
= Environment.OSVersion.Platform == PlatformID.Win32NT
            || Environment.OSVersion.Platform == PlatformID.Win32S
            || Environment.OSVersion.Platform == PlatformID.Win32Windows
            || Environment.OSVersion.Platform == PlatformID.WinCE
Definition at line 16 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer(), and Juniper.Terminal.ConsoleBuffer.SetFontSize().
lastBack
ConsoleColor Juniper.Terminal.ConsoleBuffer.lastBack private
Definition at line 28 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer(), and Juniper.Terminal.ConsoleBuffer.Flush().
lastFore
ConsoleColor Juniper.Terminal.ConsoleBuffer.lastFore private
Definition at line 29 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer(), and Juniper.Terminal.ConsoleBuffer.Flush().
outputHandle
readonly IntPtr Juniper.Terminal.ConsoleBuffer.outputHandle private
Definition at line 24 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer(), and Juniper.Terminal.ConsoleBuffer.SetFontSize().
startBack
readonly ConsoleColor Juniper.Terminal.ConsoleBuffer.startBack private
Definition at line 27 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer(), and Juniper.Terminal.ConsoleBuffer.Teardown().
startFore
readonly ConsoleColor Juniper.Terminal.ConsoleBuffer.startFore private
Definition at line 26 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.ConsoleBuffer(), and Juniper.Terminal.ConsoleBuffer.Teardown().
tiles1
Tile [,] Juniper.Terminal.ConsoleBuffer.tiles1 private
Definition at line 30 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.CheckGrids(), Juniper.Terminal.ConsoleBuffer.Draw(), Juniper.Terminal.ConsoleBuffer.Flush(), and Juniper.Terminal.ConsoleBuffer.GetBackgroundColor().
tiles2
Tile [,] Juniper.Terminal.ConsoleBuffer.tiles2 private
Definition at line 31 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.CheckGrids(), and Juniper.Terminal.ConsoleBuffer.Flush().
Width
int Juniper.Terminal.ConsoleBuffer.Width => tiles1?.GetWidth() ?? -1
Definition at line 37 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.CheckGrids(), Juniper.Terminal.ConsoleBuffer.Flush(), and Juniper.Terminal.ConsoleBuffer.IsInBounds().
x
int Juniper.Terminal.ConsoleBuffer.x static
Definition at line 223 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.CheckCursor(), Juniper.Terminal.ConsoleBuffer.Draw(), Juniper.Terminal.ConsoleBuffer.Flush(), Juniper.Terminal.ConsoleBuffer.GetBackgroundColor(), and Juniper.Terminal.ConsoleBuffer.IsInBounds().
Event Documentation
SizeChanged
EventHandler<SizeChangedEventArgs> Juniper.Terminal.ConsoleBuffer.SizeChanged
Definition at line 40 of file ConsoleBuffer.cs.
Referenced by Juniper.Terminal.ConsoleBuffer.CheckGrids().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Terminal/ConsoleBuffer.cs