Juniper: Juniper.World.SunPosition Class Reference
Juniper.World.SunPosition Class Reference
Calculates the position of the Sun in relation to the user's current position on spaceship Earth. Only one of this component is allowed on a gameObject at a time. This component also requires a GPSLocation component on the same gameObject and a CompassRose component somewhere in the scene. This component executes in the editor.
Public Member Functions
void Update ()
Retrieves the current location and/or compass, if they are needed, updates the currentTime, calculates the correct sun position from that time, and optionally prints a debug report.
Public Attributes
bool FakeTime
When set to true, the component will use a static, set time (set in the field time instead of the current system time.
EditableDateTime time
The static time to use, when FakeTime is set to true.
HorizontalSphericalPosition orientation
The pose of the sun from the user's current vantage point.
bool DebugReport
When set to true, the Update function will also print a report showing the internal state of the component.
bool CanCalculateCurrentLocalPosition
Returns true when location is not null and has a valid GPS coordinate, and compass is not null and has a valid Heading.
Private Member Functions
DateTime GetTime ()
Gets either the fake time the user specified for the component, or the current system time if FakeTime is set to false.
void PrintDebugReport ()
Prints a report showing the internal state of the component.
Private Attributes
GPSLocation location
The GPS management component.
CompassRose compass
The magnetic compass management component.
DateTime currentTime
The time for which the sun position is being calculated.
Detailed Description
Calculates the position of the Sun in relation to the user's current position on spaceship Earth. Only one of this component is allowed on a gameObject at a time. This component also requires a GPSLocation component on the same gameObject and a CompassRose component somewhere in the scene. This component executes in the editor.
Definition at line 18 of file SunPosition.cs.
Member Function Documentation
GetTime()
DateTime Juniper.World.SunPosition.GetTime () inline private
Gets either the fake time the user specified for the component, or the current system time if FakeTime is set to false.
Returns
The time.
Definition at line 100 of file SunPosition.cs.
         {
             if (!FakeTime)
             {
                 time = EditableDateTime.Now.FixTime();
             }
             return time.Value.ToUniversalTime().FixTime();
         }
References Juniper.World.SunPosition.FakeTime, Juniper.EditableDateTime.Now, Juniper.World.SunPosition.time, and Juniper.EditableDateTime.Value.
Referenced by Juniper.World.SunPosition.Update().
PrintDebugReport()
void Juniper.World.SunPosition.PrintDebugReport () inline private
Prints a report showing the internal state of the component.
Definition at line 113 of file SunPosition.cs.
         {
             ScreenDebugger.PrintFormat("  {0}", currentTime.ToLocalTime().FixTime());
             if (location == null)
             {
                 ScreenDebugger.Print("  No location service");
             }
             else if (!location.HasCoord)
             {
                 ScreenDebugger.Print("  No location yet");
             }
             if (compass == null)
             {
                 ScreenDebugger.Print("  No compass service");
             }
             else if (!compass.HasHeading)
             {
                 ScreenDebugger.Print("  No compass heading yet");
             }
             if (location?.HasCoord == true && compass?.HasHeading == true)
             {
                 ScreenDebugger.PrintFormat("  Azimuth {0}, Altitude {1}",
                     orientation.AzimuthDegrees.Label(UnitOfMeasure.Degrees, 3),
                     orientation.AltitudeDegrees.Label(UnitOfMeasure.Degrees, 3));
             }
         }
References Juniper.World.GIS.HorizontalSphericalPosition.AltitudeDegrees, Juniper.World.GIS.HorizontalSphericalPosition.AzimuthDegrees, Juniper.World.SunPosition.compass, Juniper.World.SunPosition.currentTime, Juniper.World.GPSLocation.HasCoord, Juniper.World.CompassRose.HasHeading, Juniper.World.SunPosition.location, Juniper.World.SunPosition.orientation, System.ScreenDebugger.Print(), and System.ScreenDebugger.PrintFormat().
Referenced by Juniper.World.SunPosition.Update().
Update()
void Juniper.World.SunPosition.Update () inline
Retrieves the current location and/or compass, if they are needed, updates the currentTime, calculates the correct sun position from that time, and optionally prints a debug report.
Definition at line 58 of file SunPosition.cs.
         {
             if (location == null)
             {
                 location = GetComponent<GPSLocation>();
             }
             if (compass == null)
             {
                 compass = ComponentExt.FindAny<CompassRose>();
             }
             currentTime = GetTime();
             orientation = location.Coord.ToSunPosition(currentTime);
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.World.SunPosition.compass, Juniper.World.GPSLocation.Coord, Juniper.World.SunPosition.currentTime, Juniper.World.SunPosition.DebugReport, Juniper.World.SunPosition.GetTime(), Juniper.World.SunPosition.location, Juniper.World.SunPosition.orientation, Juniper.World.SunPosition.PrintDebugReport(), and Juniper.World.GIS.LatLngPoint.ToSunPosition().
Member Data Documentation
CanCalculateCurrentLocalPosition
bool Juniper.World.SunPosition.CanCalculateCurrentLocalPosition
Initial value:
=>
            compass != null
                && compass.HasHeading
                && location?.HasCoord == true
Returns true when location is not null and has a valid GPS coordinate, and compass is not null and has a valid Heading.
true if can calculate current local position; otherwise, false.
Definition at line 48 of file SunPosition.cs.
compass
CompassRose Juniper.World.SunPosition.compass private
The magnetic compass management component.
Definition at line 88 of file SunPosition.cs.
Referenced by Juniper.World.SunPosition.PrintDebugReport(), and Juniper.World.SunPosition.Update().
currentTime
DateTime Juniper.World.SunPosition.currentTime private
The time for which the sun position is being calculated.
Definition at line 93 of file SunPosition.cs.
Referenced by Juniper.World.SunPosition.PrintDebugReport(), and Juniper.World.SunPosition.Update().
DebugReport
bool Juniper.World.SunPosition.DebugReport
When set to true, the Update function will also print a report showing the internal state of the component.
Definition at line 41 of file SunPosition.cs.
Referenced by Juniper.World.SunPosition.Update().
FakeTime
bool Juniper.World.SunPosition.FakeTime
When set to true, the component will use a static, set time (set in the field time instead of the current system time.
Definition at line 24 of file SunPosition.cs.
Referenced by Juniper.World.SunPosition.GetTime().
location
GPSLocation Juniper.World.SunPosition.location private
The GPS management component.
Definition at line 83 of file SunPosition.cs.
Referenced by Juniper.World.SunPosition.PrintDebugReport(), and Juniper.World.SunPosition.Update().
orientation
HorizontalSphericalPosition Juniper.World.SunPosition.orientation
The pose of the sun from the user's current vantage point.
Definition at line 35 of file SunPosition.cs.
Referenced by Juniper.World.SunPosition.PrintDebugReport(), and Juniper.World.SunPosition.Update().
time
EditableDateTime Juniper.World.SunPosition.time
The static time to use, when FakeTime is set to true.
Definition at line 29 of file SunPosition.cs.
Referenced by Juniper.World.SunPosition.GetTime().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/World/SunPosition.cs