Juniper: Juniper.Permissions.AbstractPermissionHandler Class Reference
Juniper.Permissions.AbstractPermissionHandler Class Reference
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Public Member Functions
void Awake ()
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void Install (bool reset)
Install, with or without a full reset.
virtual void Uninstall ()
Remove platform-specific features from the object.
Detailed Description
Perform system-specific authorization requests, such as GPS on Android, or Microphone on iOS.
Definition at line 23 of file PermissionHandler.cs.
Member Function Documentation
Awake()
void Juniper.Permissions.AbstractPermissionHandler.Awake () inline
Definition at line 25 of file PermissionHandler.cs.
         {
             Install(false);
         }
References Juniper.Permissions.AbstractPermissionHandler.Install().
Install()
virtual void Juniper.Permissions.AbstractPermissionHandler.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Permissions.WindowsMRPermissionHandler.
Definition at line 44 of file PermissionHandler.cs.
         {
         }
Referenced by Juniper.Permissions.AbstractPermissionHandler.Awake(), and Juniper.Permissions.AbstractPermissionHandler.Reinstall().
Reinstall()
virtual void Juniper.Permissions.AbstractPermissionHandler.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 30 of file PermissionHandler.cs.
         {
             Install(true);
         }
References Juniper.Permissions.AbstractPermissionHandler.Install().
Uninstall()
virtual void Juniper.Permissions.AbstractPermissionHandler.Uninstall () inline virtual
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 48 of file PermissionHandler.cs.
         {
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Permissions/PermissionHandler.cs