Juniper: Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule Class Reference
Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule Class Reference
Public Member Functions
GetFirewallRule (string name)
async Task< CIDRBlock[]> GetRangesAsync ()
async Task< bool > ExistsAsync ()
Task< int > RunAsync ()
int Run ()
Protected Member Functions
override async Task< int > RunAsync (IEnumerable< string > arguments)
Properties
bool Verbose [get, set]
override IEnumerable< string > Arguments [get]
bool UseShellExecute [get, set]
bool LoadUserProfile [get, set]
Encoding Encoding [get, set]
string TotalStandardOutput [get, private set]
string TotalStandardError [get, private set]
Events
EventHandler< StringEventArgs > Info
EventHandler< StringEventArgs > Warning
EventHandler< ErrorEventArgs > Err
Static Private Member Functions
static IEnumerable< CIDRBlock > FindBlocks (string message)
Static Private Attributes
static readonly Regex remoteIPRangePattern = new Regex("RemoteIP:\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+/\\d+)", RegexOptions.Compiled)
Detailed Description
Definition at line 10 of file GetFirewallRule.cs.
Constructor & Destructor Documentation
GetFirewallRule()
Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetFirewallRule (string name) inline
Definition at line 15 of file GetFirewallRule.cs.
             : base("show", name)
         {
         }
Member Function Documentation
ExistsAsync()
async Task<bool> Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.ExistsAsync () inline
Definition at line 74 of file GetFirewallRule.cs.
         {
             return 1 == await RunAsync()
                 .ConfigureAwait(false);
         }
References Juniper.Processes.AbstractShellCommand.RunAsync().
Referenced by Juniper.HTTP.Server.HttpServer.BanExistsAsync().
FindBlocks()
static IEnumerable<CIDRBlock> Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.FindBlocks (string message) inline static private
Definition at line 58 of file GetFirewallRule.cs.
         {
             var matches = remoteIPRangePattern.Matches(message);
             foreach (Match match in matches)
             {
                 yield return CIDRBlock.Parse(match.Groups[1].Value);
             }
         }
References Juniper.HTTP.Server.CIDRBlock.Parse(), and Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.remoteIPRangePattern.
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync().
GetRangesAsync()
async Task<CIDRBlock[]> Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync () inline
Definition at line 67 of file GetFirewallRule.cs.
         {
             _ = await RunAsync()
                 .ConfigureAwait(false);
             return FindBlocks(TotalStandardOutput.Trim()).ToArray();
         }
References Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.FindBlocks(), Juniper.Processes.AbstractShellCommand.RunAsync(), and Juniper.Processes.AbstractShellCommand.TotalStandardOutput.
Run()
int Juniper.Processes.AbstractShellCommand.Run () inline inherited
Definition at line 58 of file AbstractShellCommand.cs.
         {
             return RunAsync().Result;
         }
References Juniper.Processes.AbstractShellCommand.RunAsync().
RunAsync() [1/2]
override async Task<int> Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.RunAsync (IEnumerable< string > arguments) inline protected virtual
Reimplemented from Juniper.Processes.AbstractShellCommand.
Definition at line 38 of file GetFirewallRule.cs.
         {
             _ = await base.RunAsync(arguments)
                 .ConfigureAwait(false);
             var message = TotalStandardOutput.Trim();
             if (message == "No rules match the specified criteria.")
             {
                 return 0;
             }
             else if (!message.EndsWith("Ok.", false, CultureInfo.InvariantCulture))
             {
                 throw new InvalidOperationException(message);
             }
             else
             {
                 return 1;
             }
         }
References Juniper.Processes.AbstractShellCommand.TotalStandardOutput.
RunAsync() [2/2]
Task<int> Juniper.Processes.AbstractShellCommand.RunAsync () inline inherited
Definition at line 52 of file AbstractShellCommand.cs.
         {
             return RunAsync(Arguments);
         }
References Juniper.Processes.AbstractShellCommand.Arguments.
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.ExistsAsync(), Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync(), and Juniper.Processes.AbstractShellCommand.Run().
Member Data Documentation
remoteIPRangePattern
readonly Regex Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.remoteIPRangePattern = new Regex("RemoteIP:\\s+(\\d+\\.\\d+\\.\\d+\\.\\d+/\\d+)", RegexOptions.Compiled) static private
Definition at line 36 of file GetFirewallRule.cs.
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.FindBlocks().
Property Documentation
Arguments
override IEnumerable<string> Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.Arguments get protected
Definition at line 21 of file GetFirewallRule.cs.
         {
             get
             {
                 foreach (var arg in base.Arguments)
                 {
                     yield return arg;
                 }
                 if (Verbose)
                 {
                     yield return $"verbose";
                 }
             }
         }
Encoding
Encoding Juniper.Processes.AbstractShellCommand.Encoding get set inherited
Definition at line 26 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
LoadUserProfile
bool Juniper.Processes.AbstractShellCommand.LoadUserProfile get set inherited
Definition at line 24 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
TotalStandardError
string Juniper.Processes.AbstractShellCommand.TotalStandardError get private set inherited
Definition at line 30 of file AbstractShellCommand.cs.
 { get; private set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
TotalStandardOutput
string Juniper.Processes.AbstractShellCommand.TotalStandardOutput get private set inherited
Definition at line 28 of file AbstractShellCommand.cs.
 { get; private set; }
Referenced by Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.GetRangesAsync(), Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.RunAsync(), Juniper.Processes.AbstractShellCommand.RunAsync(), Juniper.HTTP.Server.Administration.NetSH.DeleteFirewallRule.RunAsync(), and Juniper.HTTP.Server.Administration.NetSH.AddFirewallRule.RunAsync().
UseShellExecute
bool Juniper.Processes.AbstractShellCommand.UseShellExecute get set inherited
Definition at line 22 of file AbstractShellCommand.cs.
 { get; set; }
Referenced by Juniper.Processes.AbstractShellCommand.RunAsync().
Verbose
bool Juniper.HTTP.Server.Administration.NetSH.GetFirewallRule.Verbose get set
Definition at line 13 of file GetFirewallRule.cs.
 { get; set; }
Event Documentation
Err
EventHandler<ErrorEventArgs> Juniper.Processes.AbstractShellCommand.Err inherited
Definition at line 20 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnError().
Info
EventHandler<StringEventArgs> Juniper.Processes.AbstractShellCommand.Info inherited
Definition at line 18 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnInfo().
Warning
EventHandler<StringEventArgs> Juniper.Processes.AbstractShellCommand.Warning inherited
Definition at line 19 of file AbstractShellCommand.cs.
Referenced by Juniper.Processes.AbstractShellCommand.OnWarning().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Server/Administration/NetSH/GetFirewallRule.cs