Juniper: Juniper.UnityEditor.ConfigurationManagement.RawPackage Class Reference
Juniper.UnityEditor.ConfigurationManagement.RawPackage Class Reference
Public Member Functions
override void Install (IProgress prog=null)
override void Activate (BuildTargetGroup targetGroup, IProgress prog=null)
override void Uninstall (IProgress prog=null)
Public Attributes
string Name
string CompilerDefine
Static Public Attributes
static string ROOT_DIRECTORY = PathExt.FixPath("Assets/Juniper/ThirdParty/Optional")
Properties
string InputZipFileName [get]
Static Private Member Functions
static void DeleteAll (IEnumerable< string > paths, Func< string, bool > tryDelete, IProgress prog)
Detailed Description
Definition at line 17 of file RawPackage.cs.
Member Function Documentation
Activate()
override void Juniper.UnityEditor.ConfigurationManagement.RawPackage.Activate (BuildTargetGroup targetGroup, IProgress prog = null) inline virtual
Reimplemented from Juniper.UnityEditor.ConfigurationManagement.AbstractPackage.
Definition at line 42 of file RawPackage.cs.
         {
             base.Activate(targetGroup, prog);
             if (Name == "Vuforia")
             {
                 PlayerSettings.SetPlatformVuforiaEnabled(targetGroup, true);
             }
             if (targetGroup == BuildTargetGroup.Android)
             {
                 if (Name == "GoogleARCore")
                 {
 #if UNITY_2018_2_OR_NEWER
                     PlayerSettings.Android.ARCoreEnabled = true;
 #endif
                 }
                 else if (Name == "GoogleVR")
                 {
                     FileExt.Copy(
                         PathExt.FixPath("Assets/GoogleVR/Plugins/Android/AndroidManifest-6DOF.xml"),
                         PathExt.FixPath("Assets/Plugins/Android/AndroidManifest.xml"),
                         true);
                 }
             }
             else if (targetGroup == BuildTargetGroup.iOS)
             {
                 if (Name == "UnityARKitPlugin")
                 {
                     PlayerSettingsExt.iOS.RequiresARKitSupport = true;
                     if (string.IsNullOrEmpty(PlayerSettings.iOS.cameraUsageDescription))
                     {
                         PlayerSettings.iOS.cameraUsageDescription = "Augmented reality camera view";
                     }
                 }
             }
         }
References System.IO.FileExt.Copy(), System.IO.PathExt.FixPath(), Juniper.UnityEditor.ConfigurationManagement.AbstractPackage.Name, and Juniper.UnityEditor.PlayerSettingsExt.iOS.RequiresARKitSupport.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.Activate().
DeleteAll()
static void Juniper.UnityEditor.ConfigurationManagement.RawPackage.DeleteAll (IEnumerable< string > paths, Func< string, bool > tryDelete, IProgress prog) inline static private
Definition at line 81 of file RawPackage.cs.
         {
             prog?.Report(0, "Deleting");
             var prefixedPath = paths
                 .Select(path => Path.Combine("Assets", path))
                 .ToArray();
             var subProgs = prog.Split(prefixedPath.Length);
             var index = 0;
             foreach (var path in prefixedPath)
             {
                 try
                 {
                     subProgs[index]?.Report(0);
                     if (tryDelete(path))
                     {
                         subProgs[index]?.Report(1);
                     }
                     ++index;
                 }
                 catch (OperationCanceledException)
                 {
                     throw;
                 }
                 catch (Exception exp)
                 {
                     Debug.LogException(exp);
                 }
             }
             prog?.Report(1, "Deleted");
         }
References Juniper.Progress.IProgress.Report().
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall().
Install()
override void Juniper.UnityEditor.ConfigurationManagement.RawPackage.Install (IProgress prog = null) inline virtual
Reimplemented from Juniper.UnityEditor.ConfigurationManagement.AbstractPackage.
Definition at line 30 of file RawPackage.cs.
         {
             base.Install(prog);
             if (File.Exists(InputZipFileName))
             {
                 Decompressor.DecompressDirectory(InputZipFileName, "Assets", prog);
             }
             prog?.Report(1);
         }
References Juniper.Zip.Decompressor.DecompressDirectory(), and Juniper.UnityEditor.ConfigurationManagement.RawPackage.InputZipFileName.
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.InstallRawPackages().
Uninstall()
override void Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall (IProgress prog = null) inline virtual
Reimplemented from Juniper.UnityEditor.ConfigurationManagement.AbstractPackage.
Definition at line 115 of file RawPackage.cs.
         {
             base.Uninstall(prog);
             var progs = prog.Split(4);
             var dirs = Decompressor.RecurseDirectories(InputZipFileName, progs[2]);
             var files = Decompressor.RecurseFiles(InputZipFileName, progs[0]);
             files = files
                 .Union(files.Select(file => file + ".meta"))
                 .Union(dirs.Select(dir => dir + ".meta"))
                 .Where(path => !path.EndsWith(".meta.meta"));
             DeleteAll(files, FileExt.TryDelete, progs[1]);
             DeleteAll(dirs.Reverse(), DirectoryExt.TryDelete, progs[3]);
         }
References Juniper.UnityEditor.ConfigurationManagement.RawPackage.DeleteAll(), Juniper.UnityEditor.ConfigurationManagement.RawPackage.InputZipFileName, Juniper.Zip.Decompressor.RecurseDirectories(), Juniper.Zip.Decompressor.RecurseFiles(), System.IO.FileExt.TryDelete(), and System.IO.DirectoryExt.TryDelete().
Referenced by Juniper.UnityEditor.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages().
Member Data Documentation
CompilerDefine
string Juniper.UnityEditor.ConfigurationManagement.AbstractPackage.CompilerDefine inherited
Definition at line 10 of file AbstractPackage.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.Platforms.GetCompilerDefines(), and Juniper.UnityEditor.ConfigurationManagement.UnityPackage.UnityPackage().
Name
string Juniper.UnityEditor.ConfigurationManagement.AbstractPackage.Name inherited
Definition at line 9 of file AbstractPackage.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Activate(), Juniper.UnityEditor.ConfigurationManagement.UnityPackage.Install(), Juniper.UnityEditor.ConfigurationManagement.UnityPackage.Uninstall(), and Juniper.UnityEditor.ConfigurationManagement.UnityPackage.UnityPackage().
ROOT_DIRECTORY
string Juniper.UnityEditor.ConfigurationManagement.RawPackage.ROOT_DIRECTORY = PathExt.FixPath("Assets/Juniper/ThirdParty/Optional") static
Definition at line 19 of file RawPackage.cs.
Referenced by Juniper.UnityEditor.ConfigurationManagement.Platforms.Platforms().
Property Documentation
InputZipFileName
string Juniper.UnityEditor.ConfigurationManagement.RawPackage.InputZipFileName get
Definition at line 23 of file RawPackage.cs.
         {
             get
             {
                 return Path.ChangeExtension(Path.Combine(ROOT_DIRECTORY, Name), "zip");
             }
         }
Referenced by Juniper.UnityEditor.ConfigurationManagement.RawPackage.Install(), and Juniper.UnityEditor.ConfigurationManagement.RawPackage.Uninstall().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Editor/ConfigurationManagement/RawPackage.cs