Juniper: Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT > Class Template Reference
Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT > Class Template Reference
Public Member Functions
DataMessageHandler (WebSocketConnection< SocketT > socket, string message, FactoryT factory)
Task SendAsync (ResultT value)
Events
EventHandler< EventArgs< ResultT > > DataMessage
EventHandler< ErrorEventArgs > Error
Private Member Functions
void Socket_Closed (object sender, EventArgs e)
void Socket_DataMessage (object sender, DataMessageEventArgs e)
void OnDataMessage (ResultT value)
void OnError (Exception exp)
Private Attributes
readonly WebSocketConnection< SocketT > socket
readonly string message
readonly FactoryT factory
Detailed Description
Type Constraints
FactoryT : class
FactoryT : IFactory
FactoryT : ResultT
FactoryT : MediaType.Application
SocketT : WebSocket
Definition at line 10 of file DataMessageHandler.cs.
Constructor & Destructor Documentation
DataMessageHandler()
Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler (WebSocketConnection< SocketT > socket, string message, FactoryT factory) inline
Definition at line 21 of file DataMessageHandler.cs.
         {
             if (string.IsNullOrEmpty(message))
             {
                 throw new ArgumentNullException(nameof(message), $"{nameof(message)} parameter must not be null or empty.");
             }
             if (factory is null)
             {
                 throw new ArgumentNullException(nameof(factory));
             }
             if (socket is null)
             {
                 throw new ArgumentNullException(nameof(socket));
             }
             this.socket = socket;
             this.message = message;
             this.factory = factory;
             socket.DataMessage += Socket_DataMessage;
             socket.Closed += Socket_Closed;
         }
References Juniper.HTTP.WebSocketConnection< WebSocketT >.Closed, Juniper.HTTP.WebSocketConnection< WebSocketT >.DataMessage, Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.factory, Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.message, Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.socket, Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_Closed(), and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_DataMessage().
Member Function Documentation
OnDataMessage()
void Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.OnDataMessage (ResultT value) inline private
Definition at line 74 of file DataMessageHandler.cs.
         {
             DataMessage?.Invoke(this, new EventArgs<ResultT>(value));
         }
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_DataMessage().
OnError()
void Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.OnError (Exception exp) inline private
Definition at line 80 of file DataMessageHandler.cs.
         {
             Error?.Invoke(this, new ErrorEventArgs(exp));
         }
References Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Error.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_DataMessage().
SendAsync()
Task Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.SendAsync (ResultT value) inline
Definition at line 46 of file DataMessageHandler.cs.
         {
             return factory.SerializeAsync(socket, value);
         }
References Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.factory, and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.socket.
Socket_Closed()
void Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_Closed (object sender, EventArgs e) inline private
Definition at line 51 of file DataMessageHandler.cs.
         {
             socket.DataMessage -= Socket_DataMessage;
             socket.Closed -= Socket_Closed;
         }
References Juniper.HTTP.WebSocketConnection< WebSocketT >.Closed, Juniper.HTTP.WebSocketConnection< WebSocketT >.DataMessage, Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.socket, and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_DataMessage().
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler().
Socket_DataMessage()
void Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_DataMessage (object sender, DataMessageEventArgs e) inline private
Definition at line 57 of file DataMessageHandler.cs.
         {
             if (e.Value.Message == message)
             {
                 try
                 {
                     var value = factory.Deserialize(e.Value.Data);
                     OnDataMessage(value);
                 }
                 catch (Exception exp)
                 {
                     OnError(exp);
                 }
             }
         }
References Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.factory, Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.message, Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.OnDataMessage(), Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.OnError(), and Juniper.EventArgs< T >.Value.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler(), and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_Closed().
Member Data Documentation
factory
readonly FactoryT Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.factory private
Definition at line 16 of file DataMessageHandler.cs.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler(), Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.SendAsync(), and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_DataMessage().
message
readonly string Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.message private
Definition at line 15 of file DataMessageHandler.cs.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler(), and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_DataMessage().
socket
readonly WebSocketConnection<SocketT> Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.socket private
Definition at line 14 of file DataMessageHandler.cs.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessageHandler(), Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.SendAsync(), and Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Socket_Closed().
Event Documentation
DataMessage
EventHandler<EventArgs<ResultT> > Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.DataMessage
Definition at line 18 of file DataMessageHandler.cs.
Error
EventHandler<ErrorEventArgs> Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.Error
Definition at line 19 of file DataMessageHandler.cs.
Referenced by Juniper.HTTP.DataMessageHandler< ResultT, FactoryT, SocketT >.OnError().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/HTTP/DataMessageHandler.cs