Juniper: BitMiracle.LibJpeg.Classic.JpegCompressStruct Class Reference
BitMiracle.LibJpeg.Classic.JpegCompressStruct Class Reference
JPEG compression routine.
Public Member Functions
JpegCompressStruct ()
Initializes a new instance of the JpegCompressStruct class.
JpegCompressStruct (JpegErrorMessage errorManager)
Initializes a new instance of the JpegCompressStruct class.
void JpegAbortCompress ()
Abort processing of a JPEG compression operation.
void JpegSuppressTables (bool suppress)
Forcibly suppress or un-suppress all quantization and Huffman tables.
void JpegFinishCompress ()
Finishes JPEG compression.
void JpegWriteMarker (int marker, byte[] data)
Write a special marker.
void JpegWriteMHeader (int marker, int datalen)
Writes special marker's header.
void JpegWriteMByte (byte val)
Writes a byte of special marker's data.
void JpegWriteTables ()
Alternate compression function: just write an abbreviated table file.
void JpegStdioDest (Stream outfile)
Sets output stream.
void JpegSetDefaults ()
Jpeg_set_defaultses this instance.
void JpegSetColorspace (JColorSpace colorspace)
Set the JPEG colorspace (property JpegCompressStruct.Jpeg_color_space, and choose colorspace-dependent parameters appropriately.
void JpegDefaultColorspace ()
Select an appropriate JPEG colorspace based on JpegCompressStruct.In_color_space, and calls JpegCompressStruct.JpegSetColorspace
void JpegSetQuality (int quality, bool force_baseline)
Constructs JPEG quantization tables appropriate for the indicated quality setting.
void JpegDefaultQTables (bool force_baseline)
Set or change the 'quality' (quantization) setting, using default tables and straight percentage-scaling quality scales. This entry point allows different scalings for luminance and chrominance.
void JpegSetLinearQuality (int scale_factor, bool force_baseline)
Same as JpegSetQuality except that the generated tables are the sample tables given in the JPEG specification section K.1, multiplied by the specified scale factor.
void JpegAddQuantTable (int which_tbl, int[] basic_table, int scale_factor, bool force_baseline)
Allows an arbitrary quantization table to be created.
void JpegSimpleProgression ()
Generates a default scan script for writing a progressive-JPEG file.
void JpegStartCompression (bool write_all_tables)
Starts JPEG compression.
int JpegWriteScanlines (byte[][] scanlines, int num_lines)
Write some scanlines of data to the JPEG compressor.
int JpegWriteRawData (byte[][][] data, int num_lines)
Alternate entry point to write raw data.
void JpegWriteCoefficients (JVirtArray< JBlock >[] coef_arrays)
Compression initialization for writing raw-coefficient data. Useful for lossless transcoding.
void JpegAbort ()
void JpegDestroy ()
void ErrExit (JMessageCode code)
Used for fatal errors (print message and exit).
void ErrExit (JMessageCode code, params object[] args)
Used for fatal errors (print message and exit).
void ErrExit (int code, params object[] args)
Used for fatal errors (print message and exit).
void WarnMS (JMessageCode code)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void WarnMS (JMessageCode code, params object[] args)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void WarnMS (int code, params object[] args)
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
void TraceMS (int lvl, JMessageCode code)
Shows informational and debugging messages.
void TraceMS (int lvl, JMessageCode code, params object[] args)
Shows informational and debugging messages.
void TraceMS (int lvl, int code, params object[] args)
Shows informational and debugging messages.
Static Public Member Functions
static int JpegQualityScaling (int quality)
Converts a value on the IJG-recommended quality scale to a linear scaling percentage.
static JVirtArray< byte > CreateSamplesArray (int samplesPerRow, int numberOfRows)
Creates the array of samples.
static JVirtArray< JBlock > CreateBlocksArray (int blocksPerRow, int numberOfRows)
Creates the array of blocks.
static byte [][] AllocJpegSamples (int samplesPerRow, int numberOfRows)
Creates 2-D sample array.
Public Attributes
override bool IsDecompressor => false
Retrieves false because this is not decompressor.
int Max_v_samp_factor => m_max_v_samp_factor
Gets the largest vertical sample factor.
JpegComponentInfo [] Component_info => compInfo
Gets the components that appears in SOF.
JQuantTable [] Quant_tbl_ptrs => m_quant_tbl_ptrs
Gets the coefficient quantization tables.
JHuffmanTable [] Dc_huff_tbl_ptrs => m_dc_huff_tbl_ptrs
Gets the Huffman coding tables.
JHuffmanTable [] Ac_huff_tbl_ptrs => m_ac_huff_tbl_ptrs
Gets the Huffman coding tables.
int Next_scanline => m_next_scanline
Gets the index of next scanline to be written to JpegCompressStruct.JpegWriteScanlines.
Static Public Attributes
static string Copyright => "Copyright (C) 2008-2018, Bit Miracle"
Gets the LibJpeg's copyright.
Properties
int ScaleNum [get, set]
The scale numerator
int ScaleDenom [get, set]
The scale denomenator
int [] QScaleFactor = new int[JpegConstants.NUM_QUANT_TBLS] [get, set]
corresponding scale factors (percentage, initialized 100).
bool DoFancyDownsampling [get, set]
TRUE=apply fancy downsampling
JColorTransform ColorTransform [get, set]
Color transform identifier, writes LSE marker if nonzero
int BlockSize [get, set]
the basic DCT block size: 1..16
LibJpeg.Classic.JpegDestinationManager Dest [get, set]
Gets or sets the destination for compressed data
int Image_width [get, set]
Gets or sets the width of image, in pixels.
int Image_height [get, set]
Gets or sets the height of image, in pixels.
int Input_components [get, set]
Gets or sets the number of color channels (components per pixel)
LibJpeg.Classic.JColorSpace In_color_space [get, set]
Gets or sets the color space of source image.
int Data_precision [get, set]
Gets or sets the number of bits of precision in image data.
int Num_components [get, set]
Gets or sets the number of color components for JPEG color space.
JColorSpace Jpeg_color_space [get, set]
Gets or sets the JPEG color space.
bool Raw_data_in [get, set]
Gets or sets a value indicating whether you will be supplying raw data.
bool OptimizeCoding [get, set]
Gets or sets a value indicating a way of using Huffman coding tables.
bool CCIR601Sampling [get, set]
Gets or sets a value indicating whether first samples are cosited.
int SmoothingFactor [get, set]
Gets or sets the coefficient of image smoothing.
JDctMethod DctMethod [get, set]
Gets or sets the algorithm used for the DCT step.
int RestartInterval [get, set]
Gets or sets the exact interval in MCU blocks.
int RestartInRows [get, set]
Gets or sets the interval in MCU rows.
bool Write_JFIF_header [get, set]
Gets or sets a value indicating whether the JFIF APP0 marker is emitted.
byte JFIF_major_version [get, set]
Gets or sets the version number to be written into the JFIF marker.
byte JFIF_minor_version [get, set]
Gets or sets the version number to be written into the JFIF marker.
DensityUnit Density_unit [get, set]
Gets or sets the resolution information to be written into the JFIF marker; not used otherwise.
short X_density [get, set]
Gets or sets the horizontal component of pixel ratio.
short Y_density [get, set]
Gets or sets the vertical component of pixel ratio.
bool Write_Adobe_marker [get, set]
Gets or sets a value indicating whether to emit Adobe APP14 marker.
JpegProgressManager?? Progress [get, set]
Progress monitor.
JpegErrorMessage?? Err [get, set]
Error handler module.
static string Version [get]
Gets the version of LibJpeg.
Private Member Functions
void JpegCalcJpegDimensions ()
void JpegCalcTransDimensions ()
void Initialize ()
Initialization of a JPEG compression object
void JInitCompressMaster ()
Master selection of compression modules. This is done once at the start of processing an image. We determine which modules will be used and give them appropriate initialization calls. This routine is in charge of selecting the modules to be executed and making an initialization call to each one.
void JInitCMasterControl (bool transcode_only)
Initialize master compression control.
void JInitCMainController (bool need_full_buffer)
Initialize main buffer controller.
void TransencodeMasterSelection (JVirtArray< JBlock >[] coef_arrays)
Master selection of compression modules for transcoding.
void InitialSetup (bool transcode_only)
Do computations that are needed before master selection phase
void ValidateScript ()
Verify that the scan script in scan_info[] is valid; also determine whether it uses progressive JPEG, and set progressive_mode.
void ReduceScript ()
void StdHuffTables ()
void AddHuffTable (ref JHuffmanTable htblptr, byte[] bits, byte[] val)
Define a Huffman table
void FillAScan (ref int scanIndex, int ci, int Ss, int Se, int Ah, int Al)
Support routine: generate one scan for specified component
void FillDcScans (ref int scanIndex, int ncomps, int Ah, int Al)
Support routine: generate interleaved DC scan if possible, else N scans
void FillScans (ref int scanIndex, int ncomps, int Ss, int Se, int Ah, int Al)
Support routine: generate one scan for each component
void JpegSetColorspaceSetComp (int index, int id, int hsamp, int vsamp, int quant, int dctbl, int actbl)
Private Attributes
internal JpegDestinationManager m_dest
internal int m_image_width
internal int m_image_height
internal int m_input_components
internal JColorSpace m_in_color_space
internal int jpeg_width
internal int jpeg_height
internal int m_data_precision
internal int m_num_components
internal JColorSpace m_jpeg_color_space
JpegComponentInfo [] compInfo
internal JQuantTable [] m_quant_tbl_ptrs = new JQuantTable[JpegConstants.NUM_QUANT_TBLS]
internal JHuffmanTable [] m_dc_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS]
internal JHuffmanTable [] m_ac_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS]
internal byte [] arith_dc_L = new byte[JpegConstants.NUM_ARITH_TBLS]
internal byte [] arith_dc_U = new byte[JpegConstants.NUM_ARITH_TBLS]
internal byte [] arith_ac_K = new byte[JpegConstants.NUM_ARITH_TBLS]
internal int m_num_scans
internal JpegScanInfo [] m_scan_info
internal bool m_raw_data_in
internal bool arith_code
internal bool optimizeEntropyCoding
internal bool CIR601sampling
internal int m_input_smoothing
internal JDctMethod m_dct_method
internal int m_restart_interval
internal int m_restart_in_rows
internal bool m_write_JFIF_header
internal byte m_JFIF_major_version
internal byte m_JFIF_minor_version
internal DensityUnit m_density_unit
internal short m_X_density
internal short m_Y_density
internal bool m_write_Adobe_marker
internal int m_next_scanline
internal bool m_progressive_mode
internal int m_max_h_samp_factor
internal int m_max_v_samp_factor
internal int min_DCT_h_scaled_size
internal int min_DCT_v_scaled_size
internal int m_total_iMCU_rows
internal int m_comps_in_scan
internal int [] m_cur_comp_info = new int[JpegConstants.MAX_COMPS_IN_SCAN]
internal int m_MCUs_per_row
internal int m_MCU_rows_in_scan
internal int m_blocks_in_MCU
internal int [] m_MCU_membership = new int[JpegConstants.C_MAX_BLOCKS_IN_MCU]
internal int m_Ss
internal int m_Se
internal int m_Ah
internal int m_Al
internal int [] natural_order
internal int lim_Se
internal JpegCompMaster m_master
internal JpegCMainController m_main
internal JpegCPrepController m_prep
internal JpegCCoefController m_coef
internal JpegMarkerWriter m_marker
internal JpegColorConverter m_cconvert
internal JpegDownsampler m_downsample
internal JpegForwardDct m_fdct
internal JpegEntropyEncoder m_entropy
internal JpegScanInfo [] scriptSpace
internal int m_script_space_size
Static Private Attributes
static readonly int [] std_luminance_quant_tbl
static readonly int [] std_chrominance_quant_tbl
static readonly byte [] bits_dc_luminance
static readonly byte [] val_dc_luminance = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 }
static readonly byte [] bits_dc_chrominance
static readonly byte [] val_dc_chrominance = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 }
static readonly byte [] bits_ac_luminance
static readonly byte [] val_ac_luminance
static readonly byte [] bits_ac_chrominance
static readonly byte [] val_ac_chrominance
Detailed Description
JPEG compression routine.
See also
JpegDecompressStruct
Definition at line 12 of file JpegCompressStruct.cs.
Constructor & Destructor Documentation
JpegCompressStruct() [1/2]
BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCompressStruct () inline
Initializes a new instance of the JpegCompressStruct class.
Definition at line 269 of file JpegCompressStruct.cs.
         {
             Initialize();
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize().
JpegCompressStruct() [2/2]
BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCompressStruct (JpegErrorMessage errorManager) inline
Initializes a new instance of the JpegCompressStruct class.
Parameters
errorManager The error manager.
Definition at line 278 of file JpegCompressStruct.cs.
             : base(errorManager)
         {
             Initialize();
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize().
Member Function Documentation
AddHuffTable()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.AddHuffTable (ref JHuffmanTable htblptr, byte [] bits, byte [] val) inline private
Define a Huffman table
Definition at line 2316 of file JpegCompressStruct.cs.
         {
             if (htblptr is null)
             {
                 htblptr = new JHuffmanTable();
             }
             /* Copy the number-of-symbols-of-each-code-length counts */
             Buffer.BlockCopy(bits, 0, htblptr.Bits, 0, htblptr.Bits.Length);
             /* Validate the counts.  We do this here mainly so we can copy the right
             * number of symbols from the val[] array, without risking marching off
             * the end of memory. huff_entropy_encoder will do a more thorough test later.
             */
             var nsymbols = 0;
             for (var len = 1; len <= 16; len++)
             {
                 nsymbols += bits[len];
             }
             if (nsymbols < 1 || nsymbols > 256)
             {
                 ErrExit(JMessageCode.JERR_BAD_HUFF_TABLE);
             }
             Buffer.BlockCopy(val, 0, htblptr.Huffval, 0, nsymbols);
             /* Initialize sent_table false so table will be written to JPEG file. */
             htblptr.SentTable = false;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit().
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
AllocJpegSamples()
static byte [][] BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples (int samplesPerRow, int numberOfRows) inline static inherited
Creates 2-D sample array.
Parameters
samplesPerRow The number of samples per row.
numberOfRows The number of rows.
Returns
The array of samples.
Definition at line 158 of file JpegCommonStruct.cs.
         {
             var result = new byte[numberOfRows][];
             for (var i = 0; i < numberOfRows; ++i)
             {
                 result[i] = new byte[samplesPerRow];
             }
             return result;
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColorIndex(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColormap(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateSamplesArray(), BitMiracle.LibJpeg.Jpeg.Decompress(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.JpegCMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), and BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler().
CreateBlocksArray()
static JVirtArray<JBlock> BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateBlocksArray (int blocksPerRow, int numberOfRows) inline static inherited
Creates the array of blocks.
Parameters
blocksPerRow The number of blocks in row.
numberOfRows The number of rows.
Returns
The array of blocks.
See also
JBlock
Definition at line 147 of file JpegCommonStruct.cs.
         {
             return new JVirtArray<JBlock>(blocksPerRow, numberOfRows, AllocJpegBlocks);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegBlocks().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.JpegDCoefController(), and BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.MyCCoefController().
CreateSamplesArray()
static JVirtArray<byte> BitMiracle.LibJpeg.Classic.JpegCommonStruct.CreateSamplesArray (int samplesPerRow, int numberOfRows) inline static inherited
Creates the array of samples.
Parameters
samplesPerRow The number of samples in row.
numberOfRows The number of rows.
Returns
The array of samples.
Definition at line 135 of file JpegCommonStruct.cs.
         {
             return new JVirtArray<byte>(samplesPerRow, numberOfRows, AllocJpegSamples);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.AllocJpegSamples().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.JpegDPostController().
ErrExit() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (JMessageCode code) inline inherited
Used for fatal errors (print message and exit).
Parameters
code The message code.
Definition at line 238 of file JpegCommonStruct.cs.
         {
             ErrExit((int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.JVirtArray< BitMiracle.LibJpeg.Classic.JBlock >.Access(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.AddHuffTable(), BitMiracle.LibJpeg.Classic.Internal.ArithEntropyDecoder.ArithEntropyDecoder(), BitMiracle.LibJpeg.Classic.Internal.ArithEntropyEncoder.ArithEntropyEncoder(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.ColorQuantize(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.ColorQuantize(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.ConsumeMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegDCoefController.DecompressData(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitBitsS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitEOBRun(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.MySourceManager.FillInputBuffer(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.FirstMarker(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetInterestingAppN(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetLSE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.Inverse(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMainController(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCalcOutputDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegConsumeInput(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultColorspace(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.JpegDMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct9x9(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegGenOptimalTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegHasMultipleScans(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.JpegIDct9x9(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegInputComplete(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.JpegMakeDDerivedTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadCoefficients(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSaveMarkers(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.JpegSetMarkerProcessor(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartDecompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegStartOutput(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.LatchQuantTables(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.MasterSelection(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.My1PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.My2PassCQuantizer(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.MyUpSampler(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.NewColorMap(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegInputController.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.PostProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegDecompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.ProcessData(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.SelectNColors(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.start_pass(), BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDPostController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegDMainController.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegInverseDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.StartPass(), BitMiracle.LibJpeg.Classic.Internal.MyUpSampler.UpSampleComponent(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader().
ErrExit() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (JMessageCode code, params object [] args) inline inherited
Used for fatal errors (print message and exit).
Parameters
code The message code.
args The parameters of message.
Definition at line 248 of file JpegCommonStruct.cs.
         {
             ErrExit((int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit().
ErrExit() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit (int code, params object [] args) inline inherited
Used for fatal errors (print message and exit).
Parameters
code The message code.
args The parameters of message.
Definition at line 258 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.ErrorExit();
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.ErrorExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
FillAScan()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillAScan (ref int scanIndex, int ci, int Ss, int Se, int Ah, int Al) inline private
Support routine: generate one scan for specified component
Definition at line 2350 of file JpegCompressStruct.cs.
         {
             scriptSpace[scanIndex].comps_in_scan = 1;
             scriptSpace[scanIndex].component_index[0] = ci;
             scriptSpace[scanIndex].Ss = Ss;
             scriptSpace[scanIndex].Se = Se;
             scriptSpace[scanIndex].Ah = Ah;
             scriptSpace[scanIndex].Al = Al;
             scanIndex++;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Ah, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Al, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.component_index, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.scriptSpace, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Se, and BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Ss.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression().
FillDcScans()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillDcScans (ref int scanIndex, int ncomps, int Ah, int Al) inline private
Support routine: generate interleaved DC scan if possible, else N scans
Definition at line 2364 of file JpegCompressStruct.cs.
         {
             if (ncomps <= JpegConstants.MAX_COMPS_IN_SCAN)
             {
                 /* Single interleaved DC scan */
                 scriptSpace[scanIndex].comps_in_scan = ncomps;
                 for (var ci = 0; ci < ncomps; ci++)
                 {
                     scriptSpace[scanIndex].component_index[ci] = ci;
                 }
                 scriptSpace[scanIndex].Ss = 0;
                 scriptSpace[scanIndex].Se = 0;
                 scriptSpace[scanIndex].Ah = Ah;
                 scriptSpace[scanIndex].Al = Al;
                 scanIndex++;
             }
             else
             {
                 /* Noninterleaved DC scan for each component */
                 FillScans(ref scanIndex, ncomps, 0, 0, Ah, Al);
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Ah, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Al, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.component_index, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillScans(), BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPS_IN_SCAN, BitMiracle.LibJpeg.Classic.JpegCompressStruct.scriptSpace, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Se, and BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Ss.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression().
FillScans()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillScans (ref int scanIndex, int ncomps, int Ss, int Se, int Ah, int Al) inline private
Support routine: generate one scan for each component
Definition at line 2391 of file JpegCompressStruct.cs.
         {
             for (var ci = 0; ci < ncomps; ci++)
             {
                 scriptSpace[scanIndex].comps_in_scan = 1;
                 scriptSpace[scanIndex].component_index[0] = ci;
                 scriptSpace[scanIndex].Ss = Ss;
                 scriptSpace[scanIndex].Se = Se;
                 scriptSpace[scanIndex].Ah = Ah;
                 scriptSpace[scanIndex].Al = Al;
                 scanIndex++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Ah, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Al, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.component_index, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.comps_in_scan, BitMiracle.LibJpeg.Classic.JpegCompressStruct.scriptSpace, BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Se, and BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Ss.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillDcScans(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression().
Initialize()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize () inline private
Initialization of a JPEG compression object
Definition at line 1761 of file JpegCompressStruct.cs.
         {
             /* Zero out pointers to permanent structures. */
             prog = null;
             m_dest = null;
             compInfo = null;
             for (var i = 0; i < JpegConstants.NUM_QUANT_TBLS; i++)
             {
                 m_quant_tbl_ptrs[i] = null;
                 QScaleFactor[i] = 100;
             }
             for (var i = 0; i < JpegConstants.NUM_HUFF_TBLS; i++)
             {
                 m_dc_huff_tbl_ptrs[i] = null;
                 m_ac_huff_tbl_ptrs[i] = null;
             }
             /* Must do it here for emit_dqt in case jpeg_write_tables is used */
             BlockSize = JpegConstants.DCTSIZE;
             natural_order = JpegUtils.jpeg_natural_order;
             lim_Se = JpegConstants.DCTSIZE2 - 1;
             scriptSpace = null;
             /* OK, I'm ready */
             globalState = JpegState.CSTATE_START;
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegCompressStruct.compInfo, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order, BitMiracle.LibJpeg.Classic.JpegCompressStruct.lim_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS, BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegCompressStruct.QScaleFactor, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.scriptSpace.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCompressStruct().
InitialSetup()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup (bool transcode_only) inline private
Do computations that are needed before master selection phase
Definition at line 1937 of file JpegCompressStruct.cs.
         {
             if (transcode_only)
             {
                 JpegCalcTransDimensions();
             }
             else
             {
                 JpegCalcJpegDimensions();
             }
             /* Sanity check on block_size */
             if (BlockSize < 1 || BlockSize > 16)
             {
                 ErrExit(JMessageCode.JERR_BAD_DCTSIZE, BlockSize, BlockSize);
             }
             /* Derive natural_order from block_size */
             natural_order = BlockSize switch
             {
                 2 => JpegUtils.jpeg_natural_order2,
                 3 => JpegUtils.jpeg_natural_order3,
                 4 => JpegUtils.jpeg_natural_order4,
                 5 => JpegUtils.jpeg_natural_order5,
                 6 => JpegUtils.jpeg_natural_order6,
                 7 => JpegUtils.jpeg_natural_order7,
                 _ => JpegUtils.jpeg_natural_order,
             };
             /* Derive lim_Se from block_size */
             lim_Se = BlockSize < JpegConstants.DCTSIZE
                 ? (BlockSize * BlockSize) - 1
                 : JpegConstants.DCTSIZE2 - 1;
             /* Sanity check on image dimensions */
             if (jpeg_height <= 0 || jpeg_width <= 0 || m_num_components <= 0)
             {
                 ErrExit(JMessageCode.JERR_EMPTY_IMAGE);
             }
             /* Make sure image isn't bigger than I can handle */
             if (jpeg_height > JpegConstants.JPEG_MAX_DIMENSION
                 || jpeg_width > JpegConstants.JPEG_MAX_DIMENSION)
             {
                 ErrExit(JMessageCode.JERR_IMAGE_TOO_BIG, (uint)JpegConstants.JPEG_MAX_DIMENSION);
             }
             /* Only 8 to 12 bits data precision are supported for DCT based JPEG */
             if (m_data_precision < 8 || m_data_precision > 12)
             {
                 ErrExit(JMessageCode.JERR_BAD_PRECISION, m_data_precision);
             }
             /* Check that number of components won't exceed internal array sizes */
             if (m_num_components > JpegConstants.MAX_COMPONENTS)
             {
                 ErrExit(JMessageCode.JERR_COMPONENT_COUNT, m_num_components, JpegConstants.MAX_COMPONENTS);
             }
             /* Compute maximum sampling factors; check factor validity */
             m_max_h_samp_factor = 1;
             m_max_v_samp_factor = 1;
             for (var ci = 0; ci < m_num_components; ci++)
             {
                 if (compInfo[ci].H_samp_factor <= 0
                     || compInfo[ci].H_samp_factor > JpegConstants.MAX_SAMP_FACTOR
                     || compInfo[ci].V_samp_factor <= 0
                     || compInfo[ci].V_samp_factor > JpegConstants.MAX_SAMP_FACTOR)
                 {
                     ErrExit(JMessageCode.JERR_BAD_SAMPLING);
                 }
                 m_max_h_samp_factor = Math.Max(m_max_h_samp_factor, compInfo[ci].H_samp_factor);
                 m_max_v_samp_factor = Math.Max(m_max_v_samp_factor, compInfo[ci].V_samp_factor);
             }
             /* Compute dimensions of components */
             for (var ci = 0; ci < m_num_components; ci++)
             {
                 var compptr = compInfo[ci];
                 /* Fill in the correct component_index value; don't rely on application */
                 compptr.Component_index = ci;
                 /* In selecting the actual DCT scaling for each component, we try to
                  * scale down the chroma components via DCT scaling rather than downsampling.
                  * This saves time if the downsampler gets to use 1:1 scaling.
                  * Note this code adapts subsampling ratios which are powers of 2.
                  */
                 var ssize = 1;
                 var upSampleSize = DoFancyDownsampling
                     ? JpegConstants.DCTSIZE
                     : JpegConstants.DCTSIZE / 2;
                 while (min_DCT_h_scaled_size * ssize <= upSampleSize
                    && (m_max_h_samp_factor % (compptr.H_samp_factor * ssize * 2)) == 0)
                 {
                     ssize *= 2;
                 }
                 compptr.DCT_h_scaled_size = min_DCT_h_scaled_size * ssize;
                 ssize = 1;
                 while (min_DCT_v_scaled_size * ssize <= upSampleSize
                    && (m_max_v_samp_factor % (compptr.V_samp_factor * ssize * 2)) == 0)
                 {
                     ssize *= 2;
                 }
                 compptr.DCT_v_scaled_size = min_DCT_v_scaled_size * ssize;
                 /* We don't support DCT ratios larger than 2. */
                 if (compptr.DCT_h_scaled_size > compptr.DCT_v_scaled_size * 2)
                 {
                     compptr.DCT_h_scaled_size = compptr.DCT_v_scaled_size * 2;
                 }
                 else if (compptr.DCT_v_scaled_size > compptr.DCT_h_scaled_size * 2)
                 {
                     compptr.DCT_v_scaled_size = compptr.DCT_h_scaled_size * 2;
                 }
                 /* Size in DCT blocks */
                 compptr.Width_in_blocks = (int)JpegUtils.jdiv_round_up(
                     (long)jpeg_width * compptr.H_samp_factor, (long)m_max_h_samp_factor * BlockSize);
                 compptr.height_in_blocks = (int)JpegUtils.jdiv_round_up(
                     (long)jpeg_height * compptr.V_samp_factor, (long)m_max_v_samp_factor * BlockSize);
                 /* Size in samples */
                 compptr.downsampled_width = (int)JpegUtils.jdiv_round_up(
                     (long)jpeg_width * compptr.H_samp_factor * compptr.DCT_h_scaled_size,
                     (long)m_max_h_samp_factor * BlockSize);
                 compptr.downsampled_height = (int)JpegUtils.jdiv_round_up(
                     (long)jpeg_height * compptr.V_samp_factor * compptr.DCT_v_scaled_size,
                     (long)m_max_v_samp_factor * BlockSize);
                 /* Don't need quantization scale after DCT,
                  * until color conversion says otherwise.
                  */
                 compptr.component_needed = false;
             }
             /* Compute number of fully interleaved MCU rows (number of times that
              * main controller will call coefficient controller).
              */
             m_total_iMCU_rows = (int)JpegUtils.jdiv_round_up(
                 jpeg_height, (long)m_max_v_samp_factor * BlockSize);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegCompressStruct.compInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_index, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.JpegCompressStruct.DoFancyDownsampling, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jdiv_round_up(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_height, BitMiracle.LibJpeg.Classic.JpegConstants.JPEG_MAX_DIMENSION, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order2, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order3, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order4, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order5, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order6, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jpeg_natural_order7, BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_width, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.lim_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_data_precision, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_max_h_samp_factor, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_max_v_samp_factor, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_total_iMCU_rows, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPONENTS, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_SAMP_FACTOR, BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order, and BitMiracle.LibJpeg.Classic.JpegComponentInfo.V_samp_factor.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl().
JInitCMainController()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMainController (bool need_full_buffer) inline private
Initialize main buffer controller.
Definition at line 1884 of file JpegCompressStruct.cs.
         {
             /* We don't need to create a buffer in raw-data mode. */
             if (m_raw_data_in)
             {
                 return;
             }
             /* Create the buffer.  It holds downsampled data, so each component
             * may be of a different size.
             */
             if (need_full_buffer)
             {
                 ErrExit(JMessageCode.JERR_BAD_BUFFER_MODE);
             }
             else
             {
                 m_main = new JpegCMainController(this);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_main, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_raw_data_in.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster().
JInitCMasterControl()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl (bool transcode_only) inline private
Initialize master compression control.
Definition at line 1845 of file JpegCompressStruct.cs.
         {
             /* Validate parameters, determine derived values */
             InitialSetup(transcode_only);
             if (m_scan_info is object)
             {
                 ValidateScript();
                 if (BlockSize < JpegConstants.DCTSIZE)
                 {
                     ReduceScript();
                 }
             }
             else
             {
                 m_progressive_mode = false;
                 m_num_scans = 1;
             }
             if (optimizeEntropyCoding)
             {
                 arith_code = false; /* disable arithmetic coding */
             }
             else if (!arith_code
                 && (m_progressive_mode
                     || (BlockSize > 1
                         && BlockSize < JpegConstants.DCTSIZE)))
             {
                 /* TEMPORARY HACK ??? */
                 /* assume default tables no good for progressive or reduced AC mode */
                 optimizeEntropyCoding = true; /* force Huffman optimization */
             }
             m_master = new JpegCompMaster(this, transcode_only);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_code, BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_scan_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding, BitMiracle.LibJpeg.Classic.JpegCompressStruct.ReduceScript(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript().
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection().
JInitCompressMaster()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster () inline private
Master selection of compression modules. This is done once at the start of processing an image. We determine which modules will be used and give them appropriate initialization calls. This routine is in charge of selecting the modules to be executed and making an initialization call to each one.
Definition at line 1798 of file JpegCompressStruct.cs.
         {
             /* Sanity check on image dimensions */
             if (m_image_height <= 0 || m_image_width <= 0 || m_input_components <= 0)
             {
                 ErrExit(JMessageCode.JERR_EMPTY_IMAGE);
             }
             /* Initialize master control (includes parameter checking/processing) */
             JInitCMasterControl(false /* full compression */);
             /* Preprocessing */
             if (!m_raw_data_in)
             {
                 m_cconvert = new JpegColorConverter(this);
                 m_downsample = new JpegDownsampler(this);
                 m_prep = new JpegCPrepController(this);
             }
             /* Forward DCT */
             m_fdct = new JpegForwardDct(this);
             /* Entropy encoding: either Huffman or arithmetic coding. */
             if (arith_code)
             {
                 m_entropy = new ArithEntropyEncoder(this);
             }
             else
             {
                 m_entropy = new HuffmanEntropyEncoder(this);
             }
             /* Need a full-image coefficient buffer in any multi-pass mode. */
             m_coef = new MyCCoefController(this, m_num_scans > 1 || optimizeEntropyCoding);
             JInitCMainController(false /* never need full buffer here */);
             m_marker = new JpegMarkerWriter(this);
             /* Write the datastream header (SOI) immediately.
             * Frame and scan headers are postponed till later.
             * This lets application insert special markers after the SOI.
             */
             m_marker.WriteFileHeader();
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_code, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMainController(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cconvert, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_downsample, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_fdct, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_width, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_input_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_prep, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_raw_data_in, BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding, and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader().
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression().
JpegAbort()
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort () inline inherited
Abort processing of a JPEG compression or decompression operation, but don't destroy the object itself.
Closing a data source or destination, if necessary, is the application's responsibility.
Definition at line 198 of file JpegCommonStruct.cs.
         {
             /* Reset overall state for possible reuse of object */
             if (IsDecompressor)
             {
                 globalState = JpegState.DSTATE_START;
                 /* Try to keep application from accessing now-deleted marker list.
                  * A bit kludgy to do it here, but this is the most central place.
                  */
                 if (this is JpegDecompressStruct s)
                 {
                     s.m_marker_list = null;
                 }
             }
             else
             {
                 globalState = JpegState.CSTATE_START;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, and BitMiracle.LibJpeg.Classic.JpegCommonStruct.IsDecompressor.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAbortCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegAbortDecompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegFinishDecompress(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadHeader().
JpegAbortCompress()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAbortCompress () inline
Abort processing of a JPEG compression operation.
Definition at line 658 of file JpegCompressStruct.cs.
         {
             // use common routine
             JpegAbort();
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort().
JpegAddQuantTable()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable (int which_tbl, int [] basic_table, int scale_factor, bool force_baseline) inline
Allows an arbitrary quantization table to be created.
Parameters
which_tbl Indicates which table slot to fill.
basic_table An array of 64 unsigned integers given in normal array order. These values are multiplied by scale_factor/100 and then clamped to the range 1..65535 (or to 1..255 if force_baseline is true).
The basic table should be given in JPEG zigzag order.
scale_factor Multiplier for values in basic_table.
force_baseline Defines range of values in basic_table. If true - 1..255, otherwise - 1..65535.
Compression parameter selection
Definition at line 1221 of file JpegCompressStruct.cs.
         {
             /* Safety check to ensure start_compress not called yet. */
             if (globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             if (which_tbl < 0 || which_tbl >= JpegConstants.NUM_QUANT_TBLS)
             {
                 ErrExit(JMessageCode.JERR_DQT_INDEX, which_tbl);
             }
             if (basic_table is null)
             {
                 throw new ArgumentNullException(nameof(basic_table));
             }
             if (m_quant_tbl_ptrs[which_tbl] is null)
             {
                 m_quant_tbl_ptrs[which_tbl] = new JQuantTable();
             }
             for (var i = 0; i < JpegConstants.DCTSIZE2; i++)
             {
                 var temp = ((basic_table[i] * scale_factor) + 50) / 100;
                 /* limit the values to the valid range */
                 if (temp <= 0)
                 {
                     temp = 1;
                 }
                 /* max quantizer needed for 12 bits */
                 if (temp > 32767)
                 {
                     temp = 32767;
                 }
                 /* limit to baseline range if requested */
                 if (force_baseline && temp > 255)
                 {
                     temp = 255;
                 }
                 m_quant_tbl_ptrs[which_tbl].quantBal[i] = (short)temp;
             }
             /* Initialize sent_table false so table will be written to JPEG file. */
             m_quant_tbl_ptrs[which_tbl].SentTable = false;
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS, BitMiracle.LibJpeg.Classic.JQuantTable.quantBal, and BitMiracle.LibJpeg.Classic.JQuantTable.SentTable.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultQTables(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetLinearQuality().
JpegCalcJpegDimensions()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions () inline private
Definition at line 1604 of file JpegCompressStruct.cs.
         {
             /* Sanity check on input image dimensions to prevent overflow in
              * following calculation.
              * We do check jpeg_width and jpeg_height in initial_setup below,
              * but image_width and image_height can come from arbitrary data,
              * and we need some space for multiplication by block_size.
              */
             if (((long)m_image_width >> 24) != 0 || ((long)m_image_height >> 24) != 0)
             {
                 ErrExit(JMessageCode.JERR_IMAGE_TOO_BIG, (uint)JpegConstants.JPEG_MAX_DIMENSION);
             }
             /* Compute actual JPEG image dimensions and DCT scaling choices. */
             if (ScaleNum >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/1 scaling */
                 jpeg_width = m_image_width * BlockSize;
                 jpeg_height = m_image_height * BlockSize;
                 min_DCT_h_scaled_size = 1;
                 min_DCT_v_scaled_size = 1;
             }
             else if (ScaleNum * 2 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/2 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 2L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 2L);
                 min_DCT_h_scaled_size = 2;
                 min_DCT_v_scaled_size = 2;
             }
             else if (ScaleNum * 3 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/3 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 3L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 3L);
                 min_DCT_h_scaled_size = 3;
                 min_DCT_v_scaled_size = 3;
             }
             else if (ScaleNum * 4 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/4 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 4L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 4L);
                 min_DCT_h_scaled_size = 4;
                 min_DCT_v_scaled_size = 4;
             }
             else if (ScaleNum * 5 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/5 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 5L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 5L);
                 min_DCT_h_scaled_size = 5;
                 min_DCT_v_scaled_size = 5;
             }
             else if (ScaleNum * 6 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/6 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 6L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 6L);
                 min_DCT_h_scaled_size = 6;
                 min_DCT_v_scaled_size = 6;
             }
             else if (ScaleNum * 7 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/7 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 7L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 7L);
                 min_DCT_h_scaled_size = 7;
                 min_DCT_v_scaled_size = 7;
             }
             else if (ScaleNum * 8 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/8 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 8L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 8L);
                 min_DCT_h_scaled_size = 8;
                 min_DCT_v_scaled_size = 8;
             }
             else if (ScaleNum * 9 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/9 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 9L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 9L);
                 min_DCT_h_scaled_size = 9;
                 min_DCT_v_scaled_size = 9;
             }
             else if (ScaleNum * 10 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/10 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 10L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 10L);
                 min_DCT_h_scaled_size = 10;
                 min_DCT_v_scaled_size = 10;
             }
             else if (ScaleNum * 11 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/11 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 11L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 11L);
                 min_DCT_h_scaled_size = 11;
                 min_DCT_v_scaled_size = 11;
             }
             else if (ScaleNum * 12 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/12 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 12L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 12L);
                 min_DCT_h_scaled_size = 12;
                 min_DCT_v_scaled_size = 12;
             }
             else if (ScaleNum * 13 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/13 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 13L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 13L);
                 min_DCT_h_scaled_size = 13;
                 min_DCT_v_scaled_size = 13;
             }
             else if (ScaleNum * 14 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/14 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 14L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 14L);
                 min_DCT_h_scaled_size = 14;
                 min_DCT_v_scaled_size = 14;
             }
             else if (ScaleNum * 15 >= ScaleDenom * BlockSize)
             {
                 /* Provide block_size/15 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 15L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 15L);
                 min_DCT_h_scaled_size = 15;
                 min_DCT_v_scaled_size = 15;
             }
             else
             {
                 /* Provide block_size/16 scaling */
                 jpeg_width = (int)JpegUtils.jdiv_round_up((long)m_image_width * BlockSize, 16L);
                 jpeg_height = (int)JpegUtils.jdiv_round_up((long)m_image_height * BlockSize, 16L);
                 min_DCT_h_scaled_size = 16;
                 min_DCT_v_scaled_size = 16;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jdiv_round_up(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_height, BitMiracle.LibJpeg.Classic.JpegConstants.JPEG_MAX_DIMENSION, BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_width, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_width, BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.JpegCompressStruct.ScaleDenom, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.ScaleNum.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
JpegCalcTransDimensions()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions () inline private
Definition at line 1748 of file JpegCompressStruct.cs.
         {
             if (min_DCT_h_scaled_size != min_DCT_v_scaled_size)
             {
                 ErrExit(JMessageCode.JERR_BAD_DCTSIZE, min_DCT_h_scaled_size, min_DCT_v_scaled_size);
             }
             BlockSize = min_DCT_h_scaled_size;
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_h_scaled_size, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_v_scaled_size.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
JpegDefaultColorspace()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultColorspace () inline
Select an appropriate JPEG colorspace based on JpegCompressStruct.In_color_space, and calls JpegCompressStruct.JpegSetColorspace
This is actually a subroutine of JpegSetDefaults. It's broken out in case you want to change just the colorspace-dependent JPEG parameters.
Compression parameter selection
Definition at line 1113 of file JpegCompressStruct.cs.
         {
             switch (m_in_color_space)
             {
                 case JColorSpace.JCS_UNKNOWN:
                 JpegSetColorspace(JColorSpace.JCS_UNKNOWN);
                 break;
                 case JColorSpace.JCS_GRAYSCALE:
                 JpegSetColorspace(JColorSpace.JCS_GRAYSCALE);
                 break;
                 case JColorSpace.JCS_RGB:
                 JpegSetColorspace(JColorSpace.JCS_YCbCr);
                 break;
                 case JColorSpace.JCS_YCbCr:
                 JpegSetColorspace(JColorSpace.JCS_YCbCr);
                 break;
                 case JColorSpace.JCS_CMYK:
                 JpegSetColorspace(JColorSpace.JCS_CMYK); /* By default, no translation */
                 break;
                 case JColorSpace.JCS_YCCK:
                 JpegSetColorspace(JColorSpace.JCS_YCCK);
                 break;
                 case JColorSpace.JCS_BG_RGB:
                 /* No translation for now -- conversion to BG_YCC not yet supportet */
                 JpegSetColorspace(JColorSpace.JCS_BG_RGB);
                 break;
                 case JColorSpace.JCS_BG_YCC:
                 JpegSetColorspace(JColorSpace.JCS_BG_YCC);
                 break;
                 default:
                 ErrExit(JMessageCode.JERR_BAD_IN_COLORSPACE);
                 break;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_in_color_space.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
JpegDefaultQTables()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultQTables (bool force_baseline) inline
Set or change the 'quality' (quantization) setting, using default tables and straight percentage-scaling quality scales. This entry point allows different scalings for luminance and chrominance.
Parameters
force_baseline if set to true then baseline version is forced.
Definition at line 1177 of file JpegCompressStruct.cs.
         {
             /* Set up two quantization tables using the specified scaling */
             JpegAddQuantTable(0, std_luminance_quant_tbl, QScaleFactor[0], force_baseline);
             JpegAddQuantTable(1, std_chrominance_quant_tbl, QScaleFactor[1], force_baseline);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.QScaleFactor, BitMiracle.LibJpeg.Classic.JpegCompressStruct.std_chrominance_quant_tbl, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.std_luminance_quant_tbl.
JpegDestroy()
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegDestroy () inline inherited
Destruction of a JPEG object.
Closing a data source or destination, if necessary, is the application's responsibility.
Definition at line 226 of file JpegCommonStruct.cs.
         {
             // mark it destroyed
             globalState = JpegState.DESTROYED;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState.
JpegFinishCompress()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress () inline
Finishes JPEG compression.
If a multipass operating mode was selected, this may do a great deal of work including most of the actual output.
Definition at line 707 of file JpegCompressStruct.cs.
         {
             int iMCU_row;
             if (globalState == JpegState.CSTATE_SCANNING || globalState == JpegState.CSTATE_RAW_OK)
             {
                 /* Terminate first pass */
                 if (m_next_scanline < m_image_height)
                 {
                     ErrExit(JMessageCode.JERR_TOO_LITTLE_DATA);
                 }
                 m_master.FinishPass();
             }
             else if (globalState != JpegState.CSTATE_WRCOEFS)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Perform any remaining passes */
             while (!m_master.IsLastPass())
             {
                 m_master.PrepareForPass();
                 for (iMCU_row = 0; iMCU_row < m_total_iMCU_rows; iMCU_row++)
                 {
                     if (prog is object)
                     {
                         prog.PassCounter = iMCU_row;
                         prog.PassLimit = m_total_iMCU_rows;
                         prog.Updated();
                     }
                     /* We bypass the main controller and invoke coef controller directly;
                     * all work is being done from the coefficient buffer.
                     */
                     if (!m_coef.CompressData(null))
                     {
                         ErrExit(JMessageCode.JERR_CANT_SUSPEND);
                     }
                 }
                 m_master.FinishPass();
             }
             /* Write EOI, do final cleanup */
             m_marker.WriteFileTrailer();
             m_dest.TermDestination();
             /* We can use jpeg_abort to release memory and reset global_state */
             JpegAbort();
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.IsLastPass(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegAbort(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_total_iMCU_rows, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegDestinationManager.TermDestination(), BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileTrailer().
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
JpegQualityScaling()
static int BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegQualityScaling (int quality) inline static
Converts a value on the IJG-recommended quality scale to a linear scaling percentage.
Parameters
quality The IJG-recommended quality scale. Should be 0 (terrible) to 100 (very good).
Returns
The linear scaling percentage.
Compression parameter selection
Definition at line 1279 of file JpegCompressStruct.cs.
         {
             /* Safety limit on quality factor.  Convert 0 to 1 to avoid zero divide. */
             if (quality <= 0)
             {
                 quality = 1;
             }
             if (quality > 100)
             {
                 quality = 100;
             }
             /* The basic table is used as-is (scaling 100) for a quality of 50.
             * Qualities 50..100 are converted to scaling percentage 200 - 2*Q;
             * note that at Q=100 the scaling is 0, which will cause jpeg_add_quant_table
             * to make all the table entries 1 (hence, minimum quantization loss).
             * Qualities 1..50 are converted to scaling percentage 5000/Q.
             */
             return quality < 50 ? 5000 / quality : 200 - (quality * 2);
         }
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetQuality().
JpegSetColorspace()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace (JColorSpace colorspace) inline
Set the JPEG colorspace (property JpegCompressStruct.Jpeg_color_space, and choose colorspace-dependent parameters appropriately.
Parameters
colorspace The required colorspace.
See Special color spaces
, below, before using this. A large number of parameters, including all per-component parameters, are set by this routine; if you want to twiddle individual parameters you should call jpeg_set_colorspace before rather than after.
Compression parameter selection
Special color spaces
Definition at line 993 of file JpegCompressStruct.cs.
         {
             int ci;
             /* Safety check to ensure start_compress not called yet. */
             if (globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* For all colorspaces, we use Q and Huff tables 0 for luminance components,
             * tables 1 for chrominance components.
             */
             m_jpeg_color_space = colorspace;
             m_write_JFIF_header = false; /* No marker for non-JFIF colorspaces */
             m_write_Adobe_marker = false; /* write no Adobe marker by default */
             switch (colorspace)
             {
                 case JColorSpace.JCS_UNKNOWN:
                 m_num_components = m_input_components;
                 if (m_num_components < 1 || m_num_components > JpegConstants.MAX_COMPONENTS)
                 {
                     ErrExit(JMessageCode.JERR_COMPONENT_COUNT, m_num_components, JpegConstants.MAX_COMPONENTS);
                 }
                 for (ci = 0; ci < m_num_components; ci++)
                 {
                     JpegSetColorspaceSetComp(ci, ci, 1, 1, 0, 0, 0);
                 }
                 break;
                 case JColorSpace.JCS_GRAYSCALE:
                 m_write_JFIF_header = true; /* Write a JFIF marker */
                 m_num_components = 1;
                 /* JFIF specifies component ID 1 */
                 JpegSetColorspaceSetComp(0, 0x01, 1, 1, 0, 0, 0);
                 break;
                 case JColorSpace.JCS_RGB:
                 m_write_Adobe_marker = true; /* write Adobe marker to flag RGB */
                 m_num_components = 3;
                 JpegSetColorspaceSetComp(0, 0x52 /* 'R' */, 1, 1, 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0);
                 JpegSetColorspaceSetComp(1, 0x47 /* 'G' */, 1, 1, 0, 0, 0);
                 JpegSetColorspaceSetComp(2, 0x42 /* 'B' */, 1, 1, 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0);
                 break;
                 case JColorSpace.JCS_YCbCr:
                 m_write_JFIF_header = true; /* Write a JFIF marker */
                 m_num_components = 3;
                 /* JFIF specifies component IDs 1,2,3 */
                 /* We default to 2x2 subsamples of chrominance */
                 JpegSetColorspaceSetComp(0, 0x01, 2, 2, 0, 0, 0);
                 JpegSetColorspaceSetComp(1, 0x02, 1, 1, 1, 1, 1);
                 JpegSetColorspaceSetComp(2, 0x03, 1, 1, 1, 1, 1);
                 break;
                 case JColorSpace.JCS_CMYK:
                 m_write_Adobe_marker = true; /* write Adobe marker to flag CMYK */
                 m_num_components = 4;
                 JpegSetColorspaceSetComp(0, 0x43 /* 'C' */, 1, 1, 0, 0, 0);
                 JpegSetColorspaceSetComp(1, 0x4D /* 'M' */, 1, 1, 0, 0, 0);
                 JpegSetColorspaceSetComp(2, 0x59 /* 'Y' */, 1, 1, 0, 0, 0);
                 JpegSetColorspaceSetComp(3, 0x4B /* 'K' */, 1, 1, 0, 0, 0);
                 break;
                 case JColorSpace.JCS_YCCK:
                 m_write_Adobe_marker = true; /* write Adobe marker to flag YCCK */
                 m_num_components = 4;
                 JpegSetColorspaceSetComp(0, 0x01, 2, 2, 0, 0, 0);
                 JpegSetColorspaceSetComp(1, 0x02, 1, 1, 1, 1, 1);
                 JpegSetColorspaceSetComp(2, 0x03, 1, 1, 1, 1, 1);
                 JpegSetColorspaceSetComp(3, 0x04, 2, 2, 0, 0, 0);
                 break;
                 case JColorSpace.JCS_BG_RGB:
                 m_write_JFIF_header = true; /* Write a JFIF marker */
                 JFIF_major_version = 2;   /* Set JFIF major version = 2 */
                 m_num_components = 3;
                 /* Add offset 0x20 to the normal R/G/B component IDs */
                 JpegSetColorspaceSetComp(0, 0x72 /* 'r' */, 1, 1, 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0);
                 JpegSetColorspaceSetComp(1, 0x67 /* 'g' */, 1, 1, 0, 0, 0);
                 JpegSetColorspaceSetComp(2, 0x62 /* 'b' */, 1, 1, 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0,
                     ColorTransform == JColorTransform.JCT_SUBTRACT_GREEN ? 1 : 0);
                 break;
                 case JColorSpace.JCS_BG_YCC:
                 m_write_JFIF_header = true; /* Write a JFIF marker */
                 JFIF_major_version = 2;   /* Set JFIF major version = 2 */
                 m_num_components = 3;
                 /* Add offset 0x20 to the normal Cb/Cr component IDs */
                 /* We default to 2x2 subsamples of chrominance */
                 JpegSetColorspaceSetComp(0, 0x01, 2, 2, 0, 0, 0);
                 JpegSetColorspaceSetComp(1, 0x22, 1, 1, 1, 1, 1);
                 JpegSetColorspaceSetComp(2, 0x23, 1, 1, 1, 1, 1);
                 break;
                 default:
                 ErrExit(JMessageCode.JERR_BAD_J_COLORSPACE);
                 break;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.ColorTransform, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JFIF_major_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspaceSetComp(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_input_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_jpeg_color_space, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_write_Adobe_marker, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_write_JFIF_header, and BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPONENTS.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultColorspace().
JpegSetColorspaceSetComp()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspaceSetComp (int index, int id, int hsamp, int vsamp, int quant, int dctbl, int actbl) inline private
Definition at line 2405 of file JpegCompressStruct.cs.
         {
             compInfo[index].Component_id = id;
             compInfo[index].H_samp_factor = hsamp;
             compInfo[index].V_samp_factor = vsamp;
             compInfo[index].Quant_tbl_no = quant;
             compInfo[index].Dc_tbl_no = dctbl;
             compInfo[index].Ac_tbl_no = actbl;
         }
References BitMiracle.LibJpeg.Classic.JpegComponentInfo.Ac_tbl_no, BitMiracle.LibJpeg.Classic.JpegCompressStruct.compInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_id, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Dc_tbl_no, BitMiracle.LibJpeg.Classic.JpegComponentInfo.H_samp_factor, BitMiracle.LibJpeg.Classic.JpegComponentInfo.Quant_tbl_no, and BitMiracle.LibJpeg.Classic.JpegComponentInfo.V_samp_factor.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace().
JpegSetDefaults()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults () inline
Jpeg_set_defaultses this instance.
Uses only the input image's color space (property JpegCompressStruct.In_color_space, which must already be set in JpegCompressStruct). Many applications will only need to use this routine and perhaps JpegCompressStruct.JpegSetQuality.
Compression parameter selection
Definition at line 892 of file JpegCompressStruct.cs.
         {
             /* Safety check to ensure start_compress not called yet. */
             if (globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Allocate comp_info array large enough for maximum component count.
             * Array is made permanent in case application wants to compress
             * multiple images at same param settings.
             */
             if (compInfo is null)
             {
                 compInfo = JpegComponentInfo.CreateArrayOfComponents(JpegConstants.MAX_COMPONENTS);
             }
             /* Initialize everything not dependent on the color space */
             ScaleNum = 1;       /* 1:1 scaling */
             ScaleDenom = 1;
             m_data_precision = JpegConstants.BITS_IN_JSAMPLE;
             /* Set up two quantization tables using default quality of 75 */
             JpegSetQuality(75, true);
             /* Set up two Huffman tables */
             StdHuffTables();
             /* Default is no multiple-scan output */
             m_scan_info = null;
             m_num_scans = 0;
             /* Expect normal source image, not raw downsampled data */
             m_raw_data_in = false;
             /* The standard Huffman tables are only valid for 8-bit data precision.
              * If the precision is higher, use arithmetic coding.
              * (Alternatively, using Huffman coding would be possible with forcing
              * optimization on so that usable tables will be computed, or by
              * supplying default tables that are valid for the desired precision.)
              * Otherwise, use Huffman coding by default.
              */
             arith_code = (m_data_precision > 8);
             /* By default, don't do extra passes to optimize entropy coding */
             optimizeEntropyCoding = false;
             /* By default, use the simpler non-cosited sampling alignment */
             CIR601sampling = false;
             /* By default, apply fancy downsampling */
             DoFancyDownsampling = true;
             /* No input smoothing */
             m_input_smoothing = 0;
             /* DCT algorithm preference */
             m_dct_method = JpegConstants.JDCT_DEFAULT;
             /* No restart markers */
             m_restart_interval = 0;
             m_restart_in_rows = 0;
             /* Fill in default JFIF marker parameters.  Note that whether the marker
             * will actually be written is determined by jpeg_set_colorspace.
             *
             * By default, the library emits JFIF version code 1.01.
             * An application that wants to emit JFIF 1.02 extension markers should set
             * JFIF_minor_version to 2.  We could probably get away with just defaulting
             * to 1.02, but there may still be some decoders in use that will complain
             * about that; saying 1.01 should minimize compatibility problems.
             *
             * For wide gamut colorspaces (BG_RGB and BG_YCC), the major version will be
             * overridden by jpeg_set_colorspace and set to 2.
             */
             m_JFIF_major_version = 1; /* Default JFIF version = 1.01 */
             m_JFIF_minor_version = 1;
             m_density_unit = DensityUnit.Unknown;    /* Pixel size is unknown by default */
             m_X_density = 1;       /* Pixel aspect ratio is square by default */
             m_Y_density = 1;
             /* No color transform */
             ColorTransform = JColorTransform.JCT_NONE;
             /* Choose JPEG colorspace based on input space, set defaults accordingly */
             JpegDefaultColorspace();
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_code, BitMiracle.LibJpeg.Classic.JpegConstants.BITS_IN_JSAMPLE, BitMiracle.LibJpeg.Classic.JpegCompressStruct.CIR601sampling, BitMiracle.LibJpeg.Classic.JpegCompressStruct.ColorTransform, BitMiracle.LibJpeg.Classic.JpegCompressStruct.compInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.CreateArrayOfComponents(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.DoFancyDownsampling, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegConstants.JDCT_DEFAULT, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetQuality(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_data_precision, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dct_method, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_density_unit, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_input_smoothing, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_major_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_minor_version, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_raw_data_in, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_in_rows, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_scan_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_X_density, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Y_density, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPONENTS, BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding, BitMiracle.LibJpeg.Classic.JpegCompressStruct.ScaleDenom, BitMiracle.LibJpeg.Classic.JpegCompressStruct.ScaleNum, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
Referenced by BitMiracle.LibJpeg.Jpeg.Compress(), and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters().
JpegSetLinearQuality()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetLinearQuality (int scale_factor, bool force_baseline) inline
Same as JpegSetQuality except that the generated tables are the sample tables given in the JPEG specification section K.1, multiplied by the specified scale factor.
Parameters
scale_factor The scale_factor.
force_baseline If true, then the quantization table entries are constrained to the range 1..255 for full JPEG baseline compatibility. In the current implementation, this only makes a difference for quality settings below 25, and it effectively prevents very small/low quality files from being generated. The IJG decoder is capable of reading the non-baseline files generated at low quality settings when force_baseline is false, but other decoders may not be.
Note that larger scale factors give lower quality. This entry point is useful for conforming to the Adobe PostScript DCT conventions, but we do not recommend linear scaling as a user-visible quality scale otherwise.
Compression parameter selection
Definition at line 1201 of file JpegCompressStruct.cs.
         {
             /* Set up two quantization tables using the specified scaling */
             JpegAddQuantTable(0, std_luminance_quant_tbl, scale_factor, force_baseline);
             JpegAddQuantTable(1, std_chrominance_quant_tbl, scale_factor, force_baseline);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.std_chrominance_quant_tbl, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.std_luminance_quant_tbl.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetQuality().
JpegSetQuality()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetQuality (int quality, bool force_baseline) inline
Constructs JPEG quantization tables appropriate for the indicated quality setting.
Parameters
quality The quality value is expressed on the 0..100 scale recommended by IJG.
force_baseline If true, then the quantization table entries are constrained to the range 1..255 for full JPEG baseline compatibility. In the current implementation, this only makes a difference for quality settings below 25, and it effectively prevents very small/low quality files from being generated. The IJG decoder is capable of reading the non-baseline files generated at low quality settings when force_baseline is false, but other decoders may not be.
Note that the exact mapping from quality values to tables may change in future IJG releases as more is learned about DCT quantization.
Compression parameter selection
Definition at line 1162 of file JpegCompressStruct.cs.
         {
             /* Convert user 0-100 rating to percentage scaling */
             quality = JpegQualityScaling(quality);
             /* Set up standard quality tables */
             JpegSetLinearQuality(quality, force_baseline);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegQualityScaling(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetLinearQuality().
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
JpegSimpleProgression()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression () inline
Generates a default scan script for writing a progressive-JPEG file.
This is the recommended method of creating a progressive file, unless you want to make a custom scan sequence. You must ensure that the JPEG color space is set correctly before calling this routine.
Compression parameter selection
Definition at line 1308 of file JpegCompressStruct.cs.
         {
             /* Safety check to ensure start_compress not called yet. */
             if (globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Figure space needed for script.  Calculation must match code below! */
             int nscans;
             if (m_num_components == 3
                 && (m_jpeg_color_space == JColorSpace.JCS_YCbCr
                     || m_jpeg_color_space == JColorSpace.JCS_BG_YCC))
             {
                 /* Custom script for YCC color images. */
                 nscans = 10;
             }
             else
             {
                 /* All-purpose script for other color spaces. */
                 if (m_num_components > JpegConstants.MAX_COMPS_IN_SCAN)
                 {
                     /* 2 DC + 4 AC scans per component */
                     nscans = 6 * m_num_components;
                 }
                 else
                 {
                     /* 2 DC scans; 4 AC scans per component */
                     nscans = 2 + (4 * m_num_components);
                 }
             }
             /* Allocate space for script.
             * We need to put it in the permanent pool in case the application performs
             * multiple compressions without changing the settings.  To avoid a memory
             * leak if jpeg_simple_progression is called repeatedly for the same JPEG
             * object, we try to re-use previously allocated space, and we allocate
             * enough space to handle YCC even if initially asked for grayscale.
             */
             if (scriptSpace is null || m_script_space_size < nscans)
             {
                 m_script_space_size = Math.Max(nscans, 10);
                 scriptSpace = new JpegScanInfo[m_script_space_size];
                 for (var i = 0; i < m_script_space_size; i++)
                 {
                     scriptSpace[i] = new JpegScanInfo();
                 }
             }
             m_scan_info = scriptSpace;
             m_num_scans = nscans;
             var scanIndex = 0;
             if (m_num_components == 3
                 && (m_jpeg_color_space == JColorSpace.JCS_YCbCr
                     || m_jpeg_color_space == JColorSpace.JCS_BG_YCC))
             {
                 /* Custom script for YCC color images. */
                 /* Initial DC scan */
                 FillDcScans(ref scanIndex, m_num_components, 0, 1);
                 /* Initial AC scan: get some luma data out in a hurry */
                 FillAScan(ref scanIndex, 0, 1, 5, 0, 2);
                 /* Chroma data is too small to be worth expending many scans on */
                 FillAScan(ref scanIndex, 2, 1, 63, 0, 1);
                 FillAScan(ref scanIndex, 1, 1, 63, 0, 1);
                 /* Complete spectral selection for luma AC */
                 FillAScan(ref scanIndex, 0, 6, 63, 0, 2);
                 /* Refine next bit of luma AC */
                 FillAScan(ref scanIndex, 0, 1, 63, 2, 1);
                 /* Finish DC successive approximation */
                 FillDcScans(ref scanIndex, m_num_components, 1, 0);
                 /* Finish AC successive approximation */
                 FillAScan(ref scanIndex, 2, 1, 63, 1, 0);
                 FillAScan(ref scanIndex, 1, 1, 63, 1, 0);
                 /* Luma bottom bit comes last since it's usually largest scan */
                 FillAScan(ref scanIndex, 0, 1, 63, 1, 0);
             }
             else
             {
                 /* All-purpose script for other color spaces. */
                 /* Successive approximation first pass */
                 FillDcScans(ref scanIndex, m_num_components, 0, 1);
                 FillScans(ref scanIndex, m_num_components, 1, 5, 0, 2);
                 FillScans(ref scanIndex, m_num_components, 6, 63, 0, 2);
                 /* Successive approximation second pass */
                 FillScans(ref scanIndex, m_num_components, 1, 63, 2, 1);
                 /* Successive approximation final pass */
                 FillDcScans(ref scanIndex, m_num_components, 1, 0);
                 FillScans(ref scanIndex, m_num_components, 1, 63, 1, 0);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillAScan(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillDcScans(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillScans(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_jpeg_color_space, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_scan_info, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_script_space_size, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPS_IN_SCAN, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.scriptSpace.
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
JpegStartCompression()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression (bool write_all_tables) inline
Starts JPEG compression.
Parameters
write_all_tables Write or not write all quantization and Huffman tables.
Before calling this, all parameters and a data destination must be set up.
See also
JpegCompressStruct.JpegSuppressTables, JpegCompressStruct.JpegWriteTables
Compression details
Definition at line 1419 of file JpegCompressStruct.cs.
         {
             if (globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             if (write_all_tables)
             {
                 JpegSuppressTables(false); /* mark all tables to be written */
             }
             /* (Re)initialize error mgr and destination modules */
             jpgError.ResetErrorMessage();
             m_dest.InitDestination();
             /* Perform master selection of active modules */
             JInitCompressMaster();
             /* Set up for the first pass */
             m_master.PrepareForPass();
             /* Ready for application to drive first pass through jpeg_write_scanlines
             * or jpeg_write_raw_data.
             */
             m_next_scanline = 0;
             globalState = (m_raw_data_in ? JpegState.CSTATE_RAW_OK : JpegState.CSTATE_SCANNING);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitDestination(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSuppressTables(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_raw_data_in, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForPass(), and BitMiracle.LibJpeg.Classic.JpegErrorMessage.ResetErrorMessage().
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
JpegStdioDest()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStdioDest (Stream outfile) inline
Sets output stream.
Parameters
outfile The output stream.
The caller must have already opened the stream, and is responsible for closing it after finishing compression.
Compression details
Definition at line 879 of file JpegCompressStruct.cs.
         {
             m_dest = new MyDestinationManager(this, outfile);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest.
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
JpegSuppressTables()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSuppressTables (bool suppress) inline
Forcibly suppress or un-suppress all quantization and Huffman tables.
Marks all currently defined tables as already written (if suppress) or not written (if !suppress). This will control whether they get emitted by a subsequent JpegCompressStruct.JpegStartCompression call.
This routine is exported for use by applications that want to produce abbreviated JPEG datastreams.
Parameters
suppress if set to true then suppress tables; otherwise unsuppress.
Definition at line 678 of file JpegCompressStruct.cs.
         {
             for (var i = 0; i < JpegConstants.NUM_QUANT_TBLS; i++)
             {
                 if (m_quant_tbl_ptrs[i] is object)
                 {
                     m_quant_tbl_ptrs[i].SentTable = suppress;
                 }
             }
             for (var i = 0; i < JpegConstants.NUM_HUFF_TBLS; i++)
             {
                 if (m_dc_huff_tbl_ptrs[i] is object)
                 {
                     m_dc_huff_tbl_ptrs[i].SentTable = suppress;
                 }
                 if (m_ac_huff_tbl_ptrs[i] is object)
                 {
                     m_ac_huff_tbl_ptrs[i].SentTable = suppress;
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_HUFF_TBLS, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS, BitMiracle.LibJpeg.Classic.JQuantTable.SentTable, and BitMiracle.LibJpeg.Classic.JHuffmanTable.SentTable.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients().
JpegWriteCoefficients()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients (JVirtArray< JBlock > [] coef_arrays) inline
Compression initialization for writing raw-coefficient data. Useful for lossless transcoding.
Parameters
coef_arrays The virtual arrays need not be filled or even realized at the time jpeg_write_coefficients is called; indeed, the virtual arrays typically will be realized during this routine and filled afterwards.
Before calling this, all parameters and a data destination must be set up. Call JpegFinishCompress to actually write the data.
Definition at line 1574 of file JpegCompressStruct.cs.
         {
             if (globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* Mark all tables to be written */
             JpegSuppressTables(false);
             /* (Re)initialize error mgr and destination modules */
             jpgError.ResetErrorMessage();
             m_dest.InitDestination();
             /* Perform master selection of active modules */
             TransencodeMasterSelection(coef_arrays);
             /* Wait for jpeg_finish_compress() call */
             m_next_scanline = 0;   /* so jpeg_write_marker works */
             globalState = JpegState.CSTATE_WRCOEFS;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitDestination(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSuppressTables(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline, BitMiracle.LibJpeg.Classic.JpegErrorMessage.ResetErrorMessage(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection().
JpegWriteMarker()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker (int marker, byte [] data) inline
Write a special marker.
This is only recommended for writing COM or APPn markers. Must be called after JpegCompressStruct.JpegStartCompression and before first call to JpegCompressStruct.JpegWriteScanlines or JpegCompressStruct.JpegWriteRawData.
Parameters
marker Specify the marker type parameter as JpegMarker.COM for COM or JpegMarker.APP0 + n for APPn. (Actually, jpeg_write_marker will let you write any marker type, but we don't recommend writing any other kinds of marker)
data The data associated with the marker.
Special markers
See also
JpegMarker
Definition at line 772 of file JpegCompressStruct.cs.
         {
             if (m_next_scanline != 0 || (globalState != JpegState.CSTATE_SCANNING && globalState != JpegState.CSTATE_RAW_OK && globalState != JpegState.CSTATE_WRCOEFS))
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             if (data is null)
             {
                 throw new ArgumentNullException(nameof(data));
             }
             m_marker.WriteMarkerHeader(marker, data.Length);
             for (var i = 0; i < data.Length; i++)
             {
                 m_marker.WriteMarkerByte(data[i]);
             }
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline, BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerByte(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader().
JpegWriteMByte()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMByte (byte val) inline
Writes a byte of special marker's data.
Parameters
val The byte of data.
See also
JpegCompressStruct.JpegWriteMHeader
Definition at line 820 of file JpegCompressStruct.cs.
         {
             m_marker.WriteMarkerByte(val);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerByte().
JpegWriteMHeader()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader (int marker, int datalen) inline
Writes special marker's header.
Parameters
marker Special marker.
datalen Length of data associated with the marker.
After calling this method you need to call JpegCompressStruct.JpegWriteMByte exactly the number of times given in the length parameter.
This method lets you empty the output buffer partway through a marker, which might be important when using a suspending data destination module. In any case, if you are using a suspending destination, you should flush its buffer after inserting any special markers.
See also
JpegCompressStruct.JpegWriteMByte, JpegCompressStruct.JpegWriteMarker
Special markers
Definition at line 805 of file JpegCompressStruct.cs.
         {
             if (m_next_scanline != 0 || (globalState != JpegState.CSTATE_SCANNING && globalState != JpegState.CSTATE_RAW_OK && globalState != JpegState.CSTATE_WRCOEFS))
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             m_marker.WriteMarkerHeader(marker, datalen);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline, and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteMarkerHeader().
JpegWriteRawData()
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData (byte data[][][], int num_lines) inline
Alternate entry point to write raw data.
Parameters
data The raw data.
num_lines The number of scanlines for writing.
Returns
The number of lines actually written.
Processes exactly one iMCU row per call, unless suspended. Replaces JpegWriteScanlines when writing raw downsampled data.
Definition at line 1514 of file JpegCompressStruct.cs.
         {
             if (globalState != JpegState.CSTATE_RAW_OK)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             if (m_next_scanline >= m_image_height)
             {
                 WarnMS(JMessageCode.JWRN_TOO_MUCH_DATA);
                 return 0;
             }
             /* Call progress monitor hook if present */
             if (prog is object)
             {
                 prog.PassCounter = m_next_scanline;
                 prog.PassLimit = m_image_height;
                 prog.Updated();
             }
             /* Give master control module another chance if this is first call to
             * jpeg_write_raw_data.  This lets output of the frame/scan headers be
             * delayed so that application can write COM, etc, markers between
             * jpeg_start_compress and jpeg_write_raw_data.
             */
             if (m_master.MustCallPassStartup())
             {
                 m_master.PassStartup();
             }
             /* Verify that at least one iMCU row has been passed. */
             var lines_per_iMCU_row = m_max_v_samp_factor * min_DCT_v_scaled_size;
             if (num_lines < lines_per_iMCU_row)
             {
                 ErrExit(JMessageCode.JERR_BUFFER_SIZE);
             }
             /* Directly compress the row. */
             if (!m_coef.CompressData(data))
             {
                 /* If compressor did not consume the whole row, suspend processing. */
                 return 0;
             }
             /* OK, we processed one iMCU row. */
             m_next_scanline += lines_per_iMCU_row;
             return lines_per_iMCU_row;
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_max_v_samp_factor, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline, BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_v_scaled_size, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.MustCallPassStartup(), BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PassStartup(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
JpegWriteScanlines()
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines (byte scanlines[][], int num_lines) inline
Write some scanlines of data to the JPEG compressor.
Parameters
scanlines The array of scanlines.
num_lines The number of scanlines for writing.
Returns
The return value will be the number of lines actually written.
This should be less than the supplied num_lines only in case that the data destination module has requested suspension of the compressor, or if more than image_height scanlines are passed in.
We warn about excess calls to jpeg_write_scanlines() since this likely signals an application programmer error. However, excess scanlines passed in the last valid call are "silently" ignored, so that the application need not adjust num_lines for end-of-image when using a multiple-scanline buffer.
Compression details
Definition at line 1463 of file JpegCompressStruct.cs.
         {
             if (globalState != JpegState.CSTATE_SCANNING)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             if (m_next_scanline >= m_image_height)
             {
                 WarnMS(JMessageCode.JWRN_TOO_MUCH_DATA);
             }
             /* Call progress monitor hook if present */
             if (prog is object)
             {
                 prog.PassCounter = m_next_scanline;
                 prog.PassLimit = m_image_height;
                 prog.Updated();
             }
             /* Give master control module another chance if this is first call to
             * jpeg_write_scanlines.  This lets output of the frame/scan headers be
             * delayed so that application can write COM, etc, markers between
             * jpeg_start_compress and jpeg_write_scanlines.
             */
             if (m_master.MustCallPassStartup())
             {
                 m_master.PassStartup();
             }
             /* Ignore any extra scanlines at bottom of image. */
             var rows_left = m_image_height - m_next_scanline;
             if (num_lines > rows_left)
             {
                 num_lines = rows_left;
             }
             var row_ctr = 0;
             m_main.process_data(scanlines, ref row_ctr, num_lines);
             m_next_scanline += row_ctr;
             return row_ctr;
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_height, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_main, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_master, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.MustCallPassStartup(), BitMiracle.LibJpeg.Classic.JpegProgressManager.PassCounter, BitMiracle.LibJpeg.Classic.JpegProgressManager.PassLimit, BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PassStartup(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.process_data(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.prog, BitMiracle.LibJpeg.Classic.JpegProgressManager.Updated(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
JpegWriteTables()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables () inline
Alternate compression function: just write an abbreviated table file.
Before calling this, all parameters and a data destination must be set up.
To produce a pair of files containing abbreviated tables and abbreviated image data, one would proceed as follows:
Initialize JPEG object
Set JPEG parameters
Set destination to table file
jpeg_write_tables();
Set destination to image file
jpeg_start_compress(false);
Write data...
jpeg_finish_compress();
jpeg_write_tables has the side effect of marking all tables written (same as jpeg_suppress_tables(true)). Thus a subsequent jpeg_start_compress will not re-emit the tables unless it is passed write_all_tables=true.
Definition at line 851 of file JpegCompressStruct.cs.
         {
             if (globalState != JpegState.CSTATE_START)
             {
                 ErrExit(JMessageCode.JERR_BAD_STATE, (int)globalState);
             }
             /* (Re)initialize error mgr and destination modules */
             jpgError.ResetErrorMessage();
             m_dest.InitDestination();
             /* Initialize the marker writer ... bit of a crock to do it here. */
             m_marker = new JpegMarkerWriter(this);
             /* Write them tables! */
             m_marker.WriteTablesOnly();
             /* And clean up. */
             m_dest.TermDestination();
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.globalState, BitMiracle.LibJpeg.Classic.JpegDestinationManager.InitDestination(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, BitMiracle.LibJpeg.Classic.JpegErrorMessage.ResetErrorMessage(), BitMiracle.LibJpeg.Classic.JpegDestinationManager.TermDestination(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
ReduceScript()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.ReduceScript () inline private
Definition at line 2267 of file JpegCompressStruct.cs.
         {
             var idxout = 0;
             for (var idxin = 0; idxin < m_num_scans; idxin++)
             {
                 /* After skipping, idxout becomes smaller than idxin */
                 if (idxin != idxout)
                 {
                     /* Copy rest of data;
                      * note we stay in given chunk of allocated memory.
                      */
                     m_scan_info[idxout] = m_scan_info[idxin];
                 }
                 if (m_scan_info[idxout].Ss > lim_Se)
                 {
                     /* Entire scan out of range - skip this entry */
                     continue;
                 }
                 if (m_scan_info[idxout].Se > lim_Se)
                 {
                     /* Limit scan to end of block */
                     m_scan_info[idxout].Se = lim_Se;
                 }
                 idxout++;
             }
             m_num_scans = idxout;
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.lim_Se, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_scan_info, and BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.Se.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl().
StdHuffTables()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables () inline private
Set up the standard Huffman tables (cf. JPEG standard section K.3)
IMPORTANT: these are only valid for 8-bit data precision!
Definition at line 2305 of file JpegCompressStruct.cs.
         {
             AddHuffTable(ref m_dc_huff_tbl_ptrs[0], bits_dc_luminance, val_dc_luminance);
             AddHuffTable(ref m_ac_huff_tbl_ptrs[0], bits_ac_luminance, val_ac_luminance);
             AddHuffTable(ref m_dc_huff_tbl_ptrs[1], bits_dc_chrominance, val_dc_chrominance);
             AddHuffTable(ref m_ac_huff_tbl_ptrs[1], bits_ac_chrominance, val_ac_chrominance);
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.AddHuffTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_ac_chrominance, BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_ac_luminance, BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_dc_chrominance, BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_dc_luminance, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_ac_chrominance, BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_ac_luminance, BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_dc_chrominance, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_dc_luminance.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
TraceMS() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, JMessageCode code) inline inherited
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
See also
JpegErrorMessage.EmitMessage
Definition at line 306 of file JpegCommonStruct.cs.
         {
             TraceMS(lvl, (int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.My1PassCQuantizer.CreateColormap(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDHT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDQT(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetDRI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOI(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.GetSOS(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadMarkers(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ReadRestartMarker(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SaveMarker(), BitMiracle.LibJpeg.Classic.Internal.My2PassCQuantizer.SelectColors(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.SkipVariable(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), BitMiracle.LibJpeg.Classic.Internal.MyDestinationManager.WriteBuffer(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
TraceMS() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, JMessageCode code, params object [] args) inline inherited
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
args The parameters of message.
See also
JpegErrorMessage.EmitMessage
Definition at line 318 of file JpegCommonStruct.cs.
         {
             TraceMS(lvl, (int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS().
TraceMS() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS (int lvl, int code, params object [] args) inline inherited
Shows informational and debugging messages.
Parameters
lvl See JpegErrorMessage.EmitMessage for description.
code The message code.
args The parameters of message.
See also
JpegErrorMessage.EmitMessage
Definition at line 330 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.EmitMessage(lvl);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
TransencodeMasterSelection()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection (JVirtArray< JBlock > [] coef_arrays) inline private
Master selection of compression modules for transcoding.
Definition at line 1908 of file JpegCompressStruct.cs.
         {
             /* Initialize master control (includes parameter checking/processing) */
             JInitCMasterControl(true /* transcode only */);
             /* Entropy encoding: only Huffman or arithmetic coding. */
             if (arith_code)
             {
                 m_entropy = new ArithEntropyEncoder(this);
             }
             else
             {
                 m_entropy = new HuffmanEntropyEncoder(this);
             }
             /* We need a special coefficient buffer controller. */
             m_coef = new MyTransCCoefController(this, coef_arrays);
             m_marker = new JpegMarkerWriter(this);
             /* Write the datastream header (SOI, JFIF) immediately.
             * Frame and scan headers are postponed till later.
             * This lets application insert special markers after the SOI.
             */
             m_marker.WriteFileHeader();
         }
References BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_code, BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_entropy, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker, and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader().
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients().
ValidateScript()
void BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript () inline private
Verify that the scan script in scan_info[] is valid; also determine whether it uses progressive JPEG, and set progressive_mode.
Definition at line 2089 of file JpegCompressStruct.cs.
         {
             if (m_num_scans <= 0)
             {
                 ErrExit(JMessageCode.JERR_BAD_SCAN_SCRIPT, 0);
             }
             /* For sequential JPEG, all scans must have Ss=0, Se=DCTSIZE2-1;
             * for progressive JPEG, no scan can have this.
             */
             var last_bitpos = new int[JpegConstants.MAX_COMPONENTS][];
             for (var i = 0; i < JpegConstants.MAX_COMPONENTS; i++)
             {
                 last_bitpos[i] = new int[JpegConstants.DCTSIZE2];
             }
             var component_sent = new bool[JpegConstants.MAX_COMPONENTS];
             /* -1 until that coefficient has been seen; then last Al for it */
             if (m_scan_info[0].Ss != 0 || m_scan_info[0].Se != JpegConstants.DCTSIZE2 - 1)
             {
                 m_progressive_mode = true;
                 for (var ci = 0; ci < m_num_components; ci++)
                 {
                     for (var coefi = 0; coefi < JpegConstants.DCTSIZE2; coefi++)
                     {
                         last_bitpos[ci][coefi] = -1;
                     }
                 }
             }
             else
             {
                 m_progressive_mode = false;
                 for (var ci = 0; ci < m_num_components; ci++)
                 {
                     component_sent[ci] = false;
                 }
             }
             for (var scanno = 1; scanno <= m_num_scans; scanno++)
             {
                 var scanInfo = m_scan_info[scanno - 1];
                 /* Validate component indexes */
                 var ncomps = scanInfo.comps_in_scan;
                 if (ncomps <= 0 || ncomps > JpegConstants.MAX_COMPS_IN_SCAN)
                 {
                     ErrExit(JMessageCode.JERR_COMPONENT_COUNT, ncomps, JpegConstants.MAX_COMPS_IN_SCAN);
                 }
                 for (var ci = 0; ci < ncomps; ci++)
                 {
                     var thisi = scanInfo.component_index[ci];
                     if (thisi < 0 || thisi >= m_num_components)
                     {
                         ErrExit(JMessageCode.JERR_BAD_SCAN_SCRIPT, scanno);
                     }
                     /* Components must appear in SOF order within each scan */
                     if (ci > 0 && thisi <= scanInfo.component_index[ci - 1])
                     {
                         ErrExit(JMessageCode.JERR_BAD_SCAN_SCRIPT, scanno);
                     }
                 }
                 /* Validate progression parameters */
                 var Ss = scanInfo.Ss;
                 var Se = scanInfo.Se;
                 var Ah = scanInfo.Ah;
                 var Al = scanInfo.Al;
                 if (m_progressive_mode)
                 {
                     /* The JPEG spec simply gives the ranges 0..13 for Ah and Al, but that
                     * seems wrong: the upper bound ought to depend on data precision.
                     * Perhaps they really meant 0..N+1 for N-bit precision.
                     * Here we allow 0..10 for 8-bit data; Al larger than 10 results in
                     * out-of-range reconstructed DC values during the first DC scan,
                     * which might cause problems for some decoders.
                     */
                     const int MAX_AH_AL = 10;
                     if (Ss < 0
                         || Ss >= JpegConstants.DCTSIZE2
                         || Se < Ss
                         || Se >= JpegConstants.DCTSIZE2
                         || Ah < 0
                         || Ah > MAX_AH_AL
                         || Al < 0
                         || Al > MAX_AH_AL
                         || (Ss == 0 && Se != 0)        /* DC and AC together not OK */
                         || (Ss != 0 && ncomps != 1))    /* AC scans must be for only one component */
                     {
                         ErrExit(JMessageCode.JERR_BAD_PROG_SCRIPT, scanno);
                     }
                     for (var ci = 0; ci < ncomps; ci++)
                     {
                         var lastBitComponentIndex = scanInfo.component_index[ci];
                         if (Ss != 0 && last_bitpos[lastBitComponentIndex][0] < 0) /* AC without prior DC scan */
{
                             ErrExit(JMessageCode.JERR_BAD_PROG_SCRIPT, scanno);
                         }
                         for (var coefi = Ss; coefi <= Se; coefi++)
{
                             if (last_bitpos[lastBitComponentIndex][coefi] < 0)
{
                                 /* first scan of this coefficient */
                                 if (Ah != 0)
{
                                     ErrExit(JMessageCode.JERR_BAD_PROG_SCRIPT, scanno);
                                 }
                             }
                             else
{
                                 /* not first scan */
                                 if (Ah != last_bitpos[lastBitComponentIndex][coefi] || Al != Ah - 1)
{
                                     ErrExit(JMessageCode.JERR_BAD_PROG_SCRIPT, scanno);
                                 }
                             }
                             last_bitpos[lastBitComponentIndex][coefi] = Al;
                         }
                     }
                 }
                 else
                 {
                     /* For sequential JPEG, all progression parameters must be these: */
                     if (Ss != 0 || Se != JpegConstants.DCTSIZE2 - 1 || Ah != 0 || Al != 0)
                     {
                         ErrExit(JMessageCode.JERR_BAD_PROG_SCRIPT, scanno);
                     }
                     /* Make sure components are not sent twice */
                     for (var ci = 0; ci < ncomps; ci++)
                     {
                         var thisi = scanInfo.component_index[ci];
                         if (component_sent[thisi])
{
                             ErrExit(JMessageCode.JERR_BAD_SCAN_SCRIPT, scanno);
                         }
                         component_sent[thisi] = true;
                     }
                 }
             }
             /* Now verify that everything got sent. */
             if (m_progressive_mode)
             {
                 /* For progressive mode, we only check that at least some DC data
                 * got sent for each component; the spec does not require that all bits
                 * of all coefficients be transmitted.  Would it be wiser to enforce
                 * transmission of all coefficient bits??
                 */
                 for (var ci = 0; ci < m_num_components; ci++)
                 {
                     if (last_bitpos[ci][0] < 0)
                     {
                         ErrExit(JMessageCode.JERR_MISSING_DATA);
                     }
                 }
             }
             else
             {
                 for (var ci = 0; ci < m_num_components; ci++)
                 {
                     if (!component_sent[ci])
                     {
                         ErrExit(JMessageCode.JERR_MISSING_DATA);
                     }
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegScanInfo.comps_in_scan, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_scan_info, BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPONENTS, and BitMiracle.LibJpeg.Classic.JpegConstants.MAX_COMPS_IN_SCAN.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl().
WarnMS() [1/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (JMessageCode code) inline inherited
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
Definition at line 271 of file JpegCommonStruct.cs.
         {
             WarnMS((int)code);
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.DecodeMcuACRefine(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.DefaultDecompressParams(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.ExamineApp0(), BitMiracle.LibJpeg.Classic.Internal.MySourceManager.FillInputBuffer(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadRawData(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegReadScanlines(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerReader.NextMarker(), BitMiracle.LibJpeg.Classic.JpegSourceManager.ReSyncToRestart(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyDecoder.StartPass(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
WarnMS() [2/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (JMessageCode code, params object [] args) inline inherited
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
args The parameters of message.
Definition at line 281 of file JpegCommonStruct.cs.
         {
             WarnMS((int)code, args);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
WarnMS() [3/3]
void BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS (int code, params object [] args) inline inherited
Used for non-fatal errors (we can keep going, but the data is probably corrupt).
Parameters
code The message code.
args The parameters of message.
Definition at line 291 of file JpegCommonStruct.cs.
         {
             jpgError.msgCode = code;
             jpgError.msgParam = args;
             jpgError.EmitMessage(-1);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.jpgError, BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
Member Data Documentation
Ac_huff_tbl_ptrs
JHuffmanTable [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.Ac_huff_tbl_ptrs => m_ac_huff_tbl_ptrs
Gets the Huffman coding tables.
The Huffman coding tables or null if not defined.
Definition at line 644 of file JpegCompressStruct.cs.
arith_ac_K
internal byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_ac_K = new byte[JpegConstants.NUM_ARITH_TBLS] private
Definition at line 158 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC().
arith_code
internal bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_code private
Definition at line 170 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
arith_dc_L
internal byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_dc_L = new byte[JpegConstants.NUM_ARITH_TBLS] private
Definition at line 156 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC().
arith_dc_U
internal byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.arith_dc_U = new byte[JpegConstants.NUM_ARITH_TBLS] private
Definition at line 157 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC().
bits_ac_chrominance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_ac_chrominance static private
Initial value:
=
        {  0, 0, 2, 1, 2, 4, 4, 3, 4, 7, 5, 4, 4, 0, 1, 2, 0x77 }
Definition at line 82 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
bits_ac_luminance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_ac_luminance static private
Initial value:
=
        {  0, 0, 2, 1, 3, 3, 2, 4, 3, 5, 5, 4, 4, 0, 0, 1, 0x7d }
Definition at line 54 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
bits_dc_chrominance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_dc_chrominance static private
Initial value:
=
        {  0, 0, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0 }
Definition at line 49 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
bits_dc_luminance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.bits_dc_luminance static private
Initial value:
=
        {  0, 0, 1, 5, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0 }
Definition at line 44 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
CIR601sampling
internal bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.CIR601sampling private
Definition at line 172 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
compInfo
JpegComponentInfo [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.compInfo private
Definition at line 142 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspaceSetComp(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
Component_info
JpegComponentInfo [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info => compInfo
Gets the components that appears in SOF.
The component info array.
Definition at line 624 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressDataImpl(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressFirstPass(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeSmoothDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V1Downsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V2Downsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V2SmoothDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.IntDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.JpegCMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.MyCCoefController(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessWithoutContext(), BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.StartIMcuRow(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.StartIMcuRow(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
Copyright
string BitMiracle.LibJpeg.Classic.JpegCommonStruct.Copyright => "Copyright (C) 2008-2018, Bit Miracle" static inherited
Gets the LibJpeg's copyright.
The copyright.
Definition at line 127 of file JpegCommonStruct.cs.
Dc_huff_tbl_ptrs
JHuffmanTable [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.Dc_huff_tbl_ptrs => m_dc_huff_tbl_ptrs
Gets the Huffman coding tables.
The Huffman coding tables or null if not defined.
Definition at line 638 of file JpegCompressStruct.cs.
IsDecompressor
override bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.IsDecompressor => false
Retrieves false because this is not decompressor.
false
Definition at line 288 of file JpegCompressStruct.cs.
jpeg_height
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_height private
Definition at line 129 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
jpeg_width
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.jpeg_width private
Definition at line 128 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
lim_Se
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.lim_Se private
Definition at line 249 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.ReduceScript().
m_ac_huff_tbl_ptrs
internal JHuffmanTable [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_ac_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 154 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSuppressTables(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
m_Ah
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ah private
Definition at line 240 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
m_Al
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Al private
Definition at line 241 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters().
m_blocks_in_MCU
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_blocks_in_MCU private
Definition at line 232 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
m_cconvert
internal JpegColorConverter BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cconvert private
Definition at line 259 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessContext(), and BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessWithoutContext().
m_coef
internal JpegCCoefController BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_coef private
Definition at line 257 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.process_data(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection().
m_comps_in_scan
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_comps_in_scan private
Definition at line 225 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressDataImpl(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartS(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.StartIMcuRow(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.StartIMcuRow(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
m_cur_comp_info
internal int [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_cur_comp_info = new int[JpegConstants.MAX_COMPS_IN_SCAN] private
Definition at line 226 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressDataImpl(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.StartIMcuRow(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.StartIMcuRow(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
m_data_precision
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_data_precision private
Definition at line 137 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
m_dc_huff_tbl_ptrs
internal JHuffmanTable [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dc_huff_tbl_ptrs = new JHuffmanTable[JpegConstants.NUM_HUFF_TBLS] private
Definition at line 153 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDHT(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.JpegMakeCDerivedTable(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSuppressTables(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
m_dct_method
internal JDctMethod BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dct_method private
Definition at line 179 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
m_density_unit
internal DensityUnit BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_density_unit private
Definition at line 188 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
m_dest
internal JpegDestinationManager BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dest private
Definition at line 111 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitByte(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteE(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitByteS(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStdioDest(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables().
m_downsample
internal JpegDownsampler BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_downsample private
Definition at line 260 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessContext(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessData(), and BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessWithoutContext().
m_entropy
internal JpegEntropyEncoder BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_entropy private
Definition at line 262 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressDataImpl(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressOutput(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection().
m_fdct
internal JpegForwardDct BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_fdct private
Definition at line 261 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressDataImpl(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressFirstPass(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass().
m_image_height
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_height private
Definition at line 114 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessContext(), and BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.StartPass().
m_image_width
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_image_width private
Definition at line 113 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.CmykYcckConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeSmoothDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.GrayscaleConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V1Downsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V2Downsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V2SmoothDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.IntDownsample(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.NullConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessContext(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessWithoutContext(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.RgbGrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.RgbRgb1Convert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.RgbYccConvert().
m_in_color_space
internal JColorSpace BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_in_color_space private
Definition at line 116 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultColorspace().
m_input_components
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_input_components private
Definition at line 115 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.GrayscaleConvert(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace().
m_input_smoothing
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_input_smoothing private
Definition at line 178 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeSmoothDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V2SmoothDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
m_JFIF_major_version
internal byte BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_major_version private
Definition at line 185 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
m_JFIF_minor_version
internal byte BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_JFIF_minor_version private
Definition at line 186 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
m_jpeg_color_space
internal JColorSpace BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_jpeg_color_space private
Definition at line 139 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitAdobeApp14(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression().
m_main
internal JpegCMainController BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_main private
Definition at line 255 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMainController(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass().
m_marker
internal JpegMarkerWriter BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_marker private
Definition at line 258 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMByte(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PassStartup(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.TransencodeMasterSelection().
m_master
internal JpegCompMaster BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_master private
Definition at line 254 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PassStartup().
m_max_h_samp_factor
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_max_h_samp_factor private
Definition at line 208 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
m_max_v_samp_factor
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_max_v_samp_factor private
Definition at line 209 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.FullsizeSmoothDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V1Downsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V2Downsample(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.H2V2SmoothDownsample(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.IntDownsample(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessContext(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessWithoutContext(), and BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.StartPass().
m_MCU_membership
internal int [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCU_membership = new int[JpegConstants.C_MAX_BLOCKS_IN_MCU] private
Definition at line 233 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
m_MCU_rows_in_scan
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCU_rows_in_scan private
Definition at line 230 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
m_MCUs_per_row
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_MCUs_per_row private
Definition at line 229 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressDataImpl(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressOutput(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
m_next_scanline
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_next_scanline private
Definition at line 198 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMarker(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteMHeader(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteScanlines().
m_num_components
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components private
Definition at line 138 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressFirstPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.Downsample(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOF(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.JpegCMainController(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.MyCCoefController(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.NullConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessContext(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessWithoutContext(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
m_num_scans
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_scans private
Definition at line 164 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.JpegCompMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.ReduceScript(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript().
m_prep
internal JpegCPrepController BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_prep private
Definition at line 256 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.process_data().
m_progressive_mode
internal bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_progressive_mode private
Definition at line 207 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassHuffman(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HuffmanEntropyEncoder(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
m_quant_tbl_ptrs
internal JQuantTable [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs = new JQuantTable[JpegConstants.NUM_QUANT_TBLS] private
Definition at line 145 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegAddQuantTable(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSuppressTables(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteTablesOnly().
m_raw_data_in
internal bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_raw_data_in private
Definition at line 169 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMainController(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.start_pass().
m_restart_in_rows
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_in_rows private
Definition at line 182 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup().
m_restart_interval
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_restart_interval private
Definition at line 181 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDRI(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuDCRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuGather(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuHuffman(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
m_scan_info
internal JpegScanInfo [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_scan_info private
Definition at line 167 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.ReduceScript(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.ValidateScript().
m_script_space_size
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_script_space_size private
Definition at line 264 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression().
m_Se
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Se private
Definition at line 239 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
m_Ss
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Ss private
Definition at line 238 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDAC(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EmitRestartE(), BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitSOS(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.FinishPassGather(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForHuffmanOptimizationPass(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.StartPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteScanHeader().
m_total_iMCU_rows
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_total_iMCU_rows private
Definition at line 214 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.CompressData(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressDataImpl(), BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.CompressFirstPass(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegFinishCompress(), BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.process_data(), BitMiracle.LibJpeg.Classic.Internal.MyTransCCoefController.StartIMcuRow(), and BitMiracle.LibJpeg.Classic.Internal.MyCCoefController.StartIMcuRow().
m_write_Adobe_marker
internal bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_write_Adobe_marker private
Definition at line 191 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader().
m_write_JFIF_header
internal bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_write_JFIF_header private
Definition at line 184 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFileHeader().
m_X_density
internal short BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_X_density private
Definition at line 189 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
m_Y_density
internal short BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_Y_density private
Definition at line 190 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitJfifApp0(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
Max_v_samp_factor
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.Max_v_samp_factor => m_max_v_samp_factor
Gets the largest vertical sample factor.
The largest vertical sample factor.
Compression parameter selection
Definition at line 618 of file JpegCompressStruct.cs.
min_DCT_h_scaled_size
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_h_scaled_size private
Definition at line 211 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.CreateContextBuffer(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.JpegCPrepController(), and BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler().
min_DCT_v_scaled_size
internal int BitMiracle.LibJpeg.Classic.JpegCompressStruct.min_DCT_v_scaled_size private
Definition at line 212 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.Internal.JpegDownsampler.JpegDownsampler(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteRawData(), BitMiracle.LibJpeg.Classic.Internal.JpegCPrepController.PreProcessWithoutContext(), and BitMiracle.LibJpeg.Classic.Internal.JpegCMainController.process_data().
natural_order
internal int [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.natural_order private
Definition at line 248 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitDQT(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACFirst(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeMcuACRefine(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.EncodeOneBlock(), BitMiracle.LibJpeg.Classic.Internal.HuffmanEntropyEncoder.HTestOneBlock(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup().
Next_scanline
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.Next_scanline => m_next_scanline
Gets the index of next scanline to be written to JpegCompressStruct.JpegWriteScanlines.
Application may use this to control its processing loop, e.g., "while (Next_scanline &lt; Image_height)"
Range: from 0 to (Image_height - 1)
See also
JpegCompressStruct.JpegWriteScanlines
Definition at line 653 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
optimizeEntropyCoding
internal bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.optimizeEntropyCoding private
Definition at line 171 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.FinishPass(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCompressMaster(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.JpegCompMaster(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForMainPass(), and BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PrepareForOutputPass().
Quant_tbl_ptrs
JQuantTable [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.Quant_tbl_ptrs => m_quant_tbl_ptrs
Gets the coefficient quantization tables.
The coefficient quantization tables or null if not defined.
Definition at line 632 of file JpegCompressStruct.cs.
scriptSpace
internal JpegScanInfo [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.scriptSpace private
Definition at line 263 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillAScan(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillDcScans(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.FillScans(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSimpleProgression().
std_chrominance_quant_tbl
readonly int [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.std_chrominance_quant_tbl static private
Initial value:
=
        {
            17,  18,  24,  47,  99,  99,  99,  99,
            18,  21,  26,  66,  99,  99,  99,  99,
            24,  26,  56,  99,  99,  99,  99,  99,
            47,  66,  99,  99,  99,  99,  99,  99,
            99,  99,  99,  99,  99,  99,  99,  99,
            99,  99,  99,  99,  99,  99,  99,  99,
            99,  99,  99,  99,  99,  99,  99,  99,
            99,  99,  99,  99,  99,  99,  99,  99
        }
Definition at line 29 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultQTables(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetLinearQuality().
std_luminance_quant_tbl
readonly int [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.std_luminance_quant_tbl static private
Initial value:
= {
            16,  11,  10,  16,  24,  40,  51,  61,
            12,  12,  14,  19,  26,  58,  60,  55,
            14,  13,  16,  24,  40,  57,  69,  56,
            14,  17,  22,  29,  51,  87,  80,  62,
            18,  22,  37,  56,  68, 109, 103,  77,
            24,  35,  55,  64,  81, 104, 113,  92,
            49,  64,  78,  87, 103, 121, 120, 101,
            72,  92,  95,  98, 112, 100, 103,  99
        }
Definition at line 18 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultQTables(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetLinearQuality().
val_ac_chrominance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_ac_chrominance static private
Initial value:
=
        {
            0x00, 0x01, 0x02, 0x03, 0x11, 0x04, 0x05, 0x21,
            0x31, 0x06, 0x12, 0x41, 0x51, 0x07, 0x61, 0x71,
            0x13, 0x22, 0x32, 0x81, 0x08, 0x14, 0x42, 0x91,
            0xa1, 0xb1, 0xc1, 0x09, 0x23, 0x33, 0x52, 0xf0,
            0x15, 0x62, 0x72, 0xd1, 0x0a, 0x16, 0x24, 0x34,
            0xe1, 0x25, 0xf1, 0x17, 0x18, 0x19, 0x1a, 0x26,
            0x27, 0x28, 0x29, 0x2a, 0x35, 0x36, 0x37, 0x38,
            0x39, 0x3a, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48,
            0x49, 0x4a, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58,
            0x59, 0x5a, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68,
            0x69, 0x6a, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78,
            0x79, 0x7a, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87,
            0x88, 0x89, 0x8a, 0x92, 0x93, 0x94, 0x95, 0x96,
            0x97, 0x98, 0x99, 0x9a, 0xa2, 0xa3, 0xa4, 0xa5,
            0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xb2, 0xb3, 0xb4,
            0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xc2, 0xc3,
            0xc4, 0xc5, 0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xd2,
            0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda,
            0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9,
            0xea, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8,
            0xf9, 0xfa
        }
Definition at line 85 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
val_ac_luminance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_ac_luminance static private
Initial value:
=
        {
            0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12,
            0x21, 0x31, 0x41, 0x06, 0x13, 0x51, 0x61, 0x07,
            0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xa1, 0x08,
            0x23, 0x42, 0xb1, 0xc1, 0x15, 0x52, 0xd1, 0xf0,
            0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0a, 0x16,
            0x17, 0x18, 0x19, 0x1a, 0x25, 0x26, 0x27, 0x28,
            0x29, 0x2a, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39,
            0x3a, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49,
            0x4a, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59,
            0x5a, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69,
            0x6a, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79,
            0x7a, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89,
            0x8a, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98,
            0x99, 0x9a, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7,
            0xa8, 0xa9, 0xaa, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6,
            0xb7, 0xb8, 0xb9, 0xba, 0xc2, 0xc3, 0xc4, 0xc5,
            0xc6, 0xc7, 0xc8, 0xc9, 0xca, 0xd2, 0xd3, 0xd4,
            0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xe1, 0xe2,
            0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea,
            0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8,
            0xf9, 0xfa
        }
Definition at line 57 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
val_dc_chrominance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_dc_chrominance = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 } static private
Definition at line 52 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
val_dc_luminance
readonly byte [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.val_dc_luminance = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 } static private
Definition at line 47 of file JpegCompressStruct.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.StdHuffTables().
Property Documentation
BlockSize
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.BlockSize get set
the basic DCT block size: 1..16
Definition at line 246 of file JpegCompressStruct.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitPseudoSOS(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JInitCMasterControl(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcTransDimensions(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.PerScanSetup(), BitMiracle.LibJpeg.Classic.Internal.JpegCompMaster.SelectScanParameters(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
CCIR601Sampling
bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.CCIR601Sampling get set
Gets or sets a value indicating whether first samples are cosited.
true if first samples are cosited; otherwise, false.
Definition at line 429 of file JpegCompressStruct.cs.
         {
             get { return CIR601sampling; }
             set { CIR601sampling = value; }
         }
ColorTransform
JColorTransform BitMiracle.LibJpeg.Classic.JpegCompressStruct.ColorTransform get set
Color transform identifier, writes LSE marker if nonzero
Definition at line 196 of file JpegCompressStruct.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct(), BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.JpegCopyCriticalParameters(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults(), and BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.WriteFrameHeader().
Data_precision
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.Data_precision get set
Gets or sets the number of bits of precision in image data.
Default value: 8
The number of bits.
The data precision.
Definition at line 368 of file JpegCompressStruct.cs.
         {
             get { return m_data_precision; }
             set { m_data_precision = value; }
         }
DctMethod
JDctMethod BitMiracle.LibJpeg.Classic.JpegCompressStruct.DctMethod get set
Gets or sets the algorithm used for the DCT step.
The DCT algorithm.
Compression parameter selection
Definition at line 454 of file JpegCompressStruct.cs.
         {
             get { return m_dct_method; }
             set { m_dct_method = value; }
         }
Density_unit
DensityUnit BitMiracle.LibJpeg.Classic.JpegCompressStruct.Density_unit get set
Gets or sets the resolution information to be written into the JFIF marker; not used otherwise.
Default value: BitMiracle.LibJpeg.Classic.DensityUnit.Unknown
The pixel aspect ratio is defined by JpegCompressStruct.X_density/JpegCompressStruct.Y_density even when Density_unit is Unknown.
The density unit.
See also
JpegCompressStruct.X_density, JpegCompressStruct.Y_density
Compression parameter selection
Definition at line 563 of file JpegCompressStruct.cs.
         {
             get { return m_density_unit; }
             set { m_density_unit = value; }
         }
Dest
LibJpeg.Classic.JpegDestinationManager BitMiracle.LibJpeg.Classic.JpegCompressStruct.Dest get set
Gets or sets the destination for compressed data
The destination for compressed data.
Definition at line 295 of file JpegCompressStruct.cs.
         {
             get { return m_dest; }
             set { m_dest = value; }
         }
DoFancyDownsampling
bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.DoFancyDownsampling get set
TRUE=apply fancy downsampling
Definition at line 177 of file JpegCompressStruct.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.InitialSetup(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
Err
JpegErrorMessage?? BitMiracle.LibJpeg.Classic.JpegCommonStruct.Err get set inherited
Error handler module.
The error manager.
Error handling
Definition at line 96 of file JpegCommonStruct.cs.
         {
             get { return jpgError; }
             set { jpgError = value ?? throw new ArgumentNullException(nameof(value)); }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.JpegCommonStruct().
Image_height
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.Image_height get set
Gets or sets the height of image, in pixels.
The height of image.
Compression details
Definition at line 322 of file JpegCompressStruct.cs.
         {
             get { return m_image_height; }
             set { m_image_height = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
Image_width
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.Image_width get set
Gets or sets the width of image, in pixels.
The width of image.
Compression details
Definition at line 311 of file JpegCompressStruct.cs.
         {
             get { return m_image_width; }
             set { m_image_width = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
In_color_space
LibJpeg.Classic.JColorSpace BitMiracle.LibJpeg.Classic.JpegCompressStruct.In_color_space get set
Gets or sets the color space of source image.
The color space.
Compression details
Special color spaces
Definition at line 345 of file JpegCompressStruct.cs.
         {
             get { return m_in_color_space; }
             set { m_in_color_space = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
Input_components
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.Input_components get set
Gets or sets the number of color channels (components per pixel)
The number of color channels.
Compression details
Definition at line 333 of file JpegCompressStruct.cs.
         {
             get { return m_input_components; }
             set { m_input_components = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
JFIF_major_version
byte BitMiracle.LibJpeg.Classic.JpegCompressStruct.JFIF_major_version get set
Gets or sets the version number to be written into the JFIF marker.
JpegCompressStruct.JpegSetDefaults initializes the version to 1.01 (major=minor=1). You should set it to 1.02 (major=1, minor=2) if you plan to write any JFIF 1.02 extension markers.
The version number to be written into the JFIF marker.
See also
JpegCompressStruct.JFIF_minor_version, JpegCompressStruct.Write_JFIF_header
Definition at line 526 of file JpegCompressStruct.cs.
         {
             get { return m_JFIF_major_version; }
             set { m_JFIF_major_version = value; }
         }
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetColorspace().
JFIF_minor_version
byte BitMiracle.LibJpeg.Classic.JpegCompressStruct.JFIF_minor_version get set
Gets or sets the version number to be written into the JFIF marker.
JpegCompressStruct.JpegSetDefaults initializes the version to 1.01 (major=minor=1). You should set it to 1.02 (major=1, minor=2) if you plan to write any JFIF 1.02 extension markers.
The version number to be written into the JFIF marker.
See also
JpegCompressStruct.JFIF_major_version, JpegCompressStruct.Write_JFIF_header
Definition at line 541 of file JpegCompressStruct.cs.
         {
             get { return m_JFIF_minor_version; }
             set { m_JFIF_minor_version = value; }
         }
Jpeg_color_space
JColorSpace BitMiracle.LibJpeg.Classic.JpegCompressStruct.Jpeg_color_space get set
Gets or sets the JPEG color space.
We recommend to use JpegSetColorspace if you want to change this.
The JPEG color space.
Definition at line 389 of file JpegCompressStruct.cs.
         {
             get { return m_jpeg_color_space; }
             set { m_jpeg_color_space = value; }
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorConverter.JpegColorConverter().
Num_components
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.Num_components get set
Gets or sets the number of color components for JPEG color space.
The number of color components for JPEG color space.
Definition at line 378 of file JpegCompressStruct.cs.
         {
             get { return m_num_components; }
             set { m_num_components = value; }
         }
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegMarkerWriter.EmitLseIct().
OptimizeCoding
bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.OptimizeCoding get set
Gets or sets a value indicating a way of using Huffman coding tables.
When this is true, you need not supply Huffman tables at all, and any you do supply will be overwritten.
true causes the compressor to compute optimal Huffman coding tables for the image. This requires an extra pass over the data and therefore costs a good deal of space and time. The default is false, which tells the compressor to use the supplied or default Huffman tables. In most cases optimal tables save only a few percent of file size compared to the default tables.
Compression parameter selection
Definition at line 419 of file JpegCompressStruct.cs.
         {
             get { return optimizeEntropyCoding; }
             set { optimizeEntropyCoding = value; }
         }
Progress
JpegProgressManager?? BitMiracle.LibJpeg.Classic.JpegCommonStruct.Progress get set inherited
Progress monitor.
The progress manager.
Default value: null.
Definition at line 85 of file JpegCommonStruct.cs.
         {
             get { return prog; }
             set { prog = value ?? throw new ArgumentNullException(nameof(value)); }
         }
QScaleFactor
int [] BitMiracle.LibJpeg.Classic.JpegCompressStruct.QScaleFactor = new int[JpegConstants.NUM_QUANT_TBLS] get set
corresponding scale factors (percentage, initialized 100).
Definition at line 150 of file JpegCompressStruct.cs.
 { get; set; } = new int[JpegConstants.NUM_QUANT_TBLS];
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.Initialize(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegDefaultQTables().
Raw_data_in
bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.Raw_data_in get set
Gets or sets a value indicating whether you will be supplying raw data.
Default value: false
true if you will be supplying raw data; otherwise, false.
See also
JpegCompressStruct.JpegWriteRawData
Definition at line 403 of file JpegCompressStruct.cs.
         {
             get { return m_raw_data_in; }
             set { m_raw_data_in = value; }
         }
RestartInRows
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.RestartInRows get set
Gets or sets the interval in MCU rows.
Default value: 0
If Restart_in_rows is not 0, then JpegCompressStruct.RestartInterval is set after the image width in MCUs is computed.
One restart marker per MCU row is often a good choice. The overhead of restart markers is higher in grayscale JPEG files than in color files, and MUCH higher in progressive JPEGs. If you use restarts, you may want to use larger intervals in those cases.
The restart interval in MCU rows.
See also
JpegCompressStruct.RestartInterval
Compression parameter selection
Definition at line 494 of file JpegCompressStruct.cs.
         {
             get { return m_restart_in_rows; }
             set { m_restart_in_rows = value; }
         }
RestartInterval
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.RestartInterval get set
Gets or sets the exact interval in MCU blocks.
Default value: 0
One restart marker per MCU row is often a good choice. The overhead of restart markers is higher in grayscale JPEG files than in color files, and MUCH higher in progressive JPEGs. If you use restarts, you may want to use larger intervals in those cases.
The restart interval.
See also
JpegCompressStruct.RestartInRows
Compression parameter selection
Definition at line 476 of file JpegCompressStruct.cs.
         {
             get { return m_restart_interval; }
             set { m_restart_interval = value; }
         }
ScaleDenom
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.ScaleDenom get set
The scale denomenator
Definition at line 126 of file JpegCompressStruct.cs.
 { get; set; } /* fraction by which to scale image */
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
ScaleNum
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.ScaleNum get set
The scale numerator
Definition at line 121 of file JpegCompressStruct.cs.
 { get; set; }
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegCalcJpegDimensions(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegSetDefaults().
SmoothingFactor
int BitMiracle.LibJpeg.Classic.JpegCompressStruct.SmoothingFactor get set
Gets or sets the coefficient of image smoothing.
Default value: 0
If non-zero, the input image is smoothed; the value should be 1 for minimal smoothing to 100 for maximum smoothing.
The coefficient of image smoothing.
Compression parameter selection
Definition at line 443 of file JpegCompressStruct.cs.
         {
             get { return m_input_smoothing; }
             set { m_input_smoothing = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
Version
string BitMiracle.LibJpeg.Classic.JpegCommonStruct.Version static get inherited
Gets the version of LibJpeg.
The version of LibJpeg.
Definition at line 106 of file JpegCommonStruct.cs.
         {
             get
             {
                 var assembly = typeof(JpegCommonStruct).GetTypeInfo().Assembly;
                 var assemblyName = new AssemblyName(assembly.FullName);
                 var version = assemblyName.Version;
                 var versionString = version.Major.ToString(CultureInfo.InvariantCulture) +
                     "." + version.Minor.ToString(CultureInfo.InvariantCulture);
                 versionString += "." + version.Build.ToString(CultureInfo.InvariantCulture);
                 versionString += "." + version.Revision.ToString(CultureInfo.InvariantCulture);
                 return versionString;
             }
         }
Write_Adobe_marker
bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.Write_Adobe_marker get set
Gets or sets a value indicating whether to emit Adobe APP14 marker.
JpegCompressStruct.JpegSetDefaults and JpegCompressStruct.JpegSetColorspace set this true if JPEG color space RGB, CMYK, or YCCK is selected, otherwise false. It is generally a bad idea to set both JpegCompressStruct.Write_JFIF_header and JpegCompressStruct.Write_Adobe_marker. In fact, you probably shouldn't change the default settings at all - the default behavior ensures that the JPEG file's color space can be recognized by the decoder.
If true an Adobe APP14 marker is emitted; false, otherwise.
Compression parameter selection
Definition at line 608 of file JpegCompressStruct.cs.
         {
             get { return m_write_Adobe_marker; }
             set { m_write_Adobe_marker = value; }
         }
Write_JFIF_header
bool BitMiracle.LibJpeg.Classic.JpegCompressStruct.Write_JFIF_header get set
Gets or sets a value indicating whether the JFIF APP0 marker is emitted.
JpegCompressStruct.JpegSetDefaults and JpegCompressStruct.JpegSetColorspace set this true if a JFIF-legal JPEG color space (i.e., YCbCr or grayscale) is selected, otherwise false.
true if JFIF APP0 marker is emitted; otherwise, false.
See also
JpegCompressStruct.JFIF_major_version
Compression parameter selection
Definition at line 511 of file JpegCompressStruct.cs.
         {
             get { return m_write_JFIF_header; }
             set { m_write_JFIF_header = value; }
         }
X_density
short BitMiracle.LibJpeg.Classic.JpegCompressStruct.X_density get set
Gets or sets the horizontal component of pixel ratio.
Default value: 1
The horizontal density.
See also
JpegCompressStruct.Density_unit, JpegCompressStruct.Y_density
Definition at line 578 of file JpegCompressStruct.cs.
         {
             get { return m_X_density; }
             set { m_X_density = value; }
         }
Y_density
short BitMiracle.LibJpeg.Classic.JpegCompressStruct.Y_density get set
Gets or sets the vertical component of pixel ratio.
Default value: 1
The vertical density.
See also
JpegCompressStruct.Density_unit, JpegCompressStruct.X_density
Definition at line 591 of file JpegCompressStruct.cs.
         {
             get { return m_Y_density; }
             set { m_Y_density = value; }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/JpegCompressStruct.cs