Juniper: Juniper.Unity.Haptics.AndroidAPI26Haptics Class Reference
Juniper.Unity.Haptics.AndroidAPI26Haptics Class Reference
Haptic system that implements the latest Android API version (26), which enables vibrations of different strengths to be played without pulse-width modulating the vibration manually.
Public Member Functions
override void Cancel ()
Cancel the current vibration, whatever it is.
override void Play (HapticExpression expr)
Play a canned haptic pattern.
override void Play (params HapticPatternElement[] points)
Play a haptic pattern.
override void Play (long[] pattern)
Play a patterned vibration with alternating amplitude modulation.
override void Play (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
override void Vibrate (HapticPatternElement point)
Play a single element of a haptic pattern.
override void Vibrate (long milliseconds)
Play a single vibration for a set period of time at max amplitude.
override void Vibrate (long milliseconds, float amplitude)
Play a patterned vibration with amplitude modulation.
Protected Member Functions
override void Awake ()
Creates the haptic interface specific to Android API 26+.
override IEnumerator VibrateCoroutine (long milliseconds)
Play a single vibration of a set length of time.
override IEnumerator VibrateCoroutine (long milliseconds, float amplitude)
Play a single vibration, of a set length of time, at a set strength.
override IEnumerator PlayCoroutine (long[] pattern)
Play a patterned vibration, where all of the vibrations are the same amplitude, the default amplitude.
override IEnumerator PlayCoroutine (long[] pattern, float[] amplitudes)
Play a patterned vibration with amplitude modulation.
Static Protected Attributes
static AndroidJavaObject vibrator
The vibrator service.
Static Private Member Functions
static void CreateVibrationEffect (string function, params object[] args)
Calls one of the static functions on VibrationEffect that creates a amplitude-modulated vibration pattern and executes it through the Android Vibration interface.
Static Private Attributes
static AndroidJavaClass VibrationEffect
The android.os.VibrationEffect class, which contains the API 26 features.
static int DefaultAmplitude
A cached value for VibrationEffect's DEFAULT_AMPLITUDE field, so we don't have to incur the context switching cost of reading it repeatedly.
Detailed Description
Haptic system that implements the latest Android API version (26), which enables vibrations of different strengths to be played without pulse-width modulating the vibration manually.
Definition at line 14 of file AndroidAPI26Haptics.cs.
Member Function Documentation
Awake()
override void Juniper.Unity.Haptics.AndroidAPI26Haptics.Awake () inline protected virtual
Creates the haptic interface specific to Android API 26+.
Reimplemented from Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.
Definition at line 42 of file AndroidAPI26Haptics.cs.
         {
             base.Awake();
             if (VibrationEffect == null)
             {
                 VibrationEffect = new AndroidJavaClass("android.os.VibrationEffect");
                 DefaultAmplitude = VibrationEffect.GetStatic<int>("DEFAULT_AMPLITUDE");
             }
         }
References Juniper.Unity.Haptics.AndroidAPI26Haptics.DefaultAmplitude, and Juniper.Unity.Haptics.AndroidAPI26Haptics.VibrationEffect.
Cancel()
override void Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.Cancel () inline virtual inherited
Cancel the current vibration, whatever it is.
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 39 of file AbstractAndroidAPIHaptics.cs.
         {
             base.Cancel();
             vibrator.Call("cancel");
         }
References Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator.
CreateVibrationEffect()
static void Juniper.Unity.Haptics.AndroidAPI26Haptics.CreateVibrationEffect (string function, params object [] args) inline static private
Calls one of the static functions on VibrationEffect that creates a amplitude-modulated vibration pattern and executes it through the Android Vibration interface.
Parameters
function Function.
args Arguments.
Definition at line 33 of file AndroidAPI26Haptics.cs.
         {
             var vibrationEffect = VibrationEffect.CallStatic<AndroidJavaObject>(function, args);
             vibrator.Call("vibrate", vibrationEffect);
         }
References Juniper.Unity.Haptics.AndroidAPI26Haptics.VibrationEffect, and Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator.
Referenced by Juniper.Unity.Haptics.AndroidAPI26Haptics.PlayCoroutine(), and Juniper.Unity.Haptics.AndroidAPI26Haptics.VibrateCoroutine().
Play() [1/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (HapticExpression expr) inline virtual inherited
Play a canned haptic pattern.
Parameters
expr
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Reimplemented in Juniper.Unity.Haptics.iOS10Haptics.
Definition at line 23 of file AbstractHapticExpressor.cs.
         {
             HapticPatternElement.Play(this, expr);
         }
References Juniper.Unity.Haptics.HapticPatternElement.Play().
Play() [2/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (params HapticPatternElement [] points) inline virtual inherited
Play a haptic pattern.
Parameters
points
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 32 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(points));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [3/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern) inline virtual inherited
Play a patterned vibration with alternating amplitude modulation.
Parameters
pattern Pattern.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 59 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
Play() [4/4]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Play (long [] pattern, float [] amplitudes) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 69 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(PlayCoroutine(pattern, amplitudes));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.PlayCoroutine().
PlayCoroutine() [1/2]
override IEnumerator Juniper.Unity.Haptics.AndroidAPI26Haptics.PlayCoroutine (long [] pattern) inline protected virtual
Play a patterned vibration, where all of the vibrations are the same amplitude, the default amplitude.
Parameters
pattern Pattern.
Reimplemented from Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.
Definition at line 76 of file AndroidAPI26Haptics.cs.
         {
             CreateVibrationEffect("createWaveform", pattern, -1);
             yield return new WaitForSeconds(pattern.Sum() * 0.001f);
         }
References Juniper.Unity.Haptics.AndroidAPI26Haptics.CreateVibrationEffect().
PlayCoroutine() [2/2]
override IEnumerator Juniper.Unity.Haptics.AndroidAPI26Haptics.PlayCoroutine (long [] pattern, float [] amplitudes) inline protected virtual
Play a patterned vibration with amplitude modulation.
Parameters
pattern Pattern.
amplitudes Amplitudes.
Reimplemented from Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 87 of file AndroidAPI26Haptics.cs.
         {
             var amps = new int[amplitudes.Length];
             for (var i = 0; i < amplitudes.Length; ++i)
             {
                 amps[i] = (int)(amplitudes[i] * 255);
             }
             CreateVibrationEffect("createWaveform", pattern, amps, -1);
             yield return new WaitForSeconds(pattern.Sum() * 0.001f);
         }
References Juniper.Unity.Haptics.AndroidAPI26Haptics.CreateVibrationEffect().
Vibrate() [1/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (HapticPatternElement point) inline virtual inherited
Play a single element of a haptic pattern.
Parameters
point
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 41 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(point));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [2/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds) inline virtual inherited
Play a single vibration for a set period of time at max amplitude.
Parameters
milliseconds Milliseconds.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 50 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
Vibrate() [3/3]
override void Juniper.Unity.Haptics.AbstractHapticExpressor.Vibrate (long milliseconds, float amplitude) inline virtual inherited
Play a patterned vibration with amplitude modulation.
Parameters
milliseconds Pattern.
amplitude Amplitudes.
Implements Juniper.Unity.Haptics.AbstractHapticDevice.
Definition at line 79 of file AbstractHapticExpressor.cs.
         {
             StartCoroutine(VibrateCoroutine(milliseconds, amplitude));
         }
References Juniper.Unity.Haptics.AbstractHapticExpressor.VibrateCoroutine().
VibrateCoroutine() [1/2]
override IEnumerator Juniper.Unity.Haptics.AndroidAPI26Haptics.VibrateCoroutine (long milliseconds) protected virtual
Play a single vibration of a set length of time.
Parameters
milliseconds Milliseconds.
Reimplemented from Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.
VibrateCoroutine() [2/2]
override IEnumerator Juniper.Unity.Haptics.AndroidAPI26Haptics.VibrateCoroutine (long milliseconds, float amplitude) inline protected virtual
Play a single vibration, of a set length of time, at a set strength.
Parameters
milliseconds Milliseconds.
amplitude Amplitude values should be on the range [0, 1].
Implements Juniper.Unity.Haptics.AbstractHapticExpressor.
Definition at line 65 of file AndroidAPI26Haptics.cs.
         {
             CreateVibrationEffect("createOneShot", milliseconds, (int)(amplitude * 255));
             yield return new WaitForSeconds(milliseconds * 0.001f);
         }
References Juniper.Unity.Haptics.AndroidAPI26Haptics.CreateVibrationEffect().
Member Data Documentation
DefaultAmplitude
int Juniper.Unity.Haptics.AndroidAPI26Haptics.DefaultAmplitude static private
A cached value for VibrationEffect's DEFAULT_AMPLITUDE field, so we don't have to incur the context switching cost of reading it repeatedly.
Definition at line 25 of file AndroidAPI26Haptics.cs.
Referenced by Juniper.Unity.Haptics.AndroidAPI26Haptics.Awake().
VibrationEffect
AndroidJavaClass Juniper.Unity.Haptics.AndroidAPI26Haptics.VibrationEffect static private
The android.os.VibrationEffect class, which contains the API 26 features.
Definition at line 19 of file AndroidAPI26Haptics.cs.
Referenced by Juniper.Unity.Haptics.AndroidAPI26Haptics.Awake(), and Juniper.Unity.Haptics.AndroidAPI26Haptics.CreateVibrationEffect().
vibrator
AndroidJavaObject Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.vibrator static protected inherited
The vibrator service.
Definition at line 20 of file AbstractAndroidAPIHaptics.cs.
Referenced by Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.Awake(), Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.Cancel(), Juniper.Unity.Haptics.AndroidAPI26Haptics.CreateVibrationEffect(), Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.PlayCoroutine(), and Juniper.Unity.Haptics.AbstractAndroidAPIHaptics.VibrateCoroutine().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/Android/AndroidAPI26Haptics.cs