Juniper: Juniper.XR.AnchorStore Class Reference
Juniper.XR.AnchorStore Class Reference
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This component creates the native anchor type for any given subsystem, and save it to its native anchor store.
Public Member Functions
void Awake ()
Acquires the anchorStore
void ResetData ()
Delete saved anchors, if there are any.
bool HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
bool DropAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
void WeighAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Private Member Functions
void Anchor ()
Private Attributes
Dictionary< string, Anchor > anchorStore
The collection in which anchors are stored. This value's type changes depending on certain compliation flags.
Detailed Description
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This component creates the native anchor type for any given subsystem, and save it to its native anchor store.
Definition at line 26 of file AnchorStore.cs.
Member Function Documentation
Anchor()
void Juniper.XR.AnchorStore.Anchor () private
Referenced by Juniper.XR.AnchorStore.DropAnchor(), and Juniper.XR.AnchorStore.WeighAnchor().
Awake()
void Juniper.XR.AnchorStore.Awake ()
Acquires the anchorStore
DropAnchor()
bool Juniper.XR.AnchorStore.DropAnchor (string ID, GameObject gameObject) inline
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
Returns
true, if anchor existed on the object, existed in the datastore, or was successfully created, false otherwise.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 99 of file AnchorStore.cs.
         {
             if (string.IsNullOrEmpty(ID))
             {
                 throw new ArgumentException("Parameter must have a value.", nameof(ID));
             }
             var scaleID = ID + "-scale";
 #if ARCORE
             var anchor = gameObject.Query<Anchor>("..");
 #elif ARKIT
             var anchor = gameObject.Query<UnityARUserAnchorComponent>("..");
 #elif HOLOLENS
             var anchor = gameObject.GetComponent<UnityEngine.XR.WSA.WorldAnchor>();
 #else
             var anchor = gameObject.GetComponent<MockWorldAnchor>();
 #endif
             if (anchor == null
 #if HOLOLENS
                 && anchorStore != null
 #endif
                )
             {
                 if (HasAnchor(ID))
                 {
 #if ARCORE || ARKIT
                     anchor = anchorStore[ID];
 #elif HOLOLENS
                     anchor = anchorStore.Load(ID, gameObject);
 #else
                     var anchorStr = PlayerPrefs.GetString(ID);
                     anchor = gameObject.AddComponent<MockWorldAnchor>();
                     var anchorState = JsonConvert.DeserializeObject<MockWorldAnchor.Pose>(anchorStr);
                     anchor.state = anchorState;
 #endif
                     if (PlayerPrefs.HasKey(scaleID))
                     {
                         gameObject.transform.localScale = JsonConvert.DeserializeObject<Vector3>(PlayerPrefs.GetString(scaleID));
                     }
                 }
                 else
                 {
 #if ARCORE
                     var pose = new Pose(
                         gameObject.transform.position,
                         gameObject.transform.rotation);
                     anchor = Session.CreateAnchor(pose);
                     anchorStore.Add(ID, anchor);
 #elif ARKIT
                     anchor = gameObject.AddComponent<UnityARUserAnchorComponent>();
                     anchorStore.Add(ID, anchor);
 #elif HOLOLENS
                     anchor = gameObject.AddComponent<UnityEngine.XR.WSA.WorldAnchor>();
                     anchorStore.Save(ID, anchor);
 #else
                     var t = gameObject.transform;
                     anchor = gameObject.AddComponent<MockWorldAnchor>();
                     anchor.state = new MockWorldAnchor.Pose
                     {
                         position = t.position,
                         rotation = t.rotation
                     };
                     PlayerPrefs.SetString(ID, JsonConvert.SerializeObject(anchor.state));
 #endif
                     PlayerPrefs.SetString(scaleID, JsonConvert.SerializeObject(gameObject.transform.localScale));
                 }
 #if ARCORE || ARKIT
                 if (anchor != null)
                 {
                     gameObject.transform.SetParent(anchor.transform, true);
                 }
 #endif
             }
 #if HOLOLENS
             return anchor != null && anchor.isLocated;
 #else
             return anchor != null;
 #endif
         }
References Juniper.XR.AnchorStore.Anchor(), Juniper.XR.AnchorStore.anchorStore, Juniper.XR.AnchorStore.HasAnchor(), Juniper.XR.MockWorldAnchor.Pose.position, and Juniper.XR.MockWorldAnchor.state.
Referenced by Juniper.XR.Anchored.DropAnchor().
HasAnchor()
bool Juniper.XR.AnchorStore.HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store. By default, Unity's PlayerPrefs KV store is used.
Returns
true, if anchor exists, false otherwise.
Parameters
anchorID Anchor identifier.
Referenced by Juniper.XR.AnchorStore.DropAnchor().
ResetData()
void Juniper.XR.AnchorStore.ResetData () inline
Delete saved anchors, if there are any.
Definition at line 63 of file AnchorStore.cs.
         {
             PlayerPrefs.DeleteAll();
             anchorStore?.Clear();
         }
References Juniper.XR.AnchorStore.anchorStore.
WeighAnchor()
void Juniper.XR.AnchorStore.WeighAnchor (string ID, GameObject gameObject) inline
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 194 of file AnchorStore.cs.
         {
 #if ARCORE
             var anchor = gameObject.Query<Anchor>("..");
 #elif ARKIT
             var anchor = gameObject.Query<UnityARUserAnchorComponent>("..");
 #elif HOLOLENS
             var anchor = gameObject.GetComponent<UnityEngine.XR.WSA.WorldAnchor>();
 #else
             var anchor = gameObject.GetComponent<MockWorldAnchor>();
 #endif
             if (anchor != null)
             {
 #if ARCORE || ARKIT
                 gameObject.transform.SetParent(anchor.transform.parent, true);
                 if (anchor.transform.childCount == 0)
                 {
                     anchorStore.Remove(ID);
                     anchor.gameObject.Destroy();
                 }
 #elif HOLOLENS
                 anchor.Destroy();
                 anchorStore.Delete(ID);
 #else
                 PlayerPrefs.DeleteKey(ID);
                 anchor.Destroy();
 #endif
                 PlayerPrefs.DeleteKey(ID + "-scale");
             }
         }
References Juniper.XR.AnchorStore.Anchor(), and Juniper.XR.AnchorStore.anchorStore.
Referenced by Juniper.XR.Anchored.WeighAnchor().
Member Data Documentation
anchorStore
Dictionary<string, Anchor> Juniper.XR.AnchorStore.anchorStore private
The collection in which anchors are stored. This value's type changes depending on certain compliation flags.
Definition at line 33 of file AnchorStore.cs.
Referenced by Juniper.XR.AnchorStore.DropAnchor(), Juniper.XR.AnchorStore.ResetData(), and Juniper.XR.AnchorStore.WeighAnchor().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/XR/AnchorStore.cs