Juniper: Juniper.ApplleiOS Class Reference
Juniper.ApplleiOS Class Reference
Static Public Member Functions
static void EnableARKit ()
static void DisableARKit ()
Properties
static Version? TargetOSVersion [get, set]
The PlayerSettings.iOS.targetOSVersionString value, exposed as a System.Version object.
static bool RequiresARKitSupport [get, set]
Gets are sets a value indicating ARKit support is required.
Static Private Member Functions
static void SetCompileFlags (string flags)
Private Attributes
const string REQUIRES_ARKIT_SUPPORT_KEY = "requiresARKitSupport"
The name of the hidden field within Unity's PlayerSettings for the ARKit Support checkbox.
Static Private Attributes
static readonly string PATH = PathExt.FixPath("Assets/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm")
Detailed Description
Definition at line 8 of file ApplleiOS.cs.
Member Function Documentation
DisableARKit()
static void Juniper.ApplleiOS.DisableARKit () inline static
Definition at line 22 of file ApplleiOS.cs.
         {
             SetCompileFlags("");
         }
References Juniper.ApplleiOS.SetCompileFlags().
EnableARKit()
static void Juniper.ApplleiOS.EnableARKit () inline static
Definition at line 17 of file ApplleiOS.cs.
         {
             SetCompileFlags("-DARKIT");
         }
References Juniper.ApplleiOS.SetCompileFlags().
SetCompileFlags()
static void Juniper.ApplleiOS.SetCompileFlags (string flags) inline static private
Definition at line 12 of file ApplleiOS.cs.
         {
             PluginImporterExt.SetPlatformData(PATH, BuildTarget.iOS, "CompileFlags", flags);
         }
References Juniper.ApplleiOS.PATH, and Juniper.PluginImporterExt.SetPlatformData().
Referenced by Juniper.ApplleiOS.DisableARKit(), and Juniper.ApplleiOS.EnableARKit().
Member Data Documentation
PATH
readonly string Juniper.ApplleiOS.PATH = PathExt.FixPath("Assets/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm") static private
Definition at line 10 of file ApplleiOS.cs.
Referenced by Juniper.ApplleiOS.SetCompileFlags().
REQUIRES_ARKIT_SUPPORT_KEY
const string Juniper.ApplleiOS.REQUIRES_ARKIT_SUPPORT_KEY = "requiresARKitSupport" private
The name of the hidden field within Unity's PlayerSettings for the ARKit Support checkbox.
We can see the existance of this property here: https://github.com/Unity-Technologies/UnityCsReference/blob/master/Editor/Mono/PlayerSettingsIOS.bindings.cs#L580-L587
Definition at line 47 of file ApplleiOS.cs.
Property Documentation
RequiresARKitSupport
bool Juniper.ApplleiOS.RequiresARKitSupport static get set
Gets are sets a value indicating ARKit support is required.
true if requires ARK it support; otherwise, false.
Definition at line 54 of file ApplleiOS.cs.
         {
             get
             {
                 return HiddenSettingsAccessor.GetHiddenStaticProperty<PlayerSettings.iOS, bool>(REQUIRES_ARKIT_SUPPORT_KEY);
             }
             set
             {
                 HiddenSettingsAccessor.SetHiddenStaticProperty<PlayerSettings.iOS>(REQUIRES_ARKIT_SUPPORT_KEY, value);
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperPackage.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.Deactivate().
TargetOSVersion
Version? Juniper.ApplleiOS.TargetOSVersion static get set
The PlayerSettings.iOS.targetOSVersionString value, exposed as a System.Version object.
The target OS Version.
Definition at line 31 of file ApplleiOS.cs.
         {
             get
             {
                 return new Version(PlayerSettings.iOS.targetOSVersionString);
             }
             set
             {
                 PlayerSettings.iOS.targetOSVersionString = value?.ToString(2);
             }
         }
Referenced by Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), and Juniper.ConfigurationManagement.PlatformConfiguration.GetCompilerDefines().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.UnityEditor/ApplleiOS.cs