Juniper: Juniper.Input.CameraControl Class Reference
Juniper.Input.CameraControl Class Reference
Public Types
enum Mode {
Mode.None, Mode.Auto, Mode.MouseLocked, Mode.MouseScreenEdge,
Mode.Gamepad, Mode.Touch, Mode.MagicWindow
}
Public Member Functions
void Awake ()
void Start ()
void Update ()
Public Attributes
Mode mode = Mode.Auto
InputEventButton requiredMouseButton = InputEventButton.None
bool showCustomCursor
int requiredTouchCount = 1
float dragThreshold = 2
bool disableHorizontal
bool disableVertical
float sensitivityX = 0.5f
How quickly the mouse moves horizontally
float sensitivityY = 0.5f
How quickly the mouse moves vertically
float minimumY = -45F
Minimum vertical value
float maximumY = 85F
Maximum vertical value
UnityEvent onModeChange
Properties
Vector2 AxialMovement [get]
Vector2 RadiusMovement [get]
Vector2 MeanTouchPointMovement [get]
Events
Action< Mode > ModeChange
Private Member Functions
void OnModeChange ()
bool GestureSatisfied (Mode mode)
Vector3 PointerMovement (Mode mode)
Quaternion OrientationDelta (Mode mode, bool disableVertical)
bool DragRequired (Mode mode)
bool DragSatisfied (Mode mode)
void CheckMouseLock ()
void CheckMode (Mode mode, bool disableVertical)
Private Attributes
Mode lastMode = Mode.None
const float MOUSE_SENSITIVITY_SCALE = 20
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
const float TOUCH_SENSITIVITY_SCALE = 0.5f
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
bool firstTime = true
Quaternion lastGyro = Quaternion.identity
Vector2 lastMousePosition
Avatar stage
readonly Dictionary< Mode, bool > wasGestureSatisfied = new Dictionary<Mode, bool>(7)
readonly Dictionary< Mode, bool > dragged = new Dictionary<Mode, bool>(7)
readonly Dictionary< Mode, float > dragDistance = new Dictionary<Mode, float>(7)
UnifiedInputModule input
const float EDGE_FACTOR = 0.8f
Static Private Attributes
static Quaternion NEUTRAL_POSITION_RESET = Quaternion.Euler(90f, 0f, 0f)
static Quaternion FLIP_IMAGE = Quaternion.Euler(0f, 0f, 180f)
Detailed Description
Definition at line 14 of file CameraControl.cs.
Member Enumeration Documentation
Mode
enum Juniper.Input.CameraControl.Mode strong
Enumerator
None
Auto
MouseLocked
MouseScreenEdge
Gamepad
Touch
MagicWindow
Definition at line 19 of file CameraControl.cs.
         {
             None,
             Auto,
             MouseLocked,
             MouseScreenEdge,
             Gamepad,
             Touch,
             MagicWindow
         }
Member Function Documentation
Awake()
void Juniper.Input.CameraControl.Awake () inline
Definition at line 98 of file CameraControl.cs.
         {
             stage = ComponentExt.FindAny<Avatar>();
             foreach (var m in Enum.GetValues(typeof(Mode)))
             {
                 var mode = (Mode)m;
                 wasGestureSatisfied[mode] = false;
                 dragged[mode] = false;
                 dragDistance[mode] = 0;
             }
             lastMousePosition = UnityInput.mousePosition;
 #if UNITY_EDITOR
             showCustomCursor = true;
 #endif
         }
References Juniper.Input.CameraControl.dragDistance, Juniper.Input.CameraControl.dragged, Juniper.Input.CameraControl.lastMousePosition, Juniper.Input.CameraControl.mode, Juniper.Input.CameraControl.showCustomCursor, Juniper.Input.CameraControl.stage, and Juniper.Input.CameraControl.wasGestureSatisfied.
CheckMode()
void Juniper.Input.CameraControl.CheckMode (Mode mode, bool disableVertical) inline private
Definition at line 362 of file CameraControl.cs.
         {
             var gest = GestureSatisfied(mode);
             var wasGest = wasGestureSatisfied[mode];
             if (gest)
             {
                 if (!wasGest)
                 {
                     dragged[mode] = false;
                     dragDistance[mode] = 0;
                 }
                 if (DragSatisfied(mode))
                 {
                     stage.RotateView(OrientationDelta(mode, disableVertical), minimumY, maximumY);
                 }
             }
             wasGestureSatisfied[mode] = gest;
         }
References Juniper.Input.CameraControl.disableVertical, Juniper.Input.CameraControl.dragDistance, Juniper.Input.CameraControl.dragged, Juniper.Input.CameraControl.DragSatisfied(), Juniper.Input.CameraControl.GestureSatisfied(), Juniper.Input.CameraControl.maximumY, Juniper.Input.CameraControl.minimumY, Juniper.Input.CameraControl.mode, Juniper.Input.CameraControl.OrientationDelta(), Juniper.Avatar.RotateView(), Juniper.Input.CameraControl.stage, and Juniper.Input.CameraControl.wasGestureSatisfied.
Referenced by Juniper.Input.CameraControl.Update().
CheckMouseLock()
void Juniper.Input.CameraControl.CheckMouseLock () inline private
Definition at line 292 of file CameraControl.cs.
         {
             if (mode == Mode.MouseLocked || mode == Mode.MouseScreenEdge)
             {
                 if (UnityInput.mousePresent && (firstTime || UnityInput.GetMouseButtonDown(0)))
                 {
                     firstTime = false;
                     if (mode == Mode.MouseLocked)
                     {
                         Cursor.lockState = CursorLockMode.Locked;
                     }
                     else
                     {
                         Cursor.lockState = CursorLockMode.Confined;
                     }
                 }
 #if UNITY_2018_1_OR_NEWER
                 else if (UnityInput.GetKeyDown(KeyCode.Escape))
                 {
                     Cursor.lockState = CursorLockMode.None;
                 }
 #endif
             }
             else if (Cursor.lockState != CursorLockMode.None)
             {
                 Cursor.lockState = CursorLockMode.None;
             }
             Cursor.visible = Cursor.lockState != CursorLockMode.Locked && !showCustomCursor;
         }
References Juniper.Input.CameraControl.firstTime, Juniper.Input.CameraControl.mode, and Juniper.Input.CameraControl.showCustomCursor.
Referenced by Juniper.Input.CameraControl.Update().
DragRequired()
bool Juniper.Input.CameraControl.DragRequired (Mode mode) inline private
Definition at line 267 of file CameraControl.cs.
         {
             return mode == Mode.Touch
                 || (mode == Mode.MouseLocked
                     && requiredMouseButton != InputEventButton.None);
         }
References Juniper.Input.CameraControl.mode, and Juniper.Input.CameraControl.requiredMouseButton.
Referenced by Juniper.Input.CameraControl.DragSatisfied().
DragSatisfied()
bool Juniper.Input.CameraControl.DragSatisfied (Mode mode) inline private
Definition at line 274 of file CameraControl.cs.
         {
             if (!DragRequired(mode))
             {
                 return true;
             }
             else
             {
                 var move = PointerMovement(mode);
                 if (!dragged[mode])
                 {
                     dragDistance[mode] += move.magnitude / Screen.dpi;
                     dragged[mode] = Units.Inches.Millimeters(dragDistance[mode]) > dragThreshold;
                 }
                 return dragged[mode];
             }
         }
References Juniper.Input.CameraControl.dragDistance, Juniper.Input.CameraControl.dragged, Juniper.Input.CameraControl.DragRequired(), Juniper.Input.CameraControl.dragThreshold, Juniper.Input.CameraControl.mode, and Juniper.Input.CameraControl.PointerMovement().
Referenced by Juniper.Input.CameraControl.CheckMode().
GestureSatisfied()
bool Juniper.Input.CameraControl.GestureSatisfied (Mode mode) inline private
Definition at line 122 of file CameraControl.cs.
         {
             if (mode == Mode.None)
             {
                 return false;
             }
             else if (mode == Mode.Gamepad || mode == Mode.MagicWindow)
             {
                 return true;
             }
             else if (mode == Mode.Touch)
             {
                 if (UnityInput.touchCount != requiredTouchCount)
                 {
                     return false;
                 }
                 else
                 {
                     var touchPhase = UnityInput.GetTouch(requiredTouchCount - 1).phase;
                     return touchPhase == TouchPhase.Moved
                         || touchPhase == TouchPhase.Stationary;
                 }
             }
             else
             {
                 var btn = (int)requiredMouseButton;
                 var pressed = requiredMouseButton == InputEventButton.None || UnityInput.GetMouseButton(btn);
                 var down = requiredMouseButton != InputEventButton.None && UnityInput.GetMouseButtonDown(btn);
                 return pressed && !down && (mode != Mode.MouseLocked || Cursor.lockState == CursorLockMode.Locked);
             }
         }
References Juniper.Input.CameraControl.mode, Juniper.Input.CameraControl.requiredMouseButton, and Juniper.Input.CameraControl.requiredTouchCount.
Referenced by Juniper.Input.CameraControl.CheckMode().
OnModeChange()
void Juniper.Input.CameraControl.OnModeChange () inline private
Definition at line 79 of file CameraControl.cs.
         {
             onModeChange?.Invoke();
             ModeChange?.Invoke(mode);
         }
References Juniper.Input.CameraControl.mode, Juniper.Input.CameraControl.ModeChange, and Juniper.Input.CameraControl.onModeChange.
Referenced by Juniper.Input.CameraControl.Update().
OrientationDelta()
Quaternion Juniper.Input.CameraControl.OrientationDelta (Mode mode, bool disableVertical) inline private
Definition at line 229 of file CameraControl.cs.
         {
             if (mode == Mode.MagicWindow)
             {
                 var endQuat = NEUTRAL_POSITION_RESET
                         * UnityInput.gyro.attitude
                         * FLIP_IMAGE;
                 var dRot = Quaternion.Inverse(lastGyro) * endQuat;
                 lastGyro = endQuat;
                 return dRot;
             }
             else
             {
                 var move = PointerMovement(mode);
                 if (disableVertical)
                 {
                     move.x = 0;
                 }
                 else
                 {
                     move.x *= sensitivityX;
                 }
                 if (disableHorizontal)
                 {
                     move.y = 0;
                 }
                 else
                 {
                     move.y *= sensitivityY;
                 }
                 move.z = 0;
                 return Quaternion.Euler(move);
             }
         }
References Juniper.Input.CameraControl.disableHorizontal, Juniper.Input.CameraControl.disableVertical, Juniper.Input.CameraControl.FLIP_IMAGE, Juniper.Input.CameraControl.lastGyro, Juniper.Input.CameraControl.mode, Juniper.Input.CameraControl.NEUTRAL_POSITION_RESET, Juniper.Input.CameraControl.PointerMovement(), Juniper.Input.CameraControl.sensitivityX, and Juniper.Input.CameraControl.sensitivityY.
Referenced by Juniper.Input.CameraControl.CheckMode().
PointerMovement()
Vector3 Juniper.Input.CameraControl.PointerMovement (Mode mode) inline private
Definition at line 154 of file CameraControl.cs.
         {
             switch (mode)
             {
                 case Mode.MouseLocked:
                 case Mode.Gamepad:
                 return AxialMovement;
                 case Mode.MouseScreenEdge:
                 return RadiusMovement;
                 case Mode.Touch:
                 return MeanTouchPointMovement;
                 default:
                 return Vector3.zero;
             }
         }
References Juniper.Input.CameraControl.AxialMovement, Juniper.Input.CameraControl.MeanTouchPointMovement, Juniper.Input.CameraControl.mode, and Juniper.Input.CameraControl.RadiusMovement.
Referenced by Juniper.Input.CameraControl.DragSatisfied(), and Juniper.Input.CameraControl.OrientationDelta().
Start()
void Juniper.Input.CameraControl.Start () inline
Definition at line 117 of file CameraControl.cs.
         {
             input = ComponentExt.FindAny<UnifiedInputModule>();
         }
References Juniper.Input.CameraControl.input.
Update()
void Juniper.Input.CameraControl.Update () inline
Definition at line 323 of file CameraControl.cs.
         {
             if (mode != lastMode)
             {
                 OnModeChange();
                 lastMode = mode;
             }
             CheckMouseLock();
             if (!input.AnyPointerDragging || Cursor.lockState == CursorLockMode.Locked)
             {
                 if (mode == Mode.MouseLocked && Cursor.lockState != CursorLockMode.Locked)
                 {
                     CheckMode(Mode.MouseScreenEdge, disableVertical);
                 }
                 else
                 {
                     CheckMode(mode, disableVertical);
                 }
                 if (mode == Mode.MagicWindow)
                 {
                     CheckMode(Mode.Touch, true);
                 }
                 else if (mode == Mode.Gamepad)
                 {
                     if (Application.isMobilePlatform)
                     {
                         CheckMode(Mode.Touch, disableVertical);
                     }
                     else
                     {
                         CheckMode(Mode.MouseLocked, disableVertical);
                     }
                 }
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.AnyPointerDragging, Juniper.Input.CameraControl.CheckMode(), Juniper.Input.CameraControl.CheckMouseLock(), Juniper.Input.CameraControl.disableVertical, Juniper.Input.CameraControl.input, Juniper.Input.CameraControl.lastMode, Juniper.Input.CameraControl.mode, and Juniper.Input.CameraControl.OnModeChange().
Member Data Documentation
disableHorizontal
bool Juniper.Input.CameraControl.disableHorizontal
Definition at line 38 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OrientationDelta().
disableVertical
bool Juniper.Input.CameraControl.disableVertical
Definition at line 39 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.CheckMode(), Juniper.Input.CameraControl.OrientationDelta(), and Juniper.Input.CameraControl.Update().
dragDistance
readonly Dictionary<Mode, float> Juniper.Input.CameraControl.dragDistance = new Dictionary<Mode, float>(7) private
Definition at line 94 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Awake(), Juniper.Input.CameraControl.CheckMode(), and Juniper.Input.CameraControl.DragSatisfied().
dragged
readonly Dictionary<Mode, bool> Juniper.Input.CameraControl.dragged = new Dictionary<Mode, bool>(7) private
Definition at line 93 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Awake(), Juniper.Input.CameraControl.CheckMode(), and Juniper.Input.CameraControl.DragSatisfied().
dragThreshold
float Juniper.Input.CameraControl.dragThreshold = 2
Definition at line 36 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.DragSatisfied().
EDGE_FACTOR
const float Juniper.Input.CameraControl.EDGE_FACTOR = 0.8f private
Definition at line 183 of file CameraControl.cs.
firstTime
bool Juniper.Input.CameraControl.firstTime = true private
Definition at line 85 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.CheckMouseLock().
FLIP_IMAGE
Quaternion Juniper.Input.CameraControl.FLIP_IMAGE = Quaternion.Euler(0f, 0f, 180f) static private
Definition at line 17 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OrientationDelta().
input
UnifiedInputModule Juniper.Input.CameraControl.input private
Definition at line 96 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Start(), and Juniper.Input.CameraControl.Update().
lastGyro
Quaternion Juniper.Input.CameraControl.lastGyro = Quaternion.identity private
Definition at line 87 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OrientationDelta().
lastMode
Mode Juniper.Input.CameraControl.lastMode = Mode.None private
Definition at line 31 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Update().
lastMousePosition
Vector2 Juniper.Input.CameraControl.lastMousePosition private
Definition at line 88 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Awake().
maximumY
float Juniper.Input.CameraControl.maximumY = 85F
Maximum vertical value
Definition at line 73 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.CheckMode().
minimumY
float Juniper.Input.CameraControl.minimumY = -45F
Minimum vertical value
Definition at line 68 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.CheckMode().
mode
Mode Juniper.Input.CameraControl.mode = Mode.Auto
Definition at line 30 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Awake(), Juniper.Input.CameraControl.CheckMode(), Juniper.Input.CameraControl.CheckMouseLock(), Juniper.Input.CameraControl.DragRequired(), Juniper.Input.CameraControl.DragSatisfied(), Juniper.Input.CameraControl.GestureSatisfied(), Juniper.Display.AbstractPassthroughDisplayManager.OnARModeChange(), Juniper.Input.CameraControl.OnModeChange(), Juniper.Input.CameraControl.OrientationDelta(), Juniper.Input.CameraControl.PointerMovement(), Juniper.Display.DefaultDisplayManager.Start(), Juniper.Display.DaydreamDisplayManager.Start(), and Juniper.Input.CameraControl.Update().
MOUSE_SENSITIVITY_SCALE
const float Juniper.Input.CameraControl.MOUSE_SENSITIVITY_SCALE = 20 private
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
Definition at line 45 of file CameraControl.cs.
NEUTRAL_POSITION_RESET
Quaternion Juniper.Input.CameraControl.NEUTRAL_POSITION_RESET = Quaternion.Euler(90f, 0f, 0f) static private
Definition at line 16 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OrientationDelta().
onModeChange
UnityEvent Juniper.Input.CameraControl.onModeChange
Definition at line 75 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OnModeChange().
requiredMouseButton
InputEventButton Juniper.Input.CameraControl.requiredMouseButton = InputEventButton.None
Definition at line 33 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.DragRequired(), and Juniper.Input.CameraControl.GestureSatisfied().
requiredTouchCount
int Juniper.Input.CameraControl.requiredTouchCount = 1
Definition at line 35 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.GestureSatisfied().
sensitivityX
float Juniper.Input.CameraControl.sensitivityX = 0.5f
How quickly the mouse moves horizontally
Definition at line 57 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OrientationDelta().
sensitivityY
float Juniper.Input.CameraControl.sensitivityY = 0.5f
How quickly the mouse moves vertically
Definition at line 63 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OrientationDelta().
showCustomCursor
bool Juniper.Input.CameraControl.showCustomCursor
Definition at line 34 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Awake(), and Juniper.Input.CameraControl.CheckMouseLock().
stage
Avatar Juniper.Input.CameraControl.stage private
Definition at line 90 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Awake(), and Juniper.Input.CameraControl.CheckMode().
TOUCH_SENSITIVITY_SCALE
const float Juniper.Input.CameraControl.TOUCH_SENSITIVITY_SCALE = 0.5f private
The mouse is not as sensitive as the motion controllers, so we have to bump up the sensitivity quite a bit.
Definition at line 51 of file CameraControl.cs.
wasGestureSatisfied
readonly Dictionary<Mode, bool> Juniper.Input.CameraControl.wasGestureSatisfied = new Dictionary<Mode, bool>(7) private
Definition at line 92 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.Awake(), and Juniper.Input.CameraControl.CheckMode().
Property Documentation
AxialMovement
Vector2 Juniper.Input.CameraControl.AxialMovement get private
Definition at line 174 of file CameraControl.cs.
         {
             get
             {
                 return MOUSE_SENSITIVITY_SCALE * new Vector2(
                     -UnityInput.GetAxis("Mouse Y"),
                     UnityInput.GetAxis("Mouse X"));
             }
         }
Referenced by Juniper.Input.CameraControl.PointerMovement().
MeanTouchPointMovement
Vector2 Juniper.Input.CameraControl.MeanTouchPointMovement get private
Definition at line 216 of file CameraControl.cs.
         {
             get
             {
                 var delta = Vector2.zero;
                 for (var i = 0; i < UnityInput.touchCount; ++i)
                 {
                     delta += UnityInput.GetTouch(i).deltaPosition / UnityInput.touchCount;
                 }
                 delta = new Vector2(delta.y, -delta.x);
                 return TOUCH_SENSITIVITY_SCALE * delta;
             }
         }
Referenced by Juniper.Input.CameraControl.PointerMovement().
RadiusMovement
Vector2 Juniper.Input.CameraControl.RadiusMovement get private
Definition at line 186 of file CameraControl.cs.
         {
             get
             {
                 var delta = new Vector2(UnityInput.GetAxisRaw("Mouse X"), UnityInput.GetAxis("Mouse Y"));
                 var trueMousePosition = lastMousePosition + delta;
                 var mousePosition = (Vector2)UnityInput.mousePosition;
                 lastMousePosition = mousePosition;
                 if (trueMousePosition.x >= 0
                     && trueMousePosition.x < Screen.width
                     && trueMousePosition.y >= 0
                     && trueMousePosition.y < Screen.height)
                 {
                     var viewport = 2 * new Vector2(
                         mousePosition.y / Screen.height,
                         mousePosition.x / Screen.width) - Vector2.one;
                     var square = viewport.Square2Round();
                     if (square.magnitude > EDGE_FACTOR)
                     {
                         viewport.x = (int)(viewport.x / -EDGE_FACTOR);
                         viewport.y = (int)(viewport.y / EDGE_FACTOR);
                         return viewport;
                     }
                 }
                 return Vector2.zero;
             }
         }
Referenced by Juniper.Input.CameraControl.PointerMovement().
Event Documentation
ModeChange
Action<Mode> Juniper.Input.CameraControl.ModeChange
Definition at line 77 of file CameraControl.cs.
Referenced by Juniper.Input.CameraControl.OnModeChange().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/CameraControl.cs