Juniper: Hjg.Pngcs.FileHelper Class Reference
Hjg.Pngcs.FileHelper Class Reference
A few utility static methods to read and write files
Static Public Member Functions
static Stream OpenFileForReading (String file)
static Stream OpenFileForWriting (String file, bool allowOverwrite)
static PngWriter CreatePngWriter (String fileName, ImageInfo imgInfo, bool allowOverwrite)
Given a filename and a ImageInfo, produces a PngWriter object, ready for writing.
static PngReader CreatePngReader (String fileName)
Given a filename, produces a PngReader object, ready for reading.
Detailed Description
A few utility static methods to read and write files
Definition at line 13 of file FileHelper.cs.
Member Function Documentation
CreatePngReader()
static PngReader Hjg.Pngcs.FileHelper.CreatePngReader (String fileName) inline static
Given a filename, produces a PngReader object, ready for reading.
Parameters
fileName Path of file
Returns
PngReader, ready for reading
Definition at line 47 of file FileHelper.cs.
{
             return new PngReader(OpenFileForReading(fileName), fileName);
         }
References Hjg.Pngcs.FileHelper.OpenFileForReading().
CreatePngWriter()
static PngWriter Hjg.Pngcs.FileHelper.CreatePngWriter (String fileName, ImageInfo imgInfo, bool allowOverwrite) inline static
Given a filename and a ImageInfo, produces a PngWriter object, ready for writing.
Parameters
fileName Path of file
imgInfo ImageInfo object
allowOverwrite Flag: if false and file exists, a PngjOutputException is thrown
Returns
A PngWriter object, ready for writing
Definition at line 37 of file FileHelper.cs.
{
             return new PngWriter(OpenFileForWriting(fileName, allowOverwrite), imgInfo,
                     fileName);
         }
References Hjg.Pngcs.FileHelper.OpenFileForWriting().
OpenFileForReading()
static Stream Hjg.Pngcs.FileHelper.OpenFileForReading (String file) inline static
Definition at line 15 of file FileHelper.cs.
{
             Stream isx = null;
             if (file == null || !File.Exists(file))
                 throw new PngjInputException("Cannot open file for reading (" + file + ")");
             isx = new FileStream(file, FileMode.Open);
             return isx;
         }
Referenced by Hjg.Pngcs.FileHelper.CreatePngReader().
OpenFileForWriting()
static Stream Hjg.Pngcs.FileHelper.OpenFileForWriting (String file, bool allowOverwrite) inline static
Definition at line 23 of file FileHelper.cs.
{
             Stream osx = null;
             if (File.Exists(file) && !allowOverwrite)
                 throw new PngjOutputException("File already exists (" + file + ") and overwrite=false");
             osx = new FileStream(file, FileMode.Create);
             return osx;
         }
Referenced by Hjg.Pngcs.FileHelper.CreatePngWriter().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/ThirdParty/Required/Hjg.Pngcs/FileHelper.cs