Juniper: Juniper.Units.Hertz Class Reference
Juniper.Units.Hertz Class Reference
Conversions from hertz
Static Public Member Functions
static float Nanoseconds (float hertz)
Convert from hertz to nanoseconds.
static float Ticks (float hertz)
Convert from hertz to ticks.
static float Microseconds (float hertz)
Convert from hertz to microseconds..
static float Milliseconds (float hertz)
Convert from hertz to milliseconds..
static float Minutes (float hertz)
Convert from hertz to minutes.
static float Hours (float hertz)
Convert from hertz to hours.
static float Days (float hertz)
Convert from hertz to days.
static float Seconds (float hertz)
Convert from hertz to seconds.
Detailed Description
Conversions from hertz
Definition at line 6 of file Hertz.cs.
Member Function Documentation
Days()
static float Juniper.Units.Hertz.Days (float hertz) inline static
Convert from hertz to days.
Parameters
hertz The number of hertz
Returns
The number of days
Definition at line 73 of file Hertz.cs.
         {
             return Seconds(Units.Days.Seconds(hertz));
         }
References Juniper.Units.Hertz.Seconds(), and Juniper.Units.Units.
Hours()
static float Juniper.Units.Hertz.Hours (float hertz) inline static
Convert from hertz to hours.
Parameters
hertz The number of hertz
Returns
The number of hours
Definition at line 63 of file Hertz.cs.
         {
             return Seconds(Units.Hours.Seconds(hertz));
         }
References Juniper.Units.Hertz.Seconds(), and Juniper.Units.Units.
Microseconds()
static float Juniper.Units.Hertz.Microseconds (float hertz) inline static
Convert from hertz to microseconds..
Parameters
hertz The number of hertz
Returns
The number of microseconds
Definition at line 33 of file Hertz.cs.
         {
             return Seconds(Units.Microseconds.Seconds(hertz));
         }
References Juniper.Units.Hertz.Seconds(), and Juniper.Units.Units.
Milliseconds()
static float Juniper.Units.Hertz.Milliseconds (float hertz) inline static
Convert from hertz to milliseconds..
Parameters
hertz The number of hertz
Returns
The number of milliseconds
Definition at line 43 of file Hertz.cs.
         {
             return Seconds(Units.Milliseconds.Seconds(hertz));
         }
References Juniper.Units.Hertz.Seconds(), and Juniper.Units.Units.
Minutes()
static float Juniper.Units.Hertz.Minutes (float hertz) inline static
Convert from hertz to minutes.
Parameters
hertz The number of hertz
Returns
The number of minutes
Definition at line 53 of file Hertz.cs.
         {
             return Seconds(Units.Minutes.Seconds(hertz));
         }
References Juniper.Units.Hertz.Seconds(), and Juniper.Units.Units.
Nanoseconds()
static float Juniper.Units.Hertz.Nanoseconds (float hertz) inline static
Convert from hertz to nanoseconds.
Parameters
hertz The number of hertz
Returns
The number of nanoseconds
Definition at line 13 of file Hertz.cs.
         {
             return Seconds(Units.Nanoseconds.Seconds(hertz));
         }
References Juniper.Units.Hertz.Seconds(), and Juniper.Units.Units.
Seconds()
static float Juniper.Units.Hertz.Seconds (float hertz) inline static
Convert from hertz to seconds.
Parameters
hertz The number of hertz
Returns
The number of seconds
Definition at line 83 of file Hertz.cs.
         {
             return 1 / hertz;
         }
Referenced by Juniper.Units.Hertz.Days(), Juniper.Units.Hertz.Hours(), Juniper.Units.Hertz.Microseconds(), Juniper.Units.Hertz.Milliseconds(), Juniper.Units.Hertz.Minutes(), Juniper.Units.Hertz.Nanoseconds(), and Juniper.Units.Hertz.Ticks().
Ticks()
static float Juniper.Units.Hertz.Ticks (float hertz) inline static
Convert from hertz to ticks.
Parameters
hertz The number of hertz
Returns
The number of ticks
Definition at line 23 of file Hertz.cs.
         {
             return Seconds(Units.Ticks.Seconds(hertz));
         }
References Juniper.Units.Hertz.Seconds(), and Juniper.Units.Units.
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Units/Frequency/Hertz.cs