Juniper: Juniper.Statistics.SingleStatistics Class Reference
Juniper.Statistics.SingleStatistics Class Reference abstract
Computes statistics on System.Single values.
Public Member Functions
SingleStatistics (IList< float > collection)
Initializes a new instance of the T:Juniper.Statistics.SingleStatistics class.
SingleStatistics (int capacity)
Create a RingBuffer of floats of a fixed size. RingBuffers aren't resizable. Statistical values default to null.
IEnumerator< T > GetEnumerator ()
Returns an enumerator that iterates through the collection.
void Add (T item)
Adds an item to the collection, and recalculates the statistical values.
void AddRange (IEnumerable< T > collect)
void Clear ()
Clears the collection and resets the statistics to null.
bool Contains (T item)
Returns true if the give item is in the collection.
void CopyTo (T[] array, int arrayIndex)
Copies the elements of the collection to an Array, starting at a particular Array index.
bool Remove (T item)
Remove an item from the collection.
int IndexOf (T item)
Determines the index of the specified item in the underlying collection.
void Insert (int index, T item)
Insert an item at an arbitrary point in the collection.
void RemoveAt (int index)
Remove an item at the specified index from the collection.
bool Append (T value, int numStandardDeviations, int minSamples=2)
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Public Attributes
int Count
Returns the number of items in the collection.
bool IsReadOnly
Gets a value indicating whether this T:Juniper.Statistics.AbstractCollectionStatistics`1 is read only.
T? Delta
The difference between the Maximum and Minimum
T? Median
The midpoint between the Maximum and the Minimum
Protected Member Functions
override float Abs (float value)
override float Add (float a, float b)
override float Divide (float a, float b)
override bool LessThan (float a, float b)
override float Multiply (float a, float b)
override float Scale (float a, float b)
override float Sqrt (float value)
override float Subtract (float a, float b)
abstract T Add (T a, T b)
void RecomputeStatistics ()
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
void UpdateStatistics (T value)
abstract T Subtract (T a, T b)
abstract T Multiply (T a, T b)
abstract T Scale (T a, float b)
abstract T Divide (T a, float b)
abstract T Sqrt (T value)
abstract T Abs (T value)
abstract bool LessThan (T a, T b)
Properties
T? Maximum [get, protected set]
The maximum value in the collection (calculated during collection modification)
T? Minimum [get, protected set]
The minimum value in the collection (calculated during collection modification)
T? Mean [get, protected set]
The arithmetic mean of the values in the collection (calculated during collection modification)
T? Variance [get, protected set]
The square of the standard deviation of the values in the collection (calculated during collection modification)
T? StandardDeviation [get, protected set]
The standard deviation of the values in the collection (calculated during collection modification)
bool IsSaturated [get]
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
T this[int index] [get, set]
Gets or sets the element at the specified index.
Detailed Description
Computes statistics on System.Single values.
Definition at line 11 of file SingleStatistics.cs.
Constructor & Destructor Documentation
SingleStatistics() [1/2]
Juniper.Statistics.SingleStatistics.SingleStatistics (IList< float > collection) inline
Initializes a new instance of the T:Juniper.Statistics.SingleStatistics class.
Parameters
collection Collection.
Definition at line 17 of file SingleStatistics.cs.
             : base(collection, 0, 1)
         {
         }
SingleStatistics() [2/2]
Juniper.Statistics.SingleStatistics.SingleStatistics (int capacity) inline
Create a RingBuffer of floats of a fixed size. RingBuffers aren't resizable. Statistical values default to null.
Parameters
capacity
Definition at line 27 of file SingleStatistics.cs.
             : base(capacity, 0, 1)
         {
         }
Member Function Documentation
Abs() [1/2]
override float Juniper.Statistics.SingleStatistics.Abs (float value) protected
Abs() [2/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Abs (T value) protected pure virtual inherited
Add() [1/3]
override float Juniper.Statistics.SingleStatistics.Add (float a, float b) protected
Referenced by Juniper.World.CompassRose.SetNorth(), Juniper.Statistics.SingleStatisticsTests.ShiftsOldValuesOut(), and Juniper.Widgets.Shaker.Update().
Add() [2/3]
void Juniper.Statistics.AbstractCollectionStatistics< T >.Add (T item) inline inherited
Adds an item to the collection, and recalculates the statistical values.
Parameters
item
Definition at line 184 of file AbstractCollectionStatistics.cs.
         {
             collect.Add(item);
             UpdateStatistics(item);
         }
Add() [3/3]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Add (T a, T b) protected pure virtual inherited
AddRange()
void Juniper.Statistics.AbstractCollectionStatistics< T >.AddRange (IEnumerable< T > collect) inline inherited
Definition at line 190 of file AbstractCollectionStatistics.cs.
         {
             foreach (var v in collect)
             {
                 Add(v);
             }
         }
Append()
bool Juniper.Statistics.AbstractCollectionStatistics< T >.Append (T value, int numStandardDeviations, int minSamples = 2) inline inherited
Adds an item to the collection, if that item is within a set number of standard deviations of the rest of the collection, and updates the statistical values.
Parameters
value
numStandardDeviations
minSamples The minimum number of collected samples in the collection to have before rejecting outliers. MinSamples must be at least 2.
Returns
True if the item was added, false if it was rejected.
Definition at line 296 of file AbstractCollectionStatistics.cs.
         {
             var delta = Abs(Subtract(value, Mean));
             var isInlier = Count < 2
                 || Count < minSamples
                 || LessThan(delta, Scale(StandardDeviation, numStandardDeviations));
             if (isInlier)
             {
                 Add(value);
             }
             return isInlier;
         }
Clear()
void Juniper.Statistics.AbstractCollectionStatistics< T >.Clear () inline inherited
Clears the collection and resets the statistics to null.
Definition at line 201 of file AbstractCollectionStatistics.cs.
         {
             collect.Clear();
             RecomputeStatistics();
         }
Contains()
bool Juniper.Statistics.AbstractCollectionStatistics< T >.Contains (T item) inherited
Returns true if the give item is in the collection.
Parameters
item The item to search for.
Returns
True if the item is found. False if it is not.
CopyTo()
void Juniper.Statistics.AbstractCollectionStatistics< T >.CopyTo (T [] array, int arrayIndex) inherited
Copies the elements of the collection to an Array, starting at a particular Array index.
Parameters
array The one-dimensional Array that is the destination of the elements copied from ICollection{T}. The Array must have zero-based indexing.
arrayIndex The zero-based index in array at which copying begins.
Exceptions
System.ArgumentNullException array is null
System.ArgumentException The number of elements to copy from the source ICollection{T} is greater than the available space from arrayIndex to the end of the destination array .
Divide() [1/2]
override float Juniper.Statistics.SingleStatistics.Divide (float a, float b) protected
Divide() [2/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Divide (T a, float b) protected pure virtual inherited
GetEnumerator()
IEnumerator<T> Juniper.Statistics.AbstractCollectionStatistics< T >.GetEnumerator () inherited
Returns an enumerator that iterates through the collection.
Returns
IndexOf()
int Juniper.Statistics.AbstractCollectionStatistics< T >.IndexOf (T item) inherited
Determines the index of the specified item in the underlying collection.
Parameters
item The object to location in the collection.
Returns
The index of item if found in the list; otherwise, -1.
If an object occurs multiple times in the list, the IndexOf method always returns the first instance found.
Insert()
void Juniper.Statistics.AbstractCollectionStatistics< T >.Insert (int index, T item) inline inherited
Insert an item at an arbitrary point in the collection.
Parameters
index The index at which to insert item .
item The value to insert.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
Definition at line 266 of file AbstractCollectionStatistics.cs.
         {
             collect.Insert(index, item);
             UpdateStatistics(item);
         }
LessThan() [1/2]
override bool Juniper.Statistics.SingleStatistics.LessThan (float a, float b) protected
LessThan() [2/2]
abstract bool Juniper.Statistics.AbstractCollectionStatistics< T >.LessThan (T a, T b) protected pure virtual inherited
Multiply() [1/2]
override float Juniper.Statistics.SingleStatistics.Multiply (float a, float b) protected
Multiply() [2/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Multiply (T a, T b) protected pure virtual inherited
RecomputeStatistics()
void Juniper.Statistics.AbstractCollectionStatistics< T >.RecomputeStatistics () inline protected inherited
Figure out the minimum, maximum, median, mean, and standard deviation of the values in the collection (if there are enough).
Definition at line 345 of file AbstractCollectionStatistics.cs.
         {
             Maximum = Minimum = Mean = Variance = StandardDeviation = null;
             if (Count > 0)
             {
                 Minimum = Scale(One, float.MaxValue);
                 Maximum = Scale(One, float.MinValue);
                 Mean = Zero;
                 foreach (var v in this)
                 {
                     Minimum = Min(Minimum, v);
                     Maximum = Max(Maximum, v);
                     Mean = Add(Mean, Divide(v, Count));
                 }
                 if (Count > 1)
                 {
                     Variance = Zero;
                     foreach (var v in this)
                     {
                         var residual = Subtract(v, Mean);
                         Variance = Add(Variance, Divide(Multiply(residual, residual), Count - 1));
                     }
                     StandardDeviation = Sqrt(Variance);
                 }
             }
         }
Remove()
bool Juniper.Statistics.AbstractCollectionStatistics< T >.Remove (T item) inline inherited
Remove an item from the collection.
Parameters
item The value to remove.
Returns
True if the item existed in the buffer and was removed. False otherwise.
Definition at line 239 of file AbstractCollectionStatistics.cs.
         {
             var removed = collect.Remove(item);
             RecomputeStatistics();
             return removed;
         }
RemoveAt()
void Juniper.Statistics.AbstractCollectionStatistics< T >.RemoveAt (int index) inline inherited
Remove an item at the specified index from the collection.
Parameters
index The index at which to remove an item.
Exceptions
System.ArgumentOutOfRangeException index is less than 0 or greater than Count - 1.
Definition at line 279 of file AbstractCollectionStatistics.cs.
         {
             collect.RemoveAt(index);
             RecomputeStatistics();
         }
Scale() [1/2]
override float Juniper.Statistics.SingleStatistics.Scale (float a, float b) protected
Scale() [2/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Scale (T a, float b) protected pure virtual inherited
Sqrt() [1/2]
override float Juniper.Statistics.SingleStatistics.Sqrt (float value) protected
Sqrt() [2/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Sqrt (T value) protected pure virtual inherited
Subtract() [1/2]
override float Juniper.Statistics.SingleStatistics.Subtract (float a, float b) protected
Subtract() [2/2]
abstract T Juniper.Statistics.AbstractCollectionStatistics< T >.Subtract (T a, T b) protected pure virtual inherited
UpdateStatistics()
void Juniper.Statistics.AbstractCollectionStatistics< T >.UpdateStatistics (T value) inline protected inherited
Definition at line 375 of file AbstractCollectionStatistics.cs.
         {
             Minimum = Min(Minimum, value);
             Maximum = Max(Maximum, value);
             var prevMean = Mean;
             var residual = Subtract(value, prevMean);
             Mean = Add(prevMean, Divide(residual, Count));
             if (Count > 1)
             {
                 var secondResidual = Subtract(value, Mean);
                 var n2 = Count - 2;
                 var n1 = Count - 1;
                 Variance = Divide(
                     Add(
                         Scale(Variance, n2),
                         Multiply(residual, secondResidual)),
                     n1);
                 StandardDeviation = Sqrt(Variance);
             }
         }
Member Data Documentation
Count
int Juniper.Statistics.AbstractCollectionStatistics< T >.Count inherited
Returns the number of items in the collection.
Definition at line 111 of file AbstractCollectionStatistics.cs.
Delta
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Delta inherited
The difference between the Maximum and Minimum
Definition at line 144 of file AbstractCollectionStatistics.cs.
IsReadOnly
bool Juniper.Statistics.AbstractCollectionStatistics< T >.IsReadOnly inherited
Gets a value indicating whether this T:Juniper.Statistics.AbstractCollectionStatistics`1 is read only.
true if is read only; otherwise, false.
Definition at line 138 of file AbstractCollectionStatistics.cs.
Median
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Median inherited
The midpoint between the Maximum and the Minimum
Definition at line 150 of file AbstractCollectionStatistics.cs.
Property Documentation
IsSaturated
bool Juniper.Statistics.AbstractCollectionStatistics< T >.IsSaturated get inherited
Returns true if the underlying collection is a RingBuffer and if that RingBuffer RingBuffer<T>.IsSaturated.
true if is saturated; otherwise, false.
Definition at line 118 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (collect is RingBuffer<T>)
                 {
                     var buf = (RingBuffer<T>)collect;
                     return buf.IsSaturated;
                 }
                 else
                 {
                     return false;
                 }
             }
         }
Maximum
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Maximum get protected set inherited
The maximum value in the collection (calculated during collection modification)
Definition at line 16 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (max == null)
                 {
                     RecomputeStatistics();
                 }
                 return max;
             }
             protected set
             {
                 max = value;
             }
         }
Mean
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Mean get protected set inherited
The arithmetic mean of the values in the collection (calculated during collection modification)
Definition at line 54 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (mean == null)
                 {
                     RecomputeStatistics();
                 }
                 return mean;
             }
             protected set
             {
                 mean = value;
             }
         }
Minimum
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Minimum get protected set inherited
The minimum value in the collection (calculated during collection modification)
Definition at line 35 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (min == null)
                 {
                     RecomputeStatistics();
                 }
                 return min;
             }
             protected set
             {
                 min = value;
             }
         }
StandardDeviation
T? Juniper.Statistics.AbstractCollectionStatistics< T >.StandardDeviation get protected set inherited
The standard deviation of the values in the collection (calculated during collection modification)
Definition at line 93 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (standardDev == null)
                 {
                     RecomputeStatistics();
                 }
                 return standardDev;
             }
             protected set
             {
                 standardDev = value;
             }
         }
this[int index]
T Juniper.Statistics.AbstractCollectionStatistics< T >.this[int index] get set inherited
Gets or sets the element at the specified index.
Parameters
index An index into the buffer, modulated by the buffer length.
Exceptions
System.ArgumentOutOfRangeException If index is less than 0, or greater than Count - 1.
The element at the specified index.
Definition at line 162 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 return collect[index];
             }
             set
             {
                 collect[index] = value;
             }
         }
Variance
T? Juniper.Statistics.AbstractCollectionStatistics< T >.Variance get protected set inherited
The square of the standard deviation of the values in the collection (calculated during collection modification)
Definition at line 74 of file AbstractCollectionStatistics.cs.
         {
             get
             {
                 if (variance == null)
                 {
                     RecomputeStatistics();
                 }
                 return variance;
             }
             protected set
             {
                 variance = value;
             }
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Common/Statistics/SingleStatistics.cs