Juniper: Juniper.UnityEditor.PluginImporterExt.iOS.ARKit Class Reference
Juniper.UnityEditor.PluginImporterExt.iOS.ARKit Class Reference
Static Public Member Functions
static void Enable ()
static void Disable ()
Static Private Member Functions
static void SetCompileFlags (string flags)
Static Private Attributes
static readonly string PATH = PathExt.FixPath("Assets/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm")
Detailed Description
Definition at line 20 of file PluginImporterExt.cs.
Member Function Documentation
Disable()
static void Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.Disable () inline static
Definition at line 34 of file PluginImporterExt.cs.
                 {
                     SetCompileFlags("");
                 }
References Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags().
Enable()
static void Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.Enable () inline static
Definition at line 29 of file PluginImporterExt.cs.
                 {
                     SetCompileFlags("-DARKIT");
                 }
References Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags().
SetCompileFlags()
static void Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags (string flags) inline static private
Definition at line 24 of file PluginImporterExt.cs.
                 {
                     SetPlatformData(PATH, BuildTarget.iOS, "CompileFlags", flags);
                 }
References Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.PATH, and Juniper.UnityEditor.PluginImporterExt.SetPlatformData().
Referenced by Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.Disable(), and Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.Enable().
Member Data Documentation
PATH
readonly string Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.PATH = PathExt.FixPath("Assets/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm") static private
Definition at line 22 of file PluginImporterExt.cs.
Referenced by Juniper.UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Editor/PluginImporterExt.cs