Juniper: Juniper.Unity.Animation.AbstractTransitionController Class Reference
Juniper.Unity.Animation.AbstractTransitionController Class Reference abstract
Child classes of this class are able to animate transitions between program states.
Classes
class ValueChangedEventArgs
Changes in the transition value can be captured in other scripts by subscribing to the ValueChanged event. This EventArgs object includes both the old and the new value.
Public Member Functions
override void Enter ()
Fire the OnEnable event and perform the Enter transition.
override void SkipEnter ()
override void Exit ()
Fire the OnExiting event and perform the Exit transition.
override void Update ()
If the transition is currently in the running state, update its internal value according to its TransitionLength.
bool HasStopped ()
virtual void SkipExit ()
void OnEnable ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
void OnDisable ()
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Public Attributes
float attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
float releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
UnityEvent onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
TweenType tween
The method to use to pre-compute the transition value.
float tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
UnityEvent onEntering = new UnityEvent()
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
UnityEvent onEntered = new UnityEvent()
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
UnityEvent onExiting = new UnityEvent()
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
UnityEvent onExited = new UnityEvent()
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Protected Member Functions
abstract void RenderValue (float value)
Child implementations of TransitionController must implement this abstract method to receive the transformed progress value (tweenedValue) and realize it in the effect of the transition.
virtual void OnEnabled ()
virtual void OnDisabled ()
virtual void OnEntering ()
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
virtual void OnEntered ()
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
virtual void OnExiting ()
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
virtual void OnExited ()
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Protected Attributes
const int ENTERING = 1
const int STOPPED = 0
const int EXITING = -1
int state
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Properties
abstract float TransitionLength [get]
The length of time, in seconds, the transition should take to complete.
virtual bool IsComplete [get]
bool IsRunning [get]
WaitUntil Waiter [get]
Events
EventHandler< ValueChangedEventArgs > ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
EventHandler Entering
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
EventHandler Entered
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
EventHandler Exiting
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
EventHandler Exited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Private Member Functions
void OnValueChanged (float final, float initial)
Override this method in child classes to implement the animation of the transition.
void SetProgress (float nextProgress)
Calls the tweening function and propogates the value to the implementing class.
void StartTransition (int nextState)
Set the transition into the running state.
Private Attributes
Func< float, float, float, float > tweenFunc
The function that performs the 'tweening.
float attack
The amount of time to delay before starting a transition.
float release
The amount of time after the end of a transition to delay the signal that it has finished.
float progress
The current proportion of progress through the transition. If the TransitionLength is 0, the progress is immediately complete. It will be 1 on completion when ascending and 0 on completion when descending.
float tweenedValue
The progress value after the tweenFunc transformation.
Detailed Description
Child classes of this class are able to animate transitions between program states.
Definition at line 11 of file AbstractTransitionController.cs.
Member Function Documentation
Enter()
override void Juniper.Unity.Animation.AbstractTransitionController.Enter () inline virtual
Fire the OnEnable event and perform the Enter transition.
Reimplemented from Juniper.Unity.AbstractStateController.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 60 of file AbstractTransitionController.cs.
         {
             StartTransition(ENTERING);
             base.Enter();
         }
References Juniper.Unity.AbstractStateController.ENTERING, and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.Widgets.Openable.SetOpen(), and Juniper.Unity.Animation.WorkflowStep.Show().
Exit()
override void Juniper.Unity.Animation.AbstractTransitionController.Exit () inline virtual
Fire the OnExiting event and perform the Exit transition.
Reimplemented from Juniper.Unity.AbstractStateController.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 74 of file AbstractTransitionController.cs.
         {
             StartTransition(EXITING);
             base.Exit();
         }
References Juniper.Unity.AbstractStateController.EXITING, and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.Widgets.Openable.SetOpen().
HasStopped()
bool Juniper.Unity.AbstractStateController.HasStopped () inline inherited
Definition at line 105 of file AbstractStateController.cs.
         {
             return IsComplete;
         }
References Juniper.Unity.AbstractStateController.IsComplete.
OnDisable()
void Juniper.Unity.AbstractStateController.OnDisable () inline inherited
Called as the object goes from Active to Inactive. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 173 of file AbstractStateController.cs.
         {
             OnDisabled();
         }
References Juniper.Unity.AbstractStateController.OnDisabled().
OnDisabled()
virtual void Juniper.Unity.AbstractStateController.OnDisabled () inline protected virtual inherited
Reimplemented in Juniper.Unity.SubSceneController.
Definition at line 233 of file AbstractStateController.cs.
         {
             if (!skipEvent)
             {
                 OnExited();
             }
         }
References Juniper.Unity.AbstractStateController.OnExited(), and Juniper.Unity.AbstractStateController.skipEvent.
Referenced by Juniper.Unity.AbstractStateController.OnDisable().
OnEnable()
void Juniper.Unity.AbstractStateController.OnEnable () inline inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 162 of file AbstractStateController.cs.
         {
             OnEnabled();
         }
References Juniper.Unity.AbstractStateController.OnEnabled().
Referenced by Juniper.Unity.AbstractStateController.Enter().
OnEnabled()
virtual void Juniper.Unity.AbstractStateController.OnEnabled () inline protected virtual inherited
Reimplemented in Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 225 of file AbstractStateController.cs.
         {
             if (!skipEvent)
             {
                 OnEntering();
             }
         }
References Juniper.Unity.AbstractStateController.OnEntering(), and Juniper.Unity.AbstractStateController.skipEvent.
Referenced by Juniper.Unity.AbstractStateController.OnEnable().
OnEntered()
virtual void Juniper.Unity.AbstractStateController.OnEntered () inline protected virtual inherited
Calls the onEntered and Entered events, if they are valid. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Reimplemented in Juniper.Unity.Animation.FadeTransition.
Definition at line 260 of file AbstractStateController.cs.
         {
             onEntered?.Invoke();
             Entered?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Unity.AbstractStateController.Entered, and Juniper.Unity.AbstractStateController.onEntered.
Referenced by Juniper.Unity.AbstractStateController.Update().
OnEntering()
virtual void Juniper.Unity.AbstractStateController.OnEntering () inline protected virtual inherited
Called as the object goes from Inactive to Active. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 247 of file AbstractStateController.cs.
         {
             onEntering?.Invoke();
             Entering?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Unity.AbstractStateController.Entering, and Juniper.Unity.AbstractStateController.onEntering.
Referenced by Juniper.Unity.AbstractStateController.OnEnabled().
OnExited()
virtual void Juniper.Unity.AbstractStateController.OnExited () inline protected virtual inherited
Calls the onExited and Exited events, if they are valid. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExited method.
Definition at line 286 of file AbstractStateController.cs.
         {
             onExited?.Invoke();
             Exited?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Unity.AbstractStateController.Exited, and Juniper.Unity.AbstractStateController.onExited.
Referenced by Juniper.Unity.AbstractStateController.OnDisabled().
OnExiting()
virtual void Juniper.Unity.AbstractStateController.OnExiting () inline protected virtual inherited
Calls the onExiting and Exiting events, if they are valid. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Reimplemented in Juniper.Unity.Animation.FadeTransition, Juniper.Unity.Animation.SpiralTransition, and Juniper.Unity.Widgets.VideoVader.
Definition at line 273 of file AbstractStateController.cs.
         {
             onExiting?.Invoke();
             Exiting?.Invoke(this, EventArgs.Empty);
         }
References Juniper.Unity.AbstractStateController.Exiting, and Juniper.Unity.AbstractStateController.onExiting.
Referenced by Juniper.Unity.AbstractStateController.Exit().
OnValueChanged()
void Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged (float final, float initial) inline private
Override this method in child classes to implement the animation of the transition.
Parameters
final
initial
Definition at line 179 of file AbstractTransitionController.cs.
         {
             ValueChanged?.Invoke(this, new ValueChangedEventArgs(initial, final));
             onValueChanged?.Invoke();
         }
References Juniper.Unity.Animation.AbstractTransitionController.onValueChanged, and Juniper.Unity.Animation.AbstractTransitionController.ValueChanged.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
RenderValue()
abstract void Juniper.Unity.Animation.AbstractTransitionController.RenderValue (float value) protected pure virtual
Child implementations of TransitionController must implement this abstract method to receive the transformed progress value (tweenedValue) and realize it in the effect of the transition.
Parameters
value Value.
Implemented in Juniper.Unity.Animation.FadeTransition, Juniper.Unity.Widgets.VideoVader, Juniper.Unity.Animation.SpiralTransition, Juniper.Unity.Animation.TranslationTransition, Juniper.Unity.Animation.AlphaTransition, and Juniper.Unity.Animation.ScaleTransition.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
SetProgress()
void Juniper.Unity.Animation.AbstractTransitionController.SetProgress (float nextProgress) inline private
Calls the tweening function and propogates the value to the implementing class.
Parameters
nextProgress The current progress through the transition.
Definition at line 189 of file AbstractTransitionController.cs.
         {
             progress = nextProgress;
             var oldTweenedValue = tweenedValue;
             var value = state == EXITING ? progress : (1 - progress);
             tweenedValue = tweenFunc(value, tweenK, state);
             OnValueChanged(tweenedValue, oldTweenedValue);
             RenderValue(tweenedValue);
         }
References Juniper.Unity.AbstractStateController.EXITING, Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged(), Juniper.Unity.Animation.AbstractTransitionController.progress, Juniper.Unity.Animation.AbstractTransitionController.RenderValue(), Juniper.Unity.AbstractStateController.state, Juniper.Unity.Animation.AbstractTransitionController.tweenedValue, Juniper.Unity.Animation.AbstractTransitionController.tweenFunc, and Juniper.Unity.Animation.AbstractTransitionController.tweenK.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SkipEnter(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
SkipEnter()
override void Juniper.Unity.Animation.AbstractTransitionController.SkipEnter () inline virtual
Reimplemented from Juniper.Unity.AbstractStateController.
Definition at line 66 of file AbstractTransitionController.cs.
         {
             StartTransition(ENTERING);
             base.SkipEnter();
             SetProgress(0);
         }
References Juniper.Unity.AbstractStateController.ENTERING, Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
Referenced by Juniper.Unity.MasterSceneController.FadeOut().
SkipExit()
virtual void Juniper.Unity.AbstractStateController.SkipExit () inline virtual inherited
Definition at line 146 of file AbstractStateController.cs.
         {
             skipEvent = true;
             Exit();
             Update();
             state = STOPPED;
             Update();
             skipEvent = false;
         }
References Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.AbstractStateController.skipEvent, Juniper.Unity.AbstractStateController.state, Juniper.Unity.AbstractStateController.STOPPED, and Juniper.Unity.AbstractStateController.Update().
StartTransition()
void Juniper.Unity.Animation.AbstractTransitionController.StartTransition (int nextState) inline private
Set the transition into the running state.
Parameters
nextState True, if this is an Enter transition. False, if this is an Exit transition.
Definition at line 207 of file AbstractTransitionController.cs.
         {
             state = nextState;
             attack = state == ENTERING ? attackTime : releaseTime;
             release = (state == ENTERING ? releaseTime : attackTime);
             tweenFunc = Tween.Functions[tween];
             SetProgress(1);
         }
References Juniper.Unity.Animation.AbstractTransitionController.attack, Juniper.Unity.Animation.AbstractTransitionController.attackTime, Juniper.Unity.AbstractStateController.ENTERING, Juniper.Unity.Animation.Tween.Functions, Juniper.Unity.Animation.AbstractTransitionController.release, Juniper.Unity.Animation.AbstractTransitionController.releaseTime, Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.state, Juniper.Unity.Animation.AbstractTransitionController.tween, and Juniper.Unity.Animation.AbstractTransitionController.tweenFunc.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.Enter(), Juniper.Unity.Animation.AbstractTransitionController.Exit(), and Juniper.Unity.Animation.AbstractTransitionController.SkipEnter().
Update()
override void Juniper.Unity.Animation.AbstractTransitionController.Update () inline virtual
If the transition is currently in the running state, update its internal value according to its TransitionLength.
Reimplemented from Juniper.Unity.AbstractStateController.
Reimplemented in Juniper.Unity.Animation.SpiralTransition.
Definition at line 84 of file AbstractTransitionController.cs.
         {
             if (IsRunning)
             {
                 if (attack > 0)
                 {
                     attack -= Time.deltaTime;
                 }
                 else if (progress > 0)
                 {
                     var change = Time.deltaTime / TransitionLength;
                     SetProgress(Mathf.Clamp01(progress - change));
                 }
                 else if (release > 0)
                 {
                     release -= Time.deltaTime;
                 }
                 else
                 {
                     SetProgress(0);
                     state = STOPPED;
                 }
             }
             base.Update();
         }
References Juniper.Unity.Animation.AbstractTransitionController.attack, Juniper.Unity.AbstractStateController.IsRunning, Juniper.Unity.Animation.AbstractTransitionController.progress, Juniper.Unity.Animation.AbstractTransitionController.release, Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.state, Juniper.Unity.AbstractStateController.STOPPED, and Juniper.Unity.Animation.AbstractTransitionController.TransitionLength.
Member Data Documentation
attack
float Juniper.Unity.Animation.AbstractTransitionController.attack private
The amount of time to delay before starting a transition.
Definition at line 155 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
attackTime
float Juniper.Unity.Animation.AbstractTransitionController.attackTime
The amount of time to delay before starting the transition. Remember that the exit is just the reverse of the enter transition, so the attackTime for the enter transition is the releaseTime for the exit.
Definition at line 18 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
ENTERING
const int Juniper.Unity.AbstractStateController.ENTERING = 1 protected inherited
Definition at line 195 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.Enter(), Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.Animation.AbstractTransitionController.SkipEnter(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.AbstractStateController.Update().
EXITING
const int Juniper.Unity.AbstractStateController.EXITING = -1 protected inherited
Definition at line 199 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.Exit(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.AbstractStateController.Update().
onEntered
UnityEvent Juniper.Unity.AbstractStateController.onEntered = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 33 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntered().
onEntering
UnityEvent Juniper.Unity.AbstractStateController.onEntering = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 24 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
onExited
UnityEvent Juniper.Unity.AbstractStateController.onExited = new UnityEvent() inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 51 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExited().
onExiting
UnityEvent Juniper.Unity.AbstractStateController.onExiting = new UnityEvent() inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 42 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
onValueChanged
UnityEvent Juniper.Unity.Animation.AbstractTransitionController.onValueChanged = new UnityEvent()
Attach event handlers in the Unity Editor to this field to receive notification when the transition has updated.
Definition at line 31 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
progress
float Juniper.Unity.Animation.AbstractTransitionController.progress private
The current proportion of progress through the transition. If the TransitionLength is 0, the progress is immediately complete. It will be 1 on completion when ascending and 0 on completion when descending.
Definition at line 167 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
release
float Juniper.Unity.Animation.AbstractTransitionController.release private
The amount of time after the end of a transition to delay the signal that it has finished.
Definition at line 160 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
releaseTime
float Juniper.Unity.Animation.AbstractTransitionController.releaseTime
The amount of time to delay after ending the transition. Remember that the exit is just the reverse of the enter transition, so the releaseTime for the enter transition is the attackTime for the exit.
Definition at line 25 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
state
int Juniper.Unity.AbstractStateController.state protected inherited
Whether or not the transition is running in the forward or backward direction (which is important for Fade(in|out) and Shrink(in|out) transitions).
Definition at line 223 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.Enter(), Juniper.Unity.AbstractStateController.Exit(), Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.Animation.AbstractTransitionController.StartTransition(), Juniper.Unity.SubSceneController.Update(), Juniper.Unity.Animation.AbstractTransitionController.Update(), and Juniper.Unity.AbstractStateController.Update().
STOPPED
const int Juniper.Unity.AbstractStateController.STOPPED = 0 protected inherited
Definition at line 197 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.SkipEnter(), Juniper.Unity.AbstractStateController.SkipExit(), Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
tween
TweenType Juniper.Unity.Animation.AbstractTransitionController.tween
The method to use to pre-compute the transition value.
Definition at line 36 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
tweenedValue
float Juniper.Unity.Animation.AbstractTransitionController.tweenedValue private
The progress value after the tweenFunc transformation.
Definition at line 172 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
tweenFunc
Func<float, float, float, float> Juniper.Unity.Animation.AbstractTransitionController.tweenFunc private
The function that performs the 'tweening.
Definition at line 150 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress(), and Juniper.Unity.Animation.AbstractTransitionController.StartTransition().
tweenK
float Juniper.Unity.Animation.AbstractTransitionController.tweenK
The constant value to provide to the tweening function. Currently, only the Bump tween function uses this value.
Definition at line 43 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.SetProgress().
Property Documentation
IsComplete
virtual bool Juniper.Unity.AbstractStateController.IsComplete get inherited
Definition at line 90 of file AbstractStateController.cs.
         {
             get
             {
                 return state == STOPPED;
             }
         }
Referenced by Juniper.Unity.AbstractStateController.HasStopped(), and Juniper.Unity.AbstractStateController.Update().
IsRunning
bool Juniper.Unity.AbstractStateController.IsRunning get inherited
Definition at line 98 of file AbstractStateController.cs.
         {
             get
             {
                 return !IsComplete;
             }
         }
Referenced by Juniper.Unity.SubSceneController.Update(), and Juniper.Unity.Animation.AbstractTransitionController.Update().
TransitionLength
abstract float Juniper.Unity.Animation.AbstractTransitionController.TransitionLength get
The length of time, in seconds, the transition should take to complete.
Definition at line 55 of file AbstractTransitionController.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Animation.AbstractTransitionController.Update().
Waiter
WaitUntil Juniper.Unity.AbstractStateController.Waiter get inherited
Definition at line 204 of file AbstractStateController.cs.
         {
             get
             {
                 if (_waiter == null)
                 {
                     _waiter = new WaitUntil(() => IsComplete);
                 }
                 else
                 {
                     _waiter.Reset();
                 }
                 return _waiter;
             }
         }
Referenced by Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
Event Documentation
Entered
EventHandler Juniper.Unity.AbstractStateController.Entered inherited
An event that occurs when the controller has finished going through the Enter transition. Prefer Entered if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntered. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEntered method.
Definition at line 69 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), Juniper.Unity.AbstractStateController.OnEntered(), and Juniper.Unity.Widgets.TeleportPad.Start().
Entering
EventHandler Juniper.Unity.AbstractStateController.Entering inherited
An event that occurs when the controller is starting to go through the Enter transition. Prefer Entering if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onEntering. If you are waiting for this event in a subclass of StateController, prefer overriding the OnEnable method.
Definition at line 60 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnEntering().
Exited
EventHandler Juniper.Unity.AbstractStateController.Exited inherited
An event that occurs when the controller has finished going through the Exit transition. Prefer Exited if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExited. If you are waiting for this event in a subclass of StateController, prefer overriding the OnDisable method.
Definition at line 87 of file AbstractStateController.cs.
Referenced by Juniper.Unity.Animation.FadeTransition.Awake(), and Juniper.Unity.AbstractStateController.OnExited().
Exiting
EventHandler Juniper.Unity.AbstractStateController.Exiting inherited
An event that occurs when the controller is starting to go through the Exit transition. Prefer Exiting if you are programmatically adding event handlers at runtime. If you are adding event handlers in the Unity Editor, prefer onExiting. If you are waiting for this event in a subclass of StateController, prefer overriding the OnExiting method.
Definition at line 78 of file AbstractStateController.cs.
Referenced by Juniper.Unity.AbstractStateController.OnExiting().
ValueChanged
EventHandler<ValueChangedEventArgs> Juniper.Unity.Animation.AbstractTransitionController.ValueChanged
Attach event handlers at runtime to this field to receive notification when the transition has updated.
Definition at line 49 of file AbstractTransitionController.cs.
Referenced by Juniper.Unity.Animation.AbstractTransitionController.OnValueChanged().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Animation/AbstractTransitionController.cs