Juniper: UnityEngine.ColorExt Class Reference
UnityEngine.ColorExt Class Reference
Extension methods for Color and float that convert to Color.
Static Public Member Functions
static Color FromKelvinToColor (this float val)
Converts a whitebalance value to a color value that can be used with a Light object.
static Color Scale (this Color rgb, float intensity)
Converts a color to HSV, scales the V, and converts back to RGB
static Color GetGrayscalePixel (this byte[] buffer, int i)
Converts a value in a byte buffer into a grayscale color.
static Color GetRGB565Pixel (this byte[] buffer, int i)
Converts two values in a byte buffer into a 16-bit color.
static Color GetRGB888Pixel (this byte[] buffer, int i)
Converts three values in a byte buffer into a 24-bit color.
static Color GetYUVPixel (this byte[] buffer, int i)
Converts three values in a byte buffer into a YUV color.
static HSVColor ToHSVColor (this Color c)
Convert an RGB color to an HSV color.
static Color ToColor (this HSVColor hsv, bool hdr=false)
Convert an HSV color to an RGB color.
Static Public Attributes
static Color TransparentBlack = new Color(0, 0, 0, 0)
Detailed Description
Extension methods for Color and float that convert to Color.
Definition at line 13 of file ColorExt.cs.
Member Function Documentation
FromKelvinToColor()
static Color UnityEngine.ColorExt.FromKelvinToColor (this float val) inline static
Converts a whitebalance value to a color value that can be used with a Light object.
Parameters
val
Returns
Definition at line 23 of file ColorExt.cs.
         {
             var t = val / 100f;
             float r, g, b;
             if (t <= 66)
             {
                 r = 255;
             }
             else
             {
                 r = t - 60;
                 r = 329.698727446f * Mathf.Pow(r, -0.1332047592f);
             }
             if (t <= 66)
             {
                 g = t;
                 g = 99.4708025861f * Mathf.Log(g) - 161.1195681661f;
             }
             else
             {
                 g = t - 60;
                 g = 288.1221695283f * Mathf.Pow(g, -0.0755148492f);
             }
             if (t >= 66)
             {
                 b = 255;
             }
             else if (t <= 19)
             {
                 b = 0;
             }
             else
             {
                 b = t - 10;
                 b = 138.5177312231f * Mathf.Log(b) - 305.0447927307f;
             }
             r = Mathf.Clamp(r, 0, 255) / 255;
             g = Mathf.Clamp(g, 0, 255) / 255;
             b = Mathf.Clamp(b, 0, 255) / 255;
             return new Color(r, g, b);
         }
GetGrayscalePixel()
static Color UnityEngine.ColorExt.GetGrayscalePixel (this byte [] buffer, int i) inline static
Converts a value in a byte buffer into a grayscale color.
Returns
The grayscale pixel.
Parameters
buffer Buffer.
i The index.
Definition at line 89 of file ColorExt.cs.
         {
             var r = buffer[i];
             return new Color(r / 255f, r / 255f, r / 255f);
         }
GetRGB565Pixel()
static Color UnityEngine.ColorExt.GetRGB565Pixel (this byte [] buffer, int i) inline static
Converts two values in a byte buffer into a 16-bit color.
Returns
The RGB 565 pixel.
Parameters
buffer Buffer.
i The index.
Definition at line 101 of file ColorExt.cs.
         {
             byte high = buffer[i],
                 low = buffer[i + 1];
             float r = high >> 3,
                 g = (0x08 & high) << 3 | (0xE0 & low) >> 5,
                 b = 0x01F & low;
             return new Color(r / 0x1F, g / 0x3F, b / 0x1F);
         }
GetRGB888Pixel()
static Color UnityEngine.ColorExt.GetRGB888Pixel (this byte [] buffer, int i) inline static
Converts three values in a byte buffer into a 24-bit color.
Returns
The RGB 888 pixel.
Parameters
buffer Buffer.
i The index.
Definition at line 117 of file ColorExt.cs.
         {
             byte r = buffer[i],
                 g = buffer[i + 1],
                 b = buffer[i + 2];
             return new Color(r / 255f, g / 255f, b / 255f);
         }
GetYUVPixel()
static Color UnityEngine.ColorExt.GetYUVPixel (this byte [] buffer, int i) inline static
Converts three values in a byte buffer into a YUV color.
Returns
The YUVP ixel.
Parameters
buffer Buffer.
i The index.
Definition at line 131 of file ColorExt.cs.
         {
             int y = buffer[i] - 16,
                 u = buffer[i + 1] - 128,
                 v = buffer[i + 2] - 128,
                 r = (int)(1.164f * y + 1.596f * v),
                 g = (int)(1.164f * y - 0.813f * u - 0.392 * v),
                 b = (int)(1.164f * y + 2.017f * u);
             return new Color(r / 255f, g / 255f, b / 255f);
         }
Scale()
static Color UnityEngine.ColorExt.Scale (this Color rgb, float intensity) inline static
Converts a color to HSV, scales the V, and converts back to RGB
Parameters
rgb
intensity
Returns
Definition at line 76 of file ColorExt.cs.
         {
             float h, s, v;
             Color.RGBToHSV(rgb, out h, out s, out v);
             return Color.HSVToRGB(h, s, v * intensity);
         }
ToColor()
static Color UnityEngine.ColorExt.ToColor (this HSVColor hsv, bool hdr = false) inline static
Convert an HSV color to an RGB color.
Returns
The color.
Parameters
hsv Hsv.
hdr If set to true hdr.
Definition at line 160 of file ColorExt.cs.
         {
             Color c;
             if (hdr)
             {
                 c = Color.HSVToRGB(
                     Mathf.Repeat(hsv.h, 1),
                     hsv.s,
                     hsv.v,
                     true);
             }
             else
             {
                 c = Color.HSVToRGB(
                     Mathf.Repeat(hsv.h, 1),
                     Mathf.Clamp01(hsv.s),
                     Mathf.Clamp01(hsv.v));
             }
             c.a = hsv.a;
             return c;
         }
References Juniper.HSVColor.a, Juniper.HSVColor.h, Juniper.HSVColor.s, and Juniper.HSVColor.v.
ToHSVColor()
static HSVColor UnityEngine.ColorExt.ToHSVColor (this Color c) inline static
Convert an RGB color to an HSV color.
Returns
The color.
Parameters
c C.
Definition at line 146 of file ColorExt.cs.
         {
             HSVColor value;
             Color.RGBToHSV(c, out value.h, out value.s, out value.v);
             value.a = c.a;
             return value;
         }
References Juniper.HSVColor.a, Juniper.HSVColor.h, Juniper.HSVColor.s, and Juniper.HSVColor.v.
Member Data Documentation
TransparentBlack
Color UnityEngine.ColorExt.TransparentBlack = new Color(0, 0, 0, 0) static
Definition at line 15 of file ColorExt.cs.
Referenced by Juniper.XRSystem.ChangeARMode(), Juniper.Animation.FadeTransition.OnEntered(), and Juniper.Input.Pointers.Probe.Start().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Extensions/UnityEngine/ColorExt.cs