Juniper: Juniper.World.GIS.EquitorialSphericalPosition Struct Reference
Juniper.World.GIS.EquitorialSphericalPosition Struct Reference
Represents a bearing and distance to an object from the Earth's equator.
Public Member Functions
EquitorialSphericalPosition (float alpha, float delta, float R)
Create a new bearing to an object.
void GetObjectData (SerializationInfo info, StreamingContext context)
Get serialization data from the object.
HorizontalSphericalPosition ToHorizontal (LatLngPoint location, float n)
Convert Equitorial Spherical Position to Horizontal Spherical Position.
Public Attributes
readonly float RightAscensionDegrees
The number of degrees from the Earth's prime azimuth at which to find the object.
readonly float DeclinationDegrees
The number of degrees above the Earth's equator at which to find the object.
readonly float RadiusAU
The distance in Astronomical Units from the earth at which to find the object.
Private Member Functions
EquitorialSphericalPosition (SerializationInfo info, StreamingContext context)
Deserialze the object.
Detailed Description
Represents a bearing and distance to an object from the Earth's equator.
Definition at line 10 of file EquitorialSphericalPosition.cs.
Constructor & Destructor Documentation
EquitorialSphericalPosition() [1/2]
Juniper.World.GIS.EquitorialSphericalPosition.EquitorialSphericalPosition (float alpha, float delta, float R) inline
Create a new bearing to an object.
Parameters
alpha The right ascension to the object, in degrees
delta The declination to the object, in degrees.
R The radius to the object, in Astronomical Units
Definition at line 33 of file EquitorialSphericalPosition.cs.
         {
             RightAscensionDegrees = alpha;
             DeclinationDegrees = delta;
             RadiusAU = R;
         }
References Juniper.World.GIS.EquitorialSphericalPosition.DeclinationDegrees, Juniper.World.GIS.EquitorialSphericalPosition.RadiusAU, and Juniper.World.GIS.EquitorialSphericalPosition.RightAscensionDegrees.
EquitorialSphericalPosition() [2/2]
Juniper.World.GIS.EquitorialSphericalPosition.EquitorialSphericalPosition (SerializationInfo info, StreamingContext context) inline private
Deserialze the object.
Parameters
info
context
Definition at line 45 of file EquitorialSphericalPosition.cs.
         {
             RightAscensionDegrees = info.GetSingle(nameof(RightAscensionDegrees));
             DeclinationDegrees = info.GetSingle(nameof(DeclinationDegrees));
             RadiusAU = info.GetSingle(nameof(RadiusAU));
         }
References Juniper.World.GIS.EquitorialSphericalPosition.DeclinationDegrees, Juniper.World.GIS.EquitorialSphericalPosition.RadiusAU, and Juniper.World.GIS.EquitorialSphericalPosition.RightAscensionDegrees.
Member Function Documentation
GetObjectData()
void Juniper.World.GIS.EquitorialSphericalPosition.GetObjectData (SerializationInfo info, StreamingContext context) inline
Get serialization data from the object.
Parameters
info
context
Definition at line 57 of file EquitorialSphericalPosition.cs.
         {
             info.AddValue(nameof(RightAscensionDegrees), RightAscensionDegrees);
             info.AddValue(nameof(DeclinationDegrees), DeclinationDegrees);
             info.AddValue(nameof(RadiusAU), RadiusAU);
         }
References Juniper.World.GIS.EquitorialSphericalPosition.DeclinationDegrees, Juniper.World.GIS.EquitorialSphericalPosition.RadiusAU, and Juniper.World.GIS.EquitorialSphericalPosition.RightAscensionDegrees.
ToHorizontal()
HorizontalSphericalPosition Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal (LatLngPoint location, float n) inline
Convert Equitorial Spherical Position to Horizontal Spherical Position.
Parameters
location The point on earth
n The Julian day
Returns
The elevation above the horizon
Definition at line 70 of file EquitorialSphericalPosition.cs.
         {
             var GMST = Units.Repeat(18.697374558f + 24.06570982441908f * n, 24);
             var LST = GMST + Units.Degrees.Hours(location.Longitude);
             var RA = Units.Degrees.Hours(RightAscensionDegrees);
             var H = Units.Hours.Radians(LST - RA);
             var sin_H = Math.Sin(H);
             var cos_H = Math.Cos(H);
             var lat_rad = Units.Degrees.Radians(location.Latitude);
             // var lng_rad = lng_deg * Math.Deg2Rad;
             var delta_rad = Units.Degrees.Radians(DeclinationDegrees);
             var sin_delta = Math.Sin(delta_rad);
             var cos_delta = Math.Cos(delta_rad);
             var sin_lat = Math.Sin(lat_rad);
             var cos_lat = Math.Cos(lat_rad);
             var sin_alt = sin_delta * sin_lat + cos_delta * cos_lat * cos_H;
             var cos_alt = Math.Sqrt(1 - sin_alt * sin_alt);
             var sin_azm = sin_H * cos_delta / cos_alt;
             var cos_azm = (sin_delta - sin_lat * sin_alt) / (cos_lat * cos_alt);
             var altitude_rad = (float)Math.Atan2(sin_alt, cos_alt);
             var azimuth_rad = (float)Math.Atan2(sin_azm, cos_azm);
             return new HorizontalSphericalPosition(
                 Units.Radians.Degrees(altitude_rad),
                 Units.Repeat(180 - Units.Radians.Degrees(azimuth_rad), 360),
                 RadiusAU);
         }
References Juniper.World.GIS.EquitorialSphericalPosition.DeclinationDegrees, Juniper.Units.Radians.Degrees(), Juniper.Units.Degrees.Hours(), Juniper.World.GIS.LatLngPoint.Latitude, Juniper.World.GIS.LatLngPoint.Longitude, Juniper.Units.Degrees.Radians(), Juniper.Units.Hours.Radians(), Juniper.World.GIS.EquitorialSphericalPosition.RadiusAU, Juniper.Units.Repeat(), and Juniper.World.GIS.EquitorialSphericalPosition.RightAscensionDegrees.
Referenced by Juniper.Units.LatLng.SunPosition().
Member Data Documentation
DeclinationDegrees
readonly float Juniper.World.GIS.EquitorialSphericalPosition.DeclinationDegrees
The number of degrees above the Earth's equator at which to find the object.
Definition at line 20 of file EquitorialSphericalPosition.cs.
Referenced by Juniper.World.GIS.EquitorialSphericalPosition.EquitorialSphericalPosition(), Juniper.World.GIS.EquitorialSphericalPosition.GetObjectData(), and Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal().
RadiusAU
readonly float Juniper.World.GIS.EquitorialSphericalPosition.RadiusAU
The distance in Astronomical Units from the earth at which to find the object.
Definition at line 25 of file EquitorialSphericalPosition.cs.
Referenced by Juniper.World.GIS.EquitorialSphericalPosition.EquitorialSphericalPosition(), Juniper.World.GIS.EquitorialSphericalPosition.GetObjectData(), and Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal().
RightAscensionDegrees
readonly float Juniper.World.GIS.EquitorialSphericalPosition.RightAscensionDegrees
The number of degrees from the Earth's prime azimuth at which to find the object.
Definition at line 15 of file EquitorialSphericalPosition.cs.
Referenced by Juniper.World.GIS.EquitorialSphericalPosition.EquitorialSphericalPosition(), Juniper.World.GIS.EquitorialSphericalPosition.GetObjectData(), and Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal().
The documentation for this struct was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper.Units/src/Geo/EquitorialSphericalPosition.cs