Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter Class Reference
Colorspace conversion
Public Member Functions
JpegColorDeconverter (JpegDecompressStruct cinfo)
Module initialization routine for output colorspace conversion.
void ColorConvert (ComponentBuffer[] input_buf, int[] perComponentOffsets, int input_row, byte[][] output_buf, int output_row, int num_rows)
Private Member Functions
delegate void color_convert_func (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
void BuildYccRgbTable ()
Initialize tables for YCbCr->RGB colorspace conversion.
void BuildBgYccRgbTable ()
Initialize tables for BG_YCC->RGB colorspace conversion.
void YccRgbConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
void BuildRgbYTable ()
void RgbGrayConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
void Rgb1RgbConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
void Rgb1GrayConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
void RgbConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
void YcckCmykConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
Adobe-style YCCK->CMYK conversion. We convert YCbCr to R=1-C, G=1-M, and B=1-Y using the same conversion as above, while passing K (black) unchanged. We assume build_ycc_rgb_table has been called.
void GrayRgbConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
Convert grayscale to RGB: just duplicate the graylevel three times. This is provided to support applications that don't want to cope with grayscale as a separate case.
void GrayscaleConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
Color conversion for grayscale: just copy the data. This also works for YCC -> grayscale conversion, in which we just copy the Y (luminance) component and ignore chrominance.
void CmykRgbConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
Color conversion for CMYK -> RGB
void YcckRgbConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
Color conversion for YCCK -> RGB it's just a gybrid of YCCK -> CMYK and CMYK -> RGB conversions
void NullConvert (ComponentBuffer[] input_buf, int input_row, byte[][] output_buf, int output_row, int num_rows)
Color conversion for no colorspace change: just copy the data, converting from separate-planes to interleaved representation.
Static Private Member Functions
static int FIX (double x)
Private Attributes
const int SCALEBITS = 16
const int ONE_HALF = 1 << (SCALEBITS - 1)
const int R_Y_OFF = 0
const int G_Y_OFF = (1 * (JpegConstants.MAXJSAMPLE + 1))
const int B_Y_OFF = (2 * (JpegConstants.MAXJSAMPLE + 1))
const int TABLE_SIZE = (3 * (JpegConstants.MAXJSAMPLE + 1))
readonly color_convert_func m_converter
readonly JpegDecompressStruct m_cinfo
int [] m_perComponentOffsets
int [] m_Cr_r_tab
int [] m_Cb_b_tab
int [] m_Cr_g_tab
int [] m_Cb_g_tab
int [] rgb_y_tab
Detailed Description
Colorspace conversion
Definition at line 10 of file JpegColorDeconverter.cs.
Constructor & Destructor Documentation
JpegColorDeconverter()
BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter (JpegDecompressStruct cinfo) inline
Module initialization routine for output colorspace conversion.
Definition at line 46 of file JpegColorDeconverter.cs.
         {
             m_cinfo = cinfo;
             /* Make sure num_components agrees with jpeg_color_space */
             switch (cinfo.jpegColorSpace)
             {
                 case JColorSpace.JCS_GRAYSCALE:
                 if (cinfo.numComponents != 1)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_J_COLORSPACE);
                 }
                 break;
                 case JColorSpace.JCS_RGB:
                 case JColorSpace.JCS_YCbCr:
                 case JColorSpace.JCS_BG_RGB:
                 case JColorSpace.JCS_BG_YCC:
                 if (cinfo.numComponents != 3)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_J_COLORSPACE);
                 }
                 break;
                 case JColorSpace.JCS_CMYK:
                 case JColorSpace.JCS_YCCK:
                 if (cinfo.numComponents != 4)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_J_COLORSPACE);
                 }
                 break;
                 case JColorSpace.JCS_NCHANNEL:
                 if (cinfo.numComponents < 1)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_J_COLORSPACE);
                 }
                 break;
                 default:
                 /* JCS_UNKNOWN can be anything */
                 if (cinfo.numComponents < 1)
                 {
                     cinfo.ErrExit(JMessageCode.JERR_BAD_J_COLORSPACE);
                 }
                 break;
             }
             /* Support color transform only for RGB colorspaces */
             if (cinfo.color_transform != JColorTransform.JCT_NONE &&
                 cinfo.jpegColorSpace != JColorSpace.JCS_RGB &&
                 cinfo.jpegColorSpace != JColorSpace.JCS_BG_RGB)
             {
                 cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
             }
             /* Set out_color_components and conversion method based on requested space.
             * Also clear the component_needed flags for any unused components,
             * so that earlier pipeline stages can avoid useless computation.
             */
             switch (cinfo.outColorSpace)
             {
                 case JColorSpace.JCS_GRAYSCALE:
                 cinfo.outColorComponents = 1;
                 switch (cinfo.jpegColorSpace)
                 {
                     case JColorSpace.JCS_GRAYSCALE:
                     case JColorSpace.JCS_YCbCr:
                     case JColorSpace.JCS_BG_YCC:
                     m_converter = GrayscaleConvert;
                     /* For color->grayscale conversion, only the Y (0) component is needed */
                     for (var ci = 1; ci < cinfo.numComponents; ci++)
                     {
                         cinfo.CompInfo[ci].component_needed = false;
                     }
                     break;
                     case JColorSpace.JCS_RGB:
                     switch (cinfo.color_transform)
                     {
                         case JColorTransform.JCT_NONE:
                         m_converter = RgbGrayConvert;
                         break;
                         case JColorTransform.JCT_SUBTRACT_GREEN:
                         m_converter = Rgb1GrayConvert;
                         break;
                         default:
                         cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                         break;
                     }
                     BuildRgbYTable();
                     break;
                     default:
                     cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                     break;
                 }
                 break;
                 case JColorSpace.JCS_RGB:
                 cinfo.outColorComponents = JpegConstants.RGB_PIXELSIZE;
                 switch (cinfo.jpegColorSpace)
                 {
                     case JColorSpace.JCS_GRAYSCALE:
                     m_converter = GrayRgbConvert;
                     break;
                     case JColorSpace.JCS_YCbCr:
                     m_converter = YccRgbConvert;
                     BuildYccRgbTable();
                     break;
                     case JColorSpace.JCS_BG_YCC:
                     m_converter = YccRgbConvert;
                     BuildBgYccRgbTable();
                     break;
                     case JColorSpace.JCS_RGB:
                     switch (cinfo.color_transform)
                     {
                         case JColorTransform.JCT_NONE:
                         m_converter = RgbConvert;
                         break;
                         case JColorTransform.JCT_SUBTRACT_GREEN:
                         m_converter = Rgb1RgbConvert;
                         break;
                         default:
                         cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                         break;
                     }
                     break;
                     case JColorSpace.JCS_CMYK:
                     m_converter = CmykRgbConvert;
                     break;
                     case JColorSpace.JCS_YCCK:
                     m_converter = YcckRgbConvert;
                     BuildYccRgbTable();
                     break;
                     default:
                     cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                     break;
                 }
                 break;
                 case JColorSpace.JCS_BG_RGB:
                 cinfo.outColorComponents = JpegConstants.RGB_PIXELSIZE;
                 if (cinfo.jpegColorSpace == JColorSpace.JCS_BG_RGB)
                 {
                     switch (cinfo.color_transform)
                     {
                         case JColorTransform.JCT_NONE:
                         m_converter = RgbConvert;
                         break;
                         case JColorTransform.JCT_SUBTRACT_GREEN:
                         m_converter = Rgb1RgbConvert;
                         break;
                         default:
                         cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                         break;
                     }
                 }
                 else
                 {
                     cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                 }
                 break;
                 case JColorSpace.JCS_CMYK:
                 cinfo.outColorComponents = 4;
                 switch (cinfo.jpegColorSpace)
                 {
                     case JColorSpace.JCS_YCCK:
                     m_converter = YcckCmykConvert;
                     BuildYccRgbTable();
                     break;
                     case JColorSpace.JCS_CMYK:
                     m_converter = NullConvert;
                     break;
                     default:
                     cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                     break;
                 }
                 break;
                 case JColorSpace.JCS_NCHANNEL:
                 if (cinfo.jpegColorSpace == JColorSpace.JCS_NCHANNEL)
                 {
                     m_converter = NullConvert;
                 }
                 else
                 {
                     cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                 }
                 break;
                 default:
                 /* Permit null conversion to same output space */
                 if (cinfo.outColorSpace == cinfo.jpegColorSpace)
                 {
                     cinfo.outColorComponents = cinfo.numComponents;
                     m_converter = NullConvert;
                 }
                 else
                 {
                     /* unsupported non-null conversion */
                     cinfo.ErrExit(JMessageCode.JERR_CONVERSION_NOTIMPL);
                 }
                 break;
             }
             if (cinfo.quantizeColors)
             {
                 cinfo.outputComponents = 1; /* single colormapped output component */
             }
             else
             {
                 cinfo.outputComponents = cinfo.outColorComponents;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.CmykRgbConvert(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.color_transform, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.CompInfo, BitMiracle.LibJpeg.Classic.JpegComponentInfo.component_needed, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayRgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayscaleConvert(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.jpegColorSpace, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_converter, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.NullConvert(), BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outColorSpace, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputComponents, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.quantizeColors, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1RgbConvert(), BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
Member Function Documentation
BuildBgYccRgbTable()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable () inline private
Initialize tables for BG_YCC->RGB colorspace conversion.
Definition at line 392 of file JpegColorDeconverter.cs.
         {
             /* Wide gamut case, bg-sYCC */
             m_Cr_r_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_b_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cr_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             for (int i = 0, x = -JpegConstants.CENTERJSAMPLE; i <= JpegConstants.MAXJSAMPLE; i++, x++)
             {
                 /* i is the actual input pixel value, in the range 0..MAXJSAMPLE */
                 /* The Cb or Cr value we are thinking of is x = i - CENTERJSAMPLE */
                 /* Cr=>R value is nearest int to 2.804 * x */
                 m_Cr_r_tab[i] = JpegUtils.RIGHT_SHIFT((FIX(2.804) * x) + ONE_HALF, SCALEBITS);
                 /* Cb=>B value is nearest int to 3.544 * x */
                 m_Cb_b_tab[i] = JpegUtils.RIGHT_SHIFT((FIX(3.544) * x) + ONE_HALF, SCALEBITS);
                 /* Cr=>G value is scaled-up -1.428272572 * x */
                 m_Cr_g_tab[i] = -FIX(1.428272572) * x;
                 /* Cb=>G value is scaled-up -0.688272572 * x */
                 /* We also add in ONE_HALF so that need not do it in inner loop */
                 m_Cb_g_tab[i] = (-FIX(0.688272572) * x) + ONE_HALF;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.FIX(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.ONE_HALF, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
BuildRgbYTable()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable () inline private
Definition at line 455 of file JpegColorDeconverter.cs.
         {
             /* Allocate and fill in the conversion tables. */
             rgb_y_tab = new int[TABLE_SIZE];
             for (var i = 0; i <= JpegConstants.MAXJSAMPLE; i++)
             {
                 rgb_y_tab[i + R_Y_OFF] = FIX(0.299) * i;
                 rgb_y_tab[i + G_Y_OFF] = FIX(0.587) * i;
                 rgb_y_tab[i + B_Y_OFF] = (FIX(0.114) * i) + ONE_HALF;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.B_Y_OFF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.FIX(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.G_Y_OFF, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.ONE_HALF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.R_Y_OFF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.rgb_y_tab, and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.TABLE_SIZE.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
BuildYccRgbTable()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable () inline private
Initialize tables for YCbCr->RGB colorspace conversion.
Definition at line 362 of file JpegColorDeconverter.cs.
         {
             /* Normal case, sYCC */
             m_Cr_r_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_b_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cr_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             m_Cb_g_tab = new int[JpegConstants.MAXJSAMPLE + 1];
             for (int i = 0, x = -JpegConstants.CENTERJSAMPLE; i <= JpegConstants.MAXJSAMPLE; i++, x++)
             {
                 /* i is the actual input pixel value, in the range 0..MAXJSAMPLE */
                 /* The Cb or Cr value we are thinking of is x = i - CENTERJSAMPLE */
                 /* Cr=>R value is nearest int to 1.402 * x */
                 m_Cr_r_tab[i] = JpegUtils.RIGHT_SHIFT((FIX(1.402) * x) + ONE_HALF, SCALEBITS);
                 /* Cb=>B value is nearest int to 1.772 * x */
                 m_Cb_b_tab[i] = JpegUtils.RIGHT_SHIFT((FIX(1.772) * x) + ONE_HALF, SCALEBITS);
                 /* Cr=>G value is scaled-up -0.714136286 * x */
                 m_Cr_g_tab[i] = -FIX(0.714136286) * x;
                 /* Cb=>G value is scaled-up -0.344136286 * x */
                 /* We also add in ONE_HALF so that need not do it in inner loop */
                 m_Cb_g_tab[i] = (-FIX(0.344136286) * x) + ONE_HALF;
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.FIX(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.ONE_HALF, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
CmykRgbConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.CmykRgbConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Color conversion for CMYK -> RGB
Definition at line 676 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var component3RowOffset = m_perComponentOffsets[3];
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < m_cinfo.outputWidth; col++)
                 {
                     int c = input_buf[0][input_row + component0RowOffset][col];
                     int m = input_buf[1][input_row + component1RowOffset][col];
                     int y = input_buf[2][input_row + component2RowOffset][col];
                     int k = input_buf[3][input_row + component3RowOffset][col];
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_RED] = (byte)((c * k) / 255);
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_GREEN] = (byte)((m * k) / 255);
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_BLUE] = (byte)((y * k) / 255);
                     columnOffset += JpegConstants.RGB_PIXELSIZE;
                 }
                 input_row++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, and BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
color_convert_func()
delegate void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.color_convert_func (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) private
ColorConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.ColorConvert (ComponentBuffer [] input_buf, int [] perComponentOffsets, int input_row, byte output_buf[][], int output_row, int num_rows) inline
Convert some rows of samples to the output colorspace.
Note that we change from noninterleaved, one-plane-per-component format to interleaved-pixel format. The output buffer is therefore three times as wide as the input buffer. A starting row offset is provided only for the input buffer. The caller can easily adjust the passed output_buf value to accommodate any row offset required on that side.
Definition at line 297 of file JpegColorDeconverter.cs.
         {
             m_perComponentOffsets = perComponentOffsets;
             m_converter(input_buf, input_row, output_buf, output_row, num_rows);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_converter, and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets.
FIX()
static int BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.FIX (double x) inline static private
Definition at line 769 of file JpegColorDeconverter.cs.
         {
             return (int)((x * (1L << SCALEBITS)) + 0.5);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable().
GrayRgbConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayRgbConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Convert grayscale to RGB: just duplicate the graylevel three times. This is provided to support applications that don't want to cope with grayscale as a separate case.
Definition at line 640 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var num_cols = m_cinfo.outputWidth;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < num_cols; col++)
                 {
                     /* We can dispense with GETJSAMPLE() here */
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_RED] = input_buf[0][input_row + component0RowOffset][col];
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_GREEN] = input_buf[0][input_row + component1RowOffset][col];
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_BLUE] = input_buf[0][input_row + component2RowOffset][col];
                     columnOffset += JpegConstants.RGB_PIXELSIZE;
                 }
                 input_row++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, and BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
GrayscaleConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayscaleConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Color conversion for grayscale: just copy the data. This also works for YCC -> grayscale conversion, in which we just copy the Y (luminance) component and ignore chrominance.
Definition at line 668 of file JpegColorDeconverter.cs.
         {
             JpegUtils.jcopy_sample_rows(input_buf[0], input_row + m_perComponentOffsets[0], output_buf, output_row, num_rows, m_cinfo.outputWidth);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegUtils.jcopy_sample_rows(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
NullConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.NullConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Color conversion for no colorspace change: just copy the data, converting from separate-planes to interleaved representation.
Definition at line 746 of file JpegColorDeconverter.cs.
         {
             for (var row = 0; row < num_rows; row++)
             {
                 for (var ci = 0; ci < m_cinfo.numComponents; ci++)
                 {
                     var columnIndex = 0;
                     var componentOffset = 0;
                     var perComponentOffset = m_perComponentOffsets[ci];
                     for (var col = 0; col < m_cinfo.outputWidth; col++)
                     {
                         /* needn't bother with GETJSAMPLE() here */
                         output_buf[output_row + row][ci + componentOffset] = input_buf[ci][input_row + perComponentOffset][columnIndex];
                         componentOffset += m_cinfo.numComponents;
                         columnIndex++;
                     }
                 }
                 input_row++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.numComponents, and BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
Rgb1GrayConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Definition at line 533 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var num_cols = m_cinfo.outputWidth;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < num_cols; col++)
                 {
                     int r = input_buf[0][input_row + component0RowOffset][col];
                     int g = input_buf[1][input_row + component1RowOffset][col];
                     int b = input_buf[2][input_row + component2RowOffset][col];
                     /* Assume that MAXJSAMPLE+1 is a power of 2, so that the MOD
                      * (modulo) operator is equivalent to the bitmask operator AND.
                      */
                     r = (r + g - JpegConstants.CENTERJSAMPLE) & JpegConstants.MAXJSAMPLE;
                     b = (b + g - JpegConstants.CENTERJSAMPLE) & JpegConstants.MAXJSAMPLE;
                     /* Y */
                     output_buf[output_row + row][columnOffset++] = (byte)((rgb_y_tab[r + R_Y_OFF] + rgb_y_tab[g + G_Y_OFF] + rgb_y_tab[b + B_Y_OFF]) >> SCALEBITS);
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.B_Y_OFF, BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.G_Y_OFF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.R_Y_OFF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.rgb_y_tab, and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
Rgb1RgbConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1RgbConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Definition at line 501 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var num_cols = m_cinfo.outputWidth;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < num_cols; col++)
                 {
                     int r = input_buf[0][input_row + component0RowOffset][col];
                     int g = input_buf[1][input_row + component1RowOffset][col];
                     int b = input_buf[2][input_row + component2RowOffset][col];
                     /* Assume that MAXJSAMPLE+1 is a power of 2, so that the MOD
                      * (modulo) operator is equivalent to the bitmask operator AND.
                      */
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_RED] = (byte)((r + g - JpegConstants.CENTERJSAMPLE) & JpegConstants.MAXJSAMPLE);
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_GREEN] = (byte)g;
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_BLUE] = (byte)((b + g - JpegConstants.CENTERJSAMPLE) & JpegConstants.MAXJSAMPLE);
                     columnOffset += JpegConstants.RGB_PIXELSIZE;
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, and BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
RgbConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Definition at line 566 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var num_cols = m_cinfo.outputWidth;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < num_cols; col++)
                 {
                     int r = input_buf[0][input_row + component0RowOffset][col];
                     int g = input_buf[1][input_row + component1RowOffset][col];
                     int b = input_buf[2][input_row + component2RowOffset][col];
                     /* We can dispense with GETJSAMPLE() here */
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_RED] = (byte)r;
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_GREEN] = (byte)g;
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_BLUE] = (byte)b;
                     columnOffset += JpegConstants.RGB_PIXELSIZE;
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, and BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
RgbGrayConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Definition at line 471 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var num_cols = m_cinfo.outputWidth;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < num_cols; col++)
                 {
                     int r = input_buf[0][input_row + component0RowOffset][col];
                     int g = input_buf[1][input_row + component1RowOffset][col];
                     int b = input_buf[2][input_row + component2RowOffset][col];
                     /* Y */
                     output_buf[output_row + row][columnOffset++] = (byte)((rgb_y_tab[r + R_Y_OFF] + rgb_y_tab[g + G_Y_OFF] + rgb_y_tab[b + B_Y_OFF]) >> SCALEBITS);
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.B_Y_OFF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.G_Y_OFF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.R_Y_OFF, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.rgb_y_tab, and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
YcckCmykConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Adobe-style YCCK->CMYK conversion. We convert YCbCr to R=1-C, G=1-M, and B=1-Y using the same conversion as above, while passing K (black) unchanged. We assume build_ycc_rgb_table has been called.
Definition at line 598 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var component3RowOffset = m_perComponentOffsets[3];
             var limit = m_cinfo.m_sample_range_limit;
             var limitOffset = m_cinfo.m_sampleRangeLimitOffset;
             var num_cols = m_cinfo.outputWidth;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < num_cols; col++)
                 {
                     int y = input_buf[0][input_row + component0RowOffset][col];
                     int cb = input_buf[1][input_row + component1RowOffset][col];
                     int cr = input_buf[2][input_row + component2RowOffset][col];
                     /* Range-limiting is essential due to noise introduced by DCT losses,
                      * and for extended gamut encodings (sYCC).
                      */
                     output_buf[output_row + row][columnOffset] = limit[limitOffset + JpegConstants.MAXJSAMPLE - (y + m_Cr_r_tab[cr])]; /* red */
                     output_buf[output_row + row][columnOffset + 1] = limit[limitOffset + JpegConstants.MAXJSAMPLE - (y + JpegUtils.RIGHT_SHIFT(m_Cb_g_tab[cb] + m_Cr_g_tab[cr], SCALEBITS))]; /* green */
                     output_buf[output_row + row][columnOffset + 2] = limit[limitOffset + JpegConstants.MAXJSAMPLE - (y + m_Cb_b_tab[cb])]; /* blue */
                     /* K passes through unchanged */
                     /* don't need GETJSAMPLE here */
                     output_buf[output_row + row][columnOffset + 3] = input_buf[3][input_row + component3RowOffset][col];
                     columnOffset += 4;
                 }
                 input_row++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sample_range_limit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sampleRangeLimitOffset, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
YcckRgbConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Color conversion for YCCK -> RGB it's just a gybrid of YCCK -> CMYK and CMYK -> RGB conversions
Definition at line 707 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var component3RowOffset = m_perComponentOffsets[3];
             var limit = m_cinfo.m_sample_range_limit;
             var limitOffset = m_cinfo.m_sampleRangeLimitOffset;
             var num_cols = m_cinfo.outputWidth;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < num_cols; col++)
                 {
                     int y = input_buf[0][input_row + component0RowOffset][col];
                     int cb = input_buf[1][input_row + component1RowOffset][col];
                     int cr = input_buf[2][input_row + component2RowOffset][col];
                     int cmyk_c = limit[limitOffset + JpegConstants.MAXJSAMPLE - (y + m_Cr_r_tab[cr])];
                     int cmyk_m = limit[limitOffset + JpegConstants.MAXJSAMPLE - (y + JpegUtils.RIGHT_SHIFT(m_Cb_g_tab[cb] + m_Cr_g_tab[cr], SCALEBITS))];
                     int cmyk_y = limit[limitOffset + JpegConstants.MAXJSAMPLE - (y + m_Cb_b_tab[cb])];
                     int cmyk_k = input_buf[3][input_row + component3RowOffset][col];
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_RED] = (byte)((cmyk_c * cmyk_k) / 255);
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_GREEN] = (byte)((cmyk_m * cmyk_k) / 255);
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_BLUE] = (byte)((cmyk_y * cmyk_k) / 255);
                     columnOffset += JpegConstants.RGB_PIXELSIZE;
                 }
                 input_row++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sample_range_limit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sampleRangeLimitOffset, BitMiracle.LibJpeg.Classic.JpegConstants.MAXJSAMPLE, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
YccRgbConvert()
void BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert (ComponentBuffer [] input_buf, int input_row, byte output_buf[][], int output_row, int num_rows) inline private
Definition at line 419 of file JpegColorDeconverter.cs.
         {
             var component0RowOffset = m_perComponentOffsets[0];
             var component1RowOffset = m_perComponentOffsets[1];
             var component2RowOffset = m_perComponentOffsets[2];
             var limit = m_cinfo.m_sample_range_limit;
             var limitOffset = m_cinfo.m_sampleRangeLimitOffset;
             for (var row = 0; row < num_rows; row++)
             {
                 var columnOffset = 0;
                 for (var col = 0; col < m_cinfo.outputWidth; col++)
                 {
                     int y = input_buf[0][input_row + component0RowOffset][col];
                     int cb = input_buf[1][input_row + component1RowOffset][col];
                     int cr = input_buf[2][input_row + component2RowOffset][col];
                     /* Range-limiting is essential due to noise introduced by DCT losses.
                      * for extended gamut (sYCC) and wide gamut (bg-sYCC) encodings.
                      */
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_RED] = limit[limitOffset + y + m_Cr_r_tab[cr]];
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_GREEN] = limit[limitOffset + y + JpegUtils.RIGHT_SHIFT(m_Cb_g_tab[cb] + m_Cr_g_tab[cr], SCALEBITS)];
                     output_buf[output_row + row][columnOffset + JpegConstants.RGB_BLUE] = limit[limitOffset + y + m_Cb_b_tab[cb]];
                     columnOffset += JpegConstants.RGB_PIXELSIZE;
                 }
                 input_row++;
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_b_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_g_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_r_tab, BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sample_range_limit, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.m_sampleRangeLimitOffset, BitMiracle.LibJpeg.Classic.JpegDecompressStruct.outputWidth, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_BLUE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_GREEN, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_PIXELSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.RGB_RED, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
Member Data Documentation
B_Y_OFF
const int BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.B_Y_OFF = (2 * (JpegConstants.MAXJSAMPLE + 1)) private
Definition at line 24 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert().
G_Y_OFF
const int BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.G_Y_OFF = (1 * (JpegConstants.MAXJSAMPLE + 1)) private
Definition at line 23 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert().
m_Cb_b_tab
int [] BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_b_tab private
Definition at line 36 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
m_Cb_g_tab
int [] BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cb_g_tab private
Definition at line 38 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
m_cinfo
readonly JpegDecompressStruct BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_cinfo private
Definition at line 30 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.CmykRgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayRgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayscaleConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.NullConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
m_converter
readonly color_convert_func BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_converter private
Definition at line 28 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.ColorConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.JpegColorDeconverter().
m_Cr_g_tab
int [] BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_g_tab private
Definition at line 37 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
m_Cr_r_tab
int [] BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_Cr_r_tab private
Definition at line 35 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
m_perComponentOffsets
int [] BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.m_perComponentOffsets private
Definition at line 32 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.CmykRgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.ColorConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayRgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.GrayscaleConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.NullConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
ONE_HALF
const int BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.ONE_HALF = 1 << (SCALEBITS - 1) private
Definition at line 13 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable().
R_Y_OFF
const int BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.R_Y_OFF = 0 private
Definition at line 22 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert().
rgb_y_tab
int [] BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.rgb_y_tab private
Definition at line 41 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert().
SCALEBITS
const int BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.SCALEBITS = 16 private
Definition at line 12 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildBgYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildYccRgbTable(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.FIX(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.Rgb1GrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.RgbGrayConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckCmykConvert(), BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YcckRgbConvert(), and BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.YccRgbConvert().
TABLE_SIZE
const int BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.TABLE_SIZE = (3 * (JpegConstants.MAXJSAMPLE + 1)) private
Definition at line 25 of file JpegColorDeconverter.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegColorDeconverter.BuildRgbYTable().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegColorDeconverter.cs