Juniper: Juniper.Unity.Input.AbstractUnifiedInputModule Class Reference
Juniper.Unity.Input.AbstractUnifiedInputModule Class Reference
Finds all of the IPointerDevice s and fires raycaster events for all of them.
Classes
class PointerFoundEvent
Public Types
enum Mode {
Mode.None, Mode.Auto = ~None, Mode.Mouse = 1, Mode.Touch = 2,
Mode.Gaze = 4, Mode.Motion = 8, Mode.Hands = 16, Mode.HasFloorPosition = 32,
Mode.Desktop = Mouse, Mode.Touchscreen = Touch | Gaze, Mode.SeatedVR = Mouse | Gaze | Motion, Mode.StandingVR = Gaze | Motion | HasFloorPosition,
Mode.HeadsetAR = Gaze | Motion | Hands | HasFloorPosition
}
Public Member Functions
void AddPointer (IPointerDevice pointer)
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void Install (bool reset)
Install, with or without a full reset.
T MakePointer< T > (Transform parent, string path)
virtual void Uninstall ()
Remove platform-specific features from the object.
PointerEventData Clone (int pointerDataID, PointerEventData original)
override void Process ()
Find all the pointers and fire raycaster events for them.
void EnableMouse (bool value, bool savePref)
void EnableGaze (bool value, bool savePref)
void EnableTouch (bool value, bool savePref)
void EnableHands (bool value, bool savePref)
void EnableControllers (bool value, bool savePref)
Public Attributes
readonly List< IPointerDevice > Devices = new List<IPointerDevice>(12)
IPointerDevice PrimaryPointer
Mode mode = Mode.Auto
GameObject pointerPrefab
Set to the clonable object that should be used for the pointer probe.
Toggle enableControllersToggle
Toggle enableMouseToggle
Toggle enableTouchToggle
Toggle enableHandsToggle
Toggle enableGazeToggle
GazePointer gazePointer
Mouse mouse
TouchPoint [] touches
MotionController [] motionControllers
HandTracker [] handTrackers
int ControllerLayer
float canvasOffset = 0.2f
Protected Member Functions
override void Awake ()
Protected Attributes
Avatar stage
Properties
bool AnyPointerDragging [get]
bool TouchConnected [get]
bool MotionConnected [get]
bool HandsConnected [get]
Private Member Functions
void SetupDevice (string key, Toggle toggle, Action< bool, bool > onEnable)
void UpdateRay (IPointerDevice pointer, PointerEventData evtData)
void RaycastAll (IPointerDevice pointer, PointerEventData eventData)
Fire a raycast using all of the GraphicRaycasters in the system, plus the one PhysicsRaycaster that is associated with the event Camera.
bool GetBool (string key)
void SetBool (string key, bool value)
void EnableDevice (string key, bool value, IPointerDevice pointer, bool savePref, Action< bool > setActive)
void EnableDevice (string key, bool value, IPointerDevice pointer, bool savePref, Action< bool > setActive, Toggle toggle)
void EnableTouches (bool value)
void EnableHands (bool value)
void EnableControllers (bool value)
Private Attributes
readonly List< IPointerDevice > newDevices = new List<IPointerDevice>(12)
const string ENABLE_GAZE_KEY = "GazePointer"
const string ENABLE_MOUSE_KEY = "MousePointer"
const string ENABLE_TOUCH_KEY = "TouchPointers"
const string ENABLE_HANDS_KEY = "HandPointers"
const string ENABLE_CONTROLLERS_KEY = "MotionControllers"
GameObject enableControllersObject
GameObject enableMouseObject
GameObject enableTouchObject
GameObject enableHandsObject
GameObject enableGazeObject
bool wasTouchAvailable = false
Detailed Description
Finds all of the IPointerDevice s and fires raycaster events for all of them.
Definition at line 49 of file UnifiedInputModule.cs.
Member Enumeration Documentation
Mode
enum Juniper.Unity.Input.AbstractUnifiedInputModule.Mode strong
Enumerator
None
Auto
Mouse
Touch
Gaze
Motion
Hands
HasFloorPosition
Desktop
Touchscreen
SeatedVR
StandingVR
HeadsetAR
Definition at line 52 of file UnifiedInputModule.cs.
         {
             None,
             Auto = ~None,
             Mouse = 1,
             Touch = 2,
             Gaze = 4,
             Motion = 8,
             Hands = 16,
             HasFloorPosition = 32,
             Desktop = Mouse,
             Touchscreen = Touch | Gaze,
             SeatedVR = Mouse | Gaze | Motion,
             StandingVR = Gaze | Motion | HasFloorPosition,
             HeadsetAR = Gaze | Motion | Hands | HasFloorPosition
         }
Member Function Documentation
AddPointer()
void Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer (IPointerDevice pointer) inline
Implements Juniper.Unity.Input.IInputModule.
Definition at line 137 of file UnifiedInputModule.cs.
         {
             if (pointer != null
                 && !Devices.Contains(pointer)
                 && !newDevices.Contains(pointer))
             {
                 newDevices.Add(pointer);
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, and Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, ConfigType >.Start().
Awake()
override void Juniper.Unity.Input.AbstractUnifiedInputModule.Awake () inline protected
Definition at line 155 of file UnifiedInputModule.cs.
         {
             base.Awake();
             Install(false);
             ControllerLayer = Devices
                 .Union(newDevices)
                 .Select(d => (int?)d.Layer)
                 .FirstOrDefault()
                 ?? LayerMask.NameToLayer("Ignore Raycast");
 #if UNITY_MODULES_UI
             SetupDevice(ENABLE_GAZE_KEY, enableGazeToggle, EnableGaze);
             SetupDevice(ENABLE_HANDS_KEY, enableHandsToggle, EnableHands);
             SetupDevice(ENABLE_CONTROLLERS_KEY, enableControllersToggle, EnableControllers);
             SetupDevice(ENABLE_MOUSE_KEY, enableMouseToggle, EnableMouse);
             SetupDevice(ENABLE_TOUCH_KEY, enableTouchToggle, EnableTouch);
 #endif
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_CONTROLLERS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_GAZE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_HANDS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_MOUSE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_TOUCH_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableControllersToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableGazeToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableHandsToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableMouseToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableTouchToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.Install(), Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices, and Juniper.Unity.Input.AbstractUnifiedInputModule.SetupDevice().
Clone()
PointerEventData Juniper.Unity.Input.AbstractUnifiedInputModule.Clone (int pointerDataID, PointerEventData original) inline
Implements Juniper.Unity.Input.IInputModule.
Definition at line 342 of file UnifiedInputModule.cs.
         {
             PointerEventData clone;
             GetPointerData(pointerDataID, out clone, true);
             clone.delta = original.delta;
             clone.position = original.position;
             clone.scrollDelta = original.scrollDelta;
             clone.pointerEnter = original.pointerEnter;
             clone.useDragThreshold = original.useDragThreshold;
             clone.pointerCurrentRaycast = original.pointerCurrentRaycast;
             if (original.clickCount == -1)
             {
                 clone.eligibleForClick = false;
                 clone.clickCount = 0;
             }
             return clone;
         }
EnableControllers() [1/2]
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers (bool value) inline private
Definition at line 578 of file UnifiedInputModule.cs.
         {
             foreach (var motionController in motionControllers)
             {
                 motionController.SetActive(value);
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.motionControllers.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Uninstall().
EnableControllers() [2/2]
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers (bool value, bool savePref) inline
Implements Juniper.Unity.Input.IInputModule.
Definition at line 586 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_CONTROLLERS_KEY, value, motionControllers.LastOrDefault(), savePref, EnableControllers
 #if UNITY_UI_MODULES
                 , enableControllersToggle
 #endif
                 );
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_CONTROLLERS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableControllersToggle, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice(), and Juniper.Unity.Input.AbstractUnifiedInputModule.motionControllers.
EnableDevice() [1/2]
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice (string key, bool value, IPointerDevice pointer, bool savePref, Action< bool > setActive) inline private
Definition at line 499 of file UnifiedInputModule.cs.
         {
             setActive(value);
             if (pointer.IsEnabled)
             {
                 PrimaryPointer = pointer;
             }
             if (savePref)
             {
                 SetBool(key, value);
             }
         }
References Juniper.Unity.Input.Pointers.IPointerDevice.IsEnabled, Juniper.Unity.Input.AbstractUnifiedInputModule.PrimaryPointer, and Juniper.Unity.Input.AbstractUnifiedInputModule.SetBool().
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch().
EnableDevice() [2/2]
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice (string key, bool value, IPointerDevice pointer, bool savePref, Action< bool > setActive, Toggle toggle) inline private
Definition at line 515 of file UnifiedInputModule.cs.
         {
             if (toggle != null && toggle.isOn != value)
             {
                 toggle.isOn = value;
             }
             EnableDevice(key, value, pointer, savePref, setActive);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice().
EnableGaze()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze (bool value, bool savePref) inline
Implements Juniper.Unity.Input.IInputModule.
Definition at line 535 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_GAZE_KEY, value, gazePointer, savePref, gazePointer.SetActive
 #if UNITY_UI_MODULES
                 , enableGazeToggle
 #endif
                 );
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_GAZE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableGazeToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.gazePointer.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Uninstall().
EnableHands() [1/2]
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands (bool value) inline private
Definition at line 561 of file UnifiedInputModule.cs.
         {
             foreach (var handTracker in handTrackers)
             {
                 handTracker.SetActive(value);
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.handTrackers.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Uninstall().
EnableHands() [2/2]
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands (bool value, bool savePref) inline
Implements Juniper.Unity.Input.IInputModule.
Definition at line 569 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_HANDS_KEY, value, handTrackers.LastOrDefault(), savePref, EnableHands
 #if UNITY_UI_MODULES
                 , enableHandsToggle
 #endif
                 );
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_HANDS_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableHandsToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.handTrackers.
EnableMouse()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse (bool value, bool savePref) inline
Implements Juniper.Unity.Input.IInputModule.
Definition at line 526 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_MOUSE_KEY, value, mouse, savePref, mouse.SetActive
 #if UNITY_UI_MODULES
                 , enableMouseToggle
 #endif
                 );
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_MOUSE_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableMouseToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.mouse.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Uninstall().
EnableTouch()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch (bool value, bool savePref) inline
Implements Juniper.Unity.Input.IInputModule.
Definition at line 552 of file UnifiedInputModule.cs.
         {
             EnableDevice(ENABLE_TOUCH_KEY, value, touches[0], savePref, EnableTouches
 #if UNITY_UI_MODULES
                 , enableTouchToggle
 #endif
                 );
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_TOUCH_KEY, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouches(), Juniper.Unity.Input.AbstractUnifiedInputModule.enableTouchToggle, and Juniper.Unity.Input.AbstractUnifiedInputModule.touches.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Uninstall().
EnableTouches()
void Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouches (bool value) inline private
Definition at line 544 of file UnifiedInputModule.cs.
         {
             foreach (var touch in touches)
             {
                 touch.SetActive(value);
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.touches.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch().
GetBool()
bool Juniper.Unity.Input.AbstractUnifiedInputModule.GetBool (string key) inline private
Definition at line 488 of file UnifiedInputModule.cs.
         {
             return PlayerPrefs.GetInt(key, 0) == 1;
         }
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.SetupDevice().
Install()
virtual void Juniper.Unity.Input.AbstractUnifiedInputModule.Install (bool reset) inline virtual
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Input.DaydreamInputModule, Juniper.Unity.Input.ViveFocusInputModule, Juniper.Unity.Input.WindowsMRInputModule, Juniper.Unity.Input.AbstractMobileInputModule, and Juniper.Unity.Input.StandaloneInputModule.
Definition at line 217 of file UnifiedInputModule.cs.
         {
 #if UNITY_EDITOR
             if (pointerPrefab == null)
             {
 #if UNITY_2018_2_OR_NEWER
                 pointerPrefab = ResourceExt.EditorLoadAsset<GameObject>("Assets/Juniper/Prefabs/Rigs/DiskProbe2018.2.prefab");
 #else
                 pointerPrefab = ResourceExt.EditorLoadAsset<GameObject>("Assets/Juniper/Prefabs/Rigs/DiskProbe2018.1.prefab");
 #endif
             }
 #endif
             stage = ComponentExt.FindAny<Avatar>();
 #if UNITY_EDITOR
             stage.IndependentHead = false;
 #else
             stage.IndependentHead = mode.HasFlag(Mode.HasFloorPosition);
 #endif
             gazePointer = MakePointer<GazePointer>(stage.Head, "GazePointer");
             mouse = MakePointer<Mouse>(stage.Head, "Mouse");
             touches = new TouchPoint[10];
             for (var i = 0; i < touches.Length; ++i)
             {
                 touches[i] = MakePointer<TouchPoint>(stage.Head, "Touches/TouchPoint" + i);
                 touches[i].fingerID = i;
             }
             motionControllers = MotionController.MakeControllers(name =>
                 MakePointer<MotionController>(stage.Hands, name));
             handTrackers = HandTracker.MakeControllers(name =>
                 MakePointer<HandTracker>(stage.Hands, name));
             this.Ensure<KeywordRecognizer>();
         }
References Juniper.Unity.Input.Pointers.Screen.TouchPoint.fingerID, Juniper.Unity.Input.AbstractUnifiedInputModule.gazePointer, Juniper.Unity.Avatar.Hands, Juniper.Unity.Input.AbstractUnifiedInputModule.handTrackers, Juniper.Unity.Avatar.Head, Juniper.Unity.Avatar.IndependentHead, Juniper.Unity.Input.AbstractUnifiedInputModule.mode, Juniper.Unity.Input.AbstractUnifiedInputModule.motionControllers, Juniper.Unity.Input.AbstractUnifiedInputModule.mouse, Juniper.Unity.Input.AbstractUnifiedInputModule.pointerPrefab, Juniper.Unity.Input.AbstractUnifiedInputModule.stage, and Juniper.Unity.Input.AbstractUnifiedInputModule.touches.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Reinstall().
MakePointer< T >()
T Juniper.Unity.Input.AbstractUnifiedInputModule.MakePointer< T > (Transform parent, string path) inline
Implements Juniper.Unity.Input.IInputModule.
Type Constraints
T : Component
T : IPointerDevice
Definition at line 256 of file UnifiedInputModule.cs.
                     : Component, IPointerDevice
         {
             var p = parent.Ensure<Transform>(path)
                 .Ensure<T>();
             p.tag = "GameController";
             p.Value.Layer = LayerMask.NameToLayer("Ignore Raycast");
             return p;
         }
Process()
override void Juniper.Unity.Input.AbstractUnifiedInputModule.Process () inline
Find all the pointers and fire raycaster events for them.
Implements Juniper.Unity.Input.IInputModule.
Definition at line 365 of file UnifiedInputModule.cs.
         {
             Devices.AddRange(newDevices);
             newDevices.Clear();
             var motion = mode.HasFlag(Mode.Motion);
             var hands = mode.HasFlag(Mode.Hands);
             var mouse = mode.HasFlag(Mode.Mouse)
                 && this.mouse.IsConnected;
             var touch = mode.HasFlag(Mode.Touch)
                 && TouchConnected
                 && !motion
                 && !hands;
             var gaze = mode.HasFlag(Mode.Gaze)
                 && !mouse
                 && !TouchConnected
                 && !MotionConnected
                 && !HandsConnected;
             EnableControllers(motion, false);
             EnableHands(hands, false);
             EnableMouse(mouse, false);
             EnableTouch(touch, false);
             EnableGaze(gaze, false);
             foreach (var pointer in Devices)
             {
                 pointer.Layer = ControllerLayer;
                 if (pointer.IsEnabled)
                 {
                     PointerEventData evtData;
                     GetPointerData(pointer.PointerDataID, out evtData, true);
                     evtData.delta = pointer.ScreenDelta;
                     evtData.position = pointer.ScreenPoint;
                     evtData.scrollDelta = pointer.ScrollDelta;
                     evtData.useDragThreshold = eventSystem.pixelDragThreshold > 0;
                     UpdateRay(pointer, evtData);
                     pointer.Process(evtData, eventSystem.pixelDragThreshold * eventSystem.pixelDragThreshold);
                 }
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch(), Juniper.Unity.Input.AbstractUnifiedInputModule.HandsConnected, Juniper.Unity.Input.AbstractUnifiedInputModule.mode, Juniper.Unity.Input.AbstractUnifiedInputModule.MotionConnected, Juniper.Unity.Input.AbstractUnifiedInputModule.mouse, Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices, Juniper.Unity.Input.AbstractUnifiedInputModule.TouchConnected, and Juniper.Unity.Input.AbstractUnifiedInputModule.UpdateRay().
RaycastAll()
void Juniper.Unity.Input.AbstractUnifiedInputModule.RaycastAll (IPointerDevice pointer, PointerEventData eventData) inline private
Fire a raycast using all of the GraphicRaycasters in the system, plus the one PhysicsRaycaster that is associated with the event Camera.
Parameters
pointer Pointer.
eventData Event data.
Definition at line 456 of file UnifiedInputModule.cs.
         {
             DisplayManager.MoveEventCameraToPointer(pointer);
             eventSystem.RaycastAll(eventData, m_RaycastResultCache);
 #if UNITY_MODULES_UI
             for (var i = 0; i < m_RaycastResultCache.Count; ++i)
             {
                 var ray = m_RaycastResultCache[i];
                 if (ray.module is GraphicRaycaster)
                 {
                     var gfr = (GraphicRaycaster)ray.module;
                     var canv = gfr.GetComponent<Canvas>();
                     ray.worldNormal = -canv.transform.forward;
                     var pos = pointer.WorldFromScreen(ray.screenPosition);
                     if (canv.renderMode == RenderMode.WorldSpace)
                     {
                         var delta = pos - pointer.Origin;
                         delta *= ray.distance / delta.magnitude + canvasOffset;
                         ray.distance = delta.magnitude;
                         pos = pointer.Origin + delta;
                     }
                     ray.worldPosition = pos;
                     m_RaycastResultCache[i] = ray;
                 }
             }
 #endif
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.canvasOffset, Juniper.Unity.Display.AbstractDisplayManager.MoveEventCameraToPointer(), Juniper.Unity.Input.Pointers.IPointerDevice.Origin, and Juniper.Unity.Input.Pointers.IPointerDevice.WorldFromScreen().
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.UpdateRay().
Reinstall()
virtual void Juniper.Unity.Input.AbstractUnifiedInputModule.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 212 of file UnifiedInputModule.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
SetBool()
void Juniper.Unity.Input.AbstractUnifiedInputModule.SetBool (string key, bool value) inline private
Definition at line 493 of file UnifiedInputModule.cs.
         {
             PlayerPrefs.SetInt(key, value ? 1 : 0);
             PlayerPrefs.Save();
         }
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice().
SetupDevice()
void Juniper.Unity.Input.AbstractUnifiedInputModule.SetupDevice (string key, Toggle toggle, Action< bool, bool > onEnable) inline private
Definition at line 202 of file UnifiedInputModule.cs.
         {
             if (toggle != null)
             {
                 toggle.onValueChanged.AddListener(enable => onEnable(enable, true));
                 toggle.isOn = GetBool(key);
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.GetBool().
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake().
Uninstall()
virtual void Juniper.Unity.Input.AbstractUnifiedInputModule.Uninstall () inline virtual
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Input.DaydreamInputModule.
Definition at line 266 of file UnifiedInputModule.cs.
         {
             EnableHands(true, false);
             EnableControllers(true, false);
             EnableGaze(true, false);
             EnableTouch(true, false);
             EnableMouse(true, false);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch().
UpdateRay()
void Juniper.Unity.Input.AbstractUnifiedInputModule.UpdateRay (IPointerDevice pointer, PointerEventData evtData) inline private
Definition at line 409 of file UnifiedInputModule.cs.
         {
             var ray = evtData.pointerCurrentRaycast;
             if (pointer.IsDragging)
             {
                 var rot = Quaternion.FromToRotation(pointer.LastDirection, pointer.Direction);
                 ray.gameObject = evtData.pointerPress;
                 ray.worldPosition = pointer.Origin + ray.distance * pointer.Direction;
                 ray.worldNormal = rot * ray.worldNormal;
                 ray.screenPosition = pointer.ScreenPoint;
             }
             else
             {
                 RaycastAll(pointer, evtData);
                 if (m_RaycastResultCache.Count > 0)
                 {
                     ray = m_RaycastResultCache[0];
                     evtData.hovered.Clear();
                     foreach (var r in m_RaycastResultCache)
                     {
                         evtData.hovered.Add(r.gameObject);
                     }
                 }
                 else
                 {
                     ray.Clear();
                     ray.worldPosition = pointer.SmoothedWorldPoint;
                     ray.distance = pointer.MinimumPointerDistance;
                     ray.worldNormal = -pointer.Direction;
                     ray.screenPosition = pointer.ScreenPoint;
                 }
             }
             evtData.pointerCurrentRaycast = ray;
         }
References Juniper.Unity.Input.Pointers.IPointerDevice.Direction, Juniper.Unity.Input.Pointers.IPointerDevice.IsDragging, Juniper.Unity.Input.Pointers.IPointerDevice.LastDirection, Juniper.Unity.Input.Pointers.IPointerDevice.MinimumPointerDistance, Juniper.Unity.Input.Pointers.IPointerDevice.Origin, Juniper.Unity.Input.AbstractUnifiedInputModule.RaycastAll(), Juniper.Unity.Input.Pointers.IPointerDevice.ScreenPoint, and Juniper.Unity.Input.Pointers.IPointerDevice.SmoothedWorldPoint.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
Member Data Documentation
canvasOffset
float Juniper.Unity.Input.AbstractUnifiedInputModule.canvasOffset = 0.2f
Definition at line 448 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.RaycastAll().
ControllerLayer
int Juniper.Unity.Input.AbstractUnifiedInputModule.ControllerLayer
Definition at line 153 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), Juniper.Unity.Animation.FadeTransition.OnEntered(), Juniper.Unity.Animation.FadeTransition.OnExiting(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
Devices
readonly List<IPointerDevice> Juniper.Unity.Input.AbstractUnifiedInputModule.Devices = new List<IPointerDevice>(12)
Definition at line 70 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer(), Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
ENABLE_CONTROLLERS_KEY
const string Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_CONTROLLERS_KEY = "MotionControllers" private
Definition at line 101 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers().
ENABLE_GAZE_KEY
const string Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_GAZE_KEY = "GazePointer" private
Definition at line 97 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze().
ENABLE_HANDS_KEY
const string Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_HANDS_KEY = "HandPointers" private
Definition at line 100 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands().
ENABLE_MOUSE_KEY
const string Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_MOUSE_KEY = "MousePointer" private
Definition at line 98 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse().
ENABLE_TOUCH_KEY
const string Juniper.Unity.Input.AbstractUnifiedInputModule.ENABLE_TOUCH_KEY = "TouchPointers" private
Definition at line 99 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch().
enableControllersObject
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.enableControllersObject private
Definition at line 113 of file UnifiedInputModule.cs.
enableControllersToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableControllersToggle
Definition at line 104 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers().
enableGazeObject
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.enableGazeObject private
Definition at line 129 of file UnifiedInputModule.cs.
enableGazeToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableGazeToggle
Definition at line 108 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze().
enableHandsObject
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.enableHandsObject private
Definition at line 125 of file UnifiedInputModule.cs.
enableHandsToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableHandsToggle
Definition at line 107 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands().
enableMouseObject
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.enableMouseObject private
Definition at line 117 of file UnifiedInputModule.cs.
enableMouseToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableMouseToggle
Definition at line 105 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse().
enableTouchObject
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.enableTouchObject private
Definition at line 121 of file UnifiedInputModule.cs.
enableTouchToggle
Toggle Juniper.Unity.Input.AbstractUnifiedInputModule.enableTouchToggle
Definition at line 106 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch().
gazePointer
GazePointer Juniper.Unity.Input.AbstractUnifiedInputModule.gazePointer
Definition at line 131 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableGaze(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
handTrackers
HandTracker [] Juniper.Unity.Input.AbstractUnifiedInputModule.handTrackers
Definition at line 135 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableHands(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
mode
Mode Juniper.Unity.Input.AbstractUnifiedInputModule.mode = Mode.Auto
Definition at line 74 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractMobileInputModule.Install(), Juniper.Unity.Input.StandaloneInputModule.Install(), Juniper.Unity.Input.ViveFocusInputModule.Install(), Juniper.Unity.Input.WindowsMRInputModule.Install(), Juniper.Unity.Input.DaydreamInputModule.Install(), Juniper.Unity.Input.AbstractUnifiedInputModule.Install(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.WindowsMRInputModule.UpdateModule().
motionControllers
MotionController [] Juniper.Unity.Input.AbstractUnifiedInputModule.motionControllers
Definition at line 134 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableControllers(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
mouse
Mouse Juniper.Unity.Input.AbstractUnifiedInputModule.mouse
Definition at line 132 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableMouse(), Juniper.Unity.Input.AbstractUnifiedInputModule.Install(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
newDevices
readonly List<IPointerDevice> Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices = new List<IPointerDevice>(12) private
Definition at line 69 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer(), Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
pointerPrefab
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.pointerPrefab
Set to the clonable object that should be used for the pointer probe.
Definition at line 95 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
PrimaryPointer
IPointerDevice Juniper.Unity.Input.AbstractUnifiedInputModule.PrimaryPointer
Definition at line 72 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableDevice(), and Juniper.Unity.Input.HoverCraft.Update().
stage
Avatar Juniper.Unity.Input.AbstractUnifiedInputModule.stage protected
Definition at line 151 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
touches
TouchPoint [] Juniper.Unity.Input.AbstractUnifiedInputModule.touches
Definition at line 133 of file UnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouch(), Juniper.Unity.Input.AbstractUnifiedInputModule.EnableTouches(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
wasTouchAvailable
bool Juniper.Unity.Input.AbstractUnifiedInputModule.wasTouchAvailable = false private
Definition at line 286 of file UnifiedInputModule.cs.
Property Documentation
AnyPointerDragging
bool Juniper.Unity.Input.AbstractUnifiedInputModule.AnyPointerDragging get
Definition at line 77 of file UnifiedInputModule.cs.
         {
             get
             {
                 foreach (var device in Devices)
                 {
                     if (device.IsDragging)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Unity.Input.CameraControl.Update().
HandsConnected
bool Juniper.Unity.Input.AbstractUnifiedInputModule.HandsConnected get private
Definition at line 327 of file UnifiedInputModule.cs.
         {
             get
             {
                 foreach (var hand in handTrackers)
                 {
                     if (hand.IsConnected)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
MotionConnected
bool Juniper.Unity.Input.AbstractUnifiedInputModule.MotionConnected get private
Definition at line 311 of file UnifiedInputModule.cs.
         {
             get
             {
                 foreach (var motion in motionControllers)
                 {
                     if (motion.IsConnected)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
TouchConnected
bool Juniper.Unity.Input.AbstractUnifiedInputModule.TouchConnected get private
Definition at line 288 of file UnifiedInputModule.cs.
         {
             get
             {
                 if (!wasTouchAvailable)
                 {
 #if UNITY_EDITOR
                     wasTouchAvailable = mode.HasFlag(Mode.Touch);
 #else
                     foreach (var touch in touches)
                     {
                         if (touch.IsConnected)
{
                             wasTouchAvailable = true;
                             return true;
                         }
                     }
 #endif
                 }
                 return wasTouchAvailable;
             }
         }
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Process().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Input/UnifiedInputModule.cs