Juniper: Juniper.Widgets.FollowMainCamera Class Reference
Juniper.Widgets.FollowMainCamera Class Reference
Public Member Functions
void OnValidate ()
void Awake ()
void OnEnable ()
Private Attributes
FollowObject f
Detailed Description
Definition at line 7 of file FollowMainCamera.cs.
Member Function Documentation
Awake()
void Juniper.Widgets.FollowMainCamera.Awake () inline
Definition at line 18 of file FollowMainCamera.cs.
         {
             if (f == null)
             {
                 OnValidate();
             }
             f.followObject = DisplayManager.MainCamera.transform;
         }
References Juniper.Widgets.FollowMainCamera.f, Juniper.Widgets.FollowObject.followObject, Juniper.Display.AbstractDisplayManager.MainCamera, and Juniper.Widgets.FollowMainCamera.OnValidate().
OnEnable()
void Juniper.Widgets.FollowMainCamera.OnEnable () inline
Definition at line 28 of file FollowMainCamera.cs.
         {
             f.Skip();
         }
References Juniper.Widgets.FollowMainCamera.f, and Juniper.Widgets.FollowObject.Skip().
OnValidate()
void Juniper.Widgets.FollowMainCamera.OnValidate () inline
Definition at line 13 of file FollowMainCamera.cs.
         {
             f = this.Ensure<FollowObject>();
         }
References Juniper.Widgets.FollowMainCamera.f.
Referenced by Juniper.Widgets.FollowMainCamera.Awake().
Member Data Documentation
f
FollowObject Juniper.Widgets.FollowMainCamera.f private
Definition at line 11 of file FollowMainCamera.cs.
Referenced by Juniper.Widgets.FollowMainCamera.Awake(), Juniper.Widgets.FollowMainCamera.OnEnable(), and Juniper.Widgets.FollowMainCamera.OnValidate().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Widgets/FollowMainCamera.cs