Juniper: Juniper.World.GIS.Google.Geocoding.GeocodingResult Class Reference
Juniper.World.GIS.Google.Geocoding.GeocodingResult Class Reference
Public Member Functions
void GetObjectData (SerializationInfo info, StreamingContext context)
AddressComponent GetAddressComponent (params AddressComponentTypes[] types)
Protected Member Functions
GeocodingResult (SerializationInfo info, StreamingContext context)
Properties
bool partial_match [get]
AddressComponent [] Address_Components [get]
string Formatted_Address [get]
string Place_ID [get]
string [] TypeStrings [get]
HashSet< AddressComponentTypes > Types [get]
GeometryResult Geometry [get]
Private Attributes
readonly Dictionary< int, AddressComponent > addressComponentLookup
Static Private Attributes
static readonly string ADDRESS_COMPONENTS_FIELD = nameof(Address_Components).ToLowerInvariant()
static readonly string FORMATTED_ADDRESS_FIELD = nameof(Formatted_Address).ToLowerInvariant()
static readonly string PLACE_ID_FIELD = nameof(Place_ID).ToLowerInvariant()
static readonly string TYPES_FIELD = nameof(Types).ToLowerInvariant()
static readonly string GEOMETRY_FIELD = nameof(Geometry).ToLowerInvariant()
static readonly string PARTIAL_MATCH_FIELD = nameof(partial_match).ToLowerInvariant()
Detailed Description
Definition at line 9 of file GeocodingResult.cs.
Constructor & Destructor Documentation
GeocodingResult()
Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult (SerializationInfo info, StreamingContext context) inline protected
Definition at line 35 of file GeocodingResult.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Address_Components = info.GetValue<AddressComponent[]>(ADDRESS_COMPONENTS_FIELD);
             addressComponentLookup = Address_Components.ToDictionary(elem => elem.Key);
             Formatted_Address = info.GetString(FORMATTED_ADDRESS_FIELD);
             Place_ID = info.GetString(PLACE_ID_FIELD);
             TypeStrings = info.GetValue<string[]>(TYPES_FIELD);
             Types = new HashSet<AddressComponentTypes>(from typeStr in TypeStrings
                                                        select Enum.TryParse<AddressComponentTypes>(typeStr, out var parsedType)
                                                            ? parsedType
                                                            : AddressComponentTypes.None);
             Geometry = info.GetValue<GeometryResult>(GEOMETRY_FIELD);
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingResult.Address_Components, Juniper.World.GIS.Google.Geocoding.GeocodingResult.ADDRESS_COMPONENTS_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.addressComponentLookup, Juniper.World.GIS.Google.Geocoding.GeocodingResult.Formatted_Address, Juniper.World.GIS.Google.Geocoding.GeocodingResult.FORMATTED_ADDRESS_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.Geometry, Juniper.World.GIS.Google.Geocoding.GeocodingResult.GEOMETRY_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.Place_ID, Juniper.World.GIS.Google.Geocoding.GeocodingResult.PLACE_ID_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.Types, Juniper.World.GIS.Google.Geocoding.GeocodingResult.TYPES_FIELD, and Juniper.World.GIS.Google.Geocoding.GeocodingResult.TypeStrings.
Member Function Documentation
GetAddressComponent()
AddressComponent Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetAddressComponent (params AddressComponentTypes [] types) inline
Definition at line 73 of file GeocodingResult.cs.
         {
             var key = AddressComponent.HashAddressComponents(types);
             var results = addressComponentLookup.Get(key);
             if (results is null)
             {
                 var subTypes = types.Append(AddressComponentTypes.political);
                 var subKey = AddressComponent.HashAddressComponents(subTypes);
                 results = addressComponentLookup.Get(subKey);
             }
             return results;
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingResult.addressComponentLookup, and Juniper.World.GIS.Google.Geocoding.AddressComponent.HashAddressComponents().
GetObjectData()
void Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 54 of file GeocodingResult.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             if (partial_match)
             {
                 info.AddValue(PARTIAL_MATCH_FIELD, partial_match);
             }
             info.AddValue(ADDRESS_COMPONENTS_FIELD, Address_Components);
             info.AddValue(FORMATTED_ADDRESS_FIELD, Formatted_Address);
             info.AddValue(PLACE_ID_FIELD, Place_ID);
             info.AddValue(TYPES_FIELD, TypeStrings);
             info.AddValue(GEOMETRY_FIELD, Geometry);
         }
References Juniper.World.GIS.Google.Geocoding.GeocodingResult.Address_Components, Juniper.World.GIS.Google.Geocoding.GeocodingResult.ADDRESS_COMPONENTS_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.Formatted_Address, Juniper.World.GIS.Google.Geocoding.GeocodingResult.FORMATTED_ADDRESS_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.Geometry, Juniper.World.GIS.Google.Geocoding.GeocodingResult.GEOMETRY_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.partial_match, Juniper.World.GIS.Google.Geocoding.GeocodingResult.PARTIAL_MATCH_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.Place_ID, Juniper.World.GIS.Google.Geocoding.GeocodingResult.PLACE_ID_FIELD, Juniper.World.GIS.Google.Geocoding.GeocodingResult.TYPES_FIELD, and Juniper.World.GIS.Google.Geocoding.GeocodingResult.TypeStrings.
Member Data Documentation
ADDRESS_COMPONENTS_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResult.ADDRESS_COMPONENTS_FIELD = nameof(Address_Components).ToLowerInvariant() static private
Definition at line 13 of file GeocodingResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
addressComponentLookup
readonly Dictionary<int, AddressComponent> Juniper.World.GIS.Google.Geocoding.GeocodingResult.addressComponentLookup private
Definition at line 20 of file GeocodingResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetAddressComponent().
FORMATTED_ADDRESS_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResult.FORMATTED_ADDRESS_FIELD = nameof(Formatted_Address).ToLowerInvariant() static private
Definition at line 14 of file GeocodingResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
GEOMETRY_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResult.GEOMETRY_FIELD = nameof(Geometry).ToLowerInvariant() static private
Definition at line 17 of file GeocodingResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
PARTIAL_MATCH_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResult.PARTIAL_MATCH_FIELD = nameof(partial_match).ToLowerInvariant() static private
Definition at line 18 of file GeocodingResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
PLACE_ID_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResult.PLACE_ID_FIELD = nameof(Place_ID).ToLowerInvariant() static private
Definition at line 15 of file GeocodingResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
TYPES_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeocodingResult.TYPES_FIELD = nameof(Types).ToLowerInvariant() static private
Definition at line 16 of file GeocodingResult.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
Property Documentation
Address_Components
AddressComponent [] Juniper.World.GIS.Google.Geocoding.GeocodingResult.Address_Components get
Definition at line 22 of file GeocodingResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
Formatted_Address
string Juniper.World.GIS.Google.Geocoding.GeocodingResult.Formatted_Address get
Definition at line 24 of file GeocodingResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
Geometry
GeometryResult Juniper.World.GIS.Google.Geocoding.GeocodingResult.Geometry get
Definition at line 32 of file GeocodingResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
partial_match
bool Juniper.World.GIS.Google.Geocoding.GeocodingResult.partial_match get
Definition at line 11 of file GeocodingResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
Place_ID
string Juniper.World.GIS.Google.Geocoding.GeocodingResult.Place_ID get
Definition at line 26 of file GeocodingResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
Types
HashSet<AddressComponentTypes> Juniper.World.GIS.Google.Geocoding.GeocodingResult.Types get
Definition at line 30 of file GeocodingResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult().
TypeStrings
string [] Juniper.World.GIS.Google.Geocoding.GeocodingResult.TypeStrings get
Definition at line 28 of file GeocodingResult.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeocodingResult.GeocodingResult(), and Juniper.World.GIS.Google.Geocoding.GeocodingResult.GetObjectData().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/Geocoding/GeocodingResult.cs