Juniper: Juniper.Unity.Widgets.Shaker Class Reference
Juniper.Unity.Widgets.Shaker Class Reference
This component manages the activity of the user picking up a mobile device and holding it, firing an event when they first pick up an object and firing another event if there has been no movement for a set amount of time (defaults to 30 seconds);
Public Member Functions
void OnEnable ()
Triggers the statistical analyzer in 3 seconds, to wait for the device gyro to settle down.
void OnDisable ()
Shuts down the gyro and statistical analysis.
void Update ()
Measures any shake or pointer movement to figure out if events need to be fired.
Public Attributes
float timeout = 30
The number of seconds to wait with no activity to consider the user inactive.
float TorqueK = 0.01f
The amount of deviation from the mean to allow before considering a gyro sample to be a "shake".
float ForceK = 0.005f
The amount of deviation from the mean to allow before considering an accelerometer sample to be a "shake".
bool includeMouseAndTouchDetection = true
Set to true to also wake up the device after the screen has been touched.
bool DebugReport
Set to true to include a debug report on ScreenDebugger.
UnityEvent onShook = new UnityEvent()
An event that is fired when the device has been shaken after a period of inactivity.
UnityEvent onInactive = new UnityEvent()
An event that is fired when there hasn't been any movement in for timeout seconds.
Properties
bool IsActive [get, private set]
Gets the current user's status as active or inactive.
bool HasShaken [get]
returns true if the statistical analyzer says there have been a lot of vibrations outside of the expected TorqueK or ForceK range.
bool? HasTorqued [get]
Returns true when the torque values breach the torque threashold.
bool? HasAccelerated [get]
Returns true when the acceleration values breach the force threshold.
bool HasPointerMoved [get]
Returns true if includeMouseAndTouchDetection has been set and the mouse has been moved or the touch screen touched.
Events
EventHandler Shook
An event that is fired when the device has been shaken after a period of inactivity.
EventHandler Inactive
An event that is fired when there hasn't been any movement in for timeout seconds.
Private Member Functions
void OnShook ()
Fires the onShook and Shook events.
void OnInactive ()
Fires the onInactive and Inactive events.
void StartSampling ()
Sets up the statistical analyzer
void Restart ()
Restart waiting for inactivity.
void PrintDebugReport ()
Prints a report to the screen that reveals the internal state of the component.
Private Attributes
const int RINGBUFFER_SIZE = 15
The number number of gyroscope samples to analyze in sequence.
SingleStatistics torques
A statistical analyzer for the gyroscope data to determine if a shake has happened.
SingleStatistics accelerations
A statistical analyzer for the accelerometer data to determine if a shake has happened.
Vector3 prevMousePosition
Keeping track of the moues position of the last frame to detect when the mouse has moved, if includeMouseAndTouchDetection is set to true.
Detailed Description
This component manages the activity of the user picking up a mobile device and holding it, firing an event when they first pick up an object and firing another event if there has been no movement for a set amount of time (defaults to 30 seconds);
Definition at line 17 of file Shaker.cs.
Member Function Documentation
OnDisable()
void Juniper.Unity.Widgets.Shaker.OnDisable () inline
Shuts down the gyro and statistical analysis.
Definition at line 86 of file Shaker.cs.
         {
             CancelInvoke();
             UnityInput.gyro.enabled = false;
             torques = null;
         }
References Juniper.Unity.Widgets.Shaker.torques.
OnEnable()
void Juniper.Unity.Widgets.Shaker.OnEnable () inline
Triggers the statistical analyzer in 3 seconds, to wait for the device gyro to settle down.
Definition at line 77 of file Shaker.cs.
         {
             UnityInput.gyro.enabled = SystemInfo.supportsGyroscope;
             Invoke(nameof(StartSampling), 3);
         }
References Juniper.Unity.Widgets.Shaker.StartSampling().
OnInactive()
void Juniper.Unity.Widgets.Shaker.OnInactive () inline private
Fires the onInactive and Inactive events.
Definition at line 207 of file Shaker.cs.
         {
             if (IsActive)
             {
                 IsActive = false;
                 onInactive?.Invoke();
                 Inactive?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.Widgets.Shaker.Inactive, Juniper.Unity.Widgets.Shaker.IsActive, and Juniper.Unity.Widgets.Shaker.onInactive.
Referenced by Juniper.Unity.Widgets.Shaker.Restart().
OnShook()
void Juniper.Unity.Widgets.Shaker.OnShook () inline private
Fires the onShook and Shook events.
Definition at line 194 of file Shaker.cs.
         {
             if (!IsActive)
             {
                 IsActive = true;
                 onShook?.Invoke();
                 Shook?.Invoke(this, EventArgs.Empty);
             }
         }
References Juniper.Unity.Widgets.Shaker.IsActive, Juniper.Unity.Widgets.Shaker.onShook, and Juniper.Unity.Widgets.Shaker.Shook.
Referenced by Juniper.Unity.Widgets.Shaker.Update().
PrintDebugReport()
void Juniper.Unity.Widgets.Shaker.PrintDebugReport () inline private
Prints a report to the screen that reveals the internal state of the component.
Definition at line 239 of file Shaker.cs.
         {
             if (torques == null)
             {
                 ScreenDebugger.Print("Torque sampling hasn't started yet.");
             }
             else
             {
                 ScreenDebugger.PrintFormat("Torqued {3} = |{0}| >{1}< {2}",
                                      torques.Mean.Label(UnitOfMeasure.Degrees, 3),
                                      torques.StandardDeviation.Label(UnitOfMeasure.Degrees),
                                      TorqueK,
                                      HasTorqued);
             }
             if (accelerations == null)
             {
                 ScreenDebugger.Print("Acceleration sampling hasn't started yet.");
             }
             else
             {
                 ScreenDebugger.PrintFormat("Acceled {3} = |{0}| >{1}< {2}",
                                      accelerations.Mean.Label(UnitOfMeasure.Degrees, 3),
                                      accelerations.StandardDeviation.Label(UnitOfMeasure.Degrees),
                                      ForceK,
                                      HasAccelerated);
                 ScreenDebugger.PrintFormat("F{0} L{1} m{2} M{3} _|_{4} |{5}| >{6}< {7}", accelerations.Mean, accelerations.StandardDeviation, ForceK);
             }
             ScreenDebugger.PrintFormat("Acceled {0} || Torqued {1} = Shaken {2}", HasAccelerated, HasTorqued, HasShaken);
         }
References Juniper.Unity.Widgets.Shaker.accelerations, Juniper.Unity.Widgets.Shaker.ForceK, Juniper.Unity.Widgets.Shaker.HasAccelerated, Juniper.Unity.Widgets.Shaker.HasShaken, Juniper.Unity.Widgets.Shaker.HasTorqued, Juniper.Statistics.AbstractCollectionStatistics< T >.Mean, System.ScreenDebugger.Print(), System.ScreenDebugger.PrintFormat(), Juniper.Statistics.AbstractCollectionStatistics< T >.StandardDeviation, Juniper.Unity.Widgets.Shaker.TorqueK, and Juniper.Unity.Widgets.Shaker.torques.
Referenced by Juniper.Unity.Widgets.Shaker.Update().
Restart()
void Juniper.Unity.Widgets.Shaker.Restart () inline private
Restart waiting for inactivity.
Definition at line 230 of file Shaker.cs.
         {
             CancelInvoke();
             Invoke(nameof(OnInactive), timeout);
         }
References Juniper.Unity.Widgets.Shaker.OnInactive(), and Juniper.Unity.Widgets.Shaker.timeout.
Referenced by Juniper.Unity.Widgets.Shaker.StartSampling(), and Juniper.Unity.Widgets.Shaker.Update().
StartSampling()
void Juniper.Unity.Widgets.Shaker.StartSampling () inline private
Sets up the statistical analyzer
Definition at line 220 of file Shaker.cs.
         {
             torques = new SingleStatistics(RINGBUFFER_SIZE);
             accelerations = new SingleStatistics(RINGBUFFER_SIZE);
             Restart();
         }
References Juniper.Unity.Widgets.Shaker.accelerations, Juniper.Unity.Widgets.Shaker.Restart(), Juniper.Unity.Widgets.Shaker.RINGBUFFER_SIZE, and Juniper.Unity.Widgets.Shaker.torques.
Referenced by Juniper.Unity.Widgets.Shaker.OnEnable().
Update()
void Juniper.Unity.Widgets.Shaker.Update () inline
Measures any shake or pointer movement to figure out if events need to be fired.
Definition at line 96 of file Shaker.cs.
         {
             torques?.Add(UnityInput.gyro.rotationRate.magnitude);
             accelerations?.Add(UnityInput.acceleration.magnitude);
             if (Application.isEditor || HasShaken || HasPointerMoved)
             {
                 Restart();
                 OnShook();
             }
             prevMousePosition = UnityInput.mousePosition;
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.Unity.Widgets.Shaker.accelerations, Juniper.Statistics.SingleStatistics.Add(), Juniper.Unity.Widgets.Shaker.DebugReport, Juniper.Unity.Widgets.Shaker.HasPointerMoved, Juniper.Unity.Widgets.Shaker.HasShaken, Juniper.Unity.Widgets.Shaker.OnShook(), Juniper.Unity.Widgets.Shaker.prevMousePosition, Juniper.Unity.Widgets.Shaker.PrintDebugReport(), Juniper.Unity.Widgets.Shaker.Restart(), and Juniper.Unity.Widgets.Shaker.torques.
Member Data Documentation
accelerations
SingleStatistics Juniper.Unity.Widgets.Shaker.accelerations private
A statistical analyzer for the accelerometer data to determine if a shake has happened.
Definition at line 128 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.PrintDebugReport(), Juniper.Unity.Widgets.Shaker.StartSampling(), and Juniper.Unity.Widgets.Shaker.Update().
DebugReport
bool Juniper.Unity.Widgets.Shaker.DebugReport
Set to true to include a debug report on ScreenDebugger.
Definition at line 43 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.Update().
ForceK
float Juniper.Unity.Widgets.Shaker.ForceK = 0.005f
The amount of deviation from the mean to allow before considering an accelerometer sample to be a "shake".
Definition at line 33 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.PrintDebugReport().
includeMouseAndTouchDetection
bool Juniper.Unity.Widgets.Shaker.includeMouseAndTouchDetection = true
Set to true to also wake up the device after the screen has been touched.
Definition at line 38 of file Shaker.cs.
onInactive
UnityEvent Juniper.Unity.Widgets.Shaker.onInactive = new UnityEvent()
An event that is fired when there hasn't been any movement in for timeout seconds.
Definition at line 53 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.OnInactive().
onShook
UnityEvent Juniper.Unity.Widgets.Shaker.onShook = new UnityEvent()
An event that is fired when the device has been shaken after a period of inactivity.
Definition at line 48 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.OnShook().
prevMousePosition
Vector3 Juniper.Unity.Widgets.Shaker.prevMousePosition private
Keeping track of the moues position of the last frame to detect when the mouse has moved, if includeMouseAndTouchDetection is set to true.
Definition at line 134 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.Update().
RINGBUFFER_SIZE
const int Juniper.Unity.Widgets.Shaker.RINGBUFFER_SIZE = 15 private
The number number of gyroscope samples to analyze in sequence.
Definition at line 118 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.StartSampling().
timeout
float Juniper.Unity.Widgets.Shaker.timeout = 30
The number of seconds to wait with no activity to consider the user inactive.
Definition at line 22 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.Restart().
TorqueK
float Juniper.Unity.Widgets.Shaker.TorqueK = 0.01f
The amount of deviation from the mean to allow before considering a gyro sample to be a "shake".
Definition at line 27 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.PrintDebugReport().
torques
SingleStatistics Juniper.Unity.Widgets.Shaker.torques private
A statistical analyzer for the gyroscope data to determine if a shake has happened.
Definition at line 123 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.OnDisable(), Juniper.Unity.Widgets.Shaker.PrintDebugReport(), Juniper.Unity.Widgets.Shaker.StartSampling(), and Juniper.Unity.Widgets.Shaker.Update().
Property Documentation
HasAccelerated
bool? Juniper.Unity.Widgets.Shaker.HasAccelerated get private
Returns true when the acceleration values breach the force threshold.
true if has accelerated; otherwise, false.
Definition at line 167 of file Shaker.cs.
         {
             get
             {
                 return accelerations?.IsSaturated == true
                     && accelerations.StandardDeviation > ForceK;
             }
         }
Referenced by Juniper.Unity.Widgets.Shaker.PrintDebugReport().
HasPointerMoved
bool Juniper.Unity.Widgets.Shaker.HasPointerMoved get private
Returns true if includeMouseAndTouchDetection has been set and the mouse has been moved or the touch screen touched.
true if has pointer moved; otherwise, false.
Definition at line 181 of file Shaker.cs.
         {
             get
             {
                 return includeMouseAndTouchDetection
                     && (UnityInput.anyKeyDown
                         || UnityInput.mousePosition != prevMousePosition
                         || UnityInput.touchCount > 0);
             }
         }
Referenced by Juniper.Unity.Widgets.Shaker.Update().
HasShaken
bool Juniper.Unity.Widgets.Shaker.HasShaken get private
returns true if the statistical analyzer says there have been a lot of vibrations outside of the expected TorqueK or ForceK range.
true if has shaken; otherwise, false.
Definition at line 142 of file Shaker.cs.
         {
             get
             {
                 return HasTorqued || HasAccelerated;
             }
         }
Referenced by Juniper.Unity.Widgets.Shaker.PrintDebugReport(), and Juniper.Unity.Widgets.Shaker.Update().
HasTorqued
bool? Juniper.Unity.Widgets.Shaker.HasTorqued get private
Returns true when the torque values breach the torque threashold.
true if has torqued; otherwise, false.
Definition at line 154 of file Shaker.cs.
         {
             get
             {
                 return torques?.IsSaturated == true
                     && torques.StandardDeviation > TorqueK;
             }
         }
Referenced by Juniper.Unity.Widgets.Shaker.PrintDebugReport().
IsActive
bool Juniper.Unity.Widgets.Shaker.IsActive get private set
Gets the current user's status as active or inactive.
true if is inactive; otherwise, false.
Definition at line 70 of file Shaker.cs.
         {
             get; private set;
         }
Referenced by Juniper.Unity.Widgets.Shaker.OnInactive(), and Juniper.Unity.Widgets.Shaker.OnShook().
Event Documentation
Inactive
EventHandler Juniper.Unity.Widgets.Shaker.Inactive
An event that is fired when there hasn't been any movement in for timeout seconds.
Definition at line 63 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.OnInactive().
Shook
EventHandler Juniper.Unity.Widgets.Shaker.Shook
An event that is fired when the device has been shaken after a period of inactivity.
Definition at line 58 of file Shaker.cs.
Referenced by Juniper.Unity.Widgets.Shaker.OnShook().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Widgets/Shaker.cs