Juniper: BitMiracle.LibJpeg.IDecompressDestination Interface Reference
BitMiracle.LibJpeg.IDecompressDestination Interface Reference
Common interface for processing of decompression.
Public Member Functions
void SetImageAttributes (LoadedImageAttributes parameters)
Implementor of this interface should process image properties received from decompressor.
void BeginWrite ()
Called before decompression
void ProcessPixelsRow (byte[] row)
It called during decompression - pass row of pixels from JPEG
void EndWrite ()
Called after decompression
Properties
Stream Output [get]
Strean with decompressed data
Detailed Description
Common interface for processing of decompression.
Definition at line 8 of file IDecompressDestination.cs.
Member Function Documentation
BeginWrite()
void BitMiracle.LibJpeg.IDecompressDestination.BeginWrite ()
Called before decompression
Implemented in BitMiracle.LibJpeg.BitmapDestination, and BitMiracle.LibJpeg.DecompressorToJpegImage.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
EndWrite()
void BitMiracle.LibJpeg.IDecompressDestination.EndWrite ()
Called after decompression
Implemented in BitMiracle.LibJpeg.BitmapDestination, and BitMiracle.LibJpeg.DecompressorToJpegImage.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
ProcessPixelsRow()
void BitMiracle.LibJpeg.IDecompressDestination.ProcessPixelsRow (byte [] row)
It called during decompression - pass row of pixels from JPEG
Parameters
row
Implemented in BitMiracle.LibJpeg.BitmapDestination, and BitMiracle.LibJpeg.DecompressorToJpegImage.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
SetImageAttributes()
void BitMiracle.LibJpeg.IDecompressDestination.SetImageAttributes (LoadedImageAttributes parameters)
Implementor of this interface should process image properties received from decompressor.
Parameters
parameters Image properties
Implemented in BitMiracle.LibJpeg.BitmapDestination, and BitMiracle.LibJpeg.DecompressorToJpegImage.
Referenced by BitMiracle.LibJpeg.Jpeg.Decompress().
Property Documentation
Output
Stream BitMiracle.LibJpeg.IDecompressDestination.Output get
Strean with decompressed data
Definition at line 13 of file IDecompressDestination.cs.
 { get; }
The documentation for this interface was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/IDecompressDestination.cs