Juniper: Juniper.XR.TrackableFoundEventHandler Class Reference
Juniper.XR.TrackableFoundEventHandler Class Reference
Trackable object–like images, scanned objects, and model generated targets– come and go out of the user's view. This component manages events around those target apperances, abstracting away platform details.
Public Member Functions
void OnValidate ()
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
void OnEnable ()
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
void Update ()
Checks the tracking status of the target and fires any appropriate change/found/lost events.
void ForceFound ()
Forces the onFound event to fire.
void ForceLost ()
Forces the onLost event to fire.
void OnDisable ()
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
void Awake ()
Registers for Vuforia's trackable event handlers.
void OnTrackableStateChanged (TrackableBehaviour.Status previousStatus, TrackableBehaviour.Status newStatus)
Updates the tracking state of the target when Unity's OnTrackableStateChange event is fired.
Public Attributes
ARReferenceImagesSet imagesSet
The ARKit set of tracked images
ARReferenceImage image
One of the images from an ARKit set of tracked images.
bool Found
This value is set to true when the target has been found.
bool Safe = true
This value is set to true when the user is at a safe distance from the target.
bool Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Transform attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
float safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
bool DebugReport
Set to true to make the update loop print a debug report.
BooleanEvent onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
UnityEvent onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
UnityEvent onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
UnityEvent onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
UnityEvent onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Events
EventHandler< TrackingStateChangeEventArgs > TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Private Member Functions
void PrintDebugReport ()
If DebugReport is set to true, prints a report on the status of tracking.
void SafetyCheck ()
Check to see if the user is standing at a comfortable distance from the object.
void OnSafeOrProximity ()
If the value of Safe has changed, fires the onSafe or onProximity event.
void OnFoundChanged ()
If the value of Found has changed, records the time at which the object was found, sets the visibility of the object, and fires the onFound, onLost, onTrackingStateChange, or the TrackingStateChange events.
void OnLostOrFound ()
Fires the onLost or onFound events.
void OnTrackingStateChanged ()
Firest the onTrackingStateChange and TrackingStateChange events.
void OnDestroy ()
When running on Vuforia, de-registers the listeners for Vuforia's tracking state changed events.
Private Attributes
TrackableBehaviour trackable
The Vuforia tracked object.
bool? wasFound
Whether or not Found was set on the previous frame, to make it easier to detect changes to it.
bool wasSafe = true
Whether or not Safe was set on the previou frame.
const string TAG_NAME = "Tracked Object Attachment Point"
The tag that the attachment point is expected to have.
const string TRANSFORM_NAME = "Attachment Point"
The name that the attachment point is expected to have.
Detailed Description
Trackable object–like images, scanned objects, and model generated targets– come and go out of the user's view. This component manages events around those target apperances, abstracting away platform details.
Definition at line 22 of file TrackableFoundEventHandler.cs.
Member Function Documentation
Awake()
void Juniper.XR.TrackableFoundEventHandler.Awake () inline
Registers for Vuforia's trackable event handlers.
Definition at line 311 of file TrackableFoundEventHandler.cs.
         {
 #if VUFORIA
             trackable = GetComponentInChildren<TrackableBehaviour>();
             trackable.RegisterTrackableEventHandler(this);
 #endif
             var keeper = this.FindAny<TrackerKeeper>();
             keeper?.Register(this);
         }
References Juniper.XR.TrackableFoundEventHandler.trackable.
ForceFound()
void Juniper.XR.TrackableFoundEventHandler.ForceFound () inline
Forces the onFound event to fire.
Definition at line 280 of file TrackableFoundEventHandler.cs.
         {
             wasFound = false;
             Found = true;
             Extended = false;
         }
References Juniper.XR.TrackableFoundEventHandler.Extended, Juniper.XR.TrackableFoundEventHandler.Found, and Juniper.XR.TrackableFoundEventHandler.wasFound.
ForceLost()
void Juniper.XR.TrackableFoundEventHandler.ForceLost () inline
Forces the onLost event to fire.
Definition at line 291 of file TrackableFoundEventHandler.cs.
         {
             wasFound = true;
             Found = false;
             Extended = false;
         }
References Juniper.XR.TrackableFoundEventHandler.Extended, Juniper.XR.TrackableFoundEventHandler.Found, and Juniper.XR.TrackableFoundEventHandler.wasFound.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnDisable().
OnDestroy()
void Juniper.XR.TrackableFoundEventHandler.OnDestroy () inline private
When running on Vuforia, de-registers the listeners for Vuforia's tracking state changed events.
Definition at line 326 of file TrackableFoundEventHandler.cs.
         {
             trackable.UnregisterTrackableEventHandler(this);
         }
References Juniper.XR.TrackableFoundEventHandler.trackable.
OnDisable()
void Juniper.XR.TrackableFoundEventHandler.OnDisable () inline
When this component is disabled, also disable the tracking of the target and fire the change event handlers.
Definition at line 302 of file TrackableFoundEventHandler.cs.
         {
             ForceLost();
             Update();
         }
References Juniper.XR.TrackableFoundEventHandler.ForceLost(), and Juniper.XR.TrackableFoundEventHandler.Update().
OnEnable()
void Juniper.XR.TrackableFoundEventHandler.OnEnable ()
When the trackable is found, we assume it's at a safe space, and then wait for the safety checker to kick in.
OnFoundChanged()
void Juniper.XR.TrackableFoundEventHandler.OnFoundChanged () inline private
If the value of Found has changed, records the time at which the object was found, sets the visibility of the object, and fires the onFound, onLost, onTrackingStateChange, or the TrackingStateChange events.
Definition at line 238 of file TrackableFoundEventHandler.cs.
         {
             if (Found != wasFound)
             {
                 this.SetVisible(Found);
                 OnTrackingStateChanged();
                 OnLostOrFound();
                 wasFound = Found;
             }
         }
References Juniper.XR.TrackableFoundEventHandler.Found, Juniper.XR.TrackableFoundEventHandler.OnLostOrFound(), Juniper.XR.TrackableFoundEventHandler.OnTrackingStateChanged(), and Juniper.XR.TrackableFoundEventHandler.wasFound.
Referenced by Juniper.XR.TrackableFoundEventHandler.Update().
OnLostOrFound()
void Juniper.XR.TrackableFoundEventHandler.OnLostOrFound () inline private
Fires the onLost or onFound events.
Definition at line 252 of file TrackableFoundEventHandler.cs.
         {
             if (wasFound != null)
             {
                 if (Found)
                 {
                     onFound?.Invoke();
                 }
                 else
                 {
                     onLost?.Invoke();
                 }
             }
         }
References Juniper.XR.TrackableFoundEventHandler.Found, Juniper.XR.TrackableFoundEventHandler.onFound, Juniper.XR.TrackableFoundEventHandler.onLost, and Juniper.XR.TrackableFoundEventHandler.wasFound.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnFoundChanged().
OnSafeOrProximity()
void Juniper.XR.TrackableFoundEventHandler.OnSafeOrProximity () inline private
If the value of Safe has changed, fires the onSafe or onProximity event.
Definition at line 215 of file TrackableFoundEventHandler.cs.
         {
             if (Safe != wasSafe)
             {
                 if (Safe)
                 {
                     onSafe?.Invoke();
                 }
                 else
                 {
                     onProximity?.Invoke();
                 }
                 wasSafe = Safe;
             }
         }
References Juniper.XR.TrackableFoundEventHandler.onProximity, Juniper.XR.TrackableFoundEventHandler.onSafe, Juniper.XR.TrackableFoundEventHandler.Safe, and Juniper.XR.TrackableFoundEventHandler.wasSafe.
Referenced by Juniper.XR.TrackableFoundEventHandler.SafetyCheck().
OnTrackableStateChanged()
void Juniper.XR.TrackableFoundEventHandler.OnTrackableStateChanged (TrackableBehaviour.Status previousStatus, TrackableBehaviour.Status newStatus) inline
Updates the tracking state of the target when Unity's OnTrackableStateChange event is fired.
Parameters
previousStatus Previous status.
newStatus New status.
Definition at line 336 of file TrackableFoundEventHandler.cs.
         {
             if (DebugReport)
             {
                 ScreenDebugger.Print("[{0}] {1} => {2}", trackable.TrackableName, previousStatus, newStatus);
             }
             Extended = trackable.CurrentStatus == TrackableBehaviour.Status.EXTENDED_TRACKED;
             Found = trackable.CurrentStatus == TrackableBehaviour.Status.DETECTED
                 || trackable.CurrentStatus == TrackableBehaviour.Status.TRACKED
                 || Extended;
         }
References Juniper.XR.TrackableFoundEventHandler.DebugReport, Juniper.XR.TrackableFoundEventHandler.Extended, Juniper.XR.TrackableFoundEventHandler.Found, ScreenDebugger.Print(), and Juniper.XR.TrackableFoundEventHandler.trackable.
OnTrackingStateChanged()
void Juniper.XR.TrackableFoundEventHandler.OnTrackingStateChanged () inline private
Firest the onTrackingStateChange and TrackingStateChange events.
Definition at line 270 of file TrackableFoundEventHandler.cs.
         {
             onTrackingStateChange?.Invoke(Found);
             TrackingStateChange?.Invoke(this, new TrackingStateChangeEventArgs(this, Found));
         }
References Juniper.XR.TrackableFoundEventHandler.Found, Juniper.XR.TrackableFoundEventHandler.onTrackingStateChange, and Juniper.XR.TrackableFoundEventHandler.TrackingStateChange.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnFoundChanged().
OnValidate()
void Juniper.XR.TrackableFoundEventHandler.OnValidate () inline
Finds the attachment point for augmentations on the trackable object. An attachment point is a definition of a space, it sets a default origin, rotation, and scale for objects attached to it.
Definition at line 138 of file TrackableFoundEventHandler.cs.
         {
             if (attachmentPoint == null)
             {
                 attachmentPoint = transform.Children().FirstOrDefault(t =>
                     t.tag == TAG_NAME)
                                            ?? transform.Children().FirstOrDefault(t =>
                                                t.name == TRANSFORM_NAME)
                                            ?? transform;
             }
         }
References Juniper.XR.TrackableFoundEventHandler.attachmentPoint, Juniper.XR.TrackableFoundEventHandler.TAG_NAME, and Juniper.XR.TrackableFoundEventHandler.TRANSFORM_NAME.
PrintDebugReport()
void Juniper.XR.TrackableFoundEventHandler.PrintDebugReport () inline private
If DebugReport is set to true, prints a report on the status of tracking.
Definition at line 173 of file TrackableFoundEventHandler.cs.
         {
             if (DebugReport)
             {
 #if VUFORIA
                 if (trackable == null)
                 {
                     ScreenDebugger.Print("[{0}] No trackable object!", name);
                 }
                 else
                 {
                     ScreenDebugger.Print("[{0}] {1} -> {2}", name, trackable.TrackableName, Extended ? "extended" : Found ? "FOUND" : "");
                 }
 #endif
             }
         }
References Juniper.XR.TrackableFoundEventHandler.DebugReport, Juniper.XR.TrackableFoundEventHandler.Extended, Juniper.XR.TrackableFoundEventHandler.Found, ScreenDebugger.Print(), and Juniper.XR.TrackableFoundEventHandler.trackable.
Referenced by Juniper.XR.TrackableFoundEventHandler.Update().
SafetyCheck()
void Juniper.XR.TrackableFoundEventHandler.SafetyCheck () inline private
Check to see if the user is standing at a comfortable distance from the object.
Definition at line 193 of file TrackableFoundEventHandler.cs.
         {
             if (Found)
             {
                 var camT = CameraExtensions.MainCamera.transform;
                 var delta = transform.position - camT.position;
                 // we only care about the over-ground distance.
                 delta.y = 0;
                 //Add 10% to the safe distance to return to safety so we don't jitter
                 // over the edge.
                 Safe = Safe && delta.magnitude >= safeDistance
                     || !Safe && delta.magnitude >= safeDistance * 1.1f;
                 OnSafeOrProximity();
             }
         }
References Juniper.XR.TrackableFoundEventHandler.Found, Juniper.CameraExtensions.MainCamera, Juniper.XR.TrackableFoundEventHandler.OnSafeOrProximity(), Juniper.XR.TrackableFoundEventHandler.Safe, and Juniper.XR.TrackableFoundEventHandler.safeDistance.
Referenced by Juniper.XR.TrackableFoundEventHandler.Update().
Update()
void Juniper.XR.TrackableFoundEventHandler.Update () inline
Checks the tracking status of the target and fires any appropriate change/found/lost events.
Definition at line 160 of file TrackableFoundEventHandler.cs.
         {
             OnFoundChanged();
             SafetyCheck();
             if (DebugReport)
             {
                 PrintDebugReport();
             }
         }
References Juniper.XR.TrackableFoundEventHandler.DebugReport, Juniper.XR.TrackableFoundEventHandler.OnFoundChanged(), Juniper.XR.TrackableFoundEventHandler.PrintDebugReport(), and Juniper.XR.TrackableFoundEventHandler.SafetyCheck().
Referenced by Juniper.XR.TrackableFoundEventHandler.OnDisable().
Member Data Documentation
attachmentPoint
Transform Juniper.XR.TrackableFoundEventHandler.attachmentPoint
A pose for where 3D objects that represent the target should be attached. The attachment point resets the object's location, orientation, and scale.
Definition at line 77 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnValidate().
DebugReport
bool Juniper.XR.TrackableFoundEventHandler.DebugReport
Set to true to make the update loop print a debug report.
Definition at line 87 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnTrackableStateChanged(), Juniper.XR.TrackableFoundEventHandler.PrintDebugReport(), and Juniper.XR.TrackableFoundEventHandler.Update().
Extended
bool Juniper.XR.TrackableFoundEventHandler.Extended
This value is set to true when the target has gone from explicit, direct tracking to extended tracking.
Definition at line 71 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.ForceFound(), Juniper.XR.TrackableFoundEventHandler.ForceLost(), Juniper.XR.TrackableFoundEventHandler.OnTrackableStateChanged(), and Juniper.XR.TrackableFoundEventHandler.PrintDebugReport().
Found
bool Juniper.XR.TrackableFoundEventHandler.Found
This value is set to true when the target has been found.
Definition at line 49 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.ForceFound(), Juniper.XR.TrackableFoundEventHandler.ForceLost(), Juniper.XR.TrackableFoundEventHandler.OnFoundChanged(), Juniper.XR.TrackableFoundEventHandler.OnLostOrFound(), Juniper.XR.TrackableFoundEventHandler.OnTrackableStateChanged(), Juniper.XR.TrackableFoundEventHandler.OnTrackingStateChanged(), Juniper.XR.TrackableFoundEventHandler.PrintDebugReport(), and Juniper.XR.TrackableFoundEventHandler.SafetyCheck().
image
ARReferenceImage Juniper.XR.TrackableFoundEventHandler.image
One of the images from an ARKit set of tracked images.
Definition at line 43 of file TrackableFoundEventHandler.cs.
imagesSet
ARReferenceImagesSet Juniper.XR.TrackableFoundEventHandler.imagesSet
The ARKit set of tracked images
Definition at line 38 of file TrackableFoundEventHandler.cs.
onFound
UnityEvent Juniper.XR.TrackableFoundEventHandler.onFound = new UnityEvent()
A Unity Event that fires when the target is first found.
Definition at line 106 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnLostOrFound(), and Juniper.XR.TrackerKeeper.Register().
onLost
UnityEvent Juniper.XR.TrackableFoundEventHandler.onLost = new UnityEvent()
A Unity Event that fires when the target is been completely lost.
Definition at line 111 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnLostOrFound(), and Juniper.XR.TrackerKeeper.Register().
onProximity
UnityEvent Juniper.XR.TrackableFoundEventHandler.onProximity = new UnityEvent()
A Unity Event that fires when the user gets too close to the target.
Definition at line 116 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.XR.TrackerKeeper.Register().
onSafe
UnityEvent Juniper.XR.TrackableFoundEventHandler.onSafe = new UnityEvent()
A Unity Event that fires when the user returns to a safe distance from the target.
Definition at line 121 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.XR.TrackerKeeper.Register().
onTrackingStateChange
BooleanEvent Juniper.XR.TrackableFoundEventHandler.onTrackingStateChange = new BooleanEvent()
A Unity Event that fires when the tracking state of the target changes. If you are wiring up events in the Unity Editor, you should prefer this version. If you are adding event listeners programmatically, you should prefer TrackingStateChange.
Definition at line 94 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnTrackingStateChanged().
Safe
bool Juniper.XR.TrackableFoundEventHandler.Safe = true
This value is set to true when the user is at a safe distance from the target.
Definition at line 60 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnSafeOrProximity(), and Juniper.XR.TrackableFoundEventHandler.SafetyCheck().
safeDistance
float Juniper.XR.TrackableFoundEventHandler.safeDistance
The minimum distance in meters from the target at which to consider the user "safe".
Definition at line 82 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.SafetyCheck().
TAG_NAME
const string Juniper.XR.TrackableFoundEventHandler.TAG_NAME = "Tracked Object Attachment Point" private
The tag that the attachment point is expected to have.
Definition at line 126 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnValidate().
trackable
TrackableBehaviour Juniper.XR.TrackableFoundEventHandler.trackable private
The Vuforia tracked object.
Definition at line 31 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.Awake(), Juniper.XR.TrackableFoundEventHandler.OnDestroy(), Juniper.XR.TrackableFoundEventHandler.OnTrackableStateChanged(), and Juniper.XR.TrackableFoundEventHandler.PrintDebugReport().
TRANSFORM_NAME
const string Juniper.XR.TrackableFoundEventHandler.TRANSFORM_NAME = "Attachment Point" private
The name that the attachment point is expected to have.
Definition at line 131 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnValidate().
wasFound
bool? Juniper.XR.TrackableFoundEventHandler.wasFound private
Whether or not Found was set on the previous frame, to make it easier to detect changes to it.
Definition at line 55 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.ForceFound(), Juniper.XR.TrackableFoundEventHandler.ForceLost(), Juniper.XR.TrackableFoundEventHandler.OnFoundChanged(), and Juniper.XR.TrackableFoundEventHandler.OnLostOrFound().
wasSafe
bool Juniper.XR.TrackableFoundEventHandler.wasSafe = true private
Whether or not Safe was set on the previou frame.
Definition at line 65 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnSafeOrProximity().
Event Documentation
TrackingStateChange
EventHandler<TrackingStateChangeEventArgs> Juniper.XR.TrackableFoundEventHandler.TrackingStateChange
A .NET Event that fires when the tracking state of the target changes. If you are adding event listeners programmatically, you should prefer this version. If you are wiring up events in the Unity Editor, you should prefer onTrackingStateChange.
Definition at line 101 of file TrackableFoundEventHandler.cs.
Referenced by Juniper.XR.TrackableFoundEventHandler.OnTrackingStateChanged().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/XR/TrackableFoundEventHandler.cs