Juniper: Juniper.Unity.MasterSceneController Class Reference
Juniper.Unity.MasterSceneController Class Reference
Manages loading SubSceneController components (scenes that are additively loaded into a "main" scene), as well as transitioning between them.
Public Member Functions
void Update ()
void SwitchToSceneName (string sceneName)
A subscene is a root game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
void Quit ()
Quit out of the application, making sure any exit transitions for the current scene are ran first.
virtual void Awake ()
Disable any subScenes that are alive in the main scene.
virtual void Reinstall ()
Reinstall the object with a full reset.
bool Install (bool reset)
Install, with or without a full reset.
void Uninstall ()
Remove platform-specific features from the object.
void LoadAllScenes ()
Static Public Member Functions
static void QuitApp ()
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Public Attributes
LoadingBar loadingBar
Image splash
Transform optionsInterface
Material sceneFaderMaterial
The material to apply to Darth Fader.
bool loadAll = true
bool exitOnEscape = true
string [] subSceneNames
All of the scene files to load. Use the "truncated scene path" format for these paths. Truncated scene paths do not need to reference the "Assets/" (it is assumed) and do not need the ".unity" file extension.
Protected Member Functions
virtual void Start ()
Wait until the Start method to load the scenes so the MasterSceneController or any child class of it can be found by the newly loaded scenes more reliably.
Properties
static IEnumerable< Scene > AllScenes [get]
Get all of the scenes defined in the Build settings.
IEnumerable< SubSceneController > SubScenes [get]
All of the SubSceneController references in the project.
SubSceneController [] CurrentSubScenes [get]
All of the active SubSceneControllers
Private Member Functions
void SwitchToSceneName (string sceneName, bool skipFadeOut)
A subscene is a root game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
void FadeOut (bool skipFadeOut)
IEnumerator SwitchToSceneNameCoroutine (string subSceneName, bool skipFadeOut)
IEnumerator LoadingCompleteCoroutine ()
void SetupFader (bool reset)
void SetupSystemInterface (bool reset, QualityDegrader qualityDegrader, InteractionAudio aud)
void SetupLighting ()
void SetupGround ()
IEnumerator LoadAllScenesCoroutine2 ()
IEnumerator LoadAllScenesCoroutine (IProgress prog=null)
Use this function by right-clicking in the editor to open up all the scenes in additive mode.
void LoadFirstScene ()
Scene? GetScene (string sceneName, string path)
Get a scene by name (or path, if we're running in the editor).
IEnumerator LoadScenePathCoroutine (string path, IProgress prog)
IEnumerator QuitCoroutine ()
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Static Private Member Functions
static AsyncOperation LoadScene (string scenePath, string sceneName)
Get a scene by name (or path, if we're running in the editor).
static string GetSceneNameFromPath (string path)
static RectTransform MakeLabeledPanel (RectTransform optionsPanel, string name, Vector2 position)
static PooledComponent< Slider > MakeLabeledSlider (RectTransform optionsPanel, string name, Vector2 position)
static bool IsScenePathLoaded (string path)
static void Exit ()
Close the application.
Private Attributes
const string SceneNamePatternStr = "([^/]+)\\.unity$"
Parse the scene name.
FadeTransition darth
bool wasLocked
A flag that indicates the cursor was locked on the previous frame.
Static Private Attributes
static readonly Regex SceneNamePattern = new Regex(SceneNamePatternStr, RegexOptions.Compiled)
Parse the scene name.
Detailed Description
Manages loading SubSceneController components (scenes that are additively loaded into a "main" scene), as well as transitioning between them.
Definition at line 38 of file MasterSceneController.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.MasterSceneController.Awake () inline virtual
Disable any subScenes that are alive in the main scene.
Definition at line 260 of file MasterSceneController.cs.
         {
             Installable.InstallAll(JuniperPlatform.GetInstallables, false);
             // Unity hacks the sense of null, creating a value reference that compares to null,
             // but doesn't work with the null coallescing operator. So we make it actually,
             // really null here.
             if (splash == null)
             {
                 splash = null;
             }
             if (optionsInterface == null)
             {
                 optionsInterface = null;
             }
             optionsInterface?.Deactivate();
             splash?.Activate();
             darth = ComponentExt.FindAny<FadeTransition>();
             foreach (var subScene in FindObjectsOfType<SubSceneController>())
             {
                 subScene.Deactivate();
             }
         }
References Juniper.Unity.MasterSceneController.darth, Juniper.Unity.JuniperPlatform.GetInstallables(), Juniper.Installable.InstallAll(), Juniper.Unity.MasterSceneController.optionsInterface, and Juniper.Unity.MasterSceneController.splash.
Exit()
static void Juniper.Unity.MasterSceneController.Exit () inline static private
Close the application.
Definition at line 731 of file MasterSceneController.cs.
         {
             if (Application.isPlaying)
             {
 #if UNITY_EDITOR
                 EditorApplication.isPlaying = false;
 #else
                 Application.Quit();
 #endif
             }
         }
Referenced by Juniper.Unity.MasterSceneController.QuitApp(), and Juniper.Unity.MasterSceneController.QuitCoroutine().
FadeOut()
void Juniper.Unity.MasterSceneController.FadeOut (bool skipFadeOut) inline private
Definition at line 205 of file MasterSceneController.cs.
         {
             if (skipFadeOut)
             {
                 darth?.SkipEnter();
             }
             else
             {
                 darth?.Enter();
             }
         }
References Juniper.Unity.MasterSceneController.darth, Juniper.Unity.Animation.AbstractTransitionController.Enter(), and Juniper.Unity.Animation.AbstractTransitionController.SkipEnter().
Referenced by Juniper.Unity.MasterSceneController.Start(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
GetScene()
Scene? Juniper.Unity.MasterSceneController.GetScene (string sceneName, string path) inline private
Get a scene by name (or path, if we're running in the editor).
Returns
The scene.
Parameters
sceneName Scene name.
path Path.
Definition at line 798 of file MasterSceneController.cs.
         {
             if (IsScenePathLoaded(path))
             {
                 return SceneManager.GetSceneByPath(path);
             }
             else
             {
 #if UNITY_EDITOR
                 if (Application.isPlaying)
                 {
 #endif
                     SceneManager.LoadScene(sceneName, LoadSceneMode.Additive);
                     return SceneManager.GetSceneByPath(path);
 #if UNITY_EDITOR
                 }
                 else
                 {
                     return EditorSceneManager.OpenScene(path, OpenSceneMode.Additive);
                 }
 #endif
             }
         }
References Juniper.Unity.MasterSceneController.IsScenePathLoaded().
Referenced by Juniper.Unity.MasterSceneController.LoadScenePathCoroutine().
GetSceneNameFromPath()
static string Juniper.Unity.MasterSceneController.GetSceneNameFromPath (string path) inline static private
Definition at line 78 of file MasterSceneController.cs.
         {
             return SceneNamePattern.Match(path).Groups[1].Value;
         }
References Juniper.Unity.MasterSceneController.SceneNamePattern.
Referenced by Juniper.Unity.MasterSceneController.LoadFirstScene(), and Juniper.Unity.MasterSceneController.LoadScenePathCoroutine().
Install()
bool Juniper.Unity.MasterSceneController.Install (bool reset) inline
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfuly. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Definition at line 302 of file MasterSceneController.cs.
         {
             reset &= Application.isEditor;
             var qualityDegrader = ComponentExt.FindAny<QualityDegrader>();
             var aud = ComponentExt.FindAny<InteractionAudio>();
             if (qualityDegrader == null || aud == null)
             {
                 return false;
             }
             SetupFader(reset);
             SetupSystemInterface(reset, qualityDegrader, aud);
             SetupLighting();
             SetupGround();
             return true;
         }
References Juniper.Unity.MasterSceneController.SetupFader(), Juniper.Unity.MasterSceneController.SetupGround(), Juniper.Unity.MasterSceneController.SetupLighting(), and Juniper.Unity.MasterSceneController.SetupSystemInterface().
Referenced by Juniper.Unity.MasterSceneController.Reinstall().
IsScenePathLoaded()
static bool Juniper.Unity.MasterSceneController.IsScenePathLoaded (string path) inline static private
Definition at line 722 of file MasterSceneController.cs.
         {
             var scene = SceneManager.GetSceneByPath(path);
             return scene.IsValid() && scene.isLoaded;
         }
Referenced by Juniper.Unity.MasterSceneController.GetScene(), and Juniper.Unity.MasterSceneController.LoadScenePathCoroutine().
LoadAllScenes()
void Juniper.Unity.MasterSceneController.LoadAllScenes () inline
Definition at line 670 of file MasterSceneController.cs.
         {
             StartCoroutine(LoadAllScenesCoroutine2());
         }
References Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine2().
Referenced by Juniper.Unity.MasterSceneController.Start().
LoadAllScenesCoroutine()
IEnumerator Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine (IProgress prog = null) inline private
Use this function by right-clicking in the editor to open up all the scenes in additive mode.
Definition at line 685 of file MasterSceneController.cs.
         {
             prog?.Report(0);
             if (subSceneNames?.Length > 0)
             {
                 var split = prog.Split(subSceneNames.Length);
                 for (var i = 0; i < subSceneNames.Length; ++i)
                 {
                     yield return LoadScenePathCoroutine(subSceneNames[i], split[i]);
                 }
             }
             prog?.Report(1);
         }
References Juniper.Unity.MasterSceneController.LoadScenePathCoroutine(), and Juniper.Unity.MasterSceneController.subSceneNames.
Referenced by Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine2().
LoadAllScenesCoroutine2()
IEnumerator Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine2 () inline private
Definition at line 675 of file MasterSceneController.cs.
         {
             loadingBar?.Activate();
             yield return LoadAllScenesCoroutine(loadingBar);
             yield return LoadingCompleteCoroutine();
         }
References Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine(), Juniper.Unity.MasterSceneController.loadingBar, and Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine().
Referenced by Juniper.Unity.MasterSceneController.LoadAllScenes().
LoadFirstScene()
void Juniper.Unity.MasterSceneController.LoadFirstScene () inline private
Definition at line 701 of file MasterSceneController.cs.
         {
             var path = subSceneNames.FirstOrDefault();
             if (string.IsNullOrEmpty(path))
             {
                 throw new InvalidOperationException("[Juniper.MasterSceneController::LoadFirstScene] No subscenes defined.");
             }
             else
             {
                 var name = GetSceneNameFromPath(path);
                 if (string.IsNullOrEmpty(name))
                 {
                     throw new InvalidOperationException("[Juniper.MasterSceneController::LoadFirstScene] Could not find scene " + path);
                 }
                 else
                 {
                     SwitchToSceneName(name, true);
                 }
             }
         }
References Juniper.Unity.MasterSceneController.GetSceneNameFromPath(), Juniper.Unity.MasterSceneController.subSceneNames, and Juniper.Unity.MasterSceneController.SwitchToSceneName().
Referenced by Juniper.Unity.MasterSceneController.Start().
LoadingCompleteCoroutine()
IEnumerator Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine () inline private
Definition at line 237 of file MasterSceneController.cs.
         {
             loadingBar?.Report(1);
             yield return loadingBar?.Waiter;
             splash?.Deactivate();
             loadingBar?.Deactivate();
             optionsInterface?.Activate();
             darth?.Exit();
             yield return darth?.Waiter;
         }
References Juniper.Unity.MasterSceneController.darth, Juniper.Unity.Animation.AbstractTransitionController.Exit(), Juniper.Unity.MasterSceneController.loadingBar, Juniper.Unity.MasterSceneController.optionsInterface, Juniper.Unity.Widgets.LoadingBar.Report(), Juniper.Unity.MasterSceneController.splash, Juniper.Unity.Widgets.LoadingBar.Waiter, and Juniper.Unity.AbstractStateController.Waiter.
Referenced by Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine2(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
LoadScene()
static AsyncOperation Juniper.Unity.MasterSceneController.LoadScene (string scenePath, string sceneName) inline static private
Get a scene by name (or path, if we're running in the editor).
Returns
The scene.
Parameters
sceneName Scene name.
path Path.
Definition at line 63 of file MasterSceneController.cs.
         {
             if (Application.isPlaying)
             {
                 return SceneManager.LoadSceneAsync(sceneName, LoadSceneMode.Additive);
             }
 #if UNITY_EDITOR
             else
             {
                 EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Additive);
             }
 #endif
             return null;
         }
Referenced by Juniper.Unity.MasterSceneController.LoadScenePathCoroutine().
LoadScenePathCoroutine()
IEnumerator Juniper.Unity.MasterSceneController.LoadScenePathCoroutine (string path, IProgress prog) inline private
Definition at line 822 of file MasterSceneController.cs.
         {
             prog?.Report(0);
             var sceneName = GetSceneNameFromPath(path);
             var split = prog.Split(2);
             var sceneLoadProg = split[0];
             var subSceneLoadProg = split[1];
             if (IsScenePathLoaded(path))
             {
                 sceneLoadProg?.Report(1);
                 yield return sceneName + " already loaded.";
             }
             else
             {
                 var op = LoadScene(path, sceneName);
                 if (op == null)
                 {
                     sceneLoadProg?.Report(1);
                     yield return sceneName + " 100%";
                 }
                 else
                 {
                     while (!op.isDone)
                     {
                         sceneLoadProg?.Report(op.progress);
                         yield return sceneName + " " + (prog?.Progress).Label(UnitOfMeasure.Percent, 1);
                     }
                 }
             }
             Scene? scene = null;
             while (scene == null)
             {
                 scene = GetScene(sceneName, path);
                 yield return sceneName + " " + (prog?.Progress).Label(UnitOfMeasure.Percent, 1);
             }
             var toLoad = from root in scene.Value.GetRootGameObjects()
                          from subScene in root.GetComponentsInChildren<SubSceneController>(true)
                          select subScene;
             subSceneLoadProg.ForEach(toLoad, (ss, p) => ss.Load(p), Debug.LogException);
             while (prog?.IsComplete() == false)
             {
                 yield return sceneName + " " + (prog?.Progress).Label(UnitOfMeasure.Percent, 1);
             }
         }
References Juniper.Unity.MasterSceneController.GetScene(), Juniper.Unity.MasterSceneController.GetSceneNameFromPath(), Juniper.Unity.MasterSceneController.IsScenePathLoaded(), Juniper.Unity.MasterSceneController.LoadScene(), Juniper.Progress.IProgress.Progress, and Juniper.Progress.IProgress.Report().
Referenced by Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
MakeLabeledPanel()
static RectTransform Juniper.Unity.MasterSceneController.MakeLabeledPanel (RectTransform optionsPanel, string name, Vector2 position) inline static private
Definition at line 528 of file MasterSceneController.cs.
         {
             var panelRect = optionsPanel.EnsureRectTransform(name).Value;
             var panel = panelRect.EnsureComponent<HorizontalLayoutGroup>();
             if (panel.IsNew)
             {
                 panel.Value.childAlignment = TextAnchor.MiddleLeft;
                 panel.Value.childControlWidth = false;
                 panel.Value.childControlHeight = true;
                 panel.Value.childForceExpandWidth = true;
                 panel.Value.childForceExpandHeight = true;
                 panel.SetAnchors(0.5f * Vector2.up, new Vector2(1, 0.5f))
                     .SetPivot(0.5f * Vector2.one)
                     .SetPosition(position)
                     .SetSize(new Vector2(0, 100));
             }
             var labelRect = panel.EnsureRectTransform(name + "Label").Value;
             var label = labelRect.EnsureComponent<TMPro.TextMeshProUGUI>();
             if (label.IsNew)
             {
                 label.SetPivot(0.5f * Vector2.one)
                     .SetSize(260, panelRect.rect.height);
                 label.Value.text = name;
                 label.Value.alignment = TMPro.TextAlignmentOptions.MidlineRight;
             }
             var content = panel.EnsureRectTransform(name + "Content");
             if (content.IsNew)
             {
                 content.SetPivot(new Vector2(1, 0.5f))
                     .SetSize(panelRect.rect.width - labelRect.rect.width, panelRect.rect.height);
             }
             return content;
         }
Referenced by Juniper.Unity.MasterSceneController.MakeLabeledSlider().
MakeLabeledSlider()
static PooledComponent<Slider> Juniper.Unity.MasterSceneController.MakeLabeledSlider (RectTransform optionsPanel, string name, Vector2 position) inline static private
Definition at line 565 of file MasterSceneController.cs.
         {
             var panel = MakeLabeledPanel(optionsPanel, name, position);
             var slider = panel
                 .EnsureRectTransform(name + "Slider")
                 .EnsureComponent<Slider>();
             if (slider.IsNew)
             {
                 var size = new Vector2(160, 20);
                 slider
                     .SetAnchors(Vector2.up, Vector2.up)
                     .SetPivot(Vector2.zero)
                     .SetScale(4f * Vector3.one)
                     .SetSize(size)
                     .SetPosition(new Vector3(0.5f * (panel.rect.width - size.x * 4), -0.5f * (panel.rect.height + size.y * 4)));
                 slider.Value.direction = Slider.Direction.LeftToRight;
             }
             var background = slider
                 .EnsureRectTransform("Background")
                 .EnsureComponent<Image>();
             if (background.IsNew)
             {
                 background.SetAnchors(0.25f * Vector2.up, new Vector2(1, 0.75f))
                     .SetPosition(Vector2.zero)
                     .SetSize(Vector2.zero);
 #if UNITY_EDITOR
                 background.Value.sprite = ComponentExt.EditorLoadAsset<Sprite>("UI/Skin/Background.psd");
 #endif
                 background.Value.type = Image.Type.Sliced;
             }
             var fillArea = slider
                 .EnsureRectTransform("Fill Area");
             if (fillArea.IsNew)
             {
                 fillArea
                     .SetAnchors(0.25f * Vector2.up, new Vector2(1, 0.75f))
                     .SetPosition(5 * Vector2.left)
                     .SetSize(20 * Vector2.left);
             }
             var fill = fillArea
                 .EnsureRectTransform("Fill")
                 .EnsureComponent<Image>();
             if (fill.IsNew)
             {
                 fill
                     .SetAnchors(Vector2.zero, Vector2.up)
                     .SetSize(new Vector2(10, 0));
 #if UNITY_EDITOR
                 fill.Value.sprite = ComponentExt.EditorLoadAsset<Sprite>("UI/Skin/UISprite.psd");
 #endif
                 fill.Value.type = Image.Type.Sliced;
             }
             var handleArea = slider
                 .EnsureRectTransform("Handle Slide Area");
             if (handleArea.IsNew)
             {
                 handleArea
                     .SetAnchors(Vector2.zero, Vector2.one)
                     .SetSize(20 * Vector2.left);
             }
             var handle = handleArea
                 .EnsureRectTransform("Handle")
                 .EnsureComponent<Image>();
             if (handle.IsNew)
             {
                 handle.SetSize(20 * Vector2.right);
 #if UNITY_EDITOR
                 handle.Value.sprite = ComponentExt.EditorLoadAsset<Sprite>("UI/Skin/Knob.psd");
 #endif
             }
             slider.Value.fillRect = fill.GetComponent<RectTransform>();
             slider.Value.handleRect = handle.GetComponent<RectTransform>();
             slider.Value.targetGraphic = handle;
             return slider;
         }
References Juniper.Unity.MasterSceneController.MakeLabeledPanel().
Referenced by Juniper.Unity.MasterSceneController.SetupSystemInterface().
Quit()
void Juniper.Unity.MasterSceneController.Quit () inline
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Definition at line 252 of file MasterSceneController.cs.
         {
             StartCoroutine(QuitCoroutine());
         }
References Juniper.Unity.MasterSceneController.QuitCoroutine().
QuitApp()
static void Juniper.Unity.MasterSceneController.QuitApp () inline static
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Definition at line 44 of file MasterSceneController.cs.
         {
             var master = ComponentExt.FindAny<MasterSceneController>();
             if (master == null)
             {
                 Exit();
             }
             else
             {
                 master.Quit();
             }
         }
References Juniper.Unity.MasterSceneController.Exit().
Referenced by Juniper.Unity.MasterSceneController.Update().
QuitCoroutine()
IEnumerator Juniper.Unity.MasterSceneController.QuitCoroutine () inline private
Quit out of the application, making sure any exit transitions for the current scene are ran first.
Definition at line 917 of file MasterSceneController.cs.
         {
             foreach (var subScene in CurrentSubScenes)
             {
                 subScene.Exit();
             }
             yield return new WaitUntil(() =>
                 CurrentSubScenes.All(subScene =>
                     subScene.IsComplete));
             if (darth != null)
             {
                 darth.Enter();
                 yield return darth.Waiter;
             }
             Exit();
         }
References Juniper.Unity.MasterSceneController.CurrentSubScenes, Juniper.Unity.MasterSceneController.darth, Juniper.Unity.Animation.AbstractTransitionController.Enter(), Juniper.Unity.MasterSceneController.Exit(), and Juniper.Unity.AbstractStateController.Waiter.
Referenced by Juniper.Unity.MasterSceneController.Quit().
Reinstall()
virtual void Juniper.Unity.MasterSceneController.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 288 of file MasterSceneController.cs.
         {
             Install(true);
         }
References Juniper.Unity.MasterSceneController.Install().
SetupFader()
void Juniper.Unity.MasterSceneController.SetupFader (bool reset) inline private
Definition at line 320 of file MasterSceneController.cs.
         {
 #if UNITY_EDITOR
             if (sceneFaderMaterial == null || reset)
             {
                 sceneFaderMaterial = ComponentExt.EditorLoadAsset<Material>("Assets/Juniper/Materials/FaderMaterial.mat");
             }
 #endif
             var fader = FadeTransition.Ensure(DisplayManager.MainCamera.transform);
             if (fader.IsNew || reset)
             {
                 fader.GetComponent<Renderer>()
                     .SetMaterial(sceneFaderMaterial);
                 fader.transform.localPosition = Mathf.Max(0.5f, 1.2f * DisplayManager.MainCamera.nearClipPlane) * Vector3.forward;
                 fader.transform.localScale = 2 * Vector3.one;
             }
         }
References Juniper.Unity.Animation.FadeTransition.Ensure(), Juniper.Unity.Display.AbstractDisplayManager.MainCamera, and Juniper.Unity.MasterSceneController.sceneFaderMaterial.
Referenced by Juniper.Unity.MasterSceneController.Install().
SetupGround()
void Juniper.Unity.MasterSceneController.SetupGround () inline private
Definition at line 518 of file MasterSceneController.cs.
         {
             var ground = transform.Query("/Ground");
             if (ground == null)
             {
                 ground = new GameObject("Ground").transform;
             }
             ground.EnsureComponent<Ground.Ground>();
         }
Referenced by Juniper.Unity.MasterSceneController.Install().
SetupLighting()
void Juniper.Unity.MasterSceneController.SetupLighting () inline private
Definition at line 474 of file MasterSceneController.cs.
         {
             var sun = RenderSettings.sun;
 #if UNITY_EDITOR
             if (sun?.gameObject?.scene.name != gameObject.scene.name)
             {
                 sun = (from light in ComponentExt.FindAll<Light>()
                        where light.type == LightType.Directional
                         && light.gameObject?.scene.name == gameObject.scene.name
                        orderby light.intensity descending
                        select light).FirstOrDefault();
                 if (sun == null)
                 {
                     sun = new GameObject("Sun").AddComponent<Light>();
                     sun.type = LightType.Directional;
                     sun.shadows = LightShadows.Soft;
                 }
                 RenderSettings.sun = sun;
             }
 #endif
             sun.EnsureComponent<GPSLocation>();
             sun.EnsureComponent<SunPosition>();
             sun.EnsureComponent<LightMeasurement>();
             var estimator = sun.GetComponent<AbstractLightEstimate>();
             if (estimator == null)
             {
                 estimator = sun.gameObject.AddComponent<IndoorLightEstimate>();
             }
             var sunRig = sun.transform.parent;
             if (sunRig == null)
             {
                 sunRig = new GameObject().transform;
                 sun.transform.SetParent(sunRig, false);
             }
             sunRig.name = "SunRig";
             sunRig.EnsureComponent<CompassRose>();
         }
Referenced by Juniper.Unity.MasterSceneController.Install().
SetupSystemInterface()
void Juniper.Unity.MasterSceneController.SetupSystemInterface (bool reset, QualityDegrader qualityDegrader, InteractionAudio aud) inline private
Definition at line 339 of file MasterSceneController.cs.
         {
             var sys = transform.Query("/SystemUserInterface");
             if (sys == null)
             {
                 sys = new GameObject("SystemUserInterface").transform;
                 sys.localPosition = 1.5f * Vector3.forward;
                 var follow = sys.EnsureComponent<FollowMainCamera>();
                 follow.Value.followDistance = 1.5f;
             }
             var transparentLayer = LayerMask.NameToLayer("TransparentFX");
             var bar = LoadingBar.Ensure(sys, transparentLayer);
             if (bar.IsNew || reset)
             {
                 bar.transform.localPosition = (2f / 3f) * Vector3.down;
                 bar.transform.localScale = new Vector3(1f, 0.1f, 0.1f);
                 loadingBar = bar;
             }
 #if UNITY_MODULES_UI
             var canv = sys.EnsureRectTransform("Canvas")
                 .EnsureComponent<Canvas>();
             if (canv.IsNew || reset)
             {
                 canv.Value.renderMode = RenderMode.WorldSpace;
                 canv.SetAnchors(0.5f * Vector2.one, 0.5f * Vector2.one)
                     .SetPivot(0.5f * Vector2.one)
                     .SetSize(1000, 1000)
                     .SetScale(new Vector3(0.001f, 0.001f, 1));
             }
             canv.EnsureComponent<GraphicRaycaster>();
             canv.gameObject.layer = transparentLayer;
             var debugText = canv.Value
                     .EnsureRectTransform("DebugText")
                     .EnsureComponent<Text>();
             if (debugText.IsNew || reset)
             {
                 debugText.Value.gameObject.layer = transparentLayer;
                 debugText.Value.raycastTarget = false;
                 debugText.Value.font = Resources.GetBuiltinResource<Font>("Arial.ttf");
                 debugText.Value.supportRichText = false;
                 debugText.Value.alignment = TextAnchor.UpperLeft;
                 debugText.Value.horizontalOverflow = HorizontalWrapMode.Wrap;
                 debugText.Value.verticalOverflow = VerticalWrapMode.Truncate;
                 debugText.Value.color = Color.green;
                 debugText.Value.fontSize = 50;
                 debugText.SetAnchors(Vector2.zero, Vector2.one)
                     .SetPivot(Vector2.up)
                     .SetPosition(Vector3.zero);
             }
             debugText.EnsureComponent<ScreenDebugger>();
             if (splash == null || reset)
             {
                 var splashImg = canv.EnsureRectTransform("SplashImage")
                     .EnsureComponent<Image>();
                 if (splashImg.IsNew || reset)
                 {
 #if UNITY_EDITOR
                     splashImg.Value.sprite = ComponentExt.EditorLoadAsset<Sprite>("Assets/Juniper/Textures/logo-large.png");
 #endif
                     splashImg
                         .SetAnchors(Vector2.zero, Vector2.one)
                         .SetPivot(0.5f * Vector2.one)
                         .SetPosition(Vector3.zero)
                         .gameObject.layer = transparentLayer;
                 }
                 splash = splashImg;
             }
             if (optionsInterface == null || reset)
             {
                 var opts = canv.EnsureRectTransform("Options");
                 if (opts.IsNew || reset)
                 {
                     opts.SetAnchors(Vector2.zero, Vector2.one)
                         .SetPivot(0.5f * Vector2.one)
                         .SetPosition(Vector3.zero);
                 }
                 optionsInterface = opts.transform;
             }
             var icon = optionsInterface
                 .EnsureRectTransform("Image")
                 .EnsureComponent<Image>();
             if (icon.IsNew)
             {
 #if UNITY_EDITOR
                 icon.Value.sprite = ComponentExt.EditorLoadAsset<Sprite>("Assets/Juniper/Textures/gear.png");
 #endif
                 icon.SetAnchors(Vector2.zero, Vector2.zero)
                     .SetPivot(Vector2.zero)
                     .SetSize(100, 100);
             }
 #if UNITY_TEXTMESHPRO
             var optionsPanel = optionsInterface.EnsureRectTransform("OptionsPanel");
             if (optionsPanel.IsNew)
             {
                 optionsPanel
                     .SetAnchors(Vector2.zero, Vector2.one)
                     .SetPivot(0.5f * Vector2.one)
                     .SetSize(Vector2.zero);
             }
             var toggle = icon.EnsureComponent<Toggle>();
             toggle.Value.isOn = true;
             toggle.Value.onValueChanged.AddListener(optionsPanel.SetActive);
             var qualitySlider = MakeLabeledSlider(optionsPanel, "Quality", 225 * Vector2.down);
             qualitySlider.Value.wholeNumbers = true;
             qualitySlider.Value.minValue = 0;
             qualitySlider.Value.maxValue = 5;
             qualityDegrader.qualitySlider = qualitySlider;
             var volumeSlider = MakeLabeledSlider(optionsPanel, "Volume", 350 * Vector2.down);
             aud.volumeSlider = volumeSlider.gameObject;
 #endif
 #endif
         }
References Juniper.Unity.Widgets.LoadingBar.Ensure(), Juniper.Unity.Widgets.FollowMainCamera.followDistance, Juniper.Unity.MasterSceneController.loadingBar, Juniper.Unity.MasterSceneController.MakeLabeledSlider(), Juniper.Unity.MasterSceneController.optionsInterface, Juniper.Unity.Widgets.QualityDegrader.qualitySlider, Juniper.Unity.MasterSceneController.splash, and Juniper.Unity.Audio.InteractionAudio.volumeSlider.
Referenced by Juniper.Unity.MasterSceneController.Install().
Start()
virtual void Juniper.Unity.MasterSceneController.Start () inline protected virtual
Wait until the Start method to load the scenes so the MasterSceneController or any child class of it can be found by the newly loaded scenes more reliably.
Definition at line 656 of file MasterSceneController.cs.
         {
             FadeOut(true);
             if (loadAll)
             {
                 Invoke(nameof(LoadAllScenes), 0.5f);
             }
             else
             {
                 Invoke(nameof(LoadFirstScene), 0.5f);
             }
         }
References Juniper.Unity.MasterSceneController.FadeOut(), Juniper.Unity.MasterSceneController.loadAll, Juniper.Unity.MasterSceneController.LoadAllScenes(), and Juniper.Unity.MasterSceneController.LoadFirstScene().
SwitchToSceneName() [1/2]
void Juniper.Unity.MasterSceneController.SwitchToSceneName (string sceneName) inline
A subscene is a root game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
Parameters
sceneName
Returns
Definition at line 184 of file MasterSceneController.cs.
         {
             SwitchToSceneName(sceneName, false);
         }
Referenced by Juniper.Unity.MasterSceneController.LoadFirstScene().
SwitchToSceneName() [2/2]
void Juniper.Unity.MasterSceneController.SwitchToSceneName (string sceneName, bool skipFadeOut) inline private
A subscene is a root game object loaded from another scene. The scenes all get loaded at runtime and then you can make different parts of it visible on the fly. This procedure deactivates any subscenes that are not the desired subscene, calling any Exit functions along the way. In the new scene, TransitionController Enter functions are called as well. It is suitable for running in a coroutine to track when the end of the switching process occurs.
Parameters
sceneName
skipFadeOut Whether or not to fade the screen out (true) or start with a black screen (false) before loading the scene.
Returns
Definition at line 200 of file MasterSceneController.cs.
         {
             StartCoroutine(SwitchToSceneNameCoroutine(sceneName, skipFadeOut));
         }
References Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
SwitchToSceneNameCoroutine()
IEnumerator Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine (string subSceneName, bool skipFadeOut) inline private
Definition at line 217 of file MasterSceneController.cs.
         {
             loadingBar?.Activate();
             loadingBar?.Report(0);
             if (!skipFadeOut)
             {
                 FadeOut(skipFadeOut);
                 yield return darth?.Waiter;
             }
             var parts = subSceneName.Split('.');
             var sceneName = parts[0];
             var sceneFileName = sceneName + ".unity";
             var scenePath = Array.Find(subSceneNames, s => s.EndsWith(sceneFileName));
             yield return LoadScenePathCoroutine(scenePath, loadingBar);
             yield return LoadingCompleteCoroutine();
         }
References Juniper.Unity.MasterSceneController.darth, Juniper.Unity.MasterSceneController.FadeOut(), Juniper.Unity.MasterSceneController.loadingBar, Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.LoadScenePathCoroutine(), Juniper.Unity.Widgets.LoadingBar.Report(), Juniper.Unity.MasterSceneController.subSceneNames, and Juniper.Unity.AbstractStateController.Waiter.
Referenced by Juniper.Unity.MasterSceneController.SwitchToSceneName().
Uninstall()
void Juniper.Unity.MasterSceneController.Uninstall () inline
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 648 of file MasterSceneController.cs.
         {
         }
Update()
void Juniper.Unity.MasterSceneController.Update () inline
Definition at line 165 of file MasterSceneController.cs.
         {
             if (exitOnEscape && !wasLocked && UnityEngine.Input.GetKeyDown(KeyCode.Escape))
             {
                 QuitApp();
             }
             wasLocked = Cursor.lockState != CursorLockMode.None;
         }
References Juniper.Unity.MasterSceneController.exitOnEscape, Juniper.Unity.MasterSceneController.QuitApp(), and Juniper.Unity.MasterSceneController.wasLocked.
Member Data Documentation
darth
FadeTransition Juniper.Unity.MasterSceneController.darth private
Definition at line 116 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.Awake(), Juniper.Unity.MasterSceneController.FadeOut(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.QuitCoroutine(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
exitOnEscape
bool Juniper.Unity.MasterSceneController.exitOnEscape = true
Definition at line 97 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.Update().
loadAll
bool Juniper.Unity.MasterSceneController.loadAll = true
Definition at line 95 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.Start().
loadingBar
LoadingBar Juniper.Unity.MasterSceneController.loadingBar
Definition at line 83 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine2(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), Juniper.Unity.MasterSceneController.SetupSystemInterface(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
optionsInterface
Transform Juniper.Unity.MasterSceneController.optionsInterface
Definition at line 87 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.Awake(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.Unity.MasterSceneController.SetupSystemInterface().
sceneFaderMaterial
Material Juniper.Unity.MasterSceneController.sceneFaderMaterial
The material to apply to Darth Fader.
Definition at line 93 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.SetupFader().
SceneNamePattern
readonly Regex Juniper.Unity.MasterSceneController.SceneNamePattern = new Regex(SceneNamePatternStr, RegexOptions.Compiled) static private
Parse the scene name.
Definition at line 114 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.GetSceneNameFromPath().
SceneNamePatternStr
const string Juniper.Unity.MasterSceneController.SceneNamePatternStr = "([^/]+)\\.unity$" private
Parse the scene name.
Definition at line 109 of file MasterSceneController.cs.
splash
Image Juniper.Unity.MasterSceneController.splash
Definition at line 85 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.Awake(), Juniper.Unity.MasterSceneController.LoadingCompleteCoroutine(), and Juniper.Unity.MasterSceneController.SetupSystemInterface().
subSceneNames
string [] Juniper.Unity.MasterSceneController.subSceneNames
All of the scene files to load. Use the "truncated scene path" format for these paths. Truncated scene paths do not need to reference the "Assets/" (it is assumed) and do not need the ".unity" file extension.
Definition at line 104 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.LoadAllScenesCoroutine(), Juniper.Unity.MasterSceneController.LoadFirstScene(), and Juniper.Unity.MasterSceneController.SwitchToSceneNameCoroutine().
wasLocked
bool Juniper.Unity.MasterSceneController.wasLocked private
A flag that indicates the cursor was locked on the previous frame.
Definition at line 121 of file MasterSceneController.cs.
Referenced by Juniper.Unity.MasterSceneController.Update().
Property Documentation
AllScenes
IEnumerable<Scene> Juniper.Unity.MasterSceneController.AllScenes static get
Get all of the scenes defined in the Build settings.
All scenes.
Definition at line 128 of file MasterSceneController.cs.
         {
             get
             {
                 for (var i = 0; i < SceneManager.sceneCount; ++i)
                 {
                     yield return SceneManager.GetSceneAt(i);
                 }
             }
         }
Referenced by UnityEngine.RectTransformExt.Query< T >(), and UnityEngine.TransformExt.Query< T >().
CurrentSubScenes
SubSceneController [] Juniper.Unity.MasterSceneController.CurrentSubScenes get
All of the active SubSceneControllers
The current sub scenes.
Definition at line 155 of file MasterSceneController.cs.
         {
             get
             {
                 return (from scene in SubScenes
                         where scene.isActiveAndEnabled
                         select scene)
                     .ToArray();
             }
         }
Referenced by Juniper.Unity.MasterSceneController.QuitCoroutine().
SubScenes
IEnumerable<SubSceneController> Juniper.Unity.MasterSceneController.SubScenes get
All of the SubSceneController references in the project.
The sub scenes.
Definition at line 143 of file MasterSceneController.cs.
         {
             get
             {
                 return ComponentExt.FindAll<SubSceneController>();
             }
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/MasterSceneController.cs