Juniper: Juniper.UnitsTests Class Reference
Juniper.UnitsTests Class Reference
Public Member Functions
void farenheit_2_celsius ()
void Farenheit_2_kelvin ()
void celsius_2_farenheit ()
void celsius_2_kelvin ()
void kelvin_2_farenheit ()
void kelvin_2_celsius ()
void degrees_2_radians ()
void degrees_2_hours ()
void hours_2_degrees ()
void hours_2_radians ()
void radians_2_degrees ()
void radians_2_hours ()
void grams_2_ounces ()
void grams_2_pounds ()
void grams_2_kilograms ()
void grams_2_tons ()
void ounces_2_grams ()
void ounces_2_pounds ()
void ounces_2_kilograms ()
void ounces_2_tons ()
void pounds_2_grams ()
void pounds_2_ounces ()
void pounds_2_kilograms ()
void pounds_2_tons ()
void kilograms_2_grams ()
void kilograms_2_ounces ()
void kilograms_2_pounds ()
void kilograms_2_tons ()
void tons_2_grams ()
void tons_2_ounces ()
void tons_2_pounds ()
void tons_2_kilograms ()
void millimeters_2_centimeters ()
void millimeters_2_inches ()
void millimeters_2_feet ()
void millimeters_2_miles ()
void millimeters_2_kilometers ()
void centimeters_2_inches ()
void centimeters_2_feet ()
void centimeters_2_miles ()
void centimeters_2_millimeters ()
void centimeters_2_kilometers ()
void inches_2_feet ()
void inches_2_miles ()
void inches_2_centimeters ()
void inches_2_millimeters ()
void inches_2_meters ()
void inches_2_kilometers ()
void feet_2_inches ()
void feet_2_miles ()
void feet_2_centimeters ()
void feet_2_millimeters ()
void feet_2_meters ()
void feet_2_kilometers ()
void meters_2_inches ()
void meters_2_feet ()
void meters_2_miles ()
void meters_2_centimeters ()
void meters_2_millimeters ()
void meters_2_kilometers ()
void kilometers_2_inches ()
void kilometers_2_feet ()
void kilometers_2_miles ()
void kilometers_2_centimeters ()
void kilometers_2_millimeters ()
void miles_2_inches ()
void miles_2_feet ()
void miles_2_centimeters ()
void miles_2_millimeters ()
void miles_2_meters ()
void miles_2_kilometers ()
void milesperhour_2_kilometersperhour ()
void milesperhour_2_meterspersecond ()
void milesperhour_2_feetpersecond ()
void kilometersperhour_2_milesperhour ()
void kilometersperhour_2_meterspersecond ()
void kilometersperhour_2_feetpersecond ()
void meterspersecond_2_milesperhour ()
void meterspersecond_2_kilometersperhour ()
void meterspersecond_2_feetpersecond ()
void feetpersecond_2_milesperhour ()
void feetpersecond_2_kilometersperhour ()
void feetpersecond_2_meterspersecond ()
void pascals_2_hectopascals ()
void pascals_2_poundspersquareinch ()
void pascals_2_kilopascals ()
void hectopascals_2_pascals ()
void hectopascals_2_poundspersquareinch ()
void hectopascals_2_kilopascals ()
void poundspersquareinch_2_pascals ()
void poundspersquareinch_2_hectopascals ()
void poundspersquareinch_2_kilopascals ()
void kilopascals_2_hectopascals ()
void kilopascals_2_poundspersquareinch ()
void kilopascals_2_pascals ()
void FormatMeters ()
Static Private Member Functions
static string SigFig (float value, int sigfigs)
static void FloatCompare (float expected, float actual, string msg=null, params object[] args)
Private Attributes
const int SIGFIGS = 9
Detailed Description
Definition at line 7 of file UnitsTests.cs.
Member Function Documentation
celsius_2_farenheit()
void Juniper.UnitsTests.celsius_2_farenheit () inline
Definition at line 24 of file UnitsTests.cs.
         {
             FloatCompare(32, Units.Celsius.Farenheit(0));
             FloatCompare(212, Units.Celsius.Farenheit(100));
         }
References Juniper.Units.Celsius.Farenheit(), and Juniper.UnitsTests.FloatCompare().
celsius_2_kelvin()
void Juniper.UnitsTests.celsius_2_kelvin () inline
Definition at line 31 of file UnitsTests.cs.
         {
             FloatCompare(273.15f, Units.Celsius.Kelvin(0));
             FloatCompare(373.15f, Units.Celsius.Kelvin(100));
         }
References Juniper.UnitsTests.FloatCompare(), and Juniper.Units.Celsius.Kelvin().
centimeters_2_feet()
void Juniper.UnitsTests.centimeters_2_feet ()
centimeters_2_inches()
void Juniper.UnitsTests.centimeters_2_inches ()
centimeters_2_kilometers()
void Juniper.UnitsTests.centimeters_2_kilometers ()
centimeters_2_miles()
void Juniper.UnitsTests.centimeters_2_miles ()
centimeters_2_millimeters()
void Juniper.UnitsTests.centimeters_2_millimeters ()
degrees_2_hours()
void Juniper.UnitsTests.degrees_2_hours ()
degrees_2_radians()
void Juniper.UnitsTests.degrees_2_radians ()
farenheit_2_celsius()
void Juniper.UnitsTests.farenheit_2_celsius () inline
Definition at line 10 of file UnitsTests.cs.
         {
             FloatCompare(0, Units.Farenheit.Celsius(32));
             FloatCompare(100, Units.Farenheit.Celsius(212));
         }
References Juniper.Units.Farenheit.Celsius(), and Juniper.UnitsTests.FloatCompare().
Farenheit_2_kelvin()
void Juniper.UnitsTests.Farenheit_2_kelvin () inline
Definition at line 17 of file UnitsTests.cs.
         {
             FloatCompare(273.15f, Units.Farenheit.Kelvin(32));
             FloatCompare(373.15f, Units.Farenheit.Kelvin(212));
         }
References Juniper.UnitsTests.FloatCompare(), and Juniper.Units.Farenheit.Kelvin().
feet_2_centimeters()
void Juniper.UnitsTests.feet_2_centimeters ()
feet_2_inches()
void Juniper.UnitsTests.feet_2_inches ()
feet_2_kilometers()
void Juniper.UnitsTests.feet_2_kilometers ()
feet_2_meters()
void Juniper.UnitsTests.feet_2_meters ()
feet_2_miles()
void Juniper.UnitsTests.feet_2_miles ()
feet_2_millimeters()
void Juniper.UnitsTests.feet_2_millimeters ()
feetpersecond_2_kilometersperhour()
void Juniper.UnitsTests.feetpersecond_2_kilometersperhour ()
feetpersecond_2_meterspersecond()
void Juniper.UnitsTests.feetpersecond_2_meterspersecond ()
feetpersecond_2_milesperhour()
void Juniper.UnitsTests.feetpersecond_2_milesperhour ()
FloatCompare()
static void Juniper.UnitsTests.FloatCompare (float expected, float actual, string msg = null, params object [] args) static private
Referenced by Juniper.UnitsTests.celsius_2_farenheit(), Juniper.UnitsTests.celsius_2_kelvin(), Juniper.UnitsTests.farenheit_2_celsius(), Juniper.UnitsTests.Farenheit_2_kelvin(), Juniper.UnitsTests.kelvin_2_celsius(), and Juniper.UnitsTests.kelvin_2_farenheit().
FormatMeters()
void Juniper.UnitsTests.FormatMeters ()
grams_2_kilograms()
void Juniper.UnitsTests.grams_2_kilograms ()
grams_2_ounces()
void Juniper.UnitsTests.grams_2_ounces ()
grams_2_pounds()
void Juniper.UnitsTests.grams_2_pounds ()
grams_2_tons()
void Juniper.UnitsTests.grams_2_tons ()
hectopascals_2_kilopascals()
void Juniper.UnitsTests.hectopascals_2_kilopascals ()
hectopascals_2_pascals()
void Juniper.UnitsTests.hectopascals_2_pascals ()
hectopascals_2_poundspersquareinch()
void Juniper.UnitsTests.hectopascals_2_poundspersquareinch ()
hours_2_degrees()
void Juniper.UnitsTests.hours_2_degrees ()
hours_2_radians()
void Juniper.UnitsTests.hours_2_radians ()
inches_2_centimeters()
void Juniper.UnitsTests.inches_2_centimeters ()
inches_2_feet()
void Juniper.UnitsTests.inches_2_feet ()
inches_2_kilometers()
void Juniper.UnitsTests.inches_2_kilometers ()
inches_2_meters()
void Juniper.UnitsTests.inches_2_meters ()
inches_2_miles()
void Juniper.UnitsTests.inches_2_miles ()
inches_2_millimeters()
void Juniper.UnitsTests.inches_2_millimeters ()
kelvin_2_celsius()
void Juniper.UnitsTests.kelvin_2_celsius () inline
Definition at line 45 of file UnitsTests.cs.
         {
             FloatCompare(0, Units.Kelvin.Celsius(273.15f));
             FloatCompare(100, Units.Kelvin.Celsius(373.15f));
         }
References Juniper.Units.Kelvin.Celsius(), and Juniper.UnitsTests.FloatCompare().
kelvin_2_farenheit()
void Juniper.UnitsTests.kelvin_2_farenheit () inline
Definition at line 38 of file UnitsTests.cs.
         {
             FloatCompare(32, Units.Kelvin.Farenheit(273.15f));
             FloatCompare(212, Units.Kelvin.Farenheit(373.15f));
         }
References Juniper.Units.Kelvin.Farenheit(), and Juniper.UnitsTests.FloatCompare().
kilograms_2_grams()
void Juniper.UnitsTests.kilograms_2_grams ()
kilograms_2_ounces()
void Juniper.UnitsTests.kilograms_2_ounces ()
kilograms_2_pounds()
void Juniper.UnitsTests.kilograms_2_pounds ()
kilograms_2_tons()
void Juniper.UnitsTests.kilograms_2_tons ()
kilometers_2_centimeters()
void Juniper.UnitsTests.kilometers_2_centimeters ()
kilometers_2_feet()
void Juniper.UnitsTests.kilometers_2_feet ()
kilometers_2_inches()
void Juniper.UnitsTests.kilometers_2_inches ()
kilometers_2_miles()
void Juniper.UnitsTests.kilometers_2_miles ()
kilometers_2_millimeters()
void Juniper.UnitsTests.kilometers_2_millimeters ()
kilometersperhour_2_feetpersecond()
void Juniper.UnitsTests.kilometersperhour_2_feetpersecond ()
kilometersperhour_2_meterspersecond()
void Juniper.UnitsTests.kilometersperhour_2_meterspersecond ()
kilometersperhour_2_milesperhour()
void Juniper.UnitsTests.kilometersperhour_2_milesperhour ()
kilopascals_2_hectopascals()
void Juniper.UnitsTests.kilopascals_2_hectopascals ()
kilopascals_2_pascals()
void Juniper.UnitsTests.kilopascals_2_pascals ()
kilopascals_2_poundspersquareinch()
void Juniper.UnitsTests.kilopascals_2_poundspersquareinch ()
meters_2_centimeters()
void Juniper.UnitsTests.meters_2_centimeters ()
meters_2_feet()
void Juniper.UnitsTests.meters_2_feet ()
meters_2_inches()
void Juniper.UnitsTests.meters_2_inches ()
meters_2_kilometers()
void Juniper.UnitsTests.meters_2_kilometers ()
meters_2_miles()
void Juniper.UnitsTests.meters_2_miles ()
meters_2_millimeters()
void Juniper.UnitsTests.meters_2_millimeters ()
meterspersecond_2_feetpersecond()
void Juniper.UnitsTests.meterspersecond_2_feetpersecond ()
meterspersecond_2_kilometersperhour()
void Juniper.UnitsTests.meterspersecond_2_kilometersperhour ()
meterspersecond_2_milesperhour()
void Juniper.UnitsTests.meterspersecond_2_milesperhour ()
miles_2_centimeters()
void Juniper.UnitsTests.miles_2_centimeters ()
miles_2_feet()
void Juniper.UnitsTests.miles_2_feet ()
miles_2_inches()
void Juniper.UnitsTests.miles_2_inches ()
miles_2_kilometers()
void Juniper.UnitsTests.miles_2_kilometers ()
miles_2_meters()
void Juniper.UnitsTests.miles_2_meters ()
miles_2_millimeters()
void Juniper.UnitsTests.miles_2_millimeters ()
milesperhour_2_feetpersecond()
void Juniper.UnitsTests.milesperhour_2_feetpersecond ()
milesperhour_2_kilometersperhour()
void Juniper.UnitsTests.milesperhour_2_kilometersperhour ()
milesperhour_2_meterspersecond()
void Juniper.UnitsTests.milesperhour_2_meterspersecond ()
millimeters_2_centimeters()
void Juniper.UnitsTests.millimeters_2_centimeters ()
millimeters_2_feet()
void Juniper.UnitsTests.millimeters_2_feet ()
millimeters_2_inches()
void Juniper.UnitsTests.millimeters_2_inches ()
millimeters_2_kilometers()
void Juniper.UnitsTests.millimeters_2_kilometers ()
millimeters_2_miles()
void Juniper.UnitsTests.millimeters_2_miles ()
ounces_2_grams()
void Juniper.UnitsTests.ounces_2_grams ()
ounces_2_kilograms()
void Juniper.UnitsTests.ounces_2_kilograms ()
ounces_2_pounds()
void Juniper.UnitsTests.ounces_2_pounds ()
ounces_2_tons()
void Juniper.UnitsTests.ounces_2_tons ()
pascals_2_hectopascals()
void Juniper.UnitsTests.pascals_2_hectopascals ()
pascals_2_kilopascals()
void Juniper.UnitsTests.pascals_2_kilopascals ()
pascals_2_poundspersquareinch()
void Juniper.UnitsTests.pascals_2_poundspersquareinch ()
pounds_2_grams()
void Juniper.UnitsTests.pounds_2_grams ()
pounds_2_kilograms()
void Juniper.UnitsTests.pounds_2_kilograms ()
pounds_2_ounces()
void Juniper.UnitsTests.pounds_2_ounces ()
pounds_2_tons()
void Juniper.UnitsTests.pounds_2_tons ()
poundspersquareinch_2_hectopascals()
void Juniper.UnitsTests.poundspersquareinch_2_hectopascals ()
poundspersquareinch_2_kilopascals()
void Juniper.UnitsTests.poundspersquareinch_2_kilopascals ()
poundspersquareinch_2_pascals()
void Juniper.UnitsTests.poundspersquareinch_2_pascals ()
radians_2_degrees()
void Juniper.UnitsTests.radians_2_degrees ()
radians_2_hours()
void Juniper.UnitsTests.radians_2_hours ()
SigFig()
static string Juniper.UnitsTests.SigFig (float value, int sigfigs) inline static private
Definition at line 413 of file UnitsTests.cs.
         {
             var q = (int)Mathf.Log10(value) + 1;
             sigfigs -= q;
             var p = Mathf.Pow(10, sigfigs);
             var v = (Mathf.Round(value * p) / p).ToString();
             if (sigfigs > 0)
             {
                 var i = v.IndexOf(".", System.StringComparison.Ordinal);
                 if (i == -1)
                 {
                     v += ".";
                     i = v.Length - 1;
                 }
                 var z = sigfigs + i + 1;
                 while (v.Length < z)
                 {
                     v += "0";
                 }
             }
             return v;
         }
tons_2_grams()
void Juniper.UnitsTests.tons_2_grams ()
tons_2_kilograms()
void Juniper.UnitsTests.tons_2_kilograms ()
tons_2_ounces()
void Juniper.UnitsTests.tons_2_ounces ()
tons_2_pounds()
void Juniper.UnitsTests.tons_2_pounds ()
Member Data Documentation
SIGFIGS
const int Juniper.UnitsTests.SIGFIGS = 9 private
Definition at line 411 of file UnitsTests.cs.
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Tests/Juniper/Units/UnitsTests.cs