Juniper: Hjg.Pngcs.Chunks.ChunkHelper Class Reference
Hjg.Pngcs.Chunks.ChunkHelper Class Reference
Static utility methods for CHunks
Static Public Member Functions
static byte [] ToBytes (string x)
Converts to bytes using Latin1 (ISO-8859-1)
static string ToString (byte[] x)
Converts to string using Latin1 (ISO-8859-1)
static string ToString (byte[] x, int offset, int len)
Converts to string using Latin1 (ISO-8859-1)
static byte [] ToBytesUTF8 (string x)
Converts to bytes using UTF-8
static string ToStringUTF8 (byte[] x)
Converts to string using UTF-8
static string ToStringUTF8 (byte[] x, int offset, int len)
Converts to string using UTF-8
static void WriteBytesToStream (Stream stream, byte[] bytes)
Writes full array of bytes to stream
static bool IsCritical (string id)
Critical chunks: first letter is uppercase
static bool IsPublic (string id)
Public chunks: second letter is uppercase
static bool IsSafeToCopy (string id)
Safe to copy chunk: fourth letter is lower case
static bool IsUnknown (AbstractPngChunk chunk)
We consider a chunk as "unknown" if our chunk factory (even when it has been augmented by client code) doesn't recognize it
static int PosNullByte (byte[] bytes)
Finds position of null byte in array
static bool ShouldLoad (string id, ChunkLoadBehaviour behav)
Decides if a chunk should be loaded, according to a ChunkLoadBehaviour
static List< AbstractPngChunk > FilterList (List< AbstractPngChunk > list, IChunkPredicate predicateKeep)
Filters a list of Chunks, keeping those which match the predicate
static int TrimList (List< AbstractPngChunk > list, IChunkPredicate predicateRemove)
Filters a list of Chunks, removing those which match the predicate
static bool Equivalent (AbstractPngChunk c1, AbstractPngChunk c2)
Ad-hoc criteria for 'equivalent' chunks.
static bool IsText (AbstractPngChunk c)
Static Private Member Functions
static internal byte [] CompressBytes (byte[] ori, bool compress)
static internal byte [] CompressBytes (byte[] ori, int offset, int len, bool compress)
static void ShovelInToOut (Stream inx, Stream outx)
static internal bool MaskMatch (int v, int mask)
Private Attributes
internal const string IHDR = "IHDR"
internal const string PLTE = "PLTE"
internal const string IDAT = "IDAT"
internal const string IEND = "IEND"
internal const string cHRM = "cHRM"
internal const string gAMA = "gAMA"
internal const string iCCP = "iCCP"
internal const string sBIT = "sBIT"
internal const string sRGB = "sRGB"
internal const string bKGD = "bKGD"
internal const string hIST = "hIST"
internal const string tRNS = "tRNS"
internal const string pHYs = "pHYs"
internal const string sPLT = "sPLT"
internal const string tIME = "tIME"
internal const string iTXt = "iTXt"
internal const string tEXt = "tEXt"
Static Private Attributes
static internal readonly byte [] b_IHDR = ToBytes(IHDR)
static internal readonly byte [] b_PLTE = ToBytes(PLTE)
static internal readonly byte [] b_IDAT = ToBytes(IDAT)
static internal readonly byte [] b_IEND = ToBytes(IEND)
Detailed Description
Static utility methods for CHunks
Client code should rarely need this, see PngMetada and ChunksList
Definition at line 16 of file ChunkHelper.cs.
Member Function Documentation
CompressBytes() [1/2]
static internal byte [] Hjg.Pngcs.Chunks.ChunkHelper.CompressBytes (byte [] ori, bool compress) inline static private
Definition at line 230 of file ChunkHelper.cs.
         {
             return CompressBytes(ori, 0, ori.Length, compress);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.GetProfile(), Hjg.Pngcs.Chunks.PngChunkZTXT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkITXT.ParseFromRaw(), and Hjg.Pngcs.Chunks.PngChunkICCP.SetProfileNameAndContent().
CompressBytes() [2/2]
static internal byte [] Hjg.Pngcs.Chunks.ChunkHelper.CompressBytes (byte [] ori, int offset, int len, bool compress) inline static private
Definition at line 235 of file ChunkHelper.cs.
         {
             try
             {
                 var inb = new MemoryStream(ori, offset, len);
                 Stream inx = inb;
                 if (!compress)
                 {
                     inx = new ZlibInputStream(inb, false);
                 }
                 var outb = new MemoryStream();
                 Stream outx = outb;
                 if (compress)
                 {
                     outx = new ZlibOutputStream(outb, DeflateCompressLevel.DEFAULT, EDeflateCompressStrategy.Default, false);
                 }
                 ShovelInToOut(inx, outx);
                 inx.Close();
                 outx.Close();
                 var res = outb.ToArray();
                 return res;
             }
             catch (Exception e)
             {
                 throw new PngjException(e);
             }
         }
References Hjg.Pngcs.Zlib.DeflateCompressLevel.DEFAULT, and Hjg.Pngcs.Chunks.ChunkHelper.ShovelInToOut().
Equivalent()
static bool Hjg.Pngcs.Chunks.ChunkHelper.Equivalent (AbstractPngChunk c1, AbstractPngChunk c2) inline static
Ad-hoc criteria for 'equivalent' chunks.
Two chunks are equivalent if they have the same Id AND either:
they are Single
both are textual and have the same key
both are SPLT and have the same palette name Bear in mind that this is an ad-hoc, non-standard, nor required (nor wrong) criterion. Use it only if you find it useful. Notice that PNG allows to have repeated textual keys with same keys.
Parameters
c1 Chunk1
c2 Chunk1
Returns
true if equivalent
Definition at line 360 of file ChunkHelper.cs.
         {
             if (c1 == c2)
             {
                 return true;
             }
             if (c1 is null
                 || c2 is null
                 || !c1.Id.Equals(c2.Id, StringComparison.Ordinal))
             {
                 return false;
             }
             // same id
             if (c1.GetType() != c2.GetType())
             {
                 return false; // should not happen
             }
             if (!c2.AllowsMultiple())
             {
                 return true;
             }
             if (c1 is AbstractPngChunkTextVar pngChunkTextVar)
             {
                 return pngChunkTextVar
                     .Key
                     .Equals(((AbstractPngChunkTextVar)c2).Key, StringComparison.Ordinal);
             }
             if (c1 is PngChunkSPLT pngChunkSPLT)
             {
                 return pngChunkSPLT.PalName.Equals(((PngChunkSPLT)c2).PalName, StringComparison.Ordinal);
             }
             // unknown chunks that allow multiple? consider they don't match
             return false;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.AllowsMultiple(), and Hjg.Pngcs.Chunks.AbstractPngChunk.Id.
Referenced by Hjg.Pngcs.Chunks.ChunkPredicateEquiv.Matches().
FilterList()
static List<AbstractPngChunk> Hjg.Pngcs.Chunks.ChunkHelper.FilterList (List< AbstractPngChunk > list, IChunkPredicate predicateKeep) inline static
Filters a list of Chunks, keeping those which match the predicate
The original list is not altered
Parameters
list
predicateKeep
Returns
Definition at line 287 of file ChunkHelper.cs.
         {
             if (list is null)
             {
                 throw new ArgumentNullException(nameof(list));
             }
             if (predicateKeep is null)
             {
                 throw new ArgumentNullException(nameof(predicateKeep));
             }
             var result = new List<AbstractPngChunk>();
             foreach (var element in list)
             {
                 if (predicateKeep.Matches(element))
                 {
                     result.Add(element);
                 }
             }
             return result;
         }
Referenced by Hjg.Pngcs.Chunks.ChunksList.GetEquivalent(), and Hjg.Pngcs.Chunks.ChunksList.GetXById().
IsCritical()
static bool Hjg.Pngcs.Chunks.ChunkHelper.IsCritical (string id) inline static
Critical chunks: first letter is uppercase
Parameters
id
Returns
Definition at line 129 of file ChunkHelper.cs.
         {
             if (string.IsNullOrEmpty(id))
             {
                 throw new ArgumentException("IsCritical flag occurs in first character of ID.", nameof(id));
             }
             // first letter is uppercase
             return char.IsUpper(id[0]);
         }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.Chunks.ChunkHelper.ShouldLoad(), and Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
IsPublic()
static bool Hjg.Pngcs.Chunks.ChunkHelper.IsPublic (string id) inline static
Public chunks: second letter is uppercase
Parameters
id
Returns
Definition at line 145 of file ChunkHelper.cs.
         {
             if (string.IsNullOrEmpty(id))
             {
                 throw new ArgumentException("IsPublic flag occurs in second character of ID.", nameof(id));
             }
             // public chunk?
             return char.IsUpper(id[1]);
         }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk().
IsSafeToCopy()
static bool Hjg.Pngcs.Chunks.ChunkHelper.IsSafeToCopy (string id) inline static
Safe to copy chunk: fourth letter is lower case
Parameters
id
Returns
Definition at line 161 of file ChunkHelper.cs.
         {
             if (string.IsNullOrEmpty(id))
             {
                 throw new ArgumentException("IsSafeToCopy flag occurs in fourth character of ID.", nameof(id));
             }
             // safe to copy?
             // fourth letter is lower case
             return !char.IsUpper(id[3]);
         }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), and Hjg.Pngcs.Chunks.ChunkHelper.ShouldLoad().
IsText()
static bool Hjg.Pngcs.Chunks.ChunkHelper.IsText (AbstractPngChunk c) inline static
Definition at line 401 of file ChunkHelper.cs.
         {
             return c is AbstractPngChunkTextVar;
         }
IsUnknown()
static bool Hjg.Pngcs.Chunks.ChunkHelper.IsUnknown (AbstractPngChunk chunk) inline static
We consider a chunk as "unknown" if our chunk factory (even when it has been augmented by client code) doesn't recognize it
Parameters
chunk
Returns
Definition at line 178 of file ChunkHelper.cs.
         {
             return chunk is PngChunkUNKNOWN;
         }
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
MaskMatch()
static internal bool Hjg.Pngcs.Chunks.ChunkHelper.MaskMatch (int v, int mask) inline static private
Definition at line 275 of file ChunkHelper.cs.
         {
             return (v & mask) != 0;
         }
Referenced by Hjg.Pngcs.PngWriter.CopyChunks().
PosNullByte()
static int Hjg.Pngcs.Chunks.ChunkHelper.PosNullByte (byte [] bytes) inline static
Finds position of null byte in array
Parameters
bytes
Returns
-1 if not found
Definition at line 188 of file ChunkHelper.cs.
         {
             if (bytes is null)
             {
                 throw new ArgumentNullException(nameof(bytes));
             }
             for (var i = 0; i < bytes.Length; i++)
             {
                 if (bytes[i] == 0)
                 {
                     return i;
                 }
             }
             return -1;
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkICCP.ParseFromRaw().
ShouldLoad()
static bool Hjg.Pngcs.Chunks.ChunkHelper.ShouldLoad (string id, ChunkLoadBehaviour behav) inline static
Decides if a chunk should be loaded, according to a ChunkLoadBehaviour
Parameters
id
behav
Returns
Definition at line 212 of file ChunkHelper.cs.
         {
             if (IsCritical(id))
             {
                 return true;
             }
             var kwown = AbstractPngChunk.IsKnown(id);
             return behav switch
             {
                 ChunkLoadBehaviour.LOAD_CHUNK_ALWAYS => true,
                 ChunkLoadBehaviour.LOAD_CHUNK_IF_SAFE => kwown || IsSafeToCopy(id),
                 ChunkLoadBehaviour.LOAD_CHUNK_KNOWN => kwown,
                 ChunkLoadBehaviour.LOAD_CHUNK_NEVER => false,
                 _ => false,// should not reach here
             };
         }
References Hjg.Pngcs.Chunks.ChunkHelper.IsCritical(), Hjg.Pngcs.Chunks.AbstractPngChunk.IsKnown(), and Hjg.Pngcs.Chunks.ChunkHelper.IsSafeToCopy().
Referenced by Hjg.Pngcs.PngReader.ReadChunk().
ShovelInToOut()
static void Hjg.Pngcs.Chunks.ChunkHelper.ShovelInToOut (Stream inx, Stream outx) inline static private
Definition at line 265 of file ChunkHelper.cs.
         {
             var buffer = new byte[1024];
             int len;
             while ((len = inx.Read(buffer, 0, 1024)) > 0)
             {
                 outx.Write(buffer, 0, len);
             }
         }
Referenced by Hjg.Pngcs.Chunks.ChunkHelper.CompressBytes().
ToBytes()
static byte [] Hjg.Pngcs.Chunks.ChunkHelper.ToBytes (string x) inline static
Converts to bytes using Latin1 (ISO-8859-1)
Parameters
x
Returns
Definition at line 45 of file ChunkHelper.cs.
         {
             return Hjg.Pngcs.PngHelperInternal.charsetLatin1.GetBytes(x);
         }
References Hjg.Pngcs.PngHelperInternal.charsetLatin1.
Referenced by Hjg.Pngcs.Chunks.ChunkRaw.ChunkRaw(), Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkICCP.SetProfileNameAndContent().
ToBytesUTF8()
static byte [] Hjg.Pngcs.Chunks.ChunkHelper.ToBytesUTF8 (string x) inline static
Converts to bytes using UTF-8
Parameters
x
Returns
Definition at line 77 of file ChunkHelper.cs.
         {
             return Encoding.UTF8.GetBytes(x);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk().
ToString() [1/2]
static string Hjg.Pngcs.Chunks.ChunkHelper.ToString (byte [] x) inline static
Converts to string using Latin1 (ISO-8859-1)
Parameters
x
Returns
Definition at line 55 of file ChunkHelper.cs.
         {
             return Hjg.Pngcs.PngHelperInternal.charsetLatin1.GetString(x);
         }
References Hjg.Pngcs.PngHelperInternal.charsetLatin1.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.Factory(), Hjg.Pngcs.Chunks.PngChunkICCP.GetProfileAsString(), Hjg.Pngcs.Chunks.PngChunkZTXT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkITXT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkSPLT.ParseFromRaw(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.Chunks.ChunkRaw.ToString(), and Hjg.Pngcs.Chunks.ChunkRaw.WriteChunk().
ToString() [2/2]
static string Hjg.Pngcs.Chunks.ChunkHelper.ToString (byte [] x, int offset, int len) inline static
Converts to string using Latin1 (ISO-8859-1)
Parameters
x
offset
len
Returns
Definition at line 67 of file ChunkHelper.cs.
         {
             return Hjg.Pngcs.PngHelperInternal.charsetLatin1.GetString(x, offset, len);
         }
References Hjg.Pngcs.PngHelperInternal.charsetLatin1.
ToStringUTF8() [1/2]
static string Hjg.Pngcs.Chunks.ChunkHelper.ToStringUTF8 (byte [] x) inline static
Converts to string using UTF-8
Parameters
x
Returns
Definition at line 87 of file ChunkHelper.cs.
         {
             return Encoding.UTF8.GetString(x);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkITXT.ParseFromRaw().
ToStringUTF8() [2/2]
static string Hjg.Pngcs.Chunks.ChunkHelper.ToStringUTF8 (byte [] x, int offset, int len) inline static
Converts to string using UTF-8
Parameters
x
offset
len
Returns
Definition at line 99 of file ChunkHelper.cs.
         {
             return Encoding.UTF8.GetString(x, offset, len);
         }
TrimList()
static int Hjg.Pngcs.Chunks.ChunkHelper.TrimList (List< AbstractPngChunk > list, IChunkPredicate predicateRemove) inline static
Filters a list of Chunks, removing those which match the predicate
The original list is not altered
Parameters
list
predicateRemove
Returns
Definition at line 319 of file ChunkHelper.cs.
         {
             if (list is null)
             {
                 throw new ArgumentNullException(nameof(list));
             }
             if (predicateRemove is null)
             {
                 throw new ArgumentNullException(nameof(predicateRemove));
             }
             var cont = 0;
             for (var i = list.Count - 1; i >= 0; i--)
             {
                 if (predicateRemove.Matches(list[i]))
                 {
                     list.RemoveAt(i);
                     cont++;
                 }
             }
             return cont;
         }
References Hjg.Pngcs.Chunks.IChunkPredicate.Matches().
Referenced by Hjg.Pngcs.Chunks.PngMetadata.QueueChunk().
WriteBytesToStream()
static void Hjg.Pngcs.Chunks.ChunkHelper.WriteBytesToStream (Stream stream, byte [] bytes) inline static
Writes full array of bytes to stream
Parameters
stream
bytes
Definition at line 109 of file ChunkHelper.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             if (bytes is null)
             {
                 throw new ArgumentNullException(nameof(bytes));
             }
             stream.Write(bytes, 0, bytes.Length);
         }
Referenced by Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk().
Member Data Documentation
b_IDAT
internal readonly byte [] Hjg.Pngcs.Chunks.ChunkHelper.b_IDAT = ToBytes(IDAT) static private
Definition at line 37 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.PngIDatChunkOutputStream.FlushBuffer(), Hjg.Pngcs.PngReader.ReadFirstChunks(), and Hjg.Pngcs.PngReader.ReadLastChunks().
b_IEND
internal readonly byte [] Hjg.Pngcs.Chunks.ChunkHelper.b_IEND = ToBytes(IEND) static private
Definition at line 38 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkIEND.CreateRawChunk(), Hjg.Pngcs.PngReader.ReadFirstChunks(), and Hjg.Pngcs.PngReader.ReadLastChunks().
b_IHDR
internal readonly byte [] Hjg.Pngcs.Chunks.ChunkHelper.b_IHDR = ToBytes(IHDR) static private
Definition at line 35 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.PngChunkIHDR.CreateRawChunk(), and Hjg.Pngcs.PngReader.PngReader().
b_PLTE
internal readonly byte [] Hjg.Pngcs.Chunks.ChunkHelper.b_PLTE = ToBytes(PLTE) static private
Definition at line 36 of file ChunkHelper.cs.
bKGD
internal const string Hjg.Pngcs.Chunks.ChunkHelper.bKGD = "bKGD" private
Definition at line 27 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
cHRM
internal const string Hjg.Pngcs.Chunks.ChunkHelper.cHRM = "cHRM" private
Definition at line 22 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
gAMA
internal const string Hjg.Pngcs.Chunks.ChunkHelper.gAMA = "gAMA" private
Definition at line 23 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
hIST
internal const string Hjg.Pngcs.Chunks.ChunkHelper.hIST = "hIST" private
Definition at line 28 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), and Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
iCCP
internal const string Hjg.Pngcs.Chunks.ChunkHelper.iCCP = "iCCP" private
Definition at line 24 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
IDAT
internal const string Hjg.Pngcs.Chunks.ChunkHelper.IDAT = "IDAT" private
Definition at line 20 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
IEND
internal const string Hjg.Pngcs.Chunks.ChunkHelper.IEND = "IEND" private
Definition at line 21 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
IHDR
internal const string Hjg.Pngcs.Chunks.ChunkHelper.IHDR = "IHDR" private
Definition at line 18 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
iTXt
internal const string Hjg.Pngcs.Chunks.ChunkHelper.iTXt = "iTXt" private
Definition at line 33 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.GetTxtsForKey(), and Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
pHYs
internal const string Hjg.Pngcs.Chunks.ChunkHelper.pHYs = "pHYs" private
Definition at line 30 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngMetadata.GetDpi(), and Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
PLTE
internal const string Hjg.Pngcs.Chunks.ChunkHelper.PLTE = "PLTE" private
Definition at line 19 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite(), and Hjg.Pngcs.Chunks.ChunksListForWrite.WriteChunks().
sBIT
internal const string Hjg.Pngcs.Chunks.ChunkHelper.sBIT = "sBIT" private
Definition at line 25 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
sPLT
internal const string Hjg.Pngcs.Chunks.ChunkHelper.sPLT = "sPLT" private
Definition at line 31 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
sRGB
internal const string Hjg.Pngcs.Chunks.ChunkHelper.sRGB = "sRGB" private
Definition at line 26 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
tEXt
internal const string Hjg.Pngcs.Chunks.ChunkHelper.tEXt = "tEXt" private
Definition at line 34 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.Chunks.PngMetadata.GetTxtsForKey(), and Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
tIME
internal const string Hjg.Pngcs.Chunks.ChunkHelper.tIME = "tIME" private
Definition at line 32 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.Chunks.PngMetadata.GetTime(), and Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
tRNS
internal const string Hjg.Pngcs.Chunks.ChunkHelper.tRNS = "tRNS" private
Definition at line 29 of file ChunkHelper.cs.
Referenced by Hjg.Pngcs.PngWriter.CopyChunks(), and Hjg.Pngcs.Chunks.AbstractPngChunk.InitFactory().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Chunks/ChunkHelper.cs