Juniper: Juniper.Unity.Widgets.QualityDegrader Class Reference
Juniper.Unity.Widgets.QualityDegrader Class Reference
This component manages the quality settings on the fly, making sure the application never falls below 50 FPS minimum. Only one of these components is allowed on a GameObject.
Public Member Functions
void Awake ()
Setup the statistics tracking and get the main camera.
void Update ()
Check to see if the average frame delta time (minus outliers) has dropped below 30FPS.
Public Attributes
Button [] qualityButtons
Properties
int QualityLevel [get, set]
Get the current graphics quality level.
string QualityName [get]
Get the name of the current graphics quality level.
bool IsBad [get]
Returns true when the frame rate drops below 30FPS.
Private Member Functions
void ChangeQuality (Action< bool > changer, Func< int, int, bool > checker, int value)
UnityAction QualityValueChange (int i)
void UpdateButtons (int value)
Private Attributes
Ground.Ground ground
readonly SingleStatistics frameStats = new SingleStatistics(30)
Calculates statistics for the frame delta time value, for knowing the mean value and rejecting outliers.
DisplayManager display
const string GRAPHICS_QUALITY_KEY = "GraphicsQuality"
Detailed Description
This component manages the quality settings on the fly, making sure the application never falls below 50 FPS minimum. Only one of these components is allowed on a GameObject.
Definition at line 22 of file QualityDegrader.cs.
Member Function Documentation
Awake()
void Juniper.Unity.Widgets.QualityDegrader.Awake () inline
Setup the statistics tracking and get the main camera.
Definition at line 127 of file QualityDegrader.cs.
         {
             ground = ComponentExt.FindAny<Ground.Ground>();
 #if UNITY_POSTPROCESSING
             prost = GetComponent<PostProcessLayer>();
 #endif
             display = ComponentExt.FindAny<DisplayManager>();
             if (qualityButtons != null)
             {
                 for (int i = 0; i < qualityButtons.Length; ++i)
                 {
                     qualityButtons[i].onClick.AddListener(QualityValueChange(i));
                 }
             }
             QualityLevel = PlayerPrefs.GetInt(GRAPHICS_QUALITY_KEY, QualityLevel);
             UpdateButtons(QualityLevel);
         }
References Juniper.Unity.Widgets.QualityDegrader.display, Juniper.Unity.Widgets.QualityDegrader.GRAPHICS_QUALITY_KEY, Juniper.Unity.Widgets.QualityDegrader.ground, Juniper.Unity.Widgets.QualityDegrader.qualityButtons, Juniper.Unity.Widgets.QualityDegrader.QualityLevel, Juniper.Unity.Widgets.QualityDegrader.QualityValueChange(), and Juniper.Unity.Widgets.QualityDegrader.UpdateButtons().
ChangeQuality()
void Juniper.Unity.Widgets.QualityDegrader.ChangeQuality (Action< bool > changer, Func< int, int, bool > checker, int value) inline private
Definition at line 73 of file QualityDegrader.cs.
         {
             var lastValue = QualityLevel;
             while (checker(lastValue, value))
             {
                 changer(true);
                 var newValue = QualityLevel;
                 if (newValue == lastValue)
                 {
                     throw new Exception("Could not change quality level");
                 }
                 else
                 {
                     lastValue = newValue;
                 }
             }
         }
References Juniper.Unity.Widgets.QualityDegrader.QualityLevel.
QualityValueChange()
UnityAction Juniper.Unity.Widgets.QualityDegrader.QualityValueChange (int i) inline private
Definition at line 149 of file QualityDegrader.cs.
         {
             return () => QualityLevel = i;
         }
References Juniper.Unity.Widgets.QualityDegrader.QualityLevel.
Referenced by Juniper.Unity.Widgets.QualityDegrader.Awake().
Update()
void Juniper.Unity.Widgets.QualityDegrader.Update () inline
Check to see if the average frame delta time (minus outliers) has dropped below 30FPS.
Definition at line 157 of file QualityDegrader.cs.
         {
             if (frameStats.IsSaturated && IsBad)
             {
                 if (QualityLevel > 0)
                 {
                     --QualityLevel;
                 }
                 ScreenDebugger.Print(QualityName);
                 frameStats.Clear();
             }
         }
References Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.Clear(), Juniper.Unity.Widgets.QualityDegrader.frameStats, Juniper.Unity.Widgets.QualityDegrader.IsBad, Juniper.Collections.Statistics.AbstractCollectionStatistics< T >.IsSaturated, System.ScreenDebugger.Print(), Juniper.Unity.Widgets.QualityDegrader.QualityLevel, and Juniper.Unity.Widgets.QualityDegrader.QualityName.
UpdateButtons()
void Juniper.Unity.Widgets.QualityDegrader.UpdateButtons (int value) inline private
Definition at line 171 of file QualityDegrader.cs.
         {
             if (qualityButtons != null)
             {
                 for (int i = 0; i < qualityButtons.Length; ++i)
                 {
                     qualityButtons[i].interactable = value != i;
                 }
             }
         }
References Juniper.Unity.Widgets.QualityDegrader.qualityButtons.
Referenced by Juniper.Unity.Widgets.QualityDegrader.Awake().
Member Data Documentation
display
DisplayManager Juniper.Unity.Widgets.QualityDegrader.display private
Definition at line 34 of file QualityDegrader.cs.
Referenced by Juniper.Unity.Widgets.QualityDegrader.Awake().
frameStats
readonly SingleStatistics Juniper.Unity.Widgets.QualityDegrader.frameStats = new SingleStatistics(30) private
Calculates statistics for the frame delta time value, for knowing the mean value and rejecting outliers.
Definition at line 32 of file QualityDegrader.cs.
Referenced by Juniper.Unity.Widgets.QualityDegrader.Update().
GRAPHICS_QUALITY_KEY
const string Juniper.Unity.Widgets.QualityDegrader.GRAPHICS_QUALITY_KEY = "GraphicsQuality" private
Definition at line 122 of file QualityDegrader.cs.
Referenced by Juniper.Unity.Widgets.QualityDegrader.Awake().
ground
Ground.Ground Juniper.Unity.Widgets.QualityDegrader.ground private
Definition at line 26 of file QualityDegrader.cs.
Referenced by Juniper.Unity.Widgets.QualityDegrader.Awake().
qualityButtons
Button [] Juniper.Unity.Widgets.QualityDegrader.qualityButtons
Definition at line 24 of file QualityDegrader.cs.
Referenced by Juniper.Unity.Widgets.QualityDegrader.Awake(), Juniper.Unity.MasterSceneController.SetupSystemInterface(), and Juniper.Unity.Widgets.QualityDegrader.UpdateButtons().
Property Documentation
IsBad
bool Juniper.Unity.Widgets.QualityDegrader.IsBad get private
Returns true when the frame rate drops below 30FPS.
true if is bad; otherwise, false.
Definition at line 108 of file QualityDegrader.cs.
         {
             get
             {
                 return frameStats.Mean / 30f < 1f;
             }
         }
Referenced by Juniper.Unity.Widgets.QualityDegrader.Update().
QualityLevel
int Juniper.Unity.Widgets.QualityDegrader.QualityLevel get set
Get the current graphics quality level.
The quality level.
Definition at line 41 of file QualityDegrader.cs.
         {
             get
             {
                 return QualitySettings.GetQualityLevel();
             }
             set
             {
                 if (value != QualityLevel)
                 {
                     display.DisableDisplay();
                     ChangeQuality(QualitySettings.IncreaseLevel, (a, b) => a < b, value);
                     ChangeQuality(QualitySettings.DecreaseLevel, (a, b) => a > b, value);
                     display.ResumeDisplay();
                     if (ground != null)
                     {
                         ground.spatialMappingFidelity = (Level)(value / 2);
                     }
 #if UNITY_POSTPROCESSING
                     prost.enabled = QualityLevel >= 4;
 #endif
                     PlayerPrefs.SetInt(GRAPHICS_QUALITY_KEY, value);
                     PlayerPrefs.Save();
                 }
                 UpdateButtons(value);
             }
         }
Referenced by Juniper.Unity.Widgets.QualityDegrader.Awake(), Juniper.Unity.Widgets.QualityDegrader.ChangeQuality(), Juniper.Unity.Widgets.QualityDegrader.QualityValueChange(), and Juniper.Unity.Widgets.QualityDegrader.Update().
QualityName
string Juniper.Unity.Widgets.QualityDegrader.QualityName get private
Get the name of the current graphics quality level.
The name of the quality.
Definition at line 96 of file QualityDegrader.cs.
         {
             get
             {
                 return QualitySettings.names[QualityLevel];
             }
         }
Referenced by Juniper.Unity.Widgets.QualityDegrader.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/Widgets/QualityDegrader.cs