Juniper: Juniper.Display.AbstractPassthroughDisplayManager Class Reference
Juniper.Display.AbstractPassthroughDisplayManager Class Reference
Public Member Functions
void StartXRDisplay ()
void StopXRDisplay ()
void DisableDisplay ()
void StartAR ()
void StopAR ()
void ToggleAR ()
virtual void Awake ()
virtual void Reinstall ()
void Reset ()
virtual void Install (bool reset)
virtual void Uninstall ()
virtual void Update ()
Updates the camera FOV according to game window dimensions, and moves the camera into position at the avatar height.
Public Attributes
Material ARBackgroundMaterial
On ARKit and ARCore systems, a special material for displaying the camera image needs to be configured. Vuforia does this on its own, and HoloLens has a clear display so it isn't needed.
bool enablePointCloud = true
On ARKit and ARCore, perform an image analysis algorithm that renders a point cloud of feature points.
Protected Attributes
JuniperPlatform jp
Properties
static Camera MainCamera [get]
virtual float DEFAULT_FOV [get]
Gets the field of view value that should be targeted for the running application.
float VerticalFieldOfView [get]
The camera field of view along the large screen axis in portrait mode, the narrow axis in landscape mode.
Detailed Description
Definition at line 5 of file AbstractPassthroughDisplayManager.cs.
Member Function Documentation
Awake()
virtual void Juniper.Display.AbstractDisplayManager.Awake () inline virtual inherited
Definition at line 215 of file AbstractDisplayManager.cs.
         {
             cam = GetComponent<Camera>();
             Install(false);
             lastSystem = jp.System;
             lastDisplayType = jp.DisplayType;
             lastARMode = jp.ARMode;
             lastOption = jp.Option;
             StartXRDisplay();
         }
References Juniper.JuniperPlatform.ARMode, Juniper.Display.AbstractDisplayManager.cam, Juniper.JuniperPlatform.DisplayType, Juniper.Display.AbstractDisplayManager.Install(), Juniper.Display.AbstractDisplayManager.jp, Juniper.Display.AbstractDisplayManager.lastARMode, Juniper.Display.AbstractDisplayManager.lastDisplayType, Juniper.Display.AbstractDisplayManager.lastOption, Juniper.Display.AbstractDisplayManager.lastSystem, Juniper.JuniperPlatform.Option, Juniper.Display.AbstractDisplayManager.StartXRDisplay(), and Juniper.JuniperPlatform.System.
DisableDisplay()
void Juniper.Display.AbstractDisplayManager.DisableDisplay () inline inherited
Definition at line 142 of file AbstractDisplayManager.cs.
         {
             ChangeDisplayType(DisplayTypes.None);
         }
References Juniper.Display.AbstractDisplayManager.ChangeDisplayType().
Install()
virtual void Juniper.Display.AbstractDisplayManager.Install (bool reset) inline virtual inherited
Implements Juniper.IInstallable.
Reimplemented in Juniper.Display.ARCoreDisplayManager, Juniper.Display.VuforiaDisplayManager, and Juniper.Display.OculusDisplayManager.
Definition at line 243 of file AbstractDisplayManager.cs.
         {
             reset &= Application.isEditor;
             jp = ComponentExt.FindAny<JuniperPlatform>();
             this.EnsureComponent<QualityDegrader>();
             this.EnsureComponent<CameraControl>();
 #if UNITY_MODULES_AUDIO
             listener = this.EnsureComponent<AudioListener>().Value;
 #if RESONANCE
             goog = listener.EnsureComponent<ResonanceAudioListener>().Value;
             goog.stereoSpeakerModeEnabled = true;
 #endif
 #endif
         }
References Juniper.Display.AbstractDisplayManager.jp.
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), and Juniper.Display.AbstractDisplayManager.Reinstall().
Reinstall()
virtual void Juniper.Display.AbstractDisplayManager.Reinstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 229 of file AbstractDisplayManager.cs.
         {
             Install(true);
         }
References Juniper.Display.AbstractDisplayManager.Install().
Referenced by Juniper.Display.AbstractDisplayManager.Reset().
Reset()
void Juniper.Display.AbstractDisplayManager.Reset () inline inherited
Definition at line 236 of file AbstractDisplayManager.cs.
         {
             Reinstall();
         }
References Juniper.Display.AbstractDisplayManager.Reinstall().
StartAR()
void Juniper.Display.AbstractDisplayManager.StartAR () inline inherited
Definition at line 173 of file AbstractDisplayManager.cs.
         {
             ChangeARMode(jp.SupportedARMode);
         }
References Juniper.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Display.AbstractDisplayManager.jp, and Juniper.JuniperPlatform.SupportedARMode.
Referenced by Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.ToggleAR(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
StartXRDisplay()
void Juniper.Display.AbstractDisplayManager.StartXRDisplay () inline inherited
Definition at line 132 of file AbstractDisplayManager.cs.
         {
             ChangeDisplayType(jp.SupportedDisplayType);
         }
References Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.jp, and Juniper.JuniperPlatform.SupportedDisplayType.
Referenced by Juniper.Display.AbstractDisplayManager.Awake().
StopAR()
void Juniper.Display.AbstractDisplayManager.StopAR () inline inherited
Definition at line 178 of file AbstractDisplayManager.cs.
         {
             ChangeARMode(AugmentedRealityTypes.None);
         }
References Juniper.Display.AbstractDisplayManager.ChangeARMode().
Referenced by Juniper.Display.AbstractDisplayManager.ToggleAR(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
StopXRDisplay()
void Juniper.Display.AbstractDisplayManager.StopXRDisplay () inline inherited
Definition at line 137 of file AbstractDisplayManager.cs.
         {
             ChangeDisplayType(DisplayTypes.Monoscopic);
         }
References Juniper.Display.AbstractDisplayManager.ChangeDisplayType().
ToggleAR()
void Juniper.Display.AbstractDisplayManager.ToggleAR () inline inherited
Definition at line 183 of file AbstractDisplayManager.cs.
         {
             if (jp.ARMode == AugmentedRealityTypes.None)
             {
                 StartAR();
             }
             else
             {
                 StopAR();
             }
         }
References Juniper.JuniperPlatform.ARMode, Juniper.Display.AbstractDisplayManager.jp, Juniper.Display.AbstractDisplayManager.StartAR(), and Juniper.Display.AbstractDisplayManager.StopAR().
Uninstall()
virtual void Juniper.Display.AbstractDisplayManager.Uninstall () inline virtual inherited
Implements Juniper.IInstallable.
Reimplemented in Juniper.Display.ARCoreDisplayManager, Juniper.Display.OculusDisplayManager, and Juniper.Display.VuforiaDisplayManager.
Definition at line 262 of file AbstractDisplayManager.cs.
         {
 #if UNITY_MODULES_AUDIO
 #if RESONANCE
             ComponentExt.FindAny<AudioListener>()
                 ?.RemoveComponent<ResonanceAudioListener>();
 #endif
             this.EnsureComponent<AudioListener>();
 #endif
         }
Update()
virtual void Juniper.Display.AbstractDisplayManager.Update () inline virtual inherited
Updates the camera FOV according to game window dimensions, and moves the camera into position at the avatar height.
Reimplemented in Juniper.Display.ARCoreDisplayManager.
Definition at line 324 of file AbstractDisplayManager.cs.
         {
             if (jp.CurrentPlatform != JuniperPlatform.CURRENT_PLATFORM)
             {
                 Debug.LogWarning($"Cannot change {nameof(Platform)} directly. Use the Juniper menu in the Unity Editor.");
                 jp.CurrentPlatform = JuniperPlatform.CURRENT_PLATFORM;
             }
             if (jp.System != lastSystem)
             {
                 Debug.LogWarning($"Cannot change {nameof(jp.System)} directly. Use the Juniper menu in the Unity Editor.");
                 jp.System = lastSystem;
             }
             if (jp.DisplayType != lastDisplayType)
             {
                 Debug.LogWarning($"Cannot change {nameof(jp.DisplayType)} directly. Use the {nameof(StartXRDisplay)} method.");
                 jp.DisplayType = lastDisplayType;
             }
             if (jp.ARMode != lastARMode)
             {
                 Debug.LogWarning($"Cannot change {nameof(jp.ARMode)} directly. Use the {nameof(StartAR)} method.");
                 jp.ARMode = lastARMode;
             }
             if (jp.Option != lastOption)
             {
                 Debug.LogWarning($"Cannot change {nameof(jp.Option)} directly. Use the Juniper menu in the Unity Editor.");
                 jp.Option = lastOption;
             }
             if (!Mathf.Approximately(MainCamera.fieldOfView, VerticalFieldOfView))
             {
                 MainCamera.fieldOfView = VerticalFieldOfView;
             }
         }
References Juniper.JuniperPlatform.ARMode, Juniper.JuniperPlatform.CURRENT_PLATFORM, Juniper.JuniperPlatform.CurrentPlatform, Juniper.JuniperPlatform.DisplayType, Juniper.Display.AbstractDisplayManager.jp, Juniper.Display.AbstractDisplayManager.lastARMode, Juniper.Display.AbstractDisplayManager.lastDisplayType, Juniper.Display.AbstractDisplayManager.lastOption, Juniper.Display.AbstractDisplayManager.lastSystem, Juniper.Display.AbstractDisplayManager.MainCamera, Juniper.JuniperPlatform.Option, Juniper.JuniperPlatform.System, and Juniper.Display.AbstractDisplayManager.VerticalFieldOfView.
Member Data Documentation
ARBackgroundMaterial
Material Juniper.Display.AbstractPassthroughDisplayManager.ARBackgroundMaterial
On ARKit and ARCore systems, a special material for displaying the camera image needs to be configured. Vuforia does this on its own, and HoloLens has a clear display so it isn't needed.
Definition at line 12 of file AbstractPassthroughDisplayManager.cs.
Referenced by Juniper.Display.ARCoreDisplayManager.Install().
enablePointCloud
bool Juniper.Display.AbstractPassthroughDisplayManager.enablePointCloud = true
On ARKit and ARCore, perform an image analysis algorithm that renders a point cloud of feature points.
Definition at line 18 of file AbstractPassthroughDisplayManager.cs.
jp
JuniperPlatform Juniper.Display.AbstractDisplayManager.jp protected inherited
Definition at line 22 of file AbstractDisplayManager.cs.
Referenced by Juniper.Display.AbstractDisplayManager.Awake(), Juniper.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Display.AbstractDisplayManager.Install(), Juniper.Display.AbstractDisplayManager.StartAR(), Juniper.Display.AbstractDisplayManager.StartXRDisplay(), Juniper.Display.AbstractDisplayManager.ToggleAR(), and Juniper.Display.AbstractDisplayManager.Update().
Property Documentation
DEFAULT_FOV
virtual float Juniper.Display.AbstractDisplayManager.DEFAULT_FOV get protected inherited
Gets the field of view value that should be targeted for the running application.
The default fov.
Definition at line 279 of file AbstractDisplayManager.cs.
         {
             get
             {
                 return MainCamera.fieldOfView;
             }
         }
MainCamera
Camera Juniper.Display.AbstractDisplayManager.MainCamera static get inherited
Definition at line 201 of file AbstractDisplayManager.cs.
         {
             get
             {
                 if (cam != null)
                 {
                     return cam;
                 }
                 else
                 {
                     return cam = ComponentExt.FindAny<Camera>(camera => camera.tag == "MainCamera");
                 }
             }
         }
Referenced by Juniper.Input.Pointers.Probe.AlignProbe(), Juniper.Widgets.FollowMainCamera.Awake(), Juniper.Widgets.Standoff.Awake(), Juniper.Widgets.Label.Awake(), Juniper.Animation.SpiralTransition.Awake(), Juniper.World.CompassRose.Awake(), Juniper.Audio.InteractionAudio.Awake(), Juniper.Widgets.AbstractValued.Awake(), Juniper.Display.AbstractDisplayManager.ChangeARMode(), Juniper.JuniperPlatform.Ensure(), Juniper.JuniperPlatform.Install(), Juniper.MasterSceneController.Install(), Juniper.Input.Pointers.Screen.AbstractScreenDevice< KeyCode, HapticsType, TouchPointConfiguration >.InternalUpdate(), Juniper.Animation.FadeTransition.OnEntered(), Juniper.Animation.FadeTransition.OnExiting(), Juniper.ImageTracking.TrackableFoundEventHandler.SafetyCheck(), Juniper.Input.Pointers.Probe.Start(), Juniper.Animation.SpiralTransition.Update(), Juniper.Widgets.AttentionDirector.Update(), and Juniper.Display.AbstractDisplayManager.Update().
VerticalFieldOfView
float Juniper.Display.AbstractDisplayManager.VerticalFieldOfView get inherited
The camera field of view along the large screen axis in portrait mode, the narrow axis in landscape mode.
The vertical field of view.
Definition at line 292 of file AbstractDisplayManager.cs.
         {
             get
             {
                 if (Screen.width < Screen.height)
                 {
                     var tan = Mathf.Tan(Units.Degrees.Radians(DEFAULT_FOV / 2));
                     var max = Mathf.Max(Screen.width, Screen.height);
                     var min = Mathf.Min(Screen.width, Screen.height);
                     float aspect;
                     if (Screen.height < Screen.width)
                     {
                         aspect = min / max;
                     }
                     else
                     {
                         aspect = max / min;
                     }
                     return 2 * Units.Radians.Degrees(Mathf.Atan(tan * aspect));
                 }
                 else
                 {
                     return DEFAULT_FOV;
                 }
             }
         }
Referenced by Juniper.Display.AbstractDisplayManager.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Display/AbstractPassthroughDisplayManager.cs