Juniper: Hjg.Pngcs.Chunks.PngChunkSingle Class Reference
Hjg.Pngcs.Chunks.PngChunkSingle Class Reference abstract
A Chunk type that does not allow duplicate in an image
Public Types
enum ChunkOrderingConstraint {
ChunkOrderingConstraint.NONE, ChunkOrderingConstraint.BEFORE_PLTE_AND_IDAT, ChunkOrderingConstraint.AFTER_PLTE_BEFORE_IDAT, ChunkOrderingConstraint.BEFORE_IDAT,
ChunkOrderingConstraint.NA
}
Restrictions for chunk ordering, for ancillary chunks
Public Member Functions
sealed override bool AllowsMultiple ()
This is implemented in PngChunkMultiple/PngChunSingle
override int GetHashCode ()
override bool Equals (object obj)
ChunkRaw CreateEmptyChunk (int len, bool alloc)
override string ToString ()
Basic info: Id, length, Type name
abstract ChunkRaw CreateRawChunk ()
Serialization. Creates a Raw chunk, ready for write, from this chunk content
abstract void ParseFromRaw (ChunkRaw c)
Deserialization. Given a Raw chunk, just rad, fills this chunk content
abstract void CloneDataFromRead (AbstractPngChunk other)
Override to make a copy (normally deep) from other chunk
abstract ChunkOrderingConstraint GetOrderingConstraint ()
Get ordering constrain
Static Public Member Functions
static void FactoryRegister (string chunkId, Type type)
Registers a Chunk ID in the factory, to instantiate a given type
static T CloneChunk< T > (T chunk, ImageInfo info)
Protected Member Functions
PngChunkSingle (string id, ImageInfo imgInfo)
Properties
string Id [get]
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
bool Crit [get]
Standard basic properties, implicit in the Id
bool Pub [get]
bool Safe [get]
ImageInfo ImgInfo [get]
Image basic info, mostly for some checks
bool Priority [get, set]
For writing. Queued chunks with high priority will be written as soon as possible
int ChunkGroup [get, set]
Chunk group where it was read or writen
int Length [get, set]
long Offset [get, set]
Detailed Description
A Chunk type that does not allow duplicate in an image
Definition at line 8 of file PngChunkSingle.cs.
Member Enumeration Documentation
ChunkOrderingConstraint
enum Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkOrderingConstraint strong inherited
Restrictions for chunk ordering, for ancillary chunks
Enumerator
NONE
No constraint, the chunk can go anywhere
BEFORE_PLTE_AND_IDAT
Before PLTE (palette) - and hence, also before IDAT
AFTER_PLTE_BEFORE_IDAT
After PLTE (palette), but before IDAT
BEFORE_IDAT
Before IDAT (before or after PLTE)
NA
Does not apply
Definition at line 55 of file AbstractPngChunk.cs.
         {
             /// <summary>
             /// No constraint, the chunk can go anywhere
             /// </summary>
             NONE,
             /// <summary>
             /// Before PLTE (palette) - and hence, also before IDAT
             /// </summary>
             BEFORE_PLTE_AND_IDAT,
             /// <summary>
             /// After PLTE (palette), but before IDAT
             /// </summary>
             AFTER_PLTE_BEFORE_IDAT,
             /// <summary>
             /// Before IDAT (before or after PLTE)
             /// </summary>
             BEFORE_IDAT,
             /// <summary>
             /// Does not apply
             /// </summary>
             NA
         }
Constructor & Destructor Documentation
PngChunkSingle()
Hjg.Pngcs.Chunks.PngChunkSingle.PngChunkSingle (string id, ImageInfo imgInfo) inline protected
Definition at line 10 of file PngChunkSingle.cs.
             : base(id, imgInfo)
         {
         }
Member Function Documentation
AllowsMultiple()
sealed override bool Hjg.Pngcs.Chunks.PngChunkSingle.AllowsMultiple () inline virtual
This is implemented in PngChunkMultiple/PngChunSingle
Returns
Allows more than one chunk of this type in a image
Implements Hjg.Pngcs.Chunks.AbstractPngChunk.
Definition at line 15 of file PngChunkSingle.cs.
         {
             return false;
         }
CloneChunk< T >()
static T Hjg.Pngcs.Chunks.AbstractPngChunk.CloneChunk< T > (T chunk, ImageInfo info) inline static inherited
Type Constraints
T : AbstractPngChunk
Definition at line 217 of file AbstractPngChunk.cs.
                                                                        : AbstractPngChunk
         {
             if (chunk is null)
             {
                 throw new ArgumentNullException(nameof(chunk));
             }
             var cn = FactoryFromId(chunk.Id, info);
             if (cn.GetType() != (object)chunk.GetType())
             {
                 throw new PngjException("bad class cloning chunk: " + cn.GetType() + " "
                         + chunk.GetType());
             }
             cn.CloneDataFromRead(chunk);
             return (T)cn;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryFromId().
CloneDataFromRead()
abstract void Hjg.Pngcs.Chunks.AbstractPngChunk.CloneDataFromRead (AbstractPngChunk other) pure virtual inherited
Override to make a copy (normally deep) from other chunk
Parameters
other
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkTEXT, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkIEND, and Hjg.Pngcs.Chunks.PngChunkSkipped.
CreateEmptyChunk()
ChunkRaw Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk (int len, bool alloc) inline inherited
Definition at line 209 of file AbstractPngChunk.cs.
         {
             var c = new ChunkRaw(len, ChunkHelper.ToBytes(Id), alloc);
             return c;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.Id, and Hjg.Pngcs.Chunks.ChunkHelper.ToBytes().
Referenced by Hjg.Pngcs.Chunks.PngChunkTEXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkZTXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkGAMA.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkITXT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkUNKNOWN.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkOFFS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSTER.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkCHRM.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTIME.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkICCP.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSRGB.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPHYS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkPLTE.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSPLT.CreateRawChunk(), and Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk().
CreateRawChunk()
abstract ChunkRaw Hjg.Pngcs.Chunks.AbstractPngChunk.CreateRawChunk () pure virtual inherited
Serialization. Creates a Raw chunk, ready for write, from this chunk content
Implemented in Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkIEND, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkTEXT, and Hjg.Pngcs.Chunks.PngChunkSkipped.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.Write().
Equals()
override bool Hjg.Pngcs.Chunks.PngChunkSingle.Equals (object obj) inline
Definition at line 26 of file PngChunkSingle.cs.
         {
             return obj is PngChunkSingle pngChunkSingle
                 && Id?.Equals(pngChunkSingle.Id, System.StringComparison.Ordinal) == true;
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.Id.
FactoryRegister()
static void Hjg.Pngcs.Chunks.AbstractPngChunk.FactoryRegister (string chunkId, Type type) inline static inherited
Registers a Chunk ID in the factory, to instantiate a given type
This can be called by client code to register additional chunk types
Parameters
chunkId
type should extend PngChunkSingle or PngChunkMultiple
Definition at line 140 of file AbstractPngChunk.cs.
         {
             factoryMap.Add(chunkId, type);
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.factoryMap.
GetHashCode()
override int Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode () inline
Definition at line 20 of file PngChunkSingle.cs.
         {
             const int prime = 31;
             return prime + EqualityComparer<string>.Default.GetHashCode(Id);
         }
References Hjg.Pngcs.Chunks.AbstractPngChunk.Id.
GetOrderingConstraint()
abstract ChunkOrderingConstraint Hjg.Pngcs.Chunks.AbstractPngChunk.GetOrderingConstraint () pure virtual inherited
Get ordering constrain
Returns
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkSkipped, Hjg.Pngcs.Chunks.AbstractPngChunkTextVar, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, and Hjg.Pngcs.Chunks.PngChunkIEND.
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoAfterPLTE(), Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforeIDAT(), and Hjg.Pngcs.Chunks.AbstractPngChunk.MustGoBeforePLTE().
ParseFromRaw()
abstract void Hjg.Pngcs.Chunks.AbstractPngChunk.ParseFromRaw (ChunkRaw c) pure virtual inherited
Deserialization. Given a Raw chunk, just rad, fills this chunk content
Implemented in Hjg.Pngcs.Chunks.PngChunkSPLT, Hjg.Pngcs.Chunks.PngChunkPHYS, Hjg.Pngcs.Chunks.PngChunkTRNS, Hjg.Pngcs.Chunks.PngChunkBKGD, Hjg.Pngcs.Chunks.PngChunkITXT, Hjg.Pngcs.Chunks.PngChunkIHDR, Hjg.Pngcs.Chunks.PngChunkPLTE, Hjg.Pngcs.Chunks.PngChunkCHRM, Hjg.Pngcs.Chunks.PngChunkHIST, Hjg.Pngcs.Chunks.PngChunkTIME, Hjg.Pngcs.Chunks.PngChunkZTXT, Hjg.Pngcs.Chunks.PngChunkICCP, Hjg.Pngcs.Chunks.PngChunkSRGB, Hjg.Pngcs.Chunks.PngChunkTEXT, Hjg.Pngcs.Chunks.PngChunkOFFS, Hjg.Pngcs.Chunks.PngChunkGAMA, Hjg.Pngcs.Chunks.PngChunkSTER, Hjg.Pngcs.Chunks.PngChunkSBIT, Hjg.Pngcs.Chunks.PngChunkUNKNOWN, Hjg.Pngcs.Chunks.PngChunkIDAT, Hjg.Pngcs.Chunks.PngChunkIEND, and Hjg.Pngcs.Chunks.PngChunkSkipped.
ToString()
override string Hjg.Pngcs.Chunks.AbstractPngChunk.ToString () inline inherited
Basic info: Id, length, Type name
Returns
Definition at line 250 of file AbstractPngChunk.cs.
         {
             return $"chunk id= {Id} (len={Length.ToString(CultureInfo.CurrentCulture)} off={Offset.ToString(CultureInfo.CurrentCulture)}) c={GetType().Name}";
         }
Property Documentation
ChunkGroup
int Hjg.Pngcs.Chunks.AbstractPngChunk.ChunkGroup get set inherited
Chunk group where it was read or writen
Definition at line 47 of file AbstractPngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
Crit
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Crit get inherited
Standard basic properties, implicit in the Id
Definition at line 30 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), and Hjg.Pngcs.PngReader.ReadChunk().
Id
string Hjg.Pngcs.Chunks.AbstractPngChunk.Id get inherited
4 letters. The Id almost determines the concrete type (except for PngUKNOWN)
Definition at line 25 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.AbstractPngChunk.CreateEmptyChunk(), Hjg.Pngcs.Chunks.PngChunkSingle.Equals(), Hjg.Pngcs.Chunks.ChunkHelper.Equivalent(), Hjg.Pngcs.Chunks.PngChunkSingle.GetHashCode(), Hjg.Pngcs.Chunks.ChunkPredicateId.Matches(), Hjg.Pngcs.Chunks.ChunkPredicateId2.Matches(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
ImgInfo
ImageInfo Hjg.Pngcs.Chunks.AbstractPngChunk.ImgInfo get protected inherited
Image basic info, mostly for some checks
Definition at line 37 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.PngChunkHIST.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkTRNS.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkSBIT.CreateRawChunk(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetGray(), Hjg.Pngcs.Chunks.PngChunkSBIT.GetLen(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.GetRGB(), Hjg.Pngcs.Chunks.PngChunkBKGD.GetRGB(), Hjg.Pngcs.Chunks.PngChunkSBIT.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkHIST.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkTRNS.ParseFromRaw(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetGray(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetIndexEntryAsTransparent(), Hjg.Pngcs.Chunks.PngChunkBKGD.SetPaletteIndex(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetPalletteAlpha(), Hjg.Pngcs.Chunks.PngChunkTRNS.SetRGB(), and Hjg.Pngcs.Chunks.PngChunkBKGD.SetRGB().
Length
int Hjg.Pngcs.Chunks.AbstractPngChunk.Length get set inherited
Definition at line 49 of file AbstractPngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.AbstractPngChunk.Factory(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), and Hjg.Pngcs.Chunks.PngChunkSkipped.PngChunkSkipped().
Offset
long Hjg.Pngcs.Chunks.AbstractPngChunk.Offset get set inherited
Definition at line 50 of file AbstractPngChunk.cs.
 { get; set; } // merely informational, for read chunks
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), Hjg.Pngcs.Chunks.PngChunkIDAT.PngChunkIDAT(), and Hjg.Pngcs.PngReader.ReadChunk().
Priority
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Priority get set inherited
For writing. Queued chunks with high priority will be written as soon as possible
Definition at line 42 of file AbstractPngChunk.cs.
 { get; set; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk(), and Hjg.Pngcs.Chunks.ChunksListForWrite.ShouldWrite().
Pub
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Pub get inherited
Definition at line 31 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk().
Safe
bool Hjg.Pngcs.Chunks.AbstractPngChunk.Safe get inherited
Definition at line 32 of file AbstractPngChunk.cs.
 { get; }
Referenced by Hjg.Pngcs.Chunks.AbstractPngChunk.AbstractPngChunk().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/Chunks/PngChunkSingle.cs