Juniper: Juniper.Units Class Reference
Juniper.Units Class Reference
TODO: validate this against https://www.nist.gov/sites/default/files/documents/pml/wmd/metric/SP1038.pdf
Classes
class Brightness
Conversions from Brightness
class Bytes
Conversions from bytes
class Celsius
Conversions from celsius
class Centimeters
Conversions from centimeters
class CubicCentimeters
Conversions from cubic centimeters
class CubicFeet
Conversions from cubic feet
class CubicInches
Conversions from cubic inches
class CubicKilometers
Conversions from cubic kilometers
class CubicMeters
Conversions from cubic meters
class CubicMiles
Conversions from cubic miles
class CubicMillimeters
Conversions from cubic millimeters
class DatumWGS_84
A model of the Earth.
class Days
Conversions from days
class Degrees
Conversions from degrees
class Exabytes
Conversions from exabytes, 10^18 bytes
class Exbibytes
Conversions from exbibytes, 2^60 bytes
class Farenheit
Conversions from farenheit
class Feet
Conversions from feet
class FeetPerSecond
Conversions from feet per second
class FeetPerSecondSquared
Conversions from feet per second squared
class Gibibytes
Conversions from gibibytes, 2^30 bytes
class Gigabytes
Conversions from gigabytes, 10^9 bytes
class Gradians
Conversions from gradians
class Grams
Conversions from grams
class Hectopascals
Conversions from hectopascals
class Hertz
Conversions from hertz
class Hours
Conversions from hours
class Inches
Conversions from inches
class Kelvin
Conversions from kelvin
class Kibibytes
Conversions from kibibytes, 2^10 bytes
class Kilobytes
Conversions from kilobytes, 10^3 bytes
class Kilograms
Conversions from kilograms
class Kilometers
Conversions from kilometers
class KilometersPerHour
Conversions from kilometers per hour
class Kilopascals
Conversions from kilopascals
class LatLng
Conversions from LatLngPoint s.
class Lumens
Conversions from Lumens
class Megabytes
Conversions from megabytes, 10^6 bytes
class Meters
Conversions from meters
class MetersPerSecond
Conversions from meters per second
class MetersPerSecondSquared
Conversions from meters per second squared
class Mibibytes
Conversions from mibibytes, 2^20 bytes.
class Miles
Conversions from miles
class MilesPerHour
Conversions from miles per hour
class Millibars
Conversions from millibars
class Millimeters
Conversions from millimeters
class MillimetersPerSecond
Conversions from millimeters per second
class Milliseconds
Conversions from milliseconds
class Minutes
Conversions from minutes
class Nits
Conversions from Nits
class Ounces
Conversions from ounces
class Pascals
Conversions from pascals
class Pebibytes
Conversions from pebibytes, 2^50 bytes
class Percent
Conversions from percent
class Petabytes
Conversions from petabytes, 10^15 bytes
class Pounds
Conversions from pounds
class PoundsPerSquareInch
Conversions from pounds per square inch
class Proportion
Conversions from proportions
class Radians
Conversions from radians
class Ratio
Conversions from ratios. These conversions are only available for direct conversion, as they require two parameters.
class Seconds
Conversions from seconds
class SquareCentimeters
Conversions from square centimeters
class SquareFeet
Conversions from square feet
class SquareInches
Conversions from square inches
class SquareKilometers
Conversions from square kilometers
class SquareMeters
Conversions from square meters
class SquareMiles
Conversions from square miles
class SquareMillimeters
Conversions from square millimeters
class Tebibytes
Conversions from tebibytes, 2^40 bytes
class Terabytes
Conversions from terabytes, 10^12 bytes
class Tons
Conversions from tons
class UTM
Conversions from UTMPoint s.
class Yobibytes
Conversions from yobibytes, 2^80 bytes
class Yotabytes
Conversions from yotabytes, 10^24 bytes
class Zebibytes
Conversions from zebibytes, 2^70 bytes
class Zettabytes
Conversions from zettabytes, 10^21 bytes
Public Types
enum Category {
Category.None, Category.Temperature, Category.Time, Category.Proportion,
Category.Angles, Category.Geo, Category.Length, Category.Area,
Category.Volume, Category.VeryShortLength, Category.VerySmallArea, Category.VerySmallVolume,
Category.ShortLength, Category.SmallArea, Category.SmallVolume, Category.LongLength,
Category.LargeArea, Category.LargeVolume, Category.Distance, Category.LandMass,
Category.HugeVolume, Category.Mass, Category.SmallMass, Category.LargeMass,
Category.Pressure, Category.AtmosphericPressure, Category.Speed, Category.BallisticSpeed,
Category.RoadSpeed, Category.Acceleration, Category.FileSize, Category.TinyFileSize,
Category.SmallFileSize, Category.RegularFileSize, Category.LargeFileSize, Category.HugeFileSize,
Category.GiganticFileSize, Category.Brightness
}
Different groupings of measurement systems.
Static Public Member Functions
static ? UnitOfMeasure GetSystemUnit (SystemOfMeasure system, Category category)
Retrieves the type of unit that is used in a given Category slot for a SystemOfMeasure.
static float Convert (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit)
Convert a value from one unit of measure to another.
static float Convert (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem=SystemOfMeasure.USCustomary)
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
static ? float Convert (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit)
Convert a value from one unit of measure to another.
static ? float Convert (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem=SystemOfMeasure.USCustomary)
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
static string Abbreviate (this UnitOfMeasure unit)
Retrieve the abbreviation for the given unit of measure.
static string Label (this float value, UnitOfMeasure unit, int? sigfigs=null)
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int? sigfigs=null)
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int? sigfigs=null)
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int? sigfigs=null)
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int? sigfigs=null)
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
static string Label (this float? value, UnitOfMeasure unit, int? sigfigs=null)
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Static Public Attributes
static Dictionary< UnitOfMeasure, string > Abbreviations
All the short-form symbols of each UnitOfMeasure.
Static Private Member Functions
static internal float Repeat (float value, float range)
Loops a circular value around an range. Unity has this function already, but we reimplement it here to make sure the Units subsystem does not depend on Unity.
static Category GetPrimaryCategory (UnitOfMeasure unit)
Retrieve the first category listing in TypeGroups for a given UnitOfMeasure.
static Units ()
Iterate over the UnitOfMeasure values and find all of the conversions that are defined in the Units namespace.
static UnitOfMeasure FindConversion (UnitOfMeasure fromUnit, SystemOfMeasure toSystem)
For a given UnitOfMeasure, find any Category in any SystemOfMeasure which has a matching Category in the given SystemOfMeasure, then retrieve the UnitOfMeasure that fulfills that category in that SystemOfMeasure.
Static Private Attributes
static readonly Dictionary< UnitOfMeasure, Category[]> TypeGroups
The TypeGroups put the different UnitOfMeasures into groupings by Category, to make conversions within categories possible. Every UnitOfMeasure should be included in a Category.
static readonly Dictionary< SystemOfMeasure, Dictionary< Category, UnitOfMeasure > > SystemUnits
SystemUnits are groupings of UnitOfMeasure s into SystemOfMeasure s by Category s. For example, this makes it possible to ask which units are used for short distance measurements in the Metric system. Not every UnitOfMeasure need be included in a SystemOfMeasure.
static readonly Dictionary< UnitOfMeasure, Dictionary< UnitOfMeasure, MethodInfo > > Conversions
A look-up to quickly find the conversion function for each unit of measure pairing without having to use reflection every time.
Detailed Description
TODO: validate this against https://www.nist.gov/sites/default/files/documents/pml/wmd/metric/SP1038.pdf
Definition at line 3 of file FeetPerSecondSquared.cs.
Member Enumeration Documentation
Category
enum Juniper.Units.Category strong
Different groupings of measurement systems.
Enumerator
None
Not set/unknown
Temperature
Molecular kinetic energy.
Time
... but not space.
Proportion
Unitless divisions of values.
Angles
Measures around a circle.
Geo
Measures of the planet and stars.
Length
Measures of displacement.
Area
Volume
VeryShortLength
Very small measures of displacement.
VerySmallArea
VerySmallVolume
ShortLength
Small measures of displacement.
SmallArea
SmallVolume
LongLength
Long measures of displacement.
LargeArea
LargeVolume
Distance
Measures of displacement.
LandMass
HugeVolume
Mass
Measures of a warping of space.
SmallMass
Measures of a small warping of space.
LargeMass
Measures of a large warping of space.
Pressure
Measures of force distributed across an area.
AtmosphericPressure
Measures of weather patterns.
Speed
Measures of change in displacement over time.
BallisticSpeed
Measures of projectiles.
RoadSpeed
Measures of vehicles.
Acceleration
Change in speed over time.
FileSize
File sizes are measured in subdivisions of bytes.
TinyFileSize
Plain bytes.
SmallFileSize
Kilo- or Kibibytes
RegularFileSize
Mega- or Mibibytes
LargeFileSize
Giga- or Gibibytes
HugeFileSize
Tera- or Tebibytes
GiganticFileSize
Peta- or Pebibytes
Brightness
A rather arbitrary set of conversions that are only used to maintain compatibility between AR subsystems and their light estimation processes. Does not necessarily reflect reality!
Definition at line 398 of file Units.cs.
         {
             /// <summary>
             /// Not set/unknown
             /// </summary>
             None,
             /// <summary>
             /// Molecular kinetic energy.
             /// </summary>
             Temperature,
             /// <summary>
             /// ... but not space.
             /// </summary>
             Time,
             /// <summary>
             /// Unitless divisions of values.
             /// </summary>
             Proportion,
             /// <summary>
             /// Measures around a circle.
             /// </summary>
             Angles,
             /// <summary>
             /// Measures of the planet and stars.
             /// </summary>
             Geo,
             /// <summary>
             /// Measures of displacement.
             /// </summary>
             Length,
             Area,
             Volume,
             /// <summary>
             /// Very small measures of displacement.
             /// </summary>
             VeryShortLength,
             VerySmallArea,
             VerySmallVolume,
             /// <summary>
             /// Small measures of displacement.
             /// </summary>
             ShortLength,
             SmallArea,
             SmallVolume,
             /// <summary>
             /// Long measures of displacement.
             /// </summary>
             LongLength,
             LargeArea,
             LargeVolume,
             /// <summary>
             /// Measures of displacement.
             /// </summary>
             Distance,
             LandMass,
             HugeVolume,
             /// <summary>
             /// Measures of a warping of space.
             /// </summary>
             Mass,
             /// <summary>
             /// Measures of a small warping of space.
             /// </summary>
             SmallMass,
             /// <summary>
             /// Measures of a large warping of space.
             /// </summary>
             LargeMass,
             /// <summary>
             /// Measures of force distributed across an area.
             /// </summary>
             Pressure,
             /// <summary>
             /// Measures of weather patterns.
             /// </summary>
             AtmosphericPressure,
             /// <summary>
             /// Measures of change in displacement over time.
             /// </summary>
             Speed,
             /// <summary>
             /// Measures of projectiles.
             /// </summary>
             BallisticSpeed,
             /// <summary>
             /// Measures of vehicles.
             /// </summary>
             RoadSpeed,
             /// <summary>
             /// Change in speed over time.
             /// </summary>
             Acceleration,
             /// <summary>
             /// File sizes are measured in subdivisions of bytes.
             /// </summary>
             FileSize,
             /// <summary>
             /// Plain bytes.
             /// </summary>
             TinyFileSize,
             /// <summary>
             /// Kilo- or Kibibytes
             /// </summary>
             SmallFileSize,
             /// <summary>
             /// Mega- or Mibibytes
             /// </summary>
             RegularFileSize,
             /// <summary>
             /// Giga- or Gibibytes
             /// </summary>
             LargeFileSize,
             /// <summary>
             /// Tera- or Tebibytes
             /// </summary>
             HugeFileSize,
             /// <summary>
             /// Peta- or Pebibytes
             /// </summary>
             GiganticFileSize,
             /// <summary>
             /// A rather arbitrary set of conversions that are only
             /// used to maintain compatibility between AR subsystems
             /// and their light estimation processes. Does not necessarily
             /// reflect reality!
             /// </summary>
             Brightness
         }
Constructor & Destructor Documentation
Units()
static Juniper.Units.Units () inline static private
Iterate over the UnitOfMeasure values and find all of the conversions that are defined in the Units namespace.
Definition at line 851 of file Units.cs.
         {
             var u = typeof(Units);
             var um = typeof(UnitOfMeasure);
             var f = typeof(float);
             Conversions =
                 (from fromType in u.GetNestedTypes(BindingFlags.Public)
                  where Enum.IsDefined(um, fromType.Name)
                  group (from toMethod in fromType.GetMethods()
                         where toMethod.ReturnType == f
                             && Enum.IsDefined(um, toMethod.Name)
                         let p = toMethod.GetParameters()
                         where p.Length == 1
                             && p[0].ParameterType == f
                         select toMethod)
                      .ToDictionary(
                          to => (UnitOfMeasure)Enum.Parse(um, to.Name))
                  by fromType.Name)
                  .ToDictionary(
                      from => (UnitOfMeasure)Enum.Parse(um, from.Key),
                      from => from.First());
         }
References Juniper.Units.Conversions.
Member Function Documentation
Abbreviate()
static string Juniper.Units.Abbreviate (this UnitOfMeasure unit) inline static
Retrieve the abbreviation for the given unit of measure.
Parameters
unit
Returns
Definition at line 980 of file Units.cs.
         {
             return Abbreviations.ContainsKey(unit) ? Abbreviations[unit] : string.Empty;
         }
References Juniper.Units.Abbreviations.
Convert() [1/4]
static float Juniper.Units.Convert (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit) inline static
Convert a value from one unit of measure to another.
Parameters
value
fromUnit
toUnit
Returns
Definition at line 920 of file Units.cs.
         {
             if (fromUnit == toUnit)
             {
                 return value;
             }
             else if (Conversions.TryGetValue(fromUnit, out var forFromUnit)
                 && Conversions[fromUnit].TryGetValue(toUnit, out var conversion))
             {
                 return (float)conversion.Invoke(null, new object[] { value });
             }
             else
             {
                 throw new InvalidCastException($"Cannot convert {value} in {fromUnit} to {toUnit}.");
             }
         }
References Juniper.Units.Conversions.
Convert() [2/4]
static float Juniper.Units.Convert (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem = SystemOfMeasure.USCustomary) inline static
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
Parameters
value
fromUnit
toSystem
Returns
Definition at line 945 of file Units.cs.
         {
             return value.Convert(fromUnit, FindConversion(fromUnit, toSystem));
         }
References Juniper.Units.FindConversion().
Convert() [3/4]
static ? float Juniper.Units.Convert (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit) inline static
Convert a value from one unit of measure to another.
Parameters
value
fromUnit
toUnit
Returns
Definition at line 957 of file Units.cs.
         {
             return value?.Convert(fromUnit, toUnit);
         }
Convert() [4/4]
static ? float Juniper.Units.Convert (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem = SystemOfMeasure.USCustomary) inline static
Convert a value from one unit of measure to the analogous unit of measure in a different system of measure.
Parameters
value
fromUnit
toSystem
Returns
Definition at line 970 of file Units.cs.
         {
             return value?.Convert(fromUnit, toSystem);
         }
FindConversion()
static UnitOfMeasure Juniper.Units.FindConversion (UnitOfMeasure fromUnit, SystemOfMeasure toSystem) inline static private
For a given UnitOfMeasure, find any Category in any SystemOfMeasure which has a matching Category in the given SystemOfMeasure, then retrieve the UnitOfMeasure that fulfills that category in that SystemOfMeasure.
Parameters
fromUnit
toSystem
Returns
Definition at line 882 of file Units.cs.
         {
             if (!Conversions.ContainsKey(fromUnit))
             {
                 throw new ArgumentException($"Unit type {fromUnit} not recognized for conversion");
             }
             else if (!TypeGroups.ContainsKey(fromUnit))
             {
                 throw new ArgumentException($"Unit type {fromUnit} has not had type groupings defined");
             }
             else if (!SystemUnits.ContainsKey(toSystem))
             {
                 throw new ArgumentException($"System type {toSystem} not specified");
             }
             else
             {
                 foreach (var g in TypeGroups[fromUnit])
                 {
                     foreach (var s in SystemUnits[toSystem])
                     {
                         if (g == s.Key)
{
                             return s.Value;
                         }
                     }
                 }
                 throw new ArgumentException($"Unit type {fromUnit} does not have a matching conversion in system {toSystem}");
             }
         }
References Juniper.Units.Conversions, Juniper.Units.SystemUnits, and Juniper.Units.TypeGroups.
Referenced by Juniper.Units.Convert(), and Juniper.Units.Label().
GetPrimaryCategory()
static Category Juniper.Units.GetPrimaryCategory (UnitOfMeasure unit) inline static private
Retrieve the first category listing in TypeGroups for a given UnitOfMeasure.
Parameters
unit The unit to look up
Returns
The gross category of the unit
Definition at line 665 of file Units.cs.
         {
             return TypeGroups[unit][0];
         }
References Juniper.Units.TypeGroups.
GetSystemUnit()
static ? UnitOfMeasure Juniper.Units.GetSystemUnit (SystemOfMeasure system, Category category) inline static
Retrieves the type of unit that is used in a given Category slot for a SystemOfMeasure.
Parameters
system The system to query
category The category to look up
Returns
null, if the category is not available in the system, or a UnitOfMeasure otherwise.
Definition at line 739 of file Units.cs.
         {
             if (SystemUnits.TryGetValue(system, out var sys)
                 && sys.TryGetValue(category, out var unit))
             {
                 return unit;
             }
             else
             {
                 return null;
             }
         }
References Juniper.Units.SystemUnits.
Label() [1/6]
static string Juniper.Units.Label (this float value, UnitOfMeasure unit, int? sigfigs = null) inline static
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
unit
sigfigs
Returns
Definition at line 993 of file Units.cs.
         {
             return float.IsInfinity(value) || float.IsNaN(value)
                 ? value.ToString()
                 : value.SigFig(sigfigs) + unit.Abbreviate();
         }
Label() [2/6]
static string Juniper.Units.Label (this float value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int? sigfigs = null) inline static
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toSystem
sigfigs
Returns
Definition at line 1009 of file Units.cs.
         {
             return value.Label(fromUnit, FindConversion(fromUnit, toSystem), sigfigs);
         }
References Juniper.Units.FindConversion().
Label() [3/6]
static string Juniper.Units.Label (this float value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int? sigfigs = null) inline static
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toUnit
sigfigs
Returns
Definition at line 1023 of file Units.cs.
         {
             return value
                 .Convert(fromUnit, toUnit)
                 .Label(toUnit, sigfigs);
         }
Label() [4/6]
static string Juniper.Units.Label (this float? value, UnitOfMeasure fromUnit, SystemOfMeasure toSystem, int? sigfigs = null) inline static
Convert a source value of a given unit of measure, converted to a given system of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toSystem
sigfigs
Returns
Definition at line 1039 of file Units.cs.
         {
             return value?.Label(fromUnit, toSystem, sigfigs) ?? "N/A";
         }
Label() [5/6]
static string Juniper.Units.Label (this float? value, UnitOfMeasure fromUnit, UnitOfMeasure toUnit, int? sigfigs = null) inline static
Convert a source value of a given unit of measure, converted directly to a different unit of measure, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
fromUnit
toUnit
sigfigs
Returns
Definition at line 1053 of file Units.cs.
         {
             return value?.Label(fromUnit, toUnit, sigfigs) ?? "N/A";
         }
Label() [6/6]
static string Juniper.Units.Label (this float? value, UnitOfMeasure unit, int? sigfigs = null) inline static
Convert a source value of a given unit of measure, with no unit conversion, with its abbreviation, to a certain number of significant digits, to a string.
Parameters
value
unit
sigfigs
Returns
Definition at line 1066 of file Units.cs.
         {
             return value?.Label(unit, sigfigs) ?? "N/A";
         }
Repeat()
static internal float Juniper.Units.Repeat (float value, float range) inline static private
Loops a circular value around an range. Unity has this function already, but we reimplement it here to make sure the Units subsystem does not depend on Unity.
Parameters
value
range
Returns
Definition at line 382 of file Units.cs.
         {
             while (value < 0)
             {
                 value += range;
             }
             while (value > range)
             {
                 value -= range;
             }
             return value;
         }
Referenced by Juniper.World.GIS.GeocentricEclipticSphericalPosition.FromJulianDay(), and Juniper.World.GIS.EquitorialSphericalPosition.ToHorizontal().
Member Data Documentation
Abbreviations
Dictionary<UnitOfMeasure, string> Juniper.Units.Abbreviations static
All the short-form symbols of each UnitOfMeasure.
Definition at line 755 of file Units.cs.
Referenced by Juniper.Units.Abbreviate().
Conversions
readonly Dictionary<UnitOfMeasure, Dictionary<UnitOfMeasure, MethodInfo> > Juniper.Units.Conversions static private
A look-up to quickly find the conversion function for each unit of measure pairing without having to use reflection every time.
Definition at line 845 of file Units.cs.
Referenced by Juniper.Units.Convert(), Juniper.Units.FindConversion(), and Juniper.Units.Units().
SystemUnits
readonly Dictionary<SystemOfMeasure, Dictionary<Category, UnitOfMeasure> > Juniper.Units.SystemUnits static private
SystemUnits are groupings of UnitOfMeasure s into SystemOfMeasure s by Category s. For example, this makes it possible to ask which units are used for short distance measurements in the Metric system. Not every UnitOfMeasure need be included in a SystemOfMeasure.
Definition at line 676 of file Units.cs.
Referenced by Juniper.Units.FindConversion(), and Juniper.Units.GetSystemUnit().
TypeGroups
readonly Dictionary<UnitOfMeasure, Category[]> Juniper.Units.TypeGroups static private
The TypeGroups put the different UnitOfMeasures into groupings by Category, to make conversions within categories possible. Every UnitOfMeasure should be included in a Category.
Definition at line 559 of file Units.cs.
Referenced by Juniper.Units.FindConversion(), and Juniper.Units.GetPrimaryCategory().
The documentation for this class was generated from the following files:
C:/Users/sean/Projects/Juniper/src/Juniper.Units/src/Acceleration/FeetPerSecondSquared.cs
C:/Users/sean/Projects/Juniper/src/Juniper.Units/src/Units.cs