Juniper: Juniper.Widgets.FileSelector Class Reference
Juniper.Widgets.FileSelector Class Reference
Public Types
enum SelectionMode { SelectionMode.File, SelectionMode.Directory }
Public Member Functions
void OK ()
void Cancel ()
void Show (string titleText, SelectionMode m, string filterPattern, Action< string > onFileSelected, Action onSelectionCanceled=null)
void Awake ()
void Update ()
void MaybeSetStartDirectory (DirectoryInfo top)
Public Attributes
SelectionMode mode
Font font
int fontSize = 20
string filter
string startDirectory
Properties
string SelectedPath [get, private set]
Private Member Functions
void CallAndExit (Action cb)
T Get< T > (string p)
void ReadDirectory (string directory)
bool FilePassesFilter (string filePath)
void ShowPath (string fileOrDirPath)
void AddEntry (SelectionMode type, string entry, string parent)
void Select (ListViewItem item)
Private Attributes
string lastFilter
Regex fileFilter
string lastStartDirectory
ListView container
Action< string > onSelected
Action onCancel
Text title
Text label
InputField path
Button ok
Button cancel
Detailed Description
Definition at line 11 of file FileSelector.cs.
Member Enumeration Documentation
SelectionMode
enum Juniper.Widgets.FileSelector.SelectionMode strong
Enumerator
File
Directory
Definition at line 23 of file FileSelector.cs.
         {
             File,
             Directory
         }
Member Function Documentation
AddEntry()
void Juniper.Widgets.FileSelector.AddEntry (SelectionMode type, string entry, string parent) inline private
Definition at line 196 of file FileSelector.cs.
         {
             string itemTitle = null;
             string itemKey = null;
             object data = null;
             if (type == SelectionMode.File)
             {
                 var file = new FileInfo(entry);
                 data = file;
                 itemTitle = file.Name;
                 itemKey = file.FullName;
             }
             else if (entry == "..")
             {
                 var dir = new DirectoryInfo(parent);
                 data = dir;
                 itemTitle = "../";
                 itemKey = dir.FullName;
             }
             else
             {
                 var dir = new DirectoryInfo(entry);
                 data = dir;
                 itemTitle = $" + {dir.Name}/";
                 itemKey = dir.FullName;
             }
             var item = container.AddItem(itemTitle, data, itemKey);
             item.AddListener(() =>
                 Select(item));
             item.interactable = type == SelectionMode.Directory || FilePassesFilter(entry);
         }
References Juniper.Widgets.ListView.AddItem(), Juniper.Widgets.ListViewItem.AddListener(), Juniper.Widgets.FileSelector.container, Juniper.Widgets.FileSelector.FilePassesFilter(), and Juniper.Widgets.FileSelector.Select().
Referenced by Juniper.Widgets.FileSelector.ReadDirectory().
Awake()
void Juniper.Widgets.FileSelector.Awake () inline
Definition at line 60 of file FileSelector.cs.
         {
             container = GetComponentInChildren<ListView>();
             title = Get<Text>("Title");
             label = Get<Text>("Controls/Label");
             path = Get<InputField>("Controls/Path");
             ok = Get<Button>("Controls/OK");
             cancel = Get<Button>("Controls/Cancel");
             ok.onClick.AddListener(OK);
             cancel.onClick.AddListener(Cancel);
         }
References Juniper.Widgets.FileSelector.Cancel(), Juniper.Widgets.FileSelector.cancel, Juniper.Widgets.FileSelector.container, Juniper.Widgets.FileSelector.label, Juniper.Widgets.FileSelector.OK(), Juniper.Widgets.FileSelector.ok, Juniper.Widgets.FileSelector.path, and Juniper.Widgets.FileSelector.title.
CallAndExit()
void Juniper.Widgets.FileSelector.CallAndExit (Action cb) inline private
Definition at line 109 of file FileSelector.cs.
         {
             gameObject.SetActive(false);
             onSelected = null;
             onCancel = null;
             cb?.Invoke();
         }
References Juniper.Widgets.FileSelector.onCancel, and Juniper.Widgets.FileSelector.onSelected.
Referenced by Juniper.Widgets.FileSelector.OK().
Cancel()
void Juniper.Widgets.FileSelector.Cancel ()
Referenced by Juniper.Widgets.FileSelector.Awake().
FilePassesFilter()
bool Juniper.Widgets.FileSelector.FilePassesFilter (string filePath) private
Referenced by Juniper.Widgets.FileSelector.AddEntry().
Get< T >()
T Juniper.Widgets.FileSelector.Get< T > (string p) inline private
Type Constraints
T : Behaviour
Definition at line 117 of file FileSelector.cs.
                                            : Behaviour
         {
             var t = transform.Find(p);
             if (t == null)
             {
                 return default(T);
             }
             else
             {
                 return t.GetComponent<T>();
             }
         }
MaybeSetStartDirectory()
void Juniper.Widgets.FileSelector.MaybeSetStartDirectory (DirectoryInfo top) inline
Definition at line 83 of file FileSelector.cs.
         {
             while (top?.Exists == false)
             {
                 top = top.Parent;
             }
             if (top == null)
             {
                 top = new DirectoryInfo(Directory.GetCurrentDirectory());
             }
             startDirectory = top.FullName;
         }
References Juniper.Widgets.FileSelector.startDirectory.
OK()
void Juniper.Widgets.FileSelector.OK () inline
Definition at line 31 of file FileSelector.cs.
         {
             if (Directory.Exists(SelectedPath))
             {
                 startDirectory = SelectedPath;
             }
             else if (File.Exists(SelectedPath))
             {
                 startDirectory = Path.GetDirectoryName(SelectedPath);
             }
             var select = onSelected;
             CallAndExit(() =>
                 select(SelectedPath));
         }
References Juniper.Widgets.FileSelector.CallAndExit(), Juniper.Widgets.FileSelector.onSelected, Juniper.Widgets.FileSelector.SelectedPath, and Juniper.Widgets.FileSelector.startDirectory.
Referenced by Juniper.Widgets.FileSelector.Awake().
ReadDirectory()
void Juniper.Widgets.FileSelector.ReadDirectory (string directory) inline private
Definition at line 130 of file FileSelector.cs.
         {
             if (Directory.Exists(directory))
             {
                 container.Clear();
                 var dirs = Directory.GetDirectories(directory).ToList();
                 string parent = null;
                 var parentDir = Directory.GetParent(directory);
                 if (parentDir != null)
                 {
                     parent = parentDir.FullName;
                     dirs.Insert(0, "..");
                 }
                 if (mode == SelectionMode.File)
                 {
                     ok.interactable = false;
                 }
                 var dir = new DirectoryInfo(directory);
                 ShowPath(dir.FullName);
                 if (filter != lastFilter)
                 {
                     fileFilter = new Regex(filter.Replace(".", "\\.").Replace("*", ".+"));
                     lastFilter = filter + "$";
                 }
                 for (var i = 0; i < dirs.Count; ++i)
                 {
                     AddEntry(SelectionMode.Directory, dirs[i], parent);
                 }
                 if (mode == SelectionMode.File)
                 {
                     var files = Directory.GetFiles(directory).ToList();
                     var j = 0;
                     for (var i = 0; i < files.Count; ++i)
                     {
                         AddEntry(SelectionMode.File, files[i], directory);
                         ++j;
                     }
                 }
             }
         }
References Juniper.Widgets.FileSelector.AddEntry(), Juniper.Widgets.ListView.Clear(), Juniper.Widgets.FileSelector.container, Juniper.Widgets.FileSelector.fileFilter, Juniper.Widgets.FileSelector.filter, Juniper.Widgets.FileSelector.lastFilter, Juniper.Widgets.FileSelector.mode, Juniper.Widgets.FileSelector.ok, and Juniper.Widgets.FileSelector.ShowPath().
Referenced by Juniper.Widgets.FileSelector.Select(), and Juniper.Widgets.FileSelector.Update().
Select()
void Juniper.Widgets.FileSelector.Select (ListViewItem item) inline private
Definition at line 229 of file FileSelector.cs.
         {
             var obj = item.DataItem;
             if (obj is FileInfo)
             {
                 var file = (FileInfo)obj;
                 ok.interactable = true;
                 ShowPath(file.FullName);
             }
             else if (obj is DirectoryInfo)
             {
                 var dir = (DirectoryInfo)obj;
                 ReadDirectory(dir.FullName);
             }
         }
References Juniper.Widgets.ListViewItem.DataItem, Juniper.Widgets.FileSelector.ok, Juniper.Widgets.FileSelector.ReadDirectory(), and Juniper.Widgets.FileSelector.ShowPath().
Referenced by Juniper.Widgets.FileSelector.AddEntry().
Show()
void Juniper.Widgets.FileSelector.Show (string titleText, SelectionMode m, string filterPattern, Action< string > onFileSelected, Action onSelectionCanceled = null) inline
Definition at line 50 of file FileSelector.cs.
         {
             gameObject.SetActive(true);
             title.text = titleText;
             mode = m;
             onSelected = onFileSelected;
             onCancel = onSelectionCanceled;
             filter = filterPattern;
         }
References Juniper.Widgets.FileSelector.filter, Juniper.Widgets.FileSelector.mode, Juniper.Widgets.FileSelector.onCancel, Juniper.Widgets.FileSelector.onSelected, and Juniper.Widgets.FileSelector.title.
ShowPath()
void Juniper.Widgets.FileSelector.ShowPath (string fileOrDirPath) inline private
Definition at line 181 of file FileSelector.cs.
         {
             SelectedPath = fileOrDirPath;
             if (string.IsNullOrEmpty(filter))
             {
                 label.text = $"{mode}:";
             }
             else
             {
                 label.text = $"{mode} ({filter}):";
             }
             path.text = SelectedPath;
         }
References Juniper.Widgets.FileSelector.filter, Juniper.Widgets.FileSelector.label, Juniper.Widgets.FileSelector.path, and Juniper.Widgets.FileSelector.SelectedPath.
Referenced by Juniper.Widgets.FileSelector.ReadDirectory(), and Juniper.Widgets.FileSelector.Select().
Update()
void Juniper.Widgets.FileSelector.Update () inline
Definition at line 74 of file FileSelector.cs.
         {
             if (startDirectory != lastStartDirectory)
             {
                 ReadDirectory(startDirectory);
                 lastStartDirectory = startDirectory;
             }
         }
References Juniper.Widgets.FileSelector.lastStartDirectory, Juniper.Widgets.FileSelector.ReadDirectory(), and Juniper.Widgets.FileSelector.startDirectory.
Member Data Documentation
cancel
Button Juniper.Widgets.FileSelector.cancel private
Definition at line 107 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.Awake().
container
ListView Juniper.Widgets.FileSelector.container private
Definition at line 101 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.AddEntry(), Juniper.Widgets.FileSelector.Awake(), and Juniper.Widgets.FileSelector.ReadDirectory().
fileFilter
Regex Juniper.Widgets.FileSelector.fileFilter private
Definition at line 99 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.ReadDirectory().
filter
string Juniper.Widgets.FileSelector.filter
Definition at line 19 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.ReadDirectory(), Juniper.Widgets.FileSelector.Show(), and Juniper.Widgets.FileSelector.ShowPath().
font
Font Juniper.Widgets.FileSelector.font
Definition at line 15 of file FileSelector.cs.
fontSize
int Juniper.Widgets.FileSelector.fontSize = 20
Definition at line 17 of file FileSelector.cs.
label
Text Juniper.Widgets.FileSelector.label private
Definition at line 105 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.Awake(), and Juniper.Widgets.FileSelector.ShowPath().
lastFilter
string Juniper.Widgets.FileSelector.lastFilter private
Definition at line 98 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.ReadDirectory().
lastStartDirectory
string Juniper.Widgets.FileSelector.lastStartDirectory private
Definition at line 100 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.Update().
mode
SelectionMode Juniper.Widgets.FileSelector.mode
Definition at line 13 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.ReadDirectory(), and Juniper.Widgets.FileSelector.Show().
ok
Button Juniper.Widgets.FileSelector.ok private
Definition at line 107 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.Awake(), Juniper.Widgets.FileSelector.ReadDirectory(), and Juniper.Widgets.FileSelector.Select().
onCancel
Action Juniper.Widgets.FileSelector.onCancel private
Definition at line 103 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.CallAndExit(), and Juniper.Widgets.FileSelector.Show().
onSelected
Action<string> Juniper.Widgets.FileSelector.onSelected private
Definition at line 102 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.CallAndExit(), Juniper.Widgets.FileSelector.OK(), and Juniper.Widgets.FileSelector.Show().
path
InputField Juniper.Widgets.FileSelector.path private
Definition at line 106 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.Awake(), and Juniper.Widgets.FileSelector.ShowPath().
startDirectory
string Juniper.Widgets.FileSelector.startDirectory
Definition at line 21 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.MaybeSetStartDirectory(), Juniper.Widgets.FileSelector.OK(), and Juniper.Widgets.FileSelector.Update().
title
Text Juniper.Widgets.FileSelector.title private
Definition at line 104 of file FileSelector.cs.
Referenced by Juniper.Widgets.FileSelector.Awake(), and Juniper.Widgets.FileSelector.Show().
Property Documentation
SelectedPath
string Juniper.Widgets.FileSelector.SelectedPath get private set
Definition at line 29 of file FileSelector.cs.
 { get; private set; }
Referenced by Juniper.Widgets.FileSelector.OK(), and Juniper.Widgets.FileSelector.ShowPath().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Unity/Widgets/FileSelector.cs