Juniper: Juniper.Imaging.UnityTexture2DCodec Class Reference
Juniper.Imaging.UnityTexture2DCodec Class Reference
Public Member Functions
UnityTexture2DCodec (MediaType.Image format)
UnityTexture2DCodec (Texture2D.EXRFlags exrFlags)
UnityTexture2DCodec (int jpegEncodingQuality=80)
byte [] Serialize (Texture2D value)
long Serialize (Stream stream, Texture2D value)
Texture2D Deserialize (Stream stream)
Texture2D Deserialize (byte[] buffer)
Properties
MediaType.Image ContentType [get, private set]
Private Member Functions
ImageInfo GetImageInfo (byte[] data)
Texture2D MakeTexture (ImageInfo info, byte[] buffer)
Private Attributes
readonly Texture2D.EXRFlags exrFlags
readonly int jpegEncodingQuality
Detailed Description
Definition at line 8 of file UnityTexture2DCodec.cs.
Constructor & Destructor Documentation
UnityTexture2DCodec() [1/3]
Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec (MediaType.Image format) inline
Definition at line 13 of file UnityTexture2DCodec.cs.
         {
             if (format != MediaType.Image.EXR
                 && format != MediaType.Image.Jpeg
                 && format != MediaType.Image.Png
                 && format != MediaType.Image.X_Tga
                 && format != MediaType.Image.Raw)
             {
                 throw new NotSupportedException($"Unity doesn't know how to encode {format.Value} image data.");
             }
             ContentType = format;
             exrFlags = Texture2D.EXRFlags.None;
             jpegEncodingQuality = 80;
         }
References Juniper.Imaging.UnityTexture2DCodec.ContentType, Juniper.MediaType.Image.EXR, Juniper.Imaging.UnityTexture2DCodec.exrFlags, Juniper.MediaType.Image.Jpeg, Juniper.Imaging.UnityTexture2DCodec.jpegEncodingQuality, Juniper.MediaType.Image.Png, Juniper.MediaType.Image.Raw, and Juniper.MediaType.Image.X_Tga.
UnityTexture2DCodec() [2/3]
Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec (Texture2D.EXRFlags exrFlags) inline
Definition at line 30 of file UnityTexture2DCodec.cs.
             : this(MediaType.Image.EXR)
         {
             this.exrFlags = exrFlags;
         }
References Juniper.Imaging.UnityTexture2DCodec.exrFlags.
UnityTexture2DCodec() [3/3]
Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec (int jpegEncodingQuality = 80) inline
Definition at line 36 of file UnityTexture2DCodec.cs.
             : this(MediaType.Image.Jpeg)
         {
             this.jpegEncodingQuality = jpegEncodingQuality;
         }
References Juniper.Imaging.UnityTexture2DCodec.jpegEncodingQuality.
Member Function Documentation
Deserialize() [1/2]
Texture2D Juniper.Imaging.UnityTexture2DCodec.Deserialize (Stream stream) inline
Definition at line 117 of file UnityTexture2DCodec.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             var mem = new MemoryStream();
             stream.CopyTo(mem);
             stream.Flush();
             var buffer = mem.ToArray();
             return Deserialize(buffer);
         }
Deserialize() [2/2]
Texture2D Juniper.Imaging.UnityTexture2DCodec.Deserialize (byte [] buffer) inline
Definition at line 131 of file UnityTexture2DCodec.cs.
         {
             if (buffer is null)
             {
                 throw new ArgumentNullException(nameof(buffer));
             }
             var info = GetImageInfo(buffer);
             return JuniperSystem.OnMainThread(() =>
                 MakeTexture(info, buffer));
         }
References Juniper.Imaging.UnityTexture2DCodec.GetImageInfo(), Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), and Juniper.JuniperSystem.OnMainThread().
GetImageInfo()
ImageInfo Juniper.Imaging.UnityTexture2DCodec.GetImageInfo (byte [] data) inline private
Definition at line 48 of file UnityTexture2DCodec.cs.
         {
             if (ContentType == MediaType.Image.Jpeg)
             {
                 return ImageInfo.ReadJPEG(data);
             }
             else if (ContentType == MediaType.Image.Png)
             {
                 return ImageInfo.ReadPNG(data);
             }
             else
             {
                 throw new NotSupportedException($"Don't know how to read image data for type {ContentType}");
             }
         }
References Juniper.Imaging.UnityTexture2DCodec.ContentType, Juniper.MediaType.Image.Jpeg, Juniper.MediaType.Image.Png, Juniper.Imaging.ImageInfo.ReadJPEG(), and Juniper.Imaging.ImageInfo.ReadPNG().
Referenced by Juniper.Imaging.UnityTexture2DCodec.Deserialize().
MakeTexture()
Texture2D Juniper.Imaging.UnityTexture2DCodec.MakeTexture (ImageInfo info, byte [] buffer) inline private
Definition at line 143 of file UnityTexture2DCodec.cs.
         {
             var texture = new Texture2D(
                 info.Dimensions.Width,
                 info.Dimensions.Height,
                 info.Components == 3
                     ? TextureFormat.RGB24
                     : TextureFormat.RGBA32,
                 false);
             if (ContentType == MediaType.Image.EXR
                 || ContentType == MediaType.Image.Jpeg
                 || ContentType == MediaType.Image.Png
                 || ContentType == MediaType.Image.X_Tga)
             {
                 texture.LoadImage(buffer);
             }
             else if (ContentType == MediaType.Image.Raw)
             {
                 texture.LoadRawTextureData(buffer);
             }
             texture.Apply();
             return texture;
         }
References Juniper.Imaging.ImageInfo.Components, Juniper.Imaging.UnityTexture2DCodec.ContentType, Juniper.Imaging.ImageInfo.Dimensions, Juniper.MediaType.Image.EXR, Juniper.Imaging.Size.Height, Juniper.MediaType.Image.Jpeg, Juniper.MediaType.Image.Png, Juniper.MediaType.Image.Raw, Juniper.Imaging.Size.Width, and Juniper.MediaType.Image.X_Tga.
Referenced by Juniper.Imaging.UnityTexture2DCodec.Deserialize().
Serialize() [1/2]
byte [] Juniper.Imaging.UnityTexture2DCodec.Serialize (Texture2D value) inline
Definition at line 64 of file UnityTexture2DCodec.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             byte[] buffer;
             if (ContentType == MediaType.Image.EXR)
             {
                 buffer = value.EncodeToEXR(exrFlags);
             }
             else if (ContentType == MediaType.Image.Jpeg)
             {
                 buffer = value.EncodeToJPG(jpegEncodingQuality);
             }
             else if (ContentType == MediaType.Image.Png)
             {
                 buffer = value.EncodeToPNG();
             }
             else if (ContentType == MediaType.Image.X_Tga)
             {
                 buffer = value.EncodeToTGA();
             }
             else if (ContentType == MediaType.Image.Raw)
             {
                 buffer = value.GetRawTextureData();
             }
             else
             {
                 throw new NotSupportedException($"Unity doesn't know how to encode {ContentType.Value} image data.");
             }
             return buffer;
         }
References Juniper.Imaging.UnityTexture2DCodec.ContentType, Juniper.MediaType.Image.EXR, Juniper.Imaging.UnityTexture2DCodec.exrFlags, Juniper.MediaType.Image.Jpeg, Juniper.Imaging.UnityTexture2DCodec.jpegEncodingQuality, Juniper.MediaType.Image.Png, Juniper.MediaType.Image.Raw, and Juniper.MediaType.Image.X_Tga.
Referenced by Juniper.Imaging.UnityTexture2DCodec.Serialize().
Serialize() [2/2]
long Juniper.Imaging.UnityTexture2DCodec.Serialize (Stream stream, Texture2D value) inline
Definition at line 100 of file UnityTexture2DCodec.cs.
         {
             if (stream is null)
             {
                 throw new ArgumentNullException(nameof(stream));
             }
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             var buffer = Serialize(value);
             stream.Write(buffer, 0, buffer.Length);
             return buffer.Length;
         }
References Juniper.Imaging.UnityTexture2DCodec.Serialize().
Member Data Documentation
exrFlags
readonly Texture2D.EXRFlags Juniper.Imaging.UnityTexture2DCodec.exrFlags private
Definition at line 10 of file UnityTexture2DCodec.cs.
Referenced by Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
jpegEncodingQuality
readonly int Juniper.Imaging.UnityTexture2DCodec.jpegEncodingQuality private
Definition at line 11 of file UnityTexture2DCodec.cs.
Referenced by Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
Property Documentation
ContentType
MediaType.Image Juniper.Imaging.UnityTexture2DCodec.ContentType get private set
Definition at line 43 of file UnityTexture2DCodec.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Imaging.UnityTexture2DCodec.GetImageInfo(), Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper/Assets/Juniper/Scripts/Imaging/UnityTexture2DCodec.cs