Juniper: Juniper.Unity.Input.Pointers.Motion.HandTracker Class Reference
Juniper.Unity.Input.Pointers.Motion.HandTracker Class Reference
Public Member Functions
override void Reinstall ()
Static Public Member Functions
static HandTracker [] MakeHandTrackers (Func< string, HandTracker > MakePointer)
Static Private Member Functions
static HandTracker MakeHandTracker (Func< string, HandTracker > MakePointer, Hands hand)
Create a new hand pointer object for an interaction source that hasn't yet been seen.
Detailed Description
Definition at line 9 of file HandTracker.cs.
Member Function Documentation
MakeHandTracker()
static HandTracker Juniper.Unity.Input.Pointers.Motion.HandTracker.MakeHandTracker (Func< string, HandTracker > MakePointer, Hands hand) inline static private
Create a new hand pointer object for an interaction source that hasn't yet been seen.
Definition at line 37 of file HandTracker.cs.
         {
             var pointer = MakePointer(PointerConfig.MakePointerName(hand));
             pointer.Hand = hand;
             return pointer;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.HandTracker.MakeHandTrackers().
MakeHandTrackers()
static HandTracker [] Juniper.Unity.Input.Pointers.Motion.HandTracker.MakeHandTrackers (Func< string, HandTracker > MakePointer) inline static
Definition at line 26 of file HandTracker.cs.
         {
             return new[] {
                 MakeHandTracker(MakePointer, Hands.Left),
                 MakeHandTracker(MakePointer, Hands.Right)
             };
         }
References Juniper.Unity.Input.Pointers.Motion.HandTracker.MakeHandTracker().
Referenced by Juniper.Unity.StageExtensions.Install().
Reinstall()
override void Juniper.Unity.Input.Pointers.Motion.HandTracker.Reinstall () inline
Definition at line 21 of file HandTracker.cs.
         {
             base.Reinstall();
         }
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Pointers/Motion/HandTracker.cs