Juniper: MenuSceneController Class Reference
MenuSceneController Class Reference
Public Member Functions
void LoadScene (int index)
void Back ()
void Update ()
Static Public Member Functions
static void Quit ()
Properties
bool InMainMenu [get]
Private Member Functions
void Start ()
Private Attributes
bool NoNativeBackButton
Detailed Description
Definition at line 7 of file MenuSceneController.cs.
Member Function Documentation
Back()
void MenuSceneController.Back () inline
Definition at line 65 of file MenuSceneController.cs.
     {
         if (InMainMenu)
         {
             Quit();
         }
         else
         {
             LoadScene(0);
         }
     }
References InMainMenu, LoadScene(), and Quit().
Referenced by Update().
LoadScene()
void MenuSceneController.LoadScene (int index) inline
Definition at line 55 of file MenuSceneController.cs.
     {
         print(string.Format("Loading scene {0}", index));
         var currentIndex = SceneManager.GetActiveScene().buildIndex;
         if (index != currentIndex)
         {
             SceneManager.LoadScene(index, LoadSceneMode.Single);
         }
     }
Referenced by Back(), and Start().
Quit()
static void MenuSceneController.Quit () static
Referenced by Back().
Start()
void MenuSceneController.Start () inline private
Definition at line 9 of file MenuSceneController.cs.
     {
         var backButton = transform.GetChild(0).gameObject;
         backButton.SetActive(NoNativeBackButton);
         var bounds = (RectTransform)transform.GetChild(1);
         var prefab = bounds.gameObject;
         if (InMainMenu)
         {
             for (var i = 1; i < SceneManager.sceneCountInBuildSettings; ++i)
             {
                 var child = Instantiate(prefab);
                 var trans = (RectTransform)child.transform;
                 var text = child.GetComponentInChildren<Text>();
                 var button = child.GetComponent<Button>();
                 var n = i;
                 text.text = string.Format("Scene {0}", i);
                 trans.SetParent(bounds.parent);
                 trans.anchoredPosition = Vector3.down * (i - 1) * 90;
                 trans.anchorMin = Vector2.up;
                 trans.anchorMax = Vector2.one;
                 trans.sizeDelta = 80 * Vector2.up;
                 button.onClick.AddListener(() =>
                     LoadScene(n));
             }
         }
         Destroy(prefab);
     }
References InMainMenu, LoadScene(), and NoNativeBackButton.
Update()
void MenuSceneController.Update () inline
Definition at line 85 of file MenuSceneController.cs.
     {
         if (GetKey(KeyCode.Escape))
         {
             Back();
         }
     }
References Back().
Member Data Documentation
NoNativeBackButton
bool MenuSceneController.NoNativeBackButton private
Initial value:
=>
        Application.platform == RuntimePlatform.IPhonePlayer
                || Application.platform == RuntimePlatform.WindowsEditor
                || Application.platform == RuntimePlatform.LinuxEditor
                || Application.platform == RuntimePlatform.OSXEditor
Definition at line 40 of file MenuSceneController.cs.
Referenced by Start().
Property Documentation
InMainMenu
bool MenuSceneController.InMainMenu get private
Definition at line 47 of file MenuSceneController.cs.
     {
         get
         {
             var scene = SceneManager.GetActiveScene();
             return scene.buildIndex == 0;
         }
     }
Referenced by Back(), and Start().
The documentation for this class was generated from the following file:
Assets/Juniper/Examples/ARKitTest/Scenes/Menu/MenuSceneController.cs