Juniper: Juniper.World.GIS.Google.Geocoding.GeometryViewport Class Reference
Juniper.World.GIS.Google.Geocoding.GeometryViewport Class Reference
Public Member Functions
GeometryViewport (LatLngPoint southwest, LatLngPoint northeast)
void GetObjectData (SerializationInfo info, StreamingContext context)
Protected Member Functions
GeometryViewport (SerializationInfo info, StreamingContext context)
Properties
LatLngPoint SouthWest [get]
LatLngPoint NorthEast [get]
Static Private Attributes
static readonly string SOUTHWEST_FIELD = nameof(SouthWest).ToLowerInvariant()
static readonly string NORTHEAST_FIELD = nameof(NorthEast).ToLowerInvariant()
Detailed Description
Definition at line 7 of file GeometryViewport.cs.
Constructor & Destructor Documentation
GeometryViewport() [1/2]
Juniper.World.GIS.Google.Geocoding.GeometryViewport.GeometryViewport (LatLngPoint southwest, LatLngPoint northeast) inline
Definition at line 15 of file GeometryViewport.cs.
         {
             SouthWest = southwest;
             NorthEast = northeast;
         }
References Juniper.World.GIS.Google.Geocoding.GeometryViewport.NorthEast, and Juniper.World.GIS.Google.Geocoding.GeometryViewport.SouthWest.
GeometryViewport() [2/2]
Juniper.World.GIS.Google.Geocoding.GeometryViewport.GeometryViewport (SerializationInfo info, StreamingContext context) inline protected
Definition at line 22 of file GeometryViewport.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             SouthWest = info.GetValue<LatLngPoint>(SOUTHWEST_FIELD);
             NorthEast = info.GetValue<LatLngPoint>(NORTHEAST_FIELD);
         }
References Juniper.World.GIS.Google.Geocoding.GeometryViewport.NorthEast, Juniper.World.GIS.Google.Geocoding.GeometryViewport.NORTHEAST_FIELD, Juniper.World.GIS.Google.Geocoding.GeometryViewport.SouthWest, and Juniper.World.GIS.Google.Geocoding.GeometryViewport.SOUTHWEST_FIELD.
Member Function Documentation
GetObjectData()
void Juniper.World.GIS.Google.Geocoding.GeometryViewport.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 33 of file GeometryViewport.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(SOUTHWEST_FIELD, new
             {
                 lat = SouthWest.Latitude,
                 lng = SouthWest.Longitude
             });
             info.AddValue(NORTHEAST_FIELD, new
             {
                 lat = NorthEast.Latitude,
                 lng = NorthEast.Longitude
             });
         }
References Juniper.World.GIS.LatLngPoint.Latitude, Juniper.World.GIS.LatLngPoint.Longitude, Juniper.World.GIS.Google.Geocoding.GeometryViewport.NorthEast, Juniper.World.GIS.Google.Geocoding.GeometryViewport.NORTHEAST_FIELD, Juniper.World.GIS.Google.Geocoding.GeometryViewport.SouthWest, and Juniper.World.GIS.Google.Geocoding.GeometryViewport.SOUTHWEST_FIELD.
Member Data Documentation
NORTHEAST_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeometryViewport.NORTHEAST_FIELD = nameof(NorthEast).ToLowerInvariant() static private
Definition at line 10 of file GeometryViewport.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryViewport.GeometryViewport(), and Juniper.World.GIS.Google.Geocoding.GeometryViewport.GetObjectData().
SOUTHWEST_FIELD
readonly string Juniper.World.GIS.Google.Geocoding.GeometryViewport.SOUTHWEST_FIELD = nameof(SouthWest).ToLowerInvariant() static private
Definition at line 9 of file GeometryViewport.cs.
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryViewport.GeometryViewport(), and Juniper.World.GIS.Google.Geocoding.GeometryViewport.GetObjectData().
Property Documentation
NorthEast
LatLngPoint Juniper.World.GIS.Google.Geocoding.GeometryViewport.NorthEast get
Definition at line 13 of file GeometryViewport.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryViewport.GeometryViewport(), and Juniper.World.GIS.Google.Geocoding.GeometryViewport.GetObjectData().
SouthWest
LatLngPoint Juniper.World.GIS.Google.Geocoding.GeometryViewport.SouthWest get
Definition at line 12 of file GeometryViewport.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.Geocoding.GeometryViewport.GeometryViewport(), and Juniper.World.GIS.Google.Geocoding.GeometryViewport.GetObjectData().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/Geocoding/GeometryViewport.cs