Juniper: UnityEditor.PluginImporterExt.iOS.ARKit Class Reference
UnityEditor.PluginImporterExt.iOS.ARKit Class Reference
Static Public Member Functions
static void Enable ()
static void Disable ()
Static Private Member Functions
static void SetCompileFlags (string flags)
Static Private Attributes
static readonly string PATH = PathExt.FixPath("Assets/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm")
Detailed Description
Definition at line 18 of file PluginImporterExt.cs.
Member Function Documentation
Disable()
static void UnityEditor.PluginImporterExt.iOS.ARKit.Disable () inline static
Definition at line 32 of file PluginImporterExt.cs.
                 {
                     SetCompileFlags("");
                 }
References UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags().
Enable()
static void UnityEditor.PluginImporterExt.iOS.ARKit.Enable () inline static
Definition at line 27 of file PluginImporterExt.cs.
                 {
                     SetCompileFlags("-DARKIT");
                 }
References UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags().
SetCompileFlags()
static void UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags (string flags) inline static private
Definition at line 22 of file PluginImporterExt.cs.
                 {
                     SetPlatformData(PATH, BuildTarget.iOS, "CompileFlags", flags);
                 }
References UnityEditor.PluginImporterExt.iOS.ARKit.PATH, and UnityEditor.PluginImporterExt.SetPlatformData().
Referenced by UnityEditor.PluginImporterExt.iOS.ARKit.Disable(), and UnityEditor.PluginImporterExt.iOS.ARKit.Enable().
Member Data Documentation
PATH
readonly string UnityEditor.PluginImporterExt.iOS.ARKit.PATH = PathExt.FixPath("Assets/Plugins/iOS/UnityARKit/NativeInterface/ARSessionNative.mm") static private
Definition at line 20 of file PluginImporterExt.cs.
Referenced by UnityEditor.PluginImporterExt.iOS.ARKit.SetCompileFlags().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/UnityEditor/PluginImporterExt.cs