Juniper: Juniper.Progress.IProgress Interface Reference
Juniper.Progress.IProgress Interface Reference
Progress reporting interface for asynchronous operations.
Public Member Functions
void Report (float progress, string status)
Report progress to a listener implementation.
Properties
float Progress [get]
The value of the most recent progress report.
Detailed Description
Progress reporting interface for asynchronous operations.
Definition at line 9 of file IProgress.cs.
Member Function Documentation
Report()
void Juniper.Progress.IProgress.Report (float progress, string status)
Report progress to a listener implementation.
Parameters
progress
status
Implemented in Juniper.Progress.ProgressStream, Juniper.Progress.ProgressSubdivision, and Juniper.Unity.Widgets.LoadingBar.
Referenced by Juniper.UnityEditor.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.UnityEditor.ConfigurationManagement.RawPackage.DeleteAll(), Juniper.Progress.IProgressExt.ForEach< T >(), Juniper.Unity.MasterSceneController.LoadScenePathCoroutine(), Juniper.Progress.ProgressSubdivision.Report(), Juniper.Progress.ProgressStream.Report(), and Juniper.Progress.IProgressExt.Report().
Property Documentation
Progress
float Juniper.Progress.IProgress.Progress get
The value of the most recent progress report.
Definition at line 15 of file IProgress.cs.
         {
             get;
         }
Referenced by Juniper.Progress.IProgressExt.IsComplete(), and Juniper.Unity.MasterSceneController.LoadScenePathCoroutine().
The documentation for this interface was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper.Progress/IProgress.cs