Juniper: Juniper.Unity.Audio.InteractionAudio Class Reference
Juniper.Unity.Audio.InteractionAudio Class Reference
The audio portion of the interaction system.
Public Member Functions
virtual void Awake ()
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
void Start ()
void OnValidate ()
Static Public Member Functions
static HapticExpression GetHapticExpressions (Interaction action)
Converst an Interaction into a haptic expression to be able to play.
static float Play (Interaction action, AbstractHapticDevice haptics)
Play the specified action at the camera position using the specified haptics, with no callback.
static float Play (Interaction action, Transform pose, AbstractHapticDevice haptics)
Play the specified action using the specified pose and haptic subsystem, with no callback.
static float Play (Interaction action, AbstractHapticDevice haptics, Action onComplete)
Play the specified action at the camera position using the specified haptics, with a callback on completion.
static float Play (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete)
Play the specified action using the specified pose and haptic subsystem, with a callback on completion.
static AudioSource Spatialize (AudioSource audioSource, bool loop, AudioMixerGroup group)
Public Attributes
GameObject volumeSlider
AudioMixerGroup defaultMixerGroup
The audio mixer to use with ResonanceAudio
AudioClip soundOnStartUp
The sound to play when the app first starts up.
AudioClip soundOnShutDown
The sound to play right before the app shuts down.
AudioClipCollection soundOnClosed
The sound to play when an Widgets.Openable object has been closed.
AudioClipCollection soundOnDisabled
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
AudioClipCollection soundOnDragged
The sound to play when a Widgets.Draggable has been moved more than 10cm.
AudioClipCollection soundOnEntered
The sound to play when a cursor first hovers over any Widgets.Touchable.
AudioClipCollection soundOnError
The sound to play when an operation needs to indicate an error.
AudioClipCollection soundOnExited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
AudioClipCollection soundOnOpened
The sound to play when an Widgets.Openable object has been opened.
AudioClipCollection soundOnReleased
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
AudioClipCollection soundOnScrolled
The sound to play when a scrollable section is moved a certain distance.
AudioClipCollection soundOnSelected
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
AudioClipCollection soundOnSuccess
The sound to play when a long-running operating needs to indicate success.
Protected Member Functions
AudioSource InternalSpatialize (AudioSource audioSource, bool loop, AudioMixerGroup group)
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Properties
float???? Volume [get, set]
Private Member Functions
void Volume_ValueChange (object sender, float value)
IAudioClipCollection GetClipCollection (Interaction action)
Converts an Interaction into a set of audio clips to be able to play.
IEnumerator Wait (float seconds, Action onComplete)
Waits a set number of seconds and then executs a callback function.
float Play_Internal (Interaction action, AbstractHapticDevice haptics)
float Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics)
float Play_Internal (Interaction action, AbstractHapticDevice haptics, Action onComplete)
float Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete)
void PlayHaptics (Interaction action, AbstractHapticDevice haptics)
Executes the haptic feedback portion of the interaction.
float PlayClip (Interaction action, Transform pose)
Plays the audio portion of the interaction.
AudioSource GetAudioSource (AudioClip clip)
Find or create a free Audio Source out of the pool.
AudioSource CreateNewAudioSource ()
Private Attributes
const string MASTER_VOLUME_KEY = "MasterVolume"
IValuedControl< float > volume
IAudioClipCollection startUp
The sound to play on application startup.
IAudioClipCollection shutDown
The sound to play on application shutdown.
List< AudioSource > audioSources
A pool of audio sources that can be moved around to play sounds wherever they are needed. The Play(Interaction, Transform, AbstractHapticDevice, Action) method will find whichever one is currently not playing and use it, or create a new one if all audio sources are currently playing. It starts out with 5 audio sources by default so that applications don't have to grow the collection right away.
Transform camT
The main camera, which also has the user's ears.
const float E = (float)Math.E
const string DEFAULT_AUDIO_MIXER = "ResonanceAudioMixer"
Static Private Attributes
static InteractionAudio instance
Detailed Description
The audio portion of the interaction system.
Definition at line 30 of file InteractionAudio.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Audio.InteractionAudio.Awake () inline virtual
Gets the system configuration, sets up the default haptics, provisions the interaction sound library, and initializes the spatial audio engine (if one was selected).
Definition at line 216 of file InteractionAudio.cs.
         {
             if (instance != null)
             {
                 Debug.LogWarning("Juniper: There can be only one! (R2D2)");
                 this.Destroy();
             }
             else
             {
                 instance = this;
                 camT = DisplayManager.MainCamera.transform;
 #if UNITY_MODULES_AUDIO
                 startUp = new SingleAudioClipCollection(soundOnStartUp, false);
                 shutDown = new SingleAudioClipCollection(soundOnShutDown, false);
                 audioSources = new List<AudioSource>();
                 volume = volumeSlider?.GetSlider();
                 volume.ValueChange += Volume_ValueChange;
 #endif
             }
         }
References Juniper.Unity.Audio.InteractionAudio.audioSources, Juniper.Unity.Audio.InteractionAudio.camT, Juniper.Unity.Audio.InteractionAudio.instance, Juniper.Unity.Display.AbstractDisplayManager.MainCamera, Juniper.Unity.Audio.InteractionAudio.shutDown, Juniper.Unity.Audio.InteractionAudio.soundOnShutDown, Juniper.Unity.Audio.InteractionAudio.soundOnStartUp, Juniper.Unity.Audio.InteractionAudio.startUp, Juniper.Unity.Widgets.IValuedControl< T >.ValueChange, Juniper.Unity.Audio.InteractionAudio.volume, Juniper.Unity.Audio.InteractionAudio.Volume_ValueChange(), and Juniper.Unity.Audio.InteractionAudio.volumeSlider.
CreateNewAudioSource()
AudioSource Juniper.Unity.Audio.InteractionAudio.CreateNewAudioSource () inline private
Definition at line 479 of file InteractionAudio.cs.
         {
             var audioSource = new GameObject()
                 .AddComponent<AudioSource>()
                 .Spatialize(defaultMixerGroup);
             audioSources.Add(audioSource);
             audioSource.name = "AudioSource" + audioSources.Count.ToString("00");
             return audioSource;
         }
References Juniper.Unity.Audio.InteractionAudio.audioSources, Juniper.Unity.Audio.InteractionAudio.defaultMixerGroup, and Juniper.Unity.Audio.InteractionAudio.Spatialize().
Referenced by Juniper.Unity.Audio.InteractionAudio.GetAudioSource(), and Juniper.Unity.Audio.InteractionAudio.Start().
GetAudioSource()
AudioSource Juniper.Unity.Audio.InteractionAudio.GetAudioSource (AudioClip clip) inline private
Find or create a free Audio Source out of the pool.
Returns
The audio source.
Definition at line 468 of file InteractionAudio.cs.
         {
             var source = audioSources
                 .Where(a => !a.isPlaying)
                 .OrderByDescending(a => a.clip == clip)
                 .FirstOrDefault()
                 ?? CreateNewAudioSource();
             source.clip = clip;
             return source;
         }
References Juniper.Unity.Audio.InteractionAudio.audioSources, and Juniper.Unity.Audio.InteractionAudio.CreateNewAudioSource().
Referenced by Juniper.Unity.Audio.InteractionAudio.PlayClip().
GetClipCollection()
IAudioClipCollection Juniper.Unity.Audio.InteractionAudio.GetClipCollection (Interaction action) inline private
Converts an Interaction into a set of audio clips to be able to play.
Returns
The audio clip.
Parameters
action Action.
Definition at line 280 of file InteractionAudio.cs.
         {
             switch (action)
             {
                 case Interaction.Closed:
                 return soundOnClosed;
                 case Interaction.Disabled:
                 return soundOnDisabled;
                 case Interaction.DraggingStarted:
                 case Interaction.Dragged:
                 case Interaction.DraggingEnded:
                 return soundOnDragged;
                 case Interaction.Scrolled:
                 return soundOnScrolled;
                 case Interaction.Entered:
                 return soundOnEntered;
                 case Interaction.Error:
                 return soundOnError;
                 case Interaction.Exited:
                 return soundOnExited;
                 case Interaction.Opened:
                 return soundOnOpened;
                 case Interaction.Released:
                 return soundOnReleased;
                 case Interaction.Clicked:
                 return soundOnSelected;
                 case Interaction.Success:
                 return soundOnSuccess;
 #if UNITY_MODULES_AUDIO
                 case Interaction.StartUp:
                 return startUp;
                 case Interaction.ShutDown:
                 return shutDown;
 #endif
                 default:
                 return null;
             }
         }
References Juniper.Unity.Audio.InteractionAudio.shutDown, Juniper.Unity.Audio.InteractionAudio.soundOnClosed, Juniper.Unity.Audio.InteractionAudio.soundOnDisabled, Juniper.Unity.Audio.InteractionAudio.soundOnDragged, Juniper.Unity.Audio.InteractionAudio.soundOnEntered, Juniper.Unity.Audio.InteractionAudio.soundOnError, Juniper.Unity.Audio.InteractionAudio.soundOnExited, Juniper.Unity.Audio.InteractionAudio.soundOnOpened, Juniper.Unity.Audio.InteractionAudio.soundOnReleased, Juniper.Unity.Audio.InteractionAudio.soundOnScrolled, Juniper.Unity.Audio.InteractionAudio.soundOnSelected, Juniper.Unity.Audio.InteractionAudio.soundOnSuccess, and Juniper.Unity.Audio.InteractionAudio.startUp.
Referenced by Juniper.Unity.Audio.InteractionAudio.PlayClip().
GetHapticExpressions()
static HapticExpression Juniper.Unity.Audio.InteractionAudio.GetHapticExpressions (Interaction action) inline static
Converst an Interaction into a haptic expression to be able to play.
Returns
The haptic expressions.
Parameters
action Action.
Definition at line 121 of file InteractionAudio.cs.
         {
             switch (action)
             {
                 case Interaction.Closed:
                 return HapticExpression.Heavy;
                 case Interaction.Disabled:
                 return HapticExpression.Warning;
                 case Interaction.DraggingStarted:
                 case Interaction.Dragged:
                 case Interaction.DraggingEnded:
                 return HapticExpression.SelectionChange;
                 case Interaction.Error:
                 return HapticExpression.Error;
                 case Interaction.Opened:
                 return HapticExpression.Medium;
                 case Interaction.Clicked:
                 return HapticExpression.Light;
                 case Interaction.Success:
                 return HapticExpression.Success;
                 default:
                 return HapticExpression.None;
             }
         }
Referenced by Juniper.Unity.Audio.InteractionAudio.PlayHaptics().
InternalSpatialize()
AudioSource Juniper.Unity.Audio.InteractionAudio.InternalSpatialize (AudioSource audioSource, bool loop, AudioMixerGroup group) inline protected
Set the common spatialization parameters for an AudioSource, including adding the necessary spatialization component for the platforms spatialization plugin.
Parameters
audioSource
loop
group
Returns
Definition at line 534 of file InteractionAudio.cs.
         {
             audioSource.loop = loop;
             audioSource.outputAudioMixerGroup = group ?? defaultMixerGroup;
             audioSource.spatialBlend = 1;
             audioSource.spatialize = true;
             audioSource.spatializePostEffects = true;
 #if UNITY_XR_WINDOWSMR_METRO
             var ms = audioSource.EnsureComponent<AudioSpatializerMicrosoft>();
             ms.Value.roomSize = AudioSpatializerMicrosoft.RoomSize.Medium;
 #elif RESONANCEAUDIO
             var goog = audioSource.EnsureComponent<ResonanceAudioSource>().Value;
             goog.quality = ResonanceAudioSource.Quality.High;
 #elif UNITY_XR_MAGICLEAP
             audioSource.EnsureComponent<MSA.MSASource>(null, (msa) =>
                 msa.Override3DProperties = true);
 #elif OCULUS
             var oculus = audioSource.EnsureComponent<ONSPAudioSource>().Value;
             oculus.EnableSpatialization = true;
             oculus.EnableRfl = true;
 #endif
             return audioSource;
         }
References Juniper.Unity.Audio.InteractionAudio.defaultMixerGroup.
Referenced by Juniper.Unity.Audio.InteractionAudio.Spatialize().
OnValidate()
void Juniper.Unity.Audio.InteractionAudio.OnValidate () inline
Definition at line 446 of file InteractionAudio.cs.
         {
             if (defaultMixerGroup == null)
             {
                 defaultMixerGroup =
                     (from g in Resources.FindObjectsOfTypeAll<AudioMixerGroup>()
                      where g.audioMixer.name == DEFAULT_AUDIO_MIXER
                      orderby g.name == "Master" descending
                      select g)
                         .FirstOrDefault();
             }
             if (defaultMixerGroup != null)
             {
                 Volume = PlayerPrefs.GetFloat(MASTER_VOLUME_KEY, 1);
             }
         }
References Juniper.Unity.Audio.InteractionAudio.DEFAULT_AUDIO_MIXER, Juniper.Unity.Audio.InteractionAudio.defaultMixerGroup, Juniper.Unity.Audio.InteractionAudio.MASTER_VOLUME_KEY, and Juniper.Unity.Audio.InteractionAudio.Volume.
Play() [1/4]
static float Juniper.Unity.Audio.InteractionAudio.Play (Interaction action, AbstractHapticDevice haptics) inline static
Play the specified action at the camera position using the specified haptics, with no callback.
Returns
The play.
Parameters
action Action.
haptics Haptics.
Definition at line 159 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, haptics) ?? 0;
         }
References Juniper.Unity.Audio.InteractionAudio.instance, and Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Referenced by Juniper.Unity.Widgets.AttentionDirector.FoundCoroutine(), Juniper.Unity.Widgets.AttentionDirector.LostCoroutine(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction().
Play() [2/4]
static float Juniper.Unity.Audio.InteractionAudio.Play (Interaction action, Transform pose, AbstractHapticDevice haptics) inline static
Play the specified action using the specified pose and haptic subsystem, with no callback.
Returns
The play.
Parameters
action Action.
pose Pose.
haptics Haptics.
Definition at line 171 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, pose, haptics) ?? 0;
         }
References Juniper.Unity.Audio.InteractionAudio.instance, and Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Play() [3/4]
static float Juniper.Unity.Audio.InteractionAudio.Play (Interaction action, AbstractHapticDevice haptics, Action onComplete) inline static
Play the specified action at the camera position using the specified haptics, with a callback on completion.
Returns
The play.
Parameters
action Action.
haptics Haptics.
onComplete
Definition at line 184 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, haptics, onComplete) ?? 0;
         }
References Juniper.Unity.Audio.InteractionAudio.instance, and Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Play() [4/4]
static float Juniper.Unity.Audio.InteractionAudio.Play (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete) inline static
Play the specified action using the specified pose and haptic subsystem, with a callback on completion.
Returns
The play.
Parameters
action Action.
pose Pose.
haptics Haptics.
onComplete
Definition at line 198 of file InteractionAudio.cs.
         {
             return instance?.Play_Internal(action, pose, haptics, onComplete) ?? 0;
         }
References Juniper.Unity.Audio.InteractionAudio.instance, and Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Play_Internal() [1/4]
float Juniper.Unity.Audio.InteractionAudio.Play_Internal (Interaction action, AbstractHapticDevice haptics) inline private
Definition at line 344 of file InteractionAudio.cs.
         {
             return Play_Internal(action, camT, haptics, null);
         }
References Juniper.Unity.Audio.InteractionAudio.camT.
Referenced by Juniper.Unity.Audio.InteractionAudio.Play(), and Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Play_Internal() [2/4]
float Juniper.Unity.Audio.InteractionAudio.Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics) inline private
Definition at line 349 of file InteractionAudio.cs.
         {
             return Play_Internal(action, pose, haptics, null);
         }
References Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Play_Internal() [3/4]
float Juniper.Unity.Audio.InteractionAudio.Play_Internal (Interaction action, AbstractHapticDevice haptics, Action onComplete) inline private
Definition at line 354 of file InteractionAudio.cs.
         {
             return Play_Internal(action, camT, haptics, onComplete);
         }
References Juniper.Unity.Audio.InteractionAudio.camT, and Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Play_Internal() [4/4]
float Juniper.Unity.Audio.InteractionAudio.Play_Internal (Interaction action, Transform pose, AbstractHapticDevice haptics, Action onComplete) inline private
Definition at line 359 of file InteractionAudio.cs.
         {
             if (action == Interaction.None)
             {
                 return 0;
             }
             else
             {
                 PlayHaptics(action, haptics);
                 var len = PlayClip(action, pose);
                 if (onComplete != null)
                 {
                     StartCoroutine(Wait(len, onComplete));
                 }
                 return len;
             }
         }
References Juniper.Unity.Audio.InteractionAudio.PlayClip(), Juniper.Unity.Audio.InteractionAudio.PlayHaptics(), and Juniper.Unity.Audio.InteractionAudio.Wait().
PlayClip()
float Juniper.Unity.Audio.InteractionAudio.PlayClip (Interaction action, Transform pose) inline private
Plays the audio portion of the interaction.
Returns
The clip.
Parameters
action Action.
pose Pose.
Definition at line 397 of file InteractionAudio.cs.
         {
 #if UNITY_MODULES_AUDIO
             var clips = GetClipCollection(action);
             var clip = clips?.Random();
             if (clip != null)
             {
                 var audioSource = GetAudioSource(clip);
                 if (clips.RandomizeClipPitch)
                 {
                     audioSource.pitch = UnityEngine.Random.Range(0.9f, 1.1f);
                 }
                 audioSource.transform.position = pose.position;
                 audioSource.transform.rotation = pose.rotation;
                 audioSource.Play();
                 return audioSource.clip.length;
             }
 #endif
             return 0;
         }
References Juniper.Unity.Audio.InteractionAudio.GetAudioSource(), and Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
Referenced by Juniper.Unity.Audio.InteractionAudio.Play_Internal().
PlayHaptics()
void Juniper.Unity.Audio.InteractionAudio.PlayHaptics (Interaction action, AbstractHapticDevice haptics) inline private
Executes the haptic feedback portion of the interaction.
Parameters
action Action.
haptics Haptics.
Definition at line 382 of file InteractionAudio.cs.
         {
             var expr = GetHapticExpressions(action);
             if (expr != HapticExpression.None)
             {
                 haptics?.Play(expr);
             }
         }
References Juniper.Unity.Audio.InteractionAudio.GetHapticExpressions(), and Juniper.Unity.Haptics.AbstractHapticDevice.Play().
Referenced by Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Spatialize()
static AudioSource Juniper.Unity.Audio.InteractionAudio.Spatialize (AudioSource audioSource, bool loop, AudioMixerGroup group) inline static
Definition at line 205 of file InteractionAudio.cs.
         {
             return instance?.InternalSpatialize(audioSource, loop, group);
         }
References Juniper.Unity.Audio.InteractionAudio.instance, and Juniper.Unity.Audio.InteractionAudio.InternalSpatialize().
Referenced by Juniper.Unity.Audio.InteractionAudio.CreateNewAudioSource(), and UnityEngine.AudioSourceExt.Spatialize().
Start()
void Juniper.Unity.Audio.InteractionAudio.Start () inline
Definition at line 423 of file InteractionAudio.cs.
         {
             for (var i = 0; i < 5; ++i)
             {
                 CreateNewAudioSource();
             }
             Volume = PlayerPrefs.GetFloat(MASTER_VOLUME_KEY, 1);
             if (volume != null)
             {
                 volume.value = Volume;
             }
         }
References Juniper.Unity.Audio.InteractionAudio.CreateNewAudioSource(), Juniper.Unity.Audio.InteractionAudio.MASTER_VOLUME_KEY, Juniper.Unity.Widgets.IValuedControl< T >.value, Juniper.Unity.Audio.InteractionAudio.volume, and Juniper.Unity.Audio.InteractionAudio.Volume.
Volume_ValueChange()
void Juniper.Unity.Audio.InteractionAudio.Volume_ValueChange (object sender, float value) inline private
Definition at line 240 of file InteractionAudio.cs.
         {
             Volume = value;
         }
References Juniper.Unity.Audio.InteractionAudio.Volume.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake().
Wait()
IEnumerator Juniper.Unity.Audio.InteractionAudio.Wait (float seconds, Action onComplete) inline private
Waits a set number of seconds and then executs a callback function.
Returns
The wait.
Parameters
seconds Seconds.
onComplete On complete.
Definition at line 338 of file InteractionAudio.cs.
         {
             yield return new WaitForSeconds(seconds);
             onComplete();
         }
Referenced by Juniper.Unity.Audio.InteractionAudio.Play_Internal().
Member Data Documentation
audioSources
List<AudioSource> Juniper.Unity.Audio.InteractionAudio.audioSources private
A pool of audio sources that can be moved around to play sounds wherever they are needed. The Play(Interaction, Transform, AbstractHapticDevice, Action) method will find whichever one is currently not playing and use it, or create a new one if all audio sources are currently playing. It starts out with 5 audio sources by default so that applications don't have to grow the collection right away.
Definition at line 266 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake(), Juniper.Unity.Audio.InteractionAudio.CreateNewAudioSource(), and Juniper.Unity.Audio.InteractionAudio.GetAudioSource().
camT
Transform Juniper.Unity.Audio.InteractionAudio.camT private
The main camera, which also has the user's ears.
Definition at line 273 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake(), and Juniper.Unity.Audio.InteractionAudio.Play_Internal().
DEFAULT_AUDIO_MIXER
const string Juniper.Unity.Audio.InteractionAudio.DEFAULT_AUDIO_MIXER = "ResonanceAudioMixer" private
Definition at line 439 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.OnValidate().
defaultMixerGroup
AudioMixerGroup Juniper.Unity.Audio.InteractionAudio.defaultMixerGroup
The audio mixer to use with ResonanceAudio
Definition at line 43 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.CreateNewAudioSource(), Juniper.Unity.Audio.InteractionAudio.InternalSpatialize(), and Juniper.Unity.Audio.InteractionAudio.OnValidate().
E
const float Juniper.Unity.Audio.InteractionAudio.E = (float)Math.E private
Definition at line 421 of file InteractionAudio.cs.
instance
InteractionAudio Juniper.Unity.Audio.InteractionAudio.instance static private
Definition at line 245 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake(), Juniper.Unity.Audio.InteractionAudio.Play(), and Juniper.Unity.Audio.InteractionAudio.Spatialize().
MASTER_VOLUME_KEY
const string Juniper.Unity.Audio.InteractionAudio.MASTER_VOLUME_KEY = "MasterVolume" private
Definition at line 36 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.OnValidate(), and Juniper.Unity.Audio.InteractionAudio.Start().
shutDown
IAudioClipCollection Juniper.Unity.Audio.InteractionAudio.shutDown private
The sound to play on application shutdown.
Definition at line 257 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake(), and Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnClosed
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnClosed
The sound to play when an Widgets.Openable object has been closed.
Definition at line 62 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnDisabled
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnDisabled
The sound to play when any Widgets.Touchable that has been set to disabled has been clicked.
Definition at line 68 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnDragged
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnDragged
The sound to play when a Widgets.Draggable has been moved more than 10cm.
Definition at line 73 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnEntered
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnEntered
The sound to play when a cursor first hovers over any Widgets.Touchable.
Definition at line 78 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnError
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnError
The sound to play when an operation needs to indicate an error.
Definition at line 83 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnExited
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnExited
The sound to play when a cursor leaves a Widgets.Touchable and is no longer hovering over it.
Definition at line 89 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnOpened
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnOpened
The sound to play when an Widgets.Openable object has been opened.
Definition at line 94 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnReleased
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnReleased
The sound to play when the primary selection button is no longer being pressed on a Widgets.Clickable.
Definition at line 99 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnScrolled
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnScrolled
The sound to play when a scrollable section is moved a certain distance.
Definition at line 104 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnSelected
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnSelected
The sound to play when the primary selection button is first being pressed on a Widgets.Clickable.
Definition at line 109 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
soundOnShutDown
AudioClip Juniper.Unity.Audio.InteractionAudio.soundOnShutDown
The sound to play right before the app shuts down.
Definition at line 54 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake().
soundOnStartUp
AudioClip Juniper.Unity.Audio.InteractionAudio.soundOnStartUp
The sound to play when the app first starts up.
Definition at line 49 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake().
soundOnSuccess
AudioClipCollection Juniper.Unity.Audio.InteractionAudio.soundOnSuccess
The sound to play when a long-running operating needs to indicate success.
Definition at line 114 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
startUp
IAudioClipCollection Juniper.Unity.Audio.InteractionAudio.startUp private
The sound to play on application startup.
Definition at line 252 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake(), and Juniper.Unity.Audio.InteractionAudio.GetClipCollection().
volume
IValuedControl<float> Juniper.Unity.Audio.InteractionAudio.volume private
Definition at line 38 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake(), and Juniper.Unity.Audio.InteractionAudio.Start().
volumeSlider
GameObject Juniper.Unity.Audio.InteractionAudio.volumeSlider
Definition at line 32 of file InteractionAudio.cs.
Referenced by Juniper.Unity.Audio.InteractionAudio.Awake(), and Juniper.Unity.MasterSceneController.SetupSystemInterface().
Property Documentation
Volume
float???? Juniper.Unity.Audio.InteractionAudio.Volume get set
Definition at line 492 of file InteractionAudio.cs.
         {
             set
             {
 #if UNITY_MODULES_AUDIO
                 PlayerPrefs.SetFloat(MASTER_VOLUME_KEY, value);
                 PlayerPrefs.Save();
                 var log = Mathf.Log(value) * 11.5f;
                 if (float.IsInfinity(log))
                 {
                     log = -1000;
                 }
                 defaultMixerGroup
                     ?.audioMixer
                     ?.SetFloat("Volume", log);
 #endif
             }
             get
             {
                 float value = 0;
 #if UNITY_MODULES_AUDIO
                 if (defaultMixerGroup?.audioMixer?.GetFloat("Volume", out value) == true)
                 {
                     value = Mathf.Pow(E, value / 11.5f);
                 }
 #endif
                 return value;
             }
         }
Referenced by Juniper.Unity.Audio.InteractionAudio.OnValidate(), Juniper.Unity.Audio.InteractionAudio.Start(), and Juniper.Unity.Audio.InteractionAudio.Volume_ValueChange().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Audio/InteractionAudio.cs