Juniper: Juniper.Input.UnifiedInputModule Class Reference
Juniper.Input.UnifiedInputModule Class Reference
Public Member Functions
override void UpdateModule ()
Manages the input controllers, either motion controllers on WindowsMR headsets, or hand tracking on HoloLens.
void ClickButtons (IEnumerable< IPointerClickHandler > buttons)
void AddKeyboardShortcut (Keyboardable shortcut)
void RemoveKeyboardShortcut (Keyboardable shortcut)
void AddPointer (IPointerDevice pointer)
virtual void Reinstall ()
Reinstall the object with a full reset.
virtual void Install (bool reset)
Install, with or without a full reset.
T MakePointer< T > (Transform parent, string path)
virtual void Uninstall ()
Remove platform-specific features from the object.
JuniperPointerEventData GetJuniperPointerData (int pointerDataID)
JuniperPointerEventData Clone (int pointerDataID, JuniperPointerEventData original)
override void Process ()
Find all the pointers and fire raycaster events for them.
void ProcessPointer (IPointerDevice pointer)
void RequestMode (InputModes newMode, bool value)
bool IsModeRequested (InputModes checkMode)
void ToggleModeRequested (InputModes newMode)
Public Attributes
readonly List< IPointerDevice > Devices = new List<IPointerDevice>(12)
bool paused
GameObject pointerPrefab
Set to the clonable object that should be used for the pointer probe.
Material laserPointerNormalMaterial
Material laserPointerEnabledMaterial
Material laserPointerDisabledMaterial
GazePointer Gaze
Mouse Mouse
TouchPoint [] Touches
MotionController [] Controllers
HandTracker [] Hands
NetworkPointer Helper
KeywordRecognizer Voice
float minPointerDistance = 1.5f
float maxPointerDistance = 25f
int ControllerLayer
float canvasOffset = 0.2f
Protected Member Functions
override void Awake ()
Protected Attributes
Avatar stage
Properties
override bool HasFloorPosition [get]
override InputModes DefaultInputMode [get]
static bool HasGamepad [get]
bool AnyPointerDragging [get]
bool VoiceAvailable [get]
bool VoiceEnabled [get]
bool VoiceRequested [get, set]
bool GazeAvailable [get]
bool GazeEnabled [get]
bool GazeRequested [get, set]
bool MouseAvailable [get]
bool MouseEnabled [get]
bool MouseRequested [get, set]
bool TouchAvailable [get]
bool TouchEnabled [get]
bool TouchRequested [get, set]
bool HandsAvailable [get]
bool HandsEnabled [get]
bool HandsRequested [get, set]
bool ControllersAvailable [get]
bool ControllersEnabled [get]
bool ControllersRequested [get, set]
IPointerDevice ActiveController [get]
Detailed Description
Definition at line 28 of file UnifiedInputModule.cs.
Member Function Documentation
AddKeyboardShortcut()
void Juniper.Input.AbstractUnifiedInputModule.AddKeyboardShortcut (Keyboardable shortcut) inline inherited
Definition at line 152 of file UnifiedInputModule.cs.
         {
             newKeyboardShortcuts.MaybeAdd(shortcut);
         }
References Juniper.Input.AbstractUnifiedInputModule.newKeyboardShortcuts.
Referenced by Juniper.Input.Keyboardable.OnEnable().
AddPointer()
void Juniper.Input.AbstractUnifiedInputModule.AddPointer (IPointerDevice pointer) inline inherited
Definition at line 186 of file UnifiedInputModule.cs.
         {
             if (pointer != null
                 && !Devices.Contains(pointer)
                 && !newDevices.Contains(pointer))
             {
                 newDevices.Add(pointer);
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.Devices, and Juniper.Input.AbstractUnifiedInputModule.newDevices.
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Start().
Awake()
override void Juniper.Input.AbstractUnifiedInputModule.Awake () inline protected inherited
Definition at line 200 of file UnifiedInputModule.cs.
         {
             base.Awake();
             Install(false);
             ControllerLayer = Devices
                 .Union(newDevices)
                 .Select(d => (int?)d.Layer)
                 .FirstOrDefault()
                 ?? LayerMask.NameToLayer("Ignore Raycast");
             requestedMode = SavedInputMode;
         }
References Juniper.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Input.AbstractUnifiedInputModule.Devices, Juniper.Input.AbstractUnifiedInputModule.Install(), Juniper.Input.AbstractUnifiedInputModule.newDevices, Juniper.Input.AbstractUnifiedInputModule.requestedMode, and Juniper.Input.AbstractUnifiedInputModule.SavedInputMode.
ClickButtons()
void Juniper.Input.AbstractUnifiedInputModule.ClickButtons (IEnumerable< IPointerClickHandler > buttons) inline inherited
Definition at line 87 of file UnifiedInputModule.cs.
         {
             var pointerEvent = new JuniperPointerEventData(eventSystem)
             {
                 button = PointerEventData.InputButton.Left,
                 keyCode = KeyCode.Mouse0,
                 eligibleForClick = true,
                 clickCount = 1,
                 clickTime = Time.unscaledTime,
             };
             foreach (var button in buttons)
             {
                 if (button != null)
                 {
                     button.OnPointerClick(pointerEvent);
                 }
             }
         }
Referenced by Juniper.Input.AbstractShortcutable.ActivateEvent().
Clone()
JuniperPointerEventData Juniper.Input.AbstractUnifiedInputModule.Clone (int pointerDataID, JuniperPointerEventData original) inline inherited
Definition at line 348 of file UnifiedInputModule.cs.
         {
             var clone = GetJuniperPointerData(pointerDataID);
             clone.delta = original.delta;
             clone.position = original.position;
             clone.scrollDelta = original.scrollDelta;
             clone.pointerEnter = original.pointerEnter;
             clone.useDragThreshold = original.useDragThreshold;
             clone.pointerCurrentRaycast = original.pointerCurrentRaycast;
             if (original.clickCount == -1)
             {
                 clone.eligibleForClick = false;
                 clone.clickCount = 0;
             }
             return clone;
         }
References Juniper.Input.AbstractUnifiedInputModule.GetJuniperPointerData().
Referenced by Juniper.Input.Pointers.AbstractPointerDevice< Unary, UnaryPointerConfiguration, NoHaptics >.Clone().
GetJuniperPointerData()
JuniperPointerEventData Juniper.Input.AbstractUnifiedInputModule.GetJuniperPointerData (int pointerDataID) inline inherited
Definition at line 299 of file UnifiedInputModule.cs.
         {
             if (!m_PointerData.ContainsKey(pointerDataID))
             {
                 m_PointerData[pointerDataID] = new JuniperPointerEventData(eventSystem);
             }
             var data = m_PointerData[pointerDataID];
             if (!(data is JuniperPointerEventData))
             {
                 var clone = new JuniperPointerEventData(eventSystem)
                 {
                     button = data.button,
                     clickCount = data.clickCount,
                     clickTime = data.clickTime,
                     delta = data.delta,
                     dragging = data.dragging,
                     eligibleForClick = data.eligibleForClick,
                     pointerCurrentRaycast = data.pointerCurrentRaycast,
                     pointerDrag = data.pointerDrag,
                     pointerEnter = data.pointerEnter,
                     pointerId = data.pointerId,
                     pointerPress = data.pointerPress,
                     pointerPressRaycast = data.pointerPressRaycast,
                     position = data.position,
                     pressPosition = data.pressPosition,
                     rawPointerPress = data.rawPointerPress,
                     scrollDelta = data.scrollDelta,
                     selectedObject = data.selectedObject,
                     useDragThreshold = data.useDragThreshold
                 };
                 if (data.hovered != null)
                 {
                     if (clone.hovered == null)
                     {
                         clone.hovered = new List<GameObject>();
                     }
                     clone.hovered.AddRange(data.hovered);
                 }
                 data = clone;
             }
             return (JuniperPointerEventData)data;
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Clone(), and Juniper.Input.AbstractUnifiedInputModule.ProcessPointer().
Install()
virtual void Juniper.Input.AbstractUnifiedInputModule.Install (bool reset) inline virtual inherited
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfully. False if the installable should be recycled and tried again.
Implements Juniper.IO.IInstallable.
Definition at line 221 of file UnifiedInputModule.cs.
         {
 #if UNITY_EDITOR
             if (pointerPrefab == null)
             {
                 pointerPrefab = ResourceExt.EditorLoadAsset<GameObject>("Assets/Juniper/Assets/Prefabs/Rigs/DiskProbe2018.2.prefab");
             }
             if (laserPointerNormalMaterial == null)
             {
                 laserPointerNormalMaterial = ResourceExt.EditorLoadAsset<Material>("Assets/Juniper/Assets/Materials/LaserPointer_White.mat");
             }
             if (laserPointerEnabledMaterial == null)
             {
                 laserPointerEnabledMaterial = ResourceExt.EditorLoadAsset<Material>("Assets/Juniper/Assets/Materials/LaserPointer_Green.mat");
             }
             if (laserPointerDisabledMaterial == null)
             {
                 laserPointerDisabledMaterial = ResourceExt.EditorLoadAsset<Material>("Assets/Juniper/Assets/Materials/LaserPointer_Red.mat");
             }
 #endif
             Find.Any(out stage);
             stage.Install(reset);
             stage.IndependentHead = HasFloorPosition;
             Gaze = MakePointer<GazePointer>(stage.Head, "GazePointer");
             Mouse = MakePointer<Mouse>(stage.Head, "Mouse");
             Helper = MakePointer<NetworkPointer>(stage.Hands, "Network");
             Touches = new TouchPoint[10];
             for (var i = 0; i < Touches.Length; ++i)
             {
                 Touches[i] = MakePointer<TouchPoint>(stage.Head, $"Touches/TouchPoint{i.ToString()}");
                 Touches[i].fingerID = i;
             }
             Controllers = MotionController.MakeControllers(MakeHandPointer<MotionController>);
             Hands = HandTracker.MakeControllers(MakeHandPointer<HandTracker>);
             Voice = this.FindClosest<KeywordRecognizer>();
         }
References Juniper.Input.AbstractUnifiedInputModule.Controllers, Juniper.Input.Pointers.Screen.TouchPoint.fingerID, Juniper.Input.AbstractUnifiedInputModule.Gaze, Juniper.Avatar.Hands, Juniper.Input.AbstractUnifiedInputModule.Hands, Juniper.Input.AbstractUnifiedInputModule.HasFloorPosition, Juniper.Avatar.Head, Juniper.Input.AbstractUnifiedInputModule.Helper, Juniper.Avatar.IndependentHead, Juniper.Avatar.Install(), Juniper.Input.AbstractUnifiedInputModule.laserPointerDisabledMaterial, Juniper.Input.AbstractUnifiedInputModule.laserPointerEnabledMaterial, Juniper.Input.AbstractUnifiedInputModule.laserPointerNormalMaterial, Juniper.Input.AbstractUnifiedInputModule.pointerPrefab, Juniper.Input.AbstractUnifiedInputModule.stage, Juniper.Input.AbstractUnifiedInputModule.Touches, and Juniper.Input.AbstractUnifiedInputModule.Voice.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.Reinstall().
IsModeRequested()
bool Juniper.Input.AbstractUnifiedInputModule.IsModeRequested (InputModes checkMode) inline inherited
Definition at line 612 of file UnifiedInputModule.cs.
         {
             return requestedMode.HasFlag(checkMode);
         }
References Juniper.Input.AbstractUnifiedInputModule.requestedMode.
Referenced by Juniper.Input.AbstractUnifiedInputModule.ToggleModeRequested().
MakePointer< T >()
T Juniper.Input.AbstractUnifiedInputModule.MakePointer< T > (Transform parent, string path) inline inherited
Type Constraints
T : Component
T : IPointerDevice
Definition at line 273 of file UnifiedInputModule.cs.
                     : Component, IPointerDevice
         {
             var p = parent.Ensure<Transform>(path)
                 .Ensure<T>();
             p.tag = "GameController";
             p.Value.Layer = LayerMask.NameToLayer("Ignore Raycast");
             return p;
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.MakeHandPointer< T >().
Process()
override void Juniper.Input.AbstractUnifiedInputModule.Process () inline inherited
Find all the pointers and fire raycaster events for them.
Definition at line 369 of file UnifiedInputModule.cs.
         {
             if (requestedMode != currentMode)
             {
                 if (requestedMode == InputModes.Auto)
                 {
                     requestedMode = SavedInputMode;
                 }
                 // Validate the InputModes that has been set
                 var voice = VoiceRequestApproved;
                 var controllers = ControllersRequestApproved;
                 var hands = HandsRequestApproved;
                 var mouse = MouseRequestApproved;
                 var gaze = GazeRequestApproved;
                 var touch = TouchRequestApproved;
                 // Enable a default device if no devices are enabled
                 if (!controllers && !hands && !mouse && !touch && !gaze)
                 {
                     if (ControllersAvailable)
                     {
                         controllers = true;
                     }
                     else if (HandsAvailable)
                     {
                         hands = true;
                     }
                     else if (MouseAvailable)
                     {
                         mouse = true;
                     }
                     else if (TouchAvailable)
                     {
                         touch = true;
                     }
                     else if (GazeAvailable)
                     {
                         gaze = true;
                     }
                 }
                 if (Voice != null)
                 {
                     Voice.enabled = voice;
                 }
                 Gaze.SetActive(gaze);
                 Mouse.SetActive(mouse);
                 foreach (var touchPoint in Touches)
                 {
                     touchPoint.SetActive(touch);
                 }
                 foreach (var handTracker in Hands)
                 {
                     handTracker.SetActive(hands);
                 }
                 foreach (var motionController in Controllers)
                 {
                     motionController.SetActive(controllers);
                 }
                 // record the actual input mode
                 VoiceRequested = voice;
                 ControllersRequested = controllers;
                 MouseRequested = mouse;
                 TouchRequested = touch;
                 HandsRequested = hands;
                 GazeRequested = gaze;
                 SavedInputMode = currentMode = requestedMode;
             }
             if (newDevices.Count > 0)
             {
                 foreach(var device in newDevices)
                 {
                     device.LaserPointerNormalMaterial = laserPointerNormalMaterial;
                     device.LaserPointerEnabledMaterial = laserPointerEnabledMaterial;
                     device.LaserPointerDisabledMaterial = laserPointerDisabledMaterial;
                 }
                 Devices.AddRange(newDevices);
                 newDevices.Clear();
             }
             if (newKeyboardShortcuts.Count > 0)
             {
                 keyboardShortcuts.AddRange(newKeyboardShortcuts);
                 newKeyboardShortcuts.Clear();
             }
             keyPresses.Clear();
             toActivate.Clear();
             toRemove.Clear();
             foreach (var pointer in Devices)
             {
                 if (pointer.ProcessInUpdate)
                 {
                     ProcessPointer(pointer);
                 }
             }
             foreach (var shortcut in keyboardShortcuts)
             {
                 if (shortcut == null
                     || !shortcut.gameObject.scene.isLoaded)
                 {
                     toRemove.MaybeAdd(shortcut);
                 }
                 else if (shortcut.IsInteractable()
                     && (UnityInput.GetKeyUp(shortcut.KeyCode)
                         || keyPresses.Contains(shortcut.KeyCode)))
                 {
                     toActivate.MaybeAdd(shortcut);
                 }
             }
             foreach (var shortcut in toRemove)
             {
                 keyboardShortcuts.Remove(shortcut);
             }
             if (!paused)
             {
                 foreach (var shortcut in toActivate)
                 {
                     shortcut.ActivateEvent();
                 }
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.Controllers, Juniper.Input.AbstractUnifiedInputModule.ControllersAvailable, Juniper.Input.AbstractUnifiedInputModule.ControllersRequestApproved, Juniper.Input.AbstractUnifiedInputModule.ControllersRequested, Juniper.Input.AbstractUnifiedInputModule.currentMode, Juniper.Input.AbstractUnifiedInputModule.Devices, Juniper.Input.AbstractUnifiedInputModule.Gaze, Juniper.Input.AbstractUnifiedInputModule.GazeAvailable, Juniper.Input.AbstractUnifiedInputModule.GazeRequestApproved, Juniper.Input.AbstractUnifiedInputModule.GazeRequested, Juniper.Input.AbstractUnifiedInputModule.Hands, Juniper.Input.AbstractUnifiedInputModule.HandsAvailable, Juniper.Input.AbstractUnifiedInputModule.HandsRequestApproved, Juniper.Input.AbstractUnifiedInputModule.HandsRequested, Juniper.Input.AbstractUnifiedInputModule.keyboardShortcuts, Juniper.Input.AbstractUnifiedInputModule.keyPresses, Juniper.Input.AbstractUnifiedInputModule.laserPointerDisabledMaterial, Juniper.Input.AbstractUnifiedInputModule.laserPointerEnabledMaterial, Juniper.Input.AbstractUnifiedInputModule.laserPointerNormalMaterial, Juniper.Input.AbstractUnifiedInputModule.MouseAvailable, Juniper.Input.AbstractUnifiedInputModule.MouseRequestApproved, Juniper.Input.AbstractUnifiedInputModule.MouseRequested, Juniper.Input.AbstractUnifiedInputModule.newDevices, Juniper.Input.AbstractUnifiedInputModule.newKeyboardShortcuts, Juniper.Input.AbstractUnifiedInputModule.paused, Juniper.Input.AbstractUnifiedInputModule.ProcessPointer(), Juniper.Input.AbstractUnifiedInputModule.requestedMode, Juniper.Input.AbstractUnifiedInputModule.SavedInputMode, Juniper.Input.AbstractUnifiedInputModule.toActivate, Juniper.Input.AbstractUnifiedInputModule.toRemove, Juniper.Input.AbstractUnifiedInputModule.TouchAvailable, Juniper.Input.AbstractUnifiedInputModule.Touches, Juniper.Input.AbstractUnifiedInputModule.TouchRequestApproved, Juniper.Input.AbstractUnifiedInputModule.TouchRequested, Juniper.Input.AbstractUnifiedInputModule.Voice, Juniper.Input.AbstractUnifiedInputModule.VoiceRequestApproved, and Juniper.Input.AbstractUnifiedInputModule.VoiceRequested.
ProcessPointer()
void Juniper.Input.AbstractUnifiedInputModule.ProcessPointer (IPointerDevice pointer) inline inherited
Definition at line 506 of file UnifiedInputModule.cs.
         {
             pointer.Layer = ControllerLayer;
             if (pointer.IsEnabled)
             {
                 var evtData = GetJuniperPointerData(pointer.PointerDataID);
                 evtData.delta = pointer.ScreenDelta;
                 evtData.position = pointer.ScreenPoint;
                 evtData.scrollDelta = pointer.ScrollDelta;
                 evtData.useDragThreshold = eventSystem.pixelDragThreshold > 0;
                 UpdateRay(pointer, evtData);
                 pointer.Process(evtData, eventSystem.pixelDragThreshold * eventSystem.pixelDragThreshold, keyPresses, paused);
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.ControllerLayer, Juniper.Input.AbstractUnifiedInputModule.GetJuniperPointerData(), Juniper.Input.Pointers.IPointerDevice.IsEnabled, Juniper.Input.AbstractUnifiedInputModule.keyPresses, Juniper.Input.Pointers.IPointerDevice.Layer, Juniper.Input.AbstractUnifiedInputModule.paused, Juniper.Input.Pointers.IPointerDevice.PointerDataID, Juniper.Input.Pointers.IPointerDevice.Process(), Juniper.Input.Pointers.IPointerDevice.ScreenDelta, Juniper.Input.Pointers.IPointerDevice.ScreenPoint, Juniper.Input.Pointers.IPointerDevice.ScrollDelta, and Juniper.Input.AbstractUnifiedInputModule.UpdateRay().
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
Reinstall()
virtual void Juniper.Input.AbstractUnifiedInputModule.Reinstall () inline virtual inherited
Reinstall the object with a full reset.
Implements Juniper.IO.IInstallable.
Definition at line 216 of file UnifiedInputModule.cs.
         {
             Install(false);
         }
References Juniper.Input.AbstractUnifiedInputModule.Install().
RemoveKeyboardShortcut()
void Juniper.Input.AbstractUnifiedInputModule.RemoveKeyboardShortcut (Keyboardable shortcut) inline inherited
Definition at line 157 of file UnifiedInputModule.cs.
         {
             newKeyboardShortcuts.Remove(shortcut);
         }
References Juniper.Input.AbstractUnifiedInputModule.newKeyboardShortcuts.
Referenced by Juniper.Input.Keyboardable.OnDisable().
RequestMode()
void Juniper.Input.AbstractUnifiedInputModule.RequestMode (InputModes newMode, bool value) inline inherited
Definition at line 600 of file UnifiedInputModule.cs.
         {
             if (value)
             {
                 requestedMode |= newMode;
             }
             else
             {
                 requestedMode &= ~newMode;
             }
         }
References Juniper.Input.AbstractUnifiedInputModule.requestedMode.
Referenced by Juniper.Input.AbstractUnifiedInputModule.ToggleModeRequested().
ToggleModeRequested()
void Juniper.Input.AbstractUnifiedInputModule.ToggleModeRequested (InputModes newMode) inline inherited
Definition at line 617 of file UnifiedInputModule.cs.
         {
             RequestMode(newMode, !IsModeRequested(newMode));
         }
References Juniper.Input.AbstractUnifiedInputModule.IsModeRequested(), and Juniper.Input.AbstractUnifiedInputModule.RequestMode().
Referenced by Juniper.Settings.AccessibilitySettings.ToggleGaze(), Juniper.Settings.AccessibilitySettings.ToggleHands(), Juniper.Settings.AccessibilitySettings.ToggleScreen(), and Juniper.Settings.AccessibilitySettings.ToggleVoice().
Uninstall()
virtual void Juniper.Input.AbstractUnifiedInputModule.Uninstall () inline virtual inherited
Remove platform-specific features from the object.
Implements Juniper.IO.IInstallable.
Definition at line 283 of file UnifiedInputModule.cs.
         {
             requestedMode = InputModes.Auto;
         }
References Juniper.Input.AbstractUnifiedInputModule.requestedMode.
UpdateModule()
override void Juniper.Input.WindowsMRInputModule.UpdateModule () inline inherited
Manages the input controllers, either motion controllers on WindowsMR headsets, or hand tracking on HoloLens.
Definition at line 11 of file WindowsMRInputModule.cs.
         {
             base.UpdateModule();
             var kind = Pointers.Motion.WindowsMRMotionController.UpdateReadings();
             if (mode == Mode.None)
             {
 error-out: mind the input mode
                 mode = kind == UnityEngine.XR.WSA.Input.InteractionSourceKind.Controller
                     ? Mode.StandingVR
                     : Mode.HeadsetAR;
             }
         }
Member Data Documentation
canvasOffset
float Juniper.Input.AbstractUnifiedInputModule.canvasOffset = 0.2f inherited
Definition at line 562 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.RaycastAll().
ControllerLayer
int Juniper.Input.AbstractUnifiedInputModule.ControllerLayer inherited
Definition at line 198 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Awake(), Juniper.Animation.FadeTransition.OnEntered(), Juniper.Animation.FadeTransition.OnExiting(), and Juniper.Input.AbstractUnifiedInputModule.ProcessPointer().
Controllers
MotionController [] Juniper.Input.AbstractUnifiedInputModule.Controllers inherited
Definition at line 176 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
Devices
readonly List<IPointerDevice> Juniper.Input.AbstractUnifiedInputModule.Devices = new List<IPointerDevice>(12) inherited
Definition at line 124 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.AddPointer(), Juniper.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Input.AbstractUnifiedInputModule.Process().
Gaze
GazePointer Juniper.Input.AbstractUnifiedInputModule.Gaze inherited
Definition at line 173 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
Hands
HandTracker [] Juniper.Input.AbstractUnifiedInputModule.Hands inherited
Definition at line 177 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
Helper
NetworkPointer Juniper.Input.AbstractUnifiedInputModule.Helper inherited
Definition at line 179 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install().
laserPointerDisabledMaterial
Material Juniper.Input.AbstractUnifiedInputModule.laserPointerDisabledMaterial inherited
Definition at line 171 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
laserPointerEnabledMaterial
Material Juniper.Input.AbstractUnifiedInputModule.laserPointerEnabledMaterial inherited
Definition at line 170 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
laserPointerNormalMaterial
Material Juniper.Input.AbstractUnifiedInputModule.laserPointerNormalMaterial inherited
Definition at line 169 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
maxPointerDistance
float Juniper.Input.AbstractUnifiedInputModule.maxPointerDistance = 25f inherited
Definition at line 184 of file UnifiedInputModule.cs.
minPointerDistance
float Juniper.Input.AbstractUnifiedInputModule.minPointerDistance = 1.5f inherited
Definition at line 183 of file UnifiedInputModule.cs.
Mouse
Mouse Juniper.Input.AbstractUnifiedInputModule.Mouse inherited
Definition at line 174 of file UnifiedInputModule.cs.
paused
bool Juniper.Input.AbstractUnifiedInputModule.paused inherited
Definition at line 134 of file UnifiedInputModule.cs.
Referenced by Juniper.MasterSceneController.Awake(), Juniper.Input.AbstractUnifiedInputModule.Process(), Juniper.Input.AbstractUnifiedInputModule.ProcessPointer(), and Juniper.MasterSceneController.SwitchToSceneCoroutine().
pointerPrefab
GameObject Juniper.Input.AbstractUnifiedInputModule.pointerPrefab inherited
Set to the clonable object that should be used for the pointer probe.
Definition at line 165 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install().
stage
Avatar Juniper.Input.AbstractUnifiedInputModule.stage protected inherited
Definition at line 196 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.MakeHandPointer< T >().
Touches
TouchPoint [] Juniper.Input.AbstractUnifiedInputModule.Touches inherited
Definition at line 175 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), and Juniper.Input.AbstractUnifiedInputModule.Process().
Voice
KeywordRecognizer Juniper.Input.AbstractUnifiedInputModule.Voice inherited
Definition at line 181 of file UnifiedInputModule.cs.
Referenced by Juniper.Input.AbstractUnifiedInputModule.Install(), Juniper.Speech.Keywordable.OnDisable(), Juniper.Speech.Keywordable.OnEnable(), and Juniper.Input.AbstractUnifiedInputModule.Process().
Property Documentation
ActiveController
IPointerDevice Juniper.Input.AbstractUnifiedInputModule.ActiveController get inherited
Definition at line 810 of file UnifiedInputModule.cs.
         {
             get
             {
                 if (MouseEnabled)
                 {
                     return Mouse;
                 }
                 if (ControllersEnabled)
                 {
                     foreach (var controller in Controllers)
                     {
                         if (controller.IsConnected)
{
                             return controller;
                         }
                     }
                 }
                 if (TouchEnabled)
                 {
                     foreach (var touch in Touches)
                     {
                         if (touch.IsConnected)
{
                             return touch;
                         }
                     }
                 }
                 if (HandsEnabled)
                 {
                     foreach (var hand in Hands)
                     {
                         if (hand.IsConnected)
{
                             return hand;
                         }
                     }
                 }
                 if (GazeEnabled)
                 {
                     return Gaze;
                 }
                 return null;
             }
         }
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.SyncData().
AnyPointerDragging
bool Juniper.Input.AbstractUnifiedInputModule.AnyPointerDragging get inherited
Definition at line 137 of file UnifiedInputModule.cs.
         {
             get
             {
                 foreach (var device in Devices)
                 {
                     if (device.IsDragging)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Input.CameraControl.Update().
ControllersAvailable
bool Juniper.Input.AbstractUnifiedInputModule.ControllersAvailable get inherited
Definition at line 780 of file UnifiedInputModule.cs.
         {
             get
             {
                 return AnyDeviceConnected(Controllers);
             }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
ControllersEnabled
bool Juniper.Input.AbstractUnifiedInputModule.ControllersEnabled get inherited
Definition at line 788 of file UnifiedInputModule.cs.
         {
             get
             {
                 return AnyDeviceEnabled(Controllers);
             }
         }
ControllersRequested
bool Juniper.Input.AbstractUnifiedInputModule.ControllersRequested get set inherited
Definition at line 796 of file UnifiedInputModule.cs.
         {
             get { return IsModeRequested(InputModes.Motion); }
             set { RequestMode(InputModes.Mouse, value); }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
DefaultInputMode
override InputModes Juniper.Input.WindowsMRInputModule.DefaultInputMode get inherited
Definition at line 34 of file WindowsMRInputModule.cs.
         {
             get
             {
                 return InputModes.StandingVR;
             }
         }
GazeAvailable
bool Juniper.Input.AbstractUnifiedInputModule.GazeAvailable get inherited
Definition at line 655 of file UnifiedInputModule.cs.
         {
             get
             {
                 return Gaze.IsConnected;
             }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
GazeEnabled
bool Juniper.Input.AbstractUnifiedInputModule.GazeEnabled get inherited
Definition at line 663 of file UnifiedInputModule.cs.
         {
             get
             {
                 return Gaze.IsEnabled;
             }
         }
GazeRequested
bool Juniper.Input.AbstractUnifiedInputModule.GazeRequested get set inherited
Definition at line 671 of file UnifiedInputModule.cs.
         {
             get { return IsModeRequested(InputModes.Gaze); }
             set { RequestMode(InputModes.Gaze, value); }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
HandsAvailable
bool Juniper.Input.AbstractUnifiedInputModule.HandsAvailable get inherited
Definition at line 750 of file UnifiedInputModule.cs.
         {
             get
             {
                 return AnyDeviceConnected(Hands);
             }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
HandsEnabled
bool Juniper.Input.AbstractUnifiedInputModule.HandsEnabled get inherited
Definition at line 758 of file UnifiedInputModule.cs.
         {
             get
             {
                 return AnyDeviceEnabled(Hands);
             }
         }
HandsRequested
bool Juniper.Input.AbstractUnifiedInputModule.HandsRequested get set inherited
Definition at line 766 of file UnifiedInputModule.cs.
         {
             get { return IsModeRequested(InputModes.Hands); }
             set { RequestMode(InputModes.Hands, value); }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
HasFloorPosition
override bool Juniper.Input.WindowsMRInputModule.HasFloorPosition get inherited
Definition at line 26 of file WindowsMRInputModule.cs.
         {
             get
             {
                 return true;
             }
         }
HasGamepad
bool Juniper.Input.AbstractUnifiedInputModule.HasGamepad static get inherited
Definition at line 108 of file UnifiedInputModule.cs.
         {
             get
             {
                 foreach (var j in UnityInput.GetJoystickNames())
                 {
                     if (!string.IsNullOrEmpty(j))
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
MouseAvailable
bool Juniper.Input.AbstractUnifiedInputModule.MouseAvailable get inherited
Definition at line 688 of file UnifiedInputModule.cs.
         {
             get
             {
                 return Mouse.IsConnected;
             }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
MouseEnabled
bool Juniper.Input.AbstractUnifiedInputModule.MouseEnabled get inherited
Definition at line 696 of file UnifiedInputModule.cs.
         {
             get
             {
                 return Mouse.IsEnabled;
             }
         }
MouseRequested
bool Juniper.Input.AbstractUnifiedInputModule.MouseRequested get set inherited
Definition at line 703 of file UnifiedInputModule.cs.
         {
             get { return IsModeRequested(InputModes.Mouse); }
             set { RequestMode(InputModes.Mouse, value); }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
TouchAvailable
bool Juniper.Input.AbstractUnifiedInputModule.TouchAvailable get inherited
Definition at line 717 of file UnifiedInputModule.cs.
         {
             get
             {
                 return AnyDeviceConnected(Touches);
             }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
TouchEnabled
bool Juniper.Input.AbstractUnifiedInputModule.TouchEnabled get inherited
Definition at line 725 of file UnifiedInputModule.cs.
         {
             get
             {
                 return AnyDeviceEnabled(Touches);
             }
         }
TouchRequested
bool Juniper.Input.AbstractUnifiedInputModule.TouchRequested get set inherited
Definition at line 733 of file UnifiedInputModule.cs.
         {
             get { return IsModeRequested(InputModes.Touch); }
             set { RequestMode(InputModes.Touch, value); }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
VoiceAvailable
bool Juniper.Input.AbstractUnifiedInputModule.VoiceAvailable get inherited
Definition at line 623 of file UnifiedInputModule.cs.
         {
             get
             {
                 return Voice != null
                     && Voice.IsAvailable;
             }
         }
VoiceEnabled
bool Juniper.Input.AbstractUnifiedInputModule.VoiceEnabled get inherited
Definition at line 632 of file UnifiedInputModule.cs.
         {
             get
             {
                 return Voice != null
                     && Voice.isActiveAndEnabled;
             }
         }
Referenced by Juniper.Speech.Keywordable.IsInteractable().
VoiceRequested
bool Juniper.Input.AbstractUnifiedInputModule.VoiceRequested get set inherited
Definition at line 649 of file UnifiedInputModule.cs.
         {
             get { return IsModeRequested(InputModes.Voice); }
             set { RequestMode(InputModes.Voice, value); }
         }
Referenced by Juniper.Input.AbstractUnifiedInputModule.Process().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Input/UnifiedInputModule.cs