Juniper: Juniper.IO.StreamingAssetsCacheLayer Class Reference
Juniper.IO.StreamingAssetsCacheLayer Class Reference
Public Member Functions
StreamingAssetsCacheLayer ()
StreamingAssetsCacheLayer (string subDirName)
virtual bool CanCache (ContentReference fileRef)
FileInfo Resolve (ContentReference fileRef)
Converts a ContentReference to a FileInfo as if the file exists in this cache layer. Check FileInfo.Exists to make sure the file actually exists.
bool IsCached (ContentReference fileRef)
Stream Create (ContentReference fileRef)
Task< Stream > GetStreamAsync (ContentReference fileRef, IProgress prog)
IEnumerable< ContentReference > GetContentReferences (MediaType ofType)
bool Delete (ContentReference fileRef)
Static Public Member Functions
static Task UnpackAPKAsync (IProgress prog)
Properties
static bool NeedsUnpack [get]
Static Private Attributes
static string RootDir
Detailed Description
Definition at line 10 of file StreamingAssetsCacheLayer.cs.
Constructor & Destructor Documentation
StreamingAssetsCacheLayer() [1/2]
Juniper.IO.StreamingAssetsCacheLayer.StreamingAssetsCacheLayer () inline
Definition at line 34 of file StreamingAssetsCacheLayer.cs.
             : base(RootDir)
         { }
StreamingAssetsCacheLayer() [2/2]
Juniper.IO.StreamingAssetsCacheLayer.StreamingAssetsCacheLayer (string subDirName) inline
Definition at line 38 of file StreamingAssetsCacheLayer.cs.
             : base(Path.Combine(RootDir, subDirName))
         { }
Member Function Documentation
CanCache()
virtual bool Juniper.IO.FileCacheLayer.CanCache (ContentReference fileRef) inline virtual inherited
Implements Juniper.IO.ICacheDestinationLayer.
Reimplemented in Juniper.World.GIS.Google.GoogleMapsCacheLayer.
Definition at line 21 of file FileCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             return !fileRef.DoNotCache;
         }
References Juniper.IO.ContentReference.DoNotCache.
Referenced by Juniper.IO.FileCacheLayer.Create().
Create()
Stream Juniper.IO.FileCacheLayer.Create (ContentReference fileRef) inline inherited
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 49 of file FileCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             if (!CanCache(fileRef))
             {
                 throw new ArgumentException("Cannot cache this file.", fileRef.ToString());
             }
             var file = Resolve(fileRef);
             file.Directory.Create();
             return file.Create();
         }
References Juniper.IO.FileCacheLayer.CanCache(), Juniper.IO.FileCacheLayer.Resolve(), and Juniper.IO.ContentReference.ToString().
Delete()
bool Juniper.IO.FileCacheLayer.Delete (ContentReference fileRef) inline inherited
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 102 of file FileCacheLayer.cs.
         {
             var file = Resolve(fileRef);
             return file.TryDelete();
         }
References Juniper.IO.FileCacheLayer.Resolve().
GetContentReferences()
IEnumerable<ContentReference> Juniper.IO.FileCacheLayer.GetContentReferences (MediaType ofType) inline inherited
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 84 of file FileCacheLayer.cs.
         {
             if (ofType is null)
             {
                 throw new ArgumentNullException(nameof(ofType));
             }
             foreach (var ext in ofType.Extensions)
             {
                 foreach (var file in cacheLocation.GetFiles($"*.{ext}"))
                 {
                     var shortName = file.Name;
                     var cacheID = PathExt.RemoveShortExtension(shortName);
                     yield return cacheID + ofType;
                 }
             }
         }
References Juniper.IO.FileCacheLayer.cacheLocation, and System.IO.PathExt.RemoveShortExtension().
GetStreamAsync()
Task<Stream> Juniper.IO.FileCacheLayer.GetStreamAsync (ContentReference fileRef, IProgress prog) inline inherited
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 66 of file FileCacheLayer.cs.
         {
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             if (!IsCached(fileRef))
             {
                 throw new FileNotFoundException("File not found in disk cache!", fileRef.ToString());
             }
             var file = Resolve(fileRef);
             var stream = file.OpenRead();
             var progStream = new ProgressStream(stream, file.Length, prog, true);
             return Task.FromResult((Stream)progStream);
         }
References Juniper.IO.FileCacheLayer.IsCached(), Juniper.IO.FileCacheLayer.Resolve(), and Juniper.IO.ContentReference.ToString().
IsCached()
bool Juniper.IO.FileCacheLayer.IsCached (ContentReference fileRef) inline inherited
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 43 of file FileCacheLayer.cs.
         {
             var file = Resolve(fileRef);
             return file.Exists;
         }
References Juniper.IO.FileCacheLayer.Resolve().
Referenced by Juniper.IO.FileCacheLayer.GetStreamAsync().
Resolve()
FileInfo Juniper.IO.FileCacheLayer.Resolve (ContentReference fileRef) inline inherited
Converts a ContentReference to a FileInfo as if the file exists in this cache layer. Check FileInfo.Exists to make sure the file actually exists.
Parameters
fileRef
Returns
Definition at line 38 of file FileCacheLayer.cs.
         {
             return cacheLocation + fileRef;
         }
References Juniper.IO.FileCacheLayer.cacheLocation.
Referenced by Juniper.IO.FileCacheLayer.Create(), Juniper.IO.FileCacheLayer.Delete(), Juniper.IO.FileCacheLayer.GetStreamAsync(), and Juniper.IO.FileCacheLayer.IsCached().
UnpackAPKAsync()
static Task Juniper.IO.StreamingAssetsCacheLayer.UnpackAPKAsync (IProgress prog) inline static
Definition at line 21 of file StreamingAssetsCacheLayer.cs.
         {
             var apk = Application.dataPath;
             var appData = Application.persistentDataPath;
             return Task.Run(() =>
                 Decompressor.Decompress(apk, appData, "assets/", prog));
         }
References Juniper.Compression.Zip.Decompressor.Decompress().
Referenced by Juniper.MasterSceneController.LoadFirstSceneCoroutine().
Member Data Documentation
RootDir
string Juniper.IO.StreamingAssetsCacheLayer.RootDir static private
Initial value:
=>
            PathExt.FixPath(NeedsUnpack
                ? Application.persistentDataPath
                : Application.streamingAssetsPath)
Definition at line 29 of file StreamingAssetsCacheLayer.cs.
Property Documentation
NeedsUnpack
bool Juniper.IO.StreamingAssetsCacheLayer.NeedsUnpack static get
Definition at line 13 of file StreamingAssetsCacheLayer.cs.
         {
             get
             {
                 return Application.platform == RuntimePlatform.Android
                     && !Application.isEditor;
             }
         }
Referenced by Juniper.MasterSceneController.LoadFirstSceneCoroutine().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Unity/IO/StreamingAssetsCacheLayer.cs