Juniper: Juniper.Unity.JuniperSystem Class Reference
Juniper.Unity.JuniperSystem Class Reference
Public Member Functions
void Awake ()
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
virtual void Reinstall ()
Reinstall the object with a full reset.
bool Install (bool reset)
Install, with or without a full reset.
void Uninstall ()
Remove platform-specific features from the object.
Public Attributes
PlatformTypes CurrentPlatform
SystemTypes System
DisplayTypes DisplayType
DisplayTypes SupportedDisplayType
AugmentedRealityTypes ARMode
AugmentedRealityTypes SupportedARMode
Options Option
Detailed Description
Definition at line 15 of file JuniperSystem.cs.
Member Function Documentation
Awake()
void Juniper.Unity.JuniperSystem.Awake () inline
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
Definition at line 72 of file JuniperSystem.cs.
         {
             var scenes = ComponentExt.FindAny<MasterSceneController>();
             if (scenes != null && scenes.gameObject.scene != gameObject.scene)
             {
                 gameObject.Destroy();
             }
             else
             {
                 Install(false);
             }
         }
References Juniper.Unity.JuniperSystem.Install().
Install()
bool Juniper.Unity.JuniperSystem.Install (bool reset) inline
Install, with or without a full reset.
Parameters
reset
Returns
True, if the installation completed successfuly. False if the installable should be recycled and tried again.
Implements Juniper.IInstallable.
Definition at line 110 of file JuniperSystem.cs.
         {
             var head = DisplayManager
                 .MainCamera
                 .Ensure<DisplayManager>()
                 .transform;
             var stage = head.parent;
             if (stage == null)
             {
                 stage = new GameObject().transform;
                 head.Reparent(stage);
             }
             stage.name = "Stage";
             stage.Ensure<StageExtensions>();
             if (stage.parent != transform)
             {
                 stage.Reparent(transform);
             }
             this.Ensure<EventSystem>();
             this.Ensure<UnifiedInputModule>();
             this.Ensure<AnchorStore>();
             this.Ensure<InteractionAudio>();
             this.Ensure<MasterSceneController>();
             this.Ensure<PermissionHandler>();
             return true;
         }
References Juniper.Unity.Display.AbstractDisplayManager.MainCamera.
Referenced by Juniper.Unity.JuniperSystem.Awake(), and Juniper.Unity.JuniperSystem.Reinstall().
Reinstall()
virtual void Juniper.Unity.JuniperSystem.Reinstall () inline virtual
Reinstall the object with a full reset.
Implements Juniper.IInstallable.
Definition at line 85 of file JuniperSystem.cs.
         {
             Install(true);
         }
References Juniper.Unity.JuniperSystem.Install().
Uninstall()
void Juniper.Unity.JuniperSystem.Uninstall () inline
Remove platform-specific features from the object.
Implements Juniper.IInstallable.
Definition at line 141 of file JuniperSystem.cs.
         {
         }
Member Data Documentation
ARMode
AugmentedRealityTypes Juniper.Unity.JuniperSystem.ARMode
Definition at line 30 of file JuniperSystem.cs.
CurrentPlatform
PlatformTypes Juniper.Unity.JuniperSystem.CurrentPlatform
Definition at line 18 of file JuniperSystem.cs.
DisplayType
DisplayTypes Juniper.Unity.JuniperSystem.DisplayType
Definition at line 24 of file JuniperSystem.cs.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Install().
Option
Options Juniper.Unity.JuniperSystem.Option
Definition at line 36 of file JuniperSystem.cs.
SupportedARMode
AugmentedRealityTypes Juniper.Unity.JuniperSystem.SupportedARMode
Definition at line 33 of file JuniperSystem.cs.
SupportedDisplayType
DisplayTypes Juniper.Unity.JuniperSystem.SupportedDisplayType
Definition at line 27 of file JuniperSystem.cs.
System
SystemTypes Juniper.Unity.JuniperSystem.System
Definition at line 21 of file JuniperSystem.cs.
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/XR/JuniperSystem.cs