Juniper: BitMiracle.LibJpeg.IRawImage Interface Reference
BitMiracle.LibJpeg.IRawImage Interface Reference
Public Member Functions
void BeginRead ()
byte [] GetPixelRow ()
void EndRead ()
Properties
int Width [get]
int Height [get]
Colorspace Colorspace [get]
int ComponentsPerPixel [get]
Detailed Description
Definition at line 3 of file IRawImage.cs.
Member Function Documentation
BeginRead()
void BitMiracle.LibJpeg.IRawImage.BeginRead ()
Implemented in BitMiracle.LibJpeg.RawImage.
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
EndRead()
void BitMiracle.LibJpeg.IRawImage.EndRead ()
Implemented in BitMiracle.LibJpeg.RawImage.
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
GetPixelRow()
byte [] BitMiracle.LibJpeg.IRawImage.GetPixelRow ()
Implemented in BitMiracle.LibJpeg.RawImage.
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
Property Documentation
Colorspace
Colorspace BitMiracle.LibJpeg.IRawImage.Colorspace get
Definition at line 12 of file IRawImage.cs.
 { get; }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
ComponentsPerPixel
int BitMiracle.LibJpeg.IRawImage.ComponentsPerPixel get
Definition at line 15 of file IRawImage.cs.
 { get; }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
Height
int BitMiracle.LibJpeg.IRawImage.Height get
Definition at line 9 of file IRawImage.cs.
 { get; }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
Width
int BitMiracle.LibJpeg.IRawImage.Width get
Definition at line 6 of file IRawImage.cs.
 { get; }
Referenced by BitMiracle.LibJpeg.Jpeg.Compress().
The documentation for this interface was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/IRawImage.cs