Juniper: Juniper.HTTP.Server.HttpListenerResponseExt Class Reference
Juniper.HTTP.Server.HttpListenerResponseExt Class Reference
Static Public Member Functions
static async Task SendContentAsync (this HttpListenerResponse response, ICacheSourceLayer layer, ContentReference fileRef)
static async Task SendContentAsync (this HttpListenerResponse response, AbstractStreamSource source)
static async Task SendFileAsync (this HttpListenerResponse response, FileInfo file)
static Task SendTextAsync (this HttpListenerResponse response, string text)
static Task SendTextAsync (this HttpListenerResponse response, MediaType contentType, string text)
static Task SendBytesAsync (this HttpListenerResponse response, MediaType contentType, byte[] data)
static Task SendStreamAsync (this HttpListenerResponse response, MediaType contentType, Stream input)
static void SetStatus (this HttpListenerResponse response, HttpStatusCode code)
static HttpStatusCode GetStatus (this HttpListenerResponse response)
static void SetFileName (this HttpListenerResponse response, MediaType type, string fileName)
Detailed Description
Definition at line 12 of file HttpListenerResponseExt.cs.
Member Function Documentation
GetStatus()
static HttpStatusCode Juniper.HTTP.Server.HttpListenerResponseExt.GetStatus (this HttpListenerResponse response) inline static
Definition at line 165 of file HttpListenerResponseExt.cs.
         {
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             return (HttpStatusCode)response.StatusCode;
         }
SendBytesAsync()
static Task Juniper.HTTP.Server.HttpListenerResponseExt.SendBytesAsync (this HttpListenerResponse response, MediaType contentType, byte [] data) inline static
Definition at line 113 of file HttpListenerResponseExt.cs.
         {
             if (data is null)
             {
                 throw new ArgumentNullException(nameof(data));
             }
             using var mem = new MemoryStream(data);
             return response.SendStreamAsync(contentType, mem);
         }
SendContentAsync() [1/2]
static async Task Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync (this HttpListenerResponse response, ICacheSourceLayer layer, ContentReference fileRef) inline static
Definition at line 14 of file HttpListenerResponseExt.cs.
         {
             if (layer is null)
             {
                 throw new ArgumentNullException(nameof(layer));
             }
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             response.SetFileName(fileRef.ContentType, fileRef.FileName);
             using var stream = await layer
                 .GetStreamAsync(fileRef, null)
                 .ConfigureAwait(false);
             await response
                 .SendStreamAsync(fileRef.ContentType, stream)
                 .ConfigureAwait(false);
         }
References Juniper.IO.ContentReference.ContentType, Juniper.IO.ContentReference.FileName, and Juniper.IO.ICacheSourceLayer.GetStreamAsync().
SendContentAsync() [2/2]
static async Task Juniper.HTTP.Server.HttpListenerResponseExt.SendContentAsync (this HttpListenerResponse response, AbstractStreamSource source) inline static
Definition at line 40 of file HttpListenerResponseExt.cs.
         {
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             if (source is null)
             {
                 throw new ArgumentNullException(nameof(source));
             }
             response.SetFileName(source.ContentType, source.FileName);
             using var stream = await source
                 .GetStreamAsync()
                 .ConfigureAwait(false);
             await response.SendStreamAsync(source.ContentType, stream)
                 .ConfigureAwait(false);
         }
References Juniper.IO.ContentReference.ContentType, Juniper.IO.ContentReference.FileName, and Juniper.IO.AbstractStreamSource.GetStreamAsync().
SendFileAsync()
static async Task Juniper.HTTP.Server.HttpListenerResponseExt.SendFileAsync (this HttpListenerResponse response, FileInfo file) inline static
Definition at line 64 of file HttpListenerResponseExt.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             if (!file.Exists)
             {
                 throw new FileNotFoundException("File not found: " + file.FullName, file.FullName);
             }
             MediaType type = MediaType.Application.Octet_Stream;
             var types = MediaType.GuessByFile(file);
             if (types.Count > 0)
             {
                 type = types[0];
             }
             response.SetFileName(type, file.Name);
             using var input = file.OpenRead();
             await response.SendStreamAsync(type, input)
                 .ConfigureAwait(false);
         }
References Juniper.MediaType.GuessByFile(), and Juniper.MediaType.Application.Octet_Stream.
SendStreamAsync()
static Task Juniper.HTTP.Server.HttpListenerResponseExt.SendStreamAsync (this HttpListenerResponse response, MediaType contentType, Stream input) inline static
Definition at line 127 of file HttpListenerResponseExt.cs.
         {
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             if (contentType is null)
             {
                 throw new ArgumentNullException(nameof(contentType));
             }
             if (input is null)
             {
                 throw new ArgumentNullException(nameof(input));
             }
             response.ContentType = contentType;
             response.ContentLength64 += input.Length;
             response.AddHeader("Date", DateTime.Now.ToString("r", CultureInfo.InvariantCulture));
             return input.CopyToAsync(response.OutputStream);
         }
SendTextAsync() [1/2]
static Task Juniper.HTTP.Server.HttpListenerResponseExt.SendTextAsync (this HttpListenerResponse response, string text) inline static
Definition at line 93 of file HttpListenerResponseExt.cs.
         {
             return response.SendTextAsync(MediaType.Text.Plain, text);
         }
References Juniper.MediaType.Text.Plain.
SendTextAsync() [2/2]
static Task Juniper.HTTP.Server.HttpListenerResponseExt.SendTextAsync (this HttpListenerResponse response, MediaType contentType, string text) inline static
Definition at line 100 of file HttpListenerResponseExt.cs.
         {
             if (text is null)
             {
                 throw new ArgumentNullException(nameof(text));
             }
             return response.SendBytesAsync(contentType, Encoding.UTF8.GetBytes(text));
         }
SetFileName()
static void Juniper.HTTP.Server.HttpListenerResponseExt.SetFileName (this HttpListenerResponse response, MediaType type, string fileName) inline static
Definition at line 175 of file HttpListenerResponseExt.cs.
         {
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             if (type is object
                 && type != MediaType.Text.AnyText
                 && type != MediaType.Image.AnyImage
                 && type != MediaType.Application.Javascript
                 && fileName is object)
             {
                 response.Headers.Add("Content-Disposition", $"attachment; filename={fileName}");
             }
         }
References Juniper.MediaType.Image.AnyImage, Juniper.MediaType.Text.AnyText, and Juniper.MediaType.Application.Javascript.
SetStatus()
static void Juniper.HTTP.Server.HttpListenerResponseExt.SetStatus (this HttpListenerResponse response, HttpStatusCode code) inline static
Definition at line 153 of file HttpListenerResponseExt.cs.
         {
             if (response is null)
             {
                 throw new ArgumentNullException(nameof(response));
             }
             response.StatusCode = (int)code;
         }
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Server/HttpListenerResponseExt.cs