Juniper: Juniper.ConfigurationManagement.JuniperConfigurationManager Class Reference
Juniper.ConfigurationManagement.JuniperConfigurationManager Class Reference
An editor to respond to changes in XRSystem.
Static Public Member Functions
static bool SetAndroid_MenuItem_Validate ()
static void SetAndroid_MenuItem ()
static bool SetAndroid_ARCore_MenuItem_Validate ()
static void SetAndroid_ARCore_MenuItem ()
static bool SetAndroid_Cardboard_MenuItem_Validate ()
static void SetAndroid_Cardboard_MenuItem ()
static bool SetAndroid_Daydream_MenuItem_Validate ()
static void SetAndroid_Daydream_MenuItem ()
static bool SetAndroid_Oculus_MenuItem_Validate ()
static void SetAndroid_Oculus_MenuItem ()
static bool SetAndroid_ViveFocus_MenuItem_Validate ()
static void SetAndroid_ViveFocus_MenuItem ()
static bool SetIOS_MenuItem_Validate ()
static void SetIOS_MenuItem ()
static bool SetIOS_ARKit_MenuItem_Validate ()
static void SetIOS_ARKit_MenuItem ()
static bool SetIOS_Cardboard_MenuItem_Validate ()
static void SetIOS_Cardboard_MenuItem ()
static bool SetStandalone_MenuItem_Validate ()
static void SetStandalone_MenuItem ()
static bool SetStandalone_Oculus_MenuItem_Validate ()
static void SetStandalone_Oculus_MenuItem ()
static bool SetStandalone_SteamVR_MenuItem_Validate ()
static void SetStandalone_SteamVR_MenuItem ()
static bool SetUWP_MenuItem_Validate ()
static void SetUWP_MenuItem ()
static bool SetUWP_WindowsMR_MenuItem_Validate ()
static void SetUWP_WindowsMR_MenuItem ()
static bool SetUWP_HoloLens_MenuItem_Validate ()
static void SetUWP_HoloLens_MenuItem ()
static bool SetMagicLeap_MenuItem_Validate ()
static void SetMagicLeap_MenuItem ()
static void ClearProgressDialog_MenuItem ()
static void Other_ResetConfiguration ()
static bool Other_ResumeBuild_Validate ()
static void Other_ResumeBuild ()
static void Other_Recompile_Menu ()
static void RefreshPackages ()
static void ActivatePlatform ()
static void PrepareScene ()
Properties
static int BuildProgress [get, set]
static PlatformTypes CurrentPlatform [get]
static PlatformTypes DesiredPlatform [get]
static bool BuildInProgress [get]
static bool RebuildNeeded [get]
static PlatformTypes NextPlatform [get, set]
static PlatformConfiguration LastConfiguration [get]
static PlatformConfiguration NextConfiguration [get]
static string [] JUNIPER_DEFINES [get]
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
Static Private Member Functions
static JuniperConfigurationManager ()
static bool Config_PlatformChanged ()
static string ThirdPartyDefines (BuildTargetGroup targetGroup)
static bool MenuCheck (PlatformTypes p)
static void Uninstall ()
static void Install ()
static void OnCancel ()
static void OnCancel (bool canceledByUser)
static void OnEditorUpdate (Action resolve, Action reject=null, Func< bool > test=null)
static void DelayedUpdate (IProgressReceiver prog, float maxTime, Action onComplete)
static List< string > FormatDefines (ref string definesString)
static IProgressReceiver PrepareBuildStep (int offset, string prefix=null)
static void WithProgress (string prefix, Action< IProgressReceiver > act)
static void Recompile (bool advanceBuildStep, string nextDefinesString=null)
static void RecompilePlatformInternal ()
static IEnumerable< IInstallable > GetInstallables ()
static void ResumeBuild ()
static void StartBuild ()
static void DeactivatePlatform ()
Private Attributes
const string MENU_NAME = "Juniper/"
const string ANDROID_MENU_NAME = MENU_NAME + "Android/"
const string IOS_MENU_NAME = MENU_NAME + "IOS/"
const string STANDALONE_MENU_NAME = MENU_NAME + "Standalone/"
const string UWP_MENU_NAME = MENU_NAME + "UWP/"
const string OTHER_MENU_NAME = MENU_NAME + "Other/"
const string RECOMPILE_SLUG = "RECOMPILE_SLUG"
Static Private Attributes
static readonly ProjectConfiguration config
static string LastPrefix
static readonly Action [] STAGES
static readonly string MANIFEST_FILE = PathExt.FixPath("Packages/manifest.json")
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 23 of file JuniperConfigurationManager.cs.
Constructor & Destructor Documentation
JuniperConfigurationManager()
static Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager () inline static private
Definition at line 29 of file JuniperConfigurationManager.cs.
         {
             config = ProjectConfiguration.Load();
             config.PlatformChanged += Config_PlatformChanged;
             config.PlatformChangeConfirmed += StartBuild;
             if (RebuildNeeded)
             {
                 OnEditorUpdate(() =>
                     NextPlatform = DesiredPlatform,
                     () => EditorUtility.DisplayDialog("Juniper", "Could not change platform.", "OK"));
             }
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), Juniper.ConfigurationManagement.JuniperConfigurationManager.DesiredPlatform, Juniper.ConfigurationManagement.ProjectConfiguration.Load(), Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), Juniper.ConfigurationManagement.ProjectConfiguration.PlatformChangeConfirmed, Juniper.ConfigurationManagement.ProjectConfiguration.PlatformChanged, Juniper.ConfigurationManagement.JuniperConfigurationManager.RebuildNeeded, and Juniper.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
Member Function Documentation
ActivatePlatform()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform () inline static
Definition at line 664 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Activating Platform " + NextPlatform, _ =>
             {
                 var newDefinesString = ThirdPartyDefines(NextConfiguration.TargetGroup);
                 var newDefines = newDefinesString.Split(';').ToList();
                 newDefines.MaybeAddRange(NextConfiguration.CompilerDefines);
                 Recompile(true, string.Join(";", newDefines));
             });
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.CompilerDefines, Juniper.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.ConfigurationManagement.PlatformConfiguration.TargetGroup, Juniper.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
ClearProgressDialog_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.ClearProgressDialog_MenuItem () inline static
Definition at line 405 of file JuniperConfigurationManager.cs.
         {
             EditorUtility.ClearProgressBar();
         }
Config_PlatformChanged()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged () inline static private
Definition at line 101 of file JuniperConfigurationManager.cs.
         {
             if (!Platforms.Instance.PlatformDB[config.NextPlatform].IsSupported)
             {
                 EditorUtility.DisplayDialog(
                    "Juniper",
                    $"The platform {config.NextPlatform} is not supported on your current system.",
                    "OK");
                 return false;
             }
             else
             {
                 return config.NextPlatform == PlatformTypes.None
                     || (config.NextPlatform != CurrentPlatform
                         && EditorUtility.DisplayDialog(
                             "Juniper",
                             $"You are about to change the platfrom from {CurrentPlatform} to {config.NextPlatform}. Do you want to continue?",
                             "Change platform",
                             "Don't change platform"));
             }
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform, Juniper.ConfigurationManagement.Platforms.Instance, Juniper.ConfigurationManagement.ProjectConfiguration.NextPlatform, and Juniper.ConfigurationManagement.Platforms.PlatformDB.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
DeactivatePlatform()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform () inline static private
Definition at line 617 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Resetting to base configuration", _ =>
             {
                 Installable.UninstallAll(GetInstallables);
                 LastConfiguration.Deactivate(NextConfiguration, ThirdPartyDefines(NextConfiguration.TargetGroup));
                 Recompile(true, ThirdPartyDefines(LastConfiguration.TargetGroup));
             });
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.Deactivate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), Juniper.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration, Juniper.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.ConfigurationManagement.PlatformConfiguration.TargetGroup, Juniper.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines(), Juniper.Installable.UninstallAll(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
DelayedUpdate()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate (IProgressReceiver prog, float maxTime, Action onComplete) inline static private
Definition at line 484 of file JuniperConfigurationManager.cs.
         {
             prog?.SetProgress(0);
             var startTime = DateTime.Now;
             OnEditorUpdate(() =>
             {
                 EditorUtility.ClearProgressBar();
                 onComplete();
             }, OnCancel, () =>
             {
                 var age = (float)(DateTime.Now - startTime).TotalSeconds;
                 prog?.SetProgress(age, maxTime);
                 return age > maxTime;
             });
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), and Juniper.Progress.IProgressReceiver.SetProgress().
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile().
FormatDefines()
static List<string> Juniper.ConfigurationManagement.JuniperConfigurationManager.FormatDefines (ref string definesString) inline static private
Definition at line 500 of file JuniperConfigurationManager.cs.
         {
             var defines = definesString?.Split(';')?.ToList() ?? new List<string>();
             defines.Sort();
             // move the slug to the end, if it exists
             if (defines.Contains(RECOMPILE_SLUG))
             {
                 defines.Remove(RECOMPILE_SLUG);
                 defines.Add(RECOMPILE_SLUG);
             }
             definesString = string.Join(";", defines);
             return defines;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile().
GetInstallables()
static IEnumerable<IInstallable> Juniper.ConfigurationManagement.JuniperConfigurationManager.GetInstallables () inline static private
Definition at line 585 of file JuniperConfigurationManager.cs.
         {
             return ComponentExt
                 .FindAll<Component>()
                 .OfType<IInstallable>();
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.Install(), Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareScene(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.Uninstall().
Install()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.Install () inline static private
Definition at line 397 of file JuniperConfigurationManager.cs.
         {
             Uninstall();
             JuniperPlatform.Ensure();
             Installable.InstallAll(GetInstallables);
         }
References Juniper.JuniperPlatform.Ensure(), Juniper.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), Juniper.Installable.InstallAll(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.Uninstall().
MenuCheck()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck (PlatformTypes p) inline static private
Definition at line 165 of file JuniperConfigurationManager.cs.
         {
             return CurrentPlatform != p && Platforms.Instance.PlatformDB[p].IsSupported;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform, Juniper.ConfigurationManagement.Platforms.Instance, and Juniper.ConfigurationManagement.Platforms.PlatformDB.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem_Validate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem_Validate(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem_Validate().
OnCancel() [1/2]
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.OnCancel () inline static private
Definition at line 441 of file JuniperConfigurationManager.cs.
         {
             OnCancel(true);
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareScene(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
OnCancel() [2/2]
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.OnCancel (bool canceledByUser) inline static private
Definition at line 446 of file JuniperConfigurationManager.cs.
         {
             if (canceledByUser)
             {
                 Debug.LogWarning("Canceled by user");
             }
             EditorUtility.ClearProgressBar();
             BuildProgress = -1;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildProgress.
OnEditorUpdate()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate (Action resolve, Action reject = null, Func< bool > test = null) inline static private
Definition at line 456 of file JuniperConfigurationManager.cs.
         {
             if (test == null)
             {
                 test = () => true;
             }
             EditorApplication.CallbackFunction exec = null;
             exec = () =>
             {
                 if (test())
                 {
                     try
                     {
                         EditorApplication.update -= exec;
                         resolve();
                     }
                     catch (OperationCanceledException)
                     {
                         EditorApplication.update -= exec;
                         reject();
                     }
                 }
             };
             EditorApplication.update += exec;
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareScene().
Other_Recompile_Menu()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu () inline static
Definition at line 429 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Recompiling platform " + NextPlatform, _ =>
                 RecompilePlatformInternal());
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Other_ResetConfiguration()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_ResetConfiguration () inline static
Definition at line 411 of file JuniperConfigurationManager.cs.
         {
             StartBuild();
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
Other_ResumeBuild()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild () inline static
Definition at line 423 of file JuniperConfigurationManager.cs.
         {
             ResumeBuild();
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
Other_ResumeBuild_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild_Validate () inline static
Definition at line 417 of file JuniperConfigurationManager.cs.
         {
             return BuildInProgress;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress.
PrepareBuildStep()
static IProgressReceiver Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep (int offset, string prefix = null) inline static private
Definition at line 518 of file JuniperConfigurationManager.cs.
         {
             LastPrefix = prefix ?? LastPrefix;
             var step = BuildProgress - offset + 1;
             var msg = $"Juniper ({step} of {STAGES.Length}): {LastPrefix}";
             return new UnityEditorProgressDialog(msg)
                 .Subdivide(step + BuildProgress, 2 * STAGES.Length, LastPrefix);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.ConfigurationManagement.JuniperConfigurationManager.LastPrefix, and Juniper.ConfigurationManagement.JuniperConfigurationManager.STAGES.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
PrepareScene()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareScene () inline static
Definition at line 675 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Preparing scene", _ =>
             {
                 var xr = JuniperPlatform.Ensure();
                 var scene = xr.gameObject.scene;
                 config.Commit();
                 OnCancel(false);
                 Installable.InstallAll(GetInstallables);
                 EditorSceneManager.MarkSceneDirty(scene);
                 if (EditorUtility.DisplayDialog("Juniper", "Done! Save scene?", "Save", "Cancel"))
                 {
                     OnEditorUpdate(() =>
                     EditorSceneManager.SaveScene(scene));
                 }
             });
         }
References Juniper.ConfigurationManagement.ProjectConfiguration.Commit(), Juniper.ConfigurationManagement.JuniperConfigurationManager.config, Juniper.JuniperPlatform.Ensure(), Juniper.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), Juniper.Installable.InstallAll(), Juniper.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.ConfigurationManagement.JuniperConfigurationManager.OnEditorUpdate(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress().
Recompile()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile (bool advanceBuildStep, string nextDefinesString = null) inline static private
Definition at line 545 of file JuniperConfigurationManager.cs.
         {
             if (advanceBuildStep)
             {
                 ++BuildProgress;
             }
             var targetGroup = BuildPipeline.GetBuildTargetGroup(EditorUserBuildSettings.activeBuildTarget);
             var prog = PrepareBuildStep(1);
             var currentDefinesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);
             var currentDefines = FormatDefines(ref currentDefinesString);
             var nextDefines = FormatDefines(ref nextDefinesString);
             if (nextDefines.Matches(currentDefines))
             {
                 if (nextDefines.Contains(RECOMPILE_SLUG))
                 {
                     nextDefines.Remove(RECOMPILE_SLUG);
                 }
                 else
                 {
                     nextDefines.Add(RECOMPILE_SLUG);
                 }
             }
             nextDefines.RemoveAll(string.IsNullOrWhiteSpace);
             nextDefinesString = string.Join(";", nextDefines);
             PlayerSettings.SetScriptingDefineSymbolsForGroup(targetGroup, nextDefinesString);
             DelayedUpdate(prog, 30, () => Debug.LogWarning("Timeout!!!"));
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.ConfigurationManagement.JuniperConfigurationManager.DelayedUpdate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.FormatDefines(), Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal().
RecompilePlatformInternal()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal () inline static private
Definition at line 577 of file JuniperConfigurationManager.cs.
         {
             var newDefinesString = ThirdPartyDefines(NextConfiguration.TargetGroup);
             var newDefines = newDefinesString.Split(';').ToList();
             newDefines.MaybeAddRange(NextConfiguration.CompilerDefines);
             Recompile(false, string.Join(";", newDefines));
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.CompilerDefines, Juniper.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.ConfigurationManagement.PlatformConfiguration.TargetGroup, and Juniper.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines().
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu().
RefreshPackages()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages () inline static
Definition at line 627 of file JuniperConfigurationManager.cs.
         {
             WithProgress("Refreshing packages " + NextPlatform, prog =>
             {
                 var progs = prog.Split(5);
                 LastConfiguration.UninstallRawPackages(progs[0]);
                 var manifest = JObject.Parse(File.ReadAllText(MANIFEST_FILE));
                 var deps = manifest["dependencies"] as JObject;
                 if (deps == null)
                 {
                     deps = new JObject();
                     manifest.Add("dependencies", deps);
                 }
                 UnityPackage.Dependencies = deps;
                 LastConfiguration.UninstallUnityPackages(progs[1]);
                 NextConfiguration.InstallUnityPackages(progs[2]);
                 var txt = manifest.ToString(Formatting.Indented);
                 FileExt.WriteAllText(MANIFEST_FILE, txt);
                 NextConfiguration.InstallRawPackages(progs[3]);
                 NextConfiguration.Activate(progs[4]);
                 if (!NextConfiguration.SwitchTarget())
                 {
                     ++BuildProgress;
                     AssetDatabase.Refresh(ImportAssetOptions.ForceUpdate | ImportAssetOptions.ImportRecursive);
                     if (!EditorApplication.isCompiling)
                     {
                         ResumeBuild();
                     }
                 }
             });
         }
References Juniper.ConfigurationManagement.PlatformConfiguration.Activate(), Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, Juniper.ConfigurationManagement.UnityPackage.Dependencies, Juniper.ConfigurationManagement.PlatformConfiguration.InstallRawPackages(), Juniper.ConfigurationManagement.PlatformConfiguration.InstallUnityPackages(), Juniper.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration, Juniper.ConfigurationManagement.JuniperConfigurationManager.MANIFEST_FILE, Juniper.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration, Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform, Juniper.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild(), Juniper.ConfigurationManagement.PlatformConfiguration.SwitchTarget(), Juniper.ConfigurationManagement.PlatformConfiguration.UninstallRawPackages(), Juniper.ConfigurationManagement.PlatformConfiguration.UninstallUnityPackages(), Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress(), and System.IO.FileExt.WriteAllText().
ResumeBuild()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild () inline static private
Definition at line 601 of file JuniperConfigurationManager.cs.
         {
             if (BuildInProgress)
             {
                 STAGES[BuildProgress].Invoke();
             }
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress, Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, and Juniper.ConfigurationManagement.JuniperConfigurationManager.STAGES.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
SetAndroid_ARCore_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem () inline static
Definition at line 189 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidARCore;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_ARCore_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem_Validate () inline static
Definition at line 183 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidARCore);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Cardboard_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem () inline static
Definition at line 201 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidCardboard;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Cardboard_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem_Validate () inline static
Definition at line 195 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidCardboard);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Daydream_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem () inline static
Definition at line 213 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidDaydream;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Daydream_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem_Validate () inline static
Definition at line 207 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidDaydream);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem () inline static
Definition at line 177 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.Android;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem_Validate () inline static
Definition at line 171 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.Android);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_Oculus_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem () inline static
Definition at line 225 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidOculus;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_Oculus_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem_Validate () inline static
Definition at line 219 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidOculus);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetAndroid_ViveFocus_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem () inline static
Definition at line 237 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.AndroidViveFocus;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetAndroid_ViveFocus_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem_Validate () inline static
Definition at line 231 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.AndroidViveFocus);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_ARKit_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem () inline static
Definition at line 267 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOSARKit;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_ARKit_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem_Validate () inline static
Definition at line 261 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOSARKit);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_Cardboard_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem () inline static
Definition at line 279 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOSCardboard;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_Cardboard_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem_Validate () inline static
Definition at line 273 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOSCardboard);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetIOS_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem () inline static
Definition at line 255 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.IOS;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetIOS_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem_Validate () inline static
Definition at line 249 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.IOS);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetMagicLeap_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem () inline static
Definition at line 379 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.MagicLeap;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetMagicLeap_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem_Validate () inline static
Definition at line 373 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.MagicLeap);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem () inline static
Definition at line 297 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.Standalone;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem_Validate () inline static
Definition at line 291 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.Standalone);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_Oculus_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem () inline static
Definition at line 309 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.StandaloneOculus;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_Oculus_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem_Validate () inline static
Definition at line 303 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.StandaloneOculus);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetStandalone_SteamVR_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem () inline static
Definition at line 321 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.StandaloneSteamVR;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetStandalone_SteamVR_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem_Validate () inline static
Definition at line 315 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.StandaloneSteamVR);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_HoloLens_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem () inline static
Definition at line 363 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWPHoloLens;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_HoloLens_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem_Validate () inline static
Definition at line 357 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWPHoloLens);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem () inline static
Definition at line 339 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWP;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem_Validate () inline static
Definition at line 333 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWP);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
SetUWP_WindowsMR_MenuItem()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem () inline static
Definition at line 351 of file JuniperConfigurationManager.cs.
         {
             NextPlatform = PlatformTypes.UWPWindowsMR;
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform.
SetUWP_WindowsMR_MenuItem_Validate()
static bool Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem_Validate () inline static
Definition at line 345 of file JuniperConfigurationManager.cs.
         {
             return MenuCheck(PlatformTypes.UWPWindowsMR);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
StartBuild()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.StartBuild () inline static private
Definition at line 611 of file JuniperConfigurationManager.cs.
         {
             BuildProgress = 0;
             DeactivatePlatform();
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildProgress, and Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform().
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_ResetConfiguration().
ThirdPartyDefines()
static string Juniper.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines (BuildTargetGroup targetGroup) inline static private
Definition at line 151 of file JuniperConfigurationManager.cs.
         {
             var oldDefinesString = PlayerSettings.GetScriptingDefineSymbolsForGroup(targetGroup);
             var oldDefines = oldDefinesString.Split(';');
             var newDefines = oldDefines.Exclude(JUNIPER_DEFINES);
             return string.Join(";", newDefines);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.JUNIPER_DEFINES.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal().
Uninstall()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.Uninstall () inline static private
Definition at line 391 of file JuniperConfigurationManager.cs.
         {
             Installable.UninstallAll(GetInstallables);
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.GetInstallables(), and Juniper.Installable.UninstallAll().
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Install().
WithProgress()
static void Juniper.ConfigurationManagement.JuniperConfigurationManager.WithProgress (string prefix, Action< IProgressReceiver > act) inline static private
Definition at line 527 of file JuniperConfigurationManager.cs.
         {
             try
             {
                 var prog = PrepareBuildStep(0, prefix);
                 prog.SetProgress(0);
                 act(prog);
             }
             catch (OperationCanceledException)
             {
                 OnCancel();
             }
             catch (Exception exp)
             {
                 Debug.LogException(exp);
             }
         }
References Juniper.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep().
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu(), Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareScene(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
Member Data Documentation
ANDROID_MENU_NAME
const string Juniper.ConfigurationManagement.JuniperConfigurationManager.ANDROID_MENU_NAME = MENU_NAME + "Android/" private
Definition at line 163 of file JuniperConfigurationManager.cs.
config
readonly ProjectConfiguration Juniper.ConfigurationManagement.JuniperConfigurationManager.config static private
Definition at line 27 of file JuniperConfigurationManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareScene().
IOS_MENU_NAME
const string Juniper.ConfigurationManagement.JuniperConfigurationManager.IOS_MENU_NAME = MENU_NAME + "IOS/" private
Definition at line 246 of file JuniperConfigurationManager.cs.
LastPrefix
string Juniper.ConfigurationManagement.JuniperConfigurationManager.LastPrefix static private
Definition at line 516 of file JuniperConfigurationManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep().
MANIFEST_FILE
readonly string Juniper.ConfigurationManagement.JuniperConfigurationManager.MANIFEST_FILE = PathExt.FixPath("Packages/manifest.json") static private
Definition at line 609 of file JuniperConfigurationManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
MENU_NAME
const string Juniper.ConfigurationManagement.JuniperConfigurationManager.MENU_NAME = "Juniper/" private
Definition at line 25 of file JuniperConfigurationManager.cs.
OTHER_MENU_NAME
const string Juniper.ConfigurationManagement.JuniperConfigurationManager.OTHER_MENU_NAME = MENU_NAME + "Other/" private
Definition at line 388 of file JuniperConfigurationManager.cs.
RECOMPILE_SLUG
const string Juniper.ConfigurationManagement.JuniperConfigurationManager.RECOMPILE_SLUG = "RECOMPILE_SLUG" private
Definition at line 439 of file JuniperConfigurationManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.FormatDefines(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile().
STAGES
readonly Action [] Juniper.ConfigurationManagement.JuniperConfigurationManager.STAGES static private
Initial value:
=
        {
            DeactivatePlatform,
            RefreshPackages,
            ActivatePlatform,
            PrepareScene
        }
Definition at line 592 of file JuniperConfigurationManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
STANDALONE_MENU_NAME
const string Juniper.ConfigurationManagement.JuniperConfigurationManager.STANDALONE_MENU_NAME = MENU_NAME + "Standalone/" private
Definition at line 288 of file JuniperConfigurationManager.cs.
UWP_MENU_NAME
const string Juniper.ConfigurationManagement.JuniperConfigurationManager.UWP_MENU_NAME = MENU_NAME + "UWP/" private
Definition at line 330 of file JuniperConfigurationManager.cs.
Property Documentation
BuildInProgress
bool Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildInProgress static get private
Definition at line 73 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return 0 <= BuildProgress && BuildProgress < STAGES.Length;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_ResumeBuild_Validate(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild().
BuildProgress
int Juniper.ConfigurationManagement.JuniperConfigurationManager.BuildProgress static get set private
Definition at line 44 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.BuildStep;
             }
             set
             {
                 config.BuildStep = value;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.OnCancel(), Juniper.ConfigurationManagement.JuniperConfigurationManager.PrepareBuildStep(), Juniper.ConfigurationManagement.JuniperConfigurationManager.Recompile(), Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages(), Juniper.ConfigurationManagement.JuniperConfigurationManager.ResumeBuild(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.StartBuild().
CurrentPlatform
PlatformTypes Juniper.ConfigurationManagement.JuniperConfigurationManager.CurrentPlatform static get private
Definition at line 57 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return JuniperPlatform.CURRENT_PLATFORM;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.Config_PlatformChanged(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.MenuCheck().
DesiredPlatform
PlatformTypes Juniper.ConfigurationManagement.JuniperConfigurationManager.DesiredPlatform static get private
Definition at line 65 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.CurrentPlatform;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
JUNIPER_DEFINES
string [] Juniper.ConfigurationManagement.JuniperConfigurationManager.JUNIPER_DEFINES static get private
The DEFINE symbols that we use in this project. We need to filter them out of the whole set so we can add the right ones back in without deleting any that we don't control.
Definition at line 144 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return Platforms.Instance.AllCompilerDefines;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.ThirdPartyDefines().
LastConfiguration
PlatformConfiguration Juniper.ConfigurationManagement.JuniperConfigurationManager.LastConfiguration static get private
Definition at line 124 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return Platforms.Instance.PlatformDB.Get(CurrentPlatform);
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
NextConfiguration
PlatformConfiguration Juniper.ConfigurationManagement.JuniperConfigurationManager.NextConfiguration static get private
Definition at line 132 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return Platforms.Instance.PlatformDB.Get(NextPlatform);
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.DeactivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.RecompilePlatformInternal(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages().
NextPlatform
PlatformTypes Juniper.ConfigurationManagement.JuniperConfigurationManager.NextPlatform static get set private
Definition at line 89 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return config.NextPlatform;
             }
             set
             {
                 config.NextPlatform = value;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.ActivatePlatform(), Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager(), Juniper.ConfigurationManagement.JuniperConfigurationManager.Other_Recompile_Menu(), Juniper.ConfigurationManagement.JuniperConfigurationManager.RefreshPackages(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ARCore_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Cardboard_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Daydream_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_Oculus_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetAndroid_ViveFocus_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_ARKit_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_Cardboard_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetIOS_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetMagicLeap_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_Oculus_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetStandalone_SteamVR_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_HoloLens_MenuItem(), Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_MenuItem(), and Juniper.ConfigurationManagement.JuniperConfigurationManager.SetUWP_WindowsMR_MenuItem().
RebuildNeeded
bool Juniper.ConfigurationManagement.JuniperConfigurationManager.RebuildNeeded static get private
Definition at line 81 of file JuniperConfigurationManager.cs.
         {
             get
             {
                 return DesiredPlatform != CurrentPlatform && !BuildInProgress;
             }
         }
Referenced by Juniper.ConfigurationManagement.JuniperConfigurationManager.JuniperConfigurationManager().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Editor/Juniper/ConfigurationManagement/JuniperConfigurationManager.cs