Juniper: Juniper.Unity.Display.ARCoreDisplayManager Class Reference
Juniper.Unity.Display.ARCoreDisplayManager Class Reference
Public Member Functions
override void Install (bool reset)
override void Uninstall ()
override void Update ()
Updates the camera FOV according to game window dimensions, and moves the camera into position at the avatar height.
void StartXRDisplay ()
void StopXRDisplay ()
void DisableDisplay ()
void StartAR ()
void StopAR ()
void ToggleAR ()
virtual void Awake ()
virtual void Reinstall ()
void Reset ()
Public Attributes
Material ARBackgroundMaterial
On ARKit and ARCore systems, a special material for displaying the camera image needs to be configured. Vuforia does this on its own, and HoloLens has a clear display so it isn't needed.
bool enablePointCloud = true
On ARKit and ARCore, perform an image analysis algorithm that renders a point cloud of feature points.
Protected Attributes
JuniperPlatform jp
Properties
static Camera MainCamera [get]
virtual float DEFAULT_FOV [get]
Gets the field of view value that should be targeted for the running application.
float VerticalFieldOfView [get]
The camera field of view along the large screen axis in portrait mode, the narrow axis in landscape mode.
Private Attributes
bool isQuitting
On ARCore, this value is used to flag when the app is shutting down so we don't capture multiple errors that would cause multiple Toast messages to appear.
Detailed Description
Definition at line 10 of file ARCoreDisplayManager.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Display.AbstractDisplayManager.Awake () inline virtual inherited
Definition at line 215 of file AbstractDisplayManager.cs.
         {
             cam = GetComponent<Camera>();
             Install(false);
             lastSystem = jp.System;
             lastDisplayType = jp.DisplayType;
             lastARMode = jp.ARMode;
             lastOption = jp.Option;
             StartXRDisplay();
         }
References Juniper.Unity.JuniperPlatform.ARMode, Juniper.Unity.Display.AbstractDisplayManager.cam, Juniper.Unity.JuniperPlatform.DisplayType, Juniper.Unity.Display.AbstractDisplayManager.Install(), Juniper.Unity.Display.AbstractDisplayManager.jp, Juniper.Unity.Display.AbstractDisplayManager.lastARMode, Juniper.Unity.Display.AbstractDisplayManager.lastDisplayType, Juniper.Unity.Display.AbstractDisplayManager.lastOption, Juniper.Unity.Display.AbstractDisplayManager.lastSystem, Juniper.Unity.JuniperPlatform.Option, Juniper.Unity.Display.AbstractDisplayManager.StartXRDisplay(), and Juniper.Unity.JuniperPlatform.System.
DisableDisplay()
void Juniper.Unity.Display.AbstractDisplayManager.DisableDisplay () inline inherited
Definition at line 142 of file AbstractDisplayManager.cs.
         {
             ChangeDisplayType(DisplayTypes.None);
         }
References Juniper.Unity.Display.AbstractDisplayManager.ChangeDisplayType().
Install()
override void Juniper.Unity.Display.ARCoreDisplayManager.Install (bool reset) inline virtual
Reimplemented from Juniper.Unity.Display.AbstractDisplayManager.
Definition at line 18 of file ARCoreDisplayManager.cs.
         {
             reset &= Application.isEditor;
             base.Install(reset);
             this.WithLock(() =>
             {
                 var arCoreSession = this.EnsureComponent<ARCoreSession>().Value;
                 arCoreSession.SessionConfig = ScriptableObject.CreateInstance<ARCoreSessionConfig>();
                 arCoreSession.SessionConfig.MatchCameraFramerate = true;
                 var poseDriver = this.EnsureComponent<TrackedPoseDriver>().Value;
                 poseDriver.SetPoseSource(TrackedPoseDriver.DeviceType.GenericXRDevice, TrackedPoseDriver.TrackedPose.ColorCamera);
                 poseDriver.trackingType = TrackedPoseDriver.TrackingType.RotationAndPosition;
                 poseDriver.updateType = TrackedPoseDriver.UpdateType.BeforeRender;
                 poseDriver.UseRelativeTransform = true;
                 var bgRenderer = this.EnsureComponent<ARCoreBackgroundRenderer>().Value;
 #if UNITY_EDITOR
                 if (ARBackgroundMaterial == null || reset)
                 {
                     ARBackgroundMaterial = UnityEditor.AssetDatabase.LoadAssetAtPath<Material>(
                         System.IO.PathExt.FixPath(
                             "Assets/GoogleARCore/SDK/Materials/ARBackground.mat"));
                 }
 #endif
                 bgRenderer.BackgroundMaterial = ARBackgroundMaterial;
             });
         }
References Juniper.Unity.Display.AbstractPassthroughDisplayManager.ARBackgroundMaterial, and System.IO.PathExt.FixPath().
Reinstall()
virtual void Juniper.Unity.Display.AbstractDisplayManager.Reinstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 229 of file AbstractDisplayManager.cs.
         {
             Install(true);
         }
References Juniper.Unity.Display.AbstractDisplayManager.Install().
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Reset().
Reset()
void Juniper.Unity.Display.AbstractDisplayManager.Reset () inline inherited
Definition at line 236 of file AbstractDisplayManager.cs.
         {
             Reinstall();
         }
References Juniper.Unity.Display.AbstractDisplayManager.Reinstall().
StartAR()
void Juniper.Unity.Display.AbstractDisplayManager.StartAR () inline inherited
Definition at line 173 of file AbstractDisplayManager.cs.
         {
             ChangeARMode(jp.SupportedARMode);
         }
References Juniper.Unity.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Unity.Display.AbstractDisplayManager.jp, and Juniper.Unity.JuniperPlatform.SupportedARMode.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Unity.Display.AbstractDisplayManager.ToggleAR(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
StartXRDisplay()
void Juniper.Unity.Display.AbstractDisplayManager.StartXRDisplay () inline inherited
Definition at line 132 of file AbstractDisplayManager.cs.
         {
             ChangeDisplayType(jp.SupportedDisplayType);
         }
References Juniper.Unity.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Unity.Display.AbstractDisplayManager.jp, and Juniper.Unity.JuniperPlatform.SupportedDisplayType.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Awake().
StopAR()
void Juniper.Unity.Display.AbstractDisplayManager.StopAR () inline inherited
Definition at line 178 of file AbstractDisplayManager.cs.
         {
             ChangeARMode(AugmentedRealityTypes.None);
         }
References Juniper.Unity.Display.AbstractDisplayManager.ChangeARMode().
Referenced by Juniper.Unity.Display.AbstractDisplayManager.ToggleAR(), and Juniper.Unity.ImageTracking.AbstractTrackerKeeper.Update().
StopXRDisplay()
void Juniper.Unity.Display.AbstractDisplayManager.StopXRDisplay () inline inherited
Definition at line 137 of file AbstractDisplayManager.cs.
         {
             ChangeDisplayType(DisplayTypes.Monoscopic);
         }
References Juniper.Unity.Display.AbstractDisplayManager.ChangeDisplayType().
ToggleAR()
void Juniper.Unity.Display.AbstractDisplayManager.ToggleAR () inline inherited
Definition at line 183 of file AbstractDisplayManager.cs.
         {
             if (jp.ARMode == AugmentedRealityTypes.None)
             {
                 StartAR();
             }
             else
             {
                 StopAR();
             }
         }
References Juniper.Unity.JuniperPlatform.ARMode, Juniper.Unity.Display.AbstractDisplayManager.jp, Juniper.Unity.Display.AbstractDisplayManager.StartAR(), and Juniper.Unity.Display.AbstractDisplayManager.StopAR().
Uninstall()
override void Juniper.Unity.Display.ARCoreDisplayManager.Uninstall () inline virtual
Reimplemented from Juniper.Unity.Display.AbstractDisplayManager.
Definition at line 50 of file ARCoreDisplayManager.cs.
         {
             this.RemoveComponent<ARCoreBackgroundRenderer>();
             this.RemoveComponent<TrackedPoseDriver>();
             this.RemoveComponent<ARCoreSession>();
             base.Uninstall();
         }
Update()
override void Juniper.Unity.Display.ARCoreDisplayManager.Update () inline virtual
Updates the camera FOV according to game window dimensions, and moves the camera into position at the avatar height.
Reimplemented from Juniper.Unity.Display.AbstractDisplayManager.
Definition at line 59 of file ARCoreDisplayManager.cs.
         {
             base.Update();
             if (!isQuitting)
             {
                 // Quit if ARCore was unable to connect and give Unity some time for the toast to appear.
                 if (Session.Status == SessionStatus.ErrorPermissionNotGranted)
                 {
                     Device.ShowToastMessage("Camera permission is needed to run this application.");
                     isQuitting = true;
                     MasterSceneController.QuitApp();
                 }
                 else if (Session.Status.IsError())
                 {
                     Device.ShowToastMessage("ARCore encountered a problem connecting.  Please start the app again.");
                     isQuitting = true;
                     MasterSceneController.QuitApp();
                 }
             }
         }
References Juniper.Unity.Display.ARCoreDisplayManager.isQuitting, Juniper.Unity.MasterSceneController.QuitApp(), and UnityEngine.Android.Device.ShowToastMessage().
Member Data Documentation
ARBackgroundMaterial
Material Juniper.Unity.Display.AbstractPassthroughDisplayManager.ARBackgroundMaterial inherited
On ARKit and ARCore systems, a special material for displaying the camera image needs to be configured. Vuforia does this on its own, and HoloLens has a clear display so it isn't needed.
Definition at line 12 of file AbstractPassthroughDisplayManager.cs.
Referenced by Juniper.Unity.Display.ARCoreDisplayManager.Install().
enablePointCloud
bool Juniper.Unity.Display.AbstractPassthroughDisplayManager.enablePointCloud = true inherited
On ARKit and ARCore, perform an image analysis algorithm that renders a point cloud of feature points.
Definition at line 18 of file AbstractPassthroughDisplayManager.cs.
isQuitting
bool Juniper.Unity.Display.ARCoreDisplayManager.isQuitting private
On ARCore, this value is used to flag when the app is shutting down so we don't capture multiple errors that would cause multiple Toast messages to appear.
Definition at line 16 of file ARCoreDisplayManager.cs.
Referenced by Juniper.Unity.Display.ARCoreDisplayManager.Update().
jp
JuniperPlatform Juniper.Unity.Display.AbstractDisplayManager.jp protected inherited
Definition at line 22 of file AbstractDisplayManager.cs.
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Awake(), Juniper.Unity.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Unity.Display.AbstractDisplayManager.ChangeDisplayType(), Juniper.Unity.Display.AbstractDisplayManager.Install(), Juniper.Unity.Display.AbstractDisplayManager.StartAR(), Juniper.Unity.Display.AbstractDisplayManager.StartXRDisplay(), Juniper.Unity.Display.AbstractDisplayManager.ToggleAR(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
Property Documentation
DEFAULT_FOV
virtual float Juniper.Unity.Display.AbstractDisplayManager.DEFAULT_FOV get protected inherited
Gets the field of view value that should be targeted for the running application.
The default fov.
Definition at line 279 of file AbstractDisplayManager.cs.
         {
             get
             {
                 return MainCamera.fieldOfView;
             }
         }
MainCamera
Camera Juniper.Unity.Display.AbstractDisplayManager.MainCamera static get inherited
Definition at line 201 of file AbstractDisplayManager.cs.
         {
             get
             {
                 if (cam != null)
                 {
                     return cam;
                 }
                 else
                 {
                     return cam = ComponentExt.FindAny<Camera>(camera => camera.tag == "MainCamera");
                 }
             }
         }
Referenced by Juniper.Unity.Input.Pointers.Probe.AlignProbe(), Juniper.Unity.Widgets.FollowMainCamera.Awake(), Juniper.Unity.Widgets.Standoff.Awake(), Juniper.Unity.Widgets.Label.Awake(), Juniper.Unity.Animation.SpiralTransition.Awake(), Juniper.Unity.World.CompassRose.Awake(), Juniper.Unity.Audio.InteractionAudio.Awake(), Juniper.Unity.Widgets.AbstractValued.Awake(), Juniper.Unity.Display.AbstractDisplayManager.ChangeARMode(), Juniper.Unity.JuniperPlatform.Ensure(), Juniper.Unity.JuniperPlatform.Install(), Juniper.Unity.MasterSceneController.Install(), Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< KeyCode, HapticsType, TouchPointConfiguration >.InternalUpdate(), Juniper.Unity.Animation.FadeTransition.OnEntered(), Juniper.Unity.Animation.FadeTransition.OnExiting(), Juniper.Unity.ImageTracking.TrackableFoundEventHandler.SafetyCheck(), Juniper.Unity.Input.Pointers.Probe.Start(), Juniper.Unity.Animation.SpiralTransition.Update(), Juniper.Unity.Widgets.AttentionDirector.Update(), and Juniper.Unity.Display.AbstractDisplayManager.Update().
VerticalFieldOfView
float Juniper.Unity.Display.AbstractDisplayManager.VerticalFieldOfView get inherited
The camera field of view along the large screen axis in portrait mode, the narrow axis in landscape mode.
The vertical field of view.
Definition at line 292 of file AbstractDisplayManager.cs.
         {
             get
             {
                 if (Screen.width < Screen.height)
                 {
                     var tan = Mathf.Tan(Units.Degrees.Radians(DEFAULT_FOV / 2));
                     var max = Mathf.Max(Screen.width, Screen.height);
                     var min = Mathf.Min(Screen.width, Screen.height);
                     float aspect;
                     if (Screen.height < Screen.width)
                     {
                         aspect = min / max;
                     }
                     else
                     {
                         aspect = max / min;
                     }
                     return 2 * Units.Radians.Degrees(Mathf.Atan(tan * aspect));
                 }
                 else
                 {
                     return DEFAULT_FOV;
                 }
             }
         }
Referenced by Juniper.Unity.Display.AbstractDisplayManager.Update().
The documentation for this class was generated from the following file:
C:/Users/smcbeth/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/ARCore/ARCoreDisplayManager.cs