Juniper: Juniper.XRSystem Class Reference
Juniper.XRSystem Class Reference
Public Member Functions
void StartXRDisplay ()
void StopXRDisplay ()
void DisableDisplay ()
void StartAR ()
void StopAR ()
void ToggleAR ()
void Awake ()
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
virtual void Reinstall ()
void Reset ()
void OnValidate ()
void Install (bool reset)
void Uninstall ()
void Update ()
Determines which XR Subsystem needs to be started for the current set of configuration parameters.
Static Public Member Functions
static string SupportedXRDevice (DisplayTypes displayType)
static XRSystem Ensure ()
Public Attributes
PlatformTypes CurrentPlatform
SystemTypes System
DisplayTypes DisplayType
DisplayTypes SupportedDisplayType
AugmentedRealityTypes ARMode
AugmentedRealityTypes SupportedARMode
Options Option
Static Public Attributes
static readonly PlatformTypes CURRENT_PLATFORM
static bool VRPlatformHasPassthrough
static bool IsARCapablePlatform
Private Member Functions
void ChangeDisplayType (DisplayTypes displayType)
void ChangeARMode (AugmentedRealityTypes mode)
Private Attributes
SystemTypes lastSystem
DisplayTypes lastDisplayType
AugmentedRealityTypes lastARMode
Options lastOption
Detailed Description
Definition at line 18 of file XRSystem.cs.
Member Function Documentation
Awake()
void Juniper.XRSystem.Awake () inline
Checks to see if there is no MasterSceneController, or if this component is in the same scene as the master scene. If not, this component is destroyed and processing stops. If so, continues on to request system- specific permissions and sets up the interaction audio system, the world anchor store, the event system, a standard input module, camera extensions, and the XR subsystem.
Definition at line 305 of file XRSystem.cs.
         {
             var scenes = ComponentExt.FindAny<MasterSceneController>();
             if (scenes != null && scenes.gameObject.scene != gameObject.scene)
             {
                 gameObject.Destroy();
             }
             else
             {
                 Install(false);
                 lastSystem = System;
                 lastDisplayType = DisplayType;
                 lastARMode = ARMode;
                 lastOption = Option;
                 StartXRDisplay();
             }
         }
References Juniper.XRSystem.ARMode, Juniper.XRSystem.DisplayType, Juniper.XRSystem.Install(), Juniper.XRSystem.lastARMode, Juniper.XRSystem.lastDisplayType, Juniper.XRSystem.lastOption, Juniper.XRSystem.lastSystem, Juniper.XRSystem.Option, Juniper.XRSystem.StartXRDisplay(), and Juniper.XRSystem.System.
ChangeARMode()
void Juniper.XRSystem.ChangeARMode (AugmentedRealityTypes mode) inline private
Definition at line 227 of file XRSystem.cs.
         {
             try
             {
                 CameraExtensions.MainCamera.enabled = DisplayType != DisplayTypes.None;
                 ARMode = mode;
                 if (ARMode == AugmentedRealityTypes.None)
                 {
                     CameraExtensions.MainCamera.clearFlags = CameraClearFlags.Skybox;
                 }
                 else
                 {
                     CameraExtensions.MainCamera.clearFlags = CameraClearFlags.Color;
                     CameraExtensions.MainCamera.backgroundColor = ColorExt.TransparentBlack;
                 }
                 lastARMode = ARMode;
             }
             catch (Exception exp)
             {
                 Debug.LogError($"Could not AR mode from {lastARMode} to {ARMode}. Reason: {exp.Message}");
                 ARMode = lastARMode;
             }
         }
References Juniper.XRSystem.ARMode, Juniper.XRSystem.DisplayType, Juniper.XRSystem.lastARMode, Juniper.CameraExtensions.MainCamera, and UnityEngine.ColorExt.TransparentBlack.
ChangeDisplayType()
void Juniper.XRSystem.ChangeDisplayType (DisplayTypes displayType) inline private
Definition at line 198 of file XRSystem.cs.
         {
             if (displayType != DisplayType)
             {
                 DisplayType = displayType;
                 if (IsARCapablePlatform && DisplayType == DisplayTypes.Monoscopic)
                 {
                     lastDisplayType = DisplayType;
                     StartAR();
                 }
                 else
                 {
                     Debug.LogWarning("Juniper: Application was not built with XR support.");
                     DisplayType = lastDisplayType;
                 }
             }
         }
References Juniper.XRSystem.DisplayType, Juniper.XRSystem.IsARCapablePlatform, Juniper.XRSystem.lastDisplayType, and Juniper.XRSystem.StartAR().
DisableDisplay()
void Juniper.XRSystem.DisableDisplay ()
Ensure()
static XRSystem Juniper.XRSystem.Ensure () inline static
Definition at line 271 of file XRSystem.cs.
         {
             var head = CameraExtensions.MainCamera?.transform;
             if (head == null)
             {
                 head = new GameObject().AddComponent<Camera>().transform;
                 head.gameObject.tag = "MainCamera";
             }
             head.gameObject.name = "Head (Camera)";
             var stage = head.parent;
             if (stage == null)
             {
                 stage = new GameObject("Stage").transform;
                 head.Reparent(stage);
             }
             var userRig = stage.parent;
             if (userRig == null)
             {
                 userRig = new GameObject("UserRig").transform;
                 stage.Reparent(userRig);
             }
             return userRig.EnsureComponent<XRSystem>();
         }
References Juniper.CameraExtensions.MainCamera.
Referenced by Juniper.XR.CustomEditors.XRSystemEditor.Install().
Install()
void Juniper.XRSystem.Install (bool reset) inline
Implements Juniper.IInstallable.
Definition at line 344 of file XRSystem.cs.
         {
             reset &= Application.isEditor;
 #if UNITY_EDITOR
             OnValidate();
 #endif
             this.EnsureComponent<EventSystem>();
             this.EnsureComponent<UnifiedInputModule>();
             this.EnsureComponent<AnchorStore>();
             this.EnsureComponent<InteractionAudio>();
             this.EnsureComponent<MasterSceneController>();
             this.EnsureComponent<PermissionHandler>();
             CameraExtensions.MainCamera.transform.parent.EnsureComponent<StageExtensions>();
             CameraExtensions.MainCamera.EnsureComponent<CameraExtensions>();
         }
References Juniper.CameraExtensions.MainCamera, and Juniper.XRSystem.OnValidate().
Referenced by Juniper.XRSystem.Awake().
OnValidate()
void Juniper.XRSystem.OnValidate () inline
Definition at line 332 of file XRSystem.cs.
         {
             CurrentPlatform = CURRENT_PLATFORM;
             System = Platform.GetSystem(CURRENT_PLATFORM);
             SupportedDisplayType = Platform.GetDisplayType(CURRENT_PLATFORM);
             SupportedARMode = Platform.GetARType(CURRENT_PLATFORM);
             Option = Platform.GetOption(CURRENT_PLATFORM);
             DisplayType = DisplayTypes.Monoscopic;
             ARMode = AugmentedRealityTypes.None;
         }
References Juniper.XRSystem.ARMode, Juniper.XRSystem.CURRENT_PLATFORM, Juniper.XRSystem.CurrentPlatform, Juniper.XRSystem.DisplayType, Juniper.Platform.GetARType(), Juniper.Platform.GetDisplayType(), Juniper.Platform.GetOption(), Juniper.Platform.GetSystem(), Juniper.XRSystem.Option, Juniper.XRSystem.SupportedARMode, and Juniper.XRSystem.SupportedDisplayType.
Referenced by Juniper.XRSystem.Install().
Reinstall()
virtual void Juniper.XRSystem.Reinstall () virtual
Implements Juniper.IInstallable.
Reset()
void Juniper.XRSystem.Reset ()
StartAR()
void Juniper.XRSystem.StartAR ()
Referenced by Juniper.XRSystem.ChangeDisplayType(), Juniper.XRSystem.ToggleAR(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
StartXRDisplay()
void Juniper.XRSystem.StartXRDisplay ()
Referenced by Juniper.XRSystem.Awake().
StopAR()
void Juniper.XRSystem.StopAR ()
Referenced by Juniper.XRSystem.ToggleAR(), and Juniper.ImageTracking.AbstractTrackerKeeper.Update().
StopXRDisplay()
void Juniper.XRSystem.StopXRDisplay ()
SupportedXRDevice()
static string Juniper.XRSystem.SupportedXRDevice (DisplayTypes displayType) inline static
Definition at line 86 of file XRSystem.cs.
         {
             if (displayType == DisplayTypes.Stereo)
             {
                 if (CURRENT_PLATFORM == PlatformTypes.AndroidDaydream)
                 {
                     return "daydream";
                 }
                 else if (CURRENT_PLATFORM == PlatformTypes.AndroidOculus
                     || CURRENT_PLATFORM == PlatformTypes.StandaloneOculus)
                 {
                     return "oculus";
                 }
                 else if (CURRENT_PLATFORM == PlatformTypes.UWPHoloLens
                     || CURRENT_PLATFORM == PlatformTypes.UWPWindowsMR)
                 {
                     return "windowsmr";
                 }
                 else if (CURRENT_PLATFORM == PlatformTypes.MagicLeap)
                 {
                     return "Lumin";
                 }
                 else if (CURRENT_PLATFORM == PlatformTypes.StandaloneSteamVR)
                 {
                     return "openvr";
                 }
                 else if (CURRENT_PLATFORM == PlatformTypes.AndroidCardboard
                     || CURRENT_PLATFORM == PlatformTypes.IOSCardboard)
                 {
                     return "cardboard";
                 }
             }
             return "None";
         }
References Juniper.XRSystem.CURRENT_PLATFORM.
ToggleAR()
void Juniper.XRSystem.ToggleAR () inline
Definition at line 259 of file XRSystem.cs.
         {
             if (ARMode == AugmentedRealityTypes.None)
             {
                 StartAR();
             }
             else
             {
                 StopAR();
             }
         }
References Juniper.XRSystem.ARMode, Juniper.XRSystem.StartAR(), and Juniper.XRSystem.StopAR().
Uninstall()
void Juniper.XRSystem.Uninstall () inline
Implements Juniper.IInstallable.
Definition at line 363 of file XRSystem.cs.
 { }
Update()
void Juniper.XRSystem.Update () inline
Determines which XR Subsystem needs to be started for the current set of configuration parameters.
Definition at line 368 of file XRSystem.cs.
         {
             if (CurrentPlatform != CURRENT_PLATFORM)
             {
                 Debug.LogWarning($"Cannot change {nameof(Platform)} directly. Use the Juniper menu in the Unity Editor.");
                 CurrentPlatform = CURRENT_PLATFORM;
             }
             if (System != lastSystem)
             {
                 Debug.LogWarning($"Cannot change {nameof(System)} directly. Use the Juniper menu in the Unity Editor.");
                 System = lastSystem;
             }
             if (DisplayType != lastDisplayType)
             {
                 Debug.LogWarning($"Cannot change {nameof(DisplayType)} directly. Use the {nameof(StartXRDisplay)} method.");
                 DisplayType = lastDisplayType;
             }
             if (ARMode != lastARMode)
             {
                 Debug.LogWarning($"Cannot change {nameof(ARMode)} directly. Use the {nameof(StartAR)} method.");
                 ARMode = lastARMode;
             }
             if (Option != lastOption)
             {
                 Debug.LogWarning($"Cannot change {nameof(Option)} directly. Use the Juniper menu in the Unity Editor.");
                 Option = lastOption;
             }
         }
References Juniper.XRSystem.ARMode, Juniper.XRSystem.CURRENT_PLATFORM, Juniper.XRSystem.CurrentPlatform, Juniper.XRSystem.DisplayType, Juniper.XRSystem.lastARMode, Juniper.XRSystem.lastDisplayType, Juniper.XRSystem.lastOption, Juniper.XRSystem.lastSystem, and Juniper.XRSystem.Option.
Member Data Documentation
ARMode
AugmentedRealityTypes Juniper.XRSystem.ARMode
Definition at line 139 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake(), Juniper.XRSystem.ChangeARMode(), Juniper.Animation.FadeTransition.OnEntered(), Juniper.Animation.FadeTransition.OnExiting(), Juniper.XRSystem.OnValidate(), Juniper.XRSystem.ToggleAR(), and Juniper.XRSystem.Update().
CURRENT_PLATFORM
readonly PlatformTypes Juniper.XRSystem.CURRENT_PLATFORM static
Initial value:
=
            PlatformTypes.AndroidARCore
Definition at line 20 of file XRSystem.cs.
Referenced by Juniper.XRSystem.OnValidate(), Juniper.XRSystem.SupportedXRDevice(), and Juniper.XRSystem.Update().
CurrentPlatform
PlatformTypes Juniper.XRSystem.CurrentPlatform
Definition at line 123 of file XRSystem.cs.
Referenced by Juniper.XRSystem.OnValidate(), and Juniper.XRSystem.Update().
DisplayType
DisplayTypes Juniper.XRSystem.DisplayType
Definition at line 131 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake(), Juniper.XRSystem.ChangeARMode(), Juniper.XRSystem.ChangeDisplayType(), Juniper.XRSystem.OnValidate(), and Juniper.XRSystem.Update().
IsARCapablePlatform
bool Juniper.XRSystem.IsARCapablePlatform static
Initial value:
=>
            CURRENT_PLATFORM == PlatformTypes.UWP
                || CURRENT_PLATFORM == PlatformTypes.IOS
                || CURRENT_PLATFORM == PlatformTypes.IOSARKit
                || CURRENT_PLATFORM == PlatformTypes.Android
                || CURRENT_PLATFORM == PlatformTypes.AndroidARCore
                || CURRENT_PLATFORM == PlatformTypes.MagicLeap
                || CURRENT_PLATFORM == PlatformTypes.UWPHoloLens
Definition at line 77 of file XRSystem.cs.
Referenced by Juniper.XRSystem.ChangeDisplayType().
lastARMode
AugmentedRealityTypes Juniper.XRSystem.lastARMode private
Definition at line 141 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake(), Juniper.XRSystem.ChangeARMode(), and Juniper.XRSystem.Update().
lastDisplayType
DisplayTypes Juniper.XRSystem.lastDisplayType private
Definition at line 133 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake(), Juniper.XRSystem.ChangeDisplayType(), and Juniper.XRSystem.Update().
lastOption
Options Juniper.XRSystem.lastOption private
Definition at line 149 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake(), and Juniper.XRSystem.Update().
lastSystem
SystemTypes Juniper.XRSystem.lastSystem private
Definition at line 128 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake(), and Juniper.XRSystem.Update().
Option
Options Juniper.XRSystem.Option
Definition at line 147 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake(), Juniper.XRSystem.OnValidate(), and Juniper.XRSystem.Update().
SupportedARMode
AugmentedRealityTypes Juniper.XRSystem.SupportedARMode
Definition at line 144 of file XRSystem.cs.
Referenced by Juniper.XRSystem.OnValidate().
SupportedDisplayType
DisplayTypes Juniper.XRSystem.SupportedDisplayType
Definition at line 136 of file XRSystem.cs.
Referenced by Juniper.XRSystem.OnValidate().
System
SystemTypes Juniper.XRSystem.System
Definition at line 126 of file XRSystem.cs.
Referenced by Juniper.XRSystem.Awake().
VRPlatformHasPassthrough
bool Juniper.XRSystem.VRPlatformHasPassthrough static
Initial value:
=>
            CURRENT_PLATFORM == PlatformTypes.AndroidDaydream
                || CURRENT_PLATFORM == PlatformTypes.AndroidViveFocus
                || CURRENT_PLATFORM == PlatformTypes.StandaloneSteamVR
                || CURRENT_PLATFORM == PlatformTypes.UWPWindowsMR
Definition at line 71 of file XRSystem.cs.
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/XRSystem.cs