Juniper: Juniper.MediaType.Text Class Reference
Juniper.MediaType.Text Class Reference
Public Member Functions
override bool Matches (string fileName)
bool Matches (FileInfo file)
string AddExtension (string fileName)
bool Equals (string other)
override bool Equals (object obj)
bool Equals (MediaType other)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static MediaType Parse (string value)
static IReadOnlyCollection< MediaType > ParseAll (string[] acceptTypes)
static bool TryParse (string value, out MediaType type)
static IReadOnlyList< MediaType > GuessByFileName (string fileName)
static IReadOnlyList< MediaType > GuessByFile (FileInfo file)
static MediaType Lookup (string value)
static ContentReference operator+ (string cacheID, MediaType contentType)
static implicit operator string (MediaType mediaType)
static bool operator== (MediaType left, MediaType right)
static bool operator== (MediaType left, string right)
static bool operator== (string left, MediaType right)
static bool operator != (MediaType left, MediaType right)
static bool operator != (MediaType left, string right)
static bool operator != (string left, MediaType right)
Static Public Attributes
static readonly Text AnyText = new Text("*")
static readonly Text Cache_Manifest = new Text("cache-manifest", new string[] { "appcache" })
static readonly Text Calendar = new Text("calendar", new string[] { "ics", "ifb" })
static readonly Text Css = new Text("css", new string[] { "css" })
static readonly Text Csv = new Text("csv", new string[] { "csv" })
static readonly Text Csv_Schema = new Text("csv-schema")
static readonly Text Directory = new Text("directory")
static readonly Text Dns = new Text("dns")
static readonly Text Ecmascript = new Text("ecmascript")
static readonly Text Encaprtp = new Text("encaprtp")
static readonly Text Enriched = new Text("enriched")
static readonly Text Example = new Text("example")
static readonly Text Flexfec = new Text("flexfec")
static readonly Text Fwdred = new Text("fwdred")
static readonly Text Grammar_Ref_List = new Text("grammar-ref-list")
static readonly Text Html = new Text("html", new string[] { "html", "htm" })
static readonly Text Javascript = new Text("javascript")
static readonly Text Jcr_Cnd = new Text("jcr-cnd")
static readonly Text Markdown = new Text("markdown")
static readonly Text Mizar = new Text("mizar")
static readonly Text N3 = new Text("n3", new string[] { "n3" })
static readonly Text Parameters = new Text("parameters")
static readonly Text Parityfec = new Text("parityfec")
static readonly Text Plain = new Text("plain", new string[] { "txt", "text", "conf", "def", "list", "log", "in" })
static readonly Text Provenance_Notation = new Text("provenance-notation")
static readonly Text PrsFallensteinRst = new Text("prs.fallenstein.rst")
static readonly Text PrsLinesTag = new Text("prs.lines.tag", new string[] { "dsc" })
static readonly Text PrsPropLogic = new Text("prs.prop.logic")
static readonly Text Raptorfec = new Text("raptorfec")
static readonly Text RED = new Text("red")
static readonly Text Rfc822_Headers = new Text("rfc822-headers")
static readonly Text Richtext = new Text("richtext", new string[] { "rtx" })
static readonly Text Rtf = new Text("rtf")
static readonly Text Rtp_Enc_Aescm128 = new Text("rtp-enc-aescm128")
static readonly Text Rtploopback = new Text("rtploopback")
static readonly Text Rtx = new Text("rtx")
static readonly Text Sgml = new Text("sgml", new string[] { "sgml", "sgm" })
static readonly Text Strings = new Text("strings")
static readonly Text T140 = new Text("t140")
static readonly Text Tab_Separated_Values = new Text("tab-separated-values", new string[] { "tsv" })
static readonly Text Troff = new Text("troff", new string[] { "t", "tr", "roff", "man", "me", "ms" })
static readonly Text Turtle = new Text("turtle", new string[] { "ttl" })
static readonly Text Ulpfec = new Text("ulpfec")
static readonly Text Uri_List = new Text("uri-list", new string[] { "uri", "uris", "urls" })
static readonly Text Vcard = new Text("vcard", new string[] { "vcard" })
static readonly Text Vendor1d_Interleaved_Parityfec = new Text("1d-interleaved-parityfec")
static readonly Text VendorA = new Text("vnd.a")
static readonly Text VendorAbc = new Text("vnd.abc")
static readonly Text VendorAscii_Art = new Text("vnd.ascii-art")
static readonly Text VendorCurl = new Text("vnd.curl", new string[] { "curl" })
static readonly Text VendorCurlDcurl = new Text("vnd.curl.dcurl", new string[] { "dcurl" })
static readonly Text VendorCurlMcurl = new Text("vnd.curl.mcurl", new string[] { "mcurl" })
static readonly Text VendorCurlScurl = new Text("vnd.curl.scurl", new string[] { "scurl" })
static readonly Text VendorDebianCopyright = new Text("vnd.debian.copyright")
static readonly Text VendorDMClientScript = new Text("vnd.dmclientscript")
static readonly Text VendorDvbSubtitle = new Text("vnd.dvb.subtitle", new string[] { "sub" })
static readonly Text VendorEsmertecTheme_Descriptor = new Text("vnd.esmertec.theme-descriptor")
static readonly Text VendorFiclabFlt = new Text("vnd.ficlab.flt")
static readonly Text VendorFly = new Text("vnd.fly", new string[] { "fly" })
static readonly Text VendorFmiFlexstor = new Text("vnd.fmi.flexstor", new string[] { "flx" })
static readonly Text VendorGml = new Text("vnd.gml")
static readonly Text VendorGraphviz = new Text("vnd.graphviz", new string[] { "gv" })
static readonly Text VendorHgl = new Text("vnd.hgl")
static readonly Text VendorIn3d3dml = new Text("vnd.in3d.3dml", new string[] { "3dml" })
static readonly Text VendorIn3dSpot = new Text("vnd.in3d.spot", new string[] { "spot" })
static readonly Text VendorIPTCNewsML = new Text("vnd.iptc.newsml")
static readonly Text VendorIPTCNITF = new Text("vnd.iptc.nitf")
static readonly Text VendorLatex_Z = new Text("vnd.latex-z")
static readonly Text VendorMotorolaReflex = new Text("vnd.motorola.reflex")
static readonly Text VendorMs_Mediapackage = new Text("vnd.ms-mediapackage")
static readonly Text VendorNet2phoneCommcenterCommand = new Text("vnd.net2phone.commcenter.command")
static readonly Text VendorRadisysMsml_Basic_Layout = new Text("vnd.radisys.msml-basic-layout")
static readonly Text VendorSenxWarpscript = new Text("vnd.senx.warpscript")
static readonly Text VendorSiUricatalogue = new Text("vnd.si.uricatalogue")
static readonly Text VendorSosi = new Text("vnd.sosi")
static readonly Text VendorSunJ2meApp_Descriptor = new Text("vnd.sun.j2me.app-descriptor", new string[] { "jad" })
static readonly Text VendorTrolltechLinguist = new Text("vnd.trolltech.linguist")
static readonly Text VendorWapSi = new Text("vnd.wap.si")
static readonly Text VendorWapSl = new Text("vnd.wap.sl")
static readonly Text VendorWapWml = new Text("vnd.wap.wml", new string[] { "wml" })
static readonly Text VendorWapWmlscript = new Text("vnd.wap.wmlscript", new string[] { "wmls" })
static readonly Text Vtt = new Text("vtt")
static readonly Text X_Asm = new Text("x-asm", new string[] { "s", "asm" })
static readonly Text X_C = new Text("x-c", new string[] { "c", "cc", "cxx", "cpp", "h", "hh", "dic" })
static readonly Text X_Fortran = new Text("x-fortran", new string[] { "f", "for", "f77", "f90" })
static readonly Text X_Java_Source = new Text("x-java-source", new string[] { "java" })
static readonly Text X_Nfo = new Text("x-nfo", new string[] { "nfo" })
static readonly Text X_Opml = new Text("x-opml", new string[] { "opml" })
static readonly Text X_Pascal = new Text("x-pascal", new string[] { "p", "pas" })
static readonly Text X_Setext = new Text("x-setext", new string[] { "etx" })
static readonly Text X_Sfv = new Text("x-sfv", new string[] { "sfv" })
static readonly Text X_Uuencode = new Text("x-uuencode", new string[] { "uu" })
static readonly Text X_Vcalendar = new Text("x-vcalendar", new string[] { "vcs" })
static readonly Text X_Vcard = new Text("x-vcard", new string[] { "vcf" })
static readonly Text Xml = new Text("xml")
static readonly Text Xml_External_Parsed_Entity = new Text("xml-external-parsed-entity")
static new readonly Text [] Values
static readonly MediaType Any = new MediaType("*/*")
static readonly IReadOnlyCollection< MediaType > All = new MediaType[] { Any }
Properties
string Value [get]
string TypeName [get]
string SubTypeName [get]
float Weight [get]
ReadOnlyCollection< string > Extensions [get]
string PrimaryExtension [get]
Private Member Functions
Text (string value, string[] extensions)
Text (string value)
Detailed Description
Definition at line 7 of file Text.cs.
Constructor & Destructor Documentation
Text() [1/2]
Juniper.MediaType.Text.Text (string value, string [] extensions) inline private
Definition at line 9 of file Text.cs.
 : base("text/" + value, extensions) { }
Text() [2/2]
Juniper.MediaType.Text.Text (string value) inline private
Definition at line 11 of file Text.cs.
 : this(value, null) { }
Member Function Documentation
AddExtension()
string Juniper.MediaType.AddExtension (string fileName) inline inherited
Definition at line 310 of file MediaType.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (PrimaryExtension is object)
             {
                 var currentExtension = PathExt.GetShortExtension(fileName);
                 if (Extensions.IndexOf(currentExtension) == -1)
                 {
                     fileName += "." + PrimaryExtension;
                 }
             }
             return fileName;
         }
References Juniper.MediaType.Extensions, System.IO.PathExt.GetShortExtension(), and Juniper.MediaType.PrimaryExtension.
Referenced by Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), and Juniper.IO.ContentReference.operator string().
Equals() [1/3]
bool Juniper.MediaType.Equals (string other) inline inherited
Definition at line 329 of file MediaType.cs.
         {
             return TryParse(other, out var type)
                 && Equals(type);
         }
References Juniper.MediaType.TryParse().
Referenced by Juniper.MediaType.Equals().
Equals() [2/3]
override bool Juniper.MediaType.Equals (object obj) inline inherited
Definition at line 335 of file MediaType.cs.
         {
             return (obj is MediaType type && Equals(type))
                 || (obj is string str && Equals(str));
         }
References Juniper.MediaType.Equals().
Equals() [3/3]
bool Juniper.MediaType.Equals (MediaType other) inline inherited
Definition at line 341 of file MediaType.cs.
         {
             return other is object
                 && (TypeName == "*"
                     || other.TypeName == "*"
                     || TypeName == other.TypeName)
                 && (SubTypeName == "*"
                     || other.SubTypeName == "*"
                     || SubTypeName == other.SubTypeName);
         }
References Juniper.MediaType.SubTypeName, and Juniper.MediaType.TypeName.
GetHashCode()
override int Juniper.MediaType.GetHashCode () inline inherited
Definition at line 397 of file MediaType.cs.
         {
             var hashCode = -1006577490;
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(TypeName);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(SubTypeName);
             hashCode = (hashCode * -1521134295) + Weight.GetHashCode();
             hashCode = (hashCode * -1521134295) + EqualityComparer<ReadOnlyCollection<string>>.Default.GetHashCode(Extensions);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(PrimaryExtension);
             return hashCode;
         }
References Juniper.MediaType.Extensions, Juniper.MediaType.PrimaryExtension, Juniper.MediaType.SubTypeName, Juniper.MediaType.TypeName, and Juniper.MediaType.Weight.
GuessByFile()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFile (FileInfo file) inline static inherited
Definition at line 155 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return GuessByFileName(file.Name);
         }
References Juniper.MediaType.GuessByFileName().
Referenced by Juniper.HTTP.Server.HttpListenerResponseExt.SendFileAsync().
GuessByFileName()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFileName (string fileName) inline static inherited
Definition at line 144 of file MediaType.cs.
         {
             if (string.IsNullOrEmpty(fileName))
             {
                 throw new ArgumentException("Must provide a valid fileName", nameof(fileName));
             }
             var ext = Path.GetExtension(fileName);
             return GuessByExtension(ref ext);
         }
References Juniper.MediaType.GuessByExtension().
Referenced by Juniper.MediaType.GuessByFile(), and Juniper.MediaType.Matches().
Lookup()
static MediaType Juniper.MediaType.Lookup (string value) inline static inherited
Definition at line 165 of file MediaType.cs.
         {
             // Trim off the weight, if one exists
             var parts = value.SplitX(';');
             if (parts.Length > 0)
             {
                 value = parts[0];
             }
             if (byValue.ContainsKey(value))
             {
                 return byValue[value];
             }
             var name = Array.Find(parts, p => p.Length > 0);
             if (string.IsNullOrEmpty(name))
             {
                 return Lookup("unknown/unknown");
             }
             else
             {
                 return new Unknown(name);
             }
         }
References Juniper.MediaType.byValue.
Matches() [1/2]
override bool Juniper.MediaType.Text.Matches (string fileName) inline virtual
Reimplemented from Juniper.MediaType.
Definition at line 15 of file Text.cs.
             {
                 if (ReferenceEquals(this, AnyText))
                 {
                     return Values.Any(x => x.Matches(fileName));
                 }
                 else
                 {
                     return base.Matches(fileName);
                 }
             }
References Juniper.MediaType.Any, Juniper.MediaType.Text.AnyText, Juniper.MediaType.Matches(), and Juniper.MediaType.Text.Values.
Matches() [2/2]
bool Juniper.MediaType.Matches (FileInfo file) inline inherited
Definition at line 300 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return Matches(file.Name);
         }
References Juniper.MediaType.Matches().
operator !=() [1/3]
static bool Juniper.MediaType.operator != (MediaType left, MediaType right) inline static inherited
Definition at line 358 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [2/3]
static bool Juniper.MediaType.operator != (MediaType left, string right) inline static inherited
Definition at line 369 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [3/3]
static bool Juniper.MediaType.operator != (string left, MediaType right) inline static inherited
Definition at line 380 of file MediaType.cs.
         {
             return !(left == right);
         }
operator string()
static implicit Juniper.MediaType.operator string (MediaType mediaType) inline static inherited
Definition at line 196 of file MediaType.cs.
         {
             return mediaType?.ToString();
         }
operator+()
static ContentReference Juniper.MediaType.operator+ (string cacheID, MediaType contentType) inline static inherited
Definition at line 191 of file MediaType.cs.
         {
             return new ContentReference(cacheID, contentType);
         }
operator==() [1/3]
static bool Juniper.MediaType.operator== (MediaType left, MediaType right) inline static inherited
Definition at line 352 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [2/3]
static bool Juniper.MediaType.operator== (MediaType left, string right) inline static inherited
Definition at line 363 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [3/3]
static bool Juniper.MediaType.operator== (string left, MediaType right) inline static inherited
Definition at line 374 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (right is object && right.Equals(left));
         }
Parse()
static MediaType Juniper.MediaType.Parse (string value) inline static inherited
Definition at line 40 of file MediaType.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             if (TryParse(value, out var type))
             {
                 return type;
             }
             else
             {
                 throw new ArgumentException($"Type value does not match expected pattern {TYPE_PATTERN.ToString()}", nameof(value));
             }
         }
References Juniper.MediaType.TryParse().
ParseAll()
static IReadOnlyCollection<MediaType> Juniper.MediaType.ParseAll (string [] acceptTypes) inline static inherited
Definition at line 57 of file MediaType.cs.
         {
             if (acceptTypes is null || acceptTypes.Length == 0)
             {
                 return All;
             }
             else
             {
                 return InternalParseAll(acceptTypes).ToArray();
             }
         }
References Juniper.MediaType.All, and Juniper.MediaType.InternalParseAll().
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable().
ToString()
override string Juniper.MediaType.ToString () inline inherited
Definition at line 385 of file MediaType.cs.
         {
             if (Weight == 1)
             {
                 return Value;
             }
             else
             {
                 return weightedValue;
             }
         }
References Juniper.MediaType.Value, Juniper.MediaType.Weight, and Juniper.MediaType.weightedValue.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.ListDirectoryAsync().
TryParse()
static bool Juniper.MediaType.TryParse (string value, out MediaType type) inline static inherited
Definition at line 83 of file MediaType.cs.
         {
             type = null;
             if (value is null)
             {
                 return false;
             }
             var match = TYPE_PATTERN.Match(value);
             if (!match.Success)
             {
                 return false;
             }
             var typeName = match.Groups[1].Value;
             var subTypeName = match.Groups[2].Value;
             var rawValue = typeName + "/" + subTypeName;
             if (match.Groups.Count == 4
                 && float.TryParse(
                     match.Groups[3].Value,
                     NumberStyles.Integer | NumberStyles.AllowDecimalPoint,
                     CultureInfo.InvariantCulture,
                     out var weight))
             {
                 type = new MediaType(typeName, subTypeName, weight);
             }
             else if (byValue.ContainsKey(rawValue))
             {
                 type = byValue[rawValue];
             }
             else
             {
                 type = new MediaType(typeName, subTypeName);
             }
             return type is object;
         }
References Juniper.MediaType.byValue, Juniper.MediaType.MediaType(), and Juniper.MediaType.TYPE_PATTERN.
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.InternalParseAll(), Juniper.MediaType.Parse(), and Juniper.Processes.ProcessArgs.TryGetMediaType().
Member Data Documentation
All
readonly IReadOnlyCollection<MediaType> Juniper.MediaType.All = new MediaType[] { Any } static inherited
Definition at line 38 of file MediaType.cs.
Referenced by Juniper.MediaType.ParseAll().
Any
readonly MediaType Juniper.MediaType.Any = new MediaType("*/*") static inherited
Definition at line 36 of file MediaType.cs.
Referenced by Juniper.MediaType.Application.Matches(), Juniper.MediaType.Audio.Matches(), Juniper.MediaType.Chemical.Matches(), Juniper.MediaType.Font.Matches(), Juniper.MediaType.Image.Matches(), Juniper.MediaType.Message.Matches(), Juniper.MediaType.Model.Matches(), Juniper.MediaType.Multipart.Matches(), Juniper.MediaType.Text.Matches(), Juniper.MediaType.Video.Matches(), and Juniper.MediaType.XConference.Matches().
AnyText
readonly Text Juniper.MediaType.Text.AnyText = new Text("*") static
Definition at line 13 of file Text.cs.
Referenced by Juniper.MediaType.Text.Matches(), and Juniper.HTTP.Server.HttpListenerResponseExt.SetFileName().
Cache_Manifest
readonly Text Juniper.MediaType.Text.Cache_Manifest = new Text("cache-manifest", new string[] { "appcache" }) static
Definition at line 7 of file Text.Values.cs.
Calendar
readonly Text Juniper.MediaType.Text.Calendar = new Text("calendar", new string[] { "ics", "ifb" }) static
Definition at line 8 of file Text.Values.cs.
Css
readonly Text Juniper.MediaType.Text.Css = new Text("css", new string[] { "css" }) static
Definition at line 9 of file Text.Values.cs.
Csv
readonly Text Juniper.MediaType.Text.Csv = new Text("csv", new string[] { "csv" }) static
Definition at line 10 of file Text.Values.cs.
Csv_Schema
readonly Text Juniper.MediaType.Text.Csv_Schema = new Text("csv-schema") static
Definition at line 11 of file Text.Values.cs.
Directory
readonly Text Juniper.MediaType.Text.Directory = new Text("directory") static
Definition at line 14 of file Text.Values.cs.
Dns
readonly Text Juniper.MediaType.Text.Dns = new Text("dns") static
Definition at line 16 of file Text.Values.cs.
Ecmascript
readonly Text Juniper.MediaType.Text.Ecmascript = new Text("ecmascript") static
Definition at line 19 of file Text.Values.cs.
Encaprtp
readonly Text Juniper.MediaType.Text.Encaprtp = new Text("encaprtp") static
Definition at line 21 of file Text.Values.cs.
Enriched
readonly Text Juniper.MediaType.Text.Enriched = new Text("enriched") static
Definition at line 22 of file Text.Values.cs.
Example
readonly Text Juniper.MediaType.Text.Example = new Text("example") static
Definition at line 23 of file Text.Values.cs.
Flexfec
readonly Text Juniper.MediaType.Text.Flexfec = new Text("flexfec") static
Definition at line 24 of file Text.Values.cs.
Fwdred
readonly Text Juniper.MediaType.Text.Fwdred = new Text("fwdred") static
Definition at line 25 of file Text.Values.cs.
Grammar_Ref_List
readonly Text Juniper.MediaType.Text.Grammar_Ref_List = new Text("grammar-ref-list") static
Definition at line 26 of file Text.Values.cs.
Html
readonly Text Juniper.MediaType.Text.Html = new Text("html", new string[] { "html", "htm" }) static
Definition at line 27 of file Text.Values.cs.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.ListDirectoryAsync().
Javascript
readonly Text Juniper.MediaType.Text.Javascript = new Text("javascript") static
Definition at line 30 of file Text.Values.cs.
Jcr_Cnd
readonly Text Juniper.MediaType.Text.Jcr_Cnd = new Text("jcr-cnd") static
Definition at line 32 of file Text.Values.cs.
Markdown
readonly Text Juniper.MediaType.Text.Markdown = new Text("markdown") static
Definition at line 33 of file Text.Values.cs.
Mizar
readonly Text Juniper.MediaType.Text.Mizar = new Text("mizar") static
Definition at line 34 of file Text.Values.cs.
N3
readonly Text Juniper.MediaType.Text.N3 = new Text("n3", new string[] { "n3" }) static
Definition at line 35 of file Text.Values.cs.
Parameters
readonly Text Juniper.MediaType.Text.Parameters = new Text("parameters") static
Definition at line 36 of file Text.Values.cs.
Parityfec
readonly Text Juniper.MediaType.Text.Parityfec = new Text("parityfec") static
Definition at line 37 of file Text.Values.cs.
Plain
readonly Text Juniper.MediaType.Text.Plain = new Text("plain", new string[] { "txt", "text", "conf", "def", "list", "log", "in" }) static
Definition at line 38 of file Text.Values.cs.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.InvokeAsync(), and Juniper.HTTP.Server.HttpListenerResponseExt.SendTextAsync().
Provenance_Notation
readonly Text Juniper.MediaType.Text.Provenance_Notation = new Text("provenance-notation") static
Definition at line 39 of file Text.Values.cs.
PrsFallensteinRst
readonly Text Juniper.MediaType.Text.PrsFallensteinRst = new Text("prs.fallenstein.rst") static
Definition at line 40 of file Text.Values.cs.
PrsLinesTag
readonly Text Juniper.MediaType.Text.PrsLinesTag = new Text("prs.lines.tag", new string[] { "dsc" }) static
Definition at line 41 of file Text.Values.cs.
PrsPropLogic
readonly Text Juniper.MediaType.Text.PrsPropLogic = new Text("prs.prop.logic") static
Definition at line 42 of file Text.Values.cs.
Raptorfec
readonly Text Juniper.MediaType.Text.Raptorfec = new Text("raptorfec") static
Definition at line 43 of file Text.Values.cs.
RED
readonly Text Juniper.MediaType.Text.RED = new Text("red") static
Definition at line 44 of file Text.Values.cs.
Rfc822_Headers
readonly Text Juniper.MediaType.Text.Rfc822_Headers = new Text("rfc822-headers") static
Definition at line 45 of file Text.Values.cs.
Richtext
readonly Text Juniper.MediaType.Text.Richtext = new Text("richtext", new string[] { "rtx" }) static
Definition at line 46 of file Text.Values.cs.
Rtf
readonly Text Juniper.MediaType.Text.Rtf = new Text("rtf") static
Definition at line 47 of file Text.Values.cs.
Rtp_Enc_Aescm128
readonly Text Juniper.MediaType.Text.Rtp_Enc_Aescm128 = new Text("rtp-enc-aescm128") static
Definition at line 48 of file Text.Values.cs.
Rtploopback
readonly Text Juniper.MediaType.Text.Rtploopback = new Text("rtploopback") static
Definition at line 49 of file Text.Values.cs.
Rtx
readonly Text Juniper.MediaType.Text.Rtx = new Text("rtx") static
Definition at line 50 of file Text.Values.cs.
Sgml
readonly Text Juniper.MediaType.Text.Sgml = new Text("sgml", new string[] { "sgml", "sgm" }) static
Definition at line 51 of file Text.Values.cs.
Strings
readonly Text Juniper.MediaType.Text.Strings = new Text("strings") static
Definition at line 52 of file Text.Values.cs.
T140
readonly Text Juniper.MediaType.Text.T140 = new Text("t140") static
Definition at line 53 of file Text.Values.cs.
Tab_Separated_Values
readonly Text Juniper.MediaType.Text.Tab_Separated_Values = new Text("tab-separated-values", new string[] { "tsv" }) static
Definition at line 54 of file Text.Values.cs.
Troff
readonly Text Juniper.MediaType.Text.Troff = new Text("troff", new string[] { "t", "tr", "roff", "man", "me", "ms" }) static
Definition at line 55 of file Text.Values.cs.
Turtle
readonly Text Juniper.MediaType.Text.Turtle = new Text("turtle", new string[] { "ttl" }) static
Definition at line 56 of file Text.Values.cs.
Ulpfec
readonly Text Juniper.MediaType.Text.Ulpfec = new Text("ulpfec") static
Definition at line 57 of file Text.Values.cs.
Uri_List
readonly Text Juniper.MediaType.Text.Uri_List = new Text("uri-list", new string[] { "uri", "uris", "urls" }) static
Definition at line 58 of file Text.Values.cs.
Values
new readonly Text [] Juniper.MediaType.Text.Values static
Definition at line 115 of file Text.Values.cs.
Referenced by Juniper.MediaType.Text.Matches().
Vcard
readonly Text Juniper.MediaType.Text.Vcard = new Text("vcard", new string[] { "vcard" }) static
Definition at line 59 of file Text.Values.cs.
Vendor1d_Interleaved_Parityfec
readonly Text Juniper.MediaType.Text.Vendor1d_Interleaved_Parityfec = new Text("1d-interleaved-parityfec") static
Definition at line 60 of file Text.Values.cs.
VendorA
readonly Text Juniper.MediaType.Text.VendorA = new Text("vnd.a") static
Definition at line 61 of file Text.Values.cs.
VendorAbc
readonly Text Juniper.MediaType.Text.VendorAbc = new Text("vnd.abc") static
Definition at line 62 of file Text.Values.cs.
VendorAscii_Art
readonly Text Juniper.MediaType.Text.VendorAscii_Art = new Text("vnd.ascii-art") static
Definition at line 63 of file Text.Values.cs.
VendorCurl
readonly Text Juniper.MediaType.Text.VendorCurl = new Text("vnd.curl", new string[] { "curl" }) static
Definition at line 64 of file Text.Values.cs.
VendorCurlDcurl
readonly Text Juniper.MediaType.Text.VendorCurlDcurl = new Text("vnd.curl.dcurl", new string[] { "dcurl" }) static
Definition at line 65 of file Text.Values.cs.
VendorCurlMcurl
readonly Text Juniper.MediaType.Text.VendorCurlMcurl = new Text("vnd.curl.mcurl", new string[] { "mcurl" }) static
Definition at line 66 of file Text.Values.cs.
VendorCurlScurl
readonly Text Juniper.MediaType.Text.VendorCurlScurl = new Text("vnd.curl.scurl", new string[] { "scurl" }) static
Definition at line 67 of file Text.Values.cs.
VendorDebianCopyright
readonly Text Juniper.MediaType.Text.VendorDebianCopyright = new Text("vnd.debian.copyright") static
Definition at line 68 of file Text.Values.cs.
VendorDMClientScript
readonly Text Juniper.MediaType.Text.VendorDMClientScript = new Text("vnd.dmclientscript") static
Definition at line 69 of file Text.Values.cs.
VendorDvbSubtitle
readonly Text Juniper.MediaType.Text.VendorDvbSubtitle = new Text("vnd.dvb.subtitle", new string[] { "sub" }) static
Definition at line 70 of file Text.Values.cs.
VendorEsmertecTheme_Descriptor
readonly Text Juniper.MediaType.Text.VendorEsmertecTheme_Descriptor = new Text("vnd.esmertec.theme-descriptor") static
Definition at line 71 of file Text.Values.cs.
VendorFiclabFlt
readonly Text Juniper.MediaType.Text.VendorFiclabFlt = new Text("vnd.ficlab.flt") static
Definition at line 72 of file Text.Values.cs.
VendorFly
readonly Text Juniper.MediaType.Text.VendorFly = new Text("vnd.fly", new string[] { "fly" }) static
Definition at line 73 of file Text.Values.cs.
VendorFmiFlexstor
readonly Text Juniper.MediaType.Text.VendorFmiFlexstor = new Text("vnd.fmi.flexstor", new string[] { "flx" }) static
Definition at line 74 of file Text.Values.cs.
VendorGml
readonly Text Juniper.MediaType.Text.VendorGml = new Text("vnd.gml") static
Definition at line 75 of file Text.Values.cs.
VendorGraphviz
readonly Text Juniper.MediaType.Text.VendorGraphviz = new Text("vnd.graphviz", new string[] { "gv" }) static
Definition at line 76 of file Text.Values.cs.
VendorHgl
readonly Text Juniper.MediaType.Text.VendorHgl = new Text("vnd.hgl") static
Definition at line 77 of file Text.Values.cs.
VendorIn3d3dml
readonly Text Juniper.MediaType.Text.VendorIn3d3dml = new Text("vnd.in3d.3dml", new string[] { "3dml" }) static
Definition at line 78 of file Text.Values.cs.
VendorIn3dSpot
readonly Text Juniper.MediaType.Text.VendorIn3dSpot = new Text("vnd.in3d.spot", new string[] { "spot" }) static
Definition at line 79 of file Text.Values.cs.
VendorIPTCNewsML
readonly Text Juniper.MediaType.Text.VendorIPTCNewsML = new Text("vnd.iptc.newsml") static
Definition at line 80 of file Text.Values.cs.
VendorIPTCNITF
readonly Text Juniper.MediaType.Text.VendorIPTCNITF = new Text("vnd.iptc.nitf") static
Definition at line 81 of file Text.Values.cs.
VendorLatex_Z
readonly Text Juniper.MediaType.Text.VendorLatex_Z = new Text("vnd.latex-z") static
Definition at line 82 of file Text.Values.cs.
VendorMotorolaReflex
readonly Text Juniper.MediaType.Text.VendorMotorolaReflex = new Text("vnd.motorola.reflex") static
Definition at line 83 of file Text.Values.cs.
VendorMs_Mediapackage
readonly Text Juniper.MediaType.Text.VendorMs_Mediapackage = new Text("vnd.ms-mediapackage") static
Definition at line 84 of file Text.Values.cs.
VendorNet2phoneCommcenterCommand
readonly Text Juniper.MediaType.Text.VendorNet2phoneCommcenterCommand = new Text("vnd.net2phone.commcenter.command") static
Definition at line 85 of file Text.Values.cs.
VendorRadisysMsml_Basic_Layout
readonly Text Juniper.MediaType.Text.VendorRadisysMsml_Basic_Layout = new Text("vnd.radisys.msml-basic-layout") static
Definition at line 86 of file Text.Values.cs.
VendorSenxWarpscript
readonly Text Juniper.MediaType.Text.VendorSenxWarpscript = new Text("vnd.senx.warpscript") static
Definition at line 87 of file Text.Values.cs.
VendorSiUricatalogue
readonly Text Juniper.MediaType.Text.VendorSiUricatalogue = new Text("vnd.si.uricatalogue") static
Definition at line 90 of file Text.Values.cs.
VendorSosi
readonly Text Juniper.MediaType.Text.VendorSosi = new Text("vnd.sosi") static
Definition at line 92 of file Text.Values.cs.
VendorSunJ2meApp_Descriptor
readonly Text Juniper.MediaType.Text.VendorSunJ2meApp_Descriptor = new Text("vnd.sun.j2me.app-descriptor", new string[] { "jad" }) static
Definition at line 93 of file Text.Values.cs.
VendorTrolltechLinguist
readonly Text Juniper.MediaType.Text.VendorTrolltechLinguist = new Text("vnd.trolltech.linguist") static
Definition at line 94 of file Text.Values.cs.
VendorWapSi
readonly Text Juniper.MediaType.Text.VendorWapSi = new Text("vnd.wap.si") static
Definition at line 95 of file Text.Values.cs.
VendorWapSl
readonly Text Juniper.MediaType.Text.VendorWapSl = new Text("vnd.wap.sl") static
Definition at line 96 of file Text.Values.cs.
VendorWapWml
readonly Text Juniper.MediaType.Text.VendorWapWml = new Text("vnd.wap.wml", new string[] { "wml" }) static
Definition at line 97 of file Text.Values.cs.
VendorWapWmlscript
readonly Text Juniper.MediaType.Text.VendorWapWmlscript = new Text("vnd.wap.wmlscript", new string[] { "wmls" }) static
Definition at line 98 of file Text.Values.cs.
Vtt
readonly Text Juniper.MediaType.Text.Vtt = new Text("vtt") static
Definition at line 99 of file Text.Values.cs.
X_Asm
readonly Text Juniper.MediaType.Text.X_Asm = new Text("x-asm", new string[] { "s", "asm" }) static
Definition at line 100 of file Text.Values.cs.
X_C
readonly Text Juniper.MediaType.Text.X_C = new Text("x-c", new string[] { "c", "cc", "cxx", "cpp", "h", "hh", "dic" }) static
Definition at line 101 of file Text.Values.cs.
X_Fortran
readonly Text Juniper.MediaType.Text.X_Fortran = new Text("x-fortran", new string[] { "f", "for", "f77", "f90" }) static
Definition at line 102 of file Text.Values.cs.
X_Java_Source
readonly Text Juniper.MediaType.Text.X_Java_Source = new Text("x-java-source", new string[] { "java" }) static
Definition at line 103 of file Text.Values.cs.
X_Nfo
readonly Text Juniper.MediaType.Text.X_Nfo = new Text("x-nfo", new string[] { "nfo" }) static
Definition at line 104 of file Text.Values.cs.
X_Opml
readonly Text Juniper.MediaType.Text.X_Opml = new Text("x-opml", new string[] { "opml" }) static
Definition at line 105 of file Text.Values.cs.
X_Pascal
readonly Text Juniper.MediaType.Text.X_Pascal = new Text("x-pascal", new string[] { "p", "pas" }) static
Definition at line 106 of file Text.Values.cs.
X_Setext
readonly Text Juniper.MediaType.Text.X_Setext = new Text("x-setext", new string[] { "etx" }) static
Definition at line 107 of file Text.Values.cs.
X_Sfv
readonly Text Juniper.MediaType.Text.X_Sfv = new Text("x-sfv", new string[] { "sfv" }) static
Definition at line 108 of file Text.Values.cs.
X_Uuencode
readonly Text Juniper.MediaType.Text.X_Uuencode = new Text("x-uuencode", new string[] { "uu" }) static
Definition at line 109 of file Text.Values.cs.
X_Vcalendar
readonly Text Juniper.MediaType.Text.X_Vcalendar = new Text("x-vcalendar", new string[] { "vcs" }) static
Definition at line 110 of file Text.Values.cs.
X_Vcard
readonly Text Juniper.MediaType.Text.X_Vcard = new Text("x-vcard", new string[] { "vcf" }) static
Definition at line 111 of file Text.Values.cs.
Xml
readonly Text Juniper.MediaType.Text.Xml = new Text("xml") static
Definition at line 112 of file Text.Values.cs.
Xml_External_Parsed_Entity
readonly Text Juniper.MediaType.Text.Xml_External_Parsed_Entity = new Text("xml-external-parsed-entity") static
Definition at line 113 of file Text.Values.cs.
Property Documentation
Extensions
ReadOnlyCollection<string> Juniper.MediaType.Extensions get inherited
Definition at line 211 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.UpdateLookupTables().
PrimaryExtension
string Juniper.MediaType.PrimaryExtension get inherited
Definition at line 213 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
SubTypeName
string Juniper.MediaType.SubTypeName get inherited
Definition at line 207 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
TypeName
string Juniper.MediaType.TypeName get inherited
Definition at line 205 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
Value
string Juniper.MediaType.Value get inherited
Definition at line 203 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.MediaType(), Juniper.MediaType.ToString(), and Juniper.MediaType.UpdateLookupTables().
Weight
float Juniper.MediaType.Weight get inherited
Definition at line 209 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.ToString().
The documentation for this class was generated from the following files:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Text.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Text.Values.cs