Juniper: Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, HapticsType, ConfigType > Class Template Reference
Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, HapticsType, ConfigType > Class Template Reference abstract
A ScreenDevice is a AbstractPointerDevice<ButtonIDType, HapticsType> that has its primary pointer interactions happening in screen space.
Public Member Functions
virtual void Awake ()
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
void Start ()
virtual bool Install (bool reset)
virtual void Uninstall ()
virtual void Reinstall ()
virtual void SetProbe (Probe p)
Vector2 ScreenFromWorld (Vector3 worldPoint)
Vector2 ScreenFromViewport (Vector2 viewportPoint)
Vector2 ViewportFromWorld (Vector3 worldPoint)
Vector2 ViewportFromScreen (Vector2 screenPoint)
Vector3 WorldFromScreen (Vector2 screenPoint)
Vector3 WorldFromViewport (Vector2 viewportPoint)
virtual void Update ()
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
virtual void PlayInteraction (Interaction action)
virtual void Process (PointerEventData evtData, float pixelDragThresholdSquared)
virtual bool IsButtonPressed (InputButton button)
abstract bool IsButtonPressed (ButtonIDType button)
bool IsButtonPressed (PointerEventData.InputButton button)
virtual bool IsButtonUp (InputButton button)
abstract bool IsButtonUp (ButtonIDType button)
bool IsButtonUp (PointerEventData.InputButton button)
virtual bool IsButtonDown (InputButton button)
abstract bool IsButtonDown (ButtonIDType button)
bool IsButtonDown (PointerEventData.InputButton button)
Public Attributes
bool Connected
Material LaserPointerMaterial
bool showProbe = true
AbstractMotionFilter motionFilter
Protected Member Functions
override void InternalUpdate ()
void DraggableChanged (bool dragging)
virtual IEventSystemHandler ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared)
Protected Attributes
readonly ButtonMapper< ButtonIDType > nativeButtons = new ButtonMapper<ButtonIDType>()
Vector3 pointerOffset
Probe probe
The cursor probe that shows the physical location of the current selection.
AbstractUnifiedInputModule eventManager
StageExtensions stage
Static Protected Attributes
static readonly Vector2 VIEWPORT_MIDPOINT
static readonly ConfigType PointerConfig
Properties
virtual Vector3 CameraPositionOffset [get]
virtual Quaternion CameraRotationOffset [get]
Type ButtonType [get]
float MinimumPointerDistance [get]
The minimum distance from the camera at which to place the pointer.
float MaximumPointerDistance [get]
bool LockedOnTarget [get, set]
IEventSystemHandler EventTarget [get, set]
abstract bool IsConnected [get]
bool IsEnabled [get]
bool IsDisabled [get]
Returns true when the device is supposed to be disabled.
PhysicsRaycaster? Raycaster [get]
Camera? EventCamera [get]
The camera the pointer uses to point at Canvas objects.
int PointerID [get, set]
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
virtual bool AnyButtonPressed [get]
string ProbeName [get, private set]
Vector3 Origin [get]
Vector3 LastOrigin [get, private set]
Vector3 OriginDelta [get]
abstract Vector3 WorldPoint [get]
Vector3 LastWorldPoint [get, private set]
Vector3 WorldDelta [get]
Vector3??? SmoothedWorldPoint [get]
The target at and through which the pointer rays fire.
Vector3 LastSmoothedWorldPoint [get, private set]
Vector3 SmoothedWorldPointDelta [get]
Vector3 Direction [get]
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
Vector3 LastDirection [get]
Vector2 ScreenPoint [get]
Vector2 LastScreenPoint [get]
Vector2 ScreenDelta [get]
Vector2 ViewportPoint [get]
Vector2 LastViewportPoint [get]
Vector2 ViewportDelta [get]
Vector2 ScrollDelta [get, protected set]
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
AbstractUnifiedInputModule InputModule [get]
bool IsDragging [get, private set]
HapticsType Haptics [get, protected set]
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
string name [get]
string name [get]
bool isActiveAndEnabled [get]
Detailed Description
A ScreenDevice is a AbstractPointerDevice<ButtonIDType, HapticsType> that has its primary pointer interactions happening in screen space.
Type Constraints
ButtonIDType : struct
HapticsType : AbstractHapticDevice
ConfigType : AbstractPointerConfiguration<ButtonIDType>
ConfigType : new()
Definition at line 12 of file AbstractScreenDevice.cs.
Member Function Documentation
Awake()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake () inline virtual inherited
Initializes a new instance of the T:Juniper.Input.PointerDevice class.
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 170 of file AbstractPointerDevice.cs.
         {
             Install(false);
             eventManager = ComponentExt.FindAny<UnifiedInputModule>();
             stage = ComponentExt.FindAny<StageExtensions>();
             pointerOffset = MinimumPointerDistance * Vector3.forward;
             ProbeName = name;
             Haptics = this.EnsureComponent<HapticsType>();
             nativeButtons.ButtonDownNeeded += IsButtonDown;
             nativeButtons.ButtonUpNeeded += IsButtonUp;
             nativeButtons.ButtonPressedNeeded += IsButtonPressed;
             nativeButtons.ClonedPointerEventNeeded += Clone;
             nativeButtons.InteractionNeeded += PlayInteraction;
             nativeButtons.DraggableChanged += DraggableChanged;
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.DraggableChanged(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.eventManager, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MinimumPointerDistance, Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.name, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProbeName, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.stage.
DraggableChanged()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.DraggableChanged (bool dragging) inline protected inherited
Definition at line 190 of file AbstractPointerDevice.cs.
         {
             IsDragging = dragging;
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
Install()
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install (bool reset) inline virtual inherited
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 200 of file AbstractPointerDevice.cs.
         {
             reset &= Application.isEditor;
             PointerConfig.Install(nativeButtons, gameObject);
             return true;
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reinstall().
InternalUpdate()
override void Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, HapticsType, ConfigType >.InternalUpdate () inline protected virtual
Implements Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.
Definition at line 35 of file AbstractScreenDevice.cs.
         {
             var camT = DisplayManager.MainCamera.transform;
             var cameraRotation = Quaternion.LookRotation(Direction, camT.up) * CameraRotationOffset;
             transform.position = camT.position + (cameraRotation * CameraPositionOffset);
             transform.rotation = cameraRotation;
         }
IsButtonDown() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonDown (PointerEventData.InputButton button) inherited
IsButtonDown() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown (InputButton button) inline virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 610 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonDown(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
IsButtonDown() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonPressed() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonPressed (PointerEventData.InputButton button) inherited
IsButtonPressed() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed (InputButton button) inline virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 600 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonPressed(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
IsButtonPressed() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
IsButtonUp() [1/3]
bool Juniper.Unity.Input.Pointers.IPointerDevice.IsButtonUp (PointerEventData.InputButton button) inherited
IsButtonUp() [2/3]
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp (InputButton button) inline virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 605 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.IsButtonUp(button);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
IsButtonUp() [3/3]
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp (ButtonIDType button) pure virtual inherited
Implements Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.
PlayInteraction()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction (Interaction action) inline virtual inherited
Definition at line 535 of file AbstractPointerDevice.cs.
         {
             if (Time.time > finishTime || action != lastAction)
             {
                 lastAction = action;
                 finishTime = Time.time + InteractionAudio.Play(action, probe.Cursor, Haptics);
             }
         }
References Juniper.Unity.Input.Pointers.Probe.Cursor, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.finishTime, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.lastAction, Juniper.Unity.Audio.InteractionAudio.Play(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.TestEnterExit().
Process()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process (PointerEventData evtData, float pixelDragThresholdSquared) inline virtual inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 549 of file AbstractPointerDevice.cs.
         {
             if (!IsDragging)
             {
                 TestEnterExit(evtData);
             }
             EventTarget = ProcessButtons(evtData, pixelDragThresholdSquared);
             if (evtData.clickCount == -1)
             {
                 evtData.clickCount = 0;
             }
             LastWorldPoint = evtData.pointerCurrentRaycast.worldPosition;
             LastSmoothedWorldPoint = SmoothedWorldPoint;
             LastOrigin = Origin;
             probe?.SetCursor(
                 evtData.pointerCurrentRaycast.gameObject != null,
                 AnyButtonPressed,
                 LastWorldPoint,
                 evtData.pointerCurrentRaycast.worldNormal);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.AnyButtonPressed, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventTarget, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastOrigin, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastSmoothedWorldPoint, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastWorldPoint, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Origin, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons(), Juniper.Unity.Input.Pointers.Probe.SetCursor(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SmoothedWorldPoint, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.TestEnterExit().
ProcessButtons()
virtual IEventSystemHandler Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons (PointerEventData evtData, float pixelDragThresholdSquared) inline protected virtual inherited
Reimplemented in Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< HandIDType, ButtonIDType, ConfigType, HapticsType >.
Definition at line 574 of file AbstractPointerDevice.cs.
         {
             return nativeButtons.Process(evtData, pixelDragThresholdSquared);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
Reinstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Reinstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 214 of file AbstractPointerDevice.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install().
ScreenFromViewport()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 437 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ViewportToScreenPoint(viewportPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
ScreenFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 432 of file AbstractPointerDevice.cs.
         {
             return EventCamera.WorldToScreenPoint(worldPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
SetProbe()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SetProbe (Probe p) inline virtual inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 253 of file AbstractPointerDevice.cs.
         {
             if (probe != p)
             {
                 if (probe != null)
                 {
                     probe.gameObject.Destroy();
                 }
                 probe = p ?? FindProbe();
             }
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.FindProbe(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe.
Start()
void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Start () inline inherited
Definition at line 195 of file AbstractPointerDevice.cs.
         {
             eventManager.AddPointer(this);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.eventManager.
Uninstall()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Uninstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 209 of file AbstractPointerDevice.cs.
         {
             PointerConfig.Uninstall(gameObject);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig.
Update()
virtual void Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update () inline virtual inherited
Update the position of the pointer and the pointer probe. Also check to see if the configuration has been changed to hide the pointer probe.
Definition at line 473 of file AbstractPointerDevice.cs.
         {
             if (motionFilter != lastMotionFilter)
             {
 #if UNITY_EDITOR
                 parent = motionFilter;
 #endif
                 motionFilter = Instantiate(motionFilter);
                 lastMotionFilter = motionFilter;
             }
 #if UNITY_EDITOR
             motionFilter?.Copy(parent);
 #endif
             Connected = IsConnected;
             if (probe != null)
             {
                 probe.SetActive(IsEnabled && showProbe);
                 probe.LaserPointerMaterial = LaserPointerMaterial;
             }
             if (IsEnabled)
             {
                 motionFilter?.UpdateState(WorldPoint);
                 InternalUpdate();
                 probe?.AlignProbe(Direction, transform.up, MaximumPointerDistance);
             }
         }
References Juniper.Unity.Input.Pointers.Probe.AlignProbe(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Connected, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsConnected, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsEnabled, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LaserPointerMaterial, Juniper.Unity.Input.Pointers.Probe.LaserPointerMaterial, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.lastMotionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MaximumPointerDistance, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.motionFilter, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe, Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.showProbe, Juniper.Unity.Statistics.AbstractMotionFilter.UpdateState(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldPoint.
ViewportFromScreen()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 447 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ScreenToViewportPoint(screenPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
ViewportFromWorld()
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromWorld (Vector3 worldPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 442 of file AbstractPointerDevice.cs.
         {
             return EventCamera.WorldToViewportPoint(worldPoint);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera.
WorldFromScreen()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen (Vector2 screenPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 452 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ScreenToWorldPoint((Vector3)screenPoint + pointerOffset);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset.
WorldFromViewport()
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport (Vector2 viewportPoint) inline inherited
Implements Juniper.Unity.Input.Pointers.IPointerDevice.
Definition at line 457 of file AbstractPointerDevice.cs.
         {
             return EventCamera.ViewportToWorldPoint((Vector3)viewportPoint + pointerOffset);
         }
References Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera, and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset.
Member Data Documentation
Connected
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Connected inherited
Definition at line 69 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
eventManager
AbstractUnifiedInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.eventManager protected inherited
Definition at line 504 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Start().
LaserPointerMaterial
Material Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LaserPointerMaterial inherited
Definition at line 92 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
motionFilter
AbstractMotionFilter Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.motionFilter inherited
Definition at line 467 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
nativeButtons
readonly ButtonMapper<ButtonIDType> Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.nativeButtons = new ButtonMapper<ButtonIDType>() protected inherited
Definition at line 66 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonDown(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonPressed(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsButtonUp(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProcessButtons().
PointerConfig
readonly ConfigType Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerConfig static protected inherited
Initial value:
=
            new ConfigType()
Definition at line 55 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Install(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Install(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Uninstall().
pointerOffset
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.pointerOffset protected inherited
Definition at line 82 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport().
probe
Probe Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.probe protected inherited
The cursor probe that shows the physical location of the current selection.
Definition at line 239 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SetProbe(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
showProbe
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.showProbe = true inherited
Definition at line 228 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
stage
StageExtensions Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.stage protected inherited
Definition at line 514 of file AbstractPointerDevice.cs.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
VIEWPORT_MIDPOINT
readonly Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.VIEWPORT_MIDPOINT static protected inherited
Initial value:
=
            0.5f * Vector2.one
Definition at line 52 of file AbstractPointerDevice.cs.
Property Documentation
AnyButtonPressed
virtual bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.AnyButtonPressed get inherited
Definition at line 158 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return IsButtonPressed(InputButton.Left)
                     || IsButtonPressed(InputButton.Right)
                     || IsButtonPressed(InputButton.Middle);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
ButtonType
Type Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ButtonType get inherited
Definition at line 59 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return typeof(ButtonIDType);
             }
         }
CameraPositionOffset
virtual Vector3 Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, HapticsType, ConfigType >.CameraPositionOffset get
Definition at line 20 of file AbstractScreenDevice.cs.
         {
             get
             {
                 return Vector3.zero;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< KeyCode, NoHaptics, MouseConfiguration >.InternalUpdate().
CameraRotationOffset
virtual Quaternion Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< ButtonIDType, HapticsType, ConfigType >.CameraRotationOffset get
Definition at line 28 of file AbstractScreenDevice.cs.
         {
             get
             {
                 return Quaternion.identity;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.Screen.AbstractScreenDevice< KeyCode, NoHaptics, MouseConfiguration >.InternalUpdate().
Direction
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Direction get inherited
The direction the pointer is pointing, from InteractionOrigin to SmoothedWorldPoint.
The interaction direction.
Definition at line 360 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (SmoothedWorldPoint - Origin).normalized;
             }
         }
EventCamera
Camera? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventCamera get inherited
The camera the pointer uses to point at Canvas objects.
Definition at line 141 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.EventCamera;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromViewport(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenFromWorld(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromScreen(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportFromWorld(), Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromScreen(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldFromViewport().
EventTarget
IEventSystemHandler Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.EventTarget get set inherited
Definition at line 100 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
Haptics
HapticsType Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Haptics get protected set inherited
The haptic feedback system associated with the device. For touch pointers, this is the global haptic system. For motion controllers, each controller has its own haptic system.
The haptics.
Definition at line 528 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PlayInteraction().
InputModule
AbstractUnifiedInputModule Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.InputModule get inherited
Definition at line 507 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return eventManager;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Clone(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone().
isActiveAndEnabled
bool Juniper.Unity.Input.Pointers.IPointerDevice.isActiveAndEnabled get inherited
Definition at line 41 of file IPointerDevice.cs.
         {
             get;
         }
IsConnected
abstract bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsConnected get inherited
Definition at line 105 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
IsDisabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDisabled get inherited
Returns true when the device is supposed to be disabled.
true if is disabled; otherwise, false.
Definition at line 122 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return !IsEnabled;
             }
         }
IsDragging
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsDragging get private set inherited
Definition at line 517 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.DraggableChanged(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
IsEnabled
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.IsEnabled get inherited
Definition at line 110 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return isActiveAndEnabled && IsConnected;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
LastDirection
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastDirection get inherited
Definition at line 368 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return (LastSmoothedWorldPoint - LastOrigin).normalized;
             }
         }
LastOrigin
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastOrigin get private set inherited
Definition at line 298 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
LastScreenPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastScreenPoint get inherited
Definition at line 384 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(LastSmoothedWorldPoint);
             }
         }
LastSmoothedWorldPoint
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastSmoothedWorldPoint get private set inherited
Definition at line 342 of file AbstractPointerDevice.cs.
         {
             get;
             private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
LastViewportPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastViewportPoint get inherited
Definition at line 408 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(LastSmoothedWorldPoint);
             }
         }
LastWorldPoint
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LastWorldPoint get private set inherited
Definition at line 317 of file AbstractPointerDevice.cs.
         {
             get; private set;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
LockedOnTarget
bool Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.LockedOnTarget get set inherited
Definition at line 95 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
MaximumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MaximumPointerDistance get inherited
Definition at line 85 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Min(10f, 0.9f * DisplayManager.MainCamera.farClipPlane);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
MinimumPointerDistance
float Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.MinimumPointerDistance get inherited
The minimum distance from the camera at which to place the pointer.
Definition at line 75 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Mathf.Max(1.5f, 1.1f * DisplayManager.MainCamera.nearClipPlane);
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
name [1/2]
string Juniper.Input.Pointers.IPointerButtons< ButtonIDType >.name get inherited
Definition at line 7 of file IPointerButtons.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake().
name [2/2]
string Juniper.Unity.Input.Pointers.IPointerDevice.name get inherited
Definition at line 26 of file IPointerDevice.cs.
         {
             get;
         }
Origin
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Origin get inherited
Definition at line 290 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return transform.position;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
OriginDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.OriginDelta get inherited
Definition at line 304 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return Origin - LastOrigin;
             }
         }
PointerID
int Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.PointerID get set inherited
Unique pointer identifiers keep the pointer events cached in Unity's Event System.
The pointer identifier.
Definition at line 153 of file AbstractPointerDevice.cs.
         {
             get; set;
         }
ProbeName
string Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ProbeName get private set inherited
Definition at line 267 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return _probeName;
             }
             private set
             {
                 if (value != ProbeName)
                 {
                     if (probe != null)
                     {
                         probe.gameObject.Destroy();
                         probe = null;
                     }
                     _probeName = value;
                     SetProbe(FindProbe());
                 }
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Awake(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.FindProbe().
Raycaster
PhysicsRaycaster? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Raycaster get inherited
Definition at line 130 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return probe?.Raycaster;
             }
         }
ScreenDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenDelta get inherited
Definition at line 392 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenPoint - LastScreenPoint;
             }
         }
ScreenPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScreenPoint get inherited
Definition at line 376 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ScreenFromWorld(SmoothedWorldPoint);
             }
         }
ScrollDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ScrollDelta get protected set inherited
Mouse wheel and touch-pad scroll. This is a 2-dimensional value, as even with a single-wheel scroll mouse, you can hold the SHIFT key to scroll in the horizontal direction.
Definition at line 428 of file AbstractPointerDevice.cs.
         {
             get; protected set;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.InternalUpdate().
SmoothedWorldPoint
Vector3??? Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SmoothedWorldPoint get inherited
The target at and through which the pointer rays fire.
The interaction end point.
Definition at line 334 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return motionFilter?.PredictedPosition ?? WorldPoint;
             }
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Process().
SmoothedWorldPointDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.SmoothedWorldPointDelta get inherited
Definition at line 348 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return SmoothedWorldPoint - LastSmoothedWorldPoint;
             }
         }
ViewportDelta
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportDelta get inherited
Definition at line 416 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportPoint - LastViewportPoint;
             }
         }
ViewportPoint
Vector2 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.ViewportPoint get inherited
Definition at line 400 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return ViewportFromWorld(SmoothedWorldPoint);
             }
         }
WorldDelta
Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldDelta get inherited
Definition at line 322 of file AbstractPointerDevice.cs.
         {
             get
             {
                 return WorldPoint - LastWorldPoint;
             }
         }
WorldPoint
abstract Vector3 Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.WorldPoint get inherited
Definition at line 312 of file AbstractPointerDevice.cs.
         {
             get;
         }
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Update().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Input/Pointers/Screen/AbstractScreenDevice.cs