Juniper: BitMiracle.LibJpeg.Classic.JpegErrorMessage Class Reference
BitMiracle.LibJpeg.Classic.JpegErrorMessage Class Reference
Contains simple error-reporting and trace-message routines.
Public Member Functions
JpegErrorMessage ()
Initializes a new instance of the JpegErrorMessage class.
virtual void ErrorExit ()
Receives control for a fatal error.
virtual void EmitMessage (int msg_level)
Conditionally emit a trace or warning message.
virtual void OutputMessage ()
Actual output of any JPEG message.
virtual string FormatMessage ()
Constructs a readable error message string.
virtual void ResetErrorMessage ()
Resets error manager to initial state.
Public Attributes
int NumWarnings => m_numWarnings
Gets the number of corrupt-data warnings.
Protected Member Functions
virtual string GetMessageText (int code)
Gets the actual message texts.
Properties
int TraceLevel [get, set]
Gets or sets the maximum message level that will be displayed.
Private Attributes
internal int msgCode
internal object [] msgParam
internal int m_traceLevel
internal int m_numWarnings
Detailed Description
Contains simple error-reporting and trace-message routines.
This class is used by both the compression and decompression code.
Error handling
Definition at line 22 of file JpegErrorMessage.cs.
Constructor & Destructor Documentation
JpegErrorMessage()
BitMiracle.LibJpeg.Classic.JpegErrorMessage.JpegErrorMessage () inline
Initializes a new instance of the JpegErrorMessage class.
Definition at line 34 of file JpegErrorMessage.cs.
         {
         }
Member Function Documentation
EmitMessage()
virtual void BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage (int msg_level) inline virtual
Conditionally emit a trace or warning message.
Parameters
msg_level The message severity level.
Values are:
-1: recoverable corrupt-data warning, may want to abort.
0: important advisory messages (always display to user).
1: first level of tracing detail.
2, 3, ...: successively more detailed tracing messages.
The main reason for overriding this method would be to abort on warnings. This method calls output_message for message showing.
An application might override this method if it wanted to abort on warnings or change the policy about which messages to display.
Error handling
Definition at line 99 of file JpegErrorMessage.cs.
         {
             if (msg_level < 0)
             {
                 /* It's a warning message.  Since corrupt files may generate many warnings,
                  * the policy implemented here is to show only the first warning,
                  * unless trace_level >= 3.
                  */
                 if (m_numWarnings == 0 || m_traceLevel >= 3)
                 {
                     OutputMessage();
                 }
                 /* Always count warnings in num_warnings. */
                 m_numWarnings++;
             }
             else
             {
                 /* It's a trace message.  Show it if trace_level >= msg_level. */
                 if (m_traceLevel >= msg_level)
                 {
                     OutputMessage();
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.m_numWarnings, BitMiracle.LibJpeg.Classic.JpegErrorMessage.m_traceLevel, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.OutputMessage().
Referenced by BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
ErrorExit()
virtual void BitMiracle.LibJpeg.Classic.JpegErrorMessage.ErrorExit () inline virtual
Receives control for a fatal error.
This method calls output_message and then throws an exception.
Error handling
Definition at line 70 of file JpegErrorMessage.cs.
         {
             // Always display the message
             OutputMessage();
             var buffer = FormatMessage();
             throw new Exception(buffer);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.FormatMessage(), and BitMiracle.LibJpeg.Classic.JpegErrorMessage.OutputMessage().
Referenced by BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit().
FormatMessage()
virtual string BitMiracle.LibJpeg.Classic.JpegErrorMessage.FormatMessage () inline virtual
Constructs a readable error message string.
This method is called by output_message. Few applications should need to override this method. One possible reason for doing so is to implement dynamic switching of error message language.
Returns
The formatted message
Error handling
Definition at line 150 of file JpegErrorMessage.cs.
         {
             var msgtext = GetMessageText(msgCode);
             if (msgtext is null)
             {
                 msgParam = new object[] { msgCode };
                 msgtext = GetMessageText(0);
             }
             /* Format the message into the passed buffer */
             return string.Format(CultureInfo.CurrentCulture, msgtext, msgParam);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.GetMessageText(), BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam.
Referenced by BitMiracle.LibJpeg.Classic.JpegErrorMessage.ErrorExit(), and BitMiracle.LibJpeg.Classic.JpegErrorMessage.OutputMessage().
GetMessageText()
virtual string BitMiracle.LibJpeg.Classic.JpegErrorMessage.GetMessageText (int code) inline protected virtual
Gets the actual message texts.
Parameters
code The message code. See JMessageCode for details.
Returns
The message text associated with code.
It may be useful for an application to add its own message texts that are handled by the same mechanism. You can override GetMessageText for this purpose. If you number the addon messages beginning at 1000 or so, you won't have to worry about conflicts with the library's built-in messages.
See also
JMessageCode
Error handling
Definition at line 192 of file JpegErrorMessage.cs.
         {
             var msg = (JMessageCode)code;
             return msg switch
             {
                 /* For maintenance convenience, list is alphabetical by message code name */
                 JMessageCode.JERR_BAD_BUFFER_MODE => "Bogus buffer control mode",
                 JMessageCode.JERR_BAD_COMPONENT_ID => "Invalid component ID {0} in SOS",
                 JMessageCode.JERR_BAD_CROP_SPEC => "Invalid crop request",
                 JMessageCode.JERR_BAD_DCT_COEF => "DCT coefficient out of range",
                 JMessageCode.JERR_BAD_DCTSIZE => "DCT scaled output block size {0}x{1} not supported",
                 JMessageCode.JERR_BAD_DROP_SAMPLING => "Component index {0}: mismatching sampling ratio {1}:{2}, {3}:{4}, {5}",
                 JMessageCode.JERR_BAD_HUFF_TABLE => "Bogus Huffman table definition",
                 JMessageCode.JERR_BAD_IN_COLORSPACE => "Bogus input colorspace",
                 JMessageCode.JERR_BAD_J_COLORSPACE => "Bogus JPEG colorspace",
                 JMessageCode.JERR_BAD_LENGTH => "Bogus marker length",
                 JMessageCode.JERR_BAD_MCU_SIZE => "Sampling factors too large for interleaved scan",
                 JMessageCode.JERR_BAD_PRECISION => "Unsupported JPEG data precision {0}",
                 JMessageCode.JERR_BAD_PROGRESSION => "Invalid progressive parameters Ss={0} Se={1} Ah={2} Al={3}",
                 JMessageCode.JERR_BAD_PROG_SCRIPT => "Invalid progressive parameters at scan script entry {0}",
                 JMessageCode.JERR_BAD_SAMPLING => "Bogus sampling factors",
                 JMessageCode.JERR_BAD_SCAN_SCRIPT => "Invalid scan script at entry {0}",
                 JMessageCode.JERR_BAD_STATE => "Improper call to JPEG library in state {0}",
                 JMessageCode.JERR_BAD_VIRTUAL_ACCESS => "Bogus virtual array access",
                 JMessageCode.JERR_BUFFER_SIZE => "Buffer passed to JPEG library is too small",
                 JMessageCode.JERR_CANT_SUSPEND => "Suspension not allowed here",
                 JMessageCode.JERR_CCIR601_NOTIMPL => "CCIR601 sampling not implemented yet",
                 JMessageCode.JERR_COMPONENT_COUNT => "Too many color components: {0}, max {1}",
                 JMessageCode.JERR_CONVERSION_NOTIMPL => "Unsupported color conversion request",
                 JMessageCode.JERR_DAC_INDEX => "Bogus DAC index {0}",
                 JMessageCode.JERR_DAC_VALUE => "Bogus DAC value 0x{0}",
                 JMessageCode.JERR_DHT_INDEX => "Bogus DHT index {0}",
                 JMessageCode.JERR_DQT_INDEX => "Bogus DQT index {0}",
                 JMessageCode.JERR_EMPTY_IMAGE => "Empty JPEG image (DNL not supported)",
                 JMessageCode.JERR_EOI_EXPECTED => "Didn't expect more than one scan",
                 JMessageCode.JERR_FILE_WRITE => "Output file write error --- out of disk space?",
                 JMessageCode.JERR_FRACT_SAMPLE_NOTIMPL => "Fractional sampling not implemented yet",
                 JMessageCode.JERR_HUFF_CLEN_OVERFLOW => "Huffman code size table overflow",
                 JMessageCode.JERR_HUFF_MISSING_CODE => "Missing Huffman code table entry",
                 JMessageCode.JERR_IMAGE_TOO_BIG => "Maximum supported image dimension is {0} pixels",
                 JMessageCode.JERR_INPUT_EMPTY => "Empty input file",
                 JMessageCode.JERR_INPUT_EOF => "Premature end of input file",
                 JMessageCode.JERR_MISMATCHED_QUANT_TABLE => "Cannot transcode due to multiple use of quantization table {0}",
                 JMessageCode.JERR_MISSING_DATA => "Scan script does not transmit all data",
                 JMessageCode.JERR_MODE_CHANGE => "Invalid color quantization mode change",
                 JMessageCode.JERR_NOTIMPL => "Not implemented yet",
                 JMessageCode.JERR_NOT_COMPILED => "Requested feature was omitted at compile time",
                 JMessageCode.JERR_NO_ARITH_TABLE => "Arithmetic table 0x{0:X2} was not defined",
                 JMessageCode.JERR_NO_HUFF_TABLE => "Huffman table 0x{0:X2} was not defined",
                 JMessageCode.JERR_NO_IMAGE => "JPEG datastream contains no image",
                 JMessageCode.JERR_NO_QUANT_TABLE => "Quantization table 0x{0:X2} was not defined",
                 JMessageCode.JERR_NO_SOI => "Not a JPEG file: starts with 0x{0:X2} 0x{1:X2}",
                 JMessageCode.JERR_OUT_OF_MEMORY => "Insufficient memory (case {0})",
                 JMessageCode.JERR_QUANT_COMPONENTS => "Cannot quantize more than {0} color components",
                 JMessageCode.JERR_QUANT_FEW_COLORS => "Cannot quantize to fewer than {0} colors",
                 JMessageCode.JERR_QUANT_MANY_COLORS => "Cannot quantize to more than {0} colors",
                 JMessageCode.JERR_SOF_BEFORE => "Invalid JPEG file structure: {0} before SOF",
                 JMessageCode.JERR_SOF_DUPLICATE => "Invalid JPEG file structure: two SOF markers",
                 JMessageCode.JERR_SOF_NO_SOS => "Invalid JPEG file structure: missing SOS marker",
                 JMessageCode.JERR_SOF_UNSUPPORTED => "Unsupported JPEG process: SOF type 0x{0:X2}",
                 JMessageCode.JERR_SOI_DUPLICATE => "Invalid JPEG file structure: two SOI markers",
                 JMessageCode.JERR_SOS_NO_SOF => "Invalid JPEG file structure: SOS before SOF",
                 JMessageCode.JERR_TOO_LITTLE_DATA => "Application transferred too few scanlines",
                 JMessageCode.JERR_UNKNOWN_MARKER => "Unsupported marker type 0x{0:X2}",
                 JMessageCode.JERR_WIDTH_OVERFLOW => "Image too wide for this implementation",
                 JMessageCode.JTRC_16BIT_TABLES => "Caution: quantization tables are too coarse for baseline JPEG",
                 JMessageCode.JTRC_ADOBE => "Adobe APP14 marker: version {0}, flags 0x{1:X4} 0x{2:X4}, transform {3}",
                 JMessageCode.JTRC_APP0 => "Unknown APP0 marker (not JFIF), length {0}",
                 JMessageCode.JTRC_APP14 => "Unknown APP14 marker (not Adobe), length {0}",
                 JMessageCode.JTRC_DAC => "Define Arithmetic Table 0x{0:X2}: 0x{1:X2}",
                 JMessageCode.JTRC_DHT => "Define Huffman Table 0x{0:X2}",
                 JMessageCode.JTRC_DQT => "Define Quantization Table {0} precision {1}",
                 JMessageCode.JTRC_DRI => "Define Restart Interval {0}",
                 JMessageCode.JTRC_EOI => "End Of Image",
                 JMessageCode.JTRC_HUFFBITS => "        {0:D3} {1:D3} {2:D3} {3:D3} {4:D3} {5:D3} {6:D3} {7:D3}",
                 JMessageCode.JTRC_JFIF => "JFIF APP0 marker: version {0}.{1:D2}, density {2}x{3}  {4}",
                 JMessageCode.JTRC_JFIF_BADTHUMBNAILSIZE => "Warning: thumbnail image size does not match data length {0}",
                 JMessageCode.JTRC_JFIF_EXTENSION => "JFIF extension marker: type 0x{0:X2}, length {1}",
                 JMessageCode.JTRC_JFIF_THUMBNAIL => "    with {0} x {1} thumbnail image",
                 JMessageCode.JTRC_MISC_MARKER => "Miscellaneous marker 0x{0:X2}, length {1}",
                 JMessageCode.JTRC_PARMLESS_MARKER => "Unexpected marker 0x{0:X2}",
                 JMessageCode.JTRC_QUANTVALS => "        {0:D4} {1:D4} {2:D4} {3:D4} {4:D4} {5:D4} {6:D4} {7:D4}",
                 JMessageCode.JTRC_QUANT_3_NCOLORS => "Quantizing to {0} = {1}*{2}*{3} colors",
                 JMessageCode.JTRC_QUANT_NCOLORS => "Quantizing to {0} colors",
                 JMessageCode.JTRC_QUANT_SELECTED => "Selected {0} colors for quantization",
                 JMessageCode.JTRC_RECOVERY_ACTION => "At marker 0x{0:X2}, recovery action {1}",
                 JMessageCode.JTRC_RST => "RST{0}",
                 JMessageCode.JTRC_SMOOTH_NOTIMPL => "Smoothing not supported with nonstandard sampling ratios",
                 JMessageCode.JTRC_SOF => "Start Of Frame 0x{0:X2}: width={1}, height={2}, components={3}",
                 JMessageCode.JTRC_SOF_COMPONENT => "    Component {0}: {1}hx{2}v q={3}",
                 JMessageCode.JTRC_SOI => "Start of Image",
                 JMessageCode.JTRC_SOS => "Start Of Scan: {0} components",
                 JMessageCode.JTRC_SOS_COMPONENT => "    Component {0}: dc={1} ac={2}",
                 JMessageCode.JTRC_SOS_PARAMS => "  Ss={0}, Se={1}, Ah={2}, Al={3}",
                 JMessageCode.JTRC_THUMB_JPEG => "JFIF extension marker: JPEG-compressed thumbnail image, length {0}",
                 JMessageCode.JTRC_THUMB_PALETTE => "JFIF extension marker: palette thumbnail image, length {0}",
                 JMessageCode.JTRC_THUMB_RGB => "JFIF extension marker: RGB thumbnail image, length {0}",
                 JMessageCode.JTRC_UNKNOWN_IDS => "Unrecognized component IDs {0} {1} {2}, assuming YCbCr",
                 JMessageCode.JWRN_ADOBE_XFORM => "Unknown Adobe color transform code {0}",
                 JMessageCode.JWRN_ARITH_BAD_CODE => "Corrupt JPEG data: bad arithmetic code",
                 JMessageCode.JWRN_BOGUS_PROGRESSION => "Inconsistent progression sequence for component {0} coefficient {1}",
                 JMessageCode.JWRN_EXTRANEOUS_DATA => "Corrupt JPEG data: {0} extraneous bytes before marker 0x{1:X2}",
                 JMessageCode.JWRN_HIT_MARKER => "Corrupt JPEG data: premature end of data segment",
                 JMessageCode.JWRN_HUFF_BAD_CODE => "Corrupt JPEG data: bad Huffman code",
                 JMessageCode.JWRN_JFIF_MAJOR => "Warning: unknown JFIF revision number {0}.{1:D2}",
                 JMessageCode.JWRN_JPEG_EOF => "Premature end of JPEG file",
                 JMessageCode.JWRN_MUST_RESYNC => "Corrupt JPEG data: found marker 0x{0:X2} instead of RST{1}",
                 JMessageCode.JWRN_NOT_SEQUENTIAL => "Invalid SOS parameters for sequential JPEG",
                 JMessageCode.JWRN_TOO_MUCH_DATA => "Application transferred too many scanlines",
                 JMessageCode.JMSG_UNKNOWNMSGCODE => "Unknown message code (possibly it is an error from application)",
                 _ => "Bogus message code {0}",
             };
         }
Referenced by BitMiracle.LibJpeg.Classic.JpegErrorMessage.FormatMessage().
OutputMessage()
virtual void BitMiracle.LibJpeg.Classic.JpegErrorMessage.OutputMessage () inline virtual
Actual output of any JPEG message.
Override this to send messages somewhere other than Console. Note that this method does not know how to generate a message, only where to send it. For extending a generation of messages see format_message.
Error handling
Definition at line 133 of file JpegErrorMessage.cs.
         {
             // Create the message
             var buffer = FormatMessage();
             // Send it to console, adding a newline */
             Console.WriteLine(buffer);
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.FormatMessage().
Referenced by BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), and BitMiracle.LibJpeg.Classic.JpegErrorMessage.ErrorExit().
ResetErrorMessage()
virtual void BitMiracle.LibJpeg.Classic.JpegErrorMessage.ResetErrorMessage () inline virtual
Resets error manager to initial state.
This is called during compression startup to reset trace/error processing to default state. An application might possibly want to override this method if it has additional error processing state.
Definition at line 170 of file JpegErrorMessage.cs.
         {
             m_numWarnings = 0;
             /* trace_level is not reset since it is an application-supplied parameter */
             // may be useful as a flag for "no error"
             msgCode = 0;
         }
References BitMiracle.LibJpeg.Classic.JpegErrorMessage.m_numWarnings, and BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode.
Referenced by BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegStartCompression(), BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteCoefficients(), and BitMiracle.LibJpeg.Classic.JpegCompressStruct.JpegWriteTables().
Member Data Documentation
m_numWarnings
internal int BitMiracle.LibJpeg.Classic.JpegErrorMessage.m_numWarnings private
Definition at line 29 of file JpegErrorMessage.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage(), and BitMiracle.LibJpeg.Classic.JpegErrorMessage.ResetErrorMessage().
m_traceLevel
internal int BitMiracle.LibJpeg.Classic.JpegErrorMessage.m_traceLevel private
Definition at line 28 of file JpegErrorMessage.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegErrorMessage.EmitMessage().
msgCode
internal int BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgCode private
Definition at line 25 of file JpegErrorMessage.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegErrorMessage.FormatMessage(), BitMiracle.LibJpeg.Classic.JpegErrorMessage.ResetErrorMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
msgParam
internal object [] BitMiracle.LibJpeg.Classic.JpegErrorMessage.msgParam private
Definition at line 26 of file JpegErrorMessage.cs.
Referenced by BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.JpegErrorMessage.FormatMessage(), BitMiracle.LibJpeg.Classic.JpegCommonStruct.TraceMS(), and BitMiracle.LibJpeg.Classic.JpegCommonStruct.WarnMS().
NumWarnings
int BitMiracle.LibJpeg.Classic.JpegErrorMessage.NumWarnings => m_numWarnings
Gets the number of corrupt-data warnings.
The num_warnings.
For recoverable corrupt-data errors, we emit a warning message, but keep going unless emit_message chooses to abort. emit_message should count warnings in Num_warnings. The surrounding application can check for bad data by seeing if Num_warnings is nonzero at the end of processing.
Definition at line 62 of file JpegErrorMessage.cs.
Property Documentation
TraceLevel
int BitMiracle.LibJpeg.Classic.JpegErrorMessage.TraceLevel get set
Gets or sets the maximum message level that will be displayed.
Values are: -1: recoverable corrupt-data warning, may want to abort.
0: important advisory messages (always display to user).
1: first level of tracing detail.
2, 3, ...: successively more detailed tracing messages.
See also
JpegErrorMessage.EmitMessage
Definition at line 49 of file JpegErrorMessage.cs.
         {
             get { return m_traceLevel; }
             set { m_traceLevel = value; }
         }
Referenced by BitMiracle.LibJpeg.Jpeg.applyParameters().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/JpegErrorMessage.cs