Juniper: Juniper.MediaType.Image Class Reference
Juniper.MediaType.Image Class Reference
Public Member Functions
override bool Matches (string fileName)
bool Matches (FileInfo file)
string AddExtension (string fileName)
bool Equals (string other)
override bool Equals (object obj)
bool Equals (MediaType other)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static MediaType Parse (string value)
static IReadOnlyCollection< MediaType > ParseAll (string[] acceptTypes)
static bool TryParse (string value, out MediaType type)
static IReadOnlyList< MediaType > GuessByFileName (string fileName)
static IReadOnlyList< MediaType > GuessByFile (FileInfo file)
static MediaType Lookup (string value)
static ContentReference operator+ (string cacheID, MediaType contentType)
static implicit operator string (MediaType mediaType)
static bool operator== (MediaType left, MediaType right)
static bool operator== (MediaType left, string right)
static bool operator== (string left, MediaType right)
static bool operator != (MediaType left, MediaType right)
static bool operator != (MediaType left, string right)
static bool operator != (string left, MediaType right)
Static Public Attributes
static readonly Image AnyImage = new Image("*")
static readonly Image Aces = new Image("aces")
static readonly Image Avci = new Image("avci")
static readonly Image Avcs = new Image("avcs")
static readonly Image Bmp = new Image("bmp", new string[] { "bmp" })
static readonly Image Cgm = new Image("cgm", new string[] { "cgm" })
static readonly Image Dicom_Rle = new Image("dicom-rle")
static readonly Image Emf = new Image("emf")
static readonly Image Example = new Image("example")
static readonly Image EXR = new Image("x-exr", new string[] { "exr" })
static readonly Image Fits = new Image("fits")
static readonly Image G3fax = new Image("g3fax", new string[] { "g3" })
static readonly Image Gif = new Image("gif", new string[] { "gif" })
static readonly Image Heic = new Image("heic")
static readonly Image Heic_Sequence = new Image("heic-sequence")
static readonly Image Heif = new Image("heif")
static readonly Image Heif_Sequence = new Image("heif-sequence")
static readonly Image Hej2k = new Image("hej2k")
static readonly Image Hsj2 = new Image("hsj2")
static readonly Image Ief = new Image("ief", new string[] { "ief" })
static readonly Image Jls = new Image("jls")
static readonly Image Jp2 = new Image("jp2")
static readonly Image Jpeg = new Image("jpeg", new string[] { "jpeg", "jpg", "jpe" })
static readonly Image Jph = new Image("jph")
static readonly Image Jphc = new Image("jphc")
static readonly Image Jpm = new Image("jpm")
static readonly Image Jpx = new Image("jpx")
static readonly Image Jxr = new Image("jxr")
static readonly Image JxrA = new Image("jxra")
static readonly Image JxrS = new Image("jxrs")
static readonly Image Jxs = new Image("jxs")
static readonly Image Jxsc = new Image("jxsc")
static readonly Image Jxsi = new Image("jxsi")
static readonly Image Jxss = new Image("jxss")
static readonly Image Ktx = new Image("ktx", new string[] { "ktx" })
static readonly Image Naplps = new Image("naplps")
static readonly Image Png = new Image("png", new string[] { "png" })
static readonly Image PrsBtif = new Image("prs.btif", new string[] { "btif" })
static readonly Image PrsPti = new Image("prs.pti")
static readonly Image Pwg_Raster = new Image("pwg-raster")
static readonly Image Raw = new Image("x-raw", new string[] { "raw" })
static readonly Image Sgi = new Image("sgi", new string[] { "sgi" })
static readonly Image SvgXml = new Image("svg+xml", new string[] { "svg", "svgz" })
static readonly Image T38 = new Image("t38")
static readonly Image Tiff = new Image("tiff", new string[] { "tiff", "tif" })
static readonly Image Tiff_Fx = new Image("tiff-fx")
static readonly Image VendorAdobePhotoshop = new Image("vnd.adobe.photoshop", new string[] { "psd" })
static readonly Image VendorAirzipAcceleratorAzv = new Image("vnd.airzip.accelerator.azv")
static readonly Image VendorCnsInf2 = new Image("vnd.cns.inf2")
static readonly Image VendorDeceGraphic = new Image("vnd.dece.graphic", new string[] { "uvi", "uvvi", "uvg", "uvvg" })
static readonly Image VendorDjvu = new Image("vnd.djvu", new string[] { "djvu", "djv" })
static readonly Image VendorDvbSubtitle = new Image("vnd.dvb.subtitle", new string[] { "sub" })
static readonly Image VendorDwg = new Image("vnd.dwg", new string[] { "dwg" })
static readonly Image VendorDxf = new Image("vnd.dxf", new string[] { "dxf" })
static readonly Image VendorFastbidsheet = new Image("vnd.fastbidsheet", new string[] { "fbs" })
static readonly Image VendorFpx = new Image("vnd.fpx", new string[] { "fpx" })
static readonly Image VendorFst = new Image("vnd.fst", new string[] { "fst" })
static readonly Image VendorFujixeroxEdmics_Mmr = new Image("vnd.fujixerox.edmics-mmr", new string[] { "mmr" })
static readonly Image VendorFujixeroxEdmics_Rlc = new Image("vnd.fujixerox.edmics-rlc", new string[] { "rlc" })
static readonly Image VendorGlobalgraphicsPgb = new Image("vnd.globalgraphics.pgb")
static readonly Image VendorMicrosoftIcon = new Image("vnd.microsoft.icon")
static readonly Image VendorMix = new Image("vnd.mix")
static readonly Image VendorMozillaApng = new Image("vnd.mozilla.apng")
static readonly Image VendorMs_Modi = new Image("vnd.ms-modi", new string[] { "mdi" })
static readonly Image VendorMs_Photo = new Image("vnd.ms-photo", new string[] { "wdp" })
static readonly Image VendorNet_Fpx = new Image("vnd.net-fpx", new string[] { "npx" })
static readonly Image VendorRadiance = new Image("vnd.radiance")
static readonly Image VendorSealedmediaSoftsealGif = new Image("vnd.sealedmedia.softseal.gif")
static readonly Image VendorSealedmediaSoftsealJpg = new Image("vnd.sealedmedia.softseal.jpg")
static readonly Image VendorSealedPng = new Image("vnd.sealed.png")
static readonly Image VendorSvf = new Image("vnd.svf")
static readonly Image VendorTencentTap = new Image("vnd.tencent.tap")
static readonly Image VendorValveSourceTexture = new Image("vnd.valve.source.texture")
static readonly Image VendorWapWbmp = new Image("vnd.wap.wbmp", new string[] { "wbmp" })
static readonly Image VendorXiff = new Image("vnd.xiff", new string[] { "xif" })
static readonly Image VendorZbrushPcx = new Image("vnd.zbrush.pcx")
static readonly Image Webp = new Image("webp", new string[] { "webp" })
static readonly Image Wmf = new Image("wmf")
static readonly Image X_3ds = new Image("x-3ds", new string[] { "3ds" })
static readonly Image X_Cmu_Raster = new Image("x-cmu-raster", new string[] { "ras" })
static readonly Image X_Cmx = new Image("x-cmx", new string[] { "cmx" })
static readonly Image X_Emf = new Image("x-emf")
static readonly Image X_Freehand = new Image("x-freehand", new string[] { "fh", "fhc", "fh4", "fh5", "fh7" })
static readonly Image X_Icon = new Image("x-icon", new string[] { "ico" })
static readonly Image X_Mrsid_Image = new Image("x-mrsid-image", new string[] { "sid" })
static readonly Image X_Pcx = new Image("x-pcx", new string[] { "pcx" })
static readonly Image X_Pict = new Image("x-pict", new string[] { "pic", "pct" })
static readonly Image X_Portable_Anymap = new Image("x-portable-anymap", new string[] { "pnm" })
static readonly Image X_Portable_Bitmap = new Image("x-portable-bitmap", new string[] { "pbm" })
static readonly Image X_Portable_Graymap = new Image("x-portable-graymap", new string[] { "pgm" })
static readonly Image X_Portable_Pixmap = new Image("x-portable-pixmap", new string[] { "ppm" })
static readonly Image X_Rgb = new Image("x-rgb", new string[] { "rgb" })
static readonly Image X_Tga = new Image("x-tga", new string[] { "tga" })
static readonly Image X_Wmf = new Image("x-wmf")
static readonly Image X_Xbitmap = new Image("x-xbitmap", new string[] { "xbm" })
static readonly Image X_Xpixmap = new Image("x-xpixmap", new string[] { "xpm" })
static readonly Image X_Xwindowdump = new Image("x-xwindowdump", new string[] { "xwd" })
static new readonly Image [] Values
static readonly MediaType Any = new MediaType("*/*")
static readonly IReadOnlyCollection< MediaType > All = new MediaType[] { Any }
Properties
string Value [get]
string TypeName [get]
string SubTypeName [get]
float Weight [get]
ReadOnlyCollection< string > Extensions [get]
string PrimaryExtension [get]
Private Member Functions
Image (string value, string[] extensions)
Image (string value)
Detailed Description
Definition at line 7 of file Image.cs.
Constructor & Destructor Documentation
Image() [1/2]
Juniper.MediaType.Image.Image (string value, string [] extensions) inline private
Definition at line 9 of file Image.cs.
 : base("image/" + value, extensions) { }
Image() [2/2]
Juniper.MediaType.Image.Image (string value) inline private
Definition at line 11 of file Image.cs.
 : this(value, null) { }
Member Function Documentation
AddExtension()
string Juniper.MediaType.AddExtension (string fileName) inline inherited
Definition at line 310 of file MediaType.cs.
         {
             if (fileName is null)
             {
                 throw new ArgumentNullException(nameof(fileName));
             }
             if (PrimaryExtension is object)
             {
                 var currentExtension = PathExt.GetShortExtension(fileName);
                 if (Extensions.IndexOf(currentExtension) == -1)
                 {
                     fileName += "." + PrimaryExtension;
                 }
             }
             return fileName;
         }
References Juniper.MediaType.Extensions, System.IO.PathExt.GetShortExtension(), and Juniper.MediaType.PrimaryExtension.
Referenced by Juniper.IO.ZipFileCacheLayer.GetCacheFileName(), and Juniper.IO.ContentReference.operator string().
Equals() [1/3]
bool Juniper.MediaType.Equals (string other) inline inherited
Definition at line 329 of file MediaType.cs.
         {
             return TryParse(other, out var type)
                 && Equals(type);
         }
References Juniper.MediaType.TryParse().
Referenced by Juniper.MediaType.Equals().
Equals() [2/3]
override bool Juniper.MediaType.Equals (object obj) inline inherited
Definition at line 335 of file MediaType.cs.
         {
             return (obj is MediaType type && Equals(type))
                 || (obj is string str && Equals(str));
         }
References Juniper.MediaType.Equals().
Equals() [3/3]
bool Juniper.MediaType.Equals (MediaType other) inline inherited
Definition at line 341 of file MediaType.cs.
         {
             return other is object
                 && (TypeName == "*"
                     || other.TypeName == "*"
                     || TypeName == other.TypeName)
                 && (SubTypeName == "*"
                     || other.SubTypeName == "*"
                     || SubTypeName == other.SubTypeName);
         }
References Juniper.MediaType.SubTypeName, and Juniper.MediaType.TypeName.
GetHashCode()
override int Juniper.MediaType.GetHashCode () inline inherited
Definition at line 397 of file MediaType.cs.
         {
             var hashCode = -1006577490;
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(TypeName);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(SubTypeName);
             hashCode = (hashCode * -1521134295) + Weight.GetHashCode();
             hashCode = (hashCode * -1521134295) + EqualityComparer<ReadOnlyCollection<string>>.Default.GetHashCode(Extensions);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(PrimaryExtension);
             return hashCode;
         }
References Juniper.MediaType.Extensions, Juniper.MediaType.PrimaryExtension, Juniper.MediaType.SubTypeName, Juniper.MediaType.TypeName, and Juniper.MediaType.Weight.
GuessByFile()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFile (FileInfo file) inline static inherited
Definition at line 155 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return GuessByFileName(file.Name);
         }
References Juniper.MediaType.GuessByFileName().
Referenced by Juniper.HTTP.Server.HttpListenerResponseExt.SendFileAsync().
GuessByFileName()
static IReadOnlyList<MediaType> Juniper.MediaType.GuessByFileName (string fileName) inline static inherited
Definition at line 144 of file MediaType.cs.
         {
             if (string.IsNullOrEmpty(fileName))
             {
                 throw new ArgumentException("Must provide a valid fileName", nameof(fileName));
             }
             var ext = Path.GetExtension(fileName);
             return GuessByExtension(ref ext);
         }
References Juniper.MediaType.GuessByExtension().
Referenced by Juniper.MediaType.GuessByFile(), and Juniper.MediaType.Matches().
Lookup()
static MediaType Juniper.MediaType.Lookup (string value) inline static inherited
Definition at line 165 of file MediaType.cs.
         {
             // Trim off the weight, if one exists
             var parts = value.SplitX(';');
             if (parts.Length > 0)
             {
                 value = parts[0];
             }
             if (byValue.ContainsKey(value))
             {
                 return byValue[value];
             }
             var name = Array.Find(parts, p => p.Length > 0);
             if (string.IsNullOrEmpty(name))
             {
                 return Lookup("unknown/unknown");
             }
             else
             {
                 return new Unknown(name);
             }
         }
References Juniper.MediaType.byValue.
Matches() [1/2]
override bool Juniper.MediaType.Image.Matches (string fileName) inline virtual
Reimplemented from Juniper.MediaType.
Definition at line 15 of file Image.cs.
             {
                 if (ReferenceEquals(this, AnyImage))
                 {
                     return Values.Any(x => x.Matches(fileName));
                 }
                 else
                 {
                     return base.Matches(fileName);
                 }
             }
References Juniper.MediaType.Any, Juniper.MediaType.Image.AnyImage, Juniper.MediaType.Matches(), and Juniper.MediaType.Image.Values.
Matches() [2/2]
bool Juniper.MediaType.Matches (FileInfo file) inline inherited
Definition at line 300 of file MediaType.cs.
         {
             if (file is null)
             {
                 throw new ArgumentNullException(nameof(file));
             }
             return Matches(file.Name);
         }
References Juniper.MediaType.Matches().
operator !=() [1/3]
static bool Juniper.MediaType.operator != (MediaType left, MediaType right) inline static inherited
Definition at line 358 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [2/3]
static bool Juniper.MediaType.operator != (MediaType left, string right) inline static inherited
Definition at line 369 of file MediaType.cs.
         {
             return !(left == right);
         }
operator !=() [3/3]
static bool Juniper.MediaType.operator != (string left, MediaType right) inline static inherited
Definition at line 380 of file MediaType.cs.
         {
             return !(left == right);
         }
operator string()
static implicit Juniper.MediaType.operator string (MediaType mediaType) inline static inherited
Definition at line 196 of file MediaType.cs.
         {
             return mediaType?.ToString();
         }
operator+()
static ContentReference Juniper.MediaType.operator+ (string cacheID, MediaType contentType) inline static inherited
Definition at line 191 of file MediaType.cs.
         {
             return new ContentReference(cacheID, contentType);
         }
operator==() [1/3]
static bool Juniper.MediaType.operator== (MediaType left, MediaType right) inline static inherited
Definition at line 352 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [2/3]
static bool Juniper.MediaType.operator== (MediaType left, string right) inline static inherited
Definition at line 363 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (left is object && left.Equals(right));
         }
operator==() [3/3]
static bool Juniper.MediaType.operator== (string left, MediaType right) inline static inherited
Definition at line 374 of file MediaType.cs.
         {
             return (left is null && right is null)
                 || (right is object && right.Equals(left));
         }
Parse()
static MediaType Juniper.MediaType.Parse (string value) inline static inherited
Definition at line 40 of file MediaType.cs.
         {
             if (value is null)
             {
                 throw new ArgumentNullException(nameof(value));
             }
             if (TryParse(value, out var type))
             {
                 return type;
             }
             else
             {
                 throw new ArgumentException($"Type value does not match expected pattern {TYPE_PATTERN.ToString()}", nameof(value));
             }
         }
References Juniper.MediaType.TryParse().
ParseAll()
static IReadOnlyCollection<MediaType> Juniper.MediaType.ParseAll (string [] acceptTypes) inline static inherited
Definition at line 57 of file MediaType.cs.
         {
             if (acceptTypes is null || acceptTypes.Length == 0)
             {
                 return All;
             }
             else
             {
                 return InternalParseAll(acceptTypes).ToArray();
             }
         }
References Juniper.MediaType.All, and Juniper.MediaType.InternalParseAll().
Referenced by Juniper.HTTP.Server.Controllers.AbstractResponse.IsAcceptable().
ToString()
override string Juniper.MediaType.ToString () inline inherited
Definition at line 385 of file MediaType.cs.
         {
             if (Weight == 1)
             {
                 return Value;
             }
             else
             {
                 return weightedValue;
             }
         }
References Juniper.MediaType.Value, Juniper.MediaType.Weight, and Juniper.MediaType.weightedValue.
Referenced by Juniper.HTTP.Server.Controllers.StaticFileServer.ListDirectoryAsync().
TryParse()
static bool Juniper.MediaType.TryParse (string value, out MediaType type) inline static inherited
Definition at line 83 of file MediaType.cs.
         {
             type = null;
             if (value is null)
             {
                 return false;
             }
             var match = TYPE_PATTERN.Match(value);
             if (!match.Success)
             {
                 return false;
             }
             var typeName = match.Groups[1].Value;
             var subTypeName = match.Groups[2].Value;
             var rawValue = typeName + "/" + subTypeName;
             if (match.Groups.Count == 4
                 && float.TryParse(
                     match.Groups[3].Value,
                     NumberStyles.Integer | NumberStyles.AllowDecimalPoint,
                     CultureInfo.InvariantCulture,
                     out var weight))
             {
                 type = new MediaType(typeName, subTypeName, weight);
             }
             else if (byValue.ContainsKey(rawValue))
             {
                 type = byValue[rawValue];
             }
             else
             {
                 type = new MediaType(typeName, subTypeName);
             }
             return type is object;
         }
References Juniper.MediaType.byValue, Juniper.MediaType.MediaType(), and Juniper.MediaType.TYPE_PATTERN.
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.InternalParseAll(), Juniper.MediaType.Parse(), and Juniper.Processes.ProcessArgs.TryGetMediaType().
Member Data Documentation
Aces
readonly Image Juniper.MediaType.Image.Aces = new Image("aces") static
Definition at line 7 of file Image.Values.cs.
All
readonly IReadOnlyCollection<MediaType> Juniper.MediaType.All = new MediaType[] { Any } static inherited
Definition at line 38 of file MediaType.cs.
Referenced by Juniper.MediaType.ParseAll().
Any
readonly MediaType Juniper.MediaType.Any = new MediaType("*/*") static inherited
Definition at line 36 of file MediaType.cs.
Referenced by Juniper.MediaType.Application.Matches(), Juniper.MediaType.Audio.Matches(), Juniper.MediaType.Chemical.Matches(), Juniper.MediaType.Font.Matches(), Juniper.MediaType.Image.Matches(), Juniper.MediaType.Message.Matches(), Juniper.MediaType.Model.Matches(), Juniper.MediaType.Multipart.Matches(), Juniper.MediaType.Text.Matches(), Juniper.MediaType.Video.Matches(), and Juniper.MediaType.XConference.Matches().
AnyImage
readonly Image Juniper.MediaType.Image.AnyImage = new Image("*") static
Definition at line 13 of file Image.cs.
Referenced by Juniper.MediaType.Image.Matches(), and Juniper.HTTP.Server.HttpListenerResponseExt.SetFileName().
Avci
readonly Image Juniper.MediaType.Image.Avci = new Image("avci") static
Definition at line 8 of file Image.Values.cs.
Avcs
readonly Image Juniper.MediaType.Image.Avcs = new Image("avcs") static
Definition at line 9 of file Image.Values.cs.
Bmp
readonly Image Juniper.MediaType.Image.Bmp = new Image("bmp", new string[] { "bmp" }) static
Definition at line 10 of file Image.Values.cs.
Cgm
readonly Image Juniper.MediaType.Image.Cgm = new Image("cgm", new string[] { "cgm" }) static
Definition at line 11 of file Image.Values.cs.
Dicom_Rle
readonly Image Juniper.MediaType.Image.Dicom_Rle = new Image("dicom-rle") static
Definition at line 12 of file Image.Values.cs.
Emf
readonly Image Juniper.MediaType.Image.Emf = new Image("emf") static
Definition at line 13 of file Image.Values.cs.
Example
readonly Image Juniper.MediaType.Image.Example = new Image("example") static
Definition at line 14 of file Image.Values.cs.
EXR
readonly Image Juniper.MediaType.Image.EXR = new Image("x-exr", new string[] { "exr" }) static
Definition at line 15 of file Image.Values.cs.
Referenced by Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
Fits
readonly Image Juniper.MediaType.Image.Fits = new Image("fits") static
Definition at line 16 of file Image.Values.cs.
G3fax
readonly Image Juniper.MediaType.Image.G3fax = new Image("g3fax", new string[] { "g3" }) static
Definition at line 17 of file Image.Values.cs.
Gif
readonly Image Juniper.MediaType.Image.Gif = new Image("gif", new string[] { "gif" }) static
Definition at line 18 of file Image.Values.cs.
Heic
readonly Image Juniper.MediaType.Image.Heic = new Image("heic") static
Definition at line 19 of file Image.Values.cs.
Heic_Sequence
readonly Image Juniper.MediaType.Image.Heic_Sequence = new Image("heic-sequence") static
Definition at line 20 of file Image.Values.cs.
Heif
readonly Image Juniper.MediaType.Image.Heif = new Image("heif") static
Definition at line 21 of file Image.Values.cs.
Heif_Sequence
readonly Image Juniper.MediaType.Image.Heif_Sequence = new Image("heif-sequence") static
Definition at line 22 of file Image.Values.cs.
Hej2k
readonly Image Juniper.MediaType.Image.Hej2k = new Image("hej2k") static
Definition at line 23 of file Image.Values.cs.
Hsj2
readonly Image Juniper.MediaType.Image.Hsj2 = new Image("hsj2") static
Definition at line 24 of file Image.Values.cs.
Ief
readonly Image Juniper.MediaType.Image.Ief = new Image("ief", new string[] { "ief" }) static
Definition at line 25 of file Image.Values.cs.
Jls
readonly Image Juniper.MediaType.Image.Jls = new Image("jls") static
Definition at line 26 of file Image.Values.cs.
Jp2
readonly Image Juniper.MediaType.Image.Jp2 = new Image("jp2") static
Definition at line 27 of file Image.Values.cs.
Jpeg
readonly Image Juniper.MediaType.Image.Jpeg = new Image("jpeg", new string[] { "jpeg", "jpg", "jpe" }) static
Definition at line 28 of file Image.Values.cs.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake(), Juniper.Imaging.UnityTexture2DCodec.GetImageInfo(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
Jph
readonly Image Juniper.MediaType.Image.Jph = new Image("jph") static
Definition at line 29 of file Image.Values.cs.
Jphc
readonly Image Juniper.MediaType.Image.Jphc = new Image("jphc") static
Definition at line 30 of file Image.Values.cs.
Jpm
readonly Image Juniper.MediaType.Image.Jpm = new Image("jpm") static
Definition at line 31 of file Image.Values.cs.
Jpx
readonly Image Juniper.MediaType.Image.Jpx = new Image("jpx") static
Definition at line 32 of file Image.Values.cs.
Jxr
readonly Image Juniper.MediaType.Image.Jxr = new Image("jxr") static
Definition at line 33 of file Image.Values.cs.
JxrA
readonly Image Juniper.MediaType.Image.JxrA = new Image("jxra") static
Definition at line 34 of file Image.Values.cs.
JxrS
readonly Image Juniper.MediaType.Image.JxrS = new Image("jxrs") static
Definition at line 35 of file Image.Values.cs.
Jxs
readonly Image Juniper.MediaType.Image.Jxs = new Image("jxs") static
Definition at line 36 of file Image.Values.cs.
Jxsc
readonly Image Juniper.MediaType.Image.Jxsc = new Image("jxsc") static
Definition at line 37 of file Image.Values.cs.
Jxsi
readonly Image Juniper.MediaType.Image.Jxsi = new Image("jxsi") static
Definition at line 38 of file Image.Values.cs.
Jxss
readonly Image Juniper.MediaType.Image.Jxss = new Image("jxss") static
Definition at line 39 of file Image.Values.cs.
Ktx
readonly Image Juniper.MediaType.Image.Ktx = new Image("ktx", new string[] { "ktx" }) static
Definition at line 40 of file Image.Values.cs.
Naplps
readonly Image Juniper.MediaType.Image.Naplps = new Image("naplps") static
Definition at line 41 of file Image.Values.cs.
Png
readonly Image Juniper.MediaType.Image.Png = new Image("png", new string[] { "png" }) static
Definition at line 42 of file Image.Values.cs.
Referenced by Juniper.Imaging.UnityTexture2DCodec.GetImageInfo(), Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
PrsBtif
readonly Image Juniper.MediaType.Image.PrsBtif = new Image("prs.btif", new string[] { "btif" }) static
Definition at line 43 of file Image.Values.cs.
PrsPti
readonly Image Juniper.MediaType.Image.PrsPti = new Image("prs.pti") static
Definition at line 44 of file Image.Values.cs.
Pwg_Raster
readonly Image Juniper.MediaType.Image.Pwg_Raster = new Image("pwg-raster") static
Definition at line 45 of file Image.Values.cs.
Raw
readonly Image Juniper.MediaType.Image.Raw = new Image("x-raw", new string[] { "raw" }) static
Definition at line 46 of file Image.Values.cs.
Referenced by Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
Sgi
readonly Image Juniper.MediaType.Image.Sgi = new Image("sgi", new string[] { "sgi" }) static
Definition at line 47 of file Image.Values.cs.
SvgXml
readonly Image Juniper.MediaType.Image.SvgXml = new Image("svg+xml", new string[] { "svg", "svgz" }) static
Definition at line 48 of file Image.Values.cs.
T38
readonly Image Juniper.MediaType.Image.T38 = new Image("t38") static
Definition at line 49 of file Image.Values.cs.
Tiff
readonly Image Juniper.MediaType.Image.Tiff = new Image("tiff", new string[] { "tiff", "tif" }) static
Definition at line 50 of file Image.Values.cs.
Tiff_Fx
readonly Image Juniper.MediaType.Image.Tiff_Fx = new Image("tiff-fx") static
Definition at line 51 of file Image.Values.cs.
Values
new readonly Image [] Juniper.MediaType.Image.Values static
Definition at line 110 of file Image.Values.cs.
Referenced by Juniper.MediaType.Image.Matches().
VendorAdobePhotoshop
readonly Image Juniper.MediaType.Image.VendorAdobePhotoshop = new Image("vnd.adobe.photoshop", new string[] { "psd" }) static
Definition at line 52 of file Image.Values.cs.
VendorAirzipAcceleratorAzv
readonly Image Juniper.MediaType.Image.VendorAirzipAcceleratorAzv = new Image("vnd.airzip.accelerator.azv") static
Definition at line 53 of file Image.Values.cs.
VendorCnsInf2
readonly Image Juniper.MediaType.Image.VendorCnsInf2 = new Image("vnd.cns.inf2") static
Definition at line 54 of file Image.Values.cs.
VendorDeceGraphic
readonly Image Juniper.MediaType.Image.VendorDeceGraphic = new Image("vnd.dece.graphic", new string[] { "uvi", "uvvi", "uvg", "uvvg" }) static
Definition at line 55 of file Image.Values.cs.
VendorDjvu
readonly Image Juniper.MediaType.Image.VendorDjvu = new Image("vnd.djvu", new string[] { "djvu", "djv" }) static
Definition at line 56 of file Image.Values.cs.
VendorDvbSubtitle
readonly Image Juniper.MediaType.Image.VendorDvbSubtitle = new Image("vnd.dvb.subtitle", new string[] { "sub" }) static
Definition at line 57 of file Image.Values.cs.
VendorDwg
readonly Image Juniper.MediaType.Image.VendorDwg = new Image("vnd.dwg", new string[] { "dwg" }) static
Definition at line 58 of file Image.Values.cs.
VendorDxf
readonly Image Juniper.MediaType.Image.VendorDxf = new Image("vnd.dxf", new string[] { "dxf" }) static
Definition at line 59 of file Image.Values.cs.
VendorFastbidsheet
readonly Image Juniper.MediaType.Image.VendorFastbidsheet = new Image("vnd.fastbidsheet", new string[] { "fbs" }) static
Definition at line 60 of file Image.Values.cs.
VendorFpx
readonly Image Juniper.MediaType.Image.VendorFpx = new Image("vnd.fpx", new string[] { "fpx" }) static
Definition at line 61 of file Image.Values.cs.
VendorFst
readonly Image Juniper.MediaType.Image.VendorFst = new Image("vnd.fst", new string[] { "fst" }) static
Definition at line 62 of file Image.Values.cs.
VendorFujixeroxEdmics_Mmr
readonly Image Juniper.MediaType.Image.VendorFujixeroxEdmics_Mmr = new Image("vnd.fujixerox.edmics-mmr", new string[] { "mmr" }) static
Definition at line 63 of file Image.Values.cs.
VendorFujixeroxEdmics_Rlc
readonly Image Juniper.MediaType.Image.VendorFujixeroxEdmics_Rlc = new Image("vnd.fujixerox.edmics-rlc", new string[] { "rlc" }) static
Definition at line 64 of file Image.Values.cs.
VendorGlobalgraphicsPgb
readonly Image Juniper.MediaType.Image.VendorGlobalgraphicsPgb = new Image("vnd.globalgraphics.pgb") static
Definition at line 65 of file Image.Values.cs.
VendorMicrosoftIcon
readonly Image Juniper.MediaType.Image.VendorMicrosoftIcon = new Image("vnd.microsoft.icon") static
Definition at line 66 of file Image.Values.cs.
VendorMix
readonly Image Juniper.MediaType.Image.VendorMix = new Image("vnd.mix") static
Definition at line 67 of file Image.Values.cs.
VendorMozillaApng
readonly Image Juniper.MediaType.Image.VendorMozillaApng = new Image("vnd.mozilla.apng") static
Definition at line 68 of file Image.Values.cs.
VendorMs_Modi
readonly Image Juniper.MediaType.Image.VendorMs_Modi = new Image("vnd.ms-modi", new string[] { "mdi" }) static
Definition at line 69 of file Image.Values.cs.
VendorMs_Photo
readonly Image Juniper.MediaType.Image.VendorMs_Photo = new Image("vnd.ms-photo", new string[] { "wdp" }) static
Definition at line 70 of file Image.Values.cs.
VendorNet_Fpx
readonly Image Juniper.MediaType.Image.VendorNet_Fpx = new Image("vnd.net-fpx", new string[] { "npx" }) static
Definition at line 71 of file Image.Values.cs.
VendorRadiance
readonly Image Juniper.MediaType.Image.VendorRadiance = new Image("vnd.radiance") static
Definition at line 72 of file Image.Values.cs.
VendorSealedmediaSoftsealGif
readonly Image Juniper.MediaType.Image.VendorSealedmediaSoftsealGif = new Image("vnd.sealedmedia.softseal.gif") static
Definition at line 73 of file Image.Values.cs.
VendorSealedmediaSoftsealJpg
readonly Image Juniper.MediaType.Image.VendorSealedmediaSoftsealJpg = new Image("vnd.sealedmedia.softseal.jpg") static
Definition at line 74 of file Image.Values.cs.
VendorSealedPng
readonly Image Juniper.MediaType.Image.VendorSealedPng = new Image("vnd.sealed.png") static
Definition at line 75 of file Image.Values.cs.
VendorSvf
readonly Image Juniper.MediaType.Image.VendorSvf = new Image("vnd.svf") static
Definition at line 76 of file Image.Values.cs.
VendorTencentTap
readonly Image Juniper.MediaType.Image.VendorTencentTap = new Image("vnd.tencent.tap") static
Definition at line 77 of file Image.Values.cs.
VendorValveSourceTexture
readonly Image Juniper.MediaType.Image.VendorValveSourceTexture = new Image("vnd.valve.source.texture") static
Definition at line 78 of file Image.Values.cs.
VendorWapWbmp
readonly Image Juniper.MediaType.Image.VendorWapWbmp = new Image("vnd.wap.wbmp", new string[] { "wbmp" }) static
Definition at line 79 of file Image.Values.cs.
VendorXiff
readonly Image Juniper.MediaType.Image.VendorXiff = new Image("vnd.xiff", new string[] { "xif" }) static
Definition at line 80 of file Image.Values.cs.
VendorZbrushPcx
readonly Image Juniper.MediaType.Image.VendorZbrushPcx = new Image("vnd.zbrush.pcx") static
Definition at line 81 of file Image.Values.cs.
Webp
readonly Image Juniper.MediaType.Image.Webp = new Image("webp", new string[] { "webp" }) static
Definition at line 82 of file Image.Values.cs.
Wmf
readonly Image Juniper.MediaType.Image.Wmf = new Image("wmf") static
Definition at line 83 of file Image.Values.cs.
X_3ds
readonly Image Juniper.MediaType.Image.X_3ds = new Image("x-3ds", new string[] { "3ds" }) static
Definition at line 84 of file Image.Values.cs.
X_Cmu_Raster
readonly Image Juniper.MediaType.Image.X_Cmu_Raster = new Image("x-cmu-raster", new string[] { "ras" }) static
Definition at line 85 of file Image.Values.cs.
X_Cmx
readonly Image Juniper.MediaType.Image.X_Cmx = new Image("x-cmx", new string[] { "cmx" }) static
Definition at line 86 of file Image.Values.cs.
X_Emf
readonly Image Juniper.MediaType.Image.X_Emf = new Image("x-emf") static
Definition at line 89 of file Image.Values.cs.
X_Freehand
readonly Image Juniper.MediaType.Image.X_Freehand = new Image("x-freehand", new string[] { "fh", "fhc", "fh4", "fh5", "fh7" }) static
Definition at line 91 of file Image.Values.cs.
X_Icon
readonly Image Juniper.MediaType.Image.X_Icon = new Image("x-icon", new string[] { "ico" }) static
Definition at line 92 of file Image.Values.cs.
X_Mrsid_Image
readonly Image Juniper.MediaType.Image.X_Mrsid_Image = new Image("x-mrsid-image", new string[] { "sid" }) static
Definition at line 93 of file Image.Values.cs.
X_Pcx
readonly Image Juniper.MediaType.Image.X_Pcx = new Image("x-pcx", new string[] { "pcx" }) static
Definition at line 94 of file Image.Values.cs.
X_Pict
readonly Image Juniper.MediaType.Image.X_Pict = new Image("x-pict", new string[] { "pic", "pct" }) static
Definition at line 95 of file Image.Values.cs.
X_Portable_Anymap
readonly Image Juniper.MediaType.Image.X_Portable_Anymap = new Image("x-portable-anymap", new string[] { "pnm" }) static
Definition at line 96 of file Image.Values.cs.
X_Portable_Bitmap
readonly Image Juniper.MediaType.Image.X_Portable_Bitmap = new Image("x-portable-bitmap", new string[] { "pbm" }) static
Definition at line 97 of file Image.Values.cs.
X_Portable_Graymap
readonly Image Juniper.MediaType.Image.X_Portable_Graymap = new Image("x-portable-graymap", new string[] { "pgm" }) static
Definition at line 98 of file Image.Values.cs.
X_Portable_Pixmap
readonly Image Juniper.MediaType.Image.X_Portable_Pixmap = new Image("x-portable-pixmap", new string[] { "ppm" }) static
Definition at line 99 of file Image.Values.cs.
X_Rgb
readonly Image Juniper.MediaType.Image.X_Rgb = new Image("x-rgb", new string[] { "rgb" }) static
Definition at line 100 of file Image.Values.cs.
X_Tga
readonly Image Juniper.MediaType.Image.X_Tga = new Image("x-tga", new string[] { "tga" }) static
Definition at line 101 of file Image.Values.cs.
Referenced by Juniper.Imaging.UnityTexture2DCodec.MakeTexture(), Juniper.Imaging.UnityTexture2DCodec.Serialize(), and Juniper.Imaging.UnityTexture2DCodec.UnityTexture2DCodec().
X_Wmf
readonly Image Juniper.MediaType.Image.X_Wmf = new Image("x-wmf") static
Definition at line 104 of file Image.Values.cs.
X_Xbitmap
readonly Image Juniper.MediaType.Image.X_Xbitmap = new Image("x-xbitmap", new string[] { "xbm" }) static
Definition at line 106 of file Image.Values.cs.
X_Xpixmap
readonly Image Juniper.MediaType.Image.X_Xpixmap = new Image("x-xpixmap", new string[] { "xpm" }) static
Definition at line 107 of file Image.Values.cs.
X_Xwindowdump
readonly Image Juniper.MediaType.Image.X_Xwindowdump = new Image("x-xwindowdump", new string[] { "xwd" }) static
Definition at line 108 of file Image.Values.cs.
Property Documentation
Extensions
ReadOnlyCollection<string> Juniper.MediaType.Extensions get inherited
Definition at line 211 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.UpdateLookupTables().
PrimaryExtension
string Juniper.MediaType.PrimaryExtension get inherited
Definition at line 213 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.AddExtension(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
SubTypeName
string Juniper.MediaType.SubTypeName get inherited
Definition at line 207 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
TypeName
string Juniper.MediaType.TypeName get inherited
Definition at line 205 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.Equals(), Juniper.MediaType.GetHashCode(), and Juniper.MediaType.MediaType().
Value
string Juniper.MediaType.Value get inherited
Definition at line 203 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.MediaType(), Juniper.MediaType.ToString(), and Juniper.MediaType.UpdateLookupTables().
Weight
float Juniper.MediaType.Weight get inherited
Definition at line 209 of file MediaType.cs.
 { get; }
Referenced by Juniper.MediaType.GetHashCode(), Juniper.MediaType.MediaType(), and Juniper.MediaType.ToString().
The documentation for this class was generated from the following files:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Image.cs
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Image.Values.cs