Juniper: Juniper.IO.CachingStrategy Class Reference
Juniper.IO.CachingStrategy Class Reference
A collection of source and destination layers for file content. Files originate from source layers and get cached in destination layers. Caching occurs automatically when a file is retrieved from a source.
Public Member Functions
CachingStrategy ()
Creates an empty caching strategy. Add cache layers to it with AppendLayer(ICacheSourceLayer) or no caching will occur.
void Add (ICacheSourceLayer source)
Adds a layer to the caching strategy. Layers are checked in the order that they are added, so make sure to add the highest-latency cache layers last.
void Prepend (ICacheSourceLayer source)
Adds a layer to the caching strategy. Layers are checked in the order that they are added, so make sure to add the lowest-latency cache layers to the front of the list.
void AddBackup (ICacheDestinationLayer dest)
Adds a layer to the caching strategy. Layers are checked in the order that they are added, so make sure to add the highest-latency cache layers last.
bool GetSource< T > (out T layer)
Retrieve the first source layer of a given type.
bool GetDestination< T > (out T layer)
Retrieve the first destination layer of a given type.
Stream Create (ContentReference fileRef)
Creates a stream that will write to the first primary cache layer that supports writing the given content reference, and any secondary cache layers as well.
bool CanCache (ContentReference fileRef)
Returns true if any of the cache layers support writing streams. Currently, only the FileCacheLayer supports writing streams.
bool IsCached (ContentReference fileRef)
Checks to see if any of the cache layers contain the referenced file.
async Task< Stream > GetStreamAsync (ContentReference fileRef, IProgress prog)
Creates a stream reader reference for the first cache layer that contains the referenced file.
IEnumerable< ContentReference > GetContentReferences (MediaType ofType)
Retrieve all the content references that match the given type within the cache layer.
bool Delete (ContentReference fileRef)
Remove a file from all caching destinations.
IEnumerator< ICacheSourceLayer > GetEnumerator ()
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Private Attributes
readonly List< ICacheSourceLayer > sources = new List<ICacheSourceLayer>()
readonly List< ICacheDestinationLayer > destinations = new List<ICacheDestinationLayer>()
Detailed Description
A collection of source and destination layers for file content. Files originate from source layers and get cached in destination layers. Caching occurs automatically when a file is retrieved from a source.
Definition at line 14 of file CachingStrategy.cs.
Constructor & Destructor Documentation
CachingStrategy()
Juniper.IO.CachingStrategy.CachingStrategy () inline
Creates an empty caching strategy. Add cache layers to it with AppendLayer(ICacheSourceLayer) or no caching will occur.
Definition at line 25 of file CachingStrategy.cs.
         {
             sources.Add(new StreamSourceLayer(this));
         }
References Juniper.IO.CachingStrategy.sources.
Member Function Documentation
Add()
void Juniper.IO.CachingStrategy.Add (ICacheSourceLayer source) inline
Adds a layer to the caching strategy. Layers are checked in the order that they are added, so make sure to add the highest-latency cache layers last.
Parameters
source
Returns
Definition at line 37 of file CachingStrategy.cs.
         {
             sources.Insert(sources.Count - 1, source);
             if (source is ICacheDestinationLayer dest)
             {
                 destinations.Add(dest);
             }
         }
References Juniper.IO.CachingStrategy.destinations, and Juniper.IO.CachingStrategy.sources.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
AddBackup()
void Juniper.IO.CachingStrategy.AddBackup (ICacheDestinationLayer dest) inline
Adds a layer to the caching strategy. Layers are checked in the order that they are added, so make sure to add the highest-latency cache layers last.
Parameters
dest
Returns
Definition at line 71 of file CachingStrategy.cs.
         {
             sources.Insert(sources.Count - 1, dest);
         }
References Juniper.IO.CachingStrategy.sources.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Awake().
CanCache()
bool Juniper.IO.CachingStrategy.CanCache (ContentReference fileRef) inline
Returns true if any of the cache layers support writing streams. Currently, only the FileCacheLayer supports writing streams.
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 146 of file CachingStrategy.cs.
         {
             foreach (var dest in destinations)
             {
                 if (dest.CanCache(fileRef))
                 {
                     return true;
                 }
             }
             return false;
         }
References Juniper.IO.CachingStrategy.destinations.
Referenced by Juniper.IO.StreamSourceLayer.GetStreamAsync().
Create()
Stream Juniper.IO.CachingStrategy.Create (ContentReference fileRef) inline
Creates a stream that will write to the first primary cache layer that supports writing the given content reference, and any secondary cache layers as well.
Exceptions
InvalidOperationException If no primary cache layer could be found.
Template Parameters
MediaTypeT
Parameters
fileRef
Returns
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 128 of file CachingStrategy.cs.
         {
             foreach (var dest in destinations)
             {
                 if (dest.CanCache(fileRef))
                 {
                     return dest.Create(fileRef);
                 }
             }
             throw new InvalidOperationException("Could not cache the file " + fileRef);
         }
References Juniper.IO.CachingStrategy.destinations.
Referenced by Juniper.IO.StreamSourceLayer.GetStreamAsync().
Delete()
bool Juniper.IO.CachingStrategy.Delete (ContentReference fileRef) inline
Remove a file from all caching destinations.
Parameters
fileRef
Returns
True, if any content was deleted. False, if the file was not found.
Implements Juniper.IO.ICacheDestinationLayer.
Definition at line 227 of file CachingStrategy.cs.
         {
             var anyDelete = false;
             foreach (var dest in destinations)
             {
                 anyDelete |= dest.Delete(fileRef);
             }
             return anyDelete;
         }
References Juniper.IO.CachingStrategy.destinations.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), and Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.LoadAsync< T >().
GetContentReferences()
IEnumerable<ContentReference> Juniper.IO.CachingStrategy.GetContentReferences (MediaType ofType) inline
Retrieve all the content references that match the given type within the cache layer.
Parameters
ofType
Returns
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 211 of file CachingStrategy.cs.
         {
             foreach (var source in sources)
             {
                 foreach (var fileRef in source.GetContentReferences(ofType))
                 {
                     yield return fileRef;
                 }
             }
         }
References Juniper.IO.CachingStrategy.sources.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient().
GetDestination< T >()
bool Juniper.IO.CachingStrategy.GetDestination< T > (out T layer) inline
Retrieve the first destination layer of a given type.
Template Parameters
T
Parameters
layer
Returns
Type Constraints
T : ICacheDestinationLayer
Definition at line 104 of file CachingStrategy.cs.
                     : ICacheDestinationLayer
         {
             layer = default;
             foreach (var dest in destinations)
             {
                 if (dest is T t)
                 {
                     layer = t;
                     return true;
                 }
             }
             return false;
         }
References Juniper.IO.CachingStrategy.destinations.
GetEnumerator() [1/2]
IEnumerator<ICacheSourceLayer> Juniper.IO.CachingStrategy.GetEnumerator () inline
Definition at line 238 of file CachingStrategy.cs.
         {
             return ((IEnumerable<ICacheSourceLayer>)destinations).GetEnumerator();
         }
References Juniper.IO.CachingStrategy.destinations.
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.IO.CachingStrategy.GetEnumerator () inline private
Definition at line 243 of file CachingStrategy.cs.
         {
             return ((IEnumerable<ICacheSourceLayer>)destinations).GetEnumerator();
         }
References Juniper.IO.CachingStrategy.destinations.
GetSource< T >()
bool Juniper.IO.CachingStrategy.GetSource< T > (out T layer) inline
Retrieve the first source layer of a given type.
Template Parameters
T
Parameters
layer
Returns
Type Constraints
T : ICacheSourceLayer
Definition at line 82 of file CachingStrategy.cs.
                     : ICacheSourceLayer
         {
             layer = default;
             foreach (var source in sources)
             {
                 if (source is T t)
                 {
                     layer = t;
                     return true;
                 }
             }
             return false;
         }
References Juniper.IO.CachingStrategy.sources.
GetStreamAsync()
async Task<Stream> Juniper.IO.CachingStrategy.GetStreamAsync (ContentReference fileRef, IProgress prog) inline
Creates a stream reader reference for the first cache layer that contains the referenced file.
Template Parameters
MediaTypeT
Parameters
fileRef
Returns
Null, if the file does not exist in the cache
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 185 of file CachingStrategy.cs.
         {
             if (fileRef is null)
             {
                 throw new ArgumentNullException(nameof(fileRef));
             }
             foreach (var source in sources)
             {
                 if (source.IsCached(fileRef))
                 {
                     return await source
                         .GetStreamAsync(fileRef, prog)
                         .ConfigureAwait(false);
                 }
             }
             throw new FileNotFoundException("Could not find file " + fileRef, fileRef.FileName);
         }
References Juniper.IO.CachingStrategy.sources.
Referenced by Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GetImageAsync().
IsCached()
bool Juniper.IO.CachingStrategy.IsCached (ContentReference fileRef) inline
Checks to see if any of the cache layers contain the referenced file.
Template Parameters
MediaTypeT
Parameters
fileRef
Returns
False, if none of the cache layers contain the file
Implements Juniper.IO.ICacheSourceLayer.
Definition at line 165 of file CachingStrategy.cs.
         {
             foreach (var source in sources)
             {
                 if (source.IsCached(fileRef))
                 {
                     return true;
                 }
             }
             return false;
         }
References Juniper.IO.CachingStrategy.sources.
Referenced by Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.CaptureCubemap(), Juniper.Speech.Azure.CognitiveServices.TextToSpeechStreamClient.GetAudioDataStreamAsync(), Juniper.Speech.Azure.CognitiveServices.VoicesClient.GetVoicesAsync(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.GoogleMapsClient(), Juniper.World.GIS.Google.GoogleMapsClient< MetadataTypeT >.LoadAsync< T >(), Juniper.Imaging.PhotosphereManager.Photo_CheckIsCubemapAvailable(), and Juniper.World.GIS.Google.AbstractGoogleStreetView< MetadataResponse >.Photosphere_CubemapNeeded().
Prepend()
void Juniper.IO.CachingStrategy.Prepend (ICacheSourceLayer source) inline
Adds a layer to the caching strategy. Layers are checked in the order that they are added, so make sure to add the lowest-latency cache layers to the front of the list.
Parameters
source
Returns
Definition at line 54 of file CachingStrategy.cs.
         {
             sources.Insert(0, source);
             if (source is ICacheDestinationLayer dest)
             {
                 destinations.Insert(0, dest);
             }
         }
References Juniper.IO.CachingStrategy.destinations, and Juniper.IO.CachingStrategy.sources.
Member Data Documentation
destinations
readonly List<ICacheDestinationLayer> Juniper.IO.CachingStrategy.destinations = new List<ICacheDestinationLayer>() private
Definition at line 19 of file CachingStrategy.cs.
Referenced by Juniper.IO.CachingStrategy.Add(), Juniper.IO.CachingStrategy.CanCache(), Juniper.IO.CachingStrategy.Create(), Juniper.IO.CachingStrategy.Delete(), Juniper.IO.CachingStrategy.GetDestination< T >(), Juniper.IO.CachingStrategy.GetEnumerator(), and Juniper.IO.CachingStrategy.Prepend().
sources
readonly List<ICacheSourceLayer> Juniper.IO.CachingStrategy.sources = new List<ICacheSourceLayer>() private
Definition at line 18 of file CachingStrategy.cs.
Referenced by Juniper.IO.CachingStrategy.Add(), Juniper.IO.CachingStrategy.AddBackup(), Juniper.IO.CachingStrategy.CachingStrategy(), Juniper.IO.CachingStrategy.GetContentReferences(), Juniper.IO.CachingStrategy.GetSource< T >(), Juniper.IO.CachingStrategy.GetStreamAsync(), Juniper.IO.CachingStrategy.IsCached(), and Juniper.IO.CachingStrategy.Prepend().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/IO/CachingStrategy.cs