Juniper: BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct Class Reference
BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct Class Reference
Classes
class DivisorTable
Public Member Functions
delegate void ForwardDctDelegate (JpegComponentInfo compptr, byte[][] sample_data, JBlock[] coef_blocks, int start_row, int start_col, int num_blocks)
JpegForwardDct (JpegCompressStruct cinfo)
virtual void StartPass ()
Initialize for a processing pass. Verify that all referenced Q-tables are present, and set up the divisor table for each one. In the current implementation, DCT of all components is done during the first pass, even if only some components will be output in the first scan. Hence all components should be examined here.
Public Attributes
ForwardDctDelegate [] forward_DCT = new ForwardDctDelegate[JpegConstants.MAX_COMPONENTS]
Private Member Functions
delegate void ForwardDctMethodDelegate (int[] data, byte[][] sample_data, int start_row, int start_col)
delegate void FloatDctMethodDelegate (float[] data, byte[][] sample_data, int start_row, int start_col)
void ForwardDctImpl (JpegComponentInfo compptr, byte[][] sample_data, JBlock[] coef_blocks, int start_row, int start_col, int num_blocks)
void ForwardDctFloatImpl (JpegComponentInfo compptr, byte[][] sample_data, JBlock[] coef_blocks, int start_row, int start_col, int num_blocks)
void JpegForwardDct1x1 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct2x2 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct3x3 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct4x4 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct5x5 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct6x6 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct7x7 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct9x9 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct10x10 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct11x11 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct12x12 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct13x13 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct14x14 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct15x15 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct16x16 (int[] data1, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct16x8 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct14x7 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct12x6 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct10x5 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct8x4 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct6x3 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct4x2 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct2x1 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct8x16 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct7x14 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct6x12 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct5x10 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct4x8 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct3x6 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct2x4 (int[] data, byte[][] sample_data, int start_row, int start_col)
void JpegForwardDct1x2 (int[] data, byte[][] sample_data, int start_row, int start_col)
Static Private Member Functions
static void JpegForwardDctFloat (float[] data, byte[][] sample_data, int start_row, int start_col)
static void JpegForwardDctIFast (int[] data, byte[][] sample_data, int start_row, int start_col)
static void JpegForwardDctISlow (int[] data, byte[][] sample_data, int start_row, int start_col)
static int FastIntegerMultiply (int var, int c)
Multiply a DCTELEM variable by an int constant, and immediately descale to yield a DCTELEM result.
static int SlowIntegerFix (double x)
Private Attributes
const int FAST_INTEGER_CONST_BITS = 8
const int FAST_INTEGER_FIX_0_382683433 = 98
const int FAST_INTEGER_FIX_0_541196100 = 139
const int FAST_INTEGER_FIX_0_707106781 = 181
const int FAST_INTEGER_FIX_1_306562965 = 334
const int SLOW_INTEGER_CONST_BITS = 13
const int SLOW_INTEGER_PASS1_BITS = 2
const int SLOW_INTEGER_FIX_0_298631336 = 2446
const int SLOW_INTEGER_FIX_0_390180644 = 3196
const int SLOW_INTEGER_FIX_0_541196100 = 4433
const int SLOW_INTEGER_FIX_0_765366865 = 6270
const int SLOW_INTEGER_FIX_0_899976223 = 7373
const int SLOW_INTEGER_FIX_1_175875602 = 9633
const int SLOW_INTEGER_FIX_1_501321110 = 12299
const int SLOW_INTEGER_FIX_1_847759065 = 15137
const int SLOW_INTEGER_FIX_1_961570560 = 16069
const int SLOW_INTEGER_FIX_2_053119869 = 16819
const int SLOW_INTEGER_FIX_2_562915447 = 20995
const int SLOW_INTEGER_FIX_3_072711026 = 25172
const int CONST_BITS = 14
readonly JpegCompressStruct m_cinfo
readonly ForwardDctMethodDelegate [] do_dct = new ForwardDctMethodDelegate[JpegConstants.MAX_COMPONENTS]
readonly FloatDctMethodDelegate [] do_float_dct = new FloatDctMethodDelegate[JpegConstants.MAX_COMPONENTS]
readonly DivisorTable [] m_dctTables
Static Private Attributes
static readonly short [] aanscales
static readonly double [] aanscalefactor
Detailed Description
Forward DCT (also controls coefficient quantization)
A forward DCT routine is given a pointer to an input sample array and a pointer to a work area of type DCTELEM[]; the DCT is to be performed in-place in that buffer. Type DCTELEM is int for 8-bit samples, INT32 for 12-bit samples. (NOTE: Floating-point DCT implementations use an array of type FAST_FLOAT, instead.) The input data is to be fetched from the sample array starting at a specified column. (Any row offset needed will be applied to the array pointer before it is passed to the FDCT code.) Note that the number of samples fetched by the FDCT routine is DCT_h_scaled_size * DCT_v_scaled_size. The DCT outputs are returned scaled up by a factor of 8; they therefore have a range of +-8K for 8-bit data, +-128K for 12-bit data. This convention improves accuracy in integer implementations and saves some work in floating-point ones.
Each IDCT routine has its own ideas about the best dct_table element type.
Definition at line 30 of file JpegForwardDct.cs.
Constructor & Destructor Documentation
JpegForwardDct()
BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct (JpegCompressStruct cinfo) inline
Definition at line 139 of file JpegForwardDct.cs.
         {
             m_cinfo = cinfo;
             m_dctTables = new DivisorTable[m_cinfo.m_num_components];
             for (var ci = 0; ci < m_cinfo.m_num_components; ci++)
             {
                 /* Allocate a divisor table for each component */
                 m_dctTables[ci] = new DivisorTable();
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_dctTables, and BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components.
Member Function Documentation
FastIntegerMultiply()
static int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FastIntegerMultiply (int var, int c) inline static private
Multiply a DCTELEM variable by an int constant, and immediately descale to yield a DCTELEM result.
Definition at line 988 of file JpegForwardDct.cs.
         {
 #if !USE_ACCURATE_ROUNDING
             return JpegUtils.RIGHT_SHIFT(var * c, FAST_INTEGER_CONST_BITS);
 #else
             return JpegUtils.DESCALE(var * c, FAST_INTEGER_CONST_BITS);
 #endif
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegUtils.DESCALE(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_CONST_BITS, and BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctIFast().
FloatDctMethodDelegate()
delegate void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FloatDctMethodDelegate (float [] data, byte sample_data[][], int start_row, int start_col) private
ForwardDctDelegate()
delegate void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctDelegate (JpegComponentInfo compptr, byte sample_data[][], JBlock [] coef_blocks, int start_row, int start_col, int num_blocks)
Perform forward DCT on one or more blocks of a component.
The input samples are taken from the sample_data[] array starting at position start_row/start_col, and moving to the right for any additional blocks. The quantized coefficients are returned in coef_blocks[].
ForwardDctFloatImpl()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctFloatImpl (JpegComponentInfo compptr, byte sample_data[][], JBlock [] coef_blocks, int start_row, int start_col, int num_blocks) inline private
Definition at line 430 of file JpegForwardDct.cs.
         {
             /* This routine is heavily used, so it's worth coding it tightly. */
             var do_dct = do_float_dct[compptr.Component_index];
             var divisors = m_dctTables[compptr.Component_index].float_array;
             var workspace = new float[JpegConstants.DCTSIZE2]; /* work area for FDCT subroutine */
             for (var bi = 0; bi < num_blocks; bi++, start_col += compptr.DCT_h_scaled_size)
             {
                 /* Perform the DCT */
                 do_dct(workspace, sample_data, start_row, start_col);
                 /* Quantize/descale the coefficients, and store into coef_blocks[] */
                 for (var i = 0; i < JpegConstants.DCTSIZE2; i++)
                 {
                     /* Apply the quantization and scaling factor */
                     var temp = workspace[i] * divisors[i];
                     /* Round to nearest integer.
                      * Since C does not specify the direction of rounding for negative
                      * quotients, we have to force the dividend positive for portability.
                      * The maximum coefficient size is +-16K (for 12-bit data), so this
                      * code should work for either 16-bit or 32-bit ints.
                      */
                     coef_blocks[bi][i] = (short)((int)(temp + (float)16384.5) - 16384);
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_index, BitMiracle.LibJpeg.Classic.JpegComponentInfo.DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.do_dct, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.do_float_dct, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.DivisorTable.float_array, and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_dctTables.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
ForwardDctImpl()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctImpl (JpegComponentInfo compptr, byte sample_data[][], JBlock [] coef_blocks, int start_row, int start_col, int num_blocks) inline private
Definition at line 377 of file JpegForwardDct.cs.
         {
             /* This routine is heavily used, so it's worth coding it tightly. */
             var do_dct = this.do_dct[compptr.Component_index];
             var divisors = m_dctTables[compptr.Component_index].int_array;
             var workspace = new int[JpegConstants.DCTSIZE2];    /* work area for FDCT subroutine */
             for (var bi = 0; bi < num_blocks; bi++, start_col += compptr.DCT_h_scaled_size)
             {
                 /* Perform the DCT */
                 do_dct(workspace, sample_data, start_row, start_col);
                 /* Quantize/descale the coefficients, and store into coef_blocks[] */
                 for (var i = 0; i < JpegConstants.DCTSIZE2; i++)
                 {
                     var qval = divisors[i];
                     var temp = workspace[i];
                     if (temp < 0)
                     {
                         temp = -temp;
                         temp += qval >> 1;  /* for rounding */
                         if (temp >= qval)
{
                             temp /= qval;
                         }
                         else
{
                             temp = 0;
                         }
                         temp = -temp;
                     }
                     else
                     {
                         temp += qval >> 1;  /* for rounding */
                         if (temp >= qval)
{
                             temp /= qval;
                         }
                         else
{
                             temp = 0;
                         }
                     }
                     coef_blocks[bi][i] = (short)temp;
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.JpegComponentInfo.Component_index, BitMiracle.LibJpeg.Classic.JpegComponentInfo.DCT_h_scaled_size, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.do_dct, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.DivisorTable.int_array, and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_dctTables.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
ForwardDctMethodDelegate()
delegate void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctMethodDelegate (int [] data, byte sample_data[][], int start_row, int start_col) private
JpegForwardDct10x10()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x10 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1042 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct10x5()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x5 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1301 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct11x11()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct11x11 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1047 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct12x12()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x12 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1052 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct12x6()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x6 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1296 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct13x13()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct13x13 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1057 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct14x14()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x14 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1062 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct14x7()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x7 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1291 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct15x15()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct15x15 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1067 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct16x16()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x16 (int [] data1, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1075 of file JpegForwardDct.cs.
         {
             /* Pass 1: process rows.
              * Note results are scaled up by sqrt(8) compared to a true DCT;
              * furthermore, we scale the results by 2**PASS1_BITS.
              * cK represents sqrt(2) * cos(K*pi/32).
              */
             var workspace = new int[JpegConstants.DCTSIZE2];
             var dataIndex = 0;
             var data = data1;
             var ctr = 0;
             for (; ; )
             {
                 var elem = sample_data[start_row + ctr];
                 var elemIndex = start_col;
                 /* Even part */
                 var tmp0 = elem[elemIndex + 0] + elem[elemIndex + 15];
                 var tmp1 = elem[elemIndex + 1] + elem[elemIndex + 14];
                 var tmp2 = elem[elemIndex + 2] + elem[elemIndex + 13];
                 var tmp3 = elem[elemIndex + 3] + elem[elemIndex + 12];
                 var tmp4 = elem[elemIndex + 4] + elem[elemIndex + 11];
                 var tmp5 = elem[elemIndex + 5] + elem[elemIndex + 10];
                 var tmp6 = elem[elemIndex + 6] + elem[elemIndex + 9];
                 var tmp7 = elem[elemIndex + 7] + elem[elemIndex + 8];
                 var tmp10 = tmp0 + tmp7;
                 var tmp14 = tmp0 - tmp7;
                 var tmp11 = tmp1 + tmp6;
                 var tmp15 = tmp1 - tmp6;
                 var tmp12 = tmp2 + tmp5;
                 var tmp16 = tmp2 - tmp5;
                 var tmp13 = tmp3 + tmp4;
                 var tmp17 = tmp3 - tmp4;
                 tmp0 = elem[elemIndex + 0] - elem[elemIndex + 15];
                 tmp1 = elem[elemIndex + 1] - elem[elemIndex + 14];
                 tmp2 = elem[elemIndex + 2] - elem[elemIndex + 13];
                 tmp3 = elem[elemIndex + 3] - elem[elemIndex + 12];
                 tmp4 = elem[elemIndex + 4] - elem[elemIndex + 11];
                 tmp5 = elem[elemIndex + 5] - elem[elemIndex + 10];
                 tmp6 = elem[elemIndex + 6] - elem[elemIndex + 9];
                 tmp7 = elem[elemIndex + 7] - elem[elemIndex + 8];
                 /* Apply unsigned->signed conversion. */
                 data[dataIndex + 0] =
                   ((tmp10 + tmp11 + tmp12 + tmp13 - (16 * JpegConstants.CENTERJSAMPLE)) << SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 4] =
                   JpegUtils.DESCALE(
                       ((tmp10 - tmp13) * SlowIntegerFix(1.306562965)) + /* c4[16] = c2[8] */
                       ((tmp11 - tmp12) * SLOW_INTEGER_FIX_0_541196100),   /* c12[16] = c6[8] */
                       SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 tmp10 = ((tmp17 - tmp15) * SlowIntegerFix(0.275899379)) +   /* c14[16] = c7[8] */
                     ((tmp14 - tmp16) * SlowIntegerFix(1.387039845));    /* c2[16] = c1[8] */
                 data[dataIndex + 2] = JpegUtils.DESCALE(
                     tmp10 + (tmp15 * SlowIntegerFix(1.451774982))   /* c6+c14 */
                     + (tmp16 * SlowIntegerFix(2.172734804)),        /* c2+c10 */
                     SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 6] = JpegUtils.DESCALE(
                     tmp10 - (tmp14 * SlowIntegerFix(0.211164243))   /* c2-c6 */
                     - (tmp17 * SlowIntegerFix(1.061594338)),        /* c10+c14 */
                     SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 /* Odd part */
                 tmp11 = ((tmp0 + tmp1) * SlowIntegerFix(1.353318001)) +         /* c3 */
                     ((tmp6 - tmp7) * SlowIntegerFix(0.410524528));          /* c13 */
                 tmp12 = ((tmp0 + tmp2) * SlowIntegerFix(1.247225013)) +         /* c5 */
                     ((tmp5 + tmp7) * SlowIntegerFix(0.666655658));          /* c11 */
                 tmp13 = ((tmp0 + tmp3) * SlowIntegerFix(1.093201867)) +         /* c7 */
                     ((tmp4 - tmp7) * SlowIntegerFix(0.897167586));          /* c9 */
                 tmp14 = ((tmp1 + tmp2) * SlowIntegerFix(0.138617169)) +         /* c15 */
                     ((tmp6 - tmp5) * SlowIntegerFix(1.407403738));          /* c1 */
                 tmp15 = ((tmp1 + tmp3) * -SlowIntegerFix(0.666655658)) +       /* -c11 */
                     ((tmp4 + tmp6) * -SlowIntegerFix(1.247225013));        /* -c5 */
                 tmp16 = ((tmp2 + tmp3) * -SlowIntegerFix(1.353318001)) +       /* -c3 */
                     ((tmp5 - tmp4) * SlowIntegerFix(0.410524528));          /* c13 */
                 tmp10 = tmp11 + tmp12 + tmp13 -
                     (tmp0 * SlowIntegerFix(2.286341144)) +                /* c7+c5+c3-c1 */
                     (tmp7 * SlowIntegerFix(0.779653625));                 /* c15+c13-c11+c9 */
                 tmp11 += tmp14 + tmp15 + (tmp1 * SlowIntegerFix(0.071888074)) /* c9-c3-c15+c11 */
                      - (tmp6 * SlowIntegerFix(1.663905119));              /* c7+c13+c1-c5 */
                 tmp12 += tmp14 + tmp16 - (tmp2 * SlowIntegerFix(1.125726048)) /* c7+c5+c15-c3 */
                      + (tmp5 * SlowIntegerFix(1.227391138));              /* c9-c11+c1-c13 */
                 tmp13 += tmp15 + tmp16 + (tmp3 * SlowIntegerFix(1.065388962)) /* c15+c3+c11-c7 */
                      + (tmp4 * SlowIntegerFix(2.167985692));              /* c1+c13+c5-c9 */
                 data[dataIndex + 1] = JpegUtils.DESCALE(tmp10, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 3] = JpegUtils.DESCALE(tmp11, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 5] = JpegUtils.DESCALE(tmp12, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 7] = JpegUtils.DESCALE(tmp13, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 ctr++;
                 if (ctr != JpegConstants.DCTSIZE)
                 {
                     if (ctr == JpegConstants.DCTSIZE * 2)
                     {
                         /* Done. */
                         break;
                     }
                     /* advance pointer to next row */
                     dataIndex += JpegConstants.DCTSIZE;
                 }
                 else
                 {
                     /* switch pointer to extended workspace */
                     data = workspace;
                     dataIndex = 0;
                 }
             }
             /* Pass 2: process columns.
              * We remove the PASS1_BITS scaling, but leave the results scaled up
              * by an overall factor of 8.
              * We must also scale the output by (8/16)**2 = 1/2**2.
              * cK represents sqrt(2) * cos(K*pi/32).
              */
             data = data1;
             dataIndex = 0;
             var workspaceIndex = 0;
             for (ctr = JpegConstants.DCTSIZE - 1; ctr >= 0; ctr--)
             {
                 /* Even part */
                 var tmp0 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 7)];
                 var tmp1 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 6)];
                 var tmp2 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 5)];
                 var tmp3 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 4)];
                 var tmp4 = data[dataIndex + (JpegConstants.DCTSIZE * 4)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 3)];
                 var tmp5 = data[dataIndex + (JpegConstants.DCTSIZE * 5)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 2)];
                 var tmp6 = data[dataIndex + (JpegConstants.DCTSIZE * 6)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 1)];
                 var tmp7 = data[dataIndex + (JpegConstants.DCTSIZE * 7)] + workspace[workspaceIndex + (JpegConstants.DCTSIZE * 0)];
                 var tmp10 = tmp0 + tmp7;
                 var tmp14 = tmp0 - tmp7;
                 var tmp11 = tmp1 + tmp6;
                 var tmp15 = tmp1 - tmp6;
                 var tmp12 = tmp2 + tmp5;
                 var tmp16 = tmp2 - tmp5;
                 var tmp13 = tmp3 + tmp4;
                 var tmp17 = tmp3 - tmp4;
                 tmp0 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 7)];
                 tmp1 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 6)];
                 tmp2 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 5)];
                 tmp3 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 4)];
                 tmp4 = data[dataIndex + (JpegConstants.DCTSIZE * 4)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 3)];
                 tmp5 = data[dataIndex + (JpegConstants.DCTSIZE * 5)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 2)];
                 tmp6 = data[dataIndex + (JpegConstants.DCTSIZE * 6)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 1)];
                 tmp7 = data[dataIndex + (JpegConstants.DCTSIZE * 7)] - workspace[workspaceIndex + (JpegConstants.DCTSIZE * 0)];
                 data[dataIndex + (JpegConstants.DCTSIZE * 0)] =
                   JpegUtils.DESCALE(tmp10 + tmp11 + tmp12 + tmp13, SLOW_INTEGER_PASS1_BITS + 2);
                 data[dataIndex + (JpegConstants.DCTSIZE * 4)] =
                   JpegUtils.DESCALE(((tmp10 - tmp13) * SlowIntegerFix(1.306562965)) + /* c4[16] = c2[8] */
                       ((tmp11 - tmp12) * SLOW_INTEGER_FIX_0_541196100),   /* c12[16] = c6[8] */
                       SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS + 2);
                 tmp10 = ((tmp17 - tmp15) * SlowIntegerFix(0.275899379)) +   /* c14[16] = c7[8] */
                     ((tmp14 - tmp16) * SlowIntegerFix(1.387039845));    /* c2[16] = c1[8] */
                 data[dataIndex + (JpegConstants.DCTSIZE * 2)] =
                   JpegUtils.DESCALE(tmp10 + (tmp15 * SlowIntegerFix(1.451774982))   /* c6+c14 */
                       + (tmp16 * SlowIntegerFix(2.172734804)),        /* c2+10 */
                       SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS + 2);
                 data[dataIndex + (JpegConstants.DCTSIZE * 6)] =
                   JpegUtils.DESCALE(tmp10 - (tmp14 * SlowIntegerFix(0.211164243))   /* c2-c6 */
                       - (tmp17 * SlowIntegerFix(1.061594338)),        /* c10+c14 */
                       SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS + 2);
                 /* Odd part */
                 tmp11 = ((tmp0 + tmp1) * SlowIntegerFix(1.353318001)) +         /* c3 */
                     ((tmp6 - tmp7) * SlowIntegerFix(0.410524528));          /* c13 */
                 tmp12 = ((tmp0 + tmp2) * SlowIntegerFix(1.247225013)) +         /* c5 */
                     ((tmp5 + tmp7) * SlowIntegerFix(0.666655658));          /* c11 */
                 tmp13 = ((tmp0 + tmp3) * SlowIntegerFix(1.093201867)) +         /* c7 */
                     ((tmp4 - tmp7) * SlowIntegerFix(0.897167586));          /* c9 */
                 tmp14 = ((tmp1 + tmp2) * SlowIntegerFix(0.138617169)) +         /* c15 */
                     ((tmp6 - tmp5) * SlowIntegerFix(1.407403738));          /* c1 */
                 tmp15 = ((tmp1 + tmp3) * -SlowIntegerFix(0.666655658)) +       /* -c11 */
                     ((tmp4 + tmp6) * -SlowIntegerFix(1.247225013));        /* -c5 */
                 tmp16 = ((tmp2 + tmp3) * -SlowIntegerFix(1.353318001)) +       /* -c3 */
                     ((tmp5 - tmp4) * SlowIntegerFix(0.410524528));          /* c13 */
                 tmp10 = tmp11 + tmp12 + tmp13 -
                     (tmp0 * SlowIntegerFix(2.286341144)) +                /* c7+c5+c3-c1 */
                     (tmp7 * SlowIntegerFix(0.779653625));                 /* c15+c13-c11+c9 */
                 tmp11 += tmp14 + tmp15 + (tmp1 * SlowIntegerFix(0.071888074)) /* c9-c3-c15+c11 */
                      - (tmp6 * SlowIntegerFix(1.663905119));              /* c7+c13+c1-c5 */
                 tmp12 += tmp14 + tmp16 - (tmp2 * SlowIntegerFix(1.125726048)) /* c7+c5+c15-c3 */
                      + (tmp5 * SlowIntegerFix(1.227391138));              /* c9-c11+c1-c13 */
                 tmp13 += tmp15 + tmp16 + (tmp3 * SlowIntegerFix(1.065388962)) /* c15+c3+c11-c7 */
                      + (tmp4 * SlowIntegerFix(2.167985692));              /* c1+c13+c5-c9 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 1)] = JpegUtils.DESCALE(tmp10, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS + 2);
                 data[dataIndex + (JpegConstants.DCTSIZE * 3)] = JpegUtils.DESCALE(tmp11, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS + 2);
                 data[dataIndex + (JpegConstants.DCTSIZE * 5)] = JpegUtils.DESCALE(tmp12, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS + 2);
                 data[dataIndex + (JpegConstants.DCTSIZE * 7)] = JpegUtils.DESCALE(tmp13, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS + 2);
                 dataIndex++;            /* advance pointer to next column */
                 workspaceIndex++;            /* advance pointer to next column */
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.DESCALE(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_CONST_BITS, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_541196100, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_PASS1_BITS, and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SlowIntegerFix().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct16x8()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x8 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1286 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct1x1()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x1 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1002 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct1x2()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x2 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1361 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct2x1()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x1 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1321 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct2x2()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x2 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1007 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct2x4()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x4 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1356 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct3x3()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x3 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1012 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct3x6()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x6 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1351 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct4x2()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x2 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1316 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct4x4()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x4 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1017 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct4x8()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x8 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1346 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct5x10()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x10 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1341 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct5x5()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x5 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1022 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct6x12()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x12 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1336 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct6x3()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x3 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1311 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct6x6()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x6 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1027 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct7x14()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x14 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1331 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct7x7()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x7 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1032 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct8x16()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x16 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1326 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct8x4()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x4 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1306 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDct9x9()
void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct9x9 (int [] data, byte sample_data[][], int start_row, int start_col) inline private
Definition at line 1037 of file JpegForwardDct.cs.
         {
             m_cinfo.ErrExit(JMessageCode.JERR_NOTIMPL);
         }
References BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDctFloat()
static void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctFloat (float [] data, byte sample_data[][], int start_row, int start_col) inline static private
Perform the forward DCT on one block of samples. NOTE: this code only copes with 8x8 DCTs.
A floating-point implementation of the forward DCT (Discrete Cosine Transform).
This implementation should be more accurate than either of the integer DCT implementations. However, it may not give the same results on all machines because of differences in roundoff behavior. Speed will depend on the hardware's floating point capacity.
A 2-D DCT can be done by 1-D DCT on each row followed by 1-D DCT on each column. Direct algorithms are also available, but they are much more complex and seem not to be any faster when reduced to code.
This implementation is based on Arai, Agui, and Nakajima's algorithm for scaled DCT. Their original paper (Trans. IEICE E-71(11):1095) is in Japanese, but the algorithm is described in the Pennebaker & Mitchell JPEG textbook (see REFERENCES section in file README). The following code is based directly on figure 4-8 in P&M. While an 8-point DCT cannot be done in less than 11 multiplies, it is possible to arrange the computation so that many of the multiplies are simple scalings of the final outputs. These multiplies can then be folded into the multiplications or divisions by the JPEG quantization table entries. The AA&N method leaves only 5 multiplies and 29 adds to be done in the DCT itself. The primary disadvantage of this method is that with a fixed-point implementation, accuracy is lost due to imprecise representation of the scaled quantization values. However, that problem does not arise if we use floating point arithmetic.
Definition at line 496 of file JpegForwardDct.cs.
         {
             /* Pass 1: process rows. */
             var dataIndex = 0;
             for (var ctr = 0; ctr < JpegConstants.DCTSIZE; ctr++)
             {
                 var elem = sample_data[start_row + ctr];
                 var elemIndex = start_col;
                 /* Load data into workspace */
                 float tmp0 = elem[elemIndex + 0] + elem[elemIndex + 7];
                 float tmp7 = elem[elemIndex + 0] - elem[elemIndex + 7];
                 float tmp1 = elem[elemIndex + 1] + elem[elemIndex + 6];
                 float tmp6 = elem[elemIndex + 1] - elem[elemIndex + 6];
                 float tmp2 = elem[elemIndex + 2] + elem[elemIndex + 5];
                 float tmp5 = elem[elemIndex + 2] - elem[elemIndex + 5];
                 float tmp3 = elem[elemIndex + 3] + elem[elemIndex + 4];
                 float tmp4 = elem[elemIndex + 3] - elem[elemIndex + 4];
                 /* Even part */
                 var tmp10 = tmp0 + tmp3;    /* phase 2 */
                 var tmp13 = tmp0 - tmp3;
                 var tmp11 = tmp1 + tmp2;
                 var tmp12 = tmp1 - tmp2;
                 /* Apply unsigned->signed conversion. */
                 data[dataIndex + 0] = tmp10 + tmp11 - (8 * JpegConstants.CENTERJSAMPLE); /* phase 3 */
                 data[dataIndex + 4] = tmp10 - tmp11;
                 var z1 = (tmp12 + tmp13) * 0.707106781f; /* c4 */
                 data[dataIndex + 2] = tmp13 + z1;    /* phase 5 */
                 data[dataIndex + 6] = tmp13 - z1;
                 /* Odd part */
                 tmp10 = tmp4 + tmp5;    /* phase 2 */
                 tmp11 = tmp5 + tmp6;
                 tmp12 = tmp6 + tmp7;
                 /* The rotator is modified from fig 4-8 to avoid extra negations. */
                 var z5 = (tmp10 - tmp12) * 0.382683433f; /* c6 */
                 var z2 = (0.541196100f * tmp10) + z5; /* c2-c6 */
                 var z4 = (1.306562965f * tmp12) + z5; /* c2+c6 */
                 var z3 = tmp11 * 0.707106781f; /* c4 */
                 var z11 = tmp7 + z3;        /* phase 5 */
                 var z13 = tmp7 - z3;
                 data[dataIndex + 5] = z13 + z2;  /* phase 6 */
                 data[dataIndex + 3] = z13 - z2;
                 data[dataIndex + 1] = z11 + z4;
                 data[dataIndex + 7] = z11 - z4;
                 dataIndex += JpegConstants.DCTSIZE;     /* advance pointer to next row */
             }
             /* Pass 2: process columns. */
             dataIndex = 0;
             for (var ctr = JpegConstants.DCTSIZE - 1; ctr >= 0; ctr--)
             {
                 var tmp0 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] + data[dataIndex + (JpegConstants.DCTSIZE * 7)];
                 var tmp7 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] - data[dataIndex + (JpegConstants.DCTSIZE * 7)];
                 var tmp1 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] + data[dataIndex + (JpegConstants.DCTSIZE * 6)];
                 var tmp6 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] - data[dataIndex + (JpegConstants.DCTSIZE * 6)];
                 var tmp2 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] + data[dataIndex + (JpegConstants.DCTSIZE * 5)];
                 var tmp5 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] - data[dataIndex + (JpegConstants.DCTSIZE * 5)];
                 var tmp3 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] + data[dataIndex + (JpegConstants.DCTSIZE * 4)];
                 var tmp4 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] - data[dataIndex + (JpegConstants.DCTSIZE * 4)];
                 /* Even part */
                 var tmp10 = tmp0 + tmp3;    /* phase 2 */
                 var tmp13 = tmp0 - tmp3;
                 var tmp11 = tmp1 + tmp2;
                 var tmp12 = tmp1 - tmp2;
                 data[dataIndex + (JpegConstants.DCTSIZE * 0)] = tmp10 + tmp11; /* phase 3 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 4)] = tmp10 - tmp11;
                 var z1 = (tmp12 + tmp13) * 0.707106781f; /* c4 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 2)] = tmp13 + z1; /* phase 5 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 6)] = tmp13 - z1;
                 /* Odd part */
                 tmp10 = tmp4 + tmp5;    /* phase 2 */
                 tmp11 = tmp5 + tmp6;
                 tmp12 = tmp6 + tmp7;
                 /* The rotator is modified from fig 4-8 to avoid extra negations. */
                 var z5 = (tmp10 - tmp12) * 0.382683433f; /* c6 */
                 var z2 = (0.541196100f * tmp10) + z5; /* c2-c6 */
                 var z4 = (1.306562965f * tmp12) + z5; /* c2+c6 */
                 var z3 = tmp11 * 0.707106781f; /* c4 */
                 var z11 = tmp7 + z3;        /* phase 5 */
                 var z13 = tmp7 - z3;
                 data[dataIndex + (JpegConstants.DCTSIZE * 5)] = z13 + z2; /* phase 6 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 3)] = z13 - z2;
                 data[dataIndex + (JpegConstants.DCTSIZE * 1)] = z11 + z4;
                 data[dataIndex + (JpegConstants.DCTSIZE * 7)] = z11 - z4;
                 dataIndex++;          /* advance pointer to next column */
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, and BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDctIFast()
static void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctIFast (int [] data, byte sample_data[][], int start_row, int start_col) inline static private
Perform the forward DCT on one block of samples. NOTE: this code only copes with 8x8 DCTs. This file contains a fast, not so accurate integer implementation of the forward DCT (Discrete Cosine Transform).
A 2-D DCT can be done by 1-D DCT on each row followed by 1-D DCT on each column. Direct algorithms are also available, but they are much more complex and seem not to be any faster when reduced to code.
This implementation is based on Arai, Agui, and Nakajima's algorithm for scaled DCT. Their original paper (Trans. IEICE E-71(11):1095) is in Japanese, but the algorithm is described in the Pennebaker & Mitchell JPEG textbook (see REFERENCES section in file README). The following code is based directly on figure 4-8 in P&M. While an 8-point DCT cannot be done in less than 11 multiplies, it is possible to arrange the computation so that many of the multiplies are simple scalings of the final outputs. These multiplies can then be folded into the multiplications or divisions by the JPEG quantization table entries. The AA&N method leaves only 5 multiplies and 29 adds to be done in the DCT itself. The primary disadvantage of this method is that with fixed-point math, accuracy is lost due to imprecise representation of the scaled quantization values. The smaller the quantization table entry, the less precise the scaled value, so this implementation does worse with high- quality-setting files than with low-quality ones.
Scaling decisions are generally the same as in the LL&M algorithm; see JpegForwardDctISlow for more details. However, we choose to descale (right shift) multiplication products as soon as they are formed, rather than carrying additional fractional bits into subsequent additions. This compromises accuracy slightly, but it lets us save a few shifts. More importantly, 16-bit arithmetic is then adequate (for 8-bit samples) everywhere except in the multiplications proper; this saves a good deal of work on 16-bit-int machines.
Again to save a few shifts, the intermediate results between pass 1 and pass 2 are not upscaled, but are represented only to integral precision.
A final compromise is to represent the multiplicative constants to only 8 fractional bits, rather than 13. This saves some shifting work on some machines, and may also reduce the cost of multiplication (since there are fewer one-bits in the constants).
Definition at line 656 of file JpegForwardDct.cs.
         {
             /* Pass 1: process rows. */
             var dataIndex = 0;
             for (var ctr = 0; ctr < JpegConstants.DCTSIZE; ctr++)
             {
                 var elem = sample_data[start_row + ctr];
                 var elemIndex = start_col;
                 /* Load data into workspace */
                 var tmp0 = elem[elemIndex + 0] + elem[elemIndex + 7];
                 var tmp7 = elem[elemIndex + 0] - elem[elemIndex + 7];
                 var tmp1 = elem[elemIndex + 1] + elem[elemIndex + 6];
                 var tmp6 = elem[elemIndex + 1] - elem[elemIndex + 6];
                 var tmp2 = elem[elemIndex + 2] + elem[elemIndex + 5];
                 var tmp5 = elem[elemIndex + 2] - elem[elemIndex + 5];
                 var tmp3 = elem[elemIndex + 3] + elem[elemIndex + 4];
                 var tmp4 = elem[elemIndex + 3] - elem[elemIndex + 4];
                 /* Even part */
                 var tmp10 = tmp0 + tmp3;    /* phase 2 */
                 var tmp13 = tmp0 - tmp3;
                 var tmp11 = tmp1 + tmp2;
                 var tmp12 = tmp1 - tmp2;
                 /* Apply unsigned->signed conversion. */
                 data[dataIndex + 0] = tmp10 + tmp11 - (8 * JpegConstants.CENTERJSAMPLE); /* phase 3 */
                 data[dataIndex + 4] = tmp10 - tmp11;
                 var z1 = FastIntegerMultiply(tmp12 + tmp13, FAST_INTEGER_FIX_0_707106781); /* c4 */
                 data[dataIndex + 2] = tmp13 + z1;    /* phase 5 */
                 data[dataIndex + 6] = tmp13 - z1;
                 /* Odd part */
                 tmp10 = tmp4 + tmp5;    /* phase 2 */
                 tmp11 = tmp5 + tmp6;
                 tmp12 = tmp6 + tmp7;
                 /* The rotator is modified from fig 4-8 to avoid extra negations. */
                 var z5 = FastIntegerMultiply(tmp10 - tmp12, FAST_INTEGER_FIX_0_382683433); /* c6 */
                 var z2 = FastIntegerMultiply(tmp10, FAST_INTEGER_FIX_0_541196100) + z5; /* c2-c6 */
                 var z4 = FastIntegerMultiply(tmp12, FAST_INTEGER_FIX_1_306562965) + z5; /* c2+c6 */
                 var z3 = FastIntegerMultiply(tmp11, FAST_INTEGER_FIX_0_707106781); /* c4 */
                 var z11 = tmp7 + z3;        /* phase 5 */
                 var z13 = tmp7 - z3;
                 data[dataIndex + 5] = z13 + z2;  /* phase 6 */
                 data[dataIndex + 3] = z13 - z2;
                 data[dataIndex + 1] = z11 + z4;
                 data[dataIndex + 7] = z11 - z4;
                 dataIndex += JpegConstants.DCTSIZE;     /* advance pointer to next row */
             }
             /* Pass 2: process columns. */
             dataIndex = 0;
             for (var ctr = JpegConstants.DCTSIZE - 1; ctr >= 0; ctr--)
             {
                 var tmp0 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] + data[dataIndex + (JpegConstants.DCTSIZE * 7)];
                 var tmp7 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] - data[dataIndex + (JpegConstants.DCTSIZE * 7)];
                 var tmp1 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] + data[dataIndex + (JpegConstants.DCTSIZE * 6)];
                 var tmp6 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] - data[dataIndex + (JpegConstants.DCTSIZE * 6)];
                 var tmp2 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] + data[dataIndex + (JpegConstants.DCTSIZE * 5)];
                 var tmp5 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] - data[dataIndex + (JpegConstants.DCTSIZE * 5)];
                 var tmp3 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] + data[dataIndex + (JpegConstants.DCTSIZE * 4)];
                 var tmp4 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] - data[dataIndex + (JpegConstants.DCTSIZE * 4)];
                 /* Even part */
                 var tmp10 = tmp0 + tmp3;    /* phase 2 */
                 var tmp13 = tmp0 - tmp3;
                 var tmp11 = tmp1 + tmp2;
                 var tmp12 = tmp1 - tmp2;
                 data[dataIndex + (JpegConstants.DCTSIZE * 0)] = tmp10 + tmp11; /* phase 3 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 4)] = tmp10 - tmp11;
                 var z1 = FastIntegerMultiply(tmp12 + tmp13, FAST_INTEGER_FIX_0_707106781); /* c4 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 2)] = tmp13 + z1; /* phase 5 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 6)] = tmp13 - z1;
                 /* Odd part */
                 tmp10 = tmp4 + tmp5;    /* phase 2 */
                 tmp11 = tmp5 + tmp6;
                 tmp12 = tmp6 + tmp7;
                 /* The rotator is modified from fig 4-8 to avoid extra negations. */
                 var z5 = FastIntegerMultiply(tmp10 - tmp12, FAST_INTEGER_FIX_0_382683433); /* c6 */
                 var z2 = FastIntegerMultiply(tmp10, FAST_INTEGER_FIX_0_541196100) + z5; /* c2-c6 */
                 var z4 = FastIntegerMultiply(tmp12, FAST_INTEGER_FIX_1_306562965) + z5; /* c2+c6 */
                 var z3 = FastIntegerMultiply(tmp11, FAST_INTEGER_FIX_0_707106781); /* c4 */
                 var z11 = tmp7 + z3;        /* phase 5 */
                 var z13 = tmp7 - z3;
                 data[dataIndex + (JpegConstants.DCTSIZE * 5)] = z13 + z2; /* phase 6 */
                 data[dataIndex + (JpegConstants.DCTSIZE * 3)] = z13 - z2;
                 data[dataIndex + (JpegConstants.DCTSIZE * 1)] = z11 + z4;
                 data[dataIndex + (JpegConstants.DCTSIZE * 7)] = z11 - z4;
                 dataIndex++;          /* advance pointer to next column */
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_0_382683433, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_0_541196100, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_0_707106781, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_1_306562965, and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FastIntegerMultiply().
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
JpegForwardDctISlow()
static void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow (int [] data, byte sample_data[][], int start_row, int start_col) inline static private
Perform the forward DCT on one block of samples. NOTE: this code only copes with 8x8 DCTs.
A slow-but-accurate integer implementation of the forward DCT (Discrete Cosine Transform).
A 2-D DCT can be done by 1-D DCT on each row followed by 1-D DCT on each column. Direct algorithms are also available, but they are much more complex and seem not to be any faster when reduced to code.
This implementation is based on an algorithm described in C. Loeffler, A. Ligtenberg and G. Moschytz, "Practical Fast 1-D DCT Algorithms with 11 Multiplications", Proc. Int'l. Conf. on Acoustics, Speech, and Signal Processing 1989 (ICASSP '89), pp. 988-991. The primary algorithm described there uses 11 multiplies and 29 adds. We use their alternate method with 12 multiplies and 32 adds. The advantage of this method is that no data path contains more than one multiplication; this allows a very simple and accurate implementation in scaled fixed-point arithmetic, with a minimal number of shifts.
The poop on this scaling stuff is as follows:
Each 1-D DCT step produces outputs which are a factor of sqrt(N) larger than the true DCT outputs. The final outputs are therefore a factor of N larger than desired; since N=8 this can be cured by a simple right shift at the end of the algorithm. The advantage of this arrangement is that we save two multiplications per 1-D DCT, because the y0 and y4 outputs need not be divided by sqrt(N). In the IJG code, this factor of 8 is removed by the quantization step, NOT here.
We have to do addition and subtraction of the integer inputs, which is no problem, and multiplication by fractional constants, which is a problem to do in integer arithmetic. We multiply all the constants by CONST_SCALE and convert them to integer constants (thus retaining SLOW_INTEGER_CONST_BITS bits of precision in the constants). After doing a multiplication we have to divide the product by CONST_SCALE, with proper rounding, to produce the correct output. This division can be done cheaply as a right shift of SLOW_INTEGER_CONST_BITS bits. We postpone shifting as long as possible so that partial sums can be added together with full fractional precision.
The outputs of the first pass are scaled up by SLOW_INTEGER_PASS1_BITS bits so that they are represented to better-than-integral precision. These outputs require BITS_IN_JSAMPLE + SLOW_INTEGER_PASS1_BITS + 3 bits; this fits in a 16-bit word with the recommended scaling. (For 12-bit sample data, the intermediate array is int anyway.)
To avoid overflow of the 32-bit intermediate results in pass 2, we must have BITS_IN_JSAMPLE + SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS <= 26. Error analysis shows that the values given below are the most effective.
Definition at line 826 of file JpegForwardDct.cs.
         {
             /* Pass 1: process rows. */
             /* Note results are scaled up by sqrt(8) compared to a true DCT; */
             /* furthermore, we scale the results by 2**SLOW_INTEGER_PASS1_BITS. */
             var dataIndex = 0;
             for (var ctr = 0; ctr < JpegConstants.DCTSIZE; ctr++)
             {
                 var elem = sample_data[start_row + ctr];
                 var elemIndex = start_col;
                 var tmp0 = elem[elemIndex + 0] + elem[elemIndex + 7];
                 var tmp1 = elem[elemIndex + 1] + elem[elemIndex + 6];
                 var tmp2 = elem[elemIndex + 2] + elem[elemIndex + 5];
                 var tmp3 = elem[elemIndex + 3] + elem[elemIndex + 4];
                 /* Even part per LL&M figure 1 --- note that published figure is faulty;
                 * rotator "sqrt(2)*c1" should be "sqrt(2)*c6".
                 */
                 var tmp10 = tmp0 + tmp3;
                 var tmp12 = tmp0 - tmp3;
                 var tmp11 = tmp1 + tmp2;
                 var tmp13 = tmp1 - tmp2;
                 tmp0 = elem[elemIndex + 0] - elem[elemIndex + 7];
                 tmp1 = elem[elemIndex + 1] - elem[elemIndex + 6];
                 tmp2 = elem[elemIndex + 2] - elem[elemIndex + 5];
                 tmp3 = elem[elemIndex + 3] - elem[elemIndex + 4];
                 data[dataIndex + 0] = (tmp10 + tmp11 - (8 * JpegConstants.CENTERJSAMPLE)) << SLOW_INTEGER_PASS1_BITS;
                 data[dataIndex + 4] = (tmp10 - tmp11) << SLOW_INTEGER_PASS1_BITS;
                 var z1 = (tmp12 + tmp13) * SLOW_INTEGER_FIX_0_541196100;
                 /* Add fudge factor here for final descale. */
                 z1 += 1 << (SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS - 1);
                 data[dataIndex + 2] = JpegUtils.RIGHT_SHIFT(z1 + (tmp12 * SLOW_INTEGER_FIX_0_765366865), /* c2-c6 */
                                                 SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 6] = JpegUtils.DESCALE(z1 - (tmp13 * SLOW_INTEGER_FIX_1_847759065),
                                                 SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 /* Odd part per figure 8 --- note paper omits factor of sqrt(2).
                 * cK represents cos(K*pi/16).
                 * i0..i3 in the paper are tmp4..tmp7 here.
                 */
                 tmp12 = tmp0 + tmp2;
                 tmp13 = tmp1 + tmp3;
                 z1 = (tmp12 + tmp13) * SLOW_INTEGER_FIX_1_175875602; /*  c3 */
                 /* Add fudge factor here for final descale. */
                 z1 += 1 << (SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS - 1);
                 tmp12 *= -SLOW_INTEGER_FIX_0_390180644;          /* -c3+c5 */
                 tmp13 *= -SLOW_INTEGER_FIX_1_961570560;          /* -c3-c5 */
                 tmp12 += z1;
                 tmp13 += z1;
                 z1 = (tmp0 + tmp3) * -SLOW_INTEGER_FIX_0_899976223;       /* -c3+c7 */
                 tmp0 *= SLOW_INTEGER_FIX_1_501321110;              /*  c1+c3-c5-c7 */
                 tmp3 *= SLOW_INTEGER_FIX_0_298631336;              /* -c1+c3+c5-c7 */
                 tmp0 += z1 + tmp12;
                 tmp3 += z1 + tmp13;
                 z1 = (tmp1 + tmp2) * -SLOW_INTEGER_FIX_2_562915447;       /* -c1-c3 */
                 tmp1 *= SLOW_INTEGER_FIX_3_072711026;              /*  c1+c3+c5-c7 */
                 tmp2 *= SLOW_INTEGER_FIX_2_053119869;              /*  c1+c3-c5+c7 */
                 tmp1 += z1 + tmp13;
                 tmp2 += z1 + tmp12;
                 data[dataIndex + 1] = JpegUtils.RIGHT_SHIFT(tmp0, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 3] = JpegUtils.RIGHT_SHIFT(tmp1, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 5] = JpegUtils.RIGHT_SHIFT(tmp2, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + 7] = JpegUtils.RIGHT_SHIFT(tmp3, SLOW_INTEGER_CONST_BITS - SLOW_INTEGER_PASS1_BITS);
                 dataIndex += JpegConstants.DCTSIZE;     /* advance pointer to next row */
             }
             /* Pass 2: process columns.
             * We remove the SLOW_INTEGER_PASS1_BITS scaling, but leave the results scaled up
             * by an overall factor of 8.
             * cK represents sqrt(2) * cos(K*pi/16).
             */
             dataIndex = 0;
             for (var ctr = JpegConstants.DCTSIZE - 1; ctr >= 0; ctr--)
             {
                 /* Even part per LL&M figure 1 --- note that published figure is faulty;
                  * rotator "sqrt(2)*c1" should be "sqrt(2)*c6".
                  */
                 var tmp0 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] + data[dataIndex + (JpegConstants.DCTSIZE * 7)];
                 var tmp1 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] + data[dataIndex + (JpegConstants.DCTSIZE * 6)];
                 var tmp2 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] + data[dataIndex + (JpegConstants.DCTSIZE * 5)];
                 var tmp3 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] + data[dataIndex + (JpegConstants.DCTSIZE * 4)];
                 /* Add fudge factor here for final descale. */
                 var tmp10 = tmp0 + tmp3 + (1 << (SLOW_INTEGER_PASS1_BITS - 1));
                 var tmp12 = tmp0 - tmp3;
                 var tmp11 = tmp1 + tmp2;
                 var tmp13 = tmp1 - tmp2;
                 tmp0 = data[dataIndex + (JpegConstants.DCTSIZE * 0)] - data[dataIndex + (JpegConstants.DCTSIZE * 7)];
                 tmp1 = data[dataIndex + (JpegConstants.DCTSIZE * 1)] - data[dataIndex + (JpegConstants.DCTSIZE * 6)];
                 tmp2 = data[dataIndex + (JpegConstants.DCTSIZE * 2)] - data[dataIndex + (JpegConstants.DCTSIZE * 5)];
                 tmp3 = data[dataIndex + (JpegConstants.DCTSIZE * 3)] - data[dataIndex + (JpegConstants.DCTSIZE * 4)];
                 data[dataIndex + (JpegConstants.DCTSIZE * 0)] = JpegUtils.RIGHT_SHIFT(tmp10 + tmp11, SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + (JpegConstants.DCTSIZE * 4)] = JpegUtils.RIGHT_SHIFT(tmp10 - tmp11, SLOW_INTEGER_PASS1_BITS);
                 var z1 = (tmp12 + tmp13) * SLOW_INTEGER_FIX_0_541196100;       /* c6 */
                 /* Add fudge factor here for final descale. */
                 z1 += 1 << (SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS - 1);
                 data[dataIndex + (JpegConstants.DCTSIZE * 2)] = JpegUtils.RIGHT_SHIFT(
                     z1 + (tmp12 * SLOW_INTEGER_FIX_0_765366865),
                     SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + (JpegConstants.DCTSIZE * 6)] = JpegUtils.RIGHT_SHIFT(
                     z1 - (tmp13 * SLOW_INTEGER_FIX_1_847759065),
                     SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS);
                 /* Odd part per figure 8 --- note paper omits factor of sqrt(2).
                 * i0..i3 in the paper are tmp4..tmp7 here.
                 */
                 tmp12 = tmp0 + tmp2;
                 tmp13 = tmp1 + tmp3;
                 z1 = (tmp12 + tmp13) * SLOW_INTEGER_FIX_1_175875602; /*  c3 */
                 /* Add fudge factor here for final descale. */
                 z1 += 1 << (SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS - 1);
                 tmp12 *= -SLOW_INTEGER_FIX_0_390180644;          /* -c3+c5 */
                 tmp13 *= -SLOW_INTEGER_FIX_1_961570560;          /* -c3-c5 */
                 tmp12 += z1;
                 tmp13 += z1;
                 z1 = (tmp0 + tmp3) * -SLOW_INTEGER_FIX_0_899976223;       /* -c3+c7 */
                 tmp0 *= SLOW_INTEGER_FIX_1_501321110;              /*  c1+c3-c5-c7 */
                 tmp3 *= SLOW_INTEGER_FIX_0_298631336;              /* -c1+c3+c5-c7 */
                 tmp0 += z1 + tmp12;
                 tmp3 += z1 + tmp13;
                 z1 = (tmp1 + tmp2) * -SLOW_INTEGER_FIX_2_562915447;       /* -c1-c3 */
                 tmp1 *= SLOW_INTEGER_FIX_3_072711026;              /*  c1+c3+c5-c7 */
                 tmp2 *= SLOW_INTEGER_FIX_2_053119869;              /*  c1+c3-c5+c7 */
                 tmp1 += z1 + tmp13;
                 tmp2 += z1 + tmp12;
                 data[dataIndex + (JpegConstants.DCTSIZE * 1)] = JpegUtils.RIGHT_SHIFT(tmp0, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + (JpegConstants.DCTSIZE * 3)] = JpegUtils.RIGHT_SHIFT(tmp1, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + (JpegConstants.DCTSIZE * 5)] = JpegUtils.RIGHT_SHIFT(tmp2, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS);
                 data[dataIndex + (JpegConstants.DCTSIZE * 7)] = JpegUtils.RIGHT_SHIFT(tmp3, SLOW_INTEGER_CONST_BITS + SLOW_INTEGER_PASS1_BITS);
                 dataIndex++;          /* advance pointer to next column */
             }
         }
References BitMiracle.LibJpeg.Classic.JpegConstants.CENTERJSAMPLE, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.DESCALE(), BitMiracle.LibJpeg.Classic.Internal.JpegUtils.RIGHT_SHIFT(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_CONST_BITS, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_298631336, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_390180644, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_541196100, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_765366865, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_899976223, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_175875602, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_501321110, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_847759065, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_961570560, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_2_053119869, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_2_562915447, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_3_072711026, and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_PASS1_BITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
SlowIntegerFix()
static int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SlowIntegerFix (double x) inline static private
Definition at line 997 of file JpegForwardDct.cs.
         {
             return (int)((x * (1 << SLOW_INTEGER_CONST_BITS)) + 0.5);
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_CONST_BITS.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x16().
StartPass()
virtual void BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass () inline virtual
Initialize for a processing pass. Verify that all referenced Q-tables are present, and set up the divisor table for each one. In the current implementation, DCT of all components is done during the first pass, even if only some components will be output in the first scan. Hence all components should be examined here.
Definition at line 159 of file JpegForwardDct.cs.
         {
             JDctMethod method = 0;
             for (var ci = 0; ci < m_cinfo.m_num_components; ci++)
             {
                 /* Select the proper DCT routine for this component's scaling */
                 var compptr = m_cinfo.Component_info[ci];
                 switch ((compptr.DCT_h_scaled_size << 8) + compptr.DCT_v_scaled_size)
                 {
                     case ((1 << 8) + 1):
                     do_dct[ci] = JpegForwardDct1x1;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((2 << 8) + 2):
                     do_dct[ci] = JpegForwardDct2x2;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((3 << 8) + 3):
                     do_dct[ci] = JpegForwardDct3x3;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((4 << 8) + 4):
                     do_dct[ci] = JpegForwardDct4x4;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((5 << 8) + 5):
                     do_dct[ci] = JpegForwardDct5x5;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((6 << 8) + 6):
                     do_dct[ci] = JpegForwardDct6x6;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((7 << 8) + 7):
                     do_dct[ci] = JpegForwardDct7x7;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((9 << 8) + 9):
                     do_dct[ci] = JpegForwardDct9x9;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((10 << 8) + 10):
                     do_dct[ci] = JpegForwardDct10x10;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((11 << 8) + 11):
                     do_dct[ci] = JpegForwardDct11x11;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((12 << 8) + 12):
                     do_dct[ci] = JpegForwardDct12x12;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((13 << 8) + 13):
                     do_dct[ci] = JpegForwardDct13x13;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((14 << 8) + 14):
                     do_dct[ci] = JpegForwardDct14x14;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((15 << 8) + 15):
                     do_dct[ci] = JpegForwardDct15x15;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((16 << 8) + 16):
                     do_dct[ci] = JpegForwardDct16x16;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((16 << 8) + 8):
                     do_dct[ci] = JpegForwardDct16x8;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((14 << 8) + 7):
                     do_dct[ci] = JpegForwardDct14x7;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((12 << 8) + 6):
                     do_dct[ci] = JpegForwardDct12x6;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((10 << 8) + 5):
                     do_dct[ci] = JpegForwardDct10x5;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((8 << 8) + 4):
                     do_dct[ci] = JpegForwardDct8x4;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((6 << 8) + 3):
                     do_dct[ci] = JpegForwardDct6x3;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((4 << 8) + 2):
                     do_dct[ci] = JpegForwardDct4x2;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((2 << 8) + 1):
                     do_dct[ci] = JpegForwardDct2x1;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((8 << 8) + 16):
                     do_dct[ci] = JpegForwardDct8x16;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((7 << 8) + 14):
                     do_dct[ci] = JpegForwardDct7x14;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((6 << 8) + 12):
                     do_dct[ci] = JpegForwardDct6x12;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((5 << 8) + 10):
                     do_dct[ci] = JpegForwardDct5x10;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((4 << 8) + 8):
                     do_dct[ci] = JpegForwardDct4x8;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((3 << 8) + 6):
                     do_dct[ci] = JpegForwardDct3x6;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((2 << 8) + 4):
                     do_dct[ci] = JpegForwardDct2x4;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((1 << 8) + 2):
                     do_dct[ci] = JpegForwardDct1x2;
                     method = JDctMethod.JDCT_ISLOW;    /* jfdctint uses islow-style table */
                     break;
                     case ((JpegConstants.DCTSIZE << 8) + JpegConstants.DCTSIZE):
                     switch (m_cinfo.m_dct_method)
                     {
                         case JDctMethod.JDCT_ISLOW:
                         do_dct[ci] = JpegForwardDctISlow;
                         method = JDctMethod.JDCT_ISLOW;
                         break;
                         case JDctMethod.JDCT_IFAST:
                         do_dct[ci] = JpegForwardDctIFast;
                         method = JDctMethod.JDCT_IFAST;
                         break;
                         case JDctMethod.JDCT_FLOAT:
                         do_float_dct[ci] = JpegForwardDctFloat;
                         method = JDctMethod.JDCT_FLOAT;
                         break;
                         default:
                         m_cinfo.ErrExit(JMessageCode.JERR_NOT_COMPILED);
                         break;
                     }
                     break;
                     default:
                     m_cinfo.ErrExit(JMessageCode.JERR_BAD_DCTSIZE, compptr.DCT_h_scaled_size, compptr.DCT_v_scaled_size);
                     break;
                 }
                 var qtblno = m_cinfo.Component_info[ci].Quant_tbl_no;
                 /* Make sure specified quantization table is present */
                 if (qtblno < 0 || qtblno >= JpegConstants.NUM_QUANT_TBLS || m_cinfo.m_quant_tbl_ptrs[qtblno] is null)
                 {
                     m_cinfo.ErrExit(JMessageCode.JERR_NO_QUANT_TABLE, qtblno);
                 }
                 var qtbl = m_cinfo.m_quant_tbl_ptrs[qtblno];
                 int[] dtbl;
                 /* Create divisor table from quant table */
                 var i = 0;
                 switch (method)
                 {
                     case JDctMethod.JDCT_ISLOW:
                     /* For LL&M IDCT method, divisors are equal to raw quantization
                      * coefficients multiplied by 8 (to counteract scaling).
                      */
                     dtbl = m_dctTables[ci].int_array;
                     for (i = 0; i < JpegConstants.DCTSIZE2; i++)
                     {
                         dtbl[i] = qtbl.quantBal[i] << (compptr.component_needed ? 4 : 3);
                     }
                     forward_DCT[ci] = ForwardDctImpl;
                     break;
                     case JDctMethod.JDCT_IFAST:
                     dtbl = m_dctTables[ci].int_array;
                     for (i = 0; i < JpegConstants.DCTSIZE2; i++)
                     {
                         dtbl[i] = JpegUtils.DESCALE(qtbl.quantBal[i] * aanscales[i], compptr.component_needed ? CONST_BITS - 4 : CONST_BITS - 3);
                     }
                     forward_DCT[ci] = ForwardDctImpl;
                     break;
                     case JDctMethod.JDCT_FLOAT:
                     var fdtbl = m_dctTables[ci].float_array;
                     i = 0;
                     for (var row = 0; row < JpegConstants.DCTSIZE; row++)
                     {
                         for (var col = 0; col < JpegConstants.DCTSIZE; col++)
{
                             fdtbl[i] = (float)(1.0 / (qtbl.quantBal[i] * aanscalefactor[row] * aanscalefactor[col] * (compptr.component_needed ? 16.0 : 8.0)));
                             i++;
                         }
                     }
                     forward_DCT[ci] = ForwardDctFloatImpl;
                     break;
                     default:
                     m_cinfo.ErrExit(JMessageCode.JERR_NOT_COMPILED);
                     break;
                 }
             }
         }
References BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.aanscalefactor, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.aanscales, BitMiracle.LibJpeg.Classic.JpegCompressStruct.Component_info, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.CONST_BITS, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE, BitMiracle.LibJpeg.Classic.JpegConstants.DCTSIZE2, BitMiracle.LibJpeg.Classic.Internal.JpegUtils.DESCALE(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.do_dct, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.do_float_dct, BitMiracle.LibJpeg.Classic.JpegCommonStruct.ErrExit(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.DivisorTable.float_array, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.forward_DCT, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctFloatImpl(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctImpl(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.DivisorTable.int_array, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct9x9(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctFloat(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctIFast(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_dct_method, BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_dctTables, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_num_components, BitMiracle.LibJpeg.Classic.JpegCompressStruct.m_quant_tbl_ptrs, BitMiracle.LibJpeg.Classic.JpegConstants.NUM_QUANT_TBLS, and BitMiracle.LibJpeg.Classic.JpegComponentInfo.Quant_tbl_no.
Member Data Documentation
aanscalefactor
readonly double [] BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.aanscalefactor static private
Initial value:
= {
            1.0, 1.387039845, 1.306562965, 1.175875602, 1.0,
            0.785694958, 0.541196100, 0.275899379 }
Definition at line 100 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
aanscales
readonly short [] BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.aanscales static private
Initial value:
= {
            16384, 22725, 21407, 19266, 16384, 12873, 8867, 4520, 22725, 31521, 29692, 26722, 22725, 17855,
            12299, 6270, 21407, 29692, 27969, 25172, 21407, 16819, 11585,
            5906, 19266, 26722, 25172, 22654, 19266, 15137, 10426, 5315,
            16384, 22725, 21407, 19266, 16384, 12873, 8867, 4520, 12873,
            17855, 16819, 15137, 12873, 10114, 6967, 3552, 8867, 12299,
            11585, 10426, 8867, 6967, 4799, 2446, 4520, 6270, 5906, 5315,
            4520, 3552, 2446, 1247 }
Definition at line 83 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
CONST_BITS
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.CONST_BITS = 14 private
Definition at line 80 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
do_dct
readonly ForwardDctMethodDelegate [] BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.do_dct = new ForwardDctMethodDelegate[JpegConstants.MAX_COMPONENTS] private
Definition at line 107 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctFloatImpl(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctImpl(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
do_float_dct
readonly FloatDctMethodDelegate [] BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.do_float_dct = new FloatDctMethodDelegate[JpegConstants.MAX_COMPONENTS] private
Definition at line 111 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctFloatImpl(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
FAST_INTEGER_CONST_BITS
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_CONST_BITS = 8 private
Definition at line 32 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FastIntegerMultiply().
FAST_INTEGER_FIX_0_382683433
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_0_382683433 = 98 private
Definition at line 43 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctIFast().
FAST_INTEGER_FIX_0_541196100
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_0_541196100 = 139 private
Definition at line 44 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctIFast().
FAST_INTEGER_FIX_0_707106781
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_0_707106781 = 181 private
Definition at line 45 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctIFast().
FAST_INTEGER_FIX_1_306562965
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.FAST_INTEGER_FIX_1_306562965 = 334 private
Definition at line 46 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctIFast().
forward_DCT
ForwardDctDelegate [] BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.forward_DCT = new ForwardDctDelegate[JpegConstants.MAX_COMPONENTS]
Definition at line 124 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
m_cinfo
readonly JpegCompressStruct BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_cinfo private
Definition at line 104 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct10x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct11x11(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct12x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct13x13(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct14x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct15x15(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct1x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x1(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct2x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct3x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x2(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct4x8(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x10(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct5x5(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x12(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x3(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct6x6(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x14(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct7x7(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct8x4(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct9x9(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
m_dctTables
readonly DivisorTable [] BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.m_dctTables private
Definition at line 135 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctFloatImpl(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.ForwardDctImpl(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.StartPass().
SLOW_INTEGER_CONST_BITS
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_CONST_BITS = 13 private
Definition at line 48 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x16(), BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SlowIntegerFix().
SLOW_INTEGER_FIX_0_298631336
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_298631336 = 2446 private
Definition at line 61 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_0_390180644
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_390180644 = 3196 private
Definition at line 62 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_0_541196100
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_541196100 = 4433 private
Definition at line 63 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x16(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_0_765366865
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_765366865 = 6270 private
Definition at line 64 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_0_899976223
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_0_899976223 = 7373 private
Definition at line 65 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_1_175875602
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_175875602 = 9633 private
Definition at line 66 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_1_501321110
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_501321110 = 12299 private
Definition at line 67 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_1_847759065
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_847759065 = 15137 private
Definition at line 68 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_1_961570560
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_1_961570560 = 16069 private
Definition at line 69 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_2_053119869
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_2_053119869 = 16819 private
Definition at line 70 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_2_562915447
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_2_562915447 = 20995 private
Definition at line 71 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_FIX_3_072711026
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_FIX_3_072711026 = 25172 private
Definition at line 72 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
SLOW_INTEGER_PASS1_BITS
const int BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.SLOW_INTEGER_PASS1_BITS = 2 private
Definition at line 49 of file JpegForwardDct.cs.
Referenced by BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDct16x16(), and BitMiracle.LibJpeg.Classic.Internal.JpegForwardDct.JpegForwardDctISlow().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/LibJpeg.NET/Classic/Internal/JpegForwardDct.cs