Juniper: Juniper.Input.Pointers.ButtonMapper< ButtonIDType > Class Template Reference
Juniper.Input.Pointers.ButtonMapper< ButtonIDType > Class Template Reference
Public Member Functions
void Install (GameObject pointer, Dictionary< ButtonIDType, InputButton > buttons)
bool IsButtonDown (InputButton button)
bool IsButtonUp (InputButton button)
bool IsButtonPressed (InputButton button)
int ToInt32 (ButtonIDType button)
IEventSystemHandler Process (PointerEventData eventData, float pixelDragThresholdSquared)
Public Attributes
readonly Dictionary< ButtonIDType, ButtonEvent > buttonEvents = new Dictionary<ButtonIDType, ButtonEvent>()
readonly Dictionary< InputButton, ButtonEvent > inputButtonEvents = new Dictionary<InputButton, ButtonEvent>()
IEnumerable< ButtonIDType > Buttons
Properties
bool AnyDragging [get, private set]
Events
Func< ButtonIDType, bool > ButtonDownNeeded
Func< ButtonIDType, bool > ButtonUpNeeded
Func< ButtonIDType, bool > ButtonPressedNeeded
Func< PointerEventData, ButtonIDType, PointerEventData > ClonedPointerEventNeeded
Action< Interaction > InteractionNeeded
Private Member Functions
void TestUpDown (PointerEventData evtData, ButtonIDType button, bool pressed)
void TestDrag (PointerEventData evtData, bool pressed, float pixelDragThresholdSquared)
Static Private Member Functions
static void MakeEventHandler< T > (GameObject pointer, T button)
static void GetEventHandlers< T > (GameObject pointer, Dictionary< T, ButtonEvent > storage)
Private Attributes
const float THRESHOLD_CLICK = 0.4f
const float THRESHOLD_LONG_PRESS = 2f
readonly Dictionary< ButtonIDType, InputButton > toInputButton = new Dictionary<ButtonIDType, InputButton>()
readonly Dictionary< InputButton, ButtonIDType > fromInputButton = new Dictionary<InputButton, ButtonIDType>()
readonly Dictionary< ButtonIDType, int > toInteger = new Dictionary<ButtonIDType, int>()
readonly Dictionary< ButtonIDType, float > buttonDownTime = new Dictionary<ButtonIDType, float>()
readonly Dictionary< ButtonIDType, bool > mayLongPress = new Dictionary<ButtonIDType, bool>()
readonly Dictionary< InputButton, float > dragDistances = new Dictionary<InputButton, float>()
Detailed Description
Type Constraints
ButtonIDType : struct
Definition at line 14 of file ButtonMapper.cs.
Member Function Documentation
GetEventHandlers< T >()
static void Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.GetEventHandlers< T > (GameObject pointer, Dictionary< T, ButtonEvent > storage) inline static private
Type Constraints
T : struct
Definition at line 79 of file ButtonMapper.cs.
                     : struct
         {
             var type = typeof(T);
             var events = pointer.GetComponents<ButtonEvent>()
                 .Where(e => e.buttonTypeName == type.FullName);
             foreach (var evt in events)
             {
                 var value = evt.GetButtonValue<T>();
                 if (value != null)
                 {
                     storage.Add(value.Value, evt);
                 }
             }
         }
Install()
void Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.Install (GameObject pointer, Dictionary< ButtonIDType, InputButton > buttons) inline
Definition at line 42 of file ButtonMapper.cs.
         {
             buttonEvents.Clear();
             inputButtonEvents.Clear();
             foreach (var pair in buttons)
             {
                 MakeEventHandler(pointer, pair.Key);
                 MakeEventHandler(pointer, pair.Value);
                 toInputButton.Add(pair.Key, pair.Value);
                 toInteger.Add(pair.Key, Convert.ToInt32(pair.Key));
             }
             foreach (var evt in pointer.GetComponents<ButtonEvent>())
             {
                 if (string.IsNullOrEmpty(evt.buttonTypeName)
                     || string.IsNullOrEmpty(evt.buttonValueName))
                 {
                     evt.Destroy();
                 }
             }
             GetEventHandlers(pointer, buttonEvents);
             GetEventHandlers(pointer, inputButtonEvents);
         }
IsButtonDown()
bool Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.IsButtonDown (InputButton button)
IsButtonPressed()
bool Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.IsButtonPressed (InputButton button)
IsButtonUp()
bool Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.IsButtonUp (InputButton button)
MakeEventHandler< T >()
static void Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.MakeEventHandler< T > (GameObject pointer, T button) inline static private
Type Constraints
T : struct
Definition at line 69 of file ButtonMapper.cs.
                     : struct
         {
             var key = ButtonEvent.MakeKey(button);
             var evt = Array.Find(pointer.GetComponents<ButtonEvent>(), e => e.Key == key)
                 ?? pointer.AddComponent<ButtonEvent>();
             evt.Key = key;
         }
Process()
IEventSystemHandler Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.Process (PointerEventData eventData, float pixelDragThresholdSquared) inline
Definition at line 111 of file ButtonMapper.cs.
         {
             IEventSystemHandler eventTarget = null;
             AnyDragging = false;
             foreach (var button in Buttons)
             {
                 var pressed = ButtonPressedNeeded?.Invoke(button) == true;
                 var evtData = ClonedPointerEventNeeded?.Invoke(eventData, button) ?? eventData;
                 evtData.button = toInputButton[button];
                 TestUpDown(evtData, button, pressed);
                 TestDrag(evtData, pressed, pixelDragThresholdSquared);
                 eventTarget = evtData.pointerEnter?.GetComponent<IEventSystemHandler>() ?? eventTarget;
             }
             return eventTarget;
         }
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.ProcessButtons().
TestDrag()
void Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.TestDrag (PointerEventData evtData, bool pressed, float pixelDragThresholdSquared) inline private
Definition at line 202 of file ButtonMapper.cs.
         {
             AnyDragging |= evtData.pointerDrag != null;
             if (evtData.pointerDrag != null && evtData.IsPointerMoving())
             {
                 var wasDragging = evtData.dragging;
                 if (!pressed)
                 {
                     evtData.dragging = false;
                 }
                 else if (!evtData.useDragThreshold)
                 {
                     evtData.dragging = true;
                 }
                 else
                 {
                     dragDistances[evtData.button] += evtData.delta.sqrMagnitude;
                     evtData.dragging = dragDistances[evtData.button] > pixelDragThresholdSquared;
                 }
                 if (evtData.dragging)
                 {
                     if (evtData.pointerPress != null && evtData.pointerPress != evtData.pointerDrag)
                     {
                         ExecuteEvents.Execute(evtData.pointerPress, evtData, ExecuteEvents.pointerUpHandler);
                         InteractionNeeded?.Invoke(Interaction.Released);
                         evtData.eligibleForClick = false;
                         evtData.pointerPress = null;
                         evtData.rawPointerPress = null;
                     }
                     if (!wasDragging)
                     {
                         ExecuteEvents.ExecuteHierarchy(evtData.pointerDrag, evtData, ExecuteEvents.beginDragHandler);
                         InteractionNeeded?.Invoke(Interaction.Dragged);
                     }
                     evtData.pointerDrag = ExecuteEvents.ExecuteHierarchy(evtData.pointerDrag ?? evtData.pointerPress, evtData, ExecuteEvents.dragHandler);
                     InteractionNeeded?.Invoke(Interaction.Dragged);
                 }
                 else if (wasDragging)
                 {
                     ExecuteEvents.ExecuteHierarchy(evtData.pointerDrag, evtData, ExecuteEvents.endDragHandler);
                     InteractionNeeded?.Invoke(Interaction.Dragged);
                     evtData.pointerDrag = null;
                 }
             }
         }
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process().
TestUpDown()
void Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.TestUpDown (PointerEventData evtData, ButtonIDType button, bool pressed) inline private
Definition at line 130 of file ButtonMapper.cs.
         {
             var up = ButtonUpNeeded?.Invoke(button) == true;
             var down = ButtonDownNeeded?.Invoke(button) == true;
             if (down)
             {
                 mayLongPress[button] = true;
                 buttonDownTime[button] = Time.time;
                 dragDistances[evtData.button] = 0;
                 evtData.rawPointerPress = evtData.pointerEnter;
                 evtData.pressPosition = evtData.position;
                 evtData.pointerPressRaycast = evtData.pointerCurrentRaycast;
                 evtData.eligibleForClick = true;
                 evtData.pointerDrag = ExecuteEvents.ExecuteHierarchy(evtData.pointerEnter, evtData, ExecuteEvents.initializePotentialDrag);
                 evtData.pointerPress = ExecuteEvents.ExecuteHierarchy(evtData.pointerEnter, evtData, ExecuteEvents.pointerDownHandler);
                 buttonEvents[button].OnDown(evtData);
                 inputButtonEvents[evtData.button]?.OnDown(evtData);
                 InteractionNeeded?.Invoke(Interaction.Pressed);
             }
             var deltaTime = buttonDownTime.ContainsKey(button)
                 ? Time.time - buttonDownTime[button]
                 : 0;
             evtData.eligibleForClick = buttonDownTime.ContainsKey(button)
                 && deltaTime < THRESHOLD_CLICK;
             if (up)
             {
                 ExecuteEvents.ExecuteHierarchy(evtData.pointerPress, evtData, ExecuteEvents.pointerUpHandler);
                 buttonEvents[button].OnUp(evtData);
                 inputButtonEvents[evtData.button]?.OnUp(evtData);
                 InteractionNeeded?.Invoke(Interaction.Released);
                 var target = evtData.pointerCurrentRaycast.gameObject;
                 if (evtData.eligibleForClick)
                 {
                     ++evtData.clickCount;
                     evtData.clickTime = Time.time;
                     evtData.selectedObject = ExecuteEvents.ExecuteHierarchy(evtData.pointerPress, evtData, ExecuteEvents.pointerClickHandler);
                     buttonEvents[button].OnClick(evtData);
                     inputButtonEvents[evtData.button]?.OnClick(evtData);
                     InteractionNeeded?.Invoke(Interaction.Clicked);
                 }
                 else if (evtData.pointerDrag != null)
                 {
                     ExecuteEvents.ExecuteHierarchy(target, evtData, ExecuteEvents.dropHandler);
                 }
                 evtData.pointerPress = null;
                 evtData.rawPointerPress = null;
             }
             else if(pressed
                 && mayLongPress[button])
             {
                 if (deltaTime < THRESHOLD_LONG_PRESS)
                 {
                     ExecuteEvents.ExecuteHierarchy(evtData.pointerPress, evtData, LongPressEvents.longPressUpdateHandler);
                 }
                 else
                 {
                     mayLongPress[button] = false;
                     ExecuteEvents.ExecuteHierarchy(evtData.pointerPress, evtData, LongPressEvents.longPressHandler);
                     buttonEvents[button].OnLongPress(evtData);
                     inputButtonEvents[evtData.button]?.OnLongPress(evtData);
                     InteractionNeeded?.Invoke(Interaction.Clicked);
                 }
             }
         }
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process().
ToInt32()
int Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.ToInt32 (ButtonIDType button)
Member Data Documentation
buttonDownTime
readonly Dictionary<ButtonIDType, float> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.buttonDownTime = new Dictionary<ButtonIDType, float>() private
Definition at line 23 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
buttonEvents
readonly Dictionary<ButtonIDType, ButtonEvent> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.buttonEvents = new Dictionary<ButtonIDType, ButtonEvent>()
Definition at line 33 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Install(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
Buttons
IEnumerable<ButtonIDType> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.Buttons
Initial value:
=>
            toInputButton.Keys
Definition at line 37 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process().
dragDistances
readonly Dictionary<InputButton, float> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.dragDistances = new Dictionary<InputButton, float>() private
Definition at line 25 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestDrag(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
fromInputButton
readonly Dictionary<InputButton, ButtonIDType> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.fromInputButton = new Dictionary<InputButton, ButtonIDType>() private
Definition at line 21 of file ButtonMapper.cs.
inputButtonEvents
readonly Dictionary<InputButton, ButtonEvent> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.inputButtonEvents = new Dictionary<InputButton, ButtonEvent>()
Definition at line 35 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Install(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
mayLongPress
readonly Dictionary<ButtonIDType, bool> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.mayLongPress = new Dictionary<ButtonIDType, bool>() private
Definition at line 24 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
THRESHOLD_CLICK
const float Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.THRESHOLD_CLICK = 0.4f private
Definition at line 17 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
THRESHOLD_LONG_PRESS
const float Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.THRESHOLD_LONG_PRESS = 2f private
Definition at line 18 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
toInputButton
readonly Dictionary<ButtonIDType, InputButton> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.toInputButton = new Dictionary<ButtonIDType, InputButton>() private
Definition at line 20 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Install(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process().
toInteger
readonly Dictionary<ButtonIDType, int> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.toInteger = new Dictionary<ButtonIDType, int>() private
Definition at line 22 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Install().
Property Documentation
AnyDragging
bool Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.AnyDragging get private set
Definition at line 40 of file ButtonMapper.cs.
 { get; private set; }
Referenced by Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestDrag().
Event Documentation
ButtonDownNeeded
Func<ButtonIDType, bool> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.ButtonDownNeeded
Definition at line 27 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
ButtonPressedNeeded
Func<ButtonIDType, bool> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.ButtonPressedNeeded
Definition at line 29 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process().
ButtonUpNeeded
Func<ButtonIDType, bool> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.ButtonUpNeeded
Definition at line 28 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
ClonedPointerEventNeeded
Func<PointerEventData, ButtonIDType, PointerEventData> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.ClonedPointerEventNeeded
Definition at line 30 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.Process().
InteractionNeeded
Action<Interaction> Juniper.Input.Pointers.ButtonMapper< ButtonIDType >.InteractionNeeded
Definition at line 31 of file ButtonMapper.cs.
Referenced by Juniper.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Awake(), Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestDrag(), and Juniper.Input.Pointers.ButtonMapper< VirtualTouchPadButton >.TestUpDown().
The documentation for this class was generated from the following file:
Assets/Juniper/Scripts/Unity/Input/Pointers/ButtonMapper.cs