Juniper: Juniper.Anchoring.WindowsMRAnchorStore Class Reference
Juniper.Anchoring.WindowsMRAnchorStore Class Reference
Public Member Functions
void Awake ()
Acquires the anchorStore
override bool HasAnchor (string anchorID)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store.
virtual void ResetData ()
Delete all saved anchors, if there are any.
bool DropAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
void WeighAnchor (string ID, GameObject gameObject)
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Protected Member Functions
override bool IsSaved (AnchorType anchor)
Checks to see if an anchor has been saved in the data store.
override AnchorType CreateAnchor (string ID, GameObject gameObject)
Creates a new anchor.
override AnchorType LoadAnchor (string ID)
Loads an anchor out of a platform-specific anchor data store.
override bool IsGood (AnchorType anchor)
Checks to see if an anchor is valid.
override void DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor)
Removes an anchor along with its scale from the data store.
virtual AnchorType SynchronizeAnchor (string ID, GameObject gameObject)
Looks to see if the anchor was already in the data store, then loads it along with the objects scale if it was, or creates it and saves the scale if it wasn't.
virtual AnchorType FindAnchor (GameObject gameObject)
Finds any anchor components on the given object
Static Protected Member Functions
static string MakeID (string name)
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
static bool HasValue (string name)
Check to see if a given name exists in the data store.
static void SaveValue< T > (string name, T value)
Saves a value to the data store.
static T LoadValue< T > (string name)
Gets a value back out of data store.
static bool DeleteValue (string name)
Removes a value from the data store.
Private Attributes
WorldAnchorStore anchorStore
The collection in which anchors are stored. This value's type changes depending on certain compilation flags.
Detailed Description
Definition at line 11 of file WindowsMRAnchorStore.cs.
Member Function Documentation
Awake()
void Juniper.Anchoring.WindowsMRAnchorStore.Awake () inline
Acquires the anchorStore
Definition at line 22 of file WindowsMRAnchorStore.cs.
         {
             WorldAnchorStore.GetAsync(new WorldAnchorStore.GetAsyncDelegate(store =>
                 anchorStore = store));
         }
References Juniper.Anchoring.WindowsMRAnchorStore.anchorStore.
CreateAnchor()
override AnchorType Juniper.Anchoring.WindowsMRAnchorStore.CreateAnchor (string ID, GameObject gameObject) inline protected virtual
Creates a new anchor.
Parameters
ID The name of the anchor to create.
gameObject The object to be anchored.
Returns
The new anchor.
Implements Juniper.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 38 of file WindowsMRAnchorStore.cs.
         {
             var anchor = gameObject.Ensure<AnchorType>();
             anchorStore.Save(ID, anchor);
             return anchor;
         }
References Juniper.Anchoring.WindowsMRAnchorStore.anchorStore.
DeleteAnchor()
override void Juniper.Anchoring.WindowsMRAnchorStore.DeleteAnchor (string ID, GameObject gameObject, AnchorType anchor) inline protected virtual
Removes an anchor along with its scale from the data store.
Parameters
ID The name of the anchor to remove
gameObject The object that was anchored
anchor The anchor to destroy
Reimplemented from Juniper.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 55 of file WindowsMRAnchorStore.cs.
         {
             anchor.Destroy();
             anchorStore.Delete(ID);
         }
References Juniper.Anchoring.WindowsMRAnchorStore.anchorStore.
DeleteValue()
static bool Juniper.Anchoring.AbstractAnchorStore< AnchorType >.DeleteValue (string name) inline static protected inherited
Removes a value from the data store.
Parameters
name
Returns
Definition at line 102 of file AbstractAnchorStore`1.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 PlayerPrefs.DeleteKey(key);
                 NameList = NameList.Remove(name);
                 PlayerPrefs.Save();
                 return true;
             }
             else
             {
                 return false;
             }
         }
Referenced by Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DeleteAnchor(), Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.LoadValue< T >(), Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.ResetData(), and Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.WeighAnchor().
DropAnchor()
bool Juniper.Anchoring.AbstractAnchorStore< AnchorType >.DropAnchor (string ID, GameObject gameObject) inline inherited
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method creates the native anchor type for any given subsystem, and save it to its native anchor store.
Returns
true, if anchor existed on the object, existed in the data-store, or was successfully created, false otherwise.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 178 of file AbstractAnchorStore`1.cs.
         {
             if (string.IsNullOrEmpty(ID))
             {
                 throw new ArgumentException("Parameter must have a value.", nameof(ID));
             }
             var anchor = FindAnchor(gameObject);
             if (!IsSaved(anchor))
             {
                 anchor = SynchronizeAnchor(ID, gameObject);
             }
             return IsGood(anchor);
         }
Referenced by Juniper.Anchoring.Anchored.DropAnchor().
FindAnchor()
virtual AnchorType Juniper.Anchoring.AbstractAnchorStore< AnchorType >.FindAnchor (GameObject gameObject) inline protected virtual inherited
Finds any anchor components on the given object
Parameters
gameObject The object that might have an anchor on it
Returns
Reimplemented in Juniper.Anchoring.ARKitAnchorStore.
Definition at line 272 of file AbstractAnchorStore`1.cs.
         {
             if (gameObject == null)
             {
                 return default;
             }
             else
             {
                 return gameObject.GetComponent<AnchorType>();
             }
         }
Referenced by Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DropAnchor(), and Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.WeighAnchor().
HasAnchor()
override bool Juniper.Anchoring.WindowsMRAnchorStore.HasAnchor (string anchorID) inline virtual
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method checks to see if a given anchor exists in the anchor data store.
Returns
true, if anchor exists, false otherwise.
Parameters
anchorID Anchor identifier.
Implements Juniper.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 28 of file WindowsMRAnchorStore.cs.
         {
             return anchorStore != null && anchorStore.GetAllIds().Contains(anchorID);
         }
References Juniper.Anchoring.WindowsMRAnchorStore.anchorStore.
HasValue()
static bool Juniper.Anchoring.AbstractAnchorStore< AnchorType >.HasValue (string name) inline static protected inherited
Check to see if a given name exists in the data store.
Parameters
name
Returns
Definition at line 46 of file AbstractAnchorStore`1.cs.
         {
             return PlayerPrefs.HasKey(MakeID(name));
         }
Referenced by Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.SynchronizeAnchor().
IsGood()
override bool Juniper.Anchoring.WindowsMRAnchorStore.IsGood (AnchorType anchor) inline protected virtual
Checks to see if an anchor is valid.
Parameters
anchor
Returns
Reimplemented from Juniper.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 50 of file WindowsMRAnchorStore.cs.
         {
             return base.IsGood(anchor) && anchor.isLocated;
         }
IsSaved()
override bool Juniper.Anchoring.WindowsMRAnchorStore.IsSaved (AnchorType anchor) inline protected virtual
Checks to see if an anchor has been saved in the data store.
Parameters
anchor The anchor to check against the data store
Returns
True, if the anchor has already been saved, false otherwise
Reimplemented from Juniper.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 33 of file WindowsMRAnchorStore.cs.
         {
             return base.IsSaved(anchor) || anchorStore == null;
         }
References Juniper.Anchoring.WindowsMRAnchorStore.anchorStore.
LoadAnchor()
override AnchorType Juniper.Anchoring.WindowsMRAnchorStore.LoadAnchor (string ID) inline protected virtual
Loads an anchor out of a platform-specific anchor data store.
Parameters
ID The name of the anchor to load.
Returns
The persisted anchor.
Implements Juniper.Anchoring.AbstractAnchorStore< AnchorType >.
Definition at line 45 of file WindowsMRAnchorStore.cs.
         {
             return anchorStore.Load(ID, gameObject);
         }
References Juniper.Anchoring.WindowsMRAnchorStore.anchorStore.
LoadValue< T >()
static T Juniper.Anchoring.AbstractAnchorStore< AnchorType >.LoadValue< T > (string name) inline static protected inherited
Gets a value back out of data store.
Template Parameters
T
Parameters
name
Returns
Definition at line 78 of file AbstractAnchorStore`1.cs.
         {
             var key = MakeID(name);
             if (PlayerPrefs.HasKey(key))
             {
                 try
                 {
                     var json = new JsonFactory<T>();
                     return json.Parse(PlayerPrefs.GetString(key));
                 }
                 catch
                 {
                     DeleteValue(name);
                 }
             }
             return default;
         }
MakeID()
static string Juniper.Anchoring.AbstractAnchorStore< AnchorType >.MakeID (string name) inline static protected inherited
Makes an identifier for storing values in that are unique to AbstractAnchorStore so that AbstractAnchorStore can delete them later, when the user requests all anchors be deleted.
Parameters
name A controllable part of the name, to be modified to be unique in the data store.
Returns
A name in the data store unique to AbstractAnchorStore.
Definition at line 31 of file AbstractAnchorStore`1.cs.
         {
             return ID_PREFIX + name;
         }
Referenced by Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DeleteValue(), Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.HasValue(), Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.LoadValue< T >(), and Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.SaveValue< T >().
ResetData()
virtual void Juniper.Anchoring.AbstractAnchorStore< AnchorType >.ResetData () inline virtual inherited
Delete all saved anchors, if there are any.
Reimplemented in Juniper.Anchoring.ARKitAnchorStore.
Definition at line 156 of file AbstractAnchorStore`1.cs.
         {
             foreach (var name in NameList)
             {
                 DeleteValue(name);
             }
             NameList = null;
         }
SaveValue< T >()
static void Juniper.Anchoring.AbstractAnchorStore< AnchorType >.SaveValue< T > (string name, T value) inline static protected inherited
Saves a value to the data store.
Parameters
name The name of the object to save.
value The value to save.
Definition at line 56 of file AbstractAnchorStore`1.cs.
         {
             var json = new JsonFactory<T>();
             PlayerPrefs.SetString(MakeID(name), json.ToString(value));
             var names = NameList;
             if (!names.Contains(name))
             {
                 var n = names.ToList();
                 n.Add(name);
                 NameList = n.ToArray();
             }
             PlayerPrefs.Save();
         }
SynchronizeAnchor()
virtual AnchorType Juniper.Anchoring.AbstractAnchorStore< AnchorType >.SynchronizeAnchor (string ID, GameObject gameObject) inline protected virtual inherited
Looks to see if the anchor was already in the data store, then loads it along with the objects scale if it was, or creates it and saves the scale if it wasn't.
Parameters
ID The name of the object to serialize
gameObject The object that is being anchored
Returns
The synchronized anchor
Reimplemented in Juniper.Anchoring.ARKitAnchorStore.
Definition at line 201 of file AbstractAnchorStore`1.cs.
         {
             var scaleID = ID + "-scale";
             AnchorType anchor;
             if (HasAnchor(ID))
             {
                 anchor = LoadAnchor(ID);
                 if (HasValue(scaleID))
                 {
                     var arr = LoadValue<float[]>(scaleID);
                     gameObject.transform.localScale = new Vector3(arr[0], arr[1], arr[2]);
                 }
             }
             else
             {
                 anchor = CreateAnchor(ID, gameObject);
                 var arr = new float[]
                 {
                     gameObject.transform.localScale.x, gameObject.transform.localScale.y, gameObject.transform.localScale.z
                 };
                 SaveValue(scaleID, arr);
             }
             return anchor;
         }
Referenced by Juniper.Anchoring.AbstractAnchorStore< MockWorldAnchor >.DropAnchor().
WeighAnchor()
void Juniper.Anchoring.AbstractAnchorStore< AnchorType >.WeighAnchor (string ID, GameObject gameObject) inline inherited
Anchors provide a means to restore the position of objects between sessions. In some AR systems, they also provide a means of prioritizing the stability of the location of specific objects. This method removes the anchor from the gameObject and delete it out of their native anchor store.
Parameters
ID Identifier.
gameObject Game object.
Definition at line 245 of file AbstractAnchorStore`1.cs.
         {
             var anchor = FindAnchor(gameObject);
             if (anchor != null)
             {
                 DeleteAnchor(ID, gameObject, anchor);
                 DeleteValue(ID + "-scale");
             }
         }
Referenced by Juniper.Anchoring.Anchored.WeighAnchor().
Member Data Documentation
anchorStore
WorldAnchorStore Juniper.Anchoring.WindowsMRAnchorStore.anchorStore private
The collection in which anchors are stored. This value's type changes depending on certain compilation flags.
Definition at line 17 of file WindowsMRAnchorStore.cs.
Referenced by Juniper.Anchoring.WindowsMRAnchorStore.Awake(), Juniper.Anchoring.WindowsMRAnchorStore.CreateAnchor(), Juniper.Anchoring.WindowsMRAnchorStore.DeleteAnchor(), Juniper.Anchoring.WindowsMRAnchorStore.HasAnchor(), Juniper.Anchoring.WindowsMRAnchorStore.IsSaved(), and Juniper.Anchoring.WindowsMRAnchorStore.LoadAnchor().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Scripts/Platforms/WindowsMR/WindowsMRAnchorStore.cs