Juniper: Juniper.World.Climate.OpenWeatherMap.API Class Reference
Juniper.World.Climate.OpenWeatherMap.API Class Reference
An implementation of OpenWeatherMap's REST API.
Classes
class Error
Encapsulates an error response from the API server. Objects of this type are Serializable.
Public Member Functions
API (string apiKey, string lastReportJSON=null)
Initialize a new API requester object with the given authentication API key.
async void Request (LatLngPoint location, bool force, IProgress prog=null)
Initiate a new request for a weather report at a given location.
Properties
IWeatherReport LastReport [get, private set]
Get the last weather report that was retrieved for the server.
float ReportTTLMinutes [get, set]
The amount of time, in minutes, to allow to pass between requesting reports.
float ReportRadiusMeters [get, set]
The radius, in meters, to allow the user to travel before we request a new report outside of the normal ReportTTLMinutes time frame.
Private Member Functions
bool NeedsNewReport (LatLngPoint location)
Returns true when LastReport is null, LastReport indicates and error occurred, the time since the last report exceeds the ReportTTLMinutes, or the distance from location to the last report's location is more than ReportRadiusMeters.
Private Attributes
const string serverURI = "https://api.openweathermap.org"
The host for the service.
const string operation = "weather"
The directory in which to find the API on the host.
const string units = "metric"
Units of measure to request from the API.
readonly string apiKey
The key to authenticate with the API
Static Private Attributes
static readonly Version version = new Version(2, 5)
The version number of the service we're targeting.
Detailed Description
An implementation of OpenWeatherMap's REST API.
Definition at line 18 of file API.cs.
Constructor & Destructor Documentation
API()
Juniper.World.Climate.OpenWeatherMap.API.API (string apiKey, string lastReportJSON = null) inline
Initialize a new API requester object with the given authentication API key.
Parameters
apiKey The OpenWeatherMap API key to use for authentication.
lastReportJSON The value of the last report we received, if there was any.
Definition at line 75 of file API.cs.
         {
             this.apiKey = apiKey;
             if (lastReportJSON != null)
             {
                 LastReport = JsonConvert.DeserializeObject<WeatherReport>(lastReportJSON);
             }
         }
References Juniper.World.Climate.OpenWeatherMap.API.apiKey, and Juniper.World.Climate.OpenWeatherMap.API.LastReport.
Member Function Documentation
NeedsNewReport()
bool Juniper.World.Climate.OpenWeatherMap.API.NeedsNewReport (LatLngPoint location) inline private
Returns true when LastReport is null, LastReport indicates and error occurred, the time since the last report exceeds the ReportTTLMinutes, or the distance from location to the last report's location is more than ReportRadiusMeters.
Parameters
location
Returns
Definition at line 93 of file API.cs.
         {
             if (LastReport == null || LastReport.ErrorMessage != null)
             {
                 return true;
             }
             else
             {
                 var dt = DateTime.Now - LastReport.ReportTime;
                 var distanceMeters = location.Distance(LastReport.Location);
                 return dt.TotalMinutes >= ReportTTLMinutes || distanceMeters >= ReportRadiusMeters;
             }
         }
References Juniper.Climate.IWeatherReport.ErrorMessage, Juniper.World.Climate.OpenWeatherMap.API.LastReport, Juniper.Climate.IWeatherReport.Location, Juniper.World.Climate.OpenWeatherMap.API.ReportRadiusMeters, Juniper.Climate.IWeatherReport.ReportTime, and Juniper.World.Climate.OpenWeatherMap.API.ReportTTLMinutes.
Referenced by Juniper.World.Climate.OpenWeatherMap.API.Request().
Request()
async void Juniper.World.Climate.OpenWeatherMap.API.Request (LatLngPoint location, bool force, IProgress prog = null) inline
Initiate a new request for a weather report at a given location.
Parameters
location The current location for which to retrieve a report. Reports need to be at least ReportTTLMinutes minutes or ReportRadiusMeters meters apart.
force Force downloading a new report, regardless of how far we are from the last report location.
prog A progress tracker, if any.
Returns
Implements Juniper.Climate.IWeatherAPI.
Definition at line 166 of file API.cs.
         {
             if (NeedsNewReport(location) || force)
             {
                 string reportJSON = null;
                 var url = $"{serverURI}/data/{version.ToString(2)}/{operation}?lat={location.Latitude}&lon={location.Longitude}&units={units}&appid={apiKey}";
                 try
                 {
                     var results = await Requester.GetStream(url, "application/json", prog);
                     var httpStatus = results.Status;
                     var report = results.Value.ReadObject<WeatherReport>();
                     if (report == null)
                     {
                         var errorObj = new Error("GetNewReport", "No response: " + url);
                         reportJSON = JsonConvert.SerializeObject(errorObj);
                         LastReport = JsonConvert.DeserializeObject<WeatherReport>(reportJSON);
                     }
                     else
                     {
                         reportJSON = JsonConvert.SerializeObject(report);
                         LastReport = report;
                     }
                 }
                 catch (Exception exp)
                 {
                     var errorObj = new Error("GetNewReport", exp.Message + ": " + url);
                     reportJSON = JsonConvert.SerializeObject(errorObj);
                     LastReport = JsonConvert.DeserializeObject<WeatherReport>(reportJSON);
                 }
             }
             else
             {
                 prog?.Report(1);
             }
         }
References Juniper.HTTP.Requester.GetStream(), Juniper.World.Climate.OpenWeatherMap.API.LastReport, and Juniper.World.Climate.OpenWeatherMap.API.NeedsNewReport().
Member Data Documentation
apiKey
readonly string Juniper.World.Climate.OpenWeatherMap.API.apiKey private
The key to authenticate with the API
Definition at line 43 of file API.cs.
Referenced by Juniper.World.Climate.OpenWeatherMap.API.API().
operation
const string Juniper.World.Climate.OpenWeatherMap.API.operation = "weather" private
The directory in which to find the API on the host.
Definition at line 33 of file API.cs.
serverURI
const string Juniper.World.Climate.OpenWeatherMap.API.serverURI = "https://api.openweathermap.org" private
The host for the service.
Definition at line 23 of file API.cs.
units
const string Juniper.World.Climate.OpenWeatherMap.API.units = "metric" private
Units of measure to request from the API.
Definition at line 38 of file API.cs.
version
readonly Version Juniper.World.Climate.OpenWeatherMap.API.version = new Version(2, 5) static private
The version number of the service we're targeting.
Definition at line 28 of file API.cs.
Property Documentation
LastReport
IWeatherReport Juniper.World.Climate.OpenWeatherMap.API.LastReport get private set
Get the last weather report that was retrieved for the server.
Definition at line 49 of file API.cs.
         {
             get; private set;
         }
Referenced by Juniper.World.Climate.OpenWeatherMap.API.API(), Juniper.World.Climate.OpenWeatherMap.API.NeedsNewReport(), and Juniper.World.Climate.OpenWeatherMap.API.Request().
ReportRadiusMeters
float Juniper.World.Climate.OpenWeatherMap.API.ReportRadiusMeters get set
The radius, in meters, to allow the user to travel before we request a new report outside of the normal ReportTTLMinutes time frame.
Definition at line 66 of file API.cs.
         {
             get; set;
         }
Referenced by Juniper.World.Climate.OpenWeatherMap.API.NeedsNewReport().
ReportTTLMinutes
float Juniper.World.Climate.OpenWeatherMap.API.ReportTTLMinutes get set
The amount of time, in minutes, to allow to pass between requesting reports.
Definition at line 57 of file API.cs.
         {
             get; set;
         }
Referenced by Juniper.World.Climate.OpenWeatherMap.API.NeedsNewReport().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/World/Climate/OpenWeatherMap/API.cs