Juniper: Juniper.Unity.Input.WindowsMRInputModule Class Reference
Juniper.Unity.Input.WindowsMRInputModule Class Reference
Public Member Functions
override void UpdateModule ()
Manages the input controllers, either motion controllers on WindowsMR headsets, or hand tracking on HoloLens.
void AddPointer (IPointerDevice pointer)
void WithPointer (Action< IPointerDevice > onPointerAvailable)
virtual void Reinstall ()
override void Process ()
Find all the pointers and fire raycaster events for them.
PointerEventData Clone (PointerEventData original, int offset)
virtual bool Install (bool reset)
virtual void Uninstall ()
Public Attributes
readonly List< IPointerDevice > Devices = new List<IPointerDevice>()
GameObject pointerPrefab
Set to the clonable object that should be used for the pointer probe.
PointerFoundEvent onPointerFound
Protected Member Functions
override void Awake ()
Protected Attributes
StageExtensions stage
Properties
bool AnyPointerDragging [get]
Events
EventHandler< PointerFoundEventArgs > PointerFound
Detailed Description
Definition at line 10 of file WindowsMRInputModule.cs.
Member Function Documentation
AddPointer()
void Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer (IPointerDevice pointer) inline inherited
Definition at line 45 of file AbstractUnifiedInputModule.cs.
         {
             if (!Devices.Contains(pointer) && !newDevices.Contains(pointer))
             {
                 pointer.PointerID = Devices.Count * 10000;
                 newDevices.Add(pointer);
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices, and Juniper.Unity.Input.Pointers.IPointerDevice.PointerID.
Referenced by Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Start().
Awake()
override void Juniper.Unity.Input.AbstractUnifiedInputModule.Awake () inline protected inherited
Definition at line 78 of file AbstractUnifiedInputModule.cs.
         {
             base.Awake();
             Install(false);
             stage = ComponentExt.FindAny<StageExtensions>();
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Install(), and Juniper.Unity.Input.AbstractUnifiedInputModule.stage.
Clone()
PointerEventData Juniper.Unity.Input.AbstractUnifiedInputModule.Clone (PointerEventData original, int offset) inline inherited
Definition at line 174 of file AbstractUnifiedInputModule.cs.
         {
             PointerEventData clone;
             GetPointerData(original.pointerId + offset, out clone, true);
             clone.delta = original.delta;
             clone.position = original.position;
             clone.scrollDelta = original.scrollDelta;
             clone.pointerEnter = original.pointerEnter;
             clone.useDragThreshold = original.useDragThreshold;
             clone.pointerCurrentRaycast = original.pointerCurrentRaycast;
             if (original.clickCount == -1)
             {
                 clone.eligibleForClick = false;
                 clone.clickCount = 0;
             }
             return clone;
         }
Referenced by Juniper.Unity.Input.Pointers.Motion.AbstractMotionController< Unary, KeyCode, NoMotionControllerConfiguration, NoHaptics >.Clone(), and Juniper.Unity.Input.Pointers.AbstractPointerDevice< ButtonIDType, HapticsType, ConfigType >.Clone().
Install()
virtual bool Juniper.Unity.Input.AbstractUnifiedInputModule.Install (bool reset) inline virtual inherited
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Input.DaydreamInputModule, and Juniper.Unity.Input.OculusInputModule.
Definition at line 267 of file AbstractUnifiedInputModule.cs.
         {
             reset &= Application.isEditor;
 #if UNITY_EDITOR
             if (pointerPrefab == null)
             {
 #if UNITY_2018_2_OR_NEWER
                 pointerPrefab = ComponentExt.EditorLoadAsset<GameObject>("Assets/Juniper/Prefabs/Rigs/DiskProbe2018.2.prefab");
 #else
                 pointerPrefab = ComponentExt.EditorLoadAsset<GameObject>("Assets/Juniper/Prefabs/Rigs/DiskProbe2018.1.prefab");
 #endif
             }
 #endif
                 return true;
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.pointerPrefab.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake(), and Juniper.Unity.Input.AbstractUnifiedInputModule.Reinstall().
Process()
override void Juniper.Unity.Input.AbstractUnifiedInputModule.Process () inline inherited
Find all the pointers and fire raycaster events for them.
Definition at line 147 of file AbstractUnifiedInputModule.cs.
         {
             foreach (var pointer in newDevices)
             {
                 Devices.Add(pointer);
                 OnPointerFound(pointer);
             }
             newDevices.Clear();
             foreach (var pointer in Devices)
             {
                 if (pointer.IsEnabled)
                 {
                     PointerEventData evtData;
                     GetPointerData(pointer.PointerID, out evtData, true);
                     evtData.delta = pointer.ScreenDelta;
                     evtData.position = pointer.ScreenPoint;
                     evtData.scrollDelta = pointer.ScrollDelta;
                     evtData.useDragThreshold = eventSystem.pixelDragThreshold > 0;
                     evtData.pointerCurrentRaycast = UpdateRay(pointer, evtData);
                     pointer.Process(evtData, eventSystem.pixelDragThreshold * eventSystem.pixelDragThreshold);
                 }
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, Juniper.Unity.Input.AbstractUnifiedInputModule.newDevices, Juniper.Unity.Input.AbstractUnifiedInputModule.OnPointerFound(), and Juniper.Unity.Input.AbstractUnifiedInputModule.UpdateRay().
Reinstall()
virtual void Juniper.Unity.Input.AbstractUnifiedInputModule.Reinstall () inline virtual inherited
Implements Juniper.IInstallable.
Definition at line 87 of file AbstractUnifiedInputModule.cs.
         {
             Install(true);
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
Uninstall()
virtual void Juniper.Unity.Input.AbstractUnifiedInputModule.Uninstall () inline virtual inherited
Implements Juniper.IInstallable.
Reimplemented in Juniper.Unity.Input.DaydreamInputModule, and Juniper.Unity.Input.OculusInputModule.
Definition at line 285 of file AbstractUnifiedInputModule.cs.
         {
         }
UpdateModule()
override void Juniper.Unity.Input.WindowsMRInputModule.UpdateModule () inline
Manages the input controllers, either motion controllers on WindowsMR headsets, or hand tracking on HoloLens.
Definition at line 16 of file WindowsMRInputModule.cs.
         {
             base.UpdateModule();
             Pointers.Motion.MotionController.UpdateReadings();
         }
WithPointer()
void Juniper.Unity.Input.AbstractUnifiedInputModule.WithPointer (Action< IPointerDevice > onPointerAvailable) inline inherited
Definition at line 54 of file AbstractUnifiedInputModule.cs.
         {
             if (Devices.Count > 0)
             {
                 onPointerAvailable(Devices[0]);
             }
             else
             {
                 EventHandler<PointerFoundEventArgs> subAct = null;
                 subAct = new EventHandler<PointerFoundEventArgs>((sender, args) =>
                 {
                     PointerFound -= subAct;
                     onPointerAvailable(args.device);
                 });
                 PointerFound += subAct;
             }
         }
References Juniper.Unity.Input.AbstractUnifiedInputModule.Devices, and Juniper.Unity.Input.AbstractUnifiedInputModule.PointerFound.
Referenced by Juniper.Unity.Input.HoverCraft.Awake().
Member Data Documentation
Devices
readonly List<IPointerDevice> Juniper.Unity.Input.AbstractUnifiedInputModule.Devices = new List<IPointerDevice>() inherited
Definition at line 18 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.AddPointer(), Juniper.Unity.Input.AbstractUnifiedInputModule.Process(), and Juniper.Unity.Input.AbstractUnifiedInputModule.WithPointer().
onPointerFound
PointerFoundEvent Juniper.Unity.Input.AbstractUnifiedInputModule.onPointerFound inherited
Definition at line 41 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.OnPointerFound().
pointerPrefab
GameObject Juniper.Unity.Input.AbstractUnifiedInputModule.pointerPrefab inherited
Set to the clonable object that should be used for the pointer probe.
Definition at line 39 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Install().
stage
StageExtensions Juniper.Unity.Input.AbstractUnifiedInputModule.stage protected inherited
Definition at line 76 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.Awake().
Property Documentation
AnyPointerDragging
bool Juniper.Unity.Input.AbstractUnifiedInputModule.AnyPointerDragging get inherited
Definition at line 21 of file AbstractUnifiedInputModule.cs.
         {
             get
             {
                 foreach (var device in Devices)
                 {
                     if (device.IsDragging)
                     {
                         return true;
                     }
                 }
                 return false;
             }
         }
Referenced by Juniper.Unity.Input.CameraControl.Update().
Event Documentation
PointerFound
EventHandler<PointerFoundEventArgs> Juniper.Unity.Input.AbstractUnifiedInputModule.PointerFound inherited
Definition at line 43 of file AbstractUnifiedInputModule.cs.
Referenced by Juniper.Unity.Input.AbstractUnifiedInputModule.OnPointerFound(), and Juniper.Unity.Input.AbstractUnifiedInputModule.WithPointer().
The documentation for this class was generated from the following file:
C:/Users/sean/Projects/Juniper/src/Juniper/Assets/Juniper/Scripts/Unity/Platforms/WindowsMR/WindowsMRInputModule.cs