Juniper: Juniper.ConfigurationManagement.JuniperCompilerDefineManager Class Reference
Juniper.ConfigurationManagement.JuniperCompilerDefineManager Class Reference
An editor to respond to changes in XRSystem.
Public Member Functions
void OnGUI ()
Static Public Member Functions
static void ShowJuniperWindow ()
Private Attributes
const string MENU_NAME = "Juniper/"
const float narrowWidthValue = 50
Static Private Attributes
static readonly GUIContent TITLE = new GUIContent("Juniper - Compiler Define Symbols")
static string newDefine
static readonly GUILayoutOption narrowWidth = GUILayout.Width(narrowWidthValue)
static readonly GUILayoutOption buttonWidth = GUILayout.Width(100)
static readonly TableView definesTable
Detailed Description
An editor to respond to changes in XRSystem.
Definition at line 21 of file JuniperCompilerDefineManager.cs.
Member Function Documentation
OnGUI()
void Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI () inline
Definition at line 46 of file JuniperCompilerDefineManager.cs.
         {
             titleContent = TITLE;
             var platforms = Platforms.Load();
             var selectedPlatform = ProjectConfiguration.Platform;
             var currentConfiguration = platforms.Configurations[selectedPlatform];
             var requiredDefines = currentConfiguration.GetCompilerDefines();
             var curDefines = Project.GetDefines();
             var allDefines = curDefines
                 .Union(requiredDefines)
                 .Distinct()
                 .OrderBy(Always.Identity)
                 .ToArray();
             using (definesTable.Begin())
             {
                 using (new HGroup())
                 {
                     newDefine = EditorGUILayout.TextField(newDefine);
                     EditorGUILayout.LabelField(string.Empty, narrowWidth);
                     if (GUILayout.Button("Add", buttonWidth))
                     {
                         if (!string.IsNullOrEmpty(newDefine))
{
                             Project.AddCompilerDefine(newDefine);
                         }
                         newDefine = string.Empty;
                     }
                 }
                 foreach (var define in allDefines)
                 {
                     using (new HGroup())
                     {
                         EditorGUILayout.LabelField(new GUIContent(define, define));
                         EditorGUILayout.LabelField(
                             requiredDefines.Contains(define).ToYesNo(),
                             EditorStyles.centeredGreyMiniLabel,
                             narrowWidth);
                         var isCurrent = curDefines.Contains(define);
                         using (new EnabledScope(!isCurrent))
{
                             if (GUILayout.Button("Add", buttonWidth))
{
                                 Project.AddCompilerDefine(define);
                             }
                         }
                         using (new EnabledScope(isCurrent))
{
                             if (GUILayout.Button("Remove", buttonWidth))
{
                                 Project.RemoveCompilerDefine(define);
                             }
                         }
                     }
                 }
             }
         }
References Juniper.ConfigurationManagement.Project.AddCompilerDefine(), UnityEditor.TableView.Begin(), Juniper.ConfigurationManagement.JuniperCompilerDefineManager.buttonWidth, Juniper.ConfigurationManagement.JuniperCompilerDefineManager.definesTable, Juniper.ConfigurationManagement.Project.GetDefines(), Juniper.ConfigurationManagement.Platforms.Load(), Juniper.ConfigurationManagement.JuniperCompilerDefineManager.narrowWidth, Juniper.ConfigurationManagement.JuniperCompilerDefineManager.newDefine, Juniper.ProjectConfiguration.Platform, Juniper.ConfigurationManagement.Project.RemoveCompilerDefine(), and Juniper.ConfigurationManagement.JuniperCompilerDefineManager.TITLE.
ShowJuniperWindow()
static void Juniper.ConfigurationManagement.JuniperCompilerDefineManager.ShowJuniperWindow () inline static
Definition at line 24 of file JuniperCompilerDefineManager.cs.
         {
             EditorWindow.GetWindow<JuniperCompilerDefineManager>();
         }
Member Data Documentation
buttonWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperCompilerDefineManager.buttonWidth = GUILayout.Width(100) static private
Definition at line 37 of file JuniperCompilerDefineManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI().
definesTable
readonly TableView Juniper.ConfigurationManagement.JuniperCompilerDefineManager.definesTable static private
Initial value:
= new TableView(
            "Defines - " + ProjectConfiguration.Platform,
            ("Define", null),
            ("Required", buttonWidth)
        )
Definition at line 39 of file JuniperCompilerDefineManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI().
MENU_NAME
const string Juniper.ConfigurationManagement.JuniperCompilerDefineManager.MENU_NAME = "Juniper/" private
Definition at line 30 of file JuniperCompilerDefineManager.cs.
narrowWidth
readonly GUILayoutOption Juniper.ConfigurationManagement.JuniperCompilerDefineManager.narrowWidth = GUILayout.Width(narrowWidthValue) static private
Definition at line 36 of file JuniperCompilerDefineManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI().
narrowWidthValue
const float Juniper.ConfigurationManagement.JuniperCompilerDefineManager.narrowWidthValue = 50 private
Definition at line 34 of file JuniperCompilerDefineManager.cs.
newDefine
string Juniper.ConfigurationManagement.JuniperCompilerDefineManager.newDefine static private
Definition at line 32 of file JuniperCompilerDefineManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI().
TITLE
readonly GUIContent Juniper.ConfigurationManagement.JuniperCompilerDefineManager.TITLE = new GUIContent("Juniper - Compiler Define Symbols") static private
Definition at line 29 of file JuniperCompilerDefineManager.cs.
Referenced by Juniper.ConfigurationManagement.JuniperCompilerDefineManager.OnGUI().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Unity Editor Plugins/ConfigurationManagement/JuniperCompilerDefineManager.cs