Juniper: Juniper.Collections.PriorityStack< T > Class Template Reference
Juniper.Collections.PriorityStack< T > Class Template Reference
A stack data structure that places emphasis on some items over others.
Classes
class PQComparer
A default Comparer to use when a comparer is not defined. If the type implements the IComparable<T> or IComparable interface, then it will use the object's own CompareTo method.
Public Member Functions
PriorityStack ()
Default constructor, uses natural ordering comparator for objects
PriorityStack (IEnumerable< T > values)
PriorityStack (IComparer< T > comparer)
Constructor using explicit comparer for objects
PriorityStack (IComparer< T > comparer, IEnumerable< T > values)
void Clear ()
removes all the objects from the priority stack
bool Contains (T item)
Performs a linear search for the provided item.
T Peek ()
Returns an item from the front of the stack without removing it
T Pop ()
Removes an item from the front of the stack
void Push (T item)
Adds an item to the stack, using the natural order of the object type if no Comparer is provided during construction of the PriorityStack.
IEnumerator< T > GetEnumerator ()
Retrieves a generic enumerator over the objects of the stack
T [] ToArray ()
Create an array out of the stack
Public Attributes
int Count => stack.Count
get the number of elements in the collection
Properties
IComparer< T > Comparer [get]
Retrieve the comparer to use with the objects being added to the stack
Private Member Functions
IEnumerator IEnumerable. GetEnumerator ()
Retrieves an enumerator over the objects of the stack
Private Attributes
readonly List< T > stack = new List<T>()
Detailed Description
A stack data structure that places emphasis on some items over others.
Template Parameters
T The type of objects that will be placed in the PriorityStack
Type Constraints
T : IComparable<T>
Definition at line 11 of file PriorityStack.cs.
Constructor & Destructor Documentation
PriorityStack() [1/4]
Juniper.Collections.PriorityStack< T >.PriorityStack () inline
Default constructor, uses natural ordering comparator for objects
Definition at line 30 of file PriorityStack.cs.
             : this(new PQComparer(), Array.Empty<T>())
         { }
PriorityStack() [2/4]
Juniper.Collections.PriorityStack< T >.PriorityStack (IEnumerable< T > values) inline
Definition at line 34 of file PriorityStack.cs.
             : this(new PQComparer(), values)
         { }
PriorityStack() [3/4]
Juniper.Collections.PriorityStack< T >.PriorityStack (IComparer< T > comparer) inline
Constructor using explicit comparer for objects
Parameters
comparer
Definition at line 42 of file PriorityStack.cs.
             : this(comparer, Array.Empty<T>())
         { }
PriorityStack() [4/4]
Juniper.Collections.PriorityStack< T >.PriorityStack (IComparer< T > comparer, IEnumerable< T > values) inline
Definition at line 46 of file PriorityStack.cs.
         {
             if (values is null)
             {
                 throw new ArgumentNullException(nameof(values));
             }
             Comparer = comparer ?? throw new ArgumentNullException(nameof(comparer));
             foreach (var value in values)
             {
                 Push(value);
             }
         }
References Juniper.Collections.PriorityStack< T >.Comparer, and Juniper.Collections.PriorityStack< T >.Push().
Member Function Documentation
Clear()
void Juniper.Collections.PriorityStack< T >.Clear () inline
removes all the objects from the priority stack
Definition at line 74 of file PriorityStack.cs.
         {
             stack.Clear();
         }
References Juniper.Collections.PriorityStack< T >.stack.
Contains()
bool Juniper.Collections.PriorityStack< T >.Contains (T item) inline
Performs a linear search for the provided item.
Returns
Definition at line 83 of file PriorityStack.cs.
         {
             return stack.Contains(item);
         }
References Juniper.Collections.PriorityStack< T >.stack.
GetEnumerator() [1/2]
IEnumerator<T> Juniper.Collections.PriorityStack< T >.GetEnumerator () inline
Retrieves a generic enumerator over the objects of the stack
Returns
Definition at line 132 of file PriorityStack.cs.
         {
             return stack.GetEnumerator();
         }
References Juniper.Collections.PriorityStack< T >.stack.
Referenced by Juniper.Collections.PriorityStack< T >.GetEnumerator().
GetEnumerator() [2/2]
IEnumerator IEnumerable. Juniper.Collections.PriorityStack< T >.GetEnumerator () inline private
Retrieves an enumerator over the objects of the stack
Returns
Definition at line 141 of file PriorityStack.cs.
         {
             return GetEnumerator();
         }
References Juniper.Collections.PriorityStack< T >.GetEnumerator().
Peek()
T Juniper.Collections.PriorityStack< T >.Peek () inline
Returns an item from the front of the stack without removing it
Returns
Definition at line 92 of file PriorityStack.cs.
         {
             return stack[stack.Count - 1];
         }
References Juniper.Collections.PriorityStack< T >.stack.
Pop()
T Juniper.Collections.PriorityStack< T >.Pop () inline
Removes an item from the front of the stack
Definition at line 100 of file PriorityStack.cs.
         {
             var obj = stack[stack.Count - 1];
             stack.RemoveAt(stack.Count - 1);
             return obj;
         }
References Juniper.Collections.PriorityStack< T >.stack.
Push()
void Juniper.Collections.PriorityStack< T >.Push (T item) inline
Adds an item to the stack, using the natural order of the object type if no Comparer is provided during construction of the PriorityStack.
Parameters
item The object to add
Definition at line 112 of file PriorityStack.cs.
         {
             //figure out which stack to add the object to
             int addIndex;
             for (addIndex = 0; addIndex < stack.Count; ++addIndex)
             {
                 var t = stack[addIndex];
                 if (Comparer.Compare(t, item) == 1)
                 {
                     break;
                 }
             }
             stack.Insert(addIndex, item);
         }
References Juniper.Collections.PriorityStack< T >.Comparer, and Juniper.Collections.PriorityStack< T >.stack.
Referenced by Juniper.Collections.PriorityStack< T >.PriorityStack().
ToArray()
T [] Juniper.Collections.PriorityStack< T >.ToArray () inline
Create an array out of the stack
Returns
Definition at line 150 of file PriorityStack.cs.
         {
             return stack.ToArray();
         }
References Juniper.Collections.PriorityStack< T >.stack.
Member Data Documentation
Count
int Juniper.Collections.PriorityStack< T >.Count => stack.Count
get the number of elements in the collection
Definition at line 69 of file PriorityStack.cs.
stack
readonly List<T> Juniper.Collections.PriorityStack< T >.stack = new List<T>() private
Definition at line 25 of file PriorityStack.cs.
Referenced by Juniper.Collections.PriorityStack< T >.Clear(), Juniper.Collections.PriorityStack< T >.Contains(), Juniper.Collections.PriorityStack< T >.GetEnumerator(), Juniper.Collections.PriorityStack< T >.Peek(), Juniper.Collections.PriorityStack< T >.Pop(), Juniper.Collections.PriorityStack< T >.Push(), and Juniper.Collections.PriorityStack< T >.ToArray().
Property Documentation
Comparer
IComparer<T> Juniper.Collections.PriorityStack< T >.Comparer get
Retrieve the comparer to use with the objects being added to the stack
Definition at line 64 of file PriorityStack.cs.
 { get; }
Referenced by Juniper.Collections.PriorityStack< T >.PriorityStack(), and Juniper.Collections.PriorityStack< T >.Push().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Root/Collections/PriorityStack.cs