import { Plugin } from "esbuild";
declare type Define = [string, string];
declare type DefineFactory = (minify: boolean) => Define;
declare type PluginFactory = (minify: boolean) => Plugin;
export declare class Build {
    private readonly buildWorkers;
    private readonly browserEntries;
    private readonly minBrowserEntries;
    private readonly plugins;
    private readonly defines;
    private readonly externals;
    private readonly globalExternals;
    private readonly isWatch;
    get buildType(): "watch" | "build";
    private entryNames;
    private outbase;
    private rootDirName;
    private outDirName;
    constructor(args: string[], buildWorkers: boolean);
    entryName(name: string): this;
    rootDir(name: string): this;
    outDir(name: string): this;
    outBase(name: string): this;
    plugin(pgn: PluginFactory): this;
    define(def: DefineFactory): this;
    external(extern: string): this;
    globalExternal(packageName: string, globalName: string): this;
    bundle(name: string): this;
    bundles(names: string[]): this;
    run(): Promise<void>;
    private makeBundle;
}
export {};
