Juniper: Juniper.World.GIS.Google.MapTiles.Marker Class Reference
Juniper.World.GIS.Google.MapTiles.Marker Class Reference
Public Member Functions
Marker (string center, MarkerStyle style=default)
Marker??? (LatLngPoint center, MarkerStyle style=default)
void GetObjectData (SerializationInfo info, StreamingContext context)
override bool Equals (object obj)
bool Equals (Marker other)
override int GetHashCode ()
Static Public Member Functions
static bool operator== (Marker left, Marker right)
static bool operator != (Marker left, Marker right)
Properties
MarkerStyle Style [get]
string Center [get]
Private Member Functions
Marker (SerializationInfo info, StreamingContext context)
Static Private Attributes
static readonly string STYLE_FIELD = nameof(Style).ToLowerInvariant()
static readonly string CENTER_FIELD = nameof(Center).ToLowerInvariant()
Detailed Description
Definition at line 9 of file Marker.cs.
Constructor & Destructor Documentation
Marker() [1/2]
Juniper.World.GIS.Google.MapTiles.Marker.Marker (string center, MarkerStyle style = default) inline
Definition at line 17 of file Marker.cs.
         {
             Center = center;
             Style = style;
         }
References Juniper.World.GIS.Google.MapTiles.center, Juniper.World.GIS.Google.MapTiles.Marker.Center, and Juniper.World.GIS.Google.MapTiles.Marker.Style.
Marker() [2/2]
Juniper.World.GIS.Google.MapTiles.Marker.Marker (SerializationInfo info, StreamingContext context) inline private
Definition at line 27 of file Marker.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             Style = info.GetValue<MarkerStyle>(STYLE_FIELD);
             Center = info.GetString(CENTER_FIELD);
         }
References Juniper.World.GIS.Google.MapTiles.Marker.Center, Juniper.World.GIS.Google.MapTiles.Marker.CENTER_FIELD, Juniper.World.GIS.Google.MapTiles.Marker.Style, and Juniper.World.GIS.Google.MapTiles.Marker.STYLE_FIELD.
Member Function Documentation
Equals() [1/2]
override bool Juniper.World.GIS.Google.MapTiles.Marker.Equals (object obj) inline
Definition at line 49 of file Marker.cs.
         {
             return obj is Marker marker && Equals(marker);
         }
Equals() [2/2]
bool Juniper.World.GIS.Google.MapTiles.Marker.Equals (Marker other) inline
Definition at line 54 of file Marker.cs.
         {
             return other is object
                 && Style == other.Style
                 && Center == other.Center;
         }
References Juniper.World.GIS.Google.MapTiles.Marker.Center, and Juniper.World.GIS.Google.MapTiles.Marker.Style.
GetHashCode()
override int Juniper.World.GIS.Google.MapTiles.Marker.GetHashCode () inline
Definition at line 61 of file Marker.cs.
         {
             var hashCode = -1099193654;
             hashCode = (hashCode * -1521134295) + EqualityComparer<MarkerStyle>.Default.GetHashCode(Style);
             hashCode = (hashCode * -1521134295) + EqualityComparer<string>.Default.GetHashCode(Center);
             return hashCode;
         }
References Juniper.World.GIS.Google.MapTiles.Marker.Center, and Juniper.World.GIS.Google.MapTiles.Marker.Style.
GetObjectData()
void Juniper.World.GIS.Google.MapTiles.Marker.GetObjectData (SerializationInfo info, StreamingContext context) inline
Definition at line 38 of file Marker.cs.
         {
             if (info is null)
             {
                 throw new ArgumentNullException(nameof(info));
             }
             info.AddValue(STYLE_FIELD, Style);
             info.AddValue(CENTER_FIELD, Center);
         }
References Juniper.World.GIS.Google.MapTiles.Marker.Center, Juniper.World.GIS.Google.MapTiles.Marker.CENTER_FIELD, Juniper.World.GIS.Google.MapTiles.Marker.Style, and Juniper.World.GIS.Google.MapTiles.Marker.STYLE_FIELD.
Marker???()
Juniper.World.GIS.Google.MapTiles.Marker.Marker??? (LatLngPoint center, MarkerStyle style = default) inline
Definition at line 23 of file Marker.cs.
             : this(center?.ToString(CultureInfo.InvariantCulture) ?? throw new ArgumentNullException(nameof(center)), style) { }
operator !=()
static bool Juniper.World.GIS.Google.MapTiles.Marker.operator != (Marker left, Marker right) inline static
Definition at line 75 of file Marker.cs.
         {
             return !(left == right);
         }
References Juniper.World.GIS.Google.MapTiles.left, and Juniper.World.GIS.Google.MapTiles.right.
operator==()
static bool Juniper.World.GIS.Google.MapTiles.Marker.operator== (Marker left, Marker right) inline static
Definition at line 69 of file Marker.cs.
         {
             return ReferenceEquals(left, right)
                 || (left is object && left.Equals(right));
         }
References Juniper.World.GIS.Google.MapTiles.left, and Juniper.World.GIS.Google.MapTiles.right.
Member Data Documentation
CENTER_FIELD
readonly string Juniper.World.GIS.Google.MapTiles.Marker.CENTER_FIELD = nameof(Center).ToLowerInvariant() static private
Definition at line 12 of file Marker.cs.
Referenced by Juniper.World.GIS.Google.MapTiles.Marker.GetObjectData(), and Juniper.World.GIS.Google.MapTiles.Marker.Marker().
STYLE_FIELD
readonly string Juniper.World.GIS.Google.MapTiles.Marker.STYLE_FIELD = nameof(Style).ToLowerInvariant() static private
Definition at line 11 of file Marker.cs.
Referenced by Juniper.World.GIS.Google.MapTiles.Marker.GetObjectData(), and Juniper.World.GIS.Google.MapTiles.Marker.Marker().
Property Documentation
Center
string Juniper.World.GIS.Google.MapTiles.Marker.Center get
Definition at line 15 of file Marker.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.MapTiles.Marker.Equals(), Juniper.World.GIS.Google.MapTiles.Marker.GetHashCode(), Juniper.World.GIS.Google.MapTiles.Marker.GetObjectData(), and Juniper.World.GIS.Google.MapTiles.Marker.Marker().
Style
MarkerStyle Juniper.World.GIS.Google.MapTiles.Marker.Style get
Definition at line 14 of file Marker.cs.
 { get; }
Referenced by Juniper.World.GIS.Google.MapTiles.Marker.Equals(), Juniper.World.GIS.Google.MapTiles.Marker.GetHashCode(), Juniper.World.GIS.Google.MapTiles.Marker.GetObjectData(), and Juniper.World.GIS.Google.MapTiles.Marker.Marker().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.GoogleMaps/MapTiles/Marker.cs