Juniper: Hjg.Pngcs.PngReader Class Reference
Hjg.Pngcs.PngReader Class Reference
Reads a PNG image, line by line
Public Member Functions
PngReader (Stream inputStream)
Constructs a PngReader from a Stream, with no filename information
PngReader (Stream inputStream, string filename)
Constructs a PNGReader objet from a opened Stream
ChunksList GetChunksList ()
Returns the ancillary chunks available
PngMetadata GetMetadata ()
Returns the ancillary chunks available
ImageLine ReadRow (int nrow)
reads the row using ImageLine as buffer
ImageLine ReadRowInt (int nrow)
ImageLine ReadRowByte (int nrow)
int [] ReadRow (int[] buffer, int nrow)
int [] ReadRowInt (int[] buffer, int nrow)
byte [] ReadRowByte (byte[] buffer, int nrow)
ImageLine GetRow (int nrow)
ImageLines ReadRowsInt (int rowOffset, int nRows, int rowStep)
ImageLines ReadRowsInt ()
ImageLines ReadRowsByte (int rowOffset, int nRows, int rowStep)
ImageLines ReadRowsByte ()
void ReadSkippingAllRows ()
override string ToString ()
void End ()
Normally this does nothing, but it can be used to force a premature closing
bool IsInterlaced ()
void SetUnpackedMode (bool unPackedMode)
void Dispose ()
Properties
ImageInfo ImgInfo [get]
Basic image info, inmutable
ChunkLoadBehaviour ChunkLoadBehaviour [get, set]
Strategy for chunk loading. Default: LOAD_CHUNK_ALWAYS
bool ShouldCloseStream [get, set]
Should close the underlying Input Stream when ends?
long MaxBytesMetadata [get, set]
Maximum amount of bytes from ancillary chunks to load in memory
long MaxTotalBytesRead [get, set]
Maximum total bytes to read from stream
int SkipChunkMaxSize [get, set]
Maximum ancillary chunk size
string [] SkipChunkIds [get, set]
Ancillary chunks to skip
bool Interlaced [get]
int CurrentChunkGroup [get, private set]
number of chunk group (0-6) last read, or currently reading
Private Member Functions
bool FirstChunksNotYetRead ()
void ReadLastAndClose ()
Internally called after having read the last line. It reads extra chunks after IDAT, if present.
void Close ()
void UnfilterRow (int nbytes)
void UnfilterRowAverage (int nbytes)
void UnfilterRowNone (int nbytes)
void UnfilterRowPaeth (int nbytes)
void UnfilterRowSub (int nbytes)
void UnfilterRowUp (int nbytes)
void ReadFirstChunks ()
Reads chunks before first IDAT. Position before: after IDHR (crc included) Position after: just after the first IDAT chunk id Returns length of first IDAT chunk , -1 if not found
void ReadLastChunks ()
Reads (and processes ... up to a point) chunks after last IDAT.
AbstractPngChunk ReadChunk (byte[] chunkid, int clen, bool skipforced)
Reads chunkd from input stream, adds to ChunksList, and returns it. If it's skipped, a PngChunkSkipped object is created
internal void LogWarn (string warn)
Logs/prints a warning.
void DecodeLastReadRowToInt (int[] buffer, int bytesRead)
void DecodeLastReadRowToByte (byte[] buffer, int bytesRead)
int ReadRowRaw (int nrow)
void Dispose (bool disposing)
Private Attributes
readonly string filename
filename, or description - merely informative, can be empty
Dictionary< string, int > skipChunkIdsSet = null
readonly PngMetadata metadata
A high level wrapper of a ChunksList : list of read chunks
readonly ChunksList chunksList
Read chunks
ImageLine imgLine
buffer: last read line
byte [] rowb
raw current row, as array of bytes,counting from 1 (index 0 is reserved for filter type)
byte [] rowbprev
previuos raw row
readonly byte [] rowbfilter
raw current row, after unfiltered
readonly PngDeinterlacer deinterlacer
bool unpackedMode = false
int rowNum = -1
last read row number
long offset = 0
int bytesChunksLoaded = 0
readonly Stream inputStream
internal AZlibInputStream idatIstream
internal PngIDatChunkInputStream iIdatCstream
bool disposedValue = false
Detailed Description
Reads a PNG image, line by line
The typical reading sequence is as follows:
1. At construction time, the header and IHDR chunk are read (basic image info)
2 (Optional) you can set some global options: UnpackedMode CrcCheckDisabled
3. (Optional) If you call GetMetadata() or or GetChunksLisk() before reading the pixels, the chunks before IDAT are automatically loaded and available
4a. The rows are read, one by one, with the ReadRowXXX methods: (ReadRowInt() , ReadRowByte(), etc) in order, from 0 to nrows-1 (you can skip or repeat rows, but not go backwards)
4b. Alternatively, you can read all rows, or a subset, in a single call: see ReadRowsInt(), ReadRowsByte() In general this consumes more memory, but for interlaced images this is equally efficient, and more so if reading a small subset of rows.
5. Read of the last row automatically loads the trailing chunks, and ends the reader.
6. End() forcibly finishes/aborts the reading and closes the stream
Definition at line 29 of file PngReader.cs.
Constructor & Destructor Documentation
PngReader() [1/2]
Hjg.Pngcs.PngReader.PngReader (Stream inputStream) inline
Constructs a PngReader from a Stream, with no filename information
Parameters
inputStream
Definition at line 146 of file PngReader.cs.
             : this(inputStream, "[NO FILENAME AVAILABLE]")
         {
         }
PngReader() [2/2]
Hjg.Pngcs.PngReader.PngReader (Stream inputStream, string filename) inline
Constructs a PNGReader objet from a opened Stream
The constructor reads the signature and first chunk (IDHR)
Parameters
inputStream
filename Optional, can be the filename or a description.
Definition at line 159 of file PngReader.cs.
         {
             this.inputStream = inputStream ?? throw new ArgumentNullException(nameof(inputStream));
             this.filename = filename ?? "";
             chunksList = new ChunksList(null);
             metadata = new PngMetadata(chunksList);
             offset = 0;
             // set default options
             CurrentChunkGroup = -1;
             ShouldCloseStream = true;
             MaxBytesMetadata = 5 * 1024 * 1024;
             MaxTotalBytesRead = 200 * 1024 * 1024; // 200MB
             SkipChunkMaxSize = 2 * 1024 * 1024;
             SkipChunkIds = new string[] { "fdAT" };
             ChunkLoadBehaviour = ChunkLoadBehaviour.LOAD_CHUNK_ALWAYS;
             // starts reading: signature
             var pngid = new byte[8];
             PngHelperInternal.ReadBytes(inputStream, pngid, 0, pngid.Length);
             offset += pngid.Length;
             if (!PngCsUtils.arraysEqual(pngid, PngHelperInternal.PNG_ID_SIGNATURE))
             {
                 throw new PngjInputException("Bad PNG signature");
             }
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_0_IDHR;
             // reads first chunk IDHR
             var clen = PngHelperInternal.ReadInt4(inputStream);
             offset += 4;
             if (clen != 13)
             {
                 throw new Exception("IDHR chunk len != 13 ?? " + clen);
             }
             var chunkid = new byte[4];
             PngHelperInternal.ReadBytes(inputStream, chunkid, 0, 4);
             if (!PngCsUtils.arraysEqual4(chunkid, ChunkHelper.b_IHDR))
             {
                 throw new PngjInputException("IHDR not found as first chunk??? ["
                         + ChunkHelper.ToString(chunkid) + "]");
             }
             offset += 4;
             var ihdr = (PngChunkIHDR)ReadChunk(chunkid, clen, false);
             var alpha = (ihdr.Colormodel & 0x04) != 0;
             var palette = (ihdr.Colormodel & 0x01) != 0;
             var grayscale = (ihdr.Colormodel == 0 || ihdr.Colormodel == 4);
             // creates ImgInfo and imgLine, and allocates buffers
             ImgInfo = new ImageInfo(ihdr.Cols, ihdr.Rows, ihdr.Bitspc, alpha, grayscale, palette);
             rowb = new byte[ImgInfo.BytesPerRow + 1];
             rowbprev = new byte[rowb.Length];
             rowbfilter = new byte[rowb.Length];
             Interlaced = ihdr.Interlaced == 1;
             deinterlacer = Interlaced ? new PngDeinterlacer(ImgInfo) : null;
             // some checks
             if (ihdr.Filmeth != 0 || ihdr.Compmeth != 0 || (ihdr.Interlaced & 0xFFFE) != 0)
             {
                 throw new PngjInputException("compmethod or filtermethod or interlaced unrecognized");
             }
             if (ihdr.Colormodel < 0 || ihdr.Colormodel > 6 || ihdr.Colormodel == 1
                     || ihdr.Colormodel == 5)
             {
                 throw new PngjInputException("Invalid colormodel " + ihdr.Colormodel);
             }
             if (ihdr.Bitspc != 1 && ihdr.Bitspc != 2 && ihdr.Bitspc != 4 && ihdr.Bitspc != 8
                     && ihdr.Bitspc != 16)
             {
                 throw new PngjInputException("Invalid bit depth " + ihdr.Bitspc);
             }
         }
References Hjg.Pngcs.PngCsUtils.arraysEqual(), Hjg.Pngcs.PngCsUtils.arraysEqual4(), Hjg.Pngcs.Chunks.ChunkHelper.b_IHDR, Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_0_IDHR, Hjg.Pngcs.PngReader.chunksList, Hjg.Pngcs.PngReader.CurrentChunkGroup, Hjg.Pngcs.PngReader.deinterlacer, Hjg.Pngcs.PngReader.filename, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.inputStream, Hjg.Pngcs.PngReader.Interlaced, Hjg.Pngcs.PngReader.MaxBytesMetadata, Hjg.Pngcs.PngReader.MaxTotalBytesRead, Hjg.Pngcs.PngReader.metadata, Hjg.Pngcs.PngReader.offset, Hjg.Pngcs.PngHelperInternal.PNG_ID_SIGNATURE, Hjg.Pngcs.PngHelperInternal.ReadBytes(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngHelperInternal.ReadInt4(), Hjg.Pngcs.PngReader.rowb, Hjg.Pngcs.PngReader.rowbfilter, Hjg.Pngcs.PngReader.rowbprev, Hjg.Pngcs.PngReader.ShouldCloseStream, Hjg.Pngcs.PngReader.SkipChunkIds, Hjg.Pngcs.PngReader.SkipChunkMaxSize, and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
Member Function Documentation
Close()
void Hjg.Pngcs.PngReader.Close () inline private
Definition at line 257 of file PngReader.cs.
         {
             if (CurrentChunkGroup < ChunksList.CHUNK_GROUP_6_END)
             {
                 // this could only happen if forced close
                 try
                 {
                     idatIstream.Close();
                 }
 #pragma warning disable RCS1075 // Avoid empty catch clause that catches System.Exception.
                 catch (Exception)
 #pragma warning restore RCS1075 // Avoid empty catch clause that catches System.Exception.
                 {
                 }
                 CurrentChunkGroup = ChunksList.CHUNK_GROUP_6_END;
             }
             if (ShouldCloseStream)
             {
                 inputStream.Close();
             }
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_6_END, Hjg.Pngcs.PngReader.CurrentChunkGroup, Hjg.Pngcs.PngReader.idatIstream, Hjg.Pngcs.PngReader.inputStream, and Hjg.Pngcs.PngReader.ShouldCloseStream.
Referenced by Hjg.Pngcs.PngReader.End(), and Hjg.Pngcs.PngReader.ReadLastAndClose().
DecodeLastReadRowToByte()
void Hjg.Pngcs.PngReader.DecodeLastReadRowToByte (byte [] buffer, int bytesRead) inline private
Definition at line 743 of file PngReader.cs.
         {            // see http://www.libpng.org/pub/png/spec/1.2/PNG-DataRep.html
             if (ImgInfo.BitDepth <= 8)
             {
                 Array.Copy(rowb, 1, buffer, 0, bytesRead);
             }
             else
             { // 16 bitspc
                 for (int i = 0, j = 1; j < bytesRead; i++, j += 2)
                 {
                     buffer[i] = rowb[j]; // 16 bits in 1 byte: this discards the LSB!!!
                 }
             }
             if (ImgInfo.Packed && unpackedMode)
             {
                 ImageLine.UnpackInplaceByte(ImgInfo, buffer, buffer, false);
             }
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.PngReader.rowb, Hjg.Pngcs.PngReader.unpackedMode, and Hjg.Pngcs.ImageLine.UnpackInplaceByte().
Referenced by Hjg.Pngcs.PngReader.ReadRowByte(), and Hjg.Pngcs.PngReader.ReadRowsByte().
DecodeLastReadRowToInt()
void Hjg.Pngcs.PngReader.DecodeLastReadRowToInt (int [] buffer, int bytesRead) inline private
Definition at line 720 of file PngReader.cs.
         {            // see http://www.libpng.org/pub/png/spec/1.2/PNG-DataRep.html
             if (ImgInfo.BitDepth <= 8)
             {
                 for (int i = 0, j = 1; i < bytesRead; i++)
                 {
                     buffer[i] = (rowb[j++]);
                 }
             }
             else
             { // 16 bitspc
                 for (int i = 0, j = 1; j < bytesRead; i++)
                 {
                     buffer[i] = (rowb[j++] << 8) + rowb[j++];
                 }
             }
             if (ImgInfo.Packed && unpackedMode)
             {
                 ImageLine.UnpackInplaceInt(ImgInfo, buffer, buffer, false);
             }
         }
References Hjg.Pngcs.ImageInfo.BitDepth, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.ImageInfo.Packed, Hjg.Pngcs.PngReader.rowb, Hjg.Pngcs.PngReader.unpackedMode, and Hjg.Pngcs.ImageLine.UnpackInplaceInt().
Referenced by Hjg.Pngcs.PngReader.ReadRowInt(), and Hjg.Pngcs.PngReader.ReadRowsInt().
Dispose() [1/2]
void Hjg.Pngcs.PngReader.Dispose (bool disposing) inline private
Definition at line 1008 of file PngReader.cs.
         {
             if (!disposedValue)
             {
                 if (disposing)
                 {
                     idatIstream?.Dispose();
                     iIdatCstream?.Dispose();
                     inputStream.Dispose();
                 }
                 // TODO: free unmanaged resources (unmanaged objects) and override a finalizer below.
                 // TODO: set large fields to null.
                 disposedValue = true;
             }
         }
References Hjg.Pngcs.Zlib.AZlibInputStream.Dispose(), Hjg.Pngcs.PngIDatChunkInputStream.Dispose(), Hjg.Pngcs.PngReader.disposedValue, Hjg.Pngcs.PngReader.idatIstream, Hjg.Pngcs.PngReader.iIdatCstream, and Hjg.Pngcs.PngReader.inputStream.
Dispose() [2/2]
void Hjg.Pngcs.PngReader.Dispose () inline
Definition at line 1027 of file PngReader.cs.
         {
             // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
             Dispose(true);
         }
End()
void Hjg.Pngcs.PngReader.End () inline
Normally this does nothing, but it can be used to force a premature closing
Definition at line 987 of file PngReader.cs.
         {
             if (CurrentChunkGroup < ChunksList.CHUNK_GROUP_6_END)
             {
                 Close();
             }
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_6_END, Hjg.Pngcs.PngReader.Close(), and Hjg.Pngcs.PngReader.CurrentChunkGroup.
Referenced by Hjg.Pngcs.PngReader.ReadRowsByte(), and Hjg.Pngcs.PngReader.ReadRowsInt().
FirstChunksNotYetRead()
bool Hjg.Pngcs.PngReader.FirstChunksNotYetRead () inline private
Definition at line 231 of file PngReader.cs.
         {
             return CurrentChunkGroup < ChunksList.CHUNK_GROUP_1_AFTERIDHR;
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_1_AFTERIDHR, and Hjg.Pngcs.PngReader.CurrentChunkGroup.
Referenced by Hjg.Pngcs.PngReader.GetChunksList(), Hjg.Pngcs.PngReader.GetMetadata(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadRowRaw(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
GetChunksList()
ChunksList Hjg.Pngcs.PngReader.GetChunksList () inline
Returns the ancillary chunks available
If the rows have not yet still been read, this includes only the chunks placed before the pixels (IDAT)
Returns
ChunksList
Definition at line 564 of file PngReader.cs.
         {
             if (FirstChunksNotYetRead())
             {
                 ReadFirstChunks();
             }
             return chunksList;
         }
References Hjg.Pngcs.PngReader.chunksList, Hjg.Pngcs.PngReader.FirstChunksNotYetRead(), and Hjg.Pngcs.PngReader.ReadFirstChunks().
GetMetadata()
PngMetadata Hjg.Pngcs.PngReader.GetMetadata () inline
Returns the ancillary chunks available
see GetChunksList
Returns
PngMetadata
Definition at line 581 of file PngReader.cs.
         {
             if (FirstChunksNotYetRead())
             {
                 ReadFirstChunks();
             }
             return metadata;
         }
References Hjg.Pngcs.PngReader.FirstChunksNotYetRead(), Hjg.Pngcs.PngReader.metadata, and Hjg.Pngcs.PngReader.ReadFirstChunks().
GetRow()
ImageLine Hjg.Pngcs.PngReader.GetRow (int nrow) inline
Definition at line 715 of file PngReader.cs.
         {
             return ReadRow(nrow);
         }
References Hjg.Pngcs.PngReader.ReadRow().
IsInterlaced()
bool Hjg.Pngcs.PngReader.IsInterlaced () inline
Definition at line 995 of file PngReader.cs.
         {
             return Interlaced;
         }
References Hjg.Pngcs.PngReader.Interlaced.
LogWarn()
internal void Hjg.Pngcs.PngReader.LogWarn (string warn) inline private
Logs/prints a warning.
The default behaviour is print to stderr, but it can be overriden. This happens rarely - most errors are fatal.
Parameters
warn
Definition at line 551 of file PngReader.cs.
         {
             Console.Error.WriteLine(warn);
         }
ReadChunk()
AbstractPngChunk Hjg.Pngcs.PngReader.ReadChunk (byte [] chunkid, int clen, bool skipforced) inline private
Reads chunkd from input stream, adds to ChunksList, and returns it. If it's skipped, a PngChunkSkipped object is created
Returns
Definition at line 484 of file PngReader.cs.
         {
             if (clen < 0)
             {
                 throw new PngjInputException("invalid chunk lenght: " + clen);
             }
             // skipChunksByIdSet is created lazyly, if fist IHDR has already been read
             if (skipChunkIdsSet is null && CurrentChunkGroup > ChunksList.CHUNK_GROUP_0_IDHR)
             {
                 skipChunkIdsSet = new Dictionary<string, int>();
                 if (SkipChunkIds is object)
                 {
                     foreach (var id in SkipChunkIds)
                     {
                         skipChunkIdsSet.Add(id, 1);
                     }
                 }
             }
             var chunkidstr = ChunkHelper.ToString(chunkid);
             var critical = ChunkHelper.IsCritical(chunkidstr);
             var skip = skipforced;
             if (MaxTotalBytesRead > 0 && clen + offset > MaxTotalBytesRead)
             {
                 throw new PngjInputException("Maximum total bytes to read exceeeded: " + MaxTotalBytesRead + " offset:"
                         + offset + " clen=" + clen);
             }
             // an ancillary chunks can be skipped because of several reasons:
             if (CurrentChunkGroup > ChunksList.CHUNK_GROUP_0_IDHR && !ChunkHelper.IsCritical(chunkidstr))
             {
                 skip = skip || (SkipChunkMaxSize > 0 && clen >= SkipChunkMaxSize) || skipChunkIdsSet.ContainsKey(chunkidstr)
                         || (MaxBytesMetadata > 0 && clen > MaxBytesMetadata - bytesChunksLoaded)
                         || !ChunkHelper.ShouldLoad(chunkidstr, ChunkLoadBehaviour);
             }
             AbstractPngChunk pngChunk;
             if (skip)
             {
                 PngHelperInternal.SkipBytes(inputStream, clen);
                 PngHelperInternal.ReadInt4(inputStream); // skip - we dont call PngHelperInternal.skipBytes(inputStream, clen + 4) for risk of overflow
                 pngChunk = new PngChunkSkipped(chunkidstr, ImgInfo, clen);
             }
             else
             {
                 var chunk = new ChunkRaw(clen, chunkid, true);
                 _ = chunk.ReadChunkData(inputStream, critical);
                 pngChunk = AbstractPngChunk.Factory(chunk, ImgInfo);
                 if (!pngChunk.Crit)
                 {
                     bytesChunksLoaded += chunk.Len;
                 }
             }
             pngChunk.Offset = offset - 8L;
             chunksList.AppendReadChunk(pngChunk, CurrentChunkGroup);
             offset += clen + 4L;
             return pngChunk;
         }
References Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), Hjg.Pngcs.PngReader.bytesChunksLoaded, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_0_IDHR, Hjg.Pngcs.PngReader.chunksList, Hjg.Pngcs.Chunks.AbstractPngChunk.Crit, Hjg.Pngcs.PngReader.CurrentChunkGroup, Hjg.Pngcs.Chunks.AbstractPngChunk.Factory(), Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.inputStream, Hjg.Pngcs.Chunks.ChunkHelper.IsCritical(), Hjg.Pngcs.PngReader.MaxBytesMetadata, Hjg.Pngcs.PngReader.MaxTotalBytesRead, Hjg.Pngcs.Chunks.AbstractPngChunk.Offset, Hjg.Pngcs.PngReader.offset, Hjg.Pngcs.PngHelperInternal.ReadInt4(), Hjg.Pngcs.Chunks.ChunkHelper.ShouldLoad(), Hjg.Pngcs.PngHelperInternal.SkipBytes(), Hjg.Pngcs.PngReader.SkipChunkIds, Hjg.Pngcs.PngReader.skipChunkIdsSet, Hjg.Pngcs.PngReader.SkipChunkMaxSize, and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
Referenced by Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadFirstChunks(), and Hjg.Pngcs.PngReader.ReadLastChunks().
ReadFirstChunks()
void Hjg.Pngcs.PngReader.ReadFirstChunks () inline private
Reads chunks before first IDAT. Position before: after IDHR (crc included) Position after: just after the first IDAT chunk id Returns length of first IDAT chunk , -1 if not found
Definition at line 369 of file PngReader.cs.
         {
             if (!FirstChunksNotYetRead())
             {
                 return;
             }
             var clen = 0;
             var found = false;
             var chunkid = new byte[4]; // it's important to reallocate in each
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_1_AFTERIDHR;
             while (!found)
             {
                 clen = PngHelperInternal.ReadInt4(inputStream);
                 offset += 4;
                 if (clen < 0)
                 {
                     break;
                 }
                 PngHelperInternal.ReadBytes(inputStream, chunkid, 0, 4);
                 offset += 4;
                 if (PngCsUtils.arraysEqual4(chunkid, Hjg.Pngcs.Chunks.ChunkHelper.b_IDAT))
                 {
                     found = true;
                     CurrentChunkGroup = ChunksList.CHUNK_GROUP_4_IDAT;
                     // add dummy idat chunk to list
                     chunksList.AppendReadChunk(new PngChunkIDAT(ImgInfo, clen, offset - 8), CurrentChunkGroup);
                     break;
                 }
                 else if (PngCsUtils.arraysEqual4(chunkid, Hjg.Pngcs.Chunks.ChunkHelper.b_IEND))
                 {
                     throw new PngjInputException("END chunk found before image data (IDAT) at offset=" + offset);
                 }
                 var chunkids = ChunkHelper.ToString(chunkid);
                 if (chunkids.Equals(ChunkHelper.PLTE, System.StringComparison.Ordinal))
                 {
                     CurrentChunkGroup = ChunksList.CHUNK_GROUP_2_PLTE;
                 }
                 ReadChunk(chunkid, clen, false);
                 if (chunkids.Equals(ChunkHelper.PLTE, System.StringComparison.Ordinal))
                 {
                     CurrentChunkGroup = ChunksList.CHUNK_GROUP_3_AFTERPLTE;
                 }
             }
             var idatLen = found ? clen : -1;
             if (idatLen < 0)
             {
                 throw new PngjInputException("first idat chunk not found!");
             }
             iIdatCstream = new PngIDatChunkInputStream(inputStream, idatLen, offset);
             idatIstream = new ZlibInputStream(iIdatCstream, true);
         }
References Hjg.Pngcs.Chunks.ChunksList.AppendReadChunk(), Hjg.Pngcs.PngCsUtils.arraysEqual4(), Hjg.Pngcs.Chunks.ChunkHelper.b_IDAT, Hjg.Pngcs.Chunks.ChunkHelper.b_IEND, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_1_AFTERIDHR, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_2_PLTE, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_3_AFTERPLTE, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_4_IDAT, Hjg.Pngcs.PngReader.chunksList, Hjg.Pngcs.PngReader.CurrentChunkGroup, Hjg.Pngcs.PngReader.FirstChunksNotYetRead(), Hjg.Pngcs.PngReader.idatIstream, Hjg.Pngcs.PngReader.iIdatCstream, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.inputStream, Hjg.Pngcs.PngReader.offset, Hjg.Pngcs.Chunks.ChunkHelper.PLTE, Hjg.Pngcs.PngHelperInternal.ReadBytes(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngHelperInternal.ReadInt4(), and Hjg.Pngcs.Chunks.ChunkHelper.ToString().
Referenced by Hjg.Pngcs.PngReader.GetChunksList(), Hjg.Pngcs.PngReader.GetMetadata(), Hjg.Pngcs.PngReader.ReadRowRaw(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
ReadLastAndClose()
void Hjg.Pngcs.PngReader.ReadLastAndClose () inline private
Internally called after having read the last line. It reads extra chunks after IDAT, if present.
Definition at line 240 of file PngReader.cs.
         {
             if (CurrentChunkGroup < ChunksList.CHUNK_GROUP_5_AFTERIDAT)
             {
                 try
                 {
                     idatIstream.Close();
                 }
 #pragma warning disable RCS1075 // Avoid empty catch clause that catches System.Exception.
                 catch (Exception) { }
 #pragma warning restore RCS1075 // Avoid empty catch clause that catches System.Exception.
                 ReadLastChunks();
             }
             Close();
         }
References Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_5_AFTERIDAT, Hjg.Pngcs.PngReader.Close(), Hjg.Pngcs.PngReader.CurrentChunkGroup, Hjg.Pngcs.PngReader.idatIstream, and Hjg.Pngcs.PngReader.ReadLastChunks().
Referenced by Hjg.Pngcs.PngReader.ReadRowRaw(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
ReadLastChunks()
void Hjg.Pngcs.PngReader.ReadLastChunks () inline private
Reads (and processes ... up to a point) chunks after last IDAT.
Definition at line 430 of file PngReader.cs.
         {
             CurrentChunkGroup = ChunksList.CHUNK_GROUP_5_AFTERIDAT;
             // PngHelper.logdebug("idat ended? " + iIdatCstream.isEnded());
             if (!iIdatCstream.IsEnded())
             {
                 iIdatCstream.ForceChunkEnd();
             }
             var clen = iIdatCstream.GetLenLastChunk();
             var chunkid = iIdatCstream.GetIdLastChunk();
             var endfound = false;
             var first = true;
             while (!endfound)
             {
                 var skip = false;
                 if (!first)
                 {
                     clen = PngHelperInternal.ReadInt4(inputStream);
                     offset += 4;
                     if (clen < 0)
                     {
                         throw new PngjInputException("bad len " + clen);
                     }
                     PngHelperInternal.ReadBytes(inputStream, chunkid, 0, 4);
                     offset += 4;
                 }
                 first = false;
                 if (PngCsUtils.arraysEqual4(chunkid, ChunkHelper.b_IDAT))
                 {
                     skip = true; // extra dummy (empty?) idat chunk, it can happen, ignore it
                 }
                 else if (PngCsUtils.arraysEqual4(chunkid, ChunkHelper.b_IEND))
                 {
                     CurrentChunkGroup = ChunksList.CHUNK_GROUP_6_END;
                     endfound = true;
                 }
                 ReadChunk(chunkid, clen, skip);
             }
             if (!endfound)
             {
                 throw new PngjInputException("end chunk not found - offset=" + offset);
             }
             // PngHelper.logdebug("end chunk found ok offset=" + offset);
         }
References Hjg.Pngcs.PngCsUtils.arraysEqual4(), Hjg.Pngcs.Chunks.ChunkHelper.b_IDAT, Hjg.Pngcs.Chunks.ChunkHelper.b_IEND, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_5_AFTERIDAT, Hjg.Pngcs.Chunks.ChunksList.CHUNK_GROUP_6_END, Hjg.Pngcs.PngReader.CurrentChunkGroup, Hjg.Pngcs.PngIDatChunkInputStream.ForceChunkEnd(), Hjg.Pngcs.PngIDatChunkInputStream.GetIdLastChunk(), Hjg.Pngcs.PngIDatChunkInputStream.GetLenLastChunk(), Hjg.Pngcs.PngReader.iIdatCstream, Hjg.Pngcs.PngReader.inputStream, Hjg.Pngcs.PngIDatChunkInputStream.IsEnded(), Hjg.Pngcs.PngReader.offset, Hjg.Pngcs.PngHelperInternal.ReadBytes(), Hjg.Pngcs.PngReader.ReadChunk(), and Hjg.Pngcs.PngHelperInternal.ReadInt4().
Referenced by Hjg.Pngcs.PngReader.ReadLastAndClose().
ReadRow() [1/2]
ImageLine Hjg.Pngcs.PngReader.ReadRow (int nrow) inline
reads the row using ImageLine as buffer
param name="nrow">row number - just as a check
Returns
the ImageLine that also is available inside this object
Definition at line 596 of file PngReader.cs.
         {
             return imgLine is null || imgLine.SampleType != ImageLine.ESampleType.BYTE ? ReadRowInt(nrow) : ReadRowByte(nrow);
         }
References Hjg.Pngcs.PngReader.imgLine, Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), and Hjg.Pngcs.ImageLine.SampleType.
Referenced by Hjg.Pngcs.PngReader.GetRow().
ReadRow() [2/2]
int [] Hjg.Pngcs.PngReader.ReadRow (int [] buffer, int nrow) inline
Definition at line 637 of file PngReader.cs.
         {
             return ReadRowInt(buffer, nrow);
         }
References Hjg.Pngcs.PngReader.ReadRowInt().
ReadRowByte() [1/2]
ImageLine Hjg.Pngcs.PngReader.ReadRowByte (int nrow) inline
Definition at line 619 of file PngReader.cs.
         {
             if (imgLine is null)
             {
                 imgLine = new ImageLine(ImgInfo, ImageLine.ESampleType.BYTE, unpackedMode);
             }
             if (imgLine.Rown == nrow) // already read
             {
                 return imgLine;
             }
             ReadRowByte(imgLine.ScanlineB, nrow);
             imgLine.FilterUsed = (FilterType)rowbfilter[0];
             imgLine.Rown = nrow;
             return imgLine;
         }
References Hjg.Pngcs.ImageLine.FilterUsed, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.imgLine, Hjg.Pngcs.PngReader.rowbfilter, Hjg.Pngcs.ImageLine.Rown, Hjg.Pngcs.ImageLine.ScanlineB, and Hjg.Pngcs.PngReader.unpackedMode.
Referenced by Hjg.Pngcs.PngReader.ReadRow().
ReadRowByte() [2/2]
byte [] Hjg.Pngcs.PngReader.ReadRowByte (byte [] buffer, int nrow) inline
Definition at line 678 of file PngReader.cs.
         {
             if (buffer is null)
             {
                 buffer = new byte[unpackedMode ? ImgInfo.SamplesPerRow : ImgInfo.SamplesPerRowPacked];
             }
             if (!Interlaced)
             {
                 if (nrow <= rowNum)
                 {
                     throw new PngjInputException("rows must be read in increasing order: " + nrow);
                 }
                 var bytesread = 0;
                 while (rowNum < nrow)
                 {
                     bytesread = ReadRowRaw(rowNum + 1); // read rows, perhaps skipping if necessary
                 }
                 DecodeLastReadRowToByte(buffer, bytesread);
             }
             else
             { // interlaced
                 if (deinterlacer.GetImageByte() is null)
                 {
                     deinterlacer.SetImageByte(ReadRowsByte().ScanlinesB); // read all image and store it in deinterlacer
                 }
                 Array.Copy(deinterlacer.GetImageByte()[nrow], 0, buffer, 0, unpackedMode ? ImgInfo.SamplesPerRow
                         : ImgInfo.SamplesPerRowPacked);
             }
             return buffer;
         }
References Hjg.Pngcs.PngReader.DecodeLastReadRowToByte(), Hjg.Pngcs.PngReader.deinterlacer, Hjg.Pngcs.PngDeinterlacer.GetImageByte(), Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.Interlaced, Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.ReadRowsByte(), Hjg.Pngcs.PngReader.rowNum, Hjg.Pngcs.ImageInfo.SamplesPerRow, Hjg.Pngcs.ImageInfo.SamplesPerRowPacked, Hjg.Pngcs.PngDeinterlacer.SetImageByte(), and Hjg.Pngcs.PngReader.unpackedMode.
ReadRowInt() [1/2]
ImageLine Hjg.Pngcs.PngReader.ReadRowInt (int nrow) inline
Definition at line 601 of file PngReader.cs.
         {
             if (imgLine is null)
             {
                 imgLine = new ImageLine(ImgInfo, ImageLine.ESampleType.INT, unpackedMode);
             }
             if (imgLine.Rown == nrow) // already read
             {
                 return imgLine;
             }
             ReadRowInt(imgLine.Scanline, nrow);
             imgLine.FilterUsed = (FilterType)rowbfilter[0];
             imgLine.Rown = nrow;
             return imgLine;
         }
References Hjg.Pngcs.ImageLine.FilterUsed, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.imgLine, Hjg.Pngcs.PngReader.rowbfilter, Hjg.Pngcs.ImageLine.Rown, Hjg.Pngcs.ImageLine.Scanline, and Hjg.Pngcs.PngReader.unpackedMode.
Referenced by Hjg.Pngcs.PngReader.ReadRow().
ReadRowInt() [2/2]
int [] Hjg.Pngcs.PngReader.ReadRowInt (int [] buffer, int nrow) inline
Definition at line 642 of file PngReader.cs.
         {
             if (buffer is null)
             {
                 buffer = new int[unpackedMode ? ImgInfo.SamplesPerRow : ImgInfo.SamplesPerRowPacked];
             }
             if (!Interlaced)
             {
                 if (nrow <= rowNum)
                 {
                     throw new PngjInputException("rows must be read in increasing order: " + nrow);
                 }
                 var bytesread = 0;
                 while (rowNum < nrow)
                 {
                     bytesread = ReadRowRaw(rowNum + 1); // read rows, perhaps skipping if necessary
                 }
                 DecodeLastReadRowToInt(buffer, bytesread);
             }
             else
             { // interlaced
                 if (deinterlacer.GetImageInt() is null)
                 {
                     deinterlacer.SetImageInt(ReadRowsInt().Scanlines); // read all image and store it in deinterlacer
                 }
                 Array.Copy(deinterlacer.GetImageInt()[nrow], 0, buffer, 0, unpackedMode ? ImgInfo.SamplesPerRow
                         : ImgInfo.SamplesPerRowPacked);
             }
             return buffer;
         }
References Hjg.Pngcs.PngReader.DecodeLastReadRowToInt(), Hjg.Pngcs.PngReader.deinterlacer, Hjg.Pngcs.PngDeinterlacer.GetImageInt(), Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.Interlaced, Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.ReadRowsInt(), Hjg.Pngcs.PngReader.rowNum, Hjg.Pngcs.ImageInfo.SamplesPerRow, Hjg.Pngcs.ImageInfo.SamplesPerRowPacked, Hjg.Pngcs.PngDeinterlacer.SetImageInt(), and Hjg.Pngcs.PngReader.unpackedMode.
ReadRowRaw()
int Hjg.Pngcs.PngReader.ReadRowRaw (int nrow) inline private
Definition at line 875 of file PngReader.cs.
         {
             //
             if (nrow == 0 && FirstChunksNotYetRead())
             {
                 ReadFirstChunks();
             }
             if (nrow == 0 && Interlaced)
             {
                 Array.Clear(rowb, 0, rowb.Length); // new subimage: reset filters: this is enough, see the swap that happens lines
             }
             // below
             var bytesRead = ImgInfo.BytesPerRow; // NOT including the filter byte
             if (Interlaced)
             {
                 if (nrow < 0 || nrow > deinterlacer.GetRows() || (nrow != 0 && nrow != deinterlacer.GetCurrRowSubimg() + 1))
                 {
                     throw new PngjInputException("invalid row in interlaced mode: " + nrow);
                 }
                 deinterlacer.SetRow(nrow);
                 bytesRead = ((ImgInfo.BitspPixel * deinterlacer.GetPixelsToRead()) + 7) / 8;
                 if (bytesRead < 1)
                 {
                     throw new PngjInternalException("wtf??");
                 }
             }
             else
             { // check for non interlaced
                 if (nrow < 0 || nrow >= ImgInfo.Rows || nrow != rowNum + 1)
                 {
                     throw new PngjInputException("invalid row: " + nrow);
                 }
             }
             rowNum = nrow;
             // swap buffers
             var tmp = rowb;
             rowb = rowbprev;
             rowbprev = tmp;
             // loads in rowbfilter "raw" bytes, with filter
             PngHelperInternal.ReadBytes(idatIstream, rowbfilter, 0, bytesRead + 1);
             offset = iIdatCstream.GetOffset();
             if (offset < 0)
             {
                 throw new PngjInternalException("bad offset ??" + offset);
             }
             if (MaxTotalBytesRead > 0 && offset >= MaxTotalBytesRead)
             {
                 throw new PngjInputException("Reading IDAT: Maximum total bytes to read exceeeded: " + MaxTotalBytesRead
                         + " offset:" + offset);
             }
             rowb[0] = 0;
             UnfilterRow(bytesRead);
             rowb[0] = rowbfilter[0];
             if ((rowNum == ImgInfo.Rows - 1 && !Interlaced) || (Interlaced && deinterlacer.IsAtLastRow()))
             {
                 ReadLastAndClose();
             }
             return bytesRead;
         }
References Hjg.Pngcs.ImageInfo.BitspPixel, Hjg.Pngcs.ImageInfo.BytesPerRow, Hjg.Pngcs.PngReader.deinterlacer, Hjg.Pngcs.PngReader.FirstChunksNotYetRead(), Hjg.Pngcs.PngDeinterlacer.GetCurrRowSubimg(), Hjg.Pngcs.PngIDatChunkInputStream.GetOffset(), Hjg.Pngcs.PngDeinterlacer.GetPixelsToRead(), Hjg.Pngcs.PngDeinterlacer.GetRows(), Hjg.Pngcs.PngReader.idatIstream, Hjg.Pngcs.PngReader.iIdatCstream, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.Interlaced, Hjg.Pngcs.PngDeinterlacer.IsAtLastRow(), Hjg.Pngcs.PngReader.MaxTotalBytesRead, Hjg.Pngcs.PngReader.offset, Hjg.Pngcs.PngHelperInternal.ReadBytes(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadLastAndClose(), Hjg.Pngcs.PngReader.rowb, Hjg.Pngcs.PngReader.rowbfilter, Hjg.Pngcs.PngReader.rowbprev, Hjg.Pngcs.PngReader.rowNum, Hjg.Pngcs.ImageInfo.Rows, Hjg.Pngcs.PngDeinterlacer.SetRow(), and Hjg.Pngcs.PngReader.UnfilterRow().
Referenced by Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), Hjg.Pngcs.PngReader.ReadRowsByte(), and Hjg.Pngcs.PngReader.ReadRowsInt().
ReadRowsByte() [1/2]
ImageLines Hjg.Pngcs.PngReader.ReadRowsByte (int rowOffset, int nRows, int rowStep) inline
Definition at line 819 of file PngReader.cs.
         {
             if (nRows < 0)
             {
                 nRows = (ImgInfo.Rows - rowOffset) / rowStep;
             }
             if (rowStep < 1
                 || rowOffset < 0
                 || (nRows * rowStep) + rowOffset > ImgInfo.Rows)
             {
                 throw new PngjInputException("bad args");
             }
             var imlines = new ImageLines(ImgInfo, ImageLine.ESampleType.BYTE, unpackedMode, rowOffset, nRows, rowStep);
             if (!Interlaced)
             {
                 for (var j = 0; j < ImgInfo.Rows; j++)
                 {
                     var bytesread = ReadRowRaw(j); // read and perhaps discards
                     var mrow = imlines.ImageRowToMatrixRowStrict(j);
                     if (mrow >= 0)
                     {
                         DecodeLastReadRowToByte(imlines.ScanlinesB[mrow], bytesread);
                     }
                 }
             }
             else
             { // and now, for something completely different (interlaced)
                 var buf = new byte[unpackedMode ? ImgInfo.SamplesPerRow : ImgInfo.SamplesPerRowPacked];
                 for (var p = 1; p <= 7; p++)
                 {
                     deinterlacer.SetPass(p);
                     for (var i = 0; i < deinterlacer.GetRows(); i++)
                     {
                         var bytesread = ReadRowRaw(i);
                         var j = deinterlacer.GetCurrRowReal();
                         var mrow = imlines.ImageRowToMatrixRowStrict(j);
                         if (mrow >= 0)
{
                             DecodeLastReadRowToByte(buf, bytesread);
                             deinterlacer.DeinterlaceByte(buf, imlines.ScanlinesB[mrow], !unpackedMode);
                         }
                     }
                 }
             }
             End();
             return imlines;
         }
References Hjg.Pngcs.PngReader.DecodeLastReadRowToByte(), Hjg.Pngcs.PngDeinterlacer.DeinterlaceByte(), Hjg.Pngcs.PngReader.deinterlacer, Hjg.Pngcs.PngReader.End(), Hjg.Pngcs.PngDeinterlacer.GetCurrRowReal(), Hjg.Pngcs.PngDeinterlacer.GetRows(), Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.Interlaced, Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.ImageInfo.Rows, Hjg.Pngcs.ImageInfo.SamplesPerRow, Hjg.Pngcs.ImageInfo.SamplesPerRowPacked, Hjg.Pngcs.PngDeinterlacer.SetPass(), and Hjg.Pngcs.PngReader.unpackedMode.
ReadRowsByte() [2/2]
ImageLines Hjg.Pngcs.PngReader.ReadRowsByte () inline
Definition at line 870 of file PngReader.cs.
         {
             return ReadRowsByte(0, ImgInfo.Rows, 1);
         }
References Hjg.Pngcs.PngReader.ImgInfo, and Hjg.Pngcs.ImageInfo.Rows.
Referenced by Hjg.Pngcs.PngReader.ReadRowByte().
ReadRowsInt() [1/2]
ImageLines Hjg.Pngcs.PngReader.ReadRowsInt (int rowOffset, int nRows, int rowStep) inline
Definition at line 763 of file PngReader.cs.
         {
             if (nRows < 0)
             {
                 nRows = (ImgInfo.Rows - rowOffset) / rowStep;
             }
             if (rowStep < 1
                 || rowOffset < 0
                 || (nRows * rowStep) + rowOffset > ImgInfo.Rows)
             {
                 throw new PngjInputException("bad args");
             }
             var imlines = new ImageLines(ImgInfo, ImageLine.ESampleType.INT, unpackedMode, rowOffset, nRows, rowStep);
             if (!Interlaced)
             {
                 for (var j = 0; j < ImgInfo.Rows; j++)
                 {
                     var bytesread = ReadRowRaw(j); // read and perhaps discards
                     var mrow = imlines.ImageRowToMatrixRowStrict(j);
                     if (mrow >= 0)
                     {
                         DecodeLastReadRowToInt(imlines.Scanlines[mrow], bytesread);
                     }
                 }
             }
             else
             { // and now, for something completely different (interlaced)
                 var buf = new int[unpackedMode ? ImgInfo.SamplesPerRow : ImgInfo.SamplesPerRowPacked];
                 for (var p = 1; p <= 7; p++)
                 {
                     deinterlacer.SetPass(p);
                     for (var i = 0; i < deinterlacer.GetRows(); i++)
                     {
                         var bytesread = ReadRowRaw(i);
                         var j = deinterlacer.GetCurrRowReal();
                         var mrow = imlines.ImageRowToMatrixRowStrict(j);
                         if (mrow >= 0)
{
                             DecodeLastReadRowToInt(buf, bytesread);
                             deinterlacer.DeinterlaceInt(buf, imlines.Scanlines[mrow], !unpackedMode);
                         }
                     }
                 }
             }
             End();
             return imlines;
         }
References Hjg.Pngcs.PngReader.DecodeLastReadRowToInt(), Hjg.Pngcs.PngDeinterlacer.DeinterlaceInt(), Hjg.Pngcs.PngReader.deinterlacer, Hjg.Pngcs.PngReader.End(), Hjg.Pngcs.PngDeinterlacer.GetCurrRowReal(), Hjg.Pngcs.PngDeinterlacer.GetRows(), Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.Interlaced, Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.ImageInfo.Rows, Hjg.Pngcs.ImageInfo.SamplesPerRow, Hjg.Pngcs.ImageInfo.SamplesPerRowPacked, Hjg.Pngcs.PngDeinterlacer.SetPass(), and Hjg.Pngcs.PngReader.unpackedMode.
ReadRowsInt() [2/2]
ImageLines Hjg.Pngcs.PngReader.ReadRowsInt () inline
Definition at line 814 of file PngReader.cs.
         {
             return ReadRowsInt(0, ImgInfo.Rows, 1);
         }
References Hjg.Pngcs.PngReader.ImgInfo, and Hjg.Pngcs.ImageInfo.Rows.
Referenced by Hjg.Pngcs.PngReader.ReadRowInt().
ReadSkippingAllRows()
void Hjg.Pngcs.PngReader.ReadSkippingAllRows () inline
Definition at line 941 of file PngReader.cs.
         {
             if (FirstChunksNotYetRead())
             {
                 ReadFirstChunks();
             }
             // we read directly from the compressed stream, we dont decompress nor chec CRC
             iIdatCstream.DisableCrcCheck();
             try
             {
                 int r;
                 do
                 {
                     r = iIdatCstream.Read(rowbfilter, 0, rowbfilter.Length);
                 } while (r >= 0);
             }
             catch (IOException e)
             {
                 throw new PngjInputException("error in raw read of IDAT", e);
             }
             offset = iIdatCstream.GetOffset();
             if (offset < 0)
             {
                 throw new PngjInternalException("bad offset ??" + offset);
             }
             if (MaxTotalBytesRead > 0 && offset >= MaxTotalBytesRead)
             {
                 throw new PngjInputException("Reading IDAT: Maximum total bytes to read exceeeded: " + MaxTotalBytesRead
                         + " offset:" + offset);
             }
             ReadLastAndClose();
         }
References Hjg.Pngcs.PngIDatChunkInputStream.DisableCrcCheck(), Hjg.Pngcs.PngReader.FirstChunksNotYetRead(), Hjg.Pngcs.PngIDatChunkInputStream.GetOffset(), Hjg.Pngcs.PngReader.iIdatCstream, Hjg.Pngcs.PngReader.MaxTotalBytesRead, Hjg.Pngcs.PngReader.offset, Hjg.Pngcs.PngIDatChunkInputStream.Read(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadLastAndClose(), and Hjg.Pngcs.PngReader.rowbfilter.
SetUnpackedMode()
void Hjg.Pngcs.PngReader.SetUnpackedMode (bool unPackedMode) inline
Definition at line 1000 of file PngReader.cs.
         {
             unpackedMode = unPackedMode;
         }
References Hjg.Pngcs.PngReader.unpackedMode.
ToString()
override string Hjg.Pngcs.PngReader.ToString () inline
Definition at line 978 of file PngReader.cs.
         { // basic info
             return "filename=" + filename + " " + ImgInfo.ToString();
         }
References Hjg.Pngcs.PngReader.filename, Hjg.Pngcs.PngReader.ImgInfo, and Hjg.Pngcs.ImageInfo.ToString().
UnfilterRow()
void Hjg.Pngcs.PngReader.UnfilterRow (int nbytes) inline private
Definition at line 281 of file PngReader.cs.
         {
             int ftn = rowbfilter[0];
             var ft = (FilterType)ftn;
             switch (ft)
             {
                 case Hjg.Pngcs.FilterType.FILTER_NONE:
                 UnfilterRowNone(nbytes);
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_SUB:
                 UnfilterRowSub(nbytes);
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_UP:
                 UnfilterRowUp(nbytes);
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_AVERAGE:
                 UnfilterRowAverage(nbytes);
                 break;
                 case Hjg.Pngcs.FilterType.FILTER_PAETH:
                 UnfilterRowPaeth(nbytes);
                 break;
                 default:
                 throw new PngjInputException("Filter type " + ftn + " not implemented");
             }
         }
References Hjg.Pngcs.PngReader.rowbfilter, Hjg.Pngcs.PngReader.UnfilterRowAverage(), Hjg.Pngcs.PngReader.UnfilterRowNone(), Hjg.Pngcs.PngReader.UnfilterRowPaeth(), Hjg.Pngcs.PngReader.UnfilterRowSub(), and Hjg.Pngcs.PngReader.UnfilterRowUp().
Referenced by Hjg.Pngcs.PngReader.ReadRowRaw().
UnfilterRowAverage()
void Hjg.Pngcs.PngReader.UnfilterRowAverage (int nbytes) inline private
Definition at line 312 of file PngReader.cs.
         {
             int i, j, x;
             for (j = 1 - ImgInfo.BytesPixel, i = 1; i <= nbytes; i++, j++)
             {
                 x = (j > 0) ? rowb[j] : 0;
                 rowb[i] = (byte)(rowbfilter[i] + ((x + (rowbprev[i] & 0xFF)) / 2));
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPixel, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.rowb, Hjg.Pngcs.PngReader.rowbfilter, and Hjg.Pngcs.PngReader.rowbprev.
Referenced by Hjg.Pngcs.PngReader.UnfilterRow().
UnfilterRowNone()
void Hjg.Pngcs.PngReader.UnfilterRowNone (int nbytes) inline private
Definition at line 322 of file PngReader.cs.
         {
             for (var i = 1; i <= nbytes; i++)
             {
                 rowb[i] = rowbfilter[i];
             }
         }
References Hjg.Pngcs.PngReader.rowb, and Hjg.Pngcs.PngReader.rowbfilter.
Referenced by Hjg.Pngcs.PngReader.UnfilterRow().
UnfilterRowPaeth()
void Hjg.Pngcs.PngReader.UnfilterRowPaeth (int nbytes) inline private
Definition at line 330 of file PngReader.cs.
         {
             int i, j, x, y;
             for (j = 1 - ImgInfo.BytesPixel, i = 1; i <= nbytes; i++, j++)
             {
                 x = (j > 0) ? rowb[j] : 0;
                 y = (j > 0) ? rowbprev[j] : 0;
                 rowb[i] = (byte)(rowbfilter[i] + PngHelperInternal.FilterPaethPredictor(x, rowbprev[i], y));
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPixel, Hjg.Pngcs.PngHelperInternal.FilterPaethPredictor(), Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.rowb, Hjg.Pngcs.PngReader.rowbfilter, and Hjg.Pngcs.PngReader.rowbprev.
Referenced by Hjg.Pngcs.PngReader.UnfilterRow().
UnfilterRowSub()
void Hjg.Pngcs.PngReader.UnfilterRowSub (int nbytes) inline private
Definition at line 341 of file PngReader.cs.
         {
             int i, j;
             for (i = 1; i <= ImgInfo.BytesPixel; i++)
             {
                 rowb[i] = rowbfilter[i];
             }
             for (j = 1, i = ImgInfo.BytesPixel + 1; i <= nbytes; i++, j++)
             {
                 rowb[i] = (byte)(rowbfilter[i] + rowb[j]);
             }
         }
References Hjg.Pngcs.ImageInfo.BytesPixel, Hjg.Pngcs.PngReader.ImgInfo, Hjg.Pngcs.PngReader.rowb, and Hjg.Pngcs.PngReader.rowbfilter.
Referenced by Hjg.Pngcs.PngReader.UnfilterRow().
UnfilterRowUp()
void Hjg.Pngcs.PngReader.UnfilterRowUp (int nbytes) inline private
Definition at line 355 of file PngReader.cs.
         {
             for (var i = 1; i <= nbytes; i++)
             {
                 rowb[i] = (byte)(rowbfilter[i] + rowbprev[i]);
             }
         }
References Hjg.Pngcs.PngReader.rowb, Hjg.Pngcs.PngReader.rowbfilter, and Hjg.Pngcs.PngReader.rowbprev.
Referenced by Hjg.Pngcs.PngReader.UnfilterRow().
Member Data Documentation
bytesChunksLoaded
int Hjg.Pngcs.PngReader.bytesChunksLoaded = 0 private
Definition at line 136 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.ReadChunk().
chunksList
readonly ChunksList Hjg.Pngcs.PngReader.chunksList private
Read chunks
Definition at line 94 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.GetChunksList(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), and Hjg.Pngcs.PngReader.ReadFirstChunks().
deinterlacer
readonly PngDeinterlacer Hjg.Pngcs.PngReader.deinterlacer private
Definition at line 119 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.ReadRowsByte(), and Hjg.Pngcs.PngReader.ReadRowsInt().
disposedValue
bool Hjg.Pngcs.PngReader.disposedValue = false private
Definition at line 1006 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.Dispose().
filename
readonly string Hjg.Pngcs.PngReader.filename private
filename, or description - merely informative, can be empty
Definition at line 40 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.PngReader(), and Hjg.Pngcs.PngReader.ToString().
idatIstream
internal AZlibInputStream Hjg.Pngcs.PngReader.idatIstream private
Definition at line 139 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.Close(), Hjg.Pngcs.PngReader.Dispose(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadLastAndClose(), and Hjg.Pngcs.PngReader.ReadRowRaw().
iIdatCstream
internal PngIDatChunkInputStream Hjg.Pngcs.PngReader.iIdatCstream private
Definition at line 140 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.Dispose(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadLastChunks(), Hjg.Pngcs.PngReader.ReadRowRaw(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
imgLine
ImageLine Hjg.Pngcs.PngReader.imgLine private
buffer: last read line
Definition at line 99 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.ReadRow(), Hjg.Pngcs.PngReader.ReadRowByte(), and Hjg.Pngcs.PngReader.ReadRowInt().
inputStream
readonly Stream Hjg.Pngcs.PngReader.inputStream private
Definition at line 138 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.Close(), Hjg.Pngcs.PngReader.Dispose(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngReader.ReadFirstChunks(), and Hjg.Pngcs.PngReader.ReadLastChunks().
metadata
readonly PngMetadata Hjg.Pngcs.PngReader.metadata private
A high level wrapper of a ChunksList : list of read chunks
Definition at line 89 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.GetMetadata(), and Hjg.Pngcs.PngReader.PngReader().
offset
long Hjg.Pngcs.PngReader.offset = 0 private
Definition at line 135 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadLastChunks(), Hjg.Pngcs.PngReader.ReadRowRaw(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
rowb
byte [] Hjg.Pngcs.PngReader.rowb private
raw current row, as array of bytes,counting from 1 (index 0 is reserved for filter type)
Definition at line 104 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.DecodeLastReadRowToByte(), Hjg.Pngcs.PngReader.DecodeLastReadRowToInt(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.UnfilterRowAverage(), Hjg.Pngcs.PngReader.UnfilterRowNone(), Hjg.Pngcs.PngReader.UnfilterRowPaeth(), Hjg.Pngcs.PngReader.UnfilterRowSub(), and Hjg.Pngcs.PngReader.UnfilterRowUp().
rowbfilter
readonly byte [] Hjg.Pngcs.PngReader.rowbfilter private
raw current row, after unfiltered
Definition at line 114 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.ReadSkippingAllRows(), Hjg.Pngcs.PngReader.UnfilterRow(), Hjg.Pngcs.PngReader.UnfilterRowAverage(), Hjg.Pngcs.PngReader.UnfilterRowNone(), Hjg.Pngcs.PngReader.UnfilterRowPaeth(), Hjg.Pngcs.PngReader.UnfilterRowSub(), and Hjg.Pngcs.PngReader.UnfilterRowUp().
rowbprev
byte [] Hjg.Pngcs.PngReader.rowbprev private
previuos raw row
Definition at line 109 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.UnfilterRowAverage(), Hjg.Pngcs.PngReader.UnfilterRowPaeth(), and Hjg.Pngcs.PngReader.UnfilterRowUp().
rowNum
int Hjg.Pngcs.PngReader.rowNum = -1 private
last read row number
Definition at line 133 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), and Hjg.Pngcs.PngReader.ReadRowRaw().
skipChunkIdsSet
Dictionary<string, int> Hjg.Pngcs.PngReader.skipChunkIdsSet = null private
Definition at line 84 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.ReadChunk().
unpackedMode
bool Hjg.Pngcs.PngReader.unpackedMode = false private
Definition at line 122 of file PngReader.cs.
Referenced by Hjg.Pngcs.PngReader.DecodeLastReadRowToByte(), Hjg.Pngcs.PngReader.DecodeLastReadRowToInt(), Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), Hjg.Pngcs.PngReader.ReadRowsByte(), Hjg.Pngcs.PngReader.ReadRowsInt(), and Hjg.Pngcs.PngReader.SetUnpackedMode().
Property Documentation
ChunkLoadBehaviour
ChunkLoadBehaviour Hjg.Pngcs.PngReader.ChunkLoadBehaviour get set
Strategy for chunk loading. Default: LOAD_CHUNK_ALWAYS
Definition at line 45 of file PngReader.cs.
 { get; set; }
CurrentChunkGroup
int Hjg.Pngcs.PngReader.CurrentChunkGroup get private set
number of chunk group (0-6) last read, or currently reading
see ChunksList.CHUNK_GROUP_NNN
Definition at line 128 of file PngReader.cs.
 { get; private set; }
Referenced by Hjg.Pngcs.PngReader.Close(), Hjg.Pngcs.PngWriter.CopyChunks(), Hjg.Pngcs.PngReader.End(), Hjg.Pngcs.PngReader.FirstChunksNotYetRead(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadLastAndClose(), and Hjg.Pngcs.PngReader.ReadLastChunks().
ImgInfo
ImageInfo Hjg.Pngcs.PngReader.ImgInfo get
Basic image info, inmutable
Definition at line 35 of file PngReader.cs.
 { get; }
Referenced by Hjg.Pngcs.PngReader.DecodeLastReadRowToByte(), Hjg.Pngcs.PngReader.DecodeLastReadRowToInt(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngReader.ReadFirstChunks(), Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.ReadRowsByte(), Hjg.Pngcs.PngReader.ReadRowsInt(), Hjg.Pngcs.PngReader.ToString(), Hjg.Pngcs.PngReader.UnfilterRowAverage(), Hjg.Pngcs.PngReader.UnfilterRowPaeth(), and Hjg.Pngcs.PngReader.UnfilterRowSub().
Interlaced
bool Hjg.Pngcs.PngReader.Interlaced get
Definition at line 117 of file PngReader.cs.
 { get; }
Referenced by Hjg.Pngcs.PngReader.IsInterlaced(), Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadRowByte(), Hjg.Pngcs.PngReader.ReadRowInt(), Hjg.Pngcs.PngReader.ReadRowRaw(), Hjg.Pngcs.PngReader.ReadRowsByte(), and Hjg.Pngcs.PngReader.ReadRowsInt().
MaxBytesMetadata
long Hjg.Pngcs.PngReader.MaxBytesMetadata get set
Maximum amount of bytes from ancillary chunks to load in memory
Default: 5MB. 0: unlimited. If exceeded, chunks will be skipped
Definition at line 58 of file PngReader.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngReader.PngReader(), and Hjg.Pngcs.PngReader.ReadChunk().
MaxTotalBytesRead
long Hjg.Pngcs.PngReader.MaxTotalBytesRead get set
Maximum total bytes to read from stream
Default: 200MB. 0: Unlimited. If exceeded, an exception will be thrown
Definition at line 66 of file PngReader.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngReader.PngReader(), Hjg.Pngcs.PngReader.ReadChunk(), Hjg.Pngcs.PngReader.ReadRowRaw(), and Hjg.Pngcs.PngReader.ReadSkippingAllRows().
ShouldCloseStream
bool Hjg.Pngcs.PngReader.ShouldCloseStream get set
Should close the underlying Input Stream when ends?
Definition at line 50 of file PngReader.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngReader.Close(), and Hjg.Pngcs.PngReader.PngReader().
SkipChunkIds
string [] Hjg.Pngcs.PngReader.SkipChunkIds get set
Ancillary chunks to skip
Default: { "fdAT" }. chunks with these ids will be skipped (nor even CRC checked)
Definition at line 82 of file PngReader.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngReader.PngReader(), and Hjg.Pngcs.PngReader.ReadChunk().
SkipChunkMaxSize
int Hjg.Pngcs.PngReader.SkipChunkMaxSize get set
Maximum ancillary chunk size
Default: 2MB, 0: unlimited. Chunks exceeding this size will be skipped (nor even CRC checked)
Definition at line 74 of file PngReader.cs.
 { get; set; }
Referenced by Hjg.Pngcs.PngReader.PngReader(), and Hjg.Pngcs.PngReader.ReadChunk().
The documentation for this class was generated from the following file:
C:/Users/smcbeth.DLS-INC/Projects/Yarrow/Juniper/src/Juniper.Client/ThirdParty/HjgPngcs/PngReader.cs